### ISSUE TITLE
Zube automation keeps reopening issues

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#10009]
# Description

In some cases (e.g. https://github.com/rancher/dashboard/issues/9683) Zube keeps reopening issues after PRs get merged.

**Comment by richard-cox** [comment]
The github bot re-opened 9683 correctly after the merge of the PR. things were a bit different then, but i think from now...
- issues labelled as QA/None are not re-opened (to check)
- issues labelled as QA/Dev Automation are re-opened and moved in to the QA Review zube column
- all other issues are re-opened and moved to the To Test zube column

**Comment by nwmac** [comment]
Can we close this and re-open when we see it again - the GH Bot should move issues that are dev-automation to the new 'QA Review' pipeline in Zube.
