### ISSUE TITLE
[back port to v2.8.0] Charts carousel shows a number after the chart name

### ISSUE THREAD

**Issue by bisht-richa** [rancher/dashboard#10002]
**Setup**
- Rancher version: v2.8.0
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

The charts carousel shows the position of the card next to the chart name

**To Reproduce**

Go to  Cluster --> Apps --> Charts
**Result**

**Expected Result**

Charts carousel title should not have slider numbers at the end
**Screenshots**

**Additional context**

**Comment by richard-cox** [comment]
This is a trivial change that we need to visually validate once merged
