### ISSUE TITLE
When installing the Windows GMSA chart, the two `Credential Spec` buttons are not sized the same

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#10000]
**Setup**
- Rancher version: `v2.7.7`
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

When installing the `Windows gMSA` chart in a downstream RKE2 custom cluster, you see the following screen right before installation:

<img width="1271" alt="image" src="https://github.com/rancher/dashboard/assets/52591819/092cf99b-cef0-4df5-9bc7-31c4a1de89ea">

The second button, when compared to the first, looks condensed and odd. It should be an exact match to the first button for consistency.

**To Reproduce**

1. As a standard user, provision a downstream RKE2 custom cluster (I had 3 etcd, 1 cp, 2 Linux workers, 4 Windows workers).
2. Navigate to cluster explorer > cluster > Apps > Repositories.
3. Add the `https://github.com/rancher/Rancher-Plugin-gMSA` repo with the `main` branch.
4. Attempt to install the `Windows gMSA` branch; note that the buttons do not match at the end of chart installation.

**Result**
The buttons mismatch prior to installing the `Windows GMSA` chart.

**Expected Result**

The buttons should not mismatch prior to installing the `Windows GMSA` chart.

**Comment by kwwii** [comment]
1) Check that this chart uses the correct labels and descriptions in the questions
2) Fix the size error in the checkbox component for containers which exceed the expected width

**Comment by cnotv** [comment]
The issue is related to the checkbox component. A unit test ensuring the min width of the element can be added using the Jest dom library.

Add `flex-shrink: 0;` to `.checkbox-container .checkbox-custom`.

This is the view on Storybook:

![Screenshot 2024-02-07 at 17 54 30](https://github.com/rancher/dashboard/assets/5009481/a18e05db-92d1-45e3-9bd7-68642e60a5d6)

**Comment by gaktive** [comment]
Rancher Desktop saw something similar in https://github.com/rancher-sandbox/rancher-desktop/issues/6003

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.8-head` https://github.com/rancher/rancher/commit/8e774331d732ea6b1539eafad637568c2e5e7870.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/8e774331d732ea6b1539eafad637568c2e5e7870

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|Windows gMSA Credential Spec buttons mismatch|Validate that the Credential Spec buttons do not mismatch in the Windows gMSA chart|:white_check_mark:|

**VALIDATION STEPS**
1. Navigated to local cluster > Cluster Explorer > Apps > Repositories.
2. Added repo for Rancher gMSA.
3. Attempted to install the Windows gMSA and correctly see the Credential Spec buttons match:
![image](https://github.com/rancher/dashboard/assets/52591819/95eac7b1-b8c1-44f8-b105-8ddf41636821)
