### ISSUE TITLE
After Clicking on hyperlink on Workload create page, user is navigated to create workload page.

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1001]
**On master-head - commit id: `28ea6d4b1`**

- Login to Dashboard --> Workloads Overview --> Create
- Click on a hyperlink for say Deployment type workload "Deployments"
<img width="1629" alt="Screen Shot 2020-08-11 at 12 04 23 PM" src="https://user-images.githubusercontent.com/26032343/89938320-314a0500-dbcb-11ea-8ddc-bc9da1d1ae76.png">

- A new window is opened with info about deployments
- Dashboard page, user is navigated to "Create Deployment" page

**Expected:**
User Should be in `Workloads Overview --> Create` page only and NOT be taken to create deployment page as the user has clicked on a hyperlink only.

**Comment by vincent99** [comment]
I also moved them to the end of the text as "more info" because some people were gravitating to clicking on it at the beginning of the sentence even when they just wanted to select the type.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `33f755f18`**

- Dashboard --> Workloads --> Overview --> Create --> More info hyperlink is available
- Clicking on it takes the user to Deployments page in kubernetes docs.

<img width="1408" alt="Screen Shot 2020-09-17 at 2 06 00 PM" src="https://user-images.githubusercontent.com/26032343/93528419-27fd3800-f8ef-11ea-84dd-1d0dce29f40b.png">
