### ISSUE TITLE
App bar does not highlight current cluster when product is not explorer

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10010]
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
- The app bar cluster icon should be highlighted when the user is in the cluster explorer context
- When navigating to a non explorer product part of cluster explorer the cluster icon highlight is removed

**To Reproduce**
- Install a chart to a cluster, suggest something simple like CIS Benchmark
- Navigate to the CIS Benchmark side nav menu group

**Result**
- The highlight of the selected cluster is removed

**Expected Result**
- Highlight remains

**Screenshots**
Correct state
![image](https://github.com/rancher/dashboard/assets/18697775/58d2fe17-fb82-464e-a518-fee4a6e179c3)

Incorrect state
![image](https://github.com/rancher/dashboard/assets/18697775/40fe44ce-3d4e-4c5b-9bc6-c0dd0106a793)

**Additional context**
- state works off of nuxt's `nuxt-link-active` class
- this works from the c-cluster-explorer route, which is product specific
- so going to other products in the explorer view fails, so something like c-cluster-cis

**Comment by izaac** [comment]
Reviewing the changes to existing tests to add support of identifying the highlighting on the menu by the context path looks good for the local cluster coverage.
