### ISSUE TITLE
Warning text is red instead of yellow

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10018]
**Setup**
- Rancher version: 2.6

**Describe the bug**
The text-warning colour was changed from red to yellow via https://github.com/rancher/dashboard/pull/3067/files#diff-dccc2098aa1f09e2bca606b45d8e7310ce632ce5c9d930cabc0b68b703f1ec3dL217 ([PR](https://github.com/rancher/dashboard/pull/3067), [Issue](https://github.com/rancher/dashboard/issues/2360))

This should have remained `--warning`. 

We also need to consider where the yellow text is on a white background and becomes illegible, so this needs a bit of investigation
 
**To Reproduce**
Discovered during hack week, whoever picks this up needs to find a couple of places where text-warning is easily seen and update these steps

**Result**
- warning text is shown as red

**Expected Result**
- warning text is shown as yellow and is clearly legible

**Comment by yonasberhe23** [comment]
e2e tests are sufficient. moving to done cc: @izaac
