### ISSUE TITLE
Easily discover expiration details of Certificates

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10025]
**Is your feature request related to a problem? Please describe.**
- Currently the expiration for a certificate is shown in two places
  - Secrets Lists - In a column full of text. There's no sort on this
  - Secret Detail Page - In the header
  - Note - The date is in red if expired, and also red if expiring (see https://github.com/rancher/dashboard/issues/10018P)
- This is clear to the user if they see it for specific secrets, but they are unable to easily discover these 

![image](https://github.com/rancher/dashboard/assets/18697775/eab1969a-fc9a-44e0-ac77-079b704d6458)

![image](https://github.com/rancher/dashboard/assets/18697775/3e8c403a-0c8c-4518-9847-ded246a0a03e)

**Describe the solution you'd like**
- Add a list view where users can see only cert secrets
- Allow the user to easily see which certificates are expiring or have expired
- I've taken a stab at this in https://github.com/rancher/dashboard/pull/10024

**Additional context**
- This was done as part of hackweek, so hasn't gone down the usual UX design path. Need to consider this before merging

**Comment by richard-cox** [comment]
@kwwii / @edenhernandez-suse I did this as part of hackweek, so the UX is developer created. There's a [PR](https://github.com/rancher/dashboard/pull/10024) up with a screenshot. I'll bump this issue to your side for a review. If it looks fine, then I try and get it merged for 2.8next1

**Comment by kwwii** [comment]
Looks good for an initial implementation. We can tweak how we are showing this kind of information later if necessary.

**Comment by aalves08** [comment]
Added to possible `automation-candidate` as we can mock a cluster already (https://github.com/rancher/dashboard/blob/master/cypress/e2e/blueprints/nav/fake-cluster.ts), so we should "fake" some data in order to assert expiration dates, banners, etc

**Comment by izaac** [comment]
E2E looks good to me moving to Done
