### ISSUE TITLE
Cluster credentials: duplicate names possible but not working

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10020]
Internal reference: SURE-6920
Reported in 2.7.5

Issue description:
It is possible in the Rancher GUI to create a cluster credential with an identical name to an already existing one. Then it is listed twice in the selection menu. It can even be selected but it seems never to be used.

Use case:
The user wanted to replace a cluster credential for a Harvester cluster which was not working anymore (reason unclear and not subject to this case).

They created a second one with the same name and selected it to be the new credential, but cluster access was still not working. Obviously, the old one was still used.

The only way to replace the old cloud credential was to create a new one with a different name and assign it to the existing cluster.

This should either not be possible to create or it should work with both credentials. 

Business impact:
There is a UI bug where someone can create a cluster credential with the name of an already existing credential. It seems the older one is then used anyway. There should be a validation that prevents re-use of the same name or both credentials should work when selected. 

Troubleshooting steps:
On a cluster with nonworking cloud credentials, a new one has been created with the same name. However, the new one was never used. It looks like the name is used for finding the object and the first one found (in this case older) is always used.

Repro steps:

In Rancher UI create a cloud credential with the same name as the existing one
Select a new credential when starting the cluster

Workaround:
None

Actual behavior:
It is possible to create a cloud credential with the name of the existing one. But then once selected during cluster creation it is not used

Expected behavior:
It should either not be possible to create a cloud credential with the name of an existing credential or it should be possible the one that was selected.

**Comment by richard-cox** [comment]
If the API allows it (i.e. someone creates creds externally with matching names), should we instead of blocking it, make it obvious that the creds are different (for example change display name to include id)?

**Comment by nwmac** [comment]
Had a quick look and was not able to easily reproduce this - at least for RKE2, seems like we are correctly using the credential ID and not the name.

**Comment by gaktive** [comment]
This may be Harvester specific, or at least that area would provide the easiest way to understand what's going on.

**Comment by richard-cox** [comment]
It's worth noting that we cannot validate the credential name is truly unique. It's optional and also the user may not be able to see all credentials. This has been taken into account in the solution in the associated PR

**Comment by izaac** [comment]
I did a manual pass to understand the coverage and it looks good tome. cc @yonasberhe23

**Comment by yonasberhe23** [comment]
Thank you @izaac! moving to Done
