### ISSUE TITLE
[BUG] Cannot read properties of undefined 

### ISSUE THREAD

**Issue by vladaman** [rancher/dashboard#10023]
Rancher | v2.7.6
-- | --
Dashboard | v2.7.6
Helm | v2.16.8-rancher2
Machine | v0.15.0-rancher100

**Describe the bug**
With clean installed Rancher we face UI bug. Navigating to More Resources - Rancher - Nodes - Create displays the following error:
`Cannot read properties of undefined (reading 'displayName')`

**Screenshots**
![image](https://github.com/rancher/rancher/assets/907206/c907e5ab-4c6d-4c0f-9b99-aa57acea8fe6)

**Comment by richard-cox** [comment]
Not reproducible in 2.9-head, closing.

The type of error page in the screenshot was also spuriously shown and has been addressed in I think 2.8.x. That would allow the user to continue using the ui
