### ISSUE TITLE
Add support for Bandwidth Manager config for Cilium

### ISSUE THREAD

**Issue by masap** [rancher/dashboard#10049]
**Is your feature request related to a problem? Please describe.**

A customer requests to add support for Bandwidth Manager config for Cilium with SURE-7195.

**Describe the solution you'd like**

Please add the functionality.

**Describe alternatives you've considered**

By editing YAML, we can configure it.

**Additional context**

**Comment by izaac** [comment]
This would be a good candidate for Manual testing on real clusters.

**Comment by yonasberhe23** [comment]
Tested in 
- v2.9-81337b95660cba868629d6fe769bd7e8242b5aee-head
- master 3da1205

Scenario | Result
-- | --
Setting is sent to the backend | ✅
RKE2 cluster creation w/ setting enabled is successful | ✅
RKE2 cluster edit w/ setting enabled is successful | ✅
RKE2 cluster creation w/ setting disabled is successful | ✅
RKE2 cluster edit w/ setting disabled is successful | ✅
RKE2 cluster edit w/ setting enabled to disabled | ✅
RKE2 cluster edit w/ setting disabled to enabled | ✅
