### ISSUE TITLE
Regression: UI no longer allows for configuration of Grafana requests and limits

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10042]
Internal reference: SURE-7089
Reported in 2.7.6

Issue description:
The UI no longer allows for the configuration of Grafana limits and requests

Impact:
The user runs a dev cluster, which is imperative to the production of their product and the developers losing access to the metrics on their deployments prevents them from being able to complete necessary tests.  As the fields were not visible, they didn't realize Prometheus configurations didn't apply to all the pods, including Grafana, so what would have been addressed in their initial deployment ended up causing intermittent issues for his users for what may have been months. 

Troubleshooting steps:

After observing that Grafana was using more than its limits allowed, they modified the manifests directly to add better requests and limits.  

Repro steps:

    Edit Monitoring App in the UI

Workaround:
Modify as YAML

![grafana-limits.png](https://zube.io/files/rancher/07dd8cf5ec6c976dd1139a0e4f668075-grafana-limits.png)

Expected behavior:
There used to be fields here for the modification of requests and limits. Since user count and dashboards will constantly change over the span of the Apps years of life in the cluster, this requires periodic tuning.  As such, these are as important part of the configuration of Grafana as Grafana's storage configuration and should be re-exposed to the users.

**Comment by yonasberhe23** [comment]
Automation reviewed. The test code included in the PR has sufficient test automation coverage. Moving to 'Done'
