### ISSUE TITLE
kubelet args do not show up in the Advanced tab

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10045]
Internal reference: SURE-7211
Reported in 2.7.4

Issue description:

Kubelet args do not show up in the advanced tab after they are applied using Terraform

Business impact:

Don't have a way to know what is already configured for the kubelete args

Troubleshooting steps:

    Checked that the TF ran successfully without any issues;
    Checked that it was applied;
    checked that edit as yaml (cluster yaml) for that cluster has the right args that were configured

Repro steps:

    TF code to modify kubelet-arg
    Apply the code
    Confirm that the config has been applied
    Going in the rancher UI, under "Advanced", kubelet args are not showing up

![1699287965_1.png](https://zube.io/files/rancher/343209722d77e9434fd6f14a7c19c897-1699287965_1.png)

Workaround:
Check the config as yaml

Actual behavior:
The kubelet args do appear the UI

Expected behavior:
The kubelet args are not showing from the UI

**Comment by gaktive** [comment]
Possible connection with #9988

**Comment by nwmac** [comment]
Terraform puts the global args in a different place to where the UI expects them - it needs to be updated to be aware of the other location.

**Comment by torchiaf** [comment]
@izaac @momesgin should we close this and open a new issue to track the missing E2E tests ?

**Comment by momesgin** [comment]
@torchiaf I'm working on manually testing this, I believe that would be sufficient enough to close, @yonasberhe23 ?

**Comment by yonasberhe23** [comment]
@momesgin correct, you can close this once the fix is verified

**Comment by momesgin** [comment]
My QA process to test this:

First I created a DO cluster using Terraform without providing `machine_selector_config` or `machine_global_config`,

then I added `machine_selector_config`:
```
    machine_selector_config {
      machine_label_selector{
        match_labels = {
          "mo-from-terraform" = "test-machine-selector-config"
        }
      }
    }
```
and the result:
![image](https://github.com/rancher/dashboard/assets/135728925/34efa61e-9b90-4d41-955c-a51127ae5e71)

in the next step I added `machine_global_config`:
```
    machine_global_config = <<EOF
     kubelet-arg:
       - pippo
    EOF
```
and the result:
![image](https://github.com/rancher/dashboard/assets/135728925/1d50b551-e65c-4585-b2b6-7c270a4d463e)

and finally I updated both:
```
    machine_selector_config {
      machine_label_selector{
        match_labels = {
          "mo-from-terraform-2" = "test-machine-selector-config"
        }
      }
    }
    machine_global_config = <<EOF
     kubelet-arg:
       - pippo2
    EOF
```
and got the desired result:
![image](https://github.com/rancher/dashboard/assets/135728925/c6d131f4-8b15-4d4b-ab61-ccdebbecd740)
