### ISSUE TITLE
Custom Istio Deployment Page: Rework with feedback

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#1005]
Per internal demo discussion on 08/07/2020 the following changes are needed:

- Remove custom answers section, and add the ability to edit the values.yaml values via a yaml edit option

- Move Advanced Options Overlay File from initial install page to be its own option on the left.
  - Have a better description for the overlay file section - "The overlay file allows for additional configuration on top of the base rancher istio installation. You can utilize the [IstioOperator api ](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/)to make changes and additions for all components and apply those changes via this overlay yaml."
  - Provide a link out to istio documentation for what an overlay file is (not sure what the best way to keep this up to date since it will change with each release) (current potential link option: https://istio.io/latest/docs/setup/install/istioctl/#customizing-the-configuration ) 
  - Have a greyed out example of an overlay file 

- Allow for annotation on the installer job pod to bubble up logs

**Comment by brendarearden** [comment]
https://github.com/brendarearden/charts/blob/phase2/packages/rancher-istio/charts/samples/overlay-example.yaml << current location of example overlay yaml, but the url will update when merged into rancher/charts, but the `rancher-istio/charts/samples/overlay-example.yaml` path will stay the same

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.0-alpha1

* Istio page shows the correct components
* Overlay file editor is shown with an example
* Values YAML editor is shown
* Helm options are shown
* Logs are shown from the installer after installing
