### ISSUE TITLE
[BUG] configmap formatting breaking on creation/edit

### ISSUE THREAD

**Issue by stonemantlearg** [rancher/dashboard#10066]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option (Docker install/Helm Chart):
- If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm

**Information about the Cluster**
- Kubernetes version: v1.24.15
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): EKS

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

**Describe the bug**
Creating or modifying a configmap from UI breaks formatting/adds empty lines

**To Reproduce**
Create a configmap
Add a key-value pair, with a long enough value (around 1000 lines seems to be enough to trigger)
Save the changes
Read the configmap value

**Result**
Configmap value formatting is different, line breaks get added randomly.

**Expected Result**
Configmap value should be exactly as input.

**Screenshots**
Left is input, right is what Rancher stored in the configmap
![MicrosoftTeams-image (17)](https://github.com/rancher/rancher/assets/46874666/38fd554b-c054-417f-970b-c205898ecbb2)

**Comment by bromine0x23** [comment]
> > I'm pretty sure this is caused by [this line](https://github.com/rancher/dashboard/commit/f04ad9c1cf582ca5ffb4eb7387ffc8bb2ebc9510#diff-5cf4eab2e7126559d21cb7359a67e030edc4332eafd9411598f9cdc048afa14cL37) which calls [this](https://github.com/rancher/dashboard/commit/f04ad9c1cf582ca5ffb4eb7387ffc8bb2ebc9510#diff-923894aa1addf785608a0acae313a41d20794b7dbf3775fa421d756b172dd836R348) added in [rancher/dashboard#7670](https://github.com/rancher/dashboard/pull/7670).
> > Possibly related [nodeca/js-yaml#464](https://github.com/nodeca/js-yaml/issues/464). Changing the `steve/actions.js` line to the below appears to avoid the line wrapping issue.
> > ```js
> > return jsyaml.dump(obj, { lineWidth: -1 });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm still trying to understand what fields steve is adding that requires this function, but this seems like it could have been avoided if steve passed these parameters separately without modifying the YAML output.
> 
> Correct. The line break is after 80 chars. Same as in [dumper.js](https://github.com/nodeca/js-yaml/blob/0d3ca7a27b03a6c974790a30a89e456007d62976/lib/dumper.js#L123)

I'm using v2.7.1, and this seems work for me.

**Comment by bromine0x23** [comment]
> I'm pretty sure this is caused by [this line](https://github.com/rancher/dashboard/commit/f04ad9c1cf582ca5ffb4eb7387ffc8bb2ebc9510#diff-5cf4eab2e7126559d21cb7359a67e030edc4332eafd9411598f9cdc048afa14cL37) which calls [this](https://github.com/rancher/dashboard/commit/f04ad9c1cf582ca5ffb4eb7387ffc8bb2ebc9510#diff-923894aa1addf785608a0acae313a41d20794b7dbf3775fa421d756b172dd836R348) added in #7670.
> 
> Possibly related [nodeca/js-yaml#464](https://github.com/nodeca/js-yaml/issues/464). Changing the `steve/actions.js` line to the below appears to avoid the line wrapping issue.
> 
> ```js
> return jsyaml.dump(obj, { lineWidth: -1 });
> ```
> 
> I'm still trying to understand what fields steve is adding that requires this function, but this seems like it could have been avoided if steve passed these parameters separately without modifying the YAML output.

I'm using v2.7.1, and this seems work for me.

**Comment by bromine0x23** [comment]
I applied this two changes, and seems fine.

[`shell/plugins/steve/actions.js`](https://github.com/rancher/dashboard/blob/b02d74a39b18171e85384007e5242c8056cd19a9/shell/plugins/steve/actions.js#L354)
```diff
    (obj?.status?.conditions || []).forEach(condition => dropKeys(condition, conditionKeys));

-    return jsyaml.dump(obj);
+    return jsyaml.dump(obj, { lineWidth: -1 });
  }
};
```

[`shell/utils/create-yaml.js`](https://github.com/rancher/dashboard/blob/b02d74a39b18171e85384007e5242c8056cd19a9/shell/utils/create-yaml.js#L459)
```diff
export function dumpBlock(data, options = {}) {
-  const parsed = jsyaml.dump(data);
+  const parsed = jsyaml.dump(data,{ lineWidth: -1 });

  let out = parsed;
```

**Comment by maartenl945** [comment]
> I applied this two changes, and seems fine.
> 
> [`shell/plugins/steve/actions.js`](https://github.com/rancher/dashboard/blob/b02d74a39b18171e85384007e5242c8056cd19a9/shell/plugins/steve/actions.js#L354)
> 
> ```diff
>     (obj?.status?.conditions || []).forEach(condition => dropKeys(condition, conditionKeys));
> 
> -   return jsyaml.dump(obj);
> +   return jsyaml.dump(obj, { lineWidth: -1 });
>   }
> };
> ```
> 
> [`shell/utils/create-yaml.js`](https://github.com/rancher/dashboard/blob/b02d74a39b18171e85384007e5242c8056cd19a9/shell/utils/create-yaml.js#L459)
> 
> ```diff
> export function dumpBlock(data, options = {}) {
> - const parsed = jsyaml.dump(data);
> + const parsed = jsyaml.dump(data,{ lineWidth: -1 });
> 
>   let out = parsed;
> ```

Is there an easy way to patch this in a running Rancher 2.7.9 installation in a docker container?

**Comment by bromine0x23** [comment]
> > I applied this two changes, and seems fine.
> > [`shell/plugins/steve/actions.js`](https://github.com/rancher/dashboard/blob/b02d74a39b18171e85384007e5242c8056cd19a9/shell/plugins/steve/actions.js#L354)
> > ```diff
> >     (obj?.status?.conditions || []).forEach(condition => dropKeys(condition, conditionKeys));
> > 
> > -   return jsyaml.dump(obj);
> > +   return jsyaml.dump(obj, { lineWidth: -1 });
> >   }
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [`shell/utils/create-yaml.js`](https://github.com/rancher/dashboard/blob/b02d74a39b18171e85384007e5242c8056cd19a9/shell/utils/create-yaml.js#L459)
> > ```diff
> > export function dumpBlock(data, options = {}) {
> > - const parsed = jsyaml.dump(data);
> > + const parsed = jsyaml.dump(data,{ lineWidth: -1 });
> > 
> >   let out = parsed;
> > ```
> 
> Is there an easy way to patch this in a running Rancher 2.7.9 installation in a docker container?

Actually, there are. I do this patch to `index.669db930.js`. It works, except needs a forced reload (Ctrl + F5 or ignore cache).

```bash
sed -i 's@L\["a"].dump(i)@L\["a"].dump(i,{lineWidth:-1})@' /usr/share/rancher/ui-dashboard/dashboard/js/index.669db930.js;
sed -i 's@n=s\["a"].dump(e),@n=s\["a"].dump(e,{lineWidth:-1}),@' /usr/share/rancher/ui-dashboard/dashboard/js/index.669db930.js; 
```

**Comment by maartenl945** [comment]
> > > I applied this two changes, and seems fine.
> > > [`shell/plugins/steve/actions.js`](https://github.com/rancher/dashboard/blob/b02d74a39b18171e85384007e5242c8056cd19a9/shell/plugins/steve/actions.js#L354)
> > > ```diff
> > >     (obj?.status?.conditions || []).forEach(condition => dropKeys(condition, conditionKeys));
> > > 
> > > -   return jsyaml.dump(obj);
> > > +   return jsyaml.dump(obj, { lineWidth: -1 });
> > >   }
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > [`shell/utils/create-yaml.js`](https://github.com/rancher/dashboard/blob/b02d74a39b18171e85384007e5242c8056cd19a9/shell/utils/create-yaml.js#L459)
> > > ```diff
> > > export function dumpBlock(data, options = {}) {
> > > - const parsed = jsyaml.dump(data);
> > > + const parsed = jsyaml.dump(data,{ lineWidth: -1 });
> > > 
> > >   let out = parsed;
> > > ```
> > 
> > 
> > Is there an easy way to patch this in a running Rancher 2.7.9 installation in a docker container?
> 
> Actually, there are. I do this patch to `index.669db930.js`. It works, except needs a forced reload (Ctrl + F5 or ignore cache).
> 
> ```shell
> sed -i 's@L\["a"].dump(i)@L\["a"].dump(i,{lineWidth:-1})@' /usr/share/rancher/ui-dashboard/dashboard/js/index.669db930.js;
> sed -i 's@n=s\["a"].dump(e),@n=s\["a"].dump(e,{lineWidth:-1}),@' /usr/share/rancher/ui-dashboard/dashboard/js/index.669db930.js; 
> ```

Thank you very much. I will give that a try!

**Comment by hhstu** [comment]
Anotherway is rebuild all, because  there are many bug shoud fix by yourself. @maartenl945 @bromine0x23 

```
OUTPUT_DIR=dist ROUTER_BASE="/dashboard/" RESOURCE_BASE="/dashboard/" yarn run build
```
then build the image with this dockerfile
```
FROM rancher/rancher:v2.7.9
WORKDIR /var/lib/rancher
RUN rm -rf /usr/share/rancher/ui-dashboard/dashboard*
COPY dist /usr/share/rancher/ui-dashboard/dashboard
```

**Comment by maartenl945** [comment]
> 
> Actually, there are. I do this patch to `index.669db930.js`. It works, except needs a forced reload (Ctrl + F5 or ignore cache).
> 
> ```shell
> sed -i 's@L\["a"].dump(i)@L\["a"].dump(i,{lineWidth:-1})@' /usr/share/rancher/ui-dashboard/dashboard/js/index.669db930.js;
> sed -i 's@n=s\["a"].dump(e),@n=s\["a"].dump(e,{lineWidth:-1}),@' /usr/share/rancher/ui-dashboard/dashboard/js/index.669db930.js; 
> ```

I tested your patch on our installation and it works partly in that at least I don't get any added empty lines anymore when editing a config map. However if I edit a large config map (e.g. an nginx.conf configuration), I still get a full screen error reported like this: 

_a line break is expected (20:11) 17 | - 1 18 | - 3m59s 19 | data: 20 | test: |+test: "load_module modules/ngx_ ... ----------------^ 21 | # key: string 22 | __clone: true_

So unfortunately, the fix does not fully solve the issue that we're experiencing on our end.

**Comment by rak-phillip** [comment]
Unable to repro after merging #10142, moving to `To Test` for validation. 

If anybody has additional repro steps outside of configmap and ingress, please leave an update in the comments.

**Comment by rameshraya3010** [comment]
> > I'm pretty sure this is caused by [this line](https://github.com/rancher/dashboard/commit/f04ad9c1cf582ca5ffb4eb7387ffc8bb2ebc9510#diff-5cf4eab2e7126559d21cb7359a67e030edc4332eafd9411598f9cdc048afa14cL37) which calls [this](https://github.com/rancher/dashboard/commit/f04ad9c1cf582ca5ffb4eb7387ffc8bb2ebc9510#diff-923894aa1addf785608a0acae313a41d20794b7dbf3775fa421d756b172dd836R348) added in #7670.
> > Possibly related [nodeca/js-yaml#464](https://github.com/nodeca/js-yaml/issues/464). Changing the `steve/actions.js` line to the below appears to avoid the line wrapping issue.
> > ```js
> > return jsyaml.dump(obj, { lineWidth: -1 });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm still trying to understand what fields steve is adding that requires this function, but this seems like it could have been avoided if steve passed these parameters separately without modifying the YAML output.
> 
> I'm using v2.7.1, and this seems work for me.

Hi , How to change this and where to change this . We have installed rancher using Helm

**Comment by rameshraya3010** [comment]
> > How about add this?
> > [shell/utils/create-yaml.js](https://github.com/rancher/dashboard/blob/b02d74a39b18171e85384007e5242c8056cd19a9/shell/utils/create-yaml.js#L431)
> > ```diff
> > export function saferDump(obj) {
> > - const out = jsyaml.dump(obj || {});
> > + const out = jsyaml.dump(obj || {}, { lineWidth: -1 });
> > 
> >   if ( out === '{}\n' ) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > sed -i 's@var t=s\["a"].dump(e||{});@var t=s\["a"].dump(e||{},{lineWidth:-1});@' /usr/share/rancher/ui-dashboard/dashboard/js/index.669db930.js;
> > ```
> 
> Thanks for another suggestion. I haven't tried it yet, but I did find that if I remove all /r and /t characters from the config map then the config map can be saved and edited fine without the above mentioned remaining error. So this seems related to #9841

@maartenl945 I am running rancher through helm . How do i patch this . can you please share some info.
