### ISSUE TITLE
Add required asterisk to cloudCredential name and message if none supplied

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#10081]
UI for rancher/rancher#19755     

If rancher/rancher#19755 is approved and completed please add a required asterisk to the cloudCredential name and supply an error in the UI if no name is provided.

We'd like the cloudCredential name to be required (requires that backend change) because it is not editable. We should be requiring the user to supply a (hopefully useful) name upon cloud credential creation so they avoid getting cloud credentials with randomly generated names that are of little use to them.

**Comment by nwmac** [comment]
Closing as stale. Please re-open if still required.
