### ISSUE TITLE
RKE2 registry configs are malformed when switching to yaml view

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#10092]
When creating an RKE2 cluster there is an option under the 'Registry' tab to set a cluster-wide custom registry. When switching to yaml view this configuration is messed up and lost if the cluster is saved from yaml view.

**This does not appear to be specific to rke2**. The data being fed into the `createYaml` utility (used in resource creation views generally) appears correct, but the result is malformed, so the problem is likely something in `createYaml`.
![Screen Shot 2023-11-28 at 1.04.11 PM.png](https://zube.io/files/rancher/0f0a7acd5acfb9e23aecc01d46c0b0d8-screen-shot-2023-11-28-at-1-04-11-pm.png)

 `rkeConfig.registries.configs` when switching to yaml view:
![Screen Shot 2023-11-28 at 12.49.27 PM.png](https://zube.io/files/rancher/e726022b01bd11f95ba31805fccaf54e-screen-shot-2023-11-28-at-12-49-27-pm.png)

The POST request for the provisioning cluster looks the same:
![Screen Shot 2023-11-28 at 12.50.05 PM.png](https://zube.io/files/rancher/1bbf2b224fa4a1034b6d631aa01bbbd8-screen-shot-2023-11-28-at-12-50-05-pm.png)

`rekConfig.registries.configs` is missing from the response to that POST request:
![Screen Shot 2023-11-28 at 12.50.18 PM.png](https://zube.io/files/rancher/c7819f5db600d515b394e76789e3b2c6-screen-shot-2023-11-28-at-12-50-18-pm.png)

When creating via form, the request looks like this:
![Screen Shot 2023-11-28 at 12.51.10 PM.png](https://zube.io/files/rancher/0560e1cdee3fc03d7f604725db45ad9c-screen-shot-2023-11-28-at-12-51-10-pm.png)

The response to the POST request when saving in form view includes the `rkeConfig.registries.configs` field:
![Screen Shot 2023-11-28 at 12.50.05 PM.png](https://zube.io/files/rancher/1bbf2b224fa4a1034b6d631aa01bbbd8-screen-shot-2023-11-28-at-12-50-05-pm.png)

**Comment by gaktive** [comment]
Possible connection to #11020

**Comment by nwmac** [comment]
@richard-cox FYI - could be related to 11020.

**Comment by richard-cox** [comment]
Similar to #11020. Following backend changes, i tried to reproduce in `v2.9-a84c3a2f` and could not. 

![image](https://github.com/rancher/dashboard/assets/18697775/172e0880-730a-4de3-b6eb-38d504b03ec6)


We just need to write some automation to prevent regression, or for quicker resolution change to manual QA.

**Comment by nwmac** [comment]
@richard-cox Already set to manual test, so moving to 'To Test' on the project board.

**Comment by sowmyav27** [comment]
On `v2.9-a9355` and dashboard - `master 30d8ecc`, issue is not seen anymore.
<img width="453" alt="Screen Shot 2024-07-10 at 9 11 30 AM" src="https://github.com/rancher/dashboard/assets/26032343/09b9f6dd-c46a-47e5-8924-9a6aca7089e8">
<img width="477" alt="Screen Shot 2024-07-10 at 9 07 49 AM" src="https://github.com/rancher/dashboard/assets/26032343/28ae0051-0915-4780-be8c-ac4f1817b4b7">
