### ISSUE TITLE
RKE2 cluster-scoped container registry hostname is only saved if an auth secret is provided

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#10093]
![Screen Shot 2023-11-28 at 2.01.58 PM.png](https://zube.io/files/rancher/359219df38aa6809b64e803658938451-screen-shot-2023-11-28-at-2-01-58-pm.png)

"Container Registry" in the screenshot above is only included in the prov cluster payload if an authentication secret is selected. If the auth secret _is_ required, that should be noted on the form.

**Comment by richard-cox** [comment]
Had a quick look at this as part of something else. There's a `if ( hostname && this.registrySecret ) {` that blocks setting `value.spec.rkeConfig.registries`

**Comment by richard-cox** [comment]
Linking issues in same area https://github.com/rancher/dashboard/issues/10314

**Comment by izaac** [comment]
I was checking the the tests and they do the e2e on a Custom cluster, but the UI view is identical on cluster driver types. I am good if this UI is sharing the same UI elements on both cluster types. cc @yonasberhe23
