### ISSUE TITLE
Edit cluster config labels cropped view missing left half of view

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10105]
Internal Ref: SURE-7174

When trying to edit cluster labels when they are not editable the labels are not shown at all and the annotations display therefore looks starnge:

![image](https://github.com/rancher/dashboard/assets/1955897/9bae4a35-0556-424a-8e98-f1c86c96afc7)

Steps to reproduce:

- Create an EKS cluster
- While the cluster is in the pending state, edit the cluster config
- Labels are not shown

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head

![Image](https://github.com/rancher/dashboard/assets/70187881/e2d1fd31-56fd-44e1-8154-92c0be9c6bb9)
