### ISSUE TITLE
Migrate Vue 2.7 compatible syntax to new format

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#10101]
# Description

As Vue 2.7 introduce the possibility to use some of the Vue3 syntax, migrate to the new format. 
Syntax to be migrated:
- [x] #10104
- Event emission with new `emits` options

## Context

[Here full list of the features for awareness](https://v2.vuejs.org/v2/guide/migration-vue-2-7.html#Backported-Features).

Given the ongoing migration from Vue 2 to Vue3 ([epic](https://github.com/rancher/dashboard/issues/7653)), to decrease complexity and split efforts we may proceed with a parallel task based on current configuration.
[Original conversation](https://github.com/rancher/dashboard/issues/9541#issuecomment-1832467210).

NOTE: This issue can be solved together with https://github.com/rancher/dashboard/issues/9541 if nobody gets assigned.

**Comment by gaktive** [comment]
@cnotv based on #9561 being closed, what's the state of this ticket then? Was the work here folded there or is there still something to do? There are concerns that we won't be able to do this across every component but what does your script do to help here?

**Comment by cnotv** [comment]
> @cnotv based on #9561 being closed, what's the state of this ticket then? Was the work here folded there or is there still something to do? There are concerns that we won't be able to do this across every component but what does your script do to help here?

I am not so sure to understand. What is the relation with this PR? https://github.com/rancher/dashboard/pull/9561
There's nothing written in it, could you maybe expand about what precisely do you want to know?

**Comment by cnotv** [comment]
Closing this issue due timeline.
