### ISSUE TITLE
Replace `Vue.extend` with `defineComponent`

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#10104]
Vue 2.7 introduced a backported Vue 3 feature known as `defineComponent` [^1]. Migrating from `Vue.extend` to `defineComponent` and resolving any potential issues that arise can help ease the overall transition to Vue 3.

## Acceptance Criteria

- [x] Instances of `Vue.extend` are replaced with the equivalent usage of `defineComponent`
- [x] Specific issues that might arise as a result of this migration are resolved
   The Vue 3 migration guide[^2] can provide guidance on how to resolve these issues 

## Identified usages of Vue.extend

- [x] ./pkg/rancher-components/src/components/BadgeState/BadgeState.vue
- [x] ./pkg/rancher-components/src/components/Banner/Banner.vue
- [x] ./pkg/rancher-components/src/components/Card/Card.vue
- [x] ./pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue
- [x] ./pkg/rancher-components/src/components/Form/Radio/RadioButton.vue
- [x] ./pkg/rancher-components/src/components/Form/Radio/RadioGroup.vue
- [x] ./pkg/rancher-components/src/components/Form/TextArea/TextAreaAutoGrow.vue
- [x] ./pkg/rancher-components/src/components/Form/ToggleSwitch/ToggleSwitch.vue
- [x] ./pkg/rancher-components/src/components/LabeledTooltip/LabeledTooltip.vue
- [x] ./pkg/rancher-components/src/components/StringList/StringList.vue
- [x] ./pkg/harvester/pages/c/_cluster/projectsnamespaces.vue
- [x] ./shell/components/form/Error.vue
- [x] ./shell/components/form/Footer.vue
- [x] ./shell/components/form/GitPicker.vue
- [x] ./shell/components/DraggableZone.vue
- [x] ./shell/components/PodSecurityAdmission.vue
- [x] ./shell/components/AsyncButton.vue
- [x] ./shell/mixins/create-edit-view/index.js

### Not updating

The following mixins should be replaced with their composable counterparts:

- ./shell/mixins/compact-input.ts
- ./shell/mixins/labeled-form-element.ts

The following files are related to our init process and will need to be refactored along with larger nuxt removal/vue 3 migration efforts:

- ./shell/utils/nuxt.js
- ./shell/initialize/client.js

`kubectl-explain` utilizes `Vue.extend` to load and mount the slide in panel component. This should be updated to make use of `createApp()` when we migrate to Vue 3:

- ./pkg/kubectl-explain/slide-in.js

Finally, this test can be rewritten after the Vue 3 migration:

- ./shell/mixins/__tests__/chart.test.ts

[^1]: https://v2.vuejs.org/v2/guide/migration-vue-2-7.html#Backported-Features
[^2]: https://v3-migration.vuejs.org/breaking-changes/global-api.html#type-inference

**Comment by aalves08** [comment]
For FYI @rak-phillip : 

- Elemental and Kubewarden don't have any reference to Vue.extend
- The partners extensions also are clear
- There's one mention on the `ui-plugin-examples` -> `BusyButton` component https://github.com/rancher/ui-plugin-examples/blob/main/pkg/node-driver/components/BusyButton.vue#L10

FYI @richard-cox @nwmac

**Comment by rak-phillip** [comment]
Reopening issue, initial PRs were reverted as a result of errors raised during plugin installation.
