### ISSUE TITLE
[BUG][UI] Creating new cloud credentials results in `t is null`

### ISSUE THREAD

**Issue by lindhe** [rancher/dashboard#10128]
**Rancher Server Setup**
- Rancher version: v2.7.6
- Installation option: Helm chart
   - If Helm Chart, Kubernetes Cluster and version: RKE2

**Information about the Cluster**
- Kubernetes version: v1.26.8
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? `user-base`

**Describe the bug**

When my test user (that has fairly low privileges) tries to create new Cloud Credentials, the user is presented with a blank page and the error "t is null".

**To Reproduce**

1. Log in as user `foo`
2. Go to: Cluster Management > Cloud Credentials
3. Click "Create" (which gets you to `rancher.example.com/dashboard/c/_/manager/cloudCredential/create`)

**Screenshots**

![Screenshot 2023-12-10 192133](https://github.com/rancher/rancher/assets/7773090/e5baf6c8-c05a-4892-b7a3-7272a970ac9e)

**Additional context**

Here's the error message from my browser's debug console:

```text
t is null console.js:31:30
    e console.js:31
    e client.js:111
    Babel 7
    errorHandler client.js:113
    VueJS 15
        $n
        Bn
        _render
        r
        get
        run
        Zr
        Zn
        Wn
        (Async: promise callback)
    qn
        Zn
        ni
        update
        notify
        set
    t fetch.client.js:91
    Babel 11
    f fetch.client.js:67
    p fetch.client.js:58
    u fetch.client.js:29
    VueJS 30
        Hn
        Hr
        Fr
        $mount
        init
        v
        d
        T
        I
        pa
        _update
        r
        get
        run
        Zr
        Zn
        Wn
        (Async: promise callback)
    qn
        Zn
        ni
        update
        $forceUpdate
        l
        h
        2b0e/</$/<
        (Async: promise callback)
    In
        pi
        Fn
        Rn
        _c
    n index.vue:1
    VueJS 13
        _render
        r
        get
        run
        Zr
        Zn
        Wn
        (Async: promise callback)
    qn
        Zn
        ni
        update
        notify
        set
    t fetch.client.js:91
    Babel 2
        p
        S
```

**Comment by richard-cox** [comment]
This will be the result of a developer error page mistakenly being shown in production and is resolved in 2.8 and the next feature release of 2.7 (for tracking see https://github.com/rancher/dashboard/issues/9542)

There will be an underlying error, but after upgrading if there are functional issues please just let us know via a fresh gh issue.
