### ISSUE TITLE
[BUG] Monitoring URLs not accessible in rancher v2.7.6

### ISSUE THREAD

**Issue by bogdanstefan010** [rancher/dashboard#10121]
**Rancher Server Setup**
- Rancher version: 2.7.6 
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2

**Information about the Cluster**
- Kubernetes version:  v1.24.12+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? 
   Imported/v1.24.12+rke2r1

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
 Admin

**Describe the bug**
Monitoring links are not accessible into Rancher UI. 

**To Reproduce**
1. Install rancher-monitoring chart (I've tried with two different chart version 101\.0.0+up19.0.3 & 102\.0.1+up40.1.2)
2. Test if monitoring UIs are available

**Result**
The monitoring links are not usable

**Expected Result**
The monitoring UIs should be available.

**Screenshots**
![image](https://github.com/rancher/rancher/assets/137087822/cfc95a73-2676-4fd7-94a0-242a7dc76375)

**Comment by mantis-toboggan-md** [comment]
This is a UI bug so I've transferred the issue. Any bugs around monitoring relating to 404 or 403 errors on catalog.cattle.io.apps should be resolved in 2.8.0 https://github.com/rancher/dashboard/pull/9663. 

It's worth noting that these external links will still be greyed out for users with the view monitoring role. You can enable the links for those users by moving the `cattle-monitoring-system` namespace, see the docs here: https://ranchermanager.docs.rancher.com/integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring#users-with-rancher-based-permissions

**Comment by tomitesh** [comment]
Thanks @mantis-toboggan-md for the update.

There is a fix/suggestion [on this post](https://github.com/rancher/rancher/issues/41036) which says, if we provide below values while installing using helm, it fixes 404/403 issue (i tested and it is fixes).

global:
  cattle:
    clusterId: c-ft9ab
    clusterName: testcluster
    url: https://$(hostname)

The 404/403 issue wihch is fixed in rancher 2.8.0, does it still requires to supply above 3 values while installing using helm? kindly suggest.

**Comment by mantis-toboggan-md** [comment]
@tomitesh from what I can tell that seems to have a different root-cause, and those steps would still be needed when installing monitoring using helm
