### ISSUE TITLE
Rancher UI 2.6.8 and session timeout - expected behaviour?

### ISSUE THREAD

**Issue by dtarrero-ibermatica** [rancher/dashboard#10134]
Hi!

I'm using Rancher 2.6.8 and I'm not able to customize the session timeout behaviour the way we want it.

For example: I want a "session timeout" of 1 hour, and I want the session to be automatically extended (refresh token?) if any action is performed in the Web UI. If there is no user activity during the "session timeout" time, the session would be destroyed/expired.
_Usually a "session timeout" represents that a maximum time has passed without activity, so the session is destroyed._

Right now, the only option I find to tweak sessions in Rancher is the Global Setting "auth-user-session-ttl-minutes".
This sets a fixed timeout, no matter if the user is actively working in the UI, the session will terminate (and Rancher prompts for login) when this time passes.

Is this the actual supported/expected behaviour?
Is there any way to configure Rancher the way we need? Session Timeout + Refresh on activity

Regards,
D

**Comment by dtarrero-ibermatica** [comment]
May this problem be also described as: "Web UI doesn't refresh token" ?

**Comment by nwmac** [comment]
Sorry this question was not responded to - it was quite some time ago - if still relevant, please re-open
