### ISSUE TITLE
Allow extensions to provide Node Driver icons

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10148]
**Is your feature request related to a problem? Please describe.**
- Extensions can provide UX components for node drivers
- However extensions can't provide an image for it, so a placeholder is shown when selecting in the create cluster process (not shown in screenshot below)
- ![image](https://github.com/rancher/dashboard/assets/18697775/2d01c2b9-e480-4065-b00e-aea052e33ded)

**Describe the solution you'd like**
- The extension should be able to provide the image

**Additional context**
- At the moment the only workaround is to add the icon to the core dashboard code
- ~Candidate to backport to 2.7.next1~ Customer has a workaround, so backport is tbd given solution in 2.9

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
