### ISSUE TITLE
Deprecation of Monitoring V1 - Addressing Required Changes in the Dashboard

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#10145]
We need to investigate how to address removing/updating the unused/non-working code in Dashboard due to the [deprecation of monitoring v1 in 2.5+](https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/advanced-user-guides/monitoring-alerting-guides/migrate-to-rancher-v2.5+-monitoring).

Some non-working doc links found in 2 files (`shell/chart/monitoring/steps/uninstall-v1.vue` & `shell/pages/c/_cluster/explorer/tools/index.vue`).

<img width="737" alt="image" src="https://github.com/rancher/dashboard/assets/135728925/799a041d-5f7b-41d8-bfcf-3c21712e3434">

**Comment by momesgin** [comment]
@nwmac  I created this issue since it's not fixed by [your PR](https://github.com/rancher/dashboard/pull/9928)

**Comment by nwmac** [comment]
Closing - work should be covered as part of https://github.com/rancher/dashboard/issues/10490
