### ISSUE TITLE
The translated content does not fall back to English after the page refresh

### ISSUE THREAD

**Issue by ly5156** [rancher/dashboard#10153]
**Setup**
- Rancher version: v2.8.0
- Rancher UI Extensions: v2.8.0
- Browser type & version: Chrome arm64 v120.0.6099.71

**Describe the bug**

After refreshing the page, the translation of the` kube-explain` tooltip  did not fall back to English on the Simplified Chinese language page

**To Reproduce**

1. In Simplified Chinese, go to the `Cluster-Events` page.
2. Refresh the page

**Result**
The ` kube-explain` tooltip display error：`%kube-explain.tooltip%`

**Expected Result**

The ` kube-explain` tooltip display `Describe Resource`

**Screenshots**

<img width="1305" alt="image" src="https://github.com/rancher/dashboard/assets/3406205/655d24ab-6a48-43c2-945d-1b2f1f558468">

![bug](https://github.com/rancher/dashboard/assets/3406205/79852fd9-03a1-4149-98cc-89db3f8cfec4)

**Additional context**

**Comment by yonasberhe23** [comment]
e2e coverage is sufficient. moving to Done
