### ISSUE TITLE
"Truncate hostnames to 15 characters for NetBIOS compatibility." checkbox is not clickable when creating an instance.

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#10159]
**Setup**
- Rancher version: 2.8.1
- Rancher UI Extensions: N/A
- Browser type & version: Chrome

**Describe the bug**

"Truncate hostnames to 15 characters for NetBIOS compatibility" checkbox cannot be checked.

**To Reproduce**

Clusters -> Create -> Network

**Result**
"Truncate hostnames to 15 characters for NetBIOS compatibility" cannot be checked.

**Expected Result**

"Truncate hostnames to 15 characters for NetBIOS compatibility" should be clickable.

**Screenshots**

**Additional context**

**Comment by izaac** [comment]
Added a note on PR. Coverage is good. Closing
