### ISSUE TITLE
[Alerting V2 UI] Basic Configuration

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1015]
Annotation: `catalog.rancher.io/ui-component: monitoring`

#### General

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Deploy AlertManager | `alertmanager.enabled` | N/A | `boolean` | `true`

#### Configuration

There should be a radio button that says `Use Existing Secret for Config` (`Enabled` or `Disabled`, where the default is `Disabled`) that exposes the following fields and is tied to the value `alertmanager.alertmanagerSpec.useExistingSecret`.

There should also be the following help text underneath it:
```
It is recommended for a user to use an Existing Secret within the namespace `cattle-monitoring-system` for the AlertManager Config in order to avoid having to to manage the Secret via Helm. Using the default Helm managed Secret will require a user to redeploy the chart in order to persist any changes to the AlertManager configuration on a `helm upgrade` while using an existing Secret will allow a user to directly modify the secret to perform live updates on the AlertManager configuration if necessary.

If using an Existing Secret, please add the label `alertmanager_config` to the Secret to enable modifying the secret using the Rancher Dashboard UI.
```

If `Enabled` is selected (if the namespace does not currently exist, the user should be notified that they need to create the namespace and a secret within it to use this option):
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Config Secret | `alertmanager.alertmanagerSpec.configSecret` | N/A | Ability to select `Secret` in `cattle-monitoring-system` namespace | `null`

If `Disabled` is selected:
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
AlertManager Config | `alertmanager.config` | N/A | `YAML` | Should be the same as the default on the `values.yaml`
Template Files | `alertmanager.templateFiles` | N/A | Ability to supply multiple key-value pairs where the key is a filename and the value is a `YAML` string | Should be the same as the default on the `values.yaml`

The following fields should be available regardless of the option selected:
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Additional Secrets | ` alertmanager.alertmanagerSpec.secrets` | Mounted on` /etc/alertmanager/secrets/` | Ability to supply list of secrets | None

**Comment by aiyengar2** [comment]
**Note:** In order to allow users to be able to initially deploy a basic AlertManager Config, this ticket currently allows users to provide the `AlertManager Config` as `YAML` directly; however, this will need to be updated to a UI that allows users to easily configure the notifiers / routes (similar to Alerting V1). 

This work will be tracked in a separate ticket, which will be later linked to this ticket.

**Comment by aiyengar2** [comment]
## Updated Requirements

Annotation: `catalog.rancher.io/ui-component: monitoring`

### Basic Configuration

#### General

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Deploy AlertManager | `alertmanager.enabled` | N/A | `boolean` | `true`

#### Configuration

There should also be the following help text:
```
Provide an Existing Secret within the namespace `cattle-monitoring-system` for the AlertManager Config.

To enable modifying the secret using the Dashboard UI, either create the secret using the Dashboard UI or add the label `alertmanager_config` to the secret.
```
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
N/A | `alertmanager.alertmanagerSpec.useExistingSecret` | N/A | N/A | `true`
Config Secret | `alertmanager.alertmanagerSpec.configSecret` | N/A | Ability to select `Secret` in `cattle-monitoring-system` namespace | `null`
Additional Secrets | ` alertmanager.alertmanagerSpec.secrets` | Mounted on` /etc/alertmanager/secrets/` | Ability to supply list of secrets | None

**Comment by deniseschannon** [comment]
All other items are being tracked inthe other ticket so closing this one
