### ISSUE TITLE
EtcdInfoBanner component canList getters Method Access Error

### ISSUE THREAD

**Issue by ly5156** [rancher/dashboard#10172]
**Setup**
- Rancher version: v2.8.0
- Rancher UI Extensions: v2.8.0
- Browser type & version: 

**Describe the bug**

Error accessing canList getters method，Error Code Location: https://github.com/rancher/dashboard/blob/v2.8.0/shell/components/EtcdInfoBanner.vue#L14

`${ inStore }/canList}`  should be `${ inStore }/canList`， the curly braces `}` after the `canList` should be removed

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

<img width="757" alt="image" src="https://github.com/rancher/dashboard/assets/3406205/41bd9e8d-84ec-424d-853d-d52594a33a09">

**Additional context**

**Comment by richard-cox** [comment]
Adding milestone

**Comment by izaac** [comment]
Unit test coverage is enough for validation this can be moved to done. @yonasberhe23
