### ISSUE TITLE
vSphere's Config Page (View Mode) Has Misleading Display of Enabled Buttons/Checkboxes

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#10181]
**Setup**
- Rancher version: 2.8-head

**Describe the bug**

When viewing your vSphere Cluster Configuration Page in the view mode you should not be able to edit the configuration. Though Save button is not shown on this page, having some buttons/checkboxes enabled and some disabled is inconsistent and confusing.

Note: The Cluster Configuration section is relevant to all the supported providers and is covered by [#10182](https://github.com/rancher/dashboard/issues/10182).

**To Reproduce**

Create a vSphere cluster and go to its Config page.

**Screenshots**

![image](https://github.com/rancher/dashboard/assets/135728925/a2c97d7a-b22b-4737-9db6-520c4a978742)

<img width="806" alt="image" src="https://github.com/rancher/dashboard/assets/135728925/0cc5404e-6690-4009-8127-fc70b63d3959">

**Comment by aalves08** [comment]
Based on other Vsphere issues that i've added as a possible `automation-candidate`, if we are able to fake it to go to EDIT or VIEW pages, we can assert the attribute `disabled` on the input... mechanism would be similar to https://github.com/rancher/dashboard/issues/10476

**Comment by rak-phillip** [comment]
During testing, I took note that the following fields are still enabled for editing

- Add Network
- Add Tag
- Cluster Configuration => Registries => Enable cluster scoped container registry
- Cluster Configuration => Basics => Show deprecated kubernetes patch versions

@momesgin and I agreed that creating a new issue to address these fields for v2.10 would be the best course of action. Add Network and Add Tag have some technical debt associated with them that makes it difficult to simply disable for the near-term.
