### ISSUE TITLE
Custom Backup-restore-operator Deployment Page

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#1019]
Chart.yaml Annotation:

catalog.cattle.io/ui-component: backup-restore-operator

What fields are required/needed for chart deployment?

Label Name |  Description     | k8s YAML | Input | Default 
-- | ---- | -- | -- | -- 
Operator Image | "Provide the name of the backup-restore-operator image" | image.respository |  String | rancher/backup-restore-operator | 
Operator Image Tag | "Provide a tag for the backup-restore-operator image" | image.tag | String | "" | 

Configure storage location for all backups created by the operator

**NOTE** Either S3 or PV can be configured

### S3
Label Name | Description | k8s YAML | Input | Default 
-- | -- | -- | -- | --
S3 | Configure s3/minio as a backup storage location by setting `enabled` and provide any necessary fields | s3 | - | 
Enabled | This flag determines if s3 is configured | s3.enabled | Boolean | false
S3 Credentials secret | Provide the name of the secret containing s3/minio creds. This secret must be created in the namespace in which chart is installed, and can be created after the chart is installed | s3.credentialSecretName | String | ""
Bucket | Provide the name of the bucket to store backups in  | s3.bucket | String | ""
Region | Provide region if applicable | s3.region | String | ""
Folder | Provide base folder if applicable | s3.folder | String | ""
Endpoint | Provide endpoint | s3.endpoint | String | ""
EndpointCA | Provide base64 encoded CA cert | s3.endpointCA | String/Read file | ""
Insecure TLS Skip Verify | |s3.insecureTLSSkipVerify | Boolean | false

### PV (Has two sub sections, PVC and NFS)
Label Name | Description | k8s YAML | Input | Default 
-- | -- | -- | -- | --
Persistence | Configure a Persistent Volume as a backup storage location by setting `enabled` and provide any necessary fields | persistence | - |
Enabled | This flag determines if a Persistent Volume storage is configured | persistence.enabled | Boolean | false
Storage Class | Provide name of the StorageClass to use for creating the PVC. If set to "-", PVC will be created with an empty storageClassName which disables dynamic provisioning | persistence.storageClass
Size | Provide the storage request/size of PV | persistence.size | String | 2Gi

**Comment by lvuch** [comment]
<img width="826" alt="Screen Shot 2020-09-08 at 4 48 31 PM" src="https://user-images.githubusercontent.com/3013118/92538290-2cd93200-f1f3-11ea-8d2b-43de38d80ad5.png">
<img width="831" alt="Screen Shot 2020-09-08 at 4 48 19 PM" src="https://user-images.githubusercontent.com/3013118/92538295-2e0a5f00-f1f3-11ea-9bcc-9c6fc907e027.png">
<img width="835" alt="Screen Shot 2020-09-08 at 4 48 08 PM" src="https://user-images.githubusercontent.com/3013118/92538300-2ea2f580-f1f3-11ea-9862-9ca6c50c0032.png">
<img width="834" alt="Screen Shot 2020-09-08 at 4 47 57 PM" src="https://user-images.githubusercontent.com/3013118/92538303-2fd42280-f1f3-11ea-847a-a0e952563019.png">

**Comment by deniseschannon** [comment]
- [ ] If no default storage class is configured on the cluster, we should disable or hide the "Use the default storage class" option
- [ ] Populate the "Use the default storage class" with the name of the default storage class

- [ ] Default should be to configure S3

**Comment by mrajashree** [comment]
When I configure s3 as the default location, I don't see s3.enabled being set to true. If it's not set then the chart doesn't configure it as the default location

<img width="717" alt="Screen Shot 2020-09-21 at 10 52 36 PM" src="https://user-images.githubusercontent.com/10672776/93914558-92312680-fcbb-11ea-8d1f-1c4455a3f1c0.png">

**Comment by sowmyav27** [comment]
**On master-head `0ccce45017`**

- Navigate to dashboard --> Deploy backup restore chart
- Select `Use an existing pv` Storage location as the default
- User is NOT able to select persistent volume from the dropdown. The input field is blank after you select from dropdown. And the backup restore operator fails to deploy

<img width="1065" alt="Screen Shot 2020-09-22 at 2 07 59 PM" src="https://user-images.githubusercontent.com/26032343/93942114-9f164000-fce4-11ea-8b79-ef93bfd571ee.png">

**Comment by sowmyav27** [comment]
**On master head- commit id: `0ccce4501`**

- `credentialSecretNamespace` is NOT available in 
<img width="1430" alt="Screen Shot 2020-09-22 at 7 38 07 PM" src="https://user-images.githubusercontent.com/26032343/93958790-22975780-fd0c-11ea-923d-215248052023.png">

- After deploying the App Navigate to Backup Restore Operator from the top menu --> Backup CR
<img width="1369" alt="Screen Shot 2020-09-22 at 7 46 01 PM" src="https://user-images.githubusercontent.com/26032343/93958891-5e322180-fd0c-11ea-9545-c168b7d8b2e7.png">

- Create a backup. Backup is in error state with error
<img width="1129" alt="Screen Shot 2020-09-22 at 7 48 17 PM" src="https://user-images.githubusercontent.com/26032343/93959011-9f2a3600-fd0c-11ea-92e7-9fdf7ac342ae.png">

Reopening the issue

**Comment by sowmyav27** [comment]
[This](https://github.com/rancher/dashboard/issues/1019#issuecomment-697098476)  was an issue with my setup, on a new setup I see in general the UI being available. I will validate the UI.

**Comment by sowmyav27** [comment]
**On latest master-head - commit id: `2229f5cd`**

- Deploy Backup restore. Pick a credential from the dropdown. Dpeloy the app.
- View in Yaml of the App shows `credentialSecretNamespace` is NOT set

```
affinity: {}
global:
  cattle:
    systemDefaultRegistry: ''
    clusterId: local
    clusterName: local
image:
  repository: rancher/backup-restore-operator
  tag: v0.1.0-rc1
nodeSelector: {}
persistence:
  enabled: false
  size: 2Gi
  storageClass: '-'
  volumeName: ''
s3:
  bucketName: <bucketname>
  credentialSecretName: creds
  credentialSecretNamespace: ''
  enabled: true
  endpoint: <endpoint>
  endpointCA: ''
  folder: test-0923
  region: ''
tolerations: null
systemDefaultRegistry: ''
```

Because of this, NOT able to create backup CRs, they have an error on creation
<img width="840" alt="Screen Shot 2020-09-23 at 10 29 28 AM" src="https://user-images.githubusercontent.com/26032343/94048001-b35f4900-fd87-11ea-83cf-4700d0036ba7.png">

**Comment by sowmyav27** [comment]
**On latest master-head - commit id: `c983bb436bf`**

- User is able to install backup restore by providing in S3 storage details/PV/Storage class
- User is able to perform backup and restore.

Related issues are tracked separately.
