### ISSUE TITLE
Documentation link does not open in a new tab on cluster's edit page

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#10192]
**Describe the bug**

Having an extra `target` attribute prevents the documentation link to open in a new tab on cluster's edit page.

**To Reproduce**

Go to any cluster's edit config page and click on the link provided inside the warning banner.
<img width="1170" alt="image" src="https://github.com/rancher/dashboard/assets/135728925/493c042c-7025-42ba-b9af-9ad12f6fa289">

**Comment by IsaSih** [comment]
Tests pass, but the current link the user is being redirected to is https://ranchermanager.docs.rancher.com/v2.7/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/rke1-vs-rke2-differences. I believe this link would be more suitable for the context of managing existing cluster configuration: https://ranchermanager.docs.rancher.com/v2.7/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider

**Comment by aalves08** [comment]
@richard-cox @gaktive any thoughts on the link change? Wdyt?

**Comment by richard-cox** [comment]
The link should probably go to the fragment within the page which details when nodes are re-provisioned `/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/rke1-vs-rke2-differences#cluster-api`

**Comment by IsaSih** [comment]
Tests pass in v2.9-0e88e978bdc9639a272422c8d611a9a7ba476761-head
