### ISSUE TITLE
Logs display errors if there are multibyte utf8 characters truncated

### ISSUE THREAD

**Issue by ly5156** [rancher/dashboard#10196]
**Setup**
- Rancher version: v2.8.0
- Browser type & version: Chrome v120.0.6099.109 arm64

**Describe the bug**

If a single log entry is too long, the log message pushed by the backend may be truncated, and if the log entry contains multibyte utf8 characters, the complete utf8 characters may be truncated, resulting in the ui being unable to display the truncated characters.

**To Reproduce**

The following mirror will replicate the problem：

arm64 image：liuyan/test:v1
amd64 image: liuyan/test:v2

**Result**
Truncated characters are displayed as `�`

**Expected Result**

The truncated utf8 characters need to be merged in order to be displayed correctly.

**Screenshots**

<img width="1560" alt="image" src="https://github.com/rancher/dashboard/assets/3406205/25ce4fb4-5c89-4669-948a-f975ebbe5665">

**Additional context**

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
