### ISSUE TITLE
[BUG] EKS imported cluster shows intermittent blank page

### ISSUE THREAD

**Issue by elenagarciam** [rancher/dashboard#10207]
SURE-7400

**Rancher Server Setup**
- Rancher version: 2.7.6
- Installation option: Helm Chart
   - If Helm Chart, Kubernetes Cluster and version RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.26.11-eks-8cb36c9

- Cluster Type: Downstream
   - If downstream, what type of cluster? Imported

* Imported = Running kubectl apply onto an existing k8s cluster
* Hosted = EKS,
 * Infrastructure Provider = AWS

**User Information**
- What is the role of the user logged in? Admin
 
**Describe the bug**
Error shown in the screenshot is appearing intermittently when working with the EKS imported cluster
**To Reproduce**
It is is an intermitent error hapeen when working with the UI console

**Result**

**Expected Result**
A fix for not getting the cannot read properties error

**Screenshots**
![image](https://github.com/rancher/rancher/assets/72928401/b8cdb6ea-58a1-4cfb-b054-5b875edc03ee)

**Comment by richard-cox** [comment]
@elenagarciam Thanks for creating this issue. Would you be able to provide a title and expand on the steps to reproduce? If clear steps are unknown, can you provide the page/s that you see the error on?

**Comment by richard-cox** [comment]
Linking some related issues
- https://github.com/rancher/dashboard/issues/9665 (possibly related underlying issue)
- https://github.com/rancher/dashboard/issues/9542 (do not show dev full blank page errors in prod)

**Comment by gaktive** [comment]
Fixed in 2.8.0 and an upcoming 2.7.x via https://github.com/rancher/dashboard/issues/10062
