### ISSUE TITLE
UI requirements for backup-restore-operator CRDs

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#1020]
### CRD 1: ResourceSet
https://github.com/rancher/dashboard/issues/1123

---------------------------------------------

### CRD 2 Backup
https://github.com/rancher/dashboard/issues/1124

---------------------------------------------

### CRD 3: Restore
https://github.com/rancher/dashboard/issues/1125

**Comment by lvuch** [comment]
wip please review: https://xd.adobe.com/view/825794e3-a0df-4579-9798-40e053f2770e-d704/

**Comment by deniseschannon** [comment]
Closing in favor of the individual issues and new XD files will be created for each CRD
