### ISSUE TITLE
Save error when cloning a job

### ISSUE THREAD

**Issue by ly5156** [rancher/dashboard#10200]
**Setup**
- Rancher version: v2.8.0
- Rancher UI Extensions: v2.8.0
- Browser type & version: Chrome v120.0.6099.129 arm64

**Describe the bug**

Creating a job by clone fails after clicking the create button and displays the error new

**To Reproduce**

1. create a job
2. create another job by cloning the job created in the previous step
3. click create button

**Result**

Job creation fails with an error

**Expected Result**

Successful job creation

**Screenshots**

<img width="1401" alt="image" src="https://github.com/rancher/dashboard/assets/3406205/b2b2a84a-1801-4ec4-a1e8-3545712d54ca">

**Additional context**

**Comment by izaac** [comment]
Left a comment ablout a small thing in #10940
