### ISSUE TITLE
Add PR backport Github action

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10218]
To help with our new branching model, we need to add the backport mechanism to our PRs

**Comment by torchiaf** [comment]
Harvester uses mergify for this,  https://github.com/apps/mergify

**Comment by rak-phillip** [comment]
When rancherbot was removed someone did write a PR backport workflow:

https://github.com/rancherlabs/rancherbot/blob/master/ALTERNATIVES.md#backportingforwardporting-pull-requests

Similar to the issue workflow, we will have to enable this or something else in dashboard
