### ISSUE TITLE
Various Monitoring/Grafana link issues related to user permissions

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10213]
Need to investigate, understand and resolve issues around monitoring links related to user permissions. We have at least 3 issues that look related so we need to dive in and understand 

Internal references:

1. SURE-6830: 404 on Cluster Dashboard graphs and Log in failure to Grafana

Related backend: https://github.com/rancher/rancher/issues/43406

2. SURE-6964: granting permissions to monitoring no longer works

Past efforts: https://github.com/rancher/dashboard/issues/4466

3. SURE-4075: Links in Dashboard are un-clickable even when the user has monitoring-ui-view

Related backend: https://github.com/rancher/rancher/issues/35311

### SURE-4075: Links in Dashboard are un-clickable even when the user has monitoring-ui-view

Not an issue

Based on details uncovered from the following issue comments:

- https://github.com/rancher/dashboard/issues/4466#issuecomment-1771627358
- https://github.com/rancher/rancher/issues/43030#issue-1922573209

It sounds like this is behaving as expected. Moving the cattle-monitoring-system namespace into the p1 project (from repro steps above) allows the user to click on Monitoring links from Rancher Dashboard. This is also noted in instructions from the docs:

- https://ranchermanager.docs.rancher.com/integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring#additional-monitoring-clusterroles

> A user bound to the View Monitoring Rancher role and read-only project permissions can't view links in the Monitoring UI. They can still access external monitoring UIs if provided links to those UIs. If you wish to grant access to users with the View Monitoring role and read-only project permissions, move the cattle-monitoring-system namespace into the project.

### SURE-6964: granting permissions to monitoring no longer works

This has been identified as a duplicate of SURE-4075. The same rules apply here.

### SURE-6830: 404 on Cluster Dashboard graphs and Log in failure to Grafana

There's nothing for us to address in this ticket at this point. The installation methods for Rancher Monitoring are unsupported at this point; we'll need buy-in and clear documentation on how helm/fleet installations of monitoring are to be handled if we intend to support this moving forward. Otherwise, we have no guarantee that a monitoring install has been configured properly.

**Comment by rak-phillip** [comment]
@nwmac I left notes in the description above for each of the items mentioned. At this point, there's nothing that our team can address. 

I think that we are safe to close this issue, but will leave it open for you to review.
