### ISSUE TITLE
Namespaces ending with -system are automatically seen as System Namespaces

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10214]
Internal reference: SURE-6914

When you create a namespace that contains `-system` it will always be handled as a system project and cannot be seen by users of the project.

We should have a curated list of Rancher's system namespaces and only use those, rather than assuming all namespaces ending in `-system` are system namespaces.

**Comment by gaktive** [comment]
The logic comes in here: https://github.com/rancher/dashboard/pull/877/files#diff-591a2bd4286c66a09c70300de8f96ef6961fb72f0fbbe0f3dfba610d1cd3b14dR16

**Comment by gaktive** [comment]
We have a list of the known internal namespaces that is called in https://github.com/vincent99/dashboard/blob/464eac6d5cd2293386557a0e3235a62f4318a2a8/models/namespace.js and we can see in line 16 there's a `-system` reference.

**Comment by izaac** [comment]
Assuming the display is based on annotations mentioned in the Unit test. This looks good to me.
