### ISSUE TITLE
Do not have access 

### ISSUE THREAD

**Issue by pallavinuuday** [rancher/dashboard#10223]
Do not have access to below ids
M103379 ,M105193

Please do the needful. Attached screenshots of My team member Martin(A70558) Who has access to it.
We need similar access. 

![MicrosoftTeams-image (3)](https://github.com/rancher/dashboard/assets/130357482/0ad19874-1524-4bb6-8b00-1a1a4a24704d)
![MicrosoftTeams-image (6)](https://github.com/rancher/dashboard/assets/130357482/ebc17ca6-1d32-4a19-8d30-a7ab32cdefd2)
![MicrosoftTeams-image (4)](https://github.com/rancher/dashboard/assets/130357482/20231bf6-1040-4dab-b096-e20a7cddaadd)
![MicrosoftTeams-image (5)](https://github.com/rancher/dashboard/assets/130357482/aa60d506-eb89-423f-9843-88964b1129af)

**Comment by richard-cox** [comment]
This seems like a permissions request for a user of the system, rather than a bug in the way permissions are handled. 

If so please contact the host of your Rancher instance.
