### ISSUE TITLE
The grafana links for rancher workload monitoring obtained an incorrect replicaset

### ISSUE THREAD

**Issue by cyfkobe** [rancher/dashboard#10236]
Edit: SURE-8551

rancher version：2.7.9

grafana button renders into a wrong replicaset

![image](https://github.com/rancher/dashboard/assets/50159489/6aab2d13-43c3-455f-91b0-880f47fbad9e)

![image](https://github.com/rancher/dashboard/assets/50159489/1b81fd51-68a4-45e4-9245-5545e828edd6)

**Comment by github-cyf** [comment]
![image](https://github.com/rancher/dashboard/assets/50159489/2cf7eb08-827c-47f7-9f85-c1cf822e7305)

**Comment by github-cyf** [comment]
![image](https://github.com/rancher/dashboard/assets/50159489/86b6ec07-6455-49a7-a9dc-e4c331013d69)
@richard-cox
