### ISSUE TITLE
Global Settings: Banners: Text is removed from input field after user focuses on different page element

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#10249]
**Setup**
- Rancher version: v2.8.0
- Dashboard version:
- Browser type & version: Any

**Describe the bug**
Text is removed from the input field after the user focuses on a different page element. This issue is specific to localhost setup and for the Header Banner, Footer Banner, and Login Screen Banner only.

**To Reproduce**

1. run Rancher instance locally
2. login to Rancher UI as an admin
3. go to Global Settings -> Banners (https://localhost:8005/c/local/settings/banners)
4. go to 'Header Banner' section 
5. select the checkbox for 'Show Banner in Header'
6. Type banner description in input field ('test') 
7. click anywhere on the page
8. notice text is removed from the input field
9. go to remote setup (https://yonasb.qa.rancher.space/dashboard/c/local/settings/banners)
10. repeat steps 4-7
11. notice text is not removed from the input field

**Result**
Text is removed from the input field after the user focuses on a different page element.

**Expected Result**
Text remains in the input field after the user focuses on a different page element.

**Screenshots**

https://github.com/rancher/dashboard/assets/127343932/57bde139-a1c8-49c3-b1db-75951e4b496f

**Comment by aalves08** [comment]
@yonasberhe23 PR merged. Problem should be fixed

**Comment by yonasberhe23** [comment]
Bug fix tested and no regressions found. Tested on both localhost and remote setups. 

This bug was caught via UI Automation so coverage is sufficient here.
