### ISSUE TITLE
[Alerting V2] UI Requirements

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1024]
These UI requirements will add on to the existing UI requirements for Monitoring V2 found in https://github.com/rancher/dashboard/issues/803, https://github.com/rancher/dashboard/issues/908, and https://github.com/rancher/dashboard/issues/909 to specifically add support for Alerting V2.

Minimum Requirements for Release:
- Basic Configuration (https://github.com/rancher/dashboard/issues/1015)
- Create default AlertManager Config Secret on deploy (https://github.com/rancher/dashboard/issues/1088)
- A UI for creating / configuring PrometheusRules CRs (https://github.com/rancher/dashboard/issues/811)

Additional Requests (in order of prioritization):
- Custom Component for Alertmanager Receivers - Detail Page (https://github.com/rancher/dashboard/issues/1238)
- Custom Component for Alertmanager Routes - Detail Page (https://github.com/rancher/dashboard/issues/1239)
- ~Custom UI Component for Alertmanager Config - Basic Configuration  (https://github.com/rancher/dashboard/issues/1017)~
- Advanced Configuration (https://github.com/rancher/dashboard/issues/1014)
- ~Update Basic Configuration for AlertManager Config (https://github.com/rancher/dashboard/issues/1023)~
- Custom UI Component for Alertmanager Config - Advanced Configuration (https://github.com/rancher/dashboard/issues/1216)

**Comment by deniseschannon** [comment]
As these are mostly epics for the entire UI requirements of the feature, I"m going to remove the milestone as all tickets for the feature are tracked separately.

**Comment by deniseschannon** [comment]
Since all the other UI tickets are tracked in individual tickets, I'm going to close this issue.
