### ISSUE TITLE
clone service failed

### ISSUE THREAD

**Issue by ly5156** [rancher/dashboard#10252]
**Setup**
- Rancher version: v2.8.0
- Rancher UI Extensions: v2.8.0

**Describe the bug**

1. When cloning an existing service, you cannot delete or reset the clusterIPs field on the form page because it does not have a form that sets the clusterIPs field.

**To Reproduce**

1. clone a cluster ip service
2. set cluster ip to empty
3. save

**Result**
save failed

**Expected Result**

1. remove clusterIPs field when clone a service
ref: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#service-v1-core

**Screenshots**

<img width="1366" alt="image" src="https://github.com/rancher/dashboard/assets/3406205/49ca20de-66e7-4f8b-9c24-3712deb196db">

**Additional context**

**Comment by yonasberhe23** [comment]
When cloning a service and the IP address reset/empty and it's saved as an empty string, the original IP is used, is that behavior expected? when in create mode and the user tries to create a service with the same IP as another service, it fails with "...provided IP is already allocated" so I'm guessing we shouldn't allow this?

See the below recordings: the file was too large so I split it into two parts.

https://zube.io/files/rancher/47f7774c3b77dbc3e5f2ad7a8ef9f968-screen-recording-2024-03-29-at-1-50-48-pm-part1.mov



https://zube.io/files/rancher/3221af23ff9670bd361105d85920fb21-screen-recording-2024-03-29-at-1-50-48-pm-part2.mov

CC: @jordojordo

**Comment by ly5156** [comment]
Referring to the k8s [kubernetes-api documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#service-v1-core), the clusterIP can be set to an empty string. If the clusterIP is an empty string and the clusterIPs attribute is deleted, the back-end will reassign a new ip to the service.

**Comment by yonasberhe23** [comment]
thanks for confirming the behavior @ly5156. The backend is in fact reassigning a new IP to the service if the clusterIP is an empty string when cloning a service

**Comment by yonasberhe23** [comment]
unit test coverage is suffice. moving to Done cc @izaac
