### ISSUE TITLE
[RKE2 - vSphere] Getting a TypeError when closing an error banner

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#10250]
**Setup**
- Rancher version: 2.8-head & 2.9-head

**Describe the bug**
When you try to close an error banner on vSphere's edit config page, the app breaks(in local env) and you get "TypeError: handler.apply is not a function". The problem is `fvUnreportedValidationErrors` that is a computed prop but it's getting invoked like a function when passed to `CruResource` in `rke2.vue`.

**To Reproduce**

Create a vSphere cluster with Terraform and come to Rancher's Edit Config page.

**Screenshots**

https://github.com/rancher/dashboard/assets/135728925/a3a00425-dae2-4106-9666-6d34abb86837

**Comment by rak-phillip** [comment]
Confirmed that dismissing banners with vSphere does not produce an error in the console.
