### ISSUE TITLE
[BUG] Rancher 2.7. `e.availableActions is undefined`

### ISSUE THREAD

**Issue by ChrisMcKee** [rancher/dashboard#10257]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option: HELM on EKS, K8 version 26
- Proxy/Cert Details: proxied via ELB; ingres is haproxy running as a daemon on hostport
- browser: firefox (115.0.2 (64-bit)) on windows

**Information about the Cluster**
- Kubernetes version:  v1.26.6-eks-a5565ad 
- Cluster Type (Local/Downstream):Local (rancher)

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

While using a cluster randomly this will pop-up during a background refresh and just crashes there.

Console Error
```
e.availableActions is undefined [console.js:31:30](webpack:///shell/plugins/console.js)
    e console.js:31
    e client.js:111
    Babel 7
```
![image](https://github.com/rancher/rancher/assets/83597/086390d9-fa41-496c-b809-45dec57e1da1)

Possibly unrelated but I also see this xhr error
`https://mydomain/api/v1/namespaces/cattle-ui-plugin-system/services/http:ui-plugin-operator:80/proxy/index.json`

**Comment by gaktive** [comment]
Will be fixed via https://github.com/rancher/dashboard/issues/9979 which will be in 2.8.0 and then a subsequent 2.7.x release. However, there may be newer console errors that appear that will have use so if you see this again after upgrading, let us know.
