### ISSUE TITLE
Cluster Explorer: Events: User must refresh the page to see cluster events when using localhost proxy setup.

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#10265]
**Setup**
- Rancher version: v2.8.0
- Dashboard version:
- Browser type & version: Any

**Describe the bug**
When using localhost proxy setup the cluster events do not load until the user refreshes the page. This issue is specific to localhost proxy setup.

**To Reproduce**

1. run Rancher instance locally
2. login to Rancher UI as an admin user
3. go to cluster explorer page (https://localhost:8005/c/local/explorer#cluster-events)
4. scroll down to events table > click 'Full events list' link 
5. notice events are not displayed
6. refresh the page
7. notice events are displayed
9. go to remote setup (https://yonasb.qa.rancher.space/dashboard/c/local/explorer#cluster-events)
10. repeat steps 3-4
11. notice events display without page refresh

**Result**
User must refresh the page to see cluster events when using localhost proxy setup.

**Expected Result**
User should not need to refresh the page to see cluster events when using localhost proxy setup.

**Screenshots**

https://github.com/rancher/dashboard/assets/127343932/528869cc-507f-4f23-8522-7621a8b80bca

**Additional Requests**
- Please check for this bug on 2.8
- Once the issue has been resolved please re-enable the [e2e test](https://github.com/rancher/dashboard/blob/550639f73d6c2fd28003ba72e627d4814616529b/cypress/e2e/tests/pages/explorer/cluster-dashboard.spec.ts#L152) associated with this feature (just remove the `.skip` from the test)

**Comment by richard-cox** [comment]
We should check this also doesn't happen in 2.8

**Comment by nwmac** [comment]
Checked with latest and this is still an issue - need to understand why in case there is an underlying issue.
