### ISSUE TITLE
Update hard-coded GKE region list

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10264]
Internal Reference: SURE-7361

There is no northamerica-northeast2 region for the GKE cluster location

The region list here needs updating:

https://github.com/rancher/ui/blob/master/lib/shared/addon/google/service.js#L95

**Comment by kkaempf** [comment]
Viewing available regions and zones: https://cloud.google.com/compute/docs/regions-zones/viewing-regions-zones

**Comment by gaktive** [comment]
Will need backport tickets for 2.8 and 2.7.

**Comment by aalves08** [comment]
Another reference in terms of regions: https://cloud.google.com/compute/docs/regions-zones

**Comment by nwmac** [comment]
@aalves08 This was closed as completed - I didn't see any QA though?

**Comment by aalves08** [comment]
You are right @nwmac . Must have closed this by mistake. QA should do manual check on this. Pretty straightforward to validate.

**Comment by gaktive** [comment]
Reopening and passing to QA.

**Comment by gaktive** [comment]
Validated by @IsaSih in QA in 2.7.11. I'll allow QA to determine if they want to retest in later versions but in the past, if it passed on one, they can mark it closed elsewhere.
