### ISSUE TITLE
Logging UI V2 Output Sidebar

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1027]
Users should see a list of outputs in the sidebar of chart options. Users should be able to configure multiple outputs at the same time.

**Comment by codyrancher** [comment]
Per https://github.com/rancher/dashboard/pull/1048#issuecomment-675781423 this is no longer relevant. @deniseschannon mind if I close this?

**Comment by deniseschannon** [comment]
Yes, we can close this and a new one would be made for how to configure the outputs as part of the CRDs.
