### ISSUE TITLE
AWS region list needs updating

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10294]
AWS region lists for EC2 and EKS are out of date - need to update these with latest values.

Testing: Validate that ca-west-1 region is available when provisioning an AWS or EKS clister

**Comment by atifhafeez** [comment]
When it is expected to have a new release that includes this update? We have an urgent deployment pending due to missing ca-west-1 region?

As per my understanding the update is required in dashboard (PR merged) and machine repos (still pending).

**Comment by skanakal** [comment]
@nwmac looks like ca-west-1 not fetched , see this  https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L5778 
but its there in EKS... https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L6009

**Comment by nwmac** [comment]
@skanakal That first link is to ebs not ec2, but regardless, I've ran the script again and `ca-west-1` is now there for ec2.

Created a new PR for this: https://github.com/rancher/ui/pull/5124

**Comment by skanakal** [comment]
@nwmac Seems they recently updated it... 
https://github.com/boto/botocore/issues/3101 I don't know if we can rely on `endpoints.json`  

see this https://github.com/aws/aws-sdk/issues/206#issuecomment-1471354853

> Upon discussing this further with a colleague we wanted to clarify that the Python SDK team is currently investigating paths forward for this method, and deprecation is one possible outcome. Here is why:
> 
> As mentioned above, the source of information returned by get_available_regions is the endpoints.json file. This file is embedded in botocore and until version 1.28.0 was used for endpoint resolution in botocore.
> 
> The get_available_regions method was introduced many years ago as a secondary use of endpoints.json data, long before other sources of service availability were available. This has always been a sub-optimal solution because the information in endpoints.json is inherently frozen at release time. And even at release time the data in endpoints.json may lag behind reality due to how it is generated internally. The boto3 documentation addresses this (the function is not documented in the botocore documentation).
> 
> Since get_available_regions was introduced, [the SSM Parameter Store API was introduced](https://aws.amazon.com/blogs/aws/new-query-for-aws-regions-endpoints-and-more-using-aws-systems-manager-parameter-store/) to solve the same user need better in 2019. Endpoint resolution in SDKs migrated to a different data source starting with botocore 1.28.0. As a result, endpoints.json will become an even less complete and up-to-date data source.
> 
> If completeness and recency of information is important for your use, switching to the SSM API is, and has been, the recommended approach.

**Comment by IsaSih** [comment]
Tests pass for EKS and EC2/rke1 but fails for EC2/rke2. 
![Screenshot 2024-04-04 at 12.49.16 AM.png](https://zube.io/files/rancher/b5fbc102a47ac9bf50db49c57251cb8a-screenshot-2024-04-04-at-12-49-16-am.png)
Moving back to To do

**Comment by IsaSih** [comment]
All tests pass now. Moving to done
