### ISSUE TITLE
ec2 RKE1 cloud provider upgrade warning banner stays when version change is reverted

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#10290]
When upgrading ec2 rke1 clusters to k8s >=1.27, if the cloud provider was aws in-tree the ui changes it to external-aws and shows a warning banner. If the user switches the k8s version back to <1.27, the cloud provider is changed back to aws in-tree, but the banner stays:

https://github.com/rancher/dashboard/assets/42977925/8b05cb13-0571-4cd8-bbf1-bcb92916f7bc

**Comment by mantis-toboggan-md** [comment]
PR to fix this is here: https://github.com/rancher/ui/pull/5105

**Comment by IsaSih** [comment]
No longer reproducible as the version v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head no longer supports kubernetes version lower than 1.27 for RKE1 AWS cluster provisioning
