### ISSUE TITLE
Registry authentication method is modified unexpectedly

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10314]
Internal reference: SURE-7465
Reported in 2.8.0

Issue description:
Registry authentication method is modified unexpectedly.

Actual behavior:
Authentication of docker.io Registry is modified from None to HTTP Basic Auth.

Expected behavior:
Authentication of docker.io Registry is not modified.

No workaround.

Repro steps:

1. [Create a Downstream Cluster]
- Create -> Amazon EC2 (RKE2)
- v1.27.8+rke2r1
- CNI Calico

2. [Configure Registry]
- Container Registry: docker.io
- Authentication: None

![1.png](https://zube.io/files/rancher/b4fbec654f4f03fd7ed1eb88999a602e-1.png)

3. Mirrors
- Registry Hostname: $REGISTRY_HOSTNAME

Registry Authentication
Registry Hostname: $REGISTRY_HOSTNAME
Authentication: Create a HTTP Basic Auth Secret
Username: user
Password: pass

![2.png](https://zube.io/files/rancher/d813a2eefeac53c9e7be4a33277fa7bd-2.png)

4. After Cluster created,
- Cluster Management -> Edit Config -> Registries

Authentication of docker.io Registry is modified from None to HTTP Basic Auth.

![3.png](https://zube.io/files/rancher/5257d450f35f1825a4136224f1a6b886-3.png)

**Comment by richard-cox** [comment]
Linking issues in same area https://github.com/rancher/dashboard/issues/10093

**Comment by richard-cox** [comment]
Introduced by https://github.com/rancher/dashboard/pull/7508
