### ISSUE TITLE
e.value is null

### ISSUE THREAD

**Issue by lindhe** [rancher/dashboard#10311]
**Setup**
- Rancher version: v2.7.6 
- Rancher UI Extensions: none?
- Browser type & version: Firefox 121.0.1 (64-bit) on Windows

**Describe the bug**

Frequently when I navigate the Rancher GUI, I get presented with a blank screen saying "e.value is null". It's not a great user experience and I find it annoying.

**To Reproduce**

Sorry for a bad bug report. I'm tired and just need to post this so I remember to do it. It _feels_ like "anything I do results in this", but that's mostly me being tired and having run into it about 10 times the last hour. I'll update this post if/when I can reliably reproduce it. Should not be too hard, I think…

**Result**

![image](https://github.com/rancher/dashboard/assets/7773090/ca151953-c290-425d-93ba-1aebcda2e279)

**Expected Result**

If something is wrong, give me a popup or warning on the screen, do not flush the whole web app with a less then helpful error message. If something is not wrong, please don't crash.

**Screenshots**

![Screenshot 2024-01-19 223956](https://github.com/rancher/dashboard/assets/7773090/f63c14d7-033a-4310-b1d0-45fa8ab6bc8a)
![image](https://github.com/rancher/dashboard/assets/7773090/eb0e1241-4313-4039-a449-f1df429597e8)

**Additional context**

Feels like this kind of bug should be easy to find with automated linting tools and/or typechecking.

Very similar to rancher/dashboard#10128

**Comment by richard-cox** [comment]
This will be the result of a developer error page mistakenly being shown in production and is resolved in 2.8 and the next feature release of 2.7 (for tracking see https://github.com/rancher/dashboard/issues/9542)

There will be an underlying error, but after upgrading if there are functional issues please just let us know via a fresh gh issue.
