### ISSUE TITLE
[CIS v2] UI Requirements

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1033]
Backend EPIC: https://github.com/rancher/rancher/issues/27723

Requirements:
1) Deploying CIS V2 Operator chart on dashboard which creates namespace and necessary CRD/CRs **[apiGroup: cis.cattle.io]**
2) Custom UI for listing ClusterScanBenchmarks, creating ClusterScanProfiles, running ClusterScans and viewing ClusterScanReport

Following are various UI tasks arranged in subtickets:

- Deploying App (https://github.com/rancher/dashboard/issues/1034)
- Navigation (https://github.com/rancher/dashboard/issues/1202)
- ClusterScanBenchmarks (https://github.com/rancher/dashboard/issues/1173)
- ClusterScanProfiles (https://github.com/rancher/dashboard/issues/1035)
- ClusterScan (https://github.com/rancher/dashboard/issues/1036)
- ClusterScanReport (https://github.com/rancher/dashboard/issues/1038)

- Feature Dashboard Page/ Overview (https://github.com/rancher/rancher/issues/28490)

More UI requirements (will add detail when available):
- Configuring Alerts and Notifiers for ClusterScan

**Comment by prachidamle** [comment]
@codyrancher please let me know if you need more information for the Overview page

**Comment by prachidamle** [comment]
Create Navigation ticket:

No create/edit for ClusterScanReport and ClusterScanBenchmark

Order of CRs for navigation:
CReport -> ClusterScan -> ClusterScanProfiles -> ClusterScanBenchmarks

**Comment by deniseschannon** [comment]
As this is the epic of all the UI tickets for CIS, I'm removing the milestone.

**Comment by deniseschannon** [comment]
All CIS tickets are taken care of except the ClusterScanBenchmark CRD ticket that we can look into when we want to custom UI forms for the ClusterScanBenchmark. Closing to track only the ClusterScanBenchmark ticket as it's own.
