### ISSUE TITLE
Unable to edit imported EKS cluster having self-managed nodes

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10335]
**Setup**
Rancher version: v2.8-d0a177f1745fe14a0b3de7483aa3ef895d1ab967-head
Rancher UI Extensions: None
Browser type & version: Chrome latest

**Describe the bug**
Unable to edit imported EKS cluster having self-managed nodes. Saving the changes after editing the cluster is not working.

**To Reproduce**
- Import EKS cluster having self-managed nodes
- Edit the cluster and upgrade k8s version or add cluster tags or enable logging, etc.

**Expected Result**
In https://github.com/rancher/eks-operator/issues/301, support is added for self-managed EKS nodes.
User must be able to edit and perform operations on imported EKS cluster having self-managed nodes

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/01f43413-259d-4fc0-a5d9-f1a3266068e0)

cc: @mjura @salasberryfin

**Comment by richard-cox** [comment]
Our go-forward milestone is 2.9.0 and we backport as required. Is this needed in 2.8?

**Comment by cpinjani** [comment]
The base [issue](https://github.com/rancher/eks-operator/issues/301) has milestone v2.8-Next1.
@kkaempf Can you please confirm the target milestone for this ?

**Comment by kkaempf** [comment]
The backend (aka `eks-operator`) fix will be shipped with 2.8-Next1.

I don't know the priority backlog of UI and if the issue at hand needs to be accelerated. Maybe @davidstauffer knows ?

**Comment by mantis-toboggan-md** [comment]
I've been working on fixing the UI side, correcting any invalid ui errors and making sure cluster information correctly populates the form; however, I found that I was not able to add node groups to imported EKS clusters with only self managed nodes. FYIU @cpinjani I filed a related issue https://github.com/rancher/rancher/issues/45982

**Comment by cpinjani** [comment]
Validation passed on the reported issue, able to perform cluster level edits on cluster.
Rancher - v2.9-637346f76ea2bb71a82ea6e00a2779f61610a2a4-head
Dashboard - master 3da1205

https://github.com/user-attachments/assets/83946a08-f2fe-4be8-918c-09b617db7cca
