### ISSUE TITLE
RKE2 Cluster Provisioning doesn't allow 'none' for container network

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10338]
Internal Reference: SURE-7482

RKE2 allows users to deploy custom cni to replace the default canal that comes with it.

This can be set in the RKE2 config file with "cni: none".

While provisioning RKE2 downstream cluster via Rancher UI, there is no option to select none in the container network field.

You have to click edit yaml and change it manually.

Need to add the option 'none' to the list for RKE2.

**Comment by nwmac** [comment]
@aalves08 This would be a simple one, I think.

I think we 'just' need to insert 'none' into the CNI list - should be able to do that with a computed, I think.

Need to think about tests - can we go to the create page and check that the request that we would send includes 'none'  correctly.

**Comment by gaktive** [comment]
@momesgin should this ticket be reopened as well? If this is actively worked on as part of a reopen, it's marked as closed.

**Comment by momesgin** [comment]
@gaktive I thought it would automatically be done by the bot, I'll reopen manually

**Comment by momesgin** [comment]
Since the new change was trivial I re-tested this issue myself, and it worked as expected, moving to done.
