### ISSUE TITLE
Improve error message for imported EKS cluster having zero nodes

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10334]
**Setup**
- Rancher version: v2.8-d0a177f1745fe14a0b3de7483aa3ef895d1ab967-head
- Rancher UI Extensions: None
- Browser type & version: Chrome latest

**Describe the bug**
Improve error message for imported EKS cluster having zero nodes

**To Reproduce**
Import EKS cluster having no nodegroups and no self-managed nodes

**Expected Result**
In https://github.com/rancher/eks-operator/issues/301, support is added for self-managed EKS nodes
So the error message needs to changed from "_Cluster must have at least one managed nodegroup_" to "_Cluster must have at least one managed nodegroup or one self-managed node_"

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/2ed57d99-eb81-4bea-8ee0-6b0faa76fa34)

cc: @mjura @salasberryfin

**Comment by richard-cox** [comment]
I don't think this is custom. So would come from either the `provisioning.cattle.io.cluster` or `management.cattle.io.cluster` resource for the cluster (i think the later, given it's not RKE2). specifically `metadata.state.description`.

https://github.com/rancher/dashboard/blob/67506b55c7b998c7597d3bfa856cec1352232943/shell/models/provisioning.cattle.io.cluster.js#L792

https://github.com/rancher/dashboard/blob/67506b55c7b998c7597d3bfa856cec1352232943/shell/plugins/dashboard-store/resource-class.js#L733

We need to confirm the above and transfer to the team responsible for the resource, so probably back your way @cpinjani

**Comment by richard-cox** [comment]
Closing as per comment in https://github.com/rancher/dashboard/issues/10334#issuecomment-1911821396. Please transfer and re-open, or recreate over at `rancher/eks-operator`
