### ISSUE TITLE
[CIS v2] UI to deploy the rancher-cis-benchmark chart 

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1034]
There will be a new "rancher-cis-benchmark" chart added for CIS v2. 

Cluster Admin can configure and enable CIS Operator chart under the Dashboard Apps.

“rancher-cis-benchmark” Chart that deploys the operator image in "clusterscan-system" namespace.

Chart installs following CRDS and few CRs
- ClusterScanProfile
- ClusterScan
- ScheduledScan
- ClusterScanReport

Basic Chart Fields/Values:

- nodeSelector: {} 
- tolerations: [] 
- resources: {} 
- Image:
  - cis-operator
     repository: rancher/clusterscan-operator
     tag: 
  - securityScan
     repository: rancher/security-scan
     tag: 
  - sonobuoy
     repository: rancher/sonobuoy-sonobuoy
     tag: v0.16.3

**Comment by prachidamle** [comment]
Make an app chart readme and add some description(2 lines) and link to kube-bench.

**Comment by deniseschannon** [comment]
Not necessary for 2.5 as there are no specific fields we need to specially configure for UI when deploying the chart.
