### ISSUE TITLE
Setting a Badge on Local Cluster Fails Attempting to Downgrade Cluster?

### ISSUE THREAD

**Issue by jberger** [rancher/dashboard#10352]
**Setup**
- Rancher version:
2.8.1
- Rancher UI Extensions:
None
- Browser type & version:
Firefox 121

**Describe the bug**
After running into https://github.com/rancher/dashboard/issues/9840#issuecomment-1915518215 I added badges for all the clusters, not just those that clashed. Trying to set a badge for the `local` cluster (which unlike the others is a manually installed RKE2 which is running Rancher itself) failed. Now if the failure had just been generic I wouldn't be filing the bug. The failure message appeared to say that setting the badge had failed to downgrade the cluster version! That would surely have been an epic failure. Luckily that downgrade was prevented by some catch mechanism, but surely that shouldn't happen at all when setting a badge right?

**To Reproduce**
Navigate to local cluster, attempt to set a badge for it.

**Result**
Failure as seen below

**Expected Result**
A badge set or even fail without attempting to alter the cluster beyond just the badge

**Screenshots**
![Screenshot 2024-01-29 at 2 36 09 PM](https://github.com/rancher/dashboard/assets/735765/f962f751-18c7-46b6-b914-8672a076c70f)

**Additional context**

**Comment by slickwarren** [comment]
on a local cluster running rke2 v1.27.8+rke2r1, I was not able to reproduce this issue when setting the local cluster's badge which is running rancher v2.8.1:
![image](https://github.com/rancher/dashboard/assets/16691014/e7c9db80-9985-4b04-b90f-82e7252197d4)

I'm on firefox 121 as well. I don't know how that error would have shown up but it is interesting. Do you have any information about what you were doing before setting the badges? i.e. had you attempted an upgrade?

**Comment by jberger** [comment]
Earlier in the day I had been updating one of the other clusters, yes, from 1.26.something to 1.27.something, but not this cluster and nothing to do with 1.24

**Comment by richard-cox** [comment]
Cluster badge information is saved as annotations on the target cluster's `/v3/cluster` resource. It could be that the kube version within that resource is out of step with the actual cluster's resource. What's the kube version of the cluster, and what does the value in `v3/clusters` state (visible via the brower's dev tool network requests tab)?

**Comment by jberger** [comment]
```
apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  annotations:
    management.cattle.io/current-cluster-controllers-version: 1.27.9+rke2r1
    ...
  name: local
...
```

vs

```
$ rke2 --version
rke2 version v1.27.9+rke2r1 (378bd59c4f0f97094c23c350d668f37f33aba406)
go version go1.20.12 X:boringcrypto
```

looks the same to me

**Comment by richard-cox** [comment]
Would you be able to provide the response to the `v3/cluster` network request the browser makes? there's additional information rancher adds and it could be somewhere in that chain

**Comment by jberger** [comment]
More specifically:

```
spec:
  rke2Config:
    kubernetesVersion: v1.24.12+rke2r1
```

I wonder how that happened. I guess that could be the original version that was running when I installed rancher. Both the cluster's rke2 and rancher have been updated since then.

**Comment by richard-cox** [comment]
Interesting, the annotation is correct but spec is not. I think this one might need a separate issue over at the `rancher/rancher` repo

**Comment by jberger** [comment]
I agree @richard-cox , are you able to migrate the ticket or should I open a new one there and link this one?

**Comment by jberger** [comment]
I guess there might still be an issue here as well though

**Comment by jberger** [comment]
I see several similar reports there already: 

* https://github.com/rancher/rancher/issues/43331
* https://github.com/rancher/rancher/issues/43172
* https://github.com/rancher/rancher/issues/42313

**Comment by richard-cox** [comment]
https://github.com/rancher/rancher/issues/43331looks like the one!
