### ISSUE TITLE
[CIS v2] UI for ClusterScanProfile CRUD

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1035]
Need UI to be able to handle ClusterScanProfile CRs:

**ClusterScanProfile CRD Explanation:**

- A ClusterScanProfile defines the parameters to configure and run a CIS scan. 
- Using the same ClusterScanProfile, multiple CIS scans can be launched.

- A ClusterScanProfile specifies following fields:
  - BenchmarkVersion: This is the benchmarkVersion name to be chosen from the list of available ClusterScanBenchmarks.
  - SkipTests: Specifies any CIS test Id's to be skipped from the chosen BenchmarkVersion, when a scan is launched to run 
     this profile. The ClusterScanReport will indicate these tests as skipped.

- When the rancher-cis-benchmark feature is enabled in dashboard, there will be few default built-in ClusterScanProfiles 
   added:
   a) rke-profile-permissive
   b) rke-profile-hardened
   c) gke-profile
   d) eks-profile
   e) cis-1.5-profile

- If a user edits the default ClusterScanProfiles, the next chart update will reset them back. So it is advisable for users to not edit the default ClusterScanProfiles, but create new ClusterScanProfiles if they want to change the profile data to run.

- ClusterScanProfile  CR defines the scan profile and other fields like:
   - BenchmarkVersion string `json:"benchmarkVersion,omitempty"`
   - SkipTests []string `json:"skipTests,omitempty"`

UI options:

- Create From YAML
- [Optional] Create using Form:
  - BenchmarkVersion  String:  dropdown of available ClusterScanBenchmarkVersion Name's
  - SkipTests array with +Add option
- Edit/Clone YAML
- Download YAML
- Delete

**Comment by deniseschannon** [comment]
Create Page:
- Dropdown of ClusterScanBenchmarks
- Ability to input an array of textboxes

**Comment by lvuch** [comment]
https://xd.adobe.com/view/9f93a45a-b207-468e-9be5-5e42ec33be5a-cac0/

**Comment by deniseschannon** [comment]
Benchmark Version 
- [ ] Dropdown of list of available ClusterScanBenchmarks
- [ ] Default -> `rke-profile-permissive`

Tests to Skip
- Do not show textbox until "Add Test ID" is used.

**Comment by prachidamle** [comment]
Tried the ClusterScanProfile UI, following are the observations:

1. Listing is all good
2. Create Form:
  -  looks good, is able to list all applicable ClusterScanBenchmarks
  - Able to add TestId using `Add TestId` option
  -  But when I add few testId's and then switch to YAML view, it shows no testIds in the yaml
  - After Creating, testIds are populated fine.

Issue is that Yaml view in Create option does not show the TestIds user Adds.

**Create Form can add TestIds:**

<img width="1193" alt="Screen Shot 2020-09-17 at 9 43 53 AM" src="https://user-images.githubusercontent.com/1470602/93505594-ee690480-f8cf-11ea-9588-76f8e7b71342.png">

**But Yaml view shows no TestIds:**

<img width="1198" alt="Screen Shot 2020-09-17 at 9 44 03 AM" src="https://user-images.githubusercontent.com/1470602/93505642-f88b0300-f8cf-11ea-8034-2bc6b794d904.png">

**Comment by sowmyav27** [comment]
**On master-head - commit id: `0ccce4501`**

Validated the following scenarios:

- Create a custom profile and run scan using this profile
- Create a custom profile with skips and run scan using this profile. Tests seen skipped.
- Clone a profile. Run scan using this profile
- Create a custom profile from Yaml and run scan using this profile
- Delete profiles
- Download profile yaml files
- Clone as form and run scan using this profile
- Clone as yaml and run scan using this profile
- Create profile--> add few testId's and then switch to YAML view --> shows testIds in the yaml --> create profile.

Issues in this area have been logged separately. Closing this issue
