### ISSUE TITLE
Create automation to ensure presence of all i18n entries

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#10358]
# Description

Ensure presence of the 7500+ entries in the i18n file as CI automation on PRs (GH action workflow).

## Context

As occurred in more scenarios and specifically for rancher/dashboard#9968 an entry was missing and displayed as `unknown`, although this should not be verified as a single case.

An attempted single case has [been handled](https://github.com/rancher/dashboard/blob/102f4e63e2970b6f7fa573586997d1f5501f444e/shell/models/__tests__/storage.k8s.io.storageclass.test.ts) (thanks @aalves08), clashing with other configurations. 

The i18n could eventually be retrieved with:

```ts
const yaml = require('js-yaml');
const fs = require('fs');

const translationData = yaml.load(fs.readFileSync(`${ process.cwd() }/shell/assets/translations/en-us.yaml`, 'utf8'));
```

The static entries may be retrieved with a RegEx through the files which use `this.t()` or `t()`, Vue text interpolation, etc

**Comment by aalves08** [comment]
FYI @aalves08

**Comment by gaktive** [comment]
Updating version number here since the PR was marked 2.9.0 but this ticket was 2.9.x. Hopefully the QA none label still applies here.

**Comment by cnotv** [comment]
> Updating version number here since the PR was marked 2.9.0 but this ticket was 2.9.x. Hopefully the QA none label still applies here.

It's a test automation, so yes 😄
