### ISSUE TITLE
[CIS v2] ClusterScan CRD - Create/List/Detail

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1036]
Need UI to be able to handle ClusterScan CRs:

**ClusterScan CRD Explanation:**

- A ClusterScan resource launches a new CIS scan on the cluster for a chosen ClusterScanProfile.
- To launch a scan, user should create a ClusterScan instance and specify a "ScanProfileName" from the list of ClusterScanProfiles available.
- The user may leave the "ScanProfileName" empty; theCIS  Operator will choose a default ClusterScanProfile applicable to the user's kubernetes cluster.
- Once a ClusterScan resource is created, the CIS Operator will launch the scan for the given ClusterScanProfile. Once the scan is complete, the status of the ClusterScan resource will indicate following:
  - LastRunTimestamp
  - Summary (number of tests total/fail/skip/not-applicable)

ClusterScan  CR fields:
- ScanProfileName string              `json:"scanProfileName,omitempty"`

ClusterScanStatus subresource:
- LastRunScanProfileName string        `json:"lastRunScanProfileName,omitempty"`
- LastRunTimestamp string             `yaml:"last_run_timestamp" json:"lastRunTimestamp"`
- Summary          *ClusterScanSummary `json:"summary,omitempty"`

ClusterScanSummary:
- Total         int `json:"total"`
- Pass          int `json:"pass"`
- Fail          int `json:"fail"`
- Skip          int `json:"skip"`
- NotApplicable int `json:"notApplicable"`

UI options needed:
- List ClusterScans, show columns like these to show state,name, profile-name, summary fields like pass/fail/skip etc:
<img width="1201" alt="Screen Shot 2020-08-13 at 7 47 36 AM" src="https://user-images.githubusercontent.com/1470602/90298972-1e446880-de49-11ea-89b6-d608b25b72bd.png">

- Create From YAML
- Run Scan (creates a ClusterScan CR with empty ScanProfileName: "" )
- Create new Scan (Create using Form):
   - ScanProfileName text field [Dropdown list of available clusterscanprofiles CR]
- Edit/Clone Scan Form
- Edit/Clone/Download YAML
- Delete
- Download/View Report when available
- UI to add Alerts and Notifiers

**Comment by prachidamle** [comment]
Add a new additionalPrinterColumn to display "ClusterScanReportName" after the report CR is generated.

**Comment by deniseschannon** [comment]
List Page
-  [ ] Add a column with a link to existing ClusterScanReport for that ClusterScan
- [ ] Add a button next to create for "Run Scan", which creates a CR with no name

Create Page
- [ ] No Name field

**Comment by lvuch** [comment]
https://xd.adobe.com/view/99d460e4-9a63-42a9-b2c1-e9443bb5d45b-cc87/

**Comment by prachidamle** [comment]
@codyrancher @vincent99 Can UI set `generateName` to have the ClusterScan CR name auto-generated so user doesn't have to specify it?

**Comment by prachidamle** [comment]
Issues:

1) After Installing `rancher-cis-benchmark` app, we only list the ClusterScanProfiles and ClusterScanBenchmarks. The ClusterScan CR is not shown in the left navigation - So user does not know how to run the first scan. 

   - We should show the ClusterScan in the left navigation with count 0, which will give user an option to create new scans.

<img width="558" alt="Screen Shot 2020-09-17 at 9 58 32 AM" src="https://user-images.githubusercontent.com/1470602/93506843-ae0a8600-f8d1-11ea-9491-4daf2a0600c1.png">


I searched for ClusterScan CR resource and then created a new scan.

**Comment by prachidamle** [comment]
Observations about "ClusterScanReports":

1. The ClusterScanReport:
 - The Detail view is listing all tests ran with state. However it populates the Nodes the test ran on in a single column. If a cluster has lot of nodes, this column can easily overflow.

<img width="1161" alt="Screen Shot 2020-09-17 at 9 51 31 AM" src="https://user-images.githubusercontent.com/1470602/93511275-64bd3500-f8d7-11ea-9cf8-25f9485adbfb.png">

- The Download Report link works, but in CIS v1 we downloaded a .csv file with the json data populated in it. Can we create a .csv in v2 as well?

**Comment by vincent99** [comment]
1) They should go to the CIS Benchmark "product" in the top-left menu.  The Explorer nav "more resources" are only shown if there is >0 of them.

2) Dunno but the ui is filtering for matching clusterProvider, min and maxKubernetesVersion so either the logic or data are wrong.

3) This is a general problem with the backend sending change events.. it works sometimes.

**Comment by prachidamle** [comment]
> 2. Dunno but the ui is filtering for matching clusterProvider, min and maxKubernetesVersion so either the logic or data are wrong.

This is just listing the ClusterScanProfiles CR names of all profiles available in the cluster - the matching should be done using the ClusterScanBenchmark that the profile uses - from the ClusterScanBenchmark, you can check the cluster provider to see if it's valid with the actual's cluster provider. You can also check the min/max k8s version sfrom the ClusterScanBenchmark to see if the cluster's k8s version is valid. After ClusterScanBenchmark matches the cluster, the dropdown should show that ClusterScanProfile name

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ed2749841`**

On a cluster --> Dashboard --> App --> Charts --> Deploy CIS benchmark app
Create a scan on this cluster
Click on the scan to go to scan details page

**Issue#1**
- Expand a test . Nodes on which the scan has run is not available.
<img width="1193" alt="Screen Shot 2020-09-21 at 10 11 33 PM" src="https://user-images.githubusercontent.com/26032343/93846206-4600ca80-fc58-11ea-8345-353d7f60e5b4.png">


**Issue#2**
- Few tests have `Mixed` state. On expanding the test in the scan detail page, status of the scan on each node is NOT available.
<img width="834" alt="Screen Shot 2020-09-21 at 10 17 31 PM" src="https://user-images.githubusercontent.com/26032343/93846266-6466c600-fc58-11ea-8870-2897e03b96a7.png">

**Issue#3**
- Pass/Mixed/Failed tests all have `yellow` background. Can we show red color for Fail, green for Passed and yellow for Not Applicable?
<img width="764" alt="Screen Shot 2020-09-21 at 10 11 57 PM" src="https://user-images.githubusercontent.com/26032343/93846302-7e080d80-fc58-11ea-9894-717c0a06da63.png">

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e9a98a3`**

On a custom RKE cluster, run a scan on the cluster.

Issue#1 --> Is seen fixed. 
Every test has nodes listed. 

Issue#2 --> State of the test result is not seen on the test details i.e. nodes listed do NOT show the state of the test. Can we have the state of the test included for every node  ? - Logging a separate bug to track this https://github.com/rancher/dashboard/issues/1378

Issue#3 --> is seen fixed 
red color for Fail, green for Passed and yellow for Not Applicable is seen on the UI
