### ISSUE TITLE
Rancher UI sidebar disappeared after upgrade from 2.7.9 to 2.8.1

### ISSUE THREAD

**Issue by ygirerd** [rancher/dashboard#10368]
**Rancher Server Setup**
- Rancher version: 2.8.1
- Installation option (Docker install/Helm Chart): docker install

**Describe the bug**

I upgrade from 2.7.9 to 2.8.1 and then, Rancher UI sidebar disappeared:
![image](https://github.com/rancher/rancher/assets/89632925/fa2cbf1a-75dd-4845-a36d-24559cfdf7f0)

I tried with Firefox, Chrome and even Edge. I have a Javascript issue:
![image](https://github.com/rancher/rancher/assets/89632925/9597dcbd-c515-4479-a09c-6256a34727d9)

I tried to upgrade from a fresh v2.7.9 install to v2.8.1 and sidebar is working fine. So, something in my config should make the sidebar not working but what??!!

**Expected Result**
I except to have this:
![image](https://github.com/rancher/rancher/assets/89632925/8aa50e7f-0c52-489f-857a-15d5417e73f3)

Thanks

**Comment by gaktive** [comment]
Looks related to https://github.com/rancher/dashboard/issues/10357

@ygirerd are you using custom banners at all? If so, do they rely on font sizes? The trace you provided seems to indicate as such.

As a workaround, can you remove the banners and reapply them? Let us know if that works at all or if you still don't see the side nav. We'll likely need to collect more info from you but I'll find someone closer to that code to assist.

**Comment by ygirerd** [comment]
Hello and thanks for the feedback.
Yes, I have a custom banners. The solution provided by @richard-cox works well. I have upgraded to v2.8.1 and all is working fine. 

Thanks for your time
