### ISSUE TITLE
Remove the need to fetch helm charts when editing an RKE1 cluster

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10362]
Internal Reference: ~SURE-7218~ A workaround has been found (using new OCI helm repo support to restrict number of third-party charts fetched)

**Is your feature request related to a problem? Please describe.**
- The create/edit component for prov clusters fetches (all) charts
- It does this to allow the user to choose to deploy RKE2 via cluster template and also if RKE2 is selected (to handle addon configuration)
- However when a user goes to Edit an RKE1 cluster we're still fetching the charts. For systems with a large number of charts this results in a step which can take a while to complete... which isn't needed

**Describe the solution you'd like**
- We should optimise the component to not fetch those charts if the user is editing an existing RKE1 cluster
- This comes with the caveat that the user will hit the same long download of charts when
  - Creating a cluster
  - The Apps pages in the local / upstream cluster
  - Managing extensions
  - Possibly others as well

**Additional context**
- We should be very careful not to break existing cluster based functionality that depends on charts

**Comment by gaktive** [comment]
Automation may be tricky since this requires an RKE1 cluster to be created, though E2E could help out here and maybe connected to Jenkins.

**Comment by nwmac** [comment]
@richard-cox is this needed for 2.9.0?

**Comment by momesgin** [comment]
@richard-cox I could see the api calls for getting the charts in 2.8 but not in 2.9 anymore. I suppose this's been done along with other performance improvements tickets.

**Comment by IsaSih** [comment]
Tests pass on v2.10-66ce2f133c38379570f59276799bebc222d9ef2d-head

Scenarios tested:

- editing an existing rke1 cluster
- Creating a new rke1, rke2 cluster
- Editing an existing k3s cluster
- The Apps page in the local cluster
- Managing extensions
