### ISSUE TITLE
parse-tag-name script targeting incorrect workflow type

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#10363]
**Describe the bug**

When running a an Extension release workflow the [`Parse Extension Name` step](https://github.com/rancher/dashboard/blob/b08e9288473b7c19c16e8825ed67d05f931d06cf/.github/workflows/build-extension-charts.yml#L73) the `parse-tag-name` script which has a condition checking for the [`charts` workflow type](https://github.com/rancher/dashboard/blob/b08e9288473b7c19c16e8825ed67d05f931d06cf/shell/scripts/extension/parse-tag-name#L8).

This causes the workflow to be automatically canceled as it was originally intended to check for naming collisions when releasing an Extension Catalog Image. Since this is now checking a "charts" release, the release tag name should absolutely equal a `pkg/<pkg-name>` causing the workflow to be canceled.

**To Reproduce**

See [this Elemental UI workflow action](https://github.com/rancher/elemental-ui/actions/runs/7724489669/job/21056821534#step:11:36) which was canceled.

**Result**
The workflow was canceled as `GITHUB_RELEASE_TAG` (`elemental-1.3.0-rc2`) matched `PKG_NAME` (`elemental-1.3.0-rc2`).

**Expected Result**

The workflow should have passed this step.

**Additional context**

The condition which checks for the workflow type should be checking for `catalog` instead of `charts`.

**Comment by nwmac** [comment]
@jordojordo I don't think we need QA to test this, as this is a script used for build/publish - is that correct? If so, can you move to done
