### ISSUE TITLE
[CIS v2] Need UI to be able to create and list a scheduled ClusterScan

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1037]
Ability to run clusterscans periodically. Creating ScheduledScan will create child ClusterScan resources periodically according to the schedule. Each ClusterScan will have Ownerreference set to point to ScheduledScan CR

ScheduledScan CR:
- ScanProfileName string
// Cron Expression for Schedule
- CronSchedule string `yaml:"cron_schedule" json:"cronSchedule,omitempty"`
// Number of past scans to keep
- Retention int `yaml:"retention" json:"retention,omitempty"`

ScheduledScan status:
- LastRunTimestamp
- LastClusterScanName

```
UI Options:
1) Add `Scheduled Scans` under the left Navigation on the CIS Benchmark App page
2) List available ScheduledScan CRs. Each will show the following fields to list as columns:
 - ScanProfileName
 - CronSchedule
 - Retention count
 - LastRunTimestamp
 - LastClusterScanName

3) Under each ScheduledScan, we can list the child ClusterScans that got created per schedule.

4) Create ScheduledScan
  - ScanProfileName text field [Dropdown list of available clusterscanprofiles CR]
  - CronSchedule
  - Retention

5) Delete ScheduledScan will also auto-delete the child ClusterScans
```

Form fields like this:
<img width="1310" alt="Screen Shot 2020-08-13 at 8 11 00 AM" src="https://user-images.githubusercontent.com/1470602/90299844-8779ab00-de4c-11ea-8168-d90f7a144170.png">

**Comment by prachidamle** [comment]
Backend PR  is ready: https://github.com/rancher/cis-operator/issues/27
@deniseschannon I have added the UI options and fields needed to show/create scheduledscans.

**Comment by prachidamle** [comment]
The design to add a new ScheduledScan CRD to support scheduling was reverted and changed to use the existing ClusterScan CR itself.

**New fields added to the ClusterScan CR Spec:**
// Cron Expression for Schedule
- CronSchedule string `yaml:"cron_schedule" json:"cronSchedule,omitempty"`
// Number of past scans to keep
- Retention int `yaml:"retention" json:"retention,omitempty"`

**New fields added to the ClusterScan Status:**
ClusterScan status:
- NextScanAt


```
UI Options:
1) Create Scheduled ClusterScan Form
  - ScanProfileName text field [Dropdown list of available clusterscanprofiles CR]
  - CronSchedule field
  - Retention field

2) ClusterScan Details page:
- View the latest run ClusterScanReport details
- Also a dropdown to List all the ClusterScanReports of the periodic scan available in the details page.
```
3) In the Listing of ClusterScans, is it possible to indicate it is a periodic/recurring scan

Form fields like this:
<img width="1310" alt="Screen Shot 2020-08-13 at 8 11 00 AM" src="https://user-images.githubusercontent.com/1470602/90299844-8779ab00-de4c-11ea-8168-d90f7a144170.png">

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `395b4fe77b`**

P1 use case of Scheduled scan has been validated:

- Create a scan CR
- Enable scheduled scan by entering in the Cron value and the retention count.
- Create Scan
- Scan runs are the scheduled interval
- All issues found are logged separately. Closing this issue
