### ISSUE TITLE
Imported RKE2 cluster not listed in the main menu

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#10377]
**Setup**
- Rancher version: Prime 2.8.1 
- Rancher UI Extensions: none
- Browser type & version: Firefox 115.6.0esr

**Describe the bug**
User admin does not have a cluster that was imported (by admin) listed in the main menu. Another user has is. 

**To Reproduce**
Installed Rancher and imported an RKE2 cluster. Not sure if it was listed in the beginning. 

**Result**
Imported cluster not listed in the main menu for user admin.

**Expected Result**
Cluster should be listed by default.

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/86831399/8307d538-c6cf-498d-bc25-66e5f08b441c)

**Additional context**

**Comment by torchiaf** [comment]
@peteingithub looks like the window here has been resized and the 3rd cluster in the list is quite not visible, except for the tiny line still visible under `RE1` icon.
I was able to replicate it:

![image](https://github.com/rancher/dashboard/assets/26394656/7133c6d2-9193-4e6c-9db5-b346c2e8dbe5)

I think we may have to improve the UI to highlights the presence of hidden icons.

**Comment by peteingithub** [comment]
Thanks Francesco, that actually is the issue. The other user (restricted admin) does not see the rancher cluster and for a two cluster env,  both see 2 clusters.
