### ISSUE TITLE
Custom roles showing as built-in after creation via UI

### ISSUE THREAD

**Issue by nickwsuse** [rancher/dashboard#10372]
**Setup**
- Rancher version: v2.8.s3-head ID: 16d9f5c
- Rancher UI Extensions: N/A
- Browser type & version: Chrome Version 120.0.6099.234

**Describe the bug**
When a restore of Rancher is done via the Rancher Backups chart, custom roles that were created before the restore took place are now showing that the role is a built-in role in the UI.

**To Reproduce**
1. Deploy Rancher v2.8.s3-head
2. Go to <host>/dashboard/c/local/auth/roles#GLOBAL
3. Create a new Global role with any rule(s)
4. Note that the UI shows the new role is built-in

**Result**
After a Rancher restore is completed, custom role templates are showing as built-in on the UI

**Expected Result**
Custom role templates continue to show as not built-in after a Rancher restore

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/107147272/dded4417-f852-42dd-aa97-6a5e6a465695)

**Comment by richard-cox** [comment]
@nickwsuse Would you be able to confirm if the global role returned via `/v1/management.cattle.io.globalroles` contains `builtin`? I don't think the UI does much more than display the value directly from the resource.

![image](https://github.com/rancher/dashboard/assets/18697775/378f57db-61f8-4db5-bb46-702b9b96546e)

**Comment by nickwsuse** [comment]
@richard-cox The global role in in `/v1/management.cattle.io.globalroles` does not contain builtin for the user created role.
![image](https://github.com/rancher/dashboard/assets/107147272/80795596-7492-4c1f-afb5-aae213613d09)

I also noticed that this is happening before a restore as well, as the screenshot above is from just after I created the role in the UI. I suppose I just didn't notice last time until after I had done a restore.

**Comment by richard-cox** [comment]
I reproduced this by going back to `https://releases.rancher.com/dashboard/release-2.8.0/index.html`, using `https://releases.rancher.com/dashboard/latest/index.html` (tracking 2.9.0) i could not.

Checked some 2.9.0 issues, it's this one https://github.com/rancher/dashboard/issues/9800
