### ISSUE TITLE
Adding registry authentication configs/mirrors throws error on console and adds broken values in YAML

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#10371]
**Setup**
- Rancher version: 2.7-head & 2.9-head

**Describe the bug**

When adding registry authentication configs on cluster's Edit Config page an error gets

**To Reproduce**

Start an RKE2 cluster creation process with any provider
Go to Registries Tab and enable the checkbox
Add a registry host
Click on "Show Advanced" and add a registry authentication
Save it and come back to the page

**Screenshots**

<img width="619" alt="image" src="https://github.com/rancher/dashboard/assets/135728925/9e08dbbf-aa83-4509-92c2-5135f7016889">

<img width="555" alt="image" src="https://github.com/rancher/dashboard/assets/135728925/ed1f1704-d209-48f5-bb40-f68d775a0005">

https://github.com/rancher/dashboard/assets/135728925/21f4d084-26ae-468a-b2b0-0930fafaf491

**Comment by momesgin** [comment]
cc @gaktive

**Comment by aalves08** [comment]
For an e2e, one could use https://github.com/rancher/dashboard/pull/10898 as a basis to build the test

**Comment by izaac** [comment]
Coverage looks good to me. Tests on generated YAML is enough as unit testing.
