### ISSUE TITLE
Setting proxy url for `pagerduty` receiver inputs wrong field

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#10389]
Internal ref: SURE-7508

**Setup**

SUSE Rancher 2.7.9, SUSE Rancher 2.8.0

**Describe the bug**

When setting the proxy URL field in the UI for the receiver in an alertmanagerconfig, it sends the YAML field proxyUrl, but the CRD asks for the field proxyURL as you can see in https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring-crd/102.0.1%2Bup40.1.2/crd-manifest/crd-alertmanagerconfigs.yaml#L720

**To Reproduce**

1. Install monitoringV2
2. Go to Monitoring -> AlertmanagerConfigs
3. Create a new AlertmanagerConfig -> Add a new Receiver -> Set a proxyUrl

**Result**
proxyUrl is not saved

**Screenshots**

**Additional context**

**Comment by nwmac** [comment]
automated e2e tests added with this PR: https://github.com/rancher/dashboard/pull/10745

**Comment by yonasberhe23** [comment]
e2e coverage looks good to me. moving to Done cc: @izaac
