### ISSUE TITLE
[CIS v2] ClusterScanReport CRD - List and Detail Page - Needs to add download report

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1038]
**ClusterScanReport CRD Explanation:**

Once a ClusterScan is completed, the report from the kube-bench tool is stored in a ClusterScanReport instance.

ClusterScanReport  CR fields:
- BenchmarkVersion string `json:"benchmarkVersion,omitempty"`
- LastRunTimestamp string             `yaml:"last_run_timestamp" json:"lastRunTimestamp"`
- ReportJSON string `json:"reportJSON"`

UI options:
- Report CR available after ClusterScan finishes
- **View detail report** can consume the ReportJSON like in 2.4 to show list of tests passed/skipped and nodes. So we should have a UI to consume the report and show result per test:

<img width="1315" alt="Screen Shot 2020-08-13 at 10 36 20 AM" src="https://user-images.githubusercontent.com/1470602/92077081-8d3e1e80-ed70-11ea-80fb-74f474a5b6ba.png">

<img width="1265" alt="Screen Shot 2020-08-13 at 10 36 28 AM" src="https://user-images.githubusercontent.com/1470602/92077059-831c2000-ed70-11ea-8797-787d09073e9d.png">

- **Download Report**
In 2.4 this was a link to download the reportJSON 
Now we are planning to put it in the CRD – do we need special way of downloading only the JSON?

**Comment by deniseschannon** [comment]
- [ ] Remove ability to create ClusterScanReport from list page of ClusterScanReport

**Comment by deniseschannon** [comment]
Moving this all to be incorporated as part of the CusterScan page
