### ISSUE TITLE
Incremental loading results in x2 requests for all resources

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10386]
**Setup**
- Rancher version: 2.7.7

**Describe the bug**
- When incremental loading is enabled (Global Settings --> Performance) the UI makes two requests
  - initial request (limit is 100 to show something quickly)
  - one more for actual incremental processing (limit is 1/4 of total). should be followed by another 3 requests for remaining resources
- However, since https://github.com/rancher/dashboard/pull/9300 in 2.7.7 the url contains duplicated `?` leading to limit being ignored
  - url now has `?exclude=metadata.managedFields`
  - supplemented with ```opt.url = `${ opt.url }?limit=100`;```
  - resulting in `?exclude=metadata.managedFields?limit=100`
  - k8s ignores the limit
  - both requests then contain all results
  - no further requests are made (no continue param)

**To Reproduce**
- incremental loading should be enabled (this is on by default)
- reduce the threshold for incremental loading to something as low as possible but above 100 (global settings --> performance --> incremental loading)
- navigate to a cluster resource that exceed the threshold

**Result**
- x2 requests to fetch the resource, both contain all resources

**Expected Result**
- 1 request with limit=100 only containing 100 resources
- 4 requests with limit=(resource count / 4) 

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/65be61b8-8792-46a4-9643-b9fee66fb0e1)

**Comment by mantis-toboggan-md** [comment]
I've verified that this is fixed:
1. set incremental loading threshold to 101
2. Created >100 events (and a few other resources eg pods) by deploying a few apps
3. checked network logs and verified that there are multiple requests to fetch a given resource, none of which contain all of the resource
