### ISSUE TITLE
Show architecture on nodes list and on cluster dashboard page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10382]
Internal Reference: SURE-7502

The node list page does not show the architecture of the node - we should add this as a column.

We should also add this to the cluster dashboard page - here, we need to look at all of the nodes and show 'something' that represents this - in most cases all nodes will have the same architecture, but there may be cases where there are (e.g.) worker nodes with different arch from the control plane.

The architecture can be read from the label `beta.kubernetes.io/arch`.

We should check how hosted providers provide this information.

Suggest on cluster dashboard we add something here:

<img width="651" alt="image" src="https://github.com/rancher/dashboard/assets/1955897/5dbf6450-1ea0-4ef2-9e4f-19d8aa7bade1">

Suggest:
- Architecture: amd_64 (shows the single architecture when they are all the same)
- Architecture: mixed (when they are not all the same - hover over this to show a tooltip with each of the architectures and the number of nodes for each)

**Comment by nwmac** [comment]
UX team will provide UX design for this - check before implementing

**Comment by gaktive** [comment]
Design: https://xd.adobe.com/view/5e0e823a-8de0-453b-9bfa-705fb0e5c992-0b5d/?fullscreen

**Comment by gaktive** [comment]
PR was merged for 2.9.0. QA has indicated that they can test this so we're lucky on capacity.
