### ISSUE TITLE
Navigation is sluggish

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10407]
Navigation between menu items, particularly in cluster explorer is sluggish.

Need to investigate and identify issues that can be fixed to improve navigation performance.

**Comment by aalves08** [comment]
Validated that issue has been fixed on Rancher `v2.9-a57f7025abdd80a2912f7fe53247ef7e1d4993de-head`. Navigation feels pretty fast and it's quite noticeable that the product does not changed, as claimed. Most noticing is going to the Apps -> Charts which would always re-trigger the product in the navigation and now it's also super quick.

I've got some performance metrics but I can't make much sense of them.

<img width="2417" alt="Screenshot 2024-07-10 at 14 08 06" src="https://github.com/rancher/dashboard/assets/97888974/5943ffcb-3a39-45fe-b638-8e80e1c4e85c">

Moving to done @izaac @IsaSih @yonasberhe23
