### ISSUE TITLE
Reduce the amount of events fetched in the Cluster Dashboard page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10408]
**Is your feature request related to a problem? Please describe.**
- The events table shown in the Cluster Dashboard (shell/pages/c/_cluster/explorer/EventsTable.vue) fetches ALL events
- On busy clusters this can be a LOT and cause very long request 
- These are non-blocking, but cause a lot of overhead (to fetch and store)

**Describe the solution you'd like**
- We should only fetch the most recent X (TBD) events

**Additional context**
- ~The other EventsTable (shell/components/EventsTable.vue) is not used anywhere and can be removed~
  - ~Added a long time ago for https://github.com/rancher/dashboard/pull/2342~
  - ~At some point it was removed from the page (there's a bug in the url as well, just went out to the local cluster)~

**Comment by kwwii** [comment]
Related to [7871](https://github.com/rancher/dashboard/issues/7871)

**Comment by richard-cox** [comment]
Pagination API docs https://github.com/rancher/steve

We should be able to do this via pagesize, page and sort by date

**Comment by nwmac** [comment]
@richard-cox Is this a must for 2.9?

**Comment by momesgin** [comment]
@richard-cox I assigned this to you as we discussed earlier it needs more investigation in terms of how we can do this without breaking the sorting.

**Comment by richard-cox** [comment]
@momesgin Chatted with Neil. Given these changes will be made obsolete when Vai is turned on we decided just to wait for that.
