### ISSUE TITLE
Warn users when trying to upgrade or delete a Installed Managed Chart

### ISSUE THREAD

**Issue by rohitsakala** [rancher/dashboard#10409]
A user reported a bug where the user was able to manually upgrade the rancher-webhook app. According to documentation https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook, it is a managed app which means it is installed, upgraded, and deleted by codebase. So, when the users performs these actions on managed charts in the Apps page of Rancher UI, the UI should throw a warning that it is not a recommended action.

A managed chart is the one which has the annotation catalog.cattle.io/managed:true in Chart.yaml

Acceptance Criteria

- [ ] In the Apps page, the user should be warned when trying to upgrade a managed chart app.
- [ ] In the Apps page, the user should be warned when trying to delete a managed chart app.

**Comment by richard-cox** [comment]
Linking SURE-6955

**Comment by gaktive** [comment]
Need to chat with Product on this and prioritization. This would then need some UX design before engineering works on this.

**Comment by kwwii** [comment]
I think we should add an alert on the helm chart edit page with something along the lines of
"Warning, Rancher manages deployment and upgrade of the XXXXXX app. Upgrading/Deleting(case dependent) this app is not supported. Under most circumstances, no user intervention should be needed to ensure that the XXXXXX version is compatible with the version of Rancher that you are running."

**Comment by gaktive** [comment]
Automation around this could look as simple as adding an annotation of a chart and then displaying the alert as @kwwii notes in his comment.

**Comment by gaktive** [comment]
@rohitsakala where is the annotation going to be? Once a chart is installed, how can we link back to the original app in case there are changes done on the backend? We suspect the annotation will be on the app so that we can trace the history properly.

**Comment by rohitsakala** [comment]
@gaktive the solution is already implemented [here](https://github.com/rancher/dashboard/blob/a8679f0df906a7d42a72b851b750100e1d028a50/shell/models/catalog.cattle.io.app.js#L72) in the UI codebase and UI also shows Managed in the Apps page column when this annotation is added to the Chart.yaml. 

The issue here is along with adding Managed in the Apps page column, the UI should also warn the user when he edit/upgrade the chart. So, I am assuming that the UI will use the same logic for showing **Managed** for **warning** the user about edit/upgrade of that particular App.
