### ISSUE TITLE
How to Build Rancher UI from Modified Source and Creating a Custom Image? (v2.8)

### ISSUE THREAD

**Issue by juchan133** [rancher/dashboard#10404]
Hello Rancher team,

I've been using the 2.6 version of Rancher, and in the past, I utilized the rancher:dev image, built with sudo make, which I then pushed to our Harbor registry and deployed to apply the changes.

Now, I've made modifications to the Vue.js-based dashboard, including adding language options and changing the title. After running the following command to generate the dist files:

`./scripts/build-embedded` # for embedding into rancher builds
`./scripts/build-hosted` # for hosting on a static file webserver and pointing Rancher's ui-dashboard-index at it
`yarn build`

I'm looking for guidance on how to create a Rancher image with these modified UI sources. Could you provide a step-by-step guide or any guidelines on how to proceed with building the Rancher image using the custom dist files?

[I referred to this.](https://rancher.github.io/dashboard/getting-started/quickstart)

**Comment by richard-cox** [comment]
The docker file referenced has been removed as it was not maintained. Generally we would advise against making custom builds and the remaining docs artefacts are being [tidied up](https://github.com/rancher/dashboard/pull/10405).

A custom title can be applied via three line burger menu --> Global Settings --> Branding --> Private Label. There you will find other branding options.

With the new Extension mechanism you can supply custom languages ([example](https://github.com/rancher/ui-plugin-examples/tree/main/extensions/uk-locale/0.1.0)). Note though this does not cover the log in page. We hope to resolve that in 2.9.
