### ISSUE TITLE
AKS cluster page while editing cluster showing old UI

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10416]
**Rancher version:**
`v2.9-b127983e2509c63090538cd1a92ce7ccf8fdabfb-head`

**Describe the bug**
AKS pages are moved to Vue in https://github.com/rancher/dashboard/issues/8965 and Import AKS option is addressed in https://github.com/rancher/dashboard/issues/10302
However the AKS page after editing the cluster, for provisioned/imported clusters still shows old UI (Ember)

**Steps**
- Go to Cluster management
- Click Import existing, Import and AKS cluster
- Edit the imported/provisioned AKS cluster

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/bc1e299f-2a0f-48f0-8998-af1f8e6ac169)

**Comment by mantis-toboggan-md** [comment]
This will be fixed by https://github.com/rancher/dashboard/pull/10581
