### ISSUE TITLE
RKE2 Registries - When multiple registry authentication hosts exist and one is removed, an incorrect secret name is rendered

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#10412]
**Setup**
- Rancher version: 2.9-head

**Describe the bug**

When you have multiple registry authentication hosts if you remove one of them the other one doesn't show its original secret name anymore. This is just a rendering issue since after save the payload still has the original secret name.

**Screenshots**

https://github.com/rancher/dashboard/assets/135728925/2eee1e79-98ff-45ce-90b4-c92ca87735e7

**Comment by aalves08** [comment]
possible `automation-candidate` if the cluster can be faked to go to EDIT view, something based of https://github.com/rancher/dashboard/blob/master/cypress/e2e/blueprints/nav/fake-cluster.ts as an example

**Comment by izaac** [comment]
https://github.com/rancher/dashboard/pull/10898#issuecomment-2101104810

**Comment by izaac** [comment]
I think I've missed some other PRs where the tests were updated. Moving to done.
