### ISSUE TITLE
Ability to customise background image of Rancher login page and Dashboard's banner

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10423]
Internal Reference: SURE-4860

Allow the user to customise the background image used on the Rancher login page:

![image](https://github.com/rancher/dashboard/assets/1955897/cc64c87f-0749-4f64-9af1-d960b3f648ad)

This should follow the pattern of other images and be added as a new settings:

1. `ui-login-background-light` - for the light theme image
2. `ui-login-background-dark` - for the dark theme image

![image](https://github.com/rancher/dashboard/assets/1955897/12b348da-17bc-4e91-be50-f45834b1dfe6)

Both a light and dark image should be supported.

The max file size should be 200Kb since this is a larger image.

NOTE: This will require a change to backend to allow these new settings to be accessed by anonymous users.

EDIT:

Adding 2 more settings to customize Banner image:

![image](https://github.com/rancher/dashboard/assets/26394656/7aaa34d0-349f-4e5c-9a8d-ce2218c3c67d)

1. `ui-banner-light` - for the banner, light theme image
2. `ui-banner-dark` - for the banner, dark theme image

**Comment by torchiaf** [comment]
back-end issue: https://github.com/rancher/rancher/issues/44577

**Comment by torchiaf** [comment]
> @torchiaf Should this go to 'QA Review', rather than Done?

Yes, I moved it in wrong column, but, why is it closed ?

**Comment by izaac** [comment]
Are there image sizes that could be validated besides the file size? The Cypress tests viewport sizes we're using is fixed so I believe this could be possible. cc @yonasberhe23

**Comment by yonasberhe23** [comment]
Tested in v2.9-c4b890ea174823b1b232d654db3f19dea89969ea-head

Login background (login page)

- able upload light/dark images ✅
- images reflected properly in light/dark mode ✅
- able to use original/custom background ✅
- various image sizes ✅
- errors out when attempting to add file size greater than 200kg ✅


Banner (dashboard home page)
- able upload light/dark images ✅
- images reflected properly in light/dark mode ✅
- able to use original/custom background ✅
- various image sizes ✅
- errors out when attempting to add file size greater than 200kg ✅
