### ISSUE TITLE
General Design Issues - Follow up from previous issues

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1042]
- [x] Border around "Create NameSpace/Create from HAML" bubble needs to be thicker or with a shadow to make it pop out more. Needs updated in Light and Dark Mode

<img width="237" alt="Screen Shot 2020-08-17 at 10 20 51 PM" src="https://user-images.githubusercontent.com/11410997/90473540-00406780-e0d8-11ea-9773-3209cf1db57d.png">

- [x] The notch has a different background from the actual background so it looks weird. 
<img width="74" alt="Screen Shot 2020-08-17 at 10 22 07 PM" src="https://user-images.githubusercontent.com/11410997/90473585-1bab7280-e0d8-11ea-9f8e-7e37a490b5a8.png">
<img width="129" alt="Screen Shot 2020-08-17 at 10 22 26 PM" src="https://user-images.githubusercontent.com/11410997/90473607-282fcb00-e0d8-11ea-91b5-90632ea24064.png">

- [x] Nav Bar "Jump to.." Dropdown - when exposing the dropdown, it needs to "pop" out more in light mode. The change made for dark mode is very distinct. 

<img width="260" alt="Screen Shot 2020-08-17 at 10 25 28 PM" src="https://user-images.githubusercontent.com/11410997/90473774-91174300-e0d8-11ea-8402-cca32dfc6d49.png">

- [x] Thickness of dropdown toggle is different thickness still:

<img width="86" alt="Screen Shot 2020-08-17 at 10 29 00 PM" src="https://user-images.githubusercontent.com/11410997/90473980-20245b00-e0d9-11ea-8833-be9c77cd9425.png">

**Comment by lvuch** [comment]
re:` Thickness of dropdown toggle is different thickness still`... dropdowns are different height then create buttons with dropdown
