### ISSUE TITLE
Cloud Credentials: Missing Credential Name

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#10424]
When editing a DigitalOcean cloud credential, the name field displays the placeholder and the field is marked as required. This can be potentially confusing for two reasons:

1. It's not clear which credential we are actually editing
2. It looks like the form is invalid 

## Expected Behavior

The name of the credential that's being edited is clearly displayed in the Credential Name field.  

![image](https://github.com/rancher/dashboard/assets/835961/d911df05-6bb8-404e-ab74-457bda5ca489)

**Comment by aalves08** [comment]
`norman` cloud creds have a different structure than `steve`creds. Different object structure

**Comment by gaktive** [comment]
There are a few things here to look at:
- when creating the cloud credential, if the name is required, we should use form validation to ensure it's not blank.
- however, duplicate names are allowed.
- these are Norman cloud creds, not Steve, so the metadata could actually be blank per the schema but based on this behaviour, we should force it.
- as noted, we have a red asterisk for a required field that's also commented as optional, so there's a discrepancy.

**Comment by gaktive** [comment]
@richard-cox confirmed that the Norman API allows for names to be changed.
