### ISSUE TITLE
AKS: Virtual network field not showing Subnets to provision the cluster

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10431]
**Setup**
Rancher version: `v2.9-4479597c19bb4f7a74c304aa621932d213a05532-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Unable to provision cluster with Network policy & Network plugin as Azure CNI
The virtual network drop-down does not lists Subnet, on old UI it does as below:

![image](https://github.com/rancher/dashboard/assets/73099870/17692d8b-f5bb-48ef-b344-34e6120fe906)

**To Reproduce**
- Create downstream AKS cluster and select Network policy & Network plugin as Azure, under Networking
- Select existing vNet under Virtual network
- Fill all other necessary fields and create cluster

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/b47172ba-48c3-4cd3-a5d1-f0c625ab28ef)

![image](https://github.com/rancher/dashboard/assets/73099870/490ed7c8-be60-4367-90a2-76488aba300e)

**Comment by yonasberhe23** [comment]
unit tests are sufficient. also did quick manual validation and all looks good. moving to done
