### ISSUE TITLE
Design Issues - User Preferences Page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1043]
Overall, can we layout it out to be prettier?

- [x] "Theme"
<img width="166" alt="Screen Shot 2020-08-17 at 10 33 27 PM" src="https://user-images.githubusercontent.com/11410997/90474234-b062a000-e0d9-11ea-97d0-9898e771a3e3.png">
 Heading seems very close to "Preferences"

- [ ]. Theme - Can we add in the icons of the sun and moon like we did in the old UI?
<img width="219" alt="Screen Shot 2020-08-17 at 10 31 20 PM" src="https://user-images.githubusercontent.com/11410997/90474110-64176000-e0d9-11ea-82ee-5588dcd136bd.png">

- [x] Formatting Section - Can we fix the alignment of these dropdowns? 
<img width="622" alt="Screen Shot 2020-08-17 at 10 31 43 PM" src="https://user-images.githubusercontent.com/11410997/90474124-709bb880-e0d9-11ea-9ea5-9df7209c6c3e.png">

- [ ]. Can we add an explanation of what enabling developer tools does? 

- [ ] In light mode, the white text on these grey buttons is hard to read

<img width="210" alt="Screen Shot 2020-08-17 at 10 32 51 PM" src="https://user-images.githubusercontent.com/11410997/90474205-99bc4900-e0d9-11ea-922b-a5ec711ad0fc.png">

**Comment by lvuch** [comment]
@deniseschannon -- in pr @vincent99 says we probably don't need to explain dev tools
