### ISSUE TITLE
Add cluster description to cluster side menu and main menu

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10441]
Internal reference: SURE-6691
Requested in 2.6.13

A user wants to add the cluster description to the Cluster Side menu and the main cluster menu. They have added some unique cluster information to the description field which is only visible when you open the full cluster view. It would become handy to have the cluster description already available in the cluster side menu without opening cluster by cluster to view and find the correct one.

Actual behavior:
No possible to see the description field in the burger menu.

Expected behavior:
Possible to read the description field directly in the burger menu, with no need to open the full cluster view.

@kwwii and @edenhernandez-suse have come up with an appropriate design: https://xd.adobe.com/view/c1936434-760f-44a6-8f7a-788b16f50722-94c0/?fullscreen

Note: Consider long descriptions and truncation

**Comment by yonasberhe23** [comment]
The e2e tests here cover the functionality of this feature well but there are instances that our e2e tests don't catch cosmetic bugs such as the below screenshots. I think it's worth doing a quick manual test for this. Moving to 'To Test'. @izaac 

![Screenshot 2024-03-25 at 11.20.19 AM.png](https://zube.io/files/rancher/80fb7abad4df6decc6c76fb9c5b5c227-screenshot-2024-03-25-at-11-20-19-am.png)

![Screenshot 2024-03-25 at 11.29.49 AM.png](https://zube.io/files/rancher/5872d5e9e589ea8b5b5a752e1710b263-screenshot-2024-03-25-at-11-29-49-am.png)

**Comment by izaac** [comment]
Visual Regression testing could be a good addition in the future using cypress. But for now I think a quick manual test would suffice.

**Comment by IsaSih** [comment]
This is currently working only for Amazon EC2 clusters. For descriptions in the local cluster, GKE and EKS clusters, the descriptions are only displayed in the cluster dashboard. They are NOT being displayed in both the Cluster Side menu and the main cluster menu. Moving it back to Reopened.

![Screenshot 2024-04-10 at 1.57.28 AM.png](https://zube.io/files/rancher/89bbd49631fe824c9bc18031fae5aa5d-screenshot-2024-04-10-at-1-57-28-am.png)

Tested them on v2.9-0b1d2a9bd0b9782d9adcd2e9f15c7811996d18d8-head

**Comment by aalves08** [comment]
@IsaSih https://github.com/rancher/dashboard/pull/10782 should fix https://github.com/rancher/dashboard/issues/10441#issuecomment-2047009103

**Comment by IsaSih** [comment]
tests pass on v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head
