### ISSUE TITLE
Header Bar - Design Issues

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1044]
The different components in the header look all mismatched.

- [x] Can we make them the same height?
- [x] Can we adjust the font size to be the same in the different components? 

<img width="574" alt="Screen Shot 2020-08-17 at 10 35 57 PM" src="https://user-images.githubusercontent.com/11410997/90474398-0afbfc00-e0da-11ea-990a-3644fdf0d784.png">

<img width="1198" alt="Screen Shot 2020-08-17 at 10 34 33 PM" src="https://user-images.githubusercontent.com/11410997/90474341-e9027980-e0d9-11ea-920d-884da5efaa6b.png">

<img width="746" alt="Screen Shot 2020-08-17 at 10 36 37 PM" src="https://user-images.githubusercontent.com/11410997/90474440-223ae980-e0da-11ea-9a70-0b49fa15e05b.png">

- [x] Adjust the heights of the items in the list? The preferences has more space above than below.

<img width="168" alt="Screen Shot 2020-08-17 at 10 37 15 PM" src="https://user-images.githubusercontent.com/11410997/90474490-3d0d5e00-e0da-11ea-93ef-0d4dcc64ce4e.png">

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1113
