### ISSUE TITLE
Reduce the times we go out and fetch all charts

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10448]
- Calling `await this.$store.dispatch('catalog/load', { force: true, reset: true })` can be very expensive
  - Some repos have a lot of charts (like bitnami)
  - Fetching these can take a looong time and block various chart pages
- This was done via https://github.com/rancher/dashboard/issues/7668 / https://github.com/rancher/dashboard/pull/7672
  - We can't subscribe for changes to the charts so any changes have to be explicitly fetched by the UI
  - The solution in the linked pr was to a force refresh at different points
    - shell/detail/catalog.cattle.io.app.vue
    - shell/mixins/chart.js
    - shell/pages/c/_cluster/apps/charts/index.vue
    - shell/utils/install-redirect.js
- Since then https://github.com/rancher/dashboard/pull/9612 was done... which would fix the issue for the admin / user who kicked off the refresh. This would not fix it for users who did not kick off the refresh. They would need to refresh the page instead.
- Given the impact of fetching charts, i would vote we revert rancher/dashboard#7672 and retest rancher/dashboard#7668

**Comment by nwmac** [comment]
See also: https://github.com/rancher/dashboard/commit/90ca1209f42a0674809fa5fa8634ea8a24527df0

**Comment by izaac** [comment]
Moving to done, the updated E2E test seems to cover the expectation of this issue.
