### ISSUE TITLE
Creating a Repository with Authentication from Cluster Management gives an error

### ISSUE THREAD

**Issue by kourosh7** [rancher/dashboard#10456]
Internal Reference: SURE-7628

**Setup**
- Rancher version: tested in 2.7.9 and 2.8.2
- Rancher UI Extensions:
- Browser type & version: Chrome Version 121.0.6167.139 (Official Build) (64-bit)

**Describe the bug**
Creating a Repository with Authentication from Cluster Management gives an error:
`Cannot read properties of undefined (reading 'linkFor')`

**To Reproduce**

1. From the Rancher UI go to Cluster Management
2. Select Advanced > Repositories
3. Click the Create button
4. Enter a Name, Git Repo URL, Git Branch
5. For Authentication select `Create a HTTP Basic Auth Secret` and supply a username/password
6. Click Create

**Result**
Error that says: `Cannot read properties of undefined (reading 'linkFor')`

**Expected Result**
No error and the repository is created

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/39573922/5171ad7b-4e9c-4c71-81e4-659e23321bc5)

**Additional context**

**Comment by richard-cox** [comment]
Reproduced.

```
impl.js:174 CreateEditView mixin failed to save:  TypeError: Cannot read properties of undefined (reading 'linkFor')
    at n.<anonymous> (resource-class.js:1157:26)
```
For type `secret` 
```
        const schema = this.$getters['schemaFor'](this.type);
        let url = schema.linkFor('collection');
```

There are no existing secrets in the drop down either.

I tried to reproduce this in the `local` clusters `Apps` / `Repositories` list and couldn't. They're the same set of resources, so that's a workaround.

Suspect this is caused by the same pages being in the mgmt store and not cluster

Interestingly similar to https://github.com/rancher/dashboard/issues/1370

**Comment by nwmac** [comment]
Probably store related? Are we assuming cluster store, when in the case of being used from cluster management, it should be the management store?

**Comment by IsaSih** [comment]
Tests pass on 2.8-head but the error still occurs in 2.7-head, so I'll create a backport issue to address this in 2.7

**Comment by yonasberhe23** [comment]
e2e test coverage LGTM however it might be worth testing this with legit SSH keys. moving to 'To Test' @izaac

**Comment by richard-cox** [comment]
Workaround (if visible to user) is to manage helm repositories in the `Local` cluster (it's the same set of resources)
