### ISSUE TITLE
Cluster Tools page fails to load with MCM disabled

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10458]
**Setup**
- Rancher version: 2.9

**Describe the bug**
- With MCM disabled the cluster tools page does not load

**To Reproduce**
- Bring up rancher with the feature flag `multi-cluster-management` disabled, for instance in docker `--features=multi-cluster-management=false`
- Navigate to the `Cluster Tools` page

**Result**
- Forever `Loading...` indicator
- In console
```
fetch.client.js:79 Error in fetch(): Error: Unknown schema for type: management.cattle.io.project
    at getters.js:23:13
``` 

**Expected Result**
List of cluster tool cards shown

**Additional context**
- with MCM disabled projects aren't available (project/namespace list is just namespaces, namespace filter only shows namespaces)

**Comment by richard-cox** [comment]
Something isn't quite right, there should be no clusters showing in the side bar (as with MCM off the cluster management section is hidden). Did you bring up a new system with the flag provided?

**Comment by torchiaf** [comment]
Enable feature flags with Helm installations:

```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=rancher.instance.foo \
  --set replicas=1 \
  --set 'extraEnv[0].name=CATTLE_FEATURES' \
  --set 'extraEnv[0].value=multi-cluster-management=false'
 ```
