### ISSUE TITLE
AKS: Nodepool name field needs validation for unsupported format

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10462]
**Setup**
Rancher version: `v2.9-a9534addc5745ec2c93cde7f5e3c54bc9b3a1f91-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS Nodepool name field needs validation for unsupported format. This validation was present on old UI, but missing on new UI.

**To Reproduce**
- Create downstream AKS cluster
- Provide nodepool name in unsupported format eg. agentPool

**Screenshots**
2.8:
![image](https://github.com/rancher/dashboard/assets/73099870/f541d162-d2a5-452c-ba4b-e3ed3d74ca5c)

2.9 allows cluster creation which eventually fails:
![image](https://github.com/rancher/dashboard/assets/73099870/ca02eb44-4aaa-4232-b18a-ad7e97eb38e2)

**Comment by valaparthvi** [comment]
Validated on Rancher(v2.9-a9355940c0629ca419b7dd3e4098c4ea0e52c0c0-head); Dashboard(master https://github.com/rancher/dashboard/commit/46a44c11ddbb14581db9793aadc3512e1362edf1), it is **partially** fixed.

- There is validation for unsupported characters.
![Screenshot from 2024-07-10 15-15-34](https://github.com/rancher/dashboard/assets/11015077/5843b666-cd1b-4dec-8b05-3d86343ce5ec)


- There is no inline validation for unsupported length, even though the creation fails later on with error:
```
 Error failed to create cluster: PUT https://management.azure.com/subscriptions/80de5134-ca65-4731-be21-13fb1f0910a2/resourceGroups/pvala-aks-rg/providers/Microsoft.ContainerService/managedClusters/pvala-aks-invalid-np-name -------------------------------------------------------------------------------- RESPONSE 400: 400 Bad Request ERROR CODE: InvalidParameter -------------------------------------------------------------------------------- { "code": "InvalidParameter", "details": null, "message": "The value of parameter agentPoolProfile.name is invalid. Please see https://aka.ms/aks-naming-rules for more details.", "subcode": "", "target": "agentPoolProfile.name" } -------------------------------------------------------------------------------- 
```
![image](https://github.com/rancher/dashboard/assets/11015077/83376054-ccc6-498b-bd92-784c5ff7f369)

**Comment by mantis-toboggan-md** [comment]
@valaparthvi I'd like to track adding node pool name length validation with https://github.com/rancher/dashboard/issues/11405 and keep this ticket for the invalid character issue if that works for you
