### ISSUE TITLE
vSphere - Adding a second or subsequent pool in Edit mode does not populate default values and shows Error banner wrongfully

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#10476]
**Setup**
- Rancher version: 2.9-head, 2.7-head(no error banner though, since it was implemented in 2.8)
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

Adding a second or subsequent pool in Edit mode does not populate default values for either specific vSphere fields(e.g. Datacenter, DataStore, etc) or other generic configuration fields(e.g. CPU , Disk ,etc). This also leads to display error banners wrongfully for the new pool.

**To Reproduce**
Create a vSphere cluster, save it and then go to Edit Config and add a new pool

**Result**
Does not populate default values and displays error banner for the new pool

**Expected Result**
Should populate default values and should not display error banner for the new pool

**Screenshots**

https://github.com/rancher/dashboard/assets/135728925/d9b98522-9fd6-4d5b-bec8-e10476ccaff2

**Comment by aalves08** [comment]
Added `automation-candidate` based on the fact that we have a pattern to mock a cluster, like https://github.com/rancher/dashboard/blob/master/cypress/e2e/blueprints/nav/fake-cluster.ts... will take a bit of time to get all of Vsphere responses mocked, but seems doable imho

**Comment by IsaSih** [comment]
Tests pass on v2.9-81337b95660cba868629d6fe769bd7e8242b5aee-head
<img width="1698" alt="Screenshot 2024-07-22 at 2 24 25 PM" src="https://github.com/user-attachments/assets/7e4097c2-d99d-4e89-8965-3f193c0dd89c">
