### ISSUE TITLE
Incremental Loading stops Deployment Pods from showing

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10479]
SURE-7515

**Setup**
- Rancher version: 2.7.9

**Describe the bug**
- Incremental loading is on by default now and kicks in when the resources are over the threshold
- When a list uses incremental loading 

**To Reproduce**
- Have a system up with lots of pods, at least 100 
- Navigate from Cluster Dashboard --> Deployments (don't click on workloads menu item, just workloads drop down)
  - At this point confirm multiple requests to fetch both deployments and pods have been made
- Navigate to a Deployment with a pod that was not fetched in the initial request for 100 pods
  - There's a hacky way to avoid this below
 
**Result**
- No pods show in a the deployment pods list
  - Refreshing page should show the pods
 
**Expected Result**
- Pods should be shown without refreshing

**Additional context**
Caused by loadDataPage not adding to pod cache

To reproduce in a system with pods count
1. set incremental loading threshold low, say 10
1.  in `shell/plugins/dashboard-store/actions.js` change `opt.url = addParam(opt.url, 'limit', '100');` to something low, say `opt.url = addParam(opt.url, 'limit', '10');`
This ensures that incremental loading will kick in.... and it's unlikely that the first fetch of resources (that uses loadAll and thus makes to pod cache) doesn't contain the deployments pod

**Comment by aalves08** [comment]
added possible `automation-candidate` based on the fact that we can lower the threshold on the UI and probably "fake" the GET's for the given resources and do a check on the list view

**Comment by aalves08** [comment]
Validated that issue has been fixed on Rancher `v2.9-a57f7025abdd80a2912f7fe53247ef7e1d4993de-head`.

Going to the deployments list page, it fetched all of the deployments + pods (fetched incrementally)
<img width="2210" alt="Screenshot 2024-07-10 at 14 54 59" src="https://github.com/rancher/dashboard/assets/97888974/d766b621-017a-4a87-992e-811b68a96ab2">


Going to a deployment details page belonging on the 2nd page of the list, all pods were shown
<img width="2210" alt="Screenshot 2024-07-10 at 14 55 12" src="https://github.com/rancher/dashboard/assets/97888974/639b3914-e472-462a-900b-6f6eaae0e28e">


Moving to done @izaac @IsaSih @yonasberhe23
