### ISSUE TITLE
GKE - Deprecate Windows SAC image types from supported list for Node pools

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10484]
**Rancher Server Setup**
Rancher version: v2.9-84884ba4ab3da2e7c8561abfe4e2428933688836-head
Kubernetes Cluster and version: Downstream GKE with Kubernetes 1.25

**Describe the bug**
Found while validating https://github.com/rancher/dashboard/issues/10088
Unable to create Node pool with Windows SAC Image Type on GKE v1.25, so we can remove it from image list as supported option
Ref: https://cloud.google.com/kubernetes-engine/docs/deprecations/windows-server-sac

**To Reproduce**
Provision downstream GKE cluster with lowest k8s verison (1.25) Node pools image: COS with docker or Ubuntu docker

**Result**
Unable to create Node pool with Image type Windows SAC

**Expected Result**
Since Image type with Windows SAC is unsupported from lowest version v1.25 which we use, it can be removed from supported list on UI so user does not have option to select it.

See also: https://github.com/rancher/gke-operator/issues/121

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/41b14e24-bcf2-4e0c-b93d-ddd351b07019)

**Comment by mantis-toboggan-md** [comment]
This is fixed in 2.9.0:
![Screenshot 2024-07-24 at 2 36 41 PM](https://github.com/user-attachments/assets/dcf3d22b-ad78-46f6-93d8-fa4fb243df64)

**Comment by gaktive** [comment]
Putting on to the 2.9.0 milestone though at this stage, if it's not a blocker, this could be tested from 2.9.next1.

**Comment by cpinjani** [comment]
Validation passed on below build, only Windows LTSC image is listed.
```
Rancher - v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head
Dashboard - release-2.9 e108b95
```

![image](https://github.com/user-attachments/assets/076ee194-58f1-402d-ab6c-6097ae977453)
