### ISSUE TITLE
Remove v1 tools/pages under the legacy navigation item

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10489]
With the legacy feature flag enabled, when exploring a cluster, we show a legacy nav item - fully expanded, this shows:

<img width="263" alt="image" src="https://github.com/rancher/dashboard/assets/1955897/f78c17f0-39a1-4164-80e4-fc183aca92e8">

As of 2.9, all of those options APART from:

- Project/Config Maps
- Project/Secrets

should be removed.

i.e. remove: Alerts, Catalogs, Notifiers, Project/Apps, Project/Alerts, Project/Catalog and Project/Monitoring

**Comment by yonasberhe23** [comment]
e2e test coverage LGTM. @izaac

**Comment by izaac** [comment]
Clear and straightforward e2e test
