### ISSUE TITLE
Chart dependency

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1049]
Support charts dependency.

**Comment by cbron** [comment]
Update from meeting: 
* requires-gvr and provides-gvr are now only to specify dependencies that aren't auto-installed
* `auto-install-gvr` changes to just `auto-install`, no longer specifies a gvr, but instead specifies a chart and version. This should only be used for CRD charts.

**Comment by deniseschannon** [comment]
@brendarearden Can you test that chart dependency is working with Istio deployments?

**Comment by brendarearden** [comment]
Validated both gvr and auto-install are working as exprected for istio deployments . 

`catalog.cattle.io/requires-gvr: monitoring.coreos.com.prometheus/v1` kept me from getting to the install page for istio until after I installed it. 
`catalog.cattle.io/auto-install: rancher-kiali-server-crd=1.22.001` installed the rancher-kiali-server crd automatically upon installing Istio.

**Comment by deniseschannon** [comment]
Closing as the overall flow is working but individual features will be tested as part of their feature workflow.
