### ISSUE TITLE
Remove v1 monitoring embedded pages

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10490]
We embed v1 monitoring in a few places when v1 monitoring is installed:

- Cluster explorer dashboard page - see: https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/explorer/index.vue#L570
- Node detail page - see: https://github.com/rancher/dashboard/blob/master/shell/detail/node.vue#L330
- Pod detail page - see: https://github.com/rancher/dashboard/blob/master/shell/detail/pod.vue#L262
- Workload detail page: see: https://github.com/rancher/dashboard/blob/master/shell/detail/workload/index.vue#L456

v1 monitoring has been removed, so we should remove this code to clean up the codebase.

Note: It looks like we've removed all v1 monitoring charts, so I can't find a way to install it any longer - so for this ticket, we will remove the code and verify through code review that the appropriate code has been removed - since it does not look like we can test v1 monitoring any longer. 

Note: As part of doing this, search the code for `haveV1Monitoring` and remove/claan-up areas associated with this.

Also check doc links if still valid: perviously reported that some non-working doc links found in 2 files (shell/chart/monitoring/steps/uninstall-v1.vue & shell/pages/c/_cluster/explorer/tools/index.vue).

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
