### ISSUE TITLE
Display the actual group name instead of the GUID for Azure AD groups

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10509]
Internal Reference: SURE-4887

For Azure AD, Rancher shows the group GUID rather than the group name.

**Comment by momesgin** [comment]
@nwmac I was trying to reproduce this issue, but I'm not sure if this is already fixed or not. Here's a screenshot in 2.9-head:

![image](https://github.com/rancher/dashboard/assets/135728925/d9f7ab2b-66de-45ff-9618-fa7a001c94d3)

**Comment by nwmac** [comment]
Fixed in 2.8.0
