### ISSUE TITLE
Add k8s 1.28 to version dropdown

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10504]
In support of the kubernetes 1.28 bump, we need to add the 1.28 version for 2.9.0 and the appropriate 2.8.x version as an option.

This supports the updated chart for EKS: https://github.com/rancher/rancher/issues/43746 though I don't know if we have to update other cloud providers as part of it.

https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/amazon.js#L704C1-L704C26 has the current state showing up to 1.27; that's in Ember.

**Comment by gaktive** [comment]
PR to leverage: https://github.com/rancher/ui/pull/5121

**Comment by gaktive** [comment]
Note that https://github.com/rancher/ui/pull/5121 was merged into `ui/2.8-release`, unless there's an unlinked PR that does this for 2.9.0 already. @nwmac did I miss something with a backport since this looks more like a forwardport situation now?

**Comment by nwmac** [comment]
@gaktive Yes, this is already in 2.9.0.

https://github.com/rancher/ui/pull/5094

I think we can close this

**Comment by nwmac** [comment]
@gaktive Closing as done - re-open if you disagree
