### ISSUE TITLE
Cloud Provider options are not displayed in the UI

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#10516]
**Setup**
- Rancher version: v2.8-1a406a50ed18e054a714bfa3f2087766c180b626-head and v2.9-4119767ddf14ab591e8e8e38164bc917ed5e7e18-head
- Rancher UI Extensions: -X-

**Describe the bug**
For existing rke1 clusters with Amazon In-tree cloud provider, when the user wants to upgrade the kubernetes version, the list of cloud provider architecture is not displayed in the UI when the user switches back and forth kubernetes versions.

**To Reproduce**
1. Create a rke1 cluster with a Kubernetes version older than 1.27 to select Amazon In-tree cloud provider
2. After the cluster is created, from the list of clusters in cluster management, select from the 3-dot menu, Edit Config
3. Scroll down to cluster options, and observe that the current kubernetes version is selected, but no cloud provider architectures are displayed
4. Then, select a kubernetes version higher than 1.27 and observe that the cloud provider architectures are displayed
5. But then, select another kubernetes version higher than 1.27 

**Result**

**Expected Result**
No matter the selected Kubernetes version, the list of options for cloud provider must always be displayed and available for user selection

**Screenshots**

https://github.com/rancher/dashboard/assets/70187881/c33f8777-76c9-40dc-9115-a8c856bd757d

**Comment by gaktive** [comment]
@IsaSih to coordinate with a few folks, @mantis-toboggan-md, @kwwii & @rak-phillip about how a solution could look like.

**Comment by rak-phillip** [comment]
The docs make it sound like it's recommended to migrate to out-of-tree prior to upgrading to v1.27+[^1]

> You can migrate from an in-tree to an out-of-tree AWS cloud provider on Kubernetes 1.26 and earlier. All existing clusters must migrate prior to upgrading to v1.27 in order to stay functional.

[^1]:https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/migrate-to-an-out-of-tree-cloud-provider/migrate-to-out-of-tree-amazon

**Comment by mantis-toboggan-md** [comment]
Interesting find @rak-phillip; it looks like the docs are telling users to do something the UI intentionally blocks in both [rke1](https://github.com/rancher/rancher/issues/22852) and [rke2]( https://github.com/rancher/dashboard/issues/5294) provisioning. Our internal ux docs call out making the cloud provider editable only when the previous option is no longer supported:

> For cluster edit, when the k8s version is changed, detect when the cloud provider selected is no longer available - in this situation we will:
> - Make the cloud provider editable
> - Change the cloud provider to 'External' and mark the entry that is no longer valid as disabled, so that it can't be selected (but is visible to the user for reference)
> - Show a warning banner above the external 'Cloud Provider' configuration section, with the copy: "The existing cloud provider is not supported by the selected Kubernetes version. The cloud provider has been changed to 'External'. Please refer to the out-of-tree cloud provider configuration documentation and provide the appropriate out-of-tree configuration."

From the video posted in this issue there does appear to be a bug with this in RKE1 provisioning but we may need input from someone with more technical expertise to understand exactly when the cloud provider should be editable.

**Comment by kwwii** [comment]
There is an issue with how we show the cloud provider options when changing the kubernetes versions. We currently only show the options for 1.27 but we should show them for all versions equal to or greater than 1.27

**Comment by IsaSih** [comment]
Tests pass
