### ISSUE TITLE
Improve logout message for SSO

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10519]
Internal Reference: SURE-5064

Suggest we improve the logout message in the case of SSO, e.g.

"You've been logged out of Rancher, however you may still be logged in to your single sign-on identity provider"

Current logout view:

![image](https://github.com/rancher/dashboard/assets/1955897/878674f6-4c69-45a6-8288-250f386503be)

**Comment by yonasberhe23** [comment]
e2e coverage is good but it is a good idea to do manual validation with various auth providers. moving to 'To test' @izaac

**Comment by izaac** [comment]
An additional ldap provider would be enough in my opinion. It can be a manual until an implementation using our internal CI is designed.

**Comment by bmdepesa** [comment]
Let's look at the underlying PR and determine if we actually need to test with multiple auth providers
