### ISSUE TITLE
Repository Detail - Design Issues

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1051]
Under Apps & Marketplaces -> Repositories

Make this page prettier:
- [ ] Update the heading "Git Repository containing Helm charts", so that it's a bit bigger
- [ ] Add space between detail top and the first row of items

<img width="796" alt="Screen Shot 2020-08-18 at 1 55 34 PM" src="https://user-images.githubusercontent.com/11410997/90564630-8b624180-e15a-11ea-8ac2-d08cce9c4d0d.png">

**Comment by lvuch** [comment]
I can't reproduce this, there seems to be a bigger issue
