### ISSUE TITLE
add pod selector button disappears when selected

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#1052]
On pod scheduling section of create deployment the pod selector component isn't working:
<img width="440" alt="Screen Shot 2020-08-18 at 3 13 27 PM" src="https://user-images.githubusercontent.com/3013118/90570876-7c34c100-e165-11ea-843f-13f23234e66b.png">

<img width="457" alt="Screen Shot 2020-08-18 at 3 13 32 PM" src="https://user-images.githubusercontent.com/3013118/90570873-7b039400-e165-11ea-8135-f725d8f093f2.png">

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `33f755f18`**

- Add pod selector button is available when selected
<img width="1657" alt="Screen Shot 2020-09-17 at 2 17 55 PM" src="https://user-images.githubusercontent.com/26032343/93529357-a1e1f100-f8f0-11ea-890b-965559d449ae.png">
