### ISSUE TITLE
Clicking on Profile button does not show the dropdown options

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1053]
**Verified on master-head commit id: `d19f179c4`**

- Clicking on Profile button does not show the dropdown options
- User has to hover over the profile icon for the dropdowns to be visible.
<img width="333" alt="Screen Shot 2020-08-18 at 5 56 45 PM" src="https://user-images.githubusercontent.com/26032343/90579906-42bb8000-e17c-11ea-840b-c85c6188f378.png">

**Expected:**
Dropdown options must be seen when user clicks on the profile icon

**Comment by deniseschannon** [comment]
Make the icon box more prominent (look at ember)

Style the dropdown so it's clearer the username versus what I can select

Stay open on clicking the icon.

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1571 fixes style, dev will need to look at behavior

**Comment by sowmyav27** [comment]
**On master commit id: `5a60e25b`,** 
the profile dropdown is now --
<img width="371" alt="Screen Shot 2020-10-02 at 9 39 24 AM" src="https://user-images.githubusercontent.com/26032343/94947955-59e7d000-0493-11eb-8e46-429f2d8d3778.png">

- Hover mouse over the profile (top right corner in dashboard page), dropdown is seen
- Click on it, the profile dropdown will not be seen anymore.
- user will have to move mouse out of the profile section and hover the mouse on the profile again
- This is not the same behavior as Ember UI

Reopening the issue.

**Comment by lvuch** [comment]
These last issues need a dev to fix. @westlywright can you take a look?

**Comment by nwmac** [comment]
This has been fixed now

**Comment by sowmyav27** [comment]
**On master-head commit id: `9e0d1b2`**

- Clicking on Profile shows the dropdown
- Hovering on it , however does not.
