### ISSUE TITLE
Replace Fleet Cluster `Nodes Ready` column 

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10542]
- `fleet.cattle.io.cluster`  `status.agent.readyNodes` and `status.display.sampleNode` are soon to be removed
  - These did not show fleet specific info, and info can be obtained elsewhere
  - https://github.com/rancher/fleet/pull/2190
- These are used in the fleet cluster model's `nodeInfo` property, which is used to display `Nodes Ready` column in the fleet cluster list
- We should replace the column with something else which might be useful. Candidates (one or all)
  - `readyBundles` in https://fleet.rancher.io/ref-crds#clusterdisplay 
  - `lastSeen` in https://fleet.rancher.io/ref-crds#agentstatus

**Comment by kkaempf** [comment]
@nwmac @gaktive Fleet would need this for v2.9.0 already 🥺

**Comment by thehejik** [comment]
@gaktive Just letting know that QA is done, please see report https://github.com/rancher/fleet/issues/1973#issuecomment-2064127352 with details.

**Comment by thehejik** [comment]
This seems to be fixed. This is how it looks currently in `2.9-e833f80f53b04b301f881f96154392c34d3b56b1-head` with fleet `104.0.0+up0.10.0-rc.14`:

**Comment by nwmac** [comment]
Thanks @manno - if you could create a new issue, that would be great.

**Comment by nwmac** [comment]
@yonasberhe23 I think this can be marked done now
