### ISSUE TITLE
Steve socket is spammed on fresh visit to a resource detail page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10540]
We should tackle this after fix for https://github.com/rancher/rancher/issues/41809 has merged

**Setup**
- Rancher version: 2.7.x

**Describe the bug**

After visiting by url / refreshing on an oldish steve based resource's detail page the steve socket gets spammed with messages.

This probably applies to the resource's edit page as well.

- Very roughly we fetch resources. That response contains a `revision`. We watch for changes for that set of resource over web socket using the revision as a starting point
- If that `revision` is too old we should get a resource.error `too old` message
- The UI then knows to make a fresh request for resources which will have the latest changes and the current reviewed
- There were scenarios where the `too old` message was not provided and will be / has been fixed via https://github.com/rancher/rancher/issues/41809
  - Socket spamming was due to a resource.stop --> resource.start --> resource.stop --> resource.start forever cycle
  - Fix means the cycle does not occurr resource.stop & resource.error 'too old' --> http request --> resource.start 
- This revealed another issue related to spamming sockets to do with `too old` handling
- With the fix above fetched / watching resources is fine, however fetching / watching a single resource is not
  - Fetch single resource & use revision from within to watch (note - not the current system revision) --> resource.start with old revision --> resource stop & resource.error `too old` --> http request for single resource & use revision from within forever cycle
  - There's also a bug where the namespace for the single resource http request isn't passed through to the url construction, so the request is borked anyway

**To Reproduce**
- Bring up a system with the fix from https://github.com/rancher/rancher/issues/41809
- Navigate to a configmap page that's pretty old
- Bring up dev tools --> network tab
- Refresh the page
- View the socket messages for the ds cluster's socket connection

**Result**
- LOTS of `too old` messages as the ui tries to watch with the old revision AND http requests with a bad url (no ns)
- ![image](https://github.com/rancher/dashboard/assets/18697775/4e740711-adf2-49eb-9261-bdbb5f6dd72d)

**Expected Result**
- After the first resource.error message is received the UI should make a new http request to fetch the resource and then send a watch message with no revision.
- There should not be any repeat cycles of this (for example no spammed green lines )
- ![image](https://github.com/rancher/dashboard/assets/18697775/69ce70b6-9710-475c-aa50-ed80b15eabd9)

**Comment by IsaSih** [comment]
Tests pass in v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head

![Image](https://github.com/rancher/dashboard/assets/70187881/1256d799-a669-4602-b729-4c98f4f3e0a9)
