### ISSUE TITLE
Can't click on 'Workloads' group header to go to Workloads

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10558]
This is a bug specific to group headers in the side nav.

Go to the local cluster and click on Workloads.

Click on CronJobs.

Now try and click on Workloads - not by clicking on the text, but in the area around it (see red line below) - although the cursor shows a hand icon and although this works on the first click into Workloads, this does not work when the group is expanded - you have to click on the text.

![Screenshot 2024-03-05 at 12 00 15](https://github.com/rancher/dashboard/assets/1955897/5eec0975-cc32-4693-a928-32c554c06095)

You should be able to click anywhere in the sider nav group header to go back to it.

**Comment by nwmac** [comment]
Should be possible to write an automated e2e test for this - click into workloads, click to cronjob, click back to workloads and ensure we are on the correct workloads page - ensure that the last click, clicks the outer-most element and not tehe text element, as this works.

**Comment by aalves08** [comment]
Can be automated by e2e by targeting a outer container of the menu item `Workloads` to assert that in fact works by clicking on the "whole" row... Might need to add an exception to the PO that controls the nav click part just specific to this `Workloads` entry. By passing the gates it means that overall it works as per this fix

**Comment by yonasberhe23** [comment]
This e2e test is failing in Jenkins and also locally with this error: 

AssertionError: Timed out retrying after 60000ms: 
expected 'https://jenkins-k3iz1ru1.qa.rancher.space/dashboard/c/local/explorer/workload' 
to equal 
'https://jenkins-k3iz1ru1.qa.rancher.space/dashboard/c/local/explorer#cluster-events'
      + expected - actual

      -'https://jenkins-k3iz1ru1.qa.rancher.space/dashboard/c/local/explorer/workload'
      +'https://jenkins-k3iz1ru1.qa.rancher.space/dashboard/c/local/explorer#cluster-events'

It seems there needs to be some delay after clicking 'Workloads'. This should do the trick.


_____
import WorkloadPagePo from '@/cypress/e2e/po/pages/explorer/workloads.po.ts';
    
const workloads = new WorkloadPagePo();
workloads.waitForPage();
____

**Comment by yonasberhe23** [comment]
e2e test coverage LGTM. moving to 'Done' @izaac

**Comment by izaac** [comment]
A good call out, coverage looks good.
