### ISSUE TITLE
The highlighted cluster in the App Bar retains its highlighting even when clicking on an item from the bottom category of the App Bar

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#10576]
**Setup**
- Rancher version: 2.9-head

**To Reproduce**

1. Select any cluster from the App bar
2. Click on any icons from the bottom category on the App bar, e.g. Global Settings icon

**Result**
- Only one item should be highlighted

**Expected Result**
- Two items are highlighted at the same time

**Screenshots**

<img width="338" alt="image" src="https://github.com/rancher/dashboard/assets/135728925/c12f5886-fa06-41b0-9341-b27c44626b91">

**Comment by yonasberhe23** [comment]
e2e test are sufficient. moving to done cc: @izaac
