### ISSUE TITLE
Editing configmap in rancher adds newline characters breaking kustomize

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10589]
Internal reference: SURE-7824

Issue description:
When you edit a ConfigMap in the Rancher UI via "Edit Config", the last-applied-configuration is corrupted by adding `\n` newline characters.

This does not happen if you use the 3 dot menu and click "Edit Yaml" but it does happen if you go to Edit Config, and then click Edit as YAML

The belief is that this is happening because Edit Config is using `>` as the operator in the last-applied-configuration section, while also wrapping long lines. If you use `Edit Yaml` it uses the `|` operator. This was tested going to Edit Config, clicking Edit as YAML and then replacing the `>` operator on the last-applied-configuration with a `|` and it did not experience the issue.

Impact:
One environment's CI workflow is failing with Invalid Json when using kustomize on resources that have been modified through Rancher

Repro steps:

```
    kubectl create ns dims
    kubectl create -f test.json
    kubectl get n dims configmap dimsmanagement-config -o json
    Note there are no \n characters in the last-applied-configuration
    Edit the ConfigMap in Rancher via Edit Config, change automatic-error-replay.cron-expression from 0 30 * ? * * to 0 31 * ? * * and click save
    kubectl get -n dims configmap dimsmanagement-config -o json
    Note there are now \n characters present in the last-applied-configuration
```

Workaround:
Edit the ConfigMap via Edit Yaml instead of Edit Config

Actual behavior:
last-applied-configuration has \n characters added to it

Expected behavior:
last-applied-configuration does not have \n characters added to it

Past efforts addressed in https://github.com/rancher/dashboard/issues/10044 though this is still happening on the main branch.

**Comment by izaac** [comment]
The final validation looks good to me. @yonasberhe23 @IsaSih what's your opinon on validating this manually. I think this would depend on the test configuration if whether it's possible to keep simple it in one file/configmap.

**Comment by floatingman** [comment]
I ran through repro steps and confirmed that the newline was not added to the configmap
