### ISSUE TITLE
RFE: allow allocation of vGPU resources for Harvester

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10588]
For the vGPU function to work in Harvester, a UI change needs to be made in Rancher to allow the allocation of vGPU resources.

The docker-machine driver changes to passthrough vGPU's is all ready https://github.com/harvester/docker-machine-driver-harvester/pull/50 

Harvester will introduce this in their 1.3.0 due in March

**Comment by gaktive** [comment]
Additional context via the vGPU epic: https://github.com/harvester/harvester/issues/2764

**Comment by gaktive** [comment]
This will need a backport but need to confirm which 2.8.next version with @rebeccazzzz

**Comment by gaktive** [comment]
Some work may have done already in https://github.com/harvester/dashboard/pull/930 so I'll check with @torchiaf on what's been done so far and this may require some UX review with @kwwii

**Comment by gaktive** [comment]
@torchiaf should this have gone through QA or would that be handled in the 2.8.x backport? Or did QA already happen elsewhere? @rebeccazzzz was curious since the backport was open still.

**Comment by torchiaf** [comment]
@gaktive There is a tracking issue in Harvester repo for this; either UI QA or Harvester QA should work on it.
