### ISSUE TITLE
Allow ButtonDropdown to always open the dropdown when clicked

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#1059]
The Ember UI has a form component that looks like a button and acts more like a dropdown: ![Screen Shot 2020-08-20 at 1.49.19 PM.png](https://zube.io/files/rancher/e941eba4f0c31b3ece03165ded8264d4-screen-shot-2020-08-20-at-1-49-19-pm.png)
This is specifically needed in workload storage [rancher/dashboard#502 (rancher/dashboard#500)](https://zube.io/rancher/dashboard-ui/c/502) 

`ButtonDropdown` is a likely analogue in Dashboard, but needs some additional support to be able to function the same way (have the button action open the popover)

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f7878`**

- See this dropdown
<img width="531" alt="Screen Shot 2020-09-28 at 12 34 04 PM" src="https://user-images.githubusercontent.com/26032343/94477667-0e79ad00-0187-11eb-8095-be2d3ca7540b.png">

- Click on `Secret` --> See an error in the console. Volume is NOT added.
- Error in console:
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'defaultMode' of undefined
    at f.r (Secret.vue?0a29:1)
    at f.t._render (vue.runtime.esm.js:3548)
    at f.r (vue.runtime.esm.js:4066)
    at _n.get (vue.runtime.esm.js:4479)
    at new _n (vue.runtime.esm.js:4468)
    at t (vue.runtime.esm.js:4073)
    at f.$n.$mount (vue.runtime.esm.js:8415)
    at init (vue.runtime.esm.js:3118)
    at vue.runtime.esm.js:5978
    at v (vue.runtime.esm.js:5925)
```

**Comment by sowmyav27** [comment]
**On master-head - commit id: `eb96d76c`**

Add volume --> See this dropdown. user is able to select values from dropdown
<img width="942" alt="Screen Shot 2020-09-30 at 8 14 27 AM" src="https://user-images.githubusercontent.com/26032343/94704751-1a837d00-02f5-11eb-8212-63fc949a7f9f.png">
