### ISSUE TITLE
Legacy/Project sub-nav is broken when you select a project

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10595]
Enable the legacy feature flag.

Open the 'Legacy' side nav item:

![image](https://github.com/rancher/dashboard/assets/1955897/eb710e17-68bf-45a5-9b98-d7bb13673804)

Select a project in the filter at the top - the Nav collapses - if you expand if again, 'Project' is no longer shown :

![image](https://github.com/rancher/dashboard/assets/1955897/4ad37b84-4269-4d3b-a3a7-7934713f81a5)

It is supposed to show, along with the sub-nav for legacy projects.

This is a regression.

We should add test automation - these are embedded pages, but we should be able to check that the side navigation is correctly shown.

**Comment by gaktive** [comment]
@nwmac should we backport this for 2.8.next2?

**Comment by richard-cox** [comment]
Workaround is to move one line https://github.com/rancher/dashboard/pull/10601/files#diff-3ad9f7560480743de6a82ac01d6f961c5c8674095bf5a27c65287d4946b88fc3, or remove the `v1-project` virtualType https://github.com/rancher/dashboard/pull/10601/files#diff-df1b650a2b16b99d79608f890999ea68be49bcee5d140ad0fea2a2e1366e2707. More info in https://github.com/rancher/dashboard/pull/10601

**Comment by yonasberhe23** [comment]
e2e is sufficient. moving to done @izaac
