### ISSUE TITLE
Backup-restore-operator EncyrptionConfig field

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#1060]
The encryptionConfig field in backup spec and restore spec is the name of a secret, that contains a file responsible for encrypting a backup's resources and decrypting them during restore. The operator won't store it, so its up to the user to know the contents of this file from the secret and save it properly. This will be documented, but also the UI needs to show warning conveying that encyrptionConfig is not saved by the operator, user must have it saved separately elsewhere to use the same config for restore, else restore won't work

**Comment by deniseschannon** [comment]
@mrajashree should this be a separate ticket or part of the CRD tickets as something to do for that field?

**Comment by mrajashree** [comment]
@deniseschannon Makes sense, added this to the description of the tickets for Backup and Restore CRDs
