### ISSUE TITLE
[backport v2.7.next1] Required fields are not checked when saving (via yaml save)

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#10607]
This is a backport issue for https://github.com/harvester/harvester/issues/4350

Original issue body:

**Is your enhancement related to a problem? Please describe.**

Required fields are not checked when saving (`via yaml save`).

When we creates a new Harvester cluster, they can create a cluster without a network (from the GUI, via yaml save) which eventually breaks the whole cluster, according to their information it keeps creating and deleting nodes.

Steps to reproduce: Create new cluster, `cloud credentials` -> `Select RKE2 and Harvester node driver` -> `Type in the cluster name` -> `Switch to YAML view and click on Create`. There is nothing that prevents it.

**Describe the solution you'd like**

Save via yaml should also validate.

**Describe alternatives you've considered**

**Additional context**

**Comment by gaktive** [comment]
Testing will be done by Harvester QA
