### ISSUE TITLE
Remove node images based on docker for GKE v1.24+

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#10600]
**Setup**
- Rancher version: v2.8-4350b89f75e08530c9e9c082dca6e4328eabf453-head

**Describe the bug**
Provisioning a GKE cluster in the UI from an image based on dockerd failed in GKE version higher than 1.24 with the following error message
`Googleapi: Error 400: Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.24+ clusters as Dockershim has been removed in Kubernetes v1.24. Details: [ { "@type": "type.googleapis.com/google.rpc.RequestInfo", "requestId": "0xecc07d3f4f1219ec" } ] , badRequest`

**To Reproduce**

1. Deploy Rancher on a local cluster with GKE v1.25.6-gke.1000
2. Add your GKE cloud credentials in Clusters Management > Cloud Credentials;
3. From Clusters Management, hit Create
4. Select Google GKE
5. Pick a location and a kubernetes version higher than 1.24
6. In the Node Pool section, select "Container - Optimized OS with Docker" or "Ubuntu - Docker"

**Result**
Cluster fail to provision with the following error
`Googleapi: Error 400: Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.24+ clusters as Dockershim has been removed in Kubernetes v1.24. Details: [ { "@type": "type.googleapis.com/google.rpc.RequestInfo", "requestId": "0xecc07d3f4f1219ec" } ] , badRequest`

**Expected Result**
We should not display the options "Container - Optimized OS with Docker" and "Ubuntu - Docker" in the UI if GKE version is greater than or equal to 1.24

**Screenshots**
<img width="1721" alt="Screenshot 2024-03-11 at 6 53 32 PM" src="https://github.com/rancher/dashboard/assets/70187881/6840c7d1-cbfd-48f2-bacb-300957782a6f">
<img width="1721" alt="Screenshot 2024-03-11 at 6 52 13 PM" src="https://github.com/rancher/dashboard/assets/70187881/08858414-bfa6-4a99-8922-8b5884e6a0a8">

**Additional context**

**Comment by nwmac** [comment]
This is already fixed in 2.9.0

**Comment by nwmac** [comment]
Fixed as part of https://github.com/rancher/dashboard/issues/10088
