### ISSUE TITLE
[RFE] Add `DeviceAuthEndpoint` for AzureAD custom endpoint for kubectl

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10616]
Internal reference: SURE-4275

To enable AzureAD support, Collie has been working on enabling a new endpoint on the CLI to expose an  extra input field in the AzureAD configuration section for the custom endpoints.

A user can provide custom endpoints, which ties to a custom `DeviceAuthEndpoint`.

Related backend tickets: 
- https://github.com/rancher/rancher/issues/44778
- https://github.com/rancher/rancher/issues/42939

**Comment by gaktive** [comment]
Backport to 2.8.x needed though I'll have to confirm release target.

**Comment by gaktive** [comment]
Work should be done in the Custom part of the AzureAD Auth Provider but let's review the RFC just to make sure nothing is missed.

**Comment by gaktive** [comment]
Putting QA/None here since the backport will likely be tested first.

**Comment by samjustus** [comment]
no longer needed
