### ISSUE TITLE
Remove references to v1 Alerting and Monitoring in the Ember UI

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#10617]
Similar to https://github.com/rancher/dashboard/issues/10489 
we need to remove references to v1 alerting and monitoring from the Ember UI'. 

"Alerts" "Notifiers" and "Monitoring" should all be removed from the cluster-level navigation:
 ![Screenshot 2024-03-13 at 3.06.31 PM.png](https://zube.io/files/rancher/5226d651ddc4b470faa0676d827b0b3c-screenshot-2024-03-13-at-3-06-31-pm.png)

**Comment by gaktive** [comment]
@nwmac we had this listed in the 2.8.x backports but the original work wasn't done yet in 2.9.0. Should we tackle this firstly here (preferable but we're hitting a time situation here) or try a forward port?

**Comment by IsaSih** [comment]
Tests pass on v2.9-3a426b5ba059358f8874573c0a98d01bfda25a47-head

**Comment by IsaSih** [comment]
Quick question: I was retesting this for 2.9 release, and I realized that I see the error "Monitoring in Cluster Manager has been deprecated as of Rancher v2.5.0 - check out the [FAQ](https://rancher.com/docs/rancher/v2.6/en/faq/deprecated-features-25x). The updated version of [monitoring] in Cluster Tools is currently deployed. You do not have permission to configure cluster level monitoring. in ember UI" with the latest version of monitoring installed (
rancher-monitoring
104.0.0-rc1+up45.31.1). The following error is observed in the console: 


https://github.com/rancher/dashboard/assets/70187881/8316a72a-c519-4dec-af83-bc35f92330e5

**Comment by codyrancher** [comment]
@IsaSih are you asking if we want to remove the Enable Monitoring link? If so, I think we probably want to remove that as well. 

Someone else would need to make the call if it's a blocker or not.
