### ISSUE TITLE
Backup-restore-operator Overview Page

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#1061]
### Description
The backup-restore-operator allows backing up Kubernetes applications running on any cluster, and restoring them from a backed up version. For 2.5, it is primarily used to back up the Rancher application running on the rancher management (local) cluster for HA setups. It accepts a list of resources that need to be backed up for a particular application. It then gathers these resources by querying the Kubernetes API server, packages all the resources to create a tarball file and pushes it to the configured backup storage location. Since it gathers resources by quering the API server, it can back up applications from any type of Kubernetes cluster.
This Chart comes with a template specifying all resources that need to be gathered for backing up the Rancher application. This is explained further in the CRDs section.
The operator preserves the ownerReferences on all resources, hence maintaining dependencies between objects. 
This operator provides encryption support, to encrypt user specified resources before saving them in the backup file. It uses the same encryption configuration that is used to enable [Kubernetes Encryption at Rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/). Follow the steps in [documentation link TBD] to configure this 

### CRD Explanations and User flow 
(The What/how blah blah blah? from [this](https://xd.adobe.com/view/62ea899e-acc6-4b72-a654-9ecf811430a8-37b9/) template)

It installs the following 3 namespaced CRDs:
1. [ResourceSet](https://github.com/rancher/dashboard/issues/1123)
2. [Backup](https://github.com/rancher/dashboard/issues/1124)
3. [Restore](https://github.com/rancher/dashboard/issues/1125)
The GH tickets and [this doc](https://rancher.atlassian.net/wiki/spaces/EN/pages/494501903/Backup+restore+CRD+user+flow) together explain individual CRD fields.

User flow
1. Before taking a backup, user must create a ResourceSet, that targets all the resources user wants to backup. The ResourceSet required for backing up Rancher will be provided and installed by the chart. It will by default be installed in the chart's release namespace. User can instead choose to set some other namespace while installing the chart. (This will be explained further in the deployment page). Apart from that, users can get the template from Rancher documentation and create the ResourceSet in any other namespace they want even after the chart is installed. (link to be added later)
2. Performing a backup: To take a backup, user has to create an instance of the Backup CRD (create a Backup CR). Each Backup CR must reference a ResourceSet. A Backup CR must be in the same namespace as the ResourceSet it references. A Backup CR can be used to perform a one-time backup or recurring backups.
3. Restoring from a backup: To restore from a backup, user has to create an instance of the Restore CRD (create a Restore CR). A Restore CR must contain the exact Backup filename. 

### CRD summary
The only correlation between CRDs is between the ResourceSet and Backup CRD. A Backup CR must reference a ResourceSet. And a ResourceSet can be used for taking any number of Backups. 
| Resource Set | Backups | 
| -- | -- |
| rancher-resource-set (name of the resourceSet CR) | names of all Backups that reference this resourceSet |

### Mockup based on [this](https://xd.adobe.com/view/62ea899e-acc6-4b72-a654-9ecf811430a8-37b9/) template

<img width="722" alt="Screen Shot 2020-09-02 at 9 41 28 PM" src="https://user-images.githubusercontent.com/10672776/92072025-1e0efd00-ed65-11ea-8fc4-2bc28bcb7f0a.png">

**NOTE**: apart from this, the CRDs have additionalPrinterColumns, which display additional details about them on their individual pages

<img width="1198" alt="Screen Shot 2020-09-02 at 9 59 38 PM" src="https://user-images.githubusercontent.com/10672776/92073126-d3db4b00-ed67-11ea-96f0-194d72982788.png">

<img width="1196" alt="Screen Shot 2020-09-02 at 10 00 38 PM" src="https://user-images.githubusercontent.com/10672776/92073135-d89fff00-ed67-11ea-8a01-de323ffd2689.png">

**Comment by deniseschannon** [comment]
Based on discussion of this feature, we aren't going to introduce a Overview page.
