### ISSUE TITLE
Global Settings: Server URL: "Use the default value" is unresponsive 

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#10613]
**Setup**
- Rancher version: v2.9-head
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
The user is unable to restore the original server URL value after updating it. Clicking the "Use the default value" is unresponsive upon click.

**To Reproduce**

1. Go to Global Settings page
2. Scroll down to server-url section
4. Click on the three dots menu and click "Edit Setting"
5. Update the value (i used 'https://e2e-test.com')
6. Click "Save"
7. Scroll down to server-url section
8. Click on the three dots menu and click "Edit Setting"
9. Click on "Use the default value" button

**Result**
The user cannot restore the original server URL value after updating it.

**Expected Result**
~~The user can restore the original server URL value after updating it.~~
The reset button should be disabled since there is no default value for server-url

**Screenshots**

https://github.com/rancher/dashboard/assets/127343932/e6a3d443-67b1-4d65-be68-055be1a32b30

**Additional context**
When this is fixed please remove '.skip' from the corresponding e2e test to reenable it. (cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts ->> "can update server-url")

**Comment by izaac** [comment]
The process of changing the server url is not trivial, could you take a look at the documentation and check if updating it and then chaning to default would work?

https://www.suse.com/support/kb/doc/?id=000020173

**Comment by yonasberhe23** [comment]
e2e tests are sufficient. closing cc: @izaac
