### ISSUE TITLE
Add ability to change display name (title) for an extension

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#10623]
**Is your feature request related to a problem? Please describe.**

Currently we don't have a way to change the display name (title), meaning whatever is defined as `name` in `pkg/something/package.json` will be the display name (title in the UI) of such extension

**Describe the solution you'd like**

Decouple the display name (title in the UI) from `name` in `pkg/something/package.json`

**Describe alternatives you've considered**

**Additional context**

**Comment by nwmac** [comment]
@aalves08 I can think you can do this by using `catalog.cattle.io/display-name`

**Comment by nwmac** [comment]
e.g.

```
{
  "name": "harvester-manager",
  "description": "Provides the Virtualization Management feature in Rancher Manager",
  "version": "0.1.0",
  "private": false,
  "rancher": {
    "annotations": {
      "catalog.cattle.io/display-name": "Virtualization Manager"
    }
  },
  "scripts": {
    "dev": "./node_modules/.bin/nuxt dev",
    "nuxt": "./node_modules/.bin/nuxt"
  },
  "engines": {
    "node": ">=12"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "4.5.18",
    "@vue/cli-service": "4.5.18",
    "@vue/cli-plugin-typescript": "4.5.18"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by aalves08** [comment]
Closing issue as mechanism is already in place
