### ISSUE TITLE
Missing doc link to "GKE cluster provisioning docs" while creating Private GKE

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#10621]
**Setup**
- Rancher version: 2.8.3-rc3
- Rancher UI Extensions: v2.8.0
- Browser type & version: Chrome

**Describe the bug**

The doc link to access "GKE cluster provisioning docs" is missing.

**To Reproduce**

1. Go to GKE cluster creation form.
2. In `Cluster Options`, set `Private Cluster` to true, and click the link "GKE cluster provisioning docs"(ref:https://rancher.com/docs/rancher/v2.8/en/cluster-provisioning/hosted-kubernetes-clusters/gke/)

**Result**
404 Not Found
**Expected Result**

**Screenshots**

![Screenshot from 2024-03-14 14-13-59](https://github.com/rancher/dashboard/assets/11015077/dc4729a4-3ada-43b4-8fc9-64b42b1b711b)

**Additional context**

**Comment by nwmac** [comment]
@mantis-toboggan-md I suggest we ensure this is corrected in the Vue port

**Comment by eva-vashkevich** [comment]
Confirmed that documentation opens correctly after migration.

**Comment by valaparthvi** [comment]
I confirm it too on Rancher (v2.9-d2fa8a7d6116c48a814ee7983af522d614461e49-head) and Dashboard (master https://github.com/rancher/dashboard/commit/df60f440f41fe1b59c35b5181292504bb5e66059), thanks for checking @eva-vashkevich. I will close the issue now unless it needs to remain open.
