### ISSUE TITLE
Apps - No charts available when we switch clusters from the Global Nav dropdown.

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1062]
After this issue was fixed https://github.com/rancher/rancher/issues/28097

I was able to access the Downstream clusters' Dashboard and get the Apps, Install and remove.

But if we switch clusters from the Dashboard Global Nav dashboard I still see the message:

`There are no charts available, have you added any repos?` 

This is the switch in the UI
![Screen Shot 2020-08-20 at 2 52 57 PM](https://user-images.githubusercontent.com/27659/90829609-ec258180-e2f4-11ea-9c98-950e9ca64a18.png)

After switching Clusters click on Apps.

Workaround: Refresh the browser.
Rancher version: `master-head (08/20/2020)` _7f398fb3d_

**Comment by deniseschannon** [comment]
@vincent99 is this a backend or UI issue?

**Comment by izaac** [comment]
I am still experiencing this in Rancher version `master-head (09/01/2020)` _c428bc9_

Go to Dashboard in the Local cluster in an k8s HA setup. 
Go to a downstream cluster from the Dashboard dropdown  (Global Nav Bar)
Go to Apps
Return to Local cluster
Go to Apps.

No Apps listed

**Comment by deniseschannon** [comment]
Seems to be working as of today on master-head (9/8)

**Comment by izaac** [comment]
Rancher version: `master-head (09/09/2020)` _f7f8e8bb0_ Single Docker Install
Rancher version: `master-head (09/09/2020)` _f7f8e8bb0_ HA k8s

Validated switching clusters from the Global Nav Bar and listing Apps is working. 

Checked with local and downstream clusters.
