### ISSUE TITLE
Installing an Extension Can Break if the Cache Is Disabled in the CRD

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#10639]
If the cache is disabled for any reason, it can look like an extension didn't install or is waiting to install in perpetuity.

## Background

Rancher Dashboard uses the `isCached` property to confirm that the backend has acknowledged the presence of a newly installed extension[^1]. This implementation mitigated a race condition where an extension could appear like it didn't install; when a CR is created and triggeres a refresh, it's possible that the backend hasn't yet received the webhook to inform it of the new extension.

Changes recently introduced in rancher/rancher#44230 have modified the caching behavior. If any file is larger than 20MB, the cache is disabled and removes any recently saved files. Furthermore, users can manually disable the cache by changing the CRD, potentially breaking the plugin install process in Dashboard.

## Proposed Solution

Implement a polling mechanism to deal with the race condition, checking until the backend confirms that the extension installs successfully. 

## Investigation Needed

It's still unknown how the changes to caching might affect airgapped installations. 

## Related Jira

- SURE-6314
- SURE-6315

[^1]: https://github.com/rancher/dashboard/blob/bb66802a2dc9bbd724e5c1b5f60de0dd4cf31bc8/shell/pages/c/_cluster/uiplugins/index.vue#L464-L471

**Comment by rak-phillip** [comment]
@diogoasouza let me know if you think there's any additional context that we can include in this issue

**Comment by cnotv** [comment]
Related to https://github.com/rancher/dashboard/issues/10254

**Comment by gaktive** [comment]
Need to follow up with Mapps to figure out more on how the backend cache works before we can come up with a solution.

**Comment by aalves08** [comment]
added possible `automation-candidate` based on https://github.com/rancher/dashboard/issues/10711, which is a ticket to create an e2e to cover this scenario

**Comment by gaktive** [comment]
Sync with @richard-cox based on impending changes to extension load time for 2.9.0.

**Comment by aalves08** [comment]
Currently backend blocked by: https://github.com/rancher/rancher/pull/45521

Already created extension for the e2e test: https://github.com/rancher/ui-plugin-examples/tree/main/pkg/large-extension

Draft PR for e2e test (WIP): https://github.com/rancher/dashboard/pull/11027

**Comment by yonasberhe23** [comment]
e2e test is sufficient. moving to done
