### ISSUE TITLE
Move cluster management to top of global apps in the side bar

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10631]
Currently in the sidebar, we show:

![image](https://github.com/rancher/dashboard/assets/1955897/a350f748-c431-4000-9c75-7d3a6de8b8b5)

For some reason, Fleet is at the top of the global apps - I feel Cluster Management is used more and should be at the top.

This suggestion is to move Cluster mgmt link above the fleet one - i.e. swap two two shown below linked with the red line:

![image](https://github.com/rancher/dashboard/assets/1955897/e43f9999-5713-4085-9ea2-a19e64efbc9a)

**Comment by nwmac** [comment]
^^ FYI, @kwwii @edenhernandez-suse

**Comment by edenhernandez-suse** [comment]
I've got no data about it but it sounds pretty reasonable imo, I'm totally fine with that. However, I'd like to tackle that part of the Apps Bar at some point, we have a design that moves those links to dropdowns so they're more organised (especially when there are many apps installed)

**Comment by yonasberhe23** [comment]
e2e test is straight forward and lgtm. moving to 'Done' @izaac
