### ISSUE TITLE
Issues in CruResource

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1063]
**On master-head - commit id: `f08bf21f9`**

**Issue#1**

- Go to Namespace --> Click on a namespace
- Click on cancel --> Cancel pop up window is dark in light mode

<img width="1861" alt="Screen Shot 2020-08-20 at 2 45 17 PM" src="https://user-images.githubusercontent.com/26032343/90830851-4de6eb00-e2f7-11ea-9c40-678f4d54e8ae.png">

**Issue#2**
- Go to Namespace --> Click on a namespace
- "Action" button is seen
<img width="1689" alt="Screen Shot 2020-08-20 at 3 11 37 PM" src="https://user-images.githubusercontent.com/26032343/90830924-7a026c00-e2f7-11ea-9be7-30c78f237ddf.png">

**Comment by deniseschannon** [comment]
Issue #2 is already resolved.

@lvuch can you look at the styling of our pop up windows?

**Comment by lvuch** [comment]
@vincent99 removed all cancel modals

**Comment by deniseschannon** [comment]
The "back to form" still has the dark mode styling:

<img width="644" alt="Screen Shot 2020-09-14 at 4 13 14 PM" src="https://user-images.githubusercontent.com/11410997/93147036-3d7f2180-f6a5-11ea-966e-e91eecc72851.png">

**Comment by vincent99** [comment]
I removed the cancel *buttons* that were showing up on view/detail pages, but I didn't remove these modals (or at least not on purpose).

**Comment by deniseschannon** [comment]
Dark and light mode show this color now. 

![Screen Shot 2020-09-17 at 11.36.23 AM.png](https://zube.io/files/rancher/ca8515240067bdc572731e95e582b606-screen-shot-2020-09-17-at-11-36-23-am.png)

 ![Screen Shot 2020-09-17 at 11.35.42 AM.png](https://zube.io/files/rancher/d6ffdefe5bdd7c8eff7060a379fd9dc5-screen-shot-2020-09-17-at-11-35-42-am.png)
