### ISSUE TITLE
Fleet landing page shows a vertical scroll bar

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10632]
See below:

![image](https://github.com/rancher/dashboard/assets/1955897/fe9c26b3-129a-4c61-a512-13ebe4271491)

vertical scroll bar shown.

Looks like we need to remove the `min-height: 100vh` from the `fleet-dashboard` class.

**Comment by IsaSih** [comment]
The scroll bar still exists in v2.11-4c985fcfe6a04e511ba5a3940d27a6a97dd4ba83-head and it's present in various screen resolutions. Moving back to Reopen

**Comment by IsaSih** [comment]
tests pass in v2.11-d224815d7cfbf4194db1ffdfb04676d55d1a2062-head

![Image](https://github.com/user-attachments/assets/028abca6-57d4-49ce-805a-3d4775966728)
