### ISSUE TITLE
rancher/ui: migrate from Drone to Github Actions

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10635]
We need to move off Drone in the coming months and rely on Github Actions for our builds.

We should look at our Drone configuration on rancher/ui and see how much work is required to migrate to Github Actions. We may have other things running Drone to factor in, such as E2E tests.

**Comment by richard-cox** [comment]
Additional information in https://github.com/rancher/dashboard/issues/10287#issue-2086561544.

Noticed this was added to 2.8. We should probably have this one as 2.9 and create backport issues for 2.8 and 2.7

**Comment by gaktive** [comment]
Internal reference: SURE-7934

**Comment by richard-cox** [comment]
Linking all issues
- https://github.com/rancher/dashboard/issues/10635
- https://github.com/rancher/dashboard/issues/10634
- https://github.com/rancher/dashboard/issues/10633
