### ISSUE TITLE
rancher/dashboard: Move from Drone to Github Actions

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10633]
We need to move off Drone in the coming months and rely on Github Actions for our builds.

We should look at our Drone configuration on rancher/dashboard and see how much work is required to migrate to Github Actions. We may have other things running Drone to factor in, such as E2E tests.

**Comment by richard-cox** [comment]
Additional information in https://github.com/rancher/dashboard/issues/10287#issue-2086561544.

Noticed this was added to 2.8. We should probably have this one as 2.9 and create backport issues for 2.8 and 2.7

**Comment by gaktive** [comment]
Internal reference: SURE-7933

**Comment by gaktive** [comment]
@richard-cox the milestone used is mostly for us to keep track of the date of when to get this done, which is end of May. I don't know if we ship anything particularly involving Drone since this should be fairly internal but if this requires backports, I can make this 2.9.0 instead.

**Comment by richard-cox** [comment]
@gaktive that would be best. drone is used in each version's branch, so we'll need issues for each go forward branch (master / v2.9.0, release-2.8 / 2.8.next2 and release-2.7 / 2.8.next2) along with any patch branch (but i don't think we have any at the moment).

**Comment by gaktive** [comment]
Of note: there's a fork of this repo in the sandbox for Rancher Desktop. Once the migration to Github Actions is completed, we should sync with that team if they need to do anything on their side.

**Comment by richard-cox** [comment]
Linking all issues
- https://github.com/rancher/dashboard/issues/10635
- https://github.com/rancher/dashboard/issues/10634
- https://github.com/rancher/dashboard/issues/10633
