### ISSUE TITLE
rancher/api-ui: migrate from Drone to Github Actions

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10634]
We need to move off Drone in the coming months and rely on Github Actions for our builds.

We should look at our Drone configuration on rancher/api-ui and see how much work is required to migrate to Github Actions. We may have other things running Drone to factor in, such as E2E tests.

**Comment by gaktive** [comment]
Internal reference: SURE-7926

**Comment by richard-cox** [comment]
Linking all issues
- https://github.com/rancher/dashboard/issues/10635
- https://github.com/rancher/dashboard/issues/10634
- https://github.com/rancher/dashboard/issues/10633
