### ISSUE TITLE
Node Driver RKE1 Cluster: Unable to provision RKE1 Amazon EC2 cluster when using most recent k8s version (v1.28.7-rancher1-1) 

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#10640]
**Setup**
- Rancher version: v2.9-head
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
User is unable to provision a RKE1 Amazon EC2 cluster when using the most recent k8s version (v1.28.7-rancher1-1) in v2.9. Older k8s version options (v1.27.11, v1.26.14, v1.25.16) work as expected.

**Prerequisites** 
You must have AWS cloud credentials to create a node template which will be used in creating the cluster (let me know if you need credentials for this)

**To Reproduce**
1. go to Cluster Management
2. click 'Create'
3. toggle RKE1
4. under 'Provision new nodes and create a cluster using RKE' select Amazon EC2
5. fill in all required fields
6. verify the latest k8s version is selected by default (v1.28.7-rancher1-1)
7. click 'Create'
8. wait ~8 minutes and notice the error thrown in the UI ("GetDefaultKubernetesServicesOptions: No serviceOptions found for cluster version [v1.28.7-rancher1-1] or cluster major version [v1.28]")
 

**Result**
User is unable to provision a RKE1 Amazon EC2 cluster when using the most recent k8s version (v1.28.7-rancher1-1)

**Expected Result**
User is able to provision a RKE1 Amazon EC2 cluster when using the most recent k8s version (v1.28.7-rancher1-1)

**Screenshots**
<img width="1038" alt="Screenshot 2024-03-18 at 12 58 29 PM" src="https://github.com/rancher/dashboard/assets/127343932/2f9c3bff-99ca-402a-b130-0a0c89d30c59">

**Additional context**
Bocked by: https://github.com/rancher/rancher/issues/44931

**Comment by richard-cox** [comment]
@yonasberhe23 this seems like a rancher/rancher issue. if there's something new that's missing that the UI needs to supply they'll need to let us know

**Comment by yonasberhe23** [comment]
seems like this issue has been resolved. I'm no longer able to repro this with v1.30.1-rancher1-1, 1.29.3-rancher1-1, or v1.28.7-rancher1-1 k8s. this can be closed out.

tested in v2.9-e0af6cccbff0210e1538004dfc67f10f40597c20-head
