### ISSUE TITLE
Don't show state column on import yaml dialog

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10656]
Internal Reference: SURE-7870

After you import YAML, we should a list of the resources that were imported - this includes the state column, e.g.:

![image](https://github.com/rancher/dashboard/assets/1955897/27e6b714-9db3-4d89-a539-f4799add246b)

The state column is not live, so it does not update - this can be confusing/misleading.

We should remove this column as it would be difficult/non-performant to do so.

Note also, in some cases, we will see a sub-row saying something like `Deployment generation is 2, but latest observed generation is 1` - we should not show sub-rows in this view, since this represents an intermediate state and the view is not auto-updating, so this is mis-leading.

**Comment by yonasberhe23** [comment]
e2e test coverage covers the scenarios related to this ticket. moving to 'Done' cc: @izaac
