### ISSUE TITLE
Extend test automation for installing plugins to Rancher by using serve and compiled plugins

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#10659]
# Description

Extend current tests, so they will cover cases of a new plugin creation or update since it seemed not to cover critical points.

In a practical perspective, [all the used scripts](https://github.com/rancher/ui-plugin-examples/blob/main/package.json#L15-L22) should run successfully:

```
  "scripts": {
    "dev": "NODE_ENV=dev ./node_modules/.bin/vue-cli-service serve",
    "parse-tag-name": "./node_modules/@rancher/shell/scripts/extension/parse-tag-name",
    "build": "./node_modules/.bin/vue-cli-service build",
    "clean": "./node_modules/@rancher/shell/scripts/clean",
    "build-pkg": "./node_modules/@rancher/shell/scripts/build-pkg.sh",
    "serve-pkgs": "./node_modules/@rancher/shell/scripts/serve-pkgs",
    "publish-pkgs": "./node_modules/@rancher/shell/scripts/extension/publish"
  },
```

## Examples
- `defineComponent()`: summarized issues with previous/current versions in extension and dashboard, please @rak-phillip feel free to correct https://github.com/rancher/dashboard/issues/10104
- https://github.com/rancher/dashboard/issues/11414
- https://github.com/rancher/dashboard/issues/9537 (needed to be reverted)
- Verify a Harvester cluster dashboard page and its menu items rendered

These tests will simplify and ensure migration does not break existing plugins.

This would help with:
- https://github.com/rancher/dashboard/issues/11049
- https://github.com/rancher/dashboard/issues/10660

**Comment by cnotv** [comment]
@nwmac this should be done before the migration

**Comment by cnotv** [comment]
Pushing this out of the Vue3 planning and this milestone as we are testing manually all the extensions commands.

**Comment by cnotv** [comment]
@aalves08 do you think we can close this one or do we still miss the cases in the description?

**Comment by aalves08** [comment]
**"dev"**: this the command to run the skeleton app. This runs only locally and, imo, the effort to test it doesn't surpass the actual gains of having the test. This is used a lot by devs, including the internal devs responsible for multiple extensions and it's easy to spot a problem and notify someone. It's the same as testing `yarn dev` for rancher dashboard. I don't think it's worth it.
**"parse-tag-name"**: runs in `build-extension-charts`, which is covered by https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-master.yml + https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-release-2.8.yml + https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-release-2.9.yml
**"build"**: "./node_modules/.bin/vue-cli-service build", runs in `build-extension-charts`, which is covered by https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-master.yml  + https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-release-2.8.yml + https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-release-2.9.yml + `check-plugins-build` PR job
**"clean"**: yarn cache clean.  I don't think it's worth it.
**"build-pkg"**:   runs in `build-extension-charts`, which is covered by https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-master.yml  + https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-release-2.8.yml + https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-release-2.9.yml + `check-plugins-build` PR job
**"serve-pkgs"**: Runs in `check-plugins-build` PR job
**"publish-pkgs"**: runs in `build-extension-charts`, which is covered by https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-master.yml  + https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-release-2.8.yml + https://github.com/rancher/dashboard/blob/master/.github/workflows/test-extension-workflows-release-2.9.yml

given the reply above, I would say that we can close this if you agree 🙏
