### ISSUE TITLE
Side Nav Visual Bugs

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10662]
**Setup**
- Rancher version: v2.9-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
Bug 1
- Horizontal scroll bar shown on mouse over of clusters

Bug 2
- Cluster tooltip is shown far to the right away from it's cluster

Bug 3 - Spun out to https://github.com/rancher/dashboard/issues/10667
- ~Cluster badge's background colour (bar at bottom of cluster badge) does not cover bottom of badge~
- ~This could just be for disabled clusters (create a custom rke2 cluster)~

**To Reproduce**
- If not easily reproducible with random clusters, create clusters as per screenshot (disabled clusters are custom rke2 clusters)

**Result**
- see screenshot

**Expected Result**
- no horizontal scroll bar
- tooltip next to badge as previous
- ~badge colour goes to bottom of badge (size of badge should be the same as well)~

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/0cf5d9c0-c19f-4f66-9e6b-fa89f595f97c)

**Comment by aalves08** [comment]
Bugs 1 and 2 should be fixed by https://github.com/rancher/dashboard/pull/10535

**Comment by IsaSih** [comment]
Tests pass on v2.9-ca18e7126d90c20c720dd570ea900c357baafa93-head
