### ISSUE TITLE
Side Nav: Cluster Badge colour fails to reach bottom of cluster badge

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10667]
**Setup**
- Rancher version: v2.9-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
- Cluster badge's background colour (bar at bottom of cluster badge) does not cover bottom of badge
- This could just be for disabled clusters (create a custom rke2 cluster)

**To Reproduce**
- If not easily reproducible with random clusters, create clusters as per screenshot (disabled clusters are custom rke2 clusters)

**Result**
see screenshot

**Expected Result**
badge colour goes to bottom of badge (size of badge should be the same as well)

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/ebc0da3a-4988-49a1-a83d-4467c1b8067f)

**Additional context**
spun out from https://github.com/rancher/dashboard/issues/10662

**Comment by IsaSih** [comment]
Tests pass in https://github.com/rancher/dashboard/issues/10662, so I'm closing this issue as well.

**Comment by IsaSih** [comment]
I'm reopening this issue cause I could reproduce it on v2.9-e2023b437f3ccba16169b1e51db18419832ca5d7-head
<img width="1728" alt="Screenshot 2024-04-11 at 6 20 57 PM" src="https://github.com/rancher/dashboard/assets/70187881/012ca6d5-aeed-43bd-9e1d-9bba21d595c4">

**Comment by IsaSih** [comment]
Tests pass on v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head
