### ISSUE TITLE
Modals: Alignment and scroll artifact bugs

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10661]
**Setup**
- Rancher version: v2.9-head
- Rancher UI Extensions: Elemental
- Browser type & version:
  - Brave Version 1.61.104 Chromium: 120.0.6099.115 (Official Build)  (64-bit)
  - Chrome Version 123.0.6312.58 (Official Build) (64-bit)

**Describe the bug**
Bug 1
- Modal title is not vertically aligned
Bug 2
- On linux brave and chrome scroll artifacts are shown (white blank square bottom right in brave, disabled scroll bars in chrome)

**To Reproduce**
- Nav to Custom Cluster Badge modal from explorer cluster dashboard OR delete a resource with a warning modal

**Result**
- As per screenshots

**Expected Result**
- title aligned in middle of vertical space
- no scroll artifacts

**Screenshots**
Brave
![image](https://github.com/rancher/dashboard/assets/18697775/be79ce43-2061-4a5e-8f48-fd6467756f85)

![image](https://github.com/rancher/dashboard/assets/18697775/b2598852-eca2-4cfd-8141-cd08513aa6e4)

Chrome
![image](https://github.com/rancher/dashboard/assets/18697775/fa6706b0-9001-48aa-9217-0170549e4867)

![image](https://github.com/rancher/dashboard/assets/18697775/7e98a7af-a2d7-4984-8bb0-5eebb55890d3)

**Additional context**
- artefacts caused by `.modal-overlay .modal-container` `    overflow: scroll;`. see https://github.com/rancher/dashboard/pull/10556/files#diff-ffbc7799167852e06e43d04fe1a43795f231a53841ec183530113103493a0e96R94
- also tested on windows chrome, and see the same as above

**Comment by rak-phillip** [comment]
`Bug 1: Modal title is not vertically aligned` is not a regression (that's not to say that we won't address this). This was previously present in v2.8.2, before this change came in. Although, it does look like the font size for `h4` changed, I suspect that was being overridden via `
@import 'node_modules/vue-js-modal/dist/styles.css';`[^1] 

[^1]: https://github.com/rancher/dashboard/pull/10591/files#diff-005baee0e89b80d70ae61e1e4a01c8faa54ae6d66d6b17943fde4b8529a79bb6L1

## Before (v2.8.2)

![header-before](https://github.com/rancher/dashboard/assets/835961/efc9335b-c0ed-49e1-8458-fd66edaa66fc)

## After (v2.9-head)

![header-after](https://github.com/rancher/dashboard/assets/835961/723c82ac-1756-4c12-a14c-9035ca5155df)
