### ISSUE TITLE
Investigate and remove third party gh actions

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10663]
- [x] .github/workflows/build-extension-catalog.yml
  - [x] azure/setup-helm
    - azure is now allowed
  - [x] chrisdickinson/setup-yq
    - ~check not already installed, if no replace with a manual install~
    - ~possibly in ubuntu runner already (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#tools). need to work out if in rancher runners as well~
    - https://github.com/rancher/dashboard/pull/11015
- [x] .github/workflows/build-extension-charts.yml
  - [x] azure/setup-helm
    - azure is now allowed
  - [x] chrisdickinson/setup-yq
    - https://github.com/rancher/dashboard/pull/11015
  - [x] helm/chart-releaser-action
    - ~Request to add to approve list. See 726~
    - helm is now allowed
- [x] .github/workflows/docusaurus.yaml        
  - [x] peaceiris/actions-gh-pages@v3
    - ~Request to add to approve list. See 727~
    - https://github.com/rancher/dashboard/pull/11023
- [x] .github/workflows/notify-docs-team.yml
  - [x] jenschelkopf/issue-label-notification-action@1.3
    - Disabled for a long time, CI to remove, notify docs
    - https://github.com/rancher/dashboard/issues/11003 / https://github.com/rancher/dashboard/pull/11021
- [x] .github/workflows/test.yaml
  - [x] codecov/codecov-action@v3
    - ~Request to add to approve list. 728~
      - Request approved with caveats. Removed for the moment https://github.com/rancher/dashboard/pull/11107, re-add via https://github.com/rancher/dashboard/issues/11106

Any that cannot be replaced need to be discussed with team

- [x] 2.8 backport - https://github.com/rancher/dashboard/pull/11108
- [x] 2.7 backport - https://github.com/rancher/dashboard/pull/11117
- [x] 2.7 patch1 - https://github.com/rancher/dashboard/pull/11056
- [x] 2.8 patch1 - https://github.com/rancher/dashboard/pull/11118

**Comment by cnotv** [comment]
> codecov/codecov-action@v3

This is currently used for its intended purpose: unit tests coverage.
Good news, so far we increased of 4%

**Comment by gaktive** [comment]
This will help with moving off Drone.

If there are 3rd party actions we do need, we can ask for allowances if we need them but we should evaluate their current usage.

**Comment by cnotv** [comment]
`peaceiris/actions-gh-pages@v3` could be possible replaced by the official version https://github.com/actions/deploy-pages

**Comment by richard-cox** [comment]
EIO issue 2198 discusses process to enforce the allow list. No date set yet, i'll track for changes

**Comment by cnotv** [comment]
Just whoever is going to remove the actions has the responsibility to check first the alternatives because we do not want to remove services.
