### ISSUE TITLE
Prevent Extensions from breaking without providing info in case of Vue incompatibilities

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#10660]
# Description

The upgrade of Dashboard to Vue3 will have as a consequence to break Rancher Extensions. This will include several case scenarios which will have to be covered:
- Update Dashboard version to Vue3 with old plugins with Vue2
- Install new plugins with Vue3 to older Dashboard version with Vue2
- Install old plugins with Vue2 in a new Dashboard with Vue3

### Current

We currently just let extensions break the UI and it can be fixed using `?safemode` query parameter ([docs](https://extensions.rancher.io/extensions/advanced/safe-mode)).

### Planned

TBD

Note: This is going to be part of the outcome for https://github.com/rancher/dashboard/issues/11049

# Examples

- https://github.com/rancher/dashboard/issues/10675

**Comment by jordojordo** [comment]
This has been completed with https://github.com/rancher/dashboard/pull/12071, closing.
