### ISSUE TITLE
Labels and annotations section of Services is aligned to the left

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1067]
**On master-head - commit id: `f08bf21f9`**

- Go to Services
- Click on a service
- The labels and annotations sections for Services is aligned completely towards the left

<img width="1671" alt="Screen Shot 2020-08-20 at 4 30 04 PM" src="https://user-images.githubusercontent.com/26032343/90835912-bb4c4900-e302-11ea-9357-c657d3c9cad3.png">

**Comment by lvuch** [comment]
label and annotation tab is no longer in the ui. @sowmyav27 to confirm.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e919796c`**

Labels and annotations tab is no longer available,
<img width="1439" alt="Screen Shot 2020-09-14 at 3 37 03 PM" src="https://user-images.githubusercontent.com/26032343/93145012-399cd080-f6a0-11ea-9af0-5218f6546b28.png">

**Comment by deniseschannon** [comment]
It is still in the create/edit. For detail, labels and annotaitons moved to detail top.

<img width="777" alt="Screen Shot 2020-09-14 at 4 15 09 PM" src="https://user-images.githubusercontent.com/11410997/93147205-78815500-f6a5-11ea-8924-2612532d9336.png">
