### ISSUE TITLE
vSphere - Network, Tags and Parameters can be added but not removed

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#10693]
**Setup**
- Rancher version: 2.7-head, 2.8-head & 2.9-head

**Describe the bug**

When provisioning a vSphere cluster you can successfully add network, tags and parameters but you can't remove them afterwards.

**Screenshots**

https://github.com/rancher/dashboard/assets/135728925/d041cc7f-022f-4327-98e6-fda7cde2aff3

**Comment by izaac** [comment]
Validated on Rancher `v2.9-37f6eebf662459addc96bd31f486d8573a281c27-head`

I was able to add tags, networks and parameters during creation.
Edit was also working by adding and removing tags, networks and parameters. 
Tests editing 1 value of each. Added and then removed.
Tests editing 2 values of each. Added them and removed them.
Passed.

**Comment by izaac** [comment]
Validated on Rancher `v2.9-37f6eebf662459addc96bd31f486d8573a281c27-head`

I was able to add tags, networks and parameters during creation.
Edit was also working by adding and removing tags, networks and parameters. 
Tests editing 1 value of each. Added and then removed.
Tests editing 2 values of each. Added them and removed them.
Passed.
