### ISSUE TITLE
Adding Git repo takes precendence over HTTP

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#10697]
**Setup**
- Rancher version: 2.8-head
- Rancher UI Extensions: release-2.8 832a24819
- Browser type & version: Firefox

**Describe the bug**

When adding a repo, git repo takes precedence over the http repo, if both the forms are filled.

**To Reproduce**

1. Go to "Repository: Create" form.
2. Select target: Git repo
3. Enter the git repo and branch name.
4. Select target: http
5. Enter the http URL.
6. Hit Save.

**Result**
The repo pointed by git is taken into account.

**Expected Result**

The HTTP repo should have been used.
**Screenshots**

[Screencast from 03-26-2024 12:59:12 PM.webm](https://github.com/rancher/dashboard/assets/11015077/d44281e8-8b5c-426f-b7a8-71d5bf38a960)

**Additional context**

**Comment by torchiaf** [comment]
Thanks for reporting this issue @valaparthvi . However, the issue was implicity fixed in https://github.com/rancher/dashboard/pull/10325 and will be available in `v2.9.0`.
CLosing as resolved.
