### ISSUE TITLE
Pod page displays incorrect node

### ISSUE THREAD

**Issue by RyanSearle** [rancher/dashboard#1070]
The pod listing page correctly shows the pod's node however when clicking through to the pod page the node always references a single node rather than the actual node it's mounted on.

Listing page:
![image](https://user-images.githubusercontent.com/14178641/90886997-6f091380-e3ab-11ea-827a-501646813a86.png)

Pod page:
![image](https://user-images.githubusercontent.com/14178641/90887030-7d572f80-e3ab-11ea-9efd-b7d71a780c7a.png)

**Comment by deniseschannon** [comment]
@RyanSearle What version of Rancher are you running?

**Comment by RyanSearle** [comment]
Rancher | v2.4.4
User Interface | v2.4.22
Helm | v2.16.5-rancher1
Machine | v0.15.0-rancher36

**Comment by deniseschannon** [comment]
The design of this page has changed in our latest updates that are geared for our 2.5 release and the node is showing up the same in the list page and the detailed page, so I'll close this issue.
