### ISSUE TITLE
Tweaks to new cluster switch feature

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10706]
1. One concrete ask - can we change the text in the tooltip, from:

![image](https://github.com/rancher/dashboard/assets/1955897/c1fe3323-effa-47ee-a56f-cd2eb0ee5a62)

to `Switch clusters and keep location`.

i.e. remove the plural on `keeps`

2. On the mac, I noticed if you press SHIFT+ALT and then also hold down COMMAND+F5, the arrow overlay gets stuck:

![image](https://github.com/rancher/dashboard/assets/1955897/251f4c86-7e28-4d7d-9e7b-018a448c52b4)

I don't know if there are other cases where it can get stuck.

3. I find ALT+SHIFT awkward - I can't see a reason why we can't just use ALT? Can we change that @kwwii ??

4. lodash - I notice the code changes use `lodash/isObject` - generally we should avoid lodash and looks like it is not really needed in this case - can we remove?

**Comment by IsaSih** [comment]
Tests pass on v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head
