### ISSUE TITLE
Apps - rancher-logging chart options form some fields filled with [object Object]

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1071]
- Navigate to Dashboard -> Apps -> Charts
- Click on `rancher-logging`
- Chart Options

![Screen Shot 2020-08-21 at 7 11 54 AM](https://user-images.githubusercontent.com/27659/90900201-eb84fd80-e37d-11ea-8923-e60e044dd96f.png)

I can't see the `Password` and `Client key pass` fields but those where not filled in previous builds.

Rancher version `master-head (08/21/2020)` _8a14c935a_

**Comment by deniseschannon** [comment]
As the options for chart deployment are changing, I've kept this around in case they get translated to the cluster output deployment pages

**Comment by codyrancher** [comment]
I don't think we need to keep this open. This is being caused because these fields got converted to secrets. https://github.com/rancher/dashboard/issues/1031 is concerned with this issue.

**Comment by izaac** [comment]
Agreed, we can track this in the issue mentioned by @codyrancher when the new apps UI is available.
