### ISSUE TITLE
Create e2e tests for extensions that exceed 20mb cache limit

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#10711]
Create e2e tests to demonstrate that extensions properly install when the cache is disabled. 

## Proposed solution

This can be achieved by creating a new extension in [rancher/ui-plugin-examples](https://github.com/rancher/ui-plugin-examples) that has an asset that exceeds 20mb, publish it on the repo, and it would be automatically available to run an e2e about installing that extension.

## Prior work

- https://github.com/rancher/dashboard/blob/master/cypress/e2e/tests/pages/extensions/extensions.spec.ts

## Related issues

#10639
#10700

**Comment by aalves08** [comment]
Currently backend blocked by: https://github.com/rancher/rancher/pull/45521

Already created extension for the e2e test: https://github.com/rancher/ui-plugin-examples/tree/main/pkg/large-extension

Draft PR for e2e test: https://github.com/rancher/dashboard/pull/11027

**Comment by gaktive** [comment]
Will fold this ticket in #10639
