### ISSUE TITLE
Drivers: Unable to deactivate drivers in bulk

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#10718]
**Setup**
- Rancher version: v2.9-head
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
User is unable to `deactivate` cluster/node drivers in bulk. 

**To Reproduce**
1. login to Rancher as an admin
2. go to the Cluster Management page
3. click 'Drivers' tab in the side nav
4. click Cluster/Node Drivers tab
5. select two or more active drivers
6. click deactivate
7. notice only one of the drivers selected were deactivated

**Result**
User is unable to `deactivate` cluster/node drivers in bulk. 

**Expected Result**
User is able to `deactivate` cluster/node drivers in bulk. 

**Screenshots**

https://github.com/rancher/dashboard/assets/127343932/2552b278-0256-4060-8f65-ab1938848e34

**Additional context**
We are currently skipping the associated e2e tests in `kontainer-drivers.spec.ts` and `node-drivers.spec.ts`. Please enable them once this issue has been resolved by removing `.skip`.

**Comment by gaktive** [comment]
Once there's a possible fix, there's an E2E to reenable to try it out.

**Comment by yonasberhe23** [comment]
e2e tests are sufficient. moving to done
