### ISSUE TITLE
Node Driver: RKE2 cluster provisioning: User gets error when attempting to provision a RKE2 cluster for a newly activated node driver

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#10717]
**Setup**
- Rancher version: v2.9-head
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
User gets the below error when attempting to provision a RKE2 cluster with a newly activated node driver.
Error: `Cannot find resourceFields for Schema rke-machine-config.cattle.io.linodeconfig (schemaDefinitions have not been fetched)`
Note: This issue is resolved after the user waits about ~2-3 minutes and refreshes the page.
 

**To Reproduce**

1. login to Rancher as an admin
2. go to the Cluster Management page
3. click 'Drivers' tab in the side nav
4. click 'Node Drivers' tab
5. activate any node driver
6. go back to cluster management page
7. click create
8. toggle RKE2/k3s
9. select the newly activated node driver
10. notice error in UI

**Result**
User gets an error when attempting to provision a RKE2 cluster with a newly activated node driver.

**Expected Result**
User should be prompted to enter cloud credentials/access tokens to provision a RKE2 cluster.

**Screenshots**

https://github.com/rancher/dashboard/assets/127343932/fb33b3fe-7e58-458d-98ca-beb09827300b

**Additional context**

**Comment by yonasberhe23** [comment]
this may only need a backend fix (https://github.com/rancher/rancher/issues/44992), but will leave this open for tracking purposes.

**Comment by gaktive** [comment]
Candidate for a 2.9.x backport

**Comment by eva-vashkevich** [comment]
Hi @yonasberhe23 are you able to reproduce it on 2.10? I've tried different node drivers and none of them have given an error.

**Comment by yonasberhe23** [comment]
@eva-vashkevich i'm unable to repro this issue. I'll close this out.
