### ISSUE TITLE
[CIS v2]: overview page 

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1072]
Need an overview page on dashboard UI  that is kind of like a dashboard of the feature.

**Overview/ Description**
The rancher-cis-benchmark feature provides the ability to run CIS benchmark scans on a kubernetes cluster and generate scan compliance reports. This feature supports the scanning ability to cluster types like EKS, GKE, RKE2 along with RKE clusters.

This currently supports following CIS 1.5 benchmark versions by default, which are available when you enable this feature:
a) rke-cis-1.5-permissive - Permissive profile runs custom CIS 1.5 tests on RKE clusters and skips some tests that need special cluster hardening steps.
b) rke-cis-1.5  - This profile runs custom CIS 1.5 tests on RKE clusters and does not skip any tests and expects that the cluster is hardened. Check [here](link to 2.5 hardening guide) how to harden RKE clusters according to CIS 1.5 benchmarks.
c) gke-1.0 - This is the upstream kube-bench GKE benchmark.
d) eks-1.0 - This is the upstream kube-bench EKS benchmark.
e) cis-1.5 - This is the default CIS 1.5 benchmark which can be run on any kubernetes cluster.

The feature utilizes the kube-bench tool (https://github.com/aquasecurity/kube-bench) - Connect to preview  to run the CIS benchmarks. Also to generate a cluster-wide report the feature utilises the sonobuoy-tool for report aggregation (https://github.com/vmware-tanzu/sonobuoy). - Connect to preview 

Clusterscan results are stored in a ClusterScanReport available after scans are finished.

**External Links:**
- kube-bench tool (https://github.com/aquasecurity/kube-bench) - Connect to preview 

**CRD's:**

Following are the CRD’s that the CIS v2 feature defines:
All these CRD's are cluster scoped. [non-namespaced]
1. [ClusterScanBenchmark](https://github.com/rancher/dashboard/issues/1173)
2. [ClusterScanProfile](https://github.com/rancher/dashboard/issues/1035)
3. [ClusterScan](https://github.com/rancher/dashboard/issues/1036)
4. [ClusterScanReport](https://github.com/rancher/dashboard/issues/1038)

**CRD Explanations:** 
Each of the GH tickets above explain respective CRD and the fields.

**CRD Relational Model:** 

Following is the correlation between the CIS CRDs:
- ClusterScanBenchmark - Few default benchmark CRs
- ClusterScanProfile - Multiple  ClusterScanProfiles can be created using one ClusterScanBenchmark. Few default ClusterScanProfiles per default benchmark will be available by default. But user can create new ClusterScanProfiles and choose one of the available ClusterScanBenchmark.
- ClusterScan- Multiple ClusterScans can be created for a ClusterScanProfile
- ClusterScanReport- One is to one relation with ClusterScan. A ClusterScanReport is created per ClusterScan.

<img width="663" alt="Screen Shot 2020-09-02 at 11 40 02 PM" src="https://user-images.githubusercontent.com/1470602/92080065-c331d180-ed75-11ea-9219-2a112c003343.png">

**User Flow**

1. After the feature chart is installed, User should be able to list the default ClusterScanBenchmark CRs and the default ClusterScanProfiles CR's.

2. How to run a scan on the cluster?
  -  Create a CusterScan CR
  -  Choose a ScanProfileName - choose a name from list of ClusterScanProfiles. Optional, if left empty default 
     ClusterScanProfile that matches the cluster provider is picked.
  -  Save.

3. How To check cluster scan status?
  - Check the status of the CusterScan instance created. When the scan finishes, the status will show:
       - LastRunTimestamp
       - Summary (number of tests total/fail/skip/not-applicable)

4. How to view scan report?
  - After a CusterScan is complete, a ClusterScanReport CR is created.
  - List the CusterScanReports and check for a report with name matching the ClusterScan "scan-report-<CusterScan's 
    name>"

7. How to list all ClusterScans? 
  - On the Dashboard, all ClusterScans will be listed. The CRD has additionalPrinterColumns, which displays additional 
    status fields of the ClusterScan

8. How to skip some tests from a ClusterScan?
  - Create a new ClusterScanProfile or Clone from an existing ClusterScanProfile
  - In the ClusterScanProfile YAML, define the list of testID's to be skipped: SkipTests []string.
  - Save
  - Now create a new ClusterScan and choose this custom ClusterScanProfile created. 
  - The scan will skip the tests mentioned in the profile.

### Mockup based on [this](https://xd.adobe.com/view/62ea899e-acc6-4b72-a654-9ecf811430a8-37b9/) template
<img width="1024" alt="Screen Shot 2020-09-02 at 11 05 53 PM" src="https://user-images.githubusercontent.com/1470602/92078436-18201880-ed73-11ea-8960-4bbe2a4706e0.png">

**Comment by deniseschannon** [comment]
As of now, no overview page for 2.5 as we will clean up the individual CRD pages.
