### ISSUE TITLE
Internal error saving certificates in RKE2 clusters creation

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#10725]
**Setup**
- Rancher version: v2.9-head

**Describe the bug**

Users can specify a list of registries to allow Rancher to pull container images from those registries during cluster provisioning.
For each registry, users can specify an authentication certificate, in `base64` format.

If the certificate is in wrong format, a server error is displayed on top of the form.

**To Reproduce**

- Go to Cluster Managements -> Create a new RKE2 cluster
- Click on Registries tab in Cluster Configuration section
- Enable Cluster registries
- Click on Advanced
- Add a new Registry Authentication -> set 'Registry Hostname', 'Authentication' and an invalid SSH key to  'CA cert bundle' field
- Click Save

**Result**

Rancher returns a server error

**Expected Result**

- The Ui should translate the user's input in base64 format in request's payload.
  or
- There should be a tooltip icon in the certificate's input field, saying what format is expected.

**Screenshots**

![image (8)](https://github.com/rancher/dashboard/assets/26394656/52a00374-e54f-42cd-a45e-7bab7743df6e)

**Additional context**

from #discuss-rancher  channel

**Comment by nwmac** [comment]
@torchiaf This is certainly annoying - do you think its okay to push this to 2.10.0 and backport to 2.9.x ?

**Comment by torchiaf** [comment]
@nwmac let's move it to 2.10.0. I'll take a look if there are other similar cases in the UI and make an estimate.

**Comment by izaac** [comment]
The unit tests here seem enough to me to validate the fix.
