### ISSUE TITLE
Fleet status shows error for an imported cluster

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10738]
Create a cluster and then import it into Rancher.

The new Fleet status always shows an error.

It looks like for an imported cluster, the fleet agent is a StatefulSet and not a Deployment, so we are failing to find it.

I also don't see the cluster agent status for an imported Cluster.

**Comment by richard-cox** [comment]
I've seen this in a DO RKE2 cluster as well. dashboard fleet icon shows error, `fleet-agent` was a statefulset
