### ISSUE TITLE
Can't log in to the Rancher: Rancher UI continuously loading loading

### ISSUE THREAD

**Issue by vladbeha109** [rancher/dashboard#10735]
**Setup**
- Rancher version: v2.8.2
- Browser type & version: Google Chrome

**Describe the bug**
Starting from March one time per 1/2 week we can't login/browse the Rancher, it's indefinitely loading, on the container logs we see only errors related to WebSocket disconnection.

Rancher stuck on loading -> Restarted rancher - > the one node became unavailable -> restarted node -> Cluster is back to normal (sometimes node restart doesn't help).

**To Reproduce**
No actual scenario

**Result**
Rancher UI indefinitely loading

**Expected Result**
No issues that can impact user experience

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/50966254/ff0cceb8-94a7-4b05-b509-ce63b8926e44)

**Additional context**
Infrastructure description:
The rancher container is running on a separate server in Azure - Linux (ubuntu 18.04)/Standard D8s v3
The cluster was created through the Rancher - 3 Linux nodes(Control plane, etcd, worker) and 5 Windows nodes
Kubernetes Version: v1.24.16 +rke2r1

NAME             STATUS   ROLES                              AGE    VERSION
qa-neo-wnode1    Ready    worker                             103d   v1.24.16
qa-neo-wnode2    Ready    worker                             103d   v1.24.16
qa-neo-wnode3    Ready    worker                             103d   v1.24.16
qa-neo-wnode4    Ready    worker                             96d    v1.24.16
qa-neo-wnode5    Ready    worker                             41d    v1.24.16
qa-neo-worker1   Ready    control-plane,etcd,master,worker   226d   v1.24.16+rke2r1
qa-neo-worker2   Ready    control-plane,etcd,master,worker   227d   v1.24.16+rke2r1
qa-neo-worker3   Ready    control-plane,etcd,master,worker   39d    v1.24.16+rke2r1

**Logs**
024-04-02T08:15:16.668277574Z"}
{"log":"W0402 08:17:33.040326      48 transport.go:301] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-04-02T08:17:33.040648063Z"}
{"log":"W0402 08:17:33.153651      48 transport.go:301] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-04-02T08:17:33.153831208Z"}
{"log":"W0402 08:17:33.153684      48 transport.go:301] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-04-02T08:17:33.153862008Z"}
{"log":"W0402 08:17:33.153711      48 transport.go:301] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-04-02T08:17:33.153881508Z"}
{"log":"W0402 08:17:33.282101      48 transport.go:301] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-04-02T08:17:33.282265573Z"}
{"log":"W0402 08:17:35.946516      48 transport.go:301] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-04-02T08:17:35.94684618Z"}
{"log":"W0402 08:17:37.544349      48 transport.go:301] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-04-02T08:17:37.544720791Z"}
{"log":"W0402 08:17:37.601628      48 transport.go:301] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-04-02T08:17:37.60176672Z"}
{"log":"W0402 08:17:37.971121      48 transport.go:301] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-04-02T08:17:37.971340089Z"}
{"log":"2024/04/02 08:18:09 [ERROR] Error during subscribe websocket: close sent\n","stream":"stdout","time":"2024-04-02T08:18:09.520165786Z"}

**Comment by torchiaf** [comment]
Hi, could you provide some additional information about the issue (logs and screenshots):

- Does 'indefinitely loading' mean you have the blank page showing a spinner icon or something else ?
- Do you have any https errors in the browser's console?
- Could you double check the support matrix page? It seems Rancher is running on unsupported k8s version https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-2/

**Comment by gaktive** [comment]
Hi @vladbeha109 !

We haven't heard from you in a while. Were you able to resolve the questions back in April about your issue? As noted, the version of Rancher you were running doesn't support the version of Kubernetes in place so you'll need to upgrade that.

I'll close this ticket for now. Feel free to reopen this when you have time to get back to us or file a new ticket.

**Comment by berkaykirtillii** [comment]
> Hi @vladbeha109 !
> 
> We haven't heard from you in a while. Were you able to resolve the questions back in April about your issue? As noted, the version of Rancher you were running doesn't support the version of Kubernetes in place so you'll need to upgrade that.
> 
> I'll close this ticket for now. Feel free to reopen this when you have time to get back to us or file a new ticket.
I had a similar problem and I am writing it here because I came across it. I apologize if it is irrelevant.

I run the rancher dashboard project by cloning it and run rancher as a docker image. I can log in to the dashboard via Docker, but the login screen does not appear like this in the dashboard project I run with yarn dev. 
![Screenshot from 2025-01-09 20-27-31](https://github.com/user-attachments/assets/68afe005-8e69-443d-99b0-58dff21cc5eb)
