### ISSUE TITLE
Resource Subtype Display - Masthead

### ISSUE THREAD

**Issue by westlywright** [rancher/dashboard#1073]
Spinning out a new issue from rancher/dashboard#966 re: displaying the resource subtype in masthead.

Masthead should be aware of any subtypes selected in CruResource and display that subtype:

`<ResourceType>: <Action> <Subtype-ifexists>`

**Comment by deniseschannon** [comment]
Current 2 resources that use subtypes:

Workload
Service

Evnetually secret will use it as well

**Comment by deniseschannon** [comment]
Workload was changed to go directly to the CRD, but Service is a sub-type that's not an actual CRD, so is a special use case. Secret will fall under the same category.

**Comment by deniseschannon** [comment]
Workload was changed due to the "subtype" of workloads were actual CRDs. This change will need to be used for Service and eventually secret.

**Comment by deniseschannon** [comment]
@tfiduccia Can you test that this is working for Service where you will be able ot see the subtype after it's selected?

**Comment by tfiduccia** [comment]
Fixed
