### ISSUE TITLE
Developer docs refer to incorrect password info

### ISSUE THREAD

**Issue by martyav** [rancher/dashboard#10740]
**Is your feature request related to a problem? Please describe.**
While researching information about the Rancher admin and bootstrap passwords for the Rancher docs, I found https://github.com/rancher/dashboard/blob/master/docusaurus/docs/code-base-works/auth-sessions-and-tokens.md. I don't know about the history or visibility of this page, but it claims that the password can't match the username. According to https://github.com/rancher/rancher-docs/pull/1208#issuecomment-2032744511, the password merely needs to fulfill the minimum  length requirement. It's still not clear to me if the minimum length value is alterable to users in current versions of Rancher. Finally, the bootstrap password is a special case and doesn't need to meet the minimum length requirement after all (https://github.com/rancher/rancher-docs/pull/1208#issuecomment-2032343124)

**Describe the solution you'd like**

If https://github.com/rancher/dashboard/blob/master/docusaurus/docs/code-base-works/auth-sessions-and-tokens.md is visible to users, we should definitely update it, as the information is misleading and not in sync with https://ranchermanager.docs.rancher.com/.

**Describe alternatives you've considered**

**Additional context**

I'm currently working on https://github.com/rancher/rancher-docs/pull/1208 for https://ranchermanager.docs.rancher.com/, so if there are any corrections or omissions for the admin/bootstrap password, feel free to help.

**Comment by rak-phillip** [comment]
@martyav The document in questions is accessible via our developer docs[^1]. I'm thinking that it might suffice to simply link to the Rancher password requirements instead of detailing them ourselves. This can cut down on duplication while still allowing us to effectively convey our message.   

[^1]: https://rancher.github.io/dashboard/code-base-works/auth-sessions-and-tokens

**Comment by kwwii** [comment]
https://github.com/rancher/dashboard/blob/master/docusaurus/docs/internal/code-base-works/auth-sessions-and-tokens.md <- the page in question
