### ISSUE TITLE
Unable to cancel request for *client.addQuery\n","stream":"stderr"

### ISSUE THREAD

**Issue by nanited** [rancher/dashboard#10768]
**Setup**
- Rancher version: 2.6.2
- Browser type & version: Safari

**Describe the bug**
we can't login/browse the Rancher, it's indefinitely loading, on the container logs we see only errors related to WebSocket disconnection and unable to communicate with k8s API

**To Reproduce**
No actual scenario to reproduce the issue

**Result**
Rancher UI indefinitely loading, not responding from the UI

**Expected Result**
Has to load the UI and make continuous connection with k8s api

**Additional context**
Infrastructure description:
The rancher container is running on a separate rke cluster on on-prem - RHEL (7.9)
The cluster was created through the Rancher - 3 Masters(Control plane, etcd, worker) and 10 Windows nodes
Kubernetes Version: v1.21.11 +rke

NAME STATUS ROLES AGE VERSION
master0-               Ready    controlplane,etcd   2y119d   v1.20.11
master1                 Ready    controlplane,etcd   2y119d   v1.20.11
master2.                Ready    controlplane,etcd   2y119d   v1.20.11
k8dev01-worker0       Ready    worker              2y119d   v1.20.11
k8dev01-worker1        Ready    worker              2y119d   v1.20.11
k8dev01-worker10      Ready    worker              704d     v1.20.11
k8dev01-worker2        Ready    worker              2y119d   v1.20.11
k8dev01-worker3         Ready    worker              2y119d   v1.20.11
k8dev01-worker4         Ready    worker              2y119d   v1.20.11
k8dev01-worker5         Ready    worker              2y119d   v1.20.11
k8dev01-worker6         Ready    worker              2y119d   v1.20.11
k8dev01-worker8         Ready    worker              705d     v1.20.11
k8dev01-worker9         Ready    worker              704d     v1.20.11

Logs: Cattle-cluster-agent

msg=\"Failed to dial steve aggregation server: websocket: close 1006 (abnormal closure): unexpected EOF\"\n","stream":"stdou        t",

  73049 {"log":"W0320 20:15:55.631076      56 transport.go:260] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-03-20T20:15:55.631633189Z"}
  73050 {"log":"time=\"2024-03-20T20:16:14Z\" level=error msg=\"error syncing 'kong-data-plane-kong-validations': handler need-a-cert: services \\\"kong-data-plane-kong-validation-we        bhook\\\" not found, requeuing\"\n","stream":"stdout","time":"2024-03-20T20:16:14.383951461Z"}
  73051 {"log":"time=\"2024-03-20T20:16:14Z\" level=error msg=\"error syncing 'elastic-webhook.k8s.elastic.co': handler need-a-cert: services \\\"elastic-webhook-server\\\" not found        , requeuing\"\n","stream":"stdout","time":"2024-03-20T20:16:14.383981182Z"}
  73052 {"log":"time=\"2024-03-20T20:16:14Z\" level=error msg=\"error syncing 'kong-control-plane-kong-validations': handler need-a-cert: services \\\"kong-control-plane-kong-validat        ion-webhook\\\" not found, requeuing\"\n","stream":"stdout","time":"2024-03-20T20:16:14.383985086Z"}
  73053 {"log":"W0320 20:16:28.604042      56 transport.go:260] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-03-20T20:16:28.604964764Z"}
  73054 {"log":"W0320 20:16:47.513866      56 transport.go:260] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-03-20T20:16:47.514916439Z"}
  73055 {"log":"W0320 20:16:47.520376      56 transport.go:260] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-03-20T20:16:47.52045307Z"}
  73056 {"log":"W0320 20:16:47.548199      56 transport.go:260] Unable to cancel request for *client.addQuery\n","stream":"stderr","time":"2024-03-20T20:16:47.548262609

**Comment by richard-cox** [comment]
2.6.2 is no longer a supported version https://www.suse.com/lifecycle/#suse-rancher-prime. In all worlds you'll need to update to a newer, supported one.

**Comment by nanited** [comment]
Which is the suitable version which we avoid this issue I have observed that UI slowness issue is there in multiple versions. 
Will you help me with that please ?

**Comment by richard-cox** [comment]
Responded in https://github.com/rancher/dashboard/issues/10769#issuecomment-2042916047
