### ISSUE TITLE
Update `DOCS_BASE` to v2.9

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10766]
- Current `DOCS_BASE` points to `https://ranchermanager.docs.rancher.com/v2.8`
- When 2.9 becomes available value needs updating
- Need to sync with docs team on when this will be

**Comment by btat** [comment]
> @btat are there any existing requests to do this bump already? I couldn't find any.

I'll be generating the 2.9 content next week.

**Comment by btat** [comment]
https://ranchermanager.docs.rancher.com/v2.9 is live now.

**Comment by momesgin** [comment]
@izaac should this be a manual test candidate?

**Comment by izaac** [comment]
@momesgin I see this `DOCS_BASE` variable in the dashboard repository, do we external link them or use them for translations in the UI?

If that's the case perhaps a simple validation to check the UI links to the proper Rancher Docs `DOCS_BASE`?

**Comment by momesgin** [comment]
> [@momesgin](https://github.com/momesgin) I see this `DOCS_BASE` variable in the dashboard repository, do we external link them or use them for translations in the UI?
> 
> If that's the case perhaps a simple validation to check the UI links to the proper Rancher Docs `DOCS_BASE`?

@izaac I believe we're already doing that indirectly by checking the support links on the home page, for example the Docs item on that list gets its value from DOCS_BASE.

**Comment by izaac** [comment]
We are good if that health check exist. 👍🏽

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
