### ISSUE TITLE
Issues in filter/dropdown in Overview page 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1078]
**On master-head - commit id: `8a60de75d`**

**Issue#1**

- In the filter - Choose `"All Namespaces"/ "Only System Namespaces"`
- Notice the count of resources in "Cluster Explorer" Increases - Like of Deployments/Jobs/Pods
<img width="437" alt="Screen Shot 2020-08-24 at 11 57 09 AM" src="https://user-images.githubusercontent.com/26032343/91084516-f8fdea00-e600-11ea-89e9-13961b1db20d.png">

- Remove  `"All Namespaces"/ "Only System Namespaces"` from filter and notice Deployments/Jobs/Pods count goes to Zero. 

Why is that when there is a filter selected the count increases and when there is no filter, the count is zero ? 

**Issue#2**

- Add values to the filter/dropdown.
- The size of the filter increases horizontally. And overlaps "Cluster Manager" button on the right.

<img width="1838" alt="Screen Shot 2020-08-24 at 11 36 00 AM" src="https://user-images.githubusercontent.com/26032343/91084413-d23fb380-e600-11ea-8a40-ad1c480f7ce1.png">

**Comment by vincent99** [comment]
The default view is filtered to hide system resources ("only user namespaces").  So when you choose "All namespaces", you're adding more potential namespaces to find resources (and those same things are in "only system namespaces")

**Comment by deniseschannon** [comment]
First issue doesn't seem to be an actual issue, but #2 will be a problem if it keeps filling up. Likelihood of someone picking that many namespaces is low so this is prioritized accordingly.

**Comment by deniseschannon** [comment]
Issue #1 - behaving as expected, no filters = "only user namespaces"
Issue #2 - doesn't overlap cluster manager. it touches cluster manager and could use some padding but not big enough to be an issue.

**Comment by sowmyav27** [comment]
Closing as per comments https://github.com/rancher/dashboard/issues/1078#issuecomment-690855203
