### ISSUE TITLE
Rancher UI branding customisation is not persistent on the login screen

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#10788]
Internal reference: SURE-8175

**Setup**
- Rancher version: repro'ed in Rancher 2.8.2 and 2.9-head
- Rancher UI Extensions: n/a
- Browser type & version: n/a

**Describe the bug**

The customer reports that before logging in, the login page does not use the primary and link colours. For example, they set both colours to orange, and the login page stays blue, as with the default parameters.

**To Reproduce**

- In The UI > Global Settings > Branding > Set "Primary Color" to Orange + set "Link Color" to Orange > Apply.
- Notice the change to Orange
   

![image-2024-04-11-12-22-12-190 (2)](https://github.com/rancher/dashboard/assets/97888974/d4976980-343d-41b6-9194-a1bd00d756f1)

- Now "Logout" and notice the colour is still orange:

![image-2024-04-11-12-23-04-242](https://github.com/rancher/dashboard/assets/97888974/e5fd5560-edfe-417f-bd34-1cda1ca9d34d)

- If you refresh the browser page, you'll notice that the colour has changed to the default:

![image-2024-04-11-12-23-48-336](https://github.com/rancher/dashboard/assets/97888974/8599c65b-5b81-4780-84a2-dd25e2e809bb)

- If you log back in, the colour scheme is orange:
![image-2024-04-11-12-24-34-644](https://github.com/rancher/dashboard/assets/97888974/2dc91d99-494b-4240-8f8d-b1cc67f7bf37)

**Result**
- Branding does not persist on logout/login screen

**Expected Result**

- Branding should be consistent and persistent

**Screenshots**

**Additional context**

**Comment by aalves08** [comment]
After further investigation the UI expects for settings like `ui-primary-color` and `ui-link-color` (items manipulated according to repro steps) and they aren't present on the network request for `settings` when the user is logged out. This doesn't appear to be a UI issue, especially since the `brand` mixin is applied and working properly on the `unauthenticated` layout, which is used by the `login` and `logout` views.

https://github.com/rancher/dashboard/blob/master/shell/config/router.js#L116-L129


![Screenshot 2024-04-11 at 15 55 49](https://github.com/rancher/dashboard/assets/97888974/99796f62-9a62-41a2-850e-e95b22152c28)
![Screenshot 2024-04-11 at 15 56 03](https://github.com/rancher/dashboard/assets/97888974/e8c6416d-040c-43bf-91f2-ba942e3bdb96)
![Screenshot 2024-04-11 at 16 01 26](https://github.com/rancher/dashboard/assets/97888974/851a1c72-88a3-4f8b-bb3d-859fd0f3bcff)

**Comment by aalves08** [comment]
**UPDATE:** With the merge of https://github.com/rancher/rancher/pull/45108, if you provision a new `2.9-head` the properties ui-`primary-color` and `ui-link-color` are now present in the network request when the user is logged out. There's still a part where the user clicks logout, where the branding is still not applied, but that might be a UI problem.

The rest got fixed. Also this issue will need some testing.

**Comment by yonasberhe23** [comment]
e2e coverage is straight forward and looks sufficient to me. moving to Done @izaac
