### ISSUE TITLE
User is not shown failures when creating/editing configmap

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10794]
**Setup**
- Rancher version: 2.9 pre 2.9.0

**Describe the bug**
- If the request to create or edit a configmap fails the user sees a forever `Creating/Saving` button and is not informed of the issue
- This seems to only be the case for configmaps. I had a quick look at some others (persistent volume, secrets, pod, storage class) and they were fine

> We should check if this was a recent regression or also applies to 2.8

**To Reproduce**
- Cluster Explorer --> Storage --> ConfigMap --> Create --> Add `$^$^"£%` as a name --> Create

**Result**
- user is not informed of failure
 
**Expected Result**
- error banner showing description of error. note - there's an existing pattern to convert an error response to an on screen message

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/4437f6a2-1592-42bb-84cf-7b29ed40a58f)

**Comment by yonasberhe23** [comment]
e2e test coverage is sufficient. will move this to done as soon as the below is resolved. cc @izaac 

I'm seeing this bug in 2.8, should we backport this? cc @momesgin @richard-cox

**Comment by richard-cox** [comment]
In hindsight, just 2.9.0 will suffice
