### ISSUE TITLE
Incorrect number of resources in Overview page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1080]
**On master-head - commit id: `8a60de75d`**

- On the overview page - Number of Jobs seen is 4 and  Daemonsets is 2
- click on Job/Daemonsets, it results in 0 jobs/daemonsets
<img width="1182" alt="Screen Shot 2020-08-24 at 11 41 16 AM" src="https://user-images.githubusercontent.com/26032343/91088157-62342c00-e606-11ea-9739-c4725579de11.png">

**Comment by vincent99** [comment]
The overview page is for the entire cluster; the left side counts are filtered by the namespace filter in the header (which hides system namespaces by default, where the 4+2 resources are).

**Comment by sowmyav27** [comment]
Closing the issue as per this explanation - https://github.com/rancher/dashboard/issues/1080#issuecomment-679363438
