### ISSUE TITLE
Add "v25.0.x" option for "Docker Install URL" dropdown for RKE1

### ISSUE THREAD

**Issue by chiukapoor** [rancher/dashboard#10806]
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/rancher/rancher/issues/44459 we're adding support for Docker 25.0.x.

**Describe the solution you'd like**
UI dropdowns that allow picking "Docker Install URL" (e.g. on Node Template details page - not sure where else it may be referenced) should additional have "v25.0 (Recommended)" choice that populates `https://releases.rancher.com/install-docker/25.0.sh` when selected.

**Describe alternatives you've considered**
Note "Docker Install URL" is editable and doesn't limit users to only the choices available, so they can specify `https://releases.rancher.com/install-docker/25.0.sh` manually as well before this enhancement is done.
Consequently existing option "v24.0.x (Recommended)" should be changed to "v25.0.x".

![Screenshot from 2024-04-15 17-09-42](https://github.com/rancher/dashboard/assets/32087475/45c2844e-a06f-4333-b2a3-d861323e225e)

**Comment by gaktive** [comment]
@mitulshah-suse is this needed for 2.8.next1? We'll target 2.9.0 first but let us know if this is tied to additional backported work.

**Comment by mitulshah-suse** [comment]
@gaktive yes, its needed for 2.8-next1.

**Comment by cnotv** [comment]
For the records: the value is hardcoded in Ember.

**Comment by gaktive** [comment]
Found on RKE1 provisioning.

File: lib/shared/addon/components/form-engine-opts/component.js
Example from a past change: https://github.com/rancher/ui/pull/5045
