### ISSUE TITLE
Cluster count is incorrect when coming from a downstream cluster

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10803]
**Setup**
- Rancher version: 2.9.0 (pre-release)

**Describe the bug**
- When navigating to Cluster Management from a downstream cluster with a project/namespace filter applied, the Cluster count in the sidenav is incorrect

**To Reproduce**
- Nav to a downstream cluster
- Create a project 'junk'
- Select `junk` in the header filter
- Refresh the page
- Navigate to Cluster Management

**Result**
- The count of `Cluster`s in the sidenav is zero

**Expected Result**
- Should be non-zero (at least two...)

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/f2a2d003-46e5-4fda-903a-f09b13c57394)

**Additional context**

**Comment by IsaSih** [comment]
Tests pass on v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head
