### ISSUE TITLE
RKE2 Directory config: add support for new Cluster Spec `systemAgentVarDir`, `caprVarDir` and `dataDir` fields

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10824]
Depends on https://github.com/rancher/rancher/issues/45038

SURE-5886
RFC: 004 `Allow configuring RKE2/K3s data-dir on cluster create` (link in SURE)

**Is your feature request related to a problem? Please describe.**
- `CATTLE_AGENT_VAR_DIR` agent arg env var will now not be used to support setting the RKE2 data directory
- Instead the rkeSpec will have three new properties `systemAgentVarDir`, `caprVarDir`  and `dataDir`
- These properties can only be set on create and not edit of the cluster
- The UI needs to allow the user to set these

**Describe the solution you'd like**
- UX required, but three new input fields required in the rke2 create/edit form

**Comment by kwwii** [comment]
We should add one text field which allows a user to define the path to where Rancher will store all of it's data (meaning that Rancher should create 3 dirs within this directory to store the data). We will not allow the user to set all 3 directory paths in the UI

**Comment by richard-cox** [comment]
See https://github.com/rancher/rancher/issues/45157 for missing rkeConfig spec in schemaDefinition

**Comment by yonasberhe23** [comment]
unit tests do a good job of covering many scenarios tied to this feature but I think it would be a good idea to do some manual validation once the remaining backend code is implemented https://github.com/rancher/rancher/issues/45038. moving to 'To Test' 
cc @izaac

**Comment by gaktive** [comment]
Backend should have their portion of this soon.

**Comment by IsaSih** [comment]
Tests pass on v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head

Payload successfully sent for dataDirectories settings
