### ISSUE TITLE
Architecture column shows 'Mixed' when cluster is provisioning

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#10831]
**Setup**
- Rancher version: v2.9-head

**Describe the bug**

When a new cluster is provisioning, the nodes list is not available and the architecture sub-column shows 'Mixed'

**To Reproduce**

- Create a new RKE2 cluster
- Go to Cluster Management

**Result**

The Version/Architecture column contains 'Mixed'

**Expected Result**

It should be empty

**Screenshots**

![image](https://github.com/rancher/dashboard/assets/26394656/0dbf718d-18cc-4932-bf0e-3158daeafb78)

**Additional context**

**Comment by yonasberhe23** [comment]
the Architecture column shows 'Unknown' when provisioning a RKE1 cluster. Reopening this ticket for investigation


![Image](https://github.com/rancher/dashboard/assets/127343932/01a863dc-85b3-45df-8a75-2b000f49f7c1)

**Comment by torchiaf** [comment]
@yonasberhe23 I think the NODE_ARCHITECTURE label (`kubernetes.io/arch`) could be missing in RKE1 cluster's nodes 
https://github.com/rancher/dashboard/blob/17677f34993a5000524be01dba387053fc95f787/shell/models/provisioning.cattle.io.cluster.js#L411

I will take a look, thanks.

**Comment by yonasberhe23** [comment]
e2e and unit tests are sufficient. moving to done
