### ISSUE TITLE
Shell fails to open in a pod

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#10840]
Internal reference: SURE-8318

**Setup**
- Rancher version: v2.9-c9be13b09329bbee60a5f6419d500198f83c44d1-head
- Browser type & version: Google Chrome 123.0.6312.107 (Official Build) (arm64) and Safari 16.6

**Describe the bug**

Shell fails to open in a pod due to an unknown path` /bin/sh: no such file or directory: unknown`. According to the console logs, the error occurs in file `ContainerShell.vue:319`.

**To Reproduce**
1. Create a downstream cluster (in this example, it's a GKE cluster)
2. When the cluster is available, via UI, go to Workloads > Pods and click on the 3 dot button of any pod, then click on `Execute Shell` 
3. Observe the error message when the shell is open

**Result**
Shell fails to open in a pod due to an unknown path` /bin/sh: no such file or directory: unknown`

**Expected Result**
Shell should be open in a pod with no errors

**Screenshots**
<img width="1710" alt="Screenshot 2024-04-18 at 3 33 04 PM" src="https://github.com/rancher/dashboard/assets/70187881/726dd7a7-8639-462b-b229-97a06530a36c">
<img width="1587" alt="Screenshot 2024-04-12 at 1 48 51 AM" src="https://github.com/rancher/dashboard/assets/70187881/b4306fc3-e808-4c8a-ae74-427c21be595f">

**Comment by richard-cox** [comment]
I wonder if this is related to changing the underlying image to BCI? 

We should confirm if this is a bug in 2.7 and 2.8 as well

**Comment by gaktive** [comment]
Will file something for Mapps to figure out what we can do around new BCI behaviours. Ideally, the UI could detect that there is no shell and elegantly state there's nothing to shell into.

**Comment by gaktive** [comment]
@IsaSih when you get a moment, can you check the behaviour in 2.8.x? I don't know if we have to go back into 2.7.x at all but that may help if the problem existed somewhat earlier than 2.9.0

**Comment by IsaSih** [comment]
This issue does not occur in version 2.8-head. Tested on v2.8-94108186cf35028bb5f7db2c34c5ae99450dad9b-head
<img width="1720" alt="Screenshot 2024-04-25 at 10 13 43 AM" src="https://github.com/rancher/dashboard/assets/70187881/35940cba-95c3-4974-8f77-6cdb4fce687b">

**Comment by gaktive** [comment]
Internal reference with Mapps: SURE-8318
May have to monitor here as that team works on that in case it comes back to UI or QA

**Comment by nwmac** [comment]
We should re-validate that this is still an issue - I believe this is down to a change in base image which does not contain `sh` - I think this may have been fixed - we should validate.

Should also add an automated test for this.

**Comment by richard-cox** [comment]
Worked through this with Neil. 

The description shows pods with images not from Rancher, it looks like those just don't contain a shell so will never work.

I've brought up a new v2.9-head with the BCI change and can confirm some work
- alertmanager-rancher-monitoring-alertmanager-0, cattle-monitoring-system, docker.io/rancher/mirrored-prometheus-alertmanager:v0.26.0
- gitjob-7f85cd5774-4r429, cattle-fleet-system, rancher/fleet:v0.10.0-rc.13

and some don't
- capi-controller-manager-64b8d54977-c54w6, cattle-provisioning-capi-system, rancher/mirrored-cluster-api-controller:v1.4.4
- coredns-6799fbcd5-dzggt, kube-system, rancher/mirrored-coredns-coredns:1.10.1

I don't think this is a regression, but we need to make the error clearer. One is the root failure and one is from the UI. We can do this by adding a return after each error and maybe some before our error.

**Comment by gaktive** [comment]
Holding on backport for now until someone picks this up to see what a solution looks like.

**Comment by rak-phillip** [comment]
I updated to logging so that it's easier to parse when an error occurs, we'll also get some additional context when `/bin/sh` is missing from the container. 

@gaktive this will be a fairly easy change to backport, what should our targets be at this point?

**Comment by rak-phillip** [comment]
> @gaktive this will be a fairly easy change to backport, what should our targets be at this point?

Following up from my previous comment: we discussed backporting OOB and decided that there is no need to do so at this point.
