### ISSUE TITLE
[v2.9] Add "v26.0.x" option for "Docker Install URL" dropdown for RKE1

### ISSUE THREAD

**Issue by chiukapoor** [rancher/dashboard#10841]
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/rancher/rancher/issues/45013 we're adding support for Docker 26.0.x.

**Describe the solution you'd like**
UI dropdowns that allow picking "Docker Install URL" (e.g. on Node Template details page - not sure where else it may be referenced) should additional have "v26.0 (Recommended)" choice that populates `https://releases.rancher.com/install-docker/26.0.sh` when selected.

**Describe alternatives you've considered**
Note "Docker Install URL" is editable and doesn't limit users to only the choices available, so they can specify `https://releases.rancher.com/install-docker/26.0.sh` manually as well before this enhancement is done.
Consequently existing option "v25.0.x (Recommended)" should be changed to "v25.0.x".

## Additional Information

When a new version of the docker install is published, the UI will fetch that version and mark it as the default. Our role usually involves adding the previous version to the hard-coded list to serve as a cache.

See rancher/ui#5045 and rancher/ui#5136 for examples of how this has been previously handled.

**Comment by richard-cox** [comment]
@chiukapoor is this for 2.9.0, or afterwards?

**Comment by richard-cox** [comment]
Similar to https://github.com/rancher/dashboard/issues/10806

**Comment by chiukapoor** [comment]
> @chiukapoor is this for 2.9.0, or afterwards?
Yes, This is for v2.9.

**Comment by chiukapoor** [comment]
Note: It needs to be handled only after backend changes are in.

**Comment by rak-phillip** [comment]
@richard-cox @chiukapoor does this need to be represented in v2.8-next1 as well?

**Comment by mitulshah-suse** [comment]
@richard-cox backend related work is completed. It is not blocked on backed anymore.

**Comment by IsaSih** [comment]
test pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
