### ISSUE TITLE
[Istio v2]: Overview Page

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#1084]
### Section 1:
**External Links**
Need links to external endpoints for the following dashboards:
  - Kiali (will need icon )
  - Grafana  (will need icon) **Note, the backend for this will not be implemented till 2.5.x - hide or not implement until after the release
### Section 2: 
Need links to external documentation
 - https://istio.io/latest/docs/

Description: 
  ```
Rancher Istio helm chart installs a minimal Istio configuration for you to get started integrating with your applications. 
If you would like to get additional information about Istio, visit https://istio.io/latest/docs/concepts/what-is-istio/
```

CRD Explanations: 
```
In order to expose Istio configuration, the following Custom Resource Definitions (CRDs) have been made available:

- VirtualService (https://istio.io/latest/docs/reference/config/networking/virtual-service/)
- DestionationRule (https://istio.io/latest/docs/reference/config/networking/destination-rule/)
- Gateway (https://istio.io/latest/docs/reference/config/networking/gateway/)

The VirtualService is used for traffic routing, and can be bound to a Gateway or utilize a DestinationRule to set certain protocols and configuration for traffic. 

```
### Section 3: 
Display the following CRDs:
```
VirtualSerivce
DestinationRule
Gateway

```
Each should have their own table with the following columns:
```
name | namespace | hosts | created

```

**Comment by brendarearden** [comment]
https://rancher.atlassian.net/wiki/spaces/EN/pages/674234378/UI+Pages+-+Glossary+and+Templates#Templates-for-pages

**Comment by deniseschannon** [comment]
@brendarearden We need you to define what CRDs you would want to display. If it's a count, it's straightforward, but if it's a table, what info of the CRDs would you want displayed.

**Comment by brendarearden** [comment]
@deniseschannon I added specifics around what the table should display for each crds.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head c428bc9

* Kiali link is present, but not working as noted in https://github.com/rancher/dashboard/issues/1169
* Monitoring configuration and crd explanations are present
* VirtualService, DestinationRule, Gateway crd table is present with installed CRs
