### ISSUE TITLE
Ensure list header titles are vertically aligned the same

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10842]
- We now show subheader text in a couple of places
  - home page
  - cluster list
  - others?
- At the moment these are centrally aligned, meaning the headers appear above / below each other
  - ![image](https://github.com/rancher/dashboard/assets/18697775/35a12ec1-22be-4426-8794-ac4b1c8afe19)
  - ![image](https://github.com/rancher/dashboard/assets/18697775/5e667530-e4b4-4984-94de-5fc8b520dd59)
- These should be vertically algined
 - Something like
 - ![image](https://github.com/rancher/dashboard/assets/18697775/0d0fc551-a97c-4b49-b0ba-81da61c755e1)
 - The screenshot shows how this _might_ be done (adding vertical-align and padding-top to th) but has not been tested in other use cases of the table.

**Comment by richard-cox** [comment]
Only lists with sub-header labels should be top aligned

**Comment by IsaSih** [comment]
I'm seeing the vertical-align and padding-top are under top-aligned th, and not th itself. Should this suffice for the test to pass?

![Image](https://github.com/rancher/dashboard/assets/70187881/c62ca9d9-5cd5-4a1f-84e6-b074a62e74d4)

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
