### ISSUE TITLE
Partner Extensions are not downloaded into rancher

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#10868]
**Setup**
- Infra: HA 3 Linux node cluster RKE1 
- Rancher version: The issue occurs in both v2.8-head and 2.9-head
- Rancher UI Extensions: none
- Browser type & version: Version 123.0.6312.107 (Official Build) (arm64)

PS: **Rancher was deployed with "useBundledSystemChart=true"** 
This behavior also occurs when Rancher runs on a docker container.

**Describe the bug**

Once the user wants to install an extension, by going to the extensions catalog from the side menu, there are no available extensions.

By checking the extension repositories, we see that the `partner-extensions` repository fails to download as the process fails to get the SSL certificate. 
Also, from the UI, by clicking Apps > Chart, the UI renders the catalog with missing icons and when trying to install an extension (Elemental, for example), the shell prints logs of successful installation, though the console in devtools displays HTTP error 404.
 
**To Reproduce**

1- Deploy Rancher
2- From the UI, go to Apps > Repositories 
3- Verify the status of the `partners-extensions` 
4- From the UI, go to Apps > Charts
5- Observe the apps icon
6- From the side menu, go to extensions
7- Observe that non of them is listed for download

**Result**

The error displayed in the `partner-extensions` repo:
```
head failure: git clone --depth=1 -n --branch=main -- https://github.com/rancher/partner-extensions management-state/git-repo/partner-extensions/3ff55af926408daaca3b5bedc48d479d95cae4f43ade3df4a8c9dc7e65732db1 error: exit status 128, detail: Cloning into 'management-state/git-repo/partner-extensions/3ff55af926408daaca3b5bedc48d479d95cae4f43ade3df4a8c9dc7e65732db1'...
fatal: unable to access 'https://github.com/rancher/partner-extensions/': SSL certificate problem: unable to get local issuer certificate
```
How the UI renders the catalog from inside the cluster Apps > Charts:
<img width="1726" alt="Screenshot 2024-04-23 at 1 52 51 PM" src="https://github.com/rancher/dashboard/assets/70187881/0a6c39d8-0804-4bc2-b998-8a3b4aac36a8">

No extensions are available in the extensions menu 
<img width="1726" alt="Screenshot 2024-04-23 at 1 45 54 PM" src="https://github.com/rancher/dashboard/assets/70187881/a9ee976e-4e8a-49e8-a98f-2017c5724b05">

Screen recording shows the error when trying to install Elemental in the local cluster (error 404):
https://github.com/rancher/dashboard/assets/70187881/a48f98d2-a8e2-41ad-b88a-0d89b1307c8a

**Expected Result**

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment]
I've confirmed in a docker install, @IsaSih were you also using docker?

I'm checking with Mapps and eio, as this appears to be something their side

**Comment by IsaSih** [comment]
Yes, I tested on both HA cluster and docker

**Comment by richard-cox** [comment]
Linking SURE-8301

**Comment by IsaSih** [comment]
This is blocking the tests of issue [#10568](https://github.com/rancher/dashboard/issues/10568)

**Comment by richard-cox** [comment]
With `useBundledSystemChart=true` Rancher shouldn't go out to fetch charts. Might be worth including the full helm install/upgrade command in the description

**Comment by richard-cox** [comment]
Should now be resolved via a backend fix

**Comment by richard-cox** [comment]
We have added automated tests to ensure the UI shows the icons. These will catch any future issues the UI or backend has with them

**Comment by izaac** [comment]
Moving to Done. The E2E covers this scenario properly.
