### ISSUE TITLE
'View YAML' for an installed app for monitoring really slow

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10877]
Install monitoring.

Go to Apps -> Installed Apps -> 'rancher-monitoring -> View YAML

The page will hang the browser for a long time and will either crash the tab or will eventually load.

During this time, the tab is completely unresponsive.

**Comment by richard-cox** [comment]
Looking at the performance log it looks like Vue is re-rendering the codemirror component. That could be some kind of reactionary change (we're providing churn to a value we pass to it) or an issue with code mirror itself (though i don't think we've bumped the version in 2.9.0).

**Comment by rak-phillip** [comment]
I attempted to pinpoint a commit that might have introduced this performance regression, but I'm unable to reproduce while using v2.9-head `aacda46`. At least there's no noticeable delay or crashing in Firefox 127.0b8.

**Comment by nwmac** [comment]
I can no longer reproduce this either - it does take a while to paint, but does not crash any longer.

Moving to test for QA to validate as well.

**Comment by eva-vashkevich** [comment]
'View YAML' loads reasonably quickly. Cannot reproduce
Tested in Chrome Version 126.0.6478.127, Firefox 127.0.2, and Safari 16.5.2 (18615.2.9.11.10)

**Comment by eva-vashkevich** [comment]
If we think this might have been an issue with one of the dependencies, this might be a good argument to pin dependency versions.
