### ISSUE TITLE
Extensions are not available to install from Rancher UI

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#10884]
**Setup**
- Rancher version: 2.8-head and 2.9-head
- Rancher UI Extensions: none
- Browser type & version: Version 123.0.6312.107 (Official Build) (arm64)

**Describe the bug**
From the side menu bar, if a user tries to install an extension (elemental, for example) there are very few (v2.8) or no extensions at all (v2.9) available to install.

**To Reproduce**
1- Deploy Rancher
2- From the dashboard UI, click Extensions in the side menu bar
3- Observe the available extensions to install

**Result**
Rancher dashboard v2.8 displays only one extension available to install, whereas v2.9 does not display any of them. It's important to highlight that issue #10883 affects version 2.9 directly

**Expected Result**
All the extensions from the repositories and extensions catalog must be available to install via the UI
 
**Screenshots**

In 2.8-head:
<img width="1720" alt="Screenshot 2024-04-25 at 12 18 16 PM" src="https://github.com/rancher/dashboard/assets/70187881/b26508ab-d5f1-466d-902a-5d3ed5d0ca46">

In 2.9-head:
<img width="1720" alt="Screenshot 2024-04-25 at 12 27 57 PM" src="https://github.com/rancher/dashboard/assets/70187881/05941841-bbc1-4758-a16e-7b59dd05be7d">

**Comment by rak-phillip** [comment]
We have Elemental, Kamaji, Kubewarden, & NeuVector available in Rancher v2.8.2. I expect that this should remain unchanged moving forward

![available-extensions](https://github.com/rancher/dashboard/assets/835961/e02006ec-cc2e-4287-bc23-9732b3506fb4)

**Comment by richard-cox** [comment]
2.8-head - If it's not a prime install this is expected (more details available on request in slack)
2.9-head - Same, though there's none shown due to https://github.com/rancher/dashboard/issues/10868

**Comment by IsaSih** [comment]
So maybe we could add a banner in the UI informing that Rancher Prime offers a wider range of extensions, providing the user with an URL to sign up for Rancher Prime https://www.rancher.com/products/rancher-platform

**Comment by richard-cox** [comment]
Messaged in slack, closing
