### ISSUE TITLE
Edit Yaml page footer does not stick to bottom of page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10880]
**Setup**
- Rancher version: v2.9-head

**Describe the bug**
- See screenshot, the footer should be at bottom of page

**To Reproduce**
- Go to pod list
- Click on action menu for any
- Click on `Edit YAML`
- Collapse all sections in the yaml editor

**Result**
as per screen

**Expected Result**
as per other screenshot

**Screenshots**

### Bad
![image](https://github.com/rancher/dashboard/assets/18697775/dcc58209-336c-41dd-8d32-915e5d284ae7)

### Good
![image](https://github.com/rancher/dashboard/assets/18697775/4b88e968-245d-4a16-8cdf-c63792b06b37)

**Comment by nwmac** [comment]
@richard-cox Suggest we push this to 2.9.next1

**Comment by gaktive** [comment]
Happening in 2.8.5 & 2.9.3 still. Do check how it looks in 2.10.x

**Comment by momesgin** [comment]
Same in 2.10

**Comment by yonasberhe23** [comment]
created a follow-up [ticket](https://github.com/rancher/qa-tasks/issues/1621) to add e2e test for this scenario. moving to To Test

**Comment by yonasberhe23** [comment]
testing covered in https://github.com/rancher/dashboard/pull/12796
