### ISSUE TITLE
When you choose to customize project/cluster permissions, the UI reports an error when adding project/cluster members

### ISSUE THREAD

**Issue by ly5156** [rancher/dashboard#10894]
**Setup**
- Rancher version: v2.7.9-v2.8.3
- Rancher UI Extensions: v2.7.9-v2.8.3

**Describe the bug**

When you choose to customize project/cluseter permissions, the UI reports an error when adding project/cluster members, if Simplified Chinese is selected

**To Reproduce**

1. Switch UI language to Simplified Chinese: `Preferences -> languages-> 简体中文`

Add project members

2. Go to the `Projects/Namespaces`  page, and on the project  row，click on the `Edit Config` menu
3. On the member tab page, click the `Add` button
4. In the Project Permissions section, select `Custom` Option

Add cluster members

2. Go to the `Cluster and Project Members` page, and select `Cluster Membership` tab，click `Add` button
3. In the Cluster Permissions section, select `Custom` Option

**Result**
UI goes to error page or UI is not responding

**Expected Result**

Show project/cluster customization permission options

**Screenshots**

![test](https://github.com/rancher/dashboard/assets/3406205/b031dd46-cdd7-4d11-8809-790220ffef6d)
![test1](https://github.com/rancher/dashboard/assets/3406205/a3537b2a-52d4-4e65-bc8e-1248e5aa158c)

**Additional context**

**Comment by IsaSih** [comment]
No errors found in 
v2.10-61d79963733364046c6fc8e9003bd9d6948a6db0-head.
