### ISSUE TITLE
Font size of the top navigation bar is very small

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1090]
**On master-head - commit id: `56b819995`**

Font size of the top navigation bar is very small when compared to other text on the page
<img width="1680" alt="Screen Shot 2020-08-24 at 10 20 24 PM" src="https://user-images.githubusercontent.com/26032343/91126304-86b8f400-e658-11ea-9323-6e1d006801fa.png">

**Comment by deniseschannon** [comment]
Already covered in this issue: https://github.com/rancher/dashboard/issues/1044
