### ISSUE TITLE
Replace v-tooltip plugin with floating-vue

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#10902]
[v-tooltip](https://www.npmjs.com/package/v-tooltip/v/2.1.3?activeTab=readme) library has been replaced with [floating-vue](https://github.com/Akryum/floating-vue) for Vue3 and we should replace it before we migrate to simplify the process.

We should follow https://floating-vue.starpad.dev/migration/migration-from-v2 migration guide and move to [1.0.0-beta.19](https://www.npmjs.com/package/floating-vue/v/1.0.0-beta.19) for Vue2 compatibility.

**Comment by cnotv** [comment]
Existing commits to fix this issue
- app https://github.com/rancher/dashboard/commit/369d126c68f91d7f84838f1df394b9f4bdaac4dc
- unit tests https://github.com/cnotv/dashboard/commit/0e5e5c2fced3f5e0d7c3c7097ac757094e790ae8

**Comment by rak-phillip** [comment]
Closing this issue, the floating vue migration is already completed.
