### ISSUE TITLE
vGPU field is missing in the dashboard UI for rke1 cluster provisioning

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#10909]
**Setup**
Rancher version:v2.8-head
Rancher UI Extensions:
Browser type & version: Chrome
Version 124.0.6367.78
Harvester Version: v1.3.0

**Describe the bug**
By trying to provision a harvester rke1 cluster with vGPU Clusters Management in the UI, the Rancher dashboard does not display a vGPU field under the advanced settings as it does with rke2.

**To Reproduce**

1. Set up vGPU profiles in Harvester
2. Import Harvester into Rancher
3. From Cluster Management, Create a new 1-node RKE1 cluster with Harvester as the downstream provider. 
4. Under Advanced options, verify that there's no vGPU field to assign to the cluster

**Result**
The Rancher dashboard UI does not display a vGPU field under the advanced settings under clusters management

**Expected Result**
The Rancher dashboard must display a vGPU field under the advanced settings under clusters management

**Comment by gaktive** [comment]
This may be by design. Checking on Harvester & RKE1 together but UI does want to phase out Ember updates unless absolutely required.

**Comment by IsaSih** [comment]
After discussion, with the Harvester team, the vGPU feature won't be supported for rke1. However, we want to document that this feature will be available for rke2 only, and not rke1
