### ISSUE TITLE
Clusters Management UI does not display all vGPUs of the same profile

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#10908]
**Setup**
Rancher version:v2.8-head
Rancher UI Extensions:
Browser type & version: Chrome
Version 124.0.6367.78
Harvester Version: v1.3.0

**Describe the bug**
When you create a harvester cluster with vGPUs, only one of the vGPUs shows up in the list if you have more than one vGPU of the same profile enabled.
When you add another vGPU,  the list doesn’t show any other available options.

**To Reproduce**

1. Set up vGPU profiles (multiple) in Harvester
2. Import Harvester into Rancher
3. Go to Virtualization management -> Harvester UI for cluster -> vGPU Devices and enable 2 vGPUs of the same profile
4. From Cluster Management, Create a new 1-node RKE2 cluster with Harvester as the downstream provider. Under Advanced options, add the first vGPU on the list of available vGpus. Then, try to add the second one.
5. Observe the message displayed in the dropdown list

**Result**

![Greenshot 2024-04-29 15 34 53](https://github.com/rancher/dashboard/assets/70187881/86e1c924-7c15-4c5d-8851-af043d429803)
![Greenshot 2024-04-29 15 46 29](https://github.com/rancher/dashboard/assets/70187881/d0fd2273-68d1-43c2-848b-606f2ffa0ee9)

**Expected Result**
All vGPUs of the same profile must be displayed in the dropdown list and be added to the cluster when provisioning a harvester cluster via Clusters Management

**Additional Info**
You can manually associate 2 vGPUs of the same profile directly to the VM from the dashboard UI, in Harvester UI -> Virtual Machines -> Edit config -> vGPU devices, but not from Cluster Management when provisioning the cluster
![image](https://github.com/rancher/dashboard/assets/70187881/227e07b9-9c10-4c56-86e3-a7e382bdfd60)
![Greenshot 2024-04-29 15 46 33](https://github.com/rancher/dashboard/assets/70187881/cb2881cb-8883-4040-9b25-13e5455e0acc)

**Comment by noahgildersleeve** [comment]
Validated in Rancher `v2.8-862f57beb6ff7caeab6b4e3c00c89912050cf317-head` and Harvester v1.3.0.

**Comment by noahgildersleeve** [comment]
This was closed, but still needs to be validated in v2.9.

**Comment by noahgildersleeve** [comment]
Tested with Rancher v2.9.0-rc3 and Harvester v1.3.1. This seems to be working.
![Greenshot 2024-07-25 15 55 08](https://github.com/user-attachments/assets/af58c4b6-fbc7-46c3-bdec-42dc3b50ba03)
![Greenshot 2024-07-25 15 54 12](https://github.com/user-attachments/assets/0ffeaf00-5522-4bb6-8893-9c70998408e4)
Just be aware that [5774](https://github.com/harvester/harvester/issues/5774) is still open.
