### ISSUE TITLE
[backport v2.8.next1] If you assign a vGPU profile via node driver to a VM it doesn't show up in Harvester UI

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#10914]
This is a backport issue for https://github.com/rancher/dashboard/issues/10905.

Original body:

**Setup**
- Rancher version:v2.8-head
- Rancher UI Extensions:
- Browser type & version: Chrome
Version 124.0.6367.78 
Harvester Version: v1.3.0

**Describe the bug**

When you allocate a vGPU to a RKE2 cluster in Rancher with Harvester as the downstream provider the vGPU doesn't show up as assigned in the Harvester UI.
**To Reproduce**

1. Set up vGPU profiles in Harvester
2. Import Harvester into Rancher
4. Create a new 1 node RKE2 cluster with Harvester as downstream provider
5. Make the RKE2 cluster have one vGPU assigned to it
6. Wait for cluster to come up
7. Navigate to Harvester UI
8. Edit config for the VM and check if the vGPU shows up
**Result**

**Expected Result**

The vGPU should show up in the UI

**Screenshots**

![Greenshot 2024-04-29 17 10 04](https://github.com/rancher/dashboard/assets/83787952/2e581ae5-98bb-4c36-b7ff-d53a246306d9)

![Greenshot 2024-04-29 15 34 38](https://github.com/rancher/dashboard/assets/83787952/30911bfe-388d-46ee-9169-02218058fc51)

**Additional context**

Found while testing https://github.com/rancher/dashboard/pull/10833
The vGPU seems to be working on the VM, but it's not showing up in the UI. I think this might be related to how the vGPU is named. When it is added via the node driver it's just named `vgpu` in the YAML, but when it's added via the Harvester UI. It's hamed by the node and the pcideviceclaim.

![Greenshot 2024-04-29 15 47 35](https://github.com/rancher/dashboard/assets/83787952/8afa2e4a-f0fa-4dd5-8aaa-36c613451b9e)
![Greenshot 2024-04-29 15 46 44](https://github.com/rancher/dashboard/assets/83787952/433f8f2a-b19b-4439-acde-b91cc576356f)

**Comment by noahgildersleeve** [comment]
Validated in Rancher `v2.8-862f57beb6ff7caeab6b4e3c00c89912050cf317-head` and Harvester v1.3.0. However all of the vGPUs show as the same pcideviceclaim ID. I'm not sure it matters though.
