### ISSUE TITLE
rancher-logging - Error when configuring chart options with username and password

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1092]
Rancher version `master-head (08/25/2020)` _45e3e23cd_

- Dashboard -> Apps ->  Charts
- Click `rancher-logging` -> Chart Options

Cannot use 'in' operator to search for 'key' in testpassword

![Screen Shot 2020-08-25 at 10 27 42 AM](https://user-images.githubusercontent.com/27659/91207729-147afa80-e6be-11ea-926c-11f59500483b.png)

The password is displayed in the error message and also the error is preventing the chart theployment

**Comment by deniseschannon** [comment]
With the changes in chart deployment, this is no longer a valid use case.
