### ISSUE TITLE
UI changes to support built-in plugin operator 

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10939]
Related: SURE-6314

- Previously to manage extensions the ui-plugin-operator and ui-plugin-operator-crd charts needed to be installed
- Following https://github.com/rancher/rancher/pull/44230 these are now no longer required
- This affects how the UI sets up extension management

Initial appraisal ...  we need to....
1. update ui to handle initially installed and enabled operator, disabled via existing feature flag
    - At the moment the extension page checks for the operator service to determine if the charts should be installed... or can be uninstalled. The service no longer exists (shell/pages/c/_cluster/uiplugins/index.vue updateInstallStatus)
    - disabling the FF would be the same as uninstalling the charts. What does this mean for installed plugins?
1. update ui to notify and add extension catalogs (helm repos)
1. update tests given above
1. confirm that the existing method for air-gapped installs, used to bring in Rancher Extensions, still works

**Comment by jordojordo** [comment]
>disabling the FF would be the same as uninstalling the charts. What does this mean for installed plugins?
After some initial tests, installing an extension and then disabling the `uiextensions` feature flag will not remove the `uiplugin` resource that is tied to that extension. However, the extension will not be loaded into the dashboard.

Once the feature flag is re-enabled, the extension that was previously installed will load correctly. Should we be removing the uiplugin resources when disabling this flag?

As for the "built-in" extensions, these are retained within the dashboard regardless of the feature flag.

**Comment by richard-cox** [comment]
Linking https://github.com/rancher/dashboard/issues/10888

**Comment by izaac** [comment]
Coverage looks good to me. cc @yonasberhe23 closing
