### ISSUE TITLE
[v2.9] AKS: highest k8s version getting selected while editing cluster

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10949]
**Setup**
Rancher version: v2.9-6d87a11ea46b7571646d7c3d7af704584c39fd62-head
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Highest k8s version getting selected while editing cluster.

**To Reproduce**
- Provision AKS cluster from Rancher with version less than highest supported version
- After cluster becomes Active, edit cluster and check Kubernetes version field
- At this step, highest version is selected by default

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/42676717-1241-475a-bc43-ee01a5d4c982)

**Expected Result**
Current k8s version of cluster must be auto-selected while editing cluster, as in old UI.

**Comment by yonasberhe23** [comment]
unit tests are sufficient. moving to done cc @izaac
