### ISSUE TITLE
You can add two vGPUs for RKE2 node on Harvester even though they won't start

### ISSUE THREAD

**Issue by noahgildersleeve** [rancher/dashboard#10947]
**Setup**
- Rancher version: v2.8-head
- Rancher UI Extensions:
- Browser type & version: Chrome

**Describe the bug**

You can add two vGPU devices for a RKE2 Harvester cluster. They won't start due to the need for the [YAML ramFB fix](https://docs.harvesterhci.io/v1.3/advanced/vgpusupport/#limitations).
Also Rancher stays in starting state and doesn’t go into an error state. The fail state will keep looping since it’s not reporting back the error
**To Reproduce**

1. Create a new RKE2 cluster with Harvester as the provider
2. Add two vGPUs to the cluster
3. Create the cluster
4. Check the status of the VMs after creation
**Result**
The VMs won't start
**Expected Result**

There are few possible fixes
- The VMs should start and the second vGPU should have the ramFB fix
- The Add button should be disabled after adding a vPGU
- We could add a link to the 
**Screenshots**

![Greenshot 2024-05-03 17 55 22](https://github.com/rancher/dashboard/assets/83787952/09dea4db-1895-4c91-88d0-0b374aee4f5d)

**Additional context**

Currently this is allowed in the Harvester UI, but you have to do the YAML fix after creation, or possibly via YAML during creation.

**Comment by torchiaf** [comment]
We need to confirm that we don't have a unique key problem. I'm quite sure that it's just a label issue, where we should show the node id + profile id.
For the [YAML ramFB fix](https://docs.harvesterhci.io/v1.3/advanced/vgpusupport/#limitations) we should clarify what would be the logic to disable buttons.

**Comment by noahgildersleeve** [comment]
Something to be aware of is that if you go in and edit the YAML for the ramFB fix and the node driver ever updates the node it will overwrite the fix. This will happen every time the node is redeployed, such as for the node going into error, unresponsive, or other states. Also when you change the count.
