### ISSUE TITLE
Support SAML Single Logout (SLO)

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10941]
SURE-3572

- Users currently only log out from local auth, or in the case of SSO external auth providers just clear local content and direct the user back to log in page... they are not signed out of the external auth provider. 
- Some customers have requested that Logging out of rancher should also log them out of the external auth provider
- This only makes sense for some auth providers, and in a limited way
- Linked SURE details how this should work, but briefly
  - Should be configurable (admins can enable / disable)
  - Can be optional (admins can choose to force it, or allow both types of logout)

**Comment by cnotv** [comment]
FYI we do not have logout tests with credentials

**Comment by gaktive** [comment]
@richard-cox with what else is on your 2.9.0 plate, is this something that @aalves08 can pick up?

**Comment by richard-cox** [comment]
Happy to hand over and offer guidance if needed

**Comment by aalves08** [comment]
@rancher/docs the documentation for rancher manager will need updating in regards to how they should configure the Single Logout on each of the SAML providers. Ex: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-okta-saml

Final UX will be coming soon (PR https://github.com/rancher/dashboard/pull/11182 is still WIP)

**Comment by sunilarjun** [comment]
Hello @aalves08, I have created a docs issue for this and any docs related questions or comments can be directed there. Thank you!

**Comment by richard-cox** [comment]
@gaktive I've moved this to backend blocked given an issue we see with Okta.

@andreas-kupries has confirmed his backend changes and our frontend changes work with Keycloack SAML however there's an issue he's following up with when using okta. In theory we could merge our side however it would be good to validate changes in okta and a bit of dev testing ourside as well

**Comment by gaktive** [comment]
Backend won't be able to complete this in time for 2.9.0 so pushing to 2.10.0

**Comment by nwmac** [comment]
Backend is now done - we need to test/validate these UI changes with the new backend.

**Comment by yonasberhe23** [comment]
Testing complete in:

- Rancher v2.10-e615207c8cd924c092b55a9301e7378878706d19-head
- Dashboard master 78df731

Conducted tests with Okta and Ping (saml) auth providers

Auth Provider | User | Test Case | Result
| --- | --- | --- | --- | 
Okta | Admin | Regular logout flow | ✅
Okta | Admin | SLO: Logout of Rancher and NOT auth provider | ✅
Okta | Admin | SLO: Logout of Rancher and auth provider | ✅
Okta | Admin | SLO: Allow user to choose which to logout from | ✅
Okta | Standard | SLO: Logout of Rancher and NOT auth provider | ✅
Okta | Standard | SLO: Logout of Rancher and auth provider | ✅
Okta | Standard | SLO: Allow user to choose which to logout from | ✅
Okta | Admin/Standard | SLO: Correct login page message displays per log-out method | ✅
Ping | Admin | SLO: Logout of Rancher and NOT auth provider | ✅
Ping | Admin | SLO: Logout of Rancher and auth provider | ✅
Ping | Admin | SLO: Allow user to choose which to logout from | ✅
Ping | Standard | SLO: Logout of Rancher and NOT auth provider | ✅
Ping | Standard | SLO: Logout of Rancher and auth provider | ✅
Ping | Standard | SLO: Allow user to choose which to logout from | ✅
Ping | Admin/Standard | SLO: Correct login page message displays per log-out method | ✅
-- | Admin/Standard | Regular logout flow | ✅
