### ISSUE TITLE
[v2.9] AKS: Labels/Taints not visible for Nodepool 

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10952]
**Setup**
Rancher version: `v2.9-6d87a11ea46b7571646d7c3d7af704584c39fd62-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Labels/Taints not visible for Nodepool 

**To Reproduce**
- Provision AKS cluster from Rancher UI
- For Nodepool, add labels/taints while provisioning
- Wait for Cluster to become Active

API payload sent:
```
    "nodePools": [
      {
        "availabilityZones": [
          "1",
          "2",
          "3"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "maxSurge": "1",
        "mode": "System",
        "name": "agentpool",
        "nodeLabels": {
          
        },
        "nodeTaints": [
          "k1=v1:PreferNoSchedule"
        ],
        "orchestratorVersion": "",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "vmSize": "Standard_DS2_v2",
        "labels": {
          "k2": "v2"
        }
      }
    ],
```

**Screenshots**
After cluster is provisioned:
![image](https://github.com/rancher/dashboard/assets/73099870/ea459095-9a01-43f0-8f90-c312506d6179)

**Expected Result**
Labels/Taints for Nodepool must be visible on UI

**Comment by yonasberhe23** [comment]
`Taints` are preserved but not `Labels` when editing an AKS cluster during or after provisioning. Please see the recording. Reopening for further investigation

https://github.com/rancher/dashboard/assets/127343932/b0363594-567f-48f8-8cab-a118141371b1

**Comment by yonasberhe23** [comment]
Working as expected in `v2.9-f188faae847b960d2f30cc89f4befc8ce5944f2c-head`. 
unit tests are sufficient. moving to done

thank you @mantis-toboggan-md!
