### ISSUE TITLE
Missing Notifier option under Cluster tools 

### ISSUE THREAD

**Issue by Rashimpdi** [rancher/dashboard#10953]
I was looking in the documentation about adding the notifier but couldnt find it under Cluster tools as per following documentation:
https://ranchermanager.docs.rancher.com/v2.0-v2.4/explanations/integrations-in-rancher/notifiers

We are using v2.7 and in the latest documentation there is no mention about the steps to add notifiers.
https://ranchermanager.docs.rancher.com/reference-guides/rancher-project-tools#notifiers-and-alerts

Also there is no way to add notifiers in the latest version

**Comment by richard-cox** [comment]
From 2.5 the new Rancher UI was made default. Documentation regarding the UI pre 2.5 refers to the old UI.

Notifiers are part of the [logging](https://ranchermanager.docs.rancher.com/integrations-in-rancher/logging) process, in the new UI they can be found after installing that app and going to the `Logging` section on the target cluster

**Comment by Rashimpdi** [comment]
Can we add Slack as notifier in version 2.7? Where can I find the documentation?
