### ISSUE TITLE
Apps - logs gets overwritten in the logs window and experience High CPU usage when deploying an App from Dashboard

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1095]
When deploying an App from Dashboard a tab window open at the bottom of the browser window displaying the helm operation logs.

While the deployment takes place if the logging returned by helm is too verbose then the logs start getting render overwriting the previous output and making the output all scrambled and not possible to read.

![Screen Shot 2020-08-25 at 11 22 34 AM](https://user-images.githubusercontent.com/27659/91213297-39736b80-e6c6-11ea-82a8-d7a0975e0b7e.png)

And then the browser gets slow and checking the OS CPU usage there are spikes of coming form the browser.

Browser is Chrome based.

Rancher version `master-head (08/25/2020)` _45e3e23cd_

**Comment by deniseschannon** [comment]
It looks like this console is now being hidden during deployment. So sending it to test.

**Comment by izaac** [comment]
Rancher version: `master-head (09/21/2020)` _f1a410a_

Validated in the latest master and on previous builds log overlapping and slowness is not reproducible.
I see the logging console getting opened each time I click install on each app. 

Tested with a couple of different charts `rancher-logging` `rancher-monitoring` on Chrome based browser Edge 85.0.564.60
