### ISSUE TITLE
[v2.9] AKS: Unable to change Nodepool mode

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10960]
**Setup**
Rancher version: v2.9-6d87a11ea46b7571646d7c3d7af704584c39fd62-head
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Unable to change Nodepool mode, from System to User and vice-versa.

**To Reproduce**
- Provision AKS cluster from Rancher UI with two Nodepools and different modes

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/86dba294-4ca5-44a3-b8b3-7e4c532da345)

**Expected Result**
User must be able to change Nodepool mode, as in old UI.

**Comment by izaac** [comment]
I am moving to done as the Hosted clusters automation is still on the backlog and is not clear if some other team owns it cc @yonasberhe23 

Unit test is enough in this case.
