### ISSUE TITLE
Logging Output Buffer shows schema loading error

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#10961]
**Setup**
- Rancher version: pre 2.9.0

**Describe the bug**
See screenshot

**To Reproduce**
- Install Logging chart
- Navigate to Logging --> Outputs --> Create --> Output Buffer tab

**Result**
- Code editor shows error

**Expected Result**
- no error, and i'm assuming yaml from a schema

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/02532a6f-8fc6-4e62-b365-7b29f399b0dd)

**Additional context**
- most probably related to schema diet changes

**Comment by richard-cox** [comment]
should be tested as part of https://github.com/rancher/dashboard/issues/7716

**Comment by nwmac** [comment]
@IsaSih You moved this to Working - did you mean QA Working? PR was merged. I am going to move back to 'To Test'.

**Comment by caliskanugur** [comment]
<img width="2485" alt="Screenshot 2024-07-10 at 3 43 53 PM" src="https://github.com/rancher/dashboard/assets/40526929/bf0fcb5a-c164-4cdc-8c63-5a52f534de79">

**Setup**

- Rancher version : v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head
- Dashboard version: master 30d8ecc

**Result:**

  No error
