### ISSUE TITLE
[v2.9] AKS: Configuring Container Monitoring not working

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10965]
**Setup**
Rancher version: `v2.9-6d87a11ea46b7571646d7c3d7af704584c39fd62-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Configuring Container Monitoring not working while provisioning cluster

**To Reproduce**
Provision AKS cluster from Rancher UI with "Configure Container Monitoring" checkbox enabled

AKSSpec has `monitoring: null` value after Cluster becomes Active.

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/2f1d291b-ccb4-40d7-96f1-cb8d4723dc93)

**Comment by izaac** [comment]
I am moving to done as the Hosted clusters automation is still on the backlog and is not clear if some other team owns it cc @yonasberhe23 

Unit test is enough in this case.
