### ISSUE TITLE
[v2.9] AKS: Nodepool values validation

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#10963]
**Setup**
Rancher version: `v2.9-6d87a11ea46b7571646d7c3d7af704584c39fd62-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): 
Nodepool values on UI like Count, Max surge need validation for nil, 0 value, as in old UI

**To Reproduce**
Provision AKS cluster from Rancher UI with Nodepool count 0 and max surge empty

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/c461d9bf-a886-4ac4-a8fe-e85370275864)

**Comment by izaac** [comment]
I am moving to done as the Hosted clusters automation is still on the backlog and is not clear if some other team owns it cc @yonasberhe23 

Unit test is enough in this case.
