### ISSUE TITLE
Questions.yml support - Round 2

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1097]
Validation of every field

Missing implemented 
StorageClass
Secret
PVC

**Comment by vincent99** [comment]
There's no validation still, which would be part of a more general issue for validating forms in general, but configmap/secret/storageclass/pvc are supported now, as well as `reference[any-type-name]` (see https://github.com/rancher/dashboard/issues/3304#issuecomment-866563842)

**Comment by slickwarren** [comment]
Did a preliminary check on master-head (3499046):
* updated type from `string` to `secret` in [v5 of my cluster templates](https://github.com/slickwarren/cluster-template-examples/blob/fleet-template/qa-v2charts-template-0.0.5.tgz) questions.yaml -> secrets now populate in the updated field
<img width="686" alt="Screen Shot 2021-08-02 at 3 50 50 PM" src="https://user-images.githubusercontent.com/16691014/127934129-29c7bc02-6da4-4ee6-acc1-90dbb48778d1.png">

* search function works in the secret field

**Comment by vincent99** [comment]
The questions were meant for regular catalog templates so they look at the 'selected' cluster, where they work fine.  But there is none if you're a non-admin user and aren't 'in' the local cluster while trying to use it for a cluster template.  It needs to look for them in the management cluster for cluster templates.

**Comment by slickwarren** [comment]
oh I see, you're right @vincent99 I was logged in as non-admin user. These do work as expected when the user is logged in as admin for rke2 templates.

**Comment by vincent99** [comment]
Changed to look in management cluster for cluster templates.  You probably still won't have permission to list ConfigMaps or PVCs in this situation, these questions would be better tested as a regular chart than a cluster template.

But I made it show a text box and an error instead of showing no input at all so you can still maybe use it if you knew what to type in.

**Comment by slickwarren** [comment]
on 2.6.1-rc7 using a [testing helm repo](https://github.com/slickwarren/helm-charts):
* secrets, pvc, storageclass, and configmap are all populating appropriately
<img width="863" alt="Screen Shot 2021-09-29 at 9 18 50 PM" src="https://user-images.githubusercontent.com/16691014/135386527-67ec2062-4fc0-4b8b-aaa4-7c2968f32803.png">
