### ISSUE TITLE
Update user labels

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#10978]
Given the Users List & User Details pages, the Disabled/Deleted fields should read "Disable After"/"Delete After", so that the fields better communicate what will happen after the duration has passed.

## Additional Context

The current labels of "Disabled In"/"Deleted In" give the impression that these hooks might trigger immediately when the duration is up. This is not the case, and updating the labels better communicates this behavior.

**Comment by IsaSih** [comment]
Tests pass on v2.8.4-rc5-s4
