### ISSUE TITLE
Add warning banner to allocate the number of nodes + 1 vGPUs

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#10989]
**Setup**
Rancher version:v2.8-head
Browser type & version: Chrome Version 124.0.6367.78
Harvester Version: v1.3.0

To Reproduce

1. Set up vGPU profiles (multiple) in Harvester
2. Import Harvester into Rancher
3. Go to Virtualization management -> Harvester UI for cluster -> vGPU Devices and enable a vGPU with 2 allocatable.
4. From Cluster Management, Create a new 2-node RKE2 cluster with Harvester as the downstream provider. Under Advanced options, add the vGPU with 2 allocatable resources ( same number as the cluster nodes)
5. After the creation of the cluster is completed, edit the config file of the cluster
6. Observe the logs of the failed process of provisioning. 

**Result**
Once the harvester cluster is redeployed for any reason (the user edits the config, the nodes go into an error state, etc), the new VMs spin up before the old ones are completely shut down, which causes the "un-schedulable" error as the vGPUs won't be available yet.

**Expected Result**
We could add a warning banner in the UI to recommend that the user should provision N+1 allocatable vgpu, where N is number of nodes.

**Comment by gaktive** [comment]
This isn't a blocker for the release but we'll need to release note this in Harvester and see if we can fix this later.

Moving to 2.9.0 but this may need a 2.8.x backport.

**Comment by LucasSaintarbor** [comment]
> This isn't a blocker for the release but we'll need to release note this in Harvester and see if we can fix this later.
> 
> Moving to 2.9.0 but this may need a 2.8.x backport.

@gaktive Should a release note be added to the Rancher 2.8.4 RNs? If so, should this be considered a known issue?

**Comment by gaktive** [comment]
@LucasSaintarbor I'd say it's a known issue but it impacts Harvester more so this may have to target their release notes instead. 

@rebeccazzzz is there a historical pattern for release notes in Rancher that tie to Harvester directly?

**Comment by gaktive** [comment]
Candidate for backport to 2.9.x.

**Comment by khushboo-rancher** [comment]
Reopening for the validation

**Comment by noahgildersleeve** [comment]
Tested with Harvester v1.4.0-rc2 with Rancher versions

- v2.8-68e5d43e449fcd3ef73baf1caee98da6f0104eed-head
![Greenshot 2024-10-09 17 47 34](https://github.com/user-attachments/assets/e60d594d-0f23-4b0d-bde6-8caec0d0cff6)
![Greenshot 2024-10-09 17 46 08](https://github.com/user-attachments/assets/62da3e9b-f926-41fd-bbc9-69e034501f8c)
![Greenshot 2024-10-09 17 45 47](https://github.com/user-attachments/assets/52e52c73-3bec-43e1-bdb6-a4306258e621)
![Greenshot 2024-10-09 17 45 39](https://github.com/user-attachments/assets/e2bb36e4-0e67-4bb5-9656-18b039114f0b)

- v2.9-af2463ff43418024ff86cfd9304836b7074a924a-head
![Greenshot 2024-10-09 18 04 22](https://github.com/user-attachments/assets/2327197a-d63f-456f-8cdd-dd7e7007daae)
![Greenshot 2024-10-09 18 04 18](https://github.com/user-attachments/assets/9eba035b-54a9-4669-9a15-089fc3c5e101)
![Greenshot 2024-10-09 18 03 48](https://github.com/user-attachments/assets/cf3b5ec5-c2c0-4182-b7fd-328f42498495)

- v2.10-fe30db77dab22d42b769c9d88d9410a8044c4066-head
![Greenshot 2024-10-09 20 21 08](https://github.com/user-attachments/assets/3f8d5a0a-80e1-49e8-a4f3-8857bfd3098c)
![Greenshot 2024-10-09 20 20 29](https://github.com/user-attachments/assets/d37edea5-7434-4466-82d9-1bd1c0a8dce7)
![Greenshot 2024-10-09 20 20 12](https://github.com/user-attachments/assets/7e586bdf-c2be-4448-8df1-298ba3f2ec42)
![Greenshot 2024-10-09 19 49 03](https://github.com/user-attachments/assets/a03648e5-bc13-40ef-834d-1bfa8f1256b8)
![Greenshot 2024-10-09 19 48 38](https://github.com/user-attachments/assets/7f834849-68a5-47e5-ab01-f16e88d1797f)
![Greenshot 2024-10-09 19 48 32](https://github.com/user-attachments/assets/3006a98a-ea51-4db2-b8f7-c97e4bd3fc7c)
