### ISSUE TITLE
[v2.9] Add "v26.1.x" option for "Docker Install URL" dropdown for RKE1

### ISSUE THREAD

**Issue by chiukapoor** [rancher/dashboard#10996]
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/rancher/rancher/issues/45439 we're adding support for Docker 26.1.x.

**Describe the solution you'd like**
UI dropdowns that allow picking "Docker Install URL" (e.g. on Node Template details page - not sure where else it may be referenced) should additionally have a "v26.1 (Recommended)" choice that populates `https://releases.rancher.com/install-docker/26.1.sh` when selected.

**Describe alternatives you've considered**
Note that the "Docker Install URL" is editable and doesn't limit users to only the available choices, so they can specify `https://releases.rancher.com/install-docker/26.1.sh` manually before this enhancement is done.
Consequently, the existing option "v26.0.x (Recommended)" should be changed to "v26.0.x".

## Additional Information

When a new version of the docker install is published, the UI will fetch that version and mark it as the default. Our role usually involves adding the previous version to the hard-coded list to serve as a cache.

See rancher/ui#5045 and rancher/ui#5136 for examples of how this has been previously handled.

**Comment by chiukapoor** [comment]
@richard-cox backend related work is in progress, [PR](https://github.com/rancher/rancher/pull/45632). This issue is not blocked on back-end anymore.

**Comment by nwmac** [comment]
@gaktive This got moved into the 2.9 milestone yesterday - FYI - will need to discuss.

**Comment by nwmac** [comment]
@chiukapoor Is the ask really to add v26.1 and keep v26.0 ?

We don't currently show more than one of a given major version, so I think we should be replacing v26.0 with v26.1 - can you confirm please.

**Comment by nwmac** [comment]
PR assuming a swap out: https://github.com/rancher/ui/pull/5147

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head

**Comment by snasovich** [comment]
> @chiukapoor Is the ask really to add v26.1 and keep v26.0 ?
> 
> We don't currently show more than one of a given major version, so I think we should be replacing v26.0 with v26.1 - can you confirm please.

@nwmac , is there a hard limitation to replace 26.0.x with 26.1.x?
FWIW we have precedent of having multiple minor versions with both `v18.09.x` and `v18.06.x`. Screenshot from 2.8-head:
![image](https://github.com/rancher/dashboard/assets/85187633/45423894-48fe-464a-858d-15954b54fefe)

TBH I'm not exactly sure why Docker started 26.1 while 26.0 was still pretty new but ideally I think we want our dropdown to mimic what is on https://docs.docker.com/engine/release-notes for non-ancient versions and they do list 26.0 separate from 26.1:
<img width="285" alt="image" src="https://github.com/rancher/dashboard/assets/85187633/fa430f31-7356-4824-8e10-d325ec3943d4">

So if there are no hard limitations ideally we would like to have both 26.1 and 26.0 show up in the list with the latest (26.1) being the default.

Reopening this issue for visibility.

FYI @IsaSih @mitulshah-suse

**Comment by IsaSih** [comment]
2.9-head displays both versions. However, the default is 26.0, not 26.1

![Image](https://github.com/rancher/dashboard/assets/70187881/53ce2c7c-6f14-4ad1-920d-ad2f3e3f4be6)

**Comment by snasovich** [comment]
@IsaSih , I saw https://github.com/rancher/ui/pull/5147 which replaced v26.0.x with v26.1.x and matched conversations in this issue. Not sure why both are displayed - there might have been a follow up PR.
I'm hoping we can change the default as part of this issue as it's essentially requested per the original issue's description.

**Comment by nwmac** [comment]
Note - UI has added 26.0.x to the list for completeness - the default option is provided by backend, so if that is the remaining issue here, I think we should close the UI side as done and re-open the backend work to cover the default option work required.

**Comment by IsaSih** [comment]
Created backend ticket https://github.com/rancher/rancher/issues/46020
