### ISSUE TITLE
rancher extension ui

### ISSUE THREAD

**Issue by guozijing** [rancher/dashboard#10999]
I want to test the ui extension as the user guide https://rancher.github.io/dashboard/extensions/extensions-getting-started,

When run the command 
yarn create @rancher/pkg test

Following error is shown:

yarn create v1.22.22
warning package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "@rancher/create-pkg@0.5.3" with binaries:
      - create-pkg
[########] 8/8
Creating Skeleton UI Package
  Creating package folder: /root/my-app/pkg/test
  Creating package.json
  Adding script 'dev' to package.json
  Adding script 'nuxt' to package.json
  Fetching latest Rancher Version
  Adding file: tsconfig.json
  Adding file: vue.config.js
  Adding file: babel.config.js
  Adding file: index.ts
  Adding script 'build-pkg' to top-level package.json
  Adding script 'serve-pkgs' to top-level package.json
  Adding script 'publish-pkgs' to top-level package.json
  Adding script 'parse-tag-name' to top-level package.json

  **Error fetching latest Rancher Version Error: connect ETIMEDOUT 20.205.243.168:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '20.205.243.168',
  port: 443
}**
Done in 131.90s.

Can anyone help me? thanks a lot

**Comment by richard-cox** [comment]
I've just gone through the steps from our guide and they complete locally ok

```
yarn create @rancher/app my-app
cd my-app/
yarn install
yarn create @rancher/pkg test
```

The error provided suggests your local machine is unable to contact `https://api.github.com/repos/rancher/rancher/releases/latest`. Can you confirm it can reach there in a browser?

**Comment by guozijing** [comment]
Thanks for your reply, my server is behind proxy,
when using curl to test, I can access api.github.com
```
# curl https://api.github.com/repos/rancher/rancher/releases/latest -I
HTTP/1.1 200 Connection established

HTTP/2 200
server: GitHub.com
date: Fri, 10 May 2024 12:34:39 GMT
content-type: application/json; charset=utf-8
cache-control: public, max-age=60, s-maxage=60
vary: Accept, Accept-Encoding, Accept, X-Requested-With
etag: W/"02e6aea8347a07d5901af1abe047e8a0a5edaea3eac363f53747f67c9c9220fb"
last-modified: Thu, 28 Mar 2024 19:00:00 GMT
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
x-ratelimit-limit: 60
x-ratelimit-remaining: 44
x-ratelimit-reset: 1715345984
x-ratelimit-resource: core
x-ratelimit-used: 16
accept-ranges: bytes
x-github-request-id: BCDC:314CBF:10BC2371:10D44ADE:663E145E
```

yarn create also have problem...

**Comment by richard-cox** [comment]
I think the issue revolves around the proxy used by https://github.com/rancher/dashboard/blob/master/shell/creators/pkg/init#L98. I'll discuss with the team

As a workaround you might be able to manually specify a proxy in `.config/yarn/global/node_modules/@rancher/create-pkg/init`  `const options = { headers: { 'User-Agent': 'nodejs' } };`,

**Comment by guozijing** [comment]
yeah, I try add a proxy by 
const options = {
          host: "http://...",
          port: 913,
          headers: { 'User-Agent': 'nodejs' } };

But when I re-run the yarn create, the package is refresh, how can i disable the refresh?
Thanks

**Comment by guozijing** [comment]
Thanks Richard,

I modified the file by the following:
```
function fetchLatestVersion() {
  console.log('  Fetching latest Rancher Version');
  const options = { headers: { 'User-Agent': 'nodejs' } };

  var connectReq = http.request({
    host: "",
    port: ,
    method: 'CONNECT',
    path: 'api.github.com:443',
  }).on('connect', function(res, socket, head){
    var req = https.get({
        hostname: 'api.github.com',
        path: '/repos/rancher/rancher/releases/latest',
        socket: socket,
        agent: false,
        headers: { 'User-Agent': 'nodejs' },
    }, (res) => {
        const { statusCode } = res;
        const contentType = res.headers['content-type'];

        let error;

        if ( statusCode !== 200 ) {
            error = new Error('  Request Failed.\n' +
                            `  Status Code: ${ statusCode }`);
        } else if ( !/^application\/json/.test(contentType) ) {
            error = new Error('  Invalid content-type.\n' +
                            `  Expected application/json but received ${ contentType }`);
        }

        if ( error ) {
            console.log(error.message);

            res.resume();

            return;
        }

        res.setEncoding('utf8');
        let rawData = '';

        res.on('data', (chunk) => {
            rawData += chunk;
        });
        res.on('end', () => {
            try {
                const release = JSON.parse(rawData);

                if ( release.tag_name ) {
                console.log(`  Adding rancher-version annotation '>= ${ release.tag_name }' to package.json`);

                pkg.rancher = { annotations: { 'catalog.cattle.io/rancher-version': `>= ${ release.tag_name }` } };
                writePackageJson();
                }
            } catch (e) {
                console.log('  Error parsing release data', e);
            }
        });
    }).on('error', (e) => {
        console.log('  Error fetching latest Rancher Version', e);
    });
  }).end();
}
```

it works.

**Comment by guozijing** [comment]
By the way, as the document said, 
```
Go to the three dot menu and select 'Developer load' - you'll get a dialog allowing you to load the extension into the UI.
In the top input box Extension URL, enter:
https://127.0.0.1:8005/pkg/test-0.1.0/test-0.1.0.umd.min.js
```

Is the url is right? when I use curl to have the test, can not get the scripts right.
If i use http://127.0.0.1:4500/test-0.1.0/test-0.1.0.umd.min.js, the browser reject to use the http protocol when the web is https.

Thanks.

**Comment by richard-cox** [comment]
You'll need to server up the new pkg by running something like `yarn server-pkgs`. That will output the urls which are specific to each pkg and it's name. That url should be the one to use in Rancher when doing a developer load

**Comment by guozijing** [comment]
> You'll need to server up the new pkg by running something like `yarn server-pkgs`. That will output the urls which are specific to each pkg and it's name. That url should be the one to use in Rancher when doing a developer load

yeah, but there are two problems here:
1. the serve address is 127.0.0.1, I modify the scripts to 0.0.0.0
2. the serve-pkgs is http, not https, which can not loaded by https (web browser denied)

But finally I can deploy the test-app from a git repo, thanks a lot, Richard.
This issue can be closed.
