### ISSUE TITLE
Missing most Cluster Tools

### ISSUE THREAD

**Issue by herrbpl** [rancher/dashboard#11019]
I just noticed that I cannot update/install Cluster Tools for Rancher 2.7.9 cluster anymore, there just are no more logging or monitoring Apps. 

Only cluster tools available are:
![image](https://github.com/rancher/dashboard/assets/2135514/fad902e5-fe9a-4558-8416-cde588fe8766)

All my clusters are affected so I guess something has changed in https://git.rancher.io/ ? Unable to find anything related to it

**Comment by richard-cox** [comment]
Can you confirm that's the `URL` for the `Rancher` `Apps` / `Repositories` entry? What's the branch name?

![image](https://github.com/rancher/dashboard/assets/18697775/fc59e8bf-05e1-48ae-a7fa-d7a0035530d0)

**Comment by herrbpl** [comment]
url is correct.

Branch is release-v2.7

**Comment by richard-cox** [comment]
For `https://git.rancher.io/charts` with `release-v2.7`, looking at an example of the CIS Benchmark chart it has the following restrictions

```
catalog.cattle.io/permits-os: "linux,windows"
catalog.cattle.io/kube-version: ">= 1.21.0-0 < 1.27.0-0"
catalog.cattle.io/rancher-version: ">= 2.7.0-0 < 2.8.0-0"
```

Can you double check all of those are fine?

If you open up the browser's dev tools and refresh on the Cluster Tool page can you check that the response to `/v1/catalog.cattle.io.clusterrepos/rancher-charts?link=index` contains charts in `entries` for more than you're seeing?

**Comment by richard-cox** [comment]
The maximum kube version supported by v2.7.9 is 1.26 (https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-9/), 1.28 support came in v2.8.3. Those would not have changed since the versions were released.

**Comment by herrbpl** [comment]
should it not be version of kube you can install rancher on, not clusters it can operate?

**Comment by herrbpl** [comment]
I understand point of having certified support versions oh k8s for rancher cluster apps but not actually hiding them from user if k8s version is greater.. 

Super confusing unless you actually know reason…

**Comment by richard-cox** [comment]
The kube version limitations cover both the upstream and downstream clusters.

I think there's scope though to show a warning in the UI if either limitation is exceeded. That would be a separate issue though if you'd like to create one.
