### ISSUE TITLE
[Logging V2] ClusterOuptut CRD Page

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1102]
Overview Page
This tab should just contain a description of what an output is.  @paynejacob will write this section and attach it to this ticket.
CRD Docs
This is the base of the CRD: https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/output_types/
This is the full CRD, it is a superset of the above CRD: https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/clusteroutput_types/
Mockup
![Cluster Output](https://user-images.githubusercontent.com/12258347/91073390-d7e0cd80-e5ef-11ea-98a7-926897c515c7.png)
The ... should be replaced with a tab for each output destination found here: https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/output_types/

**Comment by paynejacob** [comment]
Overview Text: "A cluster output is where logs can be delivered for all of the cluster."

**Comment by codyrancher** [comment]
@paynejacob I have a couple questions.
1. Will there be a default spec which has the default values for each of the providers fields like we had with the original chart installation?
2. "The ... should be replaced with a tab for each output destination found here: https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/output_types/" are we actually doing all of those providers now? If so I'm going to need to know which fields we're going to be using for each tab.

**Comment by codyrancher** [comment]
@deniseschannon I have a few questions for you too.
1. Are we going to be adding any metrics or anything to the overview pages in general? As of right now it looks a little austere.
![image](https://user-images.githubusercontent.com/55104481/91620535-17d3e780-e945-11ea-83f1-9d7414e9135d.png)
2. Vince wanted me to change the enabled/disabled LabeledSelect to Radios. I personally prefer the labeled select and wanted to know how you felt. Here's the conversation and some screenshots. https://github.com/rancher/dashboard/pull/1048#issuecomment-675732949
3. Similarly Vince wanted to disable all the input below instead of hiding/showing. Which would you prefer? Again, the conversation and screenshots are here https://github.com/rancher/dashboard/pull/1048#issuecomment-675732949.

**Comment by paynejacob** [comment]
1. There is not a default spec but each provider is optional, the key can just be omitted.
2. Yes we are going to support all providers.  Ill pull a table together of all the fields for them.

**Comment by deniseschannon** [comment]
@codyrancher 
1. there is the overview ticket that has some content: https://github.com/rancher/dashboard/issues/1089 
2/3. Can we bring this up in the next design meeting? I would prefer if enabled/disabled checkbox would show/hide the fields versus enable/disable, but do we actually need the enable/disable? Can't we assume if they fill in a box then it is enabled?

**Comment by paynejacob** [comment]
# Outputs

For any reference to secret type see: https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/secret/


## S3
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/s3/
| Name | Key | Type | Default |
|--|--|--|--|
| Key Id | aws_key_id | secret_pair | - |
| Secret Id | aws_sec_id | secret_pair | - |
| Endpoint | s3_endpoint | string | - |
| Bucket | s3_bucket | string | - |
| Path | path | string | - |
| Overwrite Existing Path | overwrite | bool | false |

## Azure Storage
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/azurestore/
| Name | Key | Type | Default |
|--|--|--|--|
| Storage Account | azure_storage_account | secret_pair | - |
| Access Key | azure_storage_access_key | secret_pair | - |
| Container | azure_container | string | - |
| Path | path | string | - |
| Store As | store_as | string<gzip\|json\|text\|lzo\|lzma2> | gzip |
## GCS
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/gcs/
| Name | Key | Type | Default |
|--|--|--|--|
| Project | project | string | - |
| Credentials Json | credentials_json | secret_pair | - |
| Bucket | bucket | string | - |
| Path | path | string | - |
| Overwrite Existing Path | overwrite | bool | false |
## Elasticsearch
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/elasticsearch/
| Name | Key | Type | Default |
|--|--|--|--|
| Host | host | string | - |
| Port | port | string | - |
| Scheme | scheme | string | - |
| User | user | string | - |
| Password | password | secret_pair | - |
| Certificate Authority File | ca_file | secret_pair | - |
| Client Certificate | client_cert | secret_pair | - |
| Client Key | client_key | secret_pair | - |
| Client Key Password | client_key_pass | secret_pair | - |
| Index Name | index_name | string | - |
## LogZ
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/logz/
| Name | Key | Type | Default |
|--|--|--|--|
| Endpoint | endpoint | string | - |
| Enable Compression | gzip | bool | true |
## Loki
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/loki/
| Name | Key | Type | Default |
|--|--|--|--|
| Url | url | string | - |
| Username | username | secret_pair | - |
| Password | password | secret_pair | - |
| Tenant | tenant | string | - |
## SumoLogic
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/sumologic/
| Name | Key | Type | Default |
|--|--|--|--|
| Endpoint | endpoint | string | - |
## Datadog
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/datadog/
| Name | Key | Type | Default |
|--|--|--|--|
| API Key | api_key | secret_pair | - |
| Use SSL | use_ssl | bool | - |
| Use Compression | use_compression | bool | - |
| Host | host | string | - |
## Forward
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/forward/
| Name | Key | Type | Default |
|--|--|--|--|
| Host | servers.0.host | string | - |
| Port | servers.0.port | string | - |
| Shared Key | servers.0.shared_key | secret_pair | - |
| Username | servers.0.username | secret_pair | - |
| Password | servers.0.password | secret_pair | - |
## File
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/file/
| Name | Key | Type | Default |
|--|--|--|--|
| Path | path | string | - |
## Kafka
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/kafka/
| Name | Key | Type | Default |
|--|--|--|--|
| Brokers | brokers | string | - |
| Default Topic | default_topic | string | - |
| SASL Over SSL | sasl_over_ssl | bool | - |
| SCRAM Mechanism | scram_mechanism | string<SCRAM\|PLAIN> | - |
| Username | username | secret_pair | - |
| Password | password | secret_pair | - |
| Certificate Authority Cert | ssl_ca_cert | secret_pair | - |
| Client Certificate | ssl_client_cert | secret_pair | - |
| Client Certificate Chain | ssl_client_cert_chain | secret_pair | - |
| Client Certificate Key | ssl_client_cert_key | secret_pair | - |
## Cloudwatch
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/cloudwatch/
| Name | Key | Type | Default |
|--|--|--|--|
| Key Id | aws_key_id | secret_pair | - |
| Secret Id | aws_sec_id | secret_pair | - |
| Endpoint | endpoint | string | - |
## Kinesis Stream
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/kinesis_firehose/
| Name | Key | Type | Default |
|--|--|--|--|
| Key Id | aws_key_id | secret_pair | - |
| Secret Id | aws_sec_id | secret_pair | - |
## Log DNA
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/logdna/
| Name | Key | Type | Default |
|--|--|--|--|
| API Key | api_key | string | - |
| Hostname | hostname | string | - |
| App | app | string | - |
## New Relic
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/newrelic/
| Name | Key | Type | Default |
|--|--|--|--|
| API Key| api_key | secret_pair | - |
| License Key | license_key | secret_pair | - |
| Base URI | base_uri | string | - |
## Splunk HEC
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/splunk_hec/
| Name | Key | Type | Default |
|--|--|--|--|
| Host| host | string | - |
| Port | port | string | - |
| Protocol | protocol | string<http\|https> | - |
| HEC Token | hec_token | secret_pair | - |
| Insecure SSL | insecure_ssl | bool | - |
## AWS Elasticsearch
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/aws_elasticsearch/
| Name | Key | Type | Default |
|--|--|--|--|
| Url| endpoint.url | string | - |
| Key Id | endpoint.aws_key_id | secret_pair | - |
| Secret Id | endpoint.aws_sec_id | secret_pair | - |

**Comment by deniseschannon** [comment]
MVP for 2.5: 

```
Elasticsearch
Splunk
Kafka
Fluentd
```

2.5.x: Rest of list

**Comment by deniseschannon** [comment]
Overview Page Idea:

Show icons of all providers and maybe add ability to click on icon to be re-directed to the tab.

**Comment by lvuch** [comment]
[white logos.zip](https://github.com/rancher/dashboard/files/5171708/white.logos.zip)

**Comment by paynejacob** [comment]
Cluster outputs should only be deployable in the cattle-logging-system namespace.  Any other namespace will render them inert.

**Comment by izaac** [comment]
Rancher version: `master-head (09/23/2020)` _e9a98a3_ HA k8s with RKE DO downstream 

Create ClusterOutput `Preview YAML` is not showing the spec preview.

![Screen Shot 2020-09-23 at 12 22 38 PM](https://user-images.githubusercontent.com/27659/94059587-80bd4c80-fd97-11ea-8071-0411a3d200a9.png)

![Screen Shot 2020-09-23 at 12 22 45 PM](https://user-images.githubusercontent.com/27659/94059632-8b77e180-fd97-11ea-94ba-d89c60a90538.png)

**Comment by deniseschannon** [comment]
Closing as the current open issues are opened separately.
