### ISSUE TITLE
[Logging V2] Output Page

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1103]
Overview Page
This tab should just contain a description of what an output is.  @paynejacob will write this section and attach it to this ticket.
CRD Docs
This is the CRD: https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/clusteroutput_types/
Mockup
![output](https://user-images.githubusercontent.com/12258347/91078957-49247e80-e5f8-11ea-9f3c-9861523c176f.png)
The ... should be replaced with a tab for each output destination found here: https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/output_types/ (edited)

**Comment by paynejacob** [comment]
Overview Text: "An output is where logs can be delivered for the current namespace."

**Comment by paynejacob** [comment]
# Outputs

For any reference to secret type see: https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/secret/


## S3
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/s3/
| Name | Key | Type | Default |
|--|--|--|--|
| Key Id | aws_key_id | secret_pair | - |
| Secret Id | aws_sec_id | secret_pair | - |
| Endpoint | s3_endpoint | string | - |
| Bucket | s3_bucket | string | - |
| Path | path | string | - |
| Overwrite Existing Path | overwrite | bool | false |

## Azure Storage
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/azurestore/
| Name | Key | Type | Default |
|--|--|--|--|
| Storage Account | azure_storage_account | secret_pair | - |
| Access Key | azure_storage_access_key | secret_pair | - |
| Container | azure_container | string | - |
| Path | path | string | - |
| Store As | store_as | string<gzip\|json\|text\|lzo\|lzma2> | gzip |
## GCS
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/gcs/
| Name | Key | Type | Default |
|--|--|--|--|
| Project | project | string | - |
| Credentials Json | credentials_json | secret_pair | - |
| Bucket | bucket | string | - |
| Path | path | string | - |
| Overwrite Existing Path | overwrite | bool | false |
## Elasticsearch
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/elasticsearch/
| Name | Key | Type | Default |
|--|--|--|--|
| Host | host | string | - |
| Port | port | string | - |
| Scheme | scheme | string | - |
| User | user | string | - |
| Password | password | secret_pair | - |
| Certificate Authority File | ca_file | secret_pair | - |
| Client Certificate | client_cert | secret_pair | - |
| Client Key | client_key | secret_pair | - |
| Client Key Password | client_key_pass | secret_pair | - |
| Index Name | index_name | string | - |
## LogZ
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/logz/
| Name | Key | Type | Default |
|--|--|--|--|
| Endpoint | endpoint | string | - |
| Enable Compression | gzip | bool | true |
## Loki
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/loki/
| Name | Key | Type | Default |
|--|--|--|--|
| Url | url | string | - |
| Username | username | secret_pair | - |
| Password | password | secret_pair | - |
| Tenant | tenant | string | - |
## SumoLogic
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/sumologic/
| Name | Key | Type | Default |
|--|--|--|--|
| Endpoint | endpoint | string | - |
## Datadog
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/datadog/
| Name | Key | Type | Default |
|--|--|--|--|
| API Key | api_key | secret_pair | - |
| Use SSL | use_ssl | bool | - |
| Use Compression | use_compression | bool | - |
| Host | host | string | - |
## Forward
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/forward/
| Name | Key | Type | Default |
|--|--|--|--|
| Host | servers.0.host | string | - |
| Port | servers.0.port | string | - |
| Shared Key | servers.0.shared_key | secret_pair | - |
| Username | servers.0.username | secret_pair | - |
| Password | servers.0.password | secret_pair | - |
## File
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/file/
| Name | Key | Type | Default |
|--|--|--|--|
| Path | path | string | - |
## Kafka
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/kafka/
| Name | Key | Type | Default |
|--|--|--|--|
| Brokers | brokers | string | - |
| Default Topic | default_topic | string | - |
| SASL Over SSL | sasl_over_ssl | bool | - |
| SCRAM Mechanism | scram_mechanism | string<SCRAM\|PLAIN> | - |
| Username | username | secret_pair | - |
| Password | password | secret_pair | - |
| Certificate Authority Cert | ssl_ca_cert | secret_pair | - |
| Client Certificate | ssl_client_cert | secret_pair | - |
| Client Certificate Chain | ssl_client_cert_chain | secret_pair | - |
| Client Certificate Key | ssl_client_cert_key | secret_pair | - |
## Cloudwatch
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/cloudwatch/
| Name | Key | Type | Default |
|--|--|--|--|
| Key Id | aws_key_id | secret_pair | - |
| Secret Id | aws_sec_id | secret_pair | - |
| Endpoint | endpoint | string | - |
## Kinesis Stream
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/kinesis_firehose/
| Name | Key | Type | Default |
|--|--|--|--|
| Key Id | aws_key_id | secret_pair | - |
| Secret Id | aws_sec_id | secret_pair | - |
## Log DNA
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/logdna/
| Name | Key | Type | Default |
|--|--|--|--|
| API Key | api_key | string | - |
| Hostname | hostname | string | - |
| App | app | string | - |
## New Relic
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/newrelic/
| Name | Key | Type | Default |
|--|--|--|--|
| API Key| api_key | secret_pair | - |
| License Key | license_key | secret_pair | - |
| Base URI | base_uri | string | - |
## Splunk HEC
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/splunk_hec/
| Name | Key | Type | Default |
|--|--|--|--|
| Host| host | string | - |
| Port | port | string | - |
| Protocol | protocol | string<http\|https> | - |
| HEC Token | hec_token | secret_pair | - |
| Insecure SSL | insecure_ssl | bool | - |
## AWS Elasticsearch
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/aws_elasticsearch/
| Name | Key | Type | Default |
|--|--|--|--|
| Url| endpoint.url | string | - |
| Key Id | endpoint.aws_key_id | secret_pair | - |
| Secret Id | endpoint.aws_sec_id | secret_pair | - |

**Comment by paynejacob** [comment]
Only The following outputs are required 
- Elasticsearch
- Splunk
- Kafka
- Fluentd

**Comment by izaac** [comment]
Rancher version: `master-head (09/23/2020)` _e9a98a3_ HA k8s with RKE DO downstream 

Create Output `Preview YAML` is not showing the spec preview.

![Screen Shot 2020-09-23 at 12 19 43 PM](https://user-images.githubusercontent.com/27659/94059430-3dfb7480-fd97-11ea-865c-feaff3154ad0.png)

![Screen Shot 2020-09-23 at 12 19 56 PM](https://user-images.githubusercontent.com/27659/94059443-43f15580-fd97-11ea-8d2f-8ef39fce8c8a.png)

**Comment by deniseschannon** [comment]
Closing as the current and net new issues will be filed separately.
