### ISSUE TITLE
AKS cluster creation: dropdown list for supported Kubernetes versions does not populate

### ISSUE THREAD

**Issue by moio** [rancher/dashboard#11040]
**Setup**
- Rancher version: 2.8.3
- Rancher UI Extensions: none
- Browser type & version: latest Firefox and Chrome

**Describe the bug**
When creating an AKS cluster the dropdown list for supported Kubernetes version does not populate - despite the backend apparently responding with the correct list.

![image](https://github.com/rancher/dashboard/assets/250541/fd5014ee-3363-43dd-bcd0-f203342b2ce2)

**To Reproduce**
- add an Azure Cloud credential
- home -> Create
- continue in the wizard

**Result**

**Expected Result**
When I click on the Kubernetes Version dropdown, there are options that can be chosen.

**Screenshots**
See above

**Comment by mantis-toboggan-md** [comment]
This should be resolved in 2.9.0 with the work to port this form from Ember to Vue https://github.com/rancher/dashboard/pull/9669

**Comment by yonasberhe23** [comment]
as mentioned above this is resolved. Verified in 2.9



![Image](https://github.com/rancher/dashboard/assets/127343932/16b4e08e-0d05-4852-928c-061c11987c82)
