### ISSUE TITLE
When creating constraint, changing name removes YAML

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#1104]
Go to the Dashboard in the local cluster
Apps -> Charts -> rancher-gatekeeper Install
Under OPA Gatekeeper -> Constraints -> Create from YAML
Fill in YAML field
Type something for the constraint name in upper field

Result:
YAML disappears. This also happens when the template is changed. 
Rancher server `rancher\rancher:master-head` `version 9b6984d5f` `master-9b6984d5fa33c65ebcc3dee04bb918300451cf37-head`

**Comment by deniseschannon** [comment]
OPA was re-implemented and this no longer relevant, but moving it over to test for QA .

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 731b33e`

Create from YAML no longer has a field for `name`
![Screen Shot 2020-09-03 at 12 21 03 PM](https://user-images.githubusercontent.com/57409052/92158109-4556e000-ede0-11ea-9b90-0abe378c66a8.png)
