### ISSUE TITLE
Rancher provisioned/managed RKE2/K3s data-dir support

### ISSUE THREAD

**Issue by jakefhyde** [rancher/dashboard#11061]
There is currently an ongoing effort to support specifying the RKE2/K3s `data-dir` argument, which allows a user to change it from the default of `/var/lib/rancher/rke2` & `/var/lib/rancher/k3s` respectively, to a user provided directory. I've found the following instances of these directories hardcoded within the project:
- https://github.com/rancher/dashboard/blob/e09df1da0e6fdef6c46556b186020bf2c3059484/shell/edit/provisioning.cattle.io.cluster/rke2.vue#L1379
Please review the above information, and feel free to reach out to me regarding questions. The api changes can be found within this draft PR within rancher/rancher: https://github.com/rancher/rancher/pull/45326/files#diff-6f7b3ace8ec7df668da64642416a1171322908df345c8e339d314bac3ed08af6R57.

**Comment by richard-cox** [comment]
Note - Additional work on top of https://github.com/rancher/dashboard/issues/10824.

@jakefhyde In places like this what would be the alternative? Would whatever consumes that value have to lookup the root directly given the custom data-dir setting?

**Comment by jakefhyde** [comment]
@richard-cox That's a good catch, I'm leaning towards we should always populate this field, since if the setting changed we wouldn't want to update all the clusters. I'll bring this up with the team and sync up with @mattfarina to make sure that won't have any downsides.

**Comment by IsaSih** [comment]
Validated with @noahgildersleeve and the UI is sending the payload as expected

![Image](https://github.com/user-attachments/assets/10c02e34-639a-4a0a-9dc1-8be4eaece84e)
