### ISSUE TITLE
[ Istio V2 ]: CRD View - Virtual Services

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#1107]
**Page Title: Add Virtual Service**

**Section Title: (none / na )** 
Field Name ( Header/Label of the field) | YAML (where is the field in the yaml) | Input Type (Is it string or number, etc?) | Default Value/Example Text (What should the default value (value will be passed through on creation) be or the example text (value is not passed through on creation)? | Tooltip Text (Text if it can help explain the field)
-- | -- | -- | -- | --
Name | metadata.name | string | Default Text: mygateway |  
Namespace | metadata.namespace | string | Default Text: myapp |
Hosts | spec.hosts | string[] | Default Text: Select or Input a host |
Gateways | spec.gateways| string[] | Default Test: Select or Input a gateway|

`Hosts` and `Gateways` should be able to add and remove many strings. Would be nice to select from existing resources .

**Section Title: HTTP Routes** 
Field Name ( Header/Label of the field) | YAML (where is the field in the yaml) | Input Type (Is it string or number, etc?) | Default Value/Example Text (What should the default value (value will be passed through on creation) be or the example text (value is not passed through on creation)? | Tooltip Text (Text if it can help explain the field)
-- | -- | -- | -- | --
Host | spec.http[x].route[x].destination.host | string | Default Text: Select or Input a host |
Subset | spec.http[x].route[x].destination.subset | string | Default Text: v1 |
Port | spec.http[x].route[x].destination.port | string[] | Default Text: Select or Input a host |
Weight | spec.http[x].route[x]| int | Default Test: 100% |

Should be able to add and remove multiple destinations 

Toggle `Specify match rules for this route` and show the following fields
Field Name ( Header/Label of the field) | YAML (where is the field in the yaml) | Input Type (Is it string or number, etc?) | Default Value/Example Text (What should the default value (value will be passed through on creation) be or the example text (value is not passed through on creation)? | Tooltip Text (Text if it can help explain the field)
-- | -- | -- | -- | --
Match Type | spec.http[x].match[x].<matchtype value> | string DropDown | Default Text: Select option |  
Key | spec.http[x].match[x].<matchtype value>.<key value> | string | Default Text: end-user |
Condition | spec.http[x].match[x].<matchtype value>.<key value>.<condition value> | string DropDown | Default Text: Select Option |
Value | spec.http[x].match[x].<matchtype value>.<key value>.<condition value> | string | Default Test: Jason|

Should be able to add and remove multiple matches
Should be able to add and remove multiple match types

`Match Type` dropdown values: 
```
URI
Scheme
Method
Authority
Headers
```

`Condition` dropdown values:
```
Exact Match (value: exact)
Prefix Match (value: prefix)
Regex Match (value: regex)
```

Example of match request:
```
spec:
  hosts:
  - ratings.prod.svc.cluster.local
  http:
  - match:
    - headers:
        end-user:
          exact: jason
      uri:
        prefix: "/ratings/v2/"
      ignoreUriCase: true
```
Should be able to add and remove multiple http routes

**Section Title: Labels:**
Field Name ( Header/Label of the field) | YAML (where is the field in the yaml) | Input Type (Is it string or number, etc?) | Default Value/Example Text (What should the default value (value will be passed through on creation) be or the example text (value is not passed through on creation)? | Tooltip Text (Text if it can help explain the field)
-- | -- | -- | -- | --
Key | metadata.labels | string | Default Text: key1 |  
Value | metadata.labels  | string | Default Text: value1 |

Example :
```
metadata:
  labels:
    <key>:<value>
```
**Section Title: Annotations:**
Field Name ( Header/Label of the field) | YAML (where is the field in the yaml) | Input Type (Is it string or number, etc?) | Default Value/Example Text (What should the default value (value will be passed through on creation) be or the example text (value is not passed through on creation)? | Tooltip Text (Text if it can help explain the field)
-- | -- | -- | -- | --
Key | metadata. annotations | string | Default Text: key1 |  
Value | metadata. annotations  | string | Default Text: value1 |

Example :
```
metadata:
  annotations:
    <key>:<value>
```
More examples and types can be found [here](https://istio.io/latest/docs/reference/config/networking/virtual-service/)

![Screen Shot 2020-08-26 at 2 23 44 AM](https://user-images.githubusercontent.com/19455540/91286339-2f438280-e743-11ea-9c12-20b2a99e8021.png)

**Comment by nwmac** [comment]
We don't plan to add support for this in the near future - we will be looking at the Istio UI support in a future version.
