### ISSUE TITLE
Ingresses List warns `pathExistsInSchema` has been used without fetching the schema definition

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11086]
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

- schema diet related
- ```
  pathExistsInSchema requires schema networking.k8s.io.ingress to have resources fields via schema definition but none were found. 
  has the schema 'fetchResourceFields' been called?
  ```
- ```
  get useNestedBackendField() {
    if (!this.cache.useNestedBackendField) {
      this.cache.useNestedBackendField = this.$rootGetters['cluster/pathExistsInSchema'](this.type, 'spec.rules.http.paths.backend.service.name');
    }

    return this.cache.useNestedBackendField;
  }
  ```
- /v1/schemaDefinitions/networking.k8s.io.ingress is called, so maybe a timing issue

**To Reproduce**
- Open dev tools
- Navigate to Ingress list

**Result**
- See warnings in console
-
**Expected Result**
- this has an unknown impact, could be that the list doesn't really need it, could cause info in list not to show

**Comment by yonasberhe23** [comment]
e2e test is sufficient! moving to done
