### ISSUE TITLE
Upgrade Vuex implementation to be compatible with Vue 3's reactivity system

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11081]
The current Vuex implementation for Dashboard is not fully compatible with Vue 3's reactivity system. Using `Object.defineProperty()` on the root state will generate the following error

```
Uncaught (in promise) TypeError: proxy must report the same value for the non-writable, non-configurable property '"$plugin"'
```

This error occurs because Vue 3 wraps the store's state object with a proxy to make it reactive, and the proxy's target object has its properties marked as non-writable and non-configurable.

- [ ] #11098

**Comment by rak-phillip** [comment]
@yonasberhe23 this is a refactor that should be covered by existing e2e tests.

**Comment by yonasberhe23** [comment]
@rak-phillip thanks! moving this to done. cc: @izaac
