### ISSUE TITLE
[v2.9] EKS: Inappropriate error - "Name" is required

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11105]
**Setup**
Rancher version: `v2.9-3c48a195381ad55f9fef7e9bf32b1593d43368ca-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Inappropriate error - "Name" is required, while creating EKS cluster

**To Reproduce**
- Delete Amazon cloud credentials, if any
- Create EKS cluster from Rancher UI

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/16b5d9a0-5bc3-49cf-bfb8-6c601fd94023)

**Comment by yonasberhe23** [comment]
unit test coverage is sufficient. moving to done
