### ISSUE TITLE
[v2.9] EKS: Cluster version upgrade updates nodegroup version too

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11102]
**Setup**
Rancher version: `v2.9-3c48a195381ad55f9fef7e9bf32b1593d43368ca-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Cluster version upgrade updating nodegroup version too
In Old UI, version upgrade was two-step process, Upgrade Control plane and then  upgrade Nodegroup
When new Cluster version was selected, below message is displayed for Nodegroup

![image](https://github.com/rancher/dashboard/assets/73099870/93f78078-22d1-4077-b6fd-cb164504efed)

**To Reproduce**
- Create EKS cluster from Rancher UI
- Once cluster becomes Active, edit cluster and upgrade Kubernetes Version

**Comment by yonasberhe23** [comment]
The user now has the option to upgrade the node group version after the cluster version upgrade. unit tests are sufficient. moving to done.
