### ISSUE TITLE
[v2.9] EKS: Unexpected character in Kubernetes Version drop-down

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11101]
**Setup**
Rancher version: `v2.9-3c48a195381ad55f9fef7e9bf32b1593d43368ca-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Unexpected character "[" in Kubernetes Version drop-down

**To Reproduce**
- Create EKS cluster from Rancher UI
- Check K89s version dropdown

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/bf7bceac-c4d9-42fd-8c47-50e500fb7bbc)

**Comment by mantis-toboggan-md** [comment]
Closing as duplicate of https://github.com/rancher/dashboard/issues/11195
