### ISSUE TITLE
Need an indication that the shell is connecting when launching kubectl shell

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1111]
Need a UI indicator while waiting for the shell to open when launching kubectl

**Comment by sowmyav27** [comment]
On 2.5-head latest -

Launch Shell from dashboard.
It says Connecting.. and Connected
<img width="147" alt="Screen Shot 2020-10-15 at 4 13 10 AM" src="https://user-images.githubusercontent.com/26032343/96053261-d370bc80-0e9c-11eb-9df7-36af5575739d.png">
<img width="201" alt="Screen Shot 2020-10-15 at 4 13 02 AM" src="https://user-images.githubusercontent.com/26032343/96053262-d53a8000-0e9c-11eb-9911-9c6ed699d748.png">
