### ISSUE TITLE
Update DOCS_BASE to v2.10

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11114]
- Current `DOCS_BASE` points to `https://ranchermanager.docs.rancher.com/v2.8` (2.9 soon https://github.com/rancher/dashboard/issues/10766)
- When 2.10 becomes available value needs updating
- Need to sync with docs team on when this will be

Alternatively we need a way to automate this

**Comment by gaktive** [comment]
Release team may be able to help going forward. @rak-phillip to check. 
Past efforts on automation: https://github.com/rancher/dashboard/issues/7149

@nwmac is working on another ticket to handle an upcoming URL structure change.

**Comment by gaktive** [comment]
@gunamata while we wait for the list of changes, based on the number of links we have already, we'll likely need redirects in place already for 2.10 according to @nwmac as code freeze is coming up fast. Do let us know what the new URLs are still.

**Comment by gunamata** [comment]
@gaktive , You can find the new links in the spreadsheet below. 
https://docs.google.com/spreadsheets/d/1lDw_Vx41D7m2qFaRt5ybJhm__ky00pD_nM6KH2gXqvQ/edit?usp=sharing

**Comment by nwmac** [comment]
@gaktive we do not have time to change any links or have different links for prime

**Comment by gunamata** [comment]
@momesgin , Good catch, the version numbers in the spreadsheet are just placeholders and need to be adjusted for the specific rancher version being worked on. 

> I think this will be first time we differentiate the doc links based on the prime version, and if that's the requirement then the answer is yes.
yes, that's the requirement.

**Comment by gaktive** [comment]
@gunamata as noted, UI is running up at time to get the links updated in the dashboard code. Could Docs do redirects for the old links to the new ones with the 2.10 version? 

Otherwise, I see both community & prime links there so I don't know if community users are intended to view prime docs. If not, then UI will need some new logic to detect and differentiate to show the appropriate docs. Should we default to community only for now? Then later, show prime for prime users?

**Comment by gunamata** [comment]
@gaktive , It's not possible to do the redirects from the docs side as we would not know the context (community or prime) the link is being accessed.

I understand it's late in the cycle :( , if it's not possible to squeeze this into 2.10 then we need to do this in the next set of prime releases. 

Yes, the UI will need some logic to detect and point to different docs. The idea is that community version would continue to point to the current links being used in the UI today. The Prime version needs to use the new links provided in the doc. I understand that the already released prime versions will point to community docs and it's a known limitation/behavior.

**Comment by gaktive** [comment]
OK thanks @gunamata could we do redirects for community 2.10.0 at least? I'll file a ticket to look at detecting community vs. prime so that for the 2.10.1 prime release, we can see what's possible.

**Comment by nwmac** [comment]
@gunamata UI will handle the two sets of links, but not for 2.10.0, so both prime and community will get the community links.

We do the need community links for 2.10 put in place though.

**Comment by gunamata** [comment]
@gaktive , @nwmac  - 2.10.0 community docs links have not changed (except for the obvious version part). 
@btat , Keep me honest here.

**Comment by btat** [comment]
@gaktive @nwmac @gunamata We'll have the 2.10 preview docs set, and the redirects for the specific links in the spreadsheet, available later this week.

**Comment by momesgin** [comment]
@gaktive based on the discussion above, and the fact that we're already using 2.10 in the code for the urls, we should be fine closing this issue later this week probably after a quick test, unless we want to keep this open and update the requirement to cover the implementation of dynamic links based on prime & community versions.

**Comment by gaktive** [comment]
Thanks @momesgin -- I filed a new ticket #12384 to start figuring out what to do there.

And thanks @btat for getting redirects prepared!

**Comment by gaktive** [comment]
@nwmac indeed

For now, let's get the new links in with anticipation that the redirects are in place. Timing ideally should have this done before code freeze but QA may have to keep us honest.

**Comment by btat** [comment]
2.10 docs and redirects are active now.

**Comment by izaac** [comment]
@momesgin is this coming organically to 2.10 after the 2.9 PR [here](https://github.com/rancher/dashboard/pull/11191) ? Or does this have a 2.10 specific PR?

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-10e26d1256a15f76e27a41184d92c4b8781dd94b-head`
UI version: `master 6dd2962`

Support Links, Home Links and Charts links redirect to the 2.10 pages as expected of the Rancher Manager docs.
