### ISSUE TITLE
Refreshing, or navigating directly to, a chart install page loses chart context

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11126]
**Setup**
- Rancher version: dev 2.9.0

**Describe the bug**
- As per title

**To Reproduce**
- Navigate local cluster --> cluster tools --> rancher backups --> install --> refresh page
 
**Result**
The `no chart found` chart install process kicks in and user is requested to pick the chart (bonus point, there's no chart to choose from)

**Expected Result**
Step one of the install Rancher Backups wizard is shown

**Screenshots**
Result
![image](https://github.com/rancher/dashboard/assets/18697775/8308ef9d-23dd-44a6-8332-86bcd03ba689)

Expected
![image](https://github.com/rancher/dashboard/assets/18697775/87b3e90a-1017-41fc-a43a-d709fdda5487)

**Additional context**
I'm pretty sure this is a regression

**Comment by richard-cox** [comment]
```
    updateStepOneReady() {
      const okRequires = !this.requires.length;
      const okChart = !!this.chart;

      this.steps[0].ready = okRequires && okChart;
    },
```

Looks like there's two failed (200, but empty content) requests to fetch charts BEFORE the above runs (so no chart) then another that succeeds (but above does not re-run).

**Comment by aalves08** [comment]
I can confirm that `Elemental`, `Neuvector` and `Kubewarden` extensions have their operator install procedure broken because of this. 

Temporary fix on extensions side is to use the `/chart` route instead of the `/install` one. One extra click for the user, but at least we don't hit the bug anymore.

FYI @jordojordo

**Comment by richard-cox** [comment]
Checked in 2.8, t's a regression in 2.9

**Comment by richard-cox** [comment]
In summary

- This is a 2.9.0 regression
- It breaks direct links to the install chart wizard, which is used by Elemental, KubeWarden and NeuVector in their bootstrap process 
  - To fix can either
    - Merge connected PR
    - Change three extensions to direct users to the chart detail page, they would then need to click install
    - Publish workaround asking extension users to navigate to chart via Charts list

**Comment by richard-cox** [comment]
Given timing this should have thorough manual QA, see `Areas or cases that should be tested` in PR

**Comment by yonasberhe23** [comment]
Tested in 
- v2.9-a402bfa1ff0cc051cfabe3d9380b7eca678443f9-head
- master 102f1e6


Resource | Refresh Results | Direct Nav Results
----|-----|-----
Cluster tools --> Install App | ✅ | ✅
Cluster tools --> Upgrade App | ✅ | ✅
Apps --> Charts --> chart | ✅ | ✅
Apps --> Charts --> chart --> chart version | ✅ | ✅
Apps --> Installed Apps --> app upgrade | ✅ | ✅
