### ISSUE TITLE
Deleted app is stuck in Uninstalling

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1112]
**On master-head - commit id: `9b6984d5f`**

- Login to Dashboard
- Navigate to Apps --> repositories --> Add repo
- Git URL: `https://github.com/mrajashree/charts.git` Branch: `backup-restore`
- Navigate to Charts -- deploy app backup-restore-operator. App gets deployed
- Now delete the app from "Installed Apps" page.
- The app is stuck in "Uninstalling" state for long. Click on the app. It navigates to the webpage with error

<img width="661" alt="Screen Shot 2020-08-26 at 10 09 43 AM" src="https://user-images.githubusercontent.com/26032343/91340175-64c08e00-e78c-11ea-929b-64864e7be196.png">

**Comment by deniseschannon** [comment]
I was able to delete installed apps. Please test again @sowmyav27

**Comment by sowmyav27** [comment]
**On master-head - `343b8e19c`**

- Deploy rancher - backup restore through the helm command.
- The app gets installed
- delete the app through Dashboard UI
- App goes from `Active` to `uninstalling` and the app gets deleted successfully.
