### ISSUE TITLE
Fleet: Git Repos: Details: Graph loads in ~30 min when git repo is in active state

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#11133]
**Setup**
- Rancher version: v2.9-b74832dde8f4a272ea4f5fd3cfb846159c681be1-head
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
The graph takes ~30 minutes to load in v2.9 (loads within ~15 sec in v2.8).

**To Reproduce**
1. go to fleet > git repos tab
2. click 'Add Repositories'
3. input repo URL ('https://github.com/rancher/fleet-examples.git')
4. click 'Add Path' 
5. input path ('simple')
6. click 'Create'
7. wait until it is in Active state
8. navigate to git repo's details page
9. click on 'Graph'
10. notice the time it takes for graph to load

**Result**
The graph loads in ~30 minutes in v2.9 (loads within ~15 sec in v2.8).

**Expected Result**
The graph loads within ~15 seconds

**Screenshots**
<img width="1016" alt="Screenshot 2024-05-28 at 10 44 16 AM" src="https://github.com/rancher/dashboard/assets/127343932/378887f1-c80a-4391-b2c9-9f879707674d">

**Additional context**

**Comment by gaktive** [comment]
Possibly related PR per @rak-phillip: https://github.com/rancher/dashboard/pull/11062/files

**Comment by richard-cox** [comment]
I had a look at the performance logs. There's no network requests handing around, no errors in console and no cpu churn. Needs debugging

**Comment by richard-cox** [comment]
Multiple issues here
1. $watch fails to trigger https://github.com/rancher/dashboard/blob/7d69ff2b553f00a102ab9cec95e3e4ace5d74e54/shell/components/fleet/ForceDirectedTreeChart/index.vue#L335-L337
   - for git repos this watches on the prop `data`s `bunldes` property (on modal). i added a manual watch on `data.bundles` works around this in dev land
2. no state for `gitupdating` , so cannot access color prop https://github.com/rancher/dashboard/blob/7d69ff2b553f00a102ab9cec95e3e4ace5d74e54/shell/pages/c/_cluster/fleet/GitRepoGraphConfig.js#L95
   - working around this with a ?. gives the next issue 
3. svg doesn't get created https://github.com/rancher/dashboard/blob/7d69ff2b553f00a102ab9cec95e3e4ace5d74e54/shell/components/fleet/ForceDirectedTreeChart/index.vue#L86
    - svg not defined
