### ISSUE TITLE
Show version number in app bar and remove from the side nav

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#11137]
Currently we only show the version number in the side navigation area - which does not appear on all screens - only those with a side nav - e.g.
e.g. appears here:

![image](https://github.com/rancher/dashboard/assets/1955897/df232b33-d54e-4d00-8264-51bbcbadb1ae)

but not here:

![image](https://github.com/rancher/dashboard/assets/1955897/62b42730-41de-4ae9-bf94-2d3360179a85)

With the removal of the cluster tools button (moved as Tools under Cluster nav item), the version number looks odd and out of alignment with the 'About' text in the side bar:

![image](https://github.com/rancher/dashboard/assets/1955897/181bc2ca-ba11-4316-a52c-f389c9a58450)

(Note this shows a dev version number, which is an 8 character commit hash)

My suggestion is:

- Remove the version number from the side navigation
- For a released version, instead of 'About', show the version number
  - For a .0 minor release, we should abbreviate so that for `v2.9.0` we show `v2.9`
  - For all other versions, we show the full version number, e.g. `v2.10.11`
- For a development build, we continue to show 'About' - the commit is available from the about page

@edenhernandez-suse I think I discussed this with you and you thought this was reasonable - can you confirm?

**Comment by edenhernandez-suse** [comment]
> @edenhernandez-suse I think I discussed this with you and you thought this was reasonable - can you confirm?

There might even have another issue, but I can't remember. I'm happy with this, the number is kind of a problem without the Cluster Tools button (and the addition of the "Collapse all" button), and it's not useful in production builds.

We need to test worst case scenario, though, something like `v10.10.10` to check that it fits correctly.

**Comment by nwmac** [comment]
@edenhernandez-suse Thanks - for longer versions, we can reduce the font size slightly to fit.

**Comment by yonasberhe23** [comment]
e2e tests are sufficient. moving to done @izaac
