### ISSUE TITLE
Branding colour is applied to the border of the state badge

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#11136]
SURE-8097

**Setup**
- Rancher version:2.7.11

**Describe the bug**

The branding primary color is incorrectly used as the border color for some status badges.

**To Reproduce**

Set the primary colour to a bright red.

Go to cluster management and import a generic cluster.

Go to the cluster management list page - the new cluster will be in the 'Pending' state and the border color for that badge will use the primary colour, rather than the blue background for for the pending state.

![image](https://github.com/rancher/dashboard/assets/1955897/00ca294f-da71-4626-88fd-b8b4a12df842)

The badge should not be using the primary color as the border color.

**Comment by eva-vashkevich** [comment]
Fixed by #11709

**Comment by IsaSih** [comment]
Tests pass on v2.10-61d79963733364046c6fc8e9003bd9d6948a6db0-head and dashboard version master f9d6f31


 ![Image](https://github.com/user-attachments/assets/bcfcda28-9a30-4a71-98f1-81fec7f53502)
