### ISSUE TITLE
EKS instance C6 and M6 types are not listed/found in Rancher 2.8.x 

### ISSUE THREAD

**Issue by skanakal** [rancher/dashboard#11132]
**Setup**
- Rancher version: 2.8.2 
- Rancher UI Extensions: 
- Browser type & version: 

**Describe the bug**

EKS instance C6/M6 types are not listed/found in Rancher 2.8.2. We suspect the available instance types are hardcoded somewhere in Rancher.

**To Reproduce**

- Rancher 2.8.2
- Create EKS and see C6 and M6 instances types are not available (which are available in AWS Console)

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by gaktive** [comment]
Internal reference: SURE-8426

@mantis-toboggan-md does this work in 2.9-head? @skanakal I know you referred to https://github.com/rancher/dashboard/pull/10581 elsewhere but I couldn't tell immediately.

**Comment by mantis-toboggan-md** [comment]
@gaktive this does work in 2.9-head. In the vue port we're not hardcoding instance types; the full list is automatically fetched from amazon.

![Screenshot 2024-06-04 at 7 48 34 AM](https://github.com/rancher/dashboard/assets/42977925/016271bd-3ad7-44e1-ab56-861f5f98ba97)
![Screenshot 2024-06-04 at 7 48 20 AM](https://github.com/rancher/dashboard/assets/42977925/786b6ddf-e6f3-42a0-b58e-2c3c0f59cc1c)

**Comment by nwmac** [comment]
@gaktive FYI - work was done by issue reporter - updated this issue and moved to test for QA to validate

**Comment by yonasberhe23** [comment]
Tested in 
- v2.8-51052a73adcd6ea40cedcefbedc25e707cdb2f25-head
- release-2.8 a38998e


EKS instance C6 and M6 types are available


https://github.com/user-attachments/assets/e30642e3-f8a4-4cea-b2e2-3bc3b47d398b
