### ISSUE TITLE
Add new cert setting to `Settings` page, with appropriate warning

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11138]
SURE-7641
RFC 007

- Placeholder
- New settings should be visible in Global Setting --> Settings page.
- It should have a very clear notice about the effect of changing it

**Comment by gaktive** [comment]
@richard-cox do you think @jordojordo could pick this up since you have plenty of Vai work still to do for 2.9.0?

**Comment by richard-cox** [comment]
Happy to hand over, @jordojordo ping me when you're ready to start and I'll fill in the details

**Comment by sowmyav27** [comment]
Rancher version:
```
Rancher - v2.9-a9355940c0629ca419b7dd3e4098c4ea0e52c0c0-head
Dashboard - master 30d8ecc
```
<img width="1167" alt="Screen Shot 2024-07-10 at 9 23 25 AM" src="https://github.com/rancher/dashboard/assets/26032343/bab8259c-927b-45e8-aa4f-34d22c32d610">
<img width="1180" alt="Screen Shot 2024-07-10 at 9 22 06 AM" src="https://github.com/rancher/dashboard/assets/26032343/4fbe4801-9a15-44aa-8ea7-ef3ff6acd1ca">
- Both the values get set on the setting
- Warning banner is seen.
