### ISSUE TITLE
[AKS Edit form] 'Set Authorized IP Ranges' is editable even though there is no option to set the IP range

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#11147]
**Setup**
- Rancher version: 2.8-head (827dba1)
- Rancher UI Extensions: 
- Browser type & version:

**Describe the bug**

**To Reproduce**

1. Create an AKS cluster (do not check 'Set Authorized IP Ranges').
2. Edit the cluster once it becomes Active and check the 'Set Authorized IP Ranges'.

**Result**
`Add Range` button is visible, but not active; there is no way to add the IP range.

**Expected Result**

`Add Range` button must be active too (if the method is to be allowed); so that IP range can be added.

**Screenshots**

![image](https://github.com/rancher/dashboard/assets/11015077/ceb0c39a-519a-4dfa-a422-d5c775c4a8cf)

[Screencast from 05-31-2024 12:02:05 PM.webm](https://github.com/rancher/dashboard/assets/11015077/ca2aad0b-3696-4fc3-a071-60e0cd7bf933)

**Additional context**

**Comment by mantis-toboggan-md** [comment]
This appears to be fixed in 2.9.0:

https://github.com/user-attachments/assets/a0977a60-114e-4550-9e01-410162a9c702

**Comment by gaktive** [comment]
Putting on to the 2.9.0 milestone though at this stage, if it's not a blocker, this could be tested from 2.9.next1.

**Comment by izaac** [comment]
Confirmed fixed on Rancher `v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head`

The `Add Range` button is now just `Add` and it adds new inputs to fill the ranges.
Add is enable on Edit.
