### ISSUE TITLE
Fleet: Git Repos: Conditions tab missing from details view

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#11155]
**Setup**
- Rancher version: v2.9
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
The Conditions tab is missing from Fleet cluster details view.

**To Reproduce**
2. go to fleet > git repos tab
3. click 'Add Repositories'
4. input repo URL ('https://github.com/rancher/fleet-examples.git')
5. click 'Add Path'
6. input path ('simple')
9. click 'Create'
10. wait until it is in Active state
12. navigate to git repo details page
13. notice Condition tab is missing

**Result**
The Conditions tab is missing from Fleet git repos details view.

**Expected Result**
The Conditions tab is displayed on Fleet git repos details view.

**Screenshots**
![Screenshot 2024-05-30 at 9 58 47 AM](https://github.com/rancher/dashboard/assets/127343932/c91ad648-8433-4742-b329-4facc15ba9ae)

**Additional context**
Note: 
- this also affects the fleet cluster details view
- scenarios are covered by the below e2e tests (will enable them once this fix is merged ):
  - cypress/e2e/tests/pages/fleet/gitrepo.spec.ts > 'check all tabs are available in the details view'.
  - cypress/e2e/tests/pages/fleet/fleet-clusters.spec.ts > 'check all tabs are available in the details view'.
-

**Comment by izaac** [comment]
I am moving this to done @yonasberhe23 as you're currently working on this area as part of our qa tasks
