### ISSUE TITLE
Fleet: Clusters: Resources column does not show summary graph

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#11154]
**Setup**
- Rancher version: v2.8, v2.9
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
Resources column does not show summary graph on fleet clusters page.

**To Reproduce**

1. provision a cluster and wait for it to be active
2. go to fleet > git repos tab
3. click 'Add Repositories'
4. input repo URL ('https://github.com/rancher/fleet-examples.git')
5. click 'Add Path'
6. input path ('simple')
7. click Next
8.  target: newly created cluster or all clusters
9. click 'Create'
10. wait until it is in Active state
11. navigate to fleet clusters list page
12. notice Resources column is blank `-` 

**Result**
Resources column does not show summary graph.
**Expected Result**
Resources column does not show summary graph.

**Screenshots**
![Screenshot 2024-05-30 at 10 14 47 AM](https://github.com/rancher/dashboard/assets/127343932/5cc7b5b0-7dc7-4e41-a453-3a094f7caf90)

**Additional context**

NOTE: I'm currently working on e2e tests to cover this specific scenario.

**Comment by izaac** [comment]
I am moving this to done @yonasberhe23 as you're currently working on this area as part of our qa tasks
