### ISSUE TITLE
After a resource is created duplicate rows are shown in list view

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11151]
**Setup**
- Rancher version: dev 2.9.0 (and much older)

**Describe the bug**
- After a user creates a resource and is returned to the list view for that resource, sometimes a duplicate row for it is shown
- This will occur when there is a slow connection to rancher

**To Reproduce**
- Nav to local cluster --> Apps --> Repositories
- Click `Create`
- Open Dev Tools --> `Network` tab --> change `No throttling` to `Slow 3G`
- In the repo form Enter anything for `Name` and `Index URL`
- Click `Create`

**Result**
- User is shown the Repo list with two entries for the resource that was just created

**Expected Result**
- A single resource

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/7a2d925a-05fd-4da0-984f-3df659c033b9)

**Additional context**
- This is the cause of the flaky respositories.spec e2e test

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
