### ISSUE TITLE
Add NeuVector roles to resource dropdown in global, cluster & role template pages to allow NV SSO

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#11174]
Internal reference: SURE-7894

Currently, NeuVector has to manually update the resources field when defining global roles to allow users to move from Rancher to NV UIs via a single sign-on. We need to add the NV-specific roles to the dropdown to make it less prone to typos and easier for NV admins to grant cross-product access.

NeuVector will create a CRD/CR for the defined NV permissions so that Rancher doesn't need to hard-code NV permissions. That CRD/CR will be created when NV is deployed. It contains information about what permissions are provided by NV for requests.

For 2.9.0, we likely have to hard code these values.

Code references: 
https://github.com/rancher/dashboard/blob/5782b70f7a73e71ee921124c3e31081ff91df806/shell/config/roles.ts#L1
https://github.com/rancher/dashboard/blob/5782b70f7a73e71ee921124c3e31081ff91df806/shell/config/roles.ts#L317-L321

Some information about NV permissions resources to grant on Rancher GlobalRole/ClusterRole/NamespaceRole pages:

For NeuVector verbs/resources/apiGroup to use on Rancher UI Global/Cluster/Project Role Template pages:

//-> apiGroup:

```
api.neuvector.com
```

//-> verbs:

```
get    // for read-only(i.e. view)
*      // for read/write(i.e. modify)
```

//---> for Rancher Global/Cluster Role Template pages
api.neuvector.com     // apiGroup for NeuVector

[resource display]   [resource]
--------------------------------------------------
"All Permissions":   nv-perm.all-permissions
"Admission Control": nv-perm.admctrl
"Audit Events":      nv-perm.audit-events
"Authentication":    nv-perm.authentication
"Authorization":     nv-perm.authorization
"CI Scan":           nv-perm.ci-scan
"Compliance":        nv-perm.compliance
"Events":            nv-perm.events
"Federation":        nv-perm.fed
"Registry Scan":     nv-perm.reg-scan
"Runtime Policy":    nv-perm.rt-policy
"Runtime Scan":      nv-perm.rt-scan
"Security Events":   nv-perm.security-events
"System Config":     nv-perm.config
"Vulnerability Profile":     nv-perm.vulnerability

 
//---> for Rancher Project Role Template page
api.neuvector.com   // apiGroup for NeuVector

 
[resource display]   [resource]
--------------------------------------------------
"All Permissions":   nv-perm.all-permissions
"Audit Events":      nv-perm.audit-events
"Authorization":     nv-perm.authorization
"Compliance":        nv-perm.compliance
"Events":            nv-perm.events
"Registry Scan":     nv-perm.reg-scan
"Runtime Policy":    nv-perm.rt-policy
"Runtime Scan":      nv-perm.rt-scan
"Security Events":   nv-perm.security-events
"System Config":     nv-perm.config

nv-perm.fed is not supported for Rancher Project Role Template

------

nv-perm.all-permissions resource with * verb on Rancher Global Role :
  (1) mapped to NV fedAdmin role on NV fed-master cluster  // it means customer cannot map a Rancher Global Role to NV admin role if that NV is master cluster
  (2) mapped to NV admin role on NV fed-managed cluster

------
nv-perm.all-permissions resource with * verb on Rancher Cluster Roles :
  always mapped to NV cluster admin role
------
nv-perm.all-permissions resource with * verb on Rancher Project Roles :
  always mapped to NV namespace admin role

**Comment by gaktive** [comment]
This may eventually be tied to a NV extension that could populate the list for the UI.

**Comment by nwmac** [comment]
This should be a case of adding these to `globalScopedApiGroups`, `clusterScopedApiGroups` and `projectScopedApiGroups` in `shell/config/roles.ts`
