### ISSUE TITLE
Fleet status on local cluster dashboard shows red 

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#11181]
See below:

![image](https://github.com/rancher/dashboard/assets/1955897/7010faf9-f1b2-438a-95df-c7536cf138bb)

Fresh 2.9-head install, explore the local cluster - Fleet shows up red.

**Comment by nwmac** [comment]
Okay - this is a timing issue, it takes quite a while for Fleet to come up

**Comment by gaktive** [comment]
We may have to look at this for 2.10 and then backport to 2.9.x if we run out of time.

**Comment by richard-cox** [comment]
We should be able to determine the initial in progress state by checking the target resource's `metadata.state.transitioning`
