### ISSUE TITLE
After the project is packaged and deployed to the production environment, the physical path can be viewed in the browser, source code/source section. How to avoid the physical path in the JS file???

### ISSUE THREAD

**Issue by lander123** [rancher/dashboard#11180]
After the project is packaged and deployed to the production environment, the physical path can be viewed in the browser, source code/source section. How to avoid the physical path in the JS file???
![image](https://github.com/rancher/dashboard/assets/26194690/a2963c4a-5ef1-42c5-bbe0-c3662abb0747)

**Comment by richard-cox** [comment]
What branch are you building from, and how are you building the UI?

Would you be able to expand on why you need to build it locally?

**Comment by richard-cox** [comment]
No additional information, closing.
