### ISSUE TITLE
Text is not placed correctly in Cron Job --> Scaling/Upgrade policy

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1119]
**On master-head - commit id: `5e1b21b93`**

- Cluster Explorer --> Job --> Create --> Scaling/Upgrade policy --> Enter data
<img width="1106" alt="Screen Shot 2020-08-27 at 10 27 00 AM" src="https://user-images.githubusercontent.com/26032343/91475130-0230c600-e850-11ea-896a-0a38521d593f.png">

**Expected:**
Entered text in the input fields - Completions, Parallelism, Back off Limit, Active Deadline should appear in the middle.

**Comment by lvuch** [comment]
this is a js issue @vincent99 is fixing

**Comment by sowmyav27** [comment]
**On master-head commit id: `c428bc9`**

- Cluster Explorer --> Job --> Create --> Scaling/Upgrade policy --> Enter data
- Data is available in the middle of the input text field
<img width="1439" alt="Screen Shot 2020-09-01 at 11 46 18 AM" src="https://user-images.githubusercontent.com/26032343/91893367-db580280-ec48-11ea-81e6-738952533d67.png">
