### ISSUE TITLE
EKS cluster edit is not working 

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#11199]
**Setup**
- Rancher version: v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
- Browser type & version: Version 123.0.6312.107 (Official Build) (arm64)

**Describe the bug**
Once you try to edit an existing EKS cluster, the save button in the UI is locked for all the settings, until you change the cluster name. Once the user changes the cluster name and hit save, the UI displays an error message: `{"data":""}` and an internal server error 500 is shown in the console

**To Reproduce**
1- From the rancher dashboard, go to Clusters Management > Create > Amazon EKS
2- Create an EKS cluster 
3- While the cluster is provisioning, try to edit the cluster config via the UI
4- Change the values of all the fields available for edition, except the cluster name
5- Then, change the cluster name and hit the Save button
6- Observe the error output displayed in the UI

**Result**
The Save button is just enabled in the UI if the user changes the cluster name. For changes in any of the other fields, the Save button remains locked. Once, the user changes the cluster name, and hit save, an error occurs.

**Expected Result**
The save button should be available for every single change made in the cluster config and any changes must be successfully saved.

**Screenshots**

https://github.com/rancher/dashboard/assets/70187881/7fa744e0-c94a-498a-bf62-05aa46d15759

<img width="1670" alt="Screenshot 2024-06-07 at 7 41 10 PM" src="https://github.com/rancher/dashboard/assets/70187881/f99f58ae-c1a7-4b5a-ac0e-adf6e8a21085">

**Comment by mantis-toboggan-md** [comment]
Per offline conversation, there seems to be a backend issue here where `<normanCluster>.name` is set as expected but `<normanCluster>.eksConfig.displayName` is not set. From the UI side, the fix will be to ensure if `<normanCluster>.eksConfig.displayName` is empty, the name input in the form reflects that: in this case the save button will still be disabled, but the user will see why.

**Comment by yonasberhe23** [comment]
unit test coverage is sufficient. moving to done
