### ISSUE TITLE
Random [ character in kubernetes version - EKS 

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#11195]
**Setup**
- Rancher version: v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
- Browser type & version: Version 123.0.6312.107 (Official Build) (arm64)

**Describe the bug**

When creating a EKS cluster,  there's a random [ character in kubernetes version 

**To Reproduce**

1- Deploy Rancher
2- From the UI, go to Clusters Management > Select Amazon EKS
3- Observe the [ character in the kubernetes version field

**Result**
 there's a random [ character in kubernetes version 

**Expected Result**
We should not have any special characters in this field

**Screenshots**
<img width="1622" alt="Screenshot 2024-06-06 at 9 26 55 AM" src="https://github.com/rancher/dashboard/assets/70187881/4af08c32-e13b-4de8-a9df-6339546f167f">

**Comment by gaktive** [comment]
In https://github.com/rancher/dashboard/blob/master/pkg/eks/assets/data/eks-versions.js, there's a typo:

```
export default ['[1.29',

  '1.28',

  '1.27',

  '1.26',

  '1.25'];
```

**Comment by yonasberhe23** [comment]
unit test is sufficient. moving to done cc: @izaac
