### ISSUE TITLE
[v2.9] Editing GKE cluster loads Create form

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#11204]
**Setup**
- Rancher version: v2.9-3142335ab9b375b6e2c26270f80a4bcb727bd652-head
- Rancher UI Extensions: master 75ffa34
- Browser type & version: Firefox

**Describe the bug**

Editing the GKE cluster loads `Create` GKE form instead of the edit form.
**To Reproduce**

1. Create GKE cluster.
2. Go to `Edit Config` page to edit the GKE cluster.

**Result**
The Edit form does not load.
**Expected Result**

The edit form should be loaded.
**Screenshots**

[Screencast from 06-10-2024 06:57:18 PM.webm](https://github.com/rancher/dashboard/assets/11015077/93ceb9c8-0d58-4e19-b7e7-bd04d9a1d9d0)

**Additional context**

**Comment by richard-cox** [comment]
Would you know if this happens in previous versions of Rancher?

GKE pages are currently being ported to the new ui (rather than embedded old ui).

**Comment by valaparthvi** [comment]
>Would you know if this happens in previous versions of Rancher?

If you mean, 2.8, it works fine there. I am not sure about previous 2.9 versions though, this is the first time I have used 2.9.

**Comment by nwmac** [comment]
@mantis-toboggan-md I know we are migrating GKE - but would like to get to the bottom of what changed here and make sure we haven't broken something else.

**Comment by nwmac** [comment]
You'd need to run the UI in dev and disable the new Vue port of GKE - this should mean the old Embedded UI is used for GKE.

Goal is to understand why the create form loads for edit - in case there is a bug that effects other providers.

**Comment by valaparthvi** [comment]
Tested this again on Rancher (v2.9-4c5e874add231b925aaf9f3dca894725eb2a5225-head), Dashboard (master bd70d4c) and it works. It works for all GKE, EKS and AKS. Edit form loads when it should.

**Comment by nwmac** [comment]
Moving to done on the basis the original reported has validated this is no longer an issue.
