### ISSUE TITLE
[v2.9] EKS: Nodegroup name is hard-coded while adding new one

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11202]
**Setup**
Rancher version: `v2.9-3142335ab9b375b6e2c26270f80a4bcb727bd652-head`
Browser type & version: Chrome latest

**Describe the bug**
EKS (Vue UI): Nodegroup name is hard-coded while adding new one - group2, group3, etc.

**To Reproduce**
- Create EKS cluster from Rancher UI with one Nodegroup and custom name
- Edit the cluster and add new nodegroup

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/4190de9a-7de4-4085-ac1a-3f6012cfc4fc)

**Comment by yonasberhe23** [comment]
unit tests are sufficient. moving to done.

also did a quick check and this is no longer an issue.
