### ISSUE TITLE
Cluster Dashboard: Resource Search: Sortable table does not load properly when user selects option from resource search modal

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#11210]
**Setup**
- Rancher version: 2.9-head
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
Sortable table does not load properly when the user selects an option from the resource search modal. The behavior is as follows: 
After the user selects the option, the sortable table does not load, then the page reloads automatically, and then the sortable table loads properly. `Error in fetch(): Error: Network Error` is thrown in the console. This behavior is not seen in 2.8.

**To Reproduce**
1. go to Cluster Dashboard
2. from the header actions click the search icon
3. select any option from the list
4. notice the resource data doesn't load until the page reloads automatically

**Result**
The sortable table does not load until the page reloads automatically.

**Expected Result**
The sortable table loads immediately after the user selects an option from the resource search modal.

**Screenshots**

https://github.com/rancher/dashboard/assets/127343932/02503669-25e1-4ff4-85ef-47eebea8c191

**Additional context**

**Comment by richard-cox** [comment]
I think this is a duplicate of https://github.com/rancher/dashboard/issues/10869

**Comment by yonasberhe23** [comment]
oh thanks @richard-cox. i'll close this out
