### ISSUE TITLE
Input Fields not available for a Cron Job

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1121]
**On master-head - commit id: `5e1b21b93`**

`Successful Job History Limit` and `Failed Job History Limit` and `Suspend` fields are not available in "Create"/Define Container section for a Cron Job

**Comment by mantis-toboggan-md** [comment]
These fields are in the 'Scaling/Upgrading' section; they aren't part of the container spec

**Comment by sowmyav27** [comment]
Successful Job History Limit and Failed Job History Limit and Suspend fields are available in the Scaling/Upgrade policy section of the workload.
Closing this issue.
