### ISSUE TITLE
Bad path indentation on yaml when creating GitRepo on 2.9

### ISSUE THREAD

**Issue by mmartin24** [rancher/dashboard#11225]
**Setup**
- Rancher version: `v2.9-03e149351b6877d02ffe6f32be8b896708132f08-head`
- Rancher UI Extensions:
- Browser type & version: `Brave v1.66.118`

**Describe the bug**
When creating a GitRepo, if we try to edit using `Edit Yaml` we will se how the indentation is broken for path.

**To Reproduce**
- Deploy Rancher `2.9-head`
- Go to Continuous Delivery > Git Repos > fleet-local > Add Repository
- Give any name and add any data with a valid URL and Path; I used this:
```
URL: https://github.com/rancher/fleet-test-data
PATH qa-test-apps/nginx-app
```
- Click "Edit YAML"

**Result**
Indentation on `path` is wrong, and the YAML is not valid.

Is this:
```yaml
spec:
  paths: - qa-test-apps/nginx-app
```
![ko_indent](https://github.com/rancher/dashboard/assets/37271841/ffa74d1c-d20c-4296-a52f-8afef41b5f38)

**Expected Result**
Should be this one:
```yaml
spec:
  paths: 
    - qa-test-apps/nginx-app
```
![ok_indent](https://github.com/rancher/dashboard/assets/37271841/961aac1f-f8ae-423c-a24d-2e83207a3f2a)

**Screenshots**
Video showing this:

[Screencast from 13-06-24 16:17:47.webm](https://github.com/rancher/dashboard/assets/37271841/3493f8c9-a654-47f7-a36f-216bae8ce39c)

**Additional context**
Even after deploying correctly the repo, if we go again to 'Edit config' and try again 'Edit YAML' the problem will occur again.
Note, this was ok in 2.8

**Comment by richard-cox** [comment]
Probably connected to https://github.com/rancher/dashboard/issues/11020, waiting for backend to confirm if their fix also resolves these

**Comment by mmartin24** [comment]
> Probably connected to #11020, waiting for backend to confirm if their fix also resolves these

Thanks @richard-cox. Could also this one be connected?: https://github.com/rancher/dashboard/issues/11226

**Comment by richard-cox** [comment]
Following backend changes, i tried to reproduce in `v2.9-a84c3a2f` and could not. 

We just need to write some automation to prevent regression, or for quicker resolution change to manual QA.

**Comment by mmartin24** [comment]
Manually checked on `v2.9-67919adde96b1258a6df72919b36c5c4cb4cfde4-head` and looks ok.
I created also an automation ticket on my side which should not be difficult to automate for this. 
Let me know if this is sufficient for  you or want to add more tests on UI side. Otherwise, I can close.

**Comment by richard-cox** [comment]
Your manual QA works, thank you!

Would you be able to link that automation ticket here as well, then i think we can close this one

**Comment by nwmac** [comment]
QA'd by Fleet QA

**Comment by mmartin24** [comment]
> Your manual QA works, thank you!
> 
> Would you be able to link that automation ticket here as well, then i think we can close this one

@richard-cox ,  automation implemented [here](https://github.com/rancher/fleet-e2e/pull/166) (linked to ticket above: https://github.com/rancher/fleet-e2e/issues/163)
