### ISSUE TITLE
[BUG] Node driver cluster type changes to Custom cluster after editing the config as yaml.

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/dashboard#11238]
**Setup**
- Rancher version: v2.9.0-alpha5
- Rancher UI Extensions:
- Browser type & version: Firefox

**Describe the bug**
Node Driver cluster type changes to Custom Cluster after editing the config as yaml and creating cluster.

**To Reproduce**
1. Create a rancher server v2.9.0-alpha5
2. Try creating Amazon EC2 Node Driver RKE2 cluster for AWS Out of Tree cloud provider testing by following [these steps](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon).
3. Follow the instructions to edit config as yaml.
4. Once the config is ready, create a cluster.

**Result**
1. RKE2 Node Driver cluster type changes to Custom Cluster.

**Expected Result**
RKE2 Node Driver cluster provisions successfully with Amazon Cloud Provider.

**Comment by richard-cox** [comment]
@vivek-shilimkar Would you know if this is a regression in 2.9.0?

**Comment by nwmac** [comment]
If this is not a regression, we should push it to 2.9.next1 @gaktive

**Comment by nwmac** [comment]
@gaktive Need someone to determine if this is a regression and take a look if it is.

**Comment by rak-phillip** [comment]
@vivek-shilimkar I'm not able to repro this behavior on either v2.9-head(`v2.9-a57f7025abdd80a2912f7fe53247ef7e1d4993de-head`) or v2.8-head(`v2.8-d7d0d9d854247d61f4018728e9a414cecf4fbb0e-head`). Do you have a more in-depth reproduction example that I can use?

**Comment by nwmac** [comment]
@vivek-shilimkar We can not reproduce - please check and if you are still able, please update this issue with more detailed instructions.

FYI @gaktive

**Comment by vivek-shilimkar** [comment]
Retested the issue. Issue is not reproducible. I may removed or changed the fields in the YAML unintentionally. 
Since the issue doesn't exists, closing the issue.
