### ISSUE TITLE
UI for backup-restore-operator ResourceSet CRD

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#1123]
Clusterscoped resource
Allows you to specify the set of resources to be included in a backup. This must be passed to the Backup CRD defined [here](https://github.com/rancher/dashboard/issues/1124).

Header / Label Name | k8s YAML | Input | Default | Required
-- | -- | -- | -- | -- 
ResourceSelectors | resourceSelectors | Array of ResourceSelector (defined below) | nil | ✅ 
ControllerReferences | controllerReferences | Array of ControllerReference (defined below) | nil | ✅ 

**ResourceSelector**
The following fields together specify a ResourceSelector, and an array of such resource selectors is the input to ResourceSet.ResourceSelectors field above ("ind" in the following table is to denote the index in an array)
Header / Label Name | k8s YAML | Input | Default | Required
-- | -- | -- | -- | --
ApiVersion | resourceSelectors[ind].apiVersion | String | nil | ✅ 
Kinds | resourceSelectors[ind].kinds | Array of strings | nil
KindsRegexp | resourceSelectors[ind]. kindsRegexp | String | nil
ResourcesNames | resourceSelectors[ind].resourceNames | Array of strings | nil
ResourceNameRegexp | resourceSelectors[ind].resourceNameRegexp | String | nil
Namespaces | resourceSelectors[ind].namespaces | Array of strings | nil
NamespaceRegexp | resourceSelectors[ind].namespaceRegexp | String | nil
LabelSelectors | resourceSelectors[ind].labelSelectors | See LabelSelector below | nil

**LabelSelector**
UI for a [k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector](https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#labelselector-v1-meta)

Default is nil. If nil, this should submit {}.
Header / Label Name | k8s YAML | Input | Default
-- | -- | -- | --
Match Labels | *.matchLabels | key: value inputs | nil
Match Expressions | *.matchExpressions | key: Stringoperator: Dropdown (In, NotIn, Exists and DoesNotExist)values: List of Strings. Only required to have at least one element if operator is In or NotIn, otherwise disabled. | nil

**ControllerReferences**
The following fields together specify a ControllerReference, and an array of such controller references is the input to ResourceSet.ControllerReferences field above ("ind" in the following table is to denote the index in an array)
Header / Label Name | k8s YAML | Input | Default
-- | -- | -- | --
ApiVersion | resourceSelectors[ind].apiVersion | String | nil
Resource | resourceSelectors[ind].resource | String | nil
Namespace | resourceSelectors[ind].namespace | String | nil
Name | resourceSelectors[ind].name | String | nil

**Comment by lvuch** [comment]
https://xd.adobe.com/view/04a164f0-7ec4-43d3-b6c3-bf0e7ee426d5-51f2/

**Comment by deniseschannon** [comment]
Waiting for backup/restore operator to extend to back up other apps before looking into this

**Comment by catherineluse** [comment]
Closing this issue because the backup/restore operator doesn't extend to other apps. If plans change, this issue can be reopened.
