### ISSUE TITLE
Modal for deleting a POD treats success as failure

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11247]
**Setup**
- Rancher version: 2.9.0 (pre release)

**Describe the bug**
- The modal shown to confirm deletion of a pod has an async button
- On pressing it for delete the api call is made
- Even when this succeeds the modal remains and the button changes to Error

**To Reproduce**
- Create a simple pod (any name, image nginx)
- Find the pod in the pods list and use the three dot menu to delete
- Click delete in the modal

**Result**
- API request succeeds but modal remains, button shows `Error` text

**Expected Result**
- On failure to delete the failure is shown in the modal
- On delete success the modal is closed

**Additional context**
- Deleting other resources like configmaps, secrets, deployments, etc work fine

**Comment by yonasberhe23** [comment]
e2e test is sufficient. moving to done
