### ISSUE TITLE
Extension Gitlab pipeline fails to build due to outdated nodejs and openssl packages

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#11240]
**Setup**
- Rancher version: v2.9-head
- Rancher UI Extensions: N/A
- Browser type & version: N/A

**Describe the bug**

When using the provided `.gitlab-ci.yml` pipeline file for an extension, the build will fail with:

<details open>

```console
$ npm install -g --unsafe-perm yarn
/usr/bin/node14: symbol lookup error: /usr/bin/node14: undefined symbol: RSA_get0_pss_params, version OPENSSL_1_1_1d
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit code 1
```

</details>

**To Reproduce**

- Create a new repository on gitlab.com
- Within the repository create a new extension with the `-l` [option](http://extensions.rancher.io/extensions/extensions-getting-started#extension-options) to include the gitlab pipeline file
- Follow the [extension quickstart](http://extensions.rancher.io/extensions/extensions-getting-started#extension-options) to build a top-level extension
- Push the extension to the new gitlab repository

**Result**
The `build_catalog` stage will fail.

**Expected Result**

The pipeline should succeed and the catalog image should be pushed to the specified registry.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by rak-phillip** [comment]
Validated that both the `check_version` and `build_catalog` jobs complete in gitlab.
