### ISSUE TITLE
UI for backup-restore-operator Restore CRD 

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#1125]
In order to restore from backup, user needs to create an instance/CR for the Restore CRD. When a restore CR is created, the restore controller will start restoring from whichever backup file is specified in it
Header / Label Name | k8s YAML | Input | Default | Required
-- | -- | -- | -- | --
BackupFilename | spec.backupFilename | String | nil | ✅ 
StorageLocation | spec.storageLocation | See StorageLocation (defined below) | nil
Prune | spec.prune | Boolean | True
DeleteTimeoutSeconds | spec.deleteTimeoutSeconds | Integer | 10
EncryptionConfigName | spec.encryptionConfigName | String | nil

**StorageLocation**
Header / Label Name | k8s YAML | Input | Default
-- | -- | -- | --
S3 | spec.s3 | See S3ObjectStore | nil

**S3ObjectStore**
Header / Label Name | k8s YAML | Input | Default
-- | -- | -- | --
Endpoint | spec.s3.endpoint | String | nil
EndpointCA | spec.s3.endpointCA | String | nil
InsecureTLSSkipVerify | spec.s3.insecureTLSSkipVerify | Boolean | nil
CredentialSecretName | spec.s3.credentialSecretName | String | nil
BucketName | spec.s3.bucketName | String | nil
Region | spec.s3.region | String | nil
Folder | spec.s3.folder | String | nil

The `EncryptionConfigName` field on Restore spec is the name of a Kubenetes secret, that contains an encryptionConfig file. If the backup that this Restore CR references was created with encryption enabled, the same encryptionConfig file must be used wile creating restore CR too, else restore will fail. We should add a message above this field that tells the user to use a secret containing the same encryption Config file, that was used while taking a backup

**Comment by lvuch** [comment]
https://xd.adobe.com/view/e9b63976-4c29-431d-ba8b-f56df2237393-bce5/

**Comment by mrajashree** [comment]
The `EncryptionConfigName` field is the name of a Kubenetes secret, that contains an encryptionConfig file. If the backup that this Restore CR references was created with encryption enabled, the same encryptionConfig file must be used wile creating restore CR too, else restore will fail. We should add a message above this field that tells the user to use a secret containing the same encryption Config file, that was used while taking a backup

**Comment by mrajashree** [comment]
On master-head 6a6f13cec

1. I created a backup that uses the default storage location. When I go to create Restore CR using the form, it shows up in the "Target Backup" dropdown but I can't select it. I also see this error in console.
<img width="1413" alt="Screen Shot 2020-09-11 at 11 38 48 AM" src="https://user-images.githubusercontent.com/10672776/92961376-fcc4a580-f423-11ea-887f-2ea86adfff28.png">
However I'm able to select a backup CR that had s3 details on it

2. Selecting an existing backup is not populating the Backup Filename field

3. I think the header "Storage Location" should be renamed to "Backup Source" for restores

4. If the third radio button under Storage Location (Backup Source) `Use the s3 location specified on the Backup CR` is selected, the fields for s3 should be populated with the fields on the "Target Backup". Whereas right now they show up as empty fields for the user to fill out
<img width="1188" alt="Screen Shot 2020-09-11 at 11 48 05 AM" src="https://user-images.githubusercontent.com/10672776/92961889-e9660a00-f424-11ea-925b-67210cdebe94.png">

These fields should be filled by user only if they select the second option.

5. Nit: Can the `s` in `s3` be in uppercase for `Use the s3 location specified on the Backup CR` since it is uppercase in the second option

**Comment by deniseschannon** [comment]
Let's change the UX/layout of this so it's a little more obvious what our options are about where we are restoring. 

1. There will be 3 options at the top to select where you want to restore from: 

- Radiobutton option 1: An existing backup config. 
  - If there are any backups available, this should be the default option.
  - If there is only 1 backup available, automatically select that backup if this option is selected. 
  - If there are no backups, disable this option and use the "default storage location" as the default selected.
  - Let's not attempt to display the S3 config for the selected backup. Let's just select the backup.  

<img width="563" alt="Screen Shot 2020-09-11 at 10 21 17 PM" src="https://user-images.githubusercontent.com/11410997/92988069-26f68180-f47d-11ea-8081-6073c495c888.png">

- Radiobutton option 2: The default storage target

<img width="559" alt="Screen Shot 2020-09-11 at 10 22 03 PM" src="https://user-images.githubusercontent.com/11410997/92988074-3d9cd880-f47d-11ea-9d76-44abadd38fc7.png">

- Radiobutton Option 3: A S3-compatible object store

<img width="558" alt="Screen Shot 2020-09-11 at 10 22 38 PM" src="https://user-images.githubusercontent.com/11410997/92988083-50afa880-f47d-11ea-99ae-688c5cb75c23.png">

2. For Delete Timeout, can we get text to describe it to put into an info bubble? @mrajashree 

3. For Prune, it should not be enabled by default. Can we move the text into an info bubble? Not sure if we have an example of info bubble for a checkbox, but let's try it. 

4. For Encryption Config Secret, only show this if the backupfilename indicates it's encrypted. If the filename indicates it's encrypted, show this field and the warning under that dropdown? Let's play aorund with where that warning should go.

**Comment by mrajashree** [comment]
> For Delete Timeout, can we get text to describe it to put into an info bubble?

During prune (deleting resources), some resources can get stuck in "Terminating" if they have finalizers set. So after "Delete Timeout" seconds, operator will again attempt to delete the resources and this time it will remove the finalizers.

So how about this as a text:
Time after which resources will get force-deleted (even if they have finalizers)

> For Prune, it should not be enabled by default. 

But prune should be true by default, are you saying we should use something else to represent this?

**Comment by mrajashree** [comment]
on master-head sept 21

Same as backup, selecting encryption option sets the `encryptionConfigName` yaml field, instead it should set `encryptionConfigSecretName`

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e9a98a323`**

PV using storage class is configured on the local EKS cluster.

**Issue#1**

- Create a couple of backups (one of the backups is in Error state)
- Create a restore CR
- From `Select Backup Source` -- select `An existing backup config`
- The target backup option lists the backup in error state also. 


**Expected:**
Erred backups should not be listed in the dropdown

**Issue#2**

- Create a recurring backup with retention count 10 and schedule - `@every 1m`
- Go to Restore page, select this recurring backup in the target backup dropdown.
- the user has to refresh for the latest recurring backup file to reflect in the dropdown of filename.

**Expected:**
User should be able to list the latest backup filename related to the recurring backup without a refresh of the page.

**Issue#3**
- Can these fields - Backup Filename, Prune and Delete timeout be better placed on the UI.? 
<img width="1408" alt="Screen Shot 2020-09-23 at 8 20 00 PM" src="https://user-images.githubusercontent.com/26032343/94097034-75d7db80-fdda-11ea-9055-ff2a64b1eb02.png">

**Issue#4**

- Create a backup
- Create a restore CR --> `Select Backup Source` -- select `An existing backup config` --> select a backup from dropdown
- Click on Create.
- The Restore CR is seen in the error state with error `failed to check s3 bucket:, err:Bucket name cannot be empty`
- Request sent has:

```
storageLocation: {s3: {}}
s3: {}
```
**Expected:**
S3 should not be sent in the request as the storage location

**Issue#5**

- Create a restore CR
- Restore CR is created. 
- Rancher is unreachable. when rancher is back up --> Edit as Form on the restore CR
- Original values are not displayed

**Issue#6**

- Create a restore CR
- Restore CR is created. 
- Rancher is unreachable. when rancher is back up --> Clone as Form on the restore CR
- Original values are not displayed in the page

**Issue#7**

- Create a restore CR
- Restore CR is created. 
- Rancher is unreachable. when rancher is back up. Click on the restore CR created
- `Select Backup Source` is selectable

<img width="876" alt="Screen Shot 2020-09-23 at 9 33 30 PM" src="https://user-images.githubusercontent.com/26032343/94101558-e8e64f80-fde4-11ea-918c-e0ae00d60548.png">

**Expected:**
`Select Backup Source` should not be selectable. Selected values must be shown

**Comment by sowmyav27** [comment]
Logged separate issues for these mentioned https://github.com/rancher/dashboard/issues/1125#issuecomment-698106914

1. https://github.com/rancher/dashboard/issues/1385
2. https://github.com/rancher/dashboard/issues/1386
3. https://github.com/rancher/dashboard/issues/1387
4. https://github.com/rancher/dashboard/issues/1389
5. https://github.com/rancher/dashboard/issues/1390
6. https://github.com/rancher/dashboard/issues/1391
7. https://github.com/rancher/dashboard/issues/1392

**Comment by deniseschannon** [comment]
Going to close this in favor of each individual issue.
