### ISSUE TITLE
[Logging V2] ClusterFlow CRD Page

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1126]
Overview Page
This tab should just contain a description of what a cluster flow is.  @paynejacob will write this section and attach it to this ticket.

CRD Docs
The crd fields can be found here: https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/clusterflow_types/

The only section we need to implement is the Logging Output Ref section.  Users should be able to check what outputs to enable.

Mockup
![flow](https://user-images.githubusercontent.com/12258347/91493626-71b4ae80-e86c-11ea-8e00-5f8f045f4dd5.png)

**Comment by paynejacob** [comment]
Overview Text: "A ClusterFlow defines what outputs to direct logs to for the cluster."

**Comment by deniseschannon** [comment]
- [ ] No Overview tab
- [ ] Outputs tab should be "Cluster Outputs" and it should be a list of all available ClusterOutputs that can be selected. 

@paynejacob How/where does this get configured in the yaml?

**Comment by paynejacob** [comment]
globalOutputRefs, this should be an array of cluster ouptut names

https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/clusterflow_types/

**Comment by paynejacob** [comment]
Clusterflows should only be deployable in the cattle-logging-system namespace.  Any other namespace will render them inert.

**Comment by paynejacob** [comment]
Cluster flows should require at least one output otherwise they are useless.

**Comment by paynejacob** [comment]
@codyrancher https://github.com/rancher/charts/pull/608 was merged.  All `outputRefs` keys should be changed to `globalOutputRefs`.

**Comment by izaac** [comment]
I have a ClusterFlow with three globalOutputRefs but I don't see any of them rendered in the CRD page

![Screen Shot 2020-09-19 at 1 09 30 PM](https://user-images.githubusercontent.com/27659/93688311-b998b100-fa79-11ea-9081-bd8c8566538e.png)

Rancher version `master-head (09/19/2020)` _bd88c23_

**Comment by izaac** [comment]
Rancher version: `master-head (09/22/2020)`  _0ccce45_ HA k8s 1.19 with Downstream RKE DO

**ClusterFlows** list, create, edit and details are matching the mockup. Initial E2E checks done using simple ClusterOutput
