### ISSUE TITLE
[backport v2.9.x] Allow users to easily see expiring harvester cloud credentials and to renew them

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11270]
Epic: https://github.com/rancher/dashboard/issues/11256 SURE-8516

Requires expiring label on cloud cred

- Global notification somewhere warning of expired / soon to expire harv cloud creds
- Clearly see in cloud cred table expired / soon to expire (see cluster dashboard certs list for pattern?)
  - Column for sorting, only if harv cloud cred present?
- Sub row in harv clusters list to warn that cluster has a cloud cred that's expiring
- Cloud Cred bulk action to renew (recreate kubeconfig, update cloud cred)

Edit: Blocked on https://github.com/rancher/rancher/issues/47243

**Comment by gaktive** [comment]
This needs to line up with Harvester 1.4.0 which is set to come out for 2.10.0.

**Comment by gaktive** [comment]
Pushing out of the September releases but this has to get in for October.

@richard-cox what is this blocked on again? The parent epic points in a few ways so it's not easily clear.

**Comment by richard-cox** [comment]
This is blocked on `RFC 010 Harvester Node Driver Credentials`. I couldn't directly link that to a gh issue or PR, or JIRA though. @jakefhyde can you confirm the RFC functionality will come in via SURE-8516 / https://github.com/rancher/rancher/issues/44912?

**Comment by gaktive** [comment]
RFC 010 approved but 44912 is now unassigned and off the Hostbusters board. Checking which r/r team can take care of this.

**Comment by irishgordo** [comment]
@richard-cox thanks for this addition :smile: :+1:  -> I'm going to go ahead and close this out as this has already been validated in:

- https://github.com/rancher/rancher/issues/47492#issuecomment-2412131230
( Havester v1.3.2 & (Rancher v2.9.3-alpha5 & Rancher v2.9-head (v2.9-9fa98c1a0843dbee3d8ea9ffc2e84a891f2696c3-head) ) )

cc: @khushboo-rancher @bk201

**Comment by LucasSaintarbor** [comment]
> Release note suggestion
> 
> In the Cloud Credential list users can now easily see if a Harvester Credential is about to or has expired and opt to `Renew` it. The Cluster Management Clusters list will also notify when an associated Harvester Cloud Credential is about to or has expired.
> 
> Edit: @LucasSaintarbor Can we update the above to...?
> 
> In the Cloud Credential list users can now easily see if a Harvester Credential is about to or has expired and opt to `Renew` it. The Cluster Management Clusters list will also notify when an associated Harvester Cloud Credential is about to or has expired.
> 
> On upgrade existing expired Harvester Credential will not contain a warning. Users can though still `Renew` their token via the resource's menu.

@richard-cox Thanks for the feedback. I made an update to the RNs here: [1aa6002](https://github.com/rancherlabs/release-notes/pull/414/commits/1aa600221941954c0480347935e36106b699a2e5). Does this work? Thanks!
