### ISSUE TITLE
[Logging V2] Flow CRD Page

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1127]
Overview Page
This tab should just contain a description of what an flow is.  @paynejacob will write this section and attach it to this ticket.

CRD Docs
The crd fields can be found here: https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/flow_types/

The only section we need to implement is the Logging Output Ref section.  Users should be able to check what outputs to enable.

Mockup
![flow](https://user-images.githubusercontent.com/12258347/91493626-71b4ae80-e86c-11ea-8e00-5f8f045f4dd5.png)

**Comment by paynejacob** [comment]
Overview Text: "A flow describes what outputs should receive logs in this namespace collected by loggings."

**Comment by paynejacob** [comment]
We should require at least one output for each flow, otherwise they are useless.

**Comment by paynejacob** [comment]
@codyrancher https://github.com/rancher/charts/pull/608 was merged.  All `outputRefs` keys should be changed to `localOutputRefs`.

**Comment by izaac** [comment]
I have a Flow with one Output configured but is not rendered in the Flow details

![Screen Shot 2020-09-19 at 1 09 22 PM](https://user-images.githubusercontent.com/27659/93688338-f369b780-fa79-11ea-8539-0b47888f5559.png)

```json
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"logging.banzaicloud.io/v1beta1","kind":"Flow","metadata":{"annotations":{},"name":"example-flow","namespace":"dummyapp-dev"},"spec":{"globalOutputRefs":["dev-team-a"],"localOutputRefs":["nsoutput1","nsoutput2"]}}
  creationTimestamp: "2020-09-19T20:10:35Z"
  generation: 1
  managedFields:
  - apiVersion: logging.banzaicloud.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:globalOutputRefs: {}
        f:localOutputRefs: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2020-09-19T20:10:35Z"
  name: example-flow
  namespace: dummyapp-dev
  resourceVersion: "6997"
  selfLink: /apis/logging.banzaicloud.io/v1beta1/namespaces/dummyapp-dev/flows/example-flow
  uid: a9ff5946-0b63-4ae0-ae83-d3d897c9ef50
spec:
  globalOutputRefs:
  - dev-team-a
  localOutputRefs:
  - nsoutput1
  - nsoutput2
```

Rancher version `master-head (09/19/2020)` _bd88c23_

**Comment by izaac** [comment]
Rancher version: `master-head (09/22/2020)`  _0ccce45_ HA k8s 1.19 with Downstream RKE DO

**ClusterFlows** list, create, edit and details are matching the mockup. Initial E2E checks done using simple ClusterOutput

**Comment by izaac** [comment]
Rancher version: `master-head (09/22/2020)`  _0ccce45_ HA k8s 1.19 with Downstream RKE DO

Reopening, I do not see `clusterOutputs` as an option to set Outputs in a Flow. According to the `Flows` documentation

> Outputs can be output or clusteroutput

**Comment by deniseschannon** [comment]
@paynejacob is that true? should we be allowing outputs and clusteroutputs?

**Comment by paynejacob** [comment]
Yes that should be true, this is new functionality that came with 3.6.0.  Outputs should go under `localOutputRefs` and cluster ouptuts should go under `globalOutputRefs`.

**Comment by codyrancher** [comment]
Since a clusteroutput can share a name with an output how do we want to distinguish the two within the dropdown?

**Comment by paynejacob** [comment]
Could we do a separate dropdown for each? That would match the fields better.

**Comment by codyrancher** [comment]
Sorry, not dropdowns but tables. And yeah we could do two separate tables.

**Comment by deniseschannon** [comment]
Closing as I want to capture all net new changes to flows/clusterflows in separate tickets.
