### ISSUE TITLE
Kubewarden-ui unit tests may pass in kubwarden-ui repo and fail in dashboard's check-plugins-build ci step

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#11288]
kubewarden-ui unit tests run in the dashboard ci process as part of check-plugins-build. Recently some kubewarden-ui tests that pass when run in kubewarden-ui ci (and locally) failed during dashboard ci, see  https://github.com/rancher/dashboard/actions/runs/9616946656/job/26527606192?pr=11286 for an example run. Before re-enabling this step of the test-plugins-build script we should figure out why tests would fail in one environment and not the other.

**Comment by aalves08** [comment]
@jordojordo I don't think we will ever be in a position to re-enable these because of the flakiness that this check would introduce to our pipelines. Wdyt? 🤔

**Comment by jordojordo** [comment]
@aalves08 We won't be able to for some time, once the unit tests are squared away on Kubewarden and other work is completed we may revisit this.
