### ISSUE TITLE
Namespace - Create/Edit

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#113]

**Comment by lvuch** [comment]
https://xd.adobe.com/view/e2eb11c5-31c1-44c3-6fd4-efa968becce1-94da/

**Comment by tfiduccia** [comment]
Need to add Details page.

**Comment by lvuch** [comment]
updated: https://xd.adobe.com/view/771eaaf3-8caf-44d3-5b8e-b5c97626cf7b-012f/

**Comment by lvuch** [comment]
updated per tani's notes in old link: https://xd.adobe.com/view/da2be087-8252-446d-64a0-6f440ef74779-ac1a/

**Comment by deniseschannon** [comment]
@lvuch if this is design complete, can you move it to next up?
