### ISSUE TITLE
[Monitoring V2 UI] Add RKE2 as a Cluster Type

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1130]
This issue specifies an update to the Monitoring V2 UI Basic Configuration from https://github.com/rancher/dashboard/issues/908 and Monitoring V2 UI Advanced Configuration (https://github.com/rancher/dashboard/issues/909)

### General

Add an field under the `Cluster Type` field for RKE2

If Cluster Type is RKE2, `rke2ControllerManager.enabled`, `rke2Scheduler.enabled`, `rke2Proxy.enabled`,  and `rke2Etcd.enabled` should all be true by default.

### Exporters

`Export Kube Scheduler Metrics`, `Export Kube Controller Manager Metrics`, `Export Kube Proxy Metrics`, and `Export Etcd Metrics` will need to also update the k8s YAML logic to also be able to point to rke2 fields (described above) based on the `Cluster Type`.

*Note for QA: We should test whether an RKE2 cluster uses the right exporters and is able to scrape metrics as expected after this change is merged. The targets specified should both show up on the Prometheus UI and #/# targets and the default Grafana Dashboards for these components should also be working as expected.*

- [x] Backend Changes: https://github.com/rancher/charts/pull/544

**Comment by westlywright** [comment]
Basic configuration is in review.

**Comment by westlywright** [comment]
There will be one small change to this. The cluster type is still RKE2 but the label will display `RKE Federal` (see [here](https://github.com/rancher/rancher/issues/28650))

**Comment by jiaqiluo** [comment]
The monitoring app is installed into the imported RKE2 cluster successfully. All parts are working as expected. 

Rancher version: master-e919796c808d0aa643cb3491581bffcd64cfbe56-head, HA installation 
RKE2 version: v1.18.8-beta19+rke2 

![image](https://user-images.githubusercontent.com/6218999/93147316-b8483c80-f6a5-11ea-80fd-296691681900.png)
