### ISSUE TITLE
User Retention Admin Interface

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11303]
As a Rancher Admin, I want to configure global user retention settings so that I can define when a user will get deactivated or deleted from Rancher after a not logging in for a given duration.

### Add a new button to the User Retention page

<img width="1513" alt="image" src="https://github.com/rancher/dashboard/assets/835961/b84bf641-5c8b-42e9-9f3c-8ec4268b0263">

#### Inputs disable without data

<img width="1515" alt="image" src="https://github.com/rancher/dashboard/assets/835961/72d0e642-23b5-4343-9e01-33dcd2ce1e85">

#### Form with data

<img width="1514" alt="image" src="https://github.com/rancher/dashboard/assets/835961/1ba6ef7f-0753-4d30-8e28-0d1621035b66">

**Comment by gaktive** [comment]
Backend QA assigned to the rancher/rancher ticket so UI QA should coordinate with them on where to help with testing.

**Comment by yonasberhe23** [comment]
there are e2e tests that perform basic navigation and form checks but we should expand on this to test whether a user account is disabled/deleted after a given inactivity period and to make sure users other than the admin have access to this setting. Here's a follow-up automation ticket https://github.com/rancher/qa-tasks/issues/1400

for 2.9 release we will need to manually test this feature until we can get further automation coverage. moving to To Test.

**Comment by IsaSih** [comment]
UI interface behaves as expected. However, the functionality does not work. Here are my findings:

1. For users who last logged in before the user retention is set, the cron job does not execute the disable/delete action.

https://github.com/rancher/dashboard/assets/70187881/e4ad830c-3d4f-4b4a-9ce3-f641962d697f

2. Also, the default timestamp for a user that doesn't have a last login date is not being displayed in the table

https://github.com/rancher/dashboard/assets/70187881/ccca8330-633d-471d-bc85-40f053682a72

3. For a user that last logged in after the user retention is set, when the countdown reaches 0 for both disable/delete fields, the table exhibits back the - and the actions to disable/delete the user are not performed at all

**Comment by rak-phillip** [comment]
@IsaSih we need to collect more information so that we could properly troubleshoot the behavior you are seeing. The UI is only setting and reading values from the backend, so we first need to confirm the values for the following settings:

- `user-retention-cron`
- `user-last-login-default'

> For users who last logged in before the user retention is set, the cron job does not execute the disable/delete action.

In the video that you posted, it looks like the "dry mode" option is active. Can you also validate the value for `user-retention-dry-run`? If this is active, users will not be automatically deactivated/deleted, but the Rancher backend will produce a log describing what it would have done if dry mode was disabled. 

![image](https://github.com/rancher/dashboard/assets/835961/88c52078-584e-4b90-a5f8-5d2e3f56da4e)

**Comment by yonasberhe23** [comment]
Tested in v2.9-1c2b815c8dd66e141b21630904127adc8e03c3de-head:

- user is disabled/deleted after a given inactivity period (single and multiple users) 
- only admin users have access to the settings
- The cron job schedule works as expected (there is a bit of a delay between when the cron job executes and when the user sees changes in the UI)
- dry-mode works as expected (no changes are applied to user records when it is toggled off)
- default last login - https://github.com/rancher/rancher/issues/46063
- User table
-- last login (populated when user logins into their account, see the above issue for default last login)
-- disable after (populated when inactivity period is set in settings and not in dry-mode)
-- delete after (populated when the inactivity period is set in settings and not in dry-mode)
