### ISSUE TITLE
User State Icons

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11309]
Replace existing user state strings with user icons to communicate if a user is enabled or disabled. 

### Current
![user-state-before](https://github.com/rancher/dashboard/assets/835961/74aece3c-117c-48ad-b82b-0ab0d966dbc4)

### Desired
![image](https://github.com/rancher/dashboard/assets/835961/cfa8a317-47c9-40aa-a72e-001d3a51aae8)

**Comment by yonasberhe23** [comment]
e2e tests are sufficient and also did a quick visual check. all looks good. moving to done
