### ISSUE TITLE
[Monitoring V2 UI] Update namespace from monitoring-system to cattle-monitoring-system

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1131]
This issue specifies an updates to the Monitoring V2 UI Advanced Configuration (https://github.com/rancher/dashboard/issues/909)

#### Limit Namespaces

All the logic here should use the new namespace `cattle-monitoring-system` instead of `monitoring-system`.

This change has been made in this [commit](https://github.com/rancher/charts/pull/507/commits/701098fd727f6dca10d9944cb947c1def642673d).

### Prometheus Adapter

The default `Prometheus URL` should be `http://rancher-monitoring-prometheus.cattle-monitoring-system.svc` due to the new namespace.

This change has been made in this [commit](https://github.com/rancher/charts/pull/507/commits/701098fd727f6dca10d9944cb947c1def642673d).

*Note to QA: we should check that the Prometheus Adapter works as expected and outputs some metrics to the custom Metrics API with the default deployment after this change goes in. I believe this can be done via `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1"` when using a kube config that directly access the cluster (so that it has the appropriate permissions)*

- [x] Backend Changes: https://github.com/rancher/charts/pull/507

**Comment by westlywright** [comment]
@aiyengar2 @deniseschannon I don't think we need this as a change ticket in the front end. The UI installer logic (vince wrote) uses the target namespace on the chart and the only place I am currently referencing the namespace directly is for some comparison logic in the [Alerting V2 UI Pr](https://github.com/rancher/dashboard/pull/1148) (not merged yet), which was already using the corrected namespace. AFAIKT there are no changes required in the UI.
