### ISSUE TITLE
Remove global `window.c` variable from Vue components

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11311]
Several components contain the following code in their mounted hooks:

```
mounted() {
  window.c = this;
}
```

This assigns the current vue component instance to a `window.c` variable. It's unclear as to why this was added to Dashboard and it's not a very good practice as global variables can be modified from anywhere in code.

### Expected outcome

- The `window.c` variable is removed from all Vue components
- If any functionality relies on the `window.c` variable, it is refactored to use a more controlled approach like emitting events or Vuex
- Dashboard behaves as expected and there are no regressions caused by removing `window.c`

### Additional information

Identified components using this pattern:

- shell/detail/provisioning.cattle.io.cluster.vue
- shell/list/provisioning.cattle.io.cluster.vue
- shell/pages/c/_cluster/apps/charts/index.vue
- shell/pages/c/_cluster/explorer/tools/index.vue
- shell/pages/c/_cluster/manager/drivers/kontainerDriver/index.vue
- shell/pages/c/_cluster/manager/drivers/nodeDriver/index.vue

**Comment by nwmac** [comment]
@rak-phillip My guess is this was added for developer debugging - there were other cases like this that I have previously removed - it only appears to be written to, so I would go ahead and remove.

**Comment by nwmac** [comment]
At least the last 2 are new - @eva-vashkevich may have added these and might have more information.

**Comment by eva-vashkevich** [comment]
I am removing it from the drivers pages in my drivers fixes PR. Shouldn't have added it.
