### ISSUE TITLE
Feature Flags: Infinitely Recursive Timeout in `waitForBackend()`

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11325]
`waitForBackend()` unconditionally invokes recursively, creating a scenario where the timeout continues to run even after the `close()` method was called.

## Steps to Reproduce

1. Trigger `waitForBackend()` by modifying a feature flag that requires a restart
2. Wait for the backend response

## Expected Behavior

When `close()` is invoked, it should stop `waitForBackend()` from making further API requests and clear any existing timeouts.

## Actual Behavior

`waitForBackend()` continues to make API requests and set up new timeouts even after `close()` is invoked.

## Proposed Solution

Add a condition to `waitForBackend()` to prevent the recursive call if `close()` has been invoked.

**Comment by eva-vashkevich** [comment]
No warnings or errors are shown on the console. Popup closes correctly.
https://github.com/rancher/dashboard/assets/133266076/befd1176-d6e5-4989-b7dd-16e58ddb42a6
