### ISSUE TITLE
[ Istio V2 ] Overview Page: Rancher-Monitoring documentation

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#1132]
Need to create a 'how to" similar to the "what / how blah blah blah" section here: https://xd.adobe.com/view/62ea899e-acc6-4b72-a654-9ecf811430a8-37b9/

Section Title: How to configure Rancher Monitoring integration

In a warning or highlighted section that is really obvious
```
 "If Ignore Namespace Selectors is set to true on your Rancher Monitoring instance, then Prometheus will not be able to scrape service mesh targets outside of Istio's namespace"
```

Body Text:
```
There are three different ways to configure Rancher’s Istio to ensure your service-mesh is available to Prometheus::

1. Set `Ignore Namespace Selectors` to false on your rancher monitoring instance
2. Keep the default setting for `Ignore Namespace Selectors` and add Service Monitors or Pod Monitors in the namespace with the targets you want to scrape. 
3. Keep the default setting for `Ignore Namespace Selectors` and add an `additionalScrapeConfig` to your rancher monitoring instance to scrape all targets in all namespaces. 

To get more detailed instructions on how to configure these options and what the security trade-offs would be, visit (insert link to rancher docs here that doesn't exist yet)
```

**Comment by cbron** [comment]
1. 

Can we change this: 
> “If Ignore Namespace Selectors is set to true on your Rancher Monitoring instance, then ServiceMonitors and PodMonitors will only be able to discover resources in the namespace they are deployed into”

To this: 
> “If Ignore Namespace Selectors is set to true on your Rancher Monitoring instance, then Prometheus will not be able to scrape service mesh targets outside of Istio's namespace”

And then include the part about service monitors in the body text. 

2. 
>There are three different ways to configure rancher monitoring to ensure your app data is being collected for use with the various istio addons:

to this: 
> There are three different ways to configure Rancher's Istio to ensure your app data is being collected for use with the various Istio integrations:

3. 
> to the namespaces that you have an app deployed to

to: 
> to the namespaces that have sidecar injection enabled

or something about "targets you want to scrape"...

**Comment by brendarearden** [comment]
@mantis-toboggan-md I made changes to the issue based on @cbron's comment.

**Comment by deniseschannon** [comment]
This issue has been superceded with https://github.com/rancher/dashboard/issues/1184
