### ISSUE TITLE
User Retention: Improve validation for `disable-inactive-user-after` and `delete-inactive-user-after` fields

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11333]
Setting an inactivity period to delete user accounts that is less than `336h0m0s` returns the error: 

```
admission webhook "rancher.cattle.io.settings.management.cattle.io" denied the request: value: Invalid value: "30h": must be at least 336h0m0s 
```

## Expected Behavior

The user retention form will not validate when known minimum values are not satisfied, alerting an admin that there is an issue with the form before they can submit.

## Actual Behavior

The user retention form passes validation, allowing an admin to submit the form with invalid values.

## Acceptance Criteria

- [ ] The user retention form does not validate if the inactivity period for deleting user accounts is set to a value less than `336h0m0s`
- [ ] When the inactivity period for deleting a user account is not valid, a clear and informative error message should be displayed, indicating the minimum allowed value
- [ ] The hint for inactivity period for deleting a user account is updated to reflect real values that satisfy form validation
- [ ] Disable and Delete after validate that the value is greater than `auth-user-session-ttl-minutes`
- [ ] Disable and Delete after validate that the duration format adheres to `{h|m|s}`
- [ ] Disable and Delete after disallow the use of fractional seconds in durations

**Comment by rak-phillip** [comment]
There might be other fields with well-defined minimum values that we can use for additional form validation. We need to collect more information to find out if we can enhance validation across the board.

**Comment by rak-phillip** [comment]
Updated the acceptance criteria based on conversation with @pmatseykanets on the topic of validation.

**Comment by izaac** [comment]
The updates to the E2E test data looks good to me for the purpose of validating the use case.
