### ISSUE TITLE
failure to fetch monitoring chart version

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#11341]
**Setup**
- Rancher version: v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head
- Local cluster RKE2 Kubernetes Version: v1.28.8 

**Describe the bug**
By trying to install rancher monitoring, the UI shows an error dialog:` failed to find chartName rancher-monitoring version 104.0.0+up45.31.1: NotFound 404`

**To Reproduce**
1- Try to install Rancher monitoring 104.0.0+up45.31.1 on local cluster 
2- Observe the error 404 in finding the rancher version
3- Deploy a downstream cluster 
4- Install Rancher monitoring in your downstream cluster

**Result**
For the local cluster:
Rancher monitoring version is 104.0.0+up45.31.1
![Screenshot 2024-07-02 at 4 01 19 PM](https://github.com/rancher/dashboard/assets/70187881/8247e35a-2766-44b6-990e-c655cd3713ab)

For a downstream cluster:
Rancher monitoring version is 103.1.1+up45.31.1
![Screenshot 2024-07-02 at 4 19 59 PM](https://github.com/rancher/dashboard/assets/70187881/afaf5d0f-8086-4c76-a5b9-d1439daac64c)

**Expected Result**
User must be able to install rancher monitoring with no errors in the local cluster. The versions of rancher monitoring should be the same for both the local and downstream clusters

**Comment by rak-phillip** [comment]
I don't get the error that you're seeing with `v2.9-a57f7025abdd80a2912f7fe53247ef7e1d4993de-head` that I deployed earlier this morning. 

## Local Cluster

The default monitoring version for the local cluster is `104.0.0+up45.31.1`, but the page renders without error:

![monitoring-local](https://github.com/rancher/dashboard/assets/835961/758341a4-5585-403d-82ad-6d1403eb1d2f)

Although, attempting to install the chart results in an error:

```
Error: YAML parse error on rancher-monitoring/charts/kube-state-metrics/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: line 25: mapping values are not allowed in this context
```

## Downstream Cluster

The default monitoring version is `104.0.0-rc1+up57.0.3`

![monitoring-local](https://github.com/rancher/dashboard/assets/835961/751726b1-145f-472d-b42a-29de98d3c4df)

The chart installs without issue.

**Comment by richard-cox** [comment]
Linking https://github.com/rancher/rancher/issues/45977

**Comment by richard-cox** [comment]
Linking https://github.com/rancher/charts/pull/4173

**Comment by richard-cox** [comment]
Given updates to 104.0.0-up45.31.1 this should be fixed

**Comment by igomez06** [comment]
Setup
Rancher version: v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head
Local cluster RKE2 Kubernetes Version: v1.28.8+rke2r1
Result
For the local cluster:
I was able to install  Rancher monitoring version is 104.0.0+up45.31.1 successfully with no 404 error

For downstream cluster:
I was able to install  Rancher monitoring version is 104.0.0+up45.31.1
