### ISSUE TITLE
Monitoring Alerts and Charts are broken following Grafana Bump

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11347]
**Setup**
- Rancher version: 2.9.0

**Describe the bug**

##### Monitoring Alerts
- The alerts resource is fetched via `/v1` endpoint that has been deprecated for a while
- After the latest chart bump (104.0.0+up45.31.1) it's no longer available
- v2 should be used instead
- @alexandreLamarre has confirmed we don't need to support both 1 and 2 and the same time, v2 should be supported in all supported monitoring chart releases

##### Charts
- Cluster, node and deployment metric charts get stuck on `loading`, charts never display

**To Reproduce**
##### Monitoring Alerts
- Install Rancher Monitoring Chart
- Navigate to cluster --> `Cluster` menu item --> Scroll to middle of page
- Click on the `Alerts` tab
- List is empty

##### Charts
- Install Rancher Monitoring Chart
- Navigate to cluster --> `Cluster` menu item --> Scroll down to bottom of page
- All three metrics tabs just showing the `loading` indicator instead of embedded grafana chart

**Additional context**
- Related https://github.com/rancher/rancher/issues/45977
- Currently blocked broken install of latest monitoring which contains grafana bump - fixed by https://github.com/rancher/charts/pull/4173, needs charts fix merge to be available?
  - Alternatively... the helm repo pre-releases can be enabled and the latest RC can be installed

**Comment by richard-cox** [comment]
Can successfully install 104.0.0-up45.31.1 and see charts. I'll leave the proper QA to a third party though

**Comment by rak-phillip** [comment]
Confirmed that monitoring alerts and charts render properly on a downstream cluster.
