### ISSUE TITLE
Unable to pass array into constraint parameter

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#1136]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

Create a cluster, navigate to dashboard, enable OPA gatekeeper.
Create a constraint in form view with parameters
Key:
`labels`
Value:
`["gatekeeper"]`

Result:
Creation errors with:
```
K8sRequiredLabels.constraints.gatekeeper.sh "labels2" is invalid: spec.parameters.labels: Invalid value: "string": spec.parameters.labels in body must be of type array: "string"
```
![Screen Shot 2020-08-28 at 10 39 39 AM](https://user-images.githubusercontent.com/57409052/91599732-987dee00-e91b-11ea-8718-c1d2a83c910b.png)

**Comment by izaac** [comment]
https://github.com/rancher/dashboard/issues/378 Is this a dupe of https://github.com/rancher/dashboard/issues/378 ?

**Comment by aaronRancher** [comment]
Closing in favor of #378
