### ISSUE TITLE
Fix GKE extension text and bump versions

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#11364]
Versions for built-in extensions are 0.1.0 and should be 1.0.0.

Text for GKE is not consistent with the others.

![image](https://github.com/rancher/dashboard/assets/1955897/846f1d1a-0cc3-40b7-8c5d-da8bcac13d28)

**Comment by yonasberhe23** [comment]
@mantis-toboggan-md should the Virtualization Manager extension also have a version of 1.0.0? 



![Image](https://github.com/rancher/dashboard/assets/127343932/6890be3b-3248-4ca6-9546-77dbb09c154f)

**Comment by mantis-toboggan-md** [comment]
Yeah that makes sense to me @yonasberhe23 - I've opened a new PR to do so

**Comment by yonasberhe23** [comment]
tested in v2.9-f188faae847b960d2f30cc89f4befc8ce5944f2c-head. 

<img width="1146" alt="Screenshot 2024-07-08 at 12 28 43 PM" src="https://github.com/rancher/dashboard/assets/127343932/7944641d-408d-4fb5-a7e5-cdebdfe47679">
