### ISSUE TITLE
Changes for Azure cloud provider for RKE2

### ISSUE THREAD

**Issue by kinarashah** [rancher/dashboard#11360]
Azure in-tree cloud provider has been removed for k8s >=1.30. We are adding docs on how to use `External` cloud provider for creating new Azure clusters and how to migrate from `Azure` to `External` cloud provider for k8s < 1.30. 

This currently works with `Edit as Yaml`, but need the following changes in UI: 
1. Remove `Azure` from cloud provider dropdown for RKE1 and RKE2 clusters `>= k8s 1.30`.
2. Allow changing cloud provider from `Azure` to `External` in dropdown for RKE1 and RKE2 clusters for `k8s >= 1.27 && k8s < 1.30` so users can migrate before upgrading to v1.30.

**Comment by kwwii** [comment]
We did this work for AWS already - check that PR to include the same banners informing users of the necessity to upgrade in K8S <1.27 & <1.30

**Comment by gaktive** [comment]
Phil did work also in https://github.com/rancher/dashboard/pull/10440/files

**Comment by gaktive** [comment]
Related backend: https://github.com/rancher/rancher/issues/44856

**Comment by torchiaf** [comment]
@kinarashah Do we need to remove the >=1.30 versions also from Azure AKS form ?

- Azure AKS

selection

![image](https://github.com/user-attachments/assets/695e3299-d568-411f-b720-8c1c3b15087b)

form

![image](https://github.com/user-attachments/assets/ac6265a8-db50-4d88-8352-7fd3c1e3b4f8)

**Comment by kinarashah** [comment]
@torchiaf Looks like we're overriding the msg for all cloud providers, so the msg shows up even for Amazon cluster...could we fix this so it only shows up for Azure cloud provider? 
<img width="767" alt="Screenshot 2024-08-07 at 12 35 54 PM" src="https://github.com/user-attachments/assets/4464a0cd-431d-48f5-b30c-4eec5915d5c3">
<img width="770" alt="Screenshot 2024-08-07 at 12 36 25 PM" src="https://github.com/user-attachments/assets/c9655d54-817a-4938-9cdf-b2a5da6f4054">


Also, to answer the question for AKS, I believe they manage the controller manager deployment themselves.

**Comment by torchiaf** [comment]
> @torchiaf Looks like we're overriding the msg for all cloud providers, so the msg shows up even for Amazon cluster...could we fix this so it only shows up for Azure cloud provider? 

Thanks @kinarashah Yes, that's a bug. We will fix it.

**Comment by torchiaf** [comment]
@IsaSih this [PR](https://github.com/rancher/dashboard/pull/11611) will close the issue.

**Comment by IsaSih** [comment]
Tests pass on v2.10-a79026c4409770b1bc05dd8318d0c111662a121d-head
