### ISSUE TITLE
Remove standalone access to Ember UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#11371]
Internal reference: SURE-8327

With most functionality moved away from the older Ember UI (Cluster Manager accessible via `/g` in the URL) and into the newer Vue UI (Cluster Explorer), the old UI has had less use. It's been updated less and with many API changes, it has become brittle and broken in areas. Some folks do use it as a backup for performance issues but it's not being updated and it's falling apart.

We'll keep the sections that are embedded into Vue but the point of this ticket is to remove standalone access to the Ember UI.

**Comment by nwmac** [comment]
See: https://github.com/rancher/ui/pull/5174

**Comment by gaktive** [comment]
@rancher/docs heads up that we'll need to mention in the release notes that in 2.10.0, the old UI (Cluster Manager) will not be directly accessible. The appropriate pages that still rely on that UI will continue to be embedded in the new UI (Cluster Explorer).

**Comment by izaac** [comment]
Validated on Rancher: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

`/g` redirects to a fail page.

![Image](https://github.com/user-attachments/assets/89a83c56-0210-4249-88e0-1dcf6df44598)
