### ISSUE TITLE
Rancher manager - OS Management Extension

### ISSUE THREAD

**Issue by alespestotnik** [rancher/dashboard#11372]
I am new to Rancher and trying to get familiar with functionalities.
I have installed latest Rancher version of rancher 2.8.5 to Ubuntu 22.04.4 LTS and following instructions: https://elemental.docs.rancher.com/quickstart-ui , trying to install OS Management Extension.  
Elemental OS extension is not listed in tab Available, I can only see Kamaji.
![image](https://github.com/rancher/dashboard/assets/167247195/2c062e81-dd4b-40f4-adcb-bd137f2b8de9)
Why Elemental plugin is not listed or how can I add it?  (Installation of the Elemental Operator was succesfull...)
Thank you for helping me.

**Comment by richard-cox** [comment]
The Elemental UI plugin in Rancher is only available in Rancher Prime (for more information on Prime see https://www.rancher.com/products/rancher-platform).

@aalves08 Can you see about getting elemental docs updated with the above info? @jordojordo probably need the same for kubewarden as well?
