### ISSUE TITLE
Issue in the pop up window for Delete action

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1137]
**On 2.5.0-alpha1**

create a secret --> Select it and click on delete.
The pop up window is like this 
<img width="639" alt="Screen Shot 2020-08-28 at 12 09 02 PM" src="https://user-images.githubusercontent.com/26032343/91606674-52c72280-e927-11ea-9069-15c4357d2e72.png">

**Issue#1**
- text "Protip: Hold the Command key while clicking delete to bypass this confirmation" is a little light in color and hard to read.

**Issue#2**
- When you click on the hyperlink of the secret say "test" in this case, user is navigated to this url `https://<rancher-server>/k8s/clusters/c-pjhjc/v1/secrets/default/test` .
- Is this how we want it to be ?

**Comment by lvuch** [comment]
issue 1: https://github.com/rancher/dashboard/pull/1213
issue 2: expected behavior is correct

**Comment by vincent99** [comment]
This is not a good/readable color contrast.

![image](https://user-images.githubusercontent.com/753917/92784096-2ebe0500-f35b-11ea-98bf-be4734b6ed7a.png)
![image](https://user-images.githubusercontent.com/753917/92784361-70e74680-f35b-11ea-99da-e18c6f2998e3.png)

**Comment by sowmyav27** [comment]
**On master-head - commit id: `c983bb436bf`**

- Delete a secret --> pop up window --> Text is readable now
<img width="477" alt="Screen Shot 2020-09-25 at 10 40 03 AM" src="https://user-images.githubusercontent.com/26032343/94298786-9196cb00-ff1b-11ea-9f9c-b96ad754f329.png">

- Text is readable in the following sections also
<img width="334" alt="Screen Shot 2020-09-25 at 10 41 14 AM" src="https://user-images.githubusercontent.com/26032343/94298876-b25f2080-ff1b-11ea-9edc-4c29392530f5.png">

<img width="343" alt="Screen Shot 2020-09-25 at 10 41 29 AM" src="https://user-images.githubusercontent.com/26032343/94298872-b0955d00-ff1b-11ea-8b63-55bf97780e06.png">
