### ISSUE TITLE
[v2.9] EKS - Allow version upgrade only from current version to next minor version

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11389]
**Setup**
Rancher - v2.9-1c2b815c8dd66e141b21630904127adc8e03c3de-head
Dashboard - master df60f44
Browser type & version: Chrome latest

**Describe the bug**
EKS (Vue UI): Allow version upgrade only from current version to next minor version. The same is validated on v2.8 Ember UI.

**To Reproduce**
- Create EKS cluster from Rancher UI and select lowest supported k8s version
- Upgrade version to highest supported version

**Screenshots**
2.8:
![image](https://github.com/rancher/dashboard/assets/73099870/638732d9-23a0-406d-9d73-a6e6b1f39182)

2.9:
![image](https://github.com/rancher/dashboard/assets/73099870/348e4f6f-088c-4ca2-8417-cadad1aca3d4)

![image](https://github.com/rancher/dashboard/assets/73099870/ee4416a3-a60d-42c6-a0fa-7ed2e1a34644)

**Comment by gaktive** [comment]
Looks like a release blocker but I need engineers to confirm.

**Comment by mantis-toboggan-md** [comment]
@gaktive this one is probably not a release blocker - it's requesting extra validation in the EKS form vs a bug that is actually preventing users from doing something

**Comment by yonasberhe23** [comment]
Tested in 
- v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head
- master 84975df


https://github.com/user-attachments/assets/6d481963-4bef-4273-8765-3497ff822564
