### ISSUE TITLE
Pod details - Display Pod volume details

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1138]
Main epic/story for pod details: rancher/dashboard#685
Rancher version: `v2.5-alpha1 (08/28/2020)` 

Volume details after deploying a workload are not displayed in the pod. This is TBD as per this comment https://github.com/rancher/dashboard/issues/685#issuecomment-632400172

**Comment by deniseschannon** [comment]
The view mode of this issue: https://github.com/rancher/dashboard/issues/500 needs to be added as part of the container component for the view mode. 

@vincent99 There are a lot of options in the create/edit mode, but are the fields essentially this? How much does it change from the different fields?

![Screen Shot 2020-09-09 at 9.27.56 AM.png](https://zube.io/files/rancher/519640a97104f3669c015740f587a650-screen-shot-2020-09-09-at-9-27-56-am.png)

**Comment by vincent99** [comment]
Merged but I continue to think this is the wrong approach for detail pages and it should be showing you for example the actual PVs/secret resource/etc that are bound to the pod instead of the abstract definition of the request for them to be bound.

**Comment by izaac** [comment]
Rancher version `v2.5-head (10/07/2020)` _60d3ff3_

Validated the details now appear in the pod, I tested with HostPath and AWS EBS volumes.

Sample:

![Screen Shot 2020-10-07 at 11 43 08 AM](https://user-images.githubusercontent.com/27659/95373945-90a65780-0892-11eb-8d0c-25408c73fed2.png)
