### ISSUE TITLE
Re-instate Download CLI e2e tests

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11387]
- disabled e2e tests given https://github.com/rancher/rancher/issues/46068

**Comment by gaktive** [comment]
Per @samjustus, the related backend work has been merged for both 2.9.0 & 2.8.x. Let's verify that we can reinstate this E2E test.

**Comment by richard-cox** [comment]
Thanks for update. Though original issue still open and links used in UI still seem dead still (for example https://releases.rancher.com/cli2/v2.9.0-rc4/rancher-darwin-amd64-v2.9.0-rc4.tar.gz).

Noticed 2.8 has merged (https://github.com/rancher/cli/pull/378) but not 2.9 (https://github.com/rancher/cli/pull/379). Following that though the workflows would need to run and bits uploaded

**Comment by gaktive** [comment]
2.9 appears to be merged now though https://github.com/rancher/rancher/pull/46141 is still open and the URL is still not working, even with RC5. @enrichman keep us posted on when the bits are uploaded since this E2E test helps with automated testing as QA scrambles to manually test.

**Comment by enrichman** [comment]
@gaktive that's strange, the binaries are uploaded. Do you have the failing link to check the differences?

**Comment by mantis-toboggan-md** [comment]
The -rc5 links look good to me, but rancher 2.9-head builds still reference the -rc4 links, so we'll need https://github.com/rancher/rancher/pull/46141  merged before our tests pass
