### ISSUE TITLE
[v2.9] GKE - Unable to add Master Authorized Network while Edit

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11391]
**Setup**
Rancher - v2.9-1c2b815c8dd66e141b21630904127adc8e03c3de-head
Dashboard - master df60f44
Browser type & version: Chrome latest

**Describe the bug**
GKE (Vue UI): Unable to add Master Authorized Network while Edit. The same is allowed on v2.8 Ember UI.

**To Reproduce**
- Create GKE cluster from Rancher UI and select Master Authorized Network setting
- Edit cluster and try adding another Authorized network which is disabled on UI

**Screenshots**
2.8:
![image](https://github.com/rancher/dashboard/assets/73099870/94099c5b-0ec9-4976-981e-281e83ab22e1)

2.9:
![image](https://github.com/rancher/dashboard/assets/73099870/20835732-2f5a-4f20-bc7b-5f9787e7e0dc)

**Comment by yonasberhe23** [comment]
will be a combination of automated and manual testing. moving to To Test

**Comment by cpinjani** [comment]
Validation passed on build:
Rancher	- v2.9-a9355940c0629ca419b7dd3e4098c4ea0e52c0c0-head
Dashboard - master 102f1e6

Able to add/remove Master Authorized Network while editing cluster.

![image](https://github.com/user-attachments/assets/40f0ab47-9f64-48cd-a3c4-22e106a02b1b)
