### ISSUE TITLE
Console errors in Harvester cluster's provisioning page

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#11397]
**Setup**
- Rancher version: 2.9-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

![image](https://github.com/rancher/dashboard/assets/26394656/dff55214-8eea-4e08-95ad-83b719b1b981)

**To Reproduce**

- Go To Cluster Management
- Create a Harvester cluster.
- Once the cluster is created, click on Edit Config.

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by yonasberhe23** [comment]
unit test is sufficient. moving to done
