### ISSUE TITLE
Error while provisioning/updating a cluster is not printed on the edit form header

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#11405]
**Setup**
- Rancher version: v2.9-a9355940c0629ca419b7dd3e4098c4ea0e52c0c0-head
- Rancher UI Extensions: master 46a44c1
- Browser type & version:

**Describe the bug**

When there is an error while provisioning or updating a cluster, the error should appear on the Edit form as well to make it easier for user to fix the error ( if I am not mistaken this used to happen on 2.8).

**To Reproduce**

1. Create an AKS cluster and edit the nodepool name to >12 char long value, for e.g. `abcdefghijklmnopq` and hit save.
2. The following error appears in the UI:
```
 Error failed to create cluster: PUT https://management.azure.com/subscriptions/80de5134-ca65-4731-be21-13fb1f0910a2/resourceGroups/pvala-aks-rg/providers/Microsoft.ContainerService/managedClusters/pvala-aks-invalid-np-name -------------------------------------------------------------------------------- RESPONSE 400: 400 Bad Request ERROR CODE: InvalidParameter -------------------------------------------------------------------------------- { "code": "InvalidParameter", "details": null, "message": "The value of parameter agentPoolProfile.name is invalid. Please see https://aka.ms/aks-naming-rules for more details.", "subcode": "", "target": "agentPoolProfile.name" } -------------------------------------------------------------------------------- 
```
3. Edit the cluster and notice the UI; the error message is not there.

**Result**
The error message does not appear on the edit form.
**Expected Result**

The error message must appear on the edit form to know which part of the form needs to be fixed.
**Screenshots**

[Screencast from 07-10-2024 03:37:13 PM.webm](https://github.com/rancher/dashboard/assets/11015077/5581bba4-852b-4604-9eeb-25a9b0527da3)

**Additional context**

_This might very well be a feature request._

**Comment by richard-cox** [comment]
@valaparthvi would you be able to check the network requests for any failures?

**Comment by valaparthvi** [comment]
@richard-cox I am not sure how to check that, I mean I monitored the network requests but did not catch any noteworthy request, would it help you if I shared my rancher instance with you?

**Comment by richard-cox** [comment]
If there's no failed network request we would need AKS operator changes to address this. UI side we should look at adding validation as well.

@mantis-toboggan-md i sent this your way, worth double checking just in case it's a regression and could be addressed today?

**Comment by valaparthvi** [comment]
>If there's no failed network request we would need AKS operator changes to address this. UI side we should look at adding validation as well.

cc: @mjura @yiannistri

**Comment by mantis-toboggan-md** [comment]
It looks like the old ui does validate node pool name length; I'll mark this as a release-blocker since its a regression

**Comment by mantis-toboggan-md** [comment]
To clarify, what we should be doing on the UI side is showing an error message in the node pool input with invalid name length, similar to the invalid character error shown in node pool names.

**Comment by valaparthvi** [comment]
>To clarify, what we should be doing on the UI side is showing an error message in the node pool input with invalid name length, similar to the invalid character error shown in node pool names.

You are right about this, but this is not limited to invalid character length, the error should be displayed for other cases as well, for e.g. when an invalid SSH key is provided while creating AKS.

**Comment by mantis-toboggan-md** [comment]
> > To clarify, what we should be doing on the UI side is showing an error message in the node pool input with invalid name length, similar to the invalid character error shown in node pool names.
> 
> You are right about this, but this is not limited to invalid character length, the error should be displayed for other cases as well, for e.g. when an invalid SSH key is provided while creating AKS.

That would be a solid enhancement and something we should add to the UI but it's not validated in the old AKS UI either - ideally at this stage for. 2.9.0 we'd like to stick to fixing regressions, so I have filed a separate issue for the ssh key input to tackle in a later release https://github.com/rancher/dashboard/issues/11408

**Comment by valaparthvi** [comment]
@mantis-toboggan-md The point of this issue was also to bring back error printing in the form header that was present in 2.8.


![image](https://github.com/rancher/dashboard/assets/11015077/3876cafc-2d76-467a-961d-448369891b23)

**Comment by mantis-toboggan-md** [comment]
> Expected Result
>
>The error message must appear on the edit form to know which part of the form needs to be fixed.

I am trying to implement this in a way that is consistent with the rest of the dashboard ui, which is field-level error reporting and validation during initial configuration (and editing), not a banner at the top of the page.

**Comment by yonasberhe23** [comment]
Tested in: 
- v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head
- master f8185c5


https://github.com/rancher/dashboard/assets/127343932/41b5b332-3e1f-436e-a7ca-7a5a69046ad2

**Comment by valaparthvi** [comment]
> Tested in:
> 
>     * v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head
> 
>     * master [f8185c5](https://github.com/rancher/dashboard/commit/f8185c53a3a02960ae34f3015d277761c8184d95)
> 
> 
> Screen.Recording.2024-07-11.at.9.57.24.AM.mov

This is the original behavior, we wanted the validation to happen before hitting save.
