### ISSUE TITLE
Istio v2 - `istioctl-installer` job displays in dashboard after it is deleted

### ISSUE THREAD

**Issue by bmdepesa** [rancher/dashboard#1141]
rancher/rancher:v2.5.0-alpha1

* Rancher helm install
* Create a cluster
* Deploy Istio
* After Istio installs, the UI Jobs page shows the `istioctl-installer` job, but gives an error when clicking on it: 
```
{ "data": "apiVersion: v1\ncode: 404\ndetails:\n group: batch\n kind: jobs\n name: istioctl-installer\nkind: Status\nmessage: jobs.batch \"istioctl-installer\" not found\nmetadata: {}\nreason: NotFound\nstatus: Failure\n" }
```
* `kubectl` shows the job does not exist
```
> kubectl get jobs --all-namespaces
NAMESPACE     NAME                                COMPLETIONS   DURATION   AGE
kube-system   rke-coredns-addon-deploy-job        1/1           6s         3h26m
kube-system   rke-ingress-controller-deploy-job   1/1           9s         3h26m
kube-system   rke-metrics-addon-deploy-job        1/1           4s         3h26m
kube-system   rke-network-plugin-deploy-job       1/1           5s         3h27m
```

![Screen Shot 2020-08-28 at 2 16 28 PM](https://user-images.githubusercontent.com/21316915/91615774-2d431480-e939-11ea-90ce-2ba7b261cd35.png)

**Comment by deniseschannon** [comment]
This sounds more like generic refresh issue (https://github.com/rancher/dashboard/issues/1368), so added to that list.
