### ISSUE TITLE
[v2.9] EKS - Security groups section missing under Networking

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11412]
**Setup**
Rancher - v2.9-1c2b815c8dd66e141b21630904127adc8e03c3de-head
Dashboard - master https://github.com/rancher/dashboard/commit/df60f440f41fe1b59c35b5181292504bb5e66059
Browser type & version: Chrome latest

**Describe the bug**
EKS (Vue UI): Security groups section missing while provisioning cluster. The same is present on v2.8 Ember UI.

**To Reproduce**
- Create EKS cluster from Rancher UI and select existing subnets option

**Screenshots**
2.8
![image](https://github.com/rancher/dashboard/assets/73099870/6bed7042-bcc4-4140-9fdd-86854def38d8)

2.9
![image](https://github.com/rancher/dashboard/assets/73099870/4f3d9d34-ac1c-4a5b-9a3d-a2464d5261ea)

**Comment by richard-cox** [comment]
Looks like in ember this is only applicable if the user selects custom subnets. They can then override the default behaviour of rancher creating a new one by selecting an existing one.

There's some logic for this in RKE EC2 world, but not much 

![image](https://github.com/rancher/dashboard/assets/18697775/3eb0853f-75c2-4078-8c3c-ed0d80a0330d)

Given that the user should still be able to create the cluster, just not with existing security groups, i'm not sure this a blocker... however it is a regression. @mantis-toboggan-md up to you?

**Comment by yonasberhe23** [comment]
this will be a combination of automation and manual testing. moving to To Test

**Comment by cpinjani** [comment]
Validation passed on build, able to select security group with existing subnets option
```
Rancher - v2.9-81337b95660cba868629d6fe769bd7e8242b5aee-head
Dashboard - master 3da1205
```
![image](https://github.com/user-attachments/assets/5930f7c2-d142-49da-aba8-ae6c680671be)
