### ISSUE TITLE
Unable to change a cluster's fleet workspace on continuous delivery page

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#11434]
**Setup**
- Rancher version: v.2.9-head `3c4ccdc`
- Browser type & version: Chrome and Firefox

**Describe the bug**
Unable to change workspaces in fleet continuous delivery page. 

**To Reproduce**
1. Navigate to continuous delivery page >> Advanced >> workspaces >> Create a workspace ws-ns1
2. Navigate to continuous delivery page >> clusters >> select a cluster and select change workspace

**Result**
Unable to change workspace

**Expected Result**
Option to change workspace

**Screenshots**

https://github.com/user-attachments/assets/504bc28f-70a2-4673-b38a-26dbd8a0cdef

**Additional context**
It works when edited through <URL>/v3/c-id 
Works on v2.8.5 rancher version

**Comment by gaktive** [comment]
Giving back to QA to test since Github didn't reopen this.

**Comment by yonasberhe23** [comment]
Tested in 
- v2.9-81337b95660cba868629d6fe769bd7e8242b5aee-head
- master 2fdd3be


https://github.com/user-attachments/assets/3095309d-3b74-4d4d-bbea-84db76e698dc
