### ISSUE TITLE
[v2.9] EKS - Invalid Node Kubernetes version format being while provisioning cluster

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11438]
**Setup**
Rancher - v2.9-a9355940c0629ca419b7dd3e4098c4ea0e52c0c0-head
Dashboard - master 102f1e6
Browser type & version: Chrome latest

**Describe the bug**
EKS (Vue UI): Node Kubernetes version format being set for Nodegroup while provisioning cluster is invalid.

![image](https://github.com/user-attachments/assets/70de232d-ceee-4d45-9eec-ffd3ee7cd0d7)

**To Reproduce**
- Create EKS cluster from Rancher UI and check Node Kubernetes version value.

Expected value: Same value as Cluster kubernetes version
Workaround: Toggle Cluster kubernetes version value and desired value for Nodegroup is also set.

**Screenshots**
After cluster starts provisioning:

![image](https://github.com/user-attachments/assets/9313fb07-9e12-43f8-b7b3-fcd5cee5cec9)

**Comment by gaktive** [comment]
Reopening for QA

**Comment by IsaSih** [comment]
Tests pass on v2.9-81337b95660cba868629d6fe769bd7e8242b5aee-head regarding the UI exhibiting the correct Kubernetes version, same as the kubernetes cluster version. However, the cluster fails to provision. I didn't change any of the settings and just let all the values as the default.  
<img width="1710" alt="Screenshot 2024-07-17 at 12 34 42 AM" src="https://github.com/user-attachments/assets/e935cc65-1bed-4b35-8b7b-84be9249fb17">

**Comment by cpinjani** [comment]
Validation passed on build `v2.9-81337b95660cba868629d6fe769bd7e8242b5aee-head` 
@IsaSih Seems this can be closed as `InitialRolesPopulated` issue to not always reproducible and tracked separately https://github.com/rancher/dashboard/issues/9837
