### ISSUE TITLE
Istio v2 - Overlay file and values yaml are not displayed during upgrade

### ISSUE THREAD

**Issue by bmdepesa** [rancher/dashboard#1143]
rancher/rancher:v2.5.0-alpha1

* Deploy a cluster
* Install `rancher-istio 1.6.800`
* After install, attempt to upgrade to `rancher-istio 1.7.000`
* The overlay file and values yaml shown during install are not displayed during upgrade

![Screen Shot 2020-08-28 at 2 07 16 PM](https://user-images.githubusercontent.com/21316915/91616519-b7d84380-e93a-11ea-81ee-0baaae9adb9d.png)

**Comment by vincent99** [comment]
I haven't seen this exact scenario but changed some stuff in this area, can you still get this on master @bmdepesa ?

**Comment by bmdepesa** [comment]
rancher/rancher:master-head f7f8e8b

* The overlay file and values YAML are now present during upgrade
