### ISSUE TITLE
[BUG]: Cluster Proxy Config is deleting when user disable the JWT Authentication

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/dashboard#11444]
**Setup**
- Rancher version: `v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head`
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
The resource Cluster Proxy Config is deleting when user disable the JWT Authentication

**To Reproduce**
1. Provision rancher
2. Create a downstream cluster
3. Local->Cluster Management->Advanced->JWT Authentication
4. Select the cluster and Disable the cluster(JWT Authentication)
5. Check for the Cluster Proxy Config resource update 

**Result**
1. The ClusterProxyConfig resource is deleted instead of updating the enabled flag from `true` to `false`
2. ```
    kubectl describe clusterproxyconfig -n c-m-tttttttt
    No resources found in c-m-dfcfz892 namespace.
    ```

**Expected Result**
1. On disable the clusterproxyconfig resource should be update the enabled flag from `true` to `false` instead of deleting the complete resource


**Additional context**
1. Currently this is not giving any issues to the users but good to update the flag to track updated flag time.

**Comment by eva-vashkevich** [comment]
Hi @crobby,
Do you know if there is any way to tell if ClusterProxyConfig has been enabled/disabled other than looking at a managedField with operation 'Update'? And if not, is this a reliable way to tell?

The reason why I am deleting a cluster proxy config when disabled, is to be able to tell when it was enabled by checking creation timestamp. We currently exclude managedFields when requesting resources and I couldn't find any other field that would tell us when it was modified.

Thank you

**Comment by gaktive** [comment]
@samjustus for reference, UI is proposing this as a change:

- Current behaviour:
 - Turning the feature on: creates the clusterproxyconfig
 - Turning the feature off: deletes that config
- Proposal:
 - Turning the feature on: creates the clusterproxyconfig & enables the feature
 - Turning the feature off: disables that config and doesn't delete it

This helps with re-activating the feature. The only thing UI would have to look at later would be an option to disable AND delete.

Question would then be 2.9.0? or 2.10.0 + 2.9.x?

**Comment by crobby** [comment]
> Hi @crobby, Do you know if there is any way to tell if ClusterProxyConfig has been enabled/disabled other than looking at a managedField with operation 'Update'? And if not, is this a reliable way to tell?
> 
> The reason why I am deleting a cluster proxy config when disabled, is to be able to tell when it was enabled by checking creation timestamp. We currently exclude managedFields when requesting resources and I couldn't find any other field that would tell us when it was modified.
> 
> Thank you

I'm a little bit confused about the question here.  When disabling or enabling the feature, you should be able to update the ClusterProxyConfig  (or create the object, if it's not already present), and just toggle the enabled flag to the desired value.

**Comment by crobby** [comment]
> @samjustus for reference, UI is proposing this as a change:
> 
> * Current behaviour:
>   
>   * Turning the feature on: creates the clusterproxyconfig
>   * Turning the feature off: deletes that config
> * Proposal:
>   
>   * Turning the feature on: creates the clusterproxyconfig & enables the feature
>   * Turning the feature off: disables that config and doesn't delete it
> 
> This helps with re-activating the feature. The only thing UI would have to look at later would be an option to disable AND delete.
> 
> Question would then be 2.9.0? or 2.10.0 + 2.9.x?

I like the proposal, but it should be noted that it is also possible to manually create a ClusterProxyConfig outside of the UI, so the UI would want to check for existence of the object before always attempting to create one on enablement (ie:  There is an existing ClusterProxyConfig and it is set to false....attempting to create another one will get stonewalled at the webhook level, because each cluster namespace can only ever have 1 ClusterProxyConfig at max).

**Comment by gaktive** [comment]
Based on timing, I'm going to push this out of 2.9.0. We'll work on this for 2.10.0 and back port; maybe 2.9.1 but we'll see.

**Comment by eva-vashkevich** [comment]
Hi @crobby 
RE: "it should be noted that it is also possible to manually create a ClusterProxyConfig outside of the UI, so the UI would want to check for existence of the object before always attempting to create one on enablement". This is case is currently covered already.
My question was about finding the timestamp of when JWT Authentication was enabled. Is managedFields the only way to get this information and is it accurate? From my testing, it is, but wanted to double check with you.

**Comment by crobby** [comment]
> Hi @crobby RE: "it should be noted that it is also possible to manually create a ClusterProxyConfig outside of the UI, so the UI would want to check for existence of the object before always attempting to create one on enablement". This is case is covered already. My question was about finding the timestamp of when JWT Authentication was enabled. Is managedFields the only way to get this information and is it accurate? From my testing, it is, but wanted to double check with you. I think the other question is if we should change the current approach as part of 2.9.0 or if we can do it later (and if we need to do it)

Correct.  There is no other information in the ClusterProxyConfig object that would be useful in determining when the feature was enabled/disabled.

**Comment by izaac** [comment]
Updates to the E2E tests to cover this scenario seems enough to me
