### ISSUE TITLE
Update or replace dependencies to be compatible with Vue3

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11459]
# Description

As an outcome of an earlier investigation, several libraries must be replaced to complete the migration to Vue3.

- https://github.com/rancher/dashboard/issues/9536
- https://github.com/rancher/dashboard/issues/9537
- https://github.com/rancher/dashboard/issues/9538
- https://github.com/rancher/dashboard/issues/11486
- https://github.com/rancher/dashboard/issues/11596
- Replace `vue-shortkey`

**Comment by rak-phillip** [comment]
I think that we should remove #8207 from this issue - merging the modals shouldn't have an impact on finalizing the Vue3 implementation.
