### ISSUE TITLE
Unable to access gatekeeper after install

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#1145]
What kind of request is this:
Bug

Steps:
Create cluster, navigate to dashboard
Apps -> Charts -> rancher-gatekeeper Install
After gatekeeper is deployed, refresh the page
Under global dropdown navigate to OPA Gatekeeper

Result:
User is redirected to rancher-gatekeeper install. User cannot see constraints page or gatekeeper UI.
![Screen Shot 2020-08-28 at 4 26 25 PM](https://user-images.githubusercontent.com/57409052/91622296-4ce33880-e94b-11ea-96cd-26c8aeeb3095.png)

Rancher server `rancher\rancher:v2.5.0-alpha1`

**Comment by aaronRancher** [comment]
Behavior is inconsistent. 
After hitting this issue, https://github.com/rancher/rancher/issues/28646, OPA access is blocked.
Hitting `install` again will allow the OPA page to be accessed.

**Comment by deniseschannon** [comment]
@aaronRancher Can you retest with master as it seems to be working?

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 731b33e`

Steps:
Create cluster, navigate to dashboard
Apps -> Charts -> rancher-gatekeeper Install
After gatekeeper is deployed, refresh the page
Under global dropdown navigate to OPA Gatekeeper

Result:
Gatekeeper is accessible
