### ISSUE TITLE
JWT Authentication page needs to handle user not having access

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#11461]
**Setup**
- Rancher version: 2.9
- Rancher UI Extensions: N/A
- Browser type & version: any

**Describe the bug**

JWT Authentication page should be able to handle users that do not have access.

**To Reproduce**

1. Create a standard user
2. Go to Advanced -> JWT Authentication
**Result**
"Enable this feature on a cluster to add support for JWT authenticating downstream service accounts." banner is shown, which is incorrect, because the feature is enabled, but user does not have permissions.

"fetch.client.js:75 Error in fetch(): 
Error: Unknown schema for type: management.cattle.io.clusterproxyconfig
    at getters.js:25:1" " error is shown in the console.
    
**Expected Result**

Tab should be hidden from the users that do not have access.

**Screenshots**

<img width="1715" alt="Screenshot 2024-07-17 at 8 41 29 PM" src="https://github.com/user-attachments/assets/7c029f00-559b-46b0-afae-94944724f08e">

**Additional context**

Additionally, it would be good to implement changes proposed in https://github.com/rancher/dashboard/pull/11450#pullrequestreview-2182539745:
- rows creates two functions (enabledActions and disableAction) on every call (they could both be defined in data)
- rows takes a collection of management.cattle.io.clusterproxyconfig resources, constructs a model like object and properties, and passes it to a resource table as if they were management.cattle.io.clusterproxyconfig models. This could be neatened and follow patterns by creating a model/management.cattle.io.clusterproxyconfig file. That would automatically get a lo of the required properties and have a neat place for actions. Doing this also means the two actions enabledActions and disableAction, plus enable and disable methods are only created once per model

**Comment by yonasberhe23** [comment]
automated tests are sufficient. moving to done
