### ISSUE TITLE
Extensions: Convert the various creators into a single creator

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#11484]
**Is your feature request related to a problem? Please describe.**

Convert the various creators into a single creator package/lib.

We currently have:
skeleton app creation: https://github.com/rancher/dashboard/tree/master/shell/creators/app
extension/package creation: https://github.com/rancher/dashboard/tree/master/shell/creators/pkg
extension update: https://github.com/rancher/dashboard/tree/master/shell/creators/update

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Suggestion:

create a new folder for your code
yarn create @rancher/extension EXTENSION_NAME

Operates a bit more intelligently.

So looks to see if there is an app, if not, it creates one then it creates the extension.
If there is, it adds the extension.
app name and extension name would be the same - maybe an arg to give a different app name
Maybe an arg to only create an app

**Comment by izaac** [comment]
Moving to done
