### ISSUE TITLE
[backport 2.8.x] agent-tls-mode global setting missing from ui

### ISSUE THREAD

**Issue by brudnak** [rancher/dashboard#11488]
# Setup

| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version starting         | v2.8-1dceeccd0eb996fcf8ab66282b00d0ec798bacaf-head |
| Installation option              | Helm (high availability)                           |
| RKE binary version used          | v1.5.10                                            |
| If Helm Chart k8s cluster        | v1.28.10                                           |
| Downstream cluster type          | Linode k3s                                         |
| Downstream K8s version           | 1.28.11+k3s2                                       |
| Authentication providers enabled | local                                              |
| Logged in user role              | admin                                              |
| Browser type                     | Firefox Developer Edition                          |
| Browser version                  | 129.0b5 (64-bit)                                   |
| Dashboard                        | master 102f1e6                                     |
| Webhook version                  | rancher/rancher-webhook:v0.4.8-rc5                 |

# Describe the bug

The `agent-tls-mode` setting is missing from the `Global Settings` section in the UI

# To Reproduce

1. Start rancher on v2.8-head
2. Set a value for the agent-tls-mode setting during the helm install process, e.g.,

    ```sh
    helm install rancher rancher-alpha/rancher --devel \
      --namespace cattle-system \
      --set hostname=$URL_REDACTED \
      --set ingress.tls.source=letsEncrypt \
      --set letsEncrypt.email=$EMAIL_REDACTED \
      --set letsEncrypt.ingress.class=nginx \
      --set bootstrapPassword=$PW_REDACTED \
      --set rancherImage=rancher/rancher \
      --set rancherImageTag=v2.8-head \
      --version 2.8.6-alpha3 \
      --set global.cattle.psp.enabled=false \
      --set agentTLSMode=system-store \
      --set privateCA=true
    ```

3. When logging into Rancher navigate to Global Settings
4. See there is no agent-tls-mode setting listed
5. It is however listed, and settable using kubectl

# Result

The setting was available in the UI

# Expected Result

For the setting to be listed in the UI

# Bug Frequency

| Frequency                                                                                          | Selected Option |
| -------------------------------------------------------------------------------------------------- | --------------- |
| Consistent (10/10) - A consistent bug can be replicated every time the test is executed.           | ❎               |
| Frequent (7/10)- A frequent bug can be replicated like 7 out of 10 times when a test is replicated |                 |
| Occasional (5/10) - Occasional bug is more hard to replicate than a frequent bug.                  |                 |
| Once thus far, twice thus far - Few bugs cannot be reproduced every time you run the test.         |                 |

**Comment by richard-cox** [comment]
Updated issues type and linking original issue https://github.com/rancher/dashboard/issues/11138 (SURE-7641).

UI changes were schedule for 2.9.0 or, depending on time, 2.10.0. We got 2.9.0 in however backporting was not mentioned and has now missed the 2.8.next1 boat, moving to next2

**Comment by gaktive** [comment]
next2 is now next1 so hopefully this is a quick one to work on.

**Comment by IsaSih** [comment]
Tests pass on v2.8-68e5d43e449fcd3ef73baf1caee98da6f0104eed-head. Also, payload is successfully changing the agent-tls-mode.

![Image](https://github.com/user-attachments/assets/bae5a67c-446c-47cd-87e4-7b09987525c1)
