### ISSUE TITLE
Process is undefined when executing Axios plugin 

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11493]
# Description

While initializing the application, an issue with the lack of `process` variable in this environment has been identified.

```ts
  const baseURL = process.browser ? (runtimeConfig.browserBaseURL || runtimeConfig.baseURL || '/') : (runtimeConfig.baseURL || process.env._AXIOS_BASE_URL_ || 'https://localhost:8005/');
```

As a consequence also `$axios` global is finally not initialized.
Given the low usage cases, we may also take the chance to remove this pattern.

<img width="484" alt="Screenshot 2024-07-19 at 11 12 45" src="https://github.com/user-attachments/assets/6fc74ec4-53d1-4f47-afcc-b1ead6c0bfbc">

**Comment by rak-phillip** [comment]
Do we have a concrete example that demonstrates how `$axios` is not working? In previous efforts[^1], we were able to demonstrate `fetch()` and `$axios` working in Vue3. Perhaps, something was lost in translation along the way?

[^1]: https://github.com/rancher/dashboard/compare/master...rak-phillip:dashboard:feature/9028-migration-prak-02?expand=1

**Comment by cnotv** [comment]
The whole ticket is about the example, including the error and the line of code. I imagine you aim for something more specific. What would that be?
The issue itself is not with Axios, by the way; it's specifically about the `process` being `undefined`. It can be reproduced on the branch and running the application.

**Comment by rak-phillip** [comment]
@cnotv and I synced on this out-of-band to clarify that the branch in question is the `vue3` branch and that the specific error can be reproduced by running the code there. 

I don't think that we want to consider removing the `$axios` pattern at this point for two reasons:

1. We have demonstrated the successful usage of this pattern in a Vue3 environment
2. The symptom of `process` being `undefined` is unrelated to the pattern in question

I'm currently of the mindset that there's a deeper underlying issues that needs to be resolved. Closer investigation will help us to better identify how to move forward.

**Comment by cnotv** [comment]
Thanks for the update!

**Comment by cnotv** [comment]
Issue seems solved with the new branch: https://github.com/rancher/dashboard/commits/vue3-depth-first/

To be addressed specific commit. 
@rak-phillip do you remember by chance?

**Comment by rak-phillip** [comment]
iirc it was this change that resolves the error

https://github.com/rancher/dashboard/commit/72a8eaf254f2cbbfbe83ff0e278178d3748fb74d#diff-be70a6bba200bfb07052198a366be7be6689a92a627098a81eff1d5fcb212d63
