### ISSUE TITLE
Performance: Server-side pagination setting is enabled when user hits cancel option

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#11497]
**Setup**
- Rancher version: v2.9-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
 Although the user clicks cancel, the server-side pagination setting is enabled/checked.

**To Reproduce**

1. go to Global settings > feature flags > enable ui-sql-cache
2. go to Global settings > feature flags > enable `Server-sdie Pagination'
3. hit cancel on the `Are you sure?` modal
4. notice setting is checked

**Result**
setting is checked before the user hits 'Enable'.

**Expected Result**
setting is unchecked until the user clicks 'Enable'.

**Screenshots**

https://github.com/user-attachments/assets/d39ff569-0cb4-4101-928f-c657cab2d425

**Additional context**

**Comment by richard-cox** [comment]
Gonna bump this to 2.10.0 as i don't think it's a release blocker.

- Perf pagination checkbox is only enabled once the ui-cache FF is enabled. This is an experimental feature not designed for production. So to get there the user is already in non-prod.
- Perf setting although enabled (and visually so) is not applied until user clicks save

**Comment by yonasberhe23** [comment]
The setting remains unchecked until the user clicks 'Enable' on the incompatible modal. + Regression tests passed.

Tested in: 

- Rancher v2.10-3ed01c34581afc6bcc4da77c78127d982e13a405-head
- Dashboard master 340d410
