### ISSUE TITLE
Server-side Pagination: Cluster Dashboard: Certificates: Secrets do not load in Certificates view on the Cluster Dashboard

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#11524]
**Setup**
- Rancher version: v2.9-13494c6a541d408b00e78415d18128f642f295d0-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
Secrets do not load in Certificates view on the Cluster Dashboard when vai enabled.

**To Reproduce**
1. go to Global settings > feature flags > enable `ui-sql-cache`
2. go to Global settings > performance > enable `Server-sdie Pagination'
3. go to cluster dash
4. click Certificates tab
5. notice secrets do not load and 422 error is thrown

Error: 
{
 "type": "error",
    "links": {},
    "code": "InvalidBodyContent",
    "message": "column is invalid [metadata.fields.1]: supplied column is invalid",
    "status": 422
}

**Result**
Secrets do not load in Certificates view on the Cluster Dashboard when vai enabled.

**Expected Result**
Secrets load in Certificates view on the Cluster Dashboard when vai enabled.

**Screenshots**

https://github.com/user-attachments/assets/8f261897-0f73-493d-b60f-6c18bc780d7e

**Additional context**

**Comment by richard-cox** [comment]
Note - This is a 2.9 issue only, in 2.10 the table should be updated to handle the different way of filtering

**Comment by IsaSih** [comment]
Tests pass in v2.9-63ca06b9fb165182ca1063868ef837dfaf84bb31-head

https://github.com/user-attachments/assets/47f8c783-2357-439b-a9c8-d7e1fc4b058a
