### ISSUE TITLE
Add "v27.0.x", "v27.1.x", and "v27.2.x" options for "Docker Install URL"

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#11523]
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/rancher/rancher/issues/46326 we're adding support for Docker 27.0.x and 27.1.x.

Edited after creation to also include v27.2.x as part of https://github.com/rancher/rancher/pull/47290.

**Describe the solution you'd like**
UI dropdowns that allow picking "Docker Install URL" (e.g. on Node Template details page - not sure where else it may be referenced) should have the following new items available:
* "v27.2.x" choice that populates `https://releases.rancher.com/install-docker/27.2.sh`
* "v27.1.x" choice that populates `https://releases.rancher.com/install-docker/27.1.sh`
* "v27.0.x" choice that populates `https://releases.rancher.com/install-docker/27.0.sh`

Note: Handling of default option (and addition of " (Recommended)" text) is handled via `engine-install-url` setting on backend that will be updated as part of https://github.com/rancher/rancher/issues/46326 and should be validated on that issue.

**Describe alternatives you've considered**
Note "Docker Install URL" is editable and doesn't limit users to only the choices available, so they can specify other URLs manually as well before this enhancement is done.

## Additional Information
See https://github.com/rancher/dashboard/issues/10996 on how it was handled last time for Docker 26.1

## Testing

To test, go to create a Digital Ocean cluster, click on 'Add Node Template', select a credential and click Next. Expand 'Engine Options' and verify that the new Docker Install URLs appear correctly, e.g.
![image](https://github.com/user-attachments/assets/d36edbfc-8148-4775-aaaf-421fe8204bdd)

**Comment by rancher-max** [comment]
It looks like there was some scope adjustment here for 2.10, and we are also going to be including docker v27.2.x now.

Ref: 
- Current open Rancher PR: https://github.com/rancher/rancher/pull/47290
- Merged KDM PR: https://github.com/rancher/kontainer-driver-metadata/pull/1492/files#diff-d01a2c7a3b562201db5cb878080d51541026cccb36734541963bf2a41246cab4R24-R27
- Relevant Rancher issue: https://github.com/rancher/rancher/issues/47173

**Comment by rancher-max** [comment]
## Validated using rancher `head` build

### Rancher Version Info

<img width="867" alt="image" src="https://github.com/user-attachments/assets/65c9b5de-8972-447e-b92e-2017f396fd61">


### Validations

#### 1. Default is correctly pointing to v27.2.x and the url it is pointing to is correct
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/a79a9e94-a3f0-429c-b562-b383d6736570">

#### 2. URL for v27.1.x is correct
<img width="984" alt="image" src="https://github.com/user-attachments/assets/5995ce95-5cf7-4948-8638-d69dbcd606c4">

#### 3. URL for v27.0.x is correct
<img width="988" alt="image" src="https://github.com/user-attachments/assets/c8584fde-0ef2-4ccc-b72a-4d00fdf6aa2d">
