### ISSUE TITLE
Changes for Azure cloud provider for RKE1

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#11520]
Azure in-tree cloud provider has been removed for k8s >=1.30. We are adding docs on how to use External cloud provider for creating new Azure clusters and how to migrate from Azure to External cloud provider for k8s < 1.30.

This currently works with Edit as Yaml, but need the following changes in UI:

1.  Remove Azure from cloud provider dropdown for RKE1 and RKE2 clusters >= k8s 1.30.
2. Allow changing cloud provider from Azure to External in dropdown for RKE1 and RKE2 clusters for k8s >= 1.27 && k8s < 1.30 so users can migrate before upgrading to v1.30.

Related to https://github.com/rancher/dashboard/issues/11360 which is RKE2

**Comment by momesgin** [comment]
@kinarashah when in the RKE1 creation process and you've chosen Azure In-Tree option, if you select an unsupported k8s version i.e `< 1.30`, what option should be selected after?

Creating custom cluster:

![Image](https://github.com/user-attachments/assets/11e42a54-8c49-45c0-b1f6-480d15eacc26)

Creating Azure cluster:

![Image](https://github.com/user-attachments/assets/13812db9-4ab4-46ac-b5dc-e5c25533984e)

in case the answer is "External", can we display the same warning message for AWS here as well?

> The current Cloud Provider is not supported by this version of Kubernetes. The Cloud Provider has been changed to External. Please use the Cloud Provider Config to supply an out-of-tree configuration as needed.

**Comment by kinarashah** [comment]
@momesgin That's correct, we'd expect `External` cloud provider to be selected for k8s >=1.30. The text message also looks correct, would be helpful if we could link `Cloud Provider Config` to https://ranchermanager.docs.rancher.com/v2.9/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/azure#cloud-provider-configuration. Thank you!!

**Comment by IsaSih** [comment]
Blocked by https://github.com/rancher/dashboard/issues/11656

**Comment by IsaSih** [comment]
So, after going through https://ranchermanager.docs.rancher.com/v2.9/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/azure#using-the-out-of-tree-azure-cloud-provider and comparing the implementation in Azure with AWS, I'd like to understand why the UI offers only the External out-of-tree and not the Azure out-of-tree architecture as it's mentioned in the docs? For AWS, we have 3 options, as displayed in the screenshot. I assume this is a bug, but I'd like to double-check with you first.

![Image](https://github.com/user-attachments/assets/5bc06707-364a-4b59-990c-e409e41f2d16)

**Comment by IsaSih** [comment]
Also, I'm reopening the issue cause the in-tree option is still available for kubernetes 1.30. Tested on a rancher HA cluster deployed via helm install. Rancher version: v2.10-4e2703bb4f157be02dbc2f2828d99a5b1c61bb73-main

![Image](https://github.com/user-attachments/assets/112690b7-a18e-48c1-9caf-194d25a3d72a)

**Comment by IsaSih** [comment]
Options don't change. They're the same for all available kubernetes versions. 

https://github.com/user-attachments/assets/dbfb4e7a-4f95-4fcf-909e-a36cb1cf88be

**Comment by kinarashah** [comment]
@IsaSih We introduced `Amazon out of tree` as a new option because backend needed to distinguish between `--cloud-provider=external` vs `--cloud-provider=aws-external`. For `aws-external` there is custom logic in the codebase that is required for clusters to successfully provision out of the box. Azure on the other hand, works with the out of tree provider without requiring any code changes so we can work with (there are manual installation steps required same as amazon but no code changes in backend).

**Comment by IsaSih** [comment]
Tests pass on v2.9-952f563826f5cf0712289b068f3dff48fff1e856-head
Scenarios that were tested:
1 - Creating cluster with kubernetes version 1.30.3 w/ none cloud provider
2 - Creating cluster with kubernetes version 1.30.3 w/ external cloud provider out-tree
3 - Creating cluster with kubernetes version lower than 1.30.3 w/ cloud provider azure in-tree
4 - Updating cluster with kubernetes version lower than 1.30.3 w/ cloud provider azure in-tree to external cloud provider out-tree
5 - Updating cluster with kubernetes version lower than 1.30.3 w/ cloud provider azure in-tree to external cloud provider out-tree and upgraded kubernetes version to 1.30.3
