### ISSUE TITLE
Vue 3: Web Worker communication fails due to Proxy objects in messages

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11541]
After migrating to Vue3, some messages sent to the web worker would fail with the following error:

```
Uncaught (in promise) DOMException: Proxy object could not be cloned.
    createWorker subscribe.js:182
```

We temporarily resolved this problem by utilizing `cloneDeep()`[^1], but this isn't a sufficient approach for the long term. There are a few potential issues with this approach:

[^1]: https://github.com/rancher/dashboard/blob/vue3-depth-first/shell/plugins/steve/subscribe.js#L184

1. `cloneDeep()` might not be cloning Proxy objects, just copying references
2. Modifying references to proxy object might lead to unexpected behavior
3. Data stored in the web worker might not be fully detached from Vue's reactivity system

## Proposed Solution

There are several approaches that can address this issue, one that come to mind:

- Recursively check properties in a message and convert any proxies to raw objects using `toRaw()` [^2]

[^2]: https://vuejs.org/api/reactivity-advanced.html#toraw

**Comment by richard-cox** [comment]
Out of interest, what's the proxy object?

In theory we should just be receiving raw json over socket in the worker thread... and then the same from worker to ui thread

**Comment by rak-phillip** [comment]
Currently, I'm seeing the error for `loadSchemas`; although, I haven't identified precisely which property of `loadSchemas` might be the root cause of the issue.

It's important to note that Vue3's reactivity system is proxy-based now. So there's two possible scenarios:

1. We've been providing a reactive object to the worker all along and we're just seeing this error now because of the reactivity changes
2. Vue3 also doesn't have any of the change detection caveats of Vue2[^1], so it's entirely possible that we're inadvertently making a property of an object reactive when it previously wasn't

[^1]: https://v2.vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by richard-cox** [comment]
We're talking https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy? The UI used to use them to wrap models... but were dropped when there were major performance issues (i have the PR but there's no useful descriptio https://github.com/rancher/dashboard/pull/4373). Might need investigate if that's gone, given the changes you were talking about

**Comment by rak-phillip** [comment]
> We're talking https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy?

Yes, that's right.

> The UI used to use them to wrap models... but were dropped when there were major performance issues (i have the PR but there's no useful description https://github.com/rancher/dashboard/pull/4373). Might need investigate if that's gone, given the changes you were talking about

I don't think there's much to investigate in regards to our past proxy usage. This has to with the Vue3's reactivity model being proxy-based now[^1]. My intuition at the moment is that some property in `loadSchemas` is a reactive object from Vuex state.

WRT proxy performance issues, I recall FF patching performance a while back (can't remember the release), but there seems to be some indication that proxy performance has improved[^2]. Although, it's hard to say without more details about what the issues were on our end.

[^1]: https://vuejs.org/guide/extras/reactivity-in-depth.html#how-reactivity-works-in-vue
[^2]: https://bugzilla.mozilla.org/show_bug.cgi?id=1172313

**Comment by rancher-max** [comment]
The unit tests here are sufficient as the manual validation steps don't reliably reproduce the problem.
