### ISSUE TITLE
Harvester extension does not load correctly when switching between clusters

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11559]
**Setup**
- Rancher version: 2.9.0

**Describe the bug**
- Switching between harvester clusters of different versions fails to correctly load the version of the extension related to the target cluster
- Specific bugs can be found in https://github.com/rancher/dashboard/issues/9814#issuecomment-2253325637 (first two parts, after navigating from 1.2.x to 1.3.x)

**To Reproduce**
- Import two harvester clusters, one 1.2 based, one 1.3
- Navigate to the 1.2 based cluster - note no `vGPU DEvices` in `Advanced` side nav group
- Navigate to the 1.3 based cluster - note still no `vGPU DEvices` in `Advanced` side nav group

**Expected Result**
- vGPU advanced setting should show up in 1.3 cluster

**Additional context**
- spun out from https://github.com/rancher/dashboard/issues/9814#issuecomment-2253325637

- Logs from dev when navigating from 1.2.x to 1.3.x - not related to the current issue.

![image](https://github.com/user-attachments/assets/92de101d-bd56-4329-b231-5f8e81a42006)

**Comment by torchiaf** [comment]
Confirming that the bug impacts only prod builds. Everything works properly when running the UI locally. @richard-cox

**Comment by yonasberhe23** [comment]
Created a follow up ticket to add tests for this issue https://github.com/rancher/dashboard/issues/11676. moving to To Test for manual validation

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10.0-alpha11`
UI version: `v2.10.0-alpha6`
Harvester plugin version: `1.0.0`
Harvester clusters versions: `1.4-head` and `1.3.2` - (1.4 target is Rancher 2.10).

I was able to navigate without issues between the two imported Harvester clusters in the `Virtualization Management`. All advanced options were browsable and the common options too. No errors about loading page objects.
