### ISSUE TITLE
Missing `loading...` indicator when navigating to Harvester clusters

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#11565]
**Setup**
- Rancher version: latest

**Describe the bug**

Ui lost again the loading indicator when navigating to Harvester clusters (in general, when loading a UI plugin).

It was fixed in https://github.com/rancher/dashboard/pull/11376 but broke in recent 2.9 changes

**To Reproduce**

- Click on 'Vistualization Manager'
- Click on a Harvester cluster

**Result**

loading indicator is missing

**Expected Result**

Should show up the `loading... ` layer.

**Screenshots**

**Additional context**

**Comment by rancher-max** [comment]
Per our grooming session: We may be able to automate validations of this without the need for Harvester by artificially adding delay via the test in order to see this loading indicator in other areas.

**Comment by nwmac** [comment]
Closing - could not be reproduced by @torchiaf
