### ISSUE TITLE
Not able to deploy deployments with certificates as volumes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1157]
**On master-head - commit id: `8d9ced`**

- Navigate to Dashboard --> Deployments --> create --> Storage --> Certificates --> Select a certificate from the drop down
- UI does not select a certificate.
- On clicking "Create/Save" error seen: `Deployment.apps "test-cert" is invalid: [spec.template.spec.volumes[0].secret.secretName: Required value, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "vol0"]`
<img width="752" alt="Screen Shot 2020-08-31 at 6 03 47 PM" src="https://user-images.githubusercontent.com/26032343/91783449-232d4a00-ebb5-11ea-87ab-6c540502911e.png">

**Comment by mantis-toboggan-md** [comment]
This seems to have been fixed while volume claim templates were being fixed last week.

**Comment by sowmyav27** [comment]
**Verified on 2.5-head - commit id: `eb990af66` and ui-offline-preferred - false**
