### ISSUE TITLE
Create Pod and edit as yaml renders wrong Pod spec

### ISSUE THREAD

**Issue by xhejtman** [rancher/dashboard#11583]
**Setup**
- Rancher version: 2.9.0
- Rancher UI Extensions: 2.9.0
- Browser type & version: google chrome 127.0.6533.73 

**Describe the bug**

Go to UI, `Workloads` -> **Pods**, hit `Create`,  switch to yaml (`Edit as YAML`).

The Pod manifest is wrong as it contains the `template` section.

<img width="1845" alt="Screenshot 2024-08-02 at 12 51 43" src="https://github.com/user-attachments/assets/946e3391-1f18-4912-b4ef-8b1cbdd668a9">

Running the pod without YAML form is OK.

**To Reproduce**

as above

**Result**

invalid Pod manifest

**Expected Result**

correct Pod manifest

**Comment by rak-phillip** [comment]
@xhejtman thanks for raising this issue and helping to make Rancher better! We might follow up requesting more information as we triage this issue. 

Currently, I think that this might be a duplicate of #10171.

**Comment by xhejtman** [comment]
Indeed, it is duplicate of #10171.
