### ISSUE TITLE
Ellipsis on the deployment detail page does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1158]
**On master-head - commit id: `8d9ced`**

- Dashboard --> Deployment --> Create a deployment --> When it is created click on the deployment --> Detail page
- The ellipsis does not open a pop up windows with options. 

<img width="1448" alt="Screen Shot 2020-08-31 at 4 01 28 PM" src="https://user-images.githubusercontent.com/26032343/91783587-90d97600-ebb5-11ea-9183-f768610a7111.png">

**Comment by deniseschannon** [comment]
Per @ibuildthecloud,  it would be really nice if this was just the same as the pods list table (so I get multi select and bulk actions so I can delete pods).

**Comment by sowmyav27** [comment]
**On master-head - commit id: `33f755f1`**

- Ellipsis on deployment details page works
<img width="1628" alt="Screen Shot 2020-09-17 at 2 32 57 PM" src="https://user-images.githubusercontent.com/26032343/93531180-a5c34280-f8f3-11ea-987f-d11012f1f812.png">

- Delete on a pod deletes the pod
