### ISSUE TITLE
Cluster description on home page scales horribly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11588]
**Setup**
- Rancher version: 2.9.0

**Describe the bug**
- home page shows a list of clusters and the description underneath the name
- to get the description it was iterating over all prov clusters and then again over all mgmt clusters then overwriting the prov clusters description field
  - this scales very badly. this is a O(n^2) issue. See https://github.com/rancher/dashboard/pull/10782/files#diff-ce2886b60e5beaa460bae670bfe76933a652403ffe26ae1eca5877c3ea365e5aR213-R221
  - it can mutate the prov cluster. Example - prov cluster has no description but mgmt cluster has. user navigated to home page (prov cluster gets the mgmt clusters description, user then edits the cluster (thus saving the description)
    - this also has a weird knock on. home screen --> eks cluster detail page will show a description. refresh and no description

**To Reproduce**
- Performance: Load many clusters that churn, see churn in function
- Mutation: Create an EKS cluster in the old UI (with description). In new UI go to home page then edit the EKS cluster in the new UI (on edit page you'll see the description)
- Missing Description: Create an EKS cluster in the old UI (with description). In the new UI go to the home page then the detail page for the EKS cluster and the description will show. Refresh and it won't

**Expected Result**
- Performance: Should not degrade
- Mutations should not happen

**Additional context**
- Brought in via https://github.com/rancher/dashboard/pull/10782
- This can be easily modified to avoid looping and also overwriting the prov cluster description

**Comment by izaac** [comment]
There isn't support in the E2E tests for hosted providers or the Old UI. 

Is it possible to add a unit test for this?

**Comment by richard-cox** [comment]
@izaac the home page clusters work with an agnostic cluster resource type of provisioning cluster. RKE2 and hosted providers are created in the new ui via that prov cluster type. The old ui (ember / rke1) create clusters a different way but end up as prov clusters in the home page, that angle is covered by the second referenced PR.

**Comment by izaac** [comment]
Moving to done. Thanks for clarifying @richard-cox
