### ISSUE TITLE
Backport changes following bump to Monitoring chart / components

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11592]
- Need to co-ordinate with changes to charts
  - Reach out to @joshmeranda for details
- PRs to backport
  - https://github.com/rancher/dashboard/pull/11351
  - ~https://github.com/rancher/dashboard/pull/11529~

**Comment by gaktive** [comment]
@richard-cox how easy is this backport for 2.8.x? Upon discussion with Frameworks, this will help address issues for customers who haven't gone up to 2.9.x yet and I think this avoids some of our current Vue3 efforts. I'm wondering if this can still get back into next1 rather than next2.

**Comment by richard-cox** [comment]
Backports should be straight forward. We need to make sure these UI changes happen in the same release as the chart changes, otherwise we'll just break things. @joshmeranda can you confirm the chart bumps are going into 2.8.next1?

**Comment by joshmeranda** [comment]
Sorry just getting back from holiday. Seeing the we are releasing tomorow, so probably 2.8.next2 since 1 day is definitely too quick for QA.

Once that is released it will be easy to get this rebase backported

**Comment by richard-cox** [comment]
Grand. @joshmeranda just let us know when everything is merged and ready (is there an issue?)

**Comment by richard-cox** [comment]
Once https://github.com/rancher/charts/pull/4311#issuecomment-2374534692 merges we're good to go

**Comment by mallardduck** [comment]
@richard-cox - the chart PR is merged and ready to proceed here.

**Comment by richard-cox** [comment]
Note: required monitoring version is `103.2.0-rc.1+up57.0.3`. Visible only after updating the rancher chart repo to `dev-v2.8` and enabling `prerelease versions` from user preferences

**Comment by rancher-max** [comment]
### Validated using rancher v2.8-head

#### Version Information
<img width="709" alt="image" src="https://github.com/user-attachments/assets/f3c1cd82-8e64-420d-b14d-9704eccdb323">

- Rancher : v2.8-head
- cluster : v1.28.13+rke2r1
- rancher-monitoring : 103.2.0-rc.1+up57.0.3

#### Validation Information
- Alerts tab is correctly showing and is not empty
<img width="1321" alt="image" src="https://github.com/user-attachments/assets/ab6b9e77-f3cd-4ca9-a645-68951b11fdbb">

- Cluster Metrics, Kubernetes Component Metrics, and ETCD Metrics are all showing with graphs displayed
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/aaf8e520-5f1a-4af7-af83-fe9acf3bb028">
<img width="1331" alt="image" src="https://github.com/user-attachments/assets/ab86c6dc-621a-40af-81a0-8b3e2e870ab8">
<img width="1306" alt="image" src="https://github.com/user-attachments/assets/664fdbcf-faf0-4c4b-9db7-e73e7ae362e1">
