### ISSUE TITLE
Create Statefulsets throws Unknown schema error

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1159]
**On master-head - commit id: `8d9cedde9`**

- Dashboard -->Workloads --> Stateful sets from the cluster explorer view.
- Click on Create.

<img width="1447" alt="Screen Shot 2020-08-31 at 10 43 42 PM" src="https://user-images.githubusercontent.com/26032343/91799281-98ac1100-ebdb-11ea-9574-3093f60919b0.png">

- Unknown Schema is. seen.
<img width="746" alt="Screen Shot 2020-08-31 at 10 43 47 PM" src="https://user-images.githubusercontent.com/26032343/91799272-9649b700-ebdb-11ea-8d4b-dc3da750430b.png">

**Comment by deniseschannon** [comment]
Duplicate https://github.com/rancher/dashboard/issues/921
