### ISSUE TITLE
Vue3 unit test issues

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11620]
# Description

Currently, unit tests are failing above 60% and need to be addressed to ensure code quality and allow it to pass the check:

```
2024-08-08T15:31:29.5309461Z Test Suites: 104 failed, 1 skipped, 71 passed, 175 of 176 total
2024-08-08T15:31:29.5309940Z Tests:       595 failed, 7 skipped, 18 todo, 995 passed, 1615 total
```

https://github.com/cnotv/dashboard/actions/runs/10305010589/job/28524820577 (use row due rendering issues)

TBD:
- list of issues
- pipeline to be inspected (master or enable push on current working branch?)

**Comment by codyrancher** [comment]
Closing in favor of https://github.com/rancher/dashboard/issues/11682
