### ISSUE TITLE
Vue3 E2E breaks on setup 

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11621]
# Description

It looks like during the setup happens 3 errors:
1. Setup config malformed: `AssertionError: expected 12 to be above 13`, instance `aecc0238-a6f8-4789-8efb-ef748993099b`
2. Routing failing to return the correct URL:  `expected 'https://127.0.0.1/dashboard/auth/login' to include 'https://127.0.0.1/dashboard/auth/setup'`, instance `32c038ca-6bc0-45da-8484-0f71b83e747a`
3. Request is not returning any value: `bootstrapReq. No response ever occurred.`, instance `68bbaf7e-0322-4a26-b170-62b08f615b86`

## Screenshot

<img width="1524" alt="Screenshot 2024-08-09 at 15 10 23" src="https://github.com/user-attachments/assets/11404dc7-0a40-4512-af98-ea9a2988f9f4">

## Video

https://github.com/user-attachments/assets/8f148a23-938e-494f-b332-a63e123f012e

**Comment by codyrancher** [comment]
Just using the epic to track since there's about 60 failing e2e tests https://github.com/rancher/dashboard/issues/11622.
