### ISSUE TITLE
Create from workload Overview does not show replicaset

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1163]
**On master-head commit id: `c428bc9feb`**

- Cluster explorer --> Workload Overview --> Create
- "replicaset" type is NOT available.
<img width="1440" alt="Screen Shot 2020-09-01 at 11 05 38 AM" src="https://user-images.githubusercontent.com/26032343/91889750-31c24280-ec43-11ea-8ee7-9cdb076f8efe.png">

**Expected:**
"replicaset" be displayed as an option here

**Comment by deniseschannon** [comment]
This is purposely not included as part of the requirements: https://github.com/rancher/dashboard/issues/637#issue-616332651
