### ISSUE TITLE
Vue3 logout test failing for not finding table

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11632]
# Description

After migration logout test seems to be failing for not finding a table although it seems to be there:

**Intance:** a0b24251-e4d5-4aff-a1a1-3562c8572f72
**Job:** https://github.com/cnotv/dashboard/actions/runs/10356095483/job/28665295838#step:7:1113
**Commit:** https://github.com/cnotv/dashboard/commit/98abf887a92fe91be36482e16ffcf3b02d138601

## Screenshots

<img width="1489" alt="Screenshot 2024-08-14 at 11 23 36" src="https://github.com/user-attachments/assets/95e98101-a8eb-4f63-ad09-f9c36aa1ae1b">
<img width="1493" alt="Screenshot 2024-08-14 at 11 26 36" src="https://github.com/user-attachments/assets/f52a9c1c-e30b-4246-a89b-4e44989340c0">

## Video

https://github.com/user-attachments/assets/f390d3dc-8741-41fc-bb9f-8fcc27212a03

**Comment by codyrancher** [comment]
Just using the epic to track since there's about 60 failing e2e tests https://github.com/rancher/dashboard/issues/11622.
