### ISSUE TITLE
[2.9.1] AKS: Autogenerated nodepool name generated after deleting all nodepools and adding a new one does not comply with the naming convention

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#11634]
**Setup**
- Rancher version: v2.9-7bc90dd10e937ca1b7c03e217b884a863dcc8eb5-head
- Rancher UI Extensions: release-2.9 7296914
- Browser type & version: Firefox

**Describe the bug**

When all the nodepools of a cluster are deleted and a new one is added, the name used for it is `agentPool` which does not comply with the naming rule convention 'Node pool names must be 1-12 characters long, **consist of only lowercase letters** and numbers, and start with  a letter'.

**To Reproduce**

1. Edit an existing cluster or create a new one.
2. Remove all the existing nodepools and add a new one.
**Result**
The new nodepool is called 'agentPool'.
**Expected Result**

The new nodepool name must be 'agentpool'.

**Screenshots**

[Screencast from 08-14-2024 03:25:03 PM.webm](https://github.com/user-attachments/assets/d66bcb7a-8a51-4e34-ab12-a890c74b94cf)

**Additional context**

**Comment by richard-cox** [comment]
@mantis-toboggan-md This feels borderline for a 2.9.1 release blocker (code freeze is tomorrow)?

**Comment by yonasberhe23** [comment]
Unit tests seem sufficient. also did a quick manual check, all looks good in:  
- v2.9-63d8298029ce22942459eaaf0dbe084963c234c5-head
- release-2.9 37abd4d
