### ISSUE TITLE
Vue3 E2E Modals are not able to be confirmed and prevent further actions

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11633]
# Description

For at least 2 different reasons, the modals CTA are not able to be identified by the E2E tests on deletion. It may be related to some library changes and the fact classes are used as identifiers.
As a consequence, all the successive tests are unable to interact with the UI as the modal overlay is preventing them from doing so.

**Instance:** e6b8ac8f-abb6-4d96-a91c-19e47af18ea5/test/r7
**Job:** https://github.com/cnotv/dashboard/actions/runs/10356095483/job/28665295838#step:7:1113
**Commit:** https://github.com/cnotv/dashboard/commit/98abf887a92fe91be36482e16ffcf3b02d138601

## Screenshots

<img width="1542" alt="Screenshot 2024-08-14 at 11 31 45" src="https://github.com/user-attachments/assets/ad8b9689-a8cb-40b0-a108-81758c601688">
<img width="1525" alt="Screenshot 2024-08-14 at 11 31 35" src="https://github.com/user-attachments/assets/6f5e0a21-9b58-4a0d-8d9f-1ecc4ba8e7a2">
<img width="1496" alt="Screenshot 2024-08-14 at 11 33 49" src="https://github.com/user-attachments/assets/fb9b236a-066e-4ff1-88aa-de52a6147f61">
<img width="1501" alt="Screenshot 2024-08-14 at 15 59 36" src="https://github.com/user-attachments/assets/3c5b4f8c-98cc-4d19-bb33-386f31c7f30d">

## Video

https://github.com/user-attachments/assets/cec23833-d154-4f79-bcba-b73ae1a55b14

**Comment by codyrancher** [comment]
Just using the epic to track since there's about 60 failing e2e tests https://github.com/rancher/dashboard/issues/11622.
