### ISSUE TITLE
Create button not enabled if user manually inputs the resource on Role Creation page. 

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#11646]
**Setup**
- Rancher version: 2.9-head
- Rancher UI Extensions: NeuVector
- Browser type & version:

NeuVector QA was testing the newly added NeuVector permission with v2.9-head rancher build and found that they are not able to add roletemplate with services/proxy. This is very important for NeuVector SSO work for the user with non-admin role. This could be blocker for NeuVector Rancher RBAC feature configuration from Rancher UI. The create button is not highlighted if we type resource manually instead choosing from drop down. 

it seems like the Create button is not enabled if user manually input the resource on Role Creation page. For NV SSO with Rancher to work, we need the Rancher Role to have `*`  verb on `services/proxy` resource

**Screenshots**

**Additional context**
Works in 2.9.0

![image(1)](https://github.com/user-attachments/assets/f57d46d3-c883-4036-a5cc-71a543500a2b)

**Comment by yonasberhe23** [comment]
@richard-cox do we need automation for this still?

**Comment by richard-cox** [comment]
Neuvector QA team manually confirmed fixes, updating labels and closing
