### ISSUE TITLE
Ember UI not loading - RKE1

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#11656]
**Setup**
- Rancher version: v2.9-a8d35225e80f75eed9937f556de90f0b57d1729f-head and v2.10-ac7c9ae6db37820d121e19731db85e31ed9683b1-main
- Installation: via `docker run --privileged -d --restart=always -p 8084:80 -p 8444:443 --name rancher2.10 rancher/rancher:head` and `docker run --privileged -d --restart=always -p 8083:80 -p 8443:443 --name rancher2.9 rancher/rancher:v2.9-head` 
Also reproduced the issue in a HA cluster - EC2 linux ubuntu machines - rancher installed via helm chart 
version: v1.28.12+k3s1
- No Rancher extensions installed
- Browser version: Version 126.0.6478.183 (Official Build) (arm64) Google Chrome
- Browser extensions installed: AdBlock, Adobe Acrobat, Mailsuite-Mailtrack, GoFullPage, Google Docs Offline, Grammarly, Save to Google Drive, tweak, Urban VPN Proxy

**Describe the bug**

By trying to provision an RKE1 cluster, the ember UI fails to render.

**To Reproduce**

1- From the Rancher homepage or clusters management, hit 'Create' 
2- Select RKE1
3- Select any cloud provider of your choice

**Result**
Ember UI fails to render 

**Expected Result**
UI should render on the page and be interactive as expected

**Screenshots**

https://github.com/user-attachments/assets/6ef03272-0ab5-43d7-96d9-107c7da47e1a

<img width="1712" alt="Screenshot 2024-08-16 at 15 33 29" src="https://github.com/user-attachments/assets/3217a6ae-cc54-44ae-9902-e43d19c3c16e">
mov…

**Comment by richard-cox** [comment]
- docker v2.9-head (ce5968): looks good
- helm v2.9-head: TBD

> Notes
> - only 2.10 has the ember bump
> - from the video looks like the form is shown before being hidden
> - last 2.9 ui change was 14th Aug

@IsaSih do you have any rancher extensions installed, or any browser extensions

**Comment by IsaSih** [comment]
I updated the installation instructions and the browser extensions. I was not able to reproduce it in Safari, just on Chrome.

**Comment by eva-vashkevich** [comment]
have you tried the hard reload?

**Comment by eva-vashkevich** [comment]
I've installed all of the same extensions and Ember ui still loads

**Comment by IsaSih** [comment]
After further investigation with @richard-cox , the issue was caused by the proxy of the browser Urban VPN extension that is preventing the ember UI to load. This happens on both 2.10-head and 2.9-head. So, I'm closing the issue as it seems that this is a bug on their end.

**Comment by eva-vashkevich** [comment]
Just i case this issue comes back, I've tried installing Urban VPN and configuring it the same way Isabela does but Ember UI still loads for me.
I am using Version 127.0.6533.120 (Official Build) (arm64)
Urban VPN proxy 4.9.2


<img width="1879" alt="Screenshot 2024-08-20 at 11 40 26 AM" src="https://github.com/user-attachments/assets/400bfa21-ca1a-47a7-83f3-06eae102e7b1">
