### ISSUE TITLE
[2.9] Custom Homepage doesn't work after upgrading rancher to 2.9

### ISSUE THREAD

**Issue by nowcom-johnperez** [rancher/dashboard#11654]
**Setup**
- Rancher version: 2.9
- Rancher UI Extensions: 2.0.1
- Browser type & version: Latest Chrome & Latest Safari

**Describe the bug**
Custom homepage doesn't work anymore after upgrading to rancher 2.9

**To Reproduce**
Upgrade to Rancher 2.9, install Homepage extension or create an extension that overrides the homepage

**Result**
It will show the default homepage

**Expected Result**
Show the custom homepage

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment]
Can you confirm you've read through https://extensions.rancher.io/extensions/rancher-2.9-support, updated `shell` and re-published (or loaded a dev build)?

Are there any errors in the browser's console?

**Comment by nowcom-johnperez** [comment]
> Can you confirm you've read through https://extensions.rancher.io/extensions/rancher-2.9-support, updated `shell` and re-published (or loaded a dev build)?
> 
> Are there any errors in the browser's console?

yep, I've read the documentation, updated shell and loaded a dev build, I don't see any errors.. mostly warning related to `window.$nuxt`

![Screenshot 2024-08-17 at 2 38 49 AM](https://github.com/user-attachments/assets/94aa2e1a-70fd-4c68-894f-ac08d0b2c448)

**Comment by IsaSih** [comment]
Tests pass on v2.9-db67b4e146cf85fda7803c01b79c0283269f0975-head

![Image](https://github.com/user-attachments/assets/376a6c7d-2b62-407f-bc1c-1aecbd127a4b)
