### ISSUE TITLE
[2.10] Custom Homepage doesn't work after upgrading rancher to 2.9

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#11658]
Forward port of https://github.com/rancher/dashboard/issues/11654

**Setup**
- Rancher version: 2.9
- Rancher UI Extensions: 2.0.1
- Browser type & version: Latest Chrome & Latest Safari

**Describe the bug**
Custom homepage doesn't work anymore after upgrading to rancher 2.9

**To Reproduce**
Upgrade to Rancher 2.9, install Homepage extension or create an extension that overrides the homepage

**Result**
It will show the default homepage

**Expected Result**
Show the custom homepage

**Comment by nwmac** [comment]
Already fixed by https://github.com/rancher/dashboard/pull/11863

**Comment by yonasberhe23** [comment]
based on offline conversation, this issue does not appear in 2.10. moving to done.
