### ISSUE TITLE
OS Management Extension Not Available in Rancher v2.9

### ISSUE THREAD

**Issue by KarmaPoliceT2** [rancher/dashboard#11657]
In a fresh install of Rancher v2.9 (not Rancher Prime) I can't find the OS Management Extension, I see only Kamaji as an available extension.

I saw in this issue https://github.com/rancher/dashboard/issues/11372 that it suggests the OS Management Extension is only available in Prime, however when I look at the "Detailed Comparison" of Rancher SKUs here: https://www.rancher.com/products/rancher-platform

It shows all three versions should have OS Management with Elemental
![image](https://github.com/user-attachments/assets/6145241d-0f16-45b8-98da-6a35df7c2110)

![image](https://github.com/user-attachments/assets/ee0cf518-d7b4-4d6f-abf4-b820c9e65121)

Can you please clarify and make the appropriate fix in one place or another?

**Comment by nwmac** [comment]
@KarmaPoliceT2 The built Elemental extension is only available for Prime:

![image](https://github.com/user-attachments/assets/684be2bb-ac3b-4228-823a-984709830366)

The source code is open source, so you can build the extension and load that into Rancher (Rancher or Rancher Prime).

**Comment by nwmac** [comment]
Please re-open if you have more questions
