### ISSUE TITLE
Handle rancher/rancher 2.10 image tagging change

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#11667]
The UI behaves slightly differently in dev builds, see https://github.com/rancher/dashboard/issues/9734 for context. As of 2.10 rancher/rancher latest versions will end in `-main` where they previously ended in `-head`: the UI needs to be updated [here](https://github.com/rancher/dashboard/blob/master/shell/utils/version.js#L77-L83) to correctly detect that these `-main` versions are dev builds.

The easiest place to manually test this is the release notes link on the home page - on dev versions, the link should be to the latest release notes https://github.com/rancher/rancher/releases/latest (this will redirect to v2.9.0 right now).

To test this issue:
1. Bring up a fresh Rancher 2.10 instance using the `rancher/rancher:head` image tag
2. Verify that during setup in the UI, the telemetry checkbox is _not_ checked by default
3. After logging in, verify that the 'See what's new" link on the home page is valid (https://github.com/rancher/rancher/releases/latest)

**Comment by mantis-toboggan-md** [comment]
Ember PR: https://github.com/rancher/ui/pull/5163

**Comment by richard-cox** [comment]
Should be resolved via https://github.com/rancher/rancher/pull/46757

**Comment by IsaSih** [comment]
Test pass on v2.10-61d79963733364046c6fc8e9003bd9d6948a6db0-head Dashboard | master d29392f
