### ISSUE TITLE
v2 Istio - Values yaml is difficult to edit

### ISSUE THREAD

**Issue by bmdepesa** [rancher/dashboard#1166]
rancher/rancher:master-head c428bc9

* Rancher helm install
* Deploy cluster
* Navigate to dashboard
* Install Apps > `rancher-istio`
* Click on `Values YAML` and make some changes
* As the user is typing, the cursor location and values being entered are moved around

![istio-yaml-editor](https://user-images.githubusercontent.com/21316915/91916998-8b426580-ec73-11ea-978e-ba9cb13d71d2.gif)

* This does not occur in other places like editing workload yaml

**Comment by vincent99** [comment]
The variable backing the value was being overwritten every time the yaml toggled between having errors and parsing successfully, which confuses the editor into rerendering everything and losing the cursor.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 198ec5b

This is still occurring

**Comment by deniseschannon** [comment]
I'm unable to reproduce this. @bmdepesa Can you try again?

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ec04f78

I'm still seeing this with pretty much the exact same behavior. 

Go to values yaml and add:
```
prometheus:
  enabled: true
```

and it moves the cursor near immediately.

**Comment by brendarearden** [comment]
I am also seeing this behavior in ec04f78 with the latest chrome version.

**Comment by vincent99** [comment]
I don't know what was wrong with the particular copy in istio, but this chart config was working differently than every other chart by having it's own copy of the full values-yaml visible all the time instead of being toggled by the "Edit as YAML" button at the bottom.  So I reproduced the problem, removed that version, and the normal values yaml editor seems ok.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head cc777eb

* The old editor is removed
* Editing as YAML shows the values yaml and does not have the same issue. 
* Editing as YAML and saving deploys the app with the correct values
