### ISSUE TITLE
[Monitoring V2 UI] Prevent deploy when Prometheus Operator already exists

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1167]
As discussed in https://github.com/rancher/rancher/issues/25044 (specifically https://github.com/rancher/rancher/issues/25044#issuecomment-671531531), deploying multiple Prometheus Operator pods onto one cluster is not recommended by the upstream chart since multiple operators could be managing the same CRs within the same namespaces.

As a result, when a user tries to deploy Monitoring V2, we should check to see if there are any pods with the Prometheus Operator image that are currently deployed onto the cluster that could cause issues.

i.e. check if either `quay.io/coreos/prometheus-operator:<any version>` or `rancher/coreos-prometheus-operator:<any version>` (in the case of Monitoring V1 or another Monitoring V2 deployment) shows up in the following list:
```
kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}"
```

If this is the case, the user should be presented with a warning that says:
```
Warning: Deploying multiple Prometheus Operators onto one cluster is not currently supported. Please remove any other Prometheus Operator deployments from this cluster before trying to install this chart.

If you are migrating from an older version of Rancher with Monitoring enabled, please disable Monitoring from the cluster completely before attempting to install this chart.

If you would still like to continue with the installation, please click on `Continue with Install`.
```

This check does not need to happen if the `Deploy Prometheus Operator` field in the Monitoring V2 UI Advanced Configuration (https://github.com/rancher/dashboard/issues/909) is set to false since we will not be deploying an operator onto the cluster in that case.

#### QA: What needs to be tested after this change?
Should show a warning:
- A cluster with Monitoring V1 enabled
- A cluster with [upstream Prometheus Operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) deployed

Should not show any warning:
- A clean cluster should not show any warning
- A cluster with Monitoring V1 enabled and then disabled
- Any of the cases in `Should show a warning` when `Deploy Prometheus Operator` is disabled

For the `Deploy Prometheus Operator` disabled option, we should check to see if that allows Monitoring V2 to be successfully deployed onto the cluster or track any issues for why this use case would not be supported (in which case we should roll back the UI changes for this till those issues are resolved as well). This will help in eventually providing documentation on how something like https://github.com/rancher/rancher/issues/25044 can be supported in the future.

**Comment by westlywright** [comment]
I talked with @deniseschannon a little and this warning will not come as any kind of popup or prevention, rather the warning will show up from the start and we wont disable the install button. IMO it doesn't make sense to let the user completely configure the chart values, only to find out at the end they have to back out to disable some stuff. Since the advanced case (when implemented) will allow the user to disable deploying the prometheus operator all together it wouldn't make sense to disable all together either. 

With the changes the new warning will say 
```
Warning: Prometheus Operators are currently deployed. Deploying multiple Prometheus Operators onto one cluster is not currently supported. Please remove all other Prometheus Operator deployments from this cluster before trying to install this chart.
If you are migrating from an older version of Rancher with Monitoring enabled, please disable Monitoring on this cluster completely before attempting to install this chart.
```

**Comment by jiaqiluo** [comment]
on a downstream cluster in rancher:`master-f1a410a97e2abf8c81c62195a7b40f10007398f0-head` docker insall 

see the warning message in the following scenarios:
- try to install monitoring v2 when cluster monitoring v1 is enable 
- try to install monitoring v2 when project monitoring v1 is enable 
- try to install monitoring v2 when monitoring v2 is already installed
- try to install monitoring v2 when the upstream Prometheus Operator is deployed

not see the warning message in the following scenarios:
- a clean cluster should not show any warning
- a cluster with Monitoring V1 enabled and then disabled
