### ISSUE TITLE
Helm App Upgrade: Add support for new label on ClusterRepo to help when identifying source repository for updates

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#11675]
EPIC: https://github.com/rancher/dashboard/issues/11465

Backend: https://github.com/rancher/rancher/pull/45997

Goal:

In the UI code that tries to find the correct chart to use when suggesting an upgrade to an app for a user, we should use the ner label added by the backend team - this will help to avoid the situation where we show an upgrade from a different chart repository to the one the app was installed from.

This should be a case of updating `matchingChart` here - https://github.com/rancher/dashboard/blob/master/shell/models/catalog.cattle.io.app.js#L50

If we do NOT have the annotations, then we should look for the predered repo name from the new label (`catalog.cattle.io/cluster-repo-name`), if it is there, we use that and we use a prefered repo type of `cluster`.

**Comment by gaktive** [comment]
@momesgin can assist whoever picks this up based on his past experience. Other tickets under the epic should have examples to help.

**Comment by izaac** [comment]
@eva-vashkevich is it correct that this only applies to charts installed by Rancher or through Rancher and not to those installed using `helm` directly on the cluster?

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head`
UI version: `master 78df731`

The new label is properly added to the apps installed by Rancher or installed through Rancher with Rancher repos. This seems to allow Rancher differentiate between equally named/versioned apps by using this label.

I also checked this label is also applied too to Kubewarden.
