### ISSUE TITLE
Vue3: Popover regressions in header

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11684]
The popovers used in the header have regressed in the following ways:

1. They are styled incorrectly and do not match the global theme
2. The remain open and cannot be closed

### Affected components

- User popover
- Set as login page popover

## Acceptance Criteria

- [ ] Affected components match the style, as it was defined in v2.9.0
- [ ] Affected components can open and close in the same way as they did in v2.9.0

## Screenshots

 
![set-as-login-popover](https://github.com/user-attachments/assets/a69f38bd-3bda-4496-8b9e-42dab455a37b)
![user-popover](https://github.com/user-attachments/assets/f03ac153-0a6a-486a-b2f8-d6487f1c7790)

## Additional info

- #11729
- #11730

**Comment by rak-phillip** [comment]
There's a `floating-vue` migration guide that might be useful[^1] for debugging some of the regressions.

[^1]: https://floating-vue.starpad.dev/migration/migration-from-v2

**Comment by izaac** [comment]
Is mostly styling, and the auth provider issue is not yet automated but tasks are in the QA Task UI project.
