### ISSUE TITLE
Vue3: Set as login page popover disappears

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11685]
The set as login page popover will disappear when navigating between home and different clusters.

## Reproduction steps

1. Begin on the home page
2. Navigate to Cluster Management
3. Observe the popover navigation element in the header
4. Navigate to the Local Cluster Explorer
5. Observe the popover navigation element in the header
6. Navigate to home
7. Navigate to the Local Cluster Explorer

## Actual Result

The popover navigation element is not rendered in the header

![popover-missing](https://github.com/user-attachments/assets/f4225be8-87b3-4655-9e5d-2c77299778a8)

## Expected Result

The popover navigation element is rendered in the header

![popover-present](https://github.com/user-attachments/assets/0ac5c639-3aaf-46ab-9752-1c5f208de71c)

## Acceptance Criteria

Regardless of whether or not the correct behavior is to display the popover or not in the Local Cluster Explorer, it should be consistent on each navigation.

- [ ] Showing/Hiding the popover does not regress from how it behaved in 2.9.0

**Comment by izaac** [comment]
The updates to E2E tests looks good. Moving to done. An skip was removed so this test is now executed.
