### ISSUE TITLE
Vue3: Create Persistent Volume - Clicking on "Edit as YAML" throws unhandled exception

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11687]
Clicking on "Edit as YAML" while creating a Persistent Volume will throw an unhandled exception:

```
Error: Cannot find resourceFields for Schema rke-machine-config.cattle.io.digitaloceanconfig (schemaDefinitions have not been fetched) 
```

## Reproduction steps

1. Navigate to Local Cluster Explorer => Storage => PeristentVolumes
2. Click Create
3. Click "Edit as YAML"

## Expected behavior

The YAML editor is rendered instead of the form

## Actual behavior

An unhandled exception is thrown.

## Acceptance criteria

- [ ] The YAML editor is rendered properly after clicking the "Edit as YAML" button

## Notes

I doubt that this behavior is limited to PersistentVolumes, this is only where it was observed. We should test the "Edit as YAML" button in other forms to confirm its behavior has not regressed elsewhere.

**Comment by izaac** [comment]
E2E test adjustments and additions look good. 👍🏽
