### ISSUE TITLE
Vue3: Namespace Selector with multiple namespaces has wrong hover

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#11689]
After selecting 3+ namespaces we stop displaying individual namespaces and instead show a number with a popdown. The popdown shows html instead of a list of namesapces.

https://github.com/user-attachments/assets/d3fdb621-07d5-48bc-8600-60d38b8db52f

## Acceptance Criteria

- [ ] The hover should display the appropriate text.
![image](https://github.com/user-attachments/assets/c611400d-b4b8-461d-b5db-4dbaeddc7bb9)

**Comment by izaac** [comment]
Could a hover check or the expected list of namespaces test added?

**Comment by momesgin** [comment]
@izaac considering this is a vue3 regression issue, could we do a manual test for this?

**Comment by izaac** [comment]
Sure move to To Test please

**Comment by izaac** [comment]
Validated on Rancher `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1` 

Namespaces are correctly shown when hovering over the dropdown
