### ISSUE TITLE
Revisit Extension creator mechanism

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#11681]
Follow on to #11484 

**Is your feature request related to a problem? Please describe.**
There were a few changes requested in #11605, they should be addressed.

> Previous behaviour is that the creator will create etc using the shell version of the creator.
> For the update behaviour, the idea being that the logic to do the update was in the creator with the same version as the shell.
_Originally posted by @nwmac in https://github.com/rancher/dashboard/pull/11605#discussion_r1726833041_

> How does a user create a new extension with a specific shell version?
> _Originally posted by @nwmac in https://github.com/rancher/dashboard/pull/11605#discussion_r1726833481_

> Seem to have lost the formatting we use with out lint rules
> _Originally posted by @nwmac in https://github.com/rancher/dashboard/pull/11605#discussion_r1726828791_

> Can we call this 'my-extension' rather than 'my-app' ?
> _Originally posted by @nwmac in https://github.com/rancher/dashboard/pull/11605#discussion_r1726828265_

**Comment by aalves08** [comment]
@jordojordo I think that from all the points above we are only missing the update behaviour right?

**Comment by jordojordo** [comment]
@aalves08 I believe that logic exists when running `yarn create @rancher/extension --update`, this will run the update script without changing the shell version.
