### ISSUE TITLE
Vue3: List of installed extensions fails to render

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11696]
Navigating to the extensions page fails with the following warnings:

```
[Vue warn]: Property "repos" was accessed during render but is not defined on instance. 
  at <Index class="outlet" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView key="/c/local/uiplugins" class="outlet" > 
  at <IndentedPanel class="pt-20" > 
  at <Plain onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView key=1 > 
  at <App>
```

Additional warnings:

```
Resource error [cluster] event : event watch error: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
```

```
Resource error [cluster] apps.deployment : event watch error: an error on the server ("unable to decode an event from the watch stream: http2: response body closed") has prevented the request from succeeding
```

## Reproduction steps

Navigate to extensions

## Actual Behavior

Tabs on the extensions page are rendered, but with no content rendered

![extensions-empty](https://github.com/user-attachments/assets/c57cfaeb-eacb-4c76-8730-ffd9953d419e)

Warnings are printed to the console.

## Expected behavior

Available extensions are rendered in the tab. Switching between tabs renders the correct content.

**Comment by jordojordo** [comment]
Initial investigation leads to the extra `template` element causing the issue. If the `template` element at [line `773`](https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/uiplugins/index.vue#L773) and the closing `template` at [line `966`](https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/uiplugins/index.vue#L966) are both removed the extensions list will appear.

**Comment by izaac** [comment]
Pre-existing test coverage was fixed and pass.
