### ISSUE TITLE
Vue3: Clicking on Describe Resource throws unhandled exception

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11699]
## Reproduction steps

1. Navigate to Local Cluster Explorer => Workloads => Deployments
2. Click on Describe Resource in the header

## Actual behavior

An error overlay is rendered and an error is printed to the console:

```
Uncaught (in promise) TypeError: slideInPanelClass is not a constructor
    explain slide-in.js:27
    invoke index.ts:29
    handleExtensionAction Header.vue:351
    onClick Header.vue:602
```

## Expected behavior

The Describe Resource panel is rendered.

## Additional information

- #11800

**Comment by izaac** [comment]
E2E coverage looks good to me for this scenario. Closing.
