### ISSUE TITLE
Vue3: Installed extensions throw unhandled exception 

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11695]
Navigating to the local cluster while an extension is installed can throw an unhandled error, causing Dashboard to stop functioning.

## Reproduction steps

In a stable Rancher instance running dashboard with Vue2, install the following extensions from the [ui-plugin-examples](https://github.com/rancher/ui-plugin-examples) repository. The following extensions were installed for this test:

- Clock
- Extensions-Api-Demo
- Large Extension

When starting a development server, make sure that you use the stable instance of Rancher as the backend for testing.

In the development version of Rancher running dashboard with Vue3, navigate to the Local Cluster Explorer.

## Actual behavior

An error overlay is rendered with the following:

```
Uncaught (in promise) TypeError: can't access property "extend", c.a is undefined
    eb32 Banner.vue:6
    Webpack 128
[Banner.vue:6:15](webpack://extensions-api-demo-0.1.0//Users/aalves/Desktop/PROJECTS/alex-ui-plugin-examples/node_modules/@rancher/shell/rancher-components/Banner/Banner.vue?ca18)
```

Other warnings are logged to the console:

```
[Vue warn]: Invalid VNode type: undefined (undefined) 
  at <Component resource= 
Object { id: "local", type: "management.cattle.io.cluster", links: {…}, actions: {…}, apiVersion: "management.cattle.io/v3", kind: "Cluster", metadata: {…}, spec: {…}, status: {…}, … }
 > 
  at <SimpleBox key="extensionCards0" class="extension-card" style=undefined > 
  at <ClusterExplorerIndexPage class="outlet" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView key="/c/local/explorer" class="outlet" > 
  at <Default onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< null > > 
  at <RouterView key=1 > 
  at <App>
```

## Expected behavior

The Local Cluster Explorer renders the same way that it does without extensions installed.

**Comment by codyrancher** [comment]
I think we should resolve this in a way where we don't load the plugins unless they target rancher 2.10 or greater. @jordojordo do you remember which label/annotation we should use for this?

**Comment by jordojordo** [comment]
@codyrancher we would use the `catalog.cattle.io/rancher-version` annotation.

**Comment by nwmac** [comment]
@codyrancher @jordojordo The answer here I thought was that for Vue 3, we would require the api version annotation to be there (not the rancher version one). If it is not present, then we assume the api version (now = shell version), is <2 (ie. before Vue 3) and we therefore would not load.

So, Vue 3 extensions need to have the annotation that says which version of the extensions API they need. If not present, then API for Vue 2.

**Comment by codyrancher** [comment]
> @codyrancher @jordojordo The answer here I thought was that for Vue 3, we would require the api version annotation to be there (not the rancher version one). If it is not present, then we assume the api version (now = shell version), is <2 (ie. before Vue 3) and we therefore would not load.
> 
> So, Vue 3 extensions need to have the annotation that says which version of the extensions API they need. If not present, then API for Vue 2.
> 
> So we should not need to add annotations to old Vue 2 extensions.

Are you suggesting we add a new version annotation? 

From existing documented versioning https://extensions.rancher.io/extensions/advanced/version-compatibility I would think `ui-version` or `rancher-version` would be most appropriate. It depends on what `Extension version will be loaded but will appear as disabled` means. 

If the js bundle isn't loaded using `ui-version` I would think we'd go with that otherwise `rancher-version`.

**Comment by yonasberhe23** [comment]
I believe our extension tests are sufficient for this update however many of them have been skipped before the Vue3 migration to allow for pipeline to be clear of issues. There is an on going effort to enable those tests but since we're not running them atm lets validate this manually. Moving to To Test

<img width="560" alt="Screenshot 2024-10-18 at 11 12 30 AM" src="https://github.com/user-attachments/assets/04016299-b1c5-46a3-af52-8dbd2bae3d3b">

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head`
UI: `master 78df731`

This was covered while validating: https://github.com/rancher/dashboard/issues/11474
The local cluster page was rendered correctly without errors in the UI neither in the browser's console.
