### ISSUE TITLE
Vue3: Resource Detail: Config View: Renders incorrectly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11716]
**Setup**
- Rancher version: dev 2.10.0

**Describe the bug**
- detail page's view config renders incorrectly

**To Reproduce**
- Pods list --> pod --> `Confg` tab
- cluster list --> cluster --> `Config` tab
- etc

## Additional Info

This is most likely related to changes in how slots are managed in Vue3. We had similar issues with rendering slot content when rendering create pages for provisioning new clusters. You can reference [shell/components/CruResource.vue](https://github.com/rancher/dashboard/pull/11686/commits/aedd3348035cebaeeea57832e5947f780511fdcd#diff-3949ec5a78c462b58bebb75bc06ccea895056a12129a9a8b8841dac3dd6b07d0) for more details.

**Result**
main content layout seems to push form to right

**Expected Result**
pre vu3 merge

**Screenshots**
### 2.10 (Vue3)

![image](https://github.com/user-attachments/assets/0d2a2354-70bf-4a73-a4f1-aa041c61820c)

![image](https://github.com/user-attachments/assets/f4925a18-9663-492d-987f-af53c9730add)

### 2.9 (Vue2)

![Image](https://github.com/user-attachments/assets/5fcbf3b5-2e54-4780-a11a-05dbf2e4ed83)

**Comment by izaac** [comment]
Visual styling moving to done.
