### ISSUE TITLE
Vue3: JWT Authentication list: horizontal spacing issue

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11719]
**Setup**
- Rancher version: dev 2.10.0

**Describe the bug**
- No spacing on left or right of JWT Authentication page
- Need to understand why this is now broken (not just fix for specific page)

**To Reproduce**
Cluster management --> Advanced --> JWT Authentication

**Screenshots**
![image](https://github.com/user-attachments/assets/f9df7b10-1332-4272-801e-9a3ebeadaa20)

**Comment by codyrancher** [comment]
Based on other issues I've seen I would guess that this is related to a missing or misplaced `.outlet` class on one of the elements of this page. Possibly related to `inheritAttrs: false`.

**Comment by izaac** [comment]
Styling issue, moving to done.
