### ISSUE TITLE
Vue3: API Key Create Page: vertical spacing issue

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11720]
**Setup**
- Rancher version: dev 2.10.0

**Describe the bug**
- vertical spacing broken
- need to understand why this style issue broke, could apply in other places

**To Reproduce**
User avatar --> Account & API Keys -->  Create API Key

**Result**
![image](https://github.com/user-attachments/assets/c4a1df2a-e271-4870-ab01-413ff229bcd8)

**Expected Result**
![image](https://github.com/user-attachments/assets/9c49784c-186c-48f1-9520-9ed0d1300536)

**Additional context**
- Similar spacing issue https://github.com/rancher/dashboard/issues/11719 (but horizontal)

**Comment by aalves08** [comment]
Moving to `To Test` because it got fixed by https://github.com/aalves08/dashboard/commit/47217a4c4c914e037fafaaba9121630c588d6457
