### ISSUE TITLE
Vue3: Namespace selector - Items hover/selected styling doesn't work

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#11728]
**Result**
<img width="284" alt="image" src="https://github.com/user-attachments/assets/024d3eea-439e-4845-bba7-99a6529e5134">

**Expected Result**
<img width="284" alt="image" src="https://github.com/user-attachments/assets/1d33f1f9-4b43-4ea0-8020-570174455f80">

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

Validated this is working properly and no errors in the browser console.
