### ISSUE TITLE
Vue3: API Key Create Page: numberical input rockers fail to work

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11723]
**Setup**
- Rancher version: dev 2.10.0

**Describe the bug**
- Custom expiration unit input field broken, rockers clear value and produce console warning
- could be related to https://github.com/rancher/dashboard/issues/11722?

**To Reproduce**
 - Nav to User Avatar --> Account & API Key --> Create API Key --> toggle to `Custom`

**Result**
- 0 is replaced with empty text
- in console `The specified value "[object Event]" cannot be parsed, or is out of range.`

**Expected Result**
- rockers work, no console warning

**Comment by izaac** [comment]
Was this catched by an existing test?

**Comment by rak-phillip** [comment]
I believe this was caught manually. There was no failing automated test associated with this issue when I raised the PR; keep in mind that we had a lot of tests marked as skipped at the time. 

Even today with a more comprehensive test suite, I don't think this specific issue will be covered.

**Comment by izaac** [comment]
@rak-phillip got it move it to done. Thanks
