### ISSUE TITLE
[CIS v2]  UI for ClusterScanBenchmark CRD

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1173]
Need UI to be able to handle ClusterScanBenchmark CRs:

**ClusterScanBenchmark CRD Explanation:**

- A ClusterScanBenchmark defines the CIS BenchmarkVersion name and test configuration. The BenchmarkVersion name is a parameter provided to the kube-bench tool.

- By default few BenchmarkVersion names and test config are packaged as part of this feature. 
When this feature is enabled, following default BenchmarkVersions will be auto installed and available for user to create a ClusterScanProfile. 
   a) rke-cis-1.5-permissive
   b) rke-cis-1.5
   c) gke-1.0
   d) eks-1.0
   e) cis-1.5

- If a user edits the default BenchmarkVersions, the next chart update will reset them back. So it is advisable for users to not edit the default ClusterScanBenchmarks.

- A ClusterScanBenchmark consists of fields:

   - ClusterProvider: This is the cluster provider name for which this benchmark is applicable. example: rke,eks,gke etc. Leave it empty if this benchmark can be run on any cluster type.
   - MinKubernetesVersion: Specifies the cluster's minimum kubernetes version necessary to run this benchmark. Leave it empty if there is no dependency on a particular k8s version.
   - MaxKubernetesVersion: Specifies the cluster's maximum kubernetes version necessary to run this benchmark. Leave it empty if there is no dependency on a particular k8s version.

ClusterScanBenchmark  CR defines the benchmark version and other fields like:
- ClusterProvider string `json:"clusterProvider,omitempty"`
- MinKubernetesVersion string `json:"minKubernetesVersion,omitempty"`
- MaxKubernetesVersion string `json:"maxKubernetesVersion,omitempty"`
- CustomBenchmarkConfigMapName string `json:"customBenchmarkConfigMapName,omitempty"`
- CustomBenchmarkConfigMapNameSpace string `json:"customBenchmarkConfigMapNameSpace,omitempty"`

UI options:
- Listing default ClusterScanBenchmark CRs
- Create/Edit/Clone YAML/Delete - **Can these options be disabled?** ClusterScanBenchmark cannot be created by a user and currently only default installed ClusterScanBenchmark's can be used to run a clusterscan

**Comment by deniseschannon** [comment]
List Page 
- [ ] Remove the create option

**Comment by deniseschannon** [comment]
When we allow custom benchmarks, we should look into this.

**Comment by prachidamle** [comment]
@maggieliu @vincent99 since we are adding the backend for custom benchmarks in 2.5.4, should we add this in UI now?

**Comment by prachidamle** [comment]
We need the full list of clusterproviders to be used that we support.
Also check how backend behaves if a different provider is set.

**Comment by vincent99** [comment]
List of providers: https://github.com/rancher/kubernetes-provider-detector/tree/master/providers

**Comment by prachidamle** [comment]
The backend reads the cluster's provider using the above library and so if something different is set via kubectl, there will be an error running the scan

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bb69b03 `**

- Able to create a custom benchmark and use it in a scan profile/scan and run a scan.
- Any other issues are being tracked separately. 
- Closing this issue.
