### ISSUE TITLE
Vue3: Tooltip lost styling

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11740]
**Setup**
- Rancher version: dev 2.10.0

**Describe the bug**
- lost styling on tooltip popup
  - black background
  - semi opaque background
- applies to `:tooltip`, v-tooltip too?

**To Reproduce**
- users and auth --> users --> retention settings --> hover over i icon

**Result**
![image](https://github.com/user-attachments/assets/01698ff1-2fbe-4c5c-ba4f-1de2b7ff7258)

**Expected Result**
![image](https://github.com/user-attachments/assets/ab756d9b-1837-448d-a91e-5d72e07f7ff1)

**Comment by richard-cox** [comment]
For a better example of the new transparency see https://github.com/rancher/dashboard/issues/11742

**Comment by rak-phillip** [comment]
Confirmed that this is related to our migration to `floating-vue` for Vue3. The underlying templates that we might have targeted via css have most likely changed.

**Comment by izaac** [comment]
Similar non-functional fix already checked while reviewing https://github.com/rancher/dashboard/issues/11684
