### ISSUE TITLE
Vue3: Fix problematic disabled boolean attributes

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11746]
# Description

As identified by @momesgin, in Vue3 the disabled attributed is handled differently.

Quoting our notes:

> Stylings may not apply properly to some disabled, selected or focused elements(e.g. div)
 In Vue 2, setting false to the value of an attribute would remove the attribute from being rendered. When doing this in Vue 3, false is considered a valid value, so the attribute will be rendered, to fix this you can pass null to the attribute's value instead 
 E.g. 
 > ```
 > <div :disabled="!opt.enabled">...</div>
 > ```
>  should be converted to 
 > ```
 > <div :disabled="opt.enabled ? null : true">...</div>
 > ```
>  More info: https://v3-migration.vuejs.org/breaking-changes/attribute-coercion.html

## Affected components

The following components have been identified to have potentially problematic usages of `:disabled`. This isn't a comprehensive list, but is a good starting point for identifying which patterns we might need to look out for in order to completely resolve this issue.

- [ ] pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue
- [ ] shell/components/ActionMenu.vue
- [ ] shell/pages/c/_cluster/istio/index.vue
- [ ] shell/pages/c/_cluster/monitoring/index.vue

**Comment by momesgin** [comment]
I've updated the description:

- removed `shell/components/form/KeyValue.vue` item since all the disabled cases in that file are on the tags that are supporting boolean attributes
- removed `shell/components/nav/NamespaceFilter.vue` item since it's been covered in [another PR](https://github.com/rancher/dashboard/pull/11732)

**Comment by cnotv** [comment]
I was trying to use this flag in TS for this issue, but for some reasons it does not work 🤔 
https://github.com/vuejs/language-tools/blob/master/packages/language-core/schemas/vue-tsconfig.schema.json#L43

**Comment by momesgin** [comment]
> I was trying to use this flag in TS for this issue, but for some reasons it does not work 🤔 https://github.com/vuejs/language-tools/blob/master/packages/language-core/schemas/vue-tsconfig.schema.json#L43

it would be ideal if we could add this somewhere in the ts config or eslint rules, but I think the chances are low to make this mistake without noticing it during the development.

**Comment by cnotv** [comment]
I was just thinking of a way to validate the solution in an automated way.
