### ISSUE TITLE
Vue3: Tooltip does not wrap text correctly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11742]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- tooltip text consumes max width of window
- previously it wrapped
- styling could have lost a max % width?

**To Reproduce**
- users and authentication --> role templates --> create --> hover over the `i` of `Grant Resources` `Resource` select

**Result**
![image](https://github.com/user-attachments/assets/2c5c9ce4-2d6f-43ec-b3b8-75a563ff4cf1)

**Expected Result**
![image](https://github.com/user-attachments/assets/3c3cb742-97f2-4baf-8fc2-7c23dc65d293)

**Comment by izaac** [comment]
Similar non-functional fix already checked while reviewing https://github.com/rancher/dashboard/issues/11684
