### ISSUE TITLE
[Epic] Vue3: Select Principal Issues

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11743]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- The component SelectPrinciple selects local auth provider users or external auth provider users and groups
- The component has a number of new bugs in vue3
- Some of these could be related, some not. Strong candidate to investigate and split up if required

Generic Issues
- [x] #11755
    - there's no space between the bottom of the component and the start of the screen content
- [x] #11756

Context Specific
- [x] #11753
- [x] #11752
- [x] #11754

**Additional context**

**Comment by rak-phillip** [comment]
I converted this into an epic and split it into multiple issues. I think that each problem described here is unique enough that they can be worked on independently. Of course, if someone would like to tackle multiple issues in one go, that is still entirely appropriate.

**Comment by izaac** [comment]
Moving epic after downstream issues reviews.
