### ISSUE TITLE
Vue3: FileSelector contents are not populating the associated labeledInput when creating Google Cloud Credentials

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#11748]
**Describe the bug**
When creating gcp cloud creds users need to supply a json blob - if using the 'read from file' button, the file is read correctly (saving works) but the  labeledinput where the uploaded file should be shown appears empty.

**To Reproduce**
1. Navigate to cluster management>cloud credentials>create>google
2. Upload a file, give the credential a name, and save

**Result**
The Service Account input appears empty, but the credential saves successfully (service acct data was correctly defined).

**Expected Result**
When the user uploads data via file, the Service Account input should show that data

**Screenshots**

https://github.com/user-attachments/assets/46b32053-db15-49a5-aa59-7c90712fbf19

**Comment by eva-vashkevich** [comment]
Hi @mantis-toboggan-md are you still able to reproduce it on master? I can't reproduce it.

https://github.com/user-attachments/assets/9f2f4529-cc62-4ed9-a780-aee4065d2dee

**Comment by mantis-toboggan-md** [comment]
I can't reproduce this anyone either @eva-vashkevich - closing the issue
