### ISSUE TITLE
Vue3: Unhandled exception when adding a member to a downstream cluster

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11752]
## Steps to reproduce

1. Navigate to Cluster Explorer --> Cluster --> Cluster and Project Members --> Cluster Membership tab, Click on Add
2. Click on select member and enter character

## Actual behavior

Dashboard throws an unhandled exception and an error overlay is rendered.

## Expected behavior

No errors in this process. 

## Screenshots

![image](https://github.com/user-attachments/assets/db6c7e50-feaf-40ea-87ee-f6bc35d451fa)

**Comment by izaac** [comment]
Selector is used on some areas already covered by E2E https://github.com/rancher/dashboard/pull/11869
