### ISSUE TITLE
Vue3: Checkboxes are not enabled when selecting a user for Global Roles

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11753]
## Steps to reproduce

1. Navigate to Users & Authentication --> Groups --> Assign Global Roles 
2. Click on select member and click on suggested entry 

## Actual behavior

The checkboxes are not enabled.

## Expected behavior 
checkbox should be enabled after selecting a user/group

## Screenshots

![image](https://github.com/user-attachments/assets/68fddf31-0dd3-475a-9e8a-c4330779015e)

**Comment by izaac** [comment]
Selector is used on some areas already covered by E2E https://github.com/rancher/dashboard/pull/11869
