### ISSUE TITLE
[Monitoring / Alerting V2 UI] Feature Overview Page: CRD Summary

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1175]
### CRD Summary

The primary purpose of this section is to show the relationships between CRs / resources currently on the cluster based on the descriptions provided above. In terms of the UI, this section will correspond to the colored / numbered UI elements (I'll refer to these as `Buttons`) shown above the table at the bottom of the mockup (note: the table itself can be omitted). 

There are three types of `Buttons` we should see in this section (corresponding to Prometheus, AlertManager, and Grafana) which should each contain the information described below:

#### Prometheus `Button`

There should be one `Button` per `Prometheus` CR within the cluster across any namespace (we only expect one to exist though on a default deployment).

Each `Button` should contain the following information:

Field | Type | How To Get Value | On Click
---|---|---|---|
Scrape Targets | `int` | `TBD` | Go to `{{ .spec.externalUrl }}/targets` |
Monitors | `int` | `TBD` | Go to `{{ .spec.externalUrl }}/targets` |
Rules | `int` | `TBD` | Go to `{{ .spec.externalUrl }}/rules` |

#### AlertManager `Button`

There should be one `Button` per `AlertManager` CR within the cluster across any namespace (we only expect one to exist though on a default deployment).

Each `Button` should contain the following information:

Field | Type | How To Get Value | On Click
---|---|---|---|
Notifiers | `int` | Check the len of the `receiver` list on the `alertmanager.yaml` key of the Secret specified in `{{ .spec.configSecret }}` in the `cattle-monitoring-system` namespace | `TBD` |
Active Alerts | `int` | `TBD` | Go to `{{ .spec.externalUrl }}` |

#### Grafana UI `Button`

There should be one `Button` per `Grafana` **pod** on the cluster across any namespace (we only expect one to exist though on a default deployment). This can be discovered by checking the number of times that `grafana/grafana:<any-tag>` or `rancher/grafana-grafana:<any-tag>` shows up in the output of `kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}"`.

Clicking anywhere on the button should take us to `<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy`. 

Each `Button` should contain the following information:

Field | Type | How To Get Value
---|---|---|
Dashboards | `int` | Number of Grafana Dashboard ConfigMaps in the `grafana-dashboards` namespace |
Datasources | `int` | Number of Grafana Dashboard ConfigMaps in the `grafana-datasources` namespace |

**Comment by catherineluse** [comment]
This relationships summary could go a long way toward making the monitoring app more understandable to newcomers, with a decreased reliance on documentation.
