### ISSUE TITLE
Vue3: Select Principal missing bottom spacing

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11755]
## Steps to reproduce

1. Naviage to Users & Authentication => Groups
2. Click on Assign Global Roles

## Actual Behavior

Spacing associated with the Select Principle component is not present

![image](https://github.com/user-attachments/assets/3e415191-80fb-46e7-a2c5-c7352231352d)

## Expected behavior

Spacing for the Select Principle component is the same as it was in v2.9

![image](https://github.com/user-attachments/assets/c08f2a91-4817-4ac9-941c-9acbc31dff43)

**Comment by izaac** [comment]
Selector is used on some areas already covered by E2E https://github.com/rancher/dashboard/pull/11869
