### ISSUE TITLE
Vue3: Auth Provider Users are not added to Authorized Users & Groups

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11754]
### Prerequisites 

Configure an Auth Provider

1. Navigate to Users & Authentication --> Auth Provider 
2. In the "Configure who should be able to login and use Rancher" field, select either option: 
   3. Allow members of clusters and projects, plus authorized users & groups 
   4. Restrict access to only the authorized users & groups
5. Use the Add Member component to provide a user/group that SHOULD be added

## Actual behavior

When users are selected for Authorized Users & Groups, they are not added to the list

![image](https://github.com/user-attachments/assets/b8051211-2c1d-4ff1-a4f7-7897a83c4a19)

## Expected behavior

Users are added to the list when they are selected

![image](https://github.com/user-attachments/assets/8ad086bd-6fa7-4d7d-90ab-21d93867ed29)

**Comment by izaac** [comment]
Selector is used on some areas already covered by E2E https://github.com/rancher/dashboard/pull/11869
