### ISSUE TITLE
Vue3: Select Principal initial selection is visible when searching for a new user/group

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11756]
After selecting a user/group and then clicking on the component to search for a different one the initial selection is visible

## Screenshots

![image](https://github.com/user-attachments/assets/a6e4c08f-a80b-4922-a658-367035412af8)

**Comment by izaac** [comment]
Selector is used on some areas already covered by E2E https://github.com/rancher/dashboard/pull/11869
