### ISSUE TITLE
Vue3: Finish the migration from `v-tooltip` library to `floating-vue`

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#11763]
There's this [migration documentation](https://floating-vue.starpad.dev/migration/migration-from-v2) from the `floating-vue` library that lists the changes that we need to apply in order to complete the migration.

- [ ] All the class names from `v-tooltip` used in our css to customize the tooltips styling should be updated to the class names from `floating-vue` e.g. in https://github.com/rancher/dashboard/blob/master/shell/assets/styles/global/_tooltip.scss
There's [this PR](https://github.com/rancher/dashboard/pull/11771) that addresses some of the cases

- [ ] Update `:popper-options="{modifiers: { flip: { enabled: false } } }"` to `:flip="false"`

- [ ] Replace `classes` with `popperClass`

- [ ] Update `trigger` to `:triggers`

- [ ] Update `open-group` to `show-group`

- [ ] Address the two issues that are mentioned in the comments of [this PR](https://github.com/rancher/dashboard/pull/11771), 1. Tooltip's box-shadow 2. Todo comment

- [ ] Fix LocaleSelector dropdown
**result:**
![Image](https://github.com/user-attachments/assets/1053ede3-6eed-4d3c-bc46-04d1ab2f4480)
**expected:**
![Image](https://github.com/user-attachments/assets/8b28be41-8b64-463d-a811-93e15db5826e)

- [ ] Fix Tooltip's content including `pre` tags
**result:**
![Image](https://github.com/user-attachments/assets/532bf9a2-e9eb-4568-8320-11519c6f0fb5)
**expected:**
![Image](https://github.com/user-attachments/assets/abd36e19-5886-41fe-9dd6-0aef51e59dfa)

- [ ] Fix ContainerLogs dropdown
**result:**
![Image](https://github.com/user-attachments/assets/401dca90-970e-406c-981d-bfd7ed089978)
**expected:**
![Image](https://github.com/user-attachments/assets/f005d9a6-f647-4020-b065-ad97cd82ee35)

**Comment by izaac** [comment]
This is part of the non functional updates dor the vue2 to vue3 upgrade, and is already covered on other referenced epic/issues
