### ISSUE TITLE
Vue3: SAML SLO support - feature is broken

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#11766]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions: n/a
- Browser type & version: all

**Describe the bug**

SAML SLO support feature in Rancher Dashboard is broken in several places. Needs fixing. 

**To Reproduce**

Setup a SAML auth provider that supports SLO and check that the feature is broken in master due to Vue3 migration

**Result**
Feature not working

**Expected Result**

Feature should work

**Screenshots**

**Additional context**

Based on the work done in https://github.com/rancher/dashboard/pull/11182

**Comment by yonasberhe23** [comment]
Testing will be tracked in https://github.com/rancher/dashboard/issues/11766
