### ISSUE TITLE
Vue3: Virtualisation Management page is blank

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11769]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Blank page is shown instead of harvester cluster list
- Code lives in harvester-manager built-in extension

**To Reproduce**
- spin up `head`
- Nav to `Virtualisation Management`

**Result**
- blank page
- warnings and error in console

**Expected Result**
- empty list 

**Screenshots**
![image](https://github.com/user-attachments/assets/a7c92225-5f99-4940-8393-02f1ee1f8efa)

**Additional context**

**Comment by rak-phillip** [comment]
The error `[Vue warn]: Invalid VNode type: undefined (undefined)` leads me to believe that this error is a result of a Vue2/Vue3 version mismatch. Seeing as how `harvesterhci.io.management.cluster`[^1] is defined in the `harvester/dashboard` repo, I think that we will have to migrate Harvester to Vue3 before we will be able to get this functioning.

[^1]: https://github.com/harvester/dashboard/blob/d1254dcdeddac99b7b5fbd07b77586a63fa2400a/shell/list/harvesterhci.io.management.cluster.vue#L4

**Comment by richard-cox** [comment]
Worth noting that the harvester extension is only used in the cluster context, and is loaded when a user navigates to one. This page works with the built-in harvester-manager extension.

Separate issue, the linked file should be in their extension rather than the forked dashboard code.

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

Navigation to the Virtualization Manager is no longer broken. No errors were thrown on console either.
