### ISSUE TITLE
Vue3: Login Page: 'Component made a reactive object' AsyncComponentWrapper  console warning

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11772]
**Setup**
- Rancher version:  dev of 2.10.0

**Describe the bug**
- on login page error inocuous warning in console

**To Reproduce**
- nav go log in page + refresh

**Result**
```
login.vue:407 [Vue warn]: Vue received a Component which was made a reactive object. This can lead to unnecessary performance overhead, and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`. 
Component that was made reactive:  {name: 'AsyncComponentWrapper', __asyncLoader: ƒ, setup: ƒ} 
  at <Login onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {_fetchDelay: 200, $fetch: ƒ, loadInitialSettings: ƒ, displayName: ƒ, toggleLocal: ƒ, …} > > 
  at <RouterView key="/auth/login" > 
  at <Unauthenticated onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {_fetchDelay: 200, $fetch: ƒ, setCustomColor: ƒ, removeCustomColor: ƒ, setBodyClass: ƒ, …} > > 
  at <RouterView key=1 > 
  at <App>
```

**Expected Result**
- no warning

**Additional context**
- low priority
- i have custom branding (colour + login page image) and SSO (okta) set up. both possibly not needed

**Comment by cnotv** [comment]
Same error is displayed when trying to install a chart:

<img width="1915" alt="Screenshot 2024-09-18 at 21 56 05" src="https://github.com/user-attachments/assets/cae4a1f9-f71d-4c96-8ce1-ad78c6872cda">

**Comment by izaac** [comment]
Non-functional fix, moving moving to done.
