### ISSUE TITLE
Vue3: AzureAD authentication 'enable' button stays disabled when required values are filled

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#11784]
**Describe the bug**

Form validation is not working correctly in the AzureAD auth form. The 'create' button is disabled despite all fields being populated and no errors being shown. It looks like the form requires the 'endpoint' inputs to be filled, despite being hidden unless the user switches to 'custom'

**Screenshots**
![Screenshot 2024-08-30 at 7 26 35 AM](https://github.com/user-attachments/assets/a81faa12-dcd0-4d33-a774-a38c0187d2cb)
![Screenshot 2024-08-30 at 7 28 21 AM](https://github.com/user-attachments/assets/a8adb8b7-1c63-496b-9c04-43a4421cc458)
![Screenshot 2024-08-30 at 7 28 27 AM](https://github.com/user-attachments/assets/9478b78e-a375-489e-b6ef-5f8b5a09adac)

**Additional context**
Associated AzureAD unit tests should be re-enabled when this is fixed.

**Comment by yonasberhe23** [comment]
Unit tests are sufficient. moving to done.
