### ISSUE TITLE
Vue3: Spurious warnings on load of dashboard (global formatters + formatters)

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11786]
Rancher Dashboard produces several warnings related to installing global formatters on first login:  

```
Skipping AppSummaryGraph install. Component already exists. [global-formatters.js:12](webpack://dashboard/shell/plugins/global-formatters.js)
Skipping BadgeStateFormatter install. Component already exists. [global-formatters.js:12](webpack://dashboard/shell/plugins/global-formatters.js)
Skipping Capitalize install. Component already exists. [global-formatters.js:12](webpack://dashboard/shell/plugins/global-formatters.js)
Skipping Checked install. Component already exists. [global-formatters.js:12](webpack://dashboard/shell/plugins/global-formatters.js)
Skipping CloudCredPublicData install. Component already exists. [global-formatters.js:12](webpack://dashboard/shell/plugins/global-formatters.js)
Skipping ClusterLink install. Component already exists. [global-formatters.js:12](webpack://dashboard/shell/plugins/global-formatters.js)
```

## Steps to reproduce

- Refresh on any page
- Review logs in browser console

## Additional info

- Skipping X install. Component already exists.
- see shell/plugins/global-formatters.js and shell/plugins/formatters.js
- example const components = require.context('@shell/components/formatter', false, /[A-Z]\w+\.(vue)$/);
- Low Impact - code handles duplicates, warning is only in debug

**Comment by cnotv** [comment]
Link to the source of the console message https://github.com/rancher/dashboard/blob/master/shell/plugins/global-formatters.js#L12

**Comment by cnotv** [comment]
Should not be documented somewhere the purpose of this code?

Also are we not importing plugins twice?
<img width="335" alt="Screenshot 2024-10-08 at 19 21 25" src="https://github.com/user-attachments/assets/a8bc348d-d1b6-42c1-a5b6-53415631c7a5">

**Comment by rak-phillip** [comment]
This looks like a breaking change in webpack 5 where `require.context` will return duplicate entries, I'm finding two entries for each component. For example:

```
./AppSummaryGraph.vue
```

and then later on, we attempt to register the same component again via

```
components/formatter/AppSummaryGraph.vue
```

**Comment by cnotv** [comment]
Would it make sense to suppress the warning we are intentionally adding till we solve the issue?

**Comment by yonasberhe23** [comment]
doesn't seem automatable. moving to To Test

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

This isn't longer reproducible. These messages aren't in Console navigating through some pages reloading and disabling the browser cache.
