### ISSUE TITLE
Vue3: UI shows empty page when import Harvester clusters

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#11795]
**Setup**
- Rancher version: 2.10 master

**Describe the bug**

If you have Harvester imported clusters, the UI won't load either logged in or nor.

**To Reproduce**

- Go to Virtualization Management -> Harvester clusters -> click on 'Import existing' to add a new instance - no need to register the cluster.
- Go to Dashboard home -> https://localhost:8005/?safemode

**Result**
Empty page + console error

**Expected**
The UI should work in safemode.

**Screenshots**

![image](https://github.com/user-attachments/assets/39a65f60-fc04-4716-862e-791e1f333b6f)

**Additional context**

**Comment by rak-phillip** [comment]
This looks related to #11769
