### ISSUE TITLE
[Epic] Vue3: CIS Benchmark issues

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11799]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Install CIS Benchmark cluster tool helm chart
  - Cluster --> Tools --> install CIS Benchmark --> refresh
- [x] #11910
- [ ] #11911
- [x] #11912
- [x] #11913
- [ ] #11915

**Comment by mantis-toboggan-md** [comment]
Adding on to this: I'm seeing a console error on the scan list view
![Screenshot 2024-09-11 at 2 00 52 PM](https://github.com/user-attachments/assets/1409cc38-b295-4149-bc93-ecadaf6dd08f)

**Comment by rak-phillip** [comment]
I split this issue out into multiple and marked this one as an epic to track each of them. I also added a new issue for the errors provided by @mantis-toboggan-md

**Comment by izaac** [comment]
I am closing this issue and the children, I've added QA backlog task to explore the chart install automation effort as I didn't find a CIS covered in the current code
https://github.com/rancher/qa-tasks/issues/1547

**Comment by aalves08** [comment]
I believe this was wrongfully closed, as the issues still subside and I am actively working on fixing them. Going to reopen
