### ISSUE TITLE
Helm deployer pod should support custom registry for airgap

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1180]
In order to support airgap for (dev-)charts, we need to have the helm deployer pod pass in the default-system-registry setting if that is set.

How to handle partner charts ? At this point I think we won't support airgap for partner charts.

**Comment by jiaqiluo** [comment]
the bug fix is validated on rancher:`master-01c13f69cb277e037f6d58323cb0859300e8af5d-head` docker install, airgap enviroemnt. 

when installing the monitoring app from the dashboard, the private registry is passed in the payload of the POST request 

<img width="1080" alt="Screen Shot 2020-09-16 at 9 23 25 AM" src="https://user-images.githubusercontent.com/6218999/93365221-61a24600-f7fe-11ea-908f-62f38c1efe67.png">
