### ISSUE TITLE
Burger Menu: Cluster List: Placement of pin cluster is incorrect, causes scroll bar

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11809]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- hovering over a cluster in the burger menu should show an icon on right of row to pin the cluster to the top of the list
- when there are too many clusters a vertical scroll bar is shown
- in vue3 world hovering over a cluster shows the pin icon underneath the vertical scroll bar and prompts a horizontal scroll bar to be shown

**To Reproduce**
- add 4 or so clusters (can be imported/custom)
- reduce height of window such that a scroll bar appears
- hover over the `local` text

**Result**
![image](https://github.com/user-attachments/assets/30bb9a26-5789-40b4-ba67-795d97372f3b)

**Expected Result**
- No horizontal scroll bar
- Pin visible
- This is how it previously looked (not great, but better than current)
  - ![image](https://github.com/user-attachments/assets/5e9f549b-4bfa-4cb8-844c-cb7d9d098592)

**Screenshots**

**Additional context**
- the vertical scroll bar is quite common in my setup
  - legacy enabled, multiple global apps / extensions. chuck in dev tools at bottom and it's always shown

**Comment by cyberpunk2040** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by richard-cox** [comment]
Linking
- https://github.com/rancher/dashboard/issues/11809
- https://github.com/rancher/dashboard/issues/11810

**Comment by momesgin** [comment]
Seems we have the scrollbar issue in vue2 as well
![Image](https://github.com/user-attachments/assets/3d502297-04af-4c13-8224-2360f55e9e57)

**Comment by richard-cox** [comment]
Interesting, i couldn't with release-2.9. Looking at the screenshots the horizontal scroll bar is important

**Comment by gaktive** [comment]
I'll hold on filing a backport for now until we know what the solution is and if it's a quick one. 2.10.x seems reasonable but 2.9.x with its Vue2 may be a stretch.

**Comment by izaac** [comment]
Rancher version: `v2.11-7839201dc49c3cbd138b0bb99028c5705825d699-head`
UI version: `release-2.10 d5b785b`

I wasn't able to reproduce. I've changed the size, and smaller than a phone screen and the horizontal bar didn't appear in the menu.

In the screenshot below this is the most I could resize the browser horizontally, the scrollbar there is expected as there was 10 clusters in the setup.

![Image](https://github.com/user-attachments/assets/074fe0c6-cb09-4282-9b76-1ed7a8b2c6d9)
