### ISSUE TITLE
Vue3: Windows Manager: Shell Bugs

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11812]
**Setup**
- Rancher version: dev 2.10.0

**Describe the bug**
- Shell flavours
  - Kubectl Shell (explorer header)
  - Pod (container) Shell
  - Pod (container) Logs
  - Node / Machine Shell

- Bug 1 - kubectl shell, pod shell
  - Focus on component now shows a blue border
- Bug 2 - Pod Shell
  - controls at bottom of screen only show container selector (drop down..) consuming all width
  - should also show clear button and connected status
- Bug 3 - Errors throw in console when shell opens
 
**To Reproduce**
- Bug 1
  - cluster explorer --> header `Kubectl Shell`
  - by default it'll have focus and blue border
- Bug 2
  - Pods list --> pod row's action button --> `Execute Shell`
- Bug 3
  - Provision RKE2 cluster
  - Cluster Management --> click on rke2 cluster --> Machines Pools tab --> three dot action menu for a machine --> SSH Shell

**Result**
Bug 1 & 3
![image](https://github.com/user-attachments/assets/d72e798d-c650-42fb-a83f-8aa3cb4614ee)

Bug 3
![image](https://github.com/user-attachments/assets/ba6f2a2e-24c5-446e-a919-814374de7290)

**Expected Result**
Bug 1 & 2
![image](https://github.com/user-attachments/assets/852ae776-7bae-480a-96fe-64267d816bac)

Bug 3
No errors in console

**Additional context**
Probably something broken horizontal scroll wise, but guessing container selector based

**Comment by izaac** [comment]
This is related to work already reviewed of https://github.com/rancher/dashboard/issues/11970
