### ISSUE TITLE
Vue3: Container Logs Menu Popover broken

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11814]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
Container shell menu options broken

**To Reproduce**
Pods list --> pods action menu --> `View Logs`

**Result**
![image](https://github.com/user-attachments/assets/004bd7cc-71dc-4bb8-ac30-8524783571cc)

**Expected Result**
![image](https://github.com/user-attachments/assets/6f926ee1-5504-4703-af49-7902f67c5953)

**Comment by izaac** [comment]
This is a related fix done for other issues related to this popover. Moving to done.
