### ISSUE TITLE
Update list of AKS regions that support availability zones

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#11818]
The list of available AKS regions is not hardcoded, but whether or not they support availability zones (enforced in the UI through form validation) is hardcoded here: https://github.com/rancher/dashboard/blob/master/pkg/aks/util/aks.ts#L7. We need to update this list to include `southcentralus` and any other regions missing from https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support#azure-regions-with-availability-zone-support

**Comment by nwmac** [comment]
Closing in favor of https://github.com/rancher/dashboard/issues/11817 and https://github.com/rancher/dashboard/issues/11816
