### ISSUE TITLE
Vue3: Cluster Explorer Header: Import Yaml: namespace dropdown visually broken

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11811]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Import YAML namespace dropdown renders incorrectly

**To Reproduce**
- Cluster Explorer --> `Import YAML` in header 

**Result**
![image](https://github.com/user-attachments/assets/19251d57-2f9a-4338-9812-8813de0673fb)

**Expected Result**
![image](https://github.com/user-attachments/assets/01e318d1-61ff-4028-85a9-594a7d22e187)

**Comment by izaac** [comment]
Visual enhancement and non-functional. Closing
