### ISSUE TITLE
Vue3: Nodes List: Missing Internal IP

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11819]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Nodes list column `External/Internal IP` fails to show (at least) the Internal IP

**To Reproduce**
- bring up `head` in docker
- navigate to cluster explorer --> cluster --> nodes

**Result**
![image](https://github.com/user-attachments/assets/e91bbaa1-8e87-4eac-b6bc-967fccc2a134)

**Expected Result**
![image](https://github.com/user-attachments/assets/1afe32cc-a65f-4b88-b25f-395fd41c4bff)

**Comment by mantis-toboggan-md** [comment]
Fixed by https://github.com/rancher/dashboard/pull/11916
