### ISSUE TITLE
[2.10] Update Azure Availability Zone Region List

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#11817]
Forward port of: https://github.com/rancher/dashboard/issues/11816

The list of available AKS regions is not hardcoded, but whether or not they support availability zones (enforced in the UI through form validation) is hardcoded here: https://github.com/rancher/dashboard/blob/master/pkg/aks/util/aks.ts#L7. We need to update this list to include southcentralus and any other regions missing from https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support#azure-regions-with-availability-zone-support

Ensure we check and add all missing regions.

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head`
UI version: `master 8662b03`

The availability zones listed in the PR are available through the UI as expected.
The availability zones removed/amended listed in the PR are no longer selectable in the UI.
