### ISSUE TITLE
Vue3: Cluster Membership Create Page Cancel goes back to native resource instead of custom members page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11821]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- The Cluster --> Cluster and Project Members --> Cluster Membership tab's list is a custom representation of cluster role template bindings. This is not the the generic list of cluster role template bindings
- After going to the `Add` page if a user presses `Cancel` they're taken to the generic list instead of where they previously were in the custom list
- Note - i couldn't test where the user goes after creating the membership due to the principal drop down broken (there's an open issue)

**To Reproduce**
- Cluster --> Cluster and Project Members --> Cluster Membership tab --> `Add` --> in new screen `Cancel`

**Result**
![image](https://github.com/user-attachments/assets/72565bdd-7410-4da9-8e0d-a8a7997d8288)

**Expected Result**
![image](https://github.com/user-attachments/assets/15a5e1e7-96b4-407e-8403-0688c6d1511c)

**Additional context**

**Comment by izaac** [comment]
E2E  test updates look really good. Moving to done.
