### ISSUE TITLE
Vue3: Service: Create External name cannot be created

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#11839]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions: N/A
- Browser type & version: N/A

**Describe the bug**

DNS Name field input binding is broken

**To Reproduce**

Service -> Create ExternalName
Enter "Name"
Enter "DNS name"

**Result**
"DNS Name" input field is reset
"Create" button is disabled

**Expected Result**

"DNS Name" value should be maintained
"Create"button should be enabled

**Screenshots**

https://github.com/user-attachments/assets/c77432ec-08ee-4e3e-86be-f2984dcd1f07

**Additional context**

**Comment by yonasberhe23** [comment]
Did a quick manual check in 2.10. issue resolved. moving to done.

Rancher - v2.10-afe9248a3837e249ceb92ce57fd94bc107dcb51a-head
Dashboard - master ab7308e

https://github.com/user-attachments/assets/e8ef19ce-1e28-44de-a33d-bf4ce2d09428

follow up ticket to add automated tests: https://github.com/rancher/qa-tasks/issues/1581
