### ISSUE TITLE
Charts carousel icons in dark mode are stretched

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11845]
**Setup**
- Rancher version: v2.8(?)

**Describe the bug**
- the carousel shows icons for entries
- the icons are placed in a container which a white background
- the container is stretched to the bottom of the card area
- this leads to visually unappealing icons

**To Reproduce**
- change UI to dark mode
- cluster explorer --> Apps --> Charts

**Result**
![image](https://github.com/user-attachments/assets/9dda7b97-aa24-4ffc-87df-474092a6d63a)

**Expected Result**
![image](https://github.com/user-attachments/assets/e0734a81-dbb8-493d-bb1d-74009711bb96)

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

This is no longer reproducible on this Rancher/UI version. Icons look as expected.
