### ISSUE TITLE
GKE: Validation required for Min/Max NodeCount

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11844]
**Setup**
Rancher - v2.9-ac80dbd08dd92b65627b36e8658c87ea661c1baf-head
Dashboard - release-2.9 https://github.com/rancher/dashboard/commit/e7910502ec96bab1d8e67cc20af872a755a8a01c

**Describe the bug**
On GKE portal, 0 Min NodeCount & 1000 Max NodeCount is allowed. 
On Rancher UI, the MinCount needs to be allowed and MaxCount needs to be validated.

**Screenshots**

GKE:
MinCount: 
![image](https://github.com/user-attachments/assets/210fe6f6-7957-4f2b-a16c-8cb02bf0e482)

MaxCount:
![image](https://github.com/user-attachments/assets/85ecad0c-0b6f-4caa-8492-fd68b530c3e2)

Rancher:

MinCount: 
![image](https://github.com/user-attachments/assets/586baec4-03fc-49a1-93b9-9258c65b0c42)

MaxCount:
![image](https://github.com/user-attachments/assets/6e78c01e-79e2-4791-b796-90b0219d09bb)

**Comment by izaac** [comment]
Looks good as per the backport review
