### ISSUE TITLE
AKS: Allow 0 NodeCount for User mode pools

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11842]
**Setup**
Rancher - v2.9-ac80dbd08dd92b65627b36e8658c87ea661c1baf-head
Dashboard - release-2.9 e791050

**Describe the bug**
On AKS portal, zero NodeCount is allowed for User mode pools in scale methods: Manual & Autoscale. The same to be allowed on Rancher UI.

**Screenshots**
_AKS:_

![image](https://github.com/user-attachments/assets/63976516-5dad-4b0f-9946-b02af3f01c77)
--------------------
![image](https://github.com/user-attachments/assets/c83b8667-e3d6-49eb-84ae-43bcdcdf9bc8)

_Rancher:_

![image](https://github.com/user-attachments/assets/2d6ce7b0-a950-4cd6-bdfe-ef644dadfbfd)
--------------------------------
![image](https://github.com/user-attachments/assets/50511682-dea8-4c9c-bc4a-a0ea8aa3fdcb)

**Comment by richard-cox** [comment]
Same issue as https://github.com/rancher/dashboard/issues/11826, but different provider. @mantis-toboggan-md Worth checking GKE?

**Comment by cpinjani** [comment]
GKE issue: https://github.com/rancher/dashboard/issues/11844

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

Checks were down following the backport validations. 

The System node pool doesn't allow 0 which is expected as at least one must be created for cluster creation/management.
And as expected the value 0 is allowed for user mode pools.
