### ISSUE TITLE
Respect creator's principal ID when creating projects & clusters

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#11852]
Currently when a project or a cluster is created by a user who is logged in using an external authentication provider Rancher shows that user's principal ID as the owner in the UI only to be replaced later by it's local user's counterpart.

We want to make it possible to respect the principal ID that was used to create a project/cluster.

In order to do so we may introduce an additional annotation e.g. field.cattle.io/creator-principal-name that can cary the creator's principal ID to complement the existing field.cattle.io/creatorId that is set when the corresponding project/cluster object is created. There is no need to use this annotation if the user is logged in using the local provider.

Respecting the creator's principal ID can help with the issues like this https://github.com/rancher/rancher/issues/40304

----

The backend has a solution in https://github.com/rancher/rancher/issues/46828
In order for this to work in the UI, the UI needs to add this new annotation when creating a project or a cluster.

```sh
curl https://<rancher-url>/v3/cluster?_replace=true \
...
--data-raw '{
    "type": "cluster",
    "name": "test-cluster",
    "annotations": {
        "field.cattle.io/creator-principal-name": "keycloak_user://testuser1@example.com"
    },
    ...
}'
```

```sh
curl https://<rancher-url>/v3/projects \
...
--data-raw '{
    "type":"project",
    "name":"test-project",
    "annotations": {
        "field.cattle.io/creator-principal-name": "keycloak_user://testuser1@example.com"
    },
    ...
}'
```

It makes sense to add this annotation ONLY if the user is logged in using an external auth provider.

_Originally posted by @pmatseykanets in https://github.com/rancher/rancher/issues/46828#issuecomment-2312892450_

Internal reference: SURE-6693

**Comment by gaktive** [comment]
Automation should be simple enough to at least detect the annotation.

**Comment by rancher-max** [comment]
Spoke with the QA working on the backend ticket, and confirmed it is being automated from an e2e perspective there.

**Comment by yonasberhe23** [comment]
moving to To Test to do further testing around project/namespaces with different auth providers

**Comment by yonasberhe23** [comment]
Tested in: 

- Rancher v2.10-695357ad2fdb58bfce027ecf6ce96e8a4e3ddbab-head
- Dashboard master d5024a1

Auth type | Test Case | Result
| --- | --- | --- |
Local auth | verify that no principal id annotation is set when creating projects | ✅
Local auth | verify that no principal id annotation is set when creating aks cluster | ✅
Local auth | verify that no principal id annotation is set when creating eks cluster | ✅
Local auth | verify that no principal id annotation is set when creating gke cluster | ✅
| | | 
Third-party auth | verify that the field.cattle.io/creator-principal-name is set when creating projects | ✅
Third-party auth | verify that the field.cattle.io/creator-principal-name is set when creating aks cluster | ✅
Third-party auth | verify that the field.cattle.io/creator-principal-name is set when creating eks cluster | ✅
Third-party auth | verify that the field.cattle.io/creator-principal-name is set when creating gke cluster | ✅

![image](https://github.com/user-attachments/assets/a28d71fa-5f64-46ab-99a0-c4d6c3eb2376)
