### ISSUE TITLE
Vue3: ConfigMap: Data keyvalue component shows incorrect field type for value

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11853]
**Setup**
- Rancher version: dev of 2.10-0

**Describe the bug**
- `Value` input field shows code mirror instead of standard input field

**To Reproduce**
- ConfigMap list --> Create --> Data tab

**Result**
![image](https://github.com/user-attachments/assets/56e2ce5e-0506-4134-b604-3531dcf98630)

**Expected Result**
![image](https://github.com/user-attachments/assets/8c47e197-8f58-49d3-ac58-010eeb2a3a1a)

**Comment by cnotv** [comment]
To be more accurate, it should look like an input but still be a code editor. In the previous version is the same, also a multiline. There's just styling regressions.

![Screenshot 2024-09-17 at 17 05 23](https://github.com/user-attachments/assets/01f2df42-e378-4b34-a0a6-77f08b33c658)

**Comment by cnotv** [comment]
Current style

![Screenshot 2024-09-17 at 17 13 02](https://github.com/user-attachments/assets/5e972446-d1a4-4010-9ac9-73df35efe65c)

**Comment by cnotv** [comment]
Same for YAML editor

![Screenshot 2024-09-17 at 21 29 55](https://github.com/user-attachments/assets/df4ed423-71e0-4f99-b021-8e643ed2ea27)

**Comment by cnotv** [comment]
To be solved with https://github.com/rancher/dashboard/issues/11701

**Comment by richard-cox** [comment]
@cnotv can we keep this one open to validate, or add this use case as an acceptance criteria to the other issue?

**Comment by cnotv** [comment]
> @cnotv can we keep this one open to validate, or add this use case as an acceptance criteria to the other issue?

It's an acceptance criteria and has been tested as well.
