### ISSUE TITLE
Last Login field does not sort properly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11866]
See https://github.com/rancher/dashboard/issues/10821 (specifically https://github.com/rancher/dashboard/issues/10821#issuecomment-2334490484 and comments below for ways to reproduce)

**Comment by nwmac** [comment]
@richard-cox Is this different from https://github.com/rancher/dashboard/issues/12013?

**Comment by rak-phillip** [comment]
Closing this as a duplicate of #12013. Please reopen if needed.
