### ISSUE TITLE
[2.9] [GKE] Hosted Provider create form retain old values

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#11864]
**Setup**
- Rancher version: v2.9-e65fefcaee6ca27ea4b78e355c745f34c27e5576-head
- Rancher UI Extensions: release-2.9 9d6d98b
- Browser type & version: Firefox

**Describe the bug**

Hosted Providers create form seems to retain values from previous creation.
**To Reproduce**

Taking GKE as an example
1. Create a GKE cluster with Private Endpoint: true, Master Authorized Network: true.
2. Once it is created, go back to create another GKE cluster, this time check the networking fields, the private endpoint, and the master authorized network.

**Result**
Both still retain their old values.
**Expected Result**

Form should be reset.

**Screenshots**

[Screencast from 09-09-2024 04:56:39 PM.webm](https://github.com/user-attachments/assets/5814f82a-de9a-4cdc-9571-6d7c8e8d442d)

**Additional context**

**Comment by valaparthvi** [comment]
@richard-cox Why is the milestone set to 2.10.0? I believe it is a misleading bug and should be in this release.

**Comment by richard-cox** [comment]
@valaparthvi all bugs are fixed in the latest release and then backported as needed. the `backport-candidate` label means it'll enter into that review process

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head`
UI version: `master df953cd`

The form is reset between Cluster create actions. The specific advanced network options mentioned in this issue are all false when starting a new GKE create.
