### ISSUE TITLE
AKS: Unexpected warning in NodeCount field

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11875]
**Setup**
Rancher - v2.9-65df012014c22ba29006fca8c97aa6b8c2ba1105-head
Dashboard - release-2.9 9d6d98b

**Describe the bug**
There is unexpected warning being displayed while entering NodeCount value for AKS Nodepool.

**Screenshots**

![image](https://github.com/user-attachments/assets/fc0d90d3-61cc-42aa-82d2-89c51a9bf3b3)

**Comment by mantis-toboggan-md** [comment]
Fixed in https://github.com/rancher/dashboard/pull/11907

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head`
UI: `master 8662b03`

This isn't reproducible and both system and agent node counts are properly validated as per the linked PR requirements. `>= 1` for system and `>= 0` for agent pools. 

The error isn't visible anymore. just an error indicator and a proper error is shown while hovering.
