### ISSUE TITLE
Vue3: Fleet's Create Page doesn't show the footer

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#11882]
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

**To Reproduce**

**Result**
<img width="1113" alt="fleet-vue3" src="https://github.com/user-attachments/assets/8c3e0f24-cb73-4b49-aeab-d41f0499d06f">

**Expected Result**

<img width="1149" alt="fleet-vue2" src="https://github.com/user-attachments/assets/72f7b510-4a54-48c9-b166-baf7bac4a4dd">

**Screenshots**

**Additional context**

**Comment by rak-phillip** [comment]
@cnotv I ended up solving this one during triage.. I guess that I got a little too interested during the repro 😅
