### ISSUE TITLE
Vue3 Workload create page is showing form validation errors prematurely

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#11889]
**Describe the bug**
The initial workload creation screen, where users select which type of workload they want to create, appears to be running form validation and showing the user errors about inputs which are not yet visible. When the errors are clicked, instead of going away, more appear.

**To Reproduce**
1. Navigate to the cluster explorer (local or downstream doesn't matter)
2. Select 'workloads' from the navigation, and hit 'create'

**Result**
1. The workload type selection screen shows form validation errors, which cannot be cleared

**Expected Result**
1. No form validation until the actual form loads.

**Screenshots**

https://github.com/user-attachments/assets/ba4c1ab0-611e-4663-8f03-001b3c5c5b0e

**Comment by eva-vashkevich** [comment]
Same issue in Service page

**Comment by izaac** [comment]
E2E coverage looks good. PO follow guidelines. Closing
