### ISSUE TITLE
Vue3: Fleet's dashboard table has too much padding

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#11883]
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

**To Reproduce**

**Result**
<img width="1118" alt="Screenshot 2024-09-10 at 5 50 53 PM" src="https://github.com/user-attachments/assets/dc5ade1f-07f1-4b62-8a3d-31f0e0971618">

**Expected Result**

<img width="1147" alt="Screenshot 2024-09-10 at 5 56 05 PM" src="https://github.com/user-attachments/assets/68af4c2d-9fe2-4c5a-ad0d-a4aac8adc8f7">

**Screenshots**

**Additional context**

**Comment by yonasberhe23** [comment]
Did a quick manual check in 2.10. issue resolved. moving to done.

Rancher - v2.10-afe9248a3837e249ceb92ce57fd94bc107dcb51a-head
Dashboard - master ab7308e
![Image](https://github.com/user-attachments/assets/9f855421-75de-466d-a12f-c521f8322346)
