### ISSUE TITLE
Vue3: Additional install/upgrade chart steps fail to load

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11898]
**Setup**
- Rancher version: dev if 2.10

**Describe the bug**
- Charts that have built-in install experiences can contain conditional additional steps
- these are defined as vue components in `shell/chart/<chart name/steps`
- this is a process brought in with https://github.com/rancher/dashboard/pull/3101, however the actual steps have been removed (v1 monitoring no longer supported)
- whilst testing https://github.com/rancher/dashboard/issues/11773 found out the underlying process is broken 

> Note 1: **broken feature isn't currently being used**
> Note 2: I tagged this with vue3, but haven't confirmed working in vue2

**To Reproduce**
- Add the following to a new file at `shell/chart/monitoring/steps/my-step.vue`
  - ```
    <script>
    export default {
      label:      'generic.add',
      subtext:    'generic.back',
      weight:     100,
      components: {},
      data() {
        return {};
      },
      mounted() {
        this.$emit('update', {
          loading: false,
          ready:   true,
          hidden:  false,
        });
      },
    };
    </script>
    <template>
      <div>
        Hello World
      </div>
    </template>
    ```
- Run the dashboard
- Nav to Apps --> Charts --> Monitoring --> Install
 
**Result**

```
fetch.client.js:75 Error in fetch(): TypeError: customStep.component is not a function
    at Proxy.loadChartStep (install.vue:934:1)
    at install.vue:929:1
    at Array.map (<anonymous>)
    at Proxy.loadChartSteps (install.vue:929:1)
    at async Proxy.fetch (install.vue:269:1)
    at async Proxy.$_fetch (fetch.client.js:72:1)
```


**Expected Result**
- Additional step show in install chart wizard

**Additional context**
- see `shell/store/catalog.js `chartSteps`, `shell/pages/c/_cluster/apps/charts/install.vue` `loadChartSteps`

**Comment by richard-cox** [comment]
We should also consider removing the feature

**Comment by yonasberhe23** [comment]
Follow-up QA task to add automation for this https://github.com/rancher/qa-tasks/issues/1583. Moving to To Test

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

It is no longer possible by UI means to add custom chart config.
