### ISSUE TITLE
[Logging v2] rancher-logging still use the original install chart UI and only deploys the logging operator

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1190]
Rancher version: `master-head (09/08/2020)` _76c26fb0f_

Old chart options form is still displayed but filling values and clicking install only installs the logging operator without outputs/flows.

![Screen Shot 2020-09-08 at 10 23 50 AM](https://user-images.githubusercontent.com/27659/92508702-e9b09c00-f1bd-11ea-9fe7-b87579446593.png)

**Comment by deniseschannon** [comment]
New deployment page is being worked on and will be available later

**Comment by deniseschannon** [comment]
This deployment page has been replaced. Please re-test with new workflow.

**Comment by izaac** [comment]
Rancher version `master-head (09/10/2020)` _198ec5bdf52d3ed2b4865cfcf6ac1d61150bf55f_

I see the new 

![Screen Shot 2020-09-10 at 9 17 44 AM](https://user-images.githubusercontent.com/27659/92761561-aa618700-f346-11ea-8201-b4d85bf06951.png)

Chart deployment issue: #1109
Feature Overview issue (after install): #1089

CRDs UI configuration issues:

#1102
#1103
#1126
#1127
