### ISSUE TITLE
Cluster Tools button missing inside cluster navigation

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11901]
# Description

The `Cluster Tools` button in the sidebar is missing when navigating within the local cluster.

Left 2.10, right 2.9.

![Screenshot 2024-09-12 at 17 16 48](https://github.com/user-attachments/assets/e860646e-71a5-4b08-8f44-86c4a167b820)

**Comment by richard-cox** [comment]
`Cluster Tools` has moved into the `Cluster` side nav group as `Tools`. Not quite sure when, i thought it was 2.9.0 though

**Comment by cnotv** [comment]
> `Cluster Tools` has moved into the `Cluster` side nav group as `Tools`. Not quite sure when, i thought it was 2.9.0 though

Looks like I was still using 2.8 and I've also forgot we have a script to update with Docker 🙃 
Thanks for the hint.
