### ISSUE TITLE
CIS Benchmark: Refresh on scan detail pages gives full page (dev) error

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11911]
## Steps to reproduce

- Install CIS Benchmark cluster tool helm chart
- Cluster --> Tools --> install CIS Benchmark --> refresh
- Navigate to resource menu CIS Benchmark --> Scans --> click on a scan (page renders fine)
- Refresh the page

## Actual behavior

![image](https://github.com/user-attachments/assets/ef5543a1-df71-42af-9567-3812c4bdbb2d)

## Expected behavior

Errors are not printed to the console

**Comment by izaac** [comment]
From Epic:

> I've added QA backlog task to explore the chart install automation effort as I didn't find a CIS covered in the current code
https://github.com/rancher/qa-tasks/issues/1547

**Comment by richard-cox** [comment]
There's no linked comment or PR confirming this has been fixed. @rak-phillip , @rak-phillip  can you update?

**Comment by aalves08** [comment]
I think all of the CIS issues, along with the epic https://github.com/rancher/dashboard/issues/11799 got wrongfully closed @richard-cox

**Comment by yonasberhe23** [comment]
QA backlog task to explore the CIS chart install automation
https://github.com/rancher/qa-tasks/issues/1547

Moving to To Test

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head`
UI: `master 8662b03`
Cluster RKE with k8s `1.29`

This is no longer reproducible using Chrome, no errors on console and scans list view and individual scan results views are rendered as expected.
