### ISSUE TITLE
CIS Benchmark: No content shown in profile create/edit page

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11913]
## Steps to reproduce

- Install CIS Benchmark cluster tool helm chart
- Cluster --> Tools --> install CIS Benchmark --> refresh
- Navigate to resource menu CIS Benchmark --> Profiles --> create

## Actual behavior

No content renders on page. No errors or warnings in log.

## Expected behavior

Content is rendered in page

**Comment by aalves08** [comment]
Closing as per track history of the issue
