### ISSUE TITLE
CIS Benchmark: No content shown in profile detail page

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11912]
## Steps to reproduce

- Install CIS Benchmark cluster tool helm chart
- Cluster --> Tools --> install CIS Benchmark --> refresh
- Navigate to resource menu CIS Benchmark --> Profiles --> click on a scan

## Actual behavior

No content renders on page. No errors or warnings in log.

## Expected behavior

Content is rendered in page

**Comment by izaac** [comment]
From Epic:

> I've added QA backlog task to explore the chart install automation effort as I didn't find a CIS covered in the current code
https://github.com/rancher/qa-tasks/issues/1547

**Comment by richard-cox** [comment]
Same here, there's no linked comment or PR confirming this has been fixed. @rak-phillip , @rak-phillip  can you update?

**Comment by rak-phillip** [comment]
@richard-cox yes, this is resolved by #11916. Each of the issues were tagged with the `Fixes` keyword and they look to be appropriately linked to the PR.

![image](https://github.com/user-attachments/assets/3d008504-4559-4798-9402-0663ff08693d)

**Comment by aalves08** [comment]
Closing again following comments 🙏
