### ISSUE TITLE
Height of inputs in ArrayList component is too large

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11927]
**Setup**
- Rancher version: Pre 2.7.0?

**Describe the bug**
- The height of the input element in the ArrayList component is too high

**To Reproduce**
Used in a far number of places, for examples see linked PR screenshots

**Result**
See PR screenshots

**Expected Result**
- Height should be a standard input, not one sized for if we had labels within input
- See PR screenshots

**Screenshots**
- See PR screenshots

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

The Array fields height is meeting the expected criteria described in the PR linked to this issue.
