### ISSUE TITLE
[Logging V2] Additional Cluster Outputs

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1192]
Add the following outputs to the logging cluster output CRD Page.

# Outputs

For any reference to secret type see: https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/secret/

## S3
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/s3/
| Name | Key | Type | Default |
|--|--|--|--|
| Key Id | aws_key_id | secret_pair | - |
| Secret Id | aws_sec_id | secret_pair | - |
| Endpoint | s3_endpoint | string | - |
| Bucket | s3_bucket | string | - |
| Path | path | string | - |
| Overwrite Existing Path | overwrite | bool | false |

## Azure Storage
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/azurestore/
| Name | Key | Type | Default |
|--|--|--|--|
| Storage Account | azure_storage_account | secret_pair | - |
| Access Key | azure_storage_access_key | secret_pair | - |
| Container | azure_container | string | - |
| Path | path | string | - |
| Store As | store_as | string<gzip\|json\|text\|lzo\|lzma2> | gzip |
## GCS
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/gcs/
| Name | Key | Type | Default |
|--|--|--|--|
| Project | project | string | - |
| Credentials Json | credentials_json | secret_pair | - |
| Bucket | bucket | string | - |
| Path | path | string | - |
| Overwrite Existing Path | overwrite | bool | false |
## LogZ
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/logz/
| Name | Key | Type | Default |
|--|--|--|--|
| Endpoint | endpoint | string | - |
| Enable Compression | gzip | bool | true |
## Loki
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/loki/
| Name | Key | Type | Default |
|--|--|--|--|
| Url | url | string | - |
| Username | username | secret_pair | - |
| Password | password | secret_pair | - |
| Tenant | tenant | string | - |
## SumoLogic
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/sumologic/
| Name | Key | Type | Default |
|--|--|--|--|
| Endpoint | endpoint | string | - |
## Datadog
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/datadog/
| Name | Key | Type | Default |
|--|--|--|--|
| API Key | api_key | secret_pair | - |
| Use SSL | use_ssl | bool | - |
| Use Compression | use_compression | bool | - |
| Host | host | string | - |
## File
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/file/
| Name | Key | Type | Default |
|--|--|--|--|
| Path | path | string | - |
## Cloudwatch
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/cloudwatch/
| Name | Key | Type | Default |
|--|--|--|--|
| Key Id | aws_key_id | secret_pair | - |
| Secret Id | aws_sec_id | secret_pair | - |
| Endpoint | endpoint | string | - |
## Kinesis Stream
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/kinesis_firehose/
| Name | Key | Type | Default |
|--|--|--|--|
| Key Id | aws_key_id | secret_pair | - |
| Secret Id | aws_sec_id | secret_pair | - |
## Log DNA
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/logdna/
| Name | Key | Type | Default |
|--|--|--|--|
| API Key | api_key | string | - |
| Hostname | hostname | string | - |
| App | app | string | - |
## New Relic
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/newrelic/
| Name | Key | Type | Default |
|--|--|--|--|
| API Key| api_key | secret_pair | - |
| License Key | license_key | secret_pair | - |
| Base URI | base_uri | string | - |
## AWS Elasticsearch
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/aws_elasticsearch/
| Name | Key | Type | Default |
|--|--|--|--|
| Url| endpoint.url | string | - |
| Key Id | endpoint.aws_key_id | secret_pair | - |
| Secret Id | endpoint.aws_sec_id | secret_pair | - |

**Comment by izaac** [comment]
Reopening for syslog addition.

**Comment by izaac** [comment]
Rancher version `v2.5-head (12/14/2020)` _ e3f5264_
Rancher version `master-head (12/14/2020)` _ e971e0735_

### Scope
Validated that the generated spec of each value was correct and correctly saved from the UI. This done for **ClusterOutputs**.

- Amazon Elasticsearch
- Azure Storage
- Cloudwatch
- Datadog
- File
- Fluentd
- GCS
- Kinesis Stream
- LogDNA
- LogZ
- Loki
- New Relic
- S3
- SumoLogic

---

Also I've done some UX checks and opened a couple of small issues separately for tracking.
