### ISSUE TITLE
Namespace/Project Filter Search becomes unclickable after one option is selected

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11928]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
User is unable to enter any text in the search field of the namespace/project filter after an single entry

**To Reproduce**
- Cluster Explorer --> click on the ns/project filter drop down (note clicking on the search input field and entering text works) --> Select `Project:Default` --> click on the search input field --> type in `a`

**Result**
- `a` is not shown in field

**Expected Result**
- `a` shown in field, results filtered by it

**Comment by rak-phillip** [comment]
This was most likely introduced as a part of #11762. We might need to revert this change and rework the solution for getting mouse and keyboard events properly working for this component.

**Comment by yonasberhe23** [comment]
e2e test is sufficient. moving to done
