### ISSUE TITLE
Vue 3: Circular imports in `shell/edit/auth/ldap/config.vue` throw unhandled exception

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11934]
## Steps to reproduce

- Navigate to Users & Authentication => Auth Provider
- Click on OpenLDAP

## Actual behavior

An error is printed to the browser console

```
ReferenceError: can't access lexical declaration '__WEBPACK_DEFAULT_EXPORT__' before initialization
    default index.js:232803
    js saml.vue:51
    Webpack 85
[entry-helpers.js:40](webpack://dashboard/shell/initialize/entry-helpers.js)
    errorHandler entry-helpers.js:40
    callWithErrorHandling runtime-core.esm-bundler.js:173
    handleError runtime-core.esm-bundler.js:218
    onError runtime-core.esm-bundler.js:2357
    setup runtime-core.esm-bundler.js:2402
    (Async: promise callback)
    setup runtime-core.esm-bundler.js:2401
    callWithErrorHandling runtime-core.esm-bundler.js:173
    setupStatefulComponent runtime-core.esm-bundler.js:7265
    setupComponent runtime-core.esm-bundler.js:7220
    mountComponent runtime-core.esm-bundler.js:5542
    processComponent runtime-core.esm-bundler.js:5517
    patch runtime-core.esm-bundler.js:5119
    mountChildren runtime-core.esm-bundler.js:5303
    mountElement runtime-core.esm-bundler.js:5213
    processElement runtime-core.esm-bundler.js:5196
    patch runtime-core.esm-bundler.js:5116
    componentUpdateFn runtime-core.esm-bundler.js:5729
    run reactivity.esm-bundler.js:190
    update runtime-core.esm-bundler.js:5763
    callWithErrorHandling runtime-core.esm-bundler.js:173
    flushJobs runtime-core.esm-bundler.js:406
```

## Expected behavior

The LDAP form should render without fail

## Notes

This is narrowed down to circular references present in component imports. We need to understand why this is an error now in Webpack 5/Vue 3 and didn't cause issues earlier. 

We import `saml.vue` in `config.vue`:

https://github.com/rancher/dashboard/blob/14089aba62240aa4f7af9eb27511e343e2f352e0/shell/edit/auth/ldap/config.vue#L8

And in `saml.vue`, we import `config.vue`:

https://github.com/rancher/dashboard/blob/14089aba62240aa4f7af9eb27511e343e2f352e0/shell/edit/auth/saml.vue#L12

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

No longer reproducible on this Rancher/UI version
