### ISSUE TITLE
Logging: Unable to add include or exclude rules when creating an Flow

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11933]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- users are unable to add additional include / exclude rules when creating a Logging Flow
- no errors in console

**To Reproduce**
- Cluster Explorer --> Apps --> Charts --> Logging --> Install
- Cluster Explorer --> Logging --> Flows --> Create --> Matches tab --> press either of `Add Include Rule` or `Add Exclude Rule`

**Result**
- No include / exclude pod card added to list

**Expected Result**
- include / exclude pod card added to list

**Screenshots**
![image](https://github.com/user-attachments/assets/4af3bfe8-9713-40c0-b416-f27c1a0419b2)

![image](https://github.com/user-attachments/assets/152f5832-82f8-4b5c-a10d-25ab5f5c46d9)

**Additional context**

**Comment by yonasberhe23** [comment]
Needs manual validation. Follow-up automation task create https://github.com/rancher/qa-tasks/issues/1593

**Comment by yonasberhe23** [comment]
No longer seeing the issue. Include / Exclude pod card added to the list. 

Tested in: 
- Rancher v2.10-24040b6dc9ae2fa6a3a49cbe126132c13c2587ba-head
- Dashboard master 78d12f9
