### ISSUE TITLE
Exception thrown when leaving Chart detail page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11931]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- When leaving the detail page for a Chart an exception is thrown
- Looks like some of the chart details are removed which trigger a chart look up using undefined input which throws an exception
- Feels like this shouldn't be triggered given the change of page

**To Reproduce**
- Navigate to Cluster Explorer --> Apps --> Charts --> click on any chart --> Charts

**Result**
![image](https://github.com/user-attachments/assets/5737fbc5-011a-42da-8554-2f8b437d0bd6)

**Expected Result**
The deliverable for this is in two parts
- understand why this happens, what changed with vue3 and does it impact anything else?
- given above ensure no exception is thrown

**Comment by rak-phillip** [comment]
The error is spawned from the chart mixin when navigating back to charts.

https://github.com/rancher/dashboard/blob/4de6f6d085e3e0ef8abd11c1ae2a978ffa23d07d/shell/mixins/chart.js#L358-L363

**Comment by cnotv** [comment]
The same error has been identified while installing a chart due to routing logic I imagine.

<img width="1478" alt="Screenshot 2024-09-18 at 21 58 05" src="https://github.com/user-attachments/assets/72f63f2f-fc05-4f0d-8831-7c6e6aeb7ec1">

**Comment by yonasberhe23** [comment]
Not seeing the exception when navigating through install steps, upgrade steps, or backing out to '/apps/charts' from details page.
Tested in: 
Rancher v2.10-0cddb5f146709bf471b863e6715b0a7538572e74-head
Dashboard master d0c3c5a
