### ISSUE TITLE
Cannot create Clusters in 2.9.1 using non-builtin Node drivers

### ISSUE THREAD

**Issue by nnoethling** [rancher/dashboard#11936]
**Setup**
- Rancher version: 2.9.1
- Rancher UI Extensions: None / Nothing added
- Browser type & version: Chrome Version 127.0.6533.122

**Describe the bug**

In the current stable Rancher version 2.9.1 Cluster creation is not working using non-builtin drivers.
UI is shown the following Error when trying to create the cluster: `OutscaleConfig.rke-machine-config.cattle.io "nc-outscale-test-pool1-wshzr" is invalid: extraTagsAll: Invalid value: "string": extraTagsAll in body must be of type array: "string"`

**To Reproduce**

1. Deploy Rancher 2.9.1
2. Enable Non-builtin Node driver (e.g. Outscale in my example)
3. Go to Clusters and create new Cluster
4. Make sure RKE2/K3s is enabled
5. Select outscale as node driver
6. Enter a cluster name
7. Enter dummy values for `extraTagsAll` or `securityGroupIds`
8. Click Create

**Result**
Cluster create is blocked by UI error: `OutscaleConfig.rke-machine-config.cattle.io "nc-outscale-test-pool1-wshzr" is invalid: extraTagsAll: Invalid value: "string": extraTagsAll in body must be of type array: "string"`

The actual Network Request response:
```
{
    "type": "error",
    "links": {},
    "code": "Invalid",
    "message": "OutscaleConfig.rke-machine-config.cattle.io \"nc-outscale-test-pool1-pt54k\" is invalid: extraTagsAll: Invalid value: \"string\": extraTagsAll in body must be of type array: \"string\"",
    "status": 422,
    "type": "error"
}
```

**Expected Result**

Creation of Cluster is possible using the UI.

**Screenshots**

extraTagsAll field in Cluster create in Rancher 2.9.1 seems to be a field for a string:
<img width="135" alt="image" src="https://github.com/user-attachments/assets/bda3582c-07a5-4daa-a53d-74fd3e472c72">

extraTagsAll field in Cluster create in Rancher 2.8.5 is for multiple values with Add button:
<img width="139" alt="image" src="https://github.com/user-attachments/assets/2b415a99-32b4-4d14-87e4-95da4ce08ba9">

**Additional context**

Seems like in Rancher 2.9.1 UI array fields from custom UI are not processed correctly, or atleast other than in previous versions of Rancher.
If you have a look at the custom UI code of the Driver (e.g. for outscale: https://oos.eu-west-2.outscale.com/rancher-ui-driver-outscale/v0.2.0/component.js) all fields that are arrays are affected and will not be displayed as array in Rancher UI.
This only seems to affect non-builtin Drivers. I tested with 3 different ones (Outscale, Nutanix and Cloudscale)

**Comment by brandond** [comment]
It sounds like there have been changes made to the struct on the rancher side that are out of sync with the non-builtin driver. For example the field on the rancher `MachineConfig` object is now an array, but the `OutscaleConfig` object expects a string... or vice versa. Perhaps these drivers need to be updated to support rancher 2.9?

**Comment by richard-cox** [comment]
We should investigate if this will affect partners with node drivers as well. For whoever picks this up, raise it in the team slack channel for details

**Comment by richard-cox** [comment]
In 2.9.0 the issue in https://github.com/rancher/dashboard/issues/11936#issuecomment-2361435906 was resolved by https://github.com/rancher/rancher/issues/45157.

However in 2.9.1 it's still an issue, investigating now

**Comment by yonasberhe23** [comment]
No longer seeing error when creating a cluster using non-builtin drivers.

Tested in:

- Rancher v2.10-e615207c8cd924c092b55a9301e7378878706d19-head
- Dashboard master 6dd2962
