### ISSUE TITLE
[Logging V2] Remove Logging tab from Logging Page

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1193]
The logging tab in the sidebar should be replaced with an overview tab that displays the overview page.

**Comment by izaac** [comment]
Rancher version: `master-head (09/10/2020)` _198ec5bdf52d3ed2b4865cfcf6ac1d61150bf55f_

The tab is no longer in the Logging Overview 

![Screen Shot 2020-09-10 at 9 47 16 AM](https://user-images.githubusercontent.com/27659/92766025-b6e7de80-f34a-11ea-9dde-f5bb07283dcc.png)
