### ISSUE TITLE
Logging: Dev error shown when creating a logging cluster flow / output

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11932]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Full page (dev) error shown when going to the Filters tab when creating a Logging ClusterFlow
- Note - looks like the tab uses a yaml editor

**To Reproduce**
- Install Logging app
- Cluster Explorer --> Apps --> Charts --> Logging --> Install
- locations
  - Cluster Explorer --> Logging --> ClusterFlows --> Create --> Filters tab
  - Cluster Explorer --> Logging --> Output --> Create --> Output Buffer tab

**Result**
![image](https://github.com/user-attachments/assets/878c1871-ad78-443a-a2f9-2ccae301bc3a)

**Expected Result**
Page renders without error

**Comment by rak-phillip** [comment]
This error specifically references the codemirror component

```
can't access property "focus", this.$refs.codeMirrorRef.codemirror is undefined
```

Since we have recently updated the codemirror dependencies for vue3 compatibility, we'll need to ensure that the ref for setting focus is still valid

https://github.com/rancher/dashboard/blob/4de6f6d085e3e0ef8abd11c1ae2a978ffa23d07d/shell/components/CodeMirror.vue#L105-L109

**Comment by cnotv** [comment]
It seems like that issue is going to be solved with https://github.com/rancher/dashboard/pull/11902/files#diff-056160ac018ea8f019405781fd9f0c4e7e73c7007fcbeb3c41ea87286e35e03fR105

**Comment by mantis-toboggan-md** [comment]
This should be fixed by https://github.com/rancher/dashboard/pull/11973 (I have removed the change mentioned above in favor of changes in #11973 )

**Comment by izaac** [comment]
This is related to work already reviewed of https://github.com/rancher/dashboard/issues/11970
