### ISSUE TITLE
Error info when creating NavLink is not shown to user

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11937]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Errors when creating a NavLink are not shown to the user
- Note - this works fine for other resources (pods, services, secrets)

**To Reproduce**
- Cluster Explorer --> Header `Resource Search` --> type in NavLink --> click on NavLink --> Create
- Enter `AAA` for the name --> Enter anything for `Destination URL` --> Create

**Result**
- The Create button shows `Error`, however no other information shown on screen

**Expected Result**
In 2.9.0

![image](https://github.com/user-attachments/assets/09f603d7-af23-4ae9-b93a-a16c5cea3b30)

**Comment by yonasberhe23** [comment]
Error displays as expected. Tested in: 

- Rancher v2.10-8decbf6fd040b5b2168430f1e72ccc484d59b6e0-head
- Dashboard master 4e82a4d

![Image](https://github.com/user-attachments/assets/b1cb2d2d-7c59-48d0-b12f-59458abb7d1f)
