### ISSUE TITLE
Expose a new Setting in Rancher UI: k3s-based-upgrader-uninstall-concurrency

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#11942]
As part of the effort to deprecate the legacy `rancher-k3s-upgrade` system chart, a new setting `k3s-based-upgrader-uninstall-concurrency` is being introduced to manage the cadence of uninstalling that app in downstream imported RKE2/K3s clusters. It is necessary to expose this setting to users, allowing them to customize it according to their needs.

The new setting will be displayed in the Global Settings -> Settings page, with the following characteristics:
- **Name**: k3s-based-upgrader-uninstall-concurrency
- **Description**: Defines the maximum number of clusters in which Rancher can concurrently uninstall the legacy rancher-k3s-upgrader or rancher-rke2-upgrader app from imported K3s or RKE2 clusters.
- **Default**: 5 

Related backend issue: https://github.com/rancher/rancher/issues/42448

Please check the RFC for more information. 

SURE-9046

**Comment by richard-cox** [comment]
More info in JIRA, but blocked on creation of setting

**Comment by richard-cox** [comment]
Removed assignments, anyone can pick this up once setting available

**Comment by jiaqiluo** [comment]
The backend PR has been merged, and the changes are now available in the latest `docker.io/rancher/rancher:head` image. This should no longer be a blocker for the UI.

cc @richard-cox

**Comment by gaktive** [comment]
The theory is that the Steve API should report the min/max values. However, @kwwii may have some design questions, especially if the Global Settings page is the right home.

@richard-cox can you confirm that this belongs on Global Settings? and are there any other limitations for UI that need to factor in that weren't documented?

**Comment by gaktive** [comment]
Feature complete comes up very soon here so if this is needed for 2.10.0, we can step over a bit unless it's super clear to others closer to the ticket may indicate how quick it'll be.

**Comment by richard-cox** [comment]
This is a setting to assist a short term feature applicable to bulk updates to downstream clusters that have had their kube version bumped and was discussed in the RFC. I would vote we add this to general settings, but remove it after 2.12 (and update docs)

**Comment by gaktive** [comment]
@jiaqiluo will the backend validate the input? Is there a min/max value to consider?

**Comment by momesgin** [comment]
@jiaqiluo we can add some constraints on the UI side, but I believe the backend should always have the validation in place in case the request is not coming from the UI.

Also have a question, is the type integer or string?

**Comment by jiaqiluo** [comment]
@momesgin, the backend will attempt the convert the string into an integer, or use the default value if the conversation fails.  See [code](https://github.com/rancher/rancher/blob/main/pkg/settings/setting.go#L445-L460)
