### ISSUE TITLE
Workload: Container: Large sizing regression for Service Account Name

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11954]
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
- there's some horrible vertical growth to the select component, which is then matched by the button next to it

**To Reproduce**
Cluster Explorer --> Workloads --> Pods --> Create --> container tab --> General tab --> scroll down to `Service Account Name`

**Result**

Note - the command input fields (containing a label) compared to the service account and button
![image](https://github.com/user-attachments/assets/1cceebc0-f024-49c1-add0-376b714b4a93)

**Expected Result**
Note - this is 2.9.1, however not ideal. if straight forward we should reduce the height of the clear button
![image](https://github.com/user-attachments/assets/c53c9ae7-8536-4902-8608-0dce36270d8e)

**Comment by cnotv** [comment]
Possibly related to https://github.com/rancher/dashboard/issues/11952

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

This is looking good on standard browser viewport sizes, going to smaller viewports the field and button tend to grow in size. 

Those screen sizes however aren't viable for a good desktop experience thus this meets the expected criteria.
