### ISSUE TITLE
Workload: Pod: When viewing Pod Storage info projected content fails to show until clicked

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11957]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Storage tab code blob fails to render until user clicks (or similar re-render trigger)

**To Reproduce**
- Cluster explorer --> Workloads --> Pod --> Click on any pod --> Config --> Pod tab --> Storage Tab

**Result**
![image](https://github.com/user-attachments/assets/0b096771-63af-4822-ae82-ffa7eadf7f30)

**Expected Result**
(styling aside)
![image](https://github.com/user-attachments/assets/3ba835f8-59b9-427a-9862-f6780f96e3f6)

**Comment by rak-phillip** [comment]
We get this log in the console that looks to be related:

```
resize nullpx nullpx [codemirror-editor-vue3.js:405](webpack://dashboard/node_modules/codemirror-editor-vue3/dist/codemirror-editor-vue3.js)
```

Resizing the window will trigger the render of the component.

**Comment by mantis-toboggan-md** [comment]
>resize nullpx nullpx

For whoever picks this bug up, there is an open issue about this particular console output https://github.com/rennzhang/codemirror-editor-vue3/issues/54

**Comment by yonasberhe23** [comment]
e2e test coverage added in the attached pr is sufficient. moving to done
