### ISSUE TITLE
Chart not found error when trying to upgrade an app on dashboard

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1196]
**On** master-head - commit id: `4fbd822c`

- Navigate to Apps --> Installed Apps
- Click Upgrade  on any app say `backup-restore` or `cert-manager` or `eks-operator`
- Error in console:

```
install.vue:134 Error: Repo not found
    at catalog.js:295
    at d (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.O.forEach.t.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at y.getVersionInfo (catalog.js:287)
```
<img width="632" alt="Screen Shot 2020-09-08 at 2 22 32 PM" src="https://user-images.githubusercontent.com/26032343/92529717-e0382b80-f1df-11ea-8380-90357cdb41f1.png">

**Comment by deniseschannon** [comment]
Should we be showing the upgrade option if it wasn't deployed as a helm chart through Rancher? @vincent99 

The charts listed are ones that were deployed as a chart but not through repos/new chart packaging.

**Comment by vincent99** [comment]
The desired behavior is you should be able "upgrade" a release using any available chart (even if the combination makes no sense, like upgrade mysql to wordpress).  There's no direct link between the release and which chart was used to install it, and we don't really know which are suitable charts to upgrade to.  So we basically just guess and find one with a matching name.  If you don't like what we picked (or there's no match at all, like here) you should be able to choose from all the charts to use for the upgrade.

(But that part isn't implemented yet, as you can see.)

**Comment by vincent99** [comment]
It does what I said above now.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e9a98a323`**

- Deploy wordpress through helm charts (not from Rancher)
- Do an Upgrade on the app from Rancher

<img width="859" alt="Screen Shot 2020-09-23 at 4 38 53 PM" src="https://user-images.githubusercontent.com/26032343/94084941-9fcdd580-fdbb-11ea-9403-e59c68ed7af5.png">
