### ISSUE TITLE
Add explicit emits in the components

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11961]
# Description

As already defined [in the issue related to the migration documentation](https://github.com/rancher/dashboard/issues/10658), emitters are preferred in Vue3 as they may be inherited altogether with other attributes.

Add emitters identified by the [vue linter rule](https://eslint.vuejs.org/rules/require-explicit-emits.html#options). To do so
- [Enable globally in the default configuration](https://github.com/rancher/dashboard/blob/master/.eslintrc.default.js#L192) with: `'vue/require-explicit-emits': 'error',`
- Remove definition in [root configuration](https://github.com/rancher/dashboard/blob/master/.eslintrc.default.js#L192)

Afterwards add the emitter as indicated.

Occurrences:

<img width="844" alt="Screenshot 2024-09-18 at 18 31 24" src="https://github.com/user-attachments/assets/91615729-5dd7-4629-a58f-bcb3596905e5">

**Comment by yonasberhe23** [comment]
nothing for QA to do here. moving to done
