### ISSUE TITLE
[2.9] Add "v27.2.x" options for "Docker Install URL"

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/dashboard#11968]
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/rancher/rancher/issues/47174 we're adding support for Docker 27.2.x

**Describe the solution you'd like**
UI dropdowns that allow picking "Docker Install URL" (e.g. on Node Template details page - not sure where else it may be referenced) should have the following new items available:
* "v27.2.x" choice that populates `https://releases.rancher.com/install-docker/27.2.sh`

Note: Handling of default option (and addition of " (Recommended)" text) is handled via `engine-install-url` setting on backend that will be updated as part of https://github.com/rancher/rancher/issues/46326 and should be validated on that issue.

**Describe alternatives you've considered**
Note "Docker Install URL" is editable and doesn't limit users to only the choices available, so they can specify other URLs manually as well before this enhancement is done.

## Additional Information
See https://github.com/rancher/dashboard/issues/10996 on how it was handled last time for Docker 26.1

## Testing

To test, go to create a Digital Ocean cluster, click on 'Add Node Template', select a credential and click Next. Expand 'Engine Options' and verify that the new Docker Install URLs appear correctly, e.g.
![image](https://github.com/user-attachments/assets/d36edbfc-8148-4775-aaaf-421fe8204bdd)

**Comment by nwmac** [comment]
@gaktive Is this definitely in scope for 2.10.0?

**Comment by rancher-max** [comment]
Setting the milestone here for 2.9 as the backend changes have already happened for v2.9.3, and using https://github.com/rancher/dashboard/issues/11523 as the overall "docker changes" issue for v2.10.0.

**Comment by rancher-max** [comment]
### Validated using Rancher `v2.9-head`

The default is now v27.2.x and it is pointing to the correct URL:
<img width="982" alt="image" src="https://github.com/user-attachments/assets/ceb0f8bf-c6d7-47fd-9a46-f63dd8cbc999">
