### ISSUE TITLE
Node Drivers incorrectly supply addCloudCredential, resulting in missed Cloud Credential pages

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11974]
SURE-9062

**Setup**
- Rancher version: 2.9.0

**Describe the bug**
- Before https://github.com/rancher/dashboard/issues/7023 we would block the user from creating a cloud cred via list, but always request one when creating via the prompt before the create cluster flow
- Following that we now honour management.cattle.io.nodedrivers spec.addCloudCredential of `false`, so if set we won't allow the user to create one of that type at all
- addCloudCredential for all pre-supplied node drivers comes from https://github.com/rancher/rancher/blob/7bd6951a7d07f8b00b61811fd89cc673319f85b4/pkg/data/management/machinedriver_data.go#L140. A lot of these are set to false
- At least nutanix needs it to be true, possible a lot of others too
- We need to confirm who owns that file / those lines and request the correct values are set

**To Reproduce**
- Enable Nutanix driver
- Attempt to create an RKE2 nutanix cluster

**Result**
- no prompt to create / select cloud creds

**Expected Result**
- prompt to create / select cloud cred

**Comment by richard-cox** [comment]
JIRA issue to follow once split from https://jira.suse.com/browse/SURE-9051

**Comment by richard-cox** [comment]
This just needs a forward port of https://github.com/rancher/dashboard/pull/11984

**Comment by gaktive** [comment]
Internal reference update: SURE-9062

**Comment by yonasberhe23** [comment]
Tested in: 
Rancher	v2.10-695357ad2fdb58bfce027ecf6ce96e8a4e3ddbab-head
Dashboard master d5024a1

https://github.com/user-attachments/assets/4c31c132-3542-4c7b-b239-d15bc3e56a17
