### ISSUE TITLE
Missing `machineSelectorConfig` throws unhandled exception

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11987]
A missing `machineSelectorConfig` for an RKE2 cluster can cause the edit form to fail to render. 

## Steps to reproduce

- Navigate to Cluster Management and click on Create
- Select Custom
- Add a name to the cluster and click on "Edit as YAML"
- Update `machineSelectorConfig` to `machineSelectorConfig: []`
- Click Create
- Select the Overflow Menu for your newly created cluster and select "Edit Config"

## Expected behavior

The edit form will render. If a missing `machineSelectorConfig` is an unexpected state, provide a warning to the user with information on how to resolve. 

## Actual behavior

The loading indicator is shown indefinitely, while an error is thrown in the browser console

![image](https://github.com/user-attachments/assets/4353ba08-4205-41c7-809a-faa19ab550d7)

## Additional details

- Reported in Rancher 2.9.1
- The original report was for a recent install of Rancher v2.9.1; the cluster was created with terraform
- Rancher was installed with the agent TLS mode set to Strict
- The reproduction detailed above produces the same error as what was repported
- This behavior looks to have introduced in #10186

**Comment by rak-phillip** [comment]
@torchiaf can you provide more details on this error? I'm unsure if an empty `machineSelectorConfig` is a valid state, but it appears that there are ways to create RKE2 clusters that would put a cluster into this state.

**Comment by yonasberhe23** [comment]
@rak-phillip the edit form now loads properly when `machineSelectorConfig` is missing however, a few errors are thrown in the console. Are they expected? They don't seem to have any adverse effects but wanted to ask

> TypeError: this.spec.rkeConfig.machineSelectorConfig is undefined
> TypeError: this.cloudProviderOptions is undefined

![Image](https://github.com/user-attachments/assets/22100ffd-184a-4a5b-8be4-5ad23496be04)

**Comment by gaktive** [comment]
Since we have some time now, let's reopen this and assess the work involved to see when this needs to go in and then the backport. It doesn't sound like a blocker.

**Comment by yonasberhe23** [comment]
Edit form now loads properly when machineSelectorConfig is missing and no longer seeing console errors. Tested in:

- Rancher v2.10-f2de3bdd8d8e76892fd3534c1168973ad8710973-head
- Dashboard master a1152d7
