### ISSUE TITLE
Home Page Cluster List Scales Badly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11995]
**Setup**
- Rancher version: 2.9.1 (and before?)

**Describe the bug**
- The home page cluster list should have local pagination
- List has shown to scale badly when trying to show ~700 rows
  - 17 seconds churn to filter by text (could be improved by not re-rendering lots)
    - https://github.com/rancher/dashboard/issues/11994
  - 13 second list re-render blocking navigation to downstream cluster

**To Reproduce**
- Load ~700 clusters (they could be RKE2 Custom)
- nav to home page

**Result**
- all 700 clusters shown

**Expected Result**
- one page of X shown (given user pref

**Comment by richard-cox** [comment]
Note - https://github.com/rancher/dashboard/pull/11998 contains a 2.9.3 fix

**Comment by richard-cox** [comment]
Release Note (combined with https://github.com/rancher/dashboard/issues/11993)

The performance of the Clusters lists in the Home page and the Side Menu has greatly improved when there hundreds of clusters.

**Comment by izaac** [comment]
Rancher version: `2.10.0-alpha6`
UI version: `v2.10.0-alpha4`
Rancher repro version: `2.9.1`
k8s: `1.29`
Cluster count: `701` (includes local)
Browser: Firefox `1.32` (To utilize the performance tools). Cache disabled.


The performance on `2.10.0` is noticeable. On `2.9.1` the home page loaded in not less that ~45 seconds and not completing the Cluster list rendering.

On `2.10.0` the loading times where consistent at around 5 seconds and the Cluster list was rendered properly and paginated as expected.

`2.9.1`:

<img width="1846" alt="Screenshot 2024-11-04 at 11 32 04" src="https://github.com/user-attachments/assets/e439f693-822d-46a6-a2a9-479d4da61b4e">


`2.10.0`:

<img width="1842" alt="Screenshot 2024-11-04 at 11 57 01" src="https://github.com/user-attachments/assets/f20e7645-1541-40b0-b004-7c9e4ff4ab21">
