### ISSUE TITLE
e2e tests failing on 2.9 because of extension version that shouldn't be available to install

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#11996]
**Setup**
- Rancher version: 2.9
- Rancher UI Extensions: any
- Browser type & version:

**Describe the bug**

1. E2E tests on `release-2.9` are failing because the extension tests are trying to install the `clock` extension `0.3.0`, which is not compliant with `2.9`, despite the presence of the annotation https://github.com/rancher/ui-plugin-examples/blob/main/index.yaml#L10

2. Elemental QA automated tests are failing because Elemental `2.0.0` is not available to install anymore on Rancher `2.9`, which should be compliant and available

**To Reproduce**

**Result**
1. `clock` extension `0.3.0` is wrongfully available to install 
2. `elemental` extension `2.0.0` is not available to install

**Expected Result**

1. `clock` extension `0.3.0` should not be available to install
2. `elemental` extension `2.0.0` should available to install

**Screenshots**

**Additional context**

- Problem lies with `semver.satisfies` not considering suffixed version strings when doing a comparison, ex: 
```
semver.satifies('2.9-4535jda324sff324-head, '>= 2.9') will return false

semver.satifies('2.0.2-rc.1', '>= 2.0.0') will return false
```

**Note: Will need forward-porting to `master`**

**Comment by rancher-max** [comment]
Reviewed and this LGTM since we have existing automation around extensions and there were some additional validations done with the PR.
