### ISSUE TITLE
Project/Namespace menu action is not borderless

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#12007]
# Description

Something which initially seemed a `:deep()` issue (https://github.com/rancher/dashboard/issues/11952), seems to be related to some other changes due Vue3.

Seems like the class `role-multi-action` is not added in the markup of the same file/component and therefore requires not a non-scoped definition.

https://github.com/rancher/dashboard/blob/master/shell/components/SortableTable/index.vue#L1664C1-L1668

```scss
  // Remove colors from multi-action buttons in the table
  td {
    .actions.role-multi-action {
      background-color: transparent;
      border: none;
```

![Screenshot 2024-09-24 at 18 10 39](https://github.com/user-attachments/assets/ca742971-f61b-4569-bd7f-1d9cff425863)

**Comment by yonasberhe23** [comment]
unit tests are sufficient. moving to done
