### ISSUE TITLE
OPA- Standard user is unable to view constraint templates

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#1200]
What kind of request is this:
Bug

Steps:
Create cluster, navigate to dashboard
Apps -> Charts -> rancher-gatekeeper Install
Create a standard user and add user to cluster
Log into Rancher as standard user
Navigate to dashboard -> OPA Gatekeeper
Click on `Template`

Result:
Standard user is unable to view templates. Page is empty:
![Screen Shot 2020-09-08 at 4 05 03 PM](https://user-images.githubusercontent.com/57409052/92536027-7b83cd80-f1ed-11ea-8e67-b8e19d221efd.png)

Rancher server `rancher\rancher:master-head` `version 76c26fb`

**Comment by codyrancher** [comment]
@aaronRancher how did you add the user to the cluster? As a cluster owner I see 
![Screen Shot 2020-09-09 at 8 42 51 AM](https://user-images.githubusercontent.com/55104481/92621260-76b82b80-f278-11ea-8f86-917686b07296.png)

As a member I don't even see the option to view OPA.
![image](https://user-images.githubusercontent.com/55104481/92621593-d6163b80-f278-11ea-8fea-55937c84c8e4.png)

**Comment by aaronRancher** [comment]
@codyrancher I added a standard user as a Cluster Member.
![Screen Shot 2020-09-09 at 10 31 39 AM](https://user-images.githubusercontent.com/57409052/92634956-e97dd280-f289-11ea-978a-ee537998132f.png)
But when trying this scenario again, I cannot reproduce this behavior. 
Closing issue. Will reopen if behavior is seen again.
