### ISSUE TITLE
[UI] Age shows creation timestamp in backup and restore on Dashboard

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1201]
**On master-head - commit id: `76c26fb0`** 

- backup-restore image:
```
  repository: rancher/backup-restore-operator
  tag: v0.0.1-rc10
```
- Create a backup CR.
- Age column displays the creation timestamp of the backup CR
- Same column is available in `Restore` on the dashboard. 

**Expected:**
The column can be renamed to something like `Created At` or the contents of `Age` column can reflect time before which the CR was created like 2 mins or 10 mins.

**Comment by deniseschannon** [comment]
@mrajashree can you test on master?

**Comment by mrajashree** [comment]
On master-head 6a6f13cec

The age column still shows the creationTimestamp and not time elapsed. 

<img width="1187" alt="Screen Shot 2020-09-11 at 10 37 54 AM" src="https://user-images.githubusercontent.com/10672776/92955946-e9f9a300-f41a-11ea-86fb-ea216ec190bb.png">

kubectl output shows the time elapsed for the same resource
<img width="1093" alt="Screen Shot 2020-09-11 at 10 39 02 AM" src="https://user-images.githubusercontent.com/10672776/92956074-1ad9d800-f41b-11ea-9b43-0d84942b8c80.png">

**Comment by vincent99** [comment]
That particular column was mapped in the UI to explicitly use the original value instead of being automatically converted to the live date.. changed.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e9a98a32389`**

- Deploy backup restore app v2 in dashboard
- Deploy a backup CR
- Age shows when backup was created

<img width="1703" alt="Screen Shot 2020-09-23 at 1 34 36 PM" src="https://user-images.githubusercontent.com/26032343/94066639-99cafb00-fda1-11ea-9260-6faf86f1d0e0.png">
