### ISSUE TITLE
RKE2 Add-on config does not display

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12016]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- RKE2 Add-on config for things like CNI should display a yaml block, these are missing

**To Reproduce**
- Cluster Management --> Create --> Ensure RKE2 toggled on --> Custom --> Cluster Configuration tabs --> Basic tab --> set Container Network to `calico` --> Add-On Config tab 

**Result**
![image](https://github.com/user-attachments/assets/97e03671-1c26-457a-96ea-0cde7ade444f)

**Expected Result**
![image](https://github.com/user-attachments/assets/ac3eba0d-dc72-4d64-b4b4-737572cabba0)

**Additional context**
- This area may change soon, contact @richard-cox before starting
- The configuration's shown in the Add-On tab will change given the Container Network selection. Should confirm changing it does then mean different Configurations in Add-On tab

**Comment by cnotv** [comment]
It seems like an issue with the model, as the value is empty even if no component is mounted.
