### ISSUE TITLE
Sorting on last login in the Rancher UI not working properly

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#12013]
Sorting by last login will produce unexpected results in large groups of users.

SURE-9004

## Actual behavior
Users not sorted by last login

## Expected behavior
Users sorted by last login

**Comment by rak-phillip** [comment]
@gaktive FYI - I raised a PR to fix this in 2.10. I think that we should also patch for 2.9.

**Comment by rak-phillip** [comment]
Related to #11866

**Comment by yonasberhe23** [comment]
This needs manual validation. Follow-up task created for automation https://github.com/rancher/qa-tasks/issues/1592

**Comment by yonasberhe23** [comment]
Last login sorting working as expected.

Tested in:
Rancher v2.10-ae6ac83471545ab47d052d2d760daa2e6646a969-head
Dashboard master 225e3e6



https://github.com/user-attachments/assets/4150c5ac-2bc5-437c-9f52-878f6457d26b
