### ISSUE TITLE
Re-enable checks for extensions on tests-plugin-build.sh once we have versions of those extensions compliant with 2.10

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12026]
Re-enable checks for extensions on tests-plugin-build.sh once we have versions of those extensions compliant with 2.10

https://github.com/rancher/dashboard/blob/master/shell/scripts/test-plugins-build.sh#L226-L228

**Comment by cnotv** [comment]
What's the current state of the extension migration? @aalves08 @mantis-toboggan-md @jordojordo 

@aalves08 I think this has to be enabled for 2.10.0, no?

**Comment by aalves08** [comment]
@cnotv This depends on the migration of Kubewarden, CAPI 🐢  and Elemental and having working versions of them compliant with 2.10/Vue3 and for that the deadline is `2.10.1`, so it won't be re-enabled in `2.10.0` for sure since it won't fit the timeframe we have.

I have noticed that I had wrongfully added the milestone `2.11` to this, so I removed it

**Comment by aalves08** [comment]
This also has dependency with https://github.com/rancher/dashboard/issues/12147

**Comment by cnotv** [comment]
Yes, Typescript become more restrictive, as well as the VueCLI or Webpack.

**Comment by aalves08** [comment]
Will wait a bit more for CAPI to be migrated as well a re-enable the 3 extensions there at once (KW, Elemental and CAPI)
