### ISSUE TITLE
Storage dropdown is not selecting value when creating a new deployment

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#12020]
**Setup**
- Rancher version: 
v2.10-61d79963733364046c6fc8e9003bd9d6948a6db0-head
Dashboard | master 33b6680

**Describe the bug**
Found while testing https://github.com/rancher/dashboard/issues/11781

When creating a deployment, the dropdown displays the options as expected on both the pod and the container tab. However, for the container tab, as seen in the screen recording, the values the user selects from the dropdown are not actually being selected.

https://github.com/user-attachments/assets/b4c9c9ca-b433-426a-a1a1-e38576e59f21

And when trying to create the deployment, the following error occurs related to the volume (which might be related, otherwise, I'll file a new issue):
<img width="1704" alt="Screenshot 2024-09-19 at 16 50 07" src="https://github.com/user-attachments/assets/920c5786-15a9-4de1-9b63-0ce21b2ad2cb">

**To Reproduce**
Cluster Explorer --> Workloads --> Deployments --> Initial container tab --> Storage vertical tab

**Expected Result**
the values the user selects from the dropdown should be displayed in the UI and the deployment should be successfully created

**Comment by yonasberhe23** [comment]
e2e test coverage is sufficient. moving to done
