### ISSUE TITLE
[CIS v2] Navigation ticket

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1202]
Following is the left nav order of CIS CRDs:
- ClusterScans
- ClusterScanProfiles
- ClusterScanBenchmarks

There will not be an overview page, but the feature nav should default to ClusterScan page.

**Comment by prachidamle** [comment]
This page look good.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `bcc8261`**

- Deploy CIS benchmarks app on a custor
- From the top navigation bar click on the dropdown
- Choose CIS Benchmark form the dropdown
- The following are avialable

```
ClusterScans
ClusterScanProfiles
ClusterScanBenchmarks
```
<img width="662" alt="Screen Shot 2020-09-17 at 4 58 18 PM" src="https://user-images.githubusercontent.com/26032343/93540014-3bb49880-f907-11ea-850b-9a86a32aa483.png">
