### ISSUE TITLE
[RFE] Pod detail screen: container tab does not clearly indicate which container it is

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1203]
Pod detail screen does not show the images for the containers.  But the containers tab in general is not really clear what it's showing.  I think it might be because the container name is also not shown so if you have multiple containers you just get a repeated list of headers, but the context of what container I'm looking at is lost.

**Comment by deniseschannon** [comment]
Added in container name as part of a different PR, but currently UI only supports 1 container per pod detail and need to add in sidecar support.

**Comment by deniseschannon** [comment]
Put the comment into the sidecar issue as this would be fixed there. 

Closing this in favor of it: https://github.com/rancher/dashboard/issues/975
