### ISSUE TITLE
Extract all docs links from dashboard for upcoming new URL structure

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#12040]
We need to get all the existing documentation links in our UI (Dashboard primarily though I don't know if Ember has anything that we actively use) to the Write Club as some recent rebranding has meant that the URL structure will change.

@nwmac may have a script to extract this quickly already so all we have to provide @gunamata with is a list. He can then provide us with new URL patterns for us to then update for 2.10.0 or 2.10.1 which could spawn a new ticket depending on the effort required.

**Comment by nwmac** [comment]
Yes - I have a script.

**Comment by nwmac** [comment]
Here are the links:

Links in Rancher Manager Documentation
  https://ranchermanager.docs.rancher.com/v2.9/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config#external-authentication-configuration-and-principal-users
  https://ranchermanager.docs.rancher.com/v2.9/admin-settings/authentication/google/#3-creating-service-account-credentials
  https://ranchermanager.docs.rancher.com/v2.9/monitoring-alerting/configuration/#alertmanager-configuration/
  https://ranchermanager.docs.rancher.com/v2.9/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/rke1-vs-rke2-differences#cluster-api
  https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon
  https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/azure
  https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/azure
  https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration#additionalmanifest
  https://ranchermanager.docs.rancher.com/v2.9/integrations-in-rancher/logging/logging-helm-chart-options
  https://ranchermanager.docs.rancher.com/v2.9/monitoring-alerting/
  https://rancher.com/eula
  https://ranchermanager.docs.rancher.com/v2.9/faq/telemetry
  https://ranchermanager.docs.rancher.com/v2.9/reference-guides/cluster-configuration/rancher-server-configuration/aks-cluster-configuration#support-private-kubernetes-service
  https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/gke
Links in RKE2 Documentation
  https://docs.rke2.io/install/containerd_registry_configuration
  https://docs.rke2.io/security/hardening_guide
Links in K3S Documentation
  https://docs.k3s.io/installation/private-registry
Other Links
  https://console.developers.google.com/apis/credentials
  https://help.okta.com/en-us/Content/Topics/Directory/LDAP-interface-connection-settings.htm
  https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#understanding-the-encryption-at-rest-configuration
  https://cloud.digitalocean.com/settings/api/tokens
  https://cloud.linode.com/profile/tokens
  https://bmc.phoenixnap.com/credentials/
  https://console.cloud.google.com/projectselector/iam-admin/serviceaccounts
  https://cloud.google.com/kubernetes-engine/docs/how-to/iam-integration
  https://harvesterhci.io/kb/renew_harvester_cloud_credentials
  https://www.suse.com/suse-harvester/support-matrix/all-supported-versions
  https://www.kubewarden.io
  https://istio.io/latest/docs/setup/additional-setup/customize-installation/#patching-the-output-manifest
  https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/
  https://istio.io/latest/docs/concepts/what-is-istio
  https://istio.io/latest/
  https://github.com/longhorn
  https://github.com/neuvector
  https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles
  https://github.com/coreos/prometheus-operator
  https://www.pagerduty.com/docs/guides/prometheus-integration-guide/
  https://rancher.slack.com/apps/A0F7XDUAZ-incoming-webhooks
  https://kubernetes-csi.github.io/docs/drivers.html
  https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/
  https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-user-data
  https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html
  https://cloud.google.com/kubernetes-engine/docs/concepts/alpha-clusters
  https://cloud.google.com/kubernetes-engine/docs/concepts/observability
  https://harvesterhci.io/
  https://docs.harvesterhci.io/

Checking doc links ...
  https://ranchermanager.docs.rancher.com/v2.9/admin-settings/authentication/google/#3-creating-service-account-credentials : 404   
  https://ranchermanager.docs.rancher.com/v2.9/monitoring-alerting/configuration/#alertmanager-configuration/ : 404   
  https://ranchermanager.docs.rancher.com/v2.9/monitoring-alerting/ : 404   

Found 3 link(s) that could not be fetched

Broken links in Rancher Manager Documentation
  https://ranchermanager.docs.rancher.com/v2.9/admin-settings/authentication/google/#3-creating-service-account-credentials
  https://ranchermanager.docs.rancher.com/v2.9/monitoring-alerting/configuration/#alertmanager-configuration/
  https://ranchermanager.docs.rancher.com/v2.9/monitoring-alerting/

**Comment by nwmac** [comment]
@gaktive See above ^^
