### ISSUE TITLE
NavLink icon is missaligned

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12047]
**Setup**
- Rancher version: pre 2.10.0

**Describe the bug**
- Nav links show an icon next to them
- icon is missaligned

**To Reproduce**
- Cluster Explorer --> search for NavLinks --> Create --> enter any name and any URL --> Create

**Result**
![image](https://github.com/user-attachments/assets/0dad6868-3605-4148-b975-fbba2ab49e7c)

**Expected Result**
![image](https://github.com/user-attachments/assets/f5342785-865d-4d1f-84e2-5f5f48fda24c)

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

Reproduced on UI: `release-2.9 7f907d6` . Validated in the above Rancher version the link icon is now properly aligned
