### ISSUE TITLE
Roles page - APIGroup is shown incorrectly

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1204]
In the rbac roles pages the apiGroup "" (empty string) is the "core v1" api group.  Currently it is being shown as "all api groups".  "All api groups" should only be if the api group is "*"

**Comment by deniseschannon** [comment]
For 2.5, we're removing the custom work we applied to the roles pages and we will re-visit this in 2.5.x.

**Comment by izaac** [comment]
Closing, this was validated as part of https://github.com/rancher/dashboard/issues/1322
