### ISSUE TITLE
Vue3: Cloud Credentials 'create' button stays disabled when required values are filled

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12054]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version: Chrome, Firefox

**Describe the bug**
Cloud Credentials 'create' button stays disabled when required values are filled. The user must remove focus from the name input field for the 'create' button to be enabled.

**To Reproduce**
1. go to cluster manager
2. go to cloud credential creation form (`manager/cloudCredential/create`)
3. select any cloud provider (i used aws)
4. fill in all fields and the Credential Name field last
5. notice the 'create' button is disabled
6. remove focus from the name input field
7.  notice the 'create' button is enabled

**Result**
Cloud Credentials 'create' button stays disabled when required values are filled.

**Expected Result**
Cloud Credentials 'create' button is enabled when required values are filled.

**Screenshots**

https://github.com/user-attachments/assets/f2fa0756-b009-4935-a0c3-7c39e5e6dff0

**Additional context**

**Comment by yonasberhe23** [comment]
this scenario is already automated (`cypress/e2e/tests/pages/manager/cloud-credentials.spec.ts` -> `can create aws cloud credentials`)

**Comment by rak-phillip** [comment]
Order does, indeed matter here. The regression might be related to validation.

**Comment by yonasberhe23** [comment]
No longer seeing the issue after the fix; form validation works properly. 

Tested in: 
- Rancher v2.10-13c7bae82c64b32ea68eb8981ee27dd7647c26ec-head
- Dashboard master 49829da
