### ISSUE TITLE
Pod Details Page: workload link pointing to a cluster role

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1205]
If there is a clusterrole that has the same name as the workload for the pod, the "workload" link on the top seems to go to the clusterrole and not the workload.

There might be an assumption that the "owner" of the pod is always in a workload type.  In this case the pod is a pod created from the "kubectl shell" and the owner is in fact a clusterrole. So some check on the "fromType" of the owner relationship is probably needed here.

**Comment by sowmyav27** [comment]
**Verified on 2.5-head - commit id: `56bf444`**

- Create user1 and assign user1 as "cluster-owner" of cluster1
- Login as user1
- Deploy a Job type workload with name "cluster-owner"
- In the pod detail page --> Workload hyperlink --> Click on the hyperlink.
- User is redirected to workload page and not the clusterrole
