### ISSUE TITLE
Clone of global admin role not a 100% carbon copy

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#12052]
Jira: SURE-8806

**Setup**
- Rancher version:  2.8.5
- Rancher UI Extensions: /
- Browser type & version: all

**Describe the bug**
Clone of global admin role not exact copy. (Displayed as `Administrator/admin`)
Where the original role has verbs "*" the copy has a list of individual verbs.
The result is new role does not grant the same views as the original.

**To Reproduce**
- Clone Admin role in GUI
- Assign cloned role role to user.
- View any given cluster in GUI
- User doe not have full visibility compared to the original admin role

**Result**
The clone role does not have "*" verbs as in the original global admin role.

Note: This is about the data, so it's visible only in the YAML editor.

**Expected Result**
Expect a carbon copy.

**Screenshots**

See Jira ticket

**Additional context**

See Jira ticket

**Comment by cnotv** [comment]
@richard-cox changing the client version to v2.8.6 still clones an admin correctly, I suppose this is a server issue?

![Screenshot 2024-09-30 at 16 13 08](https://github.com/user-attachments/assets/e47d1887-b66b-478d-908c-26602e33e5e4)

**Comment by richard-cox** [comment]
@cnotv It looks like it's showing the bug. The verbs have been enumerated from `*` to all known verbs

**Comment by richard-cox** [comment]
The `Grant Resources` section relates to the `role`'s `rules` array. Each one contains a `verbs` lists.

An entry to that `verbs` list could be distinct entries (`create`, `patch`, etc).

![image](https://github.com/user-attachments/assets/1f69c1d3-8d90-4db0-b23f-9541f35b00dc)

![image](https://github.com/user-attachments/assets/a702387d-9baf-4c90-b0ba-ae7320a4f3c9)

Or it could be `*` which means all verbs. This is where the bug is

![image](https://github.com/user-attachments/assets/01931357-62f6-4b23-a325-6b7c0a60ebc8)

![image](https://github.com/user-attachments/assets/e590afcc-ce6c-4015-ac04-952f02567eed)

The component that's showing a grant resource row isn't showing the `*` correctly, it converts it into a list of verbs

**Comment by cnotv** [comment]
Oh ok, in the model/YAML, I thought in the UI sorry.

**Comment by cnotv** [comment]
These 2 cases are the same but have different logic and URLs, so there's something wrong with the whole concept of editing in Rancher:
- Edit YAML: `/c/local/auth/roles/management.cattle.io.globalrole/admin?mode=edit&as=yaml`
-  Edit config with YAML tab: `/c/local/auth/roles/management.cattle.io.globalrole/admin?mode=edit#grant-resources`

Refreshing the page and keeping the YAML editor is also impossible since it redirects to the configuration.

**Comment by cnotv** [comment]
Here is a summary of what I reported today: the whole resource editing process has a logic where data initialization is injected into YAML, without providing a way to restore the mapping (like from `*` to verbs list in our case). This means that not just clones but any editing will malform data.

In the video, you can see how the roles are always manipulated and cannot be restored if edited in the form. As an outcome of this logic, we want to instead map all the verbs always into `*` and vice-versa, regardless of the operation.

https://github.com/user-attachments/assets/aa0f4c7d-c9ef-4772-beaa-a01ee2781857

**Comment by richard-cox** [comment]
I don't think we want to map anything to anything, that's the issue. If there's a `*` it should remain as so. If there's a list it should also remain as so.

The bug is we're converting a `*` to a list of verbs. Where about is that happening?

**Comment by cnotv** [comment]
We must map it for sure, because we do not have a UI for `*`.
The thing is that we should keep intact the model, which we do not.
If we map the `*` once it has to be always, otherwise it's inconsistent in both data and UI, plus the code will be even more hacked.

**Comment by richard-cox** [comment]
I'm not quite sure i follow.

I had a look, this is the code that maps * to the list of verbs https://github.com/rancher/dashboard/blob/master/shell/components/auth/RoleDetailEdit.vue#L130-L134. We just need to not do this, and also ensure `*` is a valid entry

**Comment by cnotv** [comment]
> also ensure * is a valid entry

Define valid entry, if you do not mind.
Would this PR not work as intended? https://github.com/rancher/dashboard/pull/12235

**Comment by richard-cox** [comment]
Valid entry in the select component.

The PR won't work because it's mapping * to a list of verbs. Lets get together after the team meet to go over this

**Comment by cnotv** [comment]
Updated PR as agreed in the meeting https://github.com/rancher/dashboard/pull/12235

**Comment by HoustonDad** [comment]
While this is set for v2.10, can we get backports into v2.8 and v2.9?

**Comment by richard-cox** [comment]
v2.8 is EOM, v2.9 is a possibility though

**Comment by yonasberhe23** [comment]
Clone of global admin role is properly copied. 

Tested in: 

- Rancher v2.10-ae6ac83471545ab47d052d2d760daa2e6646a969-head
- Dashboard master 225e3e6 

https://github.com/user-attachments/assets/ca7979ff-2115-4e9b-b7f0-c8a3dea03226
