### ISSUE TITLE
Split RKE2 Addon Configuration out into multiple tabs

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12066]
- Addon configuration relate to chart values that are applicable to the distro, kube version and cloud provider
  - Example Container Networks (canal, celium, calico, etc) all have their own config
- Currently this is shown in a single tab `Add-on Config`
- These are virtually hidden and offer little scope to add customisation
- We should split out each add-on into it's own tab

**Comment by yonasberhe23** [comment]
Performed smoke test as this change was tested in previous releases. 

Tested in:
- Rancher v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head
- Dashboard master 78df731
