### ISSUE TITLE
Workloads - Design Polish

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1206]
- [ ] In Node Scheduling, the operator dropdown doesn't need to be this wide. Correct it so that key/value textboxes have as much width as possible.

<img width="400" alt="Screen Shot 2020-09-08 at 4 53 42 PM" src="https://user-images.githubusercontent.com/11410997/92538597-f64fe700-f1f3-11ea-8537-089ecb7480fd.png">

**Comment by lvuch** [comment]
this is not reproducable/resolved

**Comment by deniseschannon** [comment]
I still see this issue in master.

**Comment by aaronRancher** [comment]
The fix is verified with Rancher server `rancher\rancher:master-head` `version 59936f7`

Key/Value text boxes are wider. All fields are the same width.
![Screen Shot 2020-09-16 at 12 56 46 PM](https://user-images.githubusercontent.com/57409052/93386232-40e8e900-f81c-11ea-87d2-e773f9b278ff.png)
