### ISSUE TITLE
Extensions install/uninstall loading process stuck

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#12075]
**Describe the bug**
When installing or uninstalling any extension, the loader is stuck and requires a force upload to display and access the configuration.

**To Reproduce**
- Navigate to the extensions page
- Install any extension
- The loader should start spin and/or redirect to the new tab

**Result**
The extension still not listed as installed, or still displays uninstall status

**Expected Result**
Process is completed with clear UX and data

**Screenshots**

https://github.com/user-attachments/assets/b42c07ab-856a-453f-994b-d37289f2e4f9

**Additional context**

E2E tests are failing as result.

**Comment by aalves08** [comment]
Yes it is. It should be fixed on this PR: https://github.com/rancher/dashboard/pull/12071. I am going to need your help @richard-cox by reviewing this one. It needs a second-pair of experienced eyes on it.

Me and Jordon have been working on it and I am just doing the final cleanup. I'll let you know when it's ready for a review

**Comment by yonasberhe23** [comment]
See https://github.com/rancher/dashboard/issues/11695#issuecomment-2422997768. Moving to To Test

**Comment by izaac** [comment]
I've use the plugins example extensions repo for validation. Which is ready for Vue3 and meets the requirements.
`https://github.com/rancher/ui-plugin-examples`

Rancher version: `v2.10-695357ad2fdb58bfce027ecf6ce96e8a4e3ddbab-head`
UI: `master e7876c6`

Installing and uninstalling works, the UI isn't stuck and there aren't errors in the browser's console. 
Further testing will be done when validating: https://github.com/rancher/dashboard/issues/11474
