### ISSUE TITLE
Role template: Switching from Config to YAML editor breaks

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#12073]
**Describe the bug**

When switching editor between Config and YAML for the Role Template, it breaks. The issue may be related to https://github.com/rancher/dashboard/issues/12052, although the UI does not break in that case.

**To Reproduce**
- Navigate to `User & Authentication > Role Templates` (`/c/_/auth/roles#GLOBAL`)
- Edit Config for an existing user role, e.g. Administrator
- Switch view to YAML

**Result**

Nothing happens, error in console:

```
entry-helpers.js:40 Error: Cannot find resourceFields for Schema management.cattle.io.templateversion (schemaDefinitions have not been fetched) 
    at get resourceFields (steve-schema.ts:103:1)
```

**Expected Result**
It switches the view, just as it does for all the other resources.

**Screenshots**

https://github.com/user-attachments/assets/46de3314-2d04-47bd-91c0-92817215ee45

**Additional context**

Cluster editor, Workload editor and probably all the other work as expected.

**Comment by gaktive** [comment]
@richard-cox does this look like part of your schema diet changes? Was this one of the schemas that was removed?

**Comment by richard-cox** [comment]
It means the resourceFields was accessed without the call to /schemaDefinition to populate it. There's plumbing in generic components that handle this though, so if it's a vue3 regression there's probably a hook somewhere that's not being called

**Comment by momesgin** [comment]
It seems this issue is not blocking the Edit Yaml anymore, but you can still see that error on the console when you're redirected to the Role Templates page after saving/cancelling.

https://github.com/user-attachments/assets/e583e293-91cf-4099-b3ad-f9ea0b782354

**Comment by rak-phillip** [comment]
The fetch errors only happen when navigating back to the list. 

I suspect that this behavior is related to #11986. It looks like `shell/components/ResourceDetail/index.vue` is the culprit for the error message.

 https://github.com/rancher/dashboard/blob/9e9e25b087d9499e6c31cfafaf066eee52f36102/shell/components/ResourceDetail/index.vue#L321-L338

**Comment by yonasberhe23** [comment]
No longer seeing error when cancelling/navigating back to list. Tested in: 

- Rancher v2.10-0cddb5f146709bf471b863e6715b0a7538572e74-head
- Dashboard master 73bff03
