### ISSUE TITLE
Cluster role/role page: Not showing resource name

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1207]
Clusterrole/role page is not showing "resource name" field so it's displaying the rules wrong because it effectively looks like it's granting "all resources" instead of a specific resource name

**Comment by deniseschannon** [comment]
For 2.5, we're removing the custom work we applied to the roles pages and we will re-visit this in 2.5.x.

**Comment by izaac** [comment]
These pages are now showing generic detail pages showing only the YAML
