### ISSUE TITLE
yaml: >=2.2.2

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#12090]

**Comment by yonasberhe23** [comment]
dependency bump touches Harvester, we should probably do smoke test to ensure nothing is broken there. Moving to To Test

**Comment by izaac** [comment]
@rak-phillip what would be the result in case it's broken on Harvester? It's a one off broken or working scenario? Or does it involve a more detailed validation. 

If the former I think we can move this one to done, as there are other 2.10 Harvester issues pending validation already.

**Comment by rak-phillip** [comment]
@izaac see this comment in the associated PR for more details

https://github.com/rancher/dashboard/pull/12103#pullrequestreview-2352466087

> the `YAML` dependency is used to handle the User Data field as a yaml.
