### ISSUE TITLE
Login Expired - Blank page loads

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1210]
When the login expires, nothing happens.

I can still use the navigation to go to a page, but the content doesn't load. When I try and refresh the page, it ends up with a blank page. Eventually it 404s.

Is there something that can be done to re-direct back to sign in?

**Comment by maggieliu** [comment]
Can this be re-tested on local cluster and downstream cluster.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `1b0778b1dd`**

- Have 2 tabs - one with Rancher ember UI and one with Dashboard page
- Logout from Rancher Ember page
- refresh Dashboard page
- User is navigated back to Rancher login page. (Without the fix, user would have seen a blank page in this case)
