### ISSUE TITLE
Vue3: CTA buttons are center aligned throughout Rancher

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12108]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: Chrome, Firefox

**Describe the bug**
 CTA buttons are center aligned throughout Rancher (not Ember).
- Fleet,
- Cluster Manager, 
- Harvester, 
- Users & Auth, 
- Explorer pages

**To Reproduce**
1. go to any of the mentioned areas in Rancher
2. notice alignment of CTA buttons 

**Result**
 CTA buttons are center aligned throughout Rancher

**Expected Result**
 CTA buttons are right aligned throughout Rancher

**Screenshots**

https://github.com/user-attachments/assets/d9289d74-5178-4041-9685-6ece715fa9f1

**Additional context**

**Comment by rak-phillip** [comment]
This is a recent regression that was introduced via #12062.

**Comment by yonasberhe23** [comment]
CTA buttons throughout Dashboard are aligned correctly now. 

Tested in: 
Rancher v2.10-afe9248a3837e249ceb92ce57fd94bc107dcb51a-head
Dashboard master 6146198
