### ISSUE TITLE
Vue3: Bug with LabeledSelect with "multiple" attribute

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12117]
**Setup**
- Rancher version: Any + Vue3 frontend
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

Using `LabeledSelect` with option `multiple="true"` is not working properly

**To Reproduce**

- Create some secrets of type `kubernetes.io/dockercfg` (at least a couple)
- Create Registry Secret if missing
- Go to Deployments -> Create -> go to the `Pull Secrets` select on the `General` tab and select an option

**Result**
- Throws an error

**Expected Result**

- Should work fine

**Screenshots**

**Vue3** (fails)
https://github.com/user-attachments/assets/ede5a1ec-432a-4ba9-9562-1131ca6b5276

**2.9-head** (works)
https://github.com/user-attachments/assets/52ba106a-4e41-4921-8dca-515210b9d017

**Additional context**

I believe it's related to the option `multiple="true"`
https://vue-select.org/guide/values.html#single-multiple

If we add the attribute `multiple` to  the `v-select`, the output is an array and it works fine, so the binding of the attributes is where the problem lies

**Comment by cnotv** [comment]
Note: This issue seems a recent regression since I had to pull master to reproduce it.

**Comment by yonasberhe23** [comment]
Error no longer thrown and able to select multiple options from LabelSelect.
Tested in:
Rancher	v2.10-9d9e01a847460bb3450a62f83735708d6eada5e5-head
Dashboard master cf8c6d1

![Image](https://github.com/user-attachments/assets/a965deb0-d6ca-42e1-ac2d-6e7ba2cc3798)
