### ISSUE TITLE
[UI] list of instance types in the Rancher UI for RKE1 EC2 is stale

### ISSUE THREAD

**Issue by tp-drosssmith** [rancher/dashboard#12120]
similar to https://github.com/rancher/rancher/issues/22907 from 2019 I'd like to use newer instance types in the "Instance Type" field when using the Node Group template.

I've forked the UI repo and have a PR at https://github.com/rancher/ui/pull/5178.

The TLDR is I've tried to update Intel/AMD instance types but have ignored including Graviton instances because Rancher docs say ARM64 support is "experimental".

**Comment by mantis-toboggan-md** [comment]
This list is up-to-date in EKS 2.9, but not ec2 RKE1  node templates:
![Screenshot 2024-10-03 at 9 51 51 AM](https://github.com/user-attachments/assets/e5491fc5-7e65-4f93-ab8f-21f06cd1d50a)

![Screenshot 2024-10-03 at 9 59 37 AM](https://github.com/user-attachments/assets/716b53c2-ede0-4888-8870-431f1aedb758)

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

Confirmed the instances types are now in RKE1 templates. AWS EC2 RKE2 and EKS cluster types.
