### ISSUE TITLE
Vue3: Tooltip styling has changed

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12126]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: Firefox, Chrome

**Describe the bug**
Tooltip style has changed.

**To Reproduce**
1. go to Rancher home page > hover over side nav button
2. go to Explorer > hover over header buttons
3. go to Explorer > workloads > hover over flat list/group by ns buttons

**Result**
<img width="1413" alt="Screenshot 2024-10-03 at 9 34 08 PM" src="https://github.com/user-attachments/assets/a9a8c84c-2a83-4a5a-bb87-3a0e63196fd3">

**Expected Result**
<img width="1408" alt="Screenshot 2024-10-03 at 9 35 14 PM" src="https://github.com/user-attachments/assets/d2649da4-cbf5-40e9-bda8-6ec38651ae88">

**Comment by cnotv** [comment]
Placement modifiers are not honored, I suspect some hacks have truncated any definition: https://floating-vue.starpad.dev/guide/directive#placement-modifier

**Comment by cnotv** [comment]
Tooltip also broken for main navigation bar.

![Screenshot 2024-10-07 at 23 39 38](https://github.com/user-attachments/assets/4b1b97c5-1ec1-48cd-adf4-2f5553f8693e)

**Comment by cnotv** [comment]
Probably every tooltip is broken in the current state. This is for labels:

![Screenshot 2024-10-08 at 00 01 22](https://github.com/user-attachments/assets/343ae1ef-cf9e-4a71-8cab-142dccd0211e)

**Comment by cnotv** [comment]
@eva-vashkevich @mantis-toboggan-md I see a lot of AKS/EKS/GKE use cases for the tooltip. May I ask you to confirm the default style is the right one? It would mean arrow center bottom.

**Comment by cnotv** [comment]
This issue is a regression of existing changes which have been reported and fixed with:
- https://github.com/rancher/dashboard/issues/11684
- https://github.com/rancher/dashboard/issues/11685 
- https://github.com/rancher/dashboard/issues/11740 
- https://github.com/rancher/dashboard/issues/11742
- https://github.com/rancher/dashboard/issues/11763

All these cases have to be tested afterward. Trying to identify the regression PR at this point, although refactoring in a single file only would be optimal.

**Comment by rak-phillip** [comment]
Hmm I'm finding this to be quite confusing - it appears that commit 1bc35071b9322273e3fff4dbc0e77bdd7b823cbd is the first one to exhibit this behavior. Are you finding the same?

**Comment by mantis-toboggan-md** [comment]
> @eva-vashkevich @mantis-toboggan-md I see a lot of AKS/EKS/GKE use cases for the tooltip. May I ask you to confirm the default style is the right one? It would mean arrow center bottom.

Yes AKS/EKS/GKE should use default tooltip styling

**Comment by yonasberhe23** [comment]
The tooltip issues have been resolved throughout Dashboard except for resource lists. (https://github.com/rancher/dashboard/issues/12197)

Tested in:
Rancher v2.10-8b50f8332866224f855d0d5daa535c98bc9a2f6d-head
Dashboard master 9b3c6ae
