### ISSUE TITLE
Improve tracking of vGPUs allocation

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#12133]
**Is your feature request related to a problem? Please describe.**

Related Harvester issue https://github.com/harvester/harvester/issues/5774

**Describe the solution you'd like**

- https://github.com/harvester/harvester/pull/6096 introduced the new `/v1/harvester/cluster` endpoint to provide available Harvester resources, including vGpu allocatable number.
- We want to use those information to improve the user experience assigning new vGpu devices to Harvester provisioned clusters.

**Describe alternatives you've considered**

**Additional context**

**Comment by khushboo-rancher** [comment]
Reopening for the validation

**Comment by noahgildersleeve** [comment]
Tested with Harvester v1.4.0-rc2 with Rancher versions

- v2.8-68e5d43e449fcd3ef73baf1caee98da6f0104eed-head
![Greenshot 2024-10-09 17 47 34](https://github.com/user-attachments/assets/e60d594d-0f23-4b0d-bde6-8caec0d0cff6)
![Greenshot 2024-10-09 17 46 08](https://github.com/user-attachments/assets/62da3e9b-f926-41fd-bbc9-69e034501f8c)
![Greenshot 2024-10-09 17 45 47](https://github.com/user-attachments/assets/52e52c73-3bec-43e1-bdb6-a4306258e621)
![Greenshot 2024-10-09 17 45 39](https://github.com/user-attachments/assets/e2bb36e4-0e67-4bb5-9656-18b039114f0b)

- v2.9-af2463ff43418024ff86cfd9304836b7074a924a-head
![Greenshot 2024-10-09 18 04 22](https://github.com/user-attachments/assets/2327197a-d63f-456f-8cdd-dd7e7007daae)
![Greenshot 2024-10-09 18 04 18](https://github.com/user-attachments/assets/9eba035b-54a9-4669-9a15-089fc3c5e101)
![Greenshot 2024-10-09 18 03 48](https://github.com/user-attachments/assets/cf3b5ec5-c2c0-4182-b7fd-328f42498495)

- v2.10-fe30db77dab22d42b769c9d88d9410a8044c4066-head
![Greenshot 2024-10-09 20 21 08](https://github.com/user-attachments/assets/3f8d5a0a-80e1-49e8-a4f3-8857bfd3098c)
![Greenshot 2024-10-09 20 20 29](https://github.com/user-attachments/assets/d37edea5-7434-4466-82d9-1bd1c0a8dce7)
![Greenshot 2024-10-09 20 20 12](https://github.com/user-attachments/assets/7e586bdf-c2be-4448-8df1-298ba3f2ec42)
![Greenshot 2024-10-09 19 49 03](https://github.com/user-attachments/assets/a03648e5-bc13-40ef-834d-1bfa8f1256b8)
![Greenshot 2024-10-09 19 48 38](https://github.com/user-attachments/assets/7f834849-68a5-47e5-ab01-f16e88d1797f)
![Greenshot 2024-10-09 19 48 32](https://github.com/user-attachments/assets/3006a98a-ea51-4db2-b8f7-c97e4bd3fc7c)
