### ISSUE TITLE
[Monitoring / Alerting V2 UI] Navigation Bar

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1215]
Annotation: `catalog.rancher.io/ui-component: monitoring`

On the Navigation bar for the Monitoring / Alerting, the title should show `Monitoring / Alerting` instead of just `Monitoring` like it shows right now.

In addition, on viewing components of Monitoring / Alerting, the following CRDs / Custom UIs should be shown on the left sidebar in the order described below:
Name of Component | CRD or Custom Component? | Show or Hide? |
|---|---|---|
ServiceMonitors | servicemonitors.monitoring.coreos.com | Show
PodMonitors | podmonitors.monitoring.coreos.com | Show
PrometheusRules | prometheusrules.monitoring.coreos.com | Show
AlertManager Config | Custom Component (https://github.com/rancher/dashboard/issues/1017) | Show
Prometheuses | prometheuses.monitoring.coreos.com | Hide
Alertmanagers | alertmanagers.monitoring.coreos.com | Hide
ThanosRules | thanosrules.monitoring.coreos.com | Hide

**Comment by westlywright** [comment]
Partially addressed in https://github.com/rancher/dashboard/pull/1219

The custom component for AlertManager will be added with the Component itself.

**Comment by aiyengar2** [comment]
https://github.com/rancher/dashboard/issues/1260 needs to be addressed with this if it is still in review

**Comment by deniseschannon** [comment]
Let's close this for now and track any changes in the other ticket.
