### ISSUE TITLE
[Alerting V2 UI] Receivers - Additional Receivers

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1216]
#### Note
~This ticket has been split off from the main ticket in https://github.com/rancher/dashboard/issues/1017 to remove things that are not relevant till release. It will be formatted in the exact same way for consistency.~

This ticket tracks additional notification configurations for Receivers that need to be added for https://github.com/rancher/dashboard/issues/1238 ~as well as the ability to specify custom templates for the Alertmanager Config Secret (TBD now).~ (https://github.com/rancher/dashboard/issues/1888)

Please see the original ticket for notes / clarifications that will not be duplicated onto this ticket for context.

#### PagerDuty

*Help Text: `Here's how you [create an Integration Key](https://www.pagerduty.com/docs/guides/prometheus-integration-guide/) for PagerDuty`*

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Integration Type | N/A | N/A | Dropdown of `Events API v2` or `Prometheus` | `Prometheus`
Default Integration Key | `Events API v2`: `.pagerduty_configs[0].routing_key`<br>`Prometheus`: `.pagerduty_configs[0].service_key` | N/A | `string` | `null`
Proxy URL | `.pagerduty_configs[0].http_config.proxy_url` | Placeholder: `e.g. http://my-proxy/` | `string` | `null`
Send Resolved Alerts | `.pagerduty_configs[0].send_resolved` | N/A | `boolean` | `true`

#### OpsGenie

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
API Key | `.opsgenie_configs[0].api_key` | Placeholder: `global.opsgenie_api_key` | `string` | `null`
Responders | `.opsgenie_configs[0].responders` | `N/A` | List of Responders (see below) | `[]`
Proxy URL | `.opsgenie_configs[0].http_config.proxy_url` | Placeholder: `e.g. http://my-proxy/` | `string` | `null`
Send Resolved Alerts | `.opsgenie_configs[0].send_resolved` | N/A | `boolean` | `true`

Where a Responder has the following spec:
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Type | `.type` | `N/A` | `team`, `user`, `escalation`, or `schedule` | `N/A/` but required
Send To | `.id`, `.name`, or `.username` | Identifies the responder to send the request to | One box that takes in the type of identifier (e.g. `ID`, `Name`, or `Username` and a text box for the input | `ID` and `N/A`

**Comment by maggieliu** [comment]
Switch out Wechat to OpsGenie

**Comment by bashofmann** [comment]
Will Microsoft Teams also be supported in v2 again? That was a much requested feature in v1.

**Comment by aiyengar2** [comment]
@bashofmann the `rancher-monitoring` chart needs to add support for `rancher-webhook` for that to be supported since MS teams is not something that is supported by Prometheus natively iirc. This is being tracked in https://github.com/rancher/rancher/issues/29951.

**Comment by codyrancher** [comment]
@lvuch Can you make icons for  OpsGenie and PagerDuty?

**Comment by codyrancher** [comment]
@aiyengar2 Is it fine to just use all of these fields for opsgenie? https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config

And can you setup a discussion for Template Files so we can make decision?

**Comment by aiyengar2** [comment]
@codyrancher I updated the necessary PagerDuty fields. Each type of receiver has different required fields, so we'll need Responders for PagerDuty as well. I think API URL can be dropped since that can be globally set. I don't think it's a common override either.

Will set up a template files discussion next week when Denise is back!

**Comment by codyrancher** [comment]
Alright, sounds good. Sorry, I must have missed the update. I'll go ahead and file a separate ticket for the template.

**Comment by aiyengar2** [comment]
Just moved the template file stuff off to https://github.com/rancher/dashboard/issues/1888. I think we should tackle that as a separate task since it's more of a feature request that can be prioritized outside of this issue.

cc: @maggieliu @deniseschannon

**Comment by jiaqiluo** [comment]
Found the following problems on v2.5-head 182e3de

for PagerDuty:
1. The default of `Integration Type` is expected to be `Prometheus`, but it is `Events API v2` now. 
<img width="689" alt="Screen Shot 2020-12-14 at 4 08 10 PM" src="https://user-images.githubusercontent.com/6218999/102146650-9b4b1300-3e26-11eb-81e6-5a9eba31a692.png">

for OpsGenie:

2. The `responders` are missing when viewing or editing the existing receiver as the Form, and you can see the existing responders when viewing or editing as the YAML 
<img width="924" alt="Screen Shot 2020-12-14 at 4 22 24 PM" src="https://user-images.githubusercontent.com/6218999/102147991-e9f9ac80-3e28-11eb-8bb3-8aba82832b10.png">
<img width="483" alt="Screen Shot 2020-12-14 at 4 24 15 PM" src="https://user-images.githubusercontent.com/6218999/102147999-ec5c0680-3e28-11eb-8bdc-24b3fc65bb62.png">


3.

**Comment by codyrancher** [comment]
@jiaqiluo 

1. Fixing this
2. I couldn't reproduce this. Did you do anything special?
![receivers](https://user-images.githubusercontent.com/55104481/102189299-ac6e4100-3e73-11eb-9827-5d14de0fd2ab.gif)

3. I don't think we should do this unless we're doing it elsewhere. I'm not aware of any other locations though. Would you like to ask someone else to weigh in?

**Comment by jiaqiluo** [comment]
The bugfix is validated on v2.5-head bd660e1

1. The default integration type is Prometheus
![image](https://user-images.githubusercontent.com/6218999/103025010-30789680-450e-11eb-8903-5e101a28d657.png)

2. This cannot be reproduced anymore. 
3. I am ok if this the default behavior across the entire dashboard UI.
