### ISSUE TITLE
Small Nav Updates for Gatekeeper

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1217]
~Logging - Request for Overview link~

- [x] Can we add an actual link `Overview` into the nav bar for logging so that if I click into one of the CRDs and then want to go back to the Overview, I'll be able to get to it? 

<img width="441" alt="Screen Shot 2020-09-09 at 11 07 29 PM" src="https://user-images.githubusercontent.com/11410997/92688000-61cbae80-f2f1-11ea-8a61-e80a9c0e1013.png">

OPA Gatekeeper
- [x] Can the order of the navigation be
```
Overview
Constraint
Template
```

<img width="270" alt="Screen Shot 2020-09-09 at 11 12 23 PM" src="https://user-images.githubusercontent.com/11410997/92688283-f1715d00-f2f1-11ea-9351-6d566080d48d.png">

- [x] Can we add `Overview` heading and `Powered by OPA Gatekeeper` text similar to what we did for logging? The link should direct to https://github.com/open-policy-agent/gatekeeper
- [x] Can we remove the extra shadow border around the Violations table?

<img width="805" alt="Screen Shot 2020-09-09 at 11 15 07 PM" src="https://user-images.githubusercontent.com/11410997/92688517-55942100-f2f2-11ea-9b91-3a253aeddede.png">

**Comment by izaac** [comment]
Rancher version: `master-head (09/28/2020)`  _ec04f78_ HA k8s with DO RKE downstream cluster.

- Link to Overview is now present.
- Extra Shadow border is removed
- Overview header with Powered by OPA Gatekeeper is present and the link redirects properly in a new tab to https://github.com/open-policy-agent/gatekeeper
-  Order of navigation is
   - Overview
   - Constraint
   - Templates

Opened #1484, small styling/navigation issue.
