### ISSUE TITLE
Header tooltop styles contain arrow

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#12174]
21050a369509eb5964df723ac20c4899c16e7aca contained a typo (`class` instead of `style`) that caused styles to be applied globally. Incidentally, style overrides to remove the arrow are no longer valid.

> That's a good catch, and resolves the issues regarding tooltip styling throughout dashboard. I am noticing a regression in the header styles, but I'm opting to open a new issue to address since the implementation is clearly incorrect from the outset.

![image](https://github.com/user-attachments/assets/94ae9cb7-e201-4e36-b772-7004d948e0a7)

_Originally posted by @rak-phillip in https://github.com/rancher/dashboard/pull/12172#pullrequestreview-2354989318_

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

I can't reproduce this on this Rancher version. Validated on dark and light themes on the landing page and clusters management.
