### ISSUE TITLE
Update OCI's creation message

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#12173]
**Describe the bug**

As per requested by the team who worked on the OCI feature, we should update the current message on the OCI repository creation page. It's basically just removing `For better performance` from the message.

Current message:
```
For better performance, add OCI URLs that contain ONLY helm charts. For example oci://test.rancher.io/charts or oci://test.rancher.io/charts/mychart. The list of charts available from the repository is updated every 6 hours. Scanning directories with a large number of artifacts may degrade performance considerably.
```
Updated message:
```
Add OCI URLs that contain ONLY helm charts. For example oci://test.rancher.io/charts or oci://test.rancher.io/charts/mychart. The list of charts available from the repository is updated every 6 hours. Scanning directories with a large number of artifacts may degrade performance considerably.
```

**Comment by momesgin** [comment]
@gaktive I've added 2.10.0 milestone as it's a minor change, but please let me know if I should change that

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

Validated this is now displayed as the described expectation. It is also properly capitalized.
