### ISSUE TITLE
Vue3: Cluster list: RKE1: Provider column for newly provisioned cluster says RKE instead of RKE1

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12192]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: Chrome, Firefox

**Describe the bug**
The provider column on the cluster list for a newly provisioned cluster says RKE instead of RKE1 until the user refreshes the page.

**To Reproduce**
1. create RKE1 cluster (AWS/Azure)
2. go to cluster list
3. wait for the provisioning process to complete (~9 minutes)
4. provider column says RKE
5. refresh the page
6. provider column says RKE1

**Result**
The provider column for a newly provisioned cluster says RKE instead of RKE1 until page refresh.

**Expected Result**
The provider column for a newly provisioned cluster says RKE1 without refresh.

**Screenshots**

https://github.com/user-attachments/assets/451acfb6-92d7-41de-ae4a-372d6a1b0408

**Additional context**

**Comment by richard-cox** [comment]
Might also be related to related to https://github.com/rancher/dashboard/issues/12189 (if info is dependent on something updated within the cluster)

**Comment by gaktive** [comment]
Once #12189 is merged, whoever picks this up can validate with that (or if sooner, with the appropriate PR).

**Comment by rak-phillip** [comment]
While testing #12194, I was also able to confirm that this is resolved by #12171.

**Comment by momesgin** [comment]
@rak-phillip thanks for the update!

@yonasberhe23 I leave this issue to you then

**Comment by yonasberhe23** [comment]
Issue resolved. 

Tested in:

- Rancher v2.10-ae6ac83471545ab47d052d2d760daa2e6646a969-head
- Dashboard master 225e3e6
