### ISSUE TITLE
Vue3: Cluster Details: RKE1: Node state for newly provisioning cluster says Provisioning instead of Active

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12194]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: Chrome, Firefox

**Describe the bug**
The node state for a newly provisioning cluster says Provisioning instead of Active until the user refreshes the page.

**To Reproduce**
1. create RKE1 cluster (AWS/Azure) OR add a node to an existing RKE1 cluster
2. go to cluster details > Machine Pools tab
3. wait for the provisioning process to complete (~9 minutes)
4. state column says Provisioning
5. refresh the page
6. state column says Active

**Result**
The node state for a newly provisioning cluster says Provisioning instead of Active until page refresh.

**Expected Result**
The node state for a newly provisioning cluster says Active without refresh.

**Screenshots**

https://github.com/user-attachments/assets/a40fcaf6-bbbd-47bb-8492-5e100f050071

**Additional context**

**Comment by richard-cox** [comment]
Possibly related to https://github.com/rancher/dashboard/issues/12189

**Comment by rak-phillip** [comment]
I tested this and it looks to be fixed with #12171.

**Comment by richard-cox** [comment]
Reopening, @rak-phillip  i think you tagged #12282 with the wrong issue

**Comment by yonasberhe23** [comment]
Issue resolved. 

Tested in:

- Rancher v2.10-ae6ac83471545ab47d052d2d760daa2e6646a969-head
- Dashboard master 225e3e6
