### ISSUE TITLE
Cannot see the logs of the helm-operation pod when installing apps in dashboard

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#1220]
Bug 

Steps:
- run rancher:`master-198ec5bdf52d3ed2b4865cfcf6ac1d61150bf55f-head` HA
- go to local cluster 
- go to dashboard -> apps -> install monitoring

Result:
- while the app is installing, the logs of the helm-operation pod show in the UI, but it is disconnected. 

<img width="934" alt="Screen Shot 2020-09-10 at 9 46 16 AM" src="https://user-images.githubusercontent.com/6218999/92771220-8ce4eb00-f34f-11ea-9fa7-792ffeb39cf5.png">
 

<img width="1175" alt="Screen Shot 2020-09-10 at 9 48 54 AM" src="https://user-images.githubusercontent.com/6218999/92771233-8eaeae80-f34f-11ea-9ec4-0c719d28a4e1.png">

**Comment by sowmyav27** [comment]
**On master-head - `ab6598e5a`**

- Deploy an app. (backup-restore)
- Logs are seen while the app is being deployed.

**Comment by sangeethah** [comment]
https://github.com/rancher/rancher/pull/28839
