### ISSUE TITLE
Helm Install: New namespace creation banner is obscured

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#12205]
Go to create a helm application from Apps and Marketplace by selecting a chart.

For namespace, choose the option to create a new namespace and specify a name.

A banner is shown at the bottom of the page to indicate that a new namespace will be created - this banner is obscured - see below - it should not be.

![image](https://github.com/user-attachments/assets/5637cb1f-9384-49df-8295-55cea2acfc77)

**Comment by gaktive** [comment]
Possible regression.

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-10e26d1256a15f76e27a41184d92c4b8781dd94b-head`
UI version: `master 6dd2962`

This is is always visible in that UI view. I checked both light and dark themes on Chrome/Firefox.
