### ISSUE TITLE
Form validation broken on GitRepo page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#12204]
Go to Fleet, Git Repos and press 'Create'.

The 'Next' button is disabled as expected.
Enter a name.
Validation does not update until after you remove focus from the name field - it should do so as you type a name.

Note also that Repository URL is not marked as required, when it is.

if you create a  Git Repo without a URL, this breaks the UI when you try to list GitRepos.

To be fixed:

- Updates to the name field should update the validation status immediately as you type
- Repository URL should be marked as required and should be validated
- GitRepos list page should not break if the Repository URL of a repository is undefined

**Comment by gaktive** [comment]
This is OK in 2.9.x so this is a regression in 2.10.0

**Comment by yonasberhe23** [comment]
unit tests are sufficient. moving to done

**Comment by yonasberhe23** [comment]
Next button is no longer greyed out when required fields are filled. repo url validation removed.

Tested in:

- Rancher v2.10-e2d0b42c91253243696d36f09e8e6e23cc6fb0db-head
- Dashboard master 3c808b4
