### ISSUE TITLE
vGPU dropdown isn't showing properly when adding vGPUS to downstream RKE2 clusters on Harvester

### ISSUE THREAD

**Issue by noahgildersleeve** [rancher/dashboard#12215]
**Setup**
- Rancher version: `v2.10-fe30db77dab22d42b769c9d88d9410a8044c4066-head`
- Rancher UI Extensions: 
- Browser type & version: Chrome 129.0.6668.91 on Mac OS 14.6.1
- Harvester version: v1.4.0-rc2 (single node bare metal)
**Describe the bug**

When adding vGPUs to a second RKE2 cluster being provisioned on a downstream Harvester cluster the dropdown doesn't show anything.
**To Reproduce**

1. Provision a RKE2 cluster with vGPUs on Harvester
2. Wait for the VMs to be created
3. Create a second cluster with the available vGPUs
4. Try to select something from the dropdown
**Result**
The dropdown is blank
**Expected Result**

You should be able to see and provision the vGPUs on the RKE2 cluster
**Screenshots**

![Greenshot 2024-10-10 13 15 26](https://github.com/user-attachments/assets/d22ddd53-3aae-4293-843b-ecf2366ed1e7)
![Greenshot 2024-10-10 13 14 30](https://github.com/user-attachments/assets/2c5f3aec-7b97-48c1-8417-3cb936a84cf2)
![Greenshot 2024-10-10 13 10 56](https://github.com/user-attachments/assets/9c073820-e85e-42f2-b73f-c1702cadd747)

**Additional context**

If you click the dropdown than it still will provision the RKE2 clusters correctly with the vGPUs. You can verify this in the Harvester cluster by checking vGPUs on the VMs

**Comment by richard-cox** [comment]
Could be related to https://github.com/rancher/dashboard/issues/12117, however that has been merged.

@noahgildersleeve can you confirm the version of the dashboard that's loaded (Side bar --> About --> `Dashboard`), does the same issue happen in 2.9?

**Comment by noahgildersleeve** [comment]
ThIs isn't happening in Rancher v2.9-head. The dashboard version is `master 7a296a5`

**Comment by noahgildersleeve** [comment]
I can get you the versions for Rancher v2.9-head as well if you need them.

**Comment by richard-cox** [comment]
Thanks @noahgildersleeve. That commit does contain the fix from https://github.com/rancher/dashboard/issues/12117. Though i was muddled, thought this was machine-config related however it's harvester extension based, from v1.4.0-rc2 (guessing that's serving up a non-vue3 extension @torchiaf )?

**Comment by torchiaf** [comment]
> Thanks @noahgildersleeve. That commit does contain the fix from #12117. Though i was muddled, thought this was machine-config related however it's harvester extension based, from v1.4.0-rc2 (guessing that's serving up a non-vue3 extension @torchiaf )?

Correct, this is still the current Vue2 Harvester UI.

**Comment by gaktive** [comment]
In light of some infrastructure upgrades, we need to push this out until the Harvester move is complete.

For now, I'm pushing this to 2.11.0 but this will need backports to 2.10.1 & 2.9.5 for December.

**Comment by torchiaf** [comment]
@gaktive QA provided a vgpu machine to test it, ew are working on it.

**Comment by torchiaf** [comment]
We couldn't replicate the bug in Rancher 2.9-latest and 2.10.0 cc @noahgildersleeve 

**Test Result**

1. Create a new cluster and assign 1 vGpu device from the device pool - `NVIDIA_A2-2Q (allocatable: 6)`

    Cluster details - Rancher UI

    ![image (6)](https://github.com/user-attachments/assets/d27fc82d-f59a-4c66-aa84-0ef215407fb3)

    Provisioning VM - Harvester UI

    ![image (7)](https://github.com/user-attachments/assets/f45d4a7d-e3e3-4813-82f0-3bcda8e5b678)

2. Create another cluster, assign 1 vGpu device from the device pool - `NVIDIA_A2-2Q (allocatable: 5)`

    Cluster config - Rancher UI

    ![image (8)](https://github.com/user-attachments/assets/fd6997d4-92b7-4e78-b142-0674389a9a4a)

A new vGpu device can be selected for new clusters and the vGpu counter is correctly up-to-date from 6 -> 5
Confirming that we can close the ticket
