### ISSUE TITLE
Projects/Namespaces: Console error thrown after exiting edit form

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12219]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: Firefox, Chrome

**Describe the bug**
Console error is thrown after exiting Projects/Namespaces edit form.

**To Reproduce**
1. go to local cluster
2. click Projects/Namespace in the side nav menu
3. click ellipsis for any existing project/namespace
4. click Edit Config
5. open console
6. click cancel

**Result**
A console error is thrown after exiting the Projects/Namespaces edit form.

> Error in fetch(): Error: Cannot find resourceFields for Schema rke.cattle.io.rkecontrolplane (schemaDefinitions have not been fetched) 

**Expected Result**
No errors are thrown.

**Screenshots**

https://github.com/user-attachments/assets/0c8d62a4-24c9-4aa2-8b04-978bd6294103

**Additional context**

**Comment by rak-phillip** [comment]
This appears to be related to https://github.com/rancher/dashboard/issues/12073#issuecomment-2406193247

**Comment by yonasberhe23** [comment]
No longer seeing error when cancelling/navigating back to list. Tested in:

- Rancher v2.10-0cddb5f146709bf471b863e6715b0a7538572e74-head
- Dashboard master https://github.com/rancher/dashboard/commit/73bff036c570c2f5e3c66cefc2127a638c36441a
