### ISSUE TITLE
Architecture should be all in lowercase

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12221]
**Setup**
- Rancher version: 2.10-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

The architecture in the tables on the `homepage` and `cluster management` are capitalized. They should be all lowercase.

<img width="2305" alt="Screenshot 2024-10-11 at 11 14 18" src="https://github.com/user-attachments/assets/2d450138-5ae0-4d5e-a06b-639bc0a5b6b7">
<img width="2305" alt="Screenshot 2024-10-11 at 11 14 15" src="https://github.com/user-attachments/assets/6096b8a8-c492-4ee7-9ad2-8cc75ad6ebc1">

**To Reproduce**

- Check cluster list in homepage (architecture col)
- Check cluster list in cluster management (architecture col)

**Result**
- Architecture is capitalized

**Expected Result**

- Achitecture should be all lowercase

**Screenshots**

**Additional context**

**Comment by torchiaf** [comment]
Should we also have `mixed` and `unknown` labels lowercase ?

```
  architecture:
    label:
      unknown: Unknown
      mixed: Mixed
```

**Comment by aalves08** [comment]
I would say that is correct. Let's keep it all lowercase @torchiaf . Thanks 🙏

**Comment by richard-cox** [comment]
@torchiaf should this be 2.10.0?

**Comment by aalves08** [comment]
Hey, probably I got this as `2.10.0` milestone 🤔  ... Did I get the milestone wrong again? I wonder if someone edited the milestones....

**Comment by torchiaf** [comment]
Sorry guys, I merged it without notice the milestone. Do we have to revert it ? @richard-cox

**Comment by richard-cox** [comment]
@torchiaf as long as it's gone through the correct QA process, it can just be moved to 2.10.0. Noticed though it was dev-automate, so should probably be reopened and moved to QA review.

**Comment by rancher-max** [comment]
Validated that the architecture values are lowercase:

<img width="920" alt="image" src="https://github.com/user-attachments/assets/5f1f2157-6cc6-49a9-8f20-f7037e207eec">

<img width="762" alt="image" src="https://github.com/user-attachments/assets/3c5fd88c-4b60-48a1-9b11-6548962034fa">
