### ISSUE TITLE
[SURE-9111] `Clusters Ready` missmatch between Gitrepos and Dashboard pages in Continuous Delivery

### ISSUE THREAD

**Issue by mmartin24** [rancher/dashboard#12232]
SURE-9111

**Setup**
- Rancher version: 2.9.2 and onwards
- Rancher UI Extensions:
- Browser type & version:Brave v1.70.126

**Describe the bug**
Faulty gitrepos show clusters `0/0 Ready` in Gitrepo page while shows `1/1 Ready` in Continuous Delivery Dashboard

![image (5)](https://github.com/user-attachments/assets/244b8e9c-3cad-471f-a724-b31677afafab)

**To Reproduce**
- Install Rancher 2.9.2 or newer
- Deploy faulty gitrepo (ie: set incorrect path)
- Wait until Job Failed error is displayed in Continuous Delivery > Gitrepo page
- Observe how column  `Clusters Ready` displays `0/0` with warning sign.
- Now navigate to Continuous delivery > Dashboard

**Result**
- Observe how faulty messages are correctly displayed on specifc gitrepo but `Clusters Ready` column shows a `1/1` in green with checkmark.

**Expected Result**
`Clusters Ready` column in Continuous Delivery Dashboard page should be in sync with status in gitrepo page.

**Screenshots**

**Additional context**

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-453a0d83bee6d1c00f8120b9bec1aa3fbd594d9a-head`
UI version: `master 3c808b4`

Reproduced this on 2.9.2 and now I validated the totals are now consistent between the CD Dashboard and the GitRepos views.
