### ISSUE TITLE
Vue3: Pods: Unable to set the pod selector type to `Anti-Affinity`

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12241]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: Firefox, Chrome

**Describe the bug**
User is unable to set the pod selector type to `Anti-Affinity` for pod scheduling.
> TypeError: e.$set is not a function

**To Reproduce**
1. go to local cluster
2. click Pods in side navigation
3. open pods create form
4. click Pod tab
5. click Pod Scheduling
6. click Add Pod Selector
7. open Type dropdown
8. select Anti-Affiinity option

**Result**
User is unable to set the pod selector type to `Anti-Affinity`.

**Expected Result**
User is able to set the pod selector type to `Anti-Affinity`.

**Screenshots**

https://github.com/user-attachments/assets/b568df06-c8e5-4939-855b-a636157e95f3

**Additional context**

**Comment by yonasberhe23** [comment]
The issue described in this ticket is resolved (tested in master d0c3c5a), but as mentioned in the PR, the fix goes beyond the scope defined here. Moving to To Test for further manual validation.

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

No longer reproducible. No errors on console. The pod gets created with affinity settings as expected after hitting create.
