### ISSUE TITLE
Remove test files from production builds

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#12244]
Dashboard release builds contain several instances of test files. Running `webpack-bundle-analyzer`, we can find 55 instances of test files in Dashboard's main bundle 

```
release-2.8/js/index.afc4c5df.js 

Count: 55
Total size: 189.73 KB
```

## Additional info

Discovered in 2.10
Confirmed test files are present in 2.8

## Screenshots

![image](https://github.com/user-attachments/assets/1259b63b-3d1a-454e-b7af-555ae91c4b86)

**Comment by yonasberhe23** [comment]
nothing for QA to do here.
