### ISSUE TITLE
Secrets: Error thrown when filtering secret data

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12255]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
Error is thrown when filtering secret data.
> TypeError: a.row.unrepeatedSans is null

**To Reproduce**
1. go to c/local/explorer/secret
2. in the search field filter for 'capi'

**Result**
Error is thrown when filtering secret data.

**Expected Result**
Error is not thrown when filtering secret data.

**Screenshots**
https://github.com/user-attachments/assets/7aafa57b-3378-47be-ab8c-7388af01278b

**Additional context**

**Comment by codyrancher** [comment]
I wanted to note:  this issue doesn't require the user to filter anything on the list page. The page just needs to contain a tls cert with a special format.

**Comment by codyrancher** [comment]
I've also switched this to a `manual-test` since I haven't figured out a repeatable way to reproduce this.

**Comment by yonasberhe23** [comment]
No longer experiencing issue.

Tested in:

- Rancher v2.10-e2d0b42c91253243696d36f09e8e6e23cc6fb0db-head
- Dashboard master https://github.com/rancher/dashboard/commit/3c808b4bd43e53ed132cf258d701b20096656708
