### ISSUE TITLE
Rancher UI New component health checks "Cattle" and "Fleet" fail for standard users with only project membership

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12259]
SURE-9187

**Setup**
- Rancher version: 2.9.2

**Describe the bug**
One of our users reported that in Rancher 2.9.2 in the UI Cluster status/Cluster Dashboard, it appears that some new component health checks were introduced on the cluster landing page in the GUI.

These checks work fine if you are logged in with sufficient access. However, if you are logged in as a standard project member user, it looks like you don't have access to the relevant data that feeds these checks. As a result it looks like they are failing which is a cause for concern for normal Rancher users who don't need to be aware of the state of the Cattle agents or Fleet agents running on the cluster.

![image-2024-10-11-17-52-15-372](https://github.com/user-attachments/assets/1a0c31ef-c1e2-4af4-bab5-34a6b5881ecd)

**To Reproduce**
- Crete a "userA" as Standard user, all default no changes
- Create a new project under the `local` cluster called "new-proj"
- Create a new namespace under the "new-proj" project, called "new-namespace"
- Add "userA" as **project Member** to the "new-proj" project in the `local` cluster
- Login as "userA" in Rancher and go to the `local` cluster `cluster explorer`
- The boxes for `cattle` and `fleet` appear in red and cannot get the status correctly

Actual behavior:
The project member can see a health check that looks like a component is failing

Expected behavior:
The project member should not see the health checks failing if it doesn't concern them.

**Comment by mantis-toboggan-md** [comment]
potential solution from discussion elsewhere:

> we would probably need to check if they can see the specific namespace (i think it's different for local/not local) of the required resource

**Comment by yonasberhe23** [comment]
Users with only project membership no longer see "Cattle" and "Fleet" boxes for downstream or upstream clusters.
Tested in:

- Rancher v2.10-695357ad2fdb58bfce027ecf6ce96e8a4e3ddbab-head
- Dashboard master d5024a1

**2.9**
![Image](https://github.com/user-attachments/assets/ce0ae16e-e826-4dfe-8aed-ef55adcf1743)


**2.10**
![Image](https://github.com/user-attachments/assets/bbf0d894-4f74-4501-872f-0664a38da7d6)
