### ISSUE TITLE
GKE - Unable to provision cluster with extra zones

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#12261]
**Setup**
Rancher - v2.9-99b2583e3370321a922e29a11ac5ff9f845baeb6-head
Dashboard - release-2.9 https://github.com/rancher/dashboard/commit/5b380458da42d2b75cb4dfc6f7634e3a713f11df

**Describe the bug**
User is unable to create zonal cluster with extra zones. Its a regression from 2.8
It seems location field is not including the default selected zone (for eg. us-central-1-c)

**To Reproduce**
- Provision zonal GKE cluster from Rancher UI
- While creating select extra zones

**Screenshots**

![image](https://github.com/user-attachments/assets/51beebfb-caec-442f-8e04-8887be5a245a)

![image](https://github.com/user-attachments/assets/00ae818f-d8d8-4ee6-b516-1d4321a62441)

**Comment by richard-cox** [comment]
@cpinjani no need to put the version in the title, these will all be moved to the latest milestone and a backport issue created if required

**Comment by yonasberhe23** [comment]
Repro'd the issue in 2.9. 
In 2.10, the GKE cluster came up active following the repro steps.

Tested in:

- Rancher v2.10-24040b6dc9ae2fa6a3a49cbe126132c13c2587ba-head
- Dashboard master 78d12f9
