### ISSUE TITLE
Provisioning - Node driver cluster options aren't visible when enabling the ui-sql-cache feature flag

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#12262]
**Setup**
- Rancher version: HA `v2.10-2e82262225844f52c3ef6d8a8f51b870e220ec91-head`
- Rancher UI Extensions: `master 0e5fc09`
- Browser type & version: Chrome

**Describe the bug**

In the Create Cluster section of Cluster Management the node driver options aren't visible when enabling `ui-sql-cache` from the Global settings features flags.

**To Reproduce**

1. Install Rancher
2. Go to Create clusters, note the visible clusters options. Node Drivers are available
3. Navigate to Global Settings and Feature Flags.
4. Enable `ui-sql-cache`, wait for Rancher tor estart
5. Refresh the Browser
6. Navigate to Create Cluster again.

**Result**
The node drivers cluster options aren't visible

**Expected Result**
Node driver cluster options are visible and user can interact with them to create a cluster

**Screenshots**

![Screenshot from 2024-10-15 08-24-12](https://github.com/user-attachments/assets/d987e8c6-9317-4b79-b36a-a8c32e3ec085)

**Comment by richard-cox** [comment]
My bet is missing info in api response is the cause of both 
- https://github.com/rancher/dashboard/issues/12266
- https://github.com/rancher/dashboard/issues/12265

If it relates to dynamic types then also
- https://github.com/rancher/dashboard/issues/12262

**Comment by richard-cox** [comment]
note, list comes from node drivers filtered on state (active)

**Comment by richard-cox** [comment]
Will be fixed when https://github.com/rancher/steve/pull/300 merges (and steve in rancher/rancher is bumped). Will monitor and move to test when so

**Comment by richard-cox** [comment]
Given https://github.com/rancher/rancher/pull/47616, moving to test

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-24040b6dc9ae2fa6a3a49cbe126132c13c2587ba-head`
Dashboard:	`master fa2e6dd`

The node driver provisioning cluster types Menu is now visible while the `ui-sql-cache` global feature is enabled.
