### ISSUE TITLE
Clusters: Detail View: Detail button is unresponsive

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12267]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: Chrome, FF

**Describe the bug**
The `Detail` button is unresponsive.

**To Reproduce**
1. go to cluster management
2. click 'local'
3. click 'Config'
4. click 'Detail'
5. notice 'Detail' button is unresponsive

**Result**
The `Detail` button is unresponsive.

**Expected Result**
The `Detail` button is responsive to click; user lands on details page.

**Screenshots**

https://github.com/user-attachments/assets/bea1dc63-27ef-446c-a228-27adfbb96cb9

**Additional context**

**Comment by gaktive** [comment]
This also happens outside of local clusters and no console errors appeared.

**Comment by rak-phillip** [comment]
This is a regressions introduced by #12237. We will need to revert this change and develop a different approach.

**Comment by yonasberhe23** [comment]
Detail button is responsive. Tested in:

- Rancher v2.10-0cddb5f146709bf471b863e6715b0a7538572e74-head
- Dashboard master https://github.com/rancher/dashboard/commit/73bff036c570c2f5e3c66cefc2127a638c36441a
