### ISSUE TITLE
GKE - Unable to edit cluster zones

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#12260]
**Setup**
Rancher - v2.9-99b2583e3370321a922e29a11ac5ff9f845baeb6-head
Dashboard - release-2.9 https://github.com/rancher/dashboard/commit/5b380458da42d2b75cb4dfc6f7634e3a713f11df

**Describe the bug**
User is unable to edit cluster zones after the cluster is created. Its a regression from 2.8

**To Reproduce**
- Provision zonal GKE cluster from Rancher UI
- Edit cluster and try adding extra zones

**Screenshots**
2.9:

![image](https://github.com/user-attachments/assets/a5fc4a0d-37c0-4dd2-b67b-097e32159062)

2.8:

![image](https://github.com/user-attachments/assets/825e2e10-1273-4e70-a714-407d8de25c03)

**Comment by yonasberhe23** [comment]
Users can successfully edit cluster zones; checkboxes are no longer greyed out.

Tested in:

- Rancher v2.10-24040b6dc9ae2fa6a3a49cbe126132c13c2587ba-head
- Dashboard master 78d12f9
