### ISSUE TITLE
Resources status are always Unknown when Server Side Pagination is enabled HA

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#12265]
**Setup**
- Rancher version: HA `v2.10-2e82262225844f52c3ef6d8a8f51b870e220ec91-head`
- Rancher UI Extensions: `master 4e0aa07`
- Browser type & version:

**Describe the bug**
Clusters, nodes, pods are all displaying `Unknown` state.

**To Reproduce**

- Install HA Rancher
- Enable `ui-sql-cache` from Global Settings
- Enable Server side pagination from Global settings

**Result**

The resources state is always `Unknown`

**Expected Result**

The actual State of Clusters, nodes, pods.

**Screenshots**

![Screenshot from 2024-10-15 10-51-59](https://github.com/user-attachments/assets/7a08a8ab-952e-4773-9643-6fe2df761f58)

![Screenshot from 2024-10-15 10-52-27](https://github.com/user-attachments/assets/5b2f7257-79a9-428a-98df-b2b73d36882b)

**Comment by richard-cox** [comment]
My bet is missing info in api response is the cause of both 
- https://github.com/rancher/dashboard/issues/12266
- https://github.com/rancher/dashboard/issues/12265

If it relates to dynamic types then also
- https://github.com/rancher/dashboard/issues/12262

**Comment by richard-cox** [comment]
requires metadata.state

**Comment by richard-cox** [comment]
Will be fixed when https://github.com/rancher/steve/pull/300 merges (and steve in rancher/rancher is bumped). Will monitor and move to test when so

**Comment by richard-cox** [comment]
Given https://github.com/rancher/rancher/pull/47616, moving to test

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-24040b6dc9ae2fa6a3a49cbe126132c13c2587ba-head`
Dashboard:	`master fa2e6dd`

The resources status is now properly displayed and dynamically changed depending on their status. Tested with a pod and a cluster.
