### ISSUE TITLE
Cluster list web elements disappear, can't delete clusters from UI with ui-sql-cache on

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#12266]
**Setup**
- Rancher version: HA `v2.10-2e82262225844f52c3ef6d8a8f51b870e220ec91-head`
- Rancher UI Extensions: `master 0e5fc09`
- Browser type & version: Chrome

**Describe the bug**

The cluster table/list disappears if I select a cluster, or the browser doesn't show the actions buttons. 

**To Reproduce**

1. Install Rancher
2. Go to Create clusters
3. Create a node driver RKE2 AWS
4. Enable `ui-sql-cache`, wait for Rancher tor restart
5. Refresh the Browser
6. Navigate to Cluster Management - Clusters

**Result**
The action buttons aren't displayed
If I refresh the buttons appear
If I select a cluster from the table everything disapears

**Expected Result**
All action elements are displayed and the user is able to remove a cluster

**Screenshots**

![Screenshot from 2024-10-15 11-48-13](https://github.com/user-attachments/assets/707003e9-5342-467e-8315-096e85908346)
![Screenshot from 2024-10-15 11-48-33](https://github.com/user-attachments/assets/f2fc0b9c-5e5f-474e-bf45-345b955c19d5)
![Screenshot from 2024-10-15 11-48-48](https://github.com/user-attachments/assets/5533e1fa-acf8-467a-92df-d21dd1624738)

** More info **

Multiple messages like this one in the console:
```
TypeError: Cannot read properties of undefined (reading 'name')
    at get canDelete (provisioning.cattle.io.cluster.js:236:45)
    at Reflect.get (<anonymous>)
    at Object.get (reactivity.esm-bundler.js:492:29)
    at get _availableActions (resource-class.js:928:26)
    at get _availableActions (provisioning.cattle.io.cluster.js:91:23)
    at Reflect.get (<anonymous>)
    at Object.get (reactivity.esm-bundler.js:492:29)
    at get availableActions (resource-class.js:842:22)
    at Reflect.get (<anonymous>)
    at Object.get (reactivity.esm-bundler.js:492:29)
```

**Comment by richard-cox** [comment]
My bet is missing info in api response is the cause of both 
- https://github.com/rancher/dashboard/issues/12266
- https://github.com/rancher/dashboard/issues/12265

If it relates to dynamic types then also
https://github.com/rancher/dashboard/issues/12262

**Comment by richard-cox** [comment]
requires stateObj, which is metadata.state

**Comment by richard-cox** [comment]
Will be fixed when https://github.com/rancher/steve/pull/300 merges (and steve in rancher/rancher is bumped). Will monitor and move to test when so

**Comment by richard-cox** [comment]
Given https://github.com/rancher/rancher/pull/47616, moving to test

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-24040b6dc9ae2fa6a3a49cbe126132c13c2587ba-head`
Dashboard:	`master fa2e6dd`

The resources status is now properly displayed and dynamically changed depending on their status. Tested with a pod and a cluster.
