### ISSUE TITLE
Edit Cluster Badge modal validation error

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#12274]
**Setup**
- Rancher version: v2.10
- Browser type & version: Chrome Version 129.0.6668.90

**Describe the bug**
Edit Cluster Badge modal has some validation wrong behaviours related to the colour. 
- The colour field will look disabled no matter if it's on or off. 
- However, a colour can be picked no matter if the field is on or off. 
- The "Apply" button will only be active if `Cluster badge` or `Cluster comment` are active and fulfilled. 

**To Reproduce**
Go to a Cluster dashboard and click the brush button to open the Edit Cluster Badge modal.

**Screenshots**

<img width="709" alt="image" src="https://github.com/user-attachments/assets/ed7dee9e-8284-4b4b-b5a8-b9bfeb0b0956">

<img width="665" alt="image" src="https://github.com/user-attachments/assets/6ce8f586-89f6-4428-be1a-2359a176c449">

<img width="669" alt="image" src="https://github.com/user-attachments/assets/de86b266-b276-4f42-9d8b-c94d2e6707f8">

<img width="656" alt="image" src="https://github.com/user-attachments/assets/1dd6c1ad-7776-4540-b1f0-ee2bc0eeb751">

<img width="646" alt="image" src="https://github.com/user-attachments/assets/1af7bcb9-a62d-42d5-b9a0-142efd53472d">

**Comment by rancher-max** [comment]
Trying to validate in v2.10.0-alpha11, but when I click "Apply", the color does not get updated. The custom badge and cluster comment both update appropriately, so just the color isn't being accepted now. And the form validation itself is working, where they are disabled until the checkboxes are clicked and the Apply is available for any field update.

**Comment by rak-phillip** [comment]
I recently tested this on `head` and was able to update the color without issue. I will need to follow up with a `v2.10.0-alpha11` deployment to confirm that there is no issue, but the fix should be same in both Dashboard `head` and `v2.10.0-alpha11`. 

[Screencast_20241111_200831.webm](https://github.com/user-attachments/assets/4c16e405-f665-4558-b4fb-6ea103bbcdac)

**Comment by rancher-max** [comment]
This is working based on this issue. I've opened https://github.com/rancher/dashboard/issues/12582 to resolve the other issue I saw.
