### ISSUE TITLE
Vue 3: Charts dropdown items can't be unselected 

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#12273]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions: N/A
- Browser type & version: Chrome

**Describe the bug**

Chart dropdown items cannot be unselected

**To Reproduce**

1. Local -> Apps -> Charts
2. Click "All" dropdown
3. Try unselecting any item

**Result**
Nothing happens

**Expected Result**

Clicked item should be unselected

**Screenshots**

https://github.com/user-attachments/assets/e33650dd-66e0-49e5-bfba-b7913a49b452

**Additional context**

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

This isn't reproducible in this version. The dropdown items get unselected and properly filtered from the Charts.
