### ISSUE TITLE
Users and Auth: Unable to add user to project when using third-party auth

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12287]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: FF, Chrome

**Describe the bug**
Unable to add user to project when using third-party auth.
> admission webhook "rancher.cattle.io.projects.management.cattle.io" denied the request: metadata.annotations: Invalid value: "field.cattle.io/creator-principal-name": annotation is immutable

**To Reproduce**
1. enable third-party auth (I used GitHub OAuth)
2. go to cluster dashboard
3. clusters > projects/namespaces
4. add a user to an existing project (I added GitHub user: yonasberhe23 to Default project)
5. click save

**Result**
User is unable to add a user to a project when using third-party auth.
**Expected Result**
User is able to add a user to a project when using third-party auth.

**Screenshots**

https://github.com/user-attachments/assets/1d4cd44b-1280-455d-af4e-ed2532a9b6c3

**Additional context**
I also noticed that the user is unable to remove a project member that was previously added by the admin user to the project.

**Comment by richard-cox** [comment]
Probably related to https://github.com/rancher/dashboard/issues/11852. To expand on error message, norman resource annotation cannot change if they contain `cattle.io`

**Comment by richard-cox** [comment]
Was only applicable to projects not created by the signed in user as the annotation did not change.

Annotation in question is immutable and should only be set on creation of project (rather than edit as well)

**Comment by yonasberhe23** [comment]
User can successfully add a user to a project when using third-party auth.

Tested in:
- Rancher	v2.10-e2d0b42c91253243696d36f09e8e6e23cc6fb0db-head
- Dashboard master 3c808b4
