### ISSUE TITLE
Cluster Overview - Provider type is wrong for non-admin user

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#1228]
rancher:master-head 6a6f13

- as admin, provision a cluster with EC2 
- go to the dashboard, the provider is `Amazon EC2`

![image](https://user-images.githubusercontent.com/6218999/92958755-a8b7c200-f41f-11ea-9fb1-6d139948a3ef.png)

- log in as a non-admin user ( cluster owner, cluster member, project owner, project member, etc.)
- go to the dashboard, the provider is `Custom`

![image](https://user-images.githubusercontent.com/6218999/92958853-d1d85280-f41f-11ea-9dbf-431765125e2e.png)

**Comment by deniseschannon** [comment]
We should convert detecting the cluster provider to use the new function that was implemented instead of what we were previously doing.

**Comment by vincent99** [comment]
Yes, what it's currently doing follows 2.4 and looking for nodePools and such you don't have permission to see in this case.  

Note that you're going to get that it's a "RKE" cluster now and not that it's an "Amazon EC2" cluster.  Unless backend is added to return the node driver used.

**Comment by codyrancher** [comment]
@vincent99 there are times that `cluster.status.provider` is empty. Are you wanting the provider to say `RKE` when that's the case when `cluster.status.provider` is empty?

**Comment by deniseschannon** [comment]
When implementing this, can we make sure to use the translations from clusterType to display the "translated" types from the API to what's readable to make sure it takes care of: https://github.com/rancher/dashboard/issues/1476

**Comment by jiaqiluo** [comment]
this is validated in master-head ec04f78 with the latest UI 

for all roles, the downstream cluster provisioned with EC2 instances show as RKE cluster in the dashboard now. 

![image](https://user-images.githubusercontent.com/6218999/94631993-47e11400-027e-11eb-9163-8e6d90c5e72b.png)
