### ISSUE TITLE
'Normal Human' keyboard icon overlaps user menu

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12290]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: Firefox, Chrome

**Describe the bug**
'Normal Human' keyboard icon overlaps the user menu.

**To Reproduce**
1. go to preferences
2. scroll down to 'YAML Editor Key Mapping' section
3. select Vim/Emacs
4. go to cluster management
5. click ellipsis for any cluster
6. click View Yaml
7. click avatar to open user menu

**Result**
<img width="219" alt="Screenshot 2024-10-17 at 4 23 53 PM" src="https://github.com/user-attachments/assets/26a29085-aa04-4e5e-b4be-54196d092c2d">

**Expected Result**
<img width="243" alt="Screenshot 2024-10-17 at 4 24 15 PM" src="https://github.com/user-attachments/assets/ca3fe47c-9e81-48a1-8131-5e80d061bb62">

**Additional context**

**Comment by momesgin** [comment]
@rak-phillip this is a regression after changing the css `index` from `1` to `5000` on [this PR](https://github.com/rancher/dashboard/pull/12269). I couldn't find any cases that might break the styling by using `1`, but I wanted to double-check with you before raising a PR for that.

**Comment by rak-phillip** [comment]
@momesgin revert it to 1. 5000 doesn't make sense as a value in this case.

**Comment by yonasberhe23** [comment]
Issue resolved. Tested in:

- Rancher v2.10-8decbf6fd040b5b2168430f1e72ccc484d59b6e0-head
- Dashboard master 4e82a4d
