### ISSUE TITLE
Vue3: Edit components can fail to relay errors

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#12298]
Edit components could possibly fail to render error messages on failure. See #11937 for more details on how this error manifests. 

The components identified are:

- [x] shell/edit/management.cattle.io.user.vue
- [x] shell/edit/nodeDriver.vue
- [x] shell/edit/kontainerDriver.vue
- [x] shell/edit/fleet.cattle.io.cluster.vue
- [x] shell/edit/cis.cattle.io.clusterscanbenchmark.vue
- [x] shell/edit/helm.cattle.io.projecthelmchart.vue
- [x] shell/edit/k8s.cni.cncf.io.networkattachmentdefinition.vue
- [x] shell/edit/management.cattle.io.projectroletemplatebinding.vue
- [x] shell/edit/monitoring.coreos.com.route.vue
- [x] shell/edit/constraints.gatekeeper.sh.constraint/index.vue
- [x] shell/edit/logging-flow/index.vue
- [x] shell/edit/monitoring.coreos.com.alertmanagerconfig/index.vue
- [x] shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue
- [x] shell/edit/monitoring.coreos.com.prometheusrule/index.vue
- [x] shell/edit/monitoring.coreos.com.receiver/index.vue
- [x] shell/edit/networking.istio.io.destinationrule/index.vue

## Notes

The following components were reviewed, but not modified:

- shell/edit/fleet.cattle.io.clustergroup.vue
	Already contains `inheritAttrs: false`
- shell/edit/auth/azuread.vue
	Not required - root component wrapped in div
- shell/edit/auth/ldap/index.vue
	Not required - root component wrapped in div
- shell/edit/auth/saml.vue
	Not required - root component wrapped in div
- shell/edit/auth/oidc.vue
	Not required - root component wrapped in div
- shell/edit/auth/googleoauth.vue
	Not required - root component wrapped in div
- shell/edit/auth/github.vue
	Not required - root component wrapped in div
- shell/edit/logging.banzaicloud.io.output/index.vue
	Not required - root component wrapped in div
- shell/edit/provisioning.cattle.io.cluster/import.vue (this one matches pattern... but works without inheritAttrs)
	The component tree for this one is as follows:
  ```
	<resource-detail>
	  <async-component-wrapper>
	    <cru-cluster>
	      <cru-resource>
	        <import>
    ```
	The `shell/edit/provisioning.cattle.io.cluster/index.vue` component already contains `inheritAttrs: false` . `Import.vue` is also rendered by this component, but not as a root-level ancestor; therefore, the fallthrough attributes issue is a non-issue in this case.  

## Original Message

> Looks like this same issue appears in a number of different places (some aren't fixed by inheritAttrs: false,)
>
> ## Standout - These need to be confirmed or fixed in 2.10.0
> - shell/edit/management.cattle.io.user.vue
> - shell/edit/auth/azuread.vue
> - shell/edit/auth/ldap/index.vue
> - shell/edit/auth/saml.vue
> - shell/edit/auth/oidc.vue
> - shell/edit/auth/googleoauth.vue
> - shell/edit/auth/github.vue
> - shell/edit/nodeDriver.vue
> - shell/edit/kontainerDriver.vue
> 
> ## Debatable - These need to be confirmed but not maybe fixed in 2.10.0
> - shell/edit/fleet.cattle.io.cluster.vue
> - shell/edit/fleet.cattle.io.clustergroup.vue
> 
> ## Others - These need to be confirmed and fixed at some point
> - shell/edit/cis.cattle.io.clusterscanbenchmark.vue
> - shell/edit/helm.cattle.io.projecthelmchart.vue
> - shell/edit/k8s.cni.cncf.io.networkattachmentdefinition.vue
> - shell/edit/management.cattle.io.projectroletemplatebinding.vue
> - shell/edit/monitoring.coreos.com.route.vue
> - shell/edit/constraints.gatekeeper.sh.constraint/index.vue
> - shell/edit/logging-flow/index.vue
> - shell/edit/logging.banzaicloud.io.output/index.vue
> - shell/edit/monitoring.coreos.com.alertmanagerconfig/index.vue
> - shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue
> - shell/edit/monitoring.coreos.com.prometheusrule/index.vue
> - shell/edit/monitoring.coreos.com.receiver/index.vue
> - shell/edit/networking.istio.io.destinationrule/index.vue
> 
> ## Of Note
> - shell/edit/provisioning.cattle.io.cluster/import.vue (this one matches pattern... but works without inheritAttrs)
> - The hack was already put in a number of affected places by https://github.com/rancher/dashboard/pull/11803
>
> @rak-phillip i'll leave it up to you on how to split those up, and where it leaves this PR

_Originally posted by @richard-cox in https://github.com/rancher/dashboard/issues/11956#issuecomment-2422936450_

**Comment by yonasberhe23** [comment]
Tested in:

- Rancher v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head
- Dashboard master 78df731

Errors display as expected in create/edit mode, yaml editor included in testing.
