### ISSUE TITLE
[Monitoring / Alerting V2 UI] Minor fixes

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1230]
### Modify titles of Chart Deployment Sections

- [x] Currently the titles of the are `Alerting`, `Prometheus Config`, and `Grafana Config`. We should modify this to the following order / naming:

- `Configure Prometheus`
- `Configure Alertmanager`
- `Configure Grafana`

### Cluster RBAC options

- [x] Modifying the value of `Aggregate to Default Kubernetes Roles` should be disabled if `Create Default Monitoring Cluster Roles` is false since it's no longer an applicable option.

### Lack of support for Docker / Minikube

- [x] Docker and Minikube are not currently supported, they should be aggregated into the `Other` category of Cluster Types.

### Extra Components for Managed Clusters

- [x] Managed Clusters should not deploy `kube-controller-manager`, `kube-etcd`, `kube-scheduler`, and `kube-proxy` by default. Users should still be able to optionally deploy it as part of the Advanced Configuration though. Here is a screenshot of the current diff in the UI where the first three components are still being deployed:

![Screen Shot 2020-09-11 at 12 22 16 PM](https://user-images.githubusercontent.com/13127443/92964728-701ce600-f429-11ea-9205-cae07beb7539.png)

The defaults for the following cluster types need to be modified for this change:
- Azure AKS
- Amazon EKS
- Google GKE

### ~`kubeProxy` needs to be enabled for `Other`~

~When the cluster type is `Other`, we need to set `kubeProxy.enabled=true`.~

### Exporter settings for `Other` clusters

- [x] When the cluster type is `Other` (including `Minikube` and `Docker`), we need to set `kubeControllerManager.enabled=false`, `kubeScheduler.enabled=false`, `kubeEtcd.enabled=false`, and `kubeProxy.enabled=false` by default.

This is a deviation from the original Basic Configuration spec based on discussion cited in https://github.com/rancher/dashboard/issues/908#issuecomment-692272565.

### Exporter settings for Managed Clusters

- [x] When the cluster type is `Azure AKS`, `Amazon EKS`, or `Google GKE`, we need to set `kubeControllerManager.enabled=false`, `kubeScheduler.enabled=false`, `kubeEtcd.enabled=false`, and `kubeProxy.enabled=false` by default based on the spec in https://github.com/rancher/dashboard/issues/908. We also need to set `prometheusOperator.hostNetwork=true`.

- [x] Specifically for `Google GKE`, we also need to set `coreDns.enabled=false` and `kubeDns.enabled=true` by default since the default GKE cluster still uses `kubeDns`.

### k3s clusters need a higher memory limit

Context: https://github.com/rancher/rancher/issues/28787#issuecomment-693611821

- [x] We need to set the default `prometheus.prometheusSpec.resources.limits.memory=2500Mi` and `prometheus.prometheusSpec.resources.requests.memory=1750Mi` only when the Cluster Type is detected to be k3s.

- [x] Users should be able to override this to set higher limits still.

### nit: Resource Limits

- [x] Could we introduce a separate subsection for `Resource Limits` for `Requested CPU`, `Requested Memory`, `CPU Limit`, and `Memory Limit`? Similar to the subheading on `Config Secret` or `Persistent Storage for Grafana` at the moment.

Would also be nicer if you could have this in a tabular format i.e.

x| Request | Limit |
|---|---|---|
CPU | 750m | 1000m |
Memory | 750Mi | 1500Mi |

#### Selector uses the wrong spec
_EDIT: Wes_ This was replaced with the MatchExpressions component in the UI which achieves both match expressions and match labels given the context of the operator.
- [x] The Selector UI here needs to match the `LabelSelector` spec given in https://github.com/rancher/dashboard/issues/803 with `matchLabels` and `matchExpression`, not key-value pairs. Currently this functionality seems broken since you can't submit a key-value pair for the selector's values either.

This format for `LabelSelectors` comes directly from the Persistent Volume spec in https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims.

#### Remove volumeName

- [x] Not sure if it would be used by enough users in a default configuration.

#### Disable Storage Class Name if no storage classes exist

- [x] If no storage classes exist, users should not be able to modify this option. Optionally, we could also just hide it in this case.

#### Access Modes and Volume Mode

- [x] Set the default Volume Mode to `Filesystem` to prevent users from submitting a PVC template without any volume mode set.

- [x] Set the default Access Mode to `["ReadWriteOnce"]`. Also, Access Mode should be Access Modes and allow you to submit a non-null list of the three options.

#### Disable `Enable With Existing PVC`

- [x] If no PVCs exist that can be selected with `Use Existing Claim`, this option should be disabled by default. 

#### Drop `Use Subpath` fields entirely

- [x] It's an advanced feature, so users can always set it if they want to at a later point

#### Access mode should be a list

See comments for Prometheus Persistent Storage

#### Ordering of fields for `Enable with PVC Template` and `Enable with StatefulSet Template` should be same as Prometheus

- [x] Size should be brought to the top

### Naming of Alertmanager

- [x] AlertManager should be changed to Alertmanager throughout the UI.

### Help Text

~Should be different based on which option is selected.~
_EDIT Wes_: Without a massive refactor of the component that creates this we can't do it on each option. Instead this info will be present in a single tooltip.

- [x] The giant info box should be removed in favor of an (i) hover on top of each of the options:

```
Create default config: A Secret containing your Alertmanager Config will be created in the `cattle-monitoring-system` namespace on deploying this chart under the name `alertmanager-rancher-monitoring-alertmanager`. By default, this Secret will never be modified on an uninstall or upgrade of this chart.

Once you have deployed this chart, you should edit the Secret via the UI in order to add your custom notification configurations that will be used by Alertmanager to send alerts.


Choose an existing config secret: You must specify a Secret that exists in the `cattle-monitoring-system` namespace. If the namespace does not exist, you will not be able to select an existing secret.
```

### Default Config Secret option

- [x] Should be `Create a default config`, not `Choose and existing config secret`.

### `useExistingSecret` not modified

- [x] If `Create default config` is enabled, `alertmanager.alertmanagerSpec.useExistingSecret` should be set to false. 

- [x] If `Choose existing config secret` is enabled, `alertmanager.alertmanagerSpec.useExistingSecret` should be set to true.

<img width="952" alt="Screen Shot 2020-09-16 at 2 49 59 PM" src="https://user-images.githubusercontent.com/13127443/93396215-26b70700-f82c-11ea-957e-07849374da94.png">

#### `configSecret`'s contents should be erased if `Create default config`

- [x] If you switch the option to `Choose existing config secret`, select a secret in the `cattle-monitoring-system` namespace, and switch back to `Create default config`, `alertmanager.alertmanagerSpec.configSecret` should be set to the default option of `""`.

### Additional Secrets have limited namespace

- [x] The `Additional Secrets` of the Alerting configuration can only select secrets from the `cattle-monitoring-system` namespace just like the `Alertmanager Secret` option

### UI Bug with adding additional secrets
See https://github.com/rancher/dashboard/issues/1488
![Screen Shot 2020-09-11 at 1 17 52 PM](https://user-images.githubusercontent.com/13127443/92969119-364fdd80-f431-11ea-80c4-b0e346ccd933.png)

### Create default config should be selected if there are no secrets that match criteria
See https://github.com/rancher/dashboard/issues/1489
<img width="1569" alt="screen_shot_2020-09-24_at_11 32 39_am" src="https://user-images.githubusercontent.com/13127443/94185494-30f38980-fe5a-11ea-86f0-ecfad6b65810.png">

### Use existing secret should automatically be selected if the default secret already exists in the namespace

- [x] If we find that the `cattle-monitoring-system` namespace exists and `alertmanager-rancher-monitoring-alertmanager` exists in that namespace, the default should be `Use existing secret` -> `alertmanager-rancher-monitoring-alertmanager` instead of `Use default config` since we know the config already exists and the deployment will fail if we try to create a secret that already exists.

**Comment by aiyengar2** [comment]
@cloudnautique I've updated the spec of this ticket update the exporter settings for Managed clusters; this should address the issue you saw relating to `No Data` Grafana dashboards showing up on an EKS cluster on deploying Monitoring V2.

#### Note for QA:
Once this ticket is merged in, we need to check that deploying a managed cluster only deploys Dashboards that contain data.

**Comment by maggieliu** [comment]
Related to : https://github.com/rancher/dashboard/issues/1015

**Comment by westlywright** [comment]
Ive added checkboxes and checked off what I've done. The PR is in review. A couple issues focused on styles were broken into new issues.

**Comment by jiaqiluo** [comment]
This ticket is validated in 2ae933e mater-head with the latest UI,

We still have the following items need to fix:

1. For `Disable Storage Class Name if no storage classes exist`, the Storage Class Name is NOT hidden when there is no storage class in the cluster.
<img width="1365" alt="Screen Shot 2020-09-30 at 11 52 28 AM" src="https://user-images.githubusercontent.com/6218999/94728714-7fe76600-0315-11eb-99b1-529592ffa8ba.png">

2. (Continue) It is better to move the `Size` field to the beginning of the next line, not in the same line as the checkbox?

3. All checkpoints under the `Alerting -> Default Config Secret option` are not validated at this moment and waiting for this fix https://github.com/rancher/dashboard/issues/1489

**Comment by jiaqiluo** [comment]
> This ticket is validated in 2ae933e mater-head with the latest UI,
> 
> We still have the following items need to fix:
> 
> 1. For `Disable Storage Class Name if no storage classes exist`, the Storage Class Name is NOT hidden when there is no storage class in the cluster.
> 
> <img alt="Screen Shot 2020-09-30 at 11 52 28 AM" width="1365" src="https://user-images.githubusercontent.com/6218999/94728714-7fe76600-0315-11eb-99b1-529592ffa8ba.png">
> 
> 2. (Continue) It is better to move the `Size` field to the beginning of the next line, not in the same line as the checkbox.
> 3. All checks after the `Alerting -> Default Config Secret option` are not validated at this moment and waiting for this fix #1489


Item 1 and 2 are validated in the latest master-head with the latest UI

when there is no storage class in the cluster 
<img width="1364" alt="Screen Shot 2020-09-30 at 4 07 05 PM" src="https://user-images.githubusercontent.com/6218999/94749010-969eb480-0337-11eb-928c-c17422831b0c.png">

and when there is a storage class in the cluster 
<img width="1365" alt="Screen Shot 2020-09-30 at 4 10 13 PM" src="https://user-images.githubusercontent.com/6218999/94749028-a4543a00-0337-11eb-81d7-1424e4177b4b.png">


item 3 is still pending

**Comment by jiaqiluo** [comment]
``` If you switch the option to Choose existing config secret, select a secret in the cattle-monitoring-system namespace, and switch back to Create default config, alertmanager.alertmanagerSpec.configSecret should be set to the default option of "".```

but in master-head, I don’t see the alertmanager.alertmanagerSpec.configSecret being set to “”

<img width="701" alt="Screen Shot 2020-10-01 at 11 37 58 AM" src="https://user-images.githubusercontent.com/6218999/94850233-7f190780-03db-11eb-840b-c65409424513.png">

**Comment by jiaqiluo** [comment]
> ` If you switch the option to Choose existing config secret, select a secret in the cattle-monitoring-system namespace, and switch back to Create default config, alertmanager.alertmanagerSpec.configSecret should be set to the default option of "".`
> 
> but in master-head, I don’t see the alertmanager.alertmanagerSpec.configSecret being set to “”
> 
> <img alt="Screen Shot 2020-10-01 at 11 37 58 AM" width="701" src="https://user-images.githubusercontent.com/6218999/94850233-7f190780-03db-11eb-840b-c65409424513.png">


This is fixed in the latest UI

![image](https://user-images.githubusercontent.com/6218999/94866888-0030c880-03f5-11eb-89b9-ebf5c4e51800.png)
