### ISSUE TITLE
Use complete source maps for Vue

### ISSUE THREAD

**Issue by moio** [rancher/dashboard#12306]
**Is your feature request related to a problem? Please describe.**

Debugging and especially profiling dashboard production builds is difficult because original function names are not available.

Function names are not available because source maps are incorrect. Source maps are incorrect because Vue function names are taken from the minified version of the library (`vue.min.js`), where they are already shortened and therefore not easily readable.

Eg.

![image](https://github.com/user-attachments/assets/1bdc8837-e27e-4819-a4ea-fcfd585308f0)

**Describe the solution you'd like**

Fully functional source maps, including Vue. Eg.

![image](https://github.com/user-attachments/assets/d33ecb2b-5805-4dd2-b003-37dba292fd92)

**Describe alternatives you've considered**

No alternatives considered.

**Additional context**

This is expected to be particularly useful to investigate at-scale scenarios.

**Comment by rak-phillip** [comment]
This should be a non-issue for 2.11, as we're not using a minified version of Vue anymore

https://github.com/rancher/dashboard/blob/54f24cf9c93f32ea5cab094629dc3b60423e8f8c/shell/vue.config.js#L542

**Comment by richard-cox** [comment]
@rak-phillip Good point! forgot line changed. Also would apply to 2.10.1.
