### ISSUE TITLE
Users and Auth: Error message not displayed on screen when password does not meet min requirement

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12311]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: FF, Chrome

**Describe the bug**
Error message not displayed on screen when password does not meet min requirement.

**To Reproduce**
1. go to users and auth > users
2. click create
3. input username
4. input short pw
5. click create

**Result**
No error message displays.

**Expected Result**
<img width="1728" alt="Screenshot 2024-10-21 at 10 52 55 AM" src="https://github.com/user-attachments/assets/84b9954b-ca33-44e0-928c-70099d004523">

**Screenshots**

**Additional context**

**Comment by momesgin** [comment]
I could also confirm that this is fixed, local env on master branch.

**Comment by yonasberhe23** [comment]
I'll retest once the build is published. thank you!

**Comment by yonasberhe23** [comment]
Issue resolved. Tested in: 

- Rancher v2.10-f2de3bdd8d8e76892fd3534c1168973ad8710973-head
- Dashboard master a1152d7
