### ISSUE TITLE
Add missing dependencies required in @rancher/shell for external cases, removed with migration

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12318]
**Is your feature request related to a problem? Please describe.**

After the migration to Vue3, some libraries are required for external cases when providing the files as `@rancher/shell` library, e.g. for extensions. This is a known consequence for removing `nuxt` dependency, since we were importing/using these libraries without define them in the project or shell library.

**Describe the solution you'd like**
Add these libraries to `./shell/package.json`

```
    "cache-loader": "^4.1.0",
    "color": "4.2.3",
    "ip": "2.0.1",
    "node-polyfill-webpack-plugin": "^3.0.0"
```
 
**Describe alternatives you've considered**
None.

**Additional context**

These libraries were added in the example as a requirement to make them work, but as @aalves08 pointed out, they should be already included in the `@rancher/shell` library and avoid adding in each extension.

Example to avoid, done to make it work: https://github.com/rancher/ui-plugin-examples/blob/main/pkg/clock/package.json#L20C44-L24C45

**Comment by cnotv** [comment]
Sorry I messed up with the issues, let's keep this one https://github.com/rancher/dashboard/issues/12320
