### ISSUE TITLE
Virtualization Management, support for Harvester extension

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#12322]
**Is your feature request related to a problem? Please describe.**

The Virtualization Management tab is implemented as a built-in plugin that gives access to the users to the Harvester clusters list.

1.
![image](https://github.com/user-attachments/assets/0a13491d-8a24-4640-9739-4b163917cfbb)

After importing a new Harvester cluster, the user can click on the cluster name in the clusters list and Rancher reaches out to the Harvester server, loads the Harvester UI code from that server and presents it to the user.

2.
![image](https://github.com/user-attachments/assets/0c90f97e-c84a-4e58-9e21-ccba55f6bc15)

Starting from Rancher `2.10`, Harvester will be available as a standard Rancher extension that can be installed from its extension registry although the Virtualization Management page is still built-in.

As a result of above, **users will have to manually install the new extension** to have access to the Harvester clusters.

**Describe the solution you'd like**

We need to inform the users to add the Harvester extension registry and install the new extension.

- Harvester extension is not installed:
  1. Display view 1. even if the cluster list is not empty.
  2. Keep the current presentation layout.
  3. Disable or remove the 'Import Existing' button if the Harvester extension is not installed.
  4. Remove the empty list label.
  5. Add guidelines on how to install the Harvester extension in case of the Harvester extension is not installed.
      - If the user doesn't have permission to install extensions, add guidelines to request the extension to the admin.

- Harvester extension is installed:
  1. Display view 1. if the cluster's list is empty.
  2. 'Import Existing' button is enabled.

**Describe alternatives you've considered**

Changes described here are the minimum step to integrate the Harvester extension.
We will need to define a more efficient workflow to install and use the extension.

**Additional context**

**Comment by aalves08** [comment]
just added the label `area/extensions` and I subscribed to keep track of this as well 🙏

**Comment by gaktive** [comment]
@torchiaf we're past feature complete for 2.10.0 but does this need to get in for that version? @nwmac do we need to add this to our grooming session tomorrow?

**Comment by nwmac** [comment]
@gaktive we need to do this, so yes, we need to discuss
