### ISSUE TITLE
Fix `project-namespace.spec.ts` e2e tests failing in 2.10

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#12327]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

After updating the e2e tests env to point to the latest backend(2.10) an e2e test related to projects got broken.

Test name:
`sets the creator principal id annotation when creating a project and using third-party auth`

Path:
`cypress/e2e/tests/pages/explorer2/project-namespace.spec.ts`

Error:
```

{
    "baseType": "error",
    "code": "BadRequest",
    "message": "admission webhook \"rancher.cattle.io.projects.management.cattle.io\" denied the request: metadata.annotations: Invalid value: \"field.cattle.io/creator-principal-name\": creator user user-44b5h doesn't have principal github://1234567890",
    "status": 400,
    "type": "error"
}

```

**Additional context**

[The PR](https://github.com/rancher/dashboard/pull/12310) to update e2e test env to point to the latest backend.

**Comment by izaac** [comment]
Looks good to me. 👍🏽
