### ISSUE TITLE
Update EULA link

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#12334]
Should link to:
https://www.suse.com/licensing/eula/download/suse_end_user_license_agreement_june_2024.pdf

instead of:
https://rancher.com/eula

**Comment by rancher-max** [comment]
### Validated using rancher `head` build

Link correctly points to: https://www.suse.com/licensing/eula/download/suse_end_user_license_agreement_june_2024.pdf and opens the page correctly in a new tab
<img width="614" alt="image" src="https://github.com/user-attachments/assets/d02e8fdb-4b92-4ac8-98d1-c6c6c1b8d618">
