### ISSUE TITLE
[BUG]Edit Config on local EKS cluster 

### ISSUE THREAD

**Issue by rolfbartels** [rancher/dashboard#12339]
**Rancher Server Setup**
- Rancher version: 2.92
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details: Rancher Cert from Cert Manager

**Information about the Cluster**
- Kubernetes version: 1.30
- Cluster Type (Local/Downstream): local
* Hosted = EKS

**User Information**
- What is the role of the user logged in? Admin/Cluster Owner

**Describe the bug**
On a new install or old install on Rancher 2.9.2 I want to add labels to the local cluster.
When I edit the config I am prompted that atleast 1 node group must be configured.
I insert the missing field (Cluster Name, Cloud Creds (Same Creds use to eksctl create), add a node group and try and save.

I am presented on and error
{"data":""}

**To Reproduce**
Cluster Management
Select the ellipsis for local cluster
Edit Config
Enter in required details
Save 

**Result**
{"data":""}
**Expected Result**
Cluster Config saves

**Screenshots**
![image](https://github.com/user-attachments/assets/50141fb6-e1c3-4a89-a7de-32bfce4cf08b)

**Additional context**

**Comment by rak-phillip** [comment]
I can repro this issue in v2.9.3. The form behaves exactly as described when editing the local cluster for Rancher hosted on EKS

**Comment by rak-phillip** [comment]
Following up with some information based on OOB discussions. We've identified that the behavior described in the issue is related to `eksStatus.upstreamSpec` evaluating to `null` and `eksConfig` is `undefined`. This has been reported to be expected behavior:

> on local cluster where Rancher is running, and even if it was deployed on EKS eksStatus should be:
>
>  ```
>  eksStatus:
>    generatedNodeRole: ''
>    managedLaunchTemplateID: ''
>    managedLaunchTemplateVersions: null
>    privateRequiresTunnel: null
>    securityGroups: null
>    subnets: null
>    upstreamSpec: null
>    virtualNetwork: ''
>  ```
>
> it is because local cluster is not provisioned or managed by eks-operator

Based on the information provided, I think that we will need to define the edge-cases for working with local clusters and handle them accordingly so that the form behaves as expected for this use case.

**Comment by izaac** [comment]
Rancher version: `v2.11-215cf156eb44fd6b392ef5d65d38e8dcafeb2734-head`
UI version: `release-2.10 d5b785b`
EKS cluster version: `v1.30.7-eks-56e63d8`

This is meeting the expectation. No errors are observed when adding new labels or updating the cluster members.
