### ISSUE TITLE
Fix `namespace-picker.spec.ts` e2e test failing in 2.10

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#12338]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

After updating our e2e test env pointing to the latest backend(2.10) a test from `namespace-picker.spec.ts` fails.

Test case:
`newly created project/namespace appears in namespace picker`

Path:
`cypress/e2e/tests/pages/explorer2/namespace-picker.spec.ts`

**Additional context**

[The PR](https://github.com/rancher/dashboard/pull/12310) to update e2e test env to point to the latest backend.

**Comment by gaktive** [comment]
Blocked on #12406 so once that's resolved, let's see how this looks.

**Comment by yonasberhe23** [comment]
namespace picker tests are consistently running without issue in GA and Jenkins.
