### ISSUE TITLE
Workload health column to scale up/down is missing

### ISSUE THREAD

**Issue by gulecroc** [rancher/dashboard#12344]
**Setup**
- Rancher version: 2.9.2
- Rancher UI Extensions: -
- Browser type & version: Chrome 130.0.6723.59

**Describe the bug**
After upgrade Rancher 2.8.3 to 2.9.2, when I go to workload, I don't see anymore the column Health to scale up/down the workload.

I feel quite embarrassed because I'm quite sure I use it the day after the upgrade (2 days ago), but this morning I can't see it.

**To Reproduce**
On the left panel, go to Workload, then Deployments or StatefulSets.

You should see the Health column on the right used to scale up/down the workload.

**Result**
Rancher 2.8.3 :

![image](https://github.com/user-attachments/assets/f8465fba-7f34-4944-9783-3ee142f03d70)

Rancher 2.9.2 :

![image](https://github.com/user-attachments/assets/cbffc56f-6bc9-4e99-aaf5-7f4d5911974a)

**Expected Result**

**Screenshots**

**Additional context**

**Comment by gulecroc** [comment]
I don't see the Health column because my colleague enabled the feature `ui-sql-cache` + select `enable server-side pagination`.

Do you know if the Health column will be added with this feature ?

Thank you

**Comment by richard-cox** [comment]
Thanks for updating.

The server-side pagination feature is in flux and there may be many dragons until it settles down (and why it is not recommended for production).

The `Health` column containing the workload's pods is a scaling issue that we hope to resolve but may not be in the first release where everything is on by default
