### ISSUE TITLE
Logging: Flows: Creation: Unable to specify container names

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12342]
**Setup**
- Rancher version: v2.10
- Rancher UI Extensions:
- Browser type & version: FF, Chrome

**Describe the bug**
User is unable to specify container names when creating a Flow. After entering text for the 'Exclude specific container names' field, the text becomes undefined/null. Also, an error is thrown when attempting to create a Flow with this invalid entry which makes this part of the feature unusable outside of using the default value.
> Flow.logging.banzaicloud.io "test1" is invalid: spec.match[0].select.container_names[0]: Invalid value: "null": spec.match[0].select.container_names[0] in body must be of type string: "null"

**To Reproduce**
1. install Logging (Cluster Explorer --> Apps --> Charts --> Logging --> Install)
2. Cluster Explorer --> Logging --> Flow --> Create --> Matches tab
3. press either 'Add Include Rule' or 'Add Exclude Rule'
4. for 'Exclude specific container names' type some value
5. hit enter

**Result**

https://github.com/user-attachments/assets/e3e32673-2af9-41ce-99a0-92e3a850f1d5

**Expected Result**

https://github.com/user-attachments/assets/e8581d62-f872-4fbf-82a2-73e7fb875bec

**Screenshots**

**Additional context**

**Comment by yonasberhe23** [comment]
Found while testing https://github.com/rancher/dashboard/issues/11933

**Comment by gaktive** [comment]
@yonasberhe23 is this happening in 2.9.x at all? This sounds like a regression but I don't know how much activity we have with Flows.

**Comment by momesgin** [comment]
@gaktive @yonasberhe23 I think there's something wrong about this input field on both 2.9 and 2.10. In 2.9 when you type a random container name we allow to select it by either clicking on it from the upward dropdown or by hitting the enter key:

<img width="1109" alt="image" src="https://github.com/user-attachments/assets/5b99e464-d62f-47c8-9502-ca5f5f40204d">

in 2.10 we show "No matching option" on the upward dropdown, but we still allow to add an empty item when you press the enter key:

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/02749050-4dc4-406d-8d2a-10da6b5ac940">

I honestly don't know what the actual desired behaviour is here.

**Comment by gaktive** [comment]
@momesgin will talk with @yonasberhe23 about behaviours but this may have to a release note for 2.10.0 with a workaround of editing the YAML directly.

**Comment by yonasberhe23** [comment]
User is unable to input container names when creating a Flow.

Tested in:

- Rancher v2.10-212d8b6e92992235d791d8f2aaea8436ab4f6b77-head
- Dashboard master c321e42
