### ISSUE TITLE
Remove Global DNS from UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#12343]
Internal reference: SURE-9237

In support of Mapps and their removal of the other Catalog v1, they're taking out code from their side. UI needs to remove links to it.

Support was removed in 2.10 via https://github.com/rancher/rancher/pull/47590

**Comment by yonasberhe23** [comment]
Global config no longer displays in UI when `legacy` feature flag is enabled.

Tested in:

- Rancher v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head
- Dashboard master 8662b03
