### ISSUE TITLE
Harvester shell integration

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#12347]
**Is your feature request related to a problem? Please describe.**

We want to make the `shell` package compatible with the Harvester ui extension: https://github.com/harvester/harvester-ui-extension

**Comment by gaktive** [comment]
Moving out of 2.10.0 for triage purposes and we're shipping soon. Let me know if 2.11.0 is more appropriate here.

**Comment by rancher-max** [comment]
Tested as part of PRs and explicit to Harvester. Should be okay to close without explicit manual QA validation.
