### ISSUE TITLE
Design Issue

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1235]
- [x] Header doesn't extend all the way to the edge: 

<img width="410" alt="Screen Shot 2020-09-11 at 9 11 40 PM" src="https://user-images.githubusercontent.com/11410997/92986992-789a0e80-f473-11ea-9575-453b13263d3c.png">

**Comment by aaronRancher** [comment]
The fix is verified with Rancher server `rancher\rancher:master-head` `version 59936f7`

Message header extends to the edge:
![Screen Shot 2020-09-16 at 12 51 21 PM](https://user-images.githubusercontent.com/57409052/93385651-63c6cd80-f81b-11ea-828d-5a73fd54e361.png)
