### ISSUE TITLE
Add k8s 1.31 to UI

### ISSUE THREAD

**Issue by Sahota1225** [rancher/dashboard#12361]
Update https://github.com/rancher/ui/blame/master/lib/shared/addon/utils/amazon.js#L1446 
add 1.31 and remove 1.27 from UI

**Comment by gaktive** [comment]
@mantis-toboggan-md does https://github.com/rancher/dashboard/pull/12309 take care of this already? In the past, this was in Ember based on the older approach but this was ported to Vue as of 2.9.0.

**Comment by mantis-toboggan-md** [comment]
@gaktive yes, #12309 covers this

**Comment by yonasberhe23** [comment]
Tested in:

- Rancher v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head
- Dashboard master 8662b03

1.31 added and 1.27 is remove from UI
![Image](https://github.com/user-attachments/assets/8547a1c2-5be1-4a0f-a195-c6eddbcbebc2)
