### ISSUE TITLE
Monitoring design changes

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#1236]
<img width="585" alt="Screen Shot 2020-09-11 at 11 21 59 AM" src="https://user-images.githubusercontent.com/3013118/92988834-ec441780-f483-11ea-9e06-cb04103f7b36.png">

**Comment by deniseschannon** [comment]
Features that have this component/card after you activate/turn on the feature:

Monitoring Overview 
Istio Overview
Longhorn Overview (still WIP)

**Comment by lvuch** [comment]
note to self 
<img width="504" alt="Screen Shot 2020-09-24 at 3 41 49 PM" src="https://user-images.githubusercontent.com/3013118/94207446-7e80ee00-fe7c-11ea-85f3-5c2c57937a7c.png">

**Comment by lvuch** [comment]
as of right now I can't get istio to install

**Comment by jiaqiluo** [comment]
This is validated in master-head ec04f7878 with the latest UI

note that the panels for CRDs are removed in the new design https://github.com/rancher/dashboard/issues/1260

<img width="935" alt="Screen Shot 2020-09-28 at 10 53 42 AM" src="https://user-images.githubusercontent.com/6218999/94468232-f4d16900-0178-11eb-88d7-dab9494e595f.png">
