### ISSUE TITLE
Checkbox in RKE2 create/edit cluster config form is not clickable

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#12368]
**Setup**
- Rancher version: v2.10-f1b486de4051becd030fc6f4f98785285548a910-head
- Browser type & version: Chrome Version 130.0.6723.59 (Official Build) (arm64)

**Describe the bug**
Checkbox "Raise error if kernel parameters are different than expected kubelet defaults" in RKE2 create/edit cluster config form is not clickable

**To Reproduce**
1- From the side menu bar in the UI, go to Clusters Management
2- Hit Create
3- Select RKE2
4- In the Cluster Config session of the form, go to the Advanced tab
5- Try to select the checkbox "Raise error if kernel parameters are different than expected kubelet defaults" at the very bottom 

**Result**
Checkbox in RKE2 create/edit cluster config form is not clickable and consequently cannot be enabled

**Expected Result**
User should be able to select/unselect the checkbox. The checkbox should enable the feature when selected and disable it when unselected.

**Screenshots**

https://github.com/user-attachments/assets/499d68be-6d83-4e16-a756-1984729537d1

**Comment by gaktive** [comment]
This worked in 2.9.x so this is a regression.

**Comment by aalves08** [comment]
picking this one up. Lost rancher org access. Cannot assign to me

**Comment by gaktive** [comment]
Based on code freeze coming up in 2 days, @jordojordo can you take a look at this today if you have time?

**Comment by yonasberhe23** [comment]
Tested in: 
Rancher v2.10-e615207c8cd924c092b55a9301e7378878706d19-head
Dashboard master 190f486

Checkbox is clickable.
