### ISSUE TITLE
Remove Global Catalogs (legacy v1) from the UI

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#12364]
Internal reference: SURE-4858

In support of Mapps and their removal Catalog v1, they're taking out code from their side. UI needs to remove links for the global catalogs.

**Comment by yonasberhe23** [comment]
Global configuration option no longer displays in UI when `legacy` feature flag is enabled.

Tested in:

- Rancher v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head
- Dashboard master 8662b03
