### ISSUE TITLE
Extensions banner for Rancher Prime is broken (not being displayed)

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12376]
**Setup**
- Rancher version: 2.9.3 (prime)
- Rancher UI Extensions: master/head
- Browser type & version: any

**Describe the bug**

The Banner to warn users that they can add new repos for extensions `There are new extensions repositories available. To enable these repositories, click the button on the right.`  when entering the main extensions screen is **NOT** being displayed.

The culprit is this unmet condition https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/uiplugins/index.vue#L157 and the root cause is https://github.com/rancher/rancher/pull/45894 .

We should also check if these other settings https://github.com/rancher/rancher/pull/45894 are broken on the UI side as well and fix them.

**To Reproduce**

Provision a Rancher Prime 2.9.3 system and enter the main extensions screen

**Result**
Banner not being displayed on the top of the page

**Expected Result**

Banner should be displayed on the top of the page

**Screenshots**

https://github.com/user-attachments/assets/e1d3489a-4656-442d-a261-c44aa36e2c46

**Additional context**

**Comment by rak-phillip** [comment]
Commenting here with details from our OOB discussion.

> We should also check if these other settings https://github.com/rancher/rancher/pull/45894 are broken on the UI side as well and fix them.

Anything that uses fetchOrCreateSetting to set a default value (that's different from the default on the backend) if a setting doesn't exist would be broken. It looks like the only instance that actually saves a setting is

```
    this.addExtensionReposBannerSetting = await fetchOrCreateSetting(this.$store, SETTING.ADD_EXTENSION_REPOS_BANNER_DISPLAY, 'true', true) || {};
```

**Comment by rak-phillip** [comment]
Should the default value for `display-add-extension-repos-banner` be updated to `true` in `pkg/settings/setting.go`?

https://github.com/pmatseykanets/rancher/blob/5db497538f3a6b9bef2dd4c9290ae07780837924/pkg/settings/setting.go#L324

**Comment by aalves08** [comment]
I think we can get away with my PR since the value being `false` is the condition for it not to be displayed, ihmo

To be noted that would definitely prefer to have it fixed on the backend, but given the constraints that we have in terms of time, we can get away with this 😛 

FYI @richard-cox

**Comment by aalves08** [comment]
We can also put up a PR on the backend side as well

**Comment by yonasberhe23** [comment]
Extensions banner for Rancher Prime is displayed as expected.

Tested in:

- Rancher v2.10-66f68094ca4bd26cd54e59b6f6fbf24a3cb79dbd-head
- Dashboard master 99285c9

https://github.com/user-attachments/assets/356c05b3-4849-4278-be3d-9b04a66c9ef3
