### ISSUE TITLE
Fleet: Workspace switcher: Dropdown menu overlaps select box

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12388]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version: FF, ~~Chrome~~

**Describe the bug**
Dropdown menu overlaps select box.

**To Reproduce**
1. go to Fleet
2. click workspace switcher in the header

**Result**
![image](https://github.com/user-attachments/assets/62077256-1021-4438-b320-97dc4e3f2266)
**Expected Result**
![image](https://github.com/user-attachments/assets/cb933aa8-2372-443a-8478-33006fd086a5)

**Screenshots**

**Additional context**

**Comment by gaktive** [comment]
We'll see who can grab this in the next day but this feels like something to tackle in 2.11.0 and backport to 2.10.1 if we run out of time.

**Comment by gaktive** [comment]
@nwmac wasn't able to repro this on his environment with a recent build. @yonasberhe23 can you retest just in case another fix addressed this?

**Comment by yonasberhe23** [comment]
retested and found this issue is specific to Firefox browser (not an issue in Safari and Chrome).

**Comment by yonasberhe23** [comment]
workspace selector dropdown fixed in Firefox. also tested in other browsers.

Tested in:

- Rancher v2.10-e2d0b42c91253243696d36f09e8e6e23cc6fb0db-head
- Dashboard master 3c808b4
