### ISSUE TITLE
Fleet: Git Repo: Creation: Next button is greyed out (but clickable) when required fields are filled

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12385]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version: FF, Chrome

**Describe the bug**
Next button is greyed out (but clickable) when the required fields are filled.

**To Reproduce**
1. go to Fleet > Git Repos
2. click Add Repository
3. input name
4. notice Next button is greyed out 

**Result**

https://github.com/user-attachments/assets/9161e826-8a43-4bf7-8d45-71bec35d81f6

**Expected Result**
Next button should not be greyed out when the required fields are filled.

**Screenshots**

**Additional context**

**Comment by gaktive** [comment]
@yonasberhe23 #12204 was just merged and looks related. Can you retest this with the associated build since that PR has been merged?

**Comment by yonasberhe23** [comment]
no longer an issue. closing issue

retested in:
- Rancher v2.10-e615207c8cd924c092b55a9301e7378878706d19-head
- Dashboard master 1ed167d
