### ISSUE TITLE
Fleet: Git Repo: Error is not shown when adding git repo

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12391]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version: FF, Chrome

**Describe the bug**
Error info when adding git repo is not shown to user.

**To Reproduce**
1. go to Fleet > Git Repos
2. click Add Repository 
3. enter `AAA` for name 
4. click Next
5. click Create

**Result**
Error is not shown when adding git repo
**Expected Result**
![image](https://github.com/user-attachments/assets/be8e2353-6fbe-4678-bb5a-d0682a46e1cd)

**Screenshots**

**Additional context**

**Comment by yonasberhe23** [comment]
Found while testing https://github.com/rancher/dashboard/issues/12298

**Comment by gaktive** [comment]
Similar to #12385, @yonasberhe23 #12204 was just merged and looks related. Can you retest this with the associated build since that PR has been merged?

**Comment by yonasberhe23** [comment]
@gaktive this is still an issue.

retested in:
- Rancher v2.10-e615207c8cd924c092b55a9301e7378878706d19-head
- Dashboard master 1ed167d

**Comment by momesgin** [comment]
@yonasberhe23 I can reproduce this in 2.9 as well.

**Comment by yonasberhe23** [comment]
@momesgin I'm unable to repro this in 2.9. Are you seeing the error in 2.9 when entering an invalid name?

**Comment by yonasberhe23** [comment]
Error is shown when adding git repo with invalid name.


Tested in:

- Rancher v2.10-e2d0b42c91253243696d36f09e8e6e23cc6fb0db-head
- Dashboard master https://github.com/rancher/dashboard/commit/10e5e5b0280c01d763725da23d2e6d3bb0523559
