### ISSUE TITLE
`isRancher` value gets set to `false` randomly 

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#12406]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

In initial loading of the app `isRancher` gets set to `false` randomly. This causes to not display projects in the app, for example in the namespace dropdown. `Namespaces/Projects` on the side bar also changes to `Namespaces`. Some e2e tests get failed due to this for example `namespace-picker.spec.ts`.

The problem occurs [here](https://github.com/rancher/dashboard/blob/master/shell/store/index.js#L795) where we get `rejected` for `res.rancherSchemas.status`.

**To Reproduce**

There's no reliable way to reproduce this, but refreshing the explorer page can be a good way to repro, or running e2e tests `namespace-picker.spec.ts`.

**Result**

**Expected Result**

**Screenshots**

`console.log(res, res.rancherSchemas.status, res.rancherSchemas.reason, getters['management/schemaFor'](MANAGEMENT.PROJECT))`:
<img width="691" alt="Screenshot 2024-10-25 at 9 49 08 AM" src="https://github.com/user-attachments/assets/1eb10499-9d35-4bff-8b49-e2dabd88779a">

**Additional context**

Some discussion around this issue has happened on the UI's Slack channel.

**Comment by yonasberhe23** [comment]
No longer experiencing this issue. Tested in:

- Rancher v2.10-e59c50a79bff2b6cc023bdbdb4e825190b7833fb-head
- Dashboard master f878279
