### ISSUE TITLE
Project description does not show in Projects/Namespace list

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12403]
**Setup**
- Rancher version: 2.9.1

**Describe the bug**
- project groups in project/namespace list should contain description, but do not

**To Reproduce**
- cluster explorer --> cluster --> projects/namespaces
- ensure group by project is selected

**Result**
![image](https://github.com/user-attachments/assets/99e6520c-f449-4f29-9955-538e41c7e280)

**Expected Result**
![image](https://github.com/user-attachments/assets/0616d70d-2d3a-4f10-a893-6bd5d1d58b73)

**Comment by yonasberhe23** [comment]
Project groups in Project/Namespace list contain a description.

Tested in:

- Rancher v2.10-e2d0b42c91253243696d36f09e8e6e23cc6fb0db-head
- Dashboard master 3c808b4

![Image](https://github.com/user-attachments/assets/0fa13135-c871-4d0e-883d-aa838c22763d)
