### ISSUE TITLE
CIS Benchmark: Scans: Configurations set during creation are not reflected in edit mode

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12411]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version: FF, Chrome

**Describe the bug**
Scan configurations set during creation are not reflected in edit mode. The form is reset to default values.

**To Reproduce**
1. install CIS Benchmark
2. go to Scans
3. click Create
4. select 'Run scan on a schedule' and set configs
5. click Create
6. click Edit Config > notice config is default
7. go to detail page > click Config > notice config is correct

**Result**
Configurations set during creation are not reflected in edit mode.

**Expected Result**
Configurations set during creation are reflected in edit mode.

**Screenshots**

https://github.com/user-attachments/assets/227232da-aeb3-46c3-9530-80146342e002

**Additional context**

**Comment by gaktive** [comment]
@yonasberhe23 can you quickly check how this is working on 2.9.x? I don't think we touched this part of the code in 2.10.0 at all so I'm curious if this is a regression as this doesn't look Vue3 related.

**Comment by yonasberhe23** [comment]
@gaktive this works as expected in 2.9.3


https://github.com/user-attachments/assets/45695629-b138-4fc9-9177-352f64ae9adc

**Comment by yonasberhe23** [comment]
Configurations set during creation are reflected in edit mode.

Tested in: 

- Rancher v2.10-e2d0b42c91253243696d36f09e8e6e23cc6fb0db-head
- Dashboard master 6dd2962
