### ISSUE TITLE
Test `v-model.number` usage in 2.10 / vue3 world

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12428]
- Follow on from https://github.com/rancher/dashboard/pull/12420#discussion_r1822651621
- Are all `v-model.number` usages broken and need to be replaced by changes similar to https://github.com/rancher/dashboard/pull/12420? 
  - If so this needs upgrading to bug
- Usages
  - shell/components/form/Ports.vue
  - shell/components/form/ServicePorts.vue
  - shell/edit/provisioning.cattle.io.cluster/tabs/MachinePool.vue

Screen Recording: 
https://github.com/user-attachments/assets/7dbfc1f7-df5f-4747-8836-9eaa01203d82

**Comment by gaktive** [comment]
We may be lucky in that usage of this variable is light so we could push this out to 2.11.0 with a backport but we should know how we look for 2.10.0.

**Comment by yonasberhe23** [comment]
Unit input for unhealthy node timeout on machine pools in cluster provisioning fixed.

Tested in:

- Rancher v2.10-e2d0b42c91253243696d36f09e8e6e23cc6fb0db-head
- Dashboard master 10e5e5b
