### ISSUE TITLE
Improve Fleet Performance

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12424]
**Setup**
- Rancher version: 2.9

Contributes to SURE-9104

**Describe the bug**

Improve or remove fleet git repo clusterResourceStatus and resourcesStatuses getters
- The performance of clusterResourceStatus and specifically resourcesStatuses is horrible
  - Compounded by being called a LOT given bundledeployment churn
- We need a short term fix before understanding final information requirements of fleet
  - Could involve fleet providing summary of states as requierd
  - Could involve making some very low bar fixes to functions
  - Could involve removing the need to show data

Remove dependnecy on bundledeployment resource type
- this can be HUGE, taking many seconds to fetch and then provide churn over websocket
- need to confirm where this data is used and either remove the need for it or receive from Fleet directly

**Additional context**
Reference chain

gitRepo clusterResourceStatus
--> shell/components/formatter/FleetSummaryGraph.vue component computed `summary`. find specific cluster --> status.resoureCounts
  --> FLEET_SUMMARY header
     --> Fleet Cluster List View (`Resources` Column)
     --> shell/components/fleet/FleetRepos.vue cluster (in not cluster mode) list 
       --> Fleet Git Repo List (actual list)
     --> Fleet cluster Group List View (`Resources` Column)
  --> shell/components/formatter/FleetClusterSummaryGraph.vue wrapper
    --> shell/components/fleet/FleetRepos.vue (in cluster mode)
       --> Fleet Cluster Detail View (git repo list 'Resources' column)
--> shell/components/fleet/FleetRepos.vue (in cluster mode)
  --> find current cluster --> cluster.status?.displayStatus  
    --> Fleet Cluster Detail View (git repo list)
     
gitRepo resourcesStatuses     
--> gitRepo clusterResourceStatus
  --> shell/components/fleet/FleetResources.vue   
    --> Fleet Git Repo Detail View (resources table)

trying to summarise ...
- Fleet Cluster List View (Resources Column)
- Fleet Git Repo List (State column)
- Fleet Git Repo List (Resources column)
- Fleet ClusterGroup List View (Resources Column)
- Fleet Cluster Detail View (top section, large pills)
- resourcesStatuses is only used specifically in the Fleet Git Repo Detail View (resources table)

**Comment by gaktive** [comment]
I'll defer on filing a back port issue for now until @richard-cox determines the approach.

**Comment by richard-cox** [comment]
@ QA please reach out to me for areas to test / scale

**Comment by IsaSih** [comment]
Validated in v2.9-023781e52103c45a9bbdf3cb47d60b9336321daa-head and v2.10-0f28018201f044edebee948e7644fd45836d24c7-head
