### ISSUE TITLE
As custom user incorrect fleet gitrepos are shown given the workspace filter 

### ISSUE THREAD

**Issue by mmartin24** [rancher/dashboard#12437]
**Setup**
- Rancher version: 2.10.0-alpha5
- Rancher UI Extensions:
- Browser type & version:Brave 1.70

**Describe the bug**
After an admin deploys 2 girepos one in fleet-local and the other in fleet-default, an user with access to these gitrepos will see them in incorrect order when using the toggle (the ones meant to be in local will appear in default and the one in default will appear in local)

**To Reproduce**
- Deploy Rancher `2.10.0-alpha5` with at least 1 downstream cluster
- As an admin deploy these 2 gitrepos:
**Local cluster**
```
Name: fleet-local-simple-chart
URL: https://github.com/rancher/fleet-test-data
branch: master
path: simple-chart
```
 **Default cluster**
```
Name: fleet-default-nginx
URL: https://github.com/rancher/fleet-test-data
branch: master
path: qa-test-apps/nginx-app
```
 - Create standard user `std-user-46` with this custom roles:
 ```
  { resource: "fleetworkspaces", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},
  { resource: "gitrepos", verbs: ["list"]},
  { resource: "bundles", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},
```
- Access as `std-user-46`

**Result**
When navigating to gitrepos `std-user-46` sees: 
- when changing toggle to `fleet-local` gitrepo `fleet-default-nginx` 
- when changing toggle to `fleet-default` gitrepo `fleet-local-simple-chart`
![image](https://github.com/user-attachments/assets/58b8a387-4224-4043-9b79-5ebdedb204be)

**Expected Result**
When navigating to gitrepos `std-user-46` should see: 
- when changing toggle to `fleet-local` gitrepo `fleet-local-simple-chart`
- when changing toggle to `fleet-default` gitrepo `fleet-default-nginx`

**Screenshots**

[Screencast from 30-10-24 17:15:59.webm](https://github.com/user-attachments/assets/a97b2c32-19e3-459d-a7df-fb2a7316cf0d)

**Additional context**

**Comment by richard-cox** [comment]
@mmartin24 can you confirm how you created the two git repos? it would be expected that the git repo is created in the workspace that was selected at the time of creation

**Comment by eva-vashkevich** [comment]
@gaktive should I look into this and try to fit it in 2.10?

**Comment by richard-cox** [comment]
@eva-vashkevich if it's reproducible and a regression we should try. if it's not reproducible or a regression it can definitely be pushed to 2.11. In `master` i couldn't reproduce, the gitrepos appear in the workspace they were created in

**Comment by eva-vashkevich** [comment]
I am able to reproduce the issue and can confirm it is not present in 2.9 dashboard

**Comment by mmartin24** [comment]
> @mmartin24 can you confirm how you created the two git repos? it would be expected that the git repo is created in the workspace that was selected at the time of creation
> 
> Edit: this can be confirmed by looking at the metadata.namespace of the gitrepo:

@richard-cox the admin does create the gitrepo on the expected workspace in both cases, here you can see how for gitrepo `fleet-default-nginx`, created on the workspace `fleet-default`, the `metadata.namespace` is `fleet-default`
![image](https://github.com/user-attachments/assets/fabfc6c3-fb20-41b1-a5bf-df29045fd36b)

For `std-user-46`, with the toggle pointing to `fleet-default`. the `metadata.namespace` is still `fleet-default`  but the gitrepo displayed is the one belonging to the `fleet-local` workspace, (`fleet-local-simple-chart`)
![image](https://github.com/user-attachments/assets/54ec03d7-dc81-4742-a2ad-ffb7f0c328d2)

**Comment by richard-cox** [comment]
@mmartin24 i still can't reproduce. can you try on `head`, and include specific steps to reproduce (for instance i created _global_ roles and added the required _group_ to the resource grants)? I don't think this affects much, but the gitrepo permission with just list is a bit odd (should probably include get too).

@eva-vashkevich please can you provide an update on how you reproduced and progress from yesterday?

**Comment by mmartin24** [comment]
@richard-cox, sorry for the delay.
I tried with something simpler as creating another admin user and in that case it works (although it has a delay on displaying the correct repo, in case it gives you a hint).
The best reproduction steps are the ones described in the ticket, but I can provide you a full video of our test with all the steps followed to get to this point.
Please let me know if this is ok:

https://github.com/user-attachments/assets/30e73446-fcd8-4cf9-a2b8-7866a7b7d507

**Comment by eva-vashkevich** [comment]
Hi @mmartin24 I am able to reproduce using steps from the ticket and will sync with Richard if needed. Right now I am still trying to figure out the cause.

**Comment by richard-cox** [comment]
Details in PR, but key bug points
- issue revolves around switching between workspaces or namespaces where the number of rows remains the same
 - hard to reproduce in namespace world given switcher isn't singular
- user irrelevant
- cause by a change of vue3 reactivity

**Comment by yonasberhe23** [comment]
Seeing correct gitrepos, clusters, and cluster groups when navigating between workspaces. Also conducted regression testing around lists.

Tested in:
- Rancher v2.10-212d8b6e92992235d791d8f2aaea8436ab4f6b77-head
- Dashboard master 99285c9

https://github.com/user-attachments/assets/de63eb1e-0c18-40d0-996f-44ad2edd0665
