### ISSUE TITLE
[EKS] - Changing nodegroup name to an existing name abruptly closes the edit form

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#12442]
**Setup**
- Rancher version: 2.10.0-alpha5
- Rancher UI Extensions: v2.10.0-alpha3
- Browser type & version: Firefox

**Describe the bug**

Changing a nodegroup name to an existing name abruptly closes the edit form.

**To Reproduce**

1. Edit an existing cluster
2. Add a nodegroup and edit the name; change it to `somenode`; change it again to an existing nodegroup name.
**Result**
Changing the name to `somenode` is fine, but then changing it to an existing nodegroup name, abruptly closes the form.
**Expected Result**

The form should error out with an error like the following - 
```
Node group names must be unique within the [c-w94xd] cluster to avoid duplication
```
**Screenshots**

[Uploading Screencast from 10-31-2024 04:35:32 PM.webm…]()

**Additional context**

**Comment by richard-cox** [comment]
@valaparthvi no need to prefix the issue title with the version the bug was found in, that information is tracked in the description and also it can get confusing when issues are fixed against a different milestone

**Comment by richard-cox** [comment]
@valaparthvi is this reproducible in `head` or 2.9? @mantis-toboggan-md could this be a regression?

**Comment by mantis-toboggan-md** [comment]
@richard-cox this is a vue3-related regression

**Comment by valaparthvi** [comment]
>is this reproducible in head or 2.9?

No, it's not reproducible. The form throws validation error on duplicate nodegroup name.

**Comment by izaac** [comment]
Rancher version: `v2.11-b435a2d786c50b03bd1ba7279a6a621ebcd19c84-head`
UI version: `release-2.10 d5b785b`

It is not possible to use duplicated nodegroup names in the UI form. The validation checks for that and the Save button isn't clickable. Also a message error is displayed so the user knows what's wrong.

Followed the steps to reproduce indicated in this issue and validate on the latest UI build.
![nodegroups](https://github.com/user-attachments/assets/f0deeeb5-eb76-43df-a488-6a0635e31f76)
