### ISSUE TITLE
[Logging V2] Logging Install Bug

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1244]
HA rancher setup e919796

When installing the logging app, if you check enable control plane logs the chart will fail to install with the following error.  The chart succeeds if this box is not checked.

```
Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Tolerations: []v1.Toleration: v1.Toleration.Value: ReadString: expects " or n, but found t, error found in #10    byte of ...|,"value":true},{"eff|..., bigger context ...|":"node-role.kubernetes.io/controlplane","value":true},{"effect":"NoExecute","key":"node-role.kubern|...
helm.go:94: [debug] Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Tolerations: []v1.Toleration: v1.Toleration.Value: ReadString: expects " or n, but found t, error found in rancher/dashboard#10 byte of ...|,"value":true},{"eff|..., bigger context ...|":"node-role.kubernetes.io/controlplane","value":true},{"effect":"NoExecute","key":"node-role.kubern|...
```

**Comment by izaac** [comment]
HA k8s Rancher setup `master-head (09/17/2020)` _ 33f755f_

Still reproduced in this build.

**Comment by deniseschannon** [comment]
How is this a UI issue? @paynejacob

**Comment by paynejacob** [comment]
The error is caused by malformed tolerations from the UI.  This error doesn't occur if  you install with cli.

**Comment by codyrancher** [comment]
@paynejacob What's the expectation of the tolerations? It seems like it's meeting the spec to me.
https://github.com/rancher/dashboard/issues/1109
Here's what the spec mentions:
```
- key: node-role.kubernetes.io/controlplane
   value: true
   effect: NoSchedule
- key: node-role.kubernetes.io/etcd
   value: true
   effect: NoExecute
```

Here's what's sent:
![Screen Shot 2020-09-18 at 1 11 41 PM](https://user-images.githubusercontent.com/55104481/93641560-52172e80-f9b1-11ea-982c-1ecb9ebf9e1a.png)

**Comment by paynejacob** [comment]
That looks correct to me ill test in cli and see if I can reproduce the issue.

**Comment by paynejacob** [comment]
This was an issue with the yaml I provided initially the yaml below works

```
tolerations:
  - key: "node-role.kubernetes.io/controlplane"
    value: "true"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/etcd"
    value: "true"
    effect: "NoExecute"
```

**Comment by izaac** [comment]
Rancher version: `master-head (09/18/2020)` _ 8fd81a9_ 

Validated fixed in `master-head`. Installing with and without Control Plane additional sources.

This is still an issue in `v2.5.0-alpha3` when we select `Deploy with control plane nodes.` Installing with that option disabled it works.
