### ISSUE TITLE
RKE2 cluster provision: Data Directories should not be editable after creation

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#12455]
See: https://github.com/rancher/dashboard/issues/12405#issuecomment-2450798787

Data directory settings can not be edited after cluster creation, so we should grey out the input boxes and the radio buttons.

Note, we should add a message between the 'Data directory configuration' title and the radio buttons, saying "Data directory configuration can not be changed once the cluster has been created"

**Comment by yonasberhe23** [comment]
![Image](https://github.com/user-attachments/assets/d95c230f-2a2d-40ee-8317-b28d177d252d)


Tested in:

- Rancher v2.11-1fc33272102599d7e6410f145a7bc190a0f2d292-head
- Dashboard release-2.10 `c634d5c`
