### ISSUE TITLE
CRs state get refreshed only on a refresh of the page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1246]
**On master-head - commit if: `e919796`**

- In dashboard: 
- Deploy backup-restore operator chart or CIS benchmarks charts
- Deploy a backup CR/ Cluster scan CR
- The CRs will be seen in `Active` state.
- The state of the CRs will change to `Error`/`Pass`/`Fail` only when the page is refreshed.

**Expected:**
the state of the CRs should change even without a refresh of the page.

**Comment by deniseschannon** [comment]
Closing in favor of the umbrella issue of change events not working reliably.
