### ISSUE TITLE
[ Istio V2 ] Change Kiali Url

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#1247]
Change hardcoded Kiali URL from:
`https://brendar.do.rancher.space/api/v1/namespaces/istio-system/services/http:rancher-istio-kiali:20001/proxy/` 
to 
`https://brendar.do.rancher.space/api/v1/namespaces/istio-system/services/http:kiali:20001/proxy/`

**Related Issue**
https://github.com/rancher/rancher/issues/28901

**Comment by bmdepesa** [comment]
https://github.com/rancher/rancher/issues/28901

rancher/rancher:master-head 8fd81a9

Deploy a cluster
Install monitoring & Istio
Go to Istio Overview page
Kiali link opens successfully
