### ISSUE TITLE
Kubewarden extension UI is incompatible with Rancher 2.10 and kubernetes version > 1.29

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#12481]
**Setup**
- Rancher version: v2.10-212d8b6e92992235d791d8f2aaea8436ab4f6b77-head
- Rancher UI Extensions: fleet-agent, fleet, fleet-crd, rancher-kubewarden-controller, kubewarden-controller:3.0.1, rancher-kubewarden-crds

**Describe the bug**

User can install Kubewarden controller and crds charts but cannot install the extension UI due to incompatibility with Rancher v.2.10 and kubernetes version > 1.29 according to the messages displayed in the tooltips

**To Reproduce**
1- Via the UI, select a cluster (could be local or downstream) go to Apps > Repositories 
2- Hit Create then, create an HTTP repository type, with the URL https://charts.kubewarden.io
3- Hit Create then, create another HTTP repository type, with the URL https://rancher.github.io/kubewarden-ui/
4- Go to the extensions catalog and install the Kubewarden extension with default settings
5- From the global side menu bar, go to extensions > Available tab > and install the Kubewarden UI

**Result**
All the UI versions are blocked to be installed due to incompatibility with Rancher v.2.10 or kubernetes version > 1.29
 
**Expected Result**

That there's a kubewarden UI version that is compatible with Rancher v.2.10 and Kubernetes version > 1.29 and can be successfully installed and displayed in the Rancher dashboard UI

**Screenshots**

https://github.com/user-attachments/assets/da262278-cc73-4f6a-85ad-6717dc2003e1

**Comment by richard-cox** [comment]
KubeWarden (and other prime extensions) support in vue3 world will come post 2.10.0, covered by https://github.com/rancher/dashboard/issues/12183
