### ISSUE TITLE
Clusters: Unable to edit local cluster

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#12506]
**Setup**
- Rancher version: v2.10-e59c50a79bff2b6cc023bdbdb4e825190b7833fb-head
- Rancher UI: `master f878279`
- Browser type & version: Chrome

**Describe the bug**
User is unable to edit local cluster.

**To Reproduce**
1. go to cluster management
2. click ellipsis for local cluster
3. click Edit Config
4. notice Create button (should be Save) is disabled
5. add description
6. notice Create button is still disabled

**Result**
User is unable to edit local cluster.

**Expected Result**
User is able to edit local cluster.

**Screenshots**

https://github.com/user-attachments/assets/092c7ed3-c583-4072-b371-7797922782ac

**Additional context**

**Comment by gaktive** [comment]
Problem not happening on RKE2 & k3s. QA to confirm if this is happening elsewhere; if this is only local, then it's a release note for 2.10.0 until we figure out what to do since code change here will touch a lot of things.

**Comment by mantis-toboggan-md** [comment]
Looks related to `[this](https://github.com/rancher/dashboard/blob/master/shell/models/management.cattle.io.cluster.js#L117)` getter. There is a possiblity for regression in the provider/distro column of cluster list views, as well as routing to/from the 'edit config' of clusters generally. We'll need to verify behavior for each of the following cluster types:

    local clusters:
        rke1
        rke2
        k3s
        hosted

    downstream clusters:
        rke1 provisioned
        rke2 provisioned
        k3s provisioned
        rke1 imported
        rke2 imported
        k3s imported
        hosted imported

**Comment by yonasberhe23** [comment]
Closing this out as I have already tested this in 2.10.
