### ISSUE TITLE
Dark theme - Main application & cluster drop-down is messed up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1251]
Issues:
1.  Can't see the dividing line
2. Gray color isn't used elsewhere
3. Can't see the app icon when highlighted over it.

Quick Fix:  Change background color back to previously dark color.  Ensure after fix that the light background is good as well.

![image](https://user-images.githubusercontent.com/11514927/93253617-fc8e1800-f74b-11ea-844d-4c4e74165d4f.png)

**Comment by deniseschannon** [comment]
Looks okay in master-head now?

![Screen Shot 2020-09-20 at 12.33.22 PM.png](https://zube.io/files/rancher/8ee84252ba660de278d281b4a85f8519-screen-shot-2020-09-20-at-12-33-22-pm.png)

**Comment by tfiduccia** [comment]
Yep, Vincent fixed it and never sends the bugs back :).

**Comment by vincent99** [comment]
I send them back when I'm aware they exist...
