### ISSUE TITLE
Embedding web-worker polyfill breaks sourcemap tools

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12511]
**Setup**
- Rancher version: 2.9

**Describe the bug**
The BLOB code from web-worker is minified, and contains source maps that are then passed over by webpack - that creates a situation of minified code inside BLOB inside minified code which confuses some tools, eg.

https://github.com/jantimon/chrome-profile-sourcemap-resolver/pull/4

That could be fixed, but the only reason to do so would be supporting very old (pre-2013) browsers, so we are better off removing the polyfill altogether.

**Expected Result**
Validation steps for QA
- Browser Tab 1 - Open Pods list and create a trivial pod
- Browser Tab 1 - Open browsers dev tools window --> Network tab --> WS tab --> socket connection for the cluster --> MEssages tab
- Browser Tab 2 - Nav to edit page for pod and edit it
- Browser Tab 1 - See `resoure.change` message for pod just changed

**Notes**
Fallback brought in when fixing another issue - https://github.com/rancher/dashboard/pull/6563

**Comment by gaktive** [comment]
Thankfully QA validated this in 2.10.1 so this should be OK for 2.11.0 & 2.9.5 as GH skipped passing this To Test or QA Review.
