### ISSUE TITLE
Unable to Edit Config of imported Azure AKS cluster

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#12525]
**Setup**
- Rancher version: `v2.10.0-alpha7` Dashboard: v2.10.0-alpha5 (also on current v2.10-head)
- aks-operator version: `rancher-aks-operator:105.0.0+up1.10.0-rc.2`
- Browser type & version: any

**Describe the bug**
When attempting to edit/upgrade an imported Azure AKS cluster via `Edit Config`, the dialog is blank. This dialog is sometimes shown but in this case it offers an empty list of Kubernetes versions to upgrade to with only entry `No options` instead of any k8s version.

I was able to reproduce this twice in a row on a fresh clusters and with AKS clusters in different locations / k8s versions installed.

It works fine for rancher provisioned AKS clusters. 

I believe this is related to the UI, but I may be wrong, in this case please move to `CAPI & HP` project .

**To Reproduce**
* Provision an AKS cluster via az CLI:
```
az group create -l eastus -n th-rg
az aks create --resource-group th-rg --no-ssh-key --kubernetes-version 1.29 --name th-az-imported-293 --node-count 1 --location eastus
```
* Import the AKS cluster into rancher -> Cluster Management -> Import Existing -> Azure AKS, select/create the credentials -> select the cluster you created from the list -> press `Import` button
* After a short while the cluster will be imported
* From `Cluster Management` select the cluster's three dots vertical menu and select `Edit Config`

**Result**
* The Edit dialog is blank - only sometimes offer a list of k8s versions to upgrade to but there is only `No options` "version" available.

**Expected Result**
The Edit dialog should be shown and it should offer a list of valid k8s versions for upgrade

**Screenshots**
![aks-imported-upgrade](https://github.com/user-attachments/assets/47644439-1e5a-4b27-a540-0e72829250d4)

![image](https://github.com/user-attachments/assets/7ee797f4-8bf3-4fd4-a316-ba0ffe2a3550)

**Comment by rak-phillip** [comment]
@thehejik I'm seeing the following error logged to the console

```
TypeError: Invalid Version: 1.29
    u semver.js:38
    i compare.js:3
    i gt.js:2
    t CruAks.vue:542
    aksVersionOptions CruAks.vue:538
    run reactivity.esm-bundler.js:190
    get value reactivity.esm-bundler.js:1171
    get runtime-core.esm-bundler.js:3488
    get runtime-core.esm-bundler.js:3132
    default CruAks.vue:1062
```

Can you confirm that you see the same?

**Comment by rak-phillip** [comment]
Updating milestone to 2.11 and creating a backport pr for 2.10

**Comment by thehejik** [comment]
Thanks, it's working as expected now on Dashboard `release-2.10 f9cdb12`.
![image](https://github.com/user-attachments/assets/583e894b-b912-438c-b292-ea859d290129)

Can be closed from QA point of view.

**Comment by yonasberhe23** [comment]
![Image](https://github.com/user-attachments/assets/e13d328f-9e76-4d40-ab2d-c72ff4f614ca)


Tested in:

- Rancher v2.11-47219bf3205877c4f5d09e6a1b15158a21ff4b76-head
- Dashboard release-2.10 `d803847`
