### ISSUE TITLE
[BUG] Downstream v2prov clusters do not accurately reflect configured rewrites and mirrors

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#12524]
**Rancher Server Setup**
- Rancher version: `v2.10-f95d1dc120a4b4c602fcb1485b36134fc0f4a2bc-head`
- Installation option (Docker install/Helm Chart): `Helm`

**Information about the Cluster**
- Kubernetes version: `v1.31.2+rke2r1`, `v1.31.2+k3s1`
- Cluster Type (Local/Downstream): `Downstream Node driver`

**User Information**
- What is the role of the user logged in? `Admin`

**Describe the bug**
When provisioning a downstream v2Prov Node driver cluster w/ mirrors and rewrites configured, the cluster comes up `active` and successfully provisions, but `/etc/rancher/agent/registries.yaml`, as well as Rancher UI `Edit Config > Registries`, does not reflect the expected configurations, set during the initial cluster provisioning

**To Reproduce**
1. Fresh install of Rancher `v2.10-head`
2. Provision a downstream RKE2 cluster, `v1.31.2+rke2r1`, with cluster scoped registry enabled and the following configurations set:
     - Registry hostname: `docker.io`
     - Mirror endpoints: `https://registry.example.com`
     - Rewrite Config -> Rewrite pattern: `^rancher/(.*)`
     - Rewrite Config -> Rewrite replacement: `mirrorproject/rancher-images/$1`
3. Verified - cluster successfully provisions
4. Reproduced

**Result**
`/etc/rancher/agent/registries.yaml` does **NOT** accurately reflect configured rewrites and mirrors
```logs
{"configs":{},"mirrors":null}
```

**Expected Result**
`/etc/rancher/agent/registries.yaml` accurately reflect configured rewrites and mirrors

**Additional context**
Only affects `v2.10` branch

**Comment by gaktive** [comment]
This worked in 2.9.x

**Comment by rak-phillip** [comment]
Updating milestone to `v2.11`, will create a `v2.10` backport issue.

**Comment by rancher-max** [comment]
This was validated on 2.10 line so I am going to close the 2.11 issue as well since the changes are the exact same and we don't have significant changes on the 2.11 line yet to warrant a separate validation.
