### ISSUE TITLE
CSI/CPI pre-bootstrap secrets are being created when the feature flag is disabled

### ISSUE THREAD

**Issue by susesgartner** [rancher/dashboard#12530]
**Setup**
- Rancher version: 2.9.3, 2.10-head
- Rancher UI Extensions: 
- Browser type & version:

**Describe the bug**
When provisioning a CSI/CPI with pre-bootstrap disabled the secrets for csi/cpi are created on the local cluster instead of the downstream cluster which causes the cluster to hang in bootstrapping.

**To Reproduce**
1. Create a csi/cpi cluster
2. Wait for it to hang in the bootstrap stage.
3. Go to the local cluster and search for csi/cpi secrets

**Result**
The secrets are populated in the local cluster instead of the downstream cluster causing the bootstrap stage to fail.

**Expected Result**
The secrets are stored in the downstream cluster.

**Screenshots**
![image](https://github.com/user-attachments/assets/a3610aaf-0a23-4c4f-9e4a-acf977a82f37)

**Comment by richard-cox** [comment]
@susesgartner can you confirm the downstream cluster does not receive the secret also that the downstream cluster does not eventual provision? Also can you confirm the annotations of the two secrets?

A change introduced in 2.10.0, 2.9.3 and 2.8.9 means the secret is created in the upstream cluster and then synced down to the target cluster pre-bootstrap.

Not sure where they are with 2.10.0 release notes, but for 2.9.3 see security fix point 3 and https://github.com/rancher/rancher/security/advisories/GHSA-xj7w-r753-vj8v

**Comment by susesgartner** [comment]
I can confirm that the downstream cluster does not provision. The secret doesn't exist in the downstream cluster which is what I would expect since pre-bootstrapping is disabled. 

The change that was introduced as part of the pre-bootstrapping feature should be conditional on the pre-bootstrapping feature being enabled. When it is disabled (which it is by default) the secret would not populate to the downstream cluster (since it can only do that if pre-bootstrapping is enabled), instead I would expect to see the original functionality pre-2.9.3 to be observed until the user enables the pre-bootstrap feature flag.

2.10.0 is still being worked on.

**Comment by richard-cox** [comment]
That's been missed, the UI will always create the secret upstream and expect it synced downstream.

@susesgartner can you provide details on the feature flag name?

@momesgin we need to return early in both handleVsphereCpiSecret and handleVsphereCsiSecret in shell/utils/v-sphere.ts if the feature flag is disabled. looking at the code that would then result in the previous functionality, could you confirm and implement if so?

**Comment by momesgin** [comment]
> That's been missed, the UI will always create the secret upstream and expect it synced downstream.
> 
> @susesgartner can you provide details on the feature flag name?
> 
> @momesgin we need to return early in both handleVsphereCpiSecret and handleVsphereCsiSecret in shell/utils/v-sphere.ts if the feature flag is disabled. looking at the code that would then result in the previous functionality, could you confirm and implement if so?

@richard-cox Sure, I'll add that to the logic, but in terms of real testing I should leave it to the QA as I don't have access to vSphere env anymore.

**Comment by gaktive** [comment]
This is blocking vSphere chart updates now for release so this is remains a critical thing to get. Keep @Sahota1225 in the loop so she can let Hostbusters QA know since sign-off needs this.

**Comment by susesgartner** [comment]
Ticket #12530 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provisioning test | PASS |
| 2. | Provisioning prebootstrap test | PASS |
| 3. | Migration test | PASS |

---
Verified with (HA Helm or Docker) on Rancher `v2.10-df21a48ad5e8007f449889a66c6ee1f4ba7af4ea-head`:
---
 
Scenario 1: Provisioning test
---
1. Provision a RKE2 csi/cpi cluster with pre-bootstrapping disabled
2. Verify that the cluster comes up active and all pods are in a stable state
 
Results: the cluster comes up active and all pods are in a stable state
 
---

Scenario 2: Provisioning prebootstrap test
---
1. Provision a RKE2 csi/cpi cluster with pre-bootstrapping enabled
2. Verify that the cluster comes up active and all pods are in a stable state
 
Results: the cluster comes up active and all pods are in a stable state
 
---
 
Scenario 3: Migration test 
---
1. Provision a RKE2 csi/cpi cluster with pre-bootstrapping disabled
2. Verify that the cluster comes up active and all pods are in a stable state
3. Enable pre-bootstrapping and wait for cluster to come up active
4. Run the migration script
5. Verify that all sensitive fields are moved into a secret.
 
Results: All validations passed and the cluster remains in a stable state.
