### ISSUE TITLE
Storybook landing page incorrect, and colors page broken

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12549]
**Describe the bug**
- Dev Kit home page links to https://rancher.github.io/storybook/, which instead of going to https://rancher.github.io/storybook/?path=/docs/welcome--docs goes to https://rancher.github.io/storybook/?path=/docs/foundation-colors--docs
- Colors page shows an error https://rancher.github.io/storybook/?path=/docs/foundation-colors--docs
  - ![image](https://github.com/user-attachments/assets/2a111d82-c913-4fc1-a107-c17ec6bca3fc)

**Comment by cnotv** [comment]
Closing as dupicate of https://github.com/rancher/dashboard/issues/11707

**Comment by richard-cox** [comment]
@cnotv there were two issues here, one probably not covered by #11707. I've created https://github.com/rancher/dashboard/issues/12550 for it

**Comment by cnotv** [comment]
Sorry I missed the homepage one, my fault.
