### ISSUE TITLE
Editing a non-builtin hosted cluster shows the add page instead

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12541]
**Setup**
- Rancher version: 2.9.1

**Describe the bug**
- For an existing hosted cluster's the add cluster page is shown when trying to edit the cluster
- Confirmed Not Working
  - OVH (custom provided kontainer driver)
- Confirmed Working
  - Linode (pre-installed but not built-in kontainer driver)
- Not Confirmed
  - GKE, EKS, AKS

**To Reproduce**
- Add the OVH kontainer driver
- Create a OVH hosted cluster
- Edit the cluster

**Result**
- Add cluster of that type is shown

**Expected Result**
- Edit page for that type should be shown

**Additional context**
- Could be related to the porting of some hosted providers to dashboard

**Comment by yonasberhe23** [comment]
Closing this out as I have already tested this in 2.10.
