### ISSUE TITLE
Overall drop-down Style issues (dark mode)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1255]
Issues:

Namespace drop-down:
1. White for disabled is confusing and inconsistent with how people think things should work. (dark mode)
2. Highlight, color change and underline is over-kill for hover/selection
3. Background color for drop-down needs to be fixed so I can see dividing line (dark mode, already entered as bug #1251)

Overall Fixes:
- [ ] If any selection is not selectable, it should be grey and our background UI should support that color.

- [x] Move "Sorry, no matches" text over so it's not bumping against the edge of the left side of the drop-down
![image](https://user-images.githubusercontent.com/11514927/93262905-d5d6de00-f759-11ea-88f1-7df5301c0c81.png)

- [ ] If there are not more than 10 items to be selected... the box should not be type-able.  Almost all drop-downs boxes should be not be type-able.
![image](https://user-images.githubusercontent.com/11514927/93262974-f0a95280-f759-11ea-8b1f-91724551e5a1.png)

Dark mode:
Closed drop-down issues to fix:
- [x] suggestion text (e.g.) is not light enough.  I can barely see it.  Maybe go one grey lighter?  Current is #4A4B52 and it should probably be #6C6C76 (this is true for all controls but I'm just going to reference it here)
![image](https://user-images.githubusercontent.com/11514927/93261423-855e8100-f757-11ea-9e36-f0ef9a24e89a.png)

Open drop-down issues to fix:
- [x] Always have black background, even if I hover my mouse off of that field (this should be for all controls, but referencing here):
Should always look like this:
![image](https://user-images.githubusercontent.com/11514927/93262227-bb503500-f758-11ea-8bcb-bdbca4f64213.png)
When I move my mouse around:
![image](https://user-images.githubusercontent.com/11514927/93262207-b25f6380-f758-11ea-941d-4c0e3daa93b4.png)

- [x] Remove underline when I hover over option.
![image](https://user-images.githubusercontent.com/11514927/93262348-f2264b00-f758-11ea-9cba-02ed9de0d1bb.png)

- [x] Move drop-down arrow over to the left a bit?  it's looks like it's too far to the right & even a couple of pixels will probably make it look better.

- [ ] If selection in drop-down is not required, we should have a none options (maybe in italics?) instead of small blue line at top (bug).
![image](https://user-images.githubusercontent.com/11514927/93262601-5c3ef000-f759-11ea-9dca-83fae933869e.png)

- [ ] Disabled controls & the blue drop-down for namespace on edit, looks exactly the same as enabled with suggestion text.
![image](https://user-images.githubusercontent.com/11514927/93279860-29a6ee80-f77d-11ea-98aa-9eb0dfc191af.png)

Suggestions - For drop-downs remove the v, change the text color it is same color as the Title, remove border & make the whole thing greyer (for disabled)

Current:
![image](https://user-images.githubusercontent.com/11514927/93280125-b81b7000-f77d-11ea-93f1-22000d4f4a2b.png)

Suggested:
![image](https://user-images.githubusercontent.com/11514927/93280112-b18cf880-f77d-11ea-9c73-e81015474b5f.png)

- [x] x for clearing text out of drop-down is not centered and bottom seems to be missing?
![image](https://user-images.githubusercontent.com/11514927/93322785-909dc500-f7c8-11ea-88f3-58ee1022f425.png)

- [x] double drop-down field seem to be transparent?  or the field labels are all brought to front cause they are bleeding through.
![image](https://user-images.githubusercontent.com/11514927/93323084-fee28780-f7c8-11ea-97c4-40d85a1dd631.png)

- [x] In workloads (deployments), the info text is see-through.  Add environment label and hover over i circle to see
![image](https://user-images.githubusercontent.com/11514927/94605558-25370700-024e-11eb-9bcb-9ef9649b5b29.png)

**Comment by lvuch** [comment]
"Always have black background, even if I hover my mouse off of that field (this should be for all controls" this is intentional, checking off

**Comment by lvuch** [comment]
I need a dev check these:
If selection in drop-down is not required, we should have a none options (maybe in italics?) instead of small blue line at top (bug).
If there are not more than 10 items to be selected... the box should not be type-able. Almost all drop-downs boxes should be not be type-able.

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1512

**Comment by tfiduccia** [comment]
Fixed
