### ISSUE TITLE
Generic x-able description for CRD pages

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1256]
Need a short description for all CRD pages that can be X-able.

**Comment by vincent99** [comment]
This are available in master now, I didn't add any but someone can write them.  *All* CRD pages seems way over the top, I would use this sparingly for mostly things like our products with our own types that people know nothing about.

https://github.com/rancher/dashboard/blob/e6eef37fed7d9c77c8fd09239a1fb577f25e8684/assets/translations/en-us.yaml#L1605-L1610

**Comment by aiyengar2** [comment]
#### Monitoring

ServiceMonitor: Defines a desired set of Prometheus alerting and/or recording rules, which is used by Prometheus Operator to generate a rule file used by Prometheus instances
PodMonitor: Declaratively specifies how group of pods should be monitored, which is used by Prometheus Operator to generate the scrape configuration used by Prometheus instances
PrometheusRule: Declaratively specifies how groups of Kubernetes services should be monitored, which is used by Prometheus Operator to generate the scrape configuration used by Prometheus instances

The following two above could be omitted or kept for consistency:
Prometheus: Defines a desired Prometheus deployment whose scrape configuration and rules is determined by selected ServiceMonitors, PodMonitors, and PrometheusRules and whose alerts will be sent to all selected Alertmanagers with the custom resource's configuration
AlertManager: Defines a desired Alertmanager deployment whose configuration will be specified by a Secret in the same namespace

**Comment by prachidamle** [comment]
CIS `rancher-cis-benchmark`

**ClusterScanBenchmark**
A ClusterScanBenchmark defines the CIS BenchmarkVersion name and test config. The BenchmarkVersion name is a parameter provided to the kube-bench tool. 

**ClusterScanProfile**
 A ClusterScanProfile defines the parameters to configure and run a CIS scan. It defines the CIS BenchmarkVersion to run and any set of tests that should be skipped in the scan. Using the same ClusterScanProfile, multiple CIS scans can be launched.

**ClusterScan**
A ClusterScan resource should be created to launch a new CIS scan on the cluster. The ClusterScan resource defines the ClusterScanProfile to be used for the scan. If ClusterScanProfile is empty, the default profile matching your cluster's provider will be chosen.

**ClusterScanReport**
Once a ClusterScan is completed, the report from the kube-bench tool is stored in a ClusterScanReport resource instance. For every scan a report is generated. This report can be downloaded.

**Comment by mrajashree** [comment]
### Backup-Restore-Operator

**Backup**: Create a Backup resource to perform a one-time backup or schedule recurring backups for an application by providing its ResourceSet (link to ResourceSet)

**Restore**: Create a Restore resource to restore an application from a backup

**ResourceSet**: A ResourceSet defines a set of selectors to gather/specify/target(not sure what the right word is) resources managed by a particular application, so they get included in the backup

**Comment by vincent99** [comment]
The "type" keys here are the fully-qualified `<group>.<kind>` name that you see in the URL for the list page, e.g. `management.cattle.io.fleetworkspace`

**Comment by mrajashree** [comment]
I think this should say CRDs and resources, we backup core resources like secrets, service accounts, deployments etc too
<img width="707" alt="Screen Shot 2020-09-23 at 7 09 28 AM" src="https://user-images.githubusercontent.com/10672776/94024028-c3692f80-fd6b-11ea-92df-91f02ecec57d.png">

**Comment by deniseschannon** [comment]
@aiyengar2 For now, I'm only going to focus on the CRDs for what we've created. I would hope anyone using Prometheus would refer to Prometheus docs on their CRDs.
