### ISSUE TITLE
Replace `v-tooltip` usage

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#12564]
There are several instances of `v-tooltip` identified in:

- pkg/aks/components/AksNodePool.vue
- shell/components/SideNav.vue
- shell/components/TableDataUserIcon.vue
- shell/components/nav/TopLevelMenu.vue

These should be replaced with `v-clean-tooltip`

**Comment by IsaSih** [comment]
tests pass on v2.11-d224815d7cfbf4194db1ffdfb04676d55d1a2062-head. Same test scenarios as of the ones validated for the backports
