### ISSUE TITLE
Re-enable CLI Download e2e tests

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12576]
- `head` points to 2.10.0 cli binaries, which aren't available
  - at time of issue creation v2.10-head points at 2.9.0 binaries which are available
- this causes are e2e tests that check links (amongst other things) to 404
- so now we check for 404 and need to change back to 200 when the binaries are there

**Comment by mantis-toboggan-md** [comment]
head builds now use a 2.11 CLI images that are downloading successfully. I'm rolling this issue into this pr https://github.com/rancher/dashboard/pull/12587

It is worth noting that the release-2.10 branch, which uses a 2.10 CLI version, is still returning 404s
