### ISSUE TITLE
Protocol drop-down in deployments doesn't close when I click away from the drop-down

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1257]
Issue:  The protocol drop-down doesn't close if I click anywhere except the two selections.  Even if I click on the main control or the drop-down arrow
![image](https://user-images.githubusercontent.com/11514927/93324273-8250a880-f7ca-11ea-84ca-8cac903cf44f.png)

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `33f755f18`**

The protocol drop-down closes when clicked anywhere on the page and also on the dropdown arrow
