### ISSUE TITLE
[Monitoring V2 UI] Move Prometheus / Alertmanager from Overview to Navigation Bar

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1260]
Creating a separate ticket to track this since it affects both https://github.com/rancher/dashboard/issues/1064 and https://github.com/rancher/dashboard/issues/1215.

#### Context

Currently, clicking on the Alertmanager or Prometheus buttons on the UI shown below takes the user to a URL that is otherwise inaccessible to the average user from the UI. It also takes you away from the monitoring-specific page back to the original Cluster Explorer page, but since Alertmanager and Prometheus are hidden here, no tab is highlighted on the left for the resource.

![screen_shot_2020-09-15_at_1 22 07_pm](https://user-images.githubusercontent.com/13127443/93375103-800f3e00-f80c-11ea-9f04-b49031416fbc.png)

Instead, we want to modify the Navigation Bar (https://github.com/rancher/dashboard/issues/1215) to now show Prometheus and AlertManager CRDs on the tab for Monitoring itself; since they will be accessible on the tab, we should also remove the colored buttons from the Feature Overview (https://github.com/rancher/dashboard/issues/1064) page.

**Comment by jiaqiluo** [comment]
this is validated in rancher:master-head with the latest UI

1. `Prometheus` and `AlertManager` CRDs show as tabs on the left side
2. the colored buttons are removed 

![image](https://user-images.githubusercontent.com/6218999/94214324-2226ca00-fe8e-11ea-866c-b22bfd480958.png)
