### ISSUE TITLE
[backport v2.9.5] RKE2 cluster provision: Data Directories should not be editable after creation

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12617]
This is a backport issue for https://github.com/rancher/dashboard/issues/12455

Original issue body:

See: https://github.com/rancher/dashboard/issues/12405#issuecomment-2450798787

Data directory settings can not be edited after cluster creation, so we should grey out the input boxes and the radio buttons.

Note, we should add a message between the 'Data directory configuration' title and the radio buttons, saying "Data directory configuration can not be changed once the cluster has been created"

**Comment by yonasberhe23** [comment]
![Image](https://github.com/user-attachments/assets/c2d21c51-c5b7-465d-9549-a1eb591e98d1)


Tested: 
- Rancher v2.9-023781e52103c45a9bbdf3cb47d60b9336321daa-head
- Dashboard release-2.9 `e3043ad`
