### ISSUE TITLE
[backport v2.10.1] RKE2 cluster provision: Data Directories should not be editable after creation

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12618]
This is a backport issue for https://github.com/rancher/dashboard/issues/12455

Original issue body:

See: https://github.com/rancher/dashboard/issues/12405#issuecomment-2450798787

Data directory settings can not be edited after cluster creation, so we should grey out the input boxes and the radio buttons.

Note, we should add a message between the 'Data directory configuration' title and the radio buttons, saying "Data directory configuration can not be changed once the cluster has been created"

**Comment by yonasberhe23** [comment]
![Image](https://github.com/user-attachments/assets/8d9e8061-c47b-42cf-8d22-48d1be8a5214)

Tested in:
Rancher v2.10-58e887a871d1377399ff18a4ee95335981f08991-head
Dashboard release-2.10 `c634d5c`
