### ISSUE TITLE
Add  & Add drop-down button control are confusing, & there are a couple of bugs with it.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1262]
Issue:  The Add button that has a drop-down associated to it is confusing.

![image](https://user-images.githubusercontent.com/11514927/93383585-b18e0680-f818-11ea-9b04-bd0c710e2719.png)

- [ ] Drop-down doesn't have all options, it only has the one that is separate from Add itself.  this is confusing cause I think there is really only 1 option and now I'm not sure what the drop-down is for?

- [ ] The drop-down itself looks like a comment and not associated to the button at all.  Anything with a caret at the top or associated to a box automatically make me think it's some sort of comment on that control.  If there are choices for a particular control, I assume it will be directly connected.

- [ ] Can't tab to the drop-down section or open it.
![image](https://user-images.githubusercontent.com/11514927/93384758-1e55d080-f81a-11ea-9ad2-2574c955c4ea.png)

- [x] Caret at top doesn't have border
![image](https://user-images.githubusercontent.com/11514927/93386207-3890ae00-f81c-11ea-8ad3-fb5d0b1c5291.png)

- [x] General Consistency... Not sure why the text for all the add buttons are blue & how they ended up twice the original size?  The only other control that uses the blue background is the double drop-down and the text is white for that.
![image](https://user-images.githubusercontent.com/11514927/93386862-311dd480-f81d-11ea-8040-6a9fcf773734.png)
![image](https://user-images.githubusercontent.com/11514927/93386905-40048700-f81d-11ea-9fbe-2f726899d640.png)

For consistency... the text should probably be white.  And the original Add buttons were 1/2 the size?
![image](https://user-images.githubusercontent.com/11514927/93386968-5874a180-f81d-11ea-88e8-31552289d8eb.png)

Fix:
1.  Either make a button for each type and don't have a drop-down at all (Personally I think the button drop-down concept is kinda strange)
![image](https://user-images.githubusercontent.com/11514927/93386238-434b4300-f81c-11ea-91bb-88e1fb911125.png)
or
![image](https://user-images.githubusercontent.com/11514927/93392113-13546d80-f825-11ea-97d2-e470bc218aca.png)

2.  Make the drop-down look like a true drop-down when clicked
![image](https://user-images.githubusercontent.com/11514927/93386356-71c91e00-f81c-11ea-9a80-9e3c49eea6d3.png)
or
![image](https://user-images.githubusercontent.com/11514927/93392556-d8066e80-f825-11ea-91ed-d6303dc592d8.png)

**Comment by lvuch** [comment]
This is the original mock for these buttons, using the `^` helps in cases where the button inself is relatively short. <img width="203" alt="Screen Shot 2020-10-07 at 10 14 13 AM" src="https://user-images.githubusercontent.com/3013118/95364636-ede7dc00-0885-11eb-85dc-08cccc7d457a.png">

**Comment by lvuch** [comment]
here is a grid of states and types of buttons, the color and design or these is accurate
<img width="627" alt="Screen Shot 2020-10-07 at 10 20 49 AM" src="https://user-images.githubusercontent.com/3013118/95365498-0c9aa280-0887-11eb-814b-e03277f6568c.png">

**Comment by lvuch** [comment]
the color and text is accurate as intended. 
<img width="629" alt="Screen Shot 2020-10-07 at 10 24 00 AM" src="https://user-images.githubusercontent.com/3013118/95365618-3d7ad780-0887-11eb-8973-22da7e16efc9.png">

**Comment by lvuch** [comment]
needs dev to look at key value add dropdown
<img width="741" alt="Screen Shot 2020-10-08 at 10 05 59 AM" src="https://user-images.githubusercontent.com/3013118/95491020-eb50b980-094d-11eb-9859-7fb7fd23d870.png">

**Comment by tfiduccia** [comment]
10/14 - not fixed?  Everything looks same?

**Comment by lvuch** [comment]
@tfiduccia see above comments. overall look is as it should be. There are a couple things I noted that need a dev to look at them.

**Comment by lvuch** [comment]
@vincent99 @tfiduccia as discussed on call yesterday all `button | v` should be changed to a row of buttons as to not bury the actions

**Comment by tfiduccia** [comment]
Ok, so the drop-down will be changed to two buttons.

**Comment by tfiduccia** [comment]
Discussed this issue with Lauren & Vincent.  It is covered in other general UI issues.
