### ISSUE TITLE
Fix some issues with extensions creator's package in branches

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12635]
Fix some issues with extensions creator's package in branches:

**release-2.8** 
https://github.com/rancher/dashboard/blob/release-2.8/creators/extension/app/files/.github/workflows/build-extension-charts.yml

- missing input `tagged_release: ${{ github.ref_name }}` for job
- remove `push` and `pull` triggers and replace with `release:  types: [released]` (keep `workflow_dispatch`)
- `uses` should target `release-2.8` branch

**release-2.9** 
https://github.com/rancher/dashboard/blob/release-2.9/creators/extension/app/files/.github/workflows/build-extension-charts.yml

- missing input `tagged_release: ${{ github.ref_name }}` for job
- `uses` should target `release-2.9` branch

**master** - https://github.com/rancher/dashboard/blob/master/creators/extension/app/files/.github/workflows/build-extension-charts.yml

- missing input `tagged_release: ${{ github.ref_name }}` for job

https://github.com/rancher/dashboard/blob/master/creators/extension/app/app.package.json

- update dependencies and resolutions so that the output is:
```
"dependencies": {
    "@rancher/shell": "^3.0.0"
  },
  "resolutions": {
    "@types/node": "~20.10.0",
    "@types/lodash": "4.17.5"
  },
```

After this, create releases for all creators package versions

**Comment by richard-cox** [comment]
Here's a few other strange related to creators things i picked up (WIP)

- when using the ext creator it provided the wrong `catalog.cattle.io/rancher-version` (in 2.10 it was setting 2.9.3)
