### ISSUE TITLE
Look at gating mechanism so that Elemental 2.0.0 doesn't run in Rancher 2.10

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12631]
Look at gating mechanism so that Elemental 2.0.0 doesn't run in Rancher 2.10. User reported this problem, which breaks their system.

Workaround is to use [safemode](https://extensions.rancher.io/extensions/next/advanced/safe-mode) if Rancher get's "stuck" and not running

**Comment by gaktive** [comment]
There's one report from the community of trying to run Elemental 2.0.0 in Rancher 2.10.0 today so folks are hitting this.

**Comment by richard-cox** [comment]
Update to https://github.com/rancher/dashboard/issues/12631#issuecomment-2488271910

Fix needs to cover two scenarios
- Already installed elemental
  - 2.10.0 timeframe - Release information on how to remove plugin (/safemode or by deleting resource/s)
  - 2.10.1 timeframe - Gonnna backtrack on https://github.com/rancher/dashboard/issues/12631#issuecomment-2488271910, we would need to put in an if rancher 2.10 and elemental and version 2.0.0 blocker in dashboard code
- Preventing new elemental installs
  - Need to release 2.0.1 with the correct annotation 
  - Should also double check 1.x, and other plugins (including examples)

**Comment by aalves08** [comment]
Waiting for Elemental QA to test `elemental-2.0.0-rc.3` and `elemental-3.0.0-rc.3` to get the sign-off to release `2.0.0`, `2.0.1` and `3.0.0`

**Comment by aalves08** [comment]
closing this issue since the new versions of Elemental have been released and the action points have been communicated to the stakeholders and general public
