### ISSUE TITLE
[BUG] Cannot Enable Harvester UI Extension Rancher v2.10.0

### ISSUE THREAD

**Issue by wstutt** [rancher/dashboard#12634]
**Rancher Server Setup**
- Rancher version: v2.10.0
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2

**Information about the Cluster**
- Kubernetes version: v1.30.6
- Cluster Type (Local/Downstream): Local
   

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin

**Describe the bug**
Enabling Harvester-UI extension does not result in an available extension .

**To Reproduce**
Install Fresh Rancher Manager
Add Harvester Repository as a Git repository in Apps -> Repositories (https://github.com/harvester/harvester-ui-extension)
Go to Extensions -> All 
Go to Virtualization Management -> (Cannot Be enabled)

**Result**
Extension is not available
Cluster cannot be imported

**Expected Result**
Expect to have a UI extension
Expect to be able to import cluster

**Comment by gaktive** [comment]
Need to check if https://github.com/rancher/dashboard/issues/12592 shows the same behaviour as we have console logs there.

**Comment by gaktive** [comment]
Might also be waiting on https://github.com/rancher/dashboard/issues/12347

**Comment by adonskoy** [comment]
I have a similar issue after updating from 2.9.3. Repo is added, but no extension is shown on Available tab and no errors in the console

**Comment by wstutt** [comment]
Not the exact same bug as #12592 - the extension doesn't show up at all when using 'main' branch for the ui plugin.   If I use the 'release-test' branch, the console error exhibits itself.

**Comment by socheatsok78** [comment]
Add the extension using `http` target and `https://harvester.github.io/harvester-ui-extension/` index url.

<img width="928" alt="image" src="https://github.com/user-attachments/assets/610c3fa6-3ba2-4b1f-9b4f-88d5efa0eab8">

**Comment by wstutt** [comment]
using https, exhibits the same symptoms as #12592 
![image](https://github.com/user-attachments/assets/aea98088-6c77-4021-a70e-d95b1e7a29ee)

**Comment by nwmac** [comment]
The instructions have been updated here: https://github.com/harvester/harvester-ui-extension?tab=readme-ov-file#installation - please try those and update if you are still having issues.

**Comment by wstutt** [comment]
Still same symptoms while using:
```
For Git Repo URL, enter https://github.com/harvester/harvester-ui-extension
For Git Branch, enter gh-pages
```
![image](https://github.com/user-attachments/assets/00646e76-f007-4058-9509-a97ba4eb43c2)

and virtualization management looks like this:
![image](https://github.com/user-attachments/assets/06320408-ae16-4f5b-8944-dd7a8d30a0d9)

Rolling back from 1.0.1 to 1.0.0 seems to have given me a dashboard

![image](https://github.com/user-attachments/assets/ee005afe-2278-4e7f-8b45-af169125508a)

![image](https://github.com/user-attachments/assets/56fd4cc0-41d0-4d95-9cae-20dda8af3eed)

And then when I update back to 1.0.1 I get the following Fail Whale:

![image](https://github.com/user-attachments/assets/b8d29d90-5ea0-4d84-b6ae-bf538e60d38e)

So for my personal usage, I will use 1.0.0 until 1.0.1 is fixed, but I think the bug remains.

**Comment by wstutt** [comment]
My issue has been resolved with the updates to the documentation and the removal of the 1.0.1 release.
