### ISSUE TITLE
Port section of Deployment missing hostIP for port with host.  Will need new styling to fit extra field

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1264]
Issue:  Adding host port to the Port section of deployments should have a field for Host IP\

Current:
![image](https://user-images.githubusercontent.com/11514927/93408112-9cc96700-f848-11ea-814d-d22fe5660699.png)

Resolution:  Maybe we can make it look & function like Environment Variable Add.  So then you can Style the two different types and add the two extra fields without trying to crunch them into small space.  Example:

![image](https://user-images.githubusercontent.com/11514927/93407942-3d6b5700-f848-11ea-8007-a283d1227250.png)

**Comment by deniseschannon** [comment]
I like the suggestion of changing the button to handle the 2 scenarios esp  as the private container port box doesn't need to be so long (it's only long today cause of the link to show host ports. 

From my understanding, host port isn't a common use case so we can look into this post 2.5 as this could be edited in yaml if someone wants to do it.

**Comment by tfiduccia** [comment]
@lvuch New ideas - https://xd.adobe.com/view/2a34d99a-8bd6-4d5d-b0f8-202b29a3fc55-7f67/ XD file name: template for detail pages.

**Comment by lvuch** [comment]
<img width="869" alt="Screen Shot 2020-10-13 at 9 42 23 AM" src="https://user-images.githubusercontent.com/3013118/95890314-76f48c80-0d38-11eb-8578-eaaab89850c7.png">
<img width="871" alt="Screen Shot 2020-10-13 at 9 42 14 AM" src="https://user-images.githubusercontent.com/3013118/95890318-778d2300-0d38-11eb-8266-1861e808994f.png">
<img width="844" alt="Screen Shot 2020-10-13 at 9 42 04 AM" src="https://user-images.githubusercontent.com/3013118/95890321-7825b980-0d38-11eb-8645-16c977db410c.png">

**Comment by tfiduccia** [comment]
Verified fixed
