### ISSUE TITLE
Harvester extension, Prime version

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#12641]
**Is your feature request related to a problem? Please describe.**

We want to add Harvester extension in the Rancher Prime catalog.

**Describe the solution you'd like**

Add the Harvester extension [repository](https://github.com/harvester/harvester-ui-extension) in the Rancher official catalog to be available for Prime users and provide the docker image for air-gap environments.

**Describe alternatives you've considered**

**Additional context**

**Comment by gaktive** [comment]
@aalves08 mentioned that there's work underway for this with a PR.

**Comment by rancher-max** [comment]
We can do a quick manual test on this issue as it doesn't appear that we have explicit automated validations.

**Comment by vfaergestad** [comment]
I tested the 3.10 [release](https://github.com/rancher/ui-plugin-charts/releases/tag/3.1.0), but am not able to get harvester as an option under "Available extensions" in my rancher UI. I have verified that the service deployed actually serves the relevant files.

Anyone with any ideas for further troubleshooting? Or anyone who have been able to valide it on their side?

**Comment by torchiaf** [comment]
@vfaergestad Rancher 2.10.1 has a breaking change for Harvester extension 1.0.0, so it would be not compatible with it.

**Comment by rancher-max** [comment]
Closing as this was validated in dev by forcing `prime` to `true` in UI code. There is no Prime yet for v2.10.x so cannot validated e2e at this time.

**Comment by IsaSih** [comment]
Validated in v2.10-87b97590837835650d045937b669ee0206604758-head mocked rancher prime
