### ISSUE TITLE
Improve / Fix Extension 2.10 Migration 

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12656]
https://extensions.rancher.io/extensions/next/rancher-2.10-support#how-to-proceed-with-your-extension-update

Docs
- After migration tool
  - Missing step to update local node version to  20 <= local node <= 22
  - Missing step to do a yarn install 
  - Add info on changing TS components that import JS components typing
    - for example `component: { Loading }` needs to be  `component: { Loading } --> as any`

Functional
- After running migration tool
  -  i got a lot of build errors that were only resolved by updating root package.json to that matching the elemental-ui root package.json

**Comment by aalves08** [comment]
Created an issue for the documentation in separate: https://github.com/rancher/dashboard/issues/12747

**Comment by aalves08** [comment]
Testing for this will be covered by https://github.com/rancher/dashboard/issues/12752
