### ISSUE TITLE
Add additional files to type definitions created for extensions

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12652]
- TS based files in extensions will fail to build if they reference 
  - '@shell/mixins/resource-fetch'
  - '@shell/plugins/steve/steve-class'
- These should be added to type-gen file shell/scripts/typegen.sh

**Comment by aalves08** [comment]
This is covered by the `check-plugins-build` that is covered in every PR (it does the typegen and publishes it) https://github.com/rancher/dashboard/actions/workflows/check-plugins.yaml
