### ISSUE TITLE
Vue3 Migration tool adds incorrect annotation, blocking app from loading

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12655]
**Setup**
- Rancher version: 2.10.0

**Describe the bug**
- Using the migration tool will update the extensions package.json annotations 
- However it uses the wrong value, which means the dashboard will ignore it and assume the extension is not compatible with vue3 world
  - Adds `catalog.cattle.io/ui-extension-version`
  - Should add `catalog.cattle.io/ui-extensions-version`
  - See creators/extension/migrate/tasks/packageUpdates.js

**To Reproduce**
- create a 2.9 ext
- run the migration tool (see https://extensions.rancher.io/extensions/next/rancher-2.10-support#how-to-proceed-with-your-extension-update for details)

**Result**
- pkg/<x>/package.json contains incorrect annotation `catalog.cattle.io/ui-extension-version` 

**Expected Result**
- pkg/<x>/package.json contains incorrect annotation `catalog.cattle.io/ui-extensions-version`

**Comment by aalves08** [comment]
updated milestone because this need to go into `master`
