### ISSUE TITLE
RKE2 Clusters are incorrectly treated as imported clusters while they are provisioning

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#12662]
![image](https://github.com/user-attachments/assets/c5a6c82b-682e-434f-af39-7e258b20e260)

Early investigation: The `provider` column is determined by management cluster status.provider and status.driver - it looks like driver is not populated until the cluster finishes provisioning. We probably need a better way of  computing the mgmt cluster `provider` 

Need to ensure we don't re-introduce 
https://github.com/rancher/dashboard/issues/12506
https://github.com/rancher/dashboard/issues/12339

**Comment by a-arias** [comment]
**TESTS**

Version: v2.11.0

The issue still present when creating the cluster for the first time on amazon EKS 

<img width="1704" alt="amazon-eks-bug-for-1-sec" src="https://github.com/user-attachments/assets/714b7584-412a-495c-9b69-a5e50587722c" />

**Comment by mantis-toboggan-md** [comment]
> **TESTS**
> 
> Version: v2.11.0
> 
> @mantis-toboggan-md The issue still present when creating the cluster for the first time on amazon EKS


I was able to reproduce this as well, though I only see imported/imported for 15-20 seconds then its updated to Amazon EKS; does that line up with what you've seen @a-arias?


I checked what the API is sending us before the provider/distro display corrected itself. It looks like the status fields we (partly) rely on to determine provider/distro are not populated for a small window in the provisioning process (small relative to how long EKS clusters take to come up). I think fixing this issue would involve a major major rework of the logic around that table column, which we are finding to be awful to do without causing regressions. I have also confirmed that this issue is present in 2.8-head so I think it is not a recent regression. Given that, on top of the complexity of fixing the issue and the briefness in which its shown I suggest that we track this bug in a new issue and re-evaluate if it needs to be backported to 2.10.x as the current issue has been.

**Comment by mantis-toboggan-md** [comment]
I've filed a new issue for that bug here https://github.com/rancher/dashboard/issues/12883 as well as a tech debt issue to look into making this code less challenging to maintain: https://github.com/rancher/dashboard/issues/12882

**Comment by a-arias** [comment]
**TESTS**

Version: v2.11.0

Fix validated on 2.11 version  ✅ 
A new ticket will be created for the issue mentioned above 


<img width="1704" alt="Screenshot 2024-12-13 at 3 48 23 PM" src="https://github.com/user-attachments/assets/a70d7b3a-0a07-4376-8e6d-f172ff70a333" />


<img width="1704" alt="amazon-eks-bug-for-1-sec" src="https://github.com/user-attachments/assets/d849bf39-8352-469f-9d9e-92417162af1e" />

**Comment by eva-vashkevich** [comment]
I think this is caused by this https://github.com/rancher/dashboard/blob/13632bea2213eab25d8439e9e4c67204f685950a/shell/models/management.cattle.io.cluster.js#L94 line. But I think we need to look into it more holistically first, because changing this might have a lot of side effects
