### ISSUE TITLE
Namespace not removed from list after delete

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1266]
Steps:
1. Create a namespace named "abc"
2. Click on the Namespace's menu and select delete from the menu
3. Confirm and delete the namespace

Result:
Namespace page doesn't update and looks like "abc" is still there.  If I try to edit it or anything I get an error page, cause it doesn't really exist.
![image](https://user-images.githubusercontent.com/11514927/93408838-62f96000-f84a-11ea-8263-1e388160073f.png)

Additional issue:
After I refresh the namespace is removed from my list, but if I create a new one, they come back in a terminating state and i can once again access the menu which throws errors
![image](https://user-images.githubusercontent.com/11514927/93409057-e1560200-f84a-11ea-9387-6aaeaddfe6e4.png)

**Comment by deniseschannon** [comment]
Closing in favor of the umbrella issue of change events not working reliably.
