### ISSUE TITLE
I can  Create on namespace with no name, but namespace is created.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1267]
Steps:
1.  Go to create namespace
2.  Click create

Results:  Takes you back to namespace list page but no namespace is created.  Name is a required field for Namespace.  Here is response error in console:

type":"error","links":{},"code":"Invalid","message":"Namespace \"\" is invalid: metadata.name: Required value: name or generateName is required",

**Comment by codyrancher** [comment]
I just checked in master and this is no longer possible so I'm moving to test.

![Screen Shot 2020-09-28 at 10 54 02 AM](https://user-images.githubusercontent.com/55104481/94468282-061a7580-0179-11eb-8c19-6622afe89f16.png)

**Comment by tfiduccia** [comment]
Fixed
