### ISSUE TITLE
Cancel/Create buttons on bottom are in different places for YAML/Form create

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1268]
The Cancel & Create buttons for Create as Yaml & Create as Form should be in same place.  We should be consistent.

- [ ] Buttons are always on bottom with Yaml and they float up with form - Duplicate: https://github.com/rancher/dashboard/issues/1074
 
- [ ] Create button all the way on Left & Create is all the way on Right

YAML:
![image](https://user-images.githubusercontent.com/11514927/93409576-0ac35d80-f84c-11ea-8fc4-3a11a7149566.png)

Form
![image](https://user-images.githubusercontent.com/11514927/93409475-d94a9200-f84b-11ea-9fba-48b1beaca68f.png)

Fix:  Personally I like the Cancel/Create centered... mostly because if I don't have the tabbed box above Cancel and I just have fields.. then Cancel gets lost and is hard to find.

**Comment by deniseschannon** [comment]
@lvuch what do you think we should do for both layouts?

**Comment by deniseschannon** [comment]
Seems like the buttons are all now right aligned for Create from form and create from yaml.

**Comment by tfiduccia** [comment]
Fixed
