### ISSUE TITLE
Fix e2e tests following the removal of the Restricted Admin role

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12689]
**Setup**
- Rancher version: `2.11-head`
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

- Our e2e tests are failing on the `auth` part: https://github.com/rancher/dashboard/actions/runs/12036272266/job/33593793662?pr=12681

Seems the culprit is the removal of the `Restricted Admin` role
<img width="2175" alt="Screenshot 2024-11-27 at 11 56 09" src="https://github.com/user-attachments/assets/41d16440-2a70-4d5b-ab1d-515e3cb632a8">
<img width="2175" alt="Screenshot 2024-11-27 at 11 56 04" src="https://github.com/user-attachments/assets/555563c0-adcd-4e5f-ab1f-5e24a6e5dd0e">

**To Reproduce**

**Result**
- pipeline is failing

**Expected Result**

- pipeline should succeed

**Screenshots**

**Additional context**

- seems that the backend has done the removal of the `Restricted Admin` role

**Comment by yonasberhe23** [comment]
@aalves08 should this warning be removed from the Role Templates list page? 
![image](https://github.com/user-attachments/assets/ef4817a9-5d1c-4dee-8760-16aab3280fd0)

**Comment by aalves08** [comment]
This should have been removed with https://github.com/rancher/dashboard/pull/12708 @yonasberhe23

**Comment by yonasberhe23** [comment]
ah okay, thanks @aalves08. i'll track this in that ticket then. closing this out
