### ISSUE TITLE
Delete modal - Add Node to add/confirm the node name to the modal when deleting

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1269]
Node:
![image](https://user-images.githubusercontent.com/11514927/93409876-ba003480-f84c-11ea-9ac7-8d0756a9d3d8.png)

Namespace:
![image](https://user-images.githubusercontent.com/11514927/93409921-d13f2200-f84c-11ea-970d-a821557a8324.png)

Seems like Node would be pretty important?  What is the determining factor on what get a confirm?

**Comment by deniseschannon** [comment]
Add `node` to the list of special list of types that need additional confirmations.

**Comment by sadiapoddar** [comment]
Verified on master-head, commit 5da52c0
1. Created a rke cluster from Rancher UI in AWS infra
2. From cluster explorer selected "node" page
3. Selected a node to delete and verified the "Delete Modal" ask to enter the node name to confirm the delete
3. If you provide the right node name, it properly deletes the node from UI and also deleted it from the AWS infrastructure. 

But there is an issue deleting a non-existing node if users provide the non-existent node name in the delete modal. UI shows that they couldn't find a match but the delete button goes to "deleting mode" and get stuck in "deleting" for forever, and doesn't come out from deleting. The only way to come out if the users specifically select "cancel".


Reopening the bug to fix this issue. 
<img width="397" alt="Screen Shot 2020-12-28 at 3 36 46 PM" src="https://user-images.githubusercontent.com/72409237/103249565-b9d00480-4924-11eb-92c4-79c5b19c1bbb.png">

**Comment by sadiapoddar** [comment]
Closing this issue and reopening a new bug for the non-existing node delete issue stated in the previous comment.
