### ISSUE TITLE
Workflow build-extension-charts should fail on wrong tagging

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12718]
Workflow `build-extension-charts` should fail on wrong tagging as per https://github.com/nwmac/rancher-dev-portal/actions/runs/12083482784/job/33696700701.

Look at `parse-tag-name` script to check why it didn't fail + `Run build script` job should have also failed. Both should have thrown meaningful errors and exit properly to "kill" workflow run.

**UPDATE (9-dec-2024):** Solution here is to have `parse-tag-name` fail if tag check is not met. We can't push responsibility to the `publish` script as it needs to be able so skip extension tag matching if it's not met and that happens on purpose, since we can have multiple extensions inside the same repo

**Comment by aalves08** [comment]
Blocked by https://github.com/rancher/dashboard/issues/12824

**Comment by gaktive** [comment]
Moved milestone for related PRs to January releases

@aalves08 do we need a 2.10.x version too? I'm not sure how you're tracking everything in one ticket but I trust you to make sure things land in all the releases :)

**Comment by aalves08** [comment]
😛 we don't need a 2.10 version/fix @gaktive 

We only target the branches right before we've had breaking changes on the `shell` package, which are `release-2.8`, `release-2.9` and `master`. 🙏
