### ISSUE TITLE
[2.8] App made with Rancher Extension 1.2.3 does not show install button

### ISSUE THREAD

**Issue by masap** [rancher/dashboard#12724]
**Setup**
- Rancher version: 2.8.10
- Rancher UI Extensions: 2.8.10
- Browser type & version: Firefox 133.0 (64 bit)

**Describe the bug**

App made with Rancher Extension 1.2.3 and have trailing annotation does not show install button.
```
"catalog.cattle.io/ui-extensions-version": ">= 1.2.3 < 2.0.0"
```

**To Reproduce**

Create Rancher Extension app with the annotation and open Rancher Extension page on Rancher UI.

**Result**
The app does not show install button.

**Expected Result**

The app shows install button.

**Screenshots**

**Additional context**

Workaround is to use trailing annotation.
```
"catalog.cattle.io/ui-extensions-version": ">= 1.2.0 < 2.0.0"
```

**Comment by aalves08** [comment]
This can happen due to several reasons (pending analysis) on your code, but the issue stated here is not the reason why, for sure. This annotation does nothing in Rancher 2.8.x systems.

**Comment by masap** [comment]
Thank you. I will close this.
