### ISSUE TITLE
Workload: Create page issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1274]
Issues:

- [x] I keep accidentally clicking on the blue links in the text thinking it's going to take me to create and instead it takes me out of our application and to more information page.  Suggestion:  Remove links from the text and add "For more Info" link to end of description.  This way customer know they are going to more information and not the create page.
![image](https://user-images.githubusercontent.com/11514927/93433428-a4eeca00-f87b-11ea-9f8f-7f7ec7a9bc3b.png)

- [x] Add DaemonSet & Cronjob to left pane so it matches Create screen

- [x] Make the order of both the left pane & create page match.

In light mode:
The box's shaded background is so light you can barley tell they are boxes and it's not just a white screen.
![image](https://user-images.githubusercontent.com/11514927/93542216-483bef80-f90d-11ea-88d2-9e61ae33afa5.png)

**Comment by deniseschannon** [comment]
Let's use this card to update the styling on workload create cards.

**Comment by deniseschannon** [comment]
Logically the cards should be ordered in this order. 

I'm not sure if it make sense to re-order the side nav to match this. What do you think @vincent99 ?
```
Deployments    CronJob
DaemonSet      Job
StatefulSet 
```

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1426

**Comment by tfiduccia** [comment]
Fixed
