### ISSUE TITLE
App bar icon alignment broken

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#12758]
If you have an extension that uses an image for an icon, the alignment is broken.

This appears to be due to this change: https://github.com/rancher/dashboard/pull/12591

Before: (in 2.10)

![image](https://github.com/user-attachments/assets/ff60f8fe-48bd-47b0-b50d-edd65c0ca8d4)

Now: (in 2.11)

![image](https://github.com/user-attachments/assets/35ded8a7-7037-4eaf-a68d-acf866cffff9)

The css used to have the width set for the image, but now this was moved to only apply if the icon is provided via the icon font.

**Comment by a-arias** [comment]
**TESTS**
Rancher: v2.11-b435a2d786c50b03bd1ba7279a6a621ebcd19c84-head
UI: release-2.10 d5b785b

Fix verified ✅ 

<img width="1360" alt="Screenshot 2024-12-17 at 9 42 26 a m" src="https://github.com/user-attachments/assets/61612b17-67ef-489e-8c2c-ffdbad5f1e32" />
