### ISSUE TITLE
Can't tell which resource I selected from Workload: Create

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1275]
Steps:
1.  Go to Workload: Overview page
2. Click on Create button
3. Select Deployment or any other option

Results:
The top title still says "Workload: Create" instead of "Deployment: Create" so I have no idea what type of resource I'm trying to add.
![image](https://user-images.githubusercontent.com/11514927/93434544-2561fa80-f87d-11ea-9a67-0c839de9c186.png)

**Comment by deniseschannon** [comment]
CruResource needs to be updated to handle the subtype selection and show in masthead. 

Same Issue: https://github.com/rancher/dashboard/issues/1302

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/dashboard/issues/1073
