### ISSUE TITLE
If I cancel out of Workload: Create page, it takes me to Deployment list page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1276]
Steps:
1.  Go to Workload/Overview page
2.  Click on Create
3.  Click on Cancel

Results: I ended up on the Deployment list page.  Should take me back to the Overview list page.

**Comment by deniseschannon** [comment]
From the workload "subtype" select page, direct the URL to the specific CRD instead of workload. 

This will change this workflow so that it'll be clear you are in deployments and cancel out would bring you back to deployments.

**Comment by tfiduccia** [comment]
Not fixed.

@deniseschannon - When I'm on Workload: Create, I'm still on the Overview page.  If I click cancel it should take me back to Overview.  But it always takes me back to the deployment list page
![image](https://user-images.githubusercontent.com/11514927/94525461-f63a7a00-01e8-11eb-89cb-c4ee279a580c.png)

**Comment by tfiduccia** [comment]
Fixed
