### ISSUE TITLE
Once I select a type of resource from the Workload: Create, Focus is still on overview

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1277]
Steps:
1.  Go to workload/overview page
2.  Click on Create
3.  Click on deployment box

Results:  Focus is still on Workload/Overview in left pane.  It should move to Deployments once I make my selection.  Especially since Cancel/Create will take me that list page.  
Or it should take me back to Overview list page and not move me?  then the focus would be correct when I cancel.

**Comment by deniseschannon** [comment]
From the workload "subtype" select page, direct the URL to the specific CRD instead of workload.

**Comment by tfiduccia** [comment]
Fixed
