### ISSUE TITLE
Text under schedule field for cronjob schedule is unreadable

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1279]
Steps:
1.  Go to Cronjob Create page

Results:  Can't read text underneath it, also notice I can invalid data and it doesn't error.
![image](https://user-images.githubusercontent.com/11514927/93436460-afab5e00-f87f-11ea-9a04-494a2e74ef4c.png)
![image](https://user-images.githubusercontent.com/11514927/93436599-dd90a280-f87f-11ea-96c5-597f068e96f9.png)

**Comment by lvuch** [comment]
first issue addressed here: https://github.com/rancher/dashboard/pull/1376, second will need a dev's eyes

**Comment by tfiduccia** [comment]
Fixed
