### ISSUE TITLE
Top Section is missing on Namespace & all resources

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1281]
Steps:
1.  Create a namespace & a deployment
2.  For both add a description & a Label
3.  Create
4.  Go to their detail pages

Results:  Can't see description or label info anywhere.  I thought there used to be a top section?
![image](https://user-images.githubusercontent.com/11514927/93438037-95727f80-f881-11ea-9c66-85bd267873a6.png)
![image](https://user-images.githubusercontent.com/11514927/93438072-9f947e00-f881-11ea-944b-6508b11975cd.png)

**Comment by deniseschannon** [comment]
I see DetailTop today?

![Screen Shot 2020-09-17 at 1.29.15 PM.png](https://zube.io/files/rancher/2791a1000d8c4986aba7972bd4ec932c-screen-shot-2020-09-17-at-1-29-15-pm.png)

![Screen Shot 2020-09-17 at 1.29.35 PM.png](https://zube.io/files/rancher/631282d1231dbdff5dc844399ec02731-screen-shot-2020-09-17-at-1-29-35-pm.png)

**Comment by vincent99** [comment]
I didn't know there was an issue for this but a fix was merged last night

**Comment by tfiduccia** [comment]
Verified fixed
