### ISSUE TITLE
[CIS v2] Deployment Page allows editing existing values, Description is missing

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#1284]
Deploying the `rancher-cis-benchmark` app, lets user change the chart Values.yaml. Also this chart's description value is missing and not pulled from Chart.yaml

<img width="1193" alt="Screen Shot 2020-09-17 at 9 31 47 AM" src="https://user-images.githubusercontent.com/1470602/93504672-aa293480-f8ce-11ea-8987-81f9d127e1e4.png">

**Comment by deniseschannon** [comment]
@prachidamle Are you saying you shouldn't be able to change the values.yaml? 

Where are you saying the description is missing? The actual description is being shown currently and correctly. 

![Screen Shot 2020-09-17 at 12.03.46 PM.png](https://zube.io/files/rancher/ed978fb797719266f90f15f21abf378c-screen-shot-2020-09-17-at-12-03-46-pm.png)

The `Description field` that you see allows the user to add a description to the helm chart app that is being released.

**Comment by prachidamle** [comment]
> @prachidamle Are you saying you shouldn't be able to change the values.yaml?
> 
> Where are you saying the description is missing? The actual description is being shown currently and correctly.
> 
> ![Screen Shot 2020-09-17 at 12.03.46 PM.png](https://camo.githubusercontent.com/78f9011ecc65c800f981479aa8e066fe553a27d2/68747470733a2f2f7a7562652e696f2f66696c65732f72616e636865722f65643937386662373937373139323636663930663135663231616266333738632d73637265656e2d73686f742d323032302d30392d31372d61742d31322d30332d34362d706d2e706e67)
> 
> The `Description field` that you see allows the user to add a description to the helm chart app that is being released.

Oh ok. Then we are good. The empty Description text field made me think that we are not populating this description
