### ISSUE TITLE
[backport 2.9.5] AKS: Unable to upgrade Nodepool's k8s version

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#12860]
**Setup**
Rancher: v2.9-eaafb03a1ed78475258b7523b514168a8d9c8367-head
Dashboard: release-2.9 c2c221a

**Describe the bug**
Unable to upgrade Nodepool kubernetes version. "_A new cluster version has been selected. Once the upgrade has completed, you can come back and upgrade the node pool version_" warning is not getting cleared.

**To Reproduce**
- Provision AKS cluster from Rancher UI
- Upgrade control plane version to new one, valid warning is displayed for Nodepool
- Once the upgrade is finished, edit cluster and try upgrading Nodepool

**Screenshots**

2.9-head:
![image](https://github.com/user-attachments/assets/a6accb73-4c8b-4064-9e2b-28dd53a47a2b)

2.9.3 (as expected):
![image](https://github.com/user-attachments/assets/ea7fc8c0-2383-4fac-9608-4f3896c7e770)

**Comment by izaac** [comment]
Rancher version: `v2.9-811aaa845e17942c94458af87efb4083bee532d2-head`
UI version: `release-2.9 0a69edb`

[The same scenarios ](https://github.com/rancher/dashboard/issues/12861#issuecomment-2537205655)from 2.10 were executed to validate the fix in this version 2.11

> I used an AKS hosted cluster with multiple node pools.
> Selecting a newer k8s version shows the info box as expected regarding the pools update option after update.
> If I select the current version back, the info box is hidden as expected.
> 
> I did two version bumps:
> 
> - Update Kubernetes version. Save
> - Wait until the checkbox is visible in the Edit view.
> - Checked that multiple nodepools have this checkbox visible.
> - Update Pool A and save. Wait for update.
> - Go to edit again after waiting for the upgrade, Pool A is upgraded to the current kubernetes version. The checkbox is hidden.
> - Navigating to Pool B which is still not upgraded has the upgrade checkbox visible and information about the upgrade to version.
> - Check the box save and wait for Pool B to be upgraded.
> - All the pools match the kubernetes versions after the upgrade and going to edit.
> - Previous versions before the current in the Kubernetes versions dropdown are hidden
> 
> ---
> 
> - Next Scenario, version bump, repeat the above.

Closing as validated.

**Comment by skanakal** [comment]
https://github.com/rancher/rancher/issues/48401
