### ISSUE TITLE
Invalid data entered from nodepool SSH Key dropdown when provisioning EKS

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#12877]
**Setup**
- Rancher version: `v2.10-c4944b3ca0b39c474121df9e7ef31f7aff4e4f7a-head` and  dashboard `release-2.10 5218335`
- Browser type & version: any

**Describe the bug**
When provisioning an EKS cluster from Rancher the user can select a ssh-key pair stored on AWS to be added to the node instances within their nodepool. The dropdown menu offers valid key-ids but once it's selected and saved the nodepool is going to be created or updated but it fails and then the error occurs.

**To Reproduce**
Try to provision or edit any EKS cluster and select a ssh-key from the dropdown, then save and check status of the cluster.
![image](https://github.com/user-attachments/assets/74dff3dc-ccda-4aef-8dd5-5ce305c8baa1)

**Result**
It seems instead of the key-id it uses a map structure like `map[CreateTime:2024-12-12T12:47:08.327Z...`
Error from eks-operator:
```
time="2024-12-12T13:10:18Z" level=error msg="error syncing 'cattle-global-data/c-mmmcg': handler eks-controller: error creating nodegroup: operation error EKS: CreateNodegroup, https response error StatusCode: 400, RequestID: cd41cce3-cd4a-45c7-a437-ecabee27dc0a, InvalidRequestException: The key pair 'map[CreateTime:2024-12-12T12:47:08.327Z KeyFingerprint:6b:9b:79:b1:30:d3:68:c1:32:49:6c:a3:08:90:c6:3f:3b:64:4e:40 KeyName:thehejik KeyPairId:key-0eeec448f711ec685 KeyType:rsa Tags:[]]' does not exist, requeuing"
```

**Expected Result**
The provisioning or update should be successful and ssh-key should be added.

**Screenshots**
![image](https://github.com/user-attachments/assets/10a15acd-24d2-440d-ab93-64a51dbe1a37)

**Comment by izaac** [comment]
Rancher version: `v2.11-d224815d7cfbf4194db1ffdfb04676d55d1a2062-head`
UI version: `release-2.10 d5b785b`

This is the same test scope done in the `v2.10` UI validation here. I am adding the sample `nodeGroups` json POST array.

> 
> The public ssh key is correctly formatted in the POST `ec2SshKey` key when creating the EKS cluster.
> Once the cluster is available or while it is still provisioning I am able to see the correct key without anything else just the same string in the POST;s `ec2SshKey`
> 
> The last part is visual as apparently the GET returned by Amazon looks encrypted. 

Closing as validated. ✅ 

```json
"nodeGroups": [
            {
                "desiredSize": 2,
                "diskSize": 20,
                "ec2SshKey": "testkey1",
                "gpu": false,
                "imageId": null,
                "instanceType": "t3.medium",
                "labels": {},
                "maxSize": 2,
                "minSize": 2,
                "nodeRole": "",
                "nodegroupName": "group1",
                "requestSpotInstances": false,
                "resourceTags": {},
                "spotInstanceTypes": [],
                "subnets": [],
                "tags": {},
                "type": "/v3/schemas/nodeGroup",
                "userData": "",
                "version": "1.29"
            },
            {
                "desiredSize": 2,
                "diskSize": 20,
                "ec2SshKey": "testkey2",
                "gpu": false,
                "imageId": null,
                "instanceType": "t3.medium",
                "labels": {},
                "maxSize": 2,
                "minSize": 2,
                "nodeRole": "",
                "nodegroupName": "group2",
                "requestSpotInstances": false,
                "resourceTags": {},
                "spotInstanceTypes": [],
                "subnets": [],
                "tags": {},
                "type": "/v3/schemas/nodeGroup",
                "userData": "",
                "version": "1.29"
            }
        ],
```

**Comment by thehejik** [comment]
Thanks, it is working now for me on `release-2.10 d5b785b`.
