### ISSUE TITLE
Download Yaml and delete buttons are placed on top of "Pods"

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1287]
**On master-head - commit id: `33f755f1`**

- Dashboard --> Create and deploy a deployment
- Go to dashboard details page by clicking on the deployment
- The pods section is seen as:

<img width="662" alt="Screen Shot 2020-09-17 at 2 36 45 PM" src="https://user-images.githubusercontent.com/26032343/93531076-7f050c00-f8f3-11ea-8cf9-71795aa94010.png">

- Select all pods - Download Yaml and delete buttons are seen placed on top of "Pods"
<img width="692" alt="Screen Shot 2020-09-17 at 2 35 53 PM" src="https://user-images.githubusercontent.com/26032343/93531063-7ca2b200-f8f3-11ea-89e5-a295be2fc50a.png">

**Comment by deniseschannon** [comment]
I don't think you should be able to check the pods in the workload detail page. We should remove that column, which would remove the buttons.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f787`**

- Dashboard --> Create and deploy a deployment
- Go to dashboard details page by clicking on the deployment
- Pod section is:

<img width="1426" alt="Screen Shot 2020-09-29 at 8 49 11 AM" src="https://user-images.githubusercontent.com/26032343/94582070-ae3f4580-0230-11eb-9891-15ef950003b8.png">
