### ISSUE TITLE
Issue when clicking on `execute shell` and `view logs` from Pods in deployment details page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1288]
**On master-head - commit id: `33f755f1`**

- Dashboard --> Deployment --> Create
- Create a deployment
- Go to Deployment details page by clicking on the deployment created.
- Click on the ellipsis on the Pod.

<img width="1628" alt="Screen Shot 2020-09-17 at 2 32 57 PM" src="https://user-images.githubusercontent.com/26032343/93531621-60ebdb80-f8f4-11ea-8751-63810351873a.png">

- Click on Execute Shell - Button clear is half seen on the Dashboard
<img width="283" alt="Screen Shot 2020-09-17 at 2 41 54 PM" src="https://user-images.githubusercontent.com/26032343/93531771-9f819600-f8f4-11ea-8176-57f356e842f2.png">

- Click on View logs - Buttons clear, download are half seen on the Dashboard
<img width="399" alt="Screen Shot 2020-09-17 at 2 41 35 PM" src="https://user-images.githubusercontent.com/26032343/93531759-9d1f3c00-f8f4-11ea-91f3-45f70bbc9f71.png">

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f7878cf`**

Original Issue  is still seen

View Logs:
<img width="349" alt="Screen Shot 2020-09-27 at 8 55 45 PM" src="https://user-images.githubusercontent.com/26032343/94389168-f6ad1500-0103-11eb-8751-0231e48e11ff.png">

Exec Shell:
<img width="283" alt="Screen Shot 2020-09-27 at 8 56 00 PM" src="https://user-images.githubusercontent.com/26032343/94389172-f90f6f00-0103-11eb-841d-d5ba51b73207.png">

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f787`**

**Exec shell:** -- as expected
<img width="483" alt="Screen Shot 2020-09-29 at 8 44 06 AM" src="https://user-images.githubusercontent.com/26032343/94581558-15a8c580-0230-11eb-8aea-ceb8591a121c.png">

**View logs:**
<img width="1637" alt="Screen Shot 2020-09-29 at 8 43 31 AM" src="https://user-images.githubusercontent.com/26032343/94581629-23f6e180-0230-11eb-8361-0a3939396601.png">

There is too big space below the buttons download.
Also the dropdown for `test` as seen in the snapshots do not do anything. 
Questions: 
- What is dropdown on `test` expected to do ? 
- When is `Follow` enabled ?

Reopening because of these issues ^^

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1512

**Comment by sowmyav27** [comment]
**On master-head - commit id: `d4b3bc899`**

These issues exist

Reopening the issue.

**Comment by lvuch** [comment]
resolved here: https://github.com/rancher/dashboard/pull/1571/commits/015d6272a9bba883c6113825703e8223846141e3

**Comment by vincent99** [comment]
The fix in #1512 was..not good, but I fixed it yesterday.

**Comment by sowmyav27** [comment]
Verified on 2.5.0-rc7 and setting v3/settings/ui-offline-preferred  to false

- View logs and Exec shells look good
<img width="225" alt="Screen Shot 2020-10-04 at 7 10 04 AM" src="https://user-images.githubusercontent.com/26032343/95017891-bae8e280-0610-11eb-995a-b0ad3f6a4663.png">
<img width="409" alt="Screen Shot 2020-10-04 at 7 09 38 AM" src="https://user-images.githubusercontent.com/26032343/95017892-bc1a0f80-0610-11eb-94b0-c1a7fe73bff5.png">
