### ISSUE TITLE
Value seen selected in protocol dropdown is incorrect

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1291]
**On master-head - commit id: `33f755f18`**

- Dashboard --> Workloads --> Deployments -->Create deployment --> Add Port
- Protocol dropdown has default value TCP
- Click on the protocol dropdown and select UDP
- Click on protocol dropdown again
- Value seen selected in protocol dropdown is TCP

<img width="383" alt="Screen Shot 2020-09-17 at 3 12 22 PM" src="https://user-images.githubusercontent.com/26032343/93534080-3a7c6f00-f8f9-11ea-86e6-60f749a0e1b3.png">

**Comment by deniseschannon** [comment]
This is part of the generic upstream dropdown component that we use

**Comment by sadiapoddar** [comment]
Reproduced the issue 2.5-head, 
Steps: 
1. From Dashboard --> Deployments -->Create deployment --> Add Port
2. Select UDP protocol
3. If you click the drop-down menu, TCP is high lighted as a select protocol
<img width="1169" alt="Screen Shot 2020-11-05 at 6 29 07 PM" src="https://user-images.githubusercontent.com/72409237/98319175-09cdc300-1f95-11eb-9bad-8c2f6171a3ae.png">

**Comment by sadiapoddar** [comment]
Tested with 2.5-head, commit v2.5-3d7ffc9
steps

1. From Dashboard --> Deployments -->Create deployment --> Add Port
2. Select UDP protocol
3. If you click the drop-down menu, UDP is highlighted as a select protocol

The fix looks good.
<img width="1585" alt="Screen Shot 2020-12-11 at 4 37 48 PM" src="https://user-images.githubusercontent.com/72409237/101968478-4912b380-3bd4-11eb-8c6c-524bb27ccc55.png">
