### ISSUE TITLE
MFA for the rancher account

### ISSUE THREAD

**Issue by gramabaja12** [rancher/dashboard#12940]
Hello, is there a way to enable MFA on rancher? Because I have looked at ways and nothing seems possible.

Thank you,

**Comment by eva-vashkevich** [comment]
Hi,
Please consult https://www.suse.com/support/kb/doc/?id=000020095 for information on Authentication.
For general configuration questions, we recommend using [Slack](https://rancher-users.slack.com/archives/C3ASABBD1).
