### ISSUE TITLE
Description is not being posted for any Resources if you Add an Annotation

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1294]
Steps (open Console):
1.  Go to any Resource create - I tried Deployments, DaemonSets & Cronjobs
2.  Put in Name, Description, Image & a Annotation in that order.  (I use foo=bar for annotation)
3.  Create

Results: The Description is not being passed in.  The post isn't including the description which should be passed as an annotation through the metadata.
Post without an annotation:
![image](https://user-images.githubusercontent.com/11514927/93543466-81299380-f910-11ea-8f2a-0dec696f8bb4.png)

Post with an annotation:
![image](https://user-images.githubusercontent.com/11514927/93543406-5b03f380-f910-11ea-90f4-33fdb1552ec7.png)

**Comment by mantis-toboggan-md** [comment]
It looks like this got fixed ~a week ago as part of some other workload fixes.

**Comment by tfiduccia** [comment]
Fixed
