### ISSUE TITLE
Need suggestion text for Schedule field in Cronjob

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1295]
Issue:
In Cronjob: Create, there is a schedule field but I have no idea what format I should write that in.  Suggestion text would be nice.

![image](https://user-images.githubusercontent.com/11514927/93543739-39573c00-f911-11ea-997a-4e6e43c1b093.png)

**Comment by deniseschannon** [comment]
In ember UI, we were able to have an text in the box and based on how you changed it, it would change what it interpreted: 

It started with `0 * * * *`, but if the value of the text box changed, the helper text below it would change. It would be nice if we could this same type of behavior in.

![Screen Shot 2020-09-21 at 4.48.27 PM.png](https://zube.io/files/rancher/70194a14441e2a58586ab4f2405312bf-screen-shot-2020-09-21-at-4-48-27-pm.png) 

![Screen Shot 2020-09-21 at 4.47.37 PM.png](https://zube.io/files/rancher/7e0469568d22217746357269696072cc-screen-shot-2020-09-21-at-4-47-37-pm.png)

**Comment by vincent99** [comment]
@deniseschannon That already exists (though maybe hard to read); what's missing is a placeholder.

![image](https://user-images.githubusercontent.com/753917/93863408-4c9f3a00-fc78-11ea-8908-bd8659163de4.png)

**Comment by deniseschannon** [comment]
Ah! that makes it much easier. 

Let's add in `0 * * * *` as the default text @mantis-toboggan-md

**Comment by tfiduccia** [comment]
Fixed
