### ISSUE TITLE
Can't preview yaml for StatefulSets

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1297]
Steps:
1.  Go to Workload: Overview page
2. Click on Create
3. Click on the StatefulSet box
4.  Click on Preview Yaml

Results:  Nothing happens.  Get a console error:
vue.runtime.esm.js:1888 Error: Unknown schema for

**Comment by deniseschannon** [comment]
Duplicate: https://github.com/rancher/dashboard/issues/921
