### ISSUE TITLE
Ingress Create page UI Issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1301]
- [x] Name field title in Ingress: Create says "%Name%
![image](https://user-images.githubusercontent.com/11514927/93547705-81c72780-f91a-11ea-94aa-7d035eaab861.png)

- [x] "REMOVE" for Path fields focus highlight is huge and hidden by port field.  Should be like other remove field focuses form workload resources:

Ingress:
![image](https://user-images.githubusercontent.com/11514927/93547831-cd79d100-f91a-11ea-98a7-25ac882da5fb.png)
Workload resources:
![image](https://user-images.githubusercontent.com/11514927/93547812-c18e0f00-f91a-11ea-8ebe-fcfc53033ecf.png)

- [x] ADD PATH link should really be an Add Path button like the Add Rule.
![image](https://user-images.githubusercontent.com/11514927/93548023-35c8b280-f91b-11ea-8601-1bee386d9eb4.png)

- [x] ADD HOST link in Certs tab should be button
![image](https://user-images.githubusercontent.com/11514927/93548267-bdaebc80-f91b-11ea-8227-ef942e94b9cb.png)

- [x] Move first Cert selection down to the REMOVE text isn't so close to the X.  
![image](https://user-images.githubusercontent.com/11514927/93548334-dae38b00-f91b-11ea-8348-81730537b137.png)

- [x] Port title disappears  when I select a Target service (Default Backend tab)
Before:
![image](https://user-images.githubusercontent.com/11514927/93549051-542fad80-f91d-11ea-844f-f5c0344632ab.png)

After:
![image](https://user-images.githubusercontent.com/11514927/93549059-5d207f00-f91d-11ea-8714-4fa8a3b856bd.png)
![image](https://user-images.githubusercontent.com/11514927/93549069-627dc980-f91d-11ea-8958-e4227debd62b.png)

**Comment by lvuch** [comment]
needs dev - “Port title disappears when I select a Target service (Default Backend tab)”

**Comment by tfiduccia** [comment]
@codyrancher do you want a separate issue for the port title?  All Lauren's fixes have been verified.

**Comment by codyrancher** [comment]
@tfiduccia if it's more convenient for you that's fine with me. I can update the pr.

**Comment by codyrancher** [comment]
The last issue is resolved in the latest.

However I have noticed some new issues around the rule path Target Service and Port. I think these are being caused by changes made to the underlying components. I think this needs to be addressed across the board and not just within ingress.

**Comment by tfiduccia** [comment]
Fixed - Will do another review of Ingress UI for the issues Cody mentioned and enter in new issue.
