### ISSUE TITLE
After selecting an option in Service: Create, I can't tell what type of service I picked

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1302]
Steps:
1.  Go to Services
2.  Click on Create
3.  Select one of the options

Result:  Tops still says Service: Create and now I have no idea what option I'm actually in.  The image is from ClusterIP create page.
![image](https://user-images.githubusercontent.com/11514927/93549602-8d1c5200-f91e-11ea-962f-424cc8c79ac9.png)

**Comment by deniseschannon** [comment]
Same type of issue: CruResource needs to be updated to handle the subtype selection and show in masthead. 

https://github.com/rancher/dashboard/issues/1275

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/dashboard/issues/1073
