### ISSUE TITLE
Create ClusterIP Port Rules headers are too small and too close to the fields

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1303]
Steps:
1.  Go to Services
2.  Click Create
3.  Select ClusterIP

Results:  In the Define Service Ports section... the Port rules titles (Port Name, Listening Port, etc..) are too small and too close to the input fields.  The font size should be 14px like all the other list of this sort.  And I would move them up so they have the same amount of space as labels/Annotations
Port rules
![image](https://user-images.githubusercontent.com/11514927/93549812-fc924180-f91e-11ea-89ba-03277206a0d8.png)

Label/Annotations
![image](https://user-images.githubusercontent.com/11514927/93549829-09af3080-f91f-11ea-99fc-e8330aa22149.png)

**Comment by lvuch** [comment]
This needs to be converted to not use tables @mantis-toboggan-md

**Comment by deniseschannon** [comment]
related to: https://github.com/rancher/dashboard/issues/742

**Comment by deniseschannon** [comment]
Convert the component for port rules from table to grid

**Comment by tfiduccia** [comment]
Fixed
