### ISSUE TITLE
When the info circle is inside the field, you can't tell what it is.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1304]
how to find one:
1.  Go to services
2.  Click on Create
3.  Select ClusterIP
4.  Go to Listener IPs

Results:  there is a small circle with a dot in it on the very right of the Cluster IP box.  It's actually supposed to be the more info circle.  It's pretty much unrecognizable.

![image](https://user-images.githubusercontent.com/11514927/93550087-84784b80-f91f-11ea-8aec-acced17424d5.png)

**Comment by tfiduccia** [comment]
@lvuch Info circle should be next to the text on the left?

**Comment by lvuch** [comment]
bubble should probably be just to the right of the label but as it is marked up now that may be difficult to do

**Comment by tfiduccia** [comment]
closing
