### ISSUE TITLE
Longhorn - Overview page

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1306]
Need a button on the overview page pointing to the the longhorn UI

**Comment by deniseschannon** [comment]
@yasker Can you provide the link of how to get to the Longhorn UI after it's been deployed?

**Comment by yasker** [comment]
https://rancher-master/k8s/clusters/c-54lmp/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/

**Comment by deniseschannon** [comment]
Let's make it look similar to Istio:

![Screen Shot 2020-09-25 at 3.26.33 PM.png](https://zube.io/files/rancher/69a6441d04e00fe5af6a66731c7cb977-screen-shot-2020-09-25-at-3-26-33-pm.png)

**Comment by deniseschannon** [comment]
@yasker we're going to have space to add some text to describe the link. Can you provide some?

**Comment by yasker** [comment]
You meant something like `Cloud-Native distributed storage for Kubernetes`?

**Comment by deniseschannon** [comment]
The box will end up looking like this: ![Screen Shot 2020-09-25 at 3.54.53 PM.png](https://zube.io/files/rancher/0aeba64e18847619a7bf1983709e6f35-screen-shot-2020-09-25-at-3-54-53-pm.png)

**Comment by westlywright** [comment]
@deniseschannon I have not updated the link box styles for this page so they match the current link box styles. We should probably update all link boxes at the same time so we can keep it consistent.

**Comment by deniseschannon** [comment]
Filed a different issue for the styling for @lvuch so let's get this tested that the URL is working as expected.

**Comment by khushboo-rancher** [comment]
Valdiated with dashboard ```ec04f78```

On clicking link box, the page is navigating to the longhorn UI page correctly.
Also, on clicking ``Longhorn``` URL the page is navigating to the git longhorn repo.

<img width="382" alt="Screen Shot 2020-09-28 at 11 43 15 AM" src="https://user-images.githubusercontent.com/60111667/94473569-30703100-0181-11eb-8857-362c4001197c.png">

Validated with Chrome and Safari browsers.

**Comment by yasker** [comment]
@khushboo-rancher This logo is wrong. Why does it look like this? It should be https://github.com/cncf/artwork/blob/master/examples/sandbox.md#longhorn-logos

**Comment by yasker** [comment]
Saw the style issue tracked at https://github.com/rancher/dashboard/issues/1461 . Close this issue.
