### ISSUE TITLE
OPA- Gatekeeper cannot be upgraded on Rancher upgrade

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#1312]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Provision a cluster in Rancher `v2.4.8`
Navigate to dashboard and install OPA
Upgrade Rancher to `master-head`
Navigate to apps -> rancher-gatekeeper-operator:v2 -> Upgrade OPA
![Screen Shot 2020-09-18 at 4 57 45 PM](https://user-images.githubusercontent.com/57409052/93653992-3ff8b880-f9d0-11ea-873d-16001589ffc9.png)

**Result:**
Chart not found:
![Screen Shot 2020-09-18 at 4 34 52 PM](https://user-images.githubusercontent.com/57409052/93653246-e93daf80-f9cc-11ea-8086-bea83af63aa9.png)
Trying to install OPA `v3.1.0 from the charts fails because of existing resources:
![Screen Shot 2020-09-18 at 4 59 43 PM](https://user-images.githubusercontent.com/57409052/93654024-628ad180-f9d0-11ea-87a1-361971dc8bf3.png)
```
helm --debug install --create-namespace=true --namespace=cattle-gatekeeper-system --timeout=10m0s --values=/home/shell/helm/values-rancher-gatekeeper-crd-v3.1.000.yaml --version=v3.1.000 --wait=true rancher-gatekeeper-crd /home/shell/helm/rancher-gatekeeper-crd-v3.1.000.tgz
install.go:172: [debug] Original chart version: "v3.1.000"
install.go:189: [debug] CHART PATH: /home/shell/helm/rancher-gatekeeper-crd-v3.1.000.tgz
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "configs.config.gatekeeper.sh" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher-gatekeeper-crd"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-gatekeeper-system"
helm.go:94: [debug] CustomResourceDefinition "configs.config.gatekeeper.sh" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher-gatekeeper-crd"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-gatekeeper-system"
rendered manifests contain a resource that already exists. Unable to continue with install
helm.sh/helm/v3/pkg/action.(*Install).Run
/home/circleci/helm.sh/helm/pkg/action/install.go:275
main.runInstall
/home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
/home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
/home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
/usr/local/go/src/runtime/proc.go:203
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1373
```
Deletion of the old version of OPA also fails:
![Screen Shot 2020-09-18 at 4 40 36 PM](https://user-images.githubusercontent.com/57409052/93653444-bea02680-f9cd-11ea-8ad5-0ee84bce23db.png)
![Screen Shot 2020-09-18 at 4 41 15 PM](https://user-images.githubusercontent.com/57409052/93653449-c8c22500-f9cd-11ea-84b8-9f3fa086cc8d.png)

**Environment information**
- Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): `rancher\rancher:master-head` `version 8fd81a9`
- Installation option (single install/HA): HA

**Comment by deniseschannon** [comment]
We do not expect users to be able to upgrade from one version of OPA to another.
