### ISSUE TITLE
OPA- Unable to create constraint

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#1315]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
From dashboard -> install OPA
Create a constraint from form:
![Screen Shot 2020-09-19 at 11 09 36 AM](https://user-images.githubusercontent.com/57409052/93686063-9f0a0c00-fa68-11ea-9ac3-3a2dbb103a84.png)
Create

**Result:**
User is unable to create constraint:
![Screen Shot 2020-09-19 at 10 47 28 AM](https://user-images.githubusercontent.com/57409052/93686037-75e97b80-fa68-11ea-8558-1812ef924abf.png)
![Screen Shot 2020-09-19 at 11 26 22 AM](https://user-images.githubusercontent.com/57409052/93686419-fa3cfe00-fa6a-11ea-9daa-6c181ebb496b.png)
This behavior is also seen when all parameters and fields are empty

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version db8a864`
- Installation option (single install/HA): HA

**Comment by aaronRancher** [comment]
Refreshing the page will get past this behavior. This error is only seen after navigating to the constraint create page after a fresh install of OPA.

**Comment by codyrancher** [comment]
Because this is occurring in getters and resolved with a refresh I believe this is a syncing issue so I'm reassigning.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version ec04f7878`

Steps:
From dashboard -> install OPA
Without refreshing the page, navigate to OPA Gatekeeper
Create a constraint from form

Result:
Constraint is created and enforced
