### ISSUE TITLE
OPA- Different YAML configs in constraint creation

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#1317]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
From dashboard -> Install OPA Gatekeeper
Create constraint from form
Preview as YAML
Cancel creation
From constraint view, create as YAML

**Result:**
Create constraint from form -> Preview as YAML:
![Screen Shot 2020-09-19 at 12 35 06 PM](https://user-images.githubusercontent.com/57409052/93687850-0a0e0f80-fa76-11ea-8d3a-13ebafba938b.png)

Create constraint from YAML
![Screen Shot 2020-09-19 at 12 34 39 PM](https://user-images.githubusercontent.com/57409052/93687848-08dce280-fa76-11ea-8eaa-dc028e75a4dc.png)
These two YAML configurations are different. Different constraint templates are used by default. Create from form uses k8sAllowedRepos as default. Create from YAML uses k8sRequiredLabels as default.

Should we change these so they use the same configuration?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher\rancher:master-head` `version db8a864`
- Installation option (single install/HA): HA

**Comment by codyrancher** [comment]
I think it should be consistent but it appears to already be consistent for me.

![Kapture 2020-10-19 at 13 51 37](https://user-images.githubusercontent.com/55104481/96510384-4b7b1180-1212-11eb-91ce-e8a88c69a9ae.gif)

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 298a206` and `rancher\rancher:v2.5-head` `version 7d5afc0` 

Create as YAML and Edit as YAML are consistent with template used:
![Screen Shot 2020-10-20 at 3 03 47 PM](https://user-images.githubusercontent.com/57409052/96654271-be0def00-12ef-11eb-9ec2-027492c18a30.png)
Create as YAML
![Screen Shot 2020-10-20 at 3 03 54 PM](https://user-images.githubusercontent.com/57409052/96654274-bf3f1c00-12ef-11eb-8571-78fd76107315.png)
Edit as YAML
![Screen Shot 2020-10-20 at 4 22 17 PM](https://user-images.githubusercontent.com/57409052/96654933-35904e00-12f1-11eb-8db5-bf1f864307f4.png)
