### ISSUE TITLE
App upgrade fails due to incorrect release name

### ISSUE THREAD

**Issue by bmdepesa** [rancher/dashboard#1321]
rancher/rancher:v2.5.0-alpha4

* Create a cluster
* Navigate to dashboard and install Istio - any version 
* After Istio is installed, attempt to upgrade either to the same version with a values change, or to a newer version
* The upgrade fails saying it can't find a matching release name (this was previously working)
```
helm --debug upgrade --history-max=5 --namespace=istio-system --timeout=10m0s --values=/home/shell/helm/values-rancher-istio-1.7.100.yaml --version=1.7.100 --wait=true sh.helm.release.v1.rancher-istio.v1 /home/shell/helm/rancher-istio-1.7.100.tgz
--
Sun, Sep 20 2020 8:24:02 am | upgrade.go:121: [debug] preparing upgrade for sh.helm.release.v1.rancher-istio.v1
Sun, Sep 20 2020 8:24:02 am | Error: UPGRADE FAILED: "sh.helm.release.v1.rancher-istio.v1" has no deployed releases
Sun, Sep 20 2020 8:24:02 am | helm.go:94: [debug] "sh.helm.release.v1.rancher-istio.v1" has no deployed releases
```
* The release name on the fresh installs is: 
```
"releaseName":"rancher-istio"
```
* In this upgrade request (`v1/catalog.cattle.io.clusterrepos/rancher-charts?action=upgrade`)
```
"releaseName":"sh.helm.release.v1.rancher-istio.v1"
```

This also occurs for monitoring with the same incorrect release name format

**Comment by sowmyav27** [comment]
**On master-head - commit id: `9addfe29`**

- Deploy logging app v2 in dashboard
- upgrade app from 3.4.0 to 3.6.0
- Error seen

```
helm --debug upgrade --history-max=5 --namespace=cattle-logging-system --timeout=10m0s --values=/home/shell/helm/values-rancher-logging-crd-3.6.000.yaml --version=3.6.000 --wait=true sh.helm.release.v1.rancher-logging-crd.v2 /home/shell/helm/rancher-logging-crd-3.6.000.tgz
upgrade.go:121: [debug] preparing upgrade for sh.helm.release.v1.rancher-logging-crd.v2
Error: UPGRADE FAILED: "sh.helm.release.v1.rancher-logging-crd.v2" has no deployed releases
helm.go:94: [debug] "sh.helm.release.v1.rancher-logging-crd.v2" has no deployed releases
```
- In "Recent Operations" tab in Dashboard --> Apps the app is seen having `Exit code 123`
<img width="907" alt="Screen Shot 2020-09-20 at 7 06 32 PM" src="https://user-images.githubusercontent.com/26032343/93728418-bd5d2e00-fb74-11ea-905d-88b5830c5d09.png">

**Comment by bmdepesa** [comment]
rancher/rancher:master-head f1a410a

* Deploy cluster & navigate to dashboard
* Deploy Istio v1.7.1
* After installation, upgrade v1.7.1 -> v1.7.1 with a values change (enable egress gateways for example)
* Upgrade succeeds
* Values contain the correctly applied changes
