### ISSUE TITLE
Edit views: watch for change to underlying resource and apply it instead of sending data that will conflict

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#1324]
When you start editing a resource we currently make a copy of the entire resource at that time and that's what you edit.  

The normal flow is:
- User is looking at a resource instance "A" (the original copy in the store)
- User clicks edit, a fixed (not live-updating) clone of A is created, call it "B"
- User clicks save
  - Server returns a new copy "C"
  - The "A" copy in the store is updated to match the data in "C"
  - The "B" clone is forgotten

But if the underlying resource is changed by something else (another user, controller, etc), then the "B" copy the user is editing becomes outdated and will be rejected on save (409 conflict).

The edit screen should watch for changes to the resourceVersion of "A" and do something reasonable to "B" so that the user can successfully save.  When "A" changes to a new value "D",
  - Generate a diff of A->D
  - For each changed field in the diff, compare the value in A vs B.
  - If A & B are still the same, the user hasn't updated that value.  Silently update it in B to match D's value.
  - If they are different, update it as above anyway, but warn the user with a growl that [certain field] has been updated on the server and their change to it has been lost. (Or prompt to choose to keep old or new value?)

(related: https://github.com/rancher/dashboard/issues/1250)

**Comment by sowmyav27** [comment]
**On 2.6.2**

- Create a configmap in the downstream cluster
- Edit config map in window 1, and window 2 
- change labels in the Window1 and click Save
- Change annotations in Window2
- `Operation cannot be fulfilled on configmaps "test": the object has been modified; please apply your changes to the latest version and try again` seen in Window2

**On 2.6-head commit id: `e322f8f`**

- Create a configmap in the downstream cluster
- Edit config map in window 1, and window 2 
- change labels in the Window1 and click Save
- Change annotations in Window2 and click Save
- Changes are saved

**Comment by gaktive** [comment]
Reference: 3593

**Comment by erSitzt** [comment]
This issue was mentioned as a fix for https://github.com/rancher/rancher/issues/32909
But it seems it is not...
