### ISSUE TITLE
Error seen on navigating to CIS Benchmark tab from top left menu after deploying CIS benchmark

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1339]
**On master-head- commit id: `ed274984`**

- Deploy a hosted EKS cluster
- Navigate to Dashboard --> Apps --> Charts --> Deploy CIS scan benchmark app on the cluster 
- From the top navigation bar, select CIS Benchmarks
<img width="313" alt="Screen Shot 2020-09-21 at 9 50 14 PM" src="https://user-images.githubusercontent.com/26032343/93845104-721a4c80-fc54-11ea-8050-65912f0a6dc9.png">

- Click on Scan --> Create
- Error seen
<img width="938" alt="Screen Shot 2020-09-21 at 9 35 13 PM" src="https://user-images.githubusercontent.com/26032343/93845141-9aa24680-fc54-11ea-82b1-9c8a5e510eae.png">

- On a refresh of the page, error is not seen anymore

**Expected:**
Error should not be seen even without a refresh of the page

**Comment by deniseschannon** [comment]
@mantis-toboggan-md I don't think this is anything directly with CIS but the bigger general issues with refresh that we have.

**Comment by deniseschannon** [comment]
Closing in favor of the umbrella issue of change events not working reliably.
