### ISSUE TITLE
User is navigated to the cluster explorer page when user clicks on Backup Restore on the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1343]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Verified on master-head - commit id: `6a6f13ce`**

- Go to user cluster cluster --> Tools --> Backup Restore, Fleet, OPA gateway, Rio are available
- Clicking on Backup restore navigates user to the cluster explorer page. 

**Explorer Result:**
User should be navigated to the backup restore chart installation page

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head `6a6f13ce`
- Installation option (single install/HA): HA

**Comment by deniseschannon** [comment]
From the ember UI, the link goes to `https://<mysetup>/dashboardc/local/backup` but it doesn't go to the deploy page if it's not installed. 

It should mimic what is happening in monitoring: https://github.com/rancher/dashboard/blob/master/pages/c/_cluster/monitoring/index.vue

The test cases are:

1. Hit the link when backup/restore app hasn't been installed yet - direct to the app deployment page in dashboard to deploy backup and restore operator
2. Hit the link when backup/restore app has been installed - direct to the default product page in dashboard for backup and restore operator

**Comment by sowmyav27** [comment]
**On master-head - commit id: `3950b8eab`**

- Deploy a custom rke cluster.
- Navigate to cluster --> Tools --> Backup restore.
- - When backup restore app is NOT installed on the cluster, clicking on Backup restore, takes user to the app deployment page in dashboard to deploy backup and restore operator
- - When backup restore is installed on the cluster, clicking on backup Restore option, takes the user to default product page in dashboard for backup and restore operator
