### ISSUE TITLE
Navigating to `<clusterlink>/logging` in dashboard tries to launch the backup operator instead of logging

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1345]
From @vincent99 when I was poking around all the re-directs from ember to vue.

Logging has the looking (https://github.com/rancher/dashboard/blob/master/pages/c/_cluster/logging/index.vue#L13) but refers to a CHART_NAME variable that doesn't exist (missing in https://github.com/rancher/dashboard/blob/master/config/product/logging.js )

**Comment by izaac** [comment]
Rancher version: `master-head (09/22/2020)` _67e24f2_ k8s HA. With EKS downstream cluster.

I wasn't able to reproduce the issue reported here.
I had the backup operator and rancher logging apps installed in the same cluster and I navigated to each of them using the link directly in the browser address bar. Navigated back and forth from each app .
Used Firefox and Chrome based browsers.
