### ISSUE TITLE
No warning when user deletes default built-in ClusterScanProfiles and clusterScanBenchmark versions

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1347]
**On master-node - commit id: `0ccce450`**

- Login to Dashboard
- Go to Apps and marketplace --> Charts --> Deploy/Install CIS Benchmark v2 
- Navigate to CIS Benchmark (top left dropdown menu) --> Profile 
- Delete a default scan profile available
- Warning seen:

<img width="489" alt="Screen Shot 2020-09-22 at 11 51 32 AM" src="https://user-images.githubusercontent.com/26032343/93924951-476adb00-fcca-11ea-9496-04511a296c80.png">

- Currently we have a generic warning presented when we attempt to delete any default built-in ClusterScanProfiles
- Can we have a separate warning message stating user is trying to delete default built-in ClusterScanProfiles and any further CIS scans might have a problem ? 
- Because in this use-case, where user deletes `rke-cis-1.5-permissive` profile. Run a Cluster scan and choose "default" profile for an RKE cluster, the scan will be in Error state with message: `'Error validating ClusterScanProfile , error: clusterscanprofiles.cis.cattle.io "rke-profile-permissive" not found'`

- Same issue will happen when a user deletes an existing default Benchmark version `'Error validating ClusterScanProfile rke-profile-permissive-2, error: clusterscanbenchmarks.cis.cattle.io "rke-cis-1.5-permissive" not found'`

**Comment by sadiapoddar** [comment]
Reproduced the problem.

1. Login to Dashboard
2. Go to Apps and marketplace --> Charts --> Deploy/Install CIS Benchmark v2
3. Navigate to CIS Benchmark (top left dropdown menu) --> Profile
4. Delete a default scan profile available
5. A generic warning was issued
<img width="1478" alt="Screen Shot 2020-11-05 at 6 09 26 PM" src="https://user-images.githubusercontent.com/72409237/98318381-59ab8a80-1f93-11eb-8033-68c914033efe.png">

After the deletion, all subsequent scan is failing. 
<img width="1018" alt="Screen Shot 2020-11-05 at 6 20 52 PM" src="https://user-images.githubusercontent.com/72409237/98318558-b018c900-1f93-11eb-85d7-73331a6aae14.png">

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `b2953cbc`**

- Warning is available
- related issue - https://github.com/rancher/dashboard/issues/2005
