### ISSUE TITLE
CIS v2 Scans created are not sorted in an order

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1348]
**On master-head - commit id: `0ccce45`**

- Deploy CIS v2 app on the dashboard for a use cluster
- Create few scans
- The scans are not shown in an order on the UI

<img width="1059" alt="Screen Shot 2020-09-22 at 12 08 02 PM" src="https://user-images.githubusercontent.com/26032343/93926639-9fa2dc80-fccc-11ea-89ca-01feab289755.png">

Can we have them sorted maybe in latest created --> first shown ?

**Comment by mantis-toboggan-md** [comment]
It looks like this was fixed here: rancher/dashboard#1437

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f787`**

- Deploy CIS v2 app on the dashboard for a use cluster
- Create few scans
- Scans are sorted in Ascending order of `Last Run`

<img width="1680" alt="Screen Shot 2020-09-28 at 4 31 51 PM" src="https://user-images.githubusercontent.com/26032343/94496090-49d8a380-01a8-11eb-85ed-fddf89fe0405.png">
