### ISSUE TITLE
"Edit as form" opens as "edit as Yaml" for all resources when viewing yaml on detail resource page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1350]
**On master-head - commit id: `0ccce4`**

- Deploy CIS v2 app in Dashboard
- Navigate to CIS benchmarks on the top left menu.
- Go to Profiles
- Click on any. profile
- Select `Yaml` from top right 
- Click on the ellipsis --> `Edit as form`
- Yaml file is seen instead of the form.

**Comment by deniseschannon** [comment]
This is generic to all resources, not just clusterScan or profiles. 

In masthead, if the yaml button is selected and you try to "edit as form", it's coming back in the yaml view instead of the form view.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f787`**

- Deploy CIS v2 app in Dashboard
- Navigate to CIS benchmarks on the top left menu.
- Go to Profiles
- Click on any. profile
- Select Yaml from top right
- Click on the ellipsis --> Edit as form
- Edit as form is seen. Edit a field - profile and save.
- Modified field is saved.
