### ISSUE TITLE
Tests are not sorted in a Cluster scan report

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1351]
**On master-head - commit id: `0ccce4`**

- Deploy CIS v2 app in Dashboard
- Navigate to CIS benchmarks on the top left menu.
- Run scan. Wait for the scan to finish.
- Click on the scan (which might show Pass/fail)
- Scan Report is seen.
- The tests are not sorted. 
<img width="921" alt="Screen Shot 2020-09-22 at 12 39 07 PM" src="https://user-images.githubusercontent.com/26032343/93930141-c0216580-fcd1-11ea-9276-8df253e131b8.png">

**Comment by deniseschannon** [comment]
They are sorted, but in the alphabetical sense where .12 comes before .2

**Comment by vincent99** [comment]
...which is sorted wrong.  This isn't the end of the world but it's lack of attention to detail in plain sight. The rows just need an alternate version of the number that sorts properly on them (e.g. zero-pad each number to several digits wide), and then the table definition to be told to use it.

**Comment by sowmyav27** [comment]
**Verified on 2.5-head - commit id: `9d3882175`**

- Deploy CIS v2 app in Dashboard
- Navigate to CIS benchmarks on the top left menu.
- Run scan. Wait for the scan to finish.
- Click on the scan (which might show Pass/fail)
- Tests are sorted.
<img width="983" alt="Screen Shot 2020-10-20 at 6 39 16 PM" src="https://user-images.githubusercontent.com/26032343/96590414-9de82b00-1303-11eb-811b-937734727ec2.png">
