### ISSUE TITLE
Logging - Outputs/ClusterOutputs - Card changes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1356]
Can we have the provider button styling match closer to the apps & marketplace layout? Specifically around the colored icons on a white background. 

Current Providers:
<img width="574" alt="Screen Shot 2020-09-22 at 2 30 01 PM" src="https://user-images.githubusercontent.com/11410997/93939751-2319f900-fce0-11ea-97a2-3b646d61487c.png">

Apps & Marketplace

<img width="589" alt="Screen Shot 2020-09-22 at 2 30 55 PM" src="https://user-images.githubusercontent.com/11410997/93939833-4ba1f300-fce0-11ea-889d-eb4954158932.png">

**Comment by izaac** [comment]
Rancher version: `master-head (09/26/2020)` _27000be7e_

This now looks consistent with the `Apps & Marketplace` icons style.

![Screen Shot 2020-09-26 at 11 50 00 AM](https://user-images.githubusercontent.com/27659/94348120-9b3d3300-ffee-11ea-9509-89bccf0e9446.png)

![Screen Shot 2020-09-26 at 11 52 16 AM](https://user-images.githubusercontent.com/27659/94348153-c162d300-ffee-11ea-9927-3724b056238d.png)


Checked both Outputs and ClusterOutputs Create forms.
