### ISSUE TITLE
In workload details, checking a pod pops up buttons that are in wrong position

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1360]
Steps:
1.  Create a deployment
2.  Go to the deployment details page and scroll to the Pods table.  (issue 1, checkboxes but no buttons?)
3.  Click on a checkbox

Results:  The download yaml & delete show up but they are partially on top of the Pod title
- [ ] Issue 1 - not sure if this is on purpose or not.
![image](https://user-images.githubusercontent.com/11514927/93942844-18faf900-fce6-11ea-95a4-a2b6b7a23641.png)

- [ ] issue 2 - bug
![image](https://user-images.githubusercontent.com/11514927/93942831-11d3eb00-fce6-11ea-9cb9-fcc65bfbf19d.png)

**Comment by deniseschannon** [comment]
Duplicate: https://github.com/rancher/dashboard/issues/1287
