### ISSUE TITLE
Fleet - Cannot read property 'linkFor' of undefined when creating a GitRepo

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1370]
Rancher version: `master-head (09/23/2020)` _e9a98a3_

RKE DO cluster on HA k8s Rancher

![Screen Shot 2020-09-23 at 12 27 27 PM](https://user-images.githubusercontent.com/27659/94060114-3f796c80-fd98-11ea-8a3b-e3e731a09cfe.png)

**Comment by jiaqiluo** [comment]
The bug fix is validated in master-head 6319706

the steps are the same, and the error does not show up anymore.
