### ISSUE TITLE
Upgrade of a v2 app does not have the initial values set displayed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1371]
**On master-head - commit id: `e9a98a32`**

- Deploy a backup restore app in local (EKS HA setup).
- Select `default storage class (gp2)` from the options in the UI.
- Enter default size as 2Gi
- Click on Install
- After the app has deployed, Do an Upgrade of the app.
- The UI does NOT show `default storage class (gp2)` as selected.
- UI now shows `Use an S3-compatible object store` as the select option

**Expected:**
UI shows originally selected option `default storage class (gp2)` as the one selected.

**Comment by vincent99** [comment]
This was an issue with the form for this one particular chart, not something general.

**Comment by jiaqiluo** [comment]
in the dashboard 
- add this repo 
```
URL: https://git.rancher.io/charts
Branch: master
```
- deploy the WordPress app and set the server type `NodePort`
<img width="1859" alt="Screen Shot 2020-09-25 at 9 20 30 AM" src="https://user-images.githubusercontent.com/6218999/94291635-b9ccfc80-ff10-11ea-95f4-f7a1dbceec86.png">

- wait for the app is installed 
- go to the upgrading page to check applied values 
<img width="1611" alt="Screen Shot 2020-09-25 at 9 24 28 AM" src="https://user-images.githubusercontent.com/6218999/94291845-fac51100-ff10-11ea-8129-2ab6b886c08a.png">

Results:

<img width="938" alt="Screen Shot 2020-09-25 at 9 24 40 AM" src="https://user-images.githubusercontent.com/6218999/94291938-1fb98400-ff11-11ea-92fc-9236586d92ba.png">

**Comment by jiaqiluo** [comment]
the error in the WordPress app does not happen anymore with the latest UI in rancher:master-head

**Comment by sowmyav27** [comment]
**On master-head - commit id: `27000be`**

- Deploy a backup restore app in local 
- select "No default storage location" as the option
- Click on deploy
- when the app has deployed do an Upgrade on the app
- UI shows "No default storage location" as the selected option
- Select S3 compatible storage location. Give in S3 bucket's details.
- Click on Save
- New values are saved in the app.
