### ISSUE TITLE
[Logging v2] no clear way to unselect/clear with mouse the secrets dropdowns from ClusterOutput and Output forms

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1374]
Rancher version: `master-head (09/23/2020)` _e9a98a3_ HA k8s with RKE DO downstream 
rancher/dashboard#1102
rancher/dashboard#1103

![secrets](https://user-images.githubusercontent.com/27659/94067121-3beae300-fda2-11ea-8768-c612ed0cce45.gif)

Once the user selected the secrets from the dropdowns is hard to clear the values using only the mouse pointer.  I had to use the keyboard's backspace.

**Comment by deniseschannon** [comment]
There's some review/overhaul that needs to happen on the dropdowns used throughout the UI that we will look into post 2.5

**Comment by tfiduccia** [comment]
Same with Add Volume in the Storage section of Create Workloads

**Comment by maggieliu** [comment]
Design should match the component in namespace, namens components.

**Comment by maggieliu** [comment]
Add the option "None"

**Comment by izaac** [comment]
Rancher version: `master-head (12/02/2020)` _5ebc964_

None option clears the key now (if any) and disable the dropdown either if a key is selected or not.
