### ISSUE TITLE
Action to run on-demand Job from CronJob

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#1377]
CronJobs should have a (client-side) action to take the jobSpec from the CronJob and create a new [regular] Job out of it, so that you can run the CronJob on-demand.

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Reproduction and Validation**
Rancher versions: v2.6.1 and v2.6-head(931a0f0)


**Steps for reproduction: **
1. Go to local cluster from cluster management
2. Click on workload --> CronJobs --> create CronJobs
3. Used the following inputs:
Name: auston-test
schedule: 0 * * * *
container image: ranchertest/mytestcontainer
4. Press create and land on the CronJobs dashboard.
5. You should see a "Run Now" button on the (931a0f0) version of rancher 

**Screenshot Before Button was Added**
![Screen Shot 2021-11-01 at 5.02.55 PM.png](https://zube.io/files/rancher/6c25ed3005cca113a29d4b94b3663154-screen-shot-2021-11-01-at-5-02-55-pm.png)

**Screenshot After Button is Added**
![Screen Shot 2021-11-01 at 5.03.01 PM.png](https://zube.io/files/rancher/c7f26b8e17f4850c0370c25512a6d7d7-screen-shot-2021-11-01-at-5-03-01-pm.png)

**Sanity Checks**
- I checked this on multiple types of downstream clusters.
- I deleted the CronJob and added it again
- I cleared my cache and refreshed the page and the button was still there.
