### ISSUE TITLE
CIS v2 - Nodes listed in a test's detail do not show the state of the test

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1378]
**On master-head - commit id: `e9a98a32`**

- On a custom RKE cluster, run a scan on the cluster.
- State of the test result is not seen on the test details i.e. nodes listed do NOT show the state of the test.

<img width="1044" alt="Screen Shot 2020-09-23 at 7 51 04 PM" src="https://user-images.githubusercontent.com/26032343/94095261-36a78b80-fdd6-11ea-9c31-f8883fcb1b36.png">

Can we have the state of the test included for every node  ? Because in case of a `Mixed` state, some of the nodes would have passed, and some nodes would have failed.

CISv1 has this in its report

**Comment by deniseschannon** [comment]
@prachidamle @sowmyav27 We need an example of what the results looks like to be able to know how to parse and show them.

**Comment by sowmyav27** [comment]
**In cis v1**
<img width="820" alt="Screen Shot 2020-09-24 at 2 21 00 PM" src="https://user-images.githubusercontent.com/26032343/94201755-4c1dc380-fe71-11ea-9008-d62e6417e7be.png">

**In CIS v2**
<img width="827" alt="Screen Shot 2020-09-24 at 2 21 06 PM" src="https://user-images.githubusercontent.com/26032343/94201767-4fb14a80-fe71-11ea-9684-0ea3d5d891c7.png">

Currently unable to expand the test detail in CISv2 on master.

**Comment by prachidamle** [comment]
@mantis-toboggan-md here is how data for `mixed` state tests look in the report.json

- A "mixed" state means the test has passed on few nodes and has failed on some nodes. 
- The test_data mentions all the node_types where the test was ran. Using this info, one can find all IP addresses where the test is ran
- The nodes where it failed is then explicitly mentioned in the test data. Example check the [{"id":"1.1.19",]  
or [{"id":"1.1.12"] below which show the mixed state tests.
- I have removed the specific IP addresses for security and it just says "ip-" instead

`{"version":"rke-cis-1.5","total":92,"pass":58,"fail":14,"skip":0,"notApplicable":20,"nodes":{"etcd":["ip-","ip-","ip-"],"master":["ip-"],"node":["ip-","ip-","ip-","ip-","ip-"]},"results":[{"id":"1.1","description":"Master Node Configuration Files ","checks":

[{"id":"1.1.19","description":"Ensure that the Kubernetes PKI directory and file ownership is set to root:root (Scored)","remediation":"Run the below command (based on the file location on your system) on the master node.\nFor example,\nchown -R root:root /etc/kubernetes/pki/\n","state":"mixed","node_type":["master","etcd"],"nodes":["ip-","ip-"]},

{"id":"1.1.12","description":"Ensure that the etcd data directory ownership is set to etcd:etcd (Scored)","remediation":"On the etcd server node, get the etcd data directory, passed as an argument --data-dir,\nfrom the below command:\nps -ef | grep etcd\nRun the below command (based on the etcd data directory found above).\nFor example, chown etcd:etcd /var/lib/etcd\n","state":"mixed","node_type":["etcd"],"nodes":["ip-","ip-"]}

{"id":"1.1.20","description":"Ensure that the Kubernetes PKI certificate file permissions are set to 644 or more restrictive (Scored) ","remediation":"Run the below command (based on the file location on your system) on the master node.\nFor example,\nchmod -R 644 /etc/kubernetes/pki/*.crt\n","state":"pass","node_type":["master","etcd"]},{"id":"1.1.21","description":"Ensure that the Kubernetes PKI key file permissions are set to 600 (Scored)","remediation":"Run the below command (based on the file location on your system) on the master node.\nFor example,\nchmod -R 600 /etc/kubernetes/ssl/*key.pem\n","state":"pass","node_type":["master","etcd"]}]}```

**Comment by sowmyav27** [comment]
**On master-head - commit id: `9de5a8509d`**

- On a custom RKE cluster, run a scan on the cluster.
- State of the test result is seen on the test details i.e. nodes listed show the state of the test.

<img width="804" alt="Screen Shot 2020-09-25 at 10 10 51 PM" src="https://user-images.githubusercontent.com/26032343/94330748-1b768080-ff7c-11ea-907d-458ff4842ad2.png">
