### ISSUE TITLE
Chart Icon Feedback (Prometheus)

### ISSUE THREAD

**Issue by westlywright** [rancher/dashboard#1383]
There was a request in the following comment that the Prometheus icons be addressed differently for light and dark modes. If we want to do this we should consider the other chart icons as well. 

https://github.com/rancher/dashboard/issues/1064#issuecomment-693104014

> Also the image for Prometheus should be backed with the color #E65128 and Grafana should be backed with a gradient from #EB5929 to #F5D664 (top to bottom) in light mode based on the following logos:

![prometheus-logo-square](https://user-images.githubusercontent.com/13127443/93279667-aab1b600-f77c-11ea-8dba-cab3f0929227.png)

![Grafana](https://user-images.githubusercontent.com/13127443/93279812-08de9900-f77d-11ea-989e-59935ad5dcab.png)

**Comment by deniseschannon** [comment]
Since we've added colored icons similar to how we handle the charts in apps/marketplace. Other icons might not have light/dark versions, so how we've done it today works for light and dark modes.
