### ISSUE TITLE
Cannot set node affinity while deploying backup restore

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1384]
**On master-head - commit id: `3950b8e`**

- Currently there is no way to set node affinity while deploying backup restore
- Deployed an EKS cluster - HA setup.
- nodes are in 2 zones - us-east-2b and 2c
- Volume /PV is created in us-east-2c 
- Currently there is no way from the Dashboard UI to set node affinity for the backup restore pod to deploy in the correct node.
- Earlier this was set in value.yml file and deploy through helm (not through rancher dashboard UI)
<img width="1659" alt="Screen Shot 2020-09-24 at 2 35 39 PM" src="https://user-images.githubusercontent.com/26032343/94203432-42e22600-fe74-11ea-8b3b-2ae1a6c537e7.png">

**Comment by mrajashree** [comment]
> Earlier this was set in value.yml file and deploy through helm (not through rancher dashboard UI)

the values.yaml file still accepts tolerations, affinity and selectors. And it was decided to have those fields set through values.yaml and not have separate fields in the UI. So can UI also provide the option to edit values.yaml? cc @deniseschannon

**Comment by deniseschannon** [comment]
We added the `Edit as YAML` for all charts so this should be do-able now.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `2ae933e08`**

- `Edit as YAML` is not seen for a deployed app -rancher backup

Reopening the issue
