### ISSUE TITLE
Ui placement of fields - Backup Filename, Prune and Delete timeout in Restore creation

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1387]
**On master-head - commit id: `e9a98a323`**

PV using storage class is configured on the local EKS cluster.

- Create Restore CR
- Can these fields - Backup Filename, Prune and Delete timeout be better placed on the UI.? 
<img width="1408" alt="Screen Shot 2020-09-23 at 8 20 00 PM" src="https://user-images.githubusercontent.com/26032343/94097034-75d7db80-fdda-11ea-9055-ff2a64b1eb02.png">

**Comment by deniseschannon** [comment]
@mantis-toboggan-md let's try moving delete timeout either to be right below prune since it only shows up when you select prune.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `27000be7e`**

- Delete timeout is below Prune now
<img width="1404" alt="Screen Shot 2020-09-26 at 3 09 01 PM" src="https://user-images.githubusercontent.com/26032343/94351116-54f5cd00-000a-11eb-8d86-5a9a3759ed95.png">
