### ISSUE TITLE
Change list pages so top part of page is a header and does not scroll

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1388]
When I have many resources and need to scroll to see them, I lose the top part of the page which contains: Where I am, buttons for multi-select, filter and the table titles.  We should make those things part of header that doesn't scroll.  This is functionality that we did have in 2.5.

![image](https://user-images.githubusercontent.com/11514927/94204909-049a3600-fe77-11ea-804c-474cf042fc66.png)

**Comment by lvuch** [comment]
@vincent99 is working on a way to have fixed sortable headers which would resolve this issue.

**Comment by kwwii** [comment]
This seems like something for development as the design seems clear

**Comment by nwmac** [comment]
Closing for now - not a priority and a lot of work to get the fixed table header working nicely.
