### ISSUE TITLE
Edit Form of a restore CR does not show selected/applied values

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1390]
**On master-head - commit id: `e9a98a323`**

PV using storage class is configured on the local EKS cluster.

- Create a restore CR
- Restore CR is created. 
- Rancher is unreachable. when rancher is back up --> Edit as Form on the restore CR
- Original values are not displayed

**Comment by deniseschannon** [comment]
Editing an existing CR doesn't really make sense. Is there a way to disable it? 

After a restore, there should only be an option to delete.

**Comment by sowmyav27** [comment]
@deniseschannon @mantis-toboggan-md User may want to edit a CR when the Restore CR is in an error state.
For example:

- Enter incorrect S3 values and create a restore CR.
- The Restore CR will be in an error state and in `Retrying` mode.
- User should be allowed to edit the restore CR and correct it

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f7878c`**

- Create a restore CR with invalid file name
- Restore CR is created and will be in Error state.
- Edit as Form on the restore CR
- Original values are displayed
- Correct the values and click on Create.
- Rancher is restored.
