### ISSUE TITLE
Labels and Annotations in workloads need spacing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1394]
Steps:
1.  Go to Create for any workload
2.  Go to the Labels and Annotations tab

Results:  Add button for Labels is too close to the annotations title

![image](https://user-images.githubusercontent.com/11514927/94205584-71fa9680-fe78-11ea-86c2-c3b18ba4db9c.png)

**Comment by deniseschannon** [comment]
@mantis-toboggan-md we should mimic the styling used in the `Labels` component which is used elsewhere in the dashboard

![Screen Shot 2020-09-25 at 6.50.26 AM.png](https://zube.io/files/rancher/22e620ea724d57a54acb71c4b952d969-screen-shot-2020-09-25-at-6-50-26-am.png)

Also it looks like you dropped pod annotations? There should be pod labels and pod annotations

![Screen Shot 2020-09-25 at 6.53.16 AM.png](https://zube.io/files/rancher/97aed5cf773182f24a1f8e33086f252d-screen-shot-2020-09-25-at-6-53-16-am.png)

**Comment by tfiduccia** [comment]
@mantis-toboggan-md & @deniseschannon - There are still no Pod annotations.  Do you want them?
![image](https://user-images.githubusercontent.com/11514927/94605118-77c3f380-024d-11eb-8bb9-40f4bba268f6.png)

**Comment by codyrancher** [comment]
Labels and annotations was already switched to the Labels component. I added the Pod Annotations and restyled to match the Labels component.

https://github.com/rancher/dashboard/pull/1563

**Comment by tfiduccia** [comment]
Fixed
