### ISSUE TITLE
UI should display a text about how to configure the secret so that it will appear in dropdown list of "Encryption Config Secret"

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1395]
**On master-head- commit id: `2229f5cd`**

- Create a Backup CR
- For `Encryption Config Secret` to be listed in the dropdown, the secret has to be created with key “encryption-provider-config.yaml”. This should be made obvious on the UI. Can we add a note in the UI ? 
<img width="911" alt="Screen Shot 2020-09-23 at 10 06 52 AM" src="https://user-images.githubusercontent.com/26032343/94046135-23b89b00-fd85-11ea-8c62-62d65d3e854f.png">

**Comment by deniseschannon** [comment]
Let's add a tooltip of 
"An encryption config secret has a encryption-provider-config.yaml key."

**Comment by sowmyav27** [comment]
Blocked by https://github.com/rancher/dashboard/issues/1436

**Comment by sowmyav27** [comment]
**On master-head - commit id: `27000be7`**

Create backup CR. --> Tool tip is not visible
<img width="997" alt="Screen Shot 2020-09-26 at 9 32 08 AM" src="https://user-images.githubusercontent.com/26032343/94345966-4a254300-ffde-11ea-8e14-e7b3815273ec.png">

reopening the issue

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f7878c`**
Currently tool tip shows: 
<img width="870" alt="Screen Shot 2020-09-28 at 11 37 38 AM" src="https://user-images.githubusercontent.com/26032343/94472076-11709f80-017f-11eb-93a1-ca98f860d829.png">

encryption config secret has to be created in cattle-resource-system namespace specifically. Can we have this info in the tool tip ?

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f787`**

Tool tip is currently
<img width="792" alt="Screen Shot 2020-09-29 at 8 40 02 AM" src="https://user-images.githubusercontent.com/26032343/94581029-7388dd80-022f-11eb-9ff0-8192bc22d966.png">
