### ISSUE TITLE
TTY checkbox looks clickable even if I can't click it

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1400]
Steps:
1.  Go to Create Deployment
2.  In Stdin put in No
3.  Try to click on TTY checkbox

Results:  Can't click on it.  Even thou it looks active.

Two Options:
1.  Don't show TTY checkbox if Stdin is No
2.  Remove Checkbox completely and change drop-down to have (and in this order):
     No
     Yes (this is currently Always, but should change to Yes, cause we have No)
     Yes plus TTY
     Once
     Once plus TTY

**Comment by deniseschannon** [comment]
Let's change it so that the TTY checkbox only shows up for "Once" or "Yes"

**Comment by tfiduccia** [comment]
Fixed
