### ISSUE TITLE
Ingress was automatically enabled even the default value is `false`

### ISSUE THREAD

**Issue by yasker** [rancher/dashboard#1402]
Found the issue when testing with the Longhorn chart.

The ingress rule shouldn't be enabled by default, since the `questions.yaml` has set the default value to `false`.

<img width="1267" alt="Screen Shot 2020-09-24 at 4 54 41 PM" src="https://user-images.githubusercontent.com/3344618/94211616-c73da480-fe86-11ea-9350-2ef2968316d4.png">

See the content of `questions.yaml` here:

https://github.com/longhorn/charts/blob/0a88eaae4d7bdce762af942ea490d72aee338bb1/charts/longhorn/questions.yml#L305-L318

The chart is: Longhorn, at https://github.com/shuo-wu/charts , branch `dev-v2.5`

**Comment by cbron** [comment]
branch is longhorn, pr is not merged yet: https://github.com/rancher/charts/pull/692

**Comment by yasker** [comment]
According to @vincent99 , it might due to it's

```
- variable: ingress.enabled
  default: "false"
  description: "Expose app using Layer 7 Load Balancer - ingress"
  type: boolean
```

Not (without the quote)
```
- variable: ingress.enabled
  default: false
  description: "Expose app using Layer 7 Load Balancer - ingress"
  type: boolean
```

**Comment by yasker** [comment]
Verification blocking by https://github.com/rancher/dashboard/issues/1417

**Comment by yasker** [comment]
Verified. Now the option is not selected by default on the master branch.

**Comment by khushboo-rancher** [comment]
Verified with the latest chart ```c4e115c```, Ingress is enabled by default.
