### ISSUE TITLE
Change "Entrypoint" to "Command" in Create workload screens

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1403]
Steps:
1.  Create Deployment

Results:  Entrypoint/Arguments is halfway between docker and k8s
docker -> entrypoint/command
k8s -> command/arguments

Suggestion:  We should follow k8s and change Entrypoint field to say Command
![image](https://user-images.githubusercontent.com/11514927/94214107-81d0a580-fe8d-11ea-95e4-86288bafe52c.png)

**Comment by deniseschannon** [comment]
Updated:
![Screen Shot 2020-09-27 at 8.36.34 AM.png](https://zube.io/files/rancher/aeea8a0562ce8524fe15c58dfd8c4237-screen-shot-2020-09-27-at-8-36-34-am.png)
