### ISSUE TITLE
Add volume drop-down is gray & won't close while other are black background & I can close

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1406]
1.  Go to create workloads

Results:  Drop-down is different color & I can't close the drop-down without having to select something.

Drop-down everywhere else:
![image](https://user-images.githubusercontent.com/11514927/94215397-623b7c00-fe91-11ea-8611-c491c7490e5b.png)

Add Volume drop-down in Storage section
![image](https://user-images.githubusercontent.com/11514927/94215336-2b656600-fe91-11ea-9682-c82f28b80894.png)

**Comment by lvuch** [comment]
it looks like this may have changed to a dropdown button. @tfiduccia can you verify?

**Comment by tfiduccia** [comment]
This is going to change and there is a new issue for that.  #1731
