### ISSUE TITLE
Backup Changes

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#1407]
While launching backup-restore-operator app, by default the option to "Use an S3 compatible object store" is selected, and even if no values are set, the form sets s3.enabled to true in values.yaml
With the latest checks in the helm chart, that make the "region" and "endpoint" fields mandatory for configuring s3, this leads to an error even if user didn't want to configure s3
```
 helm --debug install --create-namespace=true --namespace=cattle-resources-system --timeout=10m0s --values=/home/shell/helm/values-backup-restore-operator-0.1.0.yaml --version=0.1.0 --wait=true backup-restore-operator /home/shell/helm/backup-restore-operator-0.1.0.tgz
install.go:172: [debug] Original chart version: "0.1.0"
install.go:189: [debug] CHART PATH: /home/shell/helm/backup-restore-operator-0.1.0.tgz
Error: execution error at (backup-restore-operator/templates/s3-secret.yaml:19:17): A valid .Values.bucketName is required for configuring S3 compatible storage as the default backup storage location
```

So by default s3 should not be selected.
Maybe we can have another radio button here as the first option that says 
"Launch backup-restore-operator without configuring a default storage location"
And that should be selected by default 
<img width="1247" alt="Screen Shot 2020-09-24 at 6 15 45 PM" src="https://user-images.githubusercontent.com/10672776/94215596-002f4680-fe92-11ea-8bb1-d1e78f14ab8c.png">

cc @deniseschannon

**Comment by deniseschannon** [comment]
- [ ] Add option for `No default storage location` and this should be the default (what this issue is discussing)
- [ ] Remove `ResourceSet` CRD from the product navigation
- [ ] Backup CRD - Hide ability to select a resourceset from the page because as of now we only want to have this marketed as backing up Rancher. Whenever creating a backup, make sure to pass in the `rancher-resource-set` as the selected resource set.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `27000be7`**

- `No default storage location` option is available while deploying the backup restore chart. On selecting this option and deploying the app, no storage location is set
<img width="979" alt="Screen Shot 2020-09-26 at 9 25 12 AM" src="https://user-images.githubusercontent.com/26032343/94345444-a71efa00-ffda-11ea-92b6-f9415468667a.png">

- ResourceSet CRD is not available from the product navigation
<img width="704" alt="Screen Shot 2020-09-26 at 9 26 17 AM" src="https://user-images.githubusercontent.com/26032343/94345458-d6ce0200-ffda-11ea-905b-65e50d6804f3.png">

- Resourceset option is not available while deploying a backup CRD. On creating a backup - API request has `resourceSetName: "rancher-resource-set"`
<img width="867" alt="Screen Shot 2020-09-26 at 9 27 00 AM" src="https://user-images.githubusercontent.com/26032343/94345478-fb29de80-ffda-11ea-90ad-e3ce0ea76412.png">

- chart name is `Rancher Backup`
