### ISSUE TITLE
CIS - If the scan errors out, display the error instead of trying to display non-existent report info

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1416]
Currently, if a scan errors out, we display an empty report when clicking on the detail view of the scan, but there is no display of the error. 

We should probably hide the empty report table and show the warning of why the scan failed.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `27000be`**
- Give in invalid scan profile name. The scan will be in Error state
- Error message seen when clicked on the Scan
<img width="735" alt="Screen Shot 2020-09-26 at 9 23 13 AM" src="https://user-images.githubusercontent.com/26032343/94345332-fd3f6d80-ffd9-11ea-8ca7-9dd31f39d55a.png">
