### ISSUE TITLE
[Logging v2] - Flows CRD UI form should allow to set Outputs and ClusterOutputs

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1419]
Rancher version: `master-head (09/22/2020)`  _0ccce45_ HA k8s 1.19 with Downstream RKE DO

Reopening #1127, I do not see `clusterOutputs` as an option to set Outputs in a Flow. According to the `Flows` documentation

> Outputs can be output or clusteroutput

**Comment by deniseschannon** [comment]
The UX of this changed, so can you check if you can configure flows with clusteroutputs and outputs @izaac?

**Comment by izaac** [comment]
Rancher version `master-head (09/28/2020)` _ec04f78_ HA k8s with DO RKE downstream cluster

I'm still unable to select ClusterOutputs from the new Create Flow UI on latest master. I see the Outputs listed.
This is by using the **ClusterOwner** (Standard User)

![Screen Shot 2020-09-28 at 2 54 42 PM](https://user-images.githubusercontent.com/27659/94490167-c06ea480-019a-11eb-9e5d-fe4edd9934e7.png)


![Screen Shot 2020-09-28 at 2 54 19 PM](https://user-images.githubusercontent.com/27659/94490192-c95f7600-019a-11eb-9d14-6a6017712761.png)


![Screen Shot 2020-09-28 at 2 57 03 PM](https://user-images.githubusercontent.com/27659/94490299-e431ea80-019a-11eb-8c02-02a5466119a2.png)

**Comment by izaac** [comment]
Rancher version: `master-head (09/29/2020)` _a2a141e_

I can now select `globalOutputRefs` and `localOutputRefs` for Flows. This generates the YAML as expected but the preview YAML is not matching what's in the Edit as Form #1531
