### ISSUE TITLE
The default value of Stdin and TTY should be True.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#1435]
**Describe the bug**
While creating Deployment and StatefuleSet in the Dashboard the default value of ```Stdin``` and ```TTY``` is false.

**Steps to Reproduce**
1. Set up an HA cluster.
2. Go to the dashboard.
3. Try to create Deployment or Statefulset.

**Result**
The ```Stdin``` and ```TTY``` are set to false by default where as in rancher they are True by default.

**Comment by vincent99** [comment]
This is not the default in vanilla k8s and should not be the default here.  It is set in 2.4 because the image defaults to `ubuntu:xenial` and that will exit immediately without a terminal.  The dashboard has no default and should default to the default value.

**Comment by sowmyav27** [comment]
Closing it as per [comments](https://github.com/rancher/dashboard/issues/1435#issuecomment-699471402)
