### ISSUE TITLE
Backup-restore-operator (Rancher Backups) chart should only be available in local cluster

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#1438]
Rancher Backups (backup-restore-operator) chart for 2.5 should only be available in local cluster. The chart should have `catalog.cattle.io/scope: management` annotation so UI can show it only in local cluster

**Comment by mrajashree** [comment]
The chart now has this annotation

**Comment by sowmyav27** [comment]
**On master-head - commit id: `27000be7e`**

Rancher-Backup is NOT available in downstream cluster (backup-restore-operator in the snapshot should be removed as its the older chart, have an issue to track it)
<img width="1660" alt="Screen Shot 2020-09-26 at 3 12 52 PM" src="https://user-images.githubusercontent.com/26032343/94351148-c9307080-000a-11eb-80e1-ecf97168c7f3.png">
