### ISSUE TITLE
%Name% seen as the input field label when creating a config map

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1452]
**On master-head - commit id: `ec04f7878`**

- Dashboard --> Config Maps --> Create Config map
- %Name% seen as the input field label

<img width="923" alt="Screen Shot 2020-09-27 at 2 05 29 PM" src="https://user-images.githubusercontent.com/26032343/94376727-445c5a00-00d1-11eb-8c65-376ebaecf0a9.png">

**Comment by codyrancher** [comment]
This looks like it's already been resolved. Moving to test.

![image](https://user-images.githubusercontent.com/55104481/94587818-f877f500-0237-11eb-9ad2-ab06b24a430f.png)

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f7878c`**

- Issue is not seen
<img width="864" alt="Screen Shot 2020-09-29 at 12 06 28 PM" src="https://user-images.githubusercontent.com/26032343/94604297-50205b80-024c-11eb-8d49-570c9b3f8c9f.png">
