### ISSUE TITLE
Update card design after longhorn chart is deployed

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1461]
- [x] Match the styling of longhorn to be similar to what is implemented for monitoring

<img width="1029" alt="Screen Shot 2020-09-27 at 11 25 09 PM" src="https://user-images.githubusercontent.com/11410997/94397493-cfad0e00-0118-11eb-9cb2-3c73d6b71496.png">

**Comment by deniseschannon** [comment]
Longhorn should be the top link and the text below should be "Manage storage system via UI"

**Comment by khushboo-rancher** [comment]
Verified on the Dashboard - master-head ```ec04f78```

The icon appears as 
<img width="369" alt="Screen Shot 2020-09-29 at 9 46 52 AM" src="https://user-images.githubusercontent.com/60111667/94589703-776e2d00-023a-11eb-9886-910056cc7a38.png">

Can we change the icon as it appears at https://devstats.cncf.io/
<img width="107" alt="Screen Shot 2020-09-29 at 9 51 34 AM" src="https://user-images.githubusercontent.com/60111667/94589945-cae07b00-023a-11eb-8442-ff36f0d710e9.png">

Logo for longhorn is available at https://github.com/cncf/artwork/blob/master/examples/sandbox.md#longhorn-logos

**Comment by khushboo-rancher** [comment]
Verified on the latest dashboard, the card looks good.

<img width="382" alt="Screen Shot 2020-09-29 at 3 27 39 PM" src="https://user-images.githubusercontent.com/60111667/94623341-cf238d00-0268-11eb-94a2-6c821ac81b48.png">
