### ISSUE TITLE
Update card design after istio chart is deployed

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1462]
- [x] Match the styling of istio to be similar to what is implemented for monitoring

<img width="1029" alt="Screen Shot 2020-09-27 at 11 25 09 PM" src="https://user-images.githubusercontent.com/11410997/94397493-cfad0e00-0118-11eb-9cb2-3c73d6b71496.png">

**Comment by deniseschannon** [comment]
Text under Kiali should be
"Visualization of services within a service mesh and how they are connected"

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 6319706

* Deploy Rancher
* Navigate to dashboard view
* Install v2 Istio
* Navigate to Istio Overview
* Kiali card is shown in the correct style

![Screen Shot 2020-09-30 at 10 28 28 AM](https://user-images.githubusercontent.com/21316915/94719251-cafa7c80-0307-11eb-8dc0-e13d03b26d84.png)
