### ISSUE TITLE
Service Create page, more info & dividing line should be based on  the box size and not on text

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1470]
Issues:  More info & Dividing line based on text, not size of box.  So when I have a browser page bigger to fit my external monitor instead of laptop, the text & line don't go to end.

![image](https://user-images.githubusercontent.com/11514927/94478521-3cabbc80-0188-11eb-9b79-afc0eb6a53ac.png)

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1512

**Comment by tfiduccia** [comment]
Fixed
