### ISSUE TITLE
[Monitoring / Alerting V2 UI] Add link to Feature Overview for Grafana Login

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1474]
Based on changes from https://github.com/rancher/rancher/issues/29165, the default user who uses Grafana will be assigned the Viewer role, which means that a user who enters Grafana through the link https://github.com/rancher/dashboard/issues/1064 will not be redirected to the login page; instead, they will be treated as an anonymous user with the ability to just view dashboards.

In order to make it easier for users who want to log in to Grafana to assume non-Viewer privileges (i.e. ability to create dashboards on the Grafana UI), the Feature Overview page should have an additional button for Grafana that directs the user to the `/login` page directly.

The link will be exactly the same as the current Grafana link except with `/login` appended to the end and the text that will be on the link should say `Login to Grafana`.

**Comment by catherineluse** [comment]
Can we have that user automatically logged in to Grafana as well? The current UX is something like this:

1. User clicks Grafana link
2. User sees a login page
3. User has to navigate away to read documentation that tells them the default username and password (https://docs.ranchermanager.rancher.io/integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring#role-based-access-control-for-grafana)
4. Optional step: Freak out about the security implications of everyone having the same default username and password, before reading more docs and realizing that auth is proxied through Rancher, so only logged in Rancher users can even see the Grafana login page.
5. Log in to Grafana

It would be better if the process was:

1. Click the Grafana link
2. Already be in Grafana
