### ISSUE TITLE
Update RKE Federal to RKE Government

### ISSUE THREAD

**Issue by superseb** [rancher/dashboard#1476]
Similar to https://github.com/rancher/ui/pull/4181 in Ember

Other question is if the cluster type is going to be shown in the cluster overview, as it just shows `Rke2` as `Provider` today.

<img width="613" alt="Screenshot 2020-09-28 at 22 17 15" src="https://user-images.githubusercontent.com/2620179/94481709-72789180-01d8-11eb-8d71-24bdd64cb35a.png">

**Comment by deniseschannon** [comment]
Updated the translation in https://github.com/rancher/dashboard/pull/1473

But we need to use the translation for the Provider. Maybe it should be "Other" for the ones we don't recognize?

**Comment by bmdepesa** [comment]
rancher/rancher:master-head eb96d76

* Imported RKE Government cluster
* Provider type shows correctly in dashboard

![Screen Shot 2020-09-30 at 7 45 53 AM](https://user-images.githubusercontent.com/21316915/94701071-12294300-02f1-11eb-9959-2f71fb448443.png)
