### ISSUE TITLE
Can't click all options on Add Volume in Create Deployment

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1480]
Steps:
1.  Go to Create Deployment
2.  Click on Storage Tab
3.  Click on Add Volume drop-down button
4.  Try to add a secret, certificate, or config map

Results:  Won't add

**Comment by sowmyav27** [comment]
Related issue -- https://github.com/rancher/dashboard/issues/1059

**Comment by tfiduccia** [comment]
Fixed
