### ISSUE TITLE
Multi Select Style issues

### ISSUE THREAD

**Issue by westlywright** [rancher/dashboard#1488]
When using LabeledSelect with multi the tags are goofing the labels up.

![Screen Shot 2020-09-11 at 1 17 52 PM](https://user-images.githubusercontent.com/13127443/92969119-364fdd80-f431-11ea-80c4-b0e346ccd933.png)

originally found in rancher/dashboard#1230

**Comment by deniseschannon** [comment]
Related Issue: https://github.com/rancher/dashboard/issues/1409

Basically, multi-select style was updated for the top header nav bar, which doesn't have a label inside of it.

<img width="589" alt="Screen Shot 2020-09-29 at 9 36 48 PM" src="https://user-images.githubusercontent.com/11410997/94643545-e891fc80-029b-11eb-9aaf-1cc1fff4c796.png">

**Comment by sadiapoddar** [comment]
Verified the fix 2.5-head 9ee39b9, and mater-head, a549b47.
steps.
1. select multi-label in cluster explorer navigation bar
2. There is no overlap with other labels
3. The drop-down menu now clearly shows the option with a scroll bar.

<img width="598" alt="Screen Shot 2020-11-30 at 3 59 46 PM" src="https://user-images.githubusercontent.com/72409237/100681903-a59ae680-3329-11eb-96e6-496706ee508c.png">

**Comment by sadiapoddar** [comment]
closing the issue as it's fixed.

**Comment by sowmyav27** [comment]
@sadiapoddar Could you reproduce the issue on 2.5.2 and validate the fix for [this](https://github.com/rancher/dashboard/issues/1488#issue-710648748) issue on latest 2.5-head ?

**Comment by sadiapoddar** [comment]
2.5.2
repro steps.
1. Install monitoring app from the dashboard
2. Manually invoked Edit/upgrade on "rancher-monitoring" 
3. Try to select 
"config secret" on "Configure Alertmanager" by selecting from the existing secrets
4. Notice the "Aditional Secret" label is overlapped by selected multiple tags

<img width="618" alt="Screen Shot 2020-12-01 at 3 15 29 PM" src="https://user-images.githubusercontent.com/72409237/100809619-5b7a3980-33eb-11eb-880a-81c5e7124147.png">


Verified the fix 2.5-head 9ee39b9, and mater-head, a549b47.

<img width="713" alt="Screen Shot 2020-12-01 at 3 14 59 PM" src="https://user-images.githubusercontent.com/72409237/100809728-aa27d380-33eb-11eb-8776-7e189285bd0f.png">
