### ISSUE TITLE
Disabled RadioGroup Style Issues

### ISSUE THREAD

**Issue by westlywright** [rancher/dashboard#1489]
When the radio group is disabled and a default value is provided in the model the option that should be selected is not selected.

<img width="1569" alt="screen_shot_2020-09-24_at_11 32 39_am" src="https://user-images.githubusercontent.com/13127443/94185494-30f38980-fe5a-11ea-86f0-ecfad6b65810.png">

originally found in rancher/dashboard#1230

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1512

**Comment by jiaqiluo** [comment]
in lastest master-head with the latest UI 

when there is no existing secret, both radio buttons are disabled, but we still cannot tell which value is applied/selected. 
<img width="380" alt="Screen Shot 2020-09-30 at 4 22 39 PM" src="https://user-images.githubusercontent.com/6218999/94750149-4ffe8980-033a-11eb-995d-451dc56867f2.png">

**Comment by jiaqiluo** [comment]
@lvuch @westlywright 
Another issue found during validating this issue:

The 1st sentence in the tooltips is too long to show fully. 

<img width="1544" alt="Screen Shot 2020-09-30 at 4 20 54 PM" src="https://user-images.githubusercontent.com/6218999/94751137-8c32e980-033c-11eb-915b-76edbab29882.png">

**Comment by jiaqiluo** [comment]
the bug fix is validated in master-head cb9e8a1 

Although the radio buttons are not clickable, it shows the `Create default config` is selected. 

![image](https://user-images.githubusercontent.com/6218999/94846159-8806da80-03d5-11eb-84fa-42f3257eb9b3.png)


But, as the screenshot shows,  the tooltip is still too long to show fully in the window.
We expect the size of the tooltip can auto-adjust depending on the size of the browser window.

**Comment by deniseschannon** [comment]
@jiaqiluo Can you create a separate issue for the tooltip and let's close this issue.

**Comment by jiaqiluo** [comment]
> the bug fix is validated in master-head cb9e8a1
> 
> Although the radio buttons are not clickable, it shows the `Create default config` is selected.
> 
> ![image](https://user-images.githubusercontent.com/6218999/94846159-8806da80-03d5-11eb-84fa-42f3257eb9b3.png)
> 
> But, as the screenshot shows, the tooltip is still too long to show fully in the window.
> We expect the size of the tooltip can auto-adjust depending on the size of the browser window.


The tooltip issue is tracked in this new ticket https://github.com/rancher/dashboard/issues/1556

This issue can be closed
