### ISSUE TITLE
Unable to scale down stateful set/deployment to zero in the form view.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#1490]
**Description of the bug**
The replica field doesn't accept zero while creating/editing the Stateful set/deployment in the form view.

**Steps to reproduce**
1. Set up an HA with 3 nodes.
2. Go to the local cluster explorer.
3. Create a stateful set with 1 replica.
4. Edit the stateful set and try to make the replica as 0.

**Result**
The Save button is not enabled.
<img width="1612" alt="Screen Shot 2020-09-28 at 5 15 56 PM" src="https://user-images.githubusercontent.com/60111667/94498158-5102b000-01ae-11eb-80c5-523c69683fa4.png">

**Additional context**
The same can be done through YAML.
With the longhorn use case, the user will need to scale down the stateful set/deployment to 0 to detach the volume.

**Environment Info**
The dashboard version - ec04f78
The setup info - HA setup with k3s v1.1.3

**Comment by mantis-toboggan-md** [comment]
The workload creation form's validation has been disabled which inadvertently resolved this problem, you should be able to save statefulsets with replicas as 0 now.

**Comment by khushboo-rancher** [comment]
Verified on dashboard - ```ec04f78```

Validation - **Pass**

The Stateful set/Deployment form allows to create and edit with the replica set to 0.
