### ISSUE TITLE
App values should be preserved and merged on upgrade

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#1496]
When you launch an app, you're shown the full values.yaml from the selected chart.  On save we diff the values you've selected with the originals from the chart and save only the difference (which becomes `spec.values`).  This worked before.

On upgrade this did not work right.  The expected behavior is:

- You're shown the values.yaml from the selected chart with the overrides that you had chosen before applied (i.e. the same options/yaml as you had saved on install show up again)
- You can change versions or charts and should see the new values yaml for that chart + your diff
- You can change values in the editor and those changes should be preserved (even if you then change version/chart, above)
- On save, again what should be stored is the diff your values vs the selected version's defaults.

**Comment by jiaqiluo** [comment]
- add this repo `https://git.rancher.io/charts	master`
- the default value for the server type is `locadBalancer` for the WordPress app 
- install the WordPress app v7.3.8
- wait for it to be deployed 
- upgrade the app
![image](https://user-images.githubusercontent.com/6218999/94870840-6cafc580-03fd-11eb-8712-ffc7d642f8fd.png)
- change the service type from nodePort to clusterIP
- click `edit as yaml` then `show diff` 
![image](https://user-images.githubusercontent.com/6218999/94870970-b698ab80-03fd-11eb-9bb8-18032c0c1907.png)
- click `continue editing`, then `back to from` 
- confirm that the change is preserved, the service type is still clusterIP
![image](https://user-images.githubusercontent.com/6218999/94871199-4e969500-03fe-11eb-9b39-7ea40e3550fc.png)
- now update the chart version from 7.3.8 to 9.0.3
![image](https://user-images.githubusercontent.com/6218999/94871230-5eae7480-03fe-11eb-8ad1-e2a93c5e1a6b.png)
- confirm that the change is preserved, the service type is still clusterIP
- click `edit as yaml` then `show diff`, the change is preserved 
![screencapture-167-172-120-123-dashboard-c-c-76jd2-apps-install-2020-10-01-15_55_11](https://user-images.githubusercontent.com/6218999/94871308-89003200-03fe-11eb-88b1-4d45e659e76e.png)
-
