### ISSUE TITLE
When I execute shell, it messes up the Cluster drop-down at top left.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1497]
Steps:
1.  At top right part of screen click on execute shell

Results:  The cluster name in the custer topdown goes up and is now misaligned.  It won't go back to being aligned until I do a browser refresh.
![image](https://user-images.githubusercontent.com/11514927/94525925-a4462400-01e9-11eb-89a7-2ca2121e8865.png)

Comments:  This happens any where I may execute shell.  for example if I go to a pod and click on execute shell from it's menu, this will happen there as well.

**Comment by deniseschannon** [comment]
Also, check the main product dropdown as it moves that as well.

**Comment by tfiduccia** [comment]
Fixed.  Both the product & cluster drop-downs have been verified across multiple products.
