### ISSUE TITLE
Start buttons on Rio first page go to "page not found"

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1515]
Steps:
1.  Install Rio
2. Go to Rio
3.  Click on Start button for either "Learn how" box

Results: Both buttons go to "Page not Found" & Back to homepage link takes me back to Cluster Explorer.
Buttons:
![image](https://user-images.githubusercontent.com/11514927/94625404-89b58e80-026d-11eb-9316-25136cb64c33.png)

Results:
![image](https://user-images.githubusercontent.com/11514927/94625437-9a660480-026d-11eb-8dba-85a3718c2763.png)

**Comment by nwmac** [comment]
Closing - Rio has been removed
