### ISSUE TITLE
Discover Rio box has UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1516]
- [ ] Box with Create service is not aligned to the top
![image](https://user-images.githubusercontent.com/11514927/94624635-bec0e180-026b-11eb-93fc-ab0c1a04b689.png)

- [ ] Can't get back to Discover page unless I leave the App and go back to it.  No left menu for it.
![image](https://user-images.githubusercontent.com/11514927/94624722-f2037080-026b-11eb-9271-a255e47abacf.png)

**Comment by nwmac** [comment]
Rio has been removed
