### ISSUE TITLE
Rio app UI issues - All pages need styling

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1518]
Issues:
1.  All name field on all pages aren't translated:  Say %Name%
![image](https://user-images.githubusercontent.com/11514927/94627456-722cd480-0272-11eb-96d9-6bf51490ac19.png)

2.  Drop-down are too small on all pages
![image](https://user-images.githubusercontent.com/11514927/94627464-7bb63c80-0272-11eb-8feb-49d2001e5457.png)

3.  Spacing issues everywhere
![image](https://user-images.githubusercontent.com/11514927/94627510-a1434600-0272-11eb-80e2-47742d5857db.png)

4.   Router page - Method, Host Header, & match field are overlapping each other.  And the spacing in Headers
![image](https://user-images.githubusercontent.com/11514927/94627583-d059b780-0272-11eb-83cc-6820bbb7b82f.png)

5.  Service page - Not using properly control for scale & the tabbed section.
![image](https://user-images.githubusercontent.com/11514927/94627777-42320100-0273-11eb-84e3-1ddd52ca087e.png)

6.  Detail pages for all showing live editable drop-downs.
![image](https://user-images.githubusercontent.com/11514927/94627937-ab197900-0273-11eb-95fb-ce0c42f5ad27.png)

Comment - Basically all pages need to be gone through.  But those are main high level issues.

**Comment by lvuch** [comment]
wip https://github.com/rancher/dashboard/pull/1665

**Comment by nwmac** [comment]
We've removed Rio support, so this is no longer applicable.
