### ISSUE TITLE
If I'm on details page while scan is running, I don't see results

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1523]
steps:
1.  Install CIS
2.  Go to Create Scan
3.  Select Create
4.  Click on Scan while it running.

Results:  it will pass me status until it gets to reporting results.  Then it never shows me results, unless I get out then back in.
![image](https://user-images.githubusercontent.com/11514927/94629322-3e07e280-0277-11eb-9739-88542369c720.png)

**Comment by deniseschannon** [comment]
This sounds like a refresh issue from the backend when it's done, it should send an event.

**Comment by deniseschannon** [comment]
When the state of the scan finishes, the UI needs to fetch the report.

**Comment by tfiduccia** [comment]
Fixed
