### ISSUE TITLE
[Logging v2] - Project Owner is able to add Flows using Create from YAML but not with Create with Form

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1524]
Rancher version `master-head (09/29/2020)` _a2a141e_
`rancher-logging 3.6.000` 

![Screen Shot 2020-09-29 at 4 59 51 PM](https://user-images.githubusercontent.com/27659/94628726-96d67b80-0275-11eb-86b4-b1b0e0f7d8ad.png)

**Comment by jiaqiluo** [comment]
in the latest master-head 5044f25

- as admin, provision a cluster, and install Logging v2 in the dashboard 
- as admin, create a project p-1 and add user-1 as the project owner
- as user-1, create a namespace in the project 
- then go to dashboard -> logging -> flows -> create 

Result:
- the same as the issue describes 
<img width="594" alt="Screen Shot 2020-09-30 at 3 00 10 PM" src="https://user-images.githubusercontent.com/6218999/94744353-aa451d80-032d-11eb-9a41-79a13f1835ac.png">

**Comment by izaac** [comment]
Rancher version: `master-head (10/01/2020)` _8d590a8_

Validated this is working as I now can add outputs and clusteroutputs to a Flow as `Cluster Owner` with both YAML and UI Form.
