### ISSUE TITLE
[Logging v2] when editing the Flows with the UI Form the preview YAML is not listing the outputs/clusterOutputs

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1531]
Rancher version: `master-head (09/29/2020)` _a2a141e_

Create one ClusterOutput
Create one Output
Then Create a Flow and select the ClusterOutput and the Output
Click Edit as YAML.

![Screen Shot 2020-09-29 at 5 50 27 PM](https://user-images.githubusercontent.com/27659/94631321-f5ebbe80-027c-11eb-9806-9af0bbde8d59.png)

![Screen Shot 2020-09-29 at 5 50 19 PM](https://user-images.githubusercontent.com/27659/94631350-0bf97f00-027d-11eb-8360-2a953707a992.png)

**Comment by tfiduccia** [comment]
Flows are now listed in spec.globalOutputRefs & spec.localOutputRefs
![image](https://user-images.githubusercontent.com/11514927/94737224-54b74380-0322-11eb-9f2d-80f4609b9d5e.png)
