### ISSUE TITLE
[Monitoring v2] Expose a UI to be able to update the global values of the AlertmanagerConfig Secret, including TrustedCA

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1532]
This is a place holder ticket. Depending on how upstream will manage the CRD: https://github.com/prometheus-operator/prometheus-operator/pull/3451, we will need to design the UX accordingly.

Related to: https://github.com/rancher/rancher/issues/24272

**Comment by catherineluse** [comment]
I'm changing the title of this issue based on Arvind's description of the UX enhancement in this comment: https://github.com/rancher/rancher/issues/24272#issuecomment-696517413
