### ISSUE TITLE
Tweak namespace filter (in header of explorer) behavior

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#1533]
- Empty value means All Namespaces (instead of Only User)
- But the default value of the preference is now "only user", so a new user initially sees the same result as before.
- If you pick any one of the 5 special options at the top, all other values are removed so you have just that one special value.  
- If you pick any regular ns/project below the special 5, those selections add together, and any of selected special view options are removed from the selection.

This: eliminates the oddity of selecting "all namespaces" selects more than the default empty filter.  And disallows all sorts of odd combinations of selecting multiple conflicting special views or a special + some namespaces that didn't really make sense.

**Comment by tfiduccia** [comment]
Fixed
