### ISSUE TITLE
Monitoring installation page - tooltips is too long to show in the window  

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#1556]
bug

In the Monitoring v2 app installation page, under the `Configure Alertmanager` section, the 1st sentence in the tooltips is too long to show fully.
We expect the size of the tooltip can auto-adjust depending on the size of the browser window.

![image](https://user-images.githubusercontent.com/6218999/94847768-de751880-03d7-11eb-95d6-13ac3cb3e055.png)

**Comment by deniseschannon** [comment]
@westlywright Didn't you just put a max width for tool tips?

**Comment by jiaqiluo** [comment]
the fix is validated on rancher:`v2.5-7eb1792946639251f51bd109b630f9c1cf8940c2-head`

![image](https://user-images.githubusercontent.com/6218999/97498423-61cb5080-1929-11eb-9482-2e98598d1509.png)
