### ISSUE TITLE
[Monitoring V2 UI] Prometheus Operator warning shows up on an upgrade

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1557]
bug from https://github.com/rancher/dashboard/issues/1167: Warning shows up even during a chart upgrade; the warning should only show up during an install.

<img width="1412" alt="Screen Shot 2020-10-01 at 11 52 48 AM" src="https://user-images.githubusercontent.com/13127443/94851023-ac19ea00-03dc-11eb-8b37-45ed4e4d64fe.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in both `master-e4dc25135dbe9bad376dc7bd62360b87273cdbde-head` and `v2.5-52583ea7a00f64b0ea15190566ae2cef9540d19c-head`

The warning does not show anymore when editing the rancher-monitoring v2 app  in the dashboard
