### ISSUE TITLE
[Logging V2]  Remove "deploy to controlplane nodes" checkbox from chart options

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1558]
After some discussion related to this issue https://github.com/rancher/rancher/issues/29297 we are going to always schedule fluentbit pods on rke controlplane / etcd nodes.  The dasboard should not pass any values for the `fluentbit_tolerations` value.

**Comment by izaac** [comment]
This was tested as part of https://github.com/rancher/rancher/issues/29297
Additional checks:
- No tolerations passed by the UI to the installation.
- Only k3s clusters has chart options now. `K3s Container Engine`

> Rancher version: `master-head (10/01/2020)` _1b0778b_
> `rancher-logging 3.6.000`
> 
> All the following was installed from Dashboard
> 
> - RKE with 1 dedicated etcd, 1 dedicated control plane and 3 workers.
>   - All nodes had a container for collecting logs
>   - After installing I increased the scale of the etcd nodes to 3 and the fluentbit daemonset scaled properly
>   - Logs were flowing to a configured Output
> - EKS this was installed properly, all nodes had their fluentbit log collector.
> - k3s this was installed properly, all nodes had their fluentbit log collector.
> - RKE2 this was installed properly, all nodes had their fluentbit log collector.
