### ISSUE TITLE
Monitoring Overview Page should not  show when Monitoring v1 is installed 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#1561]
in master-head cb9e8a1

when the monitoring v1 is installed in the cluster, we can see the Monitoring Overview Page which is not expected. 

<img width="1864" alt="Screen Shot 2020-10-01 at 12 32 11 PM" src="https://user-images.githubusercontent.com/6218999/94854826-5cd6b800-03e2-11eb-907c-a7e25c22d5cb.png">

**Comment by gaktive** [comment]
At a minimum, we should add a banner to indicate if v1 is installed.

**Comment by richard-cox** [comment]
This should be fixed, I couldn't test locally (v1 monitoring failed to install correctly) but ran through with Neil. 
- If v1 is installed the Monitoring section should not show and a blocking warning shows when attempting to install v2 via helm
- if v1 & v2 is installed the Monitoring section should show but with a warning regarding v1

**Comment by sowmyav27** [comment]
@richard-cox Is there any PRs for this issue ?

**Comment by richard-cox** [comment]
@sowmyav27 No PR addressing this specific issue. These area's have received multiple changes since the issue was created that looked like they've fixed it. Just needs a re-test with the latest code.

**Comment by brendarearden** [comment]
Steps to recreate: 
1. Deployed single install rancher/rancher:master-head cb9e8a1
2. Deployed monitoring v1 from cluster manager
3. Navigated to cluster explorer and accessed the monitoring dashboard
4. The monitoring v2 dashboard was accessible with no indication that monitoring v1 was deployed

Steps used to Test:
1. Deployed single install rancher/rancher:v2.5.6-rc5
2. Deployed monitoring v1 from cluster manager
3. Navigated to cluster explorer and accessed the monitoring dashboard
4. The monitoring v2 dashboard link was accessible and informational message appeared indicating that v1 monitoring was installed, and links to external dashboards were not clickable
![Screen Shot 2021-02-22 at 1 53 11 PM](https://user-images.githubusercontent.com/19455540/108768768-4eb24100-7515-11eb-9ca8-4a8a15d6b3ca.png)
