### ISSUE TITLE
[Monitoring 2] On overview page need a warning above the links if v1 is installed

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1565]
In overview page if v1 is installed, then it should show it's a v1 install.

**Comment by jiaqiluo** [comment]
in master-head 5a60e25 with the latest UI 

When the monitoring v1 is installed in the cluster:
<img width="1871" alt="Screen Shot 2020-10-01 at 6 05 57 PM" src="https://user-images.githubusercontent.com/6218999/94878001-fe74fe00-0410-11eb-80f1-ef32741505ca.png">

**Comment by jiaqiluo** [comment]
reopen this issue because the same warning message also shows when only monitoring v2 is installed.

<img width="937" alt="Screen Shot 2020-10-01 at 6 20 21 PM" src="https://user-images.githubusercontent.com/6218999/94878653-ddada800-0412-11eb-9a9a-de247bccfc28.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in rancher:master-head 87e7cdf with the latest UI 

When monitoring v2 is installed, there is no warning message in the monitoring overview page anymore. 

<img width="1857" alt="Screen Shot 2020-10-02 at 2 31 00 PM" src="https://user-images.githubusercontent.com/6218999/94971545-135a9b80-04bc-11eb-9c47-b05db3cb3bb2.png">
