### ISSUE TITLE
[Logging v2] - Include the Output type in ClusterOutputs and Outputs list view

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1568]
Rancher version: `master-head (10/01/2020)` _1b0778b_

Adding this information will ease the output identification and for best practices

<img width="1165" alt="Screen Shot 2020-10-01 at 4 42 42 PM" src="https://user-images.githubusercontent.com/27659/94867079-59006100-03f5-11eb-8cf2-8c5a5f80656d.png">

**Comment by ebauman** [comment]
Thank you!

**Comment by deniseschannon** [comment]
I'd call it Providers or whatever language we use in the overview page

**Comment by izaac** [comment]
Rancher version: `master-head (10/23/2020)` _a3a4c87_

ClusterOutput and Output

I validated the Providers are shown properly in the list view.
