### ISSUE TITLE
Authentication pages

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#157]
https://xd.adobe.com/view/172bb0b6-1c18-4de0-7aff-32e2404ffc2a-611a/

**Comment by tfiduccia** [comment]
Lauren can you do github & google auth please.

**Comment by lvuch** [comment]
github and google here: https://xd.adobe.com/view/bd89f18c-7f62-4c4b-5b83-566c84a564b8-cbb8/ but I think google could use reconsideration. Do we need all the info in the boxes?
