### ISSUE TITLE
Bringing up shell cause App text in drop-down & Cluster picker to move up and change font size

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1574]
Steps:
1.  Bring up the shell

Results:  Text size get smaller and moves up and is no longer centered.
![image](https://user-images.githubusercontent.com/11514927/94871743-9833af80-03ff-11eb-8ba8-f6ac4f802762.png)
![image](https://user-images.githubusercontent.com/11514927/94871809-c4e7c700-03ff-11eb-81e6-976640b01f61.png)

**Comment by deniseschannon** [comment]
Duplicate: https://github.com/rancher/dashboard/issues/1497
