### ISSUE TITLE
Hide Cluster, Project, User namespaces from namespace drop-down.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1577]
Issue:  Because each Cluster, Project & User creates a namespace, my namespace drop-down fills up with namespaces I would never use.  This makes it hard for the end-user to really see what namespaces matter.  We should hide the namespaces we are creating that the user will never need.

![image](https://user-images.githubusercontent.com/11514927/94873913-5f96d480-0405-11eb-9ea6-9f9b138ab5aa.png)
![image](https://user-images.githubusercontent.com/11514927/94873921-66254c00-0405-11eb-9585-a7f396a9514d.png)

**Comment by deniseschannon** [comment]
Plan is to use a preference to decide when to show them.

If preference is on, show all of these namespaces. 
If preference is off, hide these namespaces

**Comment by ibuildthecloud** [comment]
management.cattle.io/system-namespace: "true"

**Comment by tfiduccia** [comment]
Places where Namespace drop-down currently exist:
Cluster Explorer
- [ ] Namespace picker in header
- [ ] Namespace picker in Create for all resources
- [ ] Pod Scheduling in Create workload

Logging:
- [ ] Namespace picker in Create for Flows & Output

Monitoring:
- [ ] Namespace picker in Create Prometheus Rules
- [ ] OPA Create Constraint

**Comment by catherineluse** [comment]
This work has been completed - see https://github.com/rancher/dashboard/pull/6468.
