### ISSUE TITLE
Roles Add role

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#158]

**Comment by lvuch** [comment]
https://xd.adobe.com/view/411d4b53-b8fd-4cb6-77dd-d41a1dc50173-372c/

**Comment by tfiduccia** [comment]
No add roles or detail pages.

**Comment by lvuch** [comment]
add and detail created: https://xd.adobe.com/view/411d4b53-b8fd-4cb6-77dd-d41a1dc50173-372c/

**Comment by deniseschannon** [comment]
Close in favor of #271
