### ISSUE TITLE
Tool tip info is incorrect in CIS Profile creation page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1584]
**On master-head - commit id: `5a60e25bd`**

- On an EKS cluster, Deploy CIS v2 chart.
- Go to Profiles --> Create
- Tool tip for tests to skip is incorrect here.
<img width="749" alt="Screen Shot 2020-10-01 at 11 12 02 PM" src="https://user-images.githubusercontent.com/26032343/94893336-c505b800-043b-11eb-9c59-80245d6d9d79.png">

- tests here is an array of strings

**Comment by codyrancher** [comment]
@sowmyav27 @maggieliu Are we okay with "ProTip: Paste lines into any list field for easy bulk entry"?

**Comment by sowmyav27** [comment]
@codyrancher What would be an example for this bulk entry ? Something like this : 
```
1.1.1
1.1.2
1.1.3
```

**Comment by codyrancher** [comment]
```
1.1.1
1.1.2
1.1.3
```

Would've been an example but it looks like ArrayList doesn't support the functionality. So we should either remove that tooltip or add the functionality.

A list is just a ui component that accepts multiple values it's not a k8s concept. Pretty much anywhere that you see the `add` button is a list.

**Comment by sowmyav27** [comment]
It will be a good way for the users to add tests like that in a bulk.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `56bf444ca9`**

- Tool tip info is corrected in CIS Profile creation page 
- And bulk entry of list works

<img width="450" alt="Screen Shot 2020-10-21 at 7 59 34 PM" src="https://user-images.githubusercontent.com/26032343/96819307-1cae9800-13d8-11eb-9cfc-5b1ef2792799.png">
