### ISSUE TITLE
Fields in the top nav bar are not in alignment 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1585]
**On master-head - commit id: `5a60e25bd`**

- Navigate to dashboard
- Top nav is as below
<img width="1673" alt="Screen Shot 2020-10-01 at 11 15 29 PM" src="https://user-images.githubusercontent.com/26032343/94893640-87555f00-043c-11eb-9cc2-ffa14895477c.png">

- Click on `Shell` in the top nav bar
- `Cluster Explorer` and cluster dropdown, are misaligned 
<img width="1677" alt="Screen Shot 2020-10-01 at 11 16 49 PM" src="https://user-images.githubusercontent.com/26032343/94893893-11052c80-043d-11eb-8dc7-784275da54cb.png">

**Comment by deniseschannon** [comment]
Duplicate: https://github.com/rancher/dashboard/issues/1497
