### ISSUE TITLE
Login with a user without clusters and Cluster Explorer preference is enabled the user is shown only No clusters message 

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1589]
This is a follow up enhancement of the backend issue https://github.com/rancher/rancher/issues/29330

> This is backend, the server is sending the redirect when you come back in from keycloak to the root path /. But I will also change the dashboard to show the header/footer on that screen so you're not trapped.

![Screen Shot 2020-10-01 at 5 17 31 PM](https://user-images.githubusercontent.com/27659/94875851-cbc80700-040a-11eb-80d6-23c41539bd7f.png)

Rancher version: `v2.5-head (10/02/2020)` _v2.5-66f4adaa689b25d104b7dbd630391c2a421a20d4-head_

**Comment by vincent99** [comment]
I changed the "you don't have any clusters" screen a couple days ago to include the header & footer so you could go elsewhere from there.  You don't have to have the SAML setup to see just that, a local user with no permissions granted will work too.

**Comment by izaac** [comment]
Rancher version: `v2.5.0-rc7 (10/04/2020)`

- User without cluster.
- The user has preference set to `Cluster Explorer` ( User -> Preferences -> Login Landing Page )
- Login in as this user

This user is no longer trapped in with the error in this issue description.
Now the user has this page displayed and is able to click in the Cluster Manager link. 
The user has now an error message that says `You don't have any clusters..`

![Screen Shot 2020-10-04 at 7 22 28 AM](https://user-images.githubusercontent.com/27659/95018194-f8e70600-0612-11eb-9131-8c21441f6b6c.png)
