### ISSUE TITLE
[Logging V2] Flows cannot contain empty brackets

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1590]
Currently when the dashboard creates flows and cluster flows it passes `spec.filters: []` and `spec.match: []` .  This causes fluentd to not match any logs and all logs being ignored.

# Steps to Reproduce
1. have an rke cluster with dashboard installed
2. create a cluster output
3. create a cluster flow with no filters or matches and configure the output from step 2
4. observer no logs are generated

If you edit the clusterflow with kubectl and remove the `filters` and `match` keys from the spec logs will start flowing shortly after.

**Comment by paynejacob** [comment]
The same is true for namespaced flows

**Comment by izaac** [comment]
Reproduced in `v2.5-head (10/02/2020)` _ce572b5_

**Comment by izaac** [comment]
Rancher version `v2.5-head (10/07/2020)`  _60d3ff3_

Validated matches and filters are not added if we don't select or add any.
If we add matches or filters these are added in the Edit as YAML
Opened #1641
