### ISSUE TITLE
Create button missing for PVC creation form view screen.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#1597]
**Describe the bug**
There is no create/cancel button for PVC creation (form view) under the storage section.

**Navigation**
Go to Dashboard master-head --> Under Storage section --> Click persistentVolumeClaims --> Click Create

<img width="1525" alt="Screen Shot 2020-10-02 at 3 09 25 PM" src="https://user-images.githubusercontent.com/60111667/94974177-9b43a400-04c2-11eb-8791-53304da519cc.png">

**Comment by deniseschannon** [comment]
@mantis-toboggan-md Did this somehow accidentally get created cause of something we added for workloads?

**Comment by deniseschannon** [comment]
There is no actual form for PVC or plans to do for now.

**Comment by deniseschannon** [comment]
@khushboo-rancher you shouldn't see the form to create a PVC anymore

**Comment by khushboo-rancher** [comment]
Verified on master-head - 0390ff5

There is no option to create PVC via form, only create from YAML is available and working fine.
