### ISSUE TITLE
Switching cluster while in Apps & Marketplace takes me back to Cluster Explorer

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1615]
Steps:
1.  Have two clusters deployed
2.  Go to Apps & Marketplace
3.  From the cluster drop-down, switch clusters

Results:  Takes me back to Cluster Explorer.  Should leave me in Apps & Marketplace.

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/dashboard/issues/834
