### ISSUE TITLE
Repo with bad advanced target, won't let me delete

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1619]
Issues:  I must have put something bad in the advanced for target and it wouldn't deploy the resources.  It got stuck in Githupdating state.  So I tried to delete it.  It wouldn't let me, just gave me an error.  I guess it did delete eventually, it just didn't show it removed?
![image](https://user-images.githubusercontent.com/11514927/95012636-0ab6b200-05ef-11eb-9d24-c20cf2dc0fce.png)

**Comment by nwmac** [comment]
Closing - won't fix
