### ISSUE TITLE
Second group that has same selector, not showing selector on edit

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1620]
Steps:
1.  Create a cluster with label foo:bar
2.  Create a cluster group with selector foo=bar
3.  Create a second group with same selector foo=bar

Results: Both groups are created and cluster is assigned to that group.   But if I edit the second cluster the selector isn't show up?

![image](https://user-images.githubusercontent.com/11514927/95012857-bf9d9e80-05f0-11eb-976f-68e592d892dd.png)

**Comment by nwmac** [comment]
@Shavindra This is an old issue - can we validate if it is still valid?

**Comment by Shavindra** [comment]
Cannot replicate

NB: UI have changed now
Cluster group is created via Global Apps > Continuous delivery > Cluster Groups

![Uploading image.png…]()

**Comment by sowmyav27** [comment]
**Not able to reproduce the original issue on 2.7-head commit id: `5d45218 `**
<img width="1316" alt="Screen Shot 2022-10-25 at 3 23 36 PM" src="https://user-images.githubusercontent.com/26032343/197893419-83c99e65-b5b7-429b-a8ce-f7b3dd4afea7.png">
