### ISSUE TITLE
Can not create an Ingress in Kubernetes 1.19

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1634]
The creation of an Ingress fails on a Kubernetes 1.19 cluster with a validation error.

Kubernetes version:
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2+k3s1", GitCommit:"d38505b124c92bffd45f6e0654adb9371cae9610", GitTreeState:"clean", BuildDate:"2020-09-21T17:00:07Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
Rancher version: 2.5.0

![Bildschirmfoto 2020-10-06 um 17 39 52](https://user-images.githubusercontent.com/243056/95227492-758a0800-07fe-11eb-86f2-ed83c1ef4c59.png)

**Comment by jiaqiluo** [comment]
Failed to create ingress in a k8s 1.19 cluster in `master-0390ff5bc542936c93969624c3644ddefb139b52-head` 
 
<img width="1598" alt="Screen Shot 2020-10-22 at 10 40 35 AM" src="https://user-images.githubusercontent.com/6218999/96909626-21fcf880-1453-11eb-8c47-412bc76ec991.png">


<img width="1611" alt="Screen Shot 2020-10-22 at 10 40 02 AM" src="https://user-images.githubusercontent.com/6218999/96909775-5e305900-1453-11eb-9b7e-0a2aac16f9b8.png">

It fails because the parameters in the `backend` section in 1.19 are changed from 
```
      - backend:
          serviceName: svc1
          servicePort: web
```
to 
```
      - backend:
          service:
            name: se2
            port:
              number: 80
```


It continues working in 1.17 and 1.18 clusters, only the 1.19 clusters requires the new parameters

**Comment by jiaqiluo** [comment]
reopen on v2.5-head cb8a175

## Background Information
the supporting matrix  for different versions of Kind: `Ingress` 

| k8s version | networking.k8s.io/v1 | networking.k8s.io/v1beta1 | extensions/v1beta1 |  
| ----------- | -------------------  | ------------------------- | ------------------ |
| **1.17.13**     |                      |            ✔️          |       ✔️             |
| **v1.18.10**    |                      |            ✔️          |       ✔️             |
| **v1.19.3**     |     ✔️                |            ✔️          |       ✔️             |


The `apiVersion` used in the dashboard when creating an `Ingress` as a YAML file 

| k8s version | apiVersion |
| ----------- | ---------- |
| **1.17.13**  |  networking.k8s.io/v1beta1 | 
| **v1.18.10** |  networking.k8s.io/v1beta1 | 
| **v1.19.3**  |  networking.k8s.io/v1      |
 

# issue  

1.17 and 1.18 clusters use the same apiVesion, but the UI in 1.17 misses the `pathType` part

in 1.17
![image](https://user-images.githubusercontent.com/6218999/97529016-446ba600-196c-11eb-84e7-01c7104bedc9.png)

in 1.18 
![image](https://user-images.githubusercontent.com/6218999/97529044-52212b80-196c-11eb-878b-12f8238800c8.png)

**Comment by codyrancher** [comment]
The pathType is shown when it's present in the schema. 

1.18: 
![Screen Shot 2020-10-29 at 9 06 26 AM](https://user-images.githubusercontent.com/55104481/97600443-4f532480-19c6-11eb-99e9-19ee59e3fdb3.png)

1.17:
![Screen Shot 2020-10-29 at 9 05 58 AM](https://user-images.githubusercontent.com/55104481/97600679-8c1f1b80-19c6-11eb-88f1-5106b502239c.png)


I see 1 of three possibilities.
1. pathType was added to an existing version of HTTPIngressPath
2. The backend isn't returning the appropriate schema
3. The front end isn't requesting the correct schema

I believe #1 is the case but the k8s docs I've read haven't made this clear to me. @jiaqiluo do you have docs that could show this one way or another?

**Comment by codyrancher** [comment]
Actually I was just able to find the docs which show 1. is the case.

1.18:
https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#httpingresspath-v1beta1-extensions

1.17:
https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#httpingresspath-v1beta1-extensions

**Comment by jiaqiluo** [comment]
@codyrancher  Thanks for the confirmation!

Since this is expected and not a bug the issue can be closed.

**Comment by jiaqiluo** [comment]
This is the correct docs for apiVersion  networking.k8s.io/v1beta1
1.18 
https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#httpingresspath-v1beta1-networking-k8s-io

1.17
https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#httpingressrulevalue-v1beta1-networking-k8s-io
