### ISSUE TITLE
Pod Security Policy add and list pages

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#164]

**Comment by lvuch** [comment]
https://xd.adobe.com/view/164f1e7a-adc5-4098-6a67-bdd3d30359f1-607e/

**Comment by tfiduccia** [comment]
Need some examples of details page would look like.

**Comment by lvuch** [comment]
updated pages https://xd.adobe.com/view/164f1e7a-adc5-4098-6a67-bdd3d30359f1-607e/

**Comment by tfiduccia** [comment]
No Pod Security?

**Comment by deniseschannon** [comment]
Moving away from PSPs and going with OPA Gatekeeper
