### ISSUE TITLE
[Logging v2] Not selecting Outputs or Cluster Outputs the Edit as YAML generates null from Create Flow

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1641]
Rancher version `v2.5-head (10/07/2020)`  _60d3ff3_

If we don't select an Output or a ClusterOutput the array is left empty (or commented) If we then click Create there's an error in the UI

Only add `globalOutputRefs` or `localOutputRefs` if one was selected in the UI form. (Or include them commented.)

### Steps to Reproduce

- Install Rancher v2.5+
- Navigate to Dashboard
- Install the `rancher-logging` chart
- Navigate to Output and add an Output
- Navigate to Flows and start adding a flow from `Edit as Form`
- Select only the Output and Leave the ClusterOutput empty
- Click `Edit as YAML`
- Leave the generate YAML untouched and click `Create`

`Flow.logging.banzaicloud.io "testflow1" is invalid: spec.globalOutputRefs: Invalid value: "null": spec.globalOutputRefs in body must be of type array: "null"`

![Screen Shot 2020-10-07 at 10 43 16 AM](https://user-images.githubusercontent.com/27659/95367709-ede9db00-0889-11eb-9fd6-2f939b6d38c5.png)

**Comment by codyrancher** [comment]
There's no longer an `Edit as YAML` button so I can't reproduce this.

**Comment by izaac** [comment]
Closing, this feature is no longer in the UI.
