### ISSUE TITLE
network mode in network tab issue

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#1647]
go to create deployments > network tab > select normal network mode

Normal keeps placeholder text/overlaps with selection, but host network works

<img width="431" alt="Screen Shot 2020-10-07 at 9 08 03 PM" src="https://user-images.githubusercontent.com/3013118/95413874-60d27080-08e1-11eb-82a2-8dcd80a9211c.png">
<img width="430" alt="Screen Shot 2020-10-07 at 9 07 55 PM" src="https://user-images.githubusercontent.com/3013118/95413875-616b0700-08e1-11eb-9e59-640ffb53ce7f.png">

**Comment by tfiduccia** [comment]
Fixed
