### ISSUE TITLE
info bubbles don't work

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#1648]
deployments info bubbles do not work:
![image](https://user-images.githubusercontent.com/3013118/95414138-fb32b400-08e1-11eb-93a8-0b84cadeef35.png)

service example of working:
![image](https://user-images.githubusercontent.com/3013118/95414174-169dbf00-08e2-11eb-9c23-53e3dd780594.png)

Deployments has the preferred placement of the `i` by the label, but they do not work

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 1c4b756` and `rancher\rancher:v2.5-head` `version 8639f1a`

Observed info bubble working:
![Screen Shot 2020-10-28 at 4 14 17 PM](https://user-images.githubusercontent.com/57409052/97507204-e920c000-1939-11eb-8258-3e13b118abb5.png)
