### ISSUE TITLE
[Fleet] UI mixes up Git Repo target types

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#1658]
1.  Create a Git Repo using the form and select "Target Type -> No Clusters"
<img width="712" alt="Screenshot 2020-10-13 at 17 39 29" src="https://user-images.githubusercontent.com/3813921/95885470-8e099d80-0d7d-11eb-9ac7-6ecb8535a2e9.png">

2. Notice that the repo overview page shows the "Target" for the created repo is showing "All" instead of "None".
<img width="1408" alt="Screenshot 2020-10-13 at 17 39 56" src="https://user-images.githubusercontent.com/3813921/95885464-8cd87080-0d7d-11eb-95ed-5152ac87aab0.png">

3. Choose "Edit as Form" for that repo and notice that in the "Target Type" dropdown the active item is set to "All clusters in the workspace"

<img width="717" alt="Screenshot 2020-10-13 at 17 40 03" src="https://user-images.githubusercontent.com/3813921/95885458-8a761680-0d7d-11eb-9a24-41f0fb6d899a.png">

4. Modify the Git Repo just by adding a label then click "Save"
5. Notice that the Git Repo is now being applied to all clusters instead of none.

Rancher 2.5.1

**Comment by izaac** [comment]
Reproduced in Rancher version `v2.5.1`

**Comment by izaac** [comment]
Rancher version `master-head (11/02/2020)` _6d4d6b0_
Validated the fix. When selected None it stays as None selected.
Editing or creating with other Target types are also working.

![Screen Shot 2020-11-02 at 4 09 32 PM](https://user-images.githubusercontent.com/27659/97929312-1dbfbd80-1d26-11eb-8c3c-64951a518a24.png)
