### ISSUE TITLE
Spacing around port rules is too skinny

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1666]
Steps:
1.  Go to Services
2.  Click on Create & select ClusterIP
3. Add Port Rules

Results:  The spacing around the fields for port rules is too skinny.  From Lauren in a previous design bug " Spacing around boxes in the port rules is too skinny" --- needs a dev to convert to grid not table.

![image](https://user-images.githubusercontent.com/11514927/96074316-fcc62400-0e6d-11eb-9263-bf966dd33a7a.png)

**Comment by deniseschannon** [comment]
Similar to https://github.com/rancher/dashboard/issues/1303

Fixed when converting port rules to grid.

**Comment by tfiduccia** [comment]
Fixed
