### ISSUE TITLE
Update Navigation for Monitoring

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1667]
Create an `Advanced` section that allows you to show/hide (hide by default) that has AlertManager and Promethis hidden when first going to Monitoring

**Comment by jiaqiluo** [comment]
This is validated on rancher:`v2.5-0465f049780def811e00ab32067f95734f6a88f5-head` single-install with the latest UI 

The `advanced` section is added and folded by default. 
<img width="250" alt="Screen Shot 2020-10-29 at 11 36 52 AM" src="https://user-images.githubusercontent.com/6218999/97617584-2c7f3b00-19db-11eb-9518-ca072f8c1a0f.png">
<img width="253" alt="Screen Shot 2020-10-29 at 11 37 01 AM" src="https://user-images.githubusercontent.com/6218999/97617592-2e48fe80-19db-11eb-9738-14230c13a28b.png">
