### ISSUE TITLE
Add tooltip/help text on monitoring deployment page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1668]
- [ ] "Create Default Monitoring Cluster Roles”
- [ ] “Aggregate to Default Kubernetes Roles” 

Those options exist on the deployment page and need help text on what this means

**Comment by aiyengar2** [comment]
Option | Help Text |
---|---|
Create Default Monitoring Cluster Roles | Creates `monitoring-admin`, `monitoring-edit`, and `monitoring-view` ClusterRoles that can be assigned to users to provide permissions to CRDs installed by the Monitoring chart.
Aggregate to Default Kubernetes Roles | Adds labels to the ClusterRoles deployed by the Monitoring chart to [aggregate to the corresponding default k8s admin, edit, and view ClusterRoles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles)

**Comment by jiaqiluo** [comment]
This is validated on rancher:`v2.5-0465f049780def811e00ab32067f95734f6a88f5-head` single-install with the latest UI 

for `Create Default Monitoring Cluster Roles`
<img width="1245" alt="Screen Shot 2020-10-29 at 11 03 47 AM" src="https://user-images.githubusercontent.com/6218999/97613989-9ba66080-19d6-11eb-8fae-bbaf40e1905a.png">


for `Aggregate to Default Kubernetes Roles` 
<img width="989" alt="Screen Shot 2020-10-29 at 11 03 52 AM" src="https://user-images.githubusercontent.com/6218999/97613998-a103ab00-19d6-11eb-9c4a-fde22235ecb8.png">
