### ISSUE TITLE
[Monitoring V2 UI] Add grouping to the navigation bar

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1669]
At the current moment, the navigation bar for monitoring looks like the screenshot attached below:

![Screen Shot 2020-10-15 at 2 09 19 PM](https://user-images.githubusercontent.com/13127443/96186261-055f3e80-0ef0-11eb-869a-bec129fded25.png)

However, in order to make the purpose of these CRs clearer / easier to use, it would be nice if we could introduce some sort of grouping in the monitoring pane such as:

Group | CR / Custom UI |
---|---|
Scrape Targets | ServiceMonitors, PodMonitors
Prometheus Rules | PrometheusRules
Alerting Configuration | [Routes](https://github.com/rancher/dashboard/issues/1239), [Receivers](https://github.com/rancher/dashboard/issues/1238)
More Resources | Prometheis, AlertManagers

Eventually, `Probes` will be added to Scrape Targets too once the upstream chart has moved to the newer version of Prometheus Operator that supports that.

**Comment by maggieliu** [comment]
won't do
