### ISSUE TITLE
Secrets UI Issue

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#167]
Date - 12/2/19

Create Secret Page: 

- [x] Value field is not wide enough
![image](https://user-images.githubusercontent.com/11514927/70075737-9a986380-15ba-11ea-805a-b1ae4f097768.png)

- [x] the Key/Value fields should probably be much smaller?  they don't need to take up the whole space.  But if they do, they need to match the Name/Namespace.
![image](https://user-images.githubusercontent.com/11514927/70075824-c1569a00-15ba-11ea-9a72-3e7077542456.png)

- [x] Cancel should be on the left with Create button on the right.
![image](https://user-images.githubusercontent.com/11514927/70076671-8190b200-15bc-11ea-98f3-f6050657911f.png)

- [x] Default focus should be on Secret Name when you first get into Create Secret.  Right now there is no focus.

**Comment by lvuch** [comment]
I can't do the last one @mantis-toboggan-md or @vincent99 can you?

**Comment by tfiduccia** [comment]
Date - 12/11
Verified fixed
