### ISSUE TITLE
empty array in method dropdown

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#1675]
<img width="387" alt="Screen Shot 2020-10-19 at 9 30 50 AM" src="https://user-images.githubusercontent.com/3013118/96481642-6fc5f680-11f0-11eb-8a74-a0afc55f9bba.png">

on create resource of rio the method dropdown has `[]` showing up in the dropdown

**Comment by nwmac** [comment]
We've removed Rio, so this is no longer applicable
