### ISSUE TITLE
NotApplicable tests appear first in a CIS scan v2 report

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1681]
**Verified on 2.5-head - commit id: `9d3882175`**

- Deploy CIS v2 app in Dashboard
- Navigate to CIS benchmarks on the top left menu.
- Run scan. Wait for the scan to finish.
- Click on the scan (which might show Pass/fail)
- Tests are sorted. But the NotApplicable tests appear first and then the tests that have "Passed"

<img width="983" alt="Screen Shot 2020-10-20 at 6 39 16 PM" src="https://user-images.githubusercontent.com/26032343/96590414-9de82b00-1303-11eb-811b-937734727ec2.png">

Can we have the tests in "Pass"/Fail/Skipped state to appear first ? Not Applicable tests can be available in the end of the report.

**Comment by maggieliu** [comment]
State order should be Fail, Pass, NA

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `f6712924`**

- Add repo https://github.com/mrajashree/charts and branch cis16
- Install CIS v2 charts
- On a custom cluster, run Hardened rke profile scan. The tests are sorted in order - Fail, Warn, Pass and N/A
- The tests are NOT sorted - logging a separate bug to track this - https://github.com/rancher/dashboard/issues/1901
