### ISSUE TITLE
Tooltip for CIS Profile Create doesn't make sense for that field.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1686]
Issue:  Tooltip for the Test to Skip doesn't make sense?  Since there is no key/value fields?
![image](https://user-images.githubusercontent.com/11514927/96772687-5d86bc80-1398-11eb-8c46-4da6de815016.png)

Resolution:  Take out tooltip.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `71da1569`**

- Tool tip reads:
<img width="424" alt="Screen Shot 2020-11-17 at 11 29 17 PM" src="https://user-images.githubusercontent.com/26032343/99483702-c710d100-292c-11eb-95de-f3d9e6905e27.png">

- Bulk entry works.
