### ISSUE TITLE
Ability to view when an upgrade is available for a chart

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1692]
When a chart has a new version, show that an upgrade is available

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `d87f58a`**

- deploy `rancher-cis-benchmark:1.0.100` or `rancher-logging:3.6.000`.
- Upgradable column has the version available, to which the chart can be upgraded to

<img width="1633" alt="Screen Shot 2020-10-26 at 10 46 25 AM" src="https://user-images.githubusercontent.com/26032343/97208777-be3b3e00-1778-11eb-8113-66a181b56217.png">

- When `rancher-cis-benchmark:1.0.200` is deployed, the Upgradable field is `-`
<img width="1293" alt="Screen Shot 2020-10-26 at 10 47 20 AM" src="https://user-images.githubusercontent.com/26032343/97208774-bbd8e400-1778-11eb-807a-41f950935efc.png">
