### ISSUE TITLE
Update Secrets UI/UX

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1702]
Secrets Create/Edit
-  Move subtype to cruresource and remove subtype dropdown (Tracked in https://github.com/rancher/dashboard/issues/841)

- [ ] Add tabs 
    - Tab 1 - Data - keep the same content that exists today into this tab
    - Tab 2 - Labels and Annotations - use the LabelsAndAnnotations component, which should cause the labels to be stacked on top of the annotations and it should be full width in the tab. 

- [ ] Registry Subtype - Update header from `Type Registry` to `Registry`. Update header to H3 @lvuch to confirm sizing

Secrets Detail
- [ ] For each subtype, we should change the way the data is presented based on the type. Currently it's showing up as a key value table for everything, but it should only be key value table for opaque secrets. The other types should match how we presented the creation of the subtype of secrets.
- [ ] Value in secret needs to be treated as sensitive info -> I think we decided to go with *** on the detail view and you can edit it to see the actual content. 
- [ ] Add related workloads info, which could be a table of workload names? @vincent99 to help add what other detail should be part of the related workloads info

**Comment by lvuch** [comment]
https://xd.adobe.com/view/3cf0dddb-70e3-4309-885f-f8d847399a0d-69a3/

**Comment by tfiduccia** [comment]
Verified fixed
