### ISSUE TITLE
Ingress Inconsistencies

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1706]
Ingress Edit
Inconsistency between rules/certificates.
- Rules are in boxes

<img width="965" alt="Screen Shot 2020-10-27 at 3 13 03 PM" src="https://user-images.githubusercontent.com/11410997/97367771-f1f49180-1866-11eb-8170-a48c5ea5268a.png">

- certificates are free forming text with a line between them to separate certs, but not in a box
<img width="993" alt="Screen Shot 2020-10-27 at 3 13 32 PM" src="https://user-images.githubusercontent.com/11410997/97367808-0042ad80-1867-11eb-81a1-4b23abae4e2c.png">

Ingress Detail
- Labels and Annotations are not part of detailtop

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `71da1569`**

- Rules and certificates are in boxes
<img width="925" alt="Screen Shot 2020-11-17 at 11 32 11 PM" src="https://user-images.githubusercontent.com/26032343/99484026-85ccf100-292d-11eb-9235-ee363a34c3e3.png">
<img width="929" alt="Screen Shot 2020-11-17 at 11 31 59 PM" src="https://user-images.githubusercontent.com/26032343/99484033-88c7e180-292d-11eb-9588-b461272b9946.png">

- Labels and Annotations are part of detailtop as well as the detail section.
<img width="554" alt="Screen Shot 2020-11-17 at 11 34 36 PM" src="https://user-images.githubusercontent.com/26032343/99484083-a39a5600-292d-11eb-9ca8-3dbea592f891.png">

**Expected:**
It should be part of ONLY detail top.
Reopening the issue

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `9ee39b9`**

- Labels and annotations are available as
<img width="1173" alt="Screen Shot 2020-12-01 at 8 50 03 AM" src="https://user-images.githubusercontent.com/26032343/100774508-015f8100-33b7-11eb-87a0-a5bdd991e8c4.png">
