### ISSUE TITLE
Cluster Explorer shows specs of one node instead of all nodes

### ISSUE THREAD

**Issue by aneeldadani** [rancher/dashboard#1711]
The Cluster Explorer shows the CPU and memory of the primary node: 
<img width="1426" alt="Cluster Explorer" src="https://user-images.githubusercontent.com/40775413/97457144-b4d7e000-18f6-11eb-801b-0c2b5885ad44.png">

However, when I go to the Cluster Dashboard it shows me the specs based on all of the nodes:
<img width="1250" alt="Cluster Dashboard" src="https://user-images.githubusercontent.com/40775413/97458082-97efdc80-18f7-11eb-9755-9656d2997258.png">

I would expect the Cluster Explorer to show me the CPU and memory overall and tells me the individual node specs when I click on the individual node.

This is not urgent, just a nice to have.

**Comment by codyrancher** [comment]
This appears to be resolved in the latest version of rancher.

![image](https://user-images.githubusercontent.com/55104481/102794235-4f3d2880-4368-11eb-8a3b-5b3826af9daf.png)
![image](https://user-images.githubusercontent.com/55104481/102794257-595f2700-4368-11eb-8d4f-a88117241b6e.png)
![image](https://user-images.githubusercontent.com/55104481/102794271-60863500-4368-11eb-92a2-364cd4343e73.png)

Verified this on a 2 node k3s cluster.

**Comment by sadiapoddar** [comment]
Verified on master-head, commit 5da52c0
1. Cluster Explorer dashboard now shows the overall resource reserved and usage percentage. 
2. Currently cluster explorer dashboard you get an overview of the cluster resource usages as the amber UI page.
3. I am seeing one discrepancy, Amber UI shows the 14% pod used at the same time Explorer dashboard is showing "14% pod reserved. The terms used and reserved mean two different things in virtualization. 

Amber UI

<img width="1575" alt="amber-ui" src="https://user-images.githubusercontent.com/72409237/103322108-b0609e00-49f1-11eb-9d2f-3858191efea0.png">

Cluster Explorer Dashboard. 

<img width="1247" alt="Screen Shot 2020-12-29 at 3 52 24 PM" src="https://user-images.githubusercontent.com/72409237/103322143-dab25b80-49f1-11eb-8ef9-5cf14f46acd7.png">

Reopening this bug to fix the issue.

**Comment by vincent99** [comment]
There's a PR merged to change the word, which is fine I guess.

But "reserved" vs "used" are really the same thing for pods.  They are not a variable resource like CPU/Memory where you can ask for one amount but consume a different amount. A pod either exists or it doesn't, which is why there's only one gauge for it.

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, 6c03627 
The CPU, memory, and pod consumption stats match between what listed in Cluster Explorer and Cluster Manager views.

Cluster Explorer

<img width="1493" alt="Screen Shot 2021-01-06 at 3 51 28 PM" src="https://user-images.githubusercontent.com/72409237/103834226-afee8580-5037-11eb-8b45-85ddcd6884ed.png">

<img width="1377" alt="Screen Shot 2021-01-06 at 3 58 38 PM" src="https://user-images.githubusercontent.com/72409237/103834540-884bed00-5038-11eb-94d1-2a72c32de961.png">
