### ISSUE TITLE
Cannot add credentials for private Helm repository in new Apps and Marketplace

### ISSUE THREAD

**Issue by axeljnilsson94** [rancher/dashboard#1713]
kind: feature request/enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Have a private repository that requires credentials
2. Try to add the repository for usage in the Apps and Marketplace section of the Cluster Explorer (any cluster)

**Result:**
No API Version found
However the helm repository clearly indicated a HTTP 401 error.

**Other details that may be helpful:**

**Environment information**
On Prem, Airgapped installation
Rancher 2.5.1
Rancher RKE HA (3 node setup) with several downstream clusters

**Cluster information**
- Cluster type: vSphere provider or RKEd
- Kubernetes version 1.18.9

- Docker version (use `docker version`):

Docker version: 19.3.8

gz#13190

**Comment by thedadams** [comment]
Hi @axeljnilsson94! Thank you for submitting the request. We will be investigating this so that we can add it to the UI. For now, we have the following workaround:

1. Create a Kubernetes secret. You can use this or an equivalent command. The type must be `kubernetes.io/basic-auth`:
```
kubectl -n NAMESPACE create secret generic NAME_YOUR_SECRET --from-literal=userame=YOUR_USERNAME --from-literal=password=YOUR_PASSWORD --type=kubernetes.io/basic-auth
```
2. In the Cluster Explorer Rancher UI, choose "Edit as YAML" for the repo you are adding:
<img width="1512" alt="Screen Shot 2020-10-28 at 12 53 58 PM" src="https://user-images.githubusercontent.com/3682717/97490462-1eb7b000-191e-11eb-9fa9-ed11fc480fd4.png">

3. Add the `clientSecret` in the `spec` object:
```
spec:
    ...
    clientSecret:
        name: NAME_YOUR_SECRET
        namespace: NAMESPACE
```

**Comment by axeljnilsson94** [comment]
Hi!

This resolves the problem for now. I am looking forward to the reconciling feature for the UI.
Thank you!

Best regards
Axel

**Comment by ansilh** [comment]
Hi @thedadams ,
Adding git is not working with the workaround.
Looks like we are not passing the password for 'basic' auth.

```
Request 

GET /mycompany/myproject.git/info/refs?service=git-upload-pack HTTP/1.1
Host: gitea.ansil.io:3000
User-Agent: git/2.17.1
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

Response 

HTTP/1.1 401 Unauthorized
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie: i_like_gitea=7569068d2a016270; Path=/; HttpOnly
Set-Cookie: _csrf=GGmbuGhBeqrj8rkXjQZ43MGpN8U6MTYwNTAwNzQ5Njk5MTc1OTM4Mw; Path=/; Expires=Wed, 11 Nov 2020 11:24:56 GMT; HttpOnly
Www-Authenticate: Basic realm="."
X-Frame-Options: SAMEORIGIN
Date: Tue, 10 Nov 2020 11:24:56 GMT
Content-Length: 0

Request 

GET /mycompany/myproject.git/info/refs?service=git-upload-pack HTTP/1.1
Host: gitea.ansil.io:3000
Authorization: Basic cmFuY2hlcnRlc3Q6 #<------- ie "ranchertest:" ; password field is missing 
User-Agent: git/2.17.1
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

Response 

HTTP/1.1 401 Unauthorized
Content-Type: text/plain
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie: i_like_gitea=71eb2c790c9ee859; Path=/; HttpOnly
Set-Cookie: _csrf=hxmQ9-dGXwUUNLT67bB4DvYO03g6MTYwNTAwNzQ5NzAwMTQxNTAzMw; Path=/; Expires=Wed, 11 Nov 2020 11:24:57 GMT; HttpOnly
X-Frame-Options: SAMEORIGIN
Date: Tue, 10 Nov 2020 11:24:57 GMT
Content-Length: 40

invalid credentials from 192.168.110.190

```

**Comment by mogoman** [comment]
For http an alternative is the form http://user:pass@url (I documented it here https://github.com/rancher/rancher/issues/30909)

**Comment by vincent99** [comment]
QA: Fleet->GitRepo already had a similar thing to select or create a secret, so that was refactored here into a component both app GitRepo and fleet ClusterRepo share; be sure to check both.

**Comment by Ellenqs** [comment]
Validated on rancher `v2.5-head, 3c4c625`.

**Steps**

- Clone the rancher charts/fleet repo to private repo. 
   (https://github.com/rancher/charts)
   (https://github.com/rancher/fleet-examples)
- Deploy rancher single install.

1. Validate fleet repo.
      
  - Go to cluster explorer -> continuous delivery -> create Git repo -> authentication
         -- https
             Provide git repo url, username, password.
             Result: Git repo created, bundles deployed successfully.
         -- ssh
             Provide git repo url, public key, private key.
             Result: Git repo created, bundles deployed successfully.

2. Validate cluster repo.

   - Go to cluster explorer -> Apps & marketplace ->  -> create cluster repo -> authentication
         -- https
             Provide git repo url, username, password.
             Result: cluster repo created, charts deployed successfully.
         -- ssh
             Provide git repo url, public key, private key.
             Result: 1. The UI shows the authentication option and can be added. 
                         2. After add the keys, when create cluster repo, error occurred. 
           
<img width="1256" alt="Screen Shot 2021-02-10 at 9 39 19 AM" src="https://user-images.githubusercontent.com/75277058/107594703-6c071700-6bc7-11eb-9b29-a63f4e0938a2.png">

  Dashboard UI works, so close this one.

 For the error, log a new bug, will add the link.
