### ISSUE TITLE
Move "Schedule" section out of Container tab & change replica to number only field

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1717]
Section: Create Workloads

- [ ] Change replica field for all Workloads to be numbers only (it should have the scrolls).  Also It should just be it's inherit width, it doesn't need call span or specific width.

- [ ] Page: Create Deployment - Move Replicas out of Container tab to section above

- [ ] Page: Create Cronjob - Move Schedule out of Container section to top

- [ ] Page: Create DaemonSet, Job - Remove Schedule section (it's there with no fields in it)

- [ ] Page: Create StatefulSet - remove Replicas & service name fields out of Container to top

**Comment by lvuch** [comment]
@tfiduccia @mantis-toboggan-md added nancy as discussed on yesterday's call

**Comment by tfiduccia** [comment]
Verified fixed
