### ISSUE TITLE
All create pages should have * for required fields

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1719]
- [x] On all pages, the option to turn them off when there is data in field should be turned off.  * should show all the time for required fields

Create Services - Only Name is * on all types although other fields are required.  
- [x] ClusterIP, Headless, LoadBalancer & NodePort - Listening & Target ports are required
- [x] ExternalName - External Name is required

Create Secret - Only Name is * on all types even though other fields are required
- [x] Registry type - Artifactory & Custom - Registry Domain Name is required
- [x] Certificate & SSH Key - Public Key, CA Certificate & Private Key are required
- [x] HTTP Basic Auth - Username is required

Create

**Comment by vincent99** [comment]
@tfiduccia I did the if-empty part in the great details overhaul..

**Comment by sadiapoddar** [comment]
Verified on 2.5-head v2.5-be72f96

request -1
On all pages, the option to turn them off when there is data in the field should be turned off. * should show all the time for required fields

Verified, currently, all the required fields showed it's required only during reedit not in the list view.

request-2

Create Secret - Only Name is * on all types even though other fields are required

 Registry type - Artifactory & Custom - Registry Domain Name is required
 Certificate & SSH Key - Public Key, CA Certificate & Private Key are required
 HTTP Basic Auth - Username is required

Verified all the secret creation pages and now all the required fields are marked with *

request -3

Create Services - Only Name is * on all types although other fields are required.

 ClusterIP, Headless, LoadBalancer & NodePort - Listening & Target ports are required
 ExternalName - External Name is required

Verified, most of these types has the * with all the required field external Name

<img width="1521" alt="Screen Shot 2021-01-07 at 3 30 47 PM" src="https://user-images.githubusercontent.com/72409237/103956841-3372aa00-50fe-11eb-9d04-73f2e59e23b3.png">

Closing this bug and will file a separate bug on the external name creation required fields.

**Comment by sadiapoddar** [comment]
https://github.com/rancher/dashboard/issues/2179
