### ISSUE TITLE
Fix Spacing Issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1720]
Issue:  The spacing between fields and rows are the not same on any of the pages.

Resolution:  Determine set spacing for
Top of page & main header
Between field on same row
Between sub-header & first field below it
Between top of tabbed section & first sub-header text
Between fields horizontally
(other areas?)

This spacing should reflect the same no matter if they are individual controls or in tables.  Same spacing should apply.

**Comment by sadiapoddar** [comment]
Verified on master-head, 5da52c0
The component template has the readjusted spacing between title, subheader, text box, and the space between the same field of the rows. This change reflects on all the create form and display forms of the components. 

An example of the previous "Deployment Create" form in 2.5.3 

<img width="1578" alt="Screen Shot 2020-12-30 at 3 00 27 PM" src="https://user-images.githubusercontent.com/72409237/103385589-efedbf80-4aaf-11eb-9fdf-fa4062822380.png">


After the fix, the new form looks like the following

<img width="1710" alt="Screen Shot 2020-12-30 at 2 59 25 PM" src="https://user-images.githubusercontent.com/72409237/103385577-e6645780-4aaf-11eb-86ef-67fded3b3fa0.png">
