### ISSUE TITLE
Drop-down border doesn't line up & cursor is misplaced

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1725]
- [x] Drop-down border does not line up
![image](https://user-images.githubusercontent.com/11514927/97510250-95b27000-1941-11eb-9ba4-35771e022f42.png)

- [x] In light mode the border doesn't even cover the bottom part
![image](https://user-images.githubusercontent.com/11514927/97510417-e7f39100-1941-11eb-95c1-913c12ee97fb.png)

- [x] In namespace drop-down for create, the cursor & text is too high.  It's touching the "Namespace" label.
![image](https://user-images.githubusercontent.com/11514927/97510482-0d809a80-1942-11eb-8535-581e9058f371.png)

- [x] In Dark mode, drop-downs with scroll, you can't see the scroll bar
Dark version:
![image](https://user-images.githubusercontent.com/11514927/97648638-7a636580-1a12-11eb-9ea7-3088d05de1f2.png)

**Comment by lvuch** [comment]
@tfiduccia 
<img width="1100" alt="Screen Shot 2020-11-04 at 9 16 26 AM" src="https://user-images.githubusercontent.com/3013118/98136677-6e4a2e80-1e7e-11eb-8c4a-cfbfbb173110.png">

**Comment by tfiduccia** [comment]
Verified fixed
