### ISSUE TITLE
Node & Pod Selector section need to be redesigned

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1726]
The Node & Pod selector section in create workload needs to be redesigned.

- [ ] Redo headers
- [ ] Change text (confusing?)
- [ ] Make differences between Required & Prefer more identifiable.
- [ ] Use the new standard for our "block" control

![image](https://user-images.githubusercontent.com/11514927/97510725-98619500-1942-11eb-8b95-1fe94a1a286e.png)
![image](https://user-images.githubusercontent.com/11514927/97510745-a3b4c080-1942-11eb-8de8-79475eab062c.png)

**Comment by tfiduccia** [comment]
Vincent and I took a look:  Here are his comments.
Pod Selector:
1 button for Pod selector
At start - 1 drop-down with the 4 choices
reorder so that it is Namespace, Rule, then topology.
Add tooltip to Topology
Multi-select
Topology default should be kubernetes.io/hostname (maybe drop-down with standards)

Node Selector:
Specific nodes should only be node name, cause key/Value is on other radio
Doesn't like that there isn't a None option for the radio (should that be a third option)
Change selector section to match the pod selector section

**Comment by lvuch** [comment]
<img width="386" alt="Screen Shot 2020-11-23 at 12 25 23 PM" src="https://user-images.githubusercontent.com/3013118/100000270-f8532c00-2d86-11eb-8f17-299a24cfed78.png">

**Comment by tfiduccia** [comment]
Verified fixed
