### ISSUE TITLE
Add option to create a service when setting a Port in workloads

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1728]
Issue:  In rancher 2.4 and before, when we created a deployment and added a port it automatically created a service and opened the port.  I could easily click on the port link in list page and see my app functioning.  We lost that ability in the new UI.

Resolution:  Add an option on in the port section for workloads to create service and open the port.  Then display available external port.

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, commit be72f96

1. Created a "Damemonset" workload
2. During add port selected "create service" check
3. Provided container internal port, public port
4. The daemonset workload created successfully on each worker node but the endpoint is not routable
5. The endpoint it creates not using the public port but it uses the container internal port 80
<img width="1018" alt="Screen Shot 2021-01-07 at 2 53 47 PM" src="https://user-images.githubusercontent.com/72409237/103954228-9eb97d80-50f8-11eb-9c15-a0f38dbf30f8.png">
<img width="878" alt="Screen Shot 2021-01-07 at 2 54 08 PM" src="https://user-images.githubusercontent.com/72409237/103954235-a1b46e00-50f8-11eb-982f-653402f46c20.png">
<img width="1227" alt="Screen Shot 2021-01-07 at 2 49 37 PM" src="https://user-images.githubusercontent.com/72409237/103954240-a416c800-50f8-11eb-8d22-83343bccda97.png">

**Comment by mantis-toboggan-md** [comment]
I think in order to validate this issue, both the endpoints listed in the workload table need to be correct, and the service(s) themselves need to be correct. To be in keeping with the Ember UI, clusterIP services are given the same name as the workload and nodeport ip services are given the name with `'-nodeport'` appended.

**Comment by sadiapoddar** [comment]
Verified the fix on 2.5-head, v2.5-24c32a358 
I am seeing the "check" box is not there anymore but we add a new option in the dropdown "Do not create service".

1. Created some daemonset services
2. Verified the created service in amber UI and Explorer View
3. Service creation was successful
4. Created a clone of the service created in Explorer view
5. The service endpoints display issue is fixed
6. There is still an issue with the service link endpoint created in Explorer View. 
7. The explorer view shows the created service endpoint with the container internal ports, these ports are not routable.
8. 
9. The explorer view endpoints link, not routable. Port 80 is the internal port of the pod.

<img width="1525" alt="Screen Shot 2021-01-27 at 1 17 06 PM" src="https://user-images.githubusercontent.com/72409237/106058869-b1472700-60a6-11eb-8062-b7174f963271.png">

10. In Amber UI, the endpoints link are created with external ports, the links are routable

<img width="1377" alt="Screen Shot 2021-01-27 at 1 17 32 PM" src="https://user-images.githubusercontent.com/72409237/106059026-ee131e00-60a6-11eb-96f1-8c38f6de939b.png">


Expected if we want to display the endpoint link,  we do it with the external ports.

**Comment by sadiapoddar** [comment]
Verified the fix on 2.5-head,  761c805
Test1: During the "node port" service create public port was given by the user

- Created  a daemonset service of type "node port", during creating the service public port was given as 9999
- Service creation was successful
- The service endpoint link got created successfully. The endpoint is routable. 
- But it creates two endpoints for the service,  one with the user given port "9999" other with a random port "

<img width="1026" alt="Screen Shot 2021-02-11 at 5 43 57 PM" src="https://user-images.githubusercontent.com/72409237/107721813-6d514600-6c92-11eb-8bb5-75ce7ef2b913.png">

It's expected that daemonset service should create one service endpoint per node. 
In case the public port is specified by the user then the service should be exposed only to that port. 

Test2: During node port service creation, no port was specified
This time service creation was successful and only created one service endpoint by picking a random port, which is expected

<img width="900" alt="Screen Shot 2021-02-11 at 6 06 17 PM" src="https://user-images.githubusercontent.com/72409237/107722525-edc47680-6c93-11eb-985f-7b0768a4109b.png">

Hi @mantis-toboggan-md
please fix the issue in the test1.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:v2.5-head` `version 87006de`

When setting a port in workloads, user is given an option to create a service:
![Screen Shot 2021-02-24 at 5 01 42 PM](https://user-images.githubusercontent.com/57409052/109191785-ba81ed00-7753-11eb-8193-b55f665198df.png)

Steps:
Create a daemonset. Specify listening port and create a `node port` service:
![Screen Shot 2021-02-25 at 10 17 22 AM](https://user-images.githubusercontent.com/57409052/109192346-53186d00-7754-11eb-8a38-3c82b97f9c45.png)

The endpoint is seen with the specified port:
![Screen Shot 2021-02-25 at 10 17 37 AM](https://user-images.githubusercontent.com/57409052/109192399-6297b600-7754-11eb-9b96-2cfcf5121315.png)

On ember UI, the endpoint is also seen:
![Screen Shot 2021-02-25 at 10 20 44 AM](https://user-images.githubusercontent.com/57409052/109192442-7216ff00-7754-11eb-8214-f8845cb2aea1.png)

**Comment by aaronRancher** [comment]
Ran a few validations tests:
Validated that services created through workload creation have `-nodeport` appended:
![Screen Shot 2021-02-25 at 2 34 04 PM](https://user-images.githubusercontent.com/57409052/109220779-8ff55b80-7776-11eb-9e1b-8b2f8991493f.png)

Validated that 1 endpoint is created if 1 port/service is added. And the correct number of endpoints are shown if multiple ports/services are added.
![Screen Shot 2021-02-25 at 2 38 04 PM](https://user-images.githubusercontent.com/57409052/109222868-190c9280-7777-11eb-9492-ad54403663e7.png)
Service view:
![Screen Shot 2021-02-25 at 2 37 28 PM](https://user-images.githubusercontent.com/57409052/109222870-190c9280-7777-11eb-952a-d3dc1134f091.png)

If the workload is deleted, the services created are also deleted.

Able to create the following services through workload creation:
- ClusterIP
- Node Port
- Load Balancer

Validated that no service was created if the user selects `Do not create a service`

**Comment by aaronRancher** [comment]
Validated endpoints are available in every service type (ClusterIP, Node Port, Load Balancer).
