### ISSUE TITLE
External Service UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#173]
Date - 12/3/19

Results:
- [x] The target radio options should be horizontal not vertical with the field below
![image](https://user-images.githubusercontent.com/11514927/70080607-1945ce80-15c4-11ea-85d1-24db9dd41acc.png)

- [x] Space needs to be added between the Name/Namespace and Target title as well as between Target title and radio options.
![image](https://user-images.githubusercontent.com/11514927/70080663-337fac80-15c4-11ea-9428-70602e6b0fd8.png)

- [x] The Service list drop-down needs to be bigger and the "Select a Service" text needs to show up instead of it being empty.
![image](https://user-images.githubusercontent.com/11514927/70080714-4a260380-15c4-11ea-93fd-f02ebed5c59d.png)

- [x] Spacing needs to be added when I select list of IP Addresses from Target 
![image](https://user-images.githubusercontent.com/11514927/70080811-80fc1980-15c4-11ea-8ceb-6408ed590513.png)

- [x] Probably a little space needs to be added as well when I select DNS name
![image](https://user-images.githubusercontent.com/11514927/70080870-9a9d6100-15c4-11ea-87a1-cf60953914b6.png)

- [x] Cancel needs to be first and Create on right of it.
![image](https://user-images.githubusercontent.com/11514927/70080897-a852e680-15c4-11ea-944f-cd92d73dff5c.png)

**Comment by lvuch** [comment]
I'll need @mantis-toboggan-md to fix the drop down
