### ISSUE TITLE
500 Internal Server Error when deleting apps in dashborad

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#1734]
bug, latest UI on rancher:`v2.5-cb8a1755ccd1ed7186c24e582e6fc91fa06f87ec-head` 

500 Internal Server Error is returned when trying to delete an app 

<img width="779" alt="Screen Shot 2020-10-28 at 7 07 30 PM" src="https://user-images.githubusercontent.com/6218999/97516760-12007f80-1951-11eb-9138-eb62ba9c3120.png">

The response is `EOF`

**Comment by sowmyav27** [comment]
Closing this issue in favor of this one - https://github.com/rancher/dashboard/issues/1234
