### ISSUE TITLE
Clear button for searchable drop-downs is in wrong place & can't see bottom of x

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1736]
Issue:
- [x] For the namespace field in create, the x is not in the proper place.  It's floating in the middle of the field
![image](https://user-images.githubusercontent.com/11514927/97623718-54729c80-19e3-11eb-884a-b3f8d40362b2.png)

- [x] For all searchable drop-downs, the x is either too big or not positioned correctly, because the bottom of the x fades out.
![image](https://user-images.githubusercontent.com/11514927/97623813-6e13e400-19e3-11eb-999b-14ff7f3bb62d.png)

**Comment by westlywright** [comment]
I am going to hide `x` as the button is a webkit based browser component only. Additionally it is hidden by default by v-select, there was just a bug in our CSS that caused it to show back up.

**Comment by tfiduccia** [comment]
Verified fixed
