### ISSUE TITLE
Need a single design for the Block component

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1737]
Issue:  We are currently using 3 different styles for the Add block.  We need to have a single design that all of them should follow.

Workload Create:  Node & Pod Scheduling
![image](https://user-images.githubusercontent.com/11514927/97624064-ccd95d80-19e3-11eb-9d11-d21f62fd5dd1.png)

OPA Gatekeeper:  Create Constraint
![image](https://user-images.githubusercontent.com/11514927/97624130-e5497800-19e3-11eb-8335-9b799c346b7a.png)

Loggings:  Create ClusterFlow
![image](https://user-images.githubusercontent.com/11514927/97624241-132ebc80-19e4-11eb-9a96-b78029853968.png)

**Comment by lvuch** [comment]
Node is using component `simple-box`, opa using `.box`, I can't get logging working to check what class/component it is using. It would be preferred to use a component like `simple-box` and style it from there.

**Comment by tfiduccia** [comment]
All areas using "block component" that need to be verified:

Cluster Explorer:
- [ ] All Workload create - Add Volume
- [ ] All Workload create - Node & Pod scheduling
- [ ] StatefulSet create - Add Volume Claim Template
- [ ] Ingress create - Add rule

Logging:
- [ ] ClusterFlow & Flow Create - Add & Exclude Rules

Monitoring:
- [ ] Create Receiver - Slack, Email & Webhook config

OPA:
- [ ] Create Constraint - Add Kind

**Comment by tfiduccia** [comment]
Everywhere but Logging application = Create ClusterFlows & Flows
![image](https://user-images.githubusercontent.com/11514927/99740022-5633fb00-2a8b-11eb-80f5-cfc171a806cc.png)

**Comment by lvuch** [comment]
These all look the same now but @codyrancher pointed out that not all are using `<ArrayListGrouped>` and the preference would be for all to use the same component for maintenance

**Comment by tfiduccia** [comment]
Hate to say it, but logging still isn't correct?  Is that a third component ?

**Comment by tfiduccia** [comment]
Thanks!  Verified fixed
