### ISSUE TITLE
Create a Import Yaml button.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1745]
We want an import YAML button that is on top with the Namespace drop-down that allows you to import any YAML and will automatically create a resource or multiple resources at once.  Instead of having to go to the resource list page and use the Edit YAML.

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, commit 24c32a3
Don't see the fix, there is a "YMAL" button but no drop down is available to pick the namespace as this issue requested.

**Comment by vincent99** [comment]
The API is currently only in master..

**Comment by vincent99** [comment]
PR for support in 2.5 API: https://github.com/rancher/rancher/pull/31051

**Comment by sadiapoddar** [comment]
@vincent99 
Verified the fix on 2.5-head,  commit 5f3fcb84, 
1. Created a cluster
2. Within the cluster created a project, ns, some deployments
3. By selecting the namespace try to import the yml file using the import button, but the import button is inactive 
4. Tried to import yml file from default namespace, the same thing import button is not active

<img width="1498" alt="Screen Shot 2021-02-03 at 5 04 52 PM" src="https://user-images.githubusercontent.com/72409237/106830052-289a2f00-6642-11eb-8be2-c1ed57b62154.png">

Reopening the bug, since the import button should take the users to import an yml file

**Comment by vincent99** [comment]
Ok _this time_ the API is in 2.5-head; the button is just enabled/disabled by the presence of the API.

**Comment by sadiapoddar** [comment]
Verified the fix on v2.5-head, 761c805
1. Created a few namespaces
2. Created a simple ymal file

3. selected those namespaces 

<img width="350" alt="Screen Shot 2021-02-11 at 4 00 41 PM" src="https://user-images.githubusercontent.com/72409237/107715086-5c4d0880-6c83-11eb-8a89-d734078c1631.png">


4. imported the ymal file by selecting "Read from File"

<img width="754" alt="Screen Shot 2021-02-11 at 4 01 19 PM" src="https://user-images.githubusercontent.com/72409237/107715117-6e2eab80-6c83-11eb-8ca7-e3c47752c7ae.png">


5. once clicked on import, it imported and applied the changes to the selected namespace

<img width="803" alt="Screen Shot 2021-02-11 at 4 00 07 PM" src="https://user-images.githubusercontent.com/72409237/107715004-332c7800-6c83-11eb-85a5-859969c5937a.png">

**Comment by bmdepesa** [comment]
We need to check a few more cases: 

* Different resource types:
  * Deployment
  * Service
  * Secrets
  * Configmap
  * Some resource types backed by CRDS (like VirtualService for Istio)
* Multiple resource types in a single file
* Verify that resources imported are applied to the namespace selected in the dropdwon

**Comment by aaronRancher** [comment]
Tested on `rancher\rancher:v2.5-head` `version b4be2b2`

Validated YAML import of the following resource types:
- Deployment
![Screen Shot 2021-02-22 at 3 15 53 PM](https://user-images.githubusercontent.com/57409052/108785436-a1e4bd80-752e-11eb-8325-b7c996dfa012.png)

- Service
![Screen Shot 2021-02-22 at 4 48 26 PM](https://user-images.githubusercontent.com/57409052/108785563-e83a1c80-752e-11eb-9125-14f1e97436f9.png)

- Secrets
![Screen Shot 2021-02-22 at 4 47 17 PM](https://user-images.githubusercontent.com/57409052/108785543-dce6f100-752e-11eb-9b5e-873f1b2a49da.png)
- Configmap
![Screen Shot 2021-02-22 at 4 46 08 PM](https://user-images.githubusercontent.com/57409052/108785581-f0925780-752e-11eb-8223-875c68fe805d.png)

- Some resource types backed by CRDS (Used PSP from OPA Gatekeeper)
![Screen Shot 2021-02-22 at 4 36 32 PM](https://user-images.githubusercontent.com/57409052/108785598-fa1bbf80-752e-11eb-9dba-997e757dcc69.png)


Validated import of multiple resource types in a single file:
![Screen Shot 2021-02-22 at 4 03 17 PM](https://user-images.githubusercontent.com/57409052/108785471-b4f78d80-752e-11eb-81a6-8f7460b49156.png)

Could not verify that resources imported are applied to the namespace selected in the dropdown. Could not create resource in another namespace besides `default`:
![Screen Shot 2021-02-22 at 4 27 15 PM](https://user-images.githubusercontent.com/57409052/108785533-d9536a00-752e-11eb-82ea-36b757c59a63.png)

**Comment by aaronRancher** [comment]
Creating resources from YAML in a non-default namespace errors with `json: cannot unmarshal object into Go struct field ApplyInput.defaultNamespace of type string`
Reopening for fix.

**Comment by aaronRancher** [comment]
Will track the backend issue separately: https://github.com/rancher/rancher/issues/31435

Was able to validate the following cases:
Different resource types:
- Deployment
- Service
- Secrets
- Configmap
Some resource types backed by CRDS (like VirtualService for Istio)
Multiple resource types in a single file

**Comment by brendarearden** [comment]
Tested on rancher\rancher:v2.5-head version 87006de

Validated import for the following in `default` and `testnamespace


**Deployment**: 
namespace: `default`
![Screen Shot 2021-02-24 at 3 03 12 PM](https://user-images.githubusercontent.com/19455540/109071799-6b837b80-76b1-11eb-9c17-bddc49eaf378.png)
namespace: `testnamespace`
![Screen Shot 2021-02-24 at 3 04 08 PM](https://user-images.githubusercontent.com/19455540/109071906-8ce46780-76b1-11eb-9dcc-2c22819c3179.png)
Both active after import:
![Screen Shot 2021-02-24 at 3 04 28 PM](https://user-images.githubusercontent.com/19455540/109071932-98379300-76b1-11eb-936a-c555f5af1e4d.png)

**Service**: 
namespace: `default`
![Screen Shot 2021-02-24 at 3 05 31 PM](https://user-images.githubusercontent.com/19455540/109072058-bf8e6000-76b1-11eb-9b89-772cb434a32c.png)
namespace: `testnamespace`
![Screen Shot 2021-02-24 at 3 06 16 PM](https://user-images.githubusercontent.com/19455540/109072152-d92fa780-76b1-11eb-83cc-d2d46daac884.png)
Both active after import:
![Screen Shot 2021-02-24 at 3 06 39 PM](https://user-images.githubusercontent.com/19455540/109072188-e6e52d00-76b1-11eb-921b-713766fa8b55.png)

**Secret**: 
namespace: `default`
![Screen Shot 2021-02-24 at 3 08 04 PM](https://user-images.githubusercontent.com/19455540/109072307-1a27bc00-76b2-11eb-9532-e4f31e60afd5.png)
namespace: `testnamespace`
![Screen Shot 2021-02-24 at 3 08 24 PM](https://user-images.githubusercontent.com/19455540/109072342-257ae780-76b2-11eb-82ce-9fa9d76c7203.png)
Both active after import:
![Screen Shot 2021-02-24 at 3 08 51 PM](https://user-images.githubusercontent.com/19455540/109072388-3592c700-76b2-11eb-8ce7-ea4fbc5241f3.png)

**Configmap**: 
namespace: `default`
![Screen Shot 2021-02-24 at 3 09 34 PM](https://user-images.githubusercontent.com/19455540/109072472-4f340e80-76b2-11eb-8556-07b7c668e608.png)
namespace: `testnamespace`
![Screen Shot 2021-02-24 at 3 09 54 PM](https://user-images.githubusercontent.com/19455540/109072508-5c50fd80-76b2-11eb-9499-57b6f99a6944.png)
Both active after import:
![Screen Shot 2021-02-24 at 3 10 14 PM](https://user-images.githubusercontent.com/19455540/109072545-670b9280-76b2-11eb-894d-74cb1dc65fec.png)

**Gateway (Istio CRD)**: 
namespace: `default`
![Screen Shot 2021-02-24 at 3 13 58 PM](https://user-images.githubusercontent.com/19455540/109072912-ed27d900-76b2-11eb-9148-751eca10f030.png)
namespace: `testnamespace`
![Screen Shot 2021-02-24 at 3 14 34 PM](https://user-images.githubusercontent.com/19455540/109072978-029d0300-76b3-11eb-8e0e-0def773edf8f.png)
Both active after import:
![Screen Shot 2021-02-24 at 3 14 58 PM](https://user-images.githubusercontent.com/19455540/109073020-0fb9f200-76b3-11eb-8078-3ca227dd8381.png)

**Book Info App (Multiple Resources in Single File)**
namespace: `default`
![Screen Shot 2021-02-24 at 3 16 26 PM](https://user-images.githubusercontent.com/19455540/109073172-455edb00-76b3-11eb-823c-eae4bbdff72c.png)
namespace: `testnamespace`
![Screen Shot 2021-02-24 at 3 16 51 PM](https://user-images.githubusercontent.com/19455540/109073221-54458d80-76b3-11eb-9c06-10dc7d569f08.png)
Snipper of some active after import (verified all were successfully created):
![Screen Shot 2021-02-24 at 3 17 51 PM](https://user-images.githubusercontent.com/19455540/109073340-7808d380-76b3-11eb-8e4d-504c21f4d310.png)

I did noticed that the namespace column is blank on all imports @vincent99 

Other than that, we are now able to import files and deploy them in default and non-default namespaces.
