### ISSUE TITLE
Details page updates

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1752]
Requirements:
General requirements:
1. Change top section (will have 2, Basic/Important Info & labels/Annotations)
2. Add State boxes to top for workloads
3. Body of details will contain tables of created resources & related resources (may also contain events & conditions)
4. Top tabs will be used
5. Buttons on top "Details/ Configuration / YAML
6.  Configuration will take you to the Edit as Form
7.  YAML will take you to Edit as YAML

Questions:
1.   Can we remove Type from the Info bar at top.  The type is actually in the Header already?  Should it be repeated?
2.  Do you want to move namespace & Age back into the bar?  Is Age important enough to show here.  It is in list?

**Comment by lvuch** [comment]
https://xd.adobe.com/view/b38835cd-fc89-4e0a-b89b-4ff9114e404c-e6db/

**Comment by tfiduccia** [comment]
Fixed - Each individual details will have to be looked out separately, but the main template across the board has been completed
