### ISSUE TITLE
Drop-downs/Multi-select polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1753]
1) 1st Make drop-downs consistent using the v-select
- [ ] Resolve all the drop-downs issues in dashboard repo (label area/drop-downs)
- [ ] Size of the option is bound by the trigger we should make sure you can see all dropdown options
- [ ] Add a tool tip prop to the component.
- [ ] Create Ingress => Rules=> Target service doesn't show typed in search ⇒ drop-downs
- [ ] Actions should use drop-downs so it will work with keyboard

2) Add the new v-select drop-down to the button dropdown after we are done making the v-select consistent
3) Additional changes:
- [ ] Vince/Tani to go through the drop-downs / multi-selects to put together a consolidated issue for all changes

**Comment by codyrancher** [comment]
There's a notable zindex issues in the Ingress page reported here https://github.com/rancher/dashboard/issues/1755#issuecomment-720764528

> Also while you are there can you fix: the drop-downs for Path as well, or work with Lauren to make sure component is correct? They are opaque and I can't select anything from the first drop-down if there is a second one.
> Path (Prefix)

![image](https://user-images.githubusercontent.com/55104481/98404534-020b2e80-2028-11eb-9a19-0b42b054f8d1.png)

**Comment by tfiduccia** [comment]
FIxed
