### ISSUE TITLE
Config Map Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1754]
Details:

- [ ] Data/Binary Data should be one key/value. Detect if it's binary and more it to the binary slot
   - We should only have one tab called "Data"
- [ ]  Key/Value: don't split 50/50

Create:

- [ ] The add button change to 2 buttons
- [ ] Spacing and styling issues for key/value (Lauren)

**Comment by tfiduccia** [comment]
@lvuch - this issue isn't done until the other three issues are resolved.  Also I think the detail pages fro ConfigMap needs to be redesigned?

**Comment by lvuch** [comment]
@vincent99 is working on this

**Comment by tfiduccia** [comment]
Fixed
