### ISSUE TITLE
Ingress Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1755]
List:
- [x] Add a column to flag "Default"
- [x] Add the text "Default" to point to the default backend that's used similar to 2.4 UI

Edit:
- [x] Move the default backend tab to be after rule
- [x] Validation of the "target service" should be a tool tip and color
- [x] Putting a "/" de-focuses

- Style (Lauren):
    - The drop down of the "Namespace" shows background form, z-index change

View:
- [x] Combine the rule and certs into one table instead of multiple boxes, need a name

**Comment by tfiduccia** [comment]
- [ ] Block component for Rules will need to make sure to follow the redesign that Lauren is doing. - #1737

- [ ] Also while you are there can you fix: the drop-downs for Path as well, or work with Lauren to make sure component is correct?  They are opaque and I can't select anything from the first drop-down if there is a second one.
Path (Prefix)
![image](https://user-images.githubusercontent.com/11514927/97926031-ab4bdf00-1d1f-11eb-8101-1e576c86c29d.png)

- [ ] Fix the spacing/Headers (work with Lauren/Tani to ensure all sections have headers & spacing is correct).  All pages.  But especially Labels & Annotations:
![image](https://user-images.githubusercontent.com/11514927/97926478-6eccb300-1d20-11eb-9c00-4ed5679b28f9.png)

Pro-tips needs fixing as well (maybe work with Lauren for this?) - 
- [ ] The text is not centered for key=value or the key: value.  
- [ ] The highlight for those two also look weird in Light view.
![image](https://user-images.githubusercontent.com/11514927/97926637-b2272180-1d20-11eb-81ba-97d1c2264206.png)
![image](https://user-images.githubusercontent.com/11514927/97926758-e995ce00-1d20-11eb-896b-2b61b3a9abd7.png)
- [ ] Remove the word ProTip: - Seems redundant and just takes up space

**Comment by codyrancher** [comment]
> Also while you are there can you fix: the drop-downs for Path as well, or work with Lauren to make sure component is correct? They are opaque and I can't select anything from the first drop-down if there is a second one.
Path (Prefix)

I believe this will be handled in https://github.com/rancher/dashboard/issues/1753. I'll make a note of it there.

**Comment by codyrancher** [comment]
@tfiduccia @lvuch 

I updated spacing on the Labels and Annotations component. Are there any changes you'd like to see from this?
![Screen Shot 2020-11-06 at 12 29 17 PM](https://user-images.githubusercontent.com/55104481/98406825-e3a73200-202b-11eb-9a28-d543cc609616.png)
![Screen Shot 2020-11-06 at 12 28 40 PM](https://user-images.githubusercontent.com/55104481/98406827-e3a73200-202b-11eb-9da3-acd3dad40d92.png)
![Screen Shot 2020-11-06 at 12 30 57 PM](https://user-images.githubusercontent.com/55104481/98406855-ef92f400-202b-11eb-8b05-76562e448ff9.png)

**Comment by codyrancher** [comment]
@tfiduccia do we actually want to support the code tags in the tooltip? Would em tags be acceptable?

![Screen Shot 2020-11-06 at 12 35 10 PM](https://user-images.githubusercontent.com/55104481/98407290-a4c5ac00-202c-11eb-95ea-45d2834a8e1a.png)

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `71da1569`**

List
- Default column is available
- Text "Default" to point to the default backend is available
<img width="1415" alt="Screen Shot 2020-11-17 at 11 41 56 PM" src="https://user-images.githubusercontent.com/26032343/99484602-c9742a80-292e-11eb-9f9d-715988e0cfce.png">



Edit:
Default backend tab moved to be after rule
<img width="705" alt="Screen Shot 2020-11-17 at 11 42 23 PM" src="https://user-images.githubusercontent.com/26032343/99484610-cbd68480-292e-11eb-9a10-60ea58279331.png">


View:
Rule and certs combined into one table instead of multiple boxes, need a name

<img width="1412" alt="Screen Shot 2020-11-17 at 11 43 01 PM" src="https://user-images.githubusercontent.com/26032343/99484621-d133cf00-292e-11eb-8be9-88e215af455c.png">

**Comment by tfiduccia** [comment]
Spacing & prefix not fixed.  Other issues as well.  I'm closing this one and entered new issue #1875 with list.
