### ISSUE TITLE
Only half the cores and memory visible

### ISSUE THREAD

**Issue by tuxpeople** [rancher/dashboard#1761]
I've a k3s Cluster, made from 2 Raspberry Pi 4 4GB. 1 Master, 1 Worker. Master is schedulable as it is default at K3S.

In "normal Rancher", I can see all 8 Cores and 8GB RAM:
![Bildschirmfoto 2020-11-01 um 20 51 38](https://user-images.githubusercontent.com/1506076/97812804-3f686880-1c84-11eb-965b-2b1c0810429e.png)

In "Dashboard", I can only see the half of it:
![Bildschirmfoto 2020-11-01 um 20 51 28](https://user-images.githubusercontent.com/1506076/97812810-4c855780-1c84-11eb-877d-86456e040926.png)

**Comment by codyrancher** [comment]
Closing this in favor of rancher/dashboard#1711
