### ISSUE TITLE
Rancher dashboard shows fleet-agent as an upgradeable chart to 0.3.100, but upgrading to this version throws an error

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1762]
Upgrade Rancher v2.5.1 to v2.5.2-rc5
Check List of Installed Apps.
Notice Fleet-agent is listed as upgradeable.

Upgrading it results in:

```

helm upgrade --history-max=5 --install=true --namespace=fleet-system --timeout=10m0s --values=/home/shell/helm/values-fleet-agent-0.3.100.yaml --version=0.3.100 --wait=true fleet-agent /home/shell/helm/fleet-agent-0.3.100.tgz
--
Sat, Oct 31 2020 1:53:06 pm | Error: UPGRADE FAILED: template: fleet-agent/templates/validate.yaml:10:3: executing "fleet-agent/templates/validate.yaml" at <fail "apiServerURL is required to be set, and most likely also apiServerCA">: error calling fail: apiServerURL is required to be set, and most likely also apiServerCA


```
Coming from 2.5.1 to 2.5.2-rc5 the fleet agent version is `fleet-agent:0.0.0+s-730feb1` and the upgrade version suggested is `0.3.100`
Rancher RKE HA with build your own valid certificates.
k8s in downstream cluster is `v1.19.3-rancher1-1`

**Comment by vincent99** [comment]
This is now disabled by 2 different ways that both happen to affect fleet-agent.  

1) the matching chart is marked `hidden`, so it will now offer no upgrade (#1601)
2) It has the `fleet.cattle.io/bundle-id` label, so it will show "Managed" instead

 ![image](https://user-images.githubusercontent.com/753917/97932250-c5d88500-1d2c-11eb-9be9-0db96df633cc.png)

(But you can still click the edit/upgrade action and try it if you really want).

**Comment by izaac** [comment]
Rancher version `v2.5.1` upgraded to `master-head (11/03/2020)` 
There isn't an option to upgrade the `fleet-agent` chart anymore. It is now marked as Managed. There's an upgrade option in the three dots menu but is intended for configuration upgrades.

Checked both Local HA and Downstream clusters.

![Screen Shot 2020-11-03 at 1 38 09 PM](https://user-images.githubusercontent.com/27659/98038132-d72b9b00-1dd9-11eb-8b6d-d5faf889fb33.png)


![Screen Shot 2020-11-03 at 1 37 42 PM](https://user-images.githubusercontent.com/27659/98038138-da268b80-1dd9-11eb-9441-70a3dbc3f56c.png)
