### ISSUE TITLE
Logging V2 UI Syslog

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1763]
Logging V2 UI Syslog fields

**Outputs::syslog**
| Field | Type | Default |
| -----|------|---------|
| syslog.enabled | hidden field set to true | true |
| syslog.address | string | blank |
| syslog.cluster | bool | true |
| splunk.root_ca | string | blank |

**Comment by maggieliu** [comment]
closing in favor of : https://github.com/rancher/dashboard/issues/1191
