### ISSUE TITLE
Don't show Longhorn CRD objects from dashboard UI

### ISSUE THREAD

**Issue by yasker** [rancher/dashboard#1766]
Currently, Longhorn doesn't support editing CRDs directly. It's planned for the v1.2.0 release.

Having the Longhorn CRD objects listed there may result in a wrong impression that operating through CRD is supported.

<img width="683" alt="Screen Shot 2020-11-02 at 9 36 35 AM" src="https://user-images.githubusercontent.com/3344618/97900047-fdc0d780-1cee-11eb-8878-2f52d93b8b09.png">

**Comment by vincent99** [comment]
The dashboard shows the types and operations you have RBAC for.  Whether you support it or not, they _are_ editable types and I don't really want the UI getting into opinions & special cases about what it "should" be allowing vs what the user has permission to do.

Even if we wanted to hide it, how would I know if it's <1.2 and should be disabled or >=1.2 and should be allowed?  The user viewing the CRDs doesn't necessarily have access to see the helm app/release that installed it, or the settings CRD, etc.

**Comment by yasker** [comment]
Good point. Are those just CRDs in the `longhorn.io` API group? Since if that's the case, it's a bit weird that `instance manager` is not there if the code is automatically generated. So I thought those are added manually.

Also, v1.2 is scheduled around April next year, we probably don't need to worry about it now.

**Comment by vincent99** [comment]
Types only show up under "more resources" if there are any to show matching the current namespace filter.  Which defaults to "user namespaces", which excludes anything ending in `-system`, which is where your instance managers are..

To see a type where there are no current ones visible, you can get to it in the "Jump" dropdown:

![image](https://user-images.githubusercontent.com/753917/97931267-78f3af00-1d2a-11eb-90f8-77d52c07f8a1.png)

**Comment by yasker** [comment]
I saw the `Jump` dropdown indeed contains all the Longhorn related CRDs. I am fine with keeping those since it's a generic interface.

But the Longhorn app page is created for Longhorn, and it doesn't contain e.g. `Instance Manager`, so it seems the entries there are hardcoded. Can we remove the CRD part for now?

**Comment by vincent99** [comment]
I didn't realize we had an actual product entry for Longhorn earlier.. removed the CRDs from that so that only the overview tab remains for now until editing CRDs directly is supported later.

**Comment by khushboo-rancher** [comment]
Verified with master-head - ```0852920```

Validation - **Pass**

The CRDs are not appearing and only the overview tab is available.
<img width="607" alt="Screen Shot 2020-11-03 at 2 08 02 PM" src="https://user-images.githubusercontent.com/60111667/98045880-03e1b180-1dde-11eb-8c97-1ccdea7f1524.png">
