### ISSUE TITLE
Dashboard incorrectly categorizes service type when editing

### ISSUE THREAD

**Issue by ebauman** [rancher/dashboard#1772]
Steps to reproduce:
1. Create a service that isn't a ClusterIP (I used NodePort)
2. View this service by clicking on the object name in the explorer
3. Observe that the Type is listed as Cluster IP:

![Screen Shot 2020-11-03 at 11 37 40 AM](https://user-images.githubusercontent.com/5565738/98020838-274e3180-1dc9-11eb-9137-b822aed00aec.png)

Version: v2.5.2-rc6

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 4f72515` and `rancher\rancher:v2.5-head` `version 2b061d7`

Type is properly reflected on each service.
![Screen Shot 2021-01-08 at 5 01 35 PM](https://user-images.githubusercontent.com/57409052/104076430-4c00c400-51d3-11eb-8f7f-9449a85a1e2a.png)
