### ISSUE TITLE
OPA Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1773]
Constraint (Create)

- [x]  Pick the template first before seeing the tabs

- Kinds:
- [x]  Styling The header for the inputs don't look like header
- [x]  Style of the boxes should be consistent ⇒ Make a component "Group list" (cody)
    - Add Kind Buttons:
      - [x] Outer "Kind" ⇒ called "Rule"
      - [x]  Change the tab to be called "Rule"

- Parameters:
   - [x]  Show yaml all the time and remove the add parameter option

- Enforcement:
   - [x]  Move the radio buttons out of the tabs to the section above and add a description

- Namespace list:
   - [x]     Multi-select on two separate rows for Namespaces and Excluded Namespaces
   - [x]     Any rules needed on filtering the namespaces (confirm with Prachi)
   - [x]     Add description on what this does if needed

- Selectors: to be removed (confirm with Prachi)
   - [x]  Label Selector should be moved to "Rules" tab
   - [x]  Namespace selector should be moved to "Namespace" tab

Constraints (Details):
   - [x] Only shows violations and drop the bottom tabs
   - [x] Show the "Enforcement action" since it will be moved out
   - [x] Name in the violations should be linked to the resource to see it
   - [ ] (nice to have) Show what is list of matched kinds & namespaces

Overview (list of all violations):
   - [x]  Name should be linked to resources
   - [x]  constraints, templates, violations (color numbers)

Templates:

  - [ ] Do we need to change the yaml to forms? (Confirmed with Bill that we just need yaml, but can we get the Rego syntax validator?)

Installing:
  - [x] Need a simple form for fields that are useful and don't show the yaml (Confirm with Prachi)

**Comment by tfiduccia** [comment]
Create Kind: 
- [ ] Redesign inside of Kind block so it has headers & the Label/fields are displayed properly (spacing as well adding headers) - (Cody & Lauren)
![image](https://user-images.githubusercontent.com/11514927/98034844-db08ee80-1dd4-11eb-8a1b-663ef40e3fcf.png)

- [ ] If adding a description to the top of Parameters/Namespace, can we put them into an info boxes?

- [ ] If moving Label & Namespace selector to the two other tabs, can we have Lauren help to give a quick design for that?
![image](https://user-images.githubusercontent.com/11514927/98034172-cb3cda80-1dd3-11eb-9f9d-df0eb8151d4d.png)

- [ ] Operator field - It's too small & The text does not line up with the V.
![image](https://user-images.githubusercontent.com/11514927/98034274-f9bab580-1dd3-11eb-9d67-ba0024456024.png)

**Comment by codyrancher** [comment]
>  If adding a description to the top of Parameters/Namespace, can we put them into an info boxes?
I added descriptions as tooltips. We can move the tooltips to info boxes but I'll let lauren comment in the PR one way or another.

**Comment by codyrancher** [comment]
> Do we need to change the yaml to forms? (Confirmed with Bill that we just need yaml, but can we get the Rego syntax validator?)

I opened a separate issue for this https://github.com/rancher/dashboard/issues/1860. I think this is going to be a sizable amount of work as I haven't found a rego or datalog validator.

> (nice to have) Show what is list of matched kinds & namespaces

We don't appear to have the info readily available to make use of an existing solution. So I didn't implement this.

**Comment by tfiduccia** [comment]
Verified fixed
