### ISSUE TITLE
When I click on Cancel for OPA Template, i get a 404 and then redirected back to Cluster Explorer

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1778]
Steps:
1.  Go to OPA
2.  Go to Create Template (only has YAML)
3.  Click on Cancel

Results:  Get redirected to 404 and then back to Cluster Explorer

**Comment by aaronRancher** [comment]
This behavior is seen in Rancher `v2.5.2-rc6`

Case 1:
Go to OPA
Go to Create Template (only has YAML)
Click on Cancel

Case 2:
Go to OPA
Go to Create Template (only has YAML)
Click on Create

Result:
User is redirected to Ember UI
When "create" is selected, the user will be redirected, but the template is created.

**Comment by tfiduccia** [comment]
@sowmyav27 This works in master.  Not sure if you want someone to test this in next RC.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 0852920` and `rancher\rancher:v2.5-head` `version 100198a`

OPA templates can be created and cancelled. 

Will test this again on the next RC.
