### ISSUE TITLE
[Namespace] Bug with yaml editor

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1785]
On create:
Yaml editor bug ⇒ changing the values in the form doesn't update the yaml

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version ff16903` and `rancher\rancher:v2.5-head` `version 8d759be`

Steps:
Create a namespace. Add labels:
![Screen Shot 2020-12-09 at 4 25 11 PM](https://user-images.githubusercontent.com/57409052/101701468-382f3a00-3a3c-11eb-9436-b7e4c6abdc32.png)
Edit as YAML. Change labels:
![Screen Shot 2020-12-09 at 4 25 46 PM](https://user-images.githubusercontent.com/57409052/101701489-3feede80-3a3c-11eb-86a4-6253ba1773c5.png)
Edit is seen in form view:
![Screen Shot 2020-12-09 at 4 26 04 PM](https://user-images.githubusercontent.com/57409052/101701594-70cf1380-3a3c-11eb-84f5-08788a061fe3.png)
Edit from form view:
![Screen Shot 2020-12-09 at 4 38 03 PM](https://user-images.githubusercontent.com/57409052/101701816-ef2bb580-3a3c-11eb-98a7-d939ff056039.png)
Edit is seen in YAML view:
![Screen Shot 2020-12-09 at 4 38 40 PM](https://user-images.githubusercontent.com/57409052/101701882-036fb280-3a3d-11eb-9497-14b6ee91ea47.png)
