### ISSUE TITLE
[Monitoring V2 UI] Add field to specify certificate directory for RKE1 clusters

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1787]
#### Context

Original Ticket With Workaround: https://github.com/rancher/rancher/issues/29815#issuecomment-718283775

Ticket that discusses the required help text: https://github.com/rancher/rancher/issues/29840

### Changes Requested

When the `Cluster Type` is detected to be RKE1, the following option should show up:

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Certificate Directory on Etcd Nodes | `rkeEtcd.clients.https.certDir` | Host path on your nodes where the Kubernetes certificates for etcd can be found | `string` | `/etc/kubernetes/ssl`

A tooltip should have the following help text:
```
For clusters that use RancherOS for the etcd nodes, this option should be set to `/opt/rke/etc/kubernetes/ssl`. Hybrid environments that require specifying multiple certificate directories (e.g. an etcd plane composed of both RancherOS and Ubuntu hosts) is not supported.
```

**Comment by jiaqiluo** [comment]
The enhancement is validated on rancher:`v2.5-e2e530c19ac1fda3065cdf356cdc9a4e610bc51e-head` 

- When the cluster type is RKE, the following section `ETCD Node Certificat Directory` will show up with the default value `/etc/kubernetes/ssl`. Also checked that if I change the value when installing monitoring, the value is applied to the monitoring app. 


![image](https://user-images.githubusercontent.com/6218999/101101354-97490680-3585-11eb-8611-fabc3fb6204c.png)


- For other cluster types, the section is omitted: 

![image](https://user-images.githubusercontent.com/6218999/101102699-3cfc7580-3586-11eb-8419-e46fc2194602.png)
