### ISSUE TITLE
Unable to create deployment/statefulSet without pod scheduling using form

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#1789]
**Describe Bug**
User is unable to create deployment/stateful set without ```pod scheduling``` using form in the dashboard.

**Steps to Reproduce**
1. Go to the dashboard.
2. Create a deployment using the form without setting ```pod scheduling```.
3. Click create.
4. Deployment creation fails.
<img width="1524" alt="Screen Shot 2020-11-04 at 4 57 18 PM" src="https://user-images.githubusercontent.com/60111667/98184436-4333ff00-1ebf-11eb-85a6-10459242f517.png">

**Comment by sadiapoddar** [comment]
Verified the fix with 2.5-head, v2.5-d20c9c6685ad6a17599d8c42ce6b7344ece8fb67-head
Steps used to verify

1. Go to the dashboard.
2. Create a deployment using the form without setting pod scheduling.
3. Click create.
4. Deployment succeeded. 
<img width="1532" alt="Screen Shot 2020-11-06 at 9 52 04 AM" src="https://user-images.githubusercontent.com/72409237/98398630-2100c500-2016-11eb-9f1e-56ce6cc580ce.png">

Note that wl1 created without pod scheduling is active now. 
<img width="1507" alt="Screen Shot 2020-11-06 at 9 52 26 AM" src="https://user-images.githubusercontent.com/72409237/98398716-41308400-2016-11eb-9ce7-1833eccc6743.png">

**Comment by sadiapoddar** [comment]
The fix is working, closing the issue.
