### ISSUE TITLE
[Logging v2] Unsupported output provider resource should not be editable "as form"

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#1791]
1. Create a Logging Output resource with an unsupported provider using "Create from YAML"
2. Click on the hamburger menu next to the created output resource

Result:
"Clone / Edit as form" options are available from the menu

Expected:
These options should not be shown since there is no support for editing this output via form.

<img width="739" alt="Screenshot 2020-11-05 at 14 31 04" src="https://user-images.githubusercontent.com/3813921/98247557-0e35b400-1f74-11eb-93c8-d7ee27170660.png">

**Comment by maggieliu** [comment]
Hide "Edit as Form" if it's not supported.

**Comment by izaac** [comment]
Rancher version: `master-head (12/09/2020)` _ff16903_
Rancher version: `v2.5-head (12/09/2020)` _8d759be_

Add an unsupported output in this case I used syslog as it was not yet added as an additional supported output in these Rancher builds as of 12/09/2020
https://github.com/rancher/dashboard/issues/1192
https://github.com/rancher/dashboard/issues/1191

There's no option to edit as Form as expected.

![Screen Shot 2020-12-09 at 11 46 53 AM](https://user-images.githubusercontent.com/27659/101673380-55501280-3a14-11eb-9a61-091cd20f60bd.png)
![Screen Shot 2020-12-09 at 11 46 45 AM](https://user-images.githubusercontent.com/27659/101673384-55e8a900-3a14-11eb-8d14-1eea993d3cc8.png)
