### ISSUE TITLE
[Logging v2] Detail page "Overview" view should not be shown for unsupported outputs

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#1792]
1. Create a Logging Output resource with an unsupported provider using "Create from YAML"
2. Click on the resource name

Result:
An empty Overview view is rendered

Expected Result:

The Overview view is not shown for unsupported output resources whose details can't be rendered. Instead, the YAML view is displayed.

<img width="1204" alt="Screenshot 2020-11-05 at 14 40 42" src="https://user-images.githubusercontent.com/3813921/98248543-60c3a000-1f75-11eb-8cf7-acf36e56b00b.png">

**Comment by maggieliu** [comment]
Detail component should say this is not support.

**Comment by izaac** [comment]
Rancher version: `master-head (12/09/2020)` _ff16903_
Rancher version: `v2.5-head (12/09/2020)` _8d759be_

Add an unsupported output in this case I used syslog as it was not yet added as an additional supported output in these Rancher builds as of 12/09/2020
https://github.com/rancher/dashboard/issues/1192
https://github.com/rancher/dashboard/issues/1191


![Screen Shot 2020-12-09 at 11 38 03 AM](https://user-images.githubusercontent.com/27659/101673057-e1ae0580-3a13-11eb-89ea-086429c34a7e.png)
![Screen Shot 2020-12-09 at 11 41 01 AM](https://user-images.githubusercontent.com/27659/101673067-e4105f80-3a13-11eb-91cb-048c2c97c67c.png)
