### ISSUE TITLE
Delete modal needs cleanup/design

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1795]
Issues:
1.  In dark mode: I can barely see that it's a modal on top cause the black on black (maybe a border or something?)
2.  The blue bar on the left isn't on the border of the modal and looks like it's floating.
3.  Cancel & Delete buttons too close together?
4.  Remove Protip: text?  Say "Holding the Command key while clicking delete will bypass this confirmation."

![image](https://user-images.githubusercontent.com/11514927/98290364-ceb49b00-1f66-11eb-9acd-840442e06336.png)
![image](https://user-images.githubusercontent.com/11514927/98290396-dd9b4d80-1f66-11eb-9efe-533e6ccd4c3a.png)

**Comment by tfiduccia** [comment]
Looks better but now the Cancel and Delete buttons are not centered
![image](https://user-images.githubusercontent.com/11514927/102720429-8b618200-42b1-11eb-9664-0c996b4c8174.png)

**Comment by sadiapoddar** [comment]
Verified the fix on 2.5-head bb69b03, and master-head 4297ee1.
Steps to verify
1. created a few cron jobs, namespaces, ingress, jobs, deployments, pods, and services
2. select each of the objects created in #1  and delete
3. Noticed the following changes in modal
    -- the background color has changed from dark to a little lighter, 
    -- The extra blue line has been eliminated
    -- cancel and delete buttons are separated
    -- The protip message "Holding" has changed to "Hold"
4. Verified that holding command key and issuing delete works as expected. 

<img width="413" alt="Screen Shot 2020-12-21 at 12 10 51 PM" src="https://user-images.githubusercontent.com/72409237/102826778-3186b800-4396-11eb-9d59-3a95b6656359.png">
