### ISSUE TITLE
Create generic pages to track components for list, details, edit

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1798]

**Comment by lvuch** [comment]
page examples:
/design-system/page-examples/create
/design-system/page-examples/detail
/design-system/page-examples/list

**Comment by lvuch** [comment]
keeping this in icebox for now, but should be included in storybook implementation effort

**Comment by nwmac** [comment]
We will use Storybook for this

**Comment by gaktive** [comment]
This ticket has been made irrelevant based on Storybook and other work.
