### ISSUE TITLE
[Monitoring V2 UI] UI for Probes

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1799]
Backend Issue: https://github.com/rancher/rancher/issues/29871

The Dashboard UI needs to expose a UI for being able to modify the Probe CRs that are deployed into the cluster if the CRD is installed on the cluster.

### Probe

Generates the scrape configuration of a Prometheus instance based on a provided Probe URL; you should use this to set up scrapes from groups of ingresses or static targets.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Job Name | `spec.jobName` | `N/A` | `string` | nil
Scheme | `spec.prober.scheme` | `N/A` | `http` or `https` | `http`
URL | `spec.prober.url` | `N/A` | `string` | ``
Path | `spec.prober.path` | `Path to collect metrics from` | `string` | `/probe`
Interval | `spec.interval` | `Interval at which targets are probed` | `string` | `1m`
Scrape Timeout | `spec.scrapeTimeout` | `N/A` | `string` | `10s`
Module | `spec.module` | `Used to configure the probe` | `YAML` string | `""`

If it would be possible to mock a UI where `Scheme`, `URL`, and `Path` are provided as one field (`Probe URL`), that would be better.

For the Module section, it would be nice it we could have that in a separate (but not required) tab under `Advanced Configuration` with the following Help text:

```
See Prometheus docs at [Configuring Modules](https://prometheus.io/docs/guides/multi-target-exporter/#configuring-modules) and [Blackbox Exporter Configuration](https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md#module) to provide a valid configuration for a Probe Module.
```

The following options should be exposed
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Timeout | `timeout` | How long the probe will wait before giving up | `string` | `10s`
Type of Probe | `prober` | The protocol over which the probe will take place | `http, `tcp`, `dns`, `icmp` | `http`

Depending on the type of `prober`, the following options should be exposed.

If `prober` is `http`:
Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Method | `http.method` | `GET`, `POST`, `HEAD`, `PUT`, `DELETE`, `CONNECT`, `OPTIONS`, `TRACE`, `PATCH` | `GET`
Headers | `http.headers` | Key-value pairs of strings | `{}`
Body | `http.body` | `string` | `{}`
Proxy URL | `http.proxy_url` | `string` | `""`
Additional YAML | `.` | `YAML` string | `""`

If `prober` is `tcp`, `dns`, or `icmp`, just expose a `YAML` field for input.

**Comment by lvuch** [comment]
https://xd.adobe.com/view/866862d9-4ac5-4962-a026-0c716a335cb7-d33b/

**Comment by lvuch** [comment]
page 3: https://xd.adobe.com/view/06a7ba45-e0eb-4550-89ea-ef43322622cf-53f4/

**Comment by aiyengar2** [comment]
Moving this to 2.5.8 since it needs to be prioritized with https://github.com/rancher/rancher/issues/29871

**Comment by nwmac** [comment]
See: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-probes.yaml

**Comment by catherineluse** [comment]
@kwwii This issue seems to be fleshed out with a great deal of detail already. Is there any remaining design work to be done, or can it be moved to the backlog?
