### ISSUE TITLE
[Monitoring V2 UI] Slack Receiver should default to using Rancher text

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1805]
As shown in the default [here](https://github.com/rancher/charts/blob/1d17a5bb6767f6468815b005b688fb73f7baa228/charts/rancher-monitoring/values.yaml#L416), user-configured Receivers for Slack should set `slack_configs.text='{{ template "slack.rancher.text" . }}'` by default.

Without this, an alert to Slack would have something similar to the following outputted on Slack instead of the one dictated by the Rancher template:
```
AlertManagerAPP  1:37 PM
[FIRING:2] rancher-cis-scan (CISScanHasFailures cis-operator web 10.42.0.118:8080 cis-operator-system 20 0 92 cis-operator-c7944dfb7-k5vtf cattle-monitoring-system/rancher-monitoring-prometheus rke-profile-hardened warning)
```

**Comment by jiaqiluo** [comment]
Failed to validate on rancher:`v2.5-e2e530c19ac1fda3065cdf356cdc9a4e610bc51e-head`

Basically, we cannot create any receiver.

As the screenshot shows, when we create a new receiver, a GET request is sent to `https://server-url/k8s/clusters/c-sz97l/v1/secrets/alertmanager-rancher-monitoring-alertmanager`, but the response does not contain anything in the `data` section. 

<img width="1450" alt="Screen Shot 2020-12-03 at 5 50 41 PM" src="https://user-images.githubusercontent.com/6218999/101107797-54d8f700-3590-11eb-9b01-a600ec71eb09.png">


And this secret does exist under the namespace `cattle-monitoring-system`
![image](https://user-images.githubusercontent.com/6218999/101107984-c5801380-3590-11eb-8f63-c84a0bb0948e.png)

**Comment by jiaqiluo** [comment]
The UI enhancement is validated on rancher:v2.5-head 395b4f

By default, the following config is applied when the receiver is Slack
```
      text: '{{ template "slack.rancher.text" . }}'
```

and here is a sample of the message received in Slack 

![image](https://user-images.githubusercontent.com/6218999/101425999-60426000-38b9-11eb-813f-b1c2e4064857.png)

**Comment by frouzbeh** [comment]
@jiaqiluo Hi, I'm having a problem fixing a slack config issue. The thing is that before upgrading the rancher-monitoring from 9.4 to 14.5 everything was normal, but after that the slack messages got ugly. Like this:
<img width="605" alt="Screen Shot 2021-10-15 at 9 25 50 AM" src="https://user-images.githubusercontent.com/20402896/137521524-6f6f1938-6e16-4845-9cf6-3273be03c337.png">

The title wasn't there before, and now it's this long title which is linked to the cluster internal URL. I wanted to know how I can make the title shorter and also if I can link it to the rancher monitoring magic link? If I can do this I'd prefer to remove it. 
Thank you.

**Comment by jiaqiluo** [comment]
Hi @frouzbeh  
I did not have a solution right now in my mind, but alertManager allows users to configure the title by setting a template. see https://prometheus.io/docs/alerting/latest/notification_examples/#ranging-over-all-received-alerts and https://prometheus.io/blog/2016/03/03/custom-alertmanager-templates/

In Rancher UI, you can edit the receiver as YAML and add the template/format for the title.

**Comment by frouzbeh** [comment]
@jiaqiluo Thanks, I have resolved the title. thanks again.
