### ISSUE TITLE
Monitoring Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1806]
- **Deployment page:**

- [x] Separate chart options into the following Tabs:
- General Config Tab
- Prometheus Tab
- Alerting Tab
- Grafana Tab:  Add Grafana storage as a H3

~- [ ] Add in the new advanced fields, then have Lauren do a overhaul on the styling and see if certain checkbox can be grouped together better~ Advanced has own tickets

- **Overview:**
- [x] A table of active alerts below the links
- [x] Need to have a consistent page title with the navigation

- **Prometheus Rules:**

- [x]  Switch the box around the rules to use the standard component ("array list groups")
~- [ ]  PromQL Expression:~
            ~-  H4 label with codeMirror~

**Comment by slickwarren** [comment]
on 2.5-head (3d62d5d) I was able to verify the following after creating monitoring v2 (v9.4.202) on a cluster: 
* separated chart options <img width="505" alt="Screen Shot 2021-01-19 at 2 03 36 PM" src="https://user-images.githubusercontent.com/16691014/105100122-ac102980-5a61-11eb-954e-6349cc679ddd.png">
  * **Note:** did not see `Add Grafana storage as a H3` but possibly this meant `configure grafana`?
<img width="328" alt="Screen Shot 2021-01-19 at 2 28 14 PM" src="https://user-images.githubusercontent.com/16691014/105100932-eb8b4580-5a62-11eb-96b8-7d4d62ca9385.png">

* table of active alerts on overview page (in Monitoring tab)
* page title matched dashboard home page  
<img width="1452" alt="Screen Shot 2021-01-19 at 2 02 18 PM" src="https://user-images.githubusercontent.com/16691014/105100167-b9c5af00-5a61-11eb-963b-3e6252c87e72.png">

* array-list-group used when creating new prometheus rules through rancher UI
<img width="709" alt="Screen Shot 2021-01-19 at 2 01 33 PM" src="https://user-images.githubusercontent.com/16691014/105100098-a1559480-5a61-11eb-9f83-0926b0e7aa96.png">

**Comment by slickwarren** [comment]
from the above, it sounds like `configure grafana` should be a level above `Persistent Storage for Grafana`, but here they appear on the same level.

**Comment by westlywright** [comment]
@slickwarren I believe that item was for two things, sorry its not more clear. We added the Grafana section to its own tab AND I believe the label was supposed to change from `Persistent Storage for Grafana` to `Grafana Storage`. I moved the section to its own tab but I missed changing the label. I will open a new pr for that.

**Comment by slickwarren** [comment]
<img width="311" alt="Screen Shot 2021-01-26 at 1 11 16 PM" src="https://user-images.githubusercontent.com/16691014/105906488-9e662100-5fd8-11eb-83d2-997e8d938972.png">
@westlywright this now has the label changed, thanks! Just curious, is the `Configure Grafana` section a sort of place holder that will have vars to fill later on? Looks a little odd as-is, since there are 3 titles stacked together.

**Comment by westlywright** [comment]
@slickwarren Yes, the label more matches consistency with other tabs right now but in the future there should be additional configuration options in here.
