### ISSUE TITLE
Alerts Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1807]
- **Receivers**:
- [x]   List: Configured Receivers ⇒ Configured Providers

    - Edit:
        - email:
            - [x]  Switch to use the "array list groups" component
            - [x]  Sender: add an example text
        - custom:
           - [x]   Yaml: validate the input and has a warning popup if it's not valid on save
    - View: Might just go away if there is nothing different from edit

- **Routes**:
    - Edit
        - Matching:
           - [x] Add button ⇒ drop the read from file
    - View: Might just go away if there is nothing different from edit
    - list:
       - [x] link to the receiver

**Comment by tfiduccia** [comment]
Verified fixed - Ok the things listed in this issue has been resolved.  But the create pages for all of Monitoring application including Alert pages are in need fixing.  The spacing, field usage, tooltip, suggestion text... and at lease 1 of control is not the correct size.  Polish review needs to be redone and all pages & blocks need to be looked at.
