### ISSUE TITLE
Wrong default value for Deployment, Network Settings, Network Mode

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1809]
When creating a new Deployment, the default value in the Network Settings -> Network Mode dropdown is "Host Network"

![Bildschirmfoto 2020-11-10 um 15 04 00](https://user-images.githubusercontent.com/243056/98684062-099f4000-2366-11eb-8143-7f52c75dfb15.png)

The default value should be "Normal".

And even though "Host Network" is set, this setting does not have any effect, the resulting value for `hostNetwork` in the PodSpec is still either empty or `false`.

This is also the case when editing a deployment.

**Comment by sadiapoddar** [comment]
verified the fix on master-head, commit master-5da52c0

1. created a deployment and verified that the default value is 'Normal' not 'Host Network'
2. Verified the pod config after the deployment creation and found that network value remain intact as "Normal
<img width="696" alt="Screen Shot 2020-12-28 at 4 56 30 PM" src="https://user-images.githubusercontent.com/72409237/103252170-7b404700-4930-11eb-8466-026dbb64c13d.png">

1. Created a deployment by select not default but "Host Network" as network value
2. Verified the pod config has the "Host Network" as the network value

<img width="1032" alt="Screen Shot 2020-12-28 at 4 52 18 PM" src="https://user-images.githubusercontent.com/72409237/103252225-b80c3e00-4930-11eb-818b-c6eee5206c23.png">
