### ISSUE TITLE
Redeploying a deployment has no effect

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1810]
When I click on "Redeploy" on a deployment

![Bildschirmfoto 2020-11-10 um 15 09 07](https://user-images.githubusercontent.com/243056/98684644-b5e12680-2366-11eb-89cb-c0ea507c0289.png)

it looks like everything is working, but the operation has no effect. I would expect a rolling update to be triggered (like in the ember ui), but instead nothing happens and the Pods remain running (see age):

![Bildschirmfoto 2020-11-10 um 15 09 45](https://user-images.githubusercontent.com/243056/98684808-e923b580-2366-11eb-8a2c-07a3dc56b09b.png)

**Comment by mogoman** [comment]
Seeing the same problem.

**Comment by vincent99** [comment]
The label is getting set on the workload (metadata.labels) instead of the pod spec (spec.template.metadata.labels)

**Comment by anupama2501** [comment]
Verified on 

Rancher | v2.5-b83b45c96e199dd0dc503131471ae94c8019a827-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher50

Steps:
Create a cluster and deploy a workload from dashboard
Edit config and increase the replicas or just redeploy the workload.
The event history shows the pods are redeployed 

<img width="1400" alt="Screen Shot 2021-01-28 at 4 40 22 PM" src="https://user-images.githubusercontent.com/38144301/106216228-884a9300-6187-11eb-8541-37fcb1e71670.png">
<img width="1645" alt="Screen Shot 2021-01-28 at 4 40 12 PM" src="https://user-images.githubusercontent.com/38144301/106216223-8680cf80-6187-11eb-94ae-0c7c43018829.png">
<img width="1059" alt="Screen Shot 2021-01-28 at 4 41 14 PM" src="https://user-images.githubusercontent.com/38144301/106216286-a6b08e80-6187-11eb-9813-e140df0a8502.png">
