### ISSUE TITLE
Ingress form: Unable to provide certificate secret that does not exist yet

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1812]
When creating an ingress through the ingress form, it is not possible to enter the name of a secret that does not exist yet. It is only possible to reference an existing secret or "default ingress controller certificate", which will not set any secret name.

![Bildschirmfoto 2020-11-10 um 15 19 56](https://user-images.githubusercontent.com/243056/98686073-6c91d680-2368-11eb-91ad-4ec5f6c6aa76.png)

Referencing a secret name that does not exist yet is common practice when using cert-manager through an ingress annotation (https://cert-manager.io/docs/usage/ingress/#how-it-works).
Because of this annotation, cert-manager will create the necessary certificate, which will create the secret.

**Comment by jiaqiluo** [comment]
The bug is reproduced on rancher:2.5.3 single-install 

Just like the issue mentions, we can enter the name of a secret that does not exist
![image](https://user-images.githubusercontent.com/6218999/100803416-5962ab80-33e8-11eb-873c-1374ac586a41.png)

**Comment by jiaqiluo** [comment]
the bugfix is validated on rancher:master-head 6f9668 and rancher:v2.5-head db350a

now we can enter the name of the secret that does not exist. the field is still in the form of a dropdown list, but we can select what we just entered. 

<img width="917" alt="Screen Shot 2020-12-01 at 3 42 55 PM" src="https://user-images.githubusercontent.com/6218999/100805467-ee1ad880-33eb-11eb-8020-855122c0db3d.png">


And the Ingress is created successfully.
 
<img width="699" alt="Screen Shot 2020-12-01 at 3 38 09 PM" src="https://user-images.githubusercontent.com/6218999/100805512-02f76c00-33ec-11eb-91ce-5bf2f07953c1.png">
