### ISSUE TITLE
Missing field terminationGracePeriodSeconds in Pod form

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1816]
When creating/editing a pod, the `terminationGracePeriodSeconds` field is missing.

It is common to change this value for workloads that require a longer time to gracefully shut down.

> Optional duration in seconds the pod needs to terminate gracefully. May be decreased in delete request. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period will be used instead. The grace period is the duration in seconds after the processes running in the pod are sent a termination signal and the time when the processes are forcibly halted with a kill signal. Set this value longer than the expected cleanup time for your process. Defaults to 30 seconds.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `9ee39b9f8`**

Cron Job and Job workload types have terminationGracePeriodSeconds and the value is set on the workload
