### ISSUE TITLE
[Monitoring V2] Missing tls_config and authentication fields in receivers forms

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1818]
The monitoring v2 receivers UI is missing the following fields:

# Email

![Bildschirmfoto 2020-11-10 um 15 52 14](https://user-images.githubusercontent.com/243056/98690111-e330d300-236c-11eb-873a-532ba9fbaed3.png)

* tls_config

# Webhook

![Bildschirmfoto 2020-11-10 um 15 52 22](https://user-images.githubusercontent.com/243056/98690148-ecba3b00-236c-11eb-9053-a5c4ea06cde2.png)

* http_config.tls_config
* http_config.basic_auth
* http_config.bearer_token

These are important for enterprise customers, since they usually use their own CAs and authentication.

**Comment by codyrancher** [comment]
@bashofmann 
does this cover all of the fields you were looking for? Will the cert file paths be a problem?

![image](https://user-images.githubusercontent.com/55104481/100801266-fd4a5800-33e4-11eb-9429-891cab868239.png)
![image](https://user-images.githubusercontent.com/55104481/100801281-03d8cf80-33e5-11eb-9944-0c369dc1add9.png)

**Comment by bashofmann** [comment]
Having this as a file path is not, ideal since the certificates would need to be mounted in the alertmanager pods manually. You could add additional volumes and volume mounts to alertmanager  when installing the monitoring (https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L542-L546), but it would be nicer if you could directly reference a secret with the certificates in the receiver configuration. 

Though we would likely need to update the prometheus-operator and then use AlertmanagerConfigs for this:
https://github.com/prometheus-operator/prometheus-operator/blob/8497a67b735e65ad779ed19c95a17ffd1c8fbb64/pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go#L472
https://github.com/prometheus-operator/prometheus-operator/blob/8497a67b735e65ad779ed19c95a17ffd1c8fbb64/pkg/apis/monitoring/v1/types.go#L963-L974

@ aiyengar2 what do you think?

**Comment by codyrancher** [comment]
@bashofmann the paths were my biggest concern. However, I think the paths are the only option for this release. Is it worth delivering if it's the paths with manually mounting?

**Comment by aiyengar2** [comment]
@bashofmann  There's a larger discussion of this tied to the conversation following https://github.com/rancher/rancher/issues/24272#issuecomment-696041092 with a placeholder UI ticket related to this in https://github.com/rancher/dashboard/issues/1532.

re:
> Having this as a file path is not, ideal since the certificates would need to be mounted in the alertmanager pods manually. You could add additional volumes and volume mounts to alertmanager  when installing the monitoring (https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L542-L546), but it would be nicer if you could directly reference a secret with the certificates in the receiver configuration. 

The way to mount these secrets would be to provide it as [Additional Secrets](https://github.com/rancher/charts/blob/828fdd507ae0d5be0b6f017f39aff6742356c362/charts/rancher-monitoring/values.yaml#L681-L684) to the Alertmanager Pod (I believe we have a UI field for this already), which will be mounted at `/etc/alertmanager/secrets/`. This is described in more detail in the workaround described in https://github.com/rancher/rancher/issues/24272#issuecomment-696299391.

From a UI perspective, with the current release the best thing we can do imo is to leave some sort of help text that explains this process (or maybe update the docs if they don't mention this).

But the core issue here, as you described, is that there is no way to add any additional secrets without triggering a Helm upgrade on the entire monitoring chart and following this process until we move to having `AlertmanagerConfig` CRDs, which is blocked on https://github.com/rancher/rancher/issues/29871.

**Comment by bashofmann** [comment]
I think it's better to have these fields available, even if the current process is not ideal and may change when we move to `AlertmanagerConfig` CRDs. A short help text in the UI would be great then.

**Comment by codyrancher** [comment]
Tracking the documentation here https://github.com/rancher/dashboard/issues/2400

**Comment by jiaqiluo** [comment]
Reopen with the following 2 issues. 

## Email
### Issue 1: There is no `http_config` section under `email_config`
ref https://prometheus.io/docs/alerting/latest/configuration/#email_config

so instead of 
```
email_configs:
    - http_config:
        tls_config:
          ca_file: ca
          cert_file: cer
          key_file: key
      send_resolved: true
	  ...
```
it should be 
```
email_configs:
    - tls_config:
      	ca_file: ca
      	cert_file: cer
      	key_file: key
  	send_resolved: true
	...
```

otherwise, the configuration file can not be loaded with the following error in the logs of workload `alertmanager-rancher-monitoring-alertmanager`
```
level=error ts=2021-02-25T20:57:38.281Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="yaml: unmarshal errors:\n  line 7: field http_config not found in type config.plain"
```

## Webhook

### issue 2: `bearer_token` should be the same level as `basic_auth`
ref https://prometheus.io/docs/alerting/latest/configuration/#http_config

instead of 
```
        basic_auth:
          username: john
          password: lkadfjalkfafj
          bearer_token: tokentokentokentokentokentoken
```
it should be 
```
        basic_auth:
          username: john
          password: lkadfjalkfafj
        bearer_token: tokentokentokentokentokentoken
```

error in the logs of workload `alertmanager-rancher-monitoring-alertmanager`
```
level=error ts=2021-02-25T21:19:04.306Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="yaml: unmarshal errors:\n  line 35: field bearer_token not found in type config.plain"
```

**Note** 
`basic_auth`, `bearer_token` and `bearer_token_file` options are mutually exclusive, while we do not enforce this in the UI.

**Comment by deniseschannon** [comment]
Based on where we are, for v2.5.6, let's revert this enhancement for now until we can fix it properly.

**Comment by deniseschannon** [comment]
@jiaqiluo After validating that these fields are now hidden, can you move this issue back To Triage with the 2.5.7 milestone

**Comment by jiaqiluo** [comment]
on v2.5-head 1b5aad6

Confirm that 
- the UI for creating webhook and email receiver is rolled back, new fields are hidden
- creating webhook and email receiver continue working

Here is how it looks like now on v2.5-head 

![image](https://user-images.githubusercontent.com/6218999/109364866-019fd900-784d-11eb-86ed-aec5a576f492.png)

![image](https://user-images.githubusercontent.com/6218999/109364888-095f7d80-784d-11eb-9b8c-4245df675566.png)

------

Move the issue to the milestone v2.5.7

**Comment by jiaqiluo** [comment]
Reopen the issue because the `adding notifier` feature is broken on v2.5-head 4e48b8a9 with the latest UI 

After adding any notifier:
1. no notifier will show in the UI even after a refresh
2. the following error shows in the logs of the pod `alertmanager-rancher-monitoring-alertmanager-0`:
```
level=info ts=2021-03-12T18:34:46.007Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2021-03-12T18:34:46.007Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="yaml: unmarshal errors:\n  line 2: field resolve/timeout not found in type config.plain"
```
3. the following error will show in the UI if I try to add any new notifier 

<img width="796" alt="Screen Shot 2021-03-12 at 11 40 21 AM" src="https://user-images.githubusercontent.com/6218999/110984093-e55d6b00-8327-11eb-8739-d93b2d0893ec.png">

**Comment by jiaqiluo** [comment]
Reopen the issue because the `adding notifier` feature is broken on v2.5-head 4e48b8a9 with the latest UI 

After adding any notifier:
1. no notifier will show in the UI even after a refresh
2. the following error shows in the logs of the pod `alertmanager-rancher-monitoring-alertmanager-0`:
```
level=info ts=2021-03-12T18:34:46.007Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2021-03-12T18:34:46.007Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="yaml: unmarshal errors:\n  line 2: field resolve/timeout not found in type config.plain"
```
3. the following error will show in the UI if I try to add any new notifier 

<img width="796" alt="Screen Shot 2021-03-12 at 11 40 21 AM" src="https://user-images.githubusercontent.com/6218999/110984093-e55d6b00-8327-11eb-8739-d93b2d0893ec.png">

**Comment by codyrancher** [comment]
@jiaqiluo regarding your last comment.

1. Whenever you reference notifier do you actually mean receiver? I just want to make sure there isn't some nuance I'm missing.
2. I'm not seeing issues 2 or 3 as you can see from my gif and screenshot below. Are you doing something special? I'm running off of master.

![slack](https://user-images.githubusercontent.com/55104481/111108626-7b56e880-8516-11eb-8f32-66071476088b.gif)

Here you can see the next log messages after creating the slack receiver:
![image](https://user-images.githubusercontent.com/55104481/111108665-90cc1280-8516-11eb-88cb-df087bfba775.png)

**Comment by jiaqiluo** [comment]
[The issue](https://github.com/rancher/dashboard/issues/1818#issuecomment-797677557) is not seen on the latest v2.5-head 38649e2 anymore. 

The feature is validated and those 2 issues mentioned at [this comment](https://github.com/rancher/dashboard/issues/1818#issuecomment-786237211) are fixed.
