### ISSUE TITLE
[Istio V2] Add possibility to add/remove istio auto injection namespace label with a click

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1819]
The ember UI has a very handy feature to quickly add and remove the `istio-injection=enabled` namespace label with a click.

![Bildschirmfoto 2020-11-10 um 16 05 10](https://user-images.githubusercontent.com/243056/98691818-ba114200-236e-11eb-903f-2f424323cca7.png)
![Bildschirmfoto 2020-11-10 um 16 05 15](https://user-images.githubusercontent.com/243056/98691823-bb426f00-236e-11eb-899b-3425f5dbfd30.png)

It would be great, if this is also available in the new UI.

**Comment by anupama2501** [comment]
Verified on 2.5-head[v2.5-8d5b3b8d933d04b04e0f0ae3a23d48d0a962c53f-head] and master-head[master-3ba112acba52c36b87c2bf88c40a64c693fba41d-head]

Rancher versions the above has been verified on:

Rancher | v2.5-8d5b3b8d933d04b04e0f0ae3a23d48d0a962c53f-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49


Rancher | master-3ba112acba52c36b87c2bf88c40a64c693fba41d-head
User Interface | vmaster-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49



Create a cluster and from the dashboard, install monitoring[9.4.202] and istio[1.7.600] from the apps and marketplace.
From the namespaces, create multiple namespaces and once active select the created namespaces and enable the istio auto injection. Verified that the sidecar injection has been enabled. Now disable the auto-injection and verified its disabled.

Install istio[1.7.301]. Performed similar actions from above and verified its working as expected. Upgrade the istio from 1.7.301 to 1.7.600 and verified the side car is enabled/disabled.

Screenshot showing all of the namespaces have istio-auto injection enabled
<img width="838" alt="Screen Shot 2021-01-21 at 8 48 43 AM" src="https://user-images.githubusercontent.com/38144301/105383199-b51a0b80-5bc5-11eb-81da-ea187070fee5.png">


Screen shot highlights both enable and disable options as one of them has auto injection enabled and rest two has auto injection disabled
<img width="863" alt="Screen Shot 2021-01-21 at 8 48 59 AM" src="https://user-images.githubusercontent.com/38144301/105383090-974ca680-5bc5-11eb-8195-ff9c5460e2c7.png">
