### ISSUE TITLE
[Istio V2] - Double tab when opening url

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#1820]
On the istio overview page, clicking to go to the kiali dashboard you will occasionally get two tabs that open. The overall kiali area acts like a button that links out. If you click just this button, only one new tab will open to the kiali dashboard. The header/title on this button section is also a hyperlink. If you click on the header/title you will activate the hyperlink and the button event which will open two new tabs to the kiali dashboard page. 

![image](https://user-images.githubusercontent.com/19455540/98701985-1b1d2380-2337-11eb-8831-c5873f747b9b.png)

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 8d759be
rancher/rancher:master-head e4ce376

* Install Istio w/ Kiali & Jaeger
* Clicking in any area in either link only opens one new tab
