### ISSUE TITLE
[Monitoring V2] Forward port the autocomplete and preview for PrometheusRules expression editor

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1821]
The ember UI implements a very nice autocomplete and data preview for the prometheus queries when creating expression based alerts.

![Bildschirmfoto 2020-11-10 um 17 32 06](https://user-images.githubusercontent.com/243056/98702572-d024ff80-237a-11eb-9305-338a8cd52609.png)

![Bildschirmfoto 2020-11-10 um 17 32 24](https://user-images.githubusercontent.com/243056/98702567-ce5b3c00-237a-11eb-8a64-020d0fbc5fec.png)

It would be great also to add such functionality to the PrometheusRules expression editor in monitoring V2.

**Comment by catherineluse** [comment]
This ties into a larger issue about forward porting Ember features that made it easier to set up alerts. https://github.com/rancher/dashboard/issues/6325
