### ISSUE TITLE
Config/Secrets Details Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1824]
Additional info For ConfigMap:

- [ ] 1.  Show data

Additional info For Secrets:

- [ ] 1.  show data

wireframe linked [here](https://github.com/rancher/dashboard/issues/1752#issuecomment-724990080)

**Comment by tfiduccia** [comment]
Fixed

**Comment by gaktive** [comment]
Removing from board after @a-arias mentioned this to bring this back.
