### ISSUE TITLE
Ingress Details Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1825]
- [x] 1.  Table will have a list of the targets (should be links).  Won't need to have "State boxes"

wireframe linked [here](https://github.com/rancher/dashboard/issues/1752#issuecomment-724990080)

**Comment by codyrancher** [comment]
I believe we actually wanted to keep the entire Rules table that we originally had but remove everything else so that's what I did.

If my understanding is wrong let me know and I'll update accordingly.

![image.png](https://zube.io/files/rancher/6ffd69b03b88b125c78471904490e420-image.png)

**Comment by tfiduccia** [comment]
Fixed
