### ISSUE TITLE
Services Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1826]
Additional info For Services:
1. Create service details page
	1. Add Selector & Ports (public ports link to target like service list page) tabs to detail resource-tabs default tabs
		1. Selector Tab
			1. Top section is table of selector key values
			2. if Related Resources tab does not find selected pods we should add them below the key value selectors above _edit (wes): Pods have there own tab on service details page_
2. Service Create Page
	1. Selectors - Hide the info bubble (if no selector...) if we have selectors input  _edit (wes):_ _We will not hide it completely. When no selectors have been entered, the info message will display the warning. If selectors exist the info bubble will show how many pods are targeted by the current selectors._ 
	2. Session Affinity - Move info bubble to tooltip on tab title 
	3. External Name
		1. Move info bubble to tooltip on tab title
		2. Swap basic input for Labeled Input - _edit (wes): new label is `DNS Name`. this follows the patten of the docs_
	4. Listener IPs
		1. Rename tab -> IP Addresses
		2. Remove External IPs label unless both Cluster IP and External IP input are available, then show External IP label.
		3. Move tooltip currently on External IPs label to tab title tooltip

~wireframe [here](https://github.com/rancher/dashboard/issues/1752#issuecomment-724990080)~

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `2ba49cb `**

- Selector tab is added.
- Create service --> Nodeport --> Selectors --> Info text seen "If no selector is created, manual endpoints must be made." . 
- Pods have a separate TabWhen you add a key value pair, this message is not seen.
- Session Infinity has an Info tool tip
- External Name --> Has a tool tip
- External name has a label - DNS Name
- Listener IPs --> Renamed to IP Addresses
- Create Cluster IP --> IP Addresses has External IPs input. 
- Tool tip moved to title
