### ISSUE TITLE
Copy to clipboard icon and links look like open link in new window

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1830]
All the copy links are blue with a blue icon that looks like two windows (one in backgound & one in front?).  I think this is confusing?  I keep clicking them expecting them to do something.  I'm not sure it's because it blue or the icon is strange or the tooltip is missing:  but this is what used to do in ember:

![image](https://user-images.githubusercontent.com/11514927/98747709-4f173980-2375-11eb-9bcf-9fecaaf9c67d.png)

Here is Vue:

![image](https://user-images.githubusercontent.com/11514927/98747750-65bd9080-2375-11eb-9f82-82cc899be273.png)

**Comment by lvuch** [comment]
I'm going to send this to a dev with the request  to add a tooltip on hover that says `copy to clipboard` and once clicked it should say `copied`

**Comment by lvuch** [comment]
upon further inspection the following labels are not working but should be what is in the ember tooltip

action-label
waiting-label
success-label
error-label

**Comment by Ellenqs** [comment]
This is reproduced on Rancher `v2.5.5`.

**Steps**

- Deploy rancher single install.
- Go to cluster explorer -> nodes.

**Result**
The blue icon for the node ip is an open link, which should be copy to clipboard icon.

**Comment by Ellenqs** [comment]
The validation is done on rancher `v2.5-head 4cb2ebe`.

Steps are the same as previous comment.

**Results**
The node ip is not blue icon of link, there is only copy icon on the right side.
