### ISSUE TITLE
Ingress creation on pre-v1.18 clusters results in "path is undefined"

### ISSUE THREAD

**Issue by ebauman** [rancher/dashboard#1836]
Creating an `Ingress` object on pre-v1.18 clusters (when pathType was expanded in the API) results in `path is undefined`. This behavior occurs in the following scenario:

1. Have a v2.5.2 Rancher instance installed
2. Have a v1.17 or earlier Kubernetes cluster being managed
3. Attempt to create an Ingress inside of the Cluster Explorer using the _form_ method. 
4. Input any path, request host, service, etc. 

Observe that upon clicking of the _Create_ button, an error of `path is undefined` is yielded. 
![Screen Shot 2020-11-12 at 11 11 43 AM](https://user-images.githubusercontent.com/5565738/98972291-daa8db80-24d7-11eb-9f71-2da75b1df40a.png)

**Comment by ebauman** [comment]
This also appears to occur in v1.18 clusters. I upgraded the v1.17 cluster from the previous comment to v1.18. I observed the presence of the `Prefix` dropdown, but the result is the same:
![Screen Shot 2020-11-12 at 11 19 23 AM](https://user-images.githubusercontent.com/5565738/98973100-eba61c80-24d8-11eb-84ff-1cff66f6f5f1.png)

**Comment by codyrancher** [comment]
I have not been able to replicate this error.

![ingress](https://user-images.githubusercontent.com/55104481/100164576-6118d200-2e75-11eb-8da4-45e380429688.gif)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version e4ce376` and `rancher\rancher:v2.5-head` `version 3463f5a`

Steps:

- Have a v1.17 or earlier Kubernetes cluster being managed
![Screen Shot 2020-12-10 at 4 47 58 PM](https://user-images.githubusercontent.com/57409052/101843695-02f01e00-3b08-11eb-9b93-e54ab951a192.png)
- Attempt to create an Ingress inside of the Cluster Explorer using the form method.
![Screen Shot 2020-12-10 at 4 50 34 PM](https://user-images.githubusercontent.com/57409052/101843706-084d6880-3b08-11eb-97b5-f2d32267108a.png)
- Input any path, request host, service, etc.
- Create ingress

Result:
Ingress is created without error.
![Screen Shot 2020-12-10 at 4 50 41 PM](https://user-images.githubusercontent.com/57409052/101843723-0daab300-3b08-11eb-8e22-3610cb9855da.png)
