### ISSUE TITLE
Required chart installation name field not validated

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#1840]
When installing a chart, the "name" field is marked as a required field (red asterisk). But when clicking on "Install" the chart is installed even when the name is left empty.

<img width="1421" alt="Screenshot 2020-11-13 at 19 13 56" src="https://user-images.githubusercontent.com/3813921/99106679-e7ffbc00-25e4-11eb-93b2-d60de2241e28.png">

rancher master  https://github.com/rancher/rancher/commit/5aa39182429d810be1278b294aeb396a70fe28aa
CATTLE_DASHBOARD_UI_VERSION v2.5.2-rc5

**Comment by vincent99** [comment]
Removed the star since it's not actually required.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version ff16903` and `rancher\rancher:v2.5-head` `version 8d759be`

There is no longer a star next to name field. Charts can be installed without a name:
![Screen Shot 2020-12-09 at 4 18 40 PM](https://user-images.githubusercontent.com/57409052/101700643-a5da6680-3a3a-11eb-8000-131bf2214fa1.png)
