### ISSUE TITLE
Pod command and argument options are not updated when edited as form

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#1841]
Repro:

1. Create a Deployment or Daemonset
2. Fill in values for command and/or argument
3. Save
4. Edit as Form and remove the content of the command and/or argument fields
5. Check YAML

Result:
The pod spec fields are still set to their initial value

Expected:
Pod spec fields should be unset / set to an empty string

**Comment by sowmyav27** [comment]
**On 2.5.2 reproduced the issue**

- Create a Deployment or Daemonset
- Fill in values for command and/or argument
- Save
- Edit as Form
- Delete command and/or argument
- The delete is NOT saved. 
- API request sent has the values of command and/or argument
