### ISSUE TITLE
Create From YAML for CRDs is broken

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1843]
If you navigate to the Cluster Explorer UI and go to Custom Resource Definitions, there's a button to `Create From YAML`.

On clicking it, the entire Cluster Explorer UI crashes with an error that says "Maximum Call Stack Exceeded".

It then quickly redirects to:
![Screen Shot 2020-11-13 at 5 39 16 PM](https://user-images.githubusercontent.com/13127443/99136058-d663e780-25d7-11eb-8e80-2d6e5c21750d.png)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 5da52c0`

Steps:
Navigate to cluster explorer.
Navigate to `CustomResourceDefinitions`
![Screen Shot 2020-12-28 at 5 17 42 PM](https://user-images.githubusercontent.com/57409052/103250630-f9e9b400-4931-11eb-99f2-9df9d3592693.png)
`Create from YAML`

Result:
Create from YAML page is available and functional:
![Screen Shot 2020-12-28 at 5 08 47 PM](https://user-images.githubusercontent.com/57409052/103250109-88106b00-492f-11eb-8487-edb8b3ab88a3.png)
