### ISSUE TITLE
Standard Apps are gone in Apps&Marketplace since upgrade from 2.5.1 to 2.5.2

### ISSUE THREAD

**Issue by terstx** [rancher/dashboard#1848]
Hello,

I upgraded Rancher from 2.5.1 to 2.5.2 ( on Docker ). Since now all Standard Apps are gone in the Apps&Marketplace. Is there a chance to get them back to work ?

TIA

**Comment by maggieliu** [comment]
@terstx Can you clarify what do you mean by "Standard Apps"? Is it the apps installed via the Cluster Management UI don't show up in Cluster Explorer?

**Comment by richard-cox** [comment]
@terstx Can you respond to https://github.com/rancher/dashboard/issues/1848#issuecomment-731465363, and provide steps to reproduce?

**Comment by gaktive** [comment]
Closing based on age. Let us know if this is still a question in a later Rancher release.
