### ISSUE TITLE
[CIS v2] Add new field for determining ClusterScan pass/fail state based on "warn" output from tests

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#1850]
CIS profiles will now include all tests, manual and automated. Kube-bench generates "warn" output for some manual tests. The ClusterScan should by default be marked "Pass" (when they have no failures) even if the manual tests generated output "warn" instead of "pass".
There will be a new field on the ClusterScan spec with which users can make the scan "Fail" if it ran tests that generated "warn" output.
These are the openapi spec details of the field as discussed with @vincent99 :
 | k8s YAML | Type | Enum options | Default |
| -- | -- | -- | -- |
 | spec.scoreWarning | String (Enum) | pass,fail | pass | 

Can we add a dropdown or radio buttons with this header:
```
Determine Scan state for "warn" output
```
And maybe a tooltip to further explain:
```
Scans with no failures will be marked "Pass" by default even if some of the tests generate "warn" output. This behavior can be changed by selecting the "fail" option from this section
```

This field can be added right below the profile dropdown on create scan page

<img width="1785" alt="Screen Shot 2020-11-16 at 12 18 16 PM" src="https://user-images.githubusercontent.com/10672776/99303475-d5b09880-2805-11eb-8948-c183f3e49382.png">

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `395b4fe77`**

- Deploy CIS v2. Create scan CR. When scan state for warn tests is selected as "Fail" scan fails.
<img width="1394" alt="Screen Shot 2020-12-08 at 6 36 09 AM" src="https://user-images.githubusercontent.com/26032343/101497379-bfd35680-391f-11eb-9c26-148a4a60f28d.png">

<img width="1338" alt="Screen Shot 2020-12-08 at 6 35 54 AM" src="https://user-images.githubusercontent.com/26032343/101497370-bd70fc80-391f-11eb-9d5e-5223eed4421a.png">
