### ISSUE TITLE
[Logging] Allow disabling of cloud provider logs for AKS/EKS/GKE

### ISSUE THREAD

**Issue by cbron** [rancher/dashboard#1851]
Currently when you install logging, we auto-enable the relevant cloud provider framework: https://github.com/rancher/charts/tree/dev-v2.5-source/packages/rancher-logging/overlay/templates/loggings

This should be editable. For example once we determine the right provider we could display that checkbox in the UI so that the user could un-check the box, thus disabling any cloud provider specific logging.

**Comment by nickgerace** [comment]
This will need to work for GKE, AKS, and EKS dependent on PR: https://github.com/rancher/charts/pull/851

In `values.yaml` for the `rancher-logging` chart...
```
additionalLoggingSources:
  aks:
    enabled: false
  eks:
    enabled: false
  gke:
    enabled: false

**Comment by codyrancher** [comment]
@nickgerace We currently enable this option for all providers. 

1. Do we only want to enable it for the 3 here?
2. Do we only want to make it editable for the 3 here?
3 Do we want to do both 1 and 2?

**Comment by nickgerace** [comment]
@codyrancher The short version is that we just want to make it optional. This PR appears to do what we want: https://github.com/rancher/dashboard/pull/1937

**Comment by nickgerace** [comment]
@codyrancher: Is it possible to change the wording to `Enable enhanced cloud provider logging`?

**Comment by codyrancher** [comment]
> 
> 
> @codyrancher: Is it possible to change the wording to `Enable enhanced cloud provider logging`?

Done. Sorry I didn't get to it sooner. https://github.com/rancher/dashboard/pull/1975

**Comment by nickgerace** [comment]
No problem :)

**Comment by izaac** [comment]
Rancher version `v2.5-head (12/08/2020)` _8d759be_
Rancher version `master-head (12/07/2020)` _a5e40aa_

Tested the flag with checked and unchecked checkbox. With checked checkbox I notice the extra workloads created for collecting the control plane logs.

With checkbox unmarked the workloads `eks|aks|gke-fluentbit` `eks|aks|gke-fluentd` and `eks|aks|gke-fluentd-configcheck` are not created.

This is chart the option checkbox in the UI:
<img width="518" alt="Screen Shot 2020-12-08 at 4 22 01 PM" src="https://user-images.githubusercontent.com/27659/101553850-b8896880-3972-11eb-8d06-163b46c1a937.png">
