### ISSUE TITLE
[ OPA ]  Rego syntax validator

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#1860]
We want to add rego syntax validation to OPA constraint templates

Originated in https://github.com/rancher/dashboard/issues/1773

**Comment by codyrancher** [comment]
@maggieliu I don't think that this one should be prioritized for 2.5.4. I think this will require a discussion and decide if we can find a validator (I didn't find one on my initial search) or if we want to write our own.

**Comment by nwmac** [comment]
Closing - won't fix - @codyrancher please re-open if you think this is something we really should do
