### ISSUE TITLE
"Add from Resource" does not work in environment variables

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1861]
**On 2.5-head - commit id: `71da1569`**

- Create a deployment --> Environment Variables --> Click on Add from resource
- API request sent is a GET on `https://<rancher-server>/dashboard/c/c-9dkl6/explorer/apps.deployment/create?selectNode=false&strategy=RollingUpdate&privileged=false&allowPrivilegeEscalation=true&runasNonRoot=false&readOnlyRootFilesystem=false#container`
- Page seems to refresh and "Add from Resource" section is NOT available
- On clicking "Add from Resource" again, it works

**Comment by mantis-toboggan-md** [comment]
This should be resolved when this PR is merged: rancher/dashboard#1852

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `9ee39b9`**

- Create a deployment --> Environment Variables --> Dropdown has these fields
<img width="315" alt="Screen Shot 2020-11-25 at 7 38 25 AM" src="https://user-images.githubusercontent.com/26032343/100231139-9adced80-2ef4-11eb-9c9c-4916c36fa9b0.png">
