### ISSUE TITLE
Issues with Labels and Annotations field

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1862]
**On 2.5-head - commit id: `71da1569`**

Create an ingress. Add labels and annotation - key and Value
**Issue#1**
Value field appears like password field. The value is hidden
<img width="554" alt="Screen Shot 2020-11-17 at 11 34 36 PM" src="https://user-images.githubusercontent.com/26032343/99484257-faa02b00-292d-11eb-8027-9fe35c26ef15.png">

**Issue#2**
"Copy to clipboard" icon is available near the key and value pair.

**Question:** 
Why do we need "Copy to clipboard" option for a label/annotation ?

**Comment by codyrancher** [comment]
Labels and Annotations shouldn't even be visible while viewing so I'm hiding like we do elsewhere.

**Comment by sowmyav27** [comment]
**On 2.5-head-commit id: `f671292`**

- Labels and Annotations Tag has been removed from the left.
- But the Annotations on the top section , the Values are seen like password field.

@codyrancher Is that expected? Why do we need the values to appear like password field ? 
<img width="801" alt="Screen Shot 2020-11-23 at 11 23 33 PM" src="https://user-images.githubusercontent.com/26032343/100048608-32eab200-2de3-11eb-94e5-38f367fb5bdd.png">

**Comment by codyrancher** [comment]
@sowmyav27 I don't think so but I'm not sure. It started with this pr https://github.com/rancher/dashboard/pull/1837 because of this comment https://github.com/rancher/dashboard/issues/720#issuecomment-725021913.

**Comment by vincent99** [comment]
No they shouldn't be like that, but it's not related to this issue.   I'm redoing lots of shared detail stuff so i will address it.

**Comment by sowmyav27** [comment]
On the latest 2.5-head commit id `9ee39b9` - [this](https://github.com/rancher/dashboard/issues/1862#issuecomment-732644589)  is still seen.

**Comment by vincent99** [comment]
I rewrote this as part of much bigger changes..

**Comment by sowmyav27** [comment]
Closing based on [comments](https://github.com/rancher/dashboard/issues/1862#issuecomment-736318917)
