### ISSUE TITLE
[ Istio v2 ] Overview Page: Add Jaeger Link Card

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#1863]
Need to add a card on the Istio Overview Page that links to the Jaeger addon dashboard. Card should be greyed out when Jaeger is not installed

Title: Jaeger
Icon: Use the color Icon from https://branding.cncf.io/projects/jaeger/
Card Body: Monitor and Troubleshoot microservices-based distributed systems
Link: <rancher url>/api/v1/namespaces/istio-system/services/http:tracing:16686/proxy/jaeger

Example of Kiali Card for Reference 
![image](https://user-images.githubusercontent.com/19455540/99555686-cd7b6900-297d-11eb-9279-ee74f495ae6f.png)

**Backend Issue**
https://github.com/rancher/rancher/issues/29903

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 8d759be
rancher/rancher:master-head e4ce376

2 issues - an incorrect link, and we should disable the link if Jaeger is not installed. 

The current link to Jaeger brings the user to an error page. The correct link should have `/jaeger/search` appended at the end (ex: `/api/v1/namespaces/istio-system/services/http:tracing:16686/proxy/jaeger/search`)

* Create a cluster
* Install Istio w/ Jaeger enabled 
* Navigate to the Istio dashboard and click on the Jaeger card
* Jaeger shows an error
  * url is: `/api/v1/namespaces/istio-system/services/http:tracing:16686/proxy/`

![Screen Shot 2020-12-09 at 3 58 40 PM](https://user-images.githubusercontent.com/21316915/101698928-960d5300-3a37-11eb-9cb6-41226a98cbd5.png)

--

Secondly, if Jaeger is not installed or is uninstalled, the link card should be disabled similar to how we do for Kiali.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 182e3de

* Install Istio without Jaeger
  * Jaeger link card is disabled
* Upgrade Istio to install Jaeger
  * Jaeger link card is enabled
  * The link card now navigates to the correct page when loading (no error page)
