### ISSUE TITLE
Namespace Details polish

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1870]
Namespace details needs to be updated to new design:

![image](https://user-images.githubusercontent.com/11514927/99604112-03dad780-29c2-11eb-80ce-8e3fa28a3064.png)

**Comment by aaronRancher** [comment]
This feature is validated with Rancher server `rancher\rancher:v2.5-head` `version be9683f`

Namespace UI in `v2.5.5`:
![Screen Shot 2021-01-15 at 1 43 05 PM](https://user-images.githubusercontent.com/57409052/104776711-b8317980-5737-11eb-951b-67135ca35501.png)

Namespace details are updated with changes in `v2.5-head`:
![Screen Shot 2021-01-15 at 1 03 24 PM](https://user-images.githubusercontent.com/57409052/104773747-c4ff9e80-5732-11eb-8bb7-73fc4b727402.png)
