### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by dowan1995** [rancher/dashboard#1872]
Step 1
![image](https://user-images.githubusercontent.com/46449568/99610878-9a080f80-2a4d-11eb-8fd6-07a3bbe42618.png)

Step2
![image](https://user-images.githubusercontent.com/46449568/99610920-a9875880-2a4d-11eb-942c-26fdc4c36642.png)

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version ff16903` and `rancher\rancher:v2.5-head` `version 8d759be`

UI elements are properly stacked:
![Screen Shot 2020-12-09 at 12 06 32 PM](https://user-images.githubusercontent.com/57409052/101683782-a961f380-3a22-11eb-93a1-5a2474e6b5b3.png)
