### ISSUE TITLE
Ingress UI issues:

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1875]
- [x] Highlight Remove for a host field in certs is also highlighting the close X for the block (I'm not convinced this is the proper format for this field?  Seems like Host text should be outside the edit field instead of repeating for every field, but I have another issue in for headers and sent to @lvuch.  Also if a header is added and we do leave host be, then the X should be moved upwards and then maybe it won't be lost behind the initial remove.)
![image](https://user-images.githubusercontent.com/11514927/99641083-06135500-2a07-11eb-8570-0eaab37ad96d.png)

- [x] Labels is showing the translation instead of the text
![image](https://user-images.githubusercontent.com/11514927/99640411-12e37900-2a06-11eb-8960-17e5f5ee5ade.png)

- [x] Path drop-down is transparent
![image](https://user-images.githubusercontent.com/11514927/99642321-9b631900-2a08-11eb-8737-4e1f3af587ef.png)

- [ ] Don't show the table headers for Rules until there is at least 1 rule
![image](https://user-images.githubusercontent.com/11514927/99640497-31497480-2a06-11eb-9ef5-cd638bb9c0c1.png)

- [x] Spacing issues:  So there needs to be some sort of standard here.  The Remove on Labels & Annotation is very far from the end of the Value field, but fine on Rules & Certificates.  The space between the  Add buttons is not consistent either (look at the Add Path vs Add label/Annotation.  Also the space between the field title & the first set of fields for those tables are also not consistent.  (once again look at label/Annotations vs. Add path)

![image](https://user-images.githubusercontent.com/11514927/99642016-3e676300-2a08-11eb-8f1d-5005ac29f3b9.png)

![image](https://user-images.githubusercontent.com/11514927/99642055-4aebbb80-2a08-11eb-9652-c91b25b491a5.png)

**Comment by lvuch** [comment]
@codyrancher can you look at "Don't show the table headers for Rules until there is at least 1 rule"

**Comment by codyrancher** [comment]
@lvuch sure.

**Comment by tfiduccia** [comment]
1.  Table headers are still there?
For all the other "Add" where the you can remove all the rows, the headers go away.  Example - Label and Annotations
![image](https://user-images.githubusercontent.com/11514927/100145842-2f444300-2e56-11eb-80cc-71da3871e0f4.png)

2.  Transparent is still broken for Prefix

3.  Remove still has spacing issue?

**Comment by tfiduccia** [comment]
Move prematurely.  Sending back to cody

**Comment by gaktive** [comment]
This should be all done now.
