### ISSUE TITLE
Dashboard - Deployment creation issues when special characters given in name 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#1880]
Version: v2.5.2

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. In the dashboard cluster explorer - select any cluster either a sandbox or a local.
2. go to the deployments from the workloads and click on create
3. Select any namespace
4. Type in a name with special characters. eg: 'test ' 
5. provide an image and continue with all default values provided and click on create.
6. The request fails as expected. 
7. Now delete the special characters from the name and provide a value meeting the standards without any errors eg:'test'. The button to create will still show error and now hover on the button and will be changed to create. Now click on create and the request still errors out. 
8. The same deployment goes through if we start it fresh and provide the same name given in step 8.

**Result:**
Screenshots:
**Screen when special characters given failed as expected:**
<img width="1578" alt="Screen Shot 2020-11-20 at 11 12 26 AM" src="https://user-images.githubusercontent.com/38144301/99840604-b37a8b80-2b21-11eb-9909-b255843341bd.png">
**Screen when special characters removed and still fails**
<img width="1580" alt="Screen Shot 2020-11-20 at 11 12 40 AM" src="https://user-images.githubusercontent.com/38144301/99840653-d2791d80-2b21-11eb-8e66-f1ddb045c00b.png">
**Post request payload shows correct name without special characters and still the request fails**
<img width="256" alt="Screen Shot 2020-11-20 at 12 04 23 PM" src="https://user-images.githubusercontent.com/38144301/99845487-93e76100-2b29-11eb-889d-3c95400a50db.png">
<img width="796" alt="Screen Shot 2020-11-20 at 11 27 04 AM" src="https://user-images.githubusercontent.com/38144301/99845492-96e25180-2b29-11eb-86e0-4b9f5973a276.png">
<img width="1273" alt="Screen Shot 2020-11-20 at 11 27 42 AM" src="https://user-images.githubusercontent.com/38144301/99845499-99dd4200-2b29-11eb-9caf-c5c69cfd6916.png">

**Screen when same name as given in the above step in a fresh deployment is created without issues:** 
<img width="1578" alt="Screen Shot 2020-11-20 at 11 13 06 AM" src="https://user-images.githubusercontent.com/38144301/99840735-f2a8dc80-2b21-11eb-916c-3cec920640a3.png">

**Comment by vincent99** [comment]
It's the container name (inside the pod spec) that's failing.  It's likely set only-if-empty, so the first time you hit save it puts in `test<space>` and then the 2nd time it's not empty so it's not changed.

**Comment by anupama2501** [comment]
Bug fix validated on rancher master-head and v2.5-head. It is working as expected:
With space in the text:
<img width="958" alt="Screen Shot 2020-12-03 at 2 10 49 PM" src="https://user-images.githubusercontent.com/38144301/101095110-467be280-3572-11eb-96f7-d44e2213511c.png">
From the same name, spaces have been removed:
<img width="963" alt="Screen Shot 2020-12-03 at 2 10 25 PM" src="https://user-images.githubusercontent.com/38144301/101095082-3b28b700-3572-11eb-9dc8-5bda2aefd510.png">
