### ISSUE TITLE
YAML value "Show Diff" only works with rancher charts

### ISSUE THREAD

**Issue by mecseid** [rancher/dashboard#1884]
In the new UI, on Apps & Marketplace, I don't see the "Show Diff" button with any Helm 3 chart on Install/Upgrade, except the Rancher related charts.
(which comes from https://git.rancher.io/charts).

Simple Helm 3 chart:
![image](https://user-images.githubusercontent.com/6381828/99977768-5e4eac00-2da5-11eb-8f8e-cab3c4dff8a2.png)

Helm 3 chart which contains form options:
![image](https://user-images.githubusercontent.com/6381828/99977823-70c8e580-2da5-11eb-8fc1-dd582a74f5e1.png)

**Comment by richard-cox** [comment]
Quite a bit has changed over two years and I can no longer reproduce this.

When installing the `keycloak` chart from `https://charts.bitnami.com/bitnami`
> User has to make a change before there is a diff to enable the `Compare Changes` button

![image](https://user-images.githubusercontent.com/18697775/200580301-39d3392e-3ff8-4316-8eb8-9ffe4652b78d.png)

When updating install `keycloak` app
> Same as before, change in yaml is needed to show diff
![image](https://user-images.githubusercontent.com/18697775/200580704-0343a445-e997-4ed6-9f87-a26dfc8c0963.png)

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID:  d94f42a`

Along with the change from `Show Diff` to `Compare Changes`, I see the option available for Rancher and Rancher-Partner charts. I also confirmed it appears for non-partner charts as well by adding a repo from a Rancher dev that has Prometheus Federator and installed the chart from there. 

The `Compare Changes` button isn't clickable until a change is actually made to the config, and once a change has been made and the button is clicked it will show you the difference(s) from the original yaml.

![image](https://user-images.githubusercontent.com/107147272/204398287-e9b1fc28-6208-470c-98e2-bb06ae55070e.png)

I double checked this on a few older versions as well - from v2.6.6 up to the current v2.7-head commit noted above.
