### ISSUE TITLE
OPA UI fixes

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1889]
Create Constraint

- [x] Add a Parameters Header to the Parameters tab

- [x] Check Spacing (is it too far between fields now?)

- [x] The tooltip on the fields in Namespace look too low

- [x] Namespace drop-downs - remove the Namespace text that is inside the drop-down (since the header defines the fields, like scope)

- [x] We should not show the Namespace & Exclude Namespace fields Scope is Cluster

- [x] The order of the tabs should be Namespace, Rules then Parameters

- [x] Change * in Scope drop-down to be Cluster & Namespaced

--------

Design & Dev fix?

- [x] Should we somehow show what Template they picked in the top section?  After they select one, have no idea which one it was?

**Comment by lvuch** [comment]
let's do something like this to be more specific:
<img width="592" alt="Screen Shot 2020-11-24 at 3 18 09 PM" src="https://user-images.githubusercontent.com/3013118/100152410-45f39580-2e68-11eb-89d9-6ac6ff61a729.png">

**Comment by lvuch** [comment]
Dev will need to look at three unchecked

**Comment by codyrancher** [comment]
> Namespace drop-downs - remove the Namespace text that is inside the drop-down (since the header defines the fields, like scope) 

I believe this was related to the old version of the NamespaceList so I'm leaving as is.
![image](https://user-images.githubusercontent.com/55104481/100973494-e21c3d00-34f7-11eb-9841-9d4944693545.png)

The other two I've finished.

**Comment by tfiduccia** [comment]
Fixed - everything but tooltips which was changed somewhere else generically.  So I'll be following up with that in different issue.
