### ISSUE TITLE
Need Client Side Validation

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#189]
Date - 12/3/19

We will need to implement some sort of client side validation as the API has no limitation on what we can send it.

Examples:
1.  Can create a router without a port (this would be an invalid router.)

**Comment by rancher-max** [comment]
2. Can create a service without a name (fails in API with this error on UI Service Create screen: `Service.rio.cattle.io "r...1.-jm9lx" is invalid: metadata.name: Invalid value: "r...1.-jm9lx": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`)

3. Can create a service without an Image or Repo URL (service creates but is invalid)

**Comment by deniseschannon** [comment]
Closing as this is implemented generically and will be tracked for each resource individually.
