### ISSUE TITLE
Drop-down issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1896]
General:
~- [ ] After I select an option, I lose focus.  The drop-down should keep focus.~ [New Ticket](https://github.com/rancher/dashboard/issues/2008)

Ingress: Create - Add Path

- [x] The Target service Drop-down is bigger then all the fields?  If I select something, then the Port gets bigger as well?
![image](https://user-images.githubusercontent.com/11514927/100013446-11150f00-2d92-11eb-9a09-fbc7f6353f34.png)
![image](https://user-images.githubusercontent.com/11514927/100013486-225e1b80-2d92-11eb-842b-b08886f9d76d.png)

- [x] When I select a target the example text moves to the left edge for Port field
![image](https://user-images.githubusercontent.com/11514927/100013574-4d486f80-2d92-11eb-98ad-2d65ad1948ca.png)

- [x] Prefix drop-down has issues when there is more then 1 path
![image](https://user-images.githubusercontent.com/11514927/100013702-7e28a480-2d92-11eb-86a3-cf0cb27959fb.png)

Create Workload: Pod Scheduling
- [x] Drop-downs that i can type in, the text is too close to the left boarder (This might be regulated to the multi-select drop-down)
![image](https://user-images.githubusercontent.com/11514927/100017435-1d03cf80-2d98-11eb-90cc-962fb041cb3e.png)

~- [ ] In Add Volume the drop-down should open in the direction where this more space.  Right now it's always opening down and adding space to the bottom below the footer.~ [New Ticket](https://github.com/rancher/dashboard/issues/2009) 
![image](https://user-images.githubusercontent.com/11514927/100018071-1aee4080-2d99-11eb-811b-95eeeffdfbe7.png)

OPA: Create Constraint

- [x] In the Namespace tab, all the drop-downs are way bigger then they should be.
![image](https://user-images.githubusercontent.com/11514927/100016004-0492b580-2d96-11eb-80f1-81a42299fbc4.png)

Logging: Create ClusterFlows & Flows
- [x] The Specific Nodes & Specific Container drop-down are very thin until I select a node or container then they go to correct size
![image](https://user-images.githubusercontent.com/11514927/100018542-da42f700-2d99-11eb-8070-4758435a3c20.png)

~- [ ] Same issue as Volume drop-down where direction is always down and adding space below footer~ [New Ticket](https://github.com/rancher/dashboard/issues/2009) 
![image](https://user-images.githubusercontent.com/11514927/100018619-fa72b600-2d99-11eb-8aa9-949360ef0659.png)

**Comment by westlywright** [comment]
I broke the remaining items into new tickets so the bulk of this ticket can be validated without those two issues.

**Comment by tfiduccia** [comment]
Fixed
