### ISSUE TITLE
Logging Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1900]
Lists:
- [x]  Remove the width from all list page table

Output edit:

- Better design for output selection to be scalable
   - [x] Restrict 1 destination per output
   - [x] Edit form will show warning if someone added multiple destinations for a given output via edit yaml

- [x] Horizontal line should be replaced by separator component

Flow edit:
- [x] The add component should be used instead of the "+"

- Need a filter form ⇒ what's the schema (Nick to investigate)
   - [x] remove the "To Do note"

Navigation:
- [x] Bug: no counts for the CRDs

**Comment by codyrancher** [comment]
@nickgerace have you had any luck with either of these items?
- Adding monitoring graph
- Need a filter form

**Comment by nickgerace** [comment]
@codyrancher the filter form I finished last week: https://github.com/rancher/dashboard/issues/1908

As for the monitoring graph, we have not taken a look yet.

**Comment by codyrancher** [comment]
Moved the overview page monitoring graphs to rancher/dashboard#1968

**Comment by codyrancher** [comment]
I moved "Add TLS/CA fields in form similar to elastic" to rancher/dashboard#1191

**Comment by tfiduccia** [comment]
Fixed
