### ISSUE TITLE
If replicas is 0 client side validation is saying it's an error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1917]
Steps:
1.  Open create deployment
2. Put -1 in replicas and try to create (notice and error that says must be equal to or greater than 0)
3. Put 0

Results: Error stating that "Replicas is required".  0 is a valid number for this.

**Comment by vincent99** [comment]
The "required" validator is using isEmpty() and doesn't consider 0 to be set.

**Comment by tfiduccia** [comment]
Fixed
