### ISSUE TITLE
in monitoring app, prometheus Rule create blocks are not updated to new look

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1919]
Seems I missed one (or two)

steps:
1.  Install monitoring
2.  Go to Prometheus Rules create
3.  Add a Record or Alert block

Results:
Not updated to new look

**Comment by sadiapoddar** [comment]
Verified on master-head, 5da52c0 
1. Installed Monitoring app
2. created a new Prometheus rule by adding a new record.
3. It's been added to the new component block we introduced in 2.5.4 

<img width="1203" alt="Screen Shot 2020-12-30 at 12 45 22 PM" src="https://user-images.githubusercontent.com/72409237/103380273-3685ee80-4a9d-11eb-8d4e-c6eaf897bcc6.png">

Created a Prometheus rule by adding a record in 2.5.3 and seeing the Prometheus rule component block is different. 

<img width="1203" alt="Screen Shot 2020-12-30 at 12 45 44 PM" src="https://user-images.githubusercontent.com/72409237/103380308-52899000-4a9d-11eb-95d9-9db8349d3438.png">
