### ISSUE TITLE
Error: Request failed with status code 504

### ISSUE THREAD

**Issue by pomazanbohdan** [rancher/dashboard#192]
![image](https://user-images.githubusercontent.com/696713/70120344-0808ca80-1675-11ea-834b-732c723f0f93.png)

And any other parameter

`Failed to load resource: the server responded with a status of 504 ()`

![image](https://user-images.githubusercontent.com/696713/70120641-c298cd00-1675-11ea-8712-5a5993d8b7a5.png)
`upstream request timeout`

**Comment by tfiduccia** [comment]
@Pomazan-Bogdan Github integration is momentarily down.  Will let you know when it's back up.

**Comment by Pomazan-Bogdan** [comment]
@tfiduccia  Github involved at the time of installation of the rio?

https://github.com/rancher/rio/issues/890

**Comment by nwmac** [comment]
Rio is no longer supported. If this is a general Rancher dashboard issue, please feel free to re-open with additional information.
