### ISSUE TITLE
Bug: Setting job Active Deadline Seconds in GUI does not work

### ISSUE THREAD

**Issue by patrick0057** [rancher/dashboard#1923]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Create a CronJob
2) set Active Deadline Seconds

**Result:**
Active Deadline Seconds is not saved

**Other details that may be helpful:**
Setting this manually in the YAML works just fine

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA

gz#11234

**Comment by maggieliu** [comment]
Posted the question to support.

**Comment by sadiapoddar** [comment]
Verified on master-head, commit 5da52c0


1. Created a CronJob "testcrob"
2. set "Pod Active Deadline" Seconds to 99
3.  After create, brought the cronjob detail page the "Pod Active Deadline" Seconds" is showing the value that was set during creating the corn job
<img width="1626" alt="Screen Shot 2020-12-28 at 3 26 43 PM" src="https://user-images.githubusercontent.com/72409237/103248892-8a6bc880-4921-11eb-9a97-e1f0f8fe2410.png">
