### ISSUE TITLE
should add dashboard version on UI

### ISSUE THREAD

**Issue by PmcFizz** [rancher/dashboard#1927]
Hi， I'm develop dashboard.
I run a rancher container ， use `sudo docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 --privileged rancher/rancher:v2.5.1`

But I don't find the dashboard version, Should add dashboard on dashboard UI.

**Comment by tfiduccia** [comment]
@PmcFizz 
you can get to the dashboard by clicking on the blue explorer button on the Cluster list page:
![image](https://user-images.githubusercontent.com/11514927/100676524-4f787400-3326-11eb-8913-34dc3a62aee3.png)

Or when you are in a cluster, there is a big yellow button called Cluster Explorer you can click on
![image](https://user-images.githubusercontent.com/11514927/100676561-61f2ad80-3326-11eb-8692-816501b4ad15.png)

**Comment by PmcFizz** [comment]
@tfiduccia Hi Thank your reply， I know how to go dashboard。 But I don‘t know what version  the dashboard in my `rancher `images ,Where can get dashboard version my rancher server ? Thanks again.

**Comment by tfiduccia** [comment]
Dashboard and rancher version are same.

**Comment by vincent99** [comment]
The tag of dashboard shipped with Rancher releases is the same as the Rancher release.  i.e. it's `v2.5.1` also.

In this very particular case it's _actually_ `v2.5.0`... Rancher 2.5.1 was a retagging of 2.5.0 due to DockerHub corrupting the image a few hours after release.
