### ISSUE TITLE
[ Istio V2 ] - add options to component enabled / disable

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#1928]
When installing / upgrading Istio, the following options need to be added to the enabled disable component section:
 - Enabled Kiali
 - Enabled Jaeger Tracing ( limited )

Not sure what language to use to indicate that Jaeger Tracing is not production qualified, so I made a list of potential options to replace "limited" in the parathesis: local testing only, non prod, dev, not for prod, not production qualified, quick start etc... 

The default values for these can be found under:
 - `.Values.kiali.enabled`
 - `.Values.tracing.enabled` (dependent on this pr getting merged https://github.com/rancher/charts/pull/850)

Reference Section:
![Screen Shot 2020-11-30 at 1 22 02 PM](https://user-images.githubusercontent.com/19455540/100660298-11bc2100-330f-11eb-8873-eedc8b621496.png)

**Backend Issue**
https://github.com/rancher/rancher/issues/29903

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 8d759be
rancher/rancher:master-head e4ce376

* Navigate to the Istio chart and select `Components`
* Options for Kiali & Jaeger are displayed
  * Kiali is enabled by default
  * Jaeger is disabled by default
* The component status enables/disables the component according to it's status when installed / upgraded.
