### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by cbron** [rancher/dashboard#193]
![Screen Shot 2019-12-04 at 8 11 52 AM](https://user-images.githubusercontent.com/571419/70154468-c58fbf80-166d-11ea-97c3-afd89d781b70.png)

**Comment by lvuch** [comment]
![icon-rio](https://user-images.githubusercontent.com/3013118/70164811-15c34d80-167f-11ea-927d-8cb8bea63ed0.png)

**Comment by vincent99** [comment]
There already is *a* icon, the generic nuxt.js mountains.  So two different problems, an icon relevant to us and it doesn't show up when compiled for hosting at `/dashboard/` in the actual rio build.

**Comment by tfiduccia** [comment]
Date - 12/11
Verified fixed.
