### ISSUE TITLE
Cannot see app endpoint associated to services

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#194]
Should be in `status.appEndpoints` and is an array similar to `status.endpoints`.

I think it would make the most sense to show the app endpoints when clicking into the service, similar to how the version endpoints are already shown. If shown this way, it would be nice to show the service's weight % as well since that will be the approximate percentage it is returned from that endpoint. Something like below:

![image](https://user-images.githubusercontent.com/55997940/70160686-23290980-1678-11ea-9632-c9750c1f3250.png)

**Comment by rancher-max** [comment]
Should we also be able to see the app endpoints on the main service screen?

**Comment by tfiduccia** [comment]
Not sure why this is assigned to me?

**Comment by rancher-max** [comment]
I believe it was assigned to you for input on design regarding showing the app endpoints (not just the service endpoints) and the weights of the individual service revisions for rio.

**Comment by nwmac** [comment]
Rio is no longer supported. If this is a general Rancher dashboard issue, please feel free to re-open with additional information.
