### ISSUE TITLE
Unclear how to update weight on a service

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#195]
Updating the weight on a service requires clicking on the current weight percentage and setting a value. 

After clicking "Set", the popup box does not go away, which is confusing if the weight does not immediately change (which happens if I set the weight to 100%, or I'd assume would also happen if I have a slower internet connection).

**Comment by tfiduccia** [comment]
Another Rio question?

**Comment by tfiduccia** [comment]
Design "weights"  in UI for Rio

**Comment by nwmac** [comment]
Rio is no longer supported. If this is a general Rancher dashboard issue, please feel free to re-open with additional information.
