### ISSUE TITLE
Download scan report does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1951]
**On 2.5-head - commit id: `db350a63`**

- Install CIS v2 app
- Run RKE permissive scan on the cluster.
- Clicking on Download Scan report - No API call is made.
- Error in console:

<img width="388" alt="Screen Shot 2020-12-01 at 6 33 17 PM" src="https://user-images.githubusercontent.com/26032343/100820724-b3249f00-3403-11eb-9686-a81af22709e1.png">

**Comment by mantis-toboggan-md** [comment]
This should be fixed with this PR: rancher/dashboard#1981

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `395b4fe77`**

- Download report for one time scan and scheduled scan works.
- Report/reports are downloaded
