### ISSUE TITLE
Windows UX Improvements

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#1952]
Cluster Dashboard
- [x] Add a windows/linux logo to identify windows/linux clusters

Apps & Marketplace
- [x] Only show apps if applicable to windows cluster
     Requires adding annotations to charts to indicate if it’s linux or windows or both 

~- [x] Add splash screen as currently no Rancher/partner charts are windows~ edit (wes): Will follow our current pattern and will show no apps for windows message.

Continuous Delivery (Fleet)

~- [x] Hide the windows clusters from the dropdown of cluster to use~ edit (wes): Filtering already occurs since windows clusters don't get fleet agent

**Comment by maggieliu** [comment]
Annotation on the helm chart to indicate it supports windows: 
catalog.cattle.io/os:windows, linux

**Comment by westlywright** [comment]
Logo has been added to the cluster dashboard, additionally the logo is also present in the cluster switcher dropdown next to user prefs hover.

Apps will only be filtered from the windows cluster apps page IF they contain the `catalog.cattle.io/os:linux` annotation and vice versa, windows charts will only be filtered on linux cluster if they contain `catalog.cattle.io/os:windows` annotations.

**Comment by sowmyav27** [comment]
Reopening this issue as all v2 apps are listed for a windows cluster on 2.5-head - commit id: `182e3de71`

**Comment by westlywright** [comment]
@sowmyav27 I have had to update the UX of how the chart filtering works. My previous change (incorrectly) assumed that the new annotation was on the chart itself but the annotation exists on a charts different versions. I updated the logic to add the following filtering:

Apps List Page:
  - Chart will only be filtered from the view if all versions of the chart have the catalog.cattle.io/os annotation set and all versions are either linux or windows.
  - Selecting Charts will take the user to the highest version chart that either lacks the catalog.cattle.io/os annotation (assumed to work on any os) or has the catalog.cattle.io/os annotation set to the correct os provider for the cluster.

App Install/Upgrade Page:
  - Version list will list all versions of a chart, but if a particular version of the chart is incompatible with the current clusters os the user will not be able to select that version of the chart. The label of the option will show what os it is compatible with.

This is also somewhat problematic to test for me as I couldn't get my personal fork of system-charts working so I ended up doing a lot of modification on the data directly while coding. I could be wrong but my suggestion would be you create a test chart repo and update one apps versions to have all linux os annotations and one apps versions with all windows. Leave the others mixed (e.g. only the latest version of the chart has the annotation). You wont be able to successfully deploy the fake windows only app to a windows cluster but I think you should still be able to validate the changes this way.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `e2295c6 `**

- On a windows cluster --> Dashboard --> Apps and market place --> Charts --> CIS
- 1.0.300 version is NOT selectable

<img width="262" alt="Screen Shot 2020-12-16 at 2 44 57 PM" src="https://user-images.githubusercontent.com/26032343/102416263-56ea7f00-3fae-11eb-9b80-5d839476fde1.png">

- On a linux only cluster --> Dashboard --> Apps and market place --> Charts --> CIS
- 1.0.300 is selectable

<img width="528" alt="Screen Shot 2020-12-16 at 2 49 51 PM" src="https://user-images.githubusercontent.com/26032343/102416311-6d90d600-3fae-11eb-9b9c-1e912f5c8567.png">

@deniseschannon @westlywright: Have a few questions:
- Is this how we want it? Or can we NOT show the version in the dropdown that has the annotations on the windows cluster ?
- The older chart version still continue to be available on a windows cluster, as they don't have the annotations. Is this how we want it to be ?

**Comment by sowmyav27** [comment]
On a windows cluster on latest 2.5-head, fleet fails to deploy, but "Continuous delivery" is seen in CLuster explorer in windows cluster.
<img width="1660" alt="Screen Shot 2020-12-21 at 3 56 57 PM" src="https://user-images.githubusercontent.com/26032343/102913393-8b898b00-4433-11eb-9ca4-9e5516c4d8e0.png">

@deniseschannon Fleet failing to deploy has always been the case. Do we need to change something or are we good ?

**Comment by sowmyav27** [comment]
On 2.5-head - latest, validated using custom charts: branch: `thedadams:add-linux-annotation-2.5`, repo: `https://github.com/thedadams/charts` related PR: https://github.com/rancher/charts/pull/901. 
On a windows cluster, the charts were NOT available. And on a linux cluster, the charts were available.
