### ISSUE TITLE
Can't select Template when trying to create a Constraint

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1954]
Steps:
1.  Install OPA
2. Go to Constraints
3. Try to select one of the Templates

Results:  Nothing happens.  Console also says that nothing happen.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version e129f92` and `rancher\rancher:v2.5-head` `version 395b4fe`

Templates can be selected and constraint can be created:
![Screen Shot 2020-12-06 at 9 34 13 PM](https://user-images.githubusercontent.com/57409052/101309998-f1a6c900-380a-11eb-94c2-2d771cea2249.png)
