### ISSUE TITLE
In Secret details when I click Config I can't see the data

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1957]
Steps:
1.  Create a secret that has data
2.  Click on Secret name to go to details

Results:  Nothing below the name/description.  Should have data section
![image](https://user-images.githubusercontent.com/11514927/100919123-a00edf00-3496-11eb-8a24-8a9f596e8da3.png)

![image](https://user-images.githubusercontent.com/11514927/100919165-abfaa100-3496-11eb-9e82-ee21085407d0.png)

**Comment by deniseschannon** [comment]
@vincent99 says it's fixed now. Can you please check?

**Comment by tfiduccia** [comment]
fixed
