### ISSUE TITLE
Can't see drop-down value in read-only view

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1959]
Steps;
1.  Create a deployment
2. click on deployment name to get to details
3.  Click on Config

Results:  All the drop-downs are missing their content.
![image](https://user-images.githubusercontent.com/11514927/100924910-81144b00-349e-11eb-9bb9-afc35b33e0b2.png)

**Comment by tfiduccia** [comment]
A dev will have to fix this.  The values aren't there at all.

**Comment by westlywright** [comment]
This problem is no longer present on latest that I tested this morning.

**Comment by vincent99** [comment]
Oh I didn't see the issue for this but fixed it a couple days ago by removing an "if ( is view ) show different stuff" code path in selects.

**Comment by tfiduccia** [comment]
Fixed
