### ISSUE TITLE
Read-only view UI issues:

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1960]
- [x] I think it's still hard to see the text in dark view
![image](https://user-images.githubusercontent.com/11514927/100925232-f718b200-349e-11eb-96d2-61c34add4cb7.png)

- [x] Drop-downs look like they are active and have no carrot
![image](https://user-images.githubusercontent.com/11514927/100925102-c59fe680-349e-11eb-8367-667f440858e4.png)

- [x] Radio buttons are focusable & the text is too dark to see
![image](https://user-images.githubusercontent.com/11514927/100925180-e5370f00-349e-11eb-8d5f-bca8fd956bf1.png)

- [x] Add buttons just look like floating text?  maybe the outline is too dark for the fields?
![image](https://user-images.githubusercontent.com/11514927/100925417-36470300-349f-11eb-9b0e-20ffb1c1bba3.png)

-[ ] Resource Fields need styling?
![image](https://user-images.githubusercontent.com/11514927/100925520-57a7ef00-349f-11eb-8c52-83ad3ff39c72.png)

- [x] Scaling and Upgrade policy fields need styling
![image](https://user-images.githubusercontent.com/11514927/100925594-6b535580-349f-11eb-9eae-8883e9e61c61.png)

Light View
- [x] Can't see any of the field label or text inside the fields
![image](https://user-images.githubusercontent.com/11514927/100939338-58e31700-34b3-11eb-9732-b4349c93a390.png)

**Comment by lvuch** [comment]
@vincent99 can you look at "Drop-downs look like they are active and have no carrot"

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1966
https://github.com/rancher/dashboard/pull/1963
https://github.com/rancher/dashboard/pull/1946
