### ISSUE TITLE
All Block components should use <ArrayListGrouped> but aren't

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1962]
Issue:  Cody & Vincent noticed that not all the block components are using ArrayListGrouped.  Example: the Add Volume block in Create Workload: Storage tab.  

To FIx: Cody says there's not "going to be a straight forward way to find all of them. Most likely we need to look for all uses of InfoBox and see if it's being used in an ArrayList or v-for."

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, commit be72f96
Following are the component use block components and uses the "array-list-grouped" class

- Add Volume,  Pod Scheduling in Jobs, CronJobs, DaemonSets, Deployments, StatefulSets 
- Ingress Create

By inspecting each of this element made sure it's using the "array-list-grouped" class

<img width="370" alt="Screen Shot 2021-01-07 at 2 13 52 PM" src="https://user-images.githubusercontent.com/72409237/103950916-9a8a6180-50f2-11eb-85ab-9ec5e5c1669f.png">

<img width="1524" alt="Screen Shot 2021-01-07 at 2 05 54 PM" src="https://user-images.githubusercontent.com/72409237/103952737-bfcc9f00-50f5-11eb-9fc7-1daf979d26ad.png">
