### ISSUE TITLE
[Logging] Adding monitoring graph to logging overview page

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#1968]
Adding monitoring graph ⇒ pending Nick investigation

Originated in rancher/dashboard#1900

**Comment by catherineluse** [comment]
I'm closing this issue as outdated - it has been nearly two issues since this issue was opened, and it is pending investigation of someone who no longer works here. In any case, the monitoring graphs are already available from the monitoring overview pages. Can reopen if needed.
