### ISSUE TITLE
Pause rollout gives error

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#197]
Steps:
1. Create a service and give it a rollout interval and increment (I used 10 for both)
2. Stage a new version on that service. Validate that it has the same rollout interval and increment
3. After both service versions are available, set the weight on the new version to greater than 0. I used 60.
4. After the weight starts slowly incrementing up, select "Pause Rollout" from the expanded menu on the service. It gives this error:

![image](https://user-images.githubusercontent.com/55997940/70162179-78feb100-167a-11ea-8e8c-5727f73df700.png)

Looks like the request sent had body:
`{"op":"replace","path":"/spec/rollout/pause","value":true}`
and sent PATCH to:
`[my dashboard url]/v1/rio.cattle.io.v1.services/default/roll-hp9tn` where `default/roll-hp9tn` is `[namespace]/[container name]`

**Comment by tfiduccia** [comment]
Console says - vue.runtime.esm.js:1888 TypeError: this.pauseOrResume is not a function

**Comment by rancher-max** [comment]
Fixed and validated in latest master
