### ISSUE TITLE
Typos in monitoring application

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#1973]
- Prometheis should be Prometheus
- OpsGenie should be Opsgenie

**Comment by deniseschannon** [comment]
The plural of Prometheus is actually Prometheis, so that unfortunately is correct as weird as it is. 

We should correct OpsGenie to Opsgenie based on: https://www.atlassian.com/webinars/incident-management/intro-to-opsgenie

**Comment by tfiduccia** [comment]
Fixed
