### ISSUE TITLE
PODS % from node page always 0

### ISSUE THREAD

**Issue by spencergilbert** [rancher/dashboard#1974]
It appears as though when drilling into an individual node, the CPU and MEMORY displays are correct, but PODS are always shown to be 0

![image](https://user-images.githubusercontent.com/11903873/101086718-446c5080-357f-11eb-8406-66f5aa543c90.png)

**Comment by codyrancher** [comment]
Resolved in #2064

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head (5f3fcb8)`and `master-head (54b3a75)`

**Steps:**

- Deploy rancher.
- Create a downstream cluster.(or go to local cluster)
- Go to cluster explorer.
- Go to nodes, drilling into any individual node. 
- Check PODS status

**Results:**

PODS shows  % data:

![Screen Shot 2021-02-03 at 3 14 28 PM](https://user-images.githubusercontent.com/75277058/106824372-912fde80-6637-11eb-8191-1f3bd27816d8.png)

**Comment by Ellenqs** [comment]
This is reproduced on rancher `v2.5.5`.

Steps are the same as previous comment.

**Results:**
Pods metrics are 0.

![Screen Shot 2021-02-06 at 10 32 57 AM](https://user-images.githubusercontent.com/75277058/107126839-16e5a100-6867-11eb-801b-037905fbd176.png)
