### ISSUE TITLE
Logging UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1977]
- [x] Remove Info text from Overview - Chart & each create page has info text and this is just too long to be readable.
![image](https://user-images.githubusercontent.com/11514927/101072914-f003a980-355b-11eb-9163-e12f11988c20.png)

- [x] ClusterFlows  & ClusterOutputs Create - Since we are not allowing the user to determine what namespace the logging operator is in during deployment of the logging application (and they have no way of knowing without looking in Cluster Explorer).  We should not give them the option to change the namespace in ClusterFlow or ClusterOutputs Create, and set the namespace automatically.
![image](https://user-images.githubusercontent.com/11514927/101073423-ad8e9c80-355c-11eb-89af-07b9b63e03c6.png)
![image](https://user-images.githubusercontent.com/11514927/101073543-de6ed180-355c-11eb-9935-17f126d1fb4d.png)

- [x] After automatically setting namespace for ClusterFlow, on list page change Info text to say: "Logs from the cluster will be collected and logged to the selected Cluster Output."
![image](https://user-images.githubusercontent.com/11514927/101091022-cdca5580-3574-11eb-9da6-ab5ec5400786.png)

- [x] After automatically setting namespace for ClusterOutputs.  Remove Info text box.
![image](https://user-images.githubusercontent.com/11514927/101076071-175c7580-3560-11eb-9b2a-29dd89a7d881.png)

- [x] Move Output tab up one in both Create ClusterFlows & Flows.

- [x] Spacing inside the blocks is not correct, the Select Pod table seems to be not right? (maybe Lauren can take a look?)
![image](https://user-images.githubusercontent.com/11514927/101076516-b84b3080-3560-11eb-9ad3-a6966036fbd8.png)

- [x] Create ClusterOutput & Outputs:  the Access section needs to be polished.  For User field, change so that the label is inside the field and remove from above.  For Password, change inside field label to say Password from Secret and remove Password label from above
![image](https://user-images.githubusercontent.com/11514927/101077036-766eba00-3561-11eb-85f3-eaf76338c92d.png)

- [ ] Create ClusterOutput & Outputs: Change Target section:  These fields should have standard naming convention and appearance.  Parse it out to multiple yaml field if necessary.  Example... For Elasticsearch, Splunk, Fluentd & Loki, have a single URL field and parse out the Protocal, Host & POrt from that field.
![image](https://user-images.githubusercontent.com/11514927/101077581-44118c80-3562-11eb-858c-bcfcb4f4fae6.png)

- [x] In ClusterFlows & Flows lIst page table headers: Change Configured Providers to just Providers. 
![image](https://user-images.githubusercontent.com/11514927/101091842-f99a0b00-3575-11eb-8e98-7a335d43d501.png)
 
- [x]  Remove Namespace from list page table for ClusterFlow & ClusterOutputs (this will always be the same and be preset).
![image](https://user-images.githubusercontent.com/11514927/101091168-0a964c80-3575-11eb-80be-2287de6b8c4b.png)

- [x] In ClusterOutputs & Outputs list page, change table header "Providers" to Provider.
![image](https://user-images.githubusercontent.com/11514927/101091485-74aef180-3575-11eb-905d-3376cb286d1f.png)

- [x] Remove info text at top of Flows page (not sure what this means?).  Add info text to top of Outputs tab for Flow: Create saying "Output must reside in same namespace as the flow."

- [x] Can we change the output drop-down in the Create Flows to only show outputs that reside in the same namespace and not all outputs?

**Comment by codyrancher** [comment]
In my current changes I haven't done this item
> Create ClusterOutput & Outputs: Change Target section: These fields should have standard naming convention and appearance. Parse it out to multiple yaml field if necessary. Example… For Elasticsearch, Splunk, Fluentd & Loki, have a single URL field and parse out the Protocal, Host & POrt from that field.

Each of these outputs have different fields that aren't necessarily the same. In some of the places we'll be able to preserve the protocol and other places not. So if they go back to edit it https:// may not be present even though they entered it. Same goes with port. I don't want the user to be confused about what they need to/can enter and have it change between edits.

**Comment by sadiapoddar** [comment]
Verified all the requested items listed  in this issue on master-head, commit 5da52c0

Item 1: All the overview texts have been removed, now it looks like the following

<img width="2014" alt="Screen Shot 2020-12-29 at 11 34 35 AM" src="https://user-images.githubusercontent.com/72409237/103309446-eee26280-49c9-11eb-81a4-8bd0577ef1e2.png">

Item 2:  Selecting namespace during ClusterFlows & ClusterOutputs Create was removed

<img width="1833" alt="Screen Shot 2020-12-29 at 11 37 39 AM" src="https://user-images.githubusercontent.com/72409237/103309574-51d3f980-49ca-11eb-8ee6-319804eb9fa6.png">

<img width="1879" alt="Screen Shot 2020-12-29 at 11 37 57 AM" src="https://user-images.githubusercontent.com/72409237/103309586-57314400-49ca-11eb-9cfe-62d767e1813d.png">

Item 3: List page text info has been changed to the requested one

<img width="918" alt="Screen Shot 2020-12-29 at 11 39 29 AM" src="https://user-images.githubusercontent.com/72409237/103309711-a7a8a180-49ca-11eb-8e41-96a55e8dfd40.png">

Item 4: The cluster output info text is no longer there

<img width="1133" alt="Screen Shot 2020-12-29 at 11 41 53 AM" src="https://user-images.githubusercontent.com/72409237/103309817-f48c7800-49ca-11eb-8b95-7e863d642ac6.png">

Item 5:  Automatically namespace for ClusterOutputs is and the Info text box was removed. 

<img width="1133" alt="Screen Shot 2020-12-29 at 11 41 53 AM" src="https://user-images.githubusercontent.com/72409237/103310102-a88e0300-49cb-11eb-84bf-ce836c6aee23.png">

Item 6: The Output tab up one in both Create ClusterFlows & Flows.
Before the fix
<img width="481" alt="Screen Shot 2020-12-29 at 11 44 44 AM" src="https://user-images.githubusercontent.com/72409237/103310190-e2f7a000-49cb-11eb-9eba-b3be166b0f9d.png">

After the fix
<img width="229" alt="Screen Shot 2020-12-29 at 11 44 04 AM" src="https://user-images.githubusercontent.com/72409237/103310218-f0ad2580-49cb-11eb-9ac9-4e7ea41b9a4d.png">

**Comment by sadiapoddar** [comment]
The fix took care all most all the requested items. Seeing one small issue will file a separate bug for it. and update the bug link here.

**Comment by sadiapoddar** [comment]
During verifying this fix, encountered the following issues. 
https://github.com/rancher/dashboard/issues/2146
https://github.com/rancher/dashboard/issues/2145
https://github.com/rancher/dashboard/issues/2144
