### ISSUE TITLE
Monitoring UI Polish - Overview & Create Route

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1986]
- [x] Overview - Boxes used here are not consistent with any boxes we are using.  Use either Box design associated with Apps & Marketplace or selection box from Cluster explorer.
Monitoring:
![image](https://user-images.githubusercontent.com/11514927/101105815-c2365900-358b-11eb-9f34-5c2390fed5fb.png)
Apps & Marketplace:
![image](https://user-images.githubusercontent.com/11514927/101105838-d67a5600-358b-11eb-9569-29854b57b03a.png)
Cluster Explorere selection:
![image](https://user-images.githubusercontent.com/11514927/101105886-f01b9d80-358b-11eb-86c1-c4668b2d2245.png)

- [x] Overview - Spacing needs to be fixed.  Everything is too close (refer to lauren on proper spacing rules)
![image](https://user-images.githubusercontent.com/11514927/101105954-248f5980-358c-11eb-85a9-bf3ac60a4e6b.png)

~- [ ] Info boxes at top of every page is too much.  If too complicated for regular user, refer them to help and get rancher help documentation or send them to Prometheus help.  (This should be done in one place, maybe Overview if needed?)
![image](https://user-images.githubusercontent.com/11514927/101107759-34a93800-3590-11eb-911f-dc94daf3c18f.png)
![image](https://user-images.githubusercontent.com/11514927/101107775-3c68dc80-3590-11eb-834f-0341ce82ec1e.png)
![image](https://user-images.githubusercontent.com/11514927/101107781-45f24480-3590-11eb-8963-db212b9b5a4d.png)
![image](https://user-images.githubusercontent.com/11514927/101107794-50144300-3590-11eb-8fb4-6d070bf4fa91.png)
![image](https://user-images.githubusercontent.com/11514927/101107801-57d3e780-3590-11eb-98c2-3a8712c646fe.png)~

- [ ] Why is here a null receiver and Route that I can't delete in those list pages, yet it's selectable?  If this is needed for our backend we shouldn't show it to our users.
![image](https://user-images.githubusercontent.com/11514927/101106244-e47ca680-358c-11eb-8151-c967144c6d0e.png)
![image](https://user-images.githubusercontent.com/11514927/101106257-e9d9f100-358c-11eb-8db1-c384fade2b7a.png)

- [x] Create Receiver - Slack: Remove the Info box at top.

- [x] Create Receiver - Slack: Change the URL field to say "Webhook URL" and add tooltip with link "Go here to get your Incoming webhook."  With incoming webhook as link.

- [x] Create Receiver - PagerDuty: So same thing as you just did with Slack (remove info box & add tool tip to key field).

- [x] Create Receiver - OpsGenie: Table for responders need to be redone.
1.  Spacing issues: between labels & fields & buttons
![image](https://user-images.githubusercontent.com/11514927/101107346-581fb300-358f-11eb-902e-f30dd300c0d5.png)

2.  Type label is showing up twice.  Once as Header to table & Once in field.  Should only be header
![image](https://user-images.githubusercontent.com/11514927/101107254-2a3a6e80-358f-11eb-9067-e6082305884f.png)

3.  Drop-down control field height is not tall enough
![image](https://user-images.githubusercontent.com/11514927/101107406-7c7b8f80-358f-11eb-9071-38731e385edc.png)

4.  Drop-down selection is showing up as label instead of as the actual selection
![image](https://user-images.githubusercontent.com/11514927/101107444-90bf8c80-358f-11eb-8d5f-eed1be95f549.png)

5.  Send to labelshould line up with the left side of the drop-down control
![image](https://user-images.githubusercontent.com/11514927/101106912-67523100-358e-11eb-9506-2c1d10a9dafc.png)

6.  Remove button is not centered, or maybe it is, I can't tell cause field is wrong size.  maybe check after fixing field?
![image](https://user-images.githubusercontent.com/11514927/101107532-b8aef000-358f-11eb-82ea-b535c43c8d5e.png)

**Comment by westlywright** [comment]
@deniseschannon RE: Info boxes, you added these, are you okay if we remove them?

**Comment by deniseschannon** [comment]
No, do not remove them. FEs requested them.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `be9683f `**

- Overview - Boxes used are - and spacing looks good
<img width="1214" alt="Screen Shot 2021-01-15 at 1 06 57 PM" src="https://user-images.githubusercontent.com/26032343/104778664-97b2f080-5732-11eb-8f5d-d8efdd5db013.png">

- Create receiver - Slack - Info box is removed
- Create Receiver - OpsGenie: Table 
- Spacing issues: between labels & fields & buttons --> Fixed
- Type label is seen once on the header
- Drop-down control field height is not tall enough --> Fixed
- Drop-down selection --> Fixed
- Remove button is centered
<img width="1165" alt="Screen Shot 2021-01-15 at 2 44 12 PM" src="https://user-images.githubusercontent.com/26032343/104785850-650ff480-5740-11eb-8146-cd49495e87bf.png">


### Issues:

- Receivers and Route --> Show null - **ISSUE**
<img width="660" alt="Screen Shot 2021-01-15 at 1 09 19 PM" src="https://user-images.githubusercontent.com/26032343/104778859-e95b7b00-5732-11eb-95b5-4cad8b0e79b1.png">
<img width="706" alt="Screen Shot 2021-01-15 at 1 10 37 PM" src="https://user-images.githubusercontent.com/26032343/104778951-14de6580-5733-11eb-8bde-080e6f886679.png">


- Create Receiver - Slack: URL field says Webhook URL now. Tool tip with with link "Go here to get your Incoming webhook." With incoming webhook as link. is MISSING. - **ISSUE**

<img width="1415" alt="Screen Shot 2021-01-15 at 2 27 50 PM" src="https://user-images.githubusercontent.com/26032343/104784782-df8b4500-573d-11eb-9a90-bcc7d929a1d5.png">

- Create Receiver - OpsGenie: Table 
- "Send to" label is seen in the center of the dropdown field
- **Expected:** 
- Send to label should line up with the left side of the drop-down control
<img width="300" alt="Screen Shot 2021-01-15 at 2 33 31 PM" src="https://user-images.githubusercontent.com/26032343/104785728-14989700-5740-11eb-8816-a3b2fc7b92d1.png">

**Comment by westlywright** [comment]
@sowmyav27 I have some feedback from @aiyengar2 regarding hiding null Receiver and Route. We shouldn't hide it because its the default/catch all receiver/route. There could be some UX improvement here though as it is not very intuitive. I will break this out into a new ticket where we can focus on finding the correct solution. 

re Create Receiver: I am not sure why you dont see the tooltip but when I ran master this morning it is there. The tooltip icon is actually in the input, right side. I dont see it in the image, but perhaps you can check this again?

re Create Receiver - OpsGenie: I'll be opening a PR for this.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `ac48370`**

- Issue seen with tooltip -- logged https://github.com/rancher/dashboard/issues/2249
- Create Receiver - OpsGenie: Table. Send to label lines up with the left side of the drop-down control. The field, however looks highlighted. Logged - https://github.com/rancher/dashboard/issues/2250

<img width="1404" alt="Screen Shot 2021-01-26 at 6 00 07 PM" src="https://user-images.githubusercontent.com/26032343/105931610-578c2180-6000-11eb-8cb0-7dbff971171d.png">
