### ISSUE TITLE
Placeholder text in Schedule field does not look like a placeholder

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2002]
**On 2.5-head - commit id: `7e386eba`**

- Deploy CIS v2 app
- Create scan CR 
- Placeholder text in Schedule field looks like actual value in the field
<img width="1150" alt="Screen Shot 2020-12-04 at 5 34 43 PM" src="https://user-images.githubusercontent.com/26032343/101229955-94b6e180-3657-11eb-83cd-6642f792106c.png">

- This applies to other fields also like during deployment creation
<img width="1620" alt="Screen Shot 2020-12-04 at 5 37 27 PM" src="https://user-images.githubusercontent.com/26032343/101229953-92ed1e00-3657-11eb-92a6-685c4ed4805d.png">

**Comment by mantis-toboggan-md** [comment]
@lvuch is addressing placeholder styling in her pr: #1800

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `b2953cbc`**

- Deploy CIS v2 app
- Create scan CR
- Placeholder text in Schedule field looks good.
<img width="697" alt="Screen Shot 2020-12-09 at 9 14 29 PM" src="https://user-images.githubusercontent.com/26032343/101724535-ae936280-3a63-11eb-8c2c-d704f2899977.png">

- Create deployment
<img width="948" alt="Screen Shot 2020-12-09 at 9 15 01 PM" src="https://user-images.githubusercontent.com/26032343/101724539-b05d2600-3a63-11eb-8ff7-4edfd0249e5e.png">
