### ISSUE TITLE
Dashboard doesn't start on macOS

### ISSUE THREAD

**Issue by ghost** [rancher/dashboard#2004]
Running under k3d/k3s. Started my system as described in https://github.com/rancher/rio/issues/1066 and can see the demo app exposed using the endpoint exposed via `rio ps`. When I try to launch the dashboard the pod just crashes out.

```
kubectl get pod -n rio-system
NAME                              READY   STATUS             RESTARTS   AGE
linkerd-install-62bjp-zzlwn       0/1     Completed          0          33m
socat-p9frj                       1/1     Running            0          30m
socat-2zv5t                       1/1     Running            0          30m
buildkitd-74fc45579c-zc7lc        2/2     Running            0          30m
svclb-gateway-proxy-w26qm         2/2     Running            0          33m
svclb-gateway-proxy-9dgn5         2/2     Running            0          33m
rio-controller-7f5568889f-jdx82   1/1     Running            3          33m
gateway-proxy-7b87d8999f-hbvjr    1/1     Running            0          3m47s
gateway-6c76f6b5bd-ghmn6          1/1     Running            0          3m47s
gloo-58cc697f4f-bqp52             1/1     Running            0          3m47s
webhook-58959d5d67-g6vmp          1/1     Running            0          3m48s
dashboard-6c46b84bd8-z2bg9        0/1     CrashLoopBackOff   4          3m48s
```

Note this works fine...

```
rio ps
NAME                    IMAGE                                         ENDPOINT                                                   PORTS     SCALE     WEIGHT    CREATED          DETAIL
condescending-ptolemy   default/condescending-ptolemy-v0wfpgs:f8fab   http://condescending-ptolemy-v0-default.0ne80y.on-rio.io   80:8080   1         100%      34 minutes ago
```

rio version v0.8.0 (af7ad687)
k3d version v3.3.0
k3s version v1.19.4+k3s1

**Comment by balibebas** [comment]
Including output from `rio system logs`:

<details>
<summary>Expand to show logs</summary>
<pre><code>
rio system logs
rio-controller | time="2020-12-05T06:20:14Z" level=info msg="Starting rio-controller, version: v0.8.0, git commit: af7ad687"
rio-controller | time="2020-12-05T06:20:14Z" level=info msg="Updating CRD services.rio.cattle.io"
rio-controller | time="2020-12-05T06:20:14Z" level=info msg="Updating CRD stacks.rio.cattle.io"
rio-controller | I1205 06:20:14.928823       1 leaderelection.go:241] attempting to acquire leader lease  rio-system/rio...
rio-controller | time="2020-12-05T06:20:14Z" level=info msg="listening at :443"
rio-controller | I1205 06:20:14.934009       1 leaderelection.go:251] successfully acquired lease rio-system/rio
rio-controller | time="2020-12-05T06:20:15Z" level=info msg="Starting /v1, Kind=ConfigMap controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting apps/v1, Kind=DaemonSet controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting /v1, Kind=Endpoints controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting extensions/v1beta1, Kind=Ingress controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting apps/v1, Kind=StatefulSet controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting apps/v1, Kind=Deployment controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting tekton.dev/v1alpha1, Kind=TaskRun controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting /v1, Kind=Service controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting admin.rio.cattle.io/v1, Kind=PublicDomain controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting /v1, Kind=Secret controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting admin.rio.cattle.io/v1, Kind=ClusterDomain controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting admin.rio.cattle.io/v1, Kind=Certificate controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting rio.cattle.io/v1, Kind=Stack controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting rio.cattle.io/v1, Kind=ExternalService controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting rio.cattle.io/v1, Kind=Router controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting rio.cattle.io/v1, Kind=Service controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting gloo.solo.io/v1, Kind=Settings controller"
rio-controller | time="2020-12-05T06:20:17Z" level=info msg="Starting gitwatcher.cattle.io/v1, Kind=GitCommit controller"
rio-controller | 2020/12/05 06:20:23 [INFO] [*.0ne80y.on-rio.io] acme: Obtaining bundled SAN certificate
rio-controller | 2020/12/05 06:20:25 [INFO] [*.0ne80y.on-rio.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/9084333032
rio-controller | 2020/12/05 06:20:25 [INFO] [*.0ne80y.on-rio.io] acme: use dns-01 solver
rio-controller | 2020/12/05 06:20:25 [INFO] [*.0ne80y.on-rio.io] acme: Preparing to solve DNS-01
rio-controller | 2020/12/05 06:20:27 [INFO] [*.0ne80y.on-rio.io] acme: Trying to solve DNS-01
rio-controller | 2020/12/05 06:20:27 [INFO] [*.0ne80y.on-rio.io] acme: Checking DNS record propagation using [10.43.0.10:53]
rio-controller | 2020/12/05 06:20:27 [INFO] Wait for propagation [timeout: 30s, interval: 5s]
rio-controller | 2020/12/05 06:20:28 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:20:33 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:20:48 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:20:53 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:20:58 [INFO] [*.0ne80y.on-rio.io] acme: Cleaning DNS-01 challenge
rio-controller | E1205 06:20:59.938391       1 controller.go:135] error syncing '0ne80y.on-rio.io-tls': handler certificate-provisioned: acme: Error -> One or more domains had a problem:
rio-controller | [*.0ne80y.on-rio.io] time limit exceeded: last error: NS ns-1975.awsdns-54.co.uk. did not return the expected TXT record [fqdn: _acme-challenge.0ne80y.on-rio.io., value: WMOEi3DZO72UP-Amw83UEE8zVkGdUKj5sAyRHVAavcQ]: EsM_Mzwl5h24QLBfWEWlO-XTJZriAKuSBRMUXgLnJQc
rio-controller | , requeuing
rio-controller | 2020/12/05 06:21:01 [INFO] [*.0ne80y.on-rio.io] acme: Obtaining bundled SAN certificate
rio-controller | 2020/12/05 06:21:02 [INFO] [*.0ne80y.on-rio.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/9084342963
rio-controller | 2020/12/05 06:21:02 [INFO] [*.0ne80y.on-rio.io] acme: use dns-01 solver
rio-controller | 2020/12/05 06:21:02 [INFO] [*.0ne80y.on-rio.io] acme: Preparing to solve DNS-01
rio-controller | 2020/12/05 06:21:04 [INFO] [*.0ne80y.on-rio.io] acme: Trying to solve DNS-01
rio-controller | 2020/12/05 06:21:04 [INFO] [*.0ne80y.on-rio.io] acme: Checking DNS record propagation using [10.43.0.10:53]
rio-controller | 2020/12/05 06:21:04 [INFO] Wait for propagation [timeout: 30s, interval: 5s]
rio-controller | 2020/12/05 06:21:04 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:21:09 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:21:14 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:21:19 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:21:24 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:21:29 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:21:34 [INFO] [*.0ne80y.on-rio.io] acme: Cleaning DNS-01 challenge
rio-controller | E1205 06:21:36.036340       1 controller.go:135] error syncing '0ne80y.on-rio.io-tls': handler certificate-provisioned: acme: Error -> One or more domains had a problem:
rio-controller | [*.0ne80y.on-rio.io] time limit exceeded: last error: NS ns-1101.awsdns-09.org. did not return the expected TXT record [fqdn: _acme-challenge.0ne80y.on-rio.io., value: p2z364Wy1sXQmzPDDKOMlmOySW-5LfX85VDv71-zAHs]: WMOEi3DZO72UP-Amw83UEE8zVkGdUKj5sAyRHVAavcQ
rio-controller | , requeuing
rio-controller | 2020/12/05 06:21:37 [INFO] [*.0ne80y.on-rio.io] acme: Obtaining bundled SAN certificate
rio-controller | 2020/12/05 06:21:38 [INFO] [*.0ne80y.on-rio.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/9084353837
rio-controller | 2020/12/05 06:21:38 [INFO] [*.0ne80y.on-rio.io] acme: use dns-01 solver
rio-controller | 2020/12/05 06:21:38 [INFO] [*.0ne80y.on-rio.io] acme: Preparing to solve DNS-01
rio-controller | 2020/12/05 06:21:40 [INFO] [*.0ne80y.on-rio.io] acme: Trying to solve DNS-01
rio-controller | 2020/12/05 06:21:40 [INFO] [*.0ne80y.on-rio.io] acme: Checking DNS record propagation using [10.43.0.10:53]
rio-controller | 2020/12/05 06:21:40 [INFO] Wait for propagation [timeout: 30s, interval: 5s]
rio-controller | 2020/12/05 06:21:40 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:21:45 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:21:50 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:21:55 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:22:00 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:22:06 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:22:11 [INFO] [*.0ne80y.on-rio.io] acme: Cleaning DNS-01 challenge
rio-controller | E1205 06:22:12.116098       1 controller.go:135] error syncing '0ne80y.on-rio.io-tls': handler certificate-provisioned: acme: Error -> One or more domains had a problem:
rio-controller | [*.0ne80y.on-rio.io] time limit exceeded: last error: NS ns-868.awsdns-44.net. did not return the expected TXT record [fqdn: _acme-challenge.0ne80y.on-rio.io., value: _gY71r20Eu2SW8vf3yKLOTdu1QVrMwSu_b6iAaGxs9I]: p2z364Wy1sXQmzPDDKOMlmOySW-5LfX85VDv71-zAHs
rio-controller | , requeuing
rio-controller | 2020/12/05 06:22:13 [INFO] [*.0ne80y.on-rio.io] acme: Obtaining bundled SAN certificate
rio-controller | 2020/12/05 06:22:14 [INFO] [*.0ne80y.on-rio.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/9084363620
rio-controller | 2020/12/05 06:22:14 [INFO] [*.0ne80y.on-rio.io] acme: use dns-01 solver
rio-controller | 2020/12/05 06:22:14 [INFO] [*.0ne80y.on-rio.io] acme: Preparing to solve DNS-01
rio-controller | 2020/12/05 06:22:16 [INFO] [*.0ne80y.on-rio.io] acme: Trying to solve DNS-01
rio-controller | 2020/12/05 06:22:16 [INFO] [*.0ne80y.on-rio.io] acme: Checking DNS record propagation using [10.43.0.10:53]
rio-controller | 2020/12/05 06:22:16 [INFO] Wait for propagation [timeout: 30s, interval: 5s]
rio-controller | 2020/12/05 06:22:16 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:22:21 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:22:26 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:22:31 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:22:36 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:22:41 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:22:46 [INFO] [*.0ne80y.on-rio.io] acme: Cleaning DNS-01 challenge
rio-controller | E1205 06:22:47.606255       1 controller.go:135] error syncing '0ne80y.on-rio.io-tls': handler certificate-provisioned: acme: Error -> One or more domains had a problem:
rio-controller | [*.0ne80y.on-rio.io] time limit exceeded: last error: NS ns-1975.awsdns-54.co.uk. did not return the expected TXT record [fqdn: _acme-challenge.0ne80y.on-rio.io., value: xYAEe8rr9VzyGiqMoZ2U7-7W2-jui5KNCp6DjAhZjMM]: _gY71r20Eu2SW8vf3yKLOTdu1QVrMwSu_b6iAaGxs9I
rio-controller | , requeuing
rio-controller | 2020/12/05 06:22:49 [INFO] [*.0ne80y.on-rio.io] acme: Obtaining bundled SAN certificate
rio-controller | 2020/12/05 06:22:50 [INFO] [*.0ne80y.on-rio.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/9084372708
rio-controller | 2020/12/05 06:22:50 [INFO] [*.0ne80y.on-rio.io] acme: use dns-01 solver
rio-controller | 2020/12/05 06:22:50 [INFO] [*.0ne80y.on-rio.io] acme: Preparing to solve DNS-01
rio-controller | 2020/12/05 06:22:52 [INFO] [*.0ne80y.on-rio.io] acme: Trying to solve DNS-01
rio-controller | 2020/12/05 06:22:52 [INFO] [*.0ne80y.on-rio.io] acme: Checking DNS record propagation using [10.43.0.10:53]
rio-controller | 2020/12/05 06:22:52 [INFO] Wait for propagation [timeout: 30s, interval: 5s]
rio-controller | 2020/12/05 06:22:52 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:22:57 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:02 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:07 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:12 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:17 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:22 [INFO] [*.0ne80y.on-rio.io] acme: Cleaning DNS-01 challenge
rio-controller | E1205 06:23:23.489125       1 controller.go:135] error syncing '0ne80y.on-rio.io-tls': handler certificate-provisioned: acme: Error -> One or more domains had a problem:
rio-controller | [*.0ne80y.on-rio.io] time limit exceeded: last error: NS ns-51.awsdns-06.com. did not return the expected TXT record [fqdn: _acme-challenge.0ne80y.on-rio.io., value: Uq1MusR86v83FcvA8Yq1wsTntIQ99QHXaTZ4fNKsltM]: xYAEe8rr9VzyGiqMoZ2U7-7W2-jui5KNCp6DjAhZjMM
rio-controller | , requeuing
rio-controller | 2020/12/05 06:23:27 [INFO] [*.0ne80y.on-rio.io] acme: Obtaining bundled SAN certificate
rio-controller | 2020/12/05 06:23:28 [INFO] [*.0ne80y.on-rio.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/9084383307
rio-controller | 2020/12/05 06:23:28 [INFO] [*.0ne80y.on-rio.io] acme: use dns-01 solver
rio-controller | 2020/12/05 06:23:28 [INFO] [*.0ne80y.on-rio.io] acme: Preparing to solve DNS-01
rio-controller | 2020/12/05 06:23:29 [INFO] [*.0ne80y.on-rio.io] acme: Trying to solve DNS-01
rio-controller | 2020/12/05 06:23:29 [INFO] [*.0ne80y.on-rio.io] acme: Checking DNS record propagation using [10.43.0.10:53]
rio-controller | 2020/12/05 06:23:29 [INFO] Wait for propagation [timeout: 30s, interval: 5s]
rio-controller | 2020/12/05 06:23:29 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:34 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:39 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:44 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:49 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:55 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:23:59 [INFO] [*.0ne80y.on-rio.io] acme: Cleaning DNS-01 challenge
rio-controller | E1205 06:24:00.957533       1 controller.go:135] error syncing '0ne80y.on-rio.io-tls': handler certificate-provisioned: acme: Error -> One or more domains had a problem:
rio-controller | [*.0ne80y.on-rio.io] time limit exceeded: last error: NS ns-1975.awsdns-54.co.uk. did not return the expected TXT record [fqdn: _acme-challenge.0ne80y.on-rio.io., value: 3WX7QFcJNpDJdCGYEsDcIT0cawbmrt8yZLYQLhVYt4k]: Uq1MusR86v83FcvA8Yq1wsTntIQ99QHXaTZ4fNKsltM
rio-controller | , requeuing
rio-controller | 2020/12/05 06:24:12 [INFO] [*.0ne80y.on-rio.io] acme: Obtaining bundled SAN certificate
rio-controller | 2020/12/05 06:24:14 [INFO] [*.0ne80y.on-rio.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/9084394735
rio-controller | 2020/12/05 06:24:14 [INFO] [*.0ne80y.on-rio.io] acme: use dns-01 solver
rio-controller | 2020/12/05 06:24:14 [INFO] [*.0ne80y.on-rio.io] acme: Preparing to solve DNS-01
rio-controller | 2020/12/05 06:24:16 [INFO] [*.0ne80y.on-rio.io] acme: Trying to solve DNS-01
rio-controller | 2020/12/05 06:24:16 [INFO] [*.0ne80y.on-rio.io] acme: Checking DNS record propagation using [10.43.0.10:53]
rio-controller | 2020/12/05 06:24:16 [INFO] Wait for propagation [timeout: 30s, interval: 5s]
rio-controller | 2020/12/05 06:24:16 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:24:21 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:24:26 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:24:31 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:24:36 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:24:42 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:24:47 [INFO] [*.0ne80y.on-rio.io] acme: Cleaning DNS-01 challenge
rio-controller | E1205 06:24:48.230450       1 controller.go:135] error syncing '0ne80y.on-rio.io-tls': handler certificate-provisioned: acme: Error -> One or more domains had a problem:
rio-controller | [*.0ne80y.on-rio.io] time limit exceeded: last error: NS ns-1101.awsdns-09.org. did not return the expected TXT record [fqdn: _acme-challenge.0ne80y.on-rio.io., value: c7wEoY-DUUW_eeRYIzoVLZZeiOUB98yyYiRXnCogeuI]: 3WX7QFcJNpDJdCGYEsDcIT0cawbmrt8yZLYQLhVYt4k
rio-controller | , requeuing
rio-controller | 2020/12/05 06:25:30 [INFO] [*.0ne80y.on-rio.io] acme: Obtaining bundled SAN certificate
rio-controller | 2020/12/05 06:25:32 [INFO] [*.0ne80y.on-rio.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/9084414871
rio-controller | 2020/12/05 06:25:32 [INFO] [*.0ne80y.on-rio.io] acme: use dns-01 solver
rio-controller | 2020/12/05 06:25:32 [INFO] [*.0ne80y.on-rio.io] acme: Preparing to solve DNS-01
rio-controller | 2020/12/05 06:25:34 [INFO] [*.0ne80y.on-rio.io] acme: Trying to solve DNS-01
rio-controller | 2020/12/05 06:25:34 [INFO] [*.0ne80y.on-rio.io] acme: Checking DNS record propagation using [10.43.0.10:53]
rio-controller | 2020/12/05 06:25:34 [INFO] Wait for propagation [timeout: 30s, interval: 5s]
rio-controller | 2020/12/05 06:25:34 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:25:39 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:25:44 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:25:49 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:25:54 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:25:59 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:26:04 [INFO] [*.0ne80y.on-rio.io] acme: Cleaning DNS-01 challenge
rio-controller | E1205 06:26:06.432582       1 controller.go:135] error syncing '0ne80y.on-rio.io-tls': handler certificate-provisioned: acme: Error -> One or more domains had a problem:
rio-controller | [*.0ne80y.on-rio.io] time limit exceeded: last error: NS ns-1975.awsdns-54.co.uk. did not return the expected TXT record [fqdn: _acme-challenge.0ne80y.on-rio.io., value: 6nL_SSh4T3ExrGAWxBHijwotaWu7YMcQvOo9uUk7daw]: c7wEoY-DUUW_eeRYIzoVLZZeiOUB98yyYiRXnCogeuI
rio-controller | , requeuing
rio-controller | 2020/12/05 06:28:51 [INFO] [*.0ne80y.on-rio.io] acme: Obtaining bundled SAN certificate
rio-controller | 2020/12/05 06:28:52 [INFO] [*.0ne80y.on-rio.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/9084465955
rio-controller | 2020/12/05 06:28:52 [INFO] [*.0ne80y.on-rio.io] acme: use dns-01 solver
rio-controller | 2020/12/05 06:28:52 [INFO] [*.0ne80y.on-rio.io] acme: Preparing to solve DNS-01
rio-controller | 2020/12/05 06:28:54 [INFO] [*.0ne80y.on-rio.io] acme: Trying to solve DNS-01
rio-controller | 2020/12/05 06:28:54 [INFO] [*.0ne80y.on-rio.io] acme: Checking DNS record propagation using [10.43.0.10:53]
rio-controller | 2020/12/05 06:28:54 [INFO] Wait for propagation [timeout: 30s, interval: 5s]
rio-controller | 2020/12/05 06:28:54 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:28:59 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:29:04 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:29:09 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:29:14 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:29:19 [INFO] [*.0ne80y.on-rio.io] acme: Waiting for DNS record propagation.
rio-controller | 2020/12/05 06:29:24 [INFO] [*.0ne80y.on-rio.io] acme: Cleaning DNS-01 challenge
rio-controller | E1205 06:29:26.000760       1 controller.go:135] error syncing '0ne80y.on-rio.io-tls': handler certificate-provisioned: acme: Error -> One or more domains had a problem:
rio-controller | [*.0ne80y.on-rio.io] time limit exceeded: last error: NS ns-1975.awsdns-54.co.uk. did not return the expected TXT record [fqdn: _acme-challenge.0ne80y.on-rio.io., value: 5-Sv_aDHyrH71NCfJ3NuQuNDFYnH8Yh8p6jKNZUnqKg]: 6nL_SSh4T3ExrGAWxBHijwotaWu7YMcQvOo9uUk7daw
rio-controller | , requeuing
</code></pre>
</details>

**Comment by nwmac** [comment]
Rio no longer supported
