### ISSUE TITLE
[Monitoring V2 UI] Can't create a receiver

### ISSUE THREAD

**Issue by gray314** [rancher/dashboard#2007]
Can 't create a receiver on the "Cluster Explorer/Monitoring" page

![image](https://user-images.githubusercontent.com/18534037/101336260-5144b900-388b-11eb-8b5a-7e34b9309eaa.png)

![image](https://user-images.githubusercontent.com/18534037/101336628-c0baa880-388b-11eb-869a-228f39f1e09b.png)

Rancher version is v2.5.2

**Comment by deniseschannon** [comment]
@codyrancher Can you check that this is now fixed in 2.5.4 before moving it to test?

**Comment by jiaqiluo** [comment]
duplication of https://github.com/rancher/dashboard/issues/1845 fixed in v2.5-head
