### ISSUE TITLE
Dropdown Focus Lost

### ISSUE THREAD

**Issue by westlywright** [rancher/dashboard#2008]
> After I select an option, I lose focus. The drop-down should keep focus.

Broken out from https://github.com/rancher/dashboard/issues/1896

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5-head` `version be72f96`

Dropdown keeps focus after selection:
Before:
![Screen Shot 2021-01-07 at 4 59 09 PM](https://user-images.githubusercontent.com/57409052/103958300-e563a380-5109-11eb-8c51-f5c2758cc360.png)
After:
![Screen Shot 2021-01-07 at 4 59 15 PM](https://user-images.githubusercontent.com/57409052/103958302-e5fc3a00-5109-11eb-902d-9a08811ebc5c.png)
Example in header dropdown:
![Screen Shot 2021-01-07 at 5 01 30 PM](https://user-images.githubusercontent.com/57409052/103958341-00ceae80-510a-11eb-89d1-0a6cef0b7c4f.png)
