### ISSUE TITLE
Dropdown Overflow Grows Page

### ISSUE THREAD

**Issue by westlywright** [rancher/dashboard#2009]
> In Add Volume the drop-down should open in the direction where this more space. Right now it's always opening down and adding space to the bottom below the footer.
> Same issue as Volume drop-down where direction is always down and adding space below footer

Broken out from https://github.com/rancher/dashboard/issues/1896

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5-head` `version be72f96`

The dropdown opens in the direction with more space. The footer does not extend as a result.
![Screen Shot 2021-01-07 at 4 34 01 PM](https://user-images.githubusercontent.com/57409052/103956769-70db3580-5106-11eb-8d26-d36a3acff306.png)
![Screen Shot 2021-01-07 at 4 34 56 PM](https://user-images.githubusercontent.com/57409052/103956773-720c6280-5106-11eb-91ce-e0ef412ec371.png)
