### ISSUE TITLE
Selecting Build from Dockerfile in another repository does not build if branch is not specified

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#201]
**Steps:**
1. Log into the dashboard as a local user
2. Create a service, and select "Build from Dockerfile in another repository" (I want to use Github, but that button is disabled because I did not login with Github)
3. Fill in the repo url to be: `https://github.com/rancher-max/rio-demo` or `https://github.com/rancher-max/rio-demo.git` (tried both) and leave everything else blank
4. Assign port 8080 and click Create

Service is stuck creating, showing: `Building from Git...`

If I follow the same steps above, but in step (3) also supply a valid value in the "Branch" field (i.e `master`), the service builds successfully and becomes available. 

FWIW, I also tried this with a Gitlab repo and encountered the same results.

I don't see any errors in the console, and the POST request to create the service returned 201 Created.

_Request Params:_ `{"spec":{"app":"b3","build":{"repo":"https://github.com/rancher-max/rio-demo"},"dnsNameservers":[],"dnsPolicy":"Default","env":[],"globalPermissions":[],"imagePullPolicy":"Always","permissions":[],"ports":[{"expose":true,"hostPort":false,"name":"","port":8080,"protocol":"HTTP","targetPort":8080}],"rollout":{},"searches":[],"version":"v0","weight":10000}}`

_Response Payload:_ `{"spec":{"app":"b3","build":{"repo":"https://github.com/rancher-max/rio-demo"},"dnsNameservers":[],"dnsPolicy":"Default","env":[],"globalPermissions":[],"imagePullPolicy":"Always","permissions":[],"ports":[{"expose":true,"hostPort":false,"name":"","port":8080,"protocol":"HTTP","targetPort":8080}],"rollout":{},"searches":[],"version":"v0","weight":10000}}`

---

**Suggestions:**
- Send `"branch": "master"` by default in the request `spec.build.branch` field

or

- Enforce branch as a required field.

**Comment by rancher-max** [comment]
This has the same results in latest master

**Comment by nwmac** [comment]
Rio is no longer supported. If this is a general Rancher dashboard issue, please feel free to re-open with additional information.
