### ISSUE TITLE
Default column in "Benchmark Versions" page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2014]
**On 2.5-head - commit id: `395b4fe7`**

- Create a custom Benchmark version.
- Give in Min Version of kubernetes and choose a "Cluster Provider". 
- Create the CR.
- The Default column value for this Benchmark version is `true` or `checked` (check mark). In snapshot - test and test-2
- Create another custom Benchmark version - test-custom.
- Give in Min Version of kubernetes and choose a "Cluster Provider", select configmap from the dropdown. 
- Create the CR.
- The Default column value for this Benchmark version is `false` or `crossed` (cross mark). In snapshot - test-custom
<img width="1664" alt="Screen Shot 2020-12-07 at 2 08 14 PM" src="https://user-images.githubusercontent.com/26032343/101413652-7ccea000-3899-11eb-9ab0-80b271a65a82.png">

**Question:**
Why do test and test-2 have Default values set to true ?

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `b2953cbc`**

- Default column in Benchmark version page is now blank. 
<img width="1424" alt="Screen Shot 2020-12-09 at 9 09 27 PM" src="https://user-images.githubusercontent.com/26032343/101724259-0382a900-3a63-11eb-9eb9-ed79ea7272ba.png">

What is the use case where it will have value? Can we make a benchmark version the default for a cluster?

**Comment by mantis-toboggan-md** [comment]
I updated (...fixed) this column yesterday as part of this pr #2029 
![Screen Shot 2020-12-10 at 11 18 19 AM](https://user-images.githubusercontent.com/42977925/101813391-e89f4b80-3ad9-11eb-9525-1d26e63d9c8b.png)

The intention is that the column will have a checkmark for all benchmark versions installed with cis and not for anything user-created. When I initially implemented this I used Check/X icons, but I've swapped that out in favor of matching the styling of the 'default backend' yes/no column in ingresses, which uses Check/—

**Comment by vincent99** [comment]
Sounds like the column should be called "Built-In" instead of "Default"

**Comment by sowmyav27** [comment]
Reopening for a fix as per comments - https://github.com/rancher/dashboard/issues/2014#issuecomment-742772468

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `baf4867`**

- Column is name Built-in now
<img width="1163" alt="Screen Shot 2020-12-14 at 11 16 52 AM" src="https://user-images.githubusercontent.com/26032343/102125044-e6046500-3dfd-11eb-931b-1f6ffbed6f6c.png">
