### ISSUE TITLE
Required fields are not enforced when creating service

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#202]
Creating a service appears to by default have "name" and "image' as required fields. If I leave everything blank and click "create", I receive the error: 
`Service.rio.cattle.io "r...1.-jm9lx" is invalid: metadata.name: Invalid value: "r...1.-jm9lx": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

If I only fill in the "name" field, the service is created, but has no containers so never builds properly. I would expect the required fields to give some sort of alert letting me know that I missed them.

**Comment by tfiduccia** [comment]
Can you just add this to #189.  There is currently no client side validation.  So any examples you see can you just add this to the main issue.

**Comment by rancher-max** [comment]
Added and closing this as duplicate
