### ISSUE TITLE
Cluster member with CIS admin role is NOT able to list clusterscans

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2020]
**On 2.5-head - commit- `395b4fe77`**

- As an admin deploy CIS v2, create a scan CR
- Create a user - `user-1` with cis-admin roles using

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding-new
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cis-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: u-pglzp
```

- Login as user-1 --> Dashboard --> CIS benchmarks
- API response lists 1 scan, but no scans seen on the UI
<img width="1467" alt="Screen Shot 2020-12-08 at 5 26 26 AM" src="https://user-images.githubusercontent.com/26032343/101489541-f0ae8e00-3915-11eb-8118-d66d52984df7.png">

- Response:

```
{"type":"collection","links":{"self":"https://rancher-server/k8s/clusters/c-hlsw7/v1/cis.cattle.io.clusterscans"},"createTypes":{"cis.cattle.io.clusterscan":"https://rancher-server/k8s/clusters/c-hlsw7/v1/cis.cattle.io.clusterscans"},"actions":{},"resourceType":"cis.cattle.io.clusterscan","revision":"99211","data":[{"id":"scan-cbjfv","type":"cis.cattle.io.clusterscan","links":{"remove":"https://rancher-server/k8s/clusters/c-hlsw7/v1/cis.cattle.io.clusterscans/scan-cbjfv","self":"https://rancher-server/k8s/clusters/c-hlsw7/v1/cis.cattle.io.clusterscans/scan-cbjfv","update":"https://rancher-server/k8s/clusters/c-hlsw7/v1/cis.cattle.io.clusterscans/scan-cbjfv","view":"https://rancher-server/k8s/clusters/c-hlsw7/apis/cis.cattle.io/v1/clusterscans/scan-cbjfv"},"_type":"cis.cattle.io.clusterscan","apiVersion":"cis.cattle.io/v1","kind":"ClusterScan","metadata":{"creationTimestamp":"2020-12-08T13:06:51Z","fields":["scan-cbjfv",null,null,null,null,null,null,null,"",null],"generateName":"scan-","generation":1,"managedFields":[{"apiVersion":"cis.cattle.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{}},"f:spec":{".":{},"f:scanProfileName":{},"f:scheduledScanConfig":{".":{},"f:retentionCount":{},"f:scanAlertRule":{}},"f:scoreWarning":{}}},"manager":"agent","operation":"Update","time":"2020-12-08T13:06:51Z"},{"apiVersion":"cis.cattle.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{".":{},"f:NextScanAt":{},"f:ScanAlertingRuleName":{},"f:conditions":{},"f:display":{".":{},"f:error":{},"f:message":{},"f:state":{},"f:transitioning":{}},"f:lastRunTimestamp":{},"f:observedGeneration":{}}},"manager":"cis-operator","operation":"Update","time":"2020-12-08T13:06:51Z"}],"name":"scan-cbjfv","relationships":null,"resourceVersion":"97750","selfLink":"/apis/cis.cattle.io/v1/clusterscans/scan-cbjfv","state":{"error":false,"message":"Scan is Pending, Waiting for another scan to finish","name":"pending","transitioning":true},"uid":"25407b44-9826-46a1-aea5-2e7ffaeebef3"},"metadata.annotations":{},"metadata.labels":{},"spec":{"scanProfileName":"rke-profile-permissive-1.6","scheduledScanConfig":{"retentionCount":3,"scanAlertRule":{}},"scoreWarning":"pass"},"status":{"NextScanAt":"","ScanAlertingRuleName":"","conditions":[{"error":false,"lastUpdateTime":"2020-12-08T13:06:51Z","message":"ClusterScan run pending","status":"True","transitioning":false,"type":"Pending"}],"display":{"error":false,"message":"Scan is Pending, Waiting for another scan to finish","state":"pending","transitioning":true},"lastRunTimestamp":"","observedGeneration":0}}]}
```

**Comment by mantis-toboggan-md** [comment]
Updated this page so the listing should work, but determining whether or not to show the 'warn' column requires looking at the cis install config, which this role doesn't seem to have permission to do.

**Comment by sowmyav27** [comment]
@prachidamle should a user with cis-admin have access to "cis install configs" ?

**Comment by prachidamle** [comment]
@mantis-toboggan-md what is the resource that you look for cis install config? @sowmyav27 yes we need to add that resource to access

**Comment by mantis-toboggan-md** [comment]
@prachidamle I'm using the `catalog.cattle.io.app` rancher-cis-benchmark

**Comment by sowmyav27** [comment]
Waiting for [this](https://github.com/rancher/cis-operator/issues/71) issue to be fixed

**Comment by prachidamle** [comment]
@mantis-toboggan-md I do not understand why is access to install-config needed? On a 2.5-head with a user having cis-admin role I can see the "warn" column filled. For any scan that was run prior to upgrade to 2.5-head, there wont be any warn value in the clusterscan object and so it is empty.

@sowmyav27 @mantis-toboggan-md I do not think cis-admin need to have this access to install configs.

<img width="1517" alt="Screen Shot 2020-12-11 at 6 54 03 PM" src="https://user-images.githubusercontent.com/1470602/101971039-1328fb80-3be3-11eb-878a-cd74c95a11a1.png">

**Comment by mantis-toboggan-md** [comment]
@prachidamle I was using the install config to check if the version of CIS installed supported 'warn' state tests and add the column to the table accordingly; I updated (https://github.com/rancher/dashboard/pull/2065) the table to check the scan schema instead so access to install configs isn't necessary for this to work correctly now.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `182e3de71`**

- CIS v `1.0.3`, security scan - `v0.2.2-rc4`
- As an admin deploy CIS v2, create a scan CR
- Create a user - user-1 with cis-admin roles using (cluster owner and cluster memebr)
- Login as user-1 --> Dashboard --> CIS benchmarks
- User is able to list/create scans
