### ISSUE TITLE
Can't create new workspaces in Continuous Delivery

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#2022]
1.  Go to Continuous Delivery
2.  Create workspace
3.  Add a member and try to create a new workspace

Results: Can't create new workspaces in Continuous Delivery.  Error saying namespace doesn't exist.

**Comment by vincent99** [comment]
This happened when a cluster other than `local` was selected before you went into fleet view, it was talking to that cluster instead of the management one.

**Comment by tfiduccia** [comment]
Fixed and closing.
