### ISSUE TITLE
Cluster Dashboard NaN

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#2023]
The cluster dashboard is displaying NaN.

![image.png](https://zube.io/files/rancher/a7432a1be3726f6ddd62ada642d092e9-image.png)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version ff16903` and `rancher\rancher:v2.5-head` `version 8d759be`

Dashboard displays percentage values:
![Screen Shot 2020-12-09 at 11 31 25 AM](https://user-images.githubusercontent.com/57409052/101671831-47998d80-3a12-11eb-8277-01ca7c49a0e9.png)
