### ISSUE TITLE
If I create new cluster & add a new user, they can't create anything because there is no project

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#2024]
Steps:
1.  Create a local user (name him user1)
2.  Add a new cluster & add user1 as member
3.  Go to cluster Explorer

Results:  All the workload & service discovery section is missing.  Also all the Create buttons are missing.  If I go back to Cluster Manager and add a project & namespace, then I can see everything just fine.

**Comment by catherineluse** [comment]
Related issue https://github.com/rancher/dashboard/issues/5306

**Comment by gaktive** [comment]
Closing as a duplicate of the related issue, though I'll copy the missing info there for posterity.
