### ISSUE TITLE
Cannot list installed apps

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2030]
**On 2.5-head - commit id: `b2953cbccf`**

- Install CIS v2 from Charts
- Installed app is NOT available.
- Error in console:

<img width="1670" alt="Screen Shot 2020-12-09 at 6 47 13 AM" src="https://user-images.githubusercontent.com/26032343/101644801-7d2a8080-39ea-11eb-99bb-22d424e31676.png">

**Comment by mantis-toboggan-md** [comment]
This should be fixed by rancher/dashboard#2034

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `baf4867cb5`**

Installed apps can be listed.
