### ISSUE TITLE
Issue with dropdowns

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2031]
**On 2.5-head - commit id: `b2953cbccf`**

- Go to Apps & Market place --> Charts --> CIS Benchmarks
- "Install into Project" dropdown is now smaller

<img width="1418" alt="Screen Shot 2020-12-09 at 6 46 16 AM" src="https://user-images.githubusercontent.com/26032343/101645051-c7abfd00-39ea-11eb-89d1-11c4f2b150ff.png">

Also seen while doing a create Scan CR
<img width="729" alt="Screen Shot 2020-12-09 at 6 51 10 AM" src="https://user-images.githubusercontent.com/26032343/101645218-f4f8ab00-39ea-11eb-8387-716473fd31b0.png">

Is this change expected?

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5-head` `version be72f96`

Project dropdown is the correct width:
![Screen Shot 2021-01-07 at 4 30 08 PM](https://user-images.githubusercontent.com/57409052/103956513-e8f52b80-5105-11eb-85e6-91a25608c327.png)
