### ISSUE TITLE
Default scan profile is not available while creating scan CR

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2032]
**On 2.5-head - commit id: `b2953cbccf`**

- Install CIS v2 app
- Create a scan CR.
- Default scan profile is NOT available by default in the scan profile dropdown.

<img width="1072" alt="Screen Shot 2020-12-09 at 6 52 57 AM" src="https://user-images.githubusercontent.com/26032343/101645683-810ad280-39eb-11eb-9d16-1358f1cc00b8.png">

**Comment by mantis-toboggan-md** [comment]
This should be working as of this pr: #2029

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `baf4867cb5`**

Default scan is available when you "Create " A scan CR
<img width="1056" alt="Screen Shot 2020-12-11 at 9 17 28 AM" src="https://user-images.githubusercontent.com/26032343/101933950-c406aa80-3b91-11eb-9c3e-a76d5f4fd25e.png">
