### ISSUE TITLE
Issues with CIS v2 scan runs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2033]
**On 2.5-head - commit id: `b2953cbccf`**

- Deploy CIS v2
- Create a scan CR - scheduled scan - Cron: * * * * *, retention3, scan profile - rke cis 1.6 permissive
- Deploy Scan CR
- Scan runs and Status comes up Pass.
- Click on Scan CR detail page --> Report is available.

**Issue#1**
- Dropdown for the reports has changed . Is this expected? 
<img width="1414" alt="Screen Shot 2020-12-09 at 6 58 56 AM" src="https://user-images.githubusercontent.com/26032343/101646783-d3002800-39ec-11eb-913e-c5a50f8ebb1e.png">

**Issue#2**

- Let a few scheduled scans run on the cluster.
- Click on Scan detail page
- Wait until a scan starts running.
- When a scheduled scan is running, reports are NOT available (reports which are already created/available)

**Issue#3**

- Go back to Scan page after the above steps
- Scan run is Pass
- Click on Scan detail page
- Says no reports found

<img width="829" alt="Screen Shot 2020-12-09 at 7 01 19 AM" src="https://user-images.githubusercontent.com/26032343/101647036-1f4b6800-39ed-11eb-8c57-6805ff26cb88.png">

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `b2953cbc`**

- Issue#1 still exists
<img width="924" alt="Screen Shot 2020-12-09 at 9 05 17 PM" src="https://user-images.githubusercontent.com/26032343/101724071-848d7080-3a62-11eb-80fd-e02c48b1b915.png">

- Issue#2 and Issue#3 are not seen. Report is available when a scan is running and report is available. 

Reopening the issue for a fix for Issue#1

**Comment by maggieliu** [comment]
NO longer blocker because only #1 styling issue is present.

**Comment by maggieliu** [comment]
@sowmyav27 the dropdown style becoming smaller is a known issue and we decided to fix in 2.5.4 because it will have a greater impact. We will fix it in 2.5.5 and is tracked [here](https://github.com/rancher/dashboard/issues/2031)

**Comment by sowmyav27** [comment]
@maggieliu This issue deals with the styling of the dropdown - Reports specifically. The dropdown box seems a bit bigger and the header section seems bigger. 
Reopening to fix this
<img width="1405" alt="Screen Shot 2020-12-12 at 4 56 36 PM" src="https://user-images.githubusercontent.com/26032343/102000313-1f708f80-3c9b-11eb-91d6-f95be10a7e1e.png">

**Comment by mantis-toboggan-md** [comment]
I have a PR up to fix the border/header now, (the sizing issue is still present):
![Screen Shot 2020-12-14 at 9.19.51 AM.png](https://zube.io/files/rancher/1bd78799b408249bfeebbebd54c36d7e-screen-shot-2020-12-14-at-9-19-51-am.png)

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `baf4867cb`**

- The dropdown is seen fixed
<img width="1665" alt="Screen Shot 2020-12-14 at 3 46 15 PM" src="https://user-images.githubusercontent.com/26032343/102149529-8a4cd280-3e23-11eb-8445-1ee058daf270.png">
