### ISSUE TITLE
User should be able to change their own password

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#2035]
Probably as a new item in the user dropdown, here is the Ember version for reference:

![image](https://user-images.githubusercontent.com/753917/101666132-110c4480-3a0b-11eb-9d61-012eb0a54b0a.png)

**Comment by sowmyav27** [comment]
@richard-cox @lvuch Do we have PRs for this fix?

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head, df89971`.

**Steps:**

- Deploy rancher single install.
- Add a standard user u1 with a password p1.
- Logout, login as the u1 using the password p1.
- Create a cluster.
- Go to cluster explorer -> user dropdown -> Account & API keys -> Change Password (p1->p2), click apply.
- Logout, login as u1 with p2.
![Screen Shot 2021-02-09 at 9 33 00 AM](https://user-images.githubusercontent.com/75277058/107407225-480bde80-6abe-11eb-8a51-0cab10a17a61.png)


**Result**
The user login successfully with new password p2.

**Comment by sowmyav27** [comment]
Reopening to do a few more checks
- changes mentioned here https://github.com/rancher/dashboard/issues/2035#issuecomment-775415312 in this PR
- Change Password UI -- Generate Random Password and Delete aall existing API Keys check boxes.
- Check how UI between Ember vs Dashboard is for Generate Random password and other fields

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head,03b8153`

**Steps**

- Deploy rancher single install.
- Add a standard user u2 with a password p2.
- Logout, login as the u2 using the password p2.
- Create a cluster. 
- Add two keys: k1 , k2.
<img width="716" alt="Screen Shot 2021-02-17 at 11 54 00 AM" src="https://user-images.githubusercontent.com/75277058/108260953-c9dfb580-7117-11eb-9e48-eb1597c42866.png">

- Go to cluster explorer -> user dropdown -> Account & API keys. Page is desplayed as below.
<img width="492" alt="Screen Shot 2021-02-17 at 12 06 59 PM" src="https://user-images.githubusercontent.com/75277058/108261625-bda82800-7118-11eb-8e58-bf254624d8f7.png">


- Check delete all existing API keys.
- Check generate random password.
<img width="766" alt="Screen Shot 2021-02-17 at 11 54 46 AM" src="https://user-images.githubusercontent.com/75277058/108261841-0233c380-7119-11eb-9048-9e97ef8a6b89.png">


- Logout , login as u2 with generated random key.

**Results**
Login as u2 with random password successfully, API keys k1 and k2 have been deleted.
<img width="945" alt="Screen Shot 2021-02-17 at 11 56 08 AM" src="https://user-images.githubusercontent.com/75277058/108261383-6efa8e00-7118-11eb-9e03-9a0e971e2f0c.png">
