### ISSUE TITLE
Scan details page hangs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#2036]
Steps:
1.  Install CIS
2.  Go to Scan and Create
3.  Create with defaults
4.  Click on name of scan

Results:  Details page hangs.  Error in console "vue.runtime.esm.js:1888 TypeError: Cannot read property 'summary' of undefined".  Looks like the page will hang until the scan is finished running.  We should do something about that.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `baf4867c`**

- Install CIS v2 app v 1.0.3
- Scans --> Create a scan --> When scan is running, click on the scan
- No error in console seen
