### ISSUE TITLE
Cannot change Dockerfile name when building from Github repo

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#204]
Default is Dockerfile and there are no options to change it or type something else in

Steps:
1. Login with Github
2. Create a new service and select "Build from Dockerfile in a Github repo"
3. Select a repo that has a valid Dockerfile that is named something other than "Dockerfile" (I used https://github.com/rancher-max/rio-demo branch: double-docker)
4. Select the appropriate branch, and try to change the Dockerfile to something different.

The repo I used above has a file named `testDockerfile` that I am unable to select/type in. Whenever I try to type it, as soon as I tab or click away, it is replaced by `Dockerfile`

![image](https://user-images.githubusercontent.com/55997940/70187411-58028400-16ab-11ea-8875-a353cdaaffaf.png)

**Comment by vincent99** [comment]
The UI filters for `Dockerfile*` because that's what they're almost universally called.

**Comment by rancher-max** [comment]
I'm fine with the filter, but can we allow free-form text as well? There are always those who like to be different and do things like `<purpose>.Dockerfile`

**Comment by nwmac** [comment]
Rio is no longer supported. If this is a general Rancher dashboard issue, please feel free to re-open with additional information.
