### ISSUE TITLE
To create any service port & target port required but no * and should be first

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#2040]
Issue:  For Service, the Port & Target are required fields

Resolution:

~- [ ] Add a red * by label name~ _Edit: wes_ Name is not required according to spec and validation on backend.

- [x] Make Service Ports tab first tap in list Or add them to the first tab and rename the tab to Service info or something.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 4f72515` and `rancher\rancher:v2.5-head` `version 2b061d7`

Service ports are on the first tab. Listening Port and Target Port are required fields:
![Screen Shot 2021-01-08 at 5 05 33 PM](https://user-images.githubusercontent.com/57409052/104076697-11e3f200-51d4-11eb-8925-db2d1005f58f.png)
