### ISSUE TITLE
[Logging v2] Change Syslog Output "transport" to be a dropdown menu

### ISSUE THREAD

**Issue by nickgerace** [rancher/dashboard#2050]
@izaac and I believe that the "Transport" string isn't intuitive and can cause unassuming breakages in setting up the new syslog plugin.

Currently, the "transport" string field defaults to "tls", which is not immediately obvious. Having a dropdown menu with the following three options would be best.

- `tls`
- `udp`
- `tcp`

Reference: https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/syslog/
Original Issue: https://github.com/rancher/rancher/issues/29892

**Comment by nickgerace** [comment]
This is more of a question than a request: is it possible to have a fourth "other" option that enables a text box for manual string input? I can see how that would be useful, useless, or unwanted, but I thought I'd ask.

**Comment by izaac** [comment]
Rancher version: `master-head (12/15/2020)` _e971e07_

Validated the dropdown has the three options shown tls, tcp, udp. And tls being the default as the chart.
The generated yaml was valid.
