### ISSUE TITLE
Backup/Restore Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#2056]
**Deployment:** 

- [x] On the storage class field the tooltip warning message should stay

**Backup CRD:**

Edit Page:

- [x] Schedule should be consistent with workload (cron input type)
- [ ] Tool tip for encryption config secret's style to make it taller ⇒ Lauren

List:

- [x] State/Status ⇒ need to figure out what's the difference and if we should consolidate followup with Rajashree
- [x] The table didn't change and the detail page didn't change, not refreshing
- [x] Latest-backup ⇒ should be a custom (Backup File Name)
- [x] Add 2 columns for the last and next backup dates
- [x] Remove Age

Details:

- [x]  In the "config" view should be showing everything. Remove the hiding

**Restore CRD:**

List:

- [x] State/status should be consolidated

Details:

- [x] check box style should be disable ⇒ lauren
- [x] Radio button doesn't show which one is selected ⇒ lauren

**Comment by mantis-toboggan-md** [comment]
Adding some clarity for QA:

> * [x]  On the storage class field the tooltip warning message should stay

The warning tooltip (and border) for the storage class dropdown disappeared when different storage radio options were toggled between

> **Backup CRD:**
> 
> Edit Page:
> 
> * [x]  Schedule should be consistent with workload (cron input type)

Input field should have a human-readable display of the cron schedule, as seen in Cron Jobs 

> 
> List:
> 
> * [x]  State/Status ⇒ need to figure out what's the difference and if we should consolidate followup with Rajashree

Table views for backup and restore both had 'state' and 'status' columns; they should now have 'status' displayed with the styling from the 'state' column
> * [x]  The table didn't change and the detail page didn't change, not refreshing

backupfilename needed page refresh to show changes when a scheduled backup ran
> * [x]  Latest-backup ⇒ should be a custom (Backup File Name)

'Latest-Backup' table header needs a space in it/should be changed to: Backup File Name

> Details:
> 
> * [x]   In the "config" view should be showing everything. Remove the hiding

If scheduling/encryption weren't enabled, their radio groups did not appear in view mode

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `ac48370`**

- The warning tooltip (and border) for the storage class dropdown stays when different storage radio options are toggled between

**Backup CRD**
- Input field of the cron schedule is as seen in Cron Jobs

**List page**
- State is displayed
- latest backupfilename is displayed without refresh for a recurring backup
-  Backup File Name column is available
- 2 columns for the last and next backup dates are avalable
- Age column is not available
<img width="1403" alt="Screen Shot 2021-01-26 at 8 42 21 PM" src="https://user-images.githubusercontent.com/26032343/105943914-223efe00-6017-11eb-84d7-7b4c1f3db15e.png">

- When scheduling/encryption arent enabled, their radio groups appears in view mode in Details page
<img width="979" alt="Screen Shot 2021-01-26 at 8 43 48 PM" src="https://user-images.githubusercontent.com/26032343/105944052-6500d600-6017-11eb-9f64-f6df828698cf.png">
