### ISSUE TITLE
Edit of CIS v2 Scan CRs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2057]
**On 2.5-head - commit id: `baf4867cb`**

**Issue#1**

- Deploy CIS v2 latest version
- run a scan - enable scheduled scans.
- Edit a scan cr, change scan CR to be a one time scan now
- API request sent, contains all the values for `cheduledScanConfig`  and the scheduled scan is NOT disabled.

**Expected:**
Edit and Save should work

**Issue#2**
- Why would a user want to Edit a one time scan CR created? 
- User editing a scheduled scan CR created makes sense because Alerting - can be configured.

@prachidamle Could you provide your thoughts on this ? 

**Expected:**
Action Edit should not be available for a one time scan run.

**Comment by prachidamle** [comment]
@sowmyav27 yeah for one time scan we need not provide the edit option.

**Comment by sowmyav27** [comment]
**ON 2.5-head - commit id: `baf4867` with latest cis v2 charts: `rancher-cis-benchmark:1.0.300`**

**Scenario#1**
- Create a one time scan CR. Spec contains only `spec: {scanProfileName: "rke-profile-permissive-1.6", scoreWarning: "pass"}` and does not contain `s cheduledScanConfig`. 

**Scenario#2**
- One time scan CR does not have the "Edit" option
<img width="920" alt="Screen Shot 2020-12-12 at 4 51 10 PM" src="https://user-images.githubusercontent.com/26032343/102000267-8ccff080-3c9a-11eb-8d77-906598d94868.png">
