### ISSUE TITLE
Nodes Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#2058]
List:

- [ ] CPU & RAM are not showing correct numbers for certain types of cluster

View:

- [x] Gauges should be consistent with the cluster dashboard
- [x] Wireframe for this page (need it for the flags: PID/disk/memory/kubelet) ⇒ Lauren
- [x] Drop the address tab ⇒ Make sure all the information on that tab already included on the top
- [x] Add new Pod tab similar to the Deployment view, but the columns should be from POD list page
- [x] Images tab: there are 2 images with no name

- Info:
   - [x]    gray out empty values
   - [x]     convert the keys to translation so the names are cap correctly

- [x] Delete the node edit component

**Comment by lvuch** [comment]
<img width="840" alt="Screen Shot 2020-12-21 at 10 57 29 AM" src="https://user-images.githubusercontent.com/3013118/102807109-53bf0c80-437b-11eb-89e6-6292b101ec61.png">

**Comment by lvuch** [comment]
<img width="895" alt="Screen Shot 2020-12-21 at 2 25 15 PM" src="https://user-images.githubusercontent.com/3013118/102823571-5bd97500-4398-11eb-8381-78825ddf9109.png">

**Comment by lvuch** [comment]
@vincent99 @codyrancher here are some options 
https://xd.adobe.com/view/dd7f8f53-c196-49e9-83b7-725835d648db-882c/

**Comment by codyrancher** [comment]
I think I prefer #1 or just coloring the bar/text and put the icon next to the resource label.

@vincent99 Do you have a preference?

**Comment by vincent99** [comment]
The first one seems fine to me..

**Comment by codyrancher** [comment]
1. I didn't  _gray out empty values_. I just got rid of the empty values.
1. I also didn't fix cpu & ram issue because it appears to be a backend problem. I opened an issue for that item here https://github.com/rancher/rancher/issues/30657

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `be72f96`**

- Gauges are consistent with the cluster dashboard
- Wireframe has changed
- Address Tab has been dropped.
<img width="1642" alt="Screen Shot 2021-01-07 at 1 22 29 PM" src="https://user-images.githubusercontent.com/26032343/103946424-6cedea00-50eb-11eb-8da9-a074e06ff8d9.png">

- Pods tab is available, and lists the pods on the node.
- There are no images with empty name

**Info:**

- gray out empty values - Logged a separate issue for this https://github.com/rancher/dashboard/issues/2180
- convert the keys to translation so the names are cap correctly --> Seen fixed.
- Edit yaml option is not available for nodes.
