### ISSUE TITLE
Cluster Explorer: Deployment pods are not filtered by namespace

### ISSUE THREAD

**Issue by adampl** [rancher/dashboard#2067]
**What kind of request is this:**
bug (I assume it's not a feature)

**Steps to reproduce:**
1. Create the same deployment (with the same name) in two namespaces
1. Ensure that _Cluster Explorer_ is in _All namespaces_ or _Only user namespaces_ mode
1. In the _Cluster Explorer_ sidebar go to _Workload_ / _Deployments_
1. View the deployment in one of the namespaces

**Result:**
Pods from both namespaces are listed in the _Pods_ section

**Other details that may be helpful:**
Only pods from the selected deployment should be visible, regardless of the global namespace filter mode.
This may be the case with other workloads, and not only with pods.

**Environment information**
- Rancher version: 2.5.2
- Installation option: single

**Comment by sadiapoddar** [comment]
Used 2.5.2 branch

1. Created the same deployment (with the same name) in two namespaces
2. Ensured that Cluster Explorer is in All namespaces or Only user namespaces mode
3. In the Cluster Explorer sidebar go to Workload / Deployments
The deployment view
<img width="1537" alt="Screen Shot 2020-12-13 at 1 28 39 PM" src="https://user-images.githubusercontent.com/72409237/102024544-85b2ec00-3d47-11eb-840d-8394f5ae77bd.png">

If you click on one of the deployments, it used to look like the following. 

<img width="1531" alt="Screen Shot 2020-12-13 at 1 28 52 PM" src="https://user-images.githubusercontent.com/72409237/102024565-9cf1d980-3d47-11eb-8b68-05c1662b8e59.png">

Verified the fix on 2.5-head, e3f52647 and master-head, e971e07

1. Created the same deployment (with the same name) in two namespaces
2. Ensured that Cluster Explorer is in All namespaces or Only user namespaces mode
3. In the Cluster Explorer sidebar go to Workload / Deployments
The deployment view
<img width="1796" alt="Screen Shot 2020-12-13 at 1 37 55 PM" src="https://user-images.githubusercontent.com/72409237/102024754-cb23e900-3d48-11eb-8eb1-459ec82c7bd5.png">

If you click on the deployment view, the pod is listed with status, namespace, and other information distinctly. 

<img width="1759" alt="Screen Shot 2020-12-13 at 1 23 32 PM" src="https://user-images.githubusercontent.com/72409237/102024833-3077da00-3d49-11eb-9e3a-96bc6400a2f0.png">
