### ISSUE TITLE
CIS v2 report: Skip field actual_value_per_node from the .csv report downloaded by the user

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#2071]
There has been a change added to the report data generated for the cluster scan, field "actual_value" from the report has been replaced by this map: 
ActualValueNodeMap map[string]string `json:"actual_value_per_node"`

But seems like the code that converts the json from ClusterScanReport does not handle non-scalar fields. If we cannot support that, we should skip this field "actual_value_per_node" from the .csv file

Backend ticket: https://github.com/rancher/security-scan/issues/28

**Comment by prachidamle** [comment]
@maggieliu I added this ticket since we need to change the downloaded clusterscan report due to the backend change https://github.com/rancher/security-scan/issues/28

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `182e3de7`**

- Using cis v 1.0.3 and rancher/security-scan: `v0.2.2-rc4`
- `actual_value_per_node` is NOT available in the downloaded reports
