### ISSUE TITLE
Logging chart - LogDNA api_key field should be a secret selector and mandatory. Output and ClusterOutput

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2074]
Rancher version `v2.5-head (12/14/2020)` _ e3f5264_

According to the banzai cloud [documentation for LogDNA](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/logdna/) ClusterOutput and Output the `api_key` field is mandatory. 

The current UI is using a text input field for this and if we leave it empty the generated YAML result in `api_key: ""`

I think we should handle this field the same with other Outputs using a secret selector for consistency. See Splunk, Amazon Elasticsearch or Datadog outputs.

![Screen Shot 2020-12-14 at 11 47 30 AM](https://user-images.githubusercontent.com/27659/102122085-3aa9df00-3e02-11eb-8d60-d65765bb33a4.png)

rancher/dashboard#1192
rancher/dashboard#1191

**Comment by codyrancher** [comment]
@izaac We can make this field required but I don't think we can/should make this a SecretSelector. 

The output fields that we used a SecretSelector for are Secret types. Here the api_key is a string. If we wanted to extract the value of the selected secret and key it would still be a string in the yaml.

**Comment by izaac** [comment]
Rancher `v2.5-head (12/22/2020)` _bd660e1_

Reopening, the api_key field is checked now when trying to create the Output/ClusterOutput but the field is missing the required visual indicator in the UI (the red asterisk).

The Name field has the red asterisk but not the `api_key` input.

<img width="607" alt="Screen Shot 2020-12-22 at 11 34 28 AM" src="https://user-images.githubusercontent.com/27659/102921524-bed71480-4449-11eb-84e3-ee6ec5b64c01.png">

I also opened a separate issue for the hostname, which is also required #2133

**Comment by izaac** [comment]
After I refreshed the browser I was able to see the marker. #2133 however is still a valid issue
