### ISSUE TITLE
Logging chart - Port range validation for some Outputs/ClusterOutputs

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2075]
Rancher version `v2.5-head (12/14/2020)` _ e3f5264_

- Elasticsearch
- Fluentd
- LogZ
- Splunk

These outputs/clusteroutputs have a Port input field and I am able to put arbitrary text in there or ports not in the valid port ranges for ipv4.

We should add some simple UI validation if that's possible.

rancher/dashboard#1191
rancher/dashboard#1192

**Comment by codyrancher** [comment]
@izaac Do you know of anywhere else that we do this port validation?

**Comment by izaac** [comment]
Rancher version `v2.5-head (12/22/2020)` _bd660e1_

Now the Output/ClusterOutput forms change the port to MAX 65535 if the port is greater than that value or 1 if we start typing with a zero. I think this would be enough to remind users the port ranges.

Checked the Outputs/ClusterOutputs:

- Elasticsearch
- Fluentd
- LogZ
- Splunk
