### ISSUE TITLE
rke-profile-permissive is available for clusters with k8s 1.15 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2081]
**On 2.5-head - commit id: `baf4867c`**

- Create a 1.15.12-rancher2-7 cluster(version through cluster.yml)
- Deploy CIS v2 on the cluster.
- `rke-profile-permissive` is available in dropdown and NOT `rke-profile-permissive-1.5`
<img width="1668" alt="Screen Shot 2020-12-14 at 1 33 10 PM" src="https://user-images.githubusercontent.com/26032343/102138255-ef4afd00-3e10-11eb-9d9c-93711284226e.png">

**Comment by mantis-toboggan-md** [comment]
I don't see `rke-profile-permissive-1.5` as an option here; there's `rke-profile-permissive` using the `rke-cis-1.5-permissive` benchmarkVersion and `rke-profile-permissive-1.6` using the `rke-cis-1.6-permissive benchmarkVersion`

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bb69b03`**

- Deploy a 1.15 cluster, deploy CIS v2 on the cluster
- Create scan.
- Scan profile dropdown has the following which is expected

<img width="415" alt="Screen Shot 2020-12-17 at 2 19 51 PM" src="https://user-images.githubusercontent.com/26032343/102550710-1d2f7c00-4073-11eb-9682-34e786e63ac9.png">
