### ISSUE TITLE
API Key Management

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#2087]

**Comment by sowmyav27** [comment]
@nwmac Do we have any PRs for this issue? And what has been fixed/changed ?

**Comment by sowmyav27** [comment]
PR: https://github.com/rancher/dashboard/pull/2214

**Comment by aaronRancher** [comment]
Validated with Rancher server `rancher\rancher:v2.5-head` `version 87006de`

Api keys are available in the account dropdown:
![Screen Shot 2021-02-24 at 10 37 27 AM](https://user-images.githubusercontent.com/57409052/109059100-13447d80-76a1-11eb-972a-8601597c79fb.png)
![Screen Shot 2021-02-24 at 10 37 46 AM](https://user-images.githubusercontent.com/57409052/109059493-8b12a800-76a1-11eb-964a-f946e96abdb2.png)

API Key creation is available with the same fields as Ember UI. The following fields have been tested and validated:
- Description
- Scope
- Expiration

![Screen Shot 2021-02-24 at 10 38 03 AM](https://user-images.githubusercontent.com/57409052/109059762-d5942480-76a1-11eb-9d38-dfe365d55f48.png)

API key is available and functional after create:
![Screen Shot 2021-02-24 at 12 57 41 PM](https://user-images.githubusercontent.com/57409052/109060521-b944b780-76a2-11eb-97ff-09c670847ede.png)

**Comment by aaronRancher** [comment]
Found an issue using this feature as a standard user.

Steps:
Log in as a standard user with access to a cluster.
Navigate to Dashboard
From the account dropdown, navigate to `Account & API Keys`

Result:
User is unable to see API key page load.
![Screen Shot 2021-02-24 at 2 58 33 PM](https://user-images.githubusercontent.com/57409052/109071465-fdd74f80-76b0-11eb-96ab-1ebe24c49587.png)

Reopening for a fix.

**Comment by nwmac** [comment]
Front end has been fixed so that if the user does not have permission, they don't see that functionality.

There is a backend issue that needs to be fixed so that standard users can manage API Keys - https://github.com/rancher/rancher/issues/31482

**Comment by deniseschannon** [comment]
This has been updated to use norman instead of Steve

**Comment by aaronRancher** [comment]
The change from Steve to Norman has been completed via https://github.com/rancher/dashboard/pull/2446

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5-head` `version 67228a3`

Standard users are able to create API keys.
