### ISSUE TITLE
Message to configure alerts in CIS v2 scans can be made better

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2088]
**On 2.5-head - commit id: `e2295c6 `**

- Deploy CIS v2 (alert: false) v 1.0.3
- create a scan CR cr
- Enable schedule config
- check Alert on Complete
- Message seen on UI:

<img width="1186" alt="Screen Shot 2020-12-15 at 10 27 09 AM" src="https://user-images.githubusercontent.com/26032343/102256997-fa5d6600-3ec0-11eb-8c76-272b1e3696bf.png">

Can we have a message which conveys: 
- Alerts/monitoring has to be configured before enabling alerts on CIS, else installing CIS v2 will fail
- where can we enable alerts for CIS ?

**Comment by mantis-toboggan-md** [comment]
Per conversation with @sowmyav27, alerting needs to be configured on the CIS install page (via values.yaml) before it will work for scans(this page). The CIS install page should have this warning about installing/configuring monitoring/alerting, and the CIS scan creation page should have a warning about enabling alerting via values.yaml.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bb69b03 `**

Readme file:
<img width="1345" alt="Screen Shot 2020-12-21 at 11 47 17 AM" src="https://user-images.githubusercontent.com/26032343/102816484-f0d17380-4382-11eb-989d-0f59876b35c9.png">

Creating a scan:
<img width="1284" alt="Screen Shot 2020-12-21 at 11 47 39 AM" src="https://user-images.githubusercontent.com/26032343/102816498-f5962780-4382-11eb-9ee3-f6f7eca40fc9.png">

Can we have ^^^ mentioned as "Alerting must be enabled within the CIS chart values.yaml"

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bb69b03`**

<img width="564" alt="Screen Shot 2020-12-21 at 12 45 34 PM" src="https://user-images.githubusercontent.com/26032343/102820646-760c5680-438a-11eb-99bc-feed1a382f34.png">

Closing the issue.
