### ISSUE TITLE
Istio Version 1.7.301 Undefined Error

### ISSUE THREAD

**Issue by westlywright** [rancher/dashboard#2094]
While developing rancher/dashboard#2093 I stumbled on an error in the Istio Chart UI. 

`TypeError: Cannot read property 'enabled' of undefined`

Looks like `tracing.enabled` is not defined for previous versions of the chart. I wasn't sure on the proper course of action because I dont know Istio too well and whether we should outright disable the param on that version or update the config if a user switches?

**Comment by brendarearden** [comment]
When we move charts from dev branch to be released in our main branch, it wont have the 1.7.301 version. I will go ahead and update the dev branch so that we can confirm and close

**Comment by bmdepesa** [comment]
Reproduced in `rancher/rancher:v2.5.4-rc6`

* Navigate to Dashboard > Apps
* Select Istio and change version to `1.7.301`
* See error in console and components tab doesn't load 

rancher/rancher:v2.5-head bd660e1
rancher/rancher:master-head 9c74195
* Navigate to Dashboard > Apps
* Select Istio and change version to `1.7.301`
* No error is seen and components tab loads properly with the correct components shown (No tracing)
