### ISSUE TITLE
Receiver creation issue

### ISSUE THREAD

**Issue by rtanmgm** [rancher/dashboard#2098]
When I go to create a receiver for email notification in new 2.5.3 UI getting this error.  
Cannot read property 'data' of undefined
<img width="920" alt="Screen Shot 2020-12-16 at 2 42 31 PM" src="https://user-images.githubusercontent.com/71028440/102415468-11798200-3fad-11eb-92d0-38b1a306a278.png">

**Comment by jiaqiluo** [comment]
Hi @rtanmgm This is a known [UI issue](https://github.com/rancher/dashboard/issues/1845) and the fix will be in the coming rancher:v2.5.4 release.

**Comment by rtanmgm** [comment]
Great. Thanks for the info. Much appreciated.
