### ISSUE TITLE
Istio Overview Polish

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#2104]
- [ ] Add explanation when the component is grayed out because it's not installed

**Comment by anupama2501** [comment]
Verified the issue on v2.5-23a29c306a1279cb1aa124f41992508ff60b508a-head and master-3ba112acba52c36b87c2bf88c40a64c693fba41d-head 

Steps perfomed:
Create a cluster and enable monitoring and istio [disabling the option for jaeger and Kiali]
Once the apps are installed successfully, verified the explanation for greyed out components:
On 2.5-8d5b3b8d933d04b04e0f0ae3a23d48d0a962c53f-head 
<img width="957" alt="Screen Shot 2021-01-21 at 2 06 36 PM" src="https://user-images.githubusercontent.com/38144301/105418391-ead4e980-5bf1-11eb-9073-bd47d9babfee.png">


on master:
<img width="964" alt="Screen Shot 2021-01-21 at 2 05 32 PM" src="https://user-images.githubusercontent.com/38144301/105418339-d1cc3880-5bf1-11eb-9aed-a31091dc08ac.png">
