### ISSUE TITLE
Longhorn Deployment Polishing

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#2107]
We will continue to use the question.yml to render the form. One thing is to review the order of the tabs so that it makes more sense for users. EX: The "Longhorn CSI Driver Settings" shows up before the current tab when the customization checkbox is checked in the Longhorn default settings tab.

**Comment by anupama2501** [comment]
Fix is working. On rancher v2.5.5, we have the following when longhorn is deployed, **other settings** and **Longhorn CSI Driver Settings**[when the customize default settings option is enabled in the longhorn default settings] is above **Longhorn Default Settings**:
**Previous Version when the order was not maintained**
Rancher | v2.5.5
User Interface | v2.5.4
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49


<img width="250" alt="Screen Shot 2021-02-10 at 4 17 26 PM" src="https://user-images.githubusercontent.com/38144301/107591230-06169180-6bbf-11eb-9f2f-65181e84c6ce.png">

On 2.5-head, other settings and Longhorn CSI Driver Settings are below the Longhorn Default Settings option.
**Version where the order is maintained with the fix**
Rancher | v2.5-761c805d8190692f2a29744cbd373cf14fd1c0e5-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher50


<img width="250" alt="Screen Shot 2021-02-10 at 4 44 46 PM" src="https://user-images.githubusercontent.com/38144301/107591377-60afed80-6bbf-11eb-83cd-2808be09e112.png">
