### ISSUE TITLE
Global Roles/Role Templates

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2111]
## Role Template Page for Auth/RBAC App

In Ember, this is located in the global nav bar as "Roles" divided into Global, Cluster, Project, but since k8s has their own native Roles/Cluster Roles concepts, we want it to be 1 type called "Role Templates" that will have 3 subtypes (Global, Cluster, Project/Namespace) that will map to GlobalRoles and RoleTemplates. 

Since there is no schema and we're using 1 page for multiple types, let's hide "Create from YAML", but still allow being able to edit from yaml. 

## k8s Role/ClusterRole

Add ability to add from form for the k8s native role/clusterRole resources, which should only need the ability to grant resources.

<img width="1277" alt="Screen Shot 2020-12-21 at 10 32 36 AM" src="https://user-images.githubusercontent.com/11410997/102810209-2a50b180-4378-11eb-83e1-cc870f5b9305.png">

**Comment by vincent99** [comment]
(Create from Yaml is no longer a top-level choice on any resource, you can either use Import in the header or go to regular create and then edit as yaml)

**Comment by slickwarren** [comment]
Tested on master-head (c81af53) and 2.5-head (761c805)
* creation of global/project/namespace/cluster roles works properly (through UI only) -- pass (no yaml option available)
<img width="799" alt="Screen Shot 2021-02-10 at 9 09 37 AM" src="https://user-images.githubusercontent.com/16691014/107560380-254afa00-6b92-11eb-8ff6-023a9a626121.png">

* `edit config` for a role - pass 
<img width="1519" alt="Screen Shot 2021-02-10 at 10 36 16 AM" src="https://user-images.githubusercontent.com/16691014/107559893-7efef480-6b91-11eb-8a4d-d0d57476f728.png">

* `edit as yaml` for a role - pass
  * api call made: `http://<IP_ADDRESS>/apis/management.cattle.io/v3/globalroles/roles-manage`
<img width="1532" alt="Screen Shot 2021-02-10 at 10 36 31 AM" src="https://user-images.githubusercontent.com/16691014/107560883-be7a1080-6b92-11eb-9d9f-e94e04af95b2.png">


* `edit config` then `edit as yaml` - **_Fail (no api call made)_**
<img width="1540" alt="Screen Shot 2021-02-10 at 10 36 03 AM" src="https://user-images.githubusercontent.com/16691014/107559894-7f978b00-6b91-11eb-9fba-196f87c8532d.png">

**Comment by slickwarren** [comment]
### User Flow Tests: (failures marked below)
* create global - cluster - project/namespace role -- ensure no `create as yaml` is available
* edit global - cluster - project/namespace role (both `edit as yaml` and `edit config` are available
  * check existing roles
  * check new roles
  * save change through `edit config` ui
  * save change through `edit yaml` -- **FAILED** `save` button appears to work, but when clicked does not actually save new info
  * save change through `edit config` -> `edit as yaml`  -- **FAILED** (also not populating yaml) (see last comment)
* view admin - cluster - project/namespace role
  * detail, config, and yaml (top right) are clickable and display correct information (view only) -- **FAILED** , `config` appears editable, but edits do not save to the role 
  
<img width="1017" alt="Screen Shot 2021-02-10 at 12 58 17 PM" src="https://user-images.githubusercontent.com/16691014/107571461-ca200400-6b9f-11eb-95c1-837885902d41.png">

* clone global | cluster | project/namespace role -- **FAILED** (`PUT 500 error` metadata.resourceVersion required)
  * <img width="995" alt="Screen Shot 2021-02-10 at 1 00 35 PM" src="https://user-images.githubusercontent.com/16691014/107571689-1a976180-6ba0-11eb-97da-ae68a349664b.png">
 
* Delete global | cluster | project/namespace role 


### Destructive Tests
* adding `verbs` past user's window obstructs view of dropdown until a scroll occurrs

<img width="219" alt="Screen Shot 2021-02-10 at 1 25 38 PM" src="https://user-images.githubusercontent.com/16691014/107576077-89c38480-6ba5-11eb-8960-3b17542d2dc6.png">

* Clicking previously selected items (highlighted) does nothing (sort of expected to remove, maybe?)
<img width="207" alt="Screen Shot 2021-02-10 at 1 23 58 PM" src="https://user-images.githubusercontent.com/16691014/107575992-6ac4f280-6ba5-11eb-999d-cc23d057cde9.png">

* adding empty `verbs` persist on creating/editing the role (would expect empty verbs to be removed)
<img width="1458" alt="Screen Shot 2021-02-10 at 1 37 23 PM" src="https://user-images.githubusercontent.com/16691014/107576224-b37cab80-6ba5-11eb-9aab-23e40553daaf.png">

**Comment by codyrancher** [comment]
@slickwarren I've opened a pr that will account for the failed tests you created.

I think the first two destructive tests are generic and I think we should open issues specifically to improve the Select component.

The third test I think should be opened as a separate issue as a bug since I don't think it should hold up this feature but I have a question. Are you suggesting we trim custom verbs and if they're empty we remove them? How are you creating the empty verbs?

**Comment by slickwarren** [comment]
Ok, I will open new tickets for these.  For the 3rd test, I created them by clicking the `add resource` button multiple times without entering any information to that new field

**Comment by slickwarren** [comment]
reopening, unable to create role template
<img width="1788" alt="Screen Shot 2021-02-25 at 2 18 41 PM" src="https://user-images.githubusercontent.com/16691014/109227161-bb774680-7774-11eb-805c-eaae3df2b8e8.png">

**Comment by deniseschannon** [comment]
Based on where we are for v2.5.6, let's hide these net new pages for v2.5.6 and we'll fix it for v2.5.7

**Comment by deniseschannon** [comment]
@slickwarren  After validating that this create page is hidden, can you move this issue back To Triage with the 2.5.7 milestone

**Comment by slickwarren** [comment]
Role Templates/global roles no longer show on 2.5-head (67228a3), moving back to triage for 2.5.7
<img width="245" alt="Screen Shot 2021-02-26 at 12 16 56 PM" src="https://user-images.githubusercontent.com/16691014/109350608-9e9e4a00-782c-11eb-8af2-f849bcfd11a2.png">

**Comment by richard-cox** [comment]
After discussing with Neil, Vince and Cody the Role Template resource list in the Cluster Explorer has been moved to the User and Authentication section and split into Global/Cluster/Project as per the Ember UI. This was completed as part of #2579 / #2656.

The same create/edit/view/detail components have been used to create the native k8s RBAC Role and Cluster Role resources as part of #2663 / #2664.

Closing this issue in favour of the new #2579 and #2663.
