### ISSUE TITLE
AD, OpenLDAP and FreeIPA Auth Providers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2114]
Courtesy of research done by @mantis-toboggan-md in rancher/dashboard#794 
#### (FreeIPA, OpenLDAP, Active Directory)
All LDAP types and Active Directory feature the same set of fields and can share a component with the following content

| Label | Component | Required? | Default |
|-------|------------|----|---|
| Hostname/IP |  LabeledInput | yes |   |
| Server Connection Timeout  | UnitInput (milliseconds)  | yes |   |
| Port | LabeledInput (integer) | yes | 389 / 636 for TLS|
| TLS | Checkbox | no | no (unchecked) |
| CA crt\* | LabeledInput (multiline) | yes |   |
| Service Account Distinguished Name\** | LabeledInput | yes |   |
| Service Account Password\** | LabeledInput (hidden text) | yes |   |
| User Search Base |  LabeledInput | yes |   |
| Group Search Base | LabeledInput | no |    |

\* only show if TLS=true
\** The Ember UI has an explanation above these fields: 
> Rancher needs a service account that has (read-only) access to all of the domains that will be able to login, so that we can determine what groups a user is a member of when they make a request with an API key.

In addition to these mostly-required fields, there's a section for customizing the schema if the LDAP server in question is non-standard. These fields can all use a LabeledInput
##### Users
| Label | Default | AD default |
|-----|-----|----|
| Object Class | inetOrgPerson | person |
|Username Attribute | cn | name | 
| Login Attribute | uid | sAMAccountName | 
| User Member Attribute | memberOf |   | 
| Search Attribute | uid|sn|givenName | sAMAccountName|sn|givenName | 
| Search Filter |   |   | 
| User Enabled Attribute  |   | userAccountControl |
| Disabled Status Bitmask |   | 2 |

##### Groups
| Label | Default | AD default |
|-----|-----|----|
| Object Class | groupOfNames | group |
| Name Attribute | cn | name |
| Group Member User Attribute | entryDN | distinguishedName |
| Search Attribute | cn | sAMAccountName |
| Search Filter |   |   |
| Group Member Mapping Attribute | member | member |
| Group DN Attribute | entryDN | distinguishedName |

Additionally, groups includes `Nested Group Membership` with two options: 
  *  "Search only direct group memberships" 
  *  "Search direct and nested group memberships"

View of Required Fields based on ember UI

<img width="1275" alt="Screen Shot 2020-07-14 at 4 22 44 PM" src="https://user-images.githubusercontent.com/11410997/87485704-45134300-c5ee-11ea-9d40-a7808867d490.png">

**Comment by anupama2501** [comment]
https://github.com/rancher/dashboard/issues/2254
https://github.com/rancher/dashboard/issues/2253

**Comment by anupama2501** [comment]
Rancher | v2.5-87006de30625c046523a329b03ea2580db35fb57-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher52

Verified scenarios on AD, FreeIPA and OpenLDAP:

Steps verified:

- On the dashboard, enable AD/FreeIPA/OpenLDAP by providing the required details - PASS
- Provide incorrect username and password, the auth errors out - PASS
- enable all user access from the dashboard and verify all users with access are allowed - PASS
- enable cluster members, projects users  - Login verification PASS
- enable restricted access - PASS [if the user is logged in and the access is removed, they are not kicked out of the session]
- verify restricted user access for a user without access - PASS
- Add auth before upgrade, upgrade the build and the dashboard shows AD/OpenLDAP/FreeIPA active with auth providers - PASS
- Upgrade build to 2.5-head and add AD/OpenLDAP/FreeIPA auth in the auth providers from the dashboard - failed 
- Login as standard user - Pass
- Verify login as a restricted user after upgrade and the login has failed - PAS

**Comment by anupama2501** [comment]
Closing this ticket, as the bugs are being addressed in separate tickets
