### ISSUE TITLE
SAML Auth Providers - Ping, Keycloak, ADFS, Okta, Shibboleth

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2115]
Research courtesy of @mantis-toboggan-md in rancher/dashboard#794

#### (Ping, KeyCloak, AD FS, Okta, Shibboleth‡)

These types have some individualized configuration required within the SAML client, but all require the following inputs on the Rancher UI side
| Label | Component | Required? | Default |
|-------|------------|----|---|
| Display Name Field | LabeledInput | Yes | |
| User Name Field | LabeledInput | Yes | |
| UID Field| LabeledInput | Yes | | 
| Groups Field | LabeledInput | Yes | | 
| Rancher API Host | LabeledInput | Yes | \<your Rancher API url\> |
| Private Key | Multiline Input with Paste-from-file | Yes | |
| CA crt | Multiline Input with Paste-from-file | Yes | |
| Metadata XML | Multiline Input with Paste-from-file | Yes | |

‡ Shibboleth can be configured with an OpenLDAP backend, and if so, should also show the LDAP-type inputs. I would probably hide that section by default and include: 

| Label | Component | Required? | Default |
|-------|------------|----|---|
| OpenLDAP backend? | Checkbox | No | No |

**Comment by izaac** [comment]
Opened a couple issues around SAML. This first is blocking around 70% of the QA regression coverage:

https://github.com/rancher/dashboard/issues/2273

Others:

https://github.com/rancher/dashboard/issues/2274
https://github.com/rancher/dashboard/issues/2276

**Comment by izaac** [comment]
Rancher version v2.5-head (02/24/2021) 30e53bd
Rancher version master-head (02/24/2021) 465bb3b

P1 tests done using ADFS.

**Comment by izaac** [comment]
Some improvements are being worked on and the Authentication Providers is not available on Rancher `master-head (03/10/2021)`  _eda2a07_ Reopening to reflect this.

**Comment by sowmyav27** [comment]
@izaac Can you check on 2.5-head now, the Auth should be available

**Comment by izaac** [comment]
Rancher version `v2.5-head (03/15/2021)` _38649e2_

P1 tests using PingFederate except groups (see: https://github.com/rancher/rancher/issues/31519)

**Comment by izaac** [comment]
Rancher version `v2.5-head (03/15/2021)` _38649e2_
P1 tests using Keycloak

**Comment by izaac** [comment]
Rancher version `v2.5-head (03/15/2021)` _38649e2_
P1 Site Access tests using Okta

Ember UI has this issue: https://github.com/rancher/rancher/issues/30401#issuecomment-790153866
This groups dropdown worked with the Dashboard UI.

**Comment by izaac** [comment]
Rancher version `v2.5-head (03/15/2021)` _38649e2_
P1 Site Access tests using Shibboleth.

I opened separate UI issues for Shibboleth 
- #2545
- #2546 
- #2547 
- #2548
