### ISSUE TITLE
AzureAD Auth Provider

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2117]

**Comment by codyrancher** [comment]
@qa I've only verified this using the Standard endpoints. I think it would be good to exercise the other two endpoints.

**Comment by sowmyav27** [comment]
Reopening for a backport PR for [this](https://github.com/rancher/dashboard/pull/2240#issuecomment-777074915) to 2.5.

**Comment by sowmyav27** [comment]
PR for 2.5 - https://github.com/rancher/rancher/pull/31348

**Comment by sowmyav27** [comment]
**Verified on 2.5-head commit if: `a85f4d1 `**

- Enabling Standard option - by giving in Tenant ID, ApplicationID and Application secret works. 
- Adding of `Configure who should be able to login and use Rancher` members in dropdown works. 
- Issues with `Configure who should be able to login and use Rancher`  section - logged - https://github.com/rancher/dashboard/issues/2384
- Enabling Azure AD with Custom Endpoint fails - https://github.com/rancher/dashboard/issues/2385
