### ISSUE TITLE
Github Authentication Provider 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2118]

**Comment by anupama2501** [comment]
**Rancher version:**
Rancher | v2.5-be72f967248a92190f7ed755fce7b9e36800c115-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49


**Steps verified:**

1. On the dashboard, enable github by providing the client ID and secret, github shows active [logout and login]- **PASS**
2. Provide incorrect client ID and secret, the auth errors out - **PASS**
3. Provide incorrect secret, the auth errors out - https://github.com/rancher/rancher/issues/30730
4. enable all user access from the dashboard and verify all users with access are allowed - **PASS**
5. enable cluster members, projects users https://github.com/rancher/rancher/issues/30754 and authorized users - **Login verification PASS** 
6. enable restricted access - **PASS** [if the user is logged in and the access is removed, they are not kicked out of the session]
7. verify restricted user access for a user without access - **PASS** [user is not displayed with any error but they are not allowed in]

**Upgrade:**

1. Add github auth before upgarde, upgrade the build and the dashboard shows github active with auth providers - **PASS**
2. Upgrade build to 2.5-head and add github auth in the auth providers from the dashboard - **PASS**
3. Login as standard user - **PASS**
4. Verify login as a restricted user after upgrade and the login has failed - **PASS**
