### ISSUE TITLE
No option to add config into spec when creating service

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#213]
I should be able to run a service with a particular config. There is currently no option to do this in the dashboard.

The request body for it looks like:

`{"kind":"Service","apiVersion":"rio.cattle.io/v1","metadata":{"generateName":"dazzling-keldysh-v0","namespace":"default","creationTimestamp":null},"spec":{"image":"nginx","ports":[{"port":80,"targetPort":80}],"configs":[{"target":"/usr/share/nginx/html/index.html","name":"fooconf","key":"answers.yaml"}],"version":"v0","app":"dazzling-keldysh"},"status":{}}`

And with the above, it should create an nginx service whose endpoint produces whatever value is in the `answers.yaml` key from the `fooconf` configmap.

**Comment by nwmac** [comment]
Rio is no longer supported. If this is a general Rancher dashboard issue, please feel free to re-open with additional information.
