### ISSUE TITLE
Logging chart - LogDNA hostname field should be mandatory. Output and ClusterOutput

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2133]
The hostname field is mandatory. But this is not required by the UI to create it.

https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/logdna/

The hostname should also have the required indicator (red asterisk) 

Create an output or clusteroutput using LogDNA, and do not set the hostname.
User is able to create it with an empty value.

<img width="607" alt="Screen Shot 2020-12-22 at 11 34 28 AM" src="https://user-images.githubusercontent.com/27659/102921790-360ca880-444a-11eb-9888-e8dddce30c5c.png">

rancher/dashboard#2074

**Comment by sadiapoddar** [comment]
Accidentally reponed it, closing it back
