### ISSUE TITLE
Move Cluster/Cluster Groups from CD/Fleet to "Cluster Management" app

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2135]
**Cluster Management - Global App in Navigation**
Group apps to cluster apps and global apps

**Side Bar for Cluster Management**

Overview (Tree Map/World)
Clusters (Moved from Fleet) → Create Cluster
Cluster Groups (Moved from Fleet) → Create Group
Credentials
Cluster Drivers
Node Drivers

**Create Cluster Page**
- [ ] Separate Create Cluster vs. Register Cluster buttons

- [ ] Create Cluster Screen Options
Cluster Templates
Custom
Node Driver
Hosted K8S Drivers

**Register Cluster Page**
- [ ] Register Cluster Screen Options

EKS, AKS, GKE, Other Cluster

**Comment by gaktive** [comment]
This may have been replaced some additional work in this space. Need to review after 2.6.0

**Comment by catherineluse** [comment]
Closing this issue as outdated - it has been almost two years since the issue was opened, and the UI has gone in a different direction.
