### ISSUE TITLE
Login UX and User Preferences

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2136]
**Different users/use cases:**

- First Time Login   
- Admin of only local Cluster
- Admin of Multiple Clusters
- User of Single Downstream Cluster (No access to local cluster)
- User of Multiple Downstream Clusters
- User of no clusters

**UX Flow:**
- If you have access to 0 or multiple clusters, it'll go to the cluster list view.
- If you have access to only 1 cluster, it'll go to the individual cluster dashboard

User Preferences
Default is "Automatic"

- Ability to select Automatic, cluster list view, last used cluster, a specific cluster

**What's New Page**
- Add What's new page for release notes, etc.

**Comment by gaktive** [comment]
There is a newer ticket that replaces this.

**Comment by mantis-toboggan-md** [comment]
Tracked by rancher/dashboard#2800

**Comment by gaktive** [comment]
We could close this as a duplicate, unless there's something here that isn't noted in the new tracked item. @nwmac are we covered?

**Comment by nwmac** [comment]
Yes, I think so - lets close this @gaktive
