### ISSUE TITLE
Can't see the plugins in the marketplace

### ISSUE THREAD

**Issue by smurphy79** [rancher/dashboard#2141]
Hello, 

I have added this url in the repository to add stable to the marketplace in the Rancher UI. It shows active, but I can't see any plugins:

![image](https://user-images.githubusercontent.com/35345739/103231397-e9ffaf00-48f4-11eb-8e34-fc47c80de241.png)

I uploaded a screenshot, but here is the url: 

https://charts.helm.sh/stable

Is there something I need to do to get these plugins to show up, we are wanting the nfs client provisioning that falls under the stable repo.

I'm using Rancher 2.5.1

Thanks,
Steve

**Comment by vincent99** [comment]
Deprecated charts, including [nfs-client-provisioner](https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner#deprecation-notice) are hidden from the list by default because nobody is supporting them anymore.

You can add `?hidden` to the address bar of your browser while looking at the list of charts to show all.

**Comment by smurphy79** [comment]
Hi Vincent,

Sure do appreciate the feedback. So here is what I have put into the url to see the hidden plugins: 
![image](https://user-images.githubusercontent.com/35345739/103372252-ba84aa00-4a8e-11eb-9023-c2a9fa2546b1.png)

Does that look okay to you because I'm still not seeing the nfs client provisioner. Also, with this nfs client being depricated, is there something else we can use in place of it as it would come in very handy.

**Comment by smurphy79** [comment]
Okay, so I figured it out and can see everything. However, I do not see the nfs client-client-provisioner, should it still be showing?

Here is what I put into the url:
![image](https://user-images.githubusercontent.com/35345739/103372480-6201dc80-4a8f-11eb-9a01-678df89342ef.png)


Thanks!
Steve

**Comment by vincent99** [comment]
sorry I forgot there's actually 2 separate flags... `hidden` for things that we don't normally want to show (`*-crd`, `fleet-agent`, etc) and `deprecated` for things marked deprecated.

**Comment by deniseschannon** [comment]
@smurphy79 It seems like your issue has been resolved and I will close this issue. If you have any more questions, please open a new issue.

**Comment by smurphy79** [comment]
Thank you!
