### ISSUE TITLE
ClusterFlow and ClusterOutputs list views have namespace field which is redundant. 

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/dashboard#2146]
On master-head, 5da52c0

Currently, users don't have the option to pick namespace during creating Clusterflow and ClusterOutput
The ClusterFlow and  ClusterOutput get created automatically in the "cattle-logging-system".  
The namespace field for all the clusteroutput and clusterflow always will be the same. It's cleaner if we remove the namespace field from the list view. 

<img width="1611" alt="Screen Shot 2020-12-29 at 2 48 03 PM" src="https://user-images.githubusercontent.com/72409237/103318968-f82cf880-49e4-11eb-8e4a-45777c07cf26.png">
<img width="1618" alt="Screen Shot 2020-12-29 at 2 48 19 PM" src="https://user-images.githubusercontent.com/72409237/103318973-fe22d980-49e4-11eb-9f7d-8d3a23afa102.png">

**Comment by deniseschannon** [comment]
This is a way to easily debug if the clusterflow/clusteroutput is in the correct namespace, so we will leave the namespace in the list view.

**Comment by sadiapoddar** [comment]
Verified, 2.5-head 6c03627, the namespace fields were not removed as it's designed.
