### ISSUE TITLE
dashboard/fail-whale

### ISSUE THREAD

**Issue by Csirme** [rancher/dashboard#2151]
Rancher Version:V2.5.3

Rancher Log:
upgradeaware.go:312] Proxy upgrade error: invalid upgrade response: status code 200

HTTP Error 500: Internal Server Error
from /k8s/clusters/c-4fltp/v1/schemas
Reload
![image](https://user-images.githubusercontent.com/16202890/103392723-3d266b80-4b5a-11eb-904e-983c1ff9431f.png)

**Comment by aaronRancher** [comment]
This change is closely related to this issue: https://github.com/rancher/dashboard/issues/1991
This issue is waiting on a fix for a more detailed error message.

**Comment by lvuch** [comment]
It seems @vincent99's comment in #1991 would indicate that we can't pull something more detailed

**Comment by aaronRancher** [comment]
The backend can return a more descriptive error.
Will track the backend change here: https://github.com/rancher/rancher/issues/32139
Closing issue.
