### ISSUE TITLE
Explorer view doesn't list the existing pv with access mode ReadWriteMany  to pick from during creating a new deployment

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/dashboard#2155]
master-head, 44846bf
Repro steps
1. Created a persistent volume by enabling  - ReadWriteMany
<img width="1483" alt="Screen Shot 2021-01-04 at 12 49 08 PM" src="https://user-images.githubusercontent.com/72409237/103578385-50537700-4e8b-11eb-9ed5-325554a16b95.png">

2. Attached the volume to a deployment
3. Try to create a new deployment and select "add volume" --> "persistentVolumeClaim"     It shows no volume is available to pick form

<img width="1444" alt="Screen Shot 2021-01-04 at 12 50 54 PM" src="https://user-images.githubusercontent.com/72409237/103578532-97416c80-4e8b-11eb-9b1c-69acbe8e79ed.png">

Addition information can be helpful.
When we use Amber UI, during creating a new deployment, if users select "add volume" --> "use an existing persistent volume claim",  UI list the existing volume name correctly.

<img width="1021" alt="Screen Shot 2021-01-04 at 12 54 54 PM" src="https://user-images.githubusercontent.com/72409237/103578883-32d2dd00-4e8c-11eb-9e20-ce603e29234c.png">

Expected: Explorer UI should list the existing vp (ReadWriteMany) during creating a new deployment.

**Comment by gaktive** [comment]
PR https://github.com/rancher/dashboard/pull/2290 should address this.

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, 761c805

1. created a few persistent volumes by enabling many read/write
2. Attached/mount the volume with the workload
3. From the explorer view, during creating a deployment for adding storage selected "Presistentant Volume"
4. Verified that explorer view lists the existing volume in the drop-down
5. Picked one of the existing volumes and created a "node port" type service
6. Worked load creation was successful
7. Access the PV using "execute shell" from one of the pods, created some files with content
8. Access from another pod that is sharing the same PV and verified the PV content has the same number of files and file contents are consistent across the pods

Veristent volume
<img width="1241" alt="Screen Shot 2021-02-12 at 10 24 42 AM" src="https://user-images.githubusercontent.com/72409237/107807374-e1d0c700-6d1c-11eb-90cf-f4679166d0eb.png">

Explorer view add persistent vol

<img width="1292" alt="Screen Shot 2021-02-12 at 10 06 25 AM" src="https://user-images.githubusercontent.com/72409237/107807042-72f36e00-6d1c-11eb-9f03-f3f9737d6ad2.png">

workload created with myvol2
<img width="483" alt="Screen Shot 2021-02-12 at 10 28 12 AM" src="https://user-images.githubusercontent.com/72409237/107807515-19d80a00-6d1d-11eb-8a7c-73ec451ad044.png">
