### ISSUE TITLE
Embed from Ember: Etcd Snapshots - RKE1

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2160]

**Comment by gaktive** [comment]
This would be part of the Ember migration, currently listed as an Embed

**Comment by deniseschannon** [comment]
In a cluster, go to Tools and then it's one of the options. It lists all the snapshots available for the cluster.

**Comment by vincent99** [comment]
Snapshotting rke1 was reimplemented natively instead of iframing.

**Comment by anupama2501** [comment]
@vincent99 can you let me know if this is implemented as a new feature in the dashboard for rke1 clusters and that any additional information is needed for the scope of testing?

**Comment by vincent99** [comment]
It is a new (vue) UI calling existing feature/API calls for rke1.  Iframing the ember page didn't really make sense because it's just one of the many tabs for the cluster and we don't have any partial pages iframed.

**Comment by anupama2501** [comment]
Verified on master-head 5715b8a

1. Created an rke1 node drver EC2 cluster from cluster explorer - 3 worker, 1 etcd, 1 cp
2. Once the cluster is active from cluster management --> cluster --> Snapshots --> created a snapshot and verified the call made was through v3 and the snapshot is saved on the etcd node at the path --> /opt/rke/etcd-snapshots
```
Request URL: https://**/v3/clusters/c-hlc57?action=backupEtcd
Request Method: POST
Status Code: 200 OK
```


3. Created another snapshot and restored the cluster from this snapshot --> verified the cluster went from error --> updating --> active[same behavior on the ember UI]
4. Deleted the snapshot and verified the snapshot was removed from the path mentioned in step2 and the call was through v3 API

**Comment by anupama2501** [comment]
Hi @vincent99  can we add the `snapshot now`  option in the cluster ellipsis as we have on the ember UI as well from the cluster management page?

**vue UI**

<img width="189" alt="Screen Shot 2021-06-14 at 4 19 30 PM" src="https://user-images.githubusercontent.com/38144301/121970956-8a734f80-cd2c-11eb-8a35-707ecaa76500.png">

**ember UI reference**

<img width="189" alt="Screen Shot 2021-06-14 at 4 21 56 PM" src="https://user-images.githubusercontent.com/38144301/121971013-a840b480-cd2c-11eb-9bf1-16fc835a11cd.png">

**Comment by anupama2501** [comment]
Re-opening for the above comment:
`snapshot now `, `Restore Snapshot`, `Rotate Certificates` option in the cluster ellipsis should are to be added as we have on the ember UI as well from the cluster management page in the cluster ellipsis?

**Comment by vincent99** [comment]
Added "Take Snapshot" to the cluster.  Restore doesn't make sense to offer because the modal you get doesn't offer a choice of which backup you want to restore; you will need to go into the cluster to pick a backup to restore.

Rotate certs, Rotate encryption keys, and save as RKE template were added separately.

**Comment by anupama2501** [comment]
Rancher master-head d44698d

- Verified the `Take Snapshot` option is available for the users on the cluster management page of the cluster's ellipsis and when the Snapshot is taken users are displayed with a message `Snapshot Started A snapshot has been requested for au-rke2`
