### ISSUE TITLE
Cluster Provisioning: Create v2 Cloud Credentials & Node Pools - Azure

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2163]
Tied to v2 work with @vincent99. This could be hopefully easily combined with work tied to RKE2 node pools though if that's not the case, then we can split that into another ticket.

**Comment by thehejik** [comment]
**Test report:**
This works correctly and it corresponds to the mockups visible here https://github.com/rancher/dashboard/pull/3151

I was able provision several RKE2 clusters within https://github.com/rancher/dashboard/issues/2166 (with ~ default values)

Close.
