### ISSUE TITLE
Cluster Provisioning using Node Provisioning - DigitalOcean

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2164]

**Comment by izaac** [comment]
The scope of this epic includes both RKE1 and RKE2?

**Comment by izaac** [comment]
Single and multi-node scenarios were covered in the following issues:

RKE2 DO  https://github.com/rancher/rancher/issues/32543
RKE1 DO  https://github.com/rancher/dashboard/issues/2773

**Comment by izaac** [comment]
Closing as edit was tested already for RKE1 and scaling up/down of nodepools was also covered.
