### ISSUE TITLE
How to deploy on nginx?

### ISSUE THREAD

**Issue by berlinsaint** [rancher/dashboard#2171]
i want to use nginx to serve the  yarn build dist. but there was no documention about that , how to deploy the dashboard standalone.

is there a demo conf to serve the dashboard on a nginx container, without rancher server.

**Comment by vincent99** [comment]
Dashboard uses APIs that are part of rancher server and does not just work against a random k8s cluster.

The output of `yarn build` is static files that you can just host on something and tell Rancher that's where it should load the dashboard from.  This is what the 'build-hosted' script is, which is in the readme:

```
./scripts/build-hosted # for hosting on a static file webserver and pointing Rancher's ui-dashboard-index at it
# Output in dist/)
```

You don't need any particularly special config of nginx to host static files.

**Comment by berlinsaint** [comment]
> Dashboard uses APIs that are part of rancher server and does not just work against a random k8s cluster.
> 
> The output of `yarn build` is static files that you can just host on something and tell Rancher that's where it should load the dashboard from. This is what the 'build-hosted' script is, which is in the readme:
> 
> ```
> ./scripts/build-hosted # for hosting on a static file webserver and pointing Rancher's ui-dashboard-index at it
> # Output in dist/)
> ```
> 
> You don't need any particularly special config of nginx to host static files.

i want to use only one dashboard to connect different rancher server, so i want to split them , and i want to use nginx to proxy different rancher api.. how about that....
