### ISSUE TITLE
No reconfirmation for deleting multiple resources 

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/dashboard#2175]
2.5-head, commit 6c03627

Currently, when users want to delete an important resource the UI asks users to enter the resource name to reconfirm the delete.  In the following case, the resource was a worker node. 
<img width="337" alt="Screen Shot 2021-01-06 at 4 43 02 PM" src="https://user-images.githubusercontent.com/72409237/103836880-280c7980-503f-11eb-85c5-3580173dacdc.png">

But if users select multiple of the same resource type to delete UI doesn't ask to enter the resources name to reconfirm
In this case, users selected two worker nodes to delete, but it's not required for the users to reenter the resource name but can just delete. 

<img width="850" alt="Screen Shot 2021-01-06 at 4 44 36 PM" src="https://user-images.githubusercontent.com/72409237/103836988-889bb680-503f-11eb-91a8-3edee4a322c6.png">

**Comment by gaktive** [comment]
Typo: "attempting" to be fixed by Vince.

**Comment by kravciak** [comment]
I tested the fix on 2.5-head (fa087c8), it works fine.
I tried it with multiple nodes / namespaces removal in dashboard UI.

![Screenshot from 2021-03-19 12-45-09](https://user-images.githubusercontent.com/538604/111776332-2b7b7700-88b2-11eb-9549-2952ad6fbf71.png)

I also tried to reproduce on v2.5.5, but it seems that confirmation dialog was not implemented at this version.
