### ISSUE TITLE
Need "template" option in service creation

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#218]
Should be a checkbox, probably next to "Pull Request Workflow" to set template builds. Example request with this option below:

`{"kind":"Service","apiVersion":"rio.cattle.io/v1","metadata":{"generateName":"cli-cd2-v0","namespace":"default","creationTimestamp":null},"spec":{"build":{"repo":"https://github.com/rancher-max/rio-demo","branch":"master","webhookSecretName":"githubtoken","pr":true},"ports":[{"port":8080,"targetPort":8080}],"template":true,"version":"v0","app":"cli-cd2"},"status":{}}`

**Comment by rancher-max** [comment]
Selecting "Pull Request Workflow" should also probably default to sending to `template: true`, otherwise creating a Pull Request will overwrite the currently deployed service and that is weird behavior. @tfiduccia What do you think from design perspective?

**Comment by rancher-max** [comment]
It looks like this has been added, pending Issue #243

**Comment by nwmac** [comment]
Rio is no longer supported. If this is a general Rancher dashboard issue, please feel free to re-open with additional information.
