### ISSUE TITLE
Empty values are not greyed out In Nodes --> Info tab

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2180]
**On 2.5-head - commit id: `be72f96`**

- Go to cluster explorer --> Nodes --> Info Tab
- Empty values are not greyed out

<img width="592" alt="Screen Shot 2021-01-07 at 9 17 00 PM" src="https://user-images.githubusercontent.com/26032343/103977252-b3643880-512d-11eb-9ebe-d766171ed049.png">

**Comment by deniseschannon** [comment]
@sowmyav27 What are you asking for? Clarity on when the value is empty?

Let's add  `-` when the value is empty.

**Comment by sowmyav27** [comment]
@deniseschannon As per the original issue/requirement here - https://github.com/rancher/dashboard/issues/2058

Info Tab -  gray out empty values --> is the requirement.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `be9683f `**

- Go to cluster explorer --> Nodes --> Info Tab
- Empty values have `-` a dash

<img width="584" alt="Screen Shot 2021-01-15 at 12 46 02 PM" src="https://user-images.githubusercontent.com/26032343/104776948-be235c80-572f-11eb-80dd-d532407b1e6a.png">
