### ISSUE TITLE
Reliable steps to break Apps page in 2.5.4

### ISSUE THREAD

**Issue by oskapt** [rancher/dashboard#2182]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. Perform a new install of Rancher 2.5.4 on K3s 1.19.4+k3s2
2. Go to the Apps page and add the Kyverno repo: https://kyverno.github.io/kyverno
3. Go back to the Charts tab

**Result:**

It sits on a Loading page and never recovers

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.4
- Installation option (single install/HA): single
- Kubernetes: 1.19.4+k3s2

**Comment by sowmyav27** [comment]
**Verified on `2.5.5-rc1`**

- Add repo with URLS: `https://github.com/banzaicloud/banzai-charts	` Branch: master and url: `https://git.rancher.io/charts`, branch: `master`
- Navigate to charts. Page loads.
- User is able to deploy charts

**Comment by jiaqiluo** [comment]
Verified on 2.5.5-rc3

- Add repo with URLS: https://github.com/banzaicloud/banzai-charts Branch: master and url: https://git.rancher.io/charts, branch: master
- Navigate to charts. Page loads.
- User is able to deploy charts
