### ISSUE TITLE
Header overflowed in every page in Safari

### ISSUE THREAD

**Issue by radeno** [rancher/dashboard#2183]
Hello, as my first ticket to Rancher Dashboard I want to say Thanks for the great work!

in Safari it makes header overflowed under bellow table.
The bug is made by setting `height: 100%`. for the CSS class `.actions-container` https://github.com/rancher/dashboard/blob/master/layouts/default.vue#L349

It should be fixed easily by changing `height: 100%` to `align-self: start` to get the same results for aligning to the top.

I am attaching screenshots. I have changed table opacity, to see the glitch better.
![Screen Shot 2021-01-09 at 14 39 51](https://user-images.githubusercontent.com/58521/104093251-90e73200-5289-11eb-9245-640c30be4856.png)

After change:
![Screen Shot 2021-01-09 at 14 42 14](https://user-images.githubusercontent.com/58521/104093255-9e9cb780-5289-11eb-9541-33317ce22934.png)

**Comment by lvuch** [comment]
@radeno thank you for filing your first issue :)

pr with resolution:
https://github.com/rancher/dashboard/pull/2202

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5.6-rc2`

Header no longer overflows:
![Screen Shot 2021-01-20 at 3 51 02 PM](https://user-images.githubusercontent.com/57409052/105250626-4ee6a780-5b37-11eb-9318-a59dff09fa43.png)
![Screen Shot 2021-01-20 at 3 40 15 PM](https://user-images.githubusercontent.com/57409052/105249723-cf0c0d80-5b35-11eb-9dde-65e5bff2f02d.png)
