### ISSUE TITLE
StorageClasses - Create/Edit/Detail

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2185]
Separate drivers needed for public clouds.
Ties into storage provisioners (EKS, Azure, GKE, Longhorn, etc.)
Shows things like Availability Zones, etc.
Doesn't talk to API so keys aren't needed.

Ember UI is straightforward enough that we could just port it over wholesale. Each provisioner option is unique so the work can be involved.

**Comment by vincent99** [comment]
This includes only the "supported" drivers.  See https://github.com/rancher/dashboard/issues/2284 for the others.

**Comment by sadiapoddar** [comment]
Verified this on 2.5-head, eb160e0
created by storage classes selecting the cloud provider
    -Amazon EBS
    -Vsphere 
    -Google persistent disk
    -Azure disk
    -Azure file 
    -Longhorn

    
<img width="692" alt="Screen Shot 2021-02-07 at 7 13 54 PM" src="https://user-images.githubusercontent.com/72409237/107171917-d118fd80-6978-11eb-8f81-ae70f28fb6b7.png">

**Comment by bmdepesa** [comment]
Let's add more details to this issue on what exactly was tested - end to end workflow, attaching PV from storage class to a workload, which fields were tested in the storage class.

**Comment by sadiapoddar** [comment]
Verified this on 2.5-head, eb160e0
vSpehre provider: 
1. Created a storage class selecting all the defaults
2. Binding with the storage class created a PVC  during creating a workload 
3. Verified that volume is accessible and file can be created in it

Azure provider:
1. Created a storage class selecting  Azure file 
2. Binding with the storage class created a PVC  by enabling "ManyReadWrite" during creating a workload 
3. Verified that volume is accessible and file can be created in the volume

EC2:
1. Created a storage class by selecting ec2 cluster by selecting external and used RancherK8SUnrestrictedCloudProviderRoleUS as AMI profile
2. Created a storage class type EBS
3. . During creating a deployment bound the storage class and created a new PVC 
4. Verified that volume was accessible from the pod and file can be created in the volume

**Comment by sadiapoddar** [comment]
on 2.5-head, 03b8153
EKS provider

1. Created an eks cluster
2. Created a storage class by selecting "EBS" disk type
3. During creating a deployment bound the storage class and created a new PVC 
4. Verified that volume was accessible from the pod and file can be created in the volume

**Comment by sadiapoddar** [comment]
on 2.5-head, 03b8153
Provider Azure:

1. Created a storage class by selecting "Azure Disk" as provisioner type and kind as "managed"
2. During creating a deployment bound the storage class and created a new PVC
3. Verified that volume was accessible from the pod and file can be created in the volume

**Comment by sadiapoddar** [comment]
on 2.5.6-rc5
Provider GKE 

1. Created a gke cluster
2. Created a storage class by selecting "google persistent" disk type
3. During creating a deployment bound the storage class and created a new PVC
4. Verified that volume was accessible from the pod and file can be created in the volume

**Comment by sadiapoddar** [comment]
on 2.5.6-rc5
Provider ec2 node driver
1 Created an ec2 cluster 
2.For EBS disk type created  a number of  storage classes by selecting all the possible Parameters( Volume Type, Filesystem Type, Availability Zone, Encryption, KMS Key ID for Encryption) 
and Customize (Reclaim Policy, Allow Volume Expansion, Mount Options, Volume Binding Mode)

3.Verified all the classes to make sure the selected options in the storage class were populated with the correction options during the edit.

**Comment by sowmyav27** [comment]
@anupama2501 Can you test Storage class for Longhorn as part of this issue?

**Comment by anupama2501** [comment]
Rancher | v2.5-a85f4d1f87feea0083ebf8ae517a140f39de7fbd-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher51

https://github.com/rancher/dashboard/issues/2429 
Storage class for longhorn:
Created a storage class, with longhorn as the provider. Creating a PV from this storage class has failed [workaround, removing the recurringJobs field from storage class parameters of longhorn]
Editing of storage class longhorn [only customize field] not editable from dashboard config but from edit yaml works.
Deletion of longhorn storage class - PASS

**Comment by sowmyav27** [comment]
**Verified end to end use case for these on 2.5-head - `30e53bd4`**
- Azure disk
- Azure File

Closing this issue. Tracking related bugs in separate issues
