### ISSUE TITLE
PersistentVolumes - Create/Edit/Detail

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2186]
Another direct port from the old UI.

**Comment by sadiapoddar** [comment]
Tested on 2.5-head, 03b8153, and vSphere Cloud provider

1. Creating a storage class using all the default options
2. Creating a new PVC during workload creation. there are a few differences between Ember UI and Explorer View 

Steps.
1. Cluster Explorer->Deployment->Create
2. Add "Storage" and select "create a new persistent volume"
3. Fill out the volume name, storage class, and capacity of the volume
4. Click create
During executing the above workflow notices the following difference between ember UI and explorer ui
   a. In Ember UI, the volume default access mode is "Single Read Write" in Explorer View there is no default mode is selected and also doesn't mark it as required.
  b. In Ember UI when you defined a PVC the name you gave, automatically populates as the volume name but in Explorer UI it remains as the random name 'vol0'.  if the user doesn't change the actual volume name, it fails to create the volume. 
Ember UI
<img width="731" alt="Screen Shot 2021-02-18 at 7 07 50 PM" src="https://user-images.githubusercontent.com/72409237/108453595-a30ca680-721f-11eb-886b-61add5900dbc.png">

<img width="829" alt="Screen Shot 2021-02-18 at 7 13 39 PM" src="https://user-images.githubusercontent.com/72409237/108453513-79537f80-721f-11eb-9376-715088556fe3.png">

Explorer UI
<img width="1329" alt="Screen Shot 2021-02-18 at 7 18 03 PM" src="https://user-images.githubusercontent.com/72409237/108453423-5759fd00-721f-11eb-942a-e5bdfd6c3774.png">

**Comment by sowmyav27** [comment]
@sadiapoddar Can we validate "Persistent Volumes" and not storage classes as part of this ticket?

**Comment by sowmyav27** [comment]
@anupama2501 Can you test Longhorn PV as part of this issue ?

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `30e53bd4`**

Verified PV for 
- GCE - end to end test case and other UI checks
- Azure filesystem  - end to end test case  and other UI checks
- Azure Disk - UI checks
- Amazon EBS - end to end test case and other UI checks

**Comment by anupama2501** [comment]
Rancher | v2.5-a85f4d1f87feea0083ebf8ae517a140f39de7fbd-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher51

Creation of persistent volumes on longhorn - failed ["driver" key is missing from the spec]
Attaching an existing persistent volume to a deployment - PASS
Editing the PV has the following issues: https://github.com/rancher/dashboard/issues/2424
