### ISSUE TITLE
HPA - Create/Edit/Detail

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2187]
Porting from the old UI should be OK

**Comment by sowmyav27** [comment]
**on 2.5-head commit id:`03b815317`**

- Create some deployments.
- Create a HPA, choose a deployment as target
- The HPA fails with error `The HPA controller was unable to get the target's current scale: no matches for kind "workload" in group ""`

Reopening the issue

**Comment by slickwarren** [comment]
the old UI has a % or `milliCPU` in `quantity`, but this is not in the new UI, so it is unclear to the user which field is which. Could that be added? 
<img width="1264" alt="Screen Shot 2021-02-25 at 8 41 33 AM" src="https://user-images.githubusercontent.com/16691014/109186053-6b34c000-7745-11eb-8331-219933c19224.png">
<img width="1319" alt="Screen Shot 2021-02-25 at 8 41 03 AM" src="https://user-images.githubusercontent.com/16691014/109186060-6bcd5680-7745-11eb-996a-181226c56826.png">
<img width="1378" alt="Screen Shot 2021-02-25 at 8 40 58 AM" src="https://user-images.githubusercontent.com/16691014/109186064-6c65ed00-7745-11eb-8444-1998d28783a7.png">

**Comment by slickwarren** [comment]
**compared to the old UI, here are the differences I found:** 
small typo on the `metric` screen for sources that are not of type `resource`:
<img width="340" alt="Screen Shot 2021-02-25 at 9 13 52 AM" src="https://user-images.githubusercontent.com/16691014/109191395-fcf2fc00-774a-11eb-8e74-cade0fde621d.png">

in the old UI, a warning is displayed for sources of type `pod` and `object`, but no warning is displayed in the new UI
<img width="826" alt="Screen Shot 2021-02-25 at 9 24 53 AM" src="https://user-images.githubusercontent.com/16691014/109191844-6a069180-774b-11eb-9ec9-d8cdba322675.png">
<img width="819" alt="Screen Shot 2021-02-25 at 9 24 26 AM" src="https://user-images.githubusercontent.com/16691014/109191846-6a9f2800-774b-11eb-8214-33bf5b95fef6.png">


missing metrics data on the overview page of HPAs (old UI has this under `workloads` column:
<img width="1113" alt="Screen Shot 2021-02-25 at 10 11 28 AM" src="https://user-images.githubusercontent.com/16691014/109197887-6c201e80-7752-11eb-9eff-877182ca43ed.png">
<img width="1527" alt="Screen Shot 2021-02-25 at 10 10 58 AM" src="https://user-images.githubusercontent.com/16691014/109197891-6cb8b500-7752-11eb-866b-5ebf2c8bba66.png">

and the details page of HPA (old UI does have current metric information): 
<img width="1353" alt="Screen Shot 2021-02-25 at 10 12 39 AM" src="https://user-images.githubusercontent.com/16691014/109197880-6a565b00-7752-11eb-9dd5-03df74340cc6.png">
<img width="1525" alt="Screen Shot 2021-02-25 at 10 12 22 AM" src="https://user-images.githubusercontent.com/16691014/109197885-6c201e80-7752-11eb-86f5-af9930437917.png">

**The below are improvement requests:** I can open separate tickets for these if devs think they are worth adding, as they are not requirements of this ticket
able to remove all metrics (defaults to 80% cpu): -- suggest requiring at least 1 metric field before user can save changes
![Screen Recording 2021-02-25 at 10 21 53 AM (1)](https://user-images.githubusercontent.com/16691014/109201574-da66e000-7756-11eb-89d1-3e87aea80894.gif)

able to select same resource type multiple times in UI (only first metric is applied to HPA) -- suggest warning user that only one type per source per hpa allowed / requiring user to remove duplicate types from metrics
<img width="1516" alt="Screen Shot 2021-02-25 at 10 39 15 AM" src="https://user-images.githubusercontent.com/16691014/109201806-1a2dc780-7757-11eb-99c5-4a7c8acdf240.png">
