### ISSUE TITLE
Selecting Pull Request Workflow does not create webhook

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#219]
Somewhat related to #218 

Should selecting "pull request workflow" when creating a service:
1. Expose a field to create a secret with a user-supplied Github Access Token, and then use that secret in the service creation Request? (`spec.build.webhookSecretName`)
2. Expose a field to select an existing secret to use in the service creation Request? 
3. Something different?

At minimum for this flow to work, user needs to be able to supply a secret that we pass in the request. The secret should contain `.data.accessToken`.

**Comment by vincent99** [comment]
The API is supposed to do this by using the github token authorizing the request to set the webhook and create a deploy key, but this isn't implemented yet.  You shouldn't have to manually define and pick secrets in the UI.

**Comment by nwmac** [comment]
Rio is no longer supported. If this is a general Rancher dashboard issue, please feel free to re-open with additional information.
