### ISSUE TITLE
[OIDC] Keycloak - Create / Edit / Detail Page

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#2191]
These requirements are for two new provider options to be added for auth:

1. A Keycloak OIDC provider

1. A generic OIDC provider

The priority is for Keycloak OIDC provider. Generic OIDC provider will not be released if there are issues with it. Time should not be spent correcting issues with the Generic portion of this issue. 

**Page Title:** Configure Keycloak OIDC **[Or]** Config OIDC

**Confirmed Fields:**
| Name      | Type |
| ----------- | ----------- |
| Client ID      | Text       |
| Client Secret   | Text        |
|Token Endpoint URL | Text |
|Authorization Endpoint URL | Text | 
|Certificate| Cert Field or Upload from File |  
|RedirectURL| Text | Default to: server-url from settings|

Backend Issue: https://github.com/rancher/rancher/issues/30280

**Comment by gaktive** [comment]
This will be mostly @codyrancher but @westlywright can assist based on his existing Ember attempt

**Comment by richard-cox** [comment]
Note - the frontend work has merged. The backend work is in https://github.com/rancher/rancher/pull/31572 and is still waiting to merge. I've been working from an image supplied by @brendarearden which should match the contents of that PR.

**Comment by izaac** [comment]
Rancher version `2.6 master-head (05/27/2021)` _bac4948_

![Screen Shot 2021-05-27 at 4 13 40 PM](https://user-images.githubusercontent.com/27659/119912633-bad78300-bf10-11eb-9179-e154ce647bce.png)

The Keycloak OIDC auth provider option is not visible in this build

**Comment by izaac** [comment]
Actually I will re-test this later on as the available builds are a bit old.

**Comment by cbron** [comment]
Should be available on master-62aef76....
@richard-cox can you check and see if you get it on master now

**Comment by izaac** [comment]
Rancher version `2.6 master-head (05/27/2021)` _62aef76_

Keycloak OIDC is available

![Screen Shot 2021-05-27 at 8 14 53 PM](https://user-images.githubusercontent.com/27659/119924329-398bea80-bf28-11eb-8b89-6ea45ad4a1ed.png)

**Comment by izaac** [comment]
We're missing here the secure http certificate ready keycloak to test the certificates field.
Most of the testing was done as part of https://github.com/rancher/rancher/issues/30280
Latest rancher build tested: `2.6 master-head (07/01/2021)` _c1151f6_

**Comment by izaac** [comment]
13.0.0 On Rancher version 2.6 master-head (07/14/2021) 8073489

I was able to make use of self signed certificates using the new Keycloak OIDC backend version. Completing the last UI fields checks for validation.

There are pending backend issues to be fixed for auth functionality that are being tracked separately.
