### ISSUE TITLE
Dashboard github auth is activated for incorrect credentials

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2197]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Rancher 2.5-head[v2.5-6c036279a26f1ffb8ae52276f43c722eb13ff460-head]

- in the local cluster explorer --> Rancher --> Auth Providers
- Click on Github --> edit config
- Provide correct client ID and incorrect client secret and click on enable
- Server authentication results in an error and if we click on the error button, we will be redirected to the AuthProviders page where it shows github Auth active.
- This is not the case if incorrect client ID is given where the user is taken to a 404 page if we click on the error button.
- The error button is switched back to save button after a few minutes in case of incorrect client secret.

**Result:**
The auth should be disabled as the authentication with github didn't succeed.

**Other details that may be helpful:**
<img width="1357" alt="Screen Shot 2021-01-07 at 4 41 11 PM" src="https://user-images.githubusercontent.com/38144301/103960639-76854b00-5107-11eb-8bec-cb9f321f46a8.png">
<img width="1240" alt="Screen Shot 2021-01-07 at 4 42 42 PM" src="https://user-images.githubusercontent.com/38144301/103960651-7c7b2c00-5107-11eb-8406-7825a0570100.png">
<img width="1284" alt="Screen Shot 2021-01-07 at 4 40 25 PM" src="https://user-images.githubusercontent.com/38144301/103960760-c401b800-5107-11eb-9188-5bf0fc4a2996.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Rancher | v2.5-6c036279a26f1ffb8ae52276f43c722eb13ff460-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

- Installation option (single install/HA): Single

**Comment by mantis-toboggan-md** [comment]
This should be fixed as of this PR https://github.com/rancher/dashboard/pull/2309 which has a bunch of small fixes to the edit/cancel buttons here. Clicking the error/save button shouldn't redirect to the auth providers page. When testing this i found it possible to edit the config without disabling the auth provider first so I left that functionality in the dashboard; if the initial popup fails on edit, github will still be enabled.

**Comment by anupama2501** [comment]
Verified on 
Rancher | v2.5-a420b5195dd1d0a23411b0aeb17713f291e90e10-head

Scenario1:
1. Enable github auth by providing client ID and secret
2. Edit config and change the secret to an incorrect one. User is displayed with error
<img width="1000" alt="Screen Shot 2021-03-09 at 10 00 35 AM" src="https://user-images.githubusercontent.com/38144301/110516430-6a454c00-80be-11eb-8105-d548d1941fd7.png">

github is active as the user wasn't allowed to save the config from the above step and users can login using the previously enabled.

Scenario2:
1. While enabling github auth provide correct client ID and an incorrect secret
2. Users are not allowed to enable the config and displayed the error:
<img width="1000" alt="Screen Shot 2021-03-09 at 10 00 35 AM" src="https://user-images.githubusercontent.com/38144301/110516430-6a454c00-80be-11eb-8105-d548d1941fd7.png">

github auth is not shown active in this case.
