### ISSUE TITLE
Selectors tab in services details page does not have a title row

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2201]
**On 2.5-head - commit id: `2ba49cb `**

- Go to dashboard --> Services 
- Create a Nodeport service
- Give in the selector values Key=value
- Deploy the service
- Click on the Nodeport to go into details page
- Go to selectors tab
- It does not have a title, to indicate it is a key and value pair.
<img width="530" alt="Screen Shot 2021-01-13 at 12 49 44 PM" src="https://user-images.githubusercontent.com/26032343/104509205-2fcba100-559e-11eb-94cd-2dd43e6e03dd.png">

**Comment by slickwarren** [comment]
The UI now shows a header for each tab on 2.5-head (05fbcbb) and master-head (d7203b4)
<img width="557" alt="Screen Shot 2021-02-16 at 3 49 21 PM" src="https://user-images.githubusercontent.com/16691014/108136262-9432c200-706e-11eb-97bd-0038dc703bb3.png">
