### ISSUE TITLE
Users list,create,view

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#2204]
https://xd.adobe.com/view/501c131e-6fab-48c0-86b6-bcf7bef497b9-054f/

**Comment by gaktive** [comment]
Pushing to 2.5.7 based on giving QA time to test everything else. Do not merge until 2.5.6 released.

**Comment by anupama2501** [comment]
v2.5-4e48b8a9fbedad498fa21fd00e6e426ab3e13770-head

Verified the following scenarios:
From explorer --> Users and Auth providers/ Users
Verified creation of standard, Administrator, User-base, Restricted Administrator users
Verified all the buttons in the create page
Verified Edit config/yaml by changing the values of the created users
Verified the details page of the users 
Deletion of all/some users
Verified Refresh Group memberships


Keeping this issue open for the related tickets mentioned above

**Comment by anupama2501** [comment]
Closing this issue as the issues are being tracked separately.
