### ISSUE TITLE
[CIS] Add remediation in UI

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#2207]
When a test fails/warn, the report contains a field called remediation. UI should also show the remediation text to explain to user that why it failed.

**Comment by slickwarren** [comment]
version: 2.5-head (8201e08)
* when running CIS tests, `warn` and `fail` tests now contain a `remediation` field
However, `pass` and `Notapplicable` also contain remediation in the UI. Is that the desired behavior?
<img width="999" alt="Screen Shot 2021-02-04 at 9 51 01 AM" src="https://user-images.githubusercontent.com/16691014/106934280-c76c6d00-66ce-11eb-8350-71acebad933a.png">

<img width="979" alt="Screen Shot 2021-02-04 at 9 53 18 AM" src="https://user-images.githubusercontent.com/16691014/106934329-d7844c80-66ce-11eb-9dd2-483c8551b636.png">

**Comment by mantis-toboggan-md** [comment]
Per offline convo with Rajashree, the remediation text should only be shown for fail/warn results. PR with this change is here: https://github.com/rancher/dashboard/pull/2297

**Comment by slickwarren** [comment]
veriified fixed on v2.5-head (8201e08) 
<img width="1319" alt="Screen Shot 2021-02-05 at 2 18 28 PM" src="https://user-images.githubusercontent.com/16691014/107095103-0f69bd80-67bd-11eb-9422-99e9132f35d6.png">
<img width="1484" alt="Screen Shot 2021-02-05 at 2 18 09 PM" src="https://user-images.githubusercontent.com/16691014/107095110-11338100-67bd-11eb-8bb6-62571fd5d6a0.png">
