### ISSUE TITLE
Istio dashboard: Uninstalling istio and re-installing istio missing the install into project option

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2222]
Rancher Version:
Rancher | v2.5-8d5b3b8d933d04b04e0f0ae3a23d48d0a962c53f-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

Istio version: 1.7.600

Steps:
Create a cluster and enable monitoring and istio [install into project - system]
Once the apps are installed successfully, deploy a few workloads.
Uninstall the istio app and when we try to reinstall the app, we see that the project into which the app has to be installed is missing [installing in the system project without the install in project option]
<img width="1596" alt="Screen Shot 2021-01-21 at 1 40 54 PM" src="https://user-images.githubusercontent.com/38144301/105416116-8bc1a580-5bee-11eb-935a-2d4bbe483742.png">

Install into project option for fresh installation:
<img width="1594" alt="Screen Shot 2021-01-21 at 1 40 40 PM" src="https://user-images.githubusercontent.com/38144301/105416138-90865980-5bee-11eb-8c38-f25bd9f9dff1.png">

Issue seen on v2.5-8d5b3b8d933d04b04e0f0ae3a23d48d0a962c53f-head and master-3ba112acba52c36b87c2bf88c40a64c693fba41d-head

**Comment by gaktive** [comment]
The project being missing indicates that Istio is already installed into that namespace, so we need to add information saying that it already exists so the user knows.

**Comment by slickwarren** [comment]
this happens for any app that is uninstalled. I tested with monitoring, longhorn, webhooks and all have this issue:
How to repro:
* go to install an app through apps and marketplace
* 
<img width="1573" alt="Screen Shot 2021-04-01 at 4 26 42 PM" src="https://user-images.githubusercontent.com/16691014/113363916-13bade80-9307-11eb-8020-3318689352e3.png">

* install the app
*  try to upgrade the app 
<img width="1537" alt="Screen Shot 2021-04-01 at 4 27 54 PM" src="https://user-images.githubusercontent.com/16691014/113363981-3a791500-9307-11eb-9e1b-da5f103af591.png">

* alternatively, uninstall the app then try and reinstall the app

The user should still have the option to select a project after uninstalling

So would this mean that something isn't being cleaned up on uninstall that should be?

**Comment by anupama2501** [comment]
@slickwarren the namespace into which the app is installed under the given project will not be cleaned up. Therefore, it installs in the same namespace every time we try to install it, after uninstalling the app. If we delete the namespace eg., for istio - istio-system under the projects before re-trying, the "install into project" option appears for the app:
<img width="1399" alt="Screen Shot 2021-04-01 at 5 24 21 PM" src="https://user-images.githubusercontent.com/38144301/113366801-1de0db00-930f-11eb-88bd-b58efd4b5fbc.png">

**Comment by vincent99** [comment]
It is not really "any" app, but apps that specify that they be installed into a particular namespace, which is mostly just our add-on charts.

Apps go into a namespace.  The project is a property of the namespace, not the app.  When you install an app you choose an existing or create a new namespace (unless the chart requires a particular one, which again ours almost all do).  When you are creating a namespace as part of installing an app, you can choose the project that namespace will be assigned to.

When you remove the app the namespace is not deleted (because we have no good idea if that namespace contains other stuff).

If you subsequently reinstall (or just upgrade without removing) that app, the namespace now already exists, so you do not get a choice of what project it should be in.

**Comment by anupama2501** [comment]
Verified on v2.5-41f173ae93c6692f44054fe0b02ce93bd3056a9f-head

Install istio from cluster explorer --> Apps and marketplace --> istio [default project]
Once istio is active, uninstall istio and when tried to install again, select project, warning is displayed 
<img width="200" alt="Screen Shot 2021-04-15 at 2 55 42 PM" src="https://user-images.githubusercontent.com/38144301/114943555-04558e00-9dfb-11eb-9d88-184a66ca17ea.png">

Remove namespace, cluster explorer --> Namespaces --> istio-system, warning is not shown
