### ISSUE TITLE
SAML Auth Keycloak - I can enable keycloak but if I log out and login again I'm getting an error

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2224]
Enabling Keycloak is working in this same setup using Ember UI.

I noticed that when enabling from Dashboard I click enable and I don't get the usual Pop Up we get in Ember UI to authenticate with a User to finish enabling the Auth. 

This also seems to create a principal which uid is invalid for the auth

`[ERROR] SAML: Failed getting user with error: can't find unique user for principal keycloak_user://testuser1@keycloak.com`

Steps.

- Follow the steps from the official Rancher docs  https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/keycloak/
- Enable the Keycloak Auth
- Notice there isn't a pop up appearing but the Keycloak auth is enabled.
- Logout
- Try logging with a valid Keycloak user 

![Screen Shot 2021-01-21 at 3 49 30 PM](https://user-images.githubusercontent.com/27659/105422617-43f84980-5c01-11eb-96ac-59bd3574cfd6.png)

Reference: https://github.com/rancher/dashboard/issues/2115
Rancher version `v2.5-head (01/21/2021)` _23a29c306_

**Comment by izaac** [comment]
Rancher `v2.5-head (02/01/2021)` _610920447_
I can login as the admin principal as well as other users with Keycloak
I opened a separate issue for the access control options https://github.com/rancher/dashboard/issues/2273

**Comment by gaktive** [comment]
@codyrancher @izaac since this does need some attention, what milestone do we need to put this since we shipped 2.5.6 in 2021?

**Comment by codyrancher** [comment]
We don't actually need to give this any attention. This was completed a long time ago but it got erroneously reopened and we only noticed now because I made sure all of our issues that were missing a project had the project added.
