### ISSUE TITLE
Authentication pages of Ping, Keycloak, ADFS, Okta, Shibboleth Rancher API Host field should default to Rancher URL

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2227]
Navigate to each of these Authentication pages in Dashboard
Observe the Rancher API Host text input is empty.

Expected: 

This field should default to the current Rancher host according to: https://github.com/rancher/dashboard/issues/2115
(Compare this with Ember UI It should match)

Example defaults for Keycloak

![Screen Shot 2021-01-21 at 3 20 32 PM](https://user-images.githubusercontent.com/27659/105424861-642a0780-5c05-11eb-89aa-3fa82eaa8b49.png)

Rancher version `v2.5-head (01/21/2021)` _23a29c306_

**Comment by gaktive** [comment]
Based on what's in Ember, we should pre-fill in Vue too. Then again, should the URL actually be hidden in both views?

**Comment by gaktive** [comment]
Need to figure out if "undefined" means something breaks. Checking with backend.

**Comment by izaac** [comment]
Rancher version `master-head (02/11/2021)` _98fe72a_

I see the Rancher URL getting set by default in the Rancher API Host field.
