### ISSUE TITLE
Monitoring - Confusing Default Route/Receiver UX

### ISSUE THREAD

**Issue by westlywright** [rancher/dashboard#2229]
Breakout: rancher/dashboard#1986

When a user enables monitoring a default `null` receiver and `root` route are created. The `null` receiver should be the users default/catch all receiver. The `root` route is a special route where every alert will pass through.

From a UX perspective its not very intuitive what these resources do and the null names/links are confusing.

**Comment by nwmac** [comment]
We'll look at this in 2.5.7 as part of the broader focus on monitoring. We need to agree how we want to display the null receiver (default) and root and how to provide some info to help understand their meaning.

**Comment by nwmac** [comment]
This is old and stale - closing for now as unlikely to be done.
