### ISSUE TITLE
SAML based auth enabled page - settings summary missing information and undefined server

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2230]
Rancher version `v2.5-head (01/21/2021)` _23a29c306_

Okta, Keycloak, Shibboleth, Ping, ADFS

These are missing some information in the summary page after enabling the auth.

![Screen Shot 2021-01-21 at 4 46 47 PM](https://user-images.githubusercontent.com/27659/105426437-5de95a80-5c08-11eb-8d42-3aef24ff5f61.png)

![Screen Shot 2021-01-21 at 4 46 54 PM](https://user-images.githubusercontent.com/27659/105426450-65106880-5c08-11eb-86e5-5619230ecaaf.png)

I also don't think we need `Server:` for these SAML auths, it's not set and is displayed as `undefined` in the settings summary.

Reference: https://github.com/rancher/dashboard/issues/2115

**Comment by nwmac** [comment]
We should ensure that we provide the same level of info as the ember UI, so:

- Fix the issue with the server showing as undefined
- Add the missing fields that are in the ember UI

**Comment by mantis-toboggan-md** [comment]
This is addressed in this pr (merged) rancher/dashboard#2244

**Comment by izaac** [comment]
Correct this was validated while submitting this other issue https://github.com/rancher/dashboard/issues/2274

Closing.
