### ISSUE TITLE
Unable to use the shell in Explorer with Safari

### ISSUE THREAD

**Issue by mguggi** [rancher/dashboard#2231]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Open the Cluster Explorer 
- Click on the shell button 

**Result:**

The shell window opens but the connection will not established. In the bottom I see disconnected und nothing happens. The Developers console shows no network related errors.

With Chrome the shell opens and I have a connection to the cluster.

**Environment information:**

Rancher version (rancher/rancher/rancher/serverimage tag or shown bottom left in the UI): 2.5.3
Installation option (single install/HA): HA

**Comment by vincent99** [comment]
Nevermind, the WebGL renderer just doesn't work in Safari so it needs to be disabled.

**Comment by mguggi** [comment]
> Is the SSL cert trusted or did you have to add an exception?

I added an exception

> Do "change events" work in the same browser? 

I don't know what you mean?

> Does the Cluster Manager shell work in the same browser?

Yes it works

> Nevermind, the WebGL renderer just doesn't work in Safari so it needs to be disabled.

When I enable the experimental feature _WebGL 2.0_ the connection works but the text will not displayed as expected. I see the cursor and it jumps when I typ but no text will be displayed in the shell window.

**Comment by vincent99** [comment]
You can turn it back off, the webgl renderer just needs to not be used in this case.  There's a change for it in my branch that will be merged soon and in the next 2.5 release.

(Adding an exception doesn't help for the problem I was talking about, the page would load and then websockets to the same domain would be rejected anyway.  But I don't think this applies to newer versions of Safari.

Change events are live updates of the UI when something happens from the server/cli/another window. It's just another use of websockets.)

**Comment by slickwarren** [comment]
verified on 
* safari verion 14.0.1
* rancher v2.5-head (ac48370)
<img width="1792" alt="Screen Shot 2021-01-26 at 1 26 15 PM" src="https://user-images.githubusercontent.com/16691014/105907659-154fe980-5fda-11eb-9585-c5ff763b3d00.png">
