### ISSUE TITLE
Unable to create a new Scan in CIS Benchmark app

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#2235]
**What kind of request is this (question/bug/enhancement/feature request): bug**

**Steps to reproduce (least amount of steps as possible):**
* Deploy `CIS Benchmark` in Apps & Marketplace v2 dashboard
* once deployed go to `CIS Benchmark`, select `Scans` and click `Create` button

**Result:**
After clicking the Create button the page is stuck in `Loading...` and become inactive.

There is an following error in Webdeveloper Console:
![csi_scan](https://user-images.githubusercontent.com/12828077/105506344-3fe42e80-5cca-11eb-83c4-d7b03e349ee7.png)

**Environment information**
- CSI Benchmark chart `1.0.300`
- Rancher version: v2.5.6-rc2
- Installation option (single install/HA): single/HA

**Comment by kravciak** [comment]
I can reproduce this bug on v2.5.6-rc2, it's a regression since it's not present in v2.5.5

**Comment by slickwarren** [comment]
able to successfully install cis-benchmark on 2.5-head (8201e08) and create scans
<img width="1523" alt="Screen Shot 2021-02-05 at 2 54 56 PM" src="https://user-images.githubusercontent.com/16691014/107097586-219a2a80-67c2-11eb-892c-6194746f36c1.png">
