### ISSUE TITLE
Hyperlink in the tool tip in Create Receiver is not obvious in "light" theme 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2249]
**On 2.5-head - commit id: `ac48370`**

- Install Monitoring v2 in dashboard. Go to Monitoring --> Receiver --> Create --> Slack
- Hyperlink in the tool tip in Create Receiver is not obvious in "light" theme 
<img width="1661" alt="Screen Shot 2021-01-26 at 5 42 22 PM" src="https://user-images.githubusercontent.com/26032343/105930860-10e9f780-5fff-11eb-8a8f-9482c2baf97d.png">
<img width="1644" alt="Screen Shot 2021-01-26 at 5 42 50 PM" src="https://user-images.githubusercontent.com/26032343/105930864-121b2480-5fff-11eb-9560-bb019b2e2b8c.png">

**Comment by nwmac** [comment]
Had a quick look at this - I don't see a way to actually click on links in tooltips - as soon as the pointer leaves the info icon, the tooltip is hidden, so you can't actually move the pointer to click on a link ina tooltip.

**Comment by aiyengar2** [comment]
Steps taken to reproduce (Rancher version 2.5.5, tag `v2.5.5`):
- Install Monitoring v2 in dashboard
- Go to Monitoring --> Receiver --> Create --> Slack

Result:
![Screen Shot 2021-02-19 at 4 41 06 PM](https://user-images.githubusercontent.com/13127443/108576141-54b7e000-72d1-11eb-9f51-dbf626d73471.png)

Steps taken to see if issue was fixed (Rancher version 2.5-head, commit `96dc206`):
- Install Monitoring v2 in dashboard
- Go to Monitoring --> Receiver --> Create --> Slack

Result:
![Screen Shot 2021-02-19 at 4 41 18 PM](https://user-images.githubusercontent.com/13127443/108576142-571a3a00-72d1-11eb-836a-80dd5edb2ea7.png)

@lvuch this seems like either a regression or a fix that was backported but not added to the latest release; it also seems like https://github.com/rancher/dashboard/pull/2301 has not been merged yet.

Re-opening this ticket.

**Comment by aiyengar2** [comment]
Steps taken to reproduce (Rancher version v2.5.6-rc3, tag `v2.5.6-rc3`):
- Install Monitoring v2 in dashboard
- Go to Monitoring --> Receiver --> Create --> Slack

Result:
![Screen Shot 2021-02-22 at 12 17 18 PM](https://user-images.githubusercontent.com/13127443/108765046-2ff97d80-7508-11eb-8a24-80d6a80a5cd1.png)

Steps taken to see if issue was fixed (Rancher version 2.5-head, commit `b4be2b2`):
- Install Monitoring v2 in dashboard
- Go to Monitoring --> Receiver --> Create --> Slack

Result:
![Screen Shot 2021-02-22 at 12 17 29 PM](https://user-images.githubusercontent.com/13127443/108765072-37b92200-7508-11eb-9e2f-0b34132cb95e.png)

LGTM, closing this ticket
