### ISSUE TITLE
"Send To" field looks highlighted in Add Responders section in OpsGenie receiver

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2250]
**On 2.5-head - commit id: `ac48370`**

- Install Monitoring v2 in dashboard. Go to Monitoring --> Receiver --> Create --> OpsGenie --> Add OpsGenie --> Add responders
- The Send To field looks highlighted. The blue background for the label field
<img width="1404" alt="Screen Shot 2021-01-26 at 6 00 07 PM" src="https://user-images.githubusercontent.com/26032343/105931845-c7021100-6000-11eb-9061-4792a03304fb.png">

**Expected:**
The field should not be highlighted. Why is it highlighted?

**Comment by aiyengar2** [comment]
Steps taken to reproduce (Rancher version 2.5.5, tag `v2.5.5`):
- Install Monitoring v2 in dashboard
- Go to Monitoring --> Receiver --> Create --> OpsGenie --> Add OpsGenie --> Add responders

Result:
![Screen Shot 2021-02-19 at 4 14 33 PM](https://user-images.githubusercontent.com/13127443/108574972-a494a800-72cd-11eb-8319-5985a8368eee.png)

![Screen Shot 2021-02-19 at 4 19 18 PM](https://user-images.githubusercontent.com/13127443/108575194-4d430780-72ce-11eb-8909-1f5c43cf0a34.png)

Steps taken to see if issue was fixed (Rancher version 2.5-head, commit `96dc206`):
- Install Monitoring v2 in dashboard
- Go to Monitoring --> Receiver --> Create --> OpsGenie --> Add OpsGenie --> Add responders

Result:
![Screen Shot 2021-02-19 at 4 14 40 PM](https://user-images.githubusercontent.com/13127443/108574993-b1b19700-72cd-11eb-9800-da74408f54ae.png)

![Screen Shot 2021-02-19 at 4 19 25 PM](https://user-images.githubusercontent.com/13127443/108575196-4f0ccb00-72ce-11eb-8408-57bc4926587c.png)

LGTM
