### ISSUE TITLE
Dashboard auth [FreeIPA, openldap and AD] Allow members/clusters option is not letting to add/remove users

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2254]
Rancher | v2.5-2ec02e753d1c5c428b8eff9681ad3f72553829aa-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

On the dashboard, for "Allow members of Clusters, Projects, plus Authorized Users and Organizations" not adding/removing any users from the search box. This option works on ember UI.
The user has been added from dashboard. After saving, if we went back to the auth page, the user is not seen.
<img width="1279" alt="Screen Shot 2021-01-27 at 2 22 32 PM" src="https://user-images.githubusercontent.com/38144301/106062632-e7d37080-60ab-11eb-8df5-26054fdd2f8e.png">
<img width="1277" alt="Screen Shot 2021-01-27 at 2 23 34 PM" src="https://user-images.githubusercontent.com/38144301/106062752-13eef180-60ac-11eb-8568-ca6e48870f58.png">

Same with remove user, after removing the user[users added from ember UI] and saving the config, if we went back to the auth page, the removed users are still seen on the auth page.

**Comment by anupama2501** [comment]
#2114

**Comment by izaac** [comment]
Rancher version `v2.5-head (02/18/2021)` _03b8153_

I did a spot check using AD as part of another issue validation and this seems to be working @anupama2501 still need to check on that and OpenLDAP/FreeIPA

**Comment by anupama2501** [comment]
Verified on 

Rancher | v2.5-03b8153174e6762438cd906f6dc64eaa2f0802ae-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher51

From the dashboard auth providers, select AD/OpenLDAP/FreeIPA
1.Enable the auth for each provider separately
2.Verify by adding users with "Allow members of Clusters, Projects, plus Authorized Users and Organizations"
3.Logout and login as users that were not added as part of the above option - login fails [PASS]
4.Login as a valid user from option 2, login works
5.Enable the option "Restrict access to only Authorized Users and Organizations"
6.Repeated the options 3 and 4.

Works for AD/OpenLDAP/FreeIPA
