### ISSUE TITLE
On cluster explorer creating a load balancer service by providing the minimum required info hangs

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/dashboard#2256]
on 2.5-head, commit id 24c32a3

steps to repro( it's always reproducible)

1. Cluster Explorer -> Services -> Load Balancer -> create
2. Fill out only the fields which are marked as required "*"

<img width="1080" alt="Screen Shot 2021-01-27 at 4 25 25 PM" src="https://user-images.githubusercontent.com/72409237/106072311-c8910f00-60bc-11eb-8ae6-11fa9703b6d3.png">

There was no error during creating, but it never finished the job and stays at pending status

**Comment by vincent99** [comment]
Do you have a cloud provider configured?  It is "normal" for a LoadBalancer to stay in pending when there is no cloud controller configured to do anything with it (i.e. the default RKE config).

**Comment by sadiapoddar** [comment]
@vincent99 
I didn't provision the cluster by selecting a cloud provider, it's a regular node driver cluster.
I will provision a cloud provider cluster and retry the load balancer creation and update the issue

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, commit  24c32a3
1. provisioned cloud provider enabled cluster
2. Created the load balancer type service using the minimum required info and it succeeded. 

Closing the bug as it's working on the cloud provider enabled cluster
