### ISSUE TITLE
In service page a headless service lists  as clusterip type instead of headless type

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/dashboard#2257]
On 2.5-head, commit id 24c32a3

Steps to repro
1. Create a headless type service

<img width="1707" alt="Screen Shot 2021-01-27 at 5 31 18 PM" src="https://user-images.githubusercontent.com/72409237/106077550-9c7a8b80-60c6-11eb-9b8e-058c6e43ff74.png">
2. Notice that in the service page the type is listed as clusterip instead of headless
<img width="1657" alt="Screen Shot 2021-01-27 at 5 31 56 PM" src="https://user-images.githubusercontent.com/72409237/106077429-60472b00-60c6-11eb-91cb-cdf8e117d338.png">

**Comment by brendarearden** [comment]
Is this the PR that was created to fix this issue https://github.com/rancher/dashboard/pull/2319?

**Comment by nwmac** [comment]
Yes - it looks like that PR had the wrong issue referenced.

**Comment by brendarearden** [comment]
I had one final clarifying question - from what I can see there is no service type of "headless" in the kubernetes api - its just how you configure the service types that make them "headless". So is the type in the table supposed to reflect the kubernetes yaml "type", or is it supposed to reflect the selection you made on the create service page?

**Comment by vincent99** [comment]
Neither/both?  It's supposed to be useful for a human.. which generally means showing the k8s type, which is also generally what the create service page offers.  Except if type=ClusterIP and clusterIP=none, then humans call that a headless service.

**Comment by brendarearden** [comment]
Steps to Recreate:
1. Set up single install rancher/rancher:v2.5.5
2. From the cluster explorer, navigate to service
3. create a headless service (see yaml used below)
4. See type in the service table for new headless service
![Screen Shot 2021-02-22 at 4 49 58 PM](https://user-images.githubusercontent.com/19455540/108785106-00f60280-752e-11eb-84a8-e892cc3b3bcd.png)

Steps to Test:
1. Set up single install rancher/rancher:v2.5.5
2. From the cluster explorer, navigate to service
3. create a headless service (see yaml used below)
4. See the type is now headless in the type column
![Screen Shot 2021-02-22 at 4 51 06 PM](https://user-images.githubusercontent.com/19455540/108785198-28e56600-752e-11eb-8a8d-d4ec0b7f01df.png)



=====Example Yaml======
Headless Service: 
```
apiVersion: v1
kind: Service
metadata:
  name: my-headless-service
  namespace: default
spec:
  clusterIP: None # <--
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
```

Closing as resolved - Type is now showing as headless in the table.
