### ISSUE TITLE
Viewing a router looks editable and does not show all information

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#227]
Information not shown (either on view or edit, which is problematic on edit because then saving removes whatever information should've been there):
- Path
- Header Rules
- Cookie Rules

In general, when I view the details of a route by clicking on it, I can edit the fields (but nowhere to save/cancel). The only field I cannot edit is "Name". "Namespace" has a button to "Create new namespace" that should not be there.

**Comment by rancher-max** [comment]
3 Issues upon validation:
- View does not allow me to edit fields anymore, which is good. However, Edit also does not allow me to edit fields anymore. 

- Path still doesn't show the value that was input

- Headers and Cookies also don't show the data that was input. They both show `0: false`. This might need to be a separate issue? I think possibly what we send to the API is incorrect when creating these:
**Example request:**
`{"type":"rio.cattle.io.v1.router","kind":"Router","apiVersion":"rio.cattle.io/v1","metadata":{"annotations":{},"namespace":"default","name":"myuirt"},"spec":{"routes":[{"match":{"headers":[{"name":"0","value":{"name":"FOO","value":{"exact":"TEST"},"binary":false}}],"path":{"exact":"/v0"},"cookies":[{"name":"0","value":{"name":"MYCOOK","value":{"exact":"ISACHEF"},"binary":false}}]},"uuid":"M0LilJYGrehWDR7f","to":[{"app":"demo","version":"v0","port":80,"uuid":"lIbvUBlyueYwfL90"}]}]}}`
**Example response from above request:**
`{"_type":"rio.cattle.io.v1.router","apiVersion":"rio.cattle.io/v1","id":"default/myuirt","kind":"Router","links":{"remove":"https://dashboard-rio-system.yrxyrb.on-rio.io/v1/rio.cattle.io.v1.routers/default/myuirt","rioupdate":"https://dashboard-rio-system.yrxyrb.on-rio.io/v1/rio.cattle.io.v1.routers/default/myuirt?riofile","rioview":"https://dashboard-rio-system.yrxyrb.on-rio.io/v1/rio.cattle.io.v1.routers/default/myuirt?riofile","self":"https://dashboard-rio-system.yrxyrb.on-rio.io/v1/rio.cattle.io.v1.routers/default/myuirt","update":"https://dashboard-rio-system.yrxyrb.on-rio.io/v1/rio.cattle.io.v1.routers/default/myuirt"},"metadata":{"creationTimestamp":"2019-12-11T20:20:26Z","generation":1,"name":"myuirt","namespace":"default","resourceVersion":"247468","selfLink":"/apis/rio.cattle.io/v1/namespaces/default/routers/myuirt","uid":"2a1b1c2d-cbcf-4c54-8fd1-95df560ead96"},"spec":{"routes":[{"match":{"cookies":[{"name":"0","value":{"binary":false,"name":"MYCOOK","value":{"exact":"ISACHEF"}}}],"headers":[{"name":"0","value":{"binary":false,"name":"FOO","value":{"exact":"TEST"}}}],"path":{"exact":"/v0"}},"to":[{"app":"demo","port":80,"uuid":"lIbvUBlyueYwfL90","version":"v0"}],"uuid":"M0LilJYGrehWDR7f"}]},"type":"rio.cattle.io.v1.router"}`
**Example Desired Request (left out cookies in this):**
`{"kind":"Router","apiVersion":"rio.cattle.io/v1","metadata":{"name":"clirt","namespace":"default","creationTimestamp":null},"spec":{"routes":[{"match":{"path":{"exact":"/v0"},"headers":[{"name":"FOO","value":{"exact":"TEST"}}]},"to":[{"app":"demo","version":"v0"}]}]},"status":{}}`

**Comment by nwmac** [comment]
Rio is no longer supported. If this is a general Rancher dashboard issue, please feel free to re-open with additional information.
