### ISSUE TITLE
shell always disconnected

### ISSUE THREAD

**Issue by mdizcalvino** [rancher/dashboard#2270]

**Comment by nwmac** [comment]
@mdizcalvino Can you provide a bit more information about the problem you're experiencing.

**Comment by vincent99** [comment]
If this is only in Safari, #2231 and fixed in https://github.com/rancher/dashboard/commit/2245fc3140a2c2d7c8d447f36c467e3f9b629ce0 for the next release.

**Comment by gaktive** [comment]
Closing for now, please reopen if this is still an issue for you after 2.5.6 is available.
