### ISSUE TITLE
Make istio ServiceEntries available in the Rancher UI

### ISSUE THREAD

**Issue by nicolasmaier** [rancher/dashboard#2271]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Istio ServiceEntries are not available in the Rancher UI.

Would be nice to have them available like Gateways/DestinationRules/VirtualServices

**Result:**
n/a

**Other details that may be helpful:**
n/a

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA):
HA

**Comment by gaktive** [comment]
Possible duplicate, will check.

**Comment by nwmac** [comment]
See: https://istio.io/latest/docs/reference/config/networking/service-entry/

**Comment by nwmac** [comment]
We don't plan to add support for this in the near future - we will be looking at the Istio UI support in a future version.
