### ISSUE TITLE
Namespace/Name are reverted to defaults when version is selected

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2279]
Namespace resets when chart changes version (because of page refresh). People work from left to right, so it’s unexpected that a value already chosen would change back to something else. Chart version should be on its own line in top left corner, and perhaps with nothing selected - no fields can be edited until the user chooses a version

Since version is on the top row, the expectation is the user would pick version before picking namespace/name. Some charts require specific namespaces or names for the chart being deployed. Namespace could be preserved, name is set to the name of the chart so you wouldn't want it to be.

The defaults should be less dependent upon the version, so we need a UX story that would allow admins to pick a version without selecting a namespace. Perhaps this could be addressed with a move of the button from the right to the left.

**Comment by nwmac** [comment]
We will be improving the overall UX in 2.6, so will address this then

**Comment by nwmac** [comment]
@richard-cox This is related to the Helm install process - I think with the changes you have made, this is no longer an issue, since you can't change the version once you enter the install stepper

**Comment by richard-cox** [comment]
Correct (ish), there's no where these two overlap fields overlap.

For new apps... Version is selected in the chart detail page and namespace set in step 1 of the install wizard
For existing apps.. Version can be updated in step 1 of the install wizard... but namespace cannot be updated for existing apps
