### ISSUE TITLE
Update default charts to not show pre-release Helm charts

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2280]
When showing the Helm charts that are available to upgrade, we sometimes default to pre-release/alpha charts, which isn't necessarily a version what customers want to upgrade too. We need some way to show what charts are published versus those that are only visible via Helm using the `--devel` flag.

**Comment by thehejik** [comment]
**Test report:**
The fix behaves correctly on `rancher:2.5.8-rc4` and also on `rancher:master-head` (upstream cluster only) - tested on linux and windows clusters. For the testing `v2.5-dev` for 2.5.8 and `v2.6-dev` on master were used.

In Cluster Exporter there are two new options in top right "Avatar menu"/Preferences -> Helm Charts: `Show Releases Only` and `Include Prerelease Versions`.

I've validated following cases:
- When `Show Releases Only` is selected only released charts are offered (as v2 rancher-monitoring-9.4.202) for installation
- When `Show Releases Only` is selected an upgrade to prereleased versions is not offered.
- When `Include Prerelease Versions` is selected also prereleased versions are available for installation in addition to the released ones.
- When `Include Prerelease Versions` is selected but released version was installed before with `Show Releases Only` selected the prerelease versions are offered for an upgrade in addition.
- When `Show Releases Only` is selected but there was a prerelease version installed before it shows the prerelease version as installed but no upgrade is offered.

Works as expected. Closing.
