### ISSUE TITLE
Auth Provider - SAML based auths pop up is not closing during enabling an Auth

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2292]
Rancher version `v2.5-head (02/04/2021)` _f351604_

When attempting to enable a SAML based auth like Okta or Keycloak the pop up for login is shown but after successful login the pop up is kept open.

I see the main browser instance in the background changing the Auth status to active but If a close the Pop up the mesage
 "Access was not authorized" is displayed.

![Screen Shot 2021-02-04 at 11 25 18 AM](https://user-images.githubusercontent.com/27659/106939940-24bbea80-66de-11eb-8b2b-ea11437e985e.png)

![Screen Shot 2021-02-04 at 11 25 24 AM](https://user-images.githubusercontent.com/27659/106939845-0a820c80-66de-11eb-9fb5-56fd838ecc88.png)

**Comment by mantis-toboggan-md** [comment]
This should be fixed by this pr https://github.com/rancher/dashboard/pull/2313

**Comment by izaac** [comment]
Rancher version `v2.5-head (02/23/2021)` _a85f4d1_
I'm not experiencing this in a newer build.
