### ISSUE TITLE
Workspace dropdown not aligned properly for Fleet/CD App in v2 dashboard

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#2306]
**What kind of request is this (question/bug/enhancement/feature request): bug**

**Steps to reproduce (least amount of steps as possible):**
* Go to Cluster Explorer, and click select `Global Applications->Continuous Delivery`
* The dropdown for selection Fleet Workspace is not aligned properly with the top blue strip

**Result:**
![fleet-namespaces](https://user-images.githubusercontent.com/12828077/107499226-fc783400-6b94-11eb-8dc9-8f73fb5b3af2.png)

**Environment information**
- Fleet chart version: 0.3.400-rc3
- Rancher version: v2.5.6-rc4
- Installation option (single install/HA): single
- Reproducible in Microsoft Edge 90.0.782.0, Vivaldi 3.6.2165.36 (both WebKit based) and FF 78.7.0esr on openSUSE 15.2

**Comment by nickgerace** [comment]
The fix appears to have worked.

## Before
Rancher version: v2.5.6-rc4
Installation option (single install/HA): single
Browser: Chrome 8.0.4324.182
OS: macOS Big Sur 11.2.1
Arch: amd64

<img width="514" alt="Screen Shot 2021-02-19 at 4 41 08 PM" src="https://user-images.githubusercontent.com/39320683/108564855-c3953900-72d1-11eb-95e2-455e19ed14ae.png">

## After
Rancher version: latest
Installation option (single install/HA): single
Browser: Chrome 8.0.4324.182
OS: macOS Big Sur 11.2.1
Arch: amd64

<img width="493" alt="Screen Shot 2021-02-19 at 4 44 09 PM" src="https://user-images.githubusercontent.com/39320683/108564864-c7c15680-72d1-11eb-8ee1-aaeeca6be621.png">
