### ISSUE TITLE
promethues tab  shows as promethis

### ISSUE THREAD

**Issue by MarUoneB** [rancher/dashboard#2307]
Within the monitoring on the rancher dashboard under the overview. Promethues shows as prometheis.

![image](https://user-images.githubusercontent.com/42939372/107513472-8d0c3f80-6ba8-11eb-9cb1-2038b82a2018.png)

**Comment by vincent99** [comment]
This is the [correct plural](https://prometheus.io/docs/introduction/faq/#:~:text=Apache%202.0%20license.-,What%20is%20the%20plural%20of%20Prometheus%3F,Prometheus'%20is%20'Prometheis') of Prometheus.

**Comment by MarUoneB** [comment]
my bad
