### ISSUE TITLE
Rancher v2.5.5 Apps & Marketplace charts not working with k3s 1.20.2+k3s1 clusters

### ISSUE THREAD

**Issue by asloan7** [rancher/dashboard#2310]
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+k3s1", GitCommit:"1d4adb0301b9a63ceec8cabb11b309e061f43d5f", GitTreeState:"clean", BuildDate:"2021-01-14T23:52:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+k3s1", GitCommit:"1d4adb0301b9a63ceec8cabb11b309e061f43d5f", GitTreeState:"clean", BuildDate:"2021-01-14T23:52:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Going to https://rancher-REDACTED:8443/dashboard/c/c-lmwqg/apps/charts
Charts /  Deploy Chart
All Categories 
It only shows "There are no charts available, have you added any repos?"

Installed Apps tab shows State: Unknown | fleet-agent

Chart Repositories tab shows 
State: Unknown | Partners ...
State: Unknown | Rancher ...

-----
This stuff all works for "local" cluster still, v1.18.12+rke2r2
Worked for k3s clusters v1.19.5+k3s2, which I will move back to

**Comment by vincent99** [comment]
2.5.5 does not support 1.20.  https://github.com/rancher/rancher/issues/30556
