### ISSUE TITLE
Chart's `Categories` combo box and Refresh button are visually broken

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2315]
Apps & Marketplace Product, Charts Page

![image](https://user-images.githubusercontent.com/18697775/107665002-e9449180-6c84-11eb-9c92-b3c9c75c82e2.png)

![image](https://user-images.githubusercontent.com/18697775/107665083-00837f00-6c85-11eb-9df7-f49437326adb.png)

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/2267

**Comment by richard-cox** [comment]
Closing as duplicate of #2278
