### ISSUE TITLE
Continues Delivery's Namespace combo box missaligned

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2316]
Continues Delivery Product, Any Page

![image](https://user-images.githubusercontent.com/18697775/107665442-56f0bd80-6c85-11eb-8748-ca5fe7a2e6f1.png)

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/2267

**Comment by richard-cox** [comment]
Duplicate of #2306
