### ISSUE TITLE
Create HPA does not list only deployment

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2324]
**On 2.5-head commit id: `3e96d7f`**

- Deploy a daemonset - wk01, deployment - wk02 and wk03 in Ember UI/cluster explorer
- Go to cluster explorer --> hosrizontal Pod Autoscaler
- Click on create --> Target workload shows deployment/daemonset and deployment's pod names
<img width="789" alt="Screen Shot 2021-02-14 at 4 23 22 PM" src="https://user-images.githubusercontent.com/26032343/107893611-0e354080-6ee1-11eb-822b-7b922a880cd1.png">

**Expected:**
Dropdown should show only deployment

**Comment by nwmac** [comment]
See: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by sowmyav27** [comment]
**On 2.5.6-rc5**

- Target lists the deployments and the pods. 

@richard-cox Should pods be displayed? 
<img width="824" alt="Screen Shot 2021-02-21 at 9 17 01 PM" src="https://user-images.githubusercontent.com/26032343/108665685-58429700-748a-11eb-92bc-cab8287c10ad.png">

**Comment by richard-cox** [comment]
@sowmyav27 Pods should not be shown. Can you confirm that those are not replica sets? I've gone back to the docs and double checked what should be shown and, along with the original daemon set type, have excluded cron_job and job - see #2368. Also in that PR I've made a change to show the workload type in the drop down.

**Comment by slickwarren** [comment]
only deployments, statefulsets, and replicasets are showing now for 2.5-head (87006de) and master-head (465bb3b)

<img width="1111" alt="Screen Shot 2021-02-24 at 2 20 14 PM" src="https://user-images.githubusercontent.com/16691014/109182907-44c15580-7742-11eb-8a9f-5d10969d2f10.png">
