### ISSUE TITLE
Cluster Explorer: Services: Changing sort order in a table loses active tab

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2327]
Note: this issues affects places where we have a resource that has a tabbed display with tables - described below for Services, but also affects Pods and Secrets (and others I imagine).

In Cluster Explorer, go to a Service, as shown below and change the tab to 'Ports:

![ServiceBug](https://user-images.githubusercontent.com/1955897/107945119-11830780-6f87-11eb-9c9f-4d8ca404c5e2.png)

Now, click on any of the table column headers to change the sort order - the page will refresh and go back to the first tab, 'Pods'.

The Loading indicator is also shown - it looks like the page is being reloaded, which is why the active tab is lost.

gz#16178

**Comment by UberKuber** [comment]
This issue should be resolved in https://github.com/rancher/rancher/releases/tag/v2.5.8.

**Comment by sowmyav27** [comment]
**In 2.6-head commit id: `4b6af95 `**

Sorting, sorts the columns and refresh is not seen.
