### ISSUE TITLE
Cluster Drop down overflows when text typed and text color issue

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2329]
On Cluster Explorer, click on the cluster drop down in the top-right.

The text color in light mode is black, where it should be white:

![ClusterDropDown1](https://user-images.githubusercontent.com/1955897/107951892-ed2c2880-6f90-11eb-9f88-bc6b3c522401.png)

Type more text - the drop down below the text field grows in size showing empty content:

![ClusterDropDown2](https://user-images.githubusercontent.com/1955897/107952186-54e27380-6f91-11eb-8124-ce50b5e5db98.png)

**Comment by slickwarren** [comment]
tested on version 2.5-head (a420b51):
* added some test clusters (some with shorter names, some with max character names)
* navigated to cluster explorer

<img width="204" alt="Screen Shot 2021-03-09 at 10 36 29 AM" src="https://user-images.githubusercontent.com/16691014/110520693-aaf39400-80c3-11eb-9abd-c449c561fe32.png">

* long text names now show up properly
<img width="457" alt="Screen Shot 2021-03-09 at 10 36 20 AM" src="https://user-images.githubusercontent.com/16691014/110520698-ab8c2a80-80c3-11eb-8e12-2cdbf0cd58bb.png">


### Reopening for the following: 
Text should be white (it is black in above screenshots). White should be used for anything the user enters in the toolbar (including the namespaces dropdown/textbox) for BOTH themes (light and dark) to match the white text in the toolbar. 
<img width="430" alt="Screen Shot 2021-03-09 at 11 24 42 AM" src="https://user-images.githubusercontent.com/16691014/110525942-0fb1ed00-80ca-11eb-8682-e77949faaa45.png">

**Comment by slickwarren** [comment]
validated on v2.5-head (38649e2)
<img width="274" alt="Screen Shot 2021-03-15 at 3 46 55 PM" src="https://user-images.githubusercontent.com/16691014/111231008-bce2a480-85a5-11eb-9f91-9744e2c3e4a8.png">
<img width="261" alt="Screen Shot 2021-03-15 at 3 47 42 PM" src="https://user-images.githubusercontent.com/16691014/111231044-cb30c080-85a5-11eb-899f-fedef2c69530.png">
