### ISSUE TITLE
Not able to login to rancher after enabling Azure AD Auth in dashboard, Logout and Log back in

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2340]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**On master-head:**
- Enable AzureAD using Dashboard UI
- Azure AD is enabled successfully
- Now logout from rancher
- log back in. Give in the right details
- The user is always taken back to login page with a 401 Unauthorized error in the dev tools --> Network tab

**Note:**
This does not happen when Azure AD is enabled through Ember UI.

**On 2.5-head commit id: `03b815317`**

- Enabled AzureAD through dashboard
- Logout from Rancher
- Log back in. Give in the right creds.
- Redirected to `http://rancherserver/dashboard/auth/verify/?code=**redacted**&session_state=b192a471-6aea-444c-a5aa-5ef8200b9a44#` , page is stuck - blank
- Error seen in console:

```
Uncaught (in promise) TypeError: Cannot read property 'includes' of undefined
    at verify.vue:23
    at d (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.O.forEach.t.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at Object.fetch (verify.vue:20)
```
**Related dashboard issue:**
https://github.com/rancher/dashboard/issues/2117

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `d7203b4ba` and 2.5-head commit id: `03b815317`
- Installation option (single install/HA): single install

**Comment by gaktive** [comment]
Is there a possible connection to a similar Keycloak issue? https://github.com/rancher/dashboard/issues/2343

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `30e53bd4`**

- Enabled AzureAD through dashboard
- Logout from Rancher
- log back in. Give in the right details
- The user is always taken back to login page with a 401 Unauthorized error in the dev tools --> Network tab

**Comment by anupama2501** [comment]
Verified the issue on master-8476503a1a631c25ead03293736fbfb85d69c906-head

from cluster explorer --> Users and auth --> Auth providers --> Enable Azure AD by providing the details
Log out and login --> Users are taken to rancher login page.

For 2.5-head ,seeing the issue https://github.com/rancher/dashboard/issues/2538
Tracking the issue for 2.5-head validation through https://github.com/rancher/rancher/issues/31874
