### ISSUE TITLE
Auth Providers Keycloak - User in Restrict access to only the auhorized users & groups can't login

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2343]
Rancher version `v2.5-head (02/18/2021)` _03b8153_

**Use Keycloak auth**

1. Add a user using the site access option
`Allow members of clusters and projects, plus authorized users & groups`
2. Check the user added in step 1 is able to login (using a separate browser)
3. Logout with that user
4. Change the site access option to 
`Restrict access to only the auhorized users & groups`
5. In the Second browser try login with the user added in step 1

Result:

`Logging in failed: Your account may not be authorized to log in.`

**This is working with Active Directory but not using Keycloak, this might be specific to SAML**

Expected result:

Users in this list `Restrict access to only the auhorized users & groups` should be able to login.

Site options in UI:

![Screen Shot 2021-02-18 at 11 58 45 AM](https://user-images.githubusercontent.com/27659/108407683-4d190e00-71e1-11eb-8b21-9857fd337066.png)

**Comment by gaktive** [comment]
There's a chance that https://github.com/rancher/dashboard/issues/2340 has a connection to the underlying code.

**Comment by izaac** [comment]
Rancher version: `v2.5-head (02/23/2021)` _a85f4d1_
I couldn't repro the issue in a more recent build. Closing.
