### ISSUE TITLE
inconsistent toggle on view vs edit for yaml/config

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#2345]
On detail pages the UI has a `[ detail | config | yaml ]` in the masthead, however the edit pages don't but _do_ allow toggle to yaml view in the save/cancel footer. Instead of the `[ edit as yaml ]` and `[ back to form ]` I suggest sticking with the group button that is in the new view layout.

Detail:
<img width="813" alt="Screen Shot 2021-02-18 at 3 44 55 PM" src="https://user-images.githubusercontent.com/3013118/108431557-41890f80-7200-11eb-841d-7789a70ccca7.png">

Edit:
<img width="814" alt="Screen Shot 2021-02-18 at 3 45 24 PM" src="https://user-images.githubusercontent.com/3013118/108431602-536ab280-7200-11eb-89ec-ddc07b0c0e56.png">

@codyrancher brought this to my attention when he was working on another bug. 2/18

**Comment by nwmac** [comment]
@lvuch This makes sense - we should have the group button - Form | YAML in the top-right, rather than in the button bar at the bottom.

Can you show an example of this so it can be implemented.

**Comment by lvuch** [comment]
https://xd.adobe.com/view/6c582a85-06bd-45bf-8d1d-03439c1d9042-390b/

**Comment by lvuch** [comment]
@nwmac please review above link
