### ISSUE TITLE
Unlabeled selects missing elements in view only

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#2346]
When an unlabeled select is in view mode it looses it's dropdown and select options.

edit:
<img width="550" alt="Screen Shot 2021-02-18 at 3 49 02 PM" src="https://user-images.githubusercontent.com/3013118/108431943-d68c0880-7200-11eb-9a17-2c0424292a7d.png">

view:
<img width="507" alt="Screen Shot 2021-02-18 at 3 49 29 PM" src="https://user-images.githubusercontent.com/3013118/108431982-e4da2480-7200-11eb-838d-bde305f0c1f2.png">

I could set a min height but wanted this to be tested and reviewed by a dev before doing so.

/design-system/form-controls

**Comment by westlywright** [comment]
@lvuch and I looked at this this afternoon and I believe she will be putting the fix in.
