### ISSUE TITLE
Unable to set Custom Endpoints in AzureAD Auth Provider

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2349]
- Nav to the AzureAD config page
- Select `Custom` Endpoint
- Changes the `Endpoint` value are ignored (value does not change on keypress)
- Changes to other endpoints  are visible until input is de-focused.

I had a quick look into this, expecting an easy fix by ignoring `endpoint === 'custom'` in `setEndpoints` in most cases (update to default when first selecting `custom` ignore otherwise), however that results in the same behaviour ... except setting a tenant then shows the original edited endpoint value. There's something strange going in with the model

**Comment by richard-cox** [comment]
Further info on outcome can be found in #2385

**Comment by anupama2501** [comment]
v2.5-4e48b8a9fbedad498fa21fd00e6e426ab3e13770-head

From the cluster explorer --> auth providers and users --> AzureAD --> provide all the details and from endpoints select custom
Endpoints are not defocused and can be changed to a newer value

**Comment by anupama2501** [comment]
Verified on master-cf376738e499ba538e80d8d02f37592391094ac4-head

From the cluster-explorer, Users and authentication --> Auth Providers --> Azure AD --> copy the 'Reply URL' and paste in the registration portal test app
Provide the Tenant ID, Application ID and Application Secret and select custom Endpoints in the Azure AD in the auth providers page [provide graph, token and auth endpoints] --> Authenticate with Azure and the authentication goes through without any error
Create a cluster logged in as a standard user
Restrict the access to one user and verified other users are not allowed to log in


For 2.5-head validation, tracking through this ticket https://github.com/rancher/rancher/issues/31874
