### ISSUE TITLE
Node detail fails to load for a local node with no images

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2350]
Run a fresh backend. Log into dashboard. Go to Nodes and the click on 'local-node' - the following error is shown:

![Error](https://user-images.githubusercontent.com/1955897/108501319-0858aa00-72a9-11eb-83b5-9e8bfa85dd1c.png)

Looks like when there are no images in the cluster, the expected `images` property is undefined.

**Comment by nwmac** [comment]
This only happens on oldish web browsers (e.g. Chrome version 85 (Aug 2020) or earlier)

**Comment by rmweir** [comment]
Unable to reproduce issue in v2.5.5. @nwmac confirmed they are also unable to reproduce.

On version v2.5-head I went to nodes on a fresh install and nodes are showing as expected. This has been repeated multiple times:
![image](https://user-images.githubusercontent.com/19376037/108890255-9646d480-75ca-11eb-9a6d-172125ccdc9b.png)
