### ISSUE TITLE
Node Detail View: Internal IP & External IP are not shown + warning in console log

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2352]
The node detail view does not show the internal or external IP and there is the following error in the console log:

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <CopyToClipboardText> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <DetailTop> at components/DetailTop.vue
       <ResourceDetail> at components/ResourceDetail/index.vue
         <ClusterResourcedId> at pages/c/_cluster/_product/_resource/_id.vue
           <Nuxt>
             <Layouts/default.vue> at layouts/default.vue
               <Root>
```

![MissingIP](https://user-images.githubusercontent.com/1955897/108502456-b9ac0f80-72aa-11eb-9f7f-8448f66c6c58.png)

**Comment by rmweir** [comment]
Unable to reproduce issue in v2.5.5. @nwmac confirmed they are also unable to reproduce.

On version v2.5-head I went to nodes on a fresh install and internal ip is showing as expected. This has been repeated multiple times:
![image](https://user-images.githubusercontent.com/19376037/108890840-474d6f00-75cb-11eb-8153-a0ff7a699d98.png)
