### ISSUE TITLE
Enhancement: Role Template dropdown not visible if multiple verbs added

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2356]
Type: Enhancement 

Project: Global roles/role templates
Related to: https://github.com/rancher/dashboard/issues/2111 tests

* adding `verbs` past user's window obstructs view of dropdown until a scroll occurs

<img width="219" alt="Screen Shot 2021-02-10 at 1 25 38 PM" src="https://user-images.githubusercontent.com/16691014/107576077-89c38480-6ba5-11eb-8960-3b17542d2dc6.png">

**Comment by nwmac** [comment]
The dropdown should drop above the box when there is not enough room in the browser window - but we should look for a better way to present this.

**Comment by lvuch** [comment]
- dropdown height should not change
- all, none, `delete`, `create`, `...`, `delete`, `create`, `+2`
- edit only in dropdown. this means no "closable" pills

**Comment by lvuch** [comment]
![image](https://user-images.githubusercontent.com/3013118/121088047-06ecb800-c79a-11eb-8b44-2be249eefefc.png)

**Comment by richard-cox** [comment]
Related #2680

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-24040b6dc9ae2fa6a3a49cbe126132c13c2587ba-head`
UI: `master e7876c6`

The dropdown is no longer hid and has a better reacting behavior under various viewport sizes. Original issue reproduced on 2.8.0.

Generic viewport size mac-16:

![Image](https://github.com/user-attachments/assets/1509ea15-a66d-46ba-a2e1-af9815ff456f)
