### ISSUE TITLE
Enhancement: Selecting previously selected verbs from role template options does nothing

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2357]
when creating a new role template, you have the option to select verbs
please see https://github.com/rancher/dashboard/issues/2111#issuecomment-777066167 for more context

* Clicking previously selected items (highlighted) does nothing 
<img width="207" alt="Screen Shot 2021-02-10 at 1 23 58 PM" src="https://user-images.githubusercontent.com/16691014/107575992-6ac4f280-6ba5-11eb-999d-cc23d057cde9.png">

* would expect clicking a verb from the dropdown list that has already been selected to remove from those already selected 
* Or, just remove verbs from the dropdown list as they are selected so the user can't select them again.

**Comment by nwmac** [comment]
Could be bumped to 2.5.7 if there is not an easy way to get the desired behaviour that selecting an already item should de-select.

**Comment by codyrancher** [comment]
I made this change to the Select and LabeledSelect components. This will apply to all areas that haven't overridden the options slot.

**Comment by codyrancher** [comment]
One place you can verify it without role template being active is in the monitoring chart.

![image](https://user-images.githubusercontent.com/55104481/111191903-c0f6ce00-8575-11eb-88a2-fda86cb50e7d.png)

**Comment by slickwarren** [comment]
### ENHANCEMENT VALIDATED -- UI now allows clicking previously selected items, which un-selects that item
tested on v2.5-head (38649e228b183289ddf4b876c3ca5dc1615644cc): 
* deployed cluster large enough for monitoring
* deployed monitoring with the following:
  * add additional secrets for alerts 
    * tested each of the following: 
      * Add 1 
      * remove 1 - list
      * remove 1 - dropdown
      * remove bulk - list
      * remove bulk - dropdown
  * **UI now allows clicking previously selected items, which un-selects that item** -- PASS
  * validated that secrets are saved to alerts
  * upgraded using existing workflow (only removed via the list) -- validated secret(s) is removed
  * upgraded using new workflow (only removed/added via dropdown) -- validated new secrets are added/removed
* also performed the add/remove/bulk tests on role template, UI performs as expected
