### ISSUE TITLE
Bug: able to add empty resources to role templates

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2358]
* adding empty `verbs` persist on creating/editing the role (would expect empty verbs to be removed)
<img width="1458" alt="Screen Shot 2021-02-10 at 1 37 23 PM" src="https://user-images.githubusercontent.com/16691014/107576224-b37cab80-6ba5-11eb-9aab-23e40553daaf.png">

how to reproduce: 
* create a role template (from global, project/namespace, or cluster)
* add a name for the role, and click save
* **Optional** add new resources ( you can add as many empty or non empty resources for the role as you want)
<img width="1513" alt="Screen Shot 2021-02-19 at 11 34 07 AM" src="https://user-images.githubusercontent.com/16691014/108552830-b020a880-72a6-11eb-9438-c3c96f141e6a.png">

see https://github.com/rancher/dashboard/issues/2111#issuecomment-777066167 for more details

Suggested fix: 
require any resources currently displayed to be filled out for `verbs` `resources` `api groups` , etc.

**Comment by nwmac** [comment]
Minimally, could mark the rows added during edit and remove these on save if still empty - this would preserve any empty rows added outside of the UI (or added perviously)

**Comment by codyrancher** [comment]
I think that verbs is the only one that actually is required to be filled.

Looking at the admin in rancher you can have the other fields empty
![image.png](https://zube.io/files/rancher/416ac9f9e03f7c3966f89913d6195c2b-image.png)

**Comment by vincent99** [comment]
Neither of those rows is empty?  `*` and empty mean very different things.  The API might allow it, but just a verb on its own doesn't mean anything without a noun to go with it.

**Comment by codyrancher** [comment]
> Neither of those rows is empty? `*` and empty mean very different things. The API might allow it because there's minimal semantic validation in general, but I don't think having just a verb without a noun to go with it grants anything useful (access to anything).

I wasn't saying `*` was empty. 
- Row 1: Non-resource is empty.
- Row 2: resource and api groups are empty. 

Therefore they aren't required. This was primarily in regards to the suggested fix
> require any resources currently displayed to be filled out for verbs resources api groups , etc.

Do you think requiring one verb and one resource would be a good validation rule? Rancher just removes the rule if verbs or resources are empty. Rancher made api groups * if the user just specified non-resource urls but I'm not sure why since I saw an example on the k8s docs which had just a url.

**Comment by codyrancher** [comment]
I went ahead and made the check for at least one verb and at least one resource.
![image](https://user-images.githubusercontent.com/55104481/111205869-f0610700-8584-11eb-98e6-5c5be559755d.png)
![image](https://user-images.githubusercontent.com/55104481/111205886-f6ef7e80-8584-11eb-9cca-d713a878c2c4.png)

**Comment by slickwarren** [comment]
This seems to behave as expected on 2.5-head (38649e228b183289ddf4b876c3ca5dc1615644cc), but need to wait for https://github.com/rancher/dashboard/issues/2111 to land before closing

**Comment by slickwarren** [comment]
this has been moved to the Users and Authentication section of dashboard (see https://github.com/rancher/dashboard/issues/2579 for more details)
this is fixed in 2.5-head (d1083bc63e4ddde70ffadd09bf0133ae5862b5fe)
* each new resource grant requires at least 1 verb
