### ISSUE TITLE
Changing server URL leads from Cluster Explorer default to Cluster Manager

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2359]
@oskapt has run into an odd situation with Rancher 2.5.3. When using Cluster Explorer, upon modifying the URL in the browser tab to use the root leads Rancher into a state whereby a state reset so that it brings up What's New and switches to the Cluster Manager UI.

Steps to reproduce:

1. new install
2. set password, choose "only one cluster"
3. get taken to cluster explorer
4. log out
5. log in
6. asked to set server-url
7. taken to global cluster view (old UI)
8. remove everything to the root of the URL in the location bar, press enter
9. shown "what's new"
10. taken to global cluster view (same as #7)

**Comment by gaktive** [comment]
May not be relevant in 2.6 once we move to a single UI but we should verify the behaviour once we're at that state.

**Comment by nwmac** [comment]
I don't believe this is an issue in 2.6 - please re-validate in 2.6 and re-open if necessary
