### ISSUE TITLE
Need to display more info when kubectl shell takes a long time to open UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2360]
@oskapt has noticed in Rancher 2.5.3 that when viewing the kubectl shell, when it takes a long time to open the UI, there's a Connecting message with little context as to what's going on.

On the backend, a container is being spun up for each request to view the shell, which may be pulled slowly depending on where it's being run. It also invokes a sidekick container that's not shared with other people. The Connecting message is present but it needs to made more obvious with perhaps more information about why it could take time.

If we're dependent upon the API to provide more details as to why it takes longer, let @gaktive know if a backend ticket needs to be created instead.

**Comment by gaktive** [comment]
@neillsom chat with another UI engineer regarding an approach; could be as simple as a spinner.

**Comment by kravciak** [comment]
`Connecting...` message shows fine on master-head 62aef76.
Because of connection issue kubectl shell is not started and process exists with `Disconnected` message.

Successful connection testing blocked on https://github.com/rancher/rancher/issues/32657

**Comment by kravciak** [comment]
Works fine on master-head 5715b8a
