### ISSUE TITLE
Port from Ember: ability to add namespace inline when deploying from Helm

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2362]
We should bring over the experience in Ember so that when doing a helm deployment, for instance from Marketplace, within the same window, users can add the namespace at the same time.

Within Vue, adding a namespace requires having a separate browser tab up to a different part of the UI or then having the user create the namespace first and then doing a helm deployment.

**Comment by richard-cox** [comment]
I thought this was the case as well, however after investigating it is possible by creating a custom entry in the namespace drop down which will result in the namespace being created. It wasn't obvious this was happening so we now show a message to the user that it will be created

**Comment by gaktive** [comment]
Upon chatting with Neil, we need a couple tweaks.

This specific work tied to Helm is done though a new ticket will be created to tackle other areas like workloads where this needs to be done.
