### ISSUE TITLE
Cannot create a resource from custom create pages on refresh

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2369]
- Custom create pages (edit pages in create mode) require proxy functions such as `$dispatch` and `save`
- When navigating to these pages and hitting `Create` these are available and everything works fine
- When refreshing on these pages and hitting `Create` there's a failure of type `value.<x> is not a function`
- It looks like the object in those cases is not a `Proxy` but the target itself
- Seen when creating a Chart Repo (catalog.cattle.io.clusterrepo)

**Steps to reproduce when SSR is enabled in non-production environments**
1. Nav to Cluster Explorer --> Chart Repositories 
2. Refresh the page
3. Click Create
4. Fill in details
5. Click Create
6. Resource fails to be created, red error banner shown at bottom of form

**Steps to also confirm**
Same as above, but do not refresh the page

**Comment by anupama2501** [comment]
^^ reopening to test another scenario

**Comment by anupama2501** [comment]
Verified on v2.5.6:
From cluster explorer --> chart repositories --> refresh the page and create chart by providing all the details [No issue seen]
From cluster explorer --> chart repositories --> do not refresh the page and create chart by providing all the details [No issue seen]
