### ISSUE TITLE
Hide workloads owned by others when creating a HPA

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2372]
- Workloads that have an owner, such as ReplicaSets owned by Deployments, should be hidden when creating a HPA
- There's similar code when viewing the Workloads list

> Note!
Need to handle the case where a HPA has an invalid workload type, specifically when it's display or edited. So something like..
```
- Add the current value to the dropdown options so that it's available and will end up selected
- Add :taggable, and a warning if the name you enter doesn't match anything (Ingress has some examples of this)
- Refuse to edit this resource (not really appropriate here, but some of the more complex types will just say sorry the UI doesn't support this resource's options, go use YAML)
```

**Comment by catherineluse** [comment]
Is this issue still relevant? I checked the HPA form but didn't see any reference to ReplicaSets. Are you saying that sometimes they could show up in the Target dropdown?
<img width="1309" alt="Screenshot 2022-11-04 at 5 39 13 PM" src="https://user-images.githubusercontent.com/20599230/200093116-423d3813-93f7-403e-830b-5f151f8f8642.png">
<img width="1309" alt="Screenshot 2022-11-04 at 5 39 13 PM" src="https://user-images.githubusercontent.com/20599230/200093124-a6a49b24-4c01-4811-ba21-463cd540aa90.png">

**Comment by richard-cox** [comment]
This is still an issue

![image](https://user-images.githubusercontent.com/18697775/200542203-9cbe7a8c-47d2-4297-96d2-9626793a2842.png)

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: dadb4c0), I was unable to see replicasets created by a different user when following the Steps to Reproduce. Therefore I am closing this ticket.

**Steps to Reproduce:**
1. Spin up a Rancher server
2. Create a Standard User
3. Create a downstream cluster by both the Standard User and the Admin user
4. Create new replicasets under each of the clusters by each of the Users respectively
5. Expand the _Target Reference_ dropdown when attempting to create an HPA under each of the clusters
   - Note that you can only see the replicasets created by the current User
6. Create a second downstream cluster under with the Admin User and follow steps 4-5 for that cluster
    - Note that you can see both the replicasets created on that cluster and on the other cluster created by the Admin User, but the Admin User cannot see the the replicasets created by the Standard User, and the Standard User cannot see the replicasets created by the Admin User

**`v2.7-head` (Commit ID: dadb4c0) Standard User after replicasets were created by both Admin and Standard Users:**
![image](https://user-images.githubusercontent.com/13294321/208197175-91a4cae2-e7b8-4a4b-aa12-1dd0c491d7d9.png)

**`v2.7-head` (Commit ID: dadb4c0) Admin User after replicasets were created by both Admin and Standard Users:**
![image](https://user-images.githubusercontent.com/13294321/208197435-4546425f-b68a-44e8-b19e-a3af3749104d.png)
