### ISSUE TITLE
Secret type not shown in import YAML

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#2379]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a file for resource type  `Secret`
```
apiVersion: v1
data:
  key: dmFsdWU=
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:key: {}
      f:type: {}
    manager: rancher
    operation: Update
  name: testsecret
  namespace: default
type: Opaque

```
Navigate to dashboard.
Import YAML
![Screen Shot 2021-02-22 at 5 59 43 PM](https://user-images.githubusercontent.com/57409052/108789591-d14bf800-7537-11eb-9017-0c5141f41e94.png)
Import using file.

**Result:**
Secret type is not shown. Should be seen as `Opaque`
![Screen Shot 2021-02-22 at 4 47 17 PM](https://user-images.githubusercontent.com/57409052/108791477-681ab380-753c-11eb-8422-79ddca93e8d0.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5-head` `b4be2b2 `
- Installation option (single install/HA): single install

**Comment by nwmac** [comment]
Related to this - if you click on the name in the table after creation, you get a full screen error message 'Cannot read property 'doneOverride' of null' - the URL it is going to is:

https://127.0.0.1:8005/c/local/explorer/Opaque/testsecret

where it should be:

https://127.0.0.1:8005/c/local/explorer/secret/default/testsecret

**Comment by aaronRancher** [comment]
This issue is still seen in `rancher\rancher:v2.5-head` `version 87006de` 
Steps are the same as above, including the YAML.

User cannot see secret type.
![Screen Shot 2021-02-25 at 2 28 50 AM](https://user-images.githubusercontent.com/57409052/109136993-f1d1a900-7715-11eb-8f93-917bc2887bf7.png)
Clicking on the link to the newly created secrets results in the page stuck in loading:
![Screen Shot 2021-02-25 at 2 29 53 AM](https://user-images.githubusercontent.com/57409052/109136983-eed6b880-7715-11eb-9667-72ee05bfd3f3.png)

**Comment by vincent99** [comment]
Sigh; the backend change is in master but not 2.5-head.  https://github.com/rancher/rancher/pull/31450

**Comment by cbron** [comment]
Available in 2.5-head build

**Comment by brendarearden** [comment]
Tested using the following steps: 
1. Deployed single install rancher/rancher:2.5-head
2. Navigated to the Cluster Explorer dashboard
3. Used `Import yaml` to import a `kind: Secret` resource (used secret yaml provided in the issue)
4. Type is now showing as `Type:  Secret`
![Screen Shot 2021-02-26 at 4 11 47 PM](https://user-images.githubusercontent.com/19455540/109364998-56435400-784d-11eb-8ed4-3b4ab79e340f.png)
5. Navigating to the Secrets list page, the Type is showing as `Type: Opaque`
![Uploading Screen Shot 2021-02-26 at 4.14.56 PM.png…]()

Re-opening - should be showing as `Type: Opaque`

**Comment by vincent99** [comment]
This is correct, the words mean the opposite in K8s vs our UI/API because...reasons...

Import may be loading many different kinds of resources so it shows the top-level Type (which is the `kind` k8s field on every resource).  The Secrets list is all secrets so the column is the specialization/subtype/kind/_type (which k8s calls `type` on only some kinds of resources)

**Comment by brendarearden** [comment]
With the additional information Vince provided we can go ahead and close this as fixed. Import for Secret showing the top-level type on import.
