### ISSUE TITLE
Create PVC from PV fails

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2380]
**On 2.5-head - commit id: `a85f4d1f8`**

- Create an Amazon EBS PV - using volume id
- Create a PVC from this PV. The pvc is stuck in Pending with error seen from Amber UI: `Cannot bind to requested volume "pvc-from-pv": storageClassName does not match`
- Request sent in Dashboard ui:
```
{type: "persistentvolumeclaim", metadata: {namespace: "default", name: "pvc-from-pv"},…}
metadata: {namespace: "default", name: "pvc-from-pv"}
name: "pvc-from-pv"
namespace: "default"
spec: {accessModes: ["ReadWriteOnce"], volumeName: "pv1", resources: {requests: {storage: "10Gi"}}}
accessModes: ["ReadWriteOnce"]
0: "ReadWriteOnce"
resources: {requests: {storage: "10Gi"}}
requests: {storage: "10Gi"}
volumeName: "pv1"
type: "persistentvolumeclaim"
```
- Request sent in Amber UI:
```
{type: "persistentVolumeClaim", accessModes: ["ReadWriteOnce"], name: "pvc-pv-amber", volumeId: "pv1",…}
accessModes: ["ReadWriteOnce"]
0: "ReadWriteOnce"
name: "pvc-pv-amber"
namespaceId: "default"
resources: {requests: {storage: "10Gi"}}
requests: {storage: "10Gi"}
storage: "10Gi"
storageClassId: null
type: "persistentVolumeClaim"
volumeId: "pv1"
```

**Comment by codyrancher** [comment]
@sowmyav27 I'm trying to reproduce buy I'm not running into the same issue as you.

Are you doing something different than this?
![pvc](https://user-images.githubusercontent.com/55104481/108875543-89ba8000-75ba-11eb-8f8f-05e3efd37c2a.gif)

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `30e53bd`**

- Create an Amazon EBS PV - using volume id
- Create a PVC from this PV. The pvc becomes Active
- Deployed a workload and attached this PVC. workload is up and Active. Able to access the volume on an exec in the pod
