### ISSUE TITLE
Issue in Details page of PVC

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2383]
**On 2.5-head - commit id: `a85f4d1f8`**

- On an EKS cluster, Create a PVC - `test` from storage class gp2
- Save this PVC
- Click on the PVC to go to the details page
- Source selected is not obvious from the UI
<img width="1412" alt="Screen Shot 2021-02-22 at 9 51 41 PM" src="https://user-images.githubusercontent.com/26032343/108807104-5fd07180-7558-11eb-8c81-6e896f44dc3f.png">

**Expected:**
Can the selected source be made more clear on the UI ?

**Comment by nwmac** [comment]
I don't think we have time to fix this for 2.5.6 - this is a minor issue and is to do with the way we use disabled presentation for controls when in view mode lie this - we'll revisit how best to do this in 2.5.7.

**Comment by nwmac** [comment]
This should now be improved - fix was already in - the selected option will have brighter text and be easier to see.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `b2a34d7 `**

- Selected source of Volume Claim on a PVC is more obvious now
<img width="1122" alt="Screen Shot 2021-03-31 at 8 05 52 PM" src="https://user-images.githubusercontent.com/26032343/113238074-e154a700-925c-11eb-87bf-4b99cd39f322.png">
