### ISSUE TITLE
Issues in "Configure who should be able to login and use Rancher" Section in Azure AD

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2384]
**Verified on 2.5-head commit if: `a85f4d1 `**

- In dashboard, enable AD Auth -- Standard option.
- In the "Configure who should be able to login and use Rancher" section

**Issue#1**
- Typo in "Authorized" in `Restrict access to only Auhorized Users and groups`

<img width="1421" alt="Screen Shot 2021-02-22 at 10 04 09 PM" src="https://user-images.githubusercontent.com/26032343/108808705-079b6e80-755c-11eb-8095-56a7bc635110.png">

**Issue#2**
- Can we have a title/heading for this section like how we have in Ember UI - Authorized users and groups? 

<img width="1421" alt="Screen Shot 2021-02-22 at 10 04 09 PM" src="https://user-images.githubusercontent.com/26032343/108808652-f0f51780-755b-11eb-9c50-12c27fc0f87a.png">

**Comment by nwmac** [comment]
PR with fix: https://github.com/rancher/dashboard/pull/2388

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `a85f4d1 `**

- Heading and the Type are fixed
<img width="1678" alt="Screen Shot 2021-02-23 at 9 23 43 AM" src="https://user-images.githubusercontent.com/26032343/108882414-37c52a80-75b9-11eb-9858-00cacbc3110c.png">
