### ISSUE TITLE
Design issues with Ports config on the Workload Create UI

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2386]
See PR rancher/dashboard#2332

There are some issues with the height of the dropdown for the port type selector and for numeric input boxes where the up/down controls overlap the units display at the right of the control.

We might want to look at the Ports UX anyway, as it requires quite a lot of horizontal space.

**Comment by catherineluse** [comment]
Is this still applicable since the workload create UI was redesigned?

**Comment by catherineluse** [comment]
While we're on this topic, I don't think "Do not create a service" should be a choice you can pick from in the Service Type dropdown, because that is not a service type.

**Comment by nwmac** [comment]
Stale
