### ISSUE TITLE
CronJob view: Always show Job tab

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2390]
In the view for a Cronjob (show below), we only show the Jobs tab when there are actually jobs - this means that when you first create a CronJob, the "Related Resources' tab is the active tab, so as the job is scheduled, you don't see it automatically - I think it would be better to always show the Jobs tab and for this to be the default tab for this view.

![CronJob](https://user-images.githubusercontent.com/1955897/108854505-dcf2f980-75df-11eb-8f7e-0beea28c4f2d.png)

**Comment by thehejik** [comment]
**Test report:**
* successfully reproduced the issue on `rancher:2.5.5` - Jobs tab is not visible immediately after creating a `CronJob` and selecting its name
* on rancher:2.5.6-rc2 the `Jobs` tab is visible immediately after creating a `CronJob` and selecting its name
* on rancher:master-head `b202f20` the `Jobs` tab is visible immediately after creating a `CronJob` and selecting its name

Works as expected, closing.
