### ISSUE TITLE
Misalignment in "Configure who should be able to login" section for AzureAD Auth

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2398]
**On 2.5-head commit id: `a85f4d1`**

The options below "Configure who should be able to login" Seem to be slightly higher than the Authorized Users & Groups section on the right. Can they both be aligned to the same level ? 

<img width="1678" alt="Screen Shot 2021-02-23 at 9 23 43 AM" src="https://user-images.githubusercontent.com/26032343/108882755-99859480-75b9-11eb-81be-9c93b5796b58.png">

**Comment by lvuch** [comment]
This should appear below the radios versus to the right

**Comment by lindhe** [comment]
Also, the users are misaligned for certain screen sizes:

<img width="394" alt="Screenshot 2023-10-11 142616" src="https://github.com/rancher/dashboard/assets/7773090/c6425e89-d655-449d-af80-265c2bdf5e42">
<img width="876" alt="Screenshot 2023-10-11 142558" src="https://github.com/rancher/dashboard/assets/7773090/3b1d3776-3482-4846-8fbe-17d067145e69">

**Comment by nwmac** [comment]
I believe this has been addresses

**Comment by lindhe** [comment]
Indeed it has! Very nice! 👍
