### ISSUE TITLE
[Monitoring V2] tls_config and authentication documentation

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#2400]
We need to add either helper text in the UI or documentation surrounding the tls_config and authentication fields that were added.

More details can be found in the comments here https://github.com/rancher/dashboard/issues/1818#issuecomment-737484788

**Comment by codyrancher** [comment]
Added this documentation

![image](https://user-images.githubusercontent.com/55104481/111806700-7df76c00-888f-11eb-9801-01fd5a310c1b.png)

**Comment by slickwarren** [comment]
I made [this ticket](https://github.com/rancher/docs/issues/3154) for documentation. 
 I feel like there should be more information here to help the user know what to do.  I think we should wait for documentation to land, and link to it in the message is already here, so if the user doesn't know how to edit the yaml, there are clear instructions on what to do next. That would be the most concise way to do it imo. 

**I will reopen for now, dev will need to wait for docs changes to land, then add a link to the docs to the UI**

**Comment by slickwarren** [comment]
<img width="1117" alt="Screen Shot 2021-05-27 at 9 57 53 AM" src="https://user-images.githubusercontent.com/16691014/119866792-09b1f800-bed2-11eb-9a06-53f38446b5e3.png">

on master-head (629146a) , we now include a link to documentation in ssl instructions (i.e. monitoring -> receivers -> webhook)
