### ISSUE TITLE
Namespace resource defaults to 0

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2401]
Spotted in Rancher 2.5.3: when you create a new namespace, the limits are left at a default of 0. This should default to simply being empty and omit the keys in the annotation value if not set. 

This has a ripple effect whereby an install has failed b/c namespace defaulted to 0 on limits and actually set that as the limit.

**Comment by sowmyav27** [comment]
**On 2.5.8-rc2**

- Reproduced the issue.
- The default values while creating a namespace is 0

<img width="848" alt="Screen Shot 2021-04-11 at 1 34 04 PM" src="https://user-images.githubusercontent.com/26032343/114320455-dc002380-9aca-11eb-97a2-54f3c25d43d2.png">

**On 2.5-head commit id: `9b0058c `**

- The default values are blank (no values0 and no values are sent when left as default values while creating a namespace
<img width="1423" alt="Screen Shot 2021-04-11 at 1 34 08 PM" src="https://user-images.githubusercontent.com/26032343/114320449-d9053300-9aca-11eb-88c2-3a06701697b1.png">
