### ISSUE TITLE
Window Manager: closing a shell/logs tab doesn't auto-select another shell/logs tab

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2403]
In Rancher 2.5.3, closing a background tab causes the active tab to stop reporting information until it’s clicked again.

**Comment by sowmyav27** [comment]
**On 2.5.7**

Reproduced the issue
- Deploy a downstream cluster
- Go to cluster explorer
- Click on "Shell". Shell window opens. Leave this window open
- Deploy CIS app on this cluster.
- The apps logs window is opened.
- Close this window. The Earlier "shell" window is not auto selected

**On 2.5.8-rc6**
