### ISSUE TITLE
Global Settings -Feature Flags is out of sync between Dashboard and Cluster Management UI

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#2421]
bug on v2.5-head 87006de

We can activate or deactivate features on both the dashboard and cluster management UI, but the states of features are not synced between those two UIs.

For example, deactivating the `istio-virtual-service-ui` on the dashboard does not change its state in cluster management UI. 

This happens to all three existing feature flags.

**Comment by nwmac** [comment]
I can't reproduce this issue - the states do stay in sync - note that in the Ember UI,they show as disabled where as in the new UI they show as inactive - I have changed this so that the new UI also shows disabled.

**Comment by jiaqiluo** [comment]
Hi @nwmac  I see  `inactive` became `disabled` in Dashboard UI, but I still see the bug in my setup. 

the following screen is after I disabled `istio-virtual-service-ui` in the Ember UI
<img width="1667" alt="Screen Shot 2021-02-25 at 11 20 47 AM" src="https://user-images.githubusercontent.com/6218999/109199055-3718c980-775c-11eb-99eb-ebd9fa1df503.png">
 

the following screen is after I disabled `istio-virtual-service-ui` in the Dashboard UI
<img width="1663" alt="Screen Shot 2021-02-25 at 11 21 37 AM" src="https://user-images.githubusercontent.com/6218999/109199102-46981280-775c-11eb-86e3-175864d134c8.png">

In both cases, I have refreshed both pages multiple times to make sure it gets the latest values from the server
