### ISSUE TITLE
Auth Providers - ADFS hasn't the Entity ID field in Ember Ui but it's present in Dashboard

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2422]
Rancher version `v2.5-head (02/24/2021)` _87006de_

ADFS SAML auth doesn't have the Entity ID field in EmberUI 
This field is available however in the Dashboard Auth and Users.

![Screen Shot 2021-02-24 at 12 43 51 PM](https://user-images.githubusercontent.com/27659/109056740-12f6b300-769e-11eb-8c14-4c08d6537f4b.png)

![Screen Shot 2021-02-24 at 12 43 33 PM](https://user-images.githubusercontent.com/27659/109056693-fce8f280-769d-11eb-930c-958b6c34a299.png)

**Comment by izaac** [comment]
As this is an optional field can we have confirmation that we want it in even if it's not in Ember?

**Comment by anupama2501** [comment]
Verified on v2.5-93d921f36e2d38478aedbabf9c3604115e4bdded-head
Entity-ID field from cluster explorer --> Auth Providers --> ADFS --> details is not shown 
<img width="500" alt="Screen Shot 2021-04-06 at 4 06 27 PM" src="https://user-images.githubusercontent.com/38144301/113788559-1136fb00-96f2-11eb-95b9-5d43032772f4.png">
