### ISSUE TITLE
2.5.5 "There are no charts available, have you added any repos?"

### ISSUE THREAD

**Issue by alexmnyc** [rancher/dashboard#2428]
i cannot install any apps from Rancher as none show up

![image](https://user-images.githubusercontent.com/1847565/109084638-87e9dd00-76de-11eb-9093-0e4d03137e81.png)

![image](https://user-images.githubusercontent.com/1847565/109084661-920bdb80-76de-11eb-81c6-c09ef76340ab.png)

**Comment by vincent99** [comment]
As I believe was discussed with you in Slack, k8s 1.20 is not supported by Rancher 2.5.5.

**Comment by alexmnyc** [comment]
Correct. Thanks, Vincent!
