### ISSUE TITLE
Dashboard longhorn storage class issues

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2429]
Rancher | v2.5-a85f4d1f87feea0083ebf8ae517a140f39de7fbd-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher51
 
From the cluster explorer --> Storage class --> provider [longhorn] with default values, create storage class

**Issue1:**
Parameters "Key" should be a mandatory field
**Issue2:**
In the customize tab, "Allow Volume Expansion", should have "Enabled" as default value.
**Issue3:**
Once the storage class is created, in customize tab, "Allow Volume Expansion" and "mount options" should be editable.

**Issue4:**
1. From the cluster explorer --> Storage class --> provider [longhorn] with default values, create storage class
2. From the persistent volume claims --> Add storage class from step1 in the volume claim and create
3. The pv claim is stuck in pending with the error: 
`failed to provision volume with StorageClass "anpama-test": rpc error: code = Internal desc = Invalid parameter recurringJobs: invalid json format of recurringJobs: unexpected end of JSON input
`
After removing the value "recurringJobs" from the storage class parameters, the volume claim has become active.

Screen shots for reference:
<img width="400" alt="Screen Shot 2021-02-24 at 4 54 39 PM" src="https://user-images.githubusercontent.com/38144301/109086927-557db700-76c1-11eb-9b98-c9f27af31f9b.png">

From the network logs:
on Dashboard:
```
 "parameters":{
      "diskSelector":"",
      "fromBackup":"",
      "nodeSelector":"",
      "numberOfReplicas":"3",
      "recurringJobs":"",
      "staleReplicaTimeout":"2880"
   },
```

on UI when :
```
"parameters":{
      "numberOfReplicas":"3",
      "staleReplicaTimeout":"2880"
   },
```

**Comment by codyrancher** [comment]
**Issue 1:** I don't think we should add this. All the keys aren't required seeing as you had to delete `recurringJobs` to make this work with the PV. It's also possible to save with no parameters in both ember and dashboard.

**Comment by anupama2501** [comment]
Rancher | v2.5-361d3a420bb0d08763d157cd5fd1dfc37a3ccf29-head
Issue2:
In the customize tab, "Allow Volume Expansion", has "Enabled" as default value

Issue4:

From the cluster explorer --> Storage class --> provider [longhorn] with default values, create storage class
From the persistent volume claims --> Add storage class from step1 in the volume claim and create
The pv claim created without any error.
After removing the value "recurringJobs" from the storage class parameters, the volume claim has become active as well.

**Comment by anupama2501** [comment]
Issue3 Once the storage class is created, in customize tab, "Allow Volume Expansion" and "mount options" should be editable.

The "Allow Volume Expansion" and mount options are editable but the "save" button is missing to change the edited config.

<img width="500" alt="Screen Shot 2021-02-25 at 3 28 32 PM" src="https://user-images.githubusercontent.com/38144301/109233116-29743b80-777e-11eb-9668-c20f457d72c0.png">



Reopening the ticket for this ^^^ issue

**Comment by anupama2501** [comment]
Verified on 
Rancher | v2.5-a420b5195dd1d0a23411b0aeb17713f291e90e10-head

1. Install Longhorn in the Storage project
2. Once the installation goes through, create a Storage class with provisioner Longhorn.
3. Edit the config in the customize tab for volume expansion and mount option and click on save. 
4. Create a PVC with the above storage class selected. Volume is shown in the longhorn UI
