### ISSUE TITLE
Cannot create service with image or GH repo

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#243]
2 things, but related:

- [ ] **If using an image: It just doesn't send the image field anymore in the request** (although nothing technically fails in the backend so it returns 201, but the service never becomes available).

---

- [ ] **If using a repo: It gives an error in the UI whether selecting the template checkbox or not**: ` { "code": "Invalid", "message": "Service.rio.cattle.io \"ghui-gm6k8\" is invalid: spec.build.template: Invalid value: \"boolean\": spec.build.template in body must be of type string: \"boolean\"", "status": 422, "type": "error" }` .
**I believe that the `template` field in the request should be in `spec.template` instead of `spec.build.template`**. Example request: `{"type":"rio.cattle.io.v1.service","kind":"Service","apiVersion":"rio.cattle.io/v1","metadata":{"annotations":{},"namespace":"default","generateName":"ghui-"},"spec":{"version":"v0","weight":10000,"imagePullPolicy":"Always","env":[],"dnsNameservers":[],"searches":[],"dnsPolicy":"Default","permissions":[],"globalPermissions":[],"rollout":{"pause":false},"app":"ghui","build":{"branch":"master","repo":"https://github.com/rancher-max/rio-demo.git","dockerfile":"Dockerfile","template":false},"ports":[{"name":"","expose":true,"protocol":"HTTP","port":8080,"targetPort":8080,"hostPort":false}]},"annotations":{}}`

**Comment by nwmac** [comment]
Rio is no longer supported.
