### ISSUE TITLE
Dashboard AD/OpenLDAP/FreeIPA upgrade errors

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2432]
Rancher | v2.5-87006de30625c046523a329b03ea2580db35fb57-head

Addressing 2 issues in this ticket

**Issue1**

- Enable auth on rancher - v2.5.5 from auth providers on ember UI
- Upgrade the build to v2.5-head
- From the dashboard auth providers, the AD/FreeIPA/OpenLDAP are active
- Click on edit config/Disable config throws error:
<img width="500" alt="Screen Shot 2021-02-24 at 10 30 16 PM" src="https://user-images.githubusercontent.com/38144301/109112666-e23f6980-76ef-11eb-862f-cd76adfd99bc.png">

`{"type":"error","links":{},"code":"InvalidCSRFToken","message":"Invalid CSRF token","status":422,"type":"error"}
`

**Issue2**

- Install rancher v2.5.5
- Upgrade to rancher v2.5-87006de30625c046523a329b03ea2580db35fb57-head
- Enable AD/OpenLDAP/FreeIPA by providing the required details
- Auth fails with the same error as above:
```
{"baseType":"error","code":"InvalidCSRFToken","message":"Invalid CSRF token","status":422,"type":"error"}
{"type":"error","links":{},"code":"InvalidCSRFToken","message":"Invalid CSRF token","status":422,"type":"error"}
```

https://github.com/rancher/dashboard/issues/2114

**Comment by anupama2501** [comment]
Before upgrade version **2.5.6** 
after upgrade **version v2.5-head[v2.5-51253e556b6cc3d9b285b559c4ff043e2301d687-head]**

**Test case1:**

1. Create a cluster with 1 etcd, 1 cp and 3 worker nodes
2. Enable auth providers from the ember UI
3. Upgrade the rancher version to latest v2.5-head[v2.5-51253e556b6cc3d9b285b559c4ff043e2301d687-head]
4. Issue 'crf token mentioned in the description is not seen'
5. Edit the auth provider enabled from the step2 through cluster --> cluster explorer -> Users and Auth providers

Test case2:
Create a cluster with 1 etcd, 1 cp and 3 worker nodes
Upgrade to latest 2.5-head[v2.5-51253e556b6cc3d9b285b559c4ff043e2301d687-head]
Enable authentication from the cluster --> cluster explorer --> Users and Auth providers --> enable AD and logout, login as a standard user.

Issue is not reproducible in the above two cases. So, closing this issue and will re-open if the issue is seen again

**Comment by vincent99** [comment]
I ran into what this was.. The cookie parser attempts to parse the value as JSON by default and returns the string if it fails to parse.

Most of the time this doesn't matter, but if the CSRF value happens to be all numbers except an `e` somewhere in the middle (e.g. `841e840671`) then that is valid JSON for a _number_ in scientific notation... 841 * 10^840671.  Which will not necessarily stringify back to the same value when sent as the `x-api-csrf` header, so the server sees they don't match and (correctly) rejects the request.

I changed it to not try to do JSON parsing in this case.

It's not easy to calculate but the chances of this happening on its own are on the order of 1 in 2000.  To test this, use the dev tools Application tab -> Cookies -> <your domain> tab, you can directly set the cookie value there.  Then watch for the same value to go out the `x-api-csrf` header on any post.

**Comment by anupama2501** [comment]
On v2.5-41f173ae93c6692f44054fe0b02ce93bd3056a9f-head

From developer tools --> application tab --> cookies --> changed the csrf token with letter e

- Verified the header has the x-api-csrf reflect the same value set above
- From cluster explorer --> Users and authentication --> Auth providers --> OpenLDAP --> enable auth --> goes through without any issues 

On 2.5.7 enable auth from global --> Authentication 
Upgrade to the v2.5-41f173a and changed the cookie as above --> edit the config values and no errors are seen
