### ISSUE TITLE
Standard User sees options to activate/deactivate feature flags

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2439]
Standard users don't have permission to activate/deactivate feature flags, but the UI shows them these options (the backend will fail the requests correctly).

The UI should not show these options.

**Comment by jiaqiluo** [comment]
reopen the issue on v2.5-head f9b93ea

The standard user can still see the options to activate/deactivate feature flags in the dashboard. Although the UI shows he can activate/deactivate, actually nothing is changed in the backend, only the UI shows the wrong state. 

@nwmac The standard user can see

**Comment by nwmac** [comment]
I can't reproduce this - as a standard user, if I click on the action menu icon for a feature, I am not presented with the option to activate or deactive - as shown below:

![FF](https://user-images.githubusercontent.com/1955897/109295531-d0acad80-7826-11eb-948a-9fea9b6351e4.png)


Note: We will look to hide the action button altogether in this situation in a future release

**Comment by jiaqiluo** [comment]
The bugfix is validated on the rancher v2.50-head 1b5aad6 with the latest UI

Now the standard user can not see any options for feature flags.

![image](https://user-images.githubusercontent.com/6218999/109330516-f7fc7e00-7818-11eb-914c-dc57501eaf63.png)
