### ISSUE TITLE
Quantity field missing unit or %  to quantity based on metric type and values are not saved correctly in the backend

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2442]
**Issue#1**
Quantities end in m in amber UI, but not in new UI in kubectl describe hpa <hpa_name>

<img width="285" alt="Screen Shot 2021-02-25 at 11 18 05 AM" src="https://user-images.githubusercontent.com/16691014/109205393-5ebb6200-775b-11eb-872b-30313b233611.png">

**expected** 
`100m/10m` and `2847539200m/250m`

**Issue#2**

- the old UI has a % or `milliCPU` in `quantity`, but this is not in the new UI, so it is unclear to the user which field is which. 
- average value -> unit for cpu/memory
- average utilization -> percentage
<img width="1264" alt="Screen Shot 2021-02-25 at 8 41 33 AM" src="https://user-images.githubusercontent.com/16691014/109186053-6b34c000-7745-11eb-8331-219933c19224.png">

<img width="1319" alt="Screen Shot 2021-02-25 at 8 41 03 AM" src="https://user-images.githubusercontent.com/16691014/109186060-6bcd5680-7745-11eb-996a-181226c56826.png">

<img width="1378" alt="Screen Shot 2021-02-25 at 8 40 58 AM" src="https://user-images.githubusercontent.com/16691014/109186064-6c65ed00-7745-11eb-8444-1998d28783a7.png">

**Comment by westlywright** [comment]
In the case of CPU we send `m`, for Memory we send `Mi`, and for utilization we send just the number without the SI suffix.

**Comment by slickwarren** [comment]
on rancher v2.5-head (67228a3) I was able to verify the cpu sends `m`, memory sends `Mi` and other types we send only the value. This is reflected both in the api request:
<img width="349" alt="Screen Shot 2021-02-27 at 12 47 16 PM" src="https://user-images.githubusercontent.com/16691014/109399842-0c647780-78fa-11eb-8695-be605d28f895.png">
 as well as on the cluster through kubectl:
<img width="579" alt="Screen Shot 2021-02-27 at 12 44 28 PM" src="https://user-images.githubusercontent.com/16691014/109399843-0d95a480-78fa-11eb-876d-ba19a666fcaa.png">
which is what we would expect (and matches what happens for ember UI requests)
here is the UI with the resource types included in the `quantity` field 
<img width="701" alt="Screen Shot 2021-02-27 at 12 49 29 PM" src="https://user-images.githubusercontent.com/16691014/109399882-5cdbd500-78fa-11eb-93be-d0b9270e3d7f.png">
