### ISSUE TITLE
Dashboard PV longhorn customization tab operator for node-selector to be changed

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2449]
Rancher | v2.5-a85f4d1f87feea0083ebf8ae517a140f39de7fbd-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher51

Cluster explorer --> Persistent volumes --> plugin : longhorn --> customize tab operators for node selector to be changed to [in list, is set, is not set, is not in list] as on ember UI

**Dashboard:**
<img width="500" alt="Screen Shot 2021-02-24 at 1 42 58 PM" src="https://user-images.githubusercontent.com/38144301/109069562-3d4c6e80-76a6-11eb-9873-506e2e1976cb.png">

**On ember UI:**
<img width="500" alt="Screen Shot 2021-02-24 at 1 42 49 PM" src="https://user-images.githubusercontent.com/38144301/109069642-5a813d00-76a6-11eb-9498-573d4e48bb0d.png">

**Comment by nwmac** [comment]
@codyrancher How much work is this?

**Comment by codyrancher** [comment]
Not very much.

**Comment by codyrancher** [comment]
### For QA
I switched over to the ember verbiage but I left in the `> and <` operators.

**Comment by anupama2501** [comment]
Verified on **5715b8a**
1. Created a cluster rke2 node driver DO 1 node all roles from cluster explorer
2. From explore cluster --> core --> Persistent Volumes -> Created a longhorn PV and from customize tab, verified the operator is changed as follows:
<img width="200" alt="Screen Shot 2021-06-14 at 12 31 50 PM" src="https://user-images.githubusercontent.com/38144301/121948763-833c4980-cd0c-11eb-88cf-76a96827c04f.png">
3. Selected the value with ` in list `  with a key and value and was able to create the persistent volume for longhorn
