### ISSUE TITLE
storage pages pv, sc, pvc - create

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#245]

**Comment by lvuch** [comment]
https://xd.adobe.com/view/009f6a98-7698-4618-60c4-3515aafe0be0-76ae/

**Comment by lvuch** [comment]
pvc: https://xd.adobe.com/view/f449481a-fafc-4237-7597-8de9b8846771-8278/
sc + pv: https://xd.adobe.com/view/009f6a98-7698-4618-60c4-3515aafe0be0-76ae/

**Comment by deniseschannon** [comment]
Closing in favor of #274

**Comment by lvuch** [comment]
Links updated per tani's feedback via slack: "For PVC, Related Workloads should be a table above the tabs and not in the tabs., Same with Storage class, the PV table should be outside the tabs."
