### ISSUE TITLE
Dashboard persistent volume claim for storage class missing the "Use the default class"

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2452]
Rancher | v2.5-361d3a420bb0d08763d157cd5fd1dfc37a3ccf29-head

From the cluster explorer --> Persistent volume claims --> create PVC --> select "Use a Storage Class to provision a new Persistent Volume" --> In the storage class drop down, the option "Use the default class" is missing.
When the default class is selected when longhorn is installed  --> the default class is considered as longhorn

Ember UI:
Options for "Storage Class"
<img width="500" alt="Screen Shot 2021-02-25 at 4 37 39 PM" src="https://user-images.githubusercontent.com/38144301/109238167-e4ed9d80-7787-11eb-8672-7e2a10bc93cb.png">

PVC when "Use the default class" is selected:
<img width="500" alt="Screen Shot 2021-02-25 at 4 37 55 PM" src="https://user-images.githubusercontent.com/38144301/109238240-0484c600-7788-11eb-889f-ddd1cd774b59.png">

**Comment by gaktive** [comment]
@deniseschannon should this be for 2.5.7 then? Does this impact the overall feature for 2.5.6?

**Comment by deniseschannon** [comment]
We bumped it out but needs to be added in for 2.5.7

**Comment by anupama2501** [comment]
Verified on v2.5-d1083bc63e4ddde70ffadd09bf0133ae5862b5fe-head

- Create a cluster with 3 worker, 1etcd,1cp
- From the cluster explorer --> install longhorn from apps in the cluster created above
- From the cluster explorer --> Persistent volume claims --> create PVC --> select "Use a Storage Class to provision a new Persistent Volume" --> In the storage class drop down, select the option "Use the default class".
- Once created, longhorn is selected as the default storage class
- The same is shown in the longhorn UI as well. 

<img width="300" alt="Screen Shot 2021-04-12 at 9 16 34 AM" src="https://user-images.githubusercontent.com/38144301/114427525-022bcf00-9b70-11eb-8038-050e305e657c.png">
