### ISSUE TITLE
PVC create has Related Resources section

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2453]
**On 2.5-head commit id: `30e53bd `**

- In Dashboard, create a PVC.
- Related Resources section is available

<img width="1075" alt="Screen Shot 2021-02-25 at 7 22 04 PM" src="https://user-images.githubusercontent.com/26032343/109250666-e4accc80-779e-11eb-8dec-b33f82f4288c.png">

**Comment by brendarearden** [comment]
Tested using the following steps: 
1. Deployed single install rancher/rancher:v2.5.6-rc6
2. Navigate to PVC Create page in the Cluster Explorer dashboard
3. The Related Resource section is not shown on create: 
![Screen Shot 2021-02-26 at 3 54 49 PM](https://user-images.githubusercontent.com/19455540/109364086-390d8600-784b-11eb-90a7-40e697cbb753.png)
4. After creating, clicked on the PVC list page to navigate to view page. 
5. You can see the Related Resources section:
![Screen Shot 2021-02-26 at 3 58 08 PM](https://user-images.githubusercontent.com/19455540/109364166-6c501500-784b-11eb-88ec-c3385c473f65.png)

Closing as Fixed - The PVC create no longer has the Related Resources section
