### ISSUE TITLE
Confirm that 2.5.6 has hidden Sidecars for Workloads and Users & Auth

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2465]
Since we pushed both those features in Vue for 2.5.7, we need to QA to confirm that they are in fact hidden.

**Comment by anupama2501** [comment]
Rancher | v2.5-67228a3cdba34161e1e03a4639b9c5b445e7b81b-head
Users and auth hidden:

<img width="250" alt="Screen Shot 2021-02-26 at 3 03 23 PM" src="https://user-images.githubusercontent.com/38144301/109364633-0f9d2c00-7844-11eb-878f-e82a809ad330.png">

Sidecars for workloads hidden:
<img width="250" alt="Screen Shot 2021-02-26 at 3 03 14 PM" src="https://user-images.githubusercontent.com/38144301/109364618-09a74b00-7844-11eb-896c-73f8c65e21a5.png">
