### ISSUE TITLE
Format target column in services page

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#2466]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Navigate to dashboard
Create a workload with a routable service.
Navigate to the services page in dashboard

**Result:**
The format of the target column is `IP:Port /TCP > 6443` for services that cannot be linked. Services that can be linked are seen as `Port/Protocol`
![Screen Shot 2021-02-26 at 1 01 00 PM](https://user-images.githubusercontent.com/57409052/109349312-fd66c200-7832-11eb-9c84-3716a58e54b7.png)

It is not clear why `>` is used here.
This is perhaps a formatter in the vue code that checks to see if a service can be linked. If not, we see this format in static text: `IP:Port /TCP > 6443`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version f9b93ea`
- Installation option (single install/HA): single install

**Comment by gaktive** [comment]
For a possible solution, we can compare with the UI under Project / Service Discovery.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version e546ffe`

Target column format has been changed. A new icon is visible which represents an internal link. `/protocol` has been moved to the end of the link. And `Type` column has been moved to the second to last column before age.
![Screen Shot 2021-06-30 at 11 45 31 AM](https://user-images.githubusercontent.com/57409052/124015191-41143880-d999-11eb-8ec6-77ca6364183f.png)
