### ISSUE TITLE
[Monitoring V2] Replace get PodMonitor requirement with get any resource in monitoring.coreos.com API group

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2469]
As described in Level 2 in https://github.com/rancher/dashboard/issues/2408, currently the following condition bars users from viewing the Monitoring pane (or whether Monitoring is installed in the cluster at all) unless they have permissions to view PodMonitors: https://github.com/rancher/dashboard/blob/6fa9190936449f8ab64be45a2eafd1bbbdd33dac/config/product/monitoring.js#L35 

This was originally a requirement introduced in https://github.com/rancher/dashboard/issues/1430#issuecomment-699167973, but should be removed for the following two reasons:
1. Since PodMonitors were introduced in the Monitoring V1 0.2.x line as part of upgrading the Prometheus Operator version, this doesn't serve the initial requirement of preventing users of Monitoring V1 from viewing Monitoring V1 in the Cluster Explorer view.
2. As described / tested in a later issue [here](https://github.com/rancher/dashboard/issues/1561#issuecomment-783668390), we have moved towards just exposing a banner that warns the user that Monitoring V1 is installed instead of preventing them from viewing Monitoring V1 CRDs in the Cluster Explorer UI at all.

This should be replaced with just checking if the user has permission to any `monitoring.coreos.com` CRD, similar to what we do here:

https://github.com/rancher/dashboard/blob/6fa9190936449f8ab64be45a2eafd1bbbdd33dac/config/product/backup.js#L17

Once this has been modified, the user with any permission on monitoring.coreos.com resources should be able to see the Monitoring Pane (e.g. only Cluster Members should not be able to see the Monitoring Pane by default).

**Comment by aiyengar2** [comment]
FYI, this issue is no longer waiting on any backend work since the scope of the fix has been modified. This is ready to be worked on.

**Comment by aiyengar2** [comment]
Since this issue is no longer a requirement of https://github.com/rancher/rancher/issues/31630 (see https://github.com/rancher/rancher/issues/31630#issuecomment-793138251), I'm removing the 2.5.7 milestone in favor of 2.5.x.

**Comment by catherineluse** [comment]
I'm closing this issue because I believe it is no longer applicable because pod monitors are no longer referenced in that part of the code:

```
product({
    ifHave:              IF_HAVE.V2_MONITORING, // evaluates to 'v2-monitoring'
    icon:                'monitoring',
    showNamespaceFilter: true,
    weight:              90,
  });
```
