### ISSUE TITLE
Deployments show resources from other namespaces in the cluster explorer

### ISSUE THREAD

**Issue by waterfoul** [rancher/dashboard#2476]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create two namespaces
2. In each namespace create a deployment with
```
  selector:
    matchLabels:
      app: deployment
```
and equivalent mod spec fields
3. Open the cluster explorer
4. Select "Only user namespaces" in the namespaces dropdown
5. View one of the two deployments

**Result:**
In the pods tab you will see all of the pods for both deployments. That tab should be scoped to the namespace that the deployment is in

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): Hosted Rancher

gz#14889

**Comment by vincent99** [comment]
This was fixed for 2.5.6.  https://github.com/rancher/dashboard/issues/2283

**Comment by aaronRancher** [comment]
PR: https://github.com/rancher/dashboard/pull/2285

Reproduced this issue with Rancher `v2.5.5`
Steps:
Create 2 namespaces.
In each namespace create a deployment with:
```
selector:
  matchLabels:
    app: deployment
```
View cluster explorer.
Select "Only user namespaces" in the namespaces dropdown
View one of the two deployments

Result:
![Screen Shot 2021-03-12 at 10 35 03 AM](https://user-images.githubusercontent.com/57409052/110977551-872c8a00-831f-11eb-9729-1e985db7faf6.png)

View in cluster manager with expected number of pods:
![Screen Shot 2021-03-12 at 10 35 55 AM](https://user-images.githubusercontent.com/57409052/110977625-9e6b7780-831f-11eb-8fee-b5a89f7496ff.png)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5.6`

View in cluster explorer shows the correct number of pods:
![Screen Shot 2021-03-12 at 10 50 07 AM](https://user-images.githubusercontent.com/57409052/110978829-15554000-8321-11eb-9702-7110ca70fe01.png)

View in cluster manager:
![Screen Shot 2021-03-12 at 10 49 09 AM](https://user-images.githubusercontent.com/57409052/110978841-18503080-8321-11eb-9dca-5ff738bf9e2b.png)
