### ISSUE TITLE
Some of the text in Chart dropdown is hidden

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2484]
**On 2.5.6-rc8**

- Go to Cluster --> Cluster explorer --> Apps and market place --> Charts -->. CIS benchmarks (for example) --> Charts dropdown 
- Repo name - Rancher/Partner is hidden, in the beginning
<img width="857" alt="Screen Shot 2021-03-03 at 6 27 31 PM" src="https://user-images.githubusercontent.com/26032343/109925501-b33c7100-7c76-11eb-96b6-6b463f309087.png">

**Comment by SheilaghM** [comment]
Verified that problem exists on v2.5.7 with K8S 1.20.5

- Go to Cluster --> Cluster explorer --> Apps and market place --> Charts -->. CIS benchmarks (for example) --> Charts dropdown

- First letter of "Rancher" and "Partners" are cut off in the dropdown.

**Comment by SheilaghM** [comment]
verified that issue is resolved on 2.5 head 6bb6c97

Go to Cluster --> Cluster explorer --> Apps and market place --> Charts -->. CIS benchmarks (for example) --> Charts dropdown

First letter of "Rancher" and "Partners" appear correctly.
