### ISSUE TITLE
[Monitoring V2] Set ingressNginx.enabled to true if cluster type is RKE1

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2485]
Set ingressNginx.enabled=true if the clusterType is detected to be RKE1 (probably just add ingressNginx [here](https://github.com/rancher/dashboard/blob/33481b2fec3b5b8982ce9500c799ae9c595e6ea1/chart/monitoring/ClusterSelector.vue#L68)?)

Awaiting backend fix from https://github.com/rancher/rancher/issues/30126.

Since this is a brand new field, it should be fine to set this to true regardless of what Rancher Monitoring version is used (since the field will just be ignored in older version).

**Comment by aiyengar2** [comment]
Should also be enabled for RKE2 clusters

**Comment by slickwarren** [comment]
tested on v2.5-head (70024998a0e95374a135177953a04f4539e2d59c):
* RKE2 -- upgrade from 9.4.202 -> 14.5.100-rc7 -- default settings -- ingress-nginx is enabled, but failures upgrading the cluster **FAIL** 
--first upgrade attempt -- 
<img width="1792" alt="Screen Shot 2021-04-14 at 12 38 12 PM" src="https://user-images.githubusercontent.com/16691014/114772542-c71dcd00-9d22-11eb-89b8-8f29fdcdb87a.png">
--attempting upgrade with no changes -- below
* also happens on clean install of RKE2 --4.5.100-rc7 -- default settings -- ingress-nginx is enabled, but failures upgrading the cluster **FAIL** -- even when manually adding the namespace, no pods are deployed to it and targets are not up in prometheus for ingress-nginx
<img width="1792" alt="Screen Shot 2021-04-14 at 12 41 07 PM" src="https://user-images.githubusercontent.com/16691014/114772533-c422dc80-9d22-11eb-87a0-3889562d81e6.png">

* RKE2 -- clean install of 14.5.100-rc5 -- ingress-nginx disabled -- pass

* RKE1 -- upgrade from 9.4.202 -> 14.5.100-rc7 -- default settings -- ingress-nginx is enabled -- pass
* RKE1 -- clean install of 14.5.100-rc7 -- default settings -- ingress-nginx is enabled -- PASS
* RKE1 -- clean install of 14.5.100-rc7 -- ingress-nginx is disabled -- PASS (there are still deployments in ingress-nginx, but prom does not have targets for ingress-nginx)
* RKE1 -- clean install of 14.5.100-rc7 -- ingress-nginx is disabled -- PASS (there are still deployments in ingress-nginx, but prom does not have targets for ingress-nginx)

all of the above are not related to the UI/dashboard, so I will open a new ticket for the above failures.

in every case above, ingressNginx was available in the UI

**Comment by aiyengar2** [comment]
Reopening this ticket since there were failed tests and it has been reopened in https://github.com/rancher/rancher/issues/32145, although the fix needs to come in from UI.

**Comment by aiyengar2** [comment]
> Should also be enabled for RKE2 clusters

@codyrancher based on the error mentioned in https://github.com/rancher/dashboard/issues/2485#issuecomment-819911804, it seems like we need to roll back the change to rke2 clusters. This should only be set to true for rke1 clusters, since rke2 clusters can be spun up without ingress-nginx. A user will need to manually enable this if they have ingress-nginx deployed for an RKE2 cluster.

**Comment by aiyengar2** [comment]
> > Should also be enabled for RKE2 clusters
> 
> @codyrancher based on the error mentioned in [#2485 (comment)](https://github.com/rancher/dashboard/issues/2485#issuecomment-819911804), it seems like we need to roll back the change to rke2 clusters. This should only be set to true for rke1 clusters, since rke2 clusters can be spun up without ingress-nginx. A user will need to manually enable this if they have ingress-nginx deployed for an RKE2 cluster.

This was incorrect, based on further discussion offline. RKE2 does have ingress-nginx deployed by default, but it is deployed in the kube-system namespace of its own namespace.

Closing back out this ticket in favor of a new one in https://github.com/rancher/dashboard/issues/2728 that tracks the namespace change.
