### ISSUE TITLE
Control buttons in logs and shell views are out of visible area

### ISSUE THREAD

**Issue by nabam** [rancher/dashboard#2488]
Running rancher-dashboard 2.5.6 in Firefox 86.0 on MacOS

<img width="1344" alt="Screenshot 2021-03-08 at 10 15 30" src="https://user-images.githubusercontent.com/751681/110300846-b4172f00-7ff7-11eb-9598-9887ef32379d.png">

**Comment by sowmyav27** [comment]
**On 2.5.6**

- View Logs or Exec shell on any of the pod:
<img width="693" alt="Screen Shot 2021-03-15 at 8 27 02 PM" src="https://user-images.githubusercontent.com/26032343/111251644-df3be880-85cc-11eb-933a-d2eedca6ed3f.png">
<img width="327" alt="Screen Shot 2021-03-15 at 8 31 48 PM" src="https://user-images.githubusercontent.com/26032343/111252051-9173b000-85cd-11eb-876d-fbbff157102e.png">

**Comment by gaktive** [comment]
Will be worked on at the same time as rancher/dashboard#2531 so we'll close this item.
