### ISSUE TITLE
User is able to select not-ready clusters from cluster dropdown via search, stuck on loading screen/500 error

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2496]
State of Rancher -- version 2.5-head (a420b51):
* create clusters (i.e. import cluster, custom cluster) that is in `pending` state
  * ex. add an import cluster, but do not run the registration command on a node
* go to dashboard
* navigate to the cluster selection dropdown/text box -- unable to select `pending` clusters
<img width="447" alt="Screen Shot 2021-03-09 at 10 34 51 AM" src="https://user-images.githubusercontent.com/16691014/110523154-94027100-80c6-11eb-9589-d909ccdeb5b9.png">

* search for a cluster in pending state, first match is highlighted
<img width="444" alt="Screen Shot 2021-03-09 at 10 34 57 AM" src="https://user-images.githubusercontent.com/16691014/110523244-af6d7c00-80c6-11eb-9012-b1dc69f21468.png">

* select this cluster by pressing `<enter>` -- rancher stuck in `loading` state for about 30 seconds
<img width="1229" alt="Screen Shot 2021-03-09 at 11 02 17 AM" src="https://user-images.githubusercontent.com/16691014/110523426-ee9bcd00-80c6-11eb-9d34-d8f508de854e.png">

* eventually resulting in a `500` error
<img width="1209" alt="Screen Shot 2021-03-09 at 11 01 34 AM" src="https://user-images.githubusercontent.com/16691014/110523431-efccfa00-80c6-11eb-90e3-d0be5d6d05a7.png">

* with response `waiting for cluster [c-6fcd6] agent to connect` 
<img width="553" alt="Screen Shot 2021-03-09 at 11 04 20 AM" src="https://user-images.githubusercontent.com/16691014/110523754-610cad00-80c7-11eb-817a-ca8d7f469af3.png">

**Expected Result**
UI should not allow selection of cluster that is pending/not ready through dashboard

**Comment by nwmac** [comment]
This has been removed in 2.6

**Comment by slickwarren** [comment]
on master-head 979d2ba, can confirm this UI is no longer used. There is no longer a search function for clusters either, so could not attempt a repro. closing the issue

**Comment by vincent99** [comment]
There is still a search, if you have enough of them that they're not all listed already.

**Comment by slickwarren** [comment]
<img width="189" alt="Screen Shot 2021-05-24 at 10 26 07 AM" src="https://user-images.githubusercontent.com/16691014/119385080-7fbc2200-bc7a-11eb-9b36-60005b4b523c.png">

retested with enough clusters for search to show up just to be sure; search no longer auto-selects the first match or exact matches (hitting enter does nothing. seems that user must click the option they want from search)
