### ISSUE TITLE
2.6 UX: SUSE brand migration

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#2497]
- [x] fonts (https://github.com/rancher/dashboard/pull/2294)
- [x] colors
- [ ] icons
- [x] logo (get from spencer)

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/2294

**Comment by gaktive** [comment]
This should be done though we'll create a new ticket for the icons for a later 2.6.x version
