### ISSUE TITLE
Update docker in hub.docker

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [rancher/dashboard#250]
https://hub.docker.com/r/rancher/rio-dashboard/tags
🙄

**Comment by vincent99** [comment]
Sarcastic emojis aren't helpful, and the docker image hasn't changed.  The actual UI source is loaded from CDN and updated whenever something is merged here.

**Comment by Pomazan-Bogdan** [comment]
Maybe add build in dashboard?
