### ISSUE TITLE
Port Project management functionality from Ember UI

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2500]
Create equivalent functionality in the Dashboard UI to allow Projects to be managed.

This should continue to use the Norman API.

This currently looks like this:
![image](https://user-images.githubusercontent.com/1955897/110608912-9b884f80-8184-11eb-983c-3b8bdafc838f.png)

Broadly we can keep the same look and feel - use the same tab style for the project view as used in the namespace view - e.g.

![image](https://user-images.githubusercontent.com/1955897/110609172-dd18fa80-8184-11eb-9b38-691bf6cffc66.png)

We need to support the actions on namespaces in projects to allow them to be moved to a different project.

There is quite a bit of overlap between the project view and the namespace view, so we should consider this when implementing this feature.

**Comment by richard-cox** [comment]
I briefly started this some time ago in https://github.com/richard-cox/dashboard/commit/33c69bf7277c8a9470eb4a49698a1b409e79d80a using Steve. There were issues
- Fetching projects of a particular cluster (looked like all cluster's projects were returned)
- Listing namespaces in a list's cell as a collection of links (minor tweaks in branch)
- Accessing projects based on their id (projects had <cluster>/<project> format)

I recently rebased and now get no projects.

It's probably worth quickly reviewing changes and starting afresh using Norman

**Comment by codyrancher** [comment]
The move icon will be added as part of a separate issue https://github.com/rancher/dashboard/issues/3004

**Comment by izaac** [comment]
Rancher version `2.6 master-head (05/25/2021)` _f90b36e_

This is working on the local Rancher cluster but not on Downstream. 
I tried RKE1 DO and RKE2 DO single node clusters.

Sample Screenshot of an RKE1 DO cluster `Projects/Namespaces` view.

![Screen Shot 2021-05-25 at 2 09 33 PM](https://user-images.githubusercontent.com/27659/119568994-01877a80-bd63-11eb-9bcc-4476d52343a3.png)

**Comment by izaac** [comment]
@codyrancher @vincent99 

For projects created from the Dashboard are we expecting them to show also on Ember ?

**Comment by codyrancher** [comment]
@izaac yes. But that will be taken care of by https://github.com/rancher/dashboard/issues/3090.

**Comment by izaac** [comment]
Rancher version `2.6 master-head (06/01/2021)`  _5d49b92_

Validated the P1 scenarios of UI Project/namespace management we use for Ember.

Separate related issues: 
#3090
#3104
