### ISSUE TITLE
clientSecretName not getting passed in fleet GitRepo UI unless the value is selected in the ui

### ISSUE THREAD

**Issue by vCra** [rancher/dashboard#2503]
As of 2.5.6, when changing a Fleet Git Repo object via the new UI, the clientSecretName property is not sent with the request unless it is "changed" (even to the value it already is set to) in the form.

I didn't notice this in 2.5.5, but I could be mistaken

fleet/fleet.cattle.io.gitrepo

Expected Behaviour:
When updating the form, all values should be sent, regardless of them being changed.

Current behaviour:
When submitting the form, and when the "Authentication" field has not been changed, spec.clientSecretName is not sent with the response, causing the GitRepo's clientSecretName to be set to null.
The Authentication Field shows the current clientSecretName, but it will not be included in the request unless it is "changed"

Workaround:
When editing a GitRepo via the UI, you can select the currently selected secret in the Authentication Field for it to be included in the request.

**Comment by nickgerace** [comment]
Will try to reproduce before handing off to the UI folks.

**Comment by slickwarren** [comment]
This is reproducible on 2.5.6 and 2.5-head (a420b51):
* deploy at least 1 cluster 
* navigate to `Continuous Delivery` in the cluster dashboard
* add a git repo that requires authentication. I used `HTTP w/ basic AUTH Secret`
* enter your login credentials, git branch, and path. Deploy to at least 1 cluster
* wait for repo state `active` 
* `edit config` for this repo
* UI Displays all information correctly.  Save without making any modifications
* repo goes to `failed` state. Viewing the `put` request shows `null` for login information
* re-editing the config shows that `none` is selected for auth

**Comment by nickgerace** [comment]
Thank you @slickwarren for checking it out. Making a note of that in the backend Fleet issue.

**Comment by slickwarren** [comment]
This was validated on  2.5-head (93d921f):
* deploy at least 1 cluster 
* navigate to `Continuous Delivery` in the cluster dashboard
* add a git repo that requires authentication. I used `HTTP w/ basic AUTH Secret`
* enter your login credentials, git branch, and path. Deploy to at least 1 cluster
* wait for repo state `active` 
* `edit config` for this repo
* UI Displays all information correctly.  Now, the login info entered previously is saved in a secret.  Save without making any modifications
* repo goes stays active, as expected. Viewing the `put` request shows the secret that was saved and used previously
* re-editing the config shows the same information as before
