### ISSUE TITLE
2.6 UX: Add resource jump feature into Cluster Explorer

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2508]
In 2.5, the top-left of the side navigation in Cluster Explorer showed a text box where the user could type a resource name in order to quickly get to an arbitrary k8s resource:

![image](https://user-images.githubusercontent.com/1955897/117663731-e6c8d980-b198-11eb-9df6-409ef395d2ab.png)

In 2.6, we have removed this from this location and instead there is a search icon in the top right that provides equivalent functionality. The same keyboard shortcut is used (as shown in the icon's tooltip):

![image](https://user-images.githubusercontent.com/1955897/117664062-40310880-b199-11eb-8f7b-7c1a759eea81.png)

**Comment by slickwarren** [comment]
tested on master-head (1e1ed67):
<img width="1718" alt="Screen Shot 2021-05-11 at 4 22 21 PM" src="https://user-images.githubusercontent.com/16691014/117896420-5ad8af80-b275-11eb-8586-f5f383d1da60.png">

* accessible from any cluster in the dropdown (under `cluster explorer`)
<img width="262" alt="Screen Shot 2021-05-11 at 4 25 34 PM" src="https://user-images.githubusercontent.com/16691014/117896490-88bdf400-b275-11eb-8550-bc7202ff0a0b.png">

* clicking the search Icon brings up the search menu
  * shortcut also works
* search matches full and partial strings
<img width="367" alt="Screen Shot 2021-05-11 at 4 23 55 PM" src="https://user-images.githubusercontent.com/16691014/117896406-54e2ce80-b275-11eb-8d23-179d58ccf265.png">
