### ISSUE TITLE
2.6 UX: Implement Cluster Tools

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2509]
Add a new view to the cluster explorer - see attached PDF.

[ClusterTools.pdf](https://github.com/rancher/dashboard/files/6180541/ClusterTools.pdf)

This will make it easier to discover and install/upgrade cluster tools such as monitoring and logging.

**Comment by sowmyav27** [comment]
**On master-head commit id: `8c014ef`**

- Cluster Tools is available and clicking on it shows the list of available feature charts
<img width="1889" alt="Screen Shot 2021-05-10 at 12 42 43 PM" src="https://user-images.githubusercontent.com/26032343/117715762-9304c300-b18d-11eb-804b-e0b0def35c84.png">

- Upgrade is seen when a chart has Upgrade option available
<img width="542" alt="Screen Shot 2021-05-10 at 12 44 30 PM" src="https://user-images.githubusercontent.com/26032343/117715784-9b5cfe00-b18d-11eb-9a0f-12a14ddd9a61.png">

- Deploy a feature chart on the downstream cluster (cluster deployed on Ember UI)
- Go to cluster explorer of this cluster
- Click on Cluster tools from the bottom left pane. 
- Select Monitoring v2 chart

**Issue 1**
Tab view for Options is still available.
<img width="1095" alt="Screen Shot 2021-05-10 at 12 34 47 PM" src="https://user-images.githubusercontent.com/26032343/117715027-9a779c80-b18c-11eb-9cf6-c2fa3bd1391b.png">

**Issue 2**
Install Log is still seen during installation

**Expected:**
As per required, the Install log should not be displayed by default.


**Issue 3**
Uninstalling/Deleting from here deletes only the chart/App and _not_ the CRD.

**Expected:**
CRD should also be removed

Reopening to fix these ^^^ issues (as these are requirements as part of https://github.com/rancher/dashboard/issues/2509#issue-828943441)

**Comment by nwmac** [comment]
1 is covered elsewhere.

I don't think we're going to do 2 - please create a separate issue if you want us to consider this post 2.6

3 needs broader discussion - this is always how its been and is difficult for us to fix in the UI alone - I would suggest creating a defect report in the rancher/rancher repo.

Moving to To Test - please move to done if you're okay with the above.
