### ISSUE TITLE
2.6 UX: Implement new Landing Page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2511]
Add a new landing page

Example below:

![home](https://user-images.githubusercontent.com/1955897/111666581-c3725580-880b-11eb-9ba5-5ec5b7c45fea.png)

Things to consider:

- Showing banner for release notes on upgrade (this is shown as a modal in the Ember UI) and allowing the usr to dismiss the notice
- Allowing the user to choose a different landing page in the future (should allow to choose the Landing Page, a specific Cluster or any multi-cluster product - e.g. Fleet, Cluster Mgmt (provisioning)
- Providing links to docs that we will create and being able to view those - e.g. migration guide, keyboard shortcuts

**Comment by nwmac** [comment]
@mantis-toboggan-md Happy to discuss this further

**Comment by nwmac** [comment]
@mantis-toboggan-md Had a good look at this - some suggestions:

- Can we rename the page to home rather than whats-new
- Can we make the whats new info a page? I don't think we localise this currently, but should think about a folder structure with the locale in there to support static docs that are localised
- Some boxes like the "What do you want yo see..." and "Migration Assistance" should be dismissable - having a close icon to remove them and not show them in the future
- Clusters table: I think we should remove the table actions (single and multi) in this usage. Clicking on the cluster name should navigate to that cluster rather than showing the cluster yaml
- For choosing where to go on login, the last login should be a restricted list of a specific cluster or a few global apps/products like Fleet and Cluster Mgmt (when its there).
- The community links is required on the support page as well, so I suggest we turn that into a component that can be used in both places
- I've created a layout for the support page and made various visual tweaks that should work well when combined with your work here

**Comment by kravciak** [comment]
In issue description there is a comment: `this should be the default initial view unless in a single cluster deployment (!isMultiCluster)`. Can you please explain more? - I can't see anything different when logging in with 0 / 1 / 2 clusters

I created following issues:
 - Can't filter by cluster name - https://github.com/rancher/dashboard/issues/2924
 - `Learn more` button points to placeholder page - https://github.com/rancher/dashboard/issues/2925

**Comment by vincent99** [comment]
"Single cluster" is a different packaging mode for situations where things like creating clusters will not apply because you're inherently only managing one cluster, and therefore some Ui options will be hidden.  This is for some future/side projects and is not something you configure.

It is not based on how many clusters you can see happening to be 1 (or any other number).

**Comment by kravciak** [comment]
Ok, if that's expected then I am closing the issue. I can see new landing page as default now (dark theme).
