### ISSUE TITLE
HPA Multiple Metric Warnings

### ISSUE THREAD

**Issue by westlywright** [rancher/dashboard#2519]
Currently when creating an HPA, if a user chooses to add more that one of the same resource metric, regardless of different data in the value field, only the first metric is retained by the backend. We should warn users of this either in the UI or docs. More investigation needs to be done to find out if we also need to do this check for the other metric types and how we want to inform users of this. 

breakout from https://github.com/rancher/dashboard/issues/2444

**Comment by nwmac** [comment]
Closing as stale
