### ISSUE TITLE
Dashboard users create/edit/list issues 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2525]
Rancher v2.5-a420b5195dd1d0a23411b0aeb17713f291e90e10-head

<h3>Reporting a few UI issues in this ticket</h3>

1. Cluster explorer --> Users and Auth Providers --> Create
There is some white space next to the global permissions
2. Between global permissions and create, there is some gap and the same is not the case between global permissions and built-in
3. Font size for global permissions, custom and builtin has descriptions in bold/black whereas the headers are in grey. We can change this to headers in black/bold and description to grey or both in same color to maintain uniformity
4. When users are created from the dashboard, and if we edit the config from the ember UI, the role that was selected in the dashboard is missing
  <img width="500" alt="Screen Shot 2021-03-11 at 3 57 23 PM" src="https://user-images.githubusercontent.com/38144301/110871047-809c0500-8282-11eb-8fa3-460121f2ad2d.png">

5. Users & Auth --> click on user ID --> Config button in the top right --> check marks can be made more visible[especially in dark mode].
6.  Cluster explorer --> Users and Auth --> click on any of the users created --> copy button is missing as we have on the ember UI 
![Screen Shot 2021-03-11 at 5 31 23 PM](https://user-images.githubusercontent.com/38144301/110878330-e0e57380-828f-11eb-8836-a9201e427c40.png)
7. From the Users and Auth/Users tab, if we select multiple users and click on download yaml, the button is not working. When multiple users are selected, download yaml button can be greyed out

**Screenshot for reference to the above mentioned issues**
<img width="600" alt="Screen Shot 2021-03-11 at 3 03 45 PM" src="https://user-images.githubusercontent.com/38144301/110867072-09af3e00-827b-11eb-984d-591a6e22c148.png">

https://github.com/rancher/dashboard/issues/2204

**Comment by richard-cox** [comment]
@anupama2501 I've fixed some, questions on others.

> 1. Cluster explorer --> Users and Auth Providers --> Create
>    There is some white space next to the global permissions

Could you provide a screenshot highlighting the white space? If it's the large area immediately to the right this is by design, the roles will fill up to three columns. For `Global Permissions` there is only enough for single column compared to `Built-in` which has three.

> 2. Between global permissions and create, there is some gap and the same is not the case between global permissions and built-in

Unfortunately this gap is there intentionally to provide space for errors specific to the password fields (not matching). The low-bar fix would be to remove the spacing which would lead to bobbling of the fields below when the errors are shown/hidden. Alternatively move the errors down to the standard error area above the cancel save buttons... but this would appear off screen due to the permissions below. Other forms appear in tabbed components but don't handle validation correctly. There is a bigger item of work here to re-address how forms work in the Dashboard, see #2528 for more info. 

> 3. Font size for global permissions, custom and builtin has descriptions in bold/black whereas the headers are in grey. We can change this to headers in black/bold and description to grey or both in same color to maintain uniformity

This was an issue with the checkbox in general. The colour matches that of the form labels which is light grey. I've tweaked this for this specific use case. Fixed in #2533

> 4. When users are created from the dashboard, and if we edit the config from the ember UI, the role that was selected in the dashboard is missing

I couldn't reproduce this, however I did update the create process which may have fixed it. Steps I followed
Dashboard - Users & Auth --> Click Create --> Enter Username --> Enter Password and confirmation --> Leave only role selected (Standard User) --> Click Create
Ember UI - User is already visible in the list --> Click user --> Click Edit --> Standard User is correctly checked

> 5. Users & Auth --> click on user ID --> Config button in the top right --> check marks can be made more visible[especially in dark mode].

This was a global issue affected all checkboxes in 'view' mode. Fixed in #2533

> 6. Cluster explorer --> Users and Auth --> click on any of the users created --> copy button is missing as we have on the ember UI

This is fixed in #2533

> 7. From the Users and Auth/Users tab, if we select multiple users and click on download yaml, the button is not working. When multiple users are selected, download yaml button can be greyed out

This was a global issue affected all bulk download of yaml. Fixed in #2533

**Comment by anupama2501** [comment]
@richard-cox 
Sorry, I missed the above comment.

I'm on the version v2.5-fa087c81628de057406608f077d0952bb03cea56-head

1. ``` Could you provide a screenshot highlighting the white space? If it's the large area immediately to the right this is by design, the roles will fill up to three columns. For Global Permissions there is only enough for single column compared to Built-in which has three. ```
```
Here is the screenshot. I have highlighted the space next to global permissions. 
Can we add two roles in each of the first row and second row in the Built-in field and remove 
the third row, so that the space above can be covered even the space next to credentials?
```
<img width="300" alt="Screen Shot 2021-03-22 at 7 57 33 AM" src="https://user-images.githubusercontent.com/38144301/112010260-636a0080-8ae4-11eb-9cf3-e90d826d05ad.png">

2. ``` Unfortunately this gap is there intentionally to provide space for errors specific to the password fields (not matching). The low-bar fix would be to remove the spacing which would lead to bobbling of the fields below when the errors are shown/hidden. Alternatively move the errors down to the standard error area above the cancel save buttons... but this would appear off screen due to the permissions below. Other forms appear in tabbed components but don't handle validation correctly. There is a bigger item of work here to re-address how forms work in the Dashboard, see #2528 for more info. ```

```
In the ember UI, for 'generate password' we have a button next to the password field. 
Can we have a button like this next to the password field and then we could use the space for 
displaying errors in case of an incorrect password?
```
**On ember UI** 
<img width="1348" alt="Screen Shot 2021-03-22 at 8 07 33 AM" src="https://user-images.githubusercontent.com/38144301/112011949-fce5e200-8ae5-11eb-879a-404a2e269576.png">



4. ``` When users are created from the dashboard, and if we edit the config from the ember UI, the role that was selected in the dashboard is missing ```

```
I tried reproducing and looks like it has been fixed. When I was on the version mentioned in the
ticket v2.5-a420b5195dd1d0a23411b0aeb17713f291e90e10-head, it was seen consistently.
```

**Comment by richard-cox** [comment]
I've had a chat with Neil and we agreed for the moment 1 and 2 are fine.

**Comment by anupama2501** [comment]
Verified the issues on v2.5-b2a34d7cef440e3ed1de7d506233aa3a332649ae-head

1. ``` Font size for global permissions, custom and builtin has descriptions in bold/black whereas the headers are in grey. We can change this to headers in black/bold and description to grey or both in same color to maintain uniformity```

Headers for each section are changed to bold/black whereas the descriptions are changed to grey
<img width="300" alt="Screen Shot 2021-03-30 at 2 24 00 PM" src="https://user-images.githubusercontent.com/38144301/113059605-7fb11180-9164-11eb-8664-0a2dfd7c1a72.png">

2. ```Users & Auth --> click on user ID --> Config button in the top right --> check marks can be made more visible[especially in dark mode].```

Cluster explorer --> Users and authentication --> Users --> click on any users --> in the config tab, check marks are visible in the light as well as dark mode

3. ```Cluster explorer --> Users and Auth --> click on any of the users created --> copy button is missing as we have on the ember UI```

Cluster explorer --> Users and Auth --> Users --> click on any of the users created --> copy button is available next to the username 
<img width="200" alt="Screen Shot 2021-03-30 at 2 32 05 PM" src="https://user-images.githubusercontent.com/38144301/113059799-b71fbe00-9164-11eb-8b90-8374111ba5e9.png">

4. ```From the Users and Auth/Users tab, if we select multiple users and click on download yaml, the button is not working. When multiple users are selected, download yaml button can be greyed out```

Cluster explorer --> Users and Auth --> Users --> select multiple users and click on download yaml [all the files are downloaded as a zipped folder with the name resources.zip]

5. ``` When users are created from the dashboard, and if we edit the config from the ember UI, the role that was selected in the dashboard is missing.```

- Cluster explorer --> Users and Auth --> Users --> create users by selecting some roles from the built-in roles 
- Verify on ember UI --> security --> users --> click on the ID verify all the selected roles are enabled
- from the Cluster explorer --> Users and Auth --> Users --> edit the user created from the above step and verify the values are reflected both on ember UI and dashboard
- Create a user in the ember UI and verify the roles selected for the user in the ember UI are visible for the same user in the dashboard. Edit the values from dashboard and 

verify all the selected values are enabled in both ember UI and dashboard
