### ISSUE TITLE
Dashboard Users:  advanced and Users and Auth Providers issues

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2526]
v2.5-4e48b8a9fbedad498fa21fd00e6e426ab3e13770-head

1. From cluster explorer --> Users and Auth Providers --> Create a user by providing all the details --> click on the ellipsis of the created user --> Edit yaml/download yaml, clone,  should not be present as this is an advanced users option
2. From the explorer --> users and auth providers --> users --> click on users --> verify we have Related resources tab which is not the case in ember UI. Can we have this only in the Advanced Users tab and not from the Users and Auth tab
3. From the explorer --> users and auth providers --> users --> Download yaml shouldn't be present in this tab as its in advanced users and not on ember UI
 <img width="350" alt="Screen Shot 2021-03-11 at 5 15 18 PM" src="https://user-images.githubusercontent.com/38144301/110877049-9662f780-828d-11eb-8553-bb11c82a4717.png">

4. From the explorer --> users and auth providers --> users --> click on a created user from step1 --> the page should have detail button and config/yaml can be removed as it is advanced users feature [not present in the ember UI] and the edit yaml/download yaml, delete, deactivate and refresh group memberships can be removed from the ellipsis.
<img width="400" alt="Screen Shot 2021-03-11 at 5 19 41 PM" src="https://user-images.githubusercontent.com/38144301/110877429-40db1a80-828e-11eb-8fdb-7549838c9eea.png">

**UI Screenshot for reference**
![Screen Shot 2021-03-11 at 5 22 53 PM](https://user-images.githubusercontent.com/38144301/110877830-ef7f5b00-828e-11eb-93bc-7156ca910a95.png)

https://github.com/rancher/dashboard/issues/2204

**Comment by richard-cox** [comment]
There's two versions of the table, one in Users & Auth and the other in Cluster Explorer. The main location a user should go to to manage users is the Users & Auth section. After discussing with @nwmac we agreed to remove the Cluster Explorer user table to remove confusion.

**Comment by anupama2501** [comment]
On v2.5-b2a34d7cef440e3ed1de7d506233aa3a332649ae-head
User attributes option is not seen from the explorer 




The following options are still seen in the Users and Authentication for the users:
From cluster explorer --> Users and Auth Providers --> Create a user by providing all the details --> Edit yaml/download yaml, clone is present for the users
From the explorer --> users and auth providers --> users --> click on users --> Related resources tab is present for the users
From the explorer --> users and auth providers --> users --> Download yaml option is provided for the user

<img width="300" alt="Screen Shot 2021-04-01 at 8 15 11 AM" src="https://user-images.githubusercontent.com/38144301/113316277-ffed8900-92c2-11eb-9f3f-090f0f64346d.png">

@richard-cox  Is there a reason why we are providing these options for users under "Users and Authentication" in dashboard as we do not have these in ember UI?

**Comment by richard-cox** [comment]
The ability to view/edit/download resources as yaml in a generic way is I believe new to the dashboard and wasn't available to all resources in the ember ui, this is probably the reason for the disparity between the two.

Whilst the ability to handle yaml may be confusing to some users it is helpful to others. Differentiating the UI based on user experience isn't something we handle, so a balance is required. With that in mind I've removed the possibly confusing 'Download' feature which appears in the user's list header and user row (#2648)... but kept other 'advanced' yet helpful features that are more hidden (edit user as yaml, clone user, user related resource tab).

**Comment by vincent99** [comment]
I don't understand why we're editorializing this one download button out of hundreds of types.  Downloading, clone, etc the yaml are options available on all resources in dashboard unless there's a specific good reason for them not to be (which is usually that it's a virtual type that isn't actually backed by a real record in k8s so there isn't really any YAML to manipulate).

We're porting the capabilities of the Ember UI into Vue, not trying to make them _exactly_ match or limit what Vue can do because Ember couldn't.

**Comment by richard-cox** [comment]
After a fair amount of discussion the Download actions should be show for users and other resources in the Auth product. If this changes it will be done as part of #2662. With that in mind I've closed the pr #2648, which was the only code change associated with this issue.

**Comment by anupama2501** [comment]
As there are no changes for the ticket, verified the following for a user on v2.5-
70024998a0e95374a135177953a04f4539e2d59c-head

Cluster explorer --> Users and Authentication --> Users
1. Create a user with permissions "user base" and add additional roles as "Configure Authentication"
2. Once the user is created, click on the user, edit yaml change values for username and verified the new change on the user.
3. On the ellipsis, verified download yaml, cloning the user,  deactivate and refresh group memberships work without any issues.
4. Related resources tab has the crbs related to the user
