### ISSUE TITLE
Dashboard Users: advanced and Users and Auth Providers admin issues

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2527]
v2.5-4e48b8a9fbedad498fa21fd00e6e426ab3e13770-head

1. From the Users/Users and auth providers, if we select the default admin and delete, admin deletion is stuck in removing. Admin shouldn't be allowed to delete and an error should be thrown as in ember UI 
<img width="270" alt="Screen Shot 2021-03-11 at 5 41 16 PM" src="https://user-images.githubusercontent.com/38144301/110878986-0757de80-8291-11eb-8004-8e9f7474059a.png">
2. In the Users/Users and auth providers, if we try to deactivate the admin, it is allowed which shouldn't be the case as the admin cannot re-login and should be thrown an error as in ember UI
<img width="270" alt="Screen Shot 2021-03-11 at 5 42 51 PM" src="https://user-images.githubusercontent.com/38144301/110879085-379f7d00-8291-11eb-82c6-430290340e8d.png">

https://github.com/rancher/dashboard/issues/2204

**Comment by richard-cox** [comment]
It looks like this is the same behaviour as the ember ui, though it wasn't right there either. Had a quick look and it's not straight forward to identify the signed in user given a steve user. Will investigate further

**Comment by anupama2501** [comment]
Verified on v2.5-fa087c81628de057406608f077d0952bb03cea56-head

- From Users and auth providers, select all the users and delete. The admin is not deleted 
- Create a few users and select all the users, and deactivate. Admin is not deactivated.
- Select admin, the delete button is greyed out.

<img width="500" alt="Screen Shot 2021-03-19 at 11 17 01 PM" src="https://user-images.githubusercontent.com/38144301/111861138-504f0900-8909-11eb-9e33-89c382608647.png">
