### ISSUE TITLE
hpa pages

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#253]
https://xd.adobe.com/view/d6eb95e0-4dd0-4515-5080-b30e3bf01131-a0da/

**Comment by lvuch** [comment]
updated with side tabs https://xd.adobe.com/view/36dc23a3-3b35-433c-757b-02d1817a7ffe-40ed/

**Comment by deniseschannon** [comment]
- [ ] Clean up Masthead so it matches current design
- [ ] Clean up Name/Namespace/Description to use the updated NameNSDescription component
-[ ] Required fields are namespace, name, workload, min/max replicas
-[ ] Required fields for metrics are metric type, metric name, target type, quantity
- [ ] Create 4 different screens for the 4 different metric types (Resource, Pods, Object, External) as each type has different additional fields - View Ember to see what fields are required for each type. 
- [ ] Clean up labels and annotations tab into 1 tab

**Comment by lvuch** [comment]
This link is updated with above feedback: https://xd.adobe.com/view/36dc23a3-3b35-433c-757b-02d1817a7ffe-40ed/

**Comment by deniseschannon** [comment]
Closing in favor of new design until this is prioritized
