### ISSUE TITLE
Port: Groups page to Vue

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2530]
There's a PR already for this migrated page of the Groups interface to Ember but no card until now apparently.

**Comment by richard-cox** [comment]
Linking PR - #2247

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `38649e228`**

Related issues logged:
- https://github.com/rancher/dashboard/issues/2540
- https://github.com/rancher/dashboard/issues/2541
- https://github.com/rancher/dashboard/issues/2542

**Comment by anupama2501** [comment]
On v2.5-fa087c81628de057406608f077d0952bb03cea56-head
Verified the following scenarios:
Enable auth from the explorer --> Users and authentication [AD is enabled for the verification]
1. Users and authentications --> groups --> assign global role --> select member --> Role as Restricted admin 
logout and login as restricted admin. 
> - Verified local cluster and other clusters are seen. From the cluster explorer --> Verify access to local cluster is restricted
> - Explorer --> Users and Authentication --> Groups --> edit the roles of other groups and verify enabling administrator role is restricted and all the other roles can be edited
> - Cluster explorer --> add other group as restricted admin [change the permission to Admin 
#2571
> - Create a cluster from ember UI
> - Delete other groups 

2.  Users and authentications --> groups --> assign global role --> select member --> global permissions as standard, roles with authentication enabled and create --> logout and login as standard user 
> - Create a cluster 
> - From that created cluster, explorer --> Users and authentication --> disable/edit config
> - Verified standard user's cluster explorer --> groups --> assign global roles [forbidden message is displayed]
> - Verified standard user's cluster explorer --> users --> users cannot be created

**Comment by anupama2501** [comment]
Closing this ticket as the issues are being tracked separately
