### ISSUE TITLE
Cluster explorer: Page rendering issues on 2.5.6 

### ISSUE THREAD

**Issue by ZleFox** [rancher/dashboard#2531]
There is a regression in version 2.5.6. In the namespace chooser the selected box is way too big  and when you select multiple namespaces there is weird rendering out the browser scope on mouse-over. As a result it is very difficult to use the namespace selector. 
![image](https://user-images.githubusercontent.com/22940823/110971232-45bdce00-8363-11eb-9441-3d6670313bea.png)

Issue not present in 2.5.5

**Comment by sowmyav27** [comment]
**On 2.5.6**

**Issue 1**
- In the cluster explorer, in the top dropdown of namespaces, select multiple namespaces
<img width="525" alt="Screen Shot 2021-03-15 at 8 24 16 PM" src="https://user-images.githubusercontent.com/26032343/111251553-b6b3ee80-85cc-11eb-993b-48e549e3f251.png">

**Issue 2**
- View Logs on any of the pod:
<img width="693" alt="Screen Shot 2021-03-15 at 8 27 02 PM" src="https://user-images.githubusercontent.com/26032343/111251644-df3be880-85cc-11eb-933a-d2eedca6ed3f.png">

**Comment by Jono-SUSE-Rancher** [comment]
Validated this on 2.5-head as fixed and working as expected. Tested in the jono cluster that @sowmyav27 set up for me.

The Namespaces displays properly when no namespaces are selected:
![namespace](https://user-images.githubusercontent.com/77702636/114767112-1ad8e800-9d1c-11eb-8e1f-db20618f1dab.png)

It also displays properly when multiple namespaces are added:
![Screen Shot 2021-04-14 at 12 18 43 PM](https://user-images.githubusercontent.com/77702636/114767153-23c9b980-9d1c-11eb-87b3-ab57409a9452.png)

For Issue 2 (#2488), the Logs section now displays properly, so the user is able to close/etc:
![log display](https://user-images.githubusercontent.com/77702636/114767309-51aefe00-9d1c-11eb-9af1-5828f07a12bd.png)
