### ISSUE TITLE
Cluster explorer 2.5.6 - useless and misleading PersistentVolumes page

### ISSUE THREAD

**Issue by ZleFox** [rancher/dashboard#2532]
the PersistentVolumes page is displaying wrong and less relevant information than the information in the old version 2.5.5
here is a screenshot: 
![image](https://user-images.githubusercontent.com/22940823/110972126-53c01e80-8364-11eb-9114-cd56c12c1ad9.png)

These volumes are not provisioned by longhorn and all the useful information about the volumes present in v2.5.5 is missing.

**Comment by ZleFox** [comment]
It's the same in 2.5.7

**Comment by ZleFox** [comment]
so no fix for 2.5.x versions? It is really breaking the entire "persistent volumes" page, making it useless

**Comment by codyrancher** [comment]
@ZleFox 
1. what were those volumes provisioned by? In the general case I'm seeing the appropriate provisioner listed.
2. what information would you like to see present? In the old UI I see the persistent volume claim present when available. Is there anything else that would be helpful to you?

**Comment by codyrancher** [comment]
I went ahead and added the PVC field to the list page to make it more consistent with the old UI https://github.com/rancher/dashboard/pull/3277

If there's anything more you'd like to have added or have more details about which source you were having an issue with feel free to reopen and add more details.

**Comment by ZleFox** [comment]
thanks, the format in 2.5.5 was more useful. It had information about storage class, reclaim policy, etc .. 
![image](https://user-images.githubusercontent.com/22940823/122346281-73617700-cf51-11eb-8f60-328e17186576.png)

**Comment by richard-cox** [comment]
I had a quick comparison on some of the diffs

PVC List
- We show more information in the latest dashboard than in Cluster Manager
- Volume and storage need to link to their respective resource

PV List
- No comparison in Cluster Manager
- From the screenshot in previous comment it looks like in a previous version of the dashboard where we have additional info. Need to understand why these were removed

**Comment by codyrancher** [comment]
> 
> 
> I had a quick comparison on some of the diffs
> 
> PVC List
> 
>     * We show more information in the latest dashboard than in Cluster Manager
> 
>     * Volume and storage need to link to their respective resource
> 
> 
> PV List
> 
>     * No comparison in Cluster Manager
> 
>     * From the screenshot in previous comment it looks like in a previous version of the dashboard where we have additional info. Need to understand why these were removed

It was removed while we were making it more consistent with Cluster Manager. What was shown in 2.5.5 is the default which is defined by the schema.
![image](https://user-images.githubusercontent.com/55104481/122390231-9cb8dd80-cf26-11eb-81d1-cc0b71cde509.png)

Here's the Cluster Manager comparison
![image](https://user-images.githubusercontent.com/55104481/122390534-f3261c00-cf26-11eb-8e1e-7880350dace6.png)


I'll bring it up in our meeting this morning.

**Comment by anupama2501** [comment]
Re-opening this ticket  after speaking to @codyrancher on slack - `Reclaim policy` and `Reason` to be added

**Comment by anupama2501** [comment]
Verified on rancher v2.6-head 6c14c33
Created a PV and verified the required fields added in the PV 
<img width="500" alt="Screen Shot 2021-08-03 at 4 54 38 PM" src="https://user-images.githubusercontent.com/38144301/128100686-4ed8e12d-20a3-49d7-b262-493fdc2b5794.png">
