### ISSUE TITLE
[Monitoring V2] Add ability to detect or select RKE Windows Cluster Type and set default values

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2537]
Currently, the UI is unable to detect the cluster type of an RKE Windows Custom cluster and cannot set default values as a result.

To support intuitive installs of Rancher Monitoring on RKE Windows clusters, we need to add a cluster type for rkeWindows that [copies the configKeys for RKE today](https://github.com/rancher/dashboard/blob/33481b2fec3b5b8982ce9500c799ae9c595e6ea1/chart/monitoring/ClusterSelector.vue#L68) and also sets `windowsExporter.enabled=true`.

Current workaround is to set the Cluster Type to RKE manually and then Edit as Yaml -> override `windowsExporter.enabled=true`

Related Epic Issue: https://github.com/rancher/rancher/issues/28327

**Comment by gaktive** [comment]
This is needed for 2.5.8 based on Windows testing. Wes may be stretched thing based on other feature work so we'll need someone else.

**Comment by gaktive** [comment]
A new variable should be appearing soon to help.

**Comment by thehejik** [comment]
**Test report:**
Tested on `rancher:2.5.8-rc4` (I have to enable `Include prerelease versions` in Settings) and `rancher-monitoring-14.5.100-rc07` on windows cluster.

Cluster type `Other` is still preselected but `Windows` entry is available in the dropdown and can be selected. @aiyengar2 I guess this is expected, right?

Anyway the new `global.cattle.windows.enabled` key in values.yaml is set to `false` and `windowsExporter.enabled=true` is added at the end of values.yaml what corresponds to the original issue description but it was deprecated in meantime and replaced by `global.cattle.windows.enabled=true`.

Reopening due the deprecated key in values.yaml, please replace by the new one.

**Comment by thehejik** [comment]
This problem has been resolved in current v2 `rancher-monitoring-14.5.100` chart - now when selecting `Windows` as clusterType only `global.cattle.windows.enabled=true` is present and `windowsExporter` key is not available in values.yaml anymore.

Closing.
