### ISSUE TITLE
Dashboard AzureAD authentication with standard and custom endpoint is not working

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2538]
Rancher | v2.5-4e48b8a9fbedad498fa21fd00e6e426ab3e13770-head

From the cluster explorer, Auth providers and Users --> AzureAD  

- Add the details and select standard from endpoints 
- Click on enable and users are redirected to the credential page the redirected URL 
- In the redirected URL even before we provide credentails, we see the following error:
<img width="400" alt="Screen Shot 2021-03-15 at 3 14 14 PM" src="https://user-images.githubusercontent.com/38144301/111228287-3035e780-85a1-11eb-9f34-948740c176d9.png">

From the cluster explorer, Auth providers and Users --> AzureAD 

- Add the details and select custom from endpoints
-  add all details and click on enable, user is redirected to the credential page.
-  Once we click on save, we see the following issue
<img width="400" alt="Screen Shot 2021-03-15 at 3 08 16 PM" src="https://user-images.githubusercontent.com/38144301/111228310-3af07c80-85a1-11eb-928d-7a843f2dec13.png">

`
window.opener.ls is not a function`

**Comment by mantis-toboggan-md** [comment]
Azure AD and Google oauth both require an API fix that is not in 2.5-head yet; this issue should be resolved with a master-head build however. (backend pr https://github.com/rancher/rancher/pull/31563)

**Comment by anupama2501** [comment]
Verified on master-cf376738e499ba538e80d8d02f37592391094ac4-head

- From the cluster-explorer, Users and authentication --> Auth Providers --> Azure AD --> copy the 'Reply URL' and paste in the registration portal test app
- Provide the Tenant ID, Application ID and Application Secret and select standard as the Endpoints in the Azure AD in the auth providers page --> Authenticate with Azure and the authentication goes through without any error
- Create a cluster logged in as a standard user

**Comment by anupama2501** [comment]
Closing the issue as for 2.5-head validation we are tracking through the above linked issue
