### ISSUE TITLE
[Enhancement] - Workloads display and filtering

### ISSUE THREAD

**Issue by zeylos** [rancher/dashboard#2539]
Hi !

I would like to know if we could :
- add the ability to filter the Workloads list by labels (the --selector from kubectl get)
- add the ability to select multiple type of ressources on the left pannel

From my point of view this would get closer to the CLI navigation style and can be a huge improvement when used with the checkboxes and whatever bulk actions the UI can provide in the future (I'm thinking for example, bulk label addition, removing, bulk redeployment etc...).

Thanks in advance,
Keep up the good work !

**Comment by catherineluse** [comment]
Closing this issue in favor of https://github.com/rancher/dashboard/issues/5091
