### ISSUE TITLE
Cluster dropdown left-aligns after removing search ->  long names of clusters in dropdown are not fully visible

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2544]
Repro steps:
* v2.5-head (38649e2)
* Deploy some clusters with long names (near 63 char. limit) and short names
* search for a string that is _not_ in the long cluster name 
* now remove all text from the search bar
* dropdown menu for clusters now is left-aligned, and does not show full name of long clusters

example:
<img width="525" alt="Screen Shot 2021-03-15 at 1 51 30 PM" src="https://user-images.githubusercontent.com/16691014/111231881-3e870200-85a7-11eb-87a4-0ec56ef07918.png">
<img width="259" alt="Screen Shot 2021-03-15 at 4 01 18 PM" src="https://user-images.githubusercontent.com/16691014/111232126-b6552c80-85a7-11eb-8f7f-c47612125dc8.png">

<img width="254" alt="Screen Shot 2021-03-15 at 1 51 24 PM" src="https://user-images.githubusercontent.com/16691014/111231883-4050c580-85a7-11eb-9fd2-0db3123fa545.png">

seems like this is related to alignment,  can we change this to stay right-aligned after removing text?

**Comment by westlywright** [comment]
Just adding a repo note: I could only repro this if I entered the string then did `CMD + A` followed by `delete`. Simply backspacing the text did not work for me in either chrome or firefox.

**Comment by slickwarren** [comment]
this is fixed on 2.5-head (fa087c81628de057406608f077d0952bb03cea56) and master-head (2dca0c6):
* Deploy some clusters with long names (near 63 char. limit) and short names
* search for a string that is _not_ in the long cluster name 
* now remove all text from the search bar
* all names are aligned correctly and completely visible in the window
