### ISSUE TITLE
Auth Providers - Shibboleth OpenLDAP fields should have some pre-filled values.

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2545]
Rancher version: `v2.5-head (03/15/2021)` _38649e2_

Ember UI pre-fills the OpenLDAP fields while configuring the Shibboleth auth.
We should do the same from the Dashboard UI

Here's the UI when I click the **Configure an OpenLDAP Server**

![Screen Shot 2021-03-15 at 4 46 36 PM](https://user-images.githubusercontent.com/27659/111235712-79406880-85ae-11eb-939e-0d292690d39c.png)

Default values when configuring from Ember UI:

![Screen Shot 2021-03-15 at 4 52 58 PM](https://user-images.githubusercontent.com/27659/111235947-f66bdd80-85ae-11eb-8a7c-a2f4766b07db.png)

https://github.com/rancher/dashboard/issues/2115

**Comment by anupama2501** [comment]
Verified on v2.5-93d921f36e2d38478aedbabf9c3604115e4bdded-head
From cluster explorer --> Users and auth --> Auth providers --> Shibboleth --> All openLDAP values have pre-filled values.

**Comment by anupama2501** [comment]
**Re-opening the issue as the status bit mask is missing in the openLDAP configuration. Should be set to 0.**

On ember UI:
<img width="400" alt="Screen Shot 2021-04-06 at 10 07 52 PM" src="https://user-images.githubusercontent.com/38144301/113813410-b2d74000-9724-11eb-9764-1e31e6b8ba4f.png">

on dashboard:
<img width="400" alt="Screen Shot 2021-04-06 at 10 08 00 PM" src="https://user-images.githubusercontent.com/38144301/113813424-b965b780-9724-11eb-82f1-1e1ca16a80d8.png">


**Also, on dashboard for private key, certificate and metadata xml --> Focus placeholder are missing**

**Comment by anupama2501** [comment]
Verified on v2.5-d1083bc63e4ddde70ffadd09bf0133ae5862b5fe-head

From cluster explorer --> Users and auth --> Auth providers --> Shibboleth --> Enable openLDAP and verified status bit mask is set to 0.

From cluster explorer --> Users and auth --> Auth providers --> Shibboleth --> private key, certificate and metadata xml have the placeholders.
