### ISSUE TITLE
Auth Providers - Shibboleth OpenLDAP shouldn't include option for Nested Groups

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2546]
Rancher version: `v2.5-head (03/15/2021)` _38649e2_

Ember UI doesn't expose this option for Shibboleth + OpenLDAP.
![Screen Shot 2021-03-15 at 4 52 25 PM](https://user-images.githubusercontent.com/27659/111235891-d5a38800-85ae-11eb-9096-0c6a9aea4075.png)

Here's the OpenLDAP options when configuring from Ember UI:

![Screen Shot 2021-03-15 at 4 52 58 PM](https://user-images.githubusercontent.com/27659/111236010-21563180-85af-11eb-89d0-1bef772bbb71.png)

https://github.com/rancher/dashboard/issues/2115

**Comment by anupama2501** [comment]
Verified on v2.5-93d921f36e2d38478aedbabf9c3604115e4bdded-head

From cluster explorer --> Users and auth --> Auth providers --> Shibboleth
Enable "Configure an openLDAP server" and verified the options for nested groups have been removed:
<img width="426" alt="Screen Shot 2021-04-06 at 10 29 41 PM" src="https://user-images.githubusercontent.com/38144301/113815245-b28c7400-9727-11eb-931f-a126fb463761.png">

From network tab, we can see the value is set to False
<img width="320" alt="Screen Shot 2021-04-06 at 10 32 37 PM" src="https://user-images.githubusercontent.com/38144301/113815452-0434fe80-9728-11eb-9783-5957e96288ee.png">
