### ISSUE TITLE
Auth Providers - Shibboleth OpenLDAP options doesn't show up after disabling Shibboleth

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2547]
Rancher version: `v2.5-head (03/15/2021)` _38649e2_
https://github.com/rancher/dashboard/issues/2115

- Enable Shibboleth
- Then Disable the Auth
- Click on the `Configure an OpenLDAP Server`

![shibb-disabled](https://user-images.githubusercontent.com/27659/111236529-4ac38d00-85b0-11eb-8a0d-190039011aa9.gif)

Workaround: Refresh the browser.

**Comment by anupama2501** [comment]
Verified on v2.5-93d921f36e2d38478aedbabf9c3604115e4bdded-head

From cluster explorer --> Users and auth --> Auth providers --> Shibboleth [enable auth by adding openLDAP details]
Create a cluster 
Disable auth and from the shibboleth configuration disable and enable "configure an openLDAP server". OpenLDAP options show up.

**Comment by anupama2501** [comment]
Enable the shibboleth auth by adding openLDAP server details--> disable the shibboleth auth from cluster explorer --> Users and auth --> Auth providers --> Shibboleth 
"Configure an openLDAP server" checkbox is checked but the options are not displayed. 


**Re-opening the issue, as we enable the auth and when we disable the auth, checkbox for "Configure an openLDAP server" to be unchecked.  **

<img width="400" alt="Screen Shot 2021-04-06 at 10 53 17 PM" src="https://user-images.githubusercontent.com/38144301/113900817-13956580-9783-11eb-809a-53e59e1b1ac5.png">

**Comment by anupama2501** [comment]
Verified on v2.5-d1083bc63e4ddde70ffadd09bf0133ae5862b5fe-head

Enable the shibboleth auth by adding openLDAP server details--> disable the shibboleth auth from cluster explorer --> Users and auth --> Auth providers --> Shibboleth
"Configure an openLDAP server" checkbox is disabled and when enabled, the LDAP options show up
