### ISSUE TITLE
Auth Providers - Shibboleth OpenLDAP can't unselect TLS/StartTLS checkboxes unless I edit the Port field first

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2548]
Rancher version: `v2.5-head (03/15/2021)` _38649e2_
https://github.com/rancher/dashboard/issues/2115

It's a bit confusing to select one or the other if I have to edit the Port field first.

Attached a video for clarity.

https://user-images.githubusercontent.com/27659/111237068-7bf08d00-85b1-11eb-816b-23f8ff56197e.mp4

**Comment by anupama2501** [comment]
Verified on v2.5-93d921f36e2d38478aedbabf9c3604115e4bdded-head

From cluster explorer --> Users and auth --> Auth providers --> Shibboleth --> Select/ unselect the port field. delete the value for port field check/uncheck TLS and startTLS values --> works as expected.
Enable shibboleth and edit config and verified by selecting/unselecting TLS/StartTLS --> works as expected
