### ISSUE TITLE
on create, StatefulSet "Service Name" required, but not marked as such. dropdown for Service Name is not populating

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2553]
* tested on 2.5-head (38649e2)

**Issues**
* when creating a statefulset, the Service name dropdown does not display anything
* Service name is required, but not marked with `*` 
 <img width="940" alt="Screen Shot 2021-03-16 at 8 45 09 AM" src="https://user-images.githubusercontent.com/16691014/111338622-5193e380-8634-11eb-9169-ee37237a2b30.png">

**Helpful Notes:**
I do have services in the `default` namespace, and was able to create a statefulset from the ember UI.  
<img width="453" alt="Screen Shot 2021-03-16 at 9 09 07 AM" src="https://user-images.githubusercontent.com/16691014/111342191-7178d680-8637-11eb-9528-10259e00fcd7.png">

selecting a namespace with no services does show correctly

<img width="1529" alt="Screen Shot 2021-03-16 at 9 12 58 AM" src="https://user-images.githubusercontent.com/16691014/111342576-d2a0aa00-8637-11eb-80b7-71eb62b703a9.png">

**Comment by slickwarren** [comment]
<img width="1524" alt="Screen Shot 2021-04-06 at 10 31 37 AM" src="https://user-images.githubusercontent.com/16691014/113753731-4d9f3280-96c3-11eb-99f2-3c1fd10ef1e6.png">

this is now working on 2.5-head (93d921f):
* service name is required
* drop down for service name is now populating based on user-selected namespace

**Comment by scoful** [comment]
@slickwarren 
It seems to appear again in version 2.6.1, `docker pull rancher/rancher:stable`, what can I do?

**Comment by danbigthink** [comment]
@slickwarren 
Hey, this issue seems to be closed but I'm experiencing this too, why is this closed and still present in 2.6.1 and 2.6.2 ?
Nobody even answer @scoful

I just created a cluster and have been using rancher for more than 4 years, moved to this version from 2.4 and can't create a new statefulset.

Nothing shows up in the Service Name dropdown, I even tried to create the nodeport and cluster ip separately and this dropdown still doesn't populate.

Error message: "Service Name" is required. There isn't even a red asterisk in that field like you pointed out was checked in.

Every version of Rancher I've used prior to 2.5 always created the necessary bits such as nodeport and cluster ip's when creating a stateful set, basically create new stateful set by setting name, image, volumes, secrets and poof, you have a stateful set.

This is pretty disappointing. Like what do I do now? Nobody is going to answer this quickly enough for me to meet my deadlines, I'm a long time lover of Rancher, is this all happening cause Rancher got bought by SUSE? UGH!!!!

**Comment by slickwarren** [comment]
This is not marked as required, but the service name will populate if you select a namespace that has a service. From what I see, you must have `headless` services in order to select them. I will open a ticket for the `*` on this field Monday. But the services will populate if you have the correct resources (services) deployed in your namespace. 

An example of this working is to:
* deploy monitoring v2 to your cluster
* go to deploy a statefulSet
  * select the `kube-system` namespace
  * you will be able to select some monitoring services from the `service name` field

**Comment by danbigthink** [comment]
Hi @slickwarren,

I've been using rancher for a long while now and would expect things to work as they used to. This dropdown is a required field and seems like there's a dependency on what can be associated to it. Unfortunately you never had to create a headless service in the past to create stateful sets, why would this have to be done now? Also this field is required and not marked as such. 

I used filtering to see only my namespaces/project, and nothing ever shows up in this, I never deploy my stateful sets to kube-system, I deploy them to my project based namespace.

An example I'd expect to work is:
- create my project and add a namespace under that.
- add any secrets
- add a postgres database as a stateful set while filtering just my project/namespace, with my tcp port 5432
- i should be able to create this and have a nodeport and clusterip created for me.
- i should have a new postres database

This cannot be done and can be done in rancher <= 2.4.x. 

I've completely back-pedalled to using 2.4.x.

How is this considered a stable production release? It seems like stateful sets in 2.6.2 are not working as expected and this is the stable release.

**Comment by slickwarren** [comment]
I believe this is working as intended, besides the missing * in the UI.  Kubernetes documentation for stateful sets [does say that it requires a headless service.](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations)

Perhaps the requirements changed from k8s from your rancher version to the latest.

**Comment by danbigthink** [comment]
> I believe this is working as intended, besides the missing * in the UI. Kubernetes documentation for stateful sets [does say that it requires a headless service.](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations)
> 
> Perhaps the requirements changed from k8s from your rancher version to the latest.

Thanks for your response, you're correct, it does state this, but Rancher 2.4 used to take care of this for you. 
Now the newer version isn't providing the same consistent behaviour. I'd consider that a bug or missing feature.

I realize software changes over time, but typically the behaviours become more automated over time and not more obtuse.

**Comment by Angelinsky7** [comment]
nevertheless this bug is still there in 2.6.3 ("Sorry, no matching options" but services are created in the namespace)
So now, the only way to create a statefulset is by yaml

**Comment by slickwarren** [comment]
@Angelinsky7 please double check previous comments, you must have a headless service already deployed in the namespace you're working with[ in order to deploy a statefulset.](https://github.com/rancher/dashboard/issues/2553#issuecomment-997449842)

**Comment by Angelinsky7** [comment]
@slickwarren thanks for you answer, it's true that rancher show headless service in the combobox but i think that kubernetes accept any type of service not only headless' one (https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations, i think we should mitigate this statement `StatefulSets currently require a Headless Service to be responsible for the network identity of the Pods. You are responsible for creating this Service.` with `StatefulSets currently require at LEAST a Headless Service to be responsible for the network identity of the Pods. You are responsible for creating this Service.`) 
i tried with v1.22.5+k3s1 and v1.21.8 and successfully created a StatefullSet with a headless, clusterip and nodeport service...
but i maybe don't understand correctly the specs or the current implementation of k3s and kde doesn't respect the specs.
Anyway thanks again for you answer, and sorry for the "mis-argumentation".

**Comment by altulek** [comment]
StatefulSet can be created without service at all, so this option should NOT be required. 
What more, when you add port mapping Rancher will create appropirate service.

**Comment by gp187** [comment]
> @Angelinsky7 please double check previous comments, you must have a headless service already deployed in the namespace you're working with[ in order to deploy a statefulset.](https://github.com/rancher/dashboard/issues/2553#issuecomment-997449842)

I do and it still doesn't work. Works ONLY if you create the config manually. If you create using the API, it's not found

**Comment by scndel** [comment]
Issue still present on UI of **v2.8.1** with custom cluster imported (_OVH Managed Kubernetes_).
![statefulset service name required rancher v2 8 1](https://github.com/rancher/dashboard/assets/17161227/64c95206-b40a-413e-8999-bc61e7adb28f)

`"Service Name" is required`
