### ISSUE TITLE
Download YAML list action fails when multiple resources are selected

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2561]
- Clicking button does nothing
- Error in console `Error: Can't read the data of 'resources/<resource name>.yaml'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc)`

**Comment by anupama2501** [comment]
On v2.5-fa087c81628de057406608f077d0952bb03cea56-head

Cluster explorer --> auth providers --> Users --> create multiple users --> select all users and click on download yaml
The button works and the yaml for all the users are downloaded as a zipped file. [verified contents of a yaml]
Cluster explorer[select all namespaces] --> deployments --> select all deployments and click on download yaml [yaml downloaded as zipped folder] with all the yaml files.
Cluster explorer[select all namespaces] --> in the deployments create a deployment and download the deployment [file downloaded as yaml file].
