### ISSUE TITLE
App resource requirement warning is not skippable

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#2565]
2.5.6 introduced a warning when you try to install an app, but there are not enough resources available in the cluster. Ticket: https://github.com/rancher/dashboard/issues/1849.

<img width="1989" alt="Bildschirmfoto 2021-03-18 um 16 38 52" src="https://user-images.githubusercontent.com/243056/111653774-72149700-8808-11eb-8e05-5099f8e21bb6.png">

There is currently no way to skip this warning and install the app anyways. The ember UI had such a warning as well, but you could ignore it and install the app regardless.

A skip button actually make sense, because a user with a small cluster could still install the app, but change some of the default settings so that it will work in their cluster.

With Rancher monitoring, you could for example reduce the data retention, disable components like alertmanager or disable some of the exporters to reduce the necessary memory significantly.

This is actually what we are doing in or Rancher Rodeo webinars, where every attendee gets two small VMs to install Rancher, add a cluster and install monitoring in it with a couple of config changes to make it work on the small VM.

**Comment by slickwarren** [comment]
I think only monitoring has a restriction on install. I tested with other apps (istio, logging, longhorn, cis benchmark) and only monitoring gave the warning on v2.5-head 7002499
The following were tested on a cluster with 4vCPU and 8gb RAM:
* install monitoring -- expect warning to appear -- pass
* on warning screen, continue and install -- pass
* on warning screen, cancel -- pass
* once installed, edit cluster
  * warning screen should not appear -- pass
* uninstall monitoring, then reinstall
  * message should reappear, and above flow should work as expected -- pass
