### ISSUE TITLE
Dashboard groups clicking on global group name to be displayed in tabular form

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2572]
v2.5-fa087c81628de057406608f077d0952bb03cea56-head

Cluster explorer --> Users and authentication --> Assign global roles --> select a member and enable any global permissions/ built-in roles and create
Once created click on any of the global roles name of the above created group in the groups page --> redirected to yaml page
as follows: 

<img width="300" alt="Screen Shot 2021-03-22 at 2 44 56 PM" src="https://user-images.githubusercontent.com/38144301/112062444-31c15b80-8b1d-11eb-90f1-63ad42040cd8.png">
 
**Can this be changed to a tabular form as we have on the ember UI?**

<img width="300" alt="Screen Shot 2021-03-22 at 2 45 44 PM" src="https://user-images.githubusercontent.com/38144301/112062521-4d2c6680-8b1d-11eb-8ae7-f3d2a41ec0da.png">

https://github.com/rancher/dashboard/issues/2530

**Comment by richard-cox** [comment]
This is the default view page for a global role. I think we need a 'Role' detail page. Looks like a very similar component has been created via https://github.com/rancher/dashboard/issues/2111 

![image](https://user-images.githubusercontent.com/18697775/112820565-a1839900-907d-11eb-9c5c-acbe33d3e6e9.png)

**Comment by richard-cox** [comment]
This will be fixed by default as part of #2579

**Comment by anupama2501** [comment]
Verified on  v2.5-d1083bc63e4ddde70ffadd09bf0133ae5862b5fe-head
From cluster explorer --> Users and authentication --> Assign global roles --> select a member and enable any global permissions/ built-in roles and create
Click on the roles created, redirected to the tabular format:
<img width="400" alt="Screen Shot 2021-04-11 at 10 29 12 PM" src="https://user-images.githubusercontent.com/38144301/114344901-8b61e800-9b15-11eb-92e9-ed95b3c5ae53.png">
