### ISSUE TITLE
[Monitoring V2] Set prometheusOperator.hostNetwork to false by default and expose UI option

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2573]
Due to the initial Monitoring V2 UI requests in https://github.com/rancher/dashboard/issues/908, we specifically set `prometheusOperator.hostNetwork` to `true` for Managed Clusters in the following code block:
https://github.com/rancher/dashboard/blob/33481b2fec3b5b8982ce9500c799ae9c595e6ea1/chart/monitoring/ClusterSelector.vue#L132

However, as noted in https://github.com/rancher/rancher/issues/31786, this option is only required for Managed Clusters that utilize custom CNI, which is not necessarily the normal configuration for imported EKS clusters on Rancher.

To change this default behavior, we need to:
1. Remove the logic that set `prometheusOperator.hostNetwork=true` by default for Managed Clusters (shown above)
2. Expose a new field on the UI specifically for Managed Clusters (on the same page as where a user would select / view the detected Cluster Type) that says `Use Host Network For Prometheus Operator`. This should take in a radio button with True / False values and expose a tooltip that says `If you are using a managed Kubernetes cluster with custom CNI (e.g. Calico), you must enable this option to allow a managed control plane to contact the admission webhook exposed by Prometheus Operator to mutate or validate incoming PrometheusRules.`

gz#15838
gz#15787

**Comment by slickwarren** [comment]
though I have been unable to reproduce the [original issue](https://github.com/rancher/rancher/issues/31786), I did verify the following on master-head (55f0bb2):
* enabling `hostNetwork=true` via the yaml works as expected
* enabling `hostNetwork=true` via the UI checkbox works as expected in the following cases (checkbox only available for these cases:
  * GKE
  * EKS
  * AKS
* hostnetwork=false is the default in all cases

I think that it would also make sense to have `other` clusters show the checkbox, but will make a new ticket for that.
