### ISSUE TITLE
Affinities can not be removed when editing a deployment

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#2577]
### Steps to reproduce

* Create a deployment with a node affinity
![Bildschirmfoto 2021-03-26 um 14 13 54](https://user-images.githubusercontent.com/243056/112637060-0badfb00-8e3e-11eb-8def-400b058d408e.png)

* Next edit the deployment and remove the node affinity
![Bildschirmfoto 2021-03-26 um 14 14 20](https://user-images.githubusercontent.com/243056/112637091-136d9f80-8e3e-11eb-9ee4-e90c004f1727.png)

### What should happen

The node affinity gets removed from the deployment

### What is happening

The node affinity remains at the deployment. This happens regardless if you just change the radio button back to "Run pods on any available node", or if you remove the rule beforehand.

**Comment by kravciak** [comment]
On which rancher version can I reproduce this bug?

I tested the fix on v2.5-head (4115dee), works fine.
Test on master-head blocked on https://github.com/rancher/rancher/issues/31964

**Comment by bashofmann** [comment]
This is reproducible for me in 2.5.7.

**Comment by sowmyav27** [comment]
Closing based on the validations done on 2.5-head [here](https://github.com/rancher/dashboard/issues/2577#issuecomment-814800082)
