### ISSUE TITLE
Port Roles view to Dashboard

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2579]
![image](https://user-images.githubusercontent.com/18697775/112820112-35089a00-907d-11eb-9ca8-cf0c7c6c3104.png)

- Add 'Roles' page to `User & Authentication`
- Display tabbed view with lists for global, cluster and project roles
- This replaces the Cluster Explorer `Role Template` resource list, there `Project` was updated to `Project/Namespace`

Note - the 'Show Only Defaults' checkbox filter in the Ember UI will not be ported

**Comment by slickwarren** [comment]
I have tested the following on 2.5-head (d1083bc63e4ddde70ffadd09bf0133ae5862b5fe) with 2.5-dev UI:
create/edit/view all as admin -- pass
view only as standard user/base user -- pass
create/edit global as restricted admin -- pass
**create/edit all as restricted admin with `manage roles` enabled -- some failures** 

create global role— pass
edit new global role — pass
edit existing global role — pass
remove existong global role — pass
remove new global role — pass

create cluster role — pass
edit new cluster role — pass
edit existing cluster role- pass(with correct manage roles role)
remove existing cluster role— pass
remove new cluster role — pass
create locked role -> user should not be able to select this role — pass
assign role to user — pass
lock role - existing user still has those permissions, new users cannot get locked role — pass

create namespace role — pass
edit new namespace role — pass
edit existing namespace role- pass(with correct manage roles role)
remove existing namespace role— pass
remove new namespace role — pass
create locked role -> user should not be able to select this role — pass
assign role to user — pass
lock role - existing user still has those permissions, new users cannot get locked role — pass

add no verbs — pass
add 1 verb — pass
add multi verbs—pass
**add no resources —error (should be required)**
however, some built-in roles have no resource
add 1 resource (only allowed 1?) — pass
add no non-resource URL — pass
add no api groups — pass
add multiple resource grants — pass
inherit from (not avail for global) cluster — pass
inherit from project/namespace — pass
**set as default — fail (can set multiple at once)**
set as locked — pass

Rbac:
Admin — all permissions — pass
stdusr — view only — pass
baseusr — cannot view  — pass

### Overall:
the main functionality appears to work, the bugs that were found are filed [here](https://github.com/rancher/dashboard/issues/2675)
