### ISSUE TITLE
Volume Plugin for Storage class and PVs dropdown does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2590]
**On 2.5-head commit id: `118f999`**

- On a downstream cluster -->  Custer Explorer -->  Storage Classes
- Dropdown of Storage class does not work / list all the supported providers

<img width="957" alt="Screen Shot 2021-03-30 at 8 45 51 PM" src="https://user-images.githubusercontent.com/26032343/113087733-1c8da200-9199-11eb-8427-9c66b1a550b4.png">

**Note:**
Same issue is seen for a PV also --> PV --> Create --> Volume plugin dropdown

**Comment by gaktive** [comment]
Might be addressed by some of Nancy's work.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `93d921f `**

See this issue fixed
<img width="736" alt="Screen Shot 2021-04-06 at 1 50 46 PM" src="https://user-images.githubusercontent.com/26032343/113777166-906f0380-96df-11eb-8988-36feefe4a6bb.png">
