### ISSUE TITLE
configmap columns are not spaced nicely

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2602]
<img width="1423" alt="Screen Shot 2021-03-31 at 10 30 37 AM" src="https://user-images.githubusercontent.com/16691014/113186222-39af8880-920c-11eb-8901-55ed94d07c6c.png">
<img width="1522" alt="Screen Shot 2021-03-31 at 9 51 58 AM" src="https://user-images.githubusercontent.com/16691014/113186231-3d430f80-920c-11eb-94d2-c043dd5069aa.png">
configmaps with a lot of info in `data` skew the entire UI to look weird, shortening the names to make as much room as possible for this one field with a lot of data.

- I think the long-term fix for this would be to allow dynamically sized columns, and let the user decide how large each field is, but open to other fixes

**Comment by nwmac** [comment]
As of 2.6.2, I don't see this any longer and the columns look okay when there is a config map with many keys:

![image.png](https://zube.io/files/rancher/681b8a0cd3c993f5beda303f7e6735d3-image.png)

**Comment by slickwarren** [comment]
tested on v2.6-head (c682e30):
 name is now not scaling with window size, but secrets do (which looks much better)
<img width="1147" alt="Screen Shot 2022-02-02 at 3 28 46 PM" src="https://user-images.githubusercontent.com/16691014/152255089-7191234e-17d0-4dcd-a2bd-a7c19cdd348d.png">
