### ISSUE TITLE
Cluster - List/Detail pages

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#261]
Use this wireframe from rancher/dashboard#246 for list of clusters and cluster detail pages: 

https://xd.adobe.com/view/1698a334-b78b-47d2-6f23-2ab7bebb5ae5-60a9/

**Comment by westlywright** [comment]
Clusters API is currently being worked on so I'll hold off completing this until the API is further along.

**Comment by deniseschannon** [comment]
Based on new design, there is no cluster list page in Dashboard. It will only be single cluster views.

The Cluster detail page is the dashboard sizzle page being taken care of in #819
