### ISSUE TITLE
[Monitoring V2 UI] UI for AlertmanagerConfigs

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2612]
Backend Issue: https://github.com/rancher/rancher/issues/29871

The Dashboard UI needs to expose a UI for being able to modify the AlertmanagerConfig CRs that are deployed into the cluster if the CRD is installed on the cluster.

### AlertmanagerConfig

Specifies subsections of the Alertmanager configuration, allowing routing of alerts to custom receivers, and setting inhibit rules.

The AlertmanagerConfig [spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerconfigspec) takes in the exact same fields as Routes and Receivers UIs do today, so the Create for an AlertmanagerConfig should just reference the exact fields that would have been rendered there, except the payload will end up in the CRD instead of the Alertmanager Secret.

The only new thing we need to figure out a UI for is [Inhibit Rules](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#inhibitrule).

This UI corresponds to the field on the CRD's spec called `inhibitRules`. This field takes in a list of InhibitRules and should have the following description:

```
Inhibit Rules provide a way to silence a set of alerts when another set of alerts are firing. To specify an Inhibit Rule, you must specify matchers that correspond to the set of alerts that trigger a silence (Source Alerts) and matchers that correspond to the set of alerts that should be silenced (Target Alerts). You can also specify a condition that Inhibition should only take place when certain labels are equal between Source and Target Alerts
```

Each InhibitRule that is on the UI should have the following spec:

Header / Label Name | Description | k8s YAML | Input | Default
---|---|---|---|---|
Match Source Alerts | These matchers identify alerts that should trigger a silence | `inhibitRules[i].sourceMatch` | A list of `Matcher` UIs | `[]`
Match Target Alerts | These matchers identify alerts that should be silenced | `inhibitRules[i].targetMatch` | A list of `Matcher` UIs | `[]`
Ignore Unless Equal | If the labels provided here are not equal between the Source and Target alerts, inhibition will not take place | `inhibitRules[i].equal` | A list of Labels (strings) | `[]`

And the `Matcher` UI should expose the following fields per Matcher:
Header / Label Name | Description | k8s YAML | Input | Default
---|---|---|---|---|
Label | N/A | `name` | string | ""
Value | N/A | `value` |  string | ""
Use Regex |  Whether to interpret the provided Label as a regular expression | `regex` | boolean | `false`

**Comment by Martin-Weiss** [comment]
At the moment there is no nice way for devops/gitops/fleet to deal with the alertmanagerconfigs Rancher has in the UI.
A much better approach is using helm values and the best seems to be the usage of the alertmanagerconfigs CRD.

IMO we have to switch / migrate from the "old" UI based management of the alermanager secret settings to usage of alertmanagerconfig CRDs, only and allow the creation and management of them via UI, show already existing ones etc.

In case a customer has used "the old UI way" or helm values - I think we should "display" and allow migration..

**Comment by gaktive** [comment]
@aiyengar2 to refresh this to ensure it's up to date based on recent plans.

**Comment by catherineluse** [comment]
Per discussion with Arvind, the ihibitor configuration is not supported in monitoring V2, so it won't be in the forms in v2.6.5. It will be configurable in YAML.
