### ISSUE TITLE
[Monitoring V2] Provide global.cattle.url and expose a field on chart deploy / upgrade to modify under General

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2613]
Need this to construct the external URL in https://github.com/rancher/rancher/issues/29968#issuecomment-803109544.

**Comment by slickwarren** [comment]
tested the following on 2.5-head (ebee7eb): 
tested each of the following on single install and on HA install
* install monitoring -> global.cattle.url added automatically -- pass
* upgrade monitoring -> global.cattle.url added automatically -- pass
* override global.cattle.url on install -> new value used -- pass
* override global.cattle.url on upgrade -> new value used -- pass
* remove override -> global.cattle.url added automatically -- pass
