### ISSUE TITLE
[UI] [Monitoring V2] - New Receivers options on the Monitoring dashboard 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#2622]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement 

We will add those two options to the Receivers page on the monitoring dashboard:
- MS Teams
- ~Alibaba Cloud~ SMS

![image](https://user-images.githubusercontent.com/6218999/113599774-f0887b80-95f3-11eb-82bd-8882808c1839.png)

They are actually webhooks provided by the app rancher-alerting-drivers, so the UI is identical to the existing webhook one.

The URL is the DNS for the corresponding services. We assume the app is installed into the namespace cattle-monitoring-system, then the URL 
- for MS Teams is: ` http://rancher-alerting-driver-prom-to-teams.cattle-monitoring-system.svc:8089/v2/connector`
- for ~Alibaba Cloud~ SMS is: `http://rancher-alerting-driver-sachet.cattle-monitoring-system.svc:9876/alert`

(basically the pattern is `http://<service-name>.<name-space>.svc:<port><app-spefic-path>`)

We prefill the above URLs, and users can edit the URLs anytime. 

We also need to give users some information/explanation on the page saying that 
- rancher-alerting-driver is required for those receivers to work 
- the url is the DNS to the corresponding services. 

Update on 4/20:
- remove the words Alibaba Cloud from the UI because users can use any supported providers including Alibaba Cloud. So we decide to make the option generic.

**Comment by codyrancher** [comment]
@jiaqiluo based on our discussion yesterday. Would something like this be okay?

![special-webhooks](https://user-images.githubusercontent.com/55104481/113933177-1b680080-97a9-11eb-98c8-ab8b1ec206e3.gif)

**Comment by jiaqiluo** [comment]
LGTM

@aiyengar2 What do you think?  
We choose this approach, instead of listing them in the left bar, is because we cannot distinguish the MS Teams, Alibaba SMS, and a general webhook in the Alertmanger's configuration files because they look the same.

**Comment by aiyengar2** [comment]
Great idea! I like this a lot.

The only caveat I have is that, on opening a MS teams or Alibaba Receiver, we should have some sort of tooltip that informs them to update the namespace to that which rancher-alerting-drivers is installed in (and leave the default as cattle-monitoring-system).

**Comment by codyrancher** [comment]
Alright, I'll go ahead and do that.

**Comment by codyrancher** [comment]
I figured I'd file this issue for a couple future enhancements to this https://github.com/rancher/dashboard/issues/2651.

**Comment by jiaqiluo** [comment]
The UI needs to be updated to reflect some changes we made on the backend recently:

1. the default app name is 	`rancher-alerting-drivers` (we added the `s` at the end)
2. for MS Teams, the default name of the service is `rancher-alerting-drivers-prom2teams`, so on the receiver creation page, the URL needs to be updated to `http://rancher-alerting-drivers-prom2teams.cattle-monitoring-system.svc:8089/v2/connector`

**Comment by slickwarren** [comment]
The UI is operating as expected for rancher-alerting-drivers. a new ticket was added above to address certain enhancements.
the following were tested on v2.5.8-rc7:
* deploy rancher-alerting-drivers chart with at least 1 driver selected -- pass
  * readme contains links to all driver documentation -- pass 
  * deployment options in general tab are clear -- pass
 

* in monitoring, add a webhook -> new driver options
  * selections are clear -- #2744 for details on enhancements
  * default options are correct   -- #2744 for details on enhancements
  * warnings are helpful to user -- #2744 for details on enhancements
  * general use case -- values entered are used and working for alerts -- pass
