### ISSUE TITLE
[Logging v2] Enable Windows logging if target cluster is a Windows cluster

### ISSUE THREAD

**Issue by nickgerace** [rancher/dashboard#2626]
We need to set `.Values.global.windows.enabled` to `true` if the Logging v2 (3.9.4+) chart is being installed on a Windows cluster.

Source: https://github.com/rancher/charts/blob/4660ce9ad369300105b20f5d2290f943b636a536/packages/rancher-logging/generated-changes/overlay/templates/loggings/root/logging.yaml#L11-L25

Relevant issues:
- https://github.com/rancher/rancher/issues/28721
- https://github.com/rancher/rancher/issues/31644

**Comment by nickgerace** [comment]
The windows field is now available under `global.cattle`: https://github.com/rancher/charts/pull/1080

**Comment by izaac** [comment]
Rancher version `v2.5-head (04/08/2021)` _7426ba8_

`global.windows.enabled` is set to `false` when the cluster provider is Windows (this one is expected to be true by default).
`additionalLoggingSources.rke.windows.enabled` is set to true, but this one isn't used in the backend?

**Comment by nickgerace** [comment]
@vincent99 I'm curious if this piece of code is accidentally adding `windows.enabled` to `additionalLoggingSources.rke`:

```js
      if ( isWindows ) {
        setIfNotSet(cattle, 'windows.enabled', true);
      }
```

https://github.com/rancher/dashboard/pull/2639/files#diff-27accae8965d3554141dbd4f0b44a7f0c41545886015f1e0b24c36cb05b5ce7dR707-R709

**Comment by vincent99** [comment]
@nickgerace Not that piece, but it is set in the logging chart config component: https://github.com/rancher/dashboard/blob/master/chart/logging/index.vue#L24-L29

If that's really not needed (for any chart version?) then that can be removed.

**Comment by nickgerace** [comment]
@vincent99: I spoke to @paynejacob and it has not been used since Logging v2's inception. I believe we are good to remove it.

**Comment by nickgerace** [comment]
Closing in favor of https://github.com/rancher/dashboard/issues/2684 since `global.cattle.windows.enabled` is functional.

Source: https://github.com/rancher/rancher/issues/28721#issuecomment-818321740
