### ISSUE TITLE
dashboard Repositories Unknown state

### ISSUE THREAD

**Issue by golgotow** [rancher/dashboard#2630]
Hello,

I just add k3s cluster with 3 masters and 3 workes to rancher, and tried to enable charts repositories but all of them appear unknown, no logs or info why found.

How to troubleshoot this?
![ranch-k3s](https://user-images.githubusercontent.com/29871859/113714359-96b5ad80-96e8-11eb-831b-2331a05fe090.png)

Best regards

**Comment by vincent99** [comment]
K8s 1.20 is not supported by the version of Rancher you're running. Upgrade to the current 2.5.x.

**Comment by golgotow** [comment]
Hello,

Thank you for tip @vincent99 

Strange was that other cluster in same rancher have charts working without problem.

Best Regards
