### ISSUE TITLE
Rendering issue with pod logs/shell

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2632]
When you open pod logs or shell the bottom line with the control buttons and the status of the connection are out of the browser scope: 
![image](https://user-images.githubusercontent.com/22940823/110971111-2030c480-8363-11eb-9a41-1a3cae5fb2fd.png)

Tested on both Firefox 86.0 (64-bit) and Chromium 89.0.4389.82 (Official Build) snap (64-bit) on Ubuntu 20.04 

When downgraded to 2.5.5. this issue is not present 

(This issue was broken out from #2531)

**Comment by nwmac** [comment]
@sowmyav27 I couldn't reproduce this issue. Can you try again and add steps if you can. Thanks.

**Comment by vincent99** [comment]
You need a pod with more than one container in it; this is still a problem.

**Comment by kravciak** [comment]
I reproduced on 2.5.7, fix works fine in v2.5-head (fc4f592)

![Screenshot from 2021-04-09 11-51-07](https://user-images.githubusercontent.com/538604/114162983-f3ec7180-9929-11eb-9157-e44d3a4c5807.png)
