### ISSUE TITLE
UI for resources in statefulset does not match UI for resources in deployments -> if limit is lower than request, user should not be able to create

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2637]
How to reproduce: 
* create a statefulSet
  * add a resource request and limit request, where the request is higher then the limit
<img width="1540" alt="Screen Shot 2021-04-06 at 10 48 01 AM" src="https://user-images.githubusercontent.com/16691014/113755955-bd162180-96c5-11eb-82d1-f9af00b3b5f9.png">

Result: 
* kubernetes throws an error
<img width="1349" alt="Screen Shot 2021-04-06 at 10 48 32 AM" src="https://user-images.githubusercontent.com/16691014/113756013-ca331080-96c5-11eb-9591-2e7d29e48fd3.png">

Resource UI in other create/edit fields (i.e. deployments) throws an error in the UI. This is what should happen for any resource request done through the UI
<img width="1543" alt="Screen Shot 2021-04-06 at 10 47 37 AM" src="https://user-images.githubusercontent.com/16691014/113756148-edf65680-96c5-11eb-87d2-14217b272c2e.png">

**Comment by vincent99** [comment]
This is (lack of) server-side k8s validation, not UI or even Rancher.

**Comment by gaktive** [comment]
Closing this since this outside what can be done in the product. If you think something like this is needed, then file a new ticket against the rancher/rancher repo if the backend can pass along something to the UI.
