### ISSUE TITLE
Secret  (Cert, Reg) - List/Detail & Create/Edit

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#264]
Use this wireframe from rancher/dashboard#257 for list of secrets/secret detail/create secret pages:

https://xd.adobe.com/view/f6684727-5553-46f3-759e-76118e955b2e-8059/

**Comment by lvuch** [comment]
Headers for value on page 3 and 5 are incorrect (related workloads and values) should match "values" on page 2 and 4.

**Comment by tfiduccia** [comment]
UI/UX review:

- [ ]  Type field contents should be alphanumeric.  Secret should still be default
![image](https://user-images.githubusercontent.com/11514927/73981569-b0464400-48ef-11ea-99e3-577ea98d5974.png)

- [ ]  When I click on Type and I have Secret selected.  It show other fields as selected
![image](https://user-images.githubusercontent.com/11514927/73981633-dc61c500-48ef-11ea-858c-79bbdfe19646.png)

- [ ]  Is there a way to turn off the auto fill?
![image](https://user-images.githubusercontent.com/11514927/73981673-f56a7600-48ef-11ea-94e3-ee9787fe00e5.png)

- [ ]  Value Field default text and typed text is not centered in field.  It's in upper left
![image](https://user-images.githubusercontent.com/11514927/73981715-0f0bbd80-48f0-11ea-8e40-ef10485e72d7.png)
![image](https://user-images.githubusercontent.com/11514927/73981721-13d07180-48f0-11ea-8351-d0fb8b9d0806.png)

- [ ]  Line height is missing for Description field.  I know this will add space to other fields as well.  But if you have something misspelled or descenders it starts to really look crowded
![image](https://user-images.githubusercontent.com/11514927/73982352-4cbd1600-48f1-11ea-8f4a-34ec1d94cec2.png)

- [ ]  Turn off Spell check for Value cause this will have cert info in it and will probably be just one long big red line

- [ ]  Do we want more space between rows?
![image](https://user-images.githubusercontent.com/11514927/73982742-17fd8e80-48f2-11ea-939a-5b9d2ce4c992.png)

- [ ] Clicking on Type then trying to create a secret give me an error
![image](https://user-images.githubusercontent.com/11514927/73982733-0f0cbd00-48f2-11ea-8d88-29e49905fb7f.png)

- [ ] Example text should be there all the time and the color needs to be lighter then the label text
![image](https://user-images.githubusercontent.com/11514927/73984967-32863680-48f7-11ea-8064-d159edc99684.png)

- [ ] Namespace section of field seems too large
![image](https://user-images.githubusercontent.com/11514927/73985079-7f6a0d00-48f7-11ea-9e29-fad19763e232.png)

- [ ] Add & Read from File - change so no icon and the casing should be all caps (maybe fonts wrong as well?)
![image](https://user-images.githubusercontent.com/11514927/73985287-08814400-48f8-11ea-88c6-012702bb9b1c.png)

- [ ] Add default text to registry domain Name field and make it says 'e.g. index.docker.io'
![image](https://user-images.githubusercontent.com/11514927/73985399-4716fe80-48f8-11ea-8203-83aa8919de04.png)

**Comment by lvuch** [comment]
@mantis-toboggan-md could you take a look at these last couple of tasks?

Here are some notes from what I've marked as complete and the last few that need completed
- autofill is browser feature that we cannot/should not override as it is user preference
- I think this is the case for spell check as well
- I can’t seem to get label and placeholder to not be different colors
    - on dark the label should be #B6B6C2 (secondary) and the placeholder should be #6C6C76 (disabled)

Thanks!

**Comment by deniseschannon** [comment]
Feedback based on convo with @ibuildthecloud 

* List View - Header Edits
    * Instead of “Detail” -> “Data”
    * Type for service account tokens should be “Service Acct Token” not just “Service Acct”
        * When it’s a service account token, you can link back to the service account in the same namepsace and find it based on the annotations, service account names are unique in the same namespace: 
```
annotations:
    kubernetes.io/service-account.name: <service_account_name>
```
* Create/Edit Pages
    * "Type" dropdown field should be able to select from choices but also ability to input free form text. But currently, it's weird/hard to do @lvuch can you look into this? 
        * Example: Ability to use “kubernetes.io/service-account-token” as a type and gets weird right now when trying to "Edit" the token.
    * "Type Fields" should be  Certificate, Registry, Opaque
       * Specifically "Secret" should be switched to "Opaque". Opaque is the correct k8s term.
    * Add Labels and Annotations tabs (all resources can have labels and annotations added to them)
* View Detail Page
    * If we call it "Data" in the Create/Edit page, we should call it "Data" in the view page.
    * Add ability to view Labels and Annotations


Note for reference: We dropped the ability to select multiple namespaces when creating a secret. In Ember we had the ability to create a secret for all namespaces in a project, but removing this functionality for now in Vue.

**Comment by vincent99** [comment]
> "Type" dropdown field should be able to select from choices but also ability to input free form text. But currently, it's weird/hard to do @lvuch can you look into this?

https://vue-select.org/guide/values.html#tagging

**Comment by lvuch** [comment]
Placeholder text should make it more obvious that it's both a text area and dropdown

**Comment by deniseschannon** [comment]
@lvuch Can you fix the font size/layout of the provider for Registry?
<img width="490" alt="Screen Shot 2020-04-20 at 4 06 19 PM" src="https://user-images.githubusercontent.com/11410997/79807831-e9078e00-8320-11ea-9817-5e84320dd3a5.png">

**Comment by deniseschannon** [comment]
Design issue with Type dropdown filed in https://github.com/rancher/dashboard/issues/552

# Edit Secret Page

[ ] When editing a "service account token" secret, the type dropdown is broken. It's populated correctly, but I cannot change it. 

<img width="610" alt="Screen Shot 2020-04-24 at 3 00 01 PM" src="https://user-images.githubusercontent.com/11410997/80260260-562a6480-863c-11ea-9680-aea34195e950.png">


# Detail Secret Page

[ ] When looking at secret that is a different type from "Certificate, Registry, Opaque", it's showing up like this. It should just show `Service Acct Token`, which is the `typeDisplay`

<img width="769" alt="Screen Shot 2020-04-24 at 3 13 32 PM" src="https://user-images.githubusercontent.com/11410997/80261043-3bf18600-863e-11ea-8ce6-8da3a4eaf955.png">

[ ] Missing Labels and Annotations tabs from the detail page

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/554

**Comment by deniseschannon** [comment]
Open Remaining Issues for @mantis-toboggan-md :

Type Dropdown
- [ ] It now allows us to type free form text, but I can't actually use it to input free form text as a value. -> 

# Edit Page
- [ ] Clicking on Type then trying to create a secret give me an error
![image](https://user-images.githubusercontent.com/11514927/73982733-0f0cbd00-48f2-11ea-8d88-29e49905fb7f.png)
  - [ ] Side note: I can't seem to create a certificate secret to view what it looks like after creation. I keep hitting this error. 

# List Page
- [ ] Type should be converted from the k8s name to the friendly name
    [ ] Type: `Docker JSON` -> `Registry`
    [.] Type: <whatever the value of a cert> -> `Certificate. Note: This might be a certificate already but I am having issues creating certificates

# Detail Page
- [ ] Fix labels and annotations to be in read-only/view mode for detail page
- [ ] For the data in the `SortableTable` can we display all the content in the fields in the rows? We are cutting off the data for no reason. 


<img width="1043" alt="Screen Shot 2020-04-27 at 1 44 47 PM" src="https://user-images.githubusercontent.com/11410997/80419180-7ef56880-888d-11ea-977c-e6cfc6ab47a5.png">

**Comment by deniseschannon** [comment]
## Detail Page

### Certificate Type

- [ ] When viewing an existing certificate, it pulls the data in the "Opaque" type detail instead of looking like the "Certificate" type. The detail page should be similar to Edit page, showing the 2 fields `Private Key` and `CA Certificate` with Headers.

### Registry Type

- [ ] The address is showing up a link, but it shouldn't be a link as it's not a valid link. 

<img width="583" alt="Screen Shot 2020-04-29 at 11 47 47 AM" src="https://user-images.githubusercontent.com/11410997/80634389-45e50180-8a0f-11ea-8a79-bec620e8a2da.png">

## Edit Page

### Certificate Type
- [ ] When editing a certificate, it isn't populating the `Private Key` or `CA Certificate` fields with the data. Instead, it's populated under the "Opaque" type fields. 

## Registry Type
- [ ] When editing an existing a registry type that has something that's not Dockerhub, it's not populating the correct radio button for `Address`. By default, if it doesn't' match any of the first 3 options, it should default to custom.

**Comment by deniseschannon** [comment]
## Detail Page

### Opaque Type
This should be using the KeyValue component instead of a Sortable table so that it matches the Edit page. 

### Certificate Type
- [ ] It should be `CA Certificate` instead of `Certificate` to match the Edit page header

## Edit Page

- [ ] Unable to edit the type of secret
- [ ] Example Text:
- Private Key: `Paste in the private key, typically starting with -----BEGIN RSA PRIVATE KEY-----` 
- CA Certificate: `Paste in the CA certificate, starting with -----BEGIN CERTIFICATE-----`

**Comment by mantis-toboggan-md** [comment]
@deniseschannon from what I can see editing the 'type' field of secrets is not supported; trying returns the error:  

"message": "Secret \"test-change-type\" is invalid: type: Invalid value: \"kubernetes.io/tls\": field is immutable", "status": 422

**Comment by deniseschannon** [comment]
## Detail Page

### Opaque Type

- [ ] Somehow the protip is underneath the Title

<img width="641" alt="Screen Shot 2020-05-04 at 2 36 53 PM" src="https://user-images.githubusercontent.com/11410997/81016181-d018d580-8e14-11ea-8fc3-c8d0bf7628e1.png">

Overall, there are some design issues that will be taken care of other issues (KeyValue component https://github.com/rancher/dashboard/issues/589, masthead https://github.com/rancher/dashboard/issues/538#issuecomment-623722980)

**Comment by mantis-toboggan-md** [comment]
> * [x]  Example text should be there all the time and the color needs to be lighter then the label text
>   ![image](https://user-images.githubusercontent.com/11514927/73984967-32863680-48f7-11ea-8064-d159edc99684.png)

To clarify, this was discussed in a zoom call: all labeled inputs with example text should show that text by default and hide it when hovered. The example text should be less prominent than the label(darker than label on the dark theme, lighter than label on the light theme)

**Comment by sangeethah** [comment]
Validation for  Secret (Cert, Reg , Opaque)  for List/Detail & Create/Edit pages is done.
Issues found when testing these pages are tracked as different issues.
