### ISSUE TITLE
Add Descriptions and More Info links to Secrets and Roles

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2644]
See rancher/dashboard#2595 

The cards are sparse and need descriptions. We should also link to the Kubernetes documentation for each.

**Comment by nwmac** [comment]
If you look at Workload -> Create - essentially we want the same as there but for Secrets and Roles.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `1a57856`**

Secrets have the more info link:
<img width="1415" alt="Screen Shot 2021-09-17 at 3 55 51 PM" src="https://user-images.githubusercontent.com/26032343/133861917-195040d0-8c57-41d0-bbf0-5cae2b319952.png">

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `1a57856` pulled 9/17/21 ~9:30am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2 (but type does not matter)
Downstream K8s version: v1.21.4+rke2r2 (but does not matter which version)
 
**Validation steps:**

1. Create a cluster - in my case I created an RKE2 cluster with the digitalocean node driver. 1 node.
2. Explore the cluster and on the left nav pane, go to Storage > Secrets. Click the Create button.
Note there are now "More info" links for each type of secret the user can created, as per the PR:
![image](https://user-images.githubusercontent.com/45179589/133861987-72659e84-f01c-42cf-86a3-9dc3f28e122b.png)
3. Navigate to each of these "More Info" links and ensure that each resolves properly and I am routed to the correct documentation.
Note these indeed appear to work correctly, and will bring me to the correct section on the Kubernetes Secrets docs page:
- HTTP Basic Auth takes me to https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret which seems correct to me.
- Registry takes me to https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets which is correct.
- TLS Certificate takes me to https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets which is correct.
- Opaque takes me to https://kubernetes.io/docs/concepts/configuration/secret/#opaque-secrets which is correct.
- SSH Key takes me to https://kubernetes.io/docs/concepts/configuration/secret/#ssh-authentication-secrets which is correct.
 
**Additional Info:**
Note, as per notes in the PR "Roles" was removed and therefore is not tested.
