### ISSUE TITLE
Namespace selector closes when you select an option

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2645]
Previously, the namespace selector allows you to select multiple - clicking an option keeps the dropdown open.

This behvaiour no longer works and clicking a namespace/project closes the dropdown rather than keeping it open

**Comment by sowmyav27** [comment]
**On 2.5.8-rc1**

Reproduced the issue
- In the namespace dropdown, select a namespace, dropdown closes

**On 2.5-head commit id: `9b0058c `**
- In the namespace dropdown, select a namespace, user is able to select multiple namespaces without the dropdown getting closed.
