### ISSUE TITLE
Pod Log/Shell: Can not change to a different container

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2646]
To test, you need a pod with multiple containers running.

Open a shell onto the pod - the shell with show for the first container and the drop-down will allow you to switch container.

Changing the container results in the whole shell window closing, rather than the shell opening on the different container.

**Comment by kravciak** [comment]
I reproduced on 2.5.7, fix works fine in v2.5-head (fc4f592)

![Screenshot from 2021-04-09 11-58-31](https://user-images.githubusercontent.com/538604/114163845-ee435b80-992a-11eb-84fa-19ec7f73ed59.png)
