### ISSUE TITLE
Constraint Template read from file mangles rego

### ISSUE THREAD

**Issue by jbartlet** [rancher/dashboard#2647]
If I create a Gatekeeper constraint template manifest on my local system and then use the 'read from file' option in the Rancher UI (Cluster Explorer) to import the yaml, the rego section is mangled upon clicking 'create'. The preview looks fine after it is read, but the actual import seems to have issues parsing the text. Templates are fine if applied via kubectl.

Preview after clicking 'Read from file' and selecting file:

```
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8scontainerreservation
      
      match_reservation[name] {
        ctrSpec := input.review.object.spec.template.spec
        name := ctrSpec.containers[_].name
        ctrSpec.containers[_].resources.limits.cpu <= input.parameters.limits.cpu
        ctrSpec.containers[_].resources.limits.memory <= input.parameters.limits.memory
      }
      
      match_reservation[name] {
        ctrSpec := input.review.object.spec.template.spec
        name := ctrSpec.containers[_].name
        ctrSpec.containers[_].resources.requests.cpu >= input.parameters.requests.cpu
        ctrSpec.containers[_].resources.requests.memory >= input.parameters.requests.memory
      }

      violation[{"msg": msg}] {
        ctrSpec := input.review.object.spec.template.spec
        allCtr := {ctr | ctr := ctrSpec.containers[_].name}
        badCtr := allCtr - match_reservation
        count(match_reservation) != count(ctrSpec.containers)
        msg := sprintf("One or more containers did not meet resource reservation requirements - %v", [badCtr])
      }
```
After clicking 'create' in UI and then showing YAML for template:
```
  targets:
  - rego: "package k8scontainerreservation\n\nmatch_reservation[name] {\n  ctrSpec
      := input.review.object.spec.template.spec\n  name := ctrSpec.containers[_].name\n
      \ ctrSpec.containers[_].resources.limits.cpu <= input.parameters.limits.cpu\n
      \ ctrSpec.containers[_].resources.limits.memory <= input.parameters.limits.memory\n}\n\nmatch_reservation[name]
      {\n  ctrSpec := input.review.object.spec.template.spec\n  name := ctrSpec.containers[_].name\n
      \ ctrSpec.containers[_].resources.requests.cpu >= input.parameters.requests.cpu\n
      \ ctrSpec.containers[_].resources.requests.memory >= input.parameters.requests.memory\n}\n\nviolation[{\"msg\":
      msg}] {\n  ctrSpec := input.review.object.spec.template.spec\n  allCtr := {ctr
      | ctr := ctrSpec.containers[_].name}\n  badCtr := allCtr - match_reservation\n
      \ count(match_reservation) != count(ctrSpec.containers)\n  msg := sprintf(\"One
      or more containers did not meet resource reservation requirements - %v\", [badCtr])\n}\n\n
      \ \n"
    target: admission.k8s.gatekeeper.sh
```
Version: Rancher 2.5.7

**Comment by vincent99** [comment]
These are "equivalent" objects that represent the same data.

There are many (really surprisingly many) different ways to encode a multi-line string in YAML.  The resources in k8s are stored as JSON, so your input is converted YAML->JSON, stored in etcd, then converted back to YAML for display in the UI (or kubectl).

JSON has exactly one way to represent a string, so it is not possible to "know" which way you encoded the string and round-trip that back to the same encoding when viewing the YAML later.

But you could argue that we could pick a "nicer" encoding for them, as apparently kubectl does.

**Comment by jbartlet** [comment]
You could argue that...so I will ;-).

 It would be helpful for readability if the rego was left in the "nicer" format since the Rancher UI (Cluster Explorer>OPA Gatekeeper>Template) currently highlights that section making it very legible when going through your ConstraintTemplates. The two included sample templates from Rancher have the 'nice' formatting, and importing via kubectl also preserves that.

I have no issue working around it by using the CLI but it seems odd to me for the UI team to implement syntax highlighting for legibility but then defeat that with the 'Read From File' function. I have attached screen cap snippet showing the Rancher UI display of a kubectl imported ConstraintTemplate vs the 'Read From File' imported one (same file).

My input file is just YAML of course, soft tabs, UTF-8 encoding.

<img width="948" alt="kubectl_import" src="https://user-images.githubusercontent.com/29124419/114433934-68c0e500-9b90-11eb-9c63-c3e353ad5f88.png">

<img width="1110" alt="read_from_file" src="https://user-images.githubusercontent.com/29124419/114434027-87bf7700-9b90-11eb-9b43-e3326f522a65.png">

**Comment by catherineluse** [comment]
This issue was originally reported in v2.5.x, which is no longer maintained except for a few security fixes. Is the issue still reproducible in v2.6.x?

**Comment by jbartlet** [comment]
Closing this issue. We no longer use the UI for this functionality.
