### ISSUE TITLE
Auth Provider: Add title and info

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2654]
The Auth Provider page just shows the boxes for the auth providers.

We should add:

- A page title: "Authentication Provider"
- Info box below the title

The text of the info box should be:

- When no auth provider is configured - "Local Authentication is always enabled but you may select another additional authentication provider from those shown below"

When an auth provider is configured (e.g. for GitHub) , the green info box says "GtiHub is currently enabled." - can we change this to "The GitHub authentication provider is enabled."

**Comment by anupama2501** [comment]
Verified on b2f8824

From explorer auth providers

1. Explorer UI has the` Manage accounts` link and the user is taken to the Users tab that displays all the users.
2. While the Auth is not enabled, a message is displayed - logged in as `admin`. If the auth is enabled and if we disabled it, the user logged in is shown as the auth provider user. 
> Enabled openLDAP auth user - user1.
> Message shows that the logged in user is user1
> Disabled the auth and the message shows, logged in as user1 for the auth providers.
> If we log out and re login as  admin, message shows logged in as admin.
