### ISSUE TITLE
Auth Provider Config: Steps should be grouped as per the Ember UI

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2655]
When configuring an auth provider (e.g. GitHub) - we show a single box with 3 groups of list items. You can't really tell they're in 3 groups, other than spacing looking different between them.

In Ember, we had nice numbering on the steps and the UI was nice and clear.

We should update the presentation to number the steps and make it clear what the sequence of actions that are required - use the Ember UI as a reference.

**Comment by anupama2501** [comment]
Verified on master-8c014efa85314ab1cb1cb79261d2db9251ccf31d-head
Each step is updated in separate boxes comprehensively. 
  
Re-opening for:

1. Space is missing between the radio button _"A private installation of GitHub Enterprise"_ and _"Step1"_
2. Space is missing between the text box _"Step1"_ ,  _"GitHub Enterprise Host"_ ,  and the radio button _"A private installation of GitHub Enterprise"_ when the radio button is enabled 

<img width="465" alt="Screen Shot 2021-05-10 at 11 51 01 AM" src="https://user-images.githubusercontent.com/38144301/117709666-0e627680-b186-11eb-986b-833d84241d9d.png">

**Comment by anupama2501** [comment]
Verified on commit: [d60543a](url) master-head
Explorer --> Users and Authentication --> Auth provider --> Github 

- Space between the radio button and step1 is present 
- Spacing between the text box "Step1" , "GitHub Enterprise Host" , and the radio button "A private installation of GitHub Enterprise" when the radio button is enabled

**Comment by anupama2501** [comment]
Reopening for: 
 
Color of the step1 should be changed for light and dark versions as it is not visible in both of the versions:

<img width="300" alt="Screen Shot 2021-05-23 at 3 30 04 PM" src="https://user-images.githubusercontent.com/38144301/119278706-d3c3f980-bbdb-11eb-87e3-5bd1e3dd65de.png">
<img width="300" alt="Screen Shot 2021-05-23 at 3 30 33 PM" src="https://user-images.githubusercontent.com/38144301/119278707-d58dbd00-bbdb-11eb-8205-dd7df45a528b.png">

**Comment by anupama2501** [comment]
Verified on master-head commit id 618c9ef
Cluster explorer -> Users and auth Providers --> github --> color of the steps are visible for both light and dark version of the UI
<img width="300" alt="Screen Shot 2021-06-01 at 8 55 30 PM" src="https://user-images.githubusercontent.com/38144301/120421746-b6013d80-c31b-11eb-979b-6f511da1c5c0.png">
