### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#266]
Need Design

**Comment by lvuch** [comment]
WIP: https://xd.adobe.com/view/a33e79c8-4fca-4d4e-79aa-bae9723520ce-d50f/

Would like feedback on these tab groupings
###ui
ui-index
ui-pl

###auth
auth-user-info-max-age-seconds
auth-user-session-ttl-minutes
auth-user-info-resync-cron

###server
cacerts
ingress-ip-domain

###urls
engine-install-url
engine-iso-url
server-url

###other
cluster-template-enforcement
telemetry-opt
system-default-registry
rke-metadata-config

**Comment by deniseschannon** [comment]
Closing in favor of new issue/design for when prioritized
