### ISSUE TITLE
Issues in google Auth dashboard UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2667]
I have broken this original ticket in 3 and left this issue as the remaining issue 4. Other issues are rancher/dashboard#2689 and rancher/dashboard#2690

**Issue 4**
- Nested Group Membership is missing from Authentication section after google Auth is enabled
<img width="1255" alt="Screen Shot 2021-04-09 at 9 56 36 PM" src="https://user-images.githubusercontent.com/26032343/114259195-25445c00-9981-11eb-8e43-140818214b25.png">

**Comment by nwmac** [comment]
@sowmyav27 Can I clarify - the screenshot for issue 4 is of the Ember UI - I see the checkbox for Nested Group Membership is present on the Vue UI for GtiHub Auth setup - is the bug on the Ember UI or Vue ?

**Comment by nwmac** [comment]
@sowmyav27 I can not reproduce this issue in the Dashboard UI, can you retry and provide steps to reproduce.

**Comment by sowmyav27** [comment]
**Steps:**

- Enable google Auth in Ember UI - Nested Group membership - Enabled/Disabled
- The value of Nested Group membership - Enabled/Disabled is seen on Ember UI after the Auth is enabled
- The value of Nested Group membership - Enabled/Disabled is _not_ seen on Cluster Explorer/Dashboard UI after the Auth is enabled

<img width="719" alt="Screen Shot 2021-04-14 at 6 34 45 AM" src="https://user-images.githubusercontent.com/26032343/114719437-ee0cdc80-9ceb-11eb-9db2-6f8727eadb29.png">

**Comment by sowmyav27** [comment]
On 2.5.8-rc4, [this issue](https://github.com/rancher/dashboard/issues/2667#issuecomment-819524937) is still seen.

**Comment by mantis-toboggan-md** [comment]
This should be fixed in 2.5-head, but it isn't in dashboard's 2.5.8-rc4

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `41f173a `**

See this fixed - when Nested Group membership is either Enabled or Disabled.
<img width="470" alt="Screen Shot 2021-04-15 at 11 28 35 AM" src="https://user-images.githubusercontent.com/26032343/114919963-c5fda600-9ddd-11eb-8b2e-2dba7af5c423.png">
