### ISSUE TITLE
2.6 UX: Apps & Marketplace Improvements: Chart Details Page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2669]
- Currently details and install experience is combined into a single page
- Split out details into a separate page
  - Single line header with logo
  - Rancher and Helm READMEs are now stacked vertically
  - Right section should list chart versions and additional available metadata (homepage, authors, etc). See Artifact Hub for more types
- Provide install button to install the currently selected version

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 5d2b7ac`

Details page and install are now on separate pages.
Details page (OPA Gatekeeper used as example):
![Screen Shot 2021-05-17 at 5 35 51 PM](https://user-images.githubusercontent.com/57409052/118573425-63c6f680-b737-11eb-84b1-908ef849dd09.png)
Install page is broken into steps:
![Screen Shot 2021-05-17 at 5 36 24 PM](https://user-images.githubusercontent.com/57409052/118573437-6a556e00-b737-11eb-90a5-df4b64f4d9b7.png)

The install button will install the selected version on the right section.
