### ISSUE TITLE
Workloads - List/Detail & Create/Edit

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#267]
Need Design

**Comment by lvuch** [comment]
https://xd.adobe.com/view/84134770-bb08-4d0c-736d-1f0aa44b36fd-f222/

**Comment by tfiduccia** [comment]
Field information:
Main fields:  

First Section:  Namespace/Name, Description, Type (Deployment (Rancher shows as "Scalable deployment of [n] pods"), DaemonSet ("Run one pod on each node"), StatefulSet ("Stateful set of [n] pods"), CronJob ("Run on a cron schedule"), Job, ReplicaSet, ReplicationController, Pod)

Second Section: Image
Third Section: Port Mapping, Public Host POrt, Prive Container Port, Protocol, Add button to add additional

View More Options - brings up Tab Component.
Fields & Order of tabbed component for both Add & Details

Tab1: Command - Command (entrypoint in rancher), Arguements (command in rancher), working Directory, interactive/tty/read only root checkbox, memory reservation, CPU Reservation, User Number, group number, Environment variable (+ with Key = Value fields), Values from Resource (Type drop-down that has Secret, ConfigMap, Field, Resource).  Source, Key , Prefix/Alias.
Tab2: Network - Network Mode, DnsPolicy, Hostname, Nameservers, Search Domains, Host Aliases.
Tab3: Volumes - Add Volume (TBD - Let's chat about this one with Vincent)  
Tab4: Healthcheck - health command, health Failure Threshold, Health Header, Health Interval, Health Success Threshold, Health Timeout, Health Initial Delay, Health URL
Tab5: Security - Pull Image, Priviledged Privilege Escalation, User HOst's PID Namespace, use Host's IPC Namespace, Run as Non-Root, Read-Only Root Filesystem, Add Capabilities & Drop Capabilities
Tab6: Scheduling - Option to select a specific node or auto-pick nodes.  If Auto, Need - Require All of: rule, Require Any of rule, Prefer Any of Rule sections.  Memory Reservation, CPU Reservation, NVIDIA GPU Reservation sections that are found in Security & Host Config in current UI.
Tab7: Scaling/Upgrade Policy: Radio options - Rolling (start new & then stop old), Rolling (Stop old then start new, Kill all pods then start new, Custom)  Minimum Ready Time, Progress Deadline, Batch Size for Rolling options, For Custom - Max Surge & Max Unavailable
Tab8: Labels & Annotation

**Comment by tfiduccia** [comment]
Main work for workloads is complete.  Will handle all other bugs/redesign in new issues.
