### ISSUE TITLE
2.6 UX: Apps & Marketplace Improvements: Install Chart Process

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2670]
- Move process into a stepper
  - Step 1 - basic rancher/helm cli values 
     - Provide name/namespace/description etc 
  - Step 2 - Values 
     - Step should contain settings only for values.yaml
     - Existing tabs should be combined into a single vertical scrollable section accompanied with a scroll spy like side menu on the right
  - Step 3 - helm cli overrides
- Steps / Current step indicator should be shown at top 
- Step actions (cancel, back, next) should be stickied to bottom of screen

**Comment by richard-cox** [comment]
Notes for QA
Here's some area's that are good to test. These aren't the best instructions, happy to have a call to run through them

- Install an old version of a Cluster Tool (Apps & Marketplace --> Charts --> any from `Rancher` repo). In a fresh cluster the project should be requested in step 1. Then upgrade that cluster tool via the Cluster Tools page (it should show an upgrade as available). The project should not be requested in step 1.
- Exercise some of the warning
  - Using a cluster that's struggling (for instance a cluster with less than 4.5 cores available) attempt to install the `Monitoring` cluster tool (Apps & Marketplace --> Charts --> Monitoring). There should be a warning at the top. After clicking install there should be another warning on step 1. User should not be able to proceed without accepting warning
- Exercise some of the requires/errors
  - Attempt to install the v1.7.100 of the Istio cluster tool on a cluster without the `monitoring.coreos.com.prometheus/v1` resource available. There should be a red warning regarding installing another app
- Exercise some of the auto-install feature
  - Install Longhorn and ensure another app (longhorn-crd) is installed as well
- Exercise some of the different ways helm values are supplied in step 2 of the Install Charts process. Everything in the step should work fine and ne applied when installing the chart
  - Install a chart with only YAML values (add the repo `https://cloudfoundry.github.io/stratos` and use the `console` chart). 
  - Install a chart with questions (External IP Webhook). 
  - Install a chart with custom values (Istio, Gatekeeper, Monitoring).
- Ensure the dashboard handles missing chart repos
  - Install a specific version of a chart (not latest, console above will be fine). Upgrade to latest version. Remove this chart's repo and attempt to edit/upgrade (should be forced to try and find chart). Cancel stepper flow & add repo back. Should then be able to get through edit app stepper fine

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 55f0bb2`
Tested the following use cases:
1. **Deploy an old version of a chart and upgrade it:**
Installed OPA Gatekeeper 3.1.100
The project is requested in step 1
![Screen Shot 2021-05-17 at 5 36 24 PM](https://user-images.githubusercontent.com/57409052/118737165-1e6afd80-b7f9-11eb-8297-06d8e73f0cc9.png)
From Cluster Tools, upgrade the chart to latest (v3.3.1+up3.3.0)
![Screen Shot 2021-05-18 at 4 23 33 PM](https://user-images.githubusercontent.com/57409052/118737175-262aa200-b7f9-11eb-85ba-9972fe00f8ca.png)
Project is not requested. Chart is upgraded successfully.
2. **Validate warnings:**
Attempt to install Monitoring on a cluster with less than 4.5 cores available.
User is warned on chart detail page:
![Screen Shot 2021-05-18 at 4 49 54 PM](https://user-images.githubusercontent.com/57409052/118737199-32166400-b7f9-11eb-80ad-2f17f7e4b4c3.png)
After selecting install, the user is warned again on step 1:
![Screen Shot 2021-05-18 at 4 51 31 PM](https://user-images.githubusercontent.com/57409052/118737300-6be76a80-b7f9-11eb-8ec4-6957252319d9.png)
The user IS able to proceed with the install without having to accept warning.
3. **Validate requirement warnings:**
Attempt to install Istio v1.7.100
User is not given the option to install. Blocked by a red warning.
![Screen Shot 2021-05-18 at 4 26 03 PM](https://user-images.githubusercontent.com/57409052/118737430-bcf75e80-b7f9-11eb-974b-711d67a0bdfe.png)
4. **Validate auto-install:**
Install longhorn latest (1.1.100+up1.1.1)
Longhorn crd longhorn-crd:1.1.100+up1.1.1 is also installed
5. **Validate install step 2 (values):**
Install a chart with only YAML values (add the repo https://cloudfoundry.github.io/stratos and use the console chart).
Chart is deployed successfully using default yaml found here (https://github.com/cloudfoundry/stratos/blob/master/deploy/kubernetes/console/values.yaml)
6. Validate missing chart repo:
Install opa gatekeeper 3.3.000.
Upgrade to latest 3.3.1+up3.3.0
Delete Rancher chart repo
Attempt to edit/upgrade
Chart is empty
![Screen Shot 2021-05-18 at 5 06 49 PM](https://user-images.githubusercontent.com/57409052/118738267-786cc280-b7fb-11eb-88fc-3589d21175ef.png)
Add the Rancher chart repo and attempt to edit again.
User is able to go through stepper flow.

**Comment by aaronRancher** [comment]
Ran some light smoke testing by deploying Monitoring (14.5.101+up14.5.0), OPA Gatekeeper (3.3.1+up3.3.0
), Logging (3.9.401+up3.9.4), and external IP webhook (0.1.601+up0.1.6)

On chart install, the logs do not populate in the bottom window. `There are no log entries to show in the current range.`
Helm operations can fail with `exit code: 123`, which is not detailed enough to debug.
Currently, it is difficult to debug why a chart has failed to deploy. It can error with `This resource is currently in an error state, but there isn't a detailed message available.`

**Comment by aaronRancher** [comment]
Chart install is available functionally in dashboard. Will track QA questions and feedback here: https://github.com/rancher/dashboard/issues/3057
