### ISSUE TITLE
Apps & Marketplace Improvements: Installing Process

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2671]
- Going on the install steps of...
  1. CRD (Custom Resource Definition) created successfully
  2. helm cli pod brought up
  3. helm cli command executed successfully
  4. helm cli install logs available
  5. app is up and running
- If step 1 fails user is shown error whilst still in stepper
- If step 1 completes user is shown new 'installing' page with spinner and description of step
- After step 2 user is given the option to view the logs
- After step 3 user is given the option of going to the helm app page
- After step 5 user is automatically taken to helm app page(?)

Talking points
- If this all happens quickly there could be lots of flashing changes on screen
- Determining number 5 could be tricky

**Comment by nwmac** [comment]
@Shavindra This is meatier ticket to take on that you, myself and @richard-cox should discuss before starting.

**Comment by richard-cox** [comment]
@lvuch This issue contains a step in a wizard like the Epinio Application create mentioned last week.
![image](https://user-images.githubusercontent.com/18697775/142016318-ff1e4118-03d3-49db-935c-0d6afa2cc27d.png)

After 2.6.3 can we get together and discuss a nicer version?

**Comment by richard-cox** [comment]
@nwmac We need to confirm if these steps are possible to determine and what we should show for each (are they line items in a table like the previous comment?). It might also be worth waiting until the epinio code merges as it contains changes that would support a mid-wizard async action and the generic table from above.

**Comment by lvuch** [comment]
> @lvuch This issue contains a step in a wizard like the Epinio Application create mentioned last week. ![image](https://user-images.githubusercontent.com/18697775/142016318-ff1e4118-03d3-49db-935c-0d6afa2cc27d.png)
> 
> After 2.6.3 can we get together and discuss a nicer version?

Yep sounds good just let me know when. I think enclosing it in a badge with appropriate progress text would work.

**Comment by kwwii** [comment]
I am closing this as it is quite old and I think it has already been fixed. Please reopen if the problem persissts.

**Comment by kwwii** [comment]
I am closing this as it is quite old and I think it has already been fixed. Please reopen if the problem persissts.

**Comment by richard-cox** [comment]
Neil and I are keen to keep this one. Requires a sync up / walk through to better explain what's needed

**Comment by kwwii** [comment]
Closing this as it is a stale issue that will be addressed in a larger effort to improve the UX of the apps and marketplace design
