### ISSUE TITLE
V2 Monitoring: Embed dashboards for Nodes, Workloads and Pods

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2678]
Leverage the initial work done to embed the Grafana dashboards for V2 Monitoring on the dashboard page to allow the same on the Node, Workload and Pod pages, as per the Ember UI for V1 Monitoring.

**Comment by slickwarren** [comment]
on master-head (d7ef41e):


* pod metrics appear good, showing correct graphs and metrics
<img width="1711" alt="Screen Shot 2021-05-14 at 1 50 36 PM" src="https://user-images.githubusercontent.com/16691014/118329966-f78c8e80-b4bb-11eb-99db-ba4fac52dd0c.png">

* node metrics appear good, showing correct graphs and metrics
<img width="1734" alt="Screen Shot 2021-05-14 at 1 50 03 PM" src="https://user-images.githubusercontent.com/16691014/118328995-56053d00-b4bb-11eb-9100-4cc374f74725.png">

**Reopening for the following issue**
* it appears as though deployment/workloads for grafana aren't being populated correctly. (both details and summary are broken)
They are categorized as `replica sets` on grafana, but the embedded option appears to be using `Deployments` (click the grafana link while the graphs are still showing `no data`, and select the correct type from grafana)
<img width="862" alt="Screen Shot 2021-05-14 at 1 31 04 PM" src="https://user-images.githubusercontent.com/16691014/118325886-fd34a500-b4b8-11eb-8b01-530c66e88c5b.png">
<img width="1724" alt="Screen Shot 2021-05-14 at 1 30 16 PM" src="https://user-images.githubusercontent.com/16691014/118325894-fe65d200-b4b8-11eb-8989-7e983d4ee14f.png">
after waiting some time, it appears that the correct link is found/selected in the embedded graphs (~30s to 1 minute)

* also happens for statefulsets, daemonsets, and all other workload types.

**Comment by codyrancher** [comment]
In #3106 I'm fixing an issue where I was passing the wrong ID to the workload graphs but I'm also hiding the metrics tab for unsupported workload types.

I'll put in a separate fix for showing the additional workload types once the backend portion is done for https://github.com/rancher/rancher/issues/32896.

**Comment by slickwarren** [comment]
currently blocked from testing `jobs` metrics due to this ticket: https://github.com/rancher/rancher/issues/32896

**Comment by slickwarren** [comment]
on master-head (629146a) I was able to test the following using a downstream, linode cluster:
* pod metrics for various workloads -- pass
* node metrics with various roles (dedicated, mixed, all roles) -- pass
* daemonsets -- pass
* statefulsets -- pass
* replicasets -- pass

for the remaining types, see the ticket linked by Cody above.
