### ISSUE TITLE
Workloads: Sidecars/multi-container UX could be improved

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2683]
The UX for workloads with multiple containers needs to be improved  - team to review and discuss the issues and how to improve the UX.

**Comment by richard-cox** [comment]
- A lot of the problems stem from the same page used to edit the workload and add/remove/edit containers
- The tabs shown in the edit workloads page are a mix of deployment and container 
- From the workload list, or view workload page, adding a sidecar takes user to the edit workload page with a new container selected. Slightly confusing to change contexts

**Comment by nwmac** [comment]
Addressed by 2.6.9/2.7.0 work
