### ISSUE TITLE
[Logging v2] Windows Clusters using RKE need their provider set

### ISSUE THREAD

**Issue by nickgerace** [rancher/dashboard#2684]
## Request
Set `additionalLoggingSources.rke.enabled` to true for Windows clusters on RKE (a "Custom" cluster) while ensuring that `global.cattle.windows.enabled` is still being set to true.

## Description
@izaac noted that `additionalLoggingSources.rke.enabled` is not set to true for Windows clusters that install the Logging chart, which makes sense. The good news is that `global.cattle.windows.enabled` is being set to true properly, the bad news is that we need the aforementioned value set to true as well.

I had thought that since our Windows clusters are RKE clusters, then that value would be set to true automatically, just like the Linux RKE clusters. From looking at the original PR, this does not appear to be the case, and `'rke.windows'` is the actual provider, not `rke`. Thus, we may need to check if the provider is `'rke.windows'`, and set the provider for Logging to `rke` accordingly.

## Relevant Information
- **Original PR:** https://github.com/rancher/dashboard/pull/1182
- **Current Index:** https://github.com/rancher/dashboard/blob/76add7dc45e59d33813790bbfa029ff6227f3be8/chart/logging/index.vue#L24-L29

**Comment by izaac** [comment]
What's the expectation when using `Edit/Upgrade` on an installed Logging chart?

I see these values always set as follows when editing regardless of the values configured during install:

- `additionalLoggingSources.rke.windows.enabled = true`
- `global.cattle.windows.enabled = false`

Even if I edit the values and try to edit/upgrade them again.


---------

@nickgerace could you describe the difference between setting true or false for both options?

This is what I observed when I set `global.cattle.windows.enabled = false`

<img width="1303" alt="Screen Shot 2021-04-20 at 6 44 02 PM" src="https://user-images.githubusercontent.com/27659/115485529-c8ab3180-a209-11eb-8030-e02796490a68.png">

And `global.cattle.windows.enabled = true`

The Daemon Set **rancher-logging-rke-aggregator** is created with fluent-bit pods on the Linux nodes

<img width="1252" alt="Screen Shot 2021-04-20 at 6 49 31 PM" src="https://user-images.githubusercontent.com/27659/115485574-dc569800-a209-11eb-8584-395b5c88daf2.png">


If I use `false` on both:

- `additionalLoggingSources.rke.windows.enabled = false`
- `global.cattle.windows.enabled = false`


<img width="1303" alt="Screen Shot 2021-04-20 at 6 44 02 PM" src="https://user-images.githubusercontent.com/27659/115485529-c8ab3180-a209-11eb-8030-e02796490a68.png">

**Comment by nickgerace** [comment]
> I see these values always set as follows when editing regardless of the values configured during install:
>
> - additionalLoggingSources.rke.windows.enabled = true
> - global.cattle.windows.enabled = false

I believe this is the core issue. When Logging v2 is installed with these two values set to true, it should **retain** these two upon edit/upgrade. They shouldn't be changed unless the user manually changes them.

**Comment by izaac** [comment]
Rancher version `v2.5.8-rc6`
Logging chart version `3.9.400-rc04`
Windows Cluster - Custom RKE


Even using edit YAML during chart install and set/leave the `global.cattle.windows.enabled = false` I still see it `true` after install.

```
values:
    additionalLoggingSources:
      rke:
        enabled: true
    global:
      cattle:
        clusterId: c-sjlfn
        clusterName: test-30764
        systemDefaultRegistry: ""
        url: https://<rancher_url>
        windows:
          enabled: true
      systemDefaultRegistry: ""
```

**Comment by izaac** [comment]
Closing in favor of: https://github.com/rancher/rancher/issues/32264
