### ISSUE TITLE
Improve the Google Authentication Provider UI

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2689]
Issues below broken out from rancher/dashboard#2667

**Issue 1**
Can we have different sections and demarcations for the `Authentication` section and `Access` section.

**Issue 2**
Can the "Authorized Users and groups " section be aligned correctly?

<img width="1414" alt="Screen Shot 2021-04-09 at 10 00 49 PM" src="https://user-images.githubusercontent.com/26032343/114259126-8caddc00-9980-11eb-9dc8-145033a23c10.png">

**Comment by kwwii** [comment]
Closing this as it seems to be a stale issue.
