### ISSUE TITLE
Pod - Details

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#269]
Need Design

**Comment by lvuch** [comment]
https://xd.adobe.com/view/84134770-bb08-4d0c-736d-1f0aa44b36fd-f222/

**Comment by lvuch** [comment]
https://xd.adobe.com/view/016d66e0-2822-435a-5010-7be91e207ed6-775c/

**Comment by tfiduccia** [comment]
Pod Detail page is a subset of Workload.  Detail page is only accessible either from Workload details or from workload list page itself.

**Comment by tfiduccia** [comment]
Pod Details added to workload.  Closing this.
