### ISSUE TITLE
Google Authentication Provider Configuration shows IPs

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2690]
Issue broken out from rancher/dashboard#2667 

**Issue 3**

- Enable Google auth in CLuster explorer page
- In Step One and Step Two, the Authorized redirect URL is IP address of the rancher server instead of the the FQDN. for the sam set of steps, in the Ember UI, these sections have FQDNs in Step One and Step Two.

**Comment by sowmyav27** [comment]
On 2.5.8-rc4. This issue is seen fixed.
