### ISSUE TITLE
HTTP Error 500 when trying to access Cluster Explorer Page

### ISSUE THREAD

**Issue by AmartC** [rancher/dashboard#2697]
On Rancher server using Rancher v2.5.7, created an RKE1 cluster with 1 worker node, 1 control plane node and 3 etcd nodes and cluster has been created but when trying to access the Cluster Explorer page, running into this error.

<img width="1317" alt="Screen Shot 2021-04-14 at 3 06 17 PM" src="https://user-images.githubusercontent.com/8761010/114765564-4a471f00-9d33-11eb-93c4-d462c8c69c21.png">

**Comment by gaktive** [comment]
Looks identical to https://github.com/rancher/rancher/issues/32139, whereby the API doesn't offer anything pretty to the UI when this situation happens.

**Comment by gaktive** [comment]
Duplicate. Closing here but resulting UI tickets may be needed depending on what the API offers us.
