### ISSUE TITLE
[Cluster Explorer] Available PVC does not refresh when changing namespace at creation

### ISSUE THREAD

**Issue by mscbpi** [rancher/dashboard#2716]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug (GUI)

**Steps to reproduce (least amount of steps as possible):**

1. Create a new Deployment
2. Change namespace where you want to create this deployment
3. Go to Storage Menu and try to add a PVC

**Result:**
PVCs of the selected namespace do not appear.

**Other details that may be helpful:**

Namespaces has to be selected before creation of the deployment to get existing PVCs appearing in Storage Menu
![image](https://user-images.githubusercontent.com/28528210/109949968-4eb3fd00-7cdc-11eb-94e6-280307fc7a4c.png)

Workaround: select the correct namespace before you click on "Create" button for your deployment. The PVCs appear.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.5.6
- Installation option (single install/HA):
HA

**Comment by sowmyav27** [comment]
**On 2.5.7**

- Deployed a GKE cluster
- From cluster explorer, Create a PVC `pvc1` in default namespace
- Create a PVC - `pvc2` in `test` namespace
- Create a deployment, say in `default` namespace
- Go to Storage tab --> Persistent Volume Claim --> PVC lists `pvc1`
- Modify the namespace in "Create Deployment" page to `test` namespace
- Now the PVC listed in Storage tab --> Persistent Volume Claim is `pvc1` and _not_ `pvc2`

**On 2.5.8-rc10**

- Deployed a GKE cluster
- From cluster explorer, Create a PVC `pvc1` in default namespace
- Create a PVC - `pvc2` in `test` namespace
- Create a deployment, say in `default` namespace
- Go to Storage tab --> Persistent Volume Claim --> PVC lists `pvc1`
- Modify the namespace in "Create Deployment" page to `test` namespace
- Now the PVC listed in Storage tab --> Persistent Volume Claim is `pvc2`
