### ISSUE TITLE
[Cluster Explorer] Deleting Namespace UX Inconsistency

### ISSUE THREAD

**Issue by mscbpi** [rancher/dashboard#2718]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Delete a namespace without confirming its name

**Result:**
![image](https://user-images.githubusercontent.com/28528210/107516444-b929bf80-6bac-11eb-867f-4760ef81f59c.png)

Delete button is stuck "processing" while the error is appearing, without letting the chance to the user to correct their mistake, even when field is correctly filled. User has to cancel and try again.

**Other details that may be helpful:**
Rancher 2.5.6

**Comment by gaktive** [comment]
Could be fixed already.

**Comment by neillsom** [comment]
Seems to be fixed already

**Comment by slickwarren** [comment]
I was not able to reproduce this on v2.6 (909237a)
