### ISSUE TITLE
Typing /bin into command input fields moves focus to namespace filter

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#2723]
Typing `/` into some input fields (command, ..) move focus away from input.
Input fields for deployment name / container image work fine.

**To reproduce:**
- Go to Cluster Explorer -> Deployments -> Create
- Click to `Command` input filed (or Arguments, ...)
- Type `/bin`

**Current result:**
Focus jumps out of input filed & expands namespace filter. (combination of `\` + `n`)
Other input fields in `Command` section / Environment variables have the same behavior.
Text can be typed fine after I move focus back to input field.

**Expected result**
Typing `/` won't move focus away from input filed. Even more if placeholder is `e.g. /bin/sh`

Tested on v2.5-head (31f00c1), with firefox & chrome.

**Comment by gaktive** [comment]
Per @vincent99's analysis, other problems arose with the commandeditor. Pushing out for now to give more time to investigate.

**Comment by gaktive** [comment]
@nwmac able to reproduce for the 1st time though upon moving off and going back in, it seems to correct itself. This is happening in some other fields but not all, which is weird.

**Comment by kravciak** [comment]
Works fine on master-head (744c233)
