### ISSUE TITLE
[Monitoring V2] Set the ingress-nginx namespace to kube-system by default for RKE2

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2728]
Original Issue: https://github.com/rancher/dashboard/issues/2485

Need to follow-up by updating the namespace for rke2 clusters only to kube-system.

**Comment by slickwarren** [comment]
ingressNginx is now default for RKE2 clusters and all pods deploy successfully
<img width="269" alt="Screen Shot 2021-04-21 at 12 34 27 PM" src="https://user-images.githubusercontent.com/16691014/115610635-ff328c00-a29d-11eb-9fb8-d586cf1894d0.png">
