### ISSUE TITLE
Services - List, Detail & Create/Edit

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#273]
Need Design

**Comment by lvuch** [comment]
https://xd.adobe.com/view/9c97eaa0-2f01-4459-426f-1a73d91f5059-eaa6/

**Comment by tfiduccia** [comment]
Service Discovery -->
1.  Rename to Service
2.  Fields
-  Name, Description & Type field 
     Type field is drop-down with ClusterIP, LoadBalancer, NodePort, External Name, Headless
-  Fields that show up for ClusterIP, LoadBalancer, & NodePort:
     Add Port (Name, Target Port (drop-down or input), Protocol, Listening Port, node port)
     Add Selector (Label & Value)
    Cluster IP, External Traffic Policy (radio - cluster or local), IP Family (drop-down v4 or v6), publishNotReadyAddresses (checkbox), sessionAffinity (drop-down or radio with two choices - None or ClientIP), sessionAffinityConig (?), TopologyKeys (if external Traffic policy is cluster - input with a list of suggestion options that include hostname, zone, region and any.  Needs a + to add additional with max at 16)
-  Fields for External Name
     Target Hostname, IP Family (drop-down v4 or v6)
-  Fields for Headless
     Add Port (Name, Protocol, Listening Port)
     Add Selector (Label & Value)
     IP Family (drop-down v4 or v6)
- Fields for loadbalancer type 
     HealthCheck port (only if external Traffic policy is local)
     LoadBalancerIP
     LoadBlancerSourceRange (list)

**Comment by lvuch** [comment]
updated from tani's feedback in xd: https://xd.adobe.com/view/bb785616-81a9-4dc4-5ba4-a6e25ee6f237-cd49/

**Comment by tfiduccia** [comment]
Compare against Ember UI for fields

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/dashboard/issues/573
