### ISSUE TITLE
Cluster Explorer in v2.5-head replaced by a new version for 2.6

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#2734]
During working with my testing cluster based on rancher:v2.5-head `41f173a` the Cluster Explorer was replaced suddenly by a new version probably meant for 2.6.

Workaround for the version of rancher I'm using is to set `ui-offline-preferred=true` in EmberUI Global->Settings

`ui-dashboard-index` in my rancher is set to https://releases.rancher.com/dashboard/latest/index.html

![new-explorer](https://user-images.githubusercontent.com/12828077/115408719-65150a00-a1f1-11eb-93c4-1113969046b8.png)

**Comment by thehejik** [comment]
It is the same with fresh v2.5-head `0f4526a`

**Comment by gaktive** [comment]
Can QA test off `RC` instead? I believe that 2.5-head turning into 2.6-head can be expected based on work pushed into master. Let me know if there's been a change in practice.

**Comment by sowmyav27** [comment]
Closing this issue as QA is testing off of 2.5.8-RCs
