### ISSUE TITLE
2.6 UX: Create getting started document

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2735]
Should also use same approach for release notes.

Need these to be localisable.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `b43e4d9`**

- Getting Started Document looks good
<img width="1626" alt="Screen Shot 2021-08-23 at 9 38 49 PM" src="https://user-images.githubusercontent.com/26032343/130556662-9aff0c22-db76-48ca-b2c4-3e17b90a770d.png">
