### ISSUE TITLE
2.6 UX: Update Cluster Dashboard page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2737]
- Swap out the gauges for the newer charts style
- Change the top portion that shows metadata
- Update the boxes as per the design

![image](https://user-images.githubusercontent.com/1955897/115410965-fdf45700-a1ea-11eb-8459-f7891239963a.png)

- To start with, for the three boxes: Total resources, nodes, deployments
- We already have a gauge control that we use on the nodes page that can be leveraged

Check with Lauren for latest design

**Comment by lvuch** [comment]
Sent to @mantis-toboggan-md via slack, putting here for tracking: 
Page 12 - Scrolls
https://xd.adobe.com/view/34482c73-045d-4799-8ab9-0851c28dd1aa-611b/screen/2514d4ec-193a-4378-8909-721c022038bf

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head f223834`.
The Cluster Dashboard page with and without enabled v2 monitoring matches the provided mockup. Closing.

With v2 monitoring disabled:
![dashboard_wo_monitoring](https://user-images.githubusercontent.com/12828077/118268982-679c1400-b4be-11eb-89cf-50e92f2a3f38.png)

With v2 monitoring enabled (graphs are visible when scrolled down):
![dashboard_w_monitoring](https://user-images.githubusercontent.com/12828077/118269072-89959680-b4be-11eb-9012-f295de7cd2c1.png)
