### ISSUE TITLE
Volumes - List/Detail & Create/Edit

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#274]
Use this wireframe from rancher/dashboard#245 for list of pv, sc and pv, sc detail pages:

pvc: https://xd.adobe.com/view/f449481a-fafc-4237-7597-8de9b8846771-8278/
sc + pv: https://xd.adobe.com/view/009f6a98-7698-4618-60c4-3515aafe0be0-76ae/

**Comment by lvuch** [comment]
links updated per tani's request "For PVC, Related Workloads should be a table above the tabs and not in the tabs.
Same with Storage class, the PV table should be outside the tabs."

**Comment by deniseschannon** [comment]
Replaced with #855 and #872
