### ISSUE TITLE
[Rancher Backup] s3 config are lost when creating a backup 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#2741]
Bug on v2.5.8-rc4 

Steps:
- create a `backup` in the Cluster Explorer UI
- choose the `An S3-compatible object store` option and fill in values 
- create

<img width="983" alt="Screen Shot 2021-04-20 at 11 04 29 AM" src="https://user-images.githubusercontent.com/6218999/115444015-ddb3a080-a1c8-11eb-917f-eb2f1a04d2a5.png">

Results:
The values of the s3 section are lost in the POST request, so the backup fails to proceed. 

![image](https://user-images.githubusercontent.com/6218999/115444052-ead08f80-a1c8-11eb-980b-1a64f404de3b.png)

**Comment by sowmyav27** [comment]
**On 2.5.7, Issue is reproduced**
<img width="778" alt="Screen Shot 2021-04-20 at 4 11 38 PM" src="https://user-images.githubusercontent.com/26032343/115474803-1ec0aa80-a1f3-11eb-8b07-701340ec08dc.png">

Waiting for an RC to test this.

**Comment by sowmyav27** [comment]
**On 2.5.8-rc7**
Restore CR has storage location saved
<img width="838" alt="Screen Shot 2021-04-22 at 9 57 56 PM" src="https://user-images.githubusercontent.com/26032343/115820545-e1584a80-a3b5-11eb-8b8e-435d4a629173.png">
