### ISSUE TITLE
[Monitoring v2] rancher-alerting-drivers webhook UI Issues 

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2744]
Enhancement request
parent issue: https://github.com/rancher/dashboard/issues/2622
* warning/alert window should read something like `If rancher-alerting-drivers was not installed in the cattle-monitoring-system namespace you'll need to update the namespace in the url below.` instead of what is pictured. 

* It would also be nice to alert the user to update the url if the name was changed when deploying `rancher-alerting-drivers` to whatever the new service is. Users can check the name of the new service in `services -> namespace`. maybe something like 
`If rancher-alerting-drivers name was changed from the default, please update the url below`. . 

* **a more concise way to do the above would likely be preferable.** maybe something like 
`If rancher-alerting-drivers default values were changed, please update the url below in the format http://<new_service_name>.<new_namespace>.svc.<port>/<path>`

<img width="899" alt="Screen Shot 2021-04-20 at 12 05 25 PM" src="https://user-images.githubusercontent.com/16691014/115451262-d0e77a80-a1d1-11eb-81a4-090ac0ea24d2.png">

* for SMS, please update the default value of the URL service name to `rancher-alerting-drivers-sachet` (currently the `s` in `drivers` is missing in above screenshot)

* dropdown name in webhook options should just be `SMS`, not `alibaba-cloud-sms` 
<img width="229" alt="Screen Shot 2021-04-20 at 12 05 07 PM" src="https://user-images.githubusercontent.com/16691014/115451417-04c2a000-a1d2-11eb-8ffb-f102d62b2242.png">

* UI should select `cattle-monitoring-system` namespace for user instead of `default`

<img width="765" alt="Screen Shot 2021-04-20 at 1 35 02 PM" src="https://user-images.githubusercontent.com/16691014/115460542-3ab95180-a1dd-11eb-8b95-85f9366af5cb.png">

* (optional) is it possible to mark the general tab as required to select at least one option? Otherwise, user is presented with an error
<img width="1530" alt="Screen Shot 2021-04-20 at 1 37 42 PM" src="https://user-images.githubusercontent.com/16691014/115460918-b3b8a900-a1dd-11eb-9403-2b88e63e8e0b.png">

**Comment by codyrancher** [comment]
@slickwarren  The parent issue is https://github.com/rancher/dashboard/issues/2622.

I don't see anything on that issue which mentions these changes. Are you wanting to make these changes for 2.6?

**Comment by slickwarren** [comment]
Oh thanks for the correction, I will update the main message.  I think these need to be in 2.5.8 if possible.

**Comment by codyrancher** [comment]
@slickwarren  Since we now have 2 branches on the UI I don't really want to go back and forth too many times with PRs so I was hoping you could tell me if the following is alright.

![image](https://user-images.githubusercontent.com/55104481/115628137-05803280-a2b5-11eb-8332-63499a788505.png)
![image](https://user-images.githubusercontent.com/55104481/115628164-103ac780-a2b5-11eb-828e-f1d20fdb8492.png)

I chose the simpler option for the first ask because I had already created https://github.com/rancher/dashboard/issues/2651. I think we should improve it further in 2.6 but I don't think we should now.

> UI should select cattle-monitoring-system namespace for user instead of default

There isn't a good mechanism for doing this right now. I think this should also be pushed to 2.6.

**Comment by slickwarren** [comment]
@codyrancher yes those two are good solutions

**Comment by slickwarren** [comment]
checked on version 2.5.8-rc9:
* alibaba -> sms
<img width="211" alt="Screen Shot 2021-04-23 at 10 42 07 AM" src="https://user-images.githubusercontent.com/16691014/115909606-99bad880-a420-11eb-9de1-01f438594bed.png">

* sachet default (added `s` to drivers)
<img width="533" alt="Screen Shot 2021-04-23 at 10 41 50 AM" src="https://user-images.githubusercontent.com/16691014/115909608-9a536f00-a420-11eb-9e43-fb686971583a.png">

* updated message when adding new drivers receiver 
<img width="915" alt="Screen Shot 2021-04-23 at 10 41 41 AM" src="https://user-images.githubusercontent.com/16691014/115909613-9b849c00-a420-11eb-8a40-b53020aec726.png">

* message user for requirement
<img width="381" alt="Screen Shot 2021-04-23 at 10 41 21 AM" src="https://user-images.githubusercontent.com/16691014/115909618-9c1d3280-a420-11eb-8362-5e3c8440e1d8.png">

everything looks good
