### ISSUE TITLE
Cluster Provisioning: Custom Clusters - RKE1 Linux (iFrame from Ember)

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2748]
With some connection to https://github.com/rancher/dashboard/issues/2159

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 5d2b7ac`

Provisioned an RKE1 Oracle Linux custom cluster with the following steps:
From EC2, provision OL nodes using the following AMI `ami-0d064e68838034c37` (OL 8.2 SELINUX ON)
From dashboard cluster management UI, create a custom cluster.
Run the registration command on the nodes.

The cluster becomes available. The user is able to edit the cluster from dashboard cluster management view.
Tested with RKE2 feature flag turned on and off.
