### ISSUE TITLE
Cluster Provisioning - Register GKE (iFrame)

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2749]
Similar to what's done for EKS: https://github.com/rancher/dashboard/issues/2120

**Comment by aaronRancher** [comment]
This has been tested as part of https://github.com/rancher/dashboard/issues/2973#issuecomment-840152890 on Rancher `master-head` `version 3e89bb8`
User is able to import a GKE cluster from dashboard embed from Ember.
