### ISSUE TITLE
Cannot access dasboard after i enable firewal

### ISSUE THREAD

**Issue by tullo** [rancher/dashboard#275]
After a sucesful [installation of rio and dasboard](https://github.com/rancher/rio/issues/988) I am able to login to the dashboard.

Enabling the firewall (ufw enable) makes the dahsboard no longer accessible.

What TCP ports are there expected to be open by the dashboard to communicate with the backend?

**Comment by nwmac** [comment]
Rio is no longer supported. If this is a general Rancher dashboard issue, please feel free to re-open with additional information.
