### ISSUE TITLE
Cluster Provisioning - Import other Kubernetes (Vue)

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2751]
Similar to https://github.com/rancher/dashboard/issues/2750

**Comment by sowmyav27** [comment]
Please test
- Import of rke/k3s/RKE2 when RKE2 feature flag is turned ON and OFF
- also with rke vs rke2 toggle

**Comment by kravciak** [comment]
Tested on master-head (5d2b7ac)

Import of rke/k3s/RKE2 when RKE2 feature flag is turned ON and OFF 
 - works fine

Also with rke vs rke2 toggle
 - not available on import cluster

Edit functionality works (what is seen on Ember UI)
 - edit functionality does not work https://github.com/rancher/dashboard/issues/3005
