### ISSUE TITLE
Cluster Provisioning - Cluster Drivers List (Activate/De-activate)

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2763]
Likely just an iFrame from Ember.

**Comment by thehejik** [comment]
The list of cluster/node drivers is present in explorer, all buttons visible in Ember are also visible in Explorer and seems to be working. I was able to Activate/Deactivate both kind of drivers in Explorer and also k8s Metadata Refresh works. Tested on `rancher/rancher:master-head 26d6cde`.

Cluster drivers comparsion:
![cluster_drivers_explorer](https://user-images.githubusercontent.com/12828077/119832704-b73b0080-befe-11eb-91c3-b9fd8ece582f.png)

![cluster_drivers_ember](https://user-images.githubusercontent.com/12828077/119832729-bc984b00-befe-11eb-999e-71d4a8766f27.png)

Node drivers comparsion:
![node_drivers_explorer](https://user-images.githubusercontent.com/12828077/119832570-9672ab00-befe-11eb-849d-c4bc428e56a9.png)


![node_drivers_ember](https://user-images.githubusercontent.com/12828077/119832543-8fe43380-befe-11eb-9ca7-e379ae307cc1.png)
