### ISSUE TITLE
Cluster Provisioning with Node Provisioning - RKE2 Generic Node Drivers & Node Pools

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2767]
Similar to https://github.com/rancher/dashboard/issues/2766

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/02/2021)` _82b212d_
I am testing this with the OCI Driver, the node gets created but during he custom install script I see this error:

```
failureMessage: "Failure detected from referenced resource rke-machine.cattle.io/v1,
    Kind=OciMachine with name \"izc1-p1-cbp86\": Downloading driver from https://github.com/rancher-plugins/rancher-machine-driver-oci/releases/download/v1.0.1/docker-machine-driver-oci-linux\ndocker-machine-driver-oci-linux\ndocker-machine-driver-oci-linux:
    ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped\nRunning
    pre-create checks...\n(izc1-p1-cbp86) Verifying number of availability domains...
    \nCreating machine...\n(izc1-p1-cbp86) Provisioning node using image Oracle-Linux-8.3-2021.05.12-0\n(izc1-p1-cbp86)
    created instance ID ocid1.instance.oc1.us-sanjose-1.<REDACTED>,
    IP address <REDACTED>\nWaiting for machine to be running, this may take a
    few minutes...\nDetecting operating system of created instance...\nWaiting for
    SSH to be available...\nDetecting the provisioner...\nProvisioning with ol...\nProvisioning
    with custom install script via SSH, not installing Docker...\nError creating machine:
    RHEL ssh command error: command: sudo hostname izc1-p1-cbp86 && echo \"izc1-p1-cbp86\"
    | sudo tee /etc/hostname err: inappropriate ioctl for device output: \nThe default
    lines below are for a sh/bash shell, you can specify the shell you're using, with
    the --shell flag."
```

It seems the Instance gets created, and even the Provisioner type is also detected. But then there's a failure during the instance configuration?

**Comment by izaac** [comment]
I am checking if the UI coverage ends up here, and probably open a new issue for my previous comment.

**Comment by sowmyav27** [comment]
OCI RKE1 is working - https://github.com/rancher/dashboard/issues/2777
Reopening for this issue https://github.com/rancher/dashboard/issues/2767#issuecomment-873214624

**Comment by vincent99** [comment]
@izaac @sowmyav27 That is not a dashboard issue, please bring up with backend.

**Comment by gaktive** [comment]
@izaac can you talk with backend with what you're seeing with that error?

**Comment by sowmyav27** [comment]
Logged backend issue - https://github.com/rancher/rancher/issues/33865

**On master-head commit id: `3499046`**

- Able to create a custom cloud cred and deploy an RKE2 cluster.
- Closing this issue
