### ISSUE TITLE
New: RoleBindings

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2769]
Rancher has global/cluster/project role "templates" and these can bound to a user.  We should be able to leverage the cluster & project member work once that's done so we can say users A and B are members of this cluster or whatever.

There was an original attempt here: https://github.com/rancher/dashboard/issues/251
That was tied more to the underlying actual k8s RoleBinding/ClusterRoleBinding, which Rancher creates and manages for you when you use above, but these can also be used directly in k8s.

**Comment by codyrancher** [comment]
I'm closing this in favor of these two issues
https://github.com/rancher/dashboard/issues/2501
https://github.com/rancher/dashboard/issues/2673
