### ISSUE TITLE
Cluster Provisioning - Node Provisioning RKE1 - EC2

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2771]
Tied to https://github.com/rancher/dashboard/issues/2770

**Comment by izaac** [comment]
https://github.com/rancher/rancher/issues/32718

**Comment by izaac** [comment]
https://github.com/rancher/rancher/issues/32762

**Comment by izaac** [comment]
Rancher version `v2.6 master-head (07/17/2021)` _5d2b7ac_
k8s version 1.19.10, 1.18.18, 1.20.6

Provisioning 1 node cluster all roles worked.
Scaling up this cluster to 3 worked.
Cluster 1 etcd, 1 control plane, 3 workers worked. Scaling up/down the workers here worked.
Other options here worked too, Schedule backup, default ingress, etc.
Edit from YAML test worked too.


Note:
This other is related and also noticed while testing this cluster type (RKE1 EC2).
https://github.com/rancher/dashboard/issues/3021
