### ISSUE TITLE
Cluster Provisioning - Node Provisioning RKE1 - vSphere

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2772]
Tied to rancher/dashboard#2770

**Comment by slickwarren** [comment]
was able to provision vsphere downstream cluster on master-head (1e1ed67329d6224e7a10f1c1a529eaff60ba48ea) through the dashboard workflow

**Comment by slickwarren** [comment]
I was able to test the following on master-head (5d2b7ac)

* vsphere cluster with RKE flag ON (default) - pass
* vsphere cluster already provisioned, edit cluster (add environment var/new node pool) - pass
* turn RKE flag OFF, provision vsphere cluster - pass
