### ISSUE TITLE
Cluster Provisioning - Node Provisioning RKE1 - Digital Ocean

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2773]
TIed to rancher/dashboard#2770

**Comment by izaac** [comment]
https://github.com/rancher/rancher/issues/32726

**Comment by izaac** [comment]
Rancher version `v2.6 master-head (05/18/2021)` _55f0bb2_
k8s version 1.20.6

Provisioning 1 node cluster all roles worked.
Scaling up this cluster to 3 worked.
Cluster 1 etcd, 1 control plane, 3 workers worked. Scaling up/down the nodepools here worked.
Other options here worked too, Schedule backup, default ingress, etc.
Edit from YAML test worked too.

Observed this pre-existing behavior: https://github.com/rancher/rancher/issues/32663
