### ISSUE TITLE
Cluster Provisioning - Node Provisioning RKE1 - Azure

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2774]
Tied to rancher/dashboard#2770

**Comment by slickwarren** [comment]
I was able to test the following on master-head (5d2b7ac)
* azure cluster with RKE flag ON (default) - pass
* azure cluster already provisioned, edit cluster (add environment var/new node pool) - pass
* turn RKE flag OFF, provision azure cluster - pass
