### ISSUE TITLE
Cluster Provisioning - Node Provisioning RKE1 - Linode

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2775]
Tied to rancher/dashboard#2770

**Comment by sowmyav27** [comment]
Please test

- RKE2 feature flag is turned ON and OFF 
- When RKE2 feature is turned ON, rke is selected in the toggle.

**Comment by thehejik** [comment]
Works as expected in Cluster Management within Explorer. Tested on `rancher/rancher:master-head 5d2b7ac`.

* When RKE2 flag in OFF then RKE1 Linode cluster can be created and RKE/RKE2 toggle is not present
* When RKE2 flag in ON and RKE/RKE2 toggle is set to RKE2 the Linode is inactive/grayed out - on the other hand Linode is Active when the toggle is switched to RKE
* When RKE2 flag is ON the RKE/RKE2 toggle is set to RKE2 by default - for Linode deployment one have to switch the toggle to RKE position
* Edit of the Linode RKE1 cluster is possible - I did a successful k8s upgrade on my Linode RKE cluster and also added a node pool for adding extra worker nodes - both worked
* I was able to deploy single-node RKE Linode clusters as well as multi-node clusters with various node roles.
