### ISSUE TITLE
Cluster Provisioning - Node Provisioning RKE1 - Custom UI Node Drivers

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2778]
Tied to rancher/dashboard#2770

**Comment by slickwarren** [comment]
for a custom node driver on master-head (29674d9):
* create a custom node driver (I created one, then copied the same UI, Download, and checksums from the existing `linode` node driver) through iframe -- pass
* deactivate node driver -- pass
* deactivate multiple node drivers -- [fail, existing issue for ember](https://github.com/rancher/rancher/issues/22404) ( no issue on vue side)
* activate node driver -- pass
* activate multiple node drivers -- pass
* use activated (existing, but off by default) node driver (OCI) -- pass

REOPENING FOR THE FOLLOWING ISSUE: 
**use custom (created) node driver -- fail**
* the created node driver shows up and works fine through ember, but an iframe window does not load when clicked through vue, and the option isn't loading the name from the custom UI, but is using the machine name for it (below option name should both be linode)

<img width="835" alt="Screen Shot 2021-06-03 at 4 18 33 PM" src="https://user-images.githubusercontent.com/16691014/120723874-73f50a80-c487-11eb-8cc1-575f8049b72c.png">
<img width="1089" alt="Screen Shot 2021-06-03 at 4 18 37 PM" src="https://user-images.githubusercontent.com/16691014/120723877-75263780-c487-11eb-8d30-4a0bce58528b.png">

compared to ember views 
<img width="496" alt="Screen Shot 2021-06-03 at 4 20 03 PM" src="https://user-images.githubusercontent.com/16691014/120723942-9ab34100-c487-11eb-84e2-c92c7880ae67.png">

where both options lead to a window like this (only through ember)
<img width="577" alt="Screen Shot 2021-06-03 at 4 20 13 PM" src="https://user-images.githubusercontent.com/16691014/120723970-a9015d00-c487-11eb-87d2-756a0181281d.png">

**Comment by slickwarren** [comment]
tested on master-head (e756276):
it appears that the iframe page for linode rke1 custom UI is still defaulting to vue instead 
<img width="851" alt="Screen Shot 2021-06-25 at 2 25 25 PM" src="https://user-images.githubusercontent.com/16691014/123486625-3f292e80-d5c1-11eb-9b9b-19aeb9e5a4bb.png">

**Comment by nwmac** [comment]
@slickwarren I could not reproduce this - can you verify again

**Comment by slickwarren** [comment]
repro steps (master head 44bb5b4):
* create a custom node driver by copying all linode settings from the builtin driver
  * visit linode node driver in the API to get the download URL, custom UI URL, and checksum
  * use these to create a new node driver
* deactivate the existing linode driver to avoid confusion (side note-- might be nice to have some signifier to separate custom from generic/built in node drivers, but not sure what the real use case for this would be..)
* do a `hard reset & clear cache` in your browser (I'm using chrome)
* try to create a cluster using the new linode driver
* if you do get to the iframe page, try this step again: do a `hard reset & clear cache` in your browser (I'm using chrome)

**Comment by codyrancher** [comment]
@slickwarren 
I also can't reproduce this. I see the Linode driver with the appropriate name and when I click on it it works fine even with a hard reset. I've also just run it in an incognito window and it still works. If you're still able to reproduce this can you leave up a server so I can inspect it?

**Comment by slickwarren** [comment]
ok, I have a setup when you're ready @codyrancher

**Comment by sowmyav27** [comment]
Reopening the issue as I notice the issue as mentioned [here](https://github.com/rancher/dashboard/issues/2778#issuecomment-881738788) on master - `3499046`

**Comment by codyrancher** [comment]
With @slickwarren I was able to reproduce this issue. Digging into it the cause appears to be a problem with using a custom driver that shares the same name with the builtin driver. When disabling the builtin driver ember can no longer find either driver since both were disabled since they have the same name. In ember this results in both linode drivers being omitted from the list so it's not reproducible.

![image](https://user-images.githubusercontent.com/55104481/127939084-df7e7f36-cc8b-42fd-97f3-1a9f41f39c8b.png)


This isn't a new issue. This surfaces because dashboard disabled based on the id instead of the name which I see as correct behavior.

Because this issue isn't new and users are unlikely to trigger it I think this should be moved to 2.6.x.

**Comment by sowmyav27** [comment]
**On 2.6-head - commit id: `10588ab`**

- Able to add Custom Node drivers
- Calls being made - v3 calls
- UI sends all values in these fields to the backend

```
checksum: "sdfsdf"
type: "nodeDriver"
uiUrl: "sdf"
url: "sdf"
whitelistDomains: ["sd"]
```
