### ISSUE TITLE
Explorer when try to view Configmap that container HTML data it show HTML rendered

### ISSUE THREAD

**Issue by sida-khalibre** [rancher/dashboard#2779]
In Rancher cluster explorer when viewing Configmap that container HTML data it shows rendered HTLM instead of HTML code.

**Comment by sida-khalibre** [comment]
![image](https://user-images.githubusercontent.com/9067408/115498133-2d609d80-a297-11eb-826f-1f0143a180fd.png)

**Comment by anupama2501** [comment]
Reproduced on v2.5.6:

- From cluster explorer --> config maps --> create configmap --> read from file [provide html file] and create. 
- Once the config map is active, click on the config map and verify the data which gives rendered HTML:
- 

<img width="200" height="300" alt="Screen Shot 2021-05-03 at 1 55 37 PM" src="https://user-images.githubusercontent.com/38144301/116932559-43ffe080-ac17-11eb-8db1-cc693de12aae.png">
 
Verified on rancher version v2.5.8-rc18:

- From cluster explorer --> config maps --> create configmap --> read from file [provide html file] and create. 
- Once the config map is active, click on the config map and verify the data which gives HTML code:

<img width="200" height="300" alt="Screen Shot 2021-05-03 at 1 58 18 PM" src="https://user-images.githubusercontent.com/38144301/116932847-a22cc380-ac17-11eb-9abe-0ec0a18584d7.png">
