### ISSUE TITLE
Roles menu item is un-highlighted when creating/viewing/editing a role

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2783]
1. Nav to Users & Auth  --> Roles (Roles menu item is highlighted)
2. Click on `Create Global Role` (Roles menu item is un-highlighted)

This will be down to how the routing works
- c/local/auth/roles#GLOBAL vs c/local/auth/management.cattle.io.globalrole/create?roleContext=GLOBAL#grant-resources
- auth roles virtual type vs generic resource create/view/edit route 

Note - We'll probably have the same issue for users and groups as well

**Comment by nwmac** [comment]
Can you take a look and see what is do-able
