### ISSUE TITLE
Roles: Create RBAC Role: Incorrect fields shown for Rule & local validation needs improving

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2792]
Fields
- The fields shown when creating a rule for a new RBAC role include 'Non-Resource URL'
- This field is not applicable to namespaced resources such as the RBAC role type (unlike all other role types) and should be removed

Validation
- For RBAC role's both resource and api group rule fields are must be supplied

Additionally rule fields that are marked as required need updating
- Verb is always required
- RBAC role type - verb, resource and api group should be marked as required
- Other types - verb should be marked as required (others not)

Note - Showing rule required indicators means that when the page initially loads it will appear like the user needs to enter values for the default/empty rule row ... but user can ignore these required fields and successfully save the role anyway. The alternative is to not show an empty rule to begin with... but this forces the user to click `Add Resource` for pretty much every create. I feel the later is more of an issue than the former.

This issue is connected to rancher/dashboard#2693

**Comment by slickwarren** [comment]
tested on v2.5.8-rc8:
<img width="1438" alt="Screen Shot 2021-04-22 at 9 22 18 AM" src="https://user-images.githubusercontent.com/16691014/115750616-31e78d80-a34d-11eb-9c4e-d9e82b21a396.png">

* Roles now require all 3 fields (non-resource URLs were removed)
* empty fields of any type now throw an error
