### ISSUE TITLE
Single Cluster Install Experience

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2795]
Multi-cluster management (MCM) is now a feature flag. When it's off (e.g, disable), then it should not show the ability to provision additional clusters.

This means that for a single cluster login, we shouldn't show anything related to multiple clusters (provisioning, viewing, etc.) We can tweak the home page for a simple task and then revisit.

**Comment by gaktive** [comment]
Need to chat with @nwmac and @deniseschannon since there are questions about the flag being feature or not.

**Comment by sowmyav27** [comment]
**On master-head commit id: `8a60508`**

When MCM is disabled on a single node docker install
<img width="1680" alt="Screen Shot 2021-07-19 at 9 44 04 PM" src="https://user-images.githubusercontent.com/26032343/126263408-1ec383e9-41cf-4ec6-8d44-5c1bc27236ad.png">

- Cluster tools Option isnt working. Clicking either from the Home page or from the Left slide in panel
<img width="1072" alt="Screen Shot 2021-07-19 at 9 45 28 PM" src="https://user-images.githubusercontent.com/26032343/126263426-c6b5f4cd-0c00-4d7d-8587-62a0762a72a1.png">

**Comment by nwmac** [comment]
@sowmyav27 

I've separated the 2nd issue here - https://github.com/rancher/dashboard/issues/3510 - we'll look at that for 2.6.2

The Cluster Tools issue is a backend/charts issue - I've created https://github.com/rancher/rancher/issues/33688 for this.

**Comment by sowmyav27** [comment]
Closing this issue. Separate tickets logged for issues found.
