### ISSUE TITLE
Dashboard Setup flow

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2800]
Implement the setup flow in the Dashboard UI in a similar fashion to Cluster Manager.

Specify admin password, set server URL and agree to terms + opt in to telemetry

**Comment by nwmac** [comment]
Check setting to see if this is first install, if it is, login as admin with default  password and redirect to the setup flow to get the user to change the admin password and set the server URL.

Need a UI Design - suggest using a 2 step stepper/wizard.

**Comment by sowmyav27** [comment]
**On master-head commit id: `master-be0b016`**

<img width="1089" alt="Screen Shot 2021-05-14 at 3 39 14 PM" src="https://user-images.githubusercontent.com/26032343/118338332-bc458c00-b4ca-11eb-8703-a362f8c420d0.png">
<img width="1010" alt="Screen Shot 2021-05-14 at 3 38 58 PM" src="https://user-images.githubusercontent.com/26032343/118338335-bd76b900-b4ca-11eb-9156-d7404dc1fea7.png">
