### ISSUE TITLE
[2.6] Custom Links in Cluster explorer UI

### ISSUE THREAD

**Issue by cloudnautique** [rancher/dashboard#2835]
Add custom links to the lefthand side nav in Cluster Explorer UI. 

Usecases:
* Links can be created at the top level
* Multiple links can be grouped together 
   * grouped links are drawn on a page with icons.
* Links can be for services in the cluster.
   * Access is driven off access to the Kubernetes service.
* Links will be opened in a new tab/window.

**Comment by gaktive** [comment]
Darren to provide CRD then Vince can work on it

**Comment by deniseschannon** [comment]
This is all available as YAML and not as a pretty form.

**Comment by anupama2501** [comment]
On master-head ba100bb
Verified the following scenarios:
Create a cluster and install istio app with kiali enabled and monitoring app.
1. From cluster --> more resources --> Rancher --> Navlinks --> Create from yaml with the following fields: ​

> Name: Istio
group: group1
toURL: < url of kiali UI >
iconSrc: < base64encodedImage >
description: Kiali UI
sideLabel: Istio

2. Create a new navlink with the fields:
>Name: monitoring
group: group1
toURL: < url of grafana >

3. Create a new navlink with the fields:
> Name: test
grou: group1
toUrl

<img width="400" alt="Screen Shot 2021-05-27 at 3 35 06 PM" src="https://user-images.githubusercontent.com/38144301/119905455-231e6880-bf01-11eb-8016-35223d157260.png">

3. Create a new navlink with the fields:

> Name: standalone
> toURL: < url of istio >
<img width="237" alt="Screen Shot 2021-05-27 at 3 37 42 PM" src="https://user-images.githubusercontent.com/38144301/119905674-8dcfa400-bf01-11eb-8cb2-4c2729f1a815.png">

All the links are opened in a new tab

4. Delete the navlink from step3 and verified its not populated in the group1 list

**Comment by anupama2501** [comment]
On master-d7528a261111d2ea2129a8b1547fd22974fbc67c-head
1. Create a standard user - user1 from Users and Authentication --> Users --> Create a standard user
2. Create a cluster as an admin 1 node all roles and create navlinks similar to above mentioned scenario:

> Name: monitoring
> group: group1
> toURL: < url of grafana >

3. Add the user1 to this cluster as cluster owner from ember UI --> cluster --> Members and verify the links are provided to the user1 in the cluster and can create new links as well. 

1. Create a role from Users and Authentication --> Roles --> Cluster --> create a custom role with navlinks and add all the verbs eg: Create,delete,view etc.
2. Create a cluster as an admin and once the cluster is active from ember UI --> cluster --> members --> add the user1 with the roles created above and also add the user as cluster member
3. Login as user1 and verify from the cluster --> navlinks are not showing up
Reference issue: https://github.com/rancher/dashboard/issues/3135

**Comment by sowmyav27** [comment]
Validate this: https://github.com/rancher/rancher/pull/32951/commits/7402360cafaf543722ce1a181aa1b9699dcf3783

**Comment by anupama2501** [comment]
Keeping this issue open for validations to be done with standard users be able to access the navlinks by default without requiring additional configurations: 

https://github.com/rancher/rancher/pull/32951/files

**Comment by anupama2501** [comment]
Verified the following test cases on rancher version: master-head

1. Created 4 standard users and a node driver rke2 cluster from explorer
2. Created 3 navlinks with monitoring grafana, kiali and external URL provided in the toURL, toService URL
3. User1 :

> when added as Cluster member, by default has access to all the navlinks created with the URL provided in the field toURL
> User1 was not able to click on the links with services that they have no permissions to. eg., Monitoring and kiali
> When the grafana URL of monitoring is provided as toService URL, user1 was not able to see the link for monitoring as they have no access to the monitoring service.

4. User2:
 

> User2 is added as a cluster owner in the cluster.
>  By default user2 has access to all the navlinks in the cluster and they can see the toService URL as well.
>  All the links were opened in a new window

5. User3:

>  User3 is added to the system project with pre-defined custom project role View Monitoring and to default project as project member
>  By default, project members should be able to view all the nav links.
>  This testcase has failed and linked the ticket 

6. User4:
 

> Created a custom cluster role with the verbs get,create,delete and assigned to the user4 from cluster → members
>  Logged in as the user4 and verified they cannot list the previously created navlinks but can create new navlinks, delete the created navlinks and get the list of navlinks created by user4

**Upgrade test:**

1. Created rancher server on 2.5.8 version and created a node driver rke1 cluster from ember UI.
2. Create a standard user user0
3. Upgrade the rancher server to the master-head latest
4. Once the upgrade is done and the cluster is active, from the Explorer → More Resources → Rancher → NavLinks option created 3 navlinks with group name and toURL istio, monitoring and external URL.
5. Edited the navlink2 with monitoring by removing group name and verified the link appeared as standalone
6. Deleted the navlink with external URL and verified it was removed.

**Comment by Jono-SUSE-Rancher** [comment]
@anupama2501 - Is there anything else that needs to be validated on this or is it still in the "To Test" column? Just doing some updates to our backend sheets and want to make sure this is up to date.

**Comment by anupama2501** [comment]
Hi @Jono-SUSE-Rancher, yes we still need to validate an RBAC testcase for Projects but it is yet to be fixed: https://github.com/rancher/rancher/issues/33093

**Comment by Jono-SUSE-Rancher** [comment]
OK thanks, I have updated our sheet to reflect that.

**Comment by anupama2501** [comment]
Closing this ticket as the issue mentioned in the above comment has been resolved.
