### ISSUE TITLE
Add PrefixPath and WindowsPrefixPath, if populated, to the Global.Cattle.* values.

### ISSUE THREAD

**Issue by phillipsj** [rancher/dashboard#2837]
This is an enhancement request to add PrefixPath and WindowsPrefixPath to the global.cattle.* values that are populated in the UI. These properties aren't exposed if not set and if they are set they will be in the cluster.spec.rancherKubernetesEngineConfig as PrefixPath and WindowsPrefixPath. This change will allow adjusting charts if a prefix path is used and allows rancher/rancher#32194   to be fixed.

**Comment by sowmyav27** [comment]
**On 2.5.8-rc15**
**wins-upgrader chart**
- On a windows cluster, Deploy wins-upgrader chart
- `rkeWindowsPathPrefix: ""` is send in the request sent by UI dashboard in both these scenarios
- - win_prefix_path is _not_ set on the cluster
- - win_prefix_path is set --> `win_prefix_path: 'c:\host\opt\'`

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/pull/2880

**Comment by sowmyav27** [comment]
On 2.5.8-rc16, oon a windows cluster with win_prefix_path set, UI sends `rkeWindowsPathPrefix: ""` in the request sent

I think fix should have `winPrefixPath` instead of `winPathPrefix`  and also `prefixPath` instead of `pathPrefix`. Reopening the issue.

**Comment by sowmyav27** [comment]
PR: https://github.com/rancher/dashboard/pull/2882/files

**Comment by sowmyav27** [comment]
Validated this issue on 2.5.8-rc19 as part of this issue - https://github.com/rancher/rancher/issues/32194. Works as expected. Closing this issue.
