### ISSUE TITLE
EPIC: net new with backend

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2850]
- [x] Keycloak with OIDC: https://github.com/rancher/dashboard/issues/2191
- [x] AKS v2 Provisioner (Ember): https://github.com/rancher/rancher/issues/31315

**Comment by gaktive** [comment]
Both tickets are now in QA so for tracking purposes, I'll pass this epic over to QA (and look over the other epics too).

**Comment by sowmyav27** [comment]
Closing this epic. The issues are tracked in the respective tickets, and any related issues found will be tracked separately.
