### ISSUE TITLE
Wrong handling of command argument quotes

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#2857]
To reproduce create new deployment in dashboard UI:
image: busybox
command: /bin/sh
arguments: -c `<quoted string>`

dashboard UI double quotes: when editing deployment quotes are missing from input filed, saving without quotes breaks deployment
```
input command: -c "sleep 60"
edit deployment : -c sleep 60
edit yaml:
  - args:
    - -c
    - sleep 60
yaml after changing sleep value:
  - args:
    - -c
    - sleep
    - "50"
```

dashboard UI single quotes: editing loads quotes as expected but quotes deployment yaml are broken
```
input command: -c 'sleep 60'
edit deployment : -c 'sleep 60'
edit yaml:
  - args:
    - -c
    - '''sleep'
    - 60'
```

ember UI: creating / editing existing command provides same result, works as expected
```
input command: -c "sleep 60"
edit deployment : -c 'sleep 60'
edit yaml:
  - args:
    - -c
    - sleep 60

input command: -c 'sleep 60' produces same result as above
```

Tested on v2.5.8-rc10

**Comment by kravciak** [comment]
Double quotes are saved/loaded as expected, this part works fine now (they are changed into single quotes).

Single quotes are still broken as described in `dashboard UI single quotes` part.
Saved yaml with single quotes in argument still produces:

```
  - args:
    - -c
    - '''sleep'
    - 50'
```

**Comment by anupama2501** [comment]
Verified on v2.5.8-rc18
1. Created a deployment with image busybox, command: /bin/sh, Arguments: -c 'sleep 120'
edit as yaml and verified the args are added as 
      - args:
        - -c
        - sleep 30
edit as config is added as follows:
Arguments -c 'sleep 30'
2. Created a deployment with image busybox, command: /bin/sh, Arguments: -c "sleep 120"
edit as yaml and verified the args are added as 
      containers:
      - args:
        - -c
        - sleep 30
Arguments -c 'sleep 30'
In above both cases deployment goes through and the workload comes active without issue.
