### ISSUE TITLE
Unable to edit Namespaces created by the Dashboard

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2878]
- When creating a namespace the dashboard sets empty container resource limits as `null<unit>`. 
- Attempting to then edit the new namespace will fail with, in dev world, the white screen error
- I'm not sure how this manifests in prod

**Comment by sowmyav27** [comment]
**On 2.5.8-rc15**
Reproduced the issue

- Create a namespace with empty container resource limits
- Edit namespace


<img width="1067" alt="Screen Shot 2021-04-30 at 4 20 16 PM" src="https://user-images.githubusercontent.com/26032343/116762796-67851a00-a9d0-11eb-9e72-d1746bf10c25.png">

**On 2.5.8-rc16**
- On an edit
<img width="1058" alt="Screen Shot 2021-04-30 at 4 22 42 PM" src="https://user-images.githubusercontent.com/26032343/116762807-7370dc00-a9d0-11eb-83eb-0a9e78cacad1.png">

- User is able to edit --> Add limits and save the namespace
