### ISSUE TITLE
Options on the left pane is not clickable while using rancher master-head

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/dashboard#2889]
Environment:
Rancher: master-head(Commit: 5115a54846)

On the Dashboard UI, no option is clickable while using rancher master-head

To reproduce 
1. Login using username admin and password admin.
2. Click on Menu option on the left.
3. Click on any of the options listed. Example Cluster Management.

Expected Results:
Should navigate to Cluster Management window

Actual Results:
No response

Console output does not capture any actions.
![image](https://user-images.githubusercontent.com/56045581/116932794-8f19f380-ac17-11eb-8f2d-c7a8821b18da.png)

![image](https://user-images.githubusercontent.com/56045581/116932904-b7a1ed80-ac17-11eb-905a-eee973119000.png)

**Comment by ibuildthecloud** [comment]
This should already be fixed in https://github.com/rancher/rancher/commit/fcb120d760c8742386741e47afa026ec1a52ecdf

**Comment by ShylajaDevadiga** [comment]
Validated using rancher master-head (Commit ID: f695b78a) which is few commits after the fix. Options on the left plane are available. 
Imported rke2 v1.20.6+rke2r1 cluster using Cluster management-> Import Existing cluster option.
![image](https://user-images.githubusercontent.com/56045581/116968582-9d90fb00-ac69-11eb-9ccc-95176f61aeb7.png)
![image](https://user-images.githubusercontent.com/56045581/116968865-2ad44f80-ac6a-11eb-871f-438288f2e35e.png)
