### ISSUE TITLE
Add support for ui-banners

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2893]
The Ember UI has support for a global setting 'ui-banners' which allows banner to be shown at top and bottom of UI - need to add support for the same into Dashboard.

We should provide a form/better UI for configuring this, rather than just letting the user enter JSON.

Should separate out the branding/theming preferences into a new page alongside Settings in Global Settings.

**Comment by izaac** [comment]
Rancher version `v2.6 master-head` _d8acb21_

This feature is called `Fixed Banners` in `Global Settings -> Branding`

There's a text field, two check boxes to select which banner to show or select both Top/Bottom.
Also a Text Color picker for the text entered in the text input field. As well as it's background color.

I was able to put text select color and apply either Top or Bottom or Both. 

After that navigating back and forth between Ember and Dashboard I see the banner persists

Logging out the banners are not displayed.
Logging back in the banners are present.


Tested with both Chrome 90 and Firefox 88
