### ISSUE TITLE
Add support for custom logo

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2894]
Allow user to override the rancher logo at runtime (the one shown in the slide-in).

There is both a light and dark theme version of the logo.

Use 2 new optional settings:

- ui-logo-light
- ui-logo-dark

The user can upload one or both of these - we will store the base64 encoded image in the setting - in the image data: format, suitable for use directly as an image src - e.g. "data:image/svg+xml;base64,PD94bW...."

When the logo image is needed, if ui-logo-light is set, it will be used instead of the theme's logo image. If the dark theme is active, ui-logo-dark will be used if set, otherwise ui-logo-light will be used (allowing the user to use ui-logo-light for both light and dark themes).

Add the ability to set these images in the global settings -> brand/theming config. We should set a max image size that we will accept to prevent the user using very large images.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version d8acb21`
Tested using Rancher logos from https://rancher.com/brand-guidelines/

User is able to upload custom logos at `https://.../dashboard/c/local/settings/brand`. A max size of 20KB is allowed for images. A warning will appear if the image is too large. Ex: `rancher-logo-horiz-black.eps exceeds the file size limit of 20000 bytes`
![Screen Shot 2021-05-19 at 12 02 37 PM](https://user-images.githubusercontent.com/57409052/118869899-d2709500-b89a-11eb-9969-61d8287bbfea.png)
Custom logos are used depending on the theme selected.
![Screen Shot 2021-05-19 at 12 03 02 PM](https://user-images.githubusercontent.com/57409052/118870370-56c31800-b89b-11eb-9d31-b08291e1d06b.png)
![Screen Shot 2021-05-19 at 12 03 30 PM](https://user-images.githubusercontent.com/57409052/118870372-575bae80-b89b-11eb-99b5-948dc196f8ac.png)
Also works for logos of different sizes:
![Screen Shot 2021-05-19 at 12 21 23 PM](https://user-images.githubusercontent.com/57409052/118871805-c71e6900-b89c-11eb-83fb-ceab9cc35806.png)
