### ISSUE TITLE
Improve Version information

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2903]
- Clicking on the version string currently takes user to the new release info doc
- Clicking in ember on the version string shows a popup containing some useful info (specific versions, links to repos, downloads etc)
  ![image](https://user-images.githubusercontent.com/18697775/117148673-5bbd9d00-adae-11eb-8a7a-4694b0b69c67.png)
- I'm not sure where this info comes from, or if it only shows in specific scenarios, but we should aim to match it
- I'm also not sure where and how it should display. Would be nice in the release doc though we'd need to work out how to inject it

**Comment by vincent99** [comment]
The Helm and machine versions aren't that useful, and we generally always make the Ui version match the Rancher version now.

But the image lists are important for people setting up airgap.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 351f7ca`

From the top-left dropdown, the user is able to see version information.
![Screen Shot 2021-05-13 at 3 21 51 PM](https://user-images.githubusercontent.com/57409052/118195650-78865000-b400-11eb-895e-a83d113f5dfb.png)
`https://..../dashboard/about`
![Screen Shot 2021-05-13 at 3 21 58 PM](https://user-images.githubusercontent.com/57409052/118195651-791ee680-b400-11eb-9733-967ee4a47722.png)
