### ISSUE TITLE
Add `Download CLI` feature

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2905]
- In ember this was bottom right in the footer
  ![image](https://user-images.githubusercontent.com/18697775/117149751-66c4fd00-adaf-11eb-9331-1b7fad45b49c.png)
- Need to understand where it should go in new world

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head f223834`
Download link is accessible over "About" page (click the three horizontal lines icon and then on the version/hash in the lower left corner). The CLI link is pointing to the latest released cli version.

![rancher_cli_download](https://user-images.githubusercontent.com/12828077/118250869-306e3880-b4a7-11eb-9cc0-8d941e0c1dba.png)

Closing.
