### ISSUE TITLE
Show wechat info if zh-hans locale

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2906]
- In ember, when locale is zh-hans, an additional 'forum' is shown for wechat. Clicking on link shows a modal containing a 2d barcode
- Need to replicate this functionality somehow

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head 3ae6f43`. 

I found the link for opening the modal QR weechat window only on Home screen in "Community Support" section, problem is that this menu can be hidden here by user by clicking X.
![wechat_modal](https://user-images.githubusercontent.com/12828077/125284729-1ec7d680-e31a-11eb-84bd-9a0389b7db59.png)

The link for the modal window is not present on dashboard/support page where I would expect it.
![weechat_missing](https://user-images.githubusercontent.com/12828077/125284736-20919a00-e31a-11eb-8bd4-15e2789439e2.png)

Reopening.

**Comment by thehejik** [comment]
Now on `rancher/rancher:master-head f33188d` the link for wechat modal qr window is present also on dashboard/support page.
![wechat_support](https://user-images.githubusercontent.com/12828077/126031144-39a401cd-3b4c-4f90-8850-24a871d08147.png)

Close
