### ISSUE TITLE
No cpu/memory usage in cluster explorer from rke2 clusters

### ISSUE THREAD

**Issue by xhejtman** [rancher/dashboard#2913]
While cluster manager displays cpu and memory usage for both rke1 and rke2 clusters, cluster explorer shows cpu/mem usage for particular nodes only for rke1 clusters.

![ce](https://user-images.githubusercontent.com/22795052/117216521-322d6180-ae00-11eb-879d-79b776f60f98.png)

**Comment by gaktive** [comment]
Waiting on @richard-cox's PR to be merged though initial tests look good

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head 3ae6f43`. The cpu/mem usage data are now shown for RKE2 nodes in the cluster explorer. Close.
![rke2_usage](https://user-images.githubusercontent.com/12828077/125261258-6130e980-e301-11eb-8282-51def7667e44.png)
