### ISSUE TITLE
Apostrophes displaying as ascii code instead of `'`

### ISSUE THREAD

**Issue by Tejeev** [rancher/dashboard#2914]
The apostrophe here is showing up as an ascii code.
https://github.com/rancher/dashboard/blob/master/assets/translations/en-us.yaml#L1761
![image](https://user-images.githubusercontent.com/8906089/117219879-0e691c00-adfe-11eb-9605-ae12ceee2190.png)

**Comment by gaktive** [comment]
Found under monitoring.

**Comment by thehejik** [comment]
Testing blocked by https://github.com/rancher/dashboard/issues/3078 - unable to create any Receiver/Route in v2 monitoring

**Comment by thehejik** [comment]
The issue above has been fixed, now I see Routes and Receivers and the new string is present in `rancher/rancher:master-head f90b36e` with v2 monitoring `rancher-monitoring:14.5.101+up14.5.0`. Close.
![route](https://user-images.githubusercontent.com/12828077/119622505-80ce8a00-be07-11eb-9bee-33ff00718871.png)
