### ISSUE TITLE
Can't view/list clusters in `Cluster Management`

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2915]
there are 4 clusters available, but aren't being listed in dashboard on master-head (ebad1df)

<img width="1778" alt="Screen Shot 2021-05-05 at 4 37 58 PM" src="https://user-images.githubusercontent.com/16691014/117222474-55d0b780-adc0-11eb-8e82-62477b9088b2.png">

note: can still create a cluster, but after revisiting the `clusters` page, no clusters are listed.

**Comment by vincent99** [comment]
I'll fix it, but what kind of cluster do you have that has no `spec.kubernetesVersion`?

**Comment by slickwarren** [comment]
there are [other issues](https://github.com/rancher/rancher/issues/32532) for 2.6 that are preventing clusters from provisioning all of the way.  I did provision 1 through ember that deployed successfully, and local cluster is always there as well.

**Comment by slickwarren** [comment]
<img width="2008" alt="Screen Shot 2021-05-06 at 9 17 42 AM" src="https://user-images.githubusercontent.com/16691014/117333005-55cac900-ae4d-11eb-8611-bab80be050c5.png">

on master-head (53f17be) I am now able to see the list of clusters again

**Comment by slickwarren** [comment]
<img width="1052" alt="Screen Shot 2021-05-12 at 8 08 41 AM" src="https://user-images.githubusercontent.com/16691014/118003992-e72eb500-b2fd-11eb-806f-8c2d5f90699f.png">
I was able to reproduce this by doing this on master-head (1e1ed67):
* deploy a cluster with a bad configuration (typo in yaml)
  * cluster list still displays
* edit cluster yaml that is in bad state
* cluster list shows empty again

**Comment by slickwarren** [comment]
tested on master-head (e756276):
* clusters are all listed properly on the `cluster management` page
<img width="732" alt="Screen Shot 2021-06-25 at 2 28 10 PM" src="https://user-images.githubusercontent.com/16691014/123486797-962f0380-d5c1-11eb-9580-8a9464276892.png">
