### ISSUE TITLE
Home Page: Allow landing location to be configured

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2918]

**Comment by anupama2501** [comment]
Verified on master-head commit d8acb21
1. When the option ```Take me to the home page```, if we logout and log back in, users are taken to the homepage - PASS
2. Option ```Take me to the area I last visited```, if we logout and login, users are taken to the last visited page - Tried logging out from cluster management and landed in the cluster management page
3. Option ```Take me to cluster: ``` selected the local/custom cluster cluster and landed in that cluster explore page.

**Comment by anupama2501** [comment]
Few enhancements that would be nice to have: 
1. Landing page options are taking too much space and there is a lot of white space. It would be nice to have it as a small box. It might look cluttered if there are too many clusters. It can be placed above the community support on the right hand side.
2. If we click on the cross present in the box, the ```What do you want to see when you log in?``` is gone and if I want to reconfigure the options, it is possible from the users --> preferences page. An info tab can be added that shows we can find the option to reset the landing page from preferences.
3. ```You can change where you land when you login:``` font size can be increased or made bold to differentiate between heading and options in the box.


<img width="600" alt="Screen Shot 2021-05-19 at 1 29 34 PM" src="https://user-images.githubusercontent.com/38144301/118880057-46fd0100-b8a6-11eb-93dd-cc79b4ab320d.png">

**Comment by nwmac** [comment]
@anupama2501 Can you close this ticket if it works as expected and create a new ticket for the enhancements, please

**Comment by anupama2501** [comment]
@nwmac Sure I can open an enhancement.

I have a question for the `Take me to the area I last visited` 

> For the Take me to the area I last visited, I visit any subpage of a cluster eg., explorer cluster --> cluster dashboard --> apps and market place and log out from this page. If I re-login, I land in the cluster dashboard page rather than the apps and market place. For Users and Authentication, if the last visited is auth providers, I land in the Users page. 

Is this the expected behavior?

**Comment by nwmac** [comment]
Yes, it takes you to the area you were in, not the exact last page.

**Comment by anupama2501** [comment]
Closing this issue and filed https://github.com/rancher/dashboard/issues/3072 for enhancements
