### ISSUE TITLE
cluster create/import existing `cancel` button not working (uncaught promise)

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#2929]
on the pages `manager/provisioning.cattle.io.cluster` Cluster Management create/import existing, uncaught promise occurs when clicking the cancel button

```
vue-router.esm.js:1958 Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/c/c-m-b4ddf01c/manager/provisioning.cattle.io.cluster/create".
    at $t (https://releases.rancher.com/dashboard/latest/commons/app.48b70279e3d5c2318c97.js:2:66970)
    at e.Ut.confirmTransition (https://releases.rancher.com/dashboard/latest/commons/app.48b70279e3d5c2318c97.js:2:69936)
    at e.Ut.transitionTo (https://releases.rancher.com/dashboard/latest/commons/app.48b70279e3d5c2318c97.js:2:69265)
    at e.replace (https://releases.rancher.com/dashboard/latest/commons/app.48b70279e3d5c2318c97.js:2:72629)
    at https://releases.rancher.com/dashboard/latest/commons/app.48b70279e3d5c2318c97.js:2:77601
    at new Promise (<anonymous>)
    at Qt.replace (https://releases.rancher.com/dashboard/latest/commons/app.48b70279e3d5c2318c97.js:2:77564)
    at f.emitOrRoute (https://releases.rancher.com/dashboard/latest/app.b6ea214e6bfe6c17815a.js:2:440440)
    at f.confirmCancel (https://releases.rancher.com/dashboard/latest/app.b6ea214e6bfe6c17815a.js:2:440156)
    at Qt (https://releases.rancher.com/dashboard/latest/commons/app.48b70279e3d5c2318c97.js:2:173549)

  | $t | @ | vue-router.esm.js:1958
-- | -- | -- | --
  | Ut.confirmTransition | @ | vue-router.esm.js:1928
  | Ut.transitionTo | @ | vue-router.esm.js:2152
  | e.replace | @ | vue-router.esm.js:2531
  | (anonymous) | @ | vue-router.esm.js:2963
  | Qt.replace | @ | vue-router.esm.js:2962
  | emitOrRoute | @ | CruResource.vue:174
  | confirmCancel | @ | CruResource.vue:160
  | Qt | @ | vue.runtime.esm.js:1854
  | n | @ | vue.runtime.esm.js:2179
  | Qt | @ | vue.runtime.esm.js:1854
  | t.$emit | @ | vue.runtime.esm.js:3888
  | click | @ | CruResourceFooter.vue?82b2:1
  | Qt | @ | vue.runtime.esm.js:1854
  | n | @ | vue.runtime.esm.js:2179
  | c._wrapper | @ | vue.runtime.esm.js:6917

```
<img width="1204" alt="Screen Shot 2021-05-07 at 3 12 56 PM" src="https://user-images.githubusercontent.com/16691014/117513539-c30e5500-af46-11eb-8830-e830570c3a3e.png">

on master-head (909237a)

**Comment by sowmyav27** [comment]
Happens in this scenario as well on master-head commit id: `8c014ef`

- Navigate to the new Dashboard UI
- From left pane --> Select Cluster Management --> Create
- Select say - EC2 cluster, user is presented with a UI prompting to enter a cloud credential.
- Clicking on Cancel there, throws the same error in console as the one mentioned in the bug's original description

<img width="1080" alt="Screen Shot 2021-05-10 at 3 07 00 PM" src="https://user-images.githubusercontent.com/26032343/117730560-635fb600-b1a1-11eb-8e0f-9ae27fa8cd0c.png">

**Comment by mantis-toboggan-md** [comment]
I can't reproduce this bug; the cancel behavior appears to be fixed as of this pr: https://github.com/rancher/dashboard/pull/3102

**Comment by slickwarren** [comment]
on master head (62aef76):
cancel buttons appear to be working normally on the `create` page 
<img width="1204" alt="Screen Shot 2021-05-07 at 3 12 56 PM" src="https://user-images.githubusercontent.com/16691014/117513539-c30e5500-af46-11eb-8830-e830570c3a3e.png">

also tested cancel button on each rke2 provisioner page -- pass

<img width="1823" alt="Screen Shot 2021-05-28 at 9 19 13 AM" src="https://user-images.githubusercontent.com/16691014/120013625-d173ed80-bf95-11eb-8094-4bf3f0442b20.png">

also tested cancel button on rke2 provision page for cloud credentials -- pass

<img width="1970" alt="Screen Shot 2021-05-28 at 9 23 03 AM" src="https://user-images.githubusercontent.com/16691014/120013967-5232e980-bf96-11eb-8f88-16c2421c77fc.png">
