### ISSUE TITLE
Apps & Marketplace does not list versions containing text

### ISSUE THREAD

**Issue by viandham** [rancher/dashboard#2936]
We upgraded to 2.5.8 a few days ago, and since then the Apps & Marketplace does not list versions of apps containing non-numeric characters. For example, 1.0.0-alpha1 does not show in the list.
If an app only has versions like that, it does not show at all in the list of available apps.

In this image we can see that there are in fact a -test2 version available in the repository, we are using jFrog Artifactory. 
<img width="373" alt="artifactory" src="https://user-images.githubusercontent.com/14801971/117636934-998d3d80-b181-11eb-9e13-c3ca682acae8.png">

But in rancher, it is not available for selection.
<img width="1373" alt="rancher" src="https://user-images.githubusercontent.com/14801971/117636945-9b570100-b181-11eb-810f-fcf8d8545916.png">

**Comment by viandham** [comment]
We just downgraded to 2.5.7 and now the version is available in the list. So the issue came with 2.5.8.
<img width="1363" alt="rancher_257" src="https://user-images.githubusercontent.com/14801971/117641482-7add7580-b186-11eb-9ea5-6ca24da37c63.png">

**Comment by vincent99** [comment]
Non-releases are hidden by default now, as they are in regular Helm. There's an option in the user menu (top-right) -> Prefs to see all.

And please don't nearly simultaneously post the same question in multiple places...
