### ISSUE TITLE
Change icon for the local cluster

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2942]
The local cluster shows the icon for the cluster provider - often you'll see the k3s logo:

![image](https://user-images.githubusercontent.com/1955897/117668732-1fb77d00-b19e-11eb-8198-b0695ce0b9cb.png)

This is used at the top of some pages and in the slide-in menu.

For the local cluster, we should use a rancher logo - @lvuch will need to provide one - I suggest using the half-cow logo that we use for the favicon - this will need to be provided as an svg in the providers folder of images - something like this:

![image](https://user-images.githubusercontent.com/1955897/117674236-68256980-b1a3-11eb-84ef-a7a868ef1110.png)

This is easily wired in - look in models/management.cattle.ui.cluster.js for the providerLogo function - this can be updated to special case the local cluster to use the new image.

(@lvuch Can you do a blue and green logo - we may want to switch this once the SUSE theme and switch for this are in)

**Comment by lvuch** [comment]
@neillsom I'll slack you the svgs since gh doesn't support them

**Comment by thehejik** [comment]
The icon for local cluster has been changed in `rancher/rancher:master-head f90b36e` also when you hover over the logo the image is rendered negatively. Close.

![newlogo](https://user-images.githubusercontent.com/12828077/119637467-f5a8c080-be15-11eb-8600-c87be128fdb7.png)
