### ISSUE TITLE
Labels and Annotations tab on create screens appears incorrectly

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2943]
See below:
![image](https://user-images.githubusercontent.com/1955897/117672259-96a24500-b1a1-11eb-82e1-205c3c07383f.png)

We're clearly not using html for the tab label (text shows &amp)

This tab is reused in many places - should be a simple fix.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version d8acb21`

Labels and Annotations tab is shown correctly:
![Screen Shot 2021-05-19 at 4 57 03 PM](https://user-images.githubusercontent.com/57409052/118899413-8a199d00-b8c3-11eb-9973-cd92f823e512.png)
