### ISSUE TITLE
Table row has hover state for empty table message

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2946]
Go to something like Workload/Daemonsets when you have no. DaemonSets - this shows the 'There are no rows to show' message.

Hover over this message and the row hover bg color is shown - this should not be the case for this message, since this is not a row that can be selected.

Probably need to add a class for the empty message row and ensure it has no hover styling.

**Comment by thehejik** [comment]
**Test report:**
Successfully verified on `rancher/rancher:master-head d60543a`

I was unable to reproduce the issue. When cursor moved to the message `There are no rows to show.` the bg color is not changed.

![hoover](https://user-images.githubusercontent.com/12828077/119354389-557f5a00-bca4-11eb-8c49-27f388216b57.png)

Close.
