### ISSUE TITLE
Ensure Dashboard provides same action menu capability for clusters

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2947]
(note: available actions determine applicability of each action)

Cluster:

- Rotate Certificates
- Rotate Encryption
- Save AS RKE template
- Show Registration Command

(Snapshot has already been done) 

Node:

  - Cordon
  - Drain
  - Uncordron
  - Stop drain
  - Scale down

**Comment by gaktive** [comment]
Neil to break this ticket down into separate stories. Rotate Certs may go to @mantis-toboggan-md

**Comment by richard-cox** [comment]
Now covered by other tickets, closing
