### ISSUE TITLE
Dashboard login if local user selected when authprovider is enabled gives two login boxes

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2949]
master-8c014efa85314ab1cb1cb79261d2db9251ccf31d-head

- On rancher from explorer --> Users and Authentication --> Enable any authentication provider[tried with openLDAP/FreeIPA]
- Log out once the auth is enabled
- Select "Use a local user", we see two login boxes as follows:
<img width="100" alt="Screen Shot 2021-05-10 at 12 08 15 PM" src="https://user-images.githubusercontent.com/38144301/117711805-69956880-b188-11eb-8b2c-3fa04b3c210c.png">

**- Refresh the screen and it appears as follows:**
<img width="100" alt="Screen Shot 2021-05-10 at 12 08 29 PM" src="https://user-images.githubusercontent.com/38144301/117711876-7914b180-b188-11eb-9e9c-7b0077a7ac0d.png">

**This should be only one login space to provide username/password with Local User/Auth provider.
Ember UI for reference:**

<img width="100" alt="Screen Shot 2021-05-10 at 12 09 52 PM" src="https://user-images.githubusercontent.com/38144301/117712015-a5c8c900-b188-11eb-83e8-18ef7a93299e.png">

**Comment by nwmac** [comment]
@mantis-toboggan-md I don't think this is an issue any longer - can you verify

**Comment by anupama2501** [comment]
@mantis-toboggan-md on master-head 618c9ef

From Auth providers --> enabled openLDAP auth --> logged out of the cluster --> and tried to re-login using a local user

button `Log in with OpenLDAP` goes above the username and password fields as shown in the screenshot below
This would look good if it is interchanged with the `login in with OpenLDAP button` itself

**Dashboard UI:**
<img width="300" alt="Screen Shot 2021-06-01 at 9 13 25 PM" src="https://user-images.githubusercontent.com/38144301/120422914-35900c00-c31e-11eb-80e0-52ddde266a40.png">

**Ember UI:**
<img width="300" alt="Screen Shot 2021-06-01 at 9 14 40 PM" src="https://user-images.githubusercontent.com/38144301/120423174-c1a23380-c31e-11eb-8ad9-2c8638cbfe4d.png">

**Comment by anupama2501** [comment]
Verified on 6b430f3 master-head
1. Enabled the auth openLDAP from explorer --> users and authentication 
2. Once the auth is enabled and if local users login is selected, switches in the same tab
<img width="200" alt="Screen Shot 2021-06-10 at 2 43 50 PM" src="https://user-images.githubusercontent.com/38144301/121601074-4a456180-c9fa-11eb-8c9c-27ed9e98fb22.png">
