### ISSUE TITLE
Make the Explore Cluster Section adjustable

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2950]
**On master-head commit id: `8c014ef`**

- Navigate to Dashboard UI 
- On the left pane, can we make the Explore Cluster Section _adjustable_? As I have a large number of clusters -- 7
- And to list/view them all at a time, instead of scrolling in that section, can we make it adjustable, so that user can maybe drag and make that section bigger to list all the clusters? 

<img width="527" alt="Screen Shot 2021-05-10 at 1 47 27 PM" src="https://user-images.githubusercontent.com/26032343/117723001-af592d80-b196-11eb-9f78-162f34bc44fe.png">

**Comment by nwmac** [comment]
This is not a bug - this is an enhancement request - we can add a pref for this, but that is new work.

**Comment by nwmac** [comment]
Added a new preference to allow the number of clusters shows to be configured.

**Comment by sowmyav27** [comment]
**On master-head commit id: `5d49b92`**
<img width="584" alt="Screen Shot 2021-06-02 at 7 53 11 AM" src="https://user-images.githubusercontent.com/26032343/120503360-16be6380-c378-11eb-9acf-ee9d01e0d0bf.png">

For issues around it logged a separate bug - https://github.com/rancher/dashboard/issues/3150
