### ISSUE TITLE
v2 cluster have only etcd as the role even when all roles are enabled for the nodes

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2955]
On master-8c014efa85314ab1cb1cb79261d2db9251ccf31d-head

1. Create a v2 cluster with 1 node all roles enabled
2. Once the cluster is active, from explorer --> EXPLORE CLUSTER --> Select the cluster created and from cluster dropdown --> nodes --> verify the roles shows only etcd

<img width="500" alt="Screen Shot 2021-05-10 at 5 37 03 PM" src="https://user-images.githubusercontent.com/38144301/117741116-7f218700-b1b6-11eb-8fe7-1c6ce30475b6.png">

**Comment by gaktive** [comment]
Probably backend.

**Comment by vincent99** [comment]
rke2 sets the `node-role.kubernetes.io/control-plane` label instead of `…/controlplane`, updated the UI to support both.  The backend needs to add the `…/worker` label.

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/pull/33761 
https://github.com/rancher/rancher/issues/33385

**Comment by deniseschannon** [comment]
Validated that on the Kube Node and Machine page, a node that has all 3 roles shows "All".
