### ISSUE TITLE
Show v1 charts in Cluster Tools within Cluster Explorer

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#2959]
As mentioned here https://github.com/rancher/dashboard/issues/2578#issuecomment-810476200 it would be great to display v1 Apps in the new Cluster Tools view within Cluster Explorer. 

Currently only v2 Apps from rancher helm chart repo are displayed in rancher/rancher:master-head `6030ab5`

**Comment by thehejik** [comment]
Both v1 apps for monitoring and logging are present there and could be installed by clicking on `Install` button on `(Legacy)` apps and are working.

But I found following problems with the embedded v1 charts in `Cluster Tools`:
1) user is unable to select whether the chart will be installed on `Cluster Level` or `Project Level` - seems both charts can be installed on `Cluster Level` only.

2) after installing both charts the `Install` button is still there and active but in addition `Edit` button is now active for "v2" monitoring/logging which are not installed. 

This is the `Cluster Tools` list after installing both v1 apps - note there are now 2 duplicating entries for both apps - `Edit` button is available for "v2" apps and `Install` button for "legacy/v1" apps:
![legacy_apps_in_cluster_tools](https://user-images.githubusercontent.com/12828077/120214240-7dd2ff80-c234-11eb-949f-bd9ab30cb1b0.png)

3) the legacy apps can not be simply deleted by clicking on the trash bin belonging to "v2" app in `Cluster Tools` - apps are still active - they could be deleted only in the iframed chart form by clicking on v1 app's `Install` button followed by selecting `None` for logging provider or by clicking `Disable` button for v1 monitoring.

4) I didn't find a way how can I access for eg. monitoring links for prometheus/grafana/metrics from Explorer - I see them only in in Ember/System Project/Apps:
![apps_ember](https://user-images.githubusercontent.com/12828077/120213211-3c8e2000-c233-11eb-96ab-9c044e058b6e.png)
In explorer I see them only in `Installed Apps` without the links visible:
![apps_explorer](https://user-images.githubusercontent.com/12828077/120213386-6cd5be80-c233-11eb-81f4-75afd2139a91.png)

On the other hand the graphs for v1 monitoring are now embeded in Explorer/Cluster overview and the grafana links presented there are active and working:
![graphs_explorer](https://user-images.githubusercontent.com/12828077/120216454-56c9fd00-c237-11eb-91fd-a2597c71046e.png)

@nwmac could you please tell me if the issues above are expected? I also wonder if you are going to add more v1 apps there in future?

**Comment by nwmac** [comment]
1) You only install cluster monitoring here - Project monitoring is installed through the 'Legacy -> Project' in the side navigation.

2) I'll fix this, so you can't install V1 when V2 is installed

3) You have to go into the legacy app and disable - we may bring this out to a delete icon button in the future.

4) I don't fully understand the comment - but the integrated metrics views for V1 are the way to access grafana for now.

**Comment by thehejik** [comment]
**Test report:**

1. WORKS - v1 apps could be installed by clicking `Cluster Tools` in Explorer, selecting the desired project in the top ns/project dropdown and then going to `Legacy -> Project -> Apps` and clicking `Launch button` (as in Ember but now in iframe).
2. WORKS - `Install` button for v1 app is now inactive after v1 or v2 app installation
3. WORKS - can be uninstalled either in Ember (cluster level) or in `Legacy -> Project` in Explorer
4. WORKS - links visible under `Legacy -> Project-> Apps` 

Installing into project level can be done by clicking `Cluster Tools`, selecting the desired project in the top ns/project dropdown and then going to `Legacy -> Project -> Apps` and clicking `Launch button` (as in Ember but now in iframe) - **PASS**

Tried following app upgrades in Explorer:
* go to `Apps and Marketplace -> Installed Apps`
* select logging / monitoring and click the orange link with the v2 version:
  - for v1 `logging-0.2.4` to v2 `v100.0.0.+up3.10.0` the upgrade is possible - **PASS**
  - for v1 `monitoring-0.2.3` upgrade is not supported, user has to first uninstall v1 app by clicking `Uninstall` button after clicking the orange link with the new version - **PASS**

Also tested setting of a new Notifier (webhook) and Alerts in Default project:
* add a notifier eg webhook
* go to Cluster Tools -> switch to Default project
* Edit Alert Group `A set of alerts when event happened` and select the notifier, create rule "pod changes" `When: Normal pod` and `Happens Send a Info` and press Save
* go to Workload/Deployments and create a simple workload with 10 replicas with nginx
* go to Workload/Deployment, select the new deployment and delete one of the pods
* alert is comming to webhook service - **PASS**


V1 apps can be uninstalled only either in Ember or from Explorer by clicking `Cluster Tools` button and then uninstall `Legacy -> Projects -> Apps` - **PASS**

Only problem I found is that v1 apps are showing in Apps and Marketplace but couldn't be uninstalled from there due https://github.com/rancher/dashboard/issues/3223


Close.
