### ISSUE TITLE
User is incorrectly redirected to CLuster Manager page when clicking on Cluster tools from Preferences page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2960]
**On master-head commit id: `8c014efa`**

- Navigate to the new Home page in Dashboard. (new)
- Go to Preferences on the top right. corner
- Click on Cluster tools on the bottom left
- User is redirected to Cluster Manager page with this message

<img width="407" alt="Screen Shot 2021-05-11 at 6 34 27 AM" src="https://user-images.githubusercontent.com/26032343/117824973-c4c86900-b223-11eb-86fd-e32c1cd742d6.png">

Context of the cluster Tools is local cluster in this scenario, so the user is expected to be redirected to the Cluster tools of the local cluster?

**Comment by kravciak** [comment]
There is no `Cluster Tools` button available on Preferences page anymore, closing.

Tested on master-head f90b36e
