### ISSUE TITLE
Cluster Provisioning v2: Make Edit Cluster work in Embedded Ember pages

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2968]

**Comment by aaronRancher** [comment]
On Rancher `master-head` `version 3e89bb8`

After saving an edit, the fields will disappear:
![Screen Shot 2021-05-12 at 11 45 50 AM](https://user-images.githubusercontent.com/57409052/118037601-eceac180-b322-11eb-9bd8-fafbdfc4486e.png)
User cannot get out of this without selecting `cancel`

**Comment by aaronRancher** [comment]
On Rancher `master-head` `version be0b016`

User is unable to edit an imported RKEv2 cluster.
![Screen Shot 2021-05-14 at 3 45 21 PM](https://user-images.githubusercontent.com/57409052/118338628-776e2500-b4cb-11eb-9908-dcafc15c0627.png)
Expected:
![Screen Shot 2021-05-14 at 3 41 49 PM](https://user-images.githubusercontent.com/57409052/118338570-53aadf00-b4cb-11eb-9a12-d0ac5f148877.png)

**Comment by izaac** [comment]
Edit was covered as part of the provisioning issues for the following cluster types:

RKE1 EC2 validated here: https://github.com/rancher/dashboard/issues/2771
RKE1 DO validated here: https://github.com/rancher/dashboard/issues/2773

**Comment by slickwarren** [comment]
also covered for these cluster types:
RKE1 azure: https://github.com/rancher/dashboard/issues/2774
RKE1 vsphere: https://github.com/rancher/dashboard/issues/2772
RKE1 custom/generic cluster: https://github.com/rancher/dashboard/issues/2777

**Comment by sowmyav27** [comment]
Any issues found are logged separately. Closing this issue
