### ISSUE TITLE
Cluster Provisioning: Create v2 Cloud Credentials & Node Pools - vSphere

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2969]

**Comment by slickwarren** [comment]
currently blocked from validating this ticket by https://github.com/rancher/rancher/issues/33078

**Comment by slickwarren** [comment]
on master-head (da1adad) -- workaround for blocker above is to manually set the host (default is `any`):
* create vsphere cluster using node provisioner (rke2) -- pass
  * create vsphere cluster using node provisioner (rke2) multinode -- pass
* create vsphere cluster using node provisioner (rke1) -- pass
* create vsphere cluster using custom cluster (rke2) -- pass
  * create vsphere cluster using custom cluster (rke1) -- pass
