### ISSUE TITLE
UX Design review for Deployment Wrangler (Rio)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#297]
This issue is to track any effort for creating/reviewing UX design for the Rio Deployment Wrangler.

The Deployment Wrangler at a high level is basically an add-on to the deployments which adds Rio functionality. This essentially replaces the concept of Rio services.
Based on our discussion 1/30/20 it sounded like this should just show as a new field(s) on the UI Deployment page.

**Comment by tfiduccia** [comment]
Was told this was no longer a stand alone thing?

**Comment by davidnuzik** [comment]
Who mentioned this?
cc: @cbron

**Comment by cbron** [comment]
When DW moves along we'll have to discuss how we want to implement in the UI. As its still in flux I'm not sure what that process would look like yet.
