### ISSUE TITLE
Cluster Provisioning v2: etcd snapshots

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2971]
This would cover things like:
- Advanced Configuration for Location/Schedule
- View etcd RKE1 snapshots (iFrame)
- View etcd RKE2 snapshots
- On demand etcd snapshots (local and S3)
- etcd Restore (local and S3) whereby
a) restore only etcd
b) restore with etcd & k8s version
c) restore with etcd, k8s and cluster config

Note: A separate issue, https://github.com/rancher/rancher/issues/32391 was created for RKE2. QA tested RKE2 aspects in that issue, this issue is used for testing RKE1.

**Comment by gaktive** [comment]
According to Denise, this stuff is already in. @vincent99 to confirm.

**Comment by vincent99** [comment]
On-demand snap and restore to/from S3 are missing, the rest is in.

**Comment by vincent99** [comment]
As with RKE1, the S3 options aren't shown for on-demand, but if S3 is configured on the cluster then the on-demand snapshot will be written to that S3 config.

**Comment by davidnuzik** [comment]
Related: https://github.com/rancher/dashboard/issues/3624

**Comment by davidnuzik** [comment]
We cannot test this issue until https://github.com/rancher/dashboard/issues/3624 is fixed

**Comment by davidnuzik** [comment]
The RKE2 aspects of this are duplicated by https://github.com/rancher/rancher/issues/32391.
Refer to https://github.com/rancher/rancher/issues/32391 for my RKE2 testing.

**Comment by davidnuzik** [comment]
I noticed during my testing ONLY RKE1 provides restore types is this expected @deniseschannon ?
![image](https://user-images.githubusercontent.com/45179589/128268460-2997a0cd-9cec-4fbc-ba58-e010607b3f33.png)

I would think most likely yes because of how etcd backup/restore differs slightly on backend between RKE1 and RKE2.

**Comment by davidnuzik** [comment]
All RKE1 snapshot/restore checks (s3 and local) pass. Again, for RKE2-specific tests, refer to https://github.com/rancher/rancher/issues/32391 instead. I'll use that issue for RKE2 checks.
