### ISSUE TITLE
Embed from iFrame: Hosted and imported GKE

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2973]

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 3e89bb8`

Was able to deploy a hosted GKE cluster. And import an GKE cluster through dashboard embed from Ember.
Tested with RKE2 feature flag turned on and off to ensure GKE clusters are not impacted.
Was also able to edit the clusters from dashboard Cluster Management view.
