### ISSUE TITLE
Embed from Ember: Hosted and imported AKS v1

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2975]
Though this will be replaced by v2 soon enough.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 3e89bb8`

Was able to deploy a hosted AKS v1 cluster through dashboard Cluster Management view. And was able to edit this cluster through Cluster Management view.
 Importing an AKS cluster is not available in the UI. Will have to test import manually.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 351f7ca `

Was able to import an AKS cluster through dashboard Cluster Management view. 
![Screen Shot 2021-05-13 at 3 15 07 PM](https://user-images.githubusercontent.com/57409052/118194412-2f350100-b3fe-11eb-85da-8db175ca6599.png)
