### ISSUE TITLE
Cluster Provisioning v2: Single Cloud Credentials for RKE1 & RKE2

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2976]
As it stands with cloud credentials, though RKE1 & RKE2 rely on their own settings in the UI but they are actually the same.

**Comment by deniseschannon** [comment]
Currently, we have cloud credentials v1 and v2, but it's confusing to the user cause

Cloud Credential v1 supports items from the provisioning v1 framework (RKE1, EKSv2, AKSv2, GKEv2)
Cloud Credential v2 supports items from teh provioning v2 framework (RKE2/k3s) and eventually the next gen of hosted providers.

We will be fixing this by:

Backend - Provisioning a cluster will be able to reference the old cloud credentials which are in a different namespace.
UI - Cloud Credential support in Vue will use the old Norman API to create cloud credentials.

This ticket is tracking the UI portion.

**Comment by sowmyav27** [comment]
**In 2.6-head commit id: `4b6af95`**

- Cloud creds for v1 and v2 clusters are the same/common. 
- Cloud creds are found under Cluster Management --> cloud credentials
- User is able to create a cloud credential and use it in a v1 cluster's node template
