### ISSUE TITLE
Any modifications in the cluster during cluster creation, after an error is seen on Save is not considered

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2978]
**On master-head commit id: `3e89bb8`**

- From the new Cluster explorer --> Cluster Management --> Create
- Create a DO RKE2 cluster
- Have a nodepool names `Sowmya-1`
- Create the cluster
- Request sent has - `generateName: "nc-testt-Sowmya-1-"`
- Error seen: `DigitaloceanConfig.provisioning.cattle.io "nc-test-do-Sowmya-1-s2lv9" is invalid: [metadata.generateName: Invalid value: "nc-test-do-Sowmya-1-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "nc-test-do-Sowmya-1-s2lv9": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]`
- Edit the nodepool name and change to `sowmya-1` in the same page
- Request sent _still_ has - `generateName: "nc-testt-Sowmya-1-"`
- The only way the user can get out of this way is to delete this nodepool and add a new one and proceed with cluster creation

**Expected:**
Any edits in the cluster should be saved and sent.

**Note:**
This happens to edit of any other field on the cluster too. Not just Nodepool name

**Comment by sowmyav27** [comment]
**On master-head commit id: `5d2b7ac`**

- From the new Cluster explorer --> Cluster Management --> Create
- Create a DO RKE2 cluster
- Have a nodepool names Sowmya-1
- Create the cluster
- Cluster is seen in error state with error: `failed to create fleet-default/do-new-nodepool-Sowmya-1 rke-node.cattle.io/v1, Kind=DigitaloceanMachineTemplate for rke-cluster fleet-default/do-new: DigitaloceanMachineTemplate.rke-node.cattle.io "do-new-nodepool-Sowmya-1" is invalid: metadata.name: Invalid value: "do-new-nodepool-Sowmya-1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), failed to create fleet-default/do-new-nodepool-Sowmya-1 cluster.x-k8s.io/v1alpha4, Kind=MachineDeployment for rke-cluster fleet-default/do-new: MachineDeployment.cluster.x-k8s.io "do-new-nodepool-Sowmya-1" is invalid: metadata.name: Invalid value: "do-new-nodepool-Sowmya-1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

**Question**
- The error seen after provisioning of the cluster, can that be shown during cluster creation itself? Instead of the user seeing an error after provisioning, it would be good during provisioning for the user to correct the nodepool name? 
- When the cluster name has this name `Do-new2`, the cluster is created as `do-new2`, it is all lower case. Can we not do the same for nodepools? 
- Also in Ember UI, we are able to deploy nodepools with name `Sowmya-1` (with upper case)

**Comment by vincent99** [comment]
Changed the naming to do lowercase, trim, and spaces->hyphens so that most common input becomes something valid for k8s. This affects all resource name fields.  Actual validation that what you've provided is allowed and preventing submitting the form until it is would be part of https://github.com/rancher/dashboard/issues/2528.

**Comment by sowmyav27** [comment]
**On master-head commit id: `d44698d`**

- Creating a cluster/nodepool (DO RKE2) with name - `Sowmya-do`, creates it with `sowmya-do`
- No error seen
