### ISSUE TITLE
Admin is able to delete local cluster from cluster management --> Clusters list page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2979]
**On master-head - commit id: `3e89bb8 `**

- Navigate to New cluster dashboard UI --> Home --> Left panel --> cluster management --> Clusters list page
- Select and Delete local cluster
- Cluster gets removed from the Cluster list page.

**Expected:**
User should not be able to delete the local cluster from this page

**Comment by vincent99** [comment]
API should enforce this...

**Comment by sowmyav27** [comment]
In Ember UI, Admin is able to delete the local cluster from API (View in API --> Delete). However, from UI, the `Delete` option for local cluster is disabled.

**Comment by gaktive** [comment]
Is there a related backend ticket for the larger concern about what's possible via the API and CLI? The UI could add something to mitigate this but the backend side sounds scarier.

**Comment by sowmyav27** [comment]
**On master-head, commit id: `ac7cef3`**

- Select Local cluster, delete option is not available
- Deploy a custom cluster.
- Select Custom cluster and then Local cluster
- Select Delete
- Only the custom cluster is seen deleted.
