### ISSUE TITLE
UX Design review for Deploying Rio

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#298]
This issue is to track any effort for creating/reviewing UX design for the page/method for deploying Rio.

As a reminder (some notes from our 1/30/20 meeting), since Rio needs Istio and Istio needs Monitoring the UI needs to support boostrapping these two required apps before starting up Rio.
Additionally, note that the dashboard needs to support the same resource checks we have today in the ember UI (to ensure the cluster has sufficient resources to deploy the apps). 

We noted that the rio system-chart needs the hooks to support specifying the cpu/memory limits/requests. This is being done in https://github.com/rancher/system-charts/pull/151

**Comment by tfiduccia** [comment]
During Design look at:
https://github.com/rancher/dashboard/issues/194
https://github.com/rancher/dashboard/issues/195

**Comment by nwmac** [comment]
We've just removed Rio functionality, so this is no longer applicable.
