### ISSUE TITLE
Node providers are shown as unknown in cluster management view

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#2985]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
From dashboard Cluster Management view, deploy an EKS, GKE, or AKS cluster.

**Result:**
Providers will show as unknown.
![Screen Shot 2021-05-12 at 11 17 01 AM](https://user-images.githubusercontent.com/57409052/118042704-41913b00-b329-11eb-8a1c-16e862ebce39.png)
On cluster view, it shows that node providers are unknown:
![Screen Shot 2021-05-12 at 1 54 09 PM](https://user-images.githubusercontent.com/57409052/118042922-89b05d80-b329-11eb-88e0-9832bd814b4e.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version 3e89bb8`
- Installation option (single install/HA): Single install

**Comment by vincent99** [comment]
EKS and GKE should work, I don't know what's going on with AKS having a genericEngineConfig in it and don't have an account yet to try it..

**Comment by vincent99** [comment]
@westlywright Can you spin up an AKS cluster and see if this is still broken, then fix or point me at it?

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 5b0da3d `

GKE, AKS, and EKS are shown correctly as providers:
![Screen Shot 2021-07-08 at 10 33 49 AM](https://user-images.githubusercontent.com/57409052/124966727-7b548a00-dfd8-11eb-89aa-561249de3fec.png)
Cluster view:
![Screen Shot 2021-07-08 at 10 03 50 AM](https://user-images.githubusercontent.com/57409052/124967176-f87fff00-dfd8-11eb-9d7d-7d0166ac87b6.png)
