### ISSUE TITLE
Error when setting the Root Disk Size on RKE2 / EC2 cluster provisioning

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#2986]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Dashboard RKE2 EC2 node template
- Create a new node from that and change the default value of the `Root Disk Size'

**Result:**

`Amazonec2Config.provisioning.cattle.io "nc-undefined-pool1-rcggx" is invalid: rootSize: Invalid value: "integer": rootSize in body must be of type string: "integer" `

`rootSize: 50` <--- The API has this

**Other details that may be helpful:**

If I don't change the field. Provisioning starts. I don't see `rootSize` in the POST payload with defaults.

- Fleet enabled
- RKE2 enabled

**Environment information**
- Rancher version: `v2.6` `master-head (05/12/2021)` _3e89bb8_
- Installation option: HA

**Comment by vincent99** [comment]
This is from the API @ibuildthecloud ; it's submitted as an integer in the JSON.

**Comment by vincent99** [comment]
Apparently that well-worded error from k8s means it was expected to be a string but was found to be an integer.  Changing in the UI.

**Comment by izaac** [comment]
Rancher version `v2.6 master-head` _55f0bb2_

I was able to create a single node EC2 RKE2 cluster and specifying a custom root disk size
