### ISSUE TITLE
AKS provisioner shown as "Genericengine"

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#2987]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
From dashboard Cluster Management view, deploy an AKS cluster.

**Result:**
When cluster is available, navigate to cluster view
![image](https://user-images.githubusercontent.com/57409052/118055178-7b1f7180-b33c-11eb-8969-2daaa50e49f9.png)
![Screen Shot 2021-05-12 at 11 14 14 AM](https://user-images.githubusercontent.com/57409052/118055204-85da0680-b33c-11eb-9a4e-ee9f64152d4a.png)
Provisioner is `Genericengine`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version 3e89bb8`
- Installation option (single install/HA): Single install

**Comment by gaktive** [comment]
We may have to investigate whether this is coming from AKS or somewhere else.

**Comment by westlywright** [comment]
I'm going to kick this back over to test. I believe there have been some updates on the backend that have alleviated this problem. I now see the Provisioner is `Azure AKS`. The Machine Provider is still unknown but I believe this is expected for this provider.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version c7f3cce`

AKS provisioner is seen on dashboard cluster view:
![Screen Shot 2021-06-28 at 5 02 35 PM](https://user-images.githubusercontent.com/57409052/123717904-a8fc3f00-d832-11eb-8bec-8acf29de251a.png)
![Screen Shot 2021-06-28 at 4 57 28 PM](https://user-images.githubusercontent.com/57409052/123717836-8702bc80-d832-11eb-8b12-ab8f4e78cfaf.png)
