### ISSUE TITLE
RKE cluster available under Hosted Kubernetes cluster during cluster creation

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2988]
**On master-head commit id: `3e89bb8 `**

- On the new UI --> Cluster Management --> Clusters --> Create
- RKE cluster available under Hosted Kubernetes cluster.

<img width="1674" alt="Screen Shot 2021-05-12 at 4 22 56 PM" src="https://user-images.githubusercontent.com/26032343/118057825-92ad2900-b341-11eb-8e8e-4069832cfea9.png">

**Question:**
What is RKE cluster option for?  It should not be under Hosted Kubernetes clusters though

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version be0b016`

RKE cluster is no longer available under hosted k8s cluster. Tested with RKE2 feature flag on and off.
![Screen Shot 2021-05-14 at 2 05 14 PM](https://user-images.githubusercontent.com/57409052/118331419-7cc47300-b4bd-11eb-84d5-52d8828e1b90.png)
