### ISSUE TITLE
[GKE] Cluster is stuck in updating state after node pool scale

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#2989]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
On Rancher `master-head` `3e89bb8` provision a hosted GKE cluster 
From dashboard cluster management UI, edit the cluster.
Scale the node pool and save changes.

**Result:**
Cluster will become stuck in waiting state `Waiting for nodes`
GKE operator `v1.0.1` logs show that cluster is done updating:
`time="2021-05-12T22:32:24Z" level=info msg="cluster [c-4dqfw] finished updating"` 

**Other details that may be helpful:**
The cluster has been scaled in GKE console and in Rancher UI. 
In API view, the initial node count is not scaled in gkeconfig or in upstreamspec.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version 3e89bb8`
- Installation option (single install/HA): Single install

**Comment by vincent99** [comment]
It's literally just the ember page in a frame... this is probably an Ember issue, possibly that some changes for GKE were put into 2.5.x but not also put into master?

**Comment by aaronRancher** [comment]
This behavior is seen because of a bug in Dashboard (https://github.com/rancher/dashboard/issues/2968#issuecomment-840063630). This second save page causes the cluster to be stuck in upgrading if the user hits `save` a second time.
I believe this is because the UI sends a different request the second time `save` is hit to try and leave the edit page. The UI sends many fields as `null` when they should be an empty string. The gkeconfig is also sent as `null`. Default values for `capacity` and `allocatable` are also changed.
Expected:
![Screen Shot 2021-05-13 at 3 04 22 PM](https://user-images.githubusercontent.com/57409052/118193579-cf8a2600-b3fc-11eb-8a1d-8966cffaca17.png)

Sent from UI a second time:
![Screen Shot 2021-05-13 at 3 05 10 PM](https://user-images.githubusercontent.com/57409052/118193584-d153e980-b3fc-11eb-9c2d-9d99546aefca.png)

Will retest this issue after the edit page has been fixed.

**Comment by aaronRancher** [comment]
Closing this issue, as it has been fixed by https://github.com/rancher/dashboard/issues/3006#issuecomment-857029963
The GKE cluster is not stuck updating after an edit from dashboard cluster management view.
