### ISSUE TITLE
[Monitoring V2 UI] PV options for Prometheus & Grafana should be required and validated as correct

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2994]
In the screenshots below, the configuration of Grafana's PV defaults to null values and allows you to still proceed with the installation. However, these values should be required to be non-null to successfully deploy Grafana with PVs.

Based on the Grafana Helm chart, the defaults for the following fields in either a PVC or StatefulSet template should be:
Header / Label Name | k8s YAML | Default
---|---|---|
Size | `grafana.persistence.size` | `10Gi`
Access Mode | `grafana.persistence.accessModes` | `["ReadWriteOnce"]`
PVC Finalizers (only available if type is PVC) | `grafana.persistence.accessModes` | `["ReadWriteOnce"]`
Storage Class Name | `grafana.persistence.storageClassName` | None, but this field is **Required**. User should not be able to proceed without it.
PVC Finalizers | `grafana.persistence.finalizers` | `["kubernetes.io/pvc-protection"]`

This was due to a miscommunication on the original ticket for these fields (seen here https://github.com/rancher/dashboard/issues/908) where the default was specified incorrectly to be `null`.

In addition, we need to ensure that the values provided for either Prometheus or Grafana's StatefulSet values for `Size`, `Access Mode` are required. `Size` must be a valid string for a memory size (e.g. Gi) and Access Mode must have at least one item in the list.

Related Issue: https://github.com/rancher/rancher/issues/31900
- Note: UI changes can be made independently of this backend fix; the backend fix will be with the validation of the template that is provided, but the UI should still prevent you from submitting invalid configuration via the UI components (not Edit as YAML) if possible. 

### Defaults in the UI today

![Screen Shot 2021-05-13 at 4 33 23 PM](https://user-images.githubusercontent.com/13127443/118199922-f0587880-b408-11eb-8a03-7690f4875a35.png)
![Screen Shot 2021-05-13 at 4 33 44 PM](https://user-images.githubusercontent.com/13127443/118199958-fd756780-b408-11eb-975e-9768e54fa348.png)
![Screen Shot 2021-05-13 at 4 33 56 PM](https://user-images.githubusercontent.com/13127443/118199974-0403df00-b409-11eb-886e-b9217f857f6b.png)

**Comment by gaktive** [comment]
Ties into a broader need to improve validation across all forms.

**Comment by catherineluse** [comment]
Note: This ties into https://github.com/rancher/dashboard/issues/5754. The questions.yml enhancements should support the validation specified in this issue.
