### ISSUE TITLE
Extra spaces in copied registration command

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#2998]
In Cluster management -> Import existing -> Import -> Create new cluster.

Copied registration command contains extra spaces when copied.

When pasted it shows:
```

        kubectl apply -f https://<URL...>.yaml
      
```
instead of 
```
kubectl apply -f https://<URL...>.yaml
```

Tested on master-head (f223834)

**Comment by kravciak** [comment]
Closing since it's duplicate

**Comment by sowmyav27** [comment]
Dup of https://github.com/rancher/dashboard/issues/2991
