### ISSUE TITLE
UX Design for Longhorn

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#300]
Longhorn notes:
1.  Schedule usability for Volumes backups.  
2.  Move schedules to backup tab.  
3.  Make sure to distinctly show ones created by LH and those that pre-exist.
4.  Review and redesign table headers

**Comment by tfiduccia** [comment]
Google doc with list of pages: https://docs.google.com/spreadsheets/d/1Q7CZUNrEz4w7JGkqasNdJAvUvLahLUGT5pCP0BkU4Xw/edit#gid=0

**Comment by tfiduccia** [comment]
Wireframe link:
https://xd.adobe.com/view/9c71999d-cefd-4578-bfea-14a496e780d3-c922/

Google doc link:
https://docs.google.com/document/d/1FVR17UiIZNf8MjUEKdSD8mGj3uAOBLd1iYEstb83BLE/edit?usp=sharing

**Comment by maggieliu** [comment]
This needs backend work and will be a long term goal

**Comment by nwmac** [comment]
Closing this as a stale issue
