### ISSUE TITLE
Add move icon for Projects/Namespaces

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#3004]
Need to add the `icon-fork` that ember has to dashboard.

![image](https://user-images.githubusercontent.com/55104481/118330931-eb550100-b4bc-11eb-9776-0d3a71edf4ea.png)
![image](https://user-images.githubusercontent.com/55104481/118330943-ef811e80-b4bc-11eb-9fc9-fffb1b0e3dca.png)

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/3069

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `4b6af95`**

Move Icon is available in Project/Namespaces
<img width="572" alt="Screen Shot 2021-08-08 at 3 56 40 PM" src="https://user-images.githubusercontent.com/26032343/128648115-d74c5919-95bb-4bb2-8f8e-19928f0c7ed2.png">
