### ISSUE TITLE
Only AWS and DO providers available for Cluster Credentials page in Explorer

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3011]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Deploy `rancher/rancher:master-head 5d2b7ac` anywhere
* Go to Cluster Management page in Explorer -> Cloud Credentials
* Click Create a new Secret

**Result:**
* Only Amazon and Digital Ocean providers are listed for selection:
![cloud_credentials](https://user-images.githubusercontent.com/12828077/118493964-f2c91400-b721-11eb-8af5-494cc7794c1e.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher/rancher:master-head 5d2b7ac`
- Installation option (single install/HA): any

**Comment by sowmyav27** [comment]
For RKE1 cloud credentials, navigate to CLuster Management --> RKE1 --> Cloud credentials. This page (original issue) is RKE2.
