### ISSUE TITLE
Imported cluster has wrong landing page

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3012]
Opening imported cluster from `Menu -> Cluster management -> Name` redirects to page with registration commands even when cluster is already registered.

Expected result: 
- show cluster home page when cluster is registered
- show page where I can see registration commands if cluster is not registered

Opening cluster in dashboard from other locations redirects to cluster home fine, for example from
 - EmberUI -> Explorer
 - Dashboard home page
 - Menu -> Cluster management -> Explore

This might be expected or temporary behavior since I can't find other way to display registration commands again.
Please confirm.

Tested on master-head (5d2b7ac)
Cluster: Imported rke2 single node cluster

**Comment by nwmac** [comment]
@kravciak This is the expected behaviour - when on the Cluster Management view, clicking on the name takes you to the details for the cluster, since you're in the mgmt world. You click the Explore button to explore the cluster.

If this is confusing, we can look to mitigate.

**Comment by kravciak** [comment]
Closing based on last comment
