### ISSUE TITLE
Cluster registration command is not always visible

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3014]
Registration command is not visible after creating imported cluster.
It's displayed only after page reload.

This was around 40% reproducible in my case.

![Screenshot from 2021-05-17 16-20-54](https://user-images.githubusercontent.com/538604/118504620-f5306b80-b72b-11eb-997b-0b50436501e9.png)

rke2 feature flag: off
Tested on master-head (5d2b7ac)

**Comment by vincent99** [comment]
This shouldn't happen anymore in theory, the UI now waits for the underlying management.cattle.io.cluster to show up before sending you to this screen (which then generates the clusterregistration token and shows it)

**Comment by kravciak** [comment]
Blocked on https://github.com/rancher/dashboard/issues/3120

**Comment by thehejik** [comment]
The reg. command still won't show up without manual reload of Vue in `rancher/rancher:master-head c7f3cce`

Deploy any local cluster with `rancher/rancher:master-head c7f3cce`

This is how it looks before performing a manual reload (no Registration tab):
![import_noreload](https://user-images.githubusercontent.com/12828077/123640380-65e5a000-d821-11eb-9e41-8931b2960f68.png)

And this is how it should look - but in this case user have to perform manual reload:
![import_reload](https://user-images.githubusercontent.com/12828077/123640629-a8a77800-d821-11eb-9739-8edd195c30de.png)

**Comment by kravciak** [comment]
I am still able to reproduce in ~40% of tries on master-head (c7f3cce).

**Comment by kravciak** [comment]
Closing as dup of https://github.com/rancher/dashboard/issues/3398
