### ISSUE TITLE
Cluster provider is not correctly recognized

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3015]
Importing rke2 cluster in dashboard / ember recognizes 2 different providers.
Only rke2 clusters imported in EmberUI can be edited.

**Imported in Dashboard: `Unknown RKE2`**
 - not possible to edit cluster after import

![Screenshot from 2021-05-17 16-32-18](https://user-images.githubusercontent.com/538604/118506440-9bc93c00-b72d-11eb-8728-836de793c514.png)

**Imported in EmberUI: `Imported`**
 - cluster edit config works as expected in dashboard
![Screenshot from 2021-05-17 16-32-47](https://user-images.githubusercontent.com/538604/118506482-a388e080-b72d-11eb-9c08-a33fc97e5485.png)

Tested on master-head (5d2b7ac)

**Comment by gaktive** [comment]
This feature isn't fully ready for testing yet so we'll look at this later once things settle down here.

**Comment by kravciak** [comment]
Reopening, I still see 3 different cluster providers for imported rke2 cluster.

I can see registration commands only:
 - for dashboard-imported cluster only in dashboard
 - for ember-imported cluster only in ember (menu->import host)
 

**Dashboard home page: `rke`**

![Screenshot from 2021-06-16 13-26-52](https://user-images.githubusercontent.com/538604/122211138-b0246400-cea6-11eb-9ecb-f0a3914c8128.png)



**Dashboard cluster management: `Imported` for dashboard import and `<empty>` for ember import**

![Screenshot from 2021-06-16 13-26-10](https://user-images.githubusercontent.com/538604/122211162-b74b7200-cea6-11eb-93e8-0b72a3912543.png)

rke version: 1.2.8
rancher: master-head (89b7a91)

**Comment by vincent99** [comment]
Handling imported rke2/k3s is still pending backend and will be addressed in #3338.

**Comment by vincent99** [comment]
We're going with just editing imported goes to Ember for now.

**Comment by kravciak** [comment]
I imported rke cluster on dashboard and ember. They are displayed as `imported` on both.
When I try to edit cluster options are consistent between ember and dashboard.
Works as expected, closing.

Tested on master-head (f33188d)
