### ISSUE TITLE
RKE1 Node Pools not displayed in Cluster Management in Explorer

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3016]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Deploy a rancher server based on `rancher/rancher:master-head 5d2b7ac`
* Provision a Linode RKE cluster from the rancher with two node pools - 1st pool for one node with all roles set and 2nd poll for one node with worker role set (for the rest use default values)
* Wait until the Cluster is reported as Active in Cluster Management in Explorer (and not grayed out in the cluster list)
* In Cluster Management / Explorer click on the Linode Cluster name and switch to Node Pools tab

**Result:**
* The cluster doesn't report any used Node Pools:
![empty_node_pools_list](https://user-images.githubusercontent.com/12828077/118510076-e8fadd00-b730-11eb-999b-b63cce55995b.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher/rancher:master-head 5d2b7ac`
- Installation option (single install/HA): any

**Comment by thehejik** [comment]
Currently on `rancher/rancher:master-head c7f3cce` with RKE1 EC2 cluster the following is shown - looks like the json is not rendered at all. @richard-cox do you think the opened PR https://github.com/rancher/dashboard/pull/3293 will also address this?

![machine_pools](https://user-images.githubusercontent.com/12828077/123614614-cb776380-d804-11eb-8d8b-500cc411774e.png)

**Comment by richard-cox** [comment]
@thehejik Close, #3291 will implement this feature. Hopefully should merge by tomorrow

**Comment by thehejik** [comment]
**Test report:**
Tested on `rancher/rancher master-head e546ffe`

Now RKE1 node pools and nodes itself are displayed - the output seems reasonable. I was also able to scale up node count on EC2 and on Linode within node pools.

* This is how it currently looks on **RKE1 EC2** cluster with one `allroles` pool:
![rke1_node_pools_ec2](https://user-images.githubusercontent.com/12828077/123973725-4d5dbd00-d9bc-11eb-9ef5-fcf201cdec39.png)

* similary on **RKE1 Linode** clustes with three pools each for one role:
![rke1_node_pools_linode](https://user-images.githubusercontent.com/12828077/123974088-a168a180-d9bc-11eb-89cd-78611750db93.png)

Closing.
