### ISSUE TITLE
clicks do not register on embedded windows when a shell/log is active

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3019]
When a shell/log is active and a user is creating/editing an RKE1 (embedded view) cluster through dashboard, clicks don't register near the bottom of the page, which is where the save button is. You can see in the screenshot below the flashing yellow cursor. Clicks/scrolls do not register below this line. The user must close out or minimize the shell in order to continue/save on the embedded page

Repro steps:
* add an RKE1 cluster (i.e. linode) through the dashboard using the embedded view
* wait for cluster to deploy
* open shell on one of the workloads
* go back to cluster management and edit the cluster with shell still open
* user is unable to click save

master-head (5d2b7ac)
<img width="1114" alt="Screen Shot 2021-05-17 at 1 48 21 PM" src="https://user-images.githubusercontent.com/16691014/118555159-32d6c980-b717-11eb-8d39-db0ffe34db5f.png">

**Comment by vincent99** [comment]
@nwmac z-index and/or where the iframe is put into the layout.  The partial-page loading screen mode is also half on top of windowmanager tabs.

**Comment by slickwarren** [comment]
on master-head (d3ad5d3): 
* windows are now organized properly when logs are viewed
* clicks are registering correctly in all windows with logs up or hidden
![Screen Shot 2021-07-20 at 11 15 29 AM](https://user-images.githubusercontent.com/16691014/126374955-bfbce48e-257e-43e6-b490-6039c826893d.png)
