### ISSUE TITLE
Cluster Management - State column doesn't change after editing a cluster

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3021]
Rancher version `v2.6 master-head (07/17/2021)` _5d2b7ac_

When after editing a cluster the state of the cluster change to `Updating` but the Clusters list in the Cluster  Management page doesn't update the State. It's always Active

In Dashboard Home the state is properly reflecting the current state (`Updating`)

![Screen Shot 2021-05-17 at 2 54 12 PM](https://user-images.githubusercontent.com/27659/118561688-3ae73700-b720-11eb-9347-d826d20b26c2.png)

But from Cluster Management it's not

![Screen Shot 2021-05-17 at 2 54 04 PM](https://user-images.githubusercontent.com/27659/118561750-5b16f600-b720-11eb-98e3-2ae1b0c5444f.png)

## Cluster type 

Custom/Windows
RKE1

Amazon EC2
RKE1

**Comment by izaac** [comment]
https://github.com/rancher/dashboard/issues/3021

**Comment by gaktive** [comment]
What Dashboard is reporting is different than Ember, as per https://github.com/rancher/rancher/issues/32891#issuecomment-849979830

The basic gist is that Ember is showing more but that's tied to the API. Will check with @vincent99 about what we can do for Dashboard.

**Comment by gaktive** [comment]
The two pages actually are checking on two separate states based on cluster types: one based on provisioning and the other for its actual health. This would require some backend discussion but the UX needs consideration.

**Comment by vincent99** [comment]
You're looking at the `provisioning.cattle.io.cluster` on the Cluster Management screen, which isn't changing an RKE1 cluster because the edits are made to the corresponding `management.cattle.io.cluster` (which is what the rest of the UI including the home screen shows).

The API will sync the conditions between the two clusters so that they show up in both places.

**Comment by vincent99** [comment]
Syncing was added a couple weeks ago..

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/19/2021)` _d3ad5d3_

I did a pass on a latest master build and this seems to work on both `Cluster Management` and the `Home` (landing) page.
