### ISSUE TITLE
Improve or filter the error when enabling/disabling features that require a Rancher restart

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3026]
Rancher version `v2.6 master-head (05/18/2021)` _55f0bb2_

When disabling or enabling features that require Rancher to restart we display a warning but also the 

`502 Bad Gateway`

Could we filter it to not show it if the user is attempting to change the value of one of these?

![Screen Shot 2021-05-18 at 10 24 01 AM](https://user-images.githubusercontent.com/27659/118697377-1349aa80-b7c4-11eb-9724-d89858d20f66.png)

**Comment by vincent99** [comment]
It would be nicer if the server actually returned ok and then restarted instead of just hanging up on us...

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/08/2021)` _cf5a75f_

There's now a `Waiting for Restart` modal shown when a feature that needs a Rancher restart is switched from the UI

![Screen Shot 2021-07-08 at 2 47 56 PM](https://user-images.githubusercontent.com/27659/124995437-3e01f380-dffc-11eb-9a80-9edb6ee65311.png)


Features switched on/off:

- rke2
- continuous delivery

![Screen Shot 2021-07-08 at 2 50 38 PM](https://user-images.githubusercontent.com/27659/124995485-4fe39680-dffc-11eb-8b8d-a538db543c9d.png)
![Screen Shot 2021-07-08 at 2 47 51 PM](https://user-images.githubusercontent.com/27659/124995487-507c2d00-dffc-11eb-87dc-8fe22fe39f22.png)
