### ISSUE TITLE
RKE1 Provisioning from Cluster Management doesn't show the Machines value after the cluster is active

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3028]
Rancher version `2.6 master-head` _55f0bb2_

I am unable to see the `Machines` we provisioned with RKE1 from `Cluster Explorer -> Cluster Management`

The cluster information shows the Nodes total of the RKE1 cluster I provisioned

![Screen Shot 2021-05-18 at 12 28 16 PM](https://user-images.githubusercontent.com/27659/118711769-d0dc9980-b7d4-11eb-95f8-c9b509907583.png)

![Screen Shot 2021-05-18 at 12 28 34 PM](https://user-images.githubusercontent.com/27659/118711806-d9cd6b00-b7d4-11eb-8781-9de564e3e2b5.png)

**Comment by gaktive** [comment]
@vincent99 would this be expected in the current state of development on the provisioner for 2.6?

**Comment by gaktive** [comment]
This RKE1 status isn't available yet, to be looked at soon.

**Comment by vincent99** [comment]
@richard-cox This goes along with pulling in the rke1 nodes if you want to do it at the same time so I don't step on you.  A [formatter](https://github.com/rancher/dashboard/blob/4dc6c07ff534539f1e0022497bc4d94c83186dfb/config/product/manager.js#L120) produces the progress bar cell.

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/07/2021)` _cf5a75f_

I see the node count on RKE1 clusters now after these get provisioned and on active state.
Also during provisioning state the node count is displayed correctly.


![Screen Shot 2021-07-07 at 3 14 21 PM](https://user-images.githubusercontent.com/27659/124836967-c919b580-df38-11eb-8fd2-603523db019e.png)
