### ISSUE TITLE
Welcome to Rancher header barely visible on Dark theme

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3037]
Rancher version `v2.6 master-head (05/19/2021)` _d8acb21_

- Login to a Rancher server
- In the user preferences set the theme to Dark
- Go back to Cluster Explorer Home
- The H1 is barely visible.

![Screen Shot 2021-05-19 at 1 40 11 PM](https://user-images.githubusercontent.com/27659/118881902-6d23a080-b8a8-11eb-834b-af83be32422f.png)

**Comment by izaac** [comment]
Rancher version: `v2.6 master-head (05/25/2021)` _f90b36e_

So selecting between `Light` and `Dark` themes sets the proper Header contrast.
But with `Auto` I see this, which isn't expected:

![Screen Shot 2021-05-25 at 11 57 22 AM](https://user-images.githubusercontent.com/27659/119553597-a056ab80-bd50-11eb-8ab3-0b3a4807aebc.png)

My OS X has Dark theme enabled but the `Auto` settings are showing a mixed between Dark and Light themes

**Comment by nwmac** [comment]
I can't reproduce this - can you check if you still see this, please

**Comment by izaac** [comment]
@nwmac Sure I will this was tested a few days back I will check on a newer build.

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/02/2021)` _b908330cc_
Auto theme is now also working as expected in the latest Rancher build
The Header is also showing proper contrast depending on the theme applied.

Sample Dark theme to show this is correct (for the original reported issue)

![Screen Shot 2021-06-02 at 9 24 50 AM](https://user-images.githubusercontent.com/27659/120516834-a5d17880-c384-11eb-985c-ff1bbd120e22.png)
