### ISSUE TITLE
UI for OPA gatekeeper - Deployment

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#304]
old ticket: https://github.com/rancher/rancher/issues/25232

Main Epic: https://github.com/rancher/rancher/issues/#23753

UI Need:

UI to deploy/enable OPA similar to Monitoring

**Comment by lvuch** [comment]
https://xd.adobe.com/view/70c6882e-eabe-4ef6-40d7-1d301bb75213-06f7/

**Comment by westlywright** [comment]
@lvuch Will you be adding the mocks for enabling OPA+Gatekeeper?

**Comment by westlywright** [comment]
@lvuch @maggieliu Talked to @tfiduccia offline and came to the conclusion we don't need a new mock for this page. If Gatekeeper is enabled we'll see the views you've already mocked, if not you'll see the following. 
1. A button that does a simplified launch of gatekeeper, default options only.
2. A button that shows the yaml editor allowing the user to customize the gatekeeper spec as well as the tradition save/cancel buttons.

**Comment by lvuch** [comment]
![](https://files.slack.com/files-pri/T02RW4JDH-FUXC751MZ/detail-top-info.png)
@westlywright Attaching for reference of summary at top

**Comment by tfiduccia** [comment]
Fixed
