### ISSUE TITLE
Disabling multi-cluster feature flag makes Rancher unreachable

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#3041]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
On Rancher `master-head` `version d8acb21`
Have a Rancher setup with only a local cluster.
Navigate to dashboard > Global Settings > Feature Flags
Disable multi-cluster-management feature flag

**Result:**
When Rancher restarts, the user is unable to access the setup:
![Screen Shot 2021-05-19 at 4 43 41 PM](https://user-images.githubusercontent.com/57409052/118898589-c3510d80-b8c1-11eb-914e-357ad75a1d96.png)
The user cannot access cluster manager by inputing the URL `https://.../g/clusters`

**Other details that may be helpful:**
Related to: https://github.com/rancher/dashboard/issues/2795

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version d8acb21`
- Installation option (single install/HA): single install

**Comment by vincent99** [comment]
You are not going to be able to access Ember when mcm is off, lots of CRDs are missing in that mode.

But the way the settings that are needed for the login are retrieved don't exist in that case, which breaks Vue login too.  @ibuildthecloud  is adding an alternative which we will switch to when available.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/pull/32798/files/2471f3b858bf7ac82e512dbe073295c13c98f36e..eaa6882d84b772710b06590efa87f0473c65fa15

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version be03c8bd1`
After disabling the multi-cluster feature flag, the UI will be stuck waiting for restart.
![Screen Shot 2021-06-03 at 11 14 41 AM](https://user-images.githubusercontent.com/57409052/120692659-ec92a180-c45c-11eb-886f-09ee1e490b7e.png)
On manual page refresh, the user is logged out. But Rancher is no longer unreachable.
![Screen Shot 2021-06-03 at 11 44 42 AM](https://user-images.githubusercontent.com/57409052/120696236-2bc2f180-c461-11eb-91ee-b7e6d66e0147.png)
When trying to access cluster manager using the side slide or `https://<IP>/g`:
![Screen Shot 2021-06-03 at 11 17 14 AM](https://user-images.githubusercontent.com/57409052/120696096-ff0eda00-c460-11eb-87b9-2dd6437dcf40.png)
When trying to access multi-cluster apps using the side slide or `https://<IP>/dashboard/c/local/mcapps/pages/apps`:
![Screen Shot 2021-06-03 at 11 17 04 AM](https://user-images.githubusercontent.com/57409052/120696099-ffa77080-c460-11eb-9a6a-e287b414c703.png)
Every time a user tries to access cluster manager or multi-cluster apps, the user is logged out on page refresh.
@vincent99 Is this expected behavior?

**Comment by vincent99** [comment]
If you turn it off MCM then the APIs and such for ember are missing.  There should not be links to it, and going to it isn't going to work.

**Comment by aaronRancher** [comment]
Closing as a duplicate of: https://github.com/rancher/rancher/issues/32721
