### ISSUE TITLE
UI for OPA gatekeeper - Constraints

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#305]
Old ticket: rancher/rancher#25232

Main Epic: https://github.com/rancher/rancher/issues/#23753

UI Need:

UI to edit/import contraints template
UI to indicate violation on existing resources based on enabled constraints

**Comment by lvuch** [comment]
https://xd.adobe.com/view/70c6882e-eabe-4ef6-40d7-1d301bb75213-06f7/

**Comment by codyrancher** [comment]
@tfiduccia @vincent99 
I spoke with @lvuch already and I wanted to get feedback on two things.

1. The Constraint Edit as Form page needed to change to better reflect the shape of the yaml. Here's what I made, but please feel free to change any aspect of it. Just let me know what could be better.

![Screen Shot 2020-02-25 at 2 57 28 PM](https://user-images.githubusercontent.com/55104481/75297017-0e2dc380-57ec-11ea-8517-57cc207cde8e.png)
![Screen Shot 2020-02-25 at 2 59 02 PM](https://user-images.githubusercontent.com/55104481/75297022-10901d80-57ec-11ea-9845-fc48f0b50b9d.png)

2. The existing Edit as Yaml page has buttons which conflict with the placement of the "Edit as Form" button that's in the mocks. How do we want to change the existing Edit as Yaml page or the mock to account for this? Lauren suggested that we move the conflicting buttons to match what's in the mock, I was concerned that there may be another mock which shows the existing position.
![Screen Shot 2020-02-25 at 2 59 21 PM](https://user-images.githubusercontent.com/55104481/75297229-87c5b180-57ec-11ea-9854-955d398a32b5.png)

**Comment by tfiduccia** [comment]
Fixed - new issues will go into new bug
