### ISSUE TITLE
Review Icons and leverage new SUSE icon set where appropriate

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3055]
- All logo, vendor, brand icons currently used will not be supported by eos (as it is the policy). We will use svgs that we upload to our icons repo and generate from there.
- We will use eos icons as a resource to pull standard icons as svg (we will generate, maintain and host icons/icon font ourselves)

**Comment by lvuch** [comment]
[icon-translation.pdf](https://github.com/rancher/dashboard/files/6523884/icon-translation.pdf)

**Comment by lvuch** [comment]
[svg exports for icons.zip](https://github.com/rancher/dashboard/files/6524912/svg.exports.for.icons.zip)

**Comment by lvuch** [comment]
sidenav icons: https://xd.adobe.com/view/185235c2-4385-4830-af3b-1e147c4d3b75-4d01/

**Comment by gaktive** [comment]
This may be fielded by work done in https://github.com/rancher/icons/pull/34
@nwmac to review and then determine if we still need this ticket if another exists.

**Comment by nwmac** [comment]
NA
