### ISSUE TITLE
Projects changes- List/Detail & Create/Edit

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#306]
Renaming Projects to Namespace Groups.

Basic Requirements:
Add/edit - 
1.  Name/description
2.  Ability to add a namespace to group
3.  Ability to move a namespace from a different group into group
4.  RBAC (Add/remove users & user groups)

**Comment by tfiduccia** [comment]
Rename back to projects

**Comment by lvuch** [comment]
https://xd.adobe.com/view/a24a1607-b44f-4c7e-4d96-2ac7fcdef091-d47b/

**Comment by tfiduccia** [comment]
We need to not have Projects & Namespaces separate anymore.  So let modify the current Namespace pages to 
1.  Include a Project header that you can sort on.  
2.  Change Create button to two separate buttons, Create namespace & create Project.  
3.  Add Select Project field to Add/Edit Namespace, with the default going to "None".
4.  Still need to Add RBAC to Namespace as well

So a mix of these two:
https://xd.adobe.com/view/a24a1607-b44f-4c7e-4d96-2ac7fcdef091-d47b/
https://xd.adobe.com/view/da2be087-8252-446d-64a0-6f440ef74779-ac1a/

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/dashboard/issues/567
