### ISSUE TITLE
Light color issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#307]
- [x] Dimmed buttons wrong color
![image](https://user-images.githubusercontent.com/11514927/74370210-f427c600-4d93-11ea-9027-602ea4bb20fb.png)

- [x] Drop-down color is wrong
![image](https://user-images.githubusercontent.com/11514927/74370244-ff7af180-4d93-11ea-93b7-d0ba36f99afa.png)

- [x] Mouse-over controls makes box dissapear
![image](https://user-images.githubusercontent.com/11514927/74370291-11f52b00-4d94-11ea-88dd-e81e00a16475.png)

- [x] Header needs to be blue (both light and dark)
![image](https://user-images.githubusercontent.com/11514927/74370431-55e83000-4d94-11ea-9135-917be0dde52d.png)

- [x] Shouldn't have background color for left menu top level nav items (both light and dark)
![image](https://user-images.githubusercontent.com/11514927/74370510-70baa480-4d94-11ea-9c7a-888a9aee25cb.png)

- [x] Active start buttons should be blue color (both light and dark)
![image](https://user-images.githubusercontent.com/11514927/74370748-d9098600-4d94-11ea-8faf-80a35b537b43.png)

- [x] In tabbed views, input background same as tab background
![image](https://user-images.githubusercontent.com/11514927/74370845-0bb37e80-4d95-11ea-8f97-e1df72424c4f.png)

- [x] On Routers page, the box around a rule is missing
![image](https://user-images.githubusercontent.com/11514927/74371033-56cd9180-4d95-11ea-9e78-6afaee4491a6.png)

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/311/

**Comment by tfiduccia** [comment]
Date - 2/20
Verified fixed
