### ISSUE TITLE
Port Rotate Certificates action from Ember UI for a cluster

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3080]
Check Cluster Manager UI - for some clusters, you can rotate secrets.

You can determine if the action is applicable from the `mgmt.actions` field of the `cluster.provisioning.cattle.io` model.

![image](https://user-images.githubusercontent.com/1955897/119536284-d01da780-bd80-11eb-86a1-cba51a62d4f1.png)

![image](https://user-images.githubusercontent.com/1955897/119536371-ecb9df80-bd80-11eb-935f-6a882c162aaa.png)

You'll need to call the old Norman API for this.

**Comment by kravciak** [comment]
I created DO-rke1 and custom clusters in emberUI, then switched to Dashboard:

Dashboard -> Cluster Management -> cluster menu (`...`)

- `Rotate Certificates` button is `not` visible in the menu
- `Rotate encryption keys` button is visible, even though secrets encryption is not enabled
- When I enable secrets encryption I can see `Rotate Certificates` button

It seems that logic for button visibility is swapped between certificate / encryption keys.
I tested the same few days ago (4d18400) and it was working fine.

![Screenshot from 2021-06-23 15-09-54](https://user-images.githubusercontent.com/538604/123102223-1e33d280-d435-11eb-92ca-2739583cf75d.png)

Tested on master-head (d44698d)

**Comment by kravciak** [comment]
Tested on rke1 DO infra provider cluster with 1 master 1 etcd 1 worker nodes and run on all nodes:

```
# Commands to get cert information
for file in $(find . -type f -name "*.pem"); do printf "$(md5sum $file)\n\n"; done | grep -v ^$
for i in `ls *.pem|grep -v key`; do echo $i; openssl x509 -startdate -enddate -noout -in $i; done
```

- expiration date is 10 years from now
- expiration date is updated after cert rotation
- calls are going to v3 api

Rotate single certificate:
 - etcd: modified kube-etcd cert on etcd node
 - kubelet: modified kube-node cert on all nodes
 - kube-apiserver: modified kube-apiserver on control node
 - kube-proxy: modified kube-proxy on all nodes
 - kube-scheduler: modified kube-scheduler on control node
 - kube-control-manager: modified kube-control-manager on control node

Rotate all certificates: rotated all expecpt kube-ca.pem (requestheads / tokens ignored)
