### ISSUE TITLE
Port 'Save as RKE Template' action from Ember

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3081]
Check Cluster Manager UI - for some clusters, you can save as an RKE template - the mechanism for determining this is via the actions on a cluster - this does not work yet, so we'll need to come back to that, but we can still implement the feature.

![image](https://user-images.githubusercontent.com/1955897/119536567-21c63200-bd81-11eb-8a6d-6fa6bbb9a644.png)

**Comment by aaronRancher** [comment]
On Rancher `master-head` `version 44bb5b4`

### From Ember UI:
 `Save As RKE Template` is a v3 api call from `/v3/clusters/<cluster_ID>?action=saveAsTemplate`
Selecting `Save As RKE Template` will bring up this window:
![Screen Shot 2021-07-15 at 3 51 10 PM](https://user-images.githubusercontent.com/57409052/125867620-2488e6e8-e463-49db-879d-679117f51087.png)
After saving as RKE template, the user is redirected to a view of the new template:
![Screen Shot 2021-07-15 at 3 36 41 PM](https://user-images.githubusercontent.com/57409052/125866504-a3cb1c07-87f3-431a-9e38-5810e77ef744.png)

### From Dashboard UI:
`Save As RKE Template` is available in Cluster Management list or Cluster Management cluster view:
![Screen Shot 2021-07-15 at 3 33 41 PM](https://user-images.githubusercontent.com/57409052/125866242-80172951-4711-4b3a-aacb-7d0098aa9810.png)
![Screen Shot 2021-07-15 at 3 33 18 PM](https://user-images.githubusercontent.com/57409052/125866281-1ffb5674-ffa0-4944-b295-af1c10ab8ca9.png)
`Save As RKE Template` from Dashboard UI is also a v3 api call from `/v3/clusters/<cluster_ID>?action=saveAsTemplate`
Selecting `Save As RKE Template` will bring up this window:
![Screen Shot 2021-07-15 at 3 52 37 PM](https://user-images.githubusercontent.com/57409052/125867754-6948e2c2-43b8-404e-b86c-ab9a54e370fc.png)
The message is slightly different from Ember UI. Missing the line: `This cannot be undone`
After saving as RKE template, the user is redirected to the list of RKE templates:
![Screen Shot 2021-07-15 at 3 20 52 PM](https://user-images.githubusercontent.com/57409052/125865180-d2b9b268-54ea-4965-b1d3-5f1704f09c5a.png)

**Comment by aaronRancher** [comment]
`Save as RKE Template` is functionally available in dashboard. Will track differences in UI message here: https://github.com/rancher/dashboard/issues/3492
