### ISSUE TITLE
SSH User input box is not available

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3084]
When I create DO cluster I can set ssh username, it's even filled automatically when selecting rancherOS.
I can't set this value on dashboard.

Tested on master-head (744c233)

**Ember UI:**
![Screenshot from 2021-05-25 17-09-41](https://user-images.githubusercontent.com/538604/119540253-88e9e380-bd8d-11eb-84af-893b8194d25f.png)

**Dashboard:**
![Screenshot from 2021-05-25 19-13-43](https://user-images.githubusercontent.com/538604/119540267-8e472e00-bd8d-11eb-914e-eeaf34858c92.png)

**Comment by vincent99** [comment]
Ros should probably be removed entirely since it's deprecated and provisioning v2 doesn't seem to work in it.

For every other supported OS the default user is correct AFAIK so all you can do with this option is break it.

**Comment by kravciak** [comment]
I still see rancherOS 1.5.8 on the list, will retry tomorrow.

**Comment by vincent99** [comment]
Fixed (removed) in #3208

**Comment by kravciak** [comment]
RancerOS removed in master-head 66c31dd
Based on comments above missing username input box is expected, closing.
