### ISSUE TITLE
rke2 cluster etcd snapshot issues

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3091]
On master-head 744c233

1. from cluster management --> cluster --> Snapshots --> It should be **"Snapshot Now"** 
<img width="500" alt="Screen Shot 2021-05-25 at 2 27 42 PM" src="https://user-images.githubusercontent.com/38144301/119570866-7c519500-bd65-11eb-92e8-a5367b99c92b.png">
2. While the snapshot is creating, it should be  **"Snapshot Creating"**
<img width="300" alt="Screen Shot 2021-05-25 at 2 29 01 PM" src="https://user-images.githubusercontent.com/38144301/119571043-bcb11300-bd65-11eb-8ae1-da712b3d0919.png">

**Comment by gaktive** [comment]
For reference, Snapshow and Shapshot were the typos :)

**Comment by anupama2501** [comment]
Verified on master-head d44698d

Typos are resolved and the strings on the buttons are displayed correctly `Snapshot Now` and ` Snapshot Creating`
