### ISSUE TITLE
Pre-fill resource limits of Create Namespace UI under Projects that has these values

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3104]
Rancher version `2.6 master-head (05/26/2021)` _629146a_
Related: https://github.com/rancher/dashboard/issues/2500

When we create a namespace under a Project that has Resource Limits quotas and we click `Create Namespace` on that project the UI should pre-fill/Inherit the Resource Limit values of the Project.

This is the `Cluster Manager` (Ember) behavior. 

Expectation is to match the Ember behavior.

Sample screenshots after clicking `Create Namespace` on Ember vs Vue where the Project has Resource Limits set.

![Screen Shot 2021-05-26 at 11 10 04 AM](https://user-images.githubusercontent.com/27659/119710265-03107b80-be13-11eb-80a7-b5bf25e27e61.png)

![Screen Shot 2021-05-26 at 11 09 47 AM](https://user-images.githubusercontent.com/27659/119710283-073c9900-be13-11eb-9a4e-bd99486e8f64.png)

**Comment by gaktive** [comment]
Need to determine if the pre-fill values in Ember are arbitrary or if they're being pulled from something. @codyrancher, do you know how those fields were populated?

**Comment by gaktive** [comment]
The values set in Ember were arbitrary. For the Dashboard experience, we got feedback on another feature (Workloads) where prepopulation of limits was set and it wasn't suitable.

For now, this is working as designed. The "e.g" references in the fields should indicate what the user can do.

**Comment by codyrancher** [comment]
We just realized that the project was providing these values so I'm reopening.

**Comment by izaac** [comment]
Rancher version `v2.6 master-head (06/09/2021)` _97ca638_

This is now working but there's a difference at the API level, see below.


Values are different from namespaces created on Ember include unit suffixes (`m`, `Mi`).

```json
"containerDefaultResourceLimit": {

    "limitsCpu": "1000m",
    "limitsMemory": "500Mi",
    "requestsCpu": "2000m",
    "requestsMemory": "1000Mi"

}
```


And namespace created from Dashboard:

```json
"containerDefaultResourceLimit": {

    "limitsCpu": "2000",
    "limitsMemory": "1000",
    "requestsCpu": "1000",
    "requestsMemory": "500"

},
```

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/24/2021)` _c7f3cce_

Validated the namespaces inherit the values and the units are also applied.
