### ISSUE TITLE
Embedded Manager's dark mode clashes with Dashboard's dark mode

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3112]
- One of the great things about the embedding is how it meshes together
- However In dark mode the Dashboard's dark dark navy clashes with Manager's washed out black
- ![image](https://user-images.githubusercontent.com/18697775/119809650-3fa8a980-bedd-11eb-856d-dbd8a4a49a4f.png)
- vs
- ![image](https://user-images.githubusercontent.com/18697775/119810051-9615e800-bedd-11eb-9c0c-60926a70547d.png)
- (raised as part of https://github.com/rancher/dashboard/pull/3031#pullrequestreview-669200556)

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head c1151f6`

The Legacy/Catalog page from summary now looks better:
![dark_catalog_legacy](https://user-images.githubusercontent.com/12828077/124097280-b7796f00-da5b-11eb-84a5-89d0d3f997f4.png)

But

* Seems that even original Ember Light theme has been changed - now the colours are a bit more pastel like but some button icons were not adapted (same for dark theme - see next point + screenshot)
* The Dark background in iframe is now closer to the dark theme in Dashboard but I see some glitches now - the same stands for Light theme.
![dark](https://user-images.githubusercontent.com/12828077/124096223-ad0aa580-da5a-11eb-93d8-72ba117cca85.png)

Reopening

**Comment by thehejik** [comment]
The glitches are tracked in https://github.com/rancher/rancher/issues/33449 and https://github.com/rancher/rancher/issues/33450

This can be closed then.
