### ISSUE TITLE
Enhancement: Users & authentication, global settings can be moved to Global APPS in new top-level navigation 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3114]
Cluster explorer --> hamburger menu --> configuration

In the new top level navigation, we have Users and authentication, global settings are added under configuration. 
Users & authentication, global settings can be moved to Global APPS rather than under Configuration as they are Global APPS similar to what we have on 2.5.x ?

<img width="254" alt="Screen Shot 2021-05-26 at 11 47 45 AM" src="https://user-images.githubusercontent.com/38144301/119849802-c9e31480-bec1-11eb-8796-0c05a013959a.png">

Rancher v2.5.8 dashboard:
<img width="298" alt="Screen Shot 2021-05-27 at 8 06 56 AM" src="https://user-images.githubusercontent.com/38144301/119850630-92c13300-bec2-11eb-8986-85fc98be7aee.png">

Reference ticket: https://github.com/rancher/dashboard/issues/2499

**Comment by gaktive** [comment]
Working as designed, we'll leave it as is.
