### ISSUE TITLE
Enable editing of PVCs

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3115]
- Editing PVCs is currently disabled via `configureType(PVC, { isEditable: false });`
- In some cases it's possible to edit some of the PVC detail
  - Labels & annotations
  - The size can be changed if the associated storage class is tagged with `allowVolumeExpansion` (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims)
- We should enable editing and restrict edits to these parts

**Comment by Josh-Diamond** [comment]
Ticket #3115 - Test Results

With Docker and EKS Hosted cluster:

Reproduced on v2.6.3:
1. Fresh install of rancher v2.6.3
2. Create a cluster
3. Create a PV
4. Create a PVC and bind it to PV in step 3
5. Reproduced - PVC is not editable, no labels + annotations in UI either

View Config (Edit Config not available):
<img width="1307" alt="5115 - reprod-2" src="https://user-images.githubusercontent.com/46494969/157776300-0b9a6b63-9b10-47a1-8167-afd135f50620.png">

View Config is read-only:
<img width="1321" alt="5115 - Reproduced" src="https://user-images.githubusercontent.com/46494969/157776410-a9ee72c8-fb71-497f-b078-c2ad6f08320a.png">



Verified on v2.6-bab14a306b5144ff8f576dc625284ab5c38d0c27-head:
1. Fresh install of rancher v2.6-head
2. Create a cluster
3. Create a PV
4. Create a PVC and bind it to PV in step 3
5. Verified - PVC is editable, labels + annotations appear in UI
7. Also, Create a storage class, and `enable` “Allow Volume Expansion”
8. Create a new PVC for storage class
9. Verified - PVC storage is editable

`Step #5` - Verified:
<img width="1306" alt="Screen Shot 2022-03-10 at 4 57 42 PM" src="https://user-images.githubusercontent.com/46494969/157776470-6dd43ce2-250d-46f0-8d16-21a5c7ca772b.png">

<img width="212" alt="5115 - verified-1" src="https://user-images.githubusercontent.com/46494969/157776495-8afff0c6-f10b-439f-8976-c38de50c7e49.png">

`Step #9` - Verified:
<img width="1314" alt="5115-verified-2" src="https://user-images.githubusercontent.com/46494969/157776569-9af10a50-a535-47b2-88a1-895aa487cc91.png">
