### ISSUE TITLE
Issues while creating navlinks and accessing the created navlinks

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3116]
Rancher Version: master-head ba100bb

 **Multiple issues while creating navlinks are addressed in this ticket:**

**1. Navlinks in a cluster is not showing on the left hand navigation under more resources** [select all namespaces]
 --> Rancher. 

If we search for the navlinks from cluster search option and create a custom link from that page, it can then be seen under the cluster More Resources --> Rancher. 
 <img width="100" alt="Screen Shot 2021-05-27 at 10 31 36 AM" src="https://user-images.githubusercontent.com/38144301/119870921-bdb58200-bed6-11eb-8230-4dd2cd017b94.png">
Can this be made available under Rancher --> Resources even if the navlinks were not created as in the above step?

**2. Create multiple navlinks using yaml editor, navlinks are not shown up on the navlinks screen.**

<img width="200" alt="Screen Shot 2021-05-27 at 10 34 16 AM" src="https://user-images.githubusercontent.com/38144301/119871489-564c0200-bed7-11eb-8801-6bc494226906.png">

Other console logs:
<img width="300" alt="Screen Shot 2021-06-01 at 12 07 38 PM" src="https://user-images.githubusercontent.com/38144301/120377440-f8059180-c2d1-11eb-8037-6ab8cef1ff48.png">

**3. Create navlinks without toURL and no resource is seen for this new navlink in navigation on the left**

> 1. Create a navlink with fields: `name` and `toURL`. Once created the navigation link is seen created in the explore cluster below more resources.
> 2. Create a navlink with fields: `name` but no `toURL`. Once we click on create, the navigation on the left is completely wiped off and all the other resources like workload, Apps & Marketplace, Service Discovery etc., everything on the left navigation are not seen.
> 3. Create a new navlink with fields: `name` and `toURL`. Once we click on create, the navigation links are not seen, even the navlink successfully created and displayed in step1.

**Reference screenshot with console errors:**

<img width="200" alt="Screen Shot 2021-05-27 at 10 48 20 AM" src="https://user-images.githubusercontent.com/38144301/119873184-1ede5500-bed9-11eb-874a-50781dcbd4a3.png">

https://user-images.githubusercontent.com/38144301/119873291-3f0e1400-bed9-11eb-8871-5b5d0da48b7c.mov

Reference issue: https://github.com/rancher/dashboard/issues/2835

**Comment by anupama2501** [comment]
@vincent99  Quick question: Can the navlinks be made available on the left hand navigation outside of More resources --> Rancher to increase visibility?

**Comment by vincent99** [comment]
1) No, this is how the left nav works in general; Only types where there are 1 or more resources to see are listed (otherwise there are literally hundreds of types).  If you want to find a type where you don't have any yet you have to use the cmd-k/search in the top-right.

2) Something's probably wrong with what you created or how we're handling it, but I can't tell you anything with no detail of what you created...  What's the YAML?

3) Again, specific YAML of what you're posting.  A resource missing both toURL and toService is invalid, but the UI should not blow up on it..

**Comment by anupama2501** [comment]
@vincent99:

-  Only the field name is entered and provided **no** toURL. When I click on save in this case, previously created navlinks are not shown as well as the current one.
- If we refresh the UI page then everything on the left navigation is empty with the same console errors as attached in the above comment

[au-navlinks.txt](https://github.com/rancher/dashboard/files/6624517/au-navlinks.txt)

Response in the network tab shows no error:
<img width="300" alt="Screen Shot 2021-06-09 at 7 33 13 AM" src="https://user-images.githubusercontent.com/38144301/121374948-2cda9f80-c8f5-11eb-8416-10d02d755a0c.png">

**Comment by vincent99** [comment]
Yeah that's a totally invalid navlink, but shouldn't kill the page; fixed (it will just be ignored since there's nothing useful to show without a link...)

**Comment by anupama2501** [comment]
On master-head d44698d

**Issue2**:
Verified by creating multiple navlinks and the navlinks work fine and all the navlinks are seen on the left hand navigation.

 
#### Reopening the ticket for **Issue3** which is still seen
1. Created a navlinks with the name=`test1`, toURL=`https://rancher.com/`
2. Create two more navlinks with the values - name and toURL provided in the yaml file.
3. Verified navlinks are seen on the left hand navigation of the cluster under More resources --> Rancher --> Navlinks.
4. Create another navlink with the name=`nolink` _only_.
4. Navlinks page looks empty - all the previously created navlinks are gone on the navlinks page and the following is the error seen in the console logs:
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'toService' of undefined
    at fn (ui.cattle.io.navlink.vue?0fb6:3)
    at r (vue.runtime.esm.js:2590)
    at f.Ee [as _t] (vue.runtime.esm.js:2686)
    at fn (ResourceTable.vue?7bd1:3)
    at r (vue.runtime.esm.js:2590)
    at f.Ee [as _t] (vue.runtime.esm.js:2686)
    at index.vue?1460:3
    at f.Se [as _l] (vue.runtime.esm.js:2630)
    at index.vue?1460:1
    at f.Se [as _l] (vue.runtime.esm.js:2630)
```

yaml file for the navlink that is causing the issue:
[nolink.txt](https://github.com/rancher/dashboard/files/6705348/nolink.txt)


Screenshot reference:
<img width="400" alt="Screen Shot 2021-06-23 at 4 40 44 PM" src="https://user-images.githubusercontent.com/38144301/123181244-ca7bb600-d441-11eb-8272-61aba9d29d79.png">

**Comment by anupama2501** [comment]
Verified on the rancher master-head e756276

1. Create two navlinks with the fields name and toURL provided.
2. Navlinks are shown on the left hand navigation as well as on the navlinks page.
3. Created another navlink with only name field but no toURL or toService values provided.
4. Navlinks page has all the links listed and not breaking existing navlinks page.
5. No errors are seen in the console logs as well.
<img width="400" alt="Screen Shot 2021-06-24 at 9 14 05 AM" src="https://user-images.githubusercontent.com/38144301/123297588-8c77a400-d4cc-11eb-9db5-e4b540daa7e9.png">
