### ISSUE TITLE
Alibaba Embedding is missing fields

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3123]
![image](https://user-images.githubusercontent.com/1955897/119984982-fbd7a200-bfb9-11eb-8680-a4c63e407c68.png)

Appears like this when embedded:

![image](https://user-images.githubusercontent.com/1955897/119985012-03974680-bfba-11eb-9950-15afd6acb9cd.png)

Looks like the provider name is incorrect, so we're not actually loading the right page

**Comment by vincent99** [comment]
There is a _lot_ of fairly confusing mapping of the resource fields to the provider name to the component name to render that to the query param to put in to get that in Ember, so I would not be surprised if some of that was emulated wrong in vue.

**Comment by nwmac** [comment]
Yeah . I've got a PR up for this - it's done to differences in the driver names between the two UIs.

**Comment by thehejik** [comment]
It seems to be fixed in `rancher/rancher:master-head 562737f`. But as I don't have valid alibaba credentials it won't let me move to next steps. Close.

![alibaba_explorer](https://user-images.githubusercontent.com/12828077/120490415-ae43a680-c3b8-11eb-8c7b-128b6b6f421b.png)
