### ISSUE TITLE
Add support for cluster icons for drivers that are not built in

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3124]
For external drivers, the Ember UI injects a stylesheet from the driver which contains a class to change the icon to a custom one, e.g.

```
.machine-driver.aliyun {
  background-image: url('aliyunkcs.svg');
  background-size: 60px 60px;
}
```

this is loaded thus in the Ember UI:

```
        const driverSchema = get(this, 'globalStore').getById('schema', configName.toLowerCase());

        if ( uiUrl ) {
          const cssUrl = proxifyUrl(uiUrl.replace(/\.js$/, '.css'), get(this, 'app.proxyEndpoint'));

          loadStylesheet(cssUrl, `driver-ui-css-${ name }`);
        }
```

**Comment by vincent99** [comment]
Can we just bundle in the images for all the drivers that exist in a default install, and not have dynamic loading for now?  The mechanism for loading external plugins is going to be very different when we get them in Vue.  And loading arbitrary CSS meant for Ember into sounds error-prone.

**Comment by nwmac** [comment]
Yeah we can.

**Comment by gaktive** [comment]
Internal reference: SURE-4065. We are getting reports now from people upgrading from 2.5.x to 2.6.x running into this.

**Comment by sowmyav27** [comment]
**On 2.6.3**
Using details mentioned [here](https://github.com/rancher/dashboard/pull/5135#issue-1139928667)
<img width="749" alt="Screen Shot 2022-02-21 at 11 35 12 AM" src="https://user-images.githubusercontent.com/26032343/155016800-3e721b1d-a114-458b-b377-79a7ecfde40f.png">

**On 2.6-head commit id: `d4089da`**
<img width="735" alt="Screen Shot 2022-02-21 at 11 35 16 AM" src="https://user-images.githubusercontent.com/26032343/155016806-f9bc294d-5c97-4aae-b694-3ca4632e1857.png">
