### ISSUE TITLE
User unable to add `Machine Pool` -> unable to use node provisioners/drivers

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3126]
<img width="642" alt="Screen Shot 2021-05-28 at 8 31 53 AM" src="https://user-images.githubusercontent.com/16691014/120008053-6d4e2b00-bf8f-11eb-98d8-7a4b7a57b377.png">

repro instructions: 

* go to `cluster management`
* add rke2 cluster (I used DO)
* add cloud credentials

Result: Machine pool doesn't allow addition of any pools 
also, should add 1st pool for user

rancher version: master-head (62aef76)

**Comment by vincent99** [comment]
Another API group changed, provisioning.cattle.io -> rke-machine-config.cattle.io.

**Comment by slickwarren** [comment]
after an `empty cache and hard reload` on master-head(8cdbffe), I am able to provision rke2 clusters again. Tested with:
* rke2 DO provisioner -- pass
  * single node -- pass
  * multi node -- pass
  * removal/addition of node pools -- pass
* rke2 EC2 provisioner -- pass
