### ISSUE TITLE
Custom navlinks - custom roles to view/create navlinks enabled for a cluster member is not showing the navlinks option if logged as that user

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3135]
On master-d7528a261111d2ea2129a8b1547fd22974fbc67c-head
- Create a role from Users and Authentication --> Roles --> Cluster --> create a custom role with navlinks and add all the verbs 
Ref screenshot:
<img width="1562" alt="Screen Shot 2021-06-01 at 8 41 35 AM" src="https://user-images.githubusercontent.com/38144301/120352045-3e002c80-c2b5-11eb-91d3-2de19496f74d.png">

- Create a standard user from Users and Authentication --> Users --> create user1 with standard user permissions

- Create a cluster as an admin and once the cluster is active from ember UI --> cluster --> members --> add the user1 with the roles created in step1 and also add the user as cluster member

- Login as user1 and verify from the cluster --> navlinks are not showing up:
<img width="235" alt="Screen Shot 2021-06-01 at 8 48 40 AM" src="https://user-images.githubusercontent.com/38144301/120352999-2ecdae80-c2b6-11eb-8cfc-eb5d42980931.png">

**Comment by vincent99** [comment]
The group`ui.cattle.io.navlinks` does not exist so this role grants access to nothing.  The API group is `ui.cattle.io`, and the resource `navlinks` (or `*` if you want, since that's the only type in the group right now).

**Comment by anupama2501** [comment]
Verified on master-head 3d465ee

1. Create a node driver rke2 cluster with 1 node all roles
2. Create 2 navlinks as admin 
3. From global --> security --> roles on ember UI, create a cluster role with API group selected as ui.cattle.io and resource navlinks with the verbs create, delete, get, list
4. Created a standard user1 and added the user to the cluster as a member with the above role
5. Logged in as user1 and verified the navlinks created as admin are accessible to the user1.
