### ISSUE TITLE
Auth providers - can't access property error when Navigating to enable an auth 

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3137]
Rancher version: `2.6 master-head (06/01/2021)` _5d49b92_

```
TypeError: can't access property "enabled", e.model is null
    r oidc.vue:1
    VueJS 13
    e NuxtJS
    d runtime.js:45
    _invoke runtime.js:274
    e runtime.js:97
    Babel 6
    A app.3569e512d87a5420756a.js:2
    NuxtJS 2
    VueJS 30
    r index.vue:1
    VueJS 13
    e NuxtJS
    d runtime.js:45
    _invoke runtime.js:274
vue.runtime.esm.js:1888:12
```

![Screen Shot 2021-06-01 at 10 07 39 AM](https://user-images.githubusercontent.com/27659/120363638-39417580-c2c1-11eb-9b5d-9e52ce8b87bb.png)

Workaround: Refresh the browser

**Comment by izaac** [comment]
Rancher version `2.6 master-head (06/03/2021)` _be03c8bd1_

I am now getting a 404 error from the API the first time I navigate to any Auth Provider page:

`GET `/v1/%7B%20MANAGEMENT.SETTING%20%7D/server-url``

Just Login for the first time as Local admin.
Navigate straight to `Users & Authentication -> Auth Provider -> <Auth Provider>` (I checked with keycloak OIDC and keycloak SAML)

**Comment by richard-cox** [comment]
> `GET /v1/%7B%20MANAGEMENT.SETTING%20%7D/server-url`

This is a clanger that's been in there for a long time. It was never spotted as it was part of a `management/find`... and we always had server-url so the url was never used. Now, as part of #3160 i don't think we have that setting so the url is used

**Comment by izaac** [comment]
Rancher version `2.6 master-head (06/07/2021)` _b2f8824_ 
Unable to reproduce on a newer build.
