### ISSUE TITLE
Rancher version is shown as unknown, works on Cluster Manager (Ember)

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3138]
Rancher version: `2.6 master-head (06/01/2021)` _5d49b92_

I was expecting the Rancher version or short commit id but it's displayed as `unknown`

![Screen Shot 2021-06-01 at 10 11 14 AM](https://user-images.githubusercontent.com/27659/120364136-ba007180-c2c1-11eb-9f4c-7bcd2461dbac.png)
![Screen Shot 2021-06-01 at 10 11 00 AM](https://user-images.githubusercontent.com/27659/120364139-ba990800-c2c1-11eb-9a88-97793e516e9c.png)

**Comment by richard-cox** [comment]
Ah, hadn't spotted this one, there was a dupe #3160 that I thought was first and have now processed.
