### ISSUE TITLE
User is not prompted to change password when `mustChangePassword` is enabled

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3143]
- create/edit a user and set `Ask user to change their password on first login`
  - user gains mustChangePassword: true
- log out and then log in as changed user
- user is logged straight in and not prompted to change password
  - logging in via manager shows prompt

This was working at one point - https://github.com/rancher/dashboard/issues/2524

**Comment by kravciak** [comment]
Reproduced on e756276, fix works fine on master-head (cf5a75f)
