### ISSUE TITLE
Provide access to Cluster Registration Command for RKE Cluster (from existing nodes)

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3145]
In Cluster Manager, after provisioning an RKE1 Cluster from existing nodes, it is possible to see the Cluster Registration Command, e.g.

![image](https://user-images.githubusercontent.com/1955897/120471222-5dbe5000-c39c-11eb-8e2c-cec330832137.png)

You can't get this command from the Dashboard UI - we should add this.

**Comment by nwmac** [comment]
Note: You do get the registration commands for an imported cluster

**Comment by catastrophe-brandon** [comment]
As of commit `21ab02c` I am able to access the import commands in the dashboard UI. Here's what I did:

1. Docker install Rancher
2. Set up the admin password and log in
3. Go into Cluster Management
4. Click Create
5. On the next page set the slider to RKE1
6. Click "Create Custom"
7. Provide a cluster name, click Next

Once the user arrives on the Cluster Options page, they can check/uncheck the various Node options and make changes. The provided import command is automagically updated as the values are changed.

**Comment by catastrophe-brandon** [comment]
For a custom RKE2 cluster the input validation seems to work slightly different from an RKE1.

Specifically, the Node Public IP field has some validation performed for an RKE1 cluster.

![Screen Shot 2021-07-28 at 3.45.46 PM.png](https://zube.io/files/rancher/5a0fc651b76d058e4ad95a321cfa7e0a-screen-shot-2021-07-28-at-3-45-46-pm.png)

However, for a custom RKE2 the UI doesn't complain if I enter bad input:
![Screen Shot 2021-07-28 at 3.46.25 PM.png](https://zube.io/files/rancher/d6c2578ab94bade286fbbd2394ef8f48-screen-shot-2021-07-28-at-3-46-25-pm.png)

Should this be fixed here, or in a new issue?

**Comment by catastrophe-brandon** [comment]
Closing this issue; creating a new issue for the input validation differences.
