### ISSUE TITLE
Apps & Marketplace pseudo respects project/namespace filter

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3152]
- Apply a project/namespace filter
- Expand `Apps & Marketplace` and resources shown and their counts respect the filter
- Click into any resource in `Apps & Marketplace` and filtering is lost (whilst still applied everywhere else

Feels like filter should always apply to items embedded in side nav... or we ensure where they shouldn't they wholly don't and are visually different

**Comment by bashofmann** [comment]
The current behaviour is actually really confusing. Example:

You start in the Cluster Explorer:

![Bildschirmfoto 2021-07-08 um 14 16 07](https://user-images.githubusercontent.com/243056/124920123-49065500-dff7-11eb-9f56-7826863c731a.png)

You select a namespace:

![Bildschirmfoto 2021-07-08 um 14 16 16](https://user-images.githubusercontent.com/243056/124920163-54f21700-dff7-11eb-92c8-9bcd669e3bf6.png)

The Namespace filter is applied to the left menu:

![Bildschirmfoto 2021-07-08 um 14 19 21](https://user-images.githubusercontent.com/243056/124920335-836ff200-dff7-11eb-9de9-4e9fbdbd4425.png)

This means:
* There is no link to the cluster overview page anymore or to the nodes. This makes it hard to navigate back to the overview page
* More Resources does not contain entries for CRDs that do not have CRs in the current namespace. This means that you can't create CRs in this Namspace throuh the UI from there.

Cluster level sections like "Apps & Marketplace" and "Monitoring" are still visible, but when you click on them it gets even more confusing.

Example Monitoring:

The Monitoring sections opens, but you don't see the monitoring Detail Page and you don't have access to the normal sub menu entries.

![Bildschirmfoto 2021-07-08 um 14 16 59](https://user-images.githubusercontent.com/243056/124920723-ecf00080-dff7-11eb-97e9-403236b4416a.png)

If you click on Advanced under Monitoring, you are directed to Prometheus Rules, showing all rules in the cluster and the Namespace filter seems to be removed from the left menu

![Bildschirmfoto 2021-07-08 um 14 17 14](https://user-images.githubusercontent.com/243056/124920826-0abd6580-dff8-11eb-8c35-fd752b137ce1.png)

If you click on Monitoring again, you get to the monitoring overview page

![Bildschirmfoto 2021-07-08 um 14 17 23](https://user-images.githubusercontent.com/243056/124920997-3ccec780-dff8-11eb-8116-60c8fb330cdb.png)

If you now choose Workloads in the left menu, the namespace filter is reapplied to the left menu.

Overall this behaviour feels very buggy and inconsistent.

In my opinion it should work like this:

* Cluster level, non-namespaced pages/sections like "Monitoring, Apps & Marketplace, Cluster Overview, Nodes, ..." should always be visible, regardless of the namespace filter, and somehow visually separated from namespaced sections
* A namespace filter should not limit the CRD entries that are visible, even if there are currently no CRDs for the CR in the namespace

**Comment by catherineluse** [comment]
I have a question about this last point:

> A namespace filter should not limit the CRD entries that are visible, even if there are currently no CRDs for the CR in the namespace

The cluster explorer side nav has a system of marking different behavior for different resources. Some are marked as something that needs to appear in the side nav, even if there are zero of them in the current view. Other, usually more advanced resources, are marked to appear in the side nav only if there is only one of them in the current view.

That system involves a lot of manual configuration. I'm thinking it may make more sense to have the custom resources grouped by API group in the side nav, because we have seen that pattern in other Kubernetes UIs. The side nav item should be visible if the user has permission to see the resource, but there should still be some visual indicator as to whether it is namespaced.

Moving to the issue to design triage for discussion.

**Comment by kwwii** [comment]
As far as I can tell, the Apps page no longer loses the filter or changes due to the top namespace filter. Is this correct?

**Comment by bashofmann** [comment]
The apps page works now, but access to some CRDs is still very confusing. Tested with 2.7.2:

Without a namespace filter, I see that the cluster has cert-manager CRDs.

<img width="1072" alt="Bildschirmfoto 2023-04-14 um 14 16 31" src="https://user-images.githubusercontent.com/243056/232041483-1048b4d1-102a-4c56-a5af-a5d3ac51b003.png">


With a namespace filter, the cert-manager group and CRDs are not displayed anymore. This means, I can't create a new certificate resource in the default namespace from the UI, if I'm filtering for this namespace and there is no namespace present yet.
<img width="1072" alt="Bildschirmfoto 2023-04-14 um 14 16 40" src="https://user-images.githubusercontent.com/243056/232041451-5bdff49a-0ea2-48c5-8d62-5fd1f48e5f74.png">

**Comment by kwwii** [comment]
Closing this as the issue has been addressed. Feel free to reopen if necessary
