### ISSUE TITLE
Port Cluster Rotate Encryption action from Ember UI

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3153]

**Comment by nwmac** [comment]
See:

**Comment by nwmac** [comment]
see https://github.com/rancher/ui/blob/a9166ce3fbc6e44ed9ca7acf54350a084923fbe2/app/models/cluster.js#L280

**Comment by nwmac** [comment]
You must provision a cluster with the Advanced Option 'Secrets Encryption' enabled.

**Comment by nwmac** [comment]
![image](https://user-images.githubusercontent.com/1955897/121161665-242a9080-c845-11eb-9596-856bf0ed1eb4.png)

**Comment by kravciak** [comment]
I can rotate encryption key even without etcd backup from emberUI.
I can't click `Rotate` button without backup in dashboard.
Is this intended change?

Otherwise it works fine on master-head (4d18400)

**Comment by sowmyav27** [comment]
@kravciak By default etcd snapshots are enabled on RKE1 clusters (Ember UI). Can you double check if a recurring snapshot was not available when doing Rotate Encryption action on cluster in Ember UI?

**Comment by kravciak** [comment]
> Can you double check if a recurring snapshot was not available when doing Rotate Encryption action on cluster in Ember UI?

It was available, I deleted it manually.

**Comment by kravciak** [comment]
I created DO-rke1 and custom clusters in emberUI, then switched to Dashboard:

Dashboard -> Cluster Management -> cluster menu (`...`)

- `Rotate Certificates` button is `not` visible in the menu
- `Rotate encryption keys` button is visible, even though secrets encryption is not enabled
- When I enable secrets encryption I can see `Rotate Certificates` button

It seems that logic for button visibility is swapped between certificate / encryption keys.

Rotating encryption keys results in error (there is no encryption so it's expected)
![Screenshot from 2021-06-23 15-12-35](https://user-images.githubusercontent.com/538604/123102627-8edaef00-d435-11eb-9010-a199c8d61911.png)

I tested the same few days ago (4d18400) and it was working fine.
Tested on master-head (d44698d)

**Comment by nwmac** [comment]
I believe this has been resolved now

**Comment by kravciak** [comment]
Works fine on master-head (cf5a75f):

Key rotation is available based on cluster secret encryption. Key rotation calls v3 API.
Secrets are reencrypted after rotation, I tested it with following steps:

```
# generate secret
kubectl create secret generic thesecret --from-literal=key1=supersecret
kubectl get secret thesecret -o jsonpath="{.data.key2}" | base64 --decode

# ssh to node with etcd container and display my secret
etcd_id=$(docker ps -f name=etcd -q)
docker exec -it $etcd_id etcdctl get /registry/secrets/default/thesecret

# rotate key from dashboard UI and check secret was reencrypted
docker exec -it $etcd_id etcdctl get /registry/secrets/default/thesecret
```

**Comment by kravciak** [comment]
I tested with DO infra provider cluster created in emberUI and dashboard.
Certificate actions are available only for rke1 cluster. Is this ok?

![Screenshot from 2021-07-08 23-39-53](https://user-images.githubusercontent.com/538604/124994379-0cae1580-e046-11eb-8251-3ce8f5bf9de7.png)

**Comment by nwmac** [comment]
@kravciak Yes, this is okay
