### ISSUE TITLE
Container shell does not work on windows containers

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3157]
In cluster explorer a container shell can't be opened in windows containers. The dasboard tries to execute `/bin/sh` in the windows container (https://github.com/rancher/dashboard/blob/4ebe78930d27a2300a499efce110eb78816d049c/components/nav/WindowManager/ContainerShell.vue#L17). This fails and the shell tab is never opened.

Cluster Manager detects, if the container is running on a windows node, and runs `cmd` instead: https://github.com/rancher/ui/blob/32e6b2a0955b26220de88912882a551b5e0513cc/lib/shared/addon/components/container-shell/component.js#L121-L123

Screenshot of the working shell in cluster manager:
![Bildschirmfoto 2021-06-03 um 17 05 24](https://user-images.githubusercontent.com/243056/120667558-e9fc7000-c48d-11eb-873a-21634a90824c.png)

**Comment by thehejik** [comment]
Tested on RKE1 with Windows-2004 nodes on k8s v1.20.7 `rancher/rancher:master-head 3dae3e2`

This doesn't working correctly - once I trigger `Execute shell` on windows pod (eg. `cattle-node-agent-windows*`) it is ok and `cmd` shell is opened correctly but when I do the same on linux pod (eg. `cattle-node-agent*`) it complains:
```
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "cmd": executable file not found in $PATH: unknown
```
![windows_cmd](https://user-images.githubusercontent.com/12828077/122401912-504cbc80-cf7d-11eb-877d-3e263abf8666.png)
![linux_cmd](https://user-images.githubusercontent.com/12828077/122401945-55aa0700-cf7d-11eb-8a9b-d7c94feae13f.png)




On non-windows cluster a proper linux shell is opened.

Reopening.

**Comment by westlywright** [comment]
I forgot at the pod level the container could be on a linux or windows based node so my original fix for checking the cluster os wont work here. I've found a work around which involves fetching the node the pod is running on and checking the node info for the os info. But will still fail in cases where the user does not have access to the node (RBAC). In order for this to work 100% of the time we need to have the backend team add some kind of os info the pod resource. I will open another ticket for this work. But until this work is in, this is basically all I can do.

**Comment by thehejik** [comment]
Successfully verified on `rancher/rancher:master-head 51d074b` on RKE1 windows cluster based on `Windows-20H2` worker nodes with k8s `v1.20.7-rancher1-1`:

![cmd_shell](https://user-images.githubusercontent.com/12828077/122946215-79a08a80-d379-11eb-90a9-73ccc66421b2.png)

Closing.

**Comment by thehejik** [comment]
Needed to retest  on win-2004

**Comment by thehejik** [comment]
It is working same way also on Windows 2004 nodes. 

Closing.
