### ISSUE TITLE
Rancher version is Unknown in sidebar

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#3160]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Bring up Rancher master-head
Navigate to dashboard side panel.

**Result:**
Rancher version is seen as `unknown`
![Screen Shot 2021-06-03 at 12 31 52 PM](https://user-images.githubusercontent.com/57409052/120706150-99751a80-c46d-11eb-8c17-b379382bac6f.png)
![Screen Shot 2021-06-03 at 12 33 56 PM](https://user-images.githubusercontent.com/57409052/120706151-9a0db100-c46d-11eb-9074-b5d8b0b4290a.png)

On Rancher `master-head` `version be03c8bd1`

**Comment by richard-cox** [comment]
This only happens when the user signs in, not when already signed in and window is refreshed. I think we _might_ have partial preferences / settings. Will investigate as part of #3137

**Comment by vincent99** [comment]
Yeah I never finished testing this because the partial list/public settings weren't in the API yet at the time, but is now..

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 3d465ee`
Rancher version is seen in bottom left and in side panel:
![Screen Shot 2021-06-08 at 11 26 24 AM](https://user-images.githubusercontent.com/57409052/121238004-8044e300-c84c-11eb-9085-a2eef21a7eb0.png)
![Screen Shot 2021-06-08 at 11 26 37 AM](https://user-images.githubusercontent.com/57409052/121238006-80dd7980-c84c-11eb-8d87-2d6d2ef7110a.png)
