### ISSUE TITLE
Only active nodes are showing in the dashboard

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#3172]
Originally reported here: https://www.reddit.com/r/rancher/comments/nqq53e/rancherv257_nodes_always_show_as_active_when/

After adding a new node to a cluster I noticed that the node never shows up in dashboard until it's active. When inspecting the `/k8s/clusters/c-ph275/v1/nodes` API I noticed that it didn't even return the node that was currently being provisioned while `/v3/nodes` did.

It looks like we may need to switch APIs for listing nodes and perhaps getting their status.

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/issues/1110#issuecomment-682179896

They aren't (k8s) nodes until they're an active part of the cluster.  The cluster management section will show and manage the lifecycle of the VMs we're provisioning separately (as "machines", separate from "nodes").

**Comment by codyrancher** [comment]
I recognize that's the current case which is why I mentioned switching APIs. Do we actually want to maintain showing just the k8s concept of a node? What's the benefit?
