### ISSUE TITLE
After deleting a Project with a namespace the UI shows the namespace in the Not in a Project group but the Project is now displayed empty

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3175]
Rancher version `2.6 master-head (05/07/2021)` _b2f8824_

Create a Project I set also the resource quotas fields in the UI
Create a namespace from the UI
Delete the project from the UI

The Namespace is moved to `Not in a Project` but the Project is displayed in the UI as empty

UI Screenshot after deleting Project `test3` (namespace `test3` is moved to `Not in Project`)

![Screen Shot 2021-06-07 at 4 27 08 PM](https://user-images.githubusercontent.com/27659/121099870-8a63d480-c7ad-11eb-9e9e-5998a2de74aa.png)

Screenshot after refreshing UI

![Screen Shot 2021-06-07 at 4 27 22 PM](https://user-images.githubusercontent.com/27659/121100213-33123400-c7ae-11eb-9fd5-1b2f303065c1.png)

**Comment by codyrancher** [comment]
@izaac I'm not sure the description matches the screenshot. And I'm not able to reproduce the description. Is there anything special you did? The project is removed when I delete it a

![delete-project](https://user-images.githubusercontent.com/55104481/121100914-a23c5800-c7af-11eb-8e31-47ecf4ac7285.gif)

**Comment by izaac** [comment]
@codyrancher Here's a video 

`master-head` _6f4f015_

- Downstream cluster is Custom RKE1
- Project has resource limits set.
- One namepace in the project with defaults.


https://user-images.githubusercontent.com/27659/121105259-9d2fd680-c7b8-11eb-9b33-77192bb614e1.mp4

**Comment by codyrancher** [comment]
I was only able to reproduce this about 20% of the time so make sure you repeat the test a handful of times when verifying the fix.

**Comment by izaac** [comment]
Sure @codyrancher  will do!

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/25/2021)` _c7f3cce_

I am still able to reproduce this as observed in the attached video.
Downstream RKE1 cluster.
Standard User that's the cluster owner.

I created three Projects with one namespace each. 
Steps taken for creating the projects/namespaces
- Create project `test1` with all the `Container Default Resource Limit ` set.
- Clone project `test1` and create project `test2`
- Sane for project `test3` (clone `test1`)
- Create each namespace by clicking the create namespace button on each Project.

Then I attempt to delete each project one by one.



https://user-images.githubusercontent.com/27659/123469999-a4245a80-d5a8-11eb-9f4c-86d75e8583c5.mp4

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (08/02/2021)` _3499046_

I see the Project briefly moved as empty and then disappearing automatically from the UI now in this new Rancher master-head build

Opened a separate issue about Project removal behavior on Dashboard and Ember
https://github.com/rancher/dashboard/issues/3607
