### ISSUE TITLE
Form fields in Cluster Private Registry & Agent Environment Vars tabs tweaks

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3184]
- Form fields are too high compared to others in tab group
  - Think they both use the generic KeyValue component
  - possibly due to input fields missing labels (either labels are needed or height should be reduced if missing)?
- Agent Environment Vars tab `Key` column label should be titled `Variable Name` as per cluster manager

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head 3ae6f43` where defining Custom RKE2 cluster.

* The input fields for `Private Registry` and `Agent Environment Vars` seems to use the same height as other tabs do (height: 61px taken from `$input-height` variable in code). Also the padding looks good.
![registry](https://user-images.githubusercontent.com/12828077/125304217-aec34b80-e32d-11eb-8fc8-fbe1f1b9874f.png)


* But I don't see the title `Variable Name` in `Agent Environment Vars` tab, the first column is still named `Key`.
![no_title](https://user-images.githubusercontent.com/12828077/125302772-8be46780-e32c-11eb-8414-46f463803819.png)

Reopening - please rename the `Key` title to `Variable Name` in `Agent Environment Vars` tab

**Comment by deniseschannon** [comment]
Validated that the "variable name" is used as the header for agent env var. 

master-head b395238 - 8/2/2021
