### ISSUE TITLE
Explicitly setting the RKE2 feature to true during Rancher helm upgrade makes the dashboard home not show the content

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3192]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Rancher `2.5.8` HA RKE1 setup with Custom downstream cluster 
- Upgrade to `master-head (06/08/2021)` _ce97613e8_ with feature `rke2=true`

`helm upgrade rancher rancher-latest/rancher --version 2.5.8 --namespace cattle-system --set hostname=<RANCHER_HOSTNAME> --set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=rke2=true' --set rancherImageTag=master-head` 

**Result:**

`https://<RANCHER_HOST>/dashboard/home` is Empty
But I can navigate to other areas and also to legacy Cluster Manager

![Screen Shot 2021-06-08 at 12 57 51 PM](https://user-images.githubusercontent.com/27659/121249773-cce2eb00-c859-11eb-9317-559401c8ddb7.png)

**Other details that may be helpful:**

With `rke2=false` the Dashboard Home page is populated.
https://github.com/rancher/rancher/issues/32630#issuecomment-856935496
[log.txt](https://github.com/rancher/dashboard/files/6619294/log.txt)

**Environment information**
- Rancher version: 2.5.8 upgrade to `master-head (06/08/2021)` _ce97613e8_
- Installation option: HA RKE1

**Comment by gaktive** [comment]
Might have to look if there's an error in the browser console.

**Comment by nwmac** [comment]
@izaac Can you try and reproduce this and capture the output of the console when you see it again. Thanks.

**Comment by izaac** [comment]
@nwmac sure I will attempt to repro again at my earliest

**Comment by izaac** [comment]
Rancher version `2.6 master-head (07/12/2021)` _ad099ee_

Closing as I wasn't able to reproduce this on a newer `master-head` build.
