### ISSUE TITLE
rke2 cluster creation is stuck in loading and does not recover on an upgraded rancher setup

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3195]
Single install rancher
Rancher version before upgrade: v2.5.8
Rancher version after upgrade : master-head 3d465ee

1. Upgrade rancher server version from v2.5.8 to the master-head commit 3d465ee
2. From the explorer --> cluster management create an rke2 cluster DO or AWS EC2--> page is stuck in loading with the console errors:
```
TypeError: Cannot read property 'workerConfig' of undefined
    at f.multipleAgentConfigs (rke2.vue:205)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.evaluate (vue.runtime.esm.js:4584)
    at f.multipleAgentConfigs (vue.runtime.esm.js:4836)
    at f.r (rke2.vue?c117:1)
    at f.t._render (vue.runtime.esm.js:3548)
    at f.r (vue.runtime.esm.js:4066)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.run (vue.runtime.esm.js:4554)
    at gn (vue.runtime.esm.js:4310)
```
3. This happens for custom clusters with the console logs:
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'etcd' of undefined
    at f.r (rke2.vue?c117:1)
    at f.t._render (vue.runtime.esm.js:3548)
    at f.r (vue.runtime.esm.js:4066)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.run (vue.runtime.esm.js:4554)
    at gn (vue.runtime.esm.js:4310)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at ie (vue.runtime.esm.js:1906)
```

Expected result:
When we click on create rke2 cluster, it should not be stuck in loading but should be taken to the details page

This does not happen with hosted clusters and rke1 clusters on the explorer

**Comment by vincent99** [comment]
None of this happens for me in master..

But I merged a decent set of changes 20 minutes after this issue was created, so that could have fixed it.  If this is still happening, is step 1 _actually_ relevant (as in it doesn't happen with a new master; This seems highly unlikely)?  What browser and is it different in others?  Both are suggesting the value->spec->rkeConfig isn't getting setup somehow and so child properties of it (etcd and workerConfig) are missing.

**Comment by anupama2501** [comment]
Yes @vincent99 for step1:  
on a fresh install I didn't see this issue with the same commit ID 3d465ee. I was able to create an rke2 cluster from explorer DO - 1 node all roles. Only seeing on an upgraded setup. 
Browser - Google Chrome

**Comment by gaktive** [comment]
@deniseschannon has indicated there may have been a recent backend change that caused this. To be confirmed.

**Comment by gaktive** [comment]
@anupama2501 can you try to repro this with an updated `master` and see if this happens again? If so, keep the cluster up so that UI can hop on and take a look.

**Comment by anupama2501** [comment]
Before upgrade rancher version: v2.5.8 
After upgrade rancher version: c7f3cce master-head

1. Spin up rancher on v2.5.8 and upgraded rancher to the master-head
2. Created an rke2 node driver cluster 1 node all roles and verified the cluster has come up fine without any console errors
3. Created a custom rke2 with linode all roles and verified the cluster has come up active without any errors.

Closing the issue as it is not seen in the master-head c7f3cce and will re-open if it resurfaces again.
