### ISSUE TITLE
YAML editor folding while editing doesn't remember where it folds

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#3196]
Spotted by Vince and Darren: if you edit some yaml where part of the document is "folded" (a bunch of lines for a child object collapsed into a <-> icon)  and unfold it keeps forgetting the fold state or editing stops working or other weird things. This makes using the feature annoying.

**Comment by gaktive** [comment]
Likely a long-used 3rd party library.

**Comment by ekristen** [comment]
Guess I reported my issue to the wrong place https://github.com/rancher/rancher/issues/32354, I'll close it in favor of this one. I would very much like to see this fixed. Even back ported to 2.5.9 if possible.

**Comment by thehejik** [comment]
**Test report:**
* issue reproduced successfully on `rancher/rancher:v2.5.8`
* issue validated as fixed on `rancher/rancher:master-head 4d18400`:
![unfolding_property-2 6](https://user-images.githubusercontent.com/12828077/122766029-5bfff200-d2a1-11eb-873c-fd671fbbf018.gif)

Closing.

**Comment by ekristen** [comment]
FWIW, the gif given doesn't demonstrate that this is fixed.

**Comment by thehejik** [comment]
@ekristen I was using reproducer from PR:

```
To reproduce

1. Nav to a DaemonSet's Edit Yaml page (ensure that the annotations section is initially collapsed)
2. Edit any of the yaml (for instance add a new property at the top)
3. Try to expand the annotations section, which fails and section remains collapsed
```

I was able reproduce this issue on 2.5.8 by following ^ and wasn't able on master-head.

**Comment by ekristen** [comment]
Interesting. 

I was unaware there were multiple different symptoms. My bad.

My version of this issue is expand annotations section then attempt to edit by adding a new one and it'll always collapse.

**Comment by richard-cox** [comment]
This does also fix editing inside the annotations block as well as around it. To be clear though, you were seeing the annotations section automatically collapse after editing it's content?

**Comment by ekristen** [comment]
Sweet.

To clarify, during editing, while both editing a value or adding a new annotation it would periodically just collapse.

Usually not saving changes.
