### ISSUE TITLE
rke2 explore cluster on an upgraded setup is navigated to the cluster management page

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3197]
Rancher version before upgrade v2.5.8
After upgrade : master-head 3d465ee

1. Create an rke1 cluster from ember UI on rancher server v2.5.8
2. Upgrade the rancher server to the master-head 3d465ee.

Scenario 1:
- From cluster management --> create an rke2 DO cluster [currently stuck in loading and not recovered]
- If we go to the explorer cluster from the hamburger menu --> select the cluster created in step1, users are redirected to the cluster management page

<img width="200" alt="Screen Shot 2021-06-08 at 3 53 25 PM" src="https://user-images.githubusercontent.com/38144301/121267877-bf395f80-c871-11eb-9b73-bf77064f92c1.png">

Scenario 2:

- If we logout of the cluster and re-login 
- From the explorer --> explore cluster --> select the cluster created in step1, users are redirected to the metrics page but nothing is present in the left hand navigation.
 
<img width="100" alt="Screen Shot 2021-06-08 at 3 49 38 PM" src="https://user-images.githubusercontent.com/38144301/121268528-007e3f00-c873-11eb-95d7-19656e814318.png">

**Comment by gaktive** [comment]
@anupama2501 is this cluster still up for someone to take a look at this? Reproducing this seems hard. I suspect that the lack of any sign of a cluster there indicates that it never got far enough during the upgrade to register.

**Comment by anupama2501** [comment]
@gaktive Unfortunatley, I do not have the setup from when the issue was seen and I'm not able to reproduce it on the latest master-head 3f55e03 version.

**Comment by gaktive** [comment]
Closing for now. If this surfaces again, either reopen this or create a new ticket and link back for context. Please have an environment ready for UI to look at if so.

**Comment by anupama2501** [comment]
Closing the issue as it is not reproducible on the master-head e756276. Will re-open once it resurfaces.
