### ISSUE TITLE
Update provider icons

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3199]
I added some of the missing provider icons in this PR - https://github.com/rancher/dashboard/pull/3198

@lvuch Can you resize them to be consistent with the others, please.

There is also one png image that needs to be converted to svg.

**Comment by thehejik** [comment]
**Test report:**
Tested on `rancher/rancher:master-head cf5a75f`
![providers](https://user-images.githubusercontent.com/12828077/124929439-cc787400-e000-11eb-8db5-3e87156ce9b9.png)

The icons were updated as part of not-yet linked PR https://github.com/rancher/dashboard/pull/3207

Close.
