### ISSUE TITLE
[Monitoring V2 UI]  warning for subchart's workload type when the cluster is RKE2 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#3201]
As [this issue](https://github.com/rancher/dashboard/issues/3189) describes, the workload type in the sub-chart `rke2IngressNginx` is determined by the k8s version of the RKE2 cluster. It may cause confusion when the user does not notice the detail and upgrades his existing RKE2 cluster from 1.20 to 1.21.  So we would like to show a warning or a message somewhere on the following page when the cluster type is RKE2 (UI calls it RKE government) to indicate this special behavior. 

![image](https://user-images.githubusercontent.com/6218999/121390845-a0cf7480-c902-11eb-857a-206f5aec89f7.png)

**Comment by gaktive** [comment]
@jiaqiluo can we get more details on what you'd like to see? There's another page during the upgrade process that would normally take care of this.

**Comment by jiaqiluo** [comment]
Hi @gaktive 
In the coming new version of monitoring v2 chart `100.0.0` in rancher `v2.6.0`, we will add two new sub-charts: `rkeIngressNginx` and `rke2IngressNginx`. Although we have recorded all those changes to the app's README file, I am not sure whether users will read the README file or not 🤣 , so I do not want to surprise users with 1) the newly-added sub-charts and 2) the change of workload type of the rke2IngressNginx based on the RKE2 version in the monitoring upgrading scenario. 

The 1st change should not be a problem because it is simply an addition of new sub-charts, which is a very common change in a new version of a chart. 

The 2nd change is what we want to call out on the page you mentioned for the upgrade process. Here is the scenario that will trigger the change of workload type: 
Let's say we run Rancher `v2.6.0`, we provision an RKE2 cluster which version is `v1.20.7+rke2r2`, and then we enable the monitoring `100.0.0` in this cluster. At this point, the workload type of the `rke2ingress` is `deployment`. We upgrade the RKE2 cluster to `v1.21.1+rke2r1`, and we want to either change the configuration of the running monitoring `100.0.0` or upgrade it to a newer version, for example, `100.1.0`. When the edit or upgrade happens since the cluster version is > 1.20, so `rke2ingress`'s workload type is switched to `daemonSet`. 
This is the significant change that we should warn users of the potential influence on their cluster or other apps running in the cluster. For example, since `daemonSet` will run on all nodes by default, they may need to update the `tolerations` on the `rke2IngressNginx` to run pods on selected nodes or configure their storage app to support multi-connection/multi-read-write. 

I hope I have provided sufficient information about this request. let me know if you have any questions 😄

**Comment by catherineluse** [comment]
I suggest closing this issue because I'm thinking it would be better to explain this in the monitoring Helm chart README. 

The README can say, "Warning: When this chart is installed on an RKE2 cluster older than version `v1.21.1+rke2r1`, the `rke2ingress` is changed from a Deployment to a DaemonSet."
