### ISSUE TITLE
Some states of imported clusters can show incorrect content in Config/Edit page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3209]
- I created a cluster via the 'import' option
- Not quite sure what went wrong under the hood with the import, but I could click on that cluster and get to the detail page
- Clicking on the Config section showed the same create experience instead of the read-only edit page
- ![image](https://user-images.githubusercontent.com/18697775/121497415-5669f880-c9d3-11eb-9041-a530ca872a93.png)

**Comment by vincent99** [comment]
This looks like a situation where the corresponding management cluster was never created, which "shouldn't" be happening anymore unless you can still reproduce this reliably @richard-cox .  Editing an imported cluster now goes to the Ember page (for upgrading k3s/rke2 cluster support).

**Comment by prachidamle** [comment]
Not able to reproduce this using v2.6.0-rc1 
I was able to import an rke cluster using the  "Generic" option of "Import Cluster". 

After adding cluster, Dashboard UI shows the page to import hosts:

<img width="1606" alt="Screen Shot 2021-08-06 at 4 00 32 PM" src="https://user-images.githubusercontent.com/1470602/128579413-b14a2e5b-b334-4168-865b-2566173f4541.png">


Upon clikcing the "Config" tab, this page is shown:
<img width="1603" alt="Screen Shot 2021-08-06 at 4 00 52 PM" src="https://user-images.githubusercontent.com/1470602/128579411-2c0863b3-51ec-40ae-9003-8bad49122787.png">
