### ISSUE TITLE
Enabling S3 while deploying backup restore chart is not persisting when switching between edit Options and Yaml

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3215]
**On master-head commit id: `5715b8a`**

- In the local cluster --> Apps and market place (Dashboard) --> Charts
- Rancher backups --> Install
- in Edit Options --> choose `Use S3 compatible object store`
- Click on Edit as YAML
- S3 will be enabled
- Now switch back to Edit options

<img width="808" alt="Screen Shot 2021-06-12 at 4 10 41 PM" src="https://user-images.githubusercontent.com/26032343/121790869-cecde680-cb98-11eb-8f09-0a26f529245c.png">

**Expected:**
When toggling back to Edit Options, `Use S3 compatible object store` should be enabled.

**Comment by thehejik** [comment]
It works as expected on `rancher/rancher:master-head 3dae3e2` with `rancher-backups-100.0.0+up1.1.1`
```
  branch: dev-v2.6
  commit: d9130be8f0bc9bf3504a7e578a4709e2b24de672
```

![etcd_backup](https://user-images.githubusercontent.com/12828077/122404549-9d319280-cf7f-11eb-8c6a-35132100948e.gif)

Close.
