### ISSUE TITLE
Cluster Dashboard in cluster explorer shows two Events sections

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3218]
**On master-head commit id: `5715b8a`**

- On a downstream cluster, From Cluster tools, enable Monitoring v1 (Legacy) (cluster should have enough CPU)
- Navigate to cluster Dashboard of a downstream cluster
- There are two events section available in this page

<img width="1426" alt="Screen Shot 2021-06-13 at 5 39 42 PM" src="https://user-images.githubusercontent.com/26032343/121826845-b7612d00-cc6e-11eb-9a91-bfd68c10cbf4.png">

**Expected Result:**
Only 1 events section should be available as it is redundant.

**Note:**

- Cluster monitoring v1 was enabled on this cluster, and the 2 events sections were seen while the monitoring v1 was being deployed
- But when it has been successfully enabled, 2 events sections are not available now.

**Comment by nwmac** [comment]
Fixed by this PR: https://github.com/rancher/ui/pull/4668

**Comment by sowmyav27** [comment]
**On master-head commit id: `d44698d`**

- On a downstream cluster, From Cluster tools, enable Monitoring v1 (Legacy) (cluster should have enough CPU)
- Navigate to cluster Dashboard of a downstream cluster
- Two events sections are not seen.

<img width="1432" alt="Screen Shot 2021-06-22 at 7 33 23 PM" src="https://user-images.githubusercontent.com/26032343/123026587-4b2ea980-d391-11eb-95a3-cd44bd724cb3.png">
