### ISSUE TITLE
[UI] RKE2 Windows Implementation in 2.6

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/dashboard#3222]
When provisioning a new cluster, we need to add a box that allows the user to pick Windows and then present the appropriate options to configure it.

## 2.6 UI Changes Required for RKE2 Windows Implementation (To be behind behind RKE2 feature flag. RKE1 options remain the same.)

Requirements:
- 1.21.x k8s version (min. req. k8s version is latest 1.21.x at the time of the 2.6 release)
- Windows workers require Calico as the CNI and are not supported by any other CNI choice
- Windows supported versions: 2004, 20h2 and LTSC (Windows Server 2019)
    - Requires Windows Semi-Annual Channel version 2004 or 20H2 or Windows Server 2019 LTSC with the latest patches 

UI Additions:
- Registration command for Windows worker nodes
- Only allow worker role for Windows nodes to be registered (grey out etcd and controlplane for windows)
- Ability to group machine pools by OS  ([ State, Name, OS, Age])
- Add `kubernetes.io/os` label sorting
- Requires a new args box under `Advanced:` (to match the existing "Additional Kubelet Args" box)
    - "Additional Windows Kubelet Args"
- Requires a new arguments box under `Advanced:`
- Ability to pass additional Windows-specific kubelet and kube-proxy arguments through the UI when editing a cluster as YAML

cc: @sirredbeard

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/issues/3227 is a related ticket on tying into a broader story of Windows Cluster Provisioning v2.

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/issues/33625

**Comment by vincent99** [comment]
Dashboard should show the command when appropriate now, backend may still be pending for the command to actually be correct/work.

**Comment by anupama2501** [comment]
Verified on v2.6.0-rc8

- Registration command for Windows worker nodes - **`Pass`**
- Only allow worker role for Windows nodes to be registered (grey out etcd and controlplane for windows) - Have `Windows nodes can only be workers` - **`Pass`**
- Add kubernetes.io/os label sorting - **`Pass`** 
- Requires a new args box under Advanced: (to match the existing "Additional Kubelet Args" box)
- "Additional Windows Kubelet Args"  - **`Pass`**
- Requires a new arguments box under Advanced: **`Pass`**

**Comment by anupama2501** [comment]
- Ability to group machine pools by ([ OS, Name, OS, Age]) -- OS is not displayed in the machine pools tab

Cluster management page:

<img width="500" alt="Screen Shot 2021-08-28 at 2 19 16 PM" src="https://user-images.githubusercontent.com/38144301/131231263-8751d4e6-c4cb-4aea-8874-5ae3d430ebc5.png">

Explore cluster page:

<img width="500" alt="Screen Shot 2021-08-28 at 2 19 45 PM" src="https://user-images.githubusercontent.com/38144301/131231285-602515dd-5a70-4cb3-bf6d-0dac7ed42b8d.png">

**Comment by anupama2501** [comment]
Re-opening and changing the milestone as this will be fixed as part of later release.

**Comment by gaktive** [comment]
@rak-phillip please split this OS column requirement into another ticket and determine if we need to transfer it to rancher/rancher. Otherwise, pass this back to QA for subsequent testing.

**Comment by anupama2501** [comment]
@rak-phillip I see two PRs and one of them isn't merged yet is this ready to-test?

**Comment by richard-cox** [comment]
This should be tested together with #4240

**Comment by anupama2501** [comment]
Verified on v2.6-head 223ec88

O.S tab is displayed in

explore cluster --> Cluster --> nodes 
<img width="400" alt="Screen Shot 2021-09-23 at 7 27 53 AM" src="https://user-images.githubusercontent.com/38144301/134537906-ed3c6b74-40a0-4381-a477-8d198722fc35.png">
 

 in cluster management page --> machine pools page
<img width="400" alt="Screen Shot 2021-09-23 at 7 28 09 AM" src="https://user-images.githubusercontent.com/38144301/134537758-1c1682be-8793-4b11-8fc8-770d0a4d5d55.png">
