### ISSUE TITLE
Unable to uninstall v1 apps from Explorer over Apps & Marketplace menu

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3223]
Cont. of https://github.com/rancher/dashboard/issues/2959

After installing v1 app from Explorer which is now supported in `rancher/rancher:master-head 5715b8a` user sees the v1 apps (monitoring and logging so far) in App & Marketplace menu. Problem is when user is trying to remove/uninstall the v1 app from the menu when it says `Error: uninstall: Release not loaded: cluster-monitoring: release: not found`

![uninstall-v1](https://user-images.githubusercontent.com/12828077/121924740-746d8b00-cd3c-11eb-868a-046bce1e97e4.png)

And similary for `Cluster Tools` -  when user clicks on `trash bin` icon for installed v1 app.
![uninstall-v1-cluster-tools](https://user-images.githubusercontent.com/12828077/121925263-06759380-cd3d-11eb-863d-ce175ff18745.png)

V1 apps can be uninstalled only either in Ember or from Explorer by clicking `Cluster Tools` button and then uninstall `Legacy -> Projects -> Apps` 

Ideal would be if the v1 legacy apps are not showing in `Apps and Marketplace` but it probably must show because of upgrades to v2.

**Comment by nwmac** [comment]
This is a backend issue - reported here: https://github.com/rancher/rancher/issues/33454

**Comment by aiyengar2** [comment]
https://github.com/rancher/rancher/issues/33454#issuecomment-876748266

**Comment by gaktive** [comment]
Darren looking into what's happening with Helm v2 apps displaying here and fixing that. https://github.com/rancher/rancher/issues/33454 is that work.

**Comment by vincent99** [comment]
This is a backend issue and there's nothing changing in the UI to fix it.
