### ISSUE TITLE
navlinks enhancements

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3233]
master-head commit: 5715b8a

**Addressing 3 issues in this ticket**

1. Create a do rke2 cluster with 3 worker,1 cp, 1 etcd
2. Install longhorn in the cluster 
3. Create two navlink from the explore cluster --> cluster --> More resources --> Rancher --> Navlinks with the following fields test1:
> name: test1
> group: g1
> toService:
      name: longhorn-frontend
      namespace: longhorn-system
      path: /
      port: "80"
      scheme: http

4. Create test2 with the same values as above but without group: g1
5. Create a standard user - user1 and add u1 as a cluster member in the cluster.

**Enhancement needed:**

- [ ] **`Issue1`**

1. Once the navlink is created from the navlinks --> under the To option, the link is split into two parts for the URL and port value
2. If we click on the URL, users are redirected to the pod of the longhorn and if we click on the port value, users are redirected to the longhorn UI

**Expected Result:**

When users click on the URL either the url part or the port, should be redirected to the UI of longhorn and not the pod of the longhorn

<img width="500" alt="Screen Shot 2021-06-14 at 3 25 48 PM" src="https://user-images.githubusercontent.com/38144301/121968423-2a2ddf00-cd27-11eb-9210-6ae80005bb2d.png">

- [ ] **`Issue2`**

1. Log in as user1 and since the u1 has no access to view the longhorn, the navlinks will not be shown
2. For the user1, the NavLinks show count 2, but will not show the toService links created.

**Expected Result:**

For user1, the navlink count should be displayed as 0 instead of the count of navlinks created as admin
<img width="190" alt="Screen Shot 2021-06-14 at 3 34 49 PM" src="https://user-images.githubusercontent.com/38144301/121968360-0d91a700-cd27-11eb-841b-fdf7e560ce86.png">

- [ ] **`Issue3`**

1. While creating a grouped navlinks, it would be nice to have a description for the group when we click on the group once it is created.
2. Currently it displays the name of the group if we go inside of the group. This can be set to the description field of the group to give more information for the users when they login.

**Comment by vincent99** [comment]
1: This is intentional; the left half is the service resource itself and the right half is the proxy URL for the requested scheme/port/path.
2: Not UI; backend produces the counts.  You can put an issue in rancher/rancher but they will probably not want to fix this very-edge case of a person who isn't an admin looking at the list of navlink resources anytime soon.
3: The groups is not a separate resource so there is no good place to put this that wouldn't require repeating the same description on every link with the same group.

**Comment by gaktive** [comment]
I'll check if there's a backend ticket for item 2. Otherwise, the rest of this is a won't fix.

**Comment by gaktive** [comment]
Filed https://github.com/rancher/rancher/issues/33354 for Issue 2. If Longhorn does look at it, QA can reconfirm what the UI does and reopen as necessary. Otherwise, as noted, we won't fix these.

**Comment by anupama2501** [comment]
Closing this issue as a separate issue is logged for issue2 and the other 2 issues are not changed and are displayed as before in the current master-head e756276

Verified issue1:
Once the navlink is created from the navlinks --> under the To option, the link is split into two parts for the URL and port value
Left half takes to service resource and the right half takes to the url provided in the toURL.

Verified issue2:
No description field provided for the group as it is not a separate resource but a part of the existing yaml for navlink creation.
