### ISSUE TITLE
Brand settings page broken for SSR

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#3235]
It uses window.getComputedStyle in data() but there is no window yet.

**Comment by thehejik** [comment]
**Test report:**
* Brand settings can be saved with all values set - also other combinations tried
* `Show Rancher community support links` checkbox renders html by using `aria-checked="true"` attribute when set; without the attribute when not set.
```html
<span tabindex="0" aria-label="Show Rancher community support links" role="checkbox" class="checkbox-custom" aria-checked="true"></span>
```
Close.
