### ISSUE TITLE
Hide/Disable the Continuous Delivery if the Feature Flag is disabled.

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3246]
Rancher version: `2.6 master-head (06/15/2021)` _66c31dd_

Disable the `Continuous Delivery` Feature flag.

![Screen Shot 2021-06-15 at 11 17 41 AM](https://user-images.githubusercontent.com/27659/122113716-51dc8000-cdd7-11eb-9b82-5f471e3c4036.png)

The `Continuous Delivery` in Rancher is still visible and browsable.

![Screen Shot 2021-06-15 at 11 14 24 AM](https://user-images.githubusercontent.com/27659/122113708-4f7a2600-cdd7-11eb-90d2-33edcb709896.png)

**Comment by nwmac** [comment]
@vincent99 Just checking with you that this seems reasonable and we should gate the appearance of the CD option based on the feature flag.

**Comment by vincent99** [comment]
@izaac Yes, that flag controls the gitrepo type and the CD "product" shows up when that type is present.  I'm not sure if turning off the flag actually deletes the CRD though so this might appear to do nothing if turned off after it's been on?

**Comment by izaac** [comment]
@vincent99 uhm so the backend should do something here instead of the UI? The expectation when the flag is disabled is to hide the feature from being accessible in the UI

See last point in this comment:

https://github.com/rancher/rancher/issues/32808#issuecomment-845480007

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/01/2021)` _c1151f6_

Upgrade from 2.5.8 to 2.6 with `continuous-delivery=false`
Dashboard doesn't show the Continuous Delivery section.

<img width="756" alt="Screen Shot 2021-07-01 at 2 12 03 PM" src="https://user-images.githubusercontent.com/27659/124190393-0b458180-da77-11eb-8d63-6442f52cc609.png">


Re-enabling the flag makes the Continuous Delivery section available for browsing as expected:

<img width="631" alt="Screen Shot 2021-07-01 at 2 14 21 PM" src="https://user-images.githubusercontent.com/27659/124190437-21534200-da77-11eb-9755-b0dd7d9d0b54.png">
