### ISSUE TITLE
rke2 cluster membership issues

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3247]
Rancher version: master-head 9d54b1a

1. Create an rke2 node driver DO cluster with 3 worker, 1 etcd, 1 cp
2. Create 2 users from explorer --> Users and Authentication --> Users - user1, user2

- [ ] **Issue1:**

- From the explore cluster -->  RBAC --> Cluster Members --> add user1 and select Custom and see that `Manage Navlinks` option is missing

**Expected Result:**

- `Manage Navlinks` should be present in the cluster role which is for the new feature Navlinks

- [ ] **Issue2:**

- Add user2 as a cluster member from explore cluster --> RBAC --> cluster members --> Add user2 as `cluster member`
- Log in as user2 and navigate to explore cluster --> RBAC --> cluster members and user2 is not shown in the list of cluster Members

 **Expected Result:**
- When logged in as user2 cluster owner/member, the cluster members list should display all the users present in the cluster for the logged in user if the role is cluster owner/cluster member.

- [ ] **Issue3:**

- From explore cluster --> RBAC --> Cluster members, if we star the cluster members, the option is not shown under the starred resources

**Expected Result:**

- Cluster members option should be present under the starred resources when the resource is starred.
https://github.com/rancher/dashboard/issues/2501

**Comment by codyrancher** [comment]
Issue1: Added
Issue2: Should be resolved with https://github.com/rancher/dashboard/pull/3280
Issue3: This was actually a problem with virtual types so Projects/Namespaces, Cluster Members, Workloads and Namespaces were all affected.

**Comment by anupama2501** [comment]
Verified on master-head e756276

Create an rke2 node driver DO cluster with 3 worker, 1 etcd, 1 cp
Create 2 users from explorer --> Users and Authentication --> Users - user1, user2

Issue1:
Verified the `Manage navlinks` option is shown in the custom user permissions

Issue2:
Verified by adding user1/user2  cluster owner and cluster member in the cluster.
If logged in as user1 and user2 from explore cluster --> RBAC --> cluster members shows all the users present in the cluster
