### ISSUE TITLE
Add Grouped by Project to the Project/Namespace page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#325]
We would eventually need a Grouped by Project option on the Namespace page.  From 2.4
![image](https://user-images.githubusercontent.com/11514927/75379142-1cceb600-5892-11ea-938b-00d5466d60e5.png)

Changes Needed:
1.  Add namespace should live outside the Project Title bar & sit next to Add Project.
2. Change Namespace: All to say something like Project: None

**Comment by lvuch** [comment]
https://xd.adobe.com/view/5d9fd916-d439-426e-64d3-b0215021e938-2bae/

**Comment by deniseschannon** [comment]
This already exists today where it groups by project. 

<img width="1230" alt="Screen Shot 2020-04-27 at 5 06 14 PM" src="https://user-images.githubusercontent.com/11410997/80432539-6d21be80-88a9-11ea-941f-b53e5d60b4c2.png">
