### ISSUE TITLE
Cluster Provisioning v2: Linode - Create RKE2 clusters

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#3261]
Somewhat related to what's needed in Dashboard: https://github.com/rancher/dashboard/issues/3232

This exists in Ember via RKE1 so this should be a port for RKE2. We'd replace the generic components with machine templates and the API. There's a folder in Vue we can use.

**Comment by gaktive** [comment]
Would include node pools and the other components.

**Comment by gaktive** [comment]
Linode now available

**Comment by nwmac** [comment]
@vincent99 Is this already done? It appears that the option to create a Linode RKE2 cluster is in the UI already.

**Comment by vincent99** [comment]
These issues were for custom components that talk to the Linode API and show you the appropriate options and such.  What you're seeing now is the generic support for any driver.

**Comment by sowmyav27** [comment]
To Validate:
As a standard user
- Create Linode cloud credentials
- Create Linode RKE2 cluster (note RKE2 version). - 3 etcd, 2 cp and 3 worker nodes. Cluster should come up Active
- Create Linode k3s cluster (note k3s version). - 3 etcd, 2 cp and 3 worker nodes. Cluster should come up Active

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Validation**
Rancher: v2-6-head(1d2b746)
Install: Helm
Local k8s: v1.21.10

**Test Cases For Validation**

1. Create Linode cloud credentials (I didn't have access to these had to borrow creds)
2. Create Linode RKE2 cluster (note RKE2 version). - 3 etcd, 2 cp and 3 worker nodes. Cluster should come up Active
3. Create Linode k3s cluster (note k3s version). - 3 etcd, 2 cp and 3 worker nodes. Cluster should come up Active

**Results**

Was able to successfully to accomplish the above test cases.
