### ISSUE TITLE
Cluster Provisioning v2: Oracle - Create RKE2 Clusters

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#3263]
This exists in Ember via RKE1 so this should be a port for RKE2.

**Comment by gaktive** [comment]
Need to get access to an Oracle environment for UI development.

**Comment by jlamillan** [comment]
@gaktive ping me on Slack and I'll get you access to OCI.

**Comment by gaktive** [comment]
Based on @jlamillan's work, after he upgraded to v2.6.4-rc3, he was able to provision a RKE2 cluster using the OCI node driver plugin as it is.

We can pass this to QA to verify and this could be part of 2.6.4. He made reference to "workaround that invalid URL bug" which may need expanding upon.

**Comment by gaktive** [comment]
Based on QA workload, we can have this verified for 2.6.5.

**Comment by Auston-Ivison-Suse** [comment]
**Validation  Setup**
rancher version: v2.6-(head)
Chrome version:99.0.4844.74

Pre-reqs: Have the oke driver activated within "cluster drivers"

**To Validate**
1) press the create button
2) Select the oci as the provider

**Results**

The appropriate fields in the form: 
- nodeAvailabilityDomain
- nodeCompartmentId
- nodeImage
- nodeMemoryInGb
- nodeOcpus
- nodeShape
- nodeUsePrivateIp
- privateKeyContents
- privateKeyPassphrase
- privateKeyPath
- region
- subnetId
- tenancyId
- type
- vcnCompartmentId
- vcnId
