### ISSUE TITLE
Landing page doesn't appear to respect user

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3282]
Haven't looked under the hood, so title could be incorrect, but hit a bug by....

1. As admin set the default landing page to the 'local' cluster
1. Create a user with the ` Standard User` global permission
1. Add the new user to a non-local cluster with the Custom `View Nodes` role
1. Log out and then log in with the new user... the following error is shown

![image](https://user-images.githubusercontent.com/18697775/122395672-1ffe2180-cf6f-11eb-8b72-e64afc357933.png)

5. Clicking 'Home' resolves the issue - can log out / in again

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `4b6af95`**

- As admin set the default landing page to the 'local' cluster
- Create a user with the Standard User global permission
- Add the new user to a non-local cluster with the Custom View Nodes role
- Log out and then log in with the new user. No error is seen. User is redirected to Home page.
