### ISSUE TITLE
RKE2 Cluster Templates: unable to select template version when using cluster templates

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3285]
on master-head (479795f):
<img width="419" alt="Screen Shot 2021-06-17 at 10 19 51 AM" src="https://user-images.githubusercontent.com/16691014/122444630-9857e900-cf55-11eb-8efb-967ba4475c65.png">
UI appears to auto select the latest version, but there is no option for the user to select a different version (there is a 0.0.1 and 0.0.2 version for this template) 

Repro steps:
* add a git repo with multiple versions for 1 template to the local cluster
* go to install a cluster via the rke2 templates you've just added
* there is no option to change the version

parent ticket: rancher/dashboard#2972

**Comment by vincent99** [comment]
@richard-cox I think you added something for another case like this to make the version show up on this 2nd screen instead of the big readme screen, can you do that here too?

**Comment by deniseschannon** [comment]
Validated on master-head b395238 8/2/2021.

1. Add a cluster template with multiple versions. 
2. When deploying the cluster template, there is ability to select version of template:

<img width="1180" alt="Screen Shot 2021-08-02 at 5 12 06 PM" src="https://user-images.githubusercontent.com/11410997/127938576-bad437fc-24be-49f6-bfdf-648d50f4b251.png">

Validated that the helm CLI deploys the helm chart based on version.
