### ISSUE TITLE
Setup with mcm=false feature flag shouldn't ask for server-url

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#3286]
If you run Rancher in single cluster mode (`--features=multi-cluster-management=false`) then the setup flow should not ask to setup the server-url since it won't be relevant for that usecase.

If you later turn on MCM, server-url needs to get set if it isn't already.  This could be added to the confirm modal for activating MCM, or a separate one anyone might see if they have write access to the setting and it's not currently set.

**Comment by aaronRancher** [comment]
Tested with Rancher `master-head` `version be7cdb8` with the following steps:
Install Rancher single cluster mode with:
```
docker run -it -d -p 80:80 -p 443:443 --restart unless-stopped --privileged rancher/rancher:master-head --features=multi-cluster-management=false
```
User is prompted to enter and set password. 
![Screen Shot 2021-07-23 at 11 21 46 AM](https://user-images.githubusercontent.com/57409052/126828076-6f8325c3-e33d-41b8-a606-16fd1070f67a.png)
![Screen Shot 2021-07-23 at 11 22 11 AM](https://user-images.githubusercontent.com/57409052/126826209-53c030cc-e0a7-41db-80a0-3b08cd309e69.png)
After setting password, user is taken to dashboard home page. User was not prompted for server-url.

Tested server-url prompt with the following steps:
In the same Rancher setup, log in as admin.
Enable MCM feature flag.
![Screen Shot 2021-07-23 at 11 29 37 AM](https://user-images.githubusercontent.com/57409052/126829150-8f391c3f-6628-4755-a9ba-61e1850f5ee8.png)
The user is prompted to set the server URL. User cannot activate the feature flag without first saving the URL.
