### ISSUE TITLE
Table rows with transitioningMessage in them have no dividing border

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#3288]
![image](https://user-images.githubusercontent.com/753917/122474064-86873d80-cf77-11eb-9c2c-eca42dd4a8ea.png)

There's no line separating rows below a row that has a transitioning message in it.

**Comment by thehejik** [comment]
**Test report:**
Fixed in `rancher/rancher:master-head c7f3cce`:
![bottom_lines](https://user-images.githubusercontent.com/12828077/123658355-f0360000-d831-11eb-844d-4784f1d2d42c.png)

Closing.
