### ISSUE TITLE
Add Node/Machine support to Cluster Management

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3291]
- For non-RKE2 
  - Use management node and management node pool types
  - Addresses rancher/dashboard#3016
- For RKE2 
  - Use provisioning machine and machine pool types
- List Nodes/Machines
  - Group by pools
  - Allow scaling nodes/machines in pools (addresses rancher/dashboard#493)
- Only basic provisioning/management related information should be displayed in list (explorer kube node list should be used to show running state/status of provisioned node - see rancher/dashboard#3290)
- For initial round of changes there will be NO custom view (detail) or edit pages for any of the four types (management node/node pool, machine/machine pool)

**Comment by sowmyav27** [comment]
**On master-head commit id: `e546ffe`**

Verified all the issues mentioned in the original issue's description separately.

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `2e6926b`**

- In cluster management page - there is no custom view (detail) or edit pages for nodes/machinepools
