### ISSUE TITLE
Don't show metrics that depend on kube metrics server when it's not available

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3292]
- Looks like we use a couple of stats that are dependent on the native metrics server (see node's list/details page cpu/ram charts)
  - NODE: 'metrics.k8s.io.nodemetrics',
  - POD:  'metrics.k8s.io.podmetrics',- 
- We shouldn't show these if the metrics server isn't set up
  - Tested locally with minikube (by default enabled, enable with minikube addons enable metrics-server)

**Comment by catherineluse** [comment]
@richard-cox I think this issue is fixed now, right?

**Comment by richard-cox** [comment]
No, `METRIC.NODE` is still intermittently used (some guarded, some not)

**Comment by nwmac** [comment]
@richard-cox I don't see any issues with `METRIC.NODE` - there are a few things not gated in the model, but I think the checks are made further up when they are used.

Going to close - re-open if you still think there is work to do.
