### ISSUE TITLE
cluster members: username for admin should be default admin. should not be empty

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3296]
Rancher Master-head 741adaf

1. Create a cluster with 1 node all roles. Once the cluster is active navigate to cluster explorer --> RBAC --> Cluster members
2. username for admin should be listed as Default Admin. it should not be empty.
<img width="200" alt="Screen Shot 2021-06-18 at 3 23 19 PM" src="https://user-images.githubusercontent.com/38144301/122620991-2d87da00-d049-11eb-9dac-43c7b3426c27.png">

**Comment by codyrancher** [comment]
@anupama2501 is this still something you can reproduce? Do you have any more details on reproducing? I'm not seeing this.
![image.png](https://zube.io/files/rancher/0a0d9df1cb5566d651a43e1eb60ab1e1-image.png)

**Comment by anupama2501** [comment]
@codyrancher 

On master-head 3e44415 

If logged in as a cluster member/cluster owner and navigate to RBAC --> cluster members, I still see the `Default Admin` missing for `Local`.
<img width="400" alt="Screen Shot 2021-07-06 at 10 43 59 AM" src="https://user-images.githubusercontent.com/38144301/124644493-550bde80-de60-11eb-9ea1-9fedd5855235.png">

**Comment by codyrancher** [comment]
@anupama2501 I'm still unable to reproduce this. Can you provide a cluster and account you see this with?

**Comment by anupama2501** [comment]
Verified on master-head 9e0d1b2 

`Default admin` is added to the local user in the latest master-head
