### ISSUE TITLE
Port/iFrame from Ember: CIS Scans v1

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#3298]
In light of recent UI consolidation, we need to ensure that pages from Ember aren't lost when accessing them via Vue.

CIS Scans v1

Ember location: <cluster> → Tools → CIS Scans

**Comment by nwmac** [comment]
This has been embedded in dashboard,.

When exploring a cluster, go to 'Legacy' in the side nav and select 'CIS Scans"

**Comment by kravciak** [comment]
Works fine on master-head (c1151f6).
I am able to run scans and see results.
Adding schedule worked as well.
