### ISSUE TITLE
Full cluster name is not seen on the dashboard in the cluster's context

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3301]
**On master-head commit id: `a11f9476`**

- Deploy a cluster with name `canal-pni-enabled-v2-test`
- When the cluster is Active, click on the cluster from Left panel to go to the cluster's context.
- On the top left the cluster name is displayed as `canal-pni-enabl...`
- On hovering on this, the full cluster name is not displayed
<img width="538" alt="Screen Shot 2021-06-19 at 7 32 53 PM" src="https://user-images.githubusercontent.com/26032343/122660359-c6941f00-d135-11eb-813d-63ce62649646.png">

Is there a way to show the cluster name on hovering on this? User does not know the cluster context user is on, as when user selects the cluster name from left panel, the cluster is not highlighted

**Comment by richard-cox** [comment]
This should already be the case. A tooltip containing the full name should be displayed in a similar way as the version at the bottom of the slide out side menu. The big difference though is that the cluster one will only display given a calculation on available space. @sowmyav27 could you confirm that the version tooltip works for you and the name/version of your browser?

**Comment by nwmac** [comment]
It should show on hover - there is a slight delay to prevent it popping up in the case that the user is moving the mouse up to the hamburger menu - so you need to hover the mouse over the name and about 0.5s later the tooltip will appear

**Comment by sowmyav27** [comment]
@richard-cox @nwmac I dont see the full name displayed, I had the mouse hover over the name for more than few seconds.
I am using Chrome browser - `Version 91.0.4472.114 `

**Comment by nwmac** [comment]
@sowmyav27 Can you check this again - I have reduced the delay and made is so you can hover over the icon or the name - note this ONLY happens IF the name is truncated. You will NOT see a tooltip unless the name is too long to display

**Comment by sowmyav27** [comment]
**Retested on master-head commit id: `e546ffe`**

- No tool tip is seen
<img width="522" alt="Screen Shot 2021-07-01 at 12 36 51 PM" src="https://user-images.githubusercontent.com/26032343/124180452-0f6aa280-da69-11eb-8baf-11e297cd7569.png">

Reopening the issue

**Comment by nwmac** [comment]
@sowmyav27 I can not reproduce this - it works for me and another team member:

![CPT2107021124-289x303 (2)](https://user-images.githubusercontent.com/1955897/124261263-7d29d380-db28-11eb-9054-514d8407b164.gif)

I am going to bump this to 2.6.x and we'll revisit then as I am at a loss to know why you aren't seeing the tooltip.

**Comment by sowmyav27** [comment]
@nwmac I see it work on master-head commit id: `1a218f5` _Only_ when i hover. If i click on the name and hover, it doesnt appear. I will log a new bug for that. 
<img width="314" alt="Screen Shot 2021-07-02 at 9 59 01 AM" src="https://user-images.githubusercontent.com/26032343/124307168-464dc080-db1c-11eb-9077-910b33a449c7.png">
