### ISSUE TITLE
Users with only Project member and read-only access should not have add users option in a project

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3305]
Rancher master-head version: 4d18400

1. Create an rke2 node driver cluster in the rancher server master-head with 1 worker, 1 etcd, 1 cp from cluster explorer.
2. Create two standard users user1 and user2 and once the cluster is active, create a project P1
3. Add the users, user1 as Project member and user2 as Read-only access users in the project P1 of the clusters from explore cluster --> project & namespaces -> Create Project --> Add 
4. Log in as user1 project member
 
**Result:**
- > navigate to explore cluster --> project & namespaces -> P1 --> view config, user has the option to add user. 
- > Click on add and add user1 as project owner, user is seen added as project owner in the members list but no request is sent in the API call  
- > If we refresh the page, user1 with project owner access will not be seen. Even if we log out and log in again as user1, only project member access is available to the user.
- > Although the user is not added as project owner, this option should not be provided to the users with project member and read-only access.
- > Same issue can be seen if we login as user2 with read-only permissions.

**Expected:**

Users with project members and read-only access should not be given the option to add users.

Screen shot for reference:

<img width="200" alt="Screen Shot 2021-06-21 at 3 20 40 PM" src="https://user-images.githubusercontent.com/38144301/122834923-6374ca80-d2a4-11eb-8991-9a2f98dea730.png">

Related issue: https://github.com/rancher/dashboard/issues/2673

**Comment by mantis-toboggan-md** [comment]
I'm unable to reproduce this issue; the 'view config' project action leads to a screen with no inputs. I think it was fixed specifically here, in this PR: https://github.com/rancher/dashboard/pull/3358

**Comment by anupama2501** [comment]
Verified on master-head 9e0d1b2

For project members and read-only access users, have only access to view config and not  edit config.
