### ISSUE TITLE
Prevent user from toggling the Multi-cluster Management feature flag

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3312]
This feature flag can only be set at install time and not changed afterwards.

We should prevent the user from modifying the feature flag in the UI and show a message or otherwise indicate that the flag can not be changed.

**Comment by thehejik** [comment]
Successfully tested here https://github.com/rancher/rancher/issues/33329#issuecomment-869591271

Anyway still don't know how can I disable the MCM flag at install time.

**Comment by mantis-toboggan-md** [comment]
There's a feature flag, `multi-cluster-management` that can be set to false during install: https://rancher.com/docs/rancher/v2.x/en/installation/resources/feature-flags/#enabling-features-when-starting-rancher
So for docker you'd append `--features=multi-cluster-management=false` to your `docker run` command

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head c7f3cce`

Action `Disable` is not available when the feature is enabled (default) and `No actions available` is shown instead in the list of flag actions.

But I could perform `Activate` when `--features=multi-cluster-management=false` was set at install time and the MCM feature  was activated once rancher restarted. This doesn't correspond to the summary.
![activate_mcm](https://user-images.githubusercontent.com/12828077/123670264-4f4d4200-d83d-11eb-815e-ddd5aec254b6.png)

Reopening.

**Comment by vincent99** [comment]
You are supposed to be able to turn it ON if it is currently off, but not turn it OFF one it has been on.

There's no functionality to clean the CRDs, decide what to do with existing clusters that are registered, etc, so it is a one-way street.

**Comment by thehejik** [comment]
Ok, I was unable to turn it OFF once it has been ON but was able to turn it ON when the feature was disabled at install time. This is considered as expected. Closing.
