### ISSUE TITLE
Deployment storage definition broken

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#3313]
1. Go to create a deployment
2. Storage -> Add Volume -> EBS, click the X to remove it, the entry comes back
3. Add Volume -> Bind mount, rename the Volume name, asplosion (_vm.updateMountNames is not a function)

**Comment by thehejik** [comment]
**Test report:**
Tested on `rancher/rancher:master-head cf5a75f`

* The EBS storage can be removed after clicking X and doesn't come back.
* Renaming of Bind-mount volume is possible when creating the deployment and also while Editing the current Deployment which is already using a bind-mount volume.

Close.
