### ISSUE TITLE
Login with Keycloak is still displayed after disabling Keycloak OIDC until browser refresh

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3319]
Rancher version: `2.6 master-head (06/22/2021)` _d44698d_

- Enable keycloak OIDC
- After a minute disable the auth
  - the user preference icon at the top right should still show the Principal username at this point.
- Logout from Rancher

The Login with Keycloak button is still available. There are two things I've noticed here.

1. Refreshing the browser now shows the local auth fields.
2. If with other browser that previously used the Rancher (has site cache) I try clicking  Login with Keycloak and I was able to Login.

Probably related to the follow-up issue that lists some of the pending fixes: https://github.com/rancher/rancher/issues/32920
I still wanted to track these with this UI issue in case there's something we need to check from UI

### Disable Keycloak OIDC

![Screen Shot 2021-06-22 at 3 47 32 PM](https://user-images.githubusercontent.com/27659/123010019-a56c4200-d372-11eb-83a0-0e6b8c9c585a.png)

### Logout redirects the user to login

![Screen Shot 2021-06-22 at 3 47 38 PM](https://user-images.githubusercontent.com/27659/123010101-c7fe5b00-d372-11eb-91b8-d02ef97533e8.png)

**Comment by richard-cox** [comment]
Could be the case we're not receiving the updated auth provider list when logged out. As mentioned there's some interesting changes in https://github.com/rancher/rancher/issues/32920 related to tokens which might effect the second issue. Will tackle once that's closed

**Comment by richard-cox** [comment]
I've tested with the latest backend changes. From what I can tell it's a race condition on when the user reaches the log in page and `v3-public/authProviders` providing the updated providers list. There's no watch, so if it's not there on page load we won't have it the enabled, or will still have the disabled, provider. There's not much the frontend can do on this one, @brendarearden is there anything possible in the backend?

On a similar note, I looked at fixing the user avatar after disabling the provider (which should switch back to the default admin) and it suffers from the same kind of thing. The client calls `v3/keyCloakOIDCConfigs/keycloakoidc?action=disable` and once completed we look for the `me` `v3/principal`. Which immediately after is still the keycloak one

**Comment by richard-cox** [comment]
Couldn't reproduce with the latest backend code

Logging out quickly after disabling the auth provider failed to show the 'log in with keycloak' button. Secondary window (different browser) open with keycloak button also worked as expected (ish, user could not log in however due to missing auth config 'redirectUrl').

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (08/02/2021)` _3499046_

I couldn't reproduce this issue on a newer Rancher build.
After disabling the Auth provider and logging out of Rancher I see the local user  login fields as expected
