### ISSUE TITLE
Going back button from dashboard to ember does not work

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3321]
There are two links to Explorer in cluster view:
 - cluster view -> `Cluster Explorer` link on the top navigation 
 - cluster view -> `Try out the Cluster Explorer` info box 

Those links point to `../dashboard/c/local` instead of `../dashboard/c/local/explorer`, which results in second redirect.
When use them to access explorer going back in browser navigation has random result, for example:
 - redirects to explorer home page
 - going back button is disabled
 - navigates to dashboard login page
 - navigates to random page in explorer

To reproduce:
On Ember UI, Global -> Custers -> local -> Click on `Cluster Explorer` of the top navigation
User is redirected to Dashboard page ( first dashboard/c/local then dashboard/c/local/explorer)
Click on back in the browser (can be clicked multiple times)

Tested on master-head (3dae3e2)

**Comment by vincent99** [comment]
Same as https://github.com/rancher/dashboard/issues/1635#issuecomment-866700821 ; you will not be able to go to the standalone ember pages on its own to get to these.

**Comment by kravciak** [comment]
I opened this issue based on https://github.com/rancher/dashboard/issues/1635#issuecomment-866083361
Please close if it won't get fixed / supported. Thanks.

**Comment by sowmyav27** [comment]
closing based on https://github.com/rancher/dashboard/issues/3321#issuecomment-866707371
