### ISSUE TITLE
vsphere create credential button is not clickable after entering all required fields

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3326]
![Screen Shot 2021-06-23 at 11 23 00 AM](https://user-images.githubusercontent.com/16691014/123157489-7233bc80-d41f-11eb-8b8a-8ffc19b891d1.png)

on master-head (d44698d)
* deploy a rancher setup
* go to create an rke2 vsphere cluster (cluster management -> create -> vsphere)
* enter valid information for the credentials
* create button is never clickable

**Comment by slickwarren** [comment]
this might be fixed by https://github.com/rancher/dashboard/issues/2969 once it is ready

**Comment by gaktive** [comment]
That's right; once @codyrancher has finished his work on vSphere provisioning, then this should be ready.

**Comment by slickwarren** [comment]
on master-head (d8824a1):
vsphere credential button is now clickable
