### ISSUE TITLE
RKE2 etcd Metrics without pre-selected radio button

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3331]
Under Dashboard in `rancher/rancher:master-head e756276` click `Create` a Custom RKE2 (or any other RKE2 cluster), switch to etcd pane and see `Metrics` section where are two radio buttons present but none is selected. 

Radio buttons should be used only when one of them is pre-selected as default one. If you select one of them you cannot return to the original state where none is selected.

![etcd_metrics](https://user-images.githubusercontent.com/12828077/123260986-7ed71400-d4f6-11eb-97f0-4324b450ec9f.png)

**Comment by gaktive** [comment]
Backend not providing UI with defaults, so we're not aware which one is the default. @gaktive to file a backend ticket requesting which one (likely the first one).

**Comment by gaktive** [comment]
Filed https://github.com/rancher/rancher/issues/33558 since I didn't see/find what I filed before.

**Comment by davidnuzik** [comment]
https://github.com/rancher/rancher/issues/33558#issuecomment-892887524

**Comment by deniseschannon** [comment]
Validated with v2.6-head at 8/4/2021 8:30 PM. Default is now automatically selected.

<img width="266" alt="Screen Shot 2021-08-04 at 8 29 32 PM" src="https://user-images.githubusercontent.com/11410997/128286500-7920b53e-5f78-4b6a-9128-187ee0d50bf5.png">
