### ISSUE TITLE
Don't show Registration command for already imported clusters

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3337]
Once the cluster is imported it's useless and also a bit dangerous to show the Registration command. User then may run the command by mistake on different cluster which would probably broke the current imported cluster.

Found in `rancher/rancher:master-head c7f3cce`

In Ember UI the reg. command is not available for already imported clusters.

![imported_reg_command](https://user-images.githubusercontent.com/12828077/123399857-68d45c80-d5a5-11eb-86da-113ae7400cc1.png)

**Comment by vincent99** [comment]
Now hidden if the cluster is "Ready" (which is the condition used to decide if you can navigate into the cluster for the rest of the UI).

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head ac7cef3`. 

The `Registration` tab with the registration command is not shown anymore once the cluster is imported.

Close.
