### ISSUE TITLE
Dashboard doesn't offer a kubernetes version dropdown for upgrade of imported RKE2 cluster contrary to Ember UI

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3338]
**Reproducer:**
* Deploy any local rancher cluster with `rancher/rancher:master-head c7f3cce`, RKE2 flag is `Active`
* Provision eg. one cluster VM/Node and deploy RKE2 on it by running `curl -sfL https://get.rke2.io | sh - && systemctl enable --now rke2-server.service` - with default values it will deploy RKE2 cluster with k8s `v1.20.8+rke2r1`
* Wait until the RKE2 node in the RKE2 cluster is reported as `Ready` in `kubectl get nodes` output
* Import the new RKE2 cluster over Dashboard by using `GLOBAL APPS/Cluster Management` and pressing button `Import Existing`
* Execute the offered reg. command on the node over ssh
* Once the cluster is Added into Rancher and `Active` click on "3 vertical dots" for the cluster and select `Edit Cluster`

**Result:**
There are no fields present for performing kubernetes upgrade contrary to Ember - also other fields are missing if you compare with Ember UI screen below - there are only Environment variables and Labels sections present.

This is how it looks for the very same cluster in Vue UI:
![dashboard_imported_rke2_upgrade](https://user-images.githubusercontent.com/12828077/123425124-06d62000-d5c2-11eb-9a3a-3ca7adc55a5a.png)

and the similar `Edit Cluster` action in Ember UI:
![ember_imported_rke2_upgrade](https://user-images.githubusercontent.com/12828077/123425292-44d34400-d5c2-11eb-8da2-43a0e4d3bc8e.png)

**Comment by thehejik** [comment]
Maybe related to https://github.com/rancher/dashboard/issues/3307 ~ imported RKE2 cluster from Vue doesn't belong to any Owner - but Ember is offering the k8s version to upgrade for the same cluster so I'm not sure

**Comment by gaktive** [comment]
@vincent99 to look at this once backend and product indicate what to do here.

**Comment by vincent99** [comment]
Imported clusters now go to the ember edit screen so this will work like it did before.  "Takeover" to more fully manage imported clusters that happen to be k3s/rke2 is not going into 2.6.0.

**Comment by kravciak** [comment]
Fix works fine on master-head (861fb92). When I edit imported rke2 cluster I can change kubernetes version.

![Screenshot from 2021-07-23 12-48-30](https://user-images.githubusercontent.com/538604/126771828-b438bc2b-f0c6-4be7-884e-68752a3c5f35.png)
