### ISSUE TITLE
Project management shouldn't show limited project owner roles

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#3343]
Rancher server master-head 4d18400

1. Create an rke2 node driver cluster in the rancher server master-head with 1 worker, 1 etcd, 1 cp from cluster explorer.
2. Create two standard users user1, user2, user3 and user4 and once the cluster is active, create a project P1
3. Add the users, user1 as Project owner, user2 as Project member, user3 as Read-only and user4 with custom `Manage workloads` access in the project P1 of the clusters from explore cluster --> project & namespaces -> Create Project --> Add

 **If we login as user4 with custom permissions `manage workloads`, from the project members user is displayed as `Project owner`**

- Log in as user4 and from the explore cluster --> Projects and namespaces --> Project P1 --> view config, members list has user4 as Project owner.

`Expected result:`

- user4 should not be displayed as project owner as the user has custom `Manage workloads` permissions.

**Comment by codyrancher** [comment]
I'm resolving this by only showing the members tab to users that have access to members. Specifically the resource to users that have access to the projectRoleTemplateBindings type.

**Comment by anupama2501** [comment]
Verified on master-head 9e0d1b2

- Added user as a project custom member with `Manage workloads`
- Logged in as that user and verified he cannot see the `members` in the project.

Note: Project members with custom access can see the resources they have permissions to, only if a namespace if created by the admin/PO/PM in the project.
