### ISSUE TITLE
if user visits multiple iframe pages, the iframed page will not load if user revisits any of those pages

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3347]
**on master-head (e756276):**
**issue:** when visiting an iframe page, user gets a 502 timeout

**how to repro:** 
* on rancher setup, go to `cluster management` page
* navigate to `rke1 configuration -> node templates` -> page will load as expected
* navigate to `rke1 configuration -> RKE templates`-> page will load as expected
*  navigate back to `rke1 configuration -> node templates` -> page will timeout

**workarounds:**
* if user navigates, for example `iframe -> vue -> iframe`, the page(s) will load fine
* hard reset & clear cache will also allow the original iframe page to load again

**Other Repros:**
* If user navigates, for example `iframe1 -> iframe2 -> iframe3 -> iframex `, the x page will not load, where x is the set of iframe pages already visited (1, 2, or 3)

**debug information:**
* this seems to happen to any iframe page
* the error below is only presented in some use cases, so may not be the root cause
error from console: 
```
Refused to apply style from 'https://<rancher_ip>/meta/proxy/https:/drivers.rancher.cn/node-driver-pinganyun/0.3.0/component.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by nwmac** [comment]
Can not reproduce - a change was made for another issue that may have resolved this - can you test again, please.

**Comment by slickwarren** [comment]
on master-head (d3ad5d3) I could not reproduce the issue
