### ISSUE TITLE
Incorrect number of workloads/pods displayed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3352]
**On master-head commit id: `c7f3cce`**

- From the namespace picker, select `Default project`
- Click on Apps and Martket place
- Installed Apps page is shown. 
- On the left navigation pane, Number of deployments, pods is seen > 0

<img width="765" alt="Screen Shot 2021-06-28 at 1 46 54 PM" src="https://user-images.githubusercontent.com/26032343/123702035-7c86f980-d817-11eb-8d23-c970a0863a68.png">

- Click on deployments
- The deployments, now shown are = 0
<img width="348" alt="Screen Shot 2021-06-28 at 1 47 08 PM" src="https://user-images.githubusercontent.com/26032343/123702111-96c0d780-d817-11eb-8b9c-845ef162d530.png">

**Expected:**
The actual value of deployments is 0 in this project. So the left pane should always show the right number of deployments/pods = 0

**Comment by gaktive** [comment]
Could be backend, @vincent99 could help confirm where the initial numbers are coming from.

**Comment by sowmyav27** [comment]
**On master-head commit id: `cfbd0d3`**

See this issue fixed.
<img width="726" alt="Screen Shot 2021-07-20 at 3 57 22 PM" src="https://user-images.githubusercontent.com/26032343/126405847-2fa83fe5-bf61-4e3b-9d2b-c2cb3c2c4a3f.png">
<img width="642" alt="Screen Shot 2021-07-20 at 3 56 16 PM" src="https://user-images.githubusercontent.com/26032343/126405849-a8c33ade-e06c-4e39-857a-4d5784db46a2.png">
