### ISSUE TITLE
Node count change in emberUI it won't show on dashboard node list until page refresh

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3355]
Node list is not updated until I refresh page. I can move around in left menu (workload, storage, node list).
When I refresh (f5) node list is updated.

 - in emberUI create DO managed cluster with 3 master 1 etcd 3 worker nodes
 - on second tab open Dashboard -> Cluster -> Nodes
 - in emberUI decrease master node pool size to 1 with `-`
 - in Dashboard tab open workload, then node list

Tested on master-head (c7f3cce)

**Comment by vincent99** [comment]
@richard-cox It looks like this has been around for a long time but the "[...var]" is making a copy of the list and therefore not "live" because the value given to the table is never changing.  https://github.com/rancher/dashboard/blob/master/list/node.vue#L173

**Comment by kravciak** [comment]
Fix does not work reliably - I would say it works 60%, mostly for worker nodes. For example:
 - adding / removing worker node works fine
 - adding / removing etcd / control nodes does not work reliably (not reflected on dashboard)
 - adding worker node sometimes updates (fixes) also etcd nodes ^ on node list

Node count on Dashboard -> cluster is updated properly, so sometimes it does not match what node list shows.

![Screenshot from 2021-07-08 14-19-44](https://user-images.githubusercontent.com/538604/124934285-dc925280-e004-11eb-9cf5-ea47dad8f9fe.png)
![Screenshot from 2021-07-08 14-17-25](https://user-images.githubusercontent.com/538604/124934351-e87e1480-e004-11eb-8dad-784a2fc89de6.png)

**Comment by richard-cox** [comment]
@kravciak There can be quite a large gap between scaling nodes and the change being reflected in the kube node resource list (machines have to be spun up and set up before the kube node resource is created). Could that be the case here?
Secondly the screenshot were taken in two different tabs running at the same time?

**Comment by kravciak** [comment]
> machines have to be spun up and set up before the kube node resource is created
I gave dashboard enough time to register new machines

> Secondly the screenshot were taken in two different tabs running at the same time?
It was one tab, changing between cluster view and node view (clicking around)

@richard-cox  I can recreate the setup and share it with you if it helps

**Comment by richard-cox** [comment]
I gave this a go using RKE2 DO and did see some super slow results (a Machine spent 8 minutes stuck on status 'Waiting for machine to be provisioned' before finally going away... which was quickly represented in the kube list).
I'll give another go with RKE1 however as we no longer officially support the older ember ui I'll try purely from those pages exposed by the dashboard

**Comment by catherineluse** [comment]
I'm closing this issue because the Ember UI is no longer maintained or supported.
