### ISSUE TITLE
Project members are not shown when any filter is added in the namespace picker

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3356]
**On rancher version: master-head 7a2fc74**

1. From explore cluster --> select any cluster even local cluster.
2. In the namespace picker filter select `Project: Default`
3. verify in the left hand navigation, cluster option will be not present and cluster option only appears when `All namespaces` option is set in the filter.

**Expected result:**
When `Project: Default` is selected, the cluster option with Project members should be listed in the left hand navigation. It should not be limited only to `All namespaces` filter.

### Screenshot for reference:

**When the filter is set to `All Namespaces`:**

<img width="200" alt="Screen Shot 2021-06-29 at 10 49 00 AM" src="https://user-images.githubusercontent.com/38144301/123819492-d21adf00-d8c7-11eb-9d34-4ac120ba3f06.png">

**When filter is set to `Project: Default`**
<img width="200" alt="Screen Shot 2021-06-29 at 10 49 19 AM" src="https://user-images.githubusercontent.com/38144301/123819550-dd6e0a80-d8c7-11eb-8454-aa95bc2e4b66.png">

**Comment by vincent99** [comment]
This is not related to project Menendez in particular... Cluster-level resources are all hidden when a namespace (or project) is selected because they can't belong to the selected namespace(s).

**Comment by gaktive** [comment]
Working as designed.

**Comment by anupama2501** [comment]
@vincent99  can we have an `info` button which gives a description to the users that the cluster level resources will be hidden when the namespace or project is selected?

**Comment by anupama2501** [comment]
Closing this issue as it is a `won't fix`
