### ISSUE TITLE
[Logging V2] Support multiple hosts in Elasticsearch output

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3363]
Currently, the logging Elasticsearch output form only supports the configuration of a single Elasticsearch host.

The Banzai Logging Operator also allows to configure multiple hosts: https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/elasticsearch/#elasticsearch-hosts.

Since the Elasticsearch client has loadbalancing built in, this safes you from running an extra Loadbalancer in front of your cluster (https://www.objectrocket.com/blog/elasticsearch/elasticsearch-and-load-balancers/). 
This is a common setup for highly available Elasticsearch clusters.

**Comment by MKlimuszka** [comment]
Closing based on comments in SURE-6508
