### ISSUE TITLE
Scale down option not available on selecting a node

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3366]
**On master-head commit id: `e546ffe`**

- Scale down and Scale up actions are available for RKE1 and DO RKE2 clusters - `Scale Down Pool` and `Scale Up Pool`
<img width="1664" alt="Screen Shot 2021-06-30 at 9 51 15 AM" src="https://user-images.githubusercontent.com/26032343/124000874-e541b380-d988-11eb-85ea-19fefda0627c.png">
- But when you select a node, `Scale Down` option is not presented. - For RKE1 or RKE2 clusters.
- In Ember UI this is available. This was an enhancement in 2.5.x
<img width="520" alt="Screen Shot 2021-06-30 at 9 49 21 AM" src="https://user-images.githubusercontent.com/26032343/124005467-f640f380-d98d-11eb-8e22-d5c6df33a766.png">

**Expected Result:**
- Scale down option should be presented when a node is selected in the cluster details page.

**Comment by richard-cox** [comment]
It looks like this is a norman Node action which removes that specific node from the node pool and is not replaced. I've had a look at the equivalents we use (`management.cattle.io.nodes` and `cluster.x-k8s.io.machines`) and there doesn't seem to be an something similar. I've tried manually deleting them however the pool will sale back up again. I'll check with the backend team if there's a replacement.

**Comment by richard-cox** [comment]
@kinarashah Please shout if there's any questions regarding the two resource types this will be used from

**Comment by gaktive** [comment]
This should be doable for RKE1 presently. Per @vincent99, this may work for RKE2 or not if we just copy the mechanism.

**Comment by richard-cox** [comment]
@kinarashah Was there an update on the backend changes required to support this on those two resource types?

**Comment by gaktive** [comment]
Kinara indicated that QA has seen more broken bits around scaling down: https://github.com/rancher/rancher/issues/32838

**Comment by deniseschannon** [comment]
I marked this as a release blocker as we are removing functionality that we specifically introduced for customers which allow selecting a node when scaling down.

**Comment by richard-cox** [comment]
If there is a norman/v3 node scale action we could use that. We would need to tie the norman node type to the management node type, but that would be doable.

**Comment by kinarashah** [comment]
@richard-cox Yep this won't be available for RKE2 nodes, but for RKE1 nodes, this is the same as how we show cordon and drain for Kube nodes currently. It's an action on v3 nodes norman type.

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `0ab00d7`**

- Scale down option is available in a node driver RKE1 cluster
- It is not available for an RKE2 cluster.
- But see the following issues

**Issue#1**
- Scale down option is enabled when there is only one node available in the nodepool

**Expected:**
It should be available when more than one node is available

**Issue#2**
- Can we have a `-` hypen/minus sign instead of an `x` for the scale down button?
<img width="627" alt="Screen Shot 2021-08-07 at 3 47 34 PM" src="https://user-images.githubusercontent.com/26032343/128615712-709a066e-d2db-4018-92d4-417542bc2825.png">


Reopening the issue

**Comment by richard-cox** [comment]
1) The icon in ember is `icon-arrow-circle-up icon-rotate-180`, might be worth using that one.
2) We should do this, in ember we use nodePool?.quantity > 1

**Comment by vincent99** [comment]
Scaling a pool down to zero is perfectly valid and has reasonable use cases, especially if there's more than one pool?

**Comment by richard-cox** [comment]
Sorry, understood. Scale down should be disabled on the last node only if there's one node pool.

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head c58f952`

- Scale down option is available in a node driver RKE1 cluster
- It is not available for an RKE2 cluster.
- Scale down button is not present when there is only pool with one/last node
- If there is more than one pool it can be scaled down to 0 nodes (valid)
- Icon has been updated
- The nodes are correctly removed from DO cloud when scaled down by using the Button

![scale_down1](https://user-images.githubusercontent.com/12828077/129232032-fd4b5eeb-cddf-42b8-ae92-e740dabeb4f2.png)
![scale_down2](https://user-images.githubusercontent.com/12828077/129232026-206097cd-934f-4c08-ae0d-a8b8d1d2607b.png)

Closing, works as expected.
