### ISSUE TITLE
RKE1 clusters have node pools in cluster dashboard --> nodes page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3367]
**On master-head commit id: `e546ffe`**

- Deploy an RKE2 cluster and an RKE1 DO Clusters from cluster explorer UI
- For RKE1 clusters - nodepools available in cluster dashboard - dashboard/c/<cluster-id>/explorer/node page
- For RKE2 cluster no nodepools are available.

**Expected:**
- Can we have nodepools for RKE2 also?
- Because Scale down nodes and node pools could be added too in this case to support the following:
```
- for drain/cordon, user has to go to the cluster dashboard --> nodes page
- for scale up and down, user has to go to the Cluster management --> cluster --> nodepools page.
```

**Comment by richard-cox** [comment]
The two lists represent different resource types and support different use cases. 
- The cluster explorer node list is to view the base kube node type regardless of cluster type and handles base kube concepts such as drain/cordon.
- The cluster management pool tabs show management node's (non-rke2) and machines (rke2) and for convenience handles life cycle actions such as scaling (the main place to scale pools is still by editing the cluster itself). 

The grouping of kube node's by management node pool for non-RKE2 clusters was added as the work was done on the journey to implementing the cluster management pool tabs. If any changes are made in that respect I'd vote to remove the grouping to remove complexity from this more basic view.

Scaling should only be shown where we show management nodes/machines as rancher creates that type well before it creates the kube node. Adding this to the kube node list would mean the user wouldn't see any change or know what went wrong if the node failed to come up.

In the old ember ui only one type of node was shown which handled all use cases. There wasn't a way to see the base kube node type and it doesn't handle rke2 clusters. Now we handle more types so had to move away from one uber node lists which we cannot return to.

**Comment by richard-cox** [comment]
Recently node pools for RKE1 clusters were removed from the cluster explorer node list, so there are now no type of pool shown on that page.

**Comment by sowmyav27** [comment]
**On master-head commit id: `4d41301`**

Kube nodes page do not have Nodepools.
