### ISSUE TITLE
Hold the Control key while clicking delete does not bypass confirmation

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3373]
There is a tip on confirmation dialog about how to skip confirmation
```
Tip: Hold the Control key while clicking delete to bypass this confirmation
```

Holding control key does not bypass confirmation as mentioned in the message

![Screenshot from 2021-07-01 15-51-07](https://user-images.githubusercontent.com/538604/124136272-e821ce80-da84-11eb-9331-02753b00f961.png)

To reproduce:
 - Open Dashboard -> Cluster -> Cluster Tools -> CIS Benchmark -> Install (for example)
 - Click trash can to uninstall CIS benchmark
 - There is a confirmation dialog with information how to skip it (by holding ctrl)
 - Click trash can (while holding ctrl)

Result: Dialog is not skipped when holding ctrl key and clicking trash

Tested on: master-head (c1151f6)
Tested browsers: Firefox 86.0.1, Chrome 91.0.4472.106

**Comment by richard-cox** [comment]
This is an issue with the generic PromptRemove modal for a resource. Either hide the message when the modal hasn't come from a standard list or implement the ctrl + click to skip concept everywhere this is used outside of lists

**Comment by kravciak** [comment]
Works fine:

Tested by:
- install cis-benchmark in dashboard DO infra provider cluster
- go to installed apps
- click delete button while holding ctrl - confirmation dialog is skipped
- click delete button without ctrl - confirmation is displayed

![Screenshot from 2021-07-14 15-49-58](https://user-images.githubusercontent.com/538604/125633895-64beeba2-2ecc-4d27-beef-5668a12b44fd.png)

Tested on:
- rancher master-head (8073489)
- google-chrome 91.0.4472.114
