### ISSUE TITLE
Harvester RKE1 node driver UI

### ISSUE THREAD

**Issue by yasker** [rancher/dashboard#3374]
This is created to track the Harvester Rancher integration UI work.

This will be done by the Harvester team. cc @guangbochen @WuJun2016 

- [x] RKE1 (Ember) UI for Harvester node driver
- [x] Cloud Credential v1 for Harvester node driver.

**Comment by yasker** [comment]
Example PR for cloud credential V1: https://github.com/rancher/rancher/pull/30571

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/ui/pull/4705
