### ISSUE TITLE
Harvester RKE2 node driver UI

### ISSUE THREAD

**Issue by yasker** [rancher/dashboard#3375]
This is created to track the Harvester Rancher integration UI work.

This will be done by the Harvester team. cc @guangbochen @WuJun2016 

- [x] RKE2 (Vue) UI for Harvester node driver
- [x] Cloud Credential v2 for Harvester node driver.

**Comment by guangbochen** [comment]
addressed via https://github.com/rancher/dashboard/pull/3348

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/861#issuecomment-885485785
