### ISSUE TITLE
 workload deployment import yaml issues

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3377]
Rancher server master-head c1151f6

Pre-req:
Create a node driver rke2 cluster 1 node all roles

Issue1:

- From explore cluster --> Workload deployments --> import yaml -->  read from file --> no preview is shown for the file that is imported before we import and create.

Issue2:

- If we import a file with errors, the import fails with an error but if we try to fix the errors in the file and read from file in the same session of import yaml, import fails with the same error.
- The file is imported successfully only if we close the existing session and start a new one.

Snippet of issue1 and issue2 :

https://user-images.githubusercontent.com/38144301/124195412-66d43700-da98-11eb-9700-1f3c0d7c6dfd.mov

**Comment by nwmac** [comment]
PR: https://github.com/rancher/dashboard/pull/3400

**Comment by anupama2501** [comment]
Verified on rancher master-head 01665d0

**Issue1:**

Preview of the file is shown while importing the yaml file

**Issue2:**
Importing yaml that has errors and importing a new yaml file in the same window is not errored out and import goes through successfully.
