### ISSUE TITLE
Single redeploy button for when all workloads are selected is needed

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3378]
Rancher server master-head c1151f6

- If we have multiple deployments in a project, a common re-deploy button is needed next to delete and download yaml.
- Currently `redeploy` button is only present for each individual workloads

**Comment by nwmac** [comment]
We'll think about this post 2.6

**Comment by kravciak** [comment]
I can redeploy Deployments and DeamonSets fine.
I can't redeploy CronJobs, either individually or multiple, created follow-up issue https://github.com/rancher/dashboard/issues/3835.


![Screenshot from 2021-08-13 09-13-52](https://user-images.githubusercontent.com/538604/129319084-49dd5059-d998-41be-bee9-71e7a5447bb7.png)

Tested on v2.6-head (4def656)
