### ISSUE TITLE
Mount point is not getting set while creating statefulSet or deployment

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#3379]
Kind : **Bug**

**Steps to reproduce**
1. Go to StatefulSet creation in form view.
2. Add a storage - Persistent volume claim.
3. Add a mount point.
4. Check in the Yaml, there is no `volumeMounts` present.
<img width="1513" alt="Screen Shot 2021-07-01 at 4 02 21 PM" src="https://user-images.githubusercontent.com/60111667/124198621-e0aef500-da85-11eb-88b8-ddd83904eb56.png">

**Expected Result**
The Yaml should have below value set 
```
volumeMounts:
  - mountPath: /data
     name: volume-name
```

**Env** :  Master - `c1151f6`

**Comment by nwmac** [comment]
I could not reproduce this - see video below

Can you update with more detailed steps to reproduce if you still see this.
 
![CPT2107071621-1159x791.gif](https://zube.io/files/rancher/caac7cbde12bb07bd689a5d391023804-cpt2107071621-1159x791.gif)

**Comment by khushboo-rancher** [comment]
Can't see the video, it says `content length exceeded` and I still see the problem with `cf5a75f` master. I've tried to explain the detailed repro steps below.

**Reproduction Steps:**
1. Create a cluster using the master-head
2. Deploy Longhorn app.
3. Create PVC using longhorn storage class.
4. Create a replicaset or statefulset using the PVC.
5. Add the mount point while creating the replicaSet/statefulSet.
6. Check the Yaml for the workload. It doesn't have the tag `volumeMounts`.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2021-07-07T23:05:17Z"
  generation: 1
  name: wk-1
  namespace: default
  resourceVersion: "18877"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/wk-1
  uid: f6d206d7-dbcc-4178-85ac-a42b45b48a7e
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.statefulset-default-wk-1
  serviceName: service-1
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.statefulset-default-wk-1
    spec:
      affinity: {}
      containers:
      - image: ubuntu
        imagePullPolicy: Always
        name: container-0
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol0
        persistentVolumeClaim:
          claimName: volume-test-1
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
```

The expected Yaml:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2021-07-07T23:05:17Z"
  generation: 1
  name: wk-1
  namespace: default
  resourceVersion: "18877"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/wk-1
  uid: f6d206d7-dbcc-4178-85ac-a42b45b48a7e
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.statefulset-default-wk-1
  serviceName: service-1
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.statefulset-default-wk-1
    spec:
      affinity: {}
      containers:
      - image: ubuntu
        imagePullPolicy: Always
        name: container-0
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: vol0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol0
        persistentVolumeClaim:
          claimName: volume-test-1
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
```

**Comment by nwmac** [comment]
Still struggling to reproduce this - here's my video of me doing this:

https://youtu.be/jEGuS2QULtk

Can you record and share a screencast of how you are hitting this issue - must be something subtle, so would be great to get precise view of what you're doing, so I can try again to reproduce. Thanks.

**Comment by khushboo-rancher** [comment]
Attaching the screen record with master-head `d3ad5d3`

https://user-images.githubusercontent.com/60111667/126241742-2ec621a9-2e55-42bb-9b43-51360fa54a32.mov

**Comment by khushboo-rancher** [comment]
Verified on v2.6-head - `ba95a58`

Validation - **Pass**

The mount point is getting added properly for deployment and statefulSet.
