### ISSUE TITLE
My Cluster Explorer and Apps&Marketplace become disconnected

### ISSUE THREAD

**Issue by bellship24** [rancher/dashboard#3380]
Hi, I'm touring rancher's feature nowadays. But I got in stuck.
It is happened to me that "My Cluster Explorer and Apps&Marketplace become disconnected".

For further explanation, I have added the details below.

<error phenom.>

- Apps & Marketplace is unavailable. and charts, installed apps, chart repositories, etc, they show nothing.
![image](https://user-images.githubusercontent.com/63495774/124225539-9770ab00-db42-11eb-8986-5678f1aa8217.png)

- when I click terminal icon in the upper right of Cluster Explorer, as you see below, my shell is disconnected
![image](https://user-images.githubusercontent.com/63495774/124225749-eddde980-db42-11eb-9d31-6df08cd8d643.png)

<Possible causes of errors  I think>

- my nodes in the rke cluster has internal IP and NAT IP.
- and I only can connect to the nodes by not internal IP but NAT IP.
- so, I can do anything without error in rancher dashboard including scheduling. see below.
    ![image](https://user-images.githubusercontent.com/63495774/124225992-5331da80-db43-11eb-8dc5-455395a56356.png)
- but, I can do nothing about internal IP. and I think that Cluster Explorer schedules pods about Apps&Marketplace using internal IP.

<Question>
- Can I get some architecture or network information about Apps&Marketplace's helm GUI?
Thanks to read! :)

**Comment by bellship24** [comment]
I found my trouble. It's just worker node's disk device got lost. haha :-)

**Comment by richard-cox** [comment]
@bellship24 It seems like you've determined the root error. If you're still seeing issues just let us know
