### ISSUE TITLE
Full cluster name is not seen on the dashboard in the cluster's context when you click on the cluster name and hover

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3383]
**On master-head commit id: `1a218f5`**

- Deploy a cluster with name canal-pni-enabled-v2-test
- When the cluster is Active, click on the cluster from Left panel to go to the cluster's context.
- On the top left the cluster name is displayed as canal-pni-enabl...
- Click on this name and then hover on it, the full cluster name is not displayed
- _Only_ when you hover without clicking, you see the full cluster name displayed.

Related issue that was fixed: https://github.com/rancher/dashboard/issues/3301

**Comment by nwmac** [comment]
@sowmyav27 Yeah - that's the behaviour at the moment - its a little more complicated to support the click and hover, so we'll look into that post 2.6 - for now, the user needs to hover over the name.

**Comment by nwmac** [comment]
Closing - we have moved the project/namespace filter, so the name is now shown in full, so this is no longer an issue.
