### ISSUE TITLE
Missing namespace in Related Resources

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3388]
The Related Resources lists are missing the namespace entries for namespaced resources.

![Bildschirmfoto 2021-07-05 um 16 13 30](https://user-images.githubusercontent.com/243056/124484852-3815d380-ddac-11eb-96c0-16e2537e9bd5.png)

![Bildschirmfoto 2021-07-05 um 16 42 38](https://user-images.githubusercontent.com/243056/124488427-1f0f2180-ddb0-11eb-9a36-e93b1043dee7.png)

**Comment by kravciak** [comment]
Fix works fine in master-head (5aa95f2)
![Screenshot from 2021-07-09 16-27-29](https://user-images.githubusercontent.com/538604/125093479-9e636480-e0d2-11eb-8384-b6f10f335a46.png)
![Screenshot from 2021-07-09 16-30-19](https://user-images.githubusercontent.com/538604/125093808-fbf7b100-e0d2-11eb-998c-90076c7ebf63.png)
