### ISSUE TITLE
Resources on Fleet / Continuous Delivery Git Repo page are not linked

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3390]
The resources on the Git Repo detail page in the Fleet / Continuous Delivery section are not linked. This makes it cumbersome to find out why for example Pods can't be started. Instead of clicking a link, you have to remember the cluster, namespace and resource name, navigate to the cluster explorer and then find the resource.

A direct link to the resource's detail page would be great.

![Bildschirmfoto 2021-07-05 um 17 56 28](https://user-images.githubusercontent.com/243056/124497094-a9f51980-ddba-11eb-9583-ff1ea8f9b577.png)

**Comment by kravciak** [comment]
Links work fine, but left-side menu is not opened to show current location. I assume this will be fixed as part of https://github.com/rancher/dashboard/pull/3395?

Please confirm, if yes we can close this issue.

**Comment by kravciak** [comment]
Confirmed that it should be fixed, closing
