### ISSUE TITLE
Missing nodes on Cluster detail page for RKE2 custom clusters

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3393]
The Cluster detail page shows an empty node/machine list for RKE2 custom clusters

![Bildschirmfoto 2021-07-06 um 12 28 42](https://user-images.githubusercontent.com/243056/124587338-cd21d680-de57-11eb-8cbc-f85485032602.png)

**Comment by davidnuzik** [comment]
Validation Passed:
master-head `24ab082`

1. Provision custom rke2 cluster
2. Register at least 1 node
3. Go to Machine Pools tab and the node will be shown.
![image.png](https://zube.io/files/rancher/35e5db01ea74df8f69152abc57bbeba9-image.png)
