### ISSUE TITLE
[V2 Provisioning] Race condition when importing existing cluster

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3398]
When you import an existing cluster, you are redirected to the cluster detail page in the 2nd step. Due to a race condition, this page often does not show the registration tab with the `kubectl apply` command.

Running the dashboard locally, I can even reproduce this 100% of the time.

![Bildschirmfoto 2021-07-06 um 12 00 40](https://user-images.githubusercontent.com/243056/124616421-57793300-de76-11eb-84e9-5ff93b6ece8e.png)

After you refreshed the page, the registration tab is visible.

![Bildschirmfoto 2021-07-06 um 12 00 57](https://user-images.githubusercontent.com/243056/124616447-5c3de700-de76-11eb-9451-2d79e32fd38d.png)

**Comment by kravciak** [comment]
Works fine on master-head (4d41301).
I created 10 imported clusters, all of them displayed registration commands properly.
