### ISSUE TITLE
aks v2 UI -  min and max count for "Enable Auto Scaling", should either have default values or should be made mandatory

### ISSUE THREAD

**Issue by prabalsharma** [rancher/dashboard#3412]
On enabling Auto Scaling in NPs, user might miss to set a min and max node count, which results in error

```Error failed to create cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="Required parameter agentPoolProfile.minCount is missing (null)." Target="agentPoolProfile.minCount"```

This can be avoided if there is a default value for min and max node counts **or** the field is made mandatory (when a user enables autoscaling) just like `DNS Prefix` and `Cluster Resource Group` .

Steps to repro:
1. Docker install master-3e44415
2. Create AKS cluster
3. Select `Enable Auto Scaling` (no not fill min and max node count)
4. Create

**Comment by gaktive** [comment]
@gaktive to check with backend if this can be populated; otherwise, we should default to Mandatory.

**Comment by gaktive** [comment]
For 2.6.0, this can be worked around. We should fix this in the next version, though this may require a change in UX since AKS has a conditional UI when autoscaling is enabled.

**Comment by valaparthvi** [comment]
Validated on Rancher(v2.9-a9355940c0629ca419b7dd3e4098c4ea0e52c0c0-head); Dashboard(master 46a44c1), it is fixed.

Default values for min and max count is set to 1 and 3 respectively when enabling auto-scaling.

[Screencast from 07-10-2024 03:27:01 PM.webm](https://github.com/rancher/dashboard/assets/11015077/86f9c5fe-8b21-4902-97bf-6237795ee992)
