### ISSUE TITLE
Project/Cluster Membership lists show system members

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#3413]
We sometimes show system members when lists membership on both projects and clusters.

 
![image](https://user-images.githubusercontent.com/55104481/124824403-2dcc1480-df27-11eb-9693-ed16de0908c4.png)

**Comment by richard-cox** [comment]
Hit another one of these today on a cluster
![image](https://user-images.githubusercontent.com/18697775/124925488-638aff00-dff4-11eb-981e-396dd0b41015.png)

On refresh i got the following, which was missing admin/cluster owner
![image](https://user-images.githubusercontent.com/18697775/124925576-7c93b000-dff4-11eb-9ba9-06b30bce9534.png)

**Comment by codyrancher** [comment]
I never managed to see this behavior in projects. So I'm going to re-title the issue.

**Comment by anupama2501** [comment]
Verified on master-head 01665d0

- From explore cluster --> project --> edit config no `system` members are seen
- From RBAC --> cluster members --> verified no system members are seen.
- Added user1 as a cluster member as well as project member and `system` is not seen in both pages
