### ISSUE TITLE
[Non-Admin Cluster Creation] Non-admin permissions based errors

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3416]
Container issue for bugs/funnies related to permissions handling for non-admins

Standard user (nothing else, no cluster membership)
- Side Nav
  - Empty 'Explore cluster' group is shown
  - Users & Authentication plus Global Settings both shown but clicking does nothing
- Cluster Management
  - ~unable to create a cluster~ rancher/dashboard#3719

Standard user, member of a single non-local cluster
- Global Settings
  - Advanced Settings - Action buttons shown with 'no actions available' text
  - Feature Flags - Action buttons shown with 'no actions available' text
  - Branding - Fields are editable, Apply button shown/enabled (submit fails)
- Legacy Apps
  - Multi-cluster Apps link is shown, but clicking on this attempts to fetch the local cluster, so we get a fail-whale page
- Cluster Management
  - ~Clusters - `Error: Unknown schema for type: management.cattle.io.nodetemplate` shown (should this type of user be able to see provisioning cluster/s? )~ rancher/dashboard#3719
  - ~Cloud Credentials - (dev) shows full page error `Cannot read property 'filter' of null`~ rancher/dashboard#3719

**Comment by richard-cox** [comment]
Worth reviewing https://rancher.com/docs/rancher/v2.x/en/admin-settings/rbac/global-permissions/

**Comment by richard-cox** [comment]
> Note - Most of these are low level bugs resolved by #3554. The Cluster Management section were blockers for creating a cluster, others have risen and been resolved. There's still on going work to finish this

**Comment by richard-cox** [comment]
I've removed the release blocker label as it pertains to #3719

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.6-head` `version 2778eca`. Tested the following use cases:

### Standard user (nothing else, no cluster membership)
- Side Nav
  - Empty 'Explore cluster' group is shown
    -  `Explore cluster` is not seen in side bar as standard user with membership to no clusters.
    ![Screen Shot 2021-08-18 at 5 03 44 PM](https://user-images.githubusercontent.com/57409052/129987329-989a1c4f-246c-4df2-a8bd-55be7dce4a2d.png)

  - Users & Authentication plus Global Settings both shown but clicking does nothing
    - Standard user is able to view Users & Authentication and Global Settings. Links take them to respective pages.
- Cluster Management
  - Standard user can create a downstream cluster. 

### Standard user, member of a single non-local cluster
- Global Settings
  - Advanced Settings - Action buttons shown with 'no actions available' text
    - No actions buttons are available
    ![Screen Shot 2021-08-18 at 5 17 19 PM](https://user-images.githubusercontent.com/57409052/129988252-a6385128-2c2c-4943-87b3-e853cdda1da5.png)
  - Feature Flags - Action buttons shown with 'no actions available' text (FAILED)
    - Actions buttons are still available with 'no actions available' text
    ![Screen Shot 2021-08-18 at 5 17 37 PM](https://user-images.githubusercontent.com/57409052/129988280-67b31b49-100f-47b0-9f2a-b8a42c283840.png)
  - Branding - Fields are editable, Apply button shown/enabled (submit fails) (FAILED)
  - Fields are not editable. 
  ![Screen Shot 2021-08-18 at 5 18 00 PM](https://user-images.githubusercontent.com/57409052/129988312-e2f9b6cf-93e5-4564-aa80-e5c3cde7272e.png)
  - No error is seen when standard user tries to apply branding.
  ![Screen Shot 2021-08-18 at 5 20 05 PM](https://user-images.githubusercontent.com/57409052/129989432-8d033fc8-8ecf-4dfc-82f3-b0821d456d63.png)
- Legacy Apps
  - Multi-cluster Apps link is shown, but clicking on this attempts to fetch the local cluster, so we get a fail-whale page
    - Standard user is able to access multi-cluster apps page.

Cluster management issues are resolved with the following:
- rancher/dashboard#3719

Reopening for the following fixes:
- Feature Flags - Action buttons shown with 'no actions available' text
- Branding - No error is seen when standard user tries to submit

**Comment by gaktive** [comment]
Easiest thing to do here is that non-admins shouldn't see this app.

**Comment by vincent99** [comment]
The Users & Global Settings nav items are now hidden if you can't write to the relevant resources.  If you're not an Admin / Manage Auth Configs / Manage Users / etc there's no reason to show you these pages.

**Comment by aaronRancher** [comment]
Master PR: https://github.com/rancher/dashboard/pull/3943
v2.6 PR: https://github.com/rancher/dashboard/pull/3944

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `b43e4d9`**

- Manage Auth Configs / Manage Users pages are not shown when logged in as a Standard User.
- Able to deploy an RKE `v1.21.3-rc7+rke2r2` DO 1 node all roles cluster successfully - Standard user.
