### ISSUE TITLE
Missing "SSH Shell" menu entry for RKE1 nodes deployed by cloud node drivers

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3419]
While testing https://github.com/rancher/dashboard/issues/3362 I noticed there is no `SSH Shell` menuentry for accessing RKE1 nodes deployed by cloud node drivers (eg. `Amazon EC2`) over SSH.

This is current state on `rancher/rancher:master-head cf5a75f`:
![ssh_private_key](https://user-images.githubusercontent.com/12828077/124915814-41907d00-dff2-11eb-8c16-13310dc53df8.png)

And this is how it looks for RKE2 nodes on Digital Ocean:
![rke2_ssh_shell](https://user-images.githubusercontent.com/12828077/124915954-697fe080-dff2-11eb-9bf3-f17675505420.png)

**Comment by nwmac** [comment]
@thehejik Is SSH Shell functionality available in the Ember UI for RKE1 clusters?

**Comment by vincent99** [comment]
No that is new for Vue/RKE2.  RKE1 should just have the download keys action.

**Comment by nwmac** [comment]
@thehejik This is as designed - RKE1 does not support SSH shell.

**Comment by thehejik** [comment]
Indeed, SSH Shell is not available in Ember UI for RKE1. Closing as invalid.
