### ISSUE TITLE
Namespace Links / Detail Page issues

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3422]
- In the project/namespace list need to convert namespace name to link to namespace detail page
- In namespace detail page need to remove `Move` action from action menu (retain for project/namespace view)
- The 'success' count for a newly created namespace is three, there no related resources shown. Need to understand what this count represents
- After editing the yaml of a namespace user is returned to the namespace list, rather than the project/namespace list

**Comment by thehejik** [comment]
Tested on downstream RKE1 cluster provisioned from `rancher/rancher:master-head 2e6926b` local cluster.

> * In the project/namespace list need to convert namespace name to link to namespace detail page

The links are shown and pointing to the ns detail page:
![ns_links](https://user-images.githubusercontent.com/12828077/127142456-649a1d52-1998-4c15-8eaa-2c2425be9264.png)

> * In namespace detail page need to remove `Move` action from action menu (retain for project/namespace view)

The `Move` action is still present on ns detail page and also present in project/namespace view but according to the PR #3489 it should be like that. Move action is working ok in both cases.

> * The 'success' count for a newly created namespace is three, there no related resources shown. Need to understand what this count represents

I don't see `success` count meter after creating a new namespace but I do see Resources grid and `Active` count for a new ns and the count is 8.
![ns_resources](https://user-images.githubusercontent.com/12828077/127149145-a72693f9-c334-486a-b164-59428130f12d.png)

This number (8) represents internal resources created and assingned within ns creation and consisting from 4 RoleBindings, 1 CM, 1 Resource Quota, 1 Secret and 1 Service Account - user can list them under `More Resources` menu for the cluster when the new ns is filtered out:
![active_resources](https://user-images.githubusercontent.com/12828077/127148890-c012f736-7afc-4553-a3b9-082c3b9ba8cb.png)

Although I would expect the resources will be shown in the ns detail page directly so I opened extra issue for that https://github.com/rancher/dashboard/issues/3545

> * After editing the yaml of a namespace user is returned to the namespace list, rather than the project/namespace list

User is returned to Project/Namespaces view after performing `Edit YAML` of the ns

Apart the empty list of resources in the namespace view for which I opened an extra issue https://github.com/rancher/dashboard/issues/3545 it works as expected. Close.
