### ISSUE TITLE
On deleting a cluster, it is removed from Cluster Management page, but is still seen in Home page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3423]
**On master-head commit id: `ac7cef3`**

- Deploy a custom RKE1 cluster - 3 etcd, 3 worker and 2 control plane nodes
- Delete the cluster from the Cluster management page
- the cluster is not listed in this page anymore.
- However on the Left slide in menu the cluster is available but disabled
- Also in Home page the cluster is seen in removing state
- Home Page:

<img width="1165" alt="Screen Shot 2021-07-08 at 7 05 55 AM" src="https://user-images.githubusercontent.com/26032343/124936372-569de980-dfbb-11eb-9778-fbf642340a3d.png">
- Cluster Management page

<img width="1664" alt="Screen Shot 2021-07-08 at 7 06 03 AM" src="https://user-images.githubusercontent.com/26032343/124936387-59004380-dfbb-11eb-87c9-afdd94b83aa3.png">

**Expected Result:**
It should be consistent everywhere

**Comment by gaktive** [comment]
@nwmac to check with @vincent99 about what to do here.

**Comment by gaktive** [comment]
This is expected since there are two mechanisms at play and the management side does take longer.

Perhaps we need a banner with a message indicating as such.

**Comment by catherineluse** [comment]
I think this issue is the same as this one https://github.com/rancher/dashboard/issues/4053

**Comment by gaktive** [comment]
@catherineluse so it appears, thanks for finding that! Marking as a duplicate and passing to QA to validate.

**Comment by sowmyav27** [comment]
closing this, as this issue isnt seen now
