### ISSUE TITLE
Delete option is enabled when local cluster is also selected in Cluster Management page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3424]
**On master-head, commit id: `ac7cef3`**

- Select Local cluster, delete option is not available
- Deploy a custom cluster.
- Select Custom cluster and then Local cluster
- Delete option is enabled.

**Expected:**
Delete option be disabled when local cluster is also selected.

However on Selecting Delete, and OK, Only the custom cluster is seen deleted.

**Comment by richard-cox** [comment]
Possibly related to #3353

**Comment by nwmac** [comment]
@sowmyav27 When you hover over the delete button, you should see 'Available for 1 of the 2 selected', as shown below.

This is as designed.

![image](https://user-images.githubusercontent.com/1955897/125098370-dcf72000-e0ce-11eb-9fd7-a8baca9aca6f.png)

**Comment by vincent99** [comment]
All actions work this way in Vue, the bulk buttons will apply to only the resources that they can be done on.  Rather than disabling the button entirely and you have no idea which row caused that, as Ember did.

**Comment by sowmyav27** [comment]
CLosing this issue based on above comments.
