### ISSUE TITLE
[V2 Provisioning] Support configuring HTTP(S)_PROXY and NO_PROXY for RKE2/ContainerD

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3426]
Currently it is not possible to configure the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables for RKE2 and RKE2's ContainerD when provisioning an RKE2 cluster from the dashboard.

Setting these variables is necessary in a lot of corporate environments, which are not completely air-gapped, but has internet access through a proxy. And RKE2's containerd should then also use this proxy to fetch images from external registries.

The Ember UI supported setting this in the engine options of each node template:

![Bildschirmfoto 2021-07-08 um 16 28 50](https://user-images.githubusercontent.com/243056/124940267-1f0a5e00-e00a-11eb-8a97-f7bf9fa04c03.png)

For RKE2 Provisioning this would also be necessary for custom clusters, because here the container runtime is shipped with RKE2 and is not installed by an admin beforehand.

**Comment by cloudnautique** [comment]
We should address this as a GA feature of RKE 2 provisioning.

**Comment by vincent99** [comment]
This is what Agent Environment Vars are for.

![image](https://user-images.githubusercontent.com/753917/129989156-d01f1a9b-c648-459d-8ebd-80ae8c8587ba.png)

**Comment by bashofmann** [comment]
I wasn't sure if there should be separate sets of environment variables for the agent and rke2/container runtime or not. At the moment the environment variables are only set on the agent.
This issue is tracked here https://github.com/rancher/rancher/issues/32602.
