### ISSUE TITLE
ClusterRepo generation mismatch error when refreshing a chart repository

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3427]
When you refresh a chart repository from the Apps Marketplace

![Bildschirmfoto 2021-07-08 um 16 37 41](https://user-images.githubusercontent.com/243056/124941269-fb93e300-e00a-11eb-8905-27445115609b.png)

the UI shows an error like `ClusterRepo generation is 5, but latest observed generation is 4` for a short time:

![Bildschirmfoto 2021-07-08 um 16 36 14](https://user-images.githubusercontent.com/243056/124941299-ff276a00-e00a-11eb-9e0a-e7826ca28218.png)

**Comment by nwmac** [comment]
@jordojordo This might be a tricky one - but first step is to verify and see if you can understand what is hapenning.

**Comment by vincent99** [comment]
This isn't red and isn't an error?  The way you trigger an update is by incrementing the `generation` field, and the status is just saying that the controller saw that and is updating.

**Comment by nwmac** [comment]
The phrasing of the status message  implies something is not correct. Agreed its not presented as an error. May be hard to fix as I assume this is a status message coming from the backend. If this is expected, not sure why we're showing a message at all.

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: c35f112`

Refreshing a repo via the `three dots > Refresh` and by selecting a repo (checkbox) and clicking the `Refresh` button no longer displays a message while the repo is being refreshed.
