### ISSUE TITLE
YamlEditor file diff now no longer shows diff

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3428]
- Go to Cluster --> Projects/Namespace --> 'Edit YAML' a namespace
- make a change (diff button becomes enabled)
- click diff button.. and there's no changes shown

Notes
- Loading from file does correctly show the diff
- This also affects helm chart install's yaml editor
- To avoid conflicts address after rancher/dashboard#3400

**Comment by sowmyav27** [comment]
Blocked by https://github.com/rancher/dashboard/issues/3500

**Comment by thehejik** [comment]
Successfully tested on `rancher/rancher:master-head cd623b5`. The diff is showing up after making change over `Edit YAML` action on the given NS. Both diff styles `Unified` and `Split` are working as expected.

![diff_ns](https://user-images.githubusercontent.com/12828077/126999956-4626c261-3cfb-4dec-9b9a-d30ced89e1d0.png)

Close
