### ISSUE TITLE
Unable to display / select last container from the list

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3447]
**Bug description**

I am not able to display / select last container from the list of containers.

![Screenshot from 2021-07-12 15-15-26](https://user-images.githubusercontent.com/538604/125304119-9a7f4e80-e32d-11eb-957d-a096f4fd249b.png)

**To reproduce**
 - create any (tested with custom rke2) cluster in dashboard
 - install logging
 - go to cluster -> Logging -> ClusterFlows -> Create
 - scroll to the bottom
 - select last container in `Limit to specific container names` menu

Current result:
 - last container that I can select with mouse is kube-controller-manager
 - I can select another containers using arrow on keyboard (blindly)

Expected result: I can scroll to the bottom to see all the available containers

**Environment**
docker single node
version: master-head (3ae6f43)

**Comment by gaktive** [comment]
@neillsom Timebox the investigation so that you understand what's wrong here and hopefully it's a simple fix. If not, then confirm that you can search for the term in limits and we can bump this out.

**Comment by deniseschannon** [comment]
Validated with v2.6-head 8/3/21.
