### ISSUE TITLE
Cannot create users when multi-cluster management is disabled

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3451]
- Create button is permanently disabled (probably due to now hidden global roles being invalid)
- Need to understand why global roles aren't shown, and if that's ok
- `--features=multi-cluster-management=false`

**Comment by davidnuzik** [comment]
**Reproduction Failed:**
Rancher version: master-head `4d41301d05e5128f3392c661a411322c7538a767` tagged 21 days ago, 2 days prior to pr merge
Cluster type: single-node docker
Docker version: 19.04

Reproduce steps:
1. Deploy Rancher with `--features=multi-cluster-management=false` flag set
2. Navigate to the Users & Authentication page /dashboard/c/local/auth/management.cattle.io.user
3. The "Create" button is blue and is NOT disabled. Perhaps I made a mistake in reproducing or my setup?

Additional Info (logs, etc):
Reproduction failed, I see the Create button on `4d41301d05e5128f3392c661a411322c7538a767` which is tagged 2 days older than when the PR was merged. Perhaps my environment or way I deployed Rancher is not correct?
![image](https://user-images.githubusercontent.com/45179589/127909572-262a7c8c-26b0-4b6b-bf6c-92dc2ab86b9d.png)

I did confirm the flag was passed into the server container:
```
2021/08/02 18:47:46 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features:multi-cluster-management=false}
```

I installed like this with single-node docker:
`docker run -v ~/state:/var/lib/rancher -d -p 80:80 -p 443:443 --restart=no --privileged rancher/rancher:master-4d41301d05e5128f3392c661a411322c7538a767-head --features=multi-cluster-management=false`

**Validation Successful:**
Rancher version: master-head `b39523882` 8/2/21
Cluster type: single-node docker
Docker version: 19.04

Validation steps:
1. Deploy Rancher with `--features=multi-cluster-management=false` flag set
2. Navigate to the Users & Authentication page /dashboard/c/local/auth/management.cattle.io.user
3. Confirmed that the "Create" button is NOT disabled. It is blue and I can click on it.
4. Create a simple user to ensure creation works as expected. It gets successfully created.
5. Log out of local admin user, login as this user I created. Confirmed I can log in. Confirmed my access is limited as expected.

Additional Info (logs, etc):
![image](https://user-images.githubusercontent.com/45179589/127907650-7e2dc2ff-f9e3-42b2-953c-80d47ddffd47.png)
