### ISSUE TITLE
Duplicates in Project List in Create Namespace

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3453]
- Seen when trying to create a namespace in a user generated project
- I can't remember seeing this in all scenarios, so have also included a screenshot of project/namespace set up

![image](https://user-images.githubusercontent.com/18697775/125463037-c4ba3d38-145e-4654-8d41-47aa67c577d7.png)

![image](https://user-images.githubusercontent.com/18697775/125463114-5072fd69-7596-4aa7-b166-ece1c605fd35.png)

**Comment by nwmac** [comment]
It is showing namespaces for all projects - need to filter for only the current cluster

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head 44bb5b4` with 2 downstream clusters, each with custom projects and namespaces.

The project drop-down menu now offers only projects from current cluster, there are no duplicates.
![projects](https://user-images.githubusercontent.com/12828077/125923851-c979ad3b-6f0d-43e5-882c-a19ca0b4de59.png)

Close.
