### ISSUE TITLE
Move namespace to project is broken

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3456]
Split out of rancher/dashboard#3422 

In project/namespace list clicking on Move gives the following error

```
   TypeError: Cannot read property 'shortId' of null
    at eval (MoveModal.vue?6f05:25)
```

**Comment by thehejik** [comment]
I was able to move a namespace from one project to another in Dashboard on downstream RKE cluster deployed on `rancher/rancher:master-head 44bb5b4`. Also in the drop-down menu only the relevant Projects are shown.

![move_ns](https://user-images.githubusercontent.com/12828077/125953606-08b0f1fb-a245-4b7e-bdc1-7cea67c4c0c4.png)


Close.
