### ISSUE TITLE
aksv2 - discrepancy in Azure CC, between ember and dashboard view

### ISSUE THREAD

**Issue by prabalsharma** [rancher/dashboard#3460]
This is on master-ad099ee

<img width="1299" alt="Screen Shot 2021-07-13 at 1 44 30 PM" src="https://user-images.githubusercontent.com/3749546/125522222-1f9911a4-78d0-4d53-97ca-3652d2833a9e.png">

V/S

<img width="949" alt="Screen Shot 2021-07-13 at 1 45 17 PM" src="https://user-images.githubusercontent.com/3749546/125522307-f282e0d4-9c60-48d3-9e85-2bee3b7a772d.png">

Mandatory fields are different, no idea that his Environment field is.

**Comment by prabalsharma** [comment]
If I ignore the Environment field and create CC, it is only visible when creating RKE cluster. For Azure Cluster creation, it does not show up in CC list.  
The workaround is to create Azure CC from Ember UI.

**Comment by gaktive** [comment]
There are two different types of cloud credentials here; the Dashboard/Vue one would create what's needed for Cluster Provisioning v2 (RKE2).

Perhaps we can add a banner to indicate what's required for the user. @nwmac to mull it over with @vincent99 to see for a long-term solution.

**Comment by gaktive** [comment]
Vue should be correct now, though we haven't merged Tenant ID yet.

**Comment by vincent99** [comment]
There's only one type now instead of two, though you can still get an ember vs vue screen of defining them.  Envorinment is not used by rke1 but works with rke2.  TenantId is redundant because it can be looked up from the subscription so we're no longer asking for it.

**Comment by cbron** [comment]
Test call exists now so no longer blocked by backend.

**Comment by vincent99** [comment]
I don't know what happened with zube labels but the ui was changed to call it yesterday

**Comment by prabalsharma** [comment]
LGTM
