### ISSUE TITLE
text box for deployment -> create -> container name only allows entry of 1 character at a time

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3461]
on master-head (ad099ee):

Repro Steps:
* go to deploy a workload (deployment -> create)
* enter any character in the `container name` field

Issue: 
text box only accepts 1 character. user can click back into the text box and continue entering characters. backspace also will kick user out of textbox after 1 backspace entry. copy/paste still works
window resets to image below (i.e. if user window is scrolled to the top of the page, upon entry of a character in `container name`, their window will scroll to the top of the `General` field)

<img width="519" alt="Screen Shot 2021-07-13 at 2 10 23 PM" src="https://user-images.githubusercontent.com/16691014/125525565-40f8cddc-7fa0-414a-9974-be70cd17b103.png">

**Comment by nwmac** [comment]
Duplicate of rancher/dashboard#3409

**Comment by slickwarren** [comment]
closing as duplicate
