### ISSUE TITLE
Enhancement: Missing whitespace in message

### ISSUE THREAD

**Issue by catastrophe-brandon** [rancher/dashboard#3463]
Rancher version: v2.5.8

Cluster Explorer -> Apps &  Marketplace -> Install JFrog artifactory-jcr

During installation a message is displayed: 

<img width="725" alt="Screen Shot 2021-07-13 at 5 52 40 PM" src="https://user-images.githubusercontent.com/20647751/125535387-aa864df8-729c-49d1-b271-2668e5b663ae.png">

Expected Result:
The message should have a space after the comma. E.g. `, but`

**Comment by neillsom** [comment]
Fixed in pr 2911

**Comment by catastrophe-brandon** [comment]
This fix was confirmed in master-head `9e0d1b2`.
