### ISSUE TITLE
Harvester Integration - Feature Flag Support

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#3465]
- [ ] Ability to show/hide the Harvester management page based on feature flag

**Comment by gaktive** [comment]
Corresponding backend work: https://github.com/rancher/rancher/issues/33605

**Comment by guangbochen** [comment]
The harvester team will work on the UI part integration once the backend feature flag is provided, for now we can using an existing one for implementation testing.
example PR reference:
- https://github.com/rancher/rancher/pull/32923/files
- https://github.com/rancher/rancher/pull/31560

**Comment by nwmac** [comment]
What is actually required here for the UI team to do? If Feature Flags are added to the backend, they will show up in the feature flags page in Global Setiings. Can you provide some more detail of what you need us to do.

**Comment by guangbochen** [comment]
So far this is all good and the harvester team will address this feature independently, once the feature flag is introduced, will need the rancher UI team to address the https://github.com/rancher/dashboard/issues/3467, thanks.

**Comment by nwmac** [comment]
@gunamata Can I close this issue, since there is nothing for UI to do?

**Comment by guangbochen** [comment]
sure, thanks
