### ISSUE TITLE
Deployment type icons missaligned

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3477]
- think this is a generic component, need to understand what broke it such that fix for this doesn't break that place
- ![image](https://user-images.githubusercontent.com/18697775/125760098-a67dbbc4-0256-4674-adb5-ee9144e29f4a.png)

**Comment by sowmyav27** [comment]
**On master-head commit id: `f33188d`**
<img width="1487" alt="Screen Shot 2021-07-18 at 9 31 33 PM" src="https://user-images.githubusercontent.com/26032343/126103175-99088b19-b8d5-4ae6-a0c5-e77501cd0cf8.png">
