### ISSUE TITLE
Resource search window doesn't show types

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3478]
![image](https://user-images.githubusercontent.com/18697775/125760287-c50a72b2-22a8-4442-ac88-3eb12483e4fc.png)

**Comment by sowmyav27** [comment]
**On master-head commit id: `f33188d`**
<img width="749" alt="Screen Shot 2021-07-18 at 9 30 24 PM" src="https://user-images.githubusercontent.com/26032343/126103091-a3ea294a-722e-4465-be76-e00029f76e72.png">
