### ISSUE TITLE
New OPA Gateway Constraints do not show up in table

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3479]
- After creating an new constraint user is taken back to the constraints table
- The new constraint only appears in table after refresh
- seen in 2.5.9 and 2.6

**Comment by nwmac** [comment]
Can not reproduce

**Comment by deniseschannon** [comment]
Unable to reproduce using master-head `b395238`. 

After new restraints are created, navigated to the constraint table which lists the new constraint.
