### ISSUE TITLE
aksv2- imported cluster showing system mode NPs as user mode NPs

### ISSUE THREAD

**Issue by prabalsharma** [rancher/dashboard#3486]
1. import AKS cluster with system mode NPs on master-8073489a3224599856e4adc48cfa04132262b077-head
2. System Mode NP will show up as User mode NP
<img width="1093" alt="Screen Shot 2021-07-15 at 2 54 58 PM" src="https://user-images.githubusercontent.com/3749546/125862867-04a07782-ac10-4c22-bc8a-f14b2e336f09.png">

upstreamSpec shows them as System Mode NP, as expected.

**Comment by codyrancher** [comment]
@prabalsharma are you still seeing this?

In the latest for me I'm seeing:
![image](https://user-images.githubusercontent.com/55104481/126566139-cf2d70e6-fb23-47fe-8875-6d020babad95.png)

**Comment by prabalsharma** [comment]
just checked on a1397b8
Looks fine, now.
