### ISSUE TITLE
Actions available on the cluster when it is still in provisioning state

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3490]
**On master-head commit id: `44bb5b4`**

- Deploy an RKE1 cluster from cluster Management page in Dashboard
- Actions are available on the cluster when it is still in provisioning state

<img width="1670" alt="Screen Shot 2021-07-16 at 9 03 25 AM" src="https://user-images.githubusercontent.com/26032343/125976622-42081149-b98a-4ccb-acba-ca4f9ae962c0.png">

**Expected:**
The top 5 actions are applicable only when the cluster is up and Active so they should not be available for user when it is still in provisioning state

**Comment by gaktive** [comment]
This should be a matter of adding a check for readiness.

**Comment by sowmyav27** [comment]
**On master-head commit id: `f33188df`**

- Action Download KubeConfig option is still available. Clicking on it when cluster is provisioning gives error: `{"baseType":"error","code":"ClusterUnavailable","message":"ClusterUnavailable 503: cluster not found","status":503,"type":"error"}`
<img width="1429" alt="Screen Shot 2021-07-19 at 9 16 24 PM" src="https://user-images.githubusercontent.com/26032343/126261284-ecd05438-e203-4a2f-9b4d-5fc6dbee9697.png">

Reopening - `Download KubeConfig` Option should not be available.

**Comment by catastrophe-brandon** [comment]
During provisioning I clicked on the "Download KubeConfig". It appears to have worked on the first try. During subsequent attempts I got un uncaught promise due to a Network Error. Commit `7738b25`.

**Comment by catastrophe-brandon** [comment]
For RKE1 this appears to be working as of `94bca99` (tested on DO and EC2). I'm unable to create an RKE2 cluster due to errors, but that appears to be out-of-scope for this issue.
