### ISSUE TITLE
2.6 AKS - Location should be uneditable for after AKSv1 cluster creation

### ISSUE THREAD

**Issue by prabalsharma** [rancher/dashboard#3493]
1. Deploy master-44bb5b4ea2bc4fec2cdd2d77954448aefa1975e7-head
2. Create AKS cluster --> then go to the URL bar and chop off 'v2' and it will give you the KEv1 interface (I did this in Ember UI)
3. Create a AKS v1 cluster
4. Once the cluster is Active --> Edit
5. User will be able to change location (Eg from East US to Central US, which is not possible in AKSv2)
6. Provide Azure Password
7. click Authenticate and Configure Nodes --> Save -->Cluster will go to Updating
8. Once the cluster become Active after Updating, Location will not change on Azure but will show up in API 

This will not generate any errors and is a "nice to have". Feel free to change milestone or reject it.

**Comment by catherineluse** [comment]
I'm closing this issue because the KEv1 interface is not maintained or supported.
