### ISSUE TITLE
[Cluster Creation] toggle-container rke-switch should read as "RKE2" not "RKE2/K3s"

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#3494]
master-head `24ab082`

K3s cluster provisioning won't land in v2.6.0, we should update the rke-switch such that it reads as RKE1 - RKE2 and remove the mention of "/K3s"

Actually technically it's RKE - RKE2 - should it read as RKE - RKE2 instead? "RKE1" isn't really a thing. It's an internal term we use to designate what is original RKE versus RKE2.

![image](https://user-images.githubusercontent.com/45179589/126012327-9b93cb7a-130d-4a27-bff0-e949f57befae.png)

**Comment by davidnuzik** [comment]
Interesting - I see K3s as an option like when creating custom clusters. Did we decide to add K3s support? I wasn't aware product management was asking for this:
![image](https://user-images.githubusercontent.com/45179589/126012877-364ec162-28c2-45f2-89c4-f04bf3c75650.png)

**Comment by davidnuzik** [comment]
cc for awareness on this: @cloudnautique @Oats87

**Comment by vincent99** [comment]
I don't know where the "landing" is, but It's been there for months.

**Comment by gaktive** [comment]
Based on discussion from others, we're sticking with the RKE2/K3s label.
