### ISSUE TITLE
"Error refreshing group memberships - Not Allowed" Error is seen when a standard user navigates to Users & Authentication --> Groups page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3496]
**On master-head commit id: `44bb5b4`**

- On dashboard, As a standard user navigate to Users & Authentication --> Groups page
- Error seen on UI

<img width="1074" alt="Screen Shot 2021-07-16 at 4 39 46 PM" src="https://user-images.githubusercontent.com/26032343/126018085-7094a33b-e5c2-4f9d-b012-e74a7744c6c5.png">

- API request has Post on `https://<server>/v3/users?action=refreshauthprovideraccess` happens with error: `{"baseType":"error","code":"ServerError","message":"Not Allowed","status":500,"type":"error"}`

**Expected:**
This API call should not be made when user navigates to that page.

**Comment by gaktive** [comment]
For non-admins, yeah, we shouldn't be doing this.

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.6-head` `version 222dced` with the following steps:
On dashboard, As a standard user navigate to Users & Authentication --> Groups page

No error is seen in UI:
![Screen Shot 2021-08-04 at 4 08 22 PM](https://user-images.githubusercontent.com/57409052/128267551-48db1e7f-724b-4d33-b14d-49aa7da91c6e.png)
API request `https://<server>/v3/users?action=refreshauthprovideraccess` is not seen when standard user navigates to Groups page. 
The `Refresh Groups Membership` button is not available to standard user.
