### ISSUE TITLE
Ember Ui is misaligned

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3499]
Upgrade from 2.5.9 to master-head `f33188df3` or on a rancher backup restore, Ember UI is misaligned
<img width="1293" alt="Screen Shot 2021-07-18 at 7 46 50 PM" src="https://user-images.githubusercontent.com/26032343/126095538-0069b519-2dee-4a67-83cb-2adcb08e2214.png">
<img width="1299" alt="Screen Shot 2021-07-18 at 7 45 28 PM" src="https://user-images.githubusercontent.com/26032343/126095542-9636ae15-f081-42e2-b001-7287d439d094.png">

**Comment by richard-cox** [comment]
Pages have been updated to improve how they visually fit in when embedded in the dashboard. As per comment in https://github.com/rancher/dashboard/issues/3497#issuecomment-882354388 we don't officially support a way to access them outside this process

**Comment by sowmyav27** [comment]
On an upgrade usecase, if the user is already int he Ember UI, user will be redirected to Ember UI only, right after upgrade. And i feel is really a bug that could have some fixes.

**Comment by richard-cox** [comment]
> On an upgrade usecase, if the user is already in the Ember UI, user will be redirected to Ember UI only, right after upgrade. And i feel is really a bug that could have some fixes.

@sowmyav27  I'm unfamiliar with the upgrade flow but from my understanding it's executed outside of the UI? If so then I think the issue here is that anyone already logged in to the Ember UI is still there post upgrade. We should instead redirect them to the dashboard in such cases.

**Comment by vincent99** [comment]
Yes the update is out-of-band.

I'm not sure how you'd do that other than unconditionally redirecting when not iframed ..which removes the escape hatch to get back to Ember / seems heavy-handed.

**Comment by sowmyav27** [comment]
This page is not about iframe. In fact the two I see the problems are in the cluster list page and API tokens page, both not iFramed. For upgrade this UI would be important. I still think we need to fix this.

**Comment by vincent99** [comment]
We're aware that you're looking at them directly, but the point is we mainly care about ember pages that are visible via iframes in Vue, which these aren't.

Going straight to Ember is not a normal supported path anymore.

**Comment by gaktive** [comment]
@sowmyav27 we'll mark this as "won't fix" based on our focus on iFrames of Ember for 2.6 and going forward. If the upgrade scenario needs to be considered, we can discuss with Jono.

**Comment by sowmyav27** [comment]
Closing this based on https://github.com/rancher/dashboard/issues/3499#issuecomment-885348039 and https://github.com/rancher/dashboard/issues/3499#issuecomment-888482949
