### ISSUE TITLE
Fleet Cluster Detail/Edit Pages Fail due to incorrect management cluster id

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3502]
- Resource type `fleet.cattle.io.cluster`, Detail & Edit Pages
- Both pages request management cluster using wordy name as the id rather than rancher id (`my-cluster` vs `c-m-88228df3`)

**Comment by anupama2501** [comment]
Verified on v2.6-head ba95a58

1. Created two clusters 
2. Verified From continuous delivery --> clusters [fleet-default in namespace picker], in the cluster details are shown for any git repos.
3. Verified if edited, the cluster displays labels, annotations. Added labels and it works as expected. 
<img width="400" alt="Screen Shot 2021-08-06 at 10 09 53 AM" src="https://user-images.githubusercontent.com/38144301/128547611-36a53c46-f395-4731-8efb-03affe547e63.png">
