### ISSUE TITLE
No content in Fleet Cluster `Config` page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3503]
- blocked on rancher/dashboard#3502
- When config is is view mode there's nothing shown (v-if'd out). Should be able to show these but with the correct 'view' mode

**Comment by nwmac** [comment]
@richard-cox I don't think this is an issue any longer - can you verify quickly and update the issue accodingly?

**Comment by richard-cox** [comment]
Couldn't reproduce in master, the 'view' version of the edit config page is correctly shown

![image](https://user-images.githubusercontent.com/18697775/146541774-667e3e09-cf3d-4ec1-87a9-215dbf96b495.png)

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID cd3c9d7`
1. installed downstream cluster
2. navigated to continuous delivery > Clusters
3. Verified downstream cluster had values in fleet-default workspace

![Screen Shot 2022-01-12 at 1.30.57 PM.png](https://zube.io/files/rancher/5bcd874d1511eb6b922903774d0fb76c-screen-shot-2022-01-12-at-1-30-57-pm.png)
