### ISSUE TITLE
OPA Gatekeeper: Can't select a namespace when creating a constraint

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3505]
Install OPA Gatekeeper

Go to Constraints, click  create, select either type and enter a name.

Click on the namespaces dropdown and select one - you get an indexOf null error page.

**Comment by davidnuzik** [comment]
**Reproduction:**
Not required.

**Validation Successful:**
Rancher version: master-head `b39523882` 8/2/21
Cluster type: single-node docker
Docker version: 19.03

Validation steps:
1. Install rancher server
2. Create a downstream cluster, in my case a 1-node digital ocean cluster with sufficient resources for OPA Gatekeeper
3. Install OPA Gatekeeper
4. Go to OPA Gatekeeper -> Constraints
5. Pick either option, create a name for the constraint, now -- pick a namespace. This worked without any issues and no errors in the browser dev console.
6. Click create. The constraint is successfully created.
