### ISSUE TITLE
Missing view for InitContainers

### ISSUE THREAD

**Issue by gonrial** [rancher/dashboard#3508]
If you access a Pod that has initContainers. It's not listed in the containers tab and in the logs only those containers are listed. Useful to debug issues when initContainers fail.

**Comment by zhuyumi** [comment]
Was want to fire an issue but see this same one.
100% agree. In K9S when you view log for a pod, it will show all the containers log including the init containers, not only the currently running container.

I'm on Rancher 2.5.5, cannot find a way from the UI to see the log from the init containers at all. Or there is a way but I missed?
