### ISSUE TITLE
Drop-down for Cluster list needs new component and design

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#351]
Current drop-down is actually a tooltip.  Would like a custom component that make the list of cluster look more like a drop-down.
Current:
![image](https://user-images.githubusercontent.com/11514927/76031649-55573b00-5ef5-11ea-858f-906f93fd2f7f.png)

New one should look more like the Namespaces drop-down
![image](https://user-images.githubusercontent.com/11514927/76032161-81bf8700-5ef6-11ea-913c-33cd387a62c3.png)

**Comment by lvuch** [comment]
@vincent99 can you change this from a tooltip to a dropdown?

**Comment by tfiduccia** [comment]
Fixed
