### ISSUE TITLE
Issues with left navigation bar in a cluster's context

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3512]
**On master-head commit id: `d3ad5d3`**

- Deploy a downstream cluster --> Dashboard --> go to cluster's context
- Click on Apps and MarketPlace
- The dropdown of it shows and then closes, user is navigated to Charts
- Click on Storage
- The dropdown of it shows

**Expected:**
When we click on Apps and Market place or any folder/Title , can we expand and show the sub headings in it and not close right away

**Comment by gaktive** [comment]
@sowmyav27 we can't repro this. Can you try again and post a video?

**Comment by rak-phillip** [comment]
This seems to only happen on the first time when running the dashboard. I was able to reproduce in my dev environment, first by clearing my cache with a hard refresh (cmd + shift + R) and then following the steps to reproduce. I attached an example of the behavior I saw.

![Kapture 2021-07-28 at 11 04 26](https://user-images.githubusercontent.com/835961/127373694-83ef114e-b5c6-400c-b9c2-169efe3a442d.gif)

**Comment by deniseschannon** [comment]
I consistently see this when I go to a downstream cluster detailed view and the first link I press on the sidebar is the "Apps & Marketplace". In the console, there are 404s for when retrieving certain charts. 


```
GET https://<SERVER_URL>/k8s/clusters/c-m-44c76ede/v1/catalog.cattle.io.clusterrepos/rancher-charts?chartName=rancher-alerting-drivers&link=icon&version=100.0.0 
GET https://<SERVERL_URL>/k8s/clusters/c-m-44c76ede/v1/catalog.cattle.io.clusterrepos/rancher-charts?chartName=sriov&link=icon&version=0.1.1%2Bup0.1.0
rancher-partner-charts:1 
GET https:/<SERVERL_URL>/k8s/clusters/c-m-44c76ede/v1/catalog.cattle.io.clusterrepos/rancher-partner-charts?chartName=control-agent&link=icon&version=2.0.100
GET https://<SERVERL_URL>/k8s/clusters/c-m-44c76ede/v1/catalog.cattle.io.clusterrepos/rancher-partner-charts?chartName=cost-analyzer&link=icon&version=1.70.000
```

**Comment by deniseschannon** [comment]
At first glance at this link, it would indicate that the 404 is cause of the icon, but in the Rancher charts, there are 3 charts that have no icons. 

Alerting Drivers
External IP Webhook
SRIOV

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `ba95a58`**
The original issue is seen fixed - https://github.com/rancher/dashboard/issues/3512#issue-948726943
