### ISSUE TITLE
AKSv2 UI - Kubernetes dropdown is not visible in dark mode

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3514]
**On master-head commit id: `8a60508`**

Kubernetes dropdown dropdown is not visible in dark mode
<img width="1410" alt="Screen Shot 2021-07-20 at 8 21 45 AM" src="https://user-images.githubusercontent.com/26032343/126351173-95c41316-fb43-4c0a-ba57-dabef7a09a9d.png">

Light mode
<img width="1417" alt="Screen Shot 2021-07-20 at 8 24 06 AM" src="https://user-images.githubusercontent.com/26032343/126351193-52a0f62d-b958-4af3-aa2e-0243b9ff338d.png">

**Comment by neillsom** [comment]
This appears to be specific to ember/ui and not relevant to 2.6. Please let me know if I'm mistaken

**Comment by neillsom** [comment]
Seems to be fixed

**Comment by richard-cox** [comment]
I could still see this issue in `release-2.6` and `master` of cluster manager (don't think that's branched yet). Looks like some drop downs in dark mode don't contain a border

(all see on the edit config page for an RKE1 cluster)

![image](https://user-images.githubusercontent.com/18697775/128003436-28eed35b-35b9-4c8f-82b1-47e8b7b66a33.png)

![image](https://user-images.githubusercontent.com/18697775/128003485-3af35e3e-bfa8-4f47-8256-f37c81e54504.png)

There are some where this doesn't happen though (same page)

![image](https://user-images.githubusercontent.com/18697775/128003549-770f1d30-d0d1-4e90-9488-ffd05afad567.png)

@lvuch Could you provide some assistance?

**Comment by neillsom** [comment]
Fixed by PR [#4725](https://github.com/rancher/ui/pull/4725)

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head b2a2948` and `v2.6-head 4def656`

The dropdown with kubernetes version for an AKS cluster looks good to me. Closing.
![aks_kubernetes](https://user-images.githubusercontent.com/12828077/129337839-0b1cbd8a-0009-412a-b959-a7b763601219.png)

But there are still some input boxes without value set just with placeholder/hint text and they look very similar to fields with default value set. Opened https://github.com/rancher/dashboard/issues/3837
