### ISSUE TITLE
AKS v2 cluster is not available in Cluster Management page when in Provisioning state but is available in Home page and on the panel on the left

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3515]
**On master-head commit id: `8a60508`**
- AKS v2 cluster is not available in Cluster Management page when in Provisioning state but is available in Home page and on the panel on the left
- Cluster Management page and the side panel:
<img width="1170" alt="Screen Shot 2021-07-20 at 8 25 12 AM" src="https://user-images.githubusercontent.com/26032343/126351631-a1f72b93-5002-4411-b7c6-a7995121afef.png">
- Home page:
<img width="1172" alt="Screen Shot 2021-07-20 at 8 26 24 AM" src="https://user-images.githubusercontent.com/26032343/126351636-63c75f67-e832-4c50-9715-49dfa0ae5a04.png">

**Comment by codyrancher** [comment]
Are you still able to reproduce this issue? I was able to see the pending aks cluster on both the home page and cluster management pages.

![image](https://user-images.githubusercontent.com/55104481/126566517-85c9685f-0c1d-4d6e-bce4-157a89a5c611.png)

**Comment by sowmyav27** [comment]
**On master-head commit id: `9e0d1b2`**

I dont see this issue anymore.
