### ISSUE TITLE
[KeyCloak OIDC] Username and Password Field

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#3516]
To resolve https://github.com/rancher/rancher/issues/33337 I have added a Username and a Password field to the oidc config. 

These will need to be present in the UI for Keycloak OIDC so that an Admin level user can insert their credentials on auth provider setup - those credentials will then be used to get nested group information for users logging in. The fields are not required, but they are required if you want nested groups to work properly. 

This also means you might not need to prompt the user that is setting up the auth provider to login, if you can pass along the username and password they entered into the config page but ultimately that is up to you. Acitve Directory, LDAP and Google have similar setups for an "Admin" if you need examples.  

```
type OIDCConfig struct {
	AuthConfig `json:",inline" mapstructure:",squash"`

	ClientID               string `json:"clientId" norman:"required"`
	ClientSecret           string `json:"clientSecret,omitempty" norman:"required,type=password"`
	AdminAccountUsername string `json:"adminAccountUsername,omitempty"`
	AdminAccountPassword string `json:"adminAccountPassword,omitempty" norman:"type=password"`
	Scopes                 string `json:"scope", norman:"required,notnullable"`
	AuthEndpoint           string `json:"authEndpoint,omitempty" norman:"required,notnullable"`
	Issuer                 string `json:"issuer" norman:"required,notnullable"`
	Certificate            string `json:"certificate,omitempty"`
	PrivateKey             string `json:"privateKey" norman:"type=password"`
	RancherURL             string `json:"rancherUrl" norman:"required,notnullable"`
}
```

**Comment by vincent99** [comment]
The service account user/pass should be an explicitly and very clearly labeled separate field from the "test" user (like it is in AD)..

You don't want to automatically reuse the user's credentials as the service account that's going to be used by Rancher forever (or even offer the option, if you want that you should explicitly type them in twice).  That person could change their password or be quit tomorrow.

**Comment by richard-cox** [comment]
As discussed with Brenda, these changes are now no longer required
