### ISSUE TITLE
local cluster is not hidden on ember UI when the flag `CATTLE_HIDE_LOCAL_CLUSTER` is passed as env variable in helm install

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3519]
On master-head f33188d

Helm: v3.3.4
rancher chart: v2.5.9

- Install rancher via helm by passing `CATTLE_HIDE_LOCAL_CLUSTER=true`

helm install rancher rancher-latest/rancher --namespace cattle-system
--set hostname=XXXX
--set-string extraEnv[0].name=CATTLE_HIDE_LOCAL_CLUSTER
--set-string extraEnv[0].value=true

- Deployment succeeds
- On the ember UI, local cluster is hidden but from dashboard it is still visible.

<img width="300" alt="Screen Shot 2021-07-19 at 9 00 04 AM" src="https://user-images.githubusercontent.com/38144301/126190888-cd807cea-df9e-40ec-abf9-1f735bd1a7cc.png">

**Expected Result:**

Local cluster should have been hidden from the dashboard UI as well in the cluster management and explore cluster page.

Ref ticket : https://github.com/rancher/rancher/issues/29325
https://github.com/rancher/rancher/issues/31109

**Comment by gaktive** [comment]
According to @vincent99, this should be hidden with later changes. @anupama2501 are you seeing this on any of the 2.6 builds?

**Comment by vincent99** [comment]
The dashboard UI does not look at or do anything with this setting.  But in 2.6 Restricted Admins do not have RBAC to see the local cluster, which has the same effect as this flag (for Hosted, which this was added for).

**Comment by anupama2501** [comment]
closing the issue as on master-head `861fb92`, if we login as a restricted admin the local cluster is hidden.
