### ISSUE TITLE
Arrow keys are acting different for different components on same page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#352]
The > icons means different things depending on where or what component your in.  We should be consistent on what directions we are using and what they mean.  Currently:

1.  The one for the cluster list doesn't work and is always facing >
2.  For Namespace control, ^ means open and v means closed
3.  For Left Navigation, v means open and > means closed.

![image](https://user-images.githubusercontent.com/11514927/76032255-b92e3380-5ef6-11ea-97cd-cc39c9354deb.png)

**Comment by lvuch** [comment]
v should closed, ^ should be open hinting at what direction next action will be.

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/365 fixed but cluster dropdown needs to function @vincent99

**Comment by tfiduccia** [comment]
Fixed
