### ISSUE TITLE
Whitespace causing issues in credential and login fields -> we should strip whitespace for applicable fields

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3526]
on master-head (b6bcfad)

Repro steps:
Case 1: cluster credentials
* create a cluster with new credentials (vsphere cluster, rke2)
  * in the datacenter field, add a space to the beginning or end of the field
  * proceed with other valid credentials
  * save the credential (saving bad credential is working -> unexpected)

Issue:
* `422 error: invalid body content` 
![Screen Shot 2021-07-21 at 10 11 26 AM](https://user-images.githubusercontent.com/16691014/126535049-c5fcf347-81c8-4c8a-9e3e-dd5d12931af1.png)

* for vsphere, this is not caught in our UI (error above is from the console). We just show spinning icons for each of the data fields indefinitely
![Screen Shot 2021-07-21 at 10 42 18 AM](https://user-images.githubusercontent.com/16691014/126534914-48fff751-a926-4181-8535-532ad4c214ca.png)

Other related issues/helpful information:
Case 2: aws cluster credentials -> error caught before allowing user to save bad credential
* create a cluster with new credentials (vsphere cluster, rke2)
  * in the datacenter field, add a space to the beginning or end of the field
  * proceed with other valid credentials
  * save the credential 

Case 3: login/new users
* create a new user named ` testuser ` (with a space at the beginning and/or end of the username)
* enter valid password
* try to login as this user -> **whitespace was stripped from user upon creation in this case** but not in the above cases, therefore user must sign in without spaces in their username (i.e. logging in with spaces trailing/leading username does not work, but usrname without spaces allows user to log in)

**Comment by gaktive** [comment]
Per @vincent99, some fields may need a `.trim` added so that it knows to watch for whitespace.

**Comment by codyrancher** [comment]
In this we won't be doing any trimming or removal of whitespace here. We will be performing authentication and we will error out if we're unable to authenticate.

**Comment by slickwarren** [comment]
on 2.6-head (723f747): 
* login still has issues related to whitespace (see **Case 3** from the original comment)
* for vsphere, there is no error now. It appears that the `https://` has been removed from the request for the datacenter, and whitespace is seen in the request, but it is removed in the response.

**Comment by slickwarren** [comment]
on 2.6-head (9d2e086):
* create a user with whitespace in name -> stripped on create (expected, this was behavior at time of filing ticket)
* login with this user, with whitespace  -- pass
* login with this user, without whitespace -- pass
* login with admin, whitespace added -- pass
* login with admin, no whitespace -- pass
