### ISSUE TITLE
Enhancements to Global Settings Page

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3527]
on master-head (b6bcfad), there are several changes listed below that enhance the UI of global settings:

Request 1 -> Update `advanced settings` to `settings`
* Reason -> infers there are regular settings somewhere that the user can access
![Screen Shot 2021-07-21 at 2 24 27 PM](https://user-images.githubusercontent.com/16691014/126562278-da319f46-bca4-4de1-9633-4efc580eb215.png)

Request 2, option 1 -> add `view`/`edit` buttons in each option on the current `advanced settings` page (or alternative UI change to make it clear to user that current page does not allow edits to options)
request 2, option 2-> grey out settings on read-only page (like we do for any of the `secrets` in the `config` view)

secrets config view: 
![Screen Shot 2021-07-21 at 2 28 55 PM](https://user-images.githubusercontent.com/16691014/126562794-3265d11a-9d18-4aca-bd48-20dce31bbe44.png)
current advanced settings option (read only view):
![Screen Shot 2021-07-21 at 2 26 25 PM](https://user-images.githubusercontent.com/16691014/126562481-aa6a7bbc-290d-4b20-b288-19ff1261a382.png)

* Reason-> current `advanced settings` options appear editable, but are read-only + edit button takes 2 clicks to use, making the user need to look for it if they aren't used to our dropdown button

Request 3: allow edits on the same page for `advanced settings` changes instead of bringing user to new page to edit 1 setting
* Reason: currently, users are brought to a new page when trying to edit 1 setting, then redirected back to the entire list of settings. This could be integrated into the same page for a better user experience
![Screen Shot 2021-07-21 at 2 34 56 PM](https://user-images.githubusercontent.com/16691014/126563325-f34672fe-d6da-4eac-91b7-eea6ab4596cc.png)

**Comment by catherineluse** [comment]
There are also some global settings in which only a few values are allowed, but the only way to determine the possible values is to check the Rancher API view. We should review which settings should be offered to the user in the form of a dropdown menu instead of a text input.

**Comment by richard-cox** [comment]
Request 1 - Resolved - `Advanced Settings` is now call `Settings`
Request 2 - Resolved - If the user does not have permissions to change the settings the components are now disabled
Request 3 - Requires UX. Worth noting other pages (feature flags, bannders, branding, etc) all have global `Apply` buttons rather than individual out-and-back dialogues

**Comment by nwmac** [comment]
For now, we don't plan to do the 3rd change.
