### ISSUE TITLE
Enhancements to Cluster Tools

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3528]
on master-head (b6bcfad), there are several changes listed below that enhance the UI of Cluster Tools:

Request 1: add description of what cluster tools primary use cases are (show the user that this page can manage v1 apps if the legacy flag is enabled -> maybe with a link to the `feature flags` page in `global settings`.  Also show user that this page is for `rancher` apps only, perhaps linking to `apps & marketplace` if they want to install other apps)
* Reason: as a new user, it is unclear what this feature is for, why all the charts from `apps & marketplace` aren't listed here, or that they can view and manage v1 apps from here after enabling the legacy flag. From the dev, 
```
We added V1  tools in here to mirror their appearance in Cluster Manager as being 'tools' rather than being charts the user installs.
```

Request 2: (perhaps a bug?) Add trash/edit functionality to v1 apps 
* Reason: v2 apps have this, but when v1 apps are installed they do not have a delete/edit option on the cluster tools page
![Screen Shot 2021-07-21 at 2 47 59 PM](https://user-images.githubusercontent.com/16691014/126564647-1f1e3dc2-8f64-44d6-ad65-b4932352d79d.png)

**Comment by catherineluse** [comment]
I'm closing this issue because the V1 apps have been deprecated for some time, and they are soon going to be completely removed.
