### ISSUE TITLE
Vue UI - branding issues

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3529]
master-head version b6bcfad

1. `Private label company name :`
Should be either Private label/ Company name. `Private label company name` does not sound correct
2. `Text for header and foot seem smaller: `
Text setting to increase the font for header and footer is a nice to have. Font looks too small

3. If the text color is not selected, it shows white in the color box but the color of the text would be black. Text box color should match the color of the text.`

4. Color in the text color and background color box changes only if we click on the color and not on the slider`
Select the colors via the slider and the color is not changing. It changes only if we click on the color and then the slider works as well.

<img width="400" alt="Screen Shot 2021-07-21 at 3 02 37 PM" src="https://user-images.githubusercontent.com/38144301/126566114-bc2721e3-c6ff-472f-8586-906fcdc59e92.png">

5. A floating banner in the Branding page is missing. Can be added in the branding page
6. The color change option works for most text, but there’s still some default (blue) text that stays around. i.e. text from the menu (where user can select clusters), hyperlinks, any workload links or similar are still blue as well

**Comment by gaktive** [comment]
1-3 should be easy. 4 would be dependent upon the library being imported. 5 needs more clarification; what's missing? 6 could be a case of using a CSS class that isn't impacted by branding changing.

**Comment by anupama2501** [comment]
@gaktive for `5. A floating banner in the Branding page is missing. Can be added in the branding page`
Eg: Floating banner for `Feature flags`
<img width="400" alt="Screen Shot 2021-07-23 at 9 42 43 AM" src="https://user-images.githubusercontent.com/38144301/126814792-917879c5-64d7-42f7-90e9-6ffd05a1f201.png">


Similar floating banner can be added in the Branding page as well.

**Comment by lvuch** [comment]
If i'm understanding right 5 is suggesting an example banner so the user can see their changes. I can implement but think it's a good idea.

**Comment by gaktive** [comment]
Most of this is either fixed already in other tickets or working as designed. I'll break down the list and then pass to QA to review. If something doesn't meet testing needs, please file a ticket based on that individual item since tracking 6 items in a ticket is complicated.

**Comment by gaktive** [comment]
https://xd.adobe.com/view/3a0ff278-5d42-4f38-82fe-647fe3472cc7-6f5c/screen/d05f61e2-48d4-4117-b93b-db1255ca04ab/ (Page 4) is relevant here.

**Comment by gaktive** [comment]
All right, finding all the tickets got complicated since some work to update these fixes were done in adjacent work and not directly.

However, these should all be fixed. If QA catches something of the 6 here that isn't, please file a new ticket tied to that specific problem(s) and link back here for context.

**Comment by anupama2501** [comment]
Verified on v2.6.5-rc2 

1. Private label company name  - PASS 
2. Text for header and foot seem smaller - PASS
3. If the text color is not selected, it shows white in the color box but the color of the text would be black. Text box color should match the color of the text.` - PASS
4. Color in the text color and background color box changes only if we click on the color and not on the slider -  PASS
6. The color change option works for most text, but there’s still some default (blue) text that stays around. i.e. text from the menu (where user can select clusters), hyperlinks, any workload links or similar are still blue as well - PASS

Fix for 5 is missing. Logged https://github.com/rancher/dashboard/issues/5708 for tracking.
