### ISSUE TITLE
admin is not listed in rke1 cluster members RBAC when logged in as an admin/cluster owner

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3537]
On master-head 9e0d1b2

1. Create an rke1 node driver cluster from vue UI
2. From cluster --> RBAC --> members, admin is not listed
3. Default admin is listed in the members on ember UI for the same cluster

Expected result:
Default admin should be listed as a member in the Cluster --> RBAC --> members from dashboard UI as well.

**Comment by deniseschannon** [comment]
Validated with `master-head` 3499046.

Able to see the default admin in Vue UI on RKE1 and RKE2 clusters logged in as admin or cluster owner.
