### ISSUE TITLE
Namespace Picker Overflows Off The Top Of Visible Area

### ISSUE THREAD

**Issue by bmayfi3ld** [rancher/dashboard#3539]
When I have more than one namespace selected in the namespace picker in cluster explorer, it rolls off the top of the window. Making it where I can't deselect chosen namespaces.

![image](https://user-images.githubusercontent.com/563214/126793461-7fa24422-ad3b-4199-96fd-926b0cd1b691.png)

Using
Chromium Edge
Version 92.0.902.49 (Official build) beta (64-bit)

**Comment by richard-cox** [comment]
@bmayfi3ld What version of Rancher are you using?

The upcoming 2.6 has a number of changes and includes an update that fixes this.

**Comment by bmayfi3ld** [comment]
@richard-cox  v2.5.7

Apologies I tried to search through the issues to find an existing tracker for it.

**Comment by gaktive** [comment]
@rak-phillip can you take a look to see if this is happening on the release-2.6 branch?

**Comment by richard-cox** [comment]
@gaktive This is not an issue in 2.6, the project/namespace filter has been reworked and flows / collapses horizontally. The question here is do we back port that whole change back (costly), work out some fix only for pre 2.6 land or close.

**Comment by vincent99** [comment]
We are not backporting UI changes to 2.5 in general.  Critical bugs out small things needed for backend functionality maybe; for actual UI changes there's nowhere reasonable to draw the line on porting totally different designs for many things without it just becoming 2.6.

**Comment by bmayfi3ld** [comment]
I have no issue waiting for 2.6.   I did not know it had been fixed.
