### ISSUE TITLE
Cloning nodes in Machine Pools Page in Cluster details page in Cluster management results in removal of the existing node

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3541]
**On master-head commit id: `2e6926b`**

- Deploy an RKE1 cluster - 1 etcd, 3 worker and 1 control plane
- Go to cluster details page --> Machine pools
- On the ellipsis for the worker nodes, click on Clone
- Enter a name and select save.
- Existing node gets removed and re provisioned.
- And a new node also starts provisioning

**Expected:**
Existing node should not get removed.

**Comment by gaktive** [comment]
Looks like some connection to https://github.com/rancher/dashboard/issues/3542 as well.

**Comment by vincent99** [comment]
I'll disable the action, you can't really clone a machine (or node).. there's all sorts of references to secrets and other CAPI resources that still point to the old one because you didn't change them.

**Comment by sowmyav27** [comment]
**On master-head commit id: `94bca99`**

- Deploy an RKE1/RKE2 cluster - 1 etcd, 3 worker and 1 control plane
- Go to cluster details page --> Machine pools
- On the ellipsis for the worker nodes, Clone option is not available
