### ISSUE TITLE
Resources not listed under namespace view in dashboard

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3545]
Found when testing https://github.com/rancher/dashboard/issues/3422 on `rancher/rancher:master-head 2e6926b` on downstream RKE1 k8s `v1.21.1-rancher2-1` cluster.

When a user namespace is created and some workload is deployed into it I would expect the resources will be listed in the given namespace view but they are not.

Reproducer:
* on downstream cluster create a new namespace within Default project.
* create any Deployment in the new namespace
* go to the namespace detail page and see the resources are counted in `Active` Resources but they are not listed in the `Related Resources` table:

![ns_list_resources](https://user-images.githubusercontent.com/12828077/127158944-82f8d964-31b4-4eb2-8841-e327d4ec1758.png)

Also when a new namespace is created it is showing 8 `Active` Resources by default but they are not listed there as well. I found out that the number `8` represents internal resources created and assingned within the ns creation and consisting from of 4 RoleBindings, 1 CM, 1 Resource Quota, 1 Secret, and 1 Service Account - user can list them under `More Resources` menu for the cluster when the new ns is filtered out:
![active_resources](https://user-images.githubusercontent.com/12828077/127167699-9e5099fb-d66c-4357-bcb4-f38278584890.png)

**Comment by vincent99** [comment]
Related is basically showing owner references between resources; what's shown is whatever the server returns, but it's for things like this Pod was created by this ReplicaSet from this Deployment.

Every namespaced resource _has_ a namespace by definition, but these are not owner references. It not intended for every possible resource be listed as related to a namespace, or vice-versa; the entire UI nav and the namespace picker are for selecting what namespace(s) & resources you want to see.

**Comment by catherineluse** [comment]
I'm closing this issue for the reasons above. If you are looking for the resources in a certain namespace, you can filter by namespace in the top nav, then look for the resource name in the side nav. If it's not there, you can search for the resource by clicking on the magnifying glass in the top tav.
