### ISSUE TITLE
Snapshot Action is available on the cluster in cluster details page when cluster is not up and running

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3547]
**on master-head commit id: `2e6926b`**

- Deploy a custom RKE2 cluster.
- Dont add nodes yet. Click on save
- The cluster will be in `Provisioning` state.
- click on cluster --> cluster details page--> Snapshots tab
- `Snapshot Now` option is enabled
- On clicking on it, snapshot is taken, but an error is seen on the cluster

<img width="1100" alt="Screen Shot 2021-07-27 at 11 25 55 AM" src="https://user-images.githubusercontent.com/26032343/127208614-ff3843d8-7470-404a-8c81-4d91e338bafd.png">

**Expected:**
This action should be available on a cluster only after the cluster is up and Active.

**Comment by gaktive** [comment]
Co-ordinate with @richard-cox on where to look at this (both in the code and on a cluster)

**Comment by deniseschannon** [comment]
Validated with v2.6-head on Aug 4, 10pm

This button is disabled until the cluster is up and running.
