### ISSUE TITLE
Windows registration command does not appear when creating custom cluster through rancher

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3557]
on master-head (21ab02c):

Issue:
* registration command is not showing up for windows on custom cluster registration page
<img width="1691" alt="Screen Shot 2021-07-28 at 12 43 44 PM" src="https://user-images.githubusercontent.com/16691014/127387072-5aaa59e2-825f-4bfa-9a84-daa0a80f112c.png">

Expected Result:
Based on the [original ask from this ticket](https://github.com/rancher/dashboard/issues/3222) and the layout of the registration page (after creating a custom cluster through rancher) a separate command should be shown to the user
from the original ticket: 
```
* Registration command for Windows worker nodes
* Only allow worker role for Windows nodes to be registered (grey out etcd and controlplane for windows)
```

**Comment by gaktive** [comment]
This might still be dependent upon the backend work here: https://github.com/rancher/rancher/issues/33625

**Comment by vincent99** [comment]
The command goes where the message that says "The cluster must be up and running with Linux etcd and Control Plane nodes before you can add Windows workers" is shown.  It's not shown because you don't have that yet.

The checkboxes apply only to the Linux command.

**Comment by slickwarren** [comment]
on master-head (94bca99):
* after registering etcd/CP linux node, windows registration command shows up -- pass
