### ISSUE TITLE
Fix new + disabled linting rules

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3563]
- For rancher/dashboard#3546 we switched linting config to cover ts files
- This brought in a lot of rules that had to be disabled to ensure the existing JS files passed
- Some disabled rules were JS specific and could be applied to JS files only
- However others applied to both JS and TS
- We should fix these to ensure the TS files going forward are up to standard
- Rules can be found in `.eslintrc.js` and are currently..
  ```
    'vue/order-in-components':              'off',
    'vue/no-lone-template':                 'off',
    'vue/v-slot-style':                     'off',
    'vue/component-tags-order':             'off',
    'vue/no-mutating-props':                'off',
    '@typescript-eslint/no-unused-vars':    'off',
    'array-callback-return':                'off',
  ```

**Comment by catherineluse** [comment]
It would certainly have a positive impact on the code base if we could get rid of our unused variables, because we currently have a ton of them. It makes the code harder to read and Typescript conversion more difficult.

**Comment by nwmac** [comment]
@richard-cox Is this still relevant?
