### ISSUE TITLE
File an Issue (Not redirecting to the modified URL)

### ISSUE THREAD

**Issue by sunilvalmiki** [rancher/dashboard#3564]
Updated link is available is not updated in the Cluster Explorer Dashboard.
![image](https://user-images.githubusercontent.com/28586823/127481883-0f7b9a80-9228-46f4-8ad8-da8d8122ac25.png)
Can somebody address this issue? Or is it a known issue.
Where as it is working for the Cluster Manager.
Issue is seen with owner member.

**Comment by richard-cox** [comment]
I've tested this is the upcoming release (2.6) and this works correctly. Note - The location of the setting has now moved to the 'Branding' page in the same 'Global Settings' section
