### ISSUE TITLE
Switch to use v1 api for generateKubeconfig action.

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/dashboard#3571]
Today in explorer dashboard, generateKubeconfig is called from `/v3/clusters`. Since if user run MCM=false v3 api will be disabled, then the action will be broken.(related issue https://github.com/rancher/rancher/issues/33687). https://github.com/rancher/rancher/pull/33811 adds the ability to expose `generateKubeconfig` from v1 api and UI needs to be able to pick it up.

**Comment by gaktive** [comment]
Should be straightforward. @neillsom, do ping other UI folks if you need help.

**Comment by deniseschannon** [comment]
I transferred the backend issue to dashboard repo since the backend is merged. @neillsom I'm going to re-assign you to the transferred issue..
