### ISSUE TITLE
Copy to clipboard after Click on Welcome to Rancher page doesn't work

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3574]
Seen on `rancher/rancher:master-head 94bca99`

On attempt to copy commands for getting initial rancher password after deployment a bubble `Click to Copy` is shown but after Clicking the command the content is not actually copied to the clipboard.

![password](https://user-images.githubusercontent.com/12828077/127623809-e25091c9-9a22-4eaa-ace9-c9923b4f52b9.png)

**Comment by vincent99** [comment]
Also related to the quote getting eaten.

**Comment by deniseschannon** [comment]
Validated in master-head 8/2/2021

Able to click and copy and paste the info.
