### ISSUE TITLE
Custom Cluster Windows Registration UI Fixes

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3580]
In the custom cluster `registration` page, please address the following in regard to windows nodes (parent ticket rancher/dashboard#3222):

* after registering etcd/CP linux node, windows registration command shows up
  * could we reword the message to "The cluster must be up and running with Linux etcd and Control Plane nodes before the registration command for adding Windows workers will display" or something along those lines to make that more clear to the user? 

* windows was not able to register when rancher was running on an insecure server. Is there an equivalent of `insecure` for windows that could be added as a flag (like we have for linux/curl, see screenshot below)
![Screen Shot 2021-07-30 at 10 25 45 AM](https://user-images.githubusercontent.com/16691014/127689739-8a11f8a0-4e14-424b-896e-9e0486ed3a24.png)

* can we update `Run this command on each of the existing Windows machines you want to register.` to `Run this command in Powershell on each of the existing Windows machines you want to register.` (unless that is blatantly obvious to people who are used to using windows... )

for reference, this is what is currently displayed after the user adds a linux cp/etcd node
![Screen Shot 2021-07-30 at 10 26 43 AM](https://user-images.githubusercontent.com/16691014/127689955-34a72c1c-bde0-4aa5-8fd1-9b0c5c8b9144.png)

**Comment by gaktive** [comment]
1) Should be trivial but it should be clear enough as is. We can do it.
2) There is no `insecure` equivalent for Windows
3) We'd need to check with @luthermonson or someone else with Powershell experience to confirm the Windows command but `iwr` screams Powershell so the wording change can be made.

**Comment by slickwarren** [comment]
regarding 2. Could we add a message letting the user know that their rancher server must have valid certs in order to register windows nodes?

**Comment by rak-phillip** [comment]
regarding 3: `iwr` looks to be [Invoke-WebRequest](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.1),  so I think the powershell wording makes sense here

**Comment by rak-phillip** [comment]
It sounds like a simple ask to add a message for secure certs when registering windows nodes. I would just need to know how the message would read and how we want to display it (e.g. in a second banner below the existing one)

@slickwarren @gaktive

**Comment by vincent99** [comment]
@luthermonson  Can we just add an insecure windows command to the token?  Telling people at the time they're trying to add a cluster is a little late in the game to say you(r admin) should have setup your server differently.

**Comment by luthermonson** [comment]
so a couple things.. `iwr` was picked on purpose... it definitely screams powershell and the iwr alias was around for a very long time and we're not concerned about the alias not being there. this call will bail immediately when trying to use it on cmd e.g.

```
C:\Users\luthe\payroll>iwr
'iwr' is not recognized as an internal or external command,
operable program or batch file.
```

@gaktive is right...  there is no -Insecure or say a `-k` for Invoke-WebRequest that is consistent. There is a cmdlet param added  which is -SkipCertificateCheck but this in fact fails miserably on earlier versions of powershell including 5.1 which comes standard on all aws windows ami. there is a fix for 5.1 powershell using System.Net which looks like this: https://github.com/rancher/rke2/blob/master/windows/rke2-install.ps1#L310-L322 and is not something we should be putting in a one liner install script.

i offer you an alternative which is `curl.exe` (not `curl` which is an alias for iwr on powershell) which is a windows binary of the curl you'd expect from linux. we can do a curl.exe -k and we can call this a day. it however doesn't look like powershell and could potentially be run on cmd and we maybe have to do some more trickery with the verbiage to say "run this on powershell" or call powershell in our command. we can make this work and the windows team has no issues going to curl.exe.

**Comment by luthermonson** [comment]
@slickwarren this is merged you can check from master today sometime

**Comment by rak-phillip** [comment]
We'll still require one more change on the frontend to satisfy number 2 on the list: adding an insecure for Windows

@richard-cox @slickwarren

**Comment by rak-phillip** [comment]
@slickwarren Since we've had quite a lengthy discussion on this one, I wanted to give you a chance to see the end result as I'm raising a PR. This is what the entirety of the change will look like:
![image](https://user-images.githubusercontent.com/835961/128241577-8aad1840-af77-4e32-a261-b271412324cb.png)

cluster ready:
![image](https://user-images.githubusercontent.com/835961/128239416-531ba5b0-8212-42f2-b411-876db464224f.png)

insecure checked:
![image](https://user-images.githubusercontent.com/835961/128239468-22635386-8c95-4e44-9bd7-665eae9639da.png)

**Comment by slickwarren** [comment]
hmm, I just pulled the latest on master-head (2b156fd) and 2.6-head  but I still see the other command 
<img width="1450" alt="Screen Shot 2021-08-04 at 3 00 10 PM" src="https://user-images.githubusercontent.com/16691014/128261015-01d6cb03-ab42-478e-95ec-f285a040d7ac.png">

@rak-phillip

**Comment by rak-phillip** [comment]
I was working with @luthermonson earlier because I was running into a similar issue and he was able to point me to `master-e0123a04fb11301b55b318d9532d4c8419e3b9ad-linux-amd64` to develop against and that was successful. All of our changes are supplied to us from the backend, so I'm not sure what to do in order to get `master-head` properly updated.

@slickwarren

**Comment by rak-phillip** [comment]
Images for both `master-head` and `2.6-head` look like they contain all the needed changes now. Moving to `To Test`

@slickwarren @richard-cox

**Comment by slickwarren** [comment]
based on the discussion + [ticket around taints and labels](https://github.com/rancher/rancher/issues/34295), we will need to update the warning to `...Linux etcd, control plane, and worker nodes ...`

**Comment by sirredbeard** [comment]
Thanks @slickwarren.

**Comment by anupama2501** [comment]
Verified on v2.6-head 2e55e84

1. When the etcd+cp are not registered, users are shown the following banner:
`The cluster must be up and running with Linux etcd, control plane, and worker nodes before the registration command for adding Windows workers will display.`
2. Adding `insecure` in the command works while registering windows node. 
3. `Powershell` is added in the banner for windows registration command 
```Run this command in Powershell on each of the existing Windows machines you want to register.```
