### ISSUE TITLE
Update Deprecation Warnings text to reflect consolidated UI

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#3586]
Old deprecation warnings still reference "Cluster Explorer Apps and Marketplace"

Update all deprecation warnings to remove "Cluster Explorer" reference since we have 1 consolidated UI now. Most of the tools should refer to the new "Cluster Tools" location.  

The following tools should reference the location being in "Cluster Tools" instead of "Apps and Marketplace"

- Monitoring
- Alerting Drivers
- CIS Benchmarks
- Istio
- Logging
- Longhorn
- OPA Gatekeeper
- Rancher Backups

<img width="1404" alt="Screen Shot 2021-07-30 at 1 52 07 PM" src="https://user-images.githubusercontent.com/11410997/127710651-fd9d24eb-0d30-4213-8b54-1116f25f52f8.png">

The translations are located: https://github.com/rancher/ui/blob/master/translations/en-us.yaml#L1002

**Comment by codyrancher** [comment]
I didn't see any messages for Longhorn or OPA so let me know if they were missed. I did check the entire code base for Cluster Explorer and Apps and Marketplace to ensure they weren't there.

I also removed the cluster dashboard messaging of "dashboard: Try out the <a href="{dashboardLink}">Cluster Explorer</a> for a new way to view and manage your Kubernetes resources." since it doesn't seem relevant anymore.

**Comment by deniseschannon** [comment]
Can we update the text so that for Istio, it doesn't reference Istio 1.7, but "newer versions of Istio" as Istio 1.7 will be EOL soon?
<img width="1165" alt="Screen Shot 2021-08-03 at 1 48 56 PM" src="https://user-images.githubusercontent.com/11410997/128084338-34913739-4687-4afa-8b84-d1270ef1076b.png">


Cluster and project monitoring was showing up as a blue banner instead of yellow.
<img width="945" alt="Screen Shot 2021-08-03 at 1 49 07 PM" src="https://user-images.githubusercontent.com/11410997/128084351-1556c42b-ba38-46bf-afeb-508107559e7a.png">

**Comment by codyrancher** [comment]
Updating messaging 
![image](https://user-images.githubusercontent.com/55104481/128216904-d00704c9-a75e-423d-b4cc-71d3f0bb470a.png)

Changed color
![image](https://user-images.githubusercontent.com/55104481/128216521-caa0f6ff-75ad-41e6-9277-a18bbf97a6ee.png)

**Comment by deniseschannon** [comment]
Validated with v2.6-head on Aug 4.
