### ISSUE TITLE
Unable to provision vsphere downstream clusters (RKE/RKE2) -- machines not created in vsphere

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3587]
**Rancher Server Setup**
- Rancher version: master-head (2e6926b)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, rke2
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: v1.21.1-rancher2-1, v1.21.3+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? vsphere

**Describe the bug**

When provisioning using vsphere, machines are not being created in the provider.  

**To Reproduce**
* provision a downstream cluster using vsphere provider through rancher (single node all roles)

**Result**
* machines fail to create
for rke2, machine logs from rancher below:
```
Failure detected from referenced resource rke-machine.cattle.io/v1, Kind=VmwarevsphereMachine with name "ctw-vsphere-rke2-ctw-726-rke2-dsa-9s2n6": Running pre-create checks...
    (ctw-vsphere-rke2-ctw-726-rke2-dsa-9s2n6) Connecting to vSphere for pre-create checks...
    Error with pre-create check: "Post \"https://:443/sdk\": dial tcp :443: connect: connection refused"
    The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```
it appears that the vcenter name is not being added to the post request

**Expected Result**
machines should be created on provider when provisioned through rancher

**Screenshots**

![Screen Shot 2021-07-27 at 11 28 48 AM](https://user-images.githubusercontent.com/16691014/127208368-1afbdfc6-bcc5-470e-8c15-c4facad53aa5.png)

**Comment by gaktive** [comment]
Per @thedadams, the vsphere issue is the following:

> If a user leaves the “Host” value dropdown to the “Any” value, the UI sends the value as '__SENTINEL__'.  This seems to be causing the issue.

**Comment by codyrancher** [comment]
I prevented the `__SENTINEL__` from getting sent. I couldn't verify that this resolved the original issue due to VPN issues.

**Comment by slickwarren** [comment]
on v2.6-723f747b18a595a329a3563f6c791e78e0f135a3-head and master-head (f8600c6 ):
* I am now able to create clusters using the vsphere node provisioner
* single node create -- pass 
  * edit -- pass
  * scale up -- pass
  * delete -- pass
* multi-node create -- pass
  * delete -- pass
