### ISSUE TITLE
Legacy features/deprecated features and support within newer k8s versions

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#3589]
Currently, the `legacy` feature flag enables ability to use legacy features, which are features in previous Rancher releases that we are moving away from. Based on the [deprecation policy](https://rancher.com/support-maintenance-terms/), some of these features were previously deprecated will not be supported on k8s clusters with a k8s version >= 1.21.

The complete list of legacy features includes:
Catalogs
Global DNS
Multi-cluster Apps
Monitoring v1
Alerts v1
Notifiers v1
Apps
Logging v1
CIS Scans v1
Istio 1.5
Pipelines

From this set of features, the following subset of deprecated features will drop support in v2.6 and need UI to identify the lack of support for k8s 1.21+ clusters. 

Logging
CIS Scans
Istio
Pipelines

[ ] Ember UI - If the k8s cluster is running k8s 1.21+, update the text to indicate that this feature is no longer supported instead of being deprecated. 
[ ] Ember UI - If the k8s cluster is running k8s 1.21+, update the box from a yellow box to a red box. 

<img width="1404" alt="Screen Shot 2021-07-30 at 1 52 07 PM" src="https://user-images.githubusercontent.com/11410997/127710426-63d77cf2-24e7-43f9-a1e9-528933060b65.png">

As part of wanting to highlight users to move away from legacy features esp when upgrading k8s 1.21+, we need to add a warning on the cluster configuration page in Ember and Vue if the legacy feature flag is enabled AND 
[ ] Ember UI - If legacy feature flag is on and trying to deploy/upgrade to k8s 1.21+, add a warning message that the legacy feature flag is on and not all legacy features may be supported on this k8s version. 
[ ] Vue UI - If legacy feature flag is on and trying to deploy/upgrade to k8s 1.21+, add a warning message that the legacy feature flag is on and not all legacy features may be supported on this k8s version.

**Comment by deniseschannon** [comment]
Note: whoever works on this should also look at https://github.com/rancher/dashboard/issues/3586

**Comment by codyrancher** [comment]
Here's how it looks in ember ![image.png](https://zube.io/files/rancher/442c8fb19bf25926264210de89388152-image.png)

**Comment by deniseschannon** [comment]
Validated when feature flag is on:
- Warnings are shown in RKE1 cluster creation if k8s version is 1.21
- Warning are shown in RKE2 cluster creation if k8s version is 1.21

Validated on k8s 1.21 clusters that the following tools have red banners indicating lack of support
CIS
Logging
Istio Deployment page
Pipelines Configuration page

Validated on k8s 1.20 cluster that the following tools have yellow banners similar to before
CIS
Logging
Istio Deployment page
Pipelines Configuration page
