### ISSUE TITLE
[Ember UI] Unable to view Pod's detail page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3591]
**On master-head commit id: `8397837`**

- Deploy a cluster
- GO to system Project --> Workload --> Work detail page --> Click on pod to go to pod detail page
- Error seen in console:

```
Uncaught (in promise) Error: There is no route named  authenticated.cluster.monitoring.node-detail
    at A.handlersFor (route-recognizer.js:697)
    at j.applyToState (router_js.js:1135)
    at s.applyIntent (router_js.js:2148)
    at k (router.js:1353)
    at e._prepareQueryParams (router.js:833)
    at s.normalizeQueryParams (routing.js:53)
    at s._generateURL (routing.js:61)
    at s.generateURL (routing.js:71)
    at t (href-to.js:11)
    at n.compute (href-to.js:56)
```
- The page is stuck in loading and details are not loaded.

**Comment by richard-cox** [comment]
In 2.6 the user shouldn't be able to reach this page without accessing the super secret url and that process isn't supported. So suggesting we close this one.

I did try to reproduce this on a recent build (yesterday) however could successfully see the pod detail page (error still shown in console though).

**Comment by deniseschannon** [comment]
Why would we close the issue if you can click on these links through the UI? 

Are we saying that for some pod details we wouldn't be able to see these details? If so, why are the links available in the UI?

**Comment by richard-cox** [comment]
@deniseschannon the page in question is in the old Ember / cluster manager and not new dashboard / cluster explorer. You can't reach it from any supported means. 

Pod details should all be fine in the new, supported dashboard.

**Comment by deniseschannon** [comment]
We shouldn't be extending support for pod details in Ember with v2.6 as we are consolidating the UI.

**Comment by carolosf** [comment]
Also facing this issue https://github.com/rancher/rancher/issues/38311 and it has been preventing us from upgrading.

**Comment by richard-cox** [comment]
@carolosf There are no plans to make changes to the legacy UI, we would highly recommend switching to the current UI where you should be able to do everything from the legacy UI and much more.

**Comment by richard-cox** [comment]
@carolosf The Rancher team are continually, and specifically, making performance improvements. In addition to improvements in 2.7.0 you can find experimental UI improvements in three line burger menu top left --> Global Settings --> Performance. Those are mainly targeted at UI list performance. You may be most interested in `Incremental Loading` (on by default in 2.7.2) and `Manual Refresh`.

**Comment by carolosf** [comment]
@richard-cox Hi Richard, sadly the experimental features don't really improve things and we have hundreds of users complaining.

If rancher releases don't improve in performance for large clusters we may need to drop usage of the GUI in future.

**Comment by richard-cox** [comment]
Rancher is improving in performance for large clusters. Performance issues though are varied, cover a number of features and require different solutions.

For instance in the upcoming 2.7.2 release there are changes to how often the backend provide web socket updates to resources that change a lot, which helps clusters that are in constant flux. There's also an option to restrict the resources fetched to those in a single namespace, which helps clusters where there are a lot of resources.

For the feature release following that we expand on the filtering by single namespace concept and plan to let the user select multiple namespaces, or one or more projects. We also plan to move lots of heavy lifting out of the ui thread which will help CPU and memory impacted clients.

Note - Restricting resources fetched by namespace / project bring the new UI inline with how the old UI worked.

**Comment by carolosf** [comment]
Thanks for the update Richard, filtering by namespace sounds like it will help a lot!

**Comment by richard-cox** [comment]
It's a little more complicated in the new UI, users can select more than a single namespace or project (in theory this could stretch to 10k+ namespaces in a url).

There might be a way around this for small selections though. Can you create a new github issue explaining what feature has been lost, we can then work out a solution. This may mean we partially implement this (a shareable URL that will select a namespace ... but not connect the ns filter to the url)
