### ISSUE TITLE
Issue in dropdown when adding a custom RKE2 cloud credential

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3593]
**On master-head commit id: `3499046`**

- Enable OCI node driver
- Go to rke2 cloud credential page and create a cloud cred.
- When there are a lot of keys/values to add, the ones in the bottom of the page , scroll for it doesnt work

<img width="1486" alt="Screen Shot 2021-08-01 at 11 09 39 PM" src="https://user-images.githubusercontent.com/26032343/127812419-3a971f98-c8ae-4b64-bb4d-77ed8a9035b8.png">

**Comment by deniseschannon** [comment]
@vincent99 Since you're reviewing these pages, I've assigned this to you.

**Comment by deniseschannon** [comment]
We've re-done the cloud credential page, so could you play around with the new page? 

Most of this won't be relevant cause we've gone back to the old cloud credential style.

**Comment by vincent99** [comment]
This is a general problem with the dropdown component and not really related to cloud creds... But the switch back to v1 lets me know all the fields so there's not any to choose from in most drivers anymore.

**Comment by sowmyav27** [comment]
As per these comments - [this](https://github.com/rancher/dashboard/issues/3593#issuecomment-893096379) and [this](https://github.com/rancher/dashboard/issues/3593#issuecomment-892995838) and can be tested with these fixes - https://github.com/rancher/dashboard/issues/3684,
