### ISSUE TITLE
No version information shown on log in, fine on refresh

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3596]
- side bar bottom link which should be short version shows as 'unknown'
- click on unknown, version info is missing from about page
- on refresh all is fine, only an issue after logging in

**Comment by kravciak** [comment]
I was not able to reproduce the issue. Git commit link shows fine after first login with following setup:

- docker single install
- rancher:v2.6-1e814fe55f333ef83dffd357c666faf6fa7b09c3-linux-amd64 (built 6 days ago)
- master-b395238828a92cbe26c8d41528ab0a7e7251c809-head (build 7 days ago)
- master-head (4b6af95) (today)

After I log in I see version properly, linked page with versions is displayed fine too:
![Screenshot from 2021-08-09 12-58-49](https://user-images.githubusercontent.com/538604/128704230-eb7a338c-c4fe-48c5-a380-5881df741421.png)
