### ISSUE TITLE
Support Linode cloud credential for rke2 clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3599]
It is supported for RKE1, so we should support for rke2 clusters

**Comment by Jono-SUSE-Rancher** [comment]
@gaktive I believe that we are going to be focusing primarily on provisioning again in v2.6.3 if that's what you're asking. :)

**Comment by gaktive** [comment]
Linode now available

**Comment by nwmac** [comment]
Ember UI shown below.

The credential is just the  Linode API access token

![Screenshot 2022-01-11 at 11.45.54.png](https://zube.io/files/rancher/fb961f480d0535217a09da1a754c4897-screenshot-2022-01-11-at-11-45-54.png)

**Comment by nwmac** [comment]
@vincent99 Is this already done? It appears that the option to create a Cloud Credential for Linode RKE2  is in the UI already.

**Comment by gaktive** [comment]
@nwmac to update this with what exists in Ember already.

**Comment by nwmac** [comment]
Tasks:

- Improve the presentation of the existing screen
- Add validation of the token that the user enters (as per the Ember UI) - see: https://github.com/rancher/ui/blob/master/lib/global-admin/addon/components/cru-cloud-credential/component.js#L296

**Comment by timhaneunsoo** [comment]
Waiting for [36360](https://github.com/rancher/rancher/issues/36360) blocker issue to test this issue.
@sowmyav27 @jordojordo

**Comment by timhaneunsoo** [comment]
Closing issue as resolved based on validation in [36360](https://github.com/rancher/rancher/issues/36360)
