### ISSUE TITLE
Support OCI cloud credential for rke2 clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3600]
We have its support for RKE1 cluster, so we need it for rke2 clusters as well.

**Comment by gaktive** [comment]
@nwmac I think this is 2.6.3 since this is tied to cluster prov v2, which got pushed out further. 
@Jono-SUSE-Rancher am I correct?

**Comment by gaktive** [comment]
Credentials could be common between containers and virtual machines.

**Comment by gaktive** [comment]
This will likely have to come from external contributors. I'll check with @deniseschannon about who.

**Comment by jlamillan** [comment]
Hey @gaktive. I am the author of the OKE cluster and OCI node drivers for Rancher.

**Comment by gaktive** [comment]
Should be done as part of #3263

**Comment by Auston-Ivison-Suse** [comment]
**Validation  Setup**
rancher version: v2.6-(head)
Chrome version:99.0.4844.74

Pre-reqs: Have the oke driver activated within "cluster drivers"

**To Validate**
1) Create a cloud credential within the rke2 create option
2) Create the cluster
**Results**

You can check the credentials and see that the appropriate fields populate. 

The appropriate keys are as follows: 
-fingerprint
-tenancyID
-userId
-privateKeyContents

Post creation, check the cloud credentials, the key. 

I saw the appropriate PUT request get filled with the inputs I had in the fields.
