### ISSUE TITLE
Alert that nodes are inActive is not shown in Cluster Management page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3603]
**On master-head commit id: `3499046`**

- Deploy a custom cluster. (windows cluster)
- The windows nodes were in registering state
- There is no alert on the UI that the nodes are NOT active.

<img width="1668" alt="Screen Shot 2021-08-02 at 2 38 58 PM" src="https://user-images.githubusercontent.com/26032343/127927338-18c27063-a517-49b5-83ea-93195b6cbf06.png">

- Whereas there is an alert in the Ember UI that the nodes are not active
<img width="465" alt="Screen Shot 2021-08-02 at 2 38 52 PM" src="https://user-images.githubusercontent.com/26032343/127927332-f8e30044-7d56-4e09-88b4-436e88029e7c.png">

**Expected:**

Can we have a similar alert based on machines' status , as i see the machines in registering state on the cluster management.

**Comment by nwmac** [comment]
This was implemented in 2.7.2.

Duplicate
