### ISSUE TITLE
On clicking on Create User, prompt does not appear in the Username field.

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3605]
**On master-head commit id: `b395238`**

- Deploy a rancher master
- From Settings --> Users and Authentication
- Click on Create User
- The prompt does not appear in the Username field.
- User has to manually click on the input field of Username to start typing

**Expected:**
- Can the prompt be on the Username as soon as the user clicks on Create User?

**Comment by deniseschannon** [comment]
Validated with v2.6-head. 

When navigating to create a new user, the prompt appears in the username field.
