### ISSUE TITLE
Projects - Rancher project delete action has different behavior on Ember and Dashboard

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3607]
Rancher version: `2.6 master-head (08/02/2021)` _3499046_

On Rancher 2.5.8 Ember I validated the following:

- Create project `testp1`
- Create namespace `testns1` under Project `testp1`
- Delete project `testp1`

Result on Ember:

- **The project and the namespace gets removed**

Result on Dashboard:

- On Dashboard deleting a Project, the project gets removed but the namespace is kept and is shown in `Not in a Project`

This is observed in the following gif:

![Aug-02-2021 17-13-54](https://user-images.githubusercontent.com/27659/127938980-24b3eec6-b7ed-482e-9aa1-3889c731ac46.gif)

**Comment by izaac** [comment]
DELETE requests on Rancher 2.5.9 and master-head

## 2.5.9

```
DELETE /v3/projects/c-qmdz9:p-tj4ck HTTP/1.1
Host: <RANCHER_HOST>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
content-type: application/json
x-api-action-links: actionLinks
x-api-no-challenge: true
x-api-csrf: 341031f705
Origin: https://<RANCHER_HOST>
DNT: 1
Connection: keep-alive
Referer: https://<RANCHER_HOST>/c/c-qmdz9/projects-namespaces
Cookie: CSRF=341031f705; R_SESS=token-f9dph:jkd2x28zm5j4njf5gj7l7hx6mklnv8khdtdwtqp9pt5hpb6ftrzpzh
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
```

##  `master-head` _30574c2_


```
DELETE /v1/management.cattle.io.projects/c-677dv/p-tchm5 HTTP/1.1
Host: <RANCHER_HOST>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0 Waterfox/78.12.0.1
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://<RANCHER_HOST>/dashboard/c/c-677dv/explorer/projectsnamespaces
x-api-csrf: cb27e22527
Origin: https://<RANCHER_HOST>
Connection: keep-alive
Cookie: R_PCS=dark; R_LOCALE=en-us; CSRF=cb27e22527; R_SESS=token-gscgv:lpkk2dsr5zqrktb54j2pc2hhkthr5ng8lzvn6xfpnvk596hnclnx92
Pragma: no-cache
Cache-Control: no-cache
```

**Comment by sowmyav27** [comment]
Currently Namespaces created through ember are deleted when a project is deleted.  Namespaces created in kubectl or vue or any other way aren't

**Comment by gaktive** [comment]
Internal reference: SURE-5643

I'll leave this in the 2023 Q2 milestone for now based on priority.

**Comment by nwmac** [comment]
@gaktive We have added the ability to delete the namespaces in the project:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1955897/212197374-6e647c7a-cf1c-4240-882a-88c1566aa76b.png">

I think this satisfies this ticket - I think we can move it to test for QA to acknowledge and close.

**Comment by jameson-mcghee** [comment]
Due to the addition of the ability to choose to delete all namespaces in a project, this issue is no longer valid. Therefore I am closing this ticket.

![2023-01-17_15-10-59](https://user-images.githubusercontent.com/13294321/213002439-c695b9f4-e866-4177-b441-bc4fe496ed8e.gif)
