### ISSUE TITLE
Unable to pass extvalues.yaml for helm chart/app. How do we pass the extvalues.yaml from apps and marketplace?

### ISSUE THREAD

**Issue by sunilvalmiki** [rancher/dashboard#3608]
We add few jfrog repo which has got the bunch of helm charts.
We installed the apps with default values.yaml but we are unable to pass the custom made extvalues.yaml which will override the existing values.yaml.
Editing the values.yaml feasible with less content for big it is very difficult. 
So, **How can we pass the extvalues.yaml before installing the helm chart without editing the values.yaml?**

**Comment by richard-cox** [comment]
From my understanding you're supplying your own yaml overrides to the default chart values? If so there is no way other than pasting in the content to Values. Do you see an error? How big is the file containing the overring yaml?

**Comment by sunilvalmiki** [comment]
@richard-cox  yes your understanding is correct. 
No error. Values.yaml is very big and we won't be able to manage it.
We are continuously testing few helm charts/apps. Are you planning this as one of upcoming feature? It will help lots of developers and testers.

**Comment by richard-cox** [comment]
I'm not sure there's much we can, the browser will need to load the yaml at some point. The only way around would be to maybe upload by file and disable the editor. If you would like this feature, to be able to supply yaml without using the yaml editor, please raise in a separate specific issue.
