### ISSUE TITLE
monitoring v2 receivers -> overview buttons are not working

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3617]
![Screen Shot 2021-08-03 at 9 42 43 AM](https://user-images.githubusercontent.com/16691014/128054251-33de4a03-de0a-4c36-aef3-2e76991329c7.png)

Issue:
on master-head (30574c2)
the buttons above are not navigating anywhere. Each of the buttons are supposed to link to the same place as the sidebar titles link to.

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.6-head` `version 222dced` with the following steps:
Deploy monitoring `16.6.0`
Navigate to: Monitoring > Routes and Receivers > Create

Result:
Overview buttons link to sidebar titles. 
![97363d24ebf6bd864c24ada56f1dc9da](https://user-images.githubusercontent.com/57409052/128270153-11124aa4-a406-4143-8484-58b7dab36284.gif)
