### ISSUE TITLE
[Non-Admin Cluster Creation] Standard user cannot list cluster in Cluster Management page after provisioning cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3626]
**Rancher Server Setup**
- Rancher version: master-head commit id: `8397837`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: 1.21.1
- Cluster Type (Local/Downstream): Downstream - DO RKE1

**Describe the bug**
Standard user after provisioning cluster, cannot list cluster in Cluster Management page

**To Reproduce**
- Login as a standard user, deploy an RKE1 cluster
- User is not able to list cluster in CLuster Management page
- Cluster is seen in the Left menu and in the Home page

<img width="1277" alt="Screen Shot 2021-08-01 at 1 04 03 PM" src="https://user-images.githubusercontent.com/26032343/127783976-61243ee4-655f-40bb-88bc-2c4f74d46a8d.png">

<img width="891" alt="Screen Shot 2021-08-01 at 1 04 09 PM" src="https://user-images.githubusercontent.com/26032343/127783975-0a90d349-59e4-4fa8-bdf1-a767ce2d231e.png">

**Expected Result**
Standard user should be able to list Cluster in Cluster Management page

**Comment by richard-cox** [comment]
There's a number of fixes for non-admin cluster provisioning coming in https://github.com/rancher/dashboard/pull/3554, haven't seen this issue whilst working on it, so should be fixed on merge

**Comment by richard-cox** [comment]
I've just seen this happen and it took ~6 minutes for the provisioning cluster to appear in `v1/provisioning.cattle.io.cluster`, even though it was in `v1/management.cattle.io.clusters` immediately. @dramich Could anything cause this delay, an issue with syncing with `v3/clusters` or something?

**Comment by dramich** [comment]
The initial RKE1 cluster create call creates the management cluster, we then create a provisioning cluster based off that. I would expect that to be pretty fast but we also do the permissions dance once these objects get created. That said 6 min is too long and would lead me to believe it's a performance issue on the host. 
Every time I reproduce this the provisioning cluster is seen in the api response from the server and under `/v1/provisioning.cattle.io.cluster` basically as fast as I can click over to those screens.

**Comment by richard-cox** [comment]
Fixed by Darren & Vince as part of the large non-admin cluster create work

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head b2a2948`

DO RKE1 cluster created as `Standard User`. During and after cluster provisioning the cluster is present in `Cluster Management/Clusters` pane when logged as `Standard User`.

![user_list_cluster](https://user-images.githubusercontent.com/12828077/129323900-a986e644-fed5-41c6-9e4e-1c02a82ae03b.png)

Close.
