### ISSUE TITLE
Cluster-explorer auth only: Adding groups as members of cluster/project doesn't honor the RBAC

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3643]
Rancher version: `2.6 master-head (07/29/2021)` _94bca99_

From Dashboard:
- Enable the Keycloak OIDC auth provider with `testuser1`
- Create a cluster
- Add `testgroup1` as Cluster Owner or Cluster Member from Dashboard 
- On a different browser, or use incognito login as `testuser2` (member of `testgroup1`)
- The cluster is **not** visible for `testuser2`

From Ember:
- Do the same steps above but use Ember UI to manage the Cluster Membership
- On a different browser, or use incognito login as `testuser2` (member of `testgroup1`)
- The cluster is visible from Dashboard.
- Going back to Dashboard and checking the Cluster Members shows the us the group I added on Ember as `Unable to fetch principal info`

**Comment by anupama2501** [comment]
Verified on v2.6-head ba95a58

- Enabled OpenLDAP auth
- Created two clusters
- Added 1 group as cluster member to one cluster and another group as clutser owner to the other cluster
- The cluster shows up in the `explore cluster` page when for both cluster members and cluster owners.

**Comment by anupama2501** [comment]
Re-opening the issue as the clusters are not showing up in the cluster management page when logged in as both a cluster member and cluster owner.
<img width="400" alt="Screen Shot 2021-08-06 at 10 01 13 AM" src="https://user-images.githubusercontent.com/38144301/128546270-1ca0dd05-60e8-4927-862b-581b47300669.png">

**Comment by richard-cox** [comment]
@dramich @brendarearden My two favourite people! Not sure where this one lies so i've tagged you both.

- A keycloak user is in a group, and that group is a member of a cluster. 
- The cluster appears in `v1/management.cattle.io.clusters` but not `v1/provisioning.cattle.io.clusters`
- When trying to view the provisioning cluster page we fetch a number of resource types, one doesn't seem available 
  `Error: Unknown schema for type: cluster.x-k8s.io.machinedeployment`
- When viewing `/v1` there's only a very limited number of types available, almost as if this user was being classed as someone who couldn't access a cluster. When viewing `/v1/schema` there's 191 items

**Comment by richard-cox** [comment]
A fixed has merged to rancher/rancher, so this should now work. Will validate and then move to test

**Comment by richard-cox** [comment]
@dramich With 722486c from release/v2.6 i still see the issue

**Comment by richard-cox** [comment]
Possibly related, i think the provisioning cluster list is empty whilst management cluster populated when the (local) user is an owner of the cluster.

**Comment by richard-cox** [comment]
Verified in 723f747, moving to test

**Comment by anupama2501** [comment]
Verified on v2.6-head 723f747

1. Enabled openLDAP auth from the auth providers tab
2. Created a cluster and added a few users as cluster members and cluster owners
3. Added two induvidual groups with cluster owner and cluster member permissions
4. Logged in as the users from the groups and users added in step2.
5. Verified clusters are shown for both members and owners in both cluster management page and explore cluster page
