### ISSUE TITLE
Errors in dev console when selecting OCI region while adding Node Template for RKE1 cluster

### ISSUE THREAD

**Issue by catastrophe-brandon** [rancher/dashboard#3660]
**Environment:**
Docker-installed Rancher, `10588ab`

**Setup**
Ensure that the OCI driver is activated, cloud credentials for OCI have been set

**Steps to Reproduce:**
1. Login, Cluster Management -> Create
2. Attempt to create an OCI cluster, RKE1
4. Try to add a node template (confirm the cloud credentials for OCI are already selected in the drop-down)
5. In the Region drop-down, choose `us-sanjose-1`

**Actual Results:**
In the dev console there will be errors, screenshot included.

**Expected Results:**
The user should be able to provide the relevant OCI information to complete the node template without encountering errors.

**Screenshot**
![image](https://user-images.githubusercontent.com/20647751/128265343-7b2f30ef-34a4-4502-9ee6-8396efa30998.png)

**Comment by vincent99** [comment]
Oracle maintains this driver
