### ISSUE TITLE
Text is not visible in Protocols dropdown when creating a deployment

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3662]
**On 2.6-head commit id: `e3316c9`**

- Go to a cluster's context
- Workloads --> Deployment --> Create
- Text is not visible in Protocols dropdown when creating a deployment

<img width="1657" alt="Screen Shot 2021-08-04 at 11 52 18 AM" src="https://user-images.githubusercontent.com/26032343/128265093-63ab2485-6dff-41bd-b118-dfe2f6f65ec9.png">

**Comment by richard-cox** [comment]
Selected value is not visible when drop down is closed. Selected value and all options are visible when drop down is open. Looks like there's a search element that's positioned incorrectly when closed which consumes space. Low bar fix is to increase min-width and ensure wrapping works correctly. 
Secondary issue, the the row doesn't have a uniform height (both name and container port fields seem to large given other fields on whole page)

**Comment by ronhorton** [comment]
pass - verified in v2.6-1a5785604ed0b65e12c23d3739627d42b23ac1a0-head
unable to reproduce the issue
