### ISSUE TITLE
No gap in spacing between Edit Cluster and logged errors

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#3664]
![Screen Shot 2021-08-04 at 5 03 45 PM](https://user-images.githubusercontent.com/13127443/128270915-8257dbbc-1099-4cb9-a9f5-0f7215106747.png)

Expected a little gap in between the Edit Cluster and error log on the UI when spinning up a cluster with Cluster Manager.

Seen in `rancher/rancher:v2.6-head` (`e3316c9de7f089c5eef25bf58ff700a0198527c3`).

**Comment by aiyengar2** [comment]
Also, the name of the node and the IP address seem to be off-center. This is especially noticeable after the cluster has finished provisioning:

![Screen Shot 2021-08-04 at 5 08 17 PM](https://user-images.githubusercontent.com/13127443/128271174-1fa18f5a-2c46-42cc-8167-586f4a782035.png)

**Comment by richard-cox** [comment]
Navigating to ember is now not supported, only the embedded pages are.

**Comment by sowmyav27** [comment]
Closing this as its a no fix for Ember UI
