### ISSUE TITLE
cluster templates ui link not working sometimes

### ISSUE THREAD

**Issue by ibrokethecloud** [rancher/dashboard#3669]
Sometimes the UI doesnt load the link for the new rke v2 cluster templates.

The ui element shows up but the link is disabled.

I noticed the following error when navigating to "Cluster Management"

![image](https://user-images.githubusercontent.com/19664014/128285709-3bf62991-8746-47f4-8e9c-040698a4dbe2.png)

Using v2.6-head 1e814fe

**Comment by cloudnautique** [comment]
@ibrokethecloud which browsers?
cc. @richard-cox

**Comment by ibrokethecloud** [comment]
I have had the same error on both firefox(90.0.2) and chrome (Version 92.0.4515.131)

**Comment by richard-cox** [comment]
@ibrokethecloud To clarify, 
1) You're on the cluster management create screen, you click on one of the `Catalog Template` buttons at the top and nothing happens?
![image](https://user-images.githubusercontent.com/18697775/128313942-359ffa95-784b-47a7-a1dc-395c0d8e0810.png)
2) The error show in the console outputs when you click on the button and not before?
3) You're the rancher admin, not a restricted or standard user?

Can you provide the cluster template repo you're using?

**Comment by ibrokethecloud** [comment]
Hi @richard-cox the template is https://github.com/ibrokethecloud/cluster-template 

To clarify the template does load at times and I have managed to provision the cluster.

Sometimes the link just doesnt work.

**Comment by ibrokethecloud** [comment]
Hi @richard-cox here are the answers:

1. Yes. I click on the cluster template and nothing happens at times.

2. The error in the console is as follows:
![image](https://user-images.githubusercontent.com/19664014/128337007-8ecb0140-b952-4c54-b02d-0088518ea5ab.png)

3. I can confirm that I am the rancher admin and using the admin user.

**Comment by richard-cox** [comment]
@ibrokethecloud That is a new, different error from the description. For both console errors do they appear before you click on the link or after you click on the link?

**Comment by ibrokethecloud** [comment]
@richard-cox this error appears when i click on the catalog template in create cluster menu

**Comment by mantis-toboggan-md** [comment]
> Hi @richard-cox here are the answers:
> 
> 1. Yes. I click on the cluster template and nothing happens at times.
> 2. The error in the console is as follows:
>    ![image](https://user-images.githubusercontent.com/19664014/128337007-8ecb0140-b952-4c54-b02d-0088518ea5ab.png)
> 3. I can confirm that I am the rancher admin and using the admin user.

I was able to reproduce this error by setting the current cluster id to the fallback blank value, ie navigating to `c/_/manager/provisioning.cattle.io.cluster/create` instead of `c/local/manager/provisioning.cattle.io.cluster/create`
It's still unclear to me why an admin would be using the fallback `/c/_/manager `route instead of the default `/c/local/manager` route but @richard-cox does have some pending fixes around cluster creation and the blank cluster fallback...@ibrokethecloud if you see this problem when youre _not_ currently at a `c/_/manager...` route please let us know here.

**Comment by ibrokethecloud** [comment]
Hi @mantis-toboggan-md i will keep eye on this and will update the issue

**Comment by ibrokethecloud** [comment]
@mantis-toboggan-md @richard-cox seems like the issue is when I click "create" button on the home screen I have setup

![image](https://user-images.githubusercontent.com/19664014/128625777-3c5dfa46-4f26-4def-9d81-e12854b2e75d.png)

Then the resource is loaded as `c/_/manager/`

![image](https://user-images.githubusercontent.com/19664014/128625743-5afa1181-afb7-4cc9-87a9-db78659ee3a6.png)

If I however go into Cluster Management and then provision cluster, a clusterID is loaded, and the cluster template works fine.

**Comment by richard-cox** [comment]
Fixed as part of #3416. Note, cluster provisioning via template is not currently working - #3721

**Comment by slickwarren** [comment]
on 2.6-head (9d2e086):
* provisioning both through `cluster management` and `home` -> `create` are both working as expected for rke2 templates
