### ISSUE TITLE
Remove 1.15 k8s for EKSv2 from UI for 2.6 Rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3673]
Remove 1.15 k8s for EKSv2 from UI for 2.6 Rancher as its not available anymore according to : https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

**Comment by richard-cox** [comment]
@codyrancher This is going to an ember fix right, or do we get the list from the backend?

**Comment by codyrancher** [comment]
This will remove 1.15 from eksv1 and eksv2. I don't think that will be an issue but let me know if otherwise.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `ba95a58`**

1.15 is not available anymore when creating an EKSv2 cluster
<img width="867" alt="Screen Shot 2021-08-05 at 10 03 11 PM" src="https://user-images.githubusercontent.com/26032343/128458579-ab9ec864-2bd8-428d-8415-78b3c95eafc6.png">
