### ISSUE TITLE
RKE2 Cluster Template should search in `cattle-global-data` for cloud credential secrets, currently searching in `fleet-default`

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3678]
tested on 2.6.0-rc1:

repro steps:
* create a cloud credential (i.e. for aws EC2)
* add rke2 template repo in local cluster
* go to deploy a cluster from the template via `cluster management` -> `create`
* select a cloud credential

Issue:
* new cloud credential does not appear in list for rke2 templates

![Screen Shot 2021-08-05 at 10 08 45 AM](https://user-images.githubusercontent.com/16691014/128393169-cde0e9b6-d411-4a28-966c-526b4e5fb9a8.png)
![Screen Shot 2021-08-05 at 10 08 35 AM](https://user-images.githubusercontent.com/16691014/128393175-0d5754e3-d825-4a58-a233-9a3089277be6.png)

**Comment by vincent99** [comment]
This will need to be a separate question `type: cloudcredential` instead of `type: secret` because of v1 cloud credentials.  Normal references have to be within the same namespace but they aren't and there's special cases in the backend to handle it.

**Comment by slickwarren** [comment]
validated on v2.6-head (9d2e086): 
* updated chart with new `type: cloudcredential`
  * UI populates the cloud credential field with `opaque` secrets from the `cattle-global-data` field  -- pass
    * note, if pre-selecting a secret via `values.yaml`, the user must use the id of the secret, not the name
  * cluster provisions as expected
