### ISSUE TITLE
rke2 node driver machine pools page is empty for vsphere clusters in cluster management

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3679]
rancher version v2.6-head 8784750

1. Create a node driver rke2 vsphere cluster
2. Check the machine pools page in cluster management and it looks empty

**Expected result:** 
Created nodes should be displayed in the machine pools page of cluster management

**Additional info:**
Nodes show up active in explore cluster page --> cluster --> kube nodes, cluster management page --> advanced --> machines but not in the cluster management machine pools page

Some logs found in the console:
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'memorySize' of undefined
    at Proxy.providerSize (rke-machine.cattle.io.vmwarevspheremachinetemplate.js:14)
    at Object.get (resource-proxy.js:86)
    at Proxy.providerSize (cluster.x-k8s.io.machinedeployment.js:59)
    at Object.get (resource-proxy.js:86)
    at fn (provisioning.cattle.io.cluster.vue?be28:5)
    at r (vue.runtime.esm.js:2590)
    at f.Ee [as _t] (vue.runtime.esm.js:2686)
    at fn (ResourceTable.vue?b90b:3)
    at r (vue.runtime.esm.js:2590)
    at f.Ee [as _t] (vue.runtime.esm.js:2686)

```
<img width="400" alt="Screen Shot 2021-08-05 at 10 33 01 AM" src="https://user-images.githubusercontent.com/38144301/128395880-124ce4e2-9e6e-4677-8d39-66cd28e8d038.png">

Memory size is seen sent in the Post API request of `<IP>/rke-machine-config.cattle.io.vmwarevsphereconfigs/fleet-default`
<img width="400" alt="Screen Shot 2021-08-05 at 10 30 42 AM" src="https://user-images.githubusercontent.com/38144301/128394993-d04a5a82-2cf0-4699-b536-71a458a47250.png">

**Comment by richard-cox** [comment]
@anupama2501 Is this only soon after the cluster is created, or can you refresh the page after a while and the error's still there?

**Comment by anupama2501** [comment]
@richard-cox  I tried refreshing multiple times and the error's there every time I go to the machine pools page.

<img width="300" alt="Screen Shot 2021-08-05 at 11 09 43 AM" src="https://user-images.githubusercontent.com/38144301/128399892-590814a0-24a6-479b-b27d-9b03ada2416b.png">

**Comment by anupama2501** [comment]
Verified on v2.6-head 69055ba

Created a node driver vsphere rke2 cluster
From cluster management --> cluster machine pools [all pools show up]
