### ISSUE TITLE
Error "	Can not use fleet-default/nc-sowmya-oci-pool1-kbch4 [rke-machine-config.cattle.io/v1, Kind=OciConfig] because it is already owned by cluster sowmya-oci" after cloning an RKE2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3688]
**On 2.6-head commit id: `246fbd5`**

- Create a cluster and deploy
- Clone from this cluster, enter another name
- Pool name is disabled.
- Create the cluster
- Error seen - `Can not use fleet-default/nc-sowmya-oci-pool1-kbch4 [rke-machine-config.cattle.io/v1, Kind=OciConfig] because it is already owned by cluster sowmya-oci`

**Expected:**
Machine pool name should be changed.

**Comment by deniseschannon** [comment]
For now, we've disabled clone in the UI to be fixed correctly later

**Comment by catherineluse** [comment]
I'm closing this issue due to its age and because it looks like there is no plan to support cloning for clusters.
