### ISSUE TITLE
Namespace & Project Detail pages

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#369]
Redesign Namespace detail page.

**Comment by lvuch** [comment]
<img width="683" alt="Screen Shot 2020-03-17 at 9 57 57 AM" src="https://user-images.githubusercontent.com/3013118/76881304-2f576200-6836-11ea-86c0-d1c95fc6a93c.png">

**Comment by tfiduccia** [comment]
Requirements for Namespace details:
1.  top section should have Project & Description
2.  RBAC members
3.  Two tabs (Limits & Labels)

**Comment by lvuch** [comment]
<img width="685" alt="Screen Shot 2020-03-17 at 2 50 13 PM" src="https://user-images.githubusercontent.com/3013118/76905179-a6085580-685e-11ea-9286-bed7c6342927.png">

**Comment by deniseschannon** [comment]
Closing in favor of #567
