### ISSUE TITLE
Unable to get node SSH keys with RKE2 clusters

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#3699]
Environment:
Single-node rancher in docker container, v2.6-head

There is a mismatch in behavior between RKE1 and RKE2 here - with RKE1 I can get the SSH keys from the nodes in the UI, which is incredibly useful for end-users and important for QA as well. However, with RKE2 there is no option to get SSH keys (even though this information is stored).

EDIT: UPDATE - this issue is intermittent, you can see the page and not get keys, refresh and they might show as an option. Sometimes a refresh won't be enough and you need to navigate away to Home, then back to the page and possibly refresh again.

**Comment by richard-cox** [comment]
This should be present on both Kube Node List

![image.png](https://zube.io/files/rancher/9a6891c250d55caf69e9e216ec4373b3-image.png)

and Machine List

![image.png](https://zube.io/files/rancher/9a6891c250d55caf69e9e216ec4373b3-image.png)

What kind of RKE2 cluster did you bring up and were any of the default settings changes?

**Comment by davidnuzik** [comment]
Thanks @richard-cox will check this out a little later today when time frees up. Will give this a second peek it's strange that this didn't seem to work for me first try on a downstream RKE2 cluster (Digital Ocean provider). Will check again and follow up.

**Comment by richard-cox** [comment]
It could be they aren't there whilst in the same session (cluster is created and then visiting node list, no refresh) but will appear later. Let us know how you get on.

**Comment by davidnuzik** [comment]
Yeah looks to be the case. It shows sometimes but not always:
![image](https://user-images.githubusercontent.com/45179589/128548301-447d7b9f-9019-42ff-bbd3-4bcc5be7cf93.png)

I can refresh and still won't show. I can go back home, refresh there, come back and then it may show.

**Comment by davidnuzik** [comment]
Yeah that seems to be the case. I can sometimes get into a state where the menu breaks and I can't see the download ssh key option:
![image](https://user-images.githubusercontent.com/45179589/128548434-b36bbcf1-e3f2-4d44-9662-e1b2efb1484d.png)

A refresh may fix but not always? I may have to navigate back home, refresh there, then come back and then it may show.

**Comment by deniseschannon** [comment]
@davidnuzik I am able to download SSH keys, but it's on the machines page. 

Cluster Management -> Select the Cluster -> In the Machine Pools, find the machine and then there is an option to use "Download SSH Key"

![Screen Shot 2021-08-06 at 8.49.58 PM.png](https://zube.io/files/rancher/e272c44247fcf257be352410662eebfc-screen-shot-2021-08-06-at-8-49-58-pm.png)

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.
 
**Validation Steps:**

Rancher version: v2.6-head 4def65610 8/13/21 10:50 am Pacific
Rancher cluster type: single-node docker
Docker version: 19.03
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc5+rke2r2
 
Validation steps:

1. Create an rke2 cluster in Rancher, the cluster will take time to bootstrap but after a while (before it's even fully ready) the option shows up most of the time now. I can successful get ssh access in the browser or download the keys.

I'll still encounter this issue but this seems to be due to using a self-signed cert in single-node docker setup. This appears to be improved with the changes. In these cases a simple refresh will fix that issue.

I tested in a couple of environments with multiple clusters/situations. In each case this works now (except for the situation above which is expected when using self-signed certs). I'm satisfied with the fix. Thank you!.
