### ISSUE TITLE
Create/Preview/edit YAML buttons

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#370]
Requirements:

1.  All List pages that have rancher GUI added need to have two buttons.  Create (goes to rancher gui) and Create as YAML that goes to the YAML page.
2.  Page that only have YAML create, the button should say Create as YAML
3.  Need to Add Import YAML button to the YAML Create screen

**Comment by lvuch** [comment]
@tfiduccia are you wanting mocks? a dev will probably have to implement this.

**Comment by tfiduccia** [comment]
@lvuch - Yes.  I'm sure it's just adding another button in front of create.  But wanted to make sure you agree with wording or if you wanted to do something different.

**Comment by lvuch** [comment]
![import-yaml.png](https://zube.io/files/rancher/83d477bf06ba0aa7d7f8b4c130818c4d-import-yaml.png)

**Comment by lvuch** [comment]
![Screen Shot 2020-03-23 at 3.21.40 PM.png](https://zube.io/files/rancher/ad42af38d4c5ce99c63aa8612c27327b-screen-shot-2020-03-23-at-3-21-40-pm.png)

for list page

**Comment by tfiduccia** [comment]
View as YAML as well?

**Comment by lvuch** [comment]
https://xd.adobe.com/view/0740293f-c075-4ec4-4d4a-0cc2a05ef0ce-7171/

**Comment by deniseschannon** [comment]
From the last mockup, on the first page, there is only 1 button missing.  `Read from file`  was added to finish up the use case in this ticket.

*. Resource List Page -> This has two buttons `Create from YAML` and `Create`. `Create` only shows when there is a form view to create from. This is already completed.
* Clicking on `Create from YAML` brings you to YAML create/edit page. The `Read from file` button needs to be added to the top right corner and after the file is read, it should populate the yaml editor. 

Note: This is changing from the original requirement where it said "Import from YAML" to "Read from file".

**Comment by deniseschannon** [comment]
- [ ] Can we move the "Read from file" to the right side on the same line as `Create <RESOURCE>`>?

<img width="1149" alt="Screen Shot 2020-05-08 at 2 39 41 PM" src="https://user-images.githubusercontent.com/11410997/81451692-e1762080-9139-11ea-8575-a637cff7baef.png">

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/782

**Comment by lvuch** [comment]
<img width="1176" alt="Screen Shot 2020-07-07 at 11 13 56 AM" src="https://user-images.githubusercontent.com/3013118/86824796-79618f00-c043-11ea-848c-371da4d1a89d.png">
Read from file should be moved to masthead

**Comment by soumyalj** [comment]
Validated with master-head (ec1ea7a99)
- Verified that the following objects have both "Create from Yaml" and "Create" buttons. 
1. Namespace
2. Configmap
3. Secret
4. Service
5. Ingress


- The following objects have only "Create from Yaml" button
1. Persistent Volume
2. Persistent Volume Claims
3. Pod

- The following object has only "Create" button
1. Workload

Create from yaml screen has the "Read From File" button on the top right as expected. Example:
![Screen Shot 2020-07-07 at 2 21 24 PM](https://user-images.githubusercontent.com/18536626/86844764-5b088d00-c05d-11ea-90fe-947b5843cc4a.png)
