### ISSUE TITLE
rke2: Editing and downloading the yaml of machine nodes in explore cluster page results in error

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3700]
rancher server: v2.6-head ba95a58

1. Created a node driver rke2 cluster DO 1 node all roles
2. From explore cluster page --> Cluster kube Nodes --> edit the yaml file of the node 

Result:
Stuck in loading and errors are seen in the console 
if we try to download the yaml file, same errors are seen in the console

Expected result:
Should have been able to edit the yaml

Errors in console:
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'doneOverride' of null
    at f.r (index.vue?cc80:1)
    at f.t._render (vue.runtime.esm.js:3548)
    at f.r (vue.runtime.esm.js:4066)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.run (vue.runtime.esm.js:4554)
    at gn (vue.runtime.esm.js:4310)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at ie (vue.runtime.esm.js:1906)
```

Errors in response: 
```
<ip>/k8s/clusters/c-m-8c295e46/api/v1/nodes/anu-group-e-mm47p
Request Method: GET
Status Code: 403 Forbidden

```

**Comment by mantis-toboggan-md** [comment]
I don't see any recent dashboard PRs in this area of code but the bug appears to be fixed anyway; I can't reproduce it with a fresh 2.6-head rancher server.

**Comment by anupama2501** [comment]
Verified on v2.6-head 69055ba

I do not see this issue any more. 
Will re-open the issue if its seen again.
