### ISSUE TITLE
Service creation fails as the target port is passed in string from UI to backend

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#3701]
Type: **Bug**

**Description:**
The headless service fails to create on dashboard with below error.
<img width="1040" alt="Screen Shot 2021-08-06 at 11 00 35 AM" src="https://user-images.githubusercontent.com/60111667/128553042-608bf5bf-64b7-4763-b180-04dd54c85e1b.png">

**Steps to Reproduce:**
1. Create a headless service.
2. Specify Listening port and target port.
3. Click create, the service creation fails.

The request contains port in string.
```
{"type":"service","metadata":{"namespace":"default","name":"service-test"},"spec":{"ports":[{"name":"","port":23,"protocol":"TCP","targetPort":"23"}],"sessionAffinity":"None","type":"ClusterIP","clusterIP":"None"}}
```

**Env:** - v2.6-head - ba95a58

**Comment by richard-cox** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#serviceport-v1-core

We need to return a number if the content is a number... but string if a string

**Comment by thehejik** [comment]
Tested on `v2.6-head 4def656`

I was able to create a headless service without any problem. Closing
![headless1](https://user-images.githubusercontent.com/12828077/129347822-3936351a-9004-4e38-890f-4b392d7bafd4.png)

The service `aservice` exists: 
![headless2](https://user-images.githubusercontent.com/12828077/129347838-fa7dcf0c-7128-4b40-85c1-1eaa0387a9fe.png)
