### ISSUE TITLE
Block editing of local cluster name

### ISSUE THREAD

**Issue by cbron** [rancher/dashboard#3705]
The local cluster's name should stay as "local" as it is hardcoded that way in many places. Disable editing of the cluster name in the UI.

**Comment by richard-cox** [comment]
There should be an isLocal property on the management cluster that denotes if it's the local one.

**Comment by richard-cox** [comment]
It looks like this was always possible in the old ember ui. In the dashboard we embed that page. For RKE2 types we do allow them to change it to local, which I guess is the same problem in reverse.

However, if we have the flag, what depends on the 'local' name? @vincent99 Is it valid to be able to rename the 'local' cluster? Plus then rename another non-local cluster as 'local'?

**Comment by cbron** [comment]
@deniseschannon I didn't intend for this to be in 2.6.0 or a release blocker, as Richard said it was always possible. Just something that came out of another issue.

**Comment by nwmac** [comment]
Thanks @cbron - I'll bump to 2.6.X and remove the release blocker label

**Comment by vincent99** [comment]
There's probably not anything wrong here?  The real `metadata.name` (norman "id") is never editable in k8s, but Ember/rke1 displays and lets you edit `displayName` any time, which you (backend/@cbron) shouldn't care about or ever look at.

**Comment by cbron** [comment]
Ahh, Vince is right, I was thinking we were changing the real name here and not display name. I am going to close this and re-open the other issue around potential problems when changing it.
