### ISSUE TITLE
Refresh issue in OPA Gatekeeper UI

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#371]
***Steps to reproduce***
***Scenario 1***
1. Create a cluster and navigate to dashboard.
2. Enable the OPA gatekeeper.

***Result***
Go to constraint template page, No template is shown, no create button is shown. Only on refresh, templates and create button start appearing.
Go to constraint page, No create button appears. Only on refreshing the page create button starts to appear.

***Scenario 2***
1. Create a cluster and navigate to dashboard.
2. Enable the OPA gatekeeper by clicking customize configuration button.

***Result***
After gatekeeper gets activated, it still shows creating. On refresh page appears fine and starts showing the gatekeeper details.

***Scenario 3***
1. Delete one of the template.

***Result***
Deleted template still shows up on UI. 
Only on refresh, it goes off.

***Scenario 4***
1. Go to OPA Gatekeeper, enable it.

***Result***
Sub menu constraint template and constraint do not appear.
Only on refresh, UI shows sub menus for constraint template and constraint.

***Scenario 5***
1. Create constraint
2. Delete constraint.

***Result***
Deleted constraint still shows up on UI. 
Only on refresh, it goes off.

***Scenario 6***
1. Create a constraint template
2. Go to constraint and click create button.
3. Check the template field

***Result***
The newly created template doesn't appear in template field.
Only on refresh, it starts appearing.

**Scenario 7**
1. Disable OPA gatekeeper

**Result**
OPA gatekeeper continue to show OPA gatekeeper details and doesn't show the enable button without refreshing the page.

**Comment by westlywright** [comment]
I have taken care of Scenario 2 and Scenario 7. @codyrancher will handle the constraint/template related scenarios. Will ref this ticket in my pr.

**Comment by westlywright** [comment]
Pulling myself off this ticket as the config issue fixes have been merged.

**Comment by deniseschannon** [comment]
This issue is most likely no longer relevant due to massive framework changes that have been implemented since this was filed.

**Comment by aaronRancher** [comment]
Scenario 5 is still seen in Rancher server `rancher\rancher:master-head` `version 4911f8b`

Steps:
Create a constraint
Delete the constraint
Result:
Constraint is still listed in UI and only disappears after refresh.

**Comment by deniseschannon** [comment]
Closing the last scenario in favor of the umbrella issue of change events not working reliably.
