### ISSUE TITLE
Editing deployment in UI cause errors

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/dashboard#3710]
Today when editing deployments(or other resources) in UI, it will show error `TypeError: n.applyHooks is not a function`.

Steps to reproduce:
1. Open cluster explorer UI and go to workloads.
2. Edit a deployment using Edit as Yaml. 
3. It will show error `TypeError: n.applyHooks is not a function` but edit will eventually succeed.

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `e3316c9` master-head commit id: `2916020`**

- Open cluster explorer UI and go to workloads.
- Create a deployment
- Edit a deployment using Edit as Yaml.
- No errors seen
- user is able to save
