### ISSUE TITLE
UI Issues in dark mode

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3713]
**On 2.6-head commit id: `0ab00d7`**

1. Header column doesnt have another color in these pages
**Node Templates**
<img width="1678" alt="Screen Shot 2021-08-07 at 9 41 03 AM" src="https://user-images.githubusercontent.com/26032343/128607618-d7927a3f-f244-4625-ab51-8dec56f0ef34.png">

**Pod Security Policies page**
<img width="1673" alt="Screen Shot 2021-08-07 at 9 42 47 AM" src="https://user-images.githubusercontent.com/26032343/128607648-ec00b82e-3ca2-413e-a0d7-66f60b7b2aa7.png">

2. Node template selected, cannot be seen in the dropdown 
<img width="1011" alt="Screen Shot 2021-08-07 at 9 41 40 AM" src="https://user-images.githubusercontent.com/26032343/128607687-674165d8-f722-43a4-ac73-c5f9287afadc.png">

3. Node Drivers Tab is not visible. only CLuster Drivers is
<img width="1026" alt="Screen Shot 2021-08-07 at 9 42 37 AM" src="https://user-images.githubusercontent.com/26032343/128607674-3f6c3f28-462a-4295-ae29-180923c24b38.png">

4. Drop down fields are not very obvious. 
<img width="946" alt="Screen Shot 2021-08-07 at 4 18 19 PM" src="https://user-images.githubusercontent.com/26032343/128616125-1f1adffb-66e2-4360-910f-c39641c6c834.png">

**Comment by richard-cox** [comment]
https://github.com/rancher/ui/pull/4735 fixes 1, 3
https://github.com/rancher/ui/pull/4734 fixes 2

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head b2a2948`

I'd say all the checked web elements are now visible in dark mode. Closing.

1. Header column doesnt have another color in these pages
**Node Templates**
![dark_node_templates](https://user-images.githubusercontent.com/12828077/129336804-f9978bbe-f2c2-439b-817c-315207c4fbf6.png)

**Pod Security Policies page**
![dark_psp](https://user-images.githubusercontent.com/12828077/129336818-5b013ff1-2af5-41e4-a847-232da24dd2a8.png)

2. Node template selected, cannot be seen in the dropdown 
![dark_template](https://user-images.githubusercontent.com/12828077/129336835-4dde039d-33e1-4bf9-9395-7881614da062.png)

3. Node Drivers Tab is not visible. only CLuster Drivers is
![dark_nodedrivers](https://user-images.githubusercontent.com/12828077/129336853-760805e1-671b-48bb-b647-4eb847daec28.png)

4. Drop down fields are not very obvious. 
![dark_dropdown](https://user-images.githubusercontent.com/12828077/129336860-5e045255-1ad2-482a-bdfa-05f0522a2f1a.png)
