### ISSUE TITLE
AKS v1 cluster shown as "Genericengine" in Cluster Management page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3714]
**On `v2.6.0-rc1`**

- AKS v1 cluster shown as "AKS" in Home page
<img width="1161" alt="Screen Shot 2021-08-07 at 3 26 01 PM" src="https://user-images.githubusercontent.com/26032343/128615349-764b7718-71b7-4973-9919-aaed9c0228c3.png">

- AKS v1 cluster shown as "Genericengine" in Cluster Management page
<img width="1423" alt="Screen Shot 2021-08-07 at 3 26 07 PM" src="https://user-images.githubusercontent.com/26032343/128615351-5d797023-2519-4c05-98db-f9b5715e5168.png">

- this is an upgraded rancher server setup from 2.5.9 to 2.6.0-rc1
- On 2.5.9, deploy AKSv1 and upgrade rancher to 2.6.0-rc1

**Comment by aaronRancher** [comment]
Tested on Rancher upgraded to `v2.6-head` `version 72986b2` from `v2.5.9`.
Steps:
On Rancher `v2.5.9`, deploy an AKSv1 cluster
Upgrade Rancher to `v2.6-head` `version 72986b2`

Result:
Cluster provider is `AKS` on dashboard home page.
![Screen Shot 2021-08-17 at 4 34 25 PM](https://user-images.githubusercontent.com/57409052/129814006-7cf48fc7-96da-4f6d-a1d1-713bd020e388.png)

Cluster provider is `Azurekubernetesservice` on cluster management page.
![Screen Shot 2021-08-17 at 4 31 37 PM](https://user-images.githubusercontent.com/57409052/129813791-1db39816-46c8-441c-8258-be791f7056c2.png)

**Comment by aaronRancher** [comment]
Reopening issue, as we expect the provider to be `Azure AKS` in cluster management page.
As seen in ember UI:
![Screen Shot 2021-08-17 at 4 37 08 PM](https://user-images.githubusercontent.com/57409052/129814422-51a774ae-e9f8-4b29-9bb6-073189b624ac.png)

**Comment by aaronRancher** [comment]
Tested on Rancher upgraded to `v2.6-head` `version c10ef4b` from `v2.5.9`.

Cluster provider is seen as `Azure AKS`
![Screen Shot 2021-08-18 at 10 32 03 AM](https://user-images.githubusercontent.com/57409052/129945151-2b32476c-2d59-4273-b08b-5d3389e770f5.png)
