### ISSUE TITLE
Show an Imported cluster as an Import in the Provider column on home page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3716]
**On 2.6-head commit id: `0ab00d7`**

**In the Cluster Management page:**
- RKE2 Import cluster - Provider - RKE2
- RKE2 Node driver - Provider - Amazon EC2 RKE2
<img width="561" alt="Screen Shot 2021-08-07 at 10 46 05 PM" src="https://user-images.githubusercontent.com/26032343/128622211-3ccfcb43-9072-49b6-88c9-a4f7f1855d5f.png">

**Home**
- RKE2 Import cluster - Provider - RKE2
- RKE2 Node driver - Provider - RKE2
<img width="329" alt="Screen Shot 2021-08-07 at 10 46 14 PM" src="https://user-images.githubusercontent.com/26032343/128622212-94228261-1292-4249-80f1-ac37116d97e8.png">

Could we show an Imported cluster as an `Import` in the Provider column ?

**Comment by richard-cox** [comment]
At some point the home page was aligned with the cluster's list

![image](https://user-images.githubusercontent.com/18697775/200593583-e8010c14-a56e-4319-9af4-9f8ac26f81ae.png)

![image](https://user-images.githubusercontent.com/18697775/200593652-c4b7b4cc-1637-44d0-aa22-1e1c56cb322c.png)

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, freshly install Rancher, import an RKE1 cluster and note if it shows as imported in the home page and Cluster Management|
|2|As a standard user,  freshly install Rancher, import an RKE2 cluster and note if it shows as imported in the home page and Cluster Management|
|3|As a standard user,  freshly install Rancher, import an K3s cluster and note if it shows as imported in the home page and Cluster Management|
|4|Repeat scenarios 1-3 but on Rancher `v2.7.0`. Upgrade to `v2.7-head` and see if the clusters show as imported in the home page and Cluster Management|

**Comment by markusewalker** [comment]
Validated this against `v2.7-head` https://github.com/rancher/rancher/commit/f7692f30cf47d00073cc41b879e0ff90fb0a68b0.

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/f7692f30cf47d00073cc41b879e0ff90fb0a68b0
- Browser: Chrome


**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, freshly install Rancher, import an RKE1 cluster and note if it shows as imported in the home page and Cluster Management|:white_check_mark:|
|2|As a standard user,  freshly install Rancher, import an RKE2 cluster and note if it shows as imported in the home page and Cluster Management|:white_check_mark:|
|3|As a standard user,  freshly install Rancher, import an K3s cluster and note if it shows as imported in the home page and Cluster Management|:white_check_mark:|
|4|Repeat scenarios 1-3 but on Rancher `v2.7.0`. Upgrade to `v2.7-head` and see if the clusters show as imported in the home page and Cluster Management|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigated to Cluster Management > Import Existing.
3. Imported an existing 3-node RKE1 cluster; validated the cluster and nodes come up as `Active`.
4. Validated that it shows up as `Imported` in Cluster Management and the home page:
![image](https://user-images.githubusercontent.com/52591819/204890415-3a33e939-43ed-4c07-9b1c-ba76ccc766ba.png)
![image](https://user-images.githubusercontent.com/52591819/204890439-cfe0d5f4-117f-4c9d-8b1a-55258e54acb7.png) 
_______
**Scenario 2**
1. Repeated step 1, but imported an existing 3-node RKE2 cluster.
2. As seen in scenario 1's screen capture, it shows as the expected `Imported` in the Cluster Management page and home page.
_______
**Scenario 3**
1. Repeated step 1, but imported an existing 3-node K3s cluster.
2. As seen in scenario 1's screen capture, it shows as the expected `Imported` in the Cluster Management page and home page.
________
**Scenario 4**
1. Repeated scenarios 1-3, but first ensured that I was on Rancher `v2.7.0`.
2. `Imported` DOES properly reflect on the home page and Cluster Management:
![image](https://user-images.githubusercontent.com/52591819/204890249-b8d0e9ec-794e-4556-a46c-525bdb96abfe.png)
![image](https://user-images.githubusercontent.com/52591819/204890265-8abd3311-48b1-4cd2-bae6-528c43ffc1d6.png)
![image](https://user-images.githubusercontent.com/52591819/204890273-428192f1-ec5f-4961-a670-8fc9435ffdef.png) 
3. Upgraded Rancher to `v2.7-head` https://github.com/rancher/rancher/commit/f7692f30cf47d00073cc41b879e0ff90fb0a68b0; validated that the cluster and nodes remain as `Active`.
4. Validated that `Imported` now shows in the clusters under the home page and Cluster Management page:
![image](https://user-images.githubusercontent.com/52591819/204889995-d3407f37-5580-4fca-a866-990475e61d8d.png)
![image](https://user-images.githubusercontent.com/52591819/204890008-e0c6e172-3c3d-4570-8d26-22c15a43a40a.png)
![image](https://user-images.githubusercontent.com/52591819/204890025-d36607f2-b24a-4295-bee6-a75d1a531430.png)
