### ISSUE TITLE
[Non-Admin Cluster Creation] Handling of cluster create for standard users is broken

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3719]
- Native dashboard create cluster
  - User is not redirect to cluster list page after creating cluster. Roles are not assigned
- Embedded ember create cluster
  - User does not see cluster after being redirect to cluster list

In all cases changes to clusters and other previously seen resource types do not react to changes (clusters do no appear or are removed, secrets will not change etc).

The root cause of this is the new dynamic rbac added via Steve / v1. 
- An admin has access to all resource schemas and types, will get updates to those when they change and can exercise all(?) actions against individual resources and resource collections
- Standard users however begin with a very small set of schemas and some only with POST rights. After they have access to a single cluster they gain the rights required to continue.
- However those changes to the user are not pushed to the dashboard
- This means we have to manually wait for those role changes to be applied, resubscribe to all sockets and then wait for the new resource types to be available and there are problems with this approach.

Note - This doesn't cover the reverse, when a user goes from having clusters and permissions to removing their last cluster

Note - Standard users and restricted admins also have issues related to not having access to a cluster. 

I've split this out from rancher/dashboard#3416 to allow those fixes to go in

**Comment by richard-cox** [comment]
Fixing this will fix another release blocker #3626

**Comment by richard-cox** [comment]
Fixed by Darren & Vince as part of the large non-admin cluster create work

**Comment by kravciak** [comment]
> User is not redirect to cluster list

User can see cluster on cluster list now in both dashboard (rke2) and embedded (rke1)

> Roles are not assigned

Please provide more information here, after cluster creation roles are in this state:
![Screenshot from 2021-08-18 11-57-06](https://user-images.githubusercontent.com/538604/129878756-8b2c3c91-998d-407b-b5e5-446add78c6f9.png)

> In all cases changes to clusters and other previously seen resource types do not react to changes (clusters do no appear or are removed, secrets will not change etc).

Please give more information about how to test this

Tested on v2.6-head (c10ef4b)

**Comment by richard-cox** [comment]
This covers all the ways to import/create a cluster (excluding by cluster template) when the non-admin creates their first cluster.

If the user can assign roles as part of the create process they should be shown again when editing the cluster.

**Comment by kravciak** [comment]
I tried as Standard-User to create cluster from each group:

Custom clusters RKE1 / RKE2, Import existing Generic cluster:
 - after creation I am redirected to cluster details page with registration commands

Create -> DO RKE1 / RKE2, Create GKE
 - after creation I am redirected to cluster list

I can see all created clusters on Menu -> Cluster Management list fine

Works fine on v2.6-head (c10ef4b)
