### ISSUE TITLE
[Non-Admin Cluster Creation] Unable to create a cluster via template when there's no current cluster

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3721]
Whenever we have no access to a cluster (for instance non-admin) we can't fetch cluster specific schemas, so fail on 'install' of chart at
```
        this.operation = await this.$store.dispatch('cluster/find', {
          type: CATALOG.OPERATION,
          id:   `${ res.operationNamespace }/${ res.operationName }`
        });
```

This is aside from rancher/dashboard#3719 and the fixes in rancher/dashboard#3554

**Comment by richard-cox** [comment]
Now unblocked given Darren & Vince's non-admin cluster create work

**Comment by richard-cox** [comment]
I've given this a test (using https://github.com/rancher/dashboard/pull/3820) with `4def656` and hit a couple of issues. Using `hardcoded-template` from repo `https://github.com/slickwarren/cluster-template-examples` `main` with the default values (i.e. a secret that doesn't exist 

1) The install fails before the provisioning cluster is created, therefore the user will never be able to fetch the `catalog.cattle.io.operation` and therefore never see the log which explains the failure
2) The failure itself looks permissions based. Could be a chicken and egg scenario `Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: clusters.provisioning.cattle.io "qa-hardcoded-0" is forbidden: User "u-j2tc4" cannot get resource "clusters" in API group "provisioning.cattle.io" in the namespace "fleet-default"`

@dramich Is it possible to add GET to `catalog.cattle.io.operation` for cluster-creator?

**Comment by richard-cox** [comment]
Dan is aware of the issue, however there is no rancher/rancher ticket to cover the work their side (we have changes our side - #3885 )

**Comment by nwmac** [comment]
The frontend changes for this are all done and merged.

**Comment by StrongMonkey** [comment]
@richard-cox Shouldn't the schema name be `catalog.cattle.io.operations`? I am adding the equivalent backend changes but still seeing the same error.

**Comment by StrongMonkey** [comment]
I am still seeing the same error even if I added the permission in backend. Here is the console log:
```
Find: [management] management.cattle.io.setting system-default-registry
actions.js:270 Find: [management] management.cattle.io.setting server-url
actions.js:270 Find: [cluster] namespace fleet-default
actions.js:157 Find All: [rancher] cloudcredential
resource-instance.js:516 Starting wait for catalog operation fetch
actions.js:270 Find: [management] catalog.cattle.io.operation fleet-default/helm-operation-5tlm6
resource-instance.js:542 Wait for catalog operation fetch done
actions.js:270 Find: [cluster] catalog.cattle.io.operation fleet-default/helm-operation-5tlm6
3subscribe.js:354 Ping [management] from dev
```

I think in here, rke2 cluster template is always going to be installed in management cluster, so we don't have to wait for the schema of the provisioned cluster?

**Comment by richard-cox** [comment]
For cluster template we only wait for the catalogue operation. On success we redirect to the provisioning cluster list page. In either case both management and provisioning clusters should have parity.

What was the actual error you were seeing?

**Comment by StrongMonkey** [comment]
@richard-cox I am seeing the error `unknown schema: catalog.cattle.io.operation` in UI. I am able to get operation and logs from api(/v1/catalog.cattle.io.operation).

**Comment by Jono-SUSE-Rancher** [comment]
This issue is now unblocked by the backend with the pr https://github.com/rancher/rancher/pull/34331 which addresses https://github.com/rancher/rancher/issues/34277.

**Comment by anupama2501** [comment]
Re-opening as I'm not able to create clusters logged in as standard user fails with the error `Unknown schema for type: catalog.cattle.io.operation`

1. Added the repository `https://github.com/StrongMonkey/cluster-template-examples.git` from local --> Apps and market place.
2. Enable openLDAP
3. Log in as standard user, create a cluster from the cluster template. 
4. The cluster creation fails upon clicking on the save button, fails with the error `Unknown schema for type: catalog.cattle.io.operation`.
Following are seen in the logs at https://<ip>/v1/catalog.cattle.io.operations/fleet-default/helm-operation-9gfbp/logs from the API https://<ip>/v1/catalog.cattle.io.operations
```
helm install --generate-name=true --namespace=fleet-default --timeout=10m0s --values=/home/shell/helm/values-cluster-template-0.0.1.yaml --version=0.0.1 --wait=true /home/shell/helm/cluster-template-0.0.1.tgz

---------------------------------------------------------------------
SUCCESS: helm install --generate-name=true --namespace=fleet-default --timeout=10m0s --values=/home/shell/helm/values-cluster-template-0.0.1.yaml --version=0.0.1 --wait=true /home/shell/helm/cluster-template-0.0.1.tgz
---------------------------------------------------------------------
```

If we click cancel and go back to cluster management page, we can see the cluster stuck in `Provisioning state` with the following error displayed:
```
Failing bootstrap machine(s) anupama-3-twst2-b964bf56f-57mr6: failed creating server (DigitaloceanMachine) in infrastructure provider: CreateError: Failure detected from referenced resource rke-machine.cattle.io/v1, Kind=DigitaloceanMachine with name "anupama-3-twst2-630c7e01-7zh6k": Running pre-create checks... Creating machine... (anupama-3-twst2-630c7e01-7zh6k) Creating SSH key... (anupama-3-twst2-630c7e01-7zh6k) Creating Digital Ocean droplet... Error creating machine: Error in driver during machine creation: POST https://api.digitalocean.com/v2/droplets: 500 Server Error The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag. and join url to be available on bootstrap node
```


5. If we login as an admin and create a cluster from cluster template, the cluster comes up active.

**Comment by richard-cox** [comment]
I've created a fix for the `Unknown schema for type: catalog.cattle.io.operation` issue.

The other issue though, the cluster stuck in provisioning, i couldn't reproduce (saw something different).

@anupama2501 Are you using the `main` branch of https://github.com/StrongMonkey/cluster-template-examples.git and the template named as `cluster-template` ?

**Comment by StrongMonkey** [comment]
@richard-cox The do issue is probably unrelated and are due to configuration error. cc @anupama2501

**Comment by anupama2501** [comment]
Verified on v2.6-head 2e55e84

1. Added the git repo in the chart repositories `https://github.com/StrongMonkey/cluster-template-examples.git` with `new` as the branch.
2. Created a cluster as an admin - come up fine no errors, verified all logs are shown.
3. Created a cluster as a user - came up fine, verified all logs are shown
4. Provided same name to the cluster  - verified the error logs are shown in the backend. 
5. Created a cluster with multi nodes - came up fine and no errors seen.
