### ISSUE TITLE
Edit config of a Linode Cloud credential, does not have the Key as token

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3723]
**On 2.6-head commit id: `4b6af95`**

- Create a cloud credential - Linode
- Click on Ellipsis --> Edit Config 
- Key is _not_ `Token` 

<img width="897" alt="Screen Shot 2021-08-08 at 3 42 26 PM" src="https://user-images.githubusercontent.com/26032343/128647877-b7743823-ffe6-4377-9e87-075ccf8b5c9e.png">

**Comment by catastrophe-brandon** [comment]
Tried w/ v2.6-head, commit `v2.6-9d2e08674b9318e440fb6396c6e168a9c9bdca91-head`, similar issue. Upon edit the value is empty.

**Comment by mantis-toboggan-md** [comment]
The empty value field is expected, that data isn't sent by the backend for security reasons. The other cloud creds work in a similar way

**Comment by catastrophe-brandon** [comment]
Sorry, I think I misunderstood the requirement here. I've confirmed that the value of the Key field is literally `token` in both master-head and v2.6-head.
