### ISSUE TITLE
Unable to edit constraint templates

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#373]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Scenario 1**
**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster
2. Navigate to dashboard, enable OPA gatekeeper.
3. Try to edit constraint template

**Result:**
On clicking apply button, UI shows error ```{ "type": "error", "links": {}, "code": "Conflict", "message": "Operation cannot be fulfilled on constrainttemplates.templates.gatekeeper.sh \"k8sallowedreposfinal\": StorageError: invalid object, Code: 4, Key: /registry/templates.gatekeeper.sh/constrainttemplates/k8sallowedreposfinal, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: e2e33016-bf39-41cf-bd0f-2b0a54f15da0, UID in object meta: ", "status": 409 }```

**Scenario 2**
Is edit as form required for constraint template? Edit as form doesn't take user to form view of the template.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2463-head- e651c7a81
- Installation option (single install/HA): Single

**Comment by codyrancher** [comment]
@khushboo-rancher 
Scenario 1 is likely a backend issue or a framework issue. The default editor is being used to create these.

Scenario 2 there is not supposed to be a edit as form view.

**Comment by khushboo-rancher** [comment]
@codyrancher  For scenario 2 we should remove the option to edit/clone template in form view, right?

<img width="1507" alt="Screen Shot 2020-03-19 at 1 55 35 PM" src="https://user-images.githubusercontent.com/60111667/77114184-56a26080-69e9-11ea-92a6-e450ea581085.png">
<img width="1509" alt="Screen Shot 2020-03-19 at 1 54 44 PM" src="https://user-images.githubusercontent.com/60111667/77114202-5d30d800-69e9-11ea-85bb-e41b355eb3fb.png">

**Comment by codyrancher** [comment]
I wasn't able to replicate scenario 1. I suspect it was a backend issue that's been resolved since this was opened. If you still run into that issue can you assign it to the backend?

scenario 2. We shouldn't have edit as form. I removed it.

**Comment by khushboo-rancher** [comment]
Verified in latest dashboard UI.

Steps:
1. As a standard user able to edit template.
 - Edit the properties
 - Edit the rego language
 - Editing of metadata will throw error as expected.
2. Edit as form is removed.
<img width="1550" alt="Screen Shot 2020-03-30 at 1 56 35 PM" src="https://user-images.githubusercontent.com/60111667/77961812-4c0c8480-728f-11ea-846c-0487292de75c.png">
