### ISSUE TITLE
RKE1 template node is not visible

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3730]
RKE1 selected template name is not readable in dashboard (chrome).

To reproduce:
- Clusters -> Create -> RKE1 (Digital Ocean)
- Add Node Template
  - add cloud credentials
  - add template with all defaults

Chrome 91.0.4472.114:
![Screenshot from 2021-08-09 13-27-23](https://user-images.githubusercontent.com/538604/128699382-3185066e-b8ab-4b56-9bf7-a1d7dde2e0c0.png)

Firefox 86.0.1:
![Screenshot from 2021-08-09 13-39-42](https://user-images.githubusercontent.com/538604/128700663-434a18af-64c7-418e-af7f-39e08bd3a8a6.png)

Tested on: rancher v2.6-head (4b6af95)

**Comment by richard-cox** [comment]
Dupe of #2 in #3713

**Comment by sowmyav27** [comment]
Duplicate of - https://github.com/rancher/dashboard/issues/3713

**Comment by sowmyav27** [comment]
Tracking this issue separately.

**Comment by kravciak** [comment]
I can see template name fine on both firefox & chrome, closing - v2.6-head (25d39aa)
