### ISSUE TITLE
User is not redirected to Cluster explorer on a rancher upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3733]
**Rancher Server Setup**
- Rancher version: master-head commit id: `9e0d1b2`
- Installation option (Docker install/Helm Chart): Helm install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: 1.20.7

**Describe the bug**
User is not redirected to Cluster explorer on a rancher upgrade

**To Reproduce**

- On 2.5.9 , deploy a downstream cluster (not required) in the Ember UI
- Upgrade rancher to master-head.
- User is still in Ember UI on the upgraded setup

**Expected Result**
User should be redirected to Cluster Explorer, since that is the default UI from 2.6.0

**Comment by vincent99** [comment]
We're also adding in a mechanism for Vue in 2.6+ for the subscribe pings to tell us the current server version and have Vue auto reload when it changes, so this won't happen next time...

**Comment by snasovich** [comment]
@vincent99, is the change merged already or you're working on it?

**Comment by vincent99** [comment]
The last part for future release to reload Vue is not yet, the rest is.

**Comment by snasovich** [comment]
Backend PRs for reference:
https://github.com/rancher/rancher/pull/33849
https://github.com/rancher/rancher/pull/33931

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to 2.6-head commit id: `2778eca`**

**Using Local Auth/admin**

- user is on the Ember UI cluster page on 2.5.9
- Upgrade rancher docker install to 2.6-head
- Reload/refresh rancher UI page
- user is redirected to https://server/g/clusters page for a brief moment before being redirected to Dashboard UI.
- After that the User is logged out. And the user has to log back in to go to the Dashboard --> Home page.
