### ISSUE TITLE
UI logs out user when enter bad Azure cloud credentials when creating cloud credential

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#3737]
**Environment:**
Rancher version: v2.6-head `4b6af95d7` 8/9/21 8:46 am Pacific
Rancher cluster type: single-node in docker
Docker version: 19.03
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc4+rke2r2
 
**Reproduce steps:**
1. Log in to Rancher as `admin`
2. Create an RKE2 Azure cluster for the first time, you will be routed to create your cloud credential
3. Insert invalid keys in all fields (in my case, valid text, but likely expired subscriptionId, clientId, and clientSecret)
4. This results in a 401 as expected
5. The error is only very briefly shown and you are logged out of admin (not expected)

**Expected Result:**
I expected the UI to not log me out (so I could read the error message and try creating my cloud credential again, this time with valid info in the form).

**Actual Result:**
I got logged out of the UI as soon as I put in my old Azure credentials (which seem to have expired or no longer be valid). 

Additional Info:
I used my old subscriptionId, clientId, and clientSecret from a couple of years ago. These are probably expired or deleted, but the point of the bug is to do this intentionally and see that UI act in this unexpected way.

I saw the following in the browser dev console:
![image](https://user-images.githubusercontent.com/45179589/128771089-d6f95bcd-a2a6-4bb9-b4ad-78a86ad560ec.png)

aksCheckCredentials:
![image](https://user-images.githubusercontent.com/45179589/128771319-43423d15-5b37-4152-889d-3c5f59449586.png)

aksCheckCredentials request and response:
_request (prettyfied):_
```
{
    "clientId": "<valid but likely expired clientId>",
    "clientSecret": "<valid but likely expired clientSecret>",
    "subscriptionId": "<valid but POSSIBLY expired subscriptionId>"
}
```
_response (raw):_
401 Unauthorized
```
{"error":"invalid credentials"}
```

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/pull/3743/files#diff-c2d2496f9af1638ba2e4b51ff1dfc1236f1cca5400386738a24c8b009f4645aeR51

**Comment by davidnuzik** [comment]
https://github.com/rancher/dashboard/pull/3743

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.
 
**Validation Steps:**

Rancher version: v2.6.0-rc2 (8/10/21)
Rancher cluster type: single-node docker
Docker version: 19.03
 
Validation steps:

1. Create Azure cloud credentials. Use a bad (incorrect) client secret.
2. Can confrim no longer redirected to logout and can read the error message in the UI, as expected:
![image](https://user-images.githubusercontent.com/45179589/128939246-776bebaa-e308-4484-ac86-505c69474f51.png)
