### ISSUE TITLE
Unable to clone constraint template

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#374]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

***scenario 1***
**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable OPA gatekeeper.
2. Click clone as yaml.

**Result:**
There is no apply/save button.
On clicking cancel, navigates to constraint template yaml view.
It shows metadata and status tags in yaml too. Do we want to show these data as these are not required to create a new template? 

***Expectation***
There should be apply/save button to save the changes.
On clicking cancel, it should navigate to template list page.

***scenario 2***
**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable OPA gatekeeper.
2. Click clone as form.

**Result:**
It doesn't open template in form. It opens the template in yaml.

***Expectation***
Is clone as form required? 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2463-head- e651c7a81
- Installation option (single install/HA): Single

**Comment by codyrancher** [comment]
**Scenario 1:**
> It shows metadata and status tags in yaml too.

This is using the generic YamlResrouce component which just provides the exact source yaml. This is the same functionality you'll see for all other resources. 

I think we should add this functionality but I think it should be added as a feature request.

**Scenario 2:**
Clone as form will not be an option once https://github.com/rancher/dashboard/pull/442 goes in.

**Comment by khushboo-rancher** [comment]
Verified in latest dashboard UI.

User is able to clone yaml and apply the changes.
Clone as form view is removed from option.
<img width="1550" alt="Screen Shot 2020-03-30 at 1 56 35 PM" src="https://user-images.githubusercontent.com/60111667/77961228-5ed28980-728e-11ea-87ee-48ca0707737d.png">
