### ISSUE TITLE
Customizable branding - No limit on company name length and escaping issues on content

### ISSUE THREAD

**Issue by catastrophe-brandon** [rancher/dashboard#3751]
Customize the company name in the branding section of global settings and some issues will become apparent.

1. There should probably be a limit on length.
2. The content has escaping issues.

![image](https://user-images.githubusercontent.com/20647751/128897472-7173375e-d4ac-4e60-b0e2-6a67caea479a.png)

**Comment by catastrophe-brandon** [comment]
The company name also appears to be programmatically used to construct content on the Feature Flags page. 
![image](https://user-images.githubusercontent.com/20647751/128898805-1605e448-f208-49d9-a5e1-6f0e7cff2643.png)

**Comment by catastrophe-brandon** [comment]
Another place, under Users and Authentication:

<img width="738" alt="Screen Shot 2021-08-10 at 2 46 28 PM" src="https://user-images.githubusercontent.com/20647751/128925232-8479f320-68c9-4983-bca8-15ded9773777.png">

**Comment by catastrophe-brandon** [comment]
Another spot, while creating a Node Template:

<img width="896" alt="Screen Shot 2021-08-10 at 2 48 25 PM" src="https://user-images.githubusercontent.com/20647751/128925452-c2f7bd17-e197-4af6-a375-e62da6a98b1c.png">

**Comment by gaktive** [comment]
@Shavindra sync up with @nwmac before you start working on this. This should be an easy one to work on, once we sort out the how.

**Comment by nwmac** [comment]
@Shavindra See comments below for what we should do. I think a limit of 100 characters is reasonable - would be good to have this as a constant somewhere in case we need to change it. Let's enforce this at the point the user can edit, rather than cropping it every place we show it.

**Comment by Shavindra** [comment]
What do you think of the solution below? This would be easier to manage IMO.
```

<LabeledInput  :char-length="20" /> // This could be a constant? or we can just modify accordingly

// LabeledInput 

 computed: {
    maxLength() {
      if (this.type === 'text' && this.charLength) {
        return this.charLength;
      }

      return null;
    },
```

**Comment by nwmac** [comment]
@Shavindra That will work - I'd call it maxLength rather than char-length - and we'd wire the maxLengtn() computed property into the maxlength on the input control.

**Comment by Auston-Ivison-Suse** [comment]
**Rancher Setup For Reproduction**
- Rancher version: V2.6.1

**Rancher Setup For Validation**
- Rancher version: v2.6-head (e655fd8)

**Steps for Reproduction**
1. Go to global settings --> branding
2. In the input field for Private Label Company Name enter a long string of text or generated amount of words. 
3. Save and return Home from the hamburger menu. 
4. Observer the bug

Screenshot of Bug: 
![Screen Shot 2021-11-08 at 8.17.15 PM.png](https://zube.io/files/rancher/478a249673c65e679f9d7382a0de2269-screen-shot-2021-11-08-at-8-17-15-pm.png)

**Steps for Validation**
1. Go to global settings --> branding
2. In the input field for Private Label Company Name enter a long string of text. The character limit should be 100. 
3. Save and return Home from the hamburger menu.
4. Notice the String of text doesn't distort the header now that the limit is set to 100 characters.

Screenshot of the validated fix: 
![Screen Shot 2021-11-08 at 8.20.48 PM.png](https://zube.io/files/rancher/dcdd30d5aad6d3cfc41e3eb721f8b0ab-screen-shot-2021-11-08-at-8-20-48-pm.png)

**Comment by sowmyav27** [comment]
Reopening to test an additinal usecase mentioned here - https://github.com/rancher/dashboard/pull/4510#issue-1044759486

**Comment by Auston-Ivison-Suse** [comment]
**Rancher Setup For Validation**
- Rancher version: v2.6-head (e322f8f)

**Steps for Validation**
1. Go to global settings --> branding
2. In the input field for Private Label Company Name enter Enter something along these lines to test length and Diacritic: <> () + = & #', " - _<> () + = & #', " - _<>
3. Save and return Home from the hamburger menu, this should remove the diacritic.
4. Notice the diacritic symbols don't show here either. 

**Results**


https://zube.io/files/rancher/807b1f2fc5418955e61056687835c538-2021-11-22_11-56-37.mp4

![Welcomebanner.png](https://zube.io/files/rancher/ab665279172b5705559c03a9671cfa99-welcomebanner.png)
