### ISSUE TITLE
Cluster Member, Standard User cannot create a project

### ISSUE THREAD

**Issue by catastrophe-brandon** [rancher/dashboard#3756]
Steps to Repro:
1. Create a cluster as an admin
2. Create a Standard User, user1
3. Add user1 to the cluster as a Cluster Member
4. Attempt to create a project. 

Expected Results:
Project can be created

Actual Results:
Create button is grayed-out and disabled

![chrome-capture](https://user-images.githubusercontent.com/20647751/128909301-a15d5d60-b065-4773-a974-5946fdb41bbd.gif)

Docker installed, `v2.6-723f747b18a595a329a3563f6c791e78e0f135a3-head`

**Comment by anupama2501** [comment]
Also noticed:

- If we create a project from ember UI as the user u1
- Go to dashboard and then the `create` option is enabled for the same user.

**Comment by richard-cox** [comment]
Still need to investigate more, but `Create` is disabled as the project doesn't have an owner. That's normally automatically defined by a hidden component... which is hidden as the user doesn't have access to the `management.cattle.io.projectroletemplatebinding` type. This could be an RBAC issue, but will investigate more tomorrow UK AM

**Comment by richard-cox** [comment]
Spoke with Dan, the binding type is only available once the user has created a project. I gave this a test and the user who creates the project automatically gets the owner binding. I've created a change then that will allow creation if the member section is hidden.

**Comment by catastrophe-brandon** [comment]
Fix verified in `v2.6-9d2e08674b9318e440fb6396c6e168a9c9bdca91-head`.

**Comment by catastrophe-brandon** [comment]
Also verified on `master-head` commit `master-121323a9d4918d045fd1026f8d40dcb45e579eca-head`
