### ISSUE TITLE
create rke2 on azure - invalid tenant

### ISSUE THREAD

**Issue by claudioser** [rancher/dashboard#3758]
**If this is a UI issue, please file an issue at https://github.com/rancher/dashboard/**

**Rancher Server Setup**
- Rancher version: Rancher 2.6 rc1
- Installation option (Docker install/Helm Chart): helm on rke1

**Information about the Cluster**
- Kubernetes version: 1.19.3
- Cluster Type -  RKE2 on Azure

**Describe the bug**
Just by clicking on the create cluster, the ui displays an invalid tenant id - see screenshot, even though this is not defined in the relevant cloud credential

**Screenshots**

![image](https://user-images.githubusercontent.com/53047113/128839729-bc947c40-c76b-414a-ab97-6df57fc49959.png)

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by prabalsharma** [comment]
This bug has been fixed on 2.6-head. However, there is still an issue with RKE2 on Azure https://github.com/rancher/dashboard/issues/3798
