### ISSUE TITLE
There is no progress bar or indication of app being deployed on enabling/disabling OPA Gatekeeper

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#376]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster.
2. Navigate to 'Dashboard' -> OPA Gatekeeper
3. Click enable OPA Gatekeeper.

**Result:**
'Rancher-gatekeeper-operator' app deployment starts and it takes around 1-2 minutes. The UI doesn't doesn't show any indication that app is getting deployed.
Similarly for during deletion, there is no indication of process in progress.

**Expectation**
There should be some indication that app is getting deployed/process is running and user can check built in templates created once the enabling gatekeeper process get completed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2450-head- 73f603f9f
- Installation option (single install/HA): Single

**Comment by westlywright** [comment]
When the fix is merged the loading button will be the indicator and will display 'loading' with a spinner until the app is deployed.

**Comment by khushboo-rancher** [comment]
Tested on master-2486-head- cf6d0c979

After enabling gatekeeper, enable button shows 'enabling' text and waits for app to be deployed. 
While disabling the remove resource happens immediately and no state transitions so no 'loading with spinner' displayed on UI.
