### ISSUE TITLE
RKE2 Cluster Template `view chart info` page does not have useful links

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3763]
on 2.6.0-rc1

Issue: 
<img width="1622" alt="Screen Shot 2021-08-10 at 12 52 40 PM" src="https://user-images.githubusercontent.com/16691014/128926286-6f5fc135-2264-4a15-a4b2-30e20bcf2f79.png">
amazonec2, values.yaml, etc. all link to <ip>/dashboard/<provider>.yaml

Repro steps:
* add an RKE2 cluster template 
* install a cluster using the template -> visit the `view chart info` from the chart

Solution: 
* I'm not entirely sure where this should link to, but my guess would be to link to the example chart for each respective field.  i.e. amazonec2 links to https://github.com/StrongMonkey/cluster-template-examples/blob/new1/charts/values-aws.yaml. Though I'm not sure if this is the 'official' example RKE2 template, or if we will have one added in rancher repo?

**Comment by richard-cox** [comment]
The links come straight from the chart's README, they would need to be absolute and not relative

**Comment by nwmac** [comment]
For now, we will not render relative links as links, since we don't have the base URL to which they are relative.

**Comment by slickwarren** [comment]
on 2.6.0-rc4, the links no longer appear for relative links in `chart info` pages. cc @StrongMonkey for this chart, would there be a better option for links in the readme?
