### ISSUE TITLE
Upon editing a cluster owner member is not populated

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#3768]
**I'm pulling this single item from this issue https://github.com/rancher/dashboard/issues/3727 as it still needs to be tracked but it's not related to the other items.**

I created a cluster with all defaults in the UI. When editing, the following fields are not populated and I can't save the cluster. I'm marking it as a release-blocker since I can't actually edit the cluster. 

Note: I have permissions for the cluster as I am able to view the cluster in my cluster dropdown, navigate to it and create k8s resources through the ui. 

Member Roles - I am the cluster creator/owner of the cluster and can see it when creating the clsuter, but it doesn't populate anything when I go to edit the cluster. I have the permissions to view the cluster in the cluster dropdown, so not sure why it's not populating here. 

<img width="976" alt="Screen Shot 2021-08-08 at 9 19 06 PM" src="https://user-images.githubusercontent.com/11410997/128660051-cfe1b5b8-547f-491c-b571-ecbb3bd488aa.png">

**Comment by codyrancher** [comment]
As I noted elsewhere. This issue appears to be coming from the backend. The backend doesn't appear to create the owner clusterroletemplatebinding which this issue presents itself.

**Comment by snasovich** [comment]
@codyrancher , is this V2 (RKE2) provisioning specific or happens for RKE1 too?

**Comment by deniseschannon** [comment]
I think this has been resolved and working now? Can you double check this @codyrancher ?

I believe I validated this use case for standard users and it was working towards the end of last week.

**Comment by codyrancher** [comment]
@deniseschannon looks fine on my end. We do see system accounts now which is captured in https://zube.io/rancher/dashboard-ui/c/3815.

**Comment by kravciak** [comment]
When I edit `RKE2` `DO` cluster that I created as `Standard-User` in dashboard I can see 3 owners in Member Roles.
I see the same when I edit cluster as `Admin`.

![Screenshot from 2021-08-18 11-57-06](https://user-images.githubusercontent.com/538604/129884570-934a1c02-75f8-4127-8880-5c8aab18a084.png)

So cluster owner roles are populated, but I reopened https://github.com/rancher/dashboard/issues/3256 for the principal

**Comment by kravciak** [comment]
Reopening, it worked fine yesterday, there are no roles today again.

![Screenshot from 2021-08-19 13-12-56](https://user-images.githubusercontent.com/538604/130059305-9c8fe5f5-759e-411d-8637-57a840a9518d.png)

v2.6-head (2778eca)

**Comment by codyrancher** [comment]
@kravciak was the cluster still being provisioned when you edited? 

The backend provisions the binding so if it hasn't done that yet we don't show the member. It seems that we do display it once it exists.

**Comment by kravciak** [comment]
> Nevermind, I just realized that it was requiring a page refresh to show.

As Standard-User I can't see them even after page refresh (on DO RKE2 cluster that I created as Standard User)

**Comment by kravciak** [comment]
Works fine on v2.6-head (b8a44fa)

![Screenshot from 2021-08-23 09-10-00](https://user-images.githubusercontent.com/538604/130405363-6c149ac3-a887-42d0-abda-9541a935fb98.png)
