### ISSUE TITLE
Machine Pools page under clusters in Cluster Management, does not show status as Cordoned

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3770]
**On 2.6-head commit id: `723f747`**

- Deploy an RKE1 cluster
- Upgrade k8s version of a cluster from say 1.19 to 1.20
- Navigate to Machine Pools page  --> Cluster details in the cluster list page in Cluster Management.
- The nodes will be seen in `Upgrading` state with "Upgrading" text below the state of the node.
- Whereas in the Kube nodes page of the cluster the sate will be seen as `Cordoned`. 

In Ember UI, all of this was in one page. But this is a change in behavior, Can we have the status of the nodes, in Kube nodes page, reflect in this page (Cluster management) ?

**Comment by richard-cox** [comment]
These are two different resources.

The Machine Pools list shows machine's and their status (which is Upgrading). The Kube Nodes list shows native kube nodes and their status (which is Cordoned). We shouldn't replace the Machine status with the Node status.

We do show the Node associated with the Machine though, so might be able to show it's status there
