### ISSUE TITLE
Unable to add parameters in constraints

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#378]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

***scenario 1***
**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable OPA gatekeeper.
2. Create a constraint in form view with parameters

**Result:**
UI throws error ```{ "type": "error", "links": {}, "code": "Invalid", "message": "K8sAllowedRepostest1.constraints.gatekeeper.sh \"test\" is invalid: spec.parameters.repos: Invalid value: \"string\": spec.parameters.repos in body must be of type array: \"string\"", "status": 422 }```

***Expectation***
Constraint should get created with parameter filled in form.

***Other helpful details***
The request contains ```"parameters":{"key":"value"}``` info which is throwing error, if we pass ```"parameters":{"key":["value"]}``` it works fine.  

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2463-head- e651c7a81
- Installation option (single install/HA): Single

**Comment by loganhz** [comment]
There are 3 things cause users cannot add constraints via Form to leverage the 2 default constraint templates in Rancher.

- Our 2 default templates take array , but in constraint form, there is no way to add array type
- When users didn't input any kind, UI sends an empty array. So the constraint cannot be attached to any resource.
- When users didn't input any namespace, UI sends an empty array. So constraint will not take effect.

**Comment by codyrancher** [comment]
This is resolved in the latest. You can now edit the parameters as yaml if complex objects are required.

**Comment by izaac** [comment]
I tried to validate this in the latest Dashboard but clicking create returns page not found.
Details: https://github.com/rancher/dashboard/issues/660

**Comment by izaac** [comment]
@codyrancher using the latest UI with `CATTLE_DASHBOARD_INDEX` pointing to latest index during Rancher single install I'm trying to add the `labels` parameter in a constraint using the `k8srequiredlabels` template with the following:

Key:
`labels`
Value:
`[ { "allowedRegex": "^$|^[a-zA-Z0-9]+", "key": "gatekeeper" } ]`

I keep getting:
```
 { "type": "error", "links": {}, "code": "Invalid", "message": "K8sRequiredLabels.constraints.gatekeeper.sh \"test-labels\" is invalid: spec.parameters.labels: Invalid value: \"string\": spec.parameters.labels in body must be of type array: \"string\"", "status": 422 }
```

Is this a proper value for that parameter? I see the same value if I edit it as YAML and then I view the constraint as Form in the UI.

**Comment by izaac** [comment]
Validated that simple parameters are working in latest Dashboard Index 
https://github.com/rancher/dashboard/issues/670

- Rancher version: `v2.4-head (05/19/2020)` 8e20687a4
- Installation option (single install/HA): Single
