### ISSUE TITLE
As user I am not able to add machine pool to RKE2 cluster

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3780]
I can't add machine pool (RKE2) as `User-Base` with `Create new Clusters` role (Dashboard)

As Admin:
- Create user with `User-Base` Global Permissions
- Add `Create new cluster` built-in role to the user

As User:
- Create new cluster (DO)

Result: User is not able to add machine pool, there are `+` and `-` buttons that are not clickable

![step5](https://user-images.githubusercontent.com/538604/129012430-cb67863c-3b1f-48a9-b465-9db8e74a0b14.png)

Tested on: v2.6-head (9d2e086)

**Comment by richard-cox** [comment]
```
Error in fetch(): Error: Unknown schema for type: management.cattle.io.roletemplate
    at Object.eval (getters.js?57aa:265)
```
Looks like users with that role don't have access to `/v1/schemas/management.cattle.io.roletemplate`. There could be range of others as well, would be a voyage of discovery. Pinging @dramich

**Comment by dramich** [comment]
This is expected, user-base nor does the create-cluster permissions grant that. That schema should not be needed to create a cluster.

**Comment by richard-cox** [comment]
Ok, chatted with Dan. The base user with the create cluster settings should not be able to provider membership details at edit/create time. We need to hide the relevant component. Also need to investigate how we handle other role based parts of the ui after creating that cluster (like project, make sure users & auth pages are ok, etc)

**Comment by richard-cox** [comment]
I'm in the process of removing membership features from the create cluster process (for this specific use case) and have hit another permissions thing. When creating an RKE2 Digital Ocean instance the `rke-machine-config.cattle.io.digitaloceanconfigs` schema is missing and we fail to show any machine pool options in the ui. 

I'm not 100% sure, but would `clusters-create` need both of the following? @dramich 
```
addRule().apiGroups("rke-machine-config.cattle.io").resources("*").verbs(*)
```
Possibly also?
```
addRule().apiGroups("rke-machine.cattle.io").resources("*").verbs("get", "watch")
```

**Comment by dramich** [comment]
https://github.com/rancher/rancher/pull/34199

**Comment by richard-cox** [comment]
Moving to working, just to validate rest of flow is fine, before passing to QA

**Comment by kravciak** [comment]
Works fine on v2.6-head (c10ef4b).

I can create RKE2 DO cluster as User-Base with `Create new cluster` role.
