### ISSUE TITLE
As user with Manage Roles permission I can't create Cluster Role

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3783]
As Admin:
- Create user with `User-Base` Global Permissions
- Add `Manage Roles` built-in role to the user

As User:
- Users & Authentication -> Roles -> Create Cluster Role

Result: HTTP Error 403: Forbidden. Method GET not supported

Tested on: v2.6-head (9d2e086)

**Comment by richard-cox** [comment]
403 v1/management.cattle.io.clusters/local

This will be a `currentCluster` issue (user does not have access to it)

**Comment by kravciak** [comment]
I can create new role as User-Base with Manage Roles permission
Tested on: v2.6-head (c10ef4b)
