### ISSUE TITLE
As standard user I can't edit cluster I created

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3785]
As Admin:
- Create user with `Standard-User` Global Permissions

As user:
- Create RKE2 cluster: Cluster Management -> Create -> RKE2 (DO)
- Refresh page in browser
- Open Cluster Management -> cluster -> Edit Config

Result: Page is stack at `Loading...`
Error in console: `TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))`

Tested on: v2.6-head (9d2e086)

**Comment by richard-cox** [comment]
403 when fetching `digitaloceanconfigs.rke-machine-config.cattle.io` (`/v1/rke-machine-config.cattle.io.digitaloceanconfigs/fleet-default/nc-richard-cox-rke2-user-pool1-gwlj7`) 

```
client.js?06a0:97 TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at _createForOfIteratorHelper (rke2.vue?4a6e:51)
    at VueComponent.nodeTotals (rke2.vue?4a6e:501)
```

I think this is a problem with construction of the resource type, `rke-machine-config.cattle.io.digitaloceanconfigs` exists, not the other way around. Will investigate

**Comment by richard-cox** [comment]
On refresh I can't see the edit option for the cluster, but when viewing the config get a similar error when tryn

`/v1/rke-machine-config.cattle.io.digitaloceanconfigs/fleet-default/nc-richard-cox-rke2-user-pool1-gwlj7`

message from response was `message: "digitaloceanconfigs.rke-machine-config.cattle.io "nc-richard-cox-rke2-user-pool1-gwlj7" is forbidden: User "u-bvws9" cannot get resource "digitaloceanconfigs" in API group "rke-machine-config.cattle.io" in the namespace "fleet-default": RBAC: [role.rbac.authorization.k8s.io "crt-minikube-cluster-member" not found, role.rbac.authorization.k8s.io "crt-richard-cox-rke2-user-cluster-owner" not found, role.rbac.authorization.k8s.io "crt-c-7r2dg-cluster-owner" not found]"`_

**Comment by richard-cox** [comment]
I'm not sure what was causing the previous error, but i cleared out all clusters and tried again.

It doesn't look like the permissions to `rke-machine-config.cattle.io.digitaloceanconfigs` are getting updated following a user gaining access to their first cluster (even after many minutes and refreshes).

`/v1/schemas/rke-machine-config.cattle.io.digitaloceanconfig` contains no resourceMethods GET, only collectionMethods POST
`/v1/rke-machine-config.cattle.io.digitaloceanconfigs` returns an empty list
as per above `/v1/rke-machine-config.cattle.io.digitaloceanconfigs/<namespace/<id>` returns 403

The user has a `management.cattle.io.clusterroletemplatebindings` with `cluster-owner`

@dramich Could you assist?

**Comment by richard-cox** [comment]
Adding this as a release blocker as it effects the non-admin cluster experience stories

**Comment by dramich** [comment]
I shall take a look

**Comment by dramich** [comment]
@richard-cox The backend for this is in.

**Comment by richard-cox** [comment]
Looking good! Moving to... to test

**Comment by kravciak** [comment]
Works fine on v2.6.0-rc3, I can open `Edit Config` menu as user
