### ISSUE TITLE
As user with Manage Cluster Members role I am able to escalate my permissions

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3788]
As Admin:
- Create cluster (RKE2 DO)
- Create user with `Standard-User` Global Permissions
- Add user to this cluster with `Custom - Manage Cluster Members` role (Explore -> RBAC -> Cluster Members)

As User:
- Go to Menu -> cluster -> RBAC -> Cluster Members
- Add -> add myself as Cluster Owner

Result: I have full permissions to the cluster now
Expected: I should be able to grant only permissions that I already have

Tested on: v2.6-head (9d2e086)

**Comment by richard-cox** [comment]
@kravciak Is this a regression? Feels like it's working as intended.

**Comment by kravciak** [comment]
I can do the same in EmberUI. It might be intended, I am not sure.
When I assign global permissions I can't escalate them this way. Only on cluster level.

**Comment by catherineluse** [comment]
I could not reproduce this issue in v2.7-head.

**Comment by richard-cox** [comment]
Adding milestone that's monitored by QA

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head. However, I'm creating issue #11263 for the UI to display better warning messages in case of permission denied.
