### ISSUE TITLE
As standard user I am not able to add list other users

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3790]
As Admin:
- Create cluster (RKE2 DO)
- Create user1 with `Standard-User` Global Permissions
- Add user to this cluster with `Cluster Owner` role (Explore -> RBAC -> Cluster Members)
- Create a project1
- Create second user2 (Standard-User)

As User1:
- Go to Menu -> cluster -> Projects and Namespaces
- project1 -> Edit Config
- Add user2 to the project

Result: `You are the only active registered user`

Expected:
 - I should be able to add users to the project
 - If I assign user1 `Manage cluster members` global role I can see user list

![Screenshot from 2021-08-11 15-30-00](https://user-images.githubusercontent.com/538604/129037767-bb66ccbc-770e-4840-83fd-6fa26befc140.png)

Tested on: v2.6-head (9d2e086)

**Comment by mantis-toboggan-md** [comment]
This looks like an issue with permissions @dramich ? A standard user with the Cluster Owner role in a downstream cluster can technically GET the list of users needed here (from `/v1/users`) but only see their own user resource. ...This is how projects/namespaces work in the old UI as well so is this an expected limitation? If so, the dashboard can be updated to handle these situations better/be more informative but I'd like some clarification on that before proceeding.

**Comment by dramich** [comment]
User search uses principals, not users, so only seeing yourself under /v1/users is expected unless you are an admin.

**Comment by mantis-toboggan-md** [comment]
Yeah I didn't look closely enough at the components in this form; /v1/users was only being used to disable the 'add' button and show 'You are the only active registered user.' So entirely a UI bug :)

**Comment by kravciak** [comment]
I can add other users to the project as standard user, closing - v2.6-head (25d39aa)
