### ISSUE TITLE
Delete Multiple Clusters

### ISSUE THREAD

**Issue by naeemarsalan** [rancher/dashboard#3795]
In Rancher 2.5.8 you can select tick multiple clusters and delete them. In 2.6 UI there is no way to delete these clusters from the dashboard also stuck clusters are no way to remove them.

**Comment by naeemarsalan** [comment]
I noticed this can be done in Cluster Management but this is not very clear coming from 2.5.8

**Comment by cloudnautique** [comment]
@naeemarsalan is this from the new `home` landing page? Would a quick link over to cluster manager from here help?

**Comment by naeemarsalan** [comment]
Correct the new home landing page, quick link, or maybe just have cluster manager as the first page. If someone came off 2.5.8 to 2.6 they will be confused.

**Comment by richard-cox** [comment]
To clarify, all cluster life cycle actions (create, update, delete, etc) are done via the `Cluster Management` section. Cluster resource management is done via the `Explore Cluster` pages as linked from the home page. This was a new paradigm in the dashboard UI.

@kwwii I'm not sure there's much for us to do here, but leaving for your final say

**Comment by kwwii** [comment]
I think we should have a better plan for the long term integration of the cluster management and the cluster explorer UIs rather than trying to add another link between the two.

Let's close this for now and create another issue for that work.
