### ISSUE TITLE
Rancher only warns when apps are managed by Helm, but not by other app managers

### ISSUE THREAD

**Issue by richard-fairthorne** [rancher/dashboard#3804]
Rancher 2.5.9 Provides an important warning when the app.kubernetes.io/managed-by label is set to Helm.

![Screen Shot 2021-08-11 at 4 37 09 PM](https://user-images.githubusercontent.com/1225460/129099679-d74ce4da-49ce-4bd4-b65a-485b3c76a991.png)

The warning reads: "**This Ingress is managed by a Helm app; changes made here will likely be overwritten the next time the app is changed.**"

A similar warning should be provided for any setting of that label, but it is not. The warning should also be more severe.

![Screen Shot 2021-08-11 at 4 40 40 PM](https://user-images.githubusercontent.com/1225460/129100116-5fcb95aa-9587-46a3-847f-f77d1f4e5bd6.png)

A warning should appear with useful information such as: "**This ingress is managed by _SuperAppManager_. Changes here may break the app, and could be overwritten.**"

Finally, I think it would be desirable to have the data entry form be disabled until the user acknowledges the warning.

**Comment by vincent99** [comment]
I agree that there's little reason for it to be helm-specific so we can remove that condition.  But saying that you can break the resource is redundant, you can always break things if you want to and we have no information to know if your changes will or won't, especially for an unknown manager.

**Comment by kravciak** [comment]
Works fine on v2.6-head (4def656)

![Screenshot from 2021-08-13 12-11-24](https://user-images.githubusercontent.com/538604/129342037-1b6c572d-29a6-47e7-8ac8-c0141a8f3730.png)
