### ISSUE TITLE
Worker CIS Profile - Default is blank instead of (None)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#3805]
Worker CIS Profile is only shown on custom clusters and there is a `(None)` option, but it's not selected as the default value when creating a custom cluster.

<img width="661" alt="Screen Shot 2021-08-11 at 3 21 31 PM" src="https://user-images.githubusercontent.com/11410997/129111675-8eab8214-f59b-4c12-8806-cd07ff5112e2.png">

v2.6-head 8/11 mid day

**Comment by richard-cox** [comment]
@neillsom This also needs to go in to `release-2.6` branch. You need to create another PR with this change on that branch. You should be able to check out that branch and cherry-pick the commit.

**Comment by kravciak** [comment]
Works fine on v2.6-head (c10ef4b)

![Screenshot from 2021-08-18 14-51-36](https://user-images.githubusercontent.com/538604/129901204-cfcc3758-3cf7-4925-9cb3-bb547f1c095f.png)
