### ISSUE TITLE
Forward port "Add Schedule" and "Add alert" features for CIS scans

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3806]
**On 2.6.0-rc2**

- Note this is an upgraded rancher from 2.5.9 to `2.6.0-rc2` . In order to get the `Legacy` option on a fresh install, Legacy has to be set to true. 
- On 2.5.9, deploy a downstream RKE1 cluster
- Upgrade rancher to 2.6.0-rc2
- Under `Legacy` option in the cluster --> CIS 
- The `Add Schedule` and `Add alert` buttons look disabled in CIS v1 scan page.

<img width="1431" alt="Screen Shot 2021-08-11 at 3 58 07 PM" src="https://user-images.githubusercontent.com/26032343/129115850-c4b175a6-76de-4d18-9f7c-f8b2f71e8f32.png">

**Comment by catherineluse** [comment]
I've changed the issue title to forward port those features, since they are not present in the newest version of the dashboard:
<img width="1480" alt="Screenshot 2022-11-05 at 4 07 40 PM" src="https://user-images.githubusercontent.com/20599230/200145160-794ad75a-2fb8-499a-8495-f69a4409ffdf.png">

**Comment by gaktive** [comment]
Closing as old. If anyone still sees any issues here in a newer version, let us know and reopen or file a new ticket with a link back here.
