### ISSUE TITLE
Unable to add additional cluster members even though the default admin and other users exists

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#3807]
v2.6-head 6cb1847 8/11 5pm

1. Set up HA Rancher cluster
2. Create a standard user `test1`
3. Log in as `test1`
4. Create a cluster
5. Unable to add any other members to the cluster even though the default admin exists as well as other standard users

Note: If I log in as an admin, I can add members. My theory is that it has to do with being the cluster owner. 

<img width="648" alt="Screen Shot 2021-08-11 at 4 39 37 PM" src="https://user-images.githubusercontent.com/11410997/129117232-49090b52-ebc4-4181-83fc-43d9774fd6fd.png">

**Comment by deniseschannon** [comment]
Note: I'm also unable to add in project members with the same issue. 

I'll be filing a separate issue for showing the "System account" user. 

<img width="831" alt="Screen Shot 2021-08-11 at 4 43 56 PM" src="https://user-images.githubusercontent.com/11410997/129117469-2328b316-0211-4590-8506-893d7d2beeff.png">

**Comment by richard-cox** [comment]
This was happening due a perceived lack of users to add to (aka response of v1/mgnt users only ever returning themselves). This feature was recently removed in https://github.com/rancher/dashboard/pull/3800 and won't come back until https://github.com/rancher/dashboard/issues/3813 is resolved in 2.6.x.

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head b2a2948`

As standard user I was able to add another standard user as Member of the Cluster on existing RKE1 and RKE2 clusters:
![add_member_as_stduser](https://user-images.githubusercontent.com/12828077/129326342-b73a273c-6489-4d91-a053-4c5b6f19f894.png)

It is possible to assign an user when defining a new RKE2 cluster (prior bootstrap):
![add_member_as_stduser_rke2](https://user-images.githubusercontent.com/12828077/129326257-be791120-2d7c-4937-b584-8c23cebc14bb.png)

But it is impossible to assign another user when defining a new RKE1 clusters (prior bootstrap) in iframe as standard user,  `admin` is allowed to do it. For this I opened extra issue https://github.com/rancher/rancher/issues/34230

The issue with assiging Members to a new or existing project is solved:
![add_member_to_existing_project_as_stduser](https://user-images.githubusercontent.com/12828077/129327324-c22cc069-d975-406d-b2ef-f293c210027a.png)


Close.
