### ISSUE TITLE
Project Membership shows System Account as a user

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#3808]
v2.6-head 6cb1847
8/11 - 5pm

Under Project Membership for the Default project, it's showing system account as a user. This is not a real user and shouldn't be on the list. 

<img width="831" alt="Screen Shot 2021-08-11 at 4 43 56 PM" src="https://user-images.githubusercontent.com/11410997/129117547-ca88ddd1-3ce1-47cd-9776-c8bdd8dd59ad.png">

**Comment by richard-cox** [comment]
This was a regression based on https://github.com/rancher/dashboard/commit/e34468e7eb854e3c7fd0414e50ada021184b3682. We have an internal slack thread discussing it.

**Comment by codyrancher** [comment]
This is a dupe of https://github.com/rancher/dashboard/issues/3256 so I'm closing it.
