### ISSUE TITLE
pipelines (an <iframe> view) auto-scroll to the bottom of the screen when running.  Each new log autoscrolls to the bottom of the screen

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3809]
on v2.6.0-rc2 (after an upgrade of rancher from v2.5.9)

**Repro Steps:**
* install pipeline to a cluster through vue's `legacy -> project -> pipelines` screen
* run a job

**Result:** 
* as the pipeline is running, user's screen scrolls to the bottom of the screen as logs are coming in. It very quickly gets to a point where the user can't leave the page through the UI.

**Comment by nwmac** [comment]
@slickwarren Do you have a repository and pipeline I can use for testing?

**Comment by nwmac** [comment]
@slickwarren Actually - this is going to be easier if you have a system I can use to reproduce.

**Comment by nwmac** [comment]
I didn't get a problem leaving the page - I couldn't see any behaviour different to the Ember UI - would be good to understand the problem.

From my testing, I think we can defer this post 2.6

**Comment by slickwarren** [comment]
I've repro'd this @nwmac, please ping me for the setup details when you're ready

**Comment by nwmac** [comment]
We are removing pipelines for 2.7.0, so this will no longer be an issue.

**Comment by slickwarren** [comment]
confirmed that as of v2.7-head (c567ef3), pipelines are no longer an option through the UI:
<img width="235" alt="Screen Shot 2022-09-27 at 2 03 16 PM" src="https://user-images.githubusercontent.com/16691014/192634956-359d0178-a931-4628-95b1-4ef99ddecd59.png">

for posterity, also tested through ember, and the user gets an error about `no schema` if they select pipelines for a given cluster.
