### ISSUE TITLE
Improve `Navigation Cancelled` error handling

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3810]
- vue router throws an uncaught exception quite often regarding `Navigation Cancelled`
  - does this only appear when url fragment is used?
- this appears in the console and is harmless but causes confusion with QA/Others
- We could ...
  - investigate why this occurs, are we using router wrong?
  - disable this kind of thing in production?
  - better handling the error (reduce logging level, swallow, etc?)

https://router.vuejs.org/guide/advanced/navigation-failures.html#detecting-navigation-failures

**Comment by richard-cox** [comment]
I've seen the following reliably recreating when switching between cluster manager Pod Security Policies and Clusters pages
```
vue-router.esm.js?8c4f:1958 Uncaught (in promise) Error: Navigation cancelled from "/c/local/manager/pages/pod-security-policies" to "/c/local/manager/provisioning.cattle.io.cluster" with a new navigation.
    at createRouterError (vue-router.esm.js?8c4f:1958)
    at createNavigationCancelledError (vue-router.esm.js?8c4f:1940)
```

**Comment by vincent99** [comment]
(One way) It happens when there's more than one redirect.  Last time I looked there was no good way to get it to not complain, short of redefining console functions.

**Comment by richard-cox** [comment]
No longer reproducible
