### ISSUE TITLE
After deleting clusters- status still seems strange and is stuck

### ISSUE THREAD

**Issue by claudioser** [rancher/dashboard#3818]
After deleting clusters- status still seems strange, but on the top left it has been updated to say 1 cluster.
UI is stuck like this forever ( well.. more than 15mins )... only way, is to refresh page

![image](https://user-images.githubusercontent.com/53047113/129184582-22d6b03b-fc3f-402f-bf0e-288f840d9238.png)

Using rancherImageTag=master-c58f95221d76c6e6a32c89426b300f8afd2ab69a-head

**Comment by richard-cox** [comment]
Please can you retest with the latest version (as of writing 2.8.3) and re-open if still applicable?

Inconsistency between clusters and the side nav isn't something we've in released versions (there's a current bug in 2.9 with a pending fix...)
