### ISSUE TITLE
Fleet clusters added to fleet-local aren't included in target selection

### ISSUE THREAD

**Issue by nickgerace** [rancher/dashboard#3826]
Since `fleet-local` usually only has one cluster, the local Fleet cluster, it is likely that we only expect there to ever be one target in the `fleet-cluster`. The target selection for a GitRepo does not include clusters added to `fleet-local` as a result. While that might be an anti-pattern, we should anticipate this use case and remove assumptions about what kinds of clusters live in `fleet-local`, _or_ we expose the targets when there are at least two clusters in `fleet-local`.

cc: @StrongMonkey

**Comment by vincent99** [comment]
This is an intentional special case because fleet-local is (or was) special on the backend too and always included only local.

**Comment by nwmac** [comment]
So, what needs to be done here?

**Comment by nickgerace** [comment]
**_Likely_**, we need to either update how `fleet-local` works in UI to make it behavior (at least somewhat) more like other `FleetWorkspaces` _or_ document that `fleet-local` will behave differently in our UI.

**Comment by vincent99** [comment]
We've previously discussed that fleet-local is intentionally special, the UI reflects that, @ibuildthecloud thinks it should stay that way.  

So you probably shouldn't be doing whatever it is that is causing there to be more than one cluster in that workspace to begin with (and probably validating webhook should prevent it), not changing the UI to accommodate it.

**Comment by nickgerace** [comment]
> We've previously discussed that fleet-local is intentionally special, the UI correctly reflects that, and @ibuildthecloud thinks it should stay that way.
> 
> So you probably shouldn't be doing whatever it is that is causing there to be more than one cluster in that workspace to begin with (and validating webhook should likely prevent it), not changing the UI to accommodate it.

Closing this issue accordingly and a [new docs issue will cover it](https://github.com/rancher/fleet/issues/654) in our ongoing Fleet docs re-write.
