### ISSUE TITLE
UI needs to be refreshed so it's reflects a Project have been deleted

### ISSUE THREAD

**Issue by igomez06** [rancher/dashboard#3828]
on v2.6.0-head on commit-id: `0784199`

**Repro Steps:**

- Create a project.
- Delete that project.

**Result:**

- The project appears to be not deleted, but when the webpage is refreshed the project is then removed from the UI.

**Comment by nwmac** [comment]
@codyrancher This is not critical, but if its a quick fix would be good to get in.

**Comment by codyrancher** [comment]
I actually think this may be an issue with management resources in general. I just noticed this happening with globalRoleBindings as well.

**Comment by gaktive** [comment]
Vince seeing some additional problems whereby the Save button is disabled when he tried creating a 2nd project without an explanation as to why.

**Comment by gaktive** [comment]
As a data point, trying this out in Ember works fine and seeing a project creation attempt live in another tab on Vue shows a live update with the correct info. So Vue is doing something different here...

**Comment by kravciak** [comment]
I can create / delete projects as admin on RKE2 DO cluster without any issues.
In v2.6-head (70f024e)
