### ISSUE TITLE
CronJob redeploy: Cannot read property 'metadata' of undefined

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3835]
When I try to redeploy CronJob button acts as non-clickable and it produces:
```
TypeError: Cannot read property 'metadata' of undefined` in console
```

To reproduce:
- create single node DO infra provider cluster (RKE2)
- deploy Cronjob (https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/job/cronjob.yaml)
- click `Redeploy`

![Screenshot from 2021-08-13 09-44-07](https://user-images.githubusercontent.com/538604/129322405-c203c608-6ba0-4b77-8bfb-18eb53cbde5a.png)

Rancher: single node docker v2.6-head (4def656)

**Comment by rak-phillip** [comment]
@kravciak it sounds like redeploy isn't a valid action for cron jobs, so we should be disabling this action.

**Comment by kravciak** [comment]
Redeploy buttons are gone from v2.6-head (b3980c2)
