### ISSUE TITLE
Cannot distinguish between placeholder/hint and default values in input fields in dark mode

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3837]
Seen on `rancher/rancher:v2.6-head 4def656`

Eg. when defining a new AKSv2 cluster in Explorer there are some input boxes which have no default value set but they look like they have it - I'd say the placeholder/hint texts are a bit grayed out but not enough, it is not so obvious if you compare with boxes with the default values set.

![aks_hint](https://user-images.githubusercontent.com/12828077/129343664-f3050d6a-08d0-4a15-b983-69334c14986c.png)

**Comment by thehejik** [comment]
It is not better in light mode:
![aks_hint_light](https://user-images.githubusercontent.com/12828077/129348621-6ae88356-bd58-4f0c-8c99-186441139224.png)

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.6-head` `version 9d5c699`

Placeholder text is greyed out more during AKS cluster creation:
![Screen Shot 2021-08-18 at 3 43 37 PM](https://user-images.githubusercontent.com/57409052/129984228-bfd5969e-451a-4f34-a289-5d0c16c54b8f.png)
Default text in `Linux Admin Username` retains opacity.

Will track fix for light mode here:
