### ISSUE TITLE
Unable to delete a project role from the User Detail project role list

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3840]
![image](https://user-images.githubusercontent.com/18697775/129394052-02d7ae63-48ae-496b-ae26-ce7d3c02243f.png)

**Comment by kravciak** [comment]
Fixed in v2.6-head (c10ef4b), I can delete project role as admin.

![Screenshot from 2021-08-18 16-27-53](https://user-images.githubusercontent.com/538604/129916504-e0493bb5-65af-4f16-bd6e-15c7ec53905f.png)
