### ISSUE TITLE
When editing cluster as yaml sometimes passwords are injected

### ISSUE THREAD

**Issue by Tejeev** [rancher/dashboard#3843]
Internal reference: SURE-1974

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Sometimes when editing the cluster yaml will have a secret key injected.  It would save time and trouble if we could prevent this auto fill (key in screenshot is false).
![image](https://user-images.githubusercontent.com/8906089/79599642-c76a9480-80dd-11ea-83cc-b41e3420c5d9.png)

I am still gathering information from the customer but we've observed this on Chrome in Windows

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.9 and v2.3.5

gz#9812

**Comment by codyrancher** [comment]
@gaktive @Tejeev `autocomplete="off"` has been set on all inputs for at lest 4 years (https://github.com/rancher/ui/blob/master/app/initializers/extend-ember-input.js#L16). 
![Screenshot from 2022-01-06 14-37-58](https://user-images.githubusercontent.com/55104481/148455715-5a0ea67b-96a3-4e68-8404-3f1b2824412e.png)

I've attempted to reproduce this, I've verified that I have password autofill on for chrome and I'm not prompted to save the password nor does it fill the password in for me.
![image](https://user-images.githubusercontent.com/55104481/148456524-f8bac6a5-95ba-43f6-bb03-19131d6a8736.png)

Are there more detailed repro steps (maybe starting with a fresh chrome install) that I could use?

**Comment by Tejeev** [comment]
@livenson are you still seeing this issue?  Please see Cody's reply above.

@codyrancher from my understanding of the linked bug, the actual problem is that autocomplete does _not work_ for chrome on input and form (which is what you are saying we've been using for 4 years, if I understand correctly) 
Please see https://bugs.chromium.org/p/chromium/issues/detail?id=468153 (discussed in the link provided by Ilja here: https://github.com/rancher/dashboard/issues/3843#issuecomment-663653901)

**Comment by Jono-SUSE-Rancher** [comment]
Hey @gaktive - I was meeting with the team during some triage and we noticed this is in Backend Blocked. I don't think this is backend blocked, but maybe you meant to put it in "Needs Info"?

**Comment by gaktive** [comment]
@Jono-SUSE-Rancher the UI repo doesn't have that column but I can create a label and put it in Backlog for now, then figure out a process with @nwmac

**Comment by Tejeev** [comment]
What info can I help you get?  Did I misunderstand the linked bug report? If not it looks like we've been doing exactly what it says not to?

**Comment by catherineluse** [comment]
@Tejeev Does this bug only happen for RKE1 clusters?

**Comment by Tejeev** [comment]
Honestly not sure.  Funny you should follow up on this.  Mel and I were just discussing the ticket that originated these gh issues.
Let's see if they are still even seeing the issue as it was a UI thing and there have been a lot fo changes to the UI since this was initially opened

**Comment by gaktive** [comment]
Support closed the related ticket so closing this.
