### ISSUE TITLE
Unable to create cluster with s3 snapshot config, UI sends POST to cloudcredentials and server responds with 422

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#3847]
I believe this is most likely a rancher backend issue. If I am mistaken please let me know so I may transfer the issue.

**Environment:**
v2.6-head `4def65610` 8/13/21 10:50 am Pacific single-node docker

**Summary:**
Unable to create RKE2 cluster in Vue UI when I specify s3 info on the cluster creation page. I get an error in the UI as seen below in the screenshot.
![image](https://user-images.githubusercontent.com/45179589/129603974-aa035e52-28d6-4a44-a979-6a11c5fc6a53.png)

The UI sends a POST to `cloudcredentials` upon trying to create this cluster with the following as the request body:
```
{
    "type": "cloudcredential",
    "s3credentialConfig": {}
}
```
And with a response of HTTP 422 with this body:
```
{
    "baseType": "error",
    "code": "InvalidFormat",
    "fieldName": "s3credentialConfig",
    "message": "accessKey=MissingRequired 422: ",
    "status": 422,
    "type": "error"
}
```

**The UI does NOT send a POST request to provisioning.cattle.io.clusters, most likely because the cloudcredentials POST failed.**

**Details:**
This blocks testing s3 etcd snapshot/restore.
Related: https://github.com/rancher/dashboard/issues/3844

**Comment by davidnuzik** [comment]
Thanks. Transferred to dashboard project.

**Comment by davidnuzik** [comment]
If I manually create a cloud credential first (s3-compatible) and specify this in drop down for s3 authentication, then I can workaround this issue.

**Comment by vincent99** [comment]
@davidnuzik Blocked on what?  This should work now, it makes a credential and sets the name on the cluster s3 config.

**Comment by davidnuzik** [comment]
Sorry I should have supplied more context. Donnie asked me to try creating an s3-compatible cloud credential first (on the cloud credentials page -- not on the cluster creation form) as long as I do that first THEN use that cloud credential on the cluster-creation form then this will work.

If I create a new s3-compatible cloud credential on the cluster creation form this will not work as per the issue description.

NOTE: This issue was created ten days ago and I have not tried again since. If we have reason to believe this should be working now, then I can try to test this again. (Just let me know).

**Comment by vincent99** [comment]
Yes that's what was fixed 5 days ago, when I moved it to test?

**Comment by davidnuzik** [comment]
I was just responding to your comment you left on Saturday. I moved it to blocked because s3 snapshot/restore doesn't work holistically but yeah I can close this out.

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.
 
**Validation Environment:**

Rancher version: v2.6-head `0935a90` pulled at 8/24/21 11:09 am Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3+rke2r2
 
**Validation steps:**

1. Create and RKE2 cluster, on the cluster creation form, submit valid s3 credentials.
2. This now succeeds without any issues. The UI sends proper request body and I no longer get a 422 error.
3. The cluster comes up and I can take an s3 snapshot.
