### ISSUE TITLE
Private data entry during OCI cluster creation

### ISSUE THREAD

**Issue by thedadams** [rancher/dashboard#3851]
When creating an OCI cluster, the user is presented with the option to enter private key contents, path, and password. These should not be displayed during cluster creation because they are secret and are handled by the cloud credential.

**Comment by thehejik** [comment]
Tested on `rancher/rancher:v2.6-head b8a44fa`.

After enabling `Oracle Cloud Infrastructure` Node Driver I was able to supply fake OCI credentials (just Key and Value) and after that I could pre-configure RKE2 cluster for OCI. I didn't notice any trace of user, password, private keys nor path fields on the `Create Oracle OCI` configuration page. Given that I was using fake credentials I didn't verify deploying of OCI clusters.
![oci_rke2](https://user-images.githubusercontent.com/12828077/130430195-22b38115-d1bf-4a54-b282-8baa8ad7df75.png)

When I tried the same on older rancher/rancher:v2.6.0-rc1 I wasn't able to define OCI credentials with an error: `a Config field must be set` what is not the case for v2.6-head:
![260rc1-oci-creds-fail](https://user-images.githubusercontent.com/12828077/130431365-28108348-e037-471c-aeb0-c985d58e8b08.png)

Close.
