### ISSUE TITLE
Error: "clusterregistrationtokens.management.cattle.io is forbidden: " is seen when a user with no edit access to cluster navigates to cluster details page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3852]
**On 2.6-head commit id: `a55f77f`**
- Create an RKE1 cluster
- Add user1 as Project owner
- Login as this user1
- As project Owner navigate to Cluster details page from Cluster Management page
- An API call is made to `clusterregistrationtokens` -  `https://<rancher-server>/v3/clusterregistrationtokens`
- And Error seen on UI:

<img width="850" alt="Screen Shot 2021-08-14 at 9 44 51 AM" src="https://user-images.githubusercontent.com/26032343/129453372-baf87047-c7c1-435c-b9f3-6506ad905f86.png">

**Expected:**
The call to `clusterregistrationtokens` should not be made when navigating to cluster details page

**Comment by kravciak** [comment]
Works fine on v2.6-head (b8a44fa)

As Admin:
- create RKE1 DO cluster
- create user with User-Base permissions
- create project in DO cluster and add user as owner of the project

As User:
- log in and display cluster details

![Screenshot from 2021-08-23 09-26-31](https://user-images.githubusercontent.com/538604/130412120-44c6a47b-5265-49bc-9d48-835b1832bf10.png)
