### ISSUE TITLE
Import Yaml shows 'default' namespace by default for a project owner who does not have access to this namespace

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3853]
**On 2.6-head commit id: `a55f77f`**

- Create an RKE1 cluster
- Add user1 as Project owner Of a new Project p1 and namespace ns1 _only_
- Login as this user1
- As project Owner Navigate to Cluster Explorer.
- Click on Import Yaml from top right in the cluster context
- Namespace - default is seen

**Expected:**
User does not have access to default namespace in this case, so that shhould not be visible in dropdown. Other System project namespaces are not available in dropdown. Only default and ns1 namespaces are available

**Comment by gaktive** [comment]
This is the same behaviour as seen with kubectl, per @vincent99. Users who aren't a member of the default namespace can query that namespace still via command line.
