### ISSUE TITLE
The warning on the UI for charts not supported for k8s 1.21+ is generic

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3855]
**on 2.6 commit id: `a55f77f`**

- Deploy a downstream cluster
- Warning on the cluster for CIS Scans and Monitoring apps are generic.
- Monitoring v2 and CIS scans v2 are still supported. 

<img width="514" alt="Screen Shot 2021-08-14 at 12 36 33 PM" src="https://user-images.githubusercontent.com/26032343/129458463-ce049c94-e0da-49aa-a879-47149ded6815.png">
<img width="459" alt="Screen Shot 2021-08-14 at 12 36 10 PM" src="https://user-images.githubusercontent.com/26032343/129458464-46732563-49ec-481a-889e-8ffb41c8d8ba.png">

**Expected:**
Warning should call out `v1` charts specifically.

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.6-head` `version 2778eca` with the following steps:
Enable legacy features.
Navigate to CIS scans and project logging.

Result:
The warning for charts not supported has been updated to call out `v1` specifically.
![Screen Shot 2021-08-19 at 10 45 21 AM](https://user-images.githubusercontent.com/57409052/130118379-44d286c5-4244-4a47-a3a0-93c26c8f921f.png)
![Screen Shot 2021-08-19 at 10 30 03 AM](https://user-images.githubusercontent.com/57409052/130116417-a0cff63e-33b4-4ef0-932c-669b7c4245f4.png)
