### ISSUE TITLE
Cluster Alerts page is shown when CIS Scans is selected under Legacy folder

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3857]
On 2.6-head`a55f77f`

- Enable Legacy flag
- Go to cluster explorer of a downstream cluster - RKE1 or RKE2
- Go to Legacy (Expand) this folder
- Click on CIS Scans
- Cluster Alerts page is seen
- Click on Cluster Alerts and then click on CISscans
- CIS scans page will be seen
<img width="1091" alt="Screen Shot 2021-08-14 at 2 26 47 PM" src="https://user-images.githubusercontent.com/26032343/129460455-eb01cbfb-3f3a-4aa1-a770-449b5c6316dd.png">

**Comment by nwmac** [comment]
I could not reproduce this. There may be a corner-case timing issue. @sowmyav27 Does this happen every time? Do you first wait for the page to load before you click on CIS Scans?

**Comment by nwmac** [comment]
Addressed by https://github.com/rancher/dashboard/pull/4112

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `1a57856`**

- Enable Legacy flag
- Go to cluster explorer of a downstream cluster - RKE1 or RKE2
- Go to Legacy (Expand) this folder
- Click on CIS Scans
- Cluster Alerts page is NOT seen and CIS Scan page is only seen.
