### ISSUE TITLE
Namespace/Project filter seems to persist between clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3858]
**on 2.6-head commit id: `a55f77f`**

- Have two downstream clusters. In my case it was one rke1 and one rk2 cluster
- As admin go to rke1 cluster or cluster1 and in the namespace filter/dropdown on the top, select Project Default
- The tabs on the left get filtered.
- `Cluster` tab will not be seen anymore.
- From the left slide in panel, select cluster2 (in my case rke2) cluster
- The `Cluster` tab will not be seen for this cluster even though the namespace/project dropdown/filter says `All Namespaces`

<img width="634" alt="Screen Shot 2021-08-14 at 2 34 55 PM" src="https://user-images.githubusercontent.com/26032343/129460585-0852d204-6b1c-48d4-92c5-01e2f94a974d.png">

To get out of this, user has to select a namespace in cluster2 in the dropdown and unselect or select All namespaces

**Comment by nwmac** [comment]
Confirmed this is a bug - there seems to be an issue with the namespace filter when switching between clusters

**Comment by nwmac** [comment]
@richard-cox Can you take a quick look?

**Comment by Auston-Ivison-Suse** [comment]
1. I am able to reproduce the issue with "cluster" disappearing after the rke1.

2. But the second part where the filter reads "All Namespaces" I am able to see the "cluster" option. 

Numbered screenshots provided. 


1. Screen shot of cluster gone in rke1 cluster: ![Screen Shot 2021-09-16 at 4.35.37 PM.png](https://zube.io/files/rancher/2101c90bf11a51d4cb342eadf0545f16-screen-shot-2021-09-16-at-4-35-37-pm.png)

2. I'm not getting the issue for the rke2 cluster. I might be missing a step. ![Screen Shot 2021-09-16 at 4.42.26 PM.png](https://zube.io/files/rancher/b7b8329a5324304e206140f0f744fb65-screen-shot-2021-09-16-at-4-42-26-pm.png)
