### ISSUE TITLE
Scroll is needed for violations list frame

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#386]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable OPA gatekeeper.
2. Create a constraint which will have around 20 violations.
3. Go to constraint detail page.

**Result:**
There are no scroll separately for violation list frame and constraint details is not visible ,user have to scroll to see the details. It would be helpful to user if they have many violations.
<img width="1378" alt="Screen Shot 2020-03-17 at 5 52 17 PM" src="https://user-images.githubusercontent.com/60111667/76914626-18d1fa80-6878-11ea-8810-cf05ae65d40e.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2463-head- e651c7a81
- Installation option (single install/HA): Single

**Comment by vincent99** [comment]
The name should apparently be somewhat wider so that common things fit on one line..

But we intentionally do not do scrolling sub-elements.  The only thing fixed to the screen is the blue header, and the rest of the content scrolls with the nav or body.

**Comment by codyrancher** [comment]
Just to note, I decided to add pagination instead of a scroll bar since the table component already supports pagination.

**Comment by khushboo-rancher** [comment]
Verified in latest master, pagination is appearing for violations.
<img width="1539" alt="Screen Shot 2020-03-27 at 9 53 09 AM" src="https://user-images.githubusercontent.com/60111667/77782069-e8c2ee00-7013-11ea-97bf-81b5b9832611.png">

@codyrancher can we make name column more wider as suggested by @vincent99  ?

**Comment by codyrancher** [comment]
Sure, I'll do that.

**Comment by codyrancher** [comment]
Here's a screenshot with the updated width

<img width="1429" alt="Screen Shot 2020-03-27 at 10 48 11 AM" src="https://user-images.githubusercontent.com/55104481/77785297-368e2500-7019-11ea-9f90-3835014aaaf0.png">

**Comment by khushboo-rancher** [comment]
Verified in latest dashboard UI

Name column is wider now.
<img width="1340" alt="Screen Shot 2020-03-28 at 10 02 57 AM" src="https://user-images.githubusercontent.com/60111667/77828917-a06f0300-70db-11ea-8440-513c0e3de0d1.png">
