### ISSUE TITLE
ApiGroup field in constraint create/edit should be always present.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#387]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable OPA gatekeeper.
2. Create a constraint without adding APIGroups.

**Result:**
Constraint doesn't work as it requires APIGroups always even as empty ```- apiGroups:[""]```

**Expectation:**
At least one APIGroups should be always there in create/edit constraint with empty text and user should not be able to delete all of them.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2463-head- e651c7a81
- Installation option (single install/HA): Single

**Comment by codyrancher** [comment]
I'm adding apiGroups[''] as a default value. I don't think the form should enforce not deleting all of them. I think it needlessly complicates the UI to protect people from deliberately shooting themselves in the foot. Even if we protect them in the form they could still delete the apiGroups from the yaml view.

If we insist on the enforcement then I think we should get design involved in coming up with a way to elegantly convey constraints to the user for all of our input components (I'd find it frustrating if the UI prevented me from performing a normal action without explaining why). And I think that should be a feature request and not a bug.

**Comment by khushboo-rancher** [comment]
Verified in latest UI.

APIGroup appears by default in form view.
<img width="1115" alt="Screen Shot 2020-03-27 at 11 17 17 AM" src="https://user-images.githubusercontent.com/60111667/77787343-9f2ad100-701c-11ea-8399-9c73699a2aba.png">
On creating constraint with default apigroup as empty, it is mapped to below in yaml.
```
- apiGroups:
      - ""
 ``` 

Agree with @codyrancher with above comment. Closing the issue.
