### ISSUE TITLE
Deprecation warning is not available in an upgraded rancher setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3874]
**On 2.6-head commit id: `f811996`**

For legacy tools that are no longer supported in 2.6, the message similar to `CIS Scanning in Kubernetes 1.21+ is no longer supported.` is available only on a fresh install of 2.6-head commit id: `f811996`

But when its an upgraded setup from 2.5.9 to 2.6-head, these warnings are not available.

**Comment by deniseschannon** [comment]
As these legacy tools are critical and most likely only used for users who are upgrade upgrade, this is the primary use case for these warnings.

**Comment by gaktive** [comment]
Could be tied to the state of readiness post-upgrade, whereby a banner isn't being shown. This is on the Ember side.

**Comment by codyrancher** [comment]
@sowmyav27 are you seeing a warning message at all?

I just gave this a test and it seems to be working as intended from my perspective. If you're in a cluster that's below 1.21 I see
![image](https://user-images.githubusercontent.com/55104481/129967162-55f288db-608e-42ca-95f7-cd1364438eb1.png)

On a cluster that's at or above 1.21 I see
![image](https://user-images.githubusercontent.com/55104481/129967346-0b7388bd-39d9-412c-8207-7f0f73681629.png)

Vince also mentioned the possibility of the cluster being updating and not ready yet. If the cluster is not in a ready state we can't check the version of k8s so we don't display a warning yet.

**Comment by sowmyav27** [comment]
Yes @codyrancher I think that may have been my issue. On an upgraded setup, when the k8s version is = 1.21, i see the warning when the k8s version is <1.21 i dont see that warning

Closing the issue.
