### ISSUE TITLE
Inconsistent names on button for Adding taints and node labels in a custom cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3876]
On v2.6.0-rc3

Cluster details page of a custom cluster page shows `Add` for Node Labels and `Add Taint` for Taints.
<img width="1417" alt="Screen Shot 2021-08-16 at 1 43 49 PM" src="https://user-images.githubusercontent.com/26032343/129627299-aea4b454-334f-4975-9514-d20d96565ae5.png">

**Expected:**
It should be consistent `Add Label` and `Add Taint`

**Comment by Auston-Ivison-Suse** [comment]
**VALIDATED** on 2.6.1-rc7

I spun up a custom cluster and was able to observe the intended change. *See screenshot for confirmation of build and change.

![Screen Shot 2021-09-29 at 4.05.49 PM.png](https://zube.io/files/rancher/534abe56aa7f92b998d837edc24f90b6-screen-shot-2021-09-29-at-4-05-49-pm.png)
