### ISSUE TITLE
Iframe state isn't cleared on logout

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#3884]
The state of ember iframes/caching isn't cleared properly on logout. 

1. Login to an admin
2. Go to an iframed page, e.g. Cluster Manager -> Cluster drivers
3. Log out
4. Log back in as a basic user (without reloading the page manually)
5. Go back to the same page

You get the same already loaded page that appears as if you were still an admin (e.g. clickable activate/deactivate actions for drivers) even though the user you are now logged in as doesn't have access to do them.

Showing a user stuff belonging to another account tends to understandably get people riled up, even though the backend will correctly enforce RBAC for the actual user on any writes you attempt to make.

**Comment by nwmac** [comment]
@richard-cox The easiest thing to do is to clear the cached iframe on logout (just remove it from the DOM)

**Comment by kravciak** [comment]
Iframe part seems fixed. I can't see any difference in drivers page if I refresh page after login as user.

But user without rights can still see UI components for cluster drivers management.

As Standard-User:
- UI displays edit buttons, but they respond with `Error: can not update kontainerDriver`

As User-Base:
- Driver list is empty and the is `This cluster does not have any nodes defined` message, which seems unrelated to drivers

> You get the same already loaded page that appears as if you were still an admin (e.g. clickable activate/deactivate actions for drivers) even though the user you are now logged in as doesn't have access to do them.

@vincent99 should I reopen or you have / want separate issue for tracking problems in issue description?

Tested on: v2.6-head (c10ef4b)

**Comment by kravciak** [comment]
This works fine on v2.6-head (b3980c2).

I can't see Activate / Deactivate buttons on Node Drivers list when I login as standard user (after admin logout)
