### ISSUE TITLE
Add basic formatting support to the custom banners (header/footer)

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3906]
We support custom header/footer banners through the Global Settings -> Branding -> Fixed Banners

Currently you can specify text, color and background color.

This ticket is to add basic style/formatting support to that banners.

- Make the text box slightly smaller
- Add a group of 3 icons to the right of the text box to control alignment - left, center, right (one one can be selected)
- Add another group of 3 icons to the right of the alignment icons - bold, italic, underline (all or none can be selected)

The branding config is stored in a JSON blob in a setting, so the two new options - alignment and style need to be persisted to that JSON blob. Style could be an array as multiple are permitted.

We then need to modify the code that renders the banner to add styles reflecting the alignment and style that  are configured - this should be done in `components/FixedBanner.vue`.

Obviously, we need to make sure that if neither of the new settings are in the JSON, that we default to alignment center and no styling.

Note: We don't have the icons needed for this in the icon set - you can see the available icons by looking at assets/fonts/icons/demo.html file. You can use text labels for now instead of icons (e.g. Bold, Italic, Underline etc). Lauren can bring in icons for bold, italic, underline, align left, align center, align right).

**Comment by davidnuzik** [comment]
**My checks PASSED**
I can confirm that the basic formatting support has been added for banners as per the [PR](https://github.com/rancher/dashboard/pull/3953).
 
**Reproduction Steps:**

Not required. Is a new enhancement.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `1a57856` pulled 9/17/21 ~9:30am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. As an admin, go to Global Settings page > Branding
2. Click the checkboxes for "Show Banner in Header" and "Show Banner in Footer" and enter text.
Note the new options this PR added. A "Text Alignment" section and a "Test Decoration" section which allows you to set typeface style.
3. Confirmed that by default Text Alignment is set to Center.
4. Confirmed each feature - align left and right also works. Confirmed Bold, Italic, Underline and all combinations work as expected.
Note: Text colors and text background colors not tested as this is not a part of this change (already was preexisting)
![image](https://user-images.githubusercontent.com/45179589/133863575-76179279-e206-4ede-806b-e30c0875e6c5.png)

 
**Additional Info:**
If you uncheck "Show Banner in Footer/Header" and apply, then enable it again later, the options are "remembered" which is nice. Possible this is just cached but I did not test this.
