### ISSUE TITLE
Rancher 2.5.9 Monitoring. 1 day after install Cluster Metrics shows Failed to load graph

### ISSUE THREAD

**Issue by laurie-kepford** [rancher/dashboard#3910]
**My Environment:**
Rancher 2.5.9, Docker install, Cluster created with Rancher.
Yesterday, I installed monitoring on my new cluster according the the instructions here:
https://rancher.com/docs/rancher/v2.5/en/monitoring-alerting/#enable-monitoring.

Not sure if its relevant, but I did not do the section for Enable Monitoring for use with SSL. (The instructions say to create a secret and "Add the ca, cert, and key files to the secret".  I don't know where to find these files.  I am using Lets Encrypt for my Rancher Certificate (outside Ranchers) and AWS ACM for my load balancer certificates) LE does give me cert and key files, but these are going to change every couple of months so using them as a secret does not make sense.

**Current Issues:**

From the Monitoring Overview page I can bring up Grafana but I see this error on all the graphs: Unknown error during query transaction. Please check js console logs.  This was working yesterday. 
![2021-08-18 at 10 40 AM](https://user-images.githubusercontent.com/86793511/129929899-114398ea-34ec-4b65-9036-7e4346076470.png)

From Cluster Explorer, Cluster Dashboaard, Cluster Metric does not load.  Error is Failed to load graph. This never worked.
![2021-08-18 at 10 49 AM](https://user-images.githubusercontent.com/86793511/129930109-a3cc1a53-9c84-42d0-9c93-c5d295b60344.png)

Nodes View:
Node CPU and RAM are not populated:
![2021-08-18 at 10 50 AM](https://user-images.githubusercontent.com/86793511/129930355-151f90db-4877-4818-998f-e0173d4648f7.png)

If i click on a node there is no info in the CPU and Memory section.
![2021-08-18 at 10 51 AM](https://user-images.githubusercontent.com/86793511/129930515-e6e7eb6b-7709-428a-8435-e0a847c3114d.png)

I see this in my event log:
![2021-08-18 at 10 52 AM](https://user-images.githubusercontent.com/86793511/129930712-fd147eb0-84be-42fb-b489-26cc13f36925.png)

Not sure what to do at this point.

**Comment by aprilrieger** [comment]
I am also seeing this issue in Rancher v2.6.4

**Comment by nwmac** [comment]
Closing as stale - I believe this has been fixed, but please re-open if still an issue.
