### ISSUE TITLE
Instance options in RKE2 vSphere provisioning get changed without user intervention

### ISSUE THREAD

**Issue by PennyScissors** [rancher/dashboard#3924]
When creating an RKE2 vSphere node cluster, if you change the default values under `Machine Pools > Instance Options` and then change `Cluster Configuration > Cloud Provider` to `vSphere`, the values set in instance options get changed back to the default values.

**Comment by anupama2501** [comment]
On rancher v2.6.0-rc6, verified the config values are not changed to default values while selecting the cloud providers. 

**Re-opening:** 
Seeing an issue when we check the view/edit configs of the created cluster,  value for template is changed to default value. All the other values reflect correct values.

**Selected value:**

<img width="600" alt="Screen Shot 2021-08-24 at 9 30 58 AM" src="https://user-images.githubusercontent.com/38144301/130654794-a6f7051a-0b0a-464a-b8a2-70ba5a6fa804.png">


**Changed to:**

<img width="600" alt="Screen Shot 2021-08-24 at 9 28 49 AM" src="https://user-images.githubusercontent.com/38144301/130654452-94456716-b65b-4868-a4f7-adcedd231236.png">

**Comment by PennyScissors** [comment]
Re-opening:
Seeing the same issue on Rancher v2.6.0-rc8. When we check the view/edit configs of the created cluster, value for Template is changed to default value.

**Comment by vincent99** [comment]
rc8 does not include this commit.

**Comment by PennyScissors** [comment]
Validated in v2.6-head 3c7f582
Checked the view/edit configs of the cluster after it was created and the values we not changed back to default values.
