### ISSUE TITLE
Dashboard launch is flaky it sometimes fails to load and redirected to /dashboard/fail-whale

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#393]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster.
2. Navigate to dashboard

**Result:**
Dashboard doesn't launch and redirects to dashboard/fail-whale.
On multiple refresh it sometimes work. 
Get request to ```https://rancher-server/k8s/clusters/c-xxxxx/v1/schemas``` returns 502 sometimes.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2474-head- 374b38cb2
- Installation option (single install/HA): Single

**Comment by westlywright** [comment]
This seems to be happening a lot when we create resources. For me it happens when I disable and re-enable OPA. You can tell it's happening because all the web sockets die then if you refresh the page you'll get the fail whale.

**Comment by tfiduccia** [comment]
@khushboo-rancher - this is happening because the dashboard button is showing up before the cluster is active.  You shouldn't be able to go to dashboard before that cause we don't really have anything to show.  Vincent is fixing.

**Comment by vincent99** [comment]
For clusters that are not ready: https://github.com/rancher/ui/pull/3887

**Comment by khushboo-rancher** [comment]
Verified in the latest dashboard UI. Immediately after cluster gets provisioned if user navigates to dashboard, it redirects to fail-whale. Page fails to load for around 1-2 minutes, afterwards works fine.

**Comment by dschuldt** [comment]
I experience the same issue. I upgraded a 2.3.6 instance (with imported local network clusters) to 2.4.0 and this morning to 2.4.1. With both releases, the dashboard fails with .../dashboard/fail-whale. 
After the attempt, the following log message appears:

> http: proxy error: proxyconnect tcp: failed to find Session for client <lan ip address>

Is this related to my proxy setup? The rancher server is started as a single docker container with the following environment variables:

> environment:
>   HTTP_PROXY: 'http://my.network.proxy:8080'
>   HTTPS_PROXY: 'http://my.network.proxy:8080'
>   NO_PROXY: 'localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cluster.local,network.domain,another.domain'

Apart from that, amazing release!

**Comment by closeid** [comment]
> 
> 
> I experience the same issue. I upgraded a 2.3.6 instance (with imported local network clusters) to 2.4.0 and this morning to 2.4.1. With both releases, the dashboard fails with .../dashboard/fail-whale.
> After the attempt, the following log message appears:
> 
> > http: proxy error: proxyconnect tcp: failed to find Session for client
> 
> Is this related to my proxy setup? The rancher server is started as a single docker container with the following environment variables:
> 
> > environment:
> > HTTP_PROXY: 'http://my.network.proxy:8080'
> > HTTPS_PROXY: 'http://my.network.proxy:8080'
> > NO_PROXY: 'localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cluster.local,network.domain,another.domain'
> 
> Apart from that, amazing release!

same issue here when behind proxy.

**Comment by vincent99** [comment]
I changed the error page to show a little more info in some cases, but this is really a backend problem.

There's no status/condition to know if the API service is actually up yet or not, and sometimes clusters are in an active state but the steve API is not actually available.

**Comment by khushboo-rancher** [comment]
Created a backend issue - https://github.com/rancher/rancher/issues/26727

**Comment by C-PET** [comment]
Interrmittent issue with getting fail-whale
using agent 2.4.3
cluster is active

the dashboard works on our 5 node rancher cluster (rke up --config cluster.yaml) cluster.  
We added a custom style cluster that is up and active but when I use Try Dashboard I get fail-whale. Can switch back to the Rancher local cluster and it works fine.

**Comment by pradeep-av** [comment]
I'm new to this issue, in my case the rancher instance does not have direct network connection to the cluster nodes (but nodes will reach rancher via proxy). The kubectl web term works fine, meaning proxy config is fine. I think the request is proxied to cluster endpoints and hence there is an issue. In the same rancher instance I have another cluster, which is in same network, and dashboard works fine.

**Comment by izaac** [comment]
Rancher version `master-head (08/13/2020)` _d19f179c4_
Both single and HA k8s installations checked.

Previous dashboard index (with the old cluster overview) page will no longer get maintained see: https://github.com/rancher/dashboard/issues/776#issuecomment-664641801

The behavior is different now in the latest dashboard-index and reported in this other issue, reproducible for single and HA installs https://github.com/rancher/rancher/issues/28364

**Comment by einsteinarbert** [comment]
Still error in rancher-2.7.1 install with k8s-rke2, LB with kubevip.
