### ISSUE TITLE
Updated AWS EKS regions eu-south-1

### ISSUE THREAD

**Issue by mug3n451** [rancher/dashboard#3937]
Hi,
AWS introduce a new region for EKS: eu-south-1.
Is it possible to add this region to the list of EKS option avaible?

Thanks
Cristian

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.5-head `b2f17e430` pulled 9/9/21 11:20am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Launched rancher and tried to create EKS cluster
2. Confirmed picking the `eu-south-1` region is possible now.
 
![image](https://user-images.githubusercontent.com/45179589/132742385-cbb3beef-b7d1-462d-8cf2-cb94d7e617b6.png)
