### ISSUE TITLE
500 with Cannot read property 'startsWith' of undefined on Cluster Member viewing Cluster Detail page

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#3942]
Observed in `v2.6-head (2778ecabaeae72be86bd90a4f6127d72c1a9b686)`

When logged in as a Cluster Member (via Auth Provider) and looking at the Cluster Detail page, a 500 error is observed.

![arvind-rancher-26head cp-dev rancher space_dashboard_c_c-7nlx8_manager_provisioning cattle io cluster](https://user-images.githubusercontent.com/13127443/130143332-c4c5d202-e752-47a0-914b-b995e5849811.png)

Not seen after refreshing the page.

See https://github.com/rancher/rancher/issues/34253#issuecomment-902253566 for more details

**Comment by thehejik** [comment]
Tested on `rancher/rancher:v2.6-head b8a44fa`

* On local cluster created 2 `Standard User`s with additional `Configure Authentication` permission (for enabling OAuth on user account)
* As `user1` deployed a DO RKE1 cluster with `user2` added as `Member` of this cluster.
* `user2` has been configured for accessing rancher over OAuth (github)
* Once the DO cluster has been provisioned and up I logged in as `user2` over github
* no error appeared, the cluster was present in the list of clusters on `Cluster Management` page:
![user_oauth_clusters](https://user-images.githubusercontent.com/12828077/130477726-0e1b83dc-4d58-45b1-bced-c813e8993f20.png)

I didn't see the error message on `rancher:v2.6.0-rc1` as well but the list of clusters was just empty for both `user1` (owner) and `user2` (Member) but the Cluster counter was showing `1`.

Close.
