### ISSUE TITLE
`systemdLogPath` should be in the rancher logging install form

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#3945]
We need to add a field to the rancher logging installation page for `systemdLogPath`.  The expected value is a file path string with a default value of `/run/log/journal`  There should also be a link to the linked documentation and ideally a summary on this field to help users understand how to use it.

https://github.com/rancher/rancher/issues/34339

**Comment by aiyengar2** [comment]
@deniseschannon @vincent99 I ran into this issue while talking to Jacob while testing https://github.com/rancher/rancher/issues/33046. 

IMO, we should definitely consider moving this to 2.6.0 or adding this to the release notes.

As encountered by @brendarearden in https://github.com/rancher/rancher/issues/33046#issuecomment-898656569, **a vanilla installation of Logging V2 today on any k3s cluster results in a user `not see[ing] any logs being pulled from k3s`**.

The workaround is to use `Edit YAML` and manually insert the right `systemdLogPath` based on instructions in https://github.com/rancher/charts/blob/3d6648ac9ce8a53c122bb16ad3b30f18c501dc44/charts/rancher-logging/rancher-logging/100.0.0%2Bup3.12.0/app-readme.md#systemd-configuration, but I think this either needs to be prioritized into the UI or added as a release note in case any k3s users run into this.

**Comment by deniseschannon** [comment]
We've asked to put this info into the readme of logging so that it would be obvious even if it's not directly in the UI. @paynejacob I don't believe this needs to be in 2.6.0, but this could be added in the release notes

**Comment by gaktive** [comment]
Per the backend ticket, added to the release notes so we can look at this post-2.6.1.

**Comment by sowmyav27** [comment]
Reopening this issue to test a few more usecases around `systemd Log Path`

**Comment by ronhorton** [comment]
I entered systemdLogPath: 9/9/9/ in the input field. Logging is not installing - it's in a pending install status. Is there any checking on the what the user enters in the newly exposed field? ![Screen Shot 2021-11-16 at 11.32.45 AM.png](https://zube.io/files/rancher/fc7ea26795e100d922e754ecc6ca9c45-screen-shot-2021-11-16-at-11-32-45-am.png)

**Comment by ronhorton** [comment]
**PASS** verified in `2.6-head Commit ID f487c88`
1. In `2.6-head`, Installed logging chart `100.0.1 3.15.00` on an active cluster
2. click `Next` in installation flow
3. The `systemd Log Path` is included in `Step 2`
4. Completed installation
5. Verified logs flow to the output target

**Tested on the following cluster types:**
1. GKE cluster
2. DO RKE2 cluster
3. K3S cluster
4. EC2 RKE2 cluster
5. DO RKE1 cluster
6. Custom cluster
7. EKS cluster

**Tested Negative test case** by passing bad path in the systemdLogPath. Chart install failed with expected message: `fluentbit/9/9/9: no such file or directory: unknown`

**Also testing upgrade** from chart v3.12.0 to v3.15.0 in `2.6-head Commit ID 663df43` and new field is present in `Update: Step 2`
![Screen Shot 2021-10-29 at 10.48.43 AM.png](https://zube.io/files/rancher/00ad0ee4b19a6a708e78f7f91438e74b-screen-shot-2021-10-29-at-10-48-43-am.png)
