### ISSUE TITLE
`Drivers` page could not be found

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3947]
Page is either empty or showing `This page could not be found` error.

![Screenshot from 2021-08-20 10-34-46](https://user-images.githubusercontent.com/538604/130205478-2f2b97ca-3267-4e5d-a461-64c60c63621f.png)

Same applies for Clusters -> Create (RKE1) = empty

On v2.6-head (1f54519)

**Comment by gaktive** [comment]
Should be fixed now after some backend changes.

**Comment by kravciak** [comment]
Works fine on master-head (b8a44fa)
