### ISSUE TITLE
[Nitpick] Option to SSH into node appears before the machine is even provisioned by node driver

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#3951]
v2.6-head `f576152`

Create a cluster, in my case 1 node DO cluster with RKE2. View the machine pools tab. The ability to ssh into the node is available right away even though the droplet isn't even created yet.

![image](https://user-images.githubusercontent.com/45179589/130274356-5169fc19-e215-442e-bae4-0bcf28ca27cb.png)

**Comment by nwmac** [comment]
@Sean-McQ If you look in models/cluster.x-k8s.io.machine.js you'll see _availableActions - the enabled property should also check that the cluster is active

**Comment by davidnuzik** [comment]
@gaktive I'm going to fix the milestone. This was merged in and thus will be in v2.6.3 by my understanding (merged into dashboard master branch)

**Comment by davidnuzik** [comment]
**My checks PASSED**
I no longer see this issue. The SSH Shell option isn't available until the node is ready.
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `0d14421` 12/8/2021
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: 1.21
 
**Validation steps:**

1. Create any RKE2 cluster.
2. View the cluster in the cluster management page.
3. Immediately click on the node function menu and see if the SSH option is available (it no longer is, the fix worked).
4. Wait for the node to be ready - the menu option now shows and I can ssh into the node in the UI without any issues.
 
**Additional Info:**
 Screenshot showing that when node is not ready the SSH Shell option is not available now with the fix:
![image](https://user-images.githubusercontent.com/45179589/145290861-4c86ecf7-0b8c-4a3e-b580-25da0db73c9e.png)
