### ISSUE TITLE
the 'collapse' button for dropdown does not close the dropdown menu

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3961]
Setup: v2.6.0-rc5

**Issue:** The dropdown button does not collapse when clicking the arrow to close it. The user must click somewhere outside of the dropdown in order to close it.

**Result:** dropdown menu re-opens when clicking the collapse button. 

**Expected Result:** clicking the collapse arrow would close the dropdown menu 
<img width="449" alt="Screen Shot 2021-08-21 at 6 45 54 AM" src="https://user-images.githubusercontent.com/16691014/130323783-3829b9f5-1c05-41d5-8c0f-afaac10325d6.png">

**Comment by kravciak** [comment]
Collapse button works fine on v2.6-head (b43e4d9)
