### ISSUE TITLE
Edit Config window for cluster local opens empty

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#3963]
Cluster information is not displayed.
Cluster name can not be changed.

![image](https://user-images.githubusercontent.com/86831399/130412710-34b4d161-a020-4cd4-bcbd-06ea57d20037.png)

**Comment by peteingithub** [comment]
When I tried to edit the YAML, save gives the following error:
`{ "data": "404 page not found\n" }`

**Comment by richard-cox** [comment]
Not seen in `2.6-head`. Need to confirm if this was an RC5 issue only

**Comment by gaktive** [comment]
Some fixes should have come in after so a retest for RC6 would be recommended based on changes that have come in since RC5.

**Comment by peteingithub** [comment]
> Some fixes should have come in after so a retest for RC6 would be recommended based on changes that have come in since RC5.

When is RC6 out?

**Comment by peteingithub** [comment]
> Not seen in `2.6-head`. Need to confirm if this was an RC5 issue only

It has been working with all master-heads and RCs up to RC4.

**Comment by peteingithub** [comment]
Works in RC6.
