### ISSUE TITLE
Hamburger Icon in dark Theme in Initial Getting Started doc  is not visible

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3975]
**on 2.6-head commit id: `b43e4d9`**

Hamburger Icon in dark Theme in Initial Getting Started doc  is not visible
<img width="1029" alt="Screen Shot 2021-08-23 at 9 32 52 PM" src="https://user-images.githubusercontent.com/26032343/130556331-7738af6a-7a73-4910-9317-f4aa8812ce17.png">

**Comment by kravciak** [comment]
On v2.6-head (70f024e)

![Screenshot from 2021-08-25 08-09-16](https://user-images.githubusercontent.com/538604/130735784-f2214537-c11c-44c1-a99b-665b4847fad4.png)
