### ISSUE TITLE
SUSE subscription field accepts random alphanumeric keys

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#3977]
When testing https://github.com/rancher/dashboard/issues/3861 I noticed the input field for `Add Subscription ID` on `Get Support` page accepts random 16-char alphanumeric ID like `aaaabbbbccccdddd` or `1111111111111111` and rancher reports itself as supported then.

Registration key obtained from https://scc.suse.com for `SUSE Rancher` product is not accepted.

Seen on `rancher/rancher:v2.6-head b43e4d9`

**Comment by nwmac** [comment]
Won't fix
