### ISSUE TITLE
Unable to clone constraints in form/yaml view.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#398]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable gatekeeper.
2. Create a constraint and try to clone it in form/yaml view.

**Result:**
In form view UI shows error ```{ "type": "error", "links": {}, "code": "MethodNotAllowed", "message": "Method POST not supported", "status": 405 }```
In yaml view there is no create/apply button.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2474-head- 374b38cb2
- Installation option (single install/HA): Single

**Comment by khushboo-rancher** [comment]
Verified in latest master, clone constraint via yaml works fine.
Clone as form fails if template is changed saved.

Steps:
1. Create a constraint.
2. Clone as form and change the template.
3. View the constraint in yaml view.
Type doesn't get updated.
```
_type: constraints.gatekeeper.sh.k8srequiredlabels
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  creationTimestamp: "2020-04-18T00:13:57Z"
  finalizers:
  - finalizers.gatekeeper.sh/constraint
  generation: 1
  name: test18
  resourceVersion: "381009"
  selfLink: /apis/constraints.gatekeeper.sh/v1beta1/k8sallowedrepos/test18
  uid: 6aabc3bf-4fd2-471c-9e31-f34c15d7ce36
spec:
  enforcementAction: deny
  match:
    excludedNamespaces:
    - cattle-system
    - gatekeeper-system
    - ingress-nginx
    - kube-node-lease
    - kube-public
    - kube-system
    - security-scan
    kinds:
    - apiGroups:
      - ""
    labelSelector:
      matchExpressions: []
    namespaceSelector:
      matchExpressions: []
  parameters: {}
status:
  byPod:
  - enforced: true
    id: gatekeeper-controller-manager-699f5d876-cxrpr
    observedGeneration: 1
type: constraints.gatekeeper.sh.k8srequiredlabels
```

**Comment by izaac** [comment]
Tested the fix and validated in:

Rancher version:
- master-head (05/20/2020) b85ea695f
- 2.4-head (05/20/2020) 8e20687a4 with CATTLE_DASHBOARD_INDEX=https://releases.rancher.com/dashboard/latest/index.html


- I can clone both templates and constraints. 
- Constraints can be cloned using Clone as Form and clone as YAML
- Template type can't be changed when cloning a Constraint [avoiding this error](https://github.com/rancher/dashboard/issues/398#issuecomment-615518868). This can be overridden in YAML if that's needed.
