### ISSUE TITLE
Auth provider is stuck at Loading

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3989]
To reproduce:
- open Auth Provider
- configure Github auth
- click Users & Authentication -> Auth Provider
- click Auth Provider (from left menu) again

Result: Screen is stack at `Loading...`

![Screenshot from 2021-08-24 16-40-21](https://user-images.githubusercontent.com/538604/130637552-9a403a74-30dc-4095-bc7e-107e57fb1a11.png)

Tested on: v2.6-head (b43e4d9)

**Comment by richard-cox** [comment]
Reproduced. Only happens when already on the page. There's some strange routing going on, it thinks the auth provider page is the user managment one (see error below shown when clicking on auth provider... or navigating to it)
```
Uncaught (in promise) Error: Navigation cancelled from "/c/local/auth/config/github?mode=edit" to "/c/local/auth/management.cattle.io.user" with a new navigation.
```

**Comment by gaktive** [comment]
@richard-cox to do a timebox on this to see if we can get this into 2.6.0

**Comment by kravciak** [comment]
Not fixed on v2.6-head (940ebaf)

**Comment by izaac** [comment]
Rancher version: `v2.6-head (08/30/2021)` _940ebaf_

Although this is reproducible the user can just refresh the page to access `Users & Authentication` and do further edits to the enabled auth.

**Comment by nwmac** [comment]
@kravciak Can you open the console log of the browser and add any error messages from there to this issue, please.

**Comment by richard-cox** [comment]
This issue has been fixed in rancher/dashboard `master` and not `release-2.6`. The former will go on to become `2.6.1` at some point. As this is targetted for `2.6.1` it's fine missing in `release-2.6`

**Comment by izaac** [comment]
Rancher version: `v2.6-head (09/09/2021)` _a6e7905_

Validated working using a `v2.6-head` build. Closing
