### ISSUE TITLE
Support for managing catalog.cattle.io.clusterrepos objects defined on local cluster w/o full access to local cluster

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#3995]
To support restricted admins' ability to add new RKE2 templates we need to have a way to manage Cluster Repositories (`catalog.cattle.io.clusterrepos`) via UI without having to navigate to `local` cluster (as restricted admins don't have full access to `local` cluster).
The exact solution TBD, this is a UI issue for the following back-end issue: https://github.com/rancher/rancher/issues/33110

**Comment by nwmac** [comment]
@vincent99 I assume what we need is a new nav item in Cluster Management named 'Cluster Repositories' that is the same as the chart repos list, but only showing ones with chart templates. We can then hide these in the Cluster Explorer Chart templates list.

**Comment by gaktive** [comment]
Template Repositories seems like a clearer term. Maybe we can leverage the Apps & Marketplace view via a filter.

**Comment by codyrancher** [comment]
So I don't think there's really a good way to filter out the chart repos. The structure of the index.yaml seems to allow a single repository entry to contain both templates and charts.

I'm thinking that we should just rename this to Cluster Repositories and change the messaging on the existing page. I'll do a demo tomorrow and get some feedback to find out.

**Comment by nwmac** [comment]
@codyrancher From a UX point of view, it is odd to have to change contexts to explore the local context in order to add a cluster template repository.

Even if we can't filter out the ones that are template repos, I think having the functionality in the cluster management part of the UI would be useful.

**Comment by nwmac** [comment]
@codyrancher One suggestion - when a cluster template repo is added in the UI from the new page, can we add a label so that we can identify it as a cluster template repo to filter it out from the others?

This would give an issue for any cluster template repos already added - we could look at all of the charts, find those that are cluster templates (chartType = cluster-tempate) and from that we know that the corresponding repo is a cluster template one.

**Comment by vincent99** [comment]
There is no such thing as a "chart" repo vs a "template" repo.  The difference is one annotation on the chart, and there can be many of both kinds mixed in one repository.

**Comment by nwmac** [comment]
@codyrancher So, I think we just need to the chart repos page also to be available in Cluster Management - we can add an explanation there. We could show how many cluster templates are available from each repository - this might help users see which repos are app chart repos.

We need to make sure back links work correctly when you view, add or edit a repo.

**Comment by slickwarren** [comment]
hmm, I'm on the latest v2.6-head (1f5852d) but I don't see these changes yet. In drone, I see this has merged to both dashboard `master` and tagged to `v2.6.1-rc3`.  Does this mean I need to wait for an RC to see this?
<img width="574" alt="Screen Shot 2021-09-18 at 1 30 18 PM" src="https://user-images.githubusercontent.com/16691014/133907777-6eb71d0b-1ee4-4b6d-9193-123d2ea66d9d.png">

**Comment by snasovich** [comment]
@slickwarren , `v2.6-head` has `CATTLE_DASHBOARD_UI_VERSION=v2.6.1-rc1`, so the UI changes are not in yet.

**Comment by richard-cox** [comment]
> @slickwarren , `v2.6-head` has `CATTLE_DASHBOARD_UI_VERSION=v2.6.1-rc1`, so the UI changes are not in yet.

This is and isn't true.

By default `-head` builds will use bits served from `ui-dashboard-index` (which is pointed to `rancher/dashboard` `master`). Non `-head` builds will use the `CATTLE_DASHBOARD_UI_VERSION` env. So it should be in `2.6-head` but if that env hasn't been updated by the rancher/rancher release captain then `v2.6.1-rc3` won't contain it.

@slickwarren The cluster repos are now shown in both the old (renamed) Cluster Explorer > Apps & Marketplace > Repositories page and the new Cluster Management > Advanced > Repositories page. 

![image](https://user-images.githubusercontent.com/18697775/133975003-3b89cbdc-bfba-4d41-be8c-12ba317f3e09.png)

**Comment by snasovich** [comment]
@richard-cox , thank you for explaining what version of UI is picked up by Rancher - my bad. I was going by screenshots on the PR and couldn't find any of these options available for restricted admin. But the "Cluster Management > Advanced > Repositories" is.

**Comment by slickwarren** [comment]
on v2.6-head (45dfeb4) I'm seeing an issue: 
* restricted admin can add a repository via the new menu in `cluster management` > `advanced` > `repositories` .  -- pass
  * currently, restricted admin gets this error when provisioning a cluster that the restricted admin has added:
  * <img width="1789" alt="Screen Shot 2021-09-20 at 10 01 02 AM" src="https://user-images.githubusercontent.com/16691014/134054190-03e78e37-7884-4a9c-8b5d-050c90fcf664.png">
  * the regular admin can use the same parameters to create a cluster from the template.  **Reopening for this issue.**

**Comment by richard-cox** [comment]
@slickwarren That's a separate backend issue, can you raise one against `rancher/rancher`?

**Comment by slickwarren** [comment]
also tested the following on v2.6-head (45dfeb4):
* standard users cannot edit/create repositories -- pass
  * can view repos -- pass
* admin users can edit/create/delete/view repositories -- pass
* restricted admin can edit/create/delete/view repos -- pass

closing in favor of the backend ticket linked above
