### ISSUE TITLE
Custom cluster reg command enhancement: Banner `The cluster needs to have at least one node with each role.` can be changed when registering windows nodes as windows node is only for worker nodes for custom clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3998]
Rancher version: v2.6-head 2e55e84
Installation option (Docker install/Helm Chart): Docker install
Version: local k8s, v1.21.3+k3s1
Proxy/Cert Details: self-signed

**Information about the Cluster**
Kubernetes version: `v1.21.4-rancher1-1`
Cluster Type (Local/Downstream): `Downstream custom cluster rke2`

**Result:** 
While registering a windows cluster, a banner is displayed `The cluster needs to have at least one node with each role`. 

**Expected result:**
This banner can be changed that says only worker role can be selected for windows nodes.

Screenshot:
<img width="400" alt="Screen Shot 2021-08-24 at 5 35 45 PM" src="https://user-images.githubusercontent.com/38144301/130707479-6fdde2a5-0882-4ba2-9721-25926f253909.png">

**Comment by gaktive** [comment]
@anupama2501 can you clarify what the banner should say? Your screenshot appears to be the Linux blurb which can allow all three, but the Windows one below that can only be worker.
