### ISSUE TITLE
namespace dropdown looks disabled in light theme while creating a deployment

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4003]
**on 2.6-head commit id: `b43e4d9`**

- namespace dropdown looks disabled in light theme while creating a deployment
<img width="914" alt="Screen Shot 2021-08-24 at 9 38 17 PM" src="https://user-images.githubusercontent.com/26032343/130727503-29eba612-c15b-487b-b3b4-9b4e76d32a13.png">

**Comment by ronhorton** [comment]
<img width="1173" alt="Screen Shot 2021-10-11 at 3 53 11 PM" src="https://user-images.githubusercontent.com/89212856/136848022-35c5fb04-8dde-42d0-b536-4384e51bb00c.png">

**Comment by richard-cox** [comment]
@nwmac Is this one ready for test, or given https://github.com/rancher/dashboard/issues/4003#issuecomment-951255327 needs to be reopened?

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID 4375161`

1. Deployed a downstream cluster
2. clicked `Explore`
3. clicked `Deployments` > `Create`
4. `Namespace` is now colored same as other input fields on screen; no longer looks disabled.
5. checked all other sections under `Workload` to confirm color change 
CronJobs
DaemonSets
Deployments
Jobs
Stateful Sets

![Screen Shot 2021-11-29 at 3.46.11 PM.png](https://zube.io/files/rancher/c4d3b61b38a77f4148688b1e482de0c0-screen-shot-2021-11-29-at-3-46-11-pm.png)
