### ISSUE TITLE
Error: "clusterregistrationtokens.management.cattle.io is forbidden: " is seen when a user with no edit access to cluster navigates to cluster details page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4005]
**On 2.6-head commit id: `b43e4d9`**

- Disable RKE2 feature.
- Deploy an RKE1 custom cluster
- Assign user1 as Cluster member of this cluster
- Login as user1
- Navigate to cluster management --> Cluster details page
- error seen `{ "baseType": "error", "code": "Forbidden", "message": "clusterregistrationtokens.management.cattle.io is forbidden: User \"u-z8t2z\" cannot create resource \"clusterregistrationtokens\" in API group \"management.cattle.io\" in the namespace \"c-gw5fn\"", "status": 403, "type": "error", "statusCode": 403 }`

Expected:
The call to clusterregistrationtokens should not be made when navigating to cluster details page

Similar issue: https://github.com/rancher/dashboard/issues/3852

**Comment by vincent99** [comment]
The previous fix for #3852 disabled attempting to create a token if you don't have write access to  cluster, which you shouldn't have for cluster member.. (`/v1/provisioning.cattle.io.clusters/fleet-default/c-gw5fn` should not have the `update` link present).

And that works for me with a new cluster; Are you sure you didn't give it a different role?  If there's a role that has write to cluster but not clusterRegistrationTokens that would be a problem, but I don't think there's any more granular info for the UI to go to to know if it's going to work or not.

**Comment by sowmyav27** [comment]
**On 2.6.1**

- Disable RKE2 feature.
- Deploy an RKE1 custom cluster
- Assign user1 as Cluster member of this cluster
- Login as user1
- Navigate to cluster management --> Cluster details page
- No error is seen in the page
