### ISSUE TITLE
Namespace Default Limit text box width fixed?

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4006]
2.6.0-rc6

Create Project
Click Resource Quotas 
Namespace Default Limit "breaks through the frame"

![image](https://user-images.githubusercontent.com/86831399/130734666-9ff30aca-07e0-43e5-b755-9efbe4594492.png)

**Comment by nwmac** [comment]
@peteingithub What browser are you using? I don't see this in Chrome.

**Comment by peteingithub** [comment]
I used Firefox. 
Confirm Chrome does not have it.

**Comment by neillsom** [comment]
Unable to recreate issue in firefox or chrome

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Rancher version: v2.6.0 and v2.6-head `1718f1455` pulled at 9/7/21 12:04 pm Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10

Unable to reproduce.

Hmm, I'm having issues reproducing this as well. I tried:
- Latest Firefox 91.0.1 on Linux (my normal work machine, openSUSE Tumbleweed)
- Latest Firefox 92.0 on Windows 10 (VM)
- Simulating Galaxy S9 with Firefox on Linux (custom viewport sizes)
- Try Linux and Windows with small browser window size (not very wide horizontally)

In all of these cases I'm unable to reproduce with the latest v2.6-head and with v2.6.0 release.

@peteingithub are you still encountering this with v2.6.0? @nwmac , @neillsom , and myself are unable to reproduce this.
If you can indeed still reproduce could you re-open this issue (or ask me to do so if you don't have permission to do this) and give us more details -- shouldn't matter but what OS and what exact version of FireFox?
