### ISSUE TITLE
View Config of a cluster is not available and shows Custom cluster icon on the UI for users with no access to cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4009]
On 2.6-head commit id: `b43e4d9`

- Disabled RKE2 feature flag
- Deploy an RKE1 custom cluster
- Add a user as project member of a project in this cluster
- Login as this user
- Go to cluster management --> CLick on cluster --> Config

<img width="1662" alt="Screen Shot 2021-08-24 at 11 20 52 PM" src="https://user-images.githubusercontent.com/26032343/130737478-d95f16b1-25d5-4763-a1e5-76c5173b3b64.png">

**Comment by vincent99** [comment]
Breaking looking for types that used to be readable but aren't anymore... it now goes to Ember, though it doesn't really know what to do with not being able to load the nodeTemplates and such so it shows up as custom...

**Comment by nwmac** [comment]
I've verified this and this is working correctly - passing to To Test for QA to sign off and close.

**Comment by anupama2501** [comment]
Verified on v2.6-head 1a57856

1. Created a custom cluster rke1 as an admin by disabling the rke2 flag from Global settings.
2. Create a standard user and add the user in the default project as a Project member
3. Login as the user
4. Click on the cluster and the config edit page is available
5. from the cluster management page --> Ellipsis --> View Config --> Custom which lands in the Config page edit page is available
