### ISSUE TITLE
Header UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#401]
date - 3/19

- [x] Make Cluster/Namespace & Profile drop-down all dark and consistent

![image](https://user-images.githubusercontent.com/11514927/77096309-6790a900-69cc-11ea-98d1-ec6fdff784a6.png)

- [x] Change selected namespaces & "All User namespaces" to be white like cluster
![image](https://user-images.githubusercontent.com/11514927/77096409-8db64900-69cc-11ea-93f5-4a2d413fcf29.png)
![image](https://user-images.githubusercontent.com/11514927/77096435-93ac2a00-69cc-11ea-86f7-50cd7fa8458e.png)

- [x] Fix profile to use dark drop-down with blue text.

- [x] Can we mov the Back to Rancher over to the left a bit.  I keep clicking on when I'm trying to click on profile.  Or at least have a little space between them.
![image](https://user-images.githubusercontent.com/11514927/77106782-e4c41a00-69dc-11ea-86d3-265daa9027f4.png)

**Comment by lvuch** [comment]
@vincent99 for the first one can you change it from a tooltip to a dropdown for me, please?

**Comment by tfiduccia** [comment]
Fixed
