### ISSUE TITLE
Cluster Owner (standard user) has error message in viewing the config of the RKE2 cluster

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#4023]
**Rancher Server Setup**
- Rancher version: v2.6-head 70f024e
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1
         Node Setup: 
         Version:

**Information about the Cluster**
- Kubernetes version: v1.21.3+rke2r2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): DO 

**Describe the bug**

Unable to obtain the cloud credential associated with the cluster results in lack of permissions to view and edit the machine pools

**To Reproduce**
 

1. Create a RKE2 cluster
2. Add a cluster owner (standard user) to the clsuter
3. Login as the cluster owner
4. Navigate to cluster via cluster management
5. Click on "Config"  Or try to "Edit Config"

**Result**
Since I don't have perms to the cloud credential, there are errors on the view config page and when I go to edit the config, I get asked to provide a cloud credential. 

**Expected Result**

Use case of View Config - No error on screen
Use case of Edit Config - Not prompted to input a cloud credential

**Screenshots**

View Config:
At first it shows error about perms regarding cloud-credential:

<img width="1173" alt="Screen Shot 2021-08-24 at 9 23 22 PM" src="https://user-images.githubusercontent.com/11410997/130726587-18041bd6-7ee6-4732-95a5-4b4559926ac5.png">

Then the error updates to:

<img width="1178" alt="Screen Shot 2021-08-24 at 9 24 17 PM" src="https://user-images.githubusercontent.com/11410997/130726610-56578a36-d1d5-4512-96e5-2f08454c0714.png">

**Additional context**

**Comment by vincent99** [comment]
If you have appropriate permission you should be able to _use_ the cloud credential for the pool section to be able to make API calls and show you stuff from the driver (regions, sizes, etc) even though you can't get the actual credential itself.  

Each driver needs to specifically handle this situation if they try to use info from the cloudCredential (e.g. AWS and DO store the default region in it and the UI uses it), so they should be checked individually.  But I made all of them not blow up just before 2.6.0 shipped, AFAIK.

**Comment by davidnuzik** [comment]
**My checks PASSED**
I no longer encounter this issue.
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `1a57856` pulled 9/17/21 ~9:30am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.4+rke2r2
 
**Validation steps:**

1. Create a downstream cluster with Rancher as the admin user. It does not matter, but in my case I created 1-node cluster with RKE2 with the DigitalOcean node driver.
2. Create a standard user and make them the Cluster Owner.
3. Log in as the standard user (cluster owner). View the config page of the cluster on the cluster management page.
4. The standard user is able to "use" the cloud credentials and thus see the machine pools details:
![image](https://user-images.githubusercontent.com/45179589/133865989-f51af52e-b8ac-4793-afbe-53c52ed64a86.png)

 
**Additional Info:**
