### ISSUE TITLE
When adding members to a cluster, focus on the "Select Member" text box when the modal pops up

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#4026]
Whenever I add a member to a RKE2 clsuter through the member roles tab, the focus never lands inside the select member dropdown so I have to use my mouse to put into the textbox/dropdown and then start typing to find members. 

Since the helper text says "Start typing to search for principals", it'd be nice if it focused in there when it pops up.

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `1a57856`**

this is seen fixed.
<img width="503" alt="Screen Shot 2021-09-17 at 11 35 00 PM" src="https://user-images.githubusercontent.com/26032343/133879088-81021475-063a-4122-a35c-25d7929db855.png">
