### ISSUE TITLE
When delete a cluster, see a page not found page

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#4027]
![image](https://user-images.githubusercontent.com/45179589/130870607-b3377f13-3775-400e-b59d-e033ea410463.png)

**Summary:**

**Environment:**
Rancher version: v2.6-head a50efe8 pulled at 8/25/21 2:54 pm Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.4+rke2r2

**Steps to Reproduce:**
1. Create an RKE2 cluster. In my case it was a multi-node cluster with several pools (this probably does not matter, but in case it does I will describe below):
Digital ocean provider
1 etcd pool - etcd role only - 3 nodes
1 cp pool - cp role only - 2 nodes
1 worker pool - worker role only - 3 nodes
2. While the cluster is still provisioning (shortly after creating) delete it.
3. You will see a Page Not Found error in the UI.
Note: I didn't spot anything interesting in the browser dev console.
 
**Expected Result:**
Expected to get routed back to the cluster management page.

**Actual Result:**
Am not routed properly. See a page not found page.

**Additional Info:**
I was on the cluster management page when I tried to delete the cluster.

**Comment by davidnuzik** [comment]
Sorry for the long delay @richard-cox I missed this message. I am pretty sure I was on that page yes. I didn't refresh. Pretty sure anyway.

**Comment by davidnuzik** [comment]
@richard-cox @gaktive I've not been successful in trying to reproduce this FYI. Perhaps we should close this issue; should I see it again I could reopen and provide details.

`v2.6.0 single-node docker`
same steps - RKE2 cluster with DO provider - multinode
tried other ways - rke2 and rke1 clusters multinode or not
tried with an admin user or with standard user

each time, be on cluster details page (dashboard/c/local/manager/provisioning.cattle.io.cluster/fleet-local/<cluster>) delete the cluster from there. Tried both very quickly when cluster is in "reconciling state" and after giving the cluster 10-15 seconds when it starts to provision vms (provisioning state).

Dashboard UI properly routes me back to Cluster Management page, do not get a 404 error

**Comment by richard-cox** [comment]
I think the key to this issue is the cluster context in the url. When on the cluster detail page with url  `/c/<cluster id A>/manager/provisioning.cattle.io.cluster/fleet-local/<cluster id B>` both cluster id A and B should match. If cluster A is `local` and different from cluster id B then I'm hypothesising the issue won't reproduce.

I'll investigate today.

**Comment by davidnuzik** [comment]
@richard-cox sorry I wasn't on local bad URL and it hid my `<>` due to it thining it's html

**Comment by richard-cox** [comment]
@davidnuzik  Ok, I couldn't reproduce this with the way I thought I could. Instead of closing I'll move this over to QA for them to confirm

**Comment by davidnuzik** [comment]
Yeah so that's me :) I'm going to close it since I couldn't reproduce this.
Apologies for any time wasted here - at the time leading up to 2.6.0 release it was important that we quickly mention any bugs of concern before release. I didn't have the time before to try to reproduce before filing this. 

Glad we don't seem to be able to reproduce. Should the issue happen again I'll try to provide more specifics and try to repro.
