### ISSUE TITLE
View Logs for InitContainers in Dashboard

### ISSUE THREAD

**Issue by boindil** [rancher/dashboard#4032]
As of now I can only find this possibility in Explorer whilst I dont happen to see them in Dashboard

**Comment by boindil** [comment]
@vincent99 nailed it. In the old manager view we were able to see these logs. As the manager is totally unaavailable with 2.6.0 this is somewhat critical as I cant view the logs of any initContainer (thats possibly crashing) through rancher anymore

**Comment by nwmac** [comment]
Thanks @boindil

**Comment by anupama2501** [comment]
Verified on v2.6-head 1a57856

init cotainer logs are shown in the pods details page:
<img width="225" alt="Screen Shot 2021-09-17 at 4 23 51 PM" src="https://user-images.githubusercontent.com/38144301/133863440-2ddd2afc-b58b-43de-b5d3-d95ff7257ca0.png">
