### ISSUE TITLE
Users should not be able to manage users or auth providers whem mcm is disabled

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4039]
- Given recent changes to norman/steve managing roles when mulit-cluster-management is disabled is now not supported (admin cannot assign members to the sole cluster - rancher/rancher#34452)
  - To bring up a docker image in this state just add `--features=multi-cluster-management=false` to the run command
- This means no user or auth provider management is possible, so shouldn't be reachable in the ui

**Comment by izaac** [comment]
Rancher version: `v2.6-head (08/27/2021)`  _8bc6327_

Users and Auth is not browsable or available in this build when `multi-cluster-management=false`
