### ISSUE TITLE
type: NodePort is being set twice in Service spec when editing as yaml

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/dashboard#4042]
When trying to create a nodeport service and using `Edit as yaml` instead of the form option, a second `type: NodePort` is set which will cause the nodeport creation to fail if the duplicate is not removed first

```console
Versions
Component 	Version
Rancher 	v2.6-607fcdde62ddc924bc8d4cae332b3393ced21605-head
Helm 	v2.16.8-rancher1
Machine 	v0.15.0-rancher69
```

![image](https://user-images.githubusercontent.com/55704795/131004210-a4989fae-2c96-47af-adcf-6bf8f27948e5.png)

**Comment by sowmyav27** [comment]
**On 2.6.0**
<img width="473" alt="Screen Shot 2021-09-17 at 4 19 58 PM" src="https://user-images.githubusercontent.com/26032343/133863068-439f3354-d803-4a97-b98a-be8d937e0662.png">


**On 2.6-head commit id: `1a57856`**
<img width="462" alt="Screen Shot 2021-09-17 at 4 20 57 PM" src="https://user-images.githubusercontent.com/26032343/133863123-47a1db1d-d79e-45b6-bb3c-0df3c889ae32.png">
