### ISSUE TITLE
Adding and deleting PVC prevents Deployment with error that PVC name cannot be empty

### ISSUE THREAD

**Issue by oskapt** [rancher/dashboard#4047]
I hit this with 2.6-head:

1. Create a Deployment
2. Change to the Storage Tab
3. Choose "Create a Persistent Volume Claim"
4. Delete the PVC block that gets created
5. Create and Edit as YAML no longer work

The complete error is in this screenshot:

![image](https://user-images.githubusercontent.com/171292/131040079-3d273490-b094-45c0-90b6-432f8ae15912.png)

This appears when clicking Create. If you click "Edit as YAML" then the system still POSTs the data, and the error appears in the browser console. The button appears to the user to do nothing. 

This error is unrecoverable.

**Comment by catherineluse** [comment]
The first issue is that when you open the PVC form, it creates a hook to save the PVC. The hook is saved on the model for the workload. That hook for saving the PVC is not being cleaned up when you close the form. My draft PR fixes that issue by deleting the hook for the PVC when you close the PVC form - if there's only one PVC form in the dynamic list.

But there's another issue with this form when you create two PVCs. Let's say you name the first one pvc1 and the second one pvc2. If you attempt to delete pvc1, then pvc2 is the one that actually disappears. This mixup makes it so that my PR can't delete the correct hook if you delete the forms out of order. If you delete the second one first, it works, but not if you delete the first one first. I'm starting to think that's a separate issue with how the generic ArrayList component works.

**Comment by catherineluse** [comment]
I think fixing https://github.com/rancher/dashboard/issues/4323 is a prerequisite for fully getting this deletion to work properly.

**Comment by brudnak** [comment]
**My checks PASSED**
  
**Reproduction Environment:**

| Component               | Version                                        |
| ----------------------- | ---------------------------------------------- |
| Rancher version         | 2.6.1                                          |
| Rancher cluster type    | Docker install                                 |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu1~20.04.2        |
| Downstream cluster type | Downstream RKE1 EC2                            |
| Downstream K8s version  | v1.21-rancher1-1                               |
| Browser type            | Google Chrome                                  |
| Browser version         | Version 94.0.4606.81 (Official Build) (x86_64) |

![01-issue-4047-repro-env](https://user-images.githubusercontent.com/40877149/137563704-eeccdf43-e270-4fd9-a8e0-6034b2f8dd17.png)

**Reproduction steps:**

1. Starting from the Rancher homepage `/dashboard/home`
2. Click the hamburger menu -> `Cluster Management` -> `Explore` (next to cluster described in environment setup) -> `Workload` -> `Create` -> `Deployment`
3. Fill out the required fields
   - Name: `hello-world-test`
   - Container Image: `brudnak/hello-rancher-golang`
4. Click the `Storage` tab -> click `Add Volume` -> Select `Create Persistent Volume Claim`
   - **DO NOT** enter any info in the Persistent Volume Claim card
5. Click the `X` at the top right section of the Persistent Volume Card
6. Click `Create`

**Results**

An error message is displayed on the screen, provided below. Also, see screen shot labeled `A1` under `Additional Info`. Clicking `Edit as YAML` also stops functioning at this point as well. As mentioned by the creator of this issue.
```txt
PersistentVolumeClaim "" is invalid: [metadata.name: Required value: name or generateName is required, spec.accessModes: Required value: at least 1 access mode is required, spec.resources[storage]: Invalid value: "0": must be greater than zero]
```

**Additional Info:**


![02-a1-issue-4047](https://user-images.githubusercontent.com/40877149/137563742-6cab25fa-6bcc-43d6-a4bd-7a8096588122.png)

-----
  
**Validation Environment:**


| Component               | Version                                            |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-a636bda2a00e939665b381f704ea8556c39d1a84-head |
| Rancher cluster type    | Docker install                                     |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu1~21.04.2            |
| Downstream cluster type | Downstream RKE1 EC2                                |
| Downstream K8s version  | v1.21.5-rancher1-1                                 |
| Browser type            | Google Chrome                                      |
| Browser version         | Version 94.0.4606.81 (Official Build) (x86_64)     |

![03-issue-4047-valid-env](https://user-images.githubusercontent.com/40877149/137563718-2c363809-33f5-4ceb-b4ba-bed647725d06.png)

  **Validation steps:**

1. Starting from the Rancher homepage `/dashboard/home`
2. Click the hamburger menu -> `Cluster Management` -> `Explore` (next to cluster described in environment setup) -> `Workload` -> `Create` -> `Deployment`
3. Fill out the required fields
   - Name: `hello-world-test`
   - Container Image: `brudnak/hello-rancher-golang`
4. Click the `Storage` tab -> click `Add Volume` -> Select `Create Persistent Volume Claim`
   - **DO NOT** enter any info in the Persistent Volume Claim card
5. Click the `X` at the top right section of the Persistent Volume Card
6. Click `Create`

**Result**
  
  Workload is successfully created after deleting the empty Persistent Volume Card. :tada:
