### ISSUE TITLE
Cluster member unable to install apps

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#4059]
**Summary:**
A cluster member cannot install apps.
In the event the cluster member is not expected to be able to install apps I would ask why? They should not see apps in the UI then.
Vincent mentioned there's not a whole lot we can do here -- most of our apps deploy at cluster-level and thus need to at least be a cluster owner. A cluster member can only deploy into namespaces they own. -- In this case we should perhaps determine which apps (by testing) will work for cluster member - filter and only display these. The not-so-fun part is this would require testing all apps manually and creating a filter/list and maintaining it.

**Environment:**
Rancher version: v2.6-head `607fcdde6` pulled at 8/26/21 8:58 am Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.4-rc1+rke2r1

**Steps to Reproduce:**
1. Create a cluster as a restricted user. Add a standard user that will be the cluster member.
2. Log in as the cluster member. Create a project. Try to install the Longhorn app in into this project. The install fails.
3. Create a namespace in the project. Try to install the Ambassador app into this namespace. The install fails.
 
**Expected Result:**
I expected Longhorn to install.
I expected Ambassador to install.

**Actual Result:**
Longhorn does not install. It gets an error that appears may be rbac related.
![image](https://user-images.githubusercontent.com/45179589/131176989-a316b979-321b-4352-82ab-93440cf81d01.png)

Ambassador does not install. It gets an error that appears may be rbac related.
![image](https://user-images.githubusercontent.com/45179589/131177204-9b03f892-0906-483e-97aa-ecfbc11715c2.png)

**Additional Info:**
I tried other apps like monitoring this too failed with similar errors. I suspect most or all apps will not install.

**Comment by catherineluse** [comment]
I'm closing this issue in favor of https://github.com/rancher/dashboard/issues/6667, as it is more of an enhancement to allow admins to hide charts.

**Comment by davidnuzik** [comment]
Re-closing based on Catherine's comment 11/5/2022 -- looks like Zube probably reopened this on accident some time ago.
