### ISSUE TITLE
Default audit interval is appearing as 60s instead of 300s

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#406]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable gatekeeper.
2. Verify the default audit interval 

**Result:**
The default audit interval appears as 60s.

**Expectation.**
The default audit interval should be 300s.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2486-head- cf6d0c979
- Installation option (single install/HA): Single

**Comment by westlywright** [comment]
As mentioned offline, the issue here is that the default config for the chart is hard coded into the UI as Steve offers no way that I can find to get the default values for the chart so the config has to be hard coded into the UI.

**Comment by khushboo-rancher** [comment]
Verified on Rancher master-2559-head- 02956b782

Default audit interval is set to 300s.
<img width="1059" alt="Screen Shot 2020-03-26 at 2 58 48 PM" src="https://user-images.githubusercontent.com/60111667/77700949-76e69800-6f72-11ea-9ea8-f56a296f3499.png">

As discussed with @westlywright he will be creating another issue/PR to track modification required in pulling this value from chart.
