### ISSUE TITLE
Update RKE2 instance options default values

### ISSUE THREAD

**Issue by PennyScissors** [rancher/dashboard#4066]
Problem:
The default 2cpu/2gb in the instance options when creating an RKE2 vsphere cluster with vSphere cloud provider are under the 2cpu/4gb minimum recommended. If a cluster is provisioned using the default values, the vsphere CSI node daemonset starves and falls into a crashloop sporadically (more info in this [issue](https://github.com/rancher/rancher/issues/33875)).

Solution:
Update default values to the minimum recommended.

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/commit/3882e72f4d74bf4d8de25c6f8301655e597064f6

**Comment by anupama2501** [comment]
Verified on v2.6-head `1ae31b1`

Template for rke2 vsphere node driver clusters  has the default value of 2cpus and 4GB memory

<img width="1296" alt="Screen Shot 2021-08-30 at 1 39 16 PM" src="https://user-images.githubusercontent.com/38144301/131402495-7cadbf60-0330-49f5-9eea-d716464d4e73.png">

Cluster has come up active when the default values selected.
