### ISSUE TITLE
[rke2 ec2 cluster provisioning] User can't de-select amazon ec2 region if they first select a region they don't have access to -> user can't make changes to the nodepool

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4071]
on v2.6-head (1ae31b1) Repro steps:
* provision an rke2 cluster using amazon ec2 as the provider
  * when adding a node pool, use a region that the user doesn't have access to (i.e. `af-south-1`)

Result: 
user's node pool disables all settings, with this message `you are not authorized to perform this action`. There is a 403 `forbidden` error in the console for the request. 
<img width="660" alt="Screen Shot 2021-08-30 at 11 41 56 AM" src="https://user-images.githubusercontent.com/16691014/131389187-be096eda-887d-4a61-accf-9d0d094f75d5.png">

Expected Result: 
User should be able to fix their mistake without removing the entire nodepool (this was the simplest workaround I could find to continue creating the cluster)
potential solution: 
* field that resulted in the error would remain empty, and the error message could display _in addition to_ the existing fields instead of in place of them.

**Comment by gaktive** [comment]
Phil to work with Vince on leveraging an existing AWS setup.

**Comment by slickwarren** [comment]
on v2.6-head (38bd9ec):
* provision an rke2 cluster using amazon ec2 as the provider
  * when adding a node pool, use a region that the user doesn't have access to (i.e. af-south-1) -- pass
  * able to re-select a working region after selecting a region that user doesn't have permission for -- pass

<img width="756" alt="Screen Shot 2021-09-17 at 5 07 36 PM" src="https://user-images.githubusercontent.com/16691014/133870558-9ebf4fb4-b796-4565-818f-6a6538821874.png">
