### ISSUE TITLE
`Legacy` resources show up as `root` (for project level) or `Root` (for cluster level) resource when searching a cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4075]
Reproducible on v2.6.0-rc9:
* enable legacy options in rancher
* provision a downstream cluster
* search the cluster for `catalogs` or `alerts`
* results show multiple sections, and is unclear to user which is correct
<img width="481" alt="Screen Shot 2021-08-30 at 1 05 53 PM" src="https://user-images.githubusercontent.com/16691014/131400113-9910e74d-16d9-46af-9ea9-2559be3b0a72.png">
<img width="531" alt="Screen Shot 2021-08-30 at 1 03 42 PM" src="https://user-images.githubusercontent.com/16691014/131400118-ce8e98c7-52ac-4b40-9b65-47f3b01a5276.png">

Expected Result:
section that the search belongs to should be clear to the user.

Additional Context:
 It appears that `root` maps to the project level for legacy resources, and `Root` is for the cluster level. 

Potential Solution:
* use the information from additional context to label the information more appropriately:
  * `root` could be `Legacy Project` and `Root` could be `Legacy Cluster` (other suggestions for new names are welcome)

**Comment by nwmac** [comment]
The legacy pages should not show up in the search at all, so we'll hide them.

**Comment by slickwarren** [comment]
on 2.6-head (a6e7905):
* none of the legacy features show up in search now
