### ISSUE TITLE
UI should change wording for RKE2 snapshots

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#4081]
**Summary:**
RKE2 is different from RKE1 in that it will take a snapshot per each node with etcd role. As such we should consider changing the wording on the cluster creation form -- it mentions snapshots to retain (count) but for rke2 it's really _Sets of Snapshots_

**Environment:**
Rancher version: v2.6.0-rc10

**Steps to Reproduce:**
1. Create an RKE2 cluster with one of the node drivers
2. Notice it says "Snapshots" to retain - this could confuse users -- suggest for RKE2 only it should say something like "Sets of Snapshots"

![image](https://user-images.githubusercontent.com/45179589/131423898-9a686cd9-60aa-4d21-ad3d-3b4914e70031.png)

Pictured below - user took two on-demand snapshots and 2 automatic snapshots have happened on this 3-node etcd rke2 cluster. It's not 2 automatic snapshots here -- it's two sets that are retained (during cluster creation I indicated to keep last 2 sets of snapshots).
![image](https://user-images.githubusercontent.com/45179589/131423878-4a0568c6-cd48-4e0a-a78a-22e00fe66859.png)

**Comment by nwmac** [comment]
@vincent99 Does this sounds reasonable? If so, all we need to do is change the string in Dashboard, since the RKE1 screen is provided by Ember.

**Comment by vincent99** [comment]
The snapshots are physically on each node and each node independently keeps as many as you say to without knowing about any of the others.  So I'm not sure "sets of" really clarifies anything, if you add/remove nodes you can have more than 5 "sets".

It's really more like "Keep the last [n] snapshots per node".

**Comment by nwmac** [comment]
We will change the suffix from 'Snapshots' to 'Snapshots per node' - not sure the control will allow such a long suffix, but we'll see.

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `1a57856` pulled 9/17/21 ~9:30am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: n/a
 
**Validation steps:**

1. Create an RKE2 cluster - under Cluster Configuration section > etcd the "Keep the last" field now indicates "Snapshots per node" since RKE2 creates 1 snapshot per each node (unlike RKE1)
![image](https://user-images.githubusercontent.com/45179589/133860681-7fa4847f-93b7-4825-bc40-166784b1615a.png)

2. Create an RKE1 cluster - can confirm that this form is unchanged, as expected.
![image](https://user-images.githubusercontent.com/45179589/133860719-0f8c4670-bcbb-4c38-b265-6f0c5f19b1fe.png)
