### ISSUE TITLE
UI Banners not displaying on dashboard

### ISSUE THREAD

**Issue by yankees5963** [rancher/dashboard#4086]
I use UI (classification) banners, which should display on every webpage. However, they do not show on the new dashboard UI. Tested on 2.5.8, will test on 2.5.9 and 2.6.0

**Comment by vincent99** [comment]
These are (only) in dashboard in 2.6.

**Comment by yankees5963** [comment]
Considering that 2.6.0 is not stable, this is not a viable option. We will need the classification banners in the latest stable release (2.5.9 currently)
