### ISSUE TITLE
Only show available versions for aks upgrades

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#4103]
https://github.com/rancher/rancher/pull/34624
https://github.com/rancher/rancher/issues/34161

There is a new option for the aksVersions endpoint that will only return  versions that an aks cluster can upgrade to.  Currently rancher will allow users to select versions they cannot upgrade to putting the cluster in an error state.

**Comment by gaktive** [comment]
@vincent99 to get to the bottom of this and clarify what next actions are.

**Comment by paynejacob** [comment]
The pr for this has been merged https://github.com/rancher/rancher/pull/34748 for example usage please see https://github.com/rancher/rancher/pull/34698#issuecomment-919557772

**Comment by nwmac** [comment]
@codyrancher I don't see a PR for this - is there any UI work? Not sure why this is in Review

**Comment by codyrancher** [comment]
@nwmac I was just waiting for the build to go through before I merged it. It's in now.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `ba43472`**
- Create a cluster AKS with k8s 1.19
- Edit config on the cluster
- Only versions that are applicable for upgrade are shown
<img width="955" alt="Screen Shot 2021-09-21 at 7 47 57 AM" src="https://user-images.githubusercontent.com/26032343/134193347-fe8977f7-81c0-4b27-9e5b-1729c8a7ddeb.png">
