### ISSUE TITLE
Minor layout issue on the Secret chooser page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4108]
More Info links don't appear on the right:

![image](https://user-images.githubusercontent.com/1955897/132006310-1ba5efdb-1507-461e-986b-2353a43f0d98.png)

I think the flex direction should be column not row on the the subtype-banner class

**Comment by ronhorton** [comment]
![Screen Shot 2021-09-20 at 2.53.39 PM.png](https://zube.io/files/rancher/519067906f996a09f14e8fa77730960a-screen-shot-2021-09-20-at-2-53-39-pm.png)

pass - verified in v2.6-45dfeb4f363bffec8ce8cf929ace75352e5fdb26-head
