### ISSUE TITLE
VMware integration: No Refresh of Datacenter resources when creating an RKE2-vSphere Cluster

### ISSUE THREAD

**Issue by maveice** [rancher/dashboard#4111]
During the creation process of an RANCHER RKE2/K3s-Cluster with Kubernetes Provider "VMware vSphere" vSphere resources (e.g. DataStore or ResourcePools) are not refreshed/updated AFTER selecting a different Datacenter from the Combo-Box.

Please advice. Thank you.

**Comment by slickwarren** [comment]
We only have vsphere setups with 1 data center, so to test this on 2.6-head ( 024e6fa )
* Edit dom -> Add a fake entry
* Select the fake entry -> everything reloaded
* Fake entry was removed
* Real value was selected and datacenter resources populated correctly

using the same steps on a version without the fix does reproduce the issue.
