### ISSUE TITLE
Global Settings -> Branding Bugs

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#4119]
If you upload certain image resources they will render outside the preview area. Granted, these assets are larger than 200px wide..

![image](https://user-images.githubusercontent.com/45179589/132399859-3fd7edbd-f248-40c2-a817-96ca6d4a6ebd.png)

If you upload less common image formats like TIFFs they will not work. We should declare which image types are supported.
![image](https://user-images.githubusercontent.com/45179589/132399908-cfeef2f9-4019-48ec-8a91-3ba0fbbf5def.png)

Example SVG I have that will render outside the preview area (GitHub forced me to zip it):
[BITCOIN_FULL_LOGO_SVG.zip](https://github.com/rancher/dashboard/files/7123904/BITCOIN_FULL_LOGO_SVG.zip)

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: c35f112`

Large images like the attached bitcoin logo are properly rendered inside the expected preview areas. Smaller images are still working great and images of the accepted types are working as expected. 

There is now text present stating: `Accepted formats: JPEG, PNG, SVG.`

![image](https://user-images.githubusercontent.com/107147272/206567456-148d0d95-3b46-42de-ae14-8fd15c80f961.png)
