### ISSUE TITLE
UI displays upgrade options from different catalog for OpenEBS

### ISSUE THREAD

**Issue by rmweir** [rancher/dashboard#4121]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

**To Reproduce**

1. Install OpenEBS from helm3-library catalog in cluster using old UI.
2. Go to installed apps of the cluster in dashboard.

**Result**
The "Upgradable" column will show a version not available in the catalog ember uses to install openebs. If the upgrade is attempted an error will be encountered.

**Expected Result**

Do not show upgradable unless there are upgrade options in actual catalog. If upgradable cannot be supported since it was installed with old catalog that is fine as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/19376037/132430779-56b9d975-526e-4114-a747-fc04f75c98b8.png)
![image](https://user-images.githubusercontent.com/19376037/132430951-df450f2e-2a0f-4190-b1a2-851b280cf54e.png)

**Additional context**

**Detailed Description**

**Context**

Working on making it so users can manage apps using the dashboard that were originally created in ember UI.

**Comment by jordojordo** [comment]
This is a related issue to #4120. The issue in this case with OpenEBS is caused by the App utilizing a chart (2.5.1) that no longer exists in the default repositories.

There is a PR (#4332) that will disallow the user to update/edit an App that was created using the old UI. Instead it will redirect them to the Cluster Management section which utilizes the old UI.

**Comment by jordojordo** [comment]
@ronhorton 
**Dev template**
1. Navigate to old UI `/g/clusters`, for example: `https://localhost:8005/g/clusters`

![local-select](https://user-images.githubusercontent.com/40806497/144272657-faf77018-5398-4468-a961-9889b1d85e5c.png)


2. Select `Apps` in the navigation and click on `Launch`

![launch](https://user-images.githubusercontent.com/40806497/144272682-71341b21-d676-4c2d-be39-e2380a4fda55.png)


3. Choose OpenEBS from the helm3 library

![helm3ebs](https://user-images.githubusercontent.com/40806497/144272769-9b40dcd7-9176-4f19-9512-97178ab1d893.png)


4. Launch the app

5. Return to the cluster app page in the new dashboard, for example: `https://localhost:8005/c/local/apps/catalog.cattle.io.app`

![appdashboard](https://user-images.githubusercontent.com/40806497/144273321-697632f8-1264-41c8-afbd-0d2fe0163138.png)

6. Select the `Edit/Upgrade` action for the OpenEBS app

![old-ebs](https://user-images.githubusercontent.com/40806497/144273602-fe0bd148-e8a1-421d-8962-cbd1d7a0bcd7.png)

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6.3-rc3`

1. In `2.6.2` rancher, enabled legacy feature flag
2. installed `openebs.` 
3. verified `openebs` installed on cluster
4. upgraded to `2.6.3-rc3`
5. enabled legacy feature flag
6. Navigated to Cluster from step 2
7. Navigated to `Project > Apps`

`opendbs is installed and up-to-date`

![Screen Shot 2021-12-01 at 5.01.58 PM.png](https://zube.io/files/rancher/9f13c54cf1170141252a5e42eada5d84-screen-shot-2021-12-01-at-5-01-58-pm.png)
