### ISSUE TITLE
Side nav cluster search disappears after entering non-existent cluster

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4128]
- set up rancher with enough clusters such that in the side nave the cluster search shows (these can be 'imported' clusters that aren't registered)
- enter text that results in no matching clusters
- entire search section disappears

**Comment by anupama2501** [comment]
Verified on v2.6-head 1a57856

Created multiple clusters and verified on left hand navigation when given a name thats not present in the list, `No matching clusters` is shown and the search does not dissapear
