### ISSUE TITLE
Azure storage class allows picking shared disk - but this is no longer supported

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#4134]
**Summary:**

Azure removed support for shared disks - we should hide this so it's not an option for the azure storage class.
https://www.gitmemory.com/issue/Azure/AKS/2147/786517062

This one entry in this drop down should be removed:
![image](https://user-images.githubusercontent.com/45179589/132773710-ff606d93-5a00-4701-a2cb-1c610314544b.png)

-----

**Environment:**
Rancher version: v2.6-head `a6e7905cf` pulled 9/9/21 1:28pm Pacific & v2.6.0
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: azure - rke2
Downstream K8s version: v1.21.4+rke2r2

**Steps to Reproduce:**
1. Create an rke2 cluster with the azure node driver. Be sure to properly set up the azure cloud provider (this process is not simple).
2. Create a storage class with the azure driver. Pick shared.
3. Create a PVC with the storage class - it will never provision (shared is no longer supported).
 
**Expected Result:**
I expected the Shared entry in the drop down to not be an option.

**Actual Result:**
The shared entry in the drop down is available, but should not be.

**Additional Info:**
Is a per-existing issue that affects older Rancher versions as well. Should probably [backport to 2.5](https://github.com/rancher/dashboard/issues/4135) as well.

**Comment by nwmac** [comment]
You don't need to create a cluster to reproduce - just start at Step 2 above.

@davidnuzik Is there an Azure document that confirms that shared disks have been dropped?

**Comment by davidnuzik** [comment]
Oh I thought you must set up azure cp to access these features.
I was not successful in finding official documentation on this @nwmac

**Comment by gaktive** [comment]
I'll see if I can figure out the official status of this Azure storage thing.

**Comment by gaktive** [comment]
@davidnuzik While I look the state of possible deprecation, from what I've been told, you may see that error if you don't have access to Azure itself (though @vincent99 can clarify). Is everything setup for your Azure access to allow you to connect to storage?

**Comment by davidnuzik** [comment]
I can create other storage just fine like set up this storage class, and create a PVC for non-shared disks.

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `1a57856` pulled 9/17/21 ~9:30am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.4+rke2r2
 
**Validation steps:**

1. Try to create a storage class - Shared is no longer shown, as expected:
![image](https://user-images.githubusercontent.com/45179589/133867156-3315512d-be73-4437-a416-dfd769c8d790.png)

 
**Additional Info:**
