### ISSUE TITLE
Add the rollback option to the workload when it is applicable

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#4149]
**Setup**
- Rancher version: 2.6.0
- Browser type & version: Chrome 

**Describe the bug**

The multiple-cluster management UI has the option `Rollabck` on the workload when it is applicable, and it is currently missing on the Cluster Explorer UI.  We should consider bringing the option to the Cluster Explorer UI. 

<img width="1520" alt="Screen Shot 2021-09-13 at 1 50 08 PM" src="https://user-images.githubusercontent.com/6218999/133154688-e5b4d2f0-c585-4b8b-8d08-fbfe89446cd2.png">
 
![image](https://user-images.githubusercontent.com/6218999/133154794-59d395ab-6b66-4ad2-b4a0-d1d6a0a30589.png)

**Comment by jmcsagdc** [comment]
**Reproduced IN**
v2.6.0

**confirmed in**
HEAD at v2.6-223ec88b70d87cecee8fdbe8d98e30cf004b25d9-head

Using the steps in the PR:

1. In the local cluster, create Deployment with the nginx:1.21 image.
2. Upgrade by editing the Deployment to make its image nginx:1.21.3.
3. Click ellipsis menu and see Rollback.

**Confirmed**

![rollback-present](https://user-images.githubusercontent.com/15971368/134439492-c1d20477-603f-4fde-b8ea-0e43582a4a61.png)

4. Click the Revision (only one here) then Rollback
5. On Deployments list view, image name reverted to nginx:1.21. 

**Confirmed**

6. Click the Deployment name to open the Deployment detail page and verify Image is now nginx:1.21.

**Confirmed**

7. Create a new Deployment with the nginx:1.21 image
8. Click ellipsis menu and see Rollback. Click it.
9. In Roll Back window, the UI says "There are no revisions to roll back to." and the menu is empty when clicked

**Confirmed**

![no-revisions](https://user-images.githubusercontent.com/15971368/134439171-267b1071-4945-4223-bcd1-19ef8bbfd749.png)
