### ISSUE TITLE
Node details page review & bugs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#415]
- [x] Review node detail pages and make changes so no more circle & check/x are correct.
![image](https://user-images.githubusercontent.com/11514927/77482952-45d85d00-6de4-11ea-8289-6afee674c8cf.png)

**Comment by lvuch** [comment]
Thoughts on either of these? @vincent99 @tfiduccia 

<img width="685" alt="Screen Shot 2020-03-25 at 9 27 18 AM" src="https://user-images.githubusercontent.com/3013118/77568546-02362f80-6e86-11ea-93bf-5a62836e73c1.png">
<img width="684" alt="Screen Shot 2020-03-25 at 9 27 09 AM" src="https://user-images.githubusercontent.com/3013118/77568554-03fff300-6e86-11ea-842b-0a1f9ef338c5.png">

**Comment by lvuch** [comment]
@tfiduccia via slack selected the progress bar options. @tfiduccia please confirm

**Comment by tfiduccia** [comment]
@lvuch - Vincent and I discussed and agree to progress bar option.

**Comment by tfiduccia** [comment]
Fixed
