### ISSUE TITLE
UI workload/services management issues post-upgrade to 2.6

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4159]
In conjunction with work being done in https://github.com/rancher/rancher/issues/34639, @kinarashah ran into some UI issues during a 2.5.x to 2.6.0 upgrade:

- On editing a workload to add Ports, there's an error "service already exists" but the request still goes through so there's no actual issue blocking the edit. Could we handle this error better?

- On deleting a workload ... this has been split out into issue https://github.com/rancher/dashboard/issues/4212 and will be considered separatekly

- The workload port annotation seems to be formatted wrong (both in 2.5 vue and 2.6). Service gets created but the endpoint controller fails on unmarshalling when it tries to read a []workloadID like: ```['default/svc_name']:  Failed to unmarshal targetWorkloadIds, error: invalid character '\'' looking for beginning of value``` . 
This doesn't seem related to the issue directly, but I just noticed this and wondering if this causes any other unknown issues.

**Comment by sgapanovich** [comment]
first issue:
1. created a workload with a clusterIP service in the old UI
2. opened the workload to edit in the new UI
3. was able to add/edit a new port 

second issue was handled in another ticket https://github.com/rancher/dashboard/issues/4212

third issue:
monitored logs while testing first and the second issue and no unmarshalling error was logged

**Comment by sgapanovich** [comment]
**reason for reopening the issue:** first issue is not fixed completely

**Environment:**
Rancher version: v2.6-10dfee4974b196c0d3d8a33bc80f5d750c0272f2-head
Rancher cluster type: single-node docker install
Docker version: 20.10

Downstream cluster type: n/a
Downstream K8s version: n/a

======================================

**Steps to reproduce:**
1. navigate to the old UI
2. create a workload with no port added 
3. navigate to the new UI
4. edit the deployment you created 
  - add a port (for ex. cluster ip)
5. click "save"

Issue:
the workload can't be saved with the following error appeared : `services "{name}" already exists` 

![was able to reproduce](https://user-images.githubusercontent.com/40282141/135169856-07ecef7d-5bfe-46ca-82ba-57518debf3b0.png)

**Comment by gaktive** [comment]
@mantis-toboggan-md will investigate.

**Comment by gaktive** [comment]
@Jono-SUSE-Rancher heads up that this will need to move out to the next version based on backend requirements.

**Comment by gaktive** [comment]
Filed https://github.com/rancher/dashboard/issues/4313 to look into 1st issue. Workaround through old UI works. Passing back to QA for additional validation.

**Comment by sgapanovich** [comment]
**Test Environment:**
Rancher version: 2.6.1-rc7
Rancher cluster type: ha
Docker version: 20.10
Chrome version: Version 94.0.4606.61 (Official Build) (x86_64)

Downstream cluster type: ec2 node cluster
Downstream K8s version: v1.21.5-rancher1-1

================================================================

**Test Steps:**
test case described by @mantis-toboggan-md is reproduced:
1. create a deployment in the old UI with no ports 
  - headless service is created 
2. open to edit the deployment in the new UI
3. add a port with 'do not create a service'
4. service got updated (headless became clusterIP and the port got updated)
  - removing the port in the old ui will change the service back to the headless and to the original port)
      - workaround: update the services created in the old ui using old ui

---------

original issue is fixed:
1. create a deployment in the old UI with a clusterIP port
2. service is created 
3. open to edit the deployment in the new UI
4. add a port 
  - original issue was a new port couldn't be added (it's fixed)
  - **but there is another issue with it:**
      - if you add a clusterIP the service is not created and you can see it here https://github.com/rancher/dashboard/issues/4280

-------------

extra testing:
if a user created a deployment in the old UI with a port 
  - the correct port type is displayed in the new UI but that port type can't be updated in the New UI so the user needs to go back to the old UI to modify that (brings us back to @mantis-toboggan-md and the workaround)

issue found while testing ^^^ scenario in the new UI 
https://github.com/rancher/dashboard/issues/4316

--------------


second issue in the ticket confirmed to be fixed (workaround):
when a user deletes a deployment created in the old ui we can't delete the services which were created in the old UI so we show them the warning 

![warning.png](https://zube.io/files/rancher/eaa9e989963ac08e4b826e856b78f385-warning.png)

**Comment by sgapanovich** [comment]
@gaktive @mantis-toboggan-md  https://github.com/rancher/dashboard/issues/4316 is created while testing this ticket
