### ISSUE TITLE
update node driver name to `Equinix Metal` from `Packet`

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4161]
Node driver name to be updated from `Packet` to `Equinix Metal` 
present under: Cluster management --> Drivers --> Node Drivers

<img width="400" alt="Screen Shot 2021-09-14 at 1 21 11 PM" src="https://user-images.githubusercontent.com/38144301/133328426-11050c3b-0bf2-469a-8d0f-27a359d6673a.png">

Reference issue: https://github.com/rancher/rancher/issues/33758

**Comment by rak-phillip** [comment]
@gaktive I think I should have time to take a look at this one

**Comment by gaktive** [comment]
@rak-phillip go for it!

**Comment by richard-cox** [comment]
Not sure why Zube isn't tracking the PR containing the fix... but here it is... https://github.com/rancher/ui/pull/4757

**Comment by anupama2501** [comment]
Verified on v2.6-head 1a57856

`Packet` name is updated to reflect `Equinix Metal` 
Logo is updated as well - displayed when creating equinix Metal cluster
<img width="392" alt="Screen Shot 2021-09-17 at 4 55 17 PM" src="https://user-images.githubusercontent.com/38144301/133864548-b578db52-2413-4728-8e27-d1b85c52ccd0.png">
