### ISSUE TITLE
Removing an app in Cluster Tools requires a manual refresh to update the app status

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4165]
**Setup**
- Rancher version: 2.6.0
- Browser type & version: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Describe the bug**

After removing an app in Cluster Tools the app continues to be listed as installed until manual refresh of the browser.

**To Reproduce**

Install an app in Cluster Tools. Remove the app in Cluster Tools.

**Result**
App is listed after the removal.

**Expected Result**

Browser page should be automatically updated and display the app as not installed.

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment]
Could not reproduce in 2.7-head (2.7.0 ish).

The card for the Cluster Tool transitions back to it's uninstalled state once the uninstall helm operation completes
