### ISSUE TITLE
Cronjobs list missing Suspend Status and Easy toggler

### ISSUE THREAD

**Issue by joebone** [rancher/dashboard#4166]
**Setup**
- Rancher version: 2.6.0
- Browser type & version: Edge Latest

**Describe the bug**
Cronjobs have no visual indicator for whether they are suspended or not, and no obvious interaction to suspend or resume them. It seems to be hidden away in the Scaling and upgrade policy subsection of the edit configuration form, but that was only found by searching in the browser for the word suspend and clicking through each section until a match was found.

**To Reproduce**
Open the cronjobs list.

**Result**
All cronjobs, suspended or not, are displayed as "active".

**Expected Result**
Disabled cronjobs should show a different status, and there should be an "easy" interaction to suspend or resume a cronjob, as there was in <= 2.4.x

**Screenshots**

![image](https://user-images.githubusercontent.com/31443/133422281-406a01f2-ea2a-4355-afa1-612c93993e68.png)
Contrast to previous ui:
![image](https://user-images.githubusercontent.com/31443/133422658-1f01ca46-fe40-43ee-9aa7-5813a88c023e.png)

**Context**
This is just quality of life, a regression in the ease of use of the product from previous versions.

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID 931a0f0`
On the cronjobs page, there are now additional action buttons for `Run Now`, `Resume` and `Suspend`
The status of suspended jobs, resumed jobs and active jobs now are represented correctly in the `State` comlumn
<img width="1060" alt="Screen Shot 2021-11-04 at 10 16 23 AM" src="https://user-images.githubusercontent.com/89212856/140330421-917ef473-6894-46e2-a1bb-b6b26de8a55f.png">
.
