### ISSUE TITLE
Unable to edit a Fleet cluster

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4167]
- Navigate to Continues Deployment --> Clusters
- Pick any cluster (tried with k3s, rke2 and a harvester provided one) and click the `Edit Config` action
- In prod user is taken to the edit page but with no form, in dev get a full page white error with `Cannot read property 'labels' of null`

Under the hood it looks like there's a failed (404) http get for `/v3/clusters/<cluster id>`. Interestingly the response is `{"baseType":"error","code":"NotFound","message":"clusters.management.cattle.io \"richard-cox-rke2-admin\" not found","status":404,"type":"error"}`

The missing `value` then causes cascading failures within the component

**Comment by gaktive** [comment]
@vincent99 is this an easy fix?

**Comment by Auston-Ivison-Suse** [comment]
I was able to reproduce this issue on v2.6.0 
Validated the fix using 2.6-head commit: ba43472

I see the 404 error in both the network check as well as getting the error message. 

1. This screenshot is of the failure. 
2. Screenshot of the end result of the cluster being edited. No errors in the network tab. 


1. ![Screen Shot 2021-09-21 at 11.23.29 AM.png](https://zube.io/files/rancher/7e923165b5fdcfdee3aac9344b5e5048-screen-shot-2021-09-21-at-11-23-29-am.png)

2.![Screen Shot 2021-09-21 at 11.25.02 AM.png](https://zube.io/files/rancher/e747e64162cb0be5c8744250ddba701b-screen-shot-2021-09-21-at-11-25-02-am.png)
