### ISSUE TITLE
Update & improve grouped bulkable table actions

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4168]
- During the harvester integration a new dropdown has been created and used in the table's bulk actions section
- Actions in this dropdown are manually included by tagging them as `external`

Task 1)
- Update the dropdown component after design review
  - It's similar to other drop downs, but in a more button-y way
  - Should this select a type and then clicking on text applies that type?
  - Sizing, padding, etc

Task 2)
- Remove the `external` mechanism for deciding which actions to show and if the button is shown
- Determine which buttons can be shown or be collated in drop down given how much space is available 

![image](https://user-images.githubusercontent.com/18697775/133471600-983539b3-7d58-419f-8c6b-d3b09957be6c.png)

For background see https://github.com/rancher/dashboard/pull/3726#discussion_r704502639

**Comment by richard-cox** [comment]
I thought there were a lot more of these, but having just searched the latest code for the 'extends' tag it's only applied to this `Virtual Machine` type. So the 'worst case' in terms of number of buttons in Harvester is in the screenshot.

So in summary, tasks should be as follows..?

For 2.6.3
- Review the order of actions in harvester, less important or rarely used buttons should be moved to the right / end
- Remove the `external` mechanism

Improvements for 2.6.3 / 2.6.x
- Only show a single row of actions and collapse those that aren't visible into a new menu drop down (TBD)

**Comment by richard-cox** [comment]
I've created a PR which does most of the heavy lifting of determining what is shown in that drop down - #4873. There's still work here though to update how that drop down looks, see #4875

**Comment by richard-cox** [comment]
# QA Template

## Root cause

See task 2 in description. Implementation of grouped bulk actions in a drop down was not clean and required manual defining which buttons appeared in the drop down.
 
## What was fixed, or what changes have occurred

Buttons in the grouped bulk actions drop down are now dynamically decided given the available width of the area they are in.
 
## Areas or cases that should be tested

This effects all tables that contain bulk actions. Determining the time available and thoroughness of testing those is one for QA.

During development though I used the `Workload` table on a system that had both `Deployments` and `CronJobs` (to ensure there was a large number of bulk actions). 

Other area's that might be worth checking out that contain a lot of bulk actions or have high traffic
- Fleet Clusters
- Kube Nodes
- Namespaces

Please note these changes have been in place since around 10th January, so a lot of people have been using them already.
 
## What areas could experience regressions?

As above, anywhere bulk actions are used
 
## Are the repro steps accurate/minimal?

This is a new feature, so no repro steps

**Comment by maxsokolovsky** [comment]
## Dev-validate PASSED

#### Steps taken to reproduce the issue
Navigated to screens that have a set of separate action buttons, like Namespaces.
#### Rancher version on which the issue was reproduced
Initially `v2.6.3`, then observed the improved behavior in `v2.6-head d604b7e`.
#### Steps taken to see the issue fixed
Made the browser window narrow enough to trigger the DOM changes for action buttons. The buttons transformed into an Action Dropdown menu. Tried a few actions - all worked.
Verified on the Namespaces, Deployments, Pods screens.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                          |
| ------------------------- | --------------------------------------- |
| Rancher version           | 2.6.3                                   |
| Installation option       | Docker                                  |
| If Helm Chart k8s cluster | not applicable                          |
| Docker version            | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version              | v2.16.8-rancher1                        |
| Downstream cluster type   | not applicable                          |
| Downstream K8s version    | not applicable                          |
| Logged in user role       | Administrator                           |
| Browser type              | Google Chrome                           |
| Browser version           | 99.0.4844.74 (Official Build) (x86_64)  |

## Reproduction steps



1. Starting from the **default** Rancher homepage `/dashboard/home` -> browser window set to `1680 x 1050`
2. Navigate to an area where grouped actions would be present -> click `hamburger menu` -> `local` -> `Projects/Namespaces`
3. Select multiple check boxes under `Project: System`
4. Resize the browser window to `375 x 667`
5. Observe the action buttons getting crowded together

## Additional Info

## RESULTS

#### :white_check_mark: Expected
For the UI to be more responsive to screen size


#### :x: Actual
The UI was not responsive to the screen size

<hr>

## Validation Environment

| Component                 | Version / Type                                                                                |
| ------------------------- | --------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-024e6fa23af3678aafa85d4085c02143127bd3a1-head                                            |
| Commit ID link            | [024e6fa](https://github.com/rancher/rancher/commit/024e6fa23af3678aafa85d4085c02143127bd3a1) |
| Installation option       | Docker                                                                                        |
| If Helm Chart k8s cluster | not applicable                                                                                |
| Docker version            | 20.10.7, build 20.10.7-0ubuntu5~20.04.2                                                       |
| Helm version              | v2.16.8-rancher1                                                                              |
| Downstream cluster type   | not applicable                                                                                |
| Downstream K8s version    | not applicable                                                                                |
| Logged in user role       | Administrator                                                                                 |
| Browser type              | Google Chrome                                                                                 |
| Browser version           | 99.0.4844.74 (Official Build) (x86_64)                                                        |

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home` -> browser window set to `1680 x 1050`
2. Navigate to an area where grouped actions would be present -> click `hamburger menu` -> `local` -> `Projects/Namespaces`
3. Select multiple check boxes under `Project: System`
4. Resize the browser window to `375 x 667`


## Additional Info

## RESULTS

#### :white_check_mark: Expected
For the action items to be collapsed into a drop down 


#### :white_check_mark:Actual
The action items were collapsed into a drop down when the screen size shrunk
