### ISSUE TITLE
General UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#417]
Light mode:

1.  When selecting option from drop-down, the text is white and you can't read it
![image](https://user-images.githubusercontent.com/11514927/77580506-631b3300-6e99-11ea-9998-d9a912de0cae.png)

2.  Can't tell cluster drop-down has been dropped cause it's the same color as the left nav.
![image](https://user-images.githubusercontent.com/11514927/77580572-7c23e400-6e99-11ea-8ffc-b30592a5bd64.png)

3.  First Namespace section seem too high on all pages with this design
![image](https://user-images.githubusercontent.com/11514927/77580654-9f4e9380-6e99-11ea-9f00-d1db67f7e81f.png)

4.  All table headers need to be blue (needs to be fixed in secrets, config map, workload pages)
![image](https://user-images.githubusercontent.com/11514927/77580761-cc02ab00-6e99-11ea-95f0-6cbe92553352.png)

5.  In Preferences, should Developer Tools text be bold?
![image](https://user-images.githubusercontent.com/11514927/77580859-ed639700-6e99-11ea-8f39-8c2bae22f9f4.png)

6.  In Preferences should the headers of each section be all caps?
![image](https://user-images.githubusercontent.com/11514927/77580925-04a28480-6e9a-11ea-83c0-ac99793af6a2.png)

7.  The Filter field is bigger than the buttons on the top header of all list pages.  Should they be same size?  If yes, what size should they be?
![image](https://user-images.githubusercontent.com/11514927/77583839-fa36b980-6e9e-11ea-8045-7432ebd14282.png)

**Comment by lvuch** [comment]
For #2 @vincent99 will be adjusting the size and display of the dropdown to look more like a dropdown.

**Comment by vincent99** [comment]
I'm doing what now?  It already (now) literally is a dropdown (v-select); it looks the same because the background colors of the nav and dropdowns are the same.

**Comment by lvuch** [comment]
@vincent99 I thought you were going to make it wider and shorter 

![](https://files.slack.com/files-pri/T02RW4JDH-F01093UQ6TV/screen_shot_2020-03-23_at_1.30.53_pm.png)

**Comment by lvuch** [comment]
![image](https://user-images.githubusercontent.com/3013118/77679219-7d174d00-6f4f-11ea-8a4d-8ccee5b14104.png)

**Comment by vincent99** [comment]
#2 shows the cluster dropdown, not the jump menu
