### ISSUE TITLE
CIS Scans: Clicking on a scan in progress shows no data

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4171]
Install the CIS Benchmark tool.

Go to CIS Benchmark > Scans and Create a scan.

Click on the scan name - it doesn't show that the scan is in progress, or the profile - compare this with what you see when the scan has completed.

Sometimes I would see that if you go back to the scans page and wait, the page does not update - this might be for the very first scan you do.

**Comment by momesgin** [comment]
Can't reproduce the issue:

https://zube.io/files/rancher/41302387947b7d7a05e35d810ce63103-4171.mov

@gaktive should we close this issue?

**Comment by gaktive** [comment]
Let's close since this is super old.
