### ISSUE TITLE
Harvester cloud credential being displayed as `cattle-global-data:<uuid>`

### ISSUE THREAD

**Issue by bgulla** [rancher/dashboard#4172]
**Rancher Server Setup**
- Rancher version: 2.6.1-rc1
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): docker!
- Proxy/Cert Details:

**To Reproduce**
 
1. create a harvester cloud credential named `taco`
2. the displayed harvester cloud credential is then displayed as `cattle-global-data:<uuid>`

**Expected Result**

* the credential should be displayed as its friendly/display name vs it's kubernetes object name.

**Comment by guangbochen** [comment]
@n313893254 is this something already fixed in the https://github.com/rancher/dashboard/pull/3881 ?

**Comment by n313893254** [comment]
Not yet， I will fix i.

**Comment by richard-cox** [comment]
I think this will be fixed via https://github.com/rancher/dashboard/pull/4179, will confirm tomorrow

**Comment by slickwarren** [comment]
This appears to be fixed on v2.6-head (45dfeb4):

* create a harvester cloud credential named `test32` -> cloud credential displays as `test32`


<img width="350" alt="Screen Shot 2021-09-20 at 2 18 24 PM" src="https://user-images.githubusercontent.com/16691014/134077229-fdf7b65f-0379-4f55-a51b-221fe96cbb0f.png">
