### ISSUE TITLE
Localizations for machine configs

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#4177]
While addressing a few issues regarding RKE2 clusters, I came across a few instances where translations were missing (#4164, 4162). I'm sure other components are missing a few translations in this area of the app as well, for example:

[Digital Ocean](https://github.com/rancher/dashboard/blob/93a0edff586b834e4dcced8c6ba2c2ebeccb67d2/machine-config/digitalocean.vue#L160-L190)

This area of dashboard should probably be reviewed for any gaps that might exist in translations.

**Comment by nwmac** [comment]
Closing as stale/wont-fix
