### ISSUE TITLE
e2e Tests: CI: Setup test to run each time code is merged to master

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4181]
- We need to run the tests as part of CI.
- Suggest we don't feed this into the PR pipeline initially, but instead run the tests when code is merged to master.
- We could leverage GitHub actions.
- We'd need to run a backend

**Comment by cnotv** [comment]
I will start first by fixing the following:
- Issues with the current info from the documentation (https://github.com/rancher/dashboard/pull/3405#issuecomment-1060225285)
- Current issues for the existing tests (https://github.com/rancher/dashboard/pull/3405#issuecomment-1060380650)

**Comment by cnotv** [comment]
The mentioned issues were related to  a wrong IP and lac of env vars for local auth credentials.

**Comment by cnotv** [comment]
Now it seems something changed with the `.title` :upside_down_face: 

![Screenshot from 2022-03-15 16-33-25](https://user-images.githubusercontent.com/5009481/158414808-4ba6e0ad-ba1f-4fcb-af83-f356c4feeede.png)

**Comment by cnotv** [comment]
For some reasons it seems like not able to complete all the tests on master:
```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  tests/home.spec.ts                       00:15        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  tests/login.spec.ts                      00:18        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  tests/side-nav/burger-side-menu.spe      00:51        5        5        -        -        - │
  │    c.ts                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  tests/side-nav/product-side-nav.spe      02:30        5        1        4        -        - │
  │    c.ts                                                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 4 failed (25%)                      03:56       14       10        4        -        -  
```

**Comment by cnotv** [comment]
It seems like a brand new Rancher image cannot be used without an initial configuration or setup script.

![Screenshot from 2022-03-16 22-27-47](https://user-images.githubusercontent.com/5009481/158694209-bdb8113c-949e-4d51-93a4-0d4b8714a04c.png)

**Comment by cnotv** [comment]
[Looks like more tests are failing now](https://github.com/rancher/dashboard/runs/5681172912?check_suite_focus=true#step:6:355) and I cannot find the class used for the test (`.side-nav`):

```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  tests/setup/welcome.spec.ts              00:11        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  tests/pages/home.spec.ts                 00:11        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  tests/pages/login.spec.ts                00:08        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  tests/navigation/side-nav/burger-si      00:24        5        4        1        -        - │
  │    de-menu.spec.ts                                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  tests/navigation/side-nav/product-s      00:43        5        -        5        -        - │
  │    ide-nav.spec.ts                                                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  2 of 5 failed (40%)                      01:39       16       10        6        -        -  
```

**Comment by rak-phillip** [comment]
@cnotv is this what you're looking for?

https://github.com/rancher/dashboard/blob/f7109368887442e2f6c1b5863f3ae03cb48361c3/layouts/default.vue#L537

**Comment by cnotv** [comment]
It's more like Cypress cannot find it :sweat_smile: 
It seems not possible to access directly to `/c/local/explorer`

**Comment by cnotv** [comment]
It looks like building the project does not match to the deployment and neither to the running version. @nwmac Do you know why is this different and how can I reproduce a deployed version?

The current issue is that accessing directly to the URL (e.g., `/c/local/explorer`) returns error and redirects to the homepage.
