### ISSUE TITLE
Unable to create a Fleet workspace

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4188]
Think the resource type `management.cattle.io.fleetworkspace` save needs switching to norman (`v3/fleetworkspaces` - validation required)

**Comment by sowmyav27** [comment]
**on 2.6.0**

- reproduced the issues
- Creating fleet workspace in `management.cattle.io.fleetworkspace` does not work. Error "Method POST not supported" is seen

**On 2.6-head commit id: `1a57856`**
- Creating fleet workspace in `management.cattle.io.fleetworkspace` works with no errors.
