### ISSUE TITLE
[Bug] UX inconsistency with order of Cancel/OK buttons in forms and dialog boxes

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#4189]
The dashboard UI does not implement a consistent convention regarding the order of affirmative/dismissive buttons in forms and dialog boxes. 

On some pages the button order is affirmative first and dismissive second, on others its the opposite order. This should be addressed in order to improve the UX.

Example:

**Cluster Create**

<img width="342" alt="Screenshot 2021-09-16 at 18 14 33" src="https://user-images.githubusercontent.com/3813921/133648368-6651c96e-c437-4acb-9ff2-62023ad30d75.png">

**Gitrepo Create**

<img width="307" alt="Screenshot 2021-09-16 at 18 16 26" src="https://user-images.githubusercontent.com/3813921/133648345-14f3e95e-28f5-4f64-a9f8-06131d15665c.png">

**Comment by nwmac** [comment]
@neillsom Can you fix this specific case - the order should always be the OK button on the right-> so [Cancel] [OK]

Can you jam around the UK and see if you see this anywhere else? I think we generally use std components for this, so I don't think there are many places that use a custom button arrangement.

**Comment by neillsom** [comment]
@nwmac The only instances I found so far are from ui/ember and not dashboard. 

I opened a [PR](https://github.com/rancher/ui/pull/4764/files) which fixes most of the ember issues, but there are a few more from there that I have found as well. 

Should I keep working in ember or let is be as is?

**Comment by nwmac** [comment]
@neillsom just check the pages gather embed in the dashboard - we don't want to spend effort on ember UI in general

**Comment by sowmyav27** [comment]
Reopening to test the pages listed in the original issue's description

**Comment by Auston-Ivison-Suse** [comment]
**Setup for Validation**
- Rancher version 2.6-head (e322f8f)

**Validation Steps**
1. From cluster management press the create button
2. Select ec2 as the instances to be provisioned. 
3. Follow the setup process to get to a point where you see create. (I reproduced the issue in the creation of node template)

**Get Repo Create**
![GitrepoCreate.png](https://zube.io/files/rancher/ec3dd630e1a30e5c94c4cd801be1520a-gitrepocreate.png)

**Create Cluster**
 ![ClusterCreate.png](https://zube.io/files/rancher/39fc7e39951a540fbf3af4e0fcf21af6-clustercreate.png)
