### ISSUE TITLE
Auto-focus input field when editing a global setting

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4197]
Go to Global Setting => Advanced Settings.

Pick a setting and click the 3 dots and 'Edit Setting'.

The value field should automatically get focus.

@rak-phillip Added a directive to do this, so this should be straight forward.

**Comment by rak-phillip** [comment]
The `v-focus` directive currently handles cases for for `LabeledInput`, `LabeledSelect`, and `SelectPriciple`. We might need to add more to support any focusable components as we encounter them.

**Comment by sgapanovich** [comment]
**Test Environment:**
Rancher version: v2.6-head 10dfee4
Rancher cluster type: single-node docker install
Docker version: 20.10

Downstream cluster type: n/a
Downstream K8s version: n/a

====================================

**Test Steps:**
1. go to the Main menu
2. click Global Settings
  * Advanced Settings
3. Pick a setting with an input field (they have string values on UI on the Advanced Settings page)
4. Click on three dots 
5. Click on "Edit Setting"

Confirmed: the input field is focused when the setting page open
![4197.gif](https://zube.io/files/rancher/5abd52c807b84cc104e4a098b702d63c-4197.gif)

additional notes:
adding autofocus didn't change the functionality for updating the fields
