### ISSUE TITLE
[Bug] Bulk entry of agent env vars by copy/pasting results in garbled values

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#4198]
Rancher 2.6.1-RC1

1. Copy the following multi-line string:
```
HTTP_PROXY=http://USERNAME:PASSWORD@10.0.1.1:8080/
HTTPS_PROXY=https://USERNAME:PASSWORD@10.0.0.1:8080/
NO_PROXY=master.hostname.example.com,10.1.0.0/16,172.30.0.0/16
```
2. Navigate to Cluster Manager -> Create RKE2 Cluster (any provider)
3. Scroll to Agent Environment Vars and hover over the info icon next to "variable name" to read the following:
> Past lines of `key=value` pairs for easy bulk entry
4. Paste the content above in the variable name field

**Expected Bevahiour**

Multiline string is correctly parsed into key/value pairs by splitting on the first occurrence of `=` or `:`. 

Reasoning: Key names typically do not contain these delimiter characters, values strings likely do!

**Expected Bevahiour**

Garbled parsing result, because lines are split incorrectly.

<img width="1156" alt="Screenshot 2021-09-17 at 15 54 02" src="https://user-images.githubusercontent.com/3813921/133794401-947835c4-ed53-477e-bca3-2743d42de0c3.png">

**Comment by richard-cox** [comment]
@Sean-McQ Is there a PR related to this that needs to be reviewed?

**Comment by davidnuzik** [comment]
Closing. This is effectively already validated via https://github.com/rancher/dashboard/issues/4196 please reference that issue for validation steps.
