### ISSUE TITLE
[2.6.x| Cloud credential name is not stored/displayed

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#4199]
Rancher version: 2.6.x (1a57856)

**Steps to reproduce:**

1. Create a cloud credential providing a friendly name

**Result**

When listing the credentials a random ID string is shown instead of the user provided name.

This makes it almost impossible to identify the correct credential to use when deploying a cluster with a node driver.

![image (3)](https://user-images.githubusercontent.com/3813921/133774110-a1dbcbfc-c48a-4904-b376-33d620a36c9f.png)

<img width="1672" alt="Screenshot 2021-09-17 at 12 46 40" src="https://user-images.githubusercontent.com/3813921/133771186-a8e4d145-3191-4a58-ab9c-2bc697af9a85.png">

**Comment by anupama2501** [comment]
Verified on v2.6-head adding cloud credentials with a name prefix is showing correct string 
<img width="231" alt="Screen Shot 2021-09-17 at 5 13 56 PM" src="https://user-images.githubusercontent.com/38144301/133865243-32191e82-8859-4c5d-a293-a4473d967432.png">
