### ISSUE TITLE
'Show' button in password boxes should not be in the tab order

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4200]
We have a password control used in a few places, for example, in 'Users & Auth' => Users => Create.

When focused in the New Password field, pressing tab tabs to the show button - it should tab to the next control and the show button should not be in the tab order.

![image](https://user-images.githubusercontent.com/1955897/133796549-8ad997b5-4a65-49d9-9cf5-f57633c62eca.png)

**Comment by jmcsagdc** [comment]
**Reproduced in** v.2.6.0

**Confirmed fix in** v2.6-fe57abd77598577487eb5722aba7bc1eebb50d70-head

1. Place cursor in Password field
2. Hit Tab key

RESULT:

Cursor now lands in the Confirm Password field. The **SHOW** button is skipped.

![2 6 0-head](https://user-images.githubusercontent.com/15971368/134952087-e0370385-4b4a-449f-9aa9-8a420f679e4f.png)
