### ISSUE TITLE
[2.6.x] Adding a node pool to an existing RKE1 cluster fails

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#4201]
Rancher version: 2.6.x (1a57856)

**Steps to reproduce:**

1. Create a RKE1 cluster with a node driver
2. Edit the cluster config by adding an additional node Pool
3. Click save

**Result**

The node pool is not added

**Comment by gaktive** [comment]
There were minimal UI changes in Ember between 2.6.0 and 2.6.x so this may be more backend related. Will check.

**Comment by gaktive** [comment]
@sowmyav27 as I look through the code for recent changes, just to confirm, are you able to add a node pool without the UI?

**Comment by gaktive** [comment]
There's no API call to do this. Also weird is that this isn't working in Ember either. Asking around.
