### ISSUE TITLE
Add the built-in Harvester cloud provider of RKE2 integration

### ISSUE THREAD

**Issue by guangbochen** [rancher/dashboard#4208]
**Is your feature request related to a problem? Please describe.**
Both Harvester CCM & Guest CSI driver should install and configure by default when the user spins up a k8s cluster with the Harvester RKE2 node driver, therefore we will need to add the built-in Harvester cloud provider integration.

**Describe the solution you'd like**
- Rancher Dashboard PR changes: https://github.com/rancher/dashboard/pull/3881

**Comment by guangbochen** [comment]
dashboard WIP PR https://github.com/rancher/dashboard/pull/3881

**Comment by slickwarren** [comment]
on v2.6-head ():
* when using harvester node driver, `harvester` is selected by default for the cloud provider -- pass
  * note: other providers i.e. amazonec2, do not auto-select the cloud provider.  Why are we auto-selecting here? Typically, if we know the node driver has a cloud provider, we filter all options and leave `None, <node driver/cloud provider match>, external` options for the user to choose from, with `None` as the default
* **Reopening for the following issue** custom cluster has the option for `harvester` cloud provider -- fail
  * other cluster types typically list all cloud provider options as well (i.e. digital ocean), but harvester is not listed here either. 
<img width="1527" alt="Screen Shot 2021-09-23 at 8 25 29 AM" src="https://user-images.githubusercontent.com/16691014/134537114-36d9052e-a468-42e2-b6d4-2ccbfa1d562e.png">

**Comment by guangbochen** [comment]
The built-in Harvester cloud provider integration will only work with RKE2 `v1.21.4-rc1+rke2r4` or above, so we have decided to filter it out for non-supported k8s versions, if users want to use this feature they should select the external cloud provider and install related charts manually. This will be documented in the Harvester doc https://docs.harvesterhci.io/v0.3-dev/rancher/node-driver/ later.

**Comment by slickwarren** [comment]
Even after selecting the `v1.21.4-rc1+rke2r4` k8s version in a custom cluster, the `harvester` option does not show. Is there a reason we would not want to show harvester as an option and force user to set it up with the `external` option?

**Comment by guangbochen** [comment]
The `harvester` cloud provider will only work for the Harvester cluster since it requires some infra setup like VIP and harvester-cloud-provider etc., therefore we filter it out from the other generic k8s clusters.

**Comment by slickwarren** [comment]
custom clusters can be from a harvester setup

**Comment by guangbochen** [comment]
yep, but the helm installation mode is only treated as dev mode at the current stage, we don't officially support it, that why we filtered it out, WDUT @yasker

**Comment by gaktive** [comment]
@yasker did you have any more input on what to do here with the view?

**Comment by slickwarren** [comment]
on v2.6-head (06e19b0):
I am unable to provision a load balancer using the harvester cloud provider. LB is stuck in `pending` state with the following  errors:
`Service is ready:Load balancer is being provisioned`
<img width="985" alt="Screen Shot 2021-09-28 at 4 16 29 PM" src="https://user-images.githubusercontent.com/16691014/135178233-62b4a614-bc64-4346-83c3-7ede0b2f512c.png">

**Comment by gaktive** [comment]
@yasker FYI

**Comment by yaocw2020** [comment]
> on v2.6-head (06e19b0): I am unable to provision a load balancer using the harvester cloud provider. LB is stuck in `pending` state with the following errors: `Service is ready:Load balancer is being provisioned` <img alt="Screen Shot 2021-09-28 at 4 16 29 PM" width="985" src="https://user-images.githubusercontent.com/16691014/135178233-62b4a614-bc64-4346-83c3-7ede0b2f512c.png">

Is it convenient for you to provide the support bundle of the Harvester?

**Comment by guangbochen** [comment]
please refer to the https://docs.harvesterhci.io/v0.3-dev/rancher/cloud-provider/#load-balancer-request-parameters to validate the built-in LB support.
annotations with `cloudprovider.harvesterhci.io/ipam` and `cloudprovider.harvesterhci.io/healthcheck-port` are required, thanks.

**Comment by yasker** [comment]
We need `release-note` to point out how to setup the Cloud Provider with Harvester for tech preview.

**Comment by gaktive** [comment]
@yasker if a release note will suffice to get this working, then I can push this ticket to 2.6.2. Let me know if that's not the case since with Neil & Richard out today, then I need someone else to assist.

**Comment by yasker** [comment]
@gaktive I'd like to verify and close this issue as it is (which requires adding annotation manually). We should open another issue for v2.6.2 to enhance the UX for setting up the Harvester cloud provider.

**Comment by gaktive** [comment]
I'll split this ticket.

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/issues/4312 contains the bug found from QA. Passing this back To Test for additional validation.

**Comment by slickwarren** [comment]
on v2.6.1-rc7: 
* harvester cloud provider shows up for harvester rke2 -- pass
* harvester cloud provider does not show up for all other cluster types -- pass
