### ISSUE TITLE
Workload details page UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#421]
Details:
- [x] Ports is different font size then Pods?
![image](https://user-images.githubusercontent.com/11514927/77591385-0d508600-6ead-11ea-9101-b7ad37346b01.png)

- [x] Change all <empty> to inactive "n/a" text?
![image](https://user-images.githubusercontent.com/11514927/77591445-34a75300-6ead-11ea-8e99-887f5311ffb9.png)

- [x] Spacing of top info should be better?
![image](https://user-images.githubusercontent.com/11514927/77591469-41c44200-6ead-11ea-877a-f8f32ae044bd.png)

- [x] In Command tab - should not be able to Add from Resource (button should not be there and active)
![image](https://user-images.githubusercontent.com/11514927/77591543-6ae4d280-6ead-11ea-9e60-16d567f6915b.png)

- [x] Pod menu doesn't do anything?
![image](https://user-images.githubusercontent.com/11514927/77591670-ae3f4100-6ead-11ea-9ae0-0e912656515b.png)

- [x] Checkboxes and Radio buttons are all active and I can click on them to change.

- [x] Networking tab needs design & all null values should show n/a
![image](https://user-images.githubusercontent.com/11514927/77591712-c3b46b00-6ead-11ea-997c-3f6d3bc8967d.png)

- [x] Info bubble should be aligned with top of Label Name (on all tabs & need in create/edit as well)
![image](https://user-images.githubusercontent.com/11514927/77591845-1db53080-6eae-11ea-86d2-7d9819c01f99.png)

- [x] Need consistent look for details (either grey or black?)
![image](https://user-images.githubusercontent.com/11514927/77591921-46d5c100-6eae-11ea-81bd-bd033796477a.png)

**Comment by lvuch** [comment]
The grey radios are disabled

**Comment by tfiduccia** [comment]
@lauren - since it's details, shouldn't all field inputs be grey then?  Also they really aren't disabled.... I can click on them and change the results.

**Comment by lvuch** [comment]
hm i'd see it reverse. instead of showing anything as disabled on detail just show the option that is selected. they should NOT be clickable at all on detail. a dev will have to do that.

**Comment by lvuch** [comment]
@mantis-toboggan-md 
- note comments above regarding radios and labels
- <empty> should be n/a in disabled text

**Comment by tfiduccia** [comment]
Fixed
