### ISSUE TITLE
Cluster name takes some time to display on the UI after creating a cluster, meanwhile it is seen as c-xxxxx 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4210]
**Setup**
- Rancher version: 2.6head commit id: `1a57856 `
- Browser type & version: Chrome

**Describe the bug**
Cluster name takes some time to display on the UI after creating a cluster, meanwhile it is seen as c-xxxxx 

**To Reproduce**
- Deploy a cluster (AKS cluster in this case)
- On creating, the cluster name is seen as below and the provider as Unknown
<img width="1021" alt="Screen Shot 2021-09-18 at 1 07 57 PM" src="https://user-images.githubusercontent.com/26032343/133907320-ac5bcf47-3e25-422e-a170-0689e473a533.png">

- On a refresh of the page, correct clustername is displayed
<img width="1089" alt="Screen Shot 2021-09-18 at 1 08 05 PM" src="https://user-images.githubusercontent.com/26032343/133908480-1f3c2d88-b17a-4693-8031-a5b0c5b8638b.png">

**Comment by nwmac** [comment]
@sowmyav27 Doesn't look like a blocker - so at this stage going to bump to 2.6.2 - any objections?

**Comment by gaktive** [comment]
This was reported as intermittent so it sometimes appears. Sowmya indicated that 2.6.2 was OK

**Comment by catherineluse** [comment]
Since this issue is intermittent, I wonder if it could be caused by Chrome not updating pages properly when self-signed certs are used. See Jason's comment https://github.com/rancher/dashboard/issues/3936#issuecomment-1022772061

**Comment by catherineluse** [comment]
The same behavior happens reliably every time you create a role.

**Comment by nwmac** [comment]
@Shavindra Can you take a look - solution I can see - if the name is not available, I think we're using the ID - if this is the case, we should show a spinner icon next to the ID with a tooltip on the icon saying that the cluster name is not currently available, ID is shown.

I think this can be a simple change to the `ClusterLink` formatter.

**Comment by sowmyav27** [comment]
Reopening since there is no PR linked. @Shavindra can you please link the PR  ?

**Comment by Shavindra** [comment]
@sowmyav27 I cant reproduce this in 2.6.8+ 

![image](https://user-images.githubusercontent.com/1387263/199793934-7aa330f3-7a91-40ee-a730-68ec1eb33908.png)

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision an RKE1 downstream cluster and validate if the correct cluster name is displayed without refreshing|
|2|Repeat scenario 1, but with an RKE2 downstream cluster|
|3|Repeat scenario 1, but with an K3s downstream cluster|
|4|Repeat scenario 1, but with an AKS hosted cluster|

**Comment by markusewalker** [comment]
Validated that I do not see this issue in `v2.7-head` https://github.com/rancher/rancher/commit/a2ef50b5d9519e19df9256685d3f661636da8504.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/a2ef50b5d9519e19df9256685d3f661636da8504
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision an RKE1 downstream cluster and validate if the correct cluster name is displayed without refreshing|:white_check_mark:|
|2|Repeat scenario 1, but with an RKE2 downstream cluster|:white_check_mark:|
|3|Repeat scenario 1, but with an K3s downstream cluster|:white_check_mark:|
|4|Repeat scenario 1, but with an AKS hosted cluster|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigated to Cluster Management.
3. Provisioned a downstream RKE1 cluster; validated that the correct cluster name is displayed without having to refresh the UI:
![image](https://user-images.githubusercontent.com/52591819/207948934-da8efc0d-eb1d-4945-ab94-6137280b68c4.png)
4. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
______
**Scenario 2**
1. Repeated scenario 1, but used a downstream RKE2 cluster instead:
![image](https://user-images.githubusercontent.com/52591819/207948899-5fbca830-d796-4d92-8618-c3d98def5d4a.png)
________
**Scenario 3**
1. Repeated scenario 1, but used a downstream K3s cluster instead:
![image](https://user-images.githubusercontent.com/52591819/207948865-bec919cd-85f0-45ae-a854-6fe4f2887e58.png) 
_________
**Scenario 4**
1. Repeated scenario 1, but used a hosted AKS cluster instead:
![image](https://user-images.githubusercontent.com/52591819/207948809-88cff682-ac2a-4634-8a61-d53ef61d78ca.png)
