### ISSUE TITLE
Unable to edit cluster members after cluster creation

### ISSUE THREAD

**Issue by cmurphy** [rancher/dashboard#4211]
**Setup**
- Rancher version: 2.6-head
- Browser type & version:

**Describe the bug**

After a cluster is created, the cluster members cannot be changed. Attempting to add or remove cluster members will seem to succeed, but visiting the cluster config again will show that the cluster member list has not changed.

**To Reproduce**

1. Create or import any cluster.
2. Go to edit the cluster config.
3. Click Member Roles -> Add Member and search for another user and role.
4. Click save.
5. Go to edit the cluster config again, click to show Member roles, see the new user is not in the list.

**Result**

**Expected Result**

Adding a user to a cluster should create a clusterroletemplatebinding and persist.

**Screenshots**

The developer console shows that a POST request to /v3/clusterroletemplatebindings is missing.

Requests made now:
![Screenshot_20210919_165745](https://user-images.githubusercontent.com/1220710/133947184-109d2586-f799-4498-b832-136ee0363b4b.png)

Requests made when it's working - includes POST request to v3/clusterroletemplatebinding:

![Screenshot_20210919_170256](https://user-images.githubusercontent.com/1220710/133947270-6f3d0428-3011-484b-81d4-af283f931200.png)

**Additional context**

Switching the ui-index setting to https://releases.rancher.com/ui/2.6.1-rc1/index.html shows the bug was introduced between release v2.6.1-rc1 of rancher/ui (not rancher/dashboard) and latest.

**Comment by cmurphy** [comment]
I can't edit milestones or labels, @gaktive can you get this prioritized - it's a regression since 2.6.0 so I think it should be high priority.

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/issues/4201 had a similar issue there.

**Comment by cmurphy** [comment]
@gaktive it's for any cluster, not just RKE1.

**Comment by gaktive** [comment]
@richard-cox if you can't make headway on this today, let me know if you can't find another UI person to tackle this once your day ends.

**Comment by richard-cox** [comment]
I couldn't reproduce this on my dev machine with DO RKE1 or DO RKE2 created from a previous session

@cmurphy There was a change that went in earlier (UK) today that might have fixed this for the RKE1 (embedded ember) world, I don't think there were any related to RKE2 (native dashboard) clusters though. 
- Is the user a `local` one or from an auth provider?
- Are the clusters created in the same session?
- What version is stated in the side panel / about page (I'm running on a slightly old 2.6-head)?
- Are there any errors in the browser's dev console?

**Comment by cmurphy** [comment]
The problem has gone away as of this morning so I guess the RKE1 change fixed it.

**Comment by gaktive** [comment]
Passing to QA to put on their radar, just in case it does resurface.

**Comment by ronhorton** [comment]
pass - verified in v2.6-ba4347297ef8984f629650979a1b3a470592f4da-head
tested aws & do clusters.
I wasn't able to reproduce the issue in 2.6.0 or 2.6-head.
