### ISSUE TITLE
Red color for provisioning an RKE1 cluster

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4213]
**Setup**
- Rancher version: 2.6.1-rc1 (not relevant)
- Browser type & version: Firefox 78.13.0esr (64-bit)

**Describe the bug**

When provisioning an RKE1 downstream cluster from Rancher UI, the status for provisioning
is red even if there does not seem to be any errors. 

**To Reproduce**

Cluster Management -> Create -> Custom (RKE1) -> ... 
Go back to Clusters view.
While provisioning, the state and message are in red.

**Result**
Works as intended.

**Expected Result**

Blue state and message.

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

It looks like an error situation.

It would look "normal".

**Comment by richard-cox** [comment]
No longer reproducible. 

![image](https://github.com/rancher/dashboard/assets/18697775/fdf32ca1-c44b-4817-b5aa-05f8c22f4449)

**Comment by IsaSih** [comment]
Test pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head

![Image](https://github.com/rancher/dashboard/assets/70187881/38ed1f65-6506-4ea3-aa2c-fc9dac4cb29e)
