### ISSUE TITLE
Improve UI appearance on mobile/tablet devices

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4215]
First round of low-hanging fruit to improve responsive design.

Goal is that the login, home and key views are viewable on mobile/tablet.

**Comment by gaktive** [comment]
This was reopened after a nav breakage that had to reverted.

**Comment by Leen15** [comment]
Any update on this?
It's unusable on an iphone and it's the main reason we are still with v.2.5.* 😕

![image](https://user-images.githubusercontent.com/3629071/170468725-c43bd9e1-e458-48b8-be83-bca008639cd3.png)

**Comment by gaktive** [comment]
We'll need @kwwii to help with reviewing the design we're looking at here since the original work is old.

**Comment by Leen15** [comment]
> The layout at tablet-size seems to work fine, but the smallest sizes (on phones and such) have problems with the menu(s) and breakpoints.
> 
> This requires a rethink of the layout/breakpoints and menu structure of the entire Rancher application. Even the login page is broken at very small sizes.
> 
> I am not sure that there is a direct mandate to make this work at all sizes. It would result in a very large amount of structural, functional, and theme changes (not to mention planning and testing changes going forward).
> 
> This needs clarification.

What it's not clear for me is that if the previous version (2.5) works PERFECTLY on mobile, and it's no more maintained with new features in favour of the new version (2.6), why this miss an important feature like the mobile support?
If you try to use the version 2.5 on an iphone you can see that almost everything is usable.

**Comment by kwwii** [comment]
While testing the upcoming menu changes we should review the UI to find places where things break.

**Comment by kwwii** [comment]
THe logout page is of particular interest

**Comment by rak-phillip** [comment]
Posting some more examples for future discussions. I think we'll have to split this out into multiple focus areas. 

## Vertical scrollbar offset with constrained width

https://github.com/rancher/dashboard/assets/835961/e8b38e10-dcee-4a1c-938f-50aa8e45229a

## Compressed checkboxes and overlapping input labels

![image](https://github.com/rancher/dashboard/assets/835961/113b722f-9a5e-4698-89b3-5811ddea3c8a)
