### ISSUE TITLE
Have a way to see the exact Dashboard UI version / commit hash in Rancher

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4217]
**Detailed Description**
Provide a way to see the exact Dashboard UI version / commit hash - either on UI or somewhere on payload where it can be viewed in browser's Dev Tools.

**Context**

This is helpful when validating issues or using Rancher in development to know exactly what UI commit is used to be sure that expected changes are included or not when it's may be not immediately clear when looking at the UI (case in point - the discussion here https://github.com/rancher/dashboard/issues/3995#issuecomment-922369495).

**UPDATE: As per indication from UX/UI team, the link on the bottom-right of the side menu featuring the backend version is to be replaced by link to the same about page but with the text "About".**

To test:
- test in a `-head` build that the dashboard version shown on the about page is of the format `"${COMMIT_BRANCH} ${COMMIT}"`
- test tagged (i.e. release candidate) build build that the dashboard version shown on the about page is the git version tag

**Comment by catherineluse** [comment]
Can this be in v2.6.6?

**Comment by nwmac** [comment]
We now have this from the /rancherversion endpoint.

Should add this to the About page

**Comment by richard-cox** [comment]
We have version information at build time via the `scripts/version` script
```
COMMIT=$(git rev-parse --short HEAD)
COMMIT_DATE=$(git --no-pager log -1 --format='%ct')
COMMIT_BRANCH=$(git rev-parse --abbrev-ref HEAD | sed -E 's/[^a-zA-Z0-9.-]+/-/g')
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}
LAST_TAG=${GIT_TAG:-'v0.0.0'}
```

This is used in our two build scripts
build-embedded
build-hosted

**Comment by kwwii** [comment]
As agreed in chat, we should change the current backend commit hash in the left app menu to "About", and on the About which which it already links to add "UI" to the Versions table with the commit

**Comment by aalves08** [comment]
Thanks for the issue update @kwwii 🙇

**Comment by anupama2501** [comment]
Verified on v2.7.2-rc7 and v2.7-head `2b2ed44` 

`v2.7.2-rc7
`In the about page, the commit ID of dashboard is listed:
<img width="400" alt="2023-03-24_14-19-29" src="https://user-images.githubusercontent.com/38144301/227643642-e94ec703-48a2-47ce-86f3-a7f18f285688.png">

`v2.7-head`
<img width="400" alt="2023-03-24_14-19-03" src="https://user-images.githubusercontent.com/38144301/227643654-ad8a8ee0-04b7-45d5-8bd4-d94454f37134.png">
