### ISSUE TITLE
Add Worker Counts by OS

### ISSUE THREAD

**Issue by luthermonson** [rancher/dashboard#4223]
**Is your feature request related to a problem? Please describe.**
We need to add counts for worker nodes by os so we can show the proper charts in the apps/marketplace in the ui

**Describe the solution you'd like**
will add a status of workers.linux and workers.windows with int counts for each. that will bubble up to the UI and then the math can be done to determine the ratio of windows nodes. if we feel the cluster can support windows charts based on the ratio they can then display them

**Additional context**
the ui today shows linux only charts to windows clusters which won't deploy, this will help us cleanup the windows experience.

**Comment by gaktive** [comment]
@luthermonson do you have an example chart that would be Windows only? and do you have an environment that UI can test against?

**Comment by gaktive** [comment]
Sample app to test with: monitoring & logging. Per Luther, it works today with RKE1 so we can try that out (RK2 in progress).

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: 2.6.3-rc3
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: 5 nodes windows cluster (3 etcd/cp linux nodes, 1 linux worker, 1 windows worker)

----------

### Testing: ###

Navigate to Apps&Marketplace -> Charts

Per @codyrancher comments in the PR https://github.com/rancher/dashboard/pull/4639
```
The options will show if there is at least 1 linux and windows worker node.
The option will be defaulted to the OS with the most worker nodes or to All OSs if there are equal nodes.
```
I don't see the dropdown even having a cluster with 1 linux /1 windows nodes
![no dropdown](https://user-images.githubusercontent.com/40282141/144463084-0bebf295-52c3-4a71-84d0-f0036fc21175.jpg)

Re-opening the issue

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: 2.6-head 46eb9d4
Rancher cluster type:  HA
Docker version: 20.10

Downstream cluster type: Custom windows (3 etcd/cp, and different amount of linux and windows nodes)

----------

### Testing: ###
In the main side menu navigate to "Apps&Marketplace"
- If a windows cluster has no windows nodes registered 
  - there is no "OS" drop down
  - same for just linux clusters
![10](https://user-images.githubusercontent.com/40282141/144525796-238bcd44-0d49-49aa-8b38-658c4ac27083.jpg)

- if a windows cluster has at least one linux worker and one windows worker nodes
  - there is the "OS" drop down present 
  - defaults to "All OSs"
  - ![11](https://user-images.githubusercontent.com/40282141/144525992-76176332-c11b-4d34-b9f5-35bc5dca08a0.jpg)

- if a windows cluster has more linux worker nodes than windows worker nodes (2 vs 1 in this example)
  - there is the "OS" drop down present 
  - defaults to "Linux"
  - ![21](https://user-images.githubusercontent.com/40282141/144526062-ccbd2b19-80a4-49e1-ab2f-535ab0e763dc.jpg)

- if a windows cluster has more windows worker nodes than linux worker nodes (3 vs 2 in this example)
  - there is the "OS" drop down present 
  - defaults to "Windows"
  - ![23](https://user-images.githubusercontent.com/40282141/144526116-9eb4a832-19c5-4bbd-94db-e264552b7356.jpg)

The OS dropdown shows correct number of charts per OS
![correct numbers](https://user-images.githubusercontent.com/40282141/144526229-163e3fd3-e643-4a69-b7c6-1b230c2d07b8.jpg)

UI shows charts based on responses from `GET /v1/catalog.cattle.io.clusterrepos/rancher-charts` and `GET /v1/catalog.cattle.io.clusterrepos/rancher-partner-charts`:
- there is a `catalog.cattle.io/os` parameter in responses:
  - if the parameter has a value (windows or linux) 
    - that chart will be shown only for the corresponding OS selected
    - windows example:
    - ![windows](https://user-images.githubusercontent.com/40282141/144526895-5ad6fe54-6f2f-4120-af36-fe0a0b1a2cde.jpg)
    - linux example:
    - ![linux](https://user-images.githubusercontent.com/40282141/144527217-092ad781-2976-4738-b538-c3e9bd440ce3.jpg)
  - if no parameter is returned 
    - the chart will be shown for both OS

Installing an app was not affected (tested on rancher-wins-upgrader and monitoring -> both installed with no issues)
