### ISSUE TITLE
[Continuous Delivery] "Assign To" button unavailable for migrating Fleet clusters to another 

### ISSUE THREAD

**Issue by nickgerace** [rancher/dashboard#4224]
**Setup**
- Rancher version: v2.6-head (`rancher/rancher`: 7e7db270d9ac87355d063638929fd712c6616b72)
- Browser type & version: Chrome Stable 93.0.4577.82

**Describe the bug**
In the Continuous Delivery UI, the "Assign To" button no longer exists for moving Fleet clusters to new workspaces.

**To Reproduce**
1. Create local and downstream Rancher cluster
2. Create `FleetWorkspace`
3. Navigate to `Clusters` in Continuous Delivery
4. See that "Assign To" button no longer exists when selecting clusters

**Result**
The button does not exist.

**Expected Result**
The button exists.

**Screenshots**

![Screen Shot 2021-09-20 at 6 23 43 PM](https://user-images.githubusercontent.com/39320683/134083841-1ee395cf-d48f-4440-b044-4afb5931d8ff.png)

**Additional context**
n/a

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `ba43472`**

Assign To is available
<img width="1085" alt="Screen Shot 2021-09-21 at 9 24 58 AM" src="https://user-images.githubusercontent.com/26032343/134209525-dd8d3b2e-ef0c-4afd-a063-3e14a66aaff7.png">
