### ISSUE TITLE
Workload labels and annotations are not saved

### ISSUE THREAD

**Issue by sgapanovich** [rancher/dashboard#4226]
**Setup**
- Rancher version: v2.6-ba4347297ef8984f629650979a1b3a470592f4da-head
- Browser type & version: Google Chrome Version 93.0.4577.82 (Official Build) (x86_64)

**Describe the bug**

When adding labels or annotations to a workload (tested with daemonset and deployment) labels and annotations are not sent by UI 

**To Reproduce**
Reproduced on a downstream ec2 cluster
1. Hamburger menu
2. Select your test cluster
3. click on "Workload" (left menu panel)
4. click on "Deployments"
5.  click "Create"
6. Provide with a name and Image to pull
7. Vertical tab to select "Labels & Annotations"
8. Add labels and annotations for the deployment and pod
9. Open devtools to confirm the Request Payload 
10. click "Create"

**Result**
Only Pods labels and annotations passed

**Expected Result**

The workload is created with labels and annotations passed by a user 

**Screenshots**

![labels](https://user-images.githubusercontent.com/40282141/134091127-117072b4-90db-4096-8b84-cb7b9af30244.png)
 other context about the problem here.—>

**Comment by nwmac** [comment]
@sgapanovich The UI does not allow this at present - we need to redesign the UX for deployments, so this will have to wait until 2.6.2

**Comment by sgapanovich** [comment]
@nwmac the UI does allow it in v2.6
![2 6](https://user-images.githubusercontent.com/40282141/134182008-ef701213-7f7b-4b16-a5e4-5cded6bf2af9.png)
.6

**Comment by nwmac** [comment]
@mantis-toboggan-md says there is an issue - we'll look into this.

**Comment by sgapanovich** [comment]
Test environment:
- Rancher version: v2.6-223ec88b70d87cecee8fdbe8d98e30cf004b25d9-head
- Single node install with a provisioned downstream rke ec2 cluster
- Browser version: Google Chrome Version 93.0.4577.82 (Official Build) (x86_64)

==================================================================

created a workload:deployment 
added a label and annotation 
- both are passed by UI
- both saved 
  * `describe deploy` returned passed labels and annotations 
  * `--show-labels` returned correct labels
  * `get deploy -l key=value` returned the deployment 


![labels.png](https://zube.io/files/rancher/63fc833bf31a814a39e091ced96dfb30-labels.png)


the following steps were done via UI:
able to edit existing labels and annotations
able to add labels and annotations to an existing deployment 
able to remove labels and annotations from an existing deployment
able to add/edit/remove labels and annotations for a different workload (daemonset)
able to add/edit/remove labels and annotations in the local cluster as well
