### ISSUE TITLE
Forward port feature to see difference when rolling back a workload

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#4229]
When working on forward porting the feature to roll back a workload https://github.com/rancher/dashboard/pull/4178, I tried to also add the diff shown when you roll back a workload in Ember:

![Screen Shot 2021-09-16 at 11 20 47 PM](https://user-images.githubusercontent.com/20599230/134104075-e431b4ea-a99f-4676-9700-b962b4ccbe74.png)

I found that in Ember, it looks like an Ember-specific function `get` is used to clean the data before the two revisions are compared. https://github.com/rancher/ui/blob/master/app/components/modal-rollback-service/component.js#L115

I didn't have enough time to create the diff in Vue, so opened this issue to track the diff portion separately.

@gaktive

**Comment by vincent99** [comment]
`get` is just the way you access child properties of an object in ember.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id `4375161`**
- Diff in VUE
<img width="1422" alt="Screen Shot 2021-11-27 at 6 59 19 PM" src="https://user-images.githubusercontent.com/26032343/143727163-26142a54-c841-4e26-9c5d-1135b8146381.png">

- Diff in EMber
<img width="997" alt="Screen Shot 2021-11-27 at 7 00 38 PM" src="https://user-images.githubusercontent.com/26032343/143727180-5e7fdb21-0cd5-4a44-a73b-8b471687f4eb.png">

@catherineluse Is this expected?

**Comment by catherineluse** [comment]
@sowmyav27 Neill added the ability to see the diff view. Right now it is showing more differences than the Ember UI does. It would take some more work to filter out the less important differences, and that work is being tracked in https://github.com/rancher/dashboard/issues/4636.

**Comment by sowmyav27** [comment]
Closing this as a separate GH issue is logged to track improvements.
