### ISSUE TITLE
Design update for deployment screen

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4231]
Editing a deployment is confusing since there are three levels of entity -> Deployment, Pod and Container - the UI does not allow labels and annotations at the deployment level to be changed and is confusing to understand which entity the side tabs refer to.

We need to look to redesign the UX for deployments.

Also, we render controls in a view mode for non-edit case and these aren't great - we use a disabled presentation and we sometimes show buttons (e.g. Remove) which relate to the edit case, so should not be shown.

**Comment by gaktive** [comment]
This will help fix what we're seeing with fields appearing in places that we could find more easily.

**Comment by lvuch** [comment]
this is the doc that I will be updating: https://xd.adobe.com/view/3a0ff278-5d42-4f38-82fe-647fe3472cc7-6f5c/

**Comment by richard-cox** [comment]
@nwmac @lvuch Given that this is still at the design review stage this isn't going to be completed for 2.6.3. There is a growing count in the community that are interested in an improved workload view, it would be good to get this in to 2.6.4?

**Comment by gaktive** [comment]
I'm OK to push this out to 2.6.4, especially since QA already has a lot on their plate for 2.6.3 testing. I'll defer to @nwmac since he's the main driver for this workflow improvement.

**Comment by MKlimuszka** [comment]
What's the status of this issue? It's assigned to Team 3, but it looks like a UI issue. I'm confused.

**Comment by nwmac** [comment]
It is a design issue / I've. P idea why it's been assigned to tram 3 to review

**Comment by gaktive** [comment]
@lvuch will provided a wireframe
