### ISSUE TITLE
Provisioning via local cluster explorer throw error for RKE clusters 

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#4236]
**Setup**
- Rancher version: 2.6.0/2.6.1
- Browser type & version: Firefox 92.0/Chrome 93.0.4577.63

**Describe the bug**
Navigating to an existing RKE cluster through cluster provisioning produces several issues

1. Cluster name is not human readable

   ![image](https://user-images.githubusercontent.com/835961/134216898-7ca45bef-bd5c-4816-a1aa-d4458384bdf6.png)

2. An error is displayed

   ```
    { "message": "Failed while: set provisioner", "statusCode": 500 } 
   ```

**To Reproduce**
1. Create an RKE cluster and wait for it to enter an active state (Digital Ocean was used as a provider)
2. Navigate to Explore Cluster => local => Cluster Provisioning
3. Select the RKE cluster created in step 1

**Result**
The RKE cluster renders with an error message, an ID in place of a common name, and missing Machine Pools and Snapshot tabs: 

   ![image](https://user-images.githubusercontent.com/835961/134217407-6541d6f1-69fb-4211-baf6-c3cea0a239eb.png)

**Expected Result**
The RKE cluster renders just as it would if we navigated to it via Cluster Management:

   ![image](https://user-images.githubusercontent.com/835961/134217578-804a5228-3ac1-4f8c-8108-d2eacb56fbbb.png)

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.6.2                                  |
| Rancher cluster type    | Single Node Docker Install              |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu1~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | RKE Digital Ocean                       |
| Downstream K8s version  | v1.21.6-rancher1-1                      |
| Browser type            | Google Chrome                           |
| Browser version         | 95.0.4638.69 (Official Build) (x86_64)  |

## Reproduction steps

1. Have a cluster created as described in the reproduction environment table above
2. Starting from the **default** Rancher homepage `/dashboard/home`
3. Click `hamburger menu` -> `local` -> `More Resources` -> `Cluster Provisioning`
4. You will see the cluster you created with the name you gave it
5. Click that clusters name, in this example the cluster is named `checks`

https://user-images.githubusercontent.com/40877149/140394399-0183a280-6715-4e21-a606-f71d5e26680f.mov

6. After clicking the cluster name, you will see the following issues
    1. The cluster is named by ID, and not its name
    2. There is an error message
    3. There are two missing tabs
        1. Machine Pools
        2. Snapshots

<hr>

## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-931a0f09d0f85ade0dcaa8fbe9d6e0c58ae52bbc-head |
| Rancher cluster type    | Single Node Docker Install                         |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu1~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | RKE Linode                                         |
| Downstream K8s version  | v1.21.5-rancher1-1                                 |
| Browser type            | Google Chrome                                      |
| Browser version         | 95.0.4638.69 (Official Build) (x86_64)             |

## Validation steps

1. Starting from the **default* Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> `local` -> `More Resources` -> `Cluster Provisioning`
3. Click the `Name` of the cluster -> observe the page
4. The issue has been fixed. The cluster name is now displayed, and the missing tabs are available
