### ISSUE TITLE
[rke2 templates] Question.yaml Support for secrets, pvc, configmap for non-admin users

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4239]
**Describe the bug**

non-admin users do not have permission to access the resource(s) for types secret, pvc, configmap, etc. when creating an rke2 cluster via templates

**To Reproduce**

* login as non-admin user (restricted admin)
* add an rke2 template using type `secret` for cloudcredential
* create a secret for cloudCredential
* use the template to create a cluster

**Result**
the UI cannot find the resources:

<img width="784" alt="Screen Shot 2021-09-21 at 11 46 20 AM" src="https://user-images.githubusercontent.com/16691014/134252159-db826c97-c0ba-46b3-bdec-a6467f9c6253.png">

**Expected Result**

non-admin users should be able to use RKE2 templates when questions.yaml contains non-string types for secrets.

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

non-admin users should be able to use RKE2 templates when questions.yaml contains non-string types for secrets.
Currently, non-admin users can't  use templates with these types.

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/issues/1097#issuecomment-924421111

**Comment by vincent99** [comment]
Yes?  You do indeed not have access to them in the target cluster (which is `local`) as a restricted admin.
