### ISSUE TITLE
Add Operating System to Machine Pools table in Cluster Manager

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#4240]
**Requirements**
Add OS field to list of Machine Pools in Cluster Manager 

**Details**
Given an RKE2 cluster, we get a list of machines that implement `cluster.x-k8s.ui.machine`. Each machine has a reference to a node via `status.nodeRef`, but we aren't able to reliable lookup info for a cluster that isn't selected in Rancher Dashboard.

This implementation detail originated in rancher/dashboard#3222

**Comment by richard-cox** [comment]
The Machine Pools table show two different types (for non-RKE2 and RKE2 cluster types), we can do this with one but the other is problematic. See https://github.com/rancher/dashboard/pull/4206#pullrequestreview-758387557 and https://github.com/rancher/dashboard/pull/4206#discussion_r712912154

**Comment by richard-cox** [comment]
Should be tested together with #3222

**Comment by sgapanovich** [comment]
Test environment:
rancher: v2.6-fe57abd77598577487eb5722aba7bc1eebb50d70-head

=======================================================

Cluster Management => Cluster => Machines / Machine Pools (tab)
- OS field is added to the Machine Pools table for 
  - non-RKE2 (RKE) Provisioned EC2 cluster
  - non-RKE2 (RKE) Custom Ccuster
  - RKE2 (RKE) Provisioned EC2 cluster
  - RKE2 Custom cluster

![machines rke.png](https://zube.io/files/rancher/8e68bba9fa1c7f649ac39e8c033dc00f-machines-rke.png)
