### ISSUE TITLE
{"data":"write tcp 172.17.0.2:443->xxx.xxx.xxx.xxx:5339: i/o timeout"}

### ISSUE THREAD

**Issue by wuwo1952368901** [rancher/dashboard#4243]
{"log":"E0917 04:40:08.110919      32 upgradeaware.go:401] Error proxying data from backend to client: write tcp 172.17.0.2:443-> xxx.xxx.xxx.xx:61247: write: connection timed out\n","stream":"stderr","time":"2021-09-17T04:40:08.111070168Z"}

**Comment by richard-cox** [comment]
Please fill in the issue template when creating issues in this repo
