### ISSUE TITLE
Experimental label required in OPA gatekeeper page in Dashboard

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#425]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster and navigate to dashboard.
2. Go to OPA Gatekeeper page.

**Expectation.**
Experimental label should appear on the page as this is an experimental feature for release v2.4.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2559-head- 02956b782
- Installation option (single install/HA): Single

**Comment by lvuch** [comment]
<img width="857" alt="Screen Shot 2020-03-26 at 11 54 17 AM" src="https://user-images.githubusercontent.com/3013118/77685608-eb144200-6f58-11ea-8867-5a8c38ea63a7.png">
![Screen-Shot-2020-03-26-at-11 54 17-AM](https://user-images.githubusercontent.com/3013118/77685616-ecde0580-6f58-11ea-9101-c73a51e5bea5.png)

**Comment by lvuch** [comment]
<img width="857" alt="Screen Shot 2020-03-26 at 11 54 17 AM" src="https://user-images.githubusercontent.com/3013118/77685644-f8c9c780-6f58-11ea-8d4b-fbc10b46768d.png">
![Screen-Shot-2020-03-26-at-11 54 17-AM](https://user-images.githubusercontent.com/3013118/77685652-fbc4b800-6f58-11ea-89c4-dd6ff7e9ad33.png)

**Comment by lvuch** [comment]
![Screen-Shot-2020-03-26-at-11 54 17-AM](https://user-images.githubusercontent.com/3013118/77685681-0b440100-6f59-11ea-80ae-07a72688850b.png)
<img width="857" alt="Screen Shot 2020-03-26 at 11 54 17 AM" src="https://user-images.githubusercontent.com/3013118/77685686-0c752e00-6f59-11ea-9327-e196bdc2b717.png">

**Comment by westlywright** [comment]
I prefer option 1, it doesn't seem as generic as the second option. Option 2 looks too much like a button imo.

**Comment by lvuch** [comment]
That makes sense. here is a third option, but I think this one is hard to read in the given space.
<img width="768" alt="Screen Shot 2020-03-26 at 12 10 28 PM" src="https://user-images.githubusercontent.com/3013118/77686932-e8b2e780-6f5a-11ea-91cf-5f2289b8a8d3.png">

**Comment by westlywright** [comment]
I do like the third one more. That would be my vote.

**Comment by vincent99** [comment]
I like the first one (flag) and not at all the third.. it stands out, but not in a good way, hard to read, and only fits a fixed-size word so you can't reuse that for something else later.

**Comment by khushboo-rancher** [comment]
Experimental label is available in latest dashboard UI.
<img width="528" alt="Screen Shot 2020-03-30 at 5 42 07 PM" src="https://user-images.githubusercontent.com/60111667/77976535-1dec6c00-72b2-11ea-894d-12704654088f.png">
