### ISSUE TITLE
[Fleet] Harvester cluster resources are still included in fleet

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4250]
**Setup**
- Rancher version: v2.6-head(223ec88)
- Browser type & version:chrome

**Describe the bug**

  * fleet counts harvester clusters in total cluster count, but does not display the harvester cluster in the list of clusters
  * <img width="1316" alt="Screen Shot 2021-09-22 at 1 29 01 PM" src="https://user-images.githubusercontent.com/16691014/134417046-4da73abd-bd93-4f60-9976-5267337a0e59.png">
  * fleet includes harvester cluster resources 
    * `bundles` and `ClusterRegistrationTokens` are showing for harvester clusters
    * <img width="1104" alt="Screen Shot 2021-09-22 at 1 14 58 PM" src="https://user-images.githubusercontent.com/16691014/134415425-5b4ec4ee-77b3-40c9-8f9a-bd60ef5abcc4.png">

**To Reproduce**
* add the harvester cluster via virtualization management
* navigate to fleet, and view the pages mentioned above

**Expected Result**
for fleet, we should either hide all harvester resources, or include them all. Currently, some information seems cherry-picked from the users view. 

related to : https://github.com/rancher/dashboard/issues/3467

**Comment by slickwarren** [comment]
on v2.6-head (0dd1ce6):
* banner is added letting user know that harvester clusters are not shown on cluster page -- pass
* cluster registration tokens page do not show harvester tokens -- pass

**reopening for the following issue:** 
* bundles are still showing harvester resources, and do not have a banner

<img width="1776" alt="Screen Shot 2021-09-26 at 8 05 14 PM" src="https://user-images.githubusercontent.com/16691014/134839712-86daf056-8d33-4694-92e1-f6462c401804.png">

(this might require a new ticket): 
fleet `deploy to` option under `git repos` still include harvester clusters. I will follow up and see if this expected, but I expect it is not. 
<img width="787" alt="Screen Shot 2021-09-26 at 8 08 21 PM" src="https://user-images.githubusercontent.com/16691014/134839966-5b557923-b77d-4b61-88cd-7cfbc221a47c.png">

**Comment by slickwarren** [comment]
on 2.6-head (06e19b0):
* user can no longer select the harvester cluster from the dropdown when deploying a fleet repo -- pass


<img width="806" alt="Screen Shot 2021-09-28 at 9 27 50 AM" src="https://user-images.githubusercontent.com/16691014/135127869-7d8a9dd5-0f42-473e-868b-8f11ea57d5de.png">

* **however**, if user selects `all clusters in the workspace`, fleet still deploys to the harvester cluster

<img width="911" alt="Screen Shot 2021-09-28 at 9 27 34 AM" src="https://user-images.githubusercontent.com/16691014/135127852-f94b96cd-d1b2-44e4-a69d-930c4e852843.png">

Is this something that can be fixed through the dashboard? I can file a new ticket if necessary.

**Comment by nwmac** [comment]
@slickwarren The deploy to all clusters would be better done in the backend

**Comment by nwmac** [comment]
@slickwarren I created https://github.com/rancher/rancher/issues/34954 for the backend team to take a look - moving this back to test - I think the UI issues are done.

**Comment by slickwarren** [comment]
closing in favor of the above backend ticket -- all UI issues here have been covered
