### ISSUE TITLE
Layouts for  itstio, monitoring, Opa

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#426]
- [ ] itstio, monitoring, Opa layout
    - [ ] background copy
    - [ ] system requirements
    - [ ] enable (muted if they don’ have enough) or customize

**Comment by lvuch** [comment]
![tool configuration](https://user-images.githubusercontent.com/3013118/77704851-553dde80-6f7b-11ea-90d4-1fff9e9215d6.png)

@tfiduccia here's a wip, please review

**Comment by lvuch** [comment]
https://xd.adobe.com/view/f68d1b97-c7de-4e4d-478c-d61d80342316-80bc/

**Comment by tfiduccia** [comment]
OPA main page fixed and approved.  When doing design for Monitoring & Istio we should follow same format.
