### ISSUE TITLE
Default nodepool's k8s version on an AKS v2 cluster is 1.19.9

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4262]
**Setup**
- Rancher version: 2.6.1-rc2
- Browser type & version: Chrome

**Describe the bug**
Default nodepool's k8s version on an AKS v2 cluster is 1.19.9

**To Reproduce**

- Create an AKS v2 cluster
- with default values from UI
- Cluster k8s is selected as 1.21.2
- But the nodepool's k8s is seen as `1.19.9`.
- When you save the cluster, the cluster errors out as `1.19.9` k8s is not valid.

**Expected Result**
The nodepool's default k8s should match cluster k8s version

**Comment by nwmac** [comment]
@vincent99 Can you take a look, please?

**Comment by gaktive** [comment]
@rak-phillip to repro this first then sync up with Vince.

**Comment by rak-phillip** [comment]
I see this happening when creating a cluster through Cluster Management => Create => Azure AKS. There are three steps in creating the cluster:

1. Select cloud credentials
2. Select cluster location
3. Configure cluster (this is where the error is)

Under cluster  options, Kubernetes Version defaults to 1.21.2; further down the page, node pools defaults to Kubernetes Version 1.19.9.

Making a new selection successfully updates the kubernetes version for both Cluster Options and Node Pools. 

This is in the Ember UI.

@vincent99
