### ISSUE TITLE
Cluster members page is broken after adding a cluster member

### ISSUE THREAD

**Issue by gitlawr** [rancher/dashboard#4263]
**Setup**
- Rancher version: v2.6-223ec88b70d87cecee8fdbe8d98e30cf004b25d9-head

**Describe the bug**
![image](https://user-images.githubusercontent.com/5697937/134462544-6747c8d0-fb22-47c1-a2aa-7ca8231c71ca.png)

**To Reproduce**
1. Install rancher v2.6-head using docker
2. Provision a rke2 cluster
2. Create users test1,test2 as standard users
3. Log in as test1, import the rke2 cluster to Rancher
4. as test1 user, go to the rke2 cluster explorer -> RBAC->Cluster Members page. Add test2 user to be a cluster member.

**Result**
The UI fails to load the cluster member page.

**Comment by Auston-Ivison-Suse** [comment]
**Validated** on commit fe57abd

I was able to add a standard user following the reproduce steps, without the cluster members not loading. 

Screenshot: 
![Screen Shot 2021-09-28 at 4.00.53 PM.png](https://zube.io/files/rancher/4fc4a153636ef2e6d02c841bb3f26537-screen-shot-2021-09-28-at-4-00-53-pm.png)
