### ISSUE TITLE
Bring back the option to copy the kubeconfig

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#4270]
**Detailed Description**
In the old UI you were able to copy a cluster's kubeconfig to your clipboard.  In the new dashboard the only option seems to be to download it without selecting a destination. I would like a way to have a cluster's kubeconfig copied to my clipboard rather than downloaded.

**Context**
Often times I want the kubeconfig to go to a  particular location and it can be a pain to download it, open the file, copy it and then paste it where I need it.  This is especially true on WSL or a vm when the downloads folder is not easily accessible.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `437516`**

Copy Kubeconfig to clipboard option is available

<img width="1676" alt="Screen Shot 2021-11-27 at 6 18 05 PM" src="https://user-images.githubusercontent.com/26032343/143726321-d556e2d7-ecbb-4e35-8e05-7c09ed950729.png">
