### ISSUE TITLE
[virtualization management] clusters provisioned via harvester node driver are showing up in the virtualization management list

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4273]
**Setup**
- Rancher version:v2.6-head (223ec88)
- Browser type & version: chrome

**Describe the bug**

sometimes, harvester-provisioned clusters (using harvester node driver) will show in the virtualization menu. 

**To Reproduce**

* add a harvester cluster through the virtualization management page
  * harvester setup should have network preconfigured, along with some working images and storage
* enable harvester node driver in cluster management -> drivers -> node drivers
* use the harvester node driver to provision an RKE2 cluster
  * select preconfigured network, namespace, image, etc. 
  * ensure k8s version is correctly selected (v1.21.4-rc1+rke2r4 or later) and harvester cloud provider is selected
* while the cluster is provisioning, navigate to the virtualization management page

**Result**
* cluster will show up in virtualization management
  * if cluster is not showing up, delete the cluster in cluster management. while it is deleting, go back to virtualization management and the cluster will show up while it is being removed via rancher. 

**Expected Result**

virtualization management should only show clusters that are running harvester, not clusters provisioned via harvester node driver 

**Screenshots**

<img width="1320" alt="Screen Shot 2021-09-23 at 2 03 50 PM" src="https://user-images.githubusercontent.com/16691014/134586326-b3389c29-2829-4de7-a40f-d4f6bd24a60a.png">

Additional context:
I have not had a consistent way to get a harvester-provisioned cluster to come to `active` state, but once it does, sometimes it still shws in the virtualization management page, sometimes it doesn't.

**Comment by yasker** [comment]
@guangbochen can someone from Harvester UI team take a look at this? Since Virtualization management page is done by us.

**Comment by nwmac** [comment]
@yasker We added into utils/cluster.js a function isHarvesterCluster an function filterOnlyKubernetesClusters.

The isHarvesterCluster used the check you guys put in - `mgmtCluster.metadata?.labels?.[HCI.HARVESTER_CLUSTER] === 'true' || mgmtCluster.provider === VIRTUAL_HARVESTER_PROVIDER;` - but I don't think it should be looking at the provider - as I understand it, a Harvester cluster just just have the label. A cluster that has the provider set to harvester is a kube cluster that has been provisioned onto Harvester infrastructure and is not a Harvester cluster.

**Comment by yasker** [comment]
This should have been fixed in https://github.com/rancher/dashboard/pull/4285 .

**Comment by yasker** [comment]
Regarding how to show the Harvester cluster correctly, more information in https://github.com/rancher/rancher/issues/34880#issuecomment-927218920 and https://github.com/rancher/rancher/issues/34880#issuecomment-927338480

**Comment by yasker** [comment]
@gaktive Can we move this to `To Test`?

**Comment by gaktive** [comment]
@yasker sure thing.

**Comment by slickwarren** [comment]
on v2.6-head (06e19b0):
* adding/removing clusters provisioned via harvester node driver are no longer showing up in the virtualization management page
