### ISSUE TITLE
Enhancement Request - Increase div.clusters height in Vue left nav bar (explorer cluster section)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#4275]
v2.6.0 and v2.6.1-rc2

It would be nice if we could use some more vertical real estate on the left nav pane for div.clusters - only four clusters get listed even on a huge 4k monitor or when otheriwse having tons of vertical real-estate.

Pictured:
4 of my 5 clusters are listed. Due to the overflow a scrollbar is shown - this wasn't very visually noticable to me so I thought there was a bug and my 5th cluster wasn't shown. It turns out that the vertical height is just rather small for div.clusters for some reason.

![image](https://user-images.githubusercontent.com/45179589/134598859-5c9113a4-13a1-45e5-83b9-2ac47301d4f6.png)

**Comment by richard-cox** [comment]
@davidnuzik The number of clusters shown is configurable via the User Avatar Menu --> Preferences --> Formatting section

**Comment by davidnuzik** [comment]
Oh, wow! My apologies for not being aware of this. Thank you! :)
Closing.
![image](https://user-images.githubusercontent.com/45179589/134703472-3e3266cf-ead4-44dd-9aa5-1669550947f0.png)
