### ISSUE TITLE
Can not edit/upgrade the app if the original chart is hidden by the rancher-version annotation

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#4276]
**Setup**
- Rancher version: 2.6.0
- Browser type & version: Chrome
 
**Describe the bug**

We are working on adding the following annotation to all rancher charts that should be available on rancher v2.5.x only
```
catalog.cattle.io/rancher-version: "< 2.5.99-0"
```
But it turns out the UI will go wrong after applying the annotation to the chart. 

**To Reproduce**

It requires some extra steps to reproduce it: 
- clone the rancher/charts repo https://github.com/rancher/charts/tree/dev-v2.6
- checkout the branch dev-v2.6
- run rancher v2.6.0
- on the cluster explorer UI, add a new repo pointing to your GH repo and branch 
- install the app `rancher-alerting-drivers 1.0.100` from the repo
- now update the branch to include the fix from this PR: https://github.com/rancher/charts/pull/1480
- on the cluster explorer UI, refresh the repo
- now the chart rancher-alerting-drivers 1.0.100 should NOT show in the UI anymore 
- go the the app -> edit -> change a value -> click on upgrade 

**Result**

<img width="1631" alt="Screen Shot 2021-09-23 at 5 06 30 PM" src="https://user-images.githubusercontent.com/6218999/134600358-3be2b9b0-c2ef-4b6b-93e5-387e5d660ab1.png">

**Expected Result**

We should be able to 
- editthe existing app 
- upgrade it to the newer version

**Comment by cbron** [comment]
Possible that this is just the backend not returning chart at all, which would not be UI problem. Should be able to tell via the v1 api calls.

**Comment by richard-cox** [comment]
I'm going on the assumption that chart versions with an invalid `catalog.cattle.io/rancher-version` should be filtered out by the backend. If so...
- `v1/catalog.cattle.io.clusterrepos/<repo id>?link=index` response contains invalid versions
- From the screenshot it looks like `v1/catalog.cattle.io.clusterrepos/<repod id>?link=info&chartName=rancher-alerting-drivers&version=1.0.100` then is correctly returning a 500

For app edit/upgrades the user should be offered the chance to select the version to use, the current version will always be offered as well (unless we can't find the chart, then we offer them the option to find it). From the screenshot it looks like this selection was left as-is... so the frontend is trying to request a bad version (from & to versions are displayed under the chart name in the header).

From my understanding then
1) Backend need to ensure it only provides valid chart versions for the `rancher-version`
2) Frontend chart install needs to do additional filtering on versions to ensure the current one exist (see `pages/c/_cluster/apps/charts/install.vue` and `mixins/chart.js` mappedVersions

If `catalog.cattle.io/rancher-version` applies to the target cluster and not local, so backend shouldn't filter out, then frontend needs to do additional filtering (just like we currently do or OS - `CATALOG_ANNOTATIONS.SUPPORTED_OS`)

**Comment by jiaqiluo** [comment]
My testings on the rancher 2.6.0 show that the annotation `catalog.cattle.io/rancher-version: "< 2.5.99-0"` takes effect on only the local cluster. 

So we have 2 issues that need to be addressed: 
1. on the local cluster, the installed app should be editable/upgradable even the original version of the chart is hidden after upgrading rancher
2. This is more like a design question: Should the label works on the downstream cluster? If yes, should we support it in the backend end or the front end?

cc @richard-cox @cbron

**Comment by vincent99** [comment]
Seems like the server-side version filtering should be only on the *listing* of the whole index, so that you don't offer a new install of that chart.  But if we ask for a specific chart+version by name and you have that version: just return it, so that the normal edit flow can work.

**Comment by cbron** [comment]
Backend will fix primary problem in issue linked right there, this issue can exist for the non-existing case, which can be done later.

**Comment by gaktive** [comment]
Based on Caleb's feedback, pushing the UI side out of 2.6.1.

**Comment by jiaqiluo** [comment]
The fix is validated on 2.6.1-rc5

see this comment for the detail: https://github.com/rancher/rancher/issues/34919#issuecomment-929733068

**Comment by brendarearden** [comment]
The only remaining bug seems to be:

The flow from apps & market place > charts > specific chart (for example, rancher-istio) > upgrade does not show the old existing installed version in the drop down
![Screen Shot 2021-09-28 at 5 40 47 PM](https://user-images.githubusercontent.com/19455540/135185406-24b4bb3b-f4dd-45ef-a1df-2c2fd7875c02.png)

The flow from apps & market place > installed apps > specific chart (for example, rancher-istio) > edit/upgrade does show the old existing installed version in the drop down
![Screen Shot 2021-09-28 at 5 41 09 PM](https://user-images.githubusercontent.com/19455540/135185442-1c17dc0c-688c-4bdd-be97-5fc11e89ec7a.png)

Is it possible to upgrade so that both flows work?

**Comment by jiaqiluo** [comment]
Reopen the issue to bring attention. 
Be free to move it back to to-test if it is a false alert.

**Comment by gaktive** [comment]
For the reopened element, we'll push to 2.6.2. With everything else in 2.6.1, perhaps this can be split.

**Comment by brendarearden** [comment]
@gaktive since a partial fix was added making edit is no longer completely blocked, 2.6.2 should be okay for the remainder of the work.

**Comment by gaktive** [comment]
Created https://github.com/rancher/dashboard/issues/4311 to track the outstanding issue based on a comment. Moving this one back To Test for additional QA.
