### ISSUE TITLE
Custom roles creation when assigned to users does not grant access to the resources that were provided as resources in the created custom roles 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4277]
**Setup**
- Rancher version: v2.6.1-rc3
- Browser type & version: chrome

**Describe the bug**
When we create a custom role [global/cluster/project], and add resources with required verbs, the role is created. But when the role is assigned to a user, users are not able to get access that were provided in the created custom roles.

**To Reproduce**
1. Create a rancher server on the version v2.6.1-r3
2. Create an rke1/rke2 node driver cluster [cluster type doesn't matter]
3. Create a user with standard permissions from `Users and auth` --> Users - user1
4. From Users and auth --> roles --> create either a project/global/cluster role with any resource and any verbs --> any [I tried with project role, verbs -->  create, delete and Secret --> resource]
5. Assigned the role to the user in the cluster --> system project

**Result**
Log in as the user1 and see that the user does not see the Secrets tab
See this happen for other resources as well --> Deployment, namespaces etc.

**Expected Result**
The user should be able to see the assigned resources as the role was bound to the user.

**Additional context**
All the resources work if the resource that shows up is plural.
Currently on the dashboard UI most of the resources show up as singular. If we try to add roles from ember UI, we see both singular and plural resources. eg: Namespaces, Secrets etc on the ember UI which work but on dashboard they show up as Namespace, Secret etc.

**Comment by gaktive** [comment]
This sounds similar to https://github.com/rancher/rancher/issues/34800 regarding what's spotted on the Harvester side though @vincent99 indicated that singular vs. pluralization runs into this:
> Looks like only plural works, and also there's no apiGroups set, it needs to be apiGroups: [""] because empty-string is the group for the basic k8s types (or "*" would work, but is wrong...)

**Comment by gaktive** [comment]
For those reading this later, this went back to Dev since the PR wasn't merged upon initial move to QA :)

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `10dfee4`**

- Create a rancher server on the version v2.6.1-rc7
- Create an rke1 node driver
- Create a user with standard permissions from Users and auth --> Users - user1
- From Dashboard create a custom role with `list` for Deployments and secrets
- Request sent has:

```
apiGroups: [""]
nonResourceURLs: []
resourceNames: []
resources: ["secrets"]
verbs: ["list"]
1: {apiGroups: [""], nonResourceURLs: [], resourceNames: [], resources: ["deployments"], verbs: ["list"]}
apiGroups: [""]
nonResourceURLs: []
resourceNames: []
resources: ["deployments"]
verbs: ["list"]
```

- Assign User1 with this role, in project `Default`
- Login as the user. 
- User can list Secrets but NOT Deployments
