### ISSUE TITLE
[harvester] harvester dashboard -> embedded grafana page shows no data, incorrect link is embedded

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4286]
**Setup**
- Rancher version: v2.6-head (0dd1ce6)
- Browser type & version: chrome

**Describe the bug**

embedded grafana page on the harvester dashboard works through harvester, but not on rancher on the imported harvester cluster. 

**To Reproduce**

* deploy harvester setup
* in rancher, import the harvester setup through virtualization management
* after importing, navigate to the harvester dashboard through rancher

**Result**
* grafana shows `no data` for all fields. Grafana link also shows no data
<img width="1771" alt="Screen Shot 2021-09-26 at 1 28 44 PM" src="https://user-images.githubusercontent.com/16691014/134823119-5d6c7416-5dc7-4340-8e2d-12c396ec1b88.png">

**Expected Result**

Grafana should show proper data through rancher

link should be to `/proxy/d/rancher-cluster-nodes-1/rancher-cluster-nodes?orgId=1&from=now-5m&to=now&refresh=30s&theme=dark` (pullled from the harvester grafana URL) instead of to what it is currently set to, `/proxy/d/harvester-vm-dashboard-1/harvester-vm-dashboard?orgId=1&from=now-5m&to=now&refresh=30s&theme=dark` 

**additional context** 
[Here is the harvester feature targeted for 0.3.0](https://github.com/harvester/harvester/issues/576)

**Comment by guangbochen** [comment]
should be addressed via https://github.com/rancher/dashboard/pull/4285

**Comment by yasker** [comment]
Pending on PR https://github.com/rancher/dashboard/pull/4285

**Comment by slickwarren** [comment]
on v2.6-head(06e19b0):
* embedded grafana is now working properly in rancher on harvester clusters
