### ISSUE TITLE
Harvester/UI: If there is no cluster shows in the Virtualization Management page, the page should show them links to the Harvester website/doc

### ISSUE THREAD

**Issue by yasker** [rancher/dashboard#4292]
The Harvester feature flag will be enabled by default in Rancher v2.6.1, but users might be confusing facing a new `Virtualization Management` page and an empty list of clusters.

We can help guide them to the Harvester website (https://harvesterhci.io and https://docs.harvesterhci.io/) if they don't have any Harvester cluster imported.

**Comment by slickwarren** [comment]
tested on v2.6-head(06e19b0) (with UI on 2.6-dev branch):
* links are working, and display properly
* page shows harvester cluster list as soon as at least 1 harvester cluster is added
<img width="1753" alt="Screen Shot 2021-09-28 at 6 47 13 PM" src="https://user-images.githubusercontent.com/16691014/135189219-e63d7412-99be-4c10-b725-2098df005c1b.png">
