### ISSUE TITLE
User can create/edit a git chart repo with an empty Git Branch field

### ISSUE THREAD

**Issue by sgapanovich** [rancher/dashboard#4297]
**Setup**
Bancher version: v2.6-fe57abd77598577487eb5722aba7bc1eebb50d70-head
Browser type & version: Chrome Version 94.0.4606.61 (Official Build) (x86_64)

Rancher cluster type: single-node docker install
Docker version: 20.10
Downstream cluster type: n/a
Downstream K8s version: n/a

**Describe the bug**

A user can create/edit a git chart repository without specifying a `Git Branch`

**To Reproduce**

1. From home page select any cluster (i used my local one)
2. Click "Apps&Marketplace"
3. Click "Repositories"
4. Click "Create"
5. Give it a name
6. For "Target" select "Git repository containing Helm chart or cluster template definitions"
7. For "Git Repo URL" you can use `https://git.rancher.io/charts`
7. Leave "Git Branch" empty (notice: it is a required field)
8. Click "Create"

**Result**
A repo is added 

**Expected Result**

I would expect to have an error returned when the "Create" button is clicked telling me that the branch is required

**Screenshots**

![git branch](https://user-images.githubusercontent.com/40282141/135119582-2e32fbc6-b532-4cd4-b188-5634dfe3c8a5.png)

**Additional context**

**Detailed Description**

The red asterisks should be removed if we allow users create repos without a branch 
OR
UI should return an error the Git Branch field is required and a repo can't be created/edited without specifying the git branch 

**Context**

**Comment by nwmac** [comment]
@Sean-McQ This is an example of where there is no correlation between marking the fields as required and any actual validation being done.

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6.3-rc3
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
Navigated to Apps&Marketplace -> Repositories -> Create
When "Git repository containing Helm chart or cluster template definitions" clicked 
- "Git Branch" input field 
  - no longer has the red asterisks (no longer required)
  - `Will default to "master" if left blank` label is added
    - ![default](https://user-images.githubusercontent.com/40282141/144329527-c36d7889-aedb-4e78-ac03-a9543545c131.jpg)
    - if a user types anything in the input field the label goes away 
  - value entered in the input field is passed to API
    - ![passed](https://user-images.githubusercontent.com/40282141/144330591-b5f0b21e-27bf-4d33-ac6e-e178e38734f1.jpg)
  - if nothing is entered in the input field 
    - the default branch value (main / master) is used 
  - editing the value works as expected 
    - correct value is passed to API
    - chart is updated
  - tried with a github repo where `main` is default branch and there is no `master`
    - when no value is passed 
      - chart can be found 
      - app is deployed
    - when `main` is passed
      - chart can be found 
      - app is deployed
    - when `master` is passed
      - error is returned (expected since there is no master branch)
