### ISSUE TITLE
Fleet- Editing fleet cluster labels from the UI form the label is not applied. Works with Edit YAML

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#4310]
**Setup**
- Rancher version: `v2.6.1-rc5` HA RKE1 `v1.3.1`
- Browser type & version: `MS Edge 94.0.992.31` (Chrome based) and `Chrome 93.0.4577.63`

**Describe the bug**
Editing a Label from the UI form of a Fleet Cluster config seems to work when clicking save but the label is not applied

**To Reproduce**

1. Provision a Downstream cluster
2. Go to Continuous Delivery
3. Edit Cluster config
4. Set a Label and click Save

**Result**

 User is taken back to the Fleet cluster list but the label is not applied.

I see a PUT request in the network activity with response 200 but If I go and check the YAML config or click on Edit Cluster again the Label is not set.

Also the cluster doesn't show the new label if I apply the label from Edit YAML, and then navigate to Edit Config.

**Expected Result**

**Screenshots**

Screens of a label that was set using Edit as YAML and then navigated to Edit Cluster config.

![Screen Shot 2021-09-29 at 9 17 13 AM](https://user-images.githubusercontent.com/27659/135308699-6c072815-315a-4fb9-99d4-265ccba15ab2.png)

![Screen Shot 2021-09-29 at 9 17 31 AM](https://user-images.githubusercontent.com/27659/135308722-6b560790-fa3d-4d65-a0de-6cdbf9f460fb.png)

**Additional context**
Fleet version `v0.3.7-rc3`

**Comment by sgapanovich** [comment]
seems similar to the issue we had before https://github.com/rancher/dashboard/issues/4226
that one has been fixed (adding labels and annotations to a deployment via UI) and confirmed to be working in `2.6.1-rc5`

**Comment by gaktive** [comment]
As Sergei notes, this looks to be fixed in https://github.com/rancher/dashboard/issues/4226. @izaac can you retest and confirm that this is the case?

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Validation**
- crhome: 94.0.4606.61 
- Rancher version: v2.6-head(e322f8f)
- Cluster type: RKE1 v.1.3.1
- k8s version: V1.21.6

**Steps For Validation**
1. Within rancher I navigated to continuous delivery --> clusters --> edit config
2. From here I tapped "Add Label" and enter values, do this with various names and values.
3. Navigate to Continuous Delivery --> clusters --> select cluster
4. From here I see the labels you added listed beside "Labels:"
**Screenshot of Result**
![Screen Shot 2021-11-20 at 12.20.02 AM.png](https://zube.io/files/rancher/c71809d81eaea071f91a6f00d7c95398-screen-shot-2021-11-20-at-12-20-02-am.png)
5. Checked the Yaml file for labels added via the UI. 
**Screenshot of  Yaml**
![Screen Shot 2021-11-20 at 12.22.54 AM.png](https://zube.io/files/rancher/c6683ddbb865174c1a99014995127abd-screen-shot-2021-11-20-at-12-22-54-am.png)
6. Checked the edit config to make sure the labels were still present. 

**Sanity Checks**
Tested with similar steps above in the following areas
- Cluster Node Labels Pass
- projects/Namespaces Pass
- Deployments - fleet-agent Pass
- Repositories Pass
- Services Pass
