### ISSUE TITLE
Apps & Marketplace: differences in flow for charts vs. installed apps

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4311]
Taken from https://github.com/rancher/dashboard/issues/4276 based on @brendarearden's testing for 2.6.1:

The flow from apps & market place > charts > specific chart (for example, rancher-istio) > upgrade does not show the old existing installed version in the drop down
![Screen Shot 2021-09-28 at 5 40 47 PM](https://user-images.githubusercontent.com/19455540/135185406-24b4bb3b-f4dd-45ef-a1df-2c2fd7875c02.png)

The flow from apps & market place > installed apps > specific chart (for example, rancher-istio) > edit/upgrade does show the old existing installed version in the drop down
![Screen Shot 2021-09-28 at 5 41 09 PM](https://user-images.githubusercontent.com/19455540/135185442-1c17dc0c-688c-4bdd-be97-5fc11e89ec7a.png)

Is it possible to upgrade so that both flows work?

_Originally posted by @brendarearden in https://github.com/rancher/dashboard/issues/4276#issuecomment-929737069_

**Comment by gaktive** [comment]
Despite the extra time for the 2.6.1 release, we'll focus on critical Harvester bugs so pushing out to 2.6.2.

**Comment by gaktive** [comment]
As noted by @cbron, it allows editing of pre-installed charts from a diff flow, to me its a pretty bad bug.

**Comment by Shavindra** [comment]
From closer inspection this seems to be intended? Difference is that before you click on the upgrade button in the flow (apps & market place > charts > specific chart (for example, rancher-istio)) you're looking at the the latest version regardless of the installed version and information associated with it.

So when you click on upgrade. The expectation is that latest version we suppose to upgrade is already pre selected for you.

Note how in the screenshot `(current version)` in brackets and latest is highlighted in bold

![image](https://user-images.githubusercontent.com/1387263/142672267-539c4542-9d4b-491a-a956-13681bfe44dc.png)

**Comment by Shavindra** [comment]
@davidnuzik Could you please review this again please? I've checked this also with another person. We both can't replicate and the flow is behaving as expected.

apps & market place > charts > specific chart > upgrade will pre select the version that it was selected in the chart page. All the other versions are still visible

edit/upgrade > will navigate to current installed version.

**Comment by brendarearden** [comment]
@Shavindra the versions that are available should be limited based on https://github.com/rancher/charts/blob/f69b38808ee204925e6be3651cc12edda12c93a6/charts/rancher-istio/rancher-istio/100.0.2%2Bup1.10.4/Chart.yaml#L8 this chart annotation. This annotation is not evaluated when running a non release version of rancher https://github.com/rancher/rancher/blob/ec31e6456d4068899460bb83640b63c83eaa72c6/pkg/catalogv2/content/content.go#L199. If you try the flow again with this in mind, are you able to recreate the flow discrepancy that I was seeing?

**Comment by davidnuzik** [comment]
> @davidnuzik Could you please review this again please? I've checked this also with another person. We both can't replicate and the flow is behaving as expected.

@Shavindra I've not seen this issue before but I will take a look.

**Comment by deniseschannon** [comment]
This should be fixed as part of the backend fix (which is merged) which should provide the currently installed chart even if it's not technically valid for that Rancher version. 
https://github.com/rancher/rancher/issues/35680

**Comment by sowmyav27** [comment]
Validate using `2.6.3-rc5`

**Comment by phillipsj** [comment]
Both locations are now showing the exact same output which is below which shows the current installed version in the drop down.
![Screenshot from 2021-12-15 22-13-42](https://user-images.githubusercontent.com/1568133/146301738-b8c19339-e571-497f-ac48-59291fb6c91c.png)

**Comment by sowmyav27** [comment]
Verified on latest 2.6-head
