### ISSUE TITLE
Harvester: unable to provision load balancer, stuck in pending state with errors

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4312]
on v2.6-head (06e19b0):
I am unable to provision a load balancer using the harvester cloud provider. LB is stuck in `pending` state with the following  errors:
`Service is ready:Load balancer is being provisioned`
<img width="985" alt="Screen Shot 2021-09-28 at 4 16 29 PM" src="https://user-images.githubusercontent.com/16691014/135178233-62b4a614-bc64-4346-83c3-7ede0b2f512c.png">

_Originally posted by @slickwarren in https://github.com/rancher/dashboard/issues/4208#issuecomment-929692433_

**Comment by gaktive** [comment]
Taken from https://github.com/rancher/dashboard/issues/4208. Per https://github.com/rancher/dashboard/issues/4208#issuecomment-930292635, there is documentation that indicates which annotations can identify the LBs.

**Comment by richard-cox** [comment]
@guangbochen Just confirming, this will be resolved by https://github.com/rancher/dashboard/pull/4509?

**Comment by guangbochen** [comment]
Yes and we can help to do the validation, thanks

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/1435#issuecomment-966012444
