### ISSUE TITLE
Dashboard UI | Workload's port does not get updated and no additional service created  

### ISSUE THREAD

**Issue by sgapanovich** [rancher/dashboard#4316]
**Setup**
- Rancher version: 2.6.1-rc7
- Browser type & version: Chrome version: 94.0.4606.61 (Official Build) (x86_64)

**Describe the bug**

UI does not send the cluster type when updating a port from clusterIP to NodePort (it used to in the old UI)

**To Reproduce**

1. Main Menu
2. Create a deployment 
  with a PORT: 
      - service type: clusterIP
      - private container port: 8080
3. Save
  at this point a clusterIP service is created for that deployment 
  ![test port created](https://user-images.githubusercontent.com/40282141/135373979-a810fdaf-acfb-4305-9fa5-b1eb2991edca.png)
4. go back to edit the deployment 
  change service type to Node Port
  leave the private container port to be 8080
  listening port: 30456
5. click Save 

**Result**
no node port service is created 
there are two PUT requests 

in the PUT `/k8s/clusters/.../v1/apps.deployments/default/test` deployment is sent as a **cluster ip** with another port added (listening port)
  see screenshot (30456 is mentioned only once in the context of the cluster IP)
<img width="696" alt="deployment put " src="https://user-images.githubusercontent.com/40282141/135374440-25379708-a622-493f-b69a-bfd5486f55d8.png">

in the PUT `k8s/clusters/.../v1/services/default/test` services do not send "30456" or "node port" at all (see screenshot: 30456 is not found on in the request payload)

<img width="705" alt="service put" src="https://user-images.githubusercontent.com/40282141/135374974-3191bac8-53d8-4df6-b070-6584dc99dd72.png">

**Expected Result**

node port service is added 

**Context**

it is working in the old UI and I expected to be working in the new UI as well

**Comment by sgapanovich** [comment]
found while testing https://github.com/rancher/dashboard/issues/4159

**Comment by mantis-toboggan-md** [comment]
The same bug is reported in rancher/dashboard#4398 , closing this one in favor of that as it has a pr tied to it
