### ISSUE TITLE
Not possible to uninstall app if switching branches

### ISSUE THREAD

**Issue by alex-isv** [rancher/dashboard#4320]
**Setup**
- Rancher version: 2.6
- Browser type & version:

**Describe the bug**

After installing the app from the marketplace and if change branches or if branch got removed, it's not possible to delete/uninstall the app.
**To Reproduce**

**Result**

**Expected Result**

App should be removed if needed without checking the existing branch.
**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by alex-isv** [comment]
Example:

![image](https://user-images.githubusercontent.com/52678960/136069809-ae3f2a33-7568-4f5f-91f2-a9cdab7b90cb.png)

**Comment by richard-cox** [comment]
I'm not able to reproduce this with the latest code (~2.7.0) (using https://charts.bitnami.com/bitnami and the redis chart). 

@alex-isv If you can still reproduce this with the latest version let us know the repo and chart and we can re-open this issue
