### ISSUE TITLE
User is unable to delete a nodepool through dashboard (`403 error`, permission denied) but can through ember for rke1 clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4321]
**Setup**
- Rancher version:v2.6.1-rc9
- Browser type & version:chrome

**Describe the bug**

user gets a 403 when trying to delete a nodepool

**To Reproduce**

* provision an rke1 cluster with at least 2 nodepools, say 1 has all roles and the other has only worker role
* allow cluster to come to active state
* remove the non-essential (worker only) node pool in dashboard

**Result**
* user gets a `403` error and is unable to remove the nodepool

**Expected Result**

cluster owners should be able to remove node pool(s)

**Screenshots**

rke1:

<img width="1468" alt="Screen Shot 2021-09-30 at 8 51 12 AM" src="https://user-images.githubusercontent.com/16691014/135489062-d1c0d1fd-a4a3-473d-baef-f36c9ca285d3.png">
<img width="360" alt="Screen Shot 2021-09-30 at 8 44 44 AM" src="https://user-images.githubusercontent.com/16691014/135489068-43005e8f-918a-4995-825a-042934ae3405.png">

rke2 (no option to remove nodepool through UI)
<img width="1455" alt="Screen Shot 2021-09-30 at 8 50 53 AM" src="https://user-images.githubusercontent.com/16691014/135489092-b8b9eea0-94de-4460-9b96-0aa731258680.png">

**Additional context**
* this appears to only be an option for rke1 clusters in dashboard; rke2 clusters do not have the option for nodepools (see screenshots)
* user can work around this by editing the cluster and removing the nodepool there instead

**Comment by nwmac** [comment]
@vincent99 Is this a case where we are trying to delete the nodepool using the generic mechanism, where we should be updating the cluster resource?

**Comment by vincent99** [comment]
It's probably attempting to delete via steve instead of norman.

**Comment by slickwarren** [comment]
tested on v2.6-head (4375161):
* user is now able to remove rke1 nodepools through the UI
