### ISSUE TITLE
In a list of PVC forms, attempting to close any form always causes the last form to be deleted

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#4323]
**Setup**
- Rancher version: 2.6.1
- Browser type & version: Chrome 93

**Describe the bug**
When you create a workload and go to the storage tab, and click Create Persistent Volume Claim multiple times to open multiple forms, only the last form can be deleted normally. 

**To Reproduce**
1. Go to cluster explorer
2. Open the form to create a Deployment
3. Click the Storage tab
4. Click **Add Volume > Create Persistent Volume Claim** and name the first one "1"
5. Click **Add Volume > Create Persistent Volume Claim** and name the second one "2"
6. Click X on PVC form called "1"
7. Fill out required details for a PVC and save the workload. The expected result is that it is saved successfully. The actual result is that it says PVC "1" is lacking required fields.

Saving the workload results in errors because the value for "1" is not really deleted.

You can do this with any number of PVC forms. No matter which form you try to delete, only the last one will be deleted. For example, if you create four forms and try to delete the second one, you will see that the value for the fourth one was deleted.

**Screenshots**
PVCs for deployments:
<img width="1478" alt="Screen Shot 2021-09-30 at 10 21 05 PM" src="https://user-images.githubusercontent.com/20599230/135569451-1d2149e3-002b-4ba7-bd7b-b100dbf70c25.png">

**Comment by mantis-toboggan-md** [comment]
There is a bug in which extra mount points appear sometimes when adding/removing volumes repeatedly. It might be seen while testing this bug, but it isn't specific to PVC-based volumes and is being tracked separately in #4356

**Comment by brudnak** [comment]
**My checks PASSED**
  
**Reproduction Environment:**

| Component               | Version                                        |
| ----------------------- | ---------------------------------------------- |
| Rancher version         | 2.6.1                                          |
| Rancher cluster type    | Docker install                                 |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu1~20.04.2        |
| Downstream cluster type | Downstream RKE1 EC2                            |
| Downstream K8s version  | v1.21-rancher1-1                               |
| Browser type            | Google Chrome                                  |
| Browser version         | Version 94.0.4606.81 (Official Build) (x86_64) |

<img width="491" alt="01-4323-repro-env" src="https://user-images.githubusercontent.com/40877149/137411839-9a96a98b-d839-44a1-af09-ac66963e4729.png">
  
**Reproduction steps:**

1. Starting from the Rancher homepage `/dashboard/home`
2. Click the hamburger menu -> `Cluster Management` -> `Explore` (next to cluster described in reproduction environment) -> `Workload` (from left side menu) -> `Create` -> `Deployment`
3. Fill out bare minimum for the deployment form
   - Name: `hello-world`
   - Container Image: `brudnak/hello-rancher-golang`
4. Click `Add Volume` -> Create `Persistent Volume Claim` and name the 1st `pvc-test-one`
   - **IMPORTANT:** Only enter / fill out the `Persistent Volume Name`
5. Click `Add Volume` -> Create `Persistent Volume Claim` and name the 2nd `pvc-test-two`
   - **IMPORTANT:** Only enter / fill out the `Persistent Volume Name`
6. Click `X` on PVC form called `pvc-test-one`
   - You will observe the even though you clicked the delete `pvc-test-one` it actually deleted the last pvc which was `pvc-test-two`
7. Continue to fill out the form with required fields
    - Capacity: `10`
    - Access Modes: `Single-Node Read/Write`
    - Mount Point: `/mnt`
8. Click `Create` 
9. You will now see the following error message. Even though `pvc-test-two` appears to be deleted from the UI Also see screen shot labeled `A1` under `Additional Info` below
```txt
PersistentVolumeClaim "pvc-test-two" is invalid: [spec.accessModes: Required value: at least 1 access mode is required, spec.resources[storage]: Invalid value: "0": must be greater than zero]
```

**Additional Info:**


<img width="1289" alt="02-4323-failure-a1" src="https://user-images.githubusercontent.com/40877149/137411914-54977b38-2475-42e7-8a8b-e5e80d72ced9.png">

-----
  
**Validation Environment:**


| Component               | Version                                            |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-a636bda2a00e939665b381f704ea8556c39d1a84-head |
| Rancher cluster type    | Docker install                                     |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu1~21.04.2            |
| Downstream cluster type | Downstream RKE1 EC2                                |
| Downstream K8s version  | v1.21.5-rancher1-1                                 |
| Browser type            | Google Chrome                                      |
| Browser version         | Version 94.0.4606.81 (Official Build) (x86_64)     |

<img width="583" alt="03-4323-valid-env" src="https://user-images.githubusercontent.com/40877149/137411936-23c395ce-fff0-4b4e-9035-b861a86f8a25.png">

  **Validation steps:**


1. Follow the steps from reproduction above until `STEP #6`
2. **NOW** when you Click the `X` for `pvc-test-one`
    - `pvc-test-one` actually gets deleted now and you are left with `pvc-test-two`
3. Fill out the required elements for `pvc-test-two` for example:
    - Capacity: `10`
    - Access Modes: `Single-Node Read/Write`
    - Mount Point: `/mnt`
4. Click `Create`
5. Now the deployment is successfully created :tada:
