### ISSUE TITLE
Customized widget on Home page

### ISSUE THREAD

**Issue by eumel8** [rancher/dashboard#4326]
**Detailed Description**

On the dashboard start page there are now widgets for Getting Started, Community and Enterprise support. I want to have a customized widget where I can place HTML code from `<div>` container or `<iframe>` to implement a RSS feed, i.e. from http://www.rssfeedwidget.com/
 
**Context**
We want to inform our customer on the Home page after login about service state, issues, or upcoming changes. Information can be fetched from our Jira system via RSS or any other RSS feed.

**Comment by richard-cox** [comment]
From 2.7.0 the new Extensions mechanism supports users in creating their own plugins for the Dashboard. This issue should be achievable by replacing the home page route with one that points to a new, custom page from within the plugin.

There's some initial documentation [here](https://rancher.github.io/dashboard/plugins/plugins-getting-started), and examples [here[(https://github.com/rancher/ui-plugin-examples).
