### ISSUE TITLE
Editing template in constraints doesn't work. 

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#433]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable gatekeeper.
2. Create a constraint under 'k8sallowedrepos'.
3. Edit the constraint and try to change template 'k8srequiredlabels'

**Result:**
Template doesn't get changed. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2559-head- 02956b782
- Installation option (single install/HA): Single

**Comment by codyrancher** [comment]
@khushboo-rancher what type of edit did you attempt? I've successfully edited a template before.

**Comment by khushboo-rancher** [comment]
@codyrancher Changing constraint template in constraint. This is editing of constraints and changing the constraint template of it.

Steps:
1. Go to constraint.
2. Click edit in form view.
3. Change the template from dropdown.

**Comment by codyrancher** [comment]
Oh, I see. Thanks.

**Comment by codyrancher** [comment]
@vincent99 @tfiduccia  to support switching a constraint's constraint template I would have to delete the current constraint and create a new one. I'm a little weary of doing this as this would need to be transactional to be correct.

Would you be alright if I disabled switching the template when editing a constraint?

**Comment by vincent99** [comment]
Yes, disable editing the template on edit

**Comment by khushboo-rancher** [comment]
Verified on master branch of 2.4 rancher set up.

Template field is uneditable in edit constraint in form view.
Steps :
1. Create a constraint.
2. Click edit as form.
3. Template is not editable.
<img width="1349" alt="Screen Shot 2020-05-07 at 3 54 13 PM" src="https://user-images.githubusercontent.com/60111667/81352348-28e9a780-907b-11ea-9731-5d41a591dd0b.png">
