### ISSUE TITLE
Cluster Dashboard missing utilization info

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4330]
Cluster Dashboard only shows reservation, it does not have an overlayed graph/image to quickly show reservation against utilization. It's important this is overlayed as very quickly it gives an understanding of utilization vs reservation for capacity, it's quite useless having this separated.

![image-2021-09-17-18-53-46-033.png](https://zube.io/files/rancher/c018ff949956c635bcc3effa75385f59-image-2021-09-17-18-53-46-033.png)

![image-2021-09-17-18-53-53-930.png](https://zube.io/files/rancher/229afd3e65616dc4e5ad6692bdb45b2e-image-2021-09-17-18-53-53-930.png)

**Comment by gaktive** [comment]
Earlier wireframe for the metrics dashboard story. https://xd.adobe.com/view/866862d9-4ac5-4962-a026-0c716a335cb7-d33b/

Noted as lost functionality. Slide 2 on the wireframe covers the view for RAM and cores. Would need to add reserved vs. used in the graph.

**Comment by gaktive** [comment]
Someone needs to look at how we're getting the data on v1 vs v2. 

The wireframe appearance also needs some review in the use case if Used and Reserved are equal and how to visualize that.

**Comment by jmcsagdc** [comment]
Reproduced in v2.6.2

![262-missing-used](https://user-images.githubusercontent.com/15971368/140815543-de9f58f2-c994-4882-be4a-168a3a555aa6.jpg)

Verified in v2.6-e655fd8b821840209ff6b73f7a6e520327d409ba-head

![fix-in-head](https://user-images.githubusercontent.com/15971368/140815632-48afeb78-d9f0-4ef4-876d-f0eaccaa1135.jpg)
