### ISSUE TITLE
Add customizable organization consent banner to user login page.

### ISSUE THREAD

**Issue by bgulla** [rancher/dashboard#4336]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
As an operator in a corporate enterprise, I would like to add a consent banner on the Rancher login screen. This banner would be presented to every user upon login with a block of text similar to "By using this system I consent to monitoring and proper use of this electronic medium under penalty of law..." Similarly to the announcement banner added in 2.4, I would expect this to be configurable from the Global settings UI. 

**Result:**
An example banner can be found here: https://www.bootcamp.navy.mil/consent2.html

**Other details that may be helpful:**
I would expect this to be optional and not disrupt the UI for organizations that do not have this requirement.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.5.x
- Installation option (single install/HA):
N/A

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

gz#12836

**Comment by sowmyav27** [comment]
Moving this back to Review, since the PR has not been merged.

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID 4375161`

1. Logged in 
2. Clicked Hamburger Menu
3. Clicked Global Settings
4. Clicked Branding

Under `Fixed Banners` at bottom of page, There is a new checkbox: `Show Consent Banner on Login Screen`. 

Tested and verified functionality by admin and standard user with various text, in each configuration (Left Center, Right, Different font formats and different sizes.)

![Screen Shot 2021-11-29 at 5.24.04 PM.png](https://zube.io/files/rancher/04935ba8a1b0bc10bf428beb306bc381-screen-shot-2021-11-29-at-5-24-04-pm.png)

![Screen Shot 2021-11-29 at 5.24.17 PM.png](https://zube.io/files/rancher/01ddd250616f243ddabfef12bb3a1add-screen-shot-2021-11-29-at-5-24-17-pm.png)
