### ISSUE TITLE
Reset What's New upon minor release upgrades

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4349]
https://github.com/rancher/dashboard/blob/master/shell/content/docs/en-us/whats-new.md (formerly https://github.com/rancher/dashboard/blob/master/content/docs/en-us/whats-new.md) contains a summary of the release notes, highlighting mostly high level as to what's new.

This content needs to come from all teams who would provide content for UI but per @vincent99, this page has a mechanism that doesn't reshow upon subsequent upgrades. For example, going from 2.5.x to 2.6.0 would trigger showing What's New but 2.6.0 to 2.6.1 wouldn't. 

Apparently, based on this, the file wasn't updated during 2.5.x after 2.5.0. This may be a release checklist item going forward per @Jono-SUSE-Rancher so we need a way of presenting this to existing users after minor upgrades again.

**Comment by vincent99** [comment]
I didn't mean this like it was necessarily a bad thing; there is not supposed to be anything significantly new to talk about in patch releases.  That doesn't reflect reality (especially with Harvester soon) but there's often going to be nothing interesting to talk about in a release.  And you don't know when showing it if the user came from 2.6.0 vs 2.5 vs 2.4.

**Comment by gaktive** [comment]
For 2.6.3, we did get some input: https://github.com/rancher/dashboard/issues/4678

**Comment by catherineluse** [comment]
I think that since the UI team owns the release notes, they should also own the "What's New" section. The "What's New" content could be tracked, reviewed and edited in the same GitHub repo that the release notes are edited in. I'd suggest closing this issue since it would be better tracked in process documents about the release process.

**Comment by gaktive** [comment]
@nwmac discussed with @leflambeur about the future of What's New and going forward, we'll remove this from the Ui and link directly to the release notes. 

There's a ticket somewhere to do this but I can't find it to link...
