### ISSUE TITLE
On deleting a cluster, it is removed from Cluster Management page, but is still seen on the Home page 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4355]
**On 2.6.1**

- Deploy a custom RKE2 DO cluster -1 node all roles
- The node was deleted from backend.
- The cluster went into error state
- Delete the cluster from the Cluster management page
- the cluster is not listed in this page anymore.
- However on the Left slide in menu the cluster is available but disabled
- Also in Home page the cluster is seen in removing state
- Home Page:

<img width="1161" alt="Screen Shot 2021-10-11 at 4 14 05 PM" src="https://user-images.githubusercontent.com/26032343/136865947-a23ad927-48d4-49ee-9059-975a1898a165.png">

Similar to issue - https://github.com/rancher/dashboard/issues/3423

**Comment by nwmac** [comment]
@sowmyav27 Does the cluster eventually go away in these other places?

**Comment by norcis** [comment]
![image](https://user-images.githubusercontent.com/1047487/142377675-8debb32a-6d72-4009-9828-6636b3545a10.png)
Stuck removing from home page, but removed at cluster management.

@sowmyav27 any workaround?

**Comment by catherineluse** [comment]
I wonder if the 'ghost cluster' problems could be caused by Chrome not updating pages properly when self-signed certs are used. See Jason's comment https://github.com/rancher/dashboard/issues/3936#issuecomment-1022772061

**Comment by nwmac** [comment]
Reproduced this - note that if you leave it a short time, it does clear up - the issue is the home and side nav lists show mgmt clusters where as the other list shows provisioning clusters and it can take a while for the mgmt cluster to be cleaned up when the provisioning cluster is deleted - we should be able to work around this in the UI.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head bca5ada
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 DO -1 node all roles

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy a custom RKE2 DO cluster -1 node all roles
2. Delete the cluster from the Cluster management page
3. Wait a couple minutes for the cluster to fully delete
4. Verify that the cluster is not listed on the Cluster Management page
5. Verify that the cluster is not listed in the Home Page
6. Verify that the cluster is not listed in the left side menu.

**Result** - Pass

Cluster is removed successfully and is no longer listed in the UI.
