### ISSUE TITLE
Workload volumes sometimes have duplicate auto-generated names

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#4356]
While creating or editing a workload, if multiple volumes are added and deleted, volume names may be duplicated, which breaks the mapping to container volumeMounts. 

1. Navigate to the deployment-creation form storage tab
2. Add two 'Create New PVC' volumes
3. Add a mount point to the second pvc volume
4. Delete the first pvc vol
5. Add another 'Create New PVC' volume
6. Observe that the new pvc volume has the same name and mount point as the other pvc volume

https://github.com/catherineluse/dashboard/blob/pvc/edit/workload/storage/index.vue#L151

This name should not be based off the length of the volume array; however it's generated it must be unique.

**Comment by ronhorton** [comment]
Duplicated in 2.6.2

1. Navigate to deployment-creation from storage class
2. add two new pvc volumes
3. delete the first pvc volume
4. add another pvc volume

Volume name is same as existing volume

![Screen Shot 2021-11-30 at 2.33.59 PM.png](https://zube.io/files/rancher/f567a5542179d4d9b0384461f4548870-screen-shot-2021-11-30-at-2-33-59-pm.png)

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID 4375161`

1. Navigate to deployment-creation from storage class
2. add two new pvc volumes
3. delete the first pvc volume
4. add another pvc volume

`Volume name for pvc volume created in step 4 is unique`

![Screen Shot 2021-11-30 at 2.36.21 PM.png](https://zube.io/files/rancher/107554cb6d989d7c9317623536519974-screen-shot-2021-11-30-at-2-36-21-pm.png)
