### ISSUE TITLE
Clicking a menu item has no effect while user is on a sub-level view

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#4358]
Rancher 2.6.1

**Describe the bug**

1. Open Cluster Explorer
2. Navigate to Cluster -> Nodes
3. Click on Cluster in the left hand menu

**Expected:**

Cluster Dashboard view is loaded when clicking on "Cluster" menu item.

**Actual:**
Clicking has no effect. In order to access the dashboard the user must first navigate to any other first level menu, such as workloads, then click on Cluster menu entry again...

The same behaviour can be observed with any other view that is accessed by a top-level menu item, such as Monitoring.

https://user-images.githubusercontent.com/3813921/136949721-6f99c0a3-7240-4a5a-9b85-cc29ff86e852.mov

**Comment by Auston-Ivison-Suse** [comment]
My setup for validation:

- chrome: 94.0.4606.61
- rancher v2.6.1 (repro) and v2.6.2-rc1 (validation)
- Kubernetes distribution: RKE v1.3.1
- instance type for rancher: ec2 (aws)
- cluster built: (aws high availability cluster, 3 nodes)

Steps taken for reproduction and Validation

1. create the above setup
2. navigate to the rancher setup and click the top left hamburger menu
3. Navigate to a created cluster under Explore Cluster
4. click on "projects/Namespaces" under the cluster menu
5. Try to click the cluster option above.
6. Witness the bug doesn't allow for the cluster dashboard to be pulled up again.

Some Sanity Checks:

- Witness intended pages for each selection of items on the menu and where they land in the submenu. For example; selecting workloads lands on an overview of workloads. While selecting storage puts you on the submenu page for ConfigMaps


See fix in the below video. 

https://zube.io/files/rancher/7fee60249e2ae81173d7434affacfc9b-2021-10-19_10-07-57.mp4
