### ISSUE TITLE
Info banner on cluster repo list page does not close when prompted

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#4359]
- Rancher version:
Rancher 2.6.1

- Browser type & version:
Firefox 78.13.0esr

**Describe the bug**
On the Cluster Repo List page the banner at the top does not close when prompted.
Also errors in the console point to the issue of the handler for the close event isn't defined.

**To Reproduce**
1. Navigate to _cluster_ => Apps & Marketplace => Repositories
2. Try to close info banner above the list

**Result**
The banner does not close

**Expected Result**
The banner should close

**Screenshots**

https://user-images.githubusercontent.com/40806497/136951676-4de4d22c-706f-4d5a-8984-5eaff631553f.mp4

(Errors in console)
![clusterrepoListError](https://user-images.githubusercontent.com/40806497/136951702-1160853d-9500-477f-9639-95e71e8fb1b0.png)

**Comment by brudnak** [comment]
**My checks PASSED**
  
### Reproduction Steps

Not required.
 
<hr>
  
## Validation Environment

| Component               | Type / Version                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version:        | v2.6-931a0f09d0f85ade0dcaa8fbe9d6e0c58ae52bbc-head |
| Rancher cluster type    | Single Node Docker Install                         |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu1~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | Custom RKE Linode                                  |
| Downstream K8s version  | v1.21.5-rancher1-1                                 |
| Cloud credentials       | Linode API Token setup prior to steps              |
| Browser Type            | Google Chrome                                      |
| Browser Version         | 95.0.4638.69 (Official Build) (x86_64)             |

### Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> Under EXPLORE CLUSTER click `local` -> `Apps & Marketplace` -> `Repositories`
3. Now click the `X` on the info banner that's displaying this message:

```txt
A chart repository is a Helm repository or Rancher git based application catalog. It provides the list of available charts in the cluster. Cluster Templates are deployed via Helm charts.
```

4. The message now closes successfully :rocket:
