### ISSUE TITLE
Restore Snaphot is missing on Cluster Menu on 2.6.0

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/dashboard#4364]
**Setup**
- Rancher version: 2.6

- Browser type & version: FireFox 86.0 

**Describe the bug**
After the Successful upgrade of Rancher from 2.5.9 to Rancher 2.6.0, When I compare  the old menu to new under the cluster of Restore of Snapshot I could not able to find only the menu could see only Take Snapshot 

![image](https://user-images.githubusercontent.com/4696166/137008553-3ab08be8-df5e-4f4d-900b-b5eb5085c3dd.png)

**Comment by vincent99** [comment]
Click on the cluster.  Snapshots are a tab in its details.  Restore kids an action on the snapshot, not the cluster.
