### ISSUE TITLE
Clicking the header of an expanded nav group does nothing

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#4368]
This bug was noticed while fixing rancher/dashboard#4358. 
1.Navigate to Cluster Explorer->More Resources->Core (Node page is selected)
2. Click the Discovery group: Core section remains expanded, Discovery group expands, and Endpointsslices is selected
3. Click the Core header again: Navigation is unchanged.

Clicking a group's header while the group is not expanded navigates to the first item in the group. We should see the same behavior if we click the header of an expanded group.

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.6.3**

1. Navigate to Cluster Explorer->More Resources->Core (Node page is selected)
2. Click the Discovery group: Core section remains expanded, Discovery group expands, and Endpointsslices is selected
3. Click the Core header again: Navigation is unchanged.

**On 2.6head commit id: `8c785a1`**
1. Navigate to Cluster Explorer->More Resources->Core (Node page is selected)
2. Click the Discovery group: Core section remains expanded, Discovery group expands, and Endpointsslices is selected
3. Click the Core header again: Navigation moves to Core (Node page is selected)
