### ISSUE TITLE
Accessibility: setting HTML page language

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4381]
From the audit per rancher/dashboard#4324, an easy quick win to improve accessibility is to add the lang=”en” to the <html> to allow readers to know the language of the page.

**Comment by lvuch** [comment]
This will need dev attention as language swithces

**Comment by nwmac** [comment]
Need to add code so that when the locale is changed we updated the attribute value

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 68c6c13
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 102.0.5005.63 

----------

### Testing: ###

Tested this issue with the following steps:
1. Open developer tools after navigating to Rancher UI
2. Go to `Elements` tab
3. Verify `<html lang="en-us"...` is in the top of the html

**Result** - Pass

lang tag is now set in the html
![image.png](https://zube.io/files/rancher/71f29fc9d9ec9e00e8bfb6415074f29f-image.png)
