### ISSUE TITLE
Fleet: Unable to fill in configuration form in UI with http based git address while creating gitrepo.

### ISSUE THREAD

**Issue by bluezd** [rancher/dashboard#4395]
Details please refer to this fleet issue:
https://github.com/rancher/fleet/issues/546

**Comment by gaktive** [comment]
As noted in https://github.com/rancher/fleet/issues/546#issuecomment-943710704, this looks to be a problem with a bug in the UI where it should only hide TLS Certficate Verifications not the other options. Do note that modifying the URL to be HTTPS makes this work.

**Comment by gaktive** [comment]
This reads like a duplicate of #4830. @Shavindra can you confirm? We can close this one in lieu of the other.

**Comment by Shavindra** [comment]
Yes, This is a duplicate. I have a draft PR for this already. @gaktive

**Comment by gaktive** [comment]
Excellent. I'll close this as a dupe then, thanks.
