### ISSUE TITLE
Deleting Ingress Rules - UI Doesn't Match Behavior

### ISSUE THREAD

**Issue by brudnak** [rancher/dashboard#4400]
**Setup**

| Component               | Version                                            |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-a636bda2a00e939665b381f704ea8556c39d1a84-head |
| Rancher cluster type    | Docker install                                     |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu1~21.04.2            |
| Downstream cluster type | Downstream RKE1 EC2                                |
| Downstream K8s version  | v1.21.5-rancher1-1                                 |
| Browser type            | Google Chrome                                      |
| Browser version         | Version 94.0.4606.81 (Official Build) (x86_64)     |

**Describe the bug**

When deleting ingress rules the UI does not match the expected behavior. For example. If you create three ingress rules like the following:

1. `example.com/1`
1. `example.com/2`
1. `example.com/3`

If you delete `example.com/1` in the UI by clicking the `X` on it instead of it being deleted the last rule `example.com/3` is deleted from the UI instead. However, when you click save. You'll actually see that `example.com/1` was deleted and you are left with `example.com/2` & `example.com/3`.

**To Reproduce**

1. Starting from the Rancher dashboard homepage `/dashboard/home`
2. Click the hamburger menu -> `Cluster Management` -> Click `Explore` (next to the cluster described from setup environment) -> Click `Service Discovery` -> `Ingresses` -> `Create`
3. Fill out fields to create an ingress
   - Name: `my-ingress-test`
4. Click `Add Rule` twice, giving you a total of 3 Ingress rule cards to fill out.
   1. Request Host: `example.com` Path Prefix: `/1` Target Service: `Kubernetes` Port: `443`
   2. Request Host: `example.com` Path Prefix: `/2` Target Service: `Kubernetes` Port: `443`
   3. Request Host: `example.com` Path Prefix: `/3` Target Service: `Kubernetes` Port: `443`
5. Click `Create` -> then you are routed back to the `Ingresses` screen
6. Now click the `ellipsis (three dots)` next to the ingress that was just created `my-ingress-test`
7. Click `Edit Config`
8. Click the `X` next to the first rule for `example.com/1` and observe the list of rules carefully
   - You will see that even though you clicked to delete `example.com/1` what appears to be deleted from the UI is `example.com/3`
9. Click `Save`
   - **Important:** Remember in the UI where you just clicked `Save` you only saw
     - `example.com/1`
     - `example.com/2`
10. Now you've been redirected back to the `Ingresses` page. If you observe the `Target` column. You'll see that `example.com/1` was actually deleted even though that's not what the UI displayed on the previous page. **See the gif under screenshots for a clear example.**

**Result**

Deleting the first rule `example.com/1` appeared to delete the last rule from the UI for `example.com/3`. However upon clicking save the desired result of deleting `example.com/1` was achieved however in a very confusing way. The attached gif shows this really well.

**Expected Result**

If I delete the 1st rule from the UI I would expect for the rule to disappear. Not the last rule from the list.

**Screenshots**

![new-rancher-issue](https://user-images.githubusercontent.com/40877149/137563110-b181232b-6f1c-4b27-9b38-4233ccecdebd.gif)

<img width="1766" alt="Screen Shot 2021-10-15 at 4 12 30 PM" src="https://user-images.githubusercontent.com/40877149/137563445-52a1eab2-91f7-4040-ac99-d8abed1511fe.png">

**Comment by gaktive** [comment]
Per Vince, this is likely Vue relying on a wrong model to present the change. Should be easy.

**Comment by vincent99** [comment]
The component being used in <v-for ...><Rule ...></v-for> probably needs a more unique `key` passed in so that Vue knows it can't reuse the existing one in this case

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-f487c8819d726109d8178894b6a4c082d5320b92-head |
| Rancher cluster type    | Single Node Docker Install                         |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | N/A                                                |
| Downstream K8s version  | N/A                                                |
| Browser type            | Google Chrome                                      |
| Browser version         | 96.0.4664.45 (Official Build) (x86_64)             |

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> click `local` -> click `Service Discovery` -> click `Ingresses` -> click `Create`
3. Fill out the Ingress form
    - Name: `mychecks`
    - Click `Add Rule` 3 times
        1. Request host: `example.com` Path: `/1` Target: `Kubernetes` Port: `443`
        2. Request host: `example.com` Path: `/2` Target: `Kubernetes` Port: `443`
        3. Request host: `example.com` Path: `/3` Target: `Kubernetes` Port: `443` 
4. Click `Create` -> then redirected back to Ingresses page
5. Click the `ellipsis (three dots)` next to the `mychecks` ingress -> click `Edit Config`
6.  Click the `X`
    - Next to this card: Request host: `example.com` Path: `/1` Target: `Kubernetes` Port: `443`
7. Observe UI behavior -> click `Save`

**Successfully working as expected now!**
