### ISSUE TITLE
UI component for KDM EKS versions

### ISSUE THREAD

**Issue by rmweir** [rancher/dashboard#4401]
**Description:**
Switch from using hard coded versions for EKS to using versions from KDM.

**Backend Issue:**
https://github.com/rancher/rancher/issues/33766

**Comment by gaktive** [comment]
Backend is ready per https://github.com/rancher/rancher/issues/33825, so the 33766 reads a duplicate.

**Comment by gaktive** [comment]
Removed placeholder from subject. At this point, the backend should be doing this automatically so we can remove our manually generated list.

**Comment by gaktive** [comment]
Sounds like the backend isn't actually ready yet, so we'll park this for now until things are good. This will mean manual updates to this list until then.

**Comment by nwmac** [comment]
Closing this as stale. Please re-open or file a new issue when backend is done.
