### ISSUE TITLE
Pass migrated annotation for apps

### ISSUE THREAD

**Issue by rmweir** [rancher/dashboard#4402]
**Description:**
Helmv3 apps that were originally made through norman and are migrated to dashboard will have an annotation added to their  `spec.chart.metadata.annotations` field. This annotation needs to be passed on upgrade if it can be found on the app similar to ui-repo and repo-type annotations. Annotation is "apps.cattle.io/migrated".

**Backend Issue:**
___note:___ backend does not need to be merged first.
https://github.com/rancher/rancher/issues/34700

**Comment by rmweir** [comment]
https://github.com/rancher/rancher/pull/35202

**Comment by nwmac** [comment]
@rmweir I'm not seeing the annotation - I create a helm 3 app from the ember UI (e.g. openebs). I then look at the app in the Dashboard UI (via Steve) and I don't see any annotations as described above.

I was expecting to see a `apps.cattle.io/migrated` annotation.

I thought from the description, if I retrieve an app created with Norman via the Steve API, I should see an annotation indicating that it has been migrated - which should then be retained when upgrading.

**Comment by rmweir** [comment]
@nwmac the annotation is one that would be added by the user as part of a manual process we are using for now to migrate apps. Can test by using kubectl to add "apps.cattle.io/migrated": "true" to an apps spec.metadata.annotations field. Then when you go to edit that apps, you'll notice the request omits the annotation from the chart.

**Comment by nwmac** [comment]
@rmweir So its a manual migration process - is this documented? So, if we see this annotation on an app, we should carry it forward when upgrading... should it also be passed through to any dependencies?

**Comment by nwmac** [comment]
@rmweir Can you clarify where the annotation should be placed? The description says `spec.chart.metadata.annotations` where as you latest comment says `spec.metadata.annotations`. 

I see 2 places the annotation could go on the app resource:

`spec.chart.metadata.annotations` 
`metadata.annotations` 

can you let me know which one it is, please.

**Comment by rmweir** [comment]
@nwmac you will find the annotation on spec.chart.metadata.annotations, when you pass it to the upgrade action it will be be charts.annotations, similar to how the other two annotations are passed.

**Comment by anupama2501** [comment]
Re-opening the issue as the following issue is seen while upgrade:
Rancher version: v2.6-head 44b8030

1. Create a cluster with 3 nodes 1 role each
2. Install the app aws-event-sources from the ember UI in the default project
3. Add the annotation via kubectl on the downstream cluster in spec.chart.metadata.annotations
```
catalog.cattle.io/ui-source-repo: helm3-library
catalog.cattle.io/ui-source-repo-type: cluster
apps.cattle.io/migrated: "true"
```
4. From the local cluster kubectl file or execute into the local cluster --> kubectl shell --> `kubectl edit apps.project.cattle.io aws-event-sources -n <ProjectIDAppInstalled>`
5. Add the annotation `cattle.io/skipUninstall: "true"` under metadata.annotations
6. Delete the aws-event-sources from the downstream cluster --> default project
7. Navigate to the explore --> Apps & market --> Installed apps --> aws-event-sources --> Edit/upgrade
8. The page won't load and a 404 response is returned:
```
baseType: "error"
code: "NotFound"
message: "apps.project.cattle.io \"aws-event-sources\" not found"
status: 404
type: "error"

```
9. Re-opening as I expected the upgrade to go through without any errors.

**Comment by nwmac** [comment]
@anupama2501 @rmweir I don't understand the use case that the set of steps represents. Can you please explain. Although related, I think this is a different issue to not passing down the annotation.

**Comment by rmweir** [comment]
@nwmac the use case is migrating from using a norman app to the dashboard app. Adding the annotation is part of this. The annotation tells rancher that certain steps need to be taken because the helm chart was originally installed with a norman app. Maybe the issue is not related to adding the annotation but the functionality that the annotation is trying to enable is unusable as long as this issue is here.

**Comment by anupama2501** [comment]
Verified on ac67f83 v2.6-head
1. Created an app aws-event on rancher serve v2.5.11 in the downstream cluster
2. Upgraded the rancher server to v2.6-head ac67f83
3. Added the following annotation to the app 
`kubectl edit apps aws-event-sources -n aws-event-sources`
5. Add the chart repo name: `helm3-libarary` , path: `https://git.rancher.io/helm3-charts` and branch: `master`.
4. Add the annotation `"cattle.io/skipUninstall": "true"` via `kubectl edit apps.project.cattle.io aws-event-sources -n <projectID> from the local cluster
5. Delete the app from the downstream cluster default project
6. Verify the app is not removed from the  apps & market --> installed apps
7. Upgraded the app and the upgrade goes through without an error.

**Comment by anupama2501** [comment]
Verified on v2.6-head e62e1ae upgraded from 2.5.11

Validated few more scenarios with respect to the above:

To migrate:
```
kubectl get apps -A | grep aws
kubectl edit apps aws-event-sources -n aws-event-sources

Add the annotation via kubectl on the downstream cluster in spec.chart.metadata.annotations
catalog.cattle.io/ui-source-repo: helm3-library
catalog.cattle.io/ui-source-repo-type: cluster
apps.cattle.io/migrated: "true"

From local cluster:
kubectl get apps.project.cattle.io -A | grep aws
kubectl edit  apps.project.cattle.io aws-event-sources -n p-mr57l

Delete the app from the ember UI:
kubectl delete apps.project.cattle.io aws-event-sources -n p-mr57l

From apps  & market place --> Repositories --> name: `helm3-library`, URL: `https://git.rancher.io/helm3-charts`, branch: `master`
```

**Uninstall post migration:**
- Migrated the app hpe-csi-driver from ember to dashboard by following the above mentioned steps
- Uninstalled the app and verified the uninstallation went through without errors

**Update the app post migration:**
- edited the app aws-event-sources by changing the default images to `false` 
- Verified the update went through as expected

**Upgraded the app post migration**
- Upgraded the app externalip-webhook from version 0.1.4 to 0.1.5 
- Upgrade went through without any errors

**Upgraded the app and uninstalled**
- From the above test case post upgrade, uninstalled the app
- App was deleted and all the workloads were removed from the project
