### ISSUE TITLE
"Welcome to rancher" dialog shown on 2.6.x when admin account does not exist

### ISSUE THREAD

**Issue by BlackthornYugen** [rancher/dashboard#4403]
**Setup**
- Rancher version: 2.6.0 & 2.6.1
- Browser type & version: Chrome/Firefox/Edge

**Describe the bug**
Deleting the admin user gives the prompt "It looks like this is your first time visiting Rancher". It looks like the problem is with [calcMustChangePassword](https://github.com/rancher/dashboard/commit/5ec2a77dcd8f13439651fbfed6754480119574dc#r58152130) but I don't see anything with a hardcoded "admin" account. 

**To Reproduce**
Delete admin user, restart rancher

**Result**
Prompted to provide bootstrap password but no bootstrap password exists. Even if you set CATTLE_BOOTSTRAP_PASSWORD it doesn't work because there is no admin account.

**Expected Result**
I expect to be prompted with a username/password dialog. If I restore to 2.5.x I can create an admin user, switch back to 2.6.x and login normally to any account because I am prompted for a username. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3138467/137609840-73e41b73-c9f6-4b4a-be3c-fabeb59b623a.png)

**Comment by BlackthornYugen** [comment]
I'm not sure that my reproduction steps actually make sense I was seeing inconsistent behaviour when I tried to delete/recreate/delete the admin account. 

I've tried the following workaround steps 3 times now and it behaves the same:

1. Restore a backup that has no admin account on 2.5.10
2. Browser 1 
  i) Log in as an admin
  ii) click away "first time login" notice
  iii) Log out
  iv) Log back in and stay signed in
3. Upgrade to 2.6.1
4. Browser 2 - Try to login to rancher but observe bootstrap message
5. Browser 1 - (Cookie is still valid from 2.5.10 auth!) Navigate to "Global -> Users", Click "refresh group memberships"
6. Browser 2 - Refresh and observe a normal sign in page.

**Comment by vincent99** [comment]
The UI for this is only predicated on the `first-login` Setting being set to true.  It doesn't know what users exist, or care because it is assumed you are doing initial setup with `admin` when it's true.  And it's then set to false by the backend after the admin's password is changed.

Are you creating users with automation outside of that flow?

**Comment by vincent99** [comment]
First-login is a single global setting, not per-user.  It is cleared by changing the password in initial setup, not literally just logging in. So you're creating this situation by having never gone through the normal setup, so just add setting it to false to your automation?  PUT /v3/settings/first-login {"value":"false"}

**Comment by BlackthornYugen** [comment]
Thanks! That works for me.

This doesn't happen when I start a new 2.6.x rancher because I've updated our tooling to change the bootstrap password before deleting the admin account. It was just happening when I was testing an automated install of 2.5.x and then upgrading. Probably doesn't make sense to make any changes for this issue so I'll close the ticket.
