### ISSUE TITLE
Add configuration for ACE on imported RKE2/K3S clusters

### ISSUE THREAD

**Issue by thedadams** [rancher/dashboard#4410]
**Detailed Description**
In order to support ACE for imported RKE2/K3S clusters, the UI should be updated to allow a user to turn it on/off and add the extra configuration, if necessary.

This should be supported in 2.6+ for imported RKE2/K3S clusters only. This should be available for newly imported clusters (in 2.6+) and clusters that were imported in < 2.6 and Rancher upgraded to 2.6+.

Depending on what is decided with the Product Team, a link to the documentation should also be included in the UI. This is necessary because there are manual steps the user must take on the downstream cluster to fully enable this feature.

**Comment by winterallen** [comment]
Upgrade the rke2 downstream cluster created by rancher with rancher v2.6.1, and prompt: "provisioning bootstrap node (s) custom XXXXXX: waiting for plan to be applied"

**Comment by thedadams** [comment]
Please also note: because of a change in the backend, the `localClusterAuthEndpoint` object has moved. It is no longer in the `rkeConfig` section; it is on the same level as the `rkeConfig`.

Therefore, this should also change for RKE2 provisioned clusters as well as imported clusters.

**Comment by gaktive** [comment]
Since Zube obscures some of the linked items, for context, ACE = *Authorized Cluster Endpoint*
Source: https://github.com/rancher/rancher/issues/35161

**Comment by vincent99** [comment]
The imported k3s/rke2 page is part of Ember and uses the Norman API, which [rejects](https://github.com/rancher/rancher/blob/aa7ab90ca918f0b23daedbf2170775dacbb34e13/pkg/api/norman/customization/cluster/validator.go#L170) attempts to set localClusterAuthEndpoint.

**Comment by thedadams** [comment]
This should be unblocked now. Specifically with [this](https://drone-publish.rancher.io/rancher/rancher/6875) drone build.

**Comment by davidnuzik** [comment]
Closing. This has been validated via https://github.com/rancher/rancher/issues/35161#issuecomment-988327601 already. In that issue I tested via manually editing management cluster object(s) and also by the UI. I encountered no issues when testing via the UI (Edit imported k3s/rke2 cluster and enable ACE via UI).
