### ISSUE TITLE
on create, StatefulSet "Service Name" required, but not marked as such. dropdown for Service Name is not populating

### ISSUE THREAD

**Issue by scoful** [rancher/dashboard#4411]
**Setup**
- Rancher version: v2.6.1
- Browser type & version: Chrome 94.0.4606.81

**Describe the bug**

on create, StatefulSet "Service Name" required, but not marked as such. dropdown for Service Name is not populating

**To Reproduce**

- `docker pull rancher/rancher:stable`
- when creating a statefulset, the Service name dropdown does not display anything
- Service name is required, but not marked with *
- I do have services in the default namespace, and was able to create a statefulset from the ember UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12808733/137881375-4dc27eb9-1b95-4d09-8ce1-2289e7e0f619.png)
![image](https://user-images.githubusercontent.com/12808733/137881633-0c99f764-706f-4ba7-9fcd-89bf19a03262.png)

**Additional context**
I found a cloesd issue #2553 , It seems that it has been fixed in v2.5, but why the v2.6 has appeared again.

**Comment by longtian** [comment]
problem confirmed still exist in v2.6.2

**Comment by glitterlip** [comment]
anyone has a fix ? When create a statefulset of rabbitmq,it requires a service name , but no matching options.

**Comment by thejordanclark** [comment]
I ran into the same.  A work around for now is to configure it then switch to the YAML editor to add the Service Name.

**Comment by slickwarren** [comment]
closing as duplicate https://github.com/rancher/dashboard/issues/4811
