### ISSUE TITLE
Logging ClusterFlows are not always created in the cattle-logging-system namespace

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#4413]
**Setup**
- Rancher version: 2.6.1
- Browser type & version: Chrome

**Describe the bug**
Logging ClusterFlows are not always created in the`cattle-logging-system` namespace.

**To Reproduce**
* Install rancher-logging
* Pick a namespace from the namespace selector, like `default`
* Go to Logging -> Cluster Flows
* Create a new Cluster Flow
* Note that there is no Namespace picker in the create form. This is correct, because ClusterFlows are namespaced, but must be in the `cattle-logging-system` Namespace in order to be picked up.

**Result**
The ClusterFlow is created in the `default` namespace.

**Expected Result**
The ClusterFlow is created in the `cattle-logging-system` namespace.

**Additional context**
For ClusterOutputs the logic is correct, and they are always created in the `cattle-logging-system` namespace, independent from the chosen Namespace in the global filter.

**Comment by ronhorton** [comment]
**Pass** verified in `2.6-head Commit ID 4199cac`

1. installed logging
2. created 2 cluster outputs
3. created 3 cluster flows which pointed to the cluster outputs

All cluster flows were created in the cattle-logging-system namespace

![Screen Shot 2022-06-08 at 4.16.21 PM.png](https://zube.io/files/rancher/79e7a949cc4f77707d4af73d6ea45b32-screen-shot-2022-06-08-at-4-16-21-pm.png)
