### ISSUE TITLE
[BUG] Incorrect memory unit conversion in project resource quota

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#4417]
Rancher 2.6.1

1. Create a project with the following resource quota assigned:
```
Memory limit: 512 MiB (Namespace default: 256 MiB)
Memory reservation: 256 MiB (Namespace default: 128 MiB)
```
2. Create a namespace in the project
3. Inspect the `resourcequota` Kubernetes resource that is created in the namespace

**Expected Result:**

Based on configured namespace default limit, a memory limit of 256 **Megabytes** and memory reservation of 128  Megabytes is configured.

**Actual Result:**

A memory limit of 256 **Bytes** and memory reservation of 128  Bytes is configured

<img width="1909" alt="incorrect-unit" src="https://user-images.githubusercontent.com/3813921/137902640-07cccf63-ac25-467e-a8f2-5e8fd931c195.png">

**Comment by brudnak** [comment]
# My checks PASSED

<hr>
  
## Validation Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.6.3-rc2                              |
| Rancher cluster type    | Docker                                  |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | RKE1 Linode                             |
| Downstream K8s version  | v1.21.6                                 |
| Browser type            | Google Chrome                           |
| Browser version         | 96.0.4664.55 (Official Build) (x86_64)  |

## Validation steps

1. Starting from the Rancher homepage `/dashboard/home`
2. Click the hamburger menu -> `Cluster Management` -> `Explore` next to an active cluster (one described in reproduction environment) -> `Project/Namespaces` from the left side menu -> `Create Project`
3. Enter a `Name` for the the project for example: `hello-world-project` -> Click `Resource Quotas` -> Click `Add Resource` **twice**
4. Now fill out the **two** resources
   1. `Memory Limit`
      - `Project Limit`: 512
      - `Namespace Default Limit`: 256
   2. `Memory Reservation`
      - `Project Limit`: 256
      - `Namespace Default Limit`: 128
5. Click `Create` -> you are then redirected back to the Clusters page. See screen shot labeled `A1` for what the network traffic was like for the `POST` request to `v3/projects`
    - :star: *The values are just being sent as `512`, `256`, & `128` with no identifiers, meaning they will be interpreted as bytes*
6. You have been redirected back to Projects/Namespaces
7. Under the newly created Project `hello-world-project` click `Create Namespace` -> enter a name `hello-world-namespace` -> click `Create` -> redirected back to Projects/Namespaces
8. Click `Kubectl Shell` and run the following commands
   - `kubectl get ns`
   - `kubectl get quota -n hello-world-namespace`
9. Observe the output listed directly below
```shell
> kubectl get quota -n hello-world-namespace 
NAME            AGE   REQUEST                       LIMIT
default-tz6k2   16m   requests.memory: 64Mi/128Mi   limits.memory: 64Mi/256Mi
```
10. Click `Workload` from the left side menu -> `Deployments` -> `Create`
11. Create deployment **USING THE NEWLY CREATED NAMESPACE**
       - Name: `hello-world-deployment`
       - Namespace: `hello-world-namespace`
       - Container Image: `brudnak/hello-rancher-golang`
       - :star: Resources - Memory Reservation: `64`
       - :star: Resources - Memory Limit: `64`
12. Click `Create` 
13. You are then redirected back to Deployments, everything is successful now
