### ISSUE TITLE
E2E: Create test to catch regressions in side nav behaviour

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4425]
For the in-cluster experience we had this bug - https://github.com/rancher/dashboard/issues/4358

We create e2e tests to test the various behaviour of the side nav so we don't hit this again.

**Comment by gaktive** [comment]
@cnotv suspects that we have this test already. He'll check but we need to confirm whether they align with the overall goal here of ensuring that we can click on headers.

**Comment by cnotv** [comment]
We definitely have side-nav tests already in place and have been there even before me: https://github.com/rancher/dashboard/tree/master/cypress/e2e/tests/navigation/side-nav

Just a disclaimer: using E2E tests for unit tests may be way more time consuming, especially for maintaining changes. We already had the case with the language, which has been simply disabled at the first occurrence.

**Comment by nwmac** [comment]
Closing as this is not specific enough.
