### ISSUE TITLE
Selecting monitoring dashboard form sub-level view item doesn't always function properly

### ISSUE THREAD

**Issue by Auston-Ivison-Suse** [rancher/dashboard#4427]
**Setup**
- Rancher version: v2.6.2-rc1
- Browser type & version: chrome: 94.0.4606.61
- HA cluster with MonitoringV2 installed

**Describe the bug**
Selecting monitoring from one of its sub-level items occasionally doesn't bring you back to the monitoring dashboard 

**To Reproduce**
1. from the hamburger menu select monitoring to get to the monitoring dashboard
2. select either of the sub-level items (Monitors, Routes and Receivers)
3. Switch between those two options and Monitoring until you notice the bug

**Result**
Selecting Monitoring is unresponsive and doesn't bring you to the Monitoring Dashboard.

**Expected Result**
Land on the monitoring dashboard.

**Screenshots**

https://user-images.githubusercontent.com/89411550/137977972-0fd72fb0-5563-4b74-83a9-2b0df33b83e9.mp4

(You can see the bug occur around 16 seconds, reflected by the moving of my mouse)

**Comment by mantis-toboggan-md** [comment]
This should be fixed by this PR: https://github.com/rancher/dashboard/pull/4672

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Reproduction**
- rancher version: v2.6.2
- Browser type & version: Chrome Version 95.0.4638.69
- RKE1 cluster, k8s: v1.21.6

**Steps To Reproduce**
1. from the hamburger menu select monitoring to get to the monitoring dashboard
2. select either of the sub-level items (Monitors, Routes and Receivers)
3. Switch between those two options and Monitoring until you notice the bug

**Setup For Validation**
- rancher version: v2.6-head(0d14421)
- Browser type & version: Chrome Version 95.0.4638.69
- RKE1 cluster, k8s:  v1.22.4

**Steps To Validate**
1. from the hamburger menu select monitoring to get to the monitoring dashboard
2. select either of the sub-level items (Monitors, Routes and Receivers)
3. Switch between those two options and Monitoring

**Result**
There is no issue with the selection of monitoring lagging behind.
