### ISSUE TITLE
Navigating to workloads from installed apps in apps&marketplace in a cluster is not working after selecting a namespace in ns picker

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4428]
Setup

Rancher version: 2.6.2-rc1
Browser type & version: Chrome

**Describe the bug**
When we are in installed apps in apps & marketplace in a cluster explorer, when a namespace is selected in the namespace picker and if we try to select workloads on the left hand navigation, it stays in the installed apps and doesn't take us to the workloads tab.

**To Reproduce**
1. Create a downstream cluster 1 node all roles
2. From the explore cluster, navigate to the apps& marketplace --> installed apps.
3. In the namespace picker, select istio-system or cattle-monitoring-system namespace or any namespace
4. Click on `Workload` tab 

**Result**
We are not taken to the workload tab but stay in the installed apps.

**Expected Result**
Expected to land in workload tab when the workload tab is selected.

**Screenshots**
https://user-images.githubusercontent.com/38144301/137978817-ba8d5753-8633-43a4-8a98-c57582964d74.mov

**Additional context**
workaround: If we select all namespaces then we can go to the workloads tab.

**Comment by gaktive** [comment]
Not a blocker for 2.6.2. May require a release note.

**Comment by richard-cox** [comment]
@rak-phillip Has all the work for this now been completed, if so can it go for testing?

**Comment by rak-phillip** [comment]
@richard-cox yep, it's been merged. Moved to `To Test`

**Comment by anupama2501** [comment]
Verified on v2.6.3-rc1

1. Created a node driver rke1 with 1 etcd,1cp,1 worker
2. Verified by navigating to the apps & market --> installed apps and selected a namespace
3. Clicked on workload tab and landed in workload tabs.
4. Navigated back to apps & market and landed in the apps tab
