### ISSUE TITLE
Dashboard doesn't handle cluster disconnect gracefully

### ISSUE THREAD

**Issue by cmurphy** [rancher/dashboard#4432]
**Setup**
- Rancher version: 2.6-head
- Browser type & version:

**Describe the bug**

If a cluster agent becomes disconnected and then the UI subsequently tries to make a proxy request to the cluster, the backend will return a 500 error. In the Ember UI, if the user is viewing an active cluster and then refreshes after the cluster has disconnected, the UI handles it gracefully by kicking the user back out to the global cluster screen and presenting an error modal in the top right corner. In the Vue UI, the user sees the fail-whale screen with the 500 error and the raw JSON error message. This is less friendly and makes it seem like there's something wrong with the Rancher server itself and not just the cluster.

**To Reproduce**

1. In Cluster Explorer, click into a downstream cluster.
2. Using kubectl, scale down the cluster agent to 0:

```
$ kubectl -n cattle-system scale deploy cattle-cluster-agent --replicas=0
deployment.apps/cattle-cluster-agent scaled
$ kubectl -n cattle-system get pod
No resources found in cattle-system namespace.
```

3. Back in the UI, hard refresh.

**Result**

The UI produces a fail-whale screen with the raw error message:

![image](https://user-images.githubusercontent.com/1220710/138135599-560c0707-f2c9-4b3f-91ef-8c245409662b.png)

**Expected Result**

The old UI handles the 500 errors by kicking you back to the global clusters screen and showing an error modal:

![image](https://user-images.githubusercontent.com/1220710/138140073-4b7aee07-10c1-442c-97ba-e5f26eb75494.png)

It's not obvious that there was a 500 error unless you're actually looking at the requests.

**Screenshots**

**Additional context**

The 500 error is more likely to be triggered during an upgrade because of a race condition which is addressed in [this backend issue](https://github.com/rancher/rancher/issues/34190).

**Comment by richard-cox** [comment]
Closing this in favour of #5529 (new number, but older issue). This has nicer steps to reproduce though, and suggestion for end result
