### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by jameskypee** [rancher/dashboard#4441]
**Setup**
- Rancher version:  2.5.9
- Browser type & version:

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**
<html>
<body>

level=info ts=2021-10-25T09:46:03.444Z caller=node_exporter.go:178 msg="Starting node_exporter" version="(version=1.1.2, branch=HEAD, revision=b597c1244d7bef49e6f3359c87a56dd7707f6719)"
--
Mon, Oct 25 2021 5:46:03 pm | level=info ts=2021-10-25T09:46:03.444Z caller=node_exporter.go:179 msg="Build context" build_context="(go=go1.15.8, user=root@f07de8ca602a, date=20210305-09:29:10)"
Mon, Oct 25 2021 5:46:03 pm | panic: Couldn't create metrics handler: couldn't create collector: failed to open procfs: could not read "/host/proc": stat /host/proc: permission denied
Mon, Oct 25 2021 5:46:03 pm |  
Mon, Oct 25 2021 5:46:03 pm | goroutine 1 [running]:
Mon, Oct 25 2021 5:46:03 pm | main.newHandler(0x1, 0x28, 0xd0fcc0, 0xc000117cb0, 0x0)
Mon, Oct 25 2021 5:46:03 pm | /app/node_exporter.go:64 +0x317
Mon, Oct 25 2021 5:46:03 pm | main.main()
Mon, Oct 25 2021 5:46:03 pm | /app/node_exporter.go:184 +0x1052

</body>
</html>

**Comment by richard-cox** [comment]
No additional information supplied.
