### ISSUE TITLE
Rancher suggests users upgrade the k3s-packaged Traefik chart, breaking ingress

### ISSUE THREAD

**Issue by brandond** [rancher/dashboard#4442]
Copied from https://github.com/rancher/partner-charts/issues/220 for visibility.
---

A recent PR added a Traefik chart to partner-charts:
* https://github.com/rancher/partner-charts/pull/205

K3s also packages Traefik. If you go into `Installed Apps` in `Apps and Marketplace`, there is an option to update it:
![image](https://user-images.githubusercontent.com/370103/138527097-842c0f2c-59e6-4d23-97d5-627fa0a7b4d7.png)

If the user clicks through the new version, the chart upgrade will succeed, but the traefik pod will go into ImagePullBackoff because the tag used by version 10.6.0 of the chart (v2.5.3) is not mirrored in the rancher Docker Hub org. This will leave the ingress broken and (if it is being used to access Rancher) lock the user out of Rancher. At this point the user would have to either restart k3s (so that the packaged chart is reinstalled), use kubectl to fix the deployment image tag, or helm to roll back the chart update.

I believe that the Rancher UI should not offer upgrades to K3s or RKE2 packaged components. Especially not on the local cluster.

Originally reported on Users Slack at https://rancher-users.slack.com/archives/C3ASABBD1/p1634871651031000

**Comment by rak-phillip** [comment]
@brandond do you have any repro steps for getting to a state where kube-system traefik will prompt for update? I'm having issues replicating, but I suspect that I'm missing something in my setup

**Comment by brandond** [comment]
Shouldn't take anything more than simply installing Rancher 2.6 on K3s.

**Comment by gaktive** [comment]
@brandond per https://github.com/rancher/dashboard/pull/4621#issuecomment-976954111, the UI team would like a new annotation so that this would work without having to update this chart with workarounds:

>  It looks like k3s added [ab]using the bundle-id annotation to the k3s charts, so why do we need to add looking at hidden? I don't love forever abusing both of these to have a new meaning of "it's not really fleet but we want it to be treated as not-upgradable" vs adding a new descriptive annotation to explicitly disable upgrade.

> There are other ways to handle the existing installs, like applying a new annotation to the apps you're worried about during the upgrade, or just ignoring the problem of existing ones and fixing it going forward.

Is that doable at the backend? If so, would you like an issue filed to work on that?

**Comment by gaktive** [comment]
Filed https://github.com/rancher/rancher/issues/36350 with backend since no update from question in comments.

@MKlimuszka I put an `area2` label on that item with 2.6.4 as the milestone. Hopefully this is as easy as what's in the other charts though I know it's a longstanding thing that's been around.

**Comment by Jono-SUSE-Rancher** [comment]
Hey @gaktive - just a heads up, team 2 is going to be @Sahota1225. I am talking with her now and she is going to triage it with the team and consider it for v2.6.4.

**Comment by brandond** [comment]
This has been fixed for the single chart that K3s packages, but on the RKE2 side our chart building process is a bit more complex and it hasn't been addressed yet.

**Comment by gaktive** [comment]
Backend work moved over to Team 3.

**Comment by gaktive** [comment]
Based on discussion, we should expect 2 new tickets: one for k3s to create a new annotation (`catalog.cattle.io.managed=true` or something of that ilk), which should unblock UI work, and another for RKE2 to take that annotation to then edit the bundled charts.

@PennyScissors will do the k3s ticket, which would then spawn the rke2 work via @brandond

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/a478def06ee49ff6f36c37c0444c550ef82a9c67.

**ENVIRONMENT DETAILS**
- Linode Ubuntu 20.04 VM
- Docker install: 20.10
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/a478def06ee49ff6f36c37c0444c550ef82a9c67
K3s version: v1.22.8+k3s1

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher `v2.6-head` and navigated to Rancher UI home page > Create.
2. Toggled RKE1 to RKE2/K3s and chose Linode node driver to create a K3s cluster.
3. Navigated to top-left dropdown menu > newly created K3s cluster > Apps > Installed Apps.
4. Verified that Rancher is not prompting upgrades for any of the installed K3s apps:
![image](https://user-images.githubusercontent.com/52591819/164563237-4907d508-b507-4b4f-9889-2f15a7840ef1.png)
5. Repeated steps 2-5, but for a Rancher-created RKE2 cluster. I see the below:
![image](https://user-images.githubusercontent.com/52591819/164564573-5cff69ab-a419-45fe-92c7-4bc4f04726a0.png)

As noted in the earlier comments, there will be separate issues to address adding annotations to further enhance this experience, but the original issue has been addressed and verified.
