### ISSUE TITLE
"Drain Before Delete" support for RKE2 machine pools

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4448]
**Detailed Description**
For RKE1-provisioned clusters, there is currently an option to specify whether nodes should be drained before deletion for each node pool:
![image](https://user-images.githubusercontent.com/85187633/138793914-23651cd1-89ca-4f1c-b2d4-dc594ab03c8f.png)

For RKE2-provisioned clusters, we want the same functionality to be available, probably by adding a checkbox somewhere on the base pool details section highlighted below:
![image](https://user-images.githubusercontent.com/85187633/138794310-64fa0386-30a8-4db6-a58e-d8da6e4edc5b.png)

**Context**
This is needed for RKE2 provisioning parity with RKE1

**Additional Details**
Backend support is needed: https://github.com/rancher/rancher/issues/35274

**Comment by snasovich** [comment]
Backend changes done per https://github.com/rancher/rancher/issues/35274, should no longer be blocked by backend. If clarifications are needed, please contact @jakefhyde who implemented backend changes (there is a good summary [here](https://github.com/rancher/rancher/issues/35274#issuecomment-1009384001)).

**Comment by ronhorton** [comment]
**PASS** verified in `2.6-head Commit ID cd3c9d7`

1. created downstream rke2 cluster
2. 'drain before delete' is available now for rke2
3. brought up cluster
4. checked logs - no errors
5. deleted cluster
6. cluster was deleted & removed from downstream provider

**Comment by sowmyav27** [comment]
Reopening to test a few more scenarios

**Comment by anupama2501** [comment]
Verified on v2.6-head 8c785a1 as part of this issue:
https://github.com/rancher/rancher/issues/35274#issuecomment-1049493500

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
