### ISSUE TITLE
"Auto Replace" option support for RKE2 machine pools

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4449]
**Detailed Description**
For RKE1-provisioned clusters, there is currently an option to specify the threshold on how many minutes a node can be unreachable in a node pool before it's automatically replaced:
![image](https://user-images.githubusercontent.com/85187633/138795610-3dead8ba-c110-41ae-9deb-824d63fb63ac.png)

For RKE2-provisioned clusters, we want the same functionality to be available, probably by adding a checkbox somewhere on the base pool details section highlighted below:
![image](https://user-images.githubusercontent.com/85187633/138795652-c52990d1-c116-446f-b4ea-c676fc1c210f.png)

**Context**
This is needed for RKE2 provisioning parity with RKE1

**Additional Details**
Backend support is needed: https://github.com/rancher/rancher/issues/35275

**Comment by paynejacob** [comment]
ref https://github.com/rancher/rancher/issues/35275

**Comment by paynejacob** [comment]
See https://github.com/rancher/rancher/pull/35916#issue-1083643527 for implementation

Support for self healing node pools was added with the pr above. The following fields were added to support this.

related: https://cluster-api.sigs.k8s.io/tasks/healthcheck.html

- NodeStartupTimeout `*metav1.Duration` (Duration of time the node is given to initially become ready before it is replaced.)
- UnhealthyNodeTimeout `*metav1.Duration` (How long a node can be unhealthy before it is replaced)
- MaxUnhealthy `*intstr.IntOrString` (The maximum number of nodes that can be un healthy in a pool, if this is exceeded no nodes are replaced)
- UnhealthyRange `*string` (A range of nodes that can be unhealthy and replaced see https://cluster-api.sigs.k8s.io/tasks/healthcheck.html#unhealthy-range for formatting)

**Comment by gaktive** [comment]
Thanks @paynejacob -- does this mean that UI can being work on this as QA tests the backend?

**Comment by paynejacob** [comment]
@gaktive yes qa can test backend and the ui work can start.  Let me know if you have any questions about the api.

**Comment by catherineluse** [comment]
@paynejacob It looks like the UI just needs to include the `UnhealthyNodeTimeout` property when creating the node pool. Do we need to send it with an uppercase U? does it matter? I noticed that we don't capitalize the other properties that we send when creating the node pool.

https://github.com/rancher/rancher/pull/35916/files#diff-e05181e81036cad4014bb4843ea91837fa7dd238dc3434bc4fcc598c56db6428R26

**Comment by paynejacob** [comment]
@catherineluse it looks like I accidently capitalized it, I will have a  pr up soon to make it lowercase.

**Comment by paynejacob** [comment]
@catherineluse fixed

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Feature Testing**
Rancher Version: v2.6-head(e55a04c)

**Steps for Reproduction: **
1. Start creating a node driver rke2 cluster
2. go to the advanced settings and you will see the option in the screenshot below: 

![AutoReplace.png](https://zube.io/files/rancher/8926765fe9f8932e6e5935e629b47e17-autoreplace.png)

**Result**
Was able to successfully view the noted amount post provisioning.

**Sanity Checks**

- successfully provisioned cluster
- successfully edited the yaml to change the values before provisioning. 
- successfully edited the values post provisioning via ui
- successfully edited the values post provisioning via yaml

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
