### ISSUE TITLE
[FEATURE] better loadblancer config of Harvester cloud provider

### ISSUE THREAD

**Issue by guangbochen** [rancher/dashboard#4451]
**Is your feature request related to a problem? Please describe.**
1. Create a guest k8s cluster via the Harvester node driver e.g rke2 with the Harvester cloud provider enabled.
2. Wait for the cluster to be ready and create a new service with the type of `loadbBalancer`.
3. Currently, users have to use annotations to config those cloud provider configs, we should add a better UX integration of it on the Rancher dashboard.

https://docs.harvesterhci.io/v0.3/rancher/cloud-provider/#load-balancer-request-parameters

<img width="1789" alt="lb-svc" src="https://user-images.githubusercontent.com/4569037/137464552-13d4ae38-4293-4774-8f85-d35949ddc555.png">

**Comment by gaktive** [comment]
There was discussion about getting this in for 2.6.3 but since the backend isn't complete and a ballpark estimate on the UI side looked long, I'm pushing this to the next version.

@nwmac just so this is on your radar.

**Comment by guangbochen** [comment]
@gaktive sorry for the confusion, but since the Harvester UI team is already working on this feature and should have the PR ready for review soon, can we still target it for v2.6.3, thanks.

**Comment by gaktive** [comment]
For @richard-cox, this may be simply be another PR review.

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/1435#issuecomment-966012444

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
