### ISSUE TITLE
Projects in "Group by Project" view are duplicated

### ISSUE THREAD

**Issue by cmurphy** [rancher/dashboard#4455]
**Setup**
- Rancher version: 2.6-head (6f82949c)
- Browser type & version: Chrome and Firefox

**Describe the bug**

When viewing projects under EXPLORE CLUSTER -> cluster name -> Projects/Namespaces, using the default "Group by Project" view, projects that have namespaces in them are listed twice, first with their associated namespaces and then without namespaces.

**To Reproduce**

- Visible on the local cluster with the default projects: Default and System projects will appear, then "Not in a Project", then System and Default projects again with no namespace in them.
- Create a new project, see it appear with no namespaces near the bottom of the list. Add a namespace to it, see it move toward the top with the new namespace, but also still appear near the bottom without a namespace.

**Result**

Projects appear to be duplicated. Also, trying to delete one of the extra ones results in the actual project being deleted on the backend.

The Flat List view is normal.

**Expected Result**
Projects should not be duplicated.

**Screenshots**
![image](https://user-images.githubusercontent.com/1220710/138976497-a8313865-e2c1-435e-8056-ccb8e821040a.png)

**Additional context**

The projects are not duplicated in the backend:

```
$ kubectl -n local get projects
NAME      AGE
p-jhbc4   52m
p-jmbgl   16m
p-zw2zj   52m
$ kubectl -n local get projects -o jsonpath='{.items[*].spec.displayName}'
System p1 Default
```

**Comment by Shavindra** [comment]
This code was added from ember. I don't think this is needed anymore? removing `...fakeRows` fixes the issue.

https://github.com/rancher/dashboard/blob/master/pages/c/_cluster/_product/projectsnamespaces.vue#L84-L96

@codyrancher can you clarify?

**Comment by codyrancher** [comment]
@Shavindra The ResourceTable is showing namespaces that are grouped by project.

We needed to show projects that didn't have any namespaces yet so we put in a fake namespace (effectively a sentinel value) so we can still show the project as a group.

Visually, it's so we can show these empty projects at the bottom:
![image](https://user-images.githubusercontent.com/55104481/141151492-d9279dec-6d08-427a-a533-21a838eed24e.png)

**Comment by richard-cox** [comment]
I'm bringing this one in to 2.6.3, the work is done and it's an extremely visible bug

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `eb3f1e6`**

Projects are _not_ seen duplicated.
