### ISSUE TITLE
Only User Namespaces filter inactive

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4459]
**Setup**
- Rancher version: 2.6.2
- Browser type & version: Google Chrome 89.0.4389.90 (Official Build) (64-bit)

**Describe the bug**
After SUSE Rancher 2.6.2 deployment Only User Namespaces filter for workloads did not work.

**To Reproduce**

**Result**
Workloads in all namespaces are listed.

**Expected Result**
Filter should be active.
I deleted the filter and reset, it then worked as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/86831399/139064226-7d375170-fe21-44d1-9742-d1efd264c895.png)

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment]
This has been fixed, I can't find the specific PR but there were some changes / improvements within this area. I've also tested this locally on the current `2.6-head` and the `Deployments` page updates correctly when changing to `Only User Namespaces`

**Comment by sowmyav27** [comment]
On 2.6-head commit id: `2a7857d`

This is seen fixed.
![Screen Shot 2021-12-14 at 7.52.22 PM.png](https://zube.io/files/rancher/662228ffa3b928798a8e2b61c00e6aa5-screen-shot-2021-12-14-at-7-52-22-pm.png)
