### ISSUE TITLE
Error on page when clicking through cluster name link - "Cannot set property annotations of [object Object] which only has a getter"

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#4462]
**Setup**
- Rancher version: `2.6-head commit ID 663df43`
- Browser type & version: `Chrome` Version 94.0.4606.81 (Official Build) (x86_64)

**Describe the bug**
When the user clicks the name of cluster link in cluster management page error is shown in UI: **{ "message": "Cannot set property annotations of [object Object] which has only a getter", "statusCode": 500 }**

**To Reproduce**
1. Create a do cluster - one node
2. Create an ec2 cluster - 3w, 1c, 3e
3. When clusters are active, click the href for the cluster's name on the 'cluster management page`

**Result**
Error: **{ "message": "Cannot set property annotations of [object Object] which has only a getter", "statusCode": 500 }**
<img width="980" alt="Screen Shot 2021-10-27 at 12 29 55 PM" src="https://user-images.githubusercontent.com/89212856/139108171-ae0aeb62-a4f5-4cea-b301-0c8b9a83e32f.png">

**Expected Result**
page loads with no error
**Screenshots**

<img width="1011" alt="Screen Shot 2021-10-27 at 11 49 58 AM" src="https://user-images.githubusercontent.com/89212856/139108425-69a0f522-2377-4012-bb65-aae33c5847df.png">

<img width="980" alt="Screen Shot 2021-10-27 at 12 29 55 PM" src="https://user-images.githubusercontent.com/89212856/139108454-2abaf161-6d12-4793-86ed-3c46d9ddef45.png">

**Additional context**

Error in console: 
`resource-class.js:238 Uncaught (in promise) TypeError: Cannot set property annotations of [object Object] which has only a getter
    at new e (resource-class.js:238)
    at t.<anonymous> (app.3cb066b8fc6bb8c564a0.js:2)
    at new t (app.3cb066b8fc6bb8c564a0.js:2)
    at t.<anonymous> (app.3cb066b8fc6bb8c564a0.js:2)
    at new t (app.3cb066b8fc6bb8c564a0.js:2)
    at t.<anonymous> (app.3cb066b8fc6bb8c564a0.js:2)
    at new t (app.3cb066b8fc6bb8c564a0.js:2)
    at n.classify (classify.js:37)
    at $ (mutations.js:79)`

**Detailed Description**

**Context**

**Comment by mantis-toboggan-md** [comment]
@ronhorton I struggled to reproduce this error; however, PR #4506 (now merged) should address any 'cannot set property ... which only has a getter' errors

**Comment by ronhorton** [comment]
**PASS** Verified `Fixed` in `2.6-head Commit ID e655fd8`

1. created a digital ocean cluster with 1 node
2. created an ec2 cluster with 3 nodes
3. once clusters were active, on manage clusters page clicked href to do cluster
4. clicked hamburger>manage clusters
5. clicked href to ec2 cluster from the cluster management page

RESULT: `No errors when clicking through the link. Machine pools showed on click-thru as expected.`
