### ISSUE TITLE
On refresh, rancher does not load page with error in console: Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#4463]
**Setup**
- Rancher version: `2.6-head Commit ID 663df43`
- Browser type & version: `Chrome` Version 94.0.4606.81 (Official Build) (x86_64)

**Describe the bug**
I clicked refresh from the cluster information page and the app didn't refresh. In the console, I observed this error:
`app.ae0dac4847d121ff8b18.js:2 Uncaught ReferenceError: require is not defined
    at Module.3840 (app.ae0dac4847d121ff8b18.js:2)
    at o (bootstrap:84)
    at Object.<anonymous> (axios.js:2)
    at o (bootstrap:84)
    at Object.<anonymous> (index.js:20)
    at o (bootstrap:84)
    at Object.<anonymous> (client.js:20)
    at Object.<anonymous> (app.6a8481efe4d118d7072e.js:2)
    at o (bootstrap:84)
    at Object.<anonymous> (app.6a8481efe4d118d7072e.js:2)`

**To Reproduce**
1. Installed logging chart in an RKE1 cluster (100.0.1 3.15.0) - may not be related to the error, but it's what I was doing
2. After install, clicked refresh on page

**Result**
app never refreshes. page shows the initial load spinner on an otherwise blank page. 
**Expected Result**
rancher refreshes

**Screenshots**
<img width="1594" alt="Screen Shot 2021-10-27 at 3 01 56 PM" src="https://user-images.githubusercontent.com/89212856/139130015-a21c2f18-3ecd-47f3-8052-278f97ddce24.png">

**Additional context**
This is a docker install with one do cluster and one ec2 cluster. 
1. I modified the URL to https://my rancher ip/dashboard/ and got the same error in the console. Page did not load.
2. I opened a new browser and tried to access with my rancher IP, same error. 
3. stopped docker and restarted - error in docker log: 'Waiting for server to become available. Connection refused"
4. hard refresh doesn't work, either. 
This isn't easy to recover from, whatever it is. 

**Detailed Description**

**Context**

**Comment by sowmyav27** [comment]
Reopening for QA Validation

**Comment by ronhorton** [comment]
**PASS** verified Fixed in `2.6-head Commit ID 931a0f0`
1. logged in 
2. installed logging chart
3. refreshed page
4. uninstalled logging chart
5. refreshed page
6. installed latest logging chart

Result: `The issue logged in this ticket, blank page after a refresh, is no longer occurring.`
