### ISSUE TITLE
When creating/saving a GKE cluster validation for nodepools with same name does not happen

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4465]
If this is a UI issue, please file an issue at https://github.com/rancher/dashboard/

**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `0ab00d7`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: 1.20
- Cluster Type (Local/Downstream): Downstream - GKE v2

**Describe the bug**
When creating/saving a GKE cluster validation for nodepools with same name does not happen

**To Reproduce**

- Deploy a GKE v2 hosted cluster.
- Have two nodepools with same name.
- Create/Save cluster details
- No error is seen during creation.
- Error seen on cluster after deployment: `Cluster [c-mf29m] cannot have multiple nodepools with name <nane>`
- Edit cluster, user does not have access to edit the nodepool name, but has to delete one and add another one.

**Expected Result**
When creating with same nodepool names, Error should be seen and not allow user to save details

**Comment by nwmac** [comment]
This is the same as another issue around allowing node pools with the same name - note that this is in the Ember UI

**Comment by markusewalker** [comment]
Still reproducing the original issue in `v2.6-head` https://github.com/rancher/rancher/commit/c47178eb1457a7ff1aac135c86d3627dc971b704.

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/c47178eb1457a7ff1aac135c86d3627dc971b704
- Browser: Chrome

**TEST RESULT**
FAIL

**REPRODUCTION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Provisioned a downstream RKE1 node driver cluster.
3. Added a new node template and ensured that both name prefixes are the exact same; verified that an error does occur:
![image](https://user-images.githubusercontent.com/52591819/180291566-7f1e95f3-7f15-4f3d-8d5e-a798e152166e.png)
4. Exit out of RKE1 cluster provisioning and provision a hosted GKE cluster.
5. Filled out the options and when I got to the `Node Pools` section, added a new node pool with the same name as the first one; there is still no validation that occurs and the cluster creates.
6. After some time, I received the following error message:
![image](https://user-images.githubusercontent.com/52591819/180291483-b451f3a6-7627-4e87-bb45-04f190af7d4d.png)
7. Removing the additional node pool and attempting provisioning again, I am able to successfully provision the hosted GKE cluster:
![image](https://user-images.githubusercontent.com/52591819/180291423-53b2aece-58f7-4118-baab-846741c74793.png)

**Comment by markusewalker** [comment]
While this issue awaits a fix, here is the QA test plan:

**TEST PLAN**
1. Setup Rancher and navigate to the UI in a browser.
2. Provision a downstream RKE1 node driver cluster.
3. Add a new node template and ensure that both name prefixes are the exact same; verify if an error occurs.
4. Exit out of RKE1 cluster provisioning and provision a hosted GKE cluster.
5. Fill out the options and when you get to the `Node Pools` section, add a new node pool with the same name as the first one; verify if there is any validation that occurs.
6. Create the GKE cluster and validate if the cluster successfully provisions.

**Comment by IsaSih** [comment]
This issue was tested on [#9987](https://github.com/rancher/dashboard/issues/9987)
