### ISSUE TITLE
Rancher UI auth redirect does not preserve destination URL

### ISSUE THREAD

**Issue by oxr463** [rancher/dashboard#4478]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

> If you visit a deep link in the Rancher UI, such as `https://rancher.local/p/local:p-9s4vd/workloads`, and your browser does not yet have a valid authentication cookie, the Rancher UI will redirect you to the login page. In our case, this is AzureAD, so you click that button and perform your login.

**Result:**

> After the login completes, you end up at the Rancher homepage, NOT at the deep link you started with. Somewhere in the authentication process, the original URI is lost.

> The expected behavior is that Rancher remembers the URL you were originally trying to reach, and after the authentication phase is complete, redirects you to that page.

**Other details that may be helpful:** N/A

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6
- Installation option (single install/HA): Either

gz#16096

**Comment by gaktive** [comment]
Internal ref: 2881

**Comment by phillipsj** [comment]
I navigated to a deep link, then opened a private browser tag which required signing in. I was redirected to the original destination.

**Comment by sowmyav27** [comment]
Verified on latest 2.6-head
