### ISSUE TITLE
Storybook: modal/dialog user guideline

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#4482]
We've had several dialog boxes implemented with no real guidance on when it is appropriate and what actions a user should anticipate a modal vs new page vs drawer:

https://github.com/rancher/dashboard/tree/master/components/dialog

This should be evaluated and written out in storybook so the use of them is less random and more clear for when and how to implement.

**Comment by catherineluse** [comment]
Based on conversations in Slack it sounds like the tentative guidance is that a modal is ok in these cases:

- When you need to maintain context of a larger process, such as when you need to do some sub-task in the middle of something else
- Secondary actions from the action menu such as rolling back a workload
- "Are you sure" confirmations such as confirming deletions

But modals should be avoided in these cases:

- Creating and editing resources
- Telling the user after they click a button/link that they don't have permission to use it. Instead the item should appear disabled so the user doesn't click it in the first place

**Comment by kwwii** [comment]
When someone creates a storybook for our modal dialog they should include the information from the design system.

**Comment by richard-cox** [comment]
Closing given https://github.com/rancher/dashboard/issues/8207
