### ISSUE TITLE
Branding Config: Allow header/footer text size to be configured

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4502]
Go to: Top Menu -> Global Setting -> Branding.

You can configure a header and footer to be shown on every page in the UI:

![image](https://user-images.githubusercontent.com/1955897/140072491-189d11ea-d6f9-47d2-ab8e-a6543fb00ca8.png)

This ticket is about allowing the text size of the text shown in the header/footer to be configured.

We should add a 'Text Size' field (alongside Text Alignment and Text Direction) that allows the user to choose between:

- Extra Small (10px), Small (12px), Medium (14px), Large (16px), Extra Large (18px), Largest (20px)

We should show the labels in a drop down and use the pixel sizes show in the brackets.

We'll need to change the component that allows the config to be set and also the component that renders the header/footer - you should be able to follow the code to see how some of the current parameters are managed.

**Comment by ronhorton** [comment]
**PASS** verified in `2.6-head Commit ID cd3c9d7`

Hamburger menu > global settings > branding 

`font size drop downs are present`

![Screen Shot 2022-01-12 at 6.07.05 PM.png](https://zube.io/files/rancher/988a0d08fb6319de75e3e682ac698299-screen-shot-2022-01-12-at-6-07-05-pm.png)
