### ISSUE TITLE
Support for Azure image Purchase Plan field

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4503]
**Detailed Description**
New `plan` field is being added to the backend as per https://github.com/rancher/machine/pull/122 and https://github.com/rancher/rancher/pull/35350 and it would be beneficial for the UI to expose this new (optional) field.

Ideally we want UI-side format validation for this new fields as it's in `<publisher>:<product>:<plan>` format.

This will need to be added to both RKE1 and RKE2 case, so both Ember and Vue UIs are affected.
For the RKE1 case it's suggested to add this field to the "Placement" section:
![image](https://user-images.githubusercontent.com/85187633/140149888-8e5421bf-f0ea-48b3-9e60-9f5eec7a0986.png)

For the RKE2 case, I can't access this UI due to not having working Azure credentials at this time, so no recommendation on the location (probably under the "Advanced" collapsible section as it's a new rarely used option?).

**Context**
The rationale here is to support the field added on the backend to the UI.

**Comment by snasovich** [comment]
Backend changes are done on v2.6-head, I can see this new `plan` field on both `azuremachinetemplates.rke-machine.cattle.io` CRD (for RKE2) and on the `v3/schemas/azureconfig` schema (for RKE1).

**Comment by codyrancher** [comment]
@snasovich I don't see plan in 2.6-head in either schema.

![image](https://user-images.githubusercontent.com/55104481/140828297-3164a455-f174-4406-9928-9532a26f53dd.png)

![image](https://user-images.githubusercontent.com/55104481/140827787-e1095a7f-458c-407f-ad35-42a483bd20d6.png)

![image](https://user-images.githubusercontent.com/55104481/140828216-2b0ffb4b-7246-474d-9269-3e9b462d071e.png)



I have created the PRs that add the fields to both ember and vue. Here's how it looks.
![Screenshot from 2021-11-08 15-12-51](https://user-images.githubusercontent.com/55104481/140828643-a0d173bd-6b58-4edc-9be7-eedd341e1ca0.png)
![Screenshot from 2021-11-08 15-12-55](https://user-images.githubusercontent.com/55104481/140828644-2a1048b4-35ef-4143-b0d8-0dea0e004279.png)

**Comment by snasovich** [comment]
@codyrancher , any chance you different versions of Rancher running on ports 8443 and 8005? The screenshot with the version is from the former while the schemas are from the latter.
I just did Docker run of Rancher `v2.6-head` and it has plan on both schemas:
![image](https://user-images.githubusercontent.com/85187633/141017108-63109aeb-be80-4f4f-8785-192ca4ab9e4d.png)
![image](https://user-images.githubusercontent.com/85187633/141017165-035e402f-6b5d-4348-9b23-42fe6e078d9b.png)

**Comment by codyrancher** [comment]
@snasovich 8005 points to 8443 so there isn't a difference. I'll go ahead and pull 2.6-head again and see if plan is now present.

**Comment by codyrancher** [comment]
The latest has it so we're good.

**Comment by brudnak** [comment]
## ❌  Blocking Problem - Can't Create Azure Cluster Without Purchase Plan ❌ 

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-f487c8819d726109d8178894b6a4c082d5320b92-head |
| Rancher cluster type    | Single Node Docker Install                         |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | Azure RKE1                                         |
| Downstream K8s version  | 1.21.6-rancher1-1                                  |
| Browser type            | Google Chrome                                      |
| Browser version         | 96.0.4664.45 (Official Build) (x86_64)             |
| CLoud Credential        | Azure Cloud Credentials Setup Prior to Steps       |

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> click `Cluster Management` -> click `Create` ->  click `Azure` (RKE1)
3. Create a node template
    - Default values
    - Leave the new field `Purchase Plan` blank
    - Click `Save`
4. Create 3 node pools
    1. nodes 1 etcd
    2. nodes 1 cp
    3. nodes 1 worker
5. Add `Cluster Name` & `Name Prefix` for node pools
6. Default values for the rest, click `Create`
7. The cluster will not leave `Provisioning State` 
8. Click on the created cluster and observe the following warnings

**Results**

```txt
Error creating machine: Error in driver during machine creation: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NotFound" Message="The Availability Set '/subscriptions/***[REMOVED_SUBSCRIPTION***]/resourceGroups/docker-machine/providers/Microsoft.Compute/availabilitySets/docker-machine' cannot be found."
```


![error](https://user-images.githubusercontent.com/40877149/142512517-5293e78d-7dae-4a62-b073-76fde89a6e8b.png)

  
## Additional Info

Logs from Docker Container

```txt
2021/11/18 23:09:00 [INFO] Generating and uploading node config no-purchase-plans-brudnak6
2021/11/18 23:09:00 [ERROR] error syncing 'c-8w96x/m-dbbbh': handler node-controller: Error creating machine: Error in driver during machine creation: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NotFound" Message="The Availability Set '/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Compute/availabilitySets/docker-machine' cannot be found.", requeuing
2021/11/18 23:09:02 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure request  method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/providers/Microsoft.Network/locations/westus/operations/REMOVED_LOC?api-version=2019-12-01"
2021/11/18 23:09:02 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure response  method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/providers/Microsoft.Network/locations/westus/operations/REMOVED_LOC?api-version=2019-12-01" x-ms-request-id="REMOVED_ID" status="200 OK"
2021/11/18 23:09:02 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Attempting to clean up Network Security Group resource...  name="rancher-managed-AgzdVcHA"
2021/11/18 23:09:02 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure request  method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/networkSecurityGroups/rancher-managed-AgzdVcHA?api-version=2019-12-01"
2021/11/18 23:09:02 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure response  status="200 OK" method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/networkSecurityGroups/rancher-managed-AgzdVcHA?api-version=2019-12-01" x-ms-request-id="REMOVED_ID"
2021/11/18 23:09:02 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure request  method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/networkSecurityGroups/rancher-managed-AgzdVcHA?api-version=2019-12-01"
2021/11/18 23:09:02 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure response  status="200 OK" method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/networkSecurityGroups/rancher-managed-AgzdVcHA?api-version=2019-12-01" x-ms-request-id="REMOVED_ID"
2021/11/18 23:09:02 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Network Security Group is still in use by other resources or is tagged to skip deletion, skipping removal.  name="rancher-managed-AgzdVcHA"
2021/11/18 23:09:02 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Attempting to clean up Availability Set resource...  name="docker-machine"
2021/11/18 23:09:02 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure request  method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Compute/availabilitySets/docker-machine?api-version=2019-12-01"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure response  request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Compute/availabilitySets/docker-machine?api-version=2019-12-01" x-ms-request-id="997e4949-de3b-49f1-ab0a-f57c3aa0ed14" status="200 OK" method="GET"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure request  method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Compute/availabilitySets/docker-machine?api-version=2019-12-01"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure response  status="200 OK" method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Compute/availabilitySets/docker-machine?api-version=2019-12-01" x-ms-request-id="REMOVED_ID"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Availability Set is still in use by other resources or is tagged to skip deletion, skipping removal.  name="docker-machine"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Attempting to clean up Subnet resource...  name="docker-machine"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure request  request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/virtualNetworks/docker-machine-vnet/subnets/docker-machine?api-version=2019-12-01" method="GET"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure response  status="200 OK" method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/virtualNetworks/docker-machine-vnet/subnets/docker-machine?api-version=2019-12-01" x-ms-request-id="REMOVED_ID"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure response  request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/virtualNetworks/docker-machine-vnet/subnets/docker-machine?api-version=2019-12-01" x-ms-request-id="REMOVED_ID" status="200 OK" method="GET"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Subnet is still in use by other resources or is tagged to skip deletion, skipping removal.  name="docker-machine"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Attempting to clean up Virtual Network resource...  name="docker-machine-vnet"
2021/11/18 23:09:03 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure request  method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/virtualNetworks/docker-machine-vnet?api-version=2019-12-01"
2021/11/18 23:09:04 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure response  status="200 OK" method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/virtualNetworks/docker-machine-vnet?api-version=2019-12-01" x-ms-request-id="REMOVED_ID"
2021/11/18 23:09:04 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure request  request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/virtualNetworks/docker-machine-vnet?api-version=2019-12-01" method="GET"
2021/11/18 23:09:04 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Azure response  status="200 OK" method="GET" request="https://management.azure.com/subscriptions/REMOVED_ID/resourceGroups/docker-machine/providers/Microsoft.Network/virtualNetworks/docker-machine-vnet?api-version=2019-12-01" x-ms-request-id="REMOVED_ID"
2021/11/18 23:09:04 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Virtual Network is still in use by other resources or is tagged to skip deletion, skipping removal.  name="docker-machine-vnet"
2021/11/18 23:09:04 [INFO] [node-controller-rancher-machine] Successfully removed no-purchase-plans-brudnak4
2021/11/18 23:09:04 [INFO] [node-controller-rancher-machine] (no-purchase-plans-brudnak4) Closing plugin on server side
2021/11/18 23:09:04 [INFO] Removing node no-purchase-plans-brudnak4 done
```

**Comment by codyrancher** [comment]
@snasovich the original ask says that the field is optional. Does the UI need to provide a default plan or is this something that needs to be fixed on the backend?

**Comment by snasovich** [comment]
@codyrancher , the field should be optional and backend doesn't pass anything if it's not populated.
https://github.com/rancher/machine/pull/122/files#diff-2629c719d35bcc28b17c33c0a3c30cb20902fe0f263278188ee98675a8b838e8R569-R575

Per offline conversation with @brudnak there seems to be a general issue with Azure subscription used for testing so this latest issue reported may not be related to the changes. Stay tuned...

**Comment by sowmyav27** [comment]
**On 2.6.3-rc4**

Deployed an Azure cluster with
- plan - `"plan": "cloud-infrastructure-services:centos-8-3:centos-8-3",`
- `"image": "cloud-infrastructure-services:centos-8-3:centos-8-3:0.0.1",`
Cluster came up Active.
