### ISSUE TITLE
When creating new cluster flow, getting an error: TypeError: this.value.join is not a function

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#4504]
**Setup** 
- Rancher version: `2.6-head Commit ID 931a0f0`
- Browser type & version: `Chrome` Version 94.0.4606.81 (Official Build) (x86_64)

**Describe the bug**
Creating a new cluster flow for logging. The cluster on 'create' the flow is created, and there is an error in console `TypeError: this.value.join is not a function`

**To Reproduce**
1. Install rancher logging v2 chart on an active cluster
2. Create Secret
3. Create Cluster Output
4. Create `Cluster Flow` pointing to the Cluster Output in step 3
5. Click `Create`

**Result**
Functioning Cluster Flow is created and **Error** thrown in console.
**Expected Result**
Cluster flow created with no error. 

**Screenshots**
<img width="451" alt="Screen Shot 2021-11-03 at 3 46 34 PM" src="https://user-images.githubusercontent.com/89212856/140182104-e61208ce-036a-4e72-9331-21cb81ff5747.png">

<img width="1616" alt="Screen Shot 2021-11-03 at 2 55 19 PM" src="https://user-images.githubusercontent.com/89212856/140182241-31ba8925-46cd-46ab-99de-dd641ebec4d5.png">

**Additional context**
I've determined that the error is thrown when the cluster flow page is refreshed while there are existing cluster flows. So the error occurs on page refresh as well.

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID 78b25c3`

1. Install rancher logging v2 chart on an active cluster
2. Create `Cluster Output`
3. Create `Cluster Flow` pointing to the Cluster Output in step 3
4. Click `Create`

`result: cluster flow is created and no error thrown`

Also noticed that the cluster output is shown by name in the clusterflows page, whereas when this error was occurring, components of the cluster output were shown.

![Screen Shot 2021-11-15 at 4.09.26 PM.png](https://zube.io/files/rancher/8acbd2c75a036d743d53083e36be4a49-screen-shot-2021-11-15-at-4-09-26-pm.png)

**Comment by Shavindra** [comment]
@ronhorton to clarify the follow-up comment, are we expecting to see the components of the output?

**Comment by ronhorton** [comment]
No, I noted it as I'd not noticed it in the prior write up. It was further evidence of the previous bug. It's correct now.
