### ISSUE TITLE
Brand/Company name change in Global settings doesn't persist

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#4515]
**Setup**
- Tested with master version: 9705d3ab9025fe7bb3a742151911a03af4887c88

**Describe the bug**
Brand name change from Global settings doesn't persist.

**To Reproduce**
1. Navigate to global settings
2. Change the brand name and apply changes
3. Click through to home page. You should see the new brand name
4. Refresh the page

**Result**
5. Brand name reverts back to default `Rancher`

**Expected Result**
6. New brandname should persist

**Screenshots**

https://user-images.githubusercontent.com/1387263/140485302-f3e8707b-d1f2-4959-bce4-d95892e200d9.mov

**Comment by richard-cox** [comment]
Could not reproduce in 2.7-head (cusp of 2.7.0 release)
