### ISSUE TITLE
Role templates missing the Resource names in the details page of roles

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4527]
**Setup**
- Rancher version: v2.6-head e655fd8
- Browser type & version: Chrome

**Describe the bug**
Details page of roles is missing the resource name for a role. 

**To Reproduce**
From Users and auth --> Roles 
Select any role. for eg., under global roles --> Administrator

**Result**
Resources are missing for the role in the detail page.

**Expected Result**
Expected the Resource name to be present as it gets difficult to check the resources that can be accessed for a particular role.

**Screenshots**

<img width="1360" alt="Screen Shot 2021-11-08 at 3 50 19 PM" src="https://user-images.githubusercontent.com/38144301/140836888-1c6e1220-543b-458f-9324-38374060a156.png">

**Additional context**
Workaround for now is to got to the config page and check the resources that a role can have access to.

**Comment by nwmac** [comment]
Can not reproduce - looks like this has already been fixed

**Comment by anupama2501** [comment]
Verified on v2.6-head 7efbeab

Resource names are seen on each roles of Cluster & project.
<img width="500" alt="2022-01-31_07-59-48" src="https://user-images.githubusercontent.com/38144301/151828469-a6fc998b-91b5-4046-9429-2a8caf4f9189.png">
