### ISSUE TITLE
[Feature]Enhance the Harvester import experience to Rancher

### ISSUE THREAD

**Issue by guangbochen** [rancher/dashboard#4531]
backport https://github.com/harvester/harvester/issues/1330

Proposal for the import UX:
1. In Rancher UI, we show the instructions for importing Harvester using Harvester UI.
![image](https://user-images.githubusercontent.com/5697937/139803392-03c644a2-ffb9-4d29-88a4-6bc2abddcb07.png)

2. In Harvester settings, add a `cluster-registration-url` settings. Users import the Harvester cluster by clicking the `Import to Rancher` button and inputing the registration URL.
![image](https://user-images.githubusercontent.com/5697937/139802433-c667ced7-f66d-473a-aa2f-956fc4c2307e.png)

3. Under the hood, Harvester settings controller applies the manifests for the import.

**Comment by n313893254** [comment]
**Verify Steps**

- Install the latest Rancher
- Go to `Virtualization Management` and import a cluster
- Check the `Registration` tab
- Following the instruction to import the exiting Harvester (Harvester requires latest version)
- Go to Harvester setting and check `cluster-registration-url` setting

**Additional Context**
[Import cluster instuction]
![image](https://user-images.githubusercontent.com/18737885/141441370-6ae4264f-1fe0-4763-9f16-130639384d1b.png)

[Setting Config]
![image](https://user-images.githubusercontent.com/18737885/141446895-ae4334ca-bc52-450a-a5df-cb16e293da6a.png)
