### ISSUE TITLE
Upgrade Nuxt dependency to latest 2.x version

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4533]
We're on 2.14.6 - latest is currently 2.15.8.

There are some issues updating due to the use of a newer ufo package - @nwmac knows more.

**Comment by rak-phillip** [comment]
We might want to consider performing #4820 along with this one

**Comment by gaktive** [comment]
Done as part of plugin work. Nothing for QA to test here but we're on the latest. Eventually, we will remove Nuxt completely.
