### ISSUE TITLE
Add Replica Configurable Number to Pod List View

### ISSUE THREAD

**Issue by scottking2** [rancher/dashboard#4536]
*******FEATURE REQUEST***********

I would love to see the replica number be configurable from the list view like in rancher 2.5. We often scale up and down our pods manually and having the extra number of mouse clicks to scale each deployment has become a hassle in rancher 2.6. 

Below is a screen shot of what I'm referring to in rancher 2.5. It would be fantastic to have this feature available in 2.6. (the plus and minus buttons below the replica count) 

<img width="1275" alt="Screen Shot 2021-11-05 at 10 19 25 AM" src="https://user-images.githubusercontent.com/6719805/140966821-a539146e-14d4-4f33-a45c-41d1088d8045.png">

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/issues/4328
