### ISSUE TITLE
Support to force machine deletion for RKE2 provisioned clusters

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4538]
**Detailed Description**
As part of https://github.com/rancher/rancher/issues/34945 (https://github.com/rancher/rancher/pull/35403) Rancher backend now supports forcing machine deletion which is handy in cases where VM deletion failed in the infrastructure provider.
To take advantage of this, it's requested to add new "Force Delete" action to machine dropdown menu:
![image](https://user-images.githubusercontent.com/85187633/141023684-f274ee2a-d7ea-4957-9072-69729763cf89.png)

The action should only be available if "InfrastructureReady" condition is "False" and has "DeletionFailed" as the reason (which is added by linked issue/PR).
The action should have a confirmation message similar to one already shown for "Delete" with text along the lines of "There was an issue with deleting underlying infrastructure. If you proceed with this action, the Machine (machinename) will be deleted from Rancher only. It's highly recommended to manually delete any referenced infrastructure". An option to bypass this confirmation by holding Ctrl/Command key should be supported similar to other confirmations.

Once the confirmation is received, the UI should set `provisioning.cattle.io/force-machine-remove` annotation to `true` on the infrastructure machine referenced by the current machine. The backend will take care of deleting the machine from there. The reference to infrastructure machine is available in `spec.infrastructureRef` field as shown below:
![image](https://user-images.githubusercontent.com/85187633/141024555-ea90fee3-3e42-4c14-9960-7af87d1287cf.png)

**Context**
This is UI change needed to expose new functionality supported by backend.

**Comment by snasovich** [comment]
Backend change is now merged.

**Comment by gaktive** [comment]
@jordojordo feel free to ping @richard-cox for help. The tricky part will be determining which modal to use for the dialog box.

**Comment by jordojordo** [comment]
@snasovich I have created a [draft PR](https://github.com/rancher/dashboard/pull/4592) that adds the action force remove pools, however, it does not seem capable of completing the task. I think the Yaml of my pool was stuck in a `deleting`/`deletionfailed` loop that would update the Yaml of the resource as the UI is attempting to add the annotation `provisioning.cattle.io/force-machine-remove`, which would cause the annotation to not be set. 

**`deleting`/`deletionfailed` loop:**
https://user-images.githubusercontent.com/40806497/142491201-a9523e23-5971-4d19-980f-42328874f00c.mp4

Here's my version info:
![version](https://user-images.githubusercontent.com/40806497/142491340-20ee8829-9683-4d27-a076-8c6dc05f9bab.png)

**Possible fix**
Would we be able to limit the amount of attempts that the pool tries to update?

**Comment by snasovich** [comment]
@jordojordo , thank you for letting me know.

Glancing through the PR it looks like you're setting this annotation on the machine itself and not on the infrastructure machine that is referenced by it, though I definitely may be wrong here. You need to query infrastructure machine object separately per values in `spec.infrastructureRef` field. 
> the UI should set provisioning.cattle.io/force-machine-remove annotation to true on the infrastructure machine referenced by the current machine. The backend will take care of deleting the machine from there. The reference to infrastructure machine is available in spec.infrastructureRef field as shown below (screenshot)

@thedadams , is status flipping back and forth on infrastructure machine as well until your fix is in?

**Comment by thedadams** [comment]
No the infrastructure machine does not do the flipping back and forth. Only the machine object does that (until my fix goes in).

**Comment by jordojordo** [comment]
@snasovich You were right, setting the annotation on the infrastructure machine worked. Updating my PR now. Thanks for the help!

**Comment by thedadams** [comment]
I apologize for not updating this issue. There were other changes in the backend based on feedback from QA that changed the `Reason` from `DeletionFailed` to `DeleteError`. Therefore, then option to force delete should only be available if "InfrastructureReady" condition is "False" and has "DeleteError" as the reason.

**Comment by sowmyav27** [comment]
Reopening the issue since the fix should be changed to accommodate [this](https://github.com/rancher/dashboard/issues/4538#issuecomment-981833628)

**Comment by jordojordo** [comment]
@sowmyav27 I have a merged a [PR](https://github.com/rancher/dashboard/pull/4663) that changes the reason for force removing to `DeleteError`.
