### ISSUE TITLE
Support for options when restoring RKE2 cluster etcd snapshots

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4539]
**Detailed Description**

Following the implementation of https://github.com/rancher/rancher/issues/35468, the UI should support options to restore either "Kubernetes version and etcd" or "Cluster config, Kubernetes version and etcd" similar to how RKE1 supports on the following dialog (note "etcd only" option is not needed).
![image](https://user-images.githubusercontent.com/85187633/141043775-c84dfb67-a353-4a85-882d-0c6861d998fa.png)

**Note:** This issue should be updated once more details are known on how the updated etcd snapshot is going to work in RKE2.

**Context**
This is needed for RKE2 provisioning parity with RKE1 provisioning.

**Comment by codyrancher** [comment]
@snasovich is the ask here to just remove the 'Only etcd' option? From reading the dependent ticket it sounds like we might want more than that.

**Comment by snasovich** [comment]
@codyrancher , the ask here is to support restoring RKE2/k3s downstream clusters' etcd backups on the Dashboard UI. (So, not modifying the existing form to remove additional option.)
How to actually kick off restore depends on backend implementation that @Oats87 is working on.
@Oats87 will be providing the information on how to kick off restore and pass options.

**Comment by gaktive** [comment]
Work moved to https://github.com/rancher/rancher/issues/34417 which is in QA to test, so this looks ready for UI.

**Comment by snasovich** [comment]
@gaktive @codyrancher , Chris provided a summary of backend changes: https://github.com/rancher/rancher/issues/34417#issuecomment-1043210206

Please us know if more clarifications are needed or you run into issues.
Also, there is a change in where snapshot data is stored (moved from cluster object to their own CRs). Do we need a separate UI issue on this or it can be included in this one?

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver 

----------

### Testing: ###

Tested this issue with the following steps:

1. Create RKE2 node driver cluster
2. Create couple manual snapshots
3. Click on restore snapshot and confirm the options given to user

**Result** - Pass

etcd snapshot is showing the proper options and is in parity with RKE1 provisioning
![Screen Shot 2022-03-03 at 10.04.03 AM.png](https://zube.io/files/rancher/3c27901f8f9fd982ac00c7b7ec7631d7-screen-shot-2022-03-03-at-10-04-03-am.png)

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
