### ISSUE TITLE
Only show latest version in each minor line when upgrading k3s/rke2 clusters

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#4543]
**Background:**
This has been controlled through KDM for k3s and rke2. In the rancher 2.5 line, this is working correctly because there is only ever one minor version at a time in that KDM line. However, in 2.6, with the introduction of provisioning, k3s and rke2 now follow a KDM pattern that is more similar to rke1 in that it has multiple versions available in a specific minor version line (for example 1.21.4, 1.21.5, and 1.21.6). 

**Description:**
During cluster creation, this works properly and only shows the latest version. However, when upgrading an imported cluster, it shows all of these versions as available. I believe it should only show the latest version.

This is primarily cosmetic as the growing list could be frustrating for a user. The current view for example is:

Upgrading Imported Cluster:
![image](https://user-images.githubusercontent.com/55997940/140343065-9ecd8c10-54b1-4417-bd8a-a661046c430a.png)
My expectations here are for it to show, in this order:
v1.21.6+rke2r1
v1.20.12+rke2r1
v1.19.16+rke2r1
v1.19.15+rke2r2 (current version of the imported cluster)

Provisioning New Cluster:
![image](https://user-images.githubusercontent.com/55997940/140343380-30ff504d-2e90-4aa5-9034-7169c005ba59.png)
This meets expectations.

**Comment by snasovich** [comment]
@nwmac @gaktive , I believe this is UI issue. Can we apply the same logic as we did for https://github.com/rancher/dashboard/issues/4127 here?

**Comment by nwmac** [comment]
@jordojordo Can you take a look - reach out to @vincent99 if you need more info. Thanks.

**Comment by bguzman-3pillar** [comment]
Validated using `v1.19.15+rke2r2`, 2.6head, commit: 99974f0

K8S versions to update are correct now: 

![Screen Shot 2022-03-15 at 11 59 09](https://user-images.githubusercontent.com/95362932/158442228-f5b543af-d344-4f72-a141-5033abe1b3ce.png)

**Comment by Martin-Weiss** [comment]
How should a customer upgrade the downstream production cluster to the version he tested for 4 weeks in the dev stage in case we update the data.json in the meantime?

Example:
January - customer tests 1.20.7 in dev
February - we release 1.20.8 and update the data.json
March - customer wants to upgrade prod to 1.20.7

I believe we have to show ALL patch versions as otherwise customers have no chance to rollout the tested version to their production environment.. testing can take months..

**Comment by catherineluse** [comment]
@Martin-Weiss The customer should edit this setting to stop the Kubernetes versions from automatically updating https://rancher.com/docs/rancher/v2.6/en/admin-settings/k8s-metadata/#configuring-the-metadata-synchronization

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss The customer should edit this setting to stop the Kubernetes versions from automatically updating https://rancher.com/docs/rancher/v2.6/en/admin-settings/k8s-metadata/#configuring-the-metadata-synchronization

@catherineluse  - unfortunately this does not help - while rolling out the „tested in sandbox“ version through development / testing / production environments - customers in parallel have to start testing with the next „new“ version in sandbox environment. So customers need at least two - maybe three versions and not only the latest or a single one..

**Comment by rancher-max** [comment]
@Martin-Weiss I created https://github.com/rancher/dashboard/issues/5437 to address this as you make a valid point. I am unsure when (or if) it will get prioritized, but until then, customers will unfortunately have to use Edit as YAML if using rancher v2.6.4 and want to upgrade to a previously released version that is no longer shown. Thank you for bringing those up though and let's see if we can get it addressed! 💪
