### ISSUE TITLE
Registration command for private EKS clusters not obtainable

### ISSUE THREAD

**Issue by ebauman** [rancher/dashboard#4545]
**Setup**
- Rancher version: v2.6.2
- Browser type & version: Chrome, Firefox

**Describe the bug**

When creating an EKS cluster, and specifying private endpoints, the user is unable to obtain the registration command (`kubectl apply -f ...`) from the UI. The user must go into the v3 API at the `/clusterregistrationtokens` endpoint to view it. 

**To Reproduce**

1. Create an EKS cluster, and only turn on private endpoints
2. Try to find the cluster registration command

**Result**
You can't. 

**Expected Result**

The triple-dot menu will reveal a Registration Command option as it did in v2.5.x

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by nayrnet** [comment]
Workaround: If you change to the old Rancher 2.5.x UI you can get the registration command: `https://<RANCHERSERVERURL>/g`

**Comment by nayrnet** [comment]
Missing the registration tab, with registration command on the cluster view as seen for custom clusters:
![image (1)](https://user-images.githubusercontent.com/3732081/151608670-87aa3e3c-2128-4930-824c-9d9a0886b4c2.png)

**Comment by catherineluse** [comment]
Should this be in the v2.6.4 release notes under known issues?
