### ISSUE TITLE
[Monitoring V2] A page/section for setting values for the CRD chart

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#4549]
**Setup**
- Rancher version: 2.6.x
- Browser type & version: chrome Version 95.0.4638.69 (Official Build) (x86_64)

**Describe the bug**

If we install the `rancher-monitoring` chart via the UI, it will install two apps: `rancher-monitoring` and `rancher-monitoring-crd`. Today we can only configure the values for the main chart (`rancher-monitoring`) in the UI's workflow. 
 
UI needs support to configure values for the crd chart, which is critical for allowing rancher-monitoring to be installed in different environments successfully and smoothly. Here are some typical use cases:
- I want the crd chart  to pull images from my private registry 
- I need to set node selectors or tolerations for the crd-chart's pod

Because we cannot set those in the UI, we have to let the crd chart fail to install at the first attempt, then go to edit the install app to append those values.  

Here is an issue reported by the community: https://github.com/rancher/rancher/issues/34439. To fix it, on the chart side, we are going to add the support for setting node selectors and tolerations in the crd-chart;  on the UI side, we need the support for setting values for the crd-chart.

**Comment by nwmac** [comment]
@jiaqiluo I think we have some questions about this - so bumping to 2.6.4, please let me know if that is a problem for you.

**Comment by jiaqiluo** [comment]
@nwmac It works for me. let's try to tackle it in 2.6.4
