### ISSUE TITLE
Improved IPv6 dual-stack support on the UI for RKE2 provisioning

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4550]
**Detailed Description**
We want UI to provide more guidance on setting up clusters if IPv6 dual-stack support is needed. The exact configuration needed depends on the CNI and is described here: https://docs.rke2.io/install/network_options/#dual-stack-configuration.
For example, for Cilium `ipv6.enabled` needs to be set to `true` in addition to having IPv6 addresses in `cluster-cidr` and `service-cidr` while for Calico just the latter part is sufficient.

Following discussion with @gaktive @nwmac @Oats87 @thedadams @mantis-toboggan-md the following approach is suggested:
* If the user selects `cilium` or `multus,cilium` in "Container Network" dropdown, show "Enable IPv6 dual-stack" checkbox should be shown (unchecked by default). If the user checks this checkbox, the request submitted to the backend must include `ipv6.enabled` set to `true` for `rke2-cilium` chart - so part of the request to create `provisioning.cattle.io.clusters` object would look like this:
```
    chartValues:
      rke2-cilium:
        ipv6:
          enabled: true
```
* (Regardless of "Container Network" selected) If the user specifies an IP address in any of "Cluster CIDR" / "Service CIDR" that matches IPv6 format, the UI should add a notification along the lines of "You have specified IPv6 CIDR. Please ensure your node provider supports it and any relevant options are enabled".

**Context**
This will help with RKE2 provisioning usability.

**Comment by gaktive** [comment]
@snasovich is going to work on fleshing out the design requirements here before UI works on this.

**Comment by snasovich** [comment]
@mantis-toboggan-md @nwmac , updated the description based on our discussions. Please feel free to correct/comment as necessary.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 1d2b746
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 AWS node driver 

----------

### Testing: ###

Retested the following scenario:
- Select cilium or multus,cilium in "Container Network" dropdown

**Result** - Pass

If the user chooses "multus,cilium" under Container Network, the "Enable IPv6 support" option appears
![Screen Shot 2022-03-03 at 10.13.06 AM.png](https://zube.io/files/rancher/c10364439d156a683f9d9bb61b093a85-screen-shot-2022-03-03-at-10-13-06-am.png)
