### ISSUE TITLE
RKE2 snapshot S3 configuration support

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4551]
**Detailed Description**
Currently, S3 configuration cannot be set on UI for RKE2 snapshots - I believe it was disabled at some point during 2.6.0 release due to issues (https://github.com/rancher/rancher/issues/34417 is about on-demand S3 snapshots, but probably affects scheduled ones too.)
The UI existed before per https://github.com/rancher/rancher/issues/34088#issuecomment-904952333, so it will need to be re-enabled once backend issues are fixed. This issue is to track this effort.

**Context**
Needed for RKE2 provisioning parity with RKE1

**Comment by gaktive** [comment]
UI should be pretty much in place once the backend work is done.

**Comment by gaktive** [comment]
Backend item is now in QA so this looks ready to work on. @snasovich, is this good for UI to work on?

**Comment by gaktive** [comment]
Hopefully the overlap with https://github.com/rancher/dashboard/issues/4539 means that this is simple.

**Comment by snasovich** [comment]
@gaktive , this should be unblocked now, however we need @Oats87 to provide a summary of his changes and impact on UI for this. There may be no impact on this specific issue, but there is certainly input needed for https://github.com/rancher/dashboard/issues/4539. As well as I believe there is a change needed for how UI shows snapshots which will need to be a separate UI issue (sorry!).

@Oats87 , could you please provide the "impact to QA / UI" on https://github.com/rancher/rancher/issues/34417 (unless it's provided elsewhere - please point us to it).

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 3df76e4
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 EC2

----------

### Testing: ###

Tested this issue with the following:
1. Create RKE2 Cluster
2. Under `etcd` configuration, enable backup Snapshots to S3
3. Fill out fields to set up S3 bucket
4. Confirm edits are made in the yaml

**Result** - **Pass**

The UI configuration is available.
![image.png](https://zube.io/files/rancher/435f5b4de305b99ec9f49c27971043ae-image.png)

Edits made in the UI are also reflected in the yaml
![image.png](https://zube.io/files/rancher/38a4f57e5652d30485e785c175a239ab-image.png)
