### ISSUE TITLE
Remove Enable/Disable actions for feature flags that have non-null status.lockedValue

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4556]
As part of https://github.com/rancher/rancher/pull/35372 `status.lockedValue` is now set to `true` for `rke2` feature if it cannot be disabled.
However, UI still shows "Disable" action button for this feature flag.

It's requested for "Enable"/"Disable" actions to be removed if associated `management.cattle.io.features` has `status.lockedValue` with non-null value as it indicates the value should not be changed.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `e322f8f`**

- Deployed an RKE2 cluster
- There is a lock icon next to RKE2 feature flag.
- Enabled Token hashing. There is a lock icon next to Token hashing feature flag.
- No Actions exist for either of these two flags.

<img width="1429" alt="Screen Shot 2021-11-21 at 12 32 35 PM" src="https://user-images.githubusercontent.com/26032343/142777949-97cd7b23-0d4d-4fc9-9655-f82465cb9f0b.png">
