### ISSUE TITLE
[EKS] Support custom instance roles for node groups

### ISSUE THREAD

**Issue by thedadams** [rancher/dashboard#4568]
In order to support custom node instance roles for EKS clusters, a new dropdown should be added to the "Add nodegroup" section of the UI.

This dropdown should:
1. Get the available node instance roles from the AWS API to populate the dropdown.
2. Filter out the node instance roles that are prefixed with `rancher-managed-`
3. The field name should be `nodeInstanceRole`
4. The value passed to the Rancher API should be a `string`. If no role is selected for a nodegroup, then the empty string should be passed.

SURE-4536

**Comment by snasovich** [comment]
@nwmac @gaktive , is this something that can be implemented in 2.6.3? We're working on getting backend done so it's _technically_ backend blocked, but hopefully some work can be started with the assumption this new field is added as per PR linked to backend issue.

**Comment by gaktive** [comment]
@snasovich do you have the backend ticket somewhere to refer to? Otherwise, what is the state of the backend if we can target this for 2.6.4?

**Comment by thedadams** [comment]
Backend issue: https://github.com/rancher/rancher/issues/29071

**Comment by snasovich** [comment]
@gaktive , so far we're tentatively targeting this for 2.6.5. I've updated your milestone to match.

**Comment by gaktive** [comment]
@snasovich i see that the backend ticket no longer has a milestone now. If that's expected, I can place this ticket in 2.6.x.

**Comment by snasovich** [comment]
@gaktive @nwmac , we're working on getting backend changes for this done for 2.7.0 (not 100% sure we'll make it by deadline though). Is it possible to have UI changes ready for 2.7.0 release?

**Comment by gaktive** [comment]
@snasovich is the ask to have UI ready before backend? I'll check if we can start work and then wait, though do let us know if any design changes are anticipated.

**Comment by snasovich** [comment]
@gaktive , the plan is to get backend changes merged by end of day 9/20/22. I'm not sure how this aligns with your deadlines, so if starting before backend is ready helps, that would be good.
@annablender , let us know if whatever is outlined in the description of this issue needs to be updated based on your work on backend.

**Comment by annablender** [comment]
@gaktive Backend changes for this issue are finished and reviewed in these PRs https://github.com/rancher/eks-operator/pull/73, https://github.com/rancher/rancher/pull/38939 but are waiting to be merged until a rancher 2.7.x branch is released. Feel free to go ahead and start on the UI changes. It just won't be able to be tested until my PRs are merged and eks operator v1.0.5-rc2 is being used on rancher 2.7-head.

Summary of backend changes
* The `spec.nodeGroups.nodeRole` and `status.generatedNodeRole` fields have been added to both the EKSClusterConfig and cluster management yaml in Rancher.
* The UI must pass an empty string "" (no node role) or a custom node role to the rancher backend when an EKS cluster is created. If no node role is specified, `generatedNodeRole` will be generated and set on the upstream node group. If a custom node role is specified, that custom role will be set on the node group and `generatedNodeRole` will remain empty. Once a `generatedNodeRole` has been generated for a node group, that value will persist in rancher and be used for any other node groups that need it.
*

**Comment by mantis-toboggan-md** [comment]
There's a draft PR up for the UI portion of this feature now https://github.com/rancher/ui/pull/4913, just waiting on backend availability before reviewing/merging

**Comment by annablender** [comment]
@mantis-toboggan-md Backend is available. EKS node driver is currently broken without the ui part, which blocks QA on some issues ;)

**Comment by Josh-Diamond** [comment]
Awaiting PR, https://github.com/rancher/ui/pull/4913, to be merged, before this issue is truly ready `to-test`.  Will take this up as priority once available for testing

**Comment by Josh-Diamond** [comment]
Issue is ready `to-test` but moving to `blocked` due to associated rancher issue being `re-opened`;

Will resume testing on this once associated rancher issue - [`https://github.com/rancher/rancher/issues/29071`] - is back `to-test`

**Comment by Josh-Diamond** [comment]
Issue blocked by dashboard issues: https://github.com/rancher/dashboard/issues/7754 , https://github.com/rancher/dashboard/issues/7755 and https://github.com/rancher/dashboard/issues/7756

**Comment by Josh-Diamond** [comment]
Moving to `Next up`, as this has now been unblocked and is ready `to-test`

**Comment by Josh-Diamond** [comment]
Ticket #4568 - Test Results - ✅ 
---

This ticket has been validated in parallel with the following tickets.  Full testing scenarios and details may be found via links below:
- https://github.com/rancher/dashboard/issues/7754
- https://github.com/rancher/dashboard/issues/7755
- https://github.com/rancher/dashboard/issues/7756
- https://github.com/rancher/rancher/issues/29071

**Comment by Josh-Diamond** [comment]
Re-opening
---

Why?
Once the cluster successfully provisions and is `Active`, if you navigate to `Edit Config` of cluster, then down to `Node Details` you will notice the `Node Instance Role` is set to `N/A`.  This is unexpected, and should show the role here, similar to what is shown for `Launch Template`, `Template Version`, and `Kubernetes Version`

Screenshot:
<img width="1471" alt="Screenshot 2023-01-12 at 3 09 45 PM" src="https://user-images.githubusercontent.com/46494969/212191880-eb7f694c-b0a6-4e9e-9b46-7b01c16c4714.png">

**Comment by Josh-Diamond** [comment]
Looks like drone failed, not quite ready `to-test`

Restarting drone build now, moving to `review` until drone passes.

**Comment by Josh-Diamond** [comment]
Unable to restart drone - [perhaps lack of permissions?]

Requested assistance from UI team (internally)

**Comment by annablender** [comment]
@Josh-Diamond Check if you've logged in to drone

**Comment by Josh-Diamond** [comment]
Ticket #4568 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-0504ce63c1cad67b2c2be14a0325533b60902832-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream EKS cluster w/ custom instance role assigned for node group
3. Once `active`, navigate to `Cluster Management > Edit Config > Node Instance Role`
4. Verified - accurate custom role is seen and present; as expected

Screenshot:
<img width="321" alt="Screenshot 2023-02-08 at 2 27 38 PM" src="https://user-images.githubusercontent.com/46494969/217655795-acadb582-2a5e-4575-a7c8-f15108c1bd4c.png">
