### ISSUE TITLE
Provisioning logs moving from the cluster object to a configmap

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#4569]
**Detailed Description**

Ability to review the provisioning logs in more detail as provisioning is in progress for a cluster

**Context**

Currently, the logs are written as a last line to the cluster object and reads from there in the UI. The backend is changing to be written to a configmap, so the UI will need to be updated to read the config map.

In the cluster detail page, there should be a tab for "Provisioning Log" so see the logs of provisioning.

**Comment by jmcsagdc** [comment]
Reproduced in 2.6.2 where you see no link to Provisioning Log (see screenshot)

Verified in v2.6-4375161a2780765f0fd58af2936876a3e0254741-head

New behavior shows flowing logs after a certain point during the provisioning. These are retained and viewable in the UI. See screenshot

![2021-11-24_15-00-05](https://user-images.githubusercontent.com/15971368/143328629-cee382b4-3b5a-444a-b276-21bd6745af70.jpg)
