### ISSUE TITLE
Forward port the ability to create a ConfigMap at the project scope

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#4571]
Some people asked questions about the ability to create project-scoped Secrets and ConfigMaps in Rancher v2.6, so I have opened this issue to track the last project-related feature that was not forward ported to the new UI.

As of 2.6, the ability to create project scoped Secrets is still possible, but is gated behind a feature flag. A similar process to create project-scoped ConfigMaps is not in 2.6, but could be added if someone requests it.

In Rancher v2.6, he workflow for creating project scoped Secrets is:

1. Go to Global Settings and click Feature Flags
2. Go to legacy and click ⋮ > Activate
3. Go to cluster explorer and go to Legacy > Project
4. In the top nav bar, filter to see only one project
5. In the left nav bar, click Secrets under Project
6. Click Add Secret

If the ability to create a project scoped ConfigMap is added, the workflow would be the same as the one for creating project scoped secrets. The form to create them would use iFrames for the Ember UI.

**Comment by catherineluse** [comment]
The steps to use the project scoped ConfigMap are:

1.     Go to Global Settings and click Feature Flags
2.     Go to legacy and click ⋮ > Activate
3.     Go to cluster explorer and go to Legacy > Project
4.     In the top nav bar, filter to see only one project
5.     In the left nav bar, click Config Maps under Project
6.     Click Add Config Map
7.     Create Config Map with random key and value

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head da382a8
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: AWS EC2

----------

### Testing: ###

Tested this issue with the following steps:
1. Go to Global Settings and click Feature Flags
2. Go to legacy and click ⋮ > Activate
3. Go to cluster explorer and go to Legacy > Project
4. In the top nav bar, filter to see only one project
5. In the left nav bar, click Config Maps under Project
6. Click Add Config Map
![Screen Shot 2022-02-01 at 5.31.12 PM.png](https://zube.io/files/rancher/b834a72bb217c4348b7888edbe7c4f95-screen-shot-2022-02-01-at-5-31-12-pm.png)
7. Create Config Map with random key and value
![Screen Shot 2022-02-01 at 5.31.54 PM.png](https://zube.io/files/rancher/4f134f5bc9a0c44957b41db3541b8fcb-screen-shot-2022-02-01-at-5-31-54-pm.png)

**Result** - Pass
Config Map is successfully created at the project scope
![Screen Shot 2022-02-01 at 5.33.47 PM.png](https://zube.io/files/rancher/ef0b7b110cb639632419ffae4741b954-screen-shot-2022-02-01-at-5-33-47-pm.png)

@sowmyav27 @nwmac

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
