### ISSUE TITLE
Add PNI option to AKS and GKE imported clusters

### ISSUE THREAD

**Issue by ryansann** [rancher/dashboard#4574]
What kind of request is this (question/bug/enhancement/feature request):
enhancement

In order to support Project Network Isolation for generic imported clusters, there needs to be a UI option for Enable Project Network Isolation

For RKE clusters, this option appears in the Kubernetes Options section of the provisioning page. Something similar can be done for the generic import cluster page.

Checking this option, i.e. Enabling PNI, should set `enableNetworkPolicy` on the v3.Cluster object to true

Additional Context:
This was previously done for ember UI and needs to be implemented in dashboard, backend is in

Ember issue:
- https://github.com/rancher/rancher/issues/33024

Backend issue:
- https://github.com/rancher/rancher/issues/33016

**Comment by catherineluse** [comment]
I have some questions about the requirements:

- Does this need to work on K3s, RKE2 and RKE1 clusters? I tried testing on imported K3s and RKE2 clusters and got a back end error that enabling it is not an option. I'm not sure if this is back end blocked or if I misunderstood the requirement. I asked Ryan Sanna and he's yet to respond.
- Cody pointed out that the form for editing an imported K3s cluster actually already has a checkbox to enable PNI (even though the API throws an error if you try to enable it). It's under advanced options. Is this also where we would want to expose the option for RKE2?

I put screenshots in my draft PR https://github.com/rancher/ui/pull/4815

**Comment by gaktive** [comment]
@ryansann are you able to address Catherine's questions regarding requirements?

**Comment by ryansann** [comment]
We are explicitly disallowing `enableNetworkPolicy: true` for rke2 and k3s clusters [in norman](https://github.com/rancher/rancher/blob/release/v2.6/pkg/api/norman/store/cluster/cluster_store.go#L935)

So, this should not work for k3s at this point. There is [an issue](https://github.com/rancher/rancher/issues/36007) to track it but is still open.

The work I did on PNI was to allow for enabling it on hosted providers (gke, aks). Per [this issue](https://github.com/rancher/rancher/issues/32378) it looks like it's possible on RKE2 clusters, Perhaps this would work now since it's supported on the provisioningv1 cluster, but we'd require some changes to remove disallowing rke2 and additional testing/validations. That is out of scope for this milestone. 

I can see two options here:
1. If we can distinguish the provider for the generic imported cluster, then we can display this option for RKE, GKE, and AKS based clusters. 
2. Otherwise it seems there are some additional requirements for RKE2 and K3S that should probably be addressed before moving forward with this.

**Comment by gaktive** [comment]
Thanks @ryansann. Should we get https://github.com/rancher/rancher/issues/36007 on the 2.6.5 milestone?

@catherineluse is this enough to proceed with getting what works into 2.6.4 and then wait for RKE2/k3s to catch up?

**Comment by catherineluse** [comment]
Yes, this is enough.

**Comment by catherineluse** [comment]
@ryansann I had a couple more questions. 

1. Should it be possible to edit the option to enable/disable PNI after the cluster is created?
2. I imported a GKE cluster and found that the PNI option was already available. 
<img width="803" alt="Screen Shot 2022-03-13 at 5 52 53 PM" src="https://user-images.githubusercontent.com/20599230/158113540-a14070d1-a98f-489c-8365-efa13098e65b.png">
When I enabled it in the form for importing the cluster, the cluster was stuck pending. When I imported it with PNI disabled, then edited the cluster config to enable PNI, the cluster was stuck updating.
Is this the correct network request that the form should be making to update the cluster?
<img width="331" alt="Screen Shot 2022-03-13 at 9 22 04 PM" src="https://user-images.githubusercontent.com/20599230/158113683-7e4e2f79-1783-436b-b549-9033d57a30da.png">

When PNI is enabled, the YAML is like this:
<img width="546" alt="Screen Shot 2022-03-13 at 5 32 54 PM" src="https://user-images.githubusercontent.com/20599230/158113627-540a5c4c-bd7d-4504-ba24-9c11430c1314.png">

**Comment by ryansann** [comment]
I ran some tests and didn't encounter the pending issues. The stuck in pending behavior is likely happening because Network Policy support isn't configured on the imported GKE cluster, which has to be done in GCP.

The option to enable PNI for GKE is already implemented in the UI, so must have been handled in a separate UI issue

**Comment by catherineluse** [comment]
I believe no more changes are needed because I just successfully imported a GKE cluster and an AKS cluster that both had PNI enabled.

For the GKE cluster, Ryan was right - the reason it didn't work before was that I didn't properly enable network policy support in the GKE console.

## QA Template

### What was fixed, or what changes have occurred

No changes occurred because this feature was already added in a previous Rancher version.
 
### Areas or cases that should be tested

I don't know if this needs to be retested. Just in case it does, here are screenshots of the configuration I had to set an my GKE cluster in the Google cloud console in order for PNI to work for GKE:
![Screen Shot 2022-04-06 at 1 04 28 PM](https://user-images.githubusercontent.com/20599230/162067002-7f0dfb59-5eaa-44e5-9945-544b7e73c477.png)

![Screen Shot 2022-04-06 at 1 04 28 PM](https://user-images.githubusercontent.com/20599230/162067013-3ac209de-16d8-4f7a-a73d-479fef2d7a9d.png)

 
### What areas could experience regressions?
Not applicable, no changes occurred
