### ISSUE TITLE
Additional UI-side validation for Ingress form

### ISSUE THREAD

**Issue by bengray2** [rancher/dashboard#4575]
Original description below. Per the comments, there is no backend issue, but the ask is for UI to have additional validation to prevent these requests from going through until data is valid.

**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart):  Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):  RKE1
- Proxy/Cert Details:  self signed

**Information about the Cluster**
- Kubernetes version:   v1.21.6
- Cluster Type (Local/Downstream): Local installation via docker, 1x Rancher, 2x Worker Nodes

**Describe the bug**
I can't create an ingress.  No matter what value I use for "Name" I get the message:

`Ingress.extensions "example.com" is invalid: [spec.rules[0].http.paths[0].path: Invalid value: "": must be an absolute path, spec.tls[0].hosts[0]: Invalid value: "": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]`

**To Reproduce**
Try to create an ingress and use any name.  Click create and the error message appears. 

**Result**
The error `Ingress.extensions "whatever" is invalid` and the ingress is not created.

**Expected Result**
Create the ingress with the name given.

**Screenshots**
With example.com (like the error message even gives as a valid example):
![image](https://user-images.githubusercontent.com/44791530/141430725-a2980e07-8f90-4738-8a3b-c98410d57ac0.png)

With 'something-else':
![image](https://user-images.githubusercontent.com/44791530/141430855-2dfe510a-1305-45fe-9b6c-64e005a5b01a.png)

With 'foo':
![image](https://user-images.githubusercontent.com/44791530/141430879-11f10b77-da2e-4036-9785-aca70b6a05af.png)

**Additional context**

**Comment by nwmac** [comment]
@Sean-McQ This is good example of where the form validation work you are doing will help.

**Comment by Sean-McQ** [comment]
Looks like this was accidentally moved back to "to triage" somehow. Moving back to "To Test"

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b66dd0f
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
Tested this issue with the following steps:
1. Create an ingress and use any name
2. Click create

**Result**
I was able to create ingress but I had to fill in the value where `bar` is, as shown below. Without that value I was running into the same error described in the bug. Is this the expected behavior? Will close/reopen based on @Sean-McQ comments

![image.png](https://zube.io/files/rancher/8e5e1aa161fbd99448b8c18bfa3c1d5f-image.png)

**Comment by Sean-McQ** [comment]
It looks like that value is only required if a certificate secret name is chosen. I should create a rule to catch that on the form and then pass it down to the array list to report it.
