### ISSUE TITLE
[2.5.12] Backport rancher-logging: Fix generated YAML for logging output fields referencing file paths

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#4578]
**Detailed Description**
 
Changes introduced in rancher/dashboard#4406 need to be backported into 2.5.12 as a pre-requisite for release

**Comment by ronhorton** [comment]
**PASS** Verified in `2.5-head Commit ID 07a745a`

1. installed logging v2
2. setup a cluster output for splunk
3. click on `edit as Yaml`

`mountFrom is now populated, whereas before it was valueFrom`
<img width="534" alt="Screen Shot 2022-01-04 at 5 29 09 PM" src="https://user-images.githubusercontent.com/89212856/148133014-1044805a-2e64-417f-aeb3-91b513fb4b4d.png">
