### ISSUE TITLE
[monitoring v2] routes and receivers are not listed in the UI; user is unable to save routes

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4581]
**Setup**
- Rancher version: v2.6-head (96e2438)
- Browser type & version: chrome, 95.0.4638.69

**Describe the bug**

after installing Monitoring v100.0.0+16.6.0, routes nor receivers are displaying in the UI. Routes do not allow user to save changes

**To Reproduce**

* deploy a downstream cluster and install monitoring v2 on it
* go to monitoring -> routes & receivers in the UI
* create a receiver -> save it
  * new receiver is not listed in the UI
* create a route to the new receiver
  * no save button is displayed

**Result**
* create a receiver -> save it
  * new receiver is not listed in the UI
* create a route to the new receiver
  * no save button is displayed

**Expected Result**

We should be able to view and save routes/receivers. 

**Screenshots**

<img width="1547" alt="Screen Shot 2021-11-17 at 11 20 27 AM" src="https://user-images.githubusercontent.com/16691014/142268658-f9afe7a4-5ccb-4a48-933a-9c786cd76075.png">
<img width="1551" alt="Screen Shot 2021-11-17 at 11 20 22 AM" src="https://user-images.githubusercontent.com/16691014/142268666-f7fa60a7-e4eb-475f-bc52-9eab37708443.png">
<img width="1548" alt="Screen Shot 2021-11-17 at 11 20 16 AM" src="https://user-images.githubusercontent.com/16691014/142268668-71d33711-571d-4dce-bf8b-c2f0e6c4e02c.png">

**Context**

This blocks p0 use cases for monitoring.

**Comment by jiaqiluo** [comment]
This is reproducible with monitoring v2 chart 100.0.1+up16.6.0 in 1.21 cluster. 

![image](https://user-images.githubusercontent.com/6218999/142508575-96110add-d361-4027-934f-366d9893120b.png)

**Comment by slickwarren** [comment]
tested on v2.6-head (e322f8f):
user is now able to deploy and view receivers/routes
<img width="1009" alt="Screen Shot 2021-11-22 at 11 11 19 AM" src="https://user-images.githubusercontent.com/16691014/142921111-ece5f769-ba16-484b-a693-f0f718556c3b.png">
