### ISSUE TITLE
Cloud Credentials: 创建 Azure failed

### ISSUE THREAD

**Issue by alec-lu** [rancher/dashboard#4585]
**Setup**
- Rancher version: 2.6.2
- Browser type & version:  Google Chrome 版本 95.0.4638.69（正式版本） （64 位）

**Describe the bug**

Authentication test failed, please check your credentials
**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

- 

**Additional context**

**Detailed Description**

**Context**

**Comment by nwmac** [comment]
Can you please provide more detail including steps to reproduce. Thank you.

**Comment by alec-lu** [comment]
[
![azure-aks-Cloud-Credentials-failed](https://user-images.githubusercontent.com/36758795/143423901-0c25e001-30b1-4118-af61-2ec629f4cd7a.JPG)
](url)

**Comment by richard-cox** [comment]
No steps to reproduce, closing
