### ISSUE TITLE
Top menu items are not interactive 

### ISSUE THREAD

**Issue by sgapanovich** [rancher/dashboard#4586]
**Setup**
- Rancher version: v2.6-96bce6e0882099a15c0ded35c069a786d9aadbde-head
- Browser type & version: Chrome/Firefox/Safari

**Describe the bug**

Top menu items (user menu, importing yaml, running kubectl etc) are not working 

**To Reproduce**

Log in to Rancher 
Click on the user menu (top right)
or go to the local cluster

**Result**
User menu doesn't appear completely (only logout option)
Other top menu items are not interactive

**Expected Result**

All menu items work and function

**Screenshots**
in the gif below i am clicking on the menu items but have no response

![gif](https://user-images.githubusercontent.com/40282141/142434169-d5fa6214-6603-431b-bdc9-918af2f9b715.gif)

**Comment by richard-cox** [comment]
@Sean-McQ This was broken via https://github.com/rancher/dashboard/pull/4325, reverting commit d7244ac brings the header back

**Comment by sgapanovich** [comment]
### Test Environment: ###
same as when the issue was logged

----------

### Testing: ###
-verified that top menu items are 
  - present when clicked
      - in case of cluster dropdown and user menu
  - interactive 
      - "import yaml" opens a window to paste/create a yml
      - "kubectl shell" start a new kubectl shell
      - "Download KubeConfig" downloads cluster config
      - "Resource Search" opens search window
      - three dots menu has 2 options and they work as expected
