### ISSUE TITLE
Global, Cluster and Project Role Detail page detail sections show missing info

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4594]
The Detail pages for Roles of type Global, Cluster and Project all have missing / misleading information in.

Global
- Shouldn't show empty 'name'
- Should show description (entirely missing)
  ![image](https://user-images.githubusercontent.com/18697775/142601204-95e1a4f3-457b-4a04-badc-f613ae3cf8fc.png)

Cluster
- Shouldn't show empty 'name'
- Should show description (empty value)
- (also title prefix probably needs separator (`RoleTemplate: Cluster - Cluster Member`)
  ![image](https://user-images.githubusercontent.com/18697775/142601339-4740d793-d887-48c4-b6f7-a0a5e7b7898b.png)

Project
- Shouldn't show empty 'name'
- Should show description (empty value)
- (would need matching title prefix separator (`RoleTemplate: Project/Namespaces - Create Namespaces)
![image](https://user-images.githubusercontent.com/18697775/142601533-cc3893de-d71d-48b0-9417-081b7467c4fe.png)

Changes to fix these will most probably all be in the model files

**Comment by nwmac** [comment]
@aalves08 This is probably due to changes made in the models that we have for the resources - @richard-cox can help explain that to you.

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.6.3                                  |
| Rancher cluster type    | Docker                                  |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | not applicable                          |
| Downstream K8s version  | not applicable                          |
| Browser type            | Opera GX                                |
| Browser version         | LVL3 (core: 83.0.4254.46) (x86_64)      |

## Reproduction steps


1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> `Users & Authentication` -> `Roles`
3. Test Global Tab
   1. With `Global` tab selected by default
   2. Click a role, e.g. `Administrator`
   3. Verify that a name value **IS NOT PRESENT**
   4. Click the back arrow in the browser
4. Test Cluster Tab
   1. Click `Cluster` tab
   2. Click a role, e.g. `Manage Cluster Backups`
   3. Verify that a name value **IS NOT PRESENT**
   4. Click the back arrow in the browser
5. Test Projects/Namespaces Tab
   1. Click `Projects/Namespaces` tab
   2. Click a role, e.g. `Kubernets admin`
   3. Verify that a name value **IS NOT PRESENT**
   4. Click the back arrow in the browser
  
#### RESULT

There is no name value present for Global, Cluster, and Projects/Namespaces

#### EXPECTED RESULT

For there to be name values displayed for these fields

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-fc01fff137321c3016f7e6c583bf3cb26df03768-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | not applicable                                     |
| Downstream K8s version  | not applicable                                     |
| Browser type            | Opera GX                                           |
| Browser version         | LVL3 (core: 83.0.4254.46) (x86_64)                 |

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> `Users & Authentication` -> `Roles`
3. Test Global Tab
   1. With `Global` tab selected by default
   2. Click a role, e.g. `Administrator`
   3. Verify that a name value is present
   4. Name value successfully displays for `Global` level
   5. Click the back arrow in the browser
4. Test Cluster Tab
   1. Click `Cluster` tab
   2. Click a role, e.g. `Manage Cluster Backups`
   3. Verify that a name value is present
   4. Name value successfully displays for `Cluster` level 
   5. Click the back arrow in the browser
5. Test Projects/Namespaces Tab
   1. Click `Projects/Namespaces` tab
   2. Click a role, e.g. `Kubernets admin`
   3. Verify that a name value is present
   4. Name value successfully displays for `Projects/Namespaces` level 
   5. Click the back arrow in the browser

### RESULT

Checks were successful!
