### ISSUE TITLE
["Enhancement" request] Local user password length 

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4596]
**Detailed Description**
In SUSE Rancher 2.6.3-rc1 the minimum password length for local users is 12 characters.
For testing purposes this is a bit too "difficult". (I perfectly understand the security standpoint behind, though.) 

**Context**
Would it be possible to have a check box or other way to override this configuration for testing purposes?

![image](https://user-images.githubusercontent.com/86831399/142629710-88d47ddc-1962-4fcf-848a-cabd166fd80e.png)

**Comment by richard-cox** [comment]
I'm not 100% sure, but i think the restriction is only checked on change not when initially set, so you should be able to get around this by setting it manually at install time

**Comment by peteingithub** [comment]
I created a new local user in Users and Authentication. Errored out with a pw too short.

But you are partly right. The initial password for new user must be 12 chars, but you can change it to shorter one later. :)

A short admin password can be set manually during the deployment. Can I also create other users at this stage?

**Comment by richard-cox** [comment]
I don't think you should be able to _change_ a user's password to anything less than 12 characters at any point.

I also don't think you should be able to _create_ a user with an invalid password, if that's the case it's probably a bug.

Setting the password at install time I think only works with the default admin.

**Comment by peteingithub** [comment]
OK. The UI does not complain if admin sets a short password to an existing user. The password gets corrupted, though, and user can not log in anymore with the old or the new password.

**Comment by peteingithub** [comment]
Tested some more. 
If admin sets too short password, no error is displayed.
The password does not get changed, though, and the old stays active.

**Comment by vincent99** [comment]
That was https://github.com/rancher/dashboard/pull/4583 .

If you want a shorter password length, it's a setting, set it lower.  `/v3/settings/password-min-length`

**Comment by peteingithub** [comment]
Thanks @vincent99  I'm cool with the solution.
From my standpoint the issue can be closed.
