### ISSUE TITLE
"Restore snapshot" action is not available in Cluster management page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4606]
**on 2.6.3-rc1**

- Deployed an RKE1 custom cluster
- Take a few snapshots
- On the cluster Management page, `Restore Snapshot` action is not available
- I can access `Restore` when I navigate to Cluster details --> Snapshot -->Select snapshot --> Restore.

Expected.
"Restore snapshot" action Should be available in Cluster management page

**Comment by nwmac** [comment]
Add another action for `provisioning.cattle.io.cluster` - there is already 'Take Snapshot'.

There is already a dialog `PromptRestore` that is currently used to show just a confirmation - I suggest you modify this dialog so it can also be used in a mode where instead of showing confirmation content, it shows a select control that allows the user to select which snapshot to restore from.

The logic for restoring a snapshot is already in the `PromptRestore` model, so by leveraging this dialog, you won't need to duplicate this code.

**Comment by gaktive** [comment]
This has been also reported missing in 2.6.2.

**Comment by catherineluse** [comment]
While talking about this issue, Neill and I found out that the cluster model's preexisting method to get the snapshots of a cluster (`etcdSnapshots`) seems to always return an empty array. It might be a separate backend issue to make `etcdSnapshots` included in the cluster's `status` property, as the `etcdSnapshots` getter is expecting it to be. https://github.com/rancher/dashboard/blob/master/models/provisioning.cattle.io.cluster.js#L470

**Comment by richard-cox** [comment]
@catherineluse I think I hit something related to your comment. For an RKE2 cluster, after taking some snapshots, the  `Restore Snapshot` button is available.... however there's no snapshots presented in the modal

![image](https://user-images.githubusercontent.com/18697775/149531711-8547ca11-9566-40ba-9674-550c1263f9aa.png)

**Comment by catherineluse** [comment]
Is that the modal from the cluster management page from https://github.com/rancher/dashboard/pull/4677?

**Comment by richard-cox** [comment]
@catherineluse That's the one, yep

**Comment by sowmyav27** [comment]
@timhaneunsoo Please validate:
1. "Restore snapshot" action is available on the cluster in Cluster management page.
2. Validate if "Restore snapshot" action on the cluster works. (cluster must be restored to the selected snapshot state)

**Comment by neillsom** [comment]
Issue picked up in rancher/dashboard#5011

**Comment by anupama2501** [comment]
Rancher version `a2ef67a` - docker & helm

As an admin, I see restore snapshot is available in the cluster management page for an `RKE1` node driver clusters, but I get `no matching options` even though there are three snapshots on the cluster. Same as https://github.com/rancher/dashboard/issues/4606#issuecomment-1013169866

<img width="500" alt="snapshotrestore" src="https://user-images.githubusercontent.com/38144301/157554927-8210a04c-4cde-49ee-a2b0-3bf9164fa50e.png">

**Comment by catherineluse** [comment]
I opened this separate issues about how the restore snapshot modal cannot list snapshots https://github.com/rancher/dashboard/issues/5131

**Comment by nwmac** [comment]
Looks like this PR switched over to using Steve rather than using Norman for RKE1 and Steve for RKE2 - https://github.com/rancher/dashboard/pull/5196/files

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head d604b7e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: EC2 RKE2 aws node driver
----------

### Testing: ###

Tested this issue with the following steps:
1. Deployed an ec2 node driver RKE2 cluster on rancher - 3 etcd, 2 cp and 3 worker nodes
2. Take a snapshot
3. Snapshots are listed in Cluster management --> Cluster details --> Snapshots tab
4. Click on Restore on the cluster
5. The snapshot names are seen as undefined

**Result** - Pass

Restore Snapshot is available 
![image.png](https://zube.io/files/rancher/7791f0c0314388990aef88f86d23728f-image.png)
