### ISSUE TITLE
While Installing CSI/CPI feature charts for vsphere,install into project shows ID of the project rather than the name of the project

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4607]
**Rancher Server Setup**
- Rancher version: `v2.6.2`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.3+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: v1.21.6
- Cluster Type (Local/Downstream): `Downstream infrastructure provider vsphere 3 worker, 1 etcd, 1 cp`

**Describe the bug**
When installing CSI/CPI charts in the vsphere cluster, the `installing into project` shows up as ID instead of displaying the project name

**To Reproduce**
create a downstream vsphere node driver RKE1 cluster 
From explore cluster --> apps & market --> select CPI chart 
Proceed to the page where we select a project for `Installing into Project`
Verify the project the chart to be installed in

**Result**
Project Id is displayed instead of a name

**Expected Result**
Expected the project name to be displayed
On 2.5:
<img width="1414" alt="Screen Shot 2021-11-19 at 5 28 22 PM" src="https://user-images.githubusercontent.com/38144301/142709506-9a26ef7a-d890-40e7-83f1-6cd9b4c72e58.png">

**Screenshots**
<img width="600" alt="Screen Shot 2021-11-19 at 5 25 11 PM" src="https://user-images.githubusercontent.com/38144301/142709385-0a8fab15-d8bc-4951-9cf0-eb4e9d7b2196.png">

**Additional context**
This is not the case in 2.5.11. Seen on 2.6.1

**Comment by richard-cox** [comment]
I've taken a quick look at this and it seems like there are (incorrectly) no projects being supplied to the drop down... so it's showing the raw value supplied to it

**Comment by Shavindra** [comment]
Can you clarify the additional context part? I am looking at this I can't really replicate it?

**Comment by anupama2501** [comment]
@Shavindra The issue is not seen if tried on rancher version 2.5.11 and the issue is seen on the rancher version v2.6.1 and above versions.
This is seen with vsphere node driver cluster type.

**Comment by Shavindra** [comment]
I was able to replicate this accidentally. I had the window left open. After sometime I noticed the name had changed to ID. I guess some background sync might have mutated the `project.nameDisplay`. I was also told might be able to replicate consistently with VSphere Node driver. I don't have this. I suggested a possible solution for what I found. I will leave it with @codyrancher wrt VSphere.

**Comment by codyrancher** [comment]
The only way i've been able to reproduce this is by leaving the page over for  a long while and deleting the cluster. I've tried on both vsphere and digital ocean. If the only time this surfaces is when deleting a cluster I think this issue can be resolved.

**Comment by slickwarren** [comment]
tested on v2.6-head (024e6fa) with rke1 and rke2 1.23 clusters and was not able to reproduce this issue for cpi/csi charts. 
Current behavior is, chart install defaults to `system` project, where kube-system is installed.
