### ISSUE TITLE
Pods metrics are not seen on the Cluster dashboard

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4609]
**on 2.6-head commit id: `e322f8f`**

- Deployed a 1.22/1.21 k8s rke1 cluster custom/DO node driver cluster
- In the cluster explorer --> Cluster Dashboard --> Pods section is not available

<img width="1666" alt="Screen Shot 2021-11-20 at 9 12 12 PM" src="https://user-images.githubusercontent.com/26032343/142750484-06a1dd17-4c74-4f73-a6f1-969ca154a74e.png">

**Comment by nwmac** [comment]
@sowmyav27 Can you capture the browser console log and attach to this issue. Thanks.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `4375161`**

Pods metrics are seen
<img width="1673" alt="Screen Shot 2021-11-27 at 6 16 38 PM" src="https://user-images.githubusercontent.com/26032343/143726277-cf325b78-609f-4002-b558-30d98c4e2483.png">
