### ISSUE TITLE
OPA gatekeeper customize button color makes it look like disabled.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#461]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard

**Result:**
Customize button appears as it is disabled.
<img width="1578" alt="Screen Shot 2020-03-31 at 1 25 28 PM" src="https://user-images.githubusercontent.com/60111667/78075078-b63d2c00-7358-11ea-8854-45c50903e014.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - 1575d706a
- Installation option (single install/HA): Single

**Comment by tfiduccia** [comment]
Button color needs to be addressed not just for OPA but all create pages where Cancel button also looks like this (Looks disabled) in both light and dark.

**Comment by lvuch** [comment]
<img width="940" alt="Screen Shot 2020-04-01 at 10 02 30 AM" src="https://user-images.githubusercontent.com/3013118/78165284-f1466a80-73ff-11ea-9818-c9a0d426b47b.png">
<img width="1218" alt="Screen Shot 2020-04-01 at 9 56 24 AM" src="https://user-images.githubusercontent.com/3013118/78165288-f3102e00-73ff-11ea-91b9-524a58971733.png">

**Comment by tfiduccia** [comment]
@vincent99, @lvuch  and I discussed and decided to change the focus color so we can use the blue border. Sending back to lauren for color decision and implementation.

**Comment by tfiduccia** [comment]
Fixed
