### ISSUE TITLE
Default Storage value of PVC is 1073741824 and editing it does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4611]
**on 2.6-head commit id: `e322f8f`**

- Deploy an EKS cluster
- Create a PVC
- Default Storage value of PVC is 1073741824
- Edit and set it to 1, it gets set to 1073741824
- In 2.6.2, default value is 10Gb

**Comment by richard-cox** [comment]
@mantis-toboggan-md This should be resolved by your PR https://github.com/rancher/dashboard/pull/4601

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `4375161`**

- Deploy an EKS cluster
- Create a PVC
- Default Storage value of PVC is 10G
