### ISSUE TITLE
Drop-down UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#462]
Make all drop-downs work like Namespace drop-down

- [ ] Move focus to first time in drop-downs

- [ ] Make Tab & Arrow keys work on drop-down items

![image](https://user-images.githubusercontent.com/11514927/78076767-e639fe80-735b-11ea-9cb5-a857e7af649a.png)

**Comment by lvuch** [comment]
This will have to wait until further notice. At some point all of the logic for dropdowns will change unifying the different formats.
