### ISSUE TITLE
When provisioning a GKE cluster in Rancher, cluster can be created with mismatching k8s versions for nodes/cluster

### ISSUE THREAD

**Issue by jtravee** [rancher/dashboard#4622]
**Setup**
- Rancher version: 2.5

**Describe the bug**
When provisioning a cluster with GKE in Rancher, the default k8s version for the cluster is 1.20.11-gke.1801, but the default k8s for the node pool is 1.21.5-gke.1302. Rancher will let you click Create and provision the cluster with these settings. 

User could also click into the k8s version under Cluster Options (and select the same k8s version shown or a different one), and then the version for node pool will update to match it. But if the user does not do this and proceeds to try and create the cluster, this mismatch persists and a cluster shouldn't be able to be created as such.

**To Reproduce**
1. Add a cluster to Rancher using GKE
2. Name cluster, enter Google Project ID
3. I left it at default us-central1-c, but also tested on other zones under cluster location with the same outcome
4. Under Cluster Options, note the k8s version (1.20.11-gke.1801) and under Node Pools, note the version (1.21.5-gke.1302)
5. Name the node pool, then click Create

**Result**
A cluster is able to be created with a mismatch between k8s versions for the cluster and the node pools without any error message.

**Expected Result**
An error message notifying user to adjust k8s cluster version in dropdown; alternatively, the k8s versions should default to matching versions without having to click the dropdown.

**Screenshots**
![image](https://user-images.githubusercontent.com/87146683/142949390-f06d48a3-11b1-48a6-8170-5723f0f2d0ea.png)
![image](https://user-images.githubusercontent.com/87146683/142949409-89c8b657-9a69-4b22-9085-1eb5841cc8d4.png)

**Comment by gaktive** [comment]
Closing for now until we can repro this.
