### ISSUE TITLE
Issue with Machines pools page for Azure RKE1 cluster 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4624]
**on 2.6-head commit id: `744f32fe`**

- Deploy an Azure cluster RKE1 node driver
- The cluster failed to come up with resource constraint issue.
- Click on cluster in the cluster management page
- The Ui is:

<img width="1680" alt="Screen Shot 2021-11-22 at 9 17 59 PM" src="https://user-images.githubusercontent.com/26032343/142977491-165aa8c1-28f3-4da5-a5b3-a184e750b690.png">

**Comment by rak-phillip** [comment]
@sowmyav27 I've been trying to reproduce but I can't create a scenario where error text or state descriptions causes the table to expand, making it difficult to debug this issue. Do you think we can get some repro steps?

**Comment by sowmyav27** [comment]
**Verified on 2.6-head `4375161`**

The overflow of the error message wen an RKE1 Azure node driver cluster is deployed is seen fixed.
