### ISSUE TITLE
Allow user to also create namespaces when creating a project

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4625]
Currently when setting up a project the user has to complete the initial set of requirements, save, and then one by one add namespaces in a separate view. 

It would be a nice improvement to allow the user to specify one or more namespaces in the create project view to also create.

Notes
- Would need to think of an alternative to tabs in tabs (namespace create shows two tabs - Container Resource Limit and the usual labels/annotations)
- Namespace limits supplied in the project should be handled by namespace container limits (defaults, collectively exceeding limits)
- Would need to nicely communicate project save success but specific namespace failure

**Comment by davidnuzik** [comment]
+1 to this

**Comment by richard-cox** [comment]
This is pretty useful (the UX is normally always create projects --> create namespaces), however difficult to neatly present. 

Create Project
![image](https://user-images.githubusercontent.com/18697775/200899614-64c15617-dc11-4562-9f13-fc7817979f08.png)

Create Namespace 
![image](https://user-images.githubusercontent.com/18697775/200899704-cf4d1965-2255-45f4-8bcc-d19d26e06e5d.png)

Could something like the new workloads and multi-container ux could work here too? A horizontal tab containing allowing the user to add zero to many namespaces?
