### ISSUE TITLE
"helm3-library" partner and non-partner chart error while upgrading in Multi-cluster apps

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/dashboard#4627]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Describe the bug:**
While testing this [issue](https://github.com/rancher/rancher/issues/35353). `Alcide` and `aws-event-sources` partner charts are throwing error on chart "upgrade" option in rancher v2.6.3-rc1

**Rancher Installation option (Docker install/Helm Chart):** Docker

**Steps to reproduce:**
1) Deploy rancher v2.6.2 and enable legacy feature.(from side-panel -> Global Settings -> Feature Flags -> enable legacy)
2) Create `1.21.6` downstream k8s cluster.
2) Deploy `alcide` and `aws-event-sources` partner chart from helm3 catalog (Under Multi-cluster Apps section) on downstream cluster.
3) Upgrade rancher to v2.6.3-rc1.
4) Both the partner charts are present under `Multi-Cluster Apps` section but when I am trying to upgrade chart by going to "Upgrade" option, getting this error: Cannot read property 'match' of undefined Reload to try again or log out (attached ss)
![ss1](https://user-images.githubusercontent.com/36376154/142978477-2e6ba3cb-e46a-4c5d-bb36-4a3150bbe8f0.png)

**Expected result :** Should be able to upgrade chart from the UI

**Comment by catherineluse** [comment]
The page where you upgrade that Helm chart is making an API call to this URL:

```
<rancher-server-url>/v3/templates/cattle-global-data:helm3-library-alcide-advisor-cronjob?clusterName=undefined
```

In Rancher v2.6.2, the response to that API call includes this property `versionLinks`:

```
"versionLinks":{
      "2.1.0":"https://143.198.231.170/v3/templateVersions/cattle-global-data:helm3-library-alcide-advisor-cronjob-2.1.0"
   }
```

But in v2.6.3-rc1, the response to that API call returns an empty object for `versionLinks`, and that is where it breaks:

```
"versionLinks":{}
```
I'll see if there's a way to make it say "there are no compatible versions to upgrade to" or something to that effect.

**Comment by rishabhmsra** [comment]
I am running into same error while upgrading **non-partner** charts form **helm3-library** catalog. Please see the below details:

**Describe the bug:**
While testing this [issue](https://github.com/rancher/rancher/issues/35351). **Non-partner** charts are throwing error on chart "upgrade" option in **rancher v2.6.3-rc2**

**Rancher Installation option (Docker install/Helm Chart):** Docker

**Steps to reproduce:**

1) Deploy rancher v2.6.2 and enable legacy feature.(from side-panel -> Global Settings -> Feature Flags -> enable legacy)
2) Create 1.21.6 downstream k8s cluster.
3) Deploy `mariadb` non-partner chart from `helm3-library` catalog (Under Multi-cluster Apps section) on downstream cluster.
4) Upgrade rancher to v2.6.3-rc2.
5) `mariadb` non-partner charts is present under Multi-Cluster Apps section but when I am trying to upgrade chart by going to "Upgrade" option, getting this error: `Cannot read property 'match' of undefined Reload to try again or log out`. (attached ss)
![chart_upgrade_error_after_rancher_upgrade](https://user-images.githubusercontent.com/36376154/143243543-9acd032f-a953-4b7b-b7a6-9fe66f70b483.png)

**Comment by catherineluse** [comment]
This PR https://github.com/rancher/dashboard/issues/4627 makes it so that if you have a legacy multicluster app where the max Rancher version is v2.6.2, then you upgrade Rancher to v2.6.3, then try to upgrade the app, you can at least see the upgrade form now. Previously it was just erroring out.

But now if you make a change to the app template and click upgrade, you get an error from the back end saying the version is incompatible. I think this means the back end needs another change to allow legacy apps to be updated even if their chart version is incompatible with Rancher.

**Comment by catherineluse** [comment]
I closed my PR addressing this issue because it was a stopgap measure, whereas this issue is tracking the work of solving the same problem in a better way and it's also in v2.6.3.  https://github.com/rancher/rancher/issues/35680. When that work is done, I believe no UI work would be needed to address this issue.

**Comment by catherineluse** [comment]
This issue seems fully addressed by https://github.com/rancher/rancher/pull/35711 and I believe no UI work is necessary. I did the same steps in `v2.6-head` and it worked.

**Comment by rishabhmsra** [comment]
**Verified on rancher v2.6-head (e62e1ae)**

**Rancher Installation option (Docker install/Helm Chart):** Docker

**Validation steps:**

1. Deployed rancher v2.6.2 and enabled legacy feature.(from side-panel -> Global Settings -> Feature Flags -> enable legacy)
2. Created a 1.21.6 downstream k8s cluster.
3. Deployed alcide and aws-event-sources partner chart and mariadb non-partner chart from helm3 catalog (Under Multi-cluster Apps section) on a downstream cluster.
4. Upgraded rancher to v2.6-head (e62e1ae).
5. Upgraded the charts from multicluster app section. Error page is NOT coming up and charts can be successfully upgraded.

**Result:**
- Charts can be upgraded from multicluster app section. Working as expected.
