### ISSUE TITLE
Table column headers aren't vertically aligned

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4629]
![image](https://user-images.githubusercontent.com/18697775/143015303-2f089983-cf5e-4265-9856-870e65322144.png)

There's a difference between sorted and unsorted columns

**Comment by nwmac** [comment]
@aalves08 A minor one - an example of this is on the DameonSets view with the Endpoints column:

![image](https://user-images.githubusercontent.com/1955897/151155036-6d31ccd2-7be4-43c9-bfed-0e326606ea80.png)

**Comment by markusewalker** [comment]
Verified `v2.6-head` https://github.com/rancher/rancher/commit/7a88105e02d8b779a486a544cc36b599b498d458.

**ENVIRONMENT DETAILS**
- Ubuntu 20.04
- Docker Install: 20.10
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/7a88105e02d8b779a486a544cc36b599b498d458 -> Verified Version

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher `v2.6-head` and navigated to Rancher UI > Create.
2. Toggled RKE1 to RKE2/K3s and choose node driver to create a RKE2 cluster.
3. Navigated to top-left dropdown menu > Explore Cluster > created RKE2 cluster > Workload > Deployments.
4. View the headers and verified that they are equally spaced:
![image](https://user-images.githubusercontent.com/52591819/164780195-5f88b4cd-fd64-4319-ac26-50d9fd3a9ace.png)
5. Opened the developer tools and verified that the `.sortable-table` element for each of the sections (State, Name, Image, Ready, Current, Desired, Age, Health) all showed the following:
![image](https://user-images.githubusercontent.com/52591819/164780236-4cebf541-f72f-48d0-9d0c-e7da6e9d61bd.png)
6. Repeated step 4-5 for CronJobs, DaemonSetes, Jobs, StatefulSets, Pods; all have the proper vertical alignment.
