### ISSUE TITLE
Improvements to the Rollback Diff view

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4636]
- Add in ability to switch between the side-by-side and inline diff
- Collapse (or hide) the fields that are non-standard - check the Ember UI for the list of these

**Comment by ronhorton** [comment]
**Reopening** `2.6-head Commit ID 20d20a3`

1. created deployment - nginx:1.21.3
2. edit config on new deployment - change to nginx:lastest
3. Show diff good - extraneous information not shown (such as kind:)
4. Click Rollback

Expected: deployment rolls back to original value

Actual: error that the deployment can not be found (reproducible 100%)
<img width="607" alt="Screen Shot 2022-02-17 at 3 50 40 PM" src="https://user-images.githubusercontent.com/89212856/154569197-45eff568-cbdc-4b2c-baff-a818ec20bc4e.png">

**Comment by nwmac** [comment]
Caused by same issue as https://github.com/rancher/dashboard/issues/4664

PR in review

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
