### ISSUE TITLE
"library" catalog partner and non-partner charts error while upgrading in Multi-cluster Apps

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/dashboard#4645]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Describe the bug:**
While testing these issues([issue1](https://github.com/rancher/rancher/issues/35352), [issue2](https://github.com/rancher/rancher/issues/35347)) `partner` and `non-partner` charts under `library` catalog are throwing error on chart "upgrade" option in rancher v2.6.3-rc2

**Rancher Installation option (Docker install/Helm Chart):** Docker

- **Non Partner Charts**
**Steps to reproduce:**

1) Deploy rancher v2.6.2 and enable legacy feature.(from side-panel -> Global Settings -> Feature Flags -> enable legacy)
2) Create 1.21.6 downstream k8s cluster.
3) Deploy `argo-cd, chartmuseum and mariadb` non-partner chart from "library" catalog (Under Multi-cluster Apps section) on downstream cluster.
4) Upgrade rancher to v2.6.3-rc2.
5) `argo-cd, chartmuseum and mariadb` charts are present under Multi-Cluster Apps section but when I am trying to upgrade chart by going to "Upgrade" option, getting this error: Cannot read property 'match' of undefined Reload to try again or log out (attached ss)
![upgrade_error_after_upgrading_rancher](https://user-images.githubusercontent.com/36376154/143237305-b358bbee-4089-42d1-893e-41e89a66f8eb.png)

- **Partner Charts**
**Steps to reproduce:**

1) Deploy rancher v2.6.2 and enable legacy feature.(from side-panel -> Global Settings -> Feature Flags -> enable legacy)
2) Create 1.21.6 downstream k8s cluster.
3) Deploy `tidb-operatot and traefik` partner charts from "library" catalog (Under Multi-cluster Apps section) on downstream cluster.
4) Upgrade rancher to v2.6.3-rc2.
5) `tidb-operatot and traefik` charts are present under Multi-Cluster Apps section but when I am trying to upgrade chart by going to "Upgrade" option, getting this error: Cannot read property 'match' of undefined Reload to try again or log out (attached ss)
![upgrade_error_after_upgrading_rancher](https://user-images.githubusercontent.com/36376154/143238185-e672654c-cdb3-44ac-b7ef-02f035b66afe.png)

**Comment by gaktive** [comment]
@catherineluse may have addressed this in her PRs.

**Comment by nwmac** [comment]
@catherineluse Could you validate this one, please

**Comment by nwmac** [comment]
Believe this is same issues as others - #4628, #4627, #4655 - awaiting backend fix - https://github.com/rancher/rancher/issues/35680

**Comment by catherineluse** [comment]
This issue seems fully addressed by https://github.com/rancher/rancher/pull/35711 and I believe no additional UI work is necessary to fix it. I did the same steps in `v2.6-head` and it worked.

**Comment by rishabhmsra** [comment]
**Verified on rancher v2.6-head (04520c0)**

**Rancher Installation option (Docker install/Helm Chart):** Docker

**Validation steps:**

- Deploy rancher v2.6.2 and enable legacy feature.(from side-panel -> Global Settings -> Feature Flags -> enable legacy)
- Create 1.21.6 downstream k8s cluster.
- Deploy argo-cd, chartmuseum, mariadb, tidb-operatot and traefik charts from library catalog on downstream cluster.
- Upgrade rancher to v2.6-head.
- Upgrade the charts from multicluster app section. Error page is NOT coming up and charts can be successfully upgraded.

**Result:**
- Charts can be upgraded from multicluster app section. Working as expected.
