### ISSUE TITLE
Make helm chart list filters row responsive

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4646]
Currently the control to filter by text shrinks to nothing whilst others don't forcing out the width of the page.

These just need wrapping in a sensible way.

Note - To see OS drop down see description in https://github.com/rancher/dashboard/pull/4639#issue-787474857

![image](https://user-images.githubusercontent.com/18697775/143259411-58e0059d-4a03-4320-a375-daf510ed1753.png)

**Comment by aalves08** [comment]
Connected to PR https://github.com/rancher/dashboard/pull/4884 which fixes this issue.
