### ISSUE TITLE
Project/Namespace filter doesn't group namespaces on first load

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4647]
- in some pages the namespaces are not grouped by project

To reproduce
- Refresh on a cluster dashboard page, for instance `/c/c-m-wmr9mwsp/explorer`
- Click on the Project/Namespace filter and note all namespaces are grouped into the 'Not in a project' section
- Navigate to Cluster --> Project/Namespaces, for instance `c/c-m-wmr9mwsp/explorer/projectsnamespaces`
- Click on the Project/Namespace filter again and note all the grouped namespaces

I'm guessing this is due to models/namespace's groupByLabel not finding a `this.project`.... caused by a lack of management projects in the store. Should just be able to pre-fetch these where the filter is used?

![image](https://user-images.githubusercontent.com/18697775/143266705-669cba92-92e8-4872-8efe-925a4b38ecd0.png)

![image](https://user-images.githubusercontent.com/18697775/143266786-e393cec9-ee7a-4154-bbc8-0157b1f30f6b.png)

**Comment by sowmyav27** [comment]
**On 2.6.2 reproduced the issue by following these steps**

- Refresh on a cluster dashboard page, for instance /c/c-m-wmr9mwsp/explorer
- Click on the Project/Namespace filter and note all namespaces are grouped into the 'Not in a project' section

**On 2.6-head commit id: `4375161`**

- Refresh on a cluster dashboard page, for instance /c/c-m-wmr9mwsp/explorer
- Click on the Project/Namespace filter and note all namespaces are grouped as expected
