### ISSUE TITLE
"Upgrade" option for charts other than longhorn under "Legacy" apps not working

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/dashboard#4655]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Describe the bug:**
Upgrade option for charts other than longhorn chart under "legacy" apps is not working in rancher `v2.6.3-rc2`. After clicking upgrade option, upgrade page is NOT opening, neither it's showing any error page. Please see the steps below.

**Rancher Installation option (Docker install/Helm Chart):** Docker

**Steps to reproduce:**
1) Deploy rancher v2.6.2 and enable legacy feature.(from side-panel -> Global Settings -> Feature Flags -> enable legacy)
2) Create 1.21.6 downstream k8s cluster.
3) Goto cluster -> Legacy -> project -> select `Project:System` form the drop-down -> Launch
3) Deploy `argo-cd`, and `aws-event-sources` chart from catalog on downstream cluster.
4) Upgrade rancher to v2.6.3-rc2.
5) `argo-cd`, `aws-event-sources` charts would be present under "legacy apps". Click on upgrade option of the chart. Upgrade page would not open, instead it will remain on the same page after the loading screen (attached ss).
![charts_active](https://user-images.githubusercontent.com/36376154/143461531-305829c4-54cd-4a3b-9a79-9ea6c7d04601.png)

**Comment by nwmac** [comment]
I believe this is the same issue as https://github.com/rancher/rancher/issues/35670

**Comment by catherineluse** [comment]
This issue seems addressed by https://github.com/rancher/rancher/pull/35711 and I believe no additional UI work is necessary to fix it. I did the same steps in `v2.6-head` and it worked.

**Comment by rishabhmsra** [comment]
**Verified on rancher v2.6-head (e62e1ae)**

**Rancher Installation option (Docker install/Helm Chart):** Docker

**Validation steps:**
- Deploy rancher v2.6.2 and enable legacy feature.(from side-panel -> Global Settings -> Feature Flags -> enable legacy)
- Create 1.21.6 downstream k8s cluster.
- Goto cluster -> Legacy -> project -> select Project:System form the drop-down -> Launch
- Deploy argo-cd, and aws-event-sources chart from catalog on downstream cluster.
- Upgrade rancher to v2.6-head

**Result:**
- Able to upgrade the charts under legacy section after upgrading rancher from 2.6.2 to 2.6-head. Working as expected.
