### ISSUE TITLE
Side nav collapses top-level items when clicked

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4657]
Explore a cluster.

(You'll see that the 'Cluster' section is not expanded on entry)

In the side nav, click on one of the other top-level groups, e.g. 'Storage'.

Now, click on 'Cluster' in the side nav - the section will expand and then immediately collapse.

This is a regression.

I think also related - install Monitoring - click on 'Monitoring' and then click on 'Monitors' - the side nav collapses and Monitoring is not expanded, which it should be.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `46eb9d4`**

- Explore a cluster (RKE2)
- Cluster Section is expanded on entry
-  install Monitoring - click on 'Monitoring' and then click on 'Monitors' - the side nav does not collapse and Monitoring remains exapanded.
