### ISSUE TITLE
Rancher 2.6.2 ui namespace filter not work correct

### ISSUE THREAD

**Issue by wirwolf** [rancher/dashboard#4659]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): kubespray
- Proxy/Cert Details: Does not matter

**Information about the Cluster**
- Kubernetes version: 1.21.1
- Cluster Type (Local/Downstream): local

**Describe the bug**
Filter by namespace sometimes work incorrect 

**To Reproduce**
open cluser dashboard page
seelct namespace
refresh page

**Result**
I see all resources 

**Expected Result**
After refrash page filter by namespace apply, and remove all resources not linked for filter

**Screenshots**
![image](https://user-images.githubusercontent.com/8457572/141299056-fcecb9d8-2e0c-4131-85f7-3a1e6dc74903.png)

**Additional context**
@ibuildthecloud @vincent99 @westlywright @lvuch

**Comment by pacholoamit** [comment]
Having issues regarding this as well. The namespace filter is problematic
![image](https://user-images.githubusercontent.com/69985528/143788228-6f85c80a-98fe-4262-a93f-8140b99b316f.png)

Also the Projects filtering... When I'm on the deployments tab it looks like this...
![image](https://user-images.githubusercontent.com/69985528/143788261-4ea57973-1c4a-4b2d-a795-ce3ff5821a1e.png)

When I go to the Projects/Namespaces tab and check it again, it looks like this:

![image](https://user-images.githubusercontent.com/69985528/143788291-3754fac9-0a97-40fd-bb41-3ead59b3bc92.png)

**Comment by vincent99** [comment]
These are all duplicate issues already fixed for 2.6.3.  Spam @'ing people who work on backend, design, or longer work for us at all is not helpful.

https://github.com/rancher/dashboard/issues/4647
https://github.com/rancher/dashboard/issues/3523

https://github.com/rancher/dashboard/pull/4623
https://github.com/rancher/dashboard/pull/4650

**Comment by wirwolf** [comment]
@vincent99 because some important bugs in rancher can lie for half a year without any status. I tagged only frontend devs(I check in statistic who contributed in rancher/ui  very often)

**Comment by vincent99** [comment]
You notified:
- The chief architect of the backend, that has basically never touched the UIs
- Me
- A former employee
- And our designer

You haven't been ignored for a year an a half here, and it's not very polite to preemptively spam individual random people's notifications before an issue has had a chance to go through any kind of triage.  (Especially when it's already been reported separately and resolved, but you probably didn't know this was the appropriate repo to look).

**Comment by baspenny** [comment]
@vincent99 Thanks so much for pointing this out. Missed it I think. Thanks again for your hard work on this fantastic project!
