### ISSUE TITLE
Missing labels on Cluster Manager

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4666]
Issue description:

Looking at the deployment labels, I can see them all in the Cluster Explorer.

However only some of them are visible in Cluster Manager.

Business impact: None

Troubleshooting steps: None

Repro steps:

- Deploy a workload with labels on Rancher.
- Check on the Cluster Manage deployment UI.
- Check on the Cluster Explorer deployment UI.

Actual behavior:

Only some labels are visible on the Cluster Manager UI.

Expected behavior:

All labels visible in Cluster Manager , same as Cluster Explorer

Files, logs, traces:
![image-2021-05-04-16-23-11-215.png](https://zube.io/files/rancher/b22db0aa6d438cffb27b179358023663-image-2021-05-04-16-23-11-215.png)![image-2021-05-04-16-23-50-510.png](https://zube.io/files/rancher/a228dbfaf95cb61784e670af2e9eb812-image-2021-05-04-16-23-50-510.png)

Internal reference: SURE-2957

**Comment by gaktive** [comment]
To clarify, this was reported in 2.5.7.

**Comment by leodotcloud** [comment]
<img width="212" alt="Screen Shot 2022-01-03 at 3 19 49 PM" src="https://user-images.githubusercontent.com/19392926/147990854-74a2f175-3157-4771-a1ee-2b5de53391a2.png">
<img width="341" alt="Screen Shot 2022-01-03 at 3 19 57 PM" src="https://user-images.githubusercontent.com/19392926/147990855-88d330e3-2039-4bf3-b61f-f12d9ee5ed7e.png">

There seem to be two different keys for labels under the deployment when viewed in API. The old UI seems to be showing info from `labels` whereas the new UI seems to be displaying info from `workloadLabels`.

**Comment by richard-cox** [comment]
Cluster Manager is no longer supported in 2.6. @gaktive is the ask here to fix cluster manager in 2.5.x, which I'm not sure we should be doing either?

**Comment by gaktive** [comment]
@richard-cox if we can confirm this is working in Vue, then we can pass this to QA as a "won't fix" since the expectation isn't to update Ember unless we embed a page.

**Comment by gaktive** [comment]
Alternately, we can just pass this to QA to verify.

**Comment by richard-cox** [comment]
The original issue is purely about the behaviour of cluster manager in pages that aren't visible in 2.6, so there's nothing really to verify here. Would suggest @catherineluse moves to QA for them to close

**Comment by ronhorton** [comment]
**Nothing to verify in 2.6.4**
closing
