### ISSUE TITLE
Namspace Selector not set to "All Namespaces" in a freshly provisioned cluster

### ISSUE THREAD

**Issue by Auston-Ivison-Suse** [rancher/dashboard#4669]
**Setup**
- Rancher version: v2.6-head(4375161)
- Browser type & version: Chrome Version 95.0.4638.69
- RKE1 cluster, k8s: v1.21.6

**Describe the bug**
After navigating to anything under "Workloads" the namespace selector isn't set to "All Namespaces." Instead it defaults to "Only User Namespaces"

**To Reproduce**
1. Navigate to your freshly installed cluster from the cluster explorer
2. Click on Workload-->Deployments 
3. Witness the bug in the Namespace Selector and notice that no Deployments are on the dashboard.

**Result**
After navigating to anything under "Workloads" the namespace selector isn't set to "All Namespaces." Instead it defaults to "Only User Namespaces"
**Expected Result**
The expected Default for the Namespace Selector should be "All Namespaces." 

**Screenshots**

![usernamespacebug](https://user-images.githubusercontent.com/89411550/143990978-ee533a0c-dec5-46e4-8897-3be612428951.gif)

**Comment by richard-cox** [comment]
This is expected, the default of 'Only User Namespaces` was broken for a bit but has now been fixed

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Reproduction**
- rancher version: v2.6.2
- Browser type & version: Chrome Version 95.0.4638.69
- RKE1 cluster, k8s: v1.21.6

**Steps For Reproduction**
1. Navigate to your freshly installed cluster from the cluster explorer
2. Click on Workload-->Deployments 
3. Witness the bug in the Namespace Selector and notice that no Deployments are on the dashboard.

**Setup For Validation**
- rancher version: v2.6-head(0d14421)
- Browser type & version: Chrome Version 95.0.4638.69
- RKE1 cluster, k8s:  v1.22.4

**Steps For Validation**
1. Navigate to your freshly installed cluster from the cluster explorer
2. Click on Workload-->Deployments 
3. Witness the bug in the Namespace Selector and notice that no Deployments are on the dashboard.

**Results**

As @richard-cox mentioned this was intended and has been fixed. You are able to land on the workload page and notice the intended name space selected.
