### ISSUE TITLE
Editing built-in Global/Project/Namespace Role rules doesn't work

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#4671]
This arose from conversation here https://github.com/rancher/dashboard/issues/4051#issuecomment-982641076

Repro steps:
1. Edit config of a built-in role eg Project Member
2. Add a verb to a resource rule
3. Click save; the save appears to have worked
4. Re-load the role config and observe that it is unedited

In the Ember UI, the rules fields are disabled for built-in roles. I think we just need to port that functionality over to the dashboard.

I'm also seeing this error when I try to change the 'New User Default' radio:
![Screen Shot 2021-11-30 at 8.06.07 AM.png](https://zube.io/files/rancher/4611431f8394752faa1fa38185cfe1ab-screen-shot-2021-11-30-at-8-06-07-am.png)

**Comment by catherineluse** [comment]
> In the Ember UI, the rules fields are disabled for built-in roles. I think we just need to port that functionality over to the dashboard.

This is correct. I'm closing this issue because Jordon fixed it as described https://github.com/rancher/dashboard/pull/6429
