### ISSUE TITLE
Update to What's New? for v2.6.3

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/dashboard#4678]
Creating this tracking ticket for @cloudnautique to fill in regarding the "What's New?" section for the upcoming milestone in v2.6.3.
As per our discussions this will be the headline worthy items that we want to update for What's New? to give a good idea beyond reading release notes of what is coming in the milestone.

**Comment by cloudnautique** [comment]
**Kubernetes 1.22 support**: Support has been added across Rancher distributions and for imported clusters. 
**Expanded support for Authorized Cluster Endpoint (ACE)**: Cluster admins can now configure ACE on imported RKE2/K3s clusters. 
**Workload UX enhancements**: Added dashboards for workload metrics into the Rancher UI. Added ability to pause orchestration, update the scale, and visualize the deployment health from within the main list views.

**Comment by wjimenez5271** [comment]
Harvester Integration: Harvester's integration with Rancher and RKE1 provisioning is now GA. Users can provision Kubernetes clusters with RKE1 and manage multiple Harvester HCI clusters from a single Rancher instance. RKE2 provisioning on Harvester is still Tech Preview.

**Comment by gaktive** [comment]
Need to consider what else to put here since the last update was 2.5.0.

**Comment by deniseschannon** [comment]
Note: 1.22 is going to be experimental in 2.6.3: https://github.com/rancher/rancher/issues/35839

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/pull/4755 has the changes.

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/pull/4785 contains a requested revision from @deniseschannon
