### ISSUE TITLE
Fleet: bundles detail page slow

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4682]
There are reports that the Bundles Detail page is extremely slow and occasionally locks up. It seems to be tied to loading the bundle YAML.

One suggestion to improve that page performance: hide the YAML behind a View YAML button but the problem may be happening with some other component or modal.

Internal reference: SURE-3568

**Comment by nwmac** [comment]
4793 should address this - need to validate with a large resource

**Comment by Shavindra** [comment]
I've tried this with different [example resources](https://github.com/rancher/fleet-examples) and I didn't really notice things being slow.

**Comment by nwmac** [comment]
Did you try a bundle with a few configmaps with (say) 500kb of data?

**Comment by izaac** [comment]
@nwmac could we add such bundle example like large bundle into the fleet-examples repository, that would be helpful.

**Comment by Shavindra** [comment]
@izaac I've requested that repo be updated with more examples. I will update once I get more info.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.6.4-rc10

* Create a fleet bundle with a configmap with base64 data and a size of 768kb
  * https://github.com/bmdepesa/fleet-examples/blob/helmlargebundle/single-cluster/helm/templates/configmap.yml
  * Repo:  https://github.com/bmdepesa/fleet-examples
  * branch: helmlargebundle
  * path: single-cluster/helm
* Add the git repo and deploy the bundle to a cluster
* Deploy the default single-cluster/helm bundle example to a different cluster

On average over 30 page loads
* The cluster without the configmap has the bundles request (17kb) load in ~275ms
* The cluster without the configmap has the gitrepos request (1.6kb) load in ~145ms
* The cluster with the large configmap has the bundles request (1.1mb) load in ~1.5s
* The cluster with the large configmap has the gitrepos request (1.6kb) load in ~135ms

Performance seems acceptable. Please re-open if other issues are found.
