### ISSUE TITLE
Fleet: resources age & last modified

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4683]
There's a request to provide a Resource Age along with a Last Modified Timestamp

Internal reference: SURE-4651

**Comment by nwmac** [comment]
@gaktive Where?

**Comment by nwmac** [comment]
I think we need the backend to add this - otherwise we'll have to fetch all of the resources which is expensive.

**Comment by nwmac** [comment]
This is on the resources tab that is used in a few places.

**Comment by gaktive** [comment]
@nwmac is there an existing backend ticket to work on this? or shall we transfer this over there?

**Comment by nwmac** [comment]
@gaktive Created https://github.com/rancher/rancher/issues/36173 for the backend work for this

**Comment by vincent99** [comment]
"Last modified" is not a concept k8s keeps track of for resources in general; they can't provide something that doesn't exist.

"Age" is (metadata.created), though it's just regular mutable user data so isn't necessarily when it was _actually_ created.

**Comment by MKlimuszka** [comment]
The backend ticket was missing an area3 label, so I didn't see this until now. I highly doubt it will get into 2.6.4.

**Comment by gaktive** [comment]
Related backend moved to 2.6.8, though @Jono-SUSE-Rancher & I are uncertain about that milestone yet, so moving to 2.6.x.

**Comment by catherineluse** [comment]
@gaktive @aalves08 Should this issue be closed as stale?

**Comment by gaktive** [comment]
@catherineluse the related backend is still open but without milestone. I'll check with Team 3 what their plans are.

**Comment by nwmac** [comment]
Depends on backend changes - https://github.com/rancher/fleet/issues/1184

**Comment by kkaempf** [comment]
> Depends on backend changes - [rancher/fleet#1184](https://github.com/rancher/fleet/issues/1184)

Backend is done, pending QA approval

**Comment by gaktive** [comment]
As I understand the state of things, this will require a Fleet version bump on `rancher/rancher`. https://github.com/rancher/rancher/issues/36173#issuecomment-1629247008 has the appropriate details.
