### ISSUE TITLE
Group list not sorted alphabetically when attempting to add role grant for SAML group

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4685]
Issue description:
Per the known caveat with SAML auth providers, a user must select a group from the dropdown list of their own groups, when attempting to grant a role to a group via Rancher RBAC. In Rancher v2.5.9 this list was sorted alphabetically, in v2.6.0 it is not.

Business impact:
Some users have a very large number of groups 100+, and this makes it very difficult to find and select the right group when granting a group a role.

Troubleshooting steps:
N/A

Repro steps:
- Provision a Rancher v2.5.9 instance (I used github.com/superseb/tf-do-rancher2)
- Configure the keycloak authentication with the QA keycloak instance (https://github.com/rancherlabs/the-ranch/wiki/Authentication-Test-Setup-configuration#saml-with-keycloak)
- Reset password of alex.seymour@suse.com user in keycloak and log in to Rancher as the user (user is a member of 100 aseymourgroupX groups)
- Attempt to add a group grant at global/cluster/project level and observe the group list in the dropdown is sorted.
- Upgrade to Rancher v2.6.0 and attempt to add a group grant at global/cluster/project level and observe the group list in the dropdown is not sorted.

Workaround:
Is workaround available and implemented? No

Actual behavior:
Group list is not sorted

Expected behavior:
Group list is sorted

Reference: 3460

**Comment by richard-cox** [comment]
The associated PR fixes the initial sort of principals but not sort those returned from search, those should be sorted given the proximity to the search term

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                         |
| ------------------------- | -------------------------------------- |
| Rancher version           | 2.6.3                                  |
| Installation option       | Helm high availability                 |
| If Helm Chart k8s cluster | RKE1  v1.22.6                          |
| Cert Details              | Self signed                            |
| Docker version            | 20.10.7, build f0df350                 |
| Helm version              | v2.16.8-rancher1                       |
| Downstream cluster type   | not applicable                         |
| Downstream K8s version    | not applicable                         |
| Logged in user role       | Global Admin                           |
| Browser type              | Google Chrome                          |
| Browser version           | 99.0.4844.51 (Official Build) (x86_64) |

## Reproduction steps

1. Unable Keycloak SAML Authentication
2. Navigate to -> `hamburger menu` -> `Groups` -> `Add Global Roles`
3. Click `Select Member`
4. View dropdown list order
  
## Additional Info


![001-a1](https://user-images.githubusercontent.com/40877149/158787002-35ae325f-a258-43f3-b87f-1f61cfc24e9b.png)

## RESULTS

#### :white_check_mark: Expected
Expected the drop down list to be sorted alphabetically

#### :x: Actual
The drop down list was not sorted alphabetically

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                                                                                     |
| ------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-d604b7e02ec8dfcb6c439ca8ed5500e1d1735717-head / [d604b7e](https://github.com/rancher/rancher/commit/d604b7e02ec8dfcb6c439ca8ed5500e1d1735717) |
| Installation option       | Helm high availability                                                                                                                             |
| If Helm Chart k8s cluster | RKE1  v1.22.6                                                                                                                                      |
| Cert Details              | Self signed                                                                                                                                        |
| Docker version            | 20.10.7, build f0df350                                                                                                                             |
| Helm version              | v2.16.8-rancher1                                                                                                                                   |
| Downstream cluster type   | not applicable                                                                                                                                     |
| Downstream K8s version    | not applicable                                                                                                                                     |
| Logged in user role       | Global Admin                                                                                                                                       |
| Browser type              | Google Chrome                                                                                                                                      |
| Browser version           | 99.0.4844.51 (Official Build) (x86_64)                                                                                                             |

## Validation steps

1. Unable Keycloak SAML Authentication
2. Navigate to -> `hamburger menu` -> `Groups` -> `Add Global Roles`
3. Click `Select Member`
4. View dropdown list order
  
## Additional Info


<img width="1593" alt="002-a2" src="https://user-images.githubusercontent.com/40877149/158786955-eb938e44-fcf0-40ac-868b-9b0255d7b26e.png">

## RESULTS

#### :white_check_mark: Expected
Expected the drop down list to be sorted alphabetically

#### :white_check_mark:Actual
The drop down list was now sorted alphabetically
