### ISSUE TITLE
Continuous Delivery: Incorrect matching information for a cluster group

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4688]
**Setup**
- Rancher version: 2.6.3-rc3
- Browser type & version: Firefox 78.13.0esr

**Describe the bug**
Matching information not correct when creating a selector rule in Cluster Group inside Continuous Delivery.

**To Reproduce**
Rancher GUI -> Main Menu -> Continuous Delivery -> Cluster Group -> Create

**Result**

Info: "Matches all X existing clusters.

The same message is displayed if the Rule Selector is configured to "Is set".

**Expected Result**
Info: "Matches no existing clusters.

**Screenshots**
![image](https://user-images.githubusercontent.com/86831399/144397606-135b1e3e-bff7-4f73-9d3a-5c45efc039fe.png)

![image](https://user-images.githubusercontent.com/86831399/144398157-dc33ceca-f655-40a8-81a3-ed59767d2b55.png)

**Additional context**

**Detailed Description**

**Context**

**Comment by vincent99** [comment]
An empty list has no entries to match, so it is the same as having not added that rule at all (and will be saved as such, without it).  So there are effectively no selectors.  When there are no selectors, all clusters are selected.

I presume your clusters both have a `distro` label and therefore 'distro is set' matching them is correct; putting in a label that doesn't exist shows me 'Matches no existing clusters' as expected.

**Comment by peteingithub** [comment]
Seems I thought this selector scenario as "exclusive" instead of "inclusive". :)
Since "no selector" means "all clusters", everything is working as intended.
The issue can be closed.

Thanks Vincent!

**Comment by vincent99** [comment]
They are, buy selecting nothing by default is not very useful and you need a way to say everything, so no selector == all.
