### ISSUE TITLE
[Harvester] User is unable to use template to create cluster through virtualization management

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4689]
**Setup**
- Rancher version: v2.6.3-rc3
- Browser type & version: chrome
- harvester version: v1.0.0-rc1

**Describe the bug**

User is unable to use template to create cluster through virtualization management

**To Reproduce**

* on a rancher deployment, import a harvester cluster through virtualization management
* go to `virtual machines` -> create
* check the `use template` option and select a template

**Result**
* TypeError: Cannot read properties of undefined (reading 'memory')

**Expected Result**

users should be able to use harvester templates

**Screenshots**

<img width="1558" alt="Screen Shot 2021-12-02 at 8 01 33 AM" src="https://user-images.githubusercontent.com/16691014/144457835-92d30743-3652-4d07-a654-918bc894f8ca.png">

**Additional context**
<!--Add any other context about the problem here.—>
this feature works if this is done through harvester instead of rancher -> virtualization management

**Comment by yasker** [comment]
Harvester team will take the first pass of this issue. cc @guangbochen @WuJun2016

**Comment by richard-cox** [comment]
Associated Harvester issue https://github.com/harvester/harvester/issues/1620 will be fixed by https://github.com/rancher/dashboard/pull/4697

**Comment by TachunLin** [comment]
Verified `fixed` on harvester `master-5d6f3db0-head` with rancher `v2.6-head`. Close this issue. 

### Result 
Access harvester from Rancher, on virtual machine page can load default three template to create VM. 

**iso image base template**

![image](https://user-images.githubusercontent.com/29251855/145583546-59cea4ea-4072-437e-9cf7-2449776abb56.png)

**raw image base template**
![image](https://user-images.githubusercontent.com/29251855/145583593-5aa7c897-f3dc-4fa1-9b94-750794a3e88e.png)

**windows iso image base tempalte**
![image](https://user-images.githubusercontent.com/29251855/145583672-72255932-72ee-4a88-b38a-8830789040c8.png)

**Create vm with iso template**
![image](https://user-images.githubusercontent.com/29251855/145586368-5a5b640b-3955-403b-8149-ff8657e2aa26.png)

### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: master-5d6f3db0-head (12/10 based on v1.0.0-rc1)
* Rancher version: v2.6.-head

### Verify Steps

1. Import harvester from rancher through harvester settings
2. Access harvester from rancher virtualization management page
3. Open Virtual Machine page 
4. Click create 
5. Check `Use VM Template`
6. Select one of the template
7. Create VM according to the template
