### ISSUE TITLE
Dashboard goes to error page instead of login when it's lost auth

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#469]
Steps:
1.  Leave Rancher running on the dashboard until it times out
2. Refresh page

Results:  Goes to the Error page instead of taking you back to Login page.

**Comment by izaac** [comment]
Rancher version `master-head (07/14/2020)` _691feb01a_ k8s HA install
dashboard-index -> `latest`

Tested with an expired `Dashboard UI` cookie. As described in this issue.
Checked also removing the `Dashboard UI` cookie from Rancher.

Refreshing the browser takes the session back to login `/dashboard/auth/login`
