### ISSUE TITLE
Added cluster owner is not able to change cloud credential of an rke2 DO cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4693]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `46eb9d4`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.6+rke2r1`
- Cluster Type (Local/Downstream): Local cluster - RKE2 DO

**Describe the bug**
Added cluster owner is not able to change cloud credential of an rke2 DO cluster

**To Reproduce**

- Deployed an RKE2 DO cluster
- Add a user as cluster owner
- Login as cluster owner
- Edit Config on the cluster
- User is _not_ able to add a new cloud credential

**Note:**
- But if this is an ec2 rke2 cluster, added cluster owner user is able to create a new one or change it to another one. And changing the cloud cred to a new one works, user is able to scale up nodes after.
- On 2.6.2, both the clusters - DO and AWS did not have create a new Cloud cred option.

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Reproduction**
- Rancher version: v2.6.2
- Installation option: Docker

**Cluster information**
- k8s: v1.21.6
- Cluster type: RKE2/ec2

**Steps For Reproduction**
1. Provision and RKE2 cluster
2. Create a standard user
3. Give the standard user access to the cluster with the "cluster owner role" 
4. Login as standard user and go to edit config. 
5. Notice that you are not able to create a new credential


**Setup For Validation**
- Rancher version: v2.6-head(f93f439)
- Installation option: Docker

**Cluster information**
- k8s: v1.22.4
- Cluster type: RKE2/ec2

**Steps For Validation**
1. Provision and RKE2 cluster
2. Create a standard user
3. Give the standard user access to the cluster with the "cluster owner role" 
4. Login as standard user and go to edit config. 
5. Create a new credential and let the cluster update. 


**Results**
The cluster is able to get a new credential added to the cluster and updates successfully. 


**Screenshots**

Repro:

![UICreditBug.png](https://zube.io/files/rancher/0b551225dd6c0e369258fb70592de9d7-uicreditbug.png)

Validation:

![UICredit.png](https://zube.io/files/rancher/e14c4051ac8e3a8f349d6ea781a04060-uicredit.png)
