### ISSUE TITLE
Dynamic rancher charts for Apps & Marketplace

### ISSUE THREAD

**Issue by xhejtman** [rancher/dashboard#4694]
**Detailed Description**
Would it be possible to add some dynamic question options rancher charts? E.g. embed javascript to make queries? It would be also nice, if some other context info could be passed to the values - cluster name and requesting user (but in secure way so that user cannot alter this identity).

**Context**
It would be cool, if questions for rancher could do dynamic queries, e.g, for actual PVC to let a user select of existing PVCs or other objects. Charts could be also templated based on the cluster. E.g., each cluster usually has different public endpoint, if you pass endpoint to the chard, you either need to instruct the user which endpoint select or make separate chart repo for each cluster. This could definitely be templated.

**Comment by vincent99** [comment]
No, that would be basically arbitrary-code-execution-as-a-service.

PVC has always been a supported question type (`type: pvc`).  In the newer UI (which you seem to be using) you can also do `reference[group.type]` to get a dropdown of resources of that type and fill in the selected name as a value.  `group.type` can be any type name, as shown in the URL when you're looking at a list of them, e.g. `networking.k8s.io.ingress`).

**Comment by xhejtman** [comment]
cool, is this documented somewhere?

and as of cluster or user reference, not possible?

**Comment by vincent99** [comment]
https://rancher.com/docs/rancher/v2.6/en/helm-charts/creating-apps/#question-variable-reference

(The newer `reference[type]` hasn't made it into there)

There is is no standard source of an 'endpoint' for a cluster for us to provide, or I don't know what you mean.  Normally charts do one or more of:
  - Ask for a hostname to use in an ingress (which they choose, and then has to be configured in dns separately)
  - Create a NodePort service
  - Create a LoadBalancer service

**Comment by xhejtman** [comment]
I meant if I can template the chart according to a cluster name. It would be possible, if I can get cluster name into some built-in variable. Is there such a variable?

**Comment by xhejtman** [comment]
.Values.global.cattle.clusterName contains cluster name where the app is being deployed. Perfect.
