### ISSUE TITLE
Dashboard reload causes breaks namespace filtering

### ISSUE THREAD

**Issue by xhejtman** [rancher/dashboard#4699]
**Setup**
- Rancher version: 2.6.2
- Browser type & version: chrome 97.0.4692.36

**Describe the bug**
If a namespace is selected in the top drop down menu and whole page is reloaded (ctrl-r), namespace is visualy still selected, but dashboard displays all namespaces, see attached screenshot.

**To Reproduce**
Select any namespace, reload the webpage in browser (ctrl-r or reload icon)

**Result**
Namespace is still indicated as being selected, but dashboard displays whole cluster.

**Expected Result**
Namespace is either still selected (preferred) or clear indication of selected namespace.

**Screenshots**

after webpage reload:
![ns1](https://user-images.githubusercontent.com/22795052/144588102-63e0f835-996f-48c2-8e23-9b1c8de1c42f.png)

**Comment by richard-cox** [comment]
This has been covered by https://github.com/rancher/dashboard/issues/4647 and https://github.com/rancher/dashboard/issues/4659. A fix has been implemented and will be included in 2.6.3
