### ISSUE TITLE
Private registry mirrors in YAML don't render in RKE2/K3s cluster config form

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#4701]
**Setup**
- Rancher version: v2.6-head
- Browser type & version: Firefox 94.0.2 or Chrome 96.0.4664.55

**Describe the bug**
You can provision an RKE2 cluster to have a private registry that has a mirror. If you then go to the edit config form for the cluster after it is provisioned, the mirror section of the form doesn't show up.

I put this issue in the v2.6.3 milestone because it is loosely related to this issue https://github.com/rancher/dashboard/issues/4137 because this fix is needed to fully test the fix for that other issue. Thanks @rak-phillip for helping with this.

**To Reproduce**

1. Provision an RKE2 cluster with this a private registry called registry1.com with a mirror endpoint of registry2.com. The YAML under `rkeConfig` should look like:

```
registries:
      mirrors:
        registry1.com:
          endpoint:
          - registry2.com
```
2. Go to the provisioning cluster and click Edit Config and go to the registries tab of the form

**Result**

**Expected Result**
The cluster edit form is supposed to have the same registry mirrors section as the cluster create form does:

<img width="876" alt="Screen Shot 2021-12-03 at 2 14 32 PM" src="https://user-images.githubusercontent.com/20599230/144673703-f6d67a7d-3b85-4bd3-b8dc-c448a8ed3cc2.png">

**Actual Result**
The edit form does not render the mirrors:
<img width="743" alt="Screen Shot 2021-12-03 at 1 45 12 PM" src="https://user-images.githubusercontent.com/20599230/144673774-534fa070-7369-4e0b-bb36-9eca68eb251f.png">

This issue was encountered while trying to test the fix for https://github.com/rancher/dashboard/issues/4137. After you configure a registry with a mirror and secrets for authentication for both the registry and the mirror, you shouldn't only be able to test that it is correct in YAML. You should also see it is correctly showing up in the edit cluster config form.

**Comment by snasovich** [comment]
@jakefhyde , could you please dev-validate this one? Thank you.

**Comment by jakefhyde** [comment]
Validated on `v2.6-head`

Confirmed edit has the same registry mirrors section as the cluster create form:
![edit](https://user-images.githubusercontent.com/33796120/146246957-f50c659e-2733-43c9-aea3-2785812d0da2.png)

Confirmed the registry mirrors section matches the yaml:
![yaml](https://user-images.githubusercontent.com/33796120/146246981-6f73d442-3700-40cd-a747-f034c5acd367.png)
