### ISSUE TITLE
Namespace Resource Settings for Quota Override Missing in UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4704]
Issue description:
Namespace quota settings doesn't appear in new UI.

Business impact:
No impact.

Troubleshooting steps:

Create a new Rancher 2.6.2
- create a new project and config CPU/Memory Quotas
- create namespace into previously created project
- namespace quota settings doesn't show up

Repro steps:

Create a fresh Rancher 2.6.2
Create new project and config CPU/Memory Quotas
Create a namespace into previously created project

Workaround:
Is workaround available and implemented? yes

What is the workaround: Namespace quotas settings shows up in old UI. Its possible to config namespace quotas settings accessing the old UI <rancher-url>/g

Actual behavior:
Rancher 2.6.1 / 2.6.2 does not show up Namespace quotas settings in new UI

Expected behavior:
Be able to set Namespace quotas settings in new UI

Some backend connection: https://github.com/rancher/rancher/issues/35385

Internal reference: SURE-3584, SURE-3620, SURE-3604

**Comment by gaktive** [comment]
Maybe https://github.com/rancher/dashboard/issues/4412 helps here.

**Comment by catherineluse** [comment]
Sounds similar/related to #4597

**Comment by xhejtman** [comment]
as of 2.6.3, there is UI for namespace quota settings. however, real quota resource is not updated if namespace quota is changed from UI.

**Comment by richard-cox** [comment]
This was resolved in 2.6.3 (which brought in the bug #4804). Just needs some validation from QA and we're good

**Comment by richard-cox** [comment]
This should be verified at the same time the fix in #4823 is tested

**Comment by anupama2501** [comment]
Verified by installing 2.6.2 rancher and upgrading it to 2.6.3-patch1-rc1

- Created a project with resource quotas for config maps and CPU limits set,
- Quotas did not show up while creating a namespace.
- Upgraded the rancher server to v2.6.3-patch1-rc1
- Verified for the new namespaces, resource quotas show up as set on the project.
