### ISSUE TITLE
[UX] Scale Down button on `manage` cluster page looks like a dropdown arrow for rke1 clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4705]
**Setup**
- Rancher version:v2.6.3-rc3
- Browser type & version: chrome

**Describe the bug**

scale down button on cluster management page looks like a dropdown button

**To Reproduce**

* on a rancher setup, deploy an rke1 cluster with more than 1 node
* go to the `manage` page for that cluster
* check the box in the left column for one of the nodes

**Result**
* scale down button is enabled, but the arrow looks a lot like a dropdown arrow. 

**Expected Result**

a different icon should be used to avoid confusion ( I thought this might be a dropdown to scale up instead of scale down)

**Screenshots**

<img width="481" alt="Screen Shot 2021-12-03 at 4 15 47 PM" src="https://user-images.githubusercontent.com/16691014/144688763-50ef3ce7-974e-4300-ad8c-63dd47d50b80.png">

**Additional context**
* followup from rancher/dashboard#3366

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `b7d78a8` 12/8/2021
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Provisioned an RKE1 cluster with one machine pool having more than 1 node.
2. Observed that the icon changed from the down chevron to a minus just as the PR indicates:
![image](https://user-images.githubusercontent.com/45179589/145276575-fef19525-5b73-4909-8ff1-5e0c2f103202.png)
