### ISSUE TITLE
Can't upgrade an app launched in Ember 2.5.x

### ISSUE THREAD

**Issue by sgapanovich** [rancher/dashboard#4708]
Set up: 
rancher: 2.5.11

Steps to reproduce:
- launch the openebs app to "default" project
- navigate to the project where the app was installed
- go to Apps
- click on the three dots to edit app 
- select "Upgrade"
  - app is opened to be edited 
  - ![2511](https://user-images.githubusercontent.com/40282141/144729276-cea2cfc0-ae23-4268-b456-7633d25821c4.gif)
  - "Edit as YAML" file option can be located on that page
  - ![edit](https://user-images.githubusercontent.com/40282141/144729213-22146e0e-42d5-4845-b424-0dd4dd7e75f9.jpg)

when Rancher is upgraded to 2.6.3-rc4
- enable Legacy feature if not enabled
- On the Legacy -> Project (selected the project where the app installed in the drop down) 
- go to Apps
- click on the three dots to edit app 
- select "Upgrade"
  - app is not opened to be edited 
  - ![263rc4](https://user-images.githubusercontent.com/40282141/144729266-d77479e4-c340-4992-b7a8-3d30ab7a8077.gif)

when comparing API calls made in 2.5.11 and 2.6.3-rc4 you can see missing GET API calls with info for the app
![differences](https://user-images.githubusercontent.com/40282141/144729333-459a29db-2bb6-48fa-9d08-4e25e564d6e6.jpg)

_Originally posted by @sgapanovich in https://github.com/rancher/dashboard/issues/4120#issuecomment-986144895_

**Comment by gaktive** [comment]
Per Vince, what UI has to do in this case is determine if this current version is the same, we have to pass on another variable to the API. @jordojordo had touched something simliar in Vue.

**Comment by catherineluse** [comment]
I tested these steps in `v2.6-head` and found that the app is not shown under **Legacy > Project > Apps,** but it is available under **Apps & Marketplace > Installed Apps** and can be successfully upgraded from there.

Relevant backend changes: https://github.com/rancher/rancher/pull/35711

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: 2.5.11 -> 2.6-head 77392a6
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
1. In 2.5.11 Rancher: installed OpenEbs app in the Default project 
2. Upgraded Rancher to 2.6-head
3. **Apps & Marketplace > Installed Apps** 
4. The OpenEbs app will have a yellow label `3.0` on it which means there is a newer version available 
4. Selected "Edit/Upgrade" for OpenEbs (installed in 2.5.11) OR clicked on the yellow `3.0` label
  you get redirected on a new page with a message _"This is a Legacy App and it cannot be modified here / Navigate to Legacy Apps"_ is shown with a working link to **Legacy > Project**
5. Click on the link or navigate to **Legacy > Project** 
6. In the namespace/project dropdown select "Default" project
    You are taken to the Ember iframe
    The app will appear 
    When clicking "Upgrade" you will not see 3.0 version as one of the options to upgrade to
![upgrade](https://user-images.githubusercontent.com/40282141/145442926-ba396733-590d-4bbb-aecc-813c53efaf3e.jpg)

---------

per @jordojordo "there is a PR that removes the Upgradable button from apps created with the Ember UI https://github.com/rancher/dashboard/pull/4691
There was another PR that fixes the issue of not being able to edit/upgrade the old apps from the Ember iframe https://github.com/rancher/dashboard/pull/4738"
