### ISSUE TITLE
Not able to upgrade v2 charts as a standard user 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4720]
Setup

Rancher version: 2.6.3-rc4
Browser type & version: Chrome

**Describe the bug**
As a standard user, if I try to upgrade a v2 chart, after clicking on the upgrade button the page won't load. I do not see any API requests sent in the network tab

**To Reproduce**
1. Create a rancher HA server on 2.6.3-rc4 and create a standard user u1
2. create a downstream cluster with 3 worker, 1 etcd, 1 cp as a standard user
3. Install a v2 chart in this cluster eg; istio `100.1.0+up1.11.4`
4. After installation goes through, upgrade the app as the same standard user u1

**Result**
The screen won't load and the upgrade doesn't go through. 

**Expected Result**
Expected the installation to go through and the app upgraded to the new version.

**Screenshots**
<img width="462" alt="Screen Shot 2021-12-07 at 8 13 55 AM" src="https://user-images.githubusercontent.com/38144301/145065578-87bb7ae1-70d2-4ee5-9cb8-2a2a128bdba4.png">

**Additional context**
This behavior is seen on a fresh installed rancher HA server as well as an upgraded server from v2.6.2 --> v2.6.3-rc3
If we try to upgrade the installation as an admin, we see the app upgraded and no errors seen.

**Comment by gaktive** [comment]
Sounds like something that @catherineluse is already working on with a recent change in upgrades.

**Comment by catherineluse** [comment]
@anupama2501 Was the standard user added to the downstream cluster as a member or a cluster admin?

**Comment by catherineluse** [comment]
I'm still working on this one, but I found out some more info:

- The problem involves the model `catalog.cattle.io.app.js`, specifically its method `deployedAsMultiCluster`, which is meant to say if an app is a multi cluster app or not. In this case, when a standard user is trying to upgrade a regular app (not multi cluster), the result of that method is supposed be null.
- For standard users (not admins), the method doesn't return anything. It just hangs permanently, causing the upgrade page to never load: `await this.$dispatch('management/findAll', { type: MANAGEMENT.MULTI_CLUSTER_APP }, { root: true });`
- With error handling on the hanging API call, the error is `TypeError: url is undefined`

**Comment by catherineluse** [comment]
After talking to Vince and Jordon, it sounds like there is currently a limitation that the data for an individual app doesn't have an annotation that indicates if it is a multi-cluster app or not. The current best solution is to try to fetch multi-cluster apps from the back end, and if the current app is not named in the results, assume that it is not a multi-cluster app. However, Vince said that in the long term, this may not always be an accurate assumption. In the future, if we keep having unexpected results as we figure out how to display apps, we may need to request the backend to add an annotation to the app data to indicate what type of app it is, i.e., whether it is a multi-cluster app or not.

**Comment by anupama2501** [comment]
Verified as a standard user, able to upgrade or install apps on v2.6-head 39cecf0

Installed istio 1.10.4 on v2.6-head as standard user, upgraded to version `100.1.0+up1.11.4`.
Verified the upgrade goes through without any error.

**Comment by anupama2501** [comment]
Verified upgrade scenario as well. Installed istio as a standard user in 2.6.2. Upgraded the rancher version to 2.6.3-rc7, verified upgrading istio as a standard user goes through fine.
