### ISSUE TITLE
Cannot login through dashboard if user logs out through ember UI and tries to login again

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4724]
**Setup**
- Rancher version: v2.6.3-rc4
- Browser type & version:chrome

**Describe the bug**

if user logs out via ember UI, user isn't able to log back in (through dashboard, which rancher redirects to automatically)

**To Reproduce**

* from dashboard, login as any user
* go to ember UI (i.e. <IP>/g/clusters
* logout from ember UI
  * user is redirected to dashboard login page
* user is unable to login
  * when entering valid creds + trying to login, user is redirected to login timeout page, and instructed to login again this happens not only with the original user but any user from the same browser, even after hard refresh + clear cache
  * new browsers from the same machine are able to login

**Result**
* user is not able to log back in using the same browser

**Expected Result**
user should be able to login through dashboard

**Additional context**
* workaround: navigate back to ember UI
* rancher will redirect to ember UI login page for a second, then redirect back to dashboard UI login page. from here, user can login normally

I'm aware this will likely be a `no-fix` as this involves ember in the use case.

**Comment by vincent99** [comment]
This is probably the same as https://github.com/rancher/dashboard/issues/4665 , remembering that the logout screen is the page to go 'back to'.

**Comment by davidnuzik** [comment]
v2.6-head 0d14421ed

Confirmed this is working. I tested this via https://github.com/rancher/dashboard/issues/4716#issuecomment-989151318 and I just now checked by logging out of ember UI as well then try to log in to dashboard and this works without any issues. When I log out of the ember UI I get routed to the dashboard login, login, and successfully get logged in to the dashboard UI.
