### ISSUE TITLE
Configure Shell/Terminal location

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#4733]
**Detailed Description**
Add the ability to pin the Kubectl Shell / Console output to different sides of the screen. 

**Context**
Currently, the Kubectl Shell only renders at the bottom of the screen. While the height of the shell can be changed, a lot of monitors are wider than they are tall and it would be nice to have the ability to pin terminal output to the left or right-hand side of the window to make better use of the screen real estate available.

**Comment by rak-phillip** [comment]
@lvuch here's the issue for relocating the shell

**Comment by nwmac** [comment]
Should allow it to be docked to the right as well as the bottom

**Comment by richard-cox** [comment]
We should be careful of how this affects the responsiveness of pages, particularly those with tables in. A wide window could reduce the width enough to make content look pretty bad.

**Comment by nickwsuse** [comment]
Actually, I wasn't aware that opening a pods logs also opens the shell window and in that circumstance the shell window is not properly responsive if the shell is pinned on the side of the screen. 

If you max out the size of the shell window you can see all the buttons and options that you'd see if it were pinned to the bottom, but if it's under max window size then buttons or filter fields are cut off.

**Max Width Shell:**
![image](https://user-images.githubusercontent.com/107147272/206045117-667829b0-8c34-40d4-942a-f61bce881e1d.png)

**Medium Width Shell:** 
![image](https://user-images.githubusercontent.com/107147272/206045243-12b2034a-ac9d-4942-a80e-dafdfc655781.png)

**Default Width Shell:**
![image](https://user-images.githubusercontent.com/107147272/206045291-98be54fb-e756-4513-a72f-56eb629e5328.png)

**Comment by torchiaf** [comment]
> Actually, I wasn't aware that opening a pods logs also opens the shell window and in that circumstance the shell window is not properly responsive if the shell is pinned on the side of the screen.
> 
> If you max out the size of the shell window you can see all the buttons and options that you'd see if it were pinned to the bottom, but if it's under max window size then buttons or filter fields are cut off.

Hi @nickwsuse , thanks for the review, just pushed a fix to adjust the layout of the elements at the bottom.

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: 5df9701`

There are now two separate scrollable areas in the shell, one for the logs and one for the elements at the bottom of the terminal.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/107147272/208511192-42cff4bb-9849-4115-b507-0492cadee3d9.png">
