### ISSUE TITLE
[Cluster Manager] cannot go to any page under Tools under a cluster 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#4734]
**Rancher Server Setup**
- Rancher version: 2.6.3-rc4 
- Installation option (Docker install/Helm Chart): docker install 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): DO 

**Describe the bug**

- Go to any downstream cluster
- Click on any options under the Tools at the top bar.  

![image](https://user-images.githubusercontent.com/6218999/144939569-93f01042-5653-4e69-b0ec-53f5f0be074a.png)
 
Results:
- the following error shows in the console
- the UI stays on the cluster page, does not go to the target subpage. 

![image](https://user-images.githubusercontent.com/6218999/144939496-806fa321-7760-42de-862f-f1bf268299d3.png)

**Comment by richard-cox** [comment]
From the description and screenshot this isn't the cluster explorer/new ui/dashboard, it's the unsupported Cluster Manager/old ui/Ember UI. This shouldn't be a release-blocker. 

We do embed some of these pages though, so we should confirm they work in that mode.

**Comment by nwmac** [comment]
@vincent99 I had a quick look at this - PR is here for a fix for the immediate issue: https://github.com/rancher/ui/pull/4786/files

The problem is that `componentStatuses` on the cluster is undefined - I don't know if this is an issue that needs to be addressed elsewhere?

**Comment by deniseschannon** [comment]
Note: This is most likely caused by k8s 1.22 dropping componentstatus all together.

**Comment by vincent99** [comment]
Yeah; as discussed in standup that section should just be hidden if there's no componentStatuses

**Comment by nwmac** [comment]
PR: https://github.com/rancher/ui/pull/4788 hides the component statuses when not available

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `2a7857d7a`**

On a 1.21 and 1.22 downstream cluster pages under Tools are accessible in Ember UI.
