### ISSUE TITLE
Make keyboard shortcuts discoverable

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#4735]
**Detailed Description**
As a rancher dashboard user, I want to be able to look up all existing keyboard shortcuts, so that I can learn and use those shortcuts.

**Context**
It's difficult for anyone to learn about keyboard shortcuts in rancher dashboard without experimenting to figure them out or learning them from someone else. A simple reference of keyboard shortcuts would go a long way to help users out.

**Comment by richard-cox** [comment]
This is partially covered in https://github.com/rancher/dashboard/issues/2982

**Comment by rak-phillip** [comment]
Cool, thanks! I'll close this one in favor of the other. I was searching existing issues and somehow glossed over that.
