### ISSUE TITLE
Rancher Custom Explorer dashboard from /k8s/clusters/a-1abcd/v1/schemas

### ISSUE THREAD

**Issue by ederwentz** [rancher/dashboard#4743]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment]
Closing, please update using the template provided and reopen.
