### ISSUE TITLE
Deployments page shows green status for deployment with pods in `crashloopbackoff`

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4745]
**Setup**
- Rancher version: v2.6.3-rc4
- Browser type & version: chrome

**Describe the bug**

Deployments page shows green health for deployment with pods in `crashloopbackoff` and deployment state is `updating`

**To Reproduce**

* create a deployment with an image known to fail with state `crashloopbackoff`
* wait for pod for this deployment to reach `crashloopbackoff` state
* visit the `workloads` or `deployments` page from dashboard

**Result**
The deployment shows as green in the `health` column

**Expected Result**

* color of `health` should match the worst pod state from the deployment, in this case it is blue

**Screenshots**
<img width="608" alt="Screen Shot 2021-12-09 at 2 42 41 PM" src="https://user-images.githubusercontent.com/16691014/145488046-896fd03a-ad80-4bae-85a3-e9cd43537143.png">
<img width="1524" alt="Screen Shot 2021-12-09 at 2 41 34 PM" src="https://user-images.githubusercontent.com/16691014/145488050-eb04acd2-59f7-43ad-9ca4-8921ca756037.png">

**Comment by vincent99** [comment]
It's like a bar graph, so the color is not the 'worst one' but a segment for each kind, proportional to how many there are..  Which in this case is... just blue... so yes this is wrong as shown.

But if there were 5 green, 2 yellow, 3 blue and a red it would/should look something like `[R|YY|BBB|GGGGG]`

**Comment by richard-cox** [comment]
As per Vince's comment, these should show a status of each pod in the workload (or job for job related workloads).

The segments shown for a workload in the workloads list 'Health' column match those in the workload detail page at the top `Pods by State` section. For non-job workloads this is the pod's `status.phase`. However the individual 'state' of the pods shown in pod lists below comes from the pod's `metadata.state`.

![image](https://user-images.githubusercontent.com/18697775/145566339-aa5e5456-10df-422c-9cc3-323ee2034cec.png)

@vincent99 @nwmac Should the workloads list show the specific pod state as per pod lists, and should the workloads details page show the same (at the top)?

**Comment by vincent99** [comment]
I think the workload bar graph should aggregate the pod `state`s so it's showing the same words and colors as you'd see if you clicked into the quelled to see the pods.  The page is not very useful if we think it's green when the pod isn't even running.

**Comment by phillipsj** [comment]
From what I can tell was the decision above, it looks good to me.
![Screenshot from 2021-12-15 21-57-04](https://user-images.githubusercontent.com/1568133/146299997-fceb3103-f9e0-4854-95f2-074b62557217.png)

**Comment by sowmyav27** [comment]
latest 2.6-head `39cecf0`
![Screen Shot 2021-12-15 at 10.08.58 PM.png](https://zube.io/files/rancher/c0d88aac8c616390d7ed86ca49dd516d-screen-shot-2021-12-15-at-10-08-58-pm.png)
