### ISSUE TITLE
UI no longer showing network-attachment-definitions correctly

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4748]
Internal ref: SURE-3792

In 2.5, the Cluster Explorer showed NetworkAttachmentDefinitions under the k8s.cni.cncf.io API group(screenshot attached).
![image-2021-12-09-10-03-23-103.png](https://zube.io/files/rancher/b5e72a895d586d7f93f049c74a21163b-image-2021-12-09-10-03-23-103.png)

In 2.6, the k8s.cni.cncf.io API Group is Visible and it shows the correct count of objects under the "Networks" name, but the objects are not shown (reported in 2.6.2):
![image-2021-12-09-10-03-41-505.png](https://zube.io/files/rancher/9e30a4a0c9fab1ad8ab8aabbeafd56c7-image-2021-12-09-10-03-41-505.png)

*Repro steps:*
 * Apply Multus quickstart - [https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/quickstart.md]
 * Apply dummy NetworkAttachmentDefinition -
```
cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      }
    }'
EOF
```
*Workaround:*
 Is workararound available and implemented? yes
 What is the workaround: Edit resources directly with kubectl

*Actual behavior:*

UI shows the API group and correct count of NetworkAttachmentDefinition objects(under the name "Networks", but doesn't show the objects themselves.

*Expected behavior:*

UI shows the API group and objects correctly.

*Other:*
Logs show messages like:
```
All of schema is not loaded yet
No schema found to validate userpreference Object: Getter & Setter
All of management.cattle.io.project is not loaded yet
```

**Comment by codyrancher** [comment]
QA should verify that the list page still functions properly with harvester.

**Comment by Josh-Diamond** [comment]
@codyrancher Could you please provide a template? Greatly appreciated

**Comment by Josh-Diamond** [comment]
Ticket #4748

With Docker on single-node:

Reproduced on rancher `v2.6.3`:
1. Fresh install of rancher `v2.6.3`
2. Download local.yaml and export to KUBECONFIG
3. Run scripts to clone and configure `multus`
4. Create `networkattachmentdefinition`’s 
5. In Rancher, go to `Explore Cluster` for `local` and under the tab `More Resources`, find and select `k8s.cni.cncf.io`, to view `Networks`
6. Reproduced - `Networks` tab shows entries, however none are listed in UI

Screenshot:
<img width="1451" alt="Screen Shot 2022-03-17 at 4 21 30 PM" src="https://user-images.githubusercontent.com/46494969/158914246-5e76146d-6048-4ce4-8b01-e3a6b1a0256e.png">

Verified on rancher `v2.6-93757afc3d752491dbfc209153dfa04bdf07647f-head`:
1. Fresh install of rancher `v2.6-head`
2. Download local.yaml and export to KUBECONFIG
3. Run scripts to clone and configure `multus`
4. Create `networkattachmentdefinition`’s 
5. In Rancher, go to `Explore Cluster` for `local` and under the tab `More Resources`, find and select `k8s.cni.cncf.io`, to view `Networks`
6. Verified - `Networks` tab shows entries and all are listed in UI

Screenshot:
<img width="1451" alt="Screen Shot 2022-03-17 at 5 20 43 PM" src="https://user-images.githubusercontent.com/46494969/158914373-731890d8-e280-4138-b5fa-51434bbc9df8.png">

Upgrade/Verified on rancher `v2.6.3` >> `v2.6-93757afc3d752491dbfc209153dfa04bdf07647f-head`:
1. Fresh install of rancher `v2.6.3`
2. Download local.yaml and export to KUBECONFIG
3. Run scripts to clone and configure `multus`
4. Create `networkattachmentdefinition`’s 
5. Upgrade rancher to `v2.6-head`
6. In Rancher, go to `Explore Cluster` for `local` and under the tab `More Resources`, find and select `k8s.cni.cncf.io`, to view `Networks`
7. Verified - `Networks` tab shows entries and all are listed in UI

Screenshot:
<img width="1450" alt="Screen Shot 2022-03-17 at 4 33 57 PM" src="https://user-images.githubusercontent.com/46494969/158914272-95100a47-387f-4ffc-bc6b-358b29bc6901.png">

**Comment by slickwarren** [comment]
also tested on 2.6-head 85d6925 using harvester node driver clusters. Following fresh install checks from the [comment above](https://github.com/rancher/dashboard/issues/4748#issuecomment-1075313049),  I am able to see network-attachment-definitions in the UI
