### ISSUE TITLE
Ensure API returns k8s 1.21 as the default

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4752]
Whilst 1.22 is marked as experimental for 2.6.3, 1.21 will remain the default. So the versions listed will rely on 1.21 as the default picker and higher versions would be visible.

Relates to https://github.com/rancher/rancher/issues/35839

**Comment by kinarashah** [comment]
Backend fixes for RKE2 defaults are merged, 
- [x] Support in Rancher for channel server https://github.com/rancher/rancher/pull/35843  
- [x] Check changes for k3s/RKE2 https://github.com/rancher/kontainer-driver-metadata/pull/761

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `2a7857d`**

k3s/rke2 1.22 versions are not marked experimental and also 1.22 version still shows up as the default.

**Comment by sowmyav27** [comment]
EDIT:
On 2.6-head commit id: 2a7857d

I do see it marked experimental and 1.21.7 is the default
<img width="356" alt="Screen Shot 2021-12-14 at 1 19 11 PM" src="https://user-images.githubusercontent.com/26032343/146081048-7a946609-7018-441e-82dc-6204c84db2dc.png">
