### ISSUE TITLE
Add form field for ssl_verify and ssl_version when enabling an HTTPS flow

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4753]
*Request description:*
When enabling a flow with an HTTPS scheme and secret it would be helpful to have fields in the Form UI to add the following two lines without having to edit the YAML directly:
```
ssl_verify: false
ssl_version: TLSv1_2
```
This was previously configurable in 2.5.x.

*Actual behavior:*
Though they are required for HTTPS, which can be enabled via the form view, you have to edit the actual YAML to add these two lines before it will work.  There is no indication of this being the case.

*Expected behavior:*
Enabling HTTPS in the UI should add these lines or have fields for their values so the user doesn't run into unknown and unexpected problems.

![ssl-config.png](https://zube.io/files/rancher/f5e612bb60fae4b6d98d91d4acecf832-ssl-config.png)

Additional notes:
The UI seems to allow for the enablement of HTTPS, but actually just comes off as if it is broken until the user does their own research.  This is not a good user experience and ABSA has ranked this as an important feature for themselves

Internal reference: SURE-3404

**Comment by catherineluse** [comment]
Note on the context: In Ember, these fields are only applicable to the logging application, and only if the user is using Elasticsearch.

If SSL Verify is enabled, another input needs to be shown that accepts a certificate. The certificate has this requirement defined: `application/x-x509-ca-cert,text/plain,.pem,.crt,.cert`

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID cd3c9d7`

1. installed logging on downstream cluster
2. configured cluster-output for elastic
3. verified that 'verify ssl' is available as a checkbox (below Connection info on config)
4. verified that values are persisted in yaml if user selects to enable 
5. confirmed logs flow to elasticsearch
