### ISSUE TITLE
remove `tech preview` from rke1 harvester node driver (on cluster -> create page) as harvester will be GA for 2.6.3

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4754]
**Setup**
- Rancher version: v2.6.3-rc4
- Browser type & version:chrome

**Describe the bug**

**To Reproduce**

navigate to `cluster management` -> `create` page and toggle to `rke1` 

**Result**
harvester is still marked as tech preview 

**Expected Result**

harvester is GA, so we should remove this for rke1 (rke2 should remain, since rke2 won't be GA until 2.6.4)

**Screenshots**
<img width="918" alt="Screen Shot 2021-12-10 at 12 51 34 PM" src="https://user-images.githubusercontent.com/16691014/145643520-9e718db8-2b71-47aa-924a-504ea485ace8.png">

**Comment by guangbochen** [comment]
also should remove the `tech preview` in the Virtualization Management page.
![image](https://user-images.githubusercontent.com/4569037/145749534-d7825dd5-40eb-4635-af03-ac276c5d2047.png)

**Comment by slickwarren** [comment]
on rancher v2.6-head (fd930f7):
* harvester rke1 no longer shows as `tech preview` -- pass
<img width="396" alt="Screen Shot 2021-12-13 at 9 54 48 AM" src="https://user-images.githubusercontent.com/16691014/145864014-d619eae0-f078-4665-80f3-4121dc6eff2d.png">

* no `tech preview` found on `virtualization management` pages -- pass
<img width="577" alt="Screen Shot 2021-12-13 at 9 58 27 AM" src="https://user-images.githubusercontent.com/16691014/145864031-ba1a7401-8468-49f6-8704-fb4cf95ceff5.png">
