### ISSUE TITLE
Multiple same versions of helm3 library apps show up after migrating apps from ember to dashboard

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4756]
Setup

Rancher version: 2.6-head 1ae31b1
Browser type & version: Chrome

**Describe the bug**
After migrating the apps from ember UI to dashboard, I'm seeing multiple same versions of the apps

**To Reproduce**
1. Install helm3 library app from ember UI eg., aws-event-sources
2. Migrate the app from ember UI to dashboard by adding the annotations in the app as follows:
```
kubectl get apps -A | grep aws
kubectl edit apps aws-event-sources -n aws-event-sources

Add the annotation via kubectl to the downstream cluster in spec.chart.metadata.annotations
catalog.cattle.io/ui-source-repo: helm3-library
catalog.cattle.io/ui-source-repo-type: cluster
apps.cattle.io/migrated: "true"

From local cluster:
kubectl get apps.project.cattle.io -A | grep aws
kubectl edit  apps.project.cattle.io aws-event-sources -n p-mr57l
p-mr57l --> projectID as namespace 
Add the annotation `"cattle.io/skipUninstall": "true"` in the annotations.


Delete the app from the ember UI --> downstream cluster --> default project --> apps 
or 
via kubectl by running the below command from the local cluster
kubectl delete apps.project.cattle.io aws-event-sources -n p-mr57l

From apps  & market place of the downstream cluster--> Repositories --> add a new repository with the details: 
name: helm3-library, 
URL: https://git.rancher.io/helm3-charts, 
branch: master
```
3. From apps  & market place --> edit/upgrade apps

**Result**
Multiple same versions of the apps are shown in the UI

**Expected Result**
Expected only 1 version each of the versions but not multiple versions to show up

**Screenshots**
<img width="300" alt="Screen Shot 2021-12-11 at 7 32 23 PM" src="https://user-images.githubusercontent.com/38144301/145699177-4e989fa8-f5d6-48f5-ba95-0f618a511cc0.png">

<img width="300" alt="Screen Shot 2021-12-11 at 7 31 51 PM" src="https://user-images.githubusercontent.com/38144301/145699169-bd7f550f-9610-47ca-9c68-71ac926201dd.png">

Found while validating https://github.com/rancher/dashboard/issues/4402

**Comment by nwmac** [comment]
@anupama2501 I could not reproduce this - I have generally not been able to reproduce issues for app migration. I think there is a step missing in your steps above - can you check - I think the annotation  "cattle.io/skipUninstall": "true" needs to be added.

**Comment by anupama2501** [comment]
@nwmac thanks for pointing that out. I edited the comments and added the annotation `"cattle.io/skipUninstall": "true" ` that should be added to the app from local cluster.

**Comment by rak-phillip** [comment]
@anupama2501 and I discussed and after attempting to replicate it, this appears to be resolved. Moving to test for the time being.

**Comment by anupama2501** [comment]
Closing this issue as its not seen on v2.6-head 2a7857d and will re-open if seen in future.
