### ISSUE TITLE
[Improvement] Allow user to create namespaces in the create project page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4759]
- This would be a convenience feature, currently have to 
  - create project
  - find project in projects/namespace list 
  - create each namespace individually
- This would remove the out and in flow and add the ability of creating multiple namespaces at once
- Care will need to be taken how we
  - show the edit namespace component within the edit project (no tabs in tabs...)
  - handle namespace creation failures (`save` again should successfully update the previously created project without collision errors)

**Comment by vincent99** [comment]
#4625 ?

**Comment by richard-cox** [comment]
#4625 :+1: I searched.... very very badly
