### ISSUE TITLE
"This page could not be found" is seen when a user deletes a cluster on k8s 1.22 rke2 version

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4766]
**on 2.6-head commit id: `2a7857d`**

- Deploy an RKE2 AWS Node driver cluster 1.22rke2 version
- when the cluster is up and Active, select the cluster and click on delete.
- "This page could not be found" is seen
- User has click on Go Back too Home, to get out of this page.

**Comment by gaktive** [comment]
@jordojordo to reproduce this. @nwmac can assist during UK hours if it gets tricky.

**Comment by jordojordo** [comment]
@sowmyav27 
I could not replicate the issue. I tried on multiple cloud providers to see if it was an AWS issue but did not encounter the problem.

https://user-images.githubusercontent.com/40806497/146067322-2541b016-78e3-4387-a4b9-35e03c5aa9da.mp4

---

Here's my config for the cluster (Is this the correct config to test with?):
 
![config](https://user-images.githubusercontent.com/40806497/146067805-d3b3b6a5-823b-4e26-9405-477db7d13936.png)

---

Version:

![about](https://user-images.githubusercontent.com/40806497/146067458-4860dd0b-c41f-4834-b126-531a4c03ee07.png)

**Comment by sowmyav27** [comment]
Happens only with an 1.22RKE2 version node driver cluster

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `39cecf0`**

Verified this issue is not seen when deleting a 1.22 RKE2 aws cluster
