### ISSUE TITLE
Downstream cluster's Project/Namespace list does not group namespaces by project

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4768]
Downstream
![image](https://user-images.githubusercontent.com/18697775/145967195-4c36f892-5560-4b58-8f59-03d90ffb44a6.png)

![image](https://user-images.githubusercontent.com/18697775/145967270-22c4349c-b235-424b-bd31-d5bf0cd8a651.png)

Upstream
![image](https://user-images.githubusercontent.com/18697775/145967089-a804d3f1-f418-4b37-9bc3-1aaebba5e4a4.png)

**Comment by rak-phillip** [comment]
@richard-cox I'm not able to replicate this one after standing up a new docker instance against `6de683b`. This is what see in my downstream clusters

![image](https://user-images.githubusercontent.com/835961/146072947-7389dc64-f10e-480b-96f4-f7cb93a71bdb.png)

Only `local` is listed as `Not in a Project`.. Could there be a replication step that I am missing?

**Comment by richard-cox** [comment]
@rak-phillip Only difference I can see is RKE vs an imported (k3s) cluster

**Comment by rak-phillip** [comment]
@richard-cox I'm trying to understand what looks to be a discrepancy in the Project ID for imported clusters. For example, I'm comparing two clusters

1. RKE Cluster - `{ clusterId: c-m-fzwlxl2w, projectId: p-6zmrq }`
2. Imported Cluster - `{ clusterId: c-m-5gktzt5x, projectId: p-jpbft }`

I can clearly see the `clusterId`/`projectId` pair for the RKE Cluster when I query `v1/management.cattle.io.projects`, but the `projectId` for the Imported Cluster appears to be a different value when I query the same endpoint: `p-4xr9d`.. doesn't look to be what we expected

[This is where we fail to make to lookup for the current cluster/project](https://github.com/rancher/dashboard/blob/5da61bfe8e2aa721ff6c8fac89af5476afe3301e/models/namespace.js#L112)

**Comment by richard-cox** [comment]
@rak-phillip This might be another spurious issue I've opened. The cluster was previously imported to a different local cluster, so the projects referenced by the namespaces may not exist. I'll double check and also test with a fresh local cluster.

**Comment by richard-cox** [comment]
Confirmed. Tested with a brand new imported cluster and the namespaces are correctly grouped into projects. In the re-imported cluster the projects associated with Rancher namespaces don't exist, so must have come from the cluster they were originally created in. 

Overall, I think on import rancher should be assigning it's updated assets to the cluster projects it's just created. I'm not gonna create an issue for it their side, it'll be so low down the stack I'll be fighting stale bot until the heat death of the universe.

I think this has come up before, so @rak-phillip, I apologise for wasting your time on this.

**Comment by rak-phillip** [comment]
@richard-cox I wouldn't consider a good opportunity for analysis to be time wasted. At the very least, we better understand the issue that's in play 😁
