### ISSUE TITLE
Unable to upgrade legacy apps from explorer legacy page

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4774]
Setup

Rancher version: 2.6.3-rc5 upgraded from v2.6.2
Browser type & version: Chrome

**Describe the bug**
For the apps that are installed on an ember UI using ember catalog repositories or by turning on the legacy feature flag on the explorer UI from legacy --> project --> apps, the upgrade doesn't go through. The UI screen reloads and stays in the same page. The apps won't upgrade.

**To Reproduce**
1. Create rancher server on v2.6.2 [can be 2.5.x as well]
2. Enable the legacy feature flag.
3. Navigate to the cluster explorer legacy --> projects --> apps 
4. Install a few apps like aws-event-sources, docker-registry, redis, mongodb-replicaset
5. Upgrade the rancher server to 2.6.3-rc5
6. Navigate to the cluster explorer legacy --> projects --> apps 
7. Upgrade any of the apps

**Result**
The apps won't upgrade. UI page reloads and stays in the same page

**Expected Result**
Expected the apps be upgraded.

**Additional context**
Backend ticket for this https://github.com/rancher/rancher/issues/35680

This is the case for multi cluster apps as well.

Following scenarios be covered while testing:
2.5.11 --> 2.6.3-rc Multi-cluster apps legacy apps/ single cluster apps both helm3 and library apps installed via helm2
2.6.2 --> 2.6.3-rc Multi-cluster apps legacy apps/ single cluster apps both helm3 and library apps installed via helm2

**Comment by catherineluse** [comment]
The UI part of this problem is fixed, as the upgrade form renders now.

However, when the form is submitted, an error occurs:

```
Validation failed in API: incompatible kubernetes version 
```

In order to be upgraded, a back end change will be needed to allow upgrades when the version doesn't change, even if the current version exceeds the max version. https://suse.slack.com/archives/C02AXMUQ4A1/p1639674558256500?thread_ts=1639642155.249400&cid=C02AXMUQ4A1

**Comment by anupama2501** [comment]
Re-opening 2.6.3-rc8 upgraded from 2.6.2

- Created a multi cluster app in 2.6.2 from hamburger menu --> multi cluster apps 
- Install redis or mariadb --> I installed both the apps 
- Upgrade the rancher server to 2.6.3-rc8
- from multi cluster apps, upgrade the legacy app
- The following error is seen as soon as we click on upgrade

<img width="500" alt="Screen Shot 2021-12-17 at 7 39 56 PM" src="https://user-images.githubusercontent.com/38144301/146627953-0d1d699d-ff1b-410c-9737-bc38a117c381.png">

**Comment by anupama2501** [comment]
Verified on v2.6.2 --> v2.6.3-rc10

1. On 2.6.2, installed a few apps like argo-cd, docker-registry, multi-cluster apps - redis, mariadb on an rke1 node driver cluster
2. Upgraded the rancher server to v2.6.3-rc10
3. verified from legacy --> projects --> apps --> able to upgrade apps 
4. Verified  upgrade works on multi cluster apps as well - mysql,redis post rancher server upgrade
