### ISSUE TITLE
What's New process

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4777]
Going forward on tickets like https://github.com/rancher/dashboard/issues/4678, once PMs provide us with the content for the What's New section, as part of the review process, we need a way to poke the other engineering managers to validate that the wording is correct.

The two scenarios to consider:
1) the information is accurate
2) if a feature or other documented component is pulled at the last minute, we reflect that information appropriately

**Comment by catherineluse** [comment]
I think the docs team should do the poking since they are talking to the same people about the release notes as well

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/issues/5041 features the work as part of the overall 2.6.4 release as a checklist item from the parent https://github.com/rancher/rancher/issues/36375. I'll work with @Jono-SUSE-Rancher on what he sees from the broader product goals, then figure out if the UI needs its own timelines.

**Comment by MKlimuszka** [comment]
Does this require QA testing?

**Comment by gaktive** [comment]
@MKlimuszka For now, there's nothing to test since this more of the process of how UI does the work. I'm going to push this to 2.6.6 since for 2.6.5, we'll just do what's needed for https://github.com/rancher/dashboard/issues/5638.

**Comment by gaktive** [comment]
For now, the process has been documented internally since it remains ad hoc.

For 2.7.0, PR started - https://github.com/rancher/dashboard/pull/7172 (draft)

**Comment by gaktive** [comment]
Updated PR based on current feedback. Should be ready for @nwmac shortly.
