### ISSUE TITLE
Create button is missing for GlobalDNS providers and global DNS entry

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4784]
Setup

Rancher version: 2.6.3-rc6
Browser type & version: Chrome

**Describe the bug**
Create button is missing from the Global DNS providers and Global DNSes

**To Reproduce**
1. From local cluster, in the search bar or command + k type DNS
2. Select Global DNS providers or global DNS

**Result**
Create button is missing in both the pages.

**Expected Result**
Expected the create button to be present

**Screenshots**

<img width="500" alt="Screen Shot 2021-12-16 at 10 43 32 AM" src="https://user-images.githubusercontent.com/38144301/146430086-eb76c150-0cd3-4903-8834-a132db3941bb.png">

**Comment by richard-cox** [comment]
`/v1/schemas/management.cattle.io.globaldnsprovider` shows `blocked-PUT` . `/v3/schemas/globalDnsProvider` does have `POST` permissions. This could be another  steve --> norman save thing?

**Comment by gaktive** [comment]
Per @vincent99, we should be able to use the Ember iFrame page here. There's no need to switch the `save` for `management.cattle.io.globaldnsprovider`

**Comment by richard-cox** [comment]
Settings related to global DNS should be available (after enabling the `Legacy` feature flag) via burger menu --> Legacy Apps --> Mutli-cluster Apps --> `Global DNS Entries` and `Global DNS Providers`. I've tested the create flow for both (with junk values) and they successfully complete. Both resource then do show up in Explorer --> More Resources --> Rancher --> `GlobalDnses` and  `GlobalDnsProviders`.

I think there's a general issue here of showing these core resources in the explorer. I think they should still appear in `More Resources`... however with a resource label explaining that management is done via the legacy route. I'll create a separate 2.6.4 ticket for this

**Comment by anupama2501** [comment]
Verified on 2.6-head ed77b51  can be created from hamburger --> multi cluster --> apps --> Global DNS provider and global DNS entry
