### ISSUE TITLE
Upgrade icon is missing from installed Apps

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#4786]
**Setup** : 
- Rancher version: v2.6.3-rc6
- Browser type & version: Chrome

**Describe the bug**
The upgrade icon doesn't appear on installing Longhorn previous version. For example if user install v1.2.2, the upgrade icon doesn't appear 

**To Reproduce**
1. Go to Apps and marketplace.
2. Install a prior version Longhorn (not the latest one)
3. Check the installed app.

**Result**
The upgrade icon is missing.

**Expected Result**
The upgrade icon should appear and user should be able to see that an upgradable version is available.

**Screenshots**
<img width="1539" alt="Screen Shot 2021-12-16 at 11 03 00 AM" src="https://user-images.githubusercontent.com/60111667/146452730-bf46a533-092f-4864-be14-2473fc609d7e.png">

**Additional context**
https://github.com/rancher/charts/pull/1660#issuecomment-996151993

**Comment by khushboo-rancher** [comment]
This is not specific Longhorn App, happening with other apps as well.

**Comment by richard-cox** [comment]
The upgrade button now shows in all cases (if there seems to be an upgrade). This includes legacy apps installed pre 2.6.3. This has been tracked with https://github.com/rancher/dashboard/issues/4797

**Comment by sowmyav27** [comment]
**On 2.6-head commit id:`981fbc8`**

I can see the upgrade icon now. And I can upgrade successfully on clicking it
<img width="1406" alt="Screen Shot 2021-12-17 at 10 44 28 AM" src="https://user-images.githubusercontent.com/26032343/146592945-dae2945b-21f7-4c03-b949-c752f347c22e.png">
