### ISSUE TITLE
Advanced selector settings for GitRepo get lost when editing

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4788]
Internal reference: SURE-3455

Issue description: 
When editing an exiting advanced selector GitRepo on UI form and just save it without changes, it removes advanced settings and just set as clusterGroup.

Business impact:
No business impact.

Troubleshooting steps:
Reproducing the environment and performing tests with advanced selector GitRepo options.

Repro steps:

- created an GitRepo with kubectl+yaml and/or through UI. 
```
apiVersion: fleet.cattle.io/v1alpha1
{{ kind: GitRepo}}
{{ metadata:}}
  name: test5
  namespace: fleet-default
{{ spec:}}
  branch: labopensuse
  insecureSkipTLSVerify: false
  paths:/lab/fleet
  repo:https://github.com/path/to/k8s.git
  targets:

  - clusterGroup: sandbox
    clusterSelector:
      matchLabels:
        fleet-managed: "true"
{{        name: sandbox }}
```
- edited as UI form, did change anything, just save it. It removes the clusterSelector and left clusterGroup only. When go to edit UI form, its loads the dropbox target selected as clusterGroup and not the advanced settings done previously.
- outcome after saved it
```
targets:

  - clusterGroup: sandbox
```

Workaround:
Is workaround available and implemented? no
What is the workaround:

Actual behavior:
GitRepo edit form UI loads and filled target selector as clusterGroup.

Expected behavior:
GitRepo edit form UI loads the advanced selector settings accordingly as previously created.

**Comment by davidnuzik** [comment]
The issue doesn't mention what version the issue is reproduced with. I will try v2.6.3.

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Environment:**

Rancher version: v2.6.3
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Reproduction steps:**

1. Navigate to Continous Delivery on the left nav pane. Create a GitRepo and do not fill any fields in, rather, click on the "Edit as YAML" button on the bottom of the page.
2. Remove all content. Add this content:
```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: test
  namespace: fleet-default
spec:
  branch: labopensuse
  insecureSkipTLSVerify: false
  paths: [/lab/fleet]
  repo: https://github.com/path/to/k8s.git
  targets:
  - clusterGroup: sandbox
    clusterSelector:
      matchLabels:
        fleet-managed: "true"
        name: sandbox
```
3. Stay in the YAML editor and click the Create button. This will create the repo (it won't deploy but this is not relevant)
4. Now, in the UI on the Git Repos page, click on the vertical "..." on the right and click "Edit YAML"
![image](https://user-images.githubusercontent.com/45179589/151857457-aa9078e9-4107-456c-8239-c18f8ef83f19.png)

5. Notice - the content is the same and is correct. Our clusterSelector is still listed just as it was prior. Go back.
6. Now, do the same but just chose "Edit Config" (so we get the UI form). On the bottom of the page click the "Edit as YAML" button so we get back in the YAML editor.

**Result:**
I reproduced. Upon step 6 of the steps above, I see the clusterSelector is missing now:
![image](https://user-images.githubusercontent.com/45179589/151857696-8ddd0de7-e00c-4796-a992-cda3bd50e54b.png)

 
-----
 
**Validation Environment:**

Rancher version: v2.6-head `7efbeab` 1/31/2022
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Execute the exact same steps as outlined above in the Reproduction section.
 
**Result:**
I now no longer reproduce and the issue appears to be fixed. Upon the last step (step 6 above) when I get to the YAML editor the clusterSelector is still listed and the YAML content is unchanged (except for the expected additional commented-out lines the UI adds -- this doesn't hurt anything). Below is a screenshot showing the fix:
![image](https://user-images.githubusercontent.com/45179589/151858474-5509a999-504d-4e58-979f-acba7c21d1d6.png)
