### ISSUE TITLE
Overview menu options going to Property 'attributes' of undefined error page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#479]
Steps:
1.  Go to overview page
2. Select Edit/Clone or download YAML from menu

Results:  Going to error page for Edit/Clone and does nothing for Download
![image](https://user-images.githubusercontent.com/11514927/78604528-c77db100-780e-11ea-9047-26f93d4c5e45.png)

**Comment by westlywright** [comment]
Can we retest this? I believe the erroneous links were removed in [this PR](https://github.com/rancher/dashboard/pull/525)

**Comment by deniseschannon** [comment]
@westlywright it seems we removed the Edit/Clone and Download option from the menu. is that correct? 

<img width="137" alt="Screen Shot 2020-04-24 at 3 21 23 PM" src="https://user-images.githubusercontent.com/11410997/80261459-4f512100-863f-11ea-9c0c-d7d975851aaa.png">

**Comment by westlywright** [comment]
@deniseschannon I didn't remove it explicitly, I added more logic to make sure we have the correct links on the resource to take the action requested. That is why we were seeing the errors.

**Comment by tfiduccia** [comment]
Verified fixed:
Confirmed we did not have these options in ember 'dashboard' for the cluster.
