### ISSUE TITLE
[UI]: Cannot create apps in ember UI

### ISSUE THREAD

**Issue by rmweir** [rancher/dashboard#4791]
**Rancher Server Setup**
- Rancher version: v2.6.3-rc7

**Information about the Cluster**
- Kubernetes version:
1.21.7
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
have tried local and downstream

**Describe the bug**

When selecting an app to launch I am returned to the apps overview page. This happens regardly of constraints in the chart.

**To Reproduce**
 
1. Add grafana catalog (because it isn't using rancher max constraints). URL: https://github.com/grafana/helm-charts, branch: main.
2. Go to legacy apps page or <rancher-url>/g/clusters apps page for a project in a cluster.
3. Go to "Launch". Select an app (I installed enterprise-logs).

**Result**
Automatically returned to apps overview page.

**Expected Result**

Should see the apps details page for launching the app.

**Comment by anupama2501** [comment]
Verified on 2.6.3-rc8

- Enabled legacy flag
- From cluster explorer --> projects --> catalog --> add a repo with the details . URL: https://github.com/grafana/helm-charts, branch: main.
- From projects --> apps --> Able to launch apps and install them tried with `enterprise-logs` and `enterprise metrics`
