### ISSUE TITLE
`Steve` DNS related resource types can cause confusion

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4792]
**Describe the bug**
Following on from rancher/dashboard#4784, Global DNS resources are shown in 'More Resources', however management of them is done via the Legacy route.

**Expected Result**
See comment https://github.com/rancher/dashboard/issues/4784#issuecomment-996614509. We could either remove these resources from `More Resources` or add a resource label explaining management done in legacy route.

**Comment by nwmac** [comment]
@richard-cox I am going to bump this to 2.6.5, unless you have any objections?

**Comment by richard-cox** [comment]
@nwmac bumped!

**Comment by catherineluse** [comment]
I think they should only be under Legacy because they are deprecated.

**Comment by nwmac** [comment]
Remove from more resources

**Comment by aalves08** [comment]
The idea here would be to remove the side menu entry from `More resources` --> `Rancher`, right?

I've created some dummy items for `Global DNS Entries` and `Global DNS Providers` on `Legacy Apps` --> `Multi-cluster Apps` --> `Global DNS Entries` and `Global DNS Providers`.

However they don't appear on `More resources` --> `Rancher` as I would expect.

<img width="2003" alt="Screenshot 2022-05-13 at 12 17 36" src="https://user-images.githubusercontent.com/97888974/168273135-7c302532-a1c2-4556-882b-ab0a6ade664a.png">
<img width="2047" alt="Screenshot 2022-05-13 at 12 17 59" src="https://user-images.githubusercontent.com/97888974/168273148-d3f220d5-d461-4eda-aa31-d842942a8ac3.png">
<img width="2047" alt="Screenshot 2022-05-13 at 12 18 02" src="https://user-images.githubusercontent.com/97888974/168273152-83debd2c-18ba-4261-ad63-b37bd0ad570d.png">

The only reference I could find for it's configuration is on the `multi-cluster-apps` prod config:
https://github.com/aalves08/dashboard/blob/master/shell/config/product/multi-cluster-apps.js#L56-L65

Am I looking at this right? @richard-cox

**Comment by richard-cox** [comment]
@aalves08  You'll need to change your project/ns filter top right to `All Namespaces`, they should then show up

![image](https://user-images.githubusercontent.com/18697775/168795520-fdc4b920-576e-424f-97d8-5b2e58727d42.png)

`<rancher url>/v1/management.cattle.io.globaldnsprovider`
`<rancher url>/schemas/management.cattle.io.globaldnsprovider`

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 0fd630d
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###

Tested this issue with the following steps:
1. Activate `legacy` feature flag
    - `Global Settings` -> `Feature Flags` -> `legacy`
2. Add DNS entry to `Global DNS Entries` using values described [here](https://github.com/rancher/dashboard/issues/4784#issuecomment-996614509)
3. Add DNS provider to `Global DNS Providers` using values described [here](https://github.com/rancher/dashboard/issues/4784#issuecomment-996614509)
4. Verify that the created resources are not visible through exploring cluster. Should only be available through the legacy route.
    - 'local' -> 'More Resources' -> 'Rancher' -> `GlobalDnses` and `GlobalDnsProviders` should not be present

**Result** - Pass

`GlobalDnses` and `GlobalDnsProviders` are no longer reachable through explorer and can be found through the legacy route.
![image.png](https://zube.io/files/rancher/449c2a2b5ccef594706be2666c669655-image.png)
