### ISSUE TITLE
Create a detail view for Fleet Bundle Resource

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4793]
The Fleet resource `fleet.cattle.io.bundle` does not have a detail view - we should add one.

Currently we show the YAML for the bundle as there is no detail view - for large bundles, this is slow to load - hopefully adding a detail view will avoid this - the user would still then be able to switch to the YAML view.

You should look in the `detail` folder for examples - but as long as the vue file in that folder is named with the resource name, it will be shown as the default view instead of the YAML.

Take a look at the details of the bundle resource and choose appropriate data to show on the detail view, e.g.

- The type of the bundle (kustomize, helm etc) - I think we can get this from the values under the `spec`
- The number of resources in the bundle (could show the list of resources too)
- The ready cluster information
- Status information for the bundle
- The clusters that the bundle it deployed to

You should manually create a large bundle (the max resource size is 1MB) and check that currently when you view the bundle it is slow to load and then check that with the detail view, this is no longer the case - we need to check if the slowness is dues ot the YAML rendering or the data fetch.

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.

**Comment by izaac** [comment]
Is this just click on a bundle to check its details ? Is that the view?

**Comment by Shavindra** [comment]
@izaac Please refer to https://github.com/rancher/dashboard/pull/5068 I've updated steps to test. It encompass multiple changes. Hope this is clear.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.6.4-rc10

Followed test instructions from: https://github.com/rancher/dashboard/pull/5068

* Deployed several clusters
* Added example gitrepo 
* Clicking on the git repo shows the bundles included
* With a bundle in an error state, the error is shown
* Statuses are displayed in different colors on the distrobution graph
* Counts of ready bundles/resources are shown
* Dropdowns for Bundles and Resources show the detailed view of counts of the possible states
* Pending statuses are shown correctly
* The Bundles details page is accessible from the left nav-menu
* All bundles are shown, and clicking on one shows the resources available
