### ISSUE TITLE
Add a Bundles tab to the GitRepo detail view

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4794]
Currently the GitRepo Detail view has the first tab 'Resources' - we should add a new tab 'Bundles' that shows a list of the bundles and metadata about them. Where a bundle has an error, we should show this in a table row below the bundle (this is a pattern we use elsewhere)

![image](https://user-images.githubusercontent.com/1955897/146535824-0b849952-bab7-41d2-b231-63d5902e2972.png)

This will address this is issue rancher/dashboard#4684 (I don't think we can do part 2 in that) - but we should test with their example once this is done.

Start with a list of the bundle data as this will be easy to do - but we could consider a block for each bundle presented a bit more visually-interesting if we know that in general the number of bundles will be relatively small.

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.

**Comment by izaac** [comment]
Rancher version `v2.6.4-rc10`
There's a Bundles Tab now displayed and visible by default
![Screen Shot 2022-03-18 at 1 23 28 PM](https://user-images.githubusercontent.com/27659/159078259-03105c3e-238b-4145-9e13-e8cc363065db.png)
