### ISSUE TITLE
Error seen on fleet Workspaces page when try to create any workspace

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#4798]
**Summary:**

An error is shown when you try to create any workspace on the Workspaces page under Continous Delivery (fleet) 
`dashboard/c/<clusterId>/fleet/management.cattle.io.fleetworkspace/create#labels`

-----

**Environment:**
Rancher version: v2.6-head `39cecf0` 12/17/2021
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21

**Steps to Reproduce:**
1. After installing rancher, try to create a workspace under Continous Delivery.
 
**Expected Result:**
No errors

**Actual Result:**
An error is observed in the UI and in the console.
Screenshot:
![image](https://user-images.githubusercontent.com/45179589/146610111-40645e35-1079-4242-bd71-1fdc20ac5017.png)

Console log:
```
14:23:35.974 CreateEditView mixin failed to save:  TypeError: setting getter-only property "annotations"
    t impl.js:214
    d runtime.js:45
    _invoke runtime.js:274
    e runtime.js:97
    Babel 6
    actuallySave impl.js:208
    o impl.js:177
    d runtime.js:45
    _invoke runtime.js:274
    e runtime.js:97
    Babel 6
    save impl.js:150
    VueJS 4
    click CruResource.vue:1
    VueJS 4
    clicked AsyncButton.vue:201
    VueJS 33
impl.js:203:16
```

**Additional Info:**
The workspace is still created regardless of the error.
I can still apply labels/annotations without any issues (we just see this ugly error). I can also edit and apply labels/annotations later without any issues or update existing ones I initially created.

**Comment by sgapanovich** [comment]
was able to reproduce on `2.6-head 981fbc8` (error is different but related)
![dave](https://user-images.githubusercontent.com/40282141/146610661-1c4ef6fd-817f-4c27-9341-1571f633cf69.jpg)

console error 
```
impl.js:203 CreateEditView mixin failed to save:  TypeError: Cannot set property annotations of [object Object] which has only a getter
    at Function.assign (<anonymous>)
    at impl.js:214
    at d (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.O.forEach.t.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)
```

**Comment by davidnuzik** [comment]
Reproduced again (did this check to ensure it wasn't just one environmental issue I had) v2.6-head `b4d83fb` (latest v2.6-head)

- 2 HA setups
- 2 single-node docker setups

**Comment by sowmyav27** [comment]
**On 2.6.3-rc8**

No errors seen when workspace are created. 
Able to create multiple workspaces
