### ISSUE TITLE
Assigning clusters to workspaces does not work (Fleet)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#4799]
Related: https://github.com/rancher/dashboard/issues/4798

**Summary:**

If I try to assign any cluster to a Workspace I created the modal is stuck when I try to add it with "Applying..." and never completes. In the browser dev console we see a TypeError.
![image](https://user-images.githubusercontent.com/45179589/146611259-4ffb109b-875f-475a-8a8e-f38df8ac58cd.png)

![image](https://user-images.githubusercontent.com/45179589/146611247-b1fa9e67-cdcf-4e31-9b5f-97614a08e318.png)

-----

**Environment:**
Rancher version: v2.6-head `39cecf0` 12/17/2021
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2
Downstream K8s version: 1.21

**Steps to Reproduce:**
0. Have rancher installed and at least one downstream rke2 cluster.
1. Create a fleet workspace. Note during this process you will get an error due to the related bug, https://github.com/rancher/dashboard/issues/4798.
2. Now, navigate to the Clusters page (under Continuous Delivery) and click the checkbox for it. Click the "Assign to..." button. Try to assign it to the workspace.
 
**Expected Result:**
Assigns without any issues.

**Actual Result:**
The modal gets stuck and we see a TypeError in the browser dev console.

**Additional Info:**

**Comment by davidnuzik** [comment]
I can reproduce this on additional environments on latest v2.6-head, but on those I get a slightly different TypeError like:
![image](https://user-images.githubusercontent.com/45179589/146614072-df2df4e3-c879-4a8f-95ef-a073ce278de2.png)

**Comment by sgapanovich** [comment]
Rancher version: 2.6-head 981fbc8
Rancher cluster type: HA

Downstream cluster type: aws ec2 node cluster
Downstream K8s version: v1.21.7

----------

was able to assign a cluster to a workspace 
https://user-images.githubusercontent.com/40282141/146614365-1db1dade-e104-4da8-b970-ea15253dc9b7.mp4

**Comment by davidnuzik** [comment]
Latest v2.6-head `b4d83fb` 

I have 2 HA setups now that reproduce and 2 single-node docker setups that reproduce. Gary and team are looking into the issue.

**Comment by sowmyav27** [comment]
**on 2.6.3-rc8**

- No error seen when assigning clusters to workspaces 
- Assigned multiple clusters to different workspaces successfully
