### ISSUE TITLE
Refresh rke-machine-config before updating during cluster create

### ISSUE THREAD

**Issue by thedadams** [rancher/dashboard#4800]
**Describe the bug**

If, while creating an RKE2 cluster, a standard user clicks "Edit as YAML" before creating, the UI will create the `rke-machine-config`s so it can populate the YAML with the correct names of the configs. Then, when a user clicks "Create," the UI will update the `rke-machine-config`s before making the request to create the cluster.

The issue is, after [this](https://github.com/rancher/rancher/issues/35868) backend change goes in, the UI will display an error about having an outdated version of the `rke-machine-config` object when it tries to update it. That is because Rancher will now have to alter this `rke-machine-config` to ensure the user has access to modify the config. Therefore, before making the request to update the `rke-machine-config`, the UI should first make a GET request to get the latest version of the `rke-machine-config` and then make the update (PUT) request.

**To Reproduce**

After the above linked backend issue goes in, the reproduction steps are as follows:
1. As a standard user, create an RKE2 cluster (any provider)
2. Before clicking "Create" click "Edit as YAML"
3. One the "Edit as YAML" screen, click "Create"

**Result**
An error about trying to update an older version of the `rke-machine-config` object will appear.

**Expected Result**

The create should be successful.

**Comment by thedadams** [comment]
Please note that this error will only occur once https://github.com/rancher/rancher/issues/35868 is fixed.

**Comment by thedadams** [comment]
The backend PR for this issue has been merged.

**Comment by codyrancher** [comment]
@thedadams you said that the backend issue for this was merged but you also said https://github.com/rancher/rancher/issues/35868 needs to be fixed first. Do you consider this ready for the front end?

I have the latest version of rancher and I don't see this error.
![rke-yaml](https://user-images.githubusercontent.com/55104481/151250621-6280c112-95bc-43ea-a45f-7d7953da213f.gif)

**Comment by thedadams** [comment]
@codyrancher Are you logged in as a standard user or an admin? I believe this issue is related to standard users.

**Comment by codyrancher** [comment]
@thedadams I've gotten two separate errors when creating a cluster as a standard user after going to edit as yaml.

**With no existing clusters see:**
`Method PUT not supported`

**With one existing cluster I see:**
`digitaloceanconfigs.rke-machine-config.cattle.io "nc-cjackson2-pool1-qn88s" is forbidden: User "u-jll7d" cannot update resource "digitaloceanconfigs" in API group "rke-machine-config.cattle.io" in the namespace "fleet-default"`

The standard user can create a cluster when going through the form so it's not a permissions issue. Even though the message is different is this actually what's expected?

**Comment by thedadams** [comment]
@codyrancher That is the original error that should be fixed in the backend. Are you still seeing this error on the latest v2.6-head of Rancher?

**Comment by codyrancher** [comment]
> @codyrancher That is the original error that should be fixed in the backend. Are you still seeing this error on the latest v2.6-head of Rancher?

Yeah, same version as I posted in the gif above (published about 1 hour ago):
`v2.6-1de3e6b8569979807e8d5edc82c079bfadca918f-head`

**Comment by codyrancher** [comment]
After talking with @thedadams and updating the webhook I can now produce the issue.

**Comment by Auston-Ivison-Suse** [comment]
**Rancher Setup For Reproduction**
Rancher version: v2.6.3
User: Standard User
Downstream Cluster: 
- RKE2 on Amazon ec2


**Steps For reproduction**
1. As a standard user, create an RKE2 cluster (any provider)
2. Before clicking "Create" click "Edit as YAML"
3. One the "Edit as YAML" screen, click "Create"

**Results**
We get an error stating `Method PUT not supported`

**Screenshot of error reproduction**
![MethodPutNotSupported.png](https://zube.io/files/rancher/ba4d1e3f5344bbf2541883d95311f7fe-methodputnotsupported.png)


**Setup For Validation**
Rancher version: v2.6.head(e55a04c)
User: Standard User
Downstream Cluster: 
- RKE2 on Amazon ec2

**Steps For Validation**
1. As a standard user, create an RKE2 cluster (any provider)
2. Before clicking "Create" click "Edit as YAML"
3. One the "Edit as YAML" screen, click "Create"


**Results**
The put request was able to go through and the cluster was successfully provisioned.. 

![MethodPut.png](https://zube.io/files/rancher/fd9e2a8fa69348ab0d11b009db0b041e-methodput.png)


**Sanity Checks**
- Tested and a standard user as well as admin: pass
- Custom cluster as able to provision. 
- Hosted cluster was able to provision
