### ISSUE TITLE
when a logo/image is not present on a legacy app too many API requests are sent to the backend 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4803]
Setup

Rancher version: 2.6.2
Browser type & version: Chrome

**Describe the bug**
I have helm3 library apps installed on 2.6.2. If the logo is not found for the app, eg mariadb, the API makes too many requests and won't even when we perform an action like update/edit/install.
Even if we come out of the app page, this seems to be the case.

**To Reproduce**
Create an app mariadb by enabling legacy flag from explorer --> legacy --> project --> select a namespace in the namespace picker --> launch maria db

**Result**
If we verify the network tab, too many requests are seen to be sent to the backend. the requests won;t stop until we navigate to a different page from the apps page.
The requests seem to be sent even after we come out of the app page.
```
404 page not found
```
**Expected Result**
Did not expect too many API calls while in the app and after coming out of the app.
**Screenshots**
While in the maria db app page:
```
Request URL: https://<redacted>/assets/images/generic-catalog.svg
Request Method: GET
Status Code: 404 Not Found
Remote Address:<redacted>
Referrer Policy: strict-origin-when-cross-origin
```
<img width="400" alt="Screen Shot 2021-12-17 at 11 32 48 PM" src="https://user-images.githubusercontent.com/38144301/146633401-cd517ea9-5706-474a-be63-0e054781913d.png">

While I navigated back to apps page:

Request URL: https://<ip>/p/c-97tj7:p-qmpsv/apps/undefinedassets/images/generic-catalog.svg
```
Request Method: GET
Status Code: 200 OK
Remote Address: <redacted>
Referrer Policy: strict-origin-when-cross-origin
```
<img width="400" alt="Screen Shot 2021-12-17 at 11 34 34 PM" src="https://user-images.githubusercontent.com/38144301/146633486-857e7720-b757-4003-8379-6ced49eefcfd.png">

**Comment by cmurphy** [comment]
Verified :heavy_check_mark: 

Verified original issue

1. edit setting ui-index, set to `https://releases.rancher.com/ui/2.6.2/index.html`
2. with network tools open in browser, navigate to legacy projects, go to install mariadb app
3. observe repeat requests for generic-catalog.svg

Verified fix

1. change ui-index setting back to default (latest)
2. hard refresh
3. go back to install mariadb app
4. failing requests are gone :heavy_check_mark:

**Comment by cmurphy** [comment]
Verified on f904267
