### ISSUE TITLE
resourceQuota annotation is incorrectly set on projects and leads to ResourceQuota not being created

### ISSUE THREAD

**Issue by cmurphy** [rancher/dashboard#4804]
**Setup**
- Rancher version: v2.6.3-rc11
- Browser type & version:

**Describe the bug**

When creating a project with Resource Quotas and then creating a namespace in it, the ResourceQuota resource never appears on the downstream cluster and Rancher complains about the quota value:

```
[ERROR] error syncing 'n3': handler namespace-auth: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', handler resourceQuotaSyncController: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', requeuing
```

It's because the `field.cattle.io/resourceQuota` annotation has a space after the value, or between the value and the units: `field.cattle.io/resourceQuota: "{\"limit\":{\"limitsMemory\":\"1024 Mi\"}}"`

**To Reproduce**

1. Create a project. Go to the Resource Quotas tab and add any resource. A resource like `ConfigMaps` has no units, while a resource like `CPU Limits` has a unit like `m`.
2. Create a namespace in the project.

**Result**

Namespace is created, but no ResourceQuota is created.

**Expected Result**

ResourceQuota is created in the namespace.

**Screenshots**

![image](https://user-images.githubusercontent.com/1220710/146657271-e12b3c82-05c6-488e-8b8e-b8f917f09b08.png)
![image](https://user-images.githubusercontent.com/1220710/146657301-224d8863-d972-4abc-8174-6342b449c639.png)

The values on the Project are set correctly:

![image](https://user-images.githubusercontent.com/1220710/146657368-5522705a-70f2-4f83-aee6-1806c44224c1.png)

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment]
Fix is available using the dashboard `v2.6.3-patch1-rc1` release. Until there's an RC of Rancher this can be tested by
1. Bring up Rancher 2.6.3 and log in to the Dashboard
2. `Global Settings` --> `Advanced Settings`
  i.  Set `ui-dashboard-index` to `https://releases.rancher.com/dashboard/v2.6.3-patch1-rc1/index.html`
  ii. Set `ui-offline-preferred` to `Remote`
3. Refresh the browser

**Comment by richard-cox** [comment]
rancher/dashboard#4704 Should be verified when this is tested

**Comment by anupama2501** [comment]
Verified on 2.6.3-patch1-rc1
- Created a project with the resource quotas `CPU Limits`, `Memory limits`, `configmaps` set to the values 1000, 1000, 2
- Verified the quotas are updated in the namespace and the yaml the annotations are updated:

```
    field.cattle.io/resourceQuota: '{"limit":{"configMaps":"70","limitsCpu":"1000m","limitsMemory":"1000Mi"}}'
```
Verified by creating a workload in the namespace with the limits for CPU and memory set to 1001 and the deployment failed with the error 
```
Error creating: pods "test3-55fbf45ff8-jdf99" is forbidden: exceeded quota: default-skxr8, requested: limits.cpu=1001m, used: limits.cpu=1, limited: limits.cpu=1

```

**Comment by gisyrus** [comment]
For a more detailed issue and workaround here:
When I set a new Project `test-with-quota` with a new namespace `test` configured with resourceQuota and containerDefaultResourceLimit:
1. the containerDefaultResourcceLimit does not apply to `test`
![image](https://user-images.githubusercontent.com/44492082/150572426-cab935af-81d7-4c36-b350-7902139c38c4.png)
![image](https://user-images.githubusercontent.com/44492082/150572480-b6a205e9-b5d7-44e3-a7d5-d8a4776dc197.png)
![image](https://user-images.githubusercontent.com/44492082/150572598-c81e0d86-d134-44e1-b692-1648f8945c86.png)
![image](https://user-images.githubusercontent.com/44492082/150572643-a3bb6adc-1c9d-4251-b741-75adbaffc3bc.png)
2. Error will be generated in Rancher log:
```
2022/01/21 17:24:48 [ERROR] error syncing 'test': handler namespace-auth: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*), handler resourceQuotaSyncController: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)
```
3. As the above log seems weird, so I tried to figure out what happened and I examine the annotation of `test` and found out this:
![image](https://user-images.githubusercontent.com/44492082/150573092-a91acd7d-dc98-484a-a0eb-90e214359f7c.png)
It seems like the value for resourceQuota accidentally added a space for separating the unit and the number
So I went to check Rancher configuration for the project but there's no space in the config
```
...
  namespaceDefaultResourceQuota:
    limit:
      limitsCpu: 100m
      limitsMemory: 100Mi
      requestsCpu: 100m
      requestsMemory: 100Mi
  resourceQuota:
    limit:
      limitsCpu: 1000m
      limitsMemory: 1000Mi
      requestsCpu: 1000m
      requestsMemory: 1000Mi
    usedLimit:
      limitsCpu: 100m
      limitsMemory: 100Mi
      requestsCpu: 100m
      requestsMemory: 100Mi
...
```
4. Last and the most exciting part you would like to know is that I make my resourceQuota works with a workaround:
```
apiVersion: v1
kind: Namespace
metadata:
  name: test
  annotations:
    cattle.io/status: >-
      {"Conditions":[{"Type":"ResourceQuotaValidated","Status":"True","Message":"","LastUpdateTime":"2022-01-21T17:39:10Z"},{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2022-01-21T17:39:10Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2022-01-21T17:39:10Z"}]}
    field.cattle.io/containerDefaultResourceLimit: '{}'
    field.cattle.io/projectId: c-cbshr:p-vshjm
    field.cattle.io/resourceQuota: >-
      {"limit":{"limitsCpu":"100 m","limitsMemory":"100 Mi","requestsCpu":"100
      m","requestsMemory":"100 Mi"}}
    lifecycle.cattle.io/create.namespace-auth: 'true'
#    key: string
  creationTimestamp: '2022-01-21T17:17:58Z'
  finalizers:
    - controller.cattle.io/namespace-auth
#    - string
  labels:
    field.cattle.io/projectId: p-vshjm
#    key: string
  resourceVersion: '41255763'
  uid: c50a51e6-fcd9-4e35-883e-e40e1ffe007b
  fields:
    - test
    - Active
    - 21m
spec:
  finalizers:
    - kubernetes
#    - string
__clone: true
```
change `    field.cattle.io/resourceQuota: >-
      {"limit":{"limitsCpu":"100 m","limitsMemory":"100 Mi","requestsCpu":"100
      m","requestsMemory":"100 Mi"}}`
to `field.cattle.io/resourceQuota:{"limit":{"limitsCpu":"100m","limitsMemory":"100Mi","requestsCpu":"100m","requestsMemory":"100Mi"}}`
And then verify with the above comment 😄

**Comment by anupama2501** [comment]
@gisyrus Thank you a detailed description. @richard-cox provided a fix for the same and from my comment, I was able to validate that it works on the rancher version v2.6.3-patch1-rc1. 

More validations:

- Created a downstream rke1 cluster with 2 nodes 
- Created a project with the following resource quotas set:

<img width="400" alt="Screen Shot 2022-01-21 at 1 39 06 PM" src="https://user-images.githubusercontent.com/38144301/150616330-ebf43f0c-5579-4aaf-bda4-2378372963b5.png">
- Verified the quota limits were set on the namespaces as well 
<img width="400" alt="Screen Shot 2022-01-21 at 1 38 48 PM" src="https://user-images.githubusercontent.com/38144301/150616380-f4d9c406-e111-4474-8528-d5f43df723d7.png">

- Verified the set quotas are applied on the namespace by setting more than the required limits while creating a few workloads.
<img width="400" alt="2022-01-21_16-26-27" src="https://user-images.githubusercontent.com/38144301/150616556-f7eed1f2-b8f2-4742-aaf2-ebb80526ed1f.png">

**Comment by richard-cox** [comment]
Release notes should inform user that on upgrade any effected resources will need to be updated for the fix to apply.

**Comment by anupama2501** [comment]
@richard-cox I validated this by upgrading rancher from 2.6.3 to 2.6.3-patch1-rc2 on an HA server.

- I noticed that if a project with resource quotas set was created in 2.6.3 - Project1 and a namespace ns1 was added we hit this error 

```
2022/01/24 23:13:02 [ERROR] error syncing 'postupgns': handler namespace-auth: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*) handler resourceQuotaSyncController: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*
```

- This was the yaml set for the namespace
```

    field.cattle.io/resourceQuota: '{"limit":{"configMaps":"5 ","limitsCpu":"500 m","limitsMemory":"1023
      Mi","pods":"4 ","requestsCpu":"500 m"}}'
```

- Now, if we upgrade the rancher server to 2.6.3-patch1-rc2, and create a namespace in that same project, we still see the same error.
- if we add a new project with resource quota set post upgarde, and add a namespace with the resource quota, the error is not seen.
- This is not the case on a fresh installed 2.6.3-patch1-rc2 but seen only on an upgraded version of rancher from 2.6.3 --> 2.6.3-patch1-rc2

**Comment by richard-cox** [comment]
It looks like the error seen on upgrade is due to the namespace from pre-upgrade (with invalid limits) still existing. This causes other namespaces to fail syncing downstream causing the error log. I've updated the release notice to include instructions on how to resolve this (either remove the bad namespace, fix the limits in the namespace or remove the namespace from the project) - https://github.com/rancher/dashboard/issues/4804#issuecomment-1020231339

**Comment by anupama2501** [comment]
Verified on 2.6.3-patch1-rc2 upgraded from 2.6.3

The errors `2022/01/25 21:04:39 [ERROR] error syncing 'anupamatest': handler namespace-auth: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*), handler resourceQuotaSyncController: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*), requeuing`
can be eliminated for the new namespaces that were created post upgrade in the same project with :


**Workaround1:**

- Delete the namespace that was created pre rancher upgarde.
- In my setup, I deleted the namespaces that was created in 2.6.3 after upgrading the rancher server to 2.6.3-patch1-rc2 that had a regex issue for the resource limits set `field.cattle.io/resourceQuota: '{"limit":{"configMaps":"5","limitsCpu":"500m","limitsMemory":"1023Mi","pods":"5","requestsCpu":"500 m","requestsMemory":"1024Mi"}}'`
- By removing the namespace above, the errors seen for other namespaces that were created in that project post upgrade of rancher were resolved.


**Workaround2:**

- Edit the namespace that was created pre-rancher upgrade
- In my setup, edited the namespace that was created in 2.6.3 and by re-saving the values for the resource quotas, the original error where the resource quotas had an incorrect regex was resolved.
- The errors seen for the other namespaces created in the same project as the namespace above can be resolved as well.

**Comment by jtravee** [comment]
> ~Release notes should inform user that on upgrade any effected resources will need to be updated for the fix to apply.~
> 
> The following comment should accompany this issue in the release notes: `On upgrade any namespaces created with limits should either be deleted or edited again (which will correct the invalid limits). Failure to do so will result in limits failing to apply to all other namespaces in the same project.`
> 
> @btat What's the best way to ensure the above makes it into the release notes?

The best way is to just ensure the `release note` label is affixed to the issue (and the milestone set). Additionally, you may ping us on Slack to add things if need be (if last minute things come up). Thanks for checking!
