### ISSUE TITLE
[Backport] Pass migrated annotation for apps

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4812]
Backport of https://github.com/rancher/dashboard/issues/4402

**Comment by anupama2501** [comment]
Re-opening as the issue is seen with the dashboard UI with the following steps:


- Install rancher server on v2.5-head `9dab145`
- Create a downstream rke1 node driver cluster.
- From system charts, install the app AWS-event-sources, version 0.1.1 - app1 from ember UI
- Verify the workload gets active.
- Add helm3 repository in the apps & market -> repositories: **name**: helm3-library | **URL**: https://git.rancher.io/helm3-charts | **Branch**: master from vue UI
- From the downstream cluster's `launch kubectl` 

```
kubectl get apps -A | grep aws-event-resources
kubectl edit app aws-event-sources -n aws-event-sources
```

- add annotations under spec.chart.metadata.annotations

```
catalog.cattle.io/ui-source-repo: helm3-library
catalog.cattle.io/ui-source-repo-type: cluster
apps.cattle.io/migrated: "true"
```

- From the local cluster's `launch kubectl`

```
kubectl get apps.project.cattle.io -A | grep aws
kubectl edit  apps.project.cattle.io aws-event-sources -n p-mr57l<namespaceID of the app> and add the annotation at metadata.annotations
"cattle.io/skipUninstall": "true"
```

- Upgrading the app failed with the error:

```
Error: UPGRADE FAILED: cannot patch "aws-event-sources-controller" with kind Deployment: Deployment.apps "aws-event-sources-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"aws-event-sources", "app.kubernetes.io/name":"aws-event-sources"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Comment by gaktive** [comment]
UI to set up a session with QA to go over the repro on this.

**Comment by catherineluse** [comment]
I got it to send the annotation in the request properly, but even with the annotation, the app can't be upgraded because it gets stuck in a pending state. I get the console error

```
no chart version found for aws-event-sources-0.1.1
```
and the UI error
```
Cannot read properties of undefined (reading 'version')
```
It looks like upgrade still won't work because it sees no available versions. I wonder if we'll need to backport some more of the app migration changes from v2.6 to make this work.

**Comment by gaktive** [comment]
Internal reference: SURE-3366

**Comment by anupama2501** [comment]
Verified on v2.5-head 89ccfcf

Steps:

- From cluster --> default project --> apps, install the app AWS-event-sources, version 0.1.1 - app1 from ember UI
- Add helm3 repository in the apps & market -> repositories: name: helm3-library | URL: https://git.rancher.io/helm3-charts | Branch: master from vue UI
`kubectl get apps -A | grep aws-event-sources`
`kubectl edit app aws-event-sources -n aws-event-sources`
- add annotations under spec.chart.metadata.annotations
`catalog.cattle.io/ui-source-repo: helm3-library`
`catalog.cattle.io/ui-source-repo-type: cluster`
`apps.cattle.io/migrated: "true"`
- From the local cluster
`kubectl get apps.project.cattle.io -A | grep aws`
`kubectl edit  apps.project.cattle.io aws-event-sources -n p-mr57l<namespaceID of the app>` and add the annotation at metadata.annotations
` "cattle.io/skipUninstall": "true"`

**Verified test cases:**

1. Upgrading the app to a different version and the upgrade goes through without any error
2. Deleting the app works
3. Updating the app to the same version.




**However, on 2.5.12-rc1,** after changing the dashboard-index to point to release-2.5, I see an incorrect version of the app displayed in the apps & market --> Installed apps 
As shown in the screen shot the `upgradable` version should be v0.1.4 andn ot 0.1.9

### **Dashboard UI versions which are not in sync with the ember UI versions displayed for the app:**

<img width="600" alt="Screen Shot 2022-01-07 at 4 04 10 PM" src="https://user-images.githubusercontent.com/38144301/148622633-8dec9b1f-bf08-4c24-8228-39cad9b07b19.png">


<img width="600" alt="Screen Shot 2022-01-07 at 4 13 34 PM" src="https://user-images.githubusercontent.com/38144301/148622711-97cf0f0e-43b1-410a-a7d5-bf63eb9b08b6.png">



### **Ember UI versions:**



<img width="600" alt="Screen Shot 2022-01-07 at 4 04 21 PM" src="https://user-images.githubusercontent.com/38144301/148622744-9189399e-7dc0-485c-96f7-1e34a236a882.png">

**Comment by anupama2501** [comment]
Waiting for 2.5.12-rc2 to validate the ticket

**Comment by jtravee** [comment]
@rmweir please review the [release note](https://github.com/rancherlabs/release-notes/pull/210/files) for this one as it was a backport of [4402](https://github.com/rancher/dashboard/issues/4402). Ty!

**Comment by anupama2501** [comment]
Blocked by backend rancher/rancher#36120

**Comment by anupama2501** [comment]
Verified 2.5.12-rc4

Versions on the helm3 apps post migration after adding annotations and helm3 apps repository reflects the appropriate versions.
