### ISSUE TITLE
<Value not supported by UI, see YAML> error when copy/pasting key=value pairs

### ISSUE THREAD

**Issue by sebastien-helbert** [rancher/dashboard#4814]
**Setup**
- Rancher version: 2.6.2
- Browser type & version: Google Chrome

**Describe the bug**
Error <Value not supported by UI, see YAML> when copy/pasting  key=value pairs in config map, labels, annotations, etc.

**Expected Result**
Old UI behavior

**Screenshots**
![rancher-ui-issue](https://user-images.githubusercontent.com/6445261/147066858-e1769d55-f408-4d14-9f71-4936876aaa04.gif)

**Comment by richard-cox** [comment]
Thanks for submitting this issue. I've tested in the latest version 2.6.3 (released I think today) and this has been resolved, possibly via https://github.com/rancher/dashboard/pull/4491
