### ISSUE TITLE
Target latest node LTS

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#4820]
**Detailed Description**

Update from node 12 to latest lts version.

**Context**

There's only a few months of maintenance left on node 12. It might be a good idea to be proactive and target node 16 to iron out any potential issues that might arise before then.

**Comment by rak-phillip** [comment]
Looks like there's a potential issue with postCSS.. still investigating

https://github.com/postcss/postcss/issues/1455

**Comment by gaktive** [comment]
We should be on Node 16 at this stage so this ticket is no longer relevant.
