### ISSUE TITLE
Unable to specify port in Authorized Endpoint FQDN via Rancher UI

### ISSUE THREAD

**Issue by axeal** [rancher/dashboard#4827]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.4.5 instance with a single node custom cluster
2. Click Edit Cluster, enable Authorized Endpoint and attempt to enter a FQDN with a port specification, e.g. `kube.example.com:6443`
3. Click 'Save'

**Result:**

UI returns `"FQDN" contains an invalid character: :` error.

**Other details that may be helpful:**

Attempting to edit the cluster via the /v3 API, updating the localClusterAuthEndpoint to contain the FQDN with port is successful, and is reflected in the cluster kubeconfig, so this appears to be a UI validation issue only.

**Environment information**
- Verified in Rancher v2.4.5 and v2.3.6

gz#11759
gz#12864

**Comment by gaktive** [comment]
Internal reference: SURE-2504

**Comment by nwmac** [comment]
Strictly speaking, a FQDN does not contain port information - so we need to check the fields we have and whether port should be a separate input, or we rename the current input and make it clear what the user can enter.

**Comment by codyrancher** [comment]
@axeal the backend doesn't seem to provide any sort of validation so the fact that it accepts a port number doesn't imply a valid input. I was able to save input ranging from '4444' to 'ftp://hello.444444`. As @nwmac mentioned a port is not a valid part of the FQDN. Unless I'm missing something it looks like we should either have a backend change to make the fqdn a url or provide a port.

![image](https://user-images.githubusercontent.com/55104481/165094686-791865ad-3703-40ee-8836-64bf5ff10a36.png)
