### ISSUE TITLE
Changing replicas config on a helm deployed app will end up displaying "services "app_name" already exists"

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4829]
Internal reference: SURE-3018

Reported in 2.5.8 in Vue.

Issue description:
Changing replicas config on a helm deployed app with Cluster Explorer UI form will end up displaying "services "app_name" already exists"

Business impact:

Troubleshooting steps:

Repro steps:

- Provision a Rancher v2.5.8 instance
- Deploy an application via a Helm chart, or from Apps & Marketplace (e.g Memcached, HAproxy)
- Navigate to the Cluster Explorer UI, and click Edit Config
- Make a change to the workload configuration, i.e. scale the number of replicas or update the image and Save the changes

Actual behavior:
an error is displayed: `services "haproxy" already exists`

**Comment by nwmac** [comment]
@gaktive Neill and I sat down and could not reproduce this in 2.6.3. The steps above don't make sense - step 3 'Navigate to the Cluster Explorer UI, and click Edit Config' does not make sense.

We need the steps clarifying - what we did:

From Cluster Explorer:

- Go to Apps and Marketplace, chose the 'HA Proxy' chart and install it
- Wait for app to install
- Go to 'Deployments'
- Find the deployment for the HAProxy application - choose 'Edit Config' from the action menu
- Chance the replica count to 3
- Click Save
- User is taken back to Deployment list without any error message being shown.

**Comment by gaktive** [comment]
Asked original reporter for clarification on steps.

**Comment by sowmyav27** [comment]
**on 2.6.3 and 2.6.4-rc8**
From Cluster Explorer:

- Go to Apps and Marketplace, chose the 'HA Proxy' chart and install it
- Wait for app to install
- Go to 'Deployments'
- Find the deployment for the HAProxy application - choose 'Edit Config' from the action menu
- Chance the replica count to 3
- Click Save
- User is taken back to Deployment list without any error message being shown.

Was not able to reproduce any errors
