### ISSUE TITLE
Form elements incorrectly hidden in Continuous Delivery Git Repo create/edit form for http:// repository URL

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4830]
Internal reference: SURE-3564
Reported in 2.6.2

*Issue description:*
When a non-TLS Git Repository URL is entered into the Git Repo create/edit form of the Continuous Delivery UI, not only is the TLS Certificate Verification section hidden (as expected) but the Paths, Deploy To Labels and Annotations are also hidden incorrectly. The conditional display logic incorrectly wraps these sections as well as the TLS Certificate Verification section (https://github.com/rancher/dashboard/blob/v2.6.2/edit/fleet.cattle.io.gitrepo.vue#L394)

*Business impact:*
 Cannot use GitRepo form in Continuous Delivery UI to add a http: git repository

*Troubleshooting steps:*
 N/A

*Repro steps:*
 * Provision a Rancher v2.6.2 instance
 * Navigate to the Continous Delivery UI, Git Repos view and click Create
 * Enter http:// in the Repository URL field

*Workaround:*
 Is workaround available and implemented? Yes
 What is the workaround: Create gitrepo resource from manifest versus UI form

*Actual behavior:*
 All form sections below and including TLS Certificate Verification are hidden when entered Repository URL starts http:// i.e. Paths, Deploy To Labels and Annotations

*Expected behavior:*
 Only TLS Certificate Verification are hidden when entered Repository URL starts http://

**Comment by izaac** [comment]
This is no longer reproducible on Rancher `2.6.4-rc8` and `2.4.6-rc9`
