### ISSUE TITLE
Add back Pod selection checkboxes and delete button to workload views in Cluster Explorer

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4831]
Internal reference: SURE-3726

*Issue description:*
 In the Cluster Manager UI, when in the view for a workload (i.e. Deployment, DaemonSet etc). the list of Pods for the workload had checkboxes and a delete button allowing multi-select to delete Pods. This is not present in the Cluster Explorer UI.

There's one report that users rely heavily on Rancher UI and apparently made heavy use of deletion of Pods from within a workload view. They can delete multiple Pods via the Pods view, but adds the challenge of locating Pods in Namespace with many Pods and making sure not to delete Pods for other workloads by accident.

*Repro steps:*
 * Provision a Rancher v2.6.2 instance and custom cluster
 * Navigate to a workload, i.e. `coredns` in kube-system Namespace, observe lack of multi-select checkboxes and delete button
 * Navigate to the same workload in the Cluster Manager UI, observe mutli-select checkboxes and delete button

*Workaround:*
 Is workaround available and implemented? Yes
 What is the workaround: Select and delete multiple Pods for the workloads from the Pods view (being sure to delete Pods for the correct workload)

*Actual behavior:*
 No ability to select and delete multiple Pods within the view for a workload (i.e. Deployment, DaemonSet etc.)

*Expected behavior:*
Ability to select and delete multiple Pods within the view for a workload (i.e. Deployment, DaemonSet etc.)

**Comment by nwmac** [comment]
See below - the table does not show actions, hence no checkboxes:

![image](https://user-images.githubusercontent.com/1955897/151190851-c7398ec3-828a-4de0-aafd-3c65574750e6.png)

**Comment by nwmac** [comment]
@mantis-toboggan-md This should be just a case of setting `:table-actions="false"` to true in `detail/workload/index.vue` - I believe this used to have layout issues with the buttons overlapping things - but I don't believe it does this any longer, so we can re-enable - worth checking that it renders okay.

**Comment by sgapanovich** [comment]
Reproduced on 2.6.3
![repro263](https://user-images.githubusercontent.com/40282141/155344832-72118700-afe4-48ed-98b2-514105df28a9.jpg)

----------------

### Test Environment: ###
Rancher version: 2.6-head e55a04c
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver 
Downstream K8s version: v1.21.9+rke2r1

----------

### Testing: ###
1. Create a deployment 
2. Workloads -> Deployments -> click on the deployment you created 
3. At this point you are taken to the pod list page 

- checkboxes are present next to each pod
- checkbox to select all pods in the deployment is present 
- i can delete one/many pods by selecting them individually or by selecting them all
  - when pod(s) is deleted expected DELETE request is sent by UI `https://rancher_url/k8s/clusters/cluster_id/v1/pods/default/pod_id` per pod
- i can download yaml files for selected pods
  - when pod(s) yaml is downloaded expected GET request is sent by UI `https://rancher_url/k8s/clusters/cluster_id/v1/pods/default/pod_id` per pod

![pods](https://user-images.githubusercontent.com/40282141/155347163-4609789b-d7c8-46f1-b99e-aeda65514b5e.gif)



- the whole pod table is responsive: you can left click on the field to have it selected and right click to have options open
![responsive UI](https://user-images.githubusercontent.com/40282141/155347015-2d02376b-08f6-4498-9c68-952814610ebd.gif)
