### ISSUE TITLE
Project / Cluster Member with Project Monitoring role granted on System Project unable to view workload /node metrics tab in Explorer UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4835]
Internal reference: SURE-3718

Issue description:
A Project Member granted the View Monitoring role on the System Project of a cluster, is unable to view the Metrics tab for Pods running in their Project Namespaces. A Cluster Member granted the View Monitoring role on the System Project of a cluster, is similarly unable to view the Metrics tab for Nodes in the cluster. 

Business impact:
Users granted View Monitoring permission on System Project unable to view Metrics within Rancher dashboard UI, despite having required access to Grafana dashboards.

Troubleshooting steps:
N/A

Repro steps:

- Provision a Rancher v2.6.2 instance and a custom cluster
- Install rancher-monitoring chart into custom cluster in System Project
- Create a test user
- Grant test user the View Monitoring project role on System Project and validate test user can access the Monitoring view for the cluster and Grafana/Prometheus/Alertmanager UIs
- Grant the test user Project Member role on default project and deploy simple nginx deployment
- Observe the admin user can view the Metrics tab in the Pod view for running nginx pod, but test user cannot
- Grant the test user the Cluster member role on the cluster
- Observe the admin user can view the Metrics tab in the Node view for a node, but the test user cannot

Workaround:
Is workaround available and implemented? No

Actual behavior:
No Metrics tabs displayed for Pods/Nodes in Rancher Explorer UI for users who have required permissions to view Monitoring within the cluster

Expected behavior:
Metrics tabs displayed for Pods/Nodes where user has permission on the resource (Project/Cluster Member etc.) and also has been granted View Monitoring on the System Project into which rancher-monitoring is installed.

**Comment by gaktive** [comment]
Not sure how much QA has happened so far, but based on feedback from a user, I'm curious to know if QA sees this at all if testing on AKS & EKS:

> [It] happens for everyone, all roles. No CPU or Memory stats. Just displays 0%. We see this for AKS and EKS clusters actually. What's even weirder is when navigating into a cluster that says 0 on the homepage it will say things like 0.12% CPU which is just odd.

If an additional test issue is needed for that platform, let me know and I can file one.

**Comment by brudnak** [comment]
# My checks PASSED
  
## Reproduction Environment


| Component               | Version / Type                                      |
| ----------------------- | --------------------------------------------------- |
| Rancher version         | v2.6.2                                              |
| Rancher cluster type    | Helm high availability                              |
| Helm version            | v2.16.8-rancher1                                    |
| Downstream cluster type | [`"Custom"`, `"EKS"`, `"AKS"`]                      |
| Downstream K8s version  | [`"v1.21.9"`, `"v1.21.5-eks-bc4871b"`, `"v1.21.9"`] |
| Browser type            | Google Chrome                                       |
| Browser version         | 99.0.4844.51 (Official Build) (x86_64)              |

## Reproduction steps

1. Provision a Rancher v2.6.2 instance and a custom cluster

2. Install rancher-monitoring chart into custom cluster in System Project

3. Create a test user


4. Grant test user the View Monitoring project role on System Project and validate test user can access the Monitoring view for the cluster and Grafana/Prometheus/Alertmanager UIs

5. Grant the test user Project Member role on default project and deploy simple nginx deployment

6. Observe the admin user can view the Metrics tab in the Pod view for running nginx pod, but test user cannot

7. Grant the test user the Cluster member role on the cluster

8. Observe the admin user can view the Metrics tab in the Node view for a node, but the test user cannot
  
## Results

#### Actual
No Metrics tabs displayed for Pods/Nodes in Rancher Explorer UI for users who have required permissions to view Monitoring within the cluster

### Expected
Metrics tabs displayed for Pods/Nodes where user has permission on the resource (Project/Cluster Member etc.) and also has been granted View Monitoring on the System Project into which rancher-monitoring is installed.
  
<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6.4-rc8                                         |
| Rancher cluster type    | Helm high availability                             |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | [`"Custom"`, `"EKS"`, `"AKS"`]                     |
| Downstream K8s version  | [`"v1.23.4"`, `"1.21.5-eks-bc4871b"`, `"v1.23.3"`] |
| Browser type            | Google Chrome                                      |
| Browser version         | 99.0.4844.51 (Official Build) (x86_64)             |

## Validation steps

1. Provision a Rancher v2.6.4-rc8 instance and a custom cluster

2. Install rancher-monitoring chart into custom cluster in System Project

3. Create a test user


4. Grant test user the View Monitoring project role on System Project and validate test user can access the Monitoring view for the cluster and Grafana/Prometheus/Alertmanager UIs

5. Grant the test user Project Member role on default project and deploy simple nginx deployment

6. Grant the test user the Cluster member role on the cluster

  
### Results

#### Actual
Metrics tabs displayed for Pods/Nodes where user has permission on the resource (Project/Cluster Member etc.) and also has been granted View Monitoring on the System Project into which rancher-monitoring is installed.

### Expected
Metrics tabs displayed for Pods/Nodes where user has permission on the resource (Project/Cluster Member etc.) and also has been granted View Monitoring on the System Project into which rancher-monitoring is installed.

## Additional Test Cases

<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>Testing with AKS cluster</td>
            <td>
                <ol>
                    <li>Same steps as listed in validation above</li>
                </ol>
            </td>
            <td>Metrics to be visible for a user granted access to them</td>
            <td>Metrics were visible when using an AKS cluster</td>
            <td>:white_check_mark:</td>
        </tr>
        <tr>
            <td>Testing with EKS cluster</td>
            <td>
                <ol>
                    <li>Same steps as listed in validation above</li>
                </ol>
            </td>
            <td>Metrics to be visible for a user granted access to them</td>
            <td>Metrics were visible when using an AKS cluster</td>
            <td>:white_check_mark:</td>
        </tr>
    </tbody>
</table>
