### ISSUE TITLE
Init containers are not visible in the Cluster Explorer UI

### ISSUE THREAD

**Issue by leodotcloud** [rancher/dashboard#4840]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Create a pod using an init container.
- Or use one of the existing canal pods in the System project/kube-system namespace

**Result:**
- One can see/access the logs of the `install-cni` init container in the Cluster Manager UI.
- The same container is missing in the Cluster Explorer UI.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): Both

gz#14633

gz#17564

**Comment by gaktive** [comment]
Internal reference: SURE-2741, SURE-3021

**Comment by vincent99** [comment]
These are already in 2.6[.1+].

**Comment by richard-cox** [comment]
In the latest 2.6.4-bound code logs for init containers are available as per other containers in the log window containers drop down. 

![image](https://user-images.githubusercontent.com/18697775/148067906-27adade4-106a-48ed-9f36-f9ac581c6052.png)

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment

#### Not required.

>These are already in 2.6[.1+].

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-948355cc596b8466a77aec5276640425a5935852-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | RKE1 Linode                                        |
| Downstream K8s version  | v1.22.6-rancher1-1                                 |
| Browser type            | Firefox                                            |
| Browser version         | 96.0.3                                             |

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> `Cluster Management` -> `Explore` (next to downstream RKE1 cluster)
3. Click `Workload` -> `Pods` -> `Only System Namespaces` -> right click on `canal` pod in `kube-system` -> click `View Logs` -> `Containers` drop down list available

Logs for init containers are available as per other containers in the log window containers drop down.
