### ISSUE TITLE
When commissioning a GKE cluster, can not define the Network CIDR block if Master Authorized Network is enabled

### ISSUE THREAD

**Issue by Tejeev** [rancher/dashboard#4841]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
When commissioning a cluster it is best practice to enable Master Authorized Network, but when you set this you can not set a Master Authorized Network CIDR Block.

**Result:**
![image](https://user-images.githubusercontent.com/8906089/112012024-be214d80-8b20-11eb-908f-1f9447507167.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider/GKE
- Kubernetes: z1.17.15-gke.800

SURE-2870

**Comment by gaktive** [comment]
Internal reference: SURE-2870

**Comment by catherineluse** [comment]
I tried to reproduce this bug in `v2.6-head` but it looks like the error has already been fixed. When I go to provision a new GKE cluster and enable Master Authorized Network, the Network CIDR block is not disabled:

<img width="1103" alt="Screen Shot 2022-03-13 at 5 51 48 PM" src="https://user-images.githubusercontent.com/20599230/158087697-fa7504c1-34fd-4962-8126-1282520c8e32.png">
