### ISSUE TITLE
cronjob suspend failed

### ISSUE THREAD

**Issue by Allen-yan** [rancher/dashboard#4842]
**What kind of request is this bug:**

**Steps to reproduce (least amount of steps as possible):**

1. create a cronjob in rancher UI
2. REDEPLOY it
3. suspend it
4. refresh the UI , 

**Result:**
The cronjob is active and the  suspended icon disappeared ...

**Other details that may be helpful:**
The PUT request's response:
"CronJob.batch "update-b-asset-withdraw" is invalid: spec.jobTemplate.spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: "OnFailure", "Never"

REDEPLOY button update the cronjob's metadata restartPolicy to "Always" , but cronjob does not support it.
So when I suspend the job , failed

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher/rancher v2.3.4

gz#13569

**Comment by gaktive** [comment]
Internal reference: SURE-2605

Not sure what can be fixed here based on Vue and Ember, especially if 2.5.1+ resolves this. Need to investigate.

**Comment by nwmac** [comment]
Checking the code for 2.6.4, it looks like the dashboard does the right thing here.

**Comment by nwmac** [comment]
Verified on 2.6.4 in old UI - no longer an issue.

**Comment by maxsokolovsky** [comment]
Dev-validated in new UI of `2.6-head` (e4af246, close to`v2.6.4` release), could not reproduce the issue.

@Allen-yan, maybe I am missing something about CronJobs, but what does redeploying entail? If I modify its labels and even image, then the same cronjob still exists and isn't really redeployed, only its jobs and ultimately pods will be different when it's time to run another job.

**Comment by sowmyav27** [comment]
**On 2.6-head `c2d8e32`**

- Deployed a Cron JOb.
- Clicked on `Suspend`. `restartPolicy: "Never"` is sent in the request
- Refresh the UI, the Cron Job is still in suspended state.
