### ISSUE TITLE
Remove "Tech Preview" from Cluster Provisioning v2

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4852]
Prior to 2.6.4, Cluster Provisioning v2 was listed as Tech Preview in various places. We need to remove that.

**Comment by catherineluse** [comment]
A PR can be created now, but it should be a draft. it shouldn't be merged until feature complete

**Comment by Josh-Diamond** [comment]
## Ticket #4852 - Test Results

### With Docker and single node cluster (1 etcd, 1 control plane, 1 worker): 

### Reproduced on 2.6.3:
1. Fresh install of rancher 2.6-head
2. Selected “Create” a cluster
3. Selected “RKE2/K3s”
4. Reproduced - Tech Preview label is present

<img width="1240" alt="reproduced" src="https://user-images.githubusercontent.com/46494969/157080212-d707fe8c-5855-4261-865d-70a5e9374f40.png">



### Verified on v2.6-3df76e44dd658679e10a56da2e4525771eb850b8-head: 
1. Fresh install of rancher 2.6-head
2. Selected “Create” a cluster
3. Selected “RKE2/K3s”
4. Verified - Tech Preview label has been removed

<img width="1244" alt="Verified" src="https://user-images.githubusercontent.com/46494969/157080257-38648c27-92ff-4108-8a5d-a2ecdabc70cd.png">



### Upgraded from v2.6.3 >> v2.6-3df76e44dd658679e10a56da2e4525771eb850b8-head:
1. Fresh install of rancher 2.6.3
2. Upgraded rancher from 2.6.3 => 2.6-head
3. Selected “Create” a cluster
4. Selected “RKE2/K3s”
6. Verified - Tech Preview label has been removed

<img width="1248" alt="Upgrade:verified" src="https://user-images.githubusercontent.com/46494969/157080342-7cceaee9-5c5f-448a-b77d-3099636f7917.png">
