### ISSUE TITLE
Ember UI | v1 Monitoring | Memory Data does not appear on the cluster page when switching between clusters

### ISSUE THREAD

**Issue by sgapanovich** [rancher/dashboard#4854]
**Setup**
- Rancher version: v2.5-edf83d5f6d2041217f9e543743d69246fe18afa7-head  (confirmed on 2.5.11 to be present)
- Browser type & version: Chrome

**Describe the bug**

When switching between clusters with monitoring v1 installed the Memory Data does not show up on the cluster page

**To Reproduce**

you will need at least 2 cluster with v1 monitoring enabled
1. Create HA Rancher cluster with enough resources to install monitoring 
2. Install v1 monitoring into your rancher local cluster
3. Provision a node downstream cluster with enough resources to install monitoring 
4. Install v1 monitoring into your downstream cluster
5. Wait for monitoring to work
6. Start switching between clusters
  Global > select the cluster with monitoring > select another cluster

**Result**
you will see the Memory monitoring data is not showing up even though it's returned by  POST `v3/clustermonitorgraphs`

workaround: refresh the page

**Expected Result**

All monitoring data appear when a user navigates to a cluster

**Screenshots**

![bug (1)](https://user-images.githubusercontent.com/40282141/148139973-dc800c62-f438-462f-9ece-bfec84ec13fc.gif)

**Comment by gaktive** [comment]
@sgapanovich is this happening in Vue and 2.6.x? I don't think we'll be fixing anything else in outside of security updates after 2.5.12, so if things are all right in the newer UI, that's where we'd only look going forward.

**Comment by gaktive** [comment]
2.5.x is now EOL so closing as won't fix: https://www.suse.com/support/kb/doc/?id=000020631
