### ISSUE TITLE
Charts menu missing if a namespace is selected

### ISSUE THREAD

**Issue by xhejtman** [rancher/dashboard#4856]
**Setup**
- Rancher version: 2.6.3
- Browser type & version: chrome 97.0.4692.56 

**Describe the bug**

If there is selected namespace, Charts menu is missing and application cannot be deployed. 

**To Reproduce**

Select any user namespace. Try to find charts under apps & marketspace

**Result**
Charts is missing

**Expected Result**

Charts should be present.

**Screenshots**

If a namespace not selected:
![charts1](https://user-images.githubusercontent.com/22795052/148222634-3bec19c6-305c-4b9b-8216-09f349fa6dd7.png)
If a namespace is selected:
![charts2](https://user-images.githubusercontent.com/22795052/148222630-32021bcf-577f-4960-b3e9-729addec9022.png)

**Comment by nwmac** [comment]
Fixed in 2.6.5 - we no longer hide cluster-scoped side-nav items when a namespace is selected.

QA - can you validate this (I've added 2.6.7 milestone for this).

**Comment by brandonsuse** [comment]
@AndrewHoffmanQA please test this one when you have a sec. Pretty straightforward.

**Comment by nickwsuse** [comment]
`Verified on v2.6-head Commit ID: 988b8d1`

The Charts menu is present under all of the namespaces that are available in the clusters I set up.
