### ISSUE TITLE
Adding `Role` via the UI always errors with `"Name" is required`, despite providing one

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#4858]
**Setup**
- Rancher version: 2.6.2 / 2.6.3
- Browser type & version: Firefox 95.0.2

**Describe the bug**
Populating the `Name` field when creating a new `role` object type results in the UI presenting an error stating it is not set

**To Reproduce**
Log into Rancher -> Cluster Explorer -> Search Resources -> Role -> Create

**Result**
![image](https://user-images.githubusercontent.com/5892615/148292024-30ca3a2c-1bec-4376-92a6-fdf6ccb76646.png)

**Expected Result**
Object to be created with supplied input.

**Comment by sowmyav27** [comment]
On 2.6.3, reproduced the issue as mentioned [here](https://github.com/rancher/dashboard/issues/4858#issue-1094760450)

- Error seen in console:
```
impl.js:203 CreateEditView mixin failed to save:  ['"Name" is required', __ob__: Rt]0: "\"Name\" is required"length: 1__ob__: Rt {value: Array(1), dep: _t, vmCount: 0}[[Prototype]]: Array
(anonymous) @ impl.js:203
d @ runtime.js:45
(anonymous) @ runtime.js:274
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
d @ asyncToGenerator.js:29
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
save @ impl.js:150
Qt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Qt @ vue.runtime.esm.js:1854
t.$emit @ vue.runtime.esm.js:3888
click @ CruResource.vue?c29f:1
Qt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Qt @ vue.runtime.esm.js:1854
t.$emit @ vue.runtime.esm.js:3888
clicked @ AsyncButton.vue?f516:201
Qt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
c._wrapper @ vue.runtime.esm.js:6917
```

**Comment by nwmac** [comment]
@aalves08 Might be in at the deep-end on this one - but see how far you get.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `11a7451`**

- Deploy a cluster --> CLuster Explorer --> Roles --> Create
- Give in a name, add in details. Click on create
- User is able to create a role successfully.
