### ISSUE TITLE
Add user-configurable OS field for vSphere Machine Pools in v2prov

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/dashboard#4859]
As part of the Rancher 2.6 GA for v2prov, windows will now be supported for the vSphere node driver. This will require a new field in the machine pool UI that will display the OS as determined by Rancher (PR link coming soon) and also allow the user to manually override it if they feel it is incorrect. The two possible values should be `linux` and `windows`. 

There will be two PRs to rancher/machine and rancher/rancher that will add a new OS field to the machine pool spec and add logic for rancher to retrieve the OS of a vsphere object. With these changes, Rancher will return the OS for the object (VM, template, or library obj) that the end-user selects. The default (fall-back) will be linux in the case where a template does not have an OS set in vSphere.

This issue will be updated with new information once the relevant PRs are landed.

**Comment by gaktive** [comment]
@mantis-toboggan-md can you review this since this is tied to some other work you may be looking at?

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.

**Comment by slickwarren** [comment]
filed an issue here, which I will block this ticket on https://github.com/rancher/dashboard/issues/5452

**Comment by slickwarren** [comment]
tested on v2.6.4-rc12:
machine pools in vsphere rke2 node driver now has the option for the user to specify the OS. 
This feature appears to be working properly but there was a new bug found related to it. 
https://github.com/rancher/dashboard/issues/5508
