### ISSUE TITLE
Update Dashboard to point to latest 2.5.x

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4860]
QA saw that the ui-dashboard index on v2.5-head 9dab points to:
https://releases.rancher.com/dashboard/v2.5.8/index.html

It should be pointing to a different branch to get the latest fixes on v2.5-head rancher version.

![Screen Shot 2022-01-05 at 1.48.36 PM.png](https://zube.io/files/rancher/3e6ae6d89cf5b0daa4ed07303025e5e6-screen-shot-2022-01-05-at-1-48-36-pm.png)

**Comment by gaktive** [comment]
PR: https://github.com/rancher/rancher/pull/35959

**Comment by ronhorton** [comment]
Still seeing the 2.5.8 value in `2.5-head Commit ID edf83d5`
I see that the change was merged, but not showing in new install.
<img width="1234" alt="Screen Shot 2022-01-06 at 5 06 04 PM" src="https://user-images.githubusercontent.com/89212856/148459023-5c04c6de-aeac-4413-a2c6-6b4e189a22fe.png">

**Comment by ronhorton** [comment]
**PASS** Verified in `2.5-head commit ID 89ccfcf`

1. Installed 2.5-head
2. Clicked Settings
3. ui-dashboard-index is now pinned to 2.5-head

![Screen Shot 2022-01-07 at 11.03.25 AM.png](https://zube.io/files/rancher/05ada410924ba7c70f1c195abc56b9f3-screen-shot-2022-01-07-at-11-03-25-am.png)
