### ISSUE TITLE
"Deploy Workload" should print an error when creating namespace containing an underscore

### ISSUE THREAD

**Issue by stefanlasiewski** [rancher/dashboard#4861]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Head to the `Cluster` -> `Project` -> `Workloads` view. 
2. Click `Deploy`
3. Attempt to deploy a workload.
   * Name: test
   * Dock Image: Anything
   * Namespace: Select `Add to a new namespace`. For namespace, add something that contains an underscore, such as `namespace_test`
   * Hit `Launch`

**Result:**

Rancher will return a red error box at the bottom with no error:

![image](https://user-images.githubusercontent.com/142752/88213550-bb76fd00-cc0d-11ea-9bac-0276a2114b8a.png)

**Other details that may be helpful:**

If I create a namespace another way, Rancher warns me that underscores are not allowed in namespaces.

1. Head to the `Cluster` -> `Project` view (not workload)
2. Click `Add Namespace`
3.  Attempt to add a namespace
   * Name:  add something that contains an underscore, such as `namespace_test`
4. Hit `Create`

Rancher will print the error `"Name" contains an invalid character: _`

![image](https://user-images.githubusercontent.com/142752/88213831-1c063a00-cc0e-11ea-9c08-9ce3fc672e28.png)

**Environment information**
- Rancher version: v2.4.5
- Rancher User interface: v2.4.28
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMware VMs. Specs n/a
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:57:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

gz#14010

**Comment by gaktive** [comment]
Internal reference: SURE-2663

**Comment by catherineluse** [comment]
In the workload form, the namespace/name/description component often uses an "extra columns" property. These extra columns sometimes make it so there's not quite enough room to add another column when you click **Create Namespace.** So I have made some minor layout changes to make enough room for the create/select namespace component in this design https://github.com/rancher/dashboard/issues/2513#issuecomment-1011531598. 

The form for each workload type looks a little different, but I validated that the fields that change depending on the workload type (such as schedule, which should only be there for the cronjob form) are still present or absent as they should be.

# CronJob

When selecting a namespace:

<img width="1158" alt="Screen Shot 2022-01-12 at 5 31 05 PM" src="https://user-images.githubusercontent.com/20599230/149396152-67ca9c03-0974-4dbd-86ad-bc3336acc184.png">

When creating a namespace:
<img width="1146" alt="Screen Shot 2022-01-12 at 5 31 13 PM" src="https://user-images.githubusercontent.com/20599230/149396193-93cf6ba2-bda9-4d24-8587-5b8814098c77.png">

# DaemonSet

When selecting a namespace:
<img width="1151" alt="Screen Shot 2022-01-12 at 5 31 35 PM" src="https://user-images.githubusercontent.com/20599230/149396261-157387cb-77a1-4d2e-aae9-8bad262c59c1.png">

When creating a namespace:
<img width="1143" alt="Screen Shot 2022-01-12 at 5 31 44 PM" src="https://user-images.githubusercontent.com/20599230/149396319-43e9aa08-3d8c-40de-a720-94bd23399590.png">

# Deployment
When selecting a namespace: 
<img width="1151" alt="Screen Shot 2022-01-12 at 5 34 37 PM" src="https://user-images.githubusercontent.com/20599230/149396363-18badf66-0368-4a6c-a767-8d845a25713a.png">

When creating a namespace:
<img width="1179" alt="Screen Shot 2022-01-12 at 5 34 45 PM" src="https://user-images.githubusercontent.com/20599230/149396404-bf0b6b49-995d-40f0-a309-042e44601a1a.png">

# Job

When selecting a namespace:
<img width="1141" alt="Screen Shot 2022-01-12 at 5 35 10 PM" src="https://user-images.githubusercontent.com/20599230/149396501-10f1d676-3097-4191-a470-cee533f467c5.png">

When creating a namespace:
<img width="1160" alt="Screen Shot 2022-01-12 at 5 35 19 PM" src="https://user-images.githubusercontent.com/20599230/149396544-13e31206-7e9e-4463-9c26-025511b5191d.png">

# StatefulSet
When selecting a namespace:
<img width="1186" alt="Screen Shot 2022-01-12 at 5 35 52 PM" src="https://user-images.githubusercontent.com/20599230/149396601-1c303a4b-7c7d-4722-9bd9-209c2e7f4436.png">

When creating a namespace:
<img width="1148" alt="Screen Shot 2022-01-12 at 5 35 59 PM" src="https://user-images.githubusercontent.com/20599230/149396652-25992945-8b79-4983-bc00-e41193b12836.png">

**Comment by catherineluse** [comment]
changing widths per feedback from Lauren ![image](https://user-images.githubusercontent.com/20599230/149400830-1d9b88ea-b8bb-46e8-84b8-67cdd3630bac.png)

**Comment by catherineluse** [comment]
revised column widths
<img width="1264" alt="Screen Shot 2022-01-13 at 1 49 09 PM" src="https://user-images.githubusercontent.com/20599230/149407039-b0ec347a-5a24-4d44-8c8a-ed3221242d60.png">
<img width="1259" alt="Screen Shot 2022-01-13 at 1 49 00 PM" src="https://user-images.githubusercontent.com/20599230/149407031-0b6ac98d-a426-4c2c-a74f-9d14b9277eeb.png">

**Comment by catherineluse** [comment]
There are more validation rules that apply to this field than just the rule about underscores. However there is already a namespace name validator that can be reused - https://github.com/rancher/dashboard/pull/4921/files#diff-4158d37c72000f2405f7e8cbee74d4ba2ce8b9ec5894156c8e25ecf96547679eR3

**Comment by gaktive** [comment]
Let's make sure this works in Vue, rather than Ember, and we can notify impacted folks.

**Comment by gaktive** [comment]
Ember has a fix now in PR: https://github.com/rancher/ui/pull/4901

**Comment by slickwarren** [comment]
tested on v2.7-head (d1249b5c6907bd326e09ec79d9ac8d9c22782d0d) through vue and ember:
* create a namespace with `_` in the name through vue - error is thrown to user, resource is not created
* create a namespace with `_` in the name through ember - error is thrown to user, resource is not created
* create a workload + create a namespace with `_` in the name through vue - error is thrown to user, resources are not created
* create a workload + create a namespace with `_` in the name through ember - error is thrown to user, resources are not created
