### ISSUE TITLE
API Key Expired date doesn't shows right at the first time when login as standard user

### ISSUE THREAD

**Issue by xibuka** [rancher/dashboard#4863]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1) log in as a **standard** user. 
2) create a new API key with an expired date.
![image](https://user-images.githubusercontent.com/21263862/107881278-05675d80-6f27-11eb-8828-7a550b135557.png)
3) Close the token/pass page and go back to the API & Keys page

**Result:**
The `Expired` column shows `Never`
![image](https://user-images.githubusercontent.com/21263862/107881289-16b06a00-6f27-11eb-8719-a7c751bd95da.png)

**Other details that may be helpful:**

- After a page refresh, the `Expired` column shows right date.  

![image](https://user-images.githubusercontent.com/21263862/107881340-49f2f900-6f27-11eb-93f7-14a2cf5d9456.png)

- Admin users don't have this issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.13

- Installation option (single install/HA):
single docker install

gz#14905

**Comment by gaktive** [comment]
Internal reference: SURE-2768

**Comment by richard-cox** [comment]
Tagging relevant backend issue https://github.com/rancher/rancher/issues/31509

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.6.3                                  |
| Rancher cluster type    | Docker                                  |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | not applicable                          |
| Downstream K8s version  | not applicable                          |
| Browser type            | Firefox                                 |
| Browser version         | 96.0.3 (64-bit)                         |

## Reproduction steps

1. Logged in as a `Standard User`
2. Starting from the **default** Rancher homepage `/dashboard/home`
3. Click the user icon in the top right corner of the screen -> click `Account & API keys`
4. Click `Create API key` & fill out the form:
    - Description: `MY_TOKEN`
    - Scope: `No Scope`
    - Automatically expire: `A year from now`
    - Click `Create`
    - Click `Done` at the screen where token is displayed
5. Observe the row of information about the newly created API token

#### RESULT

Even though expiration was set for 1 year. The expiration date says `Expires`: `Never`

#### EXPECTED RESULT

For the correct expiration time to be displayed without refreshing the page

#### WORKAROUND

Refresh the page and the correct expiration countdown is displayed
  
<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-948355cc596b8466a77aec5276640425a5935852-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | not applicable                                     |
| Downstream K8s version  | not applicable                                     |
| Browser type            | Firefox                                            |
| Browser version         | 96.0.3 (64-bit)                                    |

## Validation steps

1. Logged in as a `Standard User`
2. Starting from the **default** Rancher homepage `/dashboard/home`
3. Click the user icon in the top right corner of the screen -> click `Account & API keys`
4. Click `Create API key` & fill out the form:
    - Description: `MY_TOKEN`
    - Scope: `No Scope`
    - Automatically expire: `A year from now`
    - Click `Create`
    - Click `Done` at the screen where token is displayed
5. Observe the row of information about the newly created API token

#### RESULT

The `Expires` column correctly display the tokens information without having to refresh the page
  
## Additional Info
