### ISSUE TITLE
vSphere Node Template CPU Max gets set to 32 even if made higher

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4865]
Internal reference: SURE-3102

Request description:
The UI for Node Templates in the VMWare vSphere driver caps the CPU core count to 32. If someone desires to use 48 and is able to edit the node template via API, but any other changes to the node template will reset the CPU core to 32.

Actual behavior:
Any value greater than 32 is changed back to 32.

Expected behavior:
To have the value entered is the value accepted.

Additional notes:
Max is set by: https://github.com/rancher/ui/blob/master/lib/nodes/addon/components/driver-vmwarevsphere/template.hbs#L163

**Comment by nwmac** [comment]
Trivial fix to remove the max attribute from the referenced file above.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.6.5-rc6

Created a vSphere node template with cpu core count set to 64. 
Saved template and change was reflected in the node templates list view. 
Edited node template and changed memory count, and saved. 
The cpu count was not changed.
