### ISSUE TITLE
User with Custom project role - "Manage Workloads" is not able to deploy workloads in Dashboard

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#4867]
**Setup**
- Rancher version: 2.6.3
- Browser type & version: Chrome

**Describe the bug**
User with Custom project role - "Manage Workloads" is not able to deploy workloads in Dashboard

**To Reproduce**

- As an admin Create a standard user `user1`
- Navigate to Cluster Explorer of a downstream cluster (RKE2 DO cluster)--> Projects --> Edit Config --> Add member --> Select `User1` and choose custom role. 
- Select `Manage Workloads` and click on Save
- Login as `User1`.
- Navigate to cluster explorer of the downstream --> Workloads --> Deployments
- Enter name and image name, and click on Create

**Result**
- Error in Rancher UI: `Unknown schema for type: service`
- Error in console:
```
impl.js:203 CreateEditView mixin failed to save:  Error: Unknown schema for type: service
    at Object.<anonymous> (getters.js:224)
    at actions.js:234
    at d (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.O.forEach.t.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
```

**Expected Result**
User with "Manage Workloads" should be able to deploy a workload. (In Ember UI on 2.6.3 Rancher this is possible)

**Comment by nwmac** [comment]
The issue here looks like we are trying to fetch services and the given user does not have permissions to view services. We should handle this and use an input box for the secret field rather than a select control

**Comment by maxsokolovsky** [comment]
Reproduced this under `v2.6.3-patch1`.

A related observation: I saw that the Create button was present for all workloads types, except Pods.
Is this normal? My user's role allowed to View and Manage Workloads. Jobs, DaemonSets and others did have the Create button, but Pods didn't. Why?
