### ISSUE TITLE
Handle long header/footer banners better

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/dashboard#4868]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Create a header/footer banner that exceeds the page width of Rancher

**Result:**
The banner is truncated at edge of the screen

**Other details that may be helpful:**
It may be preferable to truncate large banners, but expand them multi-line when moused over.

The following banner would exceed Rancher viewed at 100% scaling at 1920x1080:
```
{
  "banner": {
    "text": "START verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text verylong text END",
    "textColor": "white",
    "background": "red"
  },
  "showHeader": "true",
  "showFooter": "true"
}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.8

gz#12812

**Comment by nwmac** [comment]
This has been fixed in 2.6. 2.6.4 includes a tweak to show text ellipsis on banners when the content overflows.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `d4089da`**

The long banner is now seen as <text> .... But the long text is not seen
<img width="1680" alt="Screen Shot 2022-02-21 at 2 16 43 PM" src="https://user-images.githubusercontent.com/26032343/155032773-e3acc677-5a59-4cd8-a208-8c7d4048f500.png">

**Expected Result:**
the long text should be seen on the UI by expanding the banner

**Comment by nwmac** [comment]
This is as designed - we don't want banners to consume large amounts of vertical space - the text will be truncated with ellipsis - generally we do not expect users to be using overly large messages in the banner or footer.

**Comment by sowmyav27** [comment]
Closing as per [this](https://github.com/rancher/dashboard/issues/4868#issuecomment-1050263571) comment
