### ISSUE TITLE
Dashboard does not show the API endpoint URL in the API Keys page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4869]
In Cluster Manager, the API Keys page showed the API endpoint and allowed you to copy it to the clipboard.

The new UI does not offer the asme - we should add this in.

**Comment by gaktive** [comment]
Internal reference: SURE-3861

Docs: https://rancher.com/docs/rancher/v2.6/en/api/#how-to-use-the-api

Repro steps:

Navigate to Avatar
Click "Account and API keys"
API endpoint is not present in the UI , but doc says its present

**Comment by ansilh** [comment]
Submitted a PR in the doc with API URL.
Adding it here for backtracking.
https://github.com/rancher/docs/pull/3765
