### ISSUE TITLE
Update design of list bulk action drop down

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4875]
- Parent issue https://github.com/rancher/dashboard/issues/4168
- See screenshots from https://github.com/rancher/dashboard/pull/4874
- Button needs a bit of a refresh/some polish

**Comment by nwmac** [comment]
@richard-cox I think this is done and implemented?

**Comment by richard-cox** [comment]
@nwmac This one relates to the drop down button itself and if we want to update how it visually looks. Happy to bump if required

**Comment by gaktive** [comment]
For QA's benefit, #4168 already has the action work on this with the refinements, so this may be a duplicate.

**Comment by nwmac** [comment]
@richard-cox done
