### ISSUE TITLE
View log buttons on bottom are either cut off or missing when text in logs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#489]
Steps:
1.  Go to Pods
2. Show the cattle-system namespace
3. Select View Logs for one of those pods

results:  Since the log is full, you can't see the buttons on the bottom.  As more info goes it, the buttons slowly get cut off the bottom as well.
![image](https://user-images.githubusercontent.com/11514927/78814034-dbe2ba80-7982-11ea-9dd9-388348476a84.png)

**Comment by deniseschannon** [comment]
Design of View logs has changed so this issue isn't valid anymore.
