### ISSUE TITLE
GKE Maintenance Window configuration is in UTC, this is not clear from the UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4894]
Internal reference: SURE-3044

Issue description:
The maintenance window time  selection for a GKE cluster is in UTC per the Rancher documentation. The UI GKE configuration form does not call this out however.

Internal reference: SURE-3044

Business impact:
User can easily misconfigure maintenance window, by failing to note the selection is in UTC.

Troubleshooting steps:
N/A

Repro steps:
Provision a GKE cluster in Rancher v2.5.8 and select a maintenance window.

Actual behavior:
Observe from Google Cloud console that selection is configured in UTC, google cloud console will show in local timezone.

Expected behavior:
UI callout to inform user the time selection is in UTC.

**Comment by richard-cox** [comment]
@ronhorton The issue milestone has now moved to the 2.6.3 patch release so I'm moving out of QA until the works ported to the (very new) 2.6.3 patch branch

**Comment by richard-cox** [comment]
Fix is available using the ui `v2.6.3-patch1-rc1` release. Until there's an RC of Rancher this can be tested by
1. Bring up Rancher 2.6.3 and log in to the Dashboard
2. `Global Settings` --> `Advanced Settings`
  i.  Set `ui-index` to `https://releases.rancher.com/ui/v2.6.3-patch1-rc1/index.html`
  ii. Set `ui-offline-preferred` to `Remote`

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6.3-patch1-rc1` and `2.6.3` with global settings update

1. Cluster Management > Create
2. Create Hosted Cluster > GKE
3. Select Maintenance Window 
`UI callout to inform user the time selection is in UTC.`
Created gke cluster with no errors. 
<img width="661" alt="Screen Shot 2022-01-21 at 10 31 20 AM" src="https://user-images.githubusercontent.com/89212856/150557365-1a757300-1365-497f-998d-8b01481e95f5.png">
