### ISSUE TITLE
Add input for droplet tags on DigitalOcean rke2 clusters

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#4898]
_**Feature Request**_

**Description**
Add an input for Tags on a DigitalOcean Droplet when creating an rke2 cluster.

**Context**
We have the ability to add tags in the Ember UI for rke1 clusters, we should have the same ability for rke2 clusters.

Brought on by [this question](https://rancher-users.slack.com/archives/C3ASABBD1/p1639852674270600) in the Rancher Community Slack. 

PR: rancher/dashboard#4882

**Comment by ronhorton** [comment]
**PASS** Confirmed in `2.6-head Commit ID cd3c9d7`

1. create cluster
2. rke2
3. digital ocean

New Section on Machine Pools tab: Droplet Tags
<img width="1200" alt="Screen Shot 2022-01-12 at 5 05 29 PM" src="https://user-images.githubusercontent.com/89212856/149230849-ef353f44-9780-4a97-9ed9-8c797f5bd735.png">

Also created rke2 do cluster and verified that the tag entered in rancher shows in the do dashboard


<img width="386" alt="Screen Shot 2022-01-12 at 5 11 05 PM" src="https://user-images.githubusercontent.com/89212856/149231078-a6461766-939f-4624-8a05-d3ad7441c651.png">
