### ISSUE TITLE
Fix SortableTable ssr actions 

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#4899]
**Setup**
- Rancher version: 
Commit: rancher/dashboard#4874 
![version](https://user-images.githubusercontent.com/40806497/149009967-ad723fa9-aafd-4c59-9396-3c413026d70c.png)

- Browser type & version: Firefox - 91.4.0esr (64-bit)

**Describe the bug**
Encountering a `window is not defined` error with the SortableTable component.

```
 ERROR  [Vue warn]: Error in created hook: "ReferenceError: window is not defined"

found in

---> <SortableTable> at components/SortableTable/index.vue
```

**To Reproduce**
In a private browser window => Once logged in and at the Home page `/home`, refresh the page.

**Result**
Page fails to load with a `window is not defined` error.

**Expected Result**
Page should load normally with zero errors.

**Screenshots**
![home](https://user-images.githubusercontent.com/40806497/149011296-616fd37b-376c-4fe1-bc54-66498354690d.png)

**Comment by richard-cox** [comment]
@QA This can be processed alongside #4873 (see  https://github.com/rancher/dashboard/issues/4873#issuecomment-1010898042)
