### ISSUE TITLE
Backport 2.5 UI displays upgrade options from different catalog for OpenEBS 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4902]
Backport of https://github.com/rancher/dashboard/issues/4121 and this https://github.com/rancher/dashboard/issues/4676

Additional info: 
This is needed for the apps issue to work on 2.5.12-rc versions as mentioned in this comment https://github.com/rancher/dashboard/issues/4812#issuecomment-1007836287

**Comment by nwmac** [comment]
This is a backend issue - I have created https://github.com/rancher/rancher/issues/36120 for the backend team to look at.

**Comment by anupama2501** [comment]
This backport is not needed as the app versions are reflected from the same catalog by the fix provided from the backend issue linked above.
