### ISSUE TITLE
Info button that shows base64 encoded value for a CA certificate is needed while installing the Rancher Backups chart in the local cluster

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#4903]
**Rancher Server Setup**
- Rancher version: `v2.5.11` or `2.6.3`
- Installation option: Helm
   - If Helm Chart, Kubernetes Cluster and version: k3s HA local
- Proxy/Cert Details: `byo-valid` 

**Information about the Cluster**
- Kubernetes version: `v1.20.12+k3s1`
- Cluster Type (Local/Downstream):  `Local`

**User Information**
- What is the role of the user logged in? `Admin`

  
**Describe the bug**

When installing

**To Reproduce**

- Go to local cluster
- Go to Apps and Marketplace -> Rancher Backups
- Configure Chart 
- Select No default Storage Location
- Install
- Navigate to Rancher Backups in the context menu (Chart is now installed)
- Configure Chart with S3 compatible storage
- Enter all necessary information (including the Endpoint CA)

**Result**

open <REDACTED CERTIFICATE HERE>: file name too long

The certificate textbox is trying to use the certificate string as the filename.

**Expected Result**

S3 compatible backup enabled and chart is functional

**Comment by anupama2501** [comment]
Need an info button that reads a base64 encoded file next to the `Read from File` is required for more clarity for installing the rancher backup charts :

<img width="1238" alt="Screen Shot 2022-01-11 at 5 08 43 PM" src="https://user-images.githubusercontent.com/38144301/149046728-0562dd88-fca7-43c2-a8c6-8d4329df589d.png">

**Comment by jiaqiluo** [comment]
It will be even better if the UI can do the base64 encoding for the file automatically.

**Comment by ronhorton** [comment]
@nwilliams22 @nickwsuse functional in this context means that the s3 bucket is reachable and writeable. No errors when configuring.

**Comment by nickwsuse** [comment]
`Verified on v2.6-head commit ID: bda0897`

This one was a bit confusing, but after looking at the linked PR - https://github.com/rancher/dashboard/pull/5873 - it became clear that the change was for reading the Endpoint CA from a file. 

If you read the raw cert from a file we now base64 encode it automatically for the user. If you copy/paste it, you'll still get this error and you'll need to either encode it yourself or have it read from a file.
