### ISSUE TITLE
AWS Marketplace Integration - Support Config

### ISSUE THREAD

**Issue by samjustus** [rancher/dashboard#4916]
When the marketplace flag/setting (tbd) is flipped, then the following things should happen:

- [ ] Add a `Generate Support Config` button, which will hit a backend service and download the SCC Support Config file directly in the browser
- [ ] The Support Page should link to SCC (Suse Customer Center) with a special parameter to indicate it came from an AWS Marketplace enabled setup. e.g. add `?from_marketplace=1` to the URI
- [ ] The button for `Already have support?` should be removed.  `Find out more about SUSE Rancher support` text should also be removed 
- [ ] The theme and logo should change to green

**Comment by samjustus** [comment]
#35736

**Comment by samjustus** [comment]
https://github.com/rancher/rancher/issues/35736 = backend blocker

**Comment by cbron** [comment]
Bumped back one milestone.

**Comment by ryansann** [comment]
I will update this issue with further details as they become available

**Comment by ryansann** [comment]
Here are the instructions to deploy a version of the csp-adapter that can be used for testing the supportconfig functionality.

1. Clone [this repo](https://github.com/rancher/csp-adapter/tree/release/v2.6)
2. Checkout the `supportconfig-testing` branch
3. Run the command: `helm upgrade --install csp-adapter ./charts/rancher-csp-adapter --set rancherHostname=<host> --set image.repository=ryansann/rancher-csp-adapter --set image.tag=test-2` from the repository root
  - no `https://` in `rancherHostname`
  - this will be discovered from the `v3.Setting` but for now it's just a helm value
5. The `csp-adapter` service can be used to generate the supportconfig tar ball, via `GET /generate/supportconfig` which returns a response with the tarball containing the support config info.

**Comment by anupama2501** [comment]
@gaktive @mantis-toboggan-md @samjustus what is the setting mentioned in the comment https://github.com/rancher/dashboard/issues/4916#issue-1102039129:
```
When the marketplace flag/setting (tbd) is flipped, then the following things should happen:

```

**Comment by mantis-toboggan-md** [comment]
Per slack conversation with @MbolotSuse , the link to generate the config is now `/v1/generateSUSERancherSupportConfig`

**Comment by brudnak** [comment]
# :x: Reopened

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component               | Version / Type                                                                     |
| ----------------------- | ---------------------------------------------------------------------------------- |
| Rancher version         | v2.6-8b3919b99293fc8b0dc5fe7191ca5bec9609aadd-head                                 |
| Rancher commit link     | https://github.com/rancher/rancher/commit/8b3919b99293fc8b0dc5fe7191ca5bec9609aadd |
| Installation option     | `eksctl` eks local cluster (bring your own cluster)                                |
| local k8s cluster       | v1.22.9-eks-a64ea69                                                                |
| Cert Details            | let's encrypt                                                                      |
| Helm version            | v2.16.8-rancher1                                                                   |
| Downstream cluster type | rke1 linode                                                                        |
| Downstream K8s version  | v1.23.6-rancher1-1                                                                 |
| Logged in user role     | administrator                                                                      |
| Browser type            | google chrome                                                                      |
| Browser version         |                                                                                    |

**ADDITIONAL SETUP**

- eksctl install command:

```shell
eksctl create cluster \
  --name $YOUR_CLUSTER_NAME \
  --version 1.22 \
  --region us-east-2 \
  --nodegroup-name $YOUR_NODE_GROUP_NAME \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
```

- Helm commands for Rancher installation:
  
```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$YOUR_HOSTNAME \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$YOUR_EMAIL \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5 \
  --set rancherImageTag=v2.6-head \
  --set extraEnv\[0\].name="CATTLE_PROMETHEUS_METRICS" --set-string extraEnv\[0\].value=true
```



## Validation steps

1. Create an EKS cluster using `eksctl`
2. Install Rancher onto the cluster
3. Install the csp adapter
   1. Setup the required oidc provider & policy
   2. Have premium support license
4. Create a downstream linode cluster with 18 nodes
   - these 18 nodes plus the 3 nodes on the local cluster will take you out of compliance if only 1 license is held
   - this shows that the csp adapter and whole setup is working properly
5. Click the `hamburger menu` on the Rancher UI -> click `Get Support`
   - There is no `Generate Support Config` button as pictured here https://github.com/rancher/dashboard/pull/5767
   - You can see the csp adapter is working properly by the screen shot labeled `A1` below

## Additional Info

Vising the support config endpoint does generate a support config

- Putting this into the browser `https://<YOUR_RANCHER_URL>/v1/generateSUSERancherSupportConfig` does download the `supportconfig.tar`
- Bringing the cluster into compliance by removing 1 node from the downstream cluster still does not cause the missing button from the UI to become available, even when the cluster is in compliance
- `support_eligible` is set to `true` and the contents of the config are:
- The UI does not change to green

```json
{
  "compliance": {
    "message": "Rancher server required 2 licens(es) and was able to check out 1 licens(es)",
    "status": "NonCompliant"
  },
  "csp": {
    "acct_number": "<REDACTED>",
    "name": "aws"
  },
  "platform": "x86_64",
  "product": "<REDACTED>",
  "support_eligible": true
}
```

## RESULTS

#### :white_check_mark: Expected
Expected the `Generate Support Config` button as pictured here https://github.com/rancher/dashboard/pull/5767 to be present. Also expected the UI to change to the green theme 

#### :x:Actual
The is no `Generate Support Config` button and the UI didn't change to the green theme

![2022-06-16_12-47-30](https://user-images.githubusercontent.com/40877149/174152791-742749a3-13ab-4421-a9db-364d8571ceeb.png)

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component               | Version / Type                                                                     |
| ----------------------- | ---------------------------------------------------------------------------------- |
| Rancher version         | v2.6-bda0897a42ac77431383eb4a4bcd0454de056b98-head                                 |
| Rancher commit link     | https://github.com/rancher/rancher/commit/bda0897a42ac77431383eb4a4bcd0454de056b98 |
| Installation option     | `eksctl` eks local cluster (bring your own cluster)                                |
| local k8s cluster       | v1.22.10-eks-84b4fe6                                                               |
| Cert Details            | let's encrypt                                                                      |
| Helm version            | v2.16.8-rancher2                                                                   |
| Downstream cluster type | rke1 linode                                                                        |
| Downstream K8s version  | v1.23.6-rancher1-1                                                                 |
| Logged in user role     | administrator                                                                      |
| Browser type            | google chrome                                                                      |
| Browser version         | 102.0.5005.115 (Official Build) (x86_64)                                           |


## Validation steps

1. Create an EKS cluster using `eksctl`
2. Install Rancher onto the cluster
3. Install the csp adapter
   1. Setup the required oidc provider & policy
   2. Have premium support license
4. Click the `hamburger menu` on the Rancher UI -> click `Get Support`
5. Click `Generate Support Config`

  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
The `Generate Support Config` button should download a valid support config

#### :white_check_mark:Actual
The `Generate Support Config` button downloaded a valid support config
