### ISSUE TITLE
Remove Experimental label for Harvester

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4919]
Catherine has a PR with a screenshot: https://github.com/rancher/dashboard/pull/4910

**Comment by catherineluse** [comment]
Note: Harvester provisioning will no longer be experimental, but external Harvester support will still be experimental. https://github.com/rancher/dashboard/pull/4910#issuecomment-1012662696

**Comment by gaktive** [comment]
A request came in to get this in sooner. I'll put this back into Working to look at the new branch.

**Comment by richard-cox** [comment]
Fix is available using the ui `v2.6.3-patch1-rc2` release. Until there's an RC of Rancher this can be tested by
1. Bring up Rancher 2.6.3 and log in to the Dashboard
2. `Global Settings` --> `Advanced Settings`
  i.  Set `ui-index` to `https://releases.rancher.com/ui/2.6.3-patch1-rc2/index.html`
  ii. Set `ui-offline-preferred` to `Remote`
3. Refresh the browser

**Comment by anupama2501** [comment]
Re-opening the issue on 2.6.3-patch1-rc1

The tag `Experimental` is removed for Harvester but we should have a tag `Tech Preview` for harvester similar to other node drivers as RKE2 is not GA yet.

<img width="500" alt="2022-01-21_10-33-01" src="https://user-images.githubusercontent.com/38144301/150583132-91eeb7d0-918b-4487-a3b1-f8e92285d578.png">

**Comment by richard-cox** [comment]
I've recreated `v2.6.3-patch1-rc2` to contain the updated fix from #4972 and it can be tested the same was as https://github.com/rancher/dashboard/issues/4919#issuecomment-1018717847

**Comment by anupama2501** [comment]
Verified on 2.6.3-patch1-rc2, `tech Preview` label is displayed on the UI for harvester for rke2
<img width="200" alt="Screen Shot 2022-01-24 at 2 16 58 PM" src="https://user-images.githubusercontent.com/38144301/150874295-44b99822-419b-4600-8ef0-c173d2bbe245.png">
