### ISSUE TITLE
On change event Nodes page show all nodes from all clusters

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#492]
Steps:
1.  Create two RKE clusters
2. Go to Dashboard/Node page
3. Wait until change event fires

Before change event:
![image](https://user-images.githubusercontent.com/11514927/78824110-ae057200-7992-11ea-8b67-894c6ad5e968.png)

After Change event:
![image](https://user-images.githubusercontent.com/11514927/78824079-a1811980-7992-11ea-86b2-60ddd8d12c09.png)

**Comment by codyrancher** [comment]
I haven't been able to reproduce. I don't think this issue is occurring any longer. Moving to test.

**Comment by vincent99** [comment]
This was coming from change events on the server side, so nothing you can do about it from the ui.  We think it involves changing what cluster you're looking at and something ont getting closed on the backend, so it's probably not reproducible with just one cluster.

**Comment by codyrancher** [comment]
I tried the following:
* used four clusters
* switched between the clusters using the dropdown (this actually caused the app to get stuck on loading)
* created the clusters while being on the page
* created the clusters and then refreshed the page.

**Comment by deniseschannon** [comment]
@tfiduccia can you see if you can reproduce this issue?

**Comment by tfiduccia** [comment]
Can't reproduce.
