### ISSUE TITLE
Incorrectly parsing Prometheus 'Duration' in Prometheus Rule Group

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4924]
2.5.12 back port rancher/dashboard#4851

**Comment by slickwarren** [comment]
on 2.5-head (1bb0d06): 
* install monitoring v2 on a cluster
* create a new prometheus rule
  * edit as yaml and update `interval` to one of the options for duration (i.e. ms, m, d, y)
* observe the rule once created in the UI

result: 
durations are working as expected -- i.e. 1 minute is converted to 60 seconds
(tested with ms, m, h, d, y)
<img width="190" alt="Screen Shot 2022-01-18 at 10 19 45 AM" src="https://user-images.githubusercontent.com/16691014/149996968-ccd5309d-fa31-4512-8937-201193f7f8b0.png">
