### ISSUE TITLE
Fleet: Show clusters applicable to a git repo

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4929]
**Detailed Description**
- When a git repo is created and it doesn't apply to any clusters the detail page can show misleading information
  - Number of 'ready' resources yet no actual resources
- On the git repo detail page we should list clusters that the repo applies to
  - Discussion: We should also maybe show a warning somewhere when a repo doesn't apply to any?

**Context**
- See https://rancher-users.slack.com/archives/C013SSBKB6U/p1642328781051100 conversation for source

**Comment by nwmac** [comment]
![image](https://user-images.githubusercontent.com/1955897/152508774-1b92cc40-f6c4-42a1-a0c1-fe64f6e93283.png)

(See clusters ready column)

**Comment by nwmac** [comment]
Currently looks like this when you target a group that does not have any matching clusters:

![image](https://user-images.githubusercontent.com/1955897/152509450-8cee07c1-315a-446a-81f9-3aa875f16add.png)

Task is to update the 'Clusters Ready' column so that when it is a Group, it shows the number of clusters in the group as well - e.g. 0/0 - when the number in the group is 0, it also shows a waring icon with a hover tooltip 'There are no clusters in this Cluster Group'

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required. Issue is well understood and reproduced recently. Before the change the total clusters ready was not show and there was no ! icon showing an issue.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `` pulled on 2/24/2022
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2
Downstream K8s version: v1.21.9+rke2r1
 
**Validation steps:**

1. Create a GitRepo on the Continuous Delivery page (left nav bar). I just used fleet-examples (https://github.com/rancher/fleet-examples.git is the Repo URL) and set the path to `/single-cluster/helm`. In the dropdown for "Deploy To", pick "No Clusters". Submit.
2. Notice the new changes as pictured below. We now see the total count of clusters targeted. We also see a warning icon when deploys to zero clusters (none targeted). This is basically the change (see the PR for details).
 
![image](https://user-images.githubusercontent.com/45179589/155760440-c4e9274a-b76a-4329-b2a6-6571677624d7.png)

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
