### ISSUE TITLE
Need a way to add/remove nodes on node page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#493]
Steps:
1.  Create RKE cluster with all three types of roles
2.  Go to Dashboard
3.  Go to Node page

Results:
There is no way to add/remove nodes to a specific role.  Here is an example of how we did it in previous UI
![image](https://user-images.githubusercontent.com/11514927/78827296-b8763a80-7997-11ea-99fa-cfc30872aadd.png)

**Comment by nwmac** [comment]
@mantis-toboggan-md We don't have a node pools view in Dashboard - so I think this needs to be added as a tab to the cluster view in Cluster Management.

May only make sense for RKE1 clusters - but we should add it and fetch the node pools for the cluster and present them in the same way we do in Cluster Manager - this is then the logical place to allow a node pool to be scaled up/down

**Comment by sowmyav27** [comment]
**On master-head commit id: `e546ffe`**

- Scale down and Scale up actions are available for RKE1 and DO RKE2 clusters - `Scale Down Pool` and `Scale Up Pool`
<img width="1664" alt="Screen Shot 2021-06-30 at 9 51 15 AM" src="https://user-images.githubusercontent.com/26032343/124000874-e541b380-d988-11eb-85ea-19fefda0627c.png">

- Scale down and scale up works.
- Scale down option on selecting a node is not available (available in Ember UI) logging a separate issue to track this - https://github.com/rancher/dashboard/issues/3366
