### ISSUE TITLE
UX Design for Fleet for 2.6.4

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4935]
UX Designs for the updates to Fleet in 2.6.4

**Comment by nwmac** [comment]
@MKlimuszka why did you close this - it's a UX design issue that has not been done. It was not in the to test column in Zube.

**Comment by MKlimuszka** [comment]
@nwmac  I don't think we have UX updates for Fleet in 2.6.4, do we?

**Comment by nwmac** [comment]
Yes we do

**Comment by MKlimuszka** [comment]
I'm sorry, there was a part of the product / PRD process I didn't understand. I talked it over with Gary and now I understand.

**Comment by gaktive** [comment]
Various tickets in flight already with Alex & Shavin. There's an additional ticket for 2.6.5 work.
