### ISSUE TITLE
[2.5 backport] Can't upgrade an app launched in Ember 2.5.x

### ISSUE THREAD

**Issue by cbron** [rancher/dashboard#4947]
https://github.com/rancher/dashboard/issues/4708

**Comment by MSpencer87** [comment]
**_Verified on 2.5.13-rc2_**

Upgrades completed via Ember UI without issue on 2.5.13-rc2
![Screen Shot 2022-04-13 at 5 04 19 PM](https://user-images.githubusercontent.com/6477538/163321625-ed200a52-08fd-4166-930c-f3a248799277.png)
