### ISSUE TITLE
CONFIGURATION -> Global Settings menu item missing for Restricted Admins users

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4954]
Internal reference: SURE-3906

*Issue description:*

Restricted Admin users are unable to see the Global Settings menu item under CONFIGURATION

*Business impact:*

Customers using Hosted Rancher cannot view global settings in the UI

*Troubleshooting steps:*
none

*Repro steps:*
 * Create a restricted admin user.
 * Log in as the restricted admin user.
 * Click the menu icon in the top left corner

*Workaround:*
 Is workaround available and implemented? 
- yes
 What is the workaround: 
- You can navigate directly to the URL, for example https://support.rancher.cloud/dashboard/c/c-p24tr/settings/management.cattle.io.setting

*Actual behavior:*

Global Settings menu is missing from UI for restricted admin users.

*Expected behavior:*

Global Settings menu should be available for restricted admin users. See also [https://rancher.com/docs/rancher/v2.6/en/admin-settings/rbac/global-permissions/] (Under Settings, Restricted Admin should be able to list, but not edit, settings)

**Comment by richard-cox** [comment]
For RAs the `settings` product visibility is blocked by `ifHaveVerb:          'PUT'`. Brought in via https://github.com/rancher/dashboard/pull/3943 due to https://github.com/rancher/dashboard/issues/3416#issuecomment-901520970

**Comment by catherineluse** [comment]
Should this be in the v2.6.4 release notes under known issues?

**Comment by nwmac** [comment]
The simple fix is to remove this line:

```
 ifHaveVerb:          'PUT',
```
from `config/product/settings.js`.

This does mean though that regular users can view the settings - there is no way to tell a restricted admin from a standard user - both have permissions to read settings.

If we do this, we need to update the pages in settings (branding, banners) to disable the apply button if the user does not have PUT permission - they can't actually update anything - they'll get an error saying PURT not allowed - so we should disable the button in the first place.

Also on the banners page, the new login message setting is editable when where it should not be in this case - the rest of the fields are correctly read-only.

**Comment by richard-cox** [comment]
// get user id (if not cached somewhere in core store
      const users = await this.$store.dispatch('rancher/findAll', {
        type: NORMAN.USER,
        opt:  { url: '/v3/users', filter: { me: true } }
      });
      const user = users?.[0];

// if can list, find matching bindings, check for 'restricted-admin'
v1/management.cattle.io.globalrolebindings

**Comment by MbolotSuse** [comment]
@richard-cox I'm just a backend engineer, but I would not recommend changing the UI based on the names of roles that a user has. 

Doing this has two issues:
1) This strategy will prevent customers from building a role which grants button visibility.
2) If a user has access to the restricted admin as a result of group membership (i.e. user1 is in group1, and group1 are restricted admins), then I believe that your above code will fail. Finding out if the user has permission as result of group membership is a larger task that currently doesn't have an easily accessible backend endpoint.

I'm actually partial to the solution that @nwmac described in https://github.com/rancher/dashboard/issues/4954#issuecomment-1095214359 (just control visibility based on the permission to read settings and fix a separate bug that lets you only see edit buttons on the settings if you can actually edit the settings), but I'm not sure on the requirements here (and why the Restricted admin would function differently than the standard user with regard to this button).

**Comment by richard-cox** [comment]
Ok, thanks for the input @MbolotSuse .

I think the improvement we're aiming for here is to obfuscate/hide settings that admins/restricted admins are fine to see but we'd like to avoid confusing users with (I think pretty much everyone has GET  on settings  / feature flags). Guess the correct way would be to remove those rights from those under restricted admin but that could have a big knock-on effect.

The fallback is as Neil described, show the settings to everyone with GET permissions but visibility of buttons on PUT

**Comment by sowmyav27** [comment]
**On 2.6.4**

- As admin create a restricted admin user
- login as restricted admin user
- User has no access to `Global Settings`.

**On 2.6head commit id: `7db4fe4`**
- As admin create a restricted admin user and a std user
- login as restricted admin user
- User has access to `Global Settings`.
- This user _cannot_ edit any settings. Can only view the settings.
- Login as the admin. 
- Admin user is able to view and edit settings on the `Global Settings` page
- Login as std user.
- User has access to `Global Settings`.
- This user _cannot_ edit any settings. Can only view the settings.
