### ISSUE TITLE
Create Namespace form in Cluster Explorer UI does not contain a Project by default

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4955]
Internal reference: SURE-2913
Reported in 2.5.7

Issue description:

The Project field within the Create Namespace form in the Cluster Explorer UI is blank by default, enabling an un-privileged user to easily create a Namespace outside of a Project which they are then unable to view

Business impact:

User can easily create a Namespace outside of a Project and is unable to view it afterwards

Repro steps:

Navigate to the Namespace view in the Cluster Explorer UI and click 'Create' (dashboard/c/<cluster_id>/explorer/namespace/create)
Specify a name for the namespace and click create

Actual behavior:

Project field is blank, and Namespace is created outside of any Project

Expected behavior:

The Project field is populated with a 'default' Project upon which the user has access or is a mandatory field. Whilst is would still be possible to create a Namespace outside of a Project via the Kubernetes API/kubectl, customer does not expect this behavior via the Rancher UI, which is Project aware. In Cluster Manager UI, 'Add Namespace' button is nested under a Project, and that Project is selected in the form by default.

**Comment by gaktive** [comment]
We may have to compromise and just provide an info box to tell them what would happen if a project is not specified.

**Comment by nwmac** [comment]
This is actually fixed in 2.6.3 - we now have the Projects/Namespaces view - you can still create a namespace not in a project - but this is a deliberate choice the users makes on the list view.

**Comment by sowmyav27** [comment]
**In 2.6.3**
<img width="1447" alt="Screen Shot 2022-03-07 at 7 15 19 AM" src="https://user-images.githubusercontent.com/26032343/156953888-43123a27-ef4f-4032-93b3-8e47152cbdfe.png">
<img width="1449" alt="Screen Shot 2022-03-07 at 7 15 27 AM" src="https://user-images.githubusercontent.com/26032343/156953893-e8374ac5-942b-48e6-891f-cdb356484c28.png">

Able to create a namespace in no project. User is able to view this namespace.
