### ISSUE TITLE
Amazon EKS not showing stats

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4956]
Internal reference: SURE-3367

Issue description:
User upgraded to 2.6.0 and the Amazon EKS cluster isn't showing nodes stats when other clusters are still showing

Business impact:
User can still use the cluster, but it will be great if it can be looked

**Comment by Josh-Diamond** [comment]
Ticket #4956 - Test Results
---

With Docker on a single-node instance:

Reproduced on rancher `v2.6.0` - ✅ Monday October 3, 2022
- Deploy EKS on `v2.5.16`, then  upgrade to `v2.6.0`

Verified on rancher `v2.7-0de241ce33201224d9bcdfba02ccf69bda45a04b-head`
- Reproduce on `v2.6.0`, then upgrade to `v2.7-head`

---

Reproduced on rancher `v2.6.0`:
1.  Fresh install of rancher `v2.5.16`
2. Provision a downstream EKS cluster
3. Once `Active`, upgrade rancher server to `v2.6.0`
4. Reproduced - EKS `Cluster Explorer > Nodes` does not show RAM or CPU stats

Screenshots:

`Step 4 - Nodes`
<img width="390" alt="nodes-260-reproduced" src="https://user-images.githubusercontent.com/46494969/193657438-8807b18c-8078-4672-acbf-a481b41bc39b.png">

`Step 4 - Node Details`
<img width="1269" alt="node-details-260-repro" src="https://user-images.githubusercontent.com/46494969/193657479-c195612f-585c-46b2-8527-be82e306fcd1.png">

---

Verified on rancher `v2.7-0de241ce33201224d9bcdfba02ccf69bda45a04b-head`:
1. Follow steps above to reproduce issue in `v2.6.0`
2. Upgrade rancher server to `v2.7-head`
3. Verified - EKS stats accurately displayed from `Cluster Explorer > Nodes` and `Cluster Explorer > Nodes > Node Details`

Screenshots:

`Step 3 - Nodes`
<img width="455" alt="Screen Shot 2022-10-03 at 12 18 26 PM" src="https://user-images.githubusercontent.com/46494969/193660563-0f61e8ef-5f4b-4b48-a4ff-bd6806d714d8.png">

`Step 3 - Node Details`
<img width="1273" alt="Screen Shot 2022-10-03 at 12 20 04 PM" src="https://user-images.githubusercontent.com/46494969/193660662-54c60af6-61c4-470e-8110-f20629b3bc07.png">
