### ISSUE TITLE
Default value of "Project Network Isolation" not selected when creating cluster from RKE template.

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4957]
Internal reference: SURE-3491
Reported in 2.5.9 so we should verify what's going on in 2.6.x

Issue description:

Let's create a template with a project's Network Isolation button changeable and defaults to Enabled, and create a cluster using this template. When I try to create a cluster using this template, the project's Network Isolation radio button is displayed with neither Enable nor Disable selected. Also, when I reload, it is not selected.

If you set it and then reload, it becomes indeterminate even if Enable is set in the template (even after setting it to Enable, it seems to become Disable or neither is selected). If I select a network provider other than Canal and then change it back to Canal, the radio button is set to Disable.

Business impact:
N/A

Troubleshooting steps:
N/A

Repro steps:
- create an RKE template and make `Project Network Isolation` can be overridden.
- confirm the default value is set to `true`, which means `Enabled`
- create a new cluster by using the template.

Workaround:
Is workaround available and implemented? no

Actual behavior:
None of the 2 options is selected.

Expected behavior:
The default one `Enable` should be selected.

**Comment by catherineluse** [comment]
This bug may have been fixed by https://github.com/rancher/dashboard/pull/5433

**Comment by nwmac** [comment]
Validate if already fixed

**Comment by aalves08** [comment]
@catherineluse had some spare time a looked at board a saw this issue... Let me know if my tests help verify that everything is working fine 🙏 

**RKE2**
_create_
![Screenshot 2022-03-30 at 15.03.52.png](https://zube.io/files/rancher/c93fc670c7b166c82a92635d8a725869-screenshot-2022-03-30-at-15-03-52.png)

_after creation_
![Screenshot 2022-03-30 at 15.11.04.png](https://zube.io/files/rancher/34909007889d58252118a3219b54e45a-screenshot-2022-03-30-at-15-11-04.png)

**RKE1**
_create (default is disabled, not indeterminate)_
![Screenshot 2022-03-30 at 15.14.12.png](https://zube.io/files/rancher/e18bca85328e1f686b43064f7a910f88-screenshot-2022-03-30-at-15-14-12.png)

_after creation_
![Screenshot 2022-03-30 at 15.21.17.png](https://zube.io/files/rancher/91e23d8d44dfd432676e359fbea9d02f-screenshot-2022-03-30-at-15-21-17.png)

**Comment by slickwarren** [comment]
tested on v2.6-head (851ff2f):
* create an rke1 template with override enabled for PNI, and PNI enabled by default
* use the template to create an rke1 cluster
  * (see screenshot) template values are read correctly, override is enabled and `enabled` is selected by default for user
* cluster is able to create with PNI reflecting value selected by the template/overridden by user. 
<img width="1077" alt="Screen Shot 2022-04-11 at 12 17 47 PM" src="https://user-images.githubusercontent.com/16691014/162813792-c296709a-da64-4333-b0b9-a2b07f54b759.png">
