### ISSUE TITLE
[ui] default value of "Docker version on nodes" is not selected when create cluster from RKE template.

### ISSUE THREAD

**Issue by xibuka** [rancher/dashboard#4958]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create an RKE template and allow the user to override `Docker version on nodes`
![image](https://user-images.githubusercontent.com/21263862/111417216-b92b5b00-8728-11eb-90ec-f1d80bcc1281.png)
2. confirm the default value is setting to `true`
![image](https://user-images.githubusercontent.com/21263862/111417175-a9ac1200-8728-11eb-8dd6-4b5a720c5a5b.png)
3. create a new cluster by using the template. 

**Result:**
None of the 2 options is selected.
![image](https://user-images.githubusercontent.com/21263862/111417391-1e7f4c00-8729-11eb-8be1-77fea7afb680.png)
I expected the default one should be selected.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.10 and 2.4.15
- Installation option (single install): Docker single install

**Cluster information**
The issue is happened before creating the cluster. 
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): N/A
- Machine type (cloud/VM/metal) and specifications (CPU/memory): N/A
- Kubernetes version (use `kubectl version`): N/A
- Docker version (use `docker version`): N/A

gz#15627

**Comment by gaktive** [comment]
Internal reference: SURE-3517

**Comment by nwmac** [comment]
Tested in 2.6.5 and this is no longer an issue

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head bca5ada
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 101.0.4951.67

----------

### Testing: ###

Tested this issue with the following steps:
1. Create an RKE template and allow the user to override `Docker version on nodes`
2. Confirm the default value is setting to `true`
3. Create a new cluster by using the template
4. Verify selection from the template is selected by default

**Result**

The selection from the RKE template is preserved when loading the template while creating a new cluster.
![image.png](https://zube.io/files/rancher/e315aee8d6dd2abc6064cc07ac6d5998-image.png)
