### ISSUE TITLE
JS error when upgrading a Helm chart that was installed with the helm cli

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#4959]
**Setup**
- Rancher version: 2.6.3
- Browser type & version: Latest Chrome

**Describe the bug**
JS error when upgrading a hem chart that was installed with the helm cli

```
fetch.client.js?2293:75 Error in fetch(): TypeError: Cannot read properties of undefined (reading 'clusterName')
    at _callee4$ (catalog.cattle.io.app.js?9e85:244:17)
    at tryCatch (runtime.js?96cf:45:15)
    at Generator.invoke [as _invoke] (runtime.js?96cf:274:1)
    at Generator.prototype.<computed> [as next] (runtime.js?96cf:97:1)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3:1)
    at _next (asyncToGenerator.js?1da1:25:1)
    at eval (asyncToGenerator.js?1da1:32:1)
    at new Promise (<anonymous>)
    at CatalogApp.eval (asyncToGenerator.js?1da1:21:1)
    at _callee$ (install.vue?8e63:107:1)
```

**To Reproduce**
* Install a helm chart through the Helm CLI outside of Rancher, e.g. cert-manager:

```
helm repo add jetstack https://charts.jetstack.io

helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace --set installCRDs=true
```

* Go into the cluster and add `https://charts.jetstack.io` as a HTTP repository in Apps & Marketplace.
* Go to Installed Apps and try to upgrade/edit the installed cert-manager app

**Result**
There is a blank page with the above JS error.

**Expected Result**
The app upgrade wizard is shown.

**Screenshots**
![Bildschirmfoto 2022-01-20 um 19 20 29](https://user-images.githubusercontent.com/243056/150398322-733ad4c9-ae2a-4ed5-b6ae-0859c67fc879.png)

**Comment by nwmac** [comment]
@bashofmann I've added this to the 2.6.4 backlog and we'll try and get it fixed for then.

**Comment by richard-cox** [comment]
@MKlimuszka I've noticed you've moved a set of issues from 2.6.4 to 2.6.x, how come?

**Comment by jmcsagdc** [comment]
Verified in v2.6-d4089da78d39bae61de48ac53d1a06e2abbad18e-head

Steps are as described in the comment above: https://github.com/rancher/dashboard/issues/4959#issue-1109626792

The results now are that the upgrade/downgrade of this path through the wizard is no longer blocked and the transition to a different version of that chart is successful.

![2022-02-17_16-28-37](https://user-images.githubusercontent.com/15971368/154594932-6c03cf1d-0092-467b-ac9b-d6a6e0efca63.png)
