### ISSUE TITLE
Branding Fixed Banner Background Color defaults to eeeff4 (gray) should be white

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#4961]
**Setup**
- Rancher version: `2.6-head Commit ID fe149d2`
- Browser type & version: Chrome Version 97.0.4692.71

**Describe the bug**
The background color default for fixed banners is gray. should be white. 

**To Reproduce**
1. Navigate to Global Settings > Branding
2. select the fixed banner check boxes 
3. view background color

**Result**
default is gray
**Expected Result**
default is white

**Screenshots**

<img width="1405" alt="Screen Shot 2022-01-20 at 3 00 03 PM" src="https://user-images.githubusercontent.com/89212856/150413800-64dab1e2-6567-4495-a838-41e4b74abb79.png">

**Comment by nwmac** [comment]
It is set to grey in order to contrast with the white of the main window - otherwise their is no delimiter between the banner and the page header area.

**Comment by ronhorton** [comment]
**As designed**
