### ISSUE TITLE
NetworkAttachmentDefinition not listed in cluster-explorer or search

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/dashboard#4962]
Issue description:
NetworkAttachmentDefinition isn't being listed as an object type under the k8s.cni.cncf.io group, only Networks (see attached screenshot)

Business impact:
No UI management ability for NetworkAttachmentDefinitions

Troubleshooting steps:
n/a

Repro steps:

    Rancher 2.6.2, downstream custom RKE2 with multus/canal
    Apply the test-network-attachment-definition.yaml file (attached)
    Notice that this object type isn't listed on the left navigation thing or in search

Workaround:
Is workararound available and implemented? no
What is the workaround: n/a

Notes:
SURE-3769

**Comment by nwmac** [comment]
Note: Your provisioned cluster needs to be RKE2 with Multus

**Comment by nwmac** [comment]
The resource is there, but we label it just 'Networks' - we will rename this to 'Network Attachment Definition' in 2.6.5

**Comment by markusewalker** [comment]
Verified on v2.6-head https://github.com/rancher/rancher/commit/6bb6e45fba97f58443e547e2f57d2807a424467f.

**REPRODUCED ENVIRONMENT DETAILS**
- Linode Ubuntu 20.04.4 VM - Client Machine
- Docker install
- Rancher version: `v2.6.4`
- Kubernetes version: `v1.22.7+rke2r2`
- Cluster Type: Downstream RKE2 - 3 control plane, 3 etcd, 3 worker
     - Provisioned via Rancher UI
     - Container network, multus, canal

**VERIFIED ENVIRONMENT DETAILS**
- Rancher version: v2.6-head https://github.com/rancher/rancher/commit/6bb6e45fba97f58443e547e2f57d2807a424467f
- Install option: Helm Chart
- Kubernetes version: `v1.22.8`
- Cluster Type: Downstream RKE2 - 3 control plane, 3 etcd, 3 worker
     - Provisioned via Rancher UI
     - Container network, multus, canal

**REPRODUCTION STEPS**
1. Setup Rancher `v2.6.4` and navigate to Rancher UI in a browser.
2. Provision downstream RKE2 cluster with networking `multus,canal` selected.
3. Download `kubeconfig` file, apply to a local client machine. Once done, apply a test `NetworkAttachmentDefinition` YAML file to your cluster.
4. Navigate to top-left dropdown menu > Explore Cluster > freshly created-RKE2 cluster > More Resources > k8s.cni.cncf.io. Should see the following:
![image](https://user-images.githubusercontent.com/52591819/164332580-14bc72d5-8d83-4f66-803d-fcb0435256c4.png)

**VERIFICATION STEPS**
1. Setup Rancher `v2.6.4` and navigate to Rancher UI in a browser.
2. Provision downstream RKE2 cluster with networking `multus,canal` selected.
3. Download `kubeconfig` file, apply to a local client machine. Once done, apply a test `NetworkAttachmentDefinition` YAML file to your cluster.
4. Navigate to top-left dropdown menu > Explore Cluster > freshly created-RKE2 cluster > More Resources > k8s.cni.cncf.io. Should see the following:
![image](https://user-images.githubusercontent.com/52591819/164332708-88329aca-0107-48c6-8963-e78b029afb1b.png)
