### ISSUE TITLE
Import host should not be shown in the local cluster option

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4964]
Internal reference: SURE-3614
Reported in 2.5.9.

Issue description:
This "import host" option is for displaying the command again for adding other clusters.

It should not be in the local cluster options list

Business impact:
The user was confused about what this option will do.

Repro steps:

just log in to the UI 

Actual behavior:
"import host" is in the options list of the local cluster.

Expected behavior:
"import host" should not be in the options list of the local cluster.

**Comment by gaktive** [comment]
@nwmac to find out what this is really supposed to do.

**Comment by Priyashetty17** [comment]
✅ Test Passed on Rancher version "v2.7-f9291747e2cd869c468a2d93fbff92b6c54b4cb3-head" 

| Component| Version | 
|----------|----------|
| Rancher   | v2.7-f9291747e2cd869c468a2d93fbff92b6c54b4cb3-head  | 
| User Interface   | vmaster-dev  | 
| Dashboard   | master "113e1d30a" | 


**Validation Steps:**

1. Install Rancher version v2.7-head
2. Login to Ember UI: https://<rancher_IP>/g/clusters
3. Verify that the option to "Import host" is **NOT** available for the local cluster.

![GH4964_fix](https://github.com/rancher/dashboard/assets/42880103/ecedf989-e7f5-421d-ab23-99258ac08717)
