### ISSUE TITLE
Rancher Error when browsing clusters and refreshing

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4967]
Internal reference: SURE-3907
Reported in 2.6.3

A user is seeing an issue with the new Interface where when browsing to a cluster and hitting refresh the Default backend error screen will appear.

It is triggered by, clicking into a cluster, then hitting F5. usually the first time, 

What's likely missing is the schema for that type in the body of the response for the request to `/k8s/clusters/(id)/v1/schemas`

Attached are some screenshots.

![ranchererror.png](https://zube.io/files/rancher/d75b8d0a396a9ae4826981f8fea9d59c-ranchererror.png)![Screen Shot 2022-01-07 at 1.38.00 PM.png](https://zube.io/files/rancher/71e0502ebf9c2e03fb6db5515509ea71-screen-shot-2022-01-07-at-1-38-00-pm.png)![Screen Shot 2022-01-07 at 1.38.36 PM.png](https://zube.io/files/rancher/3db685f36f65f8d736264f5908d6c97c-screen-shot-2022-01-07-at-1-38-36-pm.png)

**Comment by gaktive** [comment]
@nwmac has been able to repro but it's a tight window to capture it as the cluster comes up. It may take time to troubleshoot though since there's a lot of tear down required, but we need to handle this race condition with something to display and then a retry.

**Comment by nwmac** [comment]
@gaktive I tried again to reproduce and could not - previously I could deploy the docker AIO image and if I quickly logged in and tried to explore the cluster, I got the fail-whale page.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

- Refreshed webpage after cluster creation, after scaling down/up nodes.
- This error is not seen
- Tried multiple times.
- Will close the issue now. Will lo a new one if this is seen again.
