### ISSUE TITLE
Global Setting: Separate Banners into its own side nav item

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4969]
The Global Settings -> Branding page shows branding and banners.

![image](https://user-images.githubusercontent.com/1955897/150522158-d58ebba8-bab6-4ac3-88e7-5533f7a3ae5e.png)

The config has grown - we should move the "Fixed Banners" config into its own page in the navigation.

Add a new nav item for Global Settings - see: `config/product/setting.js` - add a new `virtualType` (see the one for brand, route should be `c-cluster-settings-banners`) and add that to the `basicType`.

Create a new page in `pages/c/_cluster/settings/banners.vue` - move the UI components and required code from `brand` in the same folder into this folder.

Lastly, currently the banners config shows checkboxes for header, footer and consent banners - the controls for further configuration are only shown when the checkbox is checked - it would be nice always show these controls and to enable/disabled them only when the checkbox is checked.

**Comment by ronhorton** [comment]
**PASS** Verified on `2.6-head Commit ID 4d41423`

Tested:
1. Created a section for Banner config on the "Global Settings" area
2. Removed any references of Banner config from Branding
3. BannerSettings now displays each section by default
4. Fixed BannerSettings to disable UI elements when checkbox in section is not selected
