### ISSUE TITLE
Workload Environment Variable bugs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#497]
- [x] Source in Environment Variables needs to not have the namespace.  It should only show the source from the namespace that is selected from the Namespace field at top

- [x] Prefix or Alias field in Environment Variables loses focus after every character I enter

![image](https://user-images.githubusercontent.com/11514927/78930909-bd9bbe00-7a59-11ea-8faa-57d10da54e9e.png)

**Comment by soumyalj** [comment]
Tested with master-head build (d1d63b68a)
1. Create a namespace newns and create secret "secret1" in the namespace
2. Create a workload and add environment variable using "Add from Resource" . 

- Source does not contain the namespace 

![Screen Shot 2020-05-07 at 10 51 54 AM](https://user-images.githubusercontent.com/18536626/81328257-6df8e400-9051-11ea-9e65-cd1a71be33ec.png)
- Prefix/Alias field does not have focus issue. 

**Issue not fixed**
 Workload creation fails with the error below:
```

{ "type": "error", "links": {}, "code": "Invalid", "message": "Deployment.apps \"workload\" is invalid: [spec.template.spec.containers[0].image: Required value, spec.template.spec.containers[0].envFrom[0].secretRef.name: Invalid value: \"newns/secret1\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]", "status": 422 }

```

Request Payload:
```
{"type":"apps.deployment","metadata":{"namespace":"default","name":"workload"},"apiVersion":"apps/v1","spec":{"replicas":1,"template":{"spec":{"restartPolicy":"Always","containers":[{"name":"workload","resources":{"requests":{},"limits":{}},"env":[],"envFrom":[{"prefix":"test","secretRef":{"name":"newns/secret1","optional":false}}]}]},"metadata":{"labels":{"workload.user.cattle.io/workloadselector":"deployment-default-workload"}}},"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-default-workload"}}}}

```

**Comment by soumyalj** [comment]
Validated with master-head(1f4a2c388)
1. Create a namespace newns and create secret "secret1" in the namespace
2. Create a workload with nginx image and add environment variable using "Add from Resource" . Choose the secret as a resource . Workload creation succeeds. 
3. Exec shell in the workload pod and secret will be present as a env variable as expected.
