### ISSUE TITLE
vsphere -- no `content library` option for rke2 clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4971]
**Setup**
- Rancher version: v2.6.3-patch1-rc2
- Browser type & version: chrome

**Describe the bug**

for rke1, we have an option for `deploy from template: content library`, however this option is not available in rke2/k3s

**To Reproduce**

* go to cluster management -> create to  deploy an rke2/k3s cluster 
* select vsphere node driver and enter valid credentials
* go to the `creation method` dropdown

**Result**
no `content library` option is listed. 

**Expected Result**

I would expect there to still be a content library deployment option since this functionality exists for rke1

**Screenshots**

<img width="659" alt="Screen Shot 2022-01-21 at 10 58 33 AM" src="https://user-images.githubusercontent.com/16691014/150585020-c24b0822-ae5e-402e-8477-cbb0c18930c7.png">

**Additional context**
related issue: https://github.com/rancher/dashboard/issues/4302

**Comment by nwmac** [comment]
@codyrancher is this a duplicate?

**Comment by codyrancher** [comment]
@nwmac not for the work I've done. Everything I've done in the last month has been in ember. I was also able to reproduce in the latest.

**Comment by slickwarren** [comment]
tested on v2.6-head (572ab58):
the option is now available, however there is an error in the console and no information loads when the user selects this option
<img width="901" alt="Screen Shot 2022-03-09 at 2 07 49 PM" src="https://user-images.githubusercontent.com/16691014/157544880-0f65804f-88ac-410f-960b-b6b08d42348d.png">


user gets error in console: 
`InvalidBodyContent` : <vmware_url>/rest/com/vmware/content/library: 403
422 error

**Comment by codyrancher** [comment]
@slickwarren 
The error meessage and some issues I had earlier leads me to believe the vsphere account doesn't have access to content libraries. If that's correct maybe we should create a new issue and more gracefully handle .

**Comment by slickwarren** [comment]
my apologies, you're correct @codyrancher . Tested with new credentials that have access to some content libraries and do not hit this issue. Closing this ticket as a result.
