### ISSUE TITLE
Cannot enter free text in NameNsDescription to create a NS in helm wizard

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4977]
- User should be able to enter free text which is then used in helm install to create a new namespace
- This does not work
- Think this is the second time this has broken (or i can't find the other issue). Need to understand how this is breaking so often

**Comment by catherineluse** [comment]
I looked into that before, and from what I could tell, there's no way that it ever worked because the "taggable" property being passed into the Select doesn't do anything. It just isn't used.

**Comment by richard-cox** [comment]
This worked when implemented. It seems to flip flop though and I haven't yet worked out why. I've just tested on the epinio-dev branch, master and the 2.6.3 patch and all now work fine. 

The `taggable` property is passed to `InputWithSelect` --> `LabeledSelect` --> `v-select` (via `v-bind="$attrs"`). 

If anyone hits this in the future can they record the Rancher version and which chart they were using? I'll leave it open to investigate some more.




The functionality seems to flip flop, haven't yet tied down why it does this.

**Comment by nwmac** [comment]
I think we should explicitly add a '+' icon to the namespace control that shows a modal where you can enter a new name - the current capability to type a new name does work in, but is confusing - you start typing - this new name you type appears as the only option in the select control, which you then have to click on to select.

**Comment by richard-cox** [comment]
Catherine has been working on a replacement for this component https://github.com/rancher/dashboard/pull/5598

**Comment by richard-cox** [comment]
Closing given changes in https://github.com/rancher/dashboard/pull/5598
