### ISSUE TITLE
Related workloads section - Need to add to Secrets and ConfigMap pages

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#498]
We need to add a related workloads section to the Secret's details page.  It should be consistent with what we want to do in ConfigMap section

**Comment by lvuch** [comment]
https://xd.adobe.com/view/fa2c37a2-9fc4-45ac-6f0d-7e0ee06eff5c-8c1d/

**Comment by deniseschannon** [comment]
Based on comment from configmap, let's wait for API to make this easier.

https://github.com/rancher/dashboard/issues/265#issuecomment-614795824

**Comment by deniseschannon** [comment]
Seems like it might be ready based on this: https://github.com/rancher/rancher/issues/27487

**Comment by tfiduccia** [comment]
This shouldn't have been moved to test.  This issue is for adding a Related Resources tab to ConfigMap & Secrets Detail pages that show any workload that pull them.

**Comment by vincent99** [comment]
It doesn't look anything like the 6 month old screenshots but I added related workloads to all the types that use `<ResourceTabs>`, which should be most detail pages.

**Comment by tfiduccia** [comment]
Can't verify because backend API not returning relationship info for secret & Configmaps.  https://github.com/rancher/rancher/issues/30413

**Comment by gaktive** [comment]
Once this backend is done, this should just work right away.
