### ISSUE TITLE
Custom roles missing Names after upgrade from 2.5.8 to 2.6.3

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4980]
Internal reference: SURE-3960

Issue description:
User notes when upgrading from 2.5.8 to 2.6.3, any custom roles "names" fields are empty in Explorer/Vue UI. They cannot clone any of these custom roles.

Business impact:
Minor disruptive workflow.

Troubleshooting steps:
It was mentioned that the Manager/Ember link for the /g/ path works and they were able to clone the roles in this manner.

Repro steps:

- create a custom role in rancher 2.5.8
- upgrading to 2.6.3, note that the roles are missing names

Workaround:
Is workaround available and implemented? yes
What is the workaround: leverage the /g/ Manager/Ember link.

Actual behavior:
Names of custom roles are not "carried over".

Expected behavior:
Names should be preserved/displayed across upgrades.

![custom-role-name.png](https://zube.io/files/rancher/6575d9d372a4adedfd54aea2eb8d219b-custom-role-name.png)

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.5.8                                    |
| Rancher commit link       | not applicable                           |
| Installation option       | helm                                     |
| RKE binary version used   | v1.2.8                                   |
| If Helm Chart k8s cluster | v1.20.6                                  |
| Cert Details              | let's encrypt                            |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8                                  |
| Downstream cluster type   | not applicable                           |
| Downstream K8s version    | not applicable                           |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.5.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$REDACTED_HOSTNAME \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$REDACTED_EMAIL \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.5.8
```

## Validation steps

1. Provision rancher server using 2.5.8
2. Create custom role > cluster
3. Provide a unique name
4. Upgrade to 2.6.3
5. Inspect custom role
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Inspect custom role created in 2.5.8, appears identical in v2.6.3

#### :white_check_mark:Actual
Inspect custom role created in 2.5.8, appears identical in v2.6.3
