### ISSUE TITLE
Cannot select clusters in the Cluster Management page.

### ISSUE THREAD

**Issue by thedadams** [rancher/dashboard#4982]
**Setup**
- Rancher version: v2.6-head
- Browser type & version: Chrome

**Describe the bug**
I cannot select clusters (to delete, for example) from the cluster management page.

**To Reproduce**
1. Deploy a cluster.
2. After the cluster becomes active, click the checkbox next to the cluster's name on the Cluster Management page.

**Result**
Nothing seems to happen.

**Expected Result**
I should be given the option to delete the cluster.

**Screenshots**
Here is the error I see from the console when I try to click the checkbox.
<img width="1781" alt="Screen Shot 2022-01-25 at 9 30 17 AM" src="https://user-images.githubusercontent.com/3682717/151018195-94039492-991c-4a2f-b976-0963e5a8d39f.png">

**Comment by richard-cox** [comment]
Caused by missing `type` when translating `nav.shell` in `./models/management.cattle.io.cluster.js` and `./models/provisioning.cattle.io.cluster.js` #4970

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head da382a8
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: AWS EC2

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy a cluster.
2. After the cluster becomes active, click the checkbox next to the cluster's name on the Cluster Management page.

**Result** - Pass
Rancher gives the option to delete the Cluster and the console errors in the original description no longer occurs
![Screen Shot 2022-02-01 at 2.43.00 PM.png](https://zube.io/files/rancher/27f3588f025119838ad3a98e2993908a-screen-shot-2022-02-01-at-2-43-00-pm.png)

@sowmyav27 @aalves08
