### ISSUE TITLE
Move `Cluster Members` list out of RBAC

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4985]
- The `Cluster Members` resource is hidden in the `RBAC` group in the explore view
- The list should be moved up to the more prominent `Cluster` group at the top and be under `Nodes`
- As there are no other resource types in the `RBAC` group it should be removed

![image](https://user-images.githubusercontent.com/18697775/151151954-d7819818-f6d4-43bb-9845-aa702379ca97.png)

Note - The docs team should be informed to ensure any 2.6.x guides can be updated

**Comment by richard-cox** [comment]
@aalves08 Was running through some issues with Neil and this one would be a good one for you to tackle. Any questions just let me know

**Comment by aalves08** [comment]
@richard-cox I have created a draft pull request for this issue:
https://github.com/rancher/dashboard/pull/5002

I left as draft as I am unsure if I need to remove more references to RBAC since it has disappeared from the config tab.

Also, what the procedure to notify the docs team of these changes?

Thanks

CC @nwmac

**Comment by richard-cox** [comment]
@aalves08 The PR looks good. There are other references to RBAC but those are fine (not group related)

I did wonder though, maybe the label of the menu item should be just `Members` instead of `Cluster Members`. Will check with Neil but assume that it's a additional request for this issue

![image](https://user-images.githubusercontent.com/18697775/151844885-54afd31f-f75e-4f8e-8349-24a4fc489442.png)

**Comment by aalves08** [comment]
@richard-cox just talked with @nwmac about the naming and he feels that it should be up to @lvuch to decide on that.

With that, what's your opinion @lvuch ? "Cluster Members" or "Members"?

Thanks

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `d4089da`**

- As an admin, login into Rancher. Deploy a downstream cluster.
- `Cluster Members` is available under `Cluster`
- As a Cluster Member, `Cluster Members` is available under `Cluster`
- As a Project member, this option is not not available
