### ISSUE TITLE
When adding an rke2 node driver machinepool with OS detected as/set to windows, grey out etcd/cp roles

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/dashboard#4986]
Our goal is to maintain the same UX for rke2 node driver clusters with windows machine pools as exists today when creating a custom rke2 cluster with windows nodes.

This would require the etcd and controlplane role check-boxes to be greyed-out when the OS field (Issue: https://github.com/rancher/dashboard/issues/4859, PR: https://github.com/rancher/dashboard/pull/4920) is set to `windows` in a v2prov node driver cluster.  

![checkboxes in a machinepool](https://user-images.githubusercontent.com/55704795/151238161-28723655-2212-4805-afaf-1a8aaa09d0ea.png)

**Comment by mantis-toboggan-md** [comment]
This issue is dependent on https://github.com/rancher/dashboard/pull/4920, which is still waiting on backend

**Comment by slickwarren** [comment]
tested on v2.6-head (024e6fa):
when selecting `os: windows`, the etcd and control plane options for that node pool are greyed out, and any previously selected roles for those 2 options are removed.
