### ISSUE TITLE
Scale Node Pool Up or Down for RKE2 provisioned clusters is not working for long cluster/node pool names

### ISSUE THREAD

**Issue by thedadams** [rancher/dashboard#4990]
**Setup**
- Rancher version: v2.6-head
- Browser type & version: All

**Describe the bug**
See the backend issue description for a full breakdown of the problem: https://github.com/rancher/rancher/issues/35452#issue-1050296190

**To Reproduce**
Create an RKE2/K3S cluster with a very long name (as described above). After the cluster is active, try to scale one of the machine pools.

**Result**
Nothing happens.

**Expected Result**
The machine pools should be scaled.

**Screenshots**

**Additional context**
Kubernetes [has a strict length maximum](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md#identifiers-and-names-in-kubernetes) for names. Therefore, we have to do what we are doing (truncating the name and adding 5 random characters at the end).

Instead of looking at just the name of the MachineDeployment and matching it to the machinePool, the UI will have to do the following:
- The MachineDeployment will have an `infrastructureRef` that points to a MachineTemplate
- That MachineTemplate will be cloned from a Config (*)
- The Config will be referenced by a machineConfigRef from the cluster object's `spec.rkeConfig.machinePools`

So the identification of MachineDeployment to machinePool will be more complicated, but I don't really see a way around that at this point.

(*) This is currently in review in the backend. 
Backend Issue: https://github.com/rancher/rancher/issues/35452
Backend PR: https://github.com/rancher/rancher/pull/36269

**Comment by thedadams** [comment]
The backend change for this has been merged.

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: a64d237
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 do, aws, linode, azure clusters

----------

### Testing: ###
1. Create a RKE2 node driver cluster with a long cluster/pool name 
2. Wait for the cluster to provision
3. Navigate to node pools (Cluster Management > Click on the cluster)
4. Use "+" to scale up or "-" to scale down a pool 

Issue: **only AWS cluster's node pools scaling up/down worked as expected** 
While for other node pools I tried (azure, do, linode) "+" and "-" buttons didn't work with logging a console error 
```
TypeError: Cannot read properties of undefined (reading 'metadata')
    at t.value (cluster.x-k8s.io.machinedeployment.js:84:45)
    at click (provisioning.cattle.io.cluster.vue?161d:5:1419)
    at Qt (vue.runtime.esm.js:1854:26)
    at HTMLButtonElement.n (vue.runtime.esm.js:2179:14)
    at HTMLButtonElement.c._wrapper (vue.runtime.esm.js:6917:25)
```
![gif console](https://user-images.githubusercontent.com/40282141/154591713-b5743ce1-2289-4455-aa12-52bd3ebd5647.gif)

Back end does return all annotations as expected for all clusters including `rke.cattle.io/cloned-from-name`
![sergei do](https://user-images.githubusercontent.com/40282141/154591766-e402b2eb-a7c9-4fbb-bf17-30f578c8f2ed.jpg)
![others](https://user-images.githubusercontent.com/40282141/154591807-a155f4eb-4dc2-4282-88ef-fd8efb89f2cb.jpg)

**Comment by richard-cox** [comment]
Weird, this worked for me with DO when the PR was reviewed. It looks like it's an issue with a missing `template`... which i suggested couldn't ever be the case

**Comment by anupama2501** [comment]
2.6-head 8c785a1
I'm not able to scale down/ scale up node pools either on Amazon ec2 node driver rke2 cluster. I see the same console error as Sergei mentioned. 

**Note** scale down/up works if `drain on delete` option is selected while creating the clusters for the node pools.


<img width="250" alt="2022-02-23_16-46-47" src="https://user-images.githubusercontent.com/38144301/155435630-5fdbb89e-0d74-4210-9804-41e982a85a4b.png">

**Comment by Auston-Ivison-Suse** [comment]
**Reproduction Setup**
- Rancher version: 2.6.3
- Browser: Chrome Version 99.0.4844.74

**Reproduction Steps**
1. Create a RKE2 node driver cluster with a long cluster/pool name
2. Wait for the cluster to provision
3. Navigate to node pools (Cluster Management > Click on the cluster)
4. Use "+" to scale up or "-" to scale down a pool

**Result**

We see console type errors: t.value cluster.x-k8s.io.machinedeployment
We check the issue within the rancher api resources and find machinepools.machineConfigRef.name doesn't have the appropriately truncated name. 

**Validation Setup**
- rancher version: v2.6.4-rc9
- Browser:Chrome Version 99.0.4844.74

**Validation Steps**
1. Create a RKE2 node driver cluster with a long cluster/pool name
2. Wait for the cluster to provision
3. Navigate to node pools (Cluster Management > Click on the cluster)
4. Use "+" to scale up or "-" to scale down a pool

**Result**
- When we scale down or up the pool we don't see any console errors
- When we check the dev tools we can see the appropriately named machineConfigRef (Screenshot for reference)
![Screen Shot 2022-03-18 at 3.04.33 PM.png](https://zube.io/files/rancher/d3b79e6e557c12dde9bf9cc21661bd94-screen-shot-2022-03-18-at-3-04-33-pm.png)
- There are no networks errors within the devtools
