### ISSUE TITLE
New User Default Role Toggle is Broken in Rancher UI

### ISSUE THREAD

**Issue by nayrnet** [rancher/dashboard#4992]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Docker/Helm/Hosted Rancher

**Information about the Cluster**
- Kubernetes version: 1.20 & 1.21
- Cluster Type (Local/Downstream): Local/Global

**User Information**
- What is the role of the user logged in? Admin & Restricted Admin
   
**Describe the bug**
In new Rancher UI, changing the "New User Default" Global Role value is broken, cannot select "No" for Standard User, or select "Yes" on another Role.

**To Reproduce**
On any 2.6.x instance, go to Users & Authentication -> Roles -> Standard User -> Edit Config -> Try to change "New User Default" to no. 

**Result**
The User Interface does not let you change this Value, if you change to the old user interface you can.

**Expected Result**
Should be able to configure or unconfigure new user default.

**Screenshots**
<img width="770" alt="Screen Shot 2022-01-26 at 10 13 11 AM" src="https://user-images.githubusercontent.com/3732081/151216558-0770f997-2461-4570-96a5-02070e9b90fd.png">

**Additional context**
Tested in Safari and Chrome

SURE-3966

**Comment by nayrnet** [comment]
A workaround is to open the hidden legacy UI via: `https://RANCHERSERVERURL/g` (replace /dashboard/ with /g/) then you can change these settings as needed.

**Comment by nwmac** [comment]
This appears to work on 2.6.2 - need to check on 2.6.3

**Comment by cnotv** [comment]
> This appears to work on 2.6.2 - need to check on 2.6.3

Not now, it returns 
```
Cannot use 'in' operator to search for 'newUserDefault' in null
```

**Comment by cnotv** [comment]
Analogue error happens while typing the description.

**Comment by cnotv** [comment]
@nwmac I think we should fix this issue before release 2.6.4 as every global role cannot be created or edited:
- Path: `/c/local/auth/roles`
- Users & Authentication > Roles > Create/Edit

**Comment by cnotv** [comment]
The description issue seems to come out from this https://github.com/rancher/dashboard/blob/master/components/form/NameNsDescription.vue#L251-L258

**Comment by nwmac** [comment]
@cnotv if we know how to fix it then we can get it in to 2.6.4

**Comment by cnotv** [comment]
In any case for the description the issue seems to be the UI trying to set the value for `description` which has not a setter for the model :shrug: 

For the radio button it just cannot find the context at all (`this` returns `null`), even more enigmatic :sweat_smile:

**Comment by cnotv** [comment]
For the records, this is also required for other role editor pages:

- `models/management.cattle.io.globalrole.js`
- `models/management.cattle.io.globalrolebinding.js`
- `models/management.cattle.io.roletemplate.js`

**Comment by cnotv** [comment]
> @nwmac beside analyzing the YAML, how can I test the behavior of actually setting a global user role as `New User Default Role`?

Ok basically this can be verified also on user role creation.

**Comment by Josh-Diamond** [comment]
Ticket #4992 - Test Results

With docker on single-node install:

Reproduced on v2.6.3:
1. Fresh install of rancher v2.6.3
2. As admin, go to `Users & Authentication`
3. Select `Roles`
4. Find `Standard User` and then `edit config`
5. Reproduced - New User Default is unable to be modified

Screenshot:
`New User Default` is selected as `Yes` and cannot be modifed
<img width="268" alt="Screen Shot 2022-03-16 at 10 15 40 AM" src="https://user-images.githubusercontent.com/46494969/158651347-8f5ba854-6d17-49be-b336-2f88d5ef6158.png">




Verified on v2.6-3b2677f931ef0ae4d2e773a2c5673ce968c8e9cd-head:
1. Fresh install of rancher v2.6-head
2. As admin, go to `Users & Authentication`
3. Select `Roles`
4. Find `Standard User` and then `edit config`
5. Verified - New User Default is able to be modified

Screenshot:
`New User Default` is selected as `Yes` and can be modified to `No`
<img width="243" alt="Screen Shot 2022-03-16 at 10 27 17 AM" src="https://user-images.githubusercontent.com/46494969/158651389-00fc8c08-c4ce-48fa-94ff-f4e96fd1c50a.png">




Upgrade Verified on v2.6.3 >> v2.6-3b2677f931ef0ae4d2e773a2c5673ce968c8e9cd-head:
1. Fresh install of rancher v2.6.3
2. As admin, go to `Users & Authentication`
3. Select `Roles`
4. Find `Standard User` and then `edit config`
5. Reproduced - New User Default is unable to be modified
6. Upgrade rancher from v2.6.3 >> v2.6-head
7. As admin, go to `Users & Authentication`
8. Select `Roles`
9. Find ‘Standard User` and then `edit config`
10. Upgrade Verified - New User Default is able to be modified

**Comment by gaktive** [comment]
Zube reopened this open reading the ticket, strange. Reclosing.
