### ISSUE TITLE
Sortable table will crash some pages due to an undefined 'act' variable

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#4993]
![image](https://user-images.githubusercontent.com/55104481/151266056-258241ad-bee0-48ff-99b2-2faad4a897cd.png)

Reproduce:
1. Create a cluster
2. Install monitoring
3. Visit the Routes and Receivers list page

Appears to be caused by this commit https://github.com/rancher/dashboard/commit/8802a0e2e392fcf0dff11d19f4badd5b7c022fb7. When that commit is reverted the page renders fine.

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID 20d20a3`

1. created downstream cluster
2. Installed monitoring
3. clicked into the `routes and receivers` section
4. clicked throughout monitoring section menu items, tabs, etc

No error. This has a duplicate bug that I will also close: https://github.com/rancher/dashboard/issues/5078
