### ISSUE TITLE
Missing Create from YAML button in resource lists

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#4995]
**Setup**
- Rancher version: 2.6.3
- Browser type & version: Chrome

**Describe the bug**
For resources that do not have a edit form, the "Create from YAML" button is missing on the resource list page.

**To Reproduce**
As a cluster owner, go to the NetworkPolicies resource list.

**Result**
There is no "Create from YAML" button.

**Expected Result**
There should be a "Create from YAML" button.

**Screenshots**
Broken in 2.6.3:
![Bildschirmfoto 2022-01-27 um 14 08 35](https://user-images.githubusercontent.com/243056/151365126-db7e5153-c504-43b3-9b3b-0869d9974208.png)

Works in 2.6.2:
![Bildschirmfoto 2022-01-27 um 14 09 12](https://user-images.githubusercontent.com/243056/151365218-4b85045e-0de5-478c-9150-b6872b8d383a.png)

**Additional context**
The resource list items have a edit button in the context menu. The user I tested with has permissions to create and edit these rersources.
The create button is still there in 2.6.2. The commit that breaks it is https://github.com/rancher/dashboard/commit/c4c40a580a93bea30d48f06c273e6bf0e032311c.

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.6.3                                  |
| Rancher cluster type    | Docker                                  |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | not applicable                          |
| Downstream K8s version  | not applicable                          |
| Browser type            | Google Chrome                           |
| Browser version         | 97.0.4692.99 (Official Build) (x86_64)  |

## Reproduction steps

**Prerequisites**

- Logged in as an admin user

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click the `hamburger menu` -> `Cluster Management` -> `Explore` next to the `local` cluster
3. Click `Service Discovery` from the left side menu -> `Network Policies`
  
#### RESULT

There is no `Create from YAML` button shown in the UI

#### EXPECTED RESULT

For there to be a button `Create from YAML`

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-7efbeab2cc2fa1a9dce2063970df6b48fdcaa2cf-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | not applicable                                     |
| Downstream K8s version  | not applicable                                     |
| Browser type            | Google Chrome                                      |
| Browser version         | 97.0.4692.99 (Official Build) (x86_64)             |

## Validation steps

**Prerequisites**

- Logged in as an admin user

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click the `hamburger menu` -> `Cluster Management` -> `Explore` next to the `local` cluster
3. Click `Service Discovery` from the left side menu -> `Network Policies`

### RESULT

Checks passed! The `Create from YAML` button is present and functional
