### ISSUE TITLE
Missing namespace selector on namespaced monitoring and logging resources

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#4998]
**Setup**
- Rancher version: 2.6.3
- Browser type & version: Chrome

**Describe the bug**
Starting with 2.6.3 the namespace selector dropdown is not displayed anymore for namespaced resources under Monitoring and Logging.

This affects in Monitoring
* Monitors
* Prometheus Rules
* Alert managers
* Prometheis

This affects in logging
* Flows
* Outputs

**To Reproduce**
Install Monitoring or Logging and go to one of the namespaced resources.

**Result**
There is no namespace selector shown in the title bar and only the existing resources are shown in the namespaces that were previously selected.

**Expected Result**
There is a namespace selector.

**Screenshots**
![Bildschirmfoto 2022-01-27 um 16 36 06](https://user-images.githubusercontent.com/243056/151391276-7832b516-c854-4d94-85f3-c51c59a910ae.png)

**Comment by ronhorton** [comment]
confirmed in 2.6.3
<img width="709" alt="Screen Shot 2022-02-03 at 8 22 18 AM" src="https://user-images.githubusercontent.com/89212856/152354498-5cb1d8d6-c229-4ca9-81b9-6c4015587399.png">
