### ISSUE TITLE
Storage step in workloads based on "Volumes" section in Ember UI

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#500]
Volume tab need to support multiple types of Volumes, each with it's own content.  Here is rancher 2.4 example:
![image](https://user-images.githubusercontent.com/11514927/78933004-64ce2480-7a5d-11ea-84de-15aecbf8c7f3.png)

**Comment by lvuch** [comment]
<img width="685" alt="Screen Shot 2020-04-09 at 3 10 31 PM" src="https://user-images.githubusercontent.com/3013118/78945084-4c1d3900-7a74-11ea-8a47-5e8a39d14146.png">
<img width="686" alt="Screen Shot 2020-04-09 at 3 10 23 PM" src="https://user-images.githubusercontent.com/3013118/78945091-4de6fc80-7a74-11ea-971f-e6dfce96b209.png">

@tfiduccia please review the above

**Comment by lvuch** [comment]
https://xd.adobe.com/view/fdf9e550-ec05-496d-b52c-01d679f45374-a8aa/

**Comment by sowmyav27** [comment]
**Following have been tested on master-head - commit id: `8d9cedde`**

- Secrets
- config Maps
- Existing PVC
- Create new PVC
- Ephemeral volume (AWS)

Separate issues have been logged while testing there ^^^
