### ISSUE TITLE
Can't create a new project after not specifying Namespace Default Limit once: error never clears when a value is provided

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/dashboard#5000]
**Setup**
- Rancher version: v2.6.3
- Browser type & version: Firefox 96, Safari 15.2

**Describe the bug**

When I make a Project and specify Resource Quota's Project Limit and save, there is an error saying I also must specify Namespace Default Limit, which makes sense.
However, when I edit Namespace Default Limit input for a resource, the UI clears the input and keeps re-displaying the error on every keystroke and not letting submit the form.

**To Reproduce**

1. In a cluster go to Projects/Namespaces.
2. Click "Create Project".
3. In the form, provide a Name and then switch to the Resource Quotas tab.
4. Click "Add Resource" and choose any Resource Type, then specify Project Limit. Leave Namespace Default Limit blank.
5. Click Create and observe a validation error (since Namespace Default Limit is required).
6. Do specify a value for Namespace Default Limit, click Create and see that your input has been cleared out, and the error message is rendered again below the previous one. You can't create the Project. Even if Remove this resource altogether, you still can't Create.
Adding a new Resource adds a blank row, which is another issue.
**Result**

**Expected Result**

Expect to see the validation message that would clear once I provide the value for Namespace Default Limit and click Create. Then expect the project to be created.

**Screenshots**

<img width="1305" alt="Screen Shot 2022-01-27 at 11 37 17" src="https://user-images.githubusercontent.com/17733533/151404032-101e31f9-8124-4f13-8130-e9e0c89b3982.png">

Removing the resource and trying to add a new one multiple times:

<img width="1300" alt="Screen Shot 2022-01-27 at 11 56 51" src="https://user-images.githubusercontent.com/17733533/151406479-4efec0ef-2fdd-4563-8448-1a90e0cd3df2.png">

**Additional context**

**Detailed Description**

**Context**

**Comment by sowmyav27** [comment]
**on 2.6.4**

- In a cluster go to Projects/Namespaces.
- Click "Create Project".
- In the form, provide a Name and then switch to the Resource Quotas tab.
- Click "Add Resource" and choose any Resource Type, then specify Project Limit. Leave Namespace Default Limit blank.
- Click Create. Error seen
- Now add value for Namespace Default Limit field and click on Create
- Multiple lines of same error are seen

<img width="1280" alt="Screen Shot 2022-04-24 at 8 42 53 PM" src="https://user-images.githubusercontent.com/26032343/165017302-35472376-1be7-442b-ab84-3e5fb37b0d70.png">


**on 2.6.5-rc2**
- In a cluster go to Projects/Namespaces.
- Click "Create Project".
- In the form, provide a Name and then switch to the Resource Quotas tab.
- Click "Add Resource" and choose any Resource Type, then specify Project Limit. Leave Namespace Default Limit blank.
- Click Create. Error seen
- Now add value for Namespace Default Limit field and click on Create
- No error seen
- Project is created successfully.
