### ISSUE TITLE
Azure Hosted Cloud Credentials don't save when creating them on "Add Cluster" page

### ISSUE THREAD

**Issue by Auston-Ivison-Suse** [rancher/dashboard#5009]
**Setup**
- Rancher version: v2.6-head(7efbeab)
- Browser type & version:
Chrome; version: 96.0.4664.110

**Describe the bug**

Azure Cloud Credentials don't save when provisioning an Azure(AKS) hosted cluster and creating the credentials within the add cluster page of 

**To Reproduce**
1. Go to the following page:

` /dashboard/c/local/manager/provisioning.cattle.io.cluster/create?type=azureaks
`
2. Enter valid credentials for Azure. 
3. Click create

**Result**
You will see the page "reload" with empty fields for all of the cloud credential info you just entered. 
You can also check the cloud credential page and notice that the credentials were created, they just weren't show up in the dropdown menu. 

Console Log errors: 
`plugins.js:185 Machine Driver Config schema not found for azureaks` appears when landing on the first page.

`index.js:1400 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')` When attempting to create the cloud credential.

**Expected Result**
The credentials save and you move onto the next step of provisioning the hosted cluster

**Screenshots**
Screenshot of the result after following the reproduction steps
<img width="1792" alt="AKSCloudCredentials" src="https://user-images.githubusercontent.com/89411550/151720785-2e6e9395-1645-48cc-b6e9-70715a91f7e1.png">

**Additional context**
I checked other hosted cloud credentials and it seems to be unique to the AKS hosted provider.

**Comment by nwmac** [comment]
This is some weirdness due to the Embedding - I had a quick look but it was not obvious what the problem is.

When the page is not embedded it appears to work correctly.

**Comment by nwmac** [comment]
Note: There is no validation done on this page of the credential, so you can test this without Azure access - just enter junk and press 'Create' and you'll see the form update and NOT select your new credential (which is there if you go to the cloud credentials page)

**Comment by Auston-Ivison-Suse** [comment]
**Reproduction Setup**
rancher version: v2.6.3
Chrome version:99.0.4844.74 

**To Reproduce**
1. Go to 'create' cluster --> select AKS hosted
2. Enter valid credentials for Azure. 
3. Click create

**Validation  Setup**
rancher version: v2.6.3
Chrome version:99.0.4844.74 

**To Reproduce**
1. Go to 'create' cluster --> select AKS hosted
2. Enter valid credentials for Azure. 
3. Click create

**Results**
The fix has been validated with the above steps. 
I also made sure there were errors were still working if we enter wrong values within the fields.  
`SyntaxError: Unexpected token I in JSON at position 204` is an example when you don't have the right syntax in the fields.
