### ISSUE TITLE
Snapshot create/restore and `rotate certificate`  actions not available for a Standard user (RKE1)

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/dashboard#5011]
**Setup**
- Rancher version: v2.6-head 7efbeab
- Browser type & version: Chrome Version 97.0.4692.99

**Describe the bug**

The following snapshot related actions are not available for a Std user.
- Take Snapshot
- Restore Snapshot
- Rotate Certificates

**To Reproduce**

1. Deploy an RKE1 custom cluster
2. Take a few snapshots
3. On the Cluster Management page, find snapshot related actions

**Result**
On the Cluster Management page, snapshot related actions are not available
- I can access Restore when I navigate to Cluster details --> Snapshot -->Select snapshot --> Restore.

**Expected Result**

Restore Snapshot should be available to standard user on Cluster Management page

**Screenshots**

<img width="964" alt="Screen Shot 2022-01-31 at 1 16 36 PM" src="https://user-images.githubusercontent.com/97477402/151849961-3f8d19a1-d77b-4c7a-9900-0154b281b225.png">

**Context**

The behavior for the snapshot related actions need to be consistent between standard users and admin

Standard users will be able to access the snapshot related functions as intended

**Comment by neillsom** [comment]
The issue appears to be that a standard user does not have backupEtcd as an available k8s action

**As admin**
![admin-with-action.jpg](https://zube.io/files/rancher/f9cea1372cc29e576695c101de014a9e-admin-with-action.jpg)

**As standard user**
![standarduser-without-action.jpg](https://zube.io/files/rancher/63a0327cfb36602624c0c9b1a961b27a-standarduser-without-action.jpg)

We can bypass the logic to enable a standard user to have the UI 'take snapshot' and 'restore snapshot' functionality, but these will result in a 403 error

**Non-admin user attempting to take snapshot**
![403-error.jpg](https://zube.io/files/rancher/9a630f1bcc5c84a09281a70ccdee3fc2-403-error.jpg)

**Comment by nwmac** [comment]
@neillsom This is labelled in Review, but I don't see a PR for this. If the backend is not proving the backupEtcd action for a standard user, and they should be able to snapshot, then we need a backend fix, so we should open an issue in rancher/rancher.

**Comment by neillsom** [comment]
Rancher/rancher issue https://github.com/rancher/rancher/issues/36757

**Comment by gaktive** [comment]
Based on https://github.com/rancher/rancher/issues/36757#issuecomment-1063019335, the backend appears to be working as designed.

@neillsom can you review @MbolotSuse's comment and see if there is anything else that we need the backend to help out with?

**Comment by gaktive** [comment]
Backend ticket marked as closed with comments indicating it's working as designed there. @neillsom do you have enough now to work on this?

**Comment by nwmac** [comment]
I have updated the backend issue and re-opened it - this works for RKE2 but NOT for RKE1

**Comment by MbolotSuse** [comment]
@nwmac Just tried this with an RKE1 cluster (v1.23.4) in digital ocean. Same results as above - I'm able to see the snapshots and take a new snapshot after clicking into the cluster. The backend, in this case, appears to be functioning as intended.

Would you mind providing more clarity on what specifically is not working (as well as what the expected result is)?

**Comment by catherineluse** [comment]
Should this be in the v2.6.4 release notes under know issues? Cc @jtravee

**Comment by jtravee** [comment]
> Should this be in the v2.6.4 release notes under known issues? Cc @jtravee

I think it should be, I'll add it now!

**Comment by gaktive** [comment]
Backend may have a fix now. It's in QA's hands so UI may be unblocked. @MbolotSuse is that true?

**Comment by gaktive** [comment]
@neillsom we're unblocked on this again.

**Comment by MbolotSuse** [comment]
@gaktive Sorry for not letting you know. We have the fix code available in master. Still needs to go through QA and all though.

**Comment by gaktive** [comment]
Thanks @MbolotSuse; we'll keep this in Next Up but lower on the stack in case.

**Comment by gaktive** [comment]
Backend work passed QA yesterday. Not sure if UI has time to get this in for 2.6.5 but we'll see.

**Comment by nwmac** [comment]
I have validated that given the backend changes, this is now working in the UI - moving to Test for QA to validate and sign-off.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 7db4fe4
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: EC2 rke1 node driver

----------

### Testing: ###

Tested this issue with the following steps:
1. Create rke1 node driver cluster as Standard user

**Result** - Pass

Standard users are now able to access snapshot related functions as intended on Cluster Management page

![image.png](https://zube.io/files/rancher/12ddc20cf328cc6c2e1e2482d5fa64f1-image.png)
