### ISSUE TITLE
Make sure that quoted keys can be properly evaluated by Jexl

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5014]
This is a follow-up to https://github.com/rancher/dashboard/pull/5008.

Jexl is the library Rancher uses to evaluate Javascript expressions. It is used in Rancher catalog apps in cases where users have created a Questions.yaml to conditionally show and hide inputs for the form that is displayed when you install the helm chart application through Rancher.

Jexl doesn't support hyphens in variable names and the work in https://github.com/rancher/dashboard/pull/5008 was done so that Ranchers who had created Questions.yaml files in legacy apps would see the same logic working correctly even if it had hyphens in variable names.

We need to make sure that quoted keys are able to be used in the Questions.yaml because that is the proper way that users should be creating keys with hyphens.

The question variable reference in the docs https://rancher.com/docs/rancher/v2.6/en/helm-charts/creating-apps/#question-variable-reference needs to be updated to tell people not to  put hyphens in variable names and to use quoted keys if they need to use a hyphen.

**Comment by nwmac** [comment]
Won't fix
