### ISSUE TITLE
How does the UI calculate the resource quota set for namespaces when a Project quota is enabled?

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5016]
To help with the backend on https://github.com/rancher/rancher/issues/35647, we need to sort out how the UI is calculating resource quotas as the backend would like to be on the same page as us.

From a recent comment:
>This issue occurs when you try to create namespaces bypassing the UI - directly via kubectl.
We have to support that. The UI sets the special annotation `field.cattle.io/resourceQuota` for remaining quota in relation to the project's total quota and passes it to the backend. We need to set this annotation ourselves on the backend. We must effectively do what to the UI does when it is bypassed.

> The problem is that the UI sets the value of the annotation in a strange way, it does not just pull a constant value from the project. Sometimes it calculates the remaining available quota for a new namespace, sometimes it does not. Sometimes the calculation is strange - zero or a negative value for available resource quota. And I have seen different behaviors in same scenarios.

> We need to understand exactly what the UI must do and then write the same logic for the backend, so that users can use kubectl to make namespaces in projects, but without bypassing all our additional logic.

**Comment by gaktive** [comment]
@nwmac FYI. It's possible other tickets already being worked on (like #4597) tackle this in a way but the backend team is running into their own issues and want to standardize in a simple way.

@maxsokolovsky anything else to add here?

**Comment by catherineluse** [comment]
In the namespace creation form, the logic to get the max resource limit for a namespace is in https://github.com/rancher/dashboard/blob/master/components/form/ResourceQuota/NamespaceRow.vue 

The most important value in that calculation is the max namespace limit (https://github.com/rancher/dashboard/blob/master/components/form/ResourceQuota/NamespaceRow.vue#L101). This value is the project resource limit minus the sum of all the limits of the namespaces in the project. You can configure the limit to be less than that number, but you can't exceed it when creating the namespace.

If the max limit is less than the default namespace resource limit (as configured in the project) you see the default namespace resource limit populate in the form, but you still can't exceed the max.

As for this comment:

> Sometimes the calculation is strange - zero or a negative value for available resource quota.

I believe the negative values are a bug. I saw negative values too and I logged an issue to reproduce them here: https://github.com/rancher/dashboard/issues/5153

As for the rules for how changes to the project resource quota should propagate to the namespaces inside, I've gotten mixed messages, so I will have to defer to Denise or Cody. What we have documented doesn't match the behavior I see in the UI in v2.6.4. We documented:

> Updating an existing namespace default limit for a quota at the project level will not result in that value being propagated to existing namespaces in the project; the updated value will only be applied to newly created namespaces in that project.

But in testing out the UI I have seen changes to the project quota propagate to the namespaces inside it. I'll need to ask Denise or Cody how the values are meant to propagate in v2.6.x.

**Comment by cbron** [comment]
> But in testing out the UI I have seen changes to the project quota propagate to the namespaces inside it

We discussed and we don't believe this is good behavior. Instead we should keep in line with how the docs currently state things work, Meaning we don't rebalance existing defaults, only change things moving forward. That is also how Kubernetes treats Resource Quotas.

**Comment by maxsokolovsky** [comment]
Question, @catherineluse: I looked again and found that the UI grants the **remainder** of a resource to a new namespace, even if it requires more than what's currently available. Not zero, but however much is left over. Say, there is 200 remaining, my new namespace wants 300, The UI would grant it 200, not 0 (by setting the annotation). Just wanted to confirm: is this still what we want?

**Comment by cbron** [comment]
Added some action items in this comment: https://github.com/rancher/rancher/issues/35647#issuecomment-1048321181

Discussing that last question offline.

**Comment by catherineluse** [comment]
I think if the remainder is less than 0, the UI can say that, as long as it communicates that with a sentence instead of a number. It could have a message along the lines of "The project resource quota is over capacity by [amount here] based on the resource limits of the namespaces in the project. To allocate resources for the new namespace, increase the project resource quota or decrease the resource quota for namespaces in the project"

**Comment by catherineluse** [comment]
I have made these separate UI issues dealing with project resource quotas:

- https://github.com/rancher/dashboard/issues/5188 Stop rebalancing quotas on existing namespaces, stay in line with docs
- https://github.com/rancher/dashboard/issues/5154 Dashboard crashes after creating a project with a namespace default resource limit but no project resource limit
- https://github.com/rancher/dashboard/issues/5153 Show warnings when user tries to create namespace in a project with no remaining resource capacity
- https://github.com/rancher/dashboard/issues/5173 Project is created with resource quota even after the quota is removed

**Comment by catherineluse** [comment]
@gaktive I think this issue can be closed because the back end has settled on the plan in this comment for now https://github.com/rancher/rancher/issues/35647#issuecomment-1050136094

**Comment by gaktive** [comment]
Thanks @catherineluse -- will this be the same case for the other 5 related tickets?

I'll move this to QA so that they're aware that there's a fix coming though it'll be more backend related per the 35647 item.

**Comment by catherineluse** [comment]
I'd say the other related tickets should stay open because they are still needed to improve the user experience around project quotas, even though they aren't directly solving the problem that triggered the back end ticket.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component                 | Version / Type                                      |
| ------------------------- | --------------------------------------------------- |
| Rancher version           | 2.6.4-rc8                                           |
| Installation option       | Helm high availability (AWS)                        |
| If Helm Chart k8s cluster | RKE v1.22.6                                         |
| Cert Details              | ingress.tls.source=secret (certificates from files) |
| Docker version            | 20.10.7, build f0df350                              |
| Helm version              | v2.16.8-rancher1                                    |
| Downstream cluster type   | RKE Linode                                          |
| Downstream K8s version    | v1.23.4-rancher1-1                                  |
| Logged in user role       | Standard user                                       |
| Browser type              | Google Chrome                                       |
| Browser version           | 99.0.4844.51 (Official Build) (x86_64)              |

## Validation steps

1. While taking note of the updated docs at [/resource-quotas/quotas-for-projects/](https://rancher.com/docs/rancher/v2.6/en/project-admin/resource-quotas/quotas-for-projects/)

2. Create a project
   - Name: `mytest-project` 
   - Resource Quotas:
     - CPU Limit / Project Limit: `500m`
     - Memory Limit / Project Limit: `512Mi`
     - CPU Limit / Namespace Default Limit: `300m`
     - Memory Limit / Namespace Default Limit: `64Mi`
3. Create two namespaces in the UI
    1. Name: `ns1`
    2. Name: `ns2`
4. Inspect them with

```shell
kubectl describe namespace $nameOfNamespace
```

5. Create a new namespace in the project using `kubectl` 
   - Launch the `Kubectl Shell` from the UI
   - Run the following commands

```shell
touch new-namespace-spec.yaml
vi new-namespace-spec.yaml
```

6. Paste in the following yaml file

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: [your-cluster-ID]:[your-project-ID]
  name: k1
```

7. Run the following

```shell
kubectl create -f new-namespace-spec.yaml
```

```shell
kubectl describe namespace k1
```
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
For the namespace created via kubectl to abide by the resource quota set to the project

#### :white_check_mark:Actual
The namespace created via kubectl did abide by the resource quota set against the project
