### ISSUE TITLE
Link is broken on UI under security groups

### ISSUE THREAD

**Issue by jtravee** [rancher/dashboard#5017]
Found under Cluster Management > RKE1 Config > Node Templates. When selecting a security group (step 3) for an Amazon EC2 instance, the link shown under `Learn more about the ports that will be opened` does not work. Current [link](https://rancher.com/docs/rancher/v2.5/en/installation/references/); I believe the correct link is [here](https://rancher.com/docs/rancher/v2.6/en/installation/requirements/ports/#rancher-nodes).

![image](https://user-images.githubusercontent.com/87146683/152010671-53df6e8a-979a-47fe-ab5b-03b020162be6.png)

**Comment by nwmac** [comment]
Closing in favour of https://github.com/rancher/dashboard/issues/5263 - which will be validated by QA
