### ISSUE TITLE
Update list of available EC2 instances

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5018]
The list of available EC2 instances (used for creating EC2 node templates) has become outdated. Amazon doesn't provide an API to get the available list of instances, so the UI needs to be manually updated to provide new instance types.

The new `g` instances need to be added, and the list may need to be updated to include other new instance types.

We currently use the CSV data from ec2instances.info and we can just update that.

The list of instances appears in two parts of the UI:

- The cluster provisioning form for new RKE2/K3s clusters on EC2
- The RKE1 node templates form for EC2

<img width="1162" alt="Screen Shot 2022-02-01 at 11 26 30 AM" src="https://user-images.githubusercontent.com/20599230/152028922-4e2b0267-81eb-422e-921c-b09a7f1c59e3.png">
<img width="1196" alt="Screen Shot 2022-02-01 at 11 29 11 AM" src="https://user-images.githubusercontent.com/20599230/152028943-311b6738-e0ea-4da1-bd61-448aa9763cb2.png">

Edit: Found out this API can be used https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-types.html

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/pull/5103 
Thanks @vincent99 !

**Comment by catherineluse** [comment]
This is getting done in two separate PRs. One to update the list for RKE2/K3s cluster provisioning, and one to update the list for node templates for RKE1 provisioning.

- https://github.com/rancher/dashboard/issues/5205
- https://github.com/rancher/dashboard/issues/5190

**Comment by richard-cox** [comment]
See below, RKE2 has been done via https://github.com/rancher/dashboard/pull/5103 and tracked in https://github.com/rancher/dashboard/issues/5190. RKE1 work is open and tracked in https://github.com/rancher/dashboard/issues/5205. I'll close this as the work is tracked in the other issues
