### ISSUE TITLE
favicon for rancher

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#502]
Can we update the favicon to back to rancher? Also, should it be called "Rancher" instead of "Dashboard"?

Dashboard favicon:

<img width="148" alt="Screen Shot 2020-04-12 at 12 42 01 PM" src="https://user-images.githubusercontent.com/11410997/79078133-1b7b1080-7cbb-11ea-8ed8-01e98cf4c2ed.png">

Old UI favicon

<img width="122" alt="Screen Shot 2020-04-12 at 12 42 56 PM" src="https://user-images.githubusercontent.com/11410997/79078143-26ce3c00-7cbb-11ea-8e1b-35414a12d1e1.png">

**Comment by vincent99** [comment]
I'd rather it be called and icon-ed something at least somewhat different to tell tabs apart.

Also all Ranchers have Dashboard but not all Dashboards have Rancher.  After login the window title could potentially change depending on whether Rancher is there or not...

**Comment by deniseschannon** [comment]
<img width="217" alt="Screen Shot 2020-04-23 at 10 46 04 AM" src="https://user-images.githubusercontent.com/11410997/80131826-ac6da980-854f-11ea-823f-4ddf967aa384.png">

Current dashboard tab.
