### ISSUE TITLE
UI slower than before; mouse hangs in Edge and Deployment page takes 90 seconds

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5020]
Internal reference: SURE-3754

Versions:     Component Version:
Rancher      v2.6.3-patch1
Helm           v2.16.8-rancher1
Machine      v0.15.0-rancher73

IMHO the loading from backend could be better but is like always.
But the new frontend is a mess, it takes like 3400 MB memory according to the edge browser.

And when every thing is loaded, the ui just hangs and you can't even move the mouse pointer.
e.g.: to select one Deployment on the end of the scrolling page and get the yaml, it takes about 90 seconds until I break up.

They have a large cluster, but when they change back to the old UI it is working much better.

**Comment by gaktive** [comment]
Additional reports from other users indicate that when there are more than 50 elements in a list, page loading takes far longer and the browser crashes. This may have to be separated into its own ticket.

Internal reference: SURE-4017

**Comment by gaktive** [comment]
Feedback on one environment:

> Chrome typically. Namespaces no more than 10-20. Doesn't seem to be namespace related, I notice it when there are many deployments (over 100) Problem is exacerbated by the fact that the deployments don't filter properly (as per https://github.com/rancher/dashboard/issues/5059) so you're always getting a full list of deployments returned to you

**Comment by nwmac** [comment]
@scures I think you'er on Windows - assume this is a Windows user - interested if you are able to reproduce

**Comment by nwmac** [comment]
List performance has been improved and should address performance issues in the browser

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required. Tested as part of [https://github.com/rancher/dashboard/issues/5445](https://github.com/rancher/dashboard/issues/5445)

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                                |
| ------------------------- | --------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-a6d2050e47d3b202496ad9c48d16e610be207829-head                                            |
| Rancher commit link       | [a6d2050](https://github.com/rancher/rancher/commit/a6d2050e47d3b202496ad9c48d16e610be207829) |
| Installation option       | helm high availability                                                                        |
| RKE binary version used   | v1.3.10-rc4                                                                                   |
| If Helm Chart k8s cluster | v1.22.8                                                                                       |
| Cert Details              | let's encrypt                                                                                 |
| Docker version            | 20.10.7, build f0df350                                                                        |
| Helm version              | v2.16.8-rancher1                                                                              |
| Downstream cluster type   | not applicable                                                                                |
| Downstream K8s version    | not applicable                                                                                |
| Logged in user role       | administrator                                                                                 |
| Browser type              | google chrome                                                                                 |
| Browser version           | 100.0.4896.127 (official build) (x86_64)                                                      |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --version 2.6.5-rc3 \
  --namespace cattle-system \
  --set hostname=$HOSTNAME_REDACTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_REDACTED \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=v2.6-head
```

## Validation steps

1. Run script to create 3,000 deployments & pods
2. Wait for script to complete
3. Navigate around various pages of deployments in the Rancher UI
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
With 3,000 deployments and pods, there is no lag noticed

#### :white_check_mark:Actual
With 3,000 deployments and pods, there is no lag noticed
