### ISSUE TITLE
Secrets not showing up in UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5026]
Internal reference: SURE-4000, SURE-4035

Issue description:
Local or external users, even as Cluster Owner, are not able to see secrets in the UI of a downstream cluster, but they are able to run kubectl in UI and see the secrets. Different browsers tested.

Business impact:
No impact.

Troubleshooting steps:

Screenshot evidence of the secrets not being showed up in UI at the same time of kubectl in UI are able to list the secrets.

Developer browser tool screenshots and HAR file collected.

Repro steps:

Attempts to reproduce in a lab not possible but the users were able to do it in their environment.
access the UI, select cluster, select storage/secrets

Workaround:
Is workaround available and implemented? YES
What is the workaround: Access the old UI, https://URL/g

Actual behavior:
Secrets not being shown up in UI for one downstream cluster

Expected behavior:
Being able to see the secrets in UI from a specific downstream cluster

![Screen Shot 2022-01-25 at 11.05.36 AM.png](https://zube.io/files/rancher/7a3ae3a6b9a4850afa0f62a2f1ea2bf7-screen-shot-2022-01-25-at-11-05-36-am.png)

![Screen Shot 2022-01-25 at 11.11.13 AM.png](https://zube.io/files/rancher/630616c443440a3634d595d712748ffc-screen-shot-2022-01-25-at-11-11-13-am.png)

**Comment by nwmac** [comment]
Further info: Secrets are not being shown up in UI when missing field "username" for basic-auth secret type. If you have even just one secret in this scenario, any Secrets in the namespace is showed up, even the other secrets which have Username field.

**Comment by nwmac** [comment]
I think the bug is in `detail/secret.vue` and `models/secret.js` - the `base64Decode` function should be improved to work when the value supplied is undefined

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 4a5a926
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver

----------

### Testing: ###

Tested this issue with the following steps:

1. Provision a downstream RKE2 cluster
2. Check secrets are showing in UI

**Result** - Pass

Secrets are now showing in the UI

![image.png](https://zube.io/files/rancher/c36f17b364e01c716ed24b09c2027f7b-image.png)
