### ISSUE TITLE
imagePullSecret is removed after updating workload image via Cluster Manager

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5028]
Internal reference: SURE-3579
Reported in 2.5.9 under both UIs

Issue description:
Changes to an existing deployment when editing in Cluster Manager causes the imagePullSecret to be removed from the spec, or all registry credentials appended to the imagePullSecret list. The customer has also reproduced in Cluster Explorer.

Impact:
Medium, enforcing kubectl use for image/tag changes can be used to mitigate this. If the UI is used, it can break production deployments.

Repro steps:

- Create a deployment with an imagePullSecret, I did this in the new Cluster Explorer / Dashboard which has support for this in the form editor
- Edit the same deployment in Cluster Manager, updating the container image/tag (could be other changes, but this appears to be a reliable repro)
- Once saved, check the imagePullSecret, it should be removed from the deployment spec unexpectedly, or additional (where multiple may exist in the namespace) secrets are appended.

Workaround:
Is workaround available and implemented? yes
What is the workaround: Avoid using Cluster Manager for such changes

Additional notes:
Appears to be similar and/or a regression of https://github.com/rancher/rancher/issues/18408

**Comment by nwmac** [comment]
@mantis-toboggan-md Note: this was reported against 2.5.9, so there is a possibility its been fixed

**Comment by mantis-toboggan-md** [comment]
This has been fixed. Editing deployments in either Cluster Manager or Cluster Explorer does not remove the imagePullSecret in 2.6.4
