### ISSUE TITLE
Not able to scale down/up when a node pool has just been scaled up/down

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5029]
**Rancher Server Setup**
- Rancher version: On 2.6-head commit id: da382a8
- Installation option (Docker install/Helm Chart): Helm install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: rancher generated

**Information about the Cluster**
- Kubernetes version: `v1.22.6+rke2r1`
- Cluster Type (Local/Downstream): Downstream AWS Node driver

**User Information**
- What is the role of the user logged in?  - Admin

   
**Describe the bug**
Not able to scale down/up when a node pool has just been scaled up/down

**To Reproduce**

- Provision an RKE2 cluster from Rancher with multiple nodes in the machine pools - AWS Node driver cluster - v1.22.6+rke2r1 version
- Scale up worker nodes
- Wait for the nodes to come up Active.
- Scale up the worker nodes. The nodes will start provisioning.
- Scale down the nodes.
- In the console the following error is seen.
```
Uncaught (in promise) 
{type: 'error', links: {…}, code: 'Conflict', message: 'Operation cannot be fulfilled on clusters.provisio… your changes to the latest version and try again', status: 409, …}
code: "Conflict"
links: {}
message: "Operation cannot be fulfilled on clusters.provisioning.cattle.io \"sowmya-122-2\": the object has been modified; please apply your changes to the latest version and try again"
status: 409
type: "error"
_headers: {content-encoding: 'gzip', content-length: '214', content-type: 'application/json', date: 'Wed, 02 Feb 2022 00:34:53 GMT', expires: 'Wed 24 Feb 1982 18:42:00 GMT', …}
_req: XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, onreadystatechange: ƒ, …}
_status: 409
_statusText: ""
_url: "https://server/v1/provisioning.cattle.io.clusters/fleet-default/sowmya-122-2"
[[Prototype]]: Object
```
- to get out of this situation, refresh the page and click on Scale down, and the node that is provisioning will get deleted.

**Comment by nwmac** [comment]
@richard-cox I thought Vince had put something in for this - can you take a look - we've seen this issue before on other resources.

**Comment by richard-cox** [comment]
Vince added a process where on `CreateEditView` `save` it intercepts 409 "conflict" errors, tries to understand if the conflict is genuine (i'm assuming it ignores 'status' like properties) and tries again if applicable.

Scaling node's is outside of the create/edit flow so 409 errors aren't retried.

The user is able to try again, and if at some point the server copy is the same as local (for instance when the cluster status changes calms down) then they can successfully scale without refreshing.

**Comment by Josh-Diamond** [comment]
Ticket #5209 - Test Results

With Helm on HA rancher:

Reproduced on rancher `v2.6-da382a88600d0272d48537c5de88b3ce0ede6dd3-head`:
1. Fresh install of rancher v2.6-head
2. As admin, provision an RKE2 AWS Node driver cluster, k8s `v1.22.7+rke2r2`
3. Once provisioned, scale up worker nodes in machine pool
4. Once scaled, scale up worker nodes again, however, while provisioning, scale down worker nodes
5. Reproduced - `409` status code in console

Screenshot:
![reproduced-redacted](https://user-images.githubusercontent.com/46494969/158869430-2ab20315-8b80-4d0b-bb1c-6cde0de77434.png)


Verified on rancher `v2.6-5bb08b3692ac3c18ec1361694a095e2c25eb0346-head`:
1. Fresh install of rancher v2.6-head
2. As admin, provision an RKE2 AWS Node driver cluster, k8s `v1.22.7+rke2r2`
3. Once provisioned, scale up worker nodes in machine pool
4. Once scaled, scale up worker nodes again, however, while provisioning, scale down worker nodes
5. Verified - No `409` status code, clean logs

Screenshot:
<img width="555" alt="Screen Shot 2022-03-17 at 11 06 43 AM" src="https://user-images.githubusercontent.com/46494969/158869578-72c6cef7-349e-4150-a8de-95a2d4e5db95.png">
