### ISSUE TITLE
Wrong 'type' gets populated in constraint if user chooses any other type than default. 

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#503]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable gatekeeper.
2. Create a constraint in edit form while changing the type. 
3. View constraint in yaml form.

**Result:**
Constraint is created with the type which was appearing in constraint by default. In below example kind and and type are not same.
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  annotations:
    cattle.io/description: ""
  creationTimestamp: "2020-04-13T17:02:50Z"
  finalizers:
  - finalizers.gatekeeper.sh/constraint
  generation: 1
  name: test
  resourceVersion: "926363"
  selfLink: /apis/constraints.gatekeeper.sh/v1beta1/k8srequiredlabels/test
  uid: 7d3ce42f-b4ab-4e5b-93dd-270cb1c80c8f
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
    - apiGroups:
      - ""
    labelSelector:
      matchExpressions: []
    namespaceSelector:
      matchExpressions: []
  parameters: {}
status:
  byPod:
  - enforced: true
    id: gatekeeper-controller-manager-76f7b99c4b-scrqs
    observedGeneration: 1
type: constraints.gatekeeper.sh.k8sallowedrepos
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.2
- Installation option (single install/HA): Single

**Comment by prachidamle** [comment]
@codyrancher One thing I see in the above yaml file is that there is a type added `type: constraints.gatekeeper.sh.k8sallowedrepos` which is wrongly sent by the UI in the POST request while creating the constraint. Seems like an issue with toggling the "template" on the form

1. First I created a constraint using template "k8sallowedrepos"
2. It got created fine 
3. Then I created another constraint and toggled the template to "k8srequiredlabels". But the data that is sent in the http POST by the UI still sent the "type" as "constraints.gatekeeper.sh.k8sallowedrepos"

```
{"type":"**constraints.gatekeeper.sh.k8sallowedrepos**","spec":{"parameters":{},"match":{"kinds":[{"apiGroups":[""]}],"excludedNamespaces":[],"labelSelector":{"matchExpressions":[]},"namespaceSelector":{"matchExpressions":[]}},"enforcementAction":"deny"},"metadata":{"name":"**label**","annotations":{"cattle.io/description":null}}}
```

**Comment by khushboo-rancher** [comment]
Verified in latest master, type is getting populated as template selected while creating constraint.

Steps:
1. Click create constraint.
2. Change the template value and save.
3. Verified in yaml view. Type is getting updated as per template selected.
