### ISSUE TITLE
[Bug] Create resource button not present on list pages for resources which rancher does not have a custom UI

### ISSUE THREAD

**Issue by ebauman** [rancher/dashboard#5034]
**Setup**
- Rancher version: v2.6.3
- Browser type & version: Both Chrome and Firefox latest

**Describe the bug**

The "Create" button is not present on the list pages of custom resources. 

**To Reproduce**

View the list page of any custom resource. Or, any resource for which Rancher does not have a custom UI. 

**Result**
The "Create" button (or even "Create from YAML") is not present. 

**Expected Result**

Because the user should have create (or, REST POST) permissions, the button should be present. It is not.

**Comment by bashofmann** [comment]
Should be fixed with https://github.com/rancher/dashboard/issues/4995.

**Comment by nwmac** [comment]
Can someone verify that this is fixed.

**Comment by catherineluse** [comment]
Yes it was fixed - verification steps in this comment https://github.com/rancher/dashboard/issues/4995#issuecomment-1026453512

I also just confirmed that the Pod resource has a Create from YAML button even though there's no form.

**Comment by sowmyav27** [comment]
Create from Yaml is present in 2.6-head commit id: `4df2214` for NetworkPolicies resource .

On 2.6.3, this was not available
