### ISSUE TITLE
Improve presentation of some controls when in view mode

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5035]
Goto a resource such as a deployment in the local cluster (change the namespace filter to 'All Namespaces), go to Workload > Deployments. Click on one of the deployments and click on the 'Config' button in the top right (next to Detail).

This shows a readonly version of the configuration - it uses the same form controls that are used when editing, but we use the` mode` param, setting it to `view`.

![image](https://user-images.githubusercontent.com/1955897/152309704-e675688a-595e-4b82-abba-3e73f605293c.png)

Some of the controls don't adjust their appearance correctly for the view mode - generally they use the disabled state to prevent editing of the control, but for some controls, they should hide additional elements:

- On the General Tab -> Environment Variables, the 'Add Variable` button is shown, even though its read only - this should be hidden
- On the General Tab -> Service Account Name - the Clear button is shown, even though its read only - this should be hidden

example of these two:

![image](https://user-images.githubusercontent.com/1955897/152311030-cd667a3e-91bb-4f78-a110-1e999883b782.png)

- On the Labels & Annotations Tab -> Labels (or Annotations) - the Remove button is shown at the right of each row,  even though its read only - this should be hidden
- On the Pod Scheduling Tab -> the Add Node Selector button is enabled - it should not be in view mode - it should be hidden. Additionally, when there are no node selectors, we should show a message indicating that (otherwise the view is just empty)

![image](https://user-images.githubusercontent.com/1955897/152310331-3abdeeec-3749-4436-a535-af71a56c1d27.png)

Some of the fixes for these view mode issues are in common form components, so fixing them there will fix them when they are used in other places.

**Comment by cnotv** [comment]
It may be worthy to add the following to the `side-tabs > tabs` to improve UX navigation:
https://github.com/rancher/dashboard/tree/master/components/TabbedLinks/index.vue
```scss
    position: sticky;
    align-self: flex-start;
    top: 0;
```

**Comment by cnotv** [comment]
Pod scheduling -> remove pod button has been hidden as well, as we dont want to remove them in view mode.

**Comment by Auston-Ivison-Suse** [comment]
**Rancher Setup For validation**
rancher version: v2.6-head(978e165)

**Areas Validated**
- Pods
- Deployments
- Jobs
- StatefulSets
- CronJobs
- DaemonSets

**Results of Validation**
In the above areas when I viewed the configs of each type of workload I didn't come across any buttons.
Which improves the readability of what we are looking at. 

**Screenshots**

![PodSchedulingViewOnly.png](https://zube.io/files/rancher/73137d579ca231a49c444c4aa4b182a5-podschedulingviewonly.png)

![EnvironmentVariableViewOnly.png](https://zube.io/files/rancher/f0483169825ae2b6825b2016e2d41654-environmentvariableviewonly.png)

![LabelsAnnotationsViewOnly.png](https://zube.io/files/rancher/2a6db8369cc0c18ec83a886f1ae3e22f-labelsannotationsviewonly.png)
