### ISSUE TITLE
Add ability to create/edit nav link

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5047]
Nav lInks allow users to add custom navigation links into the side navigation of the explorer UI.

These are represented as a Kubernetes resource - `ui.cattle.io.navlink`. See https://rancher.com/docs/rancher/v2.6/en/admin-settings/branding/ (Custom Navigation Links") for documentation.

You can already create these from the UI via the YAML editor if you manually search for the resource.

This issue is about adding a form for the Nav Link resource, so that users can create/edit these more easily.

- Add the NavLink resource to the Page Actions menu - i.e. in this menu:

![image](https://user-images.githubusercontent.com/1955897/152504044-e227e237-cbb6-44e3-8256-4149b79e3124.png)

- Create an edit page for the `ui.cattle.io.navlink` resource and create a form in it for editing the fields of the resource (see: https://github.com/rancher/dashboard#customizing-how-k8s-resources-are-presented)

Most of the fields are straight-forward - it should be obvious from the documentation what field to use for each.
There are two choices for specifying the destination for the link - URL and Service. URL is straight forward. Service has more options - for now, we can just use input boxes for those - but it would be nice if you could select an existing service, but that's a stretch goal.

**Comment by vincent99** [comment]
These are a per-cluster resource that live in and are displayed on only that cluster; not a global setting.

Forms for manipulating them might be of some use to someone, but the main audience for them is as a resource deployed by a helm chart.

**Comment by nwmac** [comment]
Thanks Vince - spotted that they weren't global.

**Comment by cnotv** [comment]
Should we consider displaying other [table headers](https://github.com/rancher/dashboard/blob/master/docs/developer/getting-started/development.md#customisation)? I imagine we do not have a real active/inactive state, plus probably we want to skip `label` and display other information, e.g. description?

![Screenshot from 2022-02-08 12-05-32](https://user-images.githubusercontent.com/5009481/152975145-b7086535-a12f-41d6-b213-806fff14fbf1.png)

**Comment by cnotv** [comment]
As mentioned in the daily, would you rather handle an image uploader with separated buttons or something more custom as in the following images?

![image_upload](https://user-images.githubusercontent.com/5009481/153466270-b18d51e8-6a1a-4a78-ab43-9281fa81bd39.jpg)

**Comment by cnotv** [comment]
After talking to @kwwii , we finally agreed in keeping the navigation unchanged till a major refactoring occurs, if required.

**Comment by ronhorton** [comment]
**Pass** Verified in `2.6-head Commit ID 20d20a3`

1. Explore an existing cluster
2. click the search in the upper right corner
3. enter 'navlinks'
4. select navlinks
5. create

Images above the allowed limit do not save and do not error - adding that check is out of scope for this ticket
<img width="1257" alt="Screen Shot 2022-02-22 at 11 24 43 AM" src="https://user-images.githubusercontent.com/89212856/155175482-61c982aa-c2d8-4d53-b59c-de9d34090f0e.png">

<img width="1258" alt="Screen Shot 2022-02-22 at 11 24 20 AM" src="https://user-images.githubusercontent.com/89212856/155175520-4746d064-3eee-46a6-b6a6-e5469ff5f5c9.png">
