### ISSUE TITLE
Cancel & Save don't work in edit Workload

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#505]
Steps:
1.  Create a workload
2.  Edit as Form the workload you just created
3.  Click Cancel (nothing happens)
4.  Click on Save (nothing happens).

Results:  Both buttons should go back to the list page.  Of course save should save first.  Cancel should get rid of any changes

**Comment by deniseschannon** [comment]
With the changes in workloads, I don't think is still an issue, but can you double check @tfiduccia ?

**Comment by tfiduccia** [comment]
Verified
