### ISSUE TITLE
[Catalog V2 UI] On installing a chart, OS and arch annotations should be respected

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#5055]
Note: Annotations will be introduced to all charts by the backend team, as prescribed in https://github.com/rancher/rancher/issues/36401. 

Note: This issue should not be validated by QA until the backend issue is complete; however, UI can proceed with the changes assuming the defaults for these annotations described in the original ticket for all current charts.

#### UX Change

When a user visits the chart installation page for a specific chart, the Rancher UI should grab:
- Set of all OSs currently running on nodes in this cluster (`hasOS`)
- Set of all archs used by nodes in this cluster: (`hasArch`)

For this particular chart:
- Get the values of the `catalog.cattle.io/permits-os` annotation (`permitsOS`)
- Get the values of the `catalog.cattle.io/permits-arch` annotation (`permitsArch`)
- Validate that `hasOS` is a subset of `permitsOS`; if not, **show an overridable error that this chart is not permitted to be deployed onto a cluster with nodes running this OS**.
- Validate that `hasArch` is a subset of `permitsArch`; if not, **show an overridable error that this chart is not permitted to be deployed onto a cluster with nodes on this arch**.
- Get the values of the `catalog.cattle.io/deploys-on-os` annotation (`requiresOSValue`)
- Get the values of the `catalog.cattle.io/deploys-on-arch` annotation (`requiresArchValue`)
- For each `$os` in `requiresOSValue`, set `global.cattle.$os.enabled=hasOS[$os]`
- For each `$arch` in `requiresArchValue`, set `global.cattle.$arch.enabled=hasArch[$arch]`

**Comment by aiyengar2** [comment]
note: I edited the issue description to use `catalog.cattle.io/deploys-on-os` instead of `catalog.cattle.io/os` since `catalog.cattle.io/os` has an older definition that would break older Rancher setups if we choose to modify what it means.

Description should be up-to-date now with the expectations.

**Comment by luthermonson** [comment]
This issue is going to be superceded by a previous dashboard issue which captures everything and has all PRs linked up. You can see context https://github.com/rancher/dashboard/issues/5137#issuecomment-1062323770
