### ISSUE TITLE
[Catalog V2 UI] On viewing installed charts, OS and arch annotations should be respected

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#5057]
Note: Annotations will be introduced to all charts by the backend team, as prescribed in https://github.com/rancher/rancher/issues/36401. 

Note: This issue should not be validated by QA until the backend issue is complete; however, UI can proceed with the changes assuming the defaults for these annotations described in the original ticket for all current charts.

#### UX Change

When a user visits the Installed Apps pages, the Rancher UI should grab:
- Set of all OSs currently running on nodes in this cluster (`hasOS`)
- Set of all archs used by nodes in this cluster: (`hasArch`)

For each chart:
- Get the values of the `catalog.cattle.io/permits-os` annotation (`permitsOS`)
- Get the values of the `catalog.cattle.io/permits-arch` annotation (`permitsArch`)
- Validate that `hasOS` is a subset of `permitsOS`; if not, **mark chart as broken in red saying this chart is not permitted on clusters containing nodes running OS**.
- Validate that `hasArch` is a subset of `permitsArch`; if not, **mark chart as broken in red saying this chart is not permitted on clusters running nodes based on ARCH**.
- Get the values of the `catalog.cattle.io/deploys-on-os` annotation (`requiresOSValue`)
- Get the values of the `catalog.cattle.io/deploys-on-arch` annotation (`requiresArchValue`)
- For each `$os` in `requiresOSValue`, check the value of `global.cattle.$os.enabled`
  - If the value of `global.cattle.$os.enabled=true` but `hasOS[$os]=false`: **mark chart as one that needs an upgrade to remove components targeted for $os**
  - If the value of `global.cattle.$os.enabled=false` but `hasOS[$os]=true`: **mark chart as one that needs an upgrade to add components to be deployed on $os**
- For each `$arch` in `requiresArchValue`, check the value of `global.cattle.$arch.enabled`
  - If the value of `global.cattle.$arch.enabled=true` but `hasArch[$arch]=false`: **mark chart as one that needs an upgrade remove components targeted for $arch**
  - If the value of `global.cattle.$arch.enabled=false` but `hasArch[$arch]=true`: **mark chart as one that needs an upgrade to add components to be deployed on $arch**

**Comment by aiyengar2** [comment]
note: I edited the issue description to use `catalog.cattle.io/deploys-on-os` instead of `catalog.cattle.io/os` since `catalog.cattle.io/os` has an older definition that would break older Rancher setups if we choose to modify what it means.

Description should be up-to-date now with the expectations.

**Comment by sowmyav27** [comment]
validated as part of https://github.com/rancher/dashboard/issues/5137
