### ISSUE TITLE
[Provisioning V2 UI, RKE2] On provisioning a new node, a warning should show if this can break apps

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#5058]
Note: Annotations will be introduced to all charts by the backend team, as prescribed in https://github.com/rancher/rancher/issues/36401. 

Note: This issue should not be validated by QA until the backend issue is complete; however, UI can proceed with the changes assuming the defaults for these annotations described in the original ticket for all current charts.

#### UX Change

When a user tries to provision a new node, the Rancher UI should grab:
- Set of all OSs currently running on nodes in this cluster (`hasOS`)
- Set of all archs used by nodes in this cluster: (`hasArch`)

If the current OS or arch that will be added is already tracked in `hasOS` or `hasArch`, no further steps are required.

If not, we should show a warning that says adding this node could potentially break existing apps in your cluster or may require them to be upgraded in place, so after provisioning a user should navigate to the Installed Apps page and ensure that no apps show warnings.

Dependent on https://github.com/rancher/dashboard/issues/5057, which will show a user what broke as a result of the addition.

**Comment by aiyengar2** [comment]
note: I edited the issue description to use `catalog.cattle.io/deploys-on-os` instead of `catalog.cattle.io/os` since `catalog.cattle.io/os` has an older definition that would break older Rancher setups if we choose to modify what it means.

Description should be up-to-date now with the expectations.

**Comment by phillipsj** [comment]
# Rancher Version

v2.6-head b26b920

# Steps:
1. Create a Custom cluster for RKE2 using 1.22.7
2. Add one linux controlplane and one linux worker
3. Deploy chart from apps and marketplace, I picked CIS Bencharks chart
4. Go back to cluster management and register a Windows worker node

# Outcomes

Expected to see a warning when adding the Windows node for provisioning. No warning was given.

![image](https://user-images.githubusercontent.com/1568133/157334524-d2e8cc4e-4212-4f9a-83d7-ee9d0af6c3ae.png)

**Comment by luthermonson** [comment]
This issue is going to be superceded by a previous dashboard issue which captures everything and has all PRs linked up. You can see context https://github.com/rancher/dashboard/issues/5137#issuecomment-1062323770
