### ISSUE TITLE
Description is missing from Workload details page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#506]
Steps:
1.  Create a workload with a description
2.  Click on workload name to get to details page

Results:  Workload is missing the Description in the details page.  Should go right after namespace.
![image](https://user-images.githubusercontent.com/11514927/79155938-c86e8f80-7d86-11ea-8253-a973608526da.png)

Comments:  @lvuch I don't think we are going to be able to show all the info for workloads on a single line.  It's already getting crowded.  I think even for details we are going to have to go to a 3x3 or something like we do in Overview page.

**Comment by deniseschannon** [comment]
Description was moved to `masthead` in this issue so this is no longer relevant. https://github.com/rancher/dashboard/issues/538
