### ISSUE TITLE
Typo in "auth providers"

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5060]
Setup

Rancher version: 2.6-head 948355c
Browser type & version: Chrome

**Describe the bug**
There is a typo in the Auth Provider from Users & Authentication --> Auth Providers 
Should be Auth Providers 

<img width="246" alt="2022-02-04_16-01-02" src="https://user-images.githubusercontent.com/38144301/152618933-2d3ea743-a4d2-4c50-8b41-5ea77b279afd.png">

**Comment by nwmac** [comment]
@scures Should be an easy fix - but a good first PR?!

**Comment by nwmac** [comment]
@scures Looks like someone else fixed this but did not move the issue in Zube.

**Comment by sowmyav27** [comment]
**In 2.6-head commit id: `d4089da`**

Typo is fixed.
<img width="518" alt="Screen Shot 2022-02-21 at 2 27 20 PM" src="https://user-images.githubusercontent.com/26032343/155033281-fafcec7d-4b63-4271-9344-e02c1c002cb3.png">
