### ISSUE TITLE
Create create/edit view for Service Account resource type

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5064]
Service Accounts can be viewed by clicking on the search icon and searching for 'ServiceAccount':

![image](https://user-images.githubusercontent.com/1955897/152822739-affa70cd-102b-4341-9c12-72f7a2289018.png)

Currently there is a list view and YAML creation.

This ticket is about adding a form to create/edit/view SAs using the standard approach.

You should create a page in `edit/serviceaccount.vue` and create a form for this resource, with:

- Name & Description
- Checkbox for the `automountServiceAccountToken` field
- Standard Labels and Annotations control
- Control to allow one or more secrets to be specified as 'imagePullSecrets' - see the docs

Docs: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#serviceaccount-v1-core

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                                |
| ------------------------- | --------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-a6d2050e47d3b202496ad9c48d16e610be207829-head                                            |
| Rancher commit link       | [a6d2050](https://github.com/rancher/rancher/commit/a6d2050e47d3b202496ad9c48d16e610be207829) |
| Installation option       | helm high availability                                                                        |
| RKE binary version used   | v1.3.10-rc4                                                                                   |
| If Helm Chart k8s cluster | v1.22.8                                                                                       |
| Cert Details              | let's encrypt                                                                                 |
| Docker version            | 20.10.7, build f0df350                                                                        |
| Helm version              | v2.16.8-rancher1                                                                              |
| Downstream cluster type   | not applicable                                                                                |
| Downstream K8s version    | not applicable                                                                                |
| Logged in user role       | administrator                                                                                 |
| Browser type              | google chrome                                                                                 |
| Browser version           | 100.0.4896.127 (official build) (x86_64)                                                      |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --version 2.6.5-rc3 \
  --namespace cattle-system \
  --set hostname=$HOSTNAME_REDACTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_REDACTED \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=v2.6-head
```

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Create a new secret
   - Click `hamburger menu` -> `local` -> `Storage` -> `Secrets` -> `Create` -> `Registry`
   - Fill out the form
     - Namespace: `default`
     - Name: `my-secret`
     - Data: `DockerHub`
     - Username: `<your-docker-hub-username>`
     - Password: `<your-docker-hub-password>`
     - Click `Create`
3. Create a new service account
   - Click `hamburger menu` -> `local` -> `More Resources` -> `Core` -> `Service Accounts`
   - There is a new `Create` button, click it
   - Fill out the form
     - Namespace: `default`
     - Name: `my-service-account`
     - `Check`: `Automount Service Account Token`
     - Image Pull Secret: `my-secret`
     - Click `Create`
4. Create a deployment with one of your private docker images
  
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Service account creation is successful and works with creating a workload from private docker image

#### :white_check_mark:Actual
Service account creation is successful and works with creating a workload from private docker image
