### ISSUE TITLE
Generic drivers page not listing all options

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5065]
In the midst of a walkthrough of showing how RKE2 drivers are made, @vincent99 found that on the generic drivers page, we should expect to see all the possible options but they're not all appearing.

**Comment by sowmyav27** [comment]
Reproduce Issue on 2.6.3 - 
- Deploy OCI RKE2 cluster and notice the issue

On 2.6-head
- Deploy OCI RKE2 cluster and notice the issue
- The UI should have the questions nw as mentioned [here](https://github.com/rancher/dashboard/pull/5101)
- Create RKE2 cluster. Cluster should come up Active.

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Reproduction**
Rancher: v2.6.3
Cluster: (downstream)
- oci node driver

**Reproduction Steps**
1. create OCI RKE2 cluster
2. Witness the options not available

**Setup For Validation**
Rancher: v2.6-head(e93a53c)
Cluster: (downstream)
- Ocie node driver

**Validation Steps**
1. Brought up a OCI cluster and witnessed the expected results where the chart name now appears as `:chart-name="chartName"` in the dev tools.
