### ISSUE TITLE
Unable to change default role via UI after configuring ADFS authentication

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5066]
Internal reference: SURE-4020
Reported in 2.6.2 and 2.6.3

*Issue description:*
 Unable to change default role via UI after configuring ADFS authentication

*Business impact:*
 Unable to assign default roles to users

*Repro steps:*
 * Install Rancher v2.6.2
 * Configure ADFS authentication
 * Go to Roles -> Global Role -> Standard User -> Edit Config -> Select "No" for "New User Default"

![image-2022-02-03-12-34-41-619.png](https://zube.io/files/rancher/c6fa08d590dca1aaaa521813182e84e6-image-2022-02-03-12-34-41-619.png)

*Workaround:*
 Is a workaround available and implemented? Yes
 What is the workaround: Use Old UI via "https://<rancher_fqdn>/g"

*Actual behavior:*
 New UI is not allowing default roles change

*Expected behavior:*
 UI should allow default role change

**Comment by nwmac** [comment]
Same issue as https://github.com/rancher/dashboard/issues/4992

**Comment by gaktive** [comment]
Zube keeps adjusting the milestone for some reason. @sowmyav27 just a heads-up that this is in 2.6.4.

**Comment by brudnak** [comment]
Validated in https://github.com/rancher/dashboard/issues/4992. ADFS not needed for checks.
