### ISSUE TITLE
Custom Favicon in cluster explorer

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5067]
Internal reference: SURE-3137
Reported in 2.5.x

Issue description:
Trying to push image changes to cluster-explorer via updating the path 
`-v /path/to/your/logos:/usr/share/rancher/ui-dashboard/dashboard/_nuxt/assets/images/pl`  
as per the instructions in https://github.com/rancher/dashboard/tree/master/assets/images/pl. 

However this doesn't seem to work unless the cu mounts 
`-v /path/to/your/logos:/usr/share/rancher/ui-dashboard/dashboard`, 
this is filled with .js files and they are probably important for the UI. 

Business impact:
Low

Troubleshooting steps:
Launch Rancher container image with option `-v /path/to/your/logos:/usr/share/rancher/ui-dashboard/dashboard/_nuxt/assets/images/pl` and point to a custom folder with the desired images.

**Comment by brownz11** [comment]
Reached out in the Slack and was pointed to this issue.

Wanted to drop a comment saying we're interested in having a way to do this, either through the UI or even just a setting we can stuff a encoded image into.

We deploy Rancher via Helm

Our main use case would be making life a bit easier when trying to find the tab for which Rancher instance we need. We run multiple instances for various reasons and often have 2 or more open in tabs.

**Comment by nwmac** [comment]
The favicon is currently not easily configurable via this mechanism.

**Comment by slickwarren** [comment]
note: `-v /path/to/your/logos:/usr/share/rancher/ui-dashboard/dashboard/_nuxt/assets/images/pl` will not be supported, in favor of the above PRs. 
Tested the favicon updates on 2.6-head (328b12b):
* new UI option `favicon` under `global settings` -> `branding` allows user to upload a small image to use as favicon -- pass
* removal of favicon defaults to rancher image -- pass
* checking favicon box but not uploading an image defaults to rancher image -- pass
* non-admin users can see favicon changes reflected in their browser -- pass
![Screen Shot 2022-06-23 at 10 52 25 AM](https://user-images.githubusercontent.com/16691014/175375901-18874326-f716-4fe1-afdd-b002703b396e.png)
