### ISSUE TITLE
Can not group pod list by node

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5073]
In cluster manager you can see the list of pods, grouped by the node that each is on. You can't do this in dashboard.

![image](https://user-images.githubusercontent.com/1955897/153004750-9db1145f-8c16-42fa-9ff4-80c18c3e17dd.png)

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6-head 58e374f
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1 ec2 node driver (3 worker nodes)
Downstream K8s version: v1.22.6

----------

### Testing: ###

1. Create a deployment with a few replicas 
2. Navigate to Workloads -> Pods
3. Group pods by Node 

result: UI groups pods by node (correctness checked via `kubectl`)
![group by node](https://user-images.githubusercontent.com/40282141/156245355-96fc279a-28b5-4a75-bfd3-02cc5390c332.jpg)

checked sorting when pods are grouped by nodes
checked grouping by nodes with no filters applied (with pods in all/different namespaces)
![different namespace](https://user-images.githubusercontent.com/40282141/156247819-56524100-41b0-4b58-9ed0-b33d7a8c323e.jpg)
