### ISSUE TITLE
Namespace view does not provide detail for the summary pills

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5074]
See below.

Where resources are not in the correct state, we do not provide any information as to why something is in error or transitioning.

Also, the example here shows the Active state twice.

![image](https://user-images.githubusercontent.com/1955897/153008562-99d294c2-f31a-41ad-927a-9d4ad26d4e70.png)

**Comment by nwmac** [comment]
Suggest we add a first tab 'Resources' which shows the resources in the namespace - ordered by the resource severity - i.e. the error ones first, warnings, transitioning, etc, active ones last

We have a resources table elsewhere, so we should be able to use that

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.6.3**
<img width="1679" alt="Screen Shot 2022-02-24 at 10 00 38 AM" src="https://user-images.githubusercontent.com/26032343/155581767-2d5c5029-1d0c-4ed8-a6c1-d9add425c399.png">

**On 2.6-head commit id: `8c785a1`**

- `Resource` tab is added, and columns - error, warning, transitioning, unknown, Active are seen
- Active state is seen only one time
<img width="1441" alt="Screen Shot 2022-02-24 at 10 02 20 AM" src="https://user-images.githubusercontent.com/26032343/155581754-e4aa45d6-97ba-449d-8300-1a797159ed64.png">
