### ISSUE TITLE
Helm UI does not have any bread crumb to logs of the deployment

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5079]
Internal reference: SURE-4016
Reported in 2.6.3

Within the Helm UI, there's no way to connect the logs of a deployment during a session. 

The new UI spawns a container to and will show you the logs of said deployment, but theres no way to navigate to the app and see logs from the past runs once you've navigated away.

**Comment by gaktive** [comment]
Comment from user:

> Looks related but I'm simply not seeing certain resources that are part of a Helm release (PVs PVCS, etc). Also, when the Helm chart fails, nothing shows up. In the old UI, you would still see everything and it would show you the "Deployment" failed or the "Ingress" failed. This was very useful. The old UI (despite being janky and not ideal) would persist the helm error in the top of the app UI. Now there's no way to see that.

**Comment by nwmac** [comment]
On the detail view for an application, e.g.

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/1955897/153832896-305c50b0-b6a3-4ab0-8124-07a8e5b4244d.png">

Add details for the last Helm operation for the application. Find all of the Helm operation resources - type `catalog.cattle.io.operation` and find the ones for the application being viewed - the `status.releaseName` and `status.namespace` must match `metadata.name` and `metadata.namespace` of the `catalog.cattle.io.app` resource.

You should then sort those matching operations and show only the latest operation - showing on a single line:

Last Operation (Install) - View Logs

Where `View Logs` is a link that when clicked will show the log for that operation - the model for the operation should have an action that will do this, so you should just need to invoke that.

`Install` should be replaced with whatever the action is from the operation resource.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `4df2214`**
<img width="1620" alt="Screen Shot 2022-03-07 at 7 08 25 AM" src="https://user-images.githubusercontent.com/26032343/156953432-09b09fff-d90d-4f9e-a2d8-e26f6de3f607.png">

`Last Operation: ( upgrade ) - [View Logs]()` is seen on the Installed Apps page after an upgrade on CIS Benchmark. is performed.
