### ISSUE TITLE
UI Issues with Nodes

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#508]
- [ ] Put space between each type of role in Roles column (if all three can we say all?)
![image](https://user-images.githubusercontent.com/11514927/79163401-d8d93700-7d93-11ea-9d7d-b8efb581f722.png)

- [ ] Change Node Titles to only include:  State, Name, Internal/external IP, kubelet version/docker verion, CPU, RAM & Pods.

Old Ember UI:
![image](https://user-images.githubusercontent.com/11514927/79806521-76e17a00-831d-11ea-91f1-190c9c871063.png)

New UI that needs modifying:
![image](https://user-images.githubusercontent.com/11514927/79163599-41281880-7d94-11ea-89d1-1677876982c1.png)

- [ ] Node details info for pressure & kubelet are using an x when green instead of a checkmark.
![image](https://user-images.githubusercontent.com/11514927/79806597-a5f7eb80-831d-11ea-800a-e427eb613ad1.png)

- [ ] Section section seems unnecessarily large.  The line is also connecting to the top section.
![image](https://user-images.githubusercontent.com/11514927/79807872-05a3c600-8321-11ea-83a6-24150a3e5d9a.png)

**Comment by deniseschannon** [comment]
Consolidated these requests into this comment: https://github.com/rancher/dashboard/issues/262#issuecomment-619283862
