### ISSUE TITLE
Component Status pills missing from cluster dashboard view

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5085]
In Cluster Manager, we showed health pills to reflect component status:

![image](https://user-images.githubusercontent.com/1955897/153365052-632d2182-641e-45bd-a61f-4509929dfc9e.png)

In the dashboard, you only see this when v1 monitoring is enabled - we should add this back in.

**Comment by vincent99** [comment]
These are not based on monitoring, componentStatus is a field on the cluster.  But it doesn't exist in some distributions and always says unhealthy in some others.  And it's deprecated and probably totally removed in newer k8s versions.  So this was intentionally not added to vue.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `d4089da`**

<img width="1446" alt="Screen Shot 2022-02-21 at 11 36 47 AM" src="https://user-images.githubusercontent.com/26032343/155031981-5ccd161e-48d3-4eb1-96c0-c5274057d807.png">

@nwmac There is n status for `Nodes` available in the cluster Dashboard. Is this expected?

**Comment by nwmac** [comment]
@sowmyav27 The nodes status will be shown in the existing nodes box, so we did not replicate that with the pills, as we'd be showing the same info twice.
