### ISSUE TITLE
Show pod restarts for a workload

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5086]
Cluster Manager shows pod restarts for workloads in the list and detail views for workloads.

Dashboard does not currently provide this - but this is useful for identifying workloads that are having issues.

**Comment by nwmac** [comment]
Ember:

![image](https://user-images.githubusercontent.com/1955897/158359434-1f437bf2-7b54-47de-8b25-5b85533f5877.png)

Shows Pod Restarts in the Image column.

**Comment by catherineluse** [comment]
In Steve, the `restartCount` doesn't come with the data for each container like it did in Norman.

It must be in there somewhere because according to the Kubernetes API reference, it's under `PodStatus.containerStatuses.restartCount`. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/ But this is harder to get. Steve gives us the Pod specs for each workload, but not their status data.

I think the cleanest solution would be to ask the backend to change the Steve API for workloads to provide the `restartCount` for each container along with the rest of the workload data, like Norman did. I'll open a backend ticket.

**Comment by nwmac** [comment]
@catherineluse I do see the restartCount on the containerStatuses of the pods. If you look at the pods list, we show the restarts for each pod and if you go into a pod you will see the per-container restart count - so the data is there, I believe.

To add it to workloads, e.g. a deployment, we need to use the selectors to find the pods that match that workload/controller and sum up the restarts for all of those pods to give the total restart count for all of the pods belonging to that workload. We already find the pods for a workload in the WorkloadScaleHealth component.

**Comment by catherineluse** [comment]
Ok, I'll try that and close the backend issue.

**Comment by igomez06** [comment]
**Setup**:
Rancher Version: v2.6.5-rc6
Kubernetes Version: RKE2 v1.22.8+rke2r1
HA Install

**Steps**:
1. Created a deployment workload
2. Check workloads section my cluster, and the pod restarts now shows up in the detail views for workloads.

![Screen Shot 2022-05-02 at 2.11.39 PM.png](https://zube.io/files/rancher/d3173093ad91aa9466a079b601fd7981-screen-shot-2022-05-02-at-2-11-39-pm.png)

**Comment by igomez06** [comment]
Is it expected that won't show in the list view? 

![Screen Shot 2022-05-02 at 2.12.36 PM.png](https://zube.io/files/rancher/695b0e545d808d84352f2bcc0a4d6ddf-screen-shot-2022-05-02-at-2-12-36-pm.png)

**Comment by gaktive** [comment]
Looks like the list view was missed. 

Based on @catherineluse's work on other 2.6.5 work, I'll need to find someone to jump on this for this release. Hopefully the code is modular enough for some quick work.

**Comment by jordojordo** [comment]
@nwmac Should the restarts be shown on every list page for each Workload type? (e.g. cronjobs, daemonsets, deployments...)

**Comment by catherineluse** [comment]
The code to get the pod restart count is now on the workload model:

```
get restartCount() {
    const pods = this.pods;

    let sum = 0;

    pods.forEach((pod) => {
      if (pod.status.containerStatuses) {
        sum += pod.status?.containerStatuses[0].restartCount || 0;
      }
    });

    return sum;
  }
```

So for the workload list view it can be retrieved from the model.

**Comment by catherineluse** [comment]
It's on the detail rage for each workload type so I'd say it should be on each list view as well.

**Comment by igomez06** [comment]
**Setup:**
Rancher Version: v2.6-head commit: 5e1bfc06d6be06a91236663a154b155d14da0a8c
Kubernetes Version: RKE2 v1.22.8+rke2r1
HA Install

**Steps:**
1. Created a deployment workload
2. Check workloads section my cluster, and the pod restarts now shows up in the list and detail views for workloads.

list view: ![Screen Shot 2022-05-04 at 1.49.33 PM.png](https://zube.io/files/rancher/49d00d5b688dd55ac6815d2fc22cebfb-screen-shot-2022-05-04-at-1-49-33-pm.png)

detail view: ![Screen Shot 2022-05-04 at 1.50.02 PM.png](https://zube.io/files/rancher/ca3db6b9d72eaa2ce06fecbb108b9dda-screen-shot-2022-05-04-at-1-50-02-pm.png)
