### ISSUE TITLE
Allow global search for labels and resource names

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5091]
From Vince's idea:

 If you click the magnifying glass in the top nav bar of Cluster Explorer, you should be able to search for a name or label such as `app=foo` and see things with that label.

This will requires backend support, but Steve already has the information in memory.

**Comment by catherineluse** [comment]
Eamon suggested allowing a search by API group as well https://github.com/rancher/dashboard/issues/5033

**Comment by catherineluse** [comment]
SURE-4780

**Comment by catherineluse** [comment]
https://github.com/rancher/dashboard/issues/2539#issue-832103885

**Comment by nwmac** [comment]
Requires backend support - closing for now
