### ISSUE TITLE
Add growls to notify user when connection is lost

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5093]
QA has noticed that when self-signed certs are used for Rancher, the UI doesn't update correctly. This is often caused because when you use self-signed certs, Google Chrome can decide that the cert is invalid after a period of time, causing connection problems.

Vince said the Ember UI had growls to notify a user when the connection is lost. A similar growl should be added to the dashboard so that users will be warned that the UI might not function correctly due to a connection problem.

**Comment by mantis-toboggan-md** [comment]
Reopened to handle scenarios where a websocket connection is lost then immediately reconnects: this causes a notification to flash too fast to read. Adding a timeout to the growl of a few seconds should be sufficient to resolve this.

**Comment by sowmyav27** [comment]
Reopening this for QA validations

**Comment by Josh-Diamond** [comment]
Ticket #5093 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-2587e6a79e4778cfbe41c9e5d6e9d70e2ea0754b-head`:
1. Create an instance in AWS
2. Fresh install of rancher `v2.6-head`
3. With access to a stop-watch or timer, from AWS console, select `instance > actions > stop instance` and observe the time it takes for growl to appear in rancher UI
4. Verified - precisely 10 seconds after stopping the instance, the growls appeared and were readable;
