### ISSUE TITLE
Add CRD for creating a custom driver

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5096]
From Vince's idea:

The Ember UI had a feature where you could create a custom driver from the UI. In the dashboard UI, you would have to create a pull request to the dashboard to add a custom driver.

If the dashboard UI adds this feature, it should not use Ember's implementation, because it depended on external links that could potentially break. If the dashboard includes this feature, it would be better to do the following:

- Create a CRD that says where the tarball is for information about the form for the custom driver. (This is the same information that Ember linked to.)
- The server side should download it, verify it with a checksum, and then serve it locally.

**Comment by nwmac** [comment]
This will be achievable via extensions
