### ISSUE TITLE
Overview's download yaml option not working

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#510]
Steps:
1.  Go to Overview page
2.  Click on Download yaml from the menu option

Results:  looks like nothing happened.  There is an error in console:
resource-instance.js:448 Uncaught (in promise) Error: Unknown link view on management.cattle.io.cluster c-bp4fc

**Comment by westlywright** [comment]
The download button will be removed for the cluster right now because this is a yaml based action. Yaml based actions rely on the resource having a link in the links collection for `view` or `rioview`. Ive added checks that disable these actions if they do not exist and they do not for clusters.

**Comment by tfiduccia** [comment]
Fixed
