### ISSUE TITLE
Project Members List Empty when there are over 1000 member bindings

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/dashboard#5104]
**Setup**
- Rancher version: v2.6.3
- Browser type & version: Chrome 98.0.4758.80 and Safri 15.3

**Describe the bug**
When navigating to the Config screen of a project to manage members the members list is always empty. Usually there is always the one member who created the project but then we add more. Even after adding a member (add and then save) the UI members list for that project is still blank.

**To Reproduce**
Navigate to Projects config screen. Add a project member or two. Click Save.

**Result**
 The Members list is empty.
The users can navigate to the project and access it which means the rolebinding is added but the UI never reflects it.

**Expected Result**
User binding that is added is shown in the UI.

**Screenshots**
Project Screen in new dashboard UI
![Screen Shot 2022-02-11 at 12 50 48 PM](https://user-images.githubusercontent.com/4107699/153651837-ef8d94f1-43db-4787-a38a-713e8ae4a590.png)

If I force the URL to the old Cluster Manager and view the project members there I see them:
![Screen Shot 2022-02-11 at 12 50 34 PM](https://user-images.githubusercontent.com/4107699/153651844-e70cfbde-d8cf-4054-b37f-a1e100026e09.png)

**Additional context**

**Detailed Description**

**Context**

**Comment by codyrancher** [comment]
As of right now this is what I'm seeing
![repro](https://user-images.githubusercontent.com/55104481/156969835-66a6eecd-3d67-4c33-b294-4a31793ebcf7.gif)

@mitchellmaler do you have any additional repro steps? Are these all users that were created on a previous version before a migration? What type of user are you logged in as when you run into this issue? Do you see the rolebindings in this response?

**Comment by codyrancher** [comment]
@mitchellmaler I'll see if I can reproduce after performing an upgrade. Are you seeing any errors in the browser console?

**Comment by mitchellmaler** [comment]
I mean upgrade from 6.2.2 to 6.2.3 not 6.2.4 since that isn't released

**Comment by gaktive** [comment]
Internal reference: SURE-4165

**Comment by jordojordo** [comment]
@mitchellmaler I am also having trouble replicating this issue.
From internal discussion I setup OpenLDAP as the auth provider, created two downstream clusters (rke and rke2 respectively), upgraded from `v2.6.2` to `v2.6.3` and I was able to add users and see them appear.

Here's what I was seeing when adding users (sorry for the glitchy video):

https://user-images.githubusercontent.com/40806497/163404680-76377ae7-12f3-41fa-9ed3-8556f5ff050e.mp4

---

Is there anything I am missing in my repo steps?

**Comment by gaktive** [comment]
One theory that floated up: can we take a look at the JSON file and see if the group principal ids has spaces? 

For example - `"groupPrincipalId": "openldap_group://cn=name1, o=name2, o=group1, c=com"`. 

In some environments where problems aren't being reported, this variable doesn't have spaces.

**Comment by codyrancher** [comment]
The groupPrincipalId is null the above comment https://github.com/rancher/dashboard/issues/5104#issuecomment-1060742477.

**Comment by jordojordo** [comment]
I created another rke instance with the Cluster Manager with the OpenLDAP provider, then updated to `v2.6.3` - `groupPrincipleId` is null for all three rolebindings, this seems to be normal behavior.

![projectroletemplatebindings](https://user-images.githubusercontent.com/40806497/164473788-4302c901-d790-4f58-b47f-a2cbf3af5c12.png)

**Comment by richard-cox** [comment]
Syncing info from JIRA. This only occurs  in environments where customer has over 1000 `projectroletemplatebinding`

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.6.4                                    |
| Rancher commit link       | not applicable                           |
| Installation option       | helm                                     |
| RKE binary version used   | v1.3.8                                   |
| If Helm Chart k8s cluster | v1.22.7                                  |
| Cert Details              | let's encrypt                            |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | not applicable                           |
| Downstream K8s version    | not applicable                           |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$HOSTNAME_OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_OMITTED \
  --set letsEncrypt.ingress.class=nginx
```

## Reproduction steps

1. Created some Terraform to create 1,000 member bindings to test this
   1. https://github.com/brudnak/rancher-tf-users
   2. https://github.com/brudnak/rancher-tf-project
2. Created 1,000 users and 1,000 user bindings to a project on the local cluster
3. Unable to reproduce as described, however the load time is noticeably slower without the fix
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
For the 1,000 users in the project member list to load 

#### :x: Actual
The 1,000 users do load, it just takes awhile (noticeably slow)

<hr>
  
## Validation Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.6.5-rc6                                |
| Rancher commit link       | not applicable                           |
| Installation option       | helm                                     |
| RKE binary version used   | v1.3.10                                  |
| If Helm Chart k8s cluster | v1.22.9                                  |
| Cert Details              | let's encrypt                            |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | not applicable                           |
| Downstream K8s version    | not applicable                           |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$HOSTNAME_OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_OMITTED \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5-rc6
```

## Validation steps

1. Created some Terraform to create 1,000 member bindings to test this
   1. https://github.com/brudnak/rancher-tf-users
   2. https://github.com/brudnak/rancher-tf-project
2. Created 1,000 users and 1,000 user bindings to a project on the local cluster
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
1,000 users are displayed correctly in the project member list

#### :white_check_mark:Actual
1,000 users are displayed correctly in the project member list
