### ISSUE TITLE
Allow workload to be scaled up/down from the Workload detail page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5114]
You can now scale up/down a workload from the workload list view for a given workload:

![image](https://user-images.githubusercontent.com/1955897/153838403-947d9306-6e92-4f3e-88cb-af07cebd4fb0.png)

We should add the same ability to the detail view for a deployment:

![image](https://user-images.githubusercontent.com/1955897/153838552-1d7f0b78-2a45-4967-b375-9da6ecb5dee5.png)

Initially, add this above the 'Pods by State' cards - suggest right-aligned 

`Replicas:  -  1  +`

The display can be the same as the 'Scale" line in the first image above.

The actions to scale up/down should already be in the `workload` model - so this should be "just" adding the UI!

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.6.5-rc2                                |
| Rancher commit link       | not applicable                           |
| Installation option       | helm high availability                   |
| RKE binary version used   | v1.3.8                                   |
| If Helm Chart k8s cluster | v1.22.7                                  |
| Cert Details              | let's encrypt                            |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | rke1 linode                              |
| Downstream K8s version    | v1.22.8-rancher1-1                       |
| Logged in user role       | administrator & standard user            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$OMITTED \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5-rc2
```

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> `Cluster Management` -> `Explore` next to the rke1 linode down stream cluster
3. Click `Workload` -> `Deployments` -> `Create` -> fil out the deployment creation form
4. Once deployed, and navigated back to the main deployments page, click the deployment name to see a detailed view of the deployment
5. Notice there is now a scale up `+ and scale down `-` buttons next to the `Pods by State` section
6. Verified being able to scale up and scale down the deployment
   
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Able to scale up and scale down the deployment

#### :white_check_mark:Actual
Able to scale up and scale down the deployment
