### ISSUE TITLE
Add workloads tab to the namespaces page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5115]
The detail page for a namespace currently shows:

![image](https://user-images.githubusercontent.com/1955897/153840293-3a78ad12-a103-4e5b-9006-7d033a399ee5.png)

We should add a new first tab that shows the workloads deployed in this namespace.

You will need to fetch all of the workloads and then filter for the namespace being viewed - you can then use a `ResourceTable` component to show these - an example which should help is the list for `fleet.cattle.io.clusterregistrationtoken.vue`.

**Comment by cnotv** [comment]
I think we can stick to the "subset" `SortableTable`, as we do not need all the actions functionalities, unless you want to add them as well.

**Comment by sowmyav27** [comment]
**On 2.6.3**
<img width="1446" alt="Screen Shot 2022-03-07 at 5 14 01 AM" src="https://user-images.githubusercontent.com/26032343/156947490-27b6d96d-faf3-4aa9-960a-9bf5ed98398e.png">

**On 2.6-head commit id: `4df2214`**
<img width="1438" alt="Screen Shot 2022-03-07 at 5 14 52 AM" src="https://user-images.githubusercontent.com/26032343/156947496-19598aa8-a92a-44e5-b693-8422946e0c23.png">
<img width="1439" alt="Screen Shot 2022-03-07 at 5 14 57 AM" src="https://user-images.githubusercontent.com/26032343/156947498-f193e8b8-3740-4fa0-8003-8a30a18c8679.png">

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
