### ISSUE TITLE
Namespace view shows 'Active' state twice

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5116]
![image](https://user-images.githubusercontent.com/1955897/153841557-af26703b-9b95-4e48-a0d3-bde811743459.png)

See above- there are two cards for 'Active' - there should only be one.

Take a look in `detail/namespace.vue`, in `namespaceCounts` - I think the issue is a mismatch between 'active` and `success` states.

**Comment by neillsom** [comment]
This issue is resolved by PR rancher/dashboard#5145

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.6.3**
<img width="1679" alt="Screen Shot 2022-02-24 at 10 00 38 AM" src="https://user-images.githubusercontent.com/26032343/155581767-2d5c5029-1d0c-4ed8-a6c1-d9add425c399.png">

**On 2.6-head commit id: `8c785a1`**

- `Resource` tab is added, and columns - error, warning, transitioning, unknown, Active are seen
- Active state is seen only one time
<img width="1441" alt="Screen Shot 2022-02-24 at 10 02 20 AM" src="https://user-images.githubusercontent.com/26032343/155581754-e4aa45d6-97ba-449d-8300-1a797159ed64.png">
