### ISSUE TITLE
Find out why Vue development tools are extremely slow

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5119]
Currently, when we use the Vue dev tools to inspect the dashboard app, we have to pause recording events and store actions in order to prevent the dev tools from freezing and crashing.

It would be nice to be able to use the dev tool features because it would help us work with Vuex and events. Therefore we should find out what is causing the dev tools to crash and freeze.

**Comment by catherineluse** [comment]
Note: I think it may have something to do with the cache being updated every few seconds. A lot of Vuex Actions are created because there are typically three open websockets that ping the frontend: `rancher`, `management` and `cluster`.

- `rancher` is the Steve API for cluster management
- `management` is the Norman API
- `cluster` is the Steve API for individual clusters

`management` updates every 30 seconds, while `rancher` and `cluster` update every 5 seconds.

<img width="1685" alt="Screen Shot 2022-02-10 at 4 50 53 PM" src="https://user-images.githubusercontent.com/20599230/153949517-62ff1b4c-19b1-45bf-9954-ce8db1c724a0.png">

**Comment by cnotv** [comment]
As I mentioned the other day, they do not expose configuration as in Redux to exclude mutations/actions from the Vuex devtool.

We may think about debug it with [standalone version](https://devtools.vuejs.org/guide/installation.html#standalone) which can be used also for production with some tricks. Otherwise we may isolate the logic from the store, then track only the changes, but not sure how much expensive is this last case.

**Comment by catherineluse** [comment]
To test it, we could temporarily turn off the watchers to see if it affects the deb tools, or just turn off some of them and see if the tool still crashes.

The standalone mode looks useful as well.

**Comment by catherineluse** [comment]
I took notes about what Vince said about performance issues here - https://github.com/rancher/dashboard/blob/master/docs/developer/performance.md

**Comment by catherineluse** [comment]
I'm closing this issue because I can no longer repro the issue with the development tools being slow.
