### ISSUE TITLE
Allow user option to deploy using system/cluster registry, if it is defined, for workloads through rancher

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5121]
**Detailed Description**
when creating workloads through rancher, it would be convenient to allow the user to use the cluster/global-defined registry by default. 

* perhaps a toggle box of some sort on either the user settings page, or the workload -> create page under the `image` options (see attached photos for reference)

<img width="1313" alt="Screen Shot 2022-02-14 at 1 29 07 PM" src="https://user-images.githubusercontent.com/16691014/153952763-3bbadb5c-32e3-41cb-ab76-8df2fe02f3c8.png">
<img width="1567" alt="Screen Shot 2022-02-14 at 1 51 23 PM" src="https://user-images.githubusercontent.com/16691014/153952768-715d1bd3-0e89-4024-9b4c-98b5cc5bcf94.png">

* I think this should only display if we detect that a registry is applied/available to the cluster (set at either global or cluster level)

* format of the image when this toggle is enabled would be <available-registry>/<user_entered_container_image>

**Context**

example: when in an airgap setup with a global registry defined, currently users must append the registry to their image name. This is annoying in airgap setups.

**Comment by catherineluse** [comment]
We could use a similar form section that we have for the Helm chart installation flow:
<img width="916" alt="Screenshot 2022-11-05 at 4 56 11 PM" src="https://user-images.githubusercontent.com/20599230/200147634-167111c1-7f09-40fb-bd0b-d6b5aac5267b.png">

The main difference would be that the workload form doesn't use the cluster registry by default. Maybe we should change the default registry to the cluster level one for workloads as well?

**Comment by gaktive** [comment]
Closing since we haven't heard any other demand for this. If this is still an issue, let's run this by Product Management first to understand what they feel.
