### ISSUE TITLE
Create script to populate a cluster with a large number of resources for testing

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5126]

**Comment by catherineluse** [comment]
The script can use some of the huge YAML files from https://github.com/catherineluse/dashboard-performance

**Comment by richard-cox** [comment]
I have a [PR](https://github.com/rancher/dashboard/pull/6477) containing a script that will make resources spread across new projects. It's more complicated as it makes api requests to create the projects to assign the resources to (needs rancher access keys, url, etc).

**Comment by nwmac** [comment]
Won't fix
