### ISSUE TITLE
registry secret is not disabled on the `view config` page

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5130]
**Setup**
- Rancher version: v2.6.4-rc2
- Browser type & version: chrome

**Describe the bug**

user should not be able to edit/change from the `cluster` -> `view config` page

**To Reproduce**

deploy a cluster with a registry + http secret configured
after deployment, visit the `view config` page of the cluster

**Result**
secret dropdown is not disabled

**Expected Result**

user should not be able to edit/change from a view only page

**Screenshots**

<img width="668" alt="Screen Shot 2022-02-15 at 2 06 29 PM" src="https://user-images.githubusercontent.com/16691014/154159401-43a70ad7-04d5-4494-9a15-8e32019cc96c.png">

**Comment by Josh-Diamond** [comment]
Ticket #5130 - Test Results

With Docker on single-instance:

Reproduced on rancher v2.6.3:
1. Fresh install of rancher `v2.6.3`
2. As admin, create an RKE2 provisioned cluster with a registry and http secret configured
3. Once created, `view config` and see if immutable data is mutable, under the `registries` tab of `Cluster Configuration`
4. Reproduced - immutable data is able to be modified

Screenshot:
<img width="1351" alt="registry-reproduced" src="https://user-images.githubusercontent.com/46494969/158839547-a351f6c0-510b-4c79-83f5-84588f60399d.png">


Verification FAILED on rancher `v2.6-5bb08b3692ac3c18ec1361694a095e2c25eb0346-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create an RKE2 provisioned cluster with a registry and http secret configured
3. Once created, navigate to the cluster's `view config`, and see if immutable data is mutable under the `registries` tab of `Cluster Configuration`
4. Verification FAILED - immutable data is able to be modified


<img width="1339" alt="registry-veriFAILED" src="https://user-images.githubusercontent.com/46494969/158839611-35fd93ef-3693-43d3-81c0-f4f0244ad55c.png">

**Comment by Josh-Diamond** [comment]
Ticket #5130 - Test Results - Verification

With Docker on single-instance:

Verified on rancher `v2.6-d63d95a6d75603146e5b15b948ee54a2d452b767-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create an RKE2 provisioned cluster with a registry and http secret configured
3. Once created, navigate to the cluster's `view config`, and see if immutable data is mutable under the `registries` tab of `Cluster Configuration`
4. Verified - Immutable data is NOT able to be modified

Screenshot:

<img width="1716" alt="Screen Shot 2022-04-13 at 3 11 31 PM" src="https://user-images.githubusercontent.com/46494969/163279114-2fc41b4f-255d-4b9a-8c7a-37fd7973cc0c.png">
