### ISSUE TITLE
"Restore snapshot" modal doesn't work for RKE2 clusters

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5131]
@neillsom For RKE2 clusters, when you choose the restore snapshot action from cluster manager (from the list of clusters), it opens the restore snapshot modal. However, the list of available snapshots is shown to be empty, even if there are snapshots available for that cluster.

The expected behavior is that the modal should display the list of existing snapshots.

Here the modal is empty:
<img width="1015" alt="Screen Shot 2022-02-15 at 3 16 29 PM" src="https://user-images.githubusercontent.com/20599230/154159157-574019ff-34ce-453d-ada6-5388fa947c39.png">

But the following snapshots should be available to choose from:
<img width="768" alt="Screen Shot 2022-02-15 at 3 16 40 PM" src="https://user-images.githubusercontent.com/20599230/154159181-bee906d8-1076-412c-923f-21b2967267fb.png">

The modal probably needs to have different logic for listing snapshots from Norman and Steve.

**Comment by catherineluse** [comment]
I am no longer seeing this issue on `v2.6-head`.

**Comment by gaktive** [comment]
Pushing out a release though if this isn't needed anymore, we can mark this as something for QA to record as a precaution and they can close.

**Comment by catherineluse** [comment]
This issue is now being seen in v2.6-head, but for RKE1 clusters https://github.com/rancher/dashboard/issues/4606#issuecomment-1063475954

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head d604b7e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: EC RKE2 aws node driver

----------

### Testing: ###

Tested this issue with the following steps:
1. Deployed an ec2 node driver RKE2 cluster on rancher - 3 etcd, 2 cp and 3 worker nodes
2. Take a snapshot
3. Snapshots are listed in Cluster management --> Cluster details --> Snapshots tab
4. Click on Restore on the cluster
5. The snapshot options in dropdown list

**Result** - Pass
The modal is working as expected and user is able to select from the list
![image.png](https://zube.io/files/rancher/23efa1dac0175b9e377280228bcaeeae-image.png)
