### ISSUE TITLE
Rancher Apps and Marketplace UI Improvements 

### ISSUE THREAD

**Issue by phillipsj** [rancher/dashboard#5137]
# Definitions 

* Mixed workload cluster – A cluster that has a single node other than **linux_amd64**.  
* Node Affinity – Scheduling instructions for Kubernetes, much like a node selector, can be hard or soft requirements 

# The Problem 

Currently the Rancher Apps and Marketplace categorize charts between Linux and Windows. Prior to RKE2 (Rancher Kubernetes Engine 2) this worked well enough due to how RKE1 leveraged taints and tolerations when it came to clusters that were designated for use by Windows. 

In RKE2 there is no longer a difference between a cluster that can support non linux_amd64 nodes as it can have a Windows or S390x node added or deleted at any time during its lifecycle. This brings to the forefront many different scenarios that any chart in the App and Marketplace needs accommodate. A chart in a mixed workload environment not only needs to have container images that support the different operating systems or architectures of the current cluster it needs to designate if the chart does not support that operating system or architecture. If a chart doesn’t support a non linux_amd64, then the chart needs to have a node affinity or node selector that prevents it being scheduled on a node that isn’t supported. This will ensure that if a chart is in use in cluster with only linux_amd64 nodes, that once a non linux_amd64 node is added that it doesn’t try to schedule the unsupported chart on that node.  

# Proposed Solution 

We currently have a solution in place that would determine if Windows charts should be shown based on the ratio of Windows nodes to Linux nodes in the RKE2 cluster. This is a helpful solution to solve the issue of knowing if a chart can or can’t be deployed. It doesn’t address the need for users who are working in a mixed workload cluster from knowing if the chart can be ran without issue in their cluster as it doesn’t designate if it can be deployed on or permitted on mixed workload clusters. 

Arvind designed a solution that could address this by adding annotations to existing charts that would help the customer understand what would occur in their mixed workload cluster if they deployed a chart. 

* GitHub Issue: https://github.com/rancher/rancher/issues/36401 
* Confluence Page: https://confluence.suse.com/display/EN/Handling+Shifting+Cluster+Requirements+in+Catalog+V2 

Let’s walk through a real use case to illustrate the issue. Let’s say we have a customer that is going to be deploying a Microsoft ASP .NET application using Windows Containers that connects to a SQL Server database, also deployed inside of the cluster, and this solution leverages Redis for caching. SiteCore CMS (Content Management System) is the real work solution being used. Redis and Microsoft SQL Server are only supported on linux_amd64 containers, so this user would need to have several Linux worker nodes, along with several Windows worker nodes to be able to deploy this solution. If the user wanted to deploy Monitoring, Istio, etc. then the user would need to know if the chart was able to be deployed within their cluster without having to be concerned that a linux_amd64 workload would be schedule on their Windows nodes causing the deployment to never complete or fail. If a chart designated if it were permitted or deploys to node type then the user could decide if they could leverage the solution as is, modify the helm chart to add the node affinities, or look for an alternate approach. 

![Slide1](https://user-images.githubusercontent.com/1568133/154303732-5d93c6ca-5041-493c-9124-96cc71b5b426.jpg)
_this image does not perfectly reflect the updated plan. See below_

## Updated Solution 3/10
Per feedback from Sowmya, we need the UI to better distinguish between charts that _deploy on_ Windows nodes and charts that merely _do not break_ when installed on a cluster that has at least one Windows node. 

### Deployability
All charts, Rancher and otherwise, are assumed to be deployable on Linux. Charts with the annotation `deploys-on=linux,windows` will have a badge indicating that they deploy on Windows. Currently, this is only v2 Monitoring and Logging.
### Permissibility
The Apps and Marketplace chart overview page and individual chart install pages will have a (user dismiss-able) banner: 

> “All charts have at least one version that is installable on clusters with Linux and Windows nodes unless indicated by {insert indication here}.”

Charts that do not have a `permits-os` annotation, or whose `permits-os` annotation doesn’t include `windows`, will have a badge indicating that they should not be installed on clusters with Windows nodes. Currently, this is all partner charts. All Rancher charts now have at least one version that permits Windows.

# Impact on QA for 2.6.4 

The following charts need to be annotated: 

 * https://confluence.suse.com/pages/viewpage.action?spaceKey=EN&title=Chart+Assignments

Chart annotations to not fundamentally change chart functionality. QA would need to test the revised UX based on the chart annotations approach. Because QA would have needed to test the previous UX this would introduce no new burden on QA. 

# Existing UI Issues

Existing GitHub UI issues required by Windows team for 2.6.4 GA of Windows on RKE2: 

* https://github.com/rancher/dashboard/issues/4983 
* https://github.com/rancher/dashboard/issues/4859 
* https://github.com/rancher/dashboard/issues/4986 

GitHub UI issues that reflect the updated approach:

~~* https://github.com/rancher/dashboard/issues/5054~~
~~* https://github.com/rancher/dashboard/issues/5055~~
~~* https://github.com/rancher/dashboard/issues/5056~~
~~* https://github.com/rancher/dashboard/issues/5057~~
~~* https://github.com/rancher/dashboard/issues/5058~~
The above  issues no longer reflect the updated approach and have been closed in favor of this issue.

Wiki: 

* https://confluence.suse.com/pages/viewpage.action?spaceKey=EN&title=Project+Status 
* https://confluence.suse.com/pages/viewpage.action?spaceKey=EN&title=Handling+Shifting+Cluster+Requirements+in+Catalog+V2 

# QA Test Plan 

The test plan for this would involved creating a mixed workload cluster with at least one windows worker node. The process may look like the following: 

1. Deploy a chart that “deploys on” Windows and see if it deploys successfully. 
2. Deploy a chart that “deploys on” Linux and see if it deploys successfully. 
3. Deploy a chart that permits Windows, ensures that it only deploys on Linux. 
4. Deploy a chart that permits Linux, ensures that it schedules on Windows and not on Linux. 
5. Deploy a chart that supports both Windows and Linux and ensure that it schedules on both. 
~~6. Ensure that when there aren't any permits-os annotations that nothing is displayed in the UI.~~
6. Ensure that when there aren't any permits-os annotations, there is an indication that the chart is not compatible with Windows
7. Test that labels are present regardless of worker node OS types.
~~8. Unspecified values for the permits-os annotation should just be ignored.~~
~~9. Only the permits-os annotation is implemented so verify visually that a chart indicates its compatible with an OS.~~

**Comment by phillipsj** [comment]
@sirredbeard @luthermonson @rosskirkpat @aiyengar2 @SheilaghM

**Comment by gaktive** [comment]
To simplify what QA can test for 2.6.4 here -- since as far as I understand, the backend for arch support is still underway -- I'll separate the arch support tickets into a new epic ticket. We'll focus on the OS-related work here for the UI.

**Comment by luthermonson** [comment]
This Issue is being chosen to supercede all other issues left lying around that documented how we got to the solution we did. To solve we have boiled everything down to one mega Charts PR and a Dashboard PR which presented the annotations we added to the Charts. 
* Charts: https://github.com/rancher/charts/pull/1779
* Dashboard: https://github.com/rancher/dashboard/pull/5174

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.

**Comment by eliyamlevy** [comment]
[External IP Webhook installation fails on RKE1/RKE2 Windows cluster #37045](https://github.com/rancher/rancher/issues/37045)
