### ISSUE TITLE
Longhorn App fails to install from Legacy project app

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#5139]
**Setup**
- Rancher version: v2.6-head - `3f30288`
- Browser type & version: Chrome 97.0.4692.99

**Describe the bug**
Longhorn app can't be installed from legacy project app

**To Reproduce**
1. Enable legacy flag
2. Go to Legacy --> Project - > app
3. Launch Longhorn version v1.2.3

**Result**
Longhorn fails to install. No events, no pods get created.

**Expected Result**
Longhorn should be installed properly.

**Screenshots**
<img width="919" alt="Screen Shot 2022-02-16 at 11 40 39 AM" src="https://user-images.githubusercontent.com/60111667/154353548-f6a43ace-dfdb-4015-8f5a-9c9d1b72b8a4.png">

**Comment by nwmac** [comment]
@richard-cox Can you see if you can reproduce this?

**Comment by richard-cox** [comment]
I couldn't reproduce this with the latest UI (dashboard and cluster management) and Rancher `8c785a1`. It did take a while for the embedded cluster management page for the longhorn app to show resources, though they wasn't an error at any point and the resources were visible in the dashboard. 

@khushboo-rancher Was there anything slightly interesting in your environment, what cluster type / version were you using and could it have contained any previous version of longhorn?

![image](https://user-images.githubusercontent.com/18697775/156780142-c88311cb-3162-4486-84d1-ba344a9ab74e.png)

![image](https://user-images.githubusercontent.com/18697775/156780191-da1beea6-6865-420a-b959-7018bc31162a.png)

![image](https://user-images.githubusercontent.com/18697775/156780243-474d4800-236f-4330-a9b1-ada6e103e30d.png)

**Comment by khushboo-rancher** [comment]
Revalidated this on v2.6.4-rc4 with cluster K8s version v1.21.5, It worked fine. Couldn't reproduce this.

Closing this now if I encounter this issue again in future will reopen this. 

Thanks @richard-cox for trying.
