### ISSUE TITLE
Various issues when displaying registry information on cluster -> config view

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5146]
**Setup**
- Rancher version: v2.6.4-rc3
- Browser type & version: chrome 98.0.4758.80

**Describe the bug**

When viewing `registry` information about a cluster (cluster management -> cluster -> config view) information displayed is sometimes incorrect.  

**To Reproduce**

this can be in a custom cluster without registering a node for testing purposes
* deploy a cluster that has registry information defined, specifically for the `Configure advanced containerd mirroring and registry authentication options` option
  * include some `registry authentication` and `mirror` information as well
* save your settings
* view the cluster, then select the `config` view
  * navigate to the registry settings
* if you see the correct values, edit the cluster's registry settings (say, enable the `tls skip` checkbox) and view the same `config` page upon saving the changes

**Result**
registry information is not displaying correctly. Sometimes, the `authentication` options do not display with what is in the yaml (i.e. the checkbox won't be checked even though the yaml shows that it has a `true` value)
Other times, the `Configure advanced containerd mirroring and registry authentication options` is not saved, even though there is authentication information for the registry in the yaml. And the UI will default back to the `Pull images for Rancher from a private registry` radio box instead

**Expected Result**

display options for `config` should match what is in the yaml (and what the user originally selected through the UI

**Screenshots**
(for example in repro steps above)
<img width="491" alt="Screen Shot 2022-02-17 at 9 44 17 AM" src="https://user-images.githubusercontent.com/16691014/154540170-d27cdeb7-6419-4eda-b2a3-cdcea518026a.png">
<img width="522" alt="Screen Shot 2022-02-17 at 9 43 44 AM" src="https://user-images.githubusercontent.com/16691014/154540176-d960a46a-5c4c-428c-ae1a-d77c4d4d252e.png">

**Comment by catherineluse** [comment]
This issue should be addressed in the same milestone as https://github.com/rancher/dashboard/issues/6919, which is updating and simplifying that part of the form.

**Comment by catherineluse** [comment]
I believe this issue is fixed in this PR https://github.com/rancher/dashboard/pull/7508

**Comment by Josh-Diamond** [comment]
Ticket #5146 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-8062f1e3ab7bff870dfab195ff699a308644168a-head`:
1. Fresh install of rancher `v2.7-head`
2. Create a downstream custom cluster w/ cluster level registry and mirrors configured - [i used fake data for testing; i did not actually provision]
3. Once created, `Edit Config` and confirm data values persist
4. Verified - data persists
5. `Edit YAML` and confirm data values persist and are accurate
6. Verified - data persists and is accurate

Screenshots:

`Step 4`
<img width="1106" alt="Screenshot 2023-01-04 at 4 01 05 PM" src="https://user-images.githubusercontent.com/46494969/210667350-a495ccd5-b50c-450f-bef3-ba5932fd4598.png">

`Step 6`
<img width="409" alt="Screenshot 2023-01-04 at 4 00 26 PM" src="https://user-images.githubusercontent.com/46494969/210667419-48cc3b18-59ce-4a9c-b1bf-7c802ad15dc4.png">
