### ISSUE TITLE
Change nav logic so side-nav does not change when you select a namespace

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5147]
Don't hide cluster-level resources when you select a namespace.

Add a badge next to cluster-level resources when a namespace is selected (+ tooltip), so that the user knows they are viewing a cluster-resource and that the namespace filter does not apply - see design from @lvuch

**Comment by lvuch** [comment]
This fix should also include nav accessibility as noted here: https://github.com/rancher/dashboard/issues/4388

**Comment by nwmac** [comment]
@lvuch I have created https://github.com/rancher/dashboard/issues/5287 for the follow on work for 2.6.5

**Comment by sowmyav27** [comment]
**On 2.6.3 reproduced the issue**

- Navigate to cluster explorer of a cluster
- Select `Default` namespace from the namespace picker
- Cluster dropdown and the RBAC from Left panel are hidden

**On 2.6-head commit id: `4df2214`**

- Navigate to cluster explorer of a cluster
- Select `Default` namespace from the namespace picker
- Cluster dropdown and the RBAC from Left panel are _not_ hidden. Cluster level resources are NOT hidden
