### ISSUE TITLE
Move 'show previous log' from the cog menu to a checkbox

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5149]
Check with @nwmac for details

**Comment by sowmyav27** [comment]
**On 2.6.3**
<img width="1655" alt="Screen Shot 2022-03-07 at 5 16 32 AM" src="https://user-images.githubusercontent.com/26032343/156947985-1a7de00c-fe0a-43cd-ad25-2725d71532b3.png">


**On 2.6-head commit id: `4df2214`**
<img width="1679" alt="Screen Shot 2022-03-07 at 5 27 19 AM" src="https://user-images.githubusercontent.com/26032343/156947981-550d31a6-6cd8-43ea-9575-9937003cf72a.png">
<img width="967" alt="Screen Shot 2022-03-07 at 5 27 11 AM" src="https://user-images.githubusercontent.com/26032343/156947991-1b4ae709-3472-4900-b928-239424152f4a.png">

**Comment by sowmyav27** [comment]
@nwmac could you provide more info about this fix “Fixes a minor styling issue in the AsyncButton control where there is extra margin on the left of the text when there is no icon” ?

**Comment by nwmac** [comment]
@sowmyav27 This relates to the Download button - it does not have an icon, but is an async button - you'll see that the text is not correctly horizontally aligned prior to this fix - there is extra margin on the left-hand side of the text.

**Comment by sowmyav27** [comment]
Text on download button is aligned correctly on latest 2.6-head
