### ISSUE TITLE
Sidecar missing from Workload menu

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#515]
We don't have a way to add sidecars to Workloads.

**Comment by tfiduccia** [comment]
@mantis-toboggan-md - This was implemented for Rio, so you might want to chat with @vincent99 or just see if you can copy the code from there.

**Comment by deniseschannon** [comment]
Sidecars were how we added multiple containers to a Pod, but it will be replaced using the containers component: https://github.com/rancher/dashboard/issues/596
