### ISSUE TITLE
[custom cluster] windows command shows up before a linux worker has registered with the cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5150]
**Setup**
- Rancher version: v2.6.4-rc3
- Browser type & version: any

**Describe the bug**

when registering a custom cluster in preparation for windows, it is required that the cluster has an etcd, controlplane, and worker registered from linux nodes before the windows command should display to the user. However, if user registers only an etcd and controlplane node, the UI is displaying windows command for rke2

**To Reproduce**

* create an rke2 custom cluster
* register a linux node with the `etcd` and `controlplane` roles
* wait for the node to be active in the cluster
* go back to the `cluster` -> `registration` page

**Result**
* windows registration command is showing, even though no linux worker has registered in this cluster

**Expected Result**

windows command shouldn't show until all 3 roles are registered with linux nodes first. 

**Additional context**
this is bad because users might be confused and think that it is OK to register windows workers without linux workers, which is not supported.

**Comment by phillipsj** [comment]
**Setup**
- Rancher version: v2.6-head 47c2238
- Browser type & version: any

**To Reproduce**

* create an rke2 custom cluster
* register a linux node with the `etcd` and `controlplane` roles
* wait for the node to be active in the cluster
* go back to the `cluster` -> `registration` page

**Result**
The Windows registration command is now working correctly and doesn't appear until after a Linux worker is registered.

No worker and no registration command:
![no-windows-registration-without-worker](https://user-images.githubusercontent.com/1568133/157455551-8a19d7b7-2273-4e5c-99b1-29c31ea0c5e9.png)

Once worker was added the registration command appeared.
![windows-registration-once-worker](https://user-images.githubusercontent.com/1568133/157455661-aec8c627-1534-416e-8c6d-a00bedcfdb12.png)
