### ISSUE TITLE
CIS mode is not available on RKE2 EC2 Provisioning

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/dashboard#5152]
**Setup**
- Rancher version: v2.6-head 978e165
- Browser type & version: Chrome 98.0.4758.82 

**Describe the bug**

CIS mode is not available to the user when provisioning a RKE2 node driver cluster. The option is available when creating a custom cluster and the functionality is also available for node driver cluster provisioning.

**To Reproduce**

1. Create RKE2 node driver cluster
2. Go to Security Under Cluster Configuration --> Basics

**Result**
CIS mode option is not available

**Expected Result**

CIS Mode option should be available.

**Screenshots**

CIS mode option in custom cluster provisioning
![image](https://user-images.githubusercontent.com/97477402/154598019-e00afbc5-480b-4c79-b752-2145a99f6558.png)

CIS mode option missing in node driver cluster provisioning
![image](https://user-images.githubusercontent.com/97477402/154598071-ccf8830f-9313-4fc9-8e63-c1dc94a87aa7.png)

yaml entry added when selecting CIS mode
![image](https://user-images.githubusercontent.com/97477402/154598152-86bca5ff-ff56-4156-b8ee-ee6679d581c0.png)

**Comment by timhaneunsoo** [comment]
This feature is not yet supported on v2 provisioning and will be put under Review until the feature is supported in a later release

**Comment by gaktive** [comment]
@timhaneunsoo is there are a related backend ticket for UI to track so we're aware when this feature is in?

**Comment by gaktive** [comment]
Waiting on https://github.com/rancher/rancher/issues/37190 which should then unblock https://github.com/rancher/rancher/issues/36565

**Comment by gaktive** [comment]
@Oats87 or @timhaneunsoo I see https://github.com/rancher/rancher/issues/37190 is closed; can UI work on this now?

**Comment by timhaneunsoo** [comment]
After discussing with dev, there is a lot of work that needs to be done on the user's end regarding kernel parameter changes. The only case this would work is if an ami with all the changes already in place is used. The provisioning for custom clusters works as expected. I was fairly new when logging this ticket and did not realize the complications of cis-mode with v2 prov on node driver clusters. We do have a ticket here though, [36629](https://github.com/rancher/rancher/issues/36629), which will cover testing for the cis-mode. We may not even need to make a change for node driver cluster provisioning. I would like to hold off on this ticket until testing is completed, because these changes may not be needed.

**Comment by aalves08** [comment]
@gaktive were going to move this back to Backend Blocked until further notice.

Thanks for the update @timhaneunsoo 👍

**Comment by gaktive** [comment]
Pushing to 2.6.6 unless @timhaneunsoo indicates that UI can do something immediately as time for 2.6.5 is running out.

**Comment by gaktive** [comment]
This looks to be unblocked now as all the related backend tickets are merged but @timhaneunsoo based on your April 21 comment, does UI still have to do something here?

**Comment by timhaneunsoo** [comment]
@gaktive I believe there is nothing to do here. This feature only got validated for custom clusters and will be available to rke2 custom clusters at the moment. Closing this ticket as no fix needed.
