### ISSUE TITLE
Hyphen has appeared after the cluster type in header when creating a cluster

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5160]
- ![image](https://user-images.githubusercontent.com/18697775/154702921-fe06209c-4f3e-47a0-a35e-de69ad7be6d3.png)
- The hyphen may be used in other scenarios, this should be confirmed to be or not be the case before removing it

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `4df2214`**

Hyphen is not seen when creating resources - cluster/secrets
<img width="888" alt="Screen Shot 2022-03-07 at 7 41 45 AM" src="https://user-images.githubusercontent.com/26032343/156956114-9380cf2b-6a75-4eb3-8c08-679e8c4f005b.png">
