### ISSUE TITLE
Sorting by CPU, RAM or Pods ASC/DESC broken

### ISSUE THREAD

**Issue by HoustonDad** [rancher/dashboard#5165]
Internal reference: SURE-4175

**Setup**
- Rancher version: 2.6.2/2.6.3
- Browser type & version: Chrome latest, Firefox latest

**Describe the bug**
When in the nodes area of the cluster explorer, when sorting by CPU, RAM or Pods, ascending / descending do not sort properly. Age *does* sort properly FWIW.

**To Reproduce**
Cluster -> Nodes -> Sort Asc/Desc on CPU/RAM/OR Pods

**Result**
Sort doesn't correctly list Asc/Desc
Age does sort currect though

**Expected Result**
Sorting properly per CPU/RAM/Pods

**Screenshots**
<img width="960" alt="2 6 3_screenshot" src="https://user-images.githubusercontent.com/620445/154735838-1514ddbb-fcd5-479c-b883-351e61713a7e.png">
![2 6 2_resouce_sort_1](https://user-images.githubusercontent.com/620445/154735841-506d03d2-3d48-4044-a972-a7c968c21a56.gif)

**Comment by rak-phillip** [comment]
We had a similar issue in Rancher Desktop; values like CPU and RAM come through as text (70MiB, 74KiB, etc...). We'll need to make use of the `parseSi()` utility to convert values to numbers and use that as a sort target.

https://github.com/rancher-sandbox/rancher-desktop/pull/1273/files

**Comment by slickwarren** [comment]
tested on v2.6-head (cd0555b):


* nodes are now sorting by CPU/RAM/etc. properly. Screenshot is sorting by CPU as an example

<img width="517" alt="Screen Shot 2022-04-12 at 1 18 59 PM" src="https://user-images.githubusercontent.com/16691014/163046768-abb7f42d-e9b1-440b-a5a9-efa379013625.png">
