### ISSUE TITLE
No option to SSH into RKE2 node while node is in Waiting for Node ref state

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/dashboard#5171]
**Setup**
- Rancher version: v2.6-head c49139d
- Browser type & version: Chrome 98.0.4758.102

**Describe the bug**

When provisioning RKE2 cluster(same on RKE1), after the node is created in the backend, user can access the keys from the UI, but there is no option to SSH into the node. SSH into node is successful with the keys through terminal.
<img width="1134" alt="Screen Shot 2022-02-18 at 3 09 55 PM" src="https://user-images.githubusercontent.com/97477402/154754527-b820aafd-87c1-4205-bc44-43b54fc47894.png">

**To Reproduce**

1. Create Cluster
2. Go to nodes being provisioned
3. Click on options

**Result**
There is option to download SSH key

**Expected Result**

There should also be an option to `> SSH Shell`
<img width="231" alt="Screen Shot 2022-02-18 at 3 13 03 PM" src="https://user-images.githubusercontent.com/97477402/154754881-46d105e7-aea8-493a-8d06-d7bec696dd82.png">

**Additional context**
@thedadams mentioned:
- In order to enable the SSH Shell from the UI before the node ref is set, the UI would have to dig into the machine-state secret to get the IP address.

**Comment by richard-cox** [comment]
The action to ssh only shows when the associated `cluster.x-k8s.io.machine` resource contains a `links.shell`. This was recently updated to also take into account if the node was running (`status.phase === 'Running'` - see #3951).

Some clarity is required here, what state the action should be available for, how to determine so and, if the frontend should do this or it should be tied in to the visibility of the `shell` link (which is pattern used by the api in a number of places).

**Comment by nwmac** [comment]
This is an old issue and requires backend changes - closing for now.

This is an enhancement that is up for consideration and will be driven from backend via the rancher/rancher repository.
