### ISSUE TITLE
[Apps & Marketplace V2] Add visualization of permits-os annotation to Apps & Marketplace cards

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#5172]
Per rancher/dashboard#5137 , in order to validate the new chart annotation, `permits-os`, we need at minimum a UI indication of the annotation in the apps/marketplace view:
 ![image.png](https://zube.io/files/rancher/6dd5c8216324e1ce586443f4031f0238-image.png)

Note: these labels (and the default of 'linux') should only be applied to charts with the rancher certified annotation

**Comment by luthermonson** [comment]
This issue is going to be superceded by a previous dashboard issue which captures everything and has all PRs linked up. You can see context https://github.com/rancher/dashboard/issues/5137#issuecomment-1062323770
