### ISSUE TITLE
k8s version 1.22 still listed as 'experimental' in 2.6-head 2.6-head Commit ID 20d20a3 1.22

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5175]
**Setup**
- Rancher version: `2.6-head Commit ID 20d20a3 1.22`
- Browser type & version: Chrome

**Describe the bug**
v1.22.x is listed as `experimental` in 2.6.4 for rke2 and k3s

**To Reproduce**
Provision a downstream rke2 cluster
Select Kubernetes Version

**Result**
1.22 experimental
**Expected Result**
1.22 is no longer experimental as of 2.6.4 

**Screenshots**

<img width="247" alt="Screen Shot 2022-02-18 at 10 04 36 AM" src="https://user-images.githubusercontent.com/89212856/154771742-6f25e2be-254c-4e7c-9877-88b6af87c46c.png">

**Additional context**

**Detailed Description**

**Context**

**Comment by nwmac** [comment]
@ronhorton This is as designed - although 1.22 is not experimental, any k8s version greater than the version that the mgmt server is running is considered experimental from Rancher point of view.
