### ISSUE TITLE
Follow-up #5048: Fleet Dashboard - Each card should show a maximum of 5 repos

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5176]
Follow-up of issue [5048](https://github.com/rancher/dashboard/issues/5048):

- This item was not addressed:
`Each card shows a maximum of 5 repos (this is not quite shown right in the design) - when there are more than this there is a 'Show N more workspaces' button (shown on 2nd workspace card in the design). When clicked, this will show the additional repositories. Note we could be more adaptive on what we show - e.g. if there are only 2 workspaces (the default), then we could show more repositories per workspace. With a larger number of workspaces, we show less repositories per workspace.`

Will need further explanation on how this should work if we have more than 5 repos 🙏

**Comment by gaktive** [comment]
Closing for now since an overall reassessment of the Fleet UI is in the cards and this ties into that.
