### ISSUE TITLE
Fleet: Show bundle status information for git repo

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5178]
There is bundle status that we should show on the detail page for a GitRepo - we have the detail on how many bundles have been synced and we have error information: `display.readyBundleDeployments`

<img width="1831" alt="Screenshot 2022-02-21 at 10 28 54" src="https://user-images.githubusercontent.com/97888974/154938049-4da61091-021e-4abe-bb22-798a1707c5d5.png">

**Comment by Shavindra** [comment]
@izaac this was done as part of Issue: https://github.com/rancher/dashboard/issues/4793 in this PR: https://github.com/rancher/dashboard/pull/5068

Here is the screenshot of the view now

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/1387263/158980946-ed3d62af-434e-48d3-b673-ead704934ee9.png">

**Comment by aalves08** [comment]
@izaac area for the screenshot you appended (Fleet dashboard view) is present in v2.6.4-rc9 here:
![Screenshot 2022-03-18 at 10.08.46.png](https://zube.io/files/rancher/66e40fc684f25416c352e5ac1e924506-screenshot-2022-03-18-at-10-08-46.png)

**Comment by izaac** [comment]
Thanks for the clarification @aalves08 I was a bit out of context but now I think I'm good to test.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.6.4-rc10

Followed test instructions from: https://github.com/rancher/dashboard/pull/5068

Bundle status information is shown correctly for git repos - see #4793

* Deployed several clusters
* Added example gitrepo 
* Clicking on the git repo shows the bundles included
* With a bundle in an error state, the error is shown
* Statuses are displayed in different colors on the distrobution graph
* Counts of ready bundles/resources are shown
* Dropdowns for Bundles and Resources show the detailed view of counts of the possible states
* Pending statuses are shown correctly
* The Bundles details page is accessible from the left nav-menu
* All bundles are shown, and clicking on one shows the resources available
