### ISSUE TITLE
Header banner appears two times

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5181]
**On 2.6-head commit id: `d4089da`**

- Login as an admin and set Header and footer Banner by navigating to Settings --> banner --> Enabled header and footer
- Save changes made
- Now open rancher in Firefox (new browser)
- The Header banner appears two times.

<img width="1336" alt="Screen Shot 2022-02-21 at 2 40 23 PM" src="https://user-images.githubusercontent.com/26032343/155042145-a2aefacd-e6b8-49eb-aa09-305f87e4e78d.png">

**Expected Result:**
It should appear only one time

**Comment by nwmac** [comment]
This is by design - header and footer banners appear on all screens. The login banner appears only on the login screen. What you have configured here is both a login and header banner - hence you see both.

**Comment by sowmyav27** [comment]
[This](https://github.com/rancher/dashboard/issues/5181#issuecomment-1050266005) makes sense. Closing the issue
