### ISSUE TITLE
Mimic 2.5 UI Warning for Node Problems in 2.6

### ISSUE THREAD

**Issue by HoustonDad** [rancher/dashboard#5183]
**Detailed Description**
In Rancher 2.5, when viewing clusters (/clusters), a UI warning was present if a node in a cluster was having problems.

In Rancher 2.6, when viewing clusters (Cluster Management), there are no UI warnings if a cluster is having problems. You are required to click 'into' the cluster, to see that there are node problems.

Having the ability to glance at all of your clusters and see any problems is a great feature that should be brought back. 
Rancher 2.5:
![UI Warnings](https://user-images.githubusercontent.com/620445/155181923-b477f44f-5321-41f9-8116-e7b49662d7ba.png)

Rancher 2.6:
![UI no warnings](https://user-images.githubusercontent.com/620445/155181950-7cb38df1-7236-4535-a9dd-9884e9b5fc20.png)

**Comment by nwmac** [comment]
Duplicates https://github.com/rancher/dashboard/issues/5346

**Comment by nwmac** [comment]
@neillsom This is a dup and will be fixed by the work you are doing for 5346

**Comment by floatingman** [comment]
Observed warning for nodes with issues.
![firefox_6uVjqP8hRj.png](https://zube.io/files/rancher/04173feaff20260489c3ed32e3d6e7d2-firefox_6uvjqp8hrj.png)
