### ISSUE TITLE
[rke2] `memory` field (cluster management -> create page) moves cursor to last digit if first digit is removed

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5186]
**Setup**
- Rancher version: v2.6.4-rc3
- Browser type & version: any

**Describe the bug**

When editing a memory field, if the user removes the first digit, the cursor actually jumps to the last digit in the field.
 i.e. if current/default entry is 8096 and user removes the 8, the 0 is removed and the cursor jumps to position after 6

**To Reproduce**

* go to provision a cluster (I'm using vsphere rke2)
* change the first digit of the memory field

**Result**
cursor jumps to the last digit in the field

**Expected Result**

nothing should be modified for the field until the user clicks out of that entry box.  This would probably fix both the cursor jumping issue as well as the 0 being removed

**Screenshots**
<img width="171" alt="Screen Shot 2022-02-22 at 11 04 13 AM" src="https://user-images.githubusercontent.com/16691014/155201076-25ba111f-a2bc-4e77-aa20-90cb1ca1c427.png">
<img width="195" alt="Screen Shot 2022-02-22 at 11 04 18 AM" src="https://user-images.githubusercontent.com/16691014/155201072-9b802bfa-d142-4605-9cb4-b6e637df0d23.png">
cursor is moved to the end of '96'

**Comment by nwmac** [comment]
This is also present on the memory fields for a deployment, so can be reproduced with:

- Go to create a new deployment
- Click on the 'Resources' tab
- Type '4096' into the 'Memory limit' field
- Move the cursor to the beginning of the field (i.e. before the 4) and press delete
- Field updates to '96' and cursor jumps to end

Not sure why cursor jumps to end - the issue is that the leading 0 is being stripped off, so when you delete the in 4096, it is 096 which is 96 as an int.

We've seen issues elsewhere where this is happening because there is not a key set on a component, so Vue re-renders the UI components.

**Comment by cnotv** [comment]
This is a typical flow of the Zube automation, to reopen it and put it on Test.

**Comment by Josh-Diamond** [comment]
REOPENED; Would like to request QA Template to ensure accurate and thorough testing

---

Ticket #5186 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.4-rc3`:
1. Fresh install of rancher `v2.6.4-rc3`
2. Provision a downstream RKE2 cluster [any]
3. Once provisioned, create a new deployment
4. From Create [deployment] page, select `Resources` tab on the left
5. From `Resources`, add a `Memory Limit` of 4089
6. Delete the first digit from `Memory Limit` - [`4`]
7. Reproduced - Cursor jumps to the right and the 089 resolves to 89; `4098 => 89` - when 4 is removed

Screenshots:

`Step 5`
<img width="1253" alt="Screen Shot 2022-04-27 at 3 25 51 PM" src="https://user-images.githubusercontent.com/46494969/165642798-845afc5e-d140-4aa6-bdb1-ce4adb5df314.png">

`Step 7`
<img width="1249" alt="Screen Shot 2022-04-27 at 3 26 09 PM" src="https://user-images.githubusercontent.com/46494969/165642837-ba0e0259-c7c2-41a1-928f-886bbf7f6754.png">

---

Veri-FAILED on rancher `v2.6-311f4623b3c60f22daf281ce3fd4d4c31e5e07dc-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 cluster [any]
3. Once provisioned, create a new deployment
4. From Create [deployment] page, select `Resources` tab on the left
5. From `Resources`, add a `Memory Limit` of 4089
6. Delete the first digit from `Memory Limit` - [`4`]
7. Veri-FAILED - Cursor jumps to the right and the 089 resolves to 89; `4098 => 89` - when 4 is removed

Screenshots:

`Step 5`
<img width="976" alt="Screen Shot 2022-04-27 at 4 05 28 PM" src="https://user-images.githubusercontent.com/46494969/165646052-1f8025ad-8d51-4ea3-a741-be9469f132e6.png">

`Step 6`
<img width="1069" alt="Screen Shot 2022-04-27 at 4 08 33 PM" src="https://user-images.githubusercontent.com/46494969/165646076-da6af6d9-e93a-41f9-b1c7-0700fa1b797d.png">

**Comment by nwmac** [comment]
The delay has improved the use case of deleting a digit before a zero and then wanting to type a new digit - but this UntInput control has issues that we will need to look at in 2.6.6.

**Comment by cnotv** [comment]
I'll set it as blur as initially proposed, as it seems this is the only option with our configuration.

**Comment by Josh-Diamond** [comment]
@cnotv I just tried to validate on rancher `v2.6-head` - [`v2.6-0e2fdc8060bc74c278d7f043c7846297577fb92c-head`]
Fix does not seem be present

Do you know where I can find the fix?

Screenshot:
`Global Settings`
<img width="1333" alt="Screen Shot 2022-05-19 at 11 41 19 AM" src="https://user-images.githubusercontent.com/46494969/169376280-ca20e94a-f6a1-45f0-be84-12cffa0dc6fa.png">

**Comment by cnotv** [comment]
It's on rancher/dashboard master branch, so you will have to run your own client and not a deployed version, because this has not been released anywhere yet.

**Comment by richard-cox** [comment]
Rancher release-2.6 still points at the 2.6.5 dashboard branch. I'll update this tomorrow

**Comment by richard-cox** [comment]
Once [this](https://github.com/rancher/rancher/pull/37783) merges the fix should be available. 

Neglected to mention yesterday, you can do the same by
- clicking on three line burger menu top left
- clicking on `Global Settings`
- change `ui-dashboard-index` from `https://releases.rancher.com/dashboard/release-2.6.5/index.html` to `https://releases.rancher.com/dashboard/latest/index.html`

**Comment by Josh-Diamond** [comment]
Ticket #5186 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-6fda43e5eb3654cabf6294c9a57e0ecfdfc89520-head`:
1. Fresh install of rancher v2.6-head
2. Provision a downstream RKE2 cluster [any]
3. Once provisioned, create a new deployment
4. From Create [deployment] page, select Resources tab on the left
5. From Resources, add a Memory Limit of 4089
6. Delete the first digit from Memory Limit - [4]
7. Verified - Cursor no longer jumps until input field is no longer selected

Screenshots:

`Step 5`
<img width="1101" alt="Screen Shot 2022-05-23 at 9 25 26 AM" src="https://user-images.githubusercontent.com/46494969/169865055-59029817-5b0e-4398-8be7-53ca998b377f.png">

`Step 6`
<img width="1102" alt="Screen Shot 2022-05-23 at 9 25 39 AM" src="https://user-images.githubusercontent.com/46494969/169865164-b9746fbd-ca2a-4e2e-be5b-fc10e1a01909.png">

`Step 7`
<img width="1107" alt="Screen Shot 2022-05-23 at 9 25 50 AM" src="https://user-images.githubusercontent.com/46494969/169865201-e49e2b95-12c8-4edc-a9f7-b89349d6fff2.png">
