### ISSUE TITLE
Indicate what node architectures are supported by each Rancher chart

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5193]
Following up on https://github.com/rancher/dashboard/issues/5137, we'll leave that ticket tied to OS support related work. This ticket will focus on displaying architecture support in the Apps & Marketplace.

@mantis-toboggan-md has already been working on the original ticket, so the goal here is to compile the work for the UI to take the annotations tied to:
- `catalog.cattle.io/deploys-on-arch` (NEW): indicates that a chart needs global.cattle.ARCH.enabled to be set for the archs provided by a comma-separated list (No default)
- `catalog.cattle.io/permits-arch`: indicates that the chart is deployable onto clusters who have nodes with archs provided by a comma-separated list (Default if not exists: `catalog.cattle.io/permits-arch: amd64`)

I'll cross link the related tickets in an update below.

**Comment by gaktive** [comment]
Related PRs:

- Adding permits-os annotation to SRIOV: https://github.com/rancher/charts/pull/1736
- Add permits-os to System Upgrade Controller: https://github.com/rancher/charts/pull/1737
- Add permits-os Annotation to Istio: https://github.com/rancher/charts/pull/1748
- Add permits-os to logging: https://github.com/rancher/charts/pull/1749
- Add permits-os to Monitoring: https://github.com/rancher/charts/pull/1751
- Adding permits-os annotations to Longhorn charts: https://github.com/rancher/charts/pull/1745
- Adding permits-os annotations to the harvester charts: https://github.com/rancher/charts/pull/1744
- Adding permits-os annotations to the Rancher Webhook Chart: https://github.com/rancher/charts/pull/1743
- Adding permits-os annotations to the External IP Webhook Chart: https://github.com/rancher/charts/pull/1742
- Annotation update wins upgrader: https://github.com/rancher/charts/pull/1741
- Adding annotations to GMSA Chart: https://github.com/rancher/charts/pull/1735
- Add permits-os to Backup: https://github.com/rancher/charts/pull/1753
- Add permits-os to Alerting: https://github.com/rancher/charts/pull/1754
- Add permits-os to Gatekeeper: https://github.com/rancher/charts/pull/1756
- Add permits-os to CIS: https://github.com/rancher/charts/pull/1757
- add permits-os to vsphere-csi: https://github.com/rancher/charts/pull/1755
- Add permits-os to vsphere-cpi: https://github.com/rancher/charts/pull/1750
- Adding permits-os annotations to aks operator chart: https://github.com/rancher/charts/pull/1761
- Adding permits-os annotations to gke operator chart: https://github.com/rancher/charts/pull/1762

@mantis-toboggan-md let me know if I missed anything.

**Comment by mantis-toboggan-md** [comment]
I'm moving this out of 2.6.5 because the backend work wasn't completed. It looks like in all our ticket shuffling, we lost the backend request for this feature altogether. I've created a new issue here: https://github.com/rancher/rancher/issues/37231

**Comment by gaktive** [comment]
Duplicate of #9819 which has more immediate focus. Cross-linking to there so that once we work on that, we have context on prior efforts.
