### ISSUE TITLE
[rke2 templates] `edit options` only display when template originates from `rancher/cluster-template-examples` repo

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5195]
**Setup**
- Rancher version: v2.6-head (e55a04c)
- Browser type & version: chrome (but happens on any browser)

**Describe the bug**

when using RKE2 templates, the `edit options` only show when the repo is from our upstream branch, and now for others (i.e. a fork'd repo)

**To Reproduce**

* add the default example templates by going to 
  * go to create a cluster using the template and note that you see `edit options` with dropdowns, etc. available for the user
* add from a forked repo i.e. https://github.com/StrongMonkey/cluster-template-examples.git
  * observe that, when using this template, the user can only `edit as yaml`

**Result**
when using this (forked) template, the user can only `edit as yaml`

**Expected Result**

forked and any other valid git charts should be able to populate the `edit options`

**Screenshots**
forked repo:
<img width="475" alt="Screen Shot 2022-02-23 at 1 51 28 PM" src="https://user-images.githubusercontent.com/16691014/155414780-46967534-9cd9-4504-8fe0-fddc86853fa1.png">

upstream repo: 
<img width="569" alt="Screen Shot 2022-02-23 at 1 51 19 PM" src="https://user-images.githubusercontent.com/16691014/155414784-420264d4-9bb4-4975-9a90-34e33078d153.png">

**Comment by nwmac** [comment]
To reproduce:

- Go to cluster management -> Advanced -> Repositories
- Add a new repository with any name, target 'git', URL https://github.com/StrongMonkey/cluster-template-examples.git	 and branch main.
- Go to clusters -> Create ad chose the catalog template at the top (first option).
- You only get the Edit YAML view, not the questions.yaml file (edit options)

**Comment by nwmac** [comment]
@slickwarren This works for me with my fork hat I just created - https://github.com/nwmac/cluster-template-examples?organization=nwmac&organization=nwmac

The fork you mention does not contain the questions.yaml file that is in the upstream repository, which is why the edit config option is not available

**Comment by timhaneunsoo** [comment]
I was also unable to reproduce this issue and agree with @nwmac previous comments
![image.png](https://zube.io/files/rancher/5ac31416865e3dd3c06958f34df0cb9c-image.png)
