### ISSUE TITLE
Change fleet add repository TLS certification options to a dropdown

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#5198]
**Detailed Description**
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/1387263/155497384-4fa9255d-cd17-4d88-b1f5-8510999fc241.png">

**Context**
Change the radio button group for TLS Certificate options to a dropdown. This is part of the change related to rancher/dashboard#5197. No functionality change to the form. Only change is the how the options are selected.

**Comment by izaac** [comment]
This was tested in the scope of validation of a security issue.
Also this was tested during upgrade testing as part of the release tasks for 2.6.4

Upgrade was done from 2.6.3 to 2.6.4-rc8
