### ISSUE TITLE
Need KubeConfig button on Cluster dashboard

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#521]
We need to add a download kubeconfig button onto the Cluster Overview page.  Lauren can you take a look at the page and decide where it should be, and the button style type.  Then hand this over to Wes to implement.

**Comment by lvuch** [comment]
![Screen Shot 2020-04-17 at 2.45.06 PM.png](https://zube.io/files/rancher/d142d8fbc220ddf3ff701e05dc0d50a8-screen-shot-2020-04-17-at-2-45-06-pm.png)

**Comment by vincent99** [comment]
This is currently a Norman action and needs a Steve API.  See also interaction with the RFE to limit token lifetime.

**Comment by anupama2501** [comment]
@vincent99 Labels of the ticket still has "Waiting-backend" is the issue ready to test or are we still waiting on backend?

**Comment by vincent99** [comment]
Yes, it works.. There's a button in the top-right if you're in an individual cluster, or on the cluster management list you can select one or more clusters and get the config.  If you select multiple, they get merged together into one combined kubeconfig.

**Comment by anupama2501** [comment]
Verified on 5715b8a

- Created an rke2 node driver cluster from ember UI 
- From explorer --> cluster management --> cluster --> click on the three dots and download kubeconfig.yaml 
- From explorer --> explore cluster --> top right clicked on the page button and downloaded the kubeconfig.yaml
- From cluster management --> selected multiple clusters and clicked on download kubeconfig - kubeconfig file downloaded as a single file for different clusters.
