### ISSUE TITLE
Fleet: Add notification icon to Conditions tab on git repo to alert for an error

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5218]
Add a notification icon to the Conditions tab on the git repo details page, so that a user is alerted for the presence of any errors in the items belonging to that particular group _(check red faded box on image, which refers to the tabs where icon should be added)_

<img width="1601" alt="Screenshot 2022-02-25 at 15 55 32" src="https://user-images.githubusercontent.com/97888974/155746932-75d5c4a1-add0-49fc-aeb0-c92947ece22e.png">

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6-head 4df2214
Rancher cluster type:  HA

----------

### Testing: ###
Confirmed:
red icon with an exclamation point (so a user notices) appears on the "Conditions" tab if there is an error in conditions 
![conditions](https://user-images.githubusercontent.com/40282141/157121672-c14809db-0938-4272-b12b-5bceeb7d3931.jpg)

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
