### ISSUE TITLE
Need to add the Global navigation to the Select Cluster drop-down

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#522]
Need design of how we want the Main Drop-down to switch between Global and Individual Clusters.

This menu:
![image](https://user-images.githubusercontent.com/11514927/79608465-eb13e780-80a9-11ea-905a-71aeb1eb5ae8.png)

**Comment by lvuch** [comment]
<img width="382" alt="Screen Shot 2020-04-17 at 1 58 14 PM" src="https://user-images.githubusercontent.com/3013118/79613517-88274e00-80b3-11ea-8168-294721d6ade5.png">
<img width="381" alt="Screen Shot 2020-04-17 at 1 54 11 PM" src="https://user-images.githubusercontent.com/3013118/79613521-89587b00-80b3-11ea-8400-d402fe5e8d79.png">
<img width="381" alt="Screen Shot 2020-04-17 at 1 54 00 PM" src="https://user-images.githubusercontent.com/3013118/79613522-89f11180-80b3-11ea-82ef-7f001dd4997f.png">

**Comment by deniseschannon** [comment]
Based on new design, the new nav is completely different so closing this issue.
