### ISSUE TITLE
Allow switching between down stream clusters with a dropdown menu

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5229]
SURE-3657

Add ability to switch clusters without having to go to the slide-in menu and lose your context.

If you are on Apps & Marketplace (for example) for one cluster, we would like to be able to change cluster and keep that context.

UX design needed - but most likely making the cluster name a drop-down (arrow to right of name) which gives a drop-down control showing a list of clusters to select from.

Would be nice to keep the namespace/project context as well, where that is still valid for the new cluster.

**Comment by richard-cox** [comment]
When adding more content to the header we should keep in mind long cluster names, cluster tags and Rancher Desktop usages

**Comment by nwmac** [comment]
Might want to push to 2.6.6

**Comment by nwmac** [comment]
Need to think about what happens when you switch to a cluster where the context is not applicable - e.g. you are viewing an app page, or are looking at v2 monitoring and you switch to a cluster where the that app does not exist, or monitoring is not installed - suggest in these cases (which we would need to catch) we either go to cluster dashboard home or we show a page saying that the context is not applicable - this last option would allow users to change to another cluster and still keep context.

**Comment by catherineluse** [comment]
Capturing Kenneth's idea from the UX office hours yesterday:

- The cluster explorer top nav should have three dropdowns - one to select a cluster, one to select a project, and one to select a namespace.
- When one dropdown is changed, the other two should stay the same, unless the current selection no longer applies, in which case they should revert to default values.

**Comment by gaktive** [comment]
@kwwii to confirm if https://github.com/rancher/dashboard/issues/8418 addresses all the concerns in the related SURE-3657

**Comment by kwwii** [comment]
Closing this as it is a stale issue
