### ISSUE TITLE
Create constraint doesn't work from /constraints.gatekeeper.sh.template page.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#523]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable gatekeeper.
2. Create a constraint.
3. Click edit as yaml and cancel it.
4. Page lands on url/constraints.gatekeeper.sh.template. e.g.
```
https://rancher-server/dashboard/c/c-xxxx/constraints.gatekeeper.sh.k8srequiredlabels
```
5. Click create button.
<img width="1568" alt="Screen Shot 2020-04-17 at 5 06 07 PM" src="https://user-images.githubusercontent.com/60111667/79622855-e4976700-80cd-11ea-90e4-02d6c83c0ead.png">

**Result:**
Create page is blank.
<img width="1219" alt="Screen Shot 2020-04-17 at 5 06 50 PM" src="https://user-images.githubusercontent.com/60111667/79622867-f11bbf80-80cd-11ea-9b93-8782b2882b77.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): Single

**Comment by izaac** [comment]
Validated the fix in:

- Rancher version: 
  - `master-head (05/20/2020)` b85ea695f  
  - `2.4-head (05/20/2020)` 8e20687a4 with `CATTLE_DASHBOARD_INDEX=https://releases.rancher.com/dashboard/latest/index.html`
