### ISSUE TITLE
Fleet: Update colours of badges featuring counts in Fleet Dashboard view to convey status information

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5232]
Update colours of badges (seen on next image) featuring counts in Fleet Dashboard view to convey status information (colour of badge changes according to overall statuses)

<img width="1727" alt="154079960-9c05db60-7cf0-4f0b-9854-673ddc37ba04" src="https://user-images.githubusercontent.com/97888974/156016355-ed4d235d-4930-4e44-9a51-a070e87a3069.png">

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6-head 4df2214
Rancher cluster type: HA

Downstream cluster type: RKE1 and RKE2 node drivers

----------

### Testing: ###
By adding working and broken charts/repos I can see that colors of the badges change
![colors](https://user-images.githubusercontent.com/40282141/157129037-64ae6378-d18e-4d47-8cee-089ef75148a4.jpg)

What color badge is going to be depends on the state of the bundle/resource/cluster
Colors pre-defined based on the status
![colors1](https://user-images.githubusercontent.com/40282141/157129056-526ff68f-2bcb-4fb8-81a7-0738d4c1e6ca.jpg)

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
