### ISSUE TITLE
Quickly clicking between pages which contain lists can produce a console error

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5240]
**Describe the bug**
```
actions.js?0442:105 Uncaught TypeError: Cannot read properties of undefined (reading 'querySelector')
    at VueComponent.eval (actions.js?0442:105)
    at invokeFunc (debounce.js?b047:95)
    at trailingEdge (debounce.js?b047:144)
    at timerExpired (debounce.js?b047:132)
```
Probably caused by the `$ref.container` being unavailable either because we've already left the page before `mounted` has run or we run too quickly on the new page before it's available. In either case the bulk actions which depend on the function do successfully render. So we just need null/undefined checks

**To Reproduce**
- Navigate to the explorer product
- quickly flick between workload pods and workload stateful sets

**Comment by nwmac** [comment]
@aalves08 Can you take care of this - its a simple fix - check in with @richard-cox if needed

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

- Navigate to the explorer product
- quickly flick between workload pods and workload stateful sets
- No error seen in the console
