### ISSUE TITLE
Page loading indicator covers the window manager

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5245]
**Describe the bug**
The page loading indicator covers the window manager tabs

**To Reproduce**
- Open up any window manager, for instance a shell in to a kube cluster
- Navigate anywhere the page loading indicator is shown
  - any page in the explorer that loads a resource not seen before (tweaking the dev tools network tab connection speed may help to increase the time the loading indicator is shown) 

**Result**
![image](https://user-images.githubusercontent.com/18697775/156189696-ddf2d5eb-4f05-4b08-a208-9a7258c134a2.png)

**Comment by richard-cox** [comment]
Note - From memory there are different contexts of the loading indicator. Some probably should appear over the window manager (global)... some might not (context).

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

This isn't reproducible on this Rancher version, I've tried throttling the network speed and the adding resources to trigger a slow loading of a page after opening a pod's logs.
