### ISSUE TITLE
Json blob show on chart install page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5248]
Go to Cluster Tools > Click on 'Install' on V2 Monitoring - you get a blob of JSON shown:

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/1955897/156212253-3ab423a4-25be-41b0-8ccb-26cbe1a611d9.png">

**Comment by sowmyav27** [comment]
https://github.com/rancher/dashboard/issues/5249#issuecomment-1075513076
