### ISSUE TITLE
Chart install page for monitoring shows [object Object]

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5249]
Once this issue is fixed:https://github.com/rancher/dashboard/issues/5248 you'll see this:

Go to Cluster Tools -> V2 Monitoring install

The Version select input show '[object Object]' - see below:

<img width="952" alt="image" src="https://user-images.githubusercontent.com/1955897/156212720-0ebdef60-c804-4d38-b698-93b1dcf3bccf.png">

**Comment by richard-cox** [comment]
This should be tested alongside #5248
