### ISSUE TITLE
[TS] Investigate Typescript component patterns

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5250]
- Investigate each type of component pattern (class, composition api, script, anything other that might be interesting) 
- Understand support in both Vue 2, Vue 3 and beyond

The output of this issue should be
- a confluence page answering the above, including good/bad/ugly with each option. 
- a set of examples of each type that exercise a good range of features (equivalents to props, computed, methods, templates, style, etc)

We will then use all of this with the team to decide on which type to use for existing and new components (converting existing types is up for debate)

**Comment by cnotv** [comment]
Yesterday I was already adding something around about Vue and Typescript, in case you were interested, but a clear list is definitely better.

**Comment by cnotv** [comment]
As was not possible to make work correctly the bins, I've created a repo with all the versions, so we could eventually try them out.
The link is also in Confluence.
https://github.com/cnotv/vue-typescrpt-playground

**Comment by cnotv** [comment]
As note from the talk, we want to add an example of how our current mixin are going to be changed in Composition API (Vue2/3) in our playground.
https://github.com/cnotv/vue-typescrpt-playground/blob/main/typescript-vue2/src/mixins/mixin.ts

**Comment by cnotv** [comment]
> Another important aspect to investigate, would be the use of new features in Vue 2.7, thanks @rak-phillip to point it out.

It seems like there's still a LOT of features not ported to 2.7.0, based on the [this blog release article](https://blog.vuejs.org/posts/vue-2-7-naruto.html).

**Comment by cnotv** [comment]
@richard-cox Added examples about mixins replacement for our form (CRU) API
https://github.com/cnotv/vue-typescrpt-playground/blob/main/typescript-vue3/src/components/CompositionApi.vue

**Comment by cnotv** [comment]
@richard-cox do we need any other investigation for this issue or can we consider it solved?

**Comment by richard-cox** [comment]
This can be closed. That example repo is linked in confluence right? Think I remember seeing it there
