### ISSUE TITLE
[TS] Investigate Pinia and Vuex 5

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5251]
- Current train of thought is to migrate to Pinia and in the future easily swap to Vuex 5. Find proof that the spec's are the same and there's no  (they're both based on the same spec)
- What's the roadmap for Vuex 5?
- Is Pinia fully compatible with Vue 2 and 3? Are there any performance issues when used with either? 
- Can Pinia be used with Nuxt?
- This might not be possible, but how can Pinia be used with existing vuex methods?
  - The aim is to avoid changing old JS components when they access the store via $store

The output of this issue should be
- A confluence page answering the above questions

We will use this doc to suggest a way to integrate TS with the store

**Comment by gaktive** [comment]
Nuxt needs to be removed first.

**Comment by richard-cox** [comment]
Closing for now, we can create a new issue when we look to update vuex
