### ISSUE TITLE
Info box at top of Overview page should be set height and not grow with browser

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#526]
steps:
1.  Go to overview page
2.  Increase the height of your browser

Results:  The info bar at the top grows.  this should have some sort of fixed height.
 
![image](https://user-images.githubusercontent.com/11514927/79790117-1bed5a00-8300-11ea-8808-edbc3b3075c2.png)

**Comment by deniseschannon** [comment]
Fixed in `master`
