### ISSUE TITLE
rke2 snapshot names are too long

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5260]
**Setup**
- Rancher version: v2.6-head (e93a53c)
- Browser type & version:any

**Describe the bug**

Currently rke2 snapshots are named in the following format: <etcd-snapshot-name>-<node-name>-<timestamp-in-unix-time> Expected: The name seems redndant with nodename + cluster name and is also difficult to read. 

**To Reproduce**

* create an rke2 cluster with multiple etcd nodes
* take a snapshot

**Result**
names are long and not human-reader friendly. 

**Expected Result**
we should shorten the names

**Comment by Oats87** [comment]
https://github.com/rancher/rancher/pull/36707 moves the snapshot file name to an annotation -- either this or we should display the snapshotfile.name rather than the CR name.
