### ISSUE TITLE
RKE2 snapshots should not have a `delete` option in the UI, currently unsupported in the backend

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5262]
**Setup**
- Rancher version: v2.6-head (e93a53c)
- Browser type & version:any

**Describe the bug**

currently, there is an option in the UI to delete a snapshot for rke2 clusters, however that is currently unsupported. 

**To Reproduce**

* deploy an rke2 cluster
* create a snapshot of the cluster
* delete the snapshot through the UI

**Result**
the snapshot will not be removed

**Expected Result**

currently, we should remove the `delete` option from the UI until the backend has a solution for delete
rancher/dashboard#5338

**Screenshots**
<img width="1541" alt="Screen Shot 2022-03-01 at 2 20 15 PM" src="https://user-images.githubusercontent.com/16691014/156260658-7c1e2ea5-1b99-4d47-853e-10f78637e534.png">

**Comment by nwmac** [comment]
@cnotv To fix this - look in `models/etcdbackup.js` in `_availableActions` we need to remote the 'delete' action.

If you look in `models/catalog.cattle.io.operation.js` you will see an example of removing the 'remove' action.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

- Delete snapshot is not available on the snapshot on the UI on an RKE2 cluster
<img width="1402" alt="Screen Shot 2022-03-13 at 10 36 44 PM" src="https://user-images.githubusercontent.com/26032343/158070812-5ad81330-4deb-4dae-8d11-c47ceb266ebd.png">
