### ISSUE TITLE
"Learn more about the ports that will be opened" link gives 404 error

### ISSUE THREAD

**Issue by Auston-Ivison-Suse** [rancher/dashboard#5263]
**Setup**
- Rancher version: v2.6-head(e93a53c)
- Browser type & version: Google Chrome: Version 98.0.4758.109

**Describe the bug**
When reaching step three of creating a node template you are presented with a choice to choose security group selection.
The link provided to learn more about ports is broken. 

**To Reproduce**
1. Start provisioning a cluster using rke1 and ec2(aws)
2. get to the security group section and click the link

**Result**
A page with a 404 error

**Expected Result**
The link should send us to a proper part of the rancher documentation.

**Screenshots**

The link.
<img width="788" alt="LearnMorePortsLink" src="https://user-images.githubusercontent.com/89411550/156286766-af2928e2-f0c1-45d0-9cd7-ce4c8ec0095f.png">

The Resulting 404 error:
<img width="1285" alt="LearnMoreAboutPortsLinkDead" src="https://user-images.githubusercontent.com/89411550/156286760-21225fe3-042f-4b05-a565-052646663b0b.png">

**Comment by nwmac** [comment]
Duplicate of #5017

**Comment by Auston-Ivison-Suse** [comment]
**Validation Setup**
- rancher version: v2.6.4-rc9
- Browser:Chrome Version 99.0.4844.74

**Validation Steps**
1. Start provisioning a cluster using rke1 and ec2(aws)
2. get to the security group section and click the link

**Result**
We are taken to the following: [Rancher Docs Port Requirements](https://rancher.com/docs/rancher/v2.5/en/installation/requirements/ports/#rancher-nodes)

**Notes**

I was the one to submit the original issues (granted it appears it's a duplicate) closing with just a validation for the issue.
