### ISSUE TITLE
Snapshot's age  is missing in the dropdown window during etcd restore in rke2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5264]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `e93a53c`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r1`
- Cluster Type (Local/Downstream): Downstream DO Node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**Description**

- Deploy an rke2 cluster - 3 etcd, 1 cp, 3 worker nodes
- when cluster comes up Active, take some manual snapshots
- Restore from one of the snapshot
- The dropdown is seen with snapshots names only.

<img width="712" alt="Screen Shot 2022-03-01 at 11 58 24 PM" src="https://user-images.githubusercontent.com/26032343/156319331-1b15f31a-98e8-46f2-8ba0-74db608c25b9.png">

- Can we display when the snapshot was taken? Making it easier for users to choose?

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head d604b7e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: EC RKE2 aws node driver

----------

### Testing: ###

Tested this issue with the following steps:
1. Deployed an ec2 node driver RKE2 cluster on rancher - 3 etcd, 2 cp and 3 worker nodes
2. Take a snapshot
3. Snapshots are listed in Cluster management --> Cluster details --> Snapshots tab
4. Click on Restore on the cluster
5. The snapshot options in dropdown list

**Result** - Pass

The timestamps are showing as expected
![image.png](https://zube.io/files/rancher/23efa1dac0175b9e377280228bcaeeae-image.png)
