### ISSUE TITLE
Cron Job's description not available in recurring snapshots section in rke2 cluster config

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5266]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `e93a53c`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r1`
- Cluster Type (Local/Downstream): Downstream DO Node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**Description**

- Create an RKE2. cluster
- the cron under etcd tab in the cluster config does not have the cron's description/value
<img width="892" alt="Screen Shot 2022-03-02 at 12 06 48 AM" src="https://user-images.githubusercontent.com/26032343/156320781-831b4a7e-eeb9-42e6-9906-ba2e9d0d54a7.png">

- Can we have a description that we see during cron Job (deployment's) page? Like this:
<img width="1677" alt="Screen Shot 2022-03-02 at 12 05 32 AM" src="https://user-images.githubusercontent.com/26032343/156320859-530b1ba2-ebff-4a25-a900-4996dedb13bf.png">

**Comment by Josh-Diamond** [comment]
Ticket #5266 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.4`:
1. Fresh install of rancher `v2.6.4`
2. Provision a downstream RKE2 cluster
3. Reproduced - `Cluster Configuration => Etcd` - No Cron Schedule description present

Screenshot:
<img width="1559" alt="Screen Shot 2022-05-13 at 9 22 05 AM" src="https://user-images.githubusercontent.com/46494969/168328113-7a73255a-366a-4354-a299-b0e71472dbe3.png">

---

Verified on rancher `v2.6-7d4bfd887f927396ccc882490153ef7c9223b3a9-head`:
1. Fresh install of rancher `v2.6-head`
5. Provision a downstream RKE2 cluster
6. Verified -  `Cluster Configuration => Etcd`-  Cron Schedule description is present

Screenshot:
<img width="1562" alt="Screen Shot 2022-05-13 at 9 04 49 AM" src="https://user-images.githubusercontent.com/46494969/168323684-99d473ed-0e49-4bae-9818-9392e92228dd.png">
