### ISSUE TITLE
Sorting in Age column in Snapshot page does not work 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5267]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `e93a53c`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r1`
- Cluster Type (Local/Downstream): Downstream DO Node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**Description**

- Create an RKE2. cluster
- Take some manual snapshots
- Navigate to Cluster Management --> Cluster details --> Snapshot --> Sort the Age column
- This column does not sort as expected.

**Comment by cnotv** [comment]
It seems like in some cases snapshots are not sorted correctly, while the rest does.


https://user-images.githubusercontent.com/5009481/157012238-7485d882-d8bb-4c08-85f7-48eb8c8a3403.mp4

**Comment by cnotv** [comment]
It finally seems like the logic adopted allows list sorting by multiple paths of keys.
For the creation is not correctly implemented: `createdAt` instead of `snapshotFile.createdAt`.

Investigating where these values are defined.

**Comment by rak-phillip** [comment]
@cnotv this sounds like it's related to updated snapshot api that was introduced in #5196. Consider inspecting `getEtcdSnaphsot()` in `models/provisioning.cattle.io.cluster.js`.

#5260 also seems like it might have been loosely related

**Comment by cnotv** [comment]
Yeah I noticed that already and fixed as well :sweat_smile: 

The issue you mentioned does not seem to affect it.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

Sorting on Age column in Snapshot page works.
