### ISSUE TITLE
Fleet: Unable to assign clusters to a new workspace

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#5280]
**Setup**
- Rancher version: v2.6 `1d2b746` 3/2/2022
- Browser type & version: Firefox, latest, linux

**Describe the bug**

While on the Continuous delivery page -> clusters I cannot assign any clusters to a new workspace. I can check off one or more and click the "Assign to..." button and get a 200 OK on my PUT request but nothing happens. No errors in browser dev console or in rancher server logs.

**To Reproduce**

1. Create one or more downstream clusters
2. Create a new workspace
3. On the Clusters page in CD, try to assign it to the new workspace you created. This creates a PUT request that gets a 200 OK response.

**Result**
Nothing happens. The PUT request is sent and ack'd with 200 OK, but we don't see the cluster actually get assigned to the new workspace in the UI - even if refresh the page.

**Expected Result**

I expected the cluster to get assigned to the workspace upon a 200 OK.

**Screenshots**

**Additional context**
Since the request appears to go thru correctly, I suspect this might be some issue in Vue / JS?

**Comment by nwmac** [comment]
@aalves08 This is a backend issue, right? Can we link it and move this to backend-blocked.

**Comment by aalves08** [comment]
Correct @nwmac . Here is the backend issue: https://github.com/rancher/rancher/issues/36132

**Comment by gaktive** [comment]
Related backend work now pushed to 2.6.5.

**Comment by aalves08** [comment]
As per comment on BE issue, this will be pushed out from 2.6.6:
https://github.com/rancher/rancher/issues/36132#issuecomment-1137848982

**Comment by richard-cox** [comment]
Backend issue now closed. I don't think there's anything UI side to do, so moving this to test

**Comment by nickwsuse** [comment]
Verified on v2.8-head ID: 5b42ca5 ✅ 
----
Setting a cluster to a new workspace is working as expected and is actually re-assigning the cluster to the new workspace.
