### ISSUE TITLE
Show container error message on Containers table for a pod

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5285]
The containers list on the pods detail view does not show error messages for the containers.

To see:

Create a deployment with a pod with an image that does not exist.

e.g. Deployment name 'test', image: 'does-not-exist'

Go to Deployments -> select the deployment -> on the pods list, select the pod

![image](https://user-images.githubusercontent.com/1955897/156542681-3632569a-4aa2-4791-a8cc-e7bf656d7d0b.png)

We show that the container is not ready, but we don't show the error below.

Looking at the YAML for the pod, there is a an error message for the container in the `containerStatuses`, e.g.

```
"containerStatuses": [
{
"image": "no-such-image",
"imageID": "",
"lastState": { },
"name": "container-0",
"ready": false,
"restartCount": 0,
"started": false,
"state": {
"waiting": {
"message": "Back-off pulling image \"no-such-image\"",
"reason": "ImagePullBackOff"
}
}
}
],
```

Weshould show this in an error row beneath the container row using the standard `stateDescription` mechanism.

This needs to be added in `detail/pod.vue` in the `containers()` computed property.

**Comment by cnotv** [comment]
It is unclear why, but based on the complex component we adopt, it's required to define the [status 3 times](https://github.com/cnotv/dashboard/blob/feature/5285-display-pod-containers-status-message/detail/pod.vue#L62-L73).

Anyhow it should be fine given the result.

**Comment by igomez06** [comment]
**Setup:**
Rancher Version: v2.6.5-rc6
Kubernetes Version: RKE2 v1.22.8+rke2r1
HA Install

**Steps:**
1. Created a deployment with name 'newtest', image: 'does-not-exist'
2. Got two errors `ImagePullBackOff (Back-off pulling image "does-not-exist")` and `ErrImagePull (rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/does-not-exist:latest": failed to resolve reference "docker.io/library/does-not-exist:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed)`
show at different times

![Screen Shot 2022-05-02 at 5.00.35 PM.png](https://zube.io/files/rancher/5cac120674d212a3408f93997054b8f2-screen-shot-2022-05-02-at-5-00-35-pm.png)![Screen Shot 2022-05-02 at 5.00.55 PM.png](https://zube.io/files/rancher/552477ffc653bdc4ba394c51aa1cbb59-screen-shot-2022-05-02-at-5-00-55-pm.png)

**Comment by igomez06** [comment]
@cnotv is it expected to see both errors?

**Comment by richard-cox** [comment]
@igomez06 This change means that whatever error message is provided by the backend is displayed in the front end. I'm not sure what specific message/s these should be for this error, but that fact that is shows them should be good enough.
