### ISSUE TITLE
Visually distinguish between namespaced and non-namespaced resources

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5287]
Follow-on work from 2.6.4:

Add a badge next to cluster-level resources when a namespace is selected (+ tooltip), so that the user knows they are viewing a cluster-resource and that the namespace filter does not apply - see design from @lvuch

This should all be done with the changes to add top-level icons to the navigation and remove the 2nd-level nav icons.

**Comment by lvuch** [comment]
Adding same note from 5147:
This fix should also include nav accessibility as noted here - https://github.com/rancher/dashboard/issues/4388

**Comment by nwmac** [comment]
check in with @nwmac before starting on this ticket
