### ISSUE TITLE
Dashboard Overview doesn't display metrics of the local HA cluster

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#529]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a HA K8s Rancher install. (master-head (04/20/2020) commit id: 8bd924599
2. Navigate to legacy dashboard once the `local` cluster is available.
3. Legacy shows CPU/Memory/Pods
4. Navigate to the new Dashboard Overview

**Result:**

The Dashboard Overview doesn't show the same metrics as the legacy Dashboard for the `local` HA Cluster.

![Screen Shot 2020-04-20 at 1 24 05 PM](https://user-images.githubusercontent.com/27659/79796380-4e9c5000-830a-11ea-81b2-867d02e84111.png)

![Screen Shot 2020-04-20 at 1 24 25 PM](https://user-images.githubusercontent.com/27659/79796409-5c51d580-830a-11ea-8c60-22b2c1ab5e7b.png)

**Environment information**
- Rancher version: master-head (04/20/2020) commit id: 8bd924599 (master-2783-head)
- Installation option (single install/HA): HA with K8s cluster.

**Comment by westlywright** [comment]
I am not able to reproduce the missing top info box and I've asked @izaac for more info on reproducing this. 

On my setup built off master-head (4/21/2020) I do see the top boxes but the info is all zero as indicated by the image below. The cluster resource fetched from `steve` is returning zeros for `capacity`, `requested`, & `allocatable`, the fields we use to derive all this data. On the `norman` side the data or some estimation of it is being returned. 

@vincent99 Should we open an api ticket? I am not sure if this is a limitations of steve in regards to accessing the local cluster or a bug? 

![Screenshot 2020-04-22 14 53 10](https://user-images.githubusercontent.com/858614/80039344-74615a80-84ac-11ea-8270-10f40093ca1a.png)

**Comment by izaac** [comment]
It seems this is only affecting k8s based local HA clusters.

**Comment by westlywright** [comment]
@izaac is correct, k8s based clusters are missing a couple params causing an undefined error which in prod apparently causes the component to not render (pretty cool!).

**Comment by izaac** [comment]
Rancher version: master-head (04/28/2020) commit id: rancher/rancher:14013a8d0

Metrics section is now visible in HA k8s local cluster.
