### ISSUE TITLE
Unable to set global role as a default role 

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/dashboard#5291]
**Setup**
- Rancher version: v2.6.4-rc4
- Browser type & version: Chrome Version 98.0.4758.109 (Official Build) (x86_64)

**Describe the bug**
When attempting to set a global role to the default for new users, the radio button is unable to be changed (either from yes to no, or no to yes).

**To Reproduce**
1. Launch rancher/rancher:v2.6.4-rc4
2. Login as an admin user
3. Open the sidebar, and select `Users & Authentication`
4. In the side menu, select `Roles`
5. In the resulting menu, choose a global role and click on the display name.
6. In the resulting screen, click the 3 dots at the upper right hand of the role and select "Edit Config".
7. In the resulting screen, attempt to change the value in the `New User Default` section (either from true to false or false to true).

**Result**

Regardless of the user's role, the Global Role's status as the New User Default cannot be changed.

**Expected Result**

The Global Role's status as the New User Default should be able to be changed (i.e. your choice should take effect and the role should be able to be altered).

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/95644600/156648604-adec4521-7019-4bd0-9309-80439c70cf9f.png)

**Additional context**
- The following error is displayed when trying to click the button:
```
TypeError: Cannot use 'in' operator to search for 'newUserDefault' in null
    at Function.Pt [as set] (vue.runtime.esm.js:1076:7)
    at value (management.cattle.io.globalrole.js:54:9)
    at Qt (vue.runtime.esm.js:1854:26)
    at f.n (vue.runtime.esm.js:2179:14)
    at Qt (vue.runtime.esm.js:1854:26)
    at f.t.$emit (vue.runtime.esm.js:3888:9)
    at f.clicked (RadioButton.vue:84:12)
    at click (RadioButton.vue?7efb:1:547)
    at Qt (vue.runtime.esm.js:1854:26)
    at HTMLLabelElement.n (vue.runtime.esm.js:2179:14)
```
- Error is not present on the old UI
- Error does not occur in 2.6.2, but does in 2.6.3 (in other words, looks like this started with 2.6.3)

**Context**
Users may wish to change the default global role to ensure that new users are allocated a common selection of permissions (by default). With this bug in place, it is difficult for users to do so.

**Comment by richard-cox** [comment]
Can no longer reproduce

**Comment by aalves08** [comment]
Debatable, probably, but seems testable through an e2e to cover a possible regression scenario in the future. Adding `automation-candidate`.

**Comment by izaac** [comment]
The updated E2E test covers this scenario properly. Moving to Done.
