### ISSUE TITLE
UI Cluster badges have cut off custom description when using long descriptions

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#5293]
v2.6-head `1d2b746` 3/3/2022

New custom cluster badges allow the user up to 32 chars in the description field, however if we utilze all 32 chars, often Vue will cut this off.

I would argue that this should not be intentional - if so why do we limit to 32 and not somethign like 24 or 28 chars so we can avoid the ...?

![image](https://user-images.githubusercontent.com/45179589/156666151-a178d70d-cc6e-484d-9417-8baf079750af.png)

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

There is a limit on the Custom Description and Icon Text field
<img width="1674" alt="Screen Shot 2022-03-13 at 10 25 55 PM" src="https://user-images.githubusercontent.com/26032343/158070403-46e4e979-c532-4da1-8d2d-890dda561700.png">
<img width="604" alt="Screen Shot 2022-03-13 at 10 26 50 PM" src="https://user-images.githubusercontent.com/26032343/158070401-91253ff7-aa9f-41c4-be0c-53c8aa98145b.png">
<img width="550" alt="Screen Shot 2022-03-13 at 10 27 00 PM" src="https://user-images.githubusercontent.com/26032343/158070399-ed6baa2c-0dcf-483e-80d2-149f2bf1a0bd.png">
