### ISSUE TITLE
Add note regarding RKE2/k3s provisioning behavior with link to documentation

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#5296]
**Detailed Description**

Add information/warning when editing RKE2/k3s-provisioned clusters with the link to the documentation to be created per https://github.com/rancher/docs/issues/3925.
It should be along the lines of "Making changes to cluster configuration may result in nodes reprovisioning. For more information see documentation (link)".

**Context**
RKE2/k3s provisioning behavior doesn't always that of RKE1 provisioning Rancher users are used to, so it makes sense to proactively notify users, at least in the most important places.

**Comment by catherineluse** [comment]
@jtravee do you have the link to these docs?

**Comment by nwmac** [comment]
@snasovich Is the doc going to get done for 2.6.4? We need some lead time to get this in.

**Comment by jtravee** [comment]
> @jtravee do you have the link to these docs?

As discussed in Slack, we'll be making a new page for [RKE2 cluster provisioning]( https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke2-clusters) wherein we can document this issue.

**Comment by nwmac** [comment]
TODO on this ticket:

On the edit page for an RKE2/K3s cluster, show an info box at the top of the page with the text:

Making changes to cluster configuration may result in nodes reprovisioning. For more information see documentation (link)". Where link is: https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke2-clusters

Notes:
- The page handles both create and edit, so should only show on edit
- There is a pattern for doc links that takes care of the base URL of the link - you should be able to find examples in the en-us.yaml i18n file

**Comment by snasovich** [comment]
Thank you for handling this @nwmac @jtravee !

**Comment by jtravee** [comment]
> TODO on this ticket:
> 
> On the edit page for an RKE2/K3s cluster, show an info box (Banner component) at the top of the page with the text:
> 
> Making changes to cluster configuration may result in nodes reprovisioning. For more information see documentation (link)". Where link is: https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke2-clusters
> 
> Notes:
> 
> * The page handles both create and edit, so should only show on edit
> * There is a pattern for doc links that takes care of the base URL of the link - you should be able to find examples in the en-us.yaml i18n file

Hi @nwmac and @catherineluse, after working through this issue a bit more, we decided to not create a new page at this time but rather a new section to place an overview of general RKE1 v. RKE2 diffs (with this issue being included there). This new link will be [here](https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/).

**Comment by catherineluse** [comment]
@snasovich If you see a warning about nodes reprovisioning, and you click a link for more information, why would you click that link? What would you expect to see? Information about how to do a zero downtime upgrade?

**Comment by sowmyav27** [comment]
Reopening so [this](https://github.com/rancher/dashboard/issues/5296#issuecomment-1065616457) can be implemented

**Comment by cnotv** [comment]
@sowmyav27 @jtravee the [link provided](https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/) is 404.
Could you set the page first, so we are sure that is correct?

**Comment by jtravee** [comment]
> @sowmyav27 @jtravee the [link provided](https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/) is 404. Could you set the page first, so we are sure that is correct?

The link is not in place yet; the [PR](https://github.com/rancher/docs/pull/3947) is in review now that will enable the link to be active. I just wanted to give the team the tentative link ahead of time to work off of.

**Comment by snasovich** [comment]
> @snasovich If you see a warning about nodes reprovisioning, and you click a link for more information, why would you click that link? What would you expect to see? Information about how to do a zero downtime upgrade?

@catherineluse , not sure I'm following the question. Clicking the link should open new tab with URL that Jen provided that explains more about RKE2 <-> RKE1 differences.

**Comment by catherineluse** [comment]
I was just asking what's the point of linking to the docs in the first place? If the docs don't explain how to prevent downtime, then why would someone want to go to the docs from there?

**Comment by jen** [comment]
Hi y’all, I’m @jen, but not this project's Jen.  —Jen

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `024e6fa`**

- Deployed a k3s node driver cluster
- Edit cluster config
<img width="1680" alt="Screen Shot 2022-03-21 at 12 40 13 AM" src="https://user-images.githubusercontent.com/26032343/159178743-afcfed32-50a9-4fd9-af2b-56ed41e69f77.png">

- Link redirects to `https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/`
