### ISSUE TITLE
Fleet: Add icons to badges on Fleet Dashboard

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5299]
To better convey the notion of status for each resource type displayed on the Fleet dashboard, one should add icons to represent each status in order to reinforce that idea to the user

**Currently**
<img width="1670" alt="Screenshot 2022-03-04 at 11 02 19" src="https://user-images.githubusercontent.com/97888974/156752023-900781a3-988e-4df6-bd86-581d98fee265.png">

**How it should be**
<img width="1816" alt="Screenshot 2022-03-04 at 10 36 15" src="https://user-images.githubusercontent.com/97888974/156752168-830cf2ba-d00f-4df2-a78f-c8ed6a994395.png">

**Comment by aalves08** [comment]
PR here: https://github.com/rancher/dashboard/pull/5298

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**
<img width="1680" alt="Screen Shot 2022-03-14 at 12 13 32 AM" src="https://user-images.githubusercontent.com/26032343/158074417-534143d0-cb44-4013-877f-c3816810a8f2.png">

Icons are available on Fleet Dashboard
