### ISSUE TITLE
Issues in "Machine Pools" section when creating an RKE2 node driver cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5304]
**On 2.6head commit id: `4df221`**

- Create cluster --> RKE2.
- Select DO node driver cluster

**Issue 1**

- Add a few machine pools - pool2 and pool3
- Try to switch to pool1
- When hovering over machine pool1's name, the mouse pointer changes in to the `hand` but user is able to click on the _ONLY_ when the cursor is above the text `pool1` and not in any other part in that field

**Expected:**
User should be able to click on pool1, by pointing anywhere in the field

<img width="643" alt="Screen Shot 2022-03-07 at 1 04 25 AM" src="https://user-images.githubusercontent.com/26032343/156939204-02d8c08f-7893-4868-8e32-31d8f081f0fb.png">

**Issue 2**
`+` and `-` icons is not fitting the width of the machine pools section

**Expected:**
Can we make the icons to fit the width of the pools section? 
<img width="389" alt="Screen Shot 2022-03-07 at 1 05 59 AM" src="https://user-images.githubusercontent.com/26032343/156939296-f3c74ebc-1cfa-4b8d-bd75-1442f69b6625.png">

**Comment by richard-cox** [comment]
Partially (issue 2) covered by https://github.com/rancher/dashboard/issues/5303. Both should be fixed at the same time.

As this is visual and not functional I'm bumping out to 2.6.5 as per the other issue.

@nwmac / @gaktive It would be really good if we could get these done for 2.6.4, maybe by someone new to the dashboard?

**Comment by aalves08** [comment]
Fixed by PR https://github.com/rancher/dashboard/pull/5308

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

- Issue 1 and 2 are fixed
<img width="374" alt="Screen Shot 2022-03-14 at 12 15 29 AM" src="https://user-images.githubusercontent.com/26032343/158074472-3fd10ef4-ffaf-46d3-b2c6-d1a52cae0895.png">
