### ISSUE TITLE
Resources count is incorrect in Namespace Details page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5305]
**On 2.6-head commit id: `4df2214`**

- Deploy an RKE2 cluster
- Navigate to cluster explorer --> Project and namespaces --> cattle-system namespace
- Resources count is seen as `0`
- But there are resources that are active in this namespace
<img width="1655" alt="Screen Shot 2022-03-07 at 5 16 32 AM" src="https://user-images.githubusercontent.com/26032343/156947593-855c4b65-c392-4e9e-9b03-c484153d9a0e.png">

**Comment by nwmac** [comment]
@sowmyav27 I could not reproduce this.

Could you try again and include the browser console log if you still see this.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f90426`**

- Resource count is correct.. No issues seen
<img width="1442" alt="Screen Shot 2022-03-13 at 11 54 39 PM" src="https://user-images.githubusercontent.com/26032343/158073716-9177493a-c6e4-4f2c-bce1-6ed942bce991.png">
