### ISSUE TITLE
Intermittent error "Unknown schema for type: management.cattle.io.cluster" when refreshing page

### ISSUE THREAD

**Issue by sgapanovich** [rancher/dashboard#5313]
**Setup**
- Rancher version: v2.6-head 
- Browser type & version: Chrome Version 98.0.4758.109

**Describe the bug**

When refreshing page there is an Intermittent error "Unknown schema for type: management.cattle.io.cluster".
_It seems to me_ the error occurs after a new cluster is provisioned or/and nodes added/removed
It's hard to reproduce 
I usually had RKE2 clusters when issue occurred 

**Result**
URL when error occurs: `https://rancher_url/dashboard/fail-whale`
Error text: Error Unknown schema for type: management.cattle.io.cluster
![error](https://user-images.githubusercontent.com/40282141/157078894-e1bf534f-4ba5-4f73-aec5-65d091197f87.jpg)

All API calls have successful response codes 
There are no errors in the console
![console and network tools](https://user-images.githubusercontent.com/40282141/157078906-6d53d059-8212-4bab-9241-10cea70c4f61.jpg)

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

- Refreshed webpage after cluster creation, after scaling down/up nodes.
- This error is not seen
- Tried multiple times.
- Will close the issue now. Will lo a new one if this is seen again.
