### ISSUE TITLE
UI allows Deployments > Storage yaml creation and mountPath name

### ISSUE THREAD

**Issue by neillsom** [rancher/dashboard#5317]
- Mount Point (mountPath in yaml) is a required field, but doesn't show they key in yaml until the field is populated.
- Editing the Volume Name erases Mount Point input. 

![2022-03-07_15-12-10 (1)](https://user-images.githubusercontent.com/13671297/157126784-49383aca-1e92-4b80-a788-163f180f809d.gif)

**Comment by nwmac** [comment]
To reproduce:

- Go to create a new deployment
- Go to the storage tab and select 'Persistent Volume Claim'
- Type something into the mount point field
- Edit the 'Volume Name'

The mount point and sub path and read-only fields are all reset.

**Comment by nwmac** [comment]
@cnotv Can you take a quick look - not high-priority, so if not an easy fix, then we will push out to 2.6.6.

**Comment by cnotv** [comment]
If I try to add the storage with all the requirements I get this:

`Cannot read properties of undefined (reading 'nvidia.com/gpu')`

![Screenshot from 2022-03-29 14-47-57](https://user-images.githubusercontent.com/5009481/160614662-f1a3ba9e-8cc9-4be2-a7db-79890ecbc3ec.png)

**Comment by nwmac** [comment]
@cnotv Are you up to date with master? There were some fixes for this.

**Comment by cnotv** [comment]
This error is still there, but the message is different. If a mount point is required, we should disable the remove button for the last item. 

![Screenshot from 2022-04-01 14-19-30](https://user-images.githubusercontent.com/5009481/161262092-813285ac-2daa-429b-a333-3dca34533698.png)

**Comment by cnotv** [comment]
The same issue occurs also for Volume types:
- ConfigMap
- Bind-Mount
- NFS
- Secret

Not sure about CSI, as I was not able to create the driver required of the 3 types we have.

**Comment by cnotv** [comment]
> To reproduce:
> 
> * Go to create a new deployment
> * Go to the storage tab and select 'Persistent Volume Claim'
> * Type something into the mount point field
> * Edit the 'Volume Name'
> 
> The mount point and sub path and read-only fields are all reset.

It looks like the reported issue is also on creation, not just the reset on editing, as stated in the description.

**Comment by cnotv** [comment]
@nwmac is there a reason to have for Amazon an automatic and hidden name generation for the volume, while for all the other types is hidden?

![Screenshot from 2022-04-04 17-49-10](https://user-images.githubusercontent.com/5009481/161582662-50950ce3-63b1-4f56-ba38-83020abdf93d.png)

**Comment by cnotv** [comment]
It seems like there's an issue with the BE not recognizing the mount for some types.

This is the form for both before and after the submission, so no data is removed in the process:
![Screenshot from 2022-04-04 17-58-53](https://user-images.githubusercontent.com/5009481/161584313-91d98bb0-0263-4df6-833a-0face5c3b291.png)

This is the partial of the payload for the request:
```json
      "spec": {
        "affinity": {},
        "containers": [
          {
            "image": "storage",
            "imagePullPolicy": "Always",
            "name": "container-0",
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "volumeMounts": [
              {
                "mountPath": "amazon-mount-1",
                "name": "vol-ugcun"
              },
              {
                "mountPath": "amazon-mount-2",
                "name": "vol-ugcun"
              },
              {
                "name": "vol-an58v",
                "mountPath": "secret-mount-point"
              }
            ],
            "__active": true
          }
        ],
        "dnsPolicy": "ClusterFirst",
        "restartPolicy": "Always",
        "schedulerName": "default-scheduler",
        "terminationGracePeriodSeconds": 30,
        "volumes": [
          {
            "awsElasticBlockStore": {
              "volumeID": "amazon-id"
            },
            "name": "vol-ugcun"
          },
          {
            "_type": "secret",
            "secret": {},
            "name": "vol-an58v"
          }
        ],
        "imagePullSecrets": []
      }
```

Note: `_type` is added on creation.

**Comment by cnotv** [comment]
It seems like the error returned from BE is misleading: there's no issue with the name, simply it's missing a required field for the secret, which is the `secret`.
This is not flagged as required.

I will take the chance to flag all the required values.

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/6739a84ede27905dfcccbc9675c875d1752d438a.

**ENVIRONMENT DETAILS**
- Linode Ubuntu 20.04.4 - Client Machine
- Docker install - 20.10
- Rancher version
     - `v2.6.4` - Reproduced version
     - `v2.6-head`  https://github.com/rancher/rancher/commit/6739a84ede27905dfcccbc9675c875d1752d438a - Verified version

**REPRODUCTION STEPS**
1. Setup Rancher `v2.6.4` on client machine.
2. Navigate to Rancher UI > top-left dropdown menu > Explore Cluster > local > Workloads > Deployments.
3. Click `Create` in the top-right corner.
4. In the left-side, clicked Storage > Add Volume > Persistent Volume Claim (PVC).
5. Modify the Mount Point name and then modify the Volume Name with the below results:
![image](https://user-images.githubusercontent.com/52591819/164508782-47969804-b00c-4bc4-bca1-6530b67a5ab6.png)
![image](https://user-images.githubusercontent.com/52591819/164508796-fd26608c-d820-46c7-89ad-3a5d3a4e769f.png)
6. Click the Add Volume dropdown menu and repeat step 4 and received the same results.
7. Add a third PVC and repeat step 4; same results as above.
8. Delete all of the PVCs created. Create a new PVC and In the bottom-right corner of the screen, click `Edit as YAML` and do the following addition to have `mountPath: bogus`:
![image](https://user-images.githubusercontent.com/52591819/164509042-0dc236e1-6d62-4438-8d3e-70bbfdfddda6.png)
9. Repeat step 4 and received the same result.

**VERIFICATION STEPS**
1. Setup Rancher `v2.6-head` on client machine.
2. Navigate to Rancher UI > top-left dropdown menu > Explore Cluster > local > Workloads > Deployments.
3. Click `Create` in the top-right corner.
4. In the left-side, clicked Storage > Add Volume > Persistent Volume Claim (PVC).
5. Modify the Mount Point name and then modify the Volume Name with the below results:
![image](https://user-images.githubusercontent.com/52591819/164509324-3fa13653-1991-4c96-b689-4063c514e6e3.png)
![image](https://user-images.githubusercontent.com/52591819/164509353-43c73629-19a7-443c-ae1a-b33944b80fec.png)
6. Click the Add Volume dropdown menu and repeat step 4 and received the same results.
7. Add a third PVC and repeat step 4; same results as above.
8. Delete all of the PVCs created. Create a new PVC and In the bottom-right corner of the screen, click `Edit as YAML` and do the following addition to have `mountPath: bogus`: 
![image](https://user-images.githubusercontent.com/52591819/164509716-876a91ec-d16c-40ca-82a9-1eaca9c63a2f.png) 
9. Repeat step 4 and received the same result.
