### ISSUE TITLE
Designate k3s provisioning as "Tech Preview"

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#5318]
**Detailed Description**
For 2.6.4 release, we're focusing on GA-ing RKE2 provisioning, so k3s is not getting as much attention from both QA and engineering.
Due to this, we will likely want to retain "tech preview" status for k3s provisioning.

There is currently a single toggle that controls both RKE2 and k3s:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/85187633/157158390-14c411a8-91b2-4d89-9772-cc9864f4bafb.png">

So it's suggested to add rather prominent (red-ish color?) "Tech Preview" designation to k3s section in Kubernetes Version dropdown: 
<img width="738" alt="image" src="https://user-images.githubusercontent.com/85187633/157158698-fe1d2c13-4ed3-4782-bfcc-1ec3d5811d01.png">

Other suggestions to address this requirement are welcome. We could change RKE1-RKE2/k3s toggle to dropdown, but this will require deeper changes as we will need to start filtering RKE2/k3s versions in dropdown and toggle->dropdown changes user experience more than this less intrusive change (that will also be easier to remove without changing user experience much once k3s provisioning is GA too).

**Context**
k3s is unlikely to be designated GA for 2.6.4 release.

**Comment by nwmac** [comment]
@snasovich I think the best we can do in the timeframe is to add a tech preview badge in the drop down.

**Comment by sowmyav27** [comment]
In 2.6.4, we are having both K3s and RKE2 as Tech preview. We are targeting RKE2 GA in 2.6.5. So this PR has to be reverted for the current release

**Comment by sowmyav27** [comment]
**verified on 2.6-head commit id: `80465bd`**

- RKE2 shows Tech Preview  in cluster launch page.
- K3s has no tech Preview in k8s version dropdown during cluster create
