### ISSUE TITLE
OPA gatekeeper customize label

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#532]
I see that the customize button to enable OPA gatekeeper has the label "CustomizeCustomize", it needs to be corrected:

<img width="848" alt="Screen Shot 2020-04-20 at 1 56 06 PM" src="https://user-images.githubusercontent.com/1470602/79799292-13505000-830f-11ea-8d8f-9b18b04cc236.png">

**Comment by westlywright** [comment]
@prachidamle I think you may be on an old build or something because this was addressed in https://github.com/rancher/dashboard/pull/514

Looks good on current master too (4/21)

**Comment by deniseschannon** [comment]
Fixed in `master`
<img width="435" alt="Screen Shot 2020-04-23 at 10 47 29 AM" src="https://user-images.githubusercontent.com/11410997/80131990-e50d8300-854f-11ea-9685-51a4e1f052db.png">
