### ISSUE TITLE
Odd bulk action button visibility behaviour

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5324]
Two issues
- The bulk action buttons in the cluster management cluster list only show when a row is selected. They should show but be disabled when no row is selected.
- The bulk action buttons in the machine pool tab aren't initially shown. They appear after selecting a row and will remain when a row is unselected .

**Comment by markusewalker** [comment]
Verified on v2.6-head https://github.com/rancher/rancher/commit/6bb6e45fba97f58443e547e2f57d2807a424467f.

**REPRODUCED ENVIRONMENT DETAILS**
- Linode Ubuntu 20.04.4 VM
- Docker install
- Rancher version: `v2.6.4`
- RKE version: `v1.22.7-rancher1-2`
     - 3 Nodes - 3 control plane, 3 etcd, 3 worker

**VERIFIED ENVIRONMENT DETAILS**
- Rancher version: v2.6-head https://github.com/rancher/rancher/commit/6bb6e45fba97f58443e547e2f57d2807a424467f
- Install option: Helm Chart
- Kubernetes version: `v1.22.8`
- Cluster Type: Downstream RKE cluster - 3 control plane, 3 etcd, 3 worker

**REPRODUCTION STEPS**
1. Setup Rancher v2.6.4 on client machine.
2. Navigate to Rancher UI in a browser.
3. Create a downstream RKE v1.22.7-rancher1-2 in the Rancher UI.
4. Navigate to top-left dropdown menu > Cluster Management. Resize the browser to have items come in bulk and in the defaulting `Clusters` page, see the following:
![image](https://user-images.githubusercontent.com/52591819/164292986-fd99efe4-0feb-4743-8b01-1fcb0e4f5d5a.png)
5. After clicking on the select all button, I now see bulk options listed:
![image](https://user-images.githubusercontent.com/52591819/164293078-2582873f-9dd2-445d-969e-08d5e1cb0da0.png)
6. Click downstream RKE cluster and note the machine pools tab should like the following:
![image](https://user-images.githubusercontent.com/52591819/164293154-44216764-77b4-4a6f-9907-2fbd4a67627d.png)
7. Selecting all of the rows shows the following:
![image](https://user-images.githubusercontent.com/52591819/164293230-6a4e0b07-960c-4f51-aa2a-d9487e61dc4e.png)
8. Deselecting all of the rows, the options still show:
![image](https://user-images.githubusercontent.com/52591819/164293302-92ab3066-73df-4114-8762-94ebfc2dd6f0.png)

**VERIFICATION STEPS**
1. Setup Rancher v2.6-head on client machine.
2. Navigate to Rancher UI in a browser.
3. Navigate to top-left dropdown menu > Cluster Management. Resize the browser to have items come in bulk and in the defaulting `Clusters` page, see the following:
![image](https://user-images.githubusercontent.com/52591819/164293358-3ed51306-46ce-402a-854c-ba495443d4c1.png)
4. Click downstream cluster and note the resulting screen:
![image](https://user-images.githubusercontent.com/52591819/164293436-0207ad79-eb51-4d18-984c-85945069091e.png)
     - Selecting all rows enables the actions menu and disables the action menu as expected.
