### ISSUE TITLE
No chart Yaml

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#5325]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/1387263/157286409-f3c28127-123d-4aeb-b0b1-e31ea82f4e8e.png">

**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by nwmac** [comment]
noCharts: 'There are no charts available, have you added any repos?'

need to be added back

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f90426`**

This issue is seen fixed
<img width="1288" alt="Screen Shot 2022-03-13 at 10 22 36 PM" src="https://user-images.githubusercontent.com/26032343/158070215-e81a45c4-a901-411b-9966-31549c345dee.png">
