### ISSUE TITLE
Continuous Delivery Dashboard | Incorrect Bundles count 

### ISSUE THREAD

**Issue by sgapanovich** [rancher/dashboard#5326]
**Setup**
- Rancher version: v2.6-head 3f9109c

**Describe the bug**

CD Dashboard adds an extra bundle to a gitrepo deployed in `fleet-local` workspace(namespace) when a gitrepo added to the `fleet-default` workspace (namespace) 

**To Reproduce**

1. Deploy a downstream cluster (so the fleet-default namespace at least one cluster to deploy resources)
2. As an admin navigate to "Continuous Delivery"
3. In the namespace dropdown select 'fleet-local'
4. Git repos -> Add Repository
5. Data:
  Name: test
  Repository URL: https://github.com/sgapanovich/test.git
  Branch: main
6.  Click Create 
7. If you go to Continuous Delivery Dashboard you will see that test repo has 1/1 Bundles ready (it makes sense since we had only one bundle added in the repo from step 5)
8.  In the namespace dropdown select 'fleet-default'
9. Git repos -> Add Repository
10. Data:
  Name: test1
  Repository URL: https://github.com/sgapanovich/fleet-examples.git
  Branch: master
  Path: simple
11. Click Create
12. Navigate to Continuous Delivery Dashboard

![gif](https://user-images.githubusercontent.com/40282141/157317983-2be3419b-7ec0-4f9e-9b1b-2f896d075a80.gif)

**Result**
`test` repo in the 'fleet-local' has a bundle added resulting in 2/2 

**Expected Result**

every repo in the Dashboard should have count only for its own bundles (`test` should not have its bundle count increased unless it's designed and bundle is added in the repo itself)

**Comment by geethub97** [comment]
Per the screenshot taken below, there is still a bug in the bundles count. I waited a significant amount of time to check to see if the fleet-local bundles ready count would get updated but only the fleet-default namespace shows the correct value.  

![RancherUIScreenshot.png](https://zube.io/files/rancher/a207910260707b270a64d4c1b22a218d-rancheruiscreenshot.png)

**Comment by Shavindra** [comment]
@geethub97 can you tell me the steps you followed? Can I see any console errors? I am seeing things correctly still.

**Comment by Shavindra** [comment]
@bmdepesa can you share steps/video of it if you could? 

What I find strange is that bundles ready count is 0/0 even if cluster count is 1/1

<img width="806" alt="image" src="https://user-images.githubusercontent.com/1387263/160151964-941b822e-19e8-4e3f-a737-c74ae9bccf74.png">

**Comment by geethub97** [comment]
@Shavin Fonseka I just followed the steps listed above, and I re did it multiple times before taking the screenshots. Not sure why mine was showing 0/0 for local
