### ISSUE TITLE
Fleet enhancements.

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#5329]
1. Synchronisation log output for git jobs
2. Dashboard should show the cluster tab

3. Workspace > Cluster
4. Assign cluster > Dialog fix the padding.
 
5. Representative git repositories

6. rancher/dashboard#5407 - UX improvements for ResourceSummary counters in git repo details view

7. Bundle type icon
 
8. Resource view - after clicking on Fleet resource
9. Deployment does not have minimum availability. - Shows info in Deployments, in fleet this is yellow
10. Annotation - Can’t see if this is managed by fleet or not.
 
11. Backend error message handling
 * 		"message": "ErrApplied(1) [Bundle schf-single-cluster-helm: another operation (install/upgrade/rollback) is in progress]",
 * 		"message": "another operation (install/upgrade/rollback) is in progress",
12. Diagnostic tools:

**Comment by nwmac** [comment]
Closing as stale
