### ISSUE TITLE
Workload - List, Create, Detail pages

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#533]
Original workload screen designs - https://xd.adobe.com/view/84134770-bb08-4d0c-736d-1f0aa44b36fd-f222/screen/f7b23d64-843f-4e6d-92f2-b11ff3aa0c75/workload-detail

Current workload issues: https://github.com/rancher/dashboard/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fworkloads

**Comment by sowmyav27** [comment]
Tracking issues related to workload in separate tickets. Closing this.
