### ISSUE TITLE
Consent banners only partially shown

### ISSUE THREAD

**Issue by HoustonDad** [rancher/dashboard#5333]
**Setup**
- Rancher version: 2.6.4-rc4
- Browser type & version: Chrome v99

**Describe the bug**
When a banner is added, for example, a generic USGIS banner, the text does not paginate on the screen, instead rolls off with an ellipsis. USG consent banners cannot show partially, since you cant give partial consent.

**To Reproduce**
1. Install Rancher 2.6.4 latest RC
2. Add a banner with lots of text, that will cause it to overflow the screen.
3. Log out, hard refresh 

**Result**
Banner is shown, but only partially, ending with an '...'

**Expected Result**
USG Banners (and consent banners in general) should not be partially shown and broken. It should be shown fully

**Screenshots**
![Rancher 2022-03-09 09-07-09](https://user-images.githubusercontent.com/620445/157469426-080b8e86-e3c3-4785-93c3-fc511d76891b.png)

**Comment by nwmac** [comment]
We should allow the banners to take the height they need

**Comment by sowmyav27** [comment]
**On 2.6.4**
<img width="1282" alt="Screen Shot 2022-04-24 at 9 08 27 PM" src="https://user-images.githubusercontent.com/26032343/165019327-7125b229-a0cf-40a6-95f2-6e9658b16d90.png">

**On 2.6.5-rc2**
<img width="1680" alt="Screen Shot 2022-04-24 at 9 08 03 PM" src="https://user-images.githubusercontent.com/26032343/165019344-c44fccfb-a270-4be8-9578-80e1da99e590.png">
