### ISSUE TITLE
Provisioning new cluster with invalid name cause UI hang

### ISSUE THREAD

**Issue by joshmeranda** [rancher/dashboard#5334]
- Rancher version: v2.6.3
- Browser type & version: Firefoxv91.5.0esr

**Describe the bug**
When creating a new rke2 harvester cluster with a cluster name that includes a space, the UI indicates the cluster is being created but no progress is made. No pods are created on the target harvester deployment.

**To Reproduce**
1. Start provisioning a new cluster
2. Give the new cluster a name with a space (eg "harvester cluster")
3. Click "Create"

**Result**
UI makes no progress and console error log is created containing an error message from the k8s api

```
fail to create serviceAccount: ServiceAccount "harvester cluster" is invalid: metadata.name: Invalid value:   |
"harvester cluster": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-'   |
or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation  |
is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Expected Result**
A UI error indication of the invalid cluster name.

**Screenshots**
![create-cluster-ui](https://user-images.githubusercontent.com/43455015/157484425-0a165931-768d-4bb5-b09a-03bb3155ea57.png)

![Screenshot_20220309_112057](https://user-images.githubusercontent.com/43455015/157484331-58ac7095-d4c1-4bc4-8663-62a74255ee0a.png)

**Additional context**
Bug was encountered while provisioning a new harvester rke2 cluster.

**Comment by Shavindra** [comment]
I do not see this in rancher 2.6.4-head. Can you still reproduce this? @joshmeranda

**Comment by joshmeranda** [comment]
Finally got a chance to test this with 2.6.4-head, looks like it's fixed on my end too. Thanks!
