### ISSUE TITLE
Can not edit roles via yaml

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5347]
Internal Reference: SURE-3694

Only via edit yaml - not edit config:

When you try to edit a newly created Role and click 'Save' button, UI shows {"data": "404 page not found \n"} and you can not save the change.
This issue happens to Global Role, Cluster Role, and Project/Namespaces Role.

Steps:

- Go to CONFIGURATION > Users&Authentication > Roles
- Create a new Global Role, for example with 'get' for 'apps'
- Click the 3-dot icon of the newly created Global Role, and click 'Edit YAML'
- Add 'list' permission, and click 'Save'
- Confirm you see the error saying * {"data": "404 page not found \n"}*

**Comment by sowmyav27** [comment]
@Shavindra Can you pls link the PR for this issue?

**Comment by Shavindra** [comment]
@sowmyav27 I couldn't replicate this issue.

**Comment by sowmyav27** [comment]
@Shavindra please link the issue for `edit yaml button not showing up due to blocked-put` since we will revisit this when that issue is fixed.

**Comment by nwmac** [comment]
Issue is, we do not support 'edit as yaml' for Norman resources in the new UI.

We used to use Steve for this, which is why edit appeared, but this was switched over to Norman.

Until we add support for yaml editing of Norman resources, this won't work - note 'Edit as YAML' no longer appears, so you can't get the error in this issue.

**Comment by catherineluse** [comment]
I'm closing this issue because as Neil noted above, it sounds like this is not a supported use case at this time, and as I understand it, we are not going to add support for editing Norman resources due to the planned deprecation of Norman. After Norman is deprecated, this would switch back to Steve, but I think we can cross that bridge when we come to it.
