### ISSUE TITLE
Fleet: icons in badges on Fleet Dashboard view display incorrect color

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5349]
**Describe the bug**
The icons in the badges on Fleet Dashboard view display incorrect color (all have the same golden color)

**To Reproduce**
Go to any page of Fleet (ex: git repos list page). Hit refresh. Navigate to Fleet dashboard using the side menu

**Result**
<img width="1604" alt="Screenshot 2022-03-10 at 13 57 42" src="https://user-images.githubusercontent.com/97888974/157677571-0b9a500c-a0ae-473d-b349-e4e1b3d330c7.png">

**Expected Result**
Icons should have the appropriate color according to it's background

<img width="1604" alt="Screenshot 2022-03-10 at 14 02 04" src="https://user-images.githubusercontent.com/97888974/157677642-f6955e6a-988a-4c78-a249-2be6ef0595e0.png">

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

Fleet: icons in badges on Fleet Dashboard view are fixed
<img width="1449" alt="Screen Shot 2022-03-13 at 11 57 30 PM" src="https://user-images.githubusercontent.com/26032343/158073833-3a00e53b-7c4d-4cbf-bce2-0aa9258372a3.png">

<img width="1669" alt="Screen Shot 2022-03-13 at 11 58 31 PM" src="https://user-images.githubusercontent.com/26032343/158073846-34d68cf5-659e-4118-a611-8805b4ff6f18.png">
