### ISSUE TITLE
Fleet: Remove underline from icon in git repo details -> conditions tab

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5351]
**Describe the bug**
An incorrect underline is appearing, on hovee, on the icon alerting the user that there are problems on the conditions inside a git repo details

**To Reproduce**
navigate to a git repo details in fleet (must be in an error state) -> hover conditions tab

**Result**
<img width="1604" alt="Screenshot 2022-03-10 at 15 28 41" src="https://user-images.githubusercontent.com/97888974/157695304-69cb2d33-8659-42fe-876f-6bc563255922.png">

**Expected Result**
Hover the conditions tab and only see the underline on the label (text) part of it
<img width="1604" alt="Screenshot 2022-03-10 at 15 30 08" src="https://user-images.githubusercontent.com/97888974/157695553-17cdd09e-b029-4b1f-9bae-40a3ced592e1.png">

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

Underscore is not available in the icon in git repo details --> conditions tab
<img width="627" alt="Screen Shot 2022-03-13 at 11 52 12 PM" src="https://user-images.githubusercontent.com/26032343/158073640-c083c259-4a85-4303-94dd-48b7b843fc45.png">
