### ISSUE TITLE
Revert removal of Tech Preview designation for RKE2/k3s provisioning

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#5359]
Tech Preview designation needs to be added back to RKE2/k3s provisioning for 2.6.4.
Essentially, changes done per the following issues should be reverted:
https://github.com/rancher/dashboard/issues/4852
https://github.com/rancher/dashboard/issues/5318

**Comment by snasovich** [comment]
@nwmac @gaktive , @-mentioning you for visibility.

**Comment by snasovich** [comment]
Additionally, what's the difference between "Experimental" and "Tech Preview". "Experimental" is used only for Harvester in 2.6.3 as per https://github.com/rancher/dashboard/issues/4852#issuecomment-1060906282. I believe "Experimental" was used for Harvester regardless of RKE1/RKE2 option until 2.6.3, so maybe having it labeled as "Experimental" in 2.6.3 for RKE2 is a result of that. If that's the case, it may be better to mark all of RKE2 provisioning options as "Tech Preview" (including Harvester) for consistency.

**Comment by gaktive** [comment]
@catherineluse already asked about this, so UI will look into reversion.

As for the Experimental label for Harvester, we should be clear that the RKE2 side is listed as such whilst the rest of Harvester is GA (independent of RKE2, therefore supported) just to reduce confusion. @snasovich is that what you meant?

**Comment by snasovich** [comment]
@gaktive, Correct, Harvester itself is GA. And then RKE2 is "Tech Preview". But prior to https://github.com/rancher/dashboard/issues/4852 implemented, it looks like in 2.6.3 Harvester + RKE2 combination was marked as "Experimental" even though in 2.6.3 Harvester itself is GA and RKE2 is "Tech Preview" - so I think for consistency Harvester + RKE2 combination should be designated as "Tech Preview" and not "Experimental" (unless I'm missing some specific reason why it should be "Experimental").

**Comment by sowmyav27** [comment]
**On 2.6-head  commit id: `bab14a3`**

- Harvester is shown as `Experimental` 

**Expected:**
- Harvester be shown as `Tech Preview`

**Comment by catherineluse** [comment]
I think the `Experimental` label should just be removed because Harvester went GA.

**Comment by nwmac** [comment]
I think its still Experimental on RKE2 - at least that's what it was signifying before - if he select RKE1 we don't show the badge.

**Comment by sowmyav27** [comment]
If its not experimental on RKE1 for Harvester, it should show the same as other node drivers - `Tech Preview`

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `80465bd`**

Harvester is seen as Tech Preview
<img width="1677" alt="Screen Shot 2022-03-16 at 12 37 31 PM" src="https://user-images.githubusercontent.com/26032343/158535315-0c484f42-1859-4429-93ae-85181feebab7.png">
