### ISSUE TITLE
UI cluster creation page embedded into Dashboard, how to control the translation in UI 

### ISSUE THREAD

**Issue by harryhxs** [rancher/dashboard#5361]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment]
Translations for embedded pages can be found over at https://github.com/rancher/ui. Translations for non-embedded pages can be found in this repo. We're happy to accept contributions to both if you'd like to change or add text

**Comment by harryhxs** [comment]
I mean that selected local is zh-hans, but the embedded ui page was still en-us. It will not change always.

**Comment by richard-cox** [comment]
Can you open a new issue and ensure to fill out the description, including version and steps to reproduce
