### ISSUE TITLE
Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://159.69.177.144:6443/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded

### ISSUE THREAD

**Issue by ali-alhajj98** [rancher/dashboard#5369]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

Hello am having this issue today and my cluster is app since 3 years ago nothing happened as this before. P.S: my whole cluster is still up and everything is fine but this error is bugging me.

Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://159.69.177.144:6443/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded

rancher version 2.6.3, am seeing the error on dashboard/home path 
**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment]
@ali-alhajj98 Can you fill out the issue template please, specifically the version? Where do you see that line?

**Comment by ali-alhajj98** [comment]
@richard-cox sorry for that, done.
