### ISSUE TITLE
[cluster roles] Error 'inaccessibleByURL' when saving cluster roles

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5371]
**Setup**
- Rancher version: `v2.6.4-rc8`
- Browser type & version: `Chrome Version 98.0.4758.80 (Official Build) (x86_64)`

**Describe the bug**
When creating cluster roles, there are 2 errors in the console:
`CreateEditView mixin failed to save:  
{baseType: 'error', code: 'InternalError', message: 'admission webhook "rancherauth.cattle.io" denied t…: roletemplates.management.cattle.io "" not found', status: 500, type: 'error', …}
baseType: "error"
code: "InternalError"
message: "admission webhook \"rancherauth.cattle.io\" denied the request: Internal error occurred: roletemplates.management.cattle.io \"\" not found"
status: 500
type: "error"
_headers: {content-encoding: 'gzip', content-length: '180', content-type: 'application/json', date: 'Fri, 11 Mar 2022 14:47:23 GMT', expires: 'Wed 24 Feb 1982 18:42:00 GMT', …}
_req: XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, onreadystatechange: ƒ, …}
_status: 500
_statusText: ""
_url: "https://ronrc8.qa.rancher.space/v3/roletemplates"
[[Prototype]]: Object`

`https://ronrc8.qa.rancher.space/v3/roletemplates 500`

**To Reproduce**
1. create downstream cluster
2. hamburger > users & authentication > roles > clusters
3. complete form and save

**Result**
Errors thrown. Role appears to save

**Expected Result**
No errors

**Comment by nwmac** [comment]
Can you validate if this is still an issue.

**Comment by nwmac** [comment]
Thanks @ronhorton

**Comment by nwmac** [comment]
Reported as fixed in 2.6.4 - QA to validate

**Comment by ronhorton** [comment]
**Pass** verified in `2.6-head Commit ID 228a585`

1. create downstream cluster
2. hamburger > users & authentication > roles > clusters
3. complete form and save

`new role is created with no errors`
<img width="1406" alt="Screen Shot 2022-04-20 at 11 43 43 AM" src="https://user-images.githubusercontent.com/89212856/164270829-70424256-4593-4068-bd39-f7aa1e471c79.png">
