### ISSUE TITLE
Harvester cluster create form error breaks UI

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#5373]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**
Harvester R

**To Reproduce**
1. Cluster management > Create Cluster 
2. Ensure RKE2 switch is turned on
3. Click on Harvester
4. Try to error the form in Machine pool (e.g. if there is no harvester instance/Images set up you can click on images dropdown)

**Result**
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/1387263/157904689-ce265195-74f5-4de7-9107-91c975466241.png">

<img width="1782" alt="image" src="https://user-images.githubusercontent.com/1387263/157904163-71d840bb-9e8d-47f4-8b0e-77a9ac20115b.png">

**Comment by richard-cox** [comment]
@Shavindra Was that another original issue for this?

**Comment by slickwarren** [comment]
@Shavindra could you please post more info about what versions you were using for harvester/rancher, and how you got it to this state?

**Comment by slickwarren** [comment]
I no longer see this issue on 2.6-head (b7c9b89)
test steps:
* import a harvester cluster in virtualization management 
  * harvester should be fresh, with no images added yet. 
* go to create an rke2 cluster using harvester node driver
  * check all drop downs using the node driver -- no errors show in console -- pass
* go to create an rke1 cluster using harvester node driver
  * check all drop downs using the node driver -- no errors show in console -- pass
