### ISSUE TITLE
Option to add html code to the consent text block

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5377]
Internal reference: SURE-4231

Request description:
The modal consent banner is great, however, our normal banner has line breaks which we cannot add to this option. We would like a way to either add html code (i.e `<br />`), normal breaks (`\n`) or even a text block where we can input text and it will display as inputted.

Actual behavior:
Not able to add html

Expected behavior:
To be able to add html brackets 

No workaround available at present.

**Comment by nwmac** [comment]
@aalves08 The low-bar is to add support for \n - this avoids any issue with malicious html tags which we'd hit if we were allowing arbitrary HTML.

We should add text under the Text box for configuring a banner saying something like 'Use \n for new lines'

FixedBanner is the component that renders the text - so I think we can just split the string on newlines and update the template to render each line in a div, rather than just rendering `banner.text`

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.6.5-rc2                                |
| Rancher commit link       | not applicable                           |
| Installation option       | helm high availability                   |
| RKE binary version used   | v1.3.8                                   |
| If Helm Chart k8s cluster | v1.22.7                                  |
| Cert Details              | let's encrypt                            |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | not applicable                           |
| Downstream K8s version    | not applicable                           |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$OMITTED \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5-rc2
```

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> `Global Settings` -> `Banners`
3. Navigate down the screen to `Login Screen Banner`
   - Mark the checkbox `Show Consent Banner on Login Screen`
   - Mark the checkbox `Show Login Consent as a modal dialog`
   - In the text box fill out the following

```txt
Test line 001\n
Test line 002\n
Test line 003\n
Test line 004\n
Test line 005\n
Test line 006\n
Test line 007\n
Test line 008\n
Test line 009\n
Test line 010\n
Test line 011\n
Test line 012\n
Test line 013\n
Test line 014\n
Test line 015\n
Test line 016\n
Test line 017\n
Test line 018\n
Test line 019\n
Test line 020\n
Test line 021\n
Test line 022\n
Test line 023\n
Test line 024\n
Test line 025\n
Test line 026\n
Test line 027\n
Test line 028\n
Test line 029\n
Test line 030\n
Test line 031\n
Test line 032\n
Test line 033\n
Test line 034\n
Test line 035\n
Test line 036\n
Test line 037\n
Test line 038\n
Test line 039\n
Test line 040\n
Test line 041\n
Test line 042\n
Test line 043\n
Test line 044\n
Test line 045\n
Test line 046\n
Test line 047\n
Test line 048\n
Test line 049\n
Test line 050\n
Test line 051\n
Test line 052\n
Test line 053\n
Test line 054\n
Test line 055\n
Test line 056\n
Test line 057\n
Test line 058\n
Test line 059\n
Test line 060\n
Test line 061\n
Test line 062\n
Test line 063\n
Test line 064\n
Test line 065\n
Test line 066\n
Test line 067\n
Test line 068\n
Test line 069\n
Test line 070\n
Test line 071\n
Test line 072\n
Test line 073\n
Test line 074\n
Test line 075\n
Test line 076\n
Test line 077\n
Test line 078\n
Test line 079\n
Test line 080\n
Test line 081\n
Test line 082\n
Test line 083\n
Test line 084\n
Test line 085\n
Test line 086\n
Test line 087\n
Test line 088\n
Test line 089\n
Test line 090\n
Test line 091\n
Test line 092\n
Test line 093\n
Test line 094\n
Test line 095\n
Test line 096\n
Test line 097\n
Test line 098\n
Test line 099\n
Test line 100\n
```

4. Click `Apply`
5. Log out and make sure the dialog appears and the formatting matches what is expected

## Additional Info

## RESULTS

#### :white_check_mark: Expected
New line spacing working as expected

#### :white_check_mark:Actual
New line spacing working as expected
