### ISSUE TITLE
Remove "Rotate Encryption Keys" functionality from UI (if already introduced)

### ISSUE THREAD

**Issue by Sahota1225** [rancher/dashboard#5379]
If "Rotate Encryption Keys" action is introduced in the UI as part of https://github.com/rancher/dashboard/issues/4540, we want it removed for 2.6.4 release.
If not, please close this issue as irrelevant.

**Comment by catherineluse** [comment]
@Sahota1225 I started working on the feature, but it wasn't merged into master. Should the original ticket for rotating encryption keys be moved into the v2.6.5 milestone? https://github.com/rancher/dashboard/issues/4485

**Comment by snasovich** [comment]
@catherineluse , I guess you meant https://github.com/rancher/dashboard/issues/4540, not https://github.com/rancher/dashboard/issues/4485 (they do sound similar)?

**Comment by catherineluse** [comment]
Yes, I meant https://github.com/rancher/dashboard/issues/4540
