### ISSUE TITLE
Additional actions on a snapshot on RKE2 cluster to be removed.

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5383]
**On 2.6-head commit id: `f904267`**

- Can we remove these options also on the snapshot on RKE2 cluster to be in parity with RKE1 clusters?
```
- - Clone
- - Edit Yaml
- - Download Yaml
```
<img width="1402" alt="Screen Shot 2022-03-13 at 10 36 44 PM" src="https://user-images.githubusercontent.com/26032343/158070812-5ad81330-4deb-4dae-8d11-c47ceb266ebd.png">

Extension of this issue - https://github.com/rancher/dashboard/issues/5262

**Comment by Auston-Ivison-Suse** [comment]
**Validation Setup**
- rancher version: v2.6.4-rc9
- Browser:Chrome Version 99.0.4844.74

**Validation Steps**
1. provision an rke2 cluster
2. take a snapshot
3. From cluster management navigate to the cluster and select "snapshots"
4. Click the kebab menu. 

**Result**

We shouldn't see anything else other than restore as an option. 

**Note**

This isn't exact parity with rke1 clusters, as we don't support the delete option in rke2 provisioned clusters but we do with rke1 clusters. As sited [here](https://github.com/rancher/dashboard/issues/5262)

**Screenshot of result**
![SnapshotRestoreMenu.png](https://zube.io/files/rancher/63631a53acddb419f26003889c6301f1-snapshotrestoremenu.png)
