### ISSUE TITLE
Monitoring - Failed to load resource status 500 - changing namespace in dropdown

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5389]
**Setup**
- Rancher version: `2.6.4-rc8`
- Browser type & version: `Chrome 98.0.4758.80 (Official Build) (x86_64)`

**Describe the bug**
On the prometheus rules page under monitoring, when I switch from `only user namespaces` to `all namespaces`, a 500 error appears in the console - `Failed to load resource: the server responded with a status of 500 ()`

**To Reproduce**
1. create downstream cluster - ec2 3 w, 1 cp, 1 etcd
2. install monitoring v2 100.1.1+up19.0.3
3. install alerting drivers 100.0.2
4. created receiver and route
5. click monitoring > advanced > prometheus rule
6. on page, change namespaces in dropdown from `only user` to `all`

**Result**
`/v1/userpreferences/user-bnzsb:1          Failed to load resource: the server responded with a status of 500 ()`
**Expected Result**
no error in console
<img width="1621" alt="Screen Shot 2022-03-14 at 10 45 42 AM" src="https://user-images.githubusercontent.com/89212856/158196545-d04df1e5-c6c2-4084-ad26-e039e307cb4a.png">

**Comment by catherineluse** [comment]
@ronhorton What permissions does the logged in user have?

**Comment by ronhorton** [comment]
@catherineluse this was an admin user

**Comment by nwmac** [comment]
This is actually an issue saving the user preference when the dropdown is changed - we need to wire the conflict resolution logic into the preference save.

**Comment by nwmac** [comment]
Closing as stale
