### ISSUE TITLE
Fleet: Workspace filter "moves" workspace group to the top on Fleet Dashboard

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5406]
**Describe the bug**
Workspace filter "moves" the selected workspace group to the top on Fleet Dashboard

**To Reproduce**
Go to Fleet Dashboard view -> apply a workspace filter -> check that the workspace group on Fleet dashboard view has moved to the top

**Result**
<img width="1666" alt="Screenshot 2022-03-15 at 17 33 02" src="https://user-images.githubusercontent.com/97888974/158437475-16232696-8e3f-4269-b069-2b5e0d13623e.png">

**Expected Result**
Applying a workspace filter on the header should not create changes to the Fleet dashboard view

**Comment by aalves08** [comment]
@deniseschannon based on the feedback you provided on the presentation (Rancher Demos) for the work done by the UI team (particularly in Fleet) I created this issue. Would just like your confirmation that I captured your feedback correctly. Thanks

CC @nwmac

**Comment by deniseschannon** [comment]
I would expect the workspace filter to filter out all the other non-matching workspaces instead of just moving it to the top.

**Comment by aalves08** [comment]
Thanks for clarifying that @deniseschannon . Since this is a view which is intended to give a broader perspective on what's going on with all the repos in Fleet at any given moment, imo, I think that instead of filtering out content that could be important for the user we should just remove the interaction for now and try to revisit this topic + workspace filters from a UX standpoint for 2.6.5.

**Comment by izaac** [comment]
Filtering feature interaction was removed for 2.6.4 and will be revisited on 2.6.5

Validated this is no longer possible on `v2.6.4-rc10`
