### ISSUE TITLE
Fleet: UX improvements for ResourceSummary counters in git repo details view

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5407]
**Description**
the ResourcesSummary counters in git repo details view should be improved in the following manner:
- Highlight clickable area with blue color on mouse hover and change cursor to pointer

<img width="1623" alt="Screenshot 2022-03-15 at 17 39 49" src="https://user-images.githubusercontent.com/97888974/158439175-48a5d072-ac68-4ccf-9dd1-99ab3a7a431a.png">

**Comment by aalves08** [comment]
@nwmac @kwwii , @bisht-richa has pointed out that her perception of the toggle indicator for the `bundles ready` feels more of a dropdown (connected with actionable items ex: links) rather than an informative section.

If you both agree on this take, shall we move on with replacing the `arrow` with an `info` icon for 2.6.5? What's your take?

Thanks in advance

**Comment by Shavindra** [comment]
When we did the demo @kwwii raised similar thing as well. It would be turned into a filter.

https://github.com/rancher/dashboard/issues/5329 - Point 6

**Comment by kwwii** [comment]
Would it make sense to simply make them dropdown buttons and, on selecting an item, switch the tab below accordingly and set that state as the filter for the table?

**Comment by kwwii** [comment]
I think we should change the arrow to an icon which on mouseOver turns blue and has a hand cursor, much like the hamburger menu at top right

**Comment by aalves08** [comment]
Changed title and description of the issue to fit a bigger scope of changes on this particular component for 2.6.5 according to @Shavindra .

CC @kwwii

**Comment by aalves08** [comment]
Update: scoped simplified after sync with Ken

**Comment by MSpencer87** [comment]
_Verified on 2.6.5-rc6_

**Steps to reproduce:**
1. Bring up HA Rancher 2.6.4
2. Open Main Menu -> Continuous Delivery
3. Add Git Repo, View added Repo
4. Mouse over Bundles and Resources (Text Cursor is seen with blue border box on clickable area)
5. Upgrade Rancher to 2.6.5-rc6
6. Mouse over Bundles and Resources (Finger Pointer is seen with Blue Highlight on text of clickable area)
