### ISSUE TITLE
node details fail if there is an image without a name

### ISSUE THREAD

**Issue by xhejtman** [rancher/dashboard#5408]
**Setup**
- Rancher version: 2.6.3-patch1
- Browser type & version: chrome beta 100.0.4896.20

**Describe the bug**

if there is image on a node without name such as:
```
# /var/lib/rancher/rke2/bin/crictl img
IMAGE                                                                                       TAG                              IMAGE ID            SIZE
<none>                                                                                      <none>                           2db27489be609       1.69GB
```

node detail cannot be shown and it expodes in javascript:
```
TypeError: Cannot read properties of null (reading '1')
    at node.vue:153:1
    at Array.map (<anonymous>)
    at f.imageTableRows (node.vue:151:21)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.imageTableRows (vue.runtime.esm.js:4836:17)
    at f.r (node.vue?eae7:1:2725)
    at f.t._render (vue.runtime.esm.js:3548:22)
    at f.r (vue.runtime.esm.js:4066:21)
    at _n.get (vue.runtime.esm.js:4479:25)
```

**To Reproduce**

delete an image but keep some its layers.

**Result**
node detail cannot be shown in Cluster -> Nodes -> click on such node

**Expected Result**

skip unnamed images

**Comment by nwmac** [comment]
@aalves08 Might be hard to reproduce - you could simulate this in code and fix and verfify

**Comment by xhejtman** [comment]
I think it is enough to use image that has few layers and delete the named layer (i.e., the last one). Then check with crictl, that there is an image without name.

**Comment by aalves08** [comment]
Was able to reproduce the exact same error programatically and we just need to add a fallback in case the name is undefined. PR here:
https://github.com/rancher/dashboard/pull/5565
