### ISSUE TITLE
Dashboard does not show secrets if ssh secret without ssh-publickey exists

### ISSUE THREAD

**Issue by xhejtman** [rancher/dashboard#5413]
**Setup**
- Rancher version: 2.6.3-patch1
- Browser type & version: chrome 100.0.4896.20

**Describe the bug**

If a namespace contains a secret that has ssh-auth type and the secret does not contain ssh-publickey entry, javascript fails not showing anything.

This is clear from the code `secret.js`:
```
get sshUser() {
    if ( this._type !== TYPES.SSH ) {
      return null;
    }

    const pub = base64Decode(this.data['ssh-publickey']);

    if ( !pub ) {
      return null;
    }
```

It does not check if `this.data['ssh-publickey']` is empty and `base64Decode(string)` blindly dereferences `string.replace`.

According to Kubernetes docs, ssh-auth secret should contain `ssh-privatekey`. 

**To Reproduce**

create kubernetes.io/ssh-auth without ssh-publickey data.

**Result**
no secret is shown in rancher dashboard.

**Expected Result**

show secrets as ususal.

**Comment by nwmac** [comment]
This was previously fixed in 2.6.5 and validated - there was a different issue for tracking this bug. Closing
