### ISSUE TITLE
Namespace filter component appears above 404 page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5415]
**Describe the bug**
New namespace filter appears above 404 page

**To Reproduce**
Visit `<rancher url>/asdasdsad`

**Result**
![image](https://user-images.githubusercontent.com/18697775/158660017-eb72e3a2-5a88-456e-ab28-a672420f8f2e.png)

**Additional context**
This is caused by the `absolute`ly positioned `ns-glass` element. This isn't normally an issue as nothing overlaps the component. I've noticed it in Epinio land where there's no cluster actions, the namespace filter is much more to the right and a growl is shown (underneath the namespace component). Would guess the harvester standalone ui also has this same issue

**Comment by richard-cox** [comment]
I've confirmed this will be more of an issue with harvester. In their case there's no cluster actions so the filter appears to the right and thus fights with the growl notification (which they make more use of)

![image](https://user-images.githubusercontent.com/18697775/158783281-9e588dfd-836a-47f1-9cce-5f3b59b84393.png)

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                          |
| ------------------------- | --------------------------------------- |
| Rancher version           | 2.6.4-rc10                              |
| Installation option       | Docker                                  |
| If Helm Chart k8s cluster | not applicable                          |
| Docker version            | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version              | v2.16.8-rancher1                        |
| Downstream cluster type   | not applicable                          |
| Downstream K8s version    | not applicable                          |
| Logged in user role       | Administrator                           |
| Browser type              | Google Chrome                           |
| Browser version           | 99.0.4844.74 (Official Build) (x86_64)  |

## Reproduction steps

1. Starting from the **default** Rancher homepage at `/dashboard/home`
2. Change the ending of the URL to -> `/dashboard/abc`

## Additional Info

## RESULTS

#### :white_check_mark: Expected
For the 404 page to not have UI elements such as a namespace filter

#### :x: Actual
The 404 page has UI elements that don't make sense, plus are not accessible i.e. white text on white background. With a namespace filter.

<hr>

## Validation Environment

| Component                 | Version / Type                                                                                |
| ------------------------- | --------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-024e6fa23af3678aafa85d4085c02143127bd3a1-head                                            |
| Commit ID link            | [024e6fa](https://github.com/rancher/rancher/commit/024e6fa23af3678aafa85d4085c02143127bd3a1) |
| Installation option       | Docker                                                                                        |
| If Helm Chart k8s cluster | not applicable                                                                                |
| Docker version            | 20.10.7, build 20.10.7-0ubuntu5~20.04.2                                                       |
| Helm version              | v2.16.8-rancher1                                                                              |
| Downstream cluster type   | not applicable                                                                                |
| Downstream K8s version    | not applicable                                                                                |
| Logged in user role       | Administrator                                                                                 |
| Browser type              | Google Chrome                                                                                 |
| Browser version           | 99.0.4844.74 (Official Build) (x86_64)                                                        |

## Validation steps

1. Starting from the **default** Rancher homepage at `/dashboard/home`
2. Change the ending of the URL to -> `/dashboard/abc`

## Additional Info

## RESULTS

#### :white_check_mark: Expected
For the 404 page to not have UI elements such as a namespace filter

#### :white_check_mark:Actual
The 404 page does not have UI elements such as a namespace filter
