### ISSUE TITLE
View "Form" Page for generic resources (not custom Rancher "form")

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#542]
Field | Component |Value in k8s yaml
---|---|---
`<ResourceName>`| MastHead | `metadata.name`
Namespace | MastHead | `metadata .namespace` (does this exist for all k8s resources?)
Created | DetailTop | `metadata.creationTimestamp`
Deleted |  DetailTop | `metadata.deletionTimestamp`
Conditions | Tab  (same component as used in nodes for displaying conditions, in current mock it's called "status") | `status.conditions`
Finalizers | Tab  | `metadata.finalizers`
Owners  | Tab  | `metadata.ownerReferences`
Labels | Tab using KeyValue component | `metadata.labels`
Annotations | Tab using KeyValue component| `metadata.annotations`

**Finalizers Tab Content** 
List of strings - display using as a table with no header?

Label | k8s yaml 
---|---
FInalizers | `metadata.finalizers`

**Owners Content** 
Table with these columns

Header | k8s yaml 
---|---
API Version | `metadata.ownerReferences.apiVersion` 
Kind | `metadata.ownerReferences.kind`
Name | `metadata.ownerReferences.name`

For the name, you should be able to link to the detail page of the resource. Some will be namespaced and some will be cluster scoped. 

Note: The masthead changes in the mocks are from this issue: https://github.com/rancher/dashboard/issues/538

**Comment by lvuch** [comment]
![detail](https://user-images.githubusercontent.com/3013118/80038371-5c88d700-84aa-11ea-9a59-878c5fe3bb6f.png)

**Comment by deniseschannon** [comment]
@lvuch DetailTop should only have "Created" and "Deletion Date". The other content is from Node, which doesn't make sense here.

**Comment by lvuch** [comment]
![detail-form](https://user-images.githubusercontent.com/3013118/80041787-294a4600-84b2-11ea-8c72-823a2da59515.png)

**Comment by deniseschannon** [comment]
Spoke with @ibuildthecloud and @lvuch offline earlier in the week but seems like no one added the updated mock in here.

For generic resource detail, we should only have 1 view that combines some of the content and yaml into 1 page. 

<img width="878" alt="Screen Shot 2020-05-06 at 2 13 19 PM" src="https://user-images.githubusercontent.com/11410997/81459018-843a9900-9152-11ea-8d2e-755208ba8287.png">

**Comment by vincent99** [comment]
This is showing things (like Annotations) as simultaneously both YAML and editable form controls.  You can't (practically) have a field editable in both the YAML and form at the same time.  Besides being probably confusing, they'd have to sync in both directions on every change, (including on YAML documents that currently contain errors and are unparseable).

Finalizers and Owners are uncommon on most resource types; for many types all 5 of these tabs are going to be empty "You have no X" messages that I'm going to have to click through to learn nothing.  They should be not shown, or grayed out, or say "Finalizers (0)" or something.

If these tabs are going to exist they should be on regular resources that have custom details too, there's nothing generic-resource-specific about them.

**Comment by ibuildthecloud** [comment]
The edit screen should just be yaml only.  A form doesn't make sense there.

Can finalizer and owners be combined into a some type of miscellaneous tab?  They are definitely less common.  Conditions, labels, and annotations are all common enough.  Maybe tabs is a bad structure for this?  I don't have much complaint with the current 5 tabs, but finalizers is that will really be empty most all of the time.

**Comment by deniseschannon** [comment]
This issue is only for viewing the detail page of a generic resource. There would still only be only 1 way to create/edit, which would be via YAML. 

The idea of changing how we want to have tab headers change based on if there is any content in them will be considered as a separate design request, which I created a separate issue. https://github.com/rancher/dashboard/issues/635

- [ ] If there are no conditions, let's hide the conditions tab. `status.conditions`
- [ ] Drop finalizers tab as they can be seen in the yaml.
- [ ] Move owners from tab into detailTop as the first item. Only show owners if there are owners (there could be more than 1), and make the value the name of the resource with a link to the detail page of the owner. 


@mantis-toboggan-md Can we determine a link to the owner based on the ownerReferences content? 

YAML looks like: 
```
metadata:
  ownerReferences:
     - apiVersion:
        blockOwnerDeletion:
        controller:
        kind:
        name:
        uid:
```

**Comment by mantis-toboggan-md** [comment]
Yeah we can do that. It's part of the PR (now a WIP) I made previously: https://github.com/rancher/dashboard/pull/595

**Comment by vincent99** [comment]
> This issue is only for viewing the detail page of a generic resource. There would still only be only 1 way to create/edit, which would be via YAML.

You're very literally showing an edit screen with inputs, add and remove buttons on it.

----- 

I'm sorry but I still think this is worse than doing nothing/showing only the YAML for view.

  - It's inconsistent with itself.  You create X as YAML, you edit X as YAML, you view as.. random subset of metadata/status fields displayed as tabs?
  - It's inconsistent with other detail pages.
    - On every other page the tabs are the last component, with non-tabbed detail above.
    - On every other page the Overview/YAML is a toggle, on this one they're displayed both together.
 - It's making no attempt to pull out or make prominent the definition of the resource itself, which is the primary thing that should displayed on detail pages (the `spec`).
  - Every bit of information in the tabs is redundant because it's also displayed in the YAML on the same screen.
    - They're also not going to match the displayed YAML, since the label/annotation viewers filter out some of the keys.

**Comment by deniseschannon** [comment]
We have other higher priority issues, so we can table the idea of this view page for generic resources at a later time. @mantis-toboggan-md I've put it in the backlog for now.

**Comment by ibuildthecloud** [comment]
I still very much want this page. @deniseschannon I'd rather not put it in the backlog.

**Comment by ibuildthecloud** [comment]
Can we just add the yaml section and then just iterate on it?  I'm not sure it's bad enough to completely drop at this.

**Comment by lvuch** [comment]
Updated for when we come back to this:
![image](https://user-images.githubusercontent.com/3013118/81728558-8301b880-943f-11ea-923e-e0728873c728.png)

**Comment by deniseschannon** [comment]
Current issues with YAML based on feedback from @vincent99 

- [ ] If you click on a resource from the list to go to detail you get the YAML editor, already in editing mode, with a cancel button and no save -> This should be resolved with this updated detail page for generic resources
- [ ] The YAML has important stuff stripped out of it because cleanForNew() is getting called on it somewhere
- [ ] If you then go to Edit from the action menu, you get the same stripped YAML and can't save it because you need resourceVersion to edit things but it's gone

**Comment by deniseschannon** [comment]
- [ ] Remove the border on YAML editor. Have it match the styling of the YAML editor of the view YAML pages
- [ ] Remove the option to toggle between YAML and Overview since the YAML is in the overview page
- [ ] Last Update in the conditions table isn't correct. See how the YAML is different than the table

<img width="586" alt="Screen Shot 2020-05-26 at 11 01 19 PM" src="https://user-images.githubusercontent.com/11410997/82983383-d4b05400-9fa4-11ea-9e88-1aea2e366339.png">

- [ ] @lvuch we need to review how to handle the long yamls within a page so you don't have double scrolling

**Comment by lvuch** [comment]
1. We can put tabs at the top and have yaml full height so only page scrolls. 
2. We can truncate the yaml and have a click to expand.
3. We truncate the yaml and it scolls and so does the page (we can have the tabs and yaml in either order)

**Comment by deniseschannon** [comment]
@mantis-toboggan-md let's go with option 1. Can you let @lvuch if you need a mock for it?

Also, there is no space between the yaml editor and tabs:

<img width="405" alt="Screen Shot 2020-06-05 at 10 30 03 PM" src="https://user-images.githubusercontent.com/11410997/83936867-80635c00-a77c-11ea-933c-ac9ed3011edf.png">

**Comment by deniseschannon** [comment]
Closing as we redesigned generic detail. New issue https://github.com/rancher/dashboard/issues/817
