### ISSUE TITLE
If scrollable dropdown goes off the bottom of page it does not resize to fit

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5421]
Internal reference: SURE-3350
Reported in 2.6.0

Issue description:
When performing an action like creating a role, if it's at the bottom of the page, there is no way to see the last options without resizing/rezooming

Business impact:
N/A

Troubleshooting steps:
<text>

Repro steps:

Open a window where there is a dropdown by the bottom edge (you can resize the window using Roles to reproduce) and open a dropdown. Scroll all the way down.

Workaround:
Zoom out or resize window.  This is problematic for the many users in places where it's hard to get anything more than a low-resolution laptop.

Example:
![image-2021-09-13-20-11-19-239.png](https://zube.io/files/rancher/04e4cbfe76e7d3489e552a75a5dfd7f4-image-2021-09-13-20-11-19-239.png)

Also visible under Roles, Create from Role Template and the Inherit From dropdown when not using the Project Creator Default

**Comment by nwmac** [comment]
Fixed in 2.6.5 - note user will have to open and close dropdown if they resize the window while it is open - but it should then appear above the control so that the options are all visible.

**Comment by sowmyav27** [comment]
**On 2.6.4 reproduced the issue**
<img width="1056" alt="Screen Shot 2022-04-24 at 9 03 00 PM" src="https://user-images.githubusercontent.com/26032343/165018976-2e8ebe2b-4ae8-423d-af8b-daa615acd986.png">

**On 2.6.5-rc2**
<img width="1075" alt="Screen Shot 2022-04-24 at 9 03 08 PM" src="https://user-images.githubusercontent.com/26032343/165018989-f0f17ba9-2b16-4dd1-98c6-4574bedcdcc5.png">
