### ISSUE TITLE
[vsphere rke2] unable to add node pool to rke2 cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5423]
**Setup**
- Rancher version: v2.6-head (5bb08b3)
- Browser type & version: chrome

**Describe the bug**
user is unable to provision a vsphere rke2 cluster, as the UI won't let you add a node pool 

**To Reproduce**
try to provision an rke2 vsphere cluster using the node driver

**Result**
user is unable to provision a vsphere rke2 cluster, as the UI won't let you add a node pool 
* there is no evidence of bad behavior in the browser network or console

**Screenshots**
<img width="936" alt="Screen Shot 2022-03-16 at 10 32 22 PM" src="https://user-images.githubusercontent.com/16691014/158744211-8aaa3089-5753-48fa-980b-edc3b44d7729.png">

**Comment by codyrancher** [comment]
@slickwarren 

I'm on the latest version and this appears to be working fine
![image](https://user-images.githubusercontent.com/55104481/159016272-df47fdfb-36c8-4b97-b10c-9af07d73dedb.png)
![image](https://user-images.githubusercontent.com/55104481/159016341-7a9c4e49-a084-4b5b-84f8-5a66d3abf7c8.png)


If you're still able to reproduce this can you share you cluster with me so I can poke around?

**Comment by rosskirkpat** [comment]
@codyrancher I have a setup with this issue when trying to create an EKS cluster. Sending a message on slack regarding access

**Comment by rosskirkpat** [comment]
```console
Component 	Version
Rancher 	v2.6-024e6fa23af3678aafa85d4085c02143127bd3a1-head
Helm 	v2.16.8-rancher1
Machine 	v0.15.0-rancher81
```

This is the [latest](https://github.com/rancher/rancher/commit/024e6fa23af3678aafa85d4085c02143127bd3a1) 2.6-head from 2 days go
