### ISSUE TITLE
deleted cluster still shown in rancher

### ISSUE THREAD

**Issue by sdahlbac** [rancher/dashboard#5425]
**Setup**
- Rancher version: 2.6.3
- Browser type & version:

**Describe the bug**

Deleted clusted still visible in menu and home page

![image](https://user-images.githubusercontent.com/659363/158770207-d9264386-bbd5-4b4d-bd8f-69bc738298f8.png)

In cluster management page it is correct

![image](https://user-images.githubusercontent.com/659363/158770471-e599581b-265a-465c-8990-69ecf52b13d7.png)

**To Reproduce**

- Create a few clusters
- delete one
- it is still visible 

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment]
Could not reproduce

**Comment by IsaSih** [comment]
not reproductible
