### ISSUE TITLE
RKE2 Snapshot Now and Restore actions must be removed from UI

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/dashboard#5429]
**Setup**
- Rancher version: v2.6-head d604b7e
- Browser type & version: Chrome Version 99.0.4844.51

**Describe the bug**

As per  [34417](https://github.com/rancher/rancher/issues/34417), etcd snapshot and restore got moved to 2.6.5 and the `Snapshot Now` and `Restore` actions should be removed for RKE2

**To Reproduce**

1. Create RKE2 node driver cluster
2. Check actions to take snapshot and restore

**Result**
The actions are there as expected

**Expected Result**

Now we need to hide the actions from the UI

**Screenshots**

![image](https://user-images.githubusercontent.com/97477402/158831561-136fcba0-d1b1-45df-abea-86b0897e7fa9.png)
![image](https://user-images.githubusercontent.com/97477402/158831602-288cfaf5-b899-4c99-bb7d-b258b84df626.png)

**Comment by sowmyav27** [comment]
Closing this for now, since if we remove this from the UI from 2.6.4, would be a regression wrt 2.6.3.
