### ISSUE TITLE
UI fixes for list pages

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#543]
- [x] In list page for namespace, can we make the word "Project" in a different color so that the word is less prominent:

<img width="157" alt="Screen Shot 2020-04-22 at 11 55 18 AM" src="https://user-images.githubusercontent.com/11410997/80021953-2d656c00-8490-11ea-9429-b082ef3e9a54.png">

- [x] In list page for any k8s resource, add `Namespace:` to the folder name so that it's clear that it's grouped by namespace. The name will be `Namespace: <namespace_name>`, which is similar to the `Project: <project_name>`. It's not obvious to new users that these groupings are namespace. 

<img width="247" alt="Screen Shot 2020-04-22 at 11 56 57 AM" src="https://user-images.githubusercontent.com/11410997/80022096-6ac9f980-8490-11ea-9a09-9917c6bdbbac.png">

- [x] On the `Namespace` list page, the content inside the project grouping in the table is aligned better than the spacing for any other resources. In the resource list, the checkbox is too close to the left edge. 

Namespace List View
<img width="493" alt="Screen Shot 2020-04-22 at 12 01 42 PM" src="https://user-images.githubusercontent.com/11410997/80022550-12472c00-8491-11ea-8815-02653e346273.png">

Resource List View 
<img width="294" alt="Screen Shot 2020-04-22 at 12 02 01 PM" src="https://user-images.githubusercontent.com/11410997/80022577-1d9a5780-8491-11ea-9525-96135a88d1db.png">

**Comment by deniseschannon** [comment]
The last item is still open. The spacing on other resources for where the checkbox is not the same as on the namespace page.

**Comment by lvuch** [comment]
@vincent99 is looking at this becuase the check for column widths isn't working as expected.

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/pull/751/commits/d41bb1f4f3ce8a370187507cf259dbd186885e24
