### ISSUE TITLE
Create PR template

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5434]
**Detailed Description**

Create PR template for this project with the following content. 

https://confluence.suse.com/display/EN/Issue+template+for+Devs+to+fill
```
### Root cause
### What was fixed, or what changes have occurred
### Areas or cases that should be tested
### What areas could experience regressions?
### Are the repro steps accurate/minimal?
```

**Context**

This will support both devs and QA in understanding the tasks.

**Comment by MKlimuszka** [comment]
@cnotv Does this need to be tested?

**Comment by cnotv** [comment]
@MKlimuszka Not rly tested, but I guess you can tell us if the informations have been provided and are helpful for QA, as we created mainly this for the QA process.
