### ISSUE TITLE
harvester load balancer, IPAM, defaults to `DCHP` and overrides user's selection

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5438]
**Setup**
- Rancher version: v2.6.4-rc9
- Browser type & version: any

**Describe the bug**

There is a default value for IPAM, `DCHP`, which is overriding the value the user selects. 

**To Reproduce**

* using harvester node driver, deploy a cluster with cloud provider enabled
* deploy a workload with an LB
  * note that the default is set to DCHP 
  * select `Pool` as the IPAM
* view the workload after creation

**Result**
LB deployed using DCHP instead of Pool

**Expected Result**
User selected option should be what is used for the deployment

**Additional context**
also tested the following:
* removing the ipam option when editing as yaml
  * still results in DCHP deployment
* does not occur when `cloning` an existing workload (default for IPAM is blank, and selecting either pool or dchp works as expected)

**Comment by slickwarren** [comment]
after more debugging, I've found the following:

* on a fresh create, no matter what the user selects, the resulting yaml/deployment sets spec.containers.ports._ipam = dchp -> default value overrides everything is the bug here. Even if you edit as yaml, that gets overridden with the default value of dhcp
  * is there a different values.yaml for clone vs. fresh deployment?  
* on a clone, there is no default value. Here it is revealed that, the UI is not setting the value at all for the deployment. So maybe that IPAM element isn’t connected to the backend variables? But again, no matter what the user sets, the UI value is set to null once the deployment is created. And in the backend, if there isn’t something set in values.yaml it is being set automatically to DHCP.  However, though the manually set yaml value is not read into the UI view, for cloned workloads I see that the yaml value is respected when creating the service (this is not the case when doing a fresh deployment)

**Comment by gaktive** [comment]
@jtravee this may have to a release note for 2.6.4 for Harvester

**Comment by jtravee** [comment]
> @jtravee this may have to a release note for 2.6.4 for Harvester

@gaktive, would you or @slickwarren be able to give a short note/summary from that that you'd like captured for the RN?

**Comment by n313893254** [comment]
`_ipam` is used for creating a service with an ipam annotation.

There is a workaround for the first bullet: After changing ipam, input listening port or container port.

**Comment by richard-cox** [comment]
@n313893254 Is the PR https://github.com/rancher/dashboard/pull/5444 targeted for 2.6.4, if so does it affect the release notes?

**Comment by n313893254** [comment]
@richard-cox  Yes, PR target for 2.6.4.  
I think it would affect the release notes because I fix the user selection issue. But for the second bullet on a clone, I am not sure about that.

**Comment by richard-cox** [comment]
@n313893254 Thanks! The PRs merged now, I'll leave the release note part to your side to determine

**Comment by jtravee** [comment]
> `_ipam` is used for creating a service with an ipam annotation.
> 
> There is a workaround for the first bullet: After changing ipam, input listening port or container port.

I'll add this to the release note, thanks!

**Comment by slickwarren** [comment]
tested on v2.6-head (85d6925) and no longer see this problem, however I did file a separate issue related to IPAM https://github.com/harvester/harvester/issues/2077
