### ISSUE TITLE
Add text to make ingress/service creation more understandable to Kubernetes newcomers

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5441]
I opened this issue to track the low-hanging fruit part of https://github.com/rancher/dashboard/issues/4518. That issue is about streamlining the ingress and service creation process. This is just about adding more explanatory text and doing better signposting so that a new user can better understand the UI.

## Workload Create/Edit Form

In the Ports section,

  - Change "Ports" to "Networking" because that section can create a Service in addition to defining a port.
  - Add a tooltip that says "For help exposing workloads on Kubernetes, see the official Kubernetes documentation on Services. You can also manually create a Service to expose Pods by selecting their labels, and you can use an Ingress to map HTTP routes to Services."
  - Add a description that says "Define a Service to expose the container, or define a non-functional, named port so that humans will know where the app within the container is expected to run." (If a port is defined, it updates the YAML on the workload being created. If one of the Service types is selected, it creates a Service that selects the workload using automatically created labels.)
  - Change button from "Add Port" to "Add Port or Service".
  - If the "Add Port or Service" button is clicked, more explanatory text appears: "If ClusterIP, LoadBalancer or NodePort is selected, a Service is automatically created that will select the Pods in this workload using labels."

## Service Create/Edit Form

  - A description says what a Service is. "Services allow you to define a logical set of Pods that can be accessed with single IP address and port."
  - On the Selector tab, explain that "Selector keys and values are intended to match labels and values on existing Pods."
  - Add a tooltip to target port: "The Service will send requests to this port, and the selected Pods are expected to listen on this port."
  - Add a tooltip to listening port: "The Service is exposed on this port."

## Ingress Create/Edit Form

- A description says what an Ingress is. "Ingresses route incoming traffic from the internet to Services within the cluster based on the hostname and path specified in the request. You can expose multiple Services on the same external IP address and port."
- In the Rules tab, the target service dropdown has a tooltip: "If none of the Services in this dropdown select the Pods that you need to expose, you will need to create a Service that selects those Pods first."

## Service Description

When you go to the service list view and click Create, the descriptions should be clearer. It should more clearly indicate that the ExternalName and Headless services are for advanced use cases.

**Comment by catherineluse** [comment]
@nwmac can this be in v2.6.5?

**Comment by slickwarren** [comment]
tested on v2.7-head (a49d36c):
* workflow creation of 'networks' is now more clear -- pass
* services creation has helpful tooltips and wording is improved -- pass
* ingress creation now included helpful tooltips -- pass
