### ISSUE TITLE
Improve performance of resource lists

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5445]
Address various performance issues with lists of resources - e.g. Nodes list, workloads list.

There are performance improvements that can be made to the SortableList component

**Comment by nwmac** [comment]
To test: create a large number of deployments ands pods: eg 3000 each. Before 2.6.5 pare loading for the list views for these resources was slow, as was changing page. You should see a noticeable performance improvement in the list loading time and much snappier times to change page.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.6.4                                    |
| Installation option       | helm high availability                   |
| RKE binary version used   | v1.3.8                                   |
| If Helm Chart k8s cluster | v1.22.7                                  |
| Cert Details              | self signed                              |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | rke1 amazon ec2s                         |
| Downstream K8s version    | v1.22.7                                  |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |


## Reproduction steps

1. Run script to create 3,000 deployments & pods
2. Wait for script to complete
3. Navigate around various pages of deployments in the Rancher UI
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
To browse deployments easily / quickly

#### :x: Actual
Noticeable lag / slowness when navigating through the pages of 3,000 deployments

<hr>
  
## Validation Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | v2.6.5-rc2                               |
| Installation option       | helm high availability                   |
| RKE binary version used   | v1.3.10-rc4                              |
| If Helm Chart k8s cluster | v1.22.8                                  |
| Cert Details              | self signed                              |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | rke1 amazon ec2                          |
| Downstream K8s version    | v1.22.8-rancher1-1                       |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |



## Validation steps

1. Run script to create 3,000 deployments & pods
2. Wait for script to complete
3. Navigate around various pages of deployments in the Rancher UI
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
To browse deployments easily / quickly

#### :white_check_mark:Actual
To browse deployments easily / quickly, very noticeable difference, seconds faster
