### ISSUE TITLE
Mimic 2.5 UI for Node Labels sub-row under Cluster view

### ISSUE THREAD

**Issue by flrichar** [rancher/dashboard#5448]
Internal Reference: SURE-4267

**Setup**
- Rancher version: 1.21
- Browser type & version: Chrome, Firefox, both latest versions

**Describe the bug**
 Under the 2.5 UI, one could see a list of Labels at a glance for each node, when in the Cluster view.  In 2.6 to see labels, one must go into the Node view.  This breaks the user's accustomed workflow.

**To Reproduce**
 Select any cluster, go to Cluster -> Nodes option, and cannot see any Node Labels.

**Result**
 Labels not showing under Cluster view, additional steps are required.  This can get inefficient with a large number of nodes.

**Expected Result**
 Mimic the sub-row like in 2.5 to show node labels in the cluster view

**Screenshots**
...

**Additional context**
...

**Comment by richard-cox** [comment]
Linking issue that should probably be tackled at same time https://github.com/rancher/dashboard/issues/5183

**Comment by nwmac** [comment]
Add a button to toggle node labels to show/hide sub-row for nodes - this can then show the node labels.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head d559c2f
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 110

----------

### Testing: ###
Tested this issue with the following steps:
1. Create cluster with node labels on each node pool
2. After cluster is Active, go to node view and verify labels are seen with each node that has a label

**Result**
Dashboard now shows the node labels in the nodes when labels are set.
![image.png](https://zube.io/files/rancher/5efe4c92785c6a7bccaef0ef6f5f96ed-image.png)
