### ISSUE TITLE
[vsphere node driver rke2] setting `OS: windows` in the UI does not correctly set `machineOS: windows` in the cluster.yaml

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5452]
**Setup**
- Rancher version: v2.6-head 024e6fa
- Browser type & version: any

**Describe the bug**
when setting windows for the OS type in a vsphere node driver, the OS is not actually being set

**To Reproduce**
* provision a vsphere node driver rke2 cluster
  * include a windows worker pool, and set the `os` to windows

**Result**
* windows pool does not have `os = windows`

**Expected Result**

* setting OS field should set the OS

**Screenshots**
<img width="1479" alt="Screen Shot 2022-03-21 at 2 20 58 PM" src="https://user-images.githubusercontent.com/16691014/159366292-4be34a33-ebcc-4e7d-84f1-4caf1145df98.png">

**Additional Info**
* manually settings `machineOS: windows` in the cluster.yaml for this pool will correctly set the OS

**Comment by mantis-toboggan-md** [comment]
I could use some clarification on what needs to be set here @rosskirkpat , looking at the associated rancher [PR](https://github.com/rancher/rancher/pull/35582/files#diff-e05181e81036cad4014bb4843ea91837fa7dd238dc3434bc4fcc598c56db6428R29) for this, it seems like you're expecting a value set in the provisioning cluster's spec.rkeConfig.machinePool[] called `machineOS`. Right now, the UI is setting a field in the machine config (`rke-machine-config.cattle.io.vmwarevsphereconfig`), which, according to its schema, does have an `os` field. Do we only need to set `machineOS` in the rkeConfig or do we need to set both?

**Comment by slickwarren** [comment]
tested with v2.6.4-rc12:
now, the machine OS through the UI also is being set in the yaml

opened this bug as a result of this testing.
