### ISSUE TITLE
[BUG] Form for configuring Receivers and Output should more clearly indicate where to input Port

### ISSUE THREAD

**Issue by Tejeev** [rancher/dashboard#5453]
Internal ref: SURE-3041

**What kind of request is this (question/bug/enhancement/feature request):**
Bug/Parity

**Description**
The port should be input in a separate field when configuring receivers for alerts to keep parity with v1 and logging v2 outputs.  It's easy to miss that the port should be put in the URL field, especially when you've already pasted your URL endpoint in the field (which erases the example).  This would be consistent with Monitoring v1 Notifiers and Elastic Search outputs in Logging v2.
The grey on grey text of the examples on the light background is too easily missed by the user (the customer I was working with had trouble reading it and so do I) and the Logging output field does not even display an example.

**Steps to reproduce (least amount of steps as possible):**

**Result:**
Alerting Reciever:
![image](https://user-images.githubusercontent.com/8906089/112328089-e7231900-8cad-11eb-91ca-aca6e5f91c35.png)
![image](https://user-images.githubusercontent.com/8906089/112367880-64f91b80-8cd2-11eb-853e-720c12a8db7f.png)

Logging Output for an elasticsearch endpoint separates the port into its own box, like in v1
![image](https://user-images.githubusercontent.com/8906089/112372945-56156780-8cd8-11eb-9b5d-487058c2383f.png)

Note the example text in the "Description" field above is easily missed and for some will be illegible.
![image](https://user-images.githubusercontent.com/8906089/112369202-d5ed0300-8cd3-11eb-95f9-085d2b104d99.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7

gz#15698

**Comment by nwmac** [comment]
@bisht-richa We should add a separate field for the port so it is clearer - we will then need to combine host and port to wire into the value.

**Comment by gaktive** [comment]
Engineering to write an automated test in #8830 to help QA.
