### ISSUE TITLE
[inconsistent options] `scale down` available in node `...` options, but not on `cluster` -> `machinePools` page 

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5454]
**Setup**
- Rancher version: v2.6.4-rc10
- Browser type & version: chrome

**Describe the bug**
options for a given node for scaling down are disabled when pool count = 1 and pool has worker label, but are enabled in the `...` options for that node. 

**To Reproduce**
* provision a cluster with 1 node per role
  * note that the `scale down` option is disabled for all nodes
* click the `...` option 
  * note that you can scale down the cluster's worker node. 
**Result**
* pool is removed/scaled down

**Expected Result**
Options for users should be consistent in the UI

**Screenshots**
<img width="192" alt="Screen Shot 2022-03-21 at 3 39 45 PM" src="https://user-images.githubusercontent.com/16691014/159376217-1af5766e-10b5-49c0-8245-4a8baa8c7ca1.png">
<img width="167" alt="Screen Shot 2022-03-21 at 3 39 41 PM" src="https://user-images.githubusercontent.com/16691014/159376219-c035d5c7-2f2b-41c4-8d2a-be82e444aab8.png">

**Comment by gaktive** [comment]
Based on feedback from management, we need to avoid scenarios where people can scale down to 0 by accident.

**Comment by gaktive** [comment]
At the very least, we should confirm if this is happening in RKE2. If it's only RKE 1, we can defer this to 2.6.6. Related backend: https://github.com/rancher/rancher/issues/36502

**Comment by richard-cox** [comment]
> Based on feedback from management, we need to avoid scenarios where people can scale down to 0 by accident.

@gaktive Can we get some further clarity? I was told that only control plane and etcd nodes had to be protected, and that worker nodes can be reduced to zero. 

That's the basis of 
- The bulk scale down nodes button (and the process there to leave at least one of the two types)
- The single scale down node button

It wasn't applied to the machine deployments scale down button. If the above is correct it would mean 
- the single scale down node button is correctly enabled
- the machine deployment scale down button is incorrectly disabled

**Comment by gaktive** [comment]
@richard-cox additional context: https://github.com/rancher/rancher/issues/37378, though that may be a separate scenario as I reread since the fear is that we could walk into a scenario whereby an entire nodepool in a zone disappears. 

If that's the case, it's no longer a release blocker.

**Comment by richard-cox** [comment]
@gaktive In the same area, but i don't think it's related to this one. I think that issue might be a bug with the bulk actions for node pools (rke1). If the last node in a pool is removed the pool might not be visible in that view but might still exist, if the pool is actually gone it's definitely a bug (rather than bad UX).

In terms of this issue, i'd agree it's not a blocker. In terms of what we should expect when scaling to zero I've asked for more details in slack. What we have at the moment shouldn't break RKE2 clusters (we only allow scaling to zero of worker types). Haven't dug in to RKE1.

**Comment by richard-cox** [comment]
Ok, bringing together info from slack and github the following should be fine.

- Scaling down to zero workers
- Scaling down to one control plane
- Scaling down to one etcd
- Scaling down to zero machines in a deployment (as long as the above rules aren't invalidated)

I've checked with @brandond , and from his RKE2 perspective, he raised questions regarding scaling etcd down such that it invalidated quorum (1,3,5). That's something users would need to be considerate of, that aside there weren't any objections.

I propose that the same kind of logic for scaling down is applied to scaling down a group as the other two places. So we just need to prevent scaling down if there would be no control plane or etcd machines left.

For reference
- scaling down a machine deployment - ./models/cluster.x-k8s.io.machinedeployment.js scalePool
- scaling down in single instance - ./models/cluster.x-k8s.io.machine.js canScaleDown
- scaling down multiple instances - ./components/dialog/ScaleMachineDownDialog.vue

**Comment by brandond** [comment]
I will note that I don't believe we currently **test** scaling down etcd node pools for RKE2 or K3s. It should work if it is done carefully but I don't believe this has ever been something that was specifically called out as supported, so it's not been tested.

**Comment by markusewalker** [comment]
Verified this is addressed in `v2.6.5-rc3` and `v2.6-head` https://github.com/rancher/rancher/commit/5f04f3abc36b6f8edfc38f91170cf2c3c366f72e.

**ENVIRONMENT DETAILS**
- Ubuntu 18.04.6 - HA
- Rancher version: `v2.6.5-rc3` & `v2.6-head` https://github.com/rancher/rancher/commit/5f04f3abc36b6f8edfc38f91170cf2c3c366f72e
- Browser: Chrome
	
**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to Rancher UI in a browser.
2. Created two downstream clusters: 
	a. 1 RKE2 cluster - 1 cp, 1 etcd, 1 worker
	b. 1 RKE2 cluster - 1 cp, 1 etcd, 3 worker
3. Navigate to top-left dropdown menu > Cluster Management > created cluster with 1 worker node. 
4. Verified that I can scale down with only one worker node, but am unable to scale down my only etcd and only control plane nodes:
![image](https://user-images.githubusercontent.com/52591819/165641257-f891e614-b423-4224-835a-dd434b42b5ea.png)
![image](https://user-images.githubusercontent.com/52591819/165641272-0961330a-1282-4f66-8a41-c38b9ddeb0a7.png)
5. Scaled both my etcd and cp nodes by 1 and verified that I can now scale down:
![image](https://user-images.githubusercontent.com/52591819/165641305-1eae8a91-9022-44c2-8e1f-7abe0fa916b1.png)
6. Repeat steps 3 and 4, but this time with the downstream cluster that has multiple worker nodes. Verified that I receive the same results as step 4.
![image](https://user-images.githubusercontent.com/52591819/165641341-6d0c8bac-8c3b-4b04-8174-c4ee19a6b7e9.png)
![image](https://user-images.githubusercontent.com/52591819/165641349-331aece5-0bfd-4dce-b8cb-febe28e8503d.png)
