### ISSUE TITLE
Cluster Options in Edit Config are not editable.

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/dashboard#5455]
**Rancher Server Setup**
- Rancher version: v2.6-head (024e6fa)
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.18.20/v1.19.16/v1.20.15/v1.21.10/1.22.7/v.23.4
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? AWS Node driver / RKE1 

**User Information**
- What is the role of the user logged in? : Standard User
   
**Describe the bug**

After successful cluster creation the **Edit Config** options are not editable

**To Reproduce**
 

1. Create a rancher server v2.6-head
2. Provision a downstream cluster. AWS or RKE1. (in my opinion this issue may not specific to a cluster type.)
3. Once the cluster provisioning is successful, click on **Edit Config** option.

**Result**
Cluster options are not editable.

**Expected Result**

Cluster options should be editable.

**Screenshots**

![cluster-options2](https://user-images.githubusercontent.com/83208989/159262415-db930fd6-ba97-4e22-907b-37ac5857d926.png)

**Comment by gaktive** [comment]
Sounds similar to #5442.

**Comment by Josh-Diamond** [comment]
Unable to access `Create Cluster` for RKE2/k3s Node driver provisioned clusters

With Docker single-node instance on rancher `v2.6-b7c9b893bfd8fb5c2a3e16ae0836d92f98ecc22d-head`:
1.  Fresh install of rancher `v2.6-head`
2. As admin, `Create` cluster
3. Select `RKE2/k3s` for ANY Node driver provisioned cluster
4.  Issue - User is directed to `Custom Cluster` page, form doesn't prompt from api tokens, instead it suggests registering the cluster nodes individually

Screenshot:
<img width="1644" alt="Screen Shot 2022-03-23 at 11 51 44 AM" src="https://user-images.githubusercontent.com/46494969/159774397-f2127ec1-8847-4b7d-b2c5-65b8b5f2beb2.png">

**Comment by rishabhmsra** [comment]
Validated this on rancher v2.6-head(b7c9b89)
- **Edit Config issue is resolved now, provisioned RKE1 clusters using all the k8s versions and the "Edit Config" options are editable now:**

![edit-config](https://user-images.githubusercontent.com/36376154/159904446-856f0267-58c6-4f1e-ad42-55dec42d9812.png)
