### ISSUE TITLE
Setting support link does not change title of link

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5461]
Internal Reference: SURE-4261

When a user sets a custom support link, we only change the link destination for the link shown on the home page - this is within a box called 'Community Support' under the `File an Issue`.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/1955897/159462621-675bcb67-ef07-450a-8655-c527a5b5ad85.png">

When a custom support link is set, we should change the title of the box to say 'Support' instead of 'Community Support'

**Comment by sowmyav27** [comment]
**on 2.6.5-rc2**

- Navigate to Global Settings --> Branding --> Support Links
- Add in a URL. Save changes
- Navigate to Home

<img width="1037" alt="Screen Shot 2022-04-24 at 7 40 13 PM" src="https://user-images.githubusercontent.com/26032343/165011849-d56ff1c5-d2bf-4660-a0c4-562b89db1404.png">
- Navigate to Global Settings --> Branding --> Support Links
- Remove the URL. Save changes
- Navigate to Home
- Section is titles - Community Support
