### ISSUE TITLE
Possible bug regression: Can't select groups with Okta integration

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5464]
**Setup**
Rancher 2.6.3-patch1

**Describe the bug**
[Slack thread here](https://rancher-users.slack.com/archives/C3ASABBD1/p1647547923787119)

As user description:
_There is not any group in the dropdown in my cluster settings, I'm using Okta an can log in without problems, in one of my older clusters (Rancher 2.5.3) it seems to work fine, both of my SAML applications in Okta are configured the same way_
_the difference is that my installation is clean (installed 2.6.3-patch1 a month ago)
Taking a look into the SAML Assertion the assertion that 2.6.3-patch1 makes (or gets) does not have the groups attribute, and the assertions that 2.5.3 makes (or gets) does have the groups attribute_

**To Reproduce**
As user description - Same as related issue [Can't select groups with Okta integration](https://github.com/rancher/rancher/issues/30401)

**Result**
User cannot see groups in dropdown in `Cluster Settings`
![Screenshot_20220317_171130](https://user-images.githubusercontent.com/97888974/159506097-cc9a587b-cdd4-41ad-8792-ef85ba397de4.png)

**Expected Result**
User should be able to see his groups in `Cluster Settings`

**Additional Screenshots**
As user description:
_This is my Attribute configuration Okta side
2.6.3-patch1 only gets userName and displayName
2.5.3 get userName, displayName and the groups list_
![Screenshot_20220318_092504](https://user-images.githubusercontent.com/97888974/159506093-81140762-655a-4bb7-b115-8e67bdb71e80.png)

**Comment by gaktive** [comment]
This bubbled up again. Internal reference: SURE-2882

**Comment by samjustus** [comment]
@gaktive yes please

**Comment by gaktive** [comment]
https://github.com/rancher/rancher/issues/38029 filed for backend to investigate on that side. UI will place this in Backend Blocked until either there's work we need to do or anything to test/validate independently of QA.

**Comment by junkiebev** [comment]
In my opinion, I don't believe y'all are going about this the best way (scraping attributes from the assertion) because one will _only_ ever to be able to see groups which one belongs to. I would suggest that providing an Okta API key and hitting the Okta Groups API periodically to sync-up is the best path forward.

**Comment by gaktive** [comment]
Related backend work (who are driving this issue) have pushed to 2.6.x.

**Comment by gaktive** [comment]
This was done in 2.7.5 per https://github.com/rancher/dashboard/issues/8675 and related backend tickets. Closing.
