### ISSUE TITLE
Hide S3 configuration section for RKE2 provisioned clusters

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#5466]
**Detailed Description**
Due to blocker issues with etcd snapshot/restore functionality to/from S3 buckets (most specifically https://github.com/rancher/rancher/issues/36941) and the fact RKE2 provisioning is not GA in 2.6.4, it's requested to hide S3 snapshot configuration section for RKE2 provisioned clusters (essentially revert https://github.com/rancher/dashboard/issues/4551)

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `c2d8e32`**

- For RKE2 node driver and custom clusters, S3 config section is not available when deploying an RKE2/k3s cluster
<img width="1454" alt="Screen Shot 2022-03-23 at 10 28 25 AM" src="https://user-images.githubusercontent.com/26032343/159627673-602897cc-40b1-45a1-acfd-eb1bbc4b7ca6.png">
