### ISSUE TITLE
RKE2 snapshot S3 configuration support

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#5467]
**Detailed Description**
Re-enable S3 configuration support that was initially added to 2.6.4 per https://github.com/rancher/dashboard/issues/4551 and then removed per https://github.com/rancher/dashboard/issues/5466.

**Context**
Needed for RKE2 provisioning GA.

**Comment by timhaneunsoo** [comment]
Snapshot S3 configuration support is now enabled
![image](https://user-images.githubusercontent.com/97477402/163449721-b7768674-cee8-4c8b-902c-4f0642dad9f6.png)
