### ISSUE TITLE
Remove Unused Components

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#547]
When looking into components, I found a couple of them that seem to not be used. 

Can they be removed? 

TableSparkLine
Random
DiscreteProgressBar

**Comment by vincent99** [comment]
Things that are not used are automatically not actually part of the bundled output.

>TableSparkLine

This will likely be used when metrics are available from monitoring or rio.

>Random

This is used occasionally for prototyping/demos (,but normally wouldn't make it into committed code).

>DiscreteProgressBar

Yes, this is basically the same as `PercentageBar` (though `DiscreteProgressBar` is probably the better name).

**Comment by westlywright** [comment]
@deniseschannon Doesn't seem like we should remove these based on @vincent99 comment. Can we close this?

**Comment by vincent99** [comment]
The DiscreteProgressBar is redundant & confusing, the other 2 I'd like to keep..

**Comment by izaac** [comment]
As per conversation with @westlywright this was never used in any release, this is just removing the component file from the Vue components directory.
