### ISSUE TITLE
Importing K3s or RKE2 clusters aren't listed correctly in cluster management, under provider

### ISSUE THREAD

**Issue by Auston-Ivison-Suse** [rancher/dashboard#5477]
**Setup**
- rancher version: v2.6.3
- Chrome version:99.0.4844.74 

**Describe the bug**
Importing a specific clusters don't have them listed as "imported" like they should 

**To Reproduce**
1. Import cluster
2. go to cluster management

**Result**
Under provider instead of listing "imported" you will either get RKE2 or K3s (these are the two I attempted to import) 

**Expected Result**
We should have similar 

**Screenshots**
<img width="1510" alt="ImportedCluster" src="https://user-images.githubusercontent.com/89411550/159634603-70e0e86c-0a41-4a4d-93ed-ef8c26696ac1.png">

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/e93864b3364e18e81dfd5c12366206f2d495cf52.

**ENVIRONMENT DETAILS**
- Rancher HA
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/e93864b3364e18e81dfd5c12366206f2d495cf52
- RKE1 version: `v1.23.6`
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. On a local client machine, created two clusters: one for K3s, one for RKE2.
2. Setup Rancher and navigated to the UI in a browser.
3. Created a standard user and login to Rancher as that user.
4. In Cluster Management, import both the K3s and RKE2 clusters previously created in step one; verified that they are listed correctly:
![image](https://user-images.githubusercontent.com/52591819/170578688-93e24203-48c3-4c91-841a-e168834a04cf.png)
