### ISSUE TITLE
Edit as yaml for a resource is unusable

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5483]
The sticky footer seems to have broken the edit as yaml.

Go to a resource - e.g. deployment and click 'Edit as Yaml'.

The code panel goes beneath the buttons - see bottom of image below:

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/1955897/159691702-4fff4ed6-bf9b-4d2f-af54-cb7274232c0d.png">

The buttons can not be accessed while the code overlays the buttons - if you scroll to the bottom of the page, you can click the buttons, but if you click 'Back to form':

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/1955897/159691949-a0466ed7-b34e-49ae-be41-656cbe744eaf.png">

the dialog can not be used.

**Comment by cnotv** [comment]
That's interesting, since the YAML should not be part of the CRU editor component.

**Comment by cnotv** [comment]
There is an issue with Codemirror component, where the elements have a `z-index` increased, without set it to their wrapper.


https://user-images.githubusercontent.com/5009481/159698532-5ef7d584-ca91-4cb9-b815-1879a8197d7c.mp4

**Comment by Josh-Diamond** [comment]
Ticket #5483 - Test Results

With Docker on single-node instance:

Reproduction Failure - unable to reproduce on rancher `v2.6.3` and `v2.6.4`

Verified on rancher `v2.6.4`:
1. Fresh install of rancher `v2.6.4`
2. Go to any resource and click `Edit YAML`
3. Verified - sticky footer functioning as expected; no UI overlays

Screenshots:

`No overlays`:
<img width="1077" alt="Screen Shot 2022-04-08 at 4 50 38 PM" src="https://user-images.githubusercontent.com/46494969/162548783-af397497-a74d-4c8c-a3e7-b2342fa935f0.png">

`Sticky footer at bottom`:
<img width="1076" alt="Screen Shot 2022-04-08 at 4 50 50 PM" src="https://user-images.githubusercontent.com/46494969/162548818-f41485c0-6922-40b5-abc3-591441b0be00.png">
