### ISSUE TITLE
Different behaviors on Rancher first login

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5486]
**Setup**
- Rancher version: 2.6.4
- Browser type & version: Any

**Describe the bug**
Behaviors on first login are not consistent `/auth/setup` after adding bootstrap password

**To Reproduce**
- Create a new Rancher instance
- Add bootstrap password
- Follow instructions in results

**Result**
- On refresh page without cookies, it breaks with 401
- On access to root `/`
  - Bootstrap password is removed
  - Server URL is cropped and lacks the protocol `https://`

**Expected Result**
- On refresh the user is redirected if cookies are missing
- On access to root `/` values are kept or added correctly or user is redirected to bootstrap page

**Screenshots**

https://user-images.githubusercontent.com/5009481/159739390-23451f79-9e31-4f8b-9474-59d11ec18e42.mp4

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by aalves08** [comment]
Tried to reproduce this but couldn't...
Differences worth mentioning:

node version: v12.22.9
using Digital Ocean instead of local instance

**Comment by richard-cox** [comment]
I've seen some very weird scenarios when using helm and `bootstrapPassword=admin`. Docs are currently suggesting this, i'd be interested to know if this has provided a smooth log in for them.

My guess is that the `admin` value is causing havoc with the old way we used to try to automatically sign in.

@gaktive Can we get someone to validate this behaviour next week? It makes for a very bad first experience

**Comment by nwmac** [comment]
@richard-cox Does this still need looking into?

**Comment by cnotv** [comment]
@richard-cox just as a reminder, since I cannot start Rancher locally on Mac anymore, I cannot check the status of this.

**Comment by gaktive** [comment]
We'll use #5649 to tackle this, so we'll close. In the backlog for 2.6.6

**Comment by cnotv** [comment]
@gaktive Seems a bit different the content, but ok 😅
