### ISSUE TITLE
2.6-head has ui-dashboard-index set to `latest`, should be `2.6.4-release`

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5496]
**Setup**
- Rancher version: v2.6-head (b7c9b89)
- Browser type & version: any

**Describe the bug**
us-dashboard-index should be set to `https://releases.rancher.com/dashboard/release-2.6.4/index.html` but is currently set to `...latest/index.html` on 2.6-head

**To Reproduce**
* deploy rancher using 2.6-head 

**Result**
currently set to `...latest/index.html` on 2.6-head

**Expected Result**
since we've split the branches, we should update the dashboard-index for the new branch. 

**Context**
affects ui for 2.6.4 release/testing.

**Comment by catherineluse** [comment]
@richard-cox It seems like another change is needed to reset the default UI index

**Comment by richard-cox** [comment]
@catherineluse There's a PR already open for this, just waiting on someone rancher/rancher side to review and merge (see release channel in slack).

https://github.com/rancher/rancher/pull/37011

**Comment by sowmyav27** [comment]
**To Validate** 

- Once this [build](https://drone-publish.rancher.io/rancher/rancher/7539) is complete, deploy rancher 2.6-head
- Navigate to Global Settings --> `ui-dashboard-index` is set to `https://releases.rancher.com/dashboard/release-2.6.4/index.html`

**Comment by Josh-Diamond** [comment]
Ticket #5496 - Test Results

Reproduced on `v2.6-b7c9b893bfd8fb5c2a3e16ae0836d92f98ecc22d-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, navigate to `Global Settings`
3. Reproduced - `ui-dashboard-index` is set to `https://releases.rancher.com/dashboard/latest/index.html`

Screenshot:
<img width="1445" alt="Screen Shot 2022-03-24 at 9 29 05 AM" src="https://user-images.githubusercontent.com/46494969/159967735-ef3e86e6-45a2-44f5-b652-e653734e37d6.png">


Verified on `v2.6-85d692518525d2a1f9eb740833145b242608632e-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, navigate to `Global Settings`
3. Verified - `ui-dashboard-index` is set to `https://releases.rancher.com/dashboard/release-2.6.4/index.html`

Screenshot:
<img width="1439" alt="Screen Shot 2022-03-24 at 10 12 06 AM" src="https://user-images.githubusercontent.com/46494969/159972572-4864213d-5827-49db-a5cc-272cf535eac1.png">
