### ISSUE TITLE
iFramed cluster edit forms show incorrect cluster members

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5497]
**Setup**
- Rancher version: v2.6.3 (v2.6-head)
- Browser type & version: Firefox

**Describe the bug**
Viewing one iFramed cluster edit form has side effects affecting other ones. If you add members to one form, then navigate to the second one, you will see the cluster members from the first form in the second one, which is confusing.

The workaround is to refresh the page.

**To Reproduce**

1. As an admin, provision any two clusters that both use iFramed Ember forms for the edit page. Examples are: an Amazon EKS cluster, an RKE1 node driver cluster, or a custom RKE1 cluster. Call these `cluster1` and `cluster2`.
2. Create a user named `cluster-owner1`.
3. Add the user to `cluster1`.
4. Navigate to the cluster edit form for `cluster2`. See that `cluster-owner1` is incorrectly in the member list even though you did not add him.
5. Refresh the cluster edit page for `cluster2`. See that the incorrectly added user is gone.

This will also work in reverse. Refresh the edit page for `cluster2` and add another user there, then navigate to `cluster1` and see that the user you just added to `cluster2` is shown in `cluster1` - until you refresh the page.

**Result**
Cluster member list for one form is incorrectly taken from the wrong cluster.

**Expected Result**
Cluster member list is accurate.

**Screenshots**
This is the member list:
<img width="1580" alt="Screen Shot 2022-03-23 at 11 13 40 PM" src="https://user-images.githubusercontent.com/20599230/159853698-c4382499-7f92-4176-b2ba-e24cd3e0cbe8.png">

There is a related issue with these iFramed forms where if you navigate to it, then go to the cluster list view and come back, the page is blank until you refresh. https://github.com/rancher/dashboard/issues/5511

**Comment by mantis-toboggan-md** [comment]
Fixed here https://github.com/rancher/ui/pull/4824

**Comment by markusewalker** [comment]
Verified on `v2.6.5-rc9`.

**ENVIRONMENT DETAILS**
- Rancher HA
- RKE version: `v1.23.6`
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Created a standard user, but stayed logged in as the default admin user.
3. Created a downstream RKE1 Node Driver cluster and added the standard user I previously created in the member roles.
4. After cluster creation, verified that the member roles show both the default admin and the standard user:
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/52591819/167691082-c228234c-f80e-4eef-ab0f-322ca2a70a17.png">
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/52591819/167691109-6f691c1c-e5d8-4254-b9d9-a87b08da3d71.png">
5. Begin to create a new downstream RKE1 Node Driver cluster and look at the member roles; verified there are no unexpected members there:
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/52591819/167691184-082bf9f9-fc98-43cf-804f-be4fd51c0c5f.png">
6. Created the second downstream RKE1 Node Driver cluster and verified that the members are only the default admin user:
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/52591819/167691230-16998f5b-9da5-44c3-be15-fc99b3542ecb.png">
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/52591819/167691241-6aa2f538-b9d2-47f5-9c72-2be20798f10e.png">
