### ISSUE TITLE
2.6.X Sidebar UI not updating

### ISSUE THREAD

**Issue by omarroman1** [rancher/dashboard#5503]
**Setup**
- Rancher version: 2.6.X
- Browser type & version: Chrome latest & Firefox latest

**Describe the bug**
When deleting old backups in bulk the Rancher UI updates automatically but the Sidebar UI does not update unless you refresh the page

**To Reproduce**
Cluster --> Velero.io backups --> Create a ton of backups --> Delete backups in bulk --> Watch the UI 

**Result**
The main screen updates automatically but the sidebar numbers doesn't change unless you refresh the page.

**Expected Result**
All the UI's should update at the same time.

**Comment by richard-cox** [comment]
@omarroman1 Can you provide some low level steps to reproduce, including your flow for installing velero in kube?

Those numbers come from the backend, we would need to confirm the update to `counts` is coming over socket
