### ISSUE TITLE
wins-upgrader is not meant for rke2 windows setups. We should hide the chart for rke2 windows clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5507]
**Setup**
- Rancher version: 2.6.4-rc12
- Browser type & version: any

**Describe the bug**
wins-upgrader is not meant to run on rke2 windows. 

**To Reproduce**
* deploy rke2 windows cluster
* go to `apps & marketplace`

**Result**
wins-upgrader is available. 

**Expected Result**
given windows users are used to this chart (from rke1), we should make it clear to users that this chart is not meant for rke2 windows clusters. 

**Additional context**
see this discussion for more details https://github.com/rancher/rancher/issues/37020#issuecomment-1077881387

**Comment by gaktive** [comment]
@luthermonson is there an annotation that the UI could rely on to detect if RKE1 vs RKE2 is being requested here?

**Comment by gaktive** [comment]
PR https://github.com/rancher/charts/pull/1783 might be of use.

**Comment by luthermonson** [comment]
@gaktive not sure if we should be adding more annotations to charts to get this accomplished. unfortunately it might just be an `isRke2 == true` and we hide it. we do this kind of code all over provisioning e.g. https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go#L28-L29 you can see we just check the cluster object and if it has the cluster.Status.Driver matched against a constant it will be true.

**Comment by slickwarren** [comment]
tested on v2.6-head (cd0555b):
* windows + rke2 clusters are no longer showing the wins-upgrader chart
