### ISSUE TITLE
[vsphere node driver rke2]  `scheduling` options cleared for machine pool with `windows` selected

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5508]
**Setup**
- Rancher version: v2.6.4-rc13
- Browser type & version: chrome

**Describe the bug**
when creating a windows rke2 machine pool with vpshere node driver, the `scheduling` options  (i.e. datastore, resource pool, etc) are cleared from the UI when creating the cluster and set to default values. 

**To Reproduce**
deploy a windows rke2 cluster using the vsphere node driver 

**Result**
 the `scheduling` options  (i.e. datastore, resource pool, etc) are cleared from the UI when creating the cluster and set to default values. you can see this during editing by clicking the `edit as yaml` option, and then go back to `back to form`

**Expected Result**
windows machine pool should respect user-entered values in the UI

**Comment by mantis-toboggan-md** [comment]
I've tried making multiple rke2 clusters and haven't been able to repro this. Both the UI and network requests reflect the scheduling config I altered from default values.

**Comment by slickwarren** [comment]
confirmed, I can't reproduce this on 2.6-head (cd0555b)
