### ISSUE TITLE
iFramed ember form disappears

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5511]
**Setup**
- Rancher version: v2.6.3 (v2.6-head)
- Browser type & version: Chrome

**Describe the bug**
If you navigate away from the form, then go to the cluster list view and come back, the page is blank. The workaround is to refresh the page.

**To Reproduce**
1. Create an RKE1 cluster.
2. In cluster manager, go to the cluster and click Edit Config. The form is fine.
3. Go to the cluster list view.
4. Go back to Edit Config.

**Result**

The form disappeared.
<img width="1668" alt="Screen Shot 2022-03-24 at 1 17 21 PM" src="https://user-images.githubusercontent.com/20599230/160002923-98c36800-462e-4eb8-8cd7-2158f43ceeec.png">

**Expected Result**
The form is there.

**Comment by nwmac** [comment]
Can not reproduce
