### ISSUE TITLE
IAM instance profile name should be marked as required if the Amazon cloud provider is selected

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5517]
Currently, if you try to provision an EC2 cluster through Rancher, if you enable the Amazon cloud provider without selecting any instance profiles, the UI lets you complete the form but then the cluster gets stuck in provisioning. This is a bad user experience because there is no visual indication of what is wrong.

There is a tooltip explaining this, but it's too easy to miss, and it is still displayed as an optional field:
<img width="663" alt="Screen Shot 2022-03-24 at 3 54 05 PM" src="https://user-images.githubusercontent.com/20599230/160023768-f294fc51-c78b-4db8-a93c-d295590df78f.png">

- When the Amazon cloud provider is selected, the instance profile dropdown should be marked required with a red asterisk.
- The save button should be disabled if that info is not provided.

Note: We should see if only controlplane nodes need an instance profile.

Background/context: When you enable the Amazon cloud provider you're basically saying you want to give Kubernetes permission to provision new hardware on EC2 like load balancers, and the instance profile gives it the IAM permissions to do that.

**Comment by gaktive** [comment]
QA ran into this during testing.

**Comment by gaktive** [comment]
Upon discussion with @sowmyav27, though it is not a regression, RKE2 GA starts with this release. 

Not sure if we can do a bare minimum here until form validation comes in; will leave for an engineer to investigate and see what's quickly doable for 2.6.5.

**Comment by catherineluse** [comment]
There's also some space under the cloud provider dropdown with some room to place a warning that an instance profile is needed. That might be easier in the short term
<img width="1282" alt="Screen Shot 2022-04-29 at 3 29 49 PM" src="https://user-images.githubusercontent.com/20599230/166076706-b878f579-5df4-4fdc-ad41-f2802ed5d9a5.png">

**Comment by markusewalker** [comment]
Verified in `v2.6.5-rc8` that this is resolved:

**ENVIRONMENT DETAILS**
- Ubuntu 18.04: Rancher HA
- Ubuntu 20.04: RKE2 Cluster (3 etcd, 2cp, 3 workers)
- Rancher version: `v2.6.5-rc8`
- Browser: Chrome
	
**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the Rancher UI in a browser.
2. Created a standard user and logged in to Rancher as that user.
3. Created an RKE2 downstream cluster with Amazon EC2.
4. In the Cluster Configuration, set the `Cloud Provider` to be `Amazon`.
5. Verified that in the `Machine Pools` that `IAM Instance Profile Names` has a red asterik indicating that it is now a mandated field.
6. Toggled the Cloud Provider to None and External and verified that the IAM Instance Profile Name is not mandated:
![May-09-2022 09-56-28](https://user-images.githubusercontent.com/52591819/167459818-dc0ee78e-e1cf-42e2-9b56-cc771c356ecc.gif)
8. Switched the Cloud Provider back to Amazon, do not fill out the IAM Instance Profile Name and attempt to create a cluster; verified it fails:
![image](https://user-images.githubusercontent.com/52591819/167459912-be1441d0-3786-42e2-a3b4-b2c484a83489.png)
