### ISSUE TITLE
Vertical Tab Border/Selection Visual Bugs

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5522]
**Describe the bug**
Seen screenshots

**To Reproduce**
- Visit Create RKE2 Cluster PAge

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/18697775/160093015-a27e854d-3426-465e-8b5f-ebbbb3595ab1.png)

Now
![image](https://user-images.githubusercontent.com/18697775/160093280-81f67239-8913-46b2-8e02-7920539921b3.png)

Additionally the horizontal tabs do look different with their bounding border, but I don't think this is buggy

![image](https://user-images.githubusercontent.com/18697775/160093427-fdd21b26-bdb7-4fba-bebf-2c110976fe7c.png)

**Comment by markusewalker** [comment]
Verified the visual border discrepancy is addressed in `v2.6-head` https://github.com/rancher/rancher/commit/6bb6e45fba97f58443e547e2f57d2807a424467f.

**REPRODUCED ENVIRONMENT DETAILS**
- Linode Ubuntu 20.04.4 VM - Client Machine
- Docker install
- Rancher version: `v2.6.4`

**VERIFIED ENVIRONMENT DETAILS**
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/6bb6e45fba97f58443e547e2f57d2807a424467f
- Install option: Helm Chart
- Kubernetes version: `v1.22.8`

**REPRODUCTION STEPS**
1. Setup Rancher `v2.6.4` and navigate to the Rancher UI in a browser.
2. Navigate to top-left dropdown menu > Cluster Management.
3. Click the `Create` button in the top right corner. Once done, toggle to `RKE2/K3s` and select Linode.
     - You may need to provide Linode API token if you have not done so already.
4. Verify that the vertical borders appear as the follows:
![image](https://user-images.githubusercontent.com/52591819/164335718-6b2636c8-8be5-46a3-bb81-0d2d4ed56325.png)

**VERIFICATION STEPS**
1. Setup Rancher `v2.6.4` and navigate to the Rancher UI in a browser.
2. Navigate to top-left dropdown menu > Cluster Management.
3. Click the `Create` button in the top right corner. Once done, toggle to `RKE2/K3s` and select Linode.
     - You may need to provide Linode API token if you have not done so already.
4. Verify that the vertical borders appear as the follows:
![image](https://user-images.githubusercontent.com/52591819/164335824-c77dfce8-1b18-4fe7-a2fb-0fc27f9f9a7d.png)
