### ISSUE TITLE
Missing warning message after adding Windows node to RKE2 cluster

### ISSUE THREAD

**Issue by PennyScissors** [rancher/dashboard#5530]
**Setup**
- Rancher version: v2.6-head (6f9c19d)
- Browser type & version: Mozilla Firefox Developer Edition version 99.0b2

**To Reproduce**
1. Deploy a RKE2 cluster with Linux nodes
2. Install rancher-monitoring and rancher-logging
3. Add Windows node to cluster

**Result**
A warning/alert message stating the app has to get upgraded to deploy on the Windows nodes is NOT present on the chart.

**Expected Result**
A warning/alert message stating the app has to get upgraded to deploy on the Windows nodes should be present on the chart.

**Context**
Needed as part of [this](https://github.com/rancher/dashboard/issues/5137) issue since the user is required to upgrade the chart in order for the monitoring/logging Windows resources to be deployed in the newly added Windows nodes.

**Comment by gaktive** [comment]
Should be a release note for 2.6.4 as we address this for 2.6.5

**Comment by slickwarren** [comment]
the user is now presented with this message (as of 2.6.5-rc6) in the UI when the user clicks the registration command in a custom cluster for rke2:
```
You are attemping to add a Windows worker node to a cluster with one or more Linux worker nodes: some installed apps may need to be upgraded or removed.
```
<img width="1063" alt="Screen Shot 2022-05-02 at 2 05 01 PM" src="https://user-images.githubusercontent.com/16691014/166327816-8713c597-fe0a-4a8c-856f-54df5f1208b0.png">

this message is cleared when the user exits that cluster's page, but persists if the user goes to a different tab in the cluster.
