### ISSUE TITLE
To add member roles for cluster using API  

### ISSUE THREAD

**Issue by gauravkcldcvr** [rancher/dashboard#5531]
**Version**
rancher version: 2.6
kubernetes version: 1.21

I want to automate adding of member roles (users) to cluster using API but can't find any API for the same when checked in https://<rancher-url>/v3. Is there any way to map roles & users from API for a cluster. 

For creating a new test user - followed the below curl request. Can we do the same map roles & users from API for an already created cluster?

```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
'https://<rancher-url>/v3/users'
```

**Comment by catherineluse** [comment]
For automation, we recommend using the Rancher 2 Terraform provider. We don't support using the Rancher API.

**Comment by nwmac** [comment]
Answer provided above - please re-open if you need more information.
