### ISSUE TITLE
[Backport v2.6.3-patch3] After login there is an error - Cannot read properties of null (reading 'startsWith') Home

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#5532]
This is a backport of https://github.com/rancher/dashboard/issues/5004 for v2.6.3-patch3.

Internal reference: SURE-3978

Issue description:
After upgrading to 2.6.3 I get an error on login, 
`Cannot read properties of null (reading 'startsWith') Home`

Business impact:
the UI is unusable in the 2.6.3 release in this case.

Troubleshooting steps:
User was notified that this can mean that one cluster you were working with is unavailable or offline at the moment ... because 2.6.x can remember your home screen as different pages/places hit the Home button there and make sure the UI comes up.

https://github.com/rancher/dashboard/issues/4967 is similar but slightly different. Google suggests this is problem with the underlying node system and not an API hiccup.

Repro steps:
Upgrade to Rancher 2.6.3 seems to be the only thing that triggers this

Workaround:
They discovered the old UI is still valid at the `/g/` suffix and they're using that at the moment (and happy to do so, love the old UI). There are some hiccups like an overlay that loads on page nav (guessing that RMC is pulling info for a new namespace) doesn't disappear and they need to manually remove it.

**Comment by Josh-Diamond** [comment]
Unable to reproduce - Requesting QA Template

What i've tried:

FIrst Attempt:
Fresh install of rancher v2.6.3
Provision a downstream cluster
Set login to route to downstream cluster
Log out, log back in
Cluster explorer page is loaded without errors - failed to reproduce

Second Attempt:
Fresh install of rancher v2.6.2
Provision a downstream cluster
Set login to route to downstream cluster
Upgrade from rancher v2.6.2 => v2.6.3
log out, log back in
cluster explorer is loaded without errors - failed to reproduce

**Comment by Josh-Diamond** [comment]
Ticket #5532 - Test Results

With Docker on single-node instance:

UNABLE TO REPRODUCE 
[attempted: `v2.6.2` => `v2.6.3`, `v2.6.2` => `v2.6.3-patch3`, `v2.6.3` => `v2.6.3-patch3`, `v2.6.3` => `v2.6.3-patch3-rc1`, `v2.6.2` => `v2.6.3-patch3-rc1`]

I was able to simulate the error by disconnecting downstream controlplane node to provide quality verification for this fix


Verified on upgrade from rancher `v2.6.2` => `v2.6.3-patch3-rc1`:
1. Fresh install of rancher `v2.6.2`
2. Provision a downstream cluster
3. Set rancher to route to downstream `Cluster Explorer` upon login
4. Disconnect controleplane node in downstream cluster
5. Upgrade rancher to `v2.6.3-patch3-rc1`
6. Login
7. Successfully routed to `Home`, no errors, downstream cluster is `unavailable`
8. Re-connect controleplane node in downstream cluster
9. Logout
10. Login
11. Verified - Successfully logged in and routed to downstream `Cluster Explorer` page
