### ISSUE TITLE
SortableTable chevron does not change direction when row is expanded

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#5533]
**Setup**
- Rancher version: v2.6-head
- Browser type & version: Firefox 98.0.2

**Describe the bug**
When the SortableTable component has expandable sub-rows the chevron button that is used to expand the row does not change direction.

**To Reproduce**
1. Install CIS benchmark
2. Run a scan and view the results
3. Expand one of the rows 

**Result**
The chevron will not update

**Expected Result**
The chevron should change direction indicating that the row is expanded

**Screenshots**

https://user-images.githubusercontent.com/40806497/160457276-b575c3b2-2310-4335-8b23-f7877c4665b0.mp4

**Additional context**

**Detailed Description**

**Context**

**Comment by MSpencer87** [comment]
_Reopened on v2.6.5-rc6_

**Steps to reproduce:**
1. Bring up HA Rancher 2.6.5-rc6
2. Install CIS Benchmark into local cluster with default settings
3. Run and view Scan with default settings
4. Click the chevron next to State once the scan completes (still in fixed position when expanded)
