### ISSUE TITLE
Find out if performance could be improved by avoiding recomputed getters in classes

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5539]
In the list views, sometimes a getter on a class model is recomputed many times unnecessarily.

I noticed this when I was looking at the cluster list view. I was logging the `machinePools` getter on the cluster class (`models/management.cattle.io.cluster.js`) and I saw that for a list of 5 clusters, the list of machine pools was logged 36 times:

```js
get machinePools() {
    const pools = this.$getters['all'](MANAGEMENT.NODE_POOL);

    console.log(pools);

    return pools.filter(x => x.spec?.clusterName === this.id);
  }
```

The list is recalculated multiple times per cluster because some values on the cluster model are self-referential. Ideally you should only have to get the node pools once per cluster, which could be the case if the `machinePools` calculation were moved into the class constructor. So I wonder if shifting some of these into a constructor on a case-by-case basis could speed things up.

I thought more research should be done to figure out if changing other recomputed getters similar to this one would improve performance in list views.

I also had questions about the way getters are called in general. The Resource class contains these getters:

```js
get '$getters'() {
    return this.$ctx.getters;
  }

  get '$rootGetters'() {
    return this.$ctx.rootGetters;
  }

  get '$dispatch'() {
    return this.$ctx.dispatch;
  }

  get '$state'() {
    return this.$ctx.state;
  }

  get '$rootState'() {
    return this.$ctx.rootState;
  }
```
I want to understand why we are always referencing the store through class models instead of taking a more direct route, and if recomputing the above getters could have an impact on performance. Because the above are recomputed every time the store is called. I want to experiment with moving the above getters into the constructor of the Resource model and see if it makes any discernible difference.

**Comment by nwmac** [comment]
Stale
