### ISSUE TITLE
Get RKE2/K3S Default Versions from new v3.Settings Endpoint

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#5545]
**Detailed Description**

 
Rancher will expose the following two new endpoints :
- `/v1/management.cattle.io.settings/rke2-default-version`
- `/v1/management.cattle.io.settings/k3s-default-version`

As the names indicate, the value will be the default version for rke2 and k3s.
We need to update Dashboard to retrieve the default versions from them. 

**Context**

Currently, the default versions for rke2 and k3s are retrieved from a channel named `default` by Dashboard. The major problems with the current implementation are: first, we can not have different default versions for different rancher versions; second, changing the value in the channel will affect all rancher 2.6.x versions. 

We want to move the logic to the backend, and it will provide us with the following benefits:
- it corrects the misusing of Channels 
- it simplifies the logic in the Dashboard 
- It provides a unified endpoint for the Dashboard to retrieve information 
- it provides us more flexibility to manage the default version. For example,  we can set/lock different default versions for different rancher versions 

Related issue in the backend: https://github.com/rancher/rancher/issues/36827

**Comment by catherineluse** [comment]
Labeling this as a release blocker because the corresponding backend ticket is a release blocker, and because Jack said it is needed to prevent this error https://github.com/rancher/rancher/issues/36827#issuecomment-1068341211

**Comment by catherineluse** [comment]
@jiaqiluo This change will affect the forms for cluster provisioning only, right? Are there any changes needed to the forms for imported clusters?

**Comment by jiaqiluo** [comment]
@catherineluse   Yes if the forms for cluster provisioning are the only place where the UI needs the default rke2/k3s versions.
 
FYI, the backend is merged and the feature is available in rancher:v2.6-head 50d85b5b1

**Comment by catherineluse** [comment]
I have to switch tasks so I don't have time to work on this, but for the next UI dev this gets assigned to, this is the specific piece of UI code that needs to be updated:

In `edit/provisioning.cattle.io.cluster`:
```js
rke2Channels: this.$store.dispatch('management/request', { url: '/v1-rke2-release/channels' }),
        k3sChannels:  this.$store.dispatch('management/request', { url: '/v1-k3s-release/channels' }),

...

      const defaultRke2 = this.rke2Channels.find(x => x.id === 'default')?.latest;
      const defaultK3s = this.k3sChannels.find(x => x.id === 'default')?.latest;
```

**Comment by markusewalker** [comment]
Verified on `v2.6.5-rc3` and `v2.6-head` https://github.com/rancher/rancher/commit/5f04f3abc36b6f8edfc38f91170cf2c3c366f72e.

**ENVIRONMENT DETAILS**
- Ubuntu 18.04.6 - HA
- Rancher version: `v2.6.5-rc3` & `v2.6-head` https://github.com/rancher/rancher/commit/5f04f3abc36b6f8edfc38f91170cf2c3c366f72e
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup and Rancher and navigated to the UI in a browser.
2. Verified that I could reach both of the endpoints:
	a. https://FQDN/v1/management.cattle.io/settings/rke2-default-version
![image](https://user-images.githubusercontent.com/52591819/165643238-b84b6744-b1f0-467b-a86b-767fe3c06b31.png)
	b. https://FQDN/v1/management.cattle.io/settings/k3s-default-version
![image](https://user-images.githubusercontent.com/52591819/165643316-dd96f3b3-dddd-4913-984a-b8f9dcc433d2.png)
3. Navigated to Rancher UI > Cluster Management > Create. Verified that the default RKE2 / K3s versions are as the above endpoints show:
![image](https://user-images.githubusercontent.com/52591819/165643337-5fab0c16-e731-4ebd-80e2-9a8ed089721c.png)
