### ISSUE TITLE
Cluster Explorer in Rancher 2.5 and 2.6 don't have 'Force Delete' option

### ISSUE THREAD

**Issue by watarumohawk** [rancher/dashboard#5549]
**Setup**
- Rancher version: 2.5 and 2.6
- Browser type & version:

**Describe the bug**

**To Reproduce**

1) Go to Workload/Deployment
2) Select a Pod and click Delete button
3) Confirm you don't see 'Force Delete' option on Cluster Explorer even though you see it on Cluster Manager.

**Result**
You can't do Force Delete pods on Cluster Explorer.

**Expected Result**

You can do Force Delete pods on both Cluster Explorer and Cluster Manager.

**Screenshots**
The screenshots were taken on Rancher 2.6.3.

![Rancher2 6 3-Cluster-Explorer](https://user-images.githubusercontent.com/4612196/160749236-fcaba1c1-c963-4720-ab0a-7c364c9d556b.png)

![Rancher2 6 3-Cluster-Manager](https://user-images.githubusercontent.com/4612196/160750020-2cb8fa72-f9fd-436f-a6bc-3adecae8b17c.png)

**Additional context**
I found the difference of 'Force Delete' option between Cluster Explorer and Cluster Manager when I investigated the issue where you have an error when you do Force Delete a pod on Cluster Manager on Rancher 2.5.9.

Internal reference: SURE-3582

![Rancher2 6 3-Cluster-Manager-error](https://user-images.githubusercontent.com/4612196/160750026-be9287b9-2a08-41e8-b48a-10eb40b323b8.png)

**Detailed Description**

**Context**

**Comment by sowmyav27** [comment]
**On 2.6head commit id: `c91dcaf6c`**

- select a pod, and click on `Delete`
<img width="376" alt="Screen Shot 2022-07-11 at 5 51 31 PM" src="https://user-images.githubusercontent.com/26032343/178384717-ad562a26-f087-45f0-a13a-c72ae6131e5d.png">

- Network Request: 
```
{gracePeriod: 0, force: true}
force: true
gracePeriod: 0
```

@Shavindra `ForceDelete` is enabled by default when you click on Delete. Whereas in the old UI/Ember UI, Force Delete is disabled when you click on Delete. Can we change it to be disabled by default when you click on Delete?

**Comment by sowmyav27** [comment]
**On 2.6ead commit id: `2508215`**

`ForceDelete` is disabled by default when user clicks on `Delete` on a Pod
<img width="435" alt="Screen Shot 2022-07-12 at 6 43 26 AM" src="https://user-images.githubusercontent.com/26032343/178504648-5c2f9f68-7be4-4528-92c1-0d7e93e279e2.png">
