### ISSUE TITLE
Determine list of labels/annotations that can't be edited in edit and implement disabled for these values

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#556]
Based on ember, we had a list of label and annotations to ignore and not allow to be edited. 

Need to confirm this list is correct and implement across all resources. 

```
export const LABEL_PREFIX_TO_IGNORE = [
  'io.cattle.lifecycle.',
  'beta.kubernetes.io/',
  'failure-domain.beta.kubernetes.io/',
  'node-role.kubernetes.io/',
  'kubernetes.io/',
  'cattle.io/',
  'authz.management.cattle.io',
  'rke.cattle.io',
  'field.cattle.io',
  'workload.user.cattle.io/',
  'k3s.io',
  'node.kubernetes.io',
];

export const ANNOTATIONS_TO_IGNORE_CONTAINS = [
  'coreos.com/',
  'cattle.io/',
  'k3s.io',
];

export const ANNOTATIONS_TO_IGNORE_PREFIX = [
  'kubernetes.io/',
  'beta.kubernetes.io/',
  'node.alpha.kubernetes.io/',
  'volumes.kubernetes.io/',
  'k3s.io',
]
```

**Comment by deniseschannon** [comment]
@vincent99's proposal:

Let's start with an almost non-existent list to begin with to see what shows up. 

For the list that we create:

- Add global lists (of regex or string matches against the key, like type-map does) of labels and (separately) annotations to be ignored
- If a key matches, that entry is not shown in the keyvalue editor, but its value is preserved
- Start with a very conservative list:
  - `[**.]cattle.io/`
- Do not do anything about making fields "read-only". We will just hide them from the keyvalue editor.
- Add more entries as needed


When needed:
- Add a way to define type-specific additional entries (e.g. for nodes, ignore label foo) to add to the list.
- Maybe very targeted read-only fields, or let you edit but show a warning that it will probably be overwritten

**Comment by deniseschannon** [comment]
Part of this already started here, but needs fuller/correct implementation: https://github.com/rancher/dashboard/blob/master/config/labels-annotations.js#L25

**Comment by codyrancher** [comment]
Here are the changes that I made:
- Replace prefix and contain lists with regex lists
- Allow each resource to override the filtering by overriding labelsToIgnoreRegexes/annotationsToIgnoreRegexes
- Hide the labels and annotations both from the view and edit of Labels and DetailTop components
- Allow users to modify filtered labels and annotations by entering them manually

This can only be validated on resources that have updated to using the Labels component. A good way to determine that is if the resource already has the vertical tabs.

**Comment by soumyalj** [comment]
Tested with master-head(master-8a60de75db5324c73535b71c087c3e4bd5f36d29-head)

Steps:

1. Created a project P1 and secret/configmap under P1.
2. From the dashboard view, edit the secret/configmap 

- The edit view still displays the cattle.io label as below:

![Screen Shot 2020-08-24 at 12 12 42 PM](https://user-images.githubusercontent.com/18536626/91086060-36637700-e603-11ea-9530-b93d51489333.png)

![Screen Shot 2020-08-24 at 12 30 51 PM](https://user-images.githubusercontent.com/18536626/91087684-b1c62800-e605-11ea-9ea8-b54a0674ac13.png)


- The cattle.io label can be deleted without a warning

**Comment by codyrancher** [comment]
Fixed issue with https://github.com/rancher/dashboard/pull/1081

**Comment by soumyalj** [comment]
Verified with master-head( master-616259e0274-head)

Steps:

1. Create a project "newproject" and namespace newns1 under the project.
2. Create configmap/secret/service/ingress under the project.

From the dashboard view, edit the configmap/secret/service/ingress

- The edit view does not display cattle.io labels and annotations (and cannot be deleted) as expected
- New labels and annotations can be added to the configmap/secret/service/ingress


![Screen Shot 2020-08-26 at 5 19 58 PM](https://user-images.githubusercontent.com/18536626/91369368-7459ca00-e7c0-11ea-9b9d-916db25598cf.png)

![Screen Shot 2020-08-26 at 5 18 32 PM](https://user-images.githubusercontent.com/18536626/91369376-791e7e00-e7c0-11ea-9866-a6bbb58b416f.png)
![Screen Shot 2020-08-26 at 5 17 10 PM](https://user-images.githubusercontent.com/18536626/91369382-7d4a9b80-e7c0-11ea-9879-4141e92a70f3.png)
