### ISSUE TITLE
Select dropdown icon not centered if missing label

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5562]
**Setup**
- Rancher version: 2.4.4
- Browser type & version: Chrome

**Describe the bug**
Select button look is different when the input has no label applied to it.

**To Reproduce**
Navigate to `/c/local/explorer/apps.deployment/create#storage`

**Result**
Select dropdown icon not centered.

**Expected Result**
Select dropdown icon should be located always in the same place regardless of the label.

**Screenshots**
![Screenshot from 2022-04-01 14-37-34](https://user-images.githubusercontent.com/5009481/161265542-cb14ec02-fcd0-44f6-bb7b-ec9d611fea35.png)

**Additional context**
This has been already tried to be fixed in [another issue](https://github.com/rancher/dashboard/pull/5071), but it generated another [type of issue](https://github.com/rancher/dashboard/pull/5246), so it has been reverted as it was not possible to reproduce it at the time.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 68c6c13
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###

Tested this issue with the following steps provided in this ticket:
1. Navigate to `/c/local/explorer/apps.deployment/create#storage`

**Result** - Pass

The select arrow is now centered correctly
![image.png](https://zube.io/files/rancher/78df0a85d18b7b79e8eae73abc0f4e10-image.png)
