### ISSUE TITLE
Node - Edit page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#557]
There should only be an edit node page, as creating nodes is separate. We should mimic this page based on the content in the Detail Node page, but during edit, you can only edit the content in these tabs: `Taints`, `Labels` and `Annotations`.

Note: We know that only some labels/annotations can be modified, but tracking how/when to disable those fields in this issue: https://github.com/rancher/dashboard/issues/508

**Comment by maggieliu** [comment]
This will need to be done as part of cluster management.

**Comment by anupama2501** [comment]
Verified on master-head 9d54b1a

- Verified only an edit page exists for the nodes
- Only the annotations, taints and labels are editable

Add:

1. Created a rke2 node driver DO cluster with 1 worker, 1 etcd, 1 cp
2. Once the cluster is up, added the following taints on the worker node and verified they are seen in the kubectl
```
Taints:             Key=bar:NoExecute
                    Key=bar:NoSchedule
                    key=bar:NoSchedule
                    Key=bar:PreferNoSchedule
```
Labels:
`Labels:         worker-label=bar    `
Annotation
`worker-annotation: bar`

Verified the same for etcd and cp as well

Custom cluster:
1. Created a custom rke2 cluster with 1 node all roles
2. Once the cluster is up, added the following taints on the node:

Taint:

`custom-taint | bar | PreferNoSchedule`


Label:

`custom-label=bar`


Annotation:

`custom-annotation: bar`

3. Verified the kubectl describe node reflect the respective values:
```
Taints:             custom-taint=bar:PreferNoSchedule
Annotations:        custom-annotation: bar
Labels:       custom-label=bar
```

Delete:
Node driver rke2:
Verified  by deleting the taint ` Key=bar:NoExecute`, label `Labels:         worker-label=bar` , annotation `worker-annotation: bar` for the worker node of the rke node driver and see that it is removed from UI as well as kubectl command



Edit:
Edited the taint `Key=bar:NoSchedule` to `Key=bar:PreferNoSchedule` and see that user is not allowed as theres another taint with the same key and values
```
Node "au-rke2-test-pool1-5dnwx" is invalid: metadata.taints[2]: Duplicate value: core.Taint{Key:"Key", Value:"bar", Effect:"PreferNoSchedule", TimeAdded:(*v1.Time)(nil)}: taints must be unique by key and effect pair
```

**Comment by anupama2501** [comment]
Re-opening this ticket as the edit option is currently not seen on the nodes of the downstream clusters from cluster explore --> nodes 
eg., rke2 node driver cluster

<img width="203" alt="Screen Shot 2021-06-23 at 2 03 54 PM" src="https://user-images.githubusercontent.com/38144301/123167786-e1171280-d42b-11eb-9a6e-57f02fe00ed3.png">

**Comment by anupama2501** [comment]
Verified on rancher master-head c1151f6

- Edit node option is working as expected
- Adding taint, label and annotation are reflected on the node.
