### ISSUE TITLE
Setting a role to default within 'New User Default'/'Cluster Creator Default'/'Project Creator Default' does not take effect upon save.

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5576]
Follow up on https://github.com/rancher/dashboard/issues/4992 from Support: although the New User Default Role Toggle does have a button, the issue here has not been fixed by the UI change in v2.6.4. 

Whilst the radio button is now selectable, setting the default value to Yes for a role, and clicking Save has no effect, and the role is not set as default.

**Comment by gaktive** [comment]
Internal reference: SURE-4235

**Comment by cnotv** [comment]
@gaktive what is the issue at the current state?
In the video the functionality was working in all the analyzed aspects: https://github.com/rancher/dashboard/pull/5374

**Comment by UberKuber** [comment]
Hi @cnotv, here's steps to reproduce the issue

1. Go to Roles
2. Edit "project-member" Role
3. Set Role as "Project Creator Default" to Yes
4. Click on Save button
5. Note that "project-member" Role has not been set as Project Creator Default

Or

1. Go to Roles
2. Edit "project-owner" Role
3. Set Role as "Project Creator Default" to No
4. Click on Save button
5. Note that "project-owner" Role is still set as Project Creator Default

**Comment by cnotv** [comment]
@UberKuber which version of Rancher are you using? I do not have these roles and i f I set an existing one, it changes:

![Screenshot from 2022-04-05 16-59-05](https://user-images.githubusercontent.com/5009481/161783708-cd43a192-24c7-47e0-8148-f84255ae90e2.png)

**Comment by axeal** [comment]
@cnotv Those are Global roles in your screenshot, the ability to set New User Default for a Global role does appear to be fixed in v2.6.4; however, attempting to set Cluster Creator Default for a Cluster role, or Project Creator Default for a Project role does not take effect (although the radio button is now selectable in v2.6.4, unlike v2.6.0 - v2.6.3).

**Comment by UberKuber** [comment]
@cnotv These
![Screenshot 2022-04-06 at 08 42 28](https://user-images.githubusercontent.com/64894244/161911661-adfd7874-9e96-4934-9e41-ebc7513fe760.png)

**Comment by cnotv** [comment]
@alex-isv in my data and payload of the PUT request, I can actually see the value to be passed.
Could you please verify if there's any issue server side?

![Screenshot from 2022-04-06 10-46-07](https://user-images.githubusercontent.com/5009481/161935078-eb210354-b286-42f9-b733-959f146da034.png)

![Screenshot from 2022-04-06 10-46-31](https://user-images.githubusercontent.com/5009481/161935072-c5b1baf7-2d1e-416d-a644-01bc2179f982.png)

**Comment by cnotv** [comment]
As indicated in https://github.com/rancher/rancher/issues/37209#issuecomment-1090496224, the key to be used is not the existing one:

> - `clusterCreatorDefault` - for roleTemplates which have a `Context` of `cluster` (i.e. for cluster roles)
> - `projectCreatorDefault` - for roleTemplates which have a `Context` of `project` (i.e. for project roles)

**Comment by richard-cox** [comment]
#5609 will resolve this issue. Note though when creating clusters or projects only the `owner` role is shown and not the other default roles (default roles are applied when those resources are created though). I've captured this in https://github.com/rancher/dashboard/issues/5634

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.6.4                                    |
| Rancher commit link       | not applicable                           |
| Installation option       | helm high availability                   |
| RKE binary version used   | v1.3.8                                   |
| If Helm Chart k8s cluster | v1.22.7                                  |
| Cert Details              | let's encrypt                            |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | not applicable                           |
| Downstream K8s version    | not applicable                           |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$OMITTED \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.4
```

## Reproduction steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> click `Users & Authentication` -> click `Roles` -> click the `Project/Namespaces` tab
3. Click the `ellipsis (three dots)` icon next to the `Display Name: Project Member Name: `project-member` role -> click `Edit Config`
4. Under the option for `Project Creator Default` select:
   - `Yes: Default role for new project creation`
5. Open network console in google chrome
6. Click `Save`
7. Observe the network traffic console, see the screen shot labeled `A1` below



## Additional Info


![001-a1-5576](https://user-images.githubusercontent.com/40877149/164955026-ad250ca4-73bc-444e-867c-a469973a02fa.png)


## RESULTS

#### :white_check_mark: Expected
`projectCreatorDefault: true`

#### :x: Actual
`projectCreatorDefault: false`


<hr>
  
## Validation Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.6.5-rc2                                |
| Rancher commit link       | not applicable                           |
| Installation option       | helm high availability                   |
| RKE binary version used   | v1.3.8                                   |
| If Helm Chart k8s cluster | v1.22.7                                  |
| Cert Details              | let's encrypt                            |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | not applicable                           |
| Downstream K8s version    | not applicable                           |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$OMITTED \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5-rc2
```

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> click `Users & Authentication` -> click `Roles` -> click the `Project/Namespaces` tab
3. Click the `ellipsis (three dots)` icon next to the `Display Name: Project Member Name: `project-member` role -> click `Edit Config`
4. Under the option for `Project Creator Default` select:
   - `Yes: Default role for new project creation`
5. Open network console in google chrome
6. Click `Save`
7. Observe the network traffic console, see the screen shot labeled `A1` below

## Additional Info

## RESULTS

#### :white_check_mark: Expected
`projectCreatorDefault: true`

#### :white_check_mark:Actual
`projectCreatorDefault: true`

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.6.4                                    |
| Rancher commit link       | not applicable                           |
| Installation option       | helm high availability                   |
| RKE binary version used   | v1.3.8                                   |
| If Helm Chart k8s cluster | v1.22.7                                  |
| Cert Details              | let's encrypt                            |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | not applicable                           |
| Downstream K8s version    | not applicable                           |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$OMITTED \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.4
```

## Reproduction steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> click `Users & Authentication` -> click `Roles` -> click the `Project/Namespaces` tab
3. Click the `ellipsis (three dots)` icon next to the `Display Name: Project Member Name: `project-member` role -> click `Edit Config`
4. Under the option for `Project Creator Default` select:
   - `Yes: Default role for new project creation`
5. Open network console in google chrome
6. Click `Save`
7. Observe the network traffic console, see the screen shot labeled `A1` below



## Additional Info


![001-a1-5576](https://user-images.githubusercontent.com/40877149/164955066-746f306c-c563-4a04-9012-7a3f9b4c1e87.png)


## RESULTS

#### :white_check_mark: Expected
`projectCreatorDefault: true`

#### :x: Actual
`projectCreatorDefault: false`


<hr>
  
## Validation Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.6.5-rc2                                |
| Rancher commit link       | not applicable                           |
| Installation option       | helm high availability                   |
| RKE binary version used   | v1.3.8                                   |
| If Helm Chart k8s cluster | v1.22.7                                  |
| Cert Details              | let's encrypt                            |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | not applicable                           |
| Downstream K8s version    | not applicable                           |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$OMITTED \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5-rc2
```

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> click `Users & Authentication` -> click `Roles` -> click the `Project/Namespaces` tab
3. Click the `ellipsis (three dots)` icon next to the `Display Name: Project Member Name: `project-member` role -> click `Edit Config`
4. Under the option for `Project Creator Default` select:
   - `Yes: Default role for new project creation`
5. Open network console in google chrome
6. Click `Save`
7. Observe the network traffic console

## Additional Info

## RESULTS

#### :white_check_mark: Expected
`projectCreatorDefault: true`

#### :white_check_mark:Actual
`projectCreatorDefault: true`
