### ISSUE TITLE
Enable source map in Nuxt/Webpack configuration for debugging

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5589]
**Detailed Description**
Enable source map in Nuxt/Webpack configuration for debugging, using `cheap-module-source-map` instead of `eval-source-map`

**Context**
In the current setup, it is not possible to debug code as the source code is not correctly pointing to the ash generated source map.

More about source map config: https://webpack.js.org/configuration/devtool/#devtool

**Comment by bmdepesa** [comment]
No validation is needed for this issue.
