### ISSUE TITLE
OPA gatekeeper: Unable to list Templates and Constraints on dashboard

### ISSUE THREAD

**Issue by prachidamle** [rancher/dashboard#559]
With the latest master-head, the dashboard view of OPA Gatekeeper is not listing any templates and constraints

1. Enable OPA Gatekeeper 
2. List the templates and constraints on UI - no data is shown
3. Using kubectl it is still possible to list the constrainttemplates installed by default

**Comment by deniseschannon** [comment]
Related: https://github.com/rancher/dashboard/issues/523

**Comment by prachidamle** [comment]
This seems to be backend-only issue. 
I tested both ways - 
1) by changing the dashboard-index on master setup to use release-2.4 UI index and 
2) changing a v2.4.2 setup to use latest UI index

master setup remains broken and v2.4.2 setup is working fine with either of the ui-index

@ibuildthecloud thinks this issue is possible due to master-head controller framework being rewritten...

**Comment by prachidamle** [comment]
This seems to be working fine with latest master-head build.

**Comment by izaac** [comment]
This looks fixed in the following versions:

- Rancher version: 
  - `master-head (05/20/2020)` b85ea695f  
  - `2.4-head (05/20/2020)` 8e20687a4 with `CATTLE_DASHBOARD_INDEX=https://releases.rancher.com/dashboard/latest/index.html`
