### ISSUE TITLE
Changing git repo config doesn't remove previous bundle

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#5591]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**
Add a gitrepo
Wait till it becomes active
navigate to config and change the config
previous bundle still exists

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by gaktive** [comment]
Closing based on age. If someone sees this issue in a more recent version, confirm how you can repro and we can look at this.
