### ISSUE TITLE
Continuous Delivery - No way to create a workspace from UI in v2.5.x

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#5594]
**Setup**
- Rancher version: `v2.5.12`  and `v2.5-head` a6aaa98
- Browser type & version: Chrome / Firefox

**Describe the bug**

Navigating to the workspaces section of Continuous Delivery there's no button for create workspace.
I can however create workspaces using `kubectl`

**To Reproduce**

- Install Rancher `v2.5.12` or latest head.
- Navigate to Dashboard and Continuous Delivery
- Select Workspaces 

**Result**

- No create workspace action available

**Expected Result**
 User can create workspaces from the UI.

**Screenshots**
![Screen Shot 2022-04-07 at 12 54 54 PM](https://user-images.githubusercontent.com/27659/162287329-4dc92054-ae96-4851-a5ee-d77932f1bded.png)

**Comment by izaac** [comment]
We need to validate an upgrade scenario:

## QA Validation


### Setup

Requires RKE1 or v3 api clusters.

1. Start with a previous version Rancher `v2.5.13`
2. Create one Fleet workspace through kubectl and call it `fleet-kubectl` (see yaml below steps)
3. Provision at least two downstream clusters (provider does not matter, but you can vary it to be sure)
4. Move one cluster to the `fleet-kubectl` workspace and leave the others in the `fleet-default`
5. Wait for clusters to reach "Active" state

### Upgrade validation

1. Upgrade to `v2.5.13-rc` or `v2.5-head`
2. Create a new workspace from the UI name it `fleet-dashboard`
3. Move all three clusters around between the three workspaces (including `fleet-default`)
4. Observe all v3 management clusters that have corresponding v1 provisioning clusters **ARE NOT** being deleted
5. Observe all clusters eventually reaching an "Active" state (you might see the following issue, but it is transient: https://github.com/rancher/rancher/issues/34937)


Extra validation if time permits.

You can create `GitRepo` CR(s) before and after upgrade, but you may have to edit them based on the workspace. It may be best to create `GitRepo` CR(s) _after_ validation as a result.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.13-rc2

The workspace create button is working and creates a new workspace, but attempting to assign a cluster to another workspace results in nothing happening when clicking the button, and an error in the console. 

![Screen Shot 2022-04-13 at 7 18 52 PM](https://user-images.githubusercontent.com/21316915/163301218-bfed94ce-32b9-4eb2-803a-46f9d5489f0f.png)

![Screen Shot 2022-04-13 at 7 18 26 PM](https://user-images.githubusercontent.com/21316915/163301215-9ed7219a-ec50-4d59-91c3-50c043c06a20.png)

**Comment by ronhorton** [comment]
**Pass** verified in `2.5.13-rc2`

1. in downstream cluster, clicked continuous delivery
2. clicked advanced > workspaces
3. clicked create and completed form 
4. fleet-test workspace created
5. also observed that a workspace created from kubectl command shows in workspace page
<img width="1637" alt="Screen Shot 2022-04-14 at 8 55 50 AM" src="https://user-images.githubusercontent.com/89212856/163395001-d29dc828-7af0-4f38-aafb-e1bb9de29ef7.png">
