### ISSUE TITLE
Unable to remove Cluster Members in the Edit Config form for an imported RKE2 cluster

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5595]
Internal reference: SURE-4249
Reported in 2.6.3

Issue description:
For an imported RKE2 cluster, it is not possible to remove Cluster Members in the Edit Config form, but only under Cluster Explorer -> RBAC -> Cluster Members, unlike other cluster types

Business impact:
Confusing for users, who can remove cluster members for other cluster types within the Cluster Management -> Edit Config view, except for imported RKE2 clusters

Repro steps:

- Provision a Rancher v2.6.3 instance
- Import an RKE2 cluster (example tried: `v1.21.10+rke2r1`)
- Click Edit Config for the RKE2 cluster after import and observe ability to add new Cluster Members, but not to remove members
- Create a custom cluster and click Edit Config for this cluster, observe ability to add and remove Clusters Members

Workaround:
Is workaround available and implemented? Yes
What is the workaround: Remove cluster members in Cluster Explorer -> RBAC -> Cluster Members

Actual behavior:
Unable to remove Cluster Members in the Edit Config form for an imported RKE2 cluster

Expected behavior:
Able to remove Cluster Members in the Edit Config form for an imported RKE2 cluster

Screenshots:
Custom cluster:

![custom.png](https://zube.io/files/rancher/f59190cc74bad990d4148ed6d8a883cb-custom.png)

RKE2 cluster:
![rke2.png](https://zube.io/files/rancher/8928b2958f811116a95a95c39ab4537c-rke2.png)

**Comment by nwmac** [comment]
@neillsom Can you investigate

**Comment by neillsom** [comment]
Unable to reproduce as of 2.6.5

**Comment by nwmac** [comment]
@neillsom Can you provide the steps you used? I was able to reproduce this by following the steps above - i.e.

Deploy an RKE2 cluster (https://docs.rke2.io/install/quickstart/)
Import this cluster into Rancher
Go to edit config for the cluster - cluster members does not have the minus button, so user can not be removed

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                     |
| ------------------------- | ---------------------------------- |
| Rancher version           | 2.6.6                              |
| Installation option       | helm                               |
| RKE binary version used   | v1.3.11                            |
| If Helm Chart k8s cluster | v1.23.6                            |
| Cert Details              | let's encrypt                      |
| Helm version              | v2.16.8-rancher1                   |
| Downstream cluster type   | not applicable                     |
| Downstream K8s version    | not applicable                     |
| Logged in user role       | administrator                      |
| Browser type              | Opera GX                           |
| Browser version           | LVL4 (core: 89.0.4447.64) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx
```

## Reproduction steps

1. Create a `standard user` with the following credentials:
   - Username: `testuser1`
2. Create a standalone RKE2 cluster
   - Followed these steps to create an RKE2
   - https://github.com/brudnak/rke2-quickstart-doc
3. Import the created RKE2 cluster into Rancher
4. Once imported, click the `hamburger menu` ==> `Cluster Management`
5. Click the `ellipsis (three dots)`icon next to the imported RKE2 cluster ==> `Edit Config` ==> click the `Member Roles` dropdown ==> `Add Member`
6. Add `testuser1` as a `Member`
7. Save the changes
8.  Click the `ellipsis (three dots)`icon next to the imported RKE2 cluster ==> `Edit Config` ==> click the `Member Roles` dropdown ==> There is no where to remove members from this section
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Expecting to be able to remove members from the `Edit Config` page from `Cluster Management`

#### :x: Actual
There is no way to remove cluster members from the `Edit Config` page from `Cluster Management`

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                     |
| ------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version           | v2.6-2587e6a79e4778cfbe41c9e5d6e9d70e2ea0754b-head                                 |
| Rancher commit link       | https://github.com/rancher/rancher/commit/2587e6a79e4778cfbe41c9e5d6e9d70e2ea0754b |
| Installation option       | helm                                                                               |
| RKE binary version used   | v1.3.11                                                                            |
| If Helm Chart k8s cluster | v1.23.6                                                                            |
| Cert Details              | let's encrypt                                                                      |
| Helm version              | v2.16.8-rancher1                                                                   |
| Downstream cluster type   | not applicable                                                                     |
| Downstream K8s version    | not applicable                                                                     |
| Logged in user role       | administrator                                                                      |
| Browser type              | Opera GX                                                                           |
| Browser version           | LVL4 (core: 89.0.4447.64) (x86_64)                                                 |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.7-rc3 \
  --set rancherImageTag=v2.6-head
```

## Validation steps

1. Create a `standard user` with the following credentials:
   - Username: `testuser1`
2. Create a standalone RKE2 cluster
   - Followed these steps to create an RKE2
   - https://github.com/brudnak/rke2-quickstart-doc
3. Import the created RKE2 cluster into Rancher
4. Once imported, click the `hamburger menu` ==> `Cluster Management`
5. Click the `ellipsis (three dots)`icon next to the imported RKE2 cluster ==> `Edit Config` ==> click the `Member Roles` dropdown ==> `Add Member`
6. Add `testuser1` as a `Member`
7. Save the changes
8.  Click the `ellipsis (three dots)`icon next to the imported RKE2 cluster ==> `Edit Config` ==> click the `Member Roles` dropdown ==> There is a `-` minus button next to the users so you can remove them ==> remove `testuser1`
9. Save the changes and confirm testuser1 was removed
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Expecting to be able to remove members from the `Edit Config` page from `Cluster Management`

#### :white_check_mark:Actual
Was to be able to remove members from the `Edit Config` page from `Cluster Management`
