### ISSUE TITLE
Azure AD: Not showing all the groups in add Cluster/Project member page

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5596]
Internal reference: SURE-4234
Reported in 2.5.11

Issue description:
A non admin user enables azure AD external authentication. They are able to see all the groups (theirs & other groups) in Authentication page where as when they try to add a Cluster/Project member, they are able to see only groups they belong to. 

Business impact:
Usability issue.

Troubleshooting steps:
Performed refresh groups

Repro steps:

- Enable external authentication (Azure AD) as per documentation
- Check the displayed groups in Authentication page as well Add Cluster/Project member page

Actual behavior:
With same user, In Authentication page, end user is able to see the all the groups (theirs & others) where as Add Cluster member Page, they are not seeing the all the groups and one see their groups.

Expected behavior:
While adding authentication, end user sees all the groups where as add Cluster member, they only see their specific groups. The behaviour should be same on all the pages; if it's an expected behaviour, then it needs to be documented clearly to eliminate the confusion.

Files, logs, traces:
```
tener.cattle.io/cn-10.0.1.172:10.0.1.172 
listener.cattle.io/cn-10.0.1.227:10.0.1.227 
listener.cattle.io/cn-10.0.2.199:10.0.2.199 
listener.cattle.io/cn-10.0.2.227:10.0.2.227 
listener.cattle.io/cn-10.0.2.64:10.0.2.64 
listener.cattle.io/cn-10.0.3.135:10.0.3.135 
listener.cattle.io/cn-10.0.3.92:10.0.3.92 
listener.cattle.io/cn-10.0.4.19:10.0.4.19 
listener.cattle.io/cn-10.0.5.144:10.0.5.144 
listener.cattle.io/cn-10.0.5.179:10.0.5.179 
listener.cattle.io/cn-10.0.5.30:10.0.5.30 
listener.cattle.io/cn-10.0.5.73:10.0.5.73 
listener.cattle.io/cn-127.0.0.1:127.0.0.1 
listener.cattle.io/cn-localhost:localhost 
listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system listener.cattle.io/hash:4a50c5dbe0a8a81a96a18a5b35bcdace5d4a21f6af2e0212421283a6cae34a2f]
2022/03/03 10:34:29 [ERROR] Unknown error: graphrbac.UsersClient#List: Failure responding to request: StatusCode=403 – Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2022-03-03T10:34:29","message":

{"lang":"en","value":"Insufficient privileges to complete the operation."}
,"requestId":"6e7614b9-fd97-47c4-a1b5-be53c40bac7c"}}]
2022/03/03 10:35:18 [ERR
```

**Comment by nwmac** [comment]
Is this a pagination issue?

**Comment by nwmac** [comment]
@mantis-toboggan-md check with @catherineluse as to whether this is one you could help out with

**Comment by catherineluse** [comment]
It's documented here https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/manage-users-and-groups#managing-members that for all SAML providers, group search is not supported while adding users to a cluster or a project, and in that form, you will only be able to see groups that you are a member of.

From "SAML provider caveats":

> SAML PROVIDER CAVEATS:
> SAML Protocol does not support search or lookup for users or groups. Therefore, there is no validation on users or groups when adding them to Rancher.
> When adding users, the exact user IDs (i.e. UID Field) must be entered correctly. As you type the user ID, there will be no search for other user IDs that may match.
> When adding groups, you must select the group from the drop-down that is next to the text box. Rancher assumes that any input from the text box is a user.
> The group drop-down shows only the groups that you are a member of. You will not be able to add groups that you are not a member of.

We should ask Team 1 about why we don't already allow users to see groups they are not a member of.

**Comment by gaktive** [comment]
We're having the original reporter check if this is still a problem if they've moved up to 2.7.x since the behaviour pattern has changed per backend.

**Comment by gaktive** [comment]
Original reported indicated that this resolved itself so closing this.
