### ISSUE TITLE
Dashboard does not support multiple ldap servers as a comma separated list

### ISSUE THREAD

**Issue by mayrstefan** [rancher/dashboard#5605]
**Setup**
- Rancher version: 2.6.4
- Browser type & version: all

**Describe the bug**
In the old rancher/ui ist was possible to configure multiple ldap servers as a comma-separated list in the hostname field. This is no more supported by the new dashboard: instead of splitting this string into a list of servers it sends it as a single hostname to the API endpoint.
If multiple servers are configured with the old UI the new dashboard only shows the first server.

**To Reproduce**
Configure a ldap server as an auth provider with hostname 'localhost,localhost' and look into the browser development tools.

**Result**
We see Servers as `[ "localhost,localhost" ]`

**Expected Result**
This should be an array: `[ "localhost", "localhost" ]`

**Context**
https://github.com/rancher/rancher/issues/25557
With Rancher 2.5 the UI did the right thing but multiple servers were not supported in the ldap implementation. For Rancher 2.6 I added a pull request to support multiple ldap servers but now the dashboard does not support that.

**Comment by gaktive** [comment]
Reading through linked PRs, https://github.com/rancher/dashboard/pull/5606 should take care of this but it's blocked on https://github.com/rancher/rancher/pull/37215

**Comment by gaktive** [comment]
Backend PR merged now so we can work on this.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component                 | Version / Type   |
| ------------------------- | ---------------- |
| Rancher version           | 2.6.7-rc3        |
| Installation option       | helm             |
| RKE binary version used   | 1.3.11           |
| If Helm Chart k8s cluster | v1.23.6          |
| Cert Details              | let's encrypt    |
| Helm version              | v2.16.8-rancher2 |
| Downstream cluster type   | not applicable   |
| Downstream K8s version    | not applicable   |
| Logged in user role       | administrator    |
| Browser type              | google chrome    |
| Browser version           | 103.0.5060.134   |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.7-rc3
```

## Validation steps

1. Setup OpenLDAP via the UI
2. Setup Active Directory LDAP using the API
   - Using Postman
   - Make a `POST` request to the following endpoint
   - `/v3/activeDirectoryConfigs/activedirectory?action=testAndApply` 
3. Log out of Rancher
4. Ensure that you are able to login via both OpenLDAP and Active Directory successfully
  
## Additional Info
![Screen Shot 2022-07-19 at 11 12 51 PM](https://user-images.githubusercontent.com/40877149/179909857-caeb7996-cfd5-499d-88fa-1974623d2fee.png)

## RESULTS

#### :white_check_mark: Expected
Login using either LDAP provider 

#### :white_check_mark:Actual
Login using either LDAP provider

**Comment by wichitalineman** [comment]
@brudnak 

I am trying to test out this update. Do you have an example of the body used when configuring LDAP through Postman?

**Comment by brudnak** [comment]
> @brudnak
> 
> I am trying to test out this update. Do you have an example of the body used when configuring LDAP through Postman?

Hi @wichitalineman 👋 

I don't have a body example readily available. My best suggestion would be to spin up a docker install Rancher server using this two step quick start https://rancher.com/quick-start. Then enable LDAP auth via the Rancher UI with the browser developer tools opened to the network tab and grab the body from there
