### ISSUE TITLE
Dashboard version/tag should be available on dashboard UI somewhere

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#561]
There is no information of version/tag shown on dashboard UI.
Can we show at least commit id ?

**Comment by vincent99** [comment]
Need settings api

**Comment by deniseschannon** [comment]
The setting is now available per @ibuildthecloud.

**Comment by deniseschannon** [comment]
Can this be tested with the alpha1 build?

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 8d9cedd` and `rancher\rancher:v2.5.0-alpha1`

Commit ID is available in dashboard:
<img width="516" alt="Screen Shot 2020-08-31 at 10 28 03 AM" src="https://user-images.githubusercontent.com/57409052/91748535-f6f1d900-eb74-11ea-8d7d-8d589c6f399f.png">
<img width="265" alt="Screen Shot 2020-08-31 at 10 43 22 AM" src="https://user-images.githubusercontent.com/57409052/91749754-d296fc00-eb76-11ea-92f6-7568fa98e66d.png">
