### ISSUE TITLE
Allow to create unit tests for TS components

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5610]
**Setup**
- Rancher version: 2.6.4
- Browser type & version: Not relevant

**Describe the bug**
It is not possible to create unit tests with Jest for components using TS or importing other components using TS as code.

**To Reproduce**
 - Create test for one of these components: Banner, AsyncButton, RoleDetailEdit
 - Run the test

**Result**
Tests will return error: ` TypeError: Cannot read property 'extend' of undefined`

**Expected Result**
Tests for TS code type can be created without issues.

**Screenshots**

<img width="516" alt="Screenshot 2022-04-11 at 14 57 47" src="https://user-images.githubusercontent.com/5009481/162744225-9747754e-cc80-48c8-90dd-88c69516f71d.png">

**Additional context**
New instances of Nuxt/Vue2 with TS do not break Jest unit tests.

**Comment by gaktive** [comment]
@cnotv since QA or users wouldn't have to touch this, is there anything to test here? If not, then we can likely close this but if validation is needed, we should have one of the UI engineers quickly test this if it wasn't done as part of the PR review.

**Comment by samjustus** [comment]
@cnotv - can you please advise if there is any validation needed? If so, please outline what you'd like us to check

**Comment by cnotv** [comment]
@samjustus not really, it's more about be able to have tests for components which have TS, e.g. [this Drone build](https://drone-pr.rancher.io/rancher/dashboard/5846/1/2) line 86 (no line anchors sorry) testing the [Banner component](https://github.com/rancher/dashboard/blob/master/pkg/rancher-components/src/components/Banner/Banner.vue).

**Comment by sowmyav27** [comment]
closing based on https://github.com/rancher/dashboard/issues/5610#issuecomment-1176638805
