### ISSUE TITLE
Remove existing design-system folder

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5613]
**Detailed Description**
The `design-system` path is not required and should be removed.

**Context**
We should remove this folders as the styleguide is replaced by Storybook.

<img width="867" alt="Screenshot 2022-04-11 at 15 13 22" src="https://user-images.githubusercontent.com/5009481/162751727-ecf27129-9042-442b-9401-d38329e5f891.png">
<img width="1897" alt="Screenshot 2022-04-11 at 15 35 59" src="https://user-images.githubusercontent.com/5009481/162751738-86ae3096-c5f8-4b7c-903e-afd8f664f2ea.png">

**Comment by nwmac** [comment]
@cnotv These pages will be removed as part of the plugins work - they should no longer be needed and should be part of Storybook

**Comment by cnotv** [comment]
@neillsom that was the original description :)
I rephrase it again.

**Comment by nwmac** [comment]
@richard-cox I think I removed this with the plugins stuff - in which case we can close when we switch over.
