### ISSUE TITLE
Rancher Dashboard UI - Auth Provider Page - When selecting "Github", a blank page displays with no instructions

### ISSUE THREAD

**Issue by brandonsuse** [rancher/dashboard#5615]
**Setup**
- Rancher version: 2.6-head 15b8f2c
- Browser type & version: Chrome Browser (Version 99.0.4844.83)

**Describe the bug**
When you click inside of the external auth provider "Github" you get a blank page

**To Reproduce**
1. Sign into Rancher on a Node which has a RKE1 cluster 
2. On the top-right menu, click the "Users and Authentication" option
3. Select the "Auth Provider" option.
4. Click the "Github" Authentication Provider option on the screen

**Result**
The screen displays as blank and you DO NOT get any instructions for setting up Github as your external authentication provider.

**Expected Result**
You should see instructions display on the screen for setting up your github external authentication.

**Screenshots**
<img width="954" alt="image" src="https://user-images.githubusercontent.com/100438467/162770406-15ba4807-ce0a-4a4e-b0cb-53deb982142f.png">

**Additional Notes**
Attached is also a screenshot of the console logs once on that page for Github External Auth provider.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/100438467/162770742-d493bb29-8848-47b1-a0a3-3ce6a3c21e29.png">

**Comment by KevinJoiner** [comment]
# :white_check_mark: Dev-Validate PASS <br>
**Unable to reproduce on version 15b8f2c0178956e5507f65dedf82256a3ed1a05a**

## Reproduction Steps:
| Image Name | Image Tag | Image Digest | Reproducible |
|--------------|-----------|--------------|----|
| rancher/rancher | v2.6-15b8f2c0178956e5507f65dedf82256a3ed1a05a-head | d2fc9edd2c4e4664399173f45696a1caec50599c83b179274e185c996c4ea5b5 | No |
| rancher/rancher | v2.6.5-rc1 | 2104597db4425aaf088f30000b84a413fed4b6850dcdfa793a88a5c8eb95ad7a | Yes |


- Start a new instance of rancher ` docker run -d --restart=unless-stopped -p 80:80 -p 8443:443 --privileged rancher/rancher:v2.6.5-rc1`
- Select the *Hamburger Menu* in the top left corner and navigate to 'Users & Authentication' -> 'Auth Providers'
- Select 'GitHub'
- Observe that no instructions are displayed
![5615-image1](https://user-images.githubusercontent.com/10265309/164728514-5f515668-2fe9-4af0-9ea4-51aca8a3d06c.png)
## Validation Steps:
| Image Name | Image Tag | Image Digest |
|--------------|-----------|--------------|
| rancher/rancher | 	v2.6-a478def06ee49ff6f36c37c0444c550ef82a9c67-head | 80b22110549a3ec4c7e2377c9cac2f71a31677baa73c32c434205a76601d4396 |
- Start a new instance of rancher `docker run -d --restart=unless-stopped -p 80:80 -p 8443:443 --privileged rancher/rancher:v2.6-head`
- Select the *Hamburger Menu* in the top left corner and navigate to 'Users & Authentication' -> 'Auth Providers'
- Select 'GitHub'
- Observe that instructions are displayed
 
![5615-image2](https://user-images.githubusercontent.com/10265309/164728628-3c064204-19fd-46dd-b2fe-289fb3c8de47.png)

## Validation Status: <span style="color:green">PASS</span>
@sowmyav27
