### ISSUE TITLE
Deleting a Project should allow the user to delete the namespaces in it

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5624]
Internal Reference: SURE-4313

When deleting a project, in the confirmation dialog, we should have a checkbox that allows the user to choose to delete all of the namespaces in the project - the list of namespaces should be shown.

We should include a suitable warning message.

**Comment by jameson-mcghee** [comment]
@nwmac, I am observing some weird behavior with this, and I am going to be setting its state to Reopened.

When I delete both a Project and its Namespaces, the namespaces will temporarily show up in a terminating state in the "Not in a Project" project, and then they will go away. However they will pop up randomly in that project over and over again.
![image.png](https://zube.io/files/rancher/0ffde3e5462b6e0a39e8dd6731a5322b-image.png)

I noticed that I can easily delete a project and its namespaces, but if I choose to delete the project and not its namespaces, the Deleting button will just spin and never seem to complete/go away and the Project/namespaces are never deleted.
![image.png](https://zube.io/files/rancher/1c4553dfdce64a582486908510916876-image.png)

In a similar fashion, I am also unable to delete projects that do not have namespaces.
![image.png](https://zube.io/files/rancher/d69c98f9ecf0a655a0b0bd186a851a0d-image.png)
cc @sowmyav27

**Comment by nwmac** [comment]
Main problem fixed by https://github.com/rancher/dashboard/pull/6456

Can not reproduce phantom resource issue - this is possibly backend - suggest we look at that for 2.7.0 if we can reliably reproduce it.

**Comment by jameson-mcghee** [comment]
This feature appears to be working as designed, and all issues related to this ticket have been resolved. Therefore I am closing this ticket.

2.6.5:
![image.png](https://zube.io/files/rancher/254947456bf70b210b37e828d274a108-image.png)

2.6-head:
![image.png](https://zube.io/files/rancher/cd36d33c99b6f72b2af50bb43e99ded4-image.png)
