### ISSUE TITLE
Project filtering does not show empty projects

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5626]
Internal Reference: SURE-4312

- Create a new Project called 'empty' - don't add any namespaces.
- In the project list you will see the project.
- In the filter box, type 'empty' - the list will be empty and does not show the project, even though it matches the filter text.

![image](https://user-images.githubusercontent.com/1955897/162939365-d551ddf0-36fb-4e1a-9bee-0207b7ba44a3.png)

without filter:

![image](https://user-images.githubusercontent.com/1955897/162939443-e8ef56a3-5c17-4abd-90a6-e7134a831e5e.png)

**Comment by KevinJoiner** [comment]
✅  Passed Dev-Validate

| Image Name | Image Tag | Image Digest |
|--------------|-----------|--------------|
| rancher/rancher | v2.6.3 | f411ee37efa38d7891c11ecdd5c60ca73eb03dcd32296678af808f6b4ecccfff |

Reproduction Steps:
- run rancher version v2.6.3 `docker run -d --restart=unless-stopped -p 80:80 -p 8443:443 --privileged rancher/rancher:v2.6.3`
- provision a new downstream cluster (digital ocean droplet)
- Create a project named "empty" without any namespaces
- filter search for the name empty
- observe that no projects are shown
![v2.6.3-no-filter](https://user-images.githubusercontent.com/10265309/164549941-57044423-0106-461b-b371-21ad82667cc1.png)
![v2.6.3-filter](https://user-images.githubusercontent.com/10265309/164549953-3794cb29-3f50-4f11-a91a-e42c15e4aa0b.png)

Validation Steps:
- run rancher version v2.6-head `docker run -d --restart=unless-stopped -p 80:80 -p 8443:443 --privileged rancher/rancher:v2.6-head`
    - Image Digest: df15cf3e3c93329658cdfde7ebf3b5dc3c8f20a22ad85f3621d189890402b95a
    - Version: v2.6-6739a84ede27905dfcccbc9675c875d1752d438a-head
- provision a new downstream cluster (digital ocean droplet)
- Create a project named "empty" without any namespaces
- filter search for the name empty
- observe that created project is shown
![v2.6-head-no-filter](https://user-images.githubusercontent.com/10265309/164549991-92c2080b-165c-4b93-9f44-a48a37d14ebe.png)
![v2.6-head-filter](https://user-images.githubusercontent.com/10265309/164550003-5b1a36ba-1dc2-42e4-bccc-0e5844110d47.png)
 
Validation Status: Pass
@sowmyav27
