### ISSUE TITLE
Copying a Kubeconfig file should give a visual indication of success

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5627]
Internal reference: SURE-4246

When using the copy kubeconfig button, visual feedback should be given to indicate that the config has been copied to the clipboard.

![image](https://user-images.githubusercontent.com/1955897/162941015-0d796308-9943-4ddd-92be-6cd50c7a2780.png)

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/7a88105e02d8b779a486a544cc36b599b498d458.

**ENVIRONMENT DETAILS**
- Ubuntu 20.04
- Docker Install: 20.10
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/7a88105e02d8b779a486a544cc36b599b498d458 -> Verified Version

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher `v2.6-head` and navigate to Rancher UI home page > click local cluster.
2. In the top-right corner, click the clipboard icon; verified that there is now a green checkmark that indicates it was successful:
![Apr-22-2022 09-37-08](https://user-images.githubusercontent.com/52591819/164757569-bb4b9dc1-8b1e-4c48-85fd-b6ec55f15a94.gif)
