### ISSUE TITLE
v2.6.5 Release Task - Review the "What's New?" to be displayed with Product

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/dashboard#5638]
**v2.6.5 UI Release Task**
This is a UI release task for the v2.6.5 release (https://github.com/rancher/rancher/issues/37315).

- [] Please follow-up with @cloudnautique to confirm what his team would like displayed in the "What's New?" section of the app for this milestone.

**Comment by gaktive** [comment]
@Jono-SUSE-Rancher since this task is a copy/paste, with Bill gone, should I check with @deniseschannon again or @wjimenez5271?

**Comment by Jono-SUSE-Rancher** [comment]
Yes. :)
I mean, I would check with both of them and see what their input is.

**Comment by gaktive** [comment]
Initial list from @wjimenez5271:
> 1. RKE2 Provisioning GA - Provision RKE2 clusters from Rancher using our newest Kubernetes distro.
> 2. Enhanced Windows Support - Windows support for RKE2 is now GA along with a vSphere driver for windows.
> 3. Project Monitoring V2 - Isolate metrics data between teams in the same cluster using Rancher projects.

Checking with @agracey if there's anything tied to Rancher on Z to mention

**Comment by gaktive** [comment]
Initial PR: https://github.com/rancher/dashboard/pull/5741

**Comment by sowmyav27** [comment]
**On 2.6head commit `311f4623`**

```
New in 2.6.5
NeuVector Integration
Access NeuVector directly from the Rancher UI.
RKE2 Provisioning GA
Provision RKE2 clusters from Rancher using our newest Kubernetes distro.
Enhanced Windows Support
Windows support for RKE2 is now GA along with a vSphere driver for Windows.
Prometheus Federator
Isolate metrics data between teams in the same cluster using Rancher projects.

```
