### ISSUE TITLE
Order of roles shown when creating a user is incorrect

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5648]
![image](https://user-images.githubusercontent.com/18697775/163448138-b4e57604-c7ea-4d24-a148-6e00eee38658.png)

This is a regression, it should be Admin, Restricted Admin, Standard User, User-Base

**Comment by jordojordo** [comment]
@richard-cox is this still a relevant issue? I've checked on `v2.6-head` and I am seeing the list of users show up as:

![permissions](https://user-images.githubusercontent.com/40806497/166474650-67a70709-7ad2-4021-b0cf-c699c02a483e.png)

**Comment by richard-cox** [comment]
@jordojordo I see the correct version in a newer rancher as well (68eb5d1). It might be worth just double checking if we sort entries in each of those cards (global permissions, built-in and custom). Maybe the backend was broken and fixed, or something was changed our end, for either case it would be good to ensure we don't regress again.

**Comment by jordojordo** [comment]
@richard-cox I think the code looks good, it's very confusing how the global permissions were out of order considering they're fixed.
Since there doesn't seem to be a lasting issue, would you be opposed to closing this?

**Comment by richard-cox** [comment]
Let's keep the usual flow, move it over `to test`

**Comment by sowmyav27** [comment]
**On 2.6head commit id: `79a3bcb`**

Order of roles is as expected
<img width="801" alt="Screen Shot 2022-06-03 at 2 17 53 PM" src="https://user-images.githubusercontent.com/26032343/171954308-50e45cba-e338-49c2-b462-4da2589daaee.png">
