### ISSUE TITLE
Validate Helm Install instructions and bootstrapPassword

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5649]
- Ensure that when installing with helm manually specifying a `bootstrapPassword` of `admin` leads to a smooth log in process
  - This is what our docs suggest it to be
- The output of the helm install process suggests using a `setup` arg with the bootstrap password. Validate that using the URL leads to a smooth log in process 
  - `echo https://<rancher url>/dashboard/?setup=$(kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}')`

**Comment by nwmac** [comment]
@richard-cox Can we bump this to 2.7?

**Comment by richard-cox** [comment]
@nwmac Bumped. I think there is a bug here (on one install i needed to click through some partial setup screens to complete the process) but it's not blocking anything and there's been no reports of users having issues.

**Comment by catherineluse** [comment]
Are the partial setup screens still occurring in v2.7.x? I have only seen a smooth login process, with the exception of these two issues: https://github.com/rancher/rancher/issues/37531 and https://github.com/rancher/dashboard/issues/3750.

**Comment by richard-cox** [comment]
I've seen this happen a few releases ago, specifically setting the bootstrap password to `admin` (there's a path through code to try to optimise this workload which may be broken)

**Comment by gaktive** [comment]
We should repro this with the scenario of password `admin` to confirm what's going on. The easiest option would be to document this in the bootstrap docs but for the UI, we should look at providing a better response.

**Comment by gaktive** [comment]
@richard-cox is this still relevant? I know some bootstrap behaviour changed in the 2.7.x lifespan.

**Comment by richard-cox** [comment]
Neil and I saw this in someone else's live demo yesterday, so i think we can now consider it a bug (validation would provide exact bug details)

**Comment by torchiaf** [comment]
Below the login workflows for each type of `bootstrapPassword` in helm installation:

### 1. `bootstrapPassword` = 'admin' ###
  ```
  helm install rancher rancher-latest/rancher \
    --namespace cattle-system \
    --set hostname=rancher-domain.sslip.io \
    --set replicas=1 \
    --set bootstrapPassword=admin
  ```

  -  https://rancher-domain.sslip.io
  
    Change Password page -> Add `admin` password -> Change password/Get auto-generated password -> login.

    
![admin-not-in-url](https://github.com/rancher/dashboard/assets/26394656/cb75b5c7-675e-4ec0-8ee7-211e23e68666)

  - https://rancher-domain.sslip.io/dashboard/?setup=admin

    Change Password page -> Change password/Get auto-generated password -> login.
    
    
![admin-in-url](https://github.com/rancher/dashboard/assets/26394656/3d20e28d-41cf-47f2-b33e-536f739baf95)


### 2. `bootstrapPassword` = 'random-password' ###

  ```
  helm install rancher rancher-latest/rancher \
    --namespace cattle-system \
    --set hostname=rancher-domain.sslip.io \
    --set replicas=1 \
    --set bootstrapPassword=random-password
  ```

  -   https://rancher-domain.sslip.io
   
    Add `random-password` password -> login.
    
![not-admin-password-not-in-url](https://github.com/rancher/dashboard/assets/26394656/99180847-3aa0-4cd2-90cc-b7f48eb57eb2)

  -   https://rancher-domain.sslip.io/dashboard/?setup=random-password
   
    Click continue -> login.
    
    
![not-admin-password-in-url](https://github.com/rancher/dashboard/assets/26394656/5367a1cf-ab61-4aeb-8eb3-699afa16adcc)

### 3. `bootstrapPassword` is empty ###

  ```
  helm install rancher rancher-latest/rancher \
    --namespace cattle-system \
    --set hostname=rancher-domain.sslip.io \
    --set replicas=1
  ```

  -   https://rancher-domain.sslip.io
   
    Add `random-password` password -> Change Password page -> Create new password/ Get auto-generated password -> login.
    
    
![no-password-not-in-url](https://github.com/rancher/dashboard/assets/26394656/40bed0bb-ee04-4e2a-a8d4-a0a3c82d8262)

  -   https://rancher-domain.sslip.io/dashboard/?setup=lz74ns475jtfwgx94n7rqmstwxrzlg8bd247xtt2gpq9hrnhnzf54f
   
    Change Password page -> Create new password/ Get auto-generated password -> login.

![no-password-paa-in-url](https://github.com/rancher/dashboard/assets/26394656/962f50f2-affc-4393-8614-610583804fb0)

**Comment by torchiaf** [comment]
For option 1 & 3 I managed to replicate a bug that rarely occurs.

### Step to reproduce: ###

- Install a fresh Rancher instance
- Go to https://rancher-domain.sslip.io/dashboard/?setup=your-generated-token
- Click 'Continue'

### Result ###

The user is redirected to the first login dialog again:

![not-admin-password-not-in-url](https://github.com/rancher/dashboard/assets/26394656/21281b7a-60f7-4825-9892-d2a27b5be984)


### Expected result ###

The user should be logged and should be redirected to the dashboard home

### QA notes ###
 
 This is very hard to replicate, so I would mark this issue with `status/dev-validate` label.
