### ISSUE TITLE
[Rancher v2.6.4] Cluster Management page displays incorrect cluster count due to Harvester onboarding

### ISSUE THREAD

**Issue by frank-at-suse** [rancher/dashboard#5650]
**Setup**
- Rancher version: 2.6.4  (also present in 2.6.5-rc1)
- Browser type & version: Edge 100.0.1185.39

**Describe the bug**
On-boarding a Harvester cluster causes the cluster count in Clusters & Mgmt Clusters to increment by 1 even though Harvester cluster is not displayed or able to be managed

**To Reproduce**
Onboard Harvester cluster via Virtualization Management 

**Expected Result**
Cluster count in left pane of Cluster Management page should reflect the number of downstream clusters the user is able to manage to avoid confusion

**Comment by richard-cox** [comment]
backend input no happening, closing
