### ISSUE TITLE
[RKE2][S3 Snapshot] Provide error message when S3 authentication fails

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/dashboard#5651]
**Setup**
- Rancher version: v2.6-head 32c8761
- Browser type & version: Chrome Build 100.0.4896.88 

**Describe the bug**

- When S3 authentication fails when taking snapshot, there is no error message and S3 snapshot shows as active with 0 MiB for file size.
![image](https://user-images.githubusercontent.com/97477402/163464424-5e741286-714d-4fc4-96ed-397540073c18.png)

**To Reproduce**

1. Provision RKE2 node driver cluster
2. Under `Cluster Configuration` and `etcd`, enable `Backup Snapshots to S3` option
3. Enter S3 Bucket information (Enter incorrect Authentication or `None` to a private bucket)
4. Take snapshot after cluster provisions

**Result**
No files are uploaded to S3 bucket but UI shows S3 snapshots as active and also with file size 0 MiB

**Expected Result**

There should be some error to notify the user that Authentication failed

**Comment by Oats87** [comment]
Whatever is displayed on the left should probably reflect the `etcdsnapshots` object `.snapshotFile.status` field, as that is going to be the most accurate representation of the actual state of the snapshot.

There is also a `.snapshotFile.message` field that can be displayed that would say why the snapshot is in a status other than "successful"

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 7db4fe4
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver

----------

### Testing: ###

Tested this issue with the following steps:
1. Provision RKE2 node driver cluster
2. Under `Cluster Configuration` and `etcd`, enable `Backup Snapshots to S3` option
3. Enter S3 Bucket information (Enter incorrect Authentication or `None` to a private bucket)
4. Take snapshot after cluster provisions

**Result** - Pass

Rancher now shows a `404` Error when authentication fails
![image.png](https://zube.io/files/rancher/2a15da901b3b80f93353bd4986ef15ec-image.png)

This message is okay for now `404 not found` is what rke2 gets when it tries to upload the snapshot.
A new ticket, [37498](https://github.com/rancher/rancher/issues/37498) was created for an enhancement request to enhance the error message given in a future release.
