### ISSUE TITLE
Block upgrading partner chart to a feature chart repo

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5655]
Setup

Rancher version: 2.6-head 56f0c2d
Browser type & version: Chrome

**Describe the bug**
When we install an app from a partner chart repo, we can upgrade the same chart via feature charts if the chart also exists in the feature charts default repo.

**To Reproduce**
1. Create a cluster 3 worker, 1 etcd, 1cp [required spec as I tested with istio app]
2. From the cluster's apps & market >> Repositories >> create a repo [ I forked feature charts to my repositories. If needed can make use of this https://github.com/anupama2501/charts ]
3. Select the option Git repository containing Helm chart or cluster template definitions, Git repo URL :https://github.com/anupama2501/charts and branch:`dev-v2.6` , name:test
4. Once the repo is active, navigate to charts and from the chart repos drop down select test
5. Install monitoring any version and install istio version 1.9.6
6. Once the app is installed, from the charts page select `Rancher` repo from the drop down
7. Navigate to istio chart and select the version `100.2.0+up1.12.6` which is not present in the test repo versions of istio.

**Result**
Chart upgrades successfully and partner chart is upgraded to feature chart

**Expected Result**
Disallowing the upgrade of partner charts to feature charts

**Comment by gaktive** [comment]
As a note to docs, the release note label here is if we can't get this in for 2.6.5.

**Comment by gaktive** [comment]
Need to push to 2.6.6. Still need to document this for 2.6.5.
