### ISSUE TITLE
Rancher RKE2 vSphere node driver UI issues when editing memory and disk size.

### ISSUE THREAD

**Issue by phillipsj** [rancher/dashboard#5658]
**Setup**
- Rancher version: v2.6-6c12bee2d0bee16a2854df5471aaa0cdee5b9bf1-head
- Browser type & version: Edge 100.0.1185.39
![rancher-version](https://user-images.githubusercontent.com/1568133/163865595-9c19cc11-59ac-445d-9787-9a53220cd474.png)

**Describe the bug**

When editing the memory or disk size in the vSphere node driver template for RKE2 provisioning the UI doesn't edit the value correctly and ends up clearing out the value. When the values become empty, then an error is logged in the JS console.

**To Reproduce**

1. Create a cluster in cluster management
2. Enable RKE2/k3s provisioning
3. Select vSphere node driver
4. Edit the node pool template by changing the 4 in memory to an 8 and increase disk size from 20000 to 30000 by just editing the 2 to a 3.

**Result**

Editing just one number causes the cursor to jump around or completely clears the text box.

**Expected Result**

The expectation is that I can edit just a single value without having to re-enter the whole value. 

**Screenshots**

![default-value-vsphere-node-driver](https://user-images.githubusercontent.com/1568133/163865576-2b2e1727-39bd-4c34-b8ec-e08dbb1663c4.png)
![just-changing-4-to-8-vsphere-node-driver](https://user-images.githubusercontent.com/1568133/163865584-0c9da894-0770-4678-bb18-f3aafc62646c.png)
![empty-memory-throw-error-vsphere-node-driver](https://user-images.githubusercontent.com/1568133/163865589-7cb39ed4-348c-482f-b9f3-2fda6a89018d.png)

**Comment by gaktive** [comment]
Note that this was spotted with RKE2.

**Comment by cnotv** [comment]
I guess this is a possible duplication of https://zube.io/rancher/dashboard-ui/c/5210

**Comment by phillipsj** [comment]
@cnotv there is some overlap. The other issue doesn't include the error that occurs when the fields are empty and that the field clears itself. It all could be the same cause. If it's all the same cause feel free to consolidate these.

**Comment by cnotv** [comment]
The error is the same and also this is an issue with the formatting, as `096` is not a valid integer.

**Comment by gaktive** [comment]
@cnotv if this is a duplicate of https://github.com/rancher/dashboard/issues/5186 (which somehow reopened), then I can close this ticket. However, I can't tell if you tried closing the other ticket as a duplicate already since that was reopened. Based on the PR there, QA likely should be testing that.

**Comment by phillipsj** [comment]
@cnotv looks good to me and works as expected. @gaktive I will close this ticket since the other one is open and tracked.
