### ISSUE TITLE
Cannot delete project in cluster

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5660]
**Setup**
- Rancher version: 2.6-head
- Browser type & version: any

**Describe the bug**
A user (admin) cannot delete a custom (non-system) project in a given cluster

**To Reproduce**
login as admin -> create a project on local -> try to delete the project

**Result**
User cannot delete the project

**Expected Result**
A user (admin) should be able to delete a custom (non-system) project in a given cluster

**Comment by markusewalker** [comment]
**ENVIRONMENT DETAILS**
- Linode Ubuntu 20.04 VM
- Docker install: 20.10
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/a478def06ee49ff6f36c37c0444c550ef82a9c67
RKE2 version: `v1.22.8+rke2r1`

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher `v2.6-head` and navigate to Rancher UI home page > Create.
2. Toggle RKE1 to RKE2/K3s and chose Linode node driver to create a RKE2 cluster.
3. Navigate to top-left dropdown menu > Explore Cluster > local > Projects/Namespaces.
4. In the top-right corner, click Create Project, give it a name and in the bottom-right corner, click Create.
5. In the new project, create a new namespace to give some content in it:
![image](https://user-images.githubusercontent.com/52591819/164566432-f21bc20c-2a63-4c6b-ae3e-50fe819b2375.png)
6. Click the ellipses to the right of the project's row and click Delete > Delete. Verified the created `bogus` project has been deleted:
![image](https://user-images.githubusercontent.com/52591819/164566463-2da9a33d-1ec9-4e36-924c-624bd5a95142.png)
7. Navigate to top-left dropdown menu > Users & Authentication > Create. Created a new administrator and a restricted administrator.
8. Logged out, logged in as the full-access administrator and repeated steps 3-5 and received the same successful results.
9. Logged out, logged in as the restricted administrator and repeated steps 3-5, but for the RKE2 cluster created earlier. Received the same successful results.
