### ISSUE TITLE
Show error if default value for Rancher server-url is a local host IP

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5666]
**Detailed Description**
Provide insight to the user in case of communication issues with DO instance.

- Add validation to the server URL property both on the setup screen and the global settings page that lets you change it - when set to 127.0.0.1 or localhost, we show a warning banner.
- Text for banner should be: `If the Server URL is internal to the Rancher server (e.g. localhost) the downstream clusters may not be able to communicate with Rancher`

**Context**
While interacting with a cloud service, if the `server-url` is not set, requests will hang unfulfilled without a clear message, especially for beginner users.

Displaying a notice if Rancher has not a remote IP, we should inform the user of possible issue, e.g. creation of Clusters.

Configuration path: `/c/local/settings/management.cattle.io.setting`
Area: Global Settings -> Settings -> server-url

**Comment by catherineluse** [comment]
I think this is a great idea and will help many people who are trying Rancher for the first time.

Here is what should change. When you set up Rancher for the first time, you will see this screen:
![Screen Shot 2022-04-20 at 9 10 03 AM](https://user-images.githubusercontent.com/20599230/164275295-3c1990f9-755a-41c8-9a41-04ef830b6a7e.png)

Here Rancher uses whatever is in your web browser as the default value for the Rancher server URL. So if you are running Rancher on localhost, the default value can end up as `https://127.0.0.1:8005`. This does not immediately cause an error, but it should. Because if the Rancher server URL is localhost, then if you try to create a downstream cluster, the cluster will get stuck pending.

In the above screen, if the default value contains `127.0.0.1`, we should show an error that says "If the Rancher server URL is local host, Rancher will not be able to communicate with downstream Kubernetes clusters"

**Comment by richard-cox** [comment]
We would need a similar mechanism for the `server-url` setting in global settings.

That has the description below (note the incorrect product name of `Explorer`). 
```
Default Explorer install url. Must be HTTPS. All nodes in your cluster must be able to reach this.
```

So would suggest flipping the test from `If the Rancher server URL is local host, Rancher will not be able to communicate with downstream Kubernetes clusters` to `If the Rancher server URL is internal to the host the downstream clusters will not be able to communicate with Rancher`

**Comment by catherineluse** [comment]
The problem with changing the text is that people don't read. This is documented in several places as well, but a lot of times, text just doesn't register.

**Comment by catherineluse** [comment]
I'm not saying that changing the text is a bad idea, because in fact your version is more technically correct. Just that some people won't read either way

**Comment by richard-cox** [comment]
I'm only advocating a tweak to the text you suggested (to fix the direction), and that whatever we do on the setup page should also be done in the global settings page.

**Comment by nwmac** [comment]
In summary:

- Add validation to the server URL property both on the setup screen and the global settings page that lets you change it - when set to 127.0.0.1 or localhost, we show a warning banner.
- Text for banner should be: "If the Server URL is internal to the Rancher server (e.g. localhost) the downstream clusters may not be able to communicate with Rancher"

**Comment by cnotv** [comment]
As this will touch global settings, I'll proceed after https://github.com/rancher/dashboard/issues/6633 is merged, so I can simply add the setting for this.
I'll create a new validation to check if something is local, with the possibility to define `true`/`false`.

**Comment by momesgin** [comment]
As discussed with @nwmac we should not block the submission if the server url is a localhost url, we should only show a warning message. But for the below cases we'll block the submission and show an error message when the server url:

1. is not a url(we reuse the imported library `is-url` to validate this)
2. is not provided at all
3. is not https
4. has a trailing forward slash

**Comment by richard-cox** [comment]
This one should go through QA right @momesgin? Our bot should have re-opened it

**Comment by momesgin** [comment]
@richard-cox that's right, thanks! I moved it to "To Test" state as I discussed it with @gaktive

**Comment by aalves08** [comment]
Added as possible `automation-candidate`. Login part could probably be tested with a unit test... Settings page we have several e2e that we could piggy-back on.

**Comment by izaac** [comment]
The E2E implementation using fixtures was a really good call. Coverage looks good

**Comment by berkaykirtillii** [comment]
As a beginner, I run the rancher dashboard myself with yarn dev and again I run rancher with docker (that is, I gave it localhost). How can I solve this problem while working in my local? My server url is https://127.0.0.1 
![Screenshot from 2025-01-09 20-27-31](https://github.com/user-attachments/assets/8fb82dbd-7147-42ac-a660-de3fe86de9ac)
