### ISSUE TITLE
Unable to create secrets in node driver cluster

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/dashboard#5668]
**Setup**
- Rancher version: v2.6-head 228a585
- Browser type & version: Chrome 100.0.4896.88 

**Describe the bug**

User is unable to create secrets on Dashboard, but is able to create secrets through the old UI

**To Reproduce**

1. Create node driver cluster
2. Create secret

**Result**
User is unable to create a secret and the following error message is displayed
`message: "Secret in version \"v1\" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 4, error found in #10 byte of ...|:\"test123\"},\"kind\":\"|..., bigger context ...|Opaque\",\"apiVersion\":\"v1\",\"data\":{\"key1\":\"test123\"},\"kind\":\"Secret\",\"metadata\":{\"name\":\"test\",\"names|..."`
![image](https://user-images.githubusercontent.com/97477402/164278351-e63a4345-79d7-483d-959e-566817df91ab.png)

**Expected Result**

Secret should be created successfully

**Comment by aalves08** [comment]
@richard-cox checked out the branch for the Secrets issue, and had no problems in creating a Secret.

I can confirm that is working properly.

![Screenshot 2022-04-21 at 09.35.18.png](https://zube.io/files/rancher/8b1234084442cfd2a7534441cb8aa0c9-screenshot-2022-04-21-at-09-35-18.png)
![Screenshot 2022-04-21 at 09.35.26.png](https://zube.io/files/rancher/1de85cf3a898e34515a3ce3de0a96641-screenshot-2022-04-21-at-09-35-26.png)

**Comment by aalves08** [comment]
PR that fixes this issue: https://github.com/rancher/dashboard/pull/5662
