### ISSUE TITLE
Change the hardcoded AzureAD Auth Config endpoints for AzureAD auth provider

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/dashboard#5671]
### Needed for v2.6.7

This is to be coordinated with https://github.com/rancher/rancher/issues/29306.

Currently, the UI specifies the GraphEndpoint for a new AzureAD auth provider registration. Microsoft will soon retire the Azure AD Graph API endpoint in favor of the one for Microsoft Graph.

The backend will have changes to the code working with the AzureAD auth provider so that users can continue to use their Directories with Rancher's RBAC, but now via the new Microsoft Graph API.

When admins initially set up AzureAD as the external auth provider in Rancher, the UI sends to the backend an initial specification of the auth configuration. One field, in particular, specifies the GraphEndpoint that the backend later stores and uses. 
This hardcoded URL endpoint has to change in the UI.

Currently, the Global endpoint is `https://graph.windows.net/`, 
but needs to be changed to `https://graph.microsoft.com`.

The same needs to be done for the Graph API endpoint for China.

Currently, the Graph endpoint for it is `https://graph.chinacloudapi.cn/`, 
but needs to be changed to `https://microsoftgraph.chinacloudapi.cn`.

Also, for the new flow via Microsoft Graph, the default Auth Endpoint and Token Endpoint that the UI offers need to be updated.

`https://login.microsoftonline.com/{tenantID}/oauth2/authorize` is the old Auth Endpoint
`https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/authorize` is the new Auth Endpoint

`https://login.microsoftonline.com/{tenantID}/oauth2/token` is the old Token Endpoint
`https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/token` is the new Token Endpoint

#### Updated 6/16:
The same for China:
`https://login.partner.microsoftonline.cn/` is the new login endpoint (in the code known as 'endpoint')
`https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/authorize` is the new default Auth Endpoint
`https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/token` is the new default Token Endpoint

**Comment by maxsokolovsky** [comment]
Just checking, is there a reason why this one and https://github.com/rancher/dashboard/issues/5739 are labelled `Backend Blocked`? Are these indeed blocked? While the backend changes are not merged, there is a custom image `maxsokolovsky/rancher:ui` that can be used to test frontend changes.

**Comment by maxsokolovsky** [comment]
Updated the description with another requirement for default old and new Auth Endpoint and Token Endpoint. Apologies for the additional ask so late...

**Comment by niusmallnan** [comment]
@maxsokolovsky I have an Azure China account, so I tried `rancher/rancher:v2.6-0fd630dd1328233958bdef6b9f7f413eb7463005-linux-amd64` with the latest dashboard.

I think there may be some Endpoints setup issues, here are the Endpoints I found in Azure China.
<img width="841" alt="截屏2022-06-16 下午4 31 24" src="https://user-images.githubusercontent.com/998984/174031446-63574fe2-ba65-40bd-9eb4-1b742c7fcb51.png">

I also tried these custom params:
```
https://login.partner.microsoftonline.cn
https://microsoftgraph.chinacloudapi.cn
https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/token
https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/authorize
```
Then, I got this error: `server error while authenticating: authority does not have two segments`

**Comment by maxsokolovsky** [comment]
@niusmallnan, thank you very much for the note. At a minimum, we must update the endpoints for China. And will try to reproduce the last error as soon as possible.

@mantis-toboggan-md, this is my mistake, I apologize. I updated the description to fix the additional endpoints for China, which also had been updated for Microsoft Graph, which wasn't immediately evident. The documentation from Microsoft shows the new Azure AD logon endpoint, but its underlying value is the old one, for example, which is confusing.

https://docs.azure.cn/en-us/articles/guidance/developerdifferences

**Comment by maxsokolovsky** [comment]
@niusmallnan, about the last error "invalid audience": does your app have the necessary permissions? It needs application (not delegated) permissions: `Group.Read.All` and `User.Read.All`.

**Comment by niusmallnan** [comment]
This has been bugging me too, I made a configuration like this.
![image](https://user-images.githubusercontent.com/998984/174112121-d7d77cb2-a42b-4bbc-bd04-6cb5bfdf4838.png)

**Comment by mantis-toboggan-md** [comment]
No worries @maxsokolovsky, it's a quick thing to fix; PR up now

**Comment by anupama2501** [comment]
Verified the upgrade works on v2.6-head 2b1e3ee 
Fresh checks, for standard end points the graph endpoint, auth and token endpoints are updated as expected.
