### ISSUE TITLE
`addon config` form values cleared / not correctly displaying when user updates a cluster's kubernetes version

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5672]
**Setup**
- Rancher version:v2.6-head (6c12bee)
- Browser type & version: chrome 100.0.4896.88

**Describe the bug**
When a user is updating the k8s version of a cluster, if they have fields under the `addon config` section, they are cleared from the cluster and are not included in the update. 

**To Reproduce**
* in vsphere, deploy a cluster (1 etcd, cp node and 1 or more worker nodes) on 1.2x.x+rke2rx (just not the latest version so that you can update it later)
  * enable the cloud provider `vsphere`
  * enter valid credentials under `addon config` for vsphere cpi/csi charts
  * wait for the cluster to get to an active state
* once the cluster is active, update the cluster via `edit config`
  * change k8s version
  * visit the `addon config` section before updating the cluster

**Result**
the addon config does not have any/all values that are already entered by the user and used by the cluster during upgrade. 

**Expected Result**
The values should be preserved when updating the UI through the form.

**Additional context**
Updating the same field via yaml preserves the values and allows the update to complete for both the cluster and the addons (in this case, the charts for cpi/csi only properly update if the yaml is updated. The form clears the values and the upgrade will fail).

**Context**
found as a result of debugging issues from this ticket: https://github.com/rancher/rancher/issues/35474

possibly related: https://github.com/rancher/dashboard/issues/5132

**Comment by richard-cox** [comment]
There's a brief intro to addon config and how it works over in our confluence (rancher / cluster provisioning / general notes, ask for link)

**Comment by codyrancher** [comment]
From my tests it looks like it's backend. 

If all I do is refresh after the repo has been updated I see the request get made and the repo status cycles through until it gets back to active.

If you clone a repo and give it a new name and refresh the updates show up. It makes me think that the backend is caching something based on the repo name.

**Comment by codyrancher** [comment]
After digging into this one I'm not convinced this is a bug.

The Addon Config is driven by a chart/s. The charts are versioned for each kubernetes version. So what happens is if you switch the kubernetes version it  which chart questions/values are used. 

If you were to switch kubernetes versions and then switch back your addon config values will be present. 

Similarly, if you switch versions (v1), change the addon config values, switch versions (v2) again your addon values will be gone. If you then switch back to to v1 then your values will come back.

I think that this is actually reasonable behavior given the circumstance. For us to populate values between versions we'd need a way of tracking what fields are compatible. Just transferring the value if the name is the same isn't sufficient. Types could change, names could change etc.

@richard-cox I saw that you were in these files. Does the above make sense to you?

**Comment by richard-cox** [comment]
That makes sense. I wonder here if we just need to make it clearer that config is tied to addon versions, which may change given updates to kube version. That could either be a banner on screen or might be possible via a warning modal shown on changes that would clear the config (not sure we have a ux pattern for warning modals though).

**Comment by codyrancher** [comment]
@richard-cox I'm going to go ahead and add a banner in the Add-On config section. In theory this informs the user of this issue when they first set the config but it could still end up with users forgetting and making the mistake but being informed when they investigate. 

I'm personally not a big fan of confirmation modals while editing a form. Maybe in the future we can have a modal that pops up when the user tries to save which confirms that they're okay with clearing the values?

Also, I noticed that we now have 11 or 12 banners in the RKE2 provider. This is making me think that maybe we don't have the right abstraction for provisioning RKE2 clusters.

**Comment by snasovich** [comment]
@codyrancher @richard-cox , thank you for investigations on this.
While I understand the technical reason for this behavior, it sounds like a poor user experience, especially for the cases where fields don't change between add-on versions or there are only additional fields.

From what I understand per https://github.com/rancher/dashboard/pull/5775 this pop-up will show up any time you change k8s version, regardless of whether you have any impacted add-ons, which could be very annoying. On top of that, it's not like users can easily copy-paste previously entered values, so they would need to re-enter them again - and in case of vSphere there are a lot of them.

While this may be acceptable for the initial release, there is definitely a room for improvement here to carry over the values in a more seamless fashion. In cases where it cannot be done automatically (e.g. types don't match) we could present the user with a warning listing the fields that were not moved automatically and asking to correct them manually.

cc: @gaktive @nwmac

**Comment by igomez06** [comment]
**Setup:**
Rancher Version: v2.6-head commit: 5e1bfc06d6be06a91236663a154b155d14da0a8c
Kubernetes Version: RKE2 v1.22.8+rke2r1
HA Install

**Steps:**
1. Provisioned a AWS RKE2 downstream cluster version v1.21.6+rke2r1
2. Edited cluster config and added a test config  to `Add-On Config` and saved the config. I saw the expected `Add-On Configurations can vary between Kubernetes versions. Changing the Kubernetes version may reset the values below.` banner and saved the config successfully
3. When attempting to update the clusters's Kubernetes version to v1.22.9+rke2+1 and got the expected pop-up of 
![Screen Shot 2022-05-04 at 1.23.38 PM.png](https://zube.io/files/rancher/e677572982b3cf0b3e27ed520699fedd-screen-shot-2022-05-04-at-1-23-38-pm.png)

**Comment by richard-cox** [comment]
@snasovich Most config is yaml based, so the user can copy-paste their previous configuration. I'm not sure of the consequences though, or how vsphere config works. 

I've created a follow up [issue](https://github.com/rancher/dashboard/issues/5837) to improve the process. A lot of it is dependent on what add-ons are, how they work (on kube upgrade) and what confg we have available on edit.

**Comment by snasovich** [comment]
@richard-cox , thank you for taking care of it (great timing as I've had creating a follow up issue on my list of things to do for yesterday but didn't get to it).
Regarding "most config is yaml based, so the user can copy-paste their previous configuration", this doesn't seem to be the case for vSphere Cloud Provider as there are custom forms on the UI for CPI / CSI on "Add-on Config" tab with a dozen or so fields between them (don't have a setup handy where I can test it).
