### ISSUE TITLE
Unable to start Rancher locally against DO instance after GitHub auth provider enabled

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5681]
**Setup**
- Rancher version: 2.6.4
- Browser type & version: any

**Describe the bug**
Can't access to Rancher while developing if DO instance uses also GitHub authentication. 

**To Reproduce**
- Create a DO cluster
- Try to login locally to ensure everything is fine
- Add GitHub auth provider following the steps
- Logout
- Try to access to the homepage

**Result**
Rancher returns error 500 with `Maximum call stack size exceeded`.

**Expected Result**
It's possible to login with at least local users.

**Screenshots**

https://user-images.githubusercontent.com/5009481/164757234-811f2f28-e03f-4891-acec-9226e7b8df28.mov

**Additional context**
There's 2 important point to consider:
- This feature was working just fine locally, till the previous DO instance did not want to start working again ~11 days ago (20 April)
- The issue is strictly related to the login, as if I have valid cookies it does not cause any issue; I can copy the cookies and make the app work
- It is possible to access/login to the instance online with both local and GitHub user https://104.248.253.167/ so it must be related with the redirection, but again, it used to work with the same configuration

**Comment by cnotv** [comment]
Under @richard-cox suggestion, it seems to work fine using the flag `--spa` while starting the project.

**Comment by cnotv** [comment]
No, this is solved by using the `--spa` flag. I would rather take the chance ot integrate it with the `yarn dev` command, as that's the only way to start the project at the moment.

**Comment by richard-cox** [comment]
In 2.6.6 (plugin world) ssr is enabled by default, so no `--spa` is required

**Comment by cnotv** [comment]
Cant we remove it later again, just to stay safe?

**Comment by catherineluse** [comment]
I wouldn't expect the GitHub login process to go smoothly when Rancher is running on localhost due to the fact that when the GitHub auth provider was set up, the `Homepage URL` and `Authorization callback URL` were set to the Rancher server URL, not localhost. For security reasons the login process has to break if the URL doesn't match that.

**Comment by cnotv** [comment]
I make it point to localhost and that works :P

**Comment by cnotv** [comment]
In any case, we know that this scenario is probably not something realistic, which is why it has not been fixed yet. Still is an exception which should be handled in somehow and not break everything, especially since we can point exclusively to DO for development.

**Comment by catherineluse** [comment]
Ok. So the ideal error message for this should be something like "The auth provider is not configured for this Rancher server URL"?

**Comment by cnotv** [comment]
Well not really, because that's just the login page, it's not even submitting anything at all. We should be able to still login with user and password, while there there's a 500 page.
I do not recall if it's still an issue as in the video though.

**Comment by richard-cox** [comment]
Looks like the root of this issue relates to SSR which isn't supported any more. @cnotv can you try recreating the issue, and if not i'd recommend this is closed.

FWIW I often switch between GH clients configured for `localhost` and `<public rancher url>` and couldn't see an issue.

Note - There's a guide that describes (for devs) how to configure the github auth provider to support both localhost/rancher urls (currently https://github.com/rancher/dashboard/blob/master/docusaurus/docs/auth-providers.md#github, but location will move as part of https://github.com/rancher/dashboard/pull/7162)
