### ISSUE TITLE
Copying a node's external IP or internal IP does not give a visual indication of success

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#5688]
**Setup**
- Rancher version: `v2.6-head`
- Browser type & version: Chrome

**Describe the bug**

Similar to issue https://github.com/rancher/dashboard/issues/5627, when you navigate to individual nodes within your cluster, there is an option to copy either the external IP or internal IP to your clipboard. However, when you click the clipboard, there is no visual indication that this was successful.

However, if you paste onto a document or editor, then the IP appears as expected.

**To Reproduce**

1. Setup Rancher and navigate to Rancher UI > top-left dropdown menu > Explore Cluster > local > Cluster > Nodes.
2. Click any of the available nodes.
3. Click either the external IP or internal IP clipboards; you should see that the clipboard doesn't have any visual indication of success.

**Result**
Copying the clipboard does not show a green checkmark indicating that the clipboard successfully copied the IP.

**Expected Result**

Copying the clipboard for the external or internal IPs should show a green checkmark, indicating the clipboard successfully copied the IP.

**Comment by gaktive** [comment]
Need to push to 2.6.6 unless @nwmac can get this in quickly based on past efforts.

**Comment by markusewalker** [comment]
Issue is still reproducible in `v2.6` https://github.com/rancher/rancher/commit/0e2fdc8060bc74c278d7f043c7846297577fb92c.

**ENVIRONMENT**
- Rancher HA
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/0e2fdc8060bc74c278d7f043c7846297577fb92c
- Browser: Chrome

**TEST RESULT**
FAILED

**REPRODUCED STEPS**
1. Setup Rancher and navigate to UI in a browser.
2. Navigate to Cluster Explorer > local > Cluster > Nodes.
3. Click the clipboards for external and internal IP for available nodes; this is successful as shown below:
![May-20-2022 08-40-10](https://user-images.githubusercontent.com/52591819/169563921-63b07146-1ca7-47e9-bc11-9417e47c5dcd.gif)

**Comment by markusewalker** [comment]
The fix may not have been properly set at the time of testing. Verified that this is addressed in `v2.6-head` https://github.com/rancher/rancher/commit/e35d32feea3ff9511d972b87f14a4f66b194db39.

**ENVIRONMENT**

- Rancher HA
- Rancher version: v2.6-head rancher/rancher@0e2fdc8
- Browser: Chrome

**TEST RESULT**
PASSED

**VERIFIED STEPS**

1. Setup Rancher and navigate to UI in a browser.
2. Navigate to Cluster Explorer > local > Cluster > Nodes.
3. Click the clipboards for external and internal IP for available nodes; this is successful as the green checkmarks do appear.
4. Navigate to one of the nodes and click the clipboards for external and internal IP; in the image below, clicking the clipboards DOES cause the green checkmarks to appear.
