### ISSUE TITLE
Namespace - Detail

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#569]
Note: Move container default resource limit into tab and make it look similar to the layout for the edit page. Work on rancher/dashboard#568 before this one.

- [x] Tabs Update

Tab Name | Content Notes 
---|---
Container Default Resource Limit | Make the component/layout inside the tab match the Edit Namespace page
Labels | Confirm it uses the ResourceTabs component
Annotations | Confirm it uses the ResourceTabs component

@lvuch can you do a mock for this one?

**Comment by lvuch** [comment]
https://xd.adobe.com/view/16abab82-98ff-46d0-59c7-2261b36a56fb-609a/

**Comment by deniseschannon** [comment]
The label should be `milli CPUs` for CPU.
