### ISSUE TITLE
UI: Feature Request - Add Option to Enable TLS Secrets in Load Balancing Rules

### ISSUE THREAD

**Issue by ekristen** [rancher/dashboard#5690]
I think it would also be good to add an option to the UI to tell rancher to automatically create a `secretName` if one doesn’t exist or indicate this should be a TLS endpoint without having to specify a cert manually.

**Comment by catherineluse** [comment]
I think this is a duplicate of https://github.com/rancher/dashboard/issues/5714 and may be addressed by https://github.com/rancher/dashboard/pull/5856

**Comment by catherineluse** [comment]
I think it isn't fixed already because based on the comments here it looks like Bastian's PR wasn't merged https://github.com/rancher/dashboard/pull/5856

**Comment by codyrancher** [comment]
For QA. No additional changes have been made to specifically address this issue. A separate change which allowed users to enter non-existent secrets should address this issue.

**Comment by markusewalker** [comment]
> For QA. No additional changes have been made to specifically address this issue. A separate change which allowed users to enter non-existent secrets should address this issue.

@codyrancher is there a PR that we can link to this issue that involves this separate change that was made? Seeing as this is a customer reported ticket, we need to ensure that customers can reference this issue and see exactly what was fixed before performing QA work to close this out.

**Comment by codyrancher** [comment]
It was verified here https://github.com/rancher/dashboard/issues/5714#issuecomment-1150227261
It was changed here https://github.com/rancher/dashboard/pull/1882

**Comment by markusewalker** [comment]
Verified that this is addressed in `v2.6-head` https://github.com/rancher/rancher/commit/b66dd0f614f9d60ef54dfb82da12b9b8b194021b.

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/b66dd0f614f9d60ef54dfb82da12b9b8b194021b
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Created a standard user and login to Rancher as that user.
3. Provisioned a downstream RKE2 node driver cluster:
![image](https://user-images.githubusercontent.com/52591819/180838988-5f07cafd-ed65-4671-a9f6-04b09a3d7442.png) 
4. Once provisioned, copied the kubeconfig file over to a client machine to a client machine.
5. Navigated to the client machine and installed `clusterissuer` (kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml)).
6. Created a `clusterissuer` for the created RKE2 node driver cluster.
     - Used the following documentation: https://cert-manager.io/docs/configuration/selfsigned/.
7. Go to Cluster Explorer > cluster > More Resources. Verified the `ClusterIssuer` exists:
![image](https://user-images.githubusercontent.com/52591819/180838936-c736102c-9b5a-49f2-bdcd-10b086353ad2.png)
![image](https://user-images.githubusercontent.com/52591819/180838947-b7748505-8733-4ac0-8940-5702c9ad654a.png)
8. Navigated to Cluster Explorer > cluster > Service Discovery > Ingresses and click `Create`.
9. In the `cert-manager` namespace, verified I am able to use the configured `Target Service` in the TLS options:
![image](https://user-images.githubusercontent.com/52591819/180838891-f79e5d18-4293-4992-86f8-96c9e4e43ccc.png) 
10. Create the Ingress and verify if it is `Active`:
![image](https://user-images.githubusercontent.com/52591819/180838865-ab984aab-9b8e-4f7e-9faa-11539ded2238.png)
