### ISSUE TITLE
UI Components Unnecessarily Duplicated

### ISSUE THREAD

**Issue by brudnak** [rancher/dashboard#5693]
#### Setup

| Component                 | Version / Type                                                                                |
| ------------------------- | --------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-68eb5d1267679e02eb2383f0ec965b3f896ae3e3-head                                            |
| Rancher commit link       | [68eb5d1](https://github.com/rancher/rancher/commit/68eb5d1267679e02eb2383f0ec965b3f896ae3e3) |
| Installation option       | helm high availability                                                                        |
| RKE binary version used   | v1.3.10-rc4                                                                                   |
| If Helm Chart k8s cluster | v1.22.8                                                                                       |
| Cert Details              | let's encrypt                                                                                 |
| Docker version            | 20.10.7, build f0df350                                                                        |
| Helm version              | v2.16.8-rancher1                                                                              |
| Downstream cluster type   | not applicable                                                                                |
| Downstream K8s version    | not applicable                                                                                |
| Logged in user role       | administrator                                                                                 |
| Browser type              | google chrome                                                                                 |
| Browser version           | 100.0.4896.127 (official build) (x86_64)                                                      |

#### Describe the bug
Certain Vue components are being duplicated in the Rancher UI

#### To Reproduce
1. Create a Rancher server with v2.6-head
   - Either with helm or a docker install
2. Navigate to the workloads page of the local cluster
   - Click `hamburger menu` -> `local` -> `Workload` -> `Deployments` -> `All Namespaces`
3. Observe the UI

#### Result
Certain Vue components are being duplicated
- `<BadgeStateFormatter>`
- `<LinkDetail>`
- `<PodImages>`
- `<LiveDate>`

See the screenshot below

#### Expected Result
Expect components in the UI to not be unnecessarily duplicated

#### Screenshots
![2022-04-24_10-07-19](https://user-images.githubusercontent.com/40877149/164988834-31cfbdf6-0a66-49c1-980c-bc805be4637b.png)

**Comment by richard-cox** [comment]
This came in via a bad merge in https://github.com/rancher/dashboard/pull/5620. The issue is in `components/SortableTable/index.vue` the td cell slot https://github.com/rancher/dashboard/commit/ebc9927756a558fbcb242fd43cc5db796c834dbf#diff-1a2277d92947d83bba624b418c7879f3fa45d44df0bb93f741aa3ae7c4b7df43L892

**Comment by richard-cox** [comment]
There's also a bug on the dashboard home page, see https://github.com/rancher/dashboard/commit/3f2230681cc0e94c0cb1fe3f5e8962d886f321fa & https://github.com/rancher/dashboard/commit/3f2230681cc0e94c0cb1fe3f5e8962d886f321fa#diff-ab7866df53ebbcb1c832a3661f0185cad358176373f0d65912c772357e62724dR277 (`NAMESPACE` is a type here, should be a table column)

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                                |
| ------------------------- | --------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-a6d2050e47d3b202496ad9c48d16e610be207829-head                                            |
| Rancher commit link       | [a6d2050](https://github.com/rancher/rancher/commit/a6d2050e47d3b202496ad9c48d16e610be207829) |
| Installation option       | helm high availability                                                                        |
| RKE binary version used   | v1.3.10-rc4                                                                                   |
| If Helm Chart k8s cluster | v1.22.8                                                                                       |
| Cert Details              | let's encrypt                                                                                 |
| Docker version            | 20.10.7, build f0df350                                                                        |
| Helm version              | v2.16.8-rancher1                                                                              |
| Downstream cluster type   | not applicable                                                                                |
| Downstream K8s version    | not applicable                                                                                |
| Logged in user role       | administrator                                                                                 |
| Browser type              | google chrome                                                                                 |
| Browser version           | 100.0.4896.127 (official build) (x86_64)                                                      |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --version 2.6.5-rc3 \
  --namespace cattle-system \
  --set hostname=$HOSTNAME_REDACTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_REDACTED \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=v2.6-head
```

## Validation steps

1. Create a Rancher server with v2.6-head
   - Either with helm or a docker install
2. Navigate to the workloads page of the local cluster
   - Click `hamburger menu` -> `local` -> `Workload` -> `Deployments` -> `All Namespaces`
3. Observe the UI
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Rancher dashboard to work as expected with no duplicated UI elements

#### :white_check_mark:Actual
Rancher dashboard to work as expected with no duplicated UI elements
