### ISSUE TITLE
Remove `Tech Preview` for RKE2 clusters for the `v2.6.5` release

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#5698]
**Setup**
- Rancher version: `v2.6-head`
- Browser type & version: Any

**Describe the bug**

For the upcoming `v2.6.5` release, we will need to remove the `Tech Preview` for RKE2 clusters as it is going to become GA.

**To Reproduce**

1. Setup Rancher `v2.6-head` and navigate to Rancher UI > top-left dropdown menu > Cluster Management > Create.
2. Toggle the RKE1 switch to RKE2; you will see `Tech Preview`.

**Result**
You will see `Tech Preview` when going to setup a RKE2 cluster.

**Expected Result**

You should not see `Tech Preview` when going to setup a RKE2 cluster.

**Comment by richard-cox** [comment]
I brought up `2.6-head` earlier today (`68eb5d1`), only Harvester was marked with tech preview (not sure that should be though... )

![image](https://user-images.githubusercontent.com/18697775/165125325-4a9c8b15-ae1e-4964-946c-665f09b5b7ad.png)

**Comment by rak-phillip** [comment]
I just pulled a new version of head and I only see Harvester marked as `Tech Preview`, I'm running `68eb5d1`. @markusewalker can you provide the version hash that you are using? 

![image](https://user-images.githubusercontent.com/835961/165125561-da6c756f-9093-4853-82b2-b0444fa3b10c.png)

**Comment by markusewalker** [comment]
@rak-phillip seems I was using an outdated `v2.6-head`, just tried most up to date and yes, I do see that it is removed:

![image](https://user-images.githubusercontent.com/52591819/165126112-c0f750f2-ec41-4f98-a31b-4ef74636bab8.png)

Apologies for the confusion, seems that this can be closed out.

**Comment by rak-phillip** [comment]
Sorry dup, I didn't see @richard-cox already had this covered..

I was informed that Harvester should still be marked as `Tech Preview` when reviewing #5663 with @catherineluse. LMK if this is no longer the case and I'll remove the label there as well.
