### ISSUE TITLE
Unable to manage machines from Cluster Management UI

### ISSUE THREAD

**Issue by thedadams** [rancher/dashboard#5699]
**Setup**
- Rancher version: v2.6-head

**Describe the bug**
The three-dot menu next to a machine in the machine pool view isn't working currently.

**To Reproduce**
1. From the Cluster Management UI, click on a cluster to go to a URL similar to `https://RANCHER_URL/dashboard/c/CLUSTER_ID/manager/provisioning.cattle.io.cluster/fleet-default/CLUSTER_NAME#machine-pools`
2. Click on the three dots next to a machine in a pool.

**Result**
Nothing happens in the UI and the following error appears in the browser console:
```
TypeError: Cannot read properties of undefined (reading 'top')
    at c (position.js:19:17)
    at n.fitOnScreen (position.js:75:15)
    at f.updateStyle (ActionMenu.vue:149:1)
    at f.<anonymous> (ActionMenu.vue:102:1)
    at Array.<anonymous> (vue.runtime.esm.js:1980:12)
    at ie (vue.runtime.esm.js:1906:12)
```
**Expected Result**
The menu to delete the machine or SSH to the machine should appear.

**Screenshots**

![Screen Shot 2022-04-25 at 08 36 10](https://user-images.githubusercontent.com/3682717/165123351-3fee4459-2908-4d7e-aff3-f07bf2b571a7.png)

**Comment by richard-cox** [comment]
Note to QA. These two issues are most probably the same issue
- #5710
- #5719

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/d5e68641e8f5f2d05bfa82731e5d8148e0f45017.

**ENVIRONMENT DETAILS**
- Ubuntu 20.04: Docker Install
- Rancher version: `v2.6.5-rc3` and `v2.6-head` https://github.com/rancher/rancher/commit/d5e68641e8f5f2d05bfa82731e5d8148e0f45017
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and create a user with Standard global permissions.
2. As the created standard user, navigate to Rancher UI > Cluster Management > Create.
3. Create an RKE2 cluster and navigate to the cluster.
4. Click on the ellipses on each of the nodes in the `Machine Pool`; results below:
![image](https://user-images.githubusercontent.com/52591819/165813230-92ad1cab-e275-4637-aabd-8078bf3fb365.png)
