### ISSUE TITLE
Project - Create/Edit Page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#570]
# Requirements:

## Generic Info Section
- Use same `NameNSDescription` component to capture `Name` and `Description`

## Main Section
- Ability to show existing namespaces in a project, with the option of removing them.
- Ability to add/select any namespace into project. If the namespace isn't associated with a projects, it's added to the project. If the namespace is associated with a different project, it moves the namespace from that project to this project. When selecting a namespace, it should group them by "Not in a project" and per project, so the user can tell the difference between associating a namespace to a project and moving it into the project.

## Tabs:

Tab Name | Content Notes 
---|---
Resource Quota | See content below
Container Default Resource Limit | See content below - Same component/content as the tab in namespace edit/detail
Labels | Use ResourceTabs component
Annotations | Use ResourceTabs component

**Resource Quota Tab**
Helper Tab: Configure how much of the resources the project can consume 
Quotas - Ability to add/remove multiple quotas 

Review the ember UI if any questions

<img width="860" alt="Screen Shot 2020-04-29 at 8 18 08 PM" src="https://user-images.githubusercontent.com/11410997/80668373-9af83600-8a56-11ea-8f9c-ab7924127b37.png">

Name | Fields
---|---
Resource Type | Dropdown List where the examples and labels change per type
Project Limit | Textbox 
Namespace Default Limit | Textbox

Resource Type Dropdown Options

Type | Project Limit Example Input | Project Limit Unit Label | Namespace Default Example Input | Namespace Default Unit Label
---|---|---|---|---
CPU Limit | `e.g. 2000` | `milli CPUs` | `e.g. 500` | `milli CPUs`
CPU Reservation  | `e.g. 2000` | `milli CPUs` | `e.g. 500` | `milli CPUs`
Memory Limit  | `e.g. 2048` | `MiB` | `e.g. 1024` | `MiB`
Memory Reservation  | `e.g. 2048` | `MiB` | `e.g. 1024` | `MiB`
Storage Reservation   | `e.g. 50` | `GB` | `e.g. 10` | `GB`
Services - Load Balancers  | `e.g. 50` |  None | `e.g. 10` | None
Services - Node Ports  | `e.g. 50` |  None | `e.g. 10` | None
Pods  | `e.g. 50` |  None | `e.g. 10` | None
Services | `e.g. 50` |  None | `e.g. 10` | None
Config Maps | `e.g. 50` |  None | `e.g. 10` | None
Persistent Volume Claims  | `e.g. 50` |  None | `e.g. 10` | None
Replication Controllers  | `e.g. 50` |  None | `e.g. 10` | None
Secrets | `e.g. 50` |  None | `e.g. 10` | None

**Container Default Resource Limit**
Helper Text in Tab: Configure how much of the resources the container can consume by default

Type | Example Input | Unit Label next to Textbox
---|---|---
CPU Limit | `e.g. 1000` | `milli CPUs` 
CPU Reservation  | `e.g. 1000` | `milli CPUs`
Memory Limit  | `e.g. 128` | `MiB`
Memory Reservation  | `e.g. 128` | `MiB` |

<img width="868" alt="Screen Shot 2020-04-29 at 8 18 44 PM" src="https://user-images.githubusercontent.com/11410997/80668396-a8152500-8a56-11ea-98ad-a02331a5c95f.png">

To be done later:
- RBAC

**Comment by lvuch** [comment]
https://xd.adobe.com/view/c3dd248e-9eef-4bc0-5228-2dca2c899db4-b5ec/

**Comment by deniseschannon** [comment]
Putting this onto the backlog until Projects v2 is scoped

**Comment by deniseschannon** [comment]
Closing in favor of new issue when prioritized for Projects v2
