### ISSUE TITLE
Project - Detail Page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#571]
# Requirements:

Review requirements from Project Create/Edit page rancher/dashboard#570

## Generic Info Section
- Project Name
- Description

## Main Section
- Ability to show all namespaces in the project matching the layout of namespaces of Create/Edit. 

## Tabs:

Tab Name | Content Notes 
---|---
Resource Quota | Review the Project Create/Edit
Container Default Resource Limit | Review the Project Create/Editcomponent/content as the tab in namespace edit/detail
Labels | Use ResourceTabs component
Annotations | Use ResourceTabs component

To be done later:
- RBAC

**Comment by lvuch** [comment]
https://xd.adobe.com/view/c3dd248e-9eef-4bc0-5228-2dca2c899db4-b5ec/

**Comment by lvuch** [comment]
<img width="584" alt="Screen Shot 2020-04-30 at 11 17 04 AM" src="https://user-images.githubusercontent.com/3013118/80744852-2663dc80-8ad4-11ea-9680-b38ff1cf4cb2.png">

**Comment by deniseschannon** [comment]
Closing in favor of new issue when prioritized for Projects v2
