### ISSUE TITLE
Cluster Management doesn't show clusters following EKS k8s upgrade for Standard Users

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#5711]
**Rancher Server Setup**
- Rancher version: `2.6.5-rc3` or `v2.6-head [v2.6-7db4fe4e81939a5f6b420f303478a169cc35588a-head]`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm or Docker [reproduced with both]
- Proxy/Cert Details: Helm with byo-valid; Docker with no certs

**Information about the Cluster**
- Kubernetes version: `1.20`
- Cluster Type (Local/Downstream):
 Downstream EKS hosted cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Standard user

   
**Describe the bug**
Standard users no longer have access to clusters in `Cluster Management` with current rancher `v2.6-head` or on rancher `v2.6.5-rc3`

**To Reproduce**
1. Fresh install of rancher `v2.6-head` or `2.6.5-rc3`
2. As admin, create a standard user
3. As standard user, provision a downstream cluster [ Any will reproduce the issue]
4. Reproduced

**Result**
Cluster Management no longer shows clusters

**Expected Result**
Cluster Management is still populated with all clusters

**Screenshots**

`Cluster Management - Standard user`:
<img width="1684" alt="Screen Shot 2022-04-25 at 3 52 12 PM" src="https://user-images.githubusercontent.com/46494969/165190970-0a7b96f3-d670-4bdb-9c08-7e5bc4df7847.png">

`Home - Standard user`:
<img width="1682" alt="Screen Shot 2022-04-25 at 3 52 25 PM" src="https://user-images.githubusercontent.com/46494969/165191028-bd3b56ab-5e25-4c5c-af21-78c9c182e3e5.png">

`Cluster Management - Admin`:
<img width="1575" alt="Screen Shot 2022-04-25 at 4 24 16 PM" src="https://user-images.githubusercontent.com/46494969/165191047-6076f065-b912-4e96-a340-15450e6f144c.png">

**Additional context**

`Console`:
<img width="1473" alt="Screen Shot 2022-04-25 at 4 03 18 PM (1)" src="https://user-images.githubusercontent.com/46494969/165191245-0c252682-55ed-44f0-9a6d-466566686a4c.png">

<img width="1475" alt="Screen Shot 2022-04-25 at 4 03 08 PM (1)" src="https://user-images.githubusercontent.com/46494969/165191259-5d5dc9c3-50bc-4eb4-bcb6-365f64541df9.png">

**Comment by anupama2501** [comment]
Seeing this issue - Clusters are not listed in the cluster management page post rancher upgrade from 2.6.3 >> 2.6-head a6d2050

**Comment by gaktive** [comment]
Connection to a ticket @nwmac filed: https://github.com/rancher/rancher/issues/37473 -- it looks like the backend removed something that a standard user could see.

**Comment by gaktive** [comment]
Putting this in Backend Blocked for now though it's not technically that just so we're aware that @MbolotSuse is presently looking at this and we can react if UI has to do something.

**Comment by cbron** [comment]
Removing backend blocked for now, as the API's are returning cluster information correctly.

**Comment by Josh-Diamond** [comment]
Ticket #5711 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-311f4623b3c60f22daf281ce3fd4d4c31e5e07dc-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As standard user, provision a downstream cluster [ Any will reproduce the issue]
4. Verified - Standard users have access to clusters in `Cluster Management`

Screenshot:

`Cluster Management - Standard User`
<img width="1227" alt="Screen Shot 2022-04-27 at 4 55 10 PM" src="https://user-images.githubusercontent.com/46494969/165649698-64bb093c-1ac4-47b9-9ab4-dae9f1ce852d.png">
