### ISSUE TITLE
Add EKS 1.22

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#5716]
**Detailed Description**
Add support for EKS 1.22.

**Context**
EKS 1.22 is GA (https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) and Kubernetes 1.22 is also supported already for all other hosted providers.

**Comment by snasovich** [comment]
This should ow be unblocker as backend change https://github.com/rancher/rancher/issues/37534 is done as well.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `a31f5b8`**

- 1.22 is available on UI and when launched `v1.22.6-eks-14c7a48` does get deployed
