### ISSUE TITLE
the 3 dot menu on the repositories page doesn't work

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5719]
**Setup**
- Rancher version: 2.6.5-rc3
- Browser type & version: chrome latest

**Describe the bug**
after creating a repository in the apps section, attempted to click the 3 dots for a menu - instead, no observable response to user and error in console

**To Reproduce**
1. explore downstream cluster
2. navigate to apps > repositiories
3. add a repository
4. right click 3 dots menu for new repo

**Result**
clicking on the 3 dots throws an error
`vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'top')
    at c (position.js:19:17)
    at n.fitOnScreen (position.js:75:15)
    at f.updateStyle (ActionMenu.vue:149:1)
    at f.<anonymous> (ActionMenu.vue:102:1)
    at Array.<anonymous> (vue.runtime.esm.js:1980:12)
    at ie (vue.runtime.esm.js:1906:12)`

**Expected Result**
menu appears

**Screenshots**

<img width="1771" alt="Screen Shot 2022-04-26 at 9 19 14 AM" src="https://user-images.githubusercontent.com/89212856/165309024-4649e74c-b77c-4d2d-b786-41629e68bb9f.png">

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment]
I'm very certain this is the same issue as #5699 and https://github.com/rancher/dashboard/issues/5710, which was fixed via https://github.com/rancher/dashboard/pull/5707

**Comment by ronhorton** [comment]
dup of https://github.com/rancher/dashboard/issues/5699
