### ISSUE TITLE
Project - List Page for Project Create/Detail

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#572]
- Determine how to include `Create Project`. Currently, there is a `Create from YAML` and `Create` in `MastHead`, so how do we add the concept of projects in the namespace list page?
- How would you navigate to a project details page?

Note: There is no separate page for list of projects

**Comment by lvuch** [comment]
https://xd.adobe.com/view/c3dd248e-9eef-4bc0-5228-2dca2c899db4-b5ec/

**Comment by lvuch** [comment]
<img width="839" alt="Screen Shot 2020-04-30 at 10 23 20 AM" src="https://user-images.githubusercontent.com/3013118/80742249-e995e680-8acf-11ea-9bd2-f3219e753388.png">
<img width="400" alt="Screen Shot 2020-04-30 at 10 19 23 AM" src="https://user-images.githubusercontent.com/3013118/80742250-ea2e7d00-8acf-11ea-97c5-ba7cecf992b5.png">

**Comment by codyrancher** [comment]
@deniseschannon 
We want to change the create buttons for all pages to be this dropdown button right?

**Comment by deniseschannon** [comment]
@codyrancher Can we hold off on this one? It's still unclear where the best place to put the create project page.

**Comment by codyrancher** [comment]
@deniseschannon I was just referring to the button and not the page but I can hold off on both.

**Comment by deniseschannon** [comment]
Keeping this as a reminder that no list page exists for projects, but moving to the backlog until Projects v2 is scoped out and put in.

**Comment by deniseschannon** [comment]
Closing in favor of new issue when prioritized for Projects v2
