### ISSUE TITLE
Snapshot button is not aligned properly

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#5721]
**Setup**
- Rancher version: v2.6.5-rc3: 7db4fe4
- Browser type & version: Firefox Developer 100.0b9

**Describe the bug**

The `Snapshot Now` button is not aligned all the way to the right. 

**To Reproduce**

1. Create a new RKE or RKE2 cluster
2. Navigate to Cluster Management => [Cluster Name] => Snapshots

**Result**

Snapshot button doesn't appear to have any consistent alignment with the rest of the content

![image](https://user-images.githubusercontent.com/835961/165338786-431ed4ea-8ff4-4a49-9f4f-29bd149d0768.png)

**Expected Result**

Snapshot button to be aligned right

![image](https://user-images.githubusercontent.com/835961/165339196-d418e35b-7978-41d1-b18d-ddcb7a3897c9.png)

**Comment by rak-phillip** [comment]
I noticed this one while taking a glance at #5338 

@gaktive @nwmac

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `7db4fe4`**

Snapshot Now button is aligned correctly
<img width="1665" alt="Screen Shot 2022-04-27 at 3 39 12 PM" src="https://user-images.githubusercontent.com/26032343/165642953-5ae66056-501b-4d65-a53b-517d9f1e85a6.png">
