### ISSUE TITLE
Hide encryption key rotation for 2.6.5

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5723]
Per https://github.com/rancher/dashboard/issues/4540#issuecomment-1109113077, a feature designed for 2.6.5 has been delayed. We'd like to rotate encryption keys but the backend code is delayed so UI need to ensure that we won't see this in Dashboard.

This will be hopefully available in a future version.

Original work for this feature 2.6.5 (now set for 2.6.6): https://github.com/rancher/dashboard/issues/4540
Work to hide done here, already merged: https://github.com/rancher/dashboard/pull/5709

@snasovich let me know if I missed anything.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 7db4fe4
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
Encryption key rotation is hidden in 2.6.5
