### ISSUE TITLE
UI reloads while selecting an rke1 template and the node pool values if provided are removed

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5726]
Setup

Rancher version: 2.6-head a6d2050
Browser type & version: Chrome

**Describe the bug**
While creating a node driver clusters, if we fill in the node pool form before selecting the rke templates to be used in cluster options, UI reloads and the values provided for the node pools are removed. 

**To Reproduce**
1. From RKE1 configuration >> RKE templates >> create a node pool with default values
2. From cluster management >> create an rke1 node driver cluster any provider.
3. Create 4 node pools with etcd, worker, cp and cp roles respectively and provide a node template in all the node pools.
4. Select the rke template created in step1 in the cluster options.

**Result**
UI reloads and the all the added node pools are removed. 

**Expected Result**
Node pools should not be removed when the rke template is selected.

**Comment by mantis-toboggan-md** [comment]
I can't reproduce this using the latest 2.9 nor 2.10 code. The ui still appears to be reload when template revisions are selected, but node pool configuration is preserved:

https://github.com/user-attachments/assets/9975723b-a763-4374-b2ff-d813505bfdc7
