### ISSUE TITLE
RKE1 - Add a field for setting the backoff value

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#5728]
**Detailed Description**

RKE1 backoff is a new feature that allows users to configure the number of retries before Rancher gives up creating or updating the cluster due to errors. 

We would like to have an option on the cluster edit page for this value:
```
Name: retry backoff or TBD
Type: integer 
Defaut Value: 10 
Filed in Cluster Config: TBD
```

Note: more information will be added once they are available 

**Context**

Please check https://github.com/rancher/rancher/issues/37479 for more details.

**Comment by snasovich** [comment]
Due to a shift in priorities, this is no longer in the v2.6.6 release plans, so moving it to Unscheduled for now.

**Comment by nwmac** [comment]
Closing as stale since backend is no longer scheduled.
