### ISSUE TITLE
Service - List/Edit/Detail

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#573]
This issue is to track all issues around the service component. This used to be called `Service Discovery` in the old UI. 

## List page
Issue: https://github.com/rancher/dashboard/issues/630

## Create/Edit Page
Issue: https://github.com/rancher/dashboard/issues/583

## Detail Page
Issue: https://github.com/rancher/dashboard/issues/632

**Comment by izaac** [comment]
Rancher version: `master-head (09/01/2020)` _c428bc9_

Spot checked the Service Detail areas mentioned [here](https://github.com/rancher/dashboard/issues/632#issuecomment-656317714).
Additionally checked Service listing, and Service edit pages also.
