### ISSUE TITLE
Improve Deployment creations screen and add Pod creation view

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5734]
Details TBD

Implement the new design for the deployment creation screen.

Do this in a way that allows this to be reused for the Pods edit screen (which does not currently exist).

Rough design here - https://xd.adobe.com/view/3a0ff278-5d42-4f38-82fe-647fe3472cc7-6f5c/screen/fd9531dc-24ef-4425-b6df-fbd8c980544a - still some tweaks to be made.

**Comment by Josh-Diamond** [comment]
Was this closed by mistake? I did not test and sign off on this 🤔

**Comment by Josh-Diamond** [comment]
Re-opening

**Comment by nwmac** [comment]
@Josh-Diamond There should be a GH action to re-open and move to test when a linked PR is merged - not sure what happened - this should not have been closed. Apologies.

**Comment by Josh-Diamond** [comment]
Ticket #5734 - Test Results

With Docker on a single-node instance:

Veri-FAILED on rancher `v2.6-b9a70077ca0e2bae142a06e5d2286bdcc50fe42d-head`:
1. Fresh install of rancher `v2.6-head`
2. From `Cluster Explorer` of `local` cluster, visit `Deployments`, then `Create` a new deployment
3. Verified - Deployments, pods, and containers tabs are present and functional
4. Add multiple containers to a deployment
5. Veri-FAILED - `Add container` button appears to be a tab; as seen with adding labels and annotations under the `Pods` tab, styling the `Add container` button a similar border would clear up potential confusion
6. Veri-FAILED - `Add container` button stays highlighted after each click; this could be resolved by making the button un-selectable via CSS
7. Verified - CronJobs, DaemonSets, Jobs, StatefulSets, Pods - all functional and unaffected by this change

Screenshots:

`Step 3 - Deployments`
<img width="1609" alt="deploy" src="https://user-images.githubusercontent.com/46494969/180568525-664d5928-23f6-459c-a370-939d8a419831.png">

`Step 3 - Pods`
<img width="1605" alt="pods" src="https://user-images.githubusercontent.com/46494969/180568542-cab674cf-b3e2-4cc7-ad2d-cdae01b3ee56.png">

`Step 3 - Containers`
<img width="1609" alt="containers" src="https://user-images.githubusercontent.com/46494969/180568560-03015e4e-5de3-4a31-b8fa-0e01bbaee9e0.png">

`Step 5`
<img width="1608" alt="tab" src="https://user-images.githubusercontent.com/46494969/180569430-eb0768dd-d53a-40f4-ba73-a38898e4ac43.png">

`Step 6`
<img width="1611" alt="stays highlighted" src="https://user-images.githubusercontent.com/46494969/180568653-3d92ba74-2149-41b1-ae7d-472e775be1ce.png">

**Comment by Shavindra** [comment]
@Josh-Diamond I fixed the part where the button remain `focused`. Also on Friday I noticed I missed a commit from the remote. `Health Check` option should not be applicable to `init container`. I pushed this commit today. 

Probably worth checking on the properties / verifying against the Workload/Pod/Container specs.

**Comment by Josh-Diamond** [comment]
Ticket #5734 - Test Results [pt. 2]

With Docker on a single-node instance:

Verified on rancher `v2.6-b66dd0f614f9d60ef54dfb82da12b9b8b194021b-head`:
1. Fresh install of rancher `v2.6-head`
2. From `Cluster Explorer` of local cluster, visit `Deployments`, then `Create` a new deployment
3. Verified - `Containers => Init container`; Health checks unavailable for `Init container`
4. Select `Add container`
5. Verified - `Add container` button no longer stays highlighted

Screenshots:

`Step 3`
<img width="1610" alt="Screen Shot 2022-07-25 at 9 54 16 AM" src="https://user-images.githubusercontent.com/46494969/180836497-ed97ccba-7595-4f73-a8d9-0bfbbe70cdb9.png">

`Step 5`
<img width="1376" alt="Screen Shot 2022-07-25 at 9 55 02 AM" src="https://user-images.githubusercontent.com/46494969/180836524-45fdb451-27d3-4219-a9fb-12dc0201344e.png">
