### ISSUE TITLE
Add IP address to cluster machine pools list

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5735]
In this list:

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/1955897/165524394-624c2c9c-6366-48a8-8e05-6f9af1ed2ab7.png">

add a column for the IP address of the node - this is available in the `ipAddress` field.

**Comment by Shavindra** [comment]
@nwmac I am seeing following properties. Which one should I be using?

e.g endpoint: https://localhost:8005/v1/management.cattle.io.nodes/c-twtqc/m-fxh9r

```
"internalNodeStatus":{
   "addresses":[
      {
         "address":"104.248.88.140",
         "type":"InternalIP"
      },
      {
         "address":"sf120",
         "type":"Hostname"
      }
   ],
}
```
```        
"nodeAnnotations":{
       "flannel.alpha.coreos.com/public-ip":"104.248.88.140",
       "projectcalico.org/IPv4Address":"10.110.0.2/20",
```
```
"rkeNode":{
    "address":"104.248.88.140",
    "hostnameOverride":"sf120",
}
```

**Comment by nwmac** [comment]
I think we want to show the same as on the Nodes list when you go into the Cluster - so I think its the first one - `internalNodeStatus.addresses` and then the `InternalIP`. There can be an external IP in some cases - but I think showing the internal IP is a start and is consistent with the Ember UI.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head bca5ada
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: node driver

### Testing: ###

Retested node driver cluster with the following steps:
1. Deploy cluster
2. Go to Cluster Management and click on cluster
3. Check that `IP Address` field is now visible in Machine Pools section

**Result**
Node driver clusters now display the `IP Address` field in Machine Pools section

![image.png](https://zube.io/files/rancher/c9aee36835c80affe064a3227d0c7b0e-image.png)
