### ISSUE TITLE
Change catalog icon from a generic book and then include icon as part of project monitoring helm chart

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5742]
Based on feedback from a recent demo, we should change the catalog icon to be something other than a generic book. We should then include that new icon as part of the project monitoring helm chart.

**Comment by kwwii** [comment]
I suggest using the monitoring icon from our icon set: [https://gitlab.com/SUSE-UIUX/eos-icons/-/blob/master/svg/monitoring.svg](url)

**Comment by gaktive** [comment]
@aiyengar2 to add to the chart. He can then pass to @ronhorton for testing.

**Comment by ronhorton** [comment]
Icon is present
![Screen Shot 2022-05-06 at 3.50.13 PM.png](https://zube.io/files/rancher/2db1a135acda908834639be89ff71939-screen-shot-2022-05-06-at-3-50-13-pm.png)
