### ISSUE TITLE
Make it clear to users that V1 project monitoring page is not supposed to be used for V2 monitoring

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5745]
In the cluster explorer side nav, make it so that monitoring side nav link is helm-chart-specific. This means that installing monitoring v2 does not enable UI forms for project monitoring v1 if the `legacy` flag is enabled.

**Comment by gaktive** [comment]
@catherineluse to get a screenshot of what's appearing since there's an iFrame at play here.

**Comment by catherineluse** [comment]
Here's the steps to reproduce it:

1. Install V2 monitoring
2. Go to **Global Settings > Feature Flags** and enable the `legacy` feature flag
3. Go to cluster explorer in the cluster where V2 monitoring is installed
4. In the side nav, go to **Legacy > Project > Monitoring** (with a project selected in the top nav)

This V1 iFramed monitoring page appears:
<img width="1302" alt="Screen Shot 2022-04-28 at 10 58 57 AM" src="https://user-images.githubusercontent.com/20599230/165818159-c5e83b0f-e94e-4f3c-a7ad-171f5fd753e6.png">

**Comment by gaktive** [comment]
- Low bar for 2.6.5: modify the label to say V1 Project Monitoring Configuration if this appears with V2 installed.
- Stretch: show all form elements disabled (or a blank page though it'll be weird)
- Ideal: don't load this page at all (may have to be 2.6.6)

**Comment by aalves08** [comment]
PR here:
https://github.com/rancher/ui/pull/4837

**Comment by Josh-Diamond** [comment]
Ticket 5745 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6-054b5d195f115b91a5284e85270403ba6f3ac99b-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 cluster
3. Once provisioned, enable v2 monitoring
4. From `Global Settings > Feature Flags`, activate the `legacy` feature flag
5. From RKE2's `Cluster Explorer`, from left-side menu, navigate down to `Legacy > Projects > Monitoring`
6. Reproduced - Page title reads `Project Monitoring Configuration`

Screenshot:
`Step 6`
<img width="1670" alt="Screen Shot 2022-05-04 at 2 54 48 PM" src="https://user-images.githubusercontent.com/46494969/166833643-f724c0b7-9b14-45c2-a0d4-6a33333756eb.png">

---

Veri-FAILED on rancher `v2.6-4bbee5995053eb52ef447ca82de2c90b1af8b21a-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 cluster
3. Once provisioned, enable v2 monitoring
4. From `Global Settings > Feature Flags`, activate the `legacy` feature flag
5. From RKE2's `Cluster Explorer`, from left-side menu, navigate down to `Legacy > Projects > Monitoring`
6. Veri-FAILED - Page title reads `Project Monitoring Configuration`; expected to read `V1 Project Monitoring Configuration`

Screenshot:
`Step 6`
<img width="1675" alt="Screen Shot 2022-05-05 at 9 12 33 AM" src="https://user-images.githubusercontent.com/46494969/166966625-19ceee1f-03b4-41e4-ad5b-651bc32abde4.png">
