### ISSUE TITLE
When searching for `helm` in the top nav, group the results under `helm` and not `k3s`

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5746]
Based on feedback tied to v2 Project Monitoring, when searching for `helm` in the top nav, we should group the results under `helm` instead of `k3s` as is presently done.

**Comment by gaktive** [comment]
This would be complicated based on the underlying code. Searching for `k3s` doesn't even bring itself up apparently; only `helm` brings that up.

**Comment by catherineluse** [comment]
This turned out to be a very small change.

**Comment by ronhorton** [comment]
**Pass** verified in `2.6-head Commit ID c5746d9`

1. installed monitoring
2. installed alerting-drivers
3. installed prometheus-federator
4. navigated to cluster manager
5. selected cluster
6. from cluster dashboard, selected the magnifying glass at the top of the page
7. typed `helm`

result: resources were grouped under helm
![Screen Shot 2022-06-27 at 2.51.39 PM.png](https://zube.io/files/rancher/5673fc3dba476d644b9dc11de665d856-screen-shot-2022-06-27-at-2-51-39-pm.png)
