### ISSUE TITLE
Hide project monitoring form if there's only the Prometheus created namespace.

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5751]
If there are no namespaces except the namespace created by the Prometheus operator, the project monitor form should not be shown.

**Comment by gaktive** [comment]
This may be addressed by @aiyengar2's work. We'll base namespace filtering off a TBD config map.

**Comment by gaktive** [comment]
Backend complete so it's now UI.

**Comment by ronhorton** [comment]
@Sean-McQ what can be done to test this change?

**Comment by Sean-McQ** [comment]
@ronhorton 
* Create a Project: "proj"
* Create a namespace: "ns"
* Go to Create Project Monitor and notice "proj" is in the dropdown selector
* Delete namespace "ns" from project "proj"
* Go to Create Project Monitor and notice "proj" is no longer in the dropdown selector

**Comment by ronhorton** [comment]
**Pass** verified in `2.6-head Commit ID 132b182`

1. Create a Project: "proj"
2. Create a namespace: "ns"
3. Go to Create Project Monitor and notice "proj" is in the dropdown selector
4. Delete namespace "ns" from project "proj"
5. Go to Create Project Monitor and notice "proj" is no longer in the dropdown selector
