### ISSUE TITLE
Add system project ID to global values when any Helm chart is installed

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5753]
When project monitoring is installed, the UI automatically adds the system project ID to the ProjectHelmChart.

**Comment by gaktive** [comment]
The project ID would be added to the YAML for the Prometheus Federator chart. Currently it's a text box so we could add `global.cattle.clusterID` automatically.

@catherineluse to update with the location.

**Comment by catherineluse** [comment]
This `install.vue` component is where we normally add a bunch of standard "global values" for Helm charts that get installed through Rancher: https://github.com/rancher/dashboard/blob/master/pages/c/_cluster/apps/charts/install.vue#L785

To add the system project ID, I think we would have to go to the `addGlobalValuesTo` function and add something like:

```
setIfNotSet(global, 'systemProjectId', systemProjectId);
```

**Comment by catherineluse** [comment]
Changed the issue title to be more accurate - this will affect all helm charts.

**Comment by ronhorton** [comment]
**Pass** verified in `2.6-head Commit ID 132b182`
