### ISSUE TITLE
Designate k3s provisioning as "Tech Preview"

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5765]
For 2.6.5 release, we're focusing on GA-ing RKE2 provisioning.
Due to this, we will want to retain "tech preview" status for k3s provisioning.

https://github.com/rancher/dashboard/issues/5318

**Comment by gaktive** [comment]
@snasovich just to confirm what QA brought up, do we need to retain Tech Preview for k3s for 2.6.5? This should be quick to do if so.

**Comment by snasovich** [comment]
@gaktive , yes - if QA has not tested k3s to the same extent as RKE2 to sign-off on GA we should not mark k3s as GA. The commitment is "RKE2 Provisioning GA" so we should be fine.
cc: @deniseschannon

**Comment by deniseschannon** [comment]
Yes, k3s should remain in tech preview for 2.6.5.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `311f462`**
<img width="979" alt="Screen Shot 2022-04-29 at 11 22 17 AM" src="https://user-images.githubusercontent.com/26032343/166001588-7aee0e7d-9e2c-496c-9965-20cf1a43c5c2.png">
