### ISSUE TITLE
Left navigation is empty after logging out and logging back from the UI as as standard user or an admin

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5770]
Setup

Rancher version: 2.6-head d5e6864
Browser type & version: Chrome

**Describe the bug**
After installing neuvector feature chart, if we navigate to the neuvector in the left navigation, log out and log back in as a standard user or an admin left navigation becomes empty.

If we navigate to cluster management page it is still empty but if we hard refresh the cluster management page, left navigation re appears.

**To Reproduce**
1. Create an RKE1 or RKE2 node driver cluster with 3 worker, 1 etcd, 1 cp
2. Create a standard user u1 and add the user in the cluster above as Cluster Owner
3. Install neuvector chart from explorer >> apps >> neuvector  feature chart
4. Navigate to the neuvector icon on left navugation
5. Copy the URL and open the url in a different browser
6. Login as the standard user u1

**Result**
Left navigation is empty

**Expected Result**
Left navigation is not empty

**Screenshots**
<img width="400" alt="neuvectorleftnavigation" src="https://user-images.githubusercontent.com/38144301/165853512-8569deca-e675-4182-a50f-27206471dd52.png">

**Comment by anupama2501** [comment]
@richard-cox and @nwmac standard user is added as the cluster Owner in the downstream clusters. Only cluster owners have permissions to access neuvector UI currently from Rancher.

**Comment by richard-cox** [comment]
Thanks @anupama2501 #5777 should fix the issue then. Standard users will be redirected to the cluster home page if they attempt to visit the dashboard neuvector page. For them the neuvector link is hidden, so it just applies when the url is directly used.

**Comment by anupama2501** [comment]
Verified on v2.6-head 054b5d1

left navigation loads as expected for both admin and cluster owners
