### ISSUE TITLE
rke1 clusters show as `ready` and `not ready` or `pending` at the same time (while provisioning or when a node is down)

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5771]
**Setup**
- Rancher version:v2.6.5-rc5
- Browser type & version: any (tested with chrome )

**Describe the bug**
for rke1 clusters, they display as both `ready` and a second state while provisioning or when a node is down. 

**To Reproduce**
* deploy an rke1 cluster
* watch the status on the `cluster management` page 

**Result**
* report shows all nodes in rke cluster as `active` as well as some/all in other states simultaneously

**Expected Result**
a given node will only have 1 state

**Screenshots**
<img width="1185" alt="Screen Shot 2022-04-28 at 2 35 42 PM" src="https://user-images.githubusercontent.com/16691014/165865591-80eb81a9-f815-4ca6-b152-b0cfb39ab970.png">

**Comment by richard-cox** [comment]
Raised in https://github.com/rancher/dashboard/issues/5443#issuecomment-1111400773 and has been resolved in 2.6 head

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `311f462`**

<img width="1410" alt="Screen Shot 2022-04-30 at 7 54 03 AM" src="https://user-images.githubusercontent.com/26032343/166110591-754087d8-891d-4497-8321-9ddd34a438a3.png">

Original issue is fixed.
