### ISSUE TITLE
Add support for AKS 1.23

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5781]
Currently we do not have AKS 1.23 listed in the kubernetes versions for AKS providers on rancher UI. 

Context:
https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli

**Comment by thedadams** [comment]
It looks like the UI makes a proxied request to Rancher and Rancher forwards this request to the Azure API and returns a list of versions. This list does include versions for v1.23+.

My guess is that the UI is just filtering out these versions.

**Comment by thedadams** [comment]
@codyrancher Looking at the backend code, it looks like this is something that is handled by KDM. You can close this issue. We have one for the backend already, linked above.

**Comment by codyrancher** [comment]
@thedadams done. Thanks for taking a look.
