### ISSUE TITLE
Add 1.22 for EKS v2 clusters

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#5782]
**Detailed Description**

- Add 1.22 for EKS v2 clusters

**Comment by gaktive** [comment]
This is a duplicate of https://github.com/rancher/dashboard/issues/5716. @Josh-Diamond if you can confirm that's the case, then we can close this.

**Comment by Josh-Diamond** [comment]
Duplicate of [5716](https://github.com/rancher/dashboard/issues/5716) - Closing this and further details will be tracked in issue #5716
