### ISSUE TITLE
Workloads with lots of ports and/or nodes scroll to the right

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5786]
Internal Ref: SURE-4471

When a workload has a lot of ports, the table does not display properly in the legacy UI.

![image](https://user-images.githubusercontent.com/1955897/166074356-4e773cfb-a1ba-48b6-b268-9ed7770da20b.png)

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head f4d09c7
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###

Tested this issue with the following steps:
1. Create workload with multiple ports
2. Go to Ember UI and view workload
3. Verify Name column is adjusted to fit multiple ports

**Result** - Pass

The table now resizes the Name column to fit all the ports

![image.png](https://zube.io/files/rancher/54751ebbe15975539ca725b99ad4e80d-image.png)
