### ISSUE TITLE
`Save RKE Template` option is seen for a Std user who is cluster owner

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5787]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**
`Save RKE Template` option is seen for a Std user who is cluster owner

**To Reproduce**

- Deploy an RKE1 cluster.
- Add user1 as cluster owner to this cluster
- login as user1
- `Save RKE Template` option is seen for a Std user who is cluster owner

**Expected Result**
`Save RKE Template` should NOT be available for cluster owner. In 2.5.13, this option is not available on Ember UI.

**Comment by aalves08** [comment]
Looking into this issue, permissions for visibility of the option are set in [models/provisioning.cattle.io.cluster](https://github.com/aalves08/dashboard/blob/master/shell/models/provisioning.cattle.io.cluster.js#L101-L106):

In this scenario, all conditions are met, so action is displayed, but as `user1` one get's an API error saying that he cannot save the RKE Template.

The strangest thing, for me, come from the actual roles:

**Clustertemplates-create**
<img width="1647" alt="Screenshot 2022-05-13 at 14 41 34" src="https://user-images.githubusercontent.com/97888974/168296590-d5f75d39-27c8-460b-952b-0735ede25e24.png">

Has  `management.cattle.io` for `apiGroups`, `clustertemplates` for `resources` and `create` for `verbs`. (all good here)

**Cluster owner**
<img width="1647" alt="Screenshot 2022-05-13 at 14 41 55" src="https://user-images.githubusercontent.com/97888974/168298396-2b6368d5-6b97-4655-91f7-baca67940645.png">

Has wildcard (*) for `apiGroups`, `resources` and `verbs`, which, in theory, unless I am missing something, will make the user to manage every resource, therefore, manage `clustertemplates`, right @richard-cox ?

Unless we have some other condition to be checked here (even the roles don't seem to help, but I might be missing something), there always the path that we don't want to go through much like the RBAC issue on Projects... 🙏 

Will await for some feedback. Thanks

**Comment by richard-cox** [comment]
@aalves08 UI should just be checking resource schema's (or actions/links within resource instances) if it can execute a change. Looking under the hood the request to make a template is an action on the norman cluster object 

```
 await this.$store.dispatch('rancher/request', {
          url:    `/v3/clusters/${ escape(this.cluster.name) }?action=saveAsTemplate`,
          method: 'post',
          data:   {
            clusterTemplateName:         this.name,
            clusterTemplateRevisionName: DEFAULT_REVISION
          },
        });
```

However when checking to show the option with use `this.hasLink('update')`. 

We should also check if the `saveAsTemplate` action is available... and if it is but shouldn't be then that's an additional issue that the BE should look at. It's also worth double checking how cluster manager gated the action

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head bca5ada
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE1 node driver

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy an RKE1 cluster.
2. Add user1 as cluster owner to this cluster
login as user1
3. `Save RKE Template` option is seen for a Std user who is cluster owner


**Result** - Pass
`Save RKE Template` option is no longer available for a Std user who is cluster owner
![image.png](https://zube.io/files/rancher/93d823799e7e6a38578152f0621cb44d-image.png)
![image.png](https://zube.io/files/rancher/a62da7fd55d3f17e5e1c7c0637d98f46-image.png)
