### ISSUE TITLE
Dialog to delete user doesn't handle < character in user's name

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5788]
Internal Ref: SURE-4571

Create a user with a '<' character in their name.

Go to delete the user - the confirmation dialog does not show the name correctly.

This is an HTML escaping issue

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.6.5**
<img width="1425" alt="Screen Shot 2022-06-03 at 2 12 43 PM" src="https://user-images.githubusercontent.com/26032343/171953676-982641c9-5e0e-442b-b88e-ba43485950c3.png">

**On 2.6head commit id: `79a3bcb`**
This is fixed
<img width="1395" alt="Screen Shot 2022-06-03 at 2 18 50 PM" src="https://user-images.githubusercontent.com/26032343/171954515-7b659b4e-e7bd-4d69-b1d7-bf24761146e6.png">
