### ISSUE TITLE
[UI]  - close button not visible

### ISSUE THREAD

**Issue by sebastienroul** [rancher/dashboard#5796]
Rancher UI v2.6.4

When importing resources via 
![image](https://user-images.githubusercontent.com/2582255/166164210-bab6679f-ff3e-4fdb-84a5-51d591bf9117.png)

When you have many resources imported (for example 20 or more), then the popup run down under the bottom of the screen without scroll : The bouton "close" is not visible anymore.

In the sample it is visible (I just put it to make you sure to know which bouton I talking about)
![image](https://user-images.githubusercontent.com/2582255/166164180-7978d365-7c84-4795-b8ac-3068eb6ce97a.png)

**Comment by rak-phillip** [comment]
@gaktive I'm transferring this to dashboard so that it can get more visibility

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head bca5ada
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
Tested this issue with the following steps:
1. Explore local cluster
2. Next to the Namespace drop-down list, click on `Import YAML` button
3. Create 20+ resources
```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: mytest1
spec: {}
status: {}
---
repeat for mytest2, mytest3, ..., mytest21
```
4. Click import
5. Verify that list in applied resource list is scrollable and does not run off the screen
6. Verify that close button is visible and is able to interact with the button

**Result** - Pass

The applied resource list is scrollable and does not run off the screen. User is also able to view the Close button and click the button to close the applied resource list.

![image.png](https://zube.io/files/rancher/a3f4f58558dc1888fdef55a0f9c933d6-image.png)
