### ISSUE TITLE
Individual Cluster Overview - Layout/Component Changes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#580]
The current layout is cramming too much info into the top boxes. To keep the "detail" view of the cluster more consistent with other components, let's move some of the content into a `DetailTop` component so then we can focus on just the bars in the page.

<img width="852" alt="Screen Shot 2020-04-28 at 3 09 57 PM" src="https://user-images.githubusercontent.com/3013118/80542734-6dca5b80-8962-11ea-8a4d-5ec4276ff147.png">

Summary of changes:
- [x] Move `Provider`, `Kubernetes Version`. `Nodes`, `Created` into DetailTop
- [x] Only have 3 columns for each item that is being counted, make the content in the columns in the center of each column
- [x]  Change "rsvd" to use "reserved" for CPU and Memory as we have more horizontal space
- [x] Fix the spacing so it's `<number> GiB`. Currently it's `<number>G iB`.

**Comment by westlywright** [comment]
The weird spacing on the suffix is in https://github.com/rancher/dashboard/pull/610 at this commit https://github.com/rancher/dashboard/pull/610/commits/881bdb406cde69154c8d966051a6a517212ccb2e

**Comment by deniseschannon** [comment]
the spacing eems to be fixed in a different commit, but is updated in master as of 5/8 3pm
