### ISSUE TITLE
`1Namespace Project Resource Availability tooltip missing from v2.6

### ISSUE THREAD

**Issue by neillsom** [rancher/dashboard#5807]
Hover tooltip describing project resources is not implemented in 2.6

<img width="1195" alt="2022-05-02_23-38-26" src="https://user-images.githubusercontent.com/13671297/166413700-bb132b82-fe14-44e8-9167-cfcf9918ef27.png">

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 68c6c13
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###

Tested this issue with the following steps:
1. Explore local cluster and go to Projects/Namespaces
2. Create project with resource quotas added 
3. Create namespace
4. Go to Resource Quotas tab
5. Hover over `Project Resource Availability` to view tooltip

**Result** - Pass

Tooltip is now visible in dashboard for v2.6
![image.png](https://zube.io/files/rancher/1bcf236ff3e3f7318afd34f1fc1e327c-image.png)
