### ISSUE TITLE
Hovering over hyperlinks scrolls page to top

### ISSUE THREAD

**Issue by klauskobald** [rancher/dashboard#581]
It happens in the menu and on the content view.
http://clients.kobald.com/misc/dashbord-scroll-bug.mov
So none of the links are accessable.

Safari on Mac

**Comment by deniseschannon** [comment]
@vincent99 With the updated nav, can you verify if this is still an issue?

**Comment by deniseschannon** [comment]
In 2.5, the UI/nav bar is changing but we are unable to reproduce in our current master builds.

**Comment by klauskobald** [comment]
seems to work now!
