### ISSUE TITLE
RFE: Code Generation Feature

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#5813]
# Description

As the Rancher UI is effectively an API client, it could be possible to `record` and `display` the API's called in a more user-friendly way compared to using developer tools inside the clients browser client.

# Workflow

1. User clicks a `record` button in the Rancher UI
2. User performs a number of activities - For example, creating cloud credentials, cluster, install an app from a repo, etc.
3. User clicks a `stop` button in the Rancher UI.
4. Rancher UI displays the API calls that were made during this time period.

# Value

Being able to easily extrapolate API calls for complex workflows could help in third party integration with automation solutions

SURE-4581

**Comment by richard-cox** [comment]
I'm not sure this is a good idea. The UI roughly uses three APIs. 

**Norman (`v3` / the old rancher API)**
This one should be documented somewhere in the official docs

**Steve (`v1` / the new rancher API)** 
Using this outside of the UI / other tools isn't supposed to be supported. Someone from the backend team can fill in the details but as it manages native resources the kube api should supersede it.

**Native Kube API**
This should be well documented

At any point in the UI we could have used a number of them to either get the information required to create the requests or to make them.

**Comment by catherineluse** [comment]
We often get requests for API documentation, but since the API is not supported, the official response is that Fleet and the Rancher2 Terraform provider are the only supported forms of automation.

With that said, we do already have a user preferences setting that already lets you enable the "View in API" feature for development purposes. Maybe we should extend that feature so that when the "Enable Developer Tools & Features" option is clicked, then you will also be able to record the API calls.

**Comment by richard-cox** [comment]
@catherineluse We should NOT generate API docs for un-supported APIs or APIs that have external documentation. We should not either encourage people to use those un-supported APIs. The only actions for Rancher should be improving `v3` docs and guides to our custom CRDs (which can be managed by the kube API).

The `View in API` site is generally there for internal/developer purposes as a workaround for features that aren't implemented or working as expected.

Browser 'Developer tools' already exists that clearly show the API calls the dashboard makes, it also has lots of cool features (filtering, display modes, recording, throttling, stats, etc) that we would have to re-implement.

**Comment by richard-cox** [comment]
Given the supported situation of the API's and that there's an existing, built-in tool in all browsers that already covers this I'm closing this issue
