### ISSUE TITLE
[project monitoring v2] prometheis objects when opened allow user to type in the yaml file without clicking 'edit yaml'

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5814]
**Setup**
- Rancher version: `2.6-head Commit ID eb03517`
- Browser type & version: `chrome latest`

**Describe the bug**
when opening an object in prometheis, the yaml opens. the user can click inside and make changes to the yaml. there's no save on this page, so it should be presenting the yaml, not allowing typing in the form. reasoning: if a user opens this view to edit the yaml, and makes changes, those changes are lost due to no save button. 

**To Reproduce**
1. monitoring > alerting > advanced > prometheis
2. click on an existing object - eg, rancher-monitoring-prometheis

**Result**
user can type in yaml form

**Expected Result**
user cannot type in the yaml form unless the user clicks 3 dots and selects 'edit yaml'

**Screenshots**
<img width="1610" alt="Screen Shot 2022-05-03 at 1 05 54 PM" src="https://user-images.githubusercontent.com/89212856/166504253-fa1a90d2-b0ab-4087-8f72-a7be8bd1b0d9.png">

**Comment by gaktive** [comment]
Need to confirm if this is happening in 2.6.4 since there has been no changes to the editor.

**Comment by ronhorton** [comment]
**Pass** verified in `2.6-head Commit ID 132b182`
1. monitoring > alerting > advanced > prometheis
2. click on an existing object - eg, rancher-monitoring-prometheis

cannot type in yaml view. required to edit for text entry. (as expected)
