### ISSUE TITLE
[project monitoring v2] newly created receivers don't show on the route: create page

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5818]
**Setup**
- Rancher version: `2.6-head Commit ID eb03517`
- Browser type & version: `chrome latest`

**Describe the bug**
After adding a new receiver in Monitoring > Alerting > Alertmanagerconfigs > alert, the receiver is not shown in  Monitoring > Alerting > routes and receivers deprecated page 

**To Reproduce**
1. Cluster > Monitoring > Alerting > Alertmanage configs
2. Click new alert
3. Click Add Receiver
4. Add unique Name
5. Select Webhook > Add webhook > sms > Create

**Result**
When checking the receivers page (deprecated) the receiver is not shown
**Expected Result**
receiver is shown wherever receiver list is presented

**Screenshots**
<img width="1617" alt="Screen Shot 2022-05-04 at 11 20 08 AM" src="https://user-images.githubusercontent.com/89212856/166714556-66b7ff07-b8b3-47c3-93a6-e8f0e74f0496.png">

<img width="1631" alt="Screen Shot 2022-05-04 at 11 20 18 AM" src="https://user-images.githubusercontent.com/89212856/166714590-89fd88ab-5f11-4d16-b338-885eb1eea069.png">

**Additional context**

**Detailed Description**

**Context**

**Comment by gaktive** [comment]
Possible wording: "Going forward, Routes & Receivers should not be configured as Kubernetes resources; they should be configured as YAML fields under the Alert Manager Configuration."

@btat this would need to be in the docs for Prometheus Federator. If you can come up a better wording, especially indicating that between v1 & v2 of Project Monitoring, you won't see items on one page on the other.

**Comment by ronhorton** [comment]
**Pass** verified in `2.6-head Commit ID cac23ea`

![Screen Shot 2022-05-06 at 3.52.08 PM.png](https://zube.io/files/rancher/e1479dccf0627f2ccdbd473b9c584e70-screen-shot-2022-05-06-at-3-52-08-pm.png)
