### ISSUE TITLE
Secrets - Design Feedback for TextArea inputs

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#582]
### Certificate Type
- [ ] Why are the private key/CA certificate inputs so much bigger than the other ones?

<img width="963" alt="Screen Shot 2020-04-29 at 11 25 55 AM" src="https://user-images.githubusercontent.com/11410997/80632501-3912de80-8a0c-11ea-8531-804283f10985.png">

**Comment by vincent99** [comment]
It would be a lot more useful to have subtype-specific detail views for different kinds of secrets and show things like some data parsed out of the cert instead of the raw text.  Issuer, Subject, validity period, etc.  2.x does this server-side for certs but there's probably x.509 JS parsers.

Or lower effort, show "1234 byte certificate" and "853 byte key" with copy-to-clipboard buttons instead of the content for known-ugly keys ("token", "*.crt", "*.key" and value.length > 100 or something like that).

**Comment by lvuch** [comment]
@deniseschannon  Re: cert types those are text area field so they are a little bit bigger to suggest multi-line input

**Comment by deniseschannon** [comment]
@lvuch I don't know if that actually indicates that the box is bigger means multi-line input.

**Comment by deniseschannon** [comment]
I've slowly removed my other issues in this ticket as they were addressed in other issues, but I'm not sure I agree that those text boxes should be bigger for multi-line input. Now that the sample text is in it, it might not be necessary to be bigger? Or we need more sample text that will show it in 2 lines? 

It still looks like it's the wrong height to me.

![Screen Shot 2020-05-04 at 4.06.19 PM.png](https://zube.io/files/rancher/44666c06236d713da03c4815064170a5-screen-shot-2020-05-04-at-4-06-19-pm.png)

**Comment by lvuch** [comment]
<img width="1213" alt="Screen Shot 2020-05-19 at 10 58 24 AM" src="https://user-images.githubusercontent.com/3013118/82361446-b30d0680-99bf-11ea-8092-9aad92bef88d.png">
<img width="1213" alt="Screen Shot 2020-05-19 at 10 57 53 AM" src="https://user-images.githubusercontent.com/3013118/82361450-b3a59d00-99bf-11ea-931f-5fbadd1bfde0.png">
<img width="1213" alt="Screen Shot 2020-05-19 at 10 57 19 AM" src="https://user-images.githubusercontent.com/3013118/82361451-b43e3380-99bf-11ea-8fd3-9904f2c5e2cc.png">

**Comment by deniseschannon** [comment]
Better than before:

![Screen Shot 2020-06-05 at 3.26.43 PM.png](https://zube.io/files/rancher/fd5f379273ebc9be411203bcb5b3ae89-screen-shot-2020-06-05-at-3-26-43-pm.png)

**Comment by vincent99** [comment]
This should say Certificate (and maybe additional chain certs), you're not providing a CA certificate.
