### ISSUE TITLE
[Enhancement] Add Storage Options and Log Options fields to RKE1 Node Template Creation Modal

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/dashboard#5821]
This issue is being raised alongside this associated PR: https://github.com/rancher/rancher/pull/37583, and is regarding this rancher/rancher issue: https://github.com/rancher/rancher/issues/28859

**Detailed Description**

Add two new fields to the RKE1 Node Template creation modal titled "Storage Options" and "Log Options". These fields should look similar to the currently existing `Engine Options` field within the `Engine Options` drop down.  These fields would allow users to specify their storage and logging configuration options by passing key-value pairs. 

![Screen Shot 2022-05-04 at 1 46 28 PM](https://user-images.githubusercontent.com/25062254/166754617-334550ca-3a94-4648-8306-184e4ef9d4cc.png)

**Context**

Customers have encountered issues when trying to configure log-drivers and storage-drivers inside of the `Engine Options` field when creating RKE1 Node Templates. Currently, you cannot specify a key multiple times within the `Engine Options` field, which prevents users from setting up log limits or any advanced storage-driver configuration from within the UI. The addition of these two new fields, along with the backend PR linked above, would allow users to specify all of the log-driver and storage-driver options desired within the UI when creating an RKE1 Node Template.

**Comment by Josh-Diamond** [comment]
Ticket #5821 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-da21dbb6f3ac5e0ede98f469d95ed2b0d323ba5c-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE1 AWS Node driver cluster, and observe `Add Storage Options` and `Add Log Options` fields under `Node Template > Engine Options`
3. Verified

Screenshot:
<img width="917" alt="Screen Shot 2022-07-20 at 10 32 03 AM" src="https://user-images.githubusercontent.com/46494969/180046393-acc2675f-361b-49e5-b54e-6f57db50533e.png">
