### ISSUE TITLE
[project monitoring v2] Project Monitor Project Metrics do not load

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5826]
**Setup**
- Rancher version: `2.6-head Commit ID 054b5d1`
- Browser type & version: `chrome latest`

**Describe the bug**
When I go to the Project Metrics tab in Project Monitor Detail Page, the graphics never load

**To Reproduce**
1. Cluster > Monitoring > Project Monitor
2. click on existing project monitor
3. graphics stuck at `Loading...`

**Result**
Graphics don't load
Error:
`VM330:1          GET https://projmonv2test.qa.rancher.space/k8s/clusters/c-56pgn/api/v1/namespaces/cattle-project-p-dsvdp/services/http:cattle-project-p-dsvdp-monitoring-grafana:80/proxy/api/dashboards/uid/rancher-pod-1`**404**

**Expected Result**
Beautiful graphics

**Screenshots**

<img width="1601" alt="Screen Shot 2022-05-04 at 6 02 40 PM" src="https://user-images.githubusercontent.com/89212856/166833017-1c91bdf6-3a71-405f-9456-bb193b584832.png">

**Comment by gaktive** [comment]
@ronhorton to try this with the non-dev chart today and report back if this happens again since it sounds like an anomaly.

**Comment by Sean-McQ** [comment]
Looked at this with @ronhorton on a call today and after looking in Grafana itself, there didn't appear to be any dashboards listed for the Grafana instance which would result in a 404 like what we're seeing here.

**Comment by ronhorton** [comment]
fixed
