### ISSUE TITLE
Shift + click behavior to select multiple items in lists is buggy

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#5827]
**Setup**
- Rancher version: 2.6-head
- Browser type & version: Chrome

**Describe the bug**
When using Shift + click to select multiple items in lists in Rancher the count of selected items shows incorrect and "select all" behavior is incorrect.

**To Reproduce**

1. Navigate to any list in Rancher that allows selecting multiple items
2. Select any not last item by clicking on the corresponding checkbox <img width="956" alt="image" src="https://user-images.githubusercontent.com/85187633/166842071-182a5b4a-6935-4dba-84f2-7138cfda248e.png">
3. Shift + click on a checkbox for any item below. <img width="956" alt="image" src="https://user-images.githubusercontent.com/85187633/166842530-ccba0a70-fda0-47a2-8983-58eefdb381ec.png">
4. Result 1: The label showing total number of items selected is off by 1 (if can be off by more than 1 if more than one item is selected before shift + clicking)
5. Then, click on checkbox in list header (the expectation is all items will get deselected): <img width="956" alt="image" src="https://user-images.githubusercontent.com/85187633/166842756-22c1d233-0361-4067-bf91-e0e5ca4bed30.png">
6. Result 2: The item selected at step 2 is still selected and the header checkbox state is still "partly selected".

**Expected Result**
The count of items selected and the "X selected" label should match.
Also, "select all" header checkbox should behave the same way regardless of whether Shift + click was used to select items.

**Comment by aalves08** [comment]
Hi @timhaneunsoo .

The changes done on this issue does not cover the Ember UI (in reality they are separate projects)

I would say that you should open a new issue specific to the Ember UI and move this on forward if you agree.

Thanks! 🙏

**Comment by timhaneunsoo** [comment]
Closing based on @aalves08 comment
