### ISSUE TITLE
"Drain on Upgrade" should be "No" by default for RKE2

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#5829]
**Detailed Description**
"Upgrade Strategy -> Control Plane (or Worker Nodes) -> Drain Nodes" default was switched to "Yes" per https://github.com/rancher/dashboard/issues/5618, however, this was due to taking https://github.com/rancher/rancher/issues/36969#issuecomment-1093440709 a bit too far. We only need "Delete pods using emptyDir volumes" to be checked by default if "Drain Nodes" is set to "Yes" to avoid running into issue from the comment linked.

**Context**
RKE1 provisioned clusters default to "Drain Nodes on Upgrade" as "No", so making this change ensures default RKE2 provisioning settings more closely match defaults for RKE1.
Note this change will also reduce the impact of https://github.com/rancher/rancher/issues/37597 as default for "Drain Nodes" will match between backend and UI (it will still be reproducible for "Delete pods using emptyDir volumes" case though).

**Comment by Josh-Diamond** [comment]
Ticket #5829 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.5-rc3`:
1. Fresh install of rancher `v2.6.5-rc3`
2. Provision a downstream RKE2 cluster
3. Once provisioned, view cluster's config
4. Reproduced - `Drain on Upgrade` is set to `Yes` by default

Screenshot:
`Step 4`
<img width="1641" alt="Screen Shot 2022-05-05 at 9 59 07 AM" src="https://user-images.githubusercontent.com/46494969/166974758-b398a228-7c2c-4bf4-9bd1-14b26dbbdedb.png">

---
Verified on rancher `v2.6-4bbee5995053eb52ef447ca82de2c90b1af8b21a-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 cluster
3. Once provisioned, view cluster's config
4. Verified - `Drain on Upgrade` is set to `No` by default; 
5. Verified - If `Drain on Upgrade` is switched to `Yes`, `Delete pods using emptyDir volumes` is enabled [by default]

Screenshots:
`Step 4`
<img width="1669" alt="Screen Shot 2022-05-05 at 9 36 18 AM" src="https://user-images.githubusercontent.com/46494969/166971950-dc8a846f-2d92-4184-a1d7-d98497b28944.png">

`Step 5`
<img width="1636" alt="Screen Shot 2022-05-05 at 9 37 21 AM" src="https://user-images.githubusercontent.com/46494969/166971986-951535cf-6cd8-47e4-ba1b-42a4158ccbc6.png">
