### ISSUE TITLE
Service - Create/Edit Page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#583]
Requirements from reading: https://kubernetes.io/docs/concepts/services-networking/service/

## Top Section 
Normal Header - `MastHead`

Name/Description/Type - `NameNsDescription` with an added `Type` dropdown.

Note: The `Type` dropdown should allow free form text as well.

**Type** dropdown fields:
Dropdown Display | Dropdown Value | YAML value
---|---|---
Cluster IP (Default) | `ClusterIP` | `spec.type.ClusterIP`
External Name | `ExternalName` | `spec.type.ExternalName`
Headless | `ClusterIp`| `spec.type.ClusterIP` and `spec.clusterIP: "None"`
Load Balancer | `LoadBalancer` | `spec.type.LoadBalancer`
Node Port | `NodePort` | `spec.type.NodePort`

> Note: For `Headless type, it should send `"None"` for the `spec.clusterIP` field specifically. This won't be visible anywhere in the UI, but this is what defines a Headless Service. 

## Main Section
The form will change baed on `Type`

### Cluster IP Type/ Headless Type/[Node Port Type](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport)/[Load Balancer Type](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer)

Note: Example Inputs directly from k8s docs

For LoadBalancer Type, if more than 1 rule is specified, it must have all the same protocol in all rules. 

**Port Rules** - `spec.ports` - Use one component that allows you to add multiple/remove port rules. 

Service Type | Name | k8s yaml location | Field Type | Example Input
---|---|---|---|---
Cluster IP, Headless, Node Port, LoadBalancer | Port Name | `spec.ports.name` | Textbox that only allows lowercase alpha numeric characters and `-` and cannot start or end with `-` | `e.g. myport`
Cluster IP, Headless, Node Port, LoadBalancer | Listening Port | `spec.ports.port` | Textbox for integers only | `e.g. 80`
Cluster IP, Headless,  LoadBalancer | [Protocol](https://kubernetes.io/docs/concepts/services-networking/service/#protocol-support) | `spec.ports.protocol` | `Cluster IP` and `Headless` type dropdown options: `TCP`, `UDP`, `HTTP`, `PROXY`.  `LoadBalancer` type dropdown options: `TCP`, `UDP`.  | Default is `TCP`. 
Cluster IP, Headless, Node Port, LoadBalancer | Target Port | `spec.ports.targetPort` |  Textbox. When submitting the service, if nothing is set in Target Port, use the same value as the listening port. Potentially make helper text "Same as listening port" that doesn't show you to edit unless you explicitly want to change it. This is what is done in Ember | `e.g. 9376`
Node Port | Node Port | `spec.ports.nodePort` | This only shows up for `NodePort` type. Optional textbox for integers only. If possible to put a hint/note `By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767), if nothing is set.` | `e.g. 30007`

### `ExternalName` Type

Helper/Note Text -"External Name is intended to specify a canonical DNS name. To hardcode an IP address, use a `Headless` service."

**Fields**
Service Type | Name | k8s yaml location | Field Type | Example Input
---|---|---|---|---
 ExternalName | Target Hostname | `spec.externalName` | Textbox that only allows valid DNS names | `e.g. my.database.example.com`

###  Tabs - Use `ResourceTabs` which contains Labels and Annotations tabs

Service Type | Tab Name | k8s yaml value | Field Notes
---|---|---|---
 Cluster IP, NodePort, LoadBalancer | Selector | `spec.selector`  | 
All Types | IPs| `spec.clusterIP` and `spec.externalIPs` | Ability to set Cluster IP and Ability to add/remove multiple “External IPs”  
Cluster IP, Node Port, Load Balancer | Session Affinity | `spec.sessionAffinity`  | See below for content in tab
All Types | Labels | `labels` | Use ResourceTabs component which includes labels tab by default 
All Types | Annotations | `annotations` | Use ResourceTabs component which includes annotations tab by default 

**Selector Tab Content** 

KeyValue Component. Example for label: `e.g. app` and Example for value: `e.g. MyApp`

Helper Text: If no selector is created, manual endpoints need to be made, ability to create an endpoint.

**IPs Tab Content** 

Helper Text: `The IP address must be within the CIDR range configured for the API server.`
Service Type |Name | k8s yaml location | Field Type | Example Input
---|---|---|---|---
Cluster IP, LoadBalancer | Cluster IP | `spec.clusterIP` | Textbox | `e.g. 10.0.171.239`
All Types | External IPs | spec.externalIPs`| Ability to add/remove IPs via textbox | 

**Session Affinity Tab Content**
Helper Text in tab: `Map connections to a consistent target based on their source IP`

Name | k8s yaml location | Field Type | Example Input
---|---|---|--- 
Session Affinity | `spec.sessionAffinity` | Radio button with options `None` and `ClientIP`. Default is `None`. If `ClientIP` is selected, set spec.sessionAffinity to `"ClientIP"`.   | 
Session Stick Time | `service.spec.sessionAffinityConfig.clientIP.timeoutSeconds` | Textbox that shows when sessionaffinity is set to `ClientIP`. Should have label that shows that seconds is the measurement.| `e.g. 10800`

<img width="1199" alt="Screen Shot 2020-04-28 at 10 01 33 PM" src="https://user-images.githubusercontent.com/11410997/80562233-fb766d00-899b-11ea-8dd8-07aa6421cea1.png">

**Comment by deniseschannon** [comment]
@lvuch Can we do a mock for each service type?

**Comment by lvuch** [comment]
https://xd.adobe.com/view/f5adf6d8-2cac-4483-5818-fd7f5e150424-839c/

**Comment by deniseschannon** [comment]
- [ ] Labels and Annotations should always be the last tabs

## Port Rules
- [ ] Target Port/Node Port Headers should be left justified and not centered
- [ ] Expand Port rules so at least 1 is shown when you go to create. Do not allow to delete the last port rule. 

<img width="1138" alt="Screen Shot 2020-05-18 at 10 04 47 PM" src="https://user-images.githubusercontent.com/11410997/82286884-ab177d00-9953-11ea-8613-7c42a5ea284e.png">

- [ ] Target Name must be a DNS Label. Do we have the ability to check if it's a DNS label? 
- [ ] Target Port can actually be a name or number. The example text should be `e.g. 80 or http`.

- [ ] [Target Port should be hidden for Headless services.](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L4052) It should be omitted for Headless Service (when clusterIP=None). 

- [ ] Protocol API supports only `TCP`, `UDP` and `SCTP` with default as `TCP`. This contradicts the [docs](https://kubernetes.io/docs/concepts/services-networking/service/#protocol-support), but we should follow the API. 

- [ ] Node Port should be shown for type NodePort or LoadBalancer

## Selectors Tab
- [ ]. Ability to show number of pods that match the labels. If this is possible, add a column for Matching Pods that would start with 0 and update based on pods that match the label. 
- [ ] Applicable to `NodePort`  type

## IPs Tab
- [ ] Update tab name from `IPs` to `Listener IPs`
- [ ] Need tooltip next to `External IPs`  as `List of IP addresses for which nodes in the cluster will also accept traffic for this service.`
- [ ] For ClusterIP type, update the helper text for Cluster IP to say `The Cluster IP address must be`. Also move it from text in the tab to a tool tip for the field. 
- [ ] Helper Text in tab should say `Warning: Configuring additional listener IPs is an advanced use case.`
- [ ] Cluster IPs is also available for `NodePort` type
- [ ] Remove the dividing line between ClusterIP and External IPs

<img width="1135" alt="Screen Shot 2020-05-18 at 10 29 08 PM" src="https://user-images.githubusercontent.com/11410997/82288297-09922a80-9957-11ea-88b5-3cc250c974a0.png">

## Session Affinity Tab
- [ ] Remove for Headless type

**Comment by westlywright** [comment]
@deniseschannon re `Target Name must be a DNS Label. Do we have the ability to check if it's a DNS label?` This should be happening on the backend in the validation logic. We can add it but its an anti-pattern for the UI. Once we start the lines start blurring about what validation should be done where and if we're validating on the backend and the front we're duplicating effort. Ember/Norman do almost all the validation on the backend.

**Comment by deniseschannon** [comment]
@westlywright I believe there is validation within k8s, but there validation code errors are very unfriendly. We can leave it for now.

**Comment by vincent99** [comment]
Yes k8s will give you an unreadable regex.  The openapi schema will say it's a string but there's no additional info or generic way to know what particular format of value a particular field wants; this was effectively hardcoded additional rules in Norman.

There's not really much point encoding that info into the API instead of the UI now, since the Steve API is intended only for the UI; so for better validation we should just be able to add more specific hints to models for validation (which doesn't exist at all yet...) to look at.

**Comment by westlywright** [comment]
We already have a validation [request ticket open](https://github.com/rancher/dashboard/issues/189) so I will be using that to track validation changes.

**Comment by deniseschannon** [comment]
@lvuch we need to move this to the wizard style.

**Comment by deniseschannon** [comment]
Wizard Steps

Step 1: Select Workload Type
Step 2: Define Service 
 - Port Rules Section and Selector tab, Labels, Annotations
Step 3: Advanced  
 - Other Tabs (Listener Ips, Session Affinity)

**Comment by deniseschannon** [comment]
Any issues with this will be filed separately. Starting with https://github.com/rancher/dashboard/issues/966

Followed the new creation process: 

All resources are moving to the following creation workflow:

1. If there are subtypes for a resource, select the subtype.
2. Define the resource with the tabs moved to a vertical sidebar. Ability to create from the form.
3. Ability to review the YAML and make changes before create.

Edit Workflow:

Ability to either edit through form or through yaml from the menu action.
https://xd.adobe.com/view/a6c990fb-2efd-4444-b999-96111772c11c-f39a/screen/4209c6d7-a395-4019-b2dd-da9d25d753a4
