### ISSUE TITLE
Set local-path to default storageclass failed, no error message from ui

### ISSUE THREAD

**Issue by ly5156** [rancher/dashboard#5831]
**Setup**
- Rancher version: v2.6.3 v2.6.4
- Browser type & version: chrome 100.0.4896.127(arm64)

**Describe the bug**

Set `local-path` to default storageclass failed, no error message from ui

**To Reproduce**

1. Install https://github.com/rancher/local-path-provisioner
2. Click on the left menu `Storage -> storageclasses`, go to the storageClasses  page
3. Click on the name (`local-path`) link to go to the detail page
4. Click on the left menu `Storage -> storageclasses`, go back to the storageClasses page
5. Click on the `local-path` drop-down menu `Set as Default`

**Result**
The request reports error 422, but the UI shows that it is set to default
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/3406205/166857955-a8984efd-bebc-4191-98f0-7f745d186f43.png">

**Expected Result**

`local-path` storage class Set as default storage class

**Screenshots**

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/3406205/166858397-86a6c13f-a64a-454c-a476-aaa5849bdee3.png">

**Comment by gaktive** [comment]
@nwmac able to repro based on the steps provided. From the list page, if you don't go into the detail view, the Set as Default works correctly. But if you click on the detail for the `local-path` and go back one page, you get the 422. An "unprocessible entity" message appears. 

This points to something going on tied to `local-path`. This is similar to a problem we have with resizing volume claim whereby we're saving the whole object when we should be patching the annotation to indicate that it's a default or not. This is handled by the storageclass, which is being fussy by not allowing you to change a property.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 102.0.5005.61

----------

### Testing: ###

Tested this issue with the following steps:
1. Install https://github.com/rancher/local-path-provisioner
2. Click on the left menu Storage -> storageclasses, go to the storageClasses page
3. Click on the name (local-path) link to go to the detail page
4. Click on the left menu Storage -> storageclasses, go back to the storageClasses page
5. Click on the local-path drop-down menu Set as Default

**Result** - Pass

UI shows that `local-path` storage class is set as Default and the request is also successful
![image.png](https://zube.io/files/rancher/b2115148f7abc87cc5e3cbb6fedff6d9-image.png)
