### ISSUE TITLE
Add detail view for Persistent Volume Claims

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5836]
UX design needed

There is no detail view for PVCs

**Comment by catherineluse** [comment]
Closed as completed because I see an existing detail view for PVCs: 

<img width="1237" alt="Screenshot 2022-11-04 at 3 19 05 PM" src="https://user-images.githubusercontent.com/20599230/200083154-81f5c549-5a6d-4f7a-b509-b523dc2cd3ce.png">
