### ISSUE TITLE
Hide Mgmt Cluster type from Cluster Mgmt Advanced section

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5839]
Internal Reference: SURE-4257

We currently show 'Mgmt Clusters' in the advanced section of the Cluster Management area of the UI - this can be confusing.

Most users do not need to access this - if they do they can go to the local cluster and find the type there.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head bca5ada
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 101.0.4951.67 

----------

### Testing: ###

Tested this issue with the following steps:
1. Go to Cluster Management --> Advanced
2. Verify `Mgmt Clusters` is no longer showing under Advanced section

**Result** 

`Mgmt Clusters` is no longer showing under Advanced section

Before fix:
![image.png](https://zube.io/files/rancher/312af0d0d1cde54728786e0f313470ad-image.png)

After fix
![image.png](https://zube.io/files/rancher/36fed2b2c418b683da1c7e8a2b1fac23-image.png)
