### ISSUE TITLE
Ember: Can't distinguish checked radio button in view mode

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5844]
Internal Ref: SURE-2985

In the Ember UI, checked radio buttons can not be distinguished in view mode, e.g.

<img width="550" alt="Screenshot 2022-05-05 at 15 40 56" src="https://user-images.githubusercontent.com/1955897/166951294-4446705f-f0c1-4e3b-8303-8afc58be904b.png">

**Comment by nwmac** [comment]
PR: https://github.com/rancher/ui/pull/4838

**Comment by sowmyav27** [comment]
**On 2.6.6**
<img width="1269" alt="Screen Shot 2022-07-20 at 7 45 06 PM" src="https://user-images.githubusercontent.com/26032343/180118974-00ba8fb5-9b11-4cf2-9429-3e7fcd42f343.png">

---

**On 2.6-head commit id: `c47178e`**
<img width="1280" alt="Screen Shot 2022-07-20 at 7 45 11 PM" src="https://user-images.githubusercontent.com/26032343/180119032-2bd7bdba-cb45-4efd-be16-a9392a6b4472.png">
