### ISSUE TITLE
2.5 Backport AzureAD auth provider hardcoded Graph API endpoints

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#5846]
Backport:
rancher/dashboard#5671

In 2.5, auth is managed through Ember but exists in the dashboard. We will need to investigate the state of dashboard auth in 2.5 to determine how to backport this fix: it may be easier to disable Ember auth and direct users to the dashboard.

**Comment by gaktive** [comment]
2.5.x is now EOL so closing as won't fix: https://www.suse.com/support/kb/doc/?id=000020631
