### ISSUE TITLE
Rancher logging cannot match `Outputs` in the same namespace

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#5867]
**Setup**
- Rancher version: v2.6.4
- Browser type & version: Chrom 101.0.4951.54

**Describe the bug**

Cannot select Outputs in the same namespace

**To Reproduce**

1. Enable logging in the downstream cluster
2. Create `Outputs`
3. Create `Flows` and select the `Outputs` created in the previous step

**Result**
Could not match `Outputs` in the same namespace, prompt: `Sorry, no matching options`

**Expected Result**

`Outputs` in the same namespace can be selected in `Flows`

**Screenshots**

<img width="1782" alt="image" src="https://user-images.githubusercontent.com/19684717/165669634-6ad7a9b8-10c1-4c6c-8b1e-687c01da2373.png">

<img width="1786" alt="image" src="https://user-images.githubusercontent.com/19684717/165669660-0c9ef39f-7124-41c0-8c8c-126db628e347.png">

**Additional context**

This issue is only reproduced in Rancher v2.6.4, works fine in v2.6.3

**Comment by hackdefendr** [comment]
I can reproduce this with a fresh Rancher installation done minutes ago. My output is in the 'default' namespace but I don't see it when configuring the flow.

**Comment by markusewalker** [comment]
Verified that this is resolved in `v2.6.5-rc8`.

**ENVIRONMENT DETAILS**
- Ubuntu 18.04: Rancher HA
- Ubuntu 20.04: RKE2 Cluster (3 etcd, 2cp, 3 workers)
- Rancher version: `v2.6.5-rc8`
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigated to Rancher UI.
2. Created a standard user and logged in to Rancher as that user.
3. Created a downstream RKE2 cluster with following configuration: 3 etcd, 2 cp, 3 workers.
4. Navigated to that freshly-created cluster > Apps > Charts and enabled `Logging` in the cluster.
5. Once successful, navigated to Logging > Outputs and create an output.
6. Created a flow and select the previously-created output.
7. Verified the resulting `Outputs` matches in the same namespace created in `Flows`:
![image](https://user-images.githubusercontent.com/52591819/167454505-4b4c6be1-c1b7-4ec1-9316-159b874efd4b.png)
8. Additionally, verified that I can create the resulting output and the namespace appears as well:
![image](https://user-images.githubusercontent.com/52591819/167454551-03f38939-a47c-4eb5-a67a-6d86f8a5a3fe.png)
9. Repeated steps 6-7 with different providers multiple times and verified that all of the different namespaces appear:
![image](https://user-images.githubusercontent.com/52591819/167454582-bc1ebf0a-5dee-4345-9f6f-53bf32d36077.png)
![image](https://user-images.githubusercontent.com/52591819/167454602-9381a63f-e4f5-4fa1-9879-dae7f37e1a4a.png)

**Comment by sehsanm** [comment]
Is there any workaround without updating to 2.6.5?
