### ISSUE TITLE
Switch the language to Simplified Chinese, and the browser console reports an error

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#5868]
**Setup**
- Rancher version: v2.6.4
- Browser type & version: Chrom 101.0.4951.54

**Describe the bug**

When the language is switched to Simplified Chinese, the browser console reports an error, and the namespace cannot be switched

**To Reproduce**

1. Switch the language to Simplified Chinese(简体中文)
2. Access the local or downstream cluster

**Result**
The browser console will report an error and cannot switch namespaces
```
Error: The intl string context variable "更多" was not provided to the string "+{更多}"
    at new e (formatters.js:25:28)
    at K (formatters.js:86:19)
    at W (formatters.js:174:17)
    at t.format (core.js:61:20)
    at Object.<anonymous> (i18n.js:103:24)
    at c (i18n.js:5:37)
    at f.o.default.t (i18n.js:28:10)
    at f.r (NamespaceFilter.vue?17b9:1:1519)
    at f.t._render (vue.runtime.esm.js:3548:22)
    at f.r (vue.runtime.esm.js:4066:21)
```

**Expected Result**

There are no errors in the browser console and namespace switching works fine

**Screenshots**

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/19684717/167254838-b667c884-9d58-4df4-bc4e-be219ffda2b6.png">

**Additional context**

**Detailed Description**

**Context**

**Comment by Josh-Diamond** [comment]
Ticket #5868 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.4`:
1. Fresh install of rancher `v2.6.4`
2. Provision a downstream cluster - [ANY]
3. Switch language preference in Rancher from `English` to `Simplified Chinese`
4. View downstream cluster's `Cluster Explorer` page
5. Attempt to change namespace selected in filter
6. Reproduced - UI is `frozen` with error in console

Screenshot:
`Step 6`
<img width="1695" alt="Screen Shot 2022-05-09 at 9 44 46 AM" src="https://user-images.githubusercontent.com/46494969/167460253-0016f5df-8e57-4bc4-9fd3-a17bfdf215b5.png">

---

Verified on rancher `v2.6-628b1b97009ef76a425380564fa73eb26a5ef280-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream cluster - [ANY]
3. Switch language preference in Rancher from `English` to `Simplified Chinese`
4. View downstream cluster's `Cluster Explorer` page
5. Attempt to change namespace selected in filter
6. Verified - UI as expected; Clean console logs

Screenshot:
`Step 6`
<img width="1691" alt="Screen Shot 2022-05-09 at 10 14 11 AM" src="https://user-images.githubusercontent.com/46494969/167462495-13823d9e-d79e-440e-a101-16bc38a5535f.png">
