### ISSUE TITLE
Receiver form allows invalid input for some secrets

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5875]
In the new receiver form for project monitoring, the YAML isn't cleared out properly when you change a secret from an existing secret to none.

I already fixed this behavior for the httpConfig and tlsConfig secrets. It's just a matter of porting the fix over to a few other fields, but I ran out of time.

To reproduce:

1. Create an AlertmanagerConfig
2. Within the AlertmanagerConfig, create a receiver. Let's call it `slack-test`
3. In the `Secret with Slack Webhook URL` field, select any secret and select a key with the secret.
4. Save the receiver.
5. Go to edit the receiver again, and this time set `Secret with Slack Webhook URL` to `None`.
6. Click Edit as YAML
7. See that the result of setting the secret to none is like this:

```yaml
slackConfigs:
        - apiURL:
            key: username
            name: __[[NONE]]__
```
The expected behavior is for the whole value to be cleared out if no secret is selected. The `apiURL` field should just be deleted.

The workaround is to delete the values in YAML.

The affected secrets are the same ones I added in this PR, except for the ones in the httpConfig: https://github.com/rancher/dashboard/pull/5772 (The secrets I added in this PR are not affected: https://github.com/rancher/dashboard/pull/5850)

**Comment by catherineluse** [comment]
Can't test my PR until a routing bug is fixed

**Comment by catherineluse** [comment]
# QA Template
## Root cause
Didn't finish writing the code for clearing secrets when set to None
 
## What was fixed, or what changes have occurred
When you are filling out a receiver form within an AlertmanagerConfig, the following 5 secrets are now cleared when set to None:

- Email
  - auth password secret
- Opsgenie
  - API key secret
- PagerDuty (note: only one of these secrets can be seen at a time)
  - routing key secret
  - service key secret
- Slack
  - API URL secret
 
## Areas or cases that should be tested
Making sure YAML is still valid and can be saved when the above 5 secrets are set to None
 
## What areas could experience regressions?
Can't think of any

**Comment by ronhorton** [comment]
reopening after following steps and not seeing expected behavior
version tested `2.6.6-rc2`

1. created receiver
2. added slack 
3. selected token
4. edited yaml to change name: none
5. saved
6. edit yaml

apiURL field remains
![Screen Shot 2022-06-27 at 1.34.40 PM.png](https://zube.io/files/rancher/9bcf8f439a4f9adc12b265a9985c8b69-screen-shot-2022-06-27-at-1-34-40-pm.png)

**Comment by ronhorton** [comment]
Not seeing expected behavior when testing

**Comment by catherineluse** [comment]
I just tried it again and I don't see the behavior in your screenshots. When I have an API url configured for the Slack receiver it shows up:
<img width="593" alt="Screen Shot 2022-07-12 at 12 29 12 AM" src="https://user-images.githubusercontent.com/20599230/178434166-70a81509-a8a3-4a96-b869-12b5aa10b8ce.png">

And then when I set the secret to None from the form view, then go to the YAML view, the API url is gone:

<img width="744" alt="Screen Shot 2022-07-12 at 12 29 28 AM" src="https://user-images.githubusercontent.com/20599230/178434215-27d42bf0-9e66-4fe1-a12d-f852b7a3caad.png">

It seems that if you go to the YAML view first and then save, it works. But if you set it to none, then save without looking at YAML, it doesn't work.

**Comment by ronhorton** [comment]
**Pass** Verified in `2.6-head commit ID 2c21373`

1. installed monitoring
2. installed alerting
3. created alertmanager config
4. added receiver for slack with auth: token
5. edited yaml and see apiURL section in yaml
6. saved
7. checked yaml and verified yaml was saved
8. edit config again on slack receiver
9. changed auth to 'none' on form
10. switched to yaml and verified that apiURL section was gone. 
11. saved and rechecked
12. confirmed change was saved 
<img width="610" alt="2022-07-14_15-22-26" src="https://user-images.githubusercontent.com/89212856/179067502-fcb1e47c-a4f8-46a4-ab25-ecbe65dce692.png">

<img width="770" alt="2022-07-14_15-24-20" src="https://user-images.githubusercontent.com/89212856/179067740-ba423a05-0e20-40c0-bb54-89a2c14ec89b.png">
