### ISSUE TITLE
Editing receiver as YAML results in a blank page

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5877]
When you configure a receiver within an AlertmanagerConfig, you can create/edit form the form and save it and it works properly.

However, if you save it as YAML, you get directed to a blank page.

The YAML is saved correctly. It's just the routing that is incorrect.

Note: This bug is not seen if you go to Edit as YAML from clicking the action menu in the receiver list view. It is only seen when you first go to Edit Config and then switch to Edit as YAML from there.

## Workaround

The workaround is to click the back button once or twice to get back to the receiver detail page or the AlertmanagerConfig page, respectively.

## Screenshots
Editing the receiver as YAML:
<img width="1205" alt="Screen Shot 2022-05-09 at 10 53 04 AM" src="https://user-images.githubusercontent.com/20599230/167469140-16852425-df12-47ac-90ac-0c28e6338eb4.png">

Saving results in:
<img width="1165" alt="Screen Shot 2022-05-09 at 10 53 11 AM" src="https://user-images.githubusercontent.com/20599230/167469159-4881ef20-4517-42be-a37c-3f629983e16b.png">

The fix is to pass the receiver name into the query params (if we want it to go to the receiver detail page) or to route it back to the AlertmanagerConfig detail page.

**Comment by ronhorton** [comment]
Still seeing this in `2.6-head Commit ID 132b182`

1. created an alertmanagerconfig
2. clicked on alertmanagerconfig
3. clicked 'add receiver'
4. completed form
5. changed to `edit yaml`
6. saved

Page Not Found. Had to navigate back to dashboard.
When navigating to Cluster > monitoring > alerting > alertmanagerconfigs and clicking on the existing alertmanagerconfig, there isn't a receiver loaded. multiple errors in console

`vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'map')
    at f.data (index.vue:53:1)
    at f.<anonymous> (vue.runtime.esm.js:1219:51)
    at vue.runtime.esm.js:4748:17
    at vue.runtime.esm.js:4705:7
    at An (vue.runtime.esm.js:4642:5)
    at f.t._init (vue.runtime.esm.js:5006:5)
    at new f (vue.runtime.esm.js:5154:12)
    at vue.runtime.esm.js:3283:10
    at init (vue.runtime.esm.js:3114:45)
    at vue.runtime.esm.js:5978:9`

`TypeError: Cannot read properties of null (reading 'concat')
    at f.optionList (vue-select.js:1:10261)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.optionList (vue.runtime.esm.js:4836:17)
    at filteredOptions (vue-select.js:1:12284)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.filteredOptions (vue.runtime.esm.js:4836:17)
    at f.<anonymous> (vue.runtime.esm.js:503:13)
    at _n.get (vue.runtime.esm.js:4479:25)`

`vue.runtime.esm.js:1888 TypeError: Invalid attempt to spread non-iterable instance
    at t.exports (vue-select.js:1:2019)
    at t.exports (vue-select.js:1:1255)
    at findOptionFromReducedValue (vue-select.js:1:15008)
    at f.setInternalValueFromOptions (vue-select.js:1:13481)
    at f.created (vue-select.js:1:13221)
    at Qt (vue.runtime.esm.js:1854:57)
    at cn (vue.runtime.esm.js:4219:7)
    at f.t._init (vue.runtime.esm.js:5008:5)
    at new f (vue.runtime.esm.js:5154:12)
    at vue.runtime.esm.js:3283:10`

![Screen Shot 2022-05-10 at 2.28.41 PM.png](https://zube.io/files/rancher/19f96f391f6a214ea41c418efaaee84e-screen-shot-2022-05-10-at-2-28-41-pm.png)

![Screen Shot 2022-05-10 at 2.32.06 PM.png](https://zube.io/files/rancher/6973a5642e85be805fbfe0f000d99919-screen-shot-2022-05-10-at-2-32-06-pm.png)

**Comment by catherineluse** [comment]
At first I thought I broke this in my PR https://github.com/rancher/dashboard/commit/c6d212d3ee104d2c56ab6919dabd0b77d995216c but after reverting that change, I still see the same issue.

Still trying to figure out why it worked yesterday but not today.

**Comment by ronhorton** [comment]
The workflow in this ticket does not save a receiver. Tested in latest head, `2.6-head Commit ID 4bfdf0c`

1. created an alertmanagerconfig
2. clicked on alertmanagerconfig
3. clicked 'add receiver'
4. completed form
5. changed to edit yaml
6. save

Result - I don't see a blank page, but the receiver is not created. I also lose the `add receiver` button. 

![Screen Shot 2022-05-11 at 11.20.47 AM.png](https://zube.io/files/rancher/e8339f0ffa24a33045a050e3edc95086-screen-shot-2022-05-11-at-11-20-47-am.png)

**Comment by ronhorton** [comment]
Verified fixed - pulled new assets for `2.6-head Commit ID 4bfdf0c`

1. created receiver via form and it saved as expected.
2. created receiver and saved from yaml - saved as expected. 

![Screen Shot 2022-05-11 at 3.40.32 PM.png](https://zube.io/files/rancher/c3b12e48c6baea59f09288a78b4379a8-screen-shot-2022-05-11-at-3-40-32-pm.png)
