### ISSUE TITLE
When editing YAML, the header of the page says "Edit Receiver in AlertmanagerConfig"

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5879]
This issue is from feedback on a demo.

The header "Edit Receiver in AlertmanagerConfig" is supposed to only show on the form view, not the YAML view.

The title of the YAML page should be "Edit AlertmanagerConfig" because the receiver is a config block within the larger resource.

Note: If you go to Edit as YAML from the action menu in the receiver list view, I already fixed it. The bug is only seen when you go to Edit Config and then switch to Edit as YAML from there.
<img width="1205" alt="Screen Shot 2022-05-09 at 10 53 04 AM" src="https://user-images.githubusercontent.com/20599230/167469647-a0207144-14b2-4402-a926-cb3a4aeb3ae4.png">

**Comment by catherineluse** [comment]
# QA Template
## Root cause
Query params were not included in the logic for deciding what header to show
 
## What was fixed, or what changes have occurred
When you are editing an AlertmanagerConfig resource, and you navigate from Edit Config to Edit YAML, the `as=yaml` query param is added to the URL. The change now uses that param to know when the display is YAML and the header should be "Edit AlertmanagerConfig"
 
## Areas or cases that should be tested

1. Install monitoring
2. Install Prometheus Federator
3. Create an AlertmanagerConfig resource
4. Go to the new AlertmanagerConfig and click Edit Config (the error is not seen if you go directly to YAML). Confirm the title is still "Edit Receiver in AlertmanagerConfig" when the form is shown.
5. Click Edit as YAML
6. Confirm that the title is now "Edit AlertmanagerConfig" when the YAML view is shown.
 
## What areas could experience regressions?
Can't think of any

**Comment by ronhorton** [comment]
**Pass** Verified in `2.6-head Commit ID c5746d9`

1. created alert manager config
2. created receiver
3. clicked edit config
4. clicked `Edit as Yaml` on bottom of page

`Edit message at top of screen changed based on edit view as expected`

![Screen Shot 2022-06-27 at 4.04.28 PM.png](https://zube.io/files/rancher/9ef7e44272002a59286187f3f149c006-screen-shot-2022-06-27-at-4-04-28-pm.png)


![Screen Shot 2022-06-27 at 4.04.41 PM.png](https://zube.io/files/rancher/cdc6bdd453c5604cdf733b81556ad81c-screen-shot-2022-06-27-at-4-04-41-pm.png)
