### ISSUE TITLE
Add tooltip for `groupBy` field for route config within AlertmanagerConfig

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5885]
In the deprecated Route custom resource, you could enter labels to group alerts to the `groupBy` field by entering the labels as key-value pairs.

In the AlertmanagerConfig resource form, the API has changed. It takes the labels as a list of strings instead of key-value pairs. 

<img width="1045" alt="Screen Shot 2022-05-09 at 5 25 56 PM" src="https://user-images.githubusercontent.com/20599230/167506134-134178bd-cc40-446a-8b70-46ce59d4b38b.png">

According to the docs (https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#route):

> List of labels to group by. Labels must not be repeated (unique list). Special label "..." (aggregate by all possible labels), if provided, must be the only element in the list.

We should add a tooltip to this field with an example input such as `key:value` to clarify how to enter the labels. The tooltip can also say that `...` will group the output by all possible labels.

**Comment by catherineluse** [comment]
> add each label as a string in the format

Ah yes. That's a better way of phrasing it. Will change it

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head ea017a4
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 101.0.4951.67 

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy cluster
2. Install Alerting
3. Create Route
4. Hover over tooltip under Grouping

**Result**

Tooltip has been updated to give easier communication to user.
![image.png](https://zube.io/files/rancher/da548cd537ab51e166ce64d49741133f-image.png)
