### ISSUE TITLE
E2E: Create dashboard access for reviewing tests results

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5889]
**Detailed Description**
Create an on-demand and free dashboard solution like https://sorry-cypress.dev/ for reviewing tests results ([demo](https://sorry-cypress-demo.herokuapp.com/run/8234e09ebf4e94a0977126e4f4fd58e5)).

**Context**
We want to be able to easily see the results of E2E test runs and get some analysis into test runs.
Some [clouds configurations guides are already provided](https://docs.sorry-cypress.dev/cloud-setup/kubernetes), including an [Helm chart](https://artifacthub.io/packages/helm/sorry-cypress/sorry-cypress) to be used within a DO instance of Rancher and [hosted in a volume](https://cloud.digitalocean.com/volumes?i=f45bb6).

**Comment by cnotv** [comment]
Currently the Volume on DO has already been created and set to a minimum size to reduce the costs to a matter of cents.
https://cloud.digitalocean.com/volumes?i=f45bb6

It is possible to detach from the current cluster and moved to a team-sized one later on.

**Comment by cnotv** [comment]
Through the guidance of @catherineluse , we have been able to install the [Helm chart](https://crumbhole.com/indroducing-the-sorry-cypress-helm-chart/) on my [DO hosted instance of Rancher](https://104.248.253.167/dashboard) with the commands

```bash
helm repo add sorry-cypress https://sorry-cypress.github.io/charts
helm install sorry-cypress-rancher sorry-cypress/sorry-cypress
```

We have then copied the KubeConfig locally and got the nodes

```bash
kubectl get nodes --kubeconfig <MY_PWD>/kube-config-sorry-cypress
``` 

Then finally port forwarded

```bash
 kubectl port-forward service/sorry-cypress-rancher-dashboard 8080:8080 --kubeconfig <MY_PWD>/kube-config-sorry-cypress
```

In this way we were able to access to the dashboard service, but not to have the API running [as they do with Docker](https://docs.sorry-cypress.dev/guide/dashboard-and-api).

**Comment by catherineluse** [comment]
Note on the helm chart: It won't provide persistence by default.

> By default, the chart deploys everything to Kubernetes (as you’d expect), but there’s no persistence
> ...
> By default, the director uses the in-memory executionDriver, and the dummy screenshotsDriver. However, You can choose to enable a persistent mongo database for execution, and you can use S3 for screenshots.

We would also need MongoDB and S3 set up.

**Comment by catherineluse** [comment]
Also, the Helm chart says it is designed to work with Kubernetes 1.16 to 1.20.

Rancher doesn't support such old Kubernetes versions anymore.

**Comment by cnotv** [comment]
It seems possible to host it directly to a Rancher cluster by just running the Docker command: http://139.59.134.103:8080/
I am facing a CORS issue, not sure why.

**Comment by cnotv** [comment]
It seems like the CORS issue is extended to any type of deployment and it may be or a misconfiguration or a bug released on master.
