### ISSUE TITLE
KeyValue Component Feedback

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#589]
- [x] The key header and textbox should be aligned with the `Title` and the `Add` bar. 

<img width="215" alt="Screen Shot 2020-04-30 at 5 18 54 PM" src="https://user-images.githubusercontent.com/11410997/80770958-b0c53400-8b06-11ea-9e73-4a1998ac517e.png">

- [x] When the key value component is used inside the tabs, there is too much padding at the top. Since there is no title, the extra spacing that separates the title and headers (key and value) should be removed. 

<img width="451" alt="Screen Shot 2020-04-30 at 5 20 34 PM" src="https://user-images.githubusercontent.com/11410997/80771031-f124b200-8b06-11ea-9ac3-a3491164e6cd.png">

- [x] There should be no additional padding if no header on the table is defined. 

- [x] In the detail page, stop the text if it's going to overflow and cause the browser to allow you to scroll to the end of the text. 

<img width="1038" alt="Screen Shot 2020-04-30 at 6 00 53 PM" src="https://user-images.githubusercontent.com/11410997/80772804-bb82c780-8b0c-11ea-91a0-aa2a5b84c386.png">

### Detail Pages

- [x] For binary data, there is a line that appears.

<img width="952" alt="Screen Shot 2020-04-30 at 5 23 06 PM" src="https://user-images.githubusercontent.com/11410997/80771132-4f519500-8b07-11ea-9c0b-a0602d990696.png">

- [x] For binary data, it shows `There are no rows to show.`. Can we have the same information `There are no rows to show.` for the non-binary data?

<img width="597" alt="Screen Shot 2020-04-30 at 5 24 36 PM" src="https://user-images.githubusercontent.com/11410997/80771198-7f993380-8b07-11ea-90ae-770bd3bbfa1c.png">

- [x] For binary data, the headers are bigger than non-binary data. Can we standardize the size between the 2 and use the size in the binary data? 

Binary Data Header Size:

<img width="197" alt="Screen Shot 2020-04-30 at 5 29 17 PM" src="https://user-images.githubusercontent.com/11410997/80771378-27aefc80-8b08-11ea-97f0-9fd9a555d36a.png">

Non-Binary Data Header Size
The non-binary data header size for the "view" mode is 10px, but in "edit" mode, it's 12px, which is making it look small. 

<img width="194" alt="Screen Shot 2020-04-30 at 5 29 51 PM" src="https://user-images.githubusercontent.com/11410997/80771411-3ac1cc80-8b08-11ea-9c56-a44091f7ca29.png">

**Comment by lvuch** [comment]
@codyrancher could you look at the issue regarding space above <KeyValue>. I see an empty h4 that shouldn't be in the DOM unless populated. 

Could you also look at the conditional for all tables and showing "There are no rows to show." when they are empty. Thanks!

**Comment by deniseschannon** [comment]
- [ ] When using the KeyValue component in the detail page and there is no content. Add a label called `There are no rows to show.` so that it's obvious that it is intentionally blank.

**Comment by deniseschannon** [comment]
- [ ] Viewing sortable tables have a line that divide the header from the rows. Add this to KeyValue Component so the table view seems more consistent

Example with Line under Header

<img width="1131" alt="Screen Shot 2020-05-18 at 9 05 40 PM" src="https://user-images.githubusercontent.com/11410997/82283497-5ff96c00-994b-11ea-98d5-d9f7ab1925e7.png">

KeyValue Component which has no line under Header (and the tiniest header font ever)
<img width="829" alt="Screen Shot 2020-05-18 at 9 06 14 PM" src="https://user-images.githubusercontent.com/11410997/82283517-70114b80-994b-11ea-8c41-ad298ff4e5f3.png">

**Comment by vincent99** [comment]
You might as well just use sortabletable as the view version of keyvalue...

**Comment by deniseschannon** [comment]
- [ ] During edit mode of the KV component, if there are no rows, it's showing `There are no rows to show`. We should only show that when it's being used as `view` mode. Note: I don't actually know the mode names. 

<img width="1006" alt="Screen Shot 2020-05-21 at 11 14 33 AM" src="https://user-images.githubusercontent.com/11410997/82591478-46774080-9b54-11ea-9c27-41fae4765232.png">
