### ISSUE TITLE
"Take Snapshot" not visible for local Management Cluster

### ISSUE THREAD

**Issue by Florianisme** [rancher/dashboard#5894]
**Setup**
- Rancher version: v2.6.4
- Browser type & version: Google Chrome 96.0.4664.93

**Describe the bug**
Neither "Take Snapshot" nor "Restore Snapshot" is visible on the Rancher Management UI for the local Cluster. It is visible for all Downstream Clusters.
Snapshots are however automatically created on the filesystem in the default intervals.

**To Reproduce**
Setup an RKE2 Cluster and install the Rancher Management Server on top of it (following these instructions https://rancher.com/docs/rancher/v2.6/en/installation/resources/k8s-tutorials/ha-rke2/).

Log into Rancher, then go to "Cluster Management" and click the three dots on the local cluster.

**Result**
"Take Snapshot" and "Restore Snapshot" options are not visible.

**Expected Result**
"Take Snapshot" and "Restore Snapshot" options should be visible and clickable.

**Screenshots**
Context menu for local cluster:
![image](https://user-images.githubusercontent.com/7106869/167600229-300f3224-aafb-4955-8586-0cc06e63d21f.png)

Context menu for downstream clusters (as expected):
![image](https://user-images.githubusercontent.com/7106869/167600596-97acf093-8684-4e08-ac0c-c10b9c913441.png)

**Comment by rakeshk121** [comment]
@Florianisme what was fix?

**Comment by Florianisme** [comment]
Snapshots on the Management Server do not work like they do on Downstream Servers. 
You have to install the "Rancher Backup" Tool from the Marketplace. You can trigger a Backup by creating a new "Backup" Resource object.

**Comment by josedev-union** [comment]
> Snapshots on the Management Server do not work like they do on Downstream Servers. You have to install the "Rancher Backup" Tool from the Marketplace. You can trigger a Backup by creating a new "Backup" Resource object.

@Florianisme that is just a rancher backup, not cluster backup. I think there is no way to make snapshot for local cluster via GUI and need to do manually?

**Comment by Florianisme** [comment]
I think you would need to do that manually via the console

**Comment by josedev-union** [comment]
I wonder if it is possible to configure local cluster(`cluster.provisioning.cattle.io/v1`)'s `spec.rkeconfig.etcd` in a declarative way.
