### ISSUE TITLE
[project monitoring v2] Project monitor Create has a project listed that is specs rather than a project name

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5897]
**Setup**
- Rancher version: `2.6-head Commit ID 628b1b9` - `rhel 8.4 rke1 k8s 1.21.12`
- Browser type & version: `chrome latest`

**Describe the bug**
in the project monitor create page project dropdown, there is an entry `{"id":"cattle-project-p-g9l...` rather than the name of the project. a user can then select this value and `Create` which results in console error 
`vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'spec')
    at t.get (helm.cattle.io.projecthelmchart.js:23:102)
    at T (object.js:58:12)
    at f.valueFor (index.vue:607:1)
    at index.vue:466:1
    at Array.forEach (<anonymous>)
    at index.vue:465:1
    at Array.forEach (<anonymous>)
    at index.vue:454:18
    at Array.forEach (<anonymous>)
    at f.displayRows (index.vue:444:24)`
**To Reproduce**
This was after creating & deleting projects and namespaces to test project monitoring v2. 

**Result**
Error
**Expected Result**
only project names should appear in this dropdown

**Screenshots**
<img width="1619" alt="Screen Shot 2022-05-10 at 6 44 40 AM" src="https://user-images.githubusercontent.com/89212856/167613411-c6a2af68-7b13-48b9-b7c1-8b19a75fe8d2.png">

**Additional context**
after selecting this as a project, no project monitors show on project monitoring page. console error is thrown when user clicks on monitoring > project monitors

**Detailed Description**

**Context**

**Comment by ronhorton** [comment]
Reproduced in an rke2 cluster. 

1. created project
2. created namespace
3. created project monitor for that namespace
4. deleted namespace
5. deleted orphaned cattle-project-p-xxxx namespace
6. recreated namespace
7. cluster > monitoring > project monitors 
8. click Project * dropdown
<img width="1617" alt="Screen Shot 2022-05-10 at 7 13 45 AM" src="https://user-images.githubusercontent.com/89212856/167616666-08552219-a66f-4b3a-8ac9-89faee1e79ce.png">

**Comment by gaktive** [comment]
@Sean-McQ to look into this quickly though this isn't a release blocker so this can move to 2.6.6 if it's not easy to repro.
