### ISSUE TITLE
Cluster Mgmt allows a cluster being deleted to be deleted again

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5900]
Internal Ref: SURE-4470

Create a cluster and then delete it.

While it is deleting, you can still delete again from the action menu - this can cause errors to be logged in the backend.

The delete option should not be shown in the action menu if the cluster is in the process of being deleted (removed).

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head f4d09c7
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 102.0.5005.63 

----------

### Testing: ###

Tested this issue with the following steps:
1. Provision cluster
2. Delete cluster, Rancher will ask user to type in pool name to delete
![image.png](https://zube.io/files/rancher/8bc8d503e7033fdb237a8fef2f38cce1-image.png)
3. Verify that user cannot delete again


**Result** - Pass

Once deletion is in progress, user is unable to delete again. The option to delete disappears for the user.

![image.png](https://zube.io/files/rancher/743f391d9b23295d4771dbd8a90d4b33-image.png)
