### ISSUE TITLE
Error message should be displayed on the UI when the backup name contains upper case letters

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5903]
Setup

Rancher version: `v2.6.5-rc8`
Browser type & version: Chrome

**Describe the bug**
When we create a backup through rancher backup/restore charts, if the backup name contains uppercase letters no error is displayed on the UI. This can only be known from the network tab post requests.

**To Reproduce**
1. Create rancher backup charts any version in the local cluster
2. Create a rancher backup and provide a name with uppercase letters. eg: `Backup1`
3. Click on create button

**Result**
Create button errors but no message is displayed on the UI

**Expected Result**
Expected an error message as follows to be displayed on the UI.
```
Invalid value: \"Anu\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com')
```

**Additional context**
Error displayed in network tab:
```
type: "error", links: {}, code: "Invalid",…}
code: "Invalid"
links: {}
message: "Backup.resources.cattle.io \"Anu\" is invalid: metadata.name: Invalid value: \"Anu\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
status: 422
type: "error"
```

**Comment by Sean-McQ** [comment]
subdomain validator is already written, implementing form-validation is pretty simple. Still need to audit the rest of the form to make sure I'm not leaving any bugs elsewhere in it.

**Comment by anupama2501** [comment]
Opening for QA validation
