### ISSUE TITLE
Can't create an Opaque secret using plain text as value

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#5907]
**Setup**
- Rancher version: `v2.6.5-rc9`
- Browser type & version: MS Edge 101.0.1210.39 - OS X

**Describe the bug**
Previously I was able to create secrets passing a plain text string as value, Now the UI throws an error if it's not base64

**To Reproduce**

- Install Rancher `v2.6.5-rc9`
- Create a secret from the UI, I used the Opaque type.
- Pass a plain text string 

**Result**

`Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 1`

** Screenshots **

![Screen Shot 2022-05-10 at 3 27 46 PM](https://user-images.githubusercontent.com/27659/167732050-8682ae2e-f70e-484e-9997-a197f6aa24ec.png)

**Expected Result**
Plaintext should be stored properly as base64 without having to manually convert it and pass it as value in the UI

**Additional context**
This used to work passing plain text on 2.6.2

**Comment by aalves08** [comment]
**For QA, other scenarios to test from previous Secrets issues:**

- [**Scenario 1**:](https://zube.io/rancher/dashboard-ui/c/5602)
- [**Scenario 2**](https://zube.io/rancher/dashboard-ui/c/5336)

**Comment by Josh-Diamond** [comment]
Ticket #5907 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.5-rc9`:
1. Fresh install of rancher `v2.6.5-rc9`
2. Create an opaque secret from rancher UI
3. Reproduced - Unable to create a secret with plain text

Screenshot:

`Step 3`
<img width="1565" alt="Screen Shot 2022-05-11 at 8 47 32 AM" src="https://user-images.githubusercontent.com/46494969/167892777-5b901091-8535-40db-be2a-7c4982f2ec83.png">

---

Verified on rancher `v2.6-4bfdf0cd89569ab1c8a0fd06d0ded726e61445b5-head`:
1. Fresh install of rancher `v2.6-head`
2. Create an opaque secret from rancher UI
3. Verified - Secret successfully created with plain text

Screenshot:

`Step 3`
![validated](https://user-images.githubusercontent.com/46494969/167893608-81cfc6f9-68c8-457d-a78f-ca055c206345.png)
