### ISSUE TITLE
After switching to Simplified Chinese, resources cannot be searched using English keywords

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#5913]
**Setup**
- Rancher version: v2.6.4
- Browser type & version:  Google Chrome 101.0.4951.54

**Describe the bug**

Switch to Simplified Chinese and use the resource search function, only Chinese keywords can be searched, but English keywords cannot be searched

**To Reproduce**

1. Log in to Rancher 2.6 and switch the language to Simplified Chinese
2. Go to `EXPLORE CLUSTER` UI
3. Use `Resource Search` to search for `密文` and `secret` respectively

**Result**
Using `密文` can search results, but can't search results with `secret`.

**Expected Result**

Whether you use Chinese or English keywords, you should search for the corresponding resources

**Screenshots**

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/19684717/167756195-855f70f0-7f62-4128-adb8-e8877639815b.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/19684717/167756229-91f23a20-e48f-4141-af5e-37d3f4a61665.png">

**Comment by gaktive** [comment]
Proposed PR to fix this: https://github.com/rancher/dashboard/pull/5936
