### ISSUE TITLE
Kubernetes version Update not possible // Dropdown read only

### ISSUE THREAD

**Issue by tobiasfichter** [rancher/dashboard#5916]
**Setup**
- Rancher version: v2.6.4 - but also true for at least 2.6.x (rancher/rancher-agent:v2.6.4)
- Browser type & version: Chrome v101.x
- Provisioner: RKE1
- Machine Provider: VMware vSphere
- Kubernetes Version: v1.18.15 (rancher/hyperkube:v1.18.15-rancher1)
- CreationTimestamp: 2019-03-19

**Describe the bug**
The former dropdown for selecting a kubernetes version to update to is now a read only textbox, please see screenshot.

**To Reproduce**
Navigate to Cluster Management >Edit Config > Kubernetes Options > Kubernetes version

**Expected Result**
A dropdown to select de kubernetes version to which the upgrade should happen

**Screenshots**
![image](https://user-images.githubusercontent.com/80265538/167780951-36564a5c-d2c0-4807-bc47-976e8cd87dd3.png)

**Comment by rak-phillip** [comment]
@tobiasfichter thanks for raising the issue 😁

@gaktive we tried to troubleshoot this one in the Rancher Users slack, but I wasn't able to repro in a timely fashion. I asked that we get an issue created so we could take a closer look

**Comment by codyrancher** [comment]
@tobiasfichter this appears to be working as intended
![k8sversion](https://user-images.githubusercontent.com/55104481/171289985-905c67fd-3c59-491c-8a97-b825d53c40b7.gif)

I would guess that the cluster you're looking at is making use of RKE Templates and `Allow user override` has not be checked. This has caused confusion for others as well. There was a thread in our slack channel where I went over this issue in a little more detail https://rancher-users.slack.com/archives/C3ASABBD1/p1651584517701239.

![image](https://user-images.githubusercontent.com/55104481/171290125-bcf72e79-2745-4387-ac37-22f91d6b0475.png)

Would you mind confirming if this is indeed the issue you're running into?

**Comment by tobiasfichter** [comment]
It is! I therefore cloned the existing RKE Template to a new Revision, enabled User Override for Kubernetes Version and changed the Template Revision on Cluster config. The dropdown is now editable again - thanks a lot!
