### ISSUE TITLE
v2prov etcd snapshot objects are not displayed after the snapshots are taken unless a refresh of the page is performed 

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#5925]
**Setup**
- Rancher version: `v2.6-4bfdf0cd89569ab1c8a0fd06d0ded726e61445b5-head`
- Browser type & version:  Chrome

**Describe the bug**
v2prov etcd snapshot objects are not displayed after the snapshots are taken unless a refresh of the page is performed --> In this case, user is NOT expected to perform a refresh on the page

**To Reproduce**
1. Fresh install of rancher `v2.6-head`
2. Take a v2prov etcd snapshot
3. Reproduced 

**Result**
object is created but not displayed in UI unless user performs a refresh of the page

**Expected Result**
object is created and displayed in UI without any additional steps/refreshes

**Comment by nwmac** [comment]
I can not reproduce this - can you validate again, please and include detailed steps to reproduce.

When you press 'Snapshot now', the button changes to indicate the snapshot is being created and the status banner at the top gives updates - once complete, the snapshot shows in the list correctly without needing to refresh the page.

**Comment by sowmyav27** [comment]
**On 2.6head commit id: `3506e43`**

- The original issue is not seen anymore.
- Deployed an RKE2 cluster
- Navigate to cluster details --> Snapshots --> CLick on Snapshot Now
- Cluster goes into Updating state 
- Snapshots are seen in Snapshots Tab with NO refresh.
<img width="1439" alt="Screen Shot 2022-07-12 at 7 09 50 AM" src="https://user-images.githubusercontent.com/26032343/178510420-f5301e8a-cc9a-4a4e-9b89-9eae129151b0.png">
