### ISSUE TITLE
[@rancher/components] Convert components to typescript

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#5932]
The first collection of components can be converted to typescript. These need to be converted to typescript along with adding types for props and other options.

```
Components
  |- BadgeState.vue
  |- Banner.vue
  |- Card.vue
  |- Form
    |- Checkbox.vue
    |- LabeledInput.vue
    |- LabeledTooltip.vue
    |- RadioButton.vue
    |- RadioGroup.vue
    |- TextAreaAutoGrow.vue
```

### COA

- [x] Each component listed is converted to typescript
- [x] `@typescript-eslint` errors are resolved

**Comment by rak-phillip** [comment]
Running through a scenario like this should test all the inputs that were modified for this issue. We don't expect any functional changes, so we need to be testing for regressions

Open up your web console while performing this test and make sure there are no unexpected errors or warnings printed to the console. If you see an error or warning that mentions something along the lines of "Expected string, got number instead" then have a regression. We also want to validate that we don't observe any change in behavior for the following inputs:

- [ ] BadgeState

- [ ] Checkbox

- [ ] LabeledInput

- [ ] Radio & RadioGroup

- [ ] LabeledTooltip

- [ ] LabeledSelect

The following steps should touch at least one instance of each input listed above:

## Create a cluster

1. Navigate to Cluster Management => Create
2. Make sure RKE2/K3s is active and select an item from the list (using DigitalOcean for this example)
3. Enter a Cluster name

## Machine Pools

1. Create 3 machine pools with the following (As you make changes, verify that the etcd, Control Plane, and Worker badges update as you change counts and checkboxes)
   1. pool1 - Machine Count 3, Role etcd
   2. pool2 - Machine Count 3, Role Control Plane
   3. pool3 - Machine Count 3, Role Worker
2. Change the OS Image to Ubuntu 22.04 (LTS) (use anything that isn't selected by default)
3. Click on "Show Advanced" for pool1
   1. Enter a value of 5 Minuts for Quto Replace
   2. Hover your cursor over the i in the Auto Replace label and make sure that a tooltip is displayed

## Cluster Configuration

1. On the Upgrade Strategy tab, select Drain Nodes = Yes for both Control Plane and Worker Nodes
2. Hover your mouse cursor over the tooltips in labels and make sure they display
3. When finished, click create

## Edit Cluster & Review changes

1. Click on the overflow menu for your newly created cluster and select Edit Config
2. Verify that the values displayed in the form match the values that you chose during creation

@gaktive

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 6e7308f
Rancher cluster type: HA
Docker version: 20.10


----------

### Testing: ###

Tested this issue with the following steps:
1. Create a cluster
  - Navigate to Cluster Management => Create
  - Make sure RKE2/K3s is active and select an item from the list (using DigitalOcean for this example)
2. Enter a Cluster name
  - Machine Pools
  - Create 3 machine pools with the following (As you make changes, verify that the etcd, Control Plane, and Worker badges update as you change counts and checkboxes)
      - pool1 - Machine Count 3, Role etcd
      - pool2 - Machine Count 3, Role Control Plane
      - pool3 - Machine Count 3, Role Worker
  - Change the OS Image to Ubuntu 22.04 (LTS) (use anything that isn't selected by default)
  - Click on "Show Advanced" for pool1
  - Enter a value of 5 Minutes for Auto Replace
  - Hover your cursor over the i in the Auto Replace label and make sure that a tooltip is displayed
3. Cluster Configuration
  - On the Upgrade Strategy tab, select Drain Nodes = Yes for both Control Plane and Worker Nodes
  - Hover your mouse cursor over the tooltips in labels and make sure they display
  - When finished, click create
4. Edit Cluster & Review changes
  - Click on the overflow menu for your newly created cluster and select Edit Config
  - Verify that the values displayed in the form match the values that you chose during creation

**Result**

All the values displayed after creating the cluster are preserved.
Auto Replace value is preserved
![image.png](https://zube.io/files/rancher/c90bcdd959047a7c27d899d786e068ed-image.png)
Upgrade strategy values are preserved
![image.png](https://zube.io/files/rancher/4890dff2717428751f6c2c82e3e8005b-image.png)
