### ISSUE TITLE
Add Node Labels and Annotations to Node List in Cluster Explorer

### ISSUE THREAD

**Issue by jmarhee** [rancher/dashboard#5943]
**Setup**
- Rancher version: 2.6.3
- Browser type & version: Any

**Detailed Description**
In the cluster explorer view in previous versions, in the Cluster node list view, node Labels and Annotations (not just Taints) could be viewed from that list view (rather than needing to enter the page for that node (/explorer/node/{node name}, where then the annotations and labels are visible). This request to have the ability to have this visible on the listing if annotations are present on the node (or otherwise toggleable). 

I'm referring, I believe, to the use of Taints here:
https://github.com/rancher/dashboard/blob/d89bb2121d54d018d1ce35810dde7d0fb8d6cb20/list/node.vue#L152-L163

If this could be made available for Annotations or Labels as well, optionally or otherwise, this would be the enhancement being requested here.  
 
**Context**
In environments with large numbers of clusters, with large numbers of nodes providing different node-segrated services (storage, gpu-equipped, topology, etc.), this is useful to quickly identify things like function or topological information that might be stored there from that top-level view. 

With Rancher 2.4.5 reaching EOL and many users now upgrading past 2.5.x to 2.6.3 and above, this is proving to be a somewhat unexpected change for users (several of whom are from Rancher PS engagements and requested clarity) who rely on this quick overview availability in the node list view for cluster administration from the UI.

**Comment by richard-cox** [comment]
We've got this one tracked in #5448 (I've explicitly requested annotations, just in case)
