### ISSUE TITLE
Api keys missing Age date

### ISSUE THREAD

**Issue by cbron** [rancher/dashboard#5944]
No errors in console, see dash where date should be

<img width="1514" alt="Screen Shot 2022-05-12 at 15 44 09" src="https://user-images.githubusercontent.com/571419/168179505-4035b357-d8b9-4e5e-92e1-660ae1198943.png">

**Comment by gaktive** [comment]
Could be tied to changes made to the sortable table.

**Comment by richard-cox** [comment]
@gaktive  As per comment from other issue, other priorities will keep me from working on 2.6.6 issues

**Comment by nwmac** [comment]
From avatar menu -> Account & API Keys - the age data always shows a '-'.

**Comment by cbron** [comment]
This may be related: https://github.com/rancher/dashboard/issues/6097

**Comment by markusewalker** [comment]
Verified that this is resolved in `v2.6-head` https://github.com/rancher/rancher/commit/f4d09c73e1a609f5c5fe0848ebd6e4b059056264.

**ENVIRONMENT DETAILS**
- Rancher HA
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/f4d09c73e1a609f5c5fe0848ebd6e4b059056264
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navgiated to the UI in a browser.
2.  In the top-right corner, clicked the user photo > `Account and API Keys`.
3. Verified that the `Age` column has the timestamp showing:
![image](https://user-images.githubusercontent.com/52591819/172967361-54bd483a-9463-429b-8dcf-32104b6abcc5.png)
