### ISSUE TITLE
RKE1 Cluster Template Creation Error "object missing name"

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#5945]
**Setup**
- Rancher version: 2.6-head c4d59fa
- Browser type & version: Chrome 101

**Describe the bug**

When creating a cluster template, the error "object missing name" shows although the cluster template and revision are actually created 

**To Reproduce**
creating a cluster template for RKE1  

**Result**
UI show the following error 
<img width="1103" alt="Screen Shot 2022-05-12 at 3 44 39 PM" src="https://user-images.githubusercontent.com/6218999/168179518-462724eb-8fa5-4f85-af26-09cb83558191.png">

The error is returned by the POST request to the "/v3/clustertemplaterevision" endpoint
```
Request URL: https://x.x.x.x/v3/clustertemplaterevision
Request Method: POST
Status Code: 500 Internal Server Error
```

**Expected Result**

There should be no error message

**Comment by richard-cox** [comment]
I've tried to reproduce this in the latest UI (post 2.6.7) and failed. Unless there's any specific template settings missing from the description this is now working fine.

**Comment by Josh-Diamond** [comment]
Ticket #5945 - Test Results
---

With Docker on a single-node instance:

Failed to reproduce on `v2.6-c4d59fa88e2313e1446ba542a21c39e15a17f375-head` - (commit issue was reported)

Verified this issue is not seen/experienced on latest 2.6 and 2.7 head:
- Successfully able to create RKE1 cluster templates on:
    - `v2.6-12961485c69e593a1c980378902f6a026166ad50-head`
    - `v2.7-c0f6cdb9a7494cb6eae2e3b341174bd079f13073-head`
