### ISSUE TITLE
Side navigation: Some links are erroneously flagged with children

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5948]
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Any

**Describe the bug**
Some added navlink to the side navigation are flagged as with children when is actually not true.

**To Reproduce**
- Add Neuvector
- Inspect the navigation to the left

**Result**
Wrong classes are added to the navigation: `accordion package depth-0 has-children`.

**Expected Result**
The class `has-children` should not be present.

**Screenshots**
<img width="788" alt="Screenshot 2022-05-13 at 19 16 48" src="https://user-images.githubusercontent.com/5009481/168336210-d5c8e0b3-b3dd-48f2-992e-5eceeccea8cd.png">

**Additional context**

**Comment by nwmac** [comment]
This does not cause any presentation issues.

Should be looked at when we re-work the side nav

**Comment by cnotv** [comment]
Yes, it's flagged as tech-debt.

**Comment by catherineluse** [comment]
I don't get it. I assume "has children" means you can expand the nav item to see more nav items. In that case, I see nothing wrong with the screenshot.

**Comment by cnotv** [comment]
> I don't get it. I assume "has children" means you can expand the nav item to see more nav items, so there should be a down-arrow on the right side of the nav item. In that case, I see nothing wrong with the screenshot.

In the screenshot that navigation has no children and therefore cannot do what you said 😅
(sorry if it was not clear enough)

**Comment by nwmac** [comment]
I think the issue is they have the css class indicating they have children when they don't.

**Comment by cnotv** [comment]
To be solved with https://github.com/rancher/dashboard/issues/8418
