### ISSUE TITLE
Able to use Disabled/Locked Project Roles after upgrade

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5952]
Internal reference: SURE-4203
Reported in 2.6.3 patch 1

Issue description:
After upgrade from Rancher 2.5.7 to 2.6.3-patch1, the Disabled/Locked Project Roles is able to being used.

Repro steps:

- Installed a fresh rancher 2.5.7
- Disabled/locked all Project template roles, less the Project Owner
- Upgraded Rancher to 2.6.3-patch1
- Was able to use the Project Namespace Creator to a local user

Additional info:

Someone else did the following with Rancher 2.5.7: 
- Disabled/Locked Project Roles, and there were not able to add a user to a project list/using the disabled/locked Project Roles
- Upgrade Rancher to 2.6.3 and they were able to see/list the disabled/locked Project Roles but after saving it, it does not work, no error showed up in UI, and when they tried to edit the Project again, the previous user added is not showed up. 

Belief therefore is it's necessary only to fix the listing of the Project Roles during adding a new user to a Project. Also in 2.6.3, the option to select ' Project Creator Default'  to 'Yes' doesn't work also.

@cbron indicated:
"If thats the case, then the UI just needs to filter when adding user and project role, to only the project roles that don't have `locked=true`.
 
On a side note, I went back and forth between old and new UI toggling both default-role and locked, and got very odd results. It's like some of the results were cached along the way, or some of the forms weren't accepting both options. Would be worth a look."

Actual behavior:
Previous disabled/locked Project roles in 2.5.7 are being able to use after Rancher upgraded to 2.6.3-patch1

Expected behavior:
Disabled/locked Project roles still locked for use after upgrades (2.5.7 -> 2.6.3-patch1)

**Comment by nwmac** [comment]
@bisht-richa Let me know if you need me to explain this one.

Essentially, you can create a role and then edit it and say it is locked - in the new UI we still allow you to assign it to a user, where we should not.

You should check with @kwwii whether we should hide locked roles, or show them greyed-out with an indication that they are locked and can't be bound to a user.

**Comment by nwmac** [comment]
Can you add an estimate to this ticket before starting

**Comment by nwmac** [comment]
To see this issue:

In dashboard, go to users and auth, roles and cluster roles.

Pick a role e.g. `Manage Cluster Backups` and select `Edit Config` from the action menu for it. Set 'Locked` to yes:

![image](https://user-images.githubusercontent.com/1955897/213480895-fa9dcf3b-3da6-4deb-8ddd-168175d9c5ef.png)

Back on the list of roles, you will see it marked as locked:

![image](https://user-images.githubusercontent.com/1955897/213480982-f3a64c97-84d9-4a5e-84b2-4b8850fd0f3e.png)

Go to the explorer view for the local cluster and to`Cluster and Project Members`and click `Add` - you'll get this:

![image](https://user-images.githubusercontent.com/1955897/213482010-f96e00ca-d4b8-40df-947b-9acf4205a171.png)

You'll see that `Manage Cluster Backups` is shown - since it is locked, it should not be selectable - I'd suggest disabling the checkbox and adding a lock icon after the name with a tooltip saying that the role is locked.

We need to make sure we do the same for Project roles- this possibly uses the same components, but needs to be verified.

**Comment by Priyashetty17** [comment]
✅ Test Passed on Rancher version v2.7-1eb478f3e77fde8a0328ed99cc3c39a1048442d2-head

| Component| Version | 
|----------|----------|
| Rancher   | v2.7-1eb478f3e77fde8a0328ed99cc3c39a1048442d2-head  | 
| Dashboard   | master "113e1d30a" | 

Here are the test scenarios that were executed to verify the fix:

**Scenario1**: Fresh install: v2.7 head and verify that the users cannot be added with locked roles to a project/cluster.

1. [✅] Log in as an admin and create a downstream cluster. 
2. [✅ ] Verify all nodes, deployments and pods in both the local and downstream clusters are in a healthy state.
3. [✅] Create 2 standard users "testUser1" and "testUser2"
4. [✅] In the downstream cluster, assign the role "Create Namespaces" to "testUser1" as a project member and assign the role "Manage Nodes" to "testUser1" as a cluster member. 
5. [✅] Lock the cluster role "Manage Nodes" and the project role "Create Namespace"
6. [✅] In the downstream cluster, verify that the cluster role "Manage Nodes" and the project role "Create Namespaces" are in a locked state
7. [✅] In the downstream cluster, attempt to add user "testUser2" as a cluster member with the role "Manage Nodes". Go to the Cluster and Project Members -> "Cluster Membership" -> Click "Add" -> Enter "testUser2" -> select "Custom" -> Verify that the "Manage Nodes" role is disabled/locked and not available for selection. 
8. [✅] In the downstream cluster, attempt to add user "testUser2" as a project member with the role "Create Namespaces". Go to the Cluster and Project Members -> "Project Membership" -> Click "Add" for a project -> Enter "testUser2" -> select "Custom" -> Verify that the "Create Namespaces" role is disabled/locked and not available for selection. 
9. [✅] Verify that user "testUser1" remains a cluster member assigned with the role "Manage Nodes" and a project member assigned with the role "Create Namespaces".
10. [✅] Unlock the cluster role "Manage Nodes" and the project role "Create Namespace" and verify that the roles can now be used.
11. [✅] In the downstream cluster, add "testUser2" as a project member with the role "Create Namespaces" and verify that the user is added as a project member. (Verify this in both "Projects/Namespaces" and "Cluster and Project Members" sections of the UI)
12. [✅] In the downstream cluster, add "testUser2" as a cluster member with the role "Manage Nodes" and verify that the user is added as a cluster member

**Scenario2**: Recreate the issue with v2.6.3-patch1, upgrade the cluster to v2.7head and verify that the users cannot be added with locked roles to a project/cluster

1. [✅] Install Rancher v2.6.3-patch1 (To recreate the issue).
2. [✅] Log in as an admin and create a downstream cluster. 
3. [✅ ] Verify all nodes, deployments and pods in both the local and downstream clusters are in a healthy state.
4. [✅] Create 2 standard users "testUser1" and "testUser2"
5. [✅] In the downstream cluster, assign the role "Create Namespaces" to "testUser1" as a project member and assign the role "Manage Nodes" to "testUser1" as a cluster member.
6. [✅] Lock the cluster role "Manage Nodes" and the project role "Create Namespace"
7. [✅] In the downstream cluster, verify that the cluster role "Manage Nodes" and the project role "Create Namespaces" are in a locked state
8. [:x:] In the downstream cluster, add "testUser2" as a project member with the role "Create Namespaces". **Issue**: UI allowed adding user "testUser2" as a project member with the role "Create Namespaces". Although the UI did not show any error, the API call did throw a 422 Error. However, the user "testUser2" was not reflected in the list of project members . 
9. [✅] Add "testUser2" as a cluster member with the role "Manage Nodes". This worked as expected. UI displayed the following error: { "baseType": "error", "code": "InvalidState", "message": "Role is locked and cannot be assigned", "status": 422, "type": "error" }
10. [✅] Upgrade the cluster to v2.7-head
11. [✅] Verify all nodes, deployments and pods in both the local and downstream clusters are in a healthy state.
12. [✅] In the downstream cluster, Verify that the cluster role "Manage Nodes" and the project role "Create Namespaces" are in a locked state
13. [✅] Verify that user "testUser1" remains a cluster member assigned with role "Manage Nodes" and aproject member assigned with role "Create Namespaces".
14. [✅] In the downstream cluster, attempt to add user "testUser2" as a cluster member with role "Manage Nodes". Go to the Cluster and Project Members -> "Cluster Membership" -> Click "Add" -> Enter "testUser2" -> select "Custom" -> Verify that the "Manage Nodes" role is disabled/locked and not available for selection. 
15. [✅] In the downstream cluster, attempt to add user "testUser2" as a project member with the role "Create Namespaces". Go to the Cluster and Project Members -> "Project Membership" -> Click "Add" for a project -> Enter "testUser2" -> select "Custom" -> Verify that the "Create Namespaces" role is disabled/locked and not available for selection.  
16. [✅] Unlock the cluster role "Manage Nodes" and the project role "Create Namespace" and verify that the roles can now be used.
17. [✅] In the downstream cluster, add "testUser2" as a project member with the role "Create Namespaces" and verify that the user is added as a project member. (Verify this in both "Projects/Namespaces" and "Cluster and Project Members" sections of the UI)
19. [✅] In the downstream cluster, add "testUser2" as a cluster member with the role "Manage Nodes" and verify that the user is added as a cluster member
![lockedRoleCreateNamespace_v27](https://github.com/rancher/dashboard/assets/42880103/1a4c1317-98b8-4192-9c7f-498c7309ab02)
![lockedRoleManageNodes_v27](https://github.com/rancher/dashboard/assets/42880103/437c8610-5ce6-4a1f-bec1-bd1c98b8e4ba)
