### ISSUE TITLE
[RFE] Compare RKE templates in UI (diff)

### ISSUE THREAD

**Issue by asemen2608** [rancher/dashboard#5954]
**What kind of request is this (feature request):**

feature request

**Steps to reproduce (least amount of steps as possible):**

In rancher UI "Tools" -> "RKE Temalates"
```
<IP>/g/rke-templates/index
```
Create a select filed "Compare" -> see an example in the screen shot compare.png

- Select the two RKE templates which should be compared. 
  After that you could press the “new” compare button.

- After the “Compare” Button was pressed, a new window with the diff of both yaml files is shown. 
  Like a compare in visual studio code for example.

**Result:**

Select and Compare of 2 RKE templates and get an diff like shown in screen shot diff.png

**Other details that may be helpful:**

UI Rancher version 2.5.X and if possible 2.4.X

**Environment information**
- Rancher version (`rancher/rancher ):
- Installation option (HA):

compare.png
![compare](https://user-images.githubusercontent.com/61939253/97599820-b0035100-1a08-11eb-990a-6e2cc57016fb.png)

diff.png
![diff](https://user-images.githubusercontent.com/61939253/97599836-b4c80500-1a08-11eb-8118-cff33ad7c5d2.png)

gz#13062

**Comment by gaktive** [comment]
Internal reference: SURE-2529

**Comment by Josh-Diamond** [comment]
Ticket #5954 - Test Results - REOPENED
---

With Docker on a single-node instance:

Verified on rancher `v2.7-830fa58ccecfb8915fc54862a9b19fdfeb2c0f8c-head`:
1. Fresh install of rancher `v2.7-head`
2. Navigate to `Cluster Management > RKE Configuration > RKE Templates`
3. Create 3 different RKE Templates
4. Select 2 RKE Templates
5. Verified - `Compare` button becomes selectable
6. Additionally, select the 3rd RKE Template
7. Verified - `Compare` button becomes unselectable
8. Unselect the 3rd RKE Template, and `Compare` the remaining two selected RKE Templates
9. Verified - RKE Templates accurately compared
10. Veri-FAILED - Contrast is not compatible w/ Dark Mode - [unable to clearly view values]
11. Veri-FAILED - Compare does NOT show two templates side-by-side; instead grabs the first selected RKE Template and compares that to the second selected RKE Template in one view.  RKE Templates are differentiated by color but no labels are present to clearly identify which template color represents which specific RKE Template.
12. Veri-FAILED - If first template does not have configurations what second template has, only `green` values for second template are shown; expected to have red still showcase value of `null, nil, or ""`

Screenshots:

`Compare w/ Light Mode - [acceptable contrast]`
<img width="944" alt="Screenshot 2022-12-15 at 3 07 23 PM" src="https://user-images.githubusercontent.com/46494969/207981595-c63aba96-bb78-4a68-85b5-2127a8ad0edd.png">

`Compare w/ Dark Mode - [unacceptable contrast]`
<img width="981" alt="Screenshot 2022-12-15 at 3 05 27 PM" src="https://user-images.githubusercontent.com/46494969/207981583-efb64c6b-4c28-4535-9173-e62dcefe3120.png">

Issues to be addressed:

- Contrast is not compatible w/ Dark Mode - [unable to clearly view values]
- Compare does NOT show two templates side-by-side, confusion around which color [red/green] represents which Template
    - requesting colored Template labels perhaps? or side-by-side comparison
- All fields with differences should be either red or green with values being compared from the respective Templates. 
    - Currently, if `null/nil`, in first template, and populated in second template, compare will only show populated values in green, associated with the second template.  [e.g. `private_registries` field from screenshot]

**Comment by nwmac** [comment]
Final fixes in this PR: https://github.com/rancher/ui/pull/5087

**Comment by Josh-Diamond** [comment]
providing QA sign-off and closing this out now, as this delivers an acceptable UX
