### ISSUE TITLE
Add option to disable chomping YAML configmaps

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5958]
Internal reference: SURE-4416

When creating multi-line configmaps, the Rancher UI is adding the chomp designator which can break certain applications. We get around this by editing the yaml directly, but those who are less yaml-savvy sometimes use the direct editor and unknowingly reintroduce the chomp.

Possible solution (quoting):
> My first thought is to have a checkbox to enable/disable the chomp. We noticed this when we started storing haproxy configs as configmaps, and haproxy would report an error about a missing EOL because the Rancher UI adds the dash to chomp configmap blocks. We can get around it by editing the yaml directly and replacing '|-' with '|', but occasionally I or someone else would forget and Rancher would put the dash back.

**Comment by catherineluse** [comment]
Related issue https://github.com/rancher/dashboard/issues/6039

**Comment by gaktive** [comment]
Chomping syntaxes context: https://yaml-multiline.info/

**Comment by gaktive** [comment]
For QA's awareness, UI will work on test automation around this in
