### ISSUE TITLE
Container Component

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#596]
In workloads, we'll be moving towards the ability to add multiple containers into a workload, which aligns closer to the Kubernetes concepts. Based on this change, creating a `Container` component makes sense to be able to add/remove containers on 1 page. 

Within each workload type, you have the ability to specify containers which is part of a pod template. In the rest of this issue, it will refer to a field in the container spec as `<containerSpec>`, which can be nested differently between each workload type. Refer to this table to find out where the pod template spec is nested. 

Any other fields will be called out specifically between the types. 

Name | Pod Template Spec K8s yaml location
---|---
Deployment | `spec.template.spec.containers`
Daemon Set | `spec.template.spec.containers`
Stateful Set | `spec.template.spec.containers`
Replica Set | `spec.template.spec.containers`
Job | `spec.template.spec.containers`
Cron Job | `spec.jobTemplate.spec.template.spec.containers`

> Note: This container component will be nested in a `Containers` tab on the Workloads page.

# `Container` Component Fields
All these fields are nested under `<containersSpec>`

Field Name | k8s YAML | Field Note
---|---|---
Container Name | `name` | Textbox
Container Image | `image` | Textbox
Image Pull Policy | `imagePullPolicy` | Dropdown Options: <br> * `IfNotPresent` (Default) <br> *  `Always` <br> * `Never`
Ports | `ports` | Update to new mock in [comment below](https://github.com/rancher/dashboard/issues/596#issuecomment-627621274). Add in `Name`, create a link to hide/show host ports, which is not common field. 

**Container Name** & **Container Image**

<img width="526" alt="Screen Shot 2020-05-04 at 11 37 58 AM" src="https://user-images.githubusercontent.com/11410997/81000912-c20a8b00-8dfb-11ea-869a-fc04091c4625.png">

# Tabs in `Container`

Note: There are no labels/annotations in this set of tabs

Tab Name | Notes
---|---
Command | All fields in current `Command` tab
Resources | See `Resources` tab
Health Check | See `Health Check` tab
Security Context | See `Container Security Context` tab

## Command tab
All these fields are nested under `<containersSpec>`.

Field Name | k8s yaml
---|---
Entrypoint | `command`
Arguments to Entrypoint (Replace "Command")  | `args`
WorkingDir | `workingDir`
Stdn (See options)  | `stdin` & `stdnOnce` | 
TTY | `tty`
Environment Variables | `env`

**Stdn Options**

Stdn Option | `stdn` Value | `stdnOnce` Value
---|---|---
Blank | `false | `true`
`No` (Default) | `false` | `false`
`Once`| `true` | `true`
`Yes`  | `true` | `false`

**Updates**
- [ ] Change `Command` to `Arguments` as label for `args`
- [ ] Replace `Interactive` checkbox into the new `Stdn` dropdown 

<img width="1059" alt="Screen Shot 2020-05-04 at 11 20 11 AM" src="https://user-images.githubusercontent.com/11410997/80999492-a1d9cc80-8df9-11ea-8910-17762ca64761.png">

<img width="281" alt="Screen Shot 2020-05-04 at 9 50 34 AM" src="https://user-images.githubusercontent.com/11410997/80991342-b8c5f200-8dec-11ea-8ef0-18e4abe5fc65.png">

## Resources tab
All these fields are nested under `<containersSpec>.resources`.

Use the `ContainerResourceLimit` component. https://github.com/rancher/dashboard/issues/594

Component | Field Name | k8s yaml
---|---|---
`ContainerResourceLimit` | CPU Limit | `resources.limits.cpu`
`ContainerResourceLimit` | CPU Reservation | `resources.requests.cpu`
`ContainerResourceLimit` | Memory Limit | `resources.limits.memory`
`ContainerResourceLimit` | Memory Reservation | `resources.requests.memory`

<img width="1022" alt="Screen Shot 2020-05-04 at 9 53 45 AM" src="https://user-images.githubusercontent.com/11410997/80992884-0b081280-8def-11ea-96fc-a45f12e05d1c.png">

## Healthcheck tab
All these fields are nested under `<containersSpec>`. See existing content in `Health` tab from workloads.

- [ ] Create a `Probe` component if one doesn't exist today. It should have the dropdown option for types of checks and the constant fields.

Field Name | k8s yaml
---|---
Readiness Probe | `readinessProbe`
Liveness Probe | `livenessProbe`
Startup Probe (**NEW**) | `startupProbe`

- [ ] Add an additional ability to configure `startupProbe` which has the same options of Liveness and Readiness Probe 

**Fields in a Probe**

<img width="509" alt="Screen Shot 2020-05-04 at 2 00 37 PM" src="https://user-images.githubusercontent.com/11410997/81013251-add08900-8e0f-11ea-81ce-b10a3e064eb1.png">

### Different types of Health checks
Everything listed here is nested under `spec.template.spec.containers` and either under `livenessProbe`, `readinessProbe` or `startupProbe`.

**HTTP Requests (`httpGet`)**

<img width="228" alt="Screen Shot 2020-05-04 at 10 29 30 AM" src="https://user-images.githubusercontent.com/11410997/80994842-2b859c00-8df2-11ea-880c-40ac6a2a76d6.png">

Field Name | k8s yaml | Field Type
---|---|---
Check Port | `httpGet.port` | Textbox
Request Path | `httpGet.path` | Textbox
Request Headers | `httpGet.httpHeaders` | KeyValue Component

- [ ] For request headers, update the header from `Key` to `Name`

<img width="515" alt="Screen Shot 2020-05-04 at 11 34 12 AM" src="https://user-images.githubusercontent.com/11410997/81000567-50324180-8dfb-11ea-8da7-ee67ee1f4286.png">

**TCP Requests (`tcpSocket`)**

Field Name | k8s yaml | Field Type
---|---|---
Check Port | `tcpSocket.port` | Textbox

<img width="466" alt="Screen Shot 2020-05-04 at 10 31 00 AM" src="https://user-images.githubusercontent.com/11410997/80994971-5d96fe00-8df2-11ea-8f31-42c7be54f270.png">

**Command (`exec.command`)**
Field Name | k8s yaml | Field Type
---|---|---
Command to run | `exec.command` | Textbox

<img width="470" alt="Screen Shot 2020-05-04 at 10 31 21 AM" src="https://user-images.githubusercontent.com/11410997/80995007-6a1b5680-8df2-11ea-90f5-74a965778c59.png">

#### Fields for all Health Check Types

Field Name | k8s yaml | Field Type
---|---|---
Check Interval | `periodSeconds` | Textbox for `int` with `sec` label
Success Threshold | `successThreshold` | Textbox for `int`
Failure Threshold | `failureThreshold`| Textbox for `int` 
Initial Delay | `initialDelaySeconds` | Textbox for `int` 
Timeout | `timeoutSeconds` | Textbox for `int` with `sec` label

<img width="508" alt="Screen Shot 2020-05-04 at 10 35 14 AM" src="https://user-images.githubusercontent.com/11410997/80995335-f4fc5100-8df2-11ea-8dbf-fdbe5b83c0d3.png">
 
## Security Context tab
All these fields are nested under `<containersSpec>.securityContext`.

Field Name | k8s yaml
---|---
Privileged | `privileged`
Privilege Escalation | `allowPrivilegeEscalation`
Run as Non-Root | `runAsNonRoot`
Read-Only Root Filesystem | `readOnlyRootFilesystem`
Run as User (currently under the Command tab in current workloads page) | `runAsUser`
Add Capabilities | `capabilities.add`
Drop Capabilities | `capabilities.drop`

<img width="743" alt="Screen Shot 2020-05-04 at 10 37 38 AM" src="https://user-images.githubusercontent.com/11410997/80995587-57555180-8df3-11ea-9161-7dc7b5305caf.png">
<img width="820" alt="Screen Shot 2020-05-04 at 10 37 55 AM" src="https://user-images.githubusercontent.com/11410997/80995591-59b7ab80-8df3-11ea-9aca-897afb00a0ef.png">
<img width="262" alt="Screen Shot 2020-05-04 at 10 38 20 AM" src="https://user-images.githubusercontent.com/11410997/80995613-63411380-8df3-11ea-93ba-d3d3ad151adb.png">
<img width="1070" alt="Screen Shot 2020-05-04 at 10 38 46 AM" src="https://user-images.githubusercontent.com/11410997/80995655-7358f300-8df3-11ea-8c43-f5b402c1311a.png">

## Volume Devices tab
All these fields are nested under `<containersSpec>`.

> **Note**: I need to discuss with @ibuildthecloud before moving forward with this tab.

Field Name | k8s yaml
---|---
Volume Devices | `volumeDevice
 

# Adding/Removing Containers

When the `Container` component is used, you will need to be able to add/remove containers. In these mocks, ignore the content of the container component itself as the details are listed above, but focus on how we would expect how to add and remove containers and display multiple containers.  

**`Remove` link and `Add Container` button. **
<img width="782" alt="Screen Shot 2020-05-04 at 11 39 31 AM" src="https://user-images.githubusercontent.com/11410997/81001050-00a04580-8dfc-11ea-811e-aa2f82274f6c.png">

**Multiple Containers - Note the line separating the containers**
<img width="791" alt="Screen Shot 2020-05-04 at 11 40 40 AM" src="https://user-images.githubusercontent.com/11410997/81001106-1877c980-8dfc-11ea-8ec1-5cadf2e9d815.png">

**Comment by deniseschannon** [comment]
@lvuch can you create a mock for the Healthcheck tab and Security Context tab?

**Comment by lvuch** [comment]
https://xd.adobe.com/view/0603fc0b-5f93-4cbc-747b-aa82ebe818cc-7032/
page 3: health check
page 4: security
<img width="547" alt="Screen Shot 2020-05-04 at 3 37 39 PM" src="https://user-images.githubusercontent.com/3013118/81020240-373a8800-8e1d-11ea-89da-9a024ed1a003.png">
<img width="547" alt="Screen Shot 2020-05-04 at 3 37 30 PM" src="https://user-images.githubusercontent.com/3013118/81020241-39044b80-8e1d-11ea-8d23-5ac13fc8d7a3.png">

**Comment by lvuch** [comment]
<img width="556" alt="Screen Shot 2020-05-12 at 3 00 02 PM" src="https://user-images.githubusercontent.com/3013118/81749867-4cd53080-9461-11ea-99d3-25d7d0173cca.png">
