### ISSUE TITLE
Allow users to add Cloud Credential with inactive Amazon EC2 Node Driver

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5962]
Internal reference: SURE-4242
Reported in 2.5.9

Request description:
The user wants this configuration for their env:

- Cluster Drivers: Amazon EKS - active
- Node Drivers: Amazon EC2 - inactive

However, this is not an expected use case now, so they need to activate 'Node Drivers: Amazon EC2' as well.

Actual behavior:
When Amazon EC2 Node Driver is no active, users can not add Cloud Credential. This is by design for now. 

Expected behavior:
Users can add Cloud Credential even with inactive Amazon EC2 Node Driver

Workaround:
Is workaround available and implemented? yes
What is the workaround:

Activate 'Node Drivers: Amazon EC2', add Cloud Credential, and then disable 'Node Drivers: Amazon EC2' again.

**Comment by nwmac** [comment]
This is caused by a backend isuse: https://github.com/rancher/rancher/issues/39399

**Comment by nwmac** [comment]
Backend issue fixed

**Comment by slickwarren** [comment]
repro'd on 2.6.9 and tested using v2.7-head (d1249b5):
* deactivate the aws node driver
* create an aws cloud credential -- pass
* create the cloud credential via the eks cluster creation workflow -- pass

additional testing:
activate / deactivate a new driver -- pass
