### ISSUE TITLE
Ability to specify helm override values.yaml file path in targetCustomizations

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5963]
Internal reference: SURE-3345
Reported in 2.5.9

As a user, I would like to specify override override values.yaml file path in targetCustomizations as it provides a simpler UX.

Actual behavior:
Can specify individual helm override options in targetCustomizations block but not a filepath.

Expected behavior:
Be able to specify the filepath.

Additional notes from the user:
Without it, the pipeline is working. However, we usually have a repo (of course it is just a git repo rather than a chart repo) to hold charts values of all applications. Developers have full access to it. While deploying, images are built and applied to pipeline automatically as well as values they call. They are eventually assembled into fleet yaml files. We would like to keep repo of fleet yaml files accessible by pipeline only. It is fine to put all charts values into fleet yaml, while it is neater if it is possible to call a url or path of a values file.

**Comment by catherineluse** [comment]
@gaktive Which helm chart app is this for? The internal ticket redirects to something that seems unrelated.

**Comment by gaktive** [comment]
Related support ticket closed so doing the same here. If anyone still runs into this, check if this is the case in a newer version and reopen.
