### ISSUE TITLE
Unable to create a cluster when RKE templates override option is enabled and override parameters are set to required

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5967]
Setup

Rancher version: 2.5.14-rc1
Browser type & version: Chrome

**Describe the bug**
Created a cluster template with option override and then if we mark `Cluster Option Override Parameters` [located at the bottom of the RKE template page] as Required. If we use this RKE template while creating a cluster, we would need to input the required values but even after providing the required value.

**To Reproduce**
1. Create an RKE template as an admin by enabling private registry by providing the required URL, username and password
2. Enable override values for URL, username and password. 
3. Enable required override parameters at the bottom of the RKE template page 
4. Create a cluster with the RKE template created above
5. Provide the password

**Result**
Cluster creation fails with the error `"rancherKubernetesEngineConfig.privateRegistries[0].password" is required` 

**Expected Result**
Cluster creation goes through.

**Additional context**
`"rancherKubernetesEngineConfig.privateRegistries[0].password" is required` and notice the `%%` added to the 
`Maximum Worker Nodes Unavailable10%%` when we try to re submit.

**Comment by gaktive** [comment]
For context, this has been spotted going far back as 2.5.12 but not 2.6-head so it's not a true regression. Putting this in the 2.5.x backlog for now.

**Comment by catherineluse** [comment]
Terminology note: This is about RKE templates (the policies that restrict cluster config options) not cluster templates (the feature where you can define a cluster as a Helm chart in a GitHub repo).

**Comment by gaktive** [comment]
2.5.x is now EOL so closing as won't fix: https://www.suse.com/support/kb/doc/?id=000020631
