### ISSUE TITLE
Can the UI detect the docker root directory for rancher logging?

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5977]
A question arose from https://github.com/rancher/rancher/issues/33714

Main problem there: when installing rancher logging on a cluster with a non standard docker root, users need to manually pass in the docker root directory. 

Proposal for UI: can we read the node(s) in the cluster where rancher-logging is deployed to and fill in the value for the chart? Part of that ask is based on what's not doable at install time through Helm so the fall back for the backend would be something that would run in parallel to detect it.

@superseb suggested the following as guidance, namely adding a new field: 

From: `dashboard/c/c-4r8ck/manager/management.cattle.io.node/c-4r8ck/m-67fef51ccdc0`

```
apiVersion: management.cattle.io/v3
kind: Node
  name: m-67fef51ccdc0
  namespace: c-4r8ck
  resourceVersion: "4844"
  uid: 062180d7-91ab-4e04-a0cd-39ff0f78dad9
status:
  dockerInfo:
    DockerRootDir: /var/lib/docker
```

The logging page would then have this view:
![169062945-b8293a8d-e93e-4300-b021-e242ee74c51a.png](https://zube.io/files/rancher/b57cb666020964955dce2965495008c8-169062945-b8293a8d-e93e-4300-b021-e242ee74c51a.png)

**Comment by catherineluse** [comment]
I believe the answer to this question is no, because Rancher relies on Norman and Steve to get information on Kubernetes nodes.

**Comment by gaktive** [comment]
Based on what we know, the UI can't do this since we get everything from the API.
