### ISSUE TITLE
For RKE2 node pools, allow selecting an existing machine config instead of always creating a new one

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5981]
This feature is available if you are using Terraform. We've had requests to also make this selectable from the Rancher UI.

Edit: 
I propose allowing users to edit DigitaloceanConfigs or the equivalent for each infrastructure provider. I think we should be able to change the machine pools section of the form so that by default, you create a new config object, but you can also reference an existing one. However, I couldn't create a DigitaloceanConfig from YAML, as it seems to have to be auto-generated when you create the cluster provisioning resource. Still need to find out why the create/edit functionality for these resources is hidden or disabled in the UI.

**Comment by gaktive** [comment]
Need to talk with someone in the backend with Terraform experience what UI needs to do here.

**Comment by catherineluse** [comment]
Gaurav said the name of the resource we want is MachineTemplate:

> the MachineTemplate should be reusable across MachinePools / MachineSets, from a sample cluster template.. https://github.com/ibrokethecloud/cluster-template/blob/main/digitalocean/templates/cluster.yml#L57-L67

I asked Donnie about the technical limitation where we don't allow reusing the same machine configs in RKE2 cluster provisioning. He offered these reasons to help explain why it is the way it is:

- By not allowing machine configs to be reused, it simplifies RBAC a lot. It would be much more complicated to give individual users access to different machine config resources in the same namespace.
- When we create a new machine config every time, each one has an owner ref defined in it, which makes it associated with the one specific cluster. The advantages of this are that a) they will show up in the Related Resources tab of the resource detail page, and b) it is easy to clean up the machine config when a cluster is deleted.

If the ask is just to make it easier to fill out the form, it would be relatively easy to just help the user clone values from one node pool to another. We already have a cloning mechanism for creating custom roles and such.

It would require a lot more work, on both front end and backend, to treat machine configs more like node templates with a whole separate system of RBAC and access control where one person can create it and share it with others. We should confirm that this is a smaller ask and that it's just about reusing the same machine config templates that already exist in the cluster, and that you already have access to because you created them yourself.

**Comment by catherineluse** [comment]
The difference between a machine config and node template is that node templates are only for provisioning RKE1 clusters and machine configs are only for provisioning RKE2 and K3s clusters. The reason that machine configs are only for RKE2/K3s is that those clusters are provisioned with Cluster API (CAPI) and the machine config is designed specifically to work with CAPI.

**Comment by catherineluse** [comment]
Based on a quick look at the CAPI docs https://cluster-api.sigs.k8s.io/tasks/updating-machine-templates.html, it looks like another key difference is that machine templates are supposed to be immutable. That could explain why they were not treated as a drop-in substitute for node templates, since we allow editing node templates.

**Comment by johnwc** [comment]
It sounds like k8s machine template and rancher node template are the same thing. In rancher, how do we utilize a template for a pool?

Please review the scenario stated at the bottom of this issue on why we need to be able to utilize and update pool node templates
https://github.com/rancher/dashboard/issues/6020

**Comment by catherineluse** [comment]
> It sounds like k8s machine template and rancher node template are the same thing.

For the scenario in your issue, if you were using an RKE1 node template, you would be able to update the config. My interpretation of the CAPI docs is that Rancher will not be able to let you modify the machine template because it is considered immutable by CAPI. So in your case you would need to create a new node pool through the Rancher UI.

In CAPI it says you can edit a machine pool to swap out a reference to an old machine config to a new one. My thought is that if Rancher were to bring a similar UX to RKE2 cluster provisioning as we have for RKE1, we would basically have to fake the appearance of modifying the machine template in the UI. Basically, the implementation of "editing" a node pool would involve creating a new machine config and editing the node pool to point to the new one.

**Comment by johnwc** [comment]
As I stated in my other comment, the capi states you can do exactly what you are saying. You can edit a pool to use a different machine config. So this wouldn't be faking any appearance, this would be allowing to do what the capi supports. Not having to create a whole new pool to use the new machine config, just edit the existing pool to use the new machine config.

**Comment by catherineluse** [comment]
I think we are on the same page, it's just that my comment wasn't clear. When I said you would have to create a new node pool in Rancher, I meant that as the best workaround that the Rancher UI currently offers, not what is required by CAPI.

**Comment by catherineluse** [comment]
I learned a bit more about this from watching Donnie's knowledge transfers, so I'm going to capture my notes here to help with implementation later.

Although each infrastructure provider provides their own machine template CRDs to use with CAPI, we don't use those directly. Instead we created our own version of the CRDs for each infrastructure provider we support. Our CRDs have the type `<provider>machines.rke-machine.cattle.io`. We have created CRDs for:

- `Amazonec2Machines`
- `AzureMachines`
- `DigitaloceanMachines`
- `HarvesterMachines`
- `LinodeMachines` 
- `VmwarevsphereMachines`.

The primary reason we created these provider-of-a-provider CRDs is so that RKE2 cluster provisioning can have full feature parity with RKE1 provisioning, specifically so that Rancher can provision each node using flags passed to the `rancher-machine` CLI.

In addition to that, the custom resources of type `<provider>configs.rke-machine-config.cattle.io` contain all the provider-specific configuration to create machines. When you create a resource of that type, Rancher creates the objects needed for Cluster API to be aware of those machines. 

While the CAPI clusters are at `cluster.x-k8s.io.cluster`, Rancher's cluster provisioning cluster resource is at `provisioning.cattle.io.cluster`. The latter resource has a concept of node pools, while the former does not reference machine configs at all. The `provisioning.cattle.io.cluster` has machine info at `spec.rkeConfig.machinePools` and each machinePool there has a `machineConfigRef`. Those point to Rancher's special infrastructure config objects, for example a `DigitaloceanConfig`.

While CAPI does have a concept of MachinePools, Rancher does not use them due to the fact that they are experimental. So Rancher must use MachineDeployments in order for CAPI to keep track of nodes. (CAPI introduced MachinePools to replace both MachineDeployments and MachineSets.) So while Rancher's cluster resource does define node pools in its YAML, these do not reference CAPI's MachinePools.

Rancher uses a `machineConfigRef` to map between Rancher's cluster resource and CAPI. For example, let's say I have a provisioning cluster resource in which there is a node pool at `spec.rkeConfig.machinePools`, and in that node pool is defined a `machineConfigRef` pointing to a `DigitaloceanConfig`. That config is what I created when filling out the form to provision an RKE2 cluster. When Rancher creates a corresponding MachineDeployment for CAPI, it is named `c2-pool` and the same machine config details are under `spec.template.spec.infrastructureRef`, except the details are in a `DigitaloceanMachineTemplate` instead of a `DigitaloceanConfig`. From what I understand, Rancher copied the details from the `DigitalOceanConfig` to the `DigitalOceanMachineTemplate`.

In my local testing, I tried editing a `DigitaloceanConfig` referenced by one of my node pools just to see what would happen. When I changed a value in it, it triggered a new `DigitaloceanMachineTemplate` to be created. Then I checked the YAML for the `MachineDeployment` created by the same node pool and confirmed that its `infrastructureRef` had indeed been changed to point to the new `DigitaloceanMachineTemplate`'s name. And when I went to Edit Config for the cluster, the node pool reflected the change.

That approach seems promising to me but I don't know if it's recommended, so I'll ask some more questions about it next week.

**Comment by catherineluse** [comment]
After talking with the backend cluster provisioning team, it sounds like this would be a lot of effort and would not be worth it, given other more important priorities. I am moving this ticket to To Test for QA to acknowledge this issue as a won't fix.

**Comment by johnwc** [comment]
How can we create node templates for Harvester?

**Comment by johnwc** [comment]
@catherineluse is there a documentation _guide_ on automating cluster creation with config yaml files?
