### ISSUE TITLE
Resource Quota - Inconsistent height of limit fields  

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#6006]
**Setup**
- Rancher version: v2.6-head (0e2fdc8)
- Browser type & version: Firefox Developer 101.0b7 (64-bit)

**Describe the bug**

The height of the limit fields are taller than the other fields in the row. (screenshots below)

**To Reproduce**

1. Navigate to create project --> members --> resource quotas
2. Click on Add a Resource

**Result**
Project Limit and Namespace default limit are too tall

**Expected Result**

Project Limit and Namespace default limit are the same height as resource type dropdown

**Screenshots**

![image](https://user-images.githubusercontent.com/835961/169566158-9b7c5710-0aba-4424-9987-6ce86b07556d.png)

**Context**
Discovered while reviewing rancher/dashboard#5504

> Minor styling issue
> 
>     * create project --> members --> resource quotas --> height of limit fields has grown (when compared with 2.6.5)

This is an existing issue in `v2.6-head` (`0e2fdc8`), unrelated to this change. Here's what a new instance of Dashboard looks like this morning

![image](https://user-images.githubusercontent.com/835961/169566158-9b7c5710-0aba-4424-9987-6ce86b07556d.png)

_Originally posted by @rak-phillip in https://github.com/rancher/dashboard/issues/5504#issuecomment-1133064791_

**Comment by nwmac** [comment]
This has been fixed:
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/1955897/201653554-8d13aae0-5de4-4651-8a52-e2a634f2eaf8.png">

**Comment by AndrewHoffmanQA** [comment]
retest passed

QA  tested on HA local 2.7head 44d3d40

screenshot

![image.png](https://zube.io/files/rancher/1847dd2cb3488cf63c2ccaf772790874-image.png)
