### ISSUE TITLE
"Failed while: mgmt cluster create" when creating RKE2 cluster

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6010]
Internal reference: SURE-4658
Reported in 2.6.5

Issue description:
When provisioning an AWS cluster using node driver, often getting a "Failed while: mgmt cluster create" error after clicking create. Options chosen for cluster seem to be irrelevant. Doesn't happen consistently. If you navigate back to Cluster Management, cluster was created and provisions successfully

Business impact:
Error message indicates cluster was not created and is poorly worded. May prompt users to file support cases or GitHub issues.

Repro steps:

Create an RKE2 cluster, using EC2 nodes. (doesn't seem to matter what options are selected)

Workaround:
Is workaround available and implemented? no

Actual behavior:
Error message is displayed, but cluster does eventually provision.

Expected behavior:
No error message is displayed. Or error is displayed that properly describes the problem that was hit.

Additional notes:
Backend found the reference here: https://github.com/rancher/dashboard/blob/0ae5d741dac5129dc74655ce24bd0f6aea18f644/shell/models/provisioning.cattle.io.cluster.js#L205

We need a better worded message here, especially if the cluster was actually created properly. If this is tied to a race condition, we have to take that into consideration.

**Comment by Josh-Diamond** [comment]
Ticket #6010 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.5`:
1. Fresh install of rancher `v2.6.5`
2. Provision a downstream AWS Node driver RKE2 cluster - [issue intermittent; more easily reproduced with high resource cluster specs]
3. Reproduced - Error is encountered; cluster provisions successfully

Screenshots:

`Error`
<img width="1583" alt="Screen Shot 2022-06-14 at 9 59 07 AM" src="https://user-images.githubusercontent.com/46494969/173634331-b89b2eca-9bbc-4807-abdb-b7d9f8eea0f1.png">

`Cluster Successfully Provisions`
<img width="1594" alt="Screen Shot 2022-06-14 at 9 59 29 AM" src="https://user-images.githubusercontent.com/46494969/173634516-ef923070-a4de-4f6d-bfc2-3e63ba477e36.png">

---

Verified on rancher `v2.6-67c2c49953f11f8a39bf0231a13b521517197da3-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream AWS Node driver RKE2 cluster - [give cluster high resource availability in hopes of catching error]
3. Verified - Unable to encounter issue with extended timeout fix;

If encountered, new error will read:
![172713277-cd1e538d-8d25-46e3-b364-2950befacbb1](https://user-images.githubusercontent.com/46494969/173638038-ae946f09-4432-4eee-991c-29915f0e38b8.png)
