### ISSUE TITLE
"Neuvector" not capitalized correctly in left side menu (should be NeuVector)

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6012]
Internal reference: SURE-4656
Reported in 2.6.5

After installing NeuVector, a new section called "Neuvector" is displayed in the left side menu. It should read "NeuVector"

Repro steps:
Install rancher and add the NeuVector app from the Apps & Marketplace

**Comment by sowmyav27** [comment]
On 2.6head `a8ae635`

- Reads `NeuVector` now
<img width="740" alt="Screen Shot 2022-06-23 at 3 35 20 PM" src="https://user-images.githubusercontent.com/26032343/175426241-a1966f55-0b6f-4855-98a7-7230e4ac6570.png">
