### ISSUE TITLE
Fleet cluster object is misleading when editing cluster labels

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6014]
Internal reference: SURE-4642
Reported in 2.6.4

A user automates their tasks and had a missing label issue on fleet clusters, this was due to the labels needing to be applied to the Rancher cluster object (management.cattle.io), not the fleet cluster object (fleet.cattle.io).

This was misleading with the continuous delivery UI area displaying the fleet.cattle.io CRD in the URL bar when editing cluster configuration, or as YAML.

It turns out tags applied to clusters in fleet via 'Edit Config' in the UI involve a PUT to the Rancher cluster object, and the sync between Rancher/fleet cluster objects are one-way - Rancher -> fleet.

Business impact:
UX annoyance and misleading direction of how to perform changes for different areas

Repro steps:

- Add tags to the list of a clusters fleet.cattle.io object - either as 'Edit as YAML' in the UI or with kubectl.
- The above changes don't show the tags on the cluster in the UI
- Add tags to the list of a clusters cattle.management.io object (same methods as above)
- The tags now show in the UI, and are replicated to the fleet.cattle.io object

Workaround:
Is workaround available and implemented? yes
What is the workaround: Depending on change, apply it to the correct object, for tags, always apply to the Rancher cluster object.{}

Expected behavior:
Merge of tags bi-directionally or note in UI, docs etc.

**Comment by izaac** [comment]
Rancher version: `v2.6.7-rc5`
Rancher version: `v2.6-head` `6629e3e` (08/01/2022)

There's a tooltip explaining the functionality to the end user, see screenshot:

![Screen Shot 2022-08-01 at 2 55 49 PM](https://user-images.githubusercontent.com/27659/182253470-678164e6-609a-4d55-8a8a-ac73ad3d626a.png)

> Label changes are made to the Management Cluster and synchronized to the Fleet Cluster.
