### ISSUE TITLE
Cancel the time display on the view logs page

### ISSUE THREAD

**Issue by AbelHugh** [rancher/dashboard#6015]
**Setup**
- Rancher version: v2.6.5
- Browser type & version: chrome 100

**Describe the bug**
 - To Fix [#5979](https://github.com/rancher/dashboard/issues/5979)
 - The logs printed by the application generally include the time, so there is no need to display the time in the view logs page

@richard-cox
@catherineluse

**Comment by richard-cox** [comment]
Had a quick look, the timestamps are already optional and it's just enabled by default. There's places where the date/time stamp isn't included in the logs so this seems reasonable.

![image](https://user-images.githubusercontent.com/18697775/170083000-f07da723-e1e1-4512-883c-ad1a07ac8207.png)
