### ISSUE TITLE
Rollback revision list shows relative times only

### ISSUE THREAD

**Issue by hameno** [rancher/dashboard#6022]
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Chrome 101.0.4951.67

**Describe the bug**
The revision list only shows relative times, there is no way to see the actual date.
See
![image](https://user-images.githubusercontent.com/365084/169959482-2710bc2f-f5cb-4bbd-bc2a-76fa07bf77bf.png)
This is not very helpful in finding the correct time

**Comment by rak-phillip** [comment]
@gaktive @kwwii I asked that we get an issue together for this so we can take a closer look. I think we have an opportunity to improve the UX a little bit here, what do you think?

**Comment by kwwii** [comment]
@rak-phillip Agreed, perhaps something like this would be better:

Rev. 179 - 24.05.2022 9:45am
Rev. 180 - 24.05.2022 7:00am
Rev. 181 - 17.05.2022 9:45am
Rev. 182 - 15.05.2022 7:00am
Rev. 183 - 17.04.2022 9:45am
Rev. 184 - 15.04.2022 7:00am

**Comment by rak-phillip** [comment]
I think it looks good. My only feedback is that we should make sure we're consistent with how we format date/time in other areas of dashboard. I took a peek to find other examples of formatting dates and we definitely prefer the "created `n` days ago" approach. Perhaps, this isn't too much a of a concern for us..

I'm not too sure on the original motivation for formatting dates this way, but I find it to be a little informal for something like this.

**Comment by catherineluse** [comment]
We should probably use the user's preferred date format that is configured in the global settings.

**Comment by catherineluse** [comment]
@gaktive  @kwwii Can we prioritize this one? There are a lot of people asking for a fix on the backend ticket. https://github.com/rancher/rancher/issues/35138

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE2 cluster. Create a test deployment, edit the image pull policy, validate that the rollback shows the timestamp in the format of user preferences|
|2|Repeat scenario 1 with a new deployment. Afterwards, modify the user preferences time format and validate that the rollback shows the updated format|

**Comment by markusewalker** [comment]
Validated this against `v2.7-head` https://github.com/rancher/rancher/commit/edf59f620ceec6b3f22507b4d1ac780d392568df.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/edf59f620ceec6b3f22507b4d1ac780d392568df
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 cluster. Create a test deployment, edit the image pull policy, validate that the rollback shows the timestamp in the format of user preferences|:white_check_mark:|
|2|Repeat scenario 1 with a new deployment. Afterwards, modify the user preferences time format and validate that the rollback shows the updated format|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigated to Cluster Management > Create > Toggled RKE2/K3s.
3. Provisioned a downstream RKE2 node driver cluster; validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
4. Navigated to Cluster Explorer > Workloads > Deployments > Create.
5. Created a test deployment, ensured that it came up as `Active`.
6. Edited the config of the test deployment and updated the `ImagePullPolicy` from `Always` to `IfNotPresent`.
7. Edited the config again and reverted the ImagePullPolicy back to `Always`.
8. Attempted to rollback and validated that the time format matches my current user preference:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/52591819/206539908-3a42459d-1f04-4628-90b4-f0a72e27083b.png">
<img width="840" alt="image" src="https://user-images.githubusercontent.com/52591819/206539935-2d37aa10-d5d8-44a5-a1da-f957bccd31b0.png"> 
9. Rolled back the deployment to the mentioned `Revision 2`; this was successful and validated that the pull policy is back to `IfNotPresent`.

___________
**Scenario 2**
1. Repeated scenario 1, but with a new deployment; validated that the result was the same.
2. Navigated to user profile > Preferences.
3. Updated the time format to the following:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/52591819/206540011-dd48e811-fb78-450b-9f37-4823bdd2b7db.png"> 
4. Navigated back to Cluster Explorer > Workloads > Deployments > testdeployment2.
5. Attempted to rollback and validated that the new time format has been picked up:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/52591819/206540040-44dcafe2-1eca-4635-98e0-1870ff7dd2f5.png"> 
6. Rolled back to the aforementioned `Revision 3`; this was successful.
7. Edited the deployment config and validated that the image pull policy is back to `Always`.
