### ISSUE TITLE
The time format of the cluster dashboard page is displayed incorrectly

### ISSUE THREAD

**Issue by AbelTaylor** [rancher/dashboard#6023]
- Rancher version: v2.6.5
- Browser type & version: chrome 100

**Describe the bug**
as follows
![image](https://user-images.githubusercontent.com/71317399/169963755-d37cf312-ad68-4ee0-aa1f-939eb2764bc9.png)

**Comment by rak-phillip** [comment]
@AbelTaylor thanks for raising the issue. 

I can reproduce in `v2.6.5`, but not in our latest development builds and looks to have been fixed with #5999

@gaktive I'm adding the `[zube]: To Test` label so that we know to confirm that this has been resolved.
