### ISSUE TITLE
Design Issues - Dropdown

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#603]
When there is no label for a dropdown, the height of the dropdown is different than with a label. Should we make all dropdowns the same height regardless of label? Or will we require a label for every dropdown?

This is from the Environment Variables from a Resource on the workloads page inside the Command tab. 

<img width="1072" alt="Screen Shot 2020-05-04 at 4 53 54 PM" src="https://user-images.githubusercontent.com/11410997/81024476-64406800-8e28-11ea-8c45-d03d052b59ed.png">

**Comment by deniseschannon** [comment]
I think the dropdown without a label will need to increase to match the labeled input height because of when you use the dropdown in scenarios where there is a label header:

<img width="433" alt="Screen Shot 2020-05-08 at 1 40 24 PM" src="https://user-images.githubusercontent.com/11410997/81447453-7de7f500-9131-11ea-8a10-56518f08ec36.png">

**Comment by lvuch** [comment]
paired with @mantis-toboggan-md. labels should be outside of inputs but just at top of each column. <KeyValue> is an example of how this should look and act.

**Comment by deniseschannon** [comment]
I see that dropdowns are the same height as textboxes now.

<img width="600" alt="Screen Shot 2020-05-22 at 2 47 21 PM" src="https://user-images.githubusercontent.com/11410997/82711784-43a34b00-9c3b-11ea-9c9a-b6398e6f72a2.png">
