### ISSUE TITLE
Importing a private AKS cluster results in the registration tab being absent in the cluster details view

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#6036]
**Rancher Server Setup**
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/e35d32feea3ff9511d972b87f14a4f66b194db39
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.23.5`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported AKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard
  - If custom, define the set of permissions:

   
**Describe the bug**

When importing a private AKS cluster into Rancher, you are able to register the cluster as expected. What is unexpected is that when you look into the cluster details, there is no registration tab. See below:

![Screen Shot 2022-05-25 at 9 42 05 AM](https://user-images.githubusercontent.com/52591819/170316498-4d2a398d-7657-4868-aeeb-fdc0659db685.png)

Whether you create a private AKS cluster via the Azure UI or use the `az` cli, the above result is the same. One point to consider is that the cluster agent uses the cattle service account in Rancher to authenticate for redeploy on a private cluster. However....the cattle service account and the secret autogenerated for it were not created in Rancher.

Additionally, I was able to verify this behavior in `v2.6.5` as well, so this is not a direct regression from the last release per say.

**To Reproduce**
 
1. Create a private AKS cluster using either the `az` cli or directly in the Azure marketplace.
     - Versions `v1.23.5` and `v1.22.6` both showed this behavior.
     - Network policy that is chosen will not matter, issue happens regardless if you choose `None` or specify a CNI.
2. Setup Rancher `v2.6-head` and navigate to the UI in a browser.
3. Create a standard user and login to Rancher as that newly-created user.
4. In Cluster Management, import an existing cluster and choose AKS.
5. Fill out the prompted information and import the previously created private AKS cluster.
6. As it is being created, click the cluster and you should NOT see the registration tab.

**Result**
The registration tab is not present when importing an existing private AKS cluster.

**Expected Result**

The registration tab should be present when importing an existing private AKS cluster.

**Comment by gaktive** [comment]
Related to https://github.com/rancher/dashboard/issues/4545 (though that's EKS)

**Comment by rak-phillip** [comment]
We have some rules that we use to conditionally render the registration tab so we might need to revisit those to understand what needs to change. As it stands now, I don't have enough information to make an informed decision about why the Registration tab might not be showing and what we would need to modify in order to correctly show it. Here's the rundown of the logic for rendering the registration tab:

```
If there is no cluster token
  Don't render the Registration Tab

If the cluster is Imported
  If management is ready
    Don't render the Registration Tab
  Else
    Render the Registration Tab

If the cluster is custom
  Render the Registration Tab

If none of the conditions above
  Don't Render the Registration Tab
```

This change came in about a year ago, in response to #3337. But the only requirement that I can glean from the change is the we shouldn't show the Registration tab when the cluster is "Ready". 

https://github.com/rancher/dashboard/pull/3381/files

@gaktive @markusewalker

**Comment by gaktive** [comment]
@kwwii to review the flow around this section and @jordojordo to take this over from @rak-phillip. This may address https://github.com/rancher/dashboard/issues/6112 but TBD.

**Comment by jordojordo** [comment]
Following a discussion with @kwwii, we decided it would make sense to modify this conditional [here](https://github.com/rancher/dashboard/blob/5edf8db25c3a47dc72ce0501659a2a01725e9fe9/shell/detail/provisioning.cattle.io.cluster.vue#L351) to show the registration tab depending on some arbitrary condition like `status: Unknown, type: Pending`. 

After some investigation, I found that there is no way to know if an imported cluster is using a private endpoint unless the cluster agent has connected, which it cannot do if not provided the private endpoint (naturally).

We should add a banner warning the user of using the registration command more than once, for example:
> "When importing a cluster with a private API server endpoint - it will need to be registered the first time in order to complete the import. Running the command a second time will cause serious issues."

With that in place we should also have a button to show the registration commands to acknowledge that the user has seen the warning.

**Comment by dnoland1** [comment]
@jordojordo What serious issues would be caused by running the import command a second time? There are some valid uses cases when a downstream cluster's agent workload was accidentally modified and the best way to recover or repair is to re-run the import to repair configuration, deployment, pods, etc. Is the "serious issues" warning needed or warranted?

**Comment by kwwii** [comment]
@richard-cox Can you explain the issues that arose for you when running this command after the cluster had already been imported?

Does anyone know if there a difference in behavior when running this command again after import in AKS vs EKS clusters? (There are similar issues open for both types)

**Comment by richard-cox** [comment]
Thought about this last night, and i had it the other way around. I'd brought up a new rancher and imported an existing cluster that was connected to a previous rancher. The cluster had references to system/default projects from the old rancher and thus namespaces weren't grouped correctly in the project/namespace list.

**Comment by kwwii** [comment]
In that case, we can always show the Registration tab with the information and add a warning that they should not import a cluster which has already been connected to another instance of Rancher as it will lead to data corruption (or something like that).

**Comment by rak-phillip** [comment]
There's also concern that the registration command can be inadvertently run on a different cluster, breaking the current cluster.

> Once the cluster is imported it's useless and also a bit dangerous to show the Registration command. User then may run the command by mistake on different cluster which would probably broke the current imported cluster.

**Comment by markusewalker** [comment]
@gaktive @jordojordo circling back to this issue to verify this is on track for v2.6.7? Thanks!

**Comment by jordojordo** [comment]
@markusewalker The pr (#6226) that will resolve this is waiting on a re-review, will keep you posted on the progress.

**Comment by tuupola** [comment]
> Thought about this last night, and i had it the other way around. I'd brought up a new rancher and imported an existing cluster that was connected to a previous rancher. The cluster had references to system/default projects from the old rancher and thus namespaces weren't grouped correctly in the project/namespace list.

Is this still the case with recent versions of Rancher?

**Comment by richard-cox** [comment]
@tuupola The action in that specific quote is an unsupported process. I think there is a flow to clean the cluster first to then re-import it, though haven't tried it in a while https://ranchermanager.docs.rancher.com/faq/rancher-is-no-longer-needed#what-if-i-dont-want-rancher-anymore

**Comment by rodriguezmelian** [comment]
The solution is create a NameSpace cattle-fleet-system if you don´t have the resource in your Cluster
