### ISSUE TITLE
Deployments: Events tab only shown when there are events

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6057]
On a workload detail page, the 'Recent Events' tab is only shown when there are events:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/1955897/170697584-63beadec-94a1-48e6-a936-ac083a1951c8.png">

We should show this all the time

**Comment by Josh-Diamond** [comment]
Ticket #6057 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-4199cac04da5174351d99255695cce9b3b555073-head`:
1. Fresh install of rancher `v2.6-head`
2. Deploy a downstream cluster - [ANY]
3. Deploy a new CronJob deployment - [set for every hour]
4. Verified - `Recent Events` tab is shown when no events are found

Screenshot:

`Step 4`
<img width="1424" alt="Screen Shot 2022-06-06 at 10 05 05 AM" src="https://user-images.githubusercontent.com/46494969/172210378-768e608e-9add-4fc7-aa9b-c2e22a1a0393.png">
