### ISSUE TITLE
Add warning that Azure AD API will be decommissioned by the end of 2022

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6060]
Microsoft is going to turn off the Azure AD API, which means users who are authenticated through it will no longer be able to log in to Rancher.

There is an email being sent to customers about this, but I think we should also put a banner in the UI warning people that service will be disrupted if the Rancher app is not added to the new API in the Azure portal.

**Comment by nwmac** [comment]
@mantis-toboggan-md Do we now have this with the work you did for 2.6.7?

**Comment by mantis-toboggan-md** [comment]
Yes: This is covered by #5739 and #5671 in 2.6 and #6316 in 2.5
