### ISSUE TITLE
Update static loading indicator to respect dark mode

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6065]
**Setup**
- Rancher version: 2.6.5

**Describe the bug**
When dark mode is enabled / picked up by OS theme the user goes from a dark mode log in page, bright white loading page and then a dark home page. It can be quite a quick transition so the page can flash.

~~The file is `/shell/components/Loading.vue`~~ see comment

**Comment by richard-cox** [comment]
Update - the issue is to do with the default loading indicator used by nuxt 

```
loadingIndicator: path.join(SHELL_ABS, 'static/loading-indicator.html'),
```
That's a raw html file so skips our entire branding/theme code (including overrides from BE)

Thought about making the default stark white background a bit darker, but then we'd hit the opposite issue for light mode. 

I'd like to look at this again after https://github.com/rancher/dashboard/issues/5968

**Comment by nwmac** [comment]
Is this done now, @richard-cox ?

**Comment by richard-cox** [comment]
Completed by Cody via https://github.com/rancher/dashboard/pull/7211

**Comment by gaktive** [comment]
Engineering to write an automated test for the login page in #8808 to help QA.

**Comment by richard-cox** [comment]
Additional  fix - https://github.com/rancher/dashboard/pull/9022
