### ISSUE TITLE
Epic: Redesign Menu(s) Navigation Structure

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6067]
# Current problems

- It is not immediately obvious to figure out how to add a user to a cluster. You probably have to read docs to know that you have to go to Cluster Management > Clusters > Click the three dots > Click Edit Config > Scroll Down > Click the Member Roles tab. In my opinion that's too deeply buried. You can also go to Cluster > Cluster Members in cluster explorer but I think that's too deeply buried as well because I wouldn't know that users would be categorized under "Cluster." The Cluster item in the side nav is misleading overall because there are a lot more cluster-level resources such as storage that are not under that heading, so it's not clear what that even means.
- We confusingly have two cluster detail pages - one if you click the name of the cluster in Cluster Management, and one in cluster explorer. These should be consolidated into one area of the UI.
- If you're in cluster explorer, it's not clear how you would get the snapshots of a cluster or see machine details. You have to read docs to know that you need to go to Cluster Management and navigate back to the same cluster from there.

# Proposed solution

I propose this navigation for the side nav of cluster explorer (See below screenshots for what would be rendered at each top level page):

- Namespace selector dropdown menu (because this is where people look to navigate)
- Dashboard
- Projects/Namespaces
- Nodes
- Users
- K8s Config
- Apps
  - Charts
  - Installed Apps
  - Repositories
  - Recent Operations
- K8s Resources (same categories that we already have)
- Snapshots
- Management (Here you would see the same Detail section as you see when clicking the cluster name in cluster explorer, with the tabs for machines, etc)

And when you click the name of the cluster in Cluster Management, it would just take you to cluster explorer with the new Management section open by default, so you would see the same tabs for machines, snapshots etc as you did before.

## Screenshots for what the top-level nav item pages would look like
Just for quick reference:

### Dashboard
<img width="1130" alt="Screen Shot 2022-05-31 at 3 47 41 PM" src="https://user-images.githubusercontent.com/20599230/171296381-dcf2eb3b-4598-4fb3-ae39-1954466a8817.png">

### Projects/Namespaces
<img width="1124" alt="Screen Shot 2022-05-31 at 3 48 47 PM" src="https://user-images.githubusercontent.com/20599230/171296505-c7f90594-1842-4382-ad35-cfe7e3e98889.png">

### Nodes
Instead of saying "go to Cluster Management," maybe we could put the machine lifecycle stuff on this page. Maybe it could be combined with the node pools config.
<img width="1121" alt="Screen Shot 2022-05-31 at 3 49 47 PM" src="https://user-images.githubusercontent.com/20599230/171296692-e7beed5d-4787-4cb5-b050-fa8cd7ea15f0.png">

### Users
Putting this at the highest level reduces the clicks and knowledge needed to add someone to a cluster.
<img width="1122" alt="Screen Shot 2022-05-31 at 3 52 06 PM" src="https://user-images.githubusercontent.com/20599230/171296779-c3bb5e64-8de3-475e-992d-2743034ae646.png">

### K8s Config
Normally you would have to go to Cluster Management and find the same cluster again in order to see this.

<img width="1112" alt="Screen Shot 2022-05-31 at 3 53 36 PM" src="https://user-images.githubusercontent.com/20599230/171296910-d54f20bc-8d47-474e-a7c5-16aec4e228e5.png">

### Apps
Same as it currently is

<img width="1120" alt="Screen Shot 2022-05-31 at 3 56 28 PM" src="https://user-images.githubusercontent.com/20599230/171297778-03504bc0-69ed-40c6-94c5-acbcc72e7022.png">

### K8s Resources
Nothing would happen when clicking this title. You would have to click a resource to see a list.

### Snapshots

<img width="1115" alt="Screen Shot 2022-05-31 at 3 58 43 PM" src="https://user-images.githubusercontent.com/20599230/171297494-abfc1d9e-9ba9-49eb-a434-0a8b58150d48.png">

### Management
Everything from the above screenshot other than snapshots - Provisioning logs, CAPI machine resources etc

**Comment by kwwii** [comment]
Closing this as it seems to be a stale issue. We'll consider this a larger part of the menu rework
