### ISSUE TITLE
Edit as Yaml of a secret fails 

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#607]
Version: master-head(7b948b289)

Steps:
1. Create a secret (opaque) providing a key/value
2. Edit the secret by choosing "Edit as Yaml" option . Change the key/value in data section.
3. Hit "Save" button

Edit fails with the error below:
```
{ "type": "error", "links": {}, "code": "BadRequest", "message": "Secret in version \"v1\" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 4, error found in rancher/dashboard#10 byte of ...|y\":\"djFly\"},\"kind\":\"|..., bigger context ...|{\"apiVersion\":\"v1\",\"data\":{\"k1ey\":\"djFly\"},\"kind\":\"Secret\",\"metadata\":{\"creationTimestamp\":|...", "status": 400 }


```
![Screen Shot 2020-05-05 at 3 54 30 PM](https://user-images.githubusercontent.com/18536626/81123868-f60faa00-8ee8-11ea-9fb1-9d97d885d258.png)

Note: Edit as a Form is functional

**Comment by mantis-toboggan-md** [comment]
This is expected for secret fields that are base64 encoded, https://github.com/rancher/dashboard/issues/611#issuecomment-628911302

**Comment by soumyalj** [comment]
Validated with master-build(b85ea695f)
Steps:
1. Create a secret (opaque) providing a key/value
2. Edit the secret by choosing "Edit as Yaml" option . To change the existing value/add new key/value paits, we have to base64 encode the value and then use it in the yaml. 
3. Hit "Save" button

Editing of secret succeeds without any errors. From the list view, we can edit as form and verify that the value has been edited and stored as expected.
