### ISSUE TITLE
Allow secret type to be set when creating a secret

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6076]
Internal Reference: SURE-4634

When creating a secret it is not possible to specify the type - you can select from 1 of 5 types, but can't create a secret with a custom type.

**Comment by bmdepesa** [comment]
https://kubernetes.io/docs/concepts/configuration/secret/#secret-types

**Comment by floatingman** [comment]
I'm able to create a custom secret on 2.6.7-rc3 on a RKE1 HA cluster.
