### ISSUE TITLE
Resource camel-casing in role create/edit results in incorrect resource names in role templates

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6090]
Internal reference: SURE-4752
Reported in 2.6.5, considered regression

Issue description:
Resource camel-casing in role create/edit results in incorrect resource names in role templates. This means that user-created custom roles in new UI not working as expected

Repro steps:

- Provision a Rancher v2.6.5 instance (and a v2.5.14 for working comparison in old UI) with a single all role node custom cluster
- Create a custom global role granting get, watch, list on rkek8ssystemimages, selecting this resource from the dropdown (as RkeK8sSystemImages in v2.6.5)
- Create a user _foo_, with User Base and the custom global role
- Grant the user 'View Nodes' on the Rancher local cluster to provide them access to the local cluster
- Log in as user _foo_ and perform `kubectl get rkek8ssytemimages -A` on the Rancher local cluster
- Observe this fails in v2.6.5 with an error of the format `Error from server (Forbidden): rkek8ssystemimages.management.cattle.io is forbidden: User "u-p7ld9" cannot list resource "rkek8ssystemimages" in API group "management.cattle.io" at the cluster scope` but succeeds in v2.5.14
- Edit the custom global role and add get, watch list on rkek8ssystemimages, typing the name all lower case and selecting this lower case version from the dropdown
- Observe the user _foo_ can now successfully perform `kubectl get rkek8ssytemimages -A`

Workaround:
Type the resource name all lower case and select the lower case version from the dropdown

Actual behavior:
Custom UI generated roles with pre-filled resource names from dropdown do not work as expected

Expected behavior:
Custom UI generated roles with pre-filled resource names from dropdown work as expected

**Comment by codyrancher** [comment]
Just as a note for those who test. There's a typo in the kubectl commands that pluralizes the resources. `kubectl get rkek8ssystemimage -A` works for me.
