### ISSUE TITLE
Session timeout doesn't redirect, showing cached data in the UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6092]
Internal reference: SURE-4501
Reported in 2.6.4

Issue description:
It is possible to click around in the web UI to various screens/interfaces and presented stale data without being informed that the session has timed out.

Eventually clicking on a UI element that causes the web app to realize my session is dead, then it's redirected to the login screen.

Impact: 
Annoyance mostly, can be misleading viewing old data.

Expected behavior:

Redirected to the login screen immediately when the session has expired
**

Additional notes:
Google Chrome Version 99.0.4844.84 (Official Build) (x86_64) on macOS.

**Comment by gaktive** [comment]
We should introduce a timeout prompt that says something like "do you want to continue this session?" and then have a countdown clock to then log them out. This will help with performance and security.

Relates to https://github.com/rancher/dashboard/issues/7776

@nwmac had done something like this before in another project. He'll dig up the associated Stratos PR/code and link.

**Comment by nwmac** [comment]
This should be addressed by doing: https://github.com/rancher/dashboard/issues/7776

**Comment by gaktive** [comment]
Closing as a duplicate.
