### ISSUE TITLE
Node providers that have multiple credentials exposes the full API Key when viewing them in `Cloud Credentials`

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#6093]
**Setup**
- Rancher version: `v2.6-head`
- Browser type & version: Chrome

**Describe the bug**

When looking into `Cloud Credentials` in `Cluster Management`, I noted that the API Key isn't hidden. For example, if you have Amazon credentials saved into Rancher from a previous cluster, it will list the entire access key, which isn't ideal.

However, when you look at a node driver such as Linode that only has one credential parameter, it will partially list the API Key and then finish off with `...` to indicate that there is more. For cohesiveness and security purposes, we should apply that same approach Linode does to all of the cloud credentials.

In other words, we list the first 8 characters and afterwards have `...`. This is beneficial in the following ways: it hides the entire API Key from being visible, allows users to still manage their API Keys by having the first 8 characters as reference, gives a cohesive feel for all of the providers.

This is more of a "nice-to-have" feature as is by no means disrupting any workflows. But something that we should still be aware of.

**To Reproduce**

1. Setup Rancher and navigate to the UI in a browser.
2. Navigate to Cluster Management > Cloud Credentials.
3. Create an Amazon cloud credential and note the full API Key is shown.
4. If possible, create a Linode cloud credential. Note that only partial API Key is shown. All providers should match this.

**Result**
The full API Key is exposed when using providers such as Amazon that use multiple credentials to authenticate the user.

**Expected Result**

Only 8 characters should be exposed when providers such as Amazon use multiple means to authenticate the user. Currently, only providers that provide a single credential give this functionality.

**Comment by markusewalker** [comment]
While this issue is awaiting triage, here is the QA test plan:

**TEST PLAN**
1. Setup Rancher and navigate to the UI.
2. Create a standard user and login as that user.
3. Navigate to Cluster Management > Cloud Credentials.
4. Create an Amazon cloud credential; validate if the full API key is shown.
5. Repeat step 4 for providers Linode, Azure and Google; validate if the full API key is shown.

**Comment by gaktive** [comment]
Per triage discussion, Linode only has a single key whilst Amazon does have two: the access key which tends to be more broadly visible and then the secret key which should always be hidden. We could potentially hide both and it would be trivial.
