### ISSUE TITLE
'Maximum Worker Nodes Unavailable' gets '%' when validation fails for Custom cluster

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6095]
Internal reference: SURE-4378
Reported in 2.6.4

When Cluster validation failed for Custom Cluster, 'Maximum Worker Nodes Unavailable' under 'Advanced Options' gets '%'.
This issue happens only to Custom Cluster.

Previously this issue was reported and has been fixed for the most of Cluster templates except for Custom Cluster in https://github.com/rancher/dashboard/issues/4870

**Comment by nwmac** [comment]
PR: https://github.com/rancher/ui/pull/4870

**Comment by sowmyav27** [comment]
**On 2.6.6**

- Create a custom cluster with no name. Click on Next a few times.
- Multiple `%` seen in the Max Worker nodes Unavailable
<img width="1280" alt="Screen Shot 2022-07-20 at 6 49 05 PM" src="https://user-images.githubusercontent.com/26032343/180112439-7b553ce7-1eab-49bc-b63f-42348377875e.png">


---

**On 2.6head commit id: `c47178e`**
- Create a custom cluster with no name. Click on Next a few times.
- Multiple `%` DOES NOT appear in the Max Worker nodes Unavailable section
- When a cluster name is given after the previous step and Click Next. `maxUnavailableWorker: "10%"` is sent in the Network request

<img width="1275" alt="Screen Shot 2022-07-20 at 6 50 05 PM" src="https://user-images.githubusercontent.com/26032343/180112373-4dd4221f-dd1e-4d47-bc0e-ea274255c157.png">
