### ISSUE TITLE
User with UserBase Global permission does not have right permissions

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6100]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 local cluster

**Information about the Cluster**
- Kubernetes version: `v1.21.7`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom). - User with UserBase Global permission

   
**Describe the bug**
User with UserBase Global permission does not have right permissions

**To Reproduce**
- As an admin create a User Base user - `user1`
- Login as user1
- User is navigated to Home page
<img width="1315" alt="Screen Shot 2022-01-05 at 5 05 34 PM" src="https://user-images.githubusercontent.com/26032343/148311698-29f3b935-5348-43a4-bd70-9ca538b4add4.png">

- Click on Create. User is navigated to this page
<img width="1680" alt="Screen Shot 2022-01-05 at 5 05 54 PM" src="https://user-images.githubusercontent.com/26032343/148311694-9e248978-e861-4175-9d6d-54f99acbc3a1.png">

- User is not able to navigate to any other page- which seems like it is expected. 

Question:
- Is the landing page on click on Create cluster correct?
- In Ember UI, this is what the user with User Base access can see.
<img width="1407" alt="Screen Shot 2022-01-05 at 5 09 17 PM" src="https://user-images.githubusercontent.com/26032343/148311932-65774763-8781-46db-96aa-d78b94d4cfeb.png">
<img width="1329" alt="Screen Shot 2022-01-05 at 5 09 35 PM" src="https://user-images.githubusercontent.com/26032343/148311938-4b38889d-9e70-4d97-be90-ee15d13c392f.png">

**Comment by gaktive** [comment]
The Ember UI is being phased out so if it's the one that's wrong, we'll leave this as is, barring some other security concern.

**Comment by catherineluse** [comment]
I'm closing this issue because the bug is only seen in Ember, which is no longer maintained or supported.
