### ISSUE TITLE
Add unit tests for cluster delete with name

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#6109]
**Describe the bug**

Add unit tests for cluster delete with name confirmation. https://github.com/rancher/dashboard/pull/5887#issuecomment-1145219412

**Expected Result**
Have unit tests for cluster delete with name confirmation.

**Comment by cnotv** [comment]
This issue is going to be solved with the existing CRUD set of tests.
https://github.com/rancher/dashboard/issues/5990
