### ISSUE TITLE
"Edit as Yaml"  issues for registry secrets

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#611]
Version: master-head((7b948b289)

Steps:

1. Create a secret "testreg" "by choosing type "registry" option 
2. Edit the secret using "Edit as Yaml" option. 

**Issue 1:**
The yaml displayed has data as .dockerconfigjson. The data section does not display registry domain, username etc for users to edit.
```
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbmRleC5kb2NrZXJodWIuaW8vdjEvIjp7InVzZXJuYW1lIjoidGVzdDEiLCJwYXNzd29yZCI6InZhbDEifX19
kind: Secret
metadata:
  creationTimestamp: "2020-05-06T18:09:15Z"
  labels:
    k1: v1
  name: testreg
  namespace: default
  resourceVersion: "217533"
  selfLink: /api/v1/namespaces/default/secrets/testreg
  uid: 62675c0e-3730-4c4d-990a-58182df1d703
type: kubernetes.io/dockerconfigjson
```

**Issue 2:**

If labels are edited or new labels are added using "Edit as Yaml", and saved, the following error was observed:
```
{ "type": "error", "links": {}, "code": "Invalid", "message": "Secret \"testreg\" is invalid: type: Invalid value: \"Opaque\": field is immutable", "status": 422 }

```

**Comment by aaronRancher** [comment]
This is also seen when editing a secret of type `certificate`
```
{ "type": "error", "links": {}, "code": "Invalid", "message": "Secret \"testreg\" is invalid: type: Invalid value: \"Opaque\": field is immutable", "status": 422 }
```

**Comment by mantis-toboggan-md** [comment]
This is how creating registry secrets should work according to the kubernetes docs: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials

You need to provide a base64 encoded JSON string here.

There are fields on other secret types that are also base64 encoded and will cause errors if you enter plain text. My understanding is that the UI's yaml-editing feature should work pretty much the same as yaml editing elsewhere, that is, no behind-the-scenes help like the UI form option has, but @deniseschannon  can you confirm this?

**Comment by vincent99** [comment]
`data` (and `binaryData`) values need to be base64-encoded and you need to know that if you're going to use the YAML editor for a secret.  (Even if we wanted to be clever and do it for you that wouldn't work on binaryData)

But the error message from @aaronRancher suggests that the `type` of the resource is trying to change on edit from (I presume) `kubernetes.io/dockerconfigjson` to `Opaque`, which fails because `type` is not editable.  So the type is accidentally getting changed somewhere?

**Comment by mantis-toboggan-md** [comment]
Issues with _type/type on create/edit/clone should all be resolved with the yaml-edit PR merged today

**Comment by soumyalj** [comment]
Validated with master-build(b85ea695f)
Steps:
1. Create a secret "testreg" "by choosing type "registry" option
2. Edit the secret using "Edit as Yaml" option.
- Case 1
The .dockerconfigjson should be regenerated if username/password are being changed.
The registry info should be base64 encoded to generate the .dockerconfigjson
```
{"auths":{"test.com":{"username":"user1","password":"newuser"}}}
```
```
eyJhdXRocyI6eyJ0ZXN0LmNvbSI6eyJ1c2VybmFtZSI6InVzZXIxIiwicGFzc3dvcmQiOiJuZXd1c2VyIn19fQ==
```
```
apiVersion: v1
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJ0ZXN0LmNvbSI6eyJ1c2VybmFtZSI6InVzZXIxIiwicGFzc3dvcmQiOiJuZXd1c2VyIn19fQ==
kind: Secret
metadata:
  name: testreg
  namespace: default
  resourceVersion: '141201'
  selfLink: /api/v1/namespaces/default/secrets/testreg
  uid: 6eccd840-5f8a-4048-8543-02921ce31849
type: kubernetes.io/dockerconfigjson

```
Edit as yaml succeeds

- Case 2

Adding labels during edit as yaml succeeds
```
apiVersion: v1
data:
  .dockerconfigjson: >-
   eyJhdXRocyI6eyJ0ZXN0LmNvbSI6eyJ1c2VybmFtZSI6InVzZXIxIiwicGFzc3dvcmQiOiJuZXd1c2VyIn19fQ==
kind: Secret
metadata:
  annotations:
    a1: a2
  creationTimestamp: '2020-05-20T17:24:49Z'
  labels:
    l1: l2
    l3: l4
  name: testreg
  namespace: default
  resourceVersion: '141201'
  selfLink: /api/v1/namespaces/default/secrets/testreg
  uid: 6eccd840-5f8a-4048-8543-02921ce31849
type: kubernetes.io/dockerconfigjson

```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version b85ea695f`
Steps:
Create a secret of type `certificate` in dashboard
Edit cert as YAML
Edit as yaml succeeds
