### ISSUE TITLE
Import command popup not showing for private EKS clusters

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6112]
Internal reference: SURE-4782
Reported in 2.6.5

Issue description:
When creating a new EKS cluster or registering an existing EKS cluster with private endpoint, there is no screen in the UI that gives the end user the `kubectl` import command. This is needed to install the agents and this behavior is specified in the documentation:

https://rancher.com/docs/rancher/v2.6/en/cluster-admin/editing-clusters/eks-config-reference/#private-only-api-endpoints

If you enable private and disable public API endpoint access when creating a cluster, then there is an extra step you must take in order for Rancher to connect to the cluster successfully. In this case, a pop-up will be displayed with a command that you will run on the cluster to register it with Rancher. Once the cluster is provisioned, you can run the displayed command anywhere you can connect to the cluster’s Kubernetes API.

Business impact:
User is unable to manage an EKS cluster with private endpoint in Rancher

Repro steps:

- Go to Cluster Management
- Create new cluster
- Select Amazon EKS
- Default options can be used, except select private endpoint and unselect public endpoint
- Create cluster - note, no import command is shown
 
- Create an EKS cluster directly on AWS. Select private endpoint, disable public endpoint.
- Go to Cluster Management in Rancher
- Click Import Existing
- Select Amazon EKS
- Select cluster created on AWS.
- Click Register, note, no import command is shown.

Workaround:
Maybe - Use generic import

Actual behavior:
No popup with import command is shown (as specified in docs)

Expected behavior:
After creating or registering an EKS cluster with private endpoint, an import `kubectl` command should be displayed with instructions.

**Comment by nwmac** [comment]
Related/same as https://github.com/rancher/dashboard/issues/6036
