### ISSUE TITLE
Create a mockup for the Rancher Desktop settings

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#6113]
**Setup**
- Rancher version: 2.6
- Browser type & version:

**Describe the bug**

The application needs to improve user experience, while the developers will address the features included in the setting area, I will create a way to display and interact with this informations

**To Reproduce**

**Result**

**Expected Result**

A visual prototype of the user flow and the graphic interface

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by nwmac** [comment]
@manuelecarlini I think has been done, right? Can we close if so

**Comment by manuelecarlini** [comment]
@nwmac yes, we can mark it as done
