### ISSUE TITLE
List view for registry type secrets have .dockerconfigjson  displayed in the data field

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#612]
Version: master-head((7b948b289)

Steps:

1. Create a secret "testreg" "by choosing type "registry" option. Refresh the UI
2. In the UI, data for registry type secret is displayed as `.dockerconfigjson`. 
This is not useful to the users. Domain name/username can be displayed  in the list view for secrets of "registry" type.

<img width="946" alt="Screen Shot 2020-05-06 at 11 25 44 AM" src="https://user-images.githubusercontent.com/18536626/81214217-5efc2e00-8f8c-11ea-9243-4ca9bc7ddf87.png">

**Comment by deniseschannon** [comment]
@mantis-toboggan-md Can we convert the data to pull the domain name of the registry as the "Data" for the list view?

**Comment by soumyalj** [comment]
Validated with master-head(1f4a2c388)
Steps:
1. Create few secrets "by choosing type "registry" option. 

In the list view, domain name is displayed in the data column for registry secret as below:

![Screen Shot 2020-05-18 at 10 32 03 AM](https://user-images.githubusercontent.com/18536626/82242573-f2b9ec80-98f2-11ea-8ffd-c96467a629e3.png)
