### ISSUE TITLE
Update global token setting descriptions.

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/dashboard#6120]
**Detailed Description**
Add the following new setting:
- ~~`kubeconfig-default-token-TTL-minutes`~~ `kubeconfig-default-ttl-minutes`
    TTL (in minutes) applied on all kubeconfig tokens

Purposed descriptions updates:
- `auth-token-max-ttl-minutes`
  Max TTL (in minutes) for all authentication tokens.
- `kubeconfig-token-ttl-minutes`
 TTL used for tokens generated via the CLI.  **Deprecated**: This setting will be removed, and `kubeconfig-default-token-TTL-minutes` will be used for all kubeconfig tokens
- `kubeconfig-generate-token`
Automatically generate tokens for users when a kubeconfig is requested.

**Context**
This [PR](https://github.com/rancher/rancher/pull/37703) will update the use of different token settings in rancher manager, which should be reflected in the UI descriptions.

**Comment by catherineluse** [comment]
@KevinJoiner Please let me know when the change to add the `kubeconfig-default-token-ttl-minutes` setting is merged into the backed.

As soon as that's merged, we can test https://github.com/rancher/dashboard/pull/6351.

**Comment by KevinJoiner** [comment]
@catherineluse The backend issues are merged and tested in v2.6

**Comment by catherineluse** [comment]
I just made sure I was using the latest Docker image:
```
root@catherine1:~# docker pull rancher/rancher:v2.6-head
v2.6-head: Pulling from rancher/rancher
Digest: sha256:261b88031594c741c8dc0953fb3df20e7c5ce9952b1fe986816c44314beae000
Status: Image is up to date for rancher/rancher:v2.6-head
docker.io/rancher/rancher:v2.6-head
```

But when I looked for `kubeconfig-default-token-ttl-minutes` in the API response at `serverUrl/v3/settings`, I didn't see it. Did I use the wrong image?

**Comment by KevinJoiner** [comment]
You are using the correct image. I didn't realize we changed the settings' name from when the issue was first created `/v3/settings/kubeconfig-default-ttl-minutes` should be the correct endpoint.

**Comment by catherineluse** [comment]
Thank you, it works now.

Just in case someone doesn't know what 0 means for the default value, I added a sentence to the descriptions for `kubeconfig-default-ttl-minutes` and `auth-token-max-ttl-minutes` - `When set to 0, the token never expires.`

**Comment by anupama2501** [comment]
Verified on v2.6-head 78017e6
`auth-token-max-ttl-minutes`
Max TTL (in minutes) for all authentication tokens. When set to 0, the token never expires.

`kubeconfig-token-ttl-minutes`
TTL used for tokens generated via the CLI. Deprecated: This setting will be removed, and kubeconfig-default-ttl-minutes will be used for all kubeconfig tokens.

kubeconfig-generate-token
Automatically generate tokens for users when a kubeconfig is requested.

`kubeconfig-default-ttl-minutes`
TTL (in minutes) applied on all kubeconfig tokens. When set to 0, the token never expires.


Verified when we set a value to greater than `auth-token-max-ttl-minutes`, the token is valid only for `auth-token-max-ttl-minutes` minutes
Verified setting the value to 2, downloaded kubeconfig and verified the token was valid for 2 minutes.

**Comment by KevinJoiner** [comment]
Reopening based on a new issue: rancher/rancher/issues/38456 to update the name of `kubeconfig-default-ttl-minutes` -> `kubeconfig-default-token-ttl-minutes`

**Comment by catherineluse** [comment]
The fix here https://github.com/rancher/dashboard/pull/6545 should work as soon as https://github.com/rancher/rancher/pull/38457 is merged.

**Comment by anupama2501** [comment]
Verified on v2.6-head 6629e3e

The token setting is updated to `kubeconfig-default-token-ttl-minutes`
