### ISSUE TITLE
Update EKS versions to remove EOL 1.19

### ISSUE THREAD

**Issue by cbron** [rancher/dashboard#6124]
https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/amazon.js#L684

1.19 is EOL at the end of June 2022: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

This should be removed before 2.6.6 is released.

**Comment by cbron** [comment]
We also need to remove 1.20, but not until around or after September. We could schedule that for 2.6.7-2.6.8.

**Comment by cbron** [comment]
@gaktive we have typically done in the next normal release. Until then it will result in an error.

**Comment by markusewalker** [comment]
Verified that this is addressed in `v2.6-head` https://github.com/rancher/rancher/commit/8ffaf566fcc764ed9665eec1ac998d8bd7b7e3f1.

**ENVIRONMENT DETAILS**
- Rancher Install: Docker
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/8ffaf566fcc764ed9665eec1ac998d8bd7b7e3f1
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Created a standard user and login to Rancher as that user.
3. Attempted to provision a hosted EKS cluster. In `Cluster Options`, verified that the K8s version 1.19 is no longer in the dropdown:
![image](https://user-images.githubusercontent.com/52591819/181121071-a3a4c00d-717f-4de2-b913-52a9157b1727.png)
