### ISSUE TITLE
Customize port forwarding

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#6130]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**
Following the request of this issue 
https://github.com/rancher-sandbox/rancher-desktop/issues/791

I will propose a visual mockup that will address the custom post forwarding 
**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by catherineluse** [comment]
I am transferring this issue to the Rancher Desktop repo. Let me know if it needs to be tracked here instead
