### ISSUE TITLE
Can only create new local users as "standard users"

### ISSUE THREAD

**Issue by brudnak** [rancher/dashboard#6137]
### Rancher Server Setup

| Component                 | Version / Type                                                                     |
| ------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version           | v2.6-780c3486803bdf80ca71f8e5e954b7b8c13562cf-head                                 |
| Rancher commit link       | https://github.com/rancher/rancher/commit/780c3486803bdf80ca71f8e5e954b7b8c13562cf |
| Installation option       | helm                                                                               |
| RKE binary version used   | 1.3.11                                                                             |
| If Helm Chart k8s cluster | rke v1.23.6                                                                        |
| Cert Details              | let's encrypt                                                                      |
| Docker version            | 20.10.7, build f0df350                                                             |
| Helm version              | v2.16.8-rancher1                                                                   |
| Downstream cluster type   | not applicable                                                                     |
| Downstream K8s version    | not applicable                                                                     |
| Logged in user role       | administrator                                                                      |
| Browser type              | opera gx                                                                           |
| Browser version           | LVL3 (core: 87.0.4390.56) (x86_64)                                                 |

   
## Describe the bug
Unable to create a new user with permissions other than `Standard User`.

## To Reproduce
1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click the `hamburger menu` -> `Users & Authentication` -> `Create`
3. Observe under `Global Permissions  the only role available is `Standard User`

#### Result
The only global permission available when creating new users is `Standard User`.

#### Expected Result
I would expect to be able to create users with all of the standard global permissions
1. Administrator
2. Restricted Administrator
3. Standard User   
4. User-Base

And with all of the `Built-in` roles available as well

#### Workaround
Able to create new users with different roles using Postman / API calls

#### Screenshots

![2022-06-09_15-22-24](https://user-images.githubusercontent.com/40877149/172956464-d6ac7d94-c7cc-4b4a-b39e-e9ff3b1b817b.png)

**Comment by richard-cox** [comment]
Console error 
```
TypeError: Method findTrueValue is undefined
    at findTrueValues (Checkbox.vue?979a:177:15)
```
Recently changed via https://github.com/rancher/dashboard/pull/6073

**Comment by brudnak** [comment]
# :white_check_mark: PASS

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component               | Version / Type                                                                     |
| ----------------------- | ---------------------------------------------------------------------------------- |
| Rancher version         | v2.6-8b3919b99293fc8b0dc5fe7191ca5bec9609aadd-head                                 |
| Rancher commit link     | https://github.com/rancher/rancher/commit/8b3919b99293fc8b0dc5fe7191ca5bec9609aadd |
| Installation option     | `eksctl` eks local cluster (bring your own cluster)                                |
| local k8s cluster       | v1.22.9-eks-a64ea69                                                                |
| Cert Details            | let's encrypt                                                                      |
| Helm version            | v2.16.8-rancher1                                                                   |
| Downstream cluster type | rke1 linode                                                                        |
| Downstream K8s version  | v1.23.6-rancher1-1                                                                 |
| Logged in user role     | administrator                                                                      |
| Browser type            | google chrome                                                                      |
| Browser version         | 102.0.5005.115 (Official Build) (x86_64)                                           |

**ADDITIONAL SETUP**

- eksctl install command:

```shell
eksctl create cluster \
  --name $YOUR_CLUSTER_NAME \
  --version 1.22 \
  --region us-east-2 \
  --nodegroup-name $YOUR_NODE_GROUP_NAME \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
```

- Helm commands for Rancher installation:
  
```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$YOUR_HOSTNAME \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$YOUR_EMAIL \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5 \
  --set rancherImageTag=v2.6-head \
  --set extraEnv\[0\].name="CATTLE_PROMETHEUS_METRICS" --set-string extraEnv\[0\].value=true
```

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click the `hamburger menu` -> `Users & Authentication` -> `Create`
3. Observe under `Global Permissions  the only role available is `Standard User`
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
I would expect to be able to create users with all of the standard global permissions

#### :white_check_mark: Actual
I was able to create users with all of the standard global permissions
