### ISSUE TITLE
Resource Tables sometimes jump back to first page after page is changed

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6138]
For any table of resources that has more resources than be displayed on one page, when changing page, the table will change to the new page and then shortly afterwards change back to the first page again.

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/0fd630dd1328233958bdef6b9f7f413eb7463005.

**ENVIRONMENT DETAILS**
- Rancher HA
- Rancher version: `v2.6` https://github.com/rancher/rancher/commit/0fd630dd1328233958bdef6b9f7f413eb7463005
- RKE2 version: `v1.23.6+rke2r2`
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Created a standard user and logged into Rancher as that user.
3. Provisioned a downstream RKE2 node driver cluster.
4. Once successfully provisioned, navigated to Cluster Explorer > RKE2 cluster.
5. In the `Events` resource table, clicked through some pages and hold for few seconds; verified that the page does not revert to the first page:
![Jun-16-2022 11-19-48](https://user-images.githubusercontent.com/52591819/174139168-5c944a34-f673-4dd8-b542-ddc64d95fa9b.gif)
