### ISSUE TITLE
Difficult to get overview of machine pool/machines on cluster detail view when lots of machines

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6142]
See below:

When you have lots of machines, you only see one pool header and the first set of machines - you have to scroll to see more.

Suggest we:

- Make it easier to see how many pool and total machines there are
- Make it easier to see how many machines are in each pool

**Comment by Josh-Diamond** [comment]
Ticket #6142 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.5`:
1. Fresh install of rancher `v2.6.5`
2. Provision a downstream RKE1 AWS Node driver cluster
3. Reproduced - UI before enhancement

Screenshot:
<img width="1508" alt="Screen Shot 2022-06-23 at 10 12 35 AM" src="https://user-images.githubusercontent.com/46494969/175361974-8bc7434d-3a3e-4bbe-86da-462043b9806e.png">


Verified on rancher `v2.6-328b12b43716c7d30a605905d73a0b799ec2a4bd-hea`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE1 AWS Node driver cluster
3. Verified - UI enhanced

Screenshot:
![validate](https://user-images.githubusercontent.com/46494969/175362005-9734b138-b53c-42cb-8669-248ba6dbef25.png)
