### ISSUE TITLE
Enable packages to provide their own formatters

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6147]
**Detailed Description**
- components like list, detail, edit, etc can be provided by a plugin. 
- we need to also support providing formatters
- formatters are loaded via `./shell/plugins/global-formatters.js`, we should be able to add plg formatters here too
- pkgs should be able to provide formatter names via plugins.js/iplugins.js register(?)

**Context**
- Require to fully package harvester

**Comment by nwmac** [comment]
The `global-formatters` file just registers the components as global components - we should probably add a way to do this for plugins, but you can achieve this as is by registering formatter plugins in your plugin:

`Vue.component(<NAME>, component);`

**Comment by nwmac** [comment]
Dev will validate - not something we expect QA to test
