### ISSUE TITLE
VPC and subnet names not listed during AWS EC2 v2 provisioning

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6155]
Internal reference: SURE-4733
Reported in 2.6.5

Issue description:
When using v2 provisioning (RKE2/K3S), the UI to select a VPC and subnet does not show the VPC name or subnet name. The v1 provisioning does show this information. (see screen captures below)

Business impact:
It may be difficult to select a VPC or subnet based on AWS ids and CIDRs.

Repro steps:

- Click create cluster (from dashboard or cluster manager)
- Select RKE2/K3s in toggle, then Amazon EC2.
- Click the VPC/Subnet dropdown for the node pool

Workaround: none

Actual behavior:
VPC and subnet names are not listed.

Expected behavior:
VPC and subnet names are displayed in the drop down

Screenshots:
V1
![image-2022-05-24-13-56-38-431.png](https://zube.io/files/rancher/867e9049c7e8136d9a2cc78f034d6fc2-image-2022-05-24-13-56-38-431.png)

V2 (note that the names aren't visible; we can try adding the names into here and see how it appears)
![image-2022-05-24-13-55-46-710.png](https://zube.io/files/rancher/888affc3fdfb0ac4ddc8a8626a93efc7-image-2022-05-24-13-55-46-710.png)

**Comment by kwwii** [comment]
The simple fix here seems to be to add the information to the labels in the drop-down. In order to make space for that, we would need to remove the availability information from each label and possibly move the "IAM Instance Profile Name" drop-down to make space (below the VPC/Subnet drop-down).

**Comment by jameson-mcghee** [comment]
This issue has been resolved in v2.6-head (2c21373). See screenshots. Therefore this issue has been closed.

2.6.5:
![image.png](https://zube.io/files/rancher/2bca88bd0044b807c6cbe86fcac74da5-image.png)

2.6-head:
![image.png](https://zube.io/files/rancher/67654a5e35fdab85346b23e5fd52cff4-image.png)

**Comment by kwwii** [comment]
I think it will be hard for a user to correlate a number at right the value at left it pertains to. It might be better to separate the information with a slash / or perhaps parenthesis ()
