### ISSUE TITLE
Private key is not hidden on edit in certificates

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#616]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
In dashboard, create a secret with type `certificate`
Populate Private Key and CA Certificate fields.
Create certificate
Edit certificate

**Result:**
Private key is not hidden.
Dashboard example with random strings:
![Screen Shot 2020-05-18 at 4 10 27 PM](https://user-images.githubusercontent.com/57409052/82267791-39730b00-9922-11ea-9ad9-5035c388cddb.png)

Rancher UI:
![Screen Shot 2020-05-06 at 3 11 17 PM](https://user-images.githubusercontent.com/57409052/81233976-b3afa100-8fac-11ea-9d67-9dbc658ef0a3.png)

**Comment by mantis-toboggan-md** [comment]
The Ember UI isn't hiding the private key; it's removing it from the form entirely. Is this the desired behavior in the vue ui @deniseschannon ?

**Comment by deniseschannon** [comment]
@mantis-toboggan-md Yes, that's fine to remove the entire private key.

**Comment by vincent99** [comment]
This is not ok as implemented.  Norman has a mechanism to mark the field write-only, not send the value back on GET and ignore that it's empty on save (or require you to put in a new value before you can save).

Steve has none of that. If you click edit cert -> change description -> save, you just nuked the tls.key value and have no certificate anymore.

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:master-head` `version b85ea695f`

On editing a certificate, the private key is still seen:
![Screen Shot 2020-05-19 at 4 31 22 PM](https://user-images.githubusercontent.com/57409052/82388344-3fceb900-99ee-11ea-954a-b17d9727fe95.png)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version b85ea695f`

Private key is not seen when editing a secret as a form:
![Screen Shot 2020-05-21 at 2 42 57 PM](https://user-images.githubusercontent.com/57409052/82609798-12ab1380-9b72-11ea-99ba-b65ec20111f3.png)
