### ISSUE TITLE
Selecting the RKE template on the cluster creation screen resets the node pool input

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6164]
Internal reference: SURE-4749
Reported in 2.6.5

Issue description:
If you select a value from the pull-down menu of the cluster template on the cluster creation screen, the contents are entered in the node pool and the checkboxes will be reset.

Business impact:
User needs to re-configure the node pool inputs again after selecting the RKE templates from the drop down.

Repro steps:

- Create a single node Rancher cluster 
- Create an RKE template
- Add a cluster with node pool -> enter some inputs in the pool -> select the RKE template drop down and select the RKE template -> node pool inputs will vanish

Workaround: none

Actual behavior:
Selecting the RKE template on the cluster creation screen resets the node pool input

Expected behavior:
Selecting the RKE template on the cluster creation screen should not reset the node pool inputs

Additional notes:
User searched our repo and found this pull request seems to be the direct cause.
https://github.com/rancher/ui/pull/4824

Commenting out this code will resolve the issue.
https://github.com/rancher/ui/pull/4824/files#diff-bd7d0095619e9f28ad09e762d0492c0b86fbaf3a1ab1ee7ef6ef549c1d75c384R145

The above pull request seems to have been created to solve the following issue, but when they checked the operation by commenting out ↑, it seems that the problem currently occurring in the following issue does not occur.
https://github.com/rancher/dashboard/issues/5343

![Screenshot 2022-05-27 at 6.06.32 PM.png](https://zube.io/files/rancher/206cdda7841c2e56d4826170795054ba-screenshot-2022-05-27-at-6-06-32-pm.png)

![Screenshot 2022-05-27 at 6.06.41 PM.png](https://zube.io/files/rancher/c580e0321f5114e6f4177644b45aff3c-screenshot-2022-05-27-at-6-06-41-pm.png)

**Comment by sowmyav27** [comment]
**On 2.6.6 reproduced the issue**

- Create a single node Rancher cluster
- Create an RKE template
- Add a cluster with node pool -> enter some inputs in the pool -> select the RKE template drop down and select the RKE template -> node pool inputs will vanish
<img width="1509" alt="Screen Shot 2022-07-20 at 7 36 15 PM" src="https://user-images.githubusercontent.com/26032343/180117918-400e1e53-ac22-4925-977b-9831490826d3.png">

---

**On 2.6head commit id: `c47178e`**
- Create a single node Rancher cluster
- Create an RKE template
- Add a cluster with node pool -> enter some inputs in the pool -> select the RKE template drop down and select the RKE template -> node pool inputs are still available
<img width="1508" alt="Screen Shot 2022-07-20 at 7 36 36 PM" src="https://user-images.githubusercontent.com/26032343/180118054-43064ec7-01a0-4887-8e8c-f756ad474788.png">
<img width="1501" alt="Screen Shot 2022-07-20 at 7 38 31 PM" src="https://user-images.githubusercontent.com/26032343/180118062-8b769861-84b1-4bab-a7ff-f16cf108bf7d.png">

- Cluster is created with the right node pool names.
