### ISSUE TITLE
Prevent Select component to emit twice on value change

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#6167]
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Any

**Describe the bug**
The `Select` component emits `@input` twice on value change.

**To Reproduce**
Open any view with `Select` and select a value

**Result**

**Expected Result**
Single event and related side effects, e.g. HTTP requests.

**Screenshots**

**Additional context**
Create an unit test to verify correct expectation.

**Comment by aalves08** [comment]
@richard-cox this has dev-validate. Can we move it forward to Done? It has been lingering on testing for quite a while.
