### ISSUE TITLE
Default namespace is available to users when they dont have access to it.

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#617]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
In Rancher UI:
Create a cluster.
Create a cluster member and give access to cluster in Rancher UI.
Create a project and namespace as cluster member.

In dashboard:
Create a secret as type `certificate` as cluster member in `default` namespace.

**Result:**
By default, the `Namespace` field is the `default` namespace in the current cluster:
![Screen Shot 2020-05-06 at 1 56 59 PM](https://user-images.githubusercontent.com/57409052/81236371-e740fa00-8fb1-11ea-8a75-4e59cbcf191d.png)

Once Namespace is clicked, `Default` disappears and dropdown has only accessible namespaces:
![Screen Shot 2020-05-06 at 1 57 06 PM](https://user-images.githubusercontent.com/57409052/81236496-2ec78600-8fb2-11ea-97ff-073aabddc323.png)
If one of these are selected, the default namespace cannot be returned to.

If `Default` namespace is left alone, secret creation errors with:
```
{ "type": "error", "links": {}, "code": "Forbidden", "message": "secrets is forbidden: User \"u-npwb2\" cannot create resource \"secrets\" in API group \"\" in the namespace \"default\"", "status": 403 }
```
This is expected to fail. 

But the default namespace should not have been pre selected if the user can not access it.

**Comment by soumyalj** [comment]
Observed that cluster member has access to Default namespace [Cluster member should not have access to the Default namespace]
If a secret is created in the default namespace the following error is seen which is expected
```
{ "type": "error", "links": {}, "code": "Forbidden", "message": "secrets is forbidden: User \"u-d87mt\" cannot create resource \"secrets\" in API group \"\" in the namespace \"default\"", "status": 403 }
```

**Comment by soumyalj** [comment]
Observed the same issue when testing configmaps too. Default namespace is preselected in the form for users who do not have access to it.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version df306e720`

When a user does not have access to `default` namespace, an available namespace will be chosen starting with the first alphabetically.
