### ISSUE TITLE
Azure AD endpoint migration - Update end point button font should be more readable in light/auto mode

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#6172]
Setup

Rancher version: 2.6-head c8d01c6
Browser type & version: Chrome

**Describe the bug**
Update end point button font in light/auto mode is difficult to read. The font color can be more visible.

**To Reproduce**
On v2.6.5 rancher server version, navigate to Users and authentication >> Auth Provider >> Azure AD
enable Azure AD auth by selecting the standard endpoint.
Upgrade the rancher server version to v2.6.6-rc1 or v2.6-head
Navigate to Users and authentication >> Auth Provider >> Azure AD
Verify the `Update end point` button is available for the users to upgrade the end points.
From preferences select Light Theme

**Result**
The Update end point button is a bit difficult to read and the font color should be changed to be more readable.

**Expected Result**
Button description to be more readable.

**Screenshots**
Background color on the button `Update Endpoint` if changed to a dark color would be more readable. 

<img width="600" alt="UpdateEndpoint" src="https://user-images.githubusercontent.com/38144301/174870592-468bc799-98a9-47ea-b08a-d7ae770e972d.png">

**Comment by gaktive** [comment]
@anupama2501 can you provide screenshots for context?

**Comment by kwwii** [comment]
I think that we should make this button use a blue outline and blue text, as it seems to be the secondary call to action. 

I do not think we use a yellow button in any other patterns in the ui so I don't think this would break the standard (please correct me if I am wrong).

**Comment by kwwii** [comment]
If we feel we need to call more attention to this, we could also make the alert with the buttons use the *-warning background colour although I would try it with the normal BG colour first.
