### ISSUE TITLE
Missing certificate secret link on ingress detail page

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#6177]
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Chromium

**Describe the bug**
The ingress detail page is missing a link to the TLS certificate secret.

**To Reproduce**
Create an ingress with a tls configuration that points to an existing TLS secret for a certificate. 

Then go to the ingress detail page.

**Result**
The certificate secret name is shown but not linked.

**Expected Result**
There is a link which points to the secret.

**Screenshots**
<img width="739" alt="Bildschirmfoto 2022-06-15 um 16 45 39" src="https://user-images.githubusercontent.com/243056/173857025-d6db06b4-4dde-45ab-b436-22a29bbc1ee5.png">

**Comment by richard-cox** [comment]
It looks like this missed QA due to no MS. Even though it merged in 2.6.7, have tagged with 2.7q3 to get some validation
