### ISSUE TITLE
Certificate data is always tls.crt and tls.key

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#618]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
In dashboard, create a secret with Type `certificate`

**Result:**
Data is renamed `tls.crt` and `tls.key`, regardless of content. 
![Screen Shot 2020-05-06 at 4 03 05 PM](https://user-images.githubusercontent.com/57409052/81236991-48b59880-8fb3-11ea-84ad-b368289a4c80.png)

**Comment by deniseschannon** [comment]
The data isn't being renamed @aaronRancher. 

This is the yaml of the secret, which is type "Certificate". Rancher is just making a nicer way of editing/creating, but the data is actually a key value pair and the data is showing the "keys" of the table. 
```
data:
  tls.crt: LS0tLS1DRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ==
```

It doesn't make sense to show the actual content of the key or certificate, so for now, the design won't change for this.

**Comment by vincent99** [comment]
I don't know if this was quite @aaronRancher 's point or not, but... Yes the keys are always `tls.crt, tls.key`, but showing me those in the table is pointless _because_ they're always the same.

A list of the keys is useful for Opaque secrets, but repetitive and useless on specialized types like Service Account and Certificate.

For certificates, it would be a lot more useful to show the CN/SANs of the cert and/or the expiration date as the "Data", like Rancher currently does:

![image](https://user-images.githubusercontent.com/753917/81979929-9a2cdb80-95e2-11ea-8d62-edc7fba51707.png)

**Comment by aaronRancher** [comment]
The fix is verified with Rancher server `rancher\rancher:master-head` `version d9184e914`

Additional information is shown in `data` field
![Screen Shot 2020-05-26 at 2 52 09 PM](https://user-images.githubusercontent.com/57409052/82954912-8712f780-9f62-11ea-92e0-9eb406621e0a.png)
`
