### ISSUE TITLE
Cannot save options related to providers when editing RKE2 clusters

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#6180]
**Setup**
- Rancher version: 2.6-head
- Browser type & version: any

**Describe the bug**
If editing on the UI a provider specific configs on a RKE2, changes aren't saved properly but operation is successful on the UI side

**To Reproduce**
- create a RKE2 `Digital Ocean` cluster without any of the `Additional DigitalOcean Options`  selected.
- edit on the UI that Cluster (select any checkbox on `Additional DigitalOcean Options`) and hit `Save`

Update:
Would suggest QA also validate there's no regression regarding [#4800](https://github.com/rancher/dashboard/issues/4800)

**Result**
- Changes done are not saved

**Expected Result**
- Changes should be saved

**Screenshots**
<img width="1519" alt="Screenshot 2022-06-15 at 15 06 15" src="https://user-images.githubusercontent.com/97888974/173876683-ff3c137b-1608-4c75-b664-b2001e90d42d.png">

**Additional context**
Problem seems to be the output of the `merge` occurring in https://github.com/rancher/dashboard/blob/master/shell/edit/provisioning.cattle.io.cluster/rke2.vue#L1025

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/069433410f08903ae5967e5178867c2622bce419.

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/069433410f08903ae5967e5178867c2622bce419
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Created a standard user and logged into Rancher as that user.
3. Provisioned a downstream RKE2 Linode cluster.
     - Ensured that I DID NOT check off the `Private Networking` option when provisioning the cluster.
4. Once the cluster is provisioned, edited the cluster's config.
5. In section `Additional Linode Options`, enabled option `Private Networking` and clicked `Save`.
6. Verified that the changes have been saved:
![image](https://user-images.githubusercontent.com/52591819/177365700-834f6adb-7359-4050-aff1-953e9a72dfe6.png)
7. Provision a second downstream RKE2 Linode cluster, but click `Edit as YAML` before clicking `Create`.
8. Verified that the cluster there is no error regarding `rke-machine-config`.
9. Edit the second cluster's config and on the `Additional Linode Options`, enable `Private Networking` and click `Save`.
10. Verified that the changes have been saved:
![image](https://user-images.githubusercontent.com/52591819/177365677-ba208c27-ba4f-4ba5-8d73-2820d1aec395.png)
