### ISSUE TITLE
"Rancher Backups" helm chart -- during installation, on the 'values' page none of the required fields are marked as such.

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/dashboard#6181]
**Rancher Server Setup**

- Rancher version v2.6.- head `f4d09c7`

**Information about the Cluster**

- Kubernetes version: v1.21.12
- Cluster Type (Local/Downstream): Downstream node driver 1 worker, 1 etcd, 1 cp RKE1

**Bug Description**
When  installing the helm chart "Rancher Backups" and selecting S3 storage, the bucket name and endpoint are required fields, however the UI does not display this information and users are allowed to attempt to install the chart without providing the required fields. 

**Reproduction Steps**
1. stand up Rancher instance and a downstream cluster
2. In Rancher UI Navigate to Local cluster > apps and marketplace > charts > Rancher Backups 
3. click to install latest Rancher Backup
4. select to install to 'system' project. 
5. click next
6. for storage options, select the S3 compatible object store. 

**Expected Result** 
Required fields are clearly designated and the user is not allowed to click 'install' before providing them.

**Actual Result**
Neither endpoint or bucket name appear to be required fields, users can click install without providing either value

**Screenshots**

error thrown when attempting to install without a bucket name ![image.png](https://zube.io/files/rancher/6ba2fb55f2eeea80561edc509cee6468-image.png)

screenshot showing lack of UI designation that the fields are required 

![image.png](https://zube.io/files/rancher/7d5331885ac0d01b2ae9b817d4fb2747-image.png)

**Comment by nickwsuse** [comment]
`Verified on v2.8-head ID: d101c27`

The required fields now have the red asterisk* to show that they are required, and the `Install` button isn't clickable until both of those fields have values.
