### ISSUE TITLE
Disable ability to edit any secret associated with a service account token

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#619]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a new project
Create a new namespace
View secrets in dashboard in new namespace
![Screen Shot 2020-05-06 at 4 11 26 PM](https://user-images.githubusercontent.com/57409052/81237456-91218600-8fb4-11ea-8e2e-3f5f3c3ef176.png)
Edit default-token

**Result:**
Cert, namespace, and token can be edited.
![Screen Shot 2020-05-06 at 4 11 12 PM](https://user-images.githubusercontent.com/57409052/81237495-a39bbf80-8fb4-11ea-81b7-1c77379a4133.png)

Question: Should we NOT be allowed to edit this entry ?

**Comment by deniseschannon** [comment]
For any secret associated with a service account token, we should not be able to edit the underlying secret.  

We should remove the options from the list page and detail page to be able to edit (either form or yaml) for these secrets. We should only be able to view them.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 7248f0966`

Service account secret cannot be edited:
![Screen Shot 2020-05-14 at 4 16 20 PM](https://user-images.githubusercontent.com/57409052/81995184-75466180-95fe-11ea-85af-0caf16a346fa.png)
