### ISSUE TITLE
[Fleet UI] GitRepos show as active even if Bundle status indicates error

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#6194]
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Brave (Chrome)

**Describe the bug**

On seeing an error with a Bundle deployed on a GitRepo, we should display some sort of error.

![Screen Shot 2022-06-16 at 3 42 52 PM](https://user-images.githubusercontent.com/13127443/174190317-7dcd3d6f-06ec-4d65-bdf2-fb957392a3b4.png)

**To Reproduce**

1. Fork https://github.com/rancher/fleet-examples and modify the release name [here](https://github.com/rancher/fleet-examples/blob/ffdc8d483baddd94ae5e4a6c0fdb49de12613b3a/single-cluster/helm/fleet.yaml#L10) to be greater than 53 characters (triggering the error we see above)
2. Add your forked fleet-examples repo as a GitRepo on the continuous delivery page of Rancher (note: fleet-default should be the namespace / workspace on the top right and it's sufficient to provide a single path on this GitRepo to watch, namely `/single-cluster/helm`
3. Wait for the Bundle to show up on the first sync

**Result**

GitRepo is green itself, but the bundle contained within it is not.

**Expected Result**

UI should indicate that this GitRepo is in some sort of error state?

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by Shavindra** [comment]
UI changed. UI no longer shows the top status bars. So this works as intended

**Comment by izaac** [comment]
Reproduced on Rancher `v2.6.5`

- GitRepo Active
- Bundle in Error state

Validated in Rancher `v2.6.9-rc3`

- GitRepo in Error state (Expected)

<img width="1285" alt="Screen Shot 2022-10-06 at 1 39 55 PM" src="https://user-images.githubusercontent.com/27659/194414525-44b6b594-e425-486d-8c33-43aa341d1c37.png">

- Bundle not created due to long name error (Expected)
