### ISSUE TITLE
Cluster templates cannot be used unless accessing the local cluster explorer first

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#6195]
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Firefox 101.0.1 (64-bit)

**Describe the bug**
Trying to leverage a cluster template results in a UI error unless cluster explorer has been accessed for the local cluster

**To Reproduce**
- Navigate to local cluster via `explorer`
- Add git repo https://github.com/rancher/cluster-template-examples via Apps and marketplace
- Logout
- Login
- Navigate to cluster explorer -> Create cluster
- Select the cluster template

**Result**
Cluster creation page does not progress, browser console throws an error:

```
TypeError: this.$rootGetters.currentCluster is undefined
    value chart.js:12
    value chart.js:41
    clickedType index.vue:401
    VueJS 4
    select SelectIconGrid.vue:80
    click SelectIconGrid.vue:3
    VueJS 3
vue.runtime.esm.js:1888:12
    VueJS 7
    select SelectIconGrid.vue:80
    click SelectIconGrid.vue:3
    VueJS 3
```

**Expected Result**
To progress to cluster creation

**Screenshots**

https://user-images.githubusercontent.com/5892615/174267319-a0003985-8e1e-4b65-8a2f-11c51f37bea0.mp4

**Additional context**
Current workaround - Within the UI session, navigate to the local cluster explorer page and then straight to cluster management

**Comment by slickwarren** [comment]
Tested on rancher v2.6-head (59eebba):
* add cluster template repo and navigate directly to   create on home page -> select cluster template -- pass
* add cluster template repo and navigate to local cluster, then cluster management -> create -> select cluster template -- pass
