### ISSUE TITLE
UX FIX: Elements in the  "Header dropdown" should not be displayed as a link 

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#6201]
**Setup**
- Rancher version: 2.6
- Browser type & version:

**Describe the bug**

The dropdown in the header bar shows different elements, but those are not link, we need to change the color and make it look like as menu items

![Screenshot 2022-03-28 at 20 51 53](https://user-images.githubusercontent.com/6459624/174752551-208a78cd-8d78-4d94-bde5-19285cab1e37.png)

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by nwmac** [comment]
@manuelecarlini This is the old namespace/project chooser - can you take a look at the latest UI - I'm not sure what you were proposing we change.

**Comment by kwwii** [comment]
I think this might be mainly fixed but we should verify the presentation.

**Comment by markusewalker** [comment]
@manuelecarlini can you provide a status update regarding this issue? I see it is in `Review`, but there is no associated PR to this ticket.

**Comment by markusewalker** [comment]
While we wait for this issue to be addressed, here is the QA test plan:

**TEST PLAN**
1. Setup Rancher and navigate to the UI in a browser.
2. Navigate to Cluster Explorer > local.
3. In the dropdown menu that says `Only User Namespaces`, click that and verify if elements in the dropdown appear as different elements and not links.

**Comment by kwwii** [comment]
For clarification, is this in the new UI or in the ember UI? I believe that this has been fixed in the new UI and doubt that it would be changed in the old one.

**Comment by markusewalker** [comment]
@kwwii circling back to this issue, can you please provide a PR where this has been addressed in the new UI so that QA can properly validate? If this has already been addressed, we can proceed forward with validating and closing this.

**Comment by catherineluse** [comment]
I haven't found the PR, although I can confirm that in the latest version, the items in the nav aren't blue anymore:
<img width="488" alt="Screen Shot 2022-09-08 at 1 14 10 PM" src="https://user-images.githubusercontent.com/20599230/189217147-329eb487-978e-4bd0-a0c4-441cc23c3bec.png">

**Comment by markusewalker** [comment]
Thanks @catherineluse, I see the same as well. Considering this is a relatively smaller issue, I will go ahead and provide an official QA sign off in a new comment to validate this and close this issue.

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.6-head` https://github.com/rancher/rancher/commit/f9001728bc8f0851ea5fea451cdce7cc04b473ec.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/f9001728bc8f0851ea5fea451cdce7cc04b473ec
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigated to the UI in a browser.
2. Navigated to Cluster Explorer > local.
3. In the dropdown menu that says `Only User Namespaces`, clicked that and validated that the elements in the dropdown appear as different elements and not links:
![image](https://user-images.githubusercontent.com/52591819/189218378-97604e71-6412-469f-a66a-2645f37ac006.png)
