### ISSUE TITLE
UX Fix: The Cluster Management Drivers page has a wrong tab element

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#6202]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**
The Cluster Management Drivers page has a wrong tab element
While another tabs style in the system are displayed with a line under
dashboard/c/local/manager/pages/rke-drivers

![Screenshot 2022-03-28 at 20 59 04](https://user-images.githubusercontent.com/6459624/174754869-69bc96d0-dd07-4947-abd8-bf3bc265380d.png)

**To Reproduce**

**Result**

**Expected Result**

Align the tab style with the other present in the system

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment]
There are some pages that use the embedded cluster manager views with their old UI components. Unfortunately this is one of them
