### ISSUE TITLE
UX FIX: Page title is not updated based on the current location

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#6206]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**
Page title is not updated based on the current location.

**To Reproduce**
Navigate through pages.

**Result**
The page title is always `Rancher`.

**Expected Result**

**Screenshots**

https://user-images.githubusercontent.com/5009481/174826993-9c7f0695-32f7-423c-bb9a-964a546b98ed.mov

**Additional context**
It's convenient to have always the page title updated based on the view.
E.g.: If in Cluster - Local dashboard, it should be updated as `Rancher - Cluster: local`

**Comment by richard-cox** [comment]
@cnotv Can you provide further detail?

**Comment by richard-cox** [comment]
Given https://github.com/rancher/dashboard/issues/9822 has more detail, i'll close this as a duplicate
