### ISSUE TITLE
Namespaces not appearing clearly on constraint display page.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#621]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard, enable gatekeeper.
2. Create a constraint under 'k8sallowedrepos'. - 'testconstriant'
3. Go to constraint page and click the 'testconstriant'

**Result:**
Texts in namespace text box are not clear.
<img width="1306" alt="Screen Shot 2020-05-07 at 3 44 49 PM" src="https://user-images.githubusercontent.com/60111667/81351891-220e6500-907a-11ea-93b3-3ff57589efa9.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master branch on 2.4-head ```454daa475``` rancher set up.
- Installation option (single install/HA): Single

**Comment by codyrancher** [comment]
This is resolved in the latest.

**Comment by izaac** [comment]
Rancher version: `v2.4-head (05/19/2020)` commit id: 8e20687a4
`CATTLE_DASHBOARD_INDEX=https://releases.rancher.com/dashboard/latest/index.html`

This is looking good in both light and dark themes.

![Screen Shot 2020-05-19 at 4 45 35 PM](https://user-images.githubusercontent.com/27659/82389226-6e4d9380-99f0-11ea-9c0e-8cdd2e562a66.png)
![Screen Shot 2020-05-19 at 4 46 05 PM](https://user-images.githubusercontent.com/27659/82389231-70175700-99f0-11ea-8262-557957489fed.png)
