### ISSUE TITLE
Add support for AWS ec2 r5a and r5n instance types for Rancher 2.x

### ISSUE THREAD

**Issue by vtrusevich** [rancher/dashboard#6211]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature Request:
Please add support for AWS r5a and r5n instance types (same performance as R5 but with 10% cost savings (for r5a) and with better network throughput (for r5n)).

**Other details that may be helpful:**
This is the same request as [this](https://github.com/rancher/rancher/issues/20372) but for r5a and r5n instance types

gz#15440

**Comment by gaktive** [comment]
For Dashboard (Cluster Explorer), this list is generated dynamically so newer instances types are being grabbed automatically via the Amazon API. I have to track down when this was added within the 2.6.x timeframe but it's been there a while (see screenshots)

<img width="1178" alt="Screen Shot 2022-08-12 at 9 27 03 AM" src="https://user-images.githubusercontent.com/11466788/184406011-1dbb3468-07da-4fb5-9e66-a9107ed94b9c.png">
<img width="1092" alt="Screen Shot 2022-08-12 at 9 27 11 AM" src="https://user-images.githubusercontent.com/11466788/184406031-4d4be90f-4f4f-42b5-b59c-73657934e63f.png">

For the older UI (2.5.x), we have https://github.com/rancher/dashboard/issues/5205 as a ticket to backport this.

Let me know if you don't see R5A or R5N in the newer UI and let me know what version you're running.

**Comment by gaktive** [comment]
For QA, please validate simply that these instance types are visible in 2.6.7. The backport work can be tracked in the other ticket.

**Comment by catherineluse** [comment]
Note: The new instance list is available for RKE2/K3s clusters, but not RKE1, because the RKE1 cluster provisioning UI uses the iFramed Ember page from 2.5.x.

**Comment by MSpencer87** [comment]
**_Verified on 2.6.7-rc9_**

Both r5a and r5n instance types are visible for RKE2 Nodedriver provisioning

**Steps to verify:**
1. Bring up Rancher on 2.6.7-rc9
2. Select Create to create a cluster and select Amazon EC2
3. Enter Cloud Credentials for Aamazon EC2
4. Select the dropdown menu for Instance Type, scroll to find r5a and r5n instances
![Screen Shot 2022-08-12 at 11 26 32 AM](https://user-images.githubusercontent.com/6477538/184428322-4ed86aed-86ed-4242-8387-f86206aeb206.png)
![Screen Shot 2022-08-12 at 11 26 50 AM](https://user-images.githubusercontent.com/6477538/184428352-f8dd1d7e-f830-4438-8048-794d0730f6da.png)
