### ISSUE TITLE
20000 pods page stuck

### ISSUE THREAD

**Issue by mimimamahaoduozi** [rancher/dashboard#6213]
**Setup**
- Rancher version: 2.6.4
- Browser type & version: chrome lastest

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment]
Please can you fill out the issue template.

**Comment by mimimamahaoduozi** [comment]
> Please can you fill out the issue template.

Describe the bug
I have around 20,000 pods and when I open the page the UI rendering is often blocked.
To Reproduce
You can use 20,000 pods for stress testing
Result
The page freezes or even crashes
Expected Result
The page runs smoothly

**Comment by mimimamahaoduozi** [comment]
> * How many nodes do you have, and can you provide a rough number of total resources?
70 nodes
> * What is the type of your cluster (RKE1, RKE2, k3s, etc)
RKE1
> * If you refresh the browser whilst on the pods list page how long does it take the initial lists to show?
api about 14s.   render about 5s
> * Once the page is loaded, how long does it take to change the sort order of the name column?
about 3s
> * At any point are there errors in the browsers dev tool's console?
have not


When it is critical, my mouse often fails to operate the page, but my mouse can move normally

**Comment by richard-cox** [comment]
@mimimamahaoduozi You might be interested in a feature from 2.7.5 that filters resources via the values in the namespace / project filter in the header. This greatly reduces the number of resources fetched by the UI. To enable please go to burger menu top left --> `Global Settings` --> `Performance` --> `Require Namespace / Project Filtering` and check the box and hit `Apply`.

**Comment by richard-cox** [comment]
This falls in the general 'we shouldn't fetch all resources' sphere. There's a current workaround listed in https://github.com/rancher/dashboard/issues/6213#issuecomment-1680473631 and will be fully resolved via https://github.com/rancher/dashboard/issues/8527
