### ISSUE TITLE
Allow link customisation on Home page "docs" link (and others)

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#6218]
**Detailed Description**
Rename "Community Support" to "Helpful Links" and allow customisation of the text and links.

**Context**
Customers often have internal documentation that their development teams consume (the main ui users of the Rancher UI). We should allow them to link to this documentation or other sources of helpful information on the Home screen.

**Comment by gaktive** [comment]
Possible duplicate.

**Comment by nwmac** [comment]
Duplicate - closing in favour of 2.7.0 work
