### ISSUE TITLE
ClusterRole/Role edit as yaml, yaml not contains apiGroups if resource is core type

### ISSUE THREAD

**Issue by chrisho** [rancher/dashboard#6223]
**Rancher Server Setup**
- Rancher version: `v2.6.5`
- Installation option (Docker install/Helm Chart): docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
     Node Setup: 1 node
     Version: `v1.23.6+k3s1`
- Proxy/Cert Details:  `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.23.7+rke2r2`
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
when editing clusterrole/role, click `edit as yaml`, yaml not contains apiGroups if resource is core type

**To Reproduce**
1. edit clusterrole/role config page.
2. select any verbs and any core resources, then click `edit as yaml`.
3. click `edit yaml`.

**Result**
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test
  annotations:
    {}
  creationTimestamp: '2022-06-23T02:31:22Z'
  labels:
    {}
  resourceVersion: '2423173'
  uid: c53fa817-f06c-4670-bc07-395188ccd2fb
  fields:
    - test
    - '2022-06-23T02:31:22Z'
rules:
  - resources:
      - Node
    verbs:
      - list
      - update
  - resources:
      - Pods
    verbs:
      - delete
__clone: true
```

**Expected Result**
The result contains apiGroups, whether empty or not.

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment]
@codyrancher I couldn't assign @ly5156 , so to avoid it being unassigned it's gone your way

**Comment by catherineluse** [comment]
I could not reproduce this issue in the latest version of master.

I created roles for resources in the core Kubernetes API, such as namespaces and nodes, and saw that the YAML is already adding an empty string for their API groups.
This configuration for listing namespaces -
<img width="1339" alt="Screen Shot 2022-06-29 at 3 25 35 PM" src="https://user-images.githubusercontent.com/20599230/176556635-e56f16b0-77c5-4a90-9d96-9e52f5f53367.png">
Resulted in this YAML:
<img width="593" alt="Screen Shot 2022-06-29 at 3 26 21 PM" src="https://user-images.githubusercontent.com/20599230/176556686-d5335fbd-13fa-4d76-a69c-1b9e321c3298.png">

**Comment by chrisho** [comment]
> I could not reproduce this issue in the latest version of master.

you can try `edit config` and `edit as yaml`
<img width="166" alt="image" src="https://user-images.githubusercontent.com/3347460/176619215-92340e14-96a2-4678-b687-04c7e82a8841.png">

**Comment by ly5156** [comment]
@chrisho 
The `edit as YAML` button is no longer available  in the latest version of master
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/3406205/177310949-317ba38d-6237-4edc-8330-85e0f0a302b4.png">
<img width="1522" alt="image" src="https://user-images.githubusercontent.com/3406205/177311493-a771e25c-ed9e-4523-840f-839214ecb632.png">
