### ISSUE TITLE
Continuous Delivery Git Repo Auth Secrets are hard to pick

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#6239]
**Detailed Description**
Existing auth secrets in the Git Repo UI of Continuous Delivery are hard to pick, because the dropdown only shows the name of the secret (which is auto-generated when created through the same UI before) and the type. If you have multiple secrets, it's hard to tell which is the right one.

**Context**
Example screenshot
<img width="950" alt="Bildschirmfoto 2022-06-28 um 14 26 10" src="https://user-images.githubusercontent.com/243056/176178635-e82ace91-aa3c-4fea-8729-c9ebcaa1f329.png">

Proposed change:
The Secrets list contains an additional data column to identify the secrets easier. These could be included in the dropdown as well:
<img width="1022" alt="Bildschirmfoto 2022-06-28 um 14 29 32" src="https://user-images.githubusercontent.com/243056/176178861-d4082f22-61d2-4065-9437-0cefadac9b73.png">

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/a678d0e12fe21936f09ae0e906bc420e43d7d35c.

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/a678d0e12fe21936f09ae0e906bc420e43d7d35c
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Navigated to Cluster Explorer > Continuous Delivery > Git repo.
3. Create a new Git repo against a public (or private) Git repo.
4. Once done, attempted to create another Git repo and verified that the `Git Authentication` dropdown correctly shows your new repo.
![image](https://user-images.githubusercontent.com/52591819/177840911-eab01419-9b76-4396-a1f8-f04ca64e6570.png) 
5. Navigated to Cluster Management and attempt to provision a downstream RKE2 node driver cluster.
6. In `Cluster Configuration` click `Registries` and select `Pull images for Rancher from a private registry`.
7. Clicked the `Authentication` dropdown and verified that the Git repo is successfully shown:
![image](https://user-images.githubusercontent.com/52591819/177840936-935dab16-a0b1-45bf-a031-3e8df3a5668c.png)
