### ISSUE TITLE
Bug about setting affinity and priority

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#6244]
**Setup**
- Rancher version: v2.6.5
- Browser type & version: 103.0.5060.53

**Describe the bug**

Set pod affinity, when I select `Affinity` from the Tpye dropdown, it shows as `Anti-Affinity`. When `Anti-Affinity` is selected, it appears as `Affinity`

The same situation exists for setting Priority

**To Reproduce**

1. Create a deployment
2. Navigate to `Pod Scheduling`
3. Set `Type` and `Priority`

**Result**
Set pod affinity, when I select `Affinity` from the Tpye dropdown, it shows as `Anti-Affinity`. When `Anti-Affinity` is selected, it appears as `Affinity`

The same situation exists for setting Priority

![Affinity](https://user-images.githubusercontent.com/19684717/176367845-e84ec9ee-f363-45d7-a6db-a1c82c2fe5c0.gif)

**Comment by ly5156** [comment]
@richard-cox @kingsd041 
This issue is already being fixed in this [PR](https://github.com/rancher/dashboard/pull/5999) and it has been merged into the master branch

**Comment by brandonsuse** [comment]
@nickwsuse  this one should be pretty self-explanatory, however, let me know if you have any ?s on this. Thanks!

**Comment by nickwsuse** [comment]
`Verified on v2.6-head 650cb0b`

The type and priority drop-downs now show the correct option when selected.
