### ISSUE TITLE
Service detail page does not always show load balancer ip

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#6245]
**Detailed Description**
The details section of the Service detail page does not always show the external IP or hostname of a LoadBalancer Service.

Currently the external IP is only shown, if it was defined in the Service spec. In most cases the external IP or hostname of a LoadBalancer Service is automatically assigned by the cloud provider though. In that case `spec.loadBalancerIP` is empty. But you can see the assigned information in `status.loadBalancer.ingress`.

**Context**
Displaying the IP or hostname makes it easier for users to copy and paste this information.

**Comment by gaktive** [comment]
This may help with #8087 though I'd have to dig in deeper.

A milestone was left off this work so if it's in To Test, QA can look for 2.7.2.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head d559c2f
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 110

----------

### Testing: ###
Tested this issue with the following steps:
1. Provision hosted cluster (AKS used)
2. After cluster becomes active, create loadbalancer service
3. Leave external IP undefined
4. Create

**Result**
External IP was automatically populated and is no longer left blank (addresses redacted)
![image.png](https://zube.io/files/rancher/0e55ec7b3e8374b6fb1015722fe6faac-image.png)
