### ISSUE TITLE
Support `gp3` as an EBS volume type

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6247]
When creating a storage class in Rancher, the list of storage types needs to include `gp3`.

Upstream docs: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html

I created this issue to correspond to this already completed PR https://github.com/rancher/dashboard/pull/6243

**Comment by catherineluse** [comment]
When the GP3 option is selected, the `Provisioned IOPS` input should also be displayed. https://github.com/rancher/dashboard/pull/6243

**Comment by richard-cox** [comment]
Issue missing milestone, so was not picked up by QA. After chatting with Neil, closing this type of ticket.
