### ISSUE TITLE
Confirmation of the deletion of multiple clusters, only prompts to confirm the first cluster name to remove them all

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#6257]
**Setup**
- Rancher version: `v2.6-5c781242c4581e5572d4749f2f0b9be62a6f2071-head`
- Browser type & version: `Chrome`

**Describe the bug**
When selecting multiple cluster to delete, the confirmation message only prompts to confirm the name of the first cluster selected to remove all clusters selected

**To Reproduce**
1. Fresh install of rancher `v2.6-head`
2. Provision multiple downstream clusters - [ANY]
3. Delete multiple clusters at once
4. Reproduced

**Result**
Deletion confirmation prompts for the first selected cluster to be entered to remove the list of selected clusters

**Expected Result**
Each cluster selected for deletion should have to be confirmed by entering the cluster's name; not just the first one from the list

**Screenshots**
<img width="366" alt="Screen Shot 2022-07-01 at 10 21 48 AM" src="https://user-images.githubusercontent.com/46494969/176958457-37ad6eb4-d69a-42e3-a1f4-1b49649560ed.png">

**Comment by richard-cox** [comment]
I've created https://github.com/rancher/dashboard/issues/6260 to better catch the issue and chosen resolution
