### ISSUE TITLE
"Not in a project" filter shows namespaces that are in projects

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6258]
Seen in v2.6-head.

To reproduce,

1. Create namespaces outside of any project
2. In the top nav of cluster explorer, select "Not in a Project"
3. In the side nav, click **Cluster > Projects/Namespaces**
4. See that namespaces in default and system projects are displayed

<img width="1538" alt="Screen Shot 2022-07-01 at 9 02 19 PM" src="https://user-images.githubusercontent.com/20599230/176985812-83d3ca04-72df-4445-baa9-8dedab12c7db.png">

**Comment by richard-cox** [comment]
The namespace resource isn't filtered by namespace (or by proxy project). I'm not sure we could mark the namespace resource as namespaced, as this would lead to weird routing issue when viewing/editing one. So for this specific list we would need to apply the same namespace/project filter.

**Comment by catherineluse** [comment]
Closing as duplicate of https://github.com/rancher/dashboard/issues/5088
