### ISSUE TITLE
Authorize one of the configmap resources for multiple configmaps

### ISSUE THREAD

**Issue by YouthInThinking** [rancher/dashboard#6266]
I hope rancher will add the ability to license resource files individually.

As shown in the picture
In the case of multiple configmap files under the same namespace, I want to grant read or write access to one of the specific files, so that normal users can only see the specific files they are authorized to see.

![Snipaste_2022-07-05_15-54-25](https://user-images.githubusercontent.com/38899870/177278491-38ca7503-1bf2-43be-b5fb-9b26036be7b4.png)

For the same resource type under multiple namespaces, you can implement regular matching to achieve batch authorization of specific files, thank you.

**Comment by gaktive** [comment]
This would require a major rewrite of our RBAC since this isn't something available in Kubernetes (at least with current versions). Based on the effort required, especially with the backend, we won't do this. Thank you for the suggestion though :)
