### ISSUE TITLE
Advanced filtering and column toggling for Elemental

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#6268]
- Add advanced filtering and column toggling for Sortable table based on the designs done for Elemental

**Design:**
https://xd.adobe.com/view/462809a7-1771-40a6-8c6d-b9faf2a865d2-137b/screen/68ead2f7-3497-44db-a962-0b2080bded59

**How to test feature**
- Test on `rancher/dashboard`, `OS management` (elemental) product

- Install the `elemental-ui` on `extensions` in `rancher/dashboard`

- Install `elemental-operator` => https://elemental.docs.rancher.com/elementaloperatorchart-reference

Go to Local cluster -> open kubectl shell -> install helm chart:
```
helm install --create-namespace -n cattle-elemental-system elemental-operator \
             oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/rancher/elemental-operator-chart
```

- Update `elemental-operator`

On the same kubectl shell run:
```
helm upgrade -n cattle-elemental-system \
             --install elemental-operator \
             oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/rancher/elemental-operator-chart
```

- Enter side-menu entry `OS Management`

- Go to `Machine Inventories` list view and create a few items of this resource type

**What to test**
- add multiple filters and make sure they are applied correctly (allows for partial string search). 
- Remove them individually and remove all (reset) and make sure list updates correctly
- make sure `group by` on table options works properly
- make sure that you can toggle/show labels as table cols from table options (you'll need to add some labels to some of the created resources)

<img width="1935" alt="Screenshot 2022-11-07 at 11 45 45" src="https://user-images.githubusercontent.com/97888974/200302508-960c35df-19de-436a-9111-1d3e8e215324.png">
<img width="1935" alt="Screenshot 2022-11-07 at 11 45 55" src="https://user-images.githubusercontent.com/97888974/200302513-f70d0a27-8f00-4397-b45d-5384c293605b.png">

**Comment by markusewalker** [comment]
@aalves08 @nwmac it seems this issue is scheduled to be en route with issue https://github.com/rancher/dashboard/issues/6040, is this correct? Could either of you provide a status update as to when QA can expect this to no longer be in review? 

Thank you!

**Comment by aalves08** [comment]
This has been merged to `rancher/dashboard` following all of the work done for `elemental-ui`. It's only available for testing on the `Machine Inventories` resource on Elemental UI. Instructions have been added to this issue on how to test. 🙏

**Comment by AndrewHoffmanQA** [comment]
@aalves08 I am attempting to repro this issue however i'm stuck on the upgrade of the elemental operator. 

- I stood up a new HA rancher
- installed the repository
- ran the install command
- got a failure when running the upgrade command 'failed to download'

did the path change? 

![image](https://user-images.githubusercontent.com/89030218/206751044-6a33dac4-84d6-46a6-accc-7a83fb7a5d32.png)

**Comment by aalves08** [comment]
Hello @AndrewHoffmanQA . I am sorry about that but the elemental team updated the helm chart a couple of weeks ago and I never remembered to update the issue description/instructions.

It should now be correct.

Basically you don't need to add the `elemental-ui` anymore as it's included on the `extensions` repo which is available by default + updated the helm chart name/reference and also added a link to the proper docs.

**Comment by AndrewHoffmanQA** [comment]
hey @aalves08, thank you for the update! 

i'm still having trouble installing the elemental operator. 

I stood up both a 2.7-head and a 2.7.0 env and found the same result. 

I installed the extensions operator and the elemental extension chart successfully, however when i run the kubectl commands, the elemental-operator deployment sits in `Deployment does not have minimum availability. `  and the elemental-operator pod is in a `Containers with unready status: [elemental-operator]` state. 


this is what the kubectl console looked like when running the commands



![image](https://user-images.githubusercontent.com/89030218/207946758-8acbdaec-71c7-4cc6-8276-e075f93d19ea.png)

**Comment by aalves08** [comment]
Hi @AndrewHoffmanQA . Can you try and upgrade the `elemental-operator` Helm chart? it's now on v1.0.2. https://elemental.docs.rancher.com/elementaloperatorchart-reference/#upgrading-chart

Apart from this, I don't know what to do more... Backend should be `v2.7.0` and frontend `v2.7-head`. All the steps described should be correct, afaik.

We can book some time together to try and troubleshoot the problem.

Will await you feedback 🙏  Thank you

**Comment by Itxaka** [comment]
if your rancher server has podsecuritypolicies enabled they might be interfering with the deployment. the operator deployment makes no effort to set a USER to run the image so kubernetes cannot infer what user is supposed to run inside the container and assumes its root, but the policy marks this container as RunAsNoRoot so it cannot run it.

Modifying the elemental-operator deployment to mark set the following options seems to make it work.
![image](https://user-images.githubusercontent.com/1447686/208112143-48ab4d25-eee2-45e5-944d-7bc89598cae4.png)


It could also work if the `restricted` pod security policy is removed so it picks the default-psp which is more permissive. Or even removing all psp as they are deprecated and no longer valid in k8s 1.25

**Comment by AndrewHoffmanQA** [comment]
### testing status: Passed 
tested on local HA 2.7head-5df9701

### testing scope 

### Filter
- validated filter for functionality works as expected. 
- validated partial string filter functionality
- validated ability to add and remove multiple filters at one time and that the page updates appropriately and retains the column selections made in the 'group by' section

### Group By 
- validated the ability to group by the 3 different 'group by' options
- validated labels are displayed as a 'show' option
- validated the ability to apply and remove columns

### Misc
- validating grouping and filters work together as expected
- validated removing machines with unique labels update the table appropriately
- validated removing machines updates the group my and filter window appropriately



### upper and lower limit testing
created 20+ labels, no display issues could be found. also created the max label and value, grouped my and filtered with them with zero issues. 

picture of table displaying long names and tons of extra columns gracefully without display errors.
![image](https://user-images.githubusercontent.com/89030218/208507763-da7316db-0f17-4fb4-bc83-1cbef6b0d501.png)


note: when a key is 63+ characters users will not see the full screen in group by /filter functionality (see screenshot)


@aalves08 in future updates to this functionality it may be helpful to show the full name of a label if the user hovers their mouse over the field. 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/89030218/208506543-a5e1a560-25d7-4857-aed7-cf0ff14e3545.png">

### Testing notes
- the filters are MOST restrictive type. aka the table only displays data that meets every filter requirement currently applied to the table

### Open questions
- @aalves08 could you please clarify, should users be able to 'sort' by labels? that functionality is currently not offered. 
![image](https://user-images.githubusercontent.com/89030218/208509539-3f28d845-b4e6-43a0-b997-5823cfa16ff5.png)

keeping this ticket open until the 'sort by' question is answered.

**Comment by aalves08** [comment]
@AndrewHoffmanQA thanks for testing and for the comments. 🙇 

Currently is not possible to sort by labels as the logic for it is more complex and out of the initial scope. 

There is an open issue to enhance the advanced filtering:
https://github.com/rancher/dashboard/issues/7206

I'll add there the sorting and the hover to show the full labels. 🙏

**Comment by AndrewHoffmanQA** [comment]
per feedback from Alexandre, sorting by labels is out of scope for this ticket. 

this ticket has been fully tested and is being moved to the 'done' column
