### ISSUE TITLE
[UI] - Navigation filter should clear when click on "Remove"

### ISSUE THREAD

**Issue by sebastienroul** [rancher/dashboard#6282]
Rancher v2.6.6

The navigation filter was really a great idea in the UI, and we love using it, but there some stange/bad UX things.
![image](https://user-images.githubusercontent.com/2582255/177711220-ab18a84e-4212-428f-846d-8ed262429bcf.png)

When clicking on "x" to remove "report", it doesn't remove report, but open the menu
![image](https://user-images.githubusercontent.com/2582255/177711414-d6b1cae1-7f41-4b5c-a2dc-7cdc2058cd15.png)
Then you must click again.

Expected : Clean the "report" filter

You could also implements : IF it's the last filter, THEN remove it AND open the menu ELSE just remove it

**Comment by Josh-Diamond** [comment]
Ticket #6282 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-edf59f620ceec6b3f22507b4d1ac780d392568df-head`:
1. Fresh install of rancher `v2.7-head`
2. Navigate to `Cluster Explorer` for any cluster
3. Using Navigation filter, add one filter, then remove it
4. Verified - successfully added + filtered, and successfully removed
5. Using Navigation filter, add multiple filters, then remove them one at a time
6. Verified - filters are added + filtering, then removed as expected; menu opens and closes as expected too
