### ISSUE TITLE
'View in API' preference is not obvious

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6289]
View in API is enabled by setting the developer setting in prefs - this is not obvious

Need to think about discoverability

**Comment by kwwii** [comment]
We should change the title of this to "Advanced/Developer Features" and list them individually with checkboxes. I think this is where the preference for the advanced filtering would be at first.

**Comment by kwwii** [comment]
This is similar to https://github.com/rancher/dashboard/issues/5813

**Comment by kwwii** [comment]
If we cannot turn this on/off individually, we should at least include a list of the features which will be enabled. If this only affects one action, we only need to correct the label.

**Comment by gaktive** [comment]
We would need to research what actually is exposed when turning on this checkbox so that we can come up with appropriate wording.

This would require a new issue around advanced filtering so if we do enable it, we should get it into a new page and then test it.

**Comment by richard-cox** [comment]
We do (only recently) describe what the `enable developer tools & features` checkbox does

![image](https://user-images.githubusercontent.com/18697775/184605345-a2682037-3d4e-4726-9790-78672a569349.png)

As Ken suggested I think we need to make this more granular. The `View in API` feature is one a lot of users like and use, however it's bundled in with the feature to reveal Rancher namespaces which confuses a lot of users and they're better hidden. It was a convenient place to gate those features once, but given user input is now not suitable.

I think we need to break the dev tools setting up, and work on making the `view in api` part more discoverable

**Comment by sowmyav27** [comment]
**On 2.7-head commit id: `5d45218`**

- View in API is seen more obvious now. And the checkboxes for all the options there work.
- Verified View in API is enabled.

<img width="716" alt="Screen Shot 2022-10-25 at 3 24 45 PM" src="https://user-images.githubusercontent.com/26032343/197893702-92d5c4b7-d21c-4162-b89b-5be066e6720c.png">
