### ISSUE TITLE
Allow users to hide UI features that they aren't going to use

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6291]
e.g.

- Harvester (can be done via feature flag - need to think about discoverability)
- Continuous Delivery
- ...

**Comment by catherineluse** [comment]
I believe this feature already exists. They just need to deactivate them in the global settings under Feature Flags.
<img width="1434" alt="Screen Shot 2022-07-12 at 3 47 10 PM" src="https://user-images.githubusercontent.com/20599230/178611256-4d6119f6-9a54-4db0-bc6d-c14f92490fcc.png">

**Comment by catherineluse** [comment]
The Continuous Delivery can be disabled via feature flag as well:
<img width="1434" alt="Screen Shot 2022-07-12 at 3 47 10 PM" src="https://user-images.githubusercontent.com/20599230/178611380-53241fa8-f9f6-4780-a6a9-9e9b73d1900f.png">

**Comment by catherineluse** [comment]
Related issues:

- https://github.com/rancher/dashboard/issues/6667
- https://github.com/rancher/dashboard/issues/6103

**Comment by gaktive** [comment]
Things like this could be done via feature flag.
