### ISSUE TITLE
Deployment shows istio image not 'real' container image

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6293]
For a deployment using Istio, there will be multiple containers, some of which are Istio containers.

Currently we pick the first image name to show in the UI and then show them all in a tooltip - often with Istio, this means we show the image for one of the Istio containers rather than the user's 'real' container.

We should not use Istio containers for the image name shown in the list.

**Comment by jbilliau-rcd** [comment]
To add detail to this, here's what it looks like when I change the image on a deployment with Istio enabled:

![image](https://user-images.githubusercontent.com/69006307/178553873-35f0cf6f-eff8-4342-8c57-58fb72bd01fe.png)

I cant tell which pod is using which "application" image from ECR, not unless I hover over every single one. It shows me the sidecar instead, which a user will never care about, at least not as much as their actual application container. If I look at the YAML of the pod, the istio sidecar is listed first, thus why it probably behaves like this. Not sure if there is a way to say "display container[0] but if istio, skip to next container", something along those lines.

**Comment by nickwsuse** [comment]
`Verified on v2.6-head - cb9ccde`

I followed the repro steps in the associated pull request and confirmed that nginx shows as the primary image even after changing the istio container image.
