### ISSUE TITLE
Add ability to customise the docs link

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6294]
Can currently set the link for filing a support issue.

Need to add ability to configure link for documentation.

This will need a new backend setting.

**Comment by nwmac** [comment]
This is covered in https://github.com/rancher/dashboard/issues/6493

**Comment by jameson-mcghee** [comment]
I have verified that in the UI for `v2.7.0-rc8`, the _Docs_ link on the Home page will navigate the user to the [v2.6 Rancher Docs Home Page](https://rancher.com/docs/rancher/v2.6/en) correctly. Therefore I am closing this ticket as Done.

![image.png](https://zube.io/files/rancher/e5272c06b83f92f466837effbc38e5db-image.png)

**Comment by sowmyav27** [comment]
Reopening for additional validations

**Comment by jameson-mcghee** [comment]
I have verified that in the UI for `v2.7.0-rc8`, when adding a new _Custom Link_ on the Global Settings > Home Links page, the  the link text appears correctly on the Home page , and the URL link will navigate the user to the correct URL. Therefore I am closing this ticket as Done.

![image](https://user-images.githubusercontent.com/13294321/199101286-de2b87fe-093c-407f-b416-99d57e9aa9c4.png)
![image](https://user-images.githubusercontent.com/13294321/199101306-9919c9e5-347a-40cb-9ec6-75c8dacda655.png)
