### ISSUE TITLE
Add missing routing segments or query parameters for cluster creation with RKE1/2

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#6299]
**Detailed Description**
Set different routes while accessing to:
- Cluster edit (create mode) for RKE1
- Cluster edit (create mode) for RKE2

**Context**
While creating a cluster, the URL is not updated for the RKE1/2 version inside the editor. 
In this way the navigation from the browser history results broken. It also makes not possible to access to a direct URL for creation. 

Current path, given custom cloud
- RKE1 and RKE2: `/c/_/manager/provisioning.cattle.io.cluster/create?type=custom#basic`

Expected path:
- RKE1: `/c/_/manager/provisioning.cattle.io.cluster/create?type=custom#basic&rke=1`
- RKE2:`/c/_/manager/provisioning.cattle.io.cluster/create?type=custom#basic&rke=2`

This should override existing selection, still requires to fulfil all the checks.

**Comment by gaktive** [comment]
Pushing to Q3 for now though if there's time at the end of Q2, this could come back in.

**Comment by gaktive** [comment]
Internal reference (for PM tracking): SURE-6493
Q4 seems more reasonable at this time.

**Comment by izaac** [comment]
The coverage here looks good. On the first PR however the Burger Menu wasn't included to check the clusters aren't listed after a delete. This is a follow up issue. https://github.com/rancher/dashboard/issues/10324 cc @yonasberhe23
