### ISSUE TITLE
[Backport] Update Azure AD Graph API endpoints and add a migration modal

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/dashboard#6316]
Needed for v2.5.16, part of https://github.com/rancher/rancher/issues/37228.

In the old UI, we need a few changes identical to those introduced in https://github.com/rancher/dashboard/issues/5671.

1. The endpoints to Azure AD that the UI offers starting with v2.5.16 must change as described at the bottom. 

1. If a Rancher instance has a deprecated Azure AD setup, we need to show a notification/banner informing the admins about the upcoming AzureAD Graph API deprecation and a transition to Microsoft Graph API.
The UI should figure out if it must show the banner with a button based on a special annotation's presence and/or value. If the auth.cattle.io/azuread-endpoint-migrated annotation is missing, assume Rancher has deprecated setup and must show the banner and button. If it's present, but its value is not a string "true" ("true" meaning migrated, so not deprecated), then also show the banner and the button. Only if `auth.cattle.io/azuread-endpoint-migrated="true"` should Rancher not show anything.

1. As part of the migration from Azure AD Graph to Microsoft Graph for Azure AD auth provider, we need a button to allow users to initiate the migration from the UI.

1. The button should be shown alongside with a warning that urges admins to update their Azure app's permissions. Specifically, the new required permissions are application-level permissions `Group.Read.All` and `User.Read.All`. We should also say that if users have custom endpoint, then Rancher will not automatically update the endpoints when users migrate to the new auth/authz flow.

#### Deprecated endpoints
Auth Endpoint:       https://login.microsoftonline.com/{tenantID}/oauth2/authorize
Endpoint:            https://login.microsoftonline.com/
Graph Endpoint:      https://graph.windows.net/
Token Endpoint:      https://login.microsoftonline.com/{tenantID}/oauth2/token

#### New endpoints
Auth Endpoint:       https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/authorize
Endpoint:            https://login.microsoftonline.com/
Graph Endpoint:      https://graph.microsoft.com
Token Endpoint:      https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/token

#### Deprecated endpoints
Auth Endpoint:       https://login.chinacloudapi.cn/{tenantID}/oauth2/authorize
Endpoint:            https://login.chinacloudapi.cn/
Graph Endpoint:      https://graph.chinacloudapi.cn/
Token Endpoint:      https://login.chinacloudapi.cn/{tenantID}/oauth2/token

#### New endpoints
Auth Endpoint:       https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/authorize
Endpoint:            https://login.partner.microsoftonline.cn/
Graph Endpoint:      https://microsoftgraph.chinacloudapi.cn
Token Endpoint:      https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/token

**Comment by gaktive** [comment]
This will involve a lot of additional code to be ported over from Vue to Ember, so this will take time but I've been informed this needs to make it for 2.5.16, which may have to extend the deadline.

Proposal: have @mantis-toboggan-md work with @codyrancher for a couple days so she can understand what's required but different in Ember.

**Comment by mantis-toboggan-md** [comment]
This needs to be added to the 2.5 dashboard as well. I poked around 2.5 today and saw that it's possible to set your after-login route to the dashboard, in which case you wont see the warning in Ember.

**Comment by anupama2501** [comment]
Verified on v2.5-head `e792a0d` as part of the issue https://github.com/rancher/rancher/issues/37228#issuecomment-1194982501
