### ISSUE TITLE
Make the namespace filter more discoverable

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6318]
Sometimes users get confused as to why they can't see resources in Cluster Explorer that they expected to see.

It could be because the namespace filter is not visually close to the Cluster Explorer side nav, which has everything else you need for cluster explorer:
<img width="1432" alt="Screen Shot 2022-07-11 at 3 38 53 PM" src="https://user-images.githubusercontent.com/20599230/178370712-15016e3b-bdd4-4171-b5ae-251aa1260312.png">

We could consider moving the namespace filter to the top of the side nav with the aim of making it more discoverable.

**Comment by gaktive** [comment]
Related epic closed and we've modified this behaviour in other work so closing as done. Feedback on subsequent improvements welcome but please confirm on a more recent version on how the picker looks.
