### ISSUE TITLE
[UI] - Removing Path in Ingress resets the page

### ISSUE THREAD

**Issue by sebastienroul** [rancher/dashboard#6319]
Rancher v2.6.6

Step to reproduce : 
  1. Create an Ingress
  2. Click on "Add path"
  3. Input a path "/foo"
  4. Click on "Add path"
  5. Input a path "/bar"
  6. Click on "Add path"
  7. Input a path "/loo"
  8. Click on "Remove" on the "/bar" path

=> Page reload

Expected : Not to reload, just remove the Path

Please note it also happend with existing Ingress - the pattern to reproduce is to remove a "Non-last Path"

**Comment by gaktive** [comment]
@jordojordo to repro and then sync with @Sean-McQ if it's fixed already in a PR

**Comment by sowmyav27** [comment]
Reopening for QA Validations

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###

Tested this issue with the following steps:
  1. Create an Ingress
  2. Click on "Add path"
  3. Input a path "/foo"
  4. Click on "Add path"
  5. Input a path "/bar"
  6. Click on "Add path"
  7. Input a path "/loo"
  8. Click on "Remove" on the "/bar" path

**Result** - Pass
When creating an ingress, removing a path no longer reloads the page and removes the path
