### ISSUE TITLE
Service - Detail Page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#632]
Based on #583, we need the detail page of this resource. 

DetailTop should include, but the rest of the page should look like edit page

Item | 
---|
Type |
Created |

**Comment by deniseschannon** [comment]
@westlywright After reviewing service detail page, it would be nice to have the selector tab be able to list out the pods that match the selector. 

Current tab:

<img width="1123" alt="Screen Shot 2020-05-21 at 2 43 45 PM" src="https://user-images.githubusercontent.com/11410997/82609679-d5468600-9b71-11ea-9ca9-f18aaeaf8b9a.png">

Addition to tab:

`Pods` Section - H3 Heading

Table with these columns

Header | Item Info
---|---
Status | State of Matching Pod
Pod | Name of pod with link to pod detail page
Workload Type | Name of workload with link to workload detail page
Image | Image Name(s) of Containers inside pod 
Node | Node Name of where the pod is running

**Comment by westlywright** [comment]
@deniseschannon we should hold off on adding the pod counts for the same reasons we discussed with the create/edit pages. I opened the ticket for a new API mechanism to fetch related resources more efficiently [here](https://github.com/rancher/dashboard/issues/714).

**Comment by deniseschannon** [comment]
## Session Affinity Tab
- [ ] Instead of `None`, can we have text that says `There is no session affinity configured.` None seems too short and not informative and we're trying to move to a style of instead of showing a bunch of empty headers to consolidate what could be done into a `There is no BLAH configured.`

**Comment by izaac** [comment]
Issues found so far:
#800
#804

**Comment by izaac** [comment]
Rancher version `master-head (07/09/2020)` commit _8a032e73b_
dashboard-index -> `latest`

Details page checked for the following service types:

- L4 Loadbalancer (Using an AWS service provider)
- Headless (Selector, Alias)
- Workload
- External IP
- Cluster IP
- External Name (Hostname in Ember UI)

Steps followed for each service type:

1. Keep the Browser Developer Tools open in the network tab for analyzing the `v1` API responses.
2. Create the service type
3. Navigate to the Service List
4. Click in the new created service.
5. Save the API response in an Editor
6. Validate each data field displayed by the Service Details Page comparing with the v1 data returned by the API.
7. Navigate through the different Tabs in the service details
  - Selectors (where applicable)
  - Listener IPs
  - Session Affinity (where applicable)
  - Labels
  - Annotations


Navigation issue found:
https://github.com/rancher/dashboard/issues/820
