### ISSUE TITLE
Design UX for creating workloads with projects selected in top nav

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6322]
This issue is a follow-up to https://github.com/rancher/dashboard/issues/6094

In the above linked issue, it has been requested to narrow down the list of namespaces that we offer as options to users who are creating a workload based on the namespace/project filter in the top nav.

As of v2.6.7, the UI will allow users to create a new namespace at the same time as they create a workload. However, the workload creation form does not expose the option to create the namespace in a project. We should figure out:

- In the workload creation form, should we allow users to select a project for a new namespace?
- If you have a single project selected in the top nav, and you create a new namespace, should it automatically be created in the selected project?
- How would we make it visually clear which project the new namespace would be created in?
- In the dropdown menu for selecting a namespace, should the namespaces be grouped by project?

This screenshot shows the current UX for creating a workload in a new namespace. If a project is selected in the top nav, should we prompt the user to select a project here as well?
<img width="1376" alt="Screen Shot 2022-08-11 at 4 47 32 PM" src="https://user-images.githubusercontent.com/20599230/184260798-523ba541-12f9-4405-adbf-bab54eacff3c.png">

**Comment by kwwii** [comment]
Maybe we can make them visually different in the dropdown (but still selectable?)

**Comment by kwwii** [comment]
We should address this when working on this: https://github.com/rancher/dashboard/issues/6322

**Comment by catherineluse** [comment]
In this issue, https://github.com/rancher/dashboard/issues/6413, we plan to group namespaces by project in this dropdown menu.

After that's done, I would say the next step to address this issue would be to filter the options in this menu by whatever is selected in the top nav.

**Comment by catherineluse** [comment]
@kwwii did you mean to link to this issue instead? https://github.com/rancher/dashboard/issues/6094

**Comment by kwwii** [comment]
@catherineluse Yes, good catch, thanks!

**Comment by kwwii** [comment]
We should create the namespace in the project context shown in the top project/namespace filter. If the filter includes more than one project or no project the namespace should be created without being included in a project.

**Comment by kwwii** [comment]
I think we should leave this as-is for now. We should revisit this when looking into https://github.com/rancher/dashboard/issues/6321
