### ISSUE TITLE
Improve UX for "View YAML" in Cluster Management

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6323]
I think we should consider removing "View YAML" or "Edit YAML" for some clusters in Cluster Management because it's confusing and not useful.

For some cluster types - for example, RKE1 clusters and the local Rancher server cluster - YAML view doesn't yield anything useful. For these clusters, the YAML you are looking at is for the management cluster resource, which is the Kubernetes resource named `Cluster` in the `management.cattle.io` API group.

The management cluster resource is an implementation detail - it's just the thing that Rancher uses to keep track of all cluster managed by Rancher, of all types, even if they are imported/registered clusters and Rancher doesn't have full control over them. To my knowledge, the only people interested in the management cluster YAML are Rancher employees.

We expose the YAML through the context menu in the list of clusters in Cluster Management:
<img width="1423" alt="Screen Shot 2022-07-11 at 4 12 47 PM" src="https://user-images.githubusercontent.com/20599230/178379464-cc55f5e4-9b87-4df9-a670-4c2ac7f528c3.png">

Here is the management cluster YAML for an RKE1 cluster, which is definitely not what users would want, as it doesn't let them configure RKE1 options:

<img width="1021" alt="Screen Shot 2022-07-11 at 5 05 27 PM" src="https://user-images.githubusercontent.com/20599230/178379356-279cbb56-cd56-419b-8d8e-e44116cb5d35.png">

Here's the YAML editor for the Rancher server cluster, which is also a management cluster resource that is only used by Rancher itself:

<img width="1416" alt="Screen Shot 2022-07-11 at 4 13 56 PM" src="https://user-images.githubusercontent.com/20599230/178379842-5d47f724-4783-4450-877f-38ef70424578.png">

However, for RKE2 clusters, the YAML view exposes the provisioning cluster resource, which is useful because the user can configure the cluster under `spec.rkeConfig`:
<img width="1418" alt="Screen Shot 2022-07-11 at 4 13 28 PM" src="https://user-images.githubusercontent.com/20599230/178380021-3c3e0ea4-9671-4ed9-9c09-0762e4274f03.png">
Since the ability to edit the provisioning cluster resource is useful, we shouldn't remove it.

To me, the most counterintuitive thing is that for RKE1 clusters, we DO allow users to edit the cluster as YAML, but it's not exposed by the context menu in cluster management. You have to go to Edit Config in the context menu, then in the form that appears, there is an **Edit as YAML** button:
<img width="1018" alt="Screen Shot 2022-07-11 at 5 21 02 PM" src="https://user-images.githubusercontent.com/20599230/178380284-d4d14be9-7633-4b7e-a16e-e658ca776687.png">

If you click that, then you can edit the RKE1 cluster under `rancher_kubernetes_engine_config`:
<img width="859" alt="Screen Shot 2022-07-11 at 5 21 39 PM" src="https://user-images.githubusercontent.com/20599230/178380395-d5980cc5-cc6e-433b-9f43-7356bcc3e315.png">

I think that for RKE1 clusters, we should expose that YAML editor that contains `rancher_kubernetes_engine_config` instead of exposing the management cluster resource.

And for other cluster types where we expose the management cluster YAML, I think we should just remove it from the context menu, because to my knowledge there is no reason why a user would need it.

Rancher engineers would still be able to get the management cluster resource by going to cluster explorer for the local Rancher server and searching for `Mgmt Clusters`.

**Comment by catherineluse** [comment]
I have added the `research-needed` label because we need to research whether these changes would disrupt anyone's workflow, and because we need to know how existing customers would perceive the change, per Kenneth's comment.

**Comment by kwwii** [comment]
For RKE1 clusters we should expose the "Edit as YAML" function from the rancher_kubernetes_engine_config in cluster options as described above instead of the current Edit as YAML functionality.
