### ISSUE TITLE
Documents hierarchy

### ISSUE THREAD

**Issue by bisht-richa** [rancher/dashboard#6334]
Currently, we have all document files in a single folder. Need to create an effective folder structure and arrange document files in a meaningful way.

All the documents files are in the below folder:

dashbaord/docusaurus/docs

**Comment by kwwii** [comment]
Hwre is what I came up with for a start:
General
Accessibility
Styles
RBAC
Kubernetes
Testing

**Comment by richard-cox** [comment]
@bisht-richa I don't think Rancher QA will test docusaurus, so make sure to add the `status/dev-validate` label to these types of issues
