### ISSUE TITLE
Dashboard UX design

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#6337]
Create a viable UX design for the dashboard of Elemental

**Comment by kwwii** [comment]
![Dashboard.png](https://zube.io/files/rancher/28ae2cb516d7b41ae6d59a5f66018e33-dashboard.png)![Dashboard – 1.png](https://zube.io/files/rancher/b005b0668cc8a920daf0e1aec9b144ef-dashboard-1.png)

**Comment by kwwii** [comment]
![Dashboard.png](https://zube.io/files/rancher/64d2edd78c47d75f8593627313fd1c82-dashboard.png)

**Comment by kwwii** [comment]
This shows a mockup with various states https://xd.adobe.com/view/0f0a9d4e-e04a-4462-8d56-441e50ad4d42-5a59/

**Comment by aalves08** [comment]
@kwwii I think we can close this one, right?
