### ISSUE TITLE
Design Issue - Helper text in tabs

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#634]
As we move stuff into tabs, we are starting to add more and more helper text to explain the fields in the tabs. 

Can we have a font/color to be used in these tabs as helper text?

Currently, we have it in Namespace edit/detail like this:

<img width="822" alt="Screen Shot 2020-05-09 at 9 47 27 AM" src="https://user-images.githubusercontent.com/11410997/81480229-22734100-91dd-11ea-9c49-b3f93f6ab107.png">

And in ingress it's like a warning/helper text and looks like this:

![detail-default](https://user-images.githubusercontent.com/55104481/81446059-fa2d0900-912e-11ea-8a1f-a31f24e5f9c6.PNG)

**Comment by lvuch** [comment]
<img width="1203" alt="Screen Shot 2020-05-19 at 2 04 15 PM" src="https://user-images.githubusercontent.com/3013118/82378232-a85f6b00-99d9-11ea-81f4-6d4690e86370.png">

**Comment by deniseschannon** [comment]
@westlywright  Could you review the service pages to change the helper text to this styling?

**Comment by deniseschannon** [comment]
Helper texts in Service pages are updated to the banner style.
