### ISSUE TITLE
[BUG]v2.6.5-rc10版本，rancher上无法查看pod的log

### ISSUE THREAD

**Issue by lijiajimi** [rancher/dashboard#6342]
![image](https://user-images.githubusercontent.com/12810328/171132157-afbefb47-514b-4f2e-ae95-f36730722f19.png)
v2.6.5-rc10版本，不知道做了什么操作，无法查看pod的log了，点击有报错，bug是跟账号走的，不是机器的问题，不同机器登录同一个账号，也会发生这个bug。

**Comment by richard-cox** [comment]
I'm going on the assumption that this is the same bug as https://github.com/rancher/dashboard/issues/5984, therefore closing as a duplicate.

If this is not the case, please comment (in English) and we can look in to it.
