### ISSUE TITLE
[UI] Rancher Changes names in the About Section when providing a private label

### ISSUE THREAD

**Issue by josegomezr** [rancher/dashboard#6345]
**Rancher Server Setup**
- Rancher version: v2.6.6
- Installation option (Docker install/Helm Chart): Helm v2.16.8-rancher1
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.23.7+k3s1

- Cluster Type (Local/Downstream): Downstream
   - Custom: K3S + Extra nodes as workers

**User Information**
- What is the role of the user logged in? Admin (first user)
   
**Describe the bug**
When changing the Branding under "Global Settings" and assigning a Private Level, the value of Rancher in the About Section changes to whatever is written in Private Level.

**To Reproduce**
1. Install Rancher (version specified up)
2. Go to Global Settings > Branding
3. Write `lorem ipsum` in Private Label
4. Save settings
5. Click on the sidebar menu > click on the version.

**Result**
The rancher component is now called `lorem ipsum`

**Expected Result**
Rancher component should keep the name.

**Screenshots**

Before:
![image](https://user-images.githubusercontent.com/5963207/177875739-2d5c4e81-4fa6-40e3-aa8c-8d2ea0965023.png)

After:
![image](https://user-images.githubusercontent.com/5963207/177875684-e1bcdaac-54b9-4466-8351-dbf9a7a6fdf1.png)

**Comment by nwmac** [comment]
About page should always say Rancher

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment




| Component                        | Version / Type                          |
| -------------------------------- | --------------------------------------- |
| Rancher version                  | 2.7.0                                   |
| Installation option              | Helm (high availability)                |
| If Helm Chart k8s cluster        | v1.24.7+k3s1                            |
| Cert Details                     | Let's Encrypt / `traefik`               |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2    |
| Helm version                     | v2.16.8-rancher2                        |
| Downstream cluster type          | not applicable                          |
| Downstream K8s version           | not applicable                          |
| Authentication providers enabled | local                                   |
| Logged in user role              | Administrator                           |
| Browser type                     | Google Chrome                           |
| Browser version                  | 108.0.5359.98 (Official Build) (x86_64) |

<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

>K3s install command for node one. Replace values in <>

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=SECRET --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```

>K3s install command for node two. Replace values in <>. Main difference here is the --token

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=<TOKEN_FROM_NODE_ONE> --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```


</details>


## Reproduction steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click the `hamburger menu` >>> `Global Settings` >>> `Branding`
3. Change the `Private Label` field to `test123` >>> click `Apply`
4. Click the `hamburger menu` >>> the rancher version at the bottom `v2.7.0`
5. Observe the `Versions` table 
   1. What was once `Rancher` with version `v2.7.0`
   2. Is now `test123` with version `v2.7.0`


## Additional Info

## RESULTS

#### ✅ Expected
Expected the Rancher component in the about page not to change

#### ❌ Actual
The name of the Rancher component changed on the about page when it shouldn't have

<hr>

## Validation Environment



| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7-216bb7f5fc36e93ef5df2a47aaf10ce592e697f2-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/216bb7f5fc36e93ef5df2a47aaf10ce592e697f2 |
| Installation option              | Helm (high availability)                                                           |
| If Helm Chart k8s cluster        | v1.24.7+k3s1                                                                       |
| Cert Details                     | Let's Encrypt / `traefik`                                                          |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2                                               |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | Administrator                                                                      |
| Browser type                     | Google Chrome                                                                      |
| Browser version                  | 108.0.5359.98 (Official Build) (x86_64)                                            |


<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

>K3s install command for node one. Replace values in <>

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=SECRET --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```

>K3s install command for node two. Replace values in <>. Main difference here is the --token

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=<TOKEN_FROM_NODE_ONE> --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```


</details>

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click the `hamburger menu` >>> `Global Settings` >>> `Branding`
3. Change the `Private Label` field to `test123` >>> click `Apply`
4. Click the `hamburger menu` >>> the rancher version at the bottom `v2.7.0`
5. Observe the `Versions` table 
   1. What was once `Rancher` with version `v2.7-216bb7f5fc36e93ef5df2a47aaf10ce592e697f2-head`
   2. Is still  `Rancher` with version `v2.7-216bb7f5fc36e93ef5df2a47aaf10ce592e697f2-head`
6. Verified the name did update in the Google chrome tab to `test123`

## Additional Info

## RESULTS

#### ✅ Expected
Expected the Rancher component in the about page not to change

#### ✅ Actual
The Rancher component in the about page did not change
