### ISSUE TITLE
[UI] - Filter not persisted

### ISSUE THREAD

**Issue by sebastienroul** [rancher/dashboard#6347]
Rancher v2.6.6

Step to reproduce : 
 0. On the deployments listing (for example)
 1. Input a filter
![image](https://user-images.githubusercontent.com/2582255/177776262-2fc5eeca-2f1c-4d33-9b0e-b97d6cf49a28.png)
 2. Open/Edit a deployment
 3. Back/Save

The filter is not there anymore, so user should retype it again.

PS : Red color is due to our Rancher setup : no pb about this :o)

**Comment by richard-cox** [comment]
We would need to persist per table filter settings in order to support this. Would need to decide if these persist for the session (info can be stored in vuex, or over different sessions as well (info can be stored in user settings). We already do something similar for the latter in terms of persisting the project/namespace filter value

**Comment by sebastienroul** [comment]
@richard-cox  IMHO you should persist it only for session.

Also IMHO the persistence of the other filter (the namespace filter) should also be there (session level) or maximum to the localstorage level - but  at the user settings level, like it is now, it's too high, cause we need to create on user per person otherwise it's a battle filter :o)

**Comment by catherineluse** [comment]
I think this bug could be fixed by https://github.com/rancher/dashboard/pull/7368 because if the filter is in the URL, it should still be active if the user clicks Back.

**Comment by richard-cox** [comment]
@sebastienroul, as Catherine spotted, we have a [change](https://github.com/rancher/dashboard/issues/6848) targetted for 2.7.1 which will bring back the table's filter as a query param. This should resolve the issue on back, refresh (and for bookmarked pages). Does that solve your original issue?

**Comment by richard-cox** [comment]
Superseded by https://github.com/rancher/dashboard/issues/10704
