### ISSUE TITLE
Closing as duplicate of https://github.com/rancher/dashboard/issues/5979 (fixed in 2.6.6).

### ISSUE THREAD

**Issue by linuxsch** [rancher/dashboard#6359]
Closing as duplicate of https://github.com/rancher/dashboard/issues/5979 (fixed in 2.6.6).

_Originally posted by @richard-cox in https://github.com/rancher/dashboard/issues/6193#issuecomment-1158657180_

**Comment by linuxsch** [comment]
in version 2.6.6, Date and time format is displayed wrong in the preferences after editing have not fixed.

**Comment by nwmac** [comment]
@linuxsch I don't understand this issue - closing - please re-open with a better title.

**Comment by richard-cox** [comment]
Frustratingly the `2.6.6` release was renamed to `2.6.7`. The fix is therefore in `2.6.7`.

As mentioned by Neil, please ensure to fill in the issue template before submitting PRs.
