### ISSUE TITLE
Uncaught (in promise) Error: Use "val" instead of "value" for setting preference when creating secret/configmap

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#636]
Version: master-head (84d937acf)

**Steps:**

1. Create a secret or config map using the Dashboard UI. Secret/config map object gets created.   

**Result**

In the UI console, below error is observed:
![Screen Shot 2020-05-11 at 2 44 35 PM](https://user-images.githubusercontent.com/18536626/81615139-f5b65980-9395-11ea-9b93-a7cc496cc93c.png)

**Comment by vincent99** [comment]
Addressed in #638

**Comment by soumyalj** [comment]
Tested with master-head build (dd102af17)
1. Create a config map of secret using the dashboard UI. Secret and Configmaps get created. 
The errors mentioned above are not see in the UI console. Console reports  info as below:
![Screen Shot 2020-05-12 at 11 12 15 AM](https://user-images.githubusercontent.com/18536626/81729870-8f871080-9441-11ea-8e50-f1477138ee8b.png)
