### ISSUE TITLE
Fleet: Error loading Bundle details in fleet

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#6361]
**Setup**
- Rancher version: latest
- Browser type & version: any

**Describe the bug**
Going to Continuous Delivery -> Advanced -> Bundles, then clicking on any given bundle on the list to see it's details it doesn't load the bundle information (404)

**To Reproduce**
Go to Continuous Delivery -> Advanced -> Bundles, then click on any given bundle to see it's details

**Result**
Doesn't load the bundle information (404)

**Expected Result**
Should load and display the bundle information

**Screenshots**
<img width="749" alt="Screenshot 2022-07-13 at 16 59 49" src="https://user-images.githubusercontent.com/97888974/178782724-d2e0c6f4-66c4-4951-901b-cee98df77163.png">

**Additional context**
The 404 seems to be caused by the URL for request to fetch the gitRepo not having a proper ID param (displays as `undefined`)

**Comment by aalves08** [comment]
FYI @sowmyav27 , @nwmac , @richard-cox , @gaktive

**Comment by izaac** [comment]
Rancher version: `v2.6.7-rc5`
Rancher version: `v2.6-head` `6629e3e` (08/01/2022)

I cannot reproduce on those Rancher versions. I am able to open the bundle details page for bundles in the local cluster and downstreams.
