### ISSUE TITLE
Continuous Delivery --> Cluster details page does not load

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6362]
**On 2.6head commit id: `2c21373`**

- Deploy RKE1 and RKE2 clusters
- Navigate to Continuous Delivery --> Clusters --> click on one of the clusters
- Page is stuck in loading
- Error in console:

```
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'resourceCounts')
    at f.<anonymous> (rke2.vue?8fa9:1:352)
    at t._render (vue.runtime.esm.js:3569:22)
    at f.r (vue.runtime.esm.js:4081:21)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.run (vue.runtime.esm.js:4570:22)
    at Sn (vue.runtime.esm.js:4326:13)
    at Array.<anonymous> (vue.runtime.esm.js:1989:12)
    at ce (vue.runtime.esm.js:1915:12)
```

**Note:**
- Fleet is in an error state (which could affect the Continuous Delivery page). Related backend bug: [this](https://github.com/rancher/rancher/issues/38248)

**Comment by Shavindra** [comment]
Seemed to be working with rancher 2.6-head commit id `434396f`

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/1387263/180404792-7bc80d76-41e7-4051-88d0-b266dc56b4c1.png">

**Comment by sowmyav27** [comment]
**on 2.6head commit id: `78017e6`**

No issues seen. Page loads
<img width="1503" alt="Screen Shot 2022-07-27 at 9 07 56 PM" src="https://user-images.githubusercontent.com/26032343/181418216-6598fd7b-63b9-41ed-9edb-005008170575.png">

This could be because fleet is in an Active state. Closing this issue for now
