### ISSUE TITLE
[Bug] Remove node/pod scheduling on deployment edit page failed

### ISSUE THREAD

**Issue by DaiYuzeng** [rancher/dashboard#6366]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

This issue can reproduce on the master branch of rancher/dashboard.

**To Reproduce**

1. Go to Create Deployment Page.
2. Switch to Pod Scheduling tab.
3. Add two node selectors.
4. Remove one of them.
5. Save.

**Result**

There are two node selectors in this deployment actually.

**Expected Result**

Node/Pod scheduling should be removed successfully.

**Screenshots**
![Kapture 2022-07-14 at 12 50 52](https://user-images.githubusercontent.com/15041915/178917977-3ccb0ae7-16ea-4127-a21a-40306409199c.gif)

**Additional context**

**Detailed Description**

**Context**

**Comment by mantis-toboggan-md** [comment]
The fix for this is in a combined Harvester PR: https://github.com/rancher/dashboard/pull/6398

**Comment by markusewalker** [comment]
Verified that this is addressed in `v2.6-head` https://github.com/rancher/rancher/commit/8ffaf566fcc764ed9665eec1ac998d8bd7b7e3f1.

**ENVIRONMENT DETAILS**
- Rancher Install: Docker
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/8ffaf566fcc764ed9665eec1ac998d8bd7b7e3f1
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Created a standard user and login to Rancher as that user.
3. Provisioned a downstream RKE1 cluster and verify that it comes up as `Active`.
4. Navigated to Cluster Explorer > cluster > Workloads > Deployments. Create a Deployment.
5. Switched to the `Pod > Pod Scheduling` tab and added multiple node selectors:
![image](https://user-images.githubusercontent.com/52591819/181124047-6e5a43b7-d6f2-496e-be73-a30ba26c8752.png) 
6. Once done, removed one of the node selectors:
![image](https://user-images.githubusercontent.com/52591819/181124034-85725555-a7ac-4c1b-aa7f-67330e57885e.png) 
7. Created the deployment. Verified that the expected amount of node selectors are present and that the deleted node selector DOES NOT appear:
![image](https://user-images.githubusercontent.com/52591819/181124013-7da7dbf3-0246-4d88-983c-f1a7a4864586.png)
![image](https://user-images.githubusercontent.com/52591819/181124019-1ce4806c-4a09-4cc0-a92b-9446f2e7b182.png)
