### ISSUE TITLE
Node IPs displayed in cluster Management page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6368]
**On 2.6head commit id: `2c21373`**

- Deploy a cluster
- Node Ips seen in the cluster Management Page

<img width="1141" alt="Screen Shot 2022-07-14 at 8 18 16 AM" src="https://user-images.githubusercontent.com/26032343/179017858-e8c2e17d-1953-4a86-94bc-a6a4edece285.png">

**Expected:**
Can we remove this column in this page? This is info is already there in Cluster details page

**Comment by richard-cox** [comment]
This was introduced intentionally via https://github.com/rancher/dashboard/issues/2957. @kwwii unless you have any specific UX objections to how this is done I vote we close

**Comment by kwwii** [comment]
@richard-cox Agreed, we can close this.
