### ISSUE TITLE
Workloads - Create

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#637]
# Workload Types

Within each type, you have the ability to specify a pod template, which has the same components for all workload types. Either metadata or the pod spec itself. The pod template is located in different locations based on the workload type. In the tabs description, it will refer to a field in the pod template spec as `<podTemplate>`, which can be nested differently between each workload type. Refer to this table to find out where the pod template spec is nested. 

Any other fields will be called out specifically between the types. 

Name | Pod Template Spec K8s yaml location
---|---
Deployment (Default) | `spec.template`
Daemon Set | `spec.template`
Stateful Set | `spec.template`
Job | `spec.template`
Cron Job | `spec.jobTemplate.spec.template`

- [ ] Remove `Replication Controller`, `ReplicaSet` from the list of types

We will be creating a wizard style process to step through the options. 

# Wizard Steps

Steps |
---|
Select Workload Type | 
Define Container | 
Storage | 
Advanced|

**Comment by deniseschannon** [comment]
# Main Section

## NameNSDescription Component

Header/Label Name | k8s yaml | Component
---|---|---
Namespace | `metadata.namespace` | NameNSDescription
Name | `metadata.name` | NameNSDescription
Description | `metadata.annotations.cattle.io/description` | NameNSDescription

## Section based on Workload Type

### Deployment Type

Header/Label Name | k8s yaml | Input Field/Component  |  Default/Example Text | 
---|---|---|---|
Replicas | `spec.replicas` | Integer Input Textbox |  Default Text: `1` | 

### DaemonSet Type

Nothing in the main content

### StatefulSet Type

Header/Label Name  | k8s yaml | Input Field/Component  |  Default/Example Text | 
---|---|---|---|
Replicas | `spec.replicas` | Integer Input Textbox |  Default Text: `1` | 
Pod Management Policy | `spec.podManagementPolicy` | Radio Button Options: <br> *Create pods in order and wait for the pod to be ready before continuing (`OrderedReady`) <br> * Create pods without waiting. Upon deletion, remove all pods at once (`Parallel`) | Default: `OrderedReady` | 
Service Name (Required) | `spec.serviceName` | Dropdown of available headless services in the selected namespace.  See below for how to find headless services | Default: Nothing selected | 

How to find headless services in k8s:
``` 
kind: Service
spec:
  type: ClusterIP 
  clusterIP: "None"
```

### ReplicaSet Type

Header/Label Name  | k8s yaml | Input Field/Component  |  Default/Example Text | 
---|---|---|---|
Replicas | `spec.replicas` | Integer Input Textbox |  Default Text: `1` | 

### Job Type

Header/Label Name | k8s yaml | Input Field/Component  |  Default/Example Text | Tooltip Text | Unit
---|---|---|---|---|---
Completions | `spec.jobTemplate.spec.completions` | Integer Input Textbox |  None |`The number of successfully finished pods the job should be run with.` | `Times`
Parallelism | `spec.jobTemplatespec. parallelism` | Integer Input Textbox | None |`The maximum number of pods the job should run at any given time.` |  `Pods`
Back off Limit | `spec.jobTemplatespec.backoffLimit` | Integer Input Textbox | Example Text: `e.g. 6` |`The number of retries before marking this job failed.` |  `Times`
Active Deadline | `spec.jobTemplatespec.activeDeadlineSeconds` |Integer Input Textbox | Example Text `e.g. 10` |  `The duration that the job may be active before the system tries to terminate it.` | `Seconds`

### CronJob Type
Header/Label Name | k8s yaml | Input Field/Component  | Default/Example Text | Helper Text | Unit
---|---|---|---|---|---
Schedule | `spec.schedule` | String Input Textbox | Example Text: `0 * * * *` | 
Concurrency | `spec.concurrencyPolicy` | Radiobutton: <br> * Allow CronJobs to run concurrently (`Allow`) <br> * Skip next run if current run hasn't finished (`Forbid`) <br> * Replace run if current run hasn't finished (`Replace`) | Default: `Allow` 
Successful Jobs History Limit | `spec.successfulJobsHistoryLimit` | Integer Input Textbox | Default Text: `3` | `The number of successful finished jobs to retain.` | `Jobs`
Failed Jobs History Limit | `spec.failedJobsHistoryLimit` | Integer Input Textbox | Default Text: `1` | `The number of failed finished jobs to retain.` | `Jobs`
Starting Deadline Seconds | `spec.startingDeadlineSeconds` | Integer Input Textbox | | `The deadline in seconds for starting the job if it misses scheduled time` | `Seconds`
Suspend Executions | `spec.suspend` | Radiobutton Options <br> * No <br> * Yes | Default: `No` |`Suspend subsequent executions`
Completions | `spec.jobTemplate.spec.completions` | Integer Input Textbox |  None |`The number of successfully finished pods the job should be run with.` | `Times`
Parallelism | `spec.jobTemplatespec. parallelism` | Integer Input Textbox | None |`The maximum number of pods the job should run at any given time.` |  `Pods`
Back off Limit | `spec.jobTemplatespec.backoffLimit` | Integer Input Textbox | Example Text: `e.g. 6` |`The number of retries before marking this job failed.` |  `Times`
Active Deadline | `spec.jobTemplatespec.activeDeadlineSeconds` |Integer Input Textbox | Example Text `e.g. 10` |  `The duration that the job may be active before the system tries to terminate it.` | `Seconds`

**Comment by deniseschannon** [comment]
## Containers Tab
Everything listed here is nested under `<podTemplate>.spec.`.

Always have at least 1 container component, cannot deploy without 1 container.

Header/Label Name | k8s yaml | Input Info/Component
---|---|---
Containers | `containers` | Containers component

**Comment by deniseschannon** [comment]
## Networking Tab
Everything listed here is nested under `<podTemplate>.spec.`.

Header/Label Name | k8s yaml | Input Field/Component | Example Input/Default
---|---|---|---
Network Mode | `hostNetwork` | Dropdown with 2 Options: <br> * Normal (`false`) <br>  * Host Network (`true`) | Default Value: `Normal`
DNS Policy | `dnsPolicy` |  Dropdown with 4 Options:  <br> * Cluster First (`ClusterFirst`) <br> * Cluster First With Host Network (`ClusterFirstWithHostNet`) <br>* Default (`Default`)  <br> * None (`None`) | Default Value: `ClusterFirst` Note: Even though there is a `Default`, it is not the default value. 
Hostname |  `hostname` | String Input Textbox  | Example Text: `e.g. web`
Subdomain  | `subdomain` | String Input Textbox|  Example Text: `e.g. foo`
DNS Nameservers | `dnsConfig.nameservers` | Ability to add/remove multiple string input textboxes  | Example Text: `e.g. 192.168.2.1`
DNS Search Domains | `dnsConfig.searches` | Ability to add/remove multiple string input textboxes | Example Text: `e.g. example.com`
DNS Resolver Options  | `dnsConfig.options.name` and `dns.Config.options.value` | KeyValue Component with `Name` and `Value` as headers | Example Text for Name: `e.g. ndots`, Example Text for Value `e.g. 5`
Host Aliases | `hostAlisases` | KeyValue Component with `IP Address` and `Hostname` as headers | Example Text for IP Address: `e.g. 192.168.0.1`, Example Text for Hostname `e.g. database`

- [ ] `DNS Policy` needs additional policy `ClusterFirstWithHostNet`
- [ ] Add missing `Subdomain`
- [ ] Add DNS Resolver Options

**Current Fields on Networking tab**
<img width="521" alt="Screen Shot 2020-05-06 at 8 30 29 PM" src="https://user-images.githubusercontent.com/11410997/81251585-77923580-8fd8-11ea-88b0-a64f8e795344.png">

**Comment by deniseschannon** [comment]
## Scheduling Tab
Everything listed here is nested under `<podTemplate>.spec.`.

### `Node Scheduling` Section
Note: We are not allowing ability to adjust the `weight` of a node selector in the node scheduling rules with current requirements. 

- [ ] Header/Title with `Node Scheduling`
- [ ] Radiobutton for different types of node scheduling
- [ ] Make a new component for `MatchExpressions` which compose of the following fields which are used in scheduling (node and pod). Ability to add/remove these `rules`.

**MatchExpressions** component
Header/Label Name | k8s yaml | Input Field/Component | Example Input/Default
---|---|---|---
Key | `key` | String input textbox | 
Operator | `operator` | Dropdown Options for Node Scheduling: <br> * = (`In`) <br> * ≠ (`NotIn`) <br> *  exists (`Exists`) <br> * does not exist (`DoesNotExist`) <br> * > (`Gt`) <br> * < (`Lt`) <br><br> Dropdown Options for Pod Scheduling: <br> * = (`In`) <br> * ≠ (`NotIn`) <br> * exists (`Exists`) <br> * does not exist (`DoesNotExist`) | Default Value: `=`
Value | `values` | String input textbox | When `exists` or `does not exist` is selected as an operator, the textbox is hidden and shown as a `n/a` label. 

**Radiobutton Options** 
- Option 1 (Default): `Run pods on specific node(s)`
- Option 2: `Run pods on node(s) matching these scheduling rules`

Based on each option, there are different fields shown:

Radiobutton Option | HHeader/Label Name | k8s yaml | Input Field/Component | Example Input/Default
---|---|---|---|---
Option 1 | Node Name | `nodeName` | Dropdown of available `worker` nodes | Default: No node selected
Option 1 | Node(s) with these Labels | `nodeSelector` | KeyValue Component | Example Text for Key: `e.g. foo` and Example Text for Value `e.g. bar`
Option 3 | Node Scheduling Rules | `affinity.nodeAffinity` | See **Node Schedule Rules** section

**Node Scheduling Preference Types**
There are two preference types:
- `Require any of`
- `Prefer any of`

Each preference type has the ability to add node selectors, which can hold multiple rules. When navigating to the tab, it only shows ability to `Add Node Selectors`. There is no requirement to have any node selector so there doesn't need to have it expanded to automatically input.

> **Note**: Currently, `Prefer Any of` is implemented correctly and `Require any of` should match that style. 

The preference types have the same content within each section, but are in the different places in the yaml. 

Preference Type | k8s yaml 
---|---
 _Require any of_ | `affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution`
_Prefer Any of_ | `affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution`

For each preference type, ability to create node selectors which can hold multiple node scheduling rules. Each node selector is 1 object in `nodeSelectorTerms`, which can hold multiple scheduling rules `matchExpressions`. 

<img width="533" alt="Screen Shot 2020-05-09 at 10 58 12 AM" src="https://user-images.githubusercontent.com/11410997/81481325-1474ee80-91e4-11ea-9e34-0b06ced739bd.png">

### `Pod Scheduling` Section
Note: We are not allowing ability to adjust the `weight` of a pod selector in the pod scheduling rules with current requirements. 

- [ ] Header/Title with `Pod Scheduling`

**Pod Scheduling Types**
There are two pod scheduling types:

Header (under `Pod Scheduling`) | k8s Yaml
---|---
Run pods on node(s) that have these pods | `affinity.podAffinity`
Run pods on node(s) that do not have these pods | `affinity.podAntiAffinity`

Within each pod scheduling type, the content is exactly the same. 

**Pod Scheduling Preference Types**
These preference types are under the pod affinity type (either `affinity.podAffinity` or `affinity.podAntiAffinity`). 

There are two rule preference types
- `Require any of` (Hard Affinity)
- `Prefer any of` (Soft Affinity)

Preference Type | k8s yaml 
---|---
 _Require any of_ | `requiredDuringSchedulingIgnoredDuringExecution`
_Prefer Any of_ | `preferredDuringSchedulingIgnoredDuringExecution`

Each rule type has the ability to add pod selectors, which can hold multiple pod label selector rules and namespaces. When navigating to the tab, it only shows ability to `Add Namespaces` and `Add Rules` for each pod scheduling preference type. There is no requirement to have any of these options so there doesn't need to have it expanded to automatically input.

**Pod Selectors**
These pod selector types are nested under the pod affinity type (either `affinity.podAffinity` or `affinity.podAntiAffinity`) and then nested under the preference type (either `requiredDuringSchedulingIgnoredDuringExecution` or `preferredDuringSchedulingIgnoredDuringExecution`).

For required, there is only 1 Pod Selector.
For preferred, there is ability to add multiple Pod Selectors. 

For each pod selector:

- [ ] Ability to add multiple namespaces 
- [ ] Ability to add/remove pod label selecting rules. There is 1 `labelSelector`, which can hold multiple pod label selector rules `matchExpressions`. 

Header/Label Name | k8s yaml under the preference type|
---|---
Namespace | `namespaces` | 
Pod Label Selector Rule | `labelSelector.matchExpressions` | 

_Namespace_ Info
- [ ] Title with `Select pods from these namespaces`
- [ ] Namespace selection - look at OPA gatekeeper constraints on how we add/remove namespaces. Default should be set to `This pod's namespace`, which would result in nothing populated in `namespaces`.  

_Pods with these Labels_ Info
- [ ]. Title with `Select pods with these labels`
- [ ] Labels selection using MatchExpressions Component
 
## `Tolerations` Section
- [ ] Header/Title with `Tolerations`

Ability to add/remove toleration rules. Each toleration rule has these fields:

Header/Label Name | k8s yaml | Input Field/Component | Example Input/Default
---|---|---|---
Label Key | `tolerations.key` | String input Textbox |
Operator | `tolerations.operator` | Dropdown options:<br> * = (`Equal`) <br> * exists (`Exists`)  | Default Value: `Equal`, If `Exists` is selected, the **value** input should be hidden with a `n/a` label shown instead of the textbox.
Value | `tolerations.value` | String input Textbox |
Effect | `tolerations.effect` | Dropdown with options: <br> * All (`All`)<br> * NoSchedule (`NoSchedule`) <br> * PreferNoSchedule (`PreferNoSchedule`) <br> * NoExecute (`NoExecute`) | Default value: `All`
Toleration Seconds | `tolerations.tolerationSeconds` | Integer input Textbox with `Seconds`  units label |

## `Priority` Section
- [ ] Header/Title with `Priority`

Header/Label Name | k8s yaml | Input Field/Component | Example Input/Default
---|---|---|---
Priority | `priority` | Integer Input Textbox | Example Text: `e.g. 3`
Priority Class Name | `priorityClassName` | String Input Textbox | Example Text: `e.g. system-node-critical`

**Comment by deniseschannon** [comment]
## Scaling/Upgrading Tab
This tab will have varying components based on the workload type. 

### Update Strategy

-[ ] Add a title for `Update Strategy` and only show for `Deployment`, `DaemonSet`, `StatefulSet`

**Deployment Update Strategy**
Header/Label Name | k8s yaml | Input Field/Component |  Default/Example Text | Helper Text | Units | 
---|---|---|---|---|---|
No Header | `spec.strategy.type` | Radiobutton Options: <br> * Rolling Update: Create new pods until max surge is reached before stopping old pods. Don't stop more pods than max unavailable.  (`RollingUpdate`)  * Recreate: Kill ALL pods, then start new pods (`Recreate`)  | Default: `RollingUpdate`. Only show Max Surge and Max Unavailable when `RollingUpdate` is selected | 
Max Surge | `spec.strategy.rollingUpdate.maxSurge` | Integer Input Textbox  | Example Text: `e.g. 25` Example dropdown: `%`| `The maximum number of pods allowed beyond the desired scale at any given time.` | Dropdown Options: <br> * `%`  <br> * `Pods`|
Max Unavailable | `spec.strategy.rollingUpdate.maxUnavailable` | Integer Input Textbox  | Example Text: `e.g. 25` Example dropdown: `%`| `The maximum number of pods which can be unavailable at any given time.` | Dropdown Options: <br> * `%`  <br> * `Pods`|

**DaemonSet Update Strategy**

Header/Label Name| k8s yaml | Input Field/Component |  Default/Example Text | Helper Text | Units | 
---|---|---|---|---|---|
No Header | `spec.strategy.type` | Radiobutton Options: <br> * Rolling Update: Stop old pods, then start new pods (`RollingUpdate`)  * On Delete: New pods are only created when you manually delete old pods  (`On Delete`)  | Default: `RollingUpdate`. Only show Max Unavailable when `RollingUpdate` is selected | 
Max Unavailable | `spec.strategy.rollingUpdate.maxUnavailable` | Integer Input Textbox  | Example Text: `e.g. 1`| `The maximum number of pods which can be unavailable at any given time.` | `Pods` |

**StatefulSet Update Strategy**
> Note: We are not implementing the StatefulSet `partition` field as part of RollingUpdate upgrades. 

Header/Label Name | k8s yaml | Input Field/Component |  Default/Example Text | Helper Text | Units | 
---|---|---|---|---|---|
No Header | `spec.strategy.type` | Radiobutton Options: <br> * Rolling Update: Stop old pods, then start new pods (`RollingUpdate`)  * On Delete: New pods are only created when you manually delete old pods  (`On Delete`)  | Default: `RollingUpdate` | 

**ReplicatSet/Job/CronJob Update Strategy**

None - Do not show anything in this section and hide `Update Strategy` title

Workload Type | Header/Label Name | k8s yaml | Input Field/Component | Default/Example Text | Helper Text |  Units
---|---|---|---|---|---|---
Deployment | Progress Deadline | `spec.progressDeadlineSeconds` | Integer Input Textbox |  Example Text: `e.g. 600` | `The duration that a deployment can make progress before being considered failed.` | `Seconds`
Deployment <br> DaemonSet <br> StatefulSet | Revision History Limit  | `spec.revisionHistoryLimit` | Integer Input Textbox | Example Text:  `e.g. 10` | `The number of versions to retain.` |  `Revisions`
Deployment <br> DaemonSet <br> ReplicaSet | Minimum Ready | `spec.minReadySeconds` | Integer Input Textbox |  Example Text: `e.g. 5` | `The minimum amount of time that the pod can be ready without any containers crashing to be considered available. ` |  `Seconds`
All | Pod Active Deadline | `<podTemplate>.spec.activeDeadlineSeconds`  | Integer Input Textbox | Example Text:`e.g. 10`| `The duration that the pod may be active before the system tries to mark it failed and kill associated containers. ` |  `Seconds`
All | Termination Grace Period | `<podTemplate>.spec.terminationGracePeriodSeconds` |  Integer Input Textbox |  Example Text: `e.g.` 30` |`The duration that the pod needs to terminate gracefully.` | `Seconds`

**Comment by deniseschannon** [comment]
## Volumes Tab
This is still TBD, but wanted to get started on mocks for other pages.

Workload Type | Header/Label Name | k8s yaml | Input Field/Component | 
---|---|---|---|
StatefulSet | StatefulSet Persistent Volume Claim Templates | `spec.volumeClaimTemplates` | Ability to add/remove PVCs

**Comment by deniseschannon** [comment]
## Security Tab
Everything listed here is nested under `<podTemplate>.spec.`.

Header/Label Name | k8s yaml | Input Field/Component | Example Input/Default
---|---|---|---
Share single process namespace | `shareProcessNamespace` | Radiobutton Options: <br> * `No` <br>* `Yes` | Default: `No`
Run as Not Root | `securityContext.runasNonRoot` | Radiobutton Options: <br> * `No` <br>* `Yes: containers must run as non-root-user`) | Default: `No`
Run as User ID | `securityContext.runAsUser` | Integer Input Textbox | Example Text: `e.g. 501`
Run as Group ID | `securityContext.runAsGroup` | Integer Input Textbox | Example Text:  `e.g. 501`
Additional Group IDs | `securityContext.supplementalGroups` | Ability to add/remove integer input textboxes by using `Add Group IDs` Button | Example Text: `e.g. 501`
Filesystem Group | `securityContext.fsGroup` | Integer Input Textbox | `e.g. 501` 
Use Host's PID Namespace | `hostPID` | Radiobutton Options: <br> * `No` <br>* `Yes`  | Default: `No`
Use Host's IPC Namespace | `hostIPC` | Radiobutton Options: <br> * `No` <br>* `Yes` | Default: `No`
Sysctls | `securityContext.sysctls` | KeyValue component with `Name` and `Value` as headers |  

- [ ] Update `Run as User number` to `Run as User ID`
- [ ] Update `Run as Group number` to `Run as Group ID`

**Fields from existing workloads page:** 

<img width="335" alt="Screen Shot 2020-05-06 at 2 04 59 PM" src="https://user-images.githubusercontent.com/11410997/81228241-970e6b80-8fa2-11ea-86d3-de603e563fa6.png">

<img width="336" alt="Screen Shot 2020-05-06 at 1 24 58 PM" src="https://user-images.githubusercontent.com/11410997/81224939-5102d900-8f9d-11ea-8da8-873af2cb3dec.png">

<img width="483" alt="Screen Shot 2020-05-06 at 8 11 38 PM" src="https://user-images.githubusercontent.com/11410997/81250739-8c6dc980-8fd6-11ea-8dbc-3d4bee1dac74.png">

**Comment by deniseschannon** [comment]
## Labels Tab

**Shown on all workload types**

Note: You won't be able to use `ResourceTabs` as there are different levels of labels that need to be specified. 

Section Header Name | k8s yaml | Input Field/Component | Tooltip Text
---|---|---|---
`<WORKLOAD_TYPE> Labels` | `metadata.labels` | KeyValue Component | 
`Pod Labels` | `<podTemplate>.metadata.labels` | KeyValue Component | 
`Selector Match Labels` |  `spec.selector.matchLabels` | ReadOnly View of KeyValue Component |  `Label selector for pods which matches the pod template's labels`

**Comment by deniseschannon** [comment]
## Annotations Tab

**Shown on all workload types**

Note: You won't be able to use `ResourceTabs` as there are different levels of annotations that need to be specified. 

Section Header Name | k8s yaml | Input Field/Component 
---|---|---
`<WORKLOAD_TYPE> Annotations` | `metadata.annotations` | KeyValue Component
`Pod Annotations` | `<podTemplate>.metadata.annotations` | KeyValue Component

**Comment by deniseschannon** [comment]
@lvuch Mocks to create:

1. Mocks for each workload type (6) with the different main section content. There are some fields that I don't know if we should put in this section or into a tab, but want to play around and see it before committing one or the other.
2. Mocks for each Tab (7) that are the same for each workload type. These tabs are universal across all the types as they are based on the pod template spec in each workload type.
3. Mocks for Scaling/Upgrading (6) for each workload type. 
Let's plan to review 1 and 2 before trying to create 3.

**Comment by lvuch** [comment]
wizard pages: https://xd.adobe.com/view/fa7ae40e-66f6-4d03-67d6-2b2f422beae5-8c4b/
tabs: https://xd.adobe.com/view/97f3c98c-addc-4664-4722-03d90e143726-e1c2/

**Comment by lvuch** [comment]
updated https://xd.adobe.com/view/fa7ae40e-66f6-4d03-67d6-2b2f422beae5-8c4b/

**Comment by deniseschannon** [comment]
Closing in favor of #825
