### ISSUE TITLE
Creating/Editing EKS clusters with Session Token requires MFA to be setup in AWS

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#6374]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Details:**
Creating an EKS cluster in Rancher requires an AWS Access Key and AWS Secret Key. There is an optional parameter for "Session Token". At this time it is not possible to use valid Session Tokens unless MFA is setup for the IAM user in AWS. 

This may require documentation in the UI as well.

**Comment by catherineluse** [comment]
I suggest closing this issue because we're not maintaining the Ember form for EKSv1.

**Comment by richard-cox** [comment]
Given https://github.com/rancher/dashboard/issues/6374#issuecomment-1184842508 closing
