### ISSUE TITLE
[BUG] Longhorn App installed through UI is not shown under 'Installed Apps'

### ISSUE THREAD

**Issue by crazyelectron-io** [rancher/dashboard#6375]
- Rancher version: 2.6.6

After installing Longhorn from the available Charts in Rancher it is installed but not showing up under the Installed Apps menu.

If I try to install Longhorn App again it shows 'Update' and when selecting the link in 'This chart has a fixed namespace and name. A matching [application](https://10.100.1.27/dashboard/c/c-m-pk2k4wjk/apps/catalog.cattle.io.app/longhorn-system/longhorn) has been found and any changes will be made to it.' It shows the Longhorn App on the next page but the application count remains 0, even when checking in another browser or refreshing the page.

To reproduce: Install a multi-node RKE2 cluster and install Longhorn through the UI. I've tested this multiple times.

**Comment by catherineluse** [comment]
> not showing up under the Installed Apps menu.

Maybe the namespace filter in the top nav is hiding it. Is it still not showing if the top nav is set to show all namespaces?

**Comment by crazyelectron-io** [comment]
My bad... I had not noticed that by default only the user namespaces is selected. I was so focused on getting Longhorn installed and configured that I failed to notice that little detail. :-)
Thanks!
