### ISSUE TITLE
Cannot update to RKE2 1.21.12 for Rancher from migration purposes

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6376]
Internal reference: SURE-4797
Reported in 2.6.5

Issue description:

The RKE2 release 1.21.12 is not available through Rancher.

Business impact: 
Cannot update to latest available RKE2 version

Troubleshooting steps:

```
$ curl -sL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.6/data/data.json | jq -r '.rke2.releases[] | select(.maxChannelServerVersion == "v2.6.4") | .version'
> v1.21.4+rke2r2
v1.21.5+rke2r1
v1.21.5+rke2r2
v1.21.6+rke2r1
v1.21.7+rke2r2
v1.21.8+rke2r2
v1.21.9+rke2r1
v1.21.10+rke2r2
v1.21.12+rke2r1
v1.21.12+rke2r2
```

```
curl -sL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.6/data/data.json | jq -r '.rke2.releases[] | select(.maxChannelServerVersion == "v2.6.5") | .version
> 
```
 
```
curl -sL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/release-v2.6/data/data.json | jq -r '.rke2.releases[] | select(.version == "v1.21.4+rke2r2") | .maxChannelServerVersion'
v2.6.4
curl -sL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.6/data/data.json | jq -r '.rke2.releases[] | select(.version == "v1.21.4+rke2r2") | .maxChannelServerVersion'
v2.6.4
``` 

Repro steps:
- Install RKE2 1.21.9
- Try to update through Rancher to RKE2 1.21.12

Workaround:
Use your own modified data.json from the settings.

Actual behavior:
Only default version are shown

Expected behavior:
Newest RKE2 version from the Matrix should be there

Additional notes:
Per https://github.com/rancher/rancher/issues/37547, this is expected but for people migrating from CaaSP to RKE2, this is a scenario that needs to be considered.

From a backend engineer:
> These versions restrictions are implemented in the Dashboard.  My suggestion would be to add an option to show deprecated versions in the ui that is disable by default.  Users should be able to edit the cluster as yaml and modify the k8s version to a deprecated version, no backend changes are required to support provisioning deprecated versions.

**Comment by catherineluse** [comment]
> These versions restrictions are implemented in the Dashboard.

For some background, this is the way it currently works.

- The UI gets the total list of RKE2 version options from the endpoint `/v1-rke2-release/releases`.
- To determine the default version, as of v2.6.5, the UI gets the default Kubernetes version from the global settings on the back end (https://github.com/rancher/dashboard/pull/5608). Anything newer in the total list of RKE2 version options is marked experimental, but the newest version should always be available in the UI.

If the most recent RKE2 version is not included, I would expect that means the endpoint `/v1-rke2-release/releases` isn't up to date.

**Comment by catherineluse** [comment]
# QA Template
## What was fixed, or what changes have occurred
Previously, the UI only showed the latest patch version for each Kubernetes minor version, because using a deprecated patch version is not a best practice for provisioning a new cluster. I added a checkbox directly under the Kubernetes version dropdown that reveals the deprecated versions if you need one for a special purpose.
 
## Areas or cases that should be tested
- Validate that when you check the new checkbox, the correct versions are marked deprecated (anything older than the latest patch version)
- Validate that you can create a RKE2/K3s cluster with a deprecated version (RKE2 v1.12.12 is the version specifically desired for this issue)
- Should see the same behavior as in the screenshots on this PR https://github.com/rancher/dashboard/pull/6410
 
## What areas could experience regressions?
- Make sure that the default Kubernetes dropdown is the same as it was before

**Comment by Josh-Diamond** [comment]
Ticket #6376 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.5`:
1. Fresh install of rancher `v2.6.5`
2. Provision a downstream RKE2 AWS Node driver cluster w/ k8s `v1.21.9+rke2r1` - [edit yaml for k8s version; not available in UI dropdown]
3.  Once cluster is `Active`, `Edit Config` and view available k8s versions in UI
4. Reproduced - `v1.21.12+rke2r2` is not available

Screenshot:

`Step 4`
<img width="1520" alt="Screen Shot 2022-07-21 at 2 12 57 PM" src="https://user-images.githubusercontent.com/46494969/180316154-1b0e08ee-9b26-4962-997e-821cfcdfc357.png">

---

Verified on rancher `v2.6-37ba5c952b3d9dbc6454e7c2dac17042838d3de0-head`:
1. Continuing on same server and cluster as above reproduction, upgrade rancher to `v2.6-head`
2. From `Cluster Management`, `Edit Cluster`; 
3. Verified - accurate k8s versions in drop down and observed new `deprecated k8s patch versions`  checkbox
4. Select `deprecated k8s patch versions` checkbox, and view available k8s versions;
5. Verified - `deprecated k8s patch versions` are accurate and older versions are un-selectable
6. Upgrade cluster to k8s `v1.21.12+rke2r2`
7. Verified - Cluster successfully upgrades
8. From `Cluster Management`, `Edit Config` on cluster once more
9. Verified - correct k8s versions in UI dopdown
10. Select `deprecated k8s patch versions` checkbox, and view available k8s versions
11. Verified - `deprecated k8s patch versions` are accurate and older versions are un-selectable

Screenshots:

`Step 3 - K8s versions`
<img width="1531" alt="Screen Shot 2022-07-21 at 2 29 51 PM" src="https://user-images.githubusercontent.com/46494969/180319919-9f5c2995-b792-44ca-b54f-dff2b4915536.png">

`Step 3 - New checkbox`
<img width="1536" alt="Screen Shot 2022-07-21 at 2 29 29 PM" src="https://user-images.githubusercontent.com/46494969/180319661-acf59589-10c0-40e1-ab9a-c2e66ced85ae.png">

`Step 5`
<img width="1534" alt="Screen Shot 2022-07-21 at 2 30 24 PM" src="https://user-images.githubusercontent.com/46494969/180319996-c7eb6a92-4bf6-4692-aa21-f321efa590a7.png">

`Step 7`
<img width="1537" alt="Screen Shot 2022-07-21 at 2 34 34 PM" src="https://user-images.githubusercontent.com/46494969/180320033-ba65451b-87e0-41ab-97a7-80688e37acec.png">

`Step 9`
<img width="1537" alt="Screen Shot 2022-07-21 at 2 35 17 PM" src="https://user-images.githubusercontent.com/46494969/180320087-51a3a66d-1935-4033-916c-f21dab47d2db.png">

`Step 11`
<img width="1540" alt="Screen Shot 2022-07-21 at 2 35 45 PM" src="https://user-images.githubusercontent.com/46494969/180320125-47a65a0f-bd1f-43c3-980c-725e0e4e1394.png">
