### ISSUE TITLE
Create button gets disabled for workloads/projects after an error

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#6378]
Setup

Rancher version: 2.6-head 3506e43
Browser type & version: Chrome

**Describe the bug**
When we submit any incorrect form for workloads/projects, the create button errors out. After few seconds the create button is disabled and we would need to navigate back to workloads/projects page to create resources.

**To Reproduce**
1. Create a project from projects/namespaces with the name `test;;;`. 
2. Click on create button , button changes to `Error`
3. Wait for a few seconds.

**Result**
Create button is disbaled.

**Expected Result**
Expected create button to be enabled after an error.

**Screenshots**
<img width="375" alt="create" src="https://user-images.githubusercontent.com/38144301/179090327-2aa7f4da-76d6-402d-a89f-f7a6ecfcfbf1.png">

**Comment by catherineluse** [comment]
It seems like something related to form validation @Sean-McQ

**Comment by Sean-McQ** [comment]
Yup! They can just click the "x" in the error message at the top to get the create button back but I can make some adjustments to make API errors not block the create button.

**Comment by nwmac** [comment]
@Sean-McQ Please to that

**Comment by anupama2501** [comment]
Re opening for QA validation.

**Comment by anupama2501** [comment]
Verified on v2.6-head 07ee596

After an error, create button changes to `Error` and then back to `Create` .
