### ISSUE TITLE
Enable Ubuntu 22.04 for RKE1 node templates

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6395]
on 2.6-head for 2.6.7, Enable Ubuntu 22.04 for RKE1 node templates.

It is called it in the support Matrix for this release.

**Comment by nwmac** [comment]
@sowmyav27 Can you point to where? I'm looking here: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-7/ and I don't see Ubuntu 22.04 support

**Comment by gaktive** [comment]
Upon checking with @sowmyav27, the goal is to add support for Ubuntu 22.04 in 2.6.9.

For context, the related backend work - https://github.com/rancher/rancher/issues/38362
And the original docker issue - https://github.com/rancher/rancher/issues/38390

**Comment by nwmac** [comment]
@gaktive Both of the referenced back-end issues are for milestone 2.7.0, so I assume this issue and the other two 22.04 issues should be as well.

**Comment by nwmac** [comment]
Digital Ocean and Linode covered by other tickets

I don't see any references in the Ember code to Ubuntu versions other than for Digital Ocean, so I don't think there is anything else to fix @catherineluse - but maybe you can verify

**Comment by catherineluse** [comment]
I looked into the other types of RKE1 templates (EC2, Azure, Harvester and VSphere). The only other reference to Ubuntu versions was the default image name for creating an Azure template:
<img width="728" alt="Screen Shot 2022-09-19 at 11 20 25 PM" src="https://user-images.githubusercontent.com/20599230/191182399-2f0bcd9d-6a1a-4713-af60-4463a6d4f22f.png">

**Comment by gaktive** [comment]
For QA, we'll leave 18.04 as the default for now just to reduce churn on the ember side of UI.

**Comment by catherineluse** [comment]
QA to validate that it works when you manually edit 18.04 to 22.04 in the image name for the instance when creating an RKE1 node template for Azure.
