### ISSUE TITLE
The secret list page loads slowly

### ISSUE THREAD

**Issue by niusmallnan** [rancher/dashboard#6400]
**Setup**
- Rancher version: v2.6.6
- Browser type & version: Chrome on Mac

**Describe the bug**
If the number of these two kinds of secrets is large: svc-account token and TLS certificate.
When using global admin or cluster owner to view the secret list, the UI response time is slow.

**To Reproduce**
Create hundreds of secrets with the svc-account token or TLS certificate.

**Result**
Even if ns is specified on the UI, this API interface(`/v1/secrets/`) will obtain the data of all namespaces, and it will take a long time to download the data.

**Expected Result**
The UI loads quickly and improves the user experience.

**Additional context**
I try to think of some solutions.

### Option One

Only request the specified ns data, which can avoid loading all secrets with a high probability.

```
/v1/secrets/ns1
/v1/secrets/ns2
/v1/secrets/ns3
```

### Option II

Secret type filtering is supported on the UI, and only data of type `Opaque` is queried by default. This may require some enhancements to the steve API.

**Comment by richard-cox** [comment]
Thanks for raising this issue. Can you confirm
- The number of secrets in your system where you see this issue
- Whether the secrets have values that are large
- Whether creating 200 secrets as described reproduces the issue

There are a number of performance issues we are currently investigating and this information will greatly help

**Comment by catherineluse** [comment]
> Even if ns is specified on the UI, this API interface(/v1/secrets/) will obtain the data of all namespaces

The UI frequently uses `findAll` to get all resources of a certain type. https://github.com/rancher/dashboard/blob/master/shell/plugins/dashboard-store/actions.js#L78 One issue with the `findAll` is that it is not aware of active namespaces. I think it that before `findAll` fetches all of any resource type, it should check for selected namespaces, preferably using this active namespace cache. https://github.com/rancher/dashboard/pull/6261/ If any are selected, it should fetch the resources one namespace at a time.

**Comment by catherineluse** [comment]
Related issue https://github.com/rancher/dashboard/issues/6515

**Comment by richard-cox** [comment]
Related issue https://github.com/rancher/dashboard/issues/6483 (which is a workaround, more improvements to come)

**Comment by gaktive** [comment]
The related issues should help sort this out but there are also going to be backend fixes coming in later that should address this.

**Comment by richard-cox** [comment]
@niusmallnan  You might be interested in a feature from 2.7.5 that filters resources via the values in the namespace / project filter in the header. This greatly reduces the number of resources fetched by the UI. To enable please go to burger menu top left --> `Global Settings` --> `Performance` --> `Require Namespace / Project Filtering` and check the box and hit `Apply`.

**Comment by richard-cox** [comment]
This falls in the general 'we shouldn't fetch all resources' sphere. There's a current workaround listed in https://github.com/rancher/dashboard/issues/6400#issuecomment-1680474700 and will be fully resolved via https://github.com/rancher/dashboard/issues/8527
