### ISSUE TITLE
HTTP Error 500: Internal Server Error --- Facing this issue while exploring cluster 

### ISSUE THREAD

**Issue by prasadve0506** [rancher/dashboard#6401]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by gaktive** [comment]
@prasadve0506 Do you have more information about which page you're seeing this and what version of Rancher? Please fill out the template on this page to help us better diagnose what you're running into, especially if you can provide reproduction steps and more information about your setup.

**Comment by nwmac** [comment]
Closing as stale - please re-open with more info if this is still an issue.
