### ISSUE TITLE
"Clone as Yaml" for a Configmap fails with Internal Server Error

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#641]
Version: master-head(dd102af17)

Steps:
1. Create a configmap "cmap1" by providing key/value
2. Clone the configmap using "Clone as Yaml" option
3. The Yaml file is displayed as below, change the name to "cmap2"
```
apiVersion: v1
data:
  k1: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-12T18:06:28Z"
  name: cmap2
  namespace: default
  resourceVersion: "6064"
  selfLink: /api/v1/namespaces/default/configmaps/cmap1
  uid: 27ad9b9b-1eae-4dcf-9cb1-4063a87c3dbc

```
4. Hit "Create" button

Result:
It fails with "Internal Server Error" as below
```
{"type":"error","links":{},"code":"","message":"resourceVersion should not be set on objects to be created","status":500,"type":"error"}
```
![Screen Shot 2020-05-12 at 11 35 36 AM](https://user-images.githubusercontent.com/18536626/81732058-bc88f280-9444-11ea-97bb-6cd625374df3.png)

Note: If the resourceVersion is removed from the yaml file, clone succeeds.

**Comment by deniseschannon** [comment]
@codyrancher Based on outside convos, when cloning yaml, in `metadata`, we are only going to clone `metadata.namespace` field.

**Comment by codyrancher** [comment]
This will be resolved by https://github.com/rancher/dashboard/pull/650

**Comment by soumyalj** [comment]
Validated with master-head(1f4a2c388)

Steps:

1. Create a configmap "cmap1" by providing key/value
2. Clone the configmap using "Clone as Yaml" option
The Yaml file is displayed as below. 
```
apiVersion: v1
binaryData:
  keyfile: azE9djE=
data:
  test1: val1
kind: ConfigMap
metadata:
  annotations:
    k2: v1
  labels:
    k1: v1
  name: ' '
  namespace: newns

```
Provide a name and the clone succeeds as expected.
