### ISSUE TITLE
Show breadcrumbs when user has filtered by project

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6414]
Capturing feedback from Kenneth -

It is not clear to new Rancher users when their view is filtered by project. For example, if you install a Helm chart, you might not immediately see it in Installed Apps due to a project filter:
<img width="1660" alt="Screen Shot 2022-07-19 at 6 38 12 PM" src="https://user-images.githubusercontent.com/20599230/179877119-26ed3af8-0388-4791-9dff-1e654a148475.png">

This could be done in addition to table filtering, depending on how the UX design turns out.

We would still need to decide what to do if the user filters to show multiple projects.

**Comment by kwwii** [comment]
I looked into this yesterday and I think that the simplest solution might be to add some text after the page title along the lines of "(14/32)" which would indicate that you are viewing 14 of a total of 32

**Comment by kwwii** [comment]
Closing this as it's a duplicate UX of https://zube.io/rancher/dashboard-ui/c/6355
