### ISSUE TITLE
Invalid Linode instance types show in LKE driver

### ISSUE THREAD

**Issue by LBGarber** [rancher/dashboard#6424]
**Rancher Server Setup**
- Rancher version: v2.6.4
   
**Describe the bug**
When provisioning an LKE cluster, new invalid Linode types will be displayed as selectable node types despite being unsupported by LKE.

**To Reproduce**
1. Navigate to the LKE cluster provisioning UI -> Node Pool Configuration
2. Observe Linode types other than `nanode` and `gpu` not being excluded from valid node types (**NOTE**: Additional Linode types may only display for certain users)

**Result**
Incompatible types display under the node type selection drop-down alongside valid types.

**Expected Result**
Only types with class `dedicated`, `highmem`, and `standard` display under the node type selection drop-down.

**Additional context**
Ideally types would be filtered on whether their class is explicitly `standard`, `highmem`, or `dedicated`.

**Comment by richard-cox** [comment]
@LBGarber To confirm, this issue only affects RKE1 clusters and NOT RKE2?

For RKE2 provisioning (in `rancher/dashboard`) we  fetch the list from a similar endpoint (`api.linode.com/v4/images`)

**Comment by LBGarber** [comment]
@nwmac Sorry for the late response,

This issue primarily affects instance types that aren't publicly available or are restricted to certain users, so this is just a preemptive issue to prevent unsupported instance types from popping up in the future.

**Comment by gaktive** [comment]
PR was merged back in February 2023 so this is fixed in 2.7.2

**Comment by gaktive** [comment]
@lbgarber let us know if there's anything left to do here.
