### ISSUE TITLE
Release task: What's new in 2.6.7 (with 2.6.6)

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6430]
Similar to https://github.com/rancher/dashboard/issues/5638, this ticket is to update dashboard/content/docs/en-us/whats-new.md with material that appears in the UI about what's new. This was missed in 2.6.6.

Checking with @wjimenez5271 what needs to go in.

(Normally there would be a ticket like https://github.com/rancher/rancher/issues/37315 for the overall release, so I'm jumping the gun a bit.)

**Comment by gaktive** [comment]
Filed moved to https://github.com/rancher/dashboard/blob/master/shell/content/docs/en-us/whats-new.md

Initial PR: https://github.com/rancher/dashboard/pull/6449 (draft)

**Comment by gaktive** [comment]
Most of content in the PR now, though checking if wording for the sole 2.6.6 item can be refined from Team 1. Should be able to get this into review shortly.

**Comment by gaktive** [comment]
Content in place.

**Comment by Josh-Diamond** [comment]
Ticket #6430 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-89fec60628df484c6a136e49ac5b49834df0b51d-head`:
1. Fresh install of rancher `v2.6-head`
2. Verified, `What's new in 2.6` is seen on `Home`
3. From `Home`, select `What's new in 2.6`
4. Verified - `New 2.6.7` content is listed
5. Veri-FAILED - AWS Marketplace link broken; `404 - Not Found`
6. Veri-FAILED - Typo seen under `Kubernetes 1.24`;
    - Currently: Kubernetes 1.24 is now a supported Kubernetes version for running Rancher as well `for` provisioned and imported RKE1/RKE2/k3s clusters.
    - Suggested-fix: Kubernetes 1.24 is now a supported Kubernetes version for running Rancher as well `as` provisioned and imported RKE1/RKE2/k3s clusters.

Screenshots:

`Step 2 - Verified`
<img width="1620" alt="Screen Shot 2022-08-08 at 10 27 26 AM" src="https://user-images.githubusercontent.com/46494969/183478912-54004aa7-eda4-4b64-b0fd-3b4e193bac91.png">

`Step 4 - Verified`
<img width="1625" alt="Screen Shot 2022-08-08 at 10 25 37 AM" src="https://user-images.githubusercontent.com/46494969/183479005-e0e88682-d45e-4c24-b8c8-f492240fa6e9.png">

`Step 5 - Veri-FAILED`
<img width="1627" alt="AWS_Bililng_marketplace_link" src="https://user-images.githubusercontent.com/46494969/183479092-e7d87dc5-aa96-40ca-a90e-6596b1161d8a.png">

`Step 6 - Veri-FAILED`
<img width="920" alt="Screen Shot 2022-08-08 at 10 36 50 AM" src="https://user-images.githubusercontent.com/46494969/183479192-f39b011c-78e7-4c70-a1a6-dcc97d5adae9.png">

**Comment by Josh-Diamond** [comment]
Ticket #6430 - Test Results [pt. 2]

With Docker on a single-node instance:

Verified on rancher `v2.6-cd97f6fd1e894dd8677efa2fa87c57d7c7a68d54-head`:
1. Fresh install of rancher `v2.6-head`
2. From `Home`, select `What's new in 2.6`
3. Observe Kubernetes 1.24 section
4. Verified - Description clearly states the following: 
   - `Kubernetes 1.24 is now a supported Kubernetes version for running Rancher as well as for provisioned and imported RKE1/RKE2/k3s clusters.`
