### ISSUE TITLE
[Nuxt Removal] - Fix live/hot module reload

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#6437]
Live/hot module reload aren't working in the nuxt removal branch. I think this will be a relatively simple webpack configuration task. I think it's just missing rather than being broken.

Notes:
- Branch with nuxt removal https://github.com/codyrancher/dashboard/tree/nuxt-out

**Comment by nwmac** [comment]
Closing this - added as a note to the main ticket #5968
