### ISSUE TITLE
[Nuxt Removal] - Verify Build

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#6439]
Verify that building and building with plugins is still functional. Thus far I've only verified that the local version of nuxt removal works. We still need to make sure that normal and plugin release versions still work.

Notes:
- Branch with nuxt removal https://github.com/codyrancher/dashboard/tree/nuxt-out

**Comment by nwmac** [comment]
Closing this - I think this is done, but added as a note to the main ticket: #5968
