### ISSUE TITLE
Creation, deletion and editing of configmaps is reflected in the list view only after a refresh

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#644]
Version: master-head(dd102af17)

Steps:

- Create configmap
1. Create a configmap by providing a key/value pair. 
2. Configmap gets created, but is displayed in the UI only after a refresh. 
After creating the configmap, we see the list view for configmaps, but the configmap created is not present.

- Delete configmap
1. Create a configmap by providing a key/value pair. Refresh the UI.
2. Delete the configmap from the list view. The configmap is removed from the list view only after a refresh
This same issue is observed when deleting multiple configmaps.

- Edit configmap
1. Create a configmap by providing a key/value pair. Refresh the UI.
2. Edit the configmap by choosing "Edit as form" option. Ex: Change the key/value pair or labels and save. 
We are directed back to the list view. Go to "Edit as form" , the changed values are not reflected. The changed values are reflected only after refreshing the UI.

Other Info:
Browser: Chrome

If we launch the dashboard in a new window and create/edit/delete configmaps, then refresh issues are not seen for sometime.

**Comment by deniseschannon** [comment]
@vincent99 It was mentioned by @mantis-toboggan-md that you might have fixed this already? Can you confirm?

**Comment by codyrancher** [comment]
@deniseschannon @vincent99 

I was just testing. Create and delete seem to be working now but editing seems to be worse. When I edit an entry a duplicate entry now shows up in the list.

![Screen Shot 2020-05-19 at 3 38 20 PM](https://user-images.githubusercontent.com/55104481/82385420-ef079200-99e6-11ea-97ca-5073cf9bd7af.png)

**Comment by vincent99** [comment]
I'll look at edit.. it appears both the clone to be edited and original are ending up in the store somehow.

**Comment by vincent99** [comment]
Should be better now, d8d3f8120ff07a4ed2990c87fb681111c5b1ed52 .

**Comment by soumyalj** [comment]
Validated with master-build(b85ea695f)
Created, deleted and edited few configmaps. 
Creation deletion and editing of configmaps are reflected in the list view without a refresh. 
Editing a configmap does not show duplicate entries in the list view.
