### ISSUE TITLE
When provisioning a downstream RKE1 node driver cluster, having multiple node pools with no name prefix gives error message `Node pools must have unique name prefixes`

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#6446]
**Setup**
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/c47178eb1457a7ff1aac135c86d3627dc971b704
- Browser type & version: Chrome

**Describe the bug**

When provisioning a downstream RKE1 node driver cluster, I noted that when you add additional node pools with no name prefix, you get error message `Node pools must have unique name prefixes`:

![image](https://user-images.githubusercontent.com/52591819/180284197-48965509-8a92-441c-b5b1-b4abe229934f.png)

In the scenario where you have one or more node pools that indeed do have a non-unique name prefix, this error makes complete sense. However, this doesn't make sense to display this error when you have not filled out any name prefixes yet and you are adding additional node pools.

Additionally, this is a recent change as last week, I did not see this behavior happen. From a user's perspective, this is confusing and we should address this.

**To Reproduce**

1. Setup Rancher and navigate to the UI in a browser.
2. Provision a downstream RKE1 node driver cluster.
3. Without entering a name for the first name prefix, dd an additional node pool and you should see the above-mentioned screenshot and the error message.

**Result**
You get error `Node pools must have unique name prefixes` without even filling out any name prefixes.

**Expected Result**

If I do not fill out any name prefixes in a node pool, I should get an error message saying my node pools need unique name prefixes.

**Comment by markusewalker** [comment]
@nwmac I think this issue may be an unexpected regression of the following PR: https://github.com/rancher/ui/pull/4842. Please correct me if I am wrong.

**Comment by markusewalker** [comment]
While this issue is under investigation, here is the QA test plan:

**TEST PLAN**
1. Setup Rancher and navigate to the UI.
2. Create a standard user and login as that user.
3. Begin to provision a downstream RKE1 node driver cluster.
4. Without entering a name for the first name prefix, add an additional node pool; validate if there is an error having multiple empty node pools with no name prefix.

**Comment by gaktive** [comment]
We're not going to fix this since this requires full form validation in the Ember UI and we're not going to implement that.

**Comment by catherineluse** [comment]
> this requires full form validation in the Ember UI

It does? The way I'm reading it, the empty fields would just need to be excluded from the equality comparison when checking for duplicated names.

So the code would just change from this:

```
if (names[hostnamePrefix]) {
        isError = true;
      } 
```
to this:
```
if (names[hostnamePrefix] && hostnamePrefix !== '') {
        isError = true;
      } 
```

**Comment by nwmac** [comment]
I think we'd want to warn that the prefix fields were empty and they are required.

Can think what we have currently is good enough.

**Comment by markusewalker** [comment]
Spoke of this issue offline with @nwmac. Considering that this issue is more of a minor annoyance as opposed to blocking functionality, I think it is okay to close this issue. The UI team is looking towards other issues at this time and this isn't a huge priority.
