### ISSUE TITLE
`isImported`, `isImportedK3s` and `isRke2` on provisioning cluster model return incorrect values

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6447]
This issue is a followup to https://github.com/rancher/dashboard/pull/6396

The `isImported` and `isImportedK3s` getters are returning false negatives for imported K3s clusters because they assume that the provisioner of an imported K3s cluster will be `imported`, but now the provisioner is `k3s`.

Before fixing the getters on the provisioning cluster model, we should find out why the return value of the provisioner changed and if anything currently relies on the provisioner being `k3s.`

Also, the `isRke2` getter returns true for both RKE2 and K3s, leading to confusing looking code, such as a conditional statement to check if a cluster is K3s within a conditional statement checking `isRke2`. https://github.com/rancher/dashboard/pull/7060

**Comment by gaktive** [comment]
Might be fixed already in 2.9.0+. Closing based on the age of the ticket but if this is still an issue, please confirm a newer version.
