### ISSUE TITLE
When clone a workload, nvidia.com/gpu resource lost

### ISSUE THREAD

**Issue by guanbear** [rancher/dashboard#6454]
**Setup**
- Rancher version: 2.6.6
- Kubernetes: v1.18.6

**Describe the bug**

When clone workload and create, nvidia.com/gpu resource lost
**To Reproduce**

1. clone a workload with nvidia/gpu resouce (request/limit is "8")
![image](https://user-images.githubusercontent.com/11829005/180414207-1519a6d6-257a-4bc0-8ceb-c6ac644d32d8.png)
2. Click "Create" buttom 

**Result**
![image](https://user-images.githubusercontent.com/11829005/180414493-e897172b-ef0a-4b82-a52d-13feb7347892.png)
nvidia.com/gpu resource lost
**Expected Result**

keep nvidia.com/gpu resource as CPU/MEM
**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by AndrewHoffmanQA** [comment]
**status: Passed**

retested on local HA server 
rancher -v2.6-22bcec9

I created, cloned and edited deployments with GPU values and the values persisted. 

video of retest 

https://user-images.githubusercontent.com/89030218/189411449-0b9f51a5-1504-4741-a32a-e33a3fa4fa46.mp4
