### ISSUE TITLE
Improve Workload creations screens

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#6455]
This is a continuation of the work done in 2.6.7.

- Use the new UI for all workload types
- Leverage new UI to create form UI for Pods
- Change use of tabs for Container settings back to original design and use tabs for categories of settings
- Ensure settings align with k8s API definitions

**Comment by catherineluse** [comment]
@Shavindra Can you please add more detail about the changes that needed to be made in order for the issue to be addressed? And how should this be tested? "Ensure settings align with k8s API definitions"

**Comment by nickwsuse** [comment]
`Verified on v2.6-head Commit ID: 68215bc`

I checked all the recommended checks noted on the merged PR (https://github.com/rancher/dashboard/pull/6632) and everything worked like a charm. The three tabs are present (the first tab is dynamic and changes to whatever workload item you're creating/editing) and tested the issues/questions brought up in the comments of the PR.
