### ISSUE TITLE
Notifications overlap and are hard to read on rancher 2.6-head w/ Docker

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#6460]
**Setup**
- Rancher version: `v2.6-head` - [`37ba5c9` + `e464ea4`]
- Browser type & version: `Chrome`

**Describe the bug**
Notifications displayed are overlapping and hard to read

**To Reproduce**
1. Fresh install of `v2.6-head` on a single-instance w/ Docker
2. From `Home`, click `Create`, or try to visit `Cluster Management`
3. Reproduced

**Result**
From `Cluster Create` page, error notifications are seen overlapping each other

**Expected Result**
Error notifications are clean, concise, and readable

**Screenshots**

`37ba5c9`
![37](https://user-images.githubusercontent.com/46494969/180475366-87a4b17e-a3ea-4b89-9733-cf9bb71d628c.png)

`e464ea4`
![ea4](https://user-images.githubusercontent.com/46494969/180475599-768e779c-7f5f-479d-8549-ff8d16ca0cf2.png)

**Comment by richard-cox** [comment]
It looks like that is a combination of ember and dashboard growls

**Comment by Josh-Diamond** [comment]
Ticket #6460 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-b66dd0f614f9d60ef54dfb82da12b9b8b194021b-head`:
1. Fresh install of rancher `v2.6-head`
2. Once logged in, terminate Rancher server instance (AWS Console)
3. Verified - Ember related notifications have been disabled

Screenshot:

`Step 3`
![proof](https://user-images.githubusercontent.com/46494969/180843027-3e9fc9ca-13c0-482f-993f-ad4dfce4307c.png)
