### ISSUE TITLE
Cluster Explorer recomputes active namespaces too many times

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6463]
Every time Cluster Explorer loads a list of resources, it recomputes the active namespaces for every item in the list. So for a list of 50 resources, the UI loops over all namespaces in the cluster 50 times. This takes too much time for clusters that have thousands of namespaces.

We should cache the short list of active namespaces so that the workloads page loads faster.

Note: This issue should not be tested until https://github.com/rancher/dashboard/issues/6463 is tested and closed

**Comment by catherineluse** [comment]
# QA Template
## Root cause
There are multiple reasons why the loading time for resource lists is a long time for large clusters (the larger issue is tracke here https://github.com/rancher/dashboard/issues/6457), but one reason is that the active namespaces are recomputed too many times.
 
## What was fixed, or what changes have occurred
This PR https://github.com/rancher/dashboard/pull/6261 caches the list of active namespaces so that they are only recomputed when they change.
 
## Areas or cases that should be tested
This PR is not intended to change any existing behavior for the UI. However, QA should try to make sure that namespace functionality has not been broken by the code changes.
 
## What areas could experience regressions?
QA should validate that as the filters in the top nav of cluster explorer change, everything continues to work as expected.

**Comment by catherineluse** [comment]
Moved out of To Test because some changes in this PR had to be refactored as part of bug fixes for namespace filtering issues. This PR needs to be revisited to make sure it achieves the same effect after the bug fix.

**Comment by catherineluse** [comment]
I validated through logging that the namespace cache is still being used for filtering lists of resources, so the performance is still intact. We still get the benefit of not looping over namespaces for each resource in a list, so I am moving this back to To Test.

**Comment by nataliefyi** [comment]
Tested on 2.67-rc9 with 10,000+ namespaces. Significantly improved performance when navigating in Cluster Explore, no effect on namespace filtering functionality observed
