### ISSUE TITLE
Elemental - TypeError when creating a machine registration

### ISSUE THREAD

**Issue by juadk** [rancher/dashboard#6471]
**Setup**
- Rancher version: latest (2.6.6)
For the dashboard, I used https://github.com/aalves08/dashboard/tree/os-elemental-resources

**Describe the bug**
Create a new machine registration:
![image](https://user-images.githubusercontent.com/6025636/180459702-e83a1abe-3cba-4fad-97bb-b9a688e5de82.png)

After clicking on `Create` , you should see these errors in the dev web console:
```
client.js:103 TypeError: Cannot read properties of undefined (reading 'registrationURL')
    at Proxy.render (elemental.cattle.io.machineregistration.vue?7a3c:44:1)
    at Vue._render (vue.runtime.esm.js:3569:1)
    at VueComponent.updateComponent (vue.runtime.esm.js:4070:1)
    at Watcher.get (vue.runtime.esm.js:4495:1)
    at Watcher.run (vue.runtime.esm.js:4570:1)
    at flushSchedulerQueue (vue.runtime.esm.js:4326:1)
    at Array.<anonymous> (vue.runtime.esm.js:1989:1)
    at flushCallbacks (vue.runtime.esm.js:1915:1)

xhr.js:178          PUT https://192.168.121.145:8005/v1/userpreferences/user-nvz67 500 (Internal Server Error)
```
Sometimes it does not impact the user experience but sometimes a web page is shown with the issue.
I will try to add a screenshot with the wrong web page.

**Comment by juadk** [comment]
In Cypress, even if the test passes, I can see this screen:
![image](https://user-images.githubusercontent.com/6025636/180741253-c677dd7c-7ca8-4824-a58b-df6292962b6a.png)

**Comment by aalves08** [comment]
@juadk thanks for reporting the issue 🙏 Just a heads up, if you are automating some tests, you are working against code that hasn't been reviewed nor merged so it may have changes to the code that can break your work.

**Comment by juadk** [comment]
yeah I know but it will be quickly fixable, I prefer start earlier and already get a code base. I will do the same for the CI waiting the push of your dev branch as Richard advised.

**Comment by juadk** [comment]
This one is no longer happening, the CI is green every night so let's close it for now.
I will open it again if needed.
