### ISSUE TITLE
Create rke2 cluster, setting Registries does not take effect

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#6472]
**Setup**
- Rancher version: v2.6.6
- Browser type & version: Chrom 103.0.5060.134 (x86_64)

**Describe the bug**

Create rke2 cluster, setting Registries does not take effect
**To Reproduce**

1. Create a custom rke2 cluster
2. Navigate to Cluster Configuration--Registries and select `Configure advanced containerd mirroring and registry authentication options`
3. Add Registry
4. Create a Http Basic Auth Secret, set the correct username/password
5. Create cluster
6. Then edit the cluster and view the parameters of the Registries

**Result**
The value of Authentication is None

**Expected Result**

The Http Basic Auth Secret I created when I created the cluster should be selected

**Screenshots**

![auth](https://user-images.githubusercontent.com/19684717/180738651-7f29c9e1-c88c-4267-8591-25f4bf102215.gif)

**Comment by catherineluse** [comment]
Note for QA: This issue seems to be only reproducible for custom RKE2 clusters, not node pool clusters.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 2587e6a
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2

----------
### Reproduction: ###
Reproduced using the following steps:
1. Create a custom rke2 cluster
2. Navigate to Cluster Configuration--Registries and select `Configure advanced containerd mirroring and registry authentication options`
3. Add Registry
4. Create a Http Basic Auth Secret, set the correct username/password
5. Create cluster
6. Then edit the cluster and view the parameters of the Registries

**Result** - Reproduced
The value of Authentication is `None`
![image.png](https://zube.io/files/rancher/d2eb7866ca64c6af1c91c474c0adbf69-image.png)

### Testing: ###
Tested this issue with the following steps:
1. Create a custom rke2 cluster
2. Navigate to Cluster Configuration--Registries and select `Configure advanced containerd mirroring and registry authentication options`
3. Add Registry
4. Create a Http Basic Auth Secret, set the correct username/password
5. Create cluster
6. Then edit the cluster and view the parameters of the Registries

**Result** - Pass
The value of Authentication now preserves the authentication created while provisioning custom cluster.
![image.png](https://zube.io/files/rancher/ea1ab7d67fb61bc7092b4673da986944-image.png)
