### ISSUE TITLE
UI Prometheus config should include a default namespace label in order for alerts to be sent

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#6478]
**Setup**
- Rancher version: `2.6.7-rc2`
- Browser type & version: `Chrome Version 103.0.5060.114 (Official Build) (x86_64)`

**Describe the bug**
Alerts are not sent due to a missing namespace label. Adding that label to the alert config corrects the situation. 

**To Reproduce**
1. install monitoring
2. install alerting drivers
3. create alertmanager config
4. create reciever
5. create route
6. create prometheus rule
7. add a match for label, eg, team=qa

**Result**
alerts are configured, they appear on the alert manager status page, but they do not get sent via sachet. the reason is the missing namespace label - so, vector(0) does not get sent. 

**Expected Result**
alerts are sent to alert endpoint (eg, sms configured webhook)
adding label for 'namespace' 'default' send the alerts
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#alertmanagerconfigspec-1
is a link to the applicable configuration rule

**Screenshots**

<img width="1157" alt="2022-07-25_18-11-09" src="https://user-images.githubusercontent.com/89212856/180882668-5be5b664-a160-4bad-9853-57ff7f8baac3.png">

**Additional context**

**Detailed Description**

**Context**

**Comment by catherineluse** [comment]
Should the default namespace label match the namespace that the AlertmanagerConfig is deployed in?

**Comment by catherineluse** [comment]
What are the requirements for the alert to be sent to sachet? Is sachet expecting alerts to be labeled in a specific namespace?

**Comment by AndrewHoffmanQA** [comment]
retest: failed

setting back to 'reopen state'

tested on local
- HA server
- rancher 2.6.7-rc6
- RKE1- v1.3.13-rc6

retest video attached 

https://zube.io/files/rancher/92d8fe86918fd124bb7b10ab54e033b4-retest6478.mp4

**Comment by AndrewHoffmanQA** [comment]
retest- passed

the pr wasnt in rancher 2.6.7-rc6, testing on v2.6.head-cd97f6f resulted in a pass. when the user creates a Prometheus rule and clicks the 'add alert' button the label field already displays an entry of 'key = namespace' and 'value = default' 

tested on local
- HA server
- rancher 2.6.head-cd97f6f
- RKE1- v1.3.13-rc6
