### ISSUE TITLE
Improve performance of side nav in Cluster Explorer

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6485]
There is already a tech debt issue about the side nav here https://github.com/rancher/dashboard/issues/5607 with more details about how it could be refactored, but I created this issue to focus on the performance aspect for v2.7.x.

Profiling showed that the browser takes a long time to run the `getGroups` button to build the side nav structure. `getGroups` determines the side nav structure by making numerous calls to the store, and could be replaced with declarative configuration objects.

**Comment by richard-cox** [comment]
Closing in favour of newer but more detailed https://github.com/rancher/dashboard/issues/7773
