### ISSUE TITLE
More improvements to SortableTable performance

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6487]
There have already been several PRs that improved the performance of SortableTable, but I opened this issue to capture additional suggestions. To my knowledge these haven't been addressed yet (though I could be wrong).

- ~~Currently the SortableTable creates a new store for the selection state, which seems to have a large overhead. The new store should be replaced if it hasn't already.~~
- We should see if it could help to convert some formatters to Vue functional components.
- Wherever possible, we should make sure that table definitions have functions to get values rather than by using JSONPath.
- Mouseovers on table rows are implemented with event processing that shouldn't be needed. We could investigate if it would make a difference to replace it with native Vue event listeners.

**Comment by gaktive** [comment]
We'll close this ticket in lieu of making this a component instead: rancher/dashboard#7416
