### ISSUE TITLE
Optimize resource lists

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6488]
Sean noted that Javascript has bad performance with arrays of objects, but you can create indices for those objects to improve performance. You can create a secondary object with a key for each object, and store those keys in an array. Then looping over the array of keys works faster because Javascript is good at optimizing arrays of primitives.

Sean also suggested storing arrays of objects in the store as serialized objects instead of classes, while turning classes into computed properties in Vue components. In other words, we could "hydrate" resources at the component level instead of storing huge arrays of "hydrated" resources in Vuex.

@Sean-McQ can confirm if I understand this correctly.

**Comment by Sean-McQ** [comment]
Indeed, most javascript engines will optimize an array of primitives to a [typed array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays) under the hood for better performance and memory usage and the gains can be significant when you're looping over large arrays to find values. Creating "index" arrays can be an extreme step though, especially if you're only ever looping through an array to find an object with a specific "id" property. In that case, it's often better to store your objects on a bigger object with the "id" of each object as the property on which the object is stored. In that way you can access the object without needing to loop over a large array of objects (which aren't optimized as typed arrays by the JS engine as far as I know) and you'll save yourself a lot of time spent evaluating potentially complex object in the UI thread.

I also tend to think we can squeeze out a decent performance increase if we only keep simple objects, arrays, and primitives in the store and then instantiate them as full objects in the component(s) that'll actually need the more advanced methods we use in our resource models.

Of the two, I'd probably go for changing how we load resources in the store and then spinning them up as class instances in components as the best bang for our buck but I don't have enough information to know what kind of refactor effort that would even look like. I'd recommend a scream test to see what kind of work doing something like that would entail (a scream test in this case would be removing our logic to instantiate resources in the store as class instances and then seeing how the app breaks, fixing the initial issues that arise would give us a decent eye on how much work we'd be looking at to fully implement a big sweeping change like that).

**Comment by nwmac** [comment]
@Sean-McQ This relates to the changes I would like us to make for 2.7.0 - note that some of our tables sort by computed fields that are described in the models, so if we want to sort over the raw json objects, we'd need to consider that.
