### ISSUE TITLE
Upgrade to Webpack 5 for performance

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6489]
I opened this issue to capture a suggestion made several months ago to improve performance. Upgrading webpack would require removing Nuxt.

Edit: Correction per Neil's comment.

**Comment by nwmac** [comment]
@catherineluse You can use WebPack 5 with Vue 2. The blocker is removing Nuxt.

**Comment by catherineluse** [comment]
Related PR https://github.com/rancher/dashboard/pull/6440

**Comment by nwmac** [comment]
Revisit after update to Vue 3 - won't fix for now
