### ISSUE TITLE
Exclude unneeded fields from API calls

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6490]
Colleen added field filtering for resources on the back end https://github.com/rancher/rancher/issues/36683. We should go through some slower list views in the UI and evaluate what data we can exclude using the new query params.

When looking at how data is fetched for list views, we should also check if some data is unnecessarily stalled by waiting for other data, which is what happened when the node list view was blocked waiting for pods: https://github.com/rancher/dashboard/pull/6392

**Comment by nwmac** [comment]
This would mainly help with resources that store data, such as Config Map, Secret and Fleet Bundles.

**Comment by nwmac** [comment]
We are using this for `managedFields` - I think this is good enough for now and with the upcoming pagination work, this will be enough.
