### ISSUE TITLE
Flush data from Vuex only when needed instead of once per second

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6491]
I created this issue to track a suggestion from our performance notes.

**Comment by richard-cox** [comment]
Neil has added a web worker to change the way the counts and schema resource types are emitted from the sockets (and thus hitting the store). We should look at extending that to other types

**Comment by gaktive** [comment]
Should be addressed based on @Sean-McQ's web-worker work in #5997 rancher/dashboard#5997

**Comment by gaktive** [comment]
Closed as duplicate.
