### ISSUE TITLE
Extract non-localised strings

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6492]
There are still a lot of strings that have not been extracted to use the localisation mechanism.

The task here is to go through the UI and pull any strings out that have not been localised.

To aid doing this, you can press `shift + l` to toggle the locale between `None` and the current locale - this quickly shows you for a given page, which strings have not been localised.

Priority order:

- Home page
- Cluster Explorer (exploring a given cluster)
- Global Settings
- Users and Authentication
- Cluster Management
- Continuous Delivery

You should create a docs page with info for localising, for other developers to reference.

Things to come back to:

- Kubernetes resource states - shown in badges - need to re-work this to support 18n

**Comment by bisht-richa** [comment]
Mostly badges, workspaces, names directly from Ids, links, and descriptions are not having localized strings.
Needs someone's help to fix these sections:

Cluster Explorer 
  projectsnamespaces
  Nodes
Global setting
   Settings page - Headings and URL
   Feature Flags page - table badge and descriptions
Users & Authentication
  Roles page  -  Page Users - Badge user name column in table
Cluster Management
  Page cluster  --- Table badge, cluster name and explore button
  Page Repositories --- table badge, type, and branch name
Continuous Delivery
  Advance > Workspaces --- Table badge and workspaces name
