### ISSUE TITLE
Workload columns fail to load on group by or project/namespace filter change

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6503]
**Setup**
- Rancher version: 2.6-head

**Describe the bug**
The delayed load columns of restarts and health fail to load if the user
- toggles between flat list and group by namespace
- changes the project/namespace filter

**To Reproduce**
- Nav to workloads list (see both columns load correctly
- change either the flat list/group by button OR the project/namespace filter
- New rows are shown, however restarts and health columns never load

![image](https://user-images.githubusercontent.com/18697775/181047856-18a765b9-09ff-4db6-a20d-1e1dc25e43f2.png)

**Comment by markusewalker** [comment]
Verified that this is addressed in `v2.6-head` https://github.com/rancher/rancher/commit/6629e3eeb746dc80c703eb628eb8e8009505730f.

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigated to the UI in a browser.
2. Navigated to Cluster Explorer > local > Workload.
3. Clicked on `Flat List` and verified that the `Restarts` and `Health` columns loaded as expected:
![image](https://user-images.githubusercontent.com/52591819/182259713-5441e0c8-1547-49f4-8d57-9bedaea83a5c.png)
