### ISSUE TITLE
Improve load time of dashboard home and cluster dashboard pages

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6504]
- reduce sequential requests
- ensure resources are un-watched
- don't block page load on all resource types

**Comment by git-ival** [comment]
LGTM, tested according to detail in #6506 

https://user-images.githubusercontent.com/85186645/184253077-d0c9378b-2e88-476a-8226-6c41207fbd5b.mp4


https://user-images.githubusercontent.com/85186645/184253091-f5f7d313-b601-457f-b83a-c4ed477be426.mp4
