### ISSUE TITLE
Research the existing sorting capabilities in the UI, find out what needs to be shifted to Steve

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6509]
In order to load fewer resources in the UI, the UI will need paginated results from Steve, and in order to preserve the ability to sort lists of resources while also having pagination, Steve will need to sort the results on the server side before sending a page to the UI.

There is a backend issue about adding the sorting capabilities to Steve https://github.com/rancher/rancher/issues/38427, but we still need to update it with a list of all the specific sorting features that we need to be added to Steve.

We should take time to:

- Go through our list views and make a list of the columns that allow sorting.
- Take note of which columns are calculated with computed properties, especially expensive computed properties that require the UI to loop over a list of resources. If we find expensive computed properties, we should look into having Steve provide them along with the original resource list.
- Take note of columns calculated with expensive getters in the resource models, for the same reason as above.
- Take note of columns that are calculated with JSONPath and look into replacing those with functions because functions are faster.

**Comment by gaktive** [comment]
We may push this out until the backend comes up with their own pagination. For 2.7.0, we'll have our own UI implementation and we'll learn more about what needs to be done there. I'll link to the other ticket once I find it.

**Comment by catherineluse** [comment]
Closing as a duplicate since https://github.com/rancher/dashboard/issues/6541 covers the same topic.
