### ISSUE TITLE
Separate unwatch from data deletion

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6512]
This PR https://github.com/rancher/dashboard/pull/6432 introduced the `forgetType` mutation, which allows a resource type to be removed from the store and unwatched at the same time.

It should improve performance to unwatch resources that are not currently rendered on the page. However, the obstacle to adding the `forgetType` optimization to every list view in Rancher is that it does not separate resource unwatching from deletion. This means that if a user goes to the workload page, then navigates away from it, the workloads will be unwatched, but when they return to the workload page, they have to watch a loading indicator again.

Ideally, the user should be able to return to the workload page and immediately see the same results as before, which will be slightly stale, but still better than seeing nothing but a loading indicator. The resources will still be refetched, as the watcher will be turned back on as soon as the list is rendered. Then the list will update as soon as the refreshed data is in the store.

When this change is implemented, then we will be able to do `forgetType` for all list views. We will be able to unwatch all types that are no longer being rendered on the screen without making the user watch loading indicators for resources that were already fetched.

Neil noted that there is already a flag that says if we have fetched all of a certain type and that we may need to change how that works in order to implement this change.

Related issue: https://github.com/rancher/dashboard/issues/6431

**Comment by richard-cox** [comment]
I don't think we should blanket retain data. Forgetting a type was done to both reduce churn from socket updates and decrease memory footprint of items in the store. If we retain data we lose the second benefit.

There's a new setting coming in that changes the behaviour of lists when there's too many entries (switch from optimal get all/watch all to sub-optimal sequential loading of pages and manual refresh). I think we should tie that setting in to whether the data is retained (possible also unwatched?).

The flag Neil refers to is `haveAll` which ties in with the `finalAll` action and whether that kicks of a https request or not.

**Comment by catherineluse** [comment]
> I don't think we should blanket retain data.

It's not all or nothing - if we just retained the first page of data, it could decrease the loading indicator time while keeping the size of retained data relatively small.

**Comment by catherineluse** [comment]
I think we should do an experiment to figure out how much memory consumption comes from retaining data vs. how much comes from watching resources.

**Comment by gaktive** [comment]
This may be obsolete once the backend pagination work comes in but we'll keep an eye on this once that lands.

**Comment by catherineluse** [comment]
I'm closing this issue because the backend pagination work is expected to make it unnecessary. Can reopen if needed.
