### ISSUE TITLE
Exclude unneeded namespaces from API calls

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6515]
Currently the UI usually fetches all resources of a given type in a cluster. To reduce excessive memory consumption in the UI, we should fetch resources only from the currently selected namespaces so that the UI doesn't have to filter resources by namespace.

There is a kubectl command that can get resources from a subset of namespaces in a cluster:
```
kubectl get pods -A --field-selector metadata.namespace!=default,metadata.namespace!=cattle-system 
```
The catch is that the field selector operators do not support OR or IN operations. So you can't provide only the namespaces you do want - you can only specify namespaces you don't want.

So, because the only way to fetch resources in a subset of namespaces with one API call is to use resource field selectors to exclude namespaces, I want to try creating a new part of state in Vuex called `inactiveNamespaceCache`, which would be the opposite of `activeNamespaceCache`. This list of inactive namespaces can be used to exclude unneeded namespaces from API calls in `findAll`.

The backend still has to select all resources and filter them down, but this method should still cut down on excess scripting and memory consumption in the browser.

**Comment by richard-cox** [comment]
This describes a solution rather than the issue, being that we need to limit the amount of resources we fetch/watch given the namespace filter, which tbh I thought https://github.com/rancher/dashboard/issues/6483 was (after rereading that just applies to rows in tables)

Using a block list to achieve this could lead to requests with 1000s in. Apart from the 'user namespace' style filter it's more likely the number of namespaces selected by the user will be less than those not selected. 

This requires some more thought before starting.

**Comment by catherineluse** [comment]
> Using a block list to achieve this could lead to requests with 1000s in.

We could mitigate this by picking an arbitrary number of namespaces, for example, 5 or 10. If the user has selected fewer than that number, we could make separate API calls to fetch resources in those individual namespaces.

I understand https://github.com/rancher/dashboard/issues/6483 about UX, specifically about changing the default view for cluster explorer. Currently we load all resources in the cluster by default, but another option as described in that issue is to just show nothing until the user selects something. Even if the filtering is done client side, it could still help just to render fewer table rows.

But even if the user selects a namespace or project, the fact that we load excess data is probably a bigger issue. The options are basically -

- Fetch resources from individual namespaces (which we almost never do, since we default to `findAll`
- Exclude unneeded namespace using resource selector fields
- Offload the ability to fetch from a subset of namespaces to a web worker
- Ask for Steve to be enhanced to allow fetching from a subset of namespaces

The first two would be easier to implement, but even the latter two option are going to be somewhat hacky because upstream Kubernetes is never going to support it.

**Comment by gaktive** [comment]
Based on triage, we need to think about this some more and see how other tickets from @Sean-McQ and @richard-cox address this first.

**Comment by catherineluse** [comment]
Closing this issue because it goes against the grain of what is supported by upstream Kubernetes.
