### ISSUE TITLE
Investigate Cluster Manager / Ember performance

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6518]
Investigate the performance of the old UI when
- selecting a project containing a large number of deployments (2000) and/or namespaces. How do pages like workloads perform? Is it comparable with the dashboard (with a similar total number of resources)

**Comment by catherineluse** [comment]
Alex compared dashboard vs. Ember performance with details here https://github.com/rancher/rancher/issues/38468#issuecomment-1216431503

**Comment by catherineluse** [comment]
I've added a couple of comparisons as well - https://github.com/rancher/rancher/issues/38468#issuecomment-1220112331 That test does confirm that when resources are evenly distributed across projects, Norman is much faster because it limits the result to a certain project.

Next I can add a few more comparisons in a setup with all the resources in one project so that Norman and Steve would return a comparable number of resources.

**Comment by gaktive** [comment]
@aalves08 may have done this already. He'll review and update this ticket.

**Comment by aalves08** [comment]
From my side, to sum it up, this is the data gathered related to the performance comparison between the old UI and 2.6.7

FCP -> First Contentful Painting
LCP -> Large Contentful Painting

**2.6.7**
FCP - 9s
LCP - 25s
Memory - starts around 180mb, ends at 829mb

doing all the requests for workloads, about 3700 items, (uses K8s api) takes on average 21s.

**Old UI**
FCP - 18s
LCP - 18s
Memory - starts around 113mb, ends at 80mb

doing all the requests for workloads, about 3700 items, (uses norman V3 api) takes on average 7s.

**Conclusion**
Quite a bit of overhead in terms of memory footprint, but also we have a much more complex table (in terms of dom nodes) on 2.6.7 with complex relationship with pods and also a big system in terms of reactivity with a load of resources being fetched on the load of the app.

There is a big difference in terms of api performance between Norman and K8s, with K8s taking 14s more than norman.

Analysing the FCP times, even though we are outperformed in terms of API by Norman on 2.6.7 (VueJS), we can see that the FCP time is much quicker with VueJS, proving that the technology used is better performant that Ember.

FYI @nwmac @richard-cox @gaktive
