### ISSUE TITLE
Requests for chart logos can fail, or block further requests due to spam/pending

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6520]
**Setup**
- Rancher version: 2.6-head

**Describe the bug**
- Charts page (and to a lesser extent cluster tools page) shows cards for charts
- Those cards show the chart logos which are roughly `k8s/clusters/c-m-v7cj4r28/v1/catalog.cattle.io.clusterrepos/rancher-partner-charts?chartName=kong&link=icon&version=2.3.1`
- On DO these seem fine, in OpenStack these stay as pending for a long time and then fail
- The pending states cause throttling of further http requests causing a blockage for other requests (?)

Need to investigate if we can handle this scenario better
- Possibly fail earlier when fetching the logos?

**Comment by nwmac** [comment]
Won't fix - not seen this be an issue in practice
