### ISSUE TITLE
Namespace filter is not applied on page load

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6525]
**Setup**
- Rancher version: 2.6-head (2.6.7ish)

**Describe the bug**
The namespace filter is not applied to either side nav counts or list rows when refreshing or navigating to the cluster

**To Reproduce**
Refresh
- Nav to pods list, filter by a namespace (note side nav counts and rows)
- Refresh 
- side nav counts and rows show all resources, not those of filter

Nav
- Nav to pods list, filter by a namespace (note side nav counts and rows)
- Nav to dashboard home page 
- Refresh
- Nav to cluster pods page
- side nav counts and rows show all resources, not those of filter

**Additional context**
- This works fine in 2.6.5
- I was debugging this as part of another PR. In `getActiveNamespaces` `getters.isAllNamespaces` is true even though there are `state.namespaceFilters` values. Note - in isAllNamespaces we check for rows with prefix of `namespace` and not `ns`. I thought this was the route issue, however if you add another NS to the filter it works fine

Related PRs
- https://github.com/rancher/dashboard/pull/6261
- https://github.com/rancher/dashboard/pull/6524
- https://github.com/rancher/dashboard/pull/6523

**Comment by catherineluse** [comment]
There's a timing issue. The `getActiveNamespaces` getter runs after the namespace filters are populated, so it initially does not know what filters are active.

**Comment by gaktive** [comment]
Internal reference: SURE-5066

**Comment by richard-cox** [comment]
@gaktive SURE-5066 is https://github.com/rancher/dashboard/issues/5088

**Comment by gaktive** [comment]
Thanks @richard-cox for the clarification; we do have a few issues around the same area :)

**Comment by slickwarren** [comment]
tested on v2.6-head (0c0a37a0):
namespaces filter is now applying on page load
* Nav to pods list, filter by a namespace (note side nav counts and rows)
* Refresh
* filtered results are shown
