### ISSUE TITLE
Improve error messages for invalid Azure credentials

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6531]
To reproduce, 

1. Go to Cluster Management > Cloud Credentials
2. Click Create
3. Click Azure
4. Enter valid credentials
5. Get error saying authentication test failed:
<img width="1129" alt="Screen Shot 2022-07-27 at 4 20 40 PM" src="https://user-images.githubusercontent.com/20599230/181389028-9c0a5e07-3f12-48ea-b780-f5f5f6dd0bfb.png">

I also tried to create cloud credentials in the AKS cluster provisioning form and it gave a lot of errors about JSON syntax:
<img width="930" alt="Screen Shot 2022-07-27 at 4 10 43 PM" src="https://user-images.githubusercontent.com/20599230/181389587-040d546d-80f0-4abb-886a-f1c4a2af597e.png">

This is probably operator error on my end, but those syntax errors make it look like something is broken. Can someone confirm they can create cloud credentials?

**Comment by kwwii** [comment]
Although it is not easy to find how to create a secret (or the client ID), I have found things labelled Client ID, Subscription ID, and I created a secret and used the Client Secret value. This always leads to an authentication error as described above. 

Perhaps someone who has done this before should test it to be sure?

**Comment by kwwii** [comment]
Apprently operator error is very likely. I have successfully created credentials with the required fields

**Comment by catherineluse** [comment]
What did the problem turn out to be? could it be turned into a better error message?

**Comment by kwwii** [comment]
In the end, it was a problem with how I set up things on the Azure side. As I was just trying to test I didn't go into detail on setting up Azure. Jordon provided an Azure that was properly configured and everything worked as expected. Ideally, we would give more specific information about what is failing but I get the feeling that we cannot get anything more specific from Azure.

I think we can close this, as it does work, if you know how to set up Azure properly

**Comment by nwmac** [comment]
We should provide a link to the docs. I think the docs might be slightly out of date was well, so we should check and work with docs team as necessary.

**Comment by nwmac** [comment]
Work was done to improve the handling of errors here, so I don't think this is an issue.
