### ISSUE TITLE
Performance: Server-side-like pagination via web worker  (step 4)

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6541]
Instead of holding all resources in the VueX store, only hold the resources for the current page in a list.

A web worker presents a paginated resource UI to the UI - it fetches all resources of a given type and processes the web socket messages to keep those up to date.

When a list is requested by the UI, the web worker will sort, filter and paginate the resources required and return this back to the UI - which can store if in the VueX store.

When updates come in, the web worker processes those, determines if they affect any active pages, and if so, sends the updates to the UI which then updates the VueX store, resulting in the same reactivity we have now, so the list will auto update.

When a user leaves a page, the lists on it are removed and the web worker stops sending updates through - but keeps processing updates for the resources it holds (We may choose not to keep all resources in memory at a later time).

**Additional context**
- Step 1 is https://github.com/rancher/dashboard/issues/7894
- Step 2 is https://github.com/rancher/dashboard/issues/7895
- Step 3 is https://github.com/rancher/dashboard/issues/7896
- This is step 4

**Comment by Sean-McQ** [comment]
@catherineluse I'm not hydrating the list resources inside of the worker but that is baked into the mutation I use to load it into the store when I pass it to the UI thread. We could potentially bake the hydration step into the getter so that we're not storing the full class instances in there or preferably only instantiate the various row resources in the component that requests it and avoid having the store hydrate anything (in the case of rows).

**Comment by gaktive** [comment]
This ticket will be split to allow for the work for the Q1 release to be deliverable but then have additional work for a subsequent release.

**Comment by richard-cox** [comment]
Some of the backend changes have already been implemented in 2.7.2
- SURE-5387

Some are incoming in 2.7 Q2
- SURE-5698
  - Adds required searching
    - Development note - only single search term is supported. searching by multiple terms locally seems broken anyway https://github.com/rancher/dashboard/issues/8042
  - Filtering by one or more projects or namespaces
    - Development note - NOT is supported, aka filter by NOT list of system namespaces (i.e. user namespaces)
    - Development note - a maximum of 50 individual namespaces are expected. We need to handle this in UI

Some are TBD
- SURE-5733
  - Filtering/Sorting by aggregated fields (for instance Deployment Pod restarts
- SURE-5735
  - Pagination of virtual resource (for instance Workloads)
- SURE-5734
  - Socket updates for paginated lists

**Comment by richard-cox** [comment]
Given change in direction, bumping out to 2.7 Q3. We should look at this work alongside https://github.com/rancher/dashboard/pull/8507

**Comment by gaktive** [comment]
Need to re-evaluate this ticket as part of our existing performance work. This didn't land but the backend plans changed.

**Comment by nwmac** [comment]
May not do this if we can get server-side pagination
