### ISSUE TITLE
UI Plugin Support

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6542]
Further work to be broken out to separate issues:

- Create GitHub action to publish npm packages when the appropriate package.json file changes
- Plugin catalog and installation - consider dev experience
- Update UI to load plugins at startup - make API request and load plugins
- Move more code out of shell (TBD)
- Allow Cloud Provider to be added as a plugin
- Create example plugins repository with examples - rancher/dashboard#6662
- Extract Harvester Cluster as a plugin
- Extract Fleet as a plugin (This one only?)
- Add docs for plugins
- Harvester dynamic loading
- Validate the code loading with code splitting - check minimum code is loaded for a plugin
- Test and use
- E2E tests
- Plugin API
- Think about plugin compatibility etc

Stretch, maybe post next release:

- Side-navigation re-work to simplify nav
- Extract Explorer as a plugin
- Extract Cluster Management as a plugin

**Comment by AndrewHoffmanQA** [comment]
per conversation with @MKlimuszka - ignore the body/specifics of this ticket, its an Epic lvl ticket that wasnt developed and now acts as a placeholder for the status of the entire feature.

 QA  to move this ticket to 'done' once QA has completed both front end and back end regression suites and they have been peer reviewed by the corresponding dev teams

Backend has signed off on their library. 

UI has been asked for review 10/20 in the ui extensions slack channel.

**Comment by AndrewHoffmanQA** [comment]
QA has finished testing activities for UI Extensions

both front end and backend libraries have been peer reviewed, executed and passed as well as a half-day of adhoc testing. 

full test suite can be found here. https://confluence.suse.com/display/RANQA/UI+plugin+-QA+notes+Test+plan

bugs opened 
https://github.com/rancher/rancher/issues/39323
https://github.com/rancher/rancher/issues/39301
https://github.com/rancher/dashboard/issues/7208
https://github.com/rancher/rancher/issues/39357
https://github.com/rancher/dashboard/issues/7239

moving this ticket to 'done'
