### ISSUE TITLE
Add diagnostic page to UI

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6544]
To help diagnose issues, have a page that shows some useful data:

- Browser, Browser version etc, OS, Memory (client info)
- Counts of clusters and counts within clusters to get info on scale of deployment
- Errors and warnings logged to the browser console
- Browser memory usage
- VueX store info for cluster - what has been loaded into the store etc ...
- More TBD

Would be good to display this info visually but also be able to download a text of json file with the data in (json might be easier, as this could drive UI directly).

Suggest:

- Button on about page to go to new diagnostic page
- Creates a JSON model include the basic data above:
   - Versions, browser info etc
- Has a button to Analyse Clusters
   - This will run through each cluster, get the counts and store that (perhaps only where the counts are not 0)
   - Have a checkbox with the button 'Check response times' - when checked (default), as it checks each cluster's counts, it performs a fetch for the top 10 resources with the highest counts) and times how long that takes, and records that too
- UI shows display of the JSON model
- JSON can be downloaded from the UI so that it can be attached to support tickets, or GitHub issues

**Comment by aalves08** [comment]
Possible release note:
Added diagnostics page to allow users to gather data from their systems to append to any issues filed for rancher, accessible via the about page. See https://github.com/rancher/dashboard/issues/6544.

FYI @richard-cox

**Comment by MSpencer87** [comment]
_**Verified on 2.6.7-rc9**_

Steps to verify:
1. Bring up Rancher on 2.6.7-rc9
2. Navigate to About page https://<rancher_url>/dashboard/about (Main Menu->Click the version link)
3. Diagnostics button present, selecting button links to https://<rancher_url>/dashboard/diagnostic
4. View that page is visible with Light, Dark and Auto preferences set
5. Select the Download Data button with the checkbox for Make additional requests un-selected
6. Verify the file is downloaded, verify the JSON is properly formatted
7. Select the Download Data button with the checkbox for Make additional requests selected
8. Verify the file is downloaded, verify the JSON is properly formatted (my file was ~3k lines longer than with additional requests selected)
<img width="1718" alt="Screen Shot 2022-08-11 at 3 00 57 PM" src="https://user-images.githubusercontent.com/6477538/184263495-977bbced-0d83-4657-81ab-07a82d6c7983.png">

![Screen Shot 2022-08-11 at 5 20 20 PM](https://user-images.githubusercontent.com/6477538/184263498-5cfd0f2c-921d-4a61-aa82-1ad492ead248.png)
