### ISSUE TITLE
[2.5.16] Remove RKE1 Windows provisioning due to EOL

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#6549]
backport of: https://github.com/rancher/dashboard/issues/5995#issue-1242431995

please have the statement as the following for 2.5:
```
Windows support is being deprecated for RKE1. We suggest migrating to RKE2 on Rancher 2.6.5+.
```

**Comment by codyrancher** [comment]
This was backported in https://github.com/rancher/ui/pull/4880

**Comment by slickwarren** [comment]
hello, could you please update the message to the following:
```
Windows support is being deprecated for RKE1. We suggest migrating to RKE2 on Rancher 2.6.5+.
```

**Comment by slickwarren** [comment]
tested on v2.5-head (788262e40f0e7029a8f4e4995e9bd32cc6fd8254):
The following message appears when creating an rke1 custom cluster: 
```
Windows support is being deprecated for RKE1. We suggest migrating to RKE2 on Rancher 2.6.5+.
```
however, the registration page does not have any message regarding the deprecation.  
I don't think the current messaging on the `global` page makes sense to have there. Can we remove that?

and can we add the same wording to the registration page `Windows support is being deprecated for RKE1. We suggest migrating to RKE2 on Rancher 2.6.5+.`


missing message:
![Screen Shot 2022-08-11 at 9 44 19 AM](https://user-images.githubusercontent.com/16691014/184190707-8ae784b0-897c-4436-a8a2-0c647e9f422c.png)


request to remove message from:
![Screen Shot 2022-08-11 at 9 53 10 AM](https://user-images.githubusercontent.com/16691014/184190525-9d9fc046-1b39-4d60-a941-abbb2ba7c922.png)

could also add message here:
![Screen Shot 2022-08-11 at 9 45 05 AM](https://user-images.githubusercontent.com/16691014/184190613-97cbf543-c6b1-41d4-b2c8-a7771fb9df5d.png)

**Comment by gaktive** [comment]
@catherineluse will pick up this last bit for 2.5.16 and ensure that things line up with what @slickwarren brought up.

**Comment by slickwarren** [comment]
tested on v2.5-head (788262e40f0e7029a8f4e4995e9bd32cc6fd8254):
* deploy custom cluster with no windows capability - no warnings show up (pass)
* custom cluster with windows enabled - the following warnings show up:
  * on the global `clusters` page -- pass
  * on the registration page immediately after creation and on edit -- pass 
  * on the cluster dashboard page -- pass
