### ISSUE TITLE
Plugins: Add Plugin catalog view

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6555]
The current Plugins page accessible from the side-nav is there for development.

Once the backend is in place, this should operate in a similar way to cluster tools - there will be be annotation on a chart to say if it is a UI plugin - the plugins page should list all of the charts that are plugins.

We can go ahead and put this in place now and fake a repository of plugins with the annotations for testing.

**Comment by ronhorton** [comment]
Complete - This was verified with extensions testing.
