### ISSUE TITLE
Namespace filter doesn't filter resources by namespaces and lists resources in all namespaces 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#6557]
Setup

Rancher version: 2.6-head 2587e6a
Browser type & version: Chrome

**Describe the bug**
When we select a namespace in the namespace filter, resources are not filtered by namespaces and resources in all namespaces are listed.

**To Reproduce**
1. Create a rancher server on v2.6-head
2. Create a downstream cluster or use the local cluster
3. Navigate to cluster explorer of the local/downstream cluster workloads
4. In the namespace filter >> select any namespace

**Result**
Notice the resources in all namespaces are listed

**Expected Result**
Expected only resources in the selected namespace to be listed

**Screenshots**
Notice the namespace filter has only the namespace `ingress-nginx` selected but the resources in all namespaces are listed.

<img width="500" alt="namespace-filter" src="https://user-images.githubusercontent.com/38144301/182002468-96cfac79-ec28-46a2-a55e-c24f0501884b.png">

**Additional context**
Workaround: Select the project the namespace is in. For example ingress-nginx is in system project. Select the system project and then select the desired namespace, only the resources in that namespaces will be listed.
This is seen happening when we select the `All namespaces` option and then select only the desired namespace.

**Comment by richard-cox** [comment]
I thought this was related to my [PR](https://github.com/rancher/dashboard/pull/6524) which uncovered [this](https://github.com/rancher/dashboard/issues/6525) issue, however I could reproduce strangeness when checking out the commit before. Not sure if there's been further regress since that PR was branched, or I'm rubbish at testing.

**Comment by anupama2501** [comment]
Verified on v2.6-head 2f85f56
Resources are listed as per the namespace filter selected
