### ISSUE TITLE
Unable to create a Service

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6559]
**on 2.6.5-rc5**

- Create a Headless Service
- Error seen: `Service "service-1" is invalid: spec.ports[0].targetPort: Invalid value: "40": must contain at least one letter or number (a-z, 0-9)`
<img width="716" alt="Screen Shot 2022-07-31 at 10 28 40 AM" src="https://user-images.githubusercontent.com/26032343/182038319-d70f4958-c4a3-4bce-a7d0-9b13e43a839a.png">

- Request Payload
```
ports: [{name: "myport", port: 42, protocol: "TCP", targetPort: "40"}]
0: {name: "myport", port: 42, protocol: "TCP", targetPort: "40"}
name: "myport"
port: 42
protocol: "TCP"
targetPort: "40"
```

**Expected:**
UI Should send targetPort as `40` instead of `"40"`

**Comment by Sean-McQ** [comment]
I believe this might be fixed by the PR below from 6 days ago as I don't seem to be able to reproduce it with the latest code from the master branch.

https://github.com/rancher/dashboard/pull/6514

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `20d6e22`**

- I am able to create a headless service.
- Request payload now contains:

```
0: {name: "test-01", port: 42, protocol: "TCP", targetPort: 42}
name: "test-01"
port: 42
protocol: "TCP"
targetPort: 42
```
