### ISSUE TITLE
First time accessing Continuous Delivery --> Clusters, Cluster Count is wrong and Namespaces dropdown not present

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#6572]
**Setup**
- Rancher version: v2.6-head commit ID 20d6e22
- Browser type & version: Brave - v1.41.100

**Describe the bug**
The first time a user accesses the Continuous Delivery --> Clusters page, the cluster count is defaulted to 0, and the Namespaces dropdown is not present in the UI

**To Reproduce**
1. Deploy a downstream cluster
2. Navigate to Continuous Delivery page
- Note that the Cluster count in the left side panel is 0
3. Navigate to the Clusters page
- Note: The Clusters grid is empty
- Note: The Namespace Dropdown is not present in the UI
4. Refresh the page
- Note: The Clusters grid is now populated with the downstream cluster, but the Namespaces dropdown is still not present
5. Log out of Rancher, and then back in
6. Navigate to the Continuous Delivery --> Clusters page
- Note: The Namespaces dropdown is now present in top right of the UI

**Expected Result**
The Clusters count must be accurate, the Clusters grid on the Continuous Delivery --> Clusters page must have the correct cluster information, and the Namespaces dropdown list must be present in the UI at all times on the Continuous Delivery --> Clusters page.

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/182407831-5a145f5d-7f3d-4c00-95c6-0263a5db2aa0.png)
![image](https://user-images.githubusercontent.com/13294321/182407970-5792e2a1-6dc4-4ae9-bbb2-5bd257870f46.png)

**Comment by jameson-mcghee** [comment]
@aalves08, this issue is still reproducing on v2.6-head commit ID db2205a.  Setting this ticket to Reopened.

![image.png](https://zube.io/files/rancher/19d426c7910a41ac1cd8c9188fd677cf-image.png)

**Comment by aalves08** [comment]
FYI @richard-cox

**Comment by aalves08** [comment]
@jameson-mcghee @richard-cox has been leading this fix but, nevertheless, we merged stuff to address this issue on Friday. Are you using a RC version or dashboard -head?

**Comment by gaktive** [comment]
Do note that Brave is the browser being used here. What is the behaviour in Firefox/Chrome?

**Comment by richard-cox** [comment]
Minor update - We can't reproduce this on `-head` and need further information. As per Alex's request, @jameson-mcghee can you confirm you're not on an `RC` build, and if not can we get access to the system where you see it?

**Comment by richard-cox** [comment]
I've given this another try, no joy. With the latest frontend `e9e88db` on firefox from the setup screen to `Continuous Delivery` the filter and counts appear and i can change the filter which changes the counts

![image](https://user-images.githubusercontent.com/18697775/183467861-bce8a527-1343-4269-8fed-c790c9a6f900.png).

@jameson-mcghee Was the UI accessed promptly before all the fleet deployments/resources were ready? Did everything work fine after a while and a refresh?

**Comment by aalves08** [comment]
@jameson-mcghee working fine on Brave. Fresh new system, `-head` for both frontend and backend. Entered the system, went to `Fleet`, `workspace` filter is populated by default (fix applied https://github.com/rancher/dashboard/pull/6586) and we can change it and clusters list view is reactive to changes. Can you confirm please?

**Starts with `fleet-default` value**
<img width="1312" alt="Screenshot 2022-08-09 at 09 39 21" src="https://user-images.githubusercontent.com/97888974/183604885-0ac9ef9b-0a5b-49a0-a474-8769cd7a8929.png">

**Switching to `fleet-local` we get the expected outcome**
<img width="1312" alt="Screenshot 2022-08-09 at 09 39 23" src="https://user-images.githubusercontent.com/97888974/183604871-58d541b2-fddf-4763-843c-b0c1dd979e79.png">


FYI @gaktive @richard-cox

**Comment by jameson-mcghee** [comment]
@aalves08 @richard-cox @gaktive I just spun up a brand new Rancher server on v2.6-head with Commit ID cd97f6f and did my testing on Google Chrome using the most recent version (v104.0.5112.81).
![image](https://user-images.githubusercontent.com/13294321/183714437-6812f238-6495-4740-a310-78720b6e7ed1.png)

During testing, I was able to confirm that on this newest commit, I am no longer seeing an incorrect value for the Clusters count, and I am able to see the fleet-default clusters in the grid without having to refresh the page: 
![image](https://user-images.githubusercontent.com/13294321/183714725-3bfc9115-5506-4903-a32e-5ffb48194bc3.png)

However, even after refreshing the page several times, and waiting several minutes, while testing on Google Chrome, I was still not able to see the Namespace dropdown on the page:
![image](https://user-images.githubusercontent.com/13294321/183714937-3cdcec9d-edf8-4b6b-af61-491c98e3d4e6.png)

cc @sowmyav27

**Comment by gaktive** [comment]
Upon discussion, this has existed in 2.6.6 so it's not a regression. It's an edge case of sorts and not a release blocker so upon agreement, we'll allow more time to investigate this for 2.7.0.

**Comment by jameson-mcghee** [comment]
I have confirmed that the Namespace dropdown issue can be reproduced in v2.6.6.
![image](https://user-images.githubusercontent.com/13294321/183722591-14930092-68de-4a07-8b2c-b61bd80f42d8.png)

**Comment by jameson-mcghee** [comment]
**Intended Test Setup**
-	Rancher version(s): v2.6-head
-	Browser type & version: Brave & Most Current
-	Rancher Host: EC2 (Jenkins Job)
-	Rancher Setup:
o	RANCHER_HA_CERT_OPTION: byo-valid
o	RKE_VERSION: 1.3.13-rc4
o	AWS_VOLUME_SIZE: 20
o	AWS_AMI: ami-066f14e43aebc7472
o	AWS_SECURITY_GROUPS: sg-0e753fd5550206e55 (open-all)
o	AWS_INSTANCE_TYPE: t3a.xlarge
o	AWS_VPC: vpc-bfccf4d7
o	AWS_SUBNET: subnet-ee8cac86
o	AWS_REGION: us-east-2
-	Deployment Type: Helm
-	User Permission: Admin and Standard Users

**Test Approach**
-	Verify that when I create a downstream cluster, that the Clusters value is increased correctly
-	Verify that when I delete a downstream cluster, that the Clusters value is decreased correctly
-	Verify that when I access the Continuous Delivery page for the first time (without logging out/in from Rancher), that the Namespace dropdown list is present on the page
-	Verify that on the Continuous Delivery page for fleet-default, when there are no downstream clusters. that the grid is empty, but that the fleet-local grid has the local cluster listed
-	Verify that on the Continuous Delivery page for fleet-default, when a downstream cluster has been created. that the grid contains all downstream clusters created, and that the fleet-local grid has the local cluster listed

**Comment by jameson-mcghee** [comment]
I have verified that this issue is no longer reproducible on `v2.7-head` (Commit ID: 48d1f8e). Therefore I am closing this ticket.
