### ISSUE TITLE
[BUG] RKE2 `Use tokens for metadata` and `Allow access to EC2 metadata` options do not work

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/dashboard#6573]
Root issue: https://github.com/rancher/rancher/issues/38405
**Setup**
- Rancher version: v2.6.7 and older
- Browser type & version: test on latest Chrome, but applicable to all browsers

**Describe the bug**
When creating RKE2 clusters which must adhere to a strict [IMDSv2 AWS policy](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) both the `Use tokens for metadata` and `Allow access to EC2 metadata` check boxes must be selected for the instance to provision successfully. This issue represents two bugs regarding the selection of those check boxes 

1. The `Use tokens for metadata` check box is initially grayed out, implying that it is enabled by default, however I cannot see that field sent in the POST request when provisioning a cluster. When you select `Allow access to EC2 metadata` the `Use tokens for metadata` box will be selectable, but this leads to bug 2

2. When enabling `Allow access to EC2 metadata` or `Use tokens for metadata` the UI will report the following type error.
```
Amazonec2Config.rke-machine-config.cattle.io "nc-haffel-button-tests-pool1-jqxsr" is invalid: [httpTokens: Invalid value: "boolean": httpTokens in body must be of type string: "boolean", httpEndpoint: Invalid value: "boolean": httpEndpoint in body must be of type string: "boolean"]
```
This error occurs when one box is selected or when both boxes are selected (above error is when both are selected). When this error is encountered the cluster will not begin provisioning. 

**To Reproduce**
+ Open Cluster-management 
+ Click Create 
+ Enable `RKE2/K3s`
+ Select `Amazon EC2`
+ Create a cloud-credential if needed
+ Under `VPC/Subnet` click `Show Advanced`
+ Observe that `Use tokens for metadata` is grayed out
+ Select `Allow access to EC2 metadata`
   + Observe that `Use tokens for metadata` is no longer grayed out 
+ Select either `Allow access to EC2 metadata`, `Use tokens for metadata` or both
+ Add a Cluster Name / VPC and press Create

**Result**

Observe error message at the top of the page stating the error message mentioned above. 

**Expected Result**
The error message does not appear and the cluster begins provisioning

**Screenshots**

![Screen Shot 2022-08-02 at 11 05 26 AM](https://user-images.githubusercontent.com/25062254/182407848-39989fe6-5b56-4b8b-934b-452c0d8030d3.png)

**Additional context**
IMDSv2 is a security policy used by several of our customers, instances will fail to create if both the `httpToken` and `httpEndpoint` options are not set. An issue was discovered in RKE1 where these fields were not set when creating spot-instances. This error was discovered while testing similar functionality for RKE2.

**Comment by gaktive** [comment]
Hopefully this is just as easy as switching from Boolean to String.

**Comment by slickwarren** [comment]
tested on rancher v2.6-head (68215bc):
* UI now allows both options to be selected without any errors on the UI nor on the cluster. The cluster now comes up active
