### ISSUE TITLE
Performance: Incremental loading requests won't cause dispatch to fail

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6574]
**Setup**
- Rancher version: 2.6.7
- Browser type & version:

**Describe the bug**
- HTTP failures in new incremental loading feature won't be caught
- This is due to missing `await` for 2x `dispatch('loadDataPage'`
- Adding `await` to these dispatches however blocks the list from showing rows until all requests have completed, which defeats the whole point

Brought in by https://github.com/rancher/dashboard/pull/6543

**Comment by nwmac** [comment]
We will remove incremental loading when we have server-side pagination - won't fix
