### ISSUE TITLE
Deployment (and other Workloads) Views should include latest Events without any additional click

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6579]
Internal reference: SURE-3162
Reported in 2.6.x

Within the UI for 2.5.x, it was possible to see the latest events on the views for Deployments and other Workloads without additional clicking. With 2.6.x, it is now required to click on the Conditions tab. A user would like to restore part of the 2.5.x behaviour so that it's as easy as use as it was in the past.

**Comment by nwmac** [comment]
This can be done with the 'Recent Events' tab
