### ISSUE TITLE
Add cluster change indication icons or signal on Rancher UI 2.6 to shows which downstream cluster needs to be updated

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6580]
Internal reference: SURE-5031
Reported in 2.6.6

Request description:
Add for example yellow Icons on Rancher 2.6 UI indicates about the need for cluster updates like it was on old Rancher UI. 

Actual behavior:
Nothing indicates about the need for cluster updates in new UI.

Expected behavior:
Show some for example yellow Icons which cluster need to be update after for exmample a RKE template changes. Like it was on the old Rancher UI see attached screen shots.

Workaround:
Use the old UI with the /g hack in Rancher URL. This allows the user to see what clusters need to be updated, reducing workload on them.

Additional notes:

Missing yellow Icons on Rancher 2.6 UI indicates about the need for cluster updates.
In Rancher 2.5 on creating a new cluster template, yellow icons were shown in UI.
So it was possible to see what clusters need to be updated.
On Rancher 2.6 we could not find that possibility.
Is there a way to see what clusters need to be updated after a template change?

Screenshot:
![rancher25.png](https://zube.io/files/rancher/11b05ebcb3054597fe694ec97bfa720f-rancher25.png)

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head f808c6a
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE1

----------

### Testing: ###
Tested this issue with the following steps:
1. Create an RKE1 Template
2. Create a 1-node RKE1 cluster from this template
3. Go to the cluster list page and validate that there is no upgrade icon
4. Go to the cluster details page and validate that there is not an upgrade icon
5. Add a new version to the RKE Template
6. Go to the cluster list page and validate that there is an upgrade icon
7. Go to the cluster details page and validate that there is an upgrade icon
8. Edit the cluster and update it to the latest template version
9. Go to the cluster list page and validate that there is no upgrade icon
10. Go to the cluster details page and validate that there is not an upgrade icon

**Result** - Pass
When RKE template is updated, dashboard now shows the yellow icon
![image.png](https://zube.io/files/rancher/825411a41488492675bd902c635ebc83-image.png)
The icon states there is a template available for upgrade
![image.png](https://zube.io/files/rancher/d5a4dd3d30d998fe28ff2383cf13f0b6-image.png)

After upgrading, The notification is removed
![image.png](https://zube.io/files/rancher/6abf9703f18659b003a61491f2373c7a-image.png)
