### ISSUE TITLE
When editing cloud credentials, a new description is not reflected in GUI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6584]
Internal reference: SURE-4921
Reported in 2.5.6 & 2.6.2

Issue description:
When editing existing cluster credentials, any new description is not reflected in GUI after saving. The original description persists.
Of note: If the initial cloud credential is created without any description, editing it and adding one is reflected. Any subsequent edits to the description are not.

Troubleshooting steps:
Tried, refreshing page, other browsers, clearing cache etc

Repro steps:

- Create Rancher server, 2.6.5 v1.23.6+k3s1 
- Create cloud credential, in my case DigitalOcean, give it a description.
- Edit the cloud credential and give it a new description

Workaround:
None

Actual behavior:
Description is not updated, the original description is displayed.

Expected behavior:
New description to be displayed.

**Comment by slickwarren** [comment]
tested on v2.6-head (68215bc):
* create new cloud credential with description -- description is observed in UI
* edit existing cloud credential and add/edit description -- new description is displayed in UI
