### ISSUE TITLE
Description field for Rancher roles not editable or 'viewable'

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6585]
Internal reference: SURE-4824
Reported in 2.6.4 & 2.6.5

Issue description:
Rancher roles were created some time back. We are able to add and edit the resources available to these roles, but are not able to add to or update the Description field.

We add the text, click "Save" and it appears to take the changes. But after logging out, the changes are gone and other users are not able to see the change either. 

It does show up in YAML but if you 'create' a new one then you can 'see' the description. However, if you log out and log back in it disappears. 

It is 'similar' to the following 
https://github.com/rancher/dashboard/issues/5568

Troubleshooting steps:
Confirm that it was created by 'checking' YAML

Repro steps:

- Install Rancher 2.6.4 or 2.6.5 (Helm) 
- Create a 'new' Roles -> 'Create Project/Namespaces Role'
- Fill out the form 
- Log out and log back in

Workaround:
None

Actual behavior:
The 'description' field is NOT shown. 

Expected behavior:
The 'description' filed is SHOWN.

**Comment by Josh-Diamond** [comment]
Ticket #6585 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.5`:
1. Fresh install of rancher `v2.6.5`
2. As admin, `Users + Auth > Roles > Project/Namespaces` and create a new role w/ description
3. Observe role successfully created and description is present
4. Log out, then log back in
5. Reproduced - Description as been reset to default placeholder

Screenshots:

`Step 2`
<img width="1444" alt="Screen Shot 2022-08-24 at 8 41 48 AM" src="https://user-images.githubusercontent.com/46494969/186471568-acc5b8de-7506-4021-8f66-14f3019cd4c4.png">

`Step 3`
<img width="1446" alt="Screen Shot 2022-08-24 at 8 42 15 AM" src="https://user-images.githubusercontent.com/46494969/186471646-35c6a0f9-4f9f-4338-9b2b-364d9a0357f9.png">

`Step 5`
<img width="1442" alt="Screen Shot 2022-08-24 at 8 43 18 AM" src="https://user-images.githubusercontent.com/46494969/186471698-95f21b93-32be-4ba0-91f8-d13c91514523.png">

---

Verified on rancher `v2.6-c54b655dfab4838063758278664f7437fa0a2dac-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, `Users + Auth > Roles > Project/Namespaces` and create a new role w/ description
3. Observe role successfully created and description is present
4. Log out, then log back in
5. Verified - Description persists

Screenshots:

`Step 2`
<img width="1441" alt="Screen Shot 2022-08-24 at 9 13 07 AM" src="https://user-images.githubusercontent.com/46494969/186471870-e0021443-4200-4f4d-856a-601645dd9df3.png">

`Step 3`
<img width="1442" alt="Screen Shot 2022-08-24 at 9 13 30 AM" src="https://user-images.githubusercontent.com/46494969/186471906-a238e559-a271-4e86-b38f-6340114a1d9b.png">

`Step 5`
<img width="1441" alt="Screen Shot 2022-08-24 at 9 14 10 AM" src="https://user-images.githubusercontent.com/46494969/186471965-01dabc04-7559-43d1-a797-be7a694a9f3f.png">
