### ISSUE TITLE
404 page `home` link crashes browser

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6608]
**Setup**
- Rancher version: 2.6-head (2.6.7ish)

**Describe the bug**
- nav to `/sdfsfd` & click `Home` link
- browser locks up
  - `[vue-router] relative params navigation requires a current route.` loops in console

**Comment by cnotv** [comment]
@richard-cox After latest changes, I get correctly the 404:
https://rancher.richardcox.dev/sdfsfd
Previously it was not styled.
`Go Home` button fixed too.

![Screenshot 2022-08-05 at 14 34 32](https://user-images.githubusercontent.com/5009481/183078136-10ffe3c0-3f9b-4bc5-9868-982e48e9a3ad.png)

**Comment by richard-cox** [comment]
That's the old ember 404 page. On a production system the one in question is `/dashboard/<junk>`

**Comment by cnotv** [comment]
So we should actually implement a 404 page in a first place.

**Comment by richard-cox** [comment]
That's the old ember 404 page. On a production system the one in question is `/dashboard/<junk>`. Interestingly though that `home` link works. I'm going to put this down to a non-realistic test

**Comment by nwmac** [comment]
Only an issue in dev
