### ISSUE TITLE
Namespace detail page hangs when the namespace filter is `Only User Namespaces`

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6609]
**Setup**
- Rancher version: 2.6-head

**Describe the bug**
- For more detail see https://github.com/rancher/dashboard/issues/6596#issuecomment-1205966187

**To Reproduce**
- Nav to cluster home page
- Set namespace filter to `All Namespaces`
- Go to Project/Namespace list and click on any namespace
- Set namespace filter to `Only User Namespaces` (warning, you will need to close the tab afterwards)

**Result**
- tab hangs, is not responsive to clicks

**Comment by noahgildersleeve** [comment]
Closing per test results here. https://github.com/harvester/harvester/issues/2626#issuecomment-1207968511 . 
> Verified this bug has been fixed.
> 
> Also tested on Rancher `v2.6.6`, didn't encounter this bug.
> 
> ## Test Information
> * Environment: **qemu/KVM 2 nodes**
> * Harvester Version: **v1.0.3-rc2**
> * **ui-source** Option: **Bundled**
> * **ui-index** URL: **https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html**
> * **Rancher** Version: **v2.6-e9e88db363ae369bec044372cae8a36c66c042c9-head**
> 
> ### Verify Steps:
> * Follow **Steps to reproduce** in [[BUG] Access Harvester project/namespace page hangs with no response timeout with local owner role from Rancher    #2626 (comment)](https://github.com/harvester/harvester/issues/2626#issue-1328160313)
