### ISSUE TITLE
multi action dropdown with tags should have label inside field

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#661]
The current multi-action dropdown that uses tagging always has the label outside of the input but ideally would be able to have it inside like all the others. that way if they are used side by side it does't look unbalanced.

![Screen Shot 2020-05-18 at 11 26 32 AM](https://user-images.githubusercontent.com/3013118/82247299-06695100-98fb-11ea-96cd-4efc31d8e745.png)
![Screen Shot 2020-05-18 at 11 25 01 AM](https://user-images.githubusercontent.com/3013118/82247304-0701e780-98fb-11ea-8209-1704e60d56d7.png)

**Comment by izaac** [comment]
The label is inside the multi action dropdown in the latest master index in Rancher `master-head (06/29/2020)` commit _1a5e5622b_ . But the `Drop Capabilities` label is not visible.

![Screen Shot 2020-06-29 at 4 23 44 PM](https://user-images.githubusercontent.com/27659/86065893-9683d580-ba25-11ea-96eb-d43be88a9f13.png)


In `v2.4-head` commit _cf8f4a6f5_ is still pointing to index `release-2.4` by checking `/v1/management.cattle.io.settings/dashboard-index` index value. (default is latest). And in `2.4-head` the labels are still outside.

![Screen Shot 2020-06-29 at 4 30 41 PM](https://user-images.githubusercontent.com/27659/86066034-e793c980-ba25-11ea-9e8e-112756407e3c.png)

**Comment by izaac** [comment]
Reopening becuase of the `Drop Capabilities` is not visible in the latest master dashboard-index

**Comment by izaac** [comment]
Validated in Rancher `master-head (07/02/2020)` _ec1ea7a99_
dashboard-index -> `latest`

Labels for add and drop capabilities are now inside the multi action dropdown.

![Screen Shot 2020-07-02 at 12 20 05 PM](https://user-images.githubusercontent.com/27659/86401005-64a98380-bc5e-11ea-991a-eb47e3937dae.png)
