### ISSUE TITLE
Enhancements to Formatting Section in Preferences Page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6614]
**on 2.6-head commit id: `89fec60`**

- Navigate to Preferences page
- Under Formatting Section can we add more details to `Date Format` and `Time Format` dropdown fields? 
- It is not clear what these formatting options are for. These are for the `View Logs` option on the pods/deployments. 
<img width="1491" alt="Screen Shot 2022-08-07 at 3 07 47 PM" src="https://user-images.githubusercontent.com/26032343/183312978-91d038c0-84c5-41c0-88f2-4669acead934.png">

Can we make a sub section calling out these are for View Logs, or name the dropdown fields appropriately ?

**Comment by richard-cox** [comment]
The date and time settings actually apply dashboard wide (for instance in `Age` tooltips, Date columns, etc).

These are grouped with other 'format' like settings (`Table Rows per Page` -only applies to lists and `Number of clusters to show in side menu` -only applies to the side menu). 

I don't think there's anything to do here for these two specific settings.

@kwwii We might want to take a look generally at how these preferences are laid out, are there any improvements we need to make? I know we have issues generally with the dev setting one (https://github.com/rancher/dashboard/issues/6289).

**Comment by Josh-Diamond** [comment]
@richard-cox could you confirm what I'm testing here?  Were there any changes made? 🤔

**Comment by richard-cox** [comment]
@Josh-Diamond There were no changes made. There may be some changes in future releases for how this page is laid out but the settings themselves are ok at the moment. 

Was tempted to just close the issue, but as this was raised by QA thought that should be done your side.

**Comment by Josh-Diamond** [comment]
@richard-cox Understanding that no changes to the settings are needed and realizing this enhancement was created with the intent of providing clarity around these settings, would it be possible to improve the title or add better descriptions?

My initial thought would be to change `Formatting => Display Formatting`, and add a hover description, similarly styled to screenshot_2, which could state something like, `seen throughout Rancher`

`screenshot_1 - Title change`
<img width="1244" alt="Screen Shot 2022-08-16 at 6 51 17 AM" src="https://user-images.githubusercontent.com/46494969/184897301-16adffed-4861-453b-8354-7686e95e3227.png">

`screenshot_2 - Hover style`
<img width="414" alt="Screen Shot 2022-08-16 at 6 50 12 AM" src="https://user-images.githubusercontent.com/46494969/184897268-f217c331-3bd4-45b4-910d-7868bf2d4573.png">

**Comment by richard-cox** [comment]
The changes suggested are rather superfluous. Without text to show the settings are restricted to certain pages, features, components etc they already show that they apply throughout the UI. 

If we were to do something the title should probably change to something like `Display Settings` (to better cover rows per page and clusters to show in side nav settings) and have description text underneath the title (as per the `Login Landing Page` section above)
```
Change the way information is displayed in <product name>
```

@kwwii is this something we need to do?

**Comment by richard-cox** [comment]
I've reviewed this with Ken and he's happy with the changes. I've created a separate issue to remove any confusion with the request in the description of this issue - https://github.com/rancher/dashboard/issues/6672. This one can now be closed
