### ISSUE TITLE
Log page related bugs

### ISSUE THREAD

**Issue by songlexin** [rancher/dashboard#6615]
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Google browser & Version 104.0.5112.79 (official version) (64 bit)

**Describe the bug**

Set the last display 1000 lines, but actually display all
**To Reproduce**

1 on the cluster page, click pods, right-click a row in the table, and click "view logs", and the log content will be displayed at the bottom

2 Click the setting button on the log page and select 1000 lines
**Result**
The number of logs displayed exceeds 1000 lines
**Expected Result**

The number of logs displayed should not exceed 1000 lines
**Screenshots**

![image](https://user-images.githubusercontent.com/34473596/183373690-928c40bb-e501-4713-bffa-465e9685b55d.png)
![image](https://user-images.githubusercontent.com/34473596/183377057-b39a0f43-f107-4b82-a499-b1463c9f5f2b.png)

**Additional context**

![image](https://user-images.githubusercontent.com/34473596/183373208-adabba2d-998b-43e0-a2d9-b78e0cc8b06d.png)
![image](https://user-images.githubusercontent.com/34473596/183373353-8dda4248-3654-4d74-a8f2-5e57f484b9c8.png)

**Detailed Description**

**Context**

When there is a large amount of data, the display of all content pages will be blocked. I only want to see the currently set content
If the number of logs is large and the page is not stuck, the user experience should be great

**Comment by richard-cox** [comment]
In 2.6.5 the preference which determines how many log lines are shown was broken which created a range of issues (primary one is https://github.com/rancher/dashboard/issues/5984). This will be resolved in 2.6.7, until then there are a number of workarounds listed [here](https://github.com/rancher/dashboard/issues/5984#issuecomment-1180191702).
