### ISSUE TITLE
daemonSets statefulSets can‘t select rollback options

### ISSUE THREAD

**Issue by luozhi1024** [rancher/dashboard#6616]
**Setup**
- Rancher version: v2.6.3
- Browser type & version: chrome 103.0.5060.134

**Describe the bug**
In the current version, except deployment can rollback, daemonSets and statefulSets cannot choose the rollback version

**To Reproduce**
Modify the daemonsets, rollback the previous version, and find that the version cannot be selected, the option is empty

**Result**

**Expected Result**
I hope there is a corresponding version to choose from

**Screenshots**
![image](https://user-images.githubusercontent.com/40513505/183407162-a9d44699-4af9-494d-a035-0f9e3e86bd7f.png)

**Additional context**
This function requests that the workload only has deployment data and no other data
```
  fetch() {
    // Fetch revisions of the current workload
    this.$store.dispatch('cluster/findAll', { type: WORKLOAD_TYPES.REPLICA_SET })
      .then(( response ) => {
        const allReplicaSets = response;
        const hasRelationshipWithCurrentWorkload = ( replicaSet ) => {  
          const relationshipsOfReplicaSet = replicaSet.metadata.relationships;
          const revisionsOfCurrentWorkload = relationshipsOfReplicaSet.filter(( relationship ) => {
            const isRevisionOfCurrentWorkload = relationship.fromId && relationship.fromId === `${ this.workloadNamespace }/${ this.workloadName }`;
            return isRevisionOfCurrentWorkload;
          });

          return revisionsOfCurrentWorkload.length > 0;
        };
        console.log(allReplicaSets, 'allReplicaSets')
        const workloadRevisions = allReplicaSets.filter(( replicaSet ) => {
          return hasRelationshipWithCurrentWorkload( replicaSet );
        });
        const revisionOptions = workloadRevisions.map( (revision ) => {
          const isCurrentRevision = this.getRevisionNumber(revision) === this.currentRevisionNumber;

          if (isCurrentRevision) {
            this.currentRevision = revision;
          }

          return this.buildRevisionOption( revision );
        });

        this.revisions = revisionOptions;
      })
      .catch(( err ) => {
        this.errors = exceptionToErrorsArray(err);
      });
  },
```

**Detailed Description**
NA

**Context**
NA

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: c35f112`

I made a daemonset and then edited it and I see all revisions in the rollback selector.

![image](https://user-images.githubusercontent.com/107147272/206005141-d7252676-c1b9-47ad-8660-ae4c4eede77e.png)
