### ISSUE TITLE
Rancher UI Service view show pods from other namespaces

### ISSUE THREAD

**Issue by jouve** [rancher/dashboard#6619]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Provider: RKE2 
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:Kubernetes Version: v1.21.6
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

in rancher ui, when viewing the `Pods` tab in the `Service` view, it shows pod matching the selector from other namespaces

**To Reproduce**
 

Create a pod in ns ns1 with labels `a: b`
Create a pod in ns ns2 with the same labels `a: b`
Create a service svc1 with the selector for `a: b` 
Go in rancher ui and display the service ns1/svc1

**Result**

It shows the pod in ns1 and ns2

**Expected Result**

It shows the pod in ns1 only

**Screenshots**

![Capturexxxx](https://user-images.githubusercontent.com/1096799/143075639-f6c53fd0-f7cb-40f5-9720-60874327c82d.PNG)

**Additional context**

**Comment by gaktive** [comment]
There's some connection with https://github.com/rancher/dashboard/issues/6613

**Comment by richard-cox** [comment]
The pods shown in the services page are determined by the pod relationships the service has (relahttps://github.com/rancher/dashboard/blob/master/shell/models/service.js#L131). 

@jouve @JanHolger Can you confirm the service relationships are valid and are not selecting pods outside of the desired namespace?

**Comment by jouve** [comment]
with a cluster created today using https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/deployment/quickstart-vagrant/#getting-started, then 2 namespaces with bitnami/nginx deployments:
```bash
helm upgrade --install --set service.type=ClusterIP --create-namespace --namespace ns1 nginx bitnami/nginx
helm upgrade --install --set service.type=ClusterIP --create-namespace --namespace ns2 nginx bitnami/nginx 
``` 

I still see that rancher UI selects pods related to the service *without* regard to the namespace:
```js
    console.log(`Find Matching: [${ ctx.state.config.namespace }] ${ type }`, selector); // eslint-disable-line no-console
``` 
->
``` 
Find Matching: [cluster] pod app.kubernetes.io/instance=nginx,app.kubernetes.io/name=nginx 
``` 
-> 
``` 
GET | https://192.168.56.101/v1/pods?labelSelector=app.kubernetes.io/instance=nginx,app.kubernetes.io/name=nginx
``` 
![image](https://user-images.githubusercontent.com/1096799/183475733-e6bff8fb-3c20-461a-897c-13b52e73049b.png)

**Comment by richard-cox** [comment]
Thanks for providing clear steps to reproduce.

Note - `ctx.state.config.namespace` does not relate to kube namespace, but the namespace of the store

**Comment by catherineluse** [comment]
Neil created a new getter, `podsByNamespace`, that we can use to narrow the results:

```
 const pods = this.$getters['podsByNamespace'](this.metadata.namespace);
```

**Comment by sowmyav27** [comment]
Reopening since it seems to have closed accidentally.

**Comment by jameson-mcghee** [comment]
I was able to reproduce this issue on v2.6.2 (see v2.6.2 Screenshot and Repro Steps). I then upgraded Rancher to v2.6-head (Commit ID: 400e559), and the issue did not reproduce. Therefore I am marking this ticket as Done. 

Repro Steps:
1) Create an RKE2 EC2 cluster on _v2.6.2_
2) On the Cluster --> Projects/Namespaces page for the cluster, create Namespaces _ns1_ and _ns2_ in _Not in a Project_
3) On the Workload --> Deployments page for the cluster, create a Deployment on _ns1_ with the _Pod Label_ **"a:b"**
4) On the Workload --> Deployments page for the cluster, create a Deployment on _ns2_ with the _Pod Label_ **"a:b"**
5) On the Service Discovery --> Services page for the cluster, create the Cluster IP service _svc1_ with the selector _Key: a_ and _Value: b_ on Namespace _ns2_
6) Open the service and change the Namespace dropdown list to display _All Namespaces_
**Reproduced:** Note that both _ns1_ and _ns2_ are present in the grid, when it should only contain _ns2_

**v2.6.2:**
![image.png](https://zube.io/files/rancher/7e2bf6187d64b770b51341aff7f576de-image.png)

**v2.6-head:**
![image.png](https://zube.io/files/rancher/516cb62a8f9d2ee89da22924687f15b7-image.png)
