### ISSUE TITLE
[Backport for 2.6.x] UI sets wrong cluster: server url

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6620]
Internal reference: SURE-4775
Reported in 2.6.4+

Backport of a 2.7.0 request: https://github.com/rancher/dashboard/issues/6605

Issue description:
The UI sets wrong cluster for the server URL. This changed behaviour in Rancher v2.6 compared to 2.5 makes extra work because the wrong URL has to be manually corrected by the sysadmins.

Business impact:
All the developers who access Rancher via Rancher web interface get the wrong URL in kubectl and cannot access the cluster in kubernetes CLI

Repro steps:

Download the KubeConfig in Rancher v2.6.4 UI
Select your cluster than click on the "Download KubeConfig" button and save the yaml file.
Check the cluster: server URL

**Comment by richard-cox** [comment]
I'm not sure this is something we need to tackle, or at least as described in the ticket. See comment in JIRA

**Comment by gaktive** [comment]
We're pausing on anything here until backend reviews the design around multiple URLs for the same setup.

**Comment by gaktive** [comment]
This is working as designed. As noted by PM, "Solutions like ACE exist to allow users to set different urls per cluster and should fulfil this need more appropriately than configuring urls in Rancher directly".

**Comment by martyav** [comment]
@gaktive Do we want to note this behavior in the release notes for v2.6.12? This still has the milestone applied

**Comment by gaktive** [comment]
@martyav We should since the question does pop up now and then.

**Comment by martyav** [comment]
@gaktive Following up -- I'm not familiar with what ACE might stand for in this context. Can you give me the full name?

**Comment by gaktive** [comment]
@martyav Application Control Engine. Otherwise, you could make it more generic as a network load balancer whereby a service allows one URL to point to many.
