### ISSUE TITLE
Bulk delete clusters sometimes throws error missing object

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#6628]
**Setup**
- Rancher version: 2.6.7
- Browser type & version: Chrome

**Describe the bug**
In some cases bulk deletion of clusters returns error missing object with reference to the mutation.

**To Reproduce**
- Select multiple clusters
- Delete selection and confirm

**Result**
Error is returned.

**Expected Result**
No error.

**Screenshots**

**Additional context**
Previously identified with the test https://github.com/rancher/dashboard/pull/6284 and commented in https://github.com/rancher/dashboard/pull/6284#discussion_r941305605 and https://github.com/rancher/dashboard/pull/6284#discussion_r941307866

**Comment by cnotv** [comment]
While implementing a check on the payload of the operations for the clusters in https://github.com/rancher/dashboard/issues/7275, then doing some cleanup of the hanging clusters, I had several completely broken behaviors on bulk delete.

Identified glitches:
- Multiple selection after page load toggled selected rows, but not the checkboxes
- After bulk deletion I receive an error of the cluster not existing
- After page reload clusters started to disappear from nowhere

**Comment by nwmac** [comment]
Can I close this @cnotv and re-open if you see it again.
