### ISSUE TITLE
Issue in navigation Cluster details --> Config Page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6631]
**On 2.6-head commit id: b8b95dc**

- Deploy an RKE2 node driver AWS cluster
- After the cluster comes up Active, from CLuster Management Page, navigate to Cluster details page --> Config Tab
- Scroll down to Cluster Configuration section
- Basics tab will be open
- Now click on `Member Roles`
- You will notice the page will scroll up automatically
- Click on the next tab --> `Add on Config`
- You will notice the page will scroll down automatically
- Now click on `Agent Environment Vars`
- You will notice the page will scroll up automatically

**Expected result:**
Can we not have the page scroll up/down automatically when switching tabs under Cluster Configuration Section

**Comment by gaktive** [comment]
It's possible that the page length is changing upon click activity since we don't have any widget to automatically scroll. Will need to repro to understand the logic behind the tab change.

**Comment by catherineluse** [comment]
This should be a one-line fix - just add a minimum height to that section.
