### ISSUE TITLE
pod counts inconsistent

### ISSUE THREAD

**Issue by perllaghu** [rancher/dashboard#6635]
**Setup**
- Rancher version: V2.6.4
- Browser type & version: Firefox 103.0.1 (linux)

**Describe the bug**
The pod count shown on the home page, the cluster dashboard page, and in the cluster workload count are all different

.... and, in my case, _wildly_ and worryingly so.

**To Reproduce**

Connect to rancher web UI, and click the the appropriate locations

**Result**

For my case, I have 68/220 on the home page; 1093/220 from the cluster dashboard; and 55 pods listed under the "Workload" menu.

(the cluster has 3 control nodes and 2 worker nodes)

**Expected Result**
I would expect the three values to be reasonably close.

I can also see no way to force a recount (assuming a page-load doesn't do that)

I note that `kubectl get pods` returns a lesser number, however that will be for the _context_ rather than the whole cluster

**Comment by catherineluse** [comment]
In the top nav of cluster explorer, is **All Namespaces** selected in the top nav? If

**Comment by perllaghu** [comment]
Top level "home" screen has a table entry that reads:

| State | Name | Provider | Kubernetes Version | CPU | Memory | pods |
| --- | --- | --- | --- | --- | --- | --- |
| (active) | foo | rke | v1.20.9 | 5.38/16 cores | 9.27GiB/47GiB | 65/220 |

(edited to remove all other clusters)

In the "Cluster Dashboard" (and I checked: 'Only User Namespaces' is selected - and changing it makes no difference to the numbers) and "workload" numbers can be seen ![google-hosted image of cluster dashboard web-page](https://lh3.googleusercontent.com/twaiLv-5BdsT3szmxSu8O6iCabYz0XKb4UOgKI17_V4DLU033nIiniJGt_aiadBtnK8yF5IhfZ4XwyEB_ZNMMNh0gvx41DzbmdngeU1bh0MihBBiLp0Lgzf_yJvexOo8fnLqP9VSA4MvKlAJIy-pV__XbzApVPVYenfi6AfE_m6vaN50C5qgs62gk3Nrg1sF0-SG93wiFD4y9xJZZYrVOA3NzOLQFaYFH7bbFKgRQ56aGIvjvG5tHEBO2L-ZwYw5ZsAgo6dMMDrqOO6f6zoDrYGWvp2umw_yPvnpPVlzxFhqpOMJebpkf8_vX5ZupvISbMGt8FF9xxRS4SDgz0fnHWHAXPYu9MBIqSzW3W_iHXhtul9YhkKa3CEuHmxUzkXtPdfqlnEio_BokQ2-UW2J1w-r5eqaVesrAaXiNOIw5iOLW9m0-kIdRR6kS3Dt-RQId4x4dTSKh4NIg6XTI8hpTt6DWpNjBQlqv9UMMEoRk4BSOc-AkPPhTtb1lC2SBG-0IJlO5kQ-4FPkVcO2CMQsya61nKHNR87kUdy4o12TIpTxgfd3rPRTMb28VciimbRJzbcTBFhPJXE1bHZ5s_LMtovKJgMVJwoKfvf7l80hTlAahVdllR7omAuDvQLvIRU9klPeHa5uuBZqqCzOsK5B5kINy-UuvGO44907lr4HhSoezcznsJfzEYv2aTEgd5Q4f9NL0TYwOGd4UqOtCYmdgVfwQDDYrkVax13Vp8N1n9IW_gGs3AZf3HMkophC0uD2o7LCjarRSH0j3uNElfarhrH53HafGm6-2FOWyhXdT8_5FbKEt2xpCUKlB3TaKVIbxJHh9V0R=w1255-h583-no?authuser=0)

**Comment by richard-cox** [comment]
Please can you retest with the latest version (as of writing 2.8.3) and re-open if still applicable
