### ISSUE TITLE
Log out/login page is stuck on loading for a standard user

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#6640]
Setup

Rancher version: 2.6-head 76d89bd
Browser type & version:  Chrome and firefox

**Describe the bug**
If we try to log out from rancher server UI as a standard user, the page is stuck on loading. When we try hard refresh on the loading page, it keeps us logged in and then if we retry the logout again, it then works. 
After a log out, if we try to re login then we are stuck on loading for login as well. 

**To Reproduce**
1. Create a rancher server on v2.6-head
2. Create a standard user as an admin from Users and auth >> Users
3. Login as a standard user, login works
4. Try to logout of the rancher server
5. UI is stuck in loading 
6. Hard refresh the page
7. Try log out again --> works
8. Try to login, page is again stuck on loading. 

**Result**

Two cases where the page is stuck on loading:
Logout and then re login.

Attached screenshot errors seen during logout but no errors were seen during login

**Expected Result**
Expected login and log out to work without any errors. 

**Screenshots**
<img width="400" alt="logout" src="https://user-images.githubusercontent.com/38144301/184099041-f9490147-6b40-43e1-8350-008db4f54601.png">

**Additional context**

- When we try to log out or login, If we hard refresh the page then we will be able to login/log out.
- Log out or login works fine for admin users.
- It is possible that the issue happens because of https://github.com/rancher/rancher/issues/38590

**Comment by aalves08** [comment]
Could reproduce this issue. Check comment https://github.com/rancher/dashboard/issues/6639#issuecomment-1211826490

FYI @gaktive @richard-cox @kwwii

**Comment by anupama2501** [comment]
User was created without any global permissions assigned, therefore seeing weird behavior in the rancher server.

**Comment by anupama2501** [comment]
Seems to happen because of  https://github.com/rancher/rancher/issues/38590
