### ISSUE TITLE
User directed to ember registration page when creating an rke1 custom cluster, but the cluster -> registration tab shows non-ember page

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#6643]
**Setup**
- Rancher version: v2.6.7-rc9
- Browser type & version: chrome

**Describe the bug**

when a user creates a custom rke1 cluster, they are shown an iframe page from ember with the registration options. However, once they click away from that page, the only way to get back to the registration page is to select the cluster -> registration tab. This page shows the vue page instead. There is mismatching information i.e. [for this ticket](https://github.com/rancher/dashboard/issues/5995), the windows warning only shows up in the vue page. 

**To Reproduce**
deploy a custom rke1 cluster

**Result**
user is brought to an ember page upon creating the cluster

**Expected Result**
I would expect  consistency.  I believe the right approach would be to bring the user to the vue page showing the cluster -> registration page instead of the ember page

**Screenshots**

ember page: 
![Screen Shot 2022-08-11 at 9 28 39 AM](https://user-images.githubusercontent.com/16691014/184183448-86debcc6-701a-43fa-9da8-293947f48381.png)

vue page: 
![Screen Shot 2022-08-11 at 9 28 46 AM](https://user-images.githubusercontent.com/16691014/184183476-c41bc390-39d8-4dfc-90e8-1b60317d145b.png)

**Comment by gaktive** [comment]
Likely won't do but we'll push out of 2.7.0 in case we can tackle this. We would like to present the Vue page as well as the Ember.

**Comment by gaktive** [comment]
Closing for now as we haven't reports about this in 2+ years. Reopen if this is still happening but in a newer version.
