### ISSUE TITLE
On workload creation page, make containers the default tab

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6644]
This is just a suggestion for the workload create/edit form. Since the container tab is the only one that has a required field - the container image name - it should be the default. This change would reduce the number of clicks needed to create a simple deployment.
<img width="1365" alt="Screen Shot 2022-08-11 at 4 40 51 PM" src="https://user-images.githubusercontent.com/20599230/184260109-1002ba00-e3c2-4821-a045-5611459f5166.png">

@kwwii

**Comment by richard-cox** [comment]
This would make a lot of sense. Was wondering if we should move it to be the first tab too, however that would push out `deployment` (or whatever workload type is shown) specific settings out to the right ... which feels odd

**Comment by kwwii** [comment]
With the current implementation using horizontal tabs for the Containers moving this tab would cause a problem, as the "Add Container" would no longer be next to the Containers tab

**Comment by kwwii** [comment]
I originally wanted to have the containers in the vertical tabs beneath the horizontal tabs but we changed this due to some issues it caused

**Comment by catherineluse** [comment]
I worry that even exposing the option to create a second or third container in a new tab adds too much complexity.

For comparison, here is a screenshot of the upstream Kubernetes dashboard, which only exposes four fields for deployments by default:

<img width="1085" alt="Screen Shot 2022-08-12 at 11 27 02 AM" src="https://user-images.githubusercontent.com/20599230/184421868-ab9b3a7e-06df-4411-8ac9-482b7d5ce66e.png">

This is getting more into UX design decisions about workflows that extend beyond 2.7.0, but in theory I think all the container configuration should fit on one tab, even a list of multiple containers, if more options were hidden under advanced options similar to the above screenshot.

**Comment by nickwsuse** [comment]
`Verified on v2.6.9-rc3`

The default tab when creating deployments is now the container tab.
