### ISSUE TITLE
[2.7.x] v2.6.7 Workloads List View not updating Restart and Health columns on user update of Workload

### ISSUE THREAD

**Issue by git-ival** [rancher/dashboard#6653]
**Setup**
- Rancher version: 2.6.7+ (commit ee084d0 or later)
- Browser type & version: Any

**Describe the bug**
In the case that the user is filtering the deployments and updates a given deployment the restart count and health columns begin to load but do not finish loading even though the Deployment has already finished updating. See [my comment](https://github.com/rancher/dashboard/issues/6457#issuecomment-1213599951) on rancher/dashboard#6457.

**To Reproduce**
1. Edit a Deployment
2. Filter the Workloads list view for the deployment
3. Wait for the Restart and Health columns to load

**Result**
The Restart and Health columns do not load long after the Deployment has successfully been updated.

**Expected Result**
The Restart and Health columns load with the updated results soon after the Deployment has been updated.

**Screenshots**
Watch from the 2-minute mark:

https://user-images.githubusercontent.com/85186645/184458162-37ee1097-149f-457a-99df-321e8b6f02b3.mp4

**Additional context**
The workaround to verify the status of the Deployment is to look at it's Workload detail view instead of the Workload list view.
![image](https://user-images.githubusercontent.com/85186645/184678570-52361eb3-1b85-4fa0-98dd-7db776e39d6c.png)

**Comment by richard-cox** [comment]
Note - Another workaround is to change namespace/project filter, list sort column or order, grouping option or page

**Comment by git-ival** [comment]
Retested with PR #6654, LGTM!

https://user-images.githubusercontent.com/85186645/184695466-852976e2-ca00-4fc5-9acc-35aa2cf23b67.mp4
