### ISSUE TITLE
Time stamp text boxes of objects are stacked one above the other preventing operations on the objects

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#666]
Version: master-head(1f4a2c388)

Steps:
1. Create several secrets/configmaps/workloads in dashboard UI
2. From the list view, hover over the age column with the mouse

Result
Time stamps for all the objects are stacked one above the other and makes it hard to right click and do other operations. Users have to wait until the boxes disappear before working with the objects.

![86AAED7B-804C-4E15-84B6-B397ADA2763E](https://user-images.githubusercontent.com/18536626/82276147-47805600-9939-11ea-8536-f8b6a03c384e.jpeg)

**Comment by vincent99** [comment]
I fixed this already in my next PR..

**Comment by soumyalj** [comment]
Validated with master-build(b85ea695f)
**Steps:**
1. Create several secrets/configmaps/workloads in dashboard UI
2. From the list view, hover over the age column with the mouse

**Results**
Time stamps for all the objects are not stacked one above the other . Users can work with the objects. 
<img width="1035" alt="Screen Shot 2020-05-19 at 10 04 59 PM" src="https://user-images.githubusercontent.com/18536626/82407113-2a24b800-9a1d-11ea-97d6-a90e760d13fa.png">
