### ISSUE TITLE
Move locale selector from slide-in to user preferences

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6660]
Now that we have the locale selector on the login screen, we should move the locale selector from the slide-in menu to the user preferences page.

**Comment by Josh-Diamond** [comment]
Ticket #6660 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-40c390d79faef993e8509d545a4ed1e18a78a4de-head`:
1. Fresh install of rancher `v2.7-head`
2. Verified - Side-menu no longer contains locale selector
3. Verified - User preferences contains locale selector

Screenshots:

`Step 2`
<img width="1569" alt="Screen Shot 2022-09-29 at 11 03 40 AM" src="https://user-images.githubusercontent.com/46494969/193109263-c619689a-9137-496d-9358-26071e4dfbe2.png">

`Step 3`
<img width="1570" alt="Screen Shot 2022-09-29 at 11 06 02 AM" src="https://user-images.githubusercontent.com/46494969/193109472-ad7a27ec-f381-48bc-b61a-4a5c1c96f855.png">
