### ISSUE TITLE
Update Support Page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6663]
Changes required to the support page:

- Hide the button and text to add a subscription ID
- Remove the right-hand card 'Support'
- Move the 'Find out more ... or contact ..' link to the right hand area
- Ensure that the 'Get Support' box is only shown when commercial support is enabled

**Comment by thaneunsoo** [comment]
Will test once fix is merged

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head a3502cd
Rancher cluster type: single-node docker install / HA
Docker version: 20.10

----------

### Testing: ###
Tested this issue with the following steps:
1. Verify button and text to add a subscription ID is hidden
2. Verify right-hand card 'Support' is removed
3. Verify 'Find out more... or contact...' link is moved to the right
4. Verify 'Get Support' box is only shown when commercial support is enabled

**Result**

1. Button and text to add a subscription ID is hidden successfully
![image.png](https://zube.io/files/rancher/a52fe2fb1bc9c29f3111ac993c936365-image.png)

2. Verify right-hand card 'Support' is **not** removed
3. Verify 'Find out more... or contact...' link is **not** moved to the right
Based on [6736](https://github.com/rancher/dashboard/pull/6736), the support page should look something like this
![image.png](https://zube.io/files/rancher/52aca3b1a576c7c4dc5c2aa8e45abccd-image.png)

4. Verify 'Get Support' box is only shown when commercial support is enabled
**Will test again once RC is available to test on Rancher Prime**

**Comment by Shavindra** [comment]
@thaneunsoo requirements changed following discussion with @kwwii 

Get support link will remain as it is however, If community 2 links will show. Otherwise it would remain as its for prime.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head d3db38f
Rancher cluster type: Docker
Docker version: 20.10

----------

### Testing: ###
Tested this issue with the following steps:
1. Verify 'Get Support' box is shown when commercial support is enabled
![image.png](https://zube.io/files/rancher/93441131e46e65c6e8c3c1be22ded4ef-image.png)
