### ISSUE TITLE
Update SUSE brand

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6666]
Logo needs updating at a minimum

**Comment by nwmac** [comment]
@kwwii to get latest logo

**Comment by gaktive** [comment]
We got a logo.

**Comment by slickwarren** [comment]
waiting on a new RC to be cut so that we may use a non-docker registry

**Comment by slickwarren** [comment]
tested on v2.7.0-rc6: 
according to https://suse.imagerelay.com/share/df255e99bdd845d9af60768b89a7f278, the colors and logo(s) are now correct. supporting issue: https://github.com/rancher/dashboard/issues/7305
