### ISSUE TITLE
Ingress - Design Issues

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#667]
## Edit Page

- [x] The spacing for the content in the Rules Box and inside the Certificates tab  should be the same.
  - [x] The content should be aligned on the left between the edge of the box/tab and th. 
  - [x] The boxes should be aligned on the right side where the content ends, so that the `REMOVE` text boxes are aligned. 
  - [x] The `X` in the Certficate tab is too close to the edge. There's no padding. It should line 
 up with the `X` in the rules box. 
  - [x] The `REMOVE` text in the Rules box should be the same size as the `REMOVE` text in the tab for Certificates and for Labels/Annotations (KeyValue Component). 
  - [x] The space between the `ADD PATH` and path text box should be the same as the space between the `ADD HOST` and the host text box. 

<img width="1128" alt="Screen Shot 2020-05-18 at 5 22 55 PM" src="https://user-images.githubusercontent.com/11410997/82271449-a8edf800-992c-11ea-8585-8aa4c3272fdc.png">

- [x] The `Request Host` text box doesn't need to span the entire width. 

<img width="1127" alt="Screen Shot 2020-05-18 at 5 20 53 PM" src="https://user-images.githubusercontent.com/11410997/82271183-f027b900-992b-11ea-8fa9-5de878103b76.png">

- [x] Host doesn't' need span the entire space.

<img width="1133" alt="Screen Shot 2020-05-18 at 5 28 01 PM" src="https://user-images.githubusercontent.com/11410997/82271559-f10d1a80-992c-11ea-8570-9a39494fb75d.png">

## Detail Page

- [x] The Header is too light for `Hostname` and too close to the text. 

<img width="238" alt="Screen Shot 2020-05-18 at 5 29 44 PM" src="https://user-images.githubusercontent.com/11410997/82271620-2fa2d500-992d-11ea-9db7-73f2a1ce1055.png">

**Comment by lvuch** [comment]
The detail page is throwing errors for me currently

**Comment by deniseschannon** [comment]
# Edit Page

- [ ] In the rules section, headers for `Path`, `Target Service`, `Port` do not match other headers for the site for this style of adding additional boxes.

**Comment by deniseschannon** [comment]
@lvuch I unchecked the boxes of the ones that were still issues for me when reviewing the ingress page. Can you take a look again?

**Comment by aaronRancher** [comment]
Validated with `rancher\rancher:master-head` `version 16616de9c`

Ingress Edit:
![Screen Shot 2020-07-17 at 4 12 40 PM](https://user-images.githubusercontent.com/57409052/87837834-cdd9eb00-c849-11ea-9d7a-86a214239e64.png)
Validated:
* Content is aligned on the left
* `REMOVE` text is the same size in both boxes
* The space between the ADD PATH and path text box is the same as the space between the ADD HOST and the host text box.

Fixes not seen:
* Content is aligned on the right
* `x` in the Rules box is aligned with the `x` in the Certificates box
* In the rules section, headers for Path, Target Service, Port match other headers for the site for this style of adding additional boxes.

Detail page:
![Screen Shot 2020-07-17 at 4 13 20 PM](https://user-images.githubusercontent.com/57409052/87837843-d7fbe980-c849-11ea-88b2-da83926e7240.png)
Validated:
- Header is not as light

**Comment by deniseschannon** [comment]
I'm going to close this issue and re-review deign after we move to the new resource create flow.
