### ISSUE TITLE
Improve the User Profile page's 'Formatting' Section

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6672]
**Is your feature request related to a problem? Please describe.**
This came out of the discussion in https://github.com/rancher/dashboard/issues/6614. I've created a new issue to remove any confusion with the request in it's description.

**Describe the solution you'd like**
1. `Formatting` title --> `Display Settings`
2. Add a description underneath the title (styled the same as the `You can change...` description underneath `Login Landing Page`
   ```
   Change the way information is displayed in <product name>
   ```
   Note - product name i think is just {product} in the translation file. It should be clear that this only applies to the UI.
3. Move the `Table Rows per Page` onto the same row as `Number of clusters to show in side menu`

**Comment by Josh-Diamond** [comment]
Ticket #6672 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.6-28a74733d5a7bf24f114b4ad4daf84d663b6a683-head`:
1. Fresh install of rancher `v2.6-head`
2. From user avatar in upper-right corner of UI, visit `Preferences` page
3. Verified - User `Preferences` page reflects desired changes
4. Verified - `Date Format`, `Time Format`, `Table Rows per Page`, and `Number of clusters to show in side menu` all functional and working as expected

Screenshot:

`Step 3`
<img width="966" alt="Screen Shot 2022-09-15 at 4 22 52 PM" src="https://user-images.githubusercontent.com/46494969/190525684-1506908b-d242-41be-9a0e-a3a01c6b2f9b.png">
