### ISSUE TITLE
Improve performance of creation screens

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6678]
Some of our creation screens have select controls that allow you to choose a secret, a config map etc - in many cases the fetch for these controls is done at the top-level page, blocking the entire page, even though the data is only needed in a control that the user may not need.

We should change this and push the fetch down into the select control and block only that control.

Currently, the fetch also uses the same mechanism as for the lists, so we fetch all resources and watch then to keep them up to date - thus as you move around the UI through creation forms, we will be storing and watching more resources.

We should update this to fetch the resources, not store or watch them.

Down the line we might cache the names of resources. Note we typically only need the names, not the full resources. 

Also worth noting that for namespaced resources, to use a secret or config map it needs to be in the same namespace, so we can optimise and only fetch the config maps etc in the same namespace as the resource being created/edited.

**Comment by floatingman** [comment]
On a k3s cluster
Create a secret and a config map.
Made sure things worked as expected.
