### ISSUE TITLE
Logging ClusterFlow: missing namespaces field in match config

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#6687]
**Is your feature request related to a problem? Please describe.**
The ClusterFlow form in the logging section is missing a field to configure namespaces in the match config:

https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/v1beta1/clusterflow_types/#clusterselect-namespaces

**Describe the solution you'd like**
Add an additional namespaces selector in the match config for ClusterFlows. This should only be present for ClusterFlows and not for namespaces Flows.

**Comment by AndrewHoffmanQA** [comment]
@bashofmann when testing this work item i found a legacy bug that adding too many namespaces to the form results in UI issues (see screenshot). 

(2.7.0)

![image.png](https://zube.io/files/rancher/75432ced08d526b1658289c89b211d73-image.png)

2.7-head


![image.png](https://zube.io/files/rancher/5a8ec04ef338982a1ccb99c0b4ef470f-image.png)

is this an issue you'd like to tackle as part of the scope of this ticket or would you prefer a new ticket to track this bug?

**Comment by bashofmann** [comment]
@AndrewHoffmanQA This seems to be a general styling issue of the `Select` component. I think it's best if we open another ticket for this, because this could affect lots of other places where this component is used.

**Comment by bashofmann** [comment]
I created https://github.com/rancher/dashboard/issues/7842

**Comment by AndrewHoffmanQA** [comment]
works for me, thanks for the feedback and opening that ticket! closing this ticket. the scope of the change has been tested and passed on 2.7head
