### ISSUE TITLE
Add support for phoenixNAP (pnap) machine driver / RKE2 provisioning

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6695]
For more detail see description in https://github.com/rancher/dashboard/pull/6569 contributed by @pajuga

**Additional context**

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head f2bde24
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2

----------

### Testing: ###

Tested this issue with the following steps:
1. Activate pnap driver under `Cluster Management` -> ` Drivers` -> `Node Drivers`
2. Create rke2 pnap node driver cluster
3. Verify cluster is created successfully

**Result**
Pnap cluster was successfully created
![image.png](https://zube.io/files/rancher/2f9207d0d9c7e38fd8ddd2defa87b544-image.png)
