### ISSUE TITLE
Prevent prefetch of Nuxt links

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#6697]
according to some sources, Nuxt had a memory leak on the `nuxt-link` component when it uses the prefetch option (which is enabled by default). The goal is to disable the option on `nuxt.config`.

Sources:
https://stackoverflow.com/questions/66841758/nuxt-huge-memory-usage-leakage-and-how-to-prevent
https://deltener.com/blog/a-deep-dive-into-the-nuxt-link-component/

Test areas:
Generally make sure that Dashboard is working properly.

**Comment by richard-cox** [comment]
Discussed with Neil, this has been merged for a long time and we'd be aware of any issues by now.
