### ISSUE TITLE
[FEATURE] Logging: Add output form for OpenSearch plugin

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#6701]
**Is your feature request related to a problem? Please describe.**
The upstream banzai logging operator has a new OpenSearch output plugin: https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/opensearch/

With Rancher 2.6.7, rancher-logging has been updated and the new output plugin is now also included.

**Describe the solution you'd like**
The new plugin should be added to the logging output form.

**Comment by ronhorton** [comment]
**Pass - verified in 2.7-head Commit ID cfe318f**

`OpenSearch form is present and functional`
