### ISSUE TITLE
[FEATURE] Logging: Add output form for Redis plugin

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#6702]
**Is your feature request related to a problem? Please describe.**
The upstream banzai logging operator has a new Redis output plugin: https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/redis/

With Rancher 2.6.7, rancher-logging has been updated and the new output plugin is now also included.

**Describe the solution you'd like**
The new plugin should be added to the logging output form.

**Comment by gaktive** [comment]
PR has 2.7.0 as a milestone so @nwmac should I push this out?

**Comment by nwmac** [comment]
Yep @gaktive
