### ISSUE TITLE
[BUG] custom colors are not saved from branding UI

### ISSUE THREAD

**Issue by xhejtman** [rancher/dashboard#6704]
**Setup**
- Rancher version: 2.6.7
- Browser type & version: google chrome 104

**Describe the bug**

After upgrade from 2.6.4 to 2.6.7, it seems that branding does not work any more - link and primary colors. I can change them - use custom color, they are applied if I hit Apply button, but if I reload browser or open rancher from another tab bot link and primary colors are default.

**Comment by richard-cox** [comment]
I've reproduced this. It looks like shell/mixins/branch.js `watch` `color` is triggered anymore, so `setCustomColor` is never called.

**Comment by xhejtman** [comment]
Didn't you consider to switch to new color scheme same as rancher web? Rancher itself is still using colors from rancher 2.5 series, while web pages use differnt blue color, so perhaps this can be default now?

**Comment by richard-cox** [comment]
The general theming has been updated a lot in the 2.6 UI. The blue used on the public rancher website isn't quite suitable for a web app though.

**Comment by thaneunsoo** [comment]
### Reproduction Environment: ###
Rancher version: 2.6.7
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Version 104

----------

### Reproduction: ###
Reproduced using the following steps:
1. Set custom link and primary colors under `branding` in 2.6.4
2. Upgrade to 2.6.7
3. Verify that colors are reset to default
4. Try changing colors and reload the page

**Result**
After upgrading to 2.6.7, the colors were reset to default but the custom color choices were preserved. Upon trying to change the colors, once reloading the page, the colors were reverted to the default color scheme.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/108360907/187263005-c804feae-a2f7-4702-807a-0dadb0733e00.png">

**Comment by richard-cox** [comment]
Note - This will be available to test in `2.6.8-rc2`

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6.8-rc2
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Version 104

----------

### Testing: ###
Tested this issue with the following steps:
1. Set custom link and primary colors under `branding` in 2.6.4
2. Upgrade to v2.6.8-rc2
3. Verify that colors are reset to default
4. Try changing colors and reload the page

**Result** - Pass
Before the upgrade:
![image.png](https://zube.io/files/rancher/a9e82d41a1b143e526c1316feb3816aa-image.png)
![image.png](https://zube.io/files/rancher/d55dbb6daa09212f7fae87e2e8dd1adb-image.png)

After the upgrade:
The custom color selections were preserved
![image.png](https://zube.io/files/rancher/0ebe2133812e1b4a1d36c612814caac3-image.png)
![image.png](https://zube.io/files/rancher/6d699730cd53894bf8a22832b7a08fed-image.png)
