### ISSUE TITLE
[BUG] Order of cluster list is different between the cluster Management page and in the side Menu

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6708]
**On 2.6.7**

1. Cluster that's in `updating` state is displayed the last in the left side Menu.
2. The same cluster is displayed in another order on the cluster Management page
3. No sorting of clusters was performed on Cluster Management page

**Expected:**
Can the list of clusters, order, be the same in both the places to avoid confusion ?

**Comment by gaktive** [comment]
With Point 1, we sort by age, which kinda makes sense based on the updating stage but we should standardize the sort order for both.

**Comment by nwmac** [comment]
I think default sort on home page and cluster mgmt is by name - check this.

I think we need to add a sort in the slide-in menu to sort those by name as well.

**Comment by jameson-mcghee** [comment]
I was able to reproduce this issue on v2.6.7 by following the Steps to Reproduce. However, I no longer see this issue on v2.7-head (Commit ID: 43f25cd) (see screenshots). Therefore I am closing this ticket.

Steps to Reproduce:
* Create a Custom Cluster without registering any nodes for it
* Create an EC2 Node Driver cluster that provisions successfully
* Create another Custom cluster without registering any nodes for it

Note that on v2.6.7 that the Cluster Management and Home pages have the clusters sorted by Age, while the Side-Bar Menu sorts them by State and then Age.
Note that on v2.7-head, however, that the Home, Cluster Management, and Side Bar menu are all sorted by Provider and then Age.

**v2.6.7:**
![image.png](https://zube.io/files/rancher/4da5577145139a58b2c16fe5e65e136c-image.png)

**v2.7-head (Commit ID: 43f25cd):**
![image.png](https://zube.io/files/rancher/a4c8e239ea5e0f4ea9ed0b52faaccce7-image.png)

**Comment by dasarinaidu** [comment]
Woking good on v2.7-head

![image.png](https://zube.io/files/rancher/ea68333a7de0d33492088d3e674e48d9-image.png)
