### ISSUE TITLE
[BUG] JS error in AlertmanagerConfig when clicking on deactivated button

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#6714]
**Setup**
- Rancher version: 2.6.7
- Browser type & version: Safari 15.6.1

**Describe the bug**
When you create a new AlertManagerConfig, the button to add Receivers is deactivated, because it only works after the config was created. You can still click on information bubble in the button, which results in a JS error:

```
[Error] TypeError: Expected "alertmanagerconfigid" to be defined
(anonyme Funktion) — utils.js:558
_callee5$ — client.js:411
tryCatch — runtime.js:63
invoke — runtime.js:294
asyncGeneratorStep — asyncToGenerator.js:3
_next — asyncToGenerator.js:25
(anonyme Funktion) — asyncToGenerator.js:32
Promise
(anonyme Funktion) — asyncToGenerator.js:21
map
_callee6$ — client.js:267
tryCatch — runtime.js:63
invoke — runtime.js:294
asyncGeneratorStep — asyncToGenerator.js:3
_next — asyncToGenerator.js:25
promiseReactionJob

	error
	(anonyme Funktion) (app.js:315690)
	_callee$ (app.js:856)
	tryCatch (app.js:15279)
	invoke (app.js:15510)
	asyncGeneratorStep (app.js:91)
	_next (app.js:113)
	(anonyme Funktion) (app.js:120)
	Promise
	(anonyme Funktion) (app.js:109)
	globalHandleError (app.js:4866)
	_callee6$ (app.js:1528:82)
	tryCatch (app.js:15279)
	invoke (app.js:15510)
	asyncGeneratorStep (app.js:91)
	_throw (app.js:117)
	promiseReactionJob
```

**To Reproduce**
* Create or go to a cluster
* Install Rancher Monitoring
* Go to Monitoring -> Alerting -> AlertmanagerConfigs
* Create a new AlertmanagerConfig
* Click on the information bubble icon of the grayed out/deactivated `Add Receiver` button

**Result**
A JS error.

**Expected Result**
Nothing happens.

**Screenshots**
![Bildschirmfoto 2022-08-22 um 16 47 25](https://user-images.githubusercontent.com/243056/185951764-ec73f352-da1e-448f-9e65-6b138e792310.png)
![Bildschirmfoto 2022-08-22 um 16 48 09](https://user-images.githubusercontent.com/243056/185951773-d0a22579-7be5-4c83-89e5-7b6ed82df523.png)

**Comment by nickwsuse** [comment]
Tested on `v2.7-head Commit ID: ce9a7ae` and on Chrome

Reopening as the JS error still appears when clicking the grayed out `Add Review` button. 

```
utils.js:555 Uncaught (in promise) TypeError: Expected "alertmanagerconfigid" to be defined
    at utils.js:555:17
    at client.js:220:14
    at Array.map (<anonymous>)
    at Dn.<anonymous> (client.js:219:58)
    at v (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
```

**Comment by bashofmann** [comment]
I don't see this JS error anymore. Just tested with rancher/dashboard commit ID `1a9fea755c58bd41f79e5f9186f6a4b7ae495dc5`. Did the version of Rancher that you used for testing maybe not contain the newest dashboard version yet?

**Comment by nickwsuse** [comment]
@bashofmann that appears to be the case as I just tried again on `v2.7-head commit id: d94f42a` and it no longer throws the error.
