### ISSUE TITLE
[BUG] Create or delete resources, the number of resources displayed in the left menu is not automatically refreshed

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#6719]
**Setup**
- Rancher version: v2.6.7
- Browser type & version: Chrom 104.0.5112.79

**Describe the bug**

Create or delete resources, the number of resources displayed in the left menu is not automatically refreshed

**To Reproduce**

1. Create a deployment

**Result**
After the creation is successful, the number of deployments counted in the left menu does not change

**Expected Result**

The number of deployments counted in the left menu should increase by 1

**Screenshots**

![create-deployment3](https://user-images.githubusercontent.com/19684717/186104306-3d77e666-6a91-49f5-b8e9-8ca357e73079.gif)

**Comment by richard-cox** [comment]
Note for QA, there are some additional steps to validate mentioned in the [PR](https://github.com/rancher/dashboard/pull/6784#issue-1357584433)

**Comment by ronhorton** [comment]
**Pass** verified in rancher `2.6-head Commit ID 68215bc`

1. Created `Deployment` - count of deployments incremented
2. created `cronjob` in separate browser - count of cron jobs incremented
3. deleted `cronjob` - count of cron jobs decremented
4. installed new app - number of `installed apps` incremented
5. deleted the new app from another browser window - number of `installed apps` decremented
