### ISSUE TITLE
Disable eslint errors / improve dev settings when not using VSCode 

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#6721]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

**To Reproduce**
Disable Eslint plugin in VSCode
Add extra empty line spaces between code and save
Browser block the UI

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by cnotv** [comment]
If we want to disable the overlay in case of issues, this is a feature implemented in Webpack and it may be disabled by configuration or passing a flag, as defined in their documentation. https://webpack.js.org/configuration/dev-server/#overlay

We may consider replacing eslint configuration on save with Husky/lint-staged pre-commit tasks, which may include `yarn lint --fix` to produce an analogue configuration.

**Comment by nwmac** [comment]
This is an internal developer issue - does not need QA
