### ISSUE TITLE
Show an error popup when running on an unsupported setup #1294

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#6722]
https://github.com/rancher-sandbox/rancher-desktop/issues/1294

**Comment by catherineluse** [comment]
This issue should be filled out with more detail about the definition of an unsupported setup.

Related issues:

- If a user installs Rancher locally with the Docker install, we already have an issue here https://github.com/rancher/dashboard/issues/5666 about notifying the user that Rancher can't manage clusters if it is running on localhost.
- I have also opened https://github.com/rancher/dashboard/issues/5256 to warn users that the Docker install is for testing and development only.
