### ISSUE TITLE
Unreasonable display of imagePullSecrets 

### ISSUE THREAD

**Issue by niusmallnan** [rancher/dashboard#6725]
**Setup**
- Rancher version: v2.6.7
- Browser type & version: Chrome os Mac 104.0.5112.101 x86_64

**Describe the bug**

Kubernetes supports specifying container image registry keys on a Pod. imagePullSecrets must all be in the same namespace as the Pod. The referenced Secrets must be of type kubernetes.io/dockercfg or kubernetes.io/dockerconfigjson.
refer to: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod

However, when creating a workload, all the secrets are displayed in the dashboard.

**To Reproduce**

When creating a workload, switch to the kube-system namespace, and it's easy to see the problem. Because this namespace will contain a lot of secrets.

In addition, when trying to filter secrets, this `metadata.name` will also cause troubles and trigger js errors.
<img width="1147" alt="截屏2022-08-23 下午6 06 43" src="https://user-images.githubusercontent.com/998984/186131833-46179a6d-2aa9-4118-9ea0-908d4cca1ce5.png">

**Result**
All secrets show in the form.

**Expected Result**

Only shows `kubernetes.io/dockercfg` or `kubernetes.io/dockerconfigjson` secrets.

**Screenshots**

**Additional context**

**Comment by AndrewHoffmanQA** [comment]
retested on rancher - 2.6 head 68215bc
retest : failed

see video recording: 

when creating a deployment i cannot get the 'pull secrets' section dropdown to display any data even when the selected namespace has secrets and I am logged in as admin. 
![image.png](https://zube.io/files/rancher/c0873fcf663f1c70d43b3c9379693eb2-image.png)


see video for more examples. 


https://zube.io/files/rancher/e7c34377c0348bc53f0f91bba1cfc35b-retest-6725.mp4

**Comment by AndrewHoffmanQA** [comment]
@Shavindra thank you for the correction! 

**retest- passed**

note: I was unable to prove dockercfg files display. based off of [this ](https://stackoverflow.com/questions/35519072/docker-config-json-vs-dockercfg)documentation I believe users can no longer create dockercfg type secrets, when I create one via kube command the system recognizes it as a dockerconfigjson. logging bug to attach to this work item shortly. 

testing video

https://user-images.githubusercontent.com/89030218/190681062-4ac4f534-da4c-4a47-a2a7-e74bbea843ff.mp4
