### ISSUE TITLE
Workload screen layout issues

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6726]
**Setup**
- Browser type & version: Chrome 101, Brave 1.33

**Describe the bug**
Something recently may have merged after the workloads changes that did this.

- There's a gab between the horizontal tabs and tab content
- The buttons no longer sticky at the bottom

![image](https://user-images.githubusercontent.com/18697775/186135321-740729ba-b847-415a-a250-7d32252e0660.png)

**To Reproduce**
- Navigate to any create/edit page for any workload
- Page content must be less than the height of the tab

**Comment by nickwsuse** [comment]
`Verified on v2.6-head Commit ID: 68215bc`

I tested this alongside https://github.com/rancher/dashboard/issues/6455 and buttons are stickied to the bottom of the page again.
