### ISSUE TITLE
Allow "Minimum ASG Size" to be set to 0

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#6731]
**Describe the solution you'd like**
Currently when specifying "Minimum ASG Size" as "0" the UI automatically changes it to "1" as soon as focus is removed:
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/85187633/186303295-11460804-1a22-4b85-8145-a4dea66880d7.png">
It's requested for the UI to allow 0 as a valid entry in this field.

**Describe alternatives you've considered**
N/A

**Additional context**
Confirmed native AWS Management Console allows 0 as a valid option for the minimum node group size.
This requires back-end change https://github.com/rancher/rancher/issues/38698 to be implemented first.

**Comment by Josh-Diamond** [comment]
@gaktive I've noticed this PR was merged, may we move this ticket to `to-test`? or are we still pending more changes?

**Comment by annablender** [comment]
This ticket is the dashboard issue associated with PR https://github.com/rancher/ui/pull/4887. You'll be verifying this change works by testing https://github.com/rancher/rancher/issues/38698.

**Comment by Josh-Diamond** [comment]
@annablender you are correct.  Technically, i've already validated this with #38698, but have not officially reported results.  Wondering when this will be moved to `to-test`.

cc: @gaktive

**Comment by Josh-Diamond** [comment]
Offline discussion w/ @annablender confirmed this issue is ready `to-test`

**Comment by Josh-Diamond** [comment]
Ticket #6731 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.8`:
1. Fresh install of rancher `v2.6.8`
2. Attempt to provision downstream EKS w/ min_size=0
3. Reproduced - UI changes value to 1 when 0 is entered, upon focus removal

---

Verified on rancher `v2.6-a7c5da0cec039524c3d386bfd26d15697cc546b2-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream EKS w/ min_size=0
3. Verified - UI allows min_size input of 0; cluster successfully provisions
