### ISSUE TITLE
[Bug] Regression admins are unable to lock or set defaults on builtin Roles.

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/dashboard#6737]
**Setup**
- Rancher version: 2.6x
- Browser type & version: Any

**Describe the bug**
Users with the appropriate permissions should be able to edit the `Locked`, `ClusterCreatorDefault` and the `ProjectCreatorDefault` fields on all roleTemplates including builtin templates. As well as the `userDefault` field on globalRoleTemplates. To add and remove default roles such as cluster-owners users will need to edit these fields.

**To Reproduce**
- Login to the Rancher server as an Admin
- navigate to roles `<server_url>/dashboard/c/local/auth/roles#CLUSTER`
- Attempt to edit a builtin role

**Result**
 Users can only view the configuration of builtin roles

**Expected Result**
For Global Roles Admins can edit  `userDefault` field
For Cluster Roles Admins can edit `Locked`and `ClusterCreatorDefault` fields
For Project/Namespace Roles Admins can edit `Locked`and `ProjectCreatorDefault` fields

**Additional context**
The current workaround is to either edit the Roles via Ember UI or Norman.

**Comment by richard-cox** [comment]
This was an intentional change made in 2.6.7 (see https://github.com/rancher/dashboard/issues/6212#issuecomment-1190753427 and https://github.com/rancher/dashboard/pull/6429). Users were not able to edit builtin roles in the old ember UI and in 2.6.7 the new dashboard UI was aligned with it.

**Comment by KevinJoiner** [comment]
@richard-cox Users should not be able to edit the input fields. But the fields that I stated need to be editable on built-in roles. Without editing these fields, users cannot update the default role given when a cluster is created away from the `cluster-owner` role. Users can edit the fields stated above in the Ember UI.

**Comment by richard-cox** [comment]
@jordojordo It looks like in your [screenshot](https://github.com/rancher/dashboard/issues/6212#issuecomment-1190753427) the locked and project creator default radio buttons are disabled. Was that the case pre 2.6.7? I've checked on a new(ish) rancher and the old ui shows them as disabled. Was there anything more to this story? Otherwise we should show the edit page with grants disabled

**Comment by jordojordo** [comment]
@richard-cox Initially I thought those radio buttons were disabled in the old UI. Oddly enough they are not disabled, although they certainly appear to be. I have checked on prior versions (`v2.6.5`, `v2.6.3`) and the behavior is the same.
This an oversight on my part, I discussed alternatives with @nwmac prior to #6429 and we determined that disabling the ability to edit the config was the best solution. We should revisit this to at least give the ability to edit the `Locked` and `ClusterCreatorDefault` fields.

**Comment by anupama2501** [comment]
Upgrade from v2.6.5 >> v2.6-head 28a7473
1. Reproduced as an admin, not able to the edit the config and change to default of global roles, cluster roles and project roles
2. Upgraded the rancher server to v2.6-head
3.  Verified as an admin/restricted admin can update the cluster and project built-in roles.
4. Verified as an admin, global built-in role can be updated.

Verified on v2.6-head 28a7473 
1. As an admin, able to edited the config of built-in roles `Administrator` and changed to User default.
5. Verified while creating a user the admin role was auto selected.
6. As an admin, able to edit the Cluster role `Create new Cluster Drivers` and locked the user
7. As an admin, able to edit the project role `Manage Config Maps` and locked the user
8. Created a new role and verified for the new role we can enable default and lock the user
9. Repeated the steps for Restricted admin - verified restricted admin cannot change global roles but can change cluster and project roles.
