### ISSUE TITLE
Enhancements needed for the Diagnostic page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6739]
**Is your feature request related to a problem? Please describe.**
Enhancements needed for the Diagnostic page

1. Title - `Diagnostics` is vague and from users' pov, it isn't clear what is this page for. Could we add in something more appropriate since its for UI diagnostics?
<img width="1477" alt="Screen Shot 2022-08-24 at 11 22 11 AM" src="https://user-images.githubusercontent.com/26032343/186494397-1c60acd4-15d9-449f-ad9f-62fd8e0acef9.png">

2. Download data button --> It isn't intuitive, what data is going to get downloaded. Everything from the page? or just the log? 

3. `Logs` and `Resource Counts` --> These sections must have more info on what logs (Rancher logs or downstream clusters' logs or in this case logs from the browser ) are these and what resources are there (local cluster? or downstream cluster?)

4. There are resources that have `0` count. can we _not_ display these ? 
<img width="1124" alt="Screen Shot 2022-08-24 at 11 25 43 AM" src="https://user-images.githubusercontent.com/26032343/186494876-d8659a86-e055-4211-9334-a284e8924bd4.png">

**Additional context**
Related to this feature - https://github.com/rancher/dashboard/issues/6544

**Comment by aalves08** [comment]
@kwwii can we take a look at this when we adjust the styling of this page and the about page? Thanks 🙏

**Comment by kwwii** [comment]
Here's a mockup:
![diagnostics.png](https://zube.io/files/rancher/3c269d53c93ab0756da67f6caa5d173b-diagnostics.png)

**Comment by aalves08** [comment]
Hi @jordojordo , as discussed with @nwmac I am passing this one you. Thanks! 🙏 🙇

**Comment by nwmac** [comment]
@jordojordo We can discuss

**Comment by nwmac** [comment]
Specifically:

- Move the latest logs to the bottom
- Compact the System Information table into 3 groups, use name/values with the table for each group
   - Browser
   - System
   - Javascript Memory
- Resource counts - should collapsed by default when more than one cluster
  - Label - Resource counts by cluster
  - Ignore counts when they are 0
  - When collapsed show the following info in the bar - Total resource, Total number of nodes,
- Allow timings to be shown on screen and for each cluster
  - Add a button 'Generate Diagnostic Data' which will go through each cluster, capture timing and add it to the table add another column, use '-' for those we did not time
- Add dialog when users downloads if they have not run the timings against to let them know if they want them, they should use the other button first.

**Comment by dasarinaidu** [comment]
Validated this issue on v2.7-9f1e0435bb45e104ba897c5c329e1f23735843d9-head
Browsers : Chrome and Firefox

**Observation 1: On Diagnostic page : The button name should be 'Generate Diagnostic Data' from the requirement?**

**Steps :**
1. Login to rancher
2. Navigate to 'About' Page
3. Click on Diagnostics page
4. Check for the button with name  'Generate Diagnostic Data'

**Actual:**
1. Not seeing the button with name : 'Generate Diagnostic Data'; User seeing the button name as 'Generate Response Times'

![image](https://user-images.githubusercontent.com/22034884/198149836-34de2218-671d-4233-a85a-8d7c09c9ad77.png)


**Observation 2: Cluster Name is NOT showing for all cluster types (Displaying the cluster ID)**
**Steps:**
1. Login to rancher
2. Navigate to 'About' Page
3. Click on Diagnostics page
4. Check for the Clusters Name associated to the user

**Actual:**
1. Clusters list is displaying properly but the cluster name is not displaying properly (It is displaying the cluster ID) for some of the clusters and some of the cluster types it is displaying correct name
2. Only RKE2 clusters are showing  the correct cluster names
3. RKE, EKS, GKE, AKS clusters are NOT showing the cluster names (Displaying cluster IDs)

**Note :** 
a. I am seeing same information is displaying with v2.6.8

![image](https://user-images.githubusercontent.com/22034884/198150705-1c800b09-0261-4eb0-b401-1ded86364d96.png)


**Observation 3: Firefox browser: System Information is not populating all the information**
**Steps:**
1. Login to rancher
4. Navigate to 'About' Page
5. Click on Diagnostics page
6. Check for the System Information

**Actual:**
1. System Information table missing below fields
    a. System :  OS: macOS, Device Memory: 8
    b. Complete row : 'Javascript Memory Heap Size limit: 4294705152, Total Heap Size: 77133756, Used Heap Size: 70122148'
2. Seeing this information on Chrome
4. Screens attached from Chrome and FireFox

**Note :** 
a. I checked the Javascript enabled flag set to true on my firefox but the full information is not displaying on Firefox
b. I am seeing same information is displaying with v2.6.8

![image](https://user-images.githubusercontent.com/22034884/198151227-7a6ce88c-e1dc-4bf5-a35d-9ef85a704d9b.png)

Missing JavaScript and Memory details on FireFox.

![image](https://user-images.githubusercontent.com/22034884/198151310-ca953c93-4058-4373-aed1-b476692b9ce1.png)

**Comment by dasarinaidu** [comment]
Validations Completed and looks good.

Rancher Ver:  v2.7-9f1e0435bb45e104ba897c5c329e1f23735843d9-head

**Validated this card:**
1. Admin & Standard user
2. Chrome & Firfox
3. All cluster types
4. Standard and Dark mode view


![image](https://user-images.githubusercontent.com/22034884/199085866-87955eef-3961-46f3-b3a9-da3676a2a4a2.png)
