### ISSUE TITLE
these dependencies were not found

### ISSUE THREAD

**Issue by itsymbol** [rancher/dashboard#6742]
..\shell\middleware\shell\middleware\authenticated.js in ./.nuxt/middleware.js
 ..\shell\middleware\shell\middleware\i18n.js in ./.nuxt/middleware.js
 ..\shell\middleware\shell\middleware\unauthenticated.js in ./.nuxt/middleware.js

**Comment by nwmac** [comment]
Can you provide detailed steps - under what situation are you hitting this problem?

**Comment by itsymbol** [comment]
> Can you provide detailed steps - under what situation are you hitting this problem?

situation windows10、node v16.15.0
steps yarn dev

**Comment by itsymbol** [comment]
> Can you provide detailed steps - under what situation are you hitting this problem?
> situation windows10、node v16.15.0
> steps yarn dev

**Comment by yishenqing** [comment]
did you solve this problem please?

**Comment by itsymbol** [comment]
> did you solve this problem please?

not resolved

**Comment by nwmac** [comment]
I think this is an issue on Windows - can you try using the git bash command prompt?

**Comment by itsymbol** [comment]
> I think this is an issue on Windows - can you try using the git bash command prompt?

not resolved

**Comment by nwmac** [comment]
@itsymbol a fix for windows build will be merged shortly

**Comment by nwmac** [comment]
@itsymbol Windows build should now be working - closing. Re-open if you are still having problems.
