### ISSUE TITLE
On Rancher upgrade to v2.6.7, the Azure AD link to update config freezes the UI

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/dashboard#6752]
**Setup**
- Rancher version: v2.6.7 (with an upgrade from v2.6.6)
- Browser type & version: Firefox

**Describe the bug**
If Rancher has a deprecated configuration of Azure AD, the UI shows the banner at the top prompting admins to update the configuration. The banner has a link `Update it here`. Clicking on it freezes the UI, nothing is displayed, except the header.

**To Reproduce**
1. Set up Azure AD in Rancher v2.6.6.
2. Upgrade Rancher to v2.6.7.
3. See the banner at the top. Click the link.

**Result**
The UI is Loading forever with no errors in the console. Only the header is shown grayed-out. I can get around this by going to the Auth Provider screen directly. Locally, I see the `Expected "cluster" to be defined` displayed without Loading.

**Expected Result**
The link should take me to the auth provider screen with a button to update its the auth provider configuration.

**Screenshots**

<img width="2000" alt="Screen Shot 2022-08-25 at 18 32 15" src="https://user-images.githubusercontent.com/17733533/186780196-b40476e4-8d2c-4f37-aa5f-99d8118d387a.png">

<img width="1220" alt="Screen Shot 2022-08-25 at 18 34 38" src="https://user-images.githubusercontent.com/17733533/186781441-b9c48c18-5650-4962-a43a-86a05e9308e3.png">

**Additional context**
When I click Home, there is an error in the console. A full refresh helps, but the issue with the link does not go away.
```All of management.cattle.io.nodepool is not loaded yet console.js:26:30
Find All: [management] userpreference console.js:26:30
Find: [rancher] authconfig azuread console.js:26:30
Uncaught (in promise) TypeError: Expected "cluster" to be defined
    NuxtJS 3
    d runtime.js:45
    _invoke runtime.js:274
    e runtime.js:97
    Babel 4
    T NuxtJS
    _ vue-router.esm.js:2362
    r vue-router.esm.js:2004
    r vue-router.esm.js:2005
    _ vue-router.esm.js:2384
    e NuxtJS
    d runtime.js:45
    _invoke runtime.js:274
    e runtime.js:97
    Babel 6
    O NuxtJS
    _ vue-router.esm.js:2362
    r vue-router.esm.js:2004
    r vue-router.esm.js:2008
    It vue-router.esm.js:2012
    confirmTransition vue-router.esm.js:2392
    transitionTo vue-router.esm.js:2260
    push vue-router.esm.js:2606
    push vue-router.esm.js:3037
    push extend-router.js:12
    push NuxtJS
    j vue-router.esm.js:1139
    VueJS 33```

**Comment by anupama2501** [comment]
Tried reproducing the issue on an upgrade from 2.6.6 >> 2.6.7
This is seen happening when the endpoint update is attempted from home page. If the endpoint update is attempted from cluster management/Users & auth/cluster explorer/global settings we will be navigated to the auth providers page.

**Comment by anupama2501** [comment]
Verified on v2.6-head 79a5328 upgraded from v2.6.5 as an admin user

Pre -reqs

- Installed rancher on v2.6.5 and created 1 node driver linode rke1 and 1 node driver AWS rke2 cluster
- Enabled azure AD auth
- Upgraded rancher server to v2.6-head
- Installed CIS v2 apps in both the downstream clusters and rancher backup in local cluster

Test cases:
1. Update endpoints navigated from home page  - PASS
2. Update endpoints navigated from local cluster explorer - PASS
3. Update endpoints navigated from downstream rke1 and rke2 cluster's CIS app - PASS
4. Update endpoints navigated from cluster management page - PASS
5. Update endpoints navigated from Global settings/Continuous delivery/Virtualization management - PASS
6. Update endpoints navigated from Users/Groups/Roles - PASS
