### ISSUE TITLE
Strings translated in zh-hans is not displayed in the UI

### ISSUE THREAD

**Issue by vickyhella** [rancher/dashboard#6754]
**Describe the bug**
Strings translated in zh-hans is not displayed in the UI

**Screenshots**
![image](https://user-images.githubusercontent.com/63201949/186852890-3c4cc48e-63b7-4dfb-870a-bca7c5045e54.png)

![image](https://user-images.githubusercontent.com/63201949/186852992-232bc768-f0ab-4467-8912-d178c2d053cc.png)

The following strings are also not displayed in the UI:
![image](https://user-images.githubusercontent.com/63201949/186853161-fe3e7d4a-c19c-4060-ba0b-fd958ba1c8d7.png)

**Comment by n313893254** [comment]
Verify fixed in v2.6.9

![image](https://user-images.githubusercontent.com/18737885/198224307-385a1816-6f89-44f9-af47-12d69c973066.png)
