### ISSUE TITLE
sidecar request and limit  configuration displayed in the UI are always the same as the configuration of the main container

### ISSUE THREAD

**Issue by ibayue** [rancher/dashboard#6755]
![image](https://user-images.githubusercontent.com/11729209/186856127-9f0e296c-3d20-43bc-8fa5-80fdfbd1b040.png)
![image](https://user-images.githubusercontent.com/11729209/186856292-6ef0e0a4-3549-45aa-8189-da6e26e4223c.png)
![image](https://user-images.githubusercontent.com/11729209/186856374-bd9610d1-c51a-4004-9ca4-8b415f4af136.png)
![image](https://user-images.githubusercontent.com/11729209/186856479-2ba0500d-ca61-4fbc-beb7-36a6c894cf06.png)
   For pods with sidecars, re-editing the configuration after saving the request and limit configuration of the sidecar modified by the UI does not take effect, but viewing the yaml file has taken effect, and it is found that the sidecar request and limit configuration displayed in the UI are always the same as the configuration of the main container

**Comment by AndrewHoffmanQA** [comment]
see PR for requirements.
tested on 2.6head 68215bc

retest passed- the new way of adding containers functionally works and values are retained when the user saves/edits the files. 

completed an adhoc regression of CRUD on the following resources
- Cronjobs
- Daemonsets
- Deployments
- Jobs
- StatefulSets
- Pods

note: as a user I would find it difficult to manage the names of the containers, if you delete #3 out of 6 and click to create a new container, the container is named #7  however this is cosmetic and a difficulty that existed before the UI update

closing ticket.
