### ISSUE TITLE
RKE2 Cluster provisioning on Harvester: Make image editable

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#6764]
**Is your feature request related to a problem? Please describe.**
For an RKE2 cluster that was provisioned from Rancher on Harvester with the Harvester node driver, the image form field in a MachinePool configuration should be editable.
Currently the form field is disabled when editing. The image is editable in the MachinePool YAML resource though.
When you edit the MachinePool YAML, the behaviour is as expected:
Rancher will perform a rolling update on the MachinePool. One-by-one a new VM with the new configuration is created, joins the cluster, and a VM with the old configuration is removed. The process is the same if you change the CPU, memory or disk configuration.

Implementing this makes it easier to update the OS. Instead of having to do in-place updates, users could provide a new, updated image and then update the MachinePool to recreate the VMs based on the new image.

The image/ami/template field of other node drivers is already editable.

**Describe the solution you'd like**
The image field of a MachinePool is also editable in the form UI.

**Additional context**
The backend works as expected. This is "just" a UI issue.

SURE-5166

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 6b4cf88
Rancher cluster type: single-node docker install
Docker version: 20.10

Downstream cluster type: RKE2 Harvester

----------

### Testing: ###
Tested this issue with the following steps:
1. Provision RKE2 Harvester cluster
2. Wait for cluster to become Active
3. Edit cluster
4. Verify that `Image` is editable

**Result**
The image parameter is now editable and save is successful
![image.png](https://zube.io/files/rancher/e662864dff4f42d39ede0cad1728f08a-image.png)
Older node gets deleted and removed
![image.png](https://zube.io/files/rancher/efd2056d9d34f3c28076ac8fde7b2959-image.png)
