### ISSUE TITLE
Sometimes, the sidebar resource count not consistent with what's displayed

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#6766]
**Setup**
- Rancher version: v.2.6.7
- Browser type & version: Firefox 104.0 

**Describe the bug**
The left side of the UI is used to give a live count of the resources viewed on the right. When changes are made, such as deleting a resource this is not always consistent. 

**To Reproduce**
* Log into Rancher
* Navigate to (for example) `Continuous Delivery`
* Navigate to `Cluster Groups`
* Add or Remove a cluster group

**Result**
* Count on the left is not updated

**Expected Result**
* Count to be consistent

**Screenshots**

After adding 2 Cluster Groups:
![image](https://user-images.githubusercontent.com/5892615/187187680-c423b576-1a53-468e-9ca2-a6cc786b417a.png)

Manual page refresh & After removing 2 Cluster Groups:
![image](https://user-images.githubusercontent.com/5892615/187187746-eb6b26fd-f6e2-4f4a-bdf7-cbe360e8e49b.png)

**Additional context**
This is not specific to Cluster Groups / CD, it can be observed in other parts of the UI. Reproducible on two different instances of Rancher

Refreshing the page rectifies the resource count.

**Comment by richard-cox** [comment]
This might have already been resolved via https://github.com/rancher/dashboard/pull/6784

**Comment by David-VTUK** [comment]
Has this been included in a specific build of Rancher yet @richard-cox? ie `v2.6-head` or similar.

**Comment by richard-cox** [comment]
It's due to release in 2.6.9 and is available in `2.6-head` (since 12th September)

**Comment by David-VTUK** [comment]
Cannot reproduce in `2.6-head` as stated by @richard-cox, looks resolved in #6784
