### ISSUE TITLE
When provisioning K8s clusters of version 1.23+, GKE should have containerd as the default image type and Docker image types should not be available as options

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#6769]
**Setup**
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/8ad5bab930d88c0564fc6c52ecedf5ff583fcd22
- Browser type & version: Chrome

**Describe the bug**

As of 1.24, K8s officially has removed dockershim support. GKE, as a result, has been preparing for this since v1.23 and will not allow you to provision 1.23+ clusters, unless you use containerd images. In the UI, we should handle this usecase better so that this will not confuse users. See below an example of what happens if you provision a hosted GKE cluster that uses Docker images as opposed to containerd images:

![image](https://user-images.githubusercontent.com/52591819/187249267-86b12f09-c30f-42de-b25c-f6b8894809d8.png)

Ideally, if a customer has selected to provision a 1.23+ GKE hosted cluster, the UI should have by default image type `Container-Optimized OS with Containerd`, NOT the default image type `Container-Optimized OS with Docker`. It would even be beneficial to not only change the default, but to not even have Docker images shown in the dropdown when provisioning v1.23+ clusters; that way, a user won't run into this issue at all.

**To Reproduce**

1. Setup Rancher, create a standard user and login as that user.
2. Provision a hosted GKE 1.24 cluster. While provisioning, ensure that your image type is the default `Container-Optimized OS with Docker`.
3. Verify that the cluster fails to create and gives you an error pertaining to Docker images no longer being supported.

**Result**
GKE hosted clusters provisioned with K8s version 1.23+ fail to provision if using the default Docker image type.

**Expected Result**
GKE hosted clusters that are provisioned with K8s version 1.23+ should have containerd as the default image type AND Docker image types should not even appear as an option in the dropdown.

**Comment by snasovich** [comment]
A bit more context on this.

It looks like the options for the "Image Type" dropdown come from the following hardcoded array: https://github.com/rancher/ui/blob/565e22c6b4e794fd25590c2f884adfc49040b33b/lib/shared/addon/google/service.js#L58-L83

Back-end endpoint `gkeVersions` does provide the list of `validImageTypes` and `defaultImageType`, however they are global and are not per k8s version. Note this endpoint is pass-through from GKE API, so we don't have much control over the payload. At a glance, I did not see an option to get a response where image types are separate per each k8s version.

Given this, hardcoding the requested logic in UI is probably the way to go.

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.6-head` https://github.com/rancher/rancher/commit/4e634b6f469b590f2224bc6b58945740316e85fd.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/4e634b6f469b590f2224bc6b58945740316e85fd
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher, create a standard user and login as that user.
2. Navigated to Cluster Management > Create > Google GKE.
3. Supplied required information and scrolled down to the node pool section. I see that `Container-Optimized OS with containerd` is now the default image as seen below:
![image](https://user-images.githubusercontent.com/52591819/189773803-74976923-6dd9-42ec-9fa4-08c9d4442a72.png)
4. Changed the version to be `1.24` and validated that the image type remained as the defined image type in the above step.
5. Provisioned the GKE cluster and validated that it came up as `Active` in Cluster Management and Cluster Explorer:
![image](https://user-images.githubusercontent.com/52591819/189774057-83a0f833-5980-4931-a7ae-b2084863165a.png)
![image](https://user-images.githubusercontent.com/52591819/189774085-d460d964-2eca-4b13-aa7a-204e700381ff.png)
![image](https://user-images.githubusercontent.com/52591819/189774106-735608b3-9c03-43c7-b3df-f0453e20f023.png)
