### ISSUE TITLE
Editing as yaml of a registry secret creates a duplicate secret in the list view

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#677]
Version: master-build(b85ea695f)

Steps:

1. Create a secret "testreg" "by choosing type "registry" option
2. Edit the secret using "Edit as Yaml" option and Save

A duplicate registry is created in the list view as below:

<img width="1033" alt="Screen Shot 2020-05-20 at 11 34 52 AM" src="https://user-images.githubusercontent.com/18536626/82483945-0e0d2f00-9a8e-11ea-9d9e-38dc66126d39.png">

Note:
After a refresh,  the duplicate registry is removed from the list view
The duplicate is created even if no data is changed during edit and just saved as is.

**Comment by vincent99** [comment]
This is a second case of https://github.com/rancher/dashboard/issues/644 that I missed.. verified that they're all updated now.

**Comment by soumyalj** [comment]
Validated with updated master-build(dea919fb2)

**Steps:**
1. Create a secret "testreg" "by choosing type "registry" option
2. Edit the secret using "Edit as Yaml" option and Save

The secret gets edited correctly and is listed in the list view. Duplicate entries are not created after editing.
