### ISSUE TITLE
Rancher UI Can't Get to Bundles Page if Bundle Status is does not exist

### ISSUE THREAD

**Issue by atsai1220** [rancher/dashboard#6771]
**Rancher Server Setup**
- Rancher version: Rancher v2.6.4 and Rancher v2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: v1.21.x
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

If I delete a bundle and refresh the gitrepo object and the status of the object is not present then the UI fails to allow me to view the bundles page.

**To Reproduce**
 
1. Delete bundle
2. Refresh gitrepo object and verify bundle exists with kubectl
3. Browser log indicates missing properties.

**Result**
I can't view the Bundle page to further debug what went wrong.

**Expected Result**

I expect to be able to view Bundle objects even if they do have the status field.

**Screenshots**

Chrome
![image](https://user-images.githubusercontent.com/14171643/176273763-628d01da-c57b-4428-968f-55f38a84bc12.png)
Safari
![image](https://user-images.githubusercontent.com/14171643/176273985-cad6c684-9890-4dda-ab16-f9644db0d468.png)

**Additional context**

**Comment by rak-phillip** [comment]
@gaktive I think this belongs in the dashboard repo

**Comment by MSpencer87** [comment]
_Verified on Rancher v2.7.0-rc9_

Bundles page is reacheable and displayed without errors after bundle deletion and update.


**Steps to reproduce:**

1. Bring up HA Rancher on v2.6.4
2. Provision a few downstream clusters
3. Navigate to Continuous Delivery -> GitRepos and select Add Repository
4. Add the Fleet Examples repo https://github.com/rancher/fleet-examples.git
5. Select the downstream cluster as your target and select Create
6. Navigate to the Bundles tab inside the repo and select the created bundles
7. Delete all bundles from the fleet examples repository
8. Select Force Update
9. Error message is displayed


**Steps for Validation:**

1. Bring up HA Rancher on v2.7.0-rc9
2. Provision a few downstream clusters
3. Navigate to Continuous Delivery -> GitRepos and select Add Repository
4. Add the Fleet Examples repo https://github.com/rancher/fleet-examples.git and set the path, Select Next
5. Select the downstream cluster as your target and select Create
6. Navigate to Continuous Delivery -> Bundles and select the created bundles
7. Delete all bundles from the fleet examples repository and select Force Update
8. No error message displayed, page is functional and update is successful
9. Bundle is visible via kubectl `kubectl get bundles -n fleet-default`
