### ISSUE TITLE
Add Ubuntu 22.04 to Linode node driver template for selection.

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/dashboard#6773]
**Setup**
- Rancher version: v2.6.8
- Browser type & version: Any

**Describe the bug**

Ubuntu 22.04 OS image is not visible on Linode Node driver UI.

**To Reproduce**

1. Create a rancher server v2.6.8
2. Add Linode node driver template
3. Under Instance Options, click on Image.
4. Notice the Ubuntu 22.04 OS image is not listed.

**Result**
The Ubuntu 22.04 OS image is not listed

**Expected Result**

Ubuntu 22.04 OS image is visible and user is able to select it as OS.

**Screenshots**

![linode-node-driver](https://user-images.githubusercontent.com/83208989/187433759-4d919a63-46bf-42a5-86d9-67c5573156f4.png)

**Comment by gaktive** [comment]
Not all the Ubuntu versions available on Linode are compatible with Rancher, so we're not showing the disabled status properly. This may have been the case for a while.

**Comment by vivek-infracloud** [comment]
@gaktive I tested the cluster creation on Ubuntu 22.04 by manually creating a instance on Linode and it worked as expected. So I'm sure the ubuntu 22.04 on Linode supports rancher and k8s v1.24.

**Comment by gaktive** [comment]
Similar question raised in https://github.com/rancher/dashboard/issues/6395 but per https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-7/, Ubuntu 22.04 isn't listed as supported.

Need to track down what's supported then.

**Comment by vivek-infracloud** [comment]
@gaktive Right, Ubuntu 22.04 is not listed as supported yet. But, I am suppose to test the Ubuntu 22.04 support. Once, I test it and close this [issue](https://github.com/rancher/qa-tasks/issues/448) support will be added in support matrix. Is there any other way I can test the Ubuntu 22.04 support with DO and Linode node drivers?

**Comment by gaktive** [comment]
Upon checking with @sowmyav27, the goal is to add support for Ubuntu 22.04 so I've changed these tickets to enhancements with some rewording.

For context, the related backend work - https://github.com/rancher/rancher/issues/38362
And the original docker issue - https://github.com/rancher/rancher/issues/38390

**Comment by gaktive** [comment]
Both of the referenced back-end issues are for milestone 2.7.0, so I assume this issue and the other two 22.04 issues should be as well.

**Comment by gaktive** [comment]
Per QA, this actually did land with 2.6.9.

**Comment by nwmac** [comment]
The Linode UI is managed by Linode - https://github.com/linode/rancher-ui-driver-linode

We'll need to submit an issue there and wait for them to fix and publish a new release and then update Rancher to pull that new release in.

This will not happen in the 2.6.9 timeframe.

**Comment by nwmac** [comment]
Create issue for the Linode Node Driver: https://github.com/linode/rancher-ui-driver-linode/issues/22

**Comment by gaktive** [comment]
Based on the external aspect, this may slip to 2.7.0 or later. I pinged someone at Linode for guidance.

**Comment by gaktive** [comment]
https://github.com/rancher/rancher/pull/39545 under review now so once that's in, this should unblock UI. 

Backend aiming for 2.7.2 so this may be accelerated.

**Comment by gaktive** [comment]
I was told by @Sahota1225 that UI can put this into QA's hands.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, validate that Ubuntu 22.04 appears as a Linode node template and a cluster can be provisioned|

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/8d7ffb9dadde2c1603902a465841aede71dadc97. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/8d7ffb9dadde2c1603902a465841aede71dadc97
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, validate that Ubuntu 22.04 appears as a Linode node template and a cluster can be provisioned|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, when provisioning a downstream RKE1 Linode node driver, noted the following in the node template:
![image](https://user-images.githubusercontent.com/52591819/230458842-54bf4e77-f98a-4dba-a0ea-36e57ee05ccf.png) 
2. Validated that I was able to provision the following two RKE1 v1.25 cluster configurations:
     - 1 etcd, 1 cp, 1 worker
     - 1 etcd/cp, 1 worker
	3. Validated that cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
4. Validated that all pods in the system project page are up and `Active`.
