### ISSUE TITLE
[Rancher 2.6] Add Ubuntu 22.04 OS image as a Digital Ocean node driver template option in rancher UI.

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/dashboard#6774]
**Setup**
- Rancher version: v2.6.8
- Browser type & version: Any

**Describe the bug**

User is not able to select Ubuntu 22.04 OS image with Digital Ocean node driver template

**To Reproduce**

1. Create a rancher server v2.6.8
2. Add Digital Ocean template.
3. Under Droplet options click on Image.
4. Notice that the Ubuntu 22.04 is visible but user is not able to select it as OS.

**Result**
The Ubuntu 22.04 is visible but user is not able to select it as OS.

**Expected Result**

User should be able to select Ubuntu 22.04 image as OS.

**Screenshots**

![DO-images](https://user-images.githubusercontent.com/83208989/187434856-9b23a63b-2740-445a-b0c2-0435a8028ac8.png)

**Comment by gaktive** [comment]
Not all the Ubuntu versions available on Digital Ocean are compatible with Rancher, so we're not showing the disabled status properly. This may have been the case for a while.

**Comment by vivek-infracloud** [comment]
@gaktive I tested the cluster creation on Ubuntu 22.04 by manually creating a droplet on digital ocean and it worked as expected. So I'm sure the ubuntu 22.04 on digital ocean supports rancher and k8s v1.24.

**Comment by gaktive** [comment]
Upon checking with @sowmyav27, the goal is to add support for Ubuntu 22.04 so I've changed these tickets to enhancements with some rewording.

For context, the related backend work - https://github.com/rancher/rancher/issues/38362
And the original docker issue - https://github.com/rancher/rancher/issues/38390

**Comment by gaktive** [comment]
Related ticket for Linode: #6773

**Comment by gaktive** [comment]
Per QA, this did land with 2.6.9

**Comment by nwmac** [comment]
Fix is in Ember with this PR: https://github.com/rancher/ui/pull/4894

**Comment by vivek-infracloud** [comment]
On rancher server v2.6-head user is now able to select Ubuntu 22.04 OS on Digital Ocean template. Hence, closing the issue.  

![do-2204](https://user-images.githubusercontent.com/83208989/191669392-79bc47c2-b680-4cbc-86ab-2e603f64ae7f.png)

**Comment by catherineluse** [comment]
The changes to address this issue (https://github.com/rancher/ui/pull/4894) were added to the `master` branch after the `release-2.6.9` branch was created. As a result, I think the changes did not make it into Rancher v2.6. Therefore I have reopened this issue.

**Comment by vivek-infracloud** [comment]
Tested the issue again on rancher v2.6.11-rc4. Cluster creation with with Ubuntu-2204 is successful.

Since the issue not active anymore, closing the issue.
