### ISSUE TITLE
Cannot see logs in Rancher GUI

### ISSUE THREAD

**Issue by rsivakanth** [rancher/dashboard#6778]
Hi,

I have a strange problem which suddenly has come up on the Rancher GUI. I am unable to see any of the workload logs, even the options toolbar that comes at the bottom of the log tab/window has gone invisible. Even strange is this issue is across all browsers, Safari, Chrome and Firefox. Have tried clearing cache, restarting browsers and even the Macbook. Nothing works.

However, my colleagues accessing the same cluster are able to view the logs without any issues.

And this problem is specific to only one cluster whereas the other cluster Rancher log windows don't have this issue.

I have attached a snapshot of same with Rancher version 2.6.6 highlighted. Please help.

Thanks,
Sivakanth.

![image](https://user-images.githubusercontent.com/2038770/187524287-8324b708-a883-4e93-b5a9-ea7dcd62237c.png)

**Comment by catherineluse** [comment]
Is this bug reproducible in v2.6.7? I ask because I believe this bug may have been fixed in v2.6.7. There is a workaround in this comment https://github.com/rancher/dashboard/issues/6453#issuecomment-1192353956

**Comment by rsivakanth** [comment]
> Is this bug reproducible in v2.6.7? I ask because I believe this bug may have been fixed in v2.6.7. There is a workaround in this comment [#6453 (comment)](https://github.com/rancher/dashboard/issues/6453#issuecomment-1192353956)

Hi @catherineluse,
Thanks for the response. I tried the work around, it threw an error. So I tried another alternative given in the same thread you shared. But unfortunately it didn't work either. Here is the screenshot of the command on the cluster terminal.
![image](https://user-images.githubusercontent.com/2038770/187613520-cee7cab0-1496-499d-93f9-8fb90078d8b4.png)

And screenshot of the log window after command execution:

![image](https://user-images.githubusercontent.com/2038770/187613830-da71f791-a415-40ec-80a1-230589fcc34e.png)

And we are not sure when the 2.6.7 upgrade will happen, it is planned by our infra admin.

Thanks again.
Sivakanth.

**Comment by rsivakanth** [comment]
Ok, looks like I didn't have access to update the kubectl preferences. So our admin fixed it with the workaround. But the issue reappears as soon as we go and select the frequency setting regardless of what it is, viz., 24 hrs, 12 hrs, 30 mins, 1000 lines or whatever. So we have to reset the logs-range once again, logout and login to Rancher to see the logs back.  Conclusion: till upgrade to 2.6.7, if we want to see the logs, just don't mess with the wrench at the bottom :-). (red square in screenshot below)

![image](https://user-images.githubusercontent.com/2038770/187635350-2c200ac2-555d-4ad1-bf54-69c27f2f8d15.png)

Thanks Caroline.
Sivaknath.

**Comment by rsivakanth** [comment]
Closing the issue for now, Thanks to Caroline for pointing out to the workaround. Waiting for 2.6.7 to see the fix done.
