### ISSUE TITLE
Add setting to disable growlers to allow users a chance to diagnose what's going on if they pop up too regularly.

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6793]
Based on rancher/dashboard#6785 , we're impeding customers from troubleshooting network connectivity by popping up growlers all the time.

We need a setting to temporarily turn these off. Perhaps under Troubleshooting.

The thinking is that this behaviour crept in here:
https://github.com/rancher/dashboard/issues/5093#issuecomment-1188467756

**Comment by gaktive** [comment]
Talk to @nwmac before starting for design ideas.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 105

----------

### Testing: ###

Tested this issue with the following steps:
1. Go to `Global Settings` -> `Performance`
2. Select `Enable incremental loading` and use default value
3. Wait for around similar time of when rancher was throwing the websocket error (For me it was about 30 minutes)
4. Verify that UI does not throw websocket error

**Result** - Pass
The websocket error was not thrown when using the default values.
![image.png](https://zube.io/files/rancher/8093000009af27b0bbf5779629977049-image.png)
