### ISSUE TITLE
Node List/Details Internal and External IP mismatch in the UI

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#680]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard
2. Navigate to Nodes
3. In the Node list check the Internal/External IP column 

**Result:**

Nodes with only external IP, the IP is rendered in the Internal part of the column.
In Node details the external IP is listed as Internal IP for each node.

![Screen Shot 2020-05-20 at 4 53 38 PM](https://user-images.githubusercontent.com/27659/82508781-f8fac500-9aba-11ea-9e99-9a519b655d9b.png)
![Screen Shot 2020-05-20 at 4 55 59 PM](https://user-images.githubusercontent.com/27659/82508790-fef0a600-9aba-11ea-97f1-0f9a490cd8df.png)

**Environment information**
- Rancher version: 
  - `master-head (05/20/2020)` b85ea695f  
  - `2.4-head (05/20/2020)` 8e20687a4 with `CATTLE_DASHBOARD_INDEX=https://releases.rancher.com/dashboard/latest/index.html`
- Installation option (single install/HA): Single
- Cluster type RKE/DigitalOcean.

Related to: https://github.com/rancher/dashboard/issues/241

**Comment by codyrancher** [comment]
@izaac what are you using to determine that the ip is external vs internal? The API seems to be indicating the ip to be internal.

![image](https://user-images.githubusercontent.com/55104481/83662344-357af600-a57c-11ea-9765-83423ee0cf1b.png)

I'm replacing the hose so I don't mind the IP getting out.

**Comment by codyrancher** [comment]
@vincent99 when looking at the annotations of the node I see 
```
"rke.cattle.io/external-ip": "64.227.60.213",
"rke.cattle.io/internal-ip": "64.227.60.213",
```

Should the annotations be used instead of the status for determining internal vs external ip?

**Comment by izaac** [comment]
@codyrancher I used the YAML info to look into the addresses network information. v3 API has more addresses information scattered in the json object.

Annotations are also in the v3 api response:

```json
"rke.cattle.io/external-ip": "18.191.x.x",
"rke.cattle.io/internal-ip": "172.31.x.x",
```

I would have to double check if external-ip/internal-ip are the same what's the behavior in the Ember UI as to what's rendered.

**Comment by izaac** [comment]
This is now Looking better @codyrancher and it seems that the same ip address displayed is also a known issue according to this comment: https://github.com/rancher/dashboard/pull/725#issuecomment-639145600

But I'm missing the issue associated with it @deniseschannon 

I'm closing this issue in the meantime. 
Validated in Rancher
- `master-head (06/09/2020)` 78b2f4dc5 
- `v2.4-head (06/09/2020)` d0a55f080
