### ISSUE TITLE
Workload storage mount point for volumes should be on containers

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#6800]
> Need to remove the mount points config from the the pod.
> Need to add a storage tab to the container to configure volume mounts - this should allow multiple - same fields as are 
> currently in the UI above - but you will need a drop-down to allow the user to choose the volume to mount.

**Describe the bug**
REF: https://github.com/rancher/dashboard/pull/6632#issuecomment-1235287918
REF: https://github.com/rancher/dashboard/pull/6632#issuecomment-1233479509

**To Reproduce**
Navigate to Cluster Explorer > Cluster > Workload > Deployment
On the Pod tab there is a sub tab called Storage. 
Mount point should be on the container

**Expected Result**
Should have mount volume path on the container

![image](https://user-images.githubusercontent.com/1387263/188136609-2a73a0e3-cf3c-4de7-a11f-616a5c6d4bf0.png)
![image](https://user-images.githubusercontent.com/1387263/188136756-684a5fc4-38c3-4367-8dda-4bfc176b1f99.png)

**Comment by gaktive** [comment]
For QA, 2.6.9 is addressed by https://github.com/rancher/dashboard/pull/6886

2.7.0 (pending review): https://github.com/rancher/dashboard/pull/6986 so if you'd like a separate ticket to track that work, let me know and I can create one.

**Comment by nickwsuse** [comment]
`Verified on v2.6.9-rc3`

The Mount Point field is now on under container -> storage and mount points can be added and saved as expected for deployments. Multiple mount points and volumes can be added as well, so it looks like this is good to go.
