### ISSUE TITLE
Add UI Enhancement to Warn Users of EKS 0 Nodes in Node Group Behavior

### ISSUE THREAD

**Issue by annablender** [rancher/dashboard#6808]
**Is your feature request related to a problem? Please describe.**

Per issue https://github.com/rancher/rancher/issues/38698, the AWS SDK was updated to v1.44 which allows EKS clusters to be provisioned with node groups with 0 nodes. As stated in [this comment](https://github.com/rancher/rancher/issues/38698#issuecomment-1227776792) and @Josh-Diamond's [test results](https://github.com/rancher/rancher/issues/38698#issuecomment-1233580417), an EKS cluster will not become/stay active in rancher if there are 0 nodes in all node groups. This is not a bug. If there is no node to run the downstream agent on, the cluster won't be able to connect back to the rancher server.

**Describe the solution you'd like**

We want the UI to show a warning if total number of desired nodes across of all node groups is 0 to let the user know that the cluster won’t come up as active until at least one node is available. Ex: _There are 0 nodes available to run agent. Cluster will not become active until at least one node is available._

**Comment by Josh-Diamond** [comment]
Ticket #6808 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.6-28a74733d5a7bf24f114b4ad4daf84d663b6a683-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream EKS cluster w/ desired_nodes set to `0`
3. While cluster provisions, visit `Cluster Management` > `Cluster Details`
4. Verified - Banner seen; 
    - `There are 0 nodes available to run the cluster agent. The cluster will not become active until at least one node is available`

Screenshot:

`Step 4`
<img width="1302" alt="Screen Shot 2022-09-15 at 3 23 43 PM" src="https://user-images.githubusercontent.com/46494969/190524685-1344c189-3598-4aaf-8cb2-316365bd0027.png">
