### ISSUE TITLE
Unable to view or visit a custom cluster driver

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6810]
**Setup**
- Rancher version: 2.6.8

**Describe the bug**

- Custom cluster drivers are kontainerdriver resources
- For custom clusters that are created (and not built in) the id is transient (per instance). For example `kd-mn64v`
- There are two issues with this
  - The custom driver card shown when creating the cluster uses the id as a key for the localisations and image resources. These are baked in and won't be able to handle the transient id
  - The id is used when visiting the ember page for the custom cluster driver's ui (see url). However the ember ui uses the name to find resources (in steps below this is civo)

**To Reproduce**
- fetch and run the cluster driver foles
  - ~Fork https://github.com/opentelekomcloud/ui-cluster-driver-otc~
  - Clone https://github.com/richard-cox/kontainer-engine-driver-otc 
  - Serve this up via `npm install && npm start  -- --name=mydriver`
- Create a new cluster driver
    - ~Download Url: https://otc-rancher.obs.eu-de.otc.t-systems.com/cluster/driver/1.0.2/kontainer-engine-driver-otccce_linux_amd64.tar.gz~
    - Download Url: https://github.com/richard-cox/kontainer-engine-driver-otc/releases/download/v1.0.1/kontainer-engine-driver-mydriver_1.0.1_linux_amd64.tar.gz
    - Custom UI URL:  http://localhost:3000/component.js
    - Whitelist Domains: localhost
- Go to cluster --> create

**Result**
- cannot navigate to the create cluster driver's custom ui
- custom cluster driver card on create cluster page won't show correctly on no-dev systems

**Screenshots**
![image](https://user-images.githubusercontent.com/18697775/188654576-1ddd54bd-bc39-4ff4-8f70-6b070c5afb57.png)

**Additional context**
Dashboard l10n for cluster drivers - https://github.com/rancher/dashboard/blob/master/shell/assets/translations/en-us.yaml#L1565 
Dashboard asset for cluster drivers - https://github.com/rancher/dashboard/blob/master/shell/edit/provisioning.cattle.io.cluster/index.vue#L294

To get around some issues above in dev `KONTAINER_TO_DRIVER` could be used (maps driver id to name), however won't work for prod as the id changes.

Could use something like an annotation on the kontainerdriver that overrides the 'id' where `KONTAINER_TO_DRIVER` is used.

**Comment by richard-cox** [comment]
@nwmac @aalves08 In case i lost track, this is the issue discussed in our previous call that should be done with work to `extenionise` node drivers

**Comment by richard-cox** [comment]
@nwmac @aalves08 In case i lost track, this is the issue discussed in our previous call that should be done with work to `extenionise` node drivers

**Comment by richard-cox** [comment]
@nwmac @aalves08 In case i lost track, this is the issue discussed in our previous call that should be done with work to `extenionise` node drivers

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/d3b5469238e965e54306f74d0e98a47b780cbe80.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/d3b5469238e965e54306f74d0e98a47b780cbe80
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As an admin user, activate cluster drivers and validate that they properly showing and can be visited|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As an admin user, navigated to Cluster Management > Drivers > Cluster Drivers.
2. Activated Linode LKE, Open Telekom Cloud CCE and Oracle OKE.
3. Logged out and logged in as a standard user.
4. Navigated to Cluster Management and validated that they are displaying successfully:
![image](https://github.com/rancher/dashboard/assets/52591819/57bcab4a-adb7-4b83-abaa-7a7aee6dead9)
5. Clicked Linode LKE and vlalidated that it is asking for credentials.
     - I am unauthorized on my end for Linode LKE and Rancher appropriately shows an error message for it despite using active access token:
![image](https://github.com/rancher/dashboard/assets/52591819/abb3f2e8-e350-4f29-8320-f6e226e40119)
