### ISSUE TITLE
Container Component - Design Feedback

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#682]
Note: This requires https://github.com/rancher/dashboard/pull/664 to be merged before being fixed. 

- [x] Review how the info bubbles look inside a labeld input. Note: I found them really hard to hover over whenever I've tried to look at one. 
- [x] Review how/where could we put the `REMOVE` for the container. 
- [x] Review how to add/drop capabilities, ensure there is bottom padding from the capability:
<img width="541" alt="Screen Shot 2020-05-18 at 9 39 12 PM" src="https://user-images.githubusercontent.com/11410997/82285335-13645f80-9950-11ea-972d-7d0e664355af.png">
- [ ] The add/drop capabilities field is a different height compared to regular inputs

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1025
