### ISSUE TITLE
Charts filtering doesn't work if an App doesn't have description

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6823]
Internal Ref: SURE-5191
 
If you have Helm charts that don't have descriptions, when filtering, these match the filter, when they should not.

1. Explore a cluster
2. Go to 'Apps'
3. Go to 'Repositories'
4. Add the Helm Repository: https://charts.truecharts.org
5. Go to Charts
6. Type `test` into the filter, you'll see that charts with an empty description match the filter, when they should not - e.g. the `fsm` and `notarious` charts show

**Comment by ronhorton** [comment]
**Pass** Verified in `2.6-head Commit ID 68215bc`
1. added `https://github.com/truecharts/charts` as repo
2. searched `test`
3. referenced charts, `fsm` and `notarious`, do not show

<img width="1627" alt="2022-09-12_14-39-32" src="https://user-images.githubusercontent.com/89212856/189733461-3a05c9d4-2100-4e69-a467-7985508811d7.png">
