### ISSUE TITLE
Add EKS 1.23

### ISSUE THREAD

**Issue by Sahota1225** [rancher/dashboard#6826]
Detailed Description 
Add support for EKS 1.23

**Comment by gaktive** [comment]
Related backend work: https://github.com/rancher/rancher/issues/38837

**Comment by markusewalker** [comment]
**QA TEST PLAN**
1. Setup Rancher, create a standard user and login as that user.
2. Navigate to Cluster Management > Amazon EKS.
3. Fill in initial prompts until you see the `Cluster Options`; validate that the `Kubernetes Version` has 1.23 and that it is the default.
4. Provision an EKS cluster with 1.23 and validate that it is successful.

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.6-head` https://github.com/rancher/rancher/commit/a3b5237ce1da4228c97df7552d57464c64947b3b and `v2.7-head` https://github.com/rancher/rancher/commit/8a2e68267c882a8adf612a29ae2bf3274a4d8572.

**ENVIRONMENT DETAILS**
- Rancher install:
     - 2.6: Helm
     - 2.7: Docker
- Rancher version:
     - 2.6: `v2.6-head` https://github.com/rancher/rancher/commit/a3b5237ce1da4228c97df7552d57464c64947b3b
     - 2.7: `v2.7-head` https://github.com/rancher/rancher/commit/8a2e68267c882a8adf612a29ae2bf3274a4d8572
- Browser: Chrome	

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher, created a standard user and login as that user.
2. Navigated to Cluster Management > Amazon EKS.
3. Filled in initial prompts until I saw the `Cluster Options`; validated that the `Kubernetes Version` has 1.23 and that it is the default:
![image](https://user-images.githubusercontent.com/52591819/190475942-8de84808-d87b-4da9-a2b5-dfdd7df4733b.png) 
4. Provision an EKS cluster with 1.23 and validated that it is successful in Cluster Management and Cluster Explorer:
![image](https://user-images.githubusercontent.com/52591819/190475880-19a9bb6b-2907-47b6-8cb7-e716ca7ba68b.png)
![image](https://user-images.githubusercontent.com/52591819/190475900-dc397409-7379-427e-982c-9db35664bca8.png)
![image](https://user-images.githubusercontent.com/52591819/190475918-4b25072b-cd1f-4323-af46-910f43567690.png)
