### ISSUE TITLE
Split out the multi-purpose `dev` user preference

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6830]
**Is your feature request related to a problem? Please describe.**
The single `dev: boolean` userpreferences toggles off/on a lot of features. This needs to become more granular and easily support additional preferences planned for the future

**Describe the solution you'd like**
- `dev` userpreference becomes a JSON stringified object containing properties for all the existing uses cases. To confirm, but i think these are currently
  - `View in API`
  - dark theme toggle keyboard shortcut
  - show namespaces managed by rancher
- the user preference page should be updated to cover enable/disable of all existing features independently
- we should support legacy systems where this is still a boolean (all existing features enabled / all existing features disabled)
  - this will be updated to the object when the user changes the one of the preferences for the first time
- places that check this preference should use a new `UserPreference` 'service' like utils file
  - This will allow us to easily integrate additional checks like if the user is admin

**Comment by nwmac** [comment]
I think this is done?

**Comment by richard-cox** [comment]
This was completed as part of https://github.com/rancher/dashboard/issues/6289
