### ISSUE TITLE
Change Menu Item "Workload" to "Workloads"

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#6832]
The page title itself says "Workloads". We should be consistent

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: 38979f8`

The side nav menu item now says `Workloads` to match the page title
![image](https://user-images.githubusercontent.com/107147272/205400138-a608f318-de2a-4682-9118-faa1531ccd3d.png)
