### ISSUE TITLE
Provider field on Imported clusters states "Imported" instead of cluster type

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#6836]
**Setup**

- Rancher version: v2.6.7 & v2.6-head Commit ID: f900172
- Browser type & version: Brave - v1.43.89 (Chromium v105.0.5195.102)

**Describe the bug**

Clusters that are imported into Rancher are showing their Provisioner as "Imported" instead of the cluster type (e.g. RKE, K3S, etc.)

**To Reproduce**

1. Start a Rancher server, and login as admin
2. Navigate to the Home page
- Note that the Provider column for the local cluster states "Imported Imported"
4. Create a cluster using RKE and then import the cluster into Rancher
- Note that the Provider column for the local cluster states "Imported Imported"
5. Navigate to the Home page
- Note that the Provider column states "Imported Imported"

**Result**

The Provider column for the local cluster states "Imported Imported"

**Expected Result**

The Provider column contains the correct information

**Screenshots**

v2.6.7:
![image](https://user-images.githubusercontent.com/13294321/189216967-f6279438-8cbe-48bd-aeb1-07c89c1f3155.png)
![image](https://user-images.githubusercontent.com/13294321/189217291-7a3bebd9-8b1e-49ab-88b9-5d6d8deb2186.png)

v2.6-head:
![image](https://user-images.githubusercontent.com/13294321/189215348-d9cffff2-2c26-4144-85c4-17e27fa20a4e.png)
![image](https://user-images.githubusercontent.com/13294321/189220761-eac57127-e25e-4267-8050-ef57c30c2b43.png)

**Additional Information**

This is reproducible as admin or as a standard user

**Comment by jameson-mcghee** [comment]
Just for contrast, here is what the Provider field looks like for the local cluster on v2.6.6
![image](https://user-images.githubusercontent.com/13294321/189221300-8e95bda3-b97c-479d-9468-c98fdcff560e.png)

**Comment by catherineluse** [comment]
Possibly related to https://github.com/rancher/dashboard/issues/6447

**Comment by nwmac** [comment]
Need to validate if this is still an issue on 2.7

**Comment by susesgartner** [comment]
@gaktive I just checked v2.8-alpha1 and while an imported rke2 cluster I created did show the correct info, the local cluster still displays the wrong information. 

<img width="933" alt="image" src="https://github.com/rancher/dashboard/assets/136753565/0843f492-e830-4b6e-9c5c-c6f5ba2ce82a">

**Comment by gaktive** [comment]
@susesgartner are you able to test on `master` at all and see if that's working as expected there? I had one engineer look and they couldn't repro it there.

**Comment by susesgartner** [comment]
@gaktive I just tested it again on v2.8-head which is using the master branch of dashboard (I believe v2.8-alpha also uses the master dashboard branch) and I still see "imported imported" for the local cluster.

<img width="884" alt="image" src="https://github.com/rancher/dashboard/assets/136753565/040eae38-727b-437b-81ad-44add4c16253">

<img width="1163" alt="image" src="https://github.com/rancher/dashboard/assets/136753565/30dfb011-18ba-4a11-bda8-c60969edb250">

**Comment by gaktive** [comment]
@susesgartner thanks. I'll put this in our backlog again and have someone look at this.

**Comment by mantis-toboggan-md** [comment]
@susesgartner is this a docker or helm rancher install? If the latter, what k8s distro/version did you install rancher on?

**Comment by susesgartner** [comment]
@mantis-toboggan-md It was a helm install and the local cluster is using k8s: v1.26.8.

**Comment by aalves08** [comment]
We might be able to mock a valid `imported cluster`, I think. Not sure about the amount of work it would entail, but at first glance it seems doable. If that's the case, then `automation-candidate`

**Comment by aalves08** [comment]
As an e2e it would fit nicely after https://github.com/rancher/dashboard/blob/master/cypress/e2e/tests/pages/manager/cluster-manager.spec.ts#L448-L488

**Comment by izaac** [comment]
Looks good. The added check makes use of a real cluster imported during the automated Rancher setup.

@aalves08 please let us know what's a pain about using existing examples of provisioning clusters, we could work something out. @nwmac @richard-cox
