### ISSUE TITLE
Workload form saves incorrect settings for workloads with multiple containers

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6837]
Rancher version: v2.6.8

When users edit workloads with multiple containers, the commands, arguments and environment variables are not populated correctly in the form.

When the selected container is changed, the UI does not switch the command/args/environment variables properly. The view for one container shows the settings that the user entered for a different container.

To reproduce:

1. Create a Deployment with two containers in the spec, container A and container B. Enter different commands, arguments and environment variables for each container
<img width="1101" alt="Screen Shot 2022-09-08 at 3 02 47 PM" src="https://user-images.githubusercontent.com/20599230/189234275-ef62aa2c-cb38-40da-be4f-471f4892786c.png">

2. After the Deployment is created, go to it again and click Edit Config.
3. Go to the config for container B and see that in the form, all the commands/args/variables for container A have overwritten the values for container B
4. Click Edit as YAML - you can see that the values for container B are still there.
5. Click Back to Form - you can see that now the opposite has happened. Both containers are showing the container B values, so it looks like values for container B have overwritten container A.

Expected behavior:

- After creating a deployment, you can edit it and see different sets of values for each container

This bug was originally reported in the Rancher Users Slack. https://rancher-users.slack.com/archives/C3ASABBD1/p1662559987818299 The user provided this gif showing the behavior:

![rancher-2 6 8-edit-multi-container](https://user-images.githubusercontent.com/20599230/189231850-2b9f2689-dc04-48c2-a062-8fd56a8c176b.gif)

Added to the v2.6.9 milestone because it is a regression.

**Comment by nickwsuse** [comment]
`Verified on v2.6-head Commit ID: 68215bc`

I tried deployments with two, three, and four containers and after saving them and editing the config they all had the correct commands and variables. Editing as YAML and going back to form also caused no changes on the UI.
