### ISSUE TITLE
When provisioning a private GKE cluster, there is no `Registration` tab showing the registration command to connect the cluster to Rancher

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#6838]
**Setup**
- Rancher version: `v2.6.8`
- Browser type & version: Chrome

**Describe the bug**

Similar to previously-logged issue https://github.com/rancher/dashboard/issues/6036, when you go to create a private GKE cluster within Rancher, there is no registration tab present. That means, if you do not copy the registration command presented after you provision the cluster, you need to go to the old UI and get the UI that way:

![image](https://user-images.githubusercontent.com/52591819/189240660-5e4440a6-a206-41a8-83a5-e45e62a6b570.png)

As we did with EKS and AKS, we need to ensure that we expose the registration tab so that it is easier for users to be able to find the registration command needed to finish configuring their private GKE clusters in Rancher.

**To Reproduce**

1. Setup Rancher, create a standard user and login as that user.
2. Navigate to Cluster Management and choose GKE.
3. Fill out the prompted information and ensure that you specify that this is a private cluster.
4. Once the cluster appears in Cluster Management, click the cluster and note that there is no `Registration` tab to grab the registration command.

**Result**
There is no registration tab containing the `kubectl apply` command to register the cluster.

**Expected Result**
There needs to be a registration tab, similar to what we have for private AKS and private EKS clusters.

**Comment by gaktive** [comment]
We can mimic what we have with EKS & AKS already.

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/eab28ddaeeb772894c35a7e86b0e37d3cb484b8c.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/eab28ddaeeb772894c35a7e86b0e37d3cb484b8c
- Browser: Chrome

**TEST RESULT - PASS**

**VERIFICATION STEPS**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigated to Cluster Management > Google GKE.
3. Provisioned a private GKE cluster.
4. Clicked on the cluster and noted that there is now a `Registration` tab:
![Screen Shot 2022-10-04 at 10 57 19 AM](https://user-images.githubusercontent.com/52591819/193892509-c04546b2-2b93-4154-a05b-f8dc424004a1.png)
