### ISSUE TITLE
Subnets selection is missing once a user clicks on any other operation on the page during EKS cluster creation

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/dashboard#6840]
**Setup**
- Rancher version: 2.6.8
- Browser type & version: Chrome/MacOS

**Describe the bug**
EKS->Create Cluster-> Networking->Subnet->Custom: Subnets selection is missing once user click on any other operation on the configuration page. 

**To Reproduce**
Steps:

1.	Create AWS Instance
2.	Provision Rancher
3.	Create a cluster from Rancher – On Network Configuration page 
4.	Select Custom and select a Subnet under a VPC
5.	Perform any other operation on the page (except click on NEXT)
Ex: Select/Deselect Private
6.	Check for the Subnets selection

**Result**
Actual:
1.	The selected subnets information is removed, user has to reselect the Subnets
2.	The Next button is enabled

**Expected Result**
1. Selected Subnets should have the focus till the user choose to change the options

**Screenshots**
On this screen if user click on any other option - the Subnet selection is loosing the selection

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/22034884/189243862-ac6c2f7f-689e-4b50-ba53-74e980edb5b1.png">

**Comment by gaktive** [comment]
This appears to be an ember issue that may have been around for a while. Need to dig in.

**Comment by nwmac** [comment]
WIll check when we port EKS to Vue

**Comment by nwmac** [comment]
@mantis-toboggan-md One to check when the port is done - moving to your next up
