### ISSUE TITLE
Detail page for Pods uses detail page for Workloads

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6842]
**Setup**
- Rancher version: 2.6-head

**Describe the bug**
- There is a detail/pod component
- When visiting the detail page for a pod it uses detail/workload instead
- this throws lots of errors.... as it tries to show the pods that the pod contains...

**To Reproduce**
- Navigate to Pods list
- Click on a Pod

**Result**
- Pods by State is shown, errors in console

**Expected Result**
- Details for pods is shown, not details for workloads

**Screenshots**
![image](https://user-images.githubusercontent.com/18697775/189371595-da419b8b-f639-4d33-9810-a94542db11ec.png)

**Comment by richard-cox** [comment]
It's worth checking that `detailComponent` is the correct type in `./shell/components/ResourceDetail/index.vue`. The 'id' param doesn't look right. `type-map/importDialog`'s `getters.componentFor(rawType, subType)` might be broken

**Comment by gaktive** [comment]
From what I can see, https://github.com/rancher/dashboard/pull/6952 was merged into `release-2.6.9` so we'll need a ticket and PR to get this in for 2.7.0 as a forward port.

**Comment by AndrewHoffmanQA** [comment]
retest failed 

tested on -2.6head 2e00266

upon navigating to the pods section of the pods section of the UI, I still see the Deployment tabs and the page does not match what is displayed in the PR fix video. 


![image](https://user-images.githubusercontent.com/89030218/192853403-4e974659-3cf5-4004-b22b-59b0635cba60.png)

**Comment by AndrewHoffmanQA** [comment]
retest passed. tested on local HA 2.7head 62f7959

when navigating to the pod section of the UI, users now see the correct tabs and corresponding data. closing ticket

![image.png](https://zube.io/files/rancher/530a34840766c6833e02b1de058f2ac3-image.png)

**Comment by AndrewHoffmanQA** [comment]
confirming this change also made it into 2.69rc3. 

tested on local HA


keeping in done column
![image](https://user-images.githubusercontent.com/89030218/193666701-38839e08-9ae3-47b1-9f6e-8e4dab4e5f90.png)
