### ISSUE TITLE
The `Cloud Configuration` field is empty after creating a machine registration in Elemental

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#6843]
**Setup**
- Rancher version: `v2.6.8`
- Browser type & version: Chrome

**Describe the bug**

When creating a `Machine Registration` with Elemental, there is the `Cloud Configuration` portion which outlines the YAML needed to create the ISO for other Elemental-dedicated machines to boot from. Currently, it looks like this:

![image](https://user-images.githubusercontent.com/52591819/189385322-0a202712-3efc-4b32-ab9a-cd798bceae6e.png)

However, after you create the machine registration it is left blank as shown below:

![Screen Shot 2022-09-09 at 8 22 12 AM](https://user-images.githubusercontent.com/52591819/189385506-78dc3469-cdbf-46a4-b730-517b6f0ffa42.png)

The `Cloud Configuration` should be filled out as it is when creating, not left blank. An administrative user may need to edit the config of that YAML, but without a reference point, it can make that simple task unnecessarily harder.

**To Reproduce**

1. Setup Rancher and ensure that the `elemental-operator` is applied to Rancher.
2. Navigate to OS Management > Create Machine Registration.
3. Create a machine registration.
     - Note that the `Cloud Configuration` is populated prior to creation.
4. Validate that the `Cloud Configuration` is empty.

**Result**
The `Cloud Configuration` YAML field is empty.

**Expected Result**
The `Cloud Configuration` YAML field should not be empty.

**Comment by juadk** [comment]
Likely a duplicate of https://github.com/rancher/dashboard/issues/6458

**Comment by markusewalker** [comment]
Closing as a duplicate of https://github.com/rancher/dashboard/issues/6458.
