### ISSUE TITLE
Bulk actions button is displayed as %harvester.tableHeaders.actions%

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#6847]
**Setup**
- Rancher version: v2.6-head 68215bc
- Browser type & version: Chrome

**Describe the bug**
In a minimized web page if we try to select a deployment/node, the bulk actions button is displayed as %harvester.tableHeaders.actions%

**To Reproduce**
From cluster management page >> minimize the web page >> Select a cluster >> check the bulk actions button

**Result**
Instead of displaying as actions its displayed as %harvester.tableHeaders.actions%

**Expected Result**
Expected the bulk actions button to be displayed as `Actions`

**Screenshots**
<img width="500" alt="bulkactions" src="https://user-images.githubusercontent.com/38144301/189673197-cd89abe7-1a4e-4d63-972c-ece4204749c8.png">

**Comment by richard-cox** [comment]
@anupama2501 Great find!

**Comment by anupama2501** [comment]
Verified on v2.6-head a3b5237
From cluster management page/Cluster explorer RKE1 and RKE2 node driver clusters/Users and auth >> Bulk actions button is displayed as `Actions`
