### ISSUE TITLE
query param not working for shared links for dashboard/c/c-cnfw6/explorer/pod?q=somepod

### ISSUE THREAD

**Issue by Ashtonian** [rancher/dashboard#6848]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart):
- 	helm chart via eks vs tf module 

**Information about the Cluster**

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
 Admin

   
**Describe the bug**
When sharing a link sometimes the query parameters don't seem to work. For example when viewing pods, then using the search to filter pods it updates the url to something like `dashboard/c/c-cnfw6/explorer/pod?q=js` however if I copy/paste that it doesn't filter the pods. In fact it just changes the url to `dashboard/c/c-cnfw6/explorer/pod`

**To Reproduce**
go to workloads>pods page in dashboard
attempt to filter pods list
copy and paste url in new tab
notice lack of filtering 

**Expected Result**
The query parameters to work and filter the pod list.

**Comment by rak-phillip** [comment]
@gaktive I would classify this one as a dashboard issue, transferring for triage.

**Comment by Ashtonian** [comment]
> List sort and filtering are maintained locally per page and no longer read from query params. The values added to the url are artefacts of that old process and should be removed (or not added)

Thats a very unfortunate regression if the end result is that a user can't share a link filtered page simply by copy pasting, especially when you have several hundred pods.

**Comment by NiklasTreml** [comment]
is this also true for projects? we have a use case where we need to link users to their projects directly

**Comment by richard-cox** [comment]
@NiklasTreml There's no project screen in 2.6+, there is a per user filter that restricts resources though. If you'd like to manually apply that to their project before your user visits the UI you can do so by mimicking the API request
```
v1/userpreferences/<user id>

data: {
  ...
  ns-by-cluster: "{\"<cluster id>\":[\"project://<project id>\"]}"
  ...
}
```

**Comment by NiklasTreml** [comment]
Setting user preferences without their consent seems a bit weird to me and is not something we'd want to be doing

**Comment by richard-cox** [comment]
This would be part of an onboarding process, like automatically applying roles. FWIW the UI automatically sets initial/default `userpreferences` without their consent

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: c35f112`

Copy/pasting a filtered pods page URL now leads to the expected filtered page. 

Example: Copying `<host>/dashboard/c/c-xn8tt/explorer/pod?q=te` and pasting into a new tab/new window/clicking the link will now take you to the pod list filtered with 'te'.
