### ISSUE TITLE
Pod - Detail

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#685]
# Detail Top

Field | Value
---|---
Workload | Workload Name (link to workload)
Pod IP | IP of pod
Node | Node (link to node) where the pod is running on
Pod Restarts | # of times the pod has restarted
Created | Created Date/Time

## Main Content

Header/Label Name | k8s yaml | Input Field/Component |  ToolTip Text |  Units
---|---|---|---|---
Containers | `spec.containers` | Containers Component - Ability to view all containers  

The list of containers should include the following fields: 

Header | Value
---|---
Status | `status.containerStatuses.state`
Name  |
Image | 
Image Pull Policy | 

# Tabs 

Header |
---|
Networking | 
Scheduling | 
Volumes | 
Security | 
Labels |
Annotations |

**Comment by deniseschannon** [comment]
## Networking Tab
Everything listed here is nested under `spec.`.

> Note: This content will be used the same as what is in create workload, so being able to use the same layout for both would be ideal. 

Header/Label Name | k8s yaml | Input Field/Component
---|---|---
Network Mode | `hostNetwork` | Dropdown with 2 Options: <br> * Normal (`false`) <br>  * Host Network (`true`) 
DNS Policy | `dnsPolicy` |  Dropdown with 4 Options:  <br> * Cluster First (`ClusterFirst`) <br> * Cluster First With Host Network (`ClusterFirstWithHostNet`) <br>* Default (`Default`)  <br> * None (`None`) 
Hostname |  `hostname` | String Input Textbox  
Subdomain  | `subdomain` | String Input Textbox
DNS Nameservers | `dnsConfig.nameservers` | Ability to add/remove multiple string input textboxes  
DNS Search Domains | `dnsConfig.searches` | Ability to add/remove multiple string input textboxes 
DNS Resolver Options  | `dnsConfig.options.name` and `dns.Config.options.value` | KeyValue Component with `Name` and `Value` as headers 
Host Aliases | `hostAlisases` | KeyValue Component with `IP Address` and `Hostname` as headers

- [ ] `DNS Policy` needs additional policy `ClusterFirstWithHostNet`
- [ ] Add missing `Subdomain`
- [ ] Add DNS Resolver Options

#### Here's a mock of what the "Edit" screen will look like, but please make it view/read only. 

<img width="566" alt="Screen Shot 2020-05-19 at 10 18 54 AM" src="https://user-images.githubusercontent.com/3013118/82357615-33306d80-99ba-11ea-8e30-34040cc955ec.png">

**Comment by deniseschannon** [comment]
## Scheduling Tab
Everything listed here is nested under `spec.`.

### `Node Scheduling` Section
Note: We are not allowing ability to adjust the `weight` of a node selector in the node scheduling rules with current requirements, but we should show it in the detail page. 

- [ ] Header/Title with `Node Scheduling`

**Detail Options** 
The input will be radio button options but we should show just the text of the selected option in the detail view.
- Option 1: `Run pods on specific node(s)`
- Option 2: `Run pods on node(s) matching these scheduling rules`

Based on each option, there are different fields shown:
Options | HHeader/Label Name | k8s yaml | Input Field/Component | 
---|---|---|---|
Option 1 | Node Name | `nodeName` | Text of Selected Node Name | 
Option 1 | Node(s) with these Labels | `nodeSelector` | KeyValue Component |
Option 3 | Node Scheduling Rules | `affinity.nodeAffinity` | See **Node Schedule Rules** section

**Node Scheduling Preference Types**
There are two preference types:
- `Require any of`
- `Prefer any of`

Each preference type has the ability to add node selectors, which can hold multiple rules. When navigating to the tab, it only shows ability to `Add Node Selectors`. There is no requirement to have any node selector so there doesn't need to have it expanded to automatically input.

> **Note**: Currently, `Prefer Any of` is implemented correctly and `Require any of` should match that style. 

The preference types have the same content within each section, but are in the different places in the yaml. 

Preference Type | k8s yaml 
---|---
 _Require any of_ | `affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution`
_Prefer Any of_ | `affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution`

For each preference type, ability to create node selectors which can hold multiple node scheduling rules. Each node selector is 1 object in `nodeSelectorTerms`, which can hold multiple scheduling rules `matchExpressions`. 

### `Pod Scheduling` Section
Note: We are not allowing ability to adjust the `weight` of a pod selector in the pod scheduling rules with current requirements. 

- [ ] Header/Title with `Pod Scheduling`

**Pod Scheduling Types**
There are two pod scheduling types:

Header (under `Pod Scheduling`) | k8s Yaml
---|---
Run pods on node(s) that have these pods | `affinity.podAffinity`
Run pods on node(s) that do not have these pods | `affinity.podAntiAffinity`

Within each pod scheduling type, the content is exactly the same. 

**Pod Scheduling Preference Types**
These preference types are under the pod affinity type (either `affinity.podAffinity` or `affinity.podAntiAffinity`). 

There are two rule preference types
- `Require any of` (Hard Affinity)
- `Prefer any of` (Soft Affinity)

Preference Type | k8s yaml 
---|---
 _Require any of_ | `requiredDuringSchedulingIgnoredDuringExecution`
_Prefer Any of_ | `preferredDuringSchedulingIgnoredDuringExecution`

Each rule type has the ability to add pod selectors, which can hold multiple pod label selector rules and namespaces. When navigating to the tab, it only shows ability to `Add Namespaces` and `Add Rules` for each pod scheduling preference type. There is no requirement to have any of these options so there doesn't need to have it expanded to automatically input.

**Pod Selectors**
These pod selector types are nested under the pod affinity type (either `affinity.podAffinity` or `affinity.podAntiAffinity`) and then nested under the preference type (either `requiredDuringSchedulingIgnoredDuringExecution` or `preferredDuringSchedulingIgnoredDuringExecution`).

For required, there is only 1 Pod Selector.
For preferred, there is ability to add multiple Pod Selectors. 

For each pod selector:

- [ ] Ability to add multiple namespaces 
- [ ] Ability to add/remove pod label selecting rules. There is 1 `labelSelector`, which can hold multiple pod label selector rules `matchExpressions`. 

Header/Label Name | k8s yaml under the preference type|
---|---
Namespace | `namespaces` | 
Pod Label Selector Rule | `labelSelector.matchExpressions` | 

_Namespace_ Info
- [ ] Title with `Pods in these namespaces`
- [ ] Namespace selection - look at OPA gatekeeper constraints on how we add/remove namespaces. Default should be set to `This pod's namespace`, which would result in nothing populated in `namespaces`.  

_Pods with these Labels_ Info
- [ ]. Title with `Select pods with these labels`
- [ ] Labels selection using MatchExpressions Component
 
## `Tolerations` Section
- [ ] Header/Title with `Tolerations`

Ability to add/remove toleration rules. Each toleration rule has these fields:

Header/Label Name | k8s yaml | Input Field/Component |
---|---|---|
Label Key | `tolerations.key` | 
Operator | `tolerations.operator` | Dropdown options:<br> * = (`Equal`) <br> * exists (`Exists`)  | 
Value | `tolerations.value` | String input Textbox |
Effect | `tolerations.effect` | Dropdown with options: <br> * All (`All`)<br> * NoSchedule (`NoSchedule`) <br> * PreferNoSchedule (`PreferNoSchedule`) <br> * NoExecute (`NoExecute`) | 
Toleration Seconds | `tolerations.tolerationSeconds` | Integer input Textbox with `Seconds`  units label |

## `Priority` Section
- [ ] Header/Title with `Priority`

Header/Label Name | k8s yaml | Input Field/Component | Example Input/Default
---|---|---|---
Priority | `priority` | Integer Input Textbox | Example Text: `e.g. 3`
Priority Class Name | `priorityClassName` | String Input Textbox | Example Text: `e.g. system-node-critical`

**Comment by deniseschannon** [comment]
## Volumes Tab
This is still TBD, but wanted to get started on mocks for other pages.

**Comment by deniseschannon** [comment]
## Security Tab
Everything listed here is nested under `spec.`.

Header/Label Name | k8s yaml | Input Field/Component |
---|---|---|
Share single process namespace | `shareProcessNamespace` | Radiobutton Options: <br> * `No` <br>* `Yes` | 
Run as Not Root | `securityContext.runasNonRoot` | Radiobutton Options: <br> * `No` <br>* `Yes: containers must run as non-root-user`) | 
Run as User ID | `securityContext.runAsUser` | Integer Input Textbox | 
Run as Group ID | `securityContext.runAsGroup` | Integer Input Textbox | 
Additional Group IDs | `securityContext.supplementalGroups` | Ability to add/remove integer input textboxes by using `Add Group IDs` Button | 
Filesystem Group | `securityContext.fsGroup` | Integer Input Textbox | 
Use Host's PID Namespace | `hostPID` | Radiobutton Options: <br> * `No` <br>* `Yes`  | 
Use Host's IPC Namespace | `hostIPC` | Radiobutton Options: <br> * `No` <br>* `Yes` | 
Sysctls | `securityContext.sysctls` | KeyValue component with `Name` and `Value` as headers |  

- [ ] Update `Run as User number` to `Run as User ID` (from previous Workloads section)
- [ ] Update `Run as Group number` to `Run as Group ID` (from previous Workloads section)

Here's are mocks of what the "Edit" screen will look like, but please make it view/read only.

<img width="621" alt="Screen Shot 2020-05-21 at 4 43 06 PM" src="https://user-images.githubusercontent.com/11410997/82616500-370eec00-9b82-11ea-9f53-bbbb8decd011.png">

**Comment by deniseschannon** [comment]
## Labels & Annotations Tab

Use the existing components for ResourceTabs.

**Comment by lvuch** [comment]
https://xd.adobe.com/view/0e8a8ff7-8323-4ff8-7a96-4e308c7ea89a-78bb/

**Comment by deniseschannon** [comment]
Make sure to re-use components where possible in the mocks.

**Comment by deniseschannon** [comment]
## Misc Tab
Everything listed here is nested under `spec.`.

Header/Label Name | k8s yaml | Input Field/Component |  ToolTip Text |  Units
---|---|---|---|---
 Pod Active Deadline | `activeDeadlineSeconds`  | Integer Input Textbox | `The duration that the pod may be active before the system tries to mark it failed and kill associated containers. ` |  `Seconds`
 Termination Grace Period | `terminationGracePeriodSeconds` |  Example Text: `e.g.` 30` |`The duration that the pod needs to terminate gracefully.` | `Seconds`

**Comment by deniseschannon** [comment]
# Pod Detail

## Detail Top
- [ ] In `status` of the yaml, you have the `hostIP`, which should allow you to search for which node it is running on. On the list page, it is able to show the node name, can we do that for detail top? Can we also make it a link to get more info about the node?

# Containers Table
- [ ] Missing Header of `Containers` above the table

## Networking Tab
- [ ] Update `Nameservers` to `DNS Nameservers`
- [ ] Update `Search Domains` to `DNS Search Domains`

## Scheduling Tab
- [ ] Under `Pod Scheduling` missing the ability to have namespaces as part of pod selectors. 
- [ ] Instead of always showing empty tables with no rows, we should make the text less dense. 
  - [ ] Use case 1: When there are no pod scheduling ruless, only show text: `There are no pod scheduling rules configured.` and hide both pod scheduling types (AKA `Run pods on nodes with pods matching these selectors` and `Run pods on nodes with without pods matching these selectors.`)
  - [ ] Use case 2: When there is only one type of pod scheduling typ, hide the other pod scheduling type. 

# Container Component in Containers Table
- [ ] In the `ContainerResourceLimit` component, let's update when none are configured, so that it hides the headers with all `n/a` and it shows text instead of `There are no resource requirements configured.` 
- [ ] When no healthcheck is configured, instead of showing each section with a dropdown of type `None`, let's try to minimize the space it takes. Hide the sections and show text `There is not a Readiness Check, Liveness Check or Startup Check configured.`

**Comment by lvuch** [comment]
https://xd.adobe.com/view/5876b0de-de59-4988-8976-05d4c6ec7be8-0d25/

**Comment by izaac** [comment]
@deniseschannon  Are we planning to track the Volumes details in a separate issue or is it ready for test in this same issue? 

Volumes are mentioned as TBD here:
https://github.com/rancher/dashboard/issues/685#issuecomment-632400172

But as of today `2.5-alpha1 (08/28/2020)` I don't see volumes in Pod details after these are provisioned.

**Comment by deniseschannon** [comment]
@mantis-toboggan-md we probably need to add in volumes of a pod into the pod detail, but I'm not sure how that actually looks like. @izaac can you create a separate ticket for it so I can look into it?

**Comment by izaac** [comment]
Rancher version: `v2.5-alpha1 (08/28/2020)`  

For Pod details the mockup/design shows the section Node Scheduling, but the requirements describe `Scheduling -> Pod Scheduling`. Assuming the mockup is the reference in this case as it was linked here after the requirements.

Validated the requirements are met based off the mockup.

Opened #1138 for pod volume details follow up.
