### ISSUE TITLE
Harvester Plugin: Release 1.0.3

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6856]
- remove `-head` from harvester package.json version in `release-harvester-plugin-v1.0.3` branch
- ensure a build successfully completes in drone
- See confluence for details

**Comment by richard-cox** [comment]
This needs to happen when the harvester team are happy with the 1.0.3 plugin and BEFORE the last 2.6.9 RC. @mantis-toboggan-md  (and 2.6.9 release captains @jordojordo / @catherineluse )

**Comment by richard-cox** [comment]
Notes to QA. The result of the associated PR creates a new harvester 1.0.3 plugin which will be picked up in the next build of the dashboard and used in the next 2.6.9 RC. We need to confirm that this new plugin works

1) Bring up the new Rancher 2.6.9 RC (something greater than RC4)
2) Import an old (pre 1.1.0) harvester cluster to Rancher
3) Navigate to the cluster by clicking on the cluster from the `Virtualization Management` section

This should cause the plugin embedded in the dashboard to load and allow the user to start exploring cluster content

**Comment by irishgordo** [comment]
@richard-cox - thanks for the info - I'm loosely looking into this a bit this weekend.
Was noticing this on the `cattle-system/cattle-system-agent-uuid` in Harvester v1.0.3:
```
Events:                                                                                                                                                                                                                           
  Type     Reason          Age                 From               Message                                                                                                                                                         
  ----     ------          ----                ----               -------                                                                                                                                                         
  Normal   Scheduled       111s                default-scheduler  Successfully assigned cattle-system/cattle-cluster-agent-67d9787f84-vw2wb to vm-harvester-v103                                                                  
  Normal   AddedInterface  112s                multus             Add eth0 [10.52.0.79/32] from k8s-pod-network                                                                                                                   
  Normal   Pulling         26s (x4 over 112s)  kubelet            Pulling image "rancher/rancher-agent:v2.6.9-rc5"                                                                                                                
  Warning  Failed          24s (x4 over 110s)  kubelet            Failed to pull image "rancher/rancher-agent:v2.6.9-rc5": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.6
.9-rc5": no match for platform in manifest: not found                                                                                                                                                                             
  Warning  Failed          24s (x4 over 110s)  kubelet            Error: ErrImagePull                                                                                                                                             
  Normal   BackOff         12s (x5 over 109s)  kubelet            Back-off pulling image "rancher/rancher-agent:v2.6.9-rc5"                                                                                                       
  Warning  Failed          12s (x5 over 109s)  kubelet            Error: ImagePullBackOff  
```

Importing the v1.0.3 cluster with v2.6.9-rc5 seems to just hang on Pending.
I am running v2.6.5, on a Ubuntu Focal VM with Docker, 4C 8Gi allotted memory - configured by this cloud-init script:
https://gist.github.com/irishgordo/10a6683cb6040a53d2c840b93bfcb396

I'm not noticing anything that stands out as errors on the docker logs for the Rancher v2.6.9-rc5 container
I'm seeing these:
```
2022/10/16 05:51:49 [ERROR] error parsing azure-group-cache-size, skipping update strconv.Atoi: parsing "": invalid syntax
2022/10/16 05:51:49 [ERROR] error parsing azure-group-cache-size, skipping update strconv.Atoi: parsing "": invalid syntax
2022/10/16 05:51:49 [ERROR] error parsing azure-group-cache-size, skipping update strconv.Atoi: parsing "": invalid syntax
2022/10/16 05:51:49 [ERROR] failed to cleanup orphan catalog bindings
2022/10/16 05:51:50 [ERROR] failed to sync cache for rke-machine.cattle.io/v1, Kind=VmwarevsphereMachineTemplate
2022/10/16 05:51:50 [ERROR] failed to start controller for rke-machine.cattle.io/v1, Kind=VmwarevsphereMachineTemplate: failed to wait for caches to sync
E1016 05:51:50.697897      45 gvks.go:69] failed to sync schemas: failed to sync cache for rke-machine.cattle.io/v1, Kind=VmwarevsphereMachineTemplate
```
But that's about it besides these other ones as I navigate around in Rancher v2.6.9-rc5:
```
2022/10/16 06:00:36 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "cluster": the object has been modified; please apply your changes to the latest version and try again
2022/10/16 06:00:36 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "last-visited": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by richard-cox** [comment]
@WuJun2016 Would you be able to provide assistance to @irishgordo ? It looks like he's having trouble importing harvester 1.0.3 to Rancher 2.6.9-rc5

**Comment by guangbochen** [comment]
seems rancher-agent amd64 arch image is missing https://hub.docker.com/layers/rancher/rancher-agent/v2.6.9-rc5/images/sha256-4dc7245dff2a2fcfc25bb89587df8675b5a6be63d49d45beb04df6e9dbade01e?context=explore
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/4569037/196142462-75075419-db55-4443-90a3-cd0e3e206e54.png">

**Comment by richard-cox** [comment]
Good catch @guangbochen ! I've reached out to the build team in slack for an update

**Comment by markusewalker** [comment]
@richard-cox as a heads-up, 2.6.9-rc6 has been released that addresses the above. Can we try validating this once more with the new RC? Thank you!

**Comment by richard-cox** [comment]
> @richard-cox as a heads-up, 2.6.9-rc6 has been released that addresses the above. Can we try validating this once more with the new RC? Thank you!

Thanks, I was on both threads.

The ask is for QA to validate. Dev will also do some our side, though with a slightly different context

**Comment by irishgordo** [comment]
@richard-cox  & @markusewalker 

As far as I can tell based on the validation requirements of:
- importing Harvester node v1.0.3 into v2.6.9-rc6 - being able to view Virtualization Management for Harvester node imported

This looks good.
I am able to navigate to the Virtualization Management, adjust Harvester settings, and as a smoke test was able to build an RKE2 single node cluster backed by Harvester after uploading an image using Rancher v2.6.9-rc6 single pane of glass.

![Screenshot from 2022-10-17 11-31-00](https://user-images.githubusercontent.com/5370752/196256176-22edae55-fd18-4ed6-9ea9-2e3cf988ceb8.png)
![Screenshot from 2022-10-17 11-27-55](https://user-images.githubusercontent.com/5370752/196256179-da2ce039-8d97-4f67-9446-3e298a71433f.png)
![Screenshot from 2022-10-17 11-20-07](https://user-images.githubusercontent.com/5370752/196256181-1b368f10-92a7-407c-ab68-a19976b58315.png)
![Screenshot from 2022-10-17 11-11-00](https://user-images.githubusercontent.com/5370752/196256183-c2925d4e-73ad-48c4-ae5f-eb858aef7328.png)
![Screenshot from 2022-10-17 11-10-32](https://user-images.githubusercontent.com/5370752/196256187-944af29b-ca64-41d3-84a7-d05c3dfc78ac.png)

@noahgildersleeve - is there anything we might be missing on this check?

**Comment by noahgildersleeve** [comment]
Tested in Rancher v2.6.9-rc6 with single node Docker install and Harvester v1.0.3. UI looks good. I tested with RKE1 and RKE2 deploys with k8s 1.24.

![Screenshot_20221017_192947](https://user-images.githubusercontent.com/83787952/196506297-5968e085-ae1e-412c-9d14-65093d4aee00.png)
![Screenshot_20221017_192941](https://user-images.githubusercontent.com/83787952/196506302-d39252cd-9a01-494b-9583-a981d27ece8c.png)
![Screenshot_20221017_192931](https://user-images.githubusercontent.com/83787952/196506306-e9610c73-60e3-4a26-8ae4-64501d12fb66.png)

**Comment by richard-cox** [comment]
Thanks @irishgordo & @noahgildersleeve , much apperciated
