### ISSUE TITLE
Harvester Plugin: Remove harvester pkg from `master`

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6857]
- Following the release of 2.6.9/harvester 1.1.0 the harvester plugin code will live in `harvester/dashboard`
- The harvester plugin 1.0.3 code will still live in `rancher/dashboard` but in the `release-harvester-plugin-v1.0.3` branch
- The harvester plugin code from `master` should be removed
- See confluence for details

**Comment by gaktive** [comment]
@richard-cox should we try to target this for 2.7.next1 or should we push it to later?

**Comment by richard-cox** [comment]
I'm having second doubts about this. There's been a number of breaking changes that have been caught with the code in `master` that would have only been discovered late in the day. Which does mean we need to consider releasing a new bundled version with the next1. That's separate though, this change doesn't have to go in to next1

**Comment by nwmac** [comment]
@richard-cox Do we still plan to do this for next2?

**Comment by gaktive** [comment]
This will likely need re-reviewing after Harvester 1.2.

**Comment by WuJun2016** [comment]
Hi @richard-cox  Do we have plans to remove `harvester-manager` pkg from the rancher/dashboard repo?   If it could also be maintained as a separate repo, then the rancher and harvester releases would be much freer!

**Comment by richard-cox** [comment]
@WuJun2016  At the moment it lives in `rancher/dashboard` so is built and shipped with the Rancher release. Moving it out of the repo will mean it can be released outside of the Rancher process, however it won't then be installed by default (users will have to manually do this). That's probably something Product side would need to agree / acknowledge. cc @mantis-toboggan-md
