### ISSUE TITLE
Creating a project as a cluster member throws forbidden error but the project is still created on an rke2 cluster

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#6861]
**Rancher Server Setup**
- Rancher version: `v2.6-head 79a5328 `
- Installation option (Docker install/Helm Chart): `Docker install`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s

**Information about the Cluster**
- Kubernetes version: `v1.24.4+rke2r1`
- Cluster Type (Local/Downstream): Downstream Infrastructure provider 1 nodes all roles.
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
Node driver rke2 clusters

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Cluster Member, validated on cluster owner but the issue is not seen
   
**Describe the bug**
Project creation errors with forbidden message for cluster members. But the project is still created. This is only seen for rke2 clusters and not rke1 clusters.

**To Reproduce**
1. Create a downstream cluster with the spec mentioned above.
2. On rancher server 2.6-head, create a standard user.
3. Add the standard user in the downstream cluster as a cluster member.
4. Login as a cluster member, from projects/namespaces create a project - P1. 

**Result**
Project creation returns an error 
```
https://<rancherserverIP>/v3/projects/c-m-npcfw5ln:p-65tnt?action=setpodsecuritypolicytemplate
Error : projects.management.cattle.io "p-65tnt" is forbidden: User "u-cczqeq4tow" cannot get resource "projects" in API group "management.cattle.io" in the namespace "c-m-npcfw5ln"
```

**Expected Result**
Expected the project creation to work without any errors.

**Additional context**
Even though the project creation from UI throws error, the project is created without any errors.
Not seen on v2.6.8
Creating a project as a cluster owner goes through without any error. 

Same as https://github.com/rancher/dashboard/issues/6464
Related https://github.com/rancher/rancher/issues/38573

**Comment by richard-cox** [comment]
To confirm, the error is on-screen and not in the console?

**Comment by anupama2501** [comment]
Yes this`Error : projects.management.cattle.io "p-65tnt" is forbidden: User "u-cczqeq4tow" cannot get resource "projects" in API group "management.cattle.io" in the namespace "c-m-npcfw5ln"` error is seen on-screen and not in the console

**Comment by nwmac** [comment]
@jordojordo Could you take a look at this one, please?

**Comment by anupama2501** [comment]
Verified on v2.6-head `a3b5237`
 
1. Create an rke1 and rke2 node driver clusters Linode and AWS respectively as an admin 
2. Create 2 standard users - u1,u2
3. Add u1 as CO in both the downstream and u2 as CM in both the downstream
4. Login as u1 --> verify user can create projects and namespaces in both rke1 and rke2 clusters
5. Login as u2 --> verify user can create project and namespaces in both rke1 and rke2 clusters
6. Create 2 more standard users - u3 and u4
7. As u1 create an rke1 custom and rke2 custom clusters
8. Add u2 ad CM as u1 
9. Verified creating a project as u1 in rke2 and rke1 and adding the users u3 and u4 to the projects while creating works fine.
10. Login as u2 and verify u2 can create projects and add users u3 and u4 to the projects
