### ISSUE TITLE
Remove support for v1 legacy tools

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6864]
- https://github.com/rancher/dashboard/issues/6876
- https://github.com/rancher/dashboard/issues/6874
- https://github.com/rancher/dashboard/issues/6872

**Comment by deniseschannon** [comment]
Please also remove/hide the logging v1 tools as well from the UI

Here is the backend issue, but the backend won't be removed until v2.7.1: https://github.com/rancher/rancher/issues/37318

**Comment by nwmac** [comment]
What will be removed:

In the 'legacy' section of the side-nav when exploring a cluster:

- CIS Scans

- Project / Istio
- Project / Logging
- Project / Pipelines

Additionally, the Istio and Logging v1 tools shown in the 'Cluster Tools' section will only now appear IF they are already installed - they will no longer be installable from the new UI - the can still be managed if already installed, so that the user can remove them in order to upgrade to v2.

**Comment by ronhorton** [comment]
**Pass** verified in `2.7-head commit id 4092002`
apps removed from UI
![2022-10-11_17-03-57](https://user-images.githubusercontent.com/89212856/195198502-3d31450d-8125-49a1-b6e4-90c064d3dd78.png)

![2022-10-11_17-02-32](https://user-images.githubusercontent.com/89212856/195198294-b8a93a4c-9825-4c5a-bb27-7734b59a8977.png)
![2022-10-11_16-58-23](https://user-images.githubusercontent.com/89212856/195198315-6ee07cda-9c68-4ca7-9fa3-917242e3b0e4.png)
<img width="244" alt="2022-10-11_16-59-13" src="https://user-images.githubusercontent.com/89212856/195198346-962c9cc8-f343-4d6e-a7a3-bd3f8e25da34.png">
