### ISSUE TITLE
Figure out how to support/enable E2E tests for extensions

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6871]
Figure out how to support/enable E2E tests for extensions (formerly plugins)

**Comment by gaktive** [comment]
Might require a 2nd ticket so that we periodically check other projects (Kubewarden, Elemental) to see that extensions don't break.

**Comment by aalves08** [comment]
@gaktive what's the scope of this issue? 🙏

**Comment by gaktive** [comment]
Let's check in with @nwmac when he's back but the key thinking here is how to regularly test the UI so that extensions don't break over time.

**Comment by aalves08** [comment]
Ok. sounds good @gaktive . We have e2e tests for `Elemental` and `Kubewarden` already in place, so the goal is to figure out how to run them from time to time in our Dashboard test suite. 🙏
