### ISSUE TITLE
[2.7.0] Remove Rancher v1 Pipelines UI components

### ISSUE THREAD

**Issue by doflamingo721** [rancher/dashboard#6872]
**Is your feature request related to a problem? Please describe.**

Rancher pipelines were deprecated in rancher v2.5.0. So we need to remove all the associated components in v2.7.0

**Additional context**

Linked issue: https://github.com/rancher/rancher/issues/37324

**Comment by AndrewHoffmanQA** [comment]
per comments in github, this work item has been tested by QA. moving to QA complete.
