### ISSUE TITLE
[2.7.0] Remove istio v1 chart components from UI

### ISSUE THREAD

**Issue by doflamingo721** [rancher/dashboard#6874]
**Is your feature request related to a problem? Please describe.**
Rancher v1 istio charts were deprecated in rancher v2.5.0. So we need to remove the associated components from UI. 

**Additional context**
Linked issue: https://github.com/rancher/rancher/issues/37327

**Comment by ronhorton** [comment]
**Pass** verified in `2.7-head commit id 7cbd5a4`

issue also verified by https://github.com/rancher/rancher/issues/37327

**Comment by ronhorton** [comment]
Istio is still visible in cluster tools - and selectable

![2022-10-20_15-43-45.png](https://zube.io/files/rancher/da61b270011bd97bd4411fd4976649a3-2022-10-20_15-43-45.png)

**Comment by ronhorton** [comment]
**Pass** verified in `2.7.0-rc6`

1. enabled legacy flag
2. went to ember ui
3. clicked tools dropdown in rke1 cluster

![2022-10-24_15-49-16](https://user-images.githubusercontent.com/89212856/197615027-b15a833a-1e8d-497a-8f6d-6f24306bad9b.png)
