### ISSUE TITLE
EPIC: Improve Rancher System Registry Container Registry configuration

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6875]
This is the Epic for all of the changes to better support private registry configuration and to ensure we have consistent terminology across the UI.

This covers the following GitHub issues:

## v2.7.0 issues

- https://github.com/rancher/dashboard/issues/6910
- https://github.com/rancher/dashboard/issues/6920
- https://github.com/rancher/dashboard/issues/6918

## v2.7.1 issues

- https://github.com/rancher/dashboard/issues/6919
- https://github.com/rancher/dashboard/issues/6917

Notes:

There is a global setting `system-default-registry ` with description `Private registry to be used for all system Docker images.`. This allows you to set a global system-wide registry default to be used for the private registry.

We should change the terminology for this (update the description) to `Global default Rancher system container registry` (TBD).

When you create a cluster, you can choose (under the `Registries` tab) which image registry to use when pulling Rancher images. We should refer to this as the `Cluster default Rancher system container registry` (TBD).

FYI, here's how you set this for a cluster:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/1955897/191307938-288077b0-9cec-44e6-bfd6-548f2308e654.png">

Note we want to change the terminology of the first item and show for each what the value is that would be used.
For the last option (shown below), this needs more UX work to understand and improve this functionality:
 
<img width="868" alt="image" src="https://user-images.githubusercontent.com/1955897/191308331-6a3c21c8-87f7-4702-8ae5-7a3fb442ea9e.png">

**Comment by Josh-Diamond** [comment]
Awaiting validation for https://github.com/rancher/dashboard/issues/5146 that above PR, associated w/ fixes, is presumed to resolve.

Once https://github.com/rancher/dashboard/issues/5146 has been validated, this ticket will be reviewed + closed

**Comment by sowmyav27** [comment]
@Josh-Diamond moved https://github.com/rancher/dashboard/issues/5146 to the current milestone. Please validate both the issues - 5146 and 6875

**Comment by Josh-Diamond** [comment]
Ticket #6875 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-8062f1e3ab7bff870dfab195ff699a308644168a-head`:
1. Fresh install of rancher `v2.7-head`
2. `Create` a custom rke2/k3s cluster and navigate to `Cluster Configuration > Registries`
3. Verified - UI as expected; [see screenshot below]; functionality has been tested + verified w/ above issues linked to this EPIC ticket

Screenshot:
<img width="1669" alt="Screenshot 2023-01-06 at 9 40 22 AM" src="https://user-images.githubusercontent.com/46494969/211057624-62820a49-36e0-4bdb-b76d-7beed3f10433.png">
