### ISSUE TITLE
[2.7.0] Remove v1 cis-benchmark chart components from UI

### ISSUE THREAD

**Issue by doflamingo721** [rancher/dashboard#6876]
**Is your feature request related to a problem? Please describe.**
Rancher v1 cis-benchmark charts were deprecated in rancher v2.5.0. So we need to remove the associated components from UI.

**Additional context**

Linked issue: https://github.com/rancher/rancher/issues/37322

**Comment by AndrewHoffmanQA** [comment]
per comments in github, this work item has been tested by QA. moving to QA complete.
