### ISSUE TITLE
Cluster Owner (not admin) unable to access items under  Related Resources tab

### ISSUE THREAD

**Issue by brudnak** [rancher/dashboard#6878]
# Rancher Server Setup

| Component                 | Version / Type                                                                     |
| ------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version           | v2.6-9670628a4813d43a8410fe27c745c79a4b566c3a-head                                 |
| Rancher commit link       | https://github.com/rancher/rancher/commit/9670628a4813d43a8410fe27c745c79a4b566c3a |
| Installation option       | Helm High Availability                                                             |
| RKE binary version used   | v1.3.11                                                                            |
| If Helm Chart k8s cluster | v1.23.6                                                                            |
| Cert Details              | Let's Encrypt                                                                      |
| Helm version              | v2.16.8-rancher2                                                                   |
| Downstream cluster type   | RKE1 Linode                                                                        |
| Downstream K8s version    | v1.24.2                                                                            |
| Logged in user role       | Administrator & Standard User as downstream cluster owner                          |
| Browser type              | Google chrome                                                                      |
| Browser version           | 103.0.5060.134 (Official Build) (x86_64)                                           |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=v2.6-head \
  --version 2.6.6
```

## Describe the bug
Under Cluster Management, Cluster details, Related resources, I am unable to access any resources as a cluster owner (not an admin).

## To Reproduce

1. Create a downstream cluster as an administrator
2. Set up a standard user named `tuser1`
3. Assign `tuser1` to the downstream cluster as a cluster owner
4. As an administrator, log out and log in as `tuser1`
5. Logged in as `tuser1`, and starting from the **default** Rancher homepage `/dashboard/home`
   1. Click `hamburger menu` ==> `Cluster Management` ==> click the link of the name of the downstream cluster (not explore) ==> click on the `Related Resources` tab
   2. Click on one of the resources, for example `Cluster Member` or `Secret` under `Refers To`
   3. Unable to access links to the resources, getting a `403` : `Forbidden` with a `GET` to `v1/management.cattle.io.clusters/local`

```json
{"type":"error","links":{},"code":"Forbidden","message":"clusters.management.cattle.io \"local\" is forbidden: User \"u-b7s7x\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","status":403,"type":"error"}
```

6. With the same click / redirect to the homepage also getting a `PUT`:`500` error to `v1/userpreferences/u-b7s7x`

```json
{"type":"error","links":{},"code":"ServerError","message":"Operation cannot be fulfilled on preferences.management.cattle.io \"cluster\": the object has been modified; please apply your changes to the latest version and try again","status":500,"type":"error"}

```

## Result
Unable to access links under related resources tab

## Expected Result
For these not to be displayed if deemed they shouldn't be accessible to a standard user as a cluster owner

**Comment by nwmac** [comment]
@brudnak This has been re-opened, but I don't see any comment on why - can you help me understand what is not working. Thanks.

**Comment by brudnak** [comment]
> @brudnak This has been re-opened, but I don't see any comment on why - can you help me understand what is not working. Thanks.

Pinged in internal comms @nwmac

**Comment by brudnak** [comment]
https://github.com/rancherlabs/rancher-security/issues/1073

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

Reproduction not requred.

## Validation Environment


| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version                  | v2.7-f9291747e2cd869c468a2d93fbff92b6c54b4cb3-head |
| Installation option              | Helm (high availability)                           |
| RKE binary version used          | v1.4.4                                             |
| If Helm Chart k8s cluster        | v1.25.6                                            |
| Cert Details                     | Let's Encrypt / `nginx`                            |
| Docker version                   | 20.10.7, build f0df350                             |
| Downstream cluster type          |                                                    |
| Downstream K8s version           |                                                    |
| Authentication providers enabled |                                                    |
| Logged in user role              | administrator                                      |
| Browser type                     | Microsoft Edge                                     |
| Browser version                  | 113.0.1774.35                                      |

## Validation steps

1. Create a downstream cluster as an administrator
2. Set up a standard user named `tuser1`
3. Assign `tuser1` to the downstream cluster as a cluster owner
4. As an administrator, log out and log in as `tuser1`
5. Logged in as `tuser1`, and starting from the **default** Rancher homepage `/dashboard/home`
   1. Click `hamburger menu` ==> `Cluster Management` ==> click the link of the name of the downstream cluster (not explore)
6. The previously exposed related resources tab is now hidden

## Additional Info

## RESULTS

### ✅ (Validation) Expected

For the related resources tab to be hidden

### ✅ (Validation) Actual

The related resources tab is hidden
