### ISSUE TITLE
UI Performance Drops to Unusable With Many Inherited Cluster Roles

### ISSUE THREAD

**Issue by brudnak** [rancher/dashboard#6885]
| Component                        | Version / Type                                                                     |
|----------------------------------|------------------------------------------------------------------------------------|
| Rancher version                  | v2.6-68215bcdde090854ff28b43b01d1aa0b69611920-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/68215bcdde090854ff28b43b01d1aa0b69611920 |
| Installation option              | Helm                                                                               |
| RKE binary version used          | v1.3.13                                                                            |
| If Helm Chart k8s cluster        | v1.24.2                                                                            |
| Cert Details                     | Let's Encrypt                                                                      |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | Not applicable                                                                     |
| Downstream K8s version           | Not applicable                                                                     |
| Logged in user role              | Administrator (GitHub OAuth)                                                       |
| Authentication providers enabled | local, GitHub OAuth, ActiveDirectory LDAP                                          |
| Browser type                     | Opera GX                                                                           |
| Browser version                  | LVL4 (core: 90.0.4480.100) (x86_64)                                                |

### ADDITIONAL VALIDATION SETUP

```shell
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=v2.6-head
```

### Describe the bug
Creating a lot of cluster roles makes the UI unresponsive.

### To Reproduce

1. Run this terraform against a rancher instance as described in the setup table above
   1. https://github.com/brudnak/rancher-tf-roles-breadth
   2. `role_count` set to 1100
2. Starting from the **default** Rancher homepage
3. Click `Hamburger Menu` > `Users & Authentication` > `Roles` > `Cluster`
4. Search for the role named `bar` > `Right Click` > `Edit Config` > `Inherit From`
5. The Rancher UI becomes unresponsive at this point
6. CPU on the Rancher nodes stays normal
7. If you have another Rancher window opened in an incognito window that Rancher will still be functional that hasn't visited the inherited cluster role list

### Result
The Rancher UI becomes unresponsive / unusable at this point in the current window

### Expected Result
For the performance not to be so greatly affected by only 1100 roles

### Additional Info
Noticed while testing: https://github.com/rancher/rancher/issues/38419

**Comment by richard-cox** [comment]
Environment Notes
- I deployed to DO, 8GB / 160GB Disk, and used k3d for kube
- Run through steps from https://cert-manager.io/docs/installation/helm/, substitute commands from issue description
- When creating a rancher token to use with terraform don't give it a scope

Issue
- The main factor is that the bar role inherits from 1100 other roles
  - Getting to the detail/edit page of the role is a bit sluggish
  - Viewing the 'inherit from' tab in edit view is sluggish
  - Leaving the page after viewing `inherit from` tab causes dashboard to hang
- Specifically oh edit page inherit from tab
  - Tab shows one drop down for every role it inherits (1100)
  - Each drop down contains 1100 entries
  - Each slot that shows the drop down is passed 1100 roles as well (See `ArrayList` "column" `slot` `:rows=rows`)

For Reference - The Detail page for bar
![image](https://user-images.githubusercontent.com/18697775/190161839-de221218-0432-41a4-8460-781e9674c0fe.png)

For Reference - the Inherit From tab in the edit page for bar
![image](https://user-images.githubusercontent.com/18697775/190162141-89031a8e-949c-4932-8e84-78db252bac6a.png)

I thought i found a fix for this by removing the slot `:rows=rows` (brought in via https://github.com/rancher/dashboard/commit/1265853652ad103d0). It wasn't used anywhere. However this didn't resolve the issue.

Other factors
- reduce number of options shown in edit page inherit from role drop downs to 1 and the cancel works fine (Tweak templateOptions in RoleDetailEdit)
- reduce number of drops downs shown to 1 and cancel works fine (tweak roleTemplateNames in RoleDetailEdit)

Possible Solutions
- Investigate why vue goes crazy when leaving the page
- Reduce the number of options in the drop downs and let the user manually provide the group id

**Comment by richard-cox** [comment]
I'm bumping this out of 2.6.9
- It's a very localised performance issue (the list of cluster roles works alright)
- The performance of the dashboard is reasonable if the role doesn't inherit from 1000's of other roles. We view this as an outlier use case

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment

| Component                        | Version / Type                                                                        |
|----------------------------------|---------------------------------------------------------------------------------------|
| Rancher version                  | v2.6-48b6bc6b4a6adb4fd4c623984862494cd0b70a5f-head                                    |
| Rancher commit link              | https://github.com/rancher/rancher/commit/48b6bc6b4a6adb4fd4c623984862494cd0b70a5f    |
| Installation option              | Helm                                                                                  |
| RKE binary version used          | v1.3.13                                                                               |
| If Helm Chart k8s cluster        | v1.24.2                                                                               |
| Cert Details                     | Let's Encrypt                                                                         |
| Docker version                   | 20.10.7, build f0df350                                                                |
| Helm version                     | v2.16.8-rancher2                                                                      |
| Downstream cluster type          | RKE1 Linode                                                                           |
| Downstream K8s version           | v1.24.4                                                                               |
| Authentication providers enabled | local, GitHub OAuth                                                                   |
| Browser type                     | Opera GX                                                                              |
| Logged in user role              | GitHub OAuth Admin for Setup / GitHub OAuth standard user with cluster owner for test |
| Browser type                     | Opera GX                                                                              |
| Browser version                  | LVL4 (core: 90.0.4480.117) (x86_64)                                                   |

### ADDITIONAL VALIDATION SETUP

```shell
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=v2.6-head
```

### Describe the bug
Creating a lot of cluster roles makes the UI unresponsive.

### To Reproduce

1. Run this terraform against a rancher instance as described in the setup table above
    1. https://github.com/brudnak/rancher-tf-roles-breadth
    2. `role_count` set to 1100
2. Starting from the **default** Rancher homepage
3. Click `Hamburger Menu` > `Users & Authentication` > `Roles` > `Cluster`
4. Search for the role named `bar` > `Right Click` > `Edit Config` > `Inherit From`
5. The UI is running smoothly - test passed with these changes.

### ✅ Result
The UI performance was unaffected after visiting the inherited roles tab

### ✅ Expected Result
For the performance not to be so greatly affected by only 1100 roles
