### ISSUE TITLE
Pods count delayed column on homepage table not loading correctly

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#6888]
**Setup**
- Rancher version: v2.6-head
- Browser type & version: Any

**Describe the bug**
Pods count delayed column on homepage table not loading correctly, showing the loading spinner until the user scrolls the homepage.

**To Reproduce**
- Go to rancher dashboard homepage, to load data
- Go to another page on rancher dashboard (using the side-menu nav)
- Go back to rancher dashboard homepage (using the side-menu nav)

**Result**
Pods count col does not show data (keeps displaying spinner) until the user scrolls the page for the first time

**Expected Result**
Pods count col should show data when that data is loaded (async)

**Screenshot**
![Screenshot 2022-09-14 at 10 09 44](https://user-images.githubusercontent.com/97888974/190112506-5b2893cd-1954-4deb-8894-91ed14a9a895.png)

**Comment by ronhorton** [comment]
**Pass** Verified in `v2.6.9`
1. logged in - pod counts loaded
2. navigated away and back - pods count loaded

verifying this is fixed, as i have several varied clusters on this ha instance and the pods count loaded immediately after landing on the page. did not experience the loading wheel. 

<img width="1495" alt="2022-09-28_17-50-55" src="https://user-images.githubusercontent.com/89212856/192895714-a44d8efa-9bbf-45c2-956a-2cc01934bb8b.png">
