### ISSUE TITLE
Enable incremental loading and manual refresh features for all list views

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#6890]
- Enable incremental loading feature and manual refresh features for all list views, if flags are activated on the global settings, instead of being binded to a specific set of resources (currently: Pods, Deployments, Cron Jobs, Daemon Sets, Jobs, Stateful Sets, Replica Sets, Replication Controllers, Workloads and Secrets)

**Comment by git-ival** [comment]
LGTM

Incremental Loading:

https://user-images.githubusercontent.com/85186645/198751322-c9cfd648-f074-4535-a292-2c65af9aa127.mp4

Manual Refresh:

https://user-images.githubusercontent.com/85186645/198751339-02e031b7-2454-4455-8d55-882b5e96b683.mp4

Incremental Loading + Manual Refresh:

https://user-images.githubusercontent.com/85186645/198751375-4645bcf8-99a9-48b2-be83-2a966080de78.mp4
