### ISSUE TITLE
Garbage Collect Resources from the Store

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6891]
**Is your feature request related to a problem? Please describe.**
- The dashboard will fetch a number of resources with varying counts. Once fetched we instruct the backend to notify us of changes and receive updates over web socket
- The dashboard performance degrades when
  - There are lot of resources in the store (high client memory consumption)
  - It receives lots of resource updates (high cpu churn to process and trigger updates to online representations of resources
- The backend performance will degrade when
  - It's watching and sending lots of resource updates to multiple clients

**Describe the solution you'd like**
- Ideally we should only
  - be storing resources that we might use often
  - explicitly removing resources from store (and stop watching for updates) when we're no longer interested in them
- We can manually address these issues, however would involve a lot of trawling through code and per-context knowledge covering all places of the dashboard
- An alternative is to GC resources from the store
  - We can look at resources that haven't been request in a long time and remove
  - This should be triggered when there's no change the elements are on screen (user leaves workloads list up for a long time)
    - GC should be triggered on navigation away from a resource. This should also not interfere with secondary resources

Note - Initially targeted for ~2.6.9~ 2.7.0 but subject to change

**Comment by richard-cox** [comment]
@git-ival The store referenced in this issue is browser side and GC runs locally to remove resources there. By default there's not a lot of logs, but if GC happens and it removes resources there'll be a summary log line in the browser's console.

Interesting to see some other type of server side GC occurs, I'm not aware of that process or how it works.

**Comment by git-ival** [comment]
Hi @richard-cox , sorry to ping again. I can't seem to find a GC log line in the console (even just a summary line). Any ideas what might be wrong?


https://user-images.githubusercontent.com/85186645/197066021-1aab5851-48c7-4ed9-a0f6-cf54fe4a61de.mp4

**Comment by richard-cox** [comment]
- Updates to GC settings will only apply to the current tab, other tabs will require a refresh to apply them
- When GC runs there's restrictions on the resources that are removed. There's a full list [here](https://github.com/rancher/dashboard/pull/6907#issue-1375822968) but the main ones are...
  - Resource type in the store must not have been accessed within the `Resource Age` setting
  - Resource count must exceed the `Resource Count` setting
  - Resource type must not be in use on the current page
  - Resource type must not be for a page we're navigating to 

  
To fully prove this out memory wise you would need to
- see the memory foot print of the browser increase as the requests for secrets complete and the count of secrets in the pagination details increases
  - this may mean creating secrets with a lot of content
- navigate to a different page that does not require secrets
- wait enough time for the GC to run (for your settings this looks like 30 seconds)
- at this point you should see 
  - a console log line regarding secrets being GCd
  - the memory of the browser reducing

![image](https://user-images.githubusercontent.com/18697775/197156945-3f4fef56-bb59-4153-8ab3-cd47e4d20ccd.png)

**Comment by git-ival** [comment]
@richard-cox LGTM, except for the case where GC is enabled but both periodic and on page change GC have been disabled.
What is the function of GC if -both- periodic -and- on page change GC are disabled?
Should it even be possible for users to disable -both- periodic -and- on page change GC?

GC disabled:

https://user-images.githubusercontent.com/85186645/197300641-4fe4b934-54c4-4a4b-8dd9-5452a328d3c3.mp4

GC fully enabled - Periodic GC:

https://user-images.githubusercontent.com/85186645/197300733-c2de4e41-d6ec-4fd9-8c21-73c744adb80c.mp4

GC fully enabled - GC on page change:

https://user-images.githubusercontent.com/85186645/197300842-54f09103-b70c-48e0-a19f-f0881d54abcd.mp4

GC enabled - Periodic and on page change GC disabled:

https://user-images.githubusercontent.com/85186645/197300989-a1e4dcef-4fbc-4399-bc8e-6545f08eb69a.mp4

**Comment by richard-cox** [comment]
When GC is on there's some tracking of when resources are accessed, which makes it a little easier if the user starts tweaking the individual settings within that session. 

Ideally we should work around that and disable the higher setting when the granular settings are disabled, but for this first release I think as-is is fine.

**Comment by git-ival** [comment]
Agreed. Closing now, great job on this by the way!
