### ISSUE TITLE
Valid resource names are rejected when creating Workload resource types

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6906]
**Setup**
- Rancher version: 2.6.8

**Describe the bug**
- When attempting to create `Workload` types such as `deployment`, `daemonset` and `statefulset` will show a validation error when their name contains a `.`
- When trying the same via kubectl or yaml the resource is successfully created

**To Reproduce**
- Workloads --> Deployment --> Create

**Result**
See screenshot

**Expected Result**
- Name validation does not fail for valid names

**Screenshots**
![image](https://user-images.githubusercontent.com/18697775/190605636-01aa40b5-791e-4ab6-9a5b-85897dac2659.png)

**Additional context**
- Kube docs state a number of specs applicable to resource name, including two that don't allow `.`. However it does not state which resources these apply to.
- The resource docs all lead to the generic `metadata` object applicable to many types
-  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#deployment-v1-apps --> https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#objectmeta-v1-meta
- To resolve this we should manually test which resources are accepted by the kube cli and make sure the UI follows suit
  -  We should first confirm the cli doesn't accept any old junk

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head eab28dd
Rancher cluster type: single-node docker install
Docker version: 20.10

----------

### Testing: ###
Tested this issue with the following steps:
1. Create a deployment with the name "valid.name"

**Result** - Pass
User is now able to create deployment using "." in the name
![image.png](https://zube.io/files/rancher/5603e4dc86283ceaaeefecdc8153e2cf-image.png)
