### ISSUE TITLE
Rancher>Storage>Secrets - the ability to create a custom secret type `dockercfg` is offered to the user.

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/dashboard#6913]
**Setup**
rancher HA 
image 2.6-head a3b5237

**Describe the bug**
the ability to create a custom secret type `dockercfg` is offered to the user. 

I believe `dockercfg` was deprecated and replaced by `dockerconfigjson` as a secret type however we still offer users the ability to create one. 

rationale:
- based off of [this ](https://stackoverflow.com/questions/35519072/docker-config-json-vs-dockercfg)post, It appears to be replaced by type `dockerconfigjson`
- when running kube commands to create my own `dockercfg`, the rancher UI recognizes it as a `dockerconfigjson`. 
 example  command `-kubectl create secret docker-registry secret-tiger-docker --docker-username=example --docker-password=example --docker-server=www.example.com`
-  I cannot create `dockercfg` via the UI, error a 422 is thrown, error Secret "[SECRET NAME]" is invalid: data[.dockercfg]: Required value

**To Reproduce**

1. stand up a rancher instance
2. hamburger menu, select local cluster.
3. from the sidebar cluster menu select storage> secrets
4. click create
5. click custom type
6. select 'type' dropdown

**Result**
create a custom secret type `dockercfg` is offered to the user. 
**Expected Result**
users should only be offered secret types they can successfully create

**Screenshots**

![image](https://user-images.githubusercontent.com/89030218/190702105-c0034f25-90f0-49db-aebe-f71fed1c03ba.png)

**Additional context**

**Comment by AndrewHoffmanQA** [comment]
![image](https://user-images.githubusercontent.com/89030218/192813092-a43386c9-1a02-46f0-9f14-534148661a87.png)
the option still appears for the user in 6.9RC1. setting work item to 'reopened' state

**Comment by AndrewHoffmanQA** [comment]
![image](https://user-images.githubusercontent.com/89030218/192813745-02bb25cd-9248-4d11-9ca4-4fad5e023c2a.png)

the option still appears in the UI in 2.7head - c567ef3

setting issue to 'reopened'

**Comment by nwmac** [comment]
I believe the kubernetes.io/dockercfg is marked legacy, rather than being deprecated - I'll update the label to make that clear.

**Comment by AndrewHoffmanQA** [comment]
passed. retested on 2.7head 6ee3949

the sercret type 'dockercfg' is not longer available in the UI

![image.png](https://zube.io/files/rancher/e0645852ef9922a3a2c4ae1695055dbc-image.png)
