### ISSUE TITLE
UX Consistency for how to reference the "Rancher Manager system images" in the UI in our descriptions

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6918]
Edit: See this comment specifying the text updates https://github.com/rancher/dashboard/issues/6918#issuecomment-1257954411

**Comment by catherineluse** [comment]
> this is actually invalid. 

How is it invalid? I thought the registry was for pulling images for provisioning Kubernetes clusters and installing Rancher Helm charts.

**Comment by nwmac** [comment]
Global Settings

Change "Private registry to be used for all system Docker images." to "Private registry to be used for all Rancher System Container Images"

RKE1 (Ember)

![image.png](https://zube.io/files/rancher/07ec4c2a47b75298708dbbeb61dfd70f-image.png)

Change:

"Configure a default private registry for provisioning RKE cluster components. When enabled, all system images required for RKE cluster provisioning and system add-ons startup will be pulled from this registry."

to:

"Configure a default cluster-level private registry to be used for all Rancher System Container Images"

**Comment by nwmac** [comment]
@catherineluse Ken and I discussed - see changes below.

**Comment by catherineluse** [comment]
I have addressed this issue in these PRS:

- Updated description for private registry in RKE1/ember cluster edit form: https://github.com/rancher/ui/pull/4898
- Updated description for private registry in RKE2/K3s cluster edit form: https://github.com/rancher/dashboard/pull/7090
- Updated description for global setting for default registry: https://github.com/rancher/dashboard/pull/6994 and https://github.com/rancher/dashboard/pull/7089

**Comment by slickwarren** [comment]
tested on v2.7-head (d8334c8):
* rke1 private registry text updated:
<img width="627" alt="Screen Shot 2022-10-21 at 10 54 44 AM" src="https://user-images.githubusercontent.com/16691014/197259419-50a86577-6f95-4d37-a03c-9e3a46e64590.png">
* rke2 private registry texts updated:
<img width="502" alt="Screen Shot 2022-10-21 at 10 55 54 AM" src="https://user-images.githubusercontent.com/16691014/197259538-275b78c8-1481-41a9-a463-4e5bdf93f783.png">
* global text updated:
<img width="1099" alt="Screen Shot 2022-10-21 at 10 57 52 AM" src="https://user-images.githubusercontent.com/16691014/197259589-b4bb345e-8b46-4731-bfd1-142068c6a06e.png">
