### ISSUE TITLE
UX: Update the option in RKE2/k3s registry page to not refer to Dockerhub registry

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6920]
This is to remove "Default Dockerhub registry"

Location in the UI:
RKE2/k3s provisioning - Private Registries section - 1st option (Default option)

**Comment by catherineluse** [comment]
Should it be called "global scoped Rancher image registry"? To differentiate it from a cluster scoped one?

**Comment by Josh-Diamond** [comment]
Moving back to `Working` column, as no PR to address RKE2/K3s registry page changes has been linked
