### ISSUE TITLE
Long user/display names will overflow the SelectPrincipal container

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#6925]
**Setup**
- Rancher version: `v2.6-a3b5237ce1da4228c97df7552d57464c64947b3b-head`
- Browser type & version: `FF 104.0`

**Describe the bug**

Long user names and display names will overflow the `SelectPrincipal` component container, if the name is long enough it will grow passed the window width. 
Recognized with [this comment](https://github.com/rancher/dashboard/pull/6909#pullrequestreview-1111292895).

**To Reproduce**

1. Create a user with a long user name and display name
  - user: long-username-hyz8ql12oa-0b2ewxkh29-vjnzbyqcmd-ohydd9bi3x-7rcje6k5hp-kr9ld7r1si
  - display name: long-displayname-e422ilkhqj-y4rzk02abt-c8m0scwcwl-reliod8oja-hj1jvu31mm-k28d9zppm1
2. Navigate to the local cluster, edit the config of a project and add the created user as a Project Member 

**Result**
The name will overflow the width of the container.

![long-user-name](https://user-images.githubusercontent.com/40806497/191021925-8960bde4-6c81-47cd-945d-deeb5102b920.png)

**Expected Result**

The user name should fold to fit within the container.

**Additional context**

This seems to appear in any instance where the `SelectPrincipal` component is used, for example adding a Cluster Member to a cluster:

![long-cluster-member](https://user-images.githubusercontent.com/40806497/191022204-a0955ff8-95b2-43ee-90c2-b118edde54c5.png)

**Comment by jameson-mcghee** [comment]
During testing on `v2.6.7` I was able to reproduce the overflow issue by following the Steps to Reproduce. Also during testing, I no longer observed the overflow issue on `v2.7-head` (Commit ID: 216bb7f) when following the Steps to Reproduce, however, I did observe that the newly implemented functionality was inconsistent with how RKE1 handled the overflow issue (by wrapping the text), and I also noted that when hovering over the abbreviated user there was no tooltip generated that would expose the full name of the user.

Personally I am a fan of the current abbreviated implementation of the RKE2 functionality (if we include the additional tooltip containing the complete display name), but in any regard (whether it be wrapping the text or abbreviating it with a tooltip) RKE1 and RKE2 functionality should be consistent. Therefore I am Reopening this ticket.

**Steps to Reproduce:**
1. Create a new user with a very long Display Name
2. During the creation of an RKE2 cluster, navigate to the _Member Roles_ tab, and click the _Add_ button
3. In the _Select Member_ dialogue, locate the new user

**`v2.6.7`:**
![image](https://user-images.githubusercontent.com/13294321/207431354-22c71084-f8a7-4790-826e-7cff85cd0808.png)

**`v2.7-head` (Commit ID: 216bb7f):**
**RKE2**
![image](https://user-images.githubusercontent.com/13294321/207431509-5029cc57-e0da-447c-944e-d2ca96c6d43e.png)
**RKE1**
![image](https://user-images.githubusercontent.com/13294321/207431706-d5062a1f-cf14-4688-b8af-36c2682cd185.png)

**Comment by richard-cox** [comment]
The old ember UI contains many legacy components that do not align with new (and in many cases improved) dashboard UI ones. Eventual these old components will go away when we no longer need to embed the old UI and I don't think we need to restrict ourselves them.

We should definitely provide a way for the user to see the entire name, and would agree the tooltip is the way forward.

**Comment by torchiaf** [comment]
HI @jameson-mcghee ! Just pushed a change to introduce the tooltip for RK2 Clusters form.

**Comment by jameson-mcghee** [comment]
@torchiaf, I am not seeing the tooltip as I would expect. Is it somewhere else?

![image](https://user-images.githubusercontent.com/13294321/208198591-c30a9cfd-ace5-4e5a-8b77-483c30785c58.png)

**Comment by torchiaf** [comment]
Hi @jameson-mcghee , I actually implemented the tooltip to pop up once that an option is selected and the drop-down element is closed. Please take a look to this pic: https://github.com/rancher/dashboard/pull/7723#issue-1498722486

**Comment by jameson-mcghee** [comment]
@torchiaf, Ah, I see! Thank you

Based on my previous testing was well as confirmation of the tooltip implementation while testing on `v2.7-head` (Commit ID: 65089ee), I am closing this ticket as Done.

**`v2.7-head` (Commit ID: 65089ee): _View of tooltip_**
![image](https://user-images.githubusercontent.com/13294321/208728001-456b3c18-d291-48cf-be6e-f0d7471f28fb.png)
