### ISSUE TITLE
Workloads - Detail 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#693]
# Workload Types

Within each type, you have the ability to specify a pod template, which has the same components for all workload types. Either metadata or the pod spec itself. The pod template is located in different locations based on the workload type. 

The pod spec/metadata of the pod will be in the Pod Detail page (https://github.com/rancher/dashboard/issues/685), so most of those fields will not be in the workloads detail page. 

# MastHead

Header/Label Name | k8s yaml |
---|---|
Namespace | `metadata.namespace` | 
Name | `metadata.name` |
Description | `metadata.annotations.cattle.io/description` |

# DetailTop

Workload Type | Header/Label Name | k8s yaml
---|---|---
all | Type  | Workload Type | `kind`
Deployment <br> StatefulSet <br> ReplicaSet | Replicas | `spec.replicas`
Job  | Succeeded | `status.succeeded`
Job  | Failed | `status.failed`
Job  | Start Time | `status.startTime`
Job  | completionTime Time | `status.completionTime`
CronJob | Last scheduled time | `status.lastScheduleTime`
StatefulSet | Services | `spec.serviceName`
Deployment <br> ReplicaSet | Available | `status.availableReplicas`
Deployment | Unavailable | `status.unavailableReplicas`
Deployment <br> ReplicaSet | Ready | `status.readyReplicas`
ReplicaSet | Fully Labeled | `status.fullyLabeledReplicas`
Deployment | Updated | `status.updatedReplicas`
DaemonSet | Number | `status.currentNumberScheduled`/`status.desiredNumberScheduled`
DaemonSet | Available |
DaemonSet | Unavailable | 
DaemonSet | Ready |
DaemonSet | Misscheduled | 
DaemonSet | Updated
All | Created |

# Main Content

## Pods
List of pods in the Workload - Need to find pods that match the selector

Table of pods with the following headers:

Header | Value
---|---
State | 
Name | Name of Container with link to pod detail page
Image Name | Name of Image
Ports | TBD of content
Node | Node that the container is running on with link to node detail page

# Tabs 

Type |Header |
---| --- |
All | Pod Overview | 
All | `<Resource Type>`Details |
Deployment <br> DaemonSet  <br> StatefulSet <br> ReplicaSet <br> Job | Conditions 
Stateful Set | Volumes | 
All | Labels |
All | Annotations |

**Comment by deniseschannon** [comment]
## Scaling/Upgrading Tab
This tab will have varying components based on the workload type. 

### Update Strategy

-[ ] Add a title for `Update Strategy` and only show for `Deployment`, `DaemonSet`, `StatefulSet`

**Deployment Update Strategy**
Header/Label Name | k8s yaml | Input Field/Component |   Helper Text | Units | 
---|---|---|---|---|
No Header | `spec.strategy.type` | Radiobutton Options: <br> * Rolling Update: Create new pods until max surge is reached before stopping old pods. Don't stop more pods than max unavailable.  (`RollingUpdate`)  * Recreate: Kill ALL pods, then start new pods (`Recreate`)  |  
Max Surge | `spec.strategy.rollingUpdate.maxSurge` | Integer Input Textbox  | `The maximum number of pods allowed beyond the desired scale at any given time.` | Dropdown Options: <br> * `%`  <br> * `Pods`|
Max Unavailable | `spec.strategy.rollingUpdate.maxUnavailable` | Integer Input Textbox  |  `The maximum number of pods which can be unavailable at any given time.` | Dropdown Options: <br> * `%`  <br> * `Pods`|

**DaemonSet Update Strategy**

Header/Label Name| k8s yaml | Input Field/Component |   Helper Text | Units | 
---|---|---|---|---|
No Header | `spec.strategy.type` | Radiobutton Options: <br> * Rolling Update: Stop old pods, then start new pods (`RollingUpdate`)  * On Delete: New pods are only created when you manually delete old pods  (`On Delete`)  |  
Max Unavailable | `spec.strategy.rollingUpdate.maxUnavailable` | Integer Input Textbox  |  `The maximum number of pods which can be unavailable at any given time.` | `Pods` |

**StatefulSet Update Strategy**
> Note: We are not implementing the StatefulSet `partition` field as part of RollingUpdate upgrades. 

Header/Label Name | k8s yaml | Input Field/Component |   Helper Text | Units | 
---|---|---|---|---|
Pod Management Policy | `spec.podManagementPolicy` | Radio Button Options: <br> *Create pods in order and wait for the pod to be ready before continuing (`OrderedReady`) <br> * Create pods without waiting. Upon deletion, remove all pods at once (`Parallel`) |
No Header | `spec.strategy.type` | Radiobutton Options: <br> * Rolling Update: Stop old pods, then start new pods (`RollingUpdate`)  * On Delete: New pods are only created when you manually delete old pods  (`On Delete`)  | 

**ReplicatSet/Job/CronJob Update Strategy**

None - Do not show anything in this section and hide `Update Strategy` title within tab

Workload Type | Header/Label Name | k8s yaml | Input Field/Component |  Helper Text |  Units
---|---|---|---|---|---
Deployment | Progress Deadline | `spec.progressDeadlineSeconds` | Integer Input Textbox |  `The duration that a deployment can make progress before being considered failed.` | `Seconds`
Deployment <br> DaemonSet <br> StatefulSet | Revision History Limit  | `spec.revisionHistoryLimit` | Integer Input Textbox |  `The number of versions to retain.` |  `Revisions`
Deployment <br> DaemonSet <br> ReplicaSet | Minimum Ready | `spec.minReadySeconds` | Integer Input Textbox |  `The minimum amount of time that the pod can be ready without any containers crashing to be considered available. ` |  `Seconds`

**Comment by deniseschannon** [comment]
## Volumes Tab
This is still TBD, but wanted to get started on mocks for other pages.

Workload Type | Header/Label Name | k8s yaml | Input Field/Component | 
---|---|---|---|
StatefulSet | StatefulSet Persistent Volume Claim Templates | `spec.volumeClaimTemplates` | Ability to add/remove PVCs

**Comment by deniseschannon** [comment]
@lvuch We should have mocks for:
 
* Deployment/DaemonSet/ReplicaSet
* StatefulSet
* Job
* CronJob

**Comment by lvuch** [comment]
https://xd.adobe.com/view/21c4a244-1c6e-4ba6-5a6d-fbe37fd6e60b-57f5/

**Comment by lvuch** [comment]
https://xd.adobe.com/view/63fc22b6-0cf6-4f90-900e-a75d6b0eb9ff-36af/

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `8d9cedde9 `**

**Issues in** 
### DetailTop
- `Job` wokrload does not have fields - Succeeded, Failed, Start time, completion time
- `CronJob` workload does not have Last scheduled time field
- `DaemonSet` listed fields are not available

### ResourceType Details Tab
- Stateful set Type
- - StatefulSet partition field is available (original issues says this will NOT be implemented)
- - Pod Management Policy is NOT available

### CronJob Type
- Schedule, Concurrency and Starting Deadline Seconds fields are not available

### StatefulSet type
- Volume claim template is NOT available

**Comment by sowmyav27** [comment]
**On master-head - commit id: `33f755f180`**

### DetailTop
- `Job` workload has fields - Succeeded, Failed, Start time, completion time
- `CronJob` workload has `Last scheduled time` field

### ResourceType Details Tab

- Stateful set Type
- - StatefulSet partition field is NOT available (as expected)
- - Pod Management Policy is available

### CronJob Type
- Schedule (in the container section), Concurrency and Starting Deadline Seconds fields are available

### **Issues:**
- `Daemonset` has all fields except for a field `Misscheduled` --> Do we need this field ? 
- Volume Claim template is available for a statefulset but the input fields are not correct. Logging a separate issue to track this -- https://github.com/rancher/dashboard/issues/1292

Reopening the issue to get confirmation on the issue seen for `Daemonset`

**Comment by deniseschannon** [comment]
@mantis-toboggan-md Sounds like we need to add the `Misscheduled` to detail top to close this issue.

The yaml is `status.numberMisscheduled`.

**Comment by sowmyav27** [comment]
Logged a separate [issue](https://github.com/rancher/dashboard/issues/1319) for [this](https://github.com/rancher/dashboard/issues/693#issuecomment-695370443)
