### ISSUE TITLE
Ensure drone does not block PRs from merging

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6936]
- A few times we have PRs blocked from merging due to a phantom drone task that does not run (https://github.com/rancher/dashboard/pull/6883 is an example... however since merge the blocking gate has disappeared)
- We need to double check .drone.yml and ensure there's nothing that might be triggered by PRs (i think this is at least the FOSSA job that doesn't have a specific trigger)
  - see https://drone-pr.rancher.io/rancher/dashboard/6421 (from merge https://github.com/rancher/dashboard/pull/6784)

**Comment by nwmac** [comment]
@richard-cox Anything still to do here?

**Comment by richard-cox** [comment]
I think this is still an issue when the branch of a PR changes. The FOSSA task in .drone.yml is strange, as it has no trigger. It could be that or something in that env. Either way EIO seem reluctant to investigate

**Comment by nwmac** [comment]
@richard-cox I think we should close this as won't fix.

**Comment by richard-cox** [comment]
The phantom jobs have now gone away, i think these were the ones running on `drone-pr`
