### ISSUE TITLE
Validate master works on 2.4.5

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#694]
* Header on all pages - This area is different/new compared to the old master. 

* OPA Gatekeeper - Parameters support added
* Cluster Overview
* Nodes - List/Detail pages
* Config Maps
* Secrets

Pages that are added in but haven't been sent to QA to validate yet:
* Service
* Ingress
* Generic Resource Detail

**Comment by sangeethah** [comment]
```docker run -d --name=v2.4-head --restart=unless-stopped \
  -e CATTLE_DASHBOARD_INDEX=https://releases.rancher.com/dashboard/latest/index.html \
  -p 80:80 -p 443:443 rancher/rancher:v2.4-head```

**Comment by izaac** [comment]
Validated

- Dashboard Overview (Completed)
  - #702 
  - #703 
  - #704
- OPA Gatekeeper (In progress)
  - #706

**Comment by aaronRancher** [comment]
Validated with `rancher\rancher:v2.4-head` `version c357f562f`:
* Secrets (Opaque, Registry, Certificate)

**Comment by soumyalj** [comment]
Configmaps:

Issue: https://github.com/rancher/dashboard/issues/709

**Comment by deniseschannon** [comment]
`master` was synced to 2.4 branch.

**Comment by deniseschannon** [comment]
Will review any other issues filed separately.
