### ISSUE TITLE
Escape characters shown on user preferences screen

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6958]
See below:

![image](https://user-images.githubusercontent.com/1955897/191678365-99aee92b-f431-402a-bf15-02301e2bf3fe.png)

This will need a fix for both 2.6.9 and 2.7.0.

This ticket is to fix for 2.6.9.

Please create another issue for 2.7.0 by cloning this one. You'll need to create a PR against the 2.6.9 release branch and one against master.

The change that broke this is here:
https://github.com/rancher/dashboard/pull/6822/files#diff-316ed9b2628e1438c50d24acd6d498b6957248543643f69b63528eee0761b1ddL210

You need to put that line back to what it was.

**Comment by jameson-mcghee** [comment]
@bisht-richa This ticket needs a forward port tickets created.

**Comment by Josh-Diamond** [comment]
Ticket #6958 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-8062f1e3ab7bff870dfab195ff699a308644168a-head`:
1. Fresh install of rancher `v2.7-head`
2. Navigate to `User Preferences > Advanced`
3. Verified - No escape characters shown; as expected

Screenshot:
<img width="1047" alt="Screenshot 2023-01-06 at 3 02 41 PM" src="https://user-images.githubusercontent.com/46494969/211107785-7da9c4a4-1a75-4c49-a332-8db046cc8cb5.png">
