### ISSUE TITLE
On logout a growl blips up and error is shown in console

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6959]
**Setup**
- Rancher version: 2.6-head (pre 2.6.9)

**Describe the bug**
- When a user logs out a growl is very briefly shown
- There is also an error in the console (which is shown during other times without a growl displaying)
  - We need to understand why this happens rather than just making the line null safe 

![image](https://user-images.githubusercontent.com/18697775/191703866-574f4587-2c7b-4f9e-9d6f-c07f2ce0eefd.png)

**To Reproduce**
- Log in, nav to home screen and refresh
- Log out

**Expected Result**
- Part 1 - No growl is shown
- Part 2 - No error

**Comment by gaktive** [comment]
We'll need to look over this once we sort out the future of growls.

**Comment by gaktive** [comment]
Closing this since we've now disabled growls by default in 2.6.9.
