### ISSUE TITLE
Prompt user to confirm node deletion when scaling down node pool in GUI

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#6961]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
In a cluster created with a node template, navigate to the nodes page and click on the minus ("-") button next to a node pool.

**Actual Result:**
A node is immediately deleted upon clicking the button.

**Expected Result:**
There should be a confirmation prompt displayed to the user to prevent accidental deletion of nodes.
Note: When selecting "Delete" from the context menu of a node, such confirmation prompt is displayed indeed.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.5
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Infrastructure Provider

**Comment by gaktive** [comment]
There's another ticket somewhere that explores UX around confirmation upon deleting nodes. @kwwii to dig around.

**Comment by nwmac** [comment]
@bisht-richa 

For this ticket, we need to add a confirmation dialog when the user pressed the minus icon on a cluster detail page (go to Cluster Management -> [cluster])

example:



The behaviour we want is that when the user clicks on the minus icon, they are show a confirmation dialog.

IF they hold down the alt key, we should NOT show this dialog - this is a pattern we use elsewhere - e.g. `shell/pages/c/_cluster/explorer/tools/index.vue`.

The dialog should contain a message asking for confirmation and show the tip that the user can hold down alt not to show again - here is an example to use as a template:

![image](https://user-images.githubusercontent.com/1955897/204779923-c8981db6-aebd-4553-9f31-fecc8da6e33e.png)

Note: Buttons should be Cancel and Confirm.

This dialog should also show a checkbox below the first line of text - this should say 'Don't prompt again for confirmation when scaling down'.

This checkbox should be checked by default and the state should be remembered - so if the user unchecks it and then scales down again, the checkbox will not be checked.

If the user checks the checkbox, we need to remember this (only within the user's browser session - we don't need this to persist across reloaded) - i.e. the first time they scale down, we prompt for confirmation. The checkbox is checked by default, so next time the scale down, we will NOT prompt again.

Hopefully this is clear - let me know if not.

**Comment by bisht-richa** [comment]
I also added prompt confirmation setting option on pref page:

![Screenshot 2023-01-11 at 13.34.50.png](https://zube.io/files/rancher/42024f6d75028d180ba18b3a436c5413-screenshot-2023-01-11-at-13-34-50.png)

**Comment by nwmac** [comment]
@bisht-richa I have re-opened this issue as the merged code does not work properly:

1. The code only works for RKE2 clusters and not RKE clusters - you need to wire the confirmation into `management.cattle.io.nodepool` as well
2. The preference does not work correctly - I think it would be better to change the meaning from Show to Don't show - i.e the preference would be "Don't ask for confirmation when scaling down node pools" - I think the problem is due to the preference defaulting to empty string. Currently, on a fresh system where the preference is new, if you go to preferences, the pref shows checked - if you uncheck it, you will still be asked for confirmation. Alternatively, you can try defaulting it to true rather than an empty string.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 48d1f8e
Rancher cluster type: single-node docker install
Docker version: 20.10

Downstream cluster type: k3s and rke2

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy a k3s/rke2 node driver cluster - multiple machine pools
2. Select a node and click on Scale Down
3. Verify pop-up dialog window

**Result**
Now Rancher confirms with user that a machine is being deleted and also gives user the option to opt out of future warnings
![image.png](https://zube.io/files/rancher/d161770b493cf3a59f32fcf68921025c-image.png)
