### ISSUE TITLE
Persistent Volume Edit Page Contains All Consuming PVC summary card

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6962]
**Setup**
- Rancher version: 2.6-head (pre-2.6.9)

**Describe the bug**
- Summary box used to show PVCs consumes all the vertical space

**To Reproduce**
- Edit any PV

**Result**

Both screenshots show card consuming space, though the second one is forced smaller due to the `Customize` tab consuming more space

![image](https://user-images.githubusercontent.com/18697775/191731917-99bc6741-b373-4cef-b831-003ecdc324e3.png)

![image](https://user-images.githubusercontent.com/18697775/191731874-70c83a3d-987b-4878-bdf3-f53a4a40cbd3.png)

**Comment by torchiaf** [comment]
Hi @richard-cox , could you please assign it to me? I am not enabled to self-assign for the moment.

**Comment by richard-cox** [comment]
@torchiaf I'll add the issue to the 2.7.0 milestone, if other commitments keep you away and you feel it won't get done by next week feel free to move to 2.7.1

**Comment by anupama2501** [comment]
Reproduced the issue on v2.6.9
1. Created a cluster rke1 node driver - 1 node all roles Linode
2. On v2.6.9, create a pv from cluster explorer >> storage >> pv
3. Create a pvc using this pv as a storage option.
4. See the space consumption is too much for the PVC:
<img width="500" alt="pv" src="https://user-images.githubusercontent.com/38144301/197547533-4fae8f73-9722-46e2-84a3-14be55a9e025.png">

Verified on v2.7-head 40932d6 test cases
1. After the above upgrade, verified the pvc do not consume too much space in pv and grows according to the name
2. On a fresh install, create a PV and associated it to a PVC on an rke1 and rke2 clusters node driver Linode and verified the spacing looks good.
3. Verified by creating a big name for the PVC and noticed the spacing looks good.
4. Verified by creating a big project name and namespace and created a PVC with another big name and verified the bound pvc in summary looks good.
