### ISSUE TITLE
Incorrect Workload Create Screen Text

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6963]
**Describe the bug**
- Title is incorrect (should be `Workload`)
- Missing l10n for pod

![image](https://user-images.githubusercontent.com/18697775/191816868-5dd481a7-32b5-4c08-896c-141de0b72f91.png)

**To Reproduce**
- Nav to explorer product
- Click on Workload group
- Click on Create

**Comment by sowmyav27** [comment]
**On 2.7-head commit id: `c567ef3`**
<img width="1486" alt="Screen Shot 2022-09-27 at 8 26 15 PM" src="https://user-images.githubusercontent.com/26032343/192680702-6a220be8-9000-4dd0-9d6f-ab334f8088fb.png">

Able to create Deployment/cron Job/Daemonset/Pod
