### ISSUE TITLE
Forward port from 2.6.9 to 2.7.0: Detail page for Pods uses detail page for Workloads

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6967]
https://github.com/rancher/dashboard/issues/6842 has the specifics about the work involved but PR https://github.com/rancher/dashboard/pull/6952 was merged only into `release-2.6.9` and not `master`.

This issue is to ensure we get the same work into 2.7.0.

**Comment by mantis-toboggan-md** [comment]
This is covered by this PR (already merged) https://github.com/rancher/dashboard/pull/7041

**Comment by AndrewHoffmanQA** [comment]
retest passed, tested on downstream v2.7.0-rc3

 ![image.png](https://zube.io/files/rancher/9e7ce0c273bbfb137d6af14c4d65fe0b-image.png)

pods show the correct UI elements.
