### ISSUE TITLE
Improve performance setting fetch

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6972]
In `subscrube.js` we have duplicated code (see below) and we have the default set there in 2 places as well as in the default for the setting itself.

```
    let disableGrowl = true;

    if ( perfSetting?.value ) {
      disableGrowl = JSON.parse(perfSetting.value).disableWebsocketNotification !== false;
    }
```

We already have some code in the `resource-fetch` mixin that does something similar.
We should create a single function for getting this setting and put it in `settings.js` and use it in all 3 places.

Note, the current code in `resource-fetch.js` does not support upgrade - i.e. we have added `disableWebsocketNotification` to the JSON, but for a setting created before that was added, we will not return the default in the code.

I think we should do something like this:

```
    // fetching the settings related to manual refresh from global settings
    const perfSetting = this.$store.getters['management/byId'](MANAGEMENT.SETTING, SETTING.UI_PERFORMANCE);
    let perfConfig = {};

    if (perfSetting && perfSetting.value) {
      try {
        perfConfig = JSON.parse(perfSetting.value);
      } catch (e) {
        console.warn('ui-performance setting contains invalid data'); // eslint-disable-line no-console
      }
    }

    // Start with the default and overwrite the values from the setting - ensures we have defaults for newly added options
    perfConfg = Object.assign(DEFAULT_PERF_SETTING, perfConfig);
```

**Comment by bmdepesa** [comment]
Code style cleanup, no functional changes.
