### ISSUE TITLE
Dashboard requests grafana URLS even when v2 monitoring is not installed

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6977]
Look at the browser log - we fetch grafana URLs even when v2 monitoring is not installed.

Should only make those requests if v2 monitoring is enabled.

**Comment by ronhorton** [comment]
**Pass** Verified in `2.7-head commit id 9e7e4bc`

1. filtered for 'grafana' in dev tools network tab
2. navigated to dashboard for cluster with monitoring installed - grafana requests made as expected
3. navigated to dashboard for second cluster with monitoring installed (difft os) - grafana requests made as expected
4. navigated to dashboard for third cluster without monitoring installed - no grafana requests made for dashboard.
