### ISSUE TITLE
Text in list view is weird when first loading a page with no resources

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#698]
<img width="1032" alt="Screen Shot 2020-05-27 at 9 39 22 AM" src="https://user-images.githubusercontent.com/11410997/83048140-01448a00-9ffe-11ea-8b21-b6492900b1c0.png">

**Comment by codyrancher** [comment]
It appears to be working now. I believe someone else already resolved this issue.

**Comment by deniseschannon** [comment]
Haven't seen it againn so I'll close it.
