### ISSUE TITLE
E2E tests in CI are randomly returning false positive

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#6980]
# Description

E2E can occasionally pass without run any test.

## Context

A PR has been merged while creating errors: https://github.com/rancher/dashboard/actions/runs/3105521574/jobs/5031443286 

Log:
```
Opening Cypress...
[7276:0922/130035.846850:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[7276:0922/130035.852476:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

tput: No value for $TERM and no -T specified
```

**Comment by cnotv** [comment]
Issue seems common and possible to solve by disabling the GPU from the CI instance.
https://github.com/cypress-io/cypress/issues/14558#issuecomment-1254478267

**Comment by cnotv** [comment]
Since this error seems to appear always ([like here](https://github.com/rancher/dashboard/actions/runs/3152532853/jobs/5127872606)), but randomly not running tests, it is mandatory to define the scenario.

**Comment by cnotv** [comment]
As @richard-cox mentioned, the issue occurs while re-running the tests after a fail.
Faulty runs have usually shorter time due lack of tests.

**Comment by cnotv** [comment]
It seems something related to the Sorry Cypress library we have to use 🙃 
https://github.com/rancher/dashboard/actions/runs/3154540532/jobs/5132893053

**Comment by cnotv** [comment]
At current date, seems like second attempts to run E2E tests are not failing anymore or there's another reason.

**Comment by gaktive** [comment]
@cnotv based on your comments, what's left to do with this ticket?
