### ISSUE TITLE
Execute shell on workload page not work correctly

### ISSUE THREAD

**Issue by altitude1326** [rancher/dashboard#6982]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option: Helm Chart on kubernetes OVH  v1.20.2

**Information about the Cluster**
- Kubernetes version:  v1.20.2
- Cluster Type : OVH 

**User Information**
- What is the role of the user logged in:  Admin/Cluster

**Describe the bug**
When using  "Execute Shell" submenu on workload screen, if there is many workload on different namespace, it will allways connect to the same container, even if we select a specific namespace
This bug not happen when doing execute shell directly on pod

**To Reproduce**
1) deploy same workload on differents namespaces (ex on namespace a,b,c)
2) go to workload screen
3) add filter on namespace b
4) click on execute shell

**Result**
you may connected to pod that run on another namespace than expected one.

**Expected Result**
you connected to pod that run on namespace b

**Screenshots**
![Capture d’écran 2022-02-01 à 16 35 32](https://user-images.githubusercontent.com/35727484/151999255-b1cd222e-0379-428c-8c65-3d6bcc6a8ffc.png)

**Comment by Josh-Diamond** [comment]
Ticket #6982 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-8062f1e3ab7bff870dfab195ff699a308644168a-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream cluster - [ I used RKE2 AWS Node driver w/ k8s `v1.25.5+rke2r1` ]
3. Once active, create three namespaces under `default` project - [ a, b, c ]
4. Create the same deployment in each namespace
5. For each namespace, filter by namespace and execute shell
6. Verified - filter successfully filters namespaces; execute shell launches in correct pod
7. Filter only a + b (excluding c), and launch execute shell for each namespace deployment
8. Verified - filter successfully filters namespaces; execute shell launches in correct pod
9. Filter a + b + c , and and launch execute shell for each namespace deployment
10. Verified - filter successfully filters namespaces; execute shell launches in correct pod

Screenshot:

`Step 9`
<img width="1594" alt="Screenshot 2023-01-06 at 11 36 23 AM" src="https://user-images.githubusercontent.com/46494969/211078914-1a006eef-7efb-482a-91f7-ea0fc98cc0cd.png">
