### ISSUE TITLE
[2.7] Disable growl on socket disconnect by default

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#6992]
- There's been issues with the growl shown when web sockets disconnect
- A setting to disable these was added which defaults to off
- Given new issues we should set the default disabled value to on
  - See slack threads 
  - https://github.com/rancher/dashboard/issues/6959

As part of this fix we need to make sure we're still trying to reconnect in the background if this setting is on

2.6.9 issue: https://github.com/rancher/dashboard/issues/6960

**Comment by Josh-Diamond** [comment]
Ticket #6992 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-40c390d79faef993e8509d545a4ed1e18a78a4de-head`:
1. Fresh install of rancher `v2.7-head`
2. Navigate to `Global Settings > Performance > Websocket Notifications`
3. Verified - `Disabled` by default

Screenshot:

<img width="1562" alt="Screen Shot 2022-09-29 at 11 02 30 AM" src="https://user-images.githubusercontent.com/46494969/193107905-8198318a-5f01-426a-adc7-5b2e02d1699b.png">
