### ISSUE TITLE
Logging v1 - error when viewing/downloading cattle-logging yaml

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#7001]
**Setup**
- Rancher version: `2.6.8`
- Browser type & version: `chrome 105.0.5195.125 (Official Build) (x86_64)`

**Describe the bug**
Installed logging v1. when attempting to view/edit the cattle-logging yaml in the system project, error in UI. when attempting to download yaml, uncaught exception in dev tools, and no download initiated. 

**To Reproduce**
1. provision a k8s 1.20 cluster RKE1 Rhel 8.6 (used in this test)
2. install logging v1
3. confirm logs are flowing to endpoint specified
4. goto projects/namespaces
5. attempt to edit or download catte-logging namespace yaml

**Result**
500 error in console
[Object object] error on UI

**Expected Result**
yaml opened for editing

**Screenshots**
<img width="1574" alt="2022-09-26_11-11-58" src="https://user-images.githubusercontent.com/89212856/192320284-2592bf25-31bb-4ebf-b140-f48c8bb38a90.png">

<img width="1363" alt="2022-09-26_11-11-21" src="https://user-images.githubusercontent.com/89212856/192320255-9de55a44-ac51-4c7a-ac37-d7d51127e286.png">

**Additional context**

**Comment by gaktive** [comment]
Logging v1 will be deprecated in 2.7.0 so fixing this is not a priority. However, we'll check if we need to remove this from the old UI along with Dashboard.

**Comment by Sean-McQ** [comment]
A 500 error is always an internal error on the server producing the API response, if it were a malformed request producing an error, we'd see something like a 300 or a 400 error. Recommend transfer to backend.

**Comment by gaktive** [comment]
@ronhorton do you have details on the logging provider used? We're going to transfer this to `rancher/rancher` since it looks like a backend issue rather than UI.

**Comment by ronhorton** [comment]
i've been unable to reproduce this error. closing for now.
