### ISSUE TITLE
Remove user preference to toggle locale to none

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#7015]
- Remove the user preference `Enable Language Selection keyboard shortcut toggle (shift+L)` as it's only meant to be used by developers and "gate" it to be available on DEV builds only

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/40c390d79faef993e8509d545a4ed1e18a78a4de.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/40c390d79faef993e8509d545a4ed1e18a78a4de
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigated to user profile > Preferences.
3. Validated that the user preference `Enable Language Selection keyboard short toggle (shift+L) is no longer there:
![image](https://user-images.githubusercontent.com/52591819/193100585-b03cdd3c-3e96-4343-bcaa-5a13d9402194.png)
