### ISSUE TITLE
Provider on Overview displays the first Provider returned by the API when multiple clusters exists in Rancher

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#702]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an Amazon Ec2 cluster (Used CentOS 7 for the Nodes)
2. Create one Linode and one DigitalOcean clusters.
3. Navigate to Try Dashboard

Depending on the cluster information returned by the API it seems that the first object returned by the `data` key would grab the Provider/driver and render that in the UI.

In my case the json returned `driver: "digitalocean"` and that Provider was displayed in the other clusters.

**Result:**

Ember UI:
![Screen Shot 2020-05-27 at 12 42 38 PM](https://user-images.githubusercontent.com/27659/83065264-0c0c1880-a018-11ea-9c1a-f33c01bb0385.png)

Vue UI:

![Screen Shot 2020-05-27 at 12 42 49 PM](https://user-images.githubusercontent.com/27659/83065286-16c6ad80-a018-11ea-9198-b64d0ae4e347.png)

**Environment information**
- Rancher version: 
  - `2.4-head (05/27/2020)` aae934198 with `CATTLE_DASHBOARD_INDEX=https://releases.rancher.com/dashboard/latest/index.html`
- Installation option: Single
- Cluster type Amazon EC2

**Comment by izaac** [comment]
This also reproducible with a Custom cluster, it seems the Dashboard always shows `Provider: Digitalocean`

**Comment by deniseschannon** [comment]
I don't see this @izaac in my setup.

<img width="777" alt="Screen Shot 2020-05-27 at 1 13 45 PM" src="https://user-images.githubusercontent.com/11410997/83067663-eb45c200-a01b-11ea-9f65-4857906759d3.png">

**Comment by izaac** [comment]
@deniseschannon is that Rancher master? maybe is it because I'm in `2.4-head` ? 

I will check with master too.

**Comment by izaac** [comment]
Ok I was able to reproduce in latest master too. But I will update the steps to reproduce as I've noticed this is happening when there are multiple clusters provisioned in Rancher.

It looks as if the UI is reading and rendering the first Provider return from API, as I also see the others providers returned by `/v1/management.cattle.io.nodetemplates` and the provider will always be the first item in the `data` key.

**Comment by izaac** [comment]
Rancher version `master-head (07/14/2020)` _691feb01a_ k8s HA install
dashboard-index -> `latest`

Tested with different infrastructure providers, hosted kubernetes, custom and imported clusters.
This is working as expected now, the Provider label is showing the right provider.
