### ISSUE TITLE
Allow user to change the volume name when creating a workload

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#7021]
**Describe the bug**
REF: https://github.com/rancher/dashboard/pull/6886#issuecomment-1258959310

Allow user to change the volume name in following volume type when creating a workload.

1. Amazon EBS disk
2. Azure disk
3. Azure file
4. CSI
5. Google persistent disk
6. VMWare vSphere volume

**To Reproduce**
1. Go to the deployments list
2. Go to a deployment. In the Pod tab, click **Storage > Add Volume > Open EBS Disk**
3. The name of the volume is not shown

<img width="1409" alt="Screen Shot 2022-09-26 at 9 33 16 PM" src="https://user-images.githubusercontent.com/20599230/192432817-c430a2fa-5d41-4fc5-b1fc-ec59ced8f75f.png">

**Expected Result**
User should be able to edit the volume name

**Comment by nwmac** [comment]
@Shavindra This is in test, but has no milestone.

I think this was fixed in 2.7.0 ? Can you confirm
