### ISSUE TITLE
DigitalOcean provider in Overview is displayed as Digitalocean (lowercase o)

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#703]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create DigitalOcean RKE cluster
2. Navigate to Try Dashboard

**Result:**

Ember UI:

![Screen Shot 2020-05-27 at 12 49 35 PM](https://user-images.githubusercontent.com/27659/83065569-8fc60500-a018-11ea-95e5-fe8db85ee19e.png)

Vue UI:

![Screen Shot 2020-05-27 at 12 49 43 PM](https://user-images.githubusercontent.com/27659/83065575-93598c00-a018-11ea-9540-22265b6b2f38.png)

**Environment information**
- Rancher version: 
  - `2.4-head (05/27/2020)` aae934198 with `CATTLE_DASHBOARD_INDEX=https://releases.rancher.com/dashboard/latest/index.html`
- Installation option: Single
- Cluster type Amazon EC2

**Comment by deniseschannon** [comment]
Validated as of 6/8:
<img width="197" alt="Screen Shot 2020-06-08 at 10 18 22 PM" src="https://user-images.githubusercontent.com/11410997/84108847-0b8b5e80-a9d6-11ea-8e42-78250354e9b2.png">
