### ISSUE TITLE
clusterscanreports resource not visible in the drop down list of resources

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7035]
Backend determined that UI is missing a resource from the dropdown list for CIS Scans.

From rancher/rancher/30395:

Incorrect verb "read" versus "get" in clusterscan resource RBAC prevents correctly granting clusterscan permissions

Steps to reproduce (also you can refer to the steps mentioned [here](https://github.com/rancher/rancher/issues/30395#issuecomment-1224227863)):

- Create a Rancher v2.6.8 instance with a single all role custom cluster.
- Create a user `foo`
- Create a custom Global role CIS, that grants get and list on `cisbenchmarkversions.management.cattle.io` and `cisconfigs.management.cattle.io`. Edit user `foo` and grant the custom CIS role.
- Create a custom Cluster role *Clusterscans*, that grants `get` and `list` on `clusterscans.cis.cattle.io`, and grant the user `foo` this role on the custom cluster.
- As the admin user run a CIS Scan on the custom cluster (after installing CIS Benchmark Chart).
- as admin, run a CIS benchmark scan with the '1.6 permissive scan.' profile applied
- log in as the user you created
- view CIS benchmark scan page
- click on the name of the scan

Result:

- Logged in as the admin user observe once the CIS scan is complete that you can click the scan name to view the report details, and that viewing the scan in the API the links: `report: field is populated`.
- Logged in as the user foo observe that whilst the CIS Scan resource is listed, you cannot view the report details in the UI, and whilst you an access the `v3/clusterScans/<cluster_id>:<report_id>/report` API endpoint successfully, the links: `report field in the v3/clusterScans/<cluster_id>:<report_id> endpoint is not populated` (which is the reason the report details are not populated in the UI.

Relevant backend discovery from @rayandas:

> I was debugging why the `clusterscanreports` resource is not visible on the UI.
Things are already written in rancher/cis-operator under `cis.cattle.io` api group. https://github.com/rancher/cis-operator/blob/master/pkg/generated/controllers/cis.cattle.io/v1/clusterscanreport.go. 
It's just not visible on the drop down list on the UI while creating cluster role. If we add `clusterscanreports` resource by editing `kubectl edit clusterrole <name>` then it’s working fine. I think it's an UI issue.

The resource `clusterscanreports` is not visible on the dropdown list in cluster roles. Refer to the below snapshot:

![Screenshot from 2022-09-29 11-35-23](https://user-images.githubusercontent.com/32811240/192952599-5ea99ac5-2919-4eac-bf55-e73fcb0ae656.png)

If we add the `clusterscanreports` resource manually in the cluster role by using kubectl, then the reports are visible and downloadable from user foo. So it seems like `clusterscanreports` is working and it's just not visible in the drop down list.

_Originally posted by @rayandas in https://github.com/rancher/rancher/issues/30395#issuecomment-1259456188_

**Comment by catherineluse** [comment]
This is a very easy one-line change. I've made the change in https://github.com/rancher/dashboard/pull/7259

**Comment by AndrewHoffmanQA** [comment]
retest failed, passing this ticket back to dev.

as an admin i cannot see clusterscanreports as a resource option when creating a clusterRoleTemplate

tested on rancher 2.7head ce9a7ae
![image.png](https://zube.io/files/rancher/fc815ce29083e5509dc7d1f348a0d647-image.png)

**Comment by catherineluse** [comment]
@AndrewHoffmanQA Can you go to the global settings and check the value of `ui-dashboard-index`? It should be `https://releases.rancher.com/dashboard/latest/index.html`

I think the reason the change isn't showing is that this is right after the 2.7.0 release, so that setting is still configured for 2.7.0 by default, but this change won't show up in the 2.7.0 version of the UI because this change is scoped for 2.7.1.

**Comment by AndrewHoffmanQA** [comment]
I pulled the latest version of 2.7head and retest now passes. moving to done column!

![image.png](https://zube.io/files/rancher/ca5b8613e63c2a25ed014e09e8e1c6d6-image.png)

note: this bug scope was just around adding clusterRoleTemplate to the UI. the functional testing of the bug is being tracked on this ticket. https://github.com/rancher/rancher/issues/30395#issuecomment-1259456188_
