### ISSUE TITLE
Preferences Dropdown options are not visible in light theme

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#704]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster (Cloud or Custom)
2. Navigate to Try Dashboard
3. Click in the User menu (the light theme is default).

**Result:**

Preferences Dropdown in Light theme:

![Screen Shot 2020-05-27 at 3 00 36 PM](https://user-images.githubusercontent.com/27659/83076893-37e4c980-a02b-11ea-9cb5-5219f0742ed0.png)

Preferences Dropdown in Dark theme:

![Screen Shot 2020-05-27 at 3 02 28 PM](https://user-images.githubusercontent.com/27659/83076919-459a4f00-a02b-11ea-83b1-39c24944e646.png)

**Environment information**
- Rancher version: 
  - `master-head (05/27/2020)` d9184e914
  - `2.4-head (05/27/2020)` aae934198 with `CATTLE_DASHBOARD_INDEX=https://releases.rancher.com/dashboard/latest/index.html`
- Installation option: Single

**Comment by deniseschannon** [comment]
@izaac is this an issue with `master` on `master-head`?

**Comment by izaac** [comment]
@deniseschannon this is both Rancher `master-head` and `v2.4-head` both pointing to the latest UI dashboard `master` index.

**Comment by izaac** [comment]
Rancher `master-head (07/13/2020)` _79618bba4_
dashboard-index -> `latest`

This is looking good in the latest index in Rancher master. 

![Screen Shot 2020-07-13 at 4 25 24 PM](https://user-images.githubusercontent.com/27659/87363233-986d8e80-c525-11ea-8300-0f9acb7e879e.png)
