### ISSUE TITLE
Enable OPA Gatekeeper shows error in Enable button and never refresh and works after manual refresh

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#706]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher
2. Enable Debug in the docker container `docker exec -it v2.4-head loglevel --set debug`
2. Create a cluster (Cloud or Custom)
3. Navigate to Try Dashboard
4. Click OPA Gatekeeper from the Left Menu in the Cluster section.
5. Keep a look at the Rancher log and Click Enable to enable OPA Gatekeeper.

**Result:**

Clicking Enable or Customize and then Enable I ended up with the Enable button turning to Red with Error text and debug logs showing: `[DEBUG] closing watcher for app`.

Refreshing the browser after some time I see OPA Gatekeeper enabled and the watcher is closed

`[ERROR] Error during subscribe websocket: close sent`

![Error-In-Enable-Button](https://user-images.githubusercontent.com/27659/83165667-b80a3e00-a0c2-11ea-8145-2449dde77587.png)
![Screen Shot 2020-05-28 at 9 01 03 AM](https://user-images.githubusercontent.com/27659/83165675-bb052e80-a0c2-11ea-8f44-42b6acc393fb.png)

**Environment information**
- Rancher version: 
  - `2.4-head (05/28/2020)` 24c684289 with `CATTLE_DASHBOARD_INDEX=https://releases.rancher.com/dashboard/latest/index.html`
- Installation option: Single

**Comment by izaac** [comment]
I was not able to reproduce this issue in latest Rancher `master-head (05/28/2020)` commit: b6264dfcb

**Comment by deniseschannon** [comment]
@codyrancher Is this a backend fix that is missing?

**Comment by westlywright** [comment]
The root cause of seeing the `error` button happens when enabling sometimes and the time it takes for the app to finish being launched is longer than the timeout for method we use to watch the conditions on the app. I am putting in a fix to increase this from 30 seconds to 60 seconds.

Regarding the log messages in Rancher, I do not know why the backend would be kicking those off. @deniseschannon if we want to investigate the logs then perhaps @prachidamle can?

**Comment by izaac** [comment]
I do not reproduce the error in `v2.4-head` anymore. But opened a separate bug after the observed behavior when clicking Enable.

I don't get the OPA Overview page if the I just keep idling waiting for OPA to get enabled. I had to refresh manually.

https://github.com/rancher/dashboard/issues/746
