### ISSUE TITLE
Console error:  Cannot read properties of undefined (reading '$workers') on logout

### ISSUE THREAD

**Issue by Sean-McQ** [rancher/dashboard#7065]
**Setup**
- Rancher version: 2.6.9

**Describe the bug**
Error ` Cannot read properties of undefined (reading '$workers')` appears when logging out

**To Reproduce**
Navigate to cluster explorer > Logout > Notice error in dev-tools console

**Result**

**Expected Result**
No error

**Comment by Josh-Diamond** [comment]
Ticket #7065 - Test Results - ✅ 
---

Unable to reproduce; `v2.6-head` points to (fix):
- UI Index: `https://releases.rancher.com/ui/release-2.6.9/index.html`
- UI Dashboard Index: `https://releases.rancher.com/dashboard/release-2.6.9/index.html`

Verified on rancher:
- `v2.6-f3afa8131a9270d51a477c8d4c334ba11ad4c8b0-head`
- `v2.6-78c7ac0187169c67b844c966691a5e5c53a4acc9-head`

1. Fresh install of rancher `v2.6-head`
2. Provision a downstream cluster
3. Once `Active`, Visit `Cluster Explorer`, open dev-tools and LOGOUT
4. Verified - Console error not seen; clean logs
