### ISSUE TITLE
[monitoring v2] in create prometheus rule user cannot `add label` to alert - cannot trigger prometheus rule

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#7069]
**Setup**
- Rancher version: `v2.7.0-rc3`
- Browser type & version: `chrome Version 105.0.5195.125 (Official Build) (x86_64)`

**Describe the bug**

When user clicks cluster > monitoring > Advanced > PrometheusRules > Create, the form that loads has an alert configuration. in the config for the alert, user cannot add a label. 
**To Reproduce**
1. install monitoring `101.0.0+up19.0.3`
2. Create prometheus rule
3. Add alert to prometheus rule
4. click `add label`

**Result**
user cannot add label
**Expected Result**

user can add labels to alerts to allow the prometheus rule to be triggered. 
**Screenshots**

<img width="1639" alt="2022-10-03_17-32-48" src="https://user-images.githubusercontent.com/89212856/193691301-e2cb4192-3f0b-4852-bb44-c2e2c08f5d55.png">

**Additional context**

- this did not occur in 2.6.9-rc3
- same issue in incognito tab
- no error in console
- also happens in rke2 cluster

**Comment by ronhorton** [comment]
work around: save prometheus rule; edit yaml - add label.

**Comment by Shavindra** [comment]
should be fixed with https://github.com/rancher/dashboard/pull/7093

**Comment by ronhorton** [comment]
**Pass** verified fixed in `2.7-head commit id 9f1e04 `

1. installed monitoring
2. Cluster > Monitoring > Advanced > Prometheus Rules
3. create prometheus rule
4. add additional label to alerting rules via ui
5. label is added
6. save
7. checked yaml, labels preserved
