### ISSUE TITLE
Can not add labels or annotations

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7073]
Looks like the KeyValue control is broken.

You can not add new values using that control.

This breaks labels and annotations across the entire UI.

**Comment by Josh-Diamond** [comment]
Ticket #7073 - Test Results - ✅ 
---

With Docker on a single-node instance:

Reproduced on rancher `v2.7.0-rc2`:
1. Fresh install of rancher `v2.7.0-rc2`
2. Provision a downstream cluster
3. Once `Active`, Navigate to `Cluster Explorer > Deployments > Create`
4. Create a new deployment with labels + annotations applied
5. Reproduced - label + annotation buttons selectable but non-responsive

Screenshot:

`Step 5`
<img width="1024" alt="Screen Shot 2022-10-20 at 4 02 20 PM" src="https://user-images.githubusercontent.com/46494969/197078802-2ef9fa5c-0f5f-4492-b132-d99046b050c7.png">

---

Verified on rancher `v2.7-9f1e0435bb45e104ba897c5c329e1f23735843d9-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream cluster
3. Once `Active`, Navigate to `Cluster Explorer > Deployments > Create`
4. Create a new deployment with labels + annotations applied
5. Verified - label + annotation buttons are selectable and responsive
6. Once deployment is `Active`, `Edit YAML` of deployed pod
7. Verified - labels + annotations successfully applied
11. Navigate to `Global Settings > Home Links`
12. Verified - UI accurately displays `Home Links`
13. Verified - All functionality w/ `Home Links` is working as expected - [`add link/show/apply`]

Screenshots:

`Step 5`
<img width="1023" alt="Screen Shot 2022-10-20 at 4 46 36 PM" src="https://user-images.githubusercontent.com/46494969/197080434-ed5c7648-8f82-4dbf-9591-8f0992f2fcd9.png">

`Step 9`
<img width="1024" alt="Screen Shot 2022-10-20 at 4 53 33 PM" src="https://user-images.githubusercontent.com/46494969/197080521-3a9b0cd0-83b0-4bc7-89bf-e5703573b410.png">
