### ISSUE TITLE
Improve mechanism for alerting the user to web socket issues

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7076]
Need something less intrusive than growls.

Maybe an icon that appears in the top bar (perhaps only for admins) that is unobtrusive that when clicked shows more info and would allow the user to hide it going forward.

**Comment by kwwii** [comment]
We should think about adding a persistent tiny footer at the bottom with this kind of information

**Comment by kwwii** [comment]
We changed the behaviour of how and when growls are shown
