### ISSUE TITLE
 ui-brand in global settings cannot be reset

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#7078]
If you set the ui-brand key to "suse" and click save you see that the value has been modified, however when editing the value the "Restore to default value" button is inactive although the value has been changed

**Comment by cnotv** [comment]
<img width="1919" alt="Screenshot 2022-10-06 at 11 27 15" src="https://user-images.githubusercontent.com/5009481/194278874-e0e9a0a6-e5ad-40a5-b16b-2a44a6077209.png">

The colors for the `SUSE` theme are completely broken when I try to reproduce this, I've issues to find the buttons as are all white 😬 
Do we have an issue for it?

**Comment by slickwarren** [comment]
tested on v2.7-head (d8334c8) : 
* user is now able to set and reset the `ui-brand` setting -- pass
