### ISSUE TITLE
Rancher 2.6.x does not allow to download RKE downstream KUBECONFIG provisioned without network CNI (network: plugin: none)

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7080]
Internal reference: SURE-5307
Reported in 2.6.1 to 2.6.8

Issue description:
RKE downstream cluster provisioned by Rancher as CNI none (network: plugin: none) keeps the cluster greyed out, so users are unable to download the KUBECONFIG or interact with it.

This worked until 2.5.x; they were able to download KUBECONFIG from RKE provisioned by Rancher as `CNI network: plugin: none`.

Troubleshooting steps:
Create a RKE downstream provisioned by Rancher as CNI none (network: plugin: none)

Repro steps:

- Create a RKE downstream as `CNI network: plugin: none`
- The cluster stays greyed out
- You are unable to download KUBECONFIG

Workaround:
It's not easy and not acceptable. 

- SSH into CP node
- Generate local KUBECONFIG
- Install any CNI that works
- cattle-agent connects to Rancher * note that the cluster goes from grey to blue (active)
- then download the KUBECONFIG from UI.

Actual behavior:
Unable to download KUBECONFIG from RKE provisioned by Rancher as `CNI network: plugin: none`.

Expected behavior:
Ablity to download KUBECONFIG from RKE provisioned by Rancher as `CNI network: plugin: none`.

**Comment by gaktive** [comment]
We should confirm what we did in 2.5.x or at least with the older Ember UI to determine how the button becomes active (are we waiting for the cluster to be ready?).

**Comment by sowmyav27** [comment]
**On 2.6.9**
<img width="557" alt="Screen Shot 2022-12-27 at 8 42 31 AM" src="https://user-images.githubusercontent.com/26032343/209699643-75c9f5b1-3410-42ab-b6e2-c479433eba07.png">
<img width="1511" alt="Screen Shot 2022-12-27 at 8 42 25 AM" src="https://user-images.githubusercontent.com/26032343/209699648-e4b998a9-6b9f-45d6-81af-ec076fc2cdfa.png">

- Download Kubeconfig is not available on cluster when 
```
network:
    mtu: 0
    plugin: none
```

**On 2.7-head commit id: `28a84c7`**
- Kubeconfig download option is available and as a user, I am able to use this yaml file to perform kubectl actions on the cluster that has not come up Active yet
<img width="1906" alt="Screen Shot 2022-12-27 at 9 13 34 AM" src="https://user-images.githubusercontent.com/26032343/209699830-43378e71-a790-4dee-8c61-cb0294575f09.png">
