### ISSUE TITLE
Number of nodes not shows for RKE2 clusters

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7082]
Internal reference: SURE-5310
Reported in 2.6.8

Issue description:
When showing the machine pools, the number is not listed for rke2 clusters, but shows with RKE1 clusters. This means that users are unable to see number within machine pools at a glance.

Repro steps:

- Create 2 downstream clusters through Rancher: one rke1, one rke2
- Look at the machine pool

No workaround.

Actual behavior:
Only list number in machine pools for rke1 clusters

Expected behavior:
Number of nodes in machine pool shows for both rke1 and rke2

RKE1 view:
![image (2) (1).png](https://zube.io/files/rancher/c872aa0c390637a93017d61dc0803e76-image-2-1.png)

RKE2 view (note the lack of a counter for "0 of 1"):
![image (4) (1).png](https://zube.io/files/rancher/8f0563599cc05fb2b08c6aeb13c8b3f0-image-4-1.png)

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, create a downstream RKE1 cluster and look at the machine pool|
|2|As a standard user, create a downstream RKE2 cluster and look at the machine pool|
|3|As a standard user, create a downstream K3S cluster and look at the machine pool|
|4|As a standard user, setup Rancher `v2.7.0`, repeat scenarios 1-3, upgrade Rancher to latest `v2.7-head` and look at the downstream cluster's machine pools|

**Comment by markusewalker** [comment]
Reproduced this behavior on `v2.7.0`. Will share validation steps in a separate comment than this once I have done so.

**ENVIRONMENT DETAILS**
- Rancher Install: Docker
- Rancher version:`v2.7.0`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, create a downstream RKE1 cluster and look at the machine pool|:white_check_mark:|
|2|As a standard user, create a downstream RKE2 cluster and look at the machine pool|:x:|
|3|As a standard user, create a downstream K3S cluster and look at the machine pool|:x:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigated to Cluster Management.
3. Provisioned a downstream RKE1 node driver cluster; validated that the cluster and nodes are `Active` in Cluster Management and Cluster Explorer.
4. Validated that the cluster's machine pools display the number of machines in a given pool:
![Screen Shot 2022-11-30 at 9 45 29 AM](https://user-images.githubusercontent.com/52591819/204870377-793a059b-1d5d-4602-8692-338bed35ba87.png)
_______
**Scenario 2**
1. Repeated scenario 1, but provisioned a downstream RKE2 node driver cluster instead.
2. Validated that the cluster's machine pools DO NOT display the number of machines in a given pool:
![image](https://user-images.githubusercontent.com/52591819/204869999-6573def7-7d4d-4d95-8df2-03f703e8288a.png)
_______
**Scenario 3**
1. Repeated scenario 1, but provisioned a downstream K3s node driver cluster instead.
2. Validated that the cluster's machine pools DO NOT display the number of machines in a given pool:
![image](https://user-images.githubusercontent.com/52591819/204869937-29b24fca-ee7f-42f1-8c49-df25fd01dd14.png)

**Comment by markusewalker** [comment]
Validated this is fixed on `v2.7-head` https://github.com/rancher/rancher/commit/f7692f30cf47d00073cc41b879e0ff90fb0a68b0. Will share validation steps in a separate comment than this once I have done so.

**ENVIRONMENT DETAILS**
- Rancher Install: Docker
- Rancher version:`v2.7-head` https://github.com/rancher/rancher/commit/f7692f30cf47d00073cc41b879e0ff90fb0a68b0
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, create a downstream RKE1 cluster and look at the machine pool|:white_check_mark:|
|2|As a standard user, create a downstream RKE2 cluster and look at the machine pool|:white_check_mark:|
|3|As a standard user, create a downstream K3S cluster and look at the machine pool|:white_check_mark:|
|4|As a standard user, setup Rancher v2.7.0, repeat scenarios 1-3, upgrade Rancher to latest `v2.7-head` and look at the downstream cluster's machine pools|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigated to Cluster Management.
3. Provisioned a downstream RKE1 node driver cluster; validated that the cluster and nodes are `Active` in Cluster Management and Cluster Explorer.
4. Validated that the cluster's machine pools display the number of machines in a given pool.
_______
**Scenario 2**
1. Repeated scenario 1, but provisioned a downstream RKE2 node driver cluster instead.
2. Validated that the cluster's machine pools display the number of machines in a given pool.
_______
**Scenario 3**
1. Repeated scenario 1, but provisioned a downstream K3s node driver cluster instead.
2. Validated that the cluster's machine pools display the number of machines in a given pool.
______
**Scenario 4**
1. Repeated scenarios 1-3, but ensured that I setup Rancher `v2.7.0` first.
2. Validated that only RKE1 machine pools shows the number of nodes, RKE2 and K3s do not:
3. Upgraded Rancher to `v2.7-head` https://github.com/rancher/rancher/commit/f7692f30cf47d00073cc41b879e0ff90fb0a68b0.
4. Validated that now the RKE2 and K3s nodes have the number of nodes shown in their respective machine pools:
![Screen Shot 2022-11-30 at 9 58 46 AM](https://user-images.githubusercontent.com/52591819/204873763-6183a3ae-630f-4c15-b7e6-b5ff2adc17bf.png)

![Screen Shot 2022-11-30 at 9 58 23 AM](https://user-images.githubusercontent.com/52591819/204873811-ca16e3eb-8f90-42c5-9374-84eb278d463e.png)

![Screen Shot 2022-11-30 at 9 58 13 AM](https://user-images.githubusercontent.com/52591819/204873836-f1ec5dee-90ca-4abc-9e0f-408d9e29c3f7.png)
