### ISSUE TITLE
Cannot clone an existing Role (Global/Cluster/Project/Namespaces)

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7083]
Internal reference: SURE-5274
Reported in 2.6.x

Issue description:
Cannot clone an existing Role (Global/Cluster/Project/Namespaces) in Rancher for a custom Role implementation with reduced permissions to specific K8s resources. This is a supported feature in Rancher 2.5, but does not appear to be available in Rancher 2.6. Looks to be a dropped or missing UI feature when compared to the Rancher 2.5 UI. This reduces UX/operational efficiency for Rancher 2.6 users.

Troubleshooting steps:
In Rancher 2.6, navigate to Users & Authentication > Roles. Click the three dots next to any existing Role. The 'Clone' option does not appear to be available.

Workaround:
Append the "/g" to the Rancher 2.6 server url and navigate to Security > Roles. Click the three dots next to any Role and utilize the 'Clone' option.

Actual behavior:
Users cannot clone an existing Role.

Expected behavior:
Users should be able to clone an existing Role.

Ember view for historical context:
![Rancher-CloneRoles.jpg](https://zube.io/files/rancher/4df2b5763684902f5fc3928dce5b0cfc-rancher-cloneroles.jpg)

**Comment by mantis-toboggan-md** [comment]
fixed in this PR: https://github.com/rancher/dashboard/pull/7258

**Comment by dasarinaidu** [comment]
I have validated this issue on `v2.7-7d16a0d3b67cacd5dff58b055d81d7cd9172ec83-head` . This issue got fixed and I m closing this card.

**Validation details as below:**
**Rancher Version :** `v2.7-7d16a0d3b67cacd5dff58b055d81d7cd9172ec83-head`
**Browsers :** Chrome and Firefox
**Users :** Admin and Standard Users
**Modes :** Auto and Dark

**Test Cases:**

1. Clone Global Roles - System Generated Roles
2. Clone Global Roles - User Created Roles
3. Clone Cluster Roles - System Generated Roles
4. Clone Cluster Roles - User Created Roles
5. Clone Project/Namespace Roles - System Generated Roles
6. Clone Project/Namespace Roles - User Created Roles


**Steps to Reproduce:**

1. Login to Rancher
2. Users & Authentication -> Roles -> Select a Role (Global/Cluster/Project)
3. Click on three dots and select option 'Clone'
4. Provide a Role Name and Create
5.  Check for the Create Role Form and values populated from Clone and Check for New Role creation
