### ISSUE TITLE
Removed v1 tools still listed in the getting started document

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7086]
The Getting Started document linked from the home page still includes detail on the v1 tools that have been removed.

**Comment by ronhorton** [comment]
running 2.7-head commit ID 6b4cf88, still see the v1 items listed; the change to remove the items has been merged - but not seen on the get started page
![2022-11-02_16-43-28.png](https://zube.io/files/rancher/3ca75a1cafb88beb7775037a6fabd6a0-2022-11-02_16-43-28.png)

**Comment by ronhorton** [comment]
Reopening this. There are still references to the 'multi cluster apps' in the get started page 
1. home screen
2. click get started



> **ronhorton said:** running 2.7-head commit ID 6b4cf88, still see the v1 items listed; the change to remove the items has been merged - but still present on the get started page ![2022-11-02_16-43-28.png](https://camo.githubusercontent.com/68e89673ee582415819a5b712368ce09757c2514cf1d35a5e30989c0284e737b/68747470733a2f2f7a7562652e696f2f66696c65732f72616e636865722f33636137356131636166623838626562373737353033376136666162643661302d323032322d31312d30325f31362d34332d32382e706e67)

checked 2.7.0 rc8, rc9 and head

**Comment by nwmac** [comment]
@ronhorton Those are still valid - but Multi-cluster-apps was renamed to 'Global Configuration', but not changed in the getting started document - fixed now via new PR

**Comment by ronhorton** [comment]
**Pass** Verified in `2.7-head commit id 08bf3fe`
1. login
2. home > get started
![2022-11-07_16-34-11.png](https://zube.io/files/rancher/8675f71b0e960a2d475e0dd392e5a28a-2022-11-07_16-34-11.png)
`multi-cluster apps verbiage replaced with Global Configuration`
