### ISSUE TITLE
"Edit/Clone as yaml" for secrets, configmaps and other objects displays managedFields, fieldsType

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#709]
Version: v2.4-head, master-head

Steps:
1.  Create a config map , secret or any object in the Dashboard UI
2. Click on "edit as yaml"/ "clone as yaml" for any of the objects. 

The yaml displayed has managedFields, fieldsType, 'f:data' with flower braces. 
Are these fields correct ? These fields should not be present. They were not present in the previous version of dashboard UI

```
apiVersion: v1
data:
  k1: v1
kind: ConfigMap
metadata:
  creationTimestamp: '2020-05-29T16:31:05Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:k1': {}
      manager: agent
      operation: Update
      time: '2020-05-29T16:31:05Z'
  name: test1
  namespace: default
  resourceVersion: '101789'
  selfLink: /api/v1/namespaces/default/configmaps/test1
  uid: e4c10e76-033d-43d9-a862-5cf1c1e5ba29


```

**Comment by vincent99** [comment]
The edit page shows the full YAML straight from the k8s API, those fields are part of the resource.  They're "new" in k8s 1.18 and are involved in [server-side apply](https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply).  We can do something like fold the `managedFields` key by default in the YAML editor, because I agree they're distracting.  But they shouldn't be entirely hidden or deleted from the data being sent back on save.

**Comment by soumyalj** [comment]
@vincent99 : Should we expect the "managedFields" key to be folded/collapsed in this fix ? I don't see that in the edit view. 
```
apiVersion: v1
data:
  key2: val2
kind: ConfigMap
metadata:
  annotations:
    cattle.io/description: ""
  creationTimestamp: "2020-06-09T00:10:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:key2: {}
      f:metadata:
        f:annotations:
          .: {}
          f:cattle.io/description: {}
    manager: agent
    operation: Update
    time: "2020-06-09T00:15:38Z"
  name: test1
  namespace: default
  resourceVersion: "2180"
  selfLink: /api/v1/namespaces/default/configmaps/test1
  uid: 6f9f4c25-f501-439e-a28d-80814a656565


```

**Comment by soumyalj** [comment]
Validated with master-head and v2.4-head(CATTLE_DASHBOARD_INDEX pointing to https://releases.rancher.com/dashboard/latest/index.html) 

Steps:
1. Create a config map , secret or any object in the Dashboard UI
2. Click on "edit as yaml"/ "clone as yaml" .

The yaml displayed has managedFields folded/collapsed as below:
![Screen Shot 2020-06-08 at 6 27 08 PM](https://user-images.githubusercontent.com/18536626/84096041-b4759180-a9b5-11ea-89bd-8e31c121ab3d.png)

![Screen Shot 2020-06-08 at 6 26 39 PM](https://user-images.githubusercontent.com/18536626/84096058-bc353600-a9b5-11ea-9448-7cc0d3a80089.png)


Verified that edit as yaml, clone as yaml and create as yaml are functional for clonfig maps and all 3 types of secrets(opaque, registry, certificate). 
[Create from yaml without the managedFields key also works. When we edit the yaml, manageFields will be displayed]
