### ISSUE TITLE
Unable to view or assign Pod labels or annotations in Edit context

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7094]
**Setup**
- Rancher version: 2.6.x
- Browser type & version:

**Describe the bug**
- Pod labels and annotations aren't visible or editable via the pod edit page
  - ![image](https://user-images.githubusercontent.com/18697775/194119298-57fb58fd-2857-4e18-b660-9ccca95270c3.png)
- Note - Pod labels and annotations are visible as expected by the pod detail mast head
  - ![image](https://user-images.githubusercontent.com/18697775/194119383-de6a914b-ac8c-4097-a17a-e77557a7572c.png)

**To Reproduce**
1. Navigate to a Pod detail page and ensure it has some labels in the masthead (if not apply some via yaml)
2. Navigate to the `Config` view for the Pod and then the `Pod` --> `Labels & Annotations` tabs. Note the missing labels
3. Navigate to the Edit page for the Pod and attempt to assign some labels. Note that the Save action completes
4. Navigate to the Pod details page and the masthead does not contain the new label

**Result**

**Expected Result**
- Edit page should show and allow edit of both types

**Additional context**
- I've reproduced this from https://github.com/rancher/dashboard/pull/7093
- I tested Deployment (and pod) labels and they worked fine

**Comment by Josh-Diamond** [comment]
TIcket #7094 - Test Results - ✅ 
---

With Docker on a single-node instance:

Reproduced on rancher `v2.6.9-rc3`:
1. Fresh install of rancher `v2.6.9-rc3`
2. Provision a downstream cluster - [ AWS Node driver k3s w/ k8s `1.24.4+k3s1` ]
3. Once `Active`, Deploy a workload, with at least one annotation and one label added to pod
4. Once `Active`, From Pod Detail page, observe annotation is added
5. Verified - Annotation successfully added
6. `Edit YAML` of pod, and observe both annotation and label accurately configured
7. Verified - YAMLs accurately represent pod label + pod annotation added
8. `Edit Config` of pod, and observe label + annotation, accurately configured
9. Reproduced - Pod label + pod annotation missing from `Edit Config`

Screenshots:

`Step 5`
<img width="1123" alt="annotaion-confirmation-pod-detail" src="https://user-images.githubusercontent.com/46494969/197265198-b641e0af-d25e-4f21-b4ae-898b004339d5.png">

`Step 6 - Pod Annotation YAML`
<img width="252" alt="annotation-yaml" src="https://user-images.githubusercontent.com/46494969/197265245-20c16b6b-ab01-43fa-be25-c78e53142989.png">

`Step 6 - Pod Label YAML`
<img width="142" alt="label-yaml" src="https://user-images.githubusercontent.com/46494969/197265298-3a3514f2-23ce-4f68-b6e6-5413082fc961.png">

`Step 9 - Edit Config of Pod > Labels + Annotations`
<img width="1120" alt="pod-edit-config-reproduced" src="https://user-images.githubusercontent.com/46494969/197265378-c33714f7-af54-494e-8e48-bf2c2b7799ee.png">

---

Verified on rancher `v2.7-d8334c8184c93baad8c73834186972d8e26c973b-head`:
1. From reproduction env above, upgrade rancher to `v2.7-head`
2. Post-upgrade, Navigate to `Pod Details > Labels + Annotations`
3. Verified - Pod Label + Pod Annotation successfully configured
4. `Edit Config` of Pod and observe label + annotation successfully configured
5. Verified - Pod Label + Pod Annotation successfully configured + accurately displayed
6. Edit the annotation and label on the pod, then `Save`
7. Verified - Pod Annotation + Pod Label successfully and accurately updated
8. Deploy a new workload w/ Pod label + Pod annotation added
9. Verified - Pod label + Pod annotation successfully configured + accurately editable

Screenshots:

`Step 3`
![pod-config-validated](https://user-images.githubusercontent.com/46494969/197266544-9157c7d2-c287-4576-9789-81e2baa3711b.png)

`Step 5`
<img width="1114" alt="pod-edit-config-validate" src="https://user-images.githubusercontent.com/46494969/197266590-d6f4fa76-b719-41cd-b67f-d1bee443268d.png">

`Step 7`
![successfully-updated-annotation-label](https://user-images.githubusercontent.com/46494969/197266756-fb99b38c-7c83-4c11-a95e-19128420053c.png)
