### ISSUE TITLE
Cluster dashboard overview page crashes for standard user

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7096]
Seen in v2.6-head:

1. As an admin, provision a downstream RKE2 cluster
2. Create a standard user
3. Add the user to the default project of the downstream cluster. The bug is reproducible if the user has project owner or project member permissions.
4. Log in as the standard user
5. Navigate to cluster explorer
6. Rancher crashes
<img width="1611" alt="Screen Shot 2022-10-05 at 4 43 16 PM" src="https://user-images.githubusercontent.com/20599230/194183496-88a1818a-aaa0-4da7-9171-824b37763da4.png">

**Comment by richard-cox** [comment]
I've tried to reproduce this with the latest `2.7-head` backend, latest `release-2.6.9` ui running locally and a brand new rke2 cluster.

On the cluster's dashboard page i couldn't see any network requests made for the `policy.podsecuritypolicy` resource and in code there's nowhere we explicitly request that resource (`policy.podsecuritypolicy` / `policy.podsecuritypolicies`). I wondered if it was a custom event that might fetch it, but the event table and model don't look like they include anything outside of the event resource.

The resources definitely exist and aren't available to the standard user. As an admin i can go to c/c-m-vsvx4lfv/explorer/policy.podsecuritypolicy. Going to the same url as the standard user correctly sends the user to the fail-whale page.

@catherineluse Was there anything other special about the upstream/downstream clusters? apps installed, auth providers, etc?


![image](https://user-images.githubusercontent.com/18697775/194290272-6ce7b392-b938-4594-9566-9266c5782106.png)

![image](https://user-images.githubusercontent.com/18697775/194290421-47043eb5-9355-4dc7-a94a-a55bbb00bf47.png)

**Comment by dasarinaidu** [comment]
I have validated this issue on **v2.7-9f1e0435bb45e104ba897c5c329e1f23735843d9-head**

I did not see a crash with standard user login.

Below Test Cases were executed as part of the validations:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/sdasari/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/sdasari/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Precondition: |   |   |   |  
-- | -- | -- | -- | --
Log in as an   Admin and create a RKE2 cluster |   |   |  
Test   Scenario | Test Cases | Check point | Status | Callouts
Standard User | 1.   Login with Admin     2. Add Standard user as a Owner to the cluster     3. Login with Standard user | Check for the cluster   explored and details | Pass |  
  | 1.   Login with Admin     2. Add Standard user as a Member to the cluster     3. Login with Standard user | Check for the cluster   explored and details | Pass |  
  | 1.   Login with Admin     2. Add Standard user as a Custom member to the cluster     3. Login with Standard user | Check for the cluster   explored and details | Pass |  
User-base | 1.   Login with Admin     2. Add User-base user as a Owner to the cluster     3. Login with User-base  user | Check for the cluster   explored and details | Pass |  
  | 1.   Login with Admin     2. Add User-base user as a Owner to the cluster     3. Login with User-base  user | Check for the cluster   explored and details | Pass |  
  | 1.   Login with Admin     2. Add User-base user as a Owner to the cluster     3. Login with User-base  user | Check for the cluster   explored and details | Pass |  
  |   |   |   |  



</body>

</html>
