### ISSUE TITLE
Fail-whale page content is flush with header

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7099]
**Setup**
- Rancher version: 2.6.9

**Describe the bug**
- Looks like the page layout has changed and the content is now flush with the header

![image](https://user-images.githubusercontent.com/18697775/194283745-2a282f35-b793-4b80-ab3a-0083fc48daa7.png)

**To Reproduce**
- Navigate to any cluster's workloads list
- Request a bad resource by changing the `workload` text in the url to `junk`

**Expected Result**
There should be more space, ideally by centrally aligning content vertically

**Comment by Josh-Diamond** [comment]
Ticket #7099 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-ae44c398377516fcd150b8fc2a81a9fd6d4d8fb5-head`:

1. Fresh install of rancher `v2.7-head`
2. Navigate to `Cluster Explorer > Workloads` of local cluster and change `/workload` in URL to `/junk` and send request
3. Verified - Fail Whale screen shows up properly formatted; as expected

Screenshot:
<img width="1298" alt="Screenshot 2022-12-13 at 2 34 43 PM" src="https://user-images.githubusercontent.com/46494969/207449111-8df3cd3b-dd13-47b0-a4dd-ada59f0e82d2.png">
