### ISSUE TITLE
Update text on setup EULA checkbox

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7100]
Should read:

 'By checking the box, you accept the End User License Agreement & Terms & Conditions'

**Comment by jameson-mcghee** [comment]
I have verified that in the UI for `v2.7.0-rc8`, the text on the Rancher setup screen states _By checking the box, you accept the End User License Agreement & Terms & Conditions_ and the [End User License Agreement & Terms & Conditions](https://rancher.com/eula) link on the Home page will navigate the user to the Suse EULA Page correctly. Therefore I am closing this ticket as Done.

![image.png](https://zube.io/files/rancher/1c2d72453595aa562345f41c81447e49-image.png)
