### ISSUE TITLE
Add Project Member permissions card gradient border is clipped

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7101]
**Setup**
- Rancher version: 2.6.9

**Describe the bug**
Bottom border of permissions card is clipped

![image](https://user-images.githubusercontent.com/18697775/194293645-b571d777-d30a-4392-a3a2-229d5770d6be.png)

![image](https://user-images.githubusercontent.com/18697775/194293804-318ce9d8-30f2-42b8-9cde-02d42982a027.png)

**To Reproduce**
- Edit a project
- Add Membmer

**Comment by nwmac** [comment]
Should just remove the box shadow and use a single line of color var(—border)

**Comment by richard-cox** [comment]
Re-opening for QA

**Comment by dasarinaidu** [comment]
Reproduced this issue on `v2.6.7`

**Steps to Reproduce:**

1. Provision rancher HA / Docker (v2.6.7)
2. Create a cluster RKE1
3. Create a Project (While creating project try to add a Member)
4. Check for the 'Add Project Member' dialog box & gradient boarder 

**Actual:**
The gradient boarder is clipped and not visible properly

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/22034884/205751018-11d10ae5-364c-43c0-8383-7df62da79b04.png">

**Comment by dasarinaidu** [comment]
Validated this issue on `v2.7-60ab459ac61cae96dfc3145e70e5d3afb9fdf7c8-head'`

All the below test cases were passed and closing the ticket.

**Test Cases:**
1. Rancher HA & Docker installed
2. Browsers : Chrome & Firefox
3. Clusters : RKE1 and RKE2
4. Modes : Light and Dark
5. Create and Edit project
6. Login with Admin and Standard user


**Steps to Reproduce:**
2. Provision rancher HA / Docker (v2.6.7)
3. Create a cluster RKE1
4. Create a Project (While creating project try to add a Member)
8. Check for the 'Add Project Member' dialog box & gradient boarder display at the bottom

<img width="594" alt="image" src="https://user-images.githubusercontent.com/22034884/205754541-185e587b-b10f-4ca6-9ff3-9d77c93bb054.png">
