### ISSUE TITLE
Create Cloud Credentials: Pressing enter navigates to Select Existing instead of submitting form

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#7112]
**Setup**
- Rancher version: 78c7ac0 (latest build from master at time of writing)
- Browser type & version: Firefox 106.0b8

**Describe the bug**

Pressing enter on the Create Cloud Credentials page navigates to Select Existing instead of submitting the form.

**To Reproduce**

1. Navigate to Clusters => Create
2. Toggle RKE2/K3s so that it's on
3. Select Digital Ocean
4. Enter a Credential Name and an Access Token
5. Press Enter to submit the form

**Result**

The page for selecting existing credentials is shown.

**Expected Result**

I expect the cloud credential to be created and to navigate to the cluster creation form. 

**Additional context**

The Continue button is the primary action on this form and I expect this to be action that will be taken when pressing enter. Select Existing is secondary and I would expect that I would need to select this option in order to use it.

**Comment by slickwarren** [comment]
seeing this on v2.6.9-rc3 as well with any provider (linode, aws, etc.)

**Comment by nwmac** [comment]
Note: this is the case when you have no cloud credentials - when you hit create, you are taken to the screen to create a new credential - pressing 'continue' goes to the list and does not continue with cluster creation.

**Comment by slickwarren** [comment]
tested on v2.7-head (d1249b5):
* create cloud credential from cluster -> create page -- pass (keyboard `enter` seems to be disabled)
* create cloud credential from cloud credential -> create page -- pass (keyboard `enter` seems to be disabled)
