### ISSUE TITLE
[backport v2.6.9] NetworkPolicy PolicyRules checkbox and buttons overlap

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#7115]
backport of issue: https://github.com/rancher/dashboard/issues/7106

**Describe the bug**

Create/edit of a NetworkPolicy the PolicyRules component overlaps the checkbox to add ingress or egress rules.

**To Reproduce**

- Navigate to a cluster Network Policy (`/c/local/explorer/networking.k8s.io.networkpolicy/create#ingress`)
- Toggle the checkbox

**Result**

Buttons overlap the checkbox

**Expected Result**

Buttons are below the checkbox.

**Screenshots**

https://user-images.githubusercontent.com/5009481/194338992-d7774825-8663-4355-898a-d49b5e89afce.mp4

**Additional context**

Possible fix (thanks @kwwii ) is to remove negative margin (`margin: -20px;`) from [`Tabbed` component](https://github.com/rancher/dashboard/blob/master/shell/components/Tabbed/index.vue)

Issue seems introduced with https://github.com/rancher/dashboard/issues/5734 with the topic https://github.com/rancher/dashboard/pull/6214

**Comment by cnotv** [comment]
This has been already fixed and solved with https://github.com/rancher/dashboard/pull/7108 which is already on 2.7.0

It however highlighted another issue in https://github.com/rancher/dashboard/issues/7124

**Comment by slickwarren** [comment]
tested on v2.6-head (3c52f71): 
now there is no overlap on the networkPolicy screen
<img width="697" alt="Screen Shot 2022-10-14 at 11 37 19 AM" src="https://user-images.githubusercontent.com/16691014/195917483-55f47b71-ae62-420d-a323-db3730d9f410.png">
