### ISSUE TITLE
Browse/Featured toggle on the Charts page

### ISSUE THREAD

**Issue by bisht-richa** [rancher/dashboard#7121]
**Describe the bug**

On the Charts page, the `Browse/Featured` toggle buttons should not be shown if there is no carousel

**Expected Result**

Show `Browse/Featured` toggle buttons only when there is carousel

**Screenshots**

![image](https://user-images.githubusercontent.com/18264463/194586087-a3f9ad6d-0fda-4473-838a-552351616504.png)

**Comment by ronhorton** [comment]
**Pass** Verified in `2.7.0-rc6`
1. charts repo has no featured charts - no featured toggle on charts page
2. added repo with featured charts
3. featured toggle and feature charts carousel appear at top of charts page
