### ISSUE TITLE
Cannot create harvester rke2/k3s cluster through rancher `https://<rancher_url>/k8s/clusters/<cluster_id>/v1/harvester/kubeconfig` 400 error

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#7125]
**Setup**
- Rancher version: v2.6-head (78c7ac0)
- Harvester Version: v1.1.0-rc2
- Browser type & version: chrome

**Describe the bug**

when deploying an rke2 harvester cluster, clicking the `creating` button infinitely spins. Checking the console has a 400 error for `https://<rancher_url>/k8s/clusters/<cluster_id>/v1/harvester/kubeconfig` 400 error

**To Reproduce**

* connect a harvester instance to rancher through virtualization management
* create an rke2 harvester node driver cluster through rancher using the harvester instance you've just connected to rancher
  * configure the cluster with default settings and wait for the cluster to get past the `create` stage

**Result**
cluster never creates and has a 400 error in the console logs

**Expected Result**

cluster should start to create

**Screenshots**

hangs here indefinitely
![Screen Shot 2022-10-07 at 11 31 54 AM](https://user-images.githubusercontent.com/16691014/194625827-da586cdf-99e2-4ef6-8f29-e8ed3875db67.png)

**additional context** 
rke1 is able to provision just fine.

**Comment by slickwarren** [comment]
x-posted in harvester: https://github.com/harvester/harvester/issues/2889

**Comment by richard-cox** [comment]
Harvester provisioning hasn't been moved out to it's own plugin yet, so that work probably hasn't affected this.

When creating the RKE2 cluster there's an additional POST made to `/k8s/clusters/${ clusterId }/v1/harvester/kubeconfig` which it looks like is failing. 

This needs to be validated with the Harvester team

**Comment by guangbochen** [comment]
This is a Harvester issue and has been fixed via https://github.com/harvester/harvester/issues/2889#issuecomment-1272472713, thanks.

**Comment by richard-cox** [comment]
I was going to close this, but there's some error handling that's been added that it would be good to validate 
- 2.6.9 - https://github.com/rancher/dashboard/pull/7128
- 2.7.0 - https://github.com/rancher/dashboard/pull/7129

**Comment by slickwarren** [comment]
tested on v2.6-head (78c7ac0):
when provisioning a harvester node driver cluster, if the kubeconfig from the harvester management cluster is not reachable, rancher should propagate that error up to the user in the ui - pass

other issues will be tested on harvester's end in the linked tickets above
