### ISSUE TITLE
Update docs link

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7144]
Base link is currently https://rancher.com/docs/rancher/v2.6/en

**Comment by gaktive** [comment]
@gaktive to sync with @gunamata about what the expected 2.7.x structure in the new docs page.

**Comment by gunamata** [comment]
`https://rancher.com/docs/rancher/v2.6/en` is the old docs link which redirects to `https://docs.ranchermanager.rancher.io/` . With the new docs portal, the latest version is served at `https://docs.ranchermanager.rancher.io/` and the previous versions are served at `https://docs.ranchermanager.rancher.io/<version-number>`. And you can switch between versions using the drop down in the top nav bar.

![image](https://user-images.githubusercontent.com/59538726/195256462-63716ddc-6774-4f67-8f81-5ea4ef08ebbe.png)

**Comment by gaktive** [comment]
So to confirm, the new base URL for 2.7.x will be https://docs.ranchermanager.rancher.io/2.7 -- if so, when will 2.7 docs go live? I suspect QA will have tests built around checking docs links in the UI.

cc: @nwmac

**Comment by nwmac** [comment]
The links we use are (relative to the docs base):

- admin-settings/authentication/google/#3-creating-service-account-credentials
- monitoring-alerting/configuration/#alertmanager-configuration/
- /cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/
- monitoring-alerting/
- monitoring-alerting/guides/migrating/
- faq/telemetry/
- monitoring-alerting/guides/migrating/
- logging/migrating/
- istio/#migrate-from-previous-istio-version

**Comment by gunamata** [comment]
> So to confirm, the new base URL for 2.7.x will be https://docs.ranchermanager.rancher.io/2.7 -- if so, when will 2.7 docs go live? I suspect QA will have tests built around checking docs links in the UI.

The current practice is to release docs around the same time as the product release. To enable QA or other teams try out docs prior to the prod release, we need to make some adjustments to the current Docusaurus implementation. @btat  has some ideas that he will try next week and let you all know here..

Plus, the relative paths shared by Neil need some adjustments to align with the latest docs structure. @btat or @jtravee will share the new paths soon.

**Comment by gaktive** [comment]
@btat, the easiest thing for UI would be having redirects for the links that @nwmac found. We're at code freeze for 2.7.0 tomorrow and we'd like to reduce the churn for QA to test.

**Comment by btat** [comment]
After some testing, Docusaurus currently has [a limitation](https://github.com/facebook/docusaurus/issues/6845) where the hash portion of the link is not taken into consideration during a redirect.

As a workaround, [redirects have been added](https://github.com/rancher/docs/pull/4339/files) to the old Hugo docs site instead.

Base link would be https://rancher.com/docs/rancher/v2.7/en and the relative paths @nwmac listed are unchanged. They'll redirect to the new site at the restructured paths.

**Comment by nwmac** [comment]
Ember UI docs links:

Base is: `https://rancher.com/docs/rancher/v2.6/en`

https://rancher.com/docs/rancher/v2.6/en/tools/pipelines/configurations/#1-configuring-version-control-providers
https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/google/
https://rancher.com/docs/rancher/v2.6/en/faq/deprecated-features-25x
https://rancher.com/docs/rancher/v2.6/en/tools/pipelines/configurations/#1-configuring-version-control-providers
https://rancher.com/docs/rancher/v2.6/en/security/security-scan/#profiles
https://rancher.com/docs/rancher/v2.6/en/cluster-admin/tools/monitoring/#resource-consumption
https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/cloud-providers/vsphere/out-of-tree
https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/hosted-kubernetes-clusters/aks/
https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/hosted-kubernetes-clusters/gke/
https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/
https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/options/#authorized-cluster-endpoint
https://rancher.com/docs/rancher/v2.6/en/cluster-admin/volumes-and-storage
https://rancher.com/docs/rancher/v2.6/en/installing-rancher/installing-server/basic-ssl-config/

**Comment by gaktive** [comment]
@btat see the latest comment about other links that UI found on the older interface.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 6b4cf88
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 106

----------

### Testing: ###

Tested that the docs link is pointing to 2.7 for the 2.7 release and not the 2.6 link.

The docs link is pointing to 2.7 now as seen in the image below. @nwmac I was wondering if the `What's new in 2.6` will also be updated, if not I will submit a ticket for it.
![image.png](https://zube.io/files/rancher/5667b9474f9b514d9049310678bce1b1-image.png)

As mentioned by @nwmac the ember base will be changed automatically and will still be pointing to 2.6
![image.png](https://zube.io/files/rancher/eba609b3336282c9741a7ce89aa46dc8-image.png)

**Comment by btat** [comment]
> Ember UI docs links:
> 
> Base is: `https://rancher.com/docs/rancher/v2.6/en` - Ember UI automatically uses Rancher version in the base so does not need to be manually updated - i.e. we will need these links for the base `https://rancher.com/docs/rancher/v2.7/en`
> 
> Here are the links - some of these are currently broken.
> 
> https://rancher.com/docs/rancher/v2.6/en/tools/pipelines/configurations/#1-configuring-version-control-providers https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/google/ https://rancher.com/docs/rancher/v2.6/en/faq/deprecated-features-25x https://rancher.com/docs/rancher/v2.6/en/tools/pipelines/configurations/#1-configuring-version-control-providers https://rancher.com/docs/rancher/v2.6/en/security/security-scan/#profiles https://rancher.com/docs/rancher/v2.6/en/cluster-admin/tools/monitoring/#resource-consumption https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/cloud-providers/vsphere/out-of-tree https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/hosted-kubernetes-clusters/aks/ https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/hosted-kubernetes-clusters/gke/ https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/windows-clusters/ https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/options/#authorized-cluster-endpoint https://rancher.com/docs/rancher/v2.6/en/cluster-admin/volumes-and-storage https://rancher.com/docs/rancher/v2.6/en/installing-rancher/installing-server/basic-ssl-config/

Redirects for these are now live.
