### ISSUE TITLE
Resize Terminal Window crash

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#7148]
**Setup**
- Rancher version: 2.7-head (Commit ID: 64816445794216d22beb2edd84479b376f4be775)
- Browser type & version: Chrome, Chromium

**Describe the bug**

When Terminal Window is resized, there is a critical error. It's necessary to reload the window to continue.

**To Reproduce**

- Go to `local` cluster homepage.
- Click on 'Kubectl Sheel' to open the Terminal.
- Nav to a cluster --> `Apps` --> `Charts` --> Click on `Alerting Driver` card (or any other) --> `Install` --> `Next` --> `View Chart Info`
- Click on 'Dock to bottom' (the icon on the top-right of Chart Info page)
- You should have tabs 'Kubectl' and 'Alerting Drivers' open.
- Drag to up the Terminal Window by the resize button.

**Result**
Message error 'This API only accepts integers' is displayed.

Console output:

console.js:31 Error: This API only accepts integers
    at e._verifyIntegers (xterm.js:1:1)
    at e.resize (xterm.js:1:1)
    at e.fit (xterm-addon-fit.js:1:1)
    at VueComponent.fit (ContainerShell.vue:296:1)
    at VueComponent.height (ContainerShell.vue:96:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863:1)
    at Watcher.run (vue.runtime.esm.js:4584:1)
    at flushSchedulerQueue (vue.runtime.esm.js:4326:1)
    at Array.<anonymous> (vue.runtime.esm.js:1989:1)
    at flushCallbacks (vue.runtime.esm.js:1915:1)

**Expected Result**

Any error are expected.

**Screenshots**

![image](https://user-images.githubusercontent.com/26394656/195058945-0388264b-b650-4683-b488-0557542e92c7.png)

![chrome-capture-2022-9-11](https://user-images.githubusercontent.com/26394656/195058781-3d475ffc-a5b4-4547-aa9b-0493c86bf9cb.gif)

**Comment by richard-cox** [comment]
Note - That big 'white page' error only occurs in dev. For production builds the error will be swallowed

**Comment by jameson-mcghee** [comment]
During testing on `v2.7.0` I was able to reproduce the reported error when following the Steps to Reproduce. As was mentioned by @richard-cox the [error was swallowed](https://github.com/rancher/dashboard/issues/7148#issuecomment-1274463525), but it was visible in the console logs.
However, when testing on `v2.7-head` (Commit ID: dadb4c0), I did not observe the error when resizing the terminal window either up or down. Therefore I am closing this ticket.

**Steps to Reproduce:**
1. Go to local cluster homepage.
2. Click on 'Kubectl Sheel' to open the Terminal.
3. Nav to a cluster --> Apps --> Charts --> Click on Alerting Driver card (or any other) --> Install --> Next --> View Chart Info
4. Click on 'Dock to bottom' (the icon on the top-right of Chart Info page)
5. You should have tabs 'Kubectl' and 'Alerting Drivers' open.
6. Drag to up the Terminal Window by the resize button.

**`v2.7.0`:**
![image](https://user-images.githubusercontent.com/13294321/208149525-75ee5f1b-06f1-4f18-acfe-4ba4100ab96b.png)

**`v2.7-head` (Commit ID: dadb4c0):**
![image](https://user-images.githubusercontent.com/13294321/208149556-a30f392c-b7b8-4616-aa3a-37c27e04d213.png)
