### ISSUE TITLE
Define automation to pair Rancher Docker version to Rancher Dashboard

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#7149]
# Description

Define a way to automatically keep track of the current Rancher version to be used also in the Rancher Dashboard. 
Ideally by updating the `package.json` with the current version, but would be however required to check if the strict pairing may create issues in some cases.

Examples of version references: e2e, changelog in the home, Digital Ocean updates

**Comment by jordojordo** [comment]
Closing this as discussed outside of the issue.

**Comment by cnotv** [comment]
For the records: as the change affecting the logic is related to minor versions, with yearly occurrence, an automation resulted over engineered.
