### ISSUE TITLE
Create Cluster(RKE)->Member Roles->Custom->Add Member-> Select Roles -> System is throwing exception after save

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/dashboard#7159]
**Setup**
- Rancher version: v2.5.16, v2.6.8 & v2.7-head
- Browser type & version: chrome

**Describe the bug**
Create Cluster(RKE)->Member Roles->Custom->Add Member-> Select Roles -> System is throwing exception after click on save and user is on same page

Error on UI screen:
You must choose a role for this member before closing the modal.

**Pre-Condition:** Login as a Standard User

**To Reproduce**

1. Login as a Standard User
2. Create a downstream cluster (RKE) in AWS from rancher
3. While creating cluster select Member Roles->Custom->Add Member->Select Roles
4. Save Roles and check for the Error on the selection page

**Actual Result**
1.System is throwing an Error on UI
2. Error on UI screen:
You must choose a role for this member before closing the modal.
3. No network call called on save
5. No issues while creating a  RKE2 cluster with a custom role assignment

Note: Happening this issue on v2.5.16, v2.6.8 & v2.7-head

**Expected Result**

**Screenshots**
![image](https://user-images.githubusercontent.com/22034884/195156899-b8ad4c15-4cfe-4d18-8c61-daad3e356445.png)

**Additional context**
Note: Happening this issue on v2.5.16, v2.6.8 & v2.7-head

**Comment by nwmac** [comment]
@dasarinaidu I could not reproduce this - can you retry and add any missing steps.

**Comment by dasarinaidu** [comment]
@nwmac I am still seeing the issue and I have updated the steps. Please let me know if you need more details.

**Comment by dasarinaidu** [comment]
I have validated this issue on `v2.7-95edd0203b7c5f0159d09e368e6897a06c48ba77-head`. This issue got fixed and closing this card.

1. Validated on Chrome and Firefox
2. Admin and Standard user
3. RKE1 and RKE2 cluster creation
4. Dark and Auto modes
