### ISSUE TITLE
Azure node template tags

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7164]
Internal reference: SURE-2700

There's a request to add tags to the Rancher provisioned K8s clusters in Azure. Based on the docs (https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_template) it's supported for vSphere, AWS, Linode, DigitalOcean but not for the Azure. Specific to the request is to have this added to the Rancher2 Terraform provider.

For the UI, the proposal:
- Similar UI elements for adding tags to AWS and DO instances should be implemented to achieve feature parity.
-- Extra field in the node-template for RKE1
-- Extra field under Advanced Options for RKE2
- UI would make the same API call for tagging resources as it does for AWS and DO

Corresponding backend work: https://github.com/rancher/rancher/issues/26955
Possible earlier feature request to make RKE1 and RKE2 visuals around Azure for the better: 
- Github - rancher/dashboard#3938 
- [Zube - #3945 (rancher/dashboard#3938)](https://zube.io/rancher/dashboard-ui/c/3945) 

Screenshot of the AWS usage (from the older Ember UI):

![81221100-5fa6bb80-8fb0-11ea-81a3-7251a1c5c82e.png](https://zube.io/files/rancher/96efc328bd84a8c3b11e61641c25f538-81221100-5fa6bb80-8fb0-11ea-81a3-7251a1c5c82e.png)

**Comment by catherineluse** [comment]
I created two PRs to add the tags:

- RKE1 node templates: https://github.com/rancher/ui/pull/4910
- RKE2/K3s machine pools: https://github.com/rancher/dashboard/pull/7296

I'm moving this issue into the backend blocked category not because there's a problem, but because if a reviewer pulled down my changes and ran them locally, they wouldn't be able to visually confirm that the tags are being saved on the backend. So I'd like to wait to send them to review/QA until the backend work is done: https://github.com/rancher/rancher/issues/26955

**Comment by catherineluse** [comment]
This issue can be fully tested after this Rancher Machine PR is merged https://github.com/rancher/machine/pull/198

**Comment by HarrisonWAffel** [comment]
The Rancher Machine PR mentioned above has been merged and the version of Rancher Machine in Rancher has been bumped to the latest tag

**Comment by gaktive** [comment]
Backend complete, so they're awaiting UI before handing to QA: https://github.com/rancher/rancher/issues/26955 though they will await for all related Azure AD tickets to be completed before testing begins.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head ea6b86c
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE1 and RKE2 azure node driver clusters

----------

### Testing: ###

Tested this issue with the following cases:
1. Create rke1 cluster with Azure tags in the node template
2. Create rke2 cluster with Azure tags in the machine pool configuration

**Result**
RKE1 now has a `Add Azure Tags` button in the node template instance section
![image.png](https://zube.io/files/rancher/1e69c654346a623a729ad35f2f08fb5f-image.png)
The cluster was successfully created and the tags were also applied successfully
![image.png](https://zube.io/files/rancher/71bc1dd8ae5ea6e4da24850a64c38c7d-image.png)


RKE2 now has a `Tags` section under the advanced options section in the machine pools section
![image.png](https://zube.io/files/rancher/e584b8b30b636766ba47f64c1dde0f93-image.png)
The cluster was successfully created and the tags were also applied successfully
![image.png](https://zube.io/files/rancher/1d78e760e28b97f550f698c5362689d3-image.png)
