### ISSUE TITLE
Creating a Deployment defaults to "Allow Privilege Escalation"

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7165]
Internal reference: SURE-3663

Request description:
When users create Deployments in the Rancher Cluster Explorer UI, the setting under "Security Context" -> "Privilege Escalation" defaults to _"Yes, container can gain more privileges than its parent process"_

Users will fail to create deployments by default (at least when e.g. setting the _"Run as User ID"_ field). The security context parameter is not added to the deployment unless one parameter is set, however when some parameter is set the Privilege Escalation option is set to yes by default.

This could be considered a more secure means of running Kubernetes, which would help with RKE2 strategy to align with other usage within the product.

Actual behavior:
Privilege Escalation in the security context tab is set to `yes` by default

Expected behavior:

Privilege Escalation in the security context tab is set to `no` by default

Additional notes:
Instead of choosing between one default or another, it would be helpful to have a way to select the default config options in the UI for each user.

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: c35f112`

The `Privilege Escalation` field is now defaulted to the `No` option.

![image](https://user-images.githubusercontent.com/107147272/206037935-72826e0d-ee70-4f16-b4f4-dc71f96317ea.png)
