### ISSUE TITLE
Service Page - Show Live Targeted Pods Count for Selectors

### ISSUE THREAD

**Issue by westlywright** [rancher/dashboard#717]
On the create service page as a user fills out the selector info it would be nice to see a live updating number of pods that will be captured by this selector as mentioned [here](https://github.com/rancher/dashboard/issues/583#issuecomment-630593656)

On the detail page the same component should be added as mentioned [here](https://github.com/rancher/dashboard/issues/632#issuecomment-632365025)

Both of these should be delayed until the API mentioned [here](https://github.com/rancher/dashboard/issues/714) is created.

**Comment by deniseschannon** [comment]
Seems like it might be ready based on this: https://github.com/rancher/rancher/issues/27487

**Comment by westlywright** [comment]
> On the create service page as a user fills out the selector info it would be nice to see a live updating number of pods that will be captured by this selector as mentioned here

@vincent99 I'm not sure there is a performant way to do this currently? The new api feature that was added that lets us fetch related resources works because its a real resource and the relationships are tied up on the backend. But AFAICT for this to work we'd need filters on the pods call. Otherwise we have to load all the pods up front and search/return as the user fills out selectors and I thought we were trying to avoid the `load all up front` requirements.

> On the detail page the same component should be added as mentioned here
This is being added via another ticket with the Service Details page.

**Comment by vincent99** [comment]
Yes you'd have to load all the pods and use `utils/selector.js`'s `matching(ary, selector)`.  We do want to avoid loading all the things all the time but if it's something specific for a good reason it's ok and I think this is a pretty useful thing to see what the selector is selecting.  You'll probably want to update the matches async/throttled so it's not blocking the UI if there's a million pods..

Cluster Groups does a similar thing where it shows how many clusters you're selecting in various colors depending on if you're selecting some of the clusters (probably good) or none/all of them (probably bad).

**Comment by sadiapoddar** [comment]
Verified the fix on v2.5.-head, commit id 24c32a3
1. Created various kind of services
2. Verified each service create page and detail page of that service
3. Created a few same service type with the same selector key=value 

<img width="1188" alt="Screen Shot 2021-01-27 at 9 38 33 PM" src="https://user-images.githubusercontent.com/72409237/106095307-6f3ed500-60e8-11eb-871d-6f7c654ad718.png">

But not seeing the fix that the selector displays the pod counts of the same selector type
<img width="492" alt="Screen Shot 2021-01-27 at 9 42 53 PM" src="https://user-images.githubusercontent.com/72409237/106095593-e5dbd280-60e8-11eb-8aec-bef255d87629.png">


@westlywright  reopening the bug for your clarification about the selector and pod count display

**Comment by nwmac** [comment]
@sadiapoddar The selectors tab shows the key/value selectors for the service, not the pods or pod counts - this should be shown on the pods tab - can you verify this

**Comment by slickwarren** [comment]
on 2.5-head (b4be2b2) here is an example list of pods when viewing services:
<img width="1512" alt="Screen Shot 2021-02-22 at 12 57 18 PM" src="https://user-images.githubusercontent.com/16691014/108770970-d5641f80-750f-11eb-9437-3854c194f1bf.png">

Test 1: a single key-value pair updates count when creating a deployment/service:
<img width="723" alt="Screen Shot 2021-02-22 at 1 10 53 PM" src="https://user-images.githubusercontent.com/16691014/108771083-fb89bf80-750f-11eb-9ad0-4802d756d52d.png">
<img width="805" alt="Screen Shot 2021-02-22 at 1 10 21 PM" src="https://user-images.githubusercontent.com/16691014/108771125-0d6b6280-7510-11eb-84cb-c1b94340f6c6.png">


test 2: **FAIL** multiple of key/value pairs appears to break the count, and if created anyways, no pods will show up in the pod list:
<img width="715" alt="Screen Shot 2021-02-22 at 1 10 46 PM" src="https://user-images.githubusercontent.com/16691014/108771145-13614380-7510-11eb-98a8-97c4d2c1a802.png">

test 3: **FAIL** an edge case is, when editing a service's labels and a label already exists, the count is at 0:

<img width="930" alt="Screen Shot 2021-02-22 at 1 00 24 PM" src="https://user-images.githubusercontent.com/16691014/108771385-705cf980-7510-11eb-81b5-d7673560fa73.png">

changing the label/adding a new one to the page corrects the count for the first key-value:
<img width="914" alt="Screen Shot 2021-02-22 at 1 04 03 PM" src="https://user-images.githubusercontent.com/16691014/108771312-558a8500-7510-11eb-9a77-8fc85596ddcf.png">

**Comment by westlywright** [comment]
@slickwarren As we talked about offline I believe `Test 2` is actually a pass. Selectors are AND'd together, not OR'd. Can we update that as a PASS?

I'll have a new PR open for the case in test 3 shortly.

**Comment by slickwarren** [comment]
checked on 2.5-head (a85f4d1) and master-head (67126b3), all tests passed from above. Also tested:
* Deleting pods with label (count should decrease) -- PASS
* adding pods with label (count should increase) -- PASS
* same selector label across different services (count should be the same) -- PASS
