### ISSUE TITLE
Can't run `yarn install`, @rancher/shell 0.1.4 not published to npm

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#7192]
It's currently not possible to run `yarn install` against `main`. It looks like `@rancher/shell 0.1.4` hasn't been published to npm

* https://www.npmjs.com/package/@rancher/shell
* https://github.com/rancher/ui-plugin-examples/blob/main/package.json

`yarn.lock` also looks to be resolving to a private registry

https://github.com/rancher/ui-plugin-examples/blob/0be281b6a45f4e95c72730c198af2d9b3bd5aa63/yarn.lock#L2928-L2931

**Comment by nwmac** [comment]
Thanks @rak-phillip - will publish

**Comment by nwmac** [comment]
@rak-phillip I think that has been resolved?

**Comment by rak-phillip** [comment]
Yes, I can confirm that `@rancher/shell 0.1.4` has been published to npm and that the lockfile resolves to `https://registry.yarnpkg.com` instead of a local registry.
