### ISSUE TITLE
[RFE] ability to create project-scoped registry secrets as in 2.5.x

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7195]
Internal reference: SURE-3802
Reported in 2.6.2

Issue description:

Project-scoped registry secrets(that propagate to all namespaces in a project) can't be created in the 2.6 UI, only namespace-scoped secrets

Workaround:
The `/g/` interface (the older Ember UI) still allows project-scoped registry secrets

Additional notes:
We have this as a legacy feature flag:
- When exploring a cluster, go to Legacy -> Project - then select a project from the dropdown -> Secrets -> Registry Credentials. 
So the ask is to bring this back into the product.

Past efforts in 2.6.x:
- https://github.com/rancher/dashboard/issues/5084
- https://github.com/rancher/dashboard/issues/4976

**Comment by kwwii** [comment]
The suggested UI is also requested in this issue: https://github.com/rancher/dashboard/issues/6322

**Comment by gaktive** [comment]
@aalves08 since Slack threads aren't always accessible or futureproof for those within this repo :) to summarize, the thread gets into the idea of the roadmap of project as a scope. @nwmac can confirm with @leflambeur about the plan, then this can be passed on to @cbron so we know where we're heading.

**Comment by gaktive** [comment]
Pushing out as we await discussion about the public API.

**Comment by gaktive** [comment]
Need to sync with Neo about the current API plans and how this ties into that. Hierarchical Namespaces may supplant this.

**Comment by nwmac** [comment]
Won't fix
