### ISSUE TITLE
Errors produced when navigating away from a page while a table is loading

### ISSUE THREAD

**Issue by moio** [rancher/dashboard#7201]
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Electron (Cypress)

**Describe the bug**
I have been developing Cypress-based end-to-end tests, which tend to click around faster than normal users.

When navigating away from a page which has a table, if the table is not done loading at click time, Javascript errors will be produced thereby failing the test.

**To Reproduce**
Ideally, [follow reproduction instructions](https://github.com/moio/scalability-tests/blob/20221003_300_pods_per_node/docs/20221003%20-%20300%20pods%20per%20node.md#reproduction-instructions) to get to the exact same environment I used (in AWS via Terraform).

At that point comment code in https://github.com/moio/scalability-tests/blob/20221003_300_pods_per_node/cypress/cypress/support/commands.js#L14-L15 and re-run the Cypress test.

**Comment by richard-cox** [comment]
@moio Please can you provide the console output including the errors, and also supply an issue title? At some point it would be worth migrating to the e2e framework the dashboard provides (which will be kept up to date with breaking changes)

**Comment by moio** [comment]
@richard-cox you are totally right. As it may take me some time before I get back to you with the exact error, I am closing this issue and will reopen it when I have better data - no need to clutter your issues list in the meantime.

I also take your suggestion to look into the dashboard e2e tests at some point.

Thanks
