### ISSUE TITLE
Unlabeled taggable select styling is poor

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#7204]
This is a port of an issue first reported in Harvester but which applies to Cluster Explorer too: https://github.com/harvester/dashboard/pull/450
The solution in the above PR breaks the display of some other dropdowns, e.g. the Apps and Marketplace provider dropdown. This issue is to track a fix that works in both places.

note: Taggable unlabeled selects are, from what I can see, rare: I only found them in logging flow create/edit, role create/edit, and generic cloud credentials

**Comment by ronhorton** [comment]
testing parameters are listed in the pr: https://github.com/harvester/dashboard/pull/450

**Comment by AndrewHoffmanQA** [comment]
testing passed on 2.7head 6316baf 

validated all locations listed in https://github.com/harvester/dashboard/pull/450

fields now appear to be displayed. in an improved stylistic manner. example picture- all pages checked on light and dark mode.
![image.png](https://zube.io/files/rancher/61d1106f10b3fca56c623d5739386f66-image.png)
