### ISSUE TITLE
Deprecation warning for v1 tools

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7210]
Internal reference: SURE-5303

Starting in 2.7.0, we need to start warning users that we will be deprecating the following:

- Apps & Catalog (Ember UI)
- Global DNS 

The removal won't happen until a later version but we need banners to ensure people are aware that these will disappear for 2.9.

**Comment by ronhorton** [comment]
@nwmac do you have some examples of what/where i'll find these deprecation warnings? i don't see any - example, expected to see one on catalog page, but no warnings
![2022-10-24_16-14-37.png](https://zube.io/files/rancher/9ba52bf8f5dd14b48a8893c7619188b2-2022-10-24_16-14-37.png)

**Comment by nwmac** [comment]
@ronhorton Strange - I see the banners on 2.7-head.

![image](https://user-images.githubusercontent.com/1955897/197754369-4a64b56f-774c-4f2d-b2f7-d1df6f30af50.png)

Banners should be seen on these pages:

- [Cluster] -> Tools-> Catalogs
- [Cluster] -> [Project] -> Tools-> Catalogs
- [Cluster] -> [Project] -> Apps
- Global -> Tools -> Global DNS Entries
- Global -> Tools -> Global DNS Providers
