### ISSUE TITLE
OKTA Login enabling failing with 404 page not found error

### ISSUE THREAD

**Issue by gobinathGH** [rancher/dashboard#7212]
tried to integrate our OKTA page with rancher v2.6.8 as per the document filled the URL as "https://rancherURL/v1-saml/okta/saml/acs" but the enabling page is failing with 404 not found error. 

we are in intial stage and without this we cant rollout to our developers for using the environment

**Comment by richard-cox** [comment]
Please can you retest with the latest version (as of writing 2.8.3) and re-open if still applicable. Please also double check https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-okta-saml
