### ISSUE TITLE
Missing namespace selector on continuous delivery page

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#7213]
Setup

Rancher version: v2.7.0-rc4 upgraded from v2.6.8
Browser type & version: Chrome

**Describe the bug**
When we navigate to continuous delivery page from cluster management page/home page, namespace selector present at the top right corner is missing . If we navigate to the continuous delivery page from cluster explorer page, the namespace selector is seen.

**To Reproduce**
1. Create a rancher server on v2.6-head or v2.7.0-rc4
2. From home page/cluster management page, navigate to continuous delivery page

**Result**
On the continuous delivery page, namespace selector dropdown is missing.

**Expected Result**
Expected the dropdown to be present

**Screenshots**

When navigated from cluster management page/home page:
<img width="500" alt="nonsselector" src="https://user-images.githubusercontent.com/38144301/196471631-af26143d-d939-44b6-8e6a-cd928b0a0d26.png">

When navigated from cluster explorer page:
<img width="500" alt="nsselector" src="https://user-images.githubusercontent.com/38144301/196471662-93347987-8d2d-472c-8776-24896f6b70a2.png">

**Additional context**

**Workaround**: Navigate to continuous delivery page from cluster explorer page.
Issue not seen on v2.6.5, v2.6.8
Issue is seen on v2.6-head, v2.7.0-rc4, v2.7-head
Do not see any errors in the console logs.

**Comment by gaktive** [comment]
@jtravee we'll need to release note this for 2.6.9 as we fix this for 2.7.0. Let me know if you need more details.

**Comment by richard-cox** [comment]
Reproduced in v2.6.9-rc6.

The Fleet Workspace filter will only show if the user visits Continues Integration from a Cluster Explorer page.

**Comment by anupama2501** [comment]
Verified on v2.7-head `9f1e043`


- Navigated to continuous delivery from cluster management, Users & authentication, cluster explorer, home page and verified the namespace selector shows up.
- Created a downstream rke1 and rke2 node driver clusters with 1 etcd + cp, 1 worker
- Changed the namespace to default and local and verified the clusters show up as per the selected namespace
