### ISSUE TITLE
Change AKS "experimental" label to apply to k8s 1.25+

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#7217]
k8s versions 1.24+ are marked as "experimental" in Rancher UI per the change done in https://github.com/rancher/dashboard/issues/6513

With AKS 1.24 tested and validated as working OK in Rancher, we don't want to have "experimental" label applied to 1.24 any longer.
However, 1.25 will be available in AKS sometime in October as Preview (and GA in December) per https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar. Since it's not yet validated, we want to have it marked as "experimental" once it becomes available in AKS. That's the rationale for setting `EXPERIMENTAL_RANGE = '>= 1.25.0'` and not simply removing the functionality outright.

**Comment by jtravee** [comment]
Adding known issue to the [2.6.9 release note PR](https://github.com/rancherlabs/release-notes/pull/274) per @snasovich.

**Comment by nwmac** [comment]
@snasovich We're past code freeze for 2.7

**Comment by snasovich** [comment]
@nwmac (cc: @gaktive ), 10-4.
Now, my understanding is that we have not cut final RC, so critical fixes can still go in. This is by no means a critical issue, however the fix is likely 1/2-line change. So if this is something that can be done in time for 2.7.0, that would be great.
If not, let's move it to 2.7.1 milestone.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|Setup fresh install of Rancher, attempt to provision an AKS cluster, validate that no listed K8s version shows as `experimental`|
|2|Setup `v2.6.9` Rancher, attempt to provision an AKS cluster, validate that K8s versions 1.24+ show as experimental, upgrade Rancher, attempt to provision an AKS cluster, validate that no listed K8s version shows as `experimental`|

**Comment by markusewalker** [comment]
Validated this against `v2.7-head`  https://github.com/rancher/rancher/commit/40932d62cdeb2f4594009436468c444c3378553d. Details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version:
     - Fresh install: `v2.7-head https://github.com/rancher/rancher/commit/40932d62cdeb2f4594009436468c444c3378553d`
     - Upgrade: `v2.6.9` -> `v2.7-head https://github.com/rancher/rancher/commit/9e7e4bc5bb4ac18ae801fba3c076f10039267052`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|Setup fresh install of Rancher, attempt to provision an AKS cluster, validate that no listed K8s version shows as `experimental`|:white_check_mark:|
|2|Setup `v2.6.9` Rancher, attempt to provision an AKS cluster, validate that K8s versions 1.24+ show as experimental, upgrade Rancher, attempt to provision an AKS cluster, validate that no listed K8s version shows as `experimental`|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigated to Cluster Management > Create > Azure AKS.
3. Attempted to provision a cluster and in the `Cluster Options` validated that no K8s version shows as experimental:
![image](https://user-images.githubusercontent.com/52591819/197618912-4eb124e2-1828-4b06-b73d-5d7c08fc2a17.png) 
___________
**Scenario 2**
1. Repeated steps 1-3, but ensured that on step 3, that K8s version 1.24+ showed as experimental.
2. Upgraded Rancher server, validated that the cluster and nodes still remain as `Active` in Cluster Management and Cluster Explorer.
     - Additionally, validated that the cluster DID NOT auto-upgrade upon upgrading Rancher server.
3. Repeated steps 2-3 in scenario and validated that no K8s version shows as experimental:
![image](https://user-images.githubusercontent.com/52591819/197618842-f996a9e4-f66c-4072-b4e2-202ed4296aaa.png)
