### ISSUE TITLE
Support K8s 1.24 EKS 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/dashboard#7219]
EKS versions are hardcoded in UI - https://github.com/rancher/ui/blob/66666c96edbfd705810f9a7ba09f7520abd51694/lib/shared/addon/utils/amazon.js#L686

1.24 will be introduced in EKS upstream in November 2022 per https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

SURE-5424

**Comment by nwmac** [comment]
Should be a 1-line change - see first link.

@mantis-toboggan-md Can we create a tech-debt ticket to investigate if this metadata is available via an API?

**Comment by Josh-Diamond** [comment]
Ticket #7219 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-d1249b5c6907bd326e09ec79d9ac8d9c22782d0d-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | `As admin, provision a downstream EKS cluster w/ k8s 1.24` | ✅ |
| 2. | `As standard user, provision a downstream EKS cluster w/ k8s 1.24` | ✅ |
| 3. | `Import EKS cluster into Rancher` | ✅ |

---

Scenario 1:
1. Fresh install of rancher `v2.7-head`
2. As admin, provision a downstream EKS cluster w/ k8s `1.24`
3. Verified - UI prompts k8s `1.24`; Cluster successfully provisions w/ k8s `v1.24.7-eks-fb459a0`

---

Scenario 2:
1. Fresh install of rancher `v2.7-head`
2. As standard user, provision a downstream EKS cluster w/ k8s `1.24`
3. Verified - - UI prompts k8s `1.24`; Cluster successfully provisions w/ k8s `v1.24.7-eks-fb459a0`

---

Scenario 3:
1. From EKS Console, create an EKS cluster w/ k8s `1.24` + 1 node group (2 nodes)
2. Fresh install of rancher `v2.7-head`
3. As standard user, import EKS cluster, created in step 1, into Rancher
4. Verified - Cluster successfully imports and is `active` - [k8s `v1.24.7-eks-fb459a0`]

**Comment by STARRY-S** [comment]
@Josh-Diamond 

Hi Josh, our customer encountered this problem:  
After importing the EKS cluster into Rancher and the cluster status is `active`, we can not view the cluster information page and it is stuck to **"Loading..."**, and the web-browser console shows the `eksNodeGroups` is `nil`.

I've submitted a bug report and a workaround PR here: https://github.com/rancher/rancher/issues/40509

Can you help to look into this issue and check if is it a bug?
