### ISSUE TITLE
Registry secrets are not available in the UI when creating a deployment 

### ISSUE THREAD

**Issue by brudnak** [rancher/dashboard#7220]
## Reproduction Environment

| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7-9f1e0435bb45e104ba897c5c329e1f23735843d9-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/9f1e0435bb45e104ba897c5c329e1f23735843d9 |
| Installation option              | Helm (high availability)                                                           |
| If Helm Chart k8s cluster        | v1.24.6+k3s1                                                                       |
| Cert Details                     | Let's Encrypt / `traefik`                                                          |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2                                               |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | RKE1 Linode                                                                        |
| Downstream K8s version           | v1.24.6-rancher1-1                                                                 |
| Authentication providers enabled | local & GitHub                                                                     |
| Logged in user role              | Administrator & Standard User                                                      |
| Browser type                     | Google Chrome                                                                      |
| Browser version                  | 106.0.5249.119 (Official Build) (x86_64)                                           |

<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=traefik \
  --version 2.6.9 \
  --set rancherImageTag=v2.7-head
```

</details>

## Describe the bug

Unable to create a deployment using a private docker image. Unable to select a `Pull Secrets` from the UI.

## Reproduction steps

1. Create a registry secret with Dockerhub
2. Start the process of creating a deployment
3. Under the `Image` section in deployments ==> click the drop down for `Pull Secrets`
4. It just displays `Sorry, no matching options`

When checking the network tab in the browser dev tools, it looks like the secrets endpoint that is being hit is `<rancher-url>/api/v1/namespaces/default/secrets` although in 2.6.8 and 2.6.9 the secrets endpoint that gets hit on the same page is `<rancher-url>/v1/secrets`. 

#### ✅ Expected
Expected to be able to create a deployment with a private image from Dockerhub.

#### ❌ Actual
Was unable to create a deployment with a private image from Dockerhub because the UI is not giving options to choose a set pull secret.

**Comment by nwmac** [comment]
@aalves08 I'm guessing this is to do with the secondary resource changes - can you take a look

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment


| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version                  | v2.7-9f1e0435bb45e104ba897c5c329e1f23735843d9-head |
| Installation option              | Helm (high availability)                           |
| If Helm Chart k8s cluster        | v1.24.6+k3s1                                       |
| Cert Details                     | Let's Encrypt / `traefik`                          |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2               |
| Helm version                     | v2.16.8-rancher2                                   |
| Downstream cluster type          | RKE1 Linode                                        |
| Downstream K8s version           | v1.24.6-rancher1-1                                 |
| Authentication providers enabled | local & GitHub                                     |
| Logged in user role              | Administrator & Standard User                      |
| Browser type                     | Google Chrome                                      |
| Browser version                  | 106.0.5249.119 (Official Build) (x86_64)           |



## Validation steps

1. Create a registry secret with Dockerhub
2. Start the process of creating a deployment
3. Under the `Image` section in deployments ==> click the drop down for `Pull Secrets`
4. The registry secret is now displayed, select it
5. Deploy the workload with a private dockerhub image
6. Image successfully runs

## Additional Info

## RESULTS

#### ✅ Expected
To be able to use a registry secret to launch a workload with a private image from Dockerhub

#### ✅ Actual
Was able to use a registry secret to launch a workload with a private image from Dockerhub

## 📋 QA Test Plan

<table>
    <tbody>
        <tr>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>Unsure that using a pull secret works for all Workload types</td>
            <td>
                <ol>
                    <li>CronJobs</li>
                    <li>DaemonSets</li>
                    <li>Deployments</li>
                    <li>Jobs</li>
                    <li>StatefulSets</li>
                    <li>Pod</li>
                </ol>
            </td>
            <td>Expected: To be able to use a registry secret to launch a workload with a private image from Dockerhub</td>
            <td>Actual: Was able to use a registry secret to launch a workload with a private image from Dockerhub<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Secret created with kubectl shows up</td>
            <td>
                <ol>
                    <li>Follow doc at https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/</li>
                    <li>Run the following command via kubectl</li>
                    <li><code>kubectl create secret docker-registry regcred --docker-server=your-registry-server --docker-username=your-name --docker-password=your-pword --docker-email=your-email</code></li>
                </ol>
            </td>
            <td>Expected: Secret created with kubectl shows up in the drop down</td>
            <td>Actual: Secret created with kubectl did show up in the drop down<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Secret is useable</td>
            <td>
                <ol>
                    <li>Use the registry secret to launch a private dockerhub image</li>
                    <li>Ensure that the secret actually works to pull the priviate image</li>
                </ol>
            </td>
            <td>Expected: Private image to successfully pull</td>
            <td>Actual: Private image was pulled and successfully ran<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>
