### ISSUE TITLE
Missing word on Helm chart install registry tooltip

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7232]
This should say "Cluster Container Registry," not "Cluster Container."
<img width="875" alt="Screen Shot 2022-10-19 at 11 51 50 AM" src="https://user-images.githubusercontent.com/20599230/196779193-4c85c612-6d91-403d-bbf2-6f935d48cce1.png">

**Comment by nickwsuse** [comment]
`Verified on v2.7.0-rc8`

The helper text is now correct

![image](https://user-images.githubusercontent.com/107147272/199604436-8a62d9d9-fd81-4605-9574-adce2297b9b0.png)
