### ISSUE TITLE
[BUG] Downstream RKE1 clusters' fail to install charts

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#7233]
**Rancher Server Setup**
- Rancher version: `v2.7-9f1e0435bb45e104ba897c5c329e1f23735843d9-head`, `v2.7.0-rc4`
- Installation option (Docker install/Helm Chart): `seen with both`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`
- Proxy/Cert Details: `byo-valid` with helm; insecure w/ Docker

**Information about the Cluster**
- Kubernetes version: `v1.24.6-rancher1-1`
- Cluster Type (Local/Downstream):
Downstream RKE1 AWS Node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
`Admin`

**Describe the bug**
Downstream RKE1 clusters are unable to install charts

**To Reproduce**
1. Fresh install of rancher `v2.7-head` or `v2.7.0-rc4`
2. Provision a downstream RKE1 AWS Node driver cluster w/ k8s `v1.24.6-rancher1-1`
3. Once `Active`, Navigate to `Cluster Explorer > Apps > Charts > [select a chart] > Install`
4. Reproduced

**Result**
Server responded with status code 404; 

**Expected Result**
Chart is installed

**Screenshots**

`Monitoring`
<img width="1603" alt="Screen Shot 2022-10-18 at 5 32 40 PM" src="https://user-images.githubusercontent.com/46494969/196574185-6afd9db7-b132-4469-a001-b7b7450be3a4.png">

`Monitoring > Install`
<img width="1600" alt="Screen Shot 2022-10-18 at 5 32 59 PM" src="https://user-images.githubusercontent.com/46494969/196574245-4a2382ed-8636-4bf1-a4a6-d1115bc0760f.png">

`CIS Benchmark`
<img width="1371" alt="Screen Shot 2022-10-18 at 5 33 13 PM" src="https://user-images.githubusercontent.com/46494969/196574290-240a3c67-7099-454a-be72-eff69a9f6eea.png">

`CIS Benchmark > Install`
<img width="1599" alt="Screen Shot 2022-10-18 at 5 33 25 PM" src="https://user-images.githubusercontent.com/46494969/196574304-0d6de051-0dc1-42f2-af46-05535df6311c.png">

`Dev Tools: Networking`
<img width="1363" alt="Screen Shot 2022-10-18 at 6 04 10 PM" src="https://user-images.githubusercontent.com/46494969/196574343-cbe2ab78-3e22-4f70-bf99-32ab92aad450.png">

`Helm Install`
<img width="711" alt="Screen Shot 2022-10-18 at 6 05 18 PM" src="https://user-images.githubusercontent.com/46494969/196574371-35d83d55-0deb-4bc3-8667-5e591fc3b183.png">

**Additional context**
This was tested via terminal as well, which resulted in the following error message:
```
Error: INSTALLATION FAILED: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets)
```

**Comment by catherineluse** [comment]
In the UI changes that were merged last week, the UI attempts to fetch the provisioning cluster resource for the purpose of checking for a cluster scoped registry for pulling the container images for the chart.

```js
const mgmCluster = this.$store.getters['currentCluster'];

const provCluster = await this.$store.dispatch('management/find', {
  type: CAPI.RANCHER_CLUSTER,
  id:   mgmCluster.provClusterId
});

```
The problem here is that `mgmCluster.provClusterId` is undefined for RKE1 clusters, so it causes the UI to crash.

**Comment by ronhorton** [comment]
**Pass** Verified in `2.7-head Commit ID 9f1e043`
1. RKE1 cluster - installed charts - behaved as expected
2. RKE1 cluster 2 - cluster-level private registry -installed charts - behaved as expected
3. RKE2 cluster - installed charts - behaved as expected
