### ISSUE TITLE
[Backport for 2.6.next1] Saving unchanged cluster leads to update status and cluster changes

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7236]
In 2.7.0, we have a fix for https://github.com/rancher/dashboard/issues/6881 -- we have been requested to back port this fix for 2.6.x.

Condensed summary from that ticket:

Saving unchanged cluster leads to update status and cluster changes.

To Reproduce

- Create a cluster.
- Wait for cluster to go to active.
- Go to edit the cluster.
- Switch to yaml (I think this is actually optional).
- Hit save.

Result
Fields are added and the cluster goes into updating.

Expected Result

The cluster should remain unchanged and should not go into updating.

Relevant PRs for reference:
- https://github.com/rancher/dashboard/pull/7218
- https://github.com/rancher/dashboard/pull/7140

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head e36364e
Rancher cluster type: HA
Docker version: 20.10
Downstream cluster type: rke2

----------

### Testing: ###
Tested this issue with the following steps:
1. Create a cluster.
2. Wait for cluster to go to active.
3. Go to edit the cluster.
4. Switch to yaml (I think this is actually optional).
5. Hit save.

**Result**
The cluster no longer goes into update status when saving an unchanged cluster
