### ISSUE TITLE
Incorrect version show when installing an extension

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7239]
UI always shows the latest version - if you select another version, while installing, the latest version is always shown instead of the version that you selected.

**Comment by AndrewHoffmanQA** [comment]
I am able to install an older version of a UI extension and the UI displays the correct version of the extension that was installed. moving to done. 

https://zube.io/files/rancher/c45a8cd49e9c12d3758e5e344dc00392-retest-7282.mp4
