### ISSUE TITLE
Charts installs are not using the system-default-registry value to pull images from private registry

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#7246]
**Setup**
- Rancher version: `v2.7.0-rc4`
- Browser type & version: Firefox

**Describe the bug**

Setting the `system-default-registry` Leaving UI defaults on RKE2 Custom (downstream) cluster creation (not editing Cluster Registries).
And leaving `Container Registry` to its default too in the Apps/Chart install UI.

The images are getting pulled from public registries (docker.io)

**To Reproduce**

- Rancher `v2.7.0-rc4` (local is RKE1 HA)
- Configure `system-default-registry` to use with a private registry (testing was done in a registry without auth)
- Create RKE2 downstream cluster (Custom was used in this case)
  - Check the `Registries` section picked up the `system-default-registry` as private registry value (do not edit)
- Once the cluster is up active Navigate to `Cluster -> Apps -> Charts` and attempt install a Chart  (OPA gatekeeper or monitoring during testing)

**Result**

- Navigate or use kubectl to check the chart namespace workloads/daemonsets/jobs and check the images are pulled from public not the private 

The images doesn't have the private registry hostname as prefix tag as seen in the screenshot:

<img width="1011" alt="Screen Shot 2022-10-19 at 5 02 43 PM" src="https://user-images.githubusercontent.com/27659/197005255-c434107d-5fa1-4d3f-9cfa-926a13fba4aa.png">

**Expected Result**

Images are pulled from the private registry

**Additional context**

Possibly related issues:

https://github.com/rancher/dashboard/issues/6910

Symptoms on Airgap:

https://github.com/rancher/rancher/issues/39364

This blocks Airgap

**Comment by richard-cox** [comment]
I added the [comment](https://github.com/rancher/rancher/issues/39364#issuecomment-1285852417) in the `rancher/rancher` issue, i don't think this is a FE bug

**Comment by richard-cox** [comment]
Update - My assumption as wrong and this was a FE issue
