### ISSUE TITLE
UI crashes with error: "Crashpad_FailedToCaptureProcess"

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7247]
Internal reference: SURE-5432
Reported in 2.6.8

Rancher 2.6.8 UI crashes showing the "Aw, Snap!" page with `Error code: Crashpad_FailedToCaptureProcess` within 30 seconds. 

The user can consistently reproduce this by navigating through the Cluster Explorer > Workload > Deployments > open a deployment that contains an ingress and go to the Ingresses tab. They have also seen it a couple of times while waiting for the deployments list to load. 

This happens on a very big/busy multi-tenant cluster. The cluster has 570 namespaces, ~1000 ingresses, ~8500 replica sets, > 1000 deployments, > 2000 pods.

This is happening when viewing multiple clusters, from multiple Rancher instances. Examples:

Rancher instance 1 - v2.6.8 RKE v1.19:

    CronJobs: 79
    DeamonSets: 14
    Deployments: 1285
    Jobs: 381
    StatefulSets: 55
    Pods: 2359

Rancher instance 2 -  v2.6.8 RKE v1.19:

    CronJobs: 102
    DaemonSets: 3
    Deployments: 1019
    Jobs: 488
    StatefulSets; 94
    Pods: 2603

Other users are reporting that the browser tab doesn't crash, but it does take a ton of RAM (multiple GB) to render the page, and so the browser gets very sluggish and unresponsive.  But doesn't fully crash.

The browser crashes or becomes very sluggish making the UI unusable for certain tasks. So far the issue seems to be impacting admin users, not the wider user base (probably because their access is limited to the number of resources they can see).

Troubleshooting steps:
It was observed that a lot of traffic coming over the websocket (including errors) when viewing the dev tools in the web browser. Big takeaways: 8500 replicasets combined with somewhere around a couple of hundred messages (or more, we weren't able to actually count) per 20-second period.

Repro steps:

It would need a similar environment as above, but the user can consistently reproduce this by navigating through the Cluster Explorer > Workload > Deployments > open a deployment that contains an ingress and go to the Ingresses tab.

Workaround:
The problem does not happen with the old UI using /g in the URL

Additional notes:
Another interesting behavior that might be related is that they're still using the Monitoring v1 stack, and when clicking into a Deployment, none of the monitoring graphs are appearing anymore.

**Comment by gaktive** [comment]
This may be addressed by other work in 2.7.1. @Sean-McQ to link a couple tickets here and this could be validated.

**Comment by gaktive** [comment]
@Sean-McQ to verify if his work elsewhere will address this. If not, then we can groom this again.

**Comment by richard-cox** [comment]
This needs re-evaluating once https://github.com/rancher/dashboard/issues/7618 has been completed

**Comment by gaktive** [comment]
Moving back to Backlog. The related other ticket is now in QA so this could be worked on but it requires discussion.

**Comment by nwmac** [comment]
Closing for now, following a number of improvements - re-open with more data if reproducible.
