### ISSUE TITLE
Cluster Owner (not admin) unable to access items under Related Resources tab

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7251]
Under Cluster Management, Cluster details, Related resources, a user is unable to access any resources as a cluster owner (not an admin).

## To Reproduce

1. Create a downstream cluster as an administrator
2. Set up a standard user named `tuser1`
3. Assign `tuser1` to the downstream cluster as a cluster owner
4. As an administrator, log out and log in as `tuser1`
5. Logged in as `tuser1`, and starting from the **default** Rancher homepage `/dashboard/home`
   1. Click `hamburger menu` ==> `Cluster Management` ==> click the link of the name of the downstream cluster (not explore) ==> click on the `Related Resources` tab
   2. Click on one of the resources, for example `Cluster Member` or `Secret` under `Refers To`
   3. Unable to access links to the resources, getting a `403` : `Forbidden` with a `GET` to `v1/management.cattle.io.clusters/local`

```json
{"type":"error","links":{},"code":"Forbidden","message":"clusters.management.cattle.io \"local\" is forbidden: User \"u-b7s7x\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","status":403,"type":"error"}
```

6. With the same click / redirect to the homepage also getting a `PUT`:`500` error to `v1/userpreferences/u-b7s7x`

```json
{"type":"error","links":{},"code":"ServerError","message":"Operation cannot be fulfilled on preferences.management.cattle.io \"cluster\": the object has been modified; please apply your changes to the latest version and try again","status":500,"type":"error"}
```

## Result
Unable to access links under related resources tab

## Expected Result
For these not to be displayed if deemed they shouldn't be accessible to a standard user as a cluster owner

## Additional Notes
Upon investigation with @nwmac, the error in Repro Step 6 is a bit of a red herring. Based on Step 5's call, the UI isn't picking up the explorer context to talk to the downstream cluster; we're still pointing to the local cluster, hence the 403. Sounds like a simple UI fix, though we need to investigate.

**Comment by nwmac** [comment]
Duplicates https://github.com/rancher/dashboard/issues/6878
