### ISSUE TITLE
Allow CIS scanning to be able to have customized scan report names

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#7252]
**Is your feature request related to a problem? Please describe.**

When performing CIS scanning on a cluster, you currently do not have the option to name the resulting scan report. Here is what the UI currently offers in `v2.7-head` https://github.com/rancher/rancher/commit/9f1e0435bb45e104ba897c5c329e1f23735843d9:

![image](https://user-images.githubusercontent.com/52591819/197069801-e1b8b5ae-d383-4a07-a005-dcda6196d33e.png)

The resulting name is `scan-xxxxx`, where the x is replaced by a string literal or number. We should give users the flexibility to name their scan reports. This will be helpful in several scenarios, one of which being if reports are regularly scheduled, then being able to find an isolated report will be easier if they're named.

**Describe the solution you'd like**

When going to run a CIS scan on a cluster, there should be  a field in the UI that allows the user to customize the scan report's name. This will be an optional field and left blank, then the name will be `scan-xxxxx`, which is the behavior now. However, if a user customizes the name, the resulting name would be whatever they changed it to.

In the case of regularly scanned reports, if a user gives a name, then there does need to be some identifier to distinguish between days. Whether that is appending the date at the end of the name, something will need to be done to ensure duplicate names are not formed.

**Comment by gaktive** [comment]
This is going to be more backend driven rather than UI. Closing for now based on current ticket volume; if this is something desired, then check with PM and have a Jira ticket created for discussion.
