### ISSUE TITLE
Mount point field not appearing on the workload creation form

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/dashboard#7253]
**Setup**
- Rancher version: v2.6.9
- Browser type & version: Chrome

**Describe the bug**
There is no option to enter mount point when creating deployment/statefulSet and attaching a volume to it.

**To Reproduce**

1. Go to Rancher Dashboard, navigate to the Deployments. Click Create.
2. Go to Pod--> Storage
3. Add volume using `Create Persistent volume claim`.

**Result**
4. There is no option to enter the mount point.

**Expected Result**
There should be a field to enter the mount path and subpath.

**Screenshots**
<img width="1290" alt="Screen Shot 2022-10-20 at 3 14 51 PM" src="https://user-images.githubusercontent.com/60111667/197072927-14dae818-4eb2-4af2-8cd8-867cc978c969.png">

**Additional context**
It was available in previous versions.

**Comment by PhanLe1010** [comment]
Do you see it under the container tab?

**Comment by catherineluse** [comment]
This should be expected behavior because the storage volume is configured at the pod scope, but the mount point is configured at the container scope (because the volume can be mounted at different paths for different containers). The mount path was removed from the pod tab because it had to move to the container tab.

**Comment by PhanLe1010** [comment]
Yeah, that was what I was confusing in the older Rancher version since it doesn't make sense to have mount point at pod level

**Comment by Shavindra** [comment]
Mount paths for containers are in containers tab as per 2.6.9

Change PR: https://github.com/rancher/dashboard/pull/6886

**Comment by khushboo-rancher** [comment]
Validated that the mount point is now available in the container tab.
<img width="1222" alt="Screenshot 2022-10-27 at 2 50 25 PM" src="https://user-images.githubusercontent.com/60111667/198404981-021a2071-4df1-49e4-9f2b-685cddfc52aa.png">
