### ISSUE TITLE
[Bug] - Charts - NeuVector Image Registry setting is not applied and pods are pulling from public docker registry

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#7260]
**Setup**
- Rancher version: `v2.7.0-rc6`
- Browser type & version: Firefox 106 and MS Edge

**Describe the bug**

When installing the NeuVector App the user can set the registry hostname in the `Image Registry` input field.  (See screenshot below)

This then makes the chart to use the private registry images instead of pulling from the default public docker registry.

**_This works on Rancher_** `v2.6.9`

**To Reproduce**

- Rancher Airgap RKE1  install
- Use private registry without auth
- Provision a Custom Downstream RKE1 cluster
- Once the cluster is up active Navigate to `Cluster -> Apps -> Charts` and attempt install the NeuVector chart
  - Make sure to use the private registry URL in the `Image Registry` input field. (See screenshot below)

**Result**

- NeuVector pods are in `ImagePullBackoff` error state because they are trying to pull the images from public docker instead of the private registry
**_This works on Rancher_** `v2.6.9`

**Expected Result**

- `Image Registry` value is correctly used and the NeuVector pods pull the images from the Private Registry

**Screenshots**

<img width="1152" alt="Screen Shot 2022-10-22 at 6 50 38 PM" src="https://user-images.githubusercontent.com/27659/197369466-cc65897a-b564-4a4a-b296-ee89ab3aa0c4.png">

**Additional context**

Not reproducible on Rancher `v2.6.9`

**Comment by izaac** [comment]
If this is Backend please move to `rancher/rancher`

**Comment by richard-cox** [comment]
I've had a play with Izaac's system providing the `systemDefaultRegistry` values and could successfully deploy the NeuVector app. It looks like they do pull these in, but i'm still not sure how they relate to their own registry value (which was also set).

We could either
1) Supply `systemDefaultRegistry` for ALL charts 
2) Request NeuVector add one/both `systemDefaultRegistry` properties to their chart values

**Comment by selvamt94** [comment]
Look like deployment template takes registry value from systemDefaultRegistry. This is one of the requirement of the feature chart. The registry value given in the UI is not taken while creating deployment. We may need to remove registry entry from UI. I will update the NeuVector chart after checking with Dev.

**Comment by richard-cox** [comment]
@selvamt94 The associated PR to this issue ensures the `systemDefaultRegistry` will be applied by default using the new input field on step 1 of the install chart wizard

![image](https://user-images.githubusercontent.com/18697775/197724108-427e377b-5a8d-4d45-89c1-63e78f29dfa2.png)

If the `Image Registy` value from `questions.yaml` (which i think is put in to values as just `registry`) isn't used then it would be great to get that removed

![image](https://user-images.githubusercontent.com/18697775/197724339-e000ab69-8e6e-48ba-a78b-ce931286c3f3.png)

Is the `Controller Image Path` used as well?

**Comment by izaac** [comment]
@richard-cox @selvamt94 

To clarify the expectation for this issue would be remove the `Image Registy` field from the UI or the entire `Container Images` section?

After this change NeuVector's `Image Registy` setting is just ignored in Rancher `v2.7.0-rc7`

If there's going to be further changes to the NeuVector chart UI could we link it in this issue assuming that's tracked in Github ?

**Comment by selvamt94** [comment]
> Is the `Controller Image Path` used as well?

@richard-cox 
Repository path and tag for the images are applied from question.yaml. Only registry value is not applied. We want to update the NeuVector chart values.yaml with the below values and pointing to registry key in values.yaml so that systemDefaultRegistry can be changed from UI 
```
global:
  cattle:
    systemDefaultRegistry: ""```

You are already providing option to change systemDefaultRegistry in the step1. Is it okay to provide again the registry option to change it in the step2 (question.yaml)?

**Comment by richard-cox** [comment]
I think there's a bit of confusion here. If the UI in step 1 is now setting `systemDefaultRegistry` in `values` is the `registry` in `values` still needed? If so can the chart itself apply the value from `systemDefaultRegistry` to `registry` and `Image Registry` from `questions.yaml` can then be removed (rather than visually keeping both in the install wizard)?

**Comment by selvamt94** [comment]
We will remove `Image Registry` from UI (question.yaml). Is it possible to make changes in Neuvector chart for 2.7.0 release. If so I can make a PR for the Neuvector chart. Do I need to add below values to NeuVector chart's values.yaml?  

```
global:
  cattle:
    systemDefaultRegistry: ""
```

**Comment by izaac** [comment]
@selvamt94 @richard-cox 

Original issue is fixed.

Opened is now open https://github.com/rancher/dashboard/issues/7307 to follow up the `Image Registry` setting
