### ISSUE TITLE
Table sub-row highlighting broken

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7263]
Move the mouse over a sub-row and only the sub-row is highlighted - the parent (main) row should be too.

This is a regression.

Example below - add a taint to a node so that it has a sub-row:

![image](https://user-images.githubusercontent.com/1955897/197509063-2f1f7ace-e7dd-4c3c-97e7-dafdd07d0519.png)

**Comment by richard-cox** [comment]
This works usually, however it looks like the node table has a custom sub-row

![image](https://user-images.githubusercontent.com/18697775/197525234-136a6029-f577-4b46-8857-b9408fff16a4.png)

**Comment by richard-cox** [comment]
This is an issue in two places where custom sub-rows are used (see #7266 for details)

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.6.8**

<img width="691" alt="Screen Shot 2022-10-25 at 2 06 40 PM" src="https://user-images.githubusercontent.com/26032343/197885144-ec5b12b4-c11a-4b53-8f8e-3b928b4f624b.png">

**validated the issue successfully on 2.7-head commit id: `5d45218`**
<img width="475" alt="Screen Shot 2022-10-25 at 2 25 31 PM" src="https://user-images.githubusercontent.com/26032343/197885154-a8b3ef57-4f39-4f68-b517-0b76b5550d7a.png">
<img width="664" alt="Screen Shot 2022-10-25 at 2 07 03 PM" src="https://user-images.githubusercontent.com/26032343/197885156-37380b8f-b775-409d-a87a-ed75f5c11ebf.png">
