### ISSUE TITLE
Sortable Table: Column heading should respect column alignment

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7265]
Look at the 'age' column in the example below.

The heading is left-aligned but the column row content is right-aligned.

The heading should align the same as the content.

**Comment by gaktive** [comment]
@kwwii to confirm how this looks but namely, this should all be left aligned.

**Comment by gaktive** [comment]
This could connect with other work tied to table columns.

**Comment by eva-vashkevich** [comment]
Duplicate of [#7560](https://github.com/rancher/dashboard/issues/7560) 
Fixed by https://github.com/rancher/dashboard/pull/7577
