### ISSUE TITLE
"UI Performance Settings" page doesn't disable the options for non-admin users

### ISSUE THREAD

**Issue by macedogm** [rancher/dashboard#7272]
**Setup**
- Rancher version: v2.6.9
- Browser type & version: Firefox (`106.0.1 (64-bit)`) and Chrome (`Version 106.0.5249.119 (Official Build) (arm64)`)

**Describe the bug**

The UI doesn't disable the buttons and options in `Global Settings > Performance > UI Performance Settings` page when accessed by non-admin users (or users without permissions to update those settings, like `Standard User` and `User-Base` for example). If the user doesn't have permissions to configure the settings, the UI will still allow the user to change the settings in the UI, but the user can't save them. The "edited" settings will not generate any configuration change at all. This can cause confusion and seem to be a security issue, which is not the case.

**To Reproduce**

1. As an admin, create a user with `User-Base` global permissions. Do not add any additional permissions.
2. Log in as the newly created user.
3. Go to `Global Settings > Performance > UI Performance Settings` page.
4. The options are not disabled, so it causes the impression that the user can change them. There is no apply button.
    1. Trying to force-save the changes by making an API request will be properly validated and denied by the backend, because the user doesn't have such permissions.
5. Go to any other settings page, like `Branding`, for example.
6. See that all the options are properly disabled.

**Result**

**Expected Result**

A non-admin user (or users without permissions to update settings in UI, like `Standard User` and `User-Base` for example), when accessing `Global Settings > Performance > UI Performance Settings` page will see all options as disabled (like what happens with the other settings pages).

**Screenshots**

The "Performance" options are editable for non-admin users.
![image](https://user-images.githubusercontent.com/17654553/197578083-4f72724f-bf8f-4d2b-8f23-1f4c4717a5cd.png)

Instead of being disabled, like in the other menus.
![image](https://user-images.githubusercontent.com/17654553/197578136-a8ef3dc6-ee4f-4e16-8dbc-a47cff4b1d83.png)

**Additional context**

This is not a security issue, because the user can't save the edited configurations.

**Comment by anupama2501** [comment]
Verified upgrade from v2.6.7 >> v2.7-head 0247e13
1. Installed rancher on v2.6.7
2. Added 3 users - user1:standard user, user2:Restricted Admin, user3: User base
3. Logged in as user1, user2 and user3 and see that the fields are editable but no apply button is present
4. Upgraded rancher server to v2.7-head and verified the fields are not editable for user1, user2 and user3. 
5. For user base user3 added additional permissions to manage settings and verified user3 was able to edit then

Verified fresh checks on rancher v2.7-head 40932d6
Repeated steps 2,3 and 5 from the above scenario and verified the fields are not editable for non admin users.
