### ISSUE TITLE
[Backport for 2.6.x] Execute shell on workload page not work correctly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7274]
- Backport of issue https://github.com/rancher/dashboard/issues/6982, resolved in 2.7 via https://github.com/rancher/dashboard/pull/6981
- It's a small fix (1 new line, 1 edited line) and should be straight forward to backport

**Comment by richard-cox** [comment]
Completed via https://github.com/rancher/dashboard/pull/7718

**Comment by Josh-Diamond** [comment]
Ticket #7274 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.6-ac694c9cd0b0e2e89e894e0b92050e76cdc1fe33-head`:
1. Fresh install of rancher v2.6-head
2. Provision a downstream cluster - [ I used RKE2 AWS Node driver w/ k8s `v1.24.8+rke2r1` ]
3. Once active, create three namespaces under default project - [ a, b, c ]
4. Create the same deployment in each namespace
5. For each namespace, filter by namespace and execute shell
6. Verified - filter successfully filters namespaces; execute shell launches in correct pod
7. Filter only a + b (excluding c), and launch execute shell for each namespace deployment
8. Verified - filter successfully filters namespaces; execute shell launches in correct pod
9. Filter a + b + c , and and launch execute shell for each namespace deployment
10. Verified - filter successfully filters namespaces; execute shell launches in correct pod

Screenshot:

`Step 9`
<img width="1586" alt="Screenshot 2023-01-06 at 12 10 36 PM" src="https://user-images.githubusercontent.com/46494969/211083024-e88bf6fb-504b-40b3-82d1-52ced8df564c.png">
