### ISSUE TITLE
Carousel error uncaught type 'cannot read properties of undefined'

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#7278]
**Setup**
- Rancher version: `2.7.0-rc6`
- Browser type & version: `chrome Version 106.0.5249.103 (Official Build) (x86_64)`

**Describe the bug**

**To Reproduce**
1. add repo for featured charts https://nwmac.github.io/rancher-charts
2. click apps > charts
3. select featured chart

**Result**
`67Carousel.vue:97 Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at f.slidePosition (Carousel.vue:97:1)
    at f.autoScrollSlide (Carousel.vue:92:1)`

**Expected Result**
no errors in console 

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment]
I'm having trouble recreating this, it shows the symptoms of https://github.com/rancher/dashboard/issues/7241 though without the fix. 

@ronhorton
- Was this something discovered after validating the other issue?
- What movement/scroll state is the carousel in when clicking on featured chart (hasn't moved yet, currently moving, finished moving, etc)
- Does the carousel scroll when returning to the page?

**Comment by ronhorton** [comment]
@richard-cox just saw this error on a cluster that doesn't have an active carousel. 

saw when clicking the charts page
saw when clicking away from charts page to cluster page

it's happening around the charts page; there are also socket errors this morning when clicking on the charts page - not sure if related. 

![2022-10-25_10-55-28.png](https://zube.io/files/rancher/ead26aeee8ca4b0b82b525bcaa532223-2022-10-25_10-55-28.png)

**Comment by richard-cox** [comment]
@ronhorton I still cannot reproduce this and have also tried on the latest version of rancher (`v2-7-head` `833b1ab`)

Please could you provide click by click reproduction instructions (from log in), and the `value` shown when going to each of these?
- <rancher url>/v3/settings/server-version
- <rancher url>/v3/settings/ui-offline-preferred
- <rancher url>/v3/settings/ui-dashboard-index

Also, these questions are important to tie down precisely where the error is coming from
- What movement/scroll state is the carousel in when clicking on featured chart (hasn't moved yet, currently moving, finished moving, etc)
- Does the carousel scroll when returning to the page?
- Does the error in the console continue to be output every 2 or 5 seconds, or is it just once?

**Comment by ronhorton** [comment]
**retested - no issue** `2.7.0-rc8`

- no 'style' uncaught errors from UI when interacting with carousel. 
- also installed logging chart
- returned to carousel and selected other featured charts
- switched toggle to browse
