### ISSUE TITLE
Document how table headers are populated

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#7283]
In the course of working on internationalization there has been knowledge learned about the various ways table headers are populated.

**Comment by sowmyav27** [comment]
@gaktive @nwmac Can you confirm if this needs QA validation?

**Comment by gaktive** [comment]
No QA validation required @sowmyav27 
I have to talk with @nwmac when he's back on the workflow for this but for now, if you see a storybook label, you don't have to test it since that's UI internal docs.
