### ISSUE TITLE
Use API to get EKS region and instance data instead of hardcoding

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#7295]
The UI has a fair bit of hardcoded amazon data, see: https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/amazon.js 
In particular we are manually keeping track of which EKS versions to show. We should investigate whether or not there is an API we can use for EKS versions and possibly region/instance data as well.

**Comment by catherineluse** [comment]
Someone found a way to do it indirectly https://stackoverflow.com/a/71448603/5370501

**Comment by catherineluse** [comment]
There is already an issue about replacing the hardcoded EKS versions https://github.com/rancher/dashboard/issues/4401, so I'm editing the scope of the issue to region and instance data.

**Comment by richard-cox** [comment]
Need to also consider EC2 regions and regions list used when supplying credentials

This covers old and new UIs.

Old UI
REGIONS - Used for EC2 AND credentials (used by both ec2 and eks)
EKS_REGIONS - Used for eks things

New UI
TBD

**Comment by gaktive** [comment]
@mantis-toboggan-md when we port EKS, is this doable in Vue? or is that even possible? We could potentially close this if this is also covered with existing migration plans.

**Comment by mantis-toboggan-md** [comment]
@gaktive I think it would make sense to tackle this at the same time as the EKS migration, but I don't think this enhancement is implicit in that plan - it's worth calling out directly

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head

**Comment by crossRT** [comment]
hi, is this feature merged?
Because the new AWS region ap-southeast-5 has been launched, I noticed another issue (https://github.com/rancher/dashboard/pull/12833): the AWS region is still being updated manually.
