### ISSUE TITLE
OPA Gatekeeper shows 'CustomizeCustomize' as button label

### ISSUE THREAD

**Issue by vocatan** [rancher/dashboard#730]
I made a Pull Request for 2 minor typographical issues I found, but I don't understand how to fix the issue with the label being duplicated on this screen.

At the URL https://[...]/dashboard/c/c-dncfv/gatekeeper
![image](https://user-images.githubusercontent.com/761455/83813485-701f8400-a68b-11ea-831e-0b5412b45717.png)

I hope that this issue report isn't a PITA and that my PR is helpful.

**Comment by deniseschannon** [comment]
This is actually already fixed in our `master` branch, and will be pushing out an update with these fixes in about a week. 

Thanks for your other PR! 

Duplicate of https://github.com/rancher/dashboard/issues/532
