### ISSUE TITLE
Tidy up from v1 Logging removal

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7300]
Reported in `v2.7.0-rc4`

Stemming from work in https://github.com/rancher/rancher/issues/39350, specifically https://github.com/rancher/rancher/issues/39350#issuecomment-1291218015, with the removal of v1 Logging, the Rancher api schema is missing and this causes workload deployment to fail through the Ember UI.

Quoting @prachidamle:
> Yes it seems like the v1 Logging removal has removed the CRDs related to `projectlogging` and `clusterlogging`. We need to check if UI is making an API call that gets the error since backend/API schema is now removed and deprecated

Repro (from @ronhorton):
- Deploying workload in 2.7.0-rc4, error for missing schema prevents workload from deploying
- Navigate to Ember UI --> cluster --> Project --> and create a workload.
- `404 Not Found: no such schema` appears on screen

Related backend PR: https://github.com/rancher/rancher/pull/39189

**Comment by ronhorton** [comment]
**Pass** verified in `2.7.0-rc9`
1. switched to emberUI on downstream rke1 cluster
2. selected cluster > default
3. deployed workload - no error
4. cloned workload - no error
<img width="1352" alt="2022-11-03_16-42-42" src="https://user-images.githubusercontent.com/89212856/199830192-e4a1f7c7-440d-48ed-af33-73044f8431cf.png">
