### ISSUE TITLE
[Backport 2.6.x] Selector preview in service edit form does not consider namespaces

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7301]
Reported in 2.6.8

When you create or edit a service, the preview box that tells you which Pods are matched by the selector does not consider namespaces. A service can only match pods from the same namespace.

2.7.0 has a fix: https://github.com/rancher/dashboard/issues/6984 with PR https://github.com/rancher/dashboard/pull/6985

This is a request for a backport.

**Comment by bashofmann** [comment]
I'd be happy to create a backport PR, but to which branch?

**Comment by richard-cox** [comment]
@bashofmann Thanks! Good question regarding branches. There is a `release-2.6` however i think that was for the 2.6.0 release. I'll check with the team

**Comment by nickwsuse** [comment]
`Verified on v2.6-head ID: 49e0eb1`

The resource selector is now namespace considerate, meaning if you make a deployment in the default namespace you can only find that resource in the default namespace.
