### ISSUE TITLE
[Bug] - NeuVector Chart Image Registry setting should default to systemDefaultRegistry

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#7307]
**Setup**
- Rancher version: `v2.7.0-rc7`
- Browser type & version: Firefox and MS Edge

**Describe the bug**

The logic when installing charts is now using `global.systemDefaultRegistry` or `global.cattle.systemDefaultRegistry` during installation and the NeuVector chart setting `Image Registry` is no longer used. This need to be removed as is no longer used when installing the chart

**To Reproduce**

- Rancher HA `v2.7.0-rc7`
- Use private registry without auth
- Provision a Custom Downstream RKE1 cluster
- Once the cluster is up active Navigate to Cluster -> Apps -> Charts and attempt install the NeuVector chart 

**Result**

There'ds now a step for the `systemDefaultRegistry` This is what's now used 

<img width="890" alt="Screen Shot 2022-10-31 at 9 16 47 AM" src="https://user-images.githubusercontent.com/27659/199057525-0f8aaeac-fb50-4b93-b3d9-dd36f07bd41f.png">

**Expected Result**

`Image Registry` NeuVector setting  should be adapted to this new logic (Possibly removed and default to `systemDefaultRegistry`? )

<img width="745" alt="Screen Shot 2022-10-31 at 9 15 59 AM" src="https://user-images.githubusercontent.com/27659/199057993-f42c436e-0e78-4e99-9d04-a812aed7e4f8.png">

Related: https://github.com/rancher/dashboard/issues/7260

**Comment by richard-cox** [comment]
@selvamt94 Sorry, i missed your questions from https://github.com/rancher/dashboard/issues/7260#issuecomment-1292840979. I'll answer here.

1) "We will remove Image Registry from UI (question.yaml)" - Great, agreed
2) "Do I need to add below values to NeuVector chart's values.yaml" - Correct. Functionally it's not needed, but I think it's Helm best practise to include it there
    ```
    global:
      cattle:
        systemDefaultRegistry: ""
    ```

Additionally
- "Is it possible to make changes in Neuvector chart for 2.7.0 release" - I'm not sure on the rancher chart release cycle, you may need to check with that team in slack

Also, as this is now a NueVector chart issue, which repo shall we transfer this issue to?

**Comment by richard-cox** [comment]
@izaac Can you recreate this over at https://github.com/neuvector/neuvector-helm? It's a different org so i can transfer it

**Comment by selvamt94** [comment]
@richard-cox @izaac  We do not change the neuvector helm chart itself for supporting Rancher feature chart. We patch the chart while making feature chart. I have already submitted PR for those changes for both branches.
https://github.com/rancher/charts/pull/2188
https://github.com/rancher/charts/pull/2187
I may need to create an issue on rancher/charts for merging.

**Comment by izaac** [comment]
@selvamt94 could you create it and link it to this issue? Or let me know if you rather me to do it.
