### ISSUE TITLE
Create GH action for PRs that checks the devkit doc build

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7314]
Docs are only built on merge to master, so if you break it, you don't know until that fails.

Add a PR check to check that a PR has not broken the docs.

**Comment by SuperAayush** [comment]
Hey @nwmac!!
I would like to work on this and can you please provide me with a few resources that would help to go for the PR ASAP!!

**Comment by nwmac** [comment]
@SuperAayush Thanks for your interest - this one was already taken care of. If you're up for contributing, please have a look for issues labelled 'good first issue'. Thanks.
