### ISSUE TITLE
Fleet RBAC: Existing UI works with user with limited permissions

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7315]
**Stage 1**

User with access to gitrepos only via global role

Create a global role, e.g. Fleet User, give permissions:

![image](https://user-images.githubusercontent.com/1955897/199246216-ebe21e25-2cad-4c49-9427-a085cf3700ef.png)

Create a new user with 'user base' and add the 'Fleet User' role to them

- Dashboard page should render - currently requires bundles.
- Should be able to add a gitrepo - adds okay, but then fails with an error message - must be computing a property or something.
- Should be able to access detail for a GitRepo - with and without bundle resource access
- BUG: Refreshing on the git repo page shows no repos, but if you go to dashboard and back again, it does - check this is not due to requiring bundle access

**Stage 2**

Can we give a user access to a single project that contains a namespace for a fleet workspace and check they can only do things to that fleet workspace

Update the global role 'Fleet User' and remove the `gitrepos` resource from it.

Create a project/namespace role and give access to gitrepos (as above image, but only gitrepos resource - call it `Fleet Project Access'.

As an admin user, create a project `FleetTestProject` and create a fleet workspace. Go into the local cluster and move the fleet workspace to the project. Edit the project and give our test user permissions the `Fleet Project Access' on that project.

With these permissions, the user we created should be able to access Fleet, but only be able to access the resources in the single Fleet Workspace we created.

We now need to remove the global permissions on the Fleet Workspace resource.

We need to:

- Update the UI so that if the user does NOT have access to the Fleet Workspace resource, that we get the list of workspaces that the user can access by looking at the namespaces they have access to and filtering those that have the annotation `"objectset.rio.cattle.io/id": "workspace"` - this appears to be preset on namespaces that are fleet workspaces.

With this done, our user will not be able to manage or see fleet workspace resources, but will be able to see the list of fleet workspaces that they have access to (via the underlying namespace) and they will be able to create git repos in those workspaces.

**Comment by olblak** [comment]
What's the current state here? 
Shouldn't we close this issue?

**Comment by izaac** [comment]
Where can I find this in the UI ? Continuous Delivery?

I am on `v2.7-head` with dashboard `release-2.7.2 4065709cf`
Fleet is `v0.6.0-rc.5`

@nwmac

**Comment by izaac** [comment]
I got this clarified in an offline conversation. Please disregard.

**Comment by izaac** [comment]
Validated on Rancher v`v2.7-head` over multiple commits latest: `0c76b3f`
Latest validated Dashboard: `release-2.7.2 94650da49`
Fleet: `v0.6.0-rc.5`

Validated based on documented test plan scenarios.

Separate issues during validation:
https://github.com/rancher/dashboard/issues/8623
https://github.com/rancher/dashboard/issues/8624
https://github.com/rancher/dashboard/issues/8468
https://github.com/rancher/dashboard/issues/8467
