### ISSUE TITLE
[featured charts]Browse selection does not persist across log outs/ins

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#7316]
**Setup**
- Rancher version: `2.7.0-rc8`
- Browser type & version: `chrome latest`

**Describe the bug**
[requirements](https://github.com/rancher/dashboard/issues/5460#:~:text=Add%20a%20toggle%20switch%20in%20the%20top%2Dright%20%27Browse%20%7C%20Featured%27%20%2D%20the%20default%20will%20be%20%27featured%27%2C%20but%20this%20should%20be%20persisted%20in%20a%20user%20preference%2C%20so%20that%20the%20choice%20is%20remembered%20across%20logins) - user choice should persist across log ins; ie, if 'browse' was selected, user should see 'browse' next visit. 
when logged out and in after selecting 'browse,' featured was again displayed when returning to the apps>charts page

**To Reproduce**
1. go to apps>charts
2. select 'browse' - carousel not shown
3. log out
4. log in
5. go to apps>charts

**Result**
`featured` is displayed with carousel

**Expected Result**
`browse` setting should be saved from setting prior to logging out

**Screenshots**

**Additional context**

**Comment by gaktive** [comment]
We'll need to add a preference for the user to remember the `browse` setting.

**Comment by nwmac** [comment]
On the Apps view we now show a featured carousel at the top - the user can toggle to 'browse' where we don't show this - but this is not remembered across sessions, so refreshing the page defaults back to showing the carousel - we need to add a preference.

**Comment by AndrewHoffmanQA** [comment]
retest passes. site now saves user's preferences regarding 'browsing' or 'feature' on the apps > charts page

tested on 2.7head 8062f1e
