### ISSUE TITLE
Enhancement: improve how memory utilization is shown

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7322]
Internal reference: SURE-5122
Reported in 2.6.3

Request description:
The Feature Request is to display Memory in the Rancher GUI as components of "Free Memory and Buffer/Cache Memory" separate. This will allow teams to understand if a node's "Actual" memory utilization is high and not just a large amount of buffer/cache memory.

Example: when viewing nodes from cluster explorer, the memory usage is displayed as a total of all "used memory, buffer memory, and cache memory." This number can sometimes be 80% or greater, causing the icon to be "Red," although actual memory utilization is relatively low; <20%.

Actual behavior:
The UI displays the total of "Used" memory and "Buffer/Cache" memory as displayed with `kubectl top nodes`.

Expected behavior:
This is expected as this is the design of upstream Kubernetes.

Workaround:
View resource utilization from Grafana/Prometheus.

Additional notes:
The operators understand the value that is being displayed and how it is calculated. The concern is for "Clients" that use the UI, and they will see "Red" icons for Memory usage and think that something is in error or failing; when in actuality, the memory usage is low, and we are seeing the additional buffer/cache memory on that particular node.

One proposed solution for the reporting user: utilizing "Resource Requests and Limits" in their environment and workloads is the best practice for managing pod resource consumption and avoiding pod evictions.

**Comment by cnotv** [comment]
@kwwii do we need any design for this one?
