### ISSUE TITLE
rke2 custom deployment from rancher 2.6.7 with CIS Profile cis-1.6 doesn't use "true" as a default for protect-kernel-default

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7331]
Internal reference: SURE-4172
Reported in 2.6.5 & 2.6.7

Issue description:
When we use rke2 custom deployment from rancher 2.6.7 with CIS Profile cis-1.6, the protect-kernel-defaults is set to false.

```
- config:
 profile: cis-1.6
 protect-kernel-defaults: false
```

In the UI under Cluster Create, there's a checkbox for `protect-kernel-defaults`. We should have this checked if a CIS Profile was selected

![screenshot-1.png](https://zube.io/files/rancher/c2a94b7d551b46d9b2983f44df7b4235-screenshot-1.png)

Repro steps:

- Install stable, latest or alpha version of rancher 2.6 and attempt to create a downstream rke2 custom cluster with CIS Profile cis-1.6.
- Then have a glance at the yaml file, protect-kernel-defaults is set to false.

**Comment by catherineluse** [comment]
> We should have this checked if a CIS Profile was selected

I'm confused about the steps to reproduce. Where did they select a CIS profile? As far as I know, selecting a CIS profile is not part of cluster provisioning.

**Comment by gaktive** [comment]
Upon chatting with @catherineluse, and referring to https://docs.ranchermanager.rancher.io/reference-guides/rancher-security/rancher-v2.6-hardening-guides/rke2-hardening-guide-with-cis-v1.6-benchmark, the steps to reproduce this follow the RKE2 Custom Template file to generate this.

It sounds like this may be an issue whereby the actual questions.yaml file in the RKE2 repo needs to be updated.

**Comment by Josh-Diamond** [comment]
Ticket #7331 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-830fa58ccecfb8915fc54862a9b19fdfeb2c0f8c-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | `Default behavior for clusters w/o CIS profile selected expected to set "protect-kernel-defaults" to FALSE` | ✅ |
| 2. | `Selecting a CIS profile sets "protect-kernel-defaults" to TRUE` | ✅ |
| 3. | `Setting the CIS profile to "None" sets "protect-kernel-defaults" to FALSE` | ✅ |

---

Scenario 1:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream RKE2 cluster w/o selecting CIS Profile
3. View YAML and confirm "protect-kernel-defaults" is set to `false`
4. Verified - "protect-kernel-defaults" is set to `false`

---

Scenario 2:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream RKE2 cluster, selecting CIS Profile
3. View YAML and confirm "protect-kernel-defaults" is set to `true`
4. Verified - "protect-kernel-defaults" is set to `true`

---

Scenario 3:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream RKE2 cluster, selecting `None` for CIS Profile
3. View YAML and confirm "protect-kernel-defaults" is set to `false`
4. Verified - "protect-kernel-defaults" is set to `false`
