### ISSUE TITLE
[@rancher/components] Assert that package builds in CI

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#7344]
It looks like builds for `@rancher/components` regressed with https://github.com/rancher/dashboard/commit/d709dcc9db06b2a846fa254e81b1774583480757#diff-1a3646597f62985362f87700c4a0752e51a8868f3849e97ba504965a44f53113 and this wasn't identified until we attempted to build and release a new component. 

It makes sense to build `@rancher/components` in CI to assert that we don't revert basic behavior in the future. 

We should be able to modify the ci script to include a line for `yarn build:lib`

https://github.com/rancher/dashboard/blob/2c22aadef43f60a30bbbbefa9962bc2c29dd7be5/scripts/ci

See also rancher/dashboard#7327

## edit
Also add a CI step to identify `lint` errors.

**Comment by cnotv** [comment]
That script it's not used anymore on a daily basis, it has been moved to the test workflow.
You should be able to add another job for that workflow to test if the build would break or not, just as we do for the E2E
