### ISSUE TITLE
Bringing a side menu in a small browser window, scroll bars appear

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7349]
@nwmac was working on something and noticed:
> If the vertical height is not big enough for the full side menu, it does not scroll, so the whole window scrolls... this used to be fine?

@cnotv noted that the side menu is absolute inside `.dashboard-content` so it looks relative.

**Comment by cnotv** [comment]
I also corrected myself as well 😅 
The height should set to max 100vh, as you want to do stay within screen size. It should then allow overflow to auto value.

There's an issue with the top part fo the navigation, as it conceptually should stick.

**Comment by Josh-Diamond** [comment]
Ticket #7349 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-4f6a03e7c9e5f1d2272b113bb9baf2b15b5d319c-head`:
1. Fresh install of rancher `v2.7-head`
2. Adjust browser size to various viewport dimensions w/ side-menu opened
3. Verified: 
    - Menu is fully responsive to all viewport sizes 
    - If viewport height is restricted enough, vertical scroll bars allow you to navigate to all options via side-menu
    - Functioning as expected

Screenshots:

`Unrestricted Viewport Dimensions`
<img width="281" alt="Screen Shot 2022-11-09 at 11 15 18 AM" src="https://user-images.githubusercontent.com/46494969/200909601-be00ef33-86df-49aa-989f-7fb5abd1a21d.png">

`Restricted Viewport Height`
<img width="283" alt="Screen Shot 2022-11-09 at 11 15 47 AM" src="https://user-images.githubusercontent.com/46494969/200909586-389a19ed-f2fb-4759-b5e8-fd5d8916f289.png">
