### ISSUE TITLE
What's New in 2.7.0: add k3s provisioning is GA

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7361]
Need to add "k3s provisioning going GA" as a new thing in 2.7.0. This will appear in What's New.

**Comment by gaktive** [comment]
PR: https://github.com/rancher/dashboard/pull/7363

**Comment by gaktive** [comment]
If you want to wait, #7376 has additional wording updates.

**Comment by Josh-Diamond** [comment]
Ticket #7361 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-4f6a03e7c9e5f1d2272b113bb9baf2b15b5d319c-head`:
1. Fresh install of rancher `v2.7-head`
2. From `Home`, Navigate to `What's New in 2.7`
3. Verified - Under `New in 2.7.0`, k3s provisioning is GA message is seen, and accurate

Screenshot:
<img width="1485" alt="Screen Shot 2022-11-09 at 11 33 25 AM" src="https://user-images.githubusercontent.com/46494969/200912624-16010140-899b-434b-bdf7-2f2f74f1861c.png">
