### ISSUE TITLE
Breakout `ui-banners` into separate CRDs  (Headers/footers, consent-banner)

### ISSUE THREAD

**Issue by bgulla** [rancher/dashboard#7366]
Internal Reference: SURE-7619

We currently shove a bunch of data into the `ui-banners` CRD. Rancher Government would like to apply changes to the header and footer (text, colors) independently of the `bannerConsent` value. 

Ideally, we break these out as separate resources that can be updated independently.

```json
{"loginError":{"message":"","showMessage":"false"},"bannerHeader":{"background":"#4f924f","color":"#fff","textAlignment":"center","fontWeight":true,"fontStyle":null,"fontSize":"14px","textDecoration":null,"text":"HEADER TEXT GOES HERE"},"bannerFooter":{"background":"#4f924f","color":"#fff","textAlignment":"center","fontWeight":true,"fontStyle":null,"fontSize":"14px","textDecoration":null,"text":"FOOTER TEXT GOES HERE"},"bannerConsent":{"background":"#27292e","color":"#fff","textAlignment":"center","fontWeight":null,"fontStyle":null,"fontSize":"14px","textDecoration":null,"text":" LONGF ORM LOGIN Consent BANNER TEXT GOES HERE","button":"Accept"},"showHeader":"true","showFooter":"true","showConsent":"true"}
```

**Comment by nwmac** [comment]
Suggest we add:

`ui-banner-header` and `ui-header-footer`

The UI will use these if they are defined, otherwise it will continue to use the single banner setting.

This allows someone to deploy seperate CRs for the banner - this will then be used by the UI and editable in the UI. Existing deployments and the default will still be to use the single, combined resource.

**Comment by bgulla** [comment]
that would work for us @nwmac .

**Comment by nwmac** [comment]
This will require a small backend change to allow the new individual settings to be retrievable by an unauthenticated user.

**Comment by nwmac** [comment]
Created backend issue https://github.com/rancher/rancher/issues/44439

**Comment by nwmac** [comment]
PR for backend changed: https://github.com/rancher/rancher/pull/45528

**Comment by yonasberhe23** [comment]
e2e tests are sufficient. moving to done
