### ISSUE TITLE
unable to create cluster from rke2 template as standard user

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#7372]
**Setup**
- Rancher version: v2.7.0-rc9
- Browser type & version: chrome

**Describe the bug**

as a standard user, when creating a cluster from an rke2 template the user is presented with a blank page. 

**To Reproduce**

* (as admin) add an rke2 cluster template repository (i.e. the [example we have in gh](https://github.com/rancher/cluster-template-examples.git))
* (as standard user) go to cluster management -> create -> select a rke2 template 

**Result**
user is presented with a blank page 

**Expected Result**

user should be able to configure the template and create from it as a standard user

**Screenshots**

<img width="1789" alt="Screen Shot 2022-11-08 at 11 23 54 AM" src="https://user-images.githubusercontent.com/16691014/200656402-08d3ae4c-8c10-4994-9640-e5ed974732dc.png">

**Additional context**

an admin user can correctly configure the template and does not hit this issue
this is a regression, as it is not an issue on 2.6.9

**Comment by mantis-toboggan-md** [comment]
This was probably introduced by the custom registry ui work. It looks like the chart install page expects `currentCluster` to be defined, but in this scenario we're using the blank cluster, `dashboard/c/_/apps/charts/install...`

**Comment by gaktive** [comment]
From investigation from @MbolotSuse:

> To add more detail, this appears to be caused by a 403 on getting the index.json for that page. I see the following associated error: `"message": "services \"http:ui-plugin-operator:80\" is forbidden: User \"u-twb8k\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"cattle-ui-plugin-system\"", .`

From @mantis-toboggan-md:

> This does look like a UI issue, just going off a look over the chart install component, it appears to assume that the user is connected to a cluster/installing an app within the cluster explorer context, while in the scenario outlined above we’re using the blank cluster workaround so this section doesn’t work:
https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/apps/charts/install.vue#L765-L768
could be other problems going on with that page too [...]

**Comment by slickwarren** [comment]
tested on v2.7-head (4f6a03e):
* cluster management -> create -> select a rke2 template -- PASS
