### ISSUE TITLE
[Bug] [Monitoring V2] Cannot add Email receivers

### ISSUE THREAD

**Issue by Tejeev** [rancher/dashboard#7375]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
In this case, the steps we followed were to:
1. Deploy a fresh Rancher v2.5.1 cluster
2. Enable monitoring v2
3. Upgrade Rancher to v2.5.3
4. Attempt to add an email receiver for notifications

**Result:**
Creation fails with `Cannot read property 'data' of undefined`
![image](https://user-images.githubusercontent.com/8906089/103965175-161cfa80-5155-11eb-91ae-c82fa77e7f71.png)

Workaround is to manually add the receiver to the `alertmanager-rancher-monitoring-alertmanager` secret.
Alerts will work but the receiver and routes will not show in the UI.

We have a HAR capture and a copy of the manually created secret (please DM me internally in Slack)

**Other details that may be helpful:**
We have seen this in another cluster where they were able to workaround by:
1. Filling in the fields to create a Reciever
2. Clicking on Edit as YAML
3. Copying the YAML and manually applying

For them the fix was to disable and re-enable monitoring.  It may be worth noting they had upgraded from v2.4.x

gz#14160

gz#15969

**Comment by gaktive** [comment]
Need to confirm what the state is in 2.6.9 (and potentially 2.7.0).

**Comment by MKlimuszka** [comment]
Reach out to @geethub97 if you need input from backend.

**Comment by catherineluse** [comment]
I tried to reproduce this issue in v2.7.0, but couldn't. I tried both the older email Receiver creation form (in which the username and password are given as plain text) and the newer receiver creation form for the AlertmanagerConfig resource (in which the password is selected as a secret and secret key).

**Comment by catherineluse** [comment]
I'm moving this to To Test so that QA can confirm that it's no longer an issue.

**Comment by ronhorton** [comment]
**not reproducible**
1. created 2.6-head rancher HA
2. installed rancher-monitoring 101.0.0+up19.0.3
3. added email receiver

`confirmed no issue in 2.6.9 adding email receiver; also unable to reproduce in 2.7.0 per https://github.com/rancher/dashboard/issues/7375#issuecomment-1322890442`
