### ISSUE TITLE
Update k3s section in What's New

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7376]
From @leflambeur:

### k3s provisioning is GA (x86 Only)

- Provisioning K3s clusters on x86 clusters has graduated to GA! The fully compliant Kubernetes distribution is simplified, secure and at less than 60mb is perfect for Edge.

Based on branching, need to update both `master` and `release-2.7.0`

**Comment by gaktive** [comment]
PR: https://github.com/rancher/dashboard/pull/7377

**Comment by gaktive** [comment]
PR for release-2.7.0 branch: https://github.com/rancher/dashboard/pull/7381

**Comment by Josh-Diamond** [comment]
Ticket #7376 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-4f6a03e7c9e5f1d2272b113bb9baf2b15b5d319c-head`:
1. Fresh install of rancher `v2.7-head`
2. From `Home`, Navigate to `What's New in 2.7`
3. Verified - Under `New in 2.7.0`, k3s provisioning is GA message is seen, and accurate

Screenshot:
<img width="1168" alt="Screen Shot 2022-11-09 at 11 26 48 AM" src="https://user-images.githubusercontent.com/46494969/200912134-a0eb00f6-6f97-46d3-80fd-0829099887cf.png">
