### ISSUE TITLE
Modify the container name, the focus will automatically focus on other tabs

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#7404]
**Setup**
- Rancher version: v2.6.9
- Browser type & version: 107.0.5304.87

**Describe the bug**

Modify the container name, the focus will automatically focus on other tabs

**To Reproduce**

1. Create an arbitrary workload
2. Modify the container name

**Result**
The focus will automatically focus on other tabs

**Screenshots**

![sidecar5](https://user-images.githubusercontent.com/19684717/201050132-23ef7921-bcd9-4238-976e-271e8b00844f.gif)

**Comment by richard-cox** [comment]
This works on 2.7.0, so there'll be a fix somewhere that needs backporting

**Comment by richard-cox** [comment]
Closing in favour of https://github.com/rancher/dashboard/issues/7505
