### ISSUE TITLE
When the container names are the same, only one of them will be displayed on the UI

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#7405]
**Setup**
- Rancher version: v2.6.9
- Browser type & version: 107.0.5304.87

**Describe the bug**

When the container names are the same, only one of them will be displayed on the UI. But in yaml you can see that there are two containers with the same name

**To Reproduce**

1. Create workload
2. Click the `Add container` button to add a new container. At this point, I created two containers, namely: `container-0` and `container-1`
3. Change the container name of container-1 to `container-0`, so that the two containers have the same name

**Result**
When the container names are the same, only `container-0` will be displayed on the UI. From the yaml view, you can see that there are two containers called `container-0`

**Screenshots**

![sidecar6](https://user-images.githubusercontent.com/19684717/201056386-1bb1c5c9-b724-42af-ac07-c58e08831578.gif)

**Comment by richard-cox** [comment]
I don't see the same behaviour on 2.7.0 (both tabs are highlighted, changing the name of the second tab takes user to first tab)

This will need fixing, and possibly backporting to 2.6.x

**Comment by catherineluse** [comment]
Moving this into the review column since there is a PR to fix it https://github.com/rancher/dashboard/pull/7400

**Comment by Shavindra** [comment]
User should not be allowed to have 2 containers with same name right? So fix should be a validation to check if container name already exists?

**Comment by markusewalker** [comment]
@richard-cox @Shavindra following up on this issue, can you confirm that the fix of this issue includes a validation to check if the container name already exists? IMO, the fix here should be to not allow non-unique container names to occur.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision an RKE1 downstream cluster. Create a deployment with two containers of the same name, validate I am unable to|
|2|As a standard user, provision an RKE1 downstream cluster. Create a deployment with two containers of different name and validate they both show. Edit the deployment and change the second container name to match the first container name, validate I am unable to|
|3|As a standard user, provision an RKE1 downstream cluster. Create a deployment with two container of different names and validate they both show. Edit the deployment and change the second container name to a new, unique container name, validate I am able to|

**Comment by gaktive** [comment]
#7400 merged so this is ready to test

**Comment by markusewalker** [comment]
Validated this issue in `v2.7-head` https://github.com/rancher/rancher/commit/a352c871a151f093a1f15898951317e177445c79.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/a352c871a151f093a1f15898951317e177445c79
- Browser: Chrome

**QA TEST PLAN**

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision an RKE1 downstream cluster. Create a deployment with two containers of the same name, validate I am unable to|:white_check_mark:|
|2|As a standard user, provision an RKE1 downstream cluster. Create a deployment with two containers of different name and validate they both show. Edit the deployment and change the second container name to match the first container name, validate I am unable to|:white_check_mark:|
|3|As a standard user, provision an RKE1 downstream cluster. Create a deployment with two container of different names and validate they both show. Edit the deployment and change the second container name to a new, unique container name, validate I am able to|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, navigated to Cluster Management > Create.
2. Provisioned a downstream RKE1 node driver cluster; validated that the cluster and nodes come up as `Active` in Cluster Management and Cluster Explorer.
3. Navigated to Cluster Explorer > cluster > Workloads.
4. Created a deployment with two containers with the same name `testdeploy` with container image `nginx:latest`.
5. Attempted to create and I received the following message:
![image](https://user-images.githubusercontent.com/52591819/214633259-c2083a7e-12cf-4d39-95f4-54c47d94da7c.png)
______________
**Scenario 2**
1. Repeated scenario 1, but ensured that I created a deployment with two containers with the following names: `testdeploy1` and `testdeploy2` with container image `nginx:latest` and `tomcat:latest`, respectively.
2. Validated that I was able to successfully create my deployment and that it is an state of `Active`.
3. Edited the deployment and attempted to change `testdeploy2` name to `testdeploy1`; validated that I get thrown an error:
![image](https://user-images.githubusercontent.com/52591819/214633192-26de11c3-15c9-4bbf-9eac-9565e59efd52.png) 
_____________
**Scenario 3**
1. Repeated scenario 2, but ensured that when I attempted to change `testdeploy2`, I changed the name to `testdeploy3` instead.
     - This way, I have two container names of `testdeploy1` and `testdeploy3`.
2. Validated that I was able to successfully update my deployment and that it remains in a state of `Active`.
