### ISSUE TITLE
Solve issue with flaky tests for branding

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#7406]
# Description

Solve issue with flaky tests related to branding runs.

![Screenshot 2023-05-23 at 08 43 29](https://github.com/rancher/dashboard/assets/5009481/75a019c1-687b-4300-90e4-b699ad026f20)

![Screenshot 2023-05-23 at 08 43 46](https://github.com/rancher/dashboard/assets/5009481/5cd4a86b-8f82-447c-a272-efb015460b5b)

**Comment by gaktive** [comment]
@nwmac had done some improvements here in the past. @cnotv can you check to see if this is better and we can re-enable some of the tests we had disabled here?

**Comment by cnotv** [comment]
Still failing, the edit is from 2 weeks ago.

**Comment by gaktive** [comment]
Could be caused by https://github.com/rancher/dashboard/issues/9444

**Comment by richard-cox** [comment]
I've looked over the last ~10 runs and `branding.spec` now doesn't show any flakyness
