### ISSUE TITLE
Remove getting started docs out of UI

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7413]
Allows these to be managed by docs.

**Comment by gaktive** [comment]
@mantis-toboggan-md to co-ordinate with @catherineluse on what's required on the docs side. We also need to update the overall release checklist with @Jono-SUSE-Rancher as we do this.

**Comment by gaktive** [comment]
Some additional feedback on formatting arose in https://github.com/rancher/dashboard/issues/7794

**Comment by gaktive** [comment]
We can sync with @btat about the URL pattern to use for our links.

**Comment by gaktive** [comment]
Docs doesn't have a page yet that replaces the getting started material. https://github.com/rancher/rancher-docs/issues/726 was filed to see what to do to organize their existing bits into a single resource. This may be more of a Q4 thing.

For release notes, https://ranchermanager.docs.rancher.com/versions should suffice for now. We can look at specific version links later (i.e, if you have 2.7.5 installed, the link points to the 2.7.5 release notes).

**Comment by mantis-toboggan-md** [comment]
Release notes change is tracked here now: https://github.com/rancher/dashboard/issues/9332

**Comment by mantis-toboggan-md** [comment]
This is actually waiting on a _docs_ PR https://github.com/rancher/rancher-docs/pull/739 but I'm moving the issue to 'backend blocked' to track the fact that we're waiting on something outside the UI team

**Comment by gaktive** [comment]
Checking with Docs on status. The PR shows recent activity as part of a review at least.
