### ISSUE TITLE
Renaming the cluster raise an error, but still works

### ISSUE THREAD

**Issue by Evantage-WS** [rancher/dashboard#7419]
**Setup**
- Rancher version: 2.6.9
- Browser type & version: Chrome Version 107.0.5304.110

**Describe the bug**
When renaming the local cluster to another name, the error "There must be at least one member with the Owner role"

**To Reproduce**
Cluster Management -> Edit Config -> change local to i.e. rancher -> Hit the save button

**Result**
Error is shown, but after clicking on Cancel the name has been changed

**Expected Result**
No error and closing of the window

**Screenshots**
![Screenshot 2022-11-11 at 16 39 40](https://user-images.githubusercontent.com/59507751/201375889-ce8e2ce9-6733-47d3-9f8a-80b142965692.png)
![Screenshot 2022-11-11 at 16 39 59](https://user-images.githubusercontent.com/59507751/201375893-acc9c006-187e-40bd-9a43-c3048877c952.png)
![Screenshot 2022-11-11 at 16 40 09](https://user-images.githubusercontent.com/59507751/201375896-724a0f25-fa7d-416d-a4e2-a1177d208a5b.png)
![Screenshot 2022-11-11 at 16 40 19](https://user-images.githubusercontent.com/59507751/201375898-67c16029-c9aa-4e39-b73a-715557745a15.png)
![Screenshot 2022-11-11 at 16 40 32](https://user-images.githubusercontent.com/59507751/201375900-62158f2a-3cfb-4380-9e41-53d1ddb9d313.png)

**Comment by richard-cox** [comment]
Thanks for raising this issue, however it's covered by https://github.com/rancher/dashboard/issues/4457

**Comment by Evantage-WS** [comment]
Great, I searched already for rename/renaming before enrtering this issue, didn't hit this one. Thanks!
