### ISSUE TITLE
When there are multiple lists on a page list bulk actions do not initially show

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7421]
**Setup**
- Rancher version: 2.7.0

**Describe the bug**
- When there are multiple lists on a page, like the cluster detail page, the initial view of the page does not show the bulk action
- User has to select a row for them to be visible

**To Reproduce**
- Cluster Management --> `local cluster`

**Result**
- The `Machine Pools` tab is shown but the `Download YAML` bulk action button is not visible

**Expected Result**
- `Download YAML` bulk action button should be visible and disabled

**Screenshots**
On First Visit
![image](https://user-images.githubusercontent.com/18697775/201413057-2930ac64-9da4-4531-b289-72355d590928.png)

After selecting a row
![image](https://user-images.githubusercontent.com/18697775/201413085-46795078-e729-4a90-aff3-58a2820f48e2.png)

**Comment by anupama2501** [comment]
Reproduced the issue on v2.7.0
1. Install rancher server and created a few downstream clusters
2. From cluster management page >> Local cluster >> download button yaml is. not present
3. Select all machine pools and the download button then appears.

<img width="300" alt="2023-01-05_15-53-37" src="https://user-images.githubusercontent.com/38144301/210902175-eb1dc3c9-0cf7-4570-b551-881cd6818757.png">


Installed rancher on v2.7.2-rc1
2. From cluster management page >> Local cluster >> download button yaml is present even without selecting any of the pools
3. Navigate to k3s downstream node driver cluster >> verified the bulk action button is visible
4. Verified the same for RKE2 node driver and RKE1 node driver
5. Verified by downloading yaml by selecting all machine pools - works as expected.
<img width="453" alt="2023-01-05_15-57-47" src="https://user-images.githubusercontent.com/38144301/210902563-64965060-9678-4254-9fb8-7016b4f363a7.png">
