### ISSUE TITLE
Fix issue with advanced filtering

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#7452]
- Fix issue with advanced filtering where we might look for labels on items which don't have any labels associated causing a blocking error

**QA testing**
As for this feature is only available in Elemental (OS management) it's better to be covered by QA for the elemental team @juadk 

If there something to be tested, it's just to make sure the simple filtering of list views is working properly from the POV of `rancher/dashboard`

**Comment by aalves08** [comment]
For reference, issue tracked on `elemental-ui` repo also: https://github.com/rancher/elemental-ui/issues/41

**Comment by sowmyav27** [comment]
Since this issue - https://github.com/rancher/elemental-ui/issues/41 is closed, closing this issue
