### ISSUE TITLE
OPA - After clicking Enable in the Dashboard I do not get redirected to the OPA Overview

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#746]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher (Used for testing: `v2.4-head` commit d0a55f080)
   - dashboard index points to `https://releases.rancher.com/dashboard/latest/index.html`
2. Create a cluster (Cloud or Custom)
3. Navigate to Try Dashboard
4. Click OPA Gatekeeper from the Left Menu in the Cluster section.
5. I see the button getting in non-clickable status then to clickable

**Result:**

I do not get the page refreshed or my browser redirected to the OPA Gatekeeper Overview page, After enabling I had to refresh to be able to see it

Here just after clicking the button is disabled and then enabled:

![Screen Shot 2020-06-09 at 11 28 02 AM](https://user-images.githubusercontent.com/27659/84186215-129d8580-aa45-11ea-9cd3-fd51242e3c4b.png)

Refreshing the page:

![Screen Shot 2020-06-09 at 11 28 15 AM](https://user-images.githubusercontent.com/27659/84186229-1af5c080-aa45-11ea-809d-eb4396a22caf.png)

**Environment information**
- Rancher version: 
  - `2.4-head (05/28/2020)` d0a55f080 
- Installation option: Single

**Comment by izaac** [comment]
I also not get redirected to the OPA Gatekeeper Description page (where the Customize and Enable buttons are located) when I Disable OPA.

**Comment by westlywright** [comment]
I believe there are a couple issues happening here. One of them is UI related, the others I do not believe to be UI related.

First the errors are not showing when the enable action fails. Currently there is a timeout of 300 seconds that the UI waits for the app to get the condition `Deployed: True`, if that fails the button should error and you should see a message about the failure. That is not happening. I will issue a fix to ensure the ui displays the error.

I believe there are some backend issues here as well. On v2.4.5-rc7 I was able to reproduce this easily. The backend never seems to send the condition update through the websockets, on master this is happening fine. When I run the `release-2.4` dashboard UI branch locally against a `master-head` backend I do not see the issues and gatekeeper is enabled fine.  There must be some change in master that isn't in 2.4. @prachidamle should probably investigate this why these messages are not being sent. @deniseschannon I am not sure how Steve is being put into 2.4 Rancher release so it may be resolved when those get synced.

**Comment by vincent99** [comment]
This is not going to be relevant anymore, deploying an app is not going to bring you into it.
