### ISSUE TITLE
Create @rancher/icons package for npm

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#7477]
# Describe

From the existing [`rancher/icon` repository](https://github.com/rancher/icons) update CI to publish the build on NPM.

## Context

We currently import the library as git reference, while instead we want to include under the scope `@rancher` also the icons.

**Comment by nwmac** [comment]
As part of this work, we should also update Dashboard to reference icons via the npm package rather than by a GitHub reference

**Comment by cnotv** [comment]
It's also worth mentioning that something already exists in NPM
https://www.npmjs.com/package/rancher-icons

**Comment by cnotv** [comment]
@nwmac the idea is to have separated implementations of this, as you cannot actually add the library to `rancher/dashboard` till you merge the changes in `rancher/icons`. The aim is to be able to do both in separated instances.
It would not be possible to do an actual review in that case.

What would you suggest otherwise as process for the review?

**Comment by nwmac** [comment]
That's an old package - I think we'd publish as @rancher/icons - I don't think we have anyone who has access to that package.

We can have 2 PRs - 1 for the changes to publish, 1 for dashboard changes - both linked to fix this issue. The icons PR can be reviewed first, the icon package reviewed and then the dashboard PR reviewed.

**Comment by cnotv** [comment]
Deal.
