### ISSUE TITLE
Node List/Details - Do not show Delete action for nodes in the HA local cluster

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#748]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard
2. Navigate to Nodes
3. In the Node list check select nodes
4. In the Node details click in the three dots button

**Result:**

Option for delete is shown for local cluster nodes in HA setups.

![Screen Shot 2020-06-09 at 2 43 03 PM](https://user-images.githubusercontent.com/27659/84204517-3621f980-aa60-11ea-838e-b638e84992ba.png)
![Screen Shot 2020-06-09 at 2 45 12 PM](https://user-images.githubusercontent.com/27659/84204519-38845380-aa60-11ea-9c79-2228351cd3c1.png)

**Environment information**
- Rancher version: 
  - `master-head (06/09/2020)` 78b2f4dc5
- Installation option (single install/HA): HA
- Cluster type: Custom

Related to: https://github.com/rancher/dashboard/issues/241

**Comment by codyrancher** [comment]
This is expected behavior. 

Darren:
> Norman we probably didn't allow it because local is a bit special.  But in 2.5 we need to allow it.

**Comment by izaac** [comment]
Rancher version `master-head (07/24/2020)` _80542c31b_ k8s HA install.
dashboard-index -> `latest`

Closing as this is intentional for `2.5`
