### ISSUE TITLE
Extension was able to override cluster provisioning pages

### ISSUE THREAD

**Issue by agracey** [rancher/dashboard#7485]
**Setup**
- Rancher version: 2.7.0
- Browser type & version: Chromium

**Describe the bug**
When running Rancher 2.7.0 with the Elemental extension enabled, I noticed that the cluster provisioning page was not the latest version.

**To Reproduce**
- Install Rancher 2.7.0
- Install the Elemental extension 0.1.2 from https://github.com/rancher/elemental-ui.git 
- Go to Cluster Management
- Click Create
- Click Custom
- Switch Kubernetes Versions to a version of k3s

**Result**
It looks like k3s is still in tech preview because the page is overridden by the extension

**Expected Result**
Extension(s) should be tighter scoped

**Screenshots**
![image](https://user-images.githubusercontent.com/442274/202515057-7c918ac3-cc80-4a52-a3ae-44fa65d4e836.png)

**Comment by agracey** [comment]
Not sure I know how to name this issue so it's clear...

**Comment by aalves08** [comment]
@agracey that's fine. Thanks for the detailed description.

The fixed has been applied on the `elemental-ui` repo: https://github.com/rancher/elemental-ui/issues/49 and is now to be tested 🙏

**Comment by aalves08** [comment]
Will be closed based on https://github.com/rancher/elemental-ui/issues/49
