### ISSUE TITLE
Track automated test progress

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7489]
Internal feature reference: SURE-5055
With some connection to rancher/dashboard#7488

In order to improve the test automation of the UI, we need to track our automated test progress. This means recording the number of tests we have and the coverage in place.

Details TK: cc @nwmac

**Comment by cnotv** [comment]
We have already coverage set in place since August 2022 and there's an issue left hanging since October 2022, as you know:
https://github.com/rancher/dashboard/issues/7142

**Comment by richard-cox** [comment]
Matching JIRA has been closed
