### ISSUE TITLE
Node List Duplicate Internal/External IP

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#749]
Currently the Nodes list page can show the sameIP for both internal and external IP and even though it's accurate it looks a little odd.

We would like to change the way we show these IPs so that it looks a little better.

![image](https://user-images.githubusercontent.com/55104481/84208900-a2552b00-aa69-11ea-90a5-7eac8cf937b2.png)

**Comment by codyrancher** [comment]
@lvuch when you have time would you mind take a stab at making a mock that helps in this situation?

**Comment by deniseschannon** [comment]
What if we show a single IP when it's the same and only distinguish with the `/` when they are different?

@vincent99 Do you have any suggestions?

**Comment by vincent99** [comment]
Yes combine if the same was [my suggestion](https://github.com/rancher/dashboard/pull/725#issuecomment-639118456).

**Comment by deniseschannon** [comment]
Ok. let's go forward with that change @codyrancher

**Comment by izaac** [comment]
This Rancher backend issue is blocking some test scenarios:
https://github.com/rancher/rancher/issues/28150

**Comment by izaac** [comment]
Should we swap the order of `Internal <-> External`  in the `Internal/External IP` header column?

It rows in the node table show the External first when the node have both internal and external shown in the UI:

![Screen Shot 2020-08-11 at 11 15 29 AM](https://user-images.githubusercontent.com/27659/89933809-7ae32180-dbc4-11ea-878d-14045d98de8b.png)

@vincent99 @deniseschannon

**Comment by vincent99** [comment]
Yes

**Comment by izaac** [comment]
`master-head (08/10/2020)` _28ea6d4b1_


Cases covered of nodes with:

- Only Internal
- Both Internal and external IP
- Only External

Opened a separate issue for the Node list issue mentioned [here](https://github.com/rancher/dashboard/issues/749#issuecomment-672157414).
#1000

Separate issues for Internal address displayed in Node details
#1002
#1003
