### ISSUE TITLE
Small layout issue

### ISSUE THREAD

**Issue by scures** [rancher/dashboard#7491]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

After the merge of https://github.com/rancher/dashboard/pull/7409 the main header spacing is wrong (no margins below namespaces filter)

**To Reproduce**
Run the latest master.
**Result**
![image](https://user-images.githubusercontent.com/88777903/202669926-6714224c-85f9-43cd-9c24-2dfe0099fc95.png)

**Expected Result**

![image](https://user-images.githubusercontent.com/88777903/202670199-ea4b71a6-e63d-42b9-b246-d68fa9f7c7a0.png)

**Comment by nickwsuse** [comment]
`Verifed on v2.7-head Commit ID: 38979f8`

The formatting for the main header is back to normal and has the correct margins under the namespace filter.
