### ISSUE TITLE
Prevent pipelines to fail on warnings

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#7493]
# Description

Some pipelines fail for warning issues such like styling, while it should allowed.
E.g.: rancher/dashboard#7492

<img width="773" alt="Screenshot 2022-11-18 at 10 37 34" src="https://user-images.githubusercontent.com/5009481/202670899-fa6e42d9-4e14-4edd-8edb-771831e93e16.png">

**Comment by gaktive** [comment]
Leaving in Q2 for now but this ties in a conversation to have about what to about linting.

**Comment by cnotv** [comment]
This issue is not about linting at all. This is an issue with the pipeline that should just not fail because are warning.

**Comment by cnotv** [comment]
Issue seems related to configuration reporting `ESLint found too many warnings (maximum: 0).`.

**Comment by cnotv** [comment]
Since we don't want tests to fail on warning, I guess we don't want also linting issue to fail on warning as well, otherwise we'll end up in the same situation: https://github.com/rancher/dashboard/issues/8906
