### ISSUE TITLE
Custom colors are not applied to dropdowns correctly

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#7501]
![image.png](https://zube.io/files/rancher/cb21fd35fe52ad949f8482c63cb386b6-image.png)
![image.png](https://zube.io/files/rancher/0020f493a9cedc11da4e62262e2cf2d4-image.png)

**Comment by Josh-Diamond** [comment]
Ticket #7501 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-8062f1e3ab7bff870dfab195ff699a308644168a-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream cluster
3. Navigate to `Global Settings > Branding` and configure custom primary color and custom link color
4. Navigate to `Cluster Explorer` and observe colors on Namespace filter dropdown
5. Verified - custom colors as expected
6. Navigate to `Cluster Explorer > Workload > Deployment` and observe colors on Namespace field dropdown
7. Verified - custom colors as expected
8. Navigate to `Preferences` and change light/dark mode, then repeat steps 4-7
9. Verified - custom colors as expected w/ both light + dark mode

Screenshots

`Dark Mode`

<img width="290" alt="Screenshot 2023-01-06 at 12 25 20 PM" src="https://user-images.githubusercontent.com/46494969/211085652-b40b5f40-69aa-4ad3-a052-4860cd67e09d.png">

<img width="340" alt="Screenshot 2023-01-06 at 12 25 48 PM" src="https://user-images.githubusercontent.com/46494969/211085701-25f8418b-15ec-47e7-8361-0ce9d5693294.png">


`Light Mode`

<img width="293" alt="Screenshot 2023-01-06 at 12 26 10 PM" src="https://user-images.githubusercontent.com/46494969/211085742-4a91cdbc-0d63-4f3b-8803-2c16b706c0e4.png">

<img width="328" alt="Screenshot 2023-01-06 at 12 26 24 PM" src="https://user-images.githubusercontent.com/46494969/211085753-51da85e3-e21a-439a-bd78-8b14e48d37ed.png">
