### ISSUE TITLE
new UI not showing the correct Pods amounts (> 100%)

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7504]
Internal reference: SURE-5541
Reported in 2.6.9

Issue description:
New UI not showing the correct Pods amounts compared to old UI. Wrong Monitoring may cause wrong hardware resources available

Repro steps:

- open UI
-> select a cluster -> Nodes ->  select a node -> check PODS Used 
- open on same Rancher old UI by using /g in URL
-> select a cluster -> Nodes ->  select a node -> check PODS Used  

In this case
new UI: 178 of 110 / 162 %
old UI:     64 of 110 /   58 %

It looks like completed pods were also counted to the number of active pods in the new UI that may explain more than 100% active pods. That may explains why the UI shows a wrong amount of pods like 178 that is much higher than the total amount of pods 110.

**Comment by gaktive** [comment]
I need to check with those who worked on this since the older reported number may have been wrong in the first place.

**Comment by gaktive** [comment]
Somehow this didn't make it to QA. I'll check the Zube workflow here but I'll move this To Test.

**Comment by AndrewHoffmanQA** [comment]
retest passed

tested on HA local, 2.7head 8062f1e

retest steps: 

1. stoop up a local
2. navigate to -> select a cluster -> Nodes -> select a node -> check PODS Used
3. confirmed the **pod's used** reporting section only counts running pods and does not display metrics for completed pods/ 

![image.png](https://zube.io/files/rancher/e4929d2fd7001df7206127381e35ff52-image.png)
