### ISSUE TITLE
Change not saved when clicking "Use TLS" in AlertmanagerConfig

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/dashboard#7507]
**Setup**
- Rancher version:2.6.9
- Browser type & version: Chrome 105

**Describe the bug**

<img width="1906" alt="image" src="https://user-images.githubusercontent.com/16741882/202853488-e947e13a-6c67-4345-a299-e68216d62b46.png">
Click the corresponding button, it does not take effect

1、If use tls is not selected, the requireTLS: false parameter should be automatically generated
2、If the key is selected on the UI, saving will not take effect

**Comment by catherineluse** [comment]
In my setup, it looks like this issue has been fixed by https://github.com/rancher/dashboard/pull/7526.

**Comment by ronhorton** [comment]
this works now in `2.7-head commit id 48d1f8e`
it is broken in `2.6-head commit id 49e0eb1`
i'm going to request a backport

**Comment by catherineluse** [comment]
@ronhorton The backport bot isn't set up for the dashboard repo
