### ISSUE TITLE
Please Add GCP asia-northeast3 (South Korean) region to register / import GKE Cluster

### ISSUE THREAD

**Issue by charge-one** [rancher/dashboard#7509]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/111402648/202945325-b91cb899-7cd1-4bfa-8e46-283446995fc7.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nwmac** [comment]
Fixed in 2.7.5
