### ISSUE TITLE
Adding cluster-id label to new Prometheus Recording rules created from the UI. 

### ISSUE THREAD

**Issue by geethub97** [rancher/dashboard#7513]
When an alert fires it does not mention from which cluster it comes. I have made the change to include cluster_id to all existing alerts in the monitoring chart, but we need this change to be reflected on the UI for all new alerts. 

Related Ticket:  #https://github.com/rancher/rancher/issues/37128

Request: 
UI add another default label to all rules that to include the cluster_id. 

<img width="1243" alt="Screen Shot 2022-11-21 at 11 31 28 AM" src="https://user-images.githubusercontent.com/99695266/203142741-680997d4-d869-4f26-86cc-060dcc971f73.png">

**Comment by catherineluse** [comment]
@gaktive This should be a quick and easy change.

**Comment by prachidamle** [comment]
The backend ticket dependent on this addition has `2023-Q1-v2.7x` milestone, will it be possible to add in the UI change for the same?

**Comment by prachidamle** [comment]
@gaktive should this be assigned to @catherineluse or anyone?

**Comment by gaktive** [comment]
@prachidamle, we'll leave this open for the taking since if you need this in early, we'll need someone else to take care of this, unless it can wait.

**Comment by ronhorton** [comment]
@Tejeev this ticket is to include the cluster-id as support for the backend work to inlcude the cluster-id. the question regarding cluster-name being included is being tracked in a rancher/rancher ticket: https://github.com/rancher/rancher/issues/37128
the disposition of that ticket will indicate if there's another UI ticket to include that as default in the UI. 
ie, your quesiton is being addressed in the other ticket - this ticket was specifically to include the cluster-id field in the UI.

**Comment by ronhorton** [comment]
**Pass** verified in `v2.7-head commit ID 1f014b7`
`cluster-id` included as default included field in alert config UI
