### ISSUE TITLE
Allow setting ssh or https for repos in fleet

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#7518]
Fleet should allow for both ssh or https protocols for repos. 

Here's a simple mockup of how this should look:
![protocol-example](https://user-images.githubusercontent.com/617368/203329698-2db8aa6a-d652-43be-8d90-ae6a72d760b3.png)

**Comment by kwwii** [comment]
There was an error in the new drop-down input label - this provides clarity:
![fleet.png](https://zube.io/files/rancher/ba0b2413ea6e183a3cec6ba92dd15856-fleet.png)

The new protocol drop-down should have two values, "ssh" and "https". The default selection is https.

**Comment by Josh-Diamond** [comment]
Per discussion/decision made here:
https://github.com/rancher/dashboard/pull/7648#issuecomment-1399972370

This enhancement will consist of a banner being added, stating the following:
`Enter a valid HTTPS or SSH URL to a git repository.`

This enhancement is NOT expected to add `protocol` dropdown w/ `https` or `ssh` options.

---

Ticket #7518 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on Rancher `v2.7-17e5bb595bc7d6d9280dd40280b4e82b21903790-head`:
1. Fresh install of Rancher `v2.7-head`
2. Navigate to `Continuous Delivery > GitRepos > Add Repository`
3. Verified - `Enter a valid HTTPS or SSH URL to a git repository.` banner is present and accurate

Screenshot:
<img width="1602" alt="Screenshot 2023-02-13 at 11 56 30 AM" src="https://user-images.githubusercontent.com/46494969/218549002-e1704c65-4dd5-49d7-aa37-8653f5c10a71.png">
