### ISSUE TITLE
Add more centralized RBAC views

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#7522]
Currently, we have no centralized RBAC: cluster and project membership needs to be edited in specific clusters. Global RBAC is defined during user creation. Under the hood, all of these are using management cluster resources, so there's no need to force users to navigate into a cluster to edit roles. We should have some way of adding any user to any cluster from the global context. Some work around this has been done here: https://github.com/mantis-toboggan-md/dashboard/tree/debt-user-role-detail-edit

It is important to consider that some of our customers have an extraordinary number of role bindings, and a page loading and filtering through all of these likely wouldn't be performant. It looks like norman principals have a method for fetching role bindings relevant to that principal: this may provide a more performant way of building this feature.

**Comment by edenhernandez-suse** [comment]
Part of #8233

**Comment by kwwii** [comment]
We will address this issue in https://jira.suse.com/browse/UXUI-162 as part of the larger RBAC improvements
