### ISSUE TITLE
Unable to select Log Output

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#7524]
**Setup**
- Rancher version: 2.7-head
- Browser type & version: Firefox

**Describe the bug**

We are unable to select log output. This looks to be a regression introduced into v2.7-head. 

Log output can be selected in v2.6-head. 

**To Reproduce**

1. Create a deployment for a cluster
2. Navigate to Workload => Pods
3. Click on overflow menu for the deployment created in step 1 and select "View Logs"
4. Try to select text in console pane

**Result**

The pane attempts to drag and drop on click and drag.

**Expected Result**

Text is highlighted on click and drag.

**Screenshots**

### v2.6-head

![image](https://user-images.githubusercontent.com/835961/203423860-403ae739-020f-415c-91be-ecdb144b1d45.png)

### v2.7-head

No screenshot, text cannot be highlighted

**Additional context**

**Comment by gaktive** [comment]
@ronhorton just so you have visibility on the work on what you filed in #7722

**Comment by sowmyav27** [comment]
**On 2.7-head commit id: `65089ee`**

- User is able to select Log output
<img width="1306" alt="Screen Shot 2022-12-21 at 8 42 17 PM" src="https://user-images.githubusercontent.com/26032343/209057847-367ab234-f1a0-432c-a060-9a31a6da25fa.png">
