### ISSUE TITLE
[Bug] Rancher 2.6 is missing emptyDir from volume types.

### ISSUE THREAD

**Issue by ItsReddi** [rancher/dashboard#7533]
Duplicating issues:
https://github.com/rancher/rancher/issues/34638
https://github.com/rancher/rancher/issues/36760

**Setup**
- Rancher version: 2.6.*
- Browser type & version: FF, Chrome, latest

**Describe the bug**
If you create a deployment and want to add an emptyDir volume, you cannot select that from volume type dropdown
```
      volumes:
      - emptyDir: {}
        name: somename
```

**To Reproduce**
1. Create a deployment
2. Storage -> Add Volume
3. emptyDir not existent

1. Import a deployment with an empty dir
2. update the deployment
3. storage, you are unable to change the name of the emptyDir mount, no field available

**Result**

**Expected Result**
1. EmptyDir is available in dropdown
2. EmptyDir name can be changed on update of an deployment

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3147888/131963000-bc060ea9-5b95-4f21-a2fc-cdc602310daa.png)
![grafik](https://user-images.githubusercontent.com/3147888/131963125-9f7783f5-2abc-45ca-8b69-ac0be187c28b.png)

**Comment by richard-cox** [comment]
@ItsReddi Please can you fill out the issue template?

**Comment by richard-cox** [comment]
This will be resolve in 2.7 by https://github.com/rancher/dashboard/pull/7569 and will need backporting to 2.6 to resolve this issue

**Comment by nickwsuse** [comment]
`Verified on v2.6-head ID: 49e0eb1`

The emptyDir volume type is now available in the dropdown and a deployment can be created using the emptyDir volume type.
