### ISSUE TITLE
Rancher-backup isn't visible in Rancher Marketplace

### ISSUE THREAD

**Issue by Kenzi007220** [rancher/dashboard#7534]
Hi, I want to create Rancher backup for my cluster but can't find rancher-backup.

![image](https://user-images.githubusercontent.com/16799685/203567122-7f365ce9-ea93-49d3-8b31-bf5efec5b6d8.png)
![image](https://user-images.githubusercontent.com/16799685/203567205-9a461ea3-eac7-4eb0-be7f-1ee4d04a1ae3.png)

We are using physical servers and Rancher v2.5.16
Can please someone support me?
Thanks in advance

**Comment by richard-cox** [comment]
Please can you retest with the latest version (as of writing 2.8.3) and re-open if still applicable

The `Rancher Backups` chart will only be visible in the `local` / upstream cluster.
