### ISSUE TITLE
[pkg/components] lint errors

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#7536]
**Setup**
HEAD: commit e76126fd124542252a7a5023f12f9d0f5a25b459

**Describe the bug**

There are some lint errors that are blocking new` @rancher/components` releases (pkg/rancher-components)

**To Reproduce**

```
cd pkg/rancher-components/
yarn lint
```

**Result**
4 lint errors

**Expected Result**

No errors

**Comment by richard-cox** [comment]
@torchiaf Is there anything specific QA need to test, or can this issue be closed?

**Comment by torchiaf** [comment]
> @torchiaf Is there anything specific QA need to test, or can this issue be closed?

It can be closed, just fixed lint errors.
