### ISSUE TITLE
Pod Detail - Design Issue

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#754]
# Pod Detail
## Containers Table
- [ ] Text of badge is really small compared to other text in table

## Networking and  Security Tab
- [ ] Headers all different shades of grey and sizes.

# Security Tab
- [ ] The text isn't lined up with the items that would be in the second column. 

## Containers Component - View Mode (Used in Pod Detail when expanding the container row)

- [ ] Headers are all different sizes and font colors for most sections. 
- [ ] Need some kind of separation between the row line and the expanded section

**Comment by lvuch** [comment]
https://xd.adobe.com/view/5876b0de-de59-4988-8976-05d4c6ec7be8-0d25/

related: https://github.com/rancher/dashboard/issues/685

**Comment by deniseschannon** [comment]
Irrelevant as we need the new mock implemented: https://github.com/rancher/dashboard/issues/685#issuecomment-668816094
