### ISSUE TITLE
Cluster Mgmt list does not warn of inactive nodes

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7544]
Internal Reference: SURE-5607

In the old UI, inactive nodes are flagged on the clusters list:

![image](https://user-images.githubusercontent.com/1955897/203822534-25cb1653-b69d-4769-9921-9cf95b12fe74.png) 

In the new UI, they are not - this is really useful and should be added.

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: 216bb7f), I observed that the new "_red bell_" icon is presented for both RKE1 and RKE2 nodes when following the Steps to Reproduce. I also verified that the tooltip on the icons presents the correct node inactive information. However, I observed that on the Cluster Management page for the RKE2 cluster, the **_Machines_** bar and count is not updating correctly (see screenshot). Therefore I am Reopening this ticket to resolve that regression.
cc @nwmac 

**Steps to Reproduce:**

**RKE1:**

1. Create an RKE1 Cluster with two node pools
    - 2nd pool should have one worker node
2. Wait for cluster to be ready
3. Stop docker on the 2nd node by running `sudo systemctl stop docker`
4. Wait ~30 seconds
Go to both the Cluster Management cluster list and home pages and check that that the warning icon appears and that when you hover on it, the tooltip shows which node is not active

**RKE2**:

1. Create an RKE2 Cluster with two node pools
    - 2nd pool should have two worker nodes
2. Wait for cluster to be ready
3. Stop one of the the RKE2 nodes in the 2nd pool
4. Wait ~30 seconds
5. Go to both the Cluster Management cluster list and home pages and check that that the warning icon appears and that when you hover on it, the tooltip shows which node is not active

**`v2.6.7` for comparison:**
**Homepage:**
![image](https://user-images.githubusercontent.com/13294321/207405063-3605c6a2-a143-4fcd-9121-3d69beab1ba2.png)
**Cluster Management Page:**
![image](https://user-images.githubusercontent.com/13294321/207402670-584211ce-aa8c-4f93-af37-fabfdf877aba.png)

**`v2.7-head` (Commit ID: 216bb7f):**
**Homepage:**
**RKE1**:
![image](https://user-images.githubusercontent.com/13294321/207405284-0024b49f-fd09-461d-967e-776976775f0b.png)
**RKE2:**
![image](https://user-images.githubusercontent.com/13294321/207405336-34d15c7f-03a8-41e9-b70f-9a1269e7c544.png)


**Cluster Management Page:**
**RKE1 is correct:**
![image](https://user-images.githubusercontent.com/13294321/207402887-2c022181-16bc-4807-abac-ac6b29a4c2ca.png)
**RKE2 Icon and Tooltip is correct, but Machine bar and count are incorrect:**
![image](https://user-images.githubusercontent.com/13294321/207403047-7f51bb41-f3cf-4fda-86b8-9c0b1418db7d.png)

**Comment by nwmac** [comment]
@jameson-mcghee Can you open a new issue for this please? The inactive indicator is working correctly. The machine bar is a different issue that we need to look into - note that machines and nodes are different, so possibly the machine is considered okay, but the node is inactive.

**Comment by jameson-mcghee** [comment]
I have created Dashboard ticket [7740](https://github.com/rancher/dashboard/issues/7740) to account for the issue observed during testing. Based on the results of previous testing and the creation of the new ticket, I am closing this ticket as Done.
