### ISSUE TITLE
Make it easier to go from home page to Cluster Management

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7547]
Add a button so its less clicks and mouse moves.

**Comment by nickwsuse** [comment]
`Verifed on v2.7-head Commit ID: 38979f8`

There is now a `Manage` button on the home page that directs the user to the cluster management page. The normal navigation still works, and the button itself just links to the same URL you'd get if you went through the side nav.

![image](https://user-images.githubusercontent.com/107147272/205365334-6f59fd98-6e9a-4b67-84cf-7469fd63ba16.png)
