### ISSUE TITLE
Some input fields are broken on role creation screens

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7549]
The text input fields on the Role creation screen are broken - if you start typing, you just get [object inputEven] - see below 

Looks like the input fields were changed from LabelInput to plain input fields - LabelInout emits the value of the entire  input via the @input event - the input element just outputs each keypress - this is why it is broken. 

This PR is the cause: https://github.com/rancher/dashboard/pull/7258/files

![image](https://user-images.githubusercontent.com/1955897/203974223-5ff8553e-8b8d-4ca3-91ec-8a3570521775.png)

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As an admin user, create a global role and manually enter in fields|
|2|As an admin user, create a global role and select the dropdown menus that appear|

**Comment by markusewalker** [comment]
Tested this against `v2.7-head` https://github.com/rancher/rancher/commit/f7692f30cf47d00073cc41b879e0ff90fb0a68b0`

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/f7692f30cf47d00073cc41b879e0ff90fb0a68b0
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As an admin user, create a global role and manually enter in fields|:white_check_mark:|
|2|As an admin user, create a global role and select the dropdown menus that appear|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher, logged in as an admin user.
2. Navigated to Cluster Explorer > Users & Authentication > Roles > Create Global Role.
3. Manually entered in values in the `Grant Resources` tab and did not see the reported behavior:
![Nov-30-2022 08-54-30](https://user-images.githubusercontent.com/52591819/204860643-34f6f79f-815b-4f7c-a670-76b37ad84eca.gif)
__________
**Scenario 2**
1. Setup Rancher, logged in as an admin user.
2. Navigated to Cluster Explorer > Users & Authentication > Roles > Create Global Role.
3. Selected the dropdown values in the `Grant Resources` tab and did not see the reported behavior:
![Nov-30-2022 08-55-35](https://user-images.githubusercontent.com/52591819/204860573-345c4dee-c0b3-490b-ae45-13573a5e1734.gif)
