### ISSUE TITLE
Workloads Create/Edit page makes additional request to fetch all PVCs

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7550]
- For this resource type and page we now use the secondary resource loader which restricts requests to required resources to a namespace (see https://github.com/rancher/dashboard/pull/6860)
- For the workloads type this includes a request to fetch _namespaced_ PVCs
- It looks like there's been a regression and we also now fetch _all_ PVCs as well
- This probably came in with https://github.com/rancher/dashboard/pull/6860
  - ContainerMountPaths.vue
    - ```
        async fetch() {
          if ( this.$store.getters['cluster/schemaFor'](PVC) ) {
            this.pvcs = await this.$store.dispatch('cluster/findAll', { type: PVC });
          } else {
            this.pvcs = [];
          }
        },
      ```  
  - This came in before rancher/dashboard#6860, but chances are rancher/dashboard#6860 hadn't been rebased to contain it

**Comment by sowmyav27** [comment]
**On 2.6.9**

- Edit Workload.
- Network calls had this request also `https://<rancher-server>/k8s/clusters/c-q4s7w/v1/persistentvolumeclaims`

**On 2.7-head commit id: `65089ee`**

- Edit workload
- The above network call doesn't happen
