### ISSUE TITLE
Table alignment in Age column wrong

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#7560]
The header title Age is left aligned, the age itself is right aligned. Both should be left aligned.
![Screenshot 2022-11-28 at 14 29 48](https://user-images.githubusercontent.com/617368/204290239-9e6c4235-ae77-4f70-9f0b-b0ae7c123205.png)

**Comment by nickwsuse** [comment]
`Verified on v2.7-head 216bb7f`

I checked every table I know of that includes the `Age` column and they are all left aligned. All other columns I saw were left aligned as well.
