### ISSUE TITLE
Adjust reading of Counts from the Websocket to account for Steve Changes

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/dashboard#7566]
**Is your feature request related to a problem? Please describe.**
Changes to the backend were requested in https://github.com/rancher/rancher/issues/36681 and  https://github.com/rancher/rancher/issues/36682 to make the "counts" resource work in a more performative method. These changes are ready, but the current state of the UI results in buggy count values with the new backend changes.

In the previous state, the counts would send the count of every resource each time a websocket message was sent out. For example, in a cluster with deployments, pods, and service accounts, you would see a message like:

```json
{
"name": "resource.change",
"resourceType": "counts",
"data": {
    "id": "count",
    "type": "count",
    "links":  {
        "self": "$RANCHER_URL/v1/counts/count"
    },
    "counts": {
        "apps.deployments": {
             "summary": {
                "count": 3
             }
        },
        "pods": {
             "summary": {
                "count": 6
             }
        },
        "serviceAccount": {
             "summary": {
                "count": 3
             }
        }
    }
}
```
If a new service account was created, you would get the following message:

```json
{
"name": "resource.change",
"resourceType": "counts",
"data": {
    "id": "count",
    "type": "count",
    "links":  {
        "self": "$RANCHER_URL/v1/counts/count"
    },
    "counts": {
        "apps.deployments": {
             "summary": {
                "count": 3
             }
        },
        "pods": {
             "summary": {
                "count": 6
             }
        },
        "serviceAccount": {
             "summary": {
                "count": 4
             }
        }
    }
}
```

With the new changes, you will only get the full count for the resource that changed. In the above example, you will get the following message:

```json
{
"name": "resource.change",
"resourceType": "counts",
"data": {
    "id": "count",
    "type": "count",
    "links":  {
        "self": "$RANCHER_URL/v1/counts/count"
    },
    "counts": {
        "serviceAccount": {
             "summary": {
                "count": 4
             }
        }
    }
}
```

In the current state, the UI appears to take this as an indication that there are 0 pods and 0 deployments. The UI will need to account for the fact that the number of deployments/pods has not changed.

In addition to the above changes, these messages will no only be sent every 5 seconds. I do not believe that the UI has any issue handling this change at this time. 

**Describe the solution you'd like**
The UI should only replace the counts present in the count message and should take an update from the counts websocket as an update of every count that currently exists.

**Describe alternatives you've considered**
I do not have any good ideas on alternatives to the above solution.

**Additional context**
I can push an image with the changes if it would help for dev purposes.

**Comment by gaktive** [comment]
As a heads up, we need to be ahead of the backend changes since once their work is checked in, the UI will break.

**Comment by floatingman** [comment]
Followed validation steps from issue https://github.com/rancher/rancher/issues/36681 and observed the correct behaviour.
