### ISSUE TITLE
logs not shown in rancher ui rancher-agent:v2.6.8

### ISSUE THREAD

**Issue by snertsnert** [rancher/dashboard#7571]
**Setup**
- Rancher version: rancher-agent:v2.6.8
- Browser type & version: Google Chrome 

**Describe the bug**
no log is shown.

**To Reproduce**
install busybox:1.28

**Result**
nothing in log window
**Expected Result**
log should be shown
**Screenshots**

**Additional context**
All solutions found so far on the net do not work.
Download shows: failed to try resolving symlinks in path "/var/log/pods/tryout_counter_a0cfc33e-dfc5-4017-be69-a3fd5311a089/count/0.log": lstat /var/log/pods/tryout_counter_a0cfc33e-dfc5-4017-be69-a3fd5311a089/count/0.log: no such file or directory
![rancher_no_log](https://user-images.githubusercontent.com/80349563/204504598-5cdd297e-adfd-4ce0-9343-b67cefbf4255.png)

**Comment by richard-cox** [comment]
Please can you retest with the latest version (as of writing 2.8.3) and re-open if still applicable. If you manage to reproduce please can you provide clear steps to reproduce.

I did try with busybox, though this just gives a crashlloopbackoff. Using just a container of `nginx` the latest dashboard displays the logs
