### ISSUE TITLE
Rancher is missing emptyDir from volume types

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7572]
This is the 2.7 issue related to https://github.com/rancher/dashboard/issues/7533

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: c35f112`

The `Empty Dir` option is appearing as expected in the volume type selector, and you can successfully create an `Empty Dir` volume.

![image](https://user-images.githubusercontent.com/107147272/206286929-6e0ff637-7103-4b2d-836e-54e658ede0bc.png)

![image](https://user-images.githubusercontent.com/107147272/206287438-b923ebfb-680e-4988-a67f-8fcdf5590083.png)
