### ISSUE TITLE
Resource page create button shows last edited resource

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#758]
What kind of request is this:
Bug

Steps to reproduce (least amount of steps as possible):
On ingress page in dashboard:
Edit an ingress
Cancel
Click `Create`

Result:
The page will show the last edited ingress instead of creating a new ingress

Environment information:

Rancher version:
master-head b6a3dc962
Installation option (single install/HA): Single install
Cluster type: DO

**Comment by codyrancher** [comment]
This isn't related to ingress, it happens to all of the resources. As such, I'm going to rename it but I'll still work on it.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version b4067a3cb`
The resource page create button shows the create resource page every time.
