### ISSUE TITLE
OPA - Re-enabling OPA not always succeed.

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#759]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, navigate to dashboard
2. Navigate to OPA Gatekeeper
3. Click Enable
4. Wait for the App to be enabled and get redirected or refresh if stuck rancher/dashboard#746
5. Once OPA is enabled click in the 3 dots button and click in the Disable action
6. you should be redirected to the OPA Gatekeeper Description Page 
   - Once here the Customize and Enable buttons should be available again
7. Click Enable

**Result:**

![Screen Shot 2020-06-11 at 12 16 02 PM](https://user-images.githubusercontent.com/27659/84429626-5925e800-abdd-11ea-8a7e-83e668384249.png)

Rancher Logs show this error a few times:

`2020/06/11 19:14:55 [ERROR] error syncing 'gatekeeper-system/gatekeeper-controller-manager': handler workloadServiceGenerationController: cannot find app namespace in labels of gatekeeper-system, requeuing`

Other Information:

The `rancher-gatekeeper-operator` app is stuck in `Deploying` state.

![Screen Shot 2020-06-11 at 12 20 18 PM](https://user-images.githubusercontent.com/27659/84430107-0862bf00-abde-11ea-8ec8-047d647878ee.png)

In 2.4-head not getting redirected after clicking enable or disable is common but not in master (#746)

After some time the Customize and Enable button are clickable but I can't enable OPA again:

![Screen Shot 2020-06-11 at 12 22 46 PM](https://user-images.githubusercontent.com/27659/84430295-537cd200-abde-11ea-93ff-042eff8edba4.png)

**Environment information**
- Rancher version: 
  - `master-head (06/11/2020)` b89c3a572
- Installation option (single install/HA): Single
- Cluster type: RKE (DO)

**Comment by vincent99** [comment]
The API to deploy and remove charts, and the chart itself are totally different now, so this is not relevant anymore (though the new OPA chart might have different problems uninstalling or reinstalling)
