### ISSUE TITLE
[pkg/rancher-components] resolve linter warnings

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#7596]
# Description

`yarn lint:lib` returns some linter warnings during CI runs.

As mention to: https://github.com/rancher/dashboard/pull/7578#pullrequestreview-1198958523

**Comment by slickwarren** [comment]
@torchiaf is there anything for QA to validate for this ticket, or is this a dev-validate?

**Comment by torchiaf** [comment]
> @torchiaf is there anything for QA to validate for this ticket, or is this a dev-validate?

Correct! Sorry for missing label.
