### ISSUE TITLE
Delete within object view does not redirect to list view

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#761]
What kind of request is this:
Bug

Steps to reproduce (least amount of steps as possible):
In dashboard, create a workload.
Save
Click on the workload.
Delete from inside workload view
![Screen Shot 2020-06-11 at 2 34 44 PM](https://user-images.githubusercontent.com/57409052/84441699-1c63ec00-abf1-11ea-8075-dbba26d9aed0.png)

Result:
The user is not redirected to the list view.
Upon refresh, the resource is not found. Expected, as it has been deleted.
![Screen Shot 2020-06-11 at 2 35 09 PM](https://user-images.githubusercontent.com/57409052/84441616-fd655a00-abf0-11ea-949e-2d9ebb59c0b1.png)

This bug is also seen in most objects (ingress, secrets, ConfigMap, ect.)

Environment information:

Rancher version:
v2.4-head 4269f6124
Installation option (single install/HA): Single install
Cluster type: DO

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 8a032e73b`
User is redirected to list view after deleting from object view.

Reopening for a fix in 2.4-head

**Comment by deniseschannon** [comment]
@aaronRancher We don't cherry-pick or add new fixes into the 2.4 branch. When we sync 2.4, we bring over the whole `master` branch into `2.4`. You could test out this UI build on top of a 2.4 release to see if it's fixed.

**Comment by aaronRancher** [comment]
This fix is not seen in Rancher server `rancher\rancher:v2.4.6-rc4` or `rancher\rancher:v2.4-head` `version bf06dcf73`

**Comment by deniseschannon** [comment]
Did you update the UI to point to master on top of v2.4-head?

**Comment by aaronRancher** [comment]
My mistake. Fix is seen when 2.4 release points to master UI. Closing issue.
