### ISSUE TITLE
The "Continuous Delivery" doesn't show in the menu

### ISSUE THREAD

**Issue by zhaoyi0113** [rancher/dashboard#7616]
I am launching Rancher docker container on Mac system. Below is the command I used to launch Rancher container:

```
docker run -d --restart=unless-stopped  -p 80:80 -p 443:443 --privileged rancher/rancher:latest
```
The version of Rancher is `v2.7.0`.

I am able to login to the dashboard but there is Continuous Delivery in the menu. How can I use `fleet` as gitops to deploy resources to K8S cluster managed by Rancher?

![image](https://user-images.githubusercontent.com/3355579/205552664-26dc06d8-dd28-40bc-9eac-d269a2b6dc23.png)

**Comment by zhaoyi0113** [comment]
- Yes I logged in as admin.
- It never shows when I setup the container. I run the container with this command: 

```
docker run -d --restart=unless-stopped  -p 80:80 -p 443:443 --privileged rancher/rancher:latest

```

after that I grab the initial admin password from the container's log. Then it shows me the dashboard without this menu.
I am running the container on Mac M1 laptop.

**Comment by zhaoyi0113** [comment]
I just run a new container with this image: `rancher/rancher:v2.7-head`. 

```
docker run -d --restart=unless-stopped  -p 80:80 -p 443:443 --privileged rancher/rancher:v2.7-head
```

and then get the password by running `docker logs  83d3d44a24fb  2>&1 | grep "Bootstrap Password:"`

after login to the dashboard with admin, you can see the `Continuous Delivery` is not there:

![image](https://user-images.githubusercontent.com/3355579/205809724-6db7d13d-8264-48f6-a143-0b9e228ae5ac.png)

**Comment by richard-cox** [comment]
Can you confirm
- That the `fleet` Feature Flag is enabled (Burger menu/three lines top left --> `Global Settings` --> `Feature Flags` --> `fleet` row shows as `active`
- After logging in, go to the url `https://<your rancher url>/v1/schemas/fleet.cattle.io.gitrepo`. Does the successfully load and look roughly like below? 
  - ![image](https://user-images.githubusercontent.com/18697775/206433512-077565ab-b8e8-41e8-acfe-9db7b797f59d.png)

**Comment by zhaoyi0113** [comment]
yes the fleet flag is active:

![image](https://user-images.githubusercontent.com/3355579/206598697-c4d27af2-f8b3-4973-94f1-74cfdf7fff8d.png)

The URL `https://localhost/v1/schemas/fleet.cattle.io.gitrepo` doesn't work well, it shows me below:

```
{
"type": "error",
"links": { },
"code": "NotFound",
"message": "no such schema",
"status": 404
}
```

**Comment by richard-cox** [comment]
The dashboard relies on both those being ok. If the schema is missing it probably means fleet has failed to come up in your env. Is there anything interesting in your `docker logs <container>`? Does your local cluster show similar pods up and running? 

![image](https://user-images.githubusercontent.com/18697775/206765476-54e1c614-7812-4a26-a38c-37f5b994d37f.png)

Will transfer the issue over to `fleet`, they should be able to help more.

**Comment by richard-cox** [comment]
Ok, i don't have permission. Please can you re-create the issue over at `rancher/fleet`? Many thanks.
