### ISSUE TITLE
Cluster Mgmt: Move PSP resource to Advanced section

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7621]

**Comment by markusewalker** [comment]
QA TEST PLAN

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, navigate to Cluster Management and validate that Policy Security Policies is in the `Advanced` section|

**Comment by markusewalker** [comment]
Validated this against `v2.7-head` https://github.com/rancher/rancher/commit/d1249b5c6907bd326e09ec79d9ac8d9c22782d0d. Details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher install: `v2.7-head`  https://github.com/rancher/rancher/commit/d1249b5c6907bd326e09ec79d9ac8d9c22782d0d
- Browser: Chrome


**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, navigate to Cluster Management and validate that Policy Security Policies is in the `Advanced` section|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigated to Cluster Management > Advanced.
3. Validated that `Pod Security Policies` appears underneath:
![image](https://user-images.githubusercontent.com/52591819/207467361-3ed4f6b1-257f-4b11-8307-de1aad26f721.png)
