### ISSUE TITLE
Right side partial card in carousel fails to display

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7624]
**Setup**
- Rancher version: 2.7-head
- Browser type & version:

**Describe the bug**
- At the moment there are three cards in the Marketplace carousel
- When the 1st or 3rd cards are shown in the centre partial cards are shown on the left and right
- When the 2nd card is shown in the centre a partial card is shown on the left but not the right

**To Reproduce**
- Nav to Cluster --> Apps --> Charts
- Note - there should be three featured charts in the carousel

**Result**
![image](https://user-images.githubusercontent.com/18697775/205722633-4c1b8d47-ed8f-4bf1-9424-9cb4d177aa33.png)

**Expected Result**
As per other two cards

![image](https://user-images.githubusercontent.com/18697775/205722710-983fb75a-1f7c-47f8-aafb-3caa167f5103.png)

![image](https://user-images.githubusercontent.com/18697775/205722773-b5cecb5e-a272-4067-820a-7488e1f9ce7b.png)

**Comment by richard-cox** [comment]
I'm now not sure what the expected behaviour is. 

For the third position there's a card on the right but the right arrow is disabled

![image](https://user-images.githubusercontent.com/18697775/208149372-ac7400ae-2b52-4faf-a74f-43381cd2908c.png)

I'm assuming now that we don't forever scroll through and that there shouldn't be a card on the right

**Comment by bisht-richa** [comment]
@richard-cox That is how Carousel is designed to show continuation.

**Comment by richard-cox** [comment]
@bisht-richa That can't be correct. Can you send me a link to the original design?

The middle location should definitely have a card to the right specifically _to_ show continuation.

For https://github.com/rancher/dashboard/issues/7624#issuecomment-1355215974, the first location has an empty card to the left which can't be navigated to and the last location has a populated card that can't be navigated to. In both of those locations continuation is blocked (arrow is disabled with a disabled icon on hover)

**Comment by bisht-richa** [comment]
@richard-cox This is the original card design is attached:  https://zube.io/rancher/dashboard-ui/c/5487

**Comment by aganesh-suse** [comment]
Tested on version v2.7-head
Commit: be0b7c8dccf1f6e9f3dcc0896208ffabd8ba09f8
![Screenshot 2023-05-12 at 2 19 42 PM](https://github.com/rancher/dashboard/assets/129900588/38f1c892-284e-4c6c-9372-7b62f94d9945)

As we can see above, the middle carousel page shows the prev and the next in line. Marking this as verified. The first and last pages also seemed fine.
