### ISSUE TITLE
Add support for Pod Security Admission in the Clusters and Workloads

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#7628]
# Description

As outcome of https://github.com/rancher/dashboard/issues/7119, add mentioned features:
5. Workload view (e.g. detail view for Pod, Deployment etc)
8. Cluster Creation RKE2

## Context

As second part for the PSA implementation, some updates are required from the server side.

## Requirements

The new versions will be listed with https://github.com/rancher/rancher/issues/39795.
This is required to access `serverArgs` and `agentArgs` responsible for all the inputs and tabs configuration.

**Comment by cnotv** [comment]
@nwmac Could you please define the steps to create the error in the Workloads?

**Comment by cnotv** [comment]
As mentioned by @deniseschannon, we should ensure that switching between YAML and UI, the configuration of PSA and PSP is correctly updated.

**Comment by cnotv** [comment]
@kwwii would it be correct to display the text as following or should we maybe replace it with `(None)`?

![Screenshot 2023-01-11 at 12 11 09](https://user-images.githubusercontent.com/5009481/211792016-a7ae69c3-775a-4afd-8653-c28a36b398ed.png)

**Comment by deniseschannon** [comment]
@cnotv My assumption is your comment is around the dropdown for Default PSA, but RKE2 ships with a default PSA, so this is correct and it shouldn't be `(None)`.

**Comment by cnotv** [comment]
As side note, returning to form from YAML prevents injections of values without prior save by discarding changes.

<img width="1728" alt="Screenshot 2023-01-12 at 10 36 40" src="https://user-images.githubusercontent.com/5009481/212031482-0a238b57-677f-4f8b-b0e6-de6b5716de78.png">

**Comment by gaktive** [comment]
Based on https://github.com/rancher/rancher/issues/38875, RKE2 will slip out to 2023 Q2 so we shouldn't focus on that here and spin out a new ticket tied to that.

**Comment by gaktive** [comment]
@cnotv RKE2 is still part of 2023 Q1 upon an update from management though we'll need extend to timeline for release so it's back on.

**Comment by kwwii** [comment]
Assuming that there will always be a cluster PSA assigned when creating a new cluster, we should name this configuration "default". 

As users MUST assign at least the default PSA, there should be no checkboxes (all 3 values must be defined), and the default values should be "baseline" (unless I have misunderstood the naming)

> 

The stacked alerts (with each alert separate) is the correct behavior.

**Comment by kwwii** [comment]
> @kwwii would it be correct to display the text as following or should we maybe replace it with `(None)`?
> 
> ![Screenshot 2023-01-11 at 12 11 09](https://user-images.githubusercontent.com/5009481/211792016-a7ae69c3-775a-4afd-8653-c28a36b398ed.png)

Assuming that there will always be a cluster PSA assigned when creating a new cluster, we should name this configuration "default". 

As users MUST assign at least the default PSA, there should be no checkboxes (all 3 values must be defined), and the default values should be "baseline" (unless I have misunderstood the naming)

**Comment by kwwii** [comment]
> @kwwii There's an issue which we did not consider while introducing multiple errors as stacked for the banner, for cases which have and have not icons.

The correct behavior is to display each alert spearately as shown in the second screenshot

**Comment by cnotv** [comment]
> Assuming that there will always be a cluster PSA assigned when creating a new cluster, we should name this configuration "default".
> 
> As users MUST assign at least the default PSA, there should be no checkboxes (all 3 values must be defined), and the default values should be "baseline" (unless I have misunderstood the naming)

I think you are talking about something else. The question is about the dropdown of the templates in the RKE2 cluster creation. If we keep `default`, we'll have it for both PSP and PSA.

**Comment by cnotv** [comment]
Error example:
From: `pods \"asd\" is forbidden: violates PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"container-0\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"container-0\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (container \"container-0\" must not set securityContext.runAsNonRoot=false), seccompProfile (pod or container \"container-0\" must set securityContext.seccompProfile.type to \"RuntimeDefault\" or \"Localhost\")`
To: `Pod "asd" Security Policy Violation "restricted:latest"`

**Comment by markusewalker** [comment]
As part of this [test plan](https://github.com/rancher/rancher/issues/39994#issuecomment-1447317676), QA included checks to validate PSA works properly in clusters and workloads. We did this with the mindset that ensuring PSA works after cluster provisioning should be seen as a basic use-case we cover.

As such, I will close this issue. If there are specific issues that are found pertaining to PSA in clusters/workloads, separate issues will be logged.
