### ISSUE TITLE
Address field always defaults to "Custom" when editing a registry secret as a form 

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#763]
Version: v2.4-head(4269f6124), master-head(b89c3a572)

Steps:

1. Create a secret of "Registry" type by choosing address "Dockerhub/Quay.io/Artifactory"  as below
![Screen Shot 2020-06-11 at 3 22 15 PM](https://user-images.githubusercontent.com/18536626/84444779-63ed7680-abf7-11ea-93cf-cfc4596c4fb4.png)

2. Edit the registry secret as a Form. In the edit mode, "Custom" is selected instead of "Dockerhub" 
![Screen Shot 2020-06-11 at 3 25 00 PM](https://user-images.githubusercontent.com/18536626/84444953-c0509600-abf7-11ea-8f04-57d4df309371.png)

Address field always defaults to "Custom" when editing a registry secret as a form

**Comment by soumyalj** [comment]
Tested with master-head (1a5e5622b) 

The issue is fixed for registry address dockerhub and quay.io, but fails for 

1. Create a secret of "Registry" type by choosing address "Dockerhub, quay.io and artifactory
2. Edit the secret as a form.   

Address is selected correctly for dockerhub and quay.io, but for artifactory, custom is chosen during edit.

 **For artifactory, custom is chosen during edit as below. This needs to be fixed**

![Screen Shot 2020-06-29 at 4 24 07 PM](https://user-images.githubusercontent.com/18536626/86065640-fe85ec00-ba24-11ea-8cb5-7ba3b3e358c5.png)

Address is selected correctly for dockerhub
![Screen Shot 2020-06-29 at 4 14 17 PM](https://user-images.githubusercontent.com/18536626/86065725-33923e80-ba25-11ea-9582-abd4813ad03d.png)

Address is selected correctly for quay.io

![Screen Shot 2020-06-29 at 4 14 55 PM](https://user-images.githubusercontent.com/18536626/86065731-3856f280-ba25-11ea-9c25-605fd85dbebe.png)

**Comment by mantis-toboggan-md** [comment]
On edit this form determines which of the address radio buttons to show selected based off the content of the 'Registry Domain Name' field; there isn't another identifier of which registry provider is being used. For a url like `test.com` I don't have a way of knowing that was an Artifactory registry. I made a PR to set the radio button to 'Artifactory' if the url includes 'artifactory' though.

**Comment by soumyalj** [comment]
Tested with master-head build(3e543f7c4)
Steps:

1. Create a secret of "Registry" type by choosing address " artifactory".  Provide  registry domain name as "artifactory.com
2. Edit the secret as a form.

Custom is still chosen on an edit. 
![Screen Shot 2020-07-27 at 5 59 20 PM](https://user-images.githubusercontent.com/18536626/88606987-ec529a00-d032-11ea-9c5b-821f5d30ccea.png)

**Comment by mantis-toboggan-md** [comment]
This should work on master-head now

**Comment by soumyalj** [comment]
Tested with master-head build(ca3f705a4)
Steps:

1. Create a secret of "Registry" type by choosing address " artifactory". Provide registry domain name as "artifactory.com
2. Edit the secret as a form.

"Artifactory" is still chosen for the address field on an edit.
![Screen Shot 2020-07-28 at 12 20 56 PM](https://user-images.githubusercontent.com/18536626/88711320-ddb8c100-d0cc-11ea-86c0-584a9f16700f.png)
