### ISSUE TITLE
New `Manage` button on the home page has a different color scheme than `Import Existing` and `Create`

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#7633]
**Setup**
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/568544bc9f149af838521c7b96accebb135182cb
- Browser type & version: Chrome

**Describe the bug**

As part of https://github.com/rancher/dashboard/issues/7547, we recently introduced a `Manage` button to the home page that links directly to the Cluster Management page. It looks like the following:

![image](https://user-images.githubusercontent.com/52591819/205977944-620dc790-d942-400f-aaba-d696f5e6c3c6.png)

The `Manage` button is the only one that has a different color scheme than `Import Existing` or `Create`. We should ensure that we have consistency across all of the buttons.

**To Reproduce**

1. Setup Rancher and navigate to the home page in a browser.
2. Validate that the `Manage` button has a different color scheme than `Import Existing` and `Create`.

**Result**
The color scheme mismatches.

**Expected Result**

The color scheme should not mismatch what we see in `Import Existing` and `Create`.

**Comment by richard-cox** [comment]
This is by design.

Block filled buttons (all blue) are call to actions like creating or importing clusters. General buttons (outlined) are designed to be less distracting like just navigating to cluster management.
