### ISSUE TITLE
Diagnostics Page: `Generate Response Times` regression

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7634]
**Setup**
- Rancher version: 2.7-head

**Describe the bug**
- Previously the response time to fetch the most numerous (this may have been 15) resources across all clusters were made
- Now it seems another technique is made which results in
  - Only the `local` cluster showing response times in the UI (download might be different...)
  - The resources tested aren't the most numerous (see screenshot below

**To Reproduce**
- Connect one or more additional clusters
- Burger menu --> Click on version --> Click on `Generate Response Times`
- Review the `Resource Timing (ms)` column for each connected cluster (see screenshot)

**Expected Result**
I'm not sure how the last update was meant to leave the state, but something is wrong. I think initially the top x from each cluster was going to be tested but this was actually the top x over all clusters.

**Screenshots**
![image](https://user-images.githubusercontent.com/18697775/205980549-3fdb9515-7d37-4694-9d82-e95a97bcc947.png)

**Comment by ronhorton** [comment]
**Pass** Verified in rancher `v2.7-head commit ID 1f014b7`
1. added downstream cluster
2. navigate to diagnostics page
3. expand both cluster details sections
4. ciicked generate response times
5. `response times shown in UI for local and downstream`

![2023-05-09_11-16-45.png](https://zube.io/files/rancher/db71485134e3b276aad5d8fb6d22fcf4-2023-05-09_11-16-45.png)
![2023-05-09_11-16-23.png](https://zube.io/files/rancher/3a8414148e1e2924dae6e951987741c0-2023-05-09_11-16-23.png)
