### ISSUE TITLE
vSphere Node Driver cluster goes back to old UI

### ISSUE THREAD

**Issue by annablender** [rancher/dashboard#7636]
**Setup**
- Rancher version: 2.7-head
- Browser type & version: Google chrome

**Describe the bug**

When creating a vSphere node driver cluster, the ui takes me through 2 pages that appear to be old ui before I get to the Edit page. @richard-cox says this is a bug.

**To Reproduce**

* Spin up a Rancher instance 2.7-head
* Create vSphere node template
* Go to Cluster Management -> Create -> vSphere Node Driver

**Result**

Next page
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/12955547/205989706-4b0fd9a0-a528-4615-bcff-42313a997466.png">

Click on Add Cluster
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/12955547/205989803-eaa659f9-c726-4ef2-b84d-3e25e2c4848b.png">

Click on vSphere Node Driver
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/12955547/205989890-2f5a9909-73be-4549-9556-bd4c5643e7f7.png">

**Expected Result**

Rancher UI should just go directly to the Edit page.

**Comment by richard-cox** [comment]
This looks like it applies to any non-rke2 cluster creation (anything that routes to the old embedded UI)

**Comment by richard-cox** [comment]
We should address #7646 at the same time

**Comment by catherineluse** [comment]
IMO this should be considered a release blocker since it disrupts the cluster provisioning workflow

**Comment by catherineluse** [comment]
This issue may have the same root cause: https://github.com/rancher/dashboard/issues/7688

**Comment by richard-cox** [comment]
It looks like we do pass through the correct location (for example `https://<snip>/g/clusters/add/launch/digitalocean` for RKE1 DO) however there's errors and we're redirected back to the cluster list

![image](https://user-images.githubusercontent.com/18697775/207404899-35099b70-27ac-432e-93bd-b7a0ad5439af.png)

**Comment by catherineluse** [comment]
@richard-cox You're correct. I created a small Ember PR that fixes this and two similar bugs https://github.com/rancher/ui/pull/4925

**Comment by sowmyav27** [comment]
**On 2.7-head commit id: `a2ef50b`**

- Edit an RKE1 cluster
- User is navigated to the cluster edit page.
- The original issue seen is NOT observed anymore.
- No 404s seen in the console
