### ISSUE TITLE
Secrets: Reading multiline file import does not remove the default row

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/dashboard#7638]
**Setup :**

Rancher version: `v2.7-60ab459ac61cae96dfc3145e70e5d3afb9fdf7c8-head`
Browser type & version: Chrome and Firefox
Rancher Installation Type : HA / Docker

**Describe the bug :**
While Creating an Opaque Secret by reading from file (which has multiline key-value pairs), once they are imported, the default key & value boxes are not removed.

**Steps To Reproduce :**

1. Provision rancher
2. Cluster->Storage->Secrets->Opaque Secret
3. Go to Create an Opaque Secret
4. Prepare a file on your computer with the following data:
```
key1=value1
key2=value2
key3=value3
4=something
5=another_thing
```
5. Click Read from File and select the file previously prepared
6. Check for the key value pair values

**Actual Result :**
a. The file is parsed properly and the appropriate key value pairs are imported but the initial row with example `key` and `value` is not removed. After create it did not give any functional impact but better to delete the unused row from the list of keys.

**Expected Result :**
a. Imported key values should be displayed properly without any additional rows
b. Screen shot will provide clear details.

**Screenshots**
![image](https://user-images.githubusercontent.com/22034884/206062443-950d74d9-2f44-4521-a514-20597fbd8083.png)

**Comment by gaktive** [comment]
As an addition to this, we should look at the margins since the objects look pretty tight together. @kwwii to offer suggestions if need be.

**Comment by dasarinaidu** [comment]
I have validated this issue on `v2.7-6397018d78418255e3773b1d7ce477d8fe6a55ea-head`

 I can see the issue is fixed and I m closing the ticket.

**Validation Details:**
Rancher Veraion : `v2.7-6397018d78418255e3773b1d7ce477d8fe6a55ea-head`
Browser : Chrome 
User types : Admin & Standard user
Modes : Auto and Dark

**Steps To Reproduce :**

Provision rancher

1. Cluster->Storage->Secrets->Opaque Secret
2. Go to Create an Opaque Secret
3. Prepare a file on your computer with the following data:

```
key1=value1
key2=value2
key3=value3
4=something
5=another_thing
```

4. Click Read from File and select the file previously prepared
5. Check for the key value pair values
![image](https://user-images.githubusercontent.com/22034884/208503293-fa597731-34b3-4863-9e3f-0021e5846172.png)
