### ISSUE TITLE
Rancher does not update depencies when installing Helm chart from custom git repo

### ISSUE THREAD

**Issue by MaximeDetne** [rancher/dashboard#7652]
**Setup**
- Rancher version: 2.7.0
- Browser type & version: Firefox 102.3.0esr

**Describe the bug**
My helm chart contains dependencies, the packaged dependencies are *.tgz downloaded after running `helm dependency update`. Then from the CLI I can easily install my chart and all of its dependencies with `helm install`. 

Then, from Rancher UI, the dependencies are not installed, only the parent chart is installed. FYI, the .tgz files are present on the git repo. 

**To Reproduce**
My repo structure is : 
- /
    - app/
        - version/
            - templates/
            - charts/
                - deps.tgz
            - Chart.yaml
            - values.yaml
            - questions.yaml
            - app-readme.md
            - README.md

In Chart.yaml I describe deps like this (for exemple with this Percona's postgres operator): 
```
dependencies:
  - name: pg-operator
    version: "1.3.1"
    repository: "https://percona.github.io/percona-helm-charts/"
```
**Result**
From UI only the parent chart is installed, from CLI with exact same values.yaml all is installed.
**Expected Result**
Coherent behavior between CLI and UI when using Helm.

**Comment by MaximeDetne** [comment]
Thanks ! I found that annotation in the docs, but it seems limited to only one dependency, what if I have two ? Is there a workaround ?

**Comment by richard-cox** [comment]
It should support a comma separated list, for example `['a', 'b=version']. Looks like these are only in the format of `<chart name><optional '=' version>`, so would need to come from the same repo as the parent. You might need to check out what happens when the parent install is removed as well, i think that action would also apply to any installs that came from the annotation.

**Comment by MaximeDetne** [comment]
Looks like the comma separated list is not supported : `Incorrect type. Expected "string".yaml-schema: Helm Chart.yaml'

For instance with : 

```
annotations:
  catalog.cattle.io/auto-install: ['pg-operator=1.3.1', 'pg-db=1.3.1']
```

**Comment by richard-cox** [comment]
Ah, sorry, sans brackets. 

```
annotations:
  catalog.cattle.io/auto-install: 'pg-operator=1.3.1,pg-db=1.3.1'
```
