### ISSUE TITLE
Migration to Vue 3

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#7653]
# Description

Vue 2 is going to be EOM for the end of 2023. This issue is to track the required operation to reach from basic to optimal migration of Vue to version 3.

## Context

Since it has been decided to remove Nuxt, due lack of SSR and given the SPA architecture is optimal for our case, it will be defined afterward the requirement to fulfill the [migration list](https://v3-migration.vuejs.org/).
The goal is to make it possible to work with Vue 3, although reaching an ex novo state would facilitate the development and further integrations.

# Requirements

## Nuxt Removal

- https://github.com/rancher/dashboard/issues/5968
- https://github.com/rancher/dashboard/issues/8376
- https://github.com/rancher/dashboard/issues/4534
- https://github.com/rancher/dashboard/pull/10716

### First steps

- https://github.com/rancher/dashboard/issues/8078
- https://github.com/rancher/dashboard/issues/9028
- https://github.com/rancher/dashboard/issues/9541
- https://github.com/rancher/dashboard/issues/9539 (waiting to rebase)

### Configuration

Epics to be completed before migration
  - https://github.com/rancher/dashboard/issues/11487
  - https://github.com/rancher/dashboard/issues/11070
  - https://github.com/rancher/dashboard/issues/11457
  - https://github.com/rancher/dashboard/issues/11458
  - https://github.com/rancher/dashboard/issues/11459

### Migration 

  - https://github.com/rancher/dashboard/issues/9541
  - https://github.com/rancher/dashboard/issues/11492
  - https://github.com/rancher/dashboard/issues/11619
  - https://github.com/rancher/dashboard/issues/11620
  - https://github.com/rancher/dashboard/issues/11622
  - https://github.com/rancher/dashboard/issues/11639

### Extensions

As part of the migration, we'll have to update also the syntax for the extensions.
For these cases, we can use the script from https://github.com/rancher/dashboard/issues/9541 and check all the crossed requirements to be at least mentioned for each extension.

- https://github.com/rancher/dashboard/issues/11049
- https://github.com/rancher/dashboard/issues/10659
- https://github.com/rancher/dashboard/issues/10660
- https://github.com/rancher/dashboard/issues/8741

### Extras (non-blockers)

- https://github.com/rancher/dashboard/issues/9540
- https://github.com/rancher/dashboard/issues/10658

### Issues to be checked if solved on migration

- https://github.com/rancher/dashboard/issues/7679
- https://github.com/rancher/dashboard/issues/7476
- https://github.com/rancher/dashboard/issues/7680
- https://github.com/rancher/dashboard/issues/7357 
- Fix warnings wall on installation [1]

### Optional

- https://github.com/rancher/dashboard/issues/10870
- https://github.com/rancher/dashboard/issues/10871
- https://github.com/rancher/dashboard/issues/7468, this seems to be required as Vue CLI library is in maintenance mode
- [Pinia](https://pinia.vuejs.org/) adoption
- ~Test migration to [Vitest](https://vitest.dev/)?~ As Jest is ESM hell configuration and is embed in Vitest, this is going to be handled with Vite migration
- [Autoimport](https://github.com/antfu/unplugin-auto-import) adoption, to reduce code and migration steps (it will require https://github.com/rancher/dashboard/issues/7357 to be fixed)
- https://github.com/rancher/dashboard/issues/9711

**Comment by cnotv** [comment]
First plugin discontinued since 5 years: https://github.com/fgr-araujo/vue-shortkey

**Comment by gaktive** [comment]
Since moving to Vue 3 will potentially introduce breakage into existing UI extensions that folks (internal & otherwise) have written, we need to warn people about that risk when we finally do ship this.

**Comment by cnotv** [comment]
This is going to break for sure something and since we still don't have enough core E2E tests and our [real code coverage is 14%](https://app.codecov.io/gh/rancher/dashboard)

**Comment by cnotv** [comment]
Closing as Vue3 branch merged.
