### ISSUE TITLE
Cannot add labels to imported k3s cluster from UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7658]
Internal reference: SURE-4541
Reported in 2.6.3

After a k3s cluster is imported in Rancher, it is impossible to add a label via the UI. It is working fine on the other cluster types. 

Repro steps:

- Create Rancher cluster
- Import k3s cluster
- Cluster Management -> Edit config
- Labels & Annotations

![image-2022-04-27-11-17-17-738.png](https://zube.io/files/rancher/9414e2529b5238deaa866a375c1d02e6-image-2022-04-27-11-17-17-738.png)

Workaround:
Run `$kubectl edit clusters.management.cattle.io <k3s_clusterID>` and add the label from there.

Actual behavior:
Can't change / add labels through the UI

Expected behavior:
The UI should offer a box to add labels for this cluster

**Comment by gaktive** [comment]
For whoever grabs this, we should confirm the behaviour with other imported clusters to see if this is specific to k3s.

@nwmac will check with the k3s team about what could be happening from their side.

**Comment by gaktive** [comment]
As part of this work, we should provide a banner or alert saying to be careful when adding labels on this.

**Comment by bguzman-3pillar** [comment]
Reproduced using `v2.7.3`

![rep_e1](https://github.com/rancher/dashboard/assets/95362932/10743fdd-d93a-423e-b284-383f4698ff04)





Validated using `v2.7-head` (95edd02)
- Btn to `Add Label` and `Add Annotation` showed.


![val_btn_showed](https://github.com/rancher/dashboard/assets/95362932/150508dc-40fd-4091-be2e-1b358b6a9044)
![val_label_Added](https://github.com/rancher/dashboard/assets/95362932/45505934-5790-4868-b678-3e62cafad0ec)
