### ISSUE TITLE
[Monitoring v2] alertmanager fails on fresh cluster with rancher-monitoring installation

### ISSUE THREAD

**Issue by devopstales** [rancher/dashboard#7661]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart): Helm Chart 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 v1.21.2+rke2r1
- Proxy/Cert Details:

**Describe the bug**
When I firs deploy the rancher-monitoring chart from the us it fails with rancher/rancher#32827 issue. I found workaround. First, I'm installing monitoring with default values which and its fails. The I uninstall the rancher-monitoring-crd, hen re deploy the chart and it is starting, but the alertmanager-rancher-monitoring-alertmanager-0 pod is in a CrashLoopBackOff satate.

 ```
# log forom pod:
level=info ts=2021-07-22T14:24:15.044Z caller=main.go:216 msg="Starting Alertmanager" version="(version=0.21.0, branch=HEAD, revision=4c6c03ebfe21009c546e4d1e9b92c371d67c021d)"
level=info ts=2021-07-22T14:24:15.045Z caller=main.go:217 build_context="(go=go1.14.4, user=root@dee35927357f, date=20200617-08:54:02)"
level=error ts=2021-07-22T14:24:15.072Z caller=main.go:352 msg="failed to determine external URL" err="\"/k8s/clusters/local/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-alertmanager:9093/proxy\": invalid \"\" scheme, only 'http' and 'https' are supported"
```

On the rancher UI the monitoring links dose not work with Resource Unavailable.

**My workaround**
The[ Link to Alertmanager](https://github.com/rancher/charts/blob/1d17a5bb6767f6468815b005b688fb73f7baa228/charts/rancher-monitoring/values.yaml#L469) uses the Alertmanager's External URL field, which somehow not generated correctly. So based on [this template](https://github.com/rancher/charts/blob/1d17a5bb6767f6468815b005b688fb73f7baa228/charts/rancher-monitoring/templates/alertmanager/alertmanager.yaml#L26) I can set the external URLs by clicking on Edit as YAML on the Chart Options when deploying the Monitoring chart, and set it manually. 

```
alertmanager.alertmanagerSpec.externalUrl=<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-alertmanager:9093/proxy
```

**Comment by gaktive** [comment]
@ronhorton based on the age of this issue, can you check if this is still happening in 2.7.x?

**Comment by fernandorocagonzalez** [comment]
Hello, happening again to me with latest fresh rancher installation . RKE2 v1.25.12+rke2r1

Chart 102.0.1+up40.1.2 (Current)
Fri, May 26 2023 
102.0.0+up40.1.2
Wed, Mar 22 2023 

The workaround of setting global.cattle.url=RANCHER_URL didnt work. 

Everything seems to be deployed and working ok ,grafana ok, prometheus ok, but alertmanager states resource inaccesible, also, it seems like the alertmanager pod is not being created .

Would be nice to have the option for debug from the rancher GUI but Im not able to find where it is

**Comment by ronhorton** [comment]
**Pass** verified fixed 
`on v2.7.7-rc5`
rancher-monitoring:102.0.2+up40.1.2
rancher-alerting-drivers:102.1.0
Charts installed with no errors. 

`on 2.8-head commit ID 331d18b`
rancher-monitoring:102.0.1+up40.1.2
rancher-alerting-drivers:103.0.0
Charts installed with no errors.
