### ISSUE TITLE
Chart Repository refresh does not actually refresh the chart repo

### ISSUE THREAD

**Issue by jamesongithub** [rancher/dashboard#7668]
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.21.7
- Cluster Type (Local/Downstream): local on AKS
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

The refresh button 

![image](https://user-images.githubusercontent.com/4452738/153684059-bb67d22d-5def-4edb-a1b7-1798a244b08d.png)

![image](https://user-images.githubusercontent.com/4452738/153684067-ff6559f8-822d-4186-9df1-3454f5151b52.png)

does not actually sync the latest changes from the repo to rancher.

**To Reproduce**
 
1. create github repo with apps/marketplace rancher chart plus questions.yaml
1. create a branch on the repo
1. add repo url to rancher as a git repo pointing to branch
1. install chart
1. make a change to the chart and/or questions.yaml in the github repo branch
1. refresh the repo in rancher
1. attempt to deploy chart again

**Result**
Chart is deployed with old version

**Expected Result**

Chart to be deployed with latest changes on the branch after a refresh

**Screenshots**

**Additional context**

The only way is the create a new repo on rancher with a different name. Deleting and creating a repo with the same name does not fix the issue, you still have the old, cached version of the chart.

Is there even a automated periodic refresh at all?

**Comment by catherineluse** [comment]
Related tech debt issue https://github.com/rancher/dashboard/issues/7963
