### ISSUE TITLE
[pkg/rancher-components] String List, long lines wrap lines

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#7675]
**To Reproduce**

Create a new item with very long text, with at least one space inside.

**Result**
The text wrapped on multiple lines.

**Expected Result**

The text doesn't wrap.

**Screenshots**

![image](https://user-images.githubusercontent.com/26394656/206786714-fc50ea8f-003f-4ffd-b9b3-680e8e9b63d2.png)

**Comment by AndrewHoffmanQA** [comment]
@torchiaf i'm unsure where in the UI this screenshot is from. could you please provide more info regarding where this should be tested?

**Comment by AndrewHoffmanQA** [comment]
per slack with conversation, this ticket does not require QA work, it was dev validated by Franesco and his team while validating the StringList component and can be moved straight to the 'done' column
