### ISSUE TITLE
Add PSA custom resource in Cluster Manager

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#7677]
# Description

As outcome of https://github.com/rancher/dashboard/issues/7119 (point 7), create new PSA custom resource to the cluster manager.
Name of the resource: `management.cattle.io.podsecurityadmissionconfigurationtemplate`.
Required changes:
- Add new model for PSA
- Add PSA navigation to the Cluster Manager
- Add view and edit screens with the path
- Extend current component and test to adapt to new requirements

## Context

**NOTE:** It is required to update Rancher server to the latest version in order to test this feature locally. You can use [this script](https://github.com/rancher/dashboard/blob/master/scripts/update-docker-image) for this scope.

**Comment by markusewalker** [comment]
Test cases in the internal test plan pertaining to this issue have been validated. Therefore, closing this issue.
