### ISSUE TITLE
Interim Nav Bar for Single Cluster View

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#769]
- Cluster (Grouping)
  - Overview
    - Node
  - Namespace
  - Workload
    - Deployment
    - DaemonSet
    - ReplicaSet
    - StatefulSet
    - Job
    - CronJob
  - Ingress
  - Service
  - Secret
  - ConfigMap
  - OPA Gatekeeper
  - Rio

Note: OPA Gatekeeper and Rio will be removed when 2.5 nav comes in

Missing as work is still TBD: Volumes & HPA

**Comment by vincent99** [comment]
I will be taking care of this as part of rearranging the other nav/product switching.

Darren/Tani/Will/I already discussed and wireframed a plan for it (which is somewhat similar to above).

**Comment by lvuch** [comment]
Should I unassign myself from this?

**Comment by deniseschannon** [comment]
No longer needed based on @vincent99 earlier comment.
