### ISSUE TITLE
Make it easier to explore a cluster from the cluster detail view

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7694]
In Cluster Management, you can explore a cluster from the list view:

![image](https://user-images.githubusercontent.com/1955897/207349926-2d8158d7-9925-4a88-bdf3-08ffc3c1ce68.png)

.. but if you click on a cluster, there is no quick way to explore - you have to go back.

We should add a button to this view to reduce clicks needed to explore a cluster.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head dadb4c0
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: n/a
Downstream K8s version: n/a

----------

### Testing: ###

Tested this issue with the following steps:
1. Go to Cluster Management
2. Click on cluster
3. Verify there is an explore button on the cluster page

**Result**
There is now an `Explore` button on the top right side of the cluster page next to the detail and config buttons
![image.png](https://zube.io/files/rancher/7ff0dd4d772c1bf4985c02b011b04f81-image.png)
