### ISSUE TITLE
Creating a custom rke1 cluster switches UI to cluster list view instead of create/edit form

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7699]
This issue is identical to https://github.com/rancher/dashboard/issues/7646, but in the 2.7.x milestone.

**Comment by sowmyav27** [comment]
**On 2.7-head commit id: `a2ef50b`**

- Edit an RKE1 cluster
- User is navigated to the cluster edit page.
- The original issue seen is NOT observed anymore.
- No 404s seen in the console
- Create RKE1 cluster switches correctly to Create cluster page
