### ISSUE TITLE
Cluster Creation: RKE1/RKE2 toggle is not visible if no node driver is active

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#7705]
**Setup**
- Rancher version: 2.7.0
- Browser type & version: Chrome

**Describe the bug**
On the cluster creation page the RKE1/RKE2 toggle is not visible if there is no node driver activated (all node drivers deactivated.
This can be the case if a user only wants to allow custom clusters.

**To Reproduce**
* Go to Cluster Manger -> Drivers -> Node Drivers
* Deactivate all node drivers
* Create a new cluster

**Result**
There is a "Custom cluster" button, but no RKE1/RKE2 toggle.

**Expected Result**
There is a RKE1/RKE2 toggle visible.

**Screenshots**
![Bildschirm­foto 2022-12-14 um 16 02 24](https://user-images.githubusercontent.com/243056/207640396-0c4c4c29-d3dc-421f-a058-592a5b7e02b4.png)

**Comment by slickwarren** [comment]
verified on v2.7-head (65089ee):
* deactivate all node drivers from rancher
* toggle rke1/rke2/k3s option -- pass
<img width="1118" alt="Screen Shot 2022-12-21 at 12 50 04 PM" src="https://user-images.githubusercontent.com/16691014/209000468-ca7e7799-fffd-40c4-af1c-8a2097025cec.png">
