### ISSUE TITLE
Rancher server version is replaced with About on left navigation page

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#7710]
Setup

Rancher version: 2.7-head v2.7-216bb7
Browser type & version: Chrome

**Describe the bug**
Rancher server version commit ID is shown on the cluster management page on the left navigation. But if we select the hamburger menu the commit ID changes to `About` on the UI.

**To Reproduce**
1. Sping up a rancher server on v2.7-head
2. Click on hamburger menu from cluster management page.
3. Notice the rancher version at the bottom of the page

**Result**
Shows up as `About` instead of rancher server version commit ID. If we hover on the `About` it gives a `https://rancherIP/dashboard/about` 

**Expected Result**
Expected rancher server commit ID to show up on the left navigation and on hovering on the commit ID, expected to see the rancher server version.

**Screenshots**
<img width="100" alt="2022-12-14_10-37-16" height="400" src="https://user-images.githubusercontent.com/38144301/207682701-a9c841f0-7c61-41e4-bc5a-fd28a78675dc.png">

**Comment by richard-cox** [comment]
These are two separate locations
1) The burger menu bottom right link has been [changed](https://github.com/rancher/dashboard/issues/4217#issuecomment-1318395453) to better explain what it's for, with all info and more being in the destination 
2) The cluster explorer text (which isn't a link) remains unchanged
