### ISSUE TITLE
[Backport 2.6.x] Add event list to Pod detail page

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#7721]
Reported in 2.6.9

The event list is visible for workloads including Deployments, but is not visible for the detail page for individual Pods.

2.7.1 has a fix: https://github.com/rancher/dashboard/issues/7374 with PR https://github.com/rancher/dashboard/pull/7540

This is a request for a backport.

**Comment by Josh-Diamond** [comment]
Ticket #7721 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.6-e36364e2f7a673bae3464442947cd3ed1e9d4032-head`:
1. Fresh install of rancher `v2.6-head`
2. Navigate to `Cluster Explorer > Pods > Pod Details`
3. Verified - event list is present, accurate, and properly formatted

Screenshot:
<img width="1405" alt="Screenshot 2023-02-07 at 9 58 50 AM" src="https://user-images.githubusercontent.com/46494969/217312201-60c89a44-0c88-457c-b025-0c2eb593d8f3.png">
