### ISSUE TITLE
Cannot add Label to a pod

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7724]
Internal reference: SURE-5695
Reported in 2.6.9

Issue description:

Cannot add Label to a pod

Repro steps:

- Cluster Dashboard
-> Workload
-> Pods
-> Edit Config
- Pod
-> Labels & Annotations
-> Add Label
```
Key: foo
Value: bar
```

Workaround:
Edit the pod with kubectl

Actual behavior:
Label is not added.

Expected behavior:
Label is added.

**Comment by masap** [comment]
I found this is fixed at Rancher 2.7.0.

**Comment by gaktive** [comment]
Closing :)
