### ISSUE TITLE
'Manage' button on home page is a slightly different height to the others

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7727]
See below:

![image](https://user-images.githubusercontent.com/1955897/208071831-c4a4d4d0-2d78-4d33-8c84-1ac227d1530c.png)

**Comment by slickwarren** [comment]
tested on v2.7-head (65089ee):
the new button appears to be in line with the screenshot in the PR
<img width="459" alt="Screen Shot 2022-12-21 at 1 32 48 PM" src="https://user-images.githubusercontent.com/16691014/209006484-94daa34d-1baf-42c4-9931-223eea030136.png">
