### ISSUE TITLE
Broken navigation in plugin

### ISSUE THREAD

**Issue by cogor** [rancher/dashboard#7730]
**Setup**
- Rancher version: v2.7.0
- Browser type & version: Sidekick (Chromium) 106.33.1.28263

**Describe the bug**
If I had installed monitoring (Prometheus, Grafana, etc.)  you can't navigate to your plugin page (if it on a cluster level) from Cluster Dashboard page

**To Reproduce**
Install monitoring
Install extension (need to have links in cluster level menu, with links in global menu it doesn't work)
Navigate to Cluster Dashboard(/dashboard/c/local/explorer)
Try to navigate to your plugin page from sidebar link
**Result**
You can't navigate to your plugin page, page just reloaded with the same URL (but different hash) 

**Expected Result**
You can navigate to your plugin page

**Screenshots**
![alt](https://i.imgur.com/RIOj7qb.png)

**Comment by richard-cox** [comment]
@cogor To confirm 
1) You've created a UI [Extension](https://rancher.github.io/dashboard/plugins/introduction) that adds a route to the explorer view?
2) How have you loaded the extension (is it built when the dashboard builds, loaded manually by the `Extension` page or loaded via a repo in the `Extension` page)?

**Comment by richard-cox** [comment]
I couldn't reproduce this with a [test pkg](https://github.com/richard-cox/dashboard/tree/test-pkg/pkg/test). @cogor Can you provide an example pkg where you see the issue?

**Comment by cogor** [comment]
> I couldn't reproduce this with a [test pkg](https://github.com/richard-cox/dashboard/tree/test-pkg/pkg/test). @cogor Can you provide an example pkg where you see the issue?

I didn't have `inExplorer:          true` in my product, now it's works

**Comment by cogor** [comment]
> @cogor To confirm
> 
> 1. You've created a UI [Extension](https://rancher.github.io/dashboard/plugins/introduction) that adds a route to the explorer view?
> 2. How have you loaded the extension (is it built when the dashboard builds, loaded manually by the `Extension` page or loaded via a repo in the `Extension` page)?

1. Yes
2. Yes(via repo)

**Comment by richard-cox** [comment]
Brilliant can this issue and associated PR now be closed?

**Comment by cogor** [comment]
> Brilliant can this issue and associated PR now be closed?

Yep

**Comment by richard-cox** [comment]
Thanks, just let us know if there's any further issues
