### ISSUE TITLE
Hide `Change Workspace` `fleet.cattle.io.cluster` action for unsupported cluster types

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7734]
- It's unlikely https://github.com/rancher/rancher/issues/36132 will be solved any time soon
- This currently means the action to move a non-rke1 cluster to a difference workspace will silently fail
- To avoid this we should only show the action for RKE1 clusters

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 1eb478f
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 112

----------

### Testing: ###
Tested this issue with the following steps:
1. Navigate to cluster management and create a RKE2 and a RKE cluster
2. Navigate to Continuous delivery
3. Ensure correct workspace with the clusters selected.
4. Click on each cluster action
5. RKE2 dropdown should not have Change workspace action

**Result**
The RKE2 dropdown does not have `Change workspace` action
![image.png](https://zube.io/files/rancher/6959f6c861a81e99d6ba26894d90ceef-image.png)
