### ISSUE TITLE
This dependency was not found: @rancher/auto-import in ./pkg/test/index.ts 

### ISSUE THREAD

**Issue by jingliangapp** [rancher/dashboard#7736]
**Setup**
- Rancher version:2.7
- Browser type & version: none

**Describe the bug**
follow  [https://rancher.github.io/dashboard/plugins/plugins-getting-started](https://rancher.github.io/dashboard/plugins/plugins-getting-started)  create a test plugin

**To Reproduce**

yarn create @rancher/app my-app
cd my-app
yarn install
yarn dev

**Result**

ERROR  Failed to compile with 1 errors  
This dependency was not found:  
* @rancher/auto-import in ./pkg/test/index.ts
To install it, you can run: npm install --save @rancher/auto-import

**Expected Result**
compile with no errors

**Additional context**
OS:windows 10
node: v16.19.0
yarn: 1.22.19

**Comment by richard-cox** [comment]
@jingliangapp Could you provide more detail on where the `test` pkg came from?

**Comment by jingliangapp** [comment]
Sorry，add the missiing step:
yarn create @rancher/pkg test

**To Reproduce**
```
yarn create @rancher/app my-app
cd my-app
yarn install
yarn create @rancher/pkg test
yarn dev
```

**Comment by jingliangapp** [comment]
@richard-cox  This problem exists only on windows, no problem on linux or macos

**Comment by richard-cox** [comment]
@jingliangapp Thanks for the update, unfortunately we don't support Windows. This isn't documented anywhere and I've created https://github.com/rancher/dashboard/issues/7759 to do so
