### ISSUE TITLE
Auth Provider config page contains bad `code` block

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7737]
**Setup**
- Rancher version: 2.7-head

**Describe the bug**
- Code block is unsightly
- We should avoid adding custom styling for this one location (there's probably some generic styling that isn't being applied where it is elsewhere)
- Applies to all auth provider types

**To Reproduce**
- Burger Menu --> `Users & Authentication` --> `Auth Provider` --> `Github`
- Scroll to bottom

**Result**

**Expected Result**
- `admin` code block should be inline with rest of text 

**Screenshots**
![image](https://user-images.githubusercontent.com/18697775/208128171-7fdeee57-6a6c-4ea2-84af-f0bac62ff0ca.png)

**Comment by gaktive** [comment]
Engineering to write an automated test for this in #8818 to help QA.

**Comment by gaktive** [comment]
Manual QA going to be needed as we need a framework (likely Storybook) for visual confirmation. Will target that for Q4.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 547282b`
1. hamburger > Users & Authentication > Auth Provider > github
`Note at bottom of page is formatted and looks good`
![2023-06-12_16-20-55.png](https://zube.io/files/rancher/cafdef6a1df4960ef3baf63d8e2d8814-2023-06-12_16-20-55.png)
