### ISSUE TITLE
RKE2 Cluster Management "Machines" bar and count not updating when a node is disconnected

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#7740]
**Setup**
- Rancher version: `v2.7-head (Commit ID: 216bb7f)`
- Browser type & version: Brave | `v1.46.140`

**Describe the bug**
When Rancher is unable to reach a node on a downstream RKE2 cluster, the _Machines_ bar and count for the cluster on the Cluster Management page is not updating correctly.
 
**To Reproduce**
1. Create an RKE2 Cluster with two node pools
2. Wait for cluster to be ready
3. Stop one of the the RKE2 nodes in the second node pool
4. Go to the Cluster Management cluster list 

**Result**
The _Machines_ bar and count for the cluster remain the same.

**Expected Result**
In the _Machines_ column for the cluster, the bar should be showing partially red and the count should be 1 less than it was.

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/207403047-7f51bb41-f3cf-4fda-86b8-9c0b1418db7d.png)

Related Issue:
[7544](https://github.com/rancher/dashboard/issues/7544)

**Comment by gaktive** [comment]
This would be coming from the backend but we'd need to confirm this from the UI side first.

**Comment by momesgin** [comment]
It's also not reproducible in 2.8

**Comment by momesgin** [comment]
Seems this is fixed already since it's not reproducible in 2.9-head as well.

**Comment by IsaSih** [comment]
Tests pass on v2.8-deba2053a837a54e383894e1ddb19b0f8b034ecf-head
