### ISSUE TITLE
RKE1 node templates - If Azure storage type StandardSSD_LRS is selected, show managed disks warning 

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7743]
Creating an issue to track this PR https://github.com/rancher/ui/pull/4928

This is a follow-up to https://github.com/rancher/dashboard/issues/7177 and addresses the change left out per this comment  https://github.com/rancher/ui/pull/4905#issuecomment-1294310982

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 8062f1e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1

----------

### Testing: ###
When selecting `StandardSSD_LRS` and managed disks is not selected, Rancher shows a warning message. Also in this state, if user then selects another option that works, the warning message is removed.
![image.png](https://zube.io/files/rancher/27d0fffd255d9f441698bae7a32c4c18-image.png)

Once user selects managed disks, the warning is removed.
![image.png](https://zube.io/files/rancher/113247b47ed837d99041a864fff4e2f2-image.png)
