### ISSUE TITLE
RKE2 machine pools - If Azure storage type StandardSSD_LRS is selected, show managed disks warning

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7744]
This is a follow-up to https://github.com/rancher/dashboard/issues/7177 and addresses the change left out per this comment  https://github.com/rancher/ui/pull/4905#issuecomment-1294310982

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 8062f1e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2/k3s

----------

### Testing: ###
When selecting `StandardSSD_LRS` and managed disks is not selected, Rancher shows a warning message. Also in this state, if user then selects another option that works, the warning message is removed.
![image.png](https://zube.io/files/rancher/97ea72418e01242e11b35c6dcc16c1ad-image.png)

Once user selects managed disks, the warning is removed.
![image.png](https://zube.io/files/rancher/45445f51013ccc2bfa5c1b51029b71bc-image.png)
