### ISSUE TITLE
[BUG] No local cluster in dashboard UI after migrating to `fleet-default` workspace

### ISSUE THREAD

**Issue by imjustvisiting** [rancher/dashboard#7745]
**Rancher Server Setup**
- Rancher version: 2.6.8
- Installation option (Docker install/Helm Chart):
   - air-gapped HA RKE (Helm)

**Information about the Cluster**
- Kubernetes version: v1.24.2
- Cluster Type (Local/Downstream):
   - 1 local + 1 downstream (both air-gapped/Imported)

**User Information**
  - Cluster Owner

**Describe the bug**

I have one local cluster and one downstream cluster. I'd like to use fleet to deploy to both.

The fleet documentation suggests migrating the local cluster from the `fleet-local` workspace to the `fleet-default` workspace in order to accomplish this.

After following the procedure [here](https://fleet.rancher.io/troubleshooting/#migrate-the-local-cluster-to-the-fleet-default-cluster), the local cluster is no longer available in the Rancher UI dashboard (`/dashboard/home` endpoint). It also never appears in the `fleet-default` workspace. The downstream cluster still appears correctly in the UI.

Fortunately, the local cluster can still be reached by navigating to the `/dashboard/c/local` endpoint.

**To Reproduce**
Following directions from fleet documentation to migrate the local cluster to the fleet-default workspace:

- To get to Fleet in Rancher, click ☰ > Continuous Delivery.
- Under the Clusters menu, select the local cluster by checking the box to the left.
- Select Assign to from the tabs above the cluster.
- Select fleet-default from the Assign Cluster To dropdown.

**Result**
The local cluster will no longer appear in the `/dashboard/home` nor under `EXPLORE CLUSTER` in the ☰ menu.

**Expected Result**
The local cluster should always appear in the `/dashboard/home` page, and under `EXPLORE CLUSTER` in the ☰ menu

**Comment by richard-cox** [comment]
The visibility of clusters is normally determined via the values BE gives us, there's a good chance we're receiving something broken

**Comment by richard-cox** [comment]
In terms of moving clusters between workspaces, this also comes in to play - https://github.com/rancher/rancher/issues/36132

**Comment by nwmac** [comment]
@manno Is it supposed to be possible to move the local cluster to another Fleet workspace?

**Comment by dcarrillo-eog** [comment]
> @manno Is it supposed to be possible to move the local cluster to another Fleet workspace?

thats what they recommend for when working with fleet + the local cluster: [https://fleet.rancher.io/troubleshooting#migrate-the-local-cluster-to-the-fleet-default-cluster](https://fleet.rancher.io/troubleshooting#migrate-the-local-cluster-to-the-fleet-default-cluster)

**Comment by dcarrillo-eog** [comment]
> I ran into the same issue. I want a multicluster deployment and one of those clusters is local. Is there any way to deploy on local without moving it to `fleet-default`? The clusterSelector matchLabel does not seem to work even when I added the label to the cluster in the `fleet-local` namespace. Here is my `fleet.yaml` -
> 
> ```
> targetCustomizations:
> - name: test
>   defaultNamespace: test
>   helm:
>     chart: ./sample-chart
>     releaseName: main
>     values:
>       version: "v1.13.4"
>       global:
>         storageClass: "longhorn"
>       ingressAnnotations:
>         kubernetes.io/ingress.class: "nginx"
>       environment: test
>   clusterSelector:
>     matchLabels:
>       region: local```
> ```

I found a way, what I did was create a group (different from default) under fleet-local that is where I'm creating the GitRepo, then adding the local cluster to the group, finally my git repo its pointing to specific group:

```yaml
spec:
  targets:
  # The name of target. This value is largely for display and logging.
  # If not specified a default name of the format "target000" will be used
  - name: dev
    clusterGroup: test-group
```

**Comment by gaktive** [comment]
Internal reference: SURE-5518

Fleet team pinged about what UI should do here. They'll triage and update us.

**Comment by manno** [comment]
The fleet docs mention that it's [possible to move the local cluster](https://fleet.rancher.io/troubleshooting#migrate-the-local-cluster-to-the-fleet-default-cluster). They also [warn against it](https://fleet.rancher.io/namespaces#gitrepo-namespace).

The "moving cluster to workspace" button is currently not working in the UI, like @richard-cox [mentioned](https://github.com/rancher/rancher/issues/36132) (but it should for fleet standalone).

> Expected Result
> The local cluster should always appear in the /dashboard/home page, and under EXPLORE CLUSTER in the ☰ menu

In 2.7.2 the local cluster can be identified, by its "name=local" label. 

> The clusterSelector matchLabel does not seem to work even when I added the label to the cluster in the fleet-local namespace

Custom labels on the fleet local cluster can be overwritten. [They should work if they're on the provisioning cluster resource](https://github.com/rancher/rancher/pull/40176). 

> Is there any way to deploy on local without moving it to fleet-default?

Maybe https://fleet.rancher.io/namespaces#cross-namespace-deployments can help until the bugs are fixed.

**Comment by gaktive** [comment]
https://github.com/rancher/fleet/issues/1489 shows that Fleet's looking into this but it'll take them more time, so pushing this to Q3 (aka `2.7.next3`).

**Comment by dl-mai** [comment]
Yesterday I had a call with rancher support regarding this issue. While they didn't had a solution for us. They hinted that this issue occurs due to upgrading rancher and skipping versions. 

At the end of the meeting i noticed via the chrome developer tools that clusters.management.cattle.io and clusters.provisioning.cattle.io are loaded from the UI. 

I noticed that the call against the clusters.provision.cattle.io resource did not had the local cluster listed. After creating this resource the cluster was visible again without moving it from or to another workspace.
I basically applied this resource to the local cluster:
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: local
  namespace: fleet-local
spec:
  localClusterAuthEndpoint: {}
`
``

**Comment by manno** [comment]
We found out in https://github.com/rancher/webhook/pull/257 that moving the local cluster to another workspace would give all restricted admins in Rancher access to deploy manifest on the local cluster.

Now that this is clear, could you hide the menu entry?

**Comment by nwmac** [comment]
@manno This should be done in the backend - backend should prevent local cluster being moved. We could do this in the UI, but the underlying problem is still there and a user could still do this using the API.

**Comment by nwmac** [comment]
UI to prevent action to change workspace for the local cluster

**Comment by gaktive** [comment]
@Shavindra do you have details to provide here to help QA on how to test this?

**Comment by sbulage** [comment]
@gaktive thanks, I got the required information from @Shavindra :smile:

**Comment by sbulage** [comment]
The information from the https://github.com/rancher/dashboard/issues/7745#issuecomment-1755397508 is sufficient to test it.
