### ISSUE TITLE
Multi-tenancy for Continous Delivery / Fleet integration

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#7748]
**Is your feature request related to a problem? Please describe.**
The Continous Delivery feature lacks support for multi-tenancy and RBAC management. This prevents the use of that feature by users that are not Rancher admins.

**Describe the solution you'd like**

Rancher should be enhanced in such way that the Continous Delivery feature can be consumed by all users of the Rancher platform in a multi-tenant fashion. This may include:

- Mapping Fleet workspaces to Rancher projects or providing separate user permission management for Fleet workspaces
- Provide the ability during cluster provisioning to define the Fleet workspace the cluster should be part of (currently all clusters are mapped to the `fleet-default` workspace)
- Adding built-in cluster or project roles that can be used to grant the permissions necessary to manage Fleet resources

**Comment by richard-cox** [comment]
Closing as duplicate of https://github.com/rancher/dashboard/issues/7315
