### ISSUE TITLE
Continuous Delivery feature not available to cluster owners

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#7749]
Rancher 2.6.1

1. Login as standard user with cluster creation permissions
2. Create a cluster (thus becoming cluster owner)
3. Open main menu to access Global Apps -> Continuous Delivery

**Result:**

Continuous Delivery feature is not available in the menu

**Expected result:**

Cluster owners should have access to the Continous Delivery feature to configure GitOps for the clusters they own

**Comment by richard-cox** [comment]
Closing as duplicate of https://github.com/rancher/dashboard/issues/7315
