### ISSUE TITLE
Dashboard unreachable on master

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#775]
What kind of request is this:
Bug

Steps to reproduce (least amount of steps as possible):
Log into Rancher as Admin
Provision a cluster
Try to access dashboard

Result:
`HTTP Error 404: Not Found`
![Screen Shot 2020-06-15 at 4 20 34 PM](https://user-images.githubusercontent.com/57409052/84715154-8992bc80-af24-11ea-9284-e7e823f088d7.png)

Environment information:

Rancher version:
master-head 0ef371371
Installation option (single install/HA): Single install
Cluster type: DO

**Comment by izaac** [comment]
This usually recovered after a couple of minutes, but this is not the case this time.

**Comment by izaac** [comment]
@aaronRancher this is working for me today in latest master, could you confirm?

**Comment by izaac** [comment]
I tried two `master-head (06/22/2020)` commit `e9bc42c11` builds today and I am no longer experiencing this issue.

**Comment by aaronRancher** [comment]
> @aaronRancher this is working for me today in latest master, could you confirm?

Dashboard is accessible on `master-head` `11017ac8f`.
