### ISSUE TITLE
[RFE] Enable Azure accelerated networking - RKE1 node templates

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7752]
This issue is very similar to https://github.com/rancher/dashboard/issues/7182, but about RKE1 node templates instead of RKE2/K3s.

# QA Template
## What was fixed, or what changes have occurred

 - Added  accelerated networking (AN) to Azure node options in the Network section of RKE1 node templates

## Areas or cases that should be tested
- When AN is enabled, the list of VM sizes should show that the VM sizes that don't support it are disabled.
- The VM size dropdown is grouped so that you can see which VMs support accelerated networking and which do not.
- If you have AN disabled, then select a VM that does not support AN (such as `BasicA0`), then try enable AN, you should see an error that says the VM size is incompatible with AN. A warning also shows next to the VM size dropdown. The warning goes away if any other non-disabled VM is selected or if AN is turned off.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 8062f1e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1

----------

### Testing: ###
The configuration is available in the node template under `Network` section. The toggle button is working as expected and nodes are set with accelerated networking enabled.
![image.png](https://zube.io/files/rancher/0a4df6509945503700936368e49374ba-image.png)
