### ISSUE TITLE
[RFE] Rancher Azure Node Driver, add option to set Availability zone - RKE1 node templates

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7753]
This issue is very similar to https://github.com/rancher/dashboard/issues/7180, but about RKE1 node templates instead of RKE2/K3s.

# QA Template

## What was fixed, or what changes have occurred

 - Added an Availability Zone option for Azure nodes

## Areas or cases that should be tested

- Can select an AZ for an Azure node template
- You can have an Availability Set or Availability Zone, but not both
- Warn the user when the selected VM size is not in the selected region
- Warn the user if they have selected availability zones, but that is not supported for the region or VM size
- The Availability Zone dropdown menu may or may not have any options, depending on the selected region. For example, if you select `westus` as the location, the Availability Zone dropdown should be disabled and you should see a warning because that region doesn't support AZs. If you select `westus2` as the location, the Availability Zone dropdown should have 1, 2 and 3 as options.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 8062f1e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1, rke2, k3s

----------

### Testing: ###
For RKE2 and K3s, the configuration is available under the `Machine Pools` section and can be correctly set.
![image.png](https://zube.io/files/rancher/d31b48173f94687e01a53e992b1626be-image.png)

When the location does not have availability zones, Rancher notifies the user and blocks out the configuration.
![image.png](https://zube.io/files/rancher/492807fb010d427b20bf5fd883fddde0-image.png)

For RKE1, the configuration is available in the node template under the `Placement` section and can be correctly set.
![image.png](https://zube.io/files/rancher/a4ff98bc7b710a1b3c7b0a8bf5070780-image.png)

However, for rke1, when the location does not have availability zones, Rancher just gives the user an empty droplist. @catherineluse is it possible to give the same or similar kind of warning just like in rke2/k3s? Thanks!
![image.png](https://zube.io/files/rancher/128dda70a99849cbb438511ad16b2587-image.png)

**Comment by catherineluse** [comment]
> is it possible to give the same or similar kind of warning just like in rke2/k3s?

Yes - I will add that warning in a new PR.

**Comment by thaneunsoo** [comment]
@catherineluse sorry one more request, would it be possible to also gray out the Availability zone dropdown list as you did for rke2? Thanks!

**Comment by catherineluse** [comment]
@thaneunsoo I have grayed out the empty dropdown in this PR https://github.com/rancher/ui/pull/4943

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head f2bde24
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1

----------

### Testing: ###
When there are no availability zones available, the zone dropdown list is grayed out and also with the same warning as rke2
![image.png](https://zube.io/files/rancher/c727053289425e7f8194dbcc716d4fdf-image.png)

When availability zones are available, the zone list is now in order with `1,2,3`
![image.png](https://zube.io/files/rancher/75803f31b4aecf83890bfb17c5aedf1f-image.png)
