### ISSUE TITLE
UI is passing incorrect values for EKS custom node group node roles

### ISSUE THREAD

**Issue by annablender** [rancher/dashboard#7754]
**Setup**
- Rancher version: `v2.7-head`
- Browser type & version: Safari

**Describe the bug**

When testing the custom node group node role feature in EKS for issue https://github.com/rancher/dashboard/issues/4568, different rand strings get passed to the backend for each custom node role selected. This results in a `AccessDeniedException: Cross-account pass role is not allowed` getting thrown on the `CreateNodeGroup` call from EKS because EKS sees that the node role specified was not created in this AWS account.

**To Reproduce**

* Run Rancher v2.7 (or use dev rainbow v2.7)
* Add EKS creds
* Create an EKS cluster with a non-default custom node role for a 2-count node group
* Check out `config.Spec.NodeGroups[0].NodeRole` in the cluster mgmt object in the Rancher UI. It will have a string that looks vaguely like an AWS access key, but not the role

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/12955547/208204318-2effdf86-9918-407d-9f82-ac59ca72244b.png">

The eks operator are spammed with logs
```
ERRO[1961] error syncing 'cattle-global-data/c-gvrl4': handler eks-controller: AccessDeniedException: Cross-account pass role is not allowed., requeuing 
ERRO[1961] Error removing metadata from failure message: message body not formatted as expected
```

<img width="672" alt="image" src="https://user-images.githubusercontent.com/12955547/208204463-5c699b3a-e1ad-4cf9-88fc-e905f4716e42.png">

**Result**

**Expected Result**

The NodeRole should've been `ablender-test-custom-NodeInstanceRole` which was the custom role I created in EKS but that value did not show up.

**Comment by annablender** [comment]
Note: Also, from the [test plan](https://github.com/rancher/rancher/issues/29071#issuecomment-1248584761), the mock value I sent to EKS when backend testing was `arn:aws:iam::<AWS account ID>:role/ablender-2nodegroups-node-instanc-NodeInstanceRole-SBF895G87LLA` so this entire string needs to be sent for the role to be applied correctly. Only the role title can be selected. We don't want the pre-str to show up in the ui because that is sensitive info so this may need a minor update on the backend to close that gap.

**Comment by snasovich** [comment]
FYI @nwmac @gaktive

**Comment by Josh-Diamond** [comment]
Ticket #7754 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-e54432ebcfba5cfdf92cf055b89a7ebff2537ef7-head`:

Testing was conducted in parity w/ related rancher/issue/29071.
Test Scenarios + Results may be viewed here: https://github.com/rancher/rancher/issues/29071#issuecomment-1379638475

All scenarios pass ✅; as expected
`AccessDeniedException: Cross-account pass role is not allowed` - this error is no longer seen; all roles accurately represented in YAML
