### ISSUE TITLE
Namespace filter, focus

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#7757]
**Setup**
- Rancher version: any
- Browser type & version: any

**Describe the bug**

https://github.com/rancher/dashboard/pull/7665#pullrequestreview-1222589162
The focus effect on the selected option doesn't change the font and icon colors, making them the same color as the bg and therefore invisible.
This is noticeable when navigating through the namespace filter options with the arrow keys.

**To Reproduce**

Click on Namespace filter

**Result**
Focus effect on the selected option doesn't change the font and icon colors.

**Expected Result**

Focused option should be clearly distinguishable from the other ones.

**Screenshots**

![namespaces_focus_2](https://user-images.githubusercontent.com/26394656/208401599-9f729664-5a17-42bb-af05-a39cb28aaccc.png)
![namespace_focus_1](https://user-images.githubusercontent.com/26394656/208401604-cc30fb24-3170-4497-9aa4-d7a7a4cae74d.png)

**Comment by richard-cox** [comment]
There's some special CSS that covers the use case where only a single namespace is selectable. When fixing this it's worth double checking that functionality still looks ok (can be tested by burger menu --> Global Settings --> Performance --> enable `Require Namespace Filtering` and reduce threshold)

**Comment by gaktive** [comment]
Engineering will write an automated test in #8805 to help QA.

**Comment by gaktive** [comment]
Visual testing is going to hard to automate without the appropriate framework, so this should hopefully be a quick manual test for QA. We'll figure out something, likely in Storybook, to build up for automation.

**Comment by Josh-Diamond** [comment]
Ticket #7757 - Test Results - ✅ 
---

Verified with HA Helm Rancher on `v2.7-5b9667d60627cfced1faf7319434f0537a052d15-head`:
1. Fresh install of Rancher `v2.7-head`
2. Navigate to `Cluster Explorer` of local cluster and select dropdown for `Namespaces` up top
3. Verified - focus displays correct stylings; as expected

Screenshots:

`Dark Theme`
<img width="326" alt="Screenshot 2023-06-07 at 10 54 45 AM" src="https://github.com/rancher/dashboard/assets/46494969/8e1a29ca-fee7-4b53-b044-c073d63a98e4">

`Light Theme`
<img width="328" alt="Screenshot 2023-06-07 at 10 55 04 AM" src="https://github.com/rancher/dashboard/assets/46494969/a4380e8a-12cf-4c2a-afdc-4a411776ac34">
