### ISSUE TITLE
Job, fix duration field format

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#7758]
**Setup**
- Rancher version: 2.7.next.1
- Browser type & version: any

**Describe the bug**

Duration field formatting is not the same as the one from of Kubernetes API.

**To Reproduce**

- Go to Local -> Worload -> Jobs
- Create a new Job
- Check the Duration field

**Result**
If a Job is running for more than 2 days, the value format is wrong.

**Expected Result**

The value should be the same as the one from  K8s API `batch.jobs` definition

**Screenshots**

![image](https://user-images.githubusercontent.com/26394656/208424477-771215f0-e731-4d13-9bff-2202527cdaa0.png)

**Comment by aganesh-suse** [comment]
Build: v2.7-head with commit: b04c942

The Duration field for jobs - shows in days+hour: 2d2h

![Screenshot 2023-05-17 at 1 38 43 PM](https://github.com/rancher/dashboard/assets/129900588/42e79b74-b8b8-4540-a128-8c1fcd4375d3)
