### ISSUE TITLE
Unable to Deactivate multiple Cluster Drivers and Node Drivers

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#7762]
**Setup**
- Rancher version: v2.7-head (5df9701)
- Browser type & version: Firefox

**Describe the bug**

Nothing happens when attempting to deactivate Cluster Drivers or Node Drivers.

**To Reproduce**

> The issue applies to both Cluster Drivers and Node Drivers

1. Navigate to Cluster Management => Drivers => Cluster/Node Drivers
2. Select all active drivers
3. Click Deactivate

**Result**

Nothing happens, no error in console.

**Expected Result**

Confirmation dialog is shown, positive selection results in Cluster/Node drivers becoming deactivated.

**Additional context**

This looks to be an issue with the confirmation dialog. 

This only happens when attempting to delete multiple cluster/node drivers.

Holding `ctrl` before to skip the confirmation dialog while clicking delete will perform the action as expected.

**Comment by jameson-mcghee** [comment]
![image](https://user-images.githubusercontent.com/13294321/208749575-1d77adf6-6b5b-4b2a-b13c-3b0397721fa3.png)
![image](https://user-images.githubusercontent.com/13294321/208749596-5b4494ab-9505-4045-ab47-fcf7e37495b2.png)
![2022-12-20_14-15-26](https://user-images.githubusercontent.com/13294321/208749616-f643ace2-10a3-4a72-aee2-c4d15260ea60.gif)

**Comment by jameson-mcghee** [comment]
@rak-phillip, can you update this ticket to include both _Cluster Drivers_ and _Node Drivers_ so that they are both fixed and tested?

**Comment by rak-phillip** [comment]
@jameson-mcghee I updated to call out both cluster & node drivers

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: e54432e) I was able to verify that the confirmation prompt is now being generated when attempting to Deactivate multiple Cluster Drivers or Node Drivers, and users are able to successfully Deactivate multiple Cluster Drivers or Node Drivers. Therefore I am closing this ticket as Done.

**`v2.7-head` (Commit ID: e54432e):**
**Cluster Drivers:**
![image](https://user-images.githubusercontent.com/13294321/212143931-22931298-61cb-4f92-9ce6-99da0c71fb87.png)
![image](https://user-images.githubusercontent.com/13294321/212143956-a47b2a35-7aec-4ffc-9a10-a5afd2594989.png)

**Node Drivers:**
![image](https://user-images.githubusercontent.com/13294321/212144032-1960af8e-0084-4129-827f-93b3bbfb2771.png)
![image](https://user-images.githubusercontent.com/13294321/212144089-94d918bb-b08d-43e3-9d4e-0c9f0793e789.png)
