### ISSUE TITLE
Cluster management 'Explore' button is missing translation when the cluster is provisioning

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#7763]
![image.png](https://zube.io/files/rancher/f6b5848f678a756d257b4cd60573a40d-image.png)

**Comment by slickwarren** [comment]
tested on v2.7-head (65089ee):
new clusters in a non-active state now show the correct icon for the `explore` button
<img width="1802" alt="Screen Shot 2022-12-21 at 1 45 22 PM" src="https://user-images.githubusercontent.com/16691014/209008218-2df42136-48f2-45b1-a3f3-305fee0565bb.png">
