### ISSUE TITLE
Fix styling issues with searchable select

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7765]
I'm opening this issue as a follow-up to feedback on my PR https://github.com/rancher/ui/pull/4932#discussion_r1052665600

In my PR, it would have been better to use a searchable select for a long list, but it needs some styling fixes before it can be used without issues.

We should make the padding of the selects and inputs consistent so that they can appear in horizontal rows without looking misaligned. And the height needs to be limited so that it can't extend past the bottom of a form when opened.

Screenshots:
![208528959-18decf4d-6395-40d1-9af2-11093ac87900](https://user-images.githubusercontent.com/20599230/208545147-657325c9-54e3-4c2e-9a02-54f56ab4bda7.png)

<img width="1249" alt="Screenshot 2022-12-19 at 3 57 41 PM" src="https://user-images.githubusercontent.com/20599230/208545127-dde59c3d-9a4f-44a2-8113-743b7c3c0a03.png">

**Comment by mohdamanzaidansari** [comment]
Hi @catherineluse. Can you assign this issue to me I would like to work on it.

**Comment by nwmac** [comment]
Closing as stale - ember UI will be retired over time
