### ISSUE TITLE
Private registry config option should not show in Helm chart installs for non-Rancher charts

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7766]
It looks like the private registry config options are showing for all Helm charts that can be installed through Rancher catalogs. Because this option is directly configuring a Helm chart value called `system_default_registry` in its global values, it only applies to Rancher charts. Non-Rancher charts don't have Rancher global values, in which case this setting does nothing and should be hidden.

We need to check for the presence of the `system_default_registry` in the chart before exposing this input to the user:
![Screenshot 2022-12-19 at 11 48 40 AM](https://user-images.githubusercontent.com/20599230/208546198-ba320950-4df6-40dc-994e-7f2bd9968671.png)
![Screenshot 2022-12-19 at 11 47 41 AM](https://user-images.githubusercontent.com/20599230/208546215-b9651f32-c550-48ce-8edb-f409ed5db223.png)

**Comment by richard-cox** [comment]
I think we originally did this given the chart values file, however NeuVector didn't have the correct entries. They were going to update their chart, though not sure if other Rancher charts have the same issue

**Comment by catherineluse** [comment]
Even for NeuVector, we should still hide the chart if that global value is not in the selected chart version. Because configuring the value won't have any effect until they add it.

**Comment by richard-cox** [comment]
I think the problem their side was that it was used in one of the chart templates but not defined in values

**Comment by gaktive** [comment]
There's potentially an existing PR in the Neuvector repo to address this but there may be other charts impacted by this.

**Comment by catherineluse** [comment]
I spoke with Selvam Thangaraj from the NeuVector team. He said that the NeuVector Helm chart has contained the system default registry in the global values since the v2.7.0 release.

https://github.com/rancher/charts/blob/release-v2.7/charts/neuvector/101.0.1%2Bup2.2.4/values.yaml#L7

No further changes are required to the NeuVector chart in order to allow this fix.

**Comment by AndrewHoffmanQA** [comment]
tested and passed on 2.7head 6ee3949

non rancher charts do not offer the option, additionally rancher charts DO still have the optoin. 



![image.png](https://zube.io/files/rancher/cbd5f7ad5637297e9777ebe625eb4352-image.png)


![image.png](https://zube.io/files/rancher/553fbc7b97827a5927040a041ce1a640-image.png)
