### ISSUE TITLE
Improve `getGroups` performance

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7773]
- `./shell/layouts/default.vue` `getGroups` fn is called often and can sometimes take a long time to complete (over a second)
- We've seen in some environments a change of namespace results in two executions of `getGroups`
- We should bring up a cluster with ~1000 namespaces and prove the performance hit of `getGroups` when changing namespace, improve it's performance and test again
- Places to consider
  - reduce number of calls to getGroups with a debounce
  - `Object.keys(namespacesObject)`
  - `addObject` (are these called on large sets of data)
  - `type-map/allTypes` and `type-map/getTree`
  - `replaceWith(this.groups, ...sortBy(out, ['weight:desc', 'label']))` takes to run

**Comment by richard-cox** [comment]
Changing NS (all sockets enabled)
![Screenshot_20221220_135523allsocketson_cropped](https://user-images.githubusercontent.com/18697775/208712518-e49fc6be-e8aa-4bf5-894e-37e93784679d.png)

Changing NS (all sockets disabled)
![image](https://user-images.githubusercontent.com/18697775/208712697-b8eae94a-291e-48ef-9373-1fd586b87576.png)

**Comment by richard-cox** [comment]
Important factor of https://jira.suse.com/browse/SURE-6584

**Comment by richard-cox** [comment]
Starting info for release notes

```The Rancher UI Side Navigation menu would perform badly in environments with lots of CRDs, namespaces or resource churn. Following this change this should now be greatly improved```

**Comment by eva-vashkevich** [comment]
Counts for ConfigMaps appear incorrect.  They are correct on preceding commit.
<img width="1715" alt="Screenshot 2024-07-15 at 3 50 37 PM" src="https://github.com/user-attachments/assets/3e135d6a-68f9-4a4d-a26f-a15febe2e948">

**Comment by eva-vashkevich** [comment]
Looks good. I've tested the scenarios listed under testing section and didn't see any issues.
