### ISSUE TITLE
Improve `NamespaceFilter` component performance

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7775]
- `./shell/components/nav/NamespaceFilter.vue` can struggle when there's ~1000 namespaces on both render time and CPU on change of namespace
- We've seen in some environments changing a NS results in two render hits of ~1.5 seconds each
- We should bring up a cluster with ~1000 namespaces and prove the performance hit of changing a NS, improve it's performance and test again

**Comment by floatingman** [comment]
Tested on Rancher versions 2.7.2-rc1 and 2.6.9

### Rancher 2.6.9
Brought up a HA cluster running on RKE1 and K8s version 1.23.10-rancher1-1

#### Steps
**Prerequisite**
After installing Rancher create over 1000 namespaces.

In Cluster Explorer

1. Click on Projects/Namespaces 
2. In the namespace filter drop down switch to **Only User Namespaces**
3. Switch to **Only System Namespaces**
4. Observe the time to make those changes.
Graphs:
![Screen Shot 2023-02-14 at 9 41 57 AM](https://user-images.githubusercontent.com/48339/218787412-9cd2d885-3dd9-48bf-912d-0d1291c8aacd.jpg)

### Rancher 2.7.2-rc1
Ran on a K3s HA cluster with K8s version 1.25.5+k3s2

#### Steps
Repeat test steps
