### ISSUE TITLE
Idle Modal (reduce impact of idle tabs)

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7776]
**Is your feature request related to a problem? Please describe.**

- Users can open multiple tabs across multiple browsers. Each tab will have at least two sockets open 
- This causes strain on the local system and also remote cluster/s

**Describe the solution you'd like**
##### Modal
- After a certain amount of time where the user hasn't interacted with the page show the idle modal
  - Interactions consist of tab focused, mouse clicks, mouse move, key up, key down, etc
- Modal shows count down 
- On count down reaching zero we unsubscribe to all sockets and inform user of state
- If the user confirms their presence using the modal, we refresh the page (this avoids having to re-fetch ALL previously cached info, only data from the present page is fetched on page load)

##### Additional Context
- This applies to ALL tabs, whether focused, active or un-active (note - un-active tab timers work differently then active)
- There will be no automatic log out. 

##### Configuration
  - Admins can disable the feature for all users
  - Admins can set the idle time the modal is shown (30 minutes?)
  - Admins can set the timer before the sockets are stopped (1 min?)
  - ~Admins can set a default value for all users (settings)~
    - ~The initial value should be smaller than the local auth provider session timeout~
  - ~Admins can set a max value for all users (settings)~
  - ~Users can set their own value (if the feature is enabled). This cannot exceed the max value~

This has been split out in to three sequential steps
- https://github.com/rancher/dashboard/issues/8317
- https://github.com/rancher/dashboard/issues/8321
- https://github.com/rancher/dashboard/issues/8322

[Specs Confluence page](https://confluence.suse.com/x/xAEOS)

**Comment by gaktive** [comment]
This may address what's reported in https://github.com/rancher/dashboard/issues/6092 so let's do this 1st and then see if we have to do anything with #6092 after.

**Comment by gaktive** [comment]
Internal reference: SURE-4501

**Comment by richard-cox** [comment]
@richard-cox to confirm if we're timing out and logging out... as well as just showing the modal with stopped sockets. then split ticket up

**Comment by edenhernandez-suse** [comment]
[Specs Confluence page](https://confluence.suse.com/x/xAEOS)

**Comment by gaktive** [comment]
This is the parent ticket that will incorporate E2E tests and other automation to help out, so as @scures writes tests, he can link here.
