### ISSUE TITLE
Empty Banner Message when attempting to Import AKS Cluster

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#7781]
**Setup**
- Rancher version: `v2.6.5` and `v2.7-head (Commit ID: 65089ee)`
- Browser type & version: Brave: `v1.46.140` | Chromium: `v108.0.5359.99`

**Describe the bug**
After inputting new cloud credentials while attempting to import an AKS cluster, a red banner is generated with no message.

**To Reproduce**
1. Spin up a Rancher `v2.6.5` Rancher server
2. Navigate to the _Cluster Management_ page, and select _Import Existing_
3. Select _Azure AKS_
4. Input new valid AKS cloud credentials, and then click create

**Result**
A red banner is generated that contains an icon but no message

**Expected Result**
The correct error/warning message is presented in the banner

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/208745048-ce1a6965-32bc-4168-ab8c-e9ccdac47b23.png)

**Comment by nwmac** [comment]
Fixed by https://github.com/rancher/ui/pull/4942/files

**Comment by jameson-mcghee** [comment]
During testing on `v2.6.6` when following the Steps to Reproduce, I was able to reproduce this issue. However, when testing on `v2.7-head` (Commit ID: 623addd), this issue was resolved. Therefore I am closing this ticket as completed.

**Steps to Reproduce:**
1. Spin up a Rancher `v2.6.5` Rancher server
2. Navigate to the _Cluster Management_ page, and select _Import Existing_
3. Select _Azure AKS_
4. Input new valid AKS cloud credentials, and then click create

**`v2.6.6`:**
![image](https://user-images.githubusercontent.com/13294321/212427543-f7256964-7628-4620-8f81-99a3d40a474f.png)

**`v2.7-head` (Commit ID: 623addd):**
![image](https://user-images.githubusercontent.com/13294321/212427600-d27bb6e6-8591-4441-b4f7-23bd4bb57758.png)
