### ISSUE TITLE
Unable to Deactivate multiple cluster drivers

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#7782]
**Setup**
- Rancher version: `v2.6.5` and `v2.7-head` (Commit ID: 65089ee)
- Browser type & version: Brave: `v1.46.140` | Chromium: `v108.0.5359.99`

**Describe the bug**
Users are unable to deactivate multiple Cluster Drivers at once

**To Reproduce**
1. Navigate to _Cluster Management_ -> _Drivers_ -> _Cluster Drivers_
2. Select all active Cluster Drivers
3. Click _Deactivate_

**Result**
Nothing appears to happen in the UI, and there are no errors in the Console or Network logs

**Expected Result**
The selected Cluster Drivers are successfully deactivated

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/208748188-0f494ac3-54c0-4255-b69e-542844c1d547.png)
![image](https://user-images.githubusercontent.com/13294321/208748208-10ce796d-5e2f-4b1e-84e0-70c1197e537b.png)
![2022-12-20_14-15-26](https://user-images.githubusercontent.com/13294321/208748411-d37536db-9bd2-4da5-b1c1-e24301864f15.gif)

**Additional context**
According to @rak-phillip in the related issue [7762](https://github.com/rancher/dashboard/issues/7762):

This looks to be an issue with the confirmation dialog.
This only happens when attempting to delete multiple [cluster] drivers.
Holding `ctrl` before to skip the confirmation dialog while clicking delete will perform the action as expected.

**Comment by richard-cox** [comment]
Unfortunately the title for https://github.com/rancher/dashboard/issues/7762 got a little lost as the issue progressed. It's the same bug as this one, so closing
