### ISSUE TITLE
Downstream RKE2 cluster fails to install chart(s)

### ISSUE THREAD

**Issue by rmammadli** [rancher/dashboard#7789]
**Setup**
- Rancher version: v2.7.0
- Installation option (Docker install/Helm Chart): Helm Chart
  If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Browser type & version:
  - Version 108.0.5359.95 (Official Build) (64-Bit)
  - Version 108.0.1462.54 (Official Build) (64-Bit)

**User Information**

What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin

**Describe the bug**

Downstream RKE2 cluster(s) can not install helm chart / apps from catalog.

**To Reproduce**

Deploy rancher v2.7.0 
Login as admin 
Provision a downstream RKE2 vSphere cluster with k8s v1.24.4+rke2r1
- Navigate to Cluster Explorer > Apps > Charts > Select a chart > Install
 or
- Navigate to Cluster Tools > Select a Chart / Tool > Select a Tool > Install

**Result**
Blank page

**Expected Result**

A user will be redirected to the next page of chart configuration.

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment]
Should have been solved via https://github.com/rancher/dashboard/pull/7952

**Comment by richard-cox** [comment]
Linking https://github.com/rancher/dashboard/issues/7808, that should be validated at the same time

**Comment by janeczku** [comment]
> Should have been solved via #7952

@richard-cox #7952 appears to specifically fix the issue for imported clusters where the root cause of the blank page is a missing `provClusterId` attribute.
The issue here affects Rancher provisioned RKE2 clusters.

**Comment by richard-cox** [comment]
Linking https://github.com/rancher/dashboard/issues/8241, which should also be validated at the same time

@janeczku There's a range of reasons why that value might be missing. There's a more recent fix (https://github.com/rancher/dashboard/pull/8242) that handles a more RKE2 specific use case. Given we can't reproduce this locally, and the range of other fixes, think a QA cycle would be good.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7.2-rc6`
Installed:
rancher-logging:102.0.0+up3.17.10
rancher-alerting-drivers:102.0.0
rancher-monitoring:102.0.0+up40.1.2

charts installed successfully with no errors. 
no blank page encountered instead of install screen/appreadme
