### ISSUE TITLE
Custom branding/theming support

### ISSUE THREAD

**Issue by tacerus** [rancher/dashboard#7790]
**Is your feature request related to a problem? Please describe.**
It may be desirable to customize the login/landing page to visualize a custom organization branding.

**Describe the solution you'd like**
Instead of the theme being hardcoded in the application, selectable themes could be offered with a place for the user to install local drop-ins based off the base theme.

**Describe alternatives you've considered**
If a full-fledged theming system is not feasible, exposing certain text fields on the landing page as editable options would already help - for example if one is not using any of the supported authentication providers, being able to add a custom "Log in with $provider" or greeting text.

**Comment by richard-cox** [comment]
These kind of changes should now be possible via https://rancher.github.io/dashboard/extensions/introduction
