### ISSUE TITLE
Resources in the `rke-machine.cattle.io` group do not appear under `Cluster Provisioning`.

### ISSUE THREAD

**Issue by jakefhyde** [rancher/dashboard#7792]
**Setup**
- Rancher version: v2.7-head

**Describe the bug**

Resources in the `rke-machine.cattle.io` group do not appear under `Cluster Provisioning`.

**To Reproduce**

Provision a v2prov cluster, and view where the `<CLOUD_PROVIDER>Machine` resources appear in the UI.

**Result**

Resources in the `rke-machine.cattle.io` group do not appear under `Cluster Provisioning`.

**Expected Result**

Resources in the `rke-machine.cattle.io` group should appear under `Cluster Provisioning`.

**Screenshots**

![image](https://user-images.githubusercontent.com/33796120/209023837-f06c8bc3-9a7d-4d11-acb2-e94212f807e0.png)

**Additional context**

`rke-machine` needs to be added here: https://github.com/rancher/dashboard/blob/b253857493d3e1117c999c06ff2fc991409a26a0/shell/config/product/explorer.js#L143

**Comment by sowmyav27** [comment]
**On 2.6.9**
<img width="241" alt="Screen Shot 2022-12-27 at 9 42 25 AM" src="https://user-images.githubusercontent.com/26032343/209702961-b012366e-1e36-4c60-87d0-b51d587f6cde.png">

**On 2.7-head commit id: `28a84c7`**
- Issue is seen fixed
<img width="769" alt="Screen Shot 2022-12-27 at 9 42 39 AM" src="https://user-images.githubusercontent.com/26032343/209702977-4cde02d2-471c-4043-869e-82b5041de3bd.png">
