### ISSUE TITLE
`What's new in 2.7` and `Preferences` hyperlinks have moved to the next line in Home Page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#7794]
**On 2.7-head commit id: `65089ee0`**

<img width="973" alt="Screen Shot 2022-12-21 at 8 21 12 PM" src="https://user-images.githubusercontent.com/26032343/209055409-a8cd9552-812b-4350-b903-3093ffde1b15.png">

**On 2.6.9**
<img width="1506" alt="Screen Shot 2022-12-21 at 8 24 08 PM" src="https://user-images.githubusercontent.com/26032343/209055440-b4b0e970-62b9-4d98-846e-04c92cf03471.png">

Can we have them on the same line, if needed a little closer than 2.6.9 ?

**Comment by gaktive** [comment]
We'll be making changes to this page already in https://github.com/rancher/dashboard/issues/7413 as move towards simply linking to the docs, rather than bundling What's New. @mantis-toboggan-md can check the formatting to ensure it conforms to what you're requesting.

**Comment by nwmac** [comment]
@kwwii Do you know if this was a deliberate design decision?

**Comment by kwwii** [comment]
@nwmac No, this was not a deliberate decision. My guess is that something changed with the break points. At some small size it would be correct behavior to have them both left aligned on separate lines but not at the size displayed in the screenshot

**Comment by nwmac** [comment]
@bisht-richa  for now, can you revert the presentation back to the 2nd screen above.

**Comment by Josh-Diamond** [comment]
Ticket #7794 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-623addd2b1f055e7da84f74e130b7a92c4b2599e-head`:
1. Fresh install of rancher `v2.7-head`
2. Verified - Link alignment fixed; Fully responsive

Screenshots:
 
<img width="496" alt="Screenshot 2023-01-13 at 2 59 15 PM" src="https://user-images.githubusercontent.com/46494969/212427595-5f7f8631-2cc5-41d6-a6ef-6ef6493cf606.png">

<img width="799" alt="Screenshot 2023-01-13 at 2 59 27 PM" src="https://user-images.githubusercontent.com/46494969/212427603-f12d8ee4-ce0e-4c27-8068-d3ec3480376c.png">

<img width="1381" alt="Screenshot 2023-01-13 at 2 59 38 PM" src="https://user-images.githubusercontent.com/46494969/212427614-b2a7ec94-532d-45ce-9eca-be3d1a1de4ec.png">

<img width="1721" alt="Screenshot 2023-01-13 at 3 00 13 PM" src="https://user-images.githubusercontent.com/46494969/212427625-aa4272dc-f1e9-4cd0-86f9-da183426e17c.png">

**Comment by bisht-richa** [comment]
Reopening this as the current fix break banner in auth/config:

![Screenshot 2023-01-16 at 17.14.28.png](https://zube.io/files/rancher/f73985ecee306d1e7e6a040fb97b8e3d-screenshot-2023-01-16-at-17-14-28.png)

**Comment by Josh-Diamond** [comment]
Ticket #7794 - Test Results
---

With Docker on a single-node instance:

Verified on Rancher `v2.7-9278cf152f9b98ae3c543c0f956af2ae6ab91368-head`:
1. Fresh install of Rancher `v2.7-head`
2. Navigate to `Users & Authentication > Auth Providers`
3. Verified - Banner is fully responsive

Screenshots:
<img width="847" alt="Screenshot 2023-01-23 at 11 28 19 AM" src="https://user-images.githubusercontent.com/46494969/214121144-87b7e1ca-1dd7-4175-b766-7657e0202204.png">

<img width="1196" alt="Screenshot 2023-01-23 at 11 28 33 AM" src="https://user-images.githubusercontent.com/46494969/214121165-e218e789-5cfa-4a33-b5b3-5523bc3aed4f.png">

<img width="1396" alt="Screenshot 2023-01-23 at 11 28 47 AM" src="https://user-images.githubusercontent.com/46494969/214121178-59541c33-ba49-4e1d-bbe9-1144bb77de66.png">

<img width="1692" alt="Screenshot 2023-01-23 at 11 29 05 AM" src="https://user-images.githubusercontent.com/46494969/214121193-8c055dfe-e4f1-4a85-809c-667db8f86ca8.png">
