### ISSUE TITLE
Networking tab is missing in Edit Config page on rke2 provisioned cluster

### ISSUE THREAD

**Issue by thomashoell** [rancher/dashboard#7799]
**Setup**
- Rancher version: 2.7.0
- Browser type & version: latest Chrome or Firefox

**Describe the bug**
Networking tab is missing in the Edit Config page when editing an existing rke2 cluster.

**NOTE:** this was reported as an attempt to install from github using terraform

**To Reproduce**
Provision a rke2 cluster in Rancher 2.7.0, go to Cluster Configuration and edit the cluster config.
The cluster was provisioned using the vSphere driver.

**Result**
Networking tab is missing in Edit Config page

**Expected Result**
Networking tab should be present in Edit Config page

**Screenshots**
![image](https://user-images.githubusercontent.com/4695168/209155246-cdf1bf6f-5f2c-4065-98cd-d6c8bf7c9ac2.png)

**Additional context**
This is the same issue as described in https://github.com/rancher/dashboard/issues/5866

**Comment by jostmart** [comment]
Same problem here, in Rancher 2.7.1. 
I can help triage since I have another separate cluster that doesn't have this problem

**Comment by gaktive** [comment]
Internal reference: SURE-6641

**Comment by gaktive** [comment]
One user only experiences this missing tab when they create the cluster through github actions and terraform, whereas the exact same terraform code works fine when executed locally.

**Comment by richard-cox** [comment]
The network tab is shown if the prov cluster's spec.kubernetesVersion is set and matches a known version from those supplied by a request to `/v1-rke2-release/releases` (and that entry has serverArgs and agentArgs)

**Comment by richard-cox** [comment]
Currently waiting on update from customer, see comment in JIRA

**Comment by gaktive** [comment]
Interesting update from SURE-6641:

> [The user is] having a syntax problem with the version. Currently as it sits in github:
```
kubernetes_version = "v1.24.15-rke2r1" 
```
> so they must have typoed because there is a - where there should be + so this line needs to be corrected to:
```
kubernetes_version = "v1.24.15+rke2r1" 
```
> We tested this on our own test clusters and found this to be the root cause. When we use a `-` there is no networking tab. When there is a + there is a networking tab. We have let [them] know and are awaiting to hear back.

**Comment by gaktive** [comment]
Awaiting user feedback. This may slip out of Q3 if we don't hear anything by end of this week.

**Comment by richard-cox** [comment]
Customer has confirmed, fixing the typo resolved their issue
