### ISSUE TITLE
Not appears any pods on deployment(Dashboard)

### ISSUE THREAD

**Issue by rcgazevedo** [rancher/dashboard#780]
Using new dashboard, when I select deployment no pods are exhibited.
<img width="1402" alt="Deployment Example" src="https://user-images.githubusercontent.com/33674906/85072273-32dceb00-b18f-11ea-877a-5c8a987edfd7.png">

Rancher: v2.4.4
Kubernetes: 1.5 and 1.6.

**Comment by mantis-toboggan-md** [comment]
This should be resolved by [this PR](https://github.com/rancher/dashboard/pull/783), which includes a refactor of the pod retrieval logic on this page.

**Comment by deniseschannon** [comment]
This appears to be working in the latest set of changes.

**Comment by sowmyav27** [comment]
**On master-head commit id: `9b0dd20b7`**

- Deploy a deployment
- When it is in Active state go to the deployment details page
- Pod is not seen
<img width="1447" alt="Screen Shot 2020-08-06 at 5 07 29 PM" src="https://user-images.githubusercontent.com/26032343/89594954-190f6a00-d808-11ea-9175-d0a92a6786ef.png">

**Comment by mantis-toboggan-md** [comment]
The functionality around this table was re-done and I'm not seeing this issue. Can you verify that you're still seeing it?

**Comment by sowmyav27** [comment]
**On master-head - commit id: `33f755f18`**

- Create a deployment.
- Click on the deployment --> details page --> Pod is listed

<img width="1443" alt="Screen Shot 2020-09-16 at 9 35 03 PM" src="https://user-images.githubusercontent.com/26032343/93420770-7fa29180-f864-11ea-8182-98eb3d9915ab.png">
