### ISSUE TITLE
When deploying Rancher using an RKE2 or K3s cluster, the external/internal addresses are missing in Cluster Management

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#7802]
**Setup**
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/61f1b93bf0eca38c2f7583b8dcbf58d0c8ada4fe
- Browser type & version: Chrome

**Describe the bug**

When deploying Rancher with K3s or RKE2 as the local cluster, the external/internal IP do not appear in Cluster Management as shown below:

![Screen Shot 2022-12-22 at 3 14 25 PM](https://user-images.githubusercontent.com/52591819/209240878-ac84f438-48e5-4591-8a23-fe128a6de901.png)

![Screen Shot 2022-12-22 at 3 14 35 PM](https://user-images.githubusercontent.com/52591819/209240881-3388b020-526b-4568-8c6c-38ec68d31d5a.png)

Imported RKE1 clusters, Rancher-provisioned RKE2/K3s all correctly shows the external/internal IP addresses in Cluster Management. 

Additionally, when going to Cluster Explorer, the external/internal IP addresses correctly shows for imported RKE2/K3s acting as the local cluster. So this issue is specific to imported RKE2/K3s clusters in Cluster Management.

**To Reproduce**

1. Setup Rancher using RKE2 or K3s as the local cluster.
2. Navigate to Cluster Management > local.
3. Note that the external/internal IP addresses are missing.

**Result**
The external/internal IP addresses are missing in Cluster Management for imported RKE2/K3s clusters.

**Expected Result**

The external/internal IP addresses SHOULD NOT be missing in Cluster Management for imported RKE2/K3s clusters.

**Comment by jameson-mcghee** [comment]
I am also seeing this reproduce on Azure AKS Imported Clusters as well on `v2.7-head` (Commit ID: 6ee3949).

![image](https://user-images.githubusercontent.com/13294321/213242097-1020c3f1-6f60-421b-8d61-ff11adb7d177.png)

**Comment by jameson-mcghee** [comment]
> I am also seeing this reproduce on Azure AKS Imported Clusters as well on `v2.7-head` (Commit ID: 6ee3949).
> 
> ![image](https://user-images.githubusercontent.com/13294321/213242097-1020c3f1-6f60-421b-8d61-ff11adb7d177.png)

This issue is still reproducing on `v2.7.2-rc6`
![image](https://user-images.githubusercontent.com/13294321/226410288-69c6a14d-ac77-4ab0-95e8-ecbf196f308f.png)

**Comment by gaktive** [comment]
Verify current state.

**Comment by markusewalker** [comment]
Still seeing the same behavior on `v2.7-head` https://github.com/rancher/rancher/commit/d8a2bcae227717e16caa8519a3709f3e013673f2.

**Comment by nwmac** [comment]
Need to validate

**Comment by markusewalker** [comment]
Validated this against `v2.8-head` https://github.com/rancher/rancher/commit/e5ce94a4c8572a8af176188172a57805e1dc76a4.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/e5ce94a4c8572a8af176188172a57805e1dc76a4

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|Validate that IP addresses are shown in the local cluster|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Provisioned Rancher with K3S as the local cluster (Docker installation).
2. Navigated to Cluster Management > local.
3. Validated that the internal IP address is showing as expected.
4. Navigated to Cluster Explorer > local.
5. Validated that the internal IP address is showing as expected.
