### ISSUE TITLE
rke2 cluster struck at provisioning on harvester cluster.

### ISSUE THREAD

**Issue by beerendar** [rancher/dashboard#7813]
**Setup**
- Rancher version: V2.7.0
- Browser type & version: edge

**Describe the bug**

Harvester cluster with 2 nodes added to rancher, I tried deploying rke2 cluster with ( 3-etcd, 3-control-plane, 3-worker) but the cluster is struck at provisioning.

**To Reproduce**
1. Create harvester cluster with 2 node, same configurations.
2. deploy VM with opensuse and deploy rancher on top of it.
3. Open rancher in browser add harvester cluster in virtualization management.
4. deploy rke2 cluster with ( 3-etcd, 3-control-plane, 3-worker).

**Result**
Cluster struck at provisioning, log says "Waiting for viable init node".

**Expected Result**
Cluster to be up and running

**Screenshots**

![image](https://user-images.githubusercontent.com/36071195/209618418-6bbd375c-b53f-4e73-89a8-7867f505faf9.png)

**Additional context**

apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-dds9v
  creationTimestamp: "2022-12-26T18:23:22Z"
  finalizers:
  - wrangler.cattle.io/cloud-config-secret-remover
  - wrangler.cattle.io/provisioning-cluster-remove
  - wrangler.cattle.io/rke-cluster-remove
  generation: 2
  managedFields:
  - apiVersion: provisioning.cattle.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"wrangler.cattle.io/cloud-config-secret-remover": {}
          v:"wrangler.cattle.io/provisioning-cluster-remove": {}
          v:"wrangler.cattle.io/rke-cluster-remove": {}
      f:spec:
        .: {}
        f:cloudCredentialSecretName: {}
        f:kubernetesVersion: {}
        f:localClusterAuthEndpoint: {}
        f:rkeConfig:
          .: {}
          f:chartValues:
            .: {}
            f:harvester-cloud-provider:
              .: {}
              f:cloudConfigPath: {}
              f:clusterName: {}
            f:rke2-calico: {}
          f:etcd:
            .: {}
            f:snapshotRetention: {}
            f:snapshotScheduleCron: {}
          f:machineGlobalConfig:
            .: {}
            f:cni: {}
            f:disable-kube-proxy: {}
            f:etcd-expose-metrics: {}
            f:profile: {}
          f:machinePools: {}
          f:machineSelectorConfig: {}
          f:registries: {}
          f:upgradeStrategy:
            .: {}
            f:controlPlaneConcurrency: {}
            f:controlPlaneDrainOptions:
              .: {}
              f:deleteEmptyDirData: {}
              f:disableEviction: {}
              f:enabled: {}
              f:force: {}
              f:gracePeriod: {}
              f:ignoreDaemonSets: {}
              f:postDrainHooks: {}
              f:preDrainHooks: {}
              f:skipWaitForDeleteTimeoutSeconds: {}
              f:timeout: {}
            f:workerConcurrency: {}
            f:workerDrainOptions:
              .: {}
              f:deleteEmptyDirData: {}
              f:disableEviction: {}
              f:enabled: {}
              f:force: {}
              f:gracePeriod: {}
              f:ignoreDaemonSets: {}
              f:postDrainHooks: {}
              f:preDrainHooks: {}
              f:skipWaitForDeleteTimeoutSeconds: {}
              f:timeout: {}
    manager: rancher
    operation: Update
    time: "2022-12-26T18:23:22Z"
  - apiVersion: provisioning.cattle.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:clusterName: {}
        f:conditions: {}
        f:observedGeneration: {}
    manager: rancher
    operation: Update
    subresource: status
    time: "2022-12-26T18:23:22Z"
  name: axon-dev
  namespace: fleet-default
  resourceVersion: "97279"
  uid: bf6872fa-ba44-40aa-91c6-a5ed7d6f6ab7
spec:
  cloudCredentialSecretName: cattle-global-data:cc-87fh2
  kubernetesVersion: v1.24.8+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      harvester-cloud-provider:
        cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
        clusterName: axon-dev
      rke2-calico: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
      profile: null
    machinePools:
    - controlPlaneRole: true
      etcdRole: true
      machineConfigRef:
        kind: HarvesterConfig
        name: nc-axon-dev-pool1-jd9hb
      name: pool1
      quantity: 3
      unhealthyNodeTimeout: 0s
      workerRole: true
    machineSelectorConfig:
    - config:
        cloud-provider-config: secret://fleet-default:harvesterconfiggpflz
        cloud-provider-name: harvester
        protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: "1"
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: "1"
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  clusterName: c-m-rzq5ccdn
  conditions:
  - lastUpdateTime: "2022-12-26T18:23:22Z"
    status: "True"
    type: HarvesterCloudProviderConfigMigrated
  - lastUpdateTime: "2022-12-26T18:23:22Z"
    reason: Reconciling
    status: "True"
    type: Reconciling
  - lastUpdateTime: "2022-12-26T18:23:22Z"
    status: "False"
    type: Stalled
  - lastUpdateTime: "2022-12-26T18:23:26Z"
    status: "True"
    type: Created
  - lastUpdateTime: "2022-12-26T18:23:24Z"
    status: "True"
    type: RKECluster
  - lastUpdateTime: "2022-12-26T18:23:22Z"
    status: "True"
    type: BackingNamespaceCreated
  - lastUpdateTime: "2022-12-26T18:23:22Z"
    status: "True"
    type: DefaultProjectCreated
  - lastUpdateTime: "2022-12-26T18:23:22Z"
    status: "True"
    type: SystemProjectCreated
  - lastUpdateTime: "2022-12-26T18:23:22Z"
    status: "True"
    type: InitialRolesPopulated
  - lastUpdateTime: "2022-12-26T18:23:23Z"
    status: "True"
    type: CreatorMadeOwner
  - lastUpdateTime: "2022-12-26T18:23:24Z"
    message: waiting for viable init node
    reason: Waiting
    status: Unknown
    type: Provisioned
  - lastUpdateTime: "2022-12-26T18:23:24Z"
    status: "True"
    type: NoDiskPressure
  - lastUpdateTime: "2022-12-26T18:23:24Z"
    status: "True"
    type: NoMemoryPressure
  - lastUpdateTime: "2022-12-26T18:23:24Z"
    status: "True"
    type: SecretsMigrated
  - lastUpdateTime: "2022-12-26T18:23:24Z"
    status: "True"
    type: ServiceAccountSecretsMigrated
  - lastUpdateTime: "2022-12-26T18:23:25Z"
    status: "False"
    type: Connected
  observedGeneration: 2

**Comment by richard-cox** [comment]
Closing stale issue. If you still see this behaviour in the latest rancher please re-open
