### ISSUE TITLE
`Scale Down` doesn't work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#7814]
**On Rancher 2.7-head commit id: `28a84c7`**

- Deployed a k3s node driver cluster
- Select a node and click on `Scale Down`
- The pop up shows `Create` button. It should say `Delete` instead.

<img width="517" alt="Screen Shot 2022-12-28 at 12 55 34 PM" src="https://user-images.githubusercontent.com/26032343/209875330-acab8935-e1f7-4646-9a9b-a417cdcac9b6.png">

- Also on clicking on Create, no API request is sent. The button doesn't seem to work

**Comment by richard-cox** [comment]
@torchiaf This is definitely a regression, there should be a custom model shown that works out if the selected nodes can be scaled. From memory there were a few model PRs that recently merged, might be related

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 48d1f8e
Rancher cluster type: single-node docker install
Docker version: 20.10

Downstream cluster type: k3s and rke2

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy a k3s/rke2 node driver cluster - multiple machine pools
2. Select a node and click on Scale Down
3. Verify pop-up dialog window

**Result**
Now Rancher confirms with user that a machine is being deleted and also gives user the option to opt out of future warnings
![image.png](https://zube.io/files/rancher/d161770b493cf3a59f32fcf68921025c-image.png)
