### ISSUE TITLE
Cluster/Nodes status do not update automatically and needs a browser refresh

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#7815]
**On 2.7-head commit id: `28a84c7`**

- Deploy a cluster - k3s node driver (cluster type should not matter)
- Clusters goes into updating state, but a refresh of the browser (Chrome browser) is required for the right state to be displayed.
- This seems to be happening quite often and is annoying to refresh multiple times, when deploying a cluster, or deleting nodes.

**Comment by richard-cox** [comment]
Linking possible related #7819

**Comment by gaktive** [comment]
Upon discussion with @sowmyav27, this was not the case with 2.6.x. All QA engineers are now taking into consideration that they have to reload every page when they're walking through the UI with 2.7-head.

She'll confirm via some testing and update this ticket.

**Comment by torchiaf** [comment]
Hi @sowmyav27, can you share more details on how to replicate the bug ? I ma trying to create a cluster using DigitalOcean, version `v1.24.9+k3s2`, but I an't replicate it

**Comment by torchiaf** [comment]
The issue is caused by this block of code: https://github.com/rancher/dashboard/commit/281ee2335de86bc00aa40de71cdec07da01edcf0

**Comment by richard-cox** [comment]
@torchiaf Can you provide the reliable way you reproduced the issue? That block of code handles how the dashboard reconnects the management web socket (used for resource change events) after the backend periodically closes it (every 30ish minutes). Does that align with your repo steps?

**Comment by richard-cox** [comment]
Think [this](https://github.com/rancher/rancher/issues/40558) is the root cause

**Comment by richard-cox** [comment]
This is persistently inconsistent. Findings in https://github.com/rancher/rancher/issues/40558#issuecomment-1434462942 (tl;dr at end)

**Comment by Josh-Diamond** [comment]
Ticket #7815 - Test Results - ✅ 
---

Verified w/ Docker on a single-node instance using Rancher `v2.7-211409c9a689d8ee4d801ed1bce1d887b0fb4b00-head`:

| Scenario | Test Case | Result|
|---|---|---|
| 1. | Provision downstream k3s - 1 node, all roles => delete | ✅ |
| 2. | Provision downstream k3s - 3 nodes, individual roles => delete | ✅ |
| 3. |Provision downstream k3s - 8 nodes: 3 etcd, 2 cp, 3 wkr => delete| 💹 |

---

Scenario 1 -
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream AWS Node driver k3s cluster w/ a single-node, all roles
3. Do not refresh the page, and observe accurate state and condition transitions
4. Once `active`, delete the cluster
5. Do no refresh the page, and observe the cluster successfully delete
6. Verified - no refresh needed, state/conditions change + are displayed via UI as expected

---

Scenario 2 -
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream AWS Node driver k3s cluster w/ 3 nodes, individual roles
3. Do not refresh the page, and observe accurate state and condition transitions
4. Once `active`, delete the cluster
5. Do no refresh the page, and observe the cluster successfully delete
6. Verified - no refresh needed, state/conditions change + are displayed via UI as expected

---

Scenario 3 -
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream AWS Node driver k3s cluster w/ 8 nodes, (3 etcd, 2cp, 3 wkr)
3. Do not refresh the page, and observe accurate state and condition transitions
4. Once `active`, delete the cluster
5. Do no refresh the page, and observe the cluster successfully delete
6. Verified - no refresh needed, state/conditions change + are displayed via UI as expected
