### ISSUE TITLE
RKE2/K3s Custom cluster registration form has incorrect label for node name field, under Advanced (settings)

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#7817]
**Setup**
- Rancher version: `v2.7-c81b8b45136f3b5d26d41dca9ef0ddcabd2e026c-head`
- Browser type & version: `Chrome`

**Describe the bug**
RKE2/K3s Custom cluster registration form has incorrect label for node name field, under Advanced (settings)

**To Reproduce**
1. Fresh install of rancher `v2.7-head`
2. Create a downstream custom RKE2/K3s cluster
3. Navigate to Cluster Details > Registration > Advanced (Step 2) > Node Name (field)
4. Reproduced

**Result**
Node Name field has a label of `%cluster.custom.advanced.nodeName%`

**Expected Result**
Node Name field should have a label of `Node Name`

**Screenshots**
<img width="1379" alt="Screenshot 2022-12-29 at 11 04 50 AM" src="https://user-images.githubusercontent.com/46494969/209991972-00e0bc90-8e3f-4d28-89ea-df54ff671c54.png">

**Additional context**

`Expected Result` - [ seen on 2.7.0 ]
<img width="1397" alt="Screenshot 2022-12-29 at 11 13 52 AM" src="https://user-images.githubusercontent.com/46494969/209992857-c20d9f40-cbee-4556-92dd-81ff41211a4b.png">

**Comment by rak-phillip** [comment]
It looks like `group.policy` was also changed from camelCase to PascalCase in #7573. We might want to do a quick review of other updated translations in `shell/assets/translations/en-us.yaml` to make sure that there aren't more regressions similar to this.

**Comment by torchiaf** [comment]
Double checked the PascalCase changes and all looks good. Should we define a guidelines to define the keys? For example use only camelCase.

**Comment by rak-phillip** [comment]
I think developing guidelines makes sense, especially if they will help encourage consistency 🙂

**Comment by Josh-Diamond** [comment]
Ticket #7817 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-8062f1e3ab7bff870dfab195ff699a308644168a-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream RKE2 Custom cluster
3. Once "Create" is selected, navigate to `Registration > Show Advanced > Node Name`
4. Verified - `Node Name` field has appropriate label; as expected
5. Provision a downstream K3s Custom cluster
6. Once "Create" is selected, navigate to `Registration > Show Advanced > Node Name`
7. Verified - `Node Name` field has appropriate label; as expected

Screenshots:

`RKE2`
<img width="1098" alt="Screenshot 2023-01-09 at 3 38 08 PM" src="https://user-images.githubusercontent.com/46494969/211422790-9f1854e5-d63c-4569-9fe6-051db31bd80a.png">

`K3s`
<img width="1094" alt="Screenshot 2023-01-09 at 3 38 54 PM" src="https://user-images.githubusercontent.com/46494969/211422815-2215f79d-9eeb-4286-8e64-38f164db5f24.png">
