### ISSUE TITLE
RKE2 cluster stays in updating state even after scaled up nodes are active

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#7819]
Setup

Rancher version: 2.7-head 28a84c7
Browser type & version: Chrome

**Describe the bug**
When we scale up nodes in a node pool of an rke2 node driver cluster, cluster goes into updating state immediately. but once the nodes are active, cluster stays in `Updating` state and the state changes only on a hard refresh of the UI

**To Reproduce**
1. Create a node driver rke2 cluster with 3 node pools 1 for each role - worker, etcd, cp 
2. Click on scale up/scale down button on the worker pool or any other node pool

**Result**
Cluster goes into updating state and never comes back active. It only comes back active when we hard refresh the UI.

**Expected Result**
Expected the state to get back to `active` when the nodes get to active state.

**Screenshots**
Notice in the screenshot, all the nodes are active and the state on the cluster management page is in `Updating`
<img width="500" alt="2022-12-29_09-52-52" src="https://user-images.githubusercontent.com/38144301/210007440-aedce63d-b7c2-4331-8940-7d0caeb85539.png">

**Additional context**

- This gives a bad UX/UI look and feel. 
- This is not the case for RKE1 clusters as the clusters states stay in `Active` while scaling the node up/down
- This is also seen on 2.7.0
- Similar issue: https://github.com/rancher/dashboard/issues/7815

**Comment by richard-cox** [comment]
Linking possibly related #7815

**Comment by richard-cox** [comment]
Think [this](https://github.com/rancher/rancher/issues/40558) is the root cause

**Comment by richard-cox** [comment]
This is persistently inconsistent. Findings in https://github.com/rancher/rancher/issues/40558#issuecomment-1434462942 (tl;dr at end)

**Comment by anupama2501** [comment]
Verified on v2.7-head 2b2ed44

- Created an rke2 node driver cluster
- Added a cluster owner and cluster member in the rke2 cluster
- Scale up node pools - on rke2 cluster and notice that the cluster state goes from updating to active for cluster owner, cluster member and admin.
- Scale down nodes -  on rke2 cluster and notice that the cluster state goes from updating to active for cluster owner, cluster member and admin.
