### ISSUE TITLE
Unable to copy output from a kubectl shell

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#7820]
Setup

Rancher version: 2.7-head 28a84c7
Browser type & version: Chrome

**Describe the bug**
Unable to highlight and copy the output from a kubectl shell.

**To Reproduce**
1. Create an rke1/rke2 node driver/custom cluster - cluster type does not matter.
2. From the explorer page >> select kubectl shell
3. Try to highlight the content from the kubectl shell

**Result**
Output/content cannot be highlighted and copied.

**Expected Result**
Expected to be able to highlight/copy the output from kubectl shell.

**Additional context**
Similar issue: https://github.com/rancher/dashboard/issues/7524
Works on 2.7.0/2.6.9

**Comment by richard-cox** [comment]
@anupama2501 Can you confirm your `ui-dashboard-index` setting? I've just given this a test and it seems to work ok 

![image](https://user-images.githubusercontent.com/18697775/210332864-3d6e79ac-aaec-457d-a5ae-ef830652e882.png)

**Comment by torchiaf** [comment]
I am able to replicate the issue running version: `2.7-head e5a9789`.
It' s a regression introduced after `xterm.js` package upgrade: https://github.com/rancher/dashboard/pull/7666/commits/4b12313b0d7f9581148091b62a5e042f6885cebd

**Comment by anupama2501** [comment]
Verified on v2.7-head `2b2ed44`

- Verified as a standard user, able to execute into kubectl shell and copy the text output
- Verified as an admin, able to execute into kubectl shell and copy the text output.
- Verified able to execute into pods and copy the text output.

**Comment by kspradheep** [comment]
Hello @anupama2501 we see this issue in v2.7.5 Could you please confirm if this was expected?

**Comment by richard-cox** [comment]
I couldn't reproduce this bug in v2.7.5 in Chromium: 115.0.5790.171 using the steps to reproduce.

@kspradheep can you provide more details?

**Comment by kspradheep** [comment]
@richard-cox It appears keyboard commands are not working (ctrl+c/ctrl+v) but worked with cursor right-click copy and paste options. I tried these in below browser versions:
Microsfot Edge: Version 115.0.1901.200
Google Chrome: Version 115.0.5790.171
![image](https://github.com/rancher/dashboard/assets/68883779/2291c9b3-94df-4c8c-95f8-85f523d02e21)

is this expected behavior?

**Comment by kspradheep** [comment]
Got it. Thank you @richard-cox
