### ISSUE TITLE
Helm Chart Details Page: Multiple versions shown

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7826]
**Setup**
- Rancher version: 2.7-head

**Describe the bug**
- Versions are duplicated in the chart detail page

**To Reproduce**
- Nav to explorer for the `local` cluster --> `Apps` --> click on any chart

**Result**
- Multiple entries for the same version appear in the `Chart Versions` list on the right

**Expected Result**
- Only a single entry for a version is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/18697775/210346550-19478685-8e30-4d09-91bb-2a31a5f83511.png)

**Additional context**
Follow on work
The user should be able to optionally see `devel` chart versions (off by default). There was a toggle to enable this somewhere, but seems to have been lost. We should understand how that setting affects this list and where the settings should go

**Comment by gaktive** [comment]
This may be possibly backend related since prior to `2.7-head`, this works. Should be a quick fix.

**Comment by nwmac** [comment]
This is not a backend issue - it seems each time we go to the chart, we add the versions again, so they keep stacking up.

Need to understand where this regression came from.

**Comment by catherineluse** [comment]
I reproduced the issue, but not on the first time loading the page. The first time I went to the Datawiza Access Broker chart, the versions looked correct. I had to visit the page again to see the issue.

**Comment by catherineluse** [comment]
The helm chart data is loaded with this async call:

```js
await this.$store.dispatch('catalog/load'});
```

A month ago, a change was made (https://github.com/rancher/dashboard/pull/7672) to force fetch the data:

```js
await this.$store.dispatch('catalog/load', { force: true });
```

The error goes away if the data is not force fetched. I'm going to try to fix the behavior while keeping the force fetch, assuming that it was important for fixing the bug it was intended to address.

**Comment by AndrewHoffmanQA** [comment]
retested in 2.7.2-rc4
test- passed
charts are displaying their version number as expected 
screenshot:
![image.png](https://zube.io/files/rancher/81d069fccea5ce035dff7acc4c758523-image.png)
