### ISSUE TITLE
[BUG]ui display error

### ISSUE THREAD

**Issue by 467892746** [rancher/dashboard#7828]
**Rancher Server Setup**
- Rancher version:
  2.6.9
- Installation option (Docker install/Helm Chart):
  Helm Chart
  
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7-eks-fb459a0", GitCommit:"c240013134c03a740781ffa1436ba2688b50b494", GitTreeState:"clean", BuildDate:"2022-10-24T20:36:26Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

**Describe the bug**
![image](https://user-images.githubusercontent.com/46819001/209523297-83af3bb8-27ef-4f0e-98bd-9a3a09c954ed.png)

This should be timeout?
**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by rak-phillip** [comment]
@gaktive transferred this one to dashboard and raised a PR to fix.

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: 48d1f8e), I was able to verify that the header for the field in question has now been updated to state "_Timeout_" correctly. Therefore I am closing this ticket as Done.

![image](https://user-images.githubusercontent.com/13294321/213009513-f5b9309b-c96e-446e-b202-a5c94b4682af.png)
