### ISSUE TITLE
[BUG] "Allow collection of anonymous statistics" message is missing from UI upon fresh install of Rancher 2.7-head

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#7840]
**Setup**
- Rancher version: `v2.7-8062f1e3ab7bff870dfab195ff699a308644168a-head`
- Browser type & version: `Chrome`

**Describe the bug**
"Allow collection of anonymous statistics" message is missing from UI upon fresh install of Rancher 2.7-head.  Only the checkbox is visable.

**To Reproduce**
1. Fresh install of rancher `v2.7-head`
2. Copy/paste bootstrap password
3. Reproduced

**Result**
<img width="650" alt="Screenshot 2023-01-04 at 3 36 49 PM" src="https://user-images.githubusercontent.com/46494969/210663168-c2b14129-c563-440c-bdfb-4a1b5d2d562c.png">

**Expected Result**
<img width="613" alt="Screenshot 2023-01-04 at 3 29 27 PM" src="https://user-images.githubusercontent.com/46494969/210663192-d74c0697-7bcc-4c7a-a038-6ae9fb5ae7d6.png">

**Comment by nwmac** [comment]
@bisht-richa Can you take a look?

**Comment by bisht-richa** [comment]
This bug is fixed in this PR: https://github.com/rancher/dashboard/pull/7863

**Comment by Josh-Diamond** [comment]
Ticket #7840 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-623addd2b1f055e7da84f74e130b7a92c4b2599e-head`:
1. Fresh install of rancher `v2.7-head`
2. Verified - "Allow collection of anonymous statistics" message is seen and accurate

Screenshots:
<img width="1353" alt="Screenshot 2023-01-13 at 1 22 15 PM" src="https://user-images.githubusercontent.com/46494969/212424445-f35b409e-299c-4bee-b0ee-b7fb99287368.png">

<img width="1351" alt="Screenshot 2023-01-13 at 1 22 31 PM" src="https://user-images.githubusercontent.com/46494969/212424462-9e01f29e-acfa-472d-87c1-6c4712e56b31.png">
