### ISSUE TITLE
[Bug] Multi select form field does not expand

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#7842]
**Setup**
- Rancher version: 2.7.0
- Browser type & version: Chrome

**Describe the bug**
The multi select form fields do not expand in height if you select more items than could fit into a single line. The selected items then overflow out of the form field.

**To Reproduce**
* Go to a page with a multi select form field, e.g. Logging -> Cluster Flows -> Create
* Pick a lot of items

**Result**
The form field does not expand in height and the items overflow the field.

**Expected Result**
The form field expands.

**Screenshots**
![Bildschirm­foto 2023-01-05 um 10 53 22](https://user-images.githubusercontent.com/243056/210753849-ecb81e91-f087-4e46-aa0d-cb62af5f5ad4.png)

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: 48d1f8e), I was able to validate that the field now expands to accommodate multiple rows. Therefore I am closing this ticket as Done.

![image](https://user-images.githubusercontent.com/13294321/212992668-12cf2186-dcad-45d0-93c6-bf8d28a2134f.png)
