### ISSUE TITLE
Padding around textboxes seems to have gone missing

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#785]
Some change has affected the padding around some input boxes

<img width="1179" alt="Screen Shot 2020-06-22 at 4 00 55 PM" src="https://user-images.githubusercontent.com/11410997/85360814-19a9a680-b4cf-11ea-9314-f542ea980e46.png">

**Comment by sowmyav27** [comment]
**Validated on master-head - commit id: 16616de9c**

- Padding in Secret --> Create --> type: Registry looks good now 
<img width="1431" alt="Screen Shot 2020-07-17 at 5 58 07 PM" src="https://user-images.githubusercontent.com/26032343/87841073-9bcf8580-c857-11ea-943d-ef95f9b713c9.png">
