### ISSUE TITLE
Change rke2 cloud provider verbage

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#7851]
**Description:**
Currently, the Cloud Provider box for RKE2 defaults to `(None)`, which is a bit of a misnomer and has led to many users coming to Slack asking about it. This setting actually supplies no explicit cloud provider for rke2, which means that rke2 will use its own built in cloud provider stub. Then, if a user wants to install their own external cloud provider (vsphere, for example), they try and fail because there is actually already a cloud provider (the built in stub) in the cluster. 
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/55997940/210856482-b5c73951-369b-4ba1-92c5-de8c14c5b52c.png">

**Desire:**
It would be helpful if we changed the language used here. I'm not sure what would be best, but some ideas we have are:
1. `None (RKE2 Embedded)`
2. `RKE2 Embedded`
3. `Default - RKE2 Embedded`

This would just need to change the value that is shown in the UI, not the value that is passed through the API.

**Comment by gaktive** [comment]
Option 3 looks the clearest here.

**Comment by Josh-Diamond** [comment]
Ticket #7851 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-1913156a9f32ded561ab100ff0ce7f9135ad8e85-head`:
1. Fresh install of rancher `v2.7-head`
2. Begin to provision the following downstream clusters:
    - RKE2 AWS Node driver
    - RKE2 Azure Node driver
    - RKE2 Linode Node driver
3. For each, Navigate to `Cloud Provider` and view default value + dropdown values
4. Verified - default + dropdown values as expected

Screenshots:

`AWS`
<img width="595" alt="aws-proof" src="https://user-images.githubusercontent.com/46494969/212160188-02df3b87-05c8-41b2-8d8c-6deb963b68c4.png">

`Azure`
<img width="602" alt="azure-proof" src="https://user-images.githubusercontent.com/46494969/212160215-c4edfb6c-dfc3-4afe-90c6-32c6955b47f6.png">

`Linode`
<img width="518" alt="linode-cloud-provider" src="https://user-images.githubusercontent.com/46494969/212160233-048189aa-816c-462a-b599-98a550ac27c8.png">
