### ISSUE TITLE
Guest cluster hostname and machine name doesn't match

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7854]
Internal reference: SURE-5707
Reported in 2.6.9

Issue description:
When debugging the guest cluster, the user noticed the following:

```
apiVersion: v1
kind: Node
metadata:
annotations:
cluster.x-k8s.io/cluster-name: NAME-cluster
cluster.x-k8s.io/cluster-namespace: fleet-default
cluster.x-k8s.io/machine: NAME-cluster-master-5cc95bb5c-9w5gp
cluster.x-k8s.io/owner-kind: MachineSet
cluster.x-k8s.io/owner-name: NAME-cluster-master-5cc95bb5c
csi.volume.kubernetes.io/nodeid: '{"driver.harvesterhci.io":"NAME-cluster-master-a174ede7-f8677"}'
etcd.rke2.cattle.io/node-address: 10.2.22.150
etcd.rke2.cattle.io/node-name: NAME-cluster-master-a174ede7-f8677-68d20c17
...
egress.rke2.io/cluster: "true"
kubernetes.io/arch: amd64
kubernetes.io/hostname: NAME-cluster-master-a174ede7-f8677
kubernetes.io/os: linux
...
name: NAME-cluster-master-a174ede7-f8677 
```

As you can see, `cluster.x-k8s.io/machine` [NAME-cluster-master-5cc95bb5c-9w5gp] and `kubernetes.io/hostname` [NAME-cluster-master-a174ede7-f8677] are not matching. When the user opens a SSH shell in the UI, it is showing "cluster.x-k8s.io/machine" as the title of the terminal while the node's name in the node list is "kubernetes.io/hostname". It is confusing because there is no node "NAME-cluster-master-5cc95bb5c-9w5gp". Node is only shown as the hostname inside the shell session.

User impact:
UI inconsistency can lead to confusion and running commands on the wrong node in the downstream cluster

Repro steps:

- Start the downstream cluster
- Connect to a cluster node over SSH in Rancher UI

Workaround: none

Actual behavior:
The UI tab displays machine/cluster name

Expected behavior:
The UI tab should display node hostname

**Comment by gaktive** [comment]
Automated test to be added by UI engineering in https://github.com/rancher/dashboard/issues/8773

**Comment by gaktive** [comment]
Automation not possible for this task for Q2 so we'll need manual testing for this or whatever QA has for this. Engineering to look at how to automate cluster provisioning, beginning with Q3.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 95edd02`

1. created downstream rke2 cluster
2. cluster > nodes > edit yaml
3. hostname reflected correctly in ui and in yaml

![2023-05-12_14-29-42.png](https://zube.io/files/rancher/8e2c3982f0a3e6e83ea17d160705b989-2023-05-12_14-29-42.png)
