### ISSUE TITLE
Web Worker fails to work following change of cluster

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7862]
**Setup**
- Rancher version: 2.7-head (2.7.next1 timeframe)

**Describe the bug**
When a user switches clusters
- `cluster/unsubscribe` is called
- subscribe handler then sends a msg to web worker to destroy itself i.e. `worker.postMessage({ destroyWorker: true })`
- web worker destroys itself "terminates" itself via `close` (see [docs](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/close#examples))
- web worker requests ui thread to remove itself via `destroyWorker`, which removes the worker instance from `store.$workers`
- the web worker then isn't available when future SCHEMA changes happen

> worker is created in `createWorker` called via `steveStoreInit` which only happens initially on first load

> I've marked this as dev-validate, as it's hard to find a nice way to show the error without hacking code.

The functional impact i _think_ is that we lose the custom schema handling in clusters that we've switched to

**To Reproduce**
- Deploy an additional cluster to switch to (RKE2)
- Add `console.warn('web-worker: removeSchema');` to `removeSchema` in `shell/plugins/steve/web-worker.steve-sub-worker.js`
- Open the browsers dev tools on the network WS tab
- Load/refresh in the local cluster's explorer page
- Navigate to the RKE2 cluster --> CRD list
- Clear the network WS tab socket messages for the cluster socket
- Create a CRD (https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)
  - Note the `resource.create` socket message for the new SCHEMA
- Delete the new CRD
  - Note the `resource.remove` socket message for the new SCHEMA

Note - In theory just editing the CRD should provide a `resource.change` for the associated SCHEMA, but this wasn't happening for me

Note - the above can also be done with `loadSchemas` and switching between clusters

**Result**
- No log output

**Expected Result**
- Log output

**Comment by nwmac** [comment]
@richard-cox Do we need to do this for 2.7.next2 ?

**Comment by richard-cox** [comment]
Nope! Bumping

**Comment by nwmac** [comment]
Only an issue in the basic worker - moving to advanced worker - wont fix
