### ISSUE TITLE
Many words are still in English characters when changing to Chinese Language

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#7865]
**Setup**
- Rancher version: `v2.6.9` and `v2.7-head` (Commit ID: 8062f1e)
- Browser type & version: Brave

**Describe the bug**
When changing to Chinese, many of the characters/words are still in English

**To Reproduce**
1. Navigate to the Explore view for the `local` cluster
2. Change the language to Chinese

**Result**
Many of the Words and Characters on the page remain in English

**Expected Result**
All characters and words through out the entire Rancher app are changed to Chinese words/characters

**Screenshots (these are examples I observed, but this issue is prolific throughout the application**
![image](https://user-images.githubusercontent.com/13294321/211106468-00314f4c-c47c-4266-a837-50bd872f6ae3.png)
![image](https://user-images.githubusercontent.com/13294321/211106478-2a4b91e0-77fd-458b-86c2-45311de039b1.png)
![image](https://user-images.githubusercontent.com/13294321/211106492-c5bd4e53-b79f-430c-80be-60bc9d3931f3.png)
![image](https://user-images.githubusercontent.com/13294321/211106512-f83fcd71-003d-4e8d-a662-aec3ea2c1259.png)
![image](https://user-images.githubusercontent.com/13294321/211106535-340fef74-00ec-4b6e-978f-455d3dfb4e0c.png)
![image](https://user-images.githubusercontent.com/13294321/211106547-7ffe67ab-644a-464d-9573-bc52616f715c.png)
![image](https://user-images.githubusercontent.com/13294321/211106560-48b4f626-b1e4-4d36-a5eb-cec3e93443c1.png)
![image](https://user-images.githubusercontent.com/13294321/211106574-1647a56d-e422-4bd1-9d02-839df06531ea.png)

Related:
[7786](https://github.com/rancher/dashboard/issues/7786)

**Comment by brandond** [comment]
It would not be correct to localize resource types or names. You can reference the upstream Kubernetes docs, where Kubernetes is still Kubernetes, Pods are still Pods, and so on. When resources have a single proper representation in the ASCII character set, it is NOT correct to localize them.

You can refer to the upstream docs as an example:
![image](https://user-images.githubusercontent.com/370103/211112776-a2c4bee5-746e-49a7-bdc4-daae527b2fcd.png)

**Comment by richard-cox** [comment]
Agree with @brandond, some text is not translatable. 

All of the `zh-hans` translations come from the Harvester team. @vickyhella Can you let us know if there's any  translations referenced in the description that still need doing, or can we close this issue?

**Comment by vickyhella** [comment]
@richard-cox I agree with @brandond. I think this issue can be safely closed.

Actually, most of the strings that require translation are already translated. The untranslated ones are either keywords that shouldn't be translated, or newly added strings that will be translated in coming translation PRs, unless they are not extracted to the `en-us.yaml` file yet (which requires frontend's help, I guess).

**Comment by richard-cox** [comment]
Thanks @vickyhella!

Going on above I'll bump to `Test` to close

**Comment by jameson-mcghee** [comment]
Per @brandond, @richard-cox, and @vickyhella, this issue is to be closed without changes to the UI.
