### ISSUE TITLE
Force refresh of the UI is needed after the initial rancher setup

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#7867]
**Setup**
- Rancher version: v2.7.2-rc1
- Browser type & version: Chrome

**Describe the bug**
After the fix from https://github.com/rancher/rancher/issues/39094, we require to refresh the UI, to accept a new certificate as an enhancement.

**To Reproduce**
1. Install rancher server v2.7.2-rc1 on a docker install 
2. After the initial basic setup, open network tab and notice the console errors:
<img width="400" alt="2023-01-03_13-40-03" src="https://user-images.githubusercontent.com/38144301/211114504-67084e37-5339-4a65-a7bf-ba78ae4c405d.png">

**Result**
Refresh the UI, users are made to accepts the cert and the errors are not seen anymore.

**Expected Result**
UI to trigger the force refresh.

**Comment by gaktive** [comment]
The backend fix for this has changed how the browser recognizes certificates, which is going to take time to figure out as we'll need to work with the backend to sort out what's what.

Workaround: on Chrome, when you go to Rancher, accept the self-signed certificate and go through the setup process. Once done, go to the browser URL bar and click on the warning icon to accept the new certificate.

**Comment by gaktive** [comment]
UI won't do anything here since this was a backend break. Let us know if this is still an issue.

**Comment by anupama2501** [comment]
Closing the ticket as this is not an issue anymore.
