### ISSUE TITLE
Events list default sort should be `Last Seen` rather than `Name`

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7872]
![image](https://user-images.githubusercontent.com/18697775/211338242-66456a19-0414-4a4f-b597-d0fda5a8a66d.png)

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: e54432e), I was able to verify that the Sort Default on the Events page grid is now _Last Seen_. Therefore I am closing this ticket.

![image](https://user-images.githubusercontent.com/13294321/212168023-d9f131bd-4bb7-4c31-b72e-f72461be9c7c.png)
