### ISSUE TITLE
When switching from Edit Yaml to Edit Form, the UI breaks for RKE2/K3s

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/dashboard#7876]
**Setup**
- Rancher version: v2.7-head 8062f1e
- Browser type & version: Chrome Build 108

**Describe the bug**

When creating an RKE2/K3s cluster, when user switches back to `Edit Form` from `Edit Yaml` the UI breaks
![image](https://user-images.githubusercontent.com/108360907/211367721-8a6e5b5a-8451-4cfd-910e-138e70fd6daa.png)

There is an `Error loading schema for cloudcredential` error displayed at the top along with a `Cancel` `Back to Form` and `Create` button. The pop-up box asking user if they want to switch back to editing form is also layered beneath the Edit Form config page

**To Reproduce**

1. Create rke2/k3s cluster
2. Click `Edit Yaml`
3. Click `Back to Form`

**Result**
The UI breaks as stated above in the description
![image](https://user-images.githubusercontent.com/108360907/211367721-8a6e5b5a-8451-4cfd-910e-138e70fd6daa.png)

**Expected Result**

The UI should not break and the Edit Form page should load successfully

**Comment by richard-cox** [comment]
@thaneunsoo Could you provide the output of the browser's console? I tried to reproduce this on an older backend (7d16a0d) with a DO cluster and couldn't, so could be something Azure related

**Comment by thaneunsoo** [comment]
@richard-cox here you go, please let me know if you are asking for something else
![image.png](https://zube.io/files/rancher/9dcd5ebccd0f31ecf32cb8db8dd41064-image.png)

**Comment by richard-cox** [comment]
@thaneunsoo right location, but looks like a lot is missing. Are there any errors, or anything that's output when you switch back to the form view?

**Comment by thaneunsoo** [comment]
@richard-cox I just get this
![image.png](https://zube.io/files/rancher/863792629ed4063e5364a96904573854-image.png)

**Comment by catherineluse** [comment]
I repro'd the `Error loading schema for cloudcredential`, but not the CSS glitch.

The error only appeared if I changed a value in YAML before switching back.

<img width="1400" alt="Screenshot 2023-01-13 at 5 59 07 PM" src="https://user-images.githubusercontent.com/20599230/212442977-d803fcb6-83e4-4be2-abcd-9c3e5b964653.png">

**Comment by catherineluse** [comment]
This PR is meant to address the issue - https://github.com/rancher/dashboard/pull/7924 Alex said he can make any needed changes.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 9bb8d56
Rancher cluster type: HA
Docker version: 20.10
Downstream cluster type: rke2

----------

### Testing: ###
Tested this issue with the following steps:
1. Create rke2/k3s cluster
2. Click Edit Yaml
3. Click Back to Form

**Result**
The UI no longer breaks and user is able to go back and forth between edit as yaml and form as expected.
