### ISSUE TITLE
Request for Information Icons to be set as same color

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/dashboard#7881]
**Setup**
- Rancher version: v2.7-head 8062f1e
- Browser type & version: Chrome Build 108

**Describe the bug**

Currently in the UI the information icon is two colors: black and gray. For consistency it would be nice to have the same color for these icons if possible. I do also see that the icon matches the color of the text it goes along with so if not, that's fine too.

**To Reproduce**

1. Create rke2/k3s cluster
2. Look at the information icons under Machine Pools, Advanced in Machine Pools, and Cluster Configuration

**Result**
The information icons are split between two colors: black and gray in Light mode or White and gray in Dark Mode
![image](https://user-images.githubusercontent.com/108360907/211372968-deed505e-2feb-4bdd-95fc-24f48740d9a1.png)
![image](https://user-images.githubusercontent.com/108360907/211373151-ecbbc3b5-f5a3-4703-9fcd-6e9b4104eb15.png)

**Expected Result**
If possible, have these icons as the same color

**Comment by richard-cox** [comment]
This is intentional. All icons across the dashboard are the inverse in light and dark modes (see the main side nav, cluster explorer side nav, cluster header top right icons, etc)
