### ISSUE TITLE
Block access to "More Resources > Rancher > Mgmt Clusters" Panel

### ISSUE THREAD

**Issue by andersmartinian** [rancher/dashboard#7908]
I'm trying to create an ingress read only role but i'm stuck seeing this the panel : 
More Resources > Rancher > Mgmt Clusters.

Is there any way,  Cluster or custom Role or resource able  to block access to this panel so an user with this custom role cant see it?

I've granted access to ingresses , projects and namespaces but I'm unable to find where to "block" this panel. User also has User-base global permissions only and obviously no built in permissions.

![ingresses](https://user-images.githubusercontent.com/122553249/212130538-d25e2b65-51c2-43eb-af26-1e6cdbef66fb.PNG)

**Comment by richard-cox** [comment]
The user will have access to mgmt clusters if the user is a member of a cluster (which would be the case if they see a Clusters More Resources option). The list there should reflect the user's permissions, for instance create, edit, delete buttons would be disabled given their rights.
