### ISSUE TITLE
feature title: Autoscale VM based on load on VM

### ISSUE THREAD

**Issue by yashi4engg** [rancher/dashboard#7912]
**Is your feature request related to a problem? Please describe.**
<NA>

**Describe the solution you'd like**
"We have harvester clusters integrated with rancher. We want to set auto scaling based on load on VM. 
EX - If cpu uses or memory uses went high from a specific percentage ex 90% rancher will start a new VM on that harvester cluster and once load will go down it will stop other VM. "

**Comment by richard-cox** [comment]
Thanks for raising this question. It seems like something for https://github.com/harvester/harvester though.
