### ISSUE TITLE
Entering invalid credentials during AKS cluster importing shows a misformed error message

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#7913]
1. Navigate to cluster management
2. Hit 'Import Existing Cluster'
3. Select AKS
4. Enter invalid credentials in the 'Account Access' section and hit 'Create'
5. The error message is useless

After quick inspection, it looks like there are two problems here. The error banner component is receiving two errors: one is a (improperly-generated) string containing `undefined` and the other is an object the component does not render correctly.

![Screen Shot 2023-01-12 at 3.19.27 PM.png](https://zube.io/files/rancher/8377f654d8fe9c14ea71604117cbc5ad-screen-shot-2023-01-12-at-3-19-27-pm.png)

**Comment by dnoland1** [comment]
During create AKS cluster, see a similar error that is probably related
![image](https://github.com/rancher/dashboard/assets/468462/d3139ab6-7aa6-4de7-9443-70bbeac606ae)

**Comment by mantis-toboggan-md** [comment]
This will be handled by the move to Vue: https://github.com/rancher/dashboard/issues/8965

AKS provisioning will use the same credential creation process as RKE2 on Azure

**Comment by valaparthvi** [comment]
Validated on Rancher(v2.9-a9355940c0629ca419b7dd3e4098c4ea0e52c0c0-head); Dashboard(master [46a44c1](https://github.com/rancher/dashboard/commit/46a44c11ddbb14581db9793aadc3512e1362edf1)), the issue still exists for import.


**Error during Import**
![image](https://github.com/rancher/dashboard/assets/11015077/2d8ba9fa-9c9c-4cbd-95c4-ed62105a7b38)

**Error during Create**
![image](https://github.com/rancher/dashboard/assets/11015077/f78f25e0-20d6-495c-9304-1e5c04cccea5)

**Comment by valaparthvi** [comment]
Tested on Rancher: v2.9-81337b95660cba868629d6fe769bd7e8242b5aee-head, Dashboard: master https://github.com/rancher/dashboard/commit/3da120530d8659b45688a666445fe66d28777d3e.

_It is partially fixed._

_Error while creating credential via the Import form_
![image](https://github.com/user-attachments/assets/79c1cc2b-719e-451c-9247-1855498dcc37)

_Error while creating credential via the Create form and Cloud Credential create form_
![image](https://github.com/user-attachments/assets/578f89cf-26bb-421e-90f0-639b17e8a397)

**Comment by valaparthvi** [comment]
Closing this issue in favor of #11473.
