### ISSUE TITLE
Sockets subscribe to all resources instead of required namespace filter

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7919]
**Setup**
- Rancher version: 2.7.-head
- Browser type & version:

**Describe the bug**
Sockets subscriptions for resources should be limited by the same attributes as their initial fetch request (id, selector, ns). It doesn't look like this is working for namespaces

**To Reproduce**
- Enabling the Required Namespace Filter Performance feature and set the threshold to something low
- Navigate to a list with resources over the threshold
- Select a single namespace
- Refresh the browser
- Notice that the http request contains the selected namespace, but the websocket subscribe message does not supply it

**Expected Result**
- socket sub should contain namespace

**Comment by gaktive** [comment]
Should be unblocked now via PRs:
https://github.com/rancher/apiserver/pull/20
https://github.com/rancher/steve/pull/73
https://github.com/rancher/rancher/pull/40238

@cmurphy let me know if I'm mistaken.

**Comment by cmurphy** [comment]
@gaktive yes the rancher PR is merged so this is ready to use.

**Comment by floatingman** [comment]
## Setup
Bring up a single node Rancher instance based on the latest RC version
Create a workload of various deployments in different namespaces

This script will create 10 nginx deployments in 10 namespaces.

``` bash
#!/bin/bash

# Create 10 namespaces
for i in {1..10}
do
  kubectl create namespace nginx-namespace-$i
done

# Create 10 Nginx deployments in each namespace
for i in {1..10}
do
  for j in {1..10}
  do
    kubectl create deployment nginx-$j --image=nginx --namespace=nginx-namespace-$i
  done
done
```

In Rancher Manager, In Global Settings under Performance,
Enable required namespace filtering and set a low threshold like 5.

## Testing
1. Browse to Rancher Manager
2. Open Dev tools in your browser and click on the Network tab.
3. In the local cluster, click on the Workloads
4. Observe the message asking you to filter by a specific namespace.
5. Select one of the namespaces you created in the filter tab and observe that the namespace is listed in the HTTP request and the WebSocket.
