### ISSUE TITLE
Trying to close a PrometheusRule warning creates duplicate warning

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7925]
Seen in v2.7-head.

To reproduce,

1. Install monitoring on a cluster.
2. In Cluster Explorer, go to Monitoring > Advanced > PrometheusRules.
3. Click Create.
4. On the form that appears, there is a warning: `At least one alert rule or one recording rule is required in rule group 1.`
5. Click X on the warning.
6. See that every time you click an X, a duplicate warning appears.
<img width="1577" alt="Screenshot 2023-01-14 at 4 06 15 PM" src="https://user-images.githubusercontent.com/20599230/212501004-f34d2bfc-f629-4368-8c5b-52de07be0897.png">

Ideally, we wouldn't see any warnings until the form is touched. But at minimum, the warnings should be able to be dismissed.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 027246f`
1. created downstream cluster
2. installed monitoring v2
3. clicked cluster > monitoring > Advanced > Prometheus rules
4. clicked `create`
5. two warnings loaded
6. clicked X on warning 2
7. clicked X on warning 1

result: no duplicate warnings appeared when clicking the X



https://zube.io/files/rancher/db3fbe4e5f5c759df03fd3e32851754b-2023-08-01_11-41-38.mp4
