### ISSUE TITLE
[Backport 2.6.x] - ensure all EKS versions are in 2.6.x branches

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7931]
We had a fix for updating the EKS versions to include k8s 1.23 & 1.24 for 2.6.x but they only made it into master, not the 2.6 branches so we still only show <1.22 for 2.6.9 and 2.6-latest.

1.23: https://github.com/rancher/ui/pull/4890
1.24: https://github.com/rancher/ui/pull/4908
Remove older versions: https://github.com/rancher/ui/pull/4899

**Comment by gaktive** [comment]
We should figure out if anything else happened during branching for the 2.6.9 release since there may be other missing PRs in the release from `master` to `2.6-xxxx`

**Comment by catherineluse** [comment]
After comparing commits in master and the release-2.6.9 branch in the Ember repo, I believe the only other change that needs to be backported is https://github.com/rancher/dashboard/issues/6774.

**Comment by gaktive** [comment]
Based on discussion with @snasovich, we may have to revert https://github.com/rancher/ui/pull/4899 since this ties into a complex web of supporting older k8s versions that 2.6.x has to but 2.7.x doesn't.

@nwmac should we Reopen this before QA starts testing?

**Comment by sowmyav27** [comment]
Reopening for QA validations

**Comment by sowmyav27** [comment]
@gaktive Can you confirm if this is ready for QA validations?

**Comment by gaktive** [comment]
@richa was https://github.com/rancher/ui/pull/4899 reverted? I can't tell from the history in that PR or here what happened.

@sowmyav27 for 2.7.x, this ticket isn't relevant since that work was already done:
- add 1.24: https://github.com/rancher/dashboard/issues/7219
- add 1.23: https://github.com/rancher/dashboard/issues/6826
- remove 1.22 and older: https://github.com/rancher/dashboard/issues/7203

This ticket was created because it was discovered that prior backports never made it into 2.6.9 due to some branching confusion.

**Comment by gaktive** [comment]
Another internal reference: SURE-5880
Bumped Priority to 0.

**Comment by gaktive** [comment]
This should be ready for QA as far as I understand.

**Comment by gaktive** [comment]
@snasovich as I look for your past comments, what did 2.6.x and 2.7.x have to support with EKS k8s versions? You said somewhere that we had to support older versions in 2.6.x for a while and we've gone to 1.20-1.24 in this work to fix things.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 6d1bd94
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: eks

----------

### Testing: ###
2.6-head is showing all the EKS versions available for users
![image.png](https://zube.io/files/rancher/07bdcf44bbaea20d5baafdd4616fa797-image.png)

**Comment by snasovich** [comment]
@gaktive , as for your last comment, replied offline (in Slack).
