### ISSUE TITLE
Intermittent 403 Fail Whale errors in new UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7932]
Internal reference: SURE-5670
Reported in 2.6.9

Issue description:
Users see intermittent 403 Forbidden Fail Whale with different errors in the 2.6.9 dashboard UI. The error changes each time. But they almost always make it seem like a permissions problem. Here are some examples:

```
"clusters.management.cattle.io is forbidden: User \"u-c75rx2mafn\" cannot list resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope"

"apps.catalog.cattle.io is forbidden: User \"u-c75rx2mafn\" cannot list resource \"apps\" in API group \"catalog.cattle.io\" at the cluster scope"

"clusters.management.cattle.io is forbidden: User \"u-c75rx2mafn\" cannot list resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope"
```

But the user does have the right permissions and access. In fact, when they reload and then click around a bit, the resources populate. Also, when users use the old UI with /g, they don't see any of these problems.

Business impact:
It is a nuisance and makes using the new dashboard difficult

Troubleshooting steps:
- Not related to https://www.suse.com/support/kb/doc/?id=000020710
- They are using ADFS, so I had them test out a local user to try and rule out the authentication provider. Local users still saw the problem.
- I had them try different browsers, disable all extensions, and use incognito mode. They still saw the problems

Repro steps:
Hard to reproduce but easily spotted based on setup. @gaktive asked about the user type and audit logs.

Workaround: User older UI ->  /g

Actual behavior:
The user sees intermittent 403 Fail Whale errors when browsing resources in the dashboard.

Expected behavior:
The user shouldn't see intermittent 403 Fail Whale errors when browsing resources in the dashboard.

**Comment by nwmac** [comment]
@Shavindra This is in review, but there is no open PR for it - what is the status?

**Comment by gaktive** [comment]
Problem went away after the original requester removed and re-added the permissions. Closing as done.
