### ISSUE TITLE
Add registry mirror rewrites to RKE2 cluster provisioning form

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#7939]
**Is your feature request related to a problem? Please describe.**
The RKE2 cluster provisioning form is missing form field to configure registry mirror rewrites. These are necessary, if a private registry has a different organizational structure, which is often the case in enterprise environments. The backend already supports the rewrites field: https://github.com/rancher/rancher/blob/release/v2.7/pkg/apis/rke.cattle.io/v1/registries.go#L4-L15.

**Describe the solution you'd like**
Extend the form to add rewrites to a mirror.

**Additional context**
Documentation for registry mirror rewrites can be found at https://docs.rke2.io/install/containerd_registry_configuration#rewrites.

**Comment by slickwarren** [comment]
tested on v2.7-head(3c1e7db):
* provision an rke2 cluster that uses `rewrite` feature in the `mirrors` section
  * provisioning without a rewrite in the mirror works as expected -- pass
  * provisioning with a valid rewrite results in correctly pulled images and an active cluster -- pass
  * provisioning with an invalid rewrite results in an error for the user -- pass, but could be improved (see linked issue above)
