### ISSUE TITLE
Typo in UI: 'Loadingg'

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7945]
`Loadingg` is mis-spelt with 2 g's at the end

**Comment by Josh-Diamond** [comment]
Ticket #7945 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-3c1e7dbaafe9c38629898273974b97ec6e8fd4da-head`:
1. Fresh install of rancher `v2.7-head`
2. Click `Create` button from home screen
3. Verified - `Loading...` is accurate and seen. typo resolved

Screenshot:
<img width="1524" alt="Screenshot 2023-02-07 at 12 52 58 PM" src="https://user-images.githubusercontent.com/46494969/217351647-280b9db3-9809-41f6-826b-4c3b81e83f7a.png">
