### ISSUE TITLE
Link to event object in cluster events table

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#7946]
**Is your feature request related to a problem? Please describe.**
Currently the detail link in the cluster events table links to the events detail page, which mostly repeats the same information that is already visible in the table. And, it's just a YAML editor.

<img width="685" alt="Bildschirm­foto 2023-01-17 um 18 47 36" src="https://user-images.githubusercontent.com/243056/212973766-de239eae-64c5-4bc6-a88b-ccf61b8365fd.png">

It would be useful, to instead or also link to the object resource, e.g. the Pod or the Deployment that this event is about.

**Describe the solution you'd like**
Based on internal discussions: Add an additional column to the cluster explorer events table, so that there is one column with the object, one with the message and one with event name. The cluster explorer events table would look more like the full events table, just with less columns.

The object column is then linked to the object resource. The event name column is linked to the event detail page.

**Describe alternatives you've considered**
Alternatively we cloud drop the link to the event detail page.

**Additional context**
Current situation:
<img width="1494" alt="Bildschirm­foto 2023-01-17 um 18 52 14" src="https://user-images.githubusercontent.com/243056/212974696-98da9f54-0a1c-4cef-bd67-5a18ba74bc13.png">
<img width="1510" alt="Bildschirm­foto 2023-01-17 um 18 52 19" src="https://user-images.githubusercontent.com/243056/212974701-f4cdb8d3-24b2-417b-a15e-b105aad18bb1.png">

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment



| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7-d559c2f16d5a634d8e5188e242ee9a5b69c55908-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/d559c2f16d5a634d8e5188e242ee9a5b69c55908 |
| Installation option              | Docker                                                                             |
| Cert Details                     | `--acme-domain`                                                                    |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin                                                                              |
| Browser type                     | Microsoft Edge                                                                     |
| Browser version                  | 110.0.1587.50 (                                                                    |


<details>
    <summary>🚨 Additional Validation Setup Details: Click to Expand</summary>

Setup Docker install Rancher setup via: 

</details>

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Navigate to `hamburger menu` >>> `Cluster Management` >>> `Explore` (next to the local cluster)
3. There are two places to check to make sure the object links are working as expected:
   1. On the cluster explorer page
   2. Click >>> `Full events list`  
4. Click objects in both of those views
5. Ensure the link goes to the correct object

## Additional Info

## RESULTS

#### ✅ Expected

Object links on both areas are working as expected

#### ✅ Actual

Object links on both areas are working as expected

#### Additional Info

Still seeing this issue for other columns in events: https://github.com/rancher/rancher/issues/40332

## 📋 QA Test Plan

<table>
    <tbody>
        <tr>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>Create 3,000 workloads, ensure that links are still routing to expected objects</td>
            <td>
                <ol>
                    <li>Run the following against the cluster</li>
                    <li>https://github.com/brudnak/deno-cattle-workloads</li>
                    <li>Check various object links across the 3,000 events</li>
                </ol>
            </td>
            <td>Expected: All links are routing as expected</td>
            <td>Actual: All links are routing as expected<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
</table>
