### ISSUE TITLE
'Worker CIS Profile' in RKE2 Custom Cluster Provisioning form should be 'CIS Profile'

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7950]
Internal reference: SURE-5744
Reported in 2.6.9 & 2.7.0

Issue description:
In the Add cluster -> RKE2 -> Custom form, the CIS profile selection dropdown in the Security section is labelled 'Worker CIS Profile', which is incorrect as the CIS Profile is applicable to all nodes. This should be relabelled simply 'CIS Profile'.

Impact:
Confusing to end-user when provisioning cluster

Repro steps:

- Provision a Rancher v2.6.9 or v2.7.0 instance
- Navigate to Add Cluster -> RKE2 -> Custom
- Observe 'Worker CIS Profile' dropdown under the Security section

Workaround: none

Actual behavior:
Form field labelled 'Worker CIS Profile'

Expected behavior:
Form field labelled 'CIS Profile'

Additional notes:
Confirmed with CIS team that as suggested, this can be renamed. The profile is also doing some validations on other nodes like 'etcd'. So it is not limited only to the worker node profile as the name suggests.

**Comment by nwmac** [comment]
@bisht-richa This is a trivial rename

**Comment by jameson-mcghee** [comment]
During testing on `v2.6.9`, I was able to see the "_Worker CIS Profile_" label when creating a Custom RKE2 Cluster. However, when testing on `v2.7-head` (Commit ID: 0504ce6), I observed that the label was now corrected to "_CIS Profile_". Therefore I am closing this ticket as Done.

**`v2.6.9`:**
![image](https://user-images.githubusercontent.com/13294321/217657525-de7affe2-bf4a-4081-8dc9-75f52f0c9273.png)

`v2.7-head` (Commit ID: 0504ce6):****
![image](https://user-images.githubusercontent.com/13294321/217657615-b8930690-611d-4043-9b7f-b340dd67f263.png)
