### ISSUE TITLE
Namespaces no longer show if istio auto-injection is enabled

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7951]
Internal ref: SURE-4624

In the Old UI, The Namespace list showed an icon next to the namespace in the list view if Istio auto-injection was enabled.

This is determined by the namespace having the label `istio-injection` set to `enabled`.

![image](https://user-images.githubusercontent.com/1955897/213178065-201798ec-a71a-49bb-ac3b-89d052e3caa8.png)

The new UI does not.

We should:

- Show the istio icon next to the namespace in the list view when the`istio-injection` set to `enabled`. This should have a hover tooltip that says `Istio automatic sidecar injection is enabled for this namespace`
- On the namespace detail view, we should show in the masthead if auto-injection is enabled

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 95edd02`
1. installed rancher-monitoring:102.0.1+up40.1.2
2. installed rancher-istio:102.2.0+up1.17.2
3. enabled istio-inection in defaut namespace
![2023-05-12_13-35-37.png](https://zube.io/files/rancher/bb8764907cdc1d58441c57b39d86fe02-2023-05-12_13-35-37.png)
![2023-05-12_13-35-50.png](https://zube.io/files/rancher/94423f68365cd9b67522d1d9108a3fe9-2023-05-12_13-35-50.png)
