### ISSUE TITLE
uncaught error when provisioning a eks cluster thru the rancher ui

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#7954]
**Setup**
- Rancher version: `2.6-head commit id 49e0eb1`
- Browser type & version: `chrome Version 108.0.5359.124 (Official Build) (x86_64)`

**Describe the bug**
when creating a new eks cluster, an uncaught error shows in the console

**To Reproduce**
provision an eks cluster via rancher ui

**Result**
`router_js.js:1895 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'inaccessibleByURL')
    at s._updateURL (router_js.js:1895:1)
    at router_js.js:1454:1
    at v (rsvp.js:493:1)
    at rsvp.js:558:1
    at invoke (backburner.js:340:1)
    at p.flush (backburner.js:229:1)
    at m.flush (backburner.js:426:1)
    at q._end (backburner.js:960:1)
    at _boundAutorunEnd (backburner.js:629:1)`

**Expected Result**
no uncaught errors

**Screenshots**

**Additional context**

**Comment by gaktive** [comment]
This might be in 2.7.x too, which would be more of a priority.

From what @nwmac has seen, this doesn't break anything but it does look icky.

**Comment by ronhorton** [comment]
this should be 'eks' in the title, not 'gke'

**Comment by ronhorton** [comment]
don't see error in 2.7-head or with another hosted provider

**Comment by gaktive** [comment]
@ronhorton just to clarify, this is EKS only on 2.7-head? Just want to understand the latest comment here before we dig into this.

**Comment by ronhorton** [comment]
@gaktive this isn't happening any longer with the latest version of 2.6-head. (commit ID b465433)

(and it was 2.6-head rather than 2.7-head, re: your last comment)

**Comment by gaktive** [comment]
@ronhorton thanks for clarifying. Should I go ahead and close this then since the console error is gone?

**Comment by ronhorton** [comment]
closing as non-reproducible.
