### ISSUE TITLE
When editing a RKE2/K3s cluster configuration, the `documentation` hyperlink is exposed as HTML instead of abstracted

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#7955]
**Setup**
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/6ee39491374d4cf1853d21fe77e9a6d2e0e7761a
- Browser type & version: Chrome

**Describe the bug**

When attempting to edit the configuration of an RKE2 or K3s cluster, I see the following:

![image](https://user-images.githubusercontent.com/52591819/213271906-05b189f0-a8eb-4ab9-b0d2-8ce7c9c65f9b.png)

The HTML is being exposed instead of just `documentation` containing a hyperlink to the aforementioned link. This seems to be a regression as this behavior did not seem to occur in 2.7.0.

**To Reproduce**

1. As a standard user, provision a RKE2 or K3s cluster with K8s version 1.24.9.
2. Validate that the nodes and cluster are set as `Active`.
3. Edit the cluster in Cluster Management and take note of the banner.

**Result**
The HTML is shown in the banner instead of a just a hyperlink with `documentation` as the abstracted word.

**Expected Result**
`documentation` should contain a hyperlink to the correct documentation.

**Comment by gaktive** [comment]
Should be taken care of via PR https://github.com/rancher/dashboard/pull/7787/files, since this was detected earlier. We also have #7920 open to address some of the padding with the banner, so it's a duplicate, though good to have someone else catch this.
