### ISSUE TITLE
[Backport 2.6.x] Wrong Certificate Information Showing

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7956]
Internal reference: SURE-5309
Reported in 2.6.4 & 2.6.8

For 2.7.x, we fixed an issue whereby we accidentally showed the root CA info, not the certificate itself. Quoting:
> Certificate information shows in the UI only shows information on the last certificate in the chain (typically the root CA) so the domain is usually not listed, and the expiration date is not correct. This means for those looking for expired certificates, the information provided in the UI is useless and would require manual review to validate.

We need to take https://github.com/rancher/dashboard/issues/7081(PR: https://github.com/rancher/dashboard/pull/7224) and backport it to 2.6.x.

**Comment by gaktive** [comment]
This feels like a stretch for 2.6.x based on timeline but if it's an easy back port, there's demand.

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment


| Component                        | Version / Type                       |
| -------------------------------- | ------------------------------------ |
| Rancher version                  | 2.6.8                                |
| Installation option              | Helm (high availability)             |
| If Helm Chart k8s cluster        | v1.24.7+k3s1                         |
| Cert Details                     | Let's Encrypt / `traefik`            |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2 |
| Helm version                     | v2.16.8-rancher2                     |
| Downstream cluster type          | not applicable                       |
| Downstream K8s version           | not applicable                       |
| Authentication providers enabled | local                                |
| Logged in user role              | administrator, standard user         |
| Browser type                     | google chrome                        |
| Browser version                  | 109.0.5414.119 (x86_64)              |

<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

>K3s install command for node one. Replace values in <>

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=SECRET --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```

>K3s install command for node two. Replace values in <>. Main difference here is the --token

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=<TOKEN_FROM_NODE_ONE> --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```


</details>


## Reproduction steps

1. Deploy Rancher 2.6.9 in K3s HA and compare the certificate expiration time of a special k3s-serving secret
2. Starting from the **default** Rancher homepage `/dashboard/home`
3. Click `hamburger menu` >>> `Storage` >>> `Secrets` >>> filter to `kube-system`
4. Click `Kubectl Shell`
5. Run the following command:

```shell
k get secret -n kube-system k3s-serving -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -noout -text | grep Not
```

6. Compare the value returned via the kubectl command to what is displayed in the Rancher UI as the TLS Certificate `Expires` date
7. These dates do not match
8. See screenshot below

## Additional Info

<img width="1687" alt="001" src="https://user-images.githubusercontent.com/40877149/217593202-23976603-925c-4298-8af0-1c54e6fe3062.png">


## RESULTS

#### ✅ Expected

For the UI to correctly display the TLS Certificate expires date

#### ❌ Actual

The UI did not correctly display the TLS Certificate expires date

<hr>

## Validation Environment



| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.6-e36364e2f7a673bae3464442947cd3ed1e9d4032-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/e36364e2f7a673bae3464442947cd3ed1e9d4032 |
| Installation option              | Helm (high availability)                                                           |
| If Helm Chart k8s cluster        | v1.24.7+k3s1                                                                       |
| Cert Details                     | Let's Encrypt / `traefik`                                                          |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2                                               |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | administrator, standard user                                                       |
| Browser type                     | google chrome                                                                      |
| Browser version                  | 109.0.5414.119 (x86_64)                                                            |


<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

>K3s install command for node one. Replace values in <>

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=SECRET --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```

>K3s install command for node two. Replace values in <>. Main difference here is the --token

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=<TOKEN_FROM_NODE_ONE> --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```


</details>

## Validation steps

1. Deploy Rancher 2.6-head in K3s HA and compare the certificate expiration time of a special k3s-serving secret
2. Starting from the **default** Rancher homepage `/dashboard/home`
3. Click `hamburger menu` >>> `Storage` >>> `Secrets` >>> filter to `kube-system`
4. Click `Kubectl Shell`
5. Run the following command:

```shell
k get secret -n kube-system k3s-serving -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -noout -text | grep Not
```

6. Compare the value returned via the kubectl command to what is displayed in the Rancher UI as the TLS Certificate `Expires` date
7. These dates do not match
8. See screenshot below


## Additional Info

<img width="1687" alt="002" src="https://user-images.githubusercontent.com/40877149/217593261-8230000b-bf8a-49dc-9a94-84330f2d7d70.png">


## RESULTS

#### ✅ Expected


For the UI to correctly display the TLS Certificate expires date

#### ✅ Actual


For the UI to correctly display the TLS Certificate expires date

## 📋 QA Test Plan

<table>
    <tbody>
        <tr>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>Start with Rancher 2.6.8 then upgrade to 2.6-head</td>
            <td>
                <ol>
                    <li>Start with Rancher 2.6.8</li>
                    <li>Verify the date is incorrectly displayed in the UI</li>
                    <li>Upgrade to Rancher 2.6-head</li>
                    <li>Check if the date displayed in the UI is now correct</li>
                </ol>
            </td>
            <td>Expected: For the UI to correctly display the TLS Certificate expires date after upgrade</td>
            <td>Actual: For the UI to correctly display the TLS Certificate expires date after upgrade<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>

**Comment by EutiziStefano** [comment]
Hi,
I experienced same error also in 2.7.1
I see on the secret, in the Data column, the details about CA instead of the certificate itself.
Also if I enter in the secret I see the Domain and expire date as the CA informations...
I'm available if you need some tests.
Thanks
