### ISSUE TITLE
products, plugins, extensions, what is the difference?

### ISSUE THREAD

**Issue by liyimeng** [rancher/dashboard#7964]
I notice rancher dashboard get a major refactoring from 2.7.0. However, I failed to follow all the new terms. 
I see there are some "products" in pkg directory. I get an impressions that those products are kind of built-in extensions. But when reading reading extensions documents here (https://rancher.github.io/dashboard/plugins/introduction), It seem I am wrong. 

Can someone kindly explains me, what is products, plugins, extensions that are referred in the documents and code? Are they different things, do they share any common?

Thanks a lot in advanced!

**Comment by richard-cox** [comment]
Rancher Manager contains a UI for many aspects. Some of these are split out in to products, for example Harvester, Fleet, Epinio. Some of these are more functional, like Cluster Management. For more information on how products are configured see [here](https://rancher.github.io/dashboard/code-base-works/products-and-navigation)

Products can be defined in the core dashboard shell, in the same code base or in an Extension. Extensions bring in additional functionality that includes more than just products.

The `pkg` directly is an old label, where you see this in code please think `Extension`.  In `shell` the `plugins` relates to [Nuxt](https://nuxtjs.org/docs/directory-structure/plugins/).

If this answers your question let us know,  and we'll make sure to include the information in our docs

**Comment by liyimeng** [comment]
@richard-cox Thanks for quick response. 
So "products" is more use case terms while extensions/plugins are more programming oriented.  In the extension [introduction](https://rancher.github.io/dashboard/plugins/introduction ), it says extensions can used for
```
- Ability to add new locales and localization packs
- Ability to add support for custom CRDs
- Ability to add new UI screens to the top-level side navigation
- Ability to customize the landing page
``` 
If we add another item
```
- Ability to dynamically load a product 
``` 
 will it be valid? If this is the case, do we have plan to move out products in pkg/* as extensions in the future? 

In my case, I will have some crds, together with core resources like pods,  and I plan to present them as a product in rancher, should I follow both [products structure](https://rancher.github.io/dashboard/code-base-works/products-and-navigation) and [ extension development ](https://rancher.github.io/dashboard/plugins/introduction )

**Comment by richard-cox** [comment]
The products are use cases, but still defined in code as per the product structure link.

> If we add another item

That's a good suggestion, thanks.

> plan to move out products in pkg/* as extensions in the future

Correct! Some will probably remain in the dashboard `pkg` folder as they will always ship with Rancher Manager whilst others may be split out into their own repositories and published separately to be optionally added 

> should I follow both [products structure](https://rancher.github.io/dashboard/code-base-works/products-and-navigation) and [extension development](https://rancher.github.io/dashboard/plugins/introduction)

That's a good approach. The product definition would exist in the extension. We have some existing examples (see `pkg/epinio` or https://github.com/rancher/elemental-ui/tree/main/pkg/elemental) to guide you

**Comment by liyimeng** [comment]
@richard-cox thanks so much for the help!

**Comment by liyimeng** [comment]
@richard-cox I see you assign this one to yourself, I assume you will do some update to the document. If that is the case, I would like to add some more comments.
-  In https://rancher.github.io/dashboard/plugins/plugins-getting-started#prerequisites, it says `You will need a recent version of nodejs installed`. according to my test, it works > 12 and < =16, node 17 work if you start node with `export NODE_OPTIONS=--openssl-legacy-provider`
-In  https://rancher.github.io/dashboard/plugins/plugins-getting-started#loading-the-extension-into-another-rancher, it describe a way to load extension into rancher. For me, this dose not look like an official way to release the extension. I guess there will be more description on this when the feature get close to be ready. Might you mention how the extension can be released to a production rancher?

**Comment by richard-cox** [comment]
- docusaurus/docs/extensions/extensions-getting-started.md. This now contains a tested version. It'll soon be updated though as part of another item of work
- https://rancher.github.io/dashboard/plugins/plugins-getting-started#loading-the-extension-into-another-rancher i think has been load in the transition to docusaurus

Given above i think we're ok closing this
