### ISSUE TITLE
Prevent selection of kiali component in rancher-istio chart installation without pilot dependency

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7970]
Internal ref: SURE-3069

With Istio, enabling Kilai should also require Pilot to be enabled too.

The UI allows you to enable Kiali without Pilot.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 95edd02`
1. installed rancher-monitoring:102.0.1+up40.1.2
2. installed rancher-istio:102.2.0+up1.17.2
3. verified cannot install rancher kiali component without pilot dependency


https://zube.io/files/rancher/ba279ac3a8e7f36791f798060627611e-2023-05-12_13-43-28.mp4
