### ISSUE TITLE
Some of the Event page column header tooltips are not being generated

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#7972]
**Setup**
- Rancher version: `v2.7-head (Commit ID: 623addd)`
- Browser type & version: Brave

**Describe the bug**
On the Events page, the _Last Seen_, _Type_, _Reason_, and _Message_ column headers' tooltips are not being generated.

**To Reproduce**
1. Spin up Rancher on `v2.7-head (Commit ID: 623addd)`
2. Navigate to the **Events** page for the `local` cluster (or a downstream cluster)
3. Hover over each of the following column headers
  - _Last Seen_
  - _Type_
  - _Reason_
  - _Message_

**Result**
None of the tooltips are generated

**Expected Result**
The tooltips are generated with the correct information

**Screenshots**
**`v2.7-head (Commit ID: 623addd)`:**
![2023-01-19_10-53-51](https://user-images.githubusercontent.com/13294321/213490388-4e20ab6e-13ed-4196-8455-33c18ffdd6f2.gif)

**Additional context**
This issue does not reproduce on `v2.7.0`, making this issue a regression.

**`v2.7.0`:**
![2023-01-19_11-04-48](https://user-images.githubusercontent.com/13294321/213492847-e8753cad-0a9a-4fc7-a6ef-2c5ace5d611a.gif)

**Comment by richard-cox** [comment]
See [this](https://github.com/rancher/dashboard/issues/7873#issuecomment-1396601063) comment for details on where the tooltip comes from

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: 0504ce6), I was able to see the tooltips generate for all of the column headers in on the _Events_ page. Therefore I am closing this ticket as Done.

**`v2.7-head` (Commit ID: 0504ce6):**
![2023-02-08_16-34-12](https://user-images.githubusercontent.com/13294321/217656414-cc45c90a-32c3-4972-9919-e4357d389849.gif)
