### ISSUE TITLE
2.6.x backport - Change not saved when clicking "Use TLS" in AlertmanagerConfig

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#7973]
**Setup**
- Rancher version:2.6.9
- Browser type & version: Chrome 105

**Describe the bug**

<img width="1906" alt="image" src="https://user-images.githubusercontent.com/16741882/202853488-e947e13a-6c67-4345-a299-e68216d62b46.png">
Click the corresponding button, it does not take effect

1、If use tls is not selected, the requireTLS: false parameter should be automatically generated
2、If the key is selected on the UI, saving will not take effect

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by gaktive** [comment]
@sowmyav27 is this needed for 2.6.x? Good news is that there's only one variable to change so the lift is light.

**Comment by sowmyav27** [comment]
@gaktive From what @ronhorton mentioned offline, was this isn't a blocker. And it seems like a small check from QA's end (checkbox validation). 
@ronhorton can you validate on 2.6-head and see if it happens always, and if you are unable to proceed or if there is a workaround for it.

**Comment by ronhorton** [comment]
It's consistent @gaktive @sowmyav27 - the workaround is to edit the yaml - so, this was happening in our previous 2.6 release.
