### ISSUE TITLE
Helm Chart Install Yaml Values editor does not use sticky footer

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7975]
Go to cluster tools, OPA Gatekeeper and install, click next to get the Values step.

The footer container the wizard buttons disappear off screen - they should be sticky as on the previous step:

![image](https://user-images.githubusercontent.com/1955897/213651648-95520647-3a71-440d-985d-13ae7a866976.png)

previous step:

![image](https://user-images.githubusercontent.com/1955897/213651773-c8764f58-09ef-42b7-bf64-fa03cb1b7d55.png)

**Comment by richard-cox** [comment]
Could be related to https://github.com/rancher/dashboard/issues/7978

**Comment by nwmac** [comment]
Can we create a layout component with a header and bottom panels with a middle panel and use that here. There are other places where we should be using sticky buttons and we don't.
