### ISSUE TITLE
Fleet Git Repos Repo column icon isn't aligned

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7976]
**Setup**
- Rancher version: 2.7-head 

**Describe the bug**
The repo icon in the repo column is not aligned with the repo text

**Screenshots**
![image](https://user-images.githubusercontent.com/18697775/213653755-3954191d-b961-4873-a8d8-02cbb554276c.png)

**Additional context**

**Comment by richard-cox** [comment]
This was probably due to the icon margin change (we hadn't branched for 2.7.2 at that point)

**Comment by ronhorton** [comment]
**Pass** verified in `rancher v2.7-head commit ID 1f014b7`
1. navigate to Git Repos page (search 'git repos')
2. add fleet examples git repo
3. check icon for alignment with 'rancher/fleet-examples' repo

![2023-05-09_11-03-49.png](https://zube.io/files/rancher/448331125ec9778ed92a26548602c105-2023-05-09_11-03-49.png)
