### ISSUE TITLE
Helm Install Wizard: Create namespace notice's namespace is not aligned

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7977]
**Setup**
- Rancher version: 2.7-head

**Describe the bug**
-  The name of the namespace is not aligned with the rest of the test

**To Reproduce**
- Start the wizard to install a chart
- Choose to create a ns and enter some text
- the notice at the bottom contains a missaligned code block

**Expected Result**
-  the ns name should be roughly in-line with the rest of the text

**Screenshots**
![image](https://user-images.githubusercontent.com/18697775/213655525-68c09e4a-7859-4136-a9d3-ee278ee40438.png)

**Comment by kwwii** [comment]
Note that this is a problem with how badges are shown inline with text and probably effects all badges

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7.2-rc6`
1. installed alerting-drivers `102.0.0`
2. created new namespace to install alerting-drivers
3. new namespace was in line with verbiage at bottom of screen

![2023-03-16_16-38-08.png](https://zube.io/files/rancher/5717cb0dea6fd9bfcfc50324064e686d-2023-03-16_16-38-08.png)
