### ISSUE TITLE
Validation UX ReDesign

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#7980]
![image](https://user-images.githubusercontent.com/617368/213664851-d1a03424-9f96-4e3f-aee7-505884251dd9.png)

**Comment by richard-cox** [comment]
Noticed another place this morning where it looks off. Not sure if this is related to the change of icon or general icon padding though

(requires monitoring to be installed)
The icon in the button, far right
![image](https://user-images.githubusercontent.com/18697775/213667506-f6540c10-09cf-4742-b5d7-5987af30c7e7.png)

**Comment by kwwii** [comment]
This is covered as part of the form validation rework
