### ISSUE TITLE
Docusaurus main page re-design

### ISSUE THREAD

**Issue by scures** [rancher/dashboard#7982]
**Is your feature request related to a problem? Please describe.**

We need to improve the layout of the current main-page of the documentation at https://rancher.github.io/dashboard/

💢 Important: the design should be consistent with the others sections (https://rancher.github.io/dashboard/home)

Some ideas:
- Beside the main two blocks, find some other information that might be useful for the user; ex, quick access to Extensions, Tests..
- Improve footer information, we might want to remove the links and have them as cards in the main content.

![image](https://user-images.githubusercontent.com/88777903/213686342-3ca1b135-ec7c-4956-afea-70387f2a8708.png)

CC @kwwii

**Comment by edenhernandez-suse** [comment]
After running a poll (and directly asking a developer), we got some answers. Not a lot, but enough to start working with:

![image](https://user-images.githubusercontent.com/120640736/214325804-2d95be80-e596-4db3-ae8d-54565ff82275.png)

These are the documentation sections devs are more likely to look for. Combining that information with our perspective of what we want to expose, I built this first approach:
 
[Wireframe](https://xd.adobe.com/view/49015622-c113-4bae-a9e2-14618baa269a-1c52/)

This is actually a refinement after Manuele's comments on the very first wireframe.

**Comment by edenhernandez-suse** [comment]
I've revisited some sections after reading the comments in the Xd prototype. 

We still need some stuff: 

@manuelecarlini we need a "Concepts" picture. "Concepts" is a kind of glossary of Rancher, you can have a look here: [Rancher Concepts](https://rancher.github.io/dashboard/getting-started/concepts)

@kwwii I need some native English support with the sections subtitles: 

![image](https://user-images.githubusercontent.com/120640736/217774250-2fcf7466-00ab-4f69-b89f-d0642405ea29.png)

I can come up with some content but it would require at least a review.

**Comment by edenhernandez-suse** [comment]
[Final proposal](https://xd.adobe.com/view/25b0bf79-20bf-4780-aaae-021bdc81781d-70e3/)

**Comment by edenhernandez-suse** [comment]
Design finished, PR: https://github.com/rancher/dashboard/pull/7837
