### ISSUE TITLE
Spacing between buttons and filter box is brokend

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7983]
There used to be spacing like this:

![image](https://user-images.githubusercontent.com/1955897/213686096-e0b25d0a-2795-4be5-a169-25b7a75229d8.png)

Now its like this:

![image](https://user-images.githubusercontent.com/1955897/213686038-e68713d1-eaae-4d78-8133-ee3ea0bc2dee.png)

We need to fix this back to how it was.

**Comment by dasarinaidu** [comment]
I have validated this issue on `v2.7-17e5bb595bc7d6d9280dd40280b4e82b21903790-head `. This issue got fixed and I m closing this card.

**Validation details as below:**
Rancher Version : v2.7-17e5bb595bc7d6d9280dd40280b4e82b21903790-head 
Browsers : Chrome and Firefox
Users : Admin and Standard Users
Modes : Auto and Dark

**Steps to Reproduce:**

1. Provision Rancher
2. Create RKE cluster 
3. Check for the Cluster Management page and check for the Space before the Cluster

**Actual:**
![image](https://user-images.githubusercontent.com/22034884/218898528-f52db125-7def-41be-ad88-0dfcae352950.png)
