### ISSUE TITLE
With manual refresh enabled, user deleted resources should be removed from lists

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7986]
**Setup**
- Rancher version: 2.7-head

**Describe the bug**
- When manual refresh is enabled we don't subscribe to affected resource types, so we don't get create, change or remove events
- When a user creates or edits a resource that change is applied to the list (as the list refreshes when user returns to it)
- When a user deletes a resource from the list view the resource remains
- We should align these behaviours (even though delete is a slightly different flow than create/edit)

**To Reproduce**
- Create a deployment
- Navigate to the Pods list
- Delete the pod from the deployment

**Result**
- The old pod remains in the list even though the user has deleted it

**Expected Result**
- The old pod is removed from the list
- The new pod should not be shown in the list (existing behaviour)

**Additional context**
-  Any action done externally from the page should not be applied to the list (current behaviour)

**Comment by nwmac** [comment]
Won't fix - manual refresh will be removed when we switch to server-side pagination
