### ISSUE TITLE
Home page card alignment is off

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7994]
See below:

![image](https://user-images.githubusercontent.com/1955897/214033493-c6942bfa-7fd7-4132-b9a9-4e46ff457c48.png)

The box to set login preferences and the side links panel should have their tops aligned.

I think extra padding crept in on the banner causing this.

**Comment by Josh-Diamond** [comment]
Ticket #7994 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-3c1e7dbaafe9c38629898273974b97ec6e8fd4da-head`:
1. Fresh install of rancher `v2.7-head`
2. Verified - Home page card alignment is pixel-perfect

Screenshot
<img width="1657" alt="Screenshot 2023-02-07 at 3 22 10 PM" src="https://user-images.githubusercontent.com/46494969/217380107-8df5bd11-6ec4-4865-9869-732e1c6530ed.png">
