### ISSUE TITLE
Presentation issues on the Extensions page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7995]
- The icon beneath the preview panel shows through - assume this is a z-index issue
- Harvester Manager build-in extension needs an icon and a description. Name should probably be 'Virtualization Management'

**Comment by noahgildersleeve** [comment]
Tested in `v2.7.2-rc5`. Verified that description showed up and icon was showing properly.

![Screenshot_20230307_120327](https://user-images.githubusercontent.com/83787952/223539784-979f08db-f8f8-42af-882f-31ec619773d0.png)
