### ISSUE TITLE
PSA minor changes

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#7999]
Change `PodSecurityAdmissionConfigurationTemplates` to `Pod Security Admission`

Capitalise the checkbox labels

Change the text size of "Define the admission ctorl mode you want to use for pod security" AND check the text itself (@kwwii)

Change the cluster template labels to NOT have checkboxes as the cluster PSAs will always be set (the default setting is privileged). Namespace PSAs are still optional and require the checkbox

Add title "Pod Security Admission" to the tooltips in the namespace list

**Comment by cnotv** [comment]
As mentioned in the meeting, there are the other 2 change requests:
https://github.com/rancher/dashboard/issues/7987
https://github.com/rancher/dashboard/issues/7988

**Comment by kwwii** [comment]
Change the way Labels are shown in the namespace detail page.
Change show all labels to "Show System Labels" and when clicked, add the details of the PSA label to the overview shown "Audit restricted (v1.25)" becomes "Audit restricted (v1.25): longdetailsofthepsa"

**Comment by kwwii** [comment]
Change the length of the growl warning message to 5s

**Comment by cnotv** [comment]
@kwwii Change the text size of "Define the admission ctorl mode you want to use for pod security" AND check the text itself 

Both the text are 12px.

**Comment by cnotv** [comment]
@kwwii I'm using the i18n of the term, as these will probably need to be changed as well.

**Comment by cnotv** [comment]
The detailTop pages changes is going to take a while, since I've to bring back [my original code with the original design from the PR](https://github.com/rancher/dashboard/pull/7619).

**Comment by liyimeng** [comment]
I think #8023 can be part of this one

**Comment by markusewalker** [comment]
This has been tracked and marked as completed in the internal test K8s 1.25 test plan. Closing issue.
