### ISSUE TITLE
[2.6] Add a modal warning for admins who try to disable an auth provider

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/dashboard#8005]
Backport needed of https://github.com/rancher/dashboard/issues/7525.

**Comment by gaktive** [comment]
@sowmyav27 is this a critical backport? It could be a light lift but testing to ensure nothing else is broken may add time for both Dev & QA.

**Comment by sowmyav27** [comment]
@gaktive This doesn't seem to have too many tests for QA unless some specific area is being fixed that will need test cases. Would appreciate if we can get some insight on regression areas from the UI Engineers. Also, this isnt a critical fix. A good to have feature in 2.6 line.

**Comment by anupama2501** [comment]
Verified on v2.6-head `e8e0e07`
Install rancher server and enabled azureAD auth
Disable azure AD auth as an admin user, verified the modal warning pops up before disabling the auth.

<img width="300" alt="2023-02-08_16-29-53" src="https://user-images.githubusercontent.com/38144301/217683537-068ce1ff-93d0-4ded-883b-836791ba4f4a.png">
