### ISSUE TITLE
harvester-manager missing in extension build

### ISSUE THREAD

**Issue by liyimeng** [rancher/dashboard#8008]
**Setup**
- Rancher version: 2.7.2-rc1
- Browser type & version:
safari
**Describe the bug**

I try to follow https://rancher.github.io/dashboard/plugins/introduction to build a simple extension.  Hit on some issues, I try to find walk around for some of them, as I described in https://github.com/rancher/dashboard/issues/7964 

However, this one I have no clue how to fix. my extension failed to build because of missing  @/pkg/harvester-manager/config/harvester-manager

**To Reproduce**

- Start a a container with node:17, mount dashboard repo into it as a volume
- Start a local verdaccio with hint from shell/scripts/test-plugin-build.sh
- Configure the container to use registry http://localhost:4873 
- Run `yarn build:lib'
- Run `yarn publish:lib'
- Run `yarn publish-shell'
- https://rancher.github.io/dashboard/plugins/introduction to create a test extension name helloworld
- when run `yarn dev`  it throws errors like below
**Result**
```
 ERROR  Failed to compile with 2 errors                                                                     friendly-errors 21:29:41

These dependencies were not found:                                                                          friendly-errors 21:29:41
                                                                                                            friendly-errors 21:29:41
* @/pkg/harvester-manager/config/harvester-manager in ./node_modules/cache-loader/dist/cjs.js??ref--6-0!./node_modules/thread-loader/dist/cjs.js??ref--6-1!./node_modules/babel-loader/lib??ref--6-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/edit/provisioning.cattle.io.cluster/import.vue?vue&type=script&lang=js&
* vue-virtual-scroll-list in ./node_modules/cache-loader/dist/cjs.js??ref--6-0!./node_modules/thread-loader/dist/cjs.js??ref--6-1!./node_modules/babel-loader/lib??ref--6-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/nav/WindowManager/ContainerLogs.vue?vue&type=script&lang=js&
                                                                                                            friendly-errors 21:29:41
To install them, you can run: npm install --save @/pkg/harvester-manager/config/harvester-manager vue-virtual-scroll-list
ℹ Waiting for file changes                                                                                                  21:29:41
ℹ Memory usage: 1.1 GB (RSS: 1.77 GB)                                                                                       21:29:41
ℹ Listening on: https://172.17.0.2:8005/  

```
**Expected Result**

The simple extension should build and run

**Screenshots**

**Additional context**

**Comment by liyimeng** [comment]
adding vue-virtual-scroll-list  into extension package.json solve the problem, but I don't understand why.

**Comment by krumware** [comment]
That resolved one of the dependency issues for me, but didn't resolve 
```
 ERROR  Failed to compile with 1 errors                                                                     friendly-errors 20:05:17

This dependency was not found:                                                                              friendly-errors 20:05:17
                                                                                                            friendly-errors 20:05:17
* @/pkg/harvester-manager/config/harvester-manager in ./node_modules/cache-loader/dist/cjs.js??ref--6-0!./node_modules/thread-loader/dist/cjs.js??ref--6-1!./node_modules/babel-loader/lib??ref--6-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/edit/provisioning.cattle.io.cluster/import.vue?vue&type=script&lang=js&
```

**Comment by krumware** [comment]
I was able to remove the import from `node_modules/@rancher/shell/edit/provisioning.cattle.io.cluster/import.vue`, then remove the relevant references/usage in that file, and the extension starter ran and built for me

**Comment by nwmac** [comment]
@richard-cox How did the plugins gate pass? We need to look at that as that is meant to make sure we don't break extensions

**Comment by aalves08** [comment]
@liyimeng @krumware fix has been deployed and you need to bump the version of `@rancher/shell` package on your extension to `0.3.3`

**Comment by krumware** [comment]
@aalves08 good to go!
Quick question, I can propose some clarification to the docs. 
The package template that gets created make more deliberate reference to the types import.
```
import { importTypes } from '@rancher/auto-import';
import { IPlugin } from '@shell/core/types';

// Init the package
export default function(plugin: IPlugin) {
  // Auto-import model, detail, edit from the folders
  importTypes(plugin);

  // Provide plugin metadata from package.json
  plugin.metadata = require('./package.json');

  // Load a product
  plugin.addProduct(require('./product'));
}
```

but the docs suggest more differences than just the uncomment of the product.addProduct call. (seems less complete)
```
import { importTypes } from '@rancher/auto-import';

// Init the package
export default function($plugin) {
  // Auto-import model, detail, edit from the folders
  importTypes($plugin);

  $plugin.addProduct(require('./product'));
}
```

Which is more recent, the section in the docs, or the code in the template?
Thanks!

**Comment by aalves08** [comment]
@krumware the code in the template is a bit more recent. We are going to update the docs. thanks

**Comment by aalves08** [comment]
@krumware docs updated. https://rancher.github.io/dashboard/extensions/introduction

Going to close this issue since it has been fixed + docs are updated.

FYI @nwmac @richard-cox @gaktive @mantis-toboggan-md
