### ISSUE TITLE
Azure Availability Zone feature does not pass `--azure-enable-public-ip-standard-sku` flag to backend

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/dashboard#8014]
**Setup**
- Rancher version: 2.7-head
- Browser type & version: Any

**Describe the bug**
Several new features were implemented for Azure node-driver provisioned clusters. This includes the ability to create Azure VM's in particular Availability Zones (https://github.com/rancher/dashboard/issues/7180, https://github.com/rancher/dashboard/issues/7753, https://github.com/rancher/rancher/issues/39458). This feature was working upon initial validation, however recently an error has been encountered whenever a VM is configured to be created in an Availability Zone. This is an issue for both RKE1 and RKE2 node-driver clusters. 

The error seen in the UI is 
```
Error with pre-create check: "The Standard Public IP SKU must be enabled when creating resources in specific Availablity Zones
    (--azure-enable-public-ip-standard-sku)"
```
This error is reported by rancher-machine, indicating that the UI is not passing this required flag to the backend via the `azureconfig`, 
```json 
"enablePublicIpStandardSku": {
"type": "boolean",
"nullable": true,
"create": true,
"update": true,
"description": "Specify if a Standard SKU should be used for the Public IP of the Azure VM"
}
```
We're unsure why this issue was not seen on initial validation, so this may be due to some recent regression. 

Additionally, there is no way to configure this flag in the node template or RKE2 UI, which seems like a gap in the initial implementation. I suspect the flag was being passed implicitly before, however having the user explicitly select it is more desirable / flexable. The ideal fix for this issue is to add this missing option in the node template and RKE2 creation UI and then pass the flag to the backend. 

**To Reproduce**
+ Create an RKE1 node template for Azure
+ In the 'Placement' section, deselect 'Availability Sets' and select 'Availability Zones'
    + You must use a region that supports Availability Zones, and westus **does not**
+ In the 'Instance' section ensure you change the 'Disk Type' to 'Managed Disk' 
+ Create an RKE1 cluster using this node template

Similar steps can be followed for RKE2 clusters, with the main difference being you will configure the zone and disk settings in the 'Advanced Options' when creating the cluster. 

**Result**
The node beings provisioning but errors out with the above error message. 

**Expected Result**
The node provisions successfuly and is placed in the desired availability zone

**Screenshots**
![Screen Shot 2023-01-24 at 3 25 04 PM](https://user-images.githubusercontent.com/25062254/214401198-210aeeee-0c48-4ced-8866-e1e061a4dec2.png)

![Screen Shot 2023-01-24 at 3 27 24 PM](https://user-images.githubusercontent.com/25062254/214401447-f6ecea45-a544-4123-9f2c-b7ea563cd8c2.png)

**Additional context**
Unsure what would have changed, but this feature was working a few weeks back.

**Comment by mantis-toboggan-md** [comment]
> We're unsure why this issue was not seen on initial validation, so this may be due to some recent regression.

I looked around the history of the azure node template UI component and couldn't find evidence of `enablePublicIpStandardSku` having ever been used. In the process of adding this option, I did find a bug in the form that could explain how this wasn't caught previously, depending on how availability zones were tested. When the 'Availiability Zone' radio option is selected, the availability zone dropdown populates and appears to have selected the first zone in the list; however, this is purely visual: an availability zone isn't set until a different option is selected in the dropdown. There will be a fix for this in the PR adding standard SKU field.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head d559c2f
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 110

----------

### Testing: ###
Tested this issue with the following steps:
1. Create rke1 cluster
  - Create an RKE1 node template for Azure
  - In the 'Placement' section, deselect 'Availability Sets' and select 'Availability Zones'
    - You must use a region that supports Availability Zones, and westus does not
  - In the 'Instance' section ensure you change the 'Disk Type' to 'Managed Disk'
  - Create an RKE1 cluster using this node template
2. Create rke2 cluster following same steps
3. Verify the clusters come up Active without the provisioning errors relating to PublicIPStandardSKU

**Result**
Both the rke1 cluster and rke2 cluster are successfully provisioned.
![image.png](https://zube.io/files/rancher/d6d774bf49a6e7955809c2ee1d65908a-image.png)
