### ISSUE TITLE
Update Display For Newly Added PSACT Role

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/dashboard#8015]
Recently a [PR was raised](https://github.com/rancher/rancher/pull/40295) to introduce a new built-in role for managing `PodSecurityAdmissionConfigurationTemplates`. During the creation of that PR I noticed that the UI provides a display name for that role when creating a new user that is not present in rancher/rancher. 

In the rancher/rancher codebase the role is defined with the following name 
![Screen Shot 2023-01-24 at 5 11 20 PM](https://user-images.githubusercontent.com/25062254/214442247-2d8494af-e9a0-4639-bead-7ba39a4b89b1.png)

However, when viewed in the UI the role looks like the following, and includes a description 
![Screen Shot 2023-01-24 at 6 16 28 PM](https://user-images.githubusercontent.com/25062254/214442372-681e45a6-1c81-4761-9301-15b326c9efe3.png)

We would like to have a similar formatting applied to the new PSACT role, as well as a description added below the name
![Screen Shot 2023-01-24 at 6 16 28 PM](https://user-images.githubusercontent.com/25062254/214442435-c487a414-7a7d-41e1-a09a-9e264acef628.png)
Both the description and name of the PSACT role should mirror the description and name of the PSP role, 

Name: `Manage Pod Security Admission Configuration Templates (PSACTs)`
Description: ` Allows the user to define, edit, and remove PSACTs.`

**Comment by gaktive** [comment]
Closing in light of rancher/dashboard#8037 though the details here should be considered as part of that work (per @snasovich )
