### ISSUE TITLE
Banner on global PSACT page warning about modifications not automatically being applied downstream

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8016]
Nice to have for 2.7.next1 from @deniseschannon:

> It would be nice to add a banner or something to indicate on the global page of PSACTs that if you modify PSACTs, it will not automatically be applied to downstream clusters that are already deployed with them until there is a cluster update.

**Comment by nwmac** [comment]
Add an info banner to the Pod Security Admission list page in Cluster Management that says:

Note: Modifying a Pod Security Admission Configuration Template will not affect any downstream cluster that references it until there is a cluster update

**Comment by markusewalker** [comment]
Validated that this has been addressed and relative test cases in the internal K8s 1.25 test plan have been updated. Closing this issue.
