### ISSUE TITLE
How to add a custom layout in shell?

### ISSUE THREAD

**Issue by liyimeng** [rancher/dashboard#8017]
In shell, there are layouts available likes this: 

```
shell/layouts/
├── blank.vue
├── default.vue
├── error.vue
├── home.vue
├── plain.vue
└── unauthenticated.vue
```

I wanna add another one, so I create a new one by doing
`cp  blank.vue myhome.vue`

I then do `yarn link` things to make sure latest shell version is used.  But

-  if I modify https://github.com/rancher/ui-plugin-examples/blob/main/pkg/homepage/NewHomeComponent.vue to use layout 'myhome'  It seem fallback to 'plain', not giving me new look. 
-  if I set the layout to 'blank' it dose work.   I get new look. 
So for some reason, my new created layout is not available for use in the extension.   What I am missing?

**Comment by richard-cox** [comment]
Layouts are only available in the upstream shell and aren't currently available to supplement by extensions. 

In 2.9.0 will remove the concept of nuxt layouts and replace them with generic components attached to routes https://github.com/rancher/dashboard/blob/master/shell/config/router.js#L117. You should be able to do the same in your extension though before (and after) 2.9.0
