### ISSUE TITLE
Workloads - Can't set the port in Edit as form when creating or editing a workload

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#802]
Rancher version: `master-head (07/01/2020)`  _001aa0c5f_
dashboard-index: `latest`

Create a new workload, set name, image, type.
Click in the Ports tab.
Add port, set the name and port.
Click Create. If all requirements are met no error is displayed and the workload gets created.

Result:
No port is set in the workload.

Expected:
Port properly set for the workload.

Sample when editing a Daemonset workload, I set the port. Click save but navigating to edit as Form, click Ports tab, the port is not set.

![Screen Shot 2020-07-01 at 12 05 42 PM](https://user-images.githubusercontent.com/27659/86282533-4a0ad800-bb94-11ea-90fe-dd8050516c36.png)

![Screen Shot 2020-07-01 at 12 05 59 PM](https://user-images.githubusercontent.com/27659/86282557-52fba980-bb94-11ea-8cde-f97a411daa33.png)

Checking the PUT (when editing a workload ) and POST (when creating) requests the `port` key in the spec is sent with an empty `[]`

PUT:

```json
...
            "spec": {
                "containers": [{
                    "image": "sangeetha/mytestcontainer",
                    "imagePullPolicy": "Always",
                    "name": "test1",
                    "resources": {},
                    "terminationMessagePath": "/dev/termination-log",
                    "terminationMessagePolicy": "File",
                    "ports": []
                }],
                "dnsPolicy": "ClusterFirst",
                "restartPolicy": "Always",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "terminationGracePeriodSeconds": 30
            }
...
```

POST:

```json
...
    "spec": {
        "replicas": 1,
        "template": {
            "spec": {
                "restartPolicy": "Always",
                "containers": [{
                    "name": "test2",
                    "imagePullPolicy": "Always",
                    "image": "sangeetha/mytestcontainer",
                    "ports": []
                }]
            },
            "metadata": {
                "labels": {
                    "workload.user.cattle.io/workloadselector": "deployment-testns1-test2"
                }
            }
        },
        "selector": {
            "matchLabels": {
                "workload.user.cattle.io/workloadselector": "deployment-testns1-test2"
            }
        }
    }
...
```

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `9b0dd20b7`**

- Create a deployment with ports enabled.
- The ports are set on the deployment.

<img width="1447" alt="Screen Shot 2020-08-06 at 5 07 29 PM" src="https://user-images.githubusercontent.com/26032343/89594810-b74f0000-d807-11ea-9e61-0c5879049034.png">
