### ISSUE TITLE
Home page not load in safari

### ISSUE THREAD

**Issue by liyimeng** [rancher/dashboard#8023]
I try to run 'yarn dev' on master, the build went well, but home page not loaded,  safari complains this line as syntax error:
https://github.com/rancher/dashboard/blob/40afad6ccda7b1c893f80a4378ce502cc488b213/shell/edit/workload/index.vue#L41

Safari error:

```
SyntaxError: Invalid regular expression: invalid group specifier name
            var match = error.match(/(?<=\")(.*?)(?=\")/gi);  --->  Invalid regular expression: invalid group specifier name

```

**Comment by liyimeng** [comment]
firefox load without issue though.

**Comment by cnotv** [comment]
Positive lookbehind is not supported in Safari, that's why. Going to rewrite the RegEx with something else.

**Comment by liyimeng** [comment]
test and works
