### ISSUE TITLE
[Monitoring V2] UI Requirements

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#803]
## Overview

Minimum Requirements for Release:
- Basic Configuration (https://github.com/rancher/dashboard/issues/908)
- Advanced Configuration (https://github.com/rancher/dashboard/issues/909)

Fast Followups for Release:
- Minor updates to defaults in the basic configuration (https://github.com/rancher/dashboard/issues/1128)
- Add field for ignoreNamespaceSelectors (https://github.com/rancher/dashboard/issues/1129)
- Add RKE2 as a Cluster Type (https://github.com/rancher/dashboard/issues/1130)
- Update namespace from monitoring-system to cattle-monitoring-system (https://github.com/rancher/dashboard/issues/1131)
- Prevent deploy when Prometheus Operator already exists (https://github.com/rancher/dashboard/issues/1167)
- Expose global fields to construct proxy URLs for chart deployment (https://github.com/rancher/dashboard/issues/1168)
- Feature Overview page (https://github.com/rancher/dashboard/issues/1064)
- Navigation Bar (https://github.com/rancher/dashboard/issues/1215)
- Minor fixes (https://github.com/rancher/dashboard/issues/1230)
- Move Prometheus / Alertmanager from Overview to Navigation Bar (https://github.com/rancher/dashboard/issues/1260)

Additional Requests (in order of prioritization):
- Feature Overview Page: CRD Summary (https://github.com/rancher/dashboard/issues/1175)
 - A UI for creating / configuring Prometheus CRs (https://github.com/rancher/dashboard/issues/808)
- Display graphs in cluster overview dashboard graphs (https://github.com/rancher/dashboard/issues/812)
- Custom UI Component for Grafana Dashboard (https://github.com/rancher/dashboard/issues/806)
- Custom UI Component for Grafana Datasource (https://github.com/rancher/dashboard/issues/807)
- A UI for creating / configuring ServiceMonitor CRs (https://github.com/rancher/dashboard/issues/809)
- A UI for creating / configuring PodMonitor CRs (https://github.com/rancher/dashboard/issues/810)
- RFE: Ability for users to test out AlertManager configurations https://github.com/rancher/dashboard/issues/1187

In the below UI specifications, any nil value mentioned is an optional setting and should ideally show a button that says `Configure` next to it. Once shown, users should be able to make it nil again by clicking on a button that says `Remove`.

I also make a reference to UIs for the following components:

#### LabelSelector

UI for a [`k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector`](https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#labelselector-v1-meta)

Default is nil. If nil, this should submit {}.

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Match Labels | `*.matchLabels` | `key`: `value` inputs | nil
Match Expressions | `*.matchExpressions` | `key`: String<br>`operator`: Dropdown (`In`, `NotIn`, `Exists` and `DoesNotExist`)<br>`values`: List of Strings. Only required to have at least one element if `operator` is `In` or `NotIn`, otherwise disabled. | nil

#### NamespaceSelector

UI for a [`github.com/coreos/prometheus-operator/pkg/client/monitoring/v1.NamespaceSelector`](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#namespaceselector)

Header / Label Name |  k8s YAML | Input | Default
---|---|---|---|
Use All Namespaces | `any` | Boolean | True
Whitelist of Namespaces | `*.matchNames` | Ability to select multiple namespaces within a cluster (Dropdown) | nil

If `Use All Namespaces` is selected, `Whitelist of Namespaces` should be disabled.

## Custom UI Components

Collection View: Viewing a collection of these components should display all ConfigMaps and Secrets in the namespace that have the particular label attached to them. There should also be a column that displays whether the given resource is defined as a ConfigMap or a Secret.

### Grafana Dashboard

A ConfigMap or Secret with a particular label `grafana_dashboard` that persists a Grafana dashboard.

_Type Help Text: ConfigMaps should be used for storing Grafana Dashboards unless Secrets are specifically required._

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Type | `kind` | Radio button for `ConfigMap` or `Secret` | `ConfigMap`
Labels | `metadata.labels.<key>` | `key`: `value` inputs | `grafana_dashboard`:`1`

Per Dashboard:

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Filename | `data.<name>` | String (needs to be acceptable as k8s key, so no spaces) | `dashboard.json`
Dashboard JSON | Value at `data.<name>` | JSON | nil

There should be a `+` button under the Dashboards that allows users to submit multiple `name`:`dashboard.json` pairs. There should also be a `Remove` button on each Dashboard to allow them to be removed.

### Grafana Datasource

A ConfigMap or Secret with a particular label `grafana_datasource` that adds a Grafana datasource.

_Type Help Text: Secrets should be used to store Grafana Datasources to avoid leaking sensitive information that configures access to the datasource._

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Type | `kind` | Radio button for `ConfigMap` or `Secret` | `Secret`
Labels | `metadata.labels.<key>` | `key`: `value` inputs | `grafana_datasource`: `1`

Per Datasource:

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Filename | `data.<name>` | String (needs to be acceptable as k8s key, so no spaces) | `datasource.yaml`
Datasource | Value at `data.<name>` | YAML | nil

There should be a `+` button under the Datasources that allows users to submit multiple `name`:`datasource.yaml` pairs. There should also be a `Remove` button on each Datasource to allow them to be removed.

On create/edit, user should be notified via banner that they need to restart their Grafana deployment to see changes (based on the [Grafana docs](https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-datasources)).

### Prometheus

Configures a Prometheus server deployment based on selected ServiceMonitors, PodMonitors, and PrometheusRules

_Namespace Selectors Help Text: Allows you to select resources from namespaces by labels attached to namespaces. If not configured, the namespace of the Prometheus CRD is selected._

_Label Selectors Help Text: Allows you to filter resources within the selected namespaces by labels attached to the resource. If not configured, all resources are selected in the selected namespaces._

#### ServiceMonitor
Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Namespace Selector | `spec.serviceMonitorNamespaceSelector` | See `LabelSelector` | nil
Labels Selector | `spec.serviceMonitorSelector` | See `LabelSelector` | nil

If possible, we should provide links to all ServiceMonitors which match the Labels Selector within all Namespaces that match the Namespace Selector here.

#### PodMonitors
Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Namespace Selector | `spec.podMonitorNamespaceSelector` | See `LabelSelector` | nil
Labels Selector | `spec.podMonitorSelector` | See `LabelSelector` | nil

If possible, we should provide links to all PodMonitors which match the Labels Selector within all Namespaces that match the Namespace Selector here.

#### PrometheusRules
Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Namespace Selector | `spec.rulesNamespaceSelector` | See `LabelSelector` | nil
Labels Selector | `spec.rulesSelector` | See `LabelSelector` | nil

If possible, we should provide links to all PrometheusRules which match the Labels Selector within all Namespaces that match the Namespace Selector here.

#### AlertManagers (default is empty list)
Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Namespace | `spec.alerting.alertmanagers[i].namespace` | Dropdown list of namespaces with ability to supply free-form text | `cattle-monitoring`
Name | `spec.alerting.alertmanagers[i].name` | Dropdown list of names of AlertManagers within the selected namespace with ability to supply free-form text; should be disabled if namespace is not selected yet | `cattle-monitoring`
Port | `spec.alerting.alertmanagers[i].port` | Integer | 9093
Scheme | `.spec.alerting.alertmanagers[i].scheme` | Dropdown of `http` or `https` | nil
Path Prefix | `.spec.alerting.alertmanagers[i].pathPrefix` | String | nil
TLS Config | `.spec.alerting.alertmanagers[I].tlsConfig` | YAML | nil
Bearer Token File for AlertManager | `.spec.alerting.alertmanagers[I].bearerTokenFile` | String | nil

There should be a `+` button under the AlertManagers that allows users to submit multiple create more AlertManager configurations. There should also be a `Remove` button on each AlertManager to allow them to be removed.

#### Storage

If `spec.storage` is missing (or on creating a new Prometheus resource), there should be a button that says `Configure`. If it exists (i.e. modifying an existing resource), the radio button value mentioned in the next step will be determined based on whether `spec.storage.emptyDir` or `spec.storage.volumeClaimTemplate` exists; if both are defined, `spec.storage.emptyDir` will take priority.

Upon clicking on `Configure`, a radio button should be shown which has two options: `EmptyDir` or `VolumeClaimTemplate`. `EmptyDir` should be selected by default.

If `EmptyDir` is selected, the following fields should be shown:

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Medium | `spec.storage.emptyDir.medium` | Radio button for `Use nodes default medium` (i.e. "") or `Mount a tmpfs (RAM-backed filesystem)`  (i.e. "Memory") | ""
Size Limit | `spec.storage.emptyDir.sizeLimit` | String (Quantity) | nil

If `VolumeClaimTemplate` is selected, the following fields should be shown:

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Metadata | `spec.storage.volumeClaimTemplate.metadata` | YAML | nil
Spec | `spec.storage.volumeClaimTemplate.spec` | YAML | nil

At the bottom, a button that says `Remove` should be shown that removes `spec.storage` entirely. After clicking on this button, `Configure` should be shown once again.

#### Secrets
Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Additional Scrape Configurations | .spec.additionalScrapeConfigs | `name`: String <br> `key`: String | nil
Additional AlertManager Configurations | .spec.additionalAlertManagerConfigs | `name`: String <br> `key`: String | nil
Additional AlertManager Relabel Configurations | .spec.additionalAlertRelabelConfigs | `name`: String <br> `key`: String | nil

If possible, name should be represented by a dropdown with the names of all the keys in the same namespace as the Prometheus CRD and key should be represented as a dropdown with the list of keys in the Secret selected in name. If this is not possible, string inputs for both values should be good, as represented above.

### ServiceMonitor

Generates the scrape configuration of a Prometheus instance based on labeled Services.

_Namespace Selectors Help Text: Allows you to restrict namespaces of Service resources that can be monitored. By default, the ServiceMonitor monitors all namespaces._

_Label Selectors Help Text: Allows you to identify Services to monitor by the labels on each Service. By default, no Services are monitored._

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Namespace Selector | `spec.namespaceSelector` |  See `NamespaceSelector` | nil
Labels Selector | `spec.selector` | See `LabelSelector` | {}
Endpoints | `spec.endpoints` | YAML | Empty
Job Label | `spec.jobLabel` | String | nil
Target Labels | `spec.targetLabels` | List of Strings | nil
Pod Target Labels | `spec.podTargetLabels` | List of Strings | nil
Maximum Samples Per Scrape | `spec.sampleLimit` | uint64 | nil

If possible, we should provide links to all Services which match the Labels Selector within all Namespaces that match the Namespace Selector here.

### PodMonitor

Generates the scrape configuration of a Prometheus instance based on labeled Pods.

_Namespace Selectors Help Text: Allows you to restrict namespaces of Pod resources that can be monitored. By default, the PodMonitor monitors all namespaces._

_Label Selectors Help Text: Allows you to identify Pods to monitor by the labels on each Pod. By default, no Pods are monitored._

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Namespace Selector | `spec.namespaceSelector` |  See `NamespaceSelector` | nil
Labels Selector | `spec.selector` | See `LabelSelector` | {}
Endpoints | `spec.podMetricsEndpoints` | YAML | Empty
Job Label | `spec.jobLabel` | String | nil
Pod Target Labels | `spec.podTargetLabels` | List of Strings | nil
Maximum Samples Per Scrape | `spec.sampleLimit` | uint64 | nil

If possible, we should provide links to all Pods which match the Labels Selector within all Namespaces that match the Namespace Selector here.

**Comment by deniseschannon** [comment]
As these are mostly epics for the entire UI requirements of the feature, I"m going to remove the milestone as all tickets for the feature are tracked separately.

**Comment by deniseschannon** [comment]
I'm going to close this ticket even though several tickets in it aren't done, but the overall progress on all the other tickets will be tracked in the currently open remaining issues.
