### ISSUE TITLE
Namespace changes on Workload creation are not kept

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8031]
**Setup**
- Rancher version: Latest
- Browser type & version: Any

**Describe the bug**
When I create a new Workload and select the Namespace, the value is not updated

**To Reproduce**
- Create a new Workload (e.g. Pod)
- Pick a different namespace
- Create the resource
- Open the Workload details or editor

**Result**
- Old Namespace is used

**Expected Result**
- Intended Namespace

**Screenshots**

**Additional context**

**Comment by cnotv** [comment]
Issue seems to happen also for `Services` but not for `PersistentVolumeClaims`

**Comment by dasarinaidu** [comment]
Validated this issue on `v2.7-7913e283ff90eebd1f8cc48860a6b410d72cd4dd-head` . This issue got fixed and closing the issue.

**Validation Details:**

1. Validated below tests with Admin and Standard user
2. Validated below tests on RKE2 cluster (Downstream cluster)
3. Validated below tests on Auto and Dark modes
4. Validated with Deployment and Service creation

**Reproducible Steps:**

1. Provision Rancher
2. Login with user
3. Downstream cluster
5. Create a Project and NameSpace
6. Create a Deployment and check for the default NameSpace selected while creating deployment
7. Try to create another deployment and check for the default Name Space which was selected
8. Make sure the default Name space selected should be from Last Picked up value while creating the deployment

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/22034884/228077436-7baca69b-3db3-45bf-9aa9-d8928f8d62f9.png">
