### ISSUE TITLE
PSA: Update PSA default

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8032]
**Changes required:**

The PSP default 'RKE Default' should be labeled 'Default - RKE2 Embedded'.

The PSA default is currently labeled '(None)' - this is fine for k8s <1.25 (because in k8s <1.25 RKE2 does not automatically apply any PSA).
When the version is >= 1.25, instead of "(None)" we should have "Default - RKE2 Embedded" (which "maps" to empty PSACT on Cluster YAML). Note that this does _not_ apply to k3s as it doesn't automatically apply PSA.

If the user changes the CIS Worker Profile to anything other than "None" **on k8s >= 1.25**, then we need to reset the PSA to "rancher-restricted" (it's guaranteed to exist) and disable the control to prevent the user changing it. We should show a banner or somehow indicate that we've done this.

In some cases, the user may create a PSA Configuration Template (PSACT) that is compatible with the "rancher-restricted" - they may want to use this with CIS Worker Profile set to something other than None - I suggest a checkbox 'Allow PSA Default Template to be overridden when using a CIS Profile". Checking this would enable the PSA template dropdown and allow them to select their own.

We should show a banner if they check this that they understand that they know what they are doing.

Note: The Rancher Default is different to the RKE2 Default, so we can't use their docs - Rancher should provide docs that we can link to when done.

**Comment by nwmac** [comment]
@kwwii FYI - feel free to update the UX of how/where the docs link should appear

**Comment by cnotv** [comment]
To recap these combination of cases:
- k8s < 1.25.x + CIS different than `(None)`:
 - PSA label is `Rancher Default`
 - Status disabled
- k8s < 1.25.x + CIS `(None)`:
 - PSA label is`(None)`
 -  Status enabled
- k8s >= 1.25.x + CIS different than `(None)`:
 - PSA label is `Rancher Default`
 - Status disabled
- k8s >= 1.25.x + CIS `(None)` or CIS checkbox enabled:
 - PSA label is`Rancher Default`
 -  Status enabled

**Comment by cnotv** [comment]
I take the chance to signal that we do not have to display the banner if it's not RKE2, as we do not have PSP for K3.

![Screenshot 2023-02-06 at 16 52 38](https://user-images.githubusercontent.com/5009481/217019283-a8269c93-cd39-401a-83cc-2127d27e038a.png)

@nwmac Please correct me if I'm wrong.

**Comment by cnotv** [comment]
In view of the [K3S requirement](https://github.com/rancher/dashboard/issues/8061) to have PSA, could you please tell me if I've to keep the banner in this case?
@kwwii @nwmac

**Comment by snasovich** [comment]
> k8s < 1.25.x + CIS different than `(None)`:
> * PSA label is `Rancher Default`
> * Status disabled

@cnotv , k8s <1.25.x with CIS profile different from none will be using PSP either one specified in Rancher UI or default coming from RKE2. So I don't believe we should automatically set PSA in this case, it should remain "None".

Could you please also clarify what do you mean by "Status disabled"? User can't change the selected PSA value?

**Comment by cnotv** [comment]
Status disabled means that the input cannot be used because is disabled. It does not refer to the model or resource.

**Comment by cnotv** [comment]
@snasovich in the UI we do not set automatically no PSP and no PSA whatsoever. This is a logic implemented server side from the other teams. Regardless that's `(None)` or `Rancher Default`, in the UI that's always empty value.

**Comment by cnotv** [comment]
As mentioned in the previous conversation, the order of the inputs will be:
- PSA/CIS
- CIS override
- PSA

**Comment by cnotv** [comment]
Given the latest update, the logic is definitely way simpler.
Label:
- k8s < 1.25.x: PSA label is`(None)`
- k8s >= 1.25.x: PSA label is`Rancher Default`

Input status: 
- CIS not set or set with override: enabled
- CIS not set: disabled

**Comment by cnotv** [comment]
Checkbox has to be displayed only if PSA is needed.

**Comment by cnotv** [comment]
@kwwii Is the logic for the PSA label the same also in case of K3S, since now it's enabled?

**Comment by kwwii** [comment]
I assume it is the same but we should confirm this.

**Comment by cnotv** [comment]
Increasing size after changing requirements.

**Comment by markusewalker** [comment]
Validated this against `v2.7-head` https://github.com/rancher/rancher/commit/ab561bf837ca6051176bf169784edb01d9dee134. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/ab561bf837ca6051176bf169784edb01d9dee134
- Browser: Chrome

**TEST RESULTS**
|Scenario|Test Case|Result|
|---|---|---|
|1|As a standard user, validate that CIS Profile 1.23 appears only for K8s v1.25 and `rancher-restricted` is set by default|:white_check_mark:|
|2|As a standard user, validate that CIS Profiles 1.5 and 1.6 appear for K8s < v1.25|:white_check_mark:|
|3|As a standard user, provision a downstream RKE2 v1.25 custom cluster with CIS 1.23, validate cluster and nodes are `Active`|:white_check_mark:|
|4|As a standard user, provision a downstream RKE2 v1.24 custom cluster with CIS 1.6, validate cluster and nodes are `Active`, upgrade cluster to v1.25 and CIS to 1.23, validate cluster and nodes upgrade|:white_check_mark:|

**Scenario 1**
1. Navigated to Cluster Management > Create > Custom.
2. Using K8s v1.25, clicked the `CIS Profile` dropdown and validated only `cis-1.23` appears:
![image](https://user-images.githubusercontent.com/52591819/220490025-cdd41da5-ae1d-4968-ac32-b16a168ae5f5.png)
3. Clicking `cis-1.23`, I noted that `rancher-restricted` is selected by default as expected:
![image](https://user-images.githubusercontent.com/52591819/220490119-3aee83be-6c3b-45f5-9173-6057368e7e54.png)
4. By clicking the `Allow PSA Default Template to be overridden when using a CIS Profile`, I can successfully modify the PSA template with any built-in and/or created PSA templates I have available:
![image](https://user-images.githubusercontent.com/52591819/220490274-b3765387-fc68-47f3-831e-fce21b352287.png)
______
**Scenario 2**
1.  Navigated to Cluster Management > Create > Custom.
2. Using K8s v1.24 and v1.23, the `CIS Profile` has values 1.5 and 1.6:
![image](https://user-images.githubusercontent.com/52591819/220490557-06e0c736-79f7-476c-a72b-8a4fd0f8e0fe.png)
3. Validated that the PSP default is set to `Default - RKE2 Embedded` and PSA is set to `rancher-restricted` when CIS Profile is selected or not selected.
_____
**Scenario 3**
1. Validated as part of this issue's [results](https://github.com/rancher/rancher/issues/40306#issuecomment-1439261091).
______
**Scenario 4**
1. Validated as part of this issue's [results](https://github.com/rancher/rancher/issues/40306#issuecomment-1439261091).
