### ISSUE TITLE
Remove matching chart UI component on RELEASE_NAME

### ISSUE THREAD

**Issue by jdloft** [rancher/dashboard#8034]
**Setup**
- Rancher version: 2.7.0
- Browser type & version: Chrome

See [loadValuesComponent](https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/apps/charts/install.vue#L847):

```js
    async loadValuesComponent() {
      // TODO: Remove RELEASE_NAME. This is only in until the component annotation is added to the OPA Gatekeeper chart.

      // The const component is a string, for example, 'monitoring'.
      const component = this.version?.annotations?.[CATALOG_ANNOTATIONS.COMPONENT] || this.version?.annotations?.[CATALOG_ANNOTATIONS.RELEASE_NAME];

      // Load a values component for the UI if it is named in the Helm chart.
      if ( component ) {
        const hasChartComponent = this.$store.getters['type-map/hasCustomChart'](component);

        if ( hasChartComponent ) {
          this.valuesComponent = this.$store.getters['type-map/importChart'](component);
          const loaded = await this.valuesComponent();

```

OPA Gatekeeper now has `catalog.cattle.io/ui-component: gatekeeper` set. Remove old `RELEASE_NAME` matching. Current behavior prevents custom charts from having a release name that matches any of the chart UI components.

**Comment by jdloft** [comment]
I found this because our custom logging chart has the release name set to "logging" and Rancher overrides the `questions.yaml` with the UI component from `rancher-logging`.

**Comment by aiyengar2** [comment]
Alerting Drivers also has a custom UI and needs changes in accordance to this, since it only uses release name: https://github.com/rancher/charts/blob/68715dbeb79b884e9e151fe5a6aea58a59cdc6e2/charts/rancher-alerting-drivers/102.0.0/Chart.yaml#L8

**Comment by nwmac** [comment]
@aiyengar2 We are going to remove the custom UI as the chart has a questions.yaml which seems to achieve the same

**Comment by richard-cox** [comment]
> @aiyengar2 We are going to remove the custom UI as the chart has a questions.yaml which seems to achieve the same

I've captured this in https://github.com/rancher/dashboard/issues/8053#issuecomment-1426211335

**Comment by nickwsuse** [comment]
`Verified on v2.7-head ID: a49d36c`

Just getting back around to this, but OPA Gatekeeper was included in my testing of https://github.com/rancher/dashboard/issues/8053 so this one should be good too.
