### ISSUE TITLE
Update warning about PSAC templates

### ISSUE THREAD

**Issue by cbron** [rancher/dashboard#8037]
On the list, or edit, page for PSAC templates, we need a warning that states how the templates work and repercussions of changes. 
Specifically: Changing any template that is currently in use _will_ cause an update to those live clusters the next time the cluster is updated.

**Comment by gaktive** [comment]
@cbron can you link to the anticipated backend work so UI can keep an eye on things?

**Comment by snasovich** [comment]
@gaktive @cbron , I believe this is already done per https://github.com/rancher/rancher/issues/40289
Please also note minor UI issue raised related to this change https://github.com/rancher/dashboard/issues/8015 that may as well be absorbed into this one.

**Comment by gaktive** [comment]
Thanks @snasovich; shall we close this ticket in light of #8015 then? or copy its materials here and then close that?

**Comment by snasovich** [comment]
@gaktive , this issue seems to be "wider" while #8015 is essentially a minor issue about adding the description to the newly introduced role. I think we want contents of #8015 copied here and close #8015 as superseded by this one.

**Comment by gaktive** [comment]
From #8015 (via @HarrisonWAffel -- we closed that ticket in light of this one):

Recently a [PR was raised](https://github.com/rancher/rancher/pull/40295) to introduce a new built-in role for managing `PodSecurityAdmissionConfigurationTemplates`. During the creation of that PR I noticed that the UI provides a display name for that role when creating a new user that is not present in rancher/rancher. 

In the rancher/rancher codebase the role is defined with the following name 
![Screen Shot 2023-01-24 at 5 11 20 PM](https://user-images.githubusercontent.com/25062254/214442247-2d8494af-e9a0-4639-bead-7ba39a4b89b1.png)

However, when viewed in the UI the role looks like the following, and includes a description 
![Screen Shot 2023-01-24 at 6 16 28 PM](https://user-images.githubusercontent.com/25062254/214442372-681e45a6-1c81-4761-9301-15b326c9efe3.png)

We would like to have a similar formatting applied to the new PSACT role, as well as a description added below the name
![Screen Shot 2023-01-24 at 6 16 28 PM](https://user-images.githubusercontent.com/25062254/214442435-c487a414-7a7d-41e1-a09a-9e264acef628.png)
Both the description and name of the PSACT role should mirror the description and name of the PSP role, 

Name: `Manage Pod Security Admission Configuration Templates (PSACTs)`
Description: ` Allows the user to define, edit, and remove PSACTs.`

**Comment by cbron** [comment]
I would still consider this backend blocked, because even though the code has merged, we haven't fully decided what to do here.

**Comment by gaktive** [comment]
This will be a banner, either inline.

**Comment by gaktive** [comment]
We await what the copy is to show in the banner/alert/what-have-you.

**Comment by gaktive** [comment]
@Sahota1225 has a meeting scheduled for Monday to bring this up.

**Comment by gaktive** [comment]
Upon discussion, there won't be a new role - but we need to add banners to warn users that it they update a PSAC. It will get applied to an existing cluster that references that PSAC the next time a change to that cluster (e.g. edit causes an update).

**Comment by gaktive** [comment]
As follow, documentation will be updated to indicate this role will be admin only during role creation as a workaround.

**Comment by cbron** [comment]
This issue has been rewritten, and is no longer backend blocked. Please review the title and description for the new request.

**Comment by cnotv** [comment]
We have already a warning, so this is about _update_ the content.

**Comment by slickwarren** [comment]
tested on v2.7-head (cca09e4):
* banner now displays in `pod security admissions` resource on all clusters with the correct messaging:
<img width="852" alt="Screen Shot 2023-02-28 at 1 14 28 PM" src="https://user-images.githubusercontent.com/16691014/221991396-35109913-1d7c-4e5f-b0f3-7ec23b1a5bcd.png">
cross-referencing this issue to improve user experience: https://github.com/rancher/dashboard/issues/8274
