### ISSUE TITLE
[BUG] Rancher dashboards are not loading on Safari

### ISSUE THREAD

**Issue by geethub97** [rancher/dashboard#8039]
**Setup**
- Rancher version: 2.7-head and latest
- Browser type & version: Safari 16.1

**Describe the bug**
Rancher does not load on Safari. See screenshots below. 

**To Reproduce**
Deploy Rancher on an EC2 instance and navigate to UI on Safari. 

**Result**

**Expected Result**
Rancher UI to load. 

**Screenshots**
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/99695266/214927012-637e7adf-8edf-4ea7-872a-61c124e8a1e2.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/99695266/214926983-059064f2-cee7-495b-aa31-9bd15232416a.png">

**Additional context**

**Comment by gaktive** [comment]
@geethub97 to confirm, this is happening on every page you've tried? Looks like a variable name typo (hopefully) so it should be an easy fix.

**Comment by geethub97** [comment]
@gaktive I wasn't able to access the login screen so I couldn't check any of the other pages, so I'm not sure how many others are affected.

**Comment by liyimeng** [comment]
same as #8023 and fixed in #8029

**Comment by gaktive** [comment]
@geethub97 as noted, a fix for this should already be in based on #8080 -- can you retest against that?

**Comment by geethub97** [comment]
@gaktive tested, it's working now. thank you!!
