### ISSUE TITLE
Gatekeeper chart install does not use custom UI component

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8043]
The `ui-component` annotation has been added to the chart for OPA Gatekeeper, but with the value `gatekeeper`. The custom UI component is named `rancher-gatekeeper` which does not match, so the custom UI is not used.

To reproduce:

Go to Apps -> Charts -> OPA Gatekeeper -> Install and click next to get to the `Values` step. Observe that you see a YAML editor like this:

![image](https://user-images.githubusercontent.com/1955897/215080422-08c30a68-3e68-4e06-a565-e876e2464860.png)

You should see a custom form like this:

![image](https://user-images.githubusercontent.com/1955897/215080596-8a36c85f-5fd8-4bb0-b6a6-0652637fee99.png)

The fix is to rename this file: https://github.com/rancher/dashboard/blob/master/shell/chart/rancher-gatekeeper.vue to `gatekeeper.vue`.

**Comment by richard-cox** [comment]
There was some other strangeness with OPA gatekeeper, see https://github.com/rancher/dashboard/issues/8034 (and fix https://github.com/rancher/dashboard/pull/8041)

**Comment by nwmac** [comment]
Yeah - that’s a workaround that is no longer needed.

**Comment by gaktive** [comment]
Updated PR: https://github.com/rancher/dashboard/pull/8041 -- originally for 2.7.next2 for Q2 but moved to 2.7.2

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7.2-rc6`
OPA Gatekeeper
102.0.0+up3.10.0
Installation flow - encountered correct screen:

![2023-03-21_10-43-29.png](https://zube.io/files/rancher/b7863f47326f2b0a726badf3648ca16b-2023-03-21_10-43-29.png)
