### ISSUE TITLE
The DetailTop is empty for the Ingress Page

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#805]
We need to add the relevant fields to the detail top.

**Comment by deniseschannon** [comment]
With the redesign for how we are laying out detailtop in https://github.com/rancher/dashboard/issues/817, this might not be empty.

**Comment by codyrancher** [comment]
We decided that for the time being we don't want to add any details to the DetailTop of the ingress page so I'm going to resolve this.
