### ISSUE TITLE
PSP Removal: Add banner to application list page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8051]
On the page that lists applications, if the cluster being explored is < 1.25, show a banner, same as on the cluster list page:

'PSP Removal: Before upgrading a cluster to Kubernetes 1.25+, please ensure you review your Helm applications for Pod Security Policies and update them accordingly'

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision an RKE1 v1.23 node driver cluster with PSP enabled, validate that the charts page has a PSP removal banner present, upgrade to v1.25, validate that the banner is no longer present|
|2|As a standard user, provision an RKE2 v1.24 custom cluster with PSP enabled, validate that the charts page has a PSP removal banner present, upgrade ot v1.25, validate that the banner is no longer present|
|3|As a standard user, provision an RKE1 v1.24 node driver cluster with PSP enabled and PSA set to `rancher-privileged`, validate that the charts page has a PSP removal banner present, disable PSP, upgrade to v1.25, validate that the banner is no longer present|

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.7-head` https://github.com/rancher/rancher/commit/62c5e321da5b576e565adf12c666489de9ea9373. See results below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/62c5e321da5b576e565adf12c666489de9ea9373
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision an RKE2 v1.23 node driver cluster with PSP enabled, validate that the charts page has a PSP removal banner present, disable PSP and enable PSA level `rancher-privileged`, upgrade to v1.25, validate that the banner is no longer present|:white_check_mark:|
|2|As a standard user, provision an RKE2 v1.24 custom cluster with PSP enabled, validate that the charts page has a PSP removal banner present, disable PSP and enable PSA level `rancher-privileged`, upgrade to v1.25, validate that the banner is no longer present|:white_check_mark:|
|3|As a standard user, provision an RKE2 v1.24 node driver cluster with PSP enabled and PSA set to `rancher-restricted`, validate that the charts page has a PSP removal banner present, disable PSP, upgrade to v1.25, validate that the banner is no longer present|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Provisioned an RKE2 v1.23 node driver cluster with PSP set to `RKE Default`.
2. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
3. Navigated to Cluster Explorer > RKE2 cluster > Apps.
4. Validated that there is a PSP removal banner:
![image](https://user-images.githubusercontent.com/52591819/219455097-0d35434f-768f-4a9a-8fe8-5cbf3d5d9170.png)
5. Edited the cluster to disable PSP and to enable PSA level `rancher-privileged`.
6. Upgraded the cluster and validated that the cluster and nodes are at v1.25.
7. Navigated back to Cluster Explorer > RKE2 cluster > Apps.
8. Validated that there no longer is a PSP removal banner:
![image](https://user-images.githubusercontent.com/52591819/219455129-df3c9a0a-df5c-41b4-9771-68c770557abf.png) 
_________
**Scenario 2**
1. Repeated scenario 1 steps 1-4, but used an RKE2 v1.24 custom cluster with PSP set to `RKE Default` instead.
2. Repeated scenario 1 steps 5-8 with the same successful results.
_________
**Scenario 3**
1. Repeated scenario 1 steps 1-3, but used an RKE2 v1.24 node driver cluster with PSP set to `RKE Default` and PSA level set to `rancher-restricted` instead.
2. Repeated scenario 1 steps 5-8 with the same successful results.
