### ISSUE TITLE
PSP Removal: Update custom chart UIs

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8053]
We have 6 custom UI components that are used during Helm chart installation of specific charts in place of the default yaml editor or form generated from `questions.yaml` - they are:

- Logging
- Alerting Drivers
- Istio
- Monitoring
- Rancher Backup
- OPA Gatekeeper

We need to update all of them to add a checkbox to enable PSPs when installing the chart - I suggest a common component that we can use - the value it should set is: `global.cattle.psp.enabled`. It should default to the value specific in the chart values.

**Comment by deniseschannon** [comment]
For Istio, there are 3 charts that have the ability to enable/disable PSP, so this would need to be available for all 3 charts. 

rancher-istio
rancher-tracing
rancher-kiali-server

**Comment by richard-cox** [comment]
I stumbled on the issue of the Alerting Drivers showing a custom component and not it's questions.yaml in https://github.com/rancher/dashboard/pull/8041#issuecomment-1421178004. The UI will display a custom component if it finds one named with either the [catalog.cattle.io/ui-component](http://catalog.cattle.io/ui-component) OR [catalog.cattle.io/release-name](http://catalog.cattle.io/release-name) annotation (https://github.com/rancher/dashboard/issues/8034 will remove the latter). UI shows a custom component for the alerting driver (instead of it's questions.yaml) as it has a custom component that matches the [catalog.cattle.io/release-name](http://catalog.cattle.io/release-name) annotation. 

FWIW Out of Logging, Monitoring, Backup, Istio, Alerting and Gatekeeper ... only alerting has a questions.yaml

**Comment by richard-cox** [comment]
As part of this work the custom ui for Alerting Drivers (`shell/chart/rancher-alerting-drivers.vue`) should be removed (see https://github.com/rancher/dashboard/issues/8034#issuecomment-1425548710). That will result in the existing `questions.yaml` being used which contains psp options

**Comment by nickwsuse** [comment]
`Verified on v2.7-head ID: a49d36c`

The PSP options are present in the following charts and their version(s):
- Logging: `v102.0.0+up3.17.10 (and many older versions)`
- Alerting Drivers: `v102.0.0`
- Istio: `v102.0.0+up1.15.3 (and many older versions)`
- Monitoring:` v102.0.0+up40.1.2 (and many older versions)`
- Rancher Backups: `v102.0.0+up3.1.0-rc3`
- OPA Gatekeeper: `v102.0.0+up3.10.0 (and many older versions)`

The following yaml is present for each of the charts and their versions listed above.

```
global:
  cattle:
    psp:
      enabled: false
```

All of the charts also contain the following info on their ReadMe:
```
Upgrading to Kubernetes v1.25+
Starting in Kubernetes v1.25, [Pod Security Policies](https://kubernetes.io/docs/concepts/security/pod-security-policy/) have been removed from the Kubernetes API.

As a result, before upgrading to Kubernetes v1.25 (or on a fresh install in a Kubernetes v1.25+ cluster), users are expected to perform an in-place upgrade of this chart with global.cattle.psp.enabled set to false if it has been previously set to true.

Note:
In this chart release, any previous field that was associated with any PSP resources have been removed in favor of a single global field: global.cattle.psp.enabled.

Note:
If you upgrade your cluster to Kubernetes v1.25+ before removing PSPs via a helm upgrade (even if you manually clean up resources), it will leave the Helm release in a broken state within the cluster such that further Helm operations will not work (helm uninstall, helm upgrade, etc.).

If your charts get stuck in this state, please consult the Rancher docs on how to clean up your Helm release secrets.

Upon setting global.cattle.psp.enabled to false, the chart will remove any PSP resources deployed on its behalf from the cluster. This is the default setting for this chart.

As a replacement for PSPs, [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/) should be used. Please consult the Rancher docs for more details on how to configure your chart release namespaces to work with the new Pod Security Admission and apply Pod Security Standards.
```
