### ISSUE TITLE
[BUG] Can not create RKE2 cluster after enable Elemental extension

### ISSUE THREAD

**Issue by n313893254** [rancher/dashboard#8059]
**Rancher Server Setup**

- Rancher version: v2.7.0

**Describe the bug**

Can not create RKE2 cluster after enabling Elemental extension

**To Reproduce**

1. Install Rancher v2.7.0 by docker
2. Enable the extension feature and install the Elemental extension
3. Go cluster create the page, and check to create an RKE2 cluster,  e.g. Harvester or Linode

**Result**

Can not create RKE2 cluster as pending in create new cloud credential.

**Expected Result**

Can create RKE2 cluster

**Screenshots**

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/18737885/212695788-98064405-635d-48f0-8069-04cfc755f939.png">

**Additional context**

**Comment by n313893254** [comment]
Thanks for the [commit](https://github.com/rancher/elemental-ui/commit/c317df6907b3330cedc3a5ad06dd308f2b277b29) of @aalves08. Verified with the latest elemental UI. The UI shows as expected.

![image](https://user-images.githubusercontent.com/18737885/215323360-61eb1bb2-7487-47ac-b89c-be86263b4318.png)

**Comment by aalves08** [comment]
@n313893254 it looks from your comment that this is resolved. Is that correct?

**Comment by n313893254** [comment]
@aalves08 Yes, I think Elemental v1.0.1 will solve this issue. Seems it is `provisioning.cattle.io.cluster` overwriting it.

**Comment by aalves08** [comment]
Closing issue. FYI @gaktive
