### ISSUE TITLE
Monitoring V2: Custom UI for Grafana Dashboard

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#806]
Need a custom UI for Grafana Dashboard (ConfigMaps) for Monitoring V2.

Design requirements listed in parent ticket: https://github.com/rancher/dashboard/issues/803

**Comment by catherineluse** [comment]
Here are the relevant requirements from the above linked issue:


### Grafana Dashboard

A ConfigMap or Secret with a particular label `grafana_dashboard` that persists a Grafana dashboard.

_Type Help Text: ConfigMaps should be used for storing Grafana Dashboards unless Secrets are specifically required._

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Type | `kind` | Radio button for `ConfigMap` or `Secret` | `ConfigMap`
Labels | `metadata.labels.<key>` | `key`: `value` inputs | `grafana_dashboard`:`1`

Per Dashboard:

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Filename | `data.<name>` | String (needs to be acceptable as k8s key, so no spaces) | `dashboard.json`
Dashboard JSON | Value at `data.<name>` | JSON | nil

There should be a `+` button under the Dashboards that allows users to submit multiple `name`:`dashboard.json` pairs. There should also be a `Remove` button on each Dashboard to allow them to be removed.
