### ISSUE TITLE
Add support for Pod Security Admission - Cluster K3S

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#8061]
Main Issue: https://github.com/rancher/dashboard/issues/7119

The support for selecting the default Pod Security Admission should also be available when the cluster is K3S. 

Below is the edit page for the RKE2 cluster as a demonstration:
<img width="1680" alt="Screen Shot 2023-01-27 at 3 19 29 PM" src="https://user-images.githubusercontent.com/6218999/215216798-e22904f4-9f4a-4fe0-ae2b-3827118c8b47.png">

**Comment by cnotv** [comment]
@jiaqiluo please mind to link the issues when these are affected.

https://github.com/rancher/dashboard/issues/8068

PSA value should not be reset if we enable PSA for K3.

**Comment by kwwii** [comment]
The current UI does not offer the possibility to set a PSP for any K3S version. Does this ticket mean that this feature should now be enabled?

**Comment by jiaqiluo** [comment]
hi @kwwii. The security feature we want to enable for k3s clusters is PSA, more specifically using PSACT, not PSP. They are two different things :)

**Comment by kwwii** [comment]
@jiaqiluo I don't think that K3S currently has any UI for setting PSPs. Does this mean that there is a new feature for supporting PSAs in K3S? I don't think that we had this on our radar of outstanding UI work.

**Comment by jiaqiluo** [comment]
hi @kwwii
 
You are right that we do not have this feature request, and even the PRD documentation does not mention it (sorry that I did not realize this when I made the issue).   I think it made sense to expose the option in the UI because the Rancher backend supports using PSACT in K3S clusters; also, we already have it in the UI for RKE2 clusters.  

This can be treated as a new feature request. I notice the linked PR is already merged and this issue is labeled "to test". Grate job UI team!

**Comment by kwwii** [comment]
@jiaqiluo Sorry, I wasn't trying to point fingers - and wasn't aware that the work is already finished :-(

I wanted to ensure that everything gets done properly but apparently overlooked something.

**Comment by jiaqiluo** [comment]
@kwwii  No worries!

**Comment by markusewalker** [comment]
Sharing the basic, applicable use cases from the internal K8s 1.25 test plan here for track-ability.

**ENVIRONMENT**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/1dd2af2d214b159c2c8ffcfc5838b6caece381cd
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|As a standard user, provision a K3s 1.25 node driver with PSA value `rancher-privileged`, create a deployment with this cluster-level PSA and validate it is successful|:white_check_mark:|
|2|As a standard user, provision a K3s 1.25 node driver with PSA value `rancher-restricted`, create a deployment with a namespace of PSA level restricted and validate it fails|:white_check_mark:|
|3|As a standard user, provision a K3s 1.24 node driver with no PSA value, upgrade to v1.25 with PSA level `rancher-privileged`, create a deployment with this cluster-level PSA and validate it is successful|:white_check_mark:|

**Scenario 1**
1. In Rancher UI as a standard user, navigated to Cluster Management > Create.
2. In the Security section, updated the PSA dropdown to have value `rancher-privileged`.
3. Edit as YAML and validate that `spec.defaultPodSecurityAdmissionConfigurationTemplateName` is set to `rancher-privileged`.
4. Provisioned the cluster and validated that the cluster and nodes came up as Active in Cluster Management and Cluster Explorer.
5. Viewed the cluster's YAML and validate that `spec.defaultPodSecurityAdmissionConfigurationTemplateName` is set to rancher-privileged.
6. Verified the workloads/pods in System project page are up and Active.
7. Created a deployment with the container image `nginx:latest` and default settings in the `default` namespace; validated that the deployment came up as `Active`.
_______
**Scenario 2**
1. Repeated scenario 1, but in step 2, chose PSA value `rancher-restricted`.
     - Step 3 through 6 were successful, but the value in `spec.defaultPodSecurityAdmissionConfigurationTemplateName` reflect as `rancher-restricted`.
2. Created a new namespace called `test-namespace` in new project `test-project` with the following PSA levels:
![image](https://user-images.githubusercontent.com/52591819/219221789-a994b898-566c-4446-9841-e7346b0a19b7.png)
3. Created a deployment with the container image `nginx:latest` in the new `test-namespace` namespace; validated that the deployment fails as expected with the following message:
![image](https://user-images.githubusercontent.com/52591819/219221998-57cd24f0-6464-43a5-80f2-dd69144c6ada.png)
_______
**Scenario 3**
1. Repeated scenario 1 steps 1-4, but ensured that the K8s version is v1.24 with no PSA level set.
2. Upgraded the K8s version from v1.24 -> v1.25 and ensured that PSA level `rancher-privileged` is set.
3. Validated that the upgrade was successful and the cluster and nodes have the new K8s version in Cluster Management and Cluster Explorer.
4. Repeated scenario 1 steps 5-7 with the same successful results.

As these are basic use cases, if there are more advanced workflows that are found to have separate issues, separate issues will be logged at that time.
