### ISSUE TITLE
CRD charts should receive same global fields as main chart

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#8062]
As part of the larger issue in https://github.com/rancher/rancher/issues/40331 and specifically for monitoring in https://github.com/rancher/rancher/issues/40350, we need to ensure that on an install any CRD chart is provided the same settings under `global` that are being used to upgrade the main chart.

Specifically, for `rancher-monitoring-crd`, the `global.cattle.psp.enabled` field introduced in 2.7.2 needs to match what the user provided in the main chart.

**Comment by stormqueen1990** [comment]
This may also apply to the following charts:
* rancher-gatekeeper-crd
* rancher-logging-crd

**Comment by mantis-toboggan-md** [comment]
This will tie into https://github.com/rancher/dashboard/issues/8062 - the `global.cattle.psp.enabled` field needs to be added to the monitoring custom component

**Comment by gaktive** [comment]
The 6 charts (from #8053) are:
- Logging
- Alerting Drivers
- Istio
- Monitoring
- Rancher Backup
- OPA Gatekeeper

**Comment by mantis-toboggan-md** [comment]
The dashboard already configures crd charts with the same globals, see https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/apps/charts/install.vue#L1245
and in our docs: https://rancher.github.io/dashboard/code-base-works/helm-chart-apps#injected-global-values

**Comment by nickwsuse** [comment]
on v2.7.2-rc8 I see that the Monitoring CRD does have the global.cattle.psp.enabled field, but it's also not a 1:1 match with the main chart's global settings (I'm not sure if it's supposed to or if we mostly just care about the psp field)

That said, I checked the Logging chart and Logging CRD and there is NOT a global.cattle.psp.enabled field in the CRD's yaml, but there is for the main chart. 

@mantis-toboggan-md @gaktive @stormqueen1990

**Comment by mantis-toboggan-md** [comment]
> That said, I checked the Logging chart and Logging CRD and there is NOT a global.cattle.psp.enabled field in the CRD's yaml, but there is for the main chart. I'm currently checking the rest of the charts mentioned above to be sure if it's just logging or not.

@nickwsuse I'm not able to reproduce that behavior when installing logging. When I set `gloabl.cattle.psp.enabled: true` during install, then navigate to 'installed apps' and view the yaml of the crd app I see `spec.values.global.cattle.psp: true`...I see this in the Values YAML tab of the detail view as well

**Comment by stormqueen1990** [comment]
With regards to this, I have seen a strange behaviour when one checks and then immediately unchecks the checkbox for enabling PodSecurityPolicies in the Monitoring chart. I outlined steps to reproduce in [rancher/rancher#40998](https://github.com/rancher/rancher/issues/40998#issuecomment-1494519524).

**Comment by nickwsuse** [comment]
@mantis-toboggan-md It seems this is another instance of me not knowing fully how the Rancher UI/CRD works 🙃 

I upgraded my installed Logging chart and set PSPs to enabled, and I do now see the `global.cattle.psp.enabled` field in both views of the chart's yaml. I was unaware either of the views required something to be changed to appear, I was under the impression it would just always show if it was in the yaml to begin with.

**Comment by nickwsuse** [comment]
`Verified on v2.7.2-rc8`

>The 6 charts (from https://github.com/rancher/rancher/issues/8053) are:
Logging
Alerting Drivers
Istio
Monitoring
Rancher Backup
OPA Gatekeeper

All six of these charts and their CRDs are looking good and global fields are matching.
