### ISSUE TITLE
Selection for PSA is cleared after changing the RKE2/K3S cluster version  

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#8068]
**Setup**
- Rancher version: v2.7-head  with  Dashboard version  master fe58a9075
- Browser type & version: Chrome Version 109.0.5414.119 (Official Build) (arm64)

**Describe the bug**

If we edit the RKE2/K3S cluster to upgrade the cluster version, the previous selection for the default PSA is cleared. 

**To Reproduce**

- create an RKE2 custom cluster 
- select cluster version "v1.24.10+rke2r1" 
- select the default PSA "privileged"
- save
- edit the cluster. Now switch the cluster version to 1.25 

**Result**
the previous selection of the default PSA is cleared

**Expected Result**

the previous selection of the default PSA should be preserved. 

**Screenshots**

Edit  the cluster:
<img width="1085" alt="Screenshot 2023-01-30 at 3 15 27 PM" src="https://user-images.githubusercontent.com/6218999/215609710-fedc5077-81a6-46c2-a4ab-a52f1bb16fa3.png">

Now change the version:

<img width="1086" alt="Screenshot 2023-01-30 at 3 15 37 PM" src="https://user-images.githubusercontent.com/6218999/215609753-cb4ceb67-78b0-47f9-8904-cc5bc496a43c.png">

**Comment by cnotv** [comment]
I thought this was changed with the PR but seems like not
https://github.com/rancher/dashboard/pull/8012

**Comment by cnotv** [comment]
K3S version should not reset PSA due https://github.com/rancher/dashboard/issues/8061

**Comment by slickwarren** [comment]
tested on v2.7-head (https://github.com/rancher/dashboard/issues/8274):
* upgrade an rke2/k3s cluster with existing PSA -- pass (PSA Persists after changing the k8s version)
