### ISSUE TITLE
Monitoring V2: Custom UI for Grafana Datasource

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#807]
Need a custom UI for Grafana Datasource (ConfigMaps) for Monitoring V2.

Design requirements listed in parent ticket: https://github.com/rancher/dashboard/issues/803

**Comment by catherineluse** [comment]
Here is the relevant information from the linked ticket:


### Grafana Datasource

A ConfigMap or Secret with a particular label `grafana_datasource` that adds a Grafana datasource.

_Type Help Text: Secrets should be used to store Grafana Datasources to avoid leaking sensitive information that configures access to the datasource._

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Type | `kind` | Radio button for `ConfigMap` or `Secret` | `Secret`
Labels | `metadata.labels.<key>` | `key`: `value` inputs | `grafana_datasource`: `1`

Per Datasource:

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Filename | `data.<name>` | String (needs to be acceptable as k8s key, so no spaces) | `datasource.yaml`
Datasource | Value at `data.<name>` | YAML | nil

There should be a `+` button under the Datasources that allows users to submit multiple `name`:`datasource.yaml` pairs. There should also be a `Remove` button on each Datasource to allow them to be removed.

On create/edit, user should be notified via banner that they need to restart their Grafana deployment to see changes (based on the [Grafana docs](https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-datasources)).
