### ISSUE TITLE
Rancher Dashboard UI does not have continuous delivery option (fleet)

### ISSUE THREAD

**Issue by 2432234085** [rancher/dashboard#8075]

**Comment by 2432234085** [comment]
<img width="2850" alt="image" src="https://user-images.githubusercontent.com/87967906/215984791-430c9ca4-a51b-458a-8b94-871f931e7765.png">

**Comment by richard-cox** [comment]
@2432234085 Please can you update the description with answers to the github issue template. There's not enough information here for us to investigate

**Comment by 2432234085** [comment]
我在 kubectl 1.24.1 上使用helm安装Rancher 2.7.1。

我能够登录到仪表板，但菜单中有持续交付。如何使用fleetas gitops将资源部署到Rancher管理的K8S集群？

**Comment by 2432234085** [comment]
我在 kubectl 1.24.1 上使用 helm 安装 Rancher 2.7.1。

我能够登录到仪表板，但菜单中有持续支付。如何使用 fleetas gitops 将资源部配置到 Rancher 管理的 K8S 集群？

**Comment by 2432234085** [comment]
I installed Rancher 2.7.1 using helm on kubectl 1.24.1.

I am able to log in to the dashboard but there are ongoing payments in the menu. How to use fleetas gitops to configure the resource department to the K8S cluster managed by Rancher?

**Comment by 2432234085** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/87967906/216014511-5eb916af-1c14-4c80-aad1-85f0f4419ca4.png">

**Comment by richard-cox** [comment]
Fleet resources are installed in the `local` cluster. Once they're successfully up and running the fleet menu it `Continuous Delivery` will appear in the side bar menu. It's worth double checking those

![image](https://user-images.githubusercontent.com/18697775/216018940-0430362a-eb92-4d43-960e-93790be8d1b5.png)
