### ISSUE TITLE
Monitoring V2: UI for ServiceMonitor CRs

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#809]
Design requirements listed in parent ticket: https://github.com/rancher/dashboard/issues/803

### ServiceMonitor

Generates the scrape configuration of a Prometheus instance based on labeled Services.

_Namespace Selectors Help Text: Allows you to restrict namespaces of Service resources that can be monitored. By default, the ServiceMonitor monitors all namespaces._

_Label Selectors Help Text: Allows you to identify Services to monitor by the labels on each Service. By default, no Services are monitored._

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Namespace Selector | `spec.namespaceSelector` |  See `NamespaceSelector` | nil
Labels Selector | `spec.selector` | See `LabelSelector` | {}
Endpoints | `spec.endpoints` | YAML | Empty
Job Label | `spec.jobLabel` | String | nil
Target Labels | `spec.targetLabels` | List of Strings | nil
Pod Target Labels | `spec.podTargetLabels` | List of Strings | nil
Maximum Samples Per Scrape | `spec.sampleLimit` | uint64 | nil

If possible, we should provide links to all Services which match the Labels Selector within all Namespaces that match the Namespace Selector here.

**Comment by lvuch** [comment]
https://xd.adobe.com/view/866862d9-4ac5-4962-a026-0c716a335cb7-d33b/

**Comment by lvuch** [comment]
Page one service monitor: https://xd.adobe.com/view/06a7ba45-e0eb-4550-89ea-ef43322622cf-53f4/
