### ISSUE TITLE
`Add Container` button in Workload views is missing

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8090]
**Setup**
- Rancher version: 2.7-head

**Describe the bug**
- (most) workload create/edit pages should have the option to add additional containers
- the button to do so is normally in the header tabs
- this button is not visible

**To Reproduce**
- Workloads --> `Create` --> `Deployment`
- ![image](https://user-images.githubusercontent.com/18697775/216619546-ebe9ce70-8292-404b-96f5-5c705fb9e8ab.png)

**Expected Result**
- `Add Container` button should be on right on currently selected container tab

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7-7913e283ff90eebd1f8cc48860a6b410d72cd4dd-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/7913e283ff90eebd1f8cc48860a6b410d72cd4dd |
| Installation option              | Helm (high availability)                                                           |
| RKE binary version used          | v1.4.0                                                                             |
| If Helm Chart k8s cluster        | v1.24.6                                                                            |
| Cert Details                     | Let's Encrypt / `nginx`                                                            |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin, standard user                                                               |
| Browser type                     | Google Chrome                                                                      |
| Browser version                  | 111.0.5563.110                                                                     |

## Validation steps

1. Create a Rancher 2.7-head
2. Workloads --> Create --> Deployment
3. Verify add container button is present and functions
4. Check all workload types:
   - CronJobs
   - DaemonSets
   - Deployments
   - Jobs
   - StatefulSets


## Additional Info

## RESULTS

#### ✅ Expected

Add container button to be available and working

#### ✅ Actual

ADd container button is available and working


## 📋 QA Test Plan

<table>
    <tbody>
        <tr>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>Check light mode in addition to dark</td>
            <td>
                <ol>
                    <li>Follow validation steps in light mode</li>
                </ol>
            </td>
            <td>Expected: Fix to also be present in light mode</td>
            <td>Actual: Fix was present in light mode as well<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>

**Comment by richard-cox** [comment]
@brudnak This was probably a bug created mid-release which never existed in 2.7.1 or 2.7.2
