### ISSUE TITLE
After selecting a row pressing any key will take the user to the details view

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8094]
**Setup**
- Rancher version: 2.7-head

**Describe the bug**
- With a single row selected, pressing any key will take the user to the detail view of the selected row

**To Reproduce**
- --> Deployments list
- select any deployment
- press the `ctrl` key

**Result**
- user is take to the detail page

**Expected Result**
- use should remain on the deployment list page
- ResourceTable shortcuts should still work (see `v-shortcut` usage ~ https://github.com/rancher/dashboard/blob/master/shell/components/ResourceTable.vue#L483)

**Additional context**
- This was broken via https://github.com/rancher/dashboard/pull/7848
- ResourceTable has a set of `v-shortkey` shortcuts that should be honoured. I'm guessing from the issue that broke the feature we should not bubble up ResourceTable shortcuts

**Comment by torchiaf** [comment]
The regression was actually introduced in #7848 . We needed a custom listener because the `v-shortkey` shortcut was capturing the Enter key when the namespace filter is open:

https://github.com/rancher/dashboard/blob/faa6f7abb405590cb0c8fa76c5a5b6a2a7393415/shell/components/ResourceTable.vue#L154-L159

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 211409c
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 110

----------

### Testing: ###
Tested this issue with the following steps:
1. --> Deployments list
2. select any deployment
3. press the ctrl key

**Result**
Pressing the `ctrl` key no longer takes user to detail page.
I noticed the following keys trigger actions:
- `e` takes user to the edit config page
- `y` takes user to the yaml page
- `n` triggers the namespace search
![image.png](https://zube.io/files/rancher/80cabbdf4311c18b89151a00d2a4ccfa-image.png)
- `/` triggers the filter search
![image.png](https://zube.io/files/rancher/352f9177459f554e492d21e932d2b124-image.png)
- `backspace` and `del` triggers a deletion to the deployment with an `Are you sure?` dialog prompt
![image.png](https://zube.io/files/rancher/ac0bc502fab0ae4783e4684ba586d922-image.png)

From the existing list of key shortcuts, I saw that `/` isn't on there, @torchiaf if that's ok I will close the ticket.
![image.png](https://zube.io/files/rancher/b2a4a4ef270079bdd8f907aed01fe090-image.png)

**Comment by torchiaf** [comment]
Thanks for your support Tim. The key to open the details page should be only `Enter`. The `/` key still works and it is defined in `SortableTable/index.vue`:

https://github.com/rancher/dashboard/blob/3405d6d10743c268c7605e5964064f7965f45436/shell/components/SortableTable/index.vue#L1398-L1402
