### ISSUE TITLE
api-ui project needs updating

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8097]
Update to refresh the dependencies on:

https://github.com/rancher/api-ui/blob/master/package.json

**Comment by richard-cox** [comment]
This should cover both the `/1` and `/v3` endpoints (pretty sure they're the same but we should be sure

Should also confirm that any changes merged to the the repo result in a build and changes make it in to Rancher

**Comment by gaktive** [comment]
New version created but we await @macedogm to update the backend to use this new version before passing to QA.

**Comment by gaktive** [comment]
I suspect this is done now. @rak-phillip can you confirm?

**Comment by macedogm** [comment]
This is being done in the following PRs:

- https://github.com/rancher/norman/pull/431
- https://github.com/rancher/norman/pull/432
- https://github.com/rancher/apiserver/pull/25

**Comment by rak-phillip** [comment]
All referenced PRs are merged, closing this issue.

@gaktive @macedogm
