### ISSUE TITLE
Monitoring V2: UI for PodMonitor CRs

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#810]
### PodMonitor

Generates the scrape configuration of a Prometheus instance based on labeled Pods.

_Namespace Selectors Help Text: Allows you to restrict namespaces of Pod resources that can be monitored. By default, the PodMonitor monitors all namespaces._

_Label Selectors Help Text: Allows you to identify Pods to monitor by the labels on each Pod. By default, no Pods are monitored._

Header / Label Name | k8s YAML | Input | Default
---|---|---|---|
Namespace Selector | `spec.namespaceSelector` |  See `NamespaceSelector` | nil
Labels Selector | `spec.selector` | See `LabelSelector` | {}
Endpoints | `spec.podMetricsEndpoints` | YAML | Empty
Job Label | `spec.jobLabel` | String | nil
Pod Target Labels | `spec.podTargetLabels` | List of Strings | nil
Maximum Samples Per Scrape | `spec.sampleLimit` | uint64 | nil

If possible, we should provide links to all Pods which match the Labels Selector within all Namespaces that match the Namespace Selector here.

**Comment by lvuch** [comment]
https://xd.adobe.com/view/866862d9-4ac5-4962-a026-0c716a335cb7-d33b/

**Comment by lvuch** [comment]
Page 2: https://xd.adobe.com/view/06a7ba45-e0eb-4550-89ea-ef43322622cf-53f4/
