### ISSUE TITLE
Standard User incorrectly shown as admin in v3 api

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8100]
Internal reference: SURE-5677
Reported in 2.6.x (and earlier)

Issue description:
When a standard user logs in Rancher and switches to `https://rancher_url/v3`, the API shows as if the user was logged as admin.

Good news: the standard user isn't actually an admin so it's not a security vector; the permissions are set properly so we're showing the wrong user name.

Troubleshooting steps:
Deploy several versions of Rancher: 2.4.x, 2.5.x, 2.6.x and check that the standard user is showed as "admin". 

Repro steps:

- Deploy Rancher 2.5.14, 2.6.8, 2.6.9
- Create a standard user and log in. Switch from Rancher dashboard to Rancher api v3 url: `https://my_rancher_url/dashboard` ===> `https://my_rancher_url/v3`
- On the right hand side, the option to Logout lists _admin_ as the active user

Repo: https://github.com/rancher/api-ui

Backend did a preliminary investigation and it looks to be from here: 

- https://github.com/rancher/api-ui/blob/e78af2f97b009cee10de84de45ce3c6dc3793e57/src/init.js#L51
- https://github.com/rancher/api-ui/blob/e78af2f97b009cee10de84de45ce3c6dc3793e57/templates/explorer.hbs#L13

**Comment by nwmac** [comment]
We should remove the username from the API UI - its not correct and getting the correct value requires a lot of change and does not add much value.

Remove the username and just have the 'Log out' link.

Currently looks like this:
![image](https://user-images.githubusercontent.com/1955897/219120250-f65586a3-15ae-4992-833f-430618174155.png)

Note: This is the API UI that you see when you choose 'View in API' for a resource

**Comment by gaktive** [comment]
Engineering to add an automated test in #8831 to help QA.

**Comment by nwmac** [comment]
This is done - waiting on backend to merge PRs to have Rancher pick up the latest version

**Comment by nwmac** [comment]
Will need manual testing of the View in API function for a resource

**Comment by nwmac** [comment]
To test:

Enable 'View in API' in user preferences

Go to any resource - e.g. Secret and choose 'View in API' - check that the username 'admin' is no longer shown in the top-right

**Comment by anupama2501** [comment]
Reproduced on v2.7.3

1. As an admin created a standard user
2. Verified from the <rancherURL>/v3 API, admin is shown as user.

Verified on v2.7-head `f0d4078`
1. Created a standard user
2. Create a cluster and add the user as CO
3. Logged in as standard user
4. From preferences >> Enabled "View in API"
5. From workloads click on view API and verified the API does not show user name
6. Verified from <rancherURL>/v1 api and <rancherURL>/v3 API, no user name is displayed.
