### ISSUE TITLE
*.js take forever (~1 minute) to load on rke-drivers page (in the cluster management dashboard)

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#8107]
**Setup**
- Rancher version: v2.7-head (3c1e7db)
- Browser type & version: Chrome

**Describe the bug**

<img width="653" alt="Screen Shot 2023-02-07 at 9 16 37 AM" src="https://user-images.githubusercontent.com/16691014/217316655-c8ec3801-cf33-4a10-aeef-8ca7cc49e6cb.png">

(not sure if this is affecting anything but wanted to mention it)
getting a 404 on the `management` -> `drivers` page (rke1-drivers) index.json `v1/namespaces/cattle-ui-plugin-system/services/http:ui-plugin-operator:80/proxy/index.json` takes forever to timeout then load the page. 

**To Reproduce**

* go to `cluster management` -> `drivers`
* wait for the page to load

**Result**
page takes over 1 minute to load

**Expected Result**

page should load just as quickly as all the others

**Additional Notes**
I'm thinking this could be some underlying issue in the setup, so posting what I'm running on here:
* local cluster is rke2 v1.24.9+rke2r1, 3 nodes, and hardened, running on ubuntu 22.04

**Comment by richard-cox** [comment]
I couldn't reproduce this in my ancient 2.7-head (`7d16a0d`), 

It looks like the problem is fetching two resources from `rke-drivers` (15 and 42 seconds). I couldn't see those locally or what that source might be.

@slickwarren What cluster and node drivers do you have enabled, and can you enable `Use large requests rows` in that network tab to reveal the full path of those long http requests?

**Comment by slickwarren** [comment]
This was on a clean install, so the default drivers are all that are enabled with no downstream clusters.  If I hard reload rancher on any cluster management page, I reproduce this on the same JS requests. 

<img width="1364" alt="Screen Shot 2023-02-07 at 9 58 45 AM" src="https://user-images.githubusercontent.com/16691014/217327854-fd8d3561-52a1-47e2-9975-58910bbb5469.png">

**Comment by richard-cox** [comment]
The 404 on `ui-plugin-operator:80/proxy/index.json` is fine.

It looks like those are generic dashboard assets. Found those now locally, however mine from the same local download pretty quickly.

![image](https://user-images.githubusercontent.com/18697775/217329250-0aea8a6a-f12a-4412-8ce1-c980885e7116.png)

This is probably a network issue between your browser and `release.rancher.com`

**Comment by slickwarren** [comment]
oof, sorry for the false alarm. You are right, I am connected to the company network, which apparently is now significantly slower than last I checked for using rancher. I will close this issue, as accessing rancher without being connected to the company network does load in an acceptable time.
