### ISSUE TITLE
Monitoring V2: Display graphs in cluster overview dashboard

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#812]
The Monitoring V2 UI should continue to support cluster-scoped metric graphs from Monitoring V1 on the Cluster Overview dashboard. 

In Monitoring V1, these are currently stored in ClusterMonitorGraph CRs ([monitoring](https://github.com/rancher/rancher/blob/9cd377ae5c12e30578f9dfe6bc9b00bc7c6eabfd/pkg/controllers/user/monitoring/metricExpression.go#L104-L1050), [istio-specific](https://github.com/rancher/rancher/blob/83ceb904a50c6ff979adf80ee879e9085ed9bf0d/pkg/controllers/user/istio/metricExpression.go#L304-L553)), which pulls its data based on the related MonitorMetric CRs (also defined in the same files linked above) selected by the ClusterMonitorGraph.

In Monitoring V2, we should not need to store these metrics in CRs as project-monitoring is not in scope (i.e. no need for RBAC in choosing to display the dashboards). Instead, the necessary PromQL queries and information on how the graphs should be rendered should be stored directly on Dashboard.

Note: When we update this, we should also ensure that we avoid the bug in https://github.com/rancher/rancher/issues/26902.

**Comment by maggieliu** [comment]
- [ ] Lauren to do initial mockup on graphs

- [ ] Cody to investigate into pulling monitoring data and drawing graphs on the dashboard

**Comment by maggieliu** [comment]
- [ ] @cloudnautique to provide a list of graphs we want to keep from Ember

**Comment by maggieliu** [comment]
https://xd.adobe.com/view/866862d9-4ac5-4962-a026-0c716a335cb7-d33b/

**Comment by aiyengar2** [comment]
@codyrancher once Grafana stuff is in for Windows in https://github.com/rancher/rancher/issues/31742, we also will need to embed Windows dashboards into the UI as part of this task.

Will sync with you offline once the above issue is completed.

**Comment by aiyengar2** [comment]
### Note for QA

Since these dashboards will be persisted in the Monitoring chart itself in https://github.com/rancher/rancher/issues/31921, part of testing this change should also test what happens if a user is still on Monitoring 9.4.204 on Rancher 2.5.8 and tries to access the Cluster Overview dashboards on Rancher.

**Comment by sowmyav27** [comment]
While testing, should validate on 
- windows clusters
- Linux cluster

**Comment by gaktive** [comment]
https://github.com/rancher/rancher/issues/31990 requires some level of fix provided here so whoever reviews this, let's make sure we don't leave backend blocked.

**Comment by aiyengar2** [comment]
> [rancher/rancher#31990](https://github.com/rancher/rancher/issues/31990) requires some level of fix provided here so whoever reviews this, let's make sure we don't leave backend blocked.

@gaktive the fix for this is a backend fix being tracked in https://github.com/rancher/charts/pull/1103

**Comment by codyrancher** [comment]
Notes for QA:
1. If https://github.com/rancher/rancher/issues/31921#issuecomment-819141759 isn't taken care of you'll need to manually enable the `allow_embedding` grafana configuration.
2. Network metrics will only have data for RKE/RKE2 clusters.
3. Etcd metrics will only be shown for RKE/RKE2 clusters.
4. Due to https://github.com/rancher/rancher/issues/31891 I wasn't able to verify non-local clusters on my local setup. I'm going to do that now and will remove this item when this works out. This affects items 2 and 3.

**Comment by slickwarren** [comment]
blocked, waiting for  https://github.com/rancher/rancher/issues/31921 to land

**Comment by codyrancher** [comment]
@slickwarren I don't actually think this is blocked. In this change you're essentially verifying that grafana dashboards are correctly being embedded in our dashboard page. You can see the graphs, modify the range and refresh rate.

rancher/rancher#31921 will just change the graphs which is independent of this change. The only thing it might affect is the dashboard id will need to change on the front end.

It's okay if you want to wait but I figured I'd bring it up in case you wanted to start on this.

**Comment by slickwarren** [comment]
I'm getting some errors on a downstream linux clusters. using latest monitoring v14.5.100-rc7 on v2.5.8-rc4. I will try on 2.5-head before moving this to reopened
<img width="1538" alt="Screen Shot 2021-04-15 at 9 10 53 AM" src="https://user-images.githubusercontent.com/16691014/114902330-92655080-9dca-11eb-81c0-eecb10d86555.png">
<img width="1516" alt="Screen Shot 2021-04-15 at 9 10 28 AM" src="https://user-images.githubusercontent.com/16691014/114902352-96916e00-9dca-11eb-83c3-aacac701c00d.png">

```
Refused to display 'https://<ip>/' in a frame because it set 'X-Frame-Options' to 'deny'.

Uncaught DOMException: Blocked a frame with origin "https://<ip>" from accessing a cross-origin frame.
    at f.graphDocument (https://<ip>/dashboard/_nuxt/pages/c/_cluster/explorer/index.01212a067f3c4a4f5c91.js:1:14151)
    at _n.get (https://<ip>/dashboard/_nuxt/commons/app.ae9b7db0a4971962a42f.js:2:185825)
    at _n.evaluate (https://<ip>/dashboard/_nuxt/commons/app.ae9b7db0a4971962a42f.js:2:186975)
    at f.graphDocument (https://<ip>/dashboard/_nuxt/commons/app.ae9b7db0a4971962a42f.js:2:188914)
    at f.injectCss (https://<ip>/dashboard/_nuxt/pages/c/_cluster/explorer/index.01212a067f3c4a4f5c91.js:1:16625)
    at f.inject (https://<ip>/dashboard/_nuxt/pages/c/_cluster/explorer/index.01212a067f3c4a4f5c91.js:1:16687)
```

**Comment by slickwarren** [comment]
the above was due to `If rancher/rancher#31921 (comment) isn't taken care of you'll need to manually enable the allow_embedding grafana configuration.`, using https://github.com/rancher/rancher/issues/32101 allows user to manually set this. moved back `to test`

**Comment by codyrancher** [comment]
@slickwarren found an issue where we weren't rendering etcd metrics for windows so I'm going to create a pr to resolve it.
