### ISSUE TITLE
Alert users when upgrading imported RKE2 cluster from k8s <1.25 to >=1.25

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#8124]
**Is your feature request related to a problem? Please describe.**
If the imported RKE2 cluster is hardened (e.g. has `cis-1.6` profile enabled, but can also just have cluster-level PSP applied), it may need to be prepared manually before it can be upgraded through Rancher.
Additionally, PSPs will be removed automatically as k8s 1.25+ no longer supports PSPs.

**Describe the solution you'd like**
On the "Edit Cluster" screen for an imported RKE2 cluster, when k8s version is changed from <1.25 to >=1.25, present the user with the confirmation message along the lines of `Kubernetes has removed support for Pod Security Policies (PSPs) starting with version 1.25. Please follow the instructions at (URL) to manually prepare the cluster for the upgrade before you proceed with saving the changes to the cluster. Proceed?` with the options "Yes" and "No".

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gaktive** [comment]
@snasovich the UI can't upgrade imported clusters based on the existing workflow. What's the actual scenario here for upgrading once imported?

**Comment by gaktive** [comment]
@snasovich never mind :)

**Comment by mantis-toboggan-md** [comment]
This is the same UI as imported k3s clusters, an iframed ember page, so I'll do this at the same time  (k3s issue: https://github.com/rancher/dashboard/issues/8126)

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, import an RKE2 v1.24 cluster into Rancher v2.7-head, attempt to upgrade to v1.25 and validate that a warning is shown, validate the upgrade is successful|
|2|As a standard user, import a K3s v1.24 cluster into Rancher v2.7-head, attempt to upgrade to v1.25 and validate that a warning is shown, validate the upgrade is successful|
|3|As a standard user, import a K3s v1.24 cluster into Rancher v2.7-head, attempt to upgrade to v1.25 and validate that a warning specific to PSPs is shown, validate the upgrade is successful|
|4|As a standard user, import an RKE2 v1.23 cluster into Rancher v2.7.1, upgrade Rancher v2.7.1 -> v2.7-head, attempt to upgrade to v1.25 and validate that a warning is shown, validate that the upgrade is successful|
|5|As a standard user, import a K3s v1.23 cluster into Rancher v2.7.1, upgrade Rancher v2.7.1 -> v2.7-head, attempt to upgrade to v1.25 and validate that a warning is shown, validate that the upgrade is successful|
|6|As a standard user, import a K3s v1.23 cluster into Rancher v2.7.1, upgrade Rancher v2.7.1 -> v2.7-head, attempt to upgrade to v1.25 and validate that a warning specific to PSPs  is shown, validate that the upgrade is successful|

**Comment by markusewalker** [comment]
Validated that this has been addressed. See details below:

**ENVIRONMENT DETAILS**
- Rancher install
     - Fresh install: Helm
     - Upgrade: Docker
- Rancher version
     - Fresh install: `v2.7-head` https://github.com/rancher/rancher/commit/6cca23fd75c3ccc447a6013c7a0a3482656515d6
     - Upgrade: `v2.7.1` -> `v2.7-head` https://github.com/rancher/rancher/commit/6cca23fd75c3ccc447a6013c7a0a3482656515d6
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, import an RKE2 v1.24 cluster into Rancher v2.7-head, attempt to upgrade to v1.25 and validate that a warning is shown, validate the upgrade is successful|:white_check_mark:|
|2|As a standard user, import a K3s v1.24 cluster into Rancher v2.7-head, attempt to upgrade to v1.25 and validate that a warning is shown, validate the upgrade is successful|:white_check_mark:|
|3|As a standard user, provision a K3s v1.24 hardened custom cluster into Rancher v2.7-head, attempt to upgrade to v1.25 and validate that a warning specific to PSPs is shown, validate the upgrade is successful|:white_check_mark:|
|4|As a standard user, import an RKE2 v1.24 cluster into Rancher v2.7.1, upgrade Rancher v2.7.1 -> v2.7-head, attempt to upgrade to v1.25 and validate that a warning is shown, validate that the upgrade is successful|:white_check_mark:|
|5|As a standard user, import a K3s v1.24 cluster into Rancher v2.7.1, upgrade Rancher v2.7.1 -> v2.7-head, attempt to upgrade to v1.25 and validate that a warning is shown, validate that the upgrade is successful|:white_check_mark:|
|6|As a standard user, provision a K3s v1.24 hardened custom cluster into Rancher v2.7.1, upgrade Rancher v2.7.1 -> v2.7-head, attempt to upgrade to v1.25 and validate that a warning specific to PSPs is shown, validate that the upgrade is successful|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. In a separate client machine, setup a 3 node RKE2 v1.24 cluster.
2. Navigated over to Rancher > Cluster Management > Import Existing.
3. Imported my RKE2 cluster; validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
4. Validated that all pods in the system project page are up and `Active`.
5. Edited the configuration of the cluster and updated K8s v1.24 -> v1.25.
6. When I attempted to upgrade, I noted the following warning message:
![image](https://user-images.githubusercontent.com/52591819/223242456-2324c1c6-7d56-4ca9-9b38-fffcfb453257.png) 
7. Proceeded to upgrade; validated that upgrade was successful and the cluster and nodes came up as `Active` with their upgraded versions in Cluster Management and Cluster Explorer.
8. Validated that all pods in the system project page are up and `Active`.
______
**Scenario 2**
1. Repeated scenario 1, except I created a 3 node K3s v1.24 cluster with no PSPs set.
_______
**Scenario 3**
1. As a standard user, navigated to Cluster Management > Create.
2. Provisioned a downstream v1.24 K3s custom cluster.
3. Registered to 1 etcd, 1 cp, 1 worker; validated that the cluster and nodes came up as `Active` in Cluster Explorer and Cluster Management.
4. Validated that the pods in the system project page are up and `Active`.
5. Performed hardening on the cluster and nodes to ensure PSPs are enabled on the cluster.
6. Edited the cluster configuration and updated K8s version to `v1.24` -> `v1.25`.
7. Attempted to upgraded and noted the following warning message:
![image](https://user-images.githubusercontent.com/52591819/223242321-a442fdbc-6ce4-4405-abf3-bf5278f1f8e8.png) 
8. Upgraded the cluster; validated I am seeing an expected error message:
![image](https://user-images.githubusercontent.com/52591819/223242268-da73b014-a73e-4ac7-bb77-94a912c9821e.png)
9. Repeated steps 2-5 to get a new custom cluster.
10. Manually removed the `kube-apiserver-arg.enable-admission-plugins` as per the warning message.
11. Upgraded the cluster; validated that the cluster and nodes successfully upgraded and are in a state of `Active`.
12. Validated that the pods in the system project page are up and `Active`.
_______
**Scenario 4**
1. In a separate client machine, setup a 3 node RKE2 v1.24 cluster.
2. Navigated over to Rancher `v2.7.1` > Cluster Management > Import Existing.
3. Imported my RKE2 cluster; validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
4. Validated that all pods in the system project page are up and `Active`.
5. Upgraded Rancher `v2.7.1` -> `v2.7-head`; validated that the cluster and nodes did not auto-upgrade their K8s version.
6. Edited the configuration of the cluster and updated K8s v1.24 -> v1.25.
7. When I attempted to upgrade, I noted the following warning message:
![image](https://user-images.githubusercontent.com/52591819/223242139-e86ec042-d3bd-45b8-ba8f-0e49b5d070e7.png)
8. Proceeded to upgrade; validated that upgrade was successful and the cluster and nodes came up as `Active` with their upgraded versions in Cluster Management and Cluster Explorer.
9. Validated that all pods in the system project page are up and `Active`.
________
**Scenario 5**
1. Repeated scenario 4, except I created a 3 node K3s v1.24 cluster with no PSPs set.
________
**Scenario 6**
1. Repeated scenario 1 steps 1-7, but provisioned a v1.24 K3s custom cluster on Rancher `v2.7.1`.
2. Upgraded Rancher `v2.7.1` -> `v2.7-head`; validated that the cluster and nodes did not auto-upgrade their K8s version.
3. Edited the cluster configuration and updated K8s version to `v1.24` -> `v1.25`.
4. Attempted to upgraded and noted the following warning message:
![image](https://user-images.githubusercontent.com/52591819/223241959-5a5d78fd-a4a8-4579-8e6c-b0da01e2fdcd.png) 
5. Manually removed the `kube-apiserver-arg.enable-admission-plugins` as per the warning message.
6. Upgraded the cluster; validated that the cluster and nodes successfully upgraded and are in a state of `Active`.
7. Validated that the pods in the system project page are up and `Active`.
