### ISSUE TITLE
Alert users when upgrading provisioned k3s cluster from k8s <1.25 to >=1.25 if PSP enabled

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#8125]
**Is your feature request related to a problem? Please describe.**
If the provisioned cluster has PodSecurityPolicy (PSP) admission controller enabled, it needs to be removed before proceeding with the upgrade.
Additionally, PSPs will be removed automatically as k8s 1.25+ no longer supports PSPs.

**Describe the solution you'd like**
On the "Edit Cluster" screen for a provisioned k8s cluster, when k8s version is changed from <1.25 to >=1.25, present the user with the confirmation message along the lines of `Kubernetes has removed support for Pod Security Policies (PSPs) starting with version 1.25. If your cluster has PodSecurityPolicy admission controller enabled via "kube-apiserver-arg.enable-admission-plugins" in Cluster YAML, it has to be MANUALLY removed before proceeding with the upgrade. Additionally, any PSPs that may be present in the cluster will no longer be available/enforced. Proceed?` with the options "Yes" and "No".

**Describe alternatives you've considered**
Ideally, we want to only show this warning if PSP admission controller is indeed enabled. If time permits only shows the following warning if Cluster YAML's `kube-apiserver-arg.enable-admission-plugins` contains `PodSecurityPolicy` value, e.g. `kube-apiserver-arg: enable-admission-plugins=NodeRestriction,PodSecurityPolicy,NamespaceLifecycle,ServiceAccount`: `Kubernetes has removed support for Pod Security Policies (PSPs) starting with version 1.25. Your cluster has PodSecurityPolicy admission controller enabled via "kube-apiserver-arg.enable-admission-plugins" in Cluster YAML, it has to be MANUALLY removed before proceeding with the upgrade. Additionally, any PSPs that may be present in the cluster will no longer be available/enforced. Proceed?` with the options "Yes" and "No".

**Additional context**
N/A

**Comment by cnotv** [comment]
As the logic already contains a modal in this process, we'll rather update the existing logic and text.

![Screenshot 2023-02-15 at 17 58 59](https://user-images.githubusercontent.com/5009481/219103289-6052e606-0133-4485-852f-d69433c5397e.png)

**Comment by cnotv** [comment]
Please note that PSP must be enabled in order to display the dialog.
As reference to how retrieve the information, please refer to the comment: https://github.com/rancher/dashboard/issues/7553#issuecomment-1430202568

**Comment by cnotv** [comment]
@snasovich 
Where is supposed to be found the value `kube-apiserver-arg.enable-admission-plugins`?
How can I create a K3S cluster with PSP enabled?
Why is the check different from https://github.com/rancher/dashboard/issues/7553#issuecomment-1430202568?

**Comment by cnotv** [comment]
@jiaqiluo Do you have eventually further information about `kube-apiserver-arg.enable-admission-plugins`?

**Comment by cnotv** [comment]
Identified some clashes with modal styles in another issue https://github.com/rancher/dashboard/issues/8207

**Comment by jiaqiluo** [comment]
Hi @cnotv , let me try to answer your questions, and please let me know if it makes to you. 

 
The way to enable PSP for the K3S cluster in rancher UI is to set the extra args for the `kube-apiserver` (see the screenshot below), and as a result, the field `.spec.rkeConfig.machineGlobalConfig.kube-apiserver-arg` will reflect the values ( see screenshot below).

For UI to check if PSP is enabled, UI needs to read the value of the above-mentioned field from the cluster's YAML file and check if the word `PodSecurityPolicy` exists. 


<img width="1644" alt="Screenshot 2023-02-21 at 11 29 29 AM" src="https://user-images.githubusercontent.com/6218999/220429976-920171fe-869d-4a68-b8c1-d041afb08e7b.png">

<img width="873" alt="Screenshot 2023-02-21 at 11 30 17 AM" src="https://user-images.githubusercontent.com/6218999/220429980-77e9ba7c-ca9f-4070-a52e-8db6b08c7fb6.png">

**Comment by cnotv** [comment]
For the sake of copy-pasting, this is the line to be added: `enable-admission-plugins=NodeRestriction,PodSecurityPolicy`

**Comment by markusewalker** [comment]
This [test plan](https://github.com/rancher/dashboard/issues/8124#issuecomment-1456840360) covers this issue as the fixes implemented are similar. As such, once that issue has been validated, I will leave a comment here and close this issue.

**Comment by markusewalker** [comment]
This has been validated as part of the test results [here](https://github.com/rancher/dashboard/issues/8124#issuecomment-1457054935). Closing issue.
