### ISSUE TITLE
Alert users when upgrading imported k3s cluster from k8s <1.25 to >=1.25

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#8126]
**Is your feature request related to a problem? Please describe.**
If the imported RKE2 cluster is hardened (e.g. per https://rancher.com/docs/k3s/latest/en/security/hardening_guide/, but can also just have cluster-level PSP applied), it may need to be prepared manually before it can be upgraded through Rancher.
Additionally, PSPs will be removed automatically as k8s 1.25+ no longer supports PSPs.

**Describe the solution you'd like**
On the "Edit Cluster" screen for an imported k3s cluster, when k8s version is changed from <1.25 to >=1.25, present the user with the confirmation message along the lines of `Kubernetes has removed support for Pod Security Policies (PSPs) starting with version 1.25. If you proceed with the upgrade, any PSPs that may be present in the cluster will no longer be available/enforced. If this is a hardened k3s cluster (or PodSecurityPolicy admission controller is enabled), please follow the instructions at (URL) before you proceed with saving the changes to the cluster. Proceed?` with the options "Yes" and "No".

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by markusewalker** [comment]
This [test plan](https://github.com/rancher/dashboard/issues/8124#issuecomment-1456840360) will cover this issue as the fix is the same for RKE2 and K3s. Once that issue has been validated, I will leave a comment in this issue notifying and close this issue.

**Comment by markusewalker** [comment]
This has been validated as part of the test results [here](https://github.com/rancher/dashboard/issues/8124#issuecomment-1457054935). Closing issue.
