### ISSUE TITLE
The harvester plugin affects the display of the global settings page

### ISSUE THREAD

**Issue by WuJun2016** [rancher/dashboard#8129]
**Setup**
- Rancher version:  rancher 2.7.0
- Browser type & version: 
- harvester version:  https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js

**Describe the bug**

After accessing the harvester cluster in rancher, going to the global setting page will cause the page to crash.

**To Reproduce**

1. Import the latest harvester version in rancher 2.7.0
2. go to harvester from the Virtualization Management page
3. Go back to rancher's global settings page

**Result**
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/24985926/217809916-9835163a-b107-4690-9e89-f1227aef3db4.png">

**Expected Result**

The global settings page should display properly

**Screenshots**

https://user-images.githubusercontent.com/24985926/217812472-7fcfa13c-ff58-4da6-b328-22f5d9f1a6ad.mov

**Additional context**

**Comment by DaiYuzeng** [comment]
Fixed by https://github.com/rancher/dashboard/pull/7904/ @WuJun2016
