### ISSUE TITLE
Multi-cluster Apps not shown in UI

### ISSUE THREAD

**Issue by 2432234085** [rancher/dashboard#8139]
Kubernetes 1.24.1
Rancher 2.7.1

I followed the documentation to have Legacy turned on and kept active，But in the upper left corner ☰ did not find the Multi-cluster Apps option
<img width="516" alt="image" src="https://user-images.githubusercontent.com/87967906/218026355-8dafc8f1-72c2-46a0-a6a3-3d73d607d2e4.png">
<img width="290" alt="image" src="https://user-images.githubusercontent.com/87967906/218026859-c4898360-2f03-41f1-9609-bd4eaa1a972e.png">

**Comment by richard-cox** [comment]
multi-cluster-apps have been deprecated and removed https://github.com/rancher/dashboard/pull/6971

https://github.com/rancher/rancher/releases/tag/v2.5.0 `Deprecated Features`
https://github.com/rancher/rancher/releases/tag/v2.7.0 `Removed Legacy Features`
