### ISSUE TITLE
Rancher dashboard vs rancher ui projects

### ISSUE THREAD

**Issue by wanderernxa** [rancher/dashboard#8142]
Hi,
What is the difference between the Rancher Dashboard and the Rancher UI projects?

thanks in advance

**Comment by richard-cox** [comment]
[Dashboard](https://github.com/rancher/dashboard) is the main UI for the core Rancher product. [UI](https://github.com/rancher/ui) is the legacy UI for the core Rancher product and is no longer supported.

If you have any more related questions feel free to ask them here and re-open the issue
