### ISSUE TITLE
Move "Read from file" button to be part of masthead

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#815]
read from file to be moved to masthead
<img width="1176" alt="Screen Shot 2020-07-07 at 11 13 56 AM" src="https://user-images.githubusercontent.com/3013118/86848853-a02fbd80-c063-11ea-80d1-9b84aa7a5d82.png">

**Comment by vincent99** [comment]
I already moved the read from file (in a future PR) as part of something else...

**Comment by deniseschannon** [comment]
Updated as of master 6/13

![Screen Shot 2020-07-13 at 4.49.32 PM.png](https://zube.io/files/rancher/50f506e76219f278d5efd2086975f1cf-screen-shot-2020-07-13-at-4-49-32-pm.png)
