### ISSUE TITLE
Can an Extensions channel be created in Rancher Users slack?

### ISSUE THREAD

**Issue by krumware** [rancher/dashboard#8150]
I'm looking for a place to ask questions or make comments without polluting the github. Can a community slack channel be opened for conversation related to extensions?

**Comment by richard-cox** [comment]
Thanks @krumware , good suggestion. We'll look in to this

**Comment by richard-cox** [comment]
Sorry for the delay. I finally managed to get one created, but it looks like someone else got there before me and didn't update the UI team. 

Looks like you've already stumbled on it. I've added a link to our docs there a well https://rancher.github.io/dashboard/plugins/introduction

For others that find this issue, please join us over at rancher-users.slack.com `#extensions`
