### ISSUE TITLE
Updates to Detail Page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#817]
https://xd.adobe.com/view/6c169dfb-df8f-4dfb-8723-6e5217d3d91e-3945/

**Comment by deniseschannon** [comment]
In DetailTop, there are 2 columns of data. 

Column 1: 
Custom pieces of info to be shown based on resource type

All keys should be stored in a map that maps the key to a weight so that the keys can be assorted based on priority. As we add in custom keys for different pages, they would need to be evaluated on where they fit on the table. 

Column 2:
Description - Currently description lies in masthead and needs to be moved into DetailTop
Labels - These should be badge style, but limit the max width when/if the label is too long with ability to hover over the label to see the full label. 
Annotations - By default, these will be hidden and exposed only if you click on the link. These should only show the list of whitelisted annotations. 

If there is nothing declard in column 1, column 2 should be left justified with the content.

**Comment by sowmyav27** [comment]
**Validated on master-head - commit id: `16616de9c`**

- Logged in as Standard user
- Labels and annotations seen as expected
<img width="988" alt="Screen Shot 2020-07-17 at 3 38 02 PM" src="https://user-images.githubusercontent.com/26032343/87836179-17273c00-c844-11ea-849e-c88f7d289074.png">

<img width="706" alt="Screen Shot 2020-07-17 at 3 37 20 PM" src="https://user-images.githubusercontent.com/26032343/87836190-1b535980-c844-11ea-8dc1-64b0a18597d2.png">

- However on clicking on `Show Annotation` the user is navigated to the explore cluster page. Logged issue -- https://github.com/rancher/dashboard/issues/866
- Data section is NOT as seen here - https://github.com/rancher/dashboard/issues/817#issue-653641850
<img width="988" alt="Screen Shot 2020-07-17 at 3 38 02 PM" src="https://user-images.githubusercontent.com/26032343/87836421-d976e300-c844-11ea-83c8-abe2cdd98af9.png">

- Labels section is seen Left justified
<img width="704" alt="Screen Shot 2020-07-17 at 3 37 08 PM" src="https://user-images.githubusercontent.com/26032343/87836467-05926400-c845-11ea-993e-184461612932.png">

**Comment by codyrancher** [comment]
@deniseschannon I wanted to check on two items.
1. Do yo u want @sowmyav27 to verify the order of column 1? If so do you just want to verify against the old detail top?
2. Quite a few of the annotations appear to have JSON content. Did you want to do anything to make it look nicer?
![Screen Shot 2020-07-28 at 5 59 49 PM](https://user-images.githubusercontent.com/55104481/88744652-d5787a00-d0fc-11ea-9c4c-05a97a143a0a.png)

**Comment by deniseschannon** [comment]
1. I don't need her to verify it. If you send me a list, I can review it. 
2. Nicer is always better, but given the table format, not sure the best solution either.

**Comment by deniseschannon** [comment]
In the current KeyValue component, there is some logic to attempt to format json if it's valid json, so let's try to re-use that logic.

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `d19f179c4`**

### Works fine:
- Create a registry, enter a description (from the amber UI). The registry on the dashboard shows description
<img width="1454" alt="Screen Shot 2020-08-18 at 6 10 52 PM" src="https://user-images.githubusercontent.com/26032343/90580686-549e2280-e17e-11ea-9db6-bfd2a1808d20.png">

- Annotations are seen as key value
<img width="1084" alt="Screen Shot 2020-08-18 at 6 09 37 PM" src="https://user-images.githubusercontent.com/26032343/90580733-6c75a680-e17e-11ea-8a91-36924372f185.png">

### Issues
- Data section is NOT as seen here - https://github.com/rancher/dashboard/issues/817#issue-653641850
<img width="1450" alt="Screen Shot 2020-08-18 at 6 02 04 PM" src="https://user-images.githubusercontent.com/26032343/90580458-c1fd8380-e17d-11ea-85ff-324425f2d5c0.png">

Reopening the issue

**Comment by codyrancher** [comment]
@sowmyav27 this change doesn't address changes to specific pages. This only addresses the top section that's common to all pages. 

The Data section issue you noticed is specific to the secret page.

**Comment by sowmyav27** [comment]
Logged a new issue for the data section of secret. - https://github.com/rancher/dashboard/issues/1057
Closing this issue.
