### ISSUE TITLE
Azure RKE2 provisioning page location dropdown is broken

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#8173]
The location dropdown is empty and mis-styled:
![Screen Shot 2023-02-14 at 9.32.26 AM.png](https://zube.io/files/rancher/65f869c3391def3a7df8d63dd005b3d0-screen-shot-2023-02-14-at-9-32-26-am.png)

The error in the browser console is `TypeError: Cannot read properties of undefined (reading 'name')
    at LabeledSelect.vue:155:1`
A non-default location must be selected to set an availability zone so this will block testing the RKE2 portion of https://github.com/rancher/dashboard/issues/8014

**Comment by mantis-toboggan-md** [comment]
This probably related to this recent LabeledSelect update https://github.com/rancher/dashboard/pull/8154

**Comment by Josh-Diamond** [comment]
Ticket #8173 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on Rancher `v2.7-d559c2f16d5a634d8e5188e242ee9a5b69c55908-head`:
1. Fresh install of Rancher `v2.7-head`
2. Create a downstream RKE2 Azure node driver cluster
3. Verified - Azure RKE2 provisioning page accurately formatted; location dropdown populated and functional

Screenshots:

`Azure RKE2 provisioning page`
<img width="1434" alt="Screenshot 2023-02-27 at 4 46 15 PM" src="https://user-images.githubusercontent.com/46494969/221715542-abd5d5e5-898b-4346-a671-e467220abfc9.png">

`Location dropdown`
<img width="482" alt="Screenshot 2023-02-27 at 4 50 02 PM" src="https://user-images.githubusercontent.com/46494969/221715552-e23002fc-c772-4637-8c39-856713263958.png">
