### ISSUE TITLE
Improve PSP/PSA Banners when deploying / upgrading an RKE1 cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#8174]
**Setup**
- Rancher version: v2.7-head (as of 2/14/23)
- Browser type & version: any 

**Describe the bug**

Currently there is only a generic banner in the `advanced options` section, that does not change based on the current k8s version, nor if PSP is enabled/disabled. (please provide feedback/comment for this)
<img width="812" alt="Screen Shot 2023-02-07 at 11 18 42 AM" src="https://user-images.githubusercontent.com/16691014/217343872-8468be48-049e-4de7-a54c-8eb364c418b5.png">
[See this ticket](https://github.com/rancher/dashboard/issues/7791) and [this PR](https://github.com/rancher/dashboard/pull/8012) which applied for RKE2 for more information on how the dynamic banner should work. 

**To Reproduce**
deploy an rke1 1.24 cluster with PSPs enabled
upgrade to 1.25
deploy a fresh 1.25

**Result**
the PSP banner is generic, no matter the k8s version selected

**Expected Result**

We should have a dynamic message just as we do for RKE2

**Additional context**

[See this ticket](https://github.com/rancher/dashboard/issues/7791) and [this PR](https://github.com/rancher/dashboard/pull/8012) which applied for RKE2 for more information on how the dynamic banner should work.

**Comment by mantis-toboggan-md** [comment]
@slickwarren You're seeing these additional warnings on upgrade, right? Just to clarify, what you're asking for here is different phrasing in the info banner depending on the kubernetes version? The idea that there's no distinction when PSPs are enabled seems completely redundant to me when there's a big red banner 50px away from that
![Screen Shot 2023-02-14 at 11 35 16 AM](https://user-images.githubusercontent.com/42977925/218827017-9952c046-e3a6-4912-be13-9ccc6a4ff2bc.png)

**Comment by slickwarren** [comment]
@mantis-toboggan-md , I might have been on an older version but did not notice those banners the first time I tested. 

I just tested it out and do see the 1st red banner appear on an upgrade / when PSP is enabled and 1.25 is selected as the version. 

It would be nice to have the rke1 and rke2 messages match exactly. The difference I see now is, nothing happens when the user has 1.25 selected unless they have already enabled PSPs. But in rke2, the 'blue' banner switches to notify them to use PSAs instead. i.e. ![https://user-images.githubusercontent.com/1955897/214273150-3daa0f2d-1303-4946-a217-59dac5517228.png](https://user-images.githubusercontent.com/1955897/214273150-3daa0f2d-1303-4946-a217-59dac5517228.png)

I also think it would be helpful to move the blue banner down to the PSP/PSA section, on top of the red banners if there are any (but beneath the nginx ingress section).

**Comment by mantis-toboggan-md** [comment]
> I just tested it out and do see the 1st red banner appear on an upgrade / when PSP is enabled and 1.25 is selected as the version.

Okay, good! I thought there might be an issue with those prompting this ticket. I see what you mean about the phrasing though, I'll update it to match the rke2 banners, and place it closer to the PSP/PSA area of the form. Thanks for clarifying @slickwarren

**Comment by slickwarren** [comment]
I like the new banners better on v2.7-head  (https://github.com/rancher/rancher/commit/cca09e4768af17067ca3a848a6b3e5ed44e99aa1)

<img width="742" alt="Screen Shot 2023-02-28 at 11 13 00 AM" src="https://user-images.githubusercontent.com/16691014/221957132-e41038f2-05f1-43c8-ba10-fd1ea3112b4f.png">
<img width="826" alt="Screen Shot 2023-02-28 at 11 12 08 AM" src="https://user-images.githubusercontent.com/16691014/221957138-a8709c2a-fc8b-40f5-bcb1-de033b9da434.png">
