### ISSUE TITLE
Failed to compile: These dependencies were not found

### ISSUE THREAD

**Issue by chaplin0** [rancher/dashboard#8177]
**Setup**
- Rancher version: v2.7
- windows 10
- node 14.15.4

**Describe the bug**
These dependencies were not found:
* ..\shell\middleware\shell\middleware\authenticated.js in ./.nuxt/middleware.js                                                                                                          friendly-errors 
* ..\shell\middleware\shell\middleware\i18n.js in ./.nuxt/middleware.js                                                                                                                   friendly-errors 
* ..\shell\middleware\shell\middleware\unauthenticated.js in ./.nuxt/middleware.js                                                                                                        friendly-errors 
* ..\shell\store\shell\store\action-menu.js in ./.nuxt/store.js                                                                                                                           friendly-errors 
* ..\shell\store\shell\store\auth.js in ./.nuxt/store.js                                                                                                                                  friendly-errors 
* ..\shell\store\shell\store\aws.js in ./.nuxt/store.js                                                                                                                                   friendly-errors 
* ..\shell\store\shell\store\catalog.js in ./.nuxt/store.js                                                                                                                               friendly-errors 
* ..\shell\store\shell\store\digitalocean.js in ./.nuxt/store.js                                                                                                                          friendly-errors 
* ..\shell\store\shell\store\features.js in ./.nuxt/store.js                                                                                                                              friendly-errors 
* ..\shell\store\shell\store\github.js in ./.nuxt/store.js                                                                                                                                friendly-errors 
* ..\shell\store\shell\store\growl.js in ./.nuxt/store.js                                                                                                                                 friendly-errors 
* ..\shell\store\shell\store\i18n.js in ./.nuxt/store.js                                                                                                                                  friendly-errors 
* ..\shell\store\shell\store\index.js in ./.nuxt/store.js                                                                                                                                 friendly-errors 
* ..\shell\store\shell\store\linode.js in ./.nuxt/store.js                                                                                                                                friendly-errors 
* ..\shell\store\shell\store\plugins.js in ./.nuxt/store.js                                                                                                                               friendly-errors 
* ..\shell\store\shell\store\prefs.js in ./.nuxt/store.js                                                                                                                                 friendly-errors 
* ..\shell\store\shell\store\resource-fetch.js in ./.nuxt/store.js                                                                                                                        friendly-errors 
* ..\shell\store\shell\store\type-map.js in ./.nuxt/store.js                                                                                                                              friendly-errors 
* ..\shell\store\shell\store\uiplugins.ts in ./.nuxt/store.js                                                                                                                             friendly-errors 
* ..\shell\store\shell\store\wm.js in ./.nuxt/store.js 

**To Reproduce**

Run yarn install
Run yarn dev

**Comment by richard-cox** [comment]
Thanks for raising this issue @chaplin0 , unfortunately development in Windows is not supported (only Linux and Mac). This used to be noted in our documentation but has been lost. I've created https://github.com/rancher/dashboard/issues/8178 to add it back in
