### ISSUE TITLE
Issue with `check-plugins-build` ->  `Validate Plugin Build System` github action

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#8179]
**Describe the bug**
The script on github action `check-plugins-build` ->  `Validate Plugin Build System` catches a problem with an import of a path of an extension to shell/dashboard code, but the validation does not fail, since the step is validated.
An example here: https://github.com/rancher/dashboard/actions/runs/4137433409/jobs/7152595631

**To Reproduce**
go to a page/component on the `/shell` folder and do an import of a method from an extension, example:
`import { something } from '@/pkg/harvester-manager/config/harvester-manager'`

Create a PR from those changes and check the github action `check-plugins-build` ->  `Validate Plugin Build System`

**Result**
validation does not fail

**Expected Result**
validation should fail so that the code won't enter shell/dashboard

**Comment by sowmyav27** [comment]
@nwmac @aalves08 Can you confirm if QA validations are needed and if yes, please add info in QA Test Template ?

**Comment by aalves08** [comment]
@sowmyav27 no validations from QA needed here. Going to add the appropriate labels and close this issue 🙏
