### ISSUE TITLE
Update 2.6.11 with missing 2.6.x commits

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8183]
In `rancher/ui`, these commits needs to get in:

- 4ea810eed68fcf053ddb8da3fc39322f5baefc2a
HARVESTER: Disable Harvester cloud provider option when the credential is external
PR: https://github.com/rancher/ui/pull/4881

- 52e0c850c800bc3115071520f9955cf029656259
Update default image for gke nodes
PR: https://github.com/rancher/ui/pull/4891

Let's check that they're in `master` and then the 2.6 branch. For reference, these went into 2.6.9-rc1 but not 2.6.9-rc2. This is similar to what happened with https://github.com/rancher/ui/pull/4890

**Comment by rak-phillip** [comment]
We will need a new release candidate for 2.6.11 before we start testing.

**Comment by slickwarren** [comment]
tested on rancher v2.6.11-rc8:
* deploy a new gke cluster 
  * default image is now `optimized for containerd` -- pass
* deploy rancher v2.6.8
  * create an external cloud credential for harvester
  * upgrade rancher to v2.6.11-rc8
  * ensure that the node driver for harvester is disabled after the upgrade -- pass
