### ISSUE TITLE
customise page in extension cause rancher dashboard update?

### ISSUE THREAD

**Issue by liyimeng** [rancher/dashboard#8195]
In my extension, I customise a page with putting pod.vue in the list directory, when I navigate aways from my extensions to rancher default dashboard, I found the page there is also updated. 

Is this by purpose? In my understanding, the pod listing page only update when I am in my extensions, when I navigate back rancher dashboard, it should load back the original one.   Am I right?

**Comment by richard-cox** [comment]
Can you provide more information on the location of your pod component in your extension?

**Comment by richard-cox** [comment]
No update, closing
