### ISSUE TITLE
Multi-cluster application status display error

### ISSUE THREAD

**Issue by 2432234085** [rancher/dashboard#8204]
**Setup**
- Rancher version: 2.6.10
- kubernetes version: 1.24.1

**Describe the bug**
After the update application is executed in a multi-cluster application, the application status always shows installing, but the application is normal

<img width="1596" alt="image" src="https://user-images.githubusercontent.com/87967906/219995368-3de4e4cb-04e7-4de7-adfc-d73eaa304135.png">

**Comment by richard-cox** [comment]
multi-cluster-apps have been deprecated and have been removed https://github.com/rancher/dashboard/pull/6971

https://github.com/rancher/rancher/releases/tag/v2.5.0 `Deprecated Features`
https://github.com/rancher/rancher/releases/tag/v2.7.0 `Removed Legacy Features`
