### ISSUE TITLE
Namespace cannot inherit the Resource Limit default value from the project

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#8205]
**Setup**
- Rancher version: v2.7.1
- Browser type & version: 110.0.5481.100

**Describe the bug**

When the namespace was created, the value of the default resource limit set in the project was not inherited into the namespace

**To Reproduce**

1. Create a project and set the default value of `Container Default Resource Limit`
2. Create a namespace in this project, check the default value of `Container Resource Limit`

**Result**
`Container Resource Limit` does not inherit from the default value of the project, all are empty
**Expected Result**

Inherit default values from project
![namespace](https://user-images.githubusercontent.com/19684717/220046519-f15a0351-1ce9-4cea-92c7-aa4704f063dc.gif)

**Comment by gaktive** [comment]
Engineering to write an automated test to help QA in #8786
