### ISSUE TITLE
Consolidate create buttons into dropdown type button (masthead)

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#821]
Current:
<img width="349" alt="Screen Shot 2020-07-10 at 11 20 18 AM" src="https://user-images.githubusercontent.com/3013118/87185916-6cd97280-c29f-11ea-97d2-e7b7533bb89d.png">

Desired:
<img width="436" alt="Screen Shot 2020-07-10 at 11 18 52 AM" src="https://user-images.githubusercontent.com/3013118/87185921-706cf980-c29f-11ea-977d-09e3a1950296.png">

**Comment by vincent99** [comment]
Clicking left of the divider should go straight to [form] create, right of it bring up the menu.  Also should be able to tab-focus both pieces separately.

**Comment by izaac** [comment]
Are we moving forward for the first create in the dropdown to include the full resource name?

Ingress Example:

![Screen Shot 2020-07-28 at 11 56 18 AM](https://user-images.githubusercontent.com/27659/88709070-764d4200-d0c9-11ea-8070-d14695d33211.png)

https://github.com/rancher/dashboard/pull/862#issue-451380078 design was showing the short name.

**Comment by deniseschannon** [comment]
@westlywright I think we should strip to shortname to match the resource name.

**Comment by westlywright** [comment]
@deniseschannon @izaac There may have been a bug here at one point but I don't think it exists anymore. The [code](https://github.com/rancher/dashboard/blob/master/store/type-map.js#L271) that populates this variable first checks if a translation exists, if not, we'll use the kind attribute, then id, and finally '?'. I no longer see the full type, I see the short name.

![Screen Shot 2020-08-13 at 1 41 53 PM](https://user-images.githubusercontent.com/858614/90185060-f5e63c80-dd6a-11ea-995f-2c0311432533.png)

**Comment by vincent99** [comment]
I fixed the name displayed to not be the raw type a [couple days ago](https://github.com/rancher/dashboard/commit/a73f35f2ba6b04351ffd969ed2863a1cf55444d3)

**Comment by izaac** [comment]
Rancher version `master-head (08/13/2020)` _d19f179c4_

Validated that the create button is displaying the short name for each resource now that has `Edit as Form` support.
