### ISSUE TITLE
Create Namespaces Button not visible when using "Flat List" view

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8216]
Internal Reference: SURE-5787

Some work was done here: https://github.com/rancher/dashboard/issues/5120

.. but as an admin, in the flat view on Projects/Namespaces, there is no button to create a namespace.

If you go to the grouped view, you can add a namespace in the 'Not in a Project' section.

You should be able to create a namespace in the flat view.

**Comment by nwmac** [comment]
@bisht-richa If you're working on this - can you move this to working, please?

**Comment by gaktive** [comment]
Engineering to create automation for this to help with testing in #8784
