### ISSUE TITLE
Ability to truncate RKE2 hostnames to 15 characters or less

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8223]
Internal reference: SURE-5923, SURE-5811

Request description:
Offer users the ability to truncate existing hostname logic to 15 characters during provisioning

Actual behaviour:
Unix style name generation is too large for the 15-character limit of NetBIOS. This prevents machines from provisioning correctly

Changing existing logic for all cluster naming for all users is too disruptive; it should be an option that is available at cluster creation

Expected behaviour:
Customers can create netbios-compliant clusters for domain joining

Workaround:
None

Changing naming conventions which is not acceptable or sustainable

Target platforms:
Provisioned RKE2, Windows RKE2 & k3s clusters

Additional notes:
This will affect all Windows setups eventually and really reduces our ability to deliver Windows Kubernetes as a solution

There is already a standard pattern for truncation in Azure CAPI for this purpose which we could emulate:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machine.go#L429

_*What needs to be done*_

- Add a checkbox at the cluster-level 'Truncate hostnames to 15 characters for NetBIOS compatibility'
- Checkbox can ONLY be set on create - it should be disabled on edit
- Note: Although we set a boolean, this is stored as an integer on the cluster object - true should be set to 15, false should remove the field
- On edit, ONLY if the value is 15, should we show the checkbox as checked
- On edit, if the value is present but NOT 15, we should show an info banner beneath the checkbox saying "Hostname truncation has been manually configured for this cluster to N" (where N is the value specified)
- Truncation can be set per machine pool. We do NOT allow this to be edited in the UI, but as a bonus, we do want to show per-machine pool if the value is set (to any value) - we should show a similar banner: "Hostname truncation has been manually configured for this pool to N" (where N is the value specified for the pool)

**Comment by nwmac** [comment]
The required UI change is to add a checkbox as per the UX design. The value will be sent to the UI in the  cluster create/edit API call.

**Comment by gaktive** [comment]
UI done their part. Putting as Backend Blocked until backend is ready; once I know there's a ticket, I can link back.

**Comment by gaktive** [comment]
Waiting on https://github.com/rancher/rancher/issues/40901

**Comment by gaktive** [comment]
Backend complete as their PRs have merged.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 1eb478f
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 112

----------

### Testing: ###
Tested the following cases:
1. Add a checkbox at the cluster-level 'Truncate hostnames to 15 characters for NetBIOS compatibility'
2. Checkbox can ONLY be set on create - it should be disabled on edit
3. On edit, ONLY if the value is 15, should we show the checkbox as checked
4. On edit, if the value is present but NOT 15, we should show an info banner beneath the checkbox saying "Hostname truncation has been manually configured for this cluster to N" (where N is the value specified)
5. Truncation can be set per machine pool. We do NOT allow this to be edited in the UI, but as a bonus, we do want to show per-machine pool if the value is set (to any value) - we should show a similar banner: "Hostname truncation has been manually configured for this pool to N" (where N is the value specified for the pool)

Results:
1. Add a checkbox at the cluster-level 'Truncate hostnames to 15 characters for NetBIOS compatibility'
![image.png](https://zube.io/files/rancher/4f4ae24648572125475304a4502c2e6f-image.png)
2. Checkbox can ONLY be set on create - it should be disabled on edit
![image.png](https://zube.io/files/rancher/f2c0145b4b35c36c21201511a2649c41-image.png)
3. On edit, ONLY if the value is 15, should we show the checkbox as checked
![image.png](https://zube.io/files/rancher/f2c0145b4b35c36c21201511a2649c41-image.png)
4. On edit, if the value is present but NOT 15, we should show an info banner beneath the checkbox saying "Hostname truncation has been manually configured for this cluster to N" (where N is the value specified)
![image.png](https://zube.io/files/rancher/9314ac2100a17a406768d248b7f06324-image.png)
5. Truncation can be set per machine pool. We do NOT allow this to be edited in the UI, but as a bonus, we do want to show per-machine pool if the value is set (to any value) - we should show a similar banner: "Hostname truncation has been manually configured for this pool to N" (where N is the value specified for the pool)
![image.png](https://zube.io/files/rancher/27a6b7c7f5d6fb89dfb9d1fe823e09ad-image.png)
Edit config page for truncated machine pool
![image.png](https://zube.io/files/rancher/583902238be0bff23368c877c2b632bb-image.png)
Edit config page for not truncated machine pool
![image.png](https://zube.io/files/rancher/1f161198f432ac249730e35a04c2975a-image.png)
