### ISSUE TITLE
Rename Pod Security Policies to Pod Security Policy Templates in Cluster Mgmt -> Advanced

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8225]
From @genexpr, under Cluster Management and Advanced, we should use *Pod Security Policy Templates* instead of _Pod Security Policies_

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, validate that in Cluster Management, `Pod Security Policies` is renamed to `Pod Security Policy Templates`|

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/6cca23fd75c3ccc447a6013c7a0a3482656515d6. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version :`v2.7-head` https://github.com/rancher/rancher/commit/6cca23fd75c3ccc447a6013c7a0a3482656515d6
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, validate that in Cluster Management, `Pod Security Policies` is renamed to `Pod Security Policy Templates`|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, navigated to Cluster Management > Advanced.
2. Validated that `Pod Security Policy Templates` is visible:
![image](https://user-images.githubusercontent.com/52591819/223209872-1a929f5a-b72d-434f-9083-deff442207da.png)
