### ISSUE TITLE
UI doesn't update RKE1 provisioned cluster status after making changes to it

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#8237]
**Setup**
- Rancher version: v2.6-head (v2.6-6c8f89d1f3c11a30b69f5d7d520df153adb0581f-head)
- Browser type & version: Chrome 110.0.5481.100 on MacOS 12.0.1

**Describe the bug**
Cluster statuses on "Cluster Management" are often not updated automatically and a browser refresh is required.

**To Reproduce**
1. Navigate to "Cluster Management"
2. Locate previously provisioned RKE1 cluster and "Edit Config" to make any change that kicks off cluster update
3. Hit "Save"

**Result**
Very often, cluster will continue to be showing "Active" status while it's in fact "Updating" - which can be confirmed by either refreshing the page or duplicating the tab to confirm two tabs are then showing different statuses.

**Expected Result**
Cluster status and any other data shown on "Cluster Management" page should be updated automatically without having to refresh the browser.

**Additional context**
It was observed that making change to RKE2 provisioned cluster "unstucks" status updating for RKE1 cluster.

See the recording below to demonstrate this.

https://user-images.githubusercontent.com/85187633/220728007-54561985-42d3-4145-a499-feecaeadedcc.mov

Another recording shows the initial update to RKE1 cluster changing its status to Updating on the tab where the change was performed, but not on another duplicate tab. However, once a change to RKE2 cluster is done on the same first tab, the status immediately updates for BOTH RKE1 and RKE2 clusters on the duplicate tab.

https://user-images.githubusercontent.com/85187633/220728786-4db0cfd2-2ae2-4dbd-9d84-ee613c9e5708.mov

**Comment by mantis-toboggan-md** [comment]
I've looked into this a little. I'm able to reproduce similar behavior on my own 2.6-head and 2.7-head setups: after editing an rke1 cluster in a way that should cause it to go into an 'updating' state, the cluster state shown in the cluster manager list doesn't update unless I either refresh the page or edit another cluster. 

This needs further investigation but I think this is indeed a dashboard issue and not a steve websocket problem. rke1 clusters in that list use the associated management cluster's `metadata.state` for the State column: I've watched the /v1 websocket while reproducing this bug and I see that the UI IS getting resource.change events for the management cluster, but the table isn't updated accordingly. I'm not sure what's going on there - maybe an issue with the live reload mechanism?

**Comment by richard-cox** [comment]
Forward port ticket: #8250

**Comment by anupama2501** [comment]
Verified following scenarios and upon the editing the config - noticed the status on the cluster is changed to `updating` without having ti refresh the UI on v2.6-head `9b65d8b`
1. As an admin, created 3 clusters - rke1, rke2 and k3s node drivers with 1 etcd+cp pool and 1 worker pool on k8s 1.23
2. Upgrade the k8s on each of the cluster to k8s 1.24 and notice the state is changed to `updating`
3. Created 2 standard users and add them as cluster owner and cluster member in all 3 downstream clusters.
4. Edit the config and changed the value of ACE to disabled and the status is reflected for all 3 users.
