### ISSUE TITLE
Blank page shown when attempt to install a Helm Chart

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8241]
**Setup**
- Rancher version: v2.7.0

**Describe the bug**
- Some RKE2 clusters do not contain an rkeConfig machineSelectorConfig, i'm not sure what scenario creates this
- User goes to Cluster Explorer for the cluster --> Apps --> Charts --> <select any chart> --> Install
- A blank page is shown 
  

**To Reproduce**
- Create an RKE2 cluster that does not contain the rkeConfig machineSelectorConfig
  - With 2.7.2 RKE2 cluster it's there
- Cluster Explorer for the cluster --> Apps --> Charts --> <select a rancher chart> --> Install

**Result**
![image](https://user-images.githubusercontent.com/18697775/220876169-684f7fe4-c7c8-4717-8b9d-c6b70b559077.png)

![image](https://user-images.githubusercontent.com/18697775/220877790-1e4d9a67-dd41-49d1-9084-d2713061e41d.png)

**Expected Result**
Install wizard is shown

**Additional context**
The outcome is similar to https://github.com/rancher/dashboard/pull/7952 where a fix was applied to avoid an error in that function. For this issue it's a different location in that function that throws the error.

Both this and the other issue were new in 2.7.0

**Comment by AndrewHoffmanQA** [comment]
retest passed
tested on 2.7.2 rc4
testing- 
tested on the following RKEs:
v1.23.16+rke2r1
v1.24.10+rke2r1
v1.25.6+rke2r1

stood up a RKE2 downstream clusters
validated the ability to install longhorn and UI operator to the downstream clusters.
