### ISSUE TITLE
CIS Profile default value on Custom Clusters is inconsistent and states "(None)" instead of "Default - RKE2 Embedded"

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#8247]
**Setup**
- Rancher version: `v2.7-head` (Commit ID: 7c60dc0)
- Browser type & version: Brave: Version 1.48.167 (Chromium: 110.0.5481.104)

**Describe the bug**
When provisioning an RKE2 Custom Cluster, the default value for the _CIS Profile_ field is "(None)" while other fields like this state "Default - RKE2 Embedded" 

**To Reproduce**
1. Spin up a Rancher cluster
2. Begin the process for provisioning an RKE2 Custom Cluster

**Result**
The default value for the _CIS Profile_ field is "(None)"

**Expected Result**
The default value for the _CIS Profile_ field should be consistent with other similar fields and instead state "Default - RKE2 Embedded"

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/220992373-b3e33585-cb74-40a9-bae5-209a370f0d3a.png)

**Comment by gaktive** [comment]
@jameson-mcghee this is working as expected at this stage. Until a CIS profile is selected, we have to show `(None)` with the parentheses to help differentiate between the options. Does the drop down show `1.23` as the only option?

**Comment by jameson-mcghee** [comment]
> @jameson-mcghee this is working as expected at this stage. Until a CIS profile is selected, we have to show `(None)` with the parentheses to help differentiate between the options. Does the drop down show `1.23` as the only option?

It is my understanding that we recently changed the label on the default value for fields like (for example) _Cloud Provider_ to state "Default - RKE2 Embedded" instead of "(None)". On `v2.6-head` (Commit ID: ddecd1b), this remains as "(None)" for the _Cloud Provider_ field (see screenshots below).
So are you saying that on `v2.7-head` that  _Cloud Provider_ of value "Default - RKE2 Embedded" is actually setting a Cloud Provider value, or is it None? If it is None, then why would we not want that label to be consistent with all fields that are operating the same way (such as CIS Profile)? Having inconsistency in the labels is confusing to me, so I would imagine it would be for users as well.

In answer to your question "_Does the drop down show `1.23` as the only option?_", when using K8s version `v1.25`, the only CIS Profile that is available is `cis-1.23`m but when using older K8s versions (i.e. `v1.23` or `v1.24`), you have the options `cis-1.5` or `cis-1.6`.

![image](https://user-images.githubusercontent.com/13294321/221288091-338b35a2-3287-4459-a031-51f233327a26.png)
![image](https://user-images.githubusercontent.com/13294321/221288102-20a19220-0a6a-4d64-bd80-2324fb1256c0.png)

**Comment by jameson-mcghee** [comment]
It was determined that this field it is acceptable for it to state "_None_" explicitly. Therefore I am closing this ticket as Won't Fix.
