### ISSUE TITLE
The default value for the Default Pod Security Admission field changes to "(None)" on older K8s versions

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#8248]
**Setup**
- Rancher version: `v2.7-head` (Commit ID: 7c60dc0)
- Browser type & version: Brave: Version 1.48.167 (Chromium: 110.0.5481.104)

**Describe the bug**
When provisioning an RKE2 or K3s downstream cluster, the default value for the _Default Pod Security Admission_ field changes to "(None)" if the K8s version is set to `v1.24` or older

**To Reproduce**
1. Spin up a Rancher cluster
2. Begin the process for provisioning an RKE2 cluster
3. Change the _Kubernetes Version_ to `v1.24.1+rke2r1`

**Result**
The default value for the _Default Pod Security Admission_ field changes to "(None)"

**Expected Result**
The default value for the _Default Pod Security Admission_ field should remain as the correct default value (i.e. "Default - RKE2 Embedded")

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/220995150-01d20a56-0f40-40fe-b6e3-a52a433bbf77.png)
![image](https://user-images.githubusercontent.com/13294321/220995215-d95c17bb-6155-432a-a178-29ada63154b1.png)

This issue is related to [8247](https://github.com/rancher/dashboard/issues/8247)

**Comment by gaktive** [comment]
@jameson-mcghee this is working as expected. Kubernetes 1.24 did not have a default PSA based on that version so we won't apply that. 1.24 would have a default PSP instead.

**Comment by jameson-mcghee** [comment]
> 

Like I mentioned on [8247](https://github.com/rancher/dashboard/issues/8247), it is my understanding that we recently changed the label on the default value for fields like (for example) _Cloud Provider_ to state "Default - RKE2 Embedded" instead of "(None)". On `v2.6-head` (Commit ID: ddecd1b), this remains as "(None)" for the _Cloud Provider_ field (see screenshots below).
So are you saying that on `v2.7-head` that  _Cloud Provider_ of value "Default - RKE2 Embedded" is actually setting a Cloud Provider value, or is it None? If it means None, then is that not confusing in relation to this field? When on K8s `v1.25`, is the default value for PSA, actually setting a PSA? Having inconsistency in the labels is confusing to me, so I would imagine it would be for users as well.

![image](https://user-images.githubusercontent.com/13294321/221290006-32a2088c-c5f2-4723-a4e6-3a27dc5dac0b.png)
![image](https://user-images.githubusercontent.com/13294321/221290019-25ea4013-9bb5-4be9-bc10-a308979ce4c5.png)

**Comment by snasovich** [comment]
Removed the milestone as there was no fix and this "functions as designed".
