### ISSUE TITLE
Reduce level of console output for missing ui plugin operator

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8253]
On load the dashboard tries to confirm if the ui-plugin-operator is there via a http request. Following this an error is shown in the console `Could not load UI Plugin list`. If the operator returns a 404 then there hasn't really been an error.

The error causes lots of confusion when users report unrelated issues.

Suggestion 
- If the response is a 404 we should only show `Could not load UI Plugin list` at info level
- If the response is any type of other error then show `Could not load UI Plugin list` at the current (error) level

<img width="1266" alt="208577306-84aff560-f4cf-4a7b-a156-8358bbc20fa4" src="https://user-images.githubusercontent.com/18697775/221159998-9ad9ad40-ce69-414c-8783-02e29d24368a.png">

**Comment by richard-cox** [comment]
> I am stumbling into this daily - is there a workaround?

It's a spurious log level and is harmless. The fix here is to change to output at info instead of error. 

To avoid the 404 though you can install the operator, there should be a prompt if you go to three line burger menu (top left) --> Extensions

**Comment by moio** [comment]
Hmm, my problem is that I get the following "pseudo-404" page apparently coming from nuxt no matter the URL I use (even `/` or `/dashboard`) - so Rancher is completely unusable.

![image](https://user-images.githubusercontent.com/250541/224063597-410e2ecf-80c3-4011-aead-e4e632f5e6d5.png)

Error in the Console is exactly matching the one you posted upthread, but, is this actually the same root issue?

**Comment by richard-cox** [comment]
We've branched for 2.7.2 now, but unfortunately the update to rancher `v2.7-head` to point to our 2.7.2 branch was a bit later than expected. What you're seeing now is a broken 2.7-Q2 build.

To fix this go to `<rancher url>/v3/settings/ui-dashboard-index` and change the value from `https://releases.rancher.com/dashboard/latest/index.html` to `https://releases.rancher.com/dashboard/release-2.7.2/index.html`. Then a fresh reload of the rancher ui should work
