### ISSUE TITLE
Node base events break Cluster dashboard and events pages

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8261]
**Setup**
- Rancher version: v2.7-head (2.7.2ish)

**Describe the bug**
- Cluster Events page doesn't handle `node` based events

**To Reproduce**
- Bring up rancher 2.7-head from docker. This should contain some node based events
- Navigate to the cluster dashboard for the local cluster (this has an events list, but cluster / events list also affected)

**Result**
- There should be a white page error caused by
   ```
    console.js:31 TypeError: Cannot read properties of undefined (reading 'split')
      at VueComponent.kind (InvolvedObjectLink.vue:22:1)
   ```

**Expected Result**
- Events list successfully shown
- User can click on the new link in the `Object` column for a node based event

**Screenshots**

**Additional context**
- The link for the `Object` column is broken as well. This could be due to the missing apiVersion... or it doesn't handle non-namespaced resources well?

**Comment by aalves08** [comment]
Same message as the bug I was seeing for the `events` list view 🤔

**Comment by Josh-Diamond** [comment]
Ticket #8261 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-6cca23fd75c3ccc447a6013c7a0a3482656515d6-head`:
1. Fresh install of rancher `v2.7-head`
2. Navigate to `Cluster Explorer > Events` of local cluster
3. Verified - Events page successfully loads and is accurate; links in `object` column accurate and functional
