### ISSUE TITLE
Standard users as `cluster-owner` are unable to add new members to the cluster in 2.6 for AKS, EKS, GKE, and RKE1 clusters

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#8266]
**Setup**
- Rancher version: `v2.6-f76a1c515cd12d0bc01e69e747d0734ae18df793-head`
- Browser type & version: `Chrome`

**Describe the bug**
When `creating` a downstream cluster as a standard user, standard users are unable to add cluster members.

Once provisioned and `active`, standard users are also unable to add cluster members when navigating to `Cluster Management > Edit Config > Cluster Members`

Note/Workaround:
Once cluster is provisioned, standard users ARE able to add cluster members when navigating to `Cluster Explorer > Cluster Members`

**To Reproduce**

Scenario 1:
1. Fresh install of rancher `2.6-head`
2. As admin, create a standard user
3. As standard user, begin to `create` a cluster and navigate to `Cluster Members`
4. Reproduced

Scenario 2:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As standard user, provision a downstream cluster
4. Once `active`, navigate to `Cluster Management > Edit Config > Cluster Members`
5. Reproduced

**Result**
Standard users, as `cluster-owner` are unable to add members to the cluster.  The `+ Add Member` button is disabled

**Expected Result**
Standard users, as `cluster-owner` are able to add members to the cluster.  The `+ Add Member` button is NOT disabled

**Screenshots**

`Scenario 1 - Create Downstream RKE1 Custom`
<img width="963" alt="Screenshot 2023-02-24 at 4 08 38 PM" src="https://user-images.githubusercontent.com/46494969/221318110-b584df79-d7e7-4624-858f-b47d74f81f50.png">

`Scenario 2 - Rancher Provisioned EKS Cluster`
<img width="1390" alt="Screenshot 2023-02-24 at 4 04 07 PM" src="https://user-images.githubusercontent.com/46494969/221317366-b6e1d2a3-32ee-4f33-a8c7-3751a9bb384a.png">

**Additional context**

❗**REGRESSION** ❗- reproducible in `2.6.9`

**Comment by codyrancher** [comment]
This has been happening at least since 2.6.5 and there's a workaround so I don't think this can be a blocker.

**Comment by Josh-Diamond** [comment]
Ticket #8266 - Test Results - _Pending review_
---

With Docker on a single-node instance:

Verified on rancher `v2.6-9b65d8be62df5516407eb1408ac013a76a7fa953-head`:

| Scenario | Test Case | Result |
|---|---|---|
| AKS | | _view a-f below_ |
| a. | As standard user, navigate to `Create > Cluster Members`, and add member standard user as `cluster-owner` | ✅ |
| b. | As standard user, provision downstream cluster, navigate to `Cluster Management > Cluster Members` and add new member standard user as `cluster-owner` | ✅ |
| c. | As standard user `cluster-owner`, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and add member standard user as `cluster-member | ✅ |
| d. | As standard user `cluster-member`, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and ensure you cannot add members | ✅ |
| e. | As admin, navigate to `Cluster Management > Cluster Members`, (on cluster from 1b) and add member | ✅ |
| f. | As admin, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and add member | ✅ |
| g. | As admin, navigate to `Create > Cluster Members`, and add member | ✅ |
| EKS | | _view a-g below_ |
| a. | As standard user, navigate to `Create > Cluster Members`, and add member standard user as `cluster-owner` | ✅ |
| b. | As standard user, provision downstream cluster, navigate to `Cluster Management > Cluster Members` and add new member standard user as `cluster-owner` | ✅ |
| c. | As standard user `cluster-owner`, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and add member standard user as `cluster-member | ✅ |
| d. | As standard user `cluster-member`, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and ensure you cannot add members | ✅ |
| e. | As admin, navigate to `Cluster Management > Cluster Members`, (on cluster from 1b) and add member | ✅ |
| f. | As admin, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and add member | ✅ |
| g. | As admin, navigate to `Create > Cluster Members`, and add member | ✅ |
| GKE |  | _view a-g below_ |
| a. | As standard user, navigate to `Create > Cluster Members`, and add member standard user as `cluster-owner` | ✅ |
| b. | As standard user, provision downstream cluster, navigate to `Cluster Management > Cluster Members` and add new member standard user as `cluster-owner` | ✅ |
| c. | As standard user `cluster-owner`, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and add member standard user as `cluster-member | ✅ |
| d. | As standard user `cluster-member`, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and ensure you cannot add members | ✅ |
| e. | As admin, navigate to `Cluster Management > Cluster Members`, (on cluster from 1b) and add member | ✅ |
| f. | As admin, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and add member | ✅ |
| g. | As admin, navigate to `Create > Cluster Members`, and add member | ✅ |
| RKE1 | | _view a-g below_ |
| a. | As standard user, navigate to `Create > Cluster Members`, and add member standard user as `cluster-owner` | ✅ |
| b. | As standard user, provision downstream cluster, navigate to `Cluster Management > Cluster Members` and add new member standard user as `cluster-owner` | ✅ |
| c. | As standard user `cluster-owner`, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and add member standard user as `cluster-member | ✅ |
| d. | As standard user `cluster-member`, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and ensure you cannot add members | ✅ |
| e. | As admin, navigate to `Cluster Management > Cluster Members`, (on cluster from 1b) and add member | ✅ |
| f. | As admin, navigate to `Cluster Explorer > Cluster Members`, (on cluster from 1b) and add member | ✅ |
| g. | As admin, navigate to `Create > Cluster Members`, and add member | ✅ |

**Comment by nwmac** [comment]
I don't think this is a regression - it's always been like this
