### ISSUE TITLE
Active Directory Auth

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#827]
Implement auth configuration for Active Directory per designs here: [rancher/dashboard#797 (rancher/dashboard#794)](https://zube.io/rancher/dashboard-ui/c/797)

**Comment by deniseschannon** [comment]
View of Required Fields based on ember UI

<img width="1275" alt="Screen Shot 2020-07-14 at 4 22 44 PM" src="https://user-images.githubusercontent.com/11410997/87485704-45134300-c5ee-11ea-9d40-a7808867d490.png">

**Comment by deniseschannon** [comment]
Closing in favor of #2114
