### ISSUE TITLE
Selected rows counter, overflow

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#8273]
**Setup**
- Rancher version: `2.7-head`
- Browser type & version: any

**Describe the bug**

We have a selection counter on the top of the each table where the number of selected rows are displayed.
If the user hits the  `shift+j` combination, the counter never stops, even after all rows are selected;
Same for `shift+k`, which selects the rows from bottom to the top.

**To Reproduce**

Hit `shift+j` until all rows are selected, then continue to see the counter overflow.

**Result**
The counter never stops.

**Expected Result**

The counter should display the number of selected rows.

**Screenshots**

![selection-counter-error-2023-1-27](https://user-images.githubusercontent.com/26394656/221616284-6c7c511e-7fcf-47bb-b888-00048fb8deca.gif)

**Comment by gaktive** [comment]
Engineering to write an automated test to help with QA in #8803
