### ISSUE TITLE
[Enhancement] Display a banner in the `Pod Security Admission` resource to ease transition of new users from PSPs

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#8274]
**Setup**
- Rancher version: v2.7.2-rc3
- Browser type & version: chrome

**Describe the bug**

When a cluster has PSAs applied in the cluster.yaml, the PSAs are not showing up when viewed through the cluster. This is because PSA works differently than PSPs, and only show through the local cluster (not downstream clusters)

**To Reproduce**

deploy a cluster with PSAs enabled. 
Check the Pod Security Admissions resource in the downstream cluster

**Result**
see screenshots, no PSAs show up in the cluster (only available via the local cluster)

**Expected Result**

Clear to the user how to use the new security set from k8s

perhaps adding something like the following to the banner would be helpful: 
```
Only administrators can make changes to any PSAs applied on downstream clusters via the local cluster 
```

**Screenshots**
<img width="719" alt="Screen Shot 2023-02-23 at 10 28 28 AM" src="https://user-images.githubusercontent.com/16691014/221622458-0b3a866b-27e2-42bb-9bb4-3b6b5750b74a.png">
<img width="1218" alt="Screen Shot 2023-02-23 at 10 28 14 AM" src="https://user-images.githubusercontent.com/16691014/221622474-db87295a-da56-49e2-95e8-3114f8eed0e4.png">

**Additional Info**
could just be added to the existing banner: https://github.com/rancher/dashboard/issues/8037

**Comment by slickwarren** [comment]
closing this issue, as it is intended behavior.

**Comment by jiaqiluo** [comment]
Some technical background information about the PodSecurityAdmissionConfigurationTemplate(PSACT) CRD in the downstream cluster:

The CRD exists in the downstream cluster but never be used. We have it due to a limitation in `rancher-webhook`: because the same `rancher-webhook` app is installed in both the local and downstream cluster(with different values, of course), and the app requires the `PodSecurityAdmissionConfigurationTemplate` CRD to exist in the cluster, therefore we have to install the CRD into the downstream clusters. 

One more note: creating the CRs in the downstream cluster does not hurt anything, users cannot use it to configure the cluster or anything. It is simply useless. 

cc @slickwarren

**Comment by nwmac** [comment]
@slickwarren What is the ask? What do you want the banner to say? Are you asking for better wording for the banner you showed above?

**Comment by slickwarren** [comment]
I'm asking that we either add this info to the existing banner or have an additional banner in this resource to inform the user that PSA changes for downstream clusters must be done from the local cluster.

This was my original suggestion, but open to better wording / alternatives:
```
Only administrators can make changes to any PSAs applied on downstream clusters via the local cluster 
```

**Comment by mantis-toboggan-md** [comment]
> One more note: creating the CRs in the downstream cluster does not hurt anything, users cannot use it to configure the cluster or anything. It is simply useless.

Given this extra info, I think it'd make more sense to hide PSACTs in downstream clusters entirely. What do you think @slickwarren ?

**Comment by slickwarren** [comment]
I cannot think of a use case that would be affected by hiding this in downstream clusters. As long as the [CRDs for it aren't affected](https://github.com/rancher/dashboard/issues/8274#issuecomment-1449045952), that sounds like a good solution to me @mantis-toboggan-md

**Comment by mantis-toboggan-md** [comment]
We can hide it purely visually without affecting the CRDs.

**Comment by slickwarren** [comment]
tested on v2.7-head (cd1a716) using dashboard `https://releases.rancher.com/dashboard/latest/index.html`:
* local cluster still has PSA available -- pass
* downstream clusters do not have PSA available in the cluster -- pass
