### ISSUE TITLE
State of rke2/k3s clusters goes to active state immediately after provisioning and then goes back to Reconciling state

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#8276]
Setup

Rancher version: 2.6-head `e6a83ce`
Browser type & version: Chrome

**Describe the bug**
When I provision an rke2/k3s cluster the state of the cluster goes immediately to `Active` state before the state switches back to `Reconciling `

**To Reproduce**
1. Create an rke2 node driver cluster - any nodes
2. Notice the state on the cluster

**Result**
The state stays in `active` for you a few seconds before it switches back to `Reconciling`

**Expected Result**
Expected the state to be in `Reconciling`

**Screenshots**
<img width="856" alt="2023-02-27_08-13-43" src="https://user-images.githubusercontent.com/38144301/221624466-9d2aca97-9a50-47a6-9fbe-51c778fb4697.png">

**Additional context**
This is not seen on v2.6.10 rancher server.

**Comment by gaktive** [comment]
Upon discussion, it's not critical since the state does resolve itself in time, so we'll push this out. We should check if this is happening in 2.7.x

**Comment by richard-cox** [comment]
I've seen this in v2.6-head 8f2f506. State starts in `Active` and changes to `Provisioning`. For RKE2 clusters this comes from the provisioning cluster `metadata.state` property (via `_stateObject` and hyrbid class `state` getters). We should check the updates we get over socket and confirm the backend is setting `active`. We should also check what the state is after creating it locally

**Comment by gaktive** [comment]
For what's left in the 2.6.x lifecycle, this won't be fixed. If this is an issue in 2.7.x, then let's get a new ticket in and link back here for reference.

**Comment by anupama2501** [comment]
Closing as its a `wontfix`.
