### ISSUE TITLE
Row focus unselects random rows

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#8277]
**Setup**
- Rancher version: `2.7-head`
- Browser type & version: any

**Describe the bug**

Clicking a row after we have selected all the rows in a table isn't working as expected. It should unselect all the rows except the one that is clicked (and focused).
It seems that the first selected row remains selected.

**To Reproduce**

- Select all rows in a table (Deployments).
- Click a random column of a row (not the checkbox).

**Result**
The other rows are randomly unselected.

**Expected Result**

It should unselect all the rows except the one that is clicked.

**Screenshots**

![selection-focus-error-2023-1-27](https://user-images.githubusercontent.com/26394656/221626446-5276b2a5-d3d2-4474-8df3-f6296058b396.gif)

**Comment by bisht-richa** [comment]
This issue got fixed after fixing selected rows bug https://github.com/rancher/dashboard/pull/8419
