### ISSUE TITLE
Can not import a generic cluster, can not edit generic cluster

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8278]
Try and import a generic cluster, press save, gets stuck.

Console log shows:
<img width="998" alt="image" src="https://user-images.githubusercontent.com/1955897/221630973-d2bd69bc-64eb-4cb8-82b2-d9eba8636d94.png">

You also get this if you try to edit a cluster brought in this way.

Looking at the code, 'driverSave' is an action not a method, so I think we should be using the 'send' method.

**Comment by jameson-mcghee** [comment]
@nwmac, I don't see a PR on this ticket, was it set to `To Test` by accident?

**Comment by mantis-toboggan-md** [comment]
The PR is here: https://github.com/rancher/ui/pull/4974

**Comment by jameson-mcghee** [comment]
@nwmac and @mantis-toboggan-md, I do not see a completed **Test Template** on this ticket or the linked PR. Setting this ticket to Reopened until we can get that added.

**Comment by mantis-toboggan-md** [comment]
@jameson-mcghee

1. Import a generic cluster with a kubernetes version <1.25
2. 'Edit config' of the generic cluster
3. Change the kubernetes version to 1.25
4. Hit save
5. A dialog appears; hit proceed

 **Expected Result**: The user is redirected back to the cluster management cluster list view, and the edited cluster enters the 'upgrading' state.

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: a841a9e), I was able to verify that the user is able to successfully import a generic cluster and then update the imported generic cluster from Kubernetes `v1.24.11+rke2r1` to `v1.25.7+rke2r1` without issue when following the Steps to Reproduce. Therefore I am closing this ticket.

**Steps to Reproduce:**

1. Import a generic cluster with a Kubernetes version `v1.24.11+rke2r1`
2. 'Edit config' of the generic cluster
3. Change the Kubernetes version to `v1.25.7+rke2r1`
4. Hit save
5. A dialog appears; hit proceed
6. The user is redirected back to the cluster management cluster list view, the edited cluster enters the 'upgrading' state, and then becomes Active again without issue

**`v2.7-head` (Commit ID: a841a9e)**
![image](https://user-images.githubusercontent.com/13294321/226752342-1444478d-47aa-4b59-949d-5b06b27be8a8.png)
![image](https://user-images.githubusercontent.com/13294321/226752358-86726fee-95ad-4ec9-b2ad-34768271586d.png)
