### ISSUE TITLE
Revert `experimental` label for AKS kubernetes 1.24 versions 

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#8280]
**Setup**
- Rancher version:
- Browser type & version: v2.6-head (9b65d8b)

**Describe the bug**

1.24 is showing up as `experimental` in rancher UI, however this is no longer a preview version in Azure and should show as a normal version through rancher. 

**To Reproduce**

try to deploy a 1.24 azure AKS cluster

**Result**
a label is shown for the 1.24 version(s)

**Expected Result**

1.24 is not in experimental state anymore, so it should not show as such. 

**Screenshots**

<img width="326" alt="Screen Shot 2023-02-27 at 9 06 09 AM" src="https://user-images.githubusercontent.com/16691014/221633798-fc5a7c0f-684e-486a-86d6-3ef983857ca7.png">

**Additional context**

a change was made here: https://github.com/rancher/dashboard/issues/6513
however, Azure has moved 1.24 out of `experimental` mode since then.

**Comment by gaktive** [comment]
Sounds similar to EKS: https://github.com/rancher/rancher/issues/40694, which in that case pointed to backend.

**Comment by codyrancher** [comment]
You should wait to test until https://github.com/rancher/rancher/issues/40694 is resolved as that can and should affect this issue.

**Comment by gaktive** [comment]
Not sure what Zube did here but putting this back in To Test.

**Comment by slickwarren** [comment]
tested on v2.6-head ():
* aks now shows 1.24 as normal (supported) version
<img width="708" alt="Screen Shot 2023-02-28 at 9 57 30 AM" src="https://user-images.githubusercontent.com/16691014/221941275-c2c07306-640e-479d-adc5-f040c1ec5bb2.png">
