### ISSUE TITLE
Cluster stays in updating state until the UI is refreshed when we perform actions on the rke2/k3s cluster

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#8282]
Setup

Rancher version: 2.6-head 9b65d8b
Browser type & version: Chrome

**Describe the bug**
Noticed while validating the [issue](https://github.com/rancher/dashboard/issues/8237) that the cluster state stays in updating state for an rke2/k3s cluster when take an etcd snapshot. If we have another cluster in updating state, do not see the issue where the state changes from updating to active without having to refresh the UI.

Steps to reproduce:
 
**To Reproduce**
1. Create an rke2 node driver cluster - 1 etcd + cp, 1 worker
2. Create 2 standard users - user1 and user2 and add the users as cluster owner and cluster member
3. Keep 2 browsers open for a cluster owner and a cluster member
5. As an admin, take an etcd snapshot on the rke2 cluster

**Result**
Notice for a cluster owner , the cluster state stays in `updating` state while for cluster member the state always stays in `active` and  no `updating` state is seen, while for an admin, the state is changed to `active` from `updating` without having to refresh the UI 

**Expected Result**
Expected the state of the cluster to be changed to active and uniform for all the users. 

**Screenshots**
https://user-images.githubusercontent.com/38144301/221717517-5358a6e0-d5f2-44e6-9e78-1a25c0ea056e.mp4

**Additional context**

- This issue will be not seen if we have any other cluster in updating `state`. for example I have an rke1 cluster in updating state and then I see the state change consistently for all three users.
- This sometimes happens when we scale nodes as well
- Do not see the issue when I rotate certs

I checked the behavior on v2.6.10 and this was not the case on 2.6.10 - cluster owner, cluster member and admin have the states on cluster change from `updating` to `active`

**Comment by anupama2501** [comment]
Verified on v2.6-head a1abea5

1. Created an rke2 node driver cluster
2. Enabled azure AD auth
3. Added a cluster owner and cluster member in the rke2 cluster
4.  etcd snapshot as an admin - the state goes into updating and back to active without needing any refresh on the cluster for both admin and cluster owner
5. Scale up node pools - on rke2 cluster and notice that the cluster state goes from updating to active for cluster owner, cluster member and admin.
6. Restore snapshot - state changes from active to updating to active for admin, cluster owner and cluster member without having to refresh the UI.
7. Rotate certs - state changes from active to updating to active for admin, cluster owner and cluster member without having to refresh the UI.

Re opening for the following observations:

1. But noticed that for a cluster member, the state stays in updating until we refresh.
2. Scale up node pools, machine shows unavailable even when the node is created and active. State on machine changes only when we refresh the UI
<img width="400" alt="2023-02-28_13-23-59" src="https://user-images.githubusercontent.com/38144301/221983829-d4b50134-b651-46e8-8bf0-8f250ecfce29.png">

**Comment by nwmac** [comment]
@anupama2501 Given where we are, we don't have time to backport a fix from 2.7.2 that we think addresses your points - the fix made improves things in some areas.

I am going to bump this out of 2.6.11 to the next 2.6 release for consideration. Let mw know if you disagree with that

**Comment by gaktive** [comment]
This is go for 2.6.next2

**Comment by richard-cox** [comment]
There were a few PRs that revolve around cluster updates. We should ensure all are backported (list TBD)

**Comment by richard-cox** [comment]
Two remaining issues from https://github.com/rancher/dashboard/issues/8282#issuecomment-1448942201

Issue 1 - https://github.com/rancher/dashboard/issues/8250#issuecomment-1487040710
Issue 2 - Is worthy of a separate issue 

Given 2.6 is now EOM this is unlikely to be resolved

**Comment by richard-cox** [comment]
After discussing, this isn't a blocker to be addressed in 2.6.12 so closing
