### ISSUE TITLE
Unable to add new machine pool for RKE2 Azure node driver cluster

### ISSUE THREAD

**Issue by jakefhyde** [rancher/dashboard#8283]
**Setup**
- Rancher version: v2.7-head (`d559c2f`)
- Browser type & version: Chrome Version 109.0.5414.74 (Official Build) (64-bit)

**Describe the bug**

When editing an RKE2 Azure node driver cluster and attempting to add a new machine pool, the UI hangs and gets stuck on the `Loading...` screen.

**To Reproduce**

- Create an RKE2 Azure node driver cluster
- Add a new machine pool

**Result**

The following error message is observed in the UI:
```
TypeError: this.vmSizes.filter is not a function
    at f.availableZones (azure.vue:367:1)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.evaluate (vue.runtime.esm.js:4597:21)
    at f.availableZones (vue.runtime.esm.js:4851:17)
    at f.<anonymous> (azure.vue?ccac:1:2173)
    at t._render (vue.runtime.esm.js:3569:22)
    at f.r (vue.runtime.esm.js:4081:21)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.run (vue.runtime.esm.js:4570:22)
    at Sn (vue.runtime.esm.js:4326:13)
```
Additionally noted the following request went out (note `region=undefined`):
```
https://rainbow-2-7.cp-dev.rancher.space/meta/aksVMSizesV2?cloudCredentialId=cattle-global-data%3Acc-klrvv&region=undefined
```

**Expected Result**

Able to successfully add new machine pool.

**Screenshots**

![Screenshot from 2023-02-27 19-53-26](https://user-images.githubusercontent.com/33796120/221724022-2916439d-37a9-45e0-b6b0-2f5d52710619.png)

**Additional context**

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 1032039
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2 azure node driver
----------

### Testing: ###
Tested this issue with the following steps:
1. Create rke2 azure node driver cluster
2. After cluster comes up active `edit config`
3. Add machine pool
4. Verify user is able to add new machine pool to the cluster

**Result**
User is able to add new machine pool to the cluster but I was wondering if it was possible to have the fields pre-filled like behavior normally is when adding a new machine pool during cluster creation.
![image.png](https://zube.io/files/rancher/f4ab2b08f9d75bc35a8716360e9d52bd-image.png)
@aalves08 could you take a look? Thanks!

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 1032039
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2 azure node driver
----------

### Testing: ###
Tested this issue with the following steps:
1. Create rke2 azure node driver cluster
2. After cluster comes up active `edit config`
3. Add machine pool
4. Verify user is able to add new machine pool to the cluster

**Result**
Adding onto the previous testing, the machine pool configurations are now prefilled when adding a new machine pool after creating the cluster.

![image.png](https://zube.io/files/rancher/81d3f8e3f1cfd342fe816c4cafd465c3-image.png)

Machine pool comes up active
![image.png](https://zube.io/files/rancher/696c18ade1620e5c349d7a7bee2f3fed-image.png)
