### ISSUE TITLE
OPA gatekeeper cannot edit Constraint

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#8284]
**Setup**
- Rancher version: rancher/rancher:v2.7.1
- Browser type & version: chrom 110.0.5481.100

**Describe the bug**

OPA gatekeeper cannot edit Constraint, error:
```
Operation cannot be fulfilled on k8sallowedrepos.constraints.gatekeeper.sh "test": the object has been modified; please apply your changes to the latest version and try again
```

**To Reproduce**

1. Create Constraint
2. Edit Constraint and save

**Result**
Editing failed and an error message was returned:
```
Operation cannot be fulfilled on k8sallowedrepos.constraints.gatekeeper.sh "test": the object has been modified; please apply your changes to the latest version and try again

```

**Expected Result**

successfully edited

**Screenshots**

![opa](https://user-images.githubusercontent.com/19684717/221732026-773d9bc5-e2f9-4177-b10d-e0bda0a7ac9a.gif)

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7.2-rc6`
1. installed rancher-gatekeeper:102.0.0+up3.10.0
2. created restraint
3. edited new restraint
4. verified functionality of edited constraint within gatekeeper
