### ISSUE TITLE
[Forward Port] Cluster stays in updating state until the UI is refreshed when we perform actions on the rke2/k3s cluster

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8292]
Forward port of https://github.com/rancher/dashboard/issues/8282
2.6 PR https://github.com/rancher/dashboard/pull/8290

**Comment by anupama2501** [comment]
Verified on v2.7-head 2b2ed44

- Created an rke2 node driver cluster
- Added a cluster owner and cluster member in the rke2 cluster
- etcd snapshot as an admin - the state goes into updating and back to active without needing any refresh on the cluster for both admin and cluster owner
- Scale up node pools - on rke2 cluster and notice that the cluster state goes from updating to active for cluster owner, cluster member and admin.
