### ISSUE TITLE
Azure AD banner to update endpoints is shown while creating RKE1/hosted clusters even when the endpoints are updated

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#8299]
Setup

Rancher version: 2.6-head a1abea5
Browser type & version: Chrome

**Describe the bug**
When we enable azure AD with the new endpoints, the banner to update endpoints is shown when we try to create an RKE1 node driver cluster or an EKS hosted cluster. This is not the case when we try to create an rke2 node driver cluster.

**To Reproduce**
1. Enable azure AD auth - new endpoints are enabled
2. Navigate to create an rke1 node driver cluster

**Result**
We get a banner to update the azure AD endpoints. 

**Expected Result**
Do not expect any banner because the endpoints are already new.

**Screenshots**
<img width="500" alt="2023-02-28_10-15-56" src="https://user-images.githubusercontent.com/38144301/221947184-4da95768-c04f-4288-8cb7-d949e033c627.png">

**Additional context**

- Banner is not seen anywhere else on the UI. only while creating a cluster is it seen.
- Issue not seen on v2.6.9 and v2.6.10
- Issue is not seen for rke2/k3s node driver clusters and custom clusters.

**Comment by anupama2501** [comment]
Verified on v2.6-head 6f7aebc

- Enable azure AD auth - new endpoints are enabled
- Navigate to create an rke1 node driver cluster
- No banner was seen and post cluster creation, if we edit the cluster no banner is seen as well.


Verified upgrade from v2.6.5 to v2.6-head 6f7aebc

- Enable azure AD auth - new endpoints are enabled
- Create an rke1 and rke2 node driver cluster
- Upgrade rancher server - login from <rancherURL>/login
- Update endpoints banner is seen click on it and update the endpoints from steve UI
- Navigate to create an rke1 node driver cluster
- No banner was seen and post cluster creation, if we edit the cluster no banner is seen as well.
- Edit the cluster created before rancher upgrade - no banner is seen as well

Verified upgrade from v2.6.9 to v2.6-head 6f7aebc

- Enable azure AD auth - new endpoints are enabled
- Create an rke1 and rke2 node driver cluster
- Upgrade rancher server - login from <rancherURL>/login
- Navigate to create an rke1 node driver cluster
- No banner was seen and post cluster creation, if we edit the cluster no banner is seen as well.
- Edit the cluster created before rancher upgrade - no banner is seen as well

**Comment by nwmac** [comment]
This is not a regression - this was added in 2.6.11 and there was a bug in the PR
