### ISSUE TITLE
Unable to edit rke2 cluster: 500 error on <cluster>/v1/policy.podsecuritypolicies

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#8300]
**Setup**
- Rancher version: v2.7-head (cca09e4)
- Browser type & version: chrome

**Describe the bug**

when trying to edit an existing rke2 cluster, user gets an error `data: EOF`. Looking at the console, there is a 500 error for `v1/policy.podsecuritypolicies` (response: EOF)

**To Reproduce**

create an rke2 cluster (tested with k8s v1.25)
after the cluster is active, edit the cluster config

**Result**
user cannot edit cluster

**Expected Result**

all users with cluster owner scope should be able to edit the cluster. 

**Screenshots**

<img width="280" alt="Screen Shot 2023-02-28 at 10 39 25 AM" src="https://user-images.githubusercontent.com/16691014/221948598-bc690ce3-27e3-4053-8714-1713338db222.png">

**Additional context**

this is not an issue on 2.7.2-rc4
only happens when editing config, not yaml

**Comment by nwmac** [comment]
@cnotv Can you take a look?

**Comment by cnotv** [comment]
This is caused by https://github.com/rancher/dashboard/issues/7553
There's an issue with the response from the server in case of missing PSP, as it should not return for sure 500, but it should not return error either, as it's meant to be an empty list.

Said that, we already have these filters in place, so we need to understand which case needs still to be excluded:
```ts
 if (this.mode !== _CREATE && !this.isK3s && this.value.state !== 'reconciling')
```

**Comment by snasovich** [comment]
@cnotv , we will look into back-end issue but meanwhile I'm seeing this happening on RKE2 clusters while they are in "Provisioning" or "Updating" state following initial creation. This will be tricky with "Updating" state as already created cluster will go into "Updating" state - so we can't simply skip the check if the cluster is in "Updating" stage.

Also, returning `0` when querying PSPs for unavailable cluster is not the right thing as this could be interpreted as confirmation there are no PSPs there while in fact the answer is "we don't know" which API telegraphs as HTTP code 500.

**Comment by cnotv** [comment]
@snasovich 
If we are not able to know, we'll just get 500 every single time we open the config editor. It's probably something we do not want to have in place.

About the UI: as I have been already covering some cases, it would be convenient to maybe identify all the remaining one.
`Provisioning` and `Updating` states include also changes to the cluster.
Is not the PSPs generated before `Provisioning`?

**Comment by snasovich** [comment]
@cnotv , thinking more about this, maybe it's possibly to update logic to handle it slightly differently.

Currently, it looks like the request to get PSPs completely blocks "Edit Cluster" screen from being shown until it's completed. However, my understanding is that we only need to know if PSPs exist for the purpose of showing a warning when k8s version is changed from <=1.24 to >=1.25. So, could we send this request only on such dropdown change and if it fails/timeouts, show a more generic warning along the lines of "Unable to check whether PodSecurityPolicy resource(s) exist in this cluster. Pod Security Policies are not available in Kubernetes v1.25 and will be automatically removed if they exist.“. If the call succeeds and returns 0 elements - no warning, if returns >0 elements - show the already implemented warning.

cc: @kwwii @nwmac @jiaqiluo

**Comment by cnotv** [comment]
@nwmac @richard-cox any hint on how to don't break out app with a 500 response at every edit? [In this comment they said to keep it like this](https://github.com/rancher/rancher/issues/40732#issuecomment-1457060944).
`Try/catch` seems not working in our architecture, so I ask before tear things apart and not to correct in the PR.

**Comment by richard-cox** [comment]
A `try/catch` block should work when dispatching a `request` action. I think the section is this one, which needs an `await`

```
        try {
          return this.$store.dispatch('cluster/request', { url });
        } catch (error) {
          // PSP may not exists for this cluster and an error is returned without need to handle
        }
```

**Comment by cnotv** [comment]
🤦

**Comment by slickwarren** [comment]
tested on 2.7-head (23074b5):
* editing rke2 cluster via config -> no 500 error -- pass
* edit rke2 via yaml -- pass
* edit rke1 via config -- pass
