### ISSUE TITLE
Cannot change embedded grafana dashboard 

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8301]
**Setup**
- Rancher version: 2.7-head (2.7.2 ish)
- Browser type & version:

**Describe the bug**
- Embedded Grafana Dashboards cannot be updated
  - Cannot switch between `Detail`/`Summary`
  - Cannot change `Range`
  - Cannot change `Refresh`

![image](https://user-images.githubusercontent.com/18697775/221949463-004c4f03-1635-4302-97d5-98731d48f8c4.png)

> I've created https://github.com/rancher/dashboard/issues/8302 for the visual issues

**To Reproduce**
- Install monitoring 
- Nav to cluster dashboard
- Scroll down below events
- Attempt to change the settings on any tab

**Result**
- Error in console
```
9969eb8130ea9eaa87d3.js:sourcemap:2 TypeError: Cannot read properties of undefined (reading 'get')
    at f.currentUrl (9969eb8130ea9eaa87d3.js:sourcemap:2:1785424)
``` 

**Expected Result**
Changes to apply to grafana dashboard

**Additional context**
- result of injector() is undefined
```
       const angularElement = this.graphWindow.angular.element(this.graphDocument.querySelector('.grafana-app');
        const injector = angularElement.injector();

        this.graphHistory.pushState({}, '', this.currentUrl);
        injector.get('$route').updateParams(this.computeParams());
```
- possible caused by a change of angular to react (though angular.element and angularElement.injector are defined)
- https://community.grafana.com/t/were-deprecating-angular-based-plugins/62673

**Comment by richard-cox** [comment]
Monitoring - New Chart - `102.0.0+up40.1.2`. Grafana `9.1.5`
- https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/102.0.0%2Bup40.1.2/charts/grafana/Chart.yaml
Monitoring - Old Chart - `101.0.0+up19.0.3`. Grafana `7.5.11`
- https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/101.0.0%2Bup19.0.3/charts/grafana/Chart.yaml

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7.2-rc7`

1. installed monitoring
2. navigated to cluster page
3. scrolled down to detail/summary graph
4. successfully changed `detail/summary`
5. successfully changed `range`
6. successfully changed `refresh`
7. `all changes verified in the display of the graph` - ie, changes took effect
8. `no console errors`

![2023-03-29_14-06-21.png](https://zube.io/files/rancher/0fccad35420ae9a6311a3a2f06e207ce-2023-03-29_14-06-21.png)
