### ISSUE TITLE
Display of grafana link and information is not displayed correctly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8302]
**Setup**
- Rancher version:2.7-head (2.7.2 ish)

**Describe the bug**
Grafana controls and messages have suffered bit rot

- Grafana link isn't vertically aligned with buttons
- no padding between sections in `Etcd Metrics` tab

**To Reproduce**
- Install monitoring
- Nav to cluster dashboard
- Scroll down below events

**Screenshots**

![221949463-004c4f03-1635-4302-97d5-98731d48f8c4](https://user-images.githubusercontent.com/18697775/221950929-3e8bf818-cc12-4405-8a45-dd9e4b5b853e.png)

**Comment by AndrewHoffmanQA** [comment]
retest passed moving to closed

**testing information:**
-stood up a local 2.7.2rc6
-deployed two downstream clusters-- one 1.25 k8, one 1.24 k8



**testing activities- **

- installed monitoring version 102.0.0+up40.1.2
- navigated to cluster dashboard
- validate UI displays as expected. 
- click on 'detail', 'summary' and 'grafana' and confirm working as expected


results:
1.25 version result- passed
1.24 version result- passed

pass criteria - all buttons work and UI displays as expected
