### ISSUE TITLE
Global Nav Bar

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#831]
<img width="1426" alt="Screen Shot 2020-07-14 at 11 14 21 AM" src="https://user-images.githubusercontent.com/11410997/87461409-45e2af80-c5c3-11ea-9cbf-09619c26cc3d.png">

**Comment by izaac** [comment]
#833

**Comment by izaac** [comment]
Namespace filter explained in a sentence:

> `@vincent`: All is ALL, "all system" includes only the system namespaces, "all user" includes everything but them and is the default.

**Comment by izaac** [comment]
Rancher version `master-head (07/14/2020)` _691feb01a_ k8s HA install
dashboard-index -> `latest`

Checked the following in the Global Nav Bar:

Namespaces filters dropdown
- Cluster switching from the Cluster Dropdown
- Namespace filtering using the predefined filters
- Created a project with 100 namespaces and was able to see all rendered in the dropdown.
- Created deployments and other resources in the user namespaces to see the default filter applied correctly
- Checked the `All Namespaces` `System Namespaces` and other namespaces filters and analyzed the resources displayed

Cluster List dropdown
- Checked in HA environment to see the local cluster included in the dropdown
- Switched to different cluster types, infrastructure and hosted k8s providers.

Cluster explorer will be covered here: https://github.com/rancher/dashboard/issues/832
Two issues/improvements found: #833 #834
