### ISSUE TITLE
[BUG] unable to edit cluster(s) as cluster owner, standard user

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#8316]
**Rancher Server Setup**
- Rancher version: v2.7-head (cca09e4)
- Installation option (Docker install/Helm Chart): docker 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: any (tested with 1.24.10-rancher2-1 and 1.25.6+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): tested with custom, and node driver (linode)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

user is able to create the cluster, but only has `view` permissions through the UI (see screenshots)

**To Reproduce**

* provision a cluster as a standard user
* try to edit the cluster

**Result**
user cannot select any `edit` option through the UI

**Expected Result**

standard users, cluster owners should have edit permissions

**Screenshots**

<img width="282" alt="Screen Shot 2023-02-28 at 10 49 40 AM" src="https://user-images.githubusercontent.com/16691014/221950761-e8fd0557-dee7-4d49-8512-6c47b29d3bc9.png">
<img width="264" alt="Screen Shot 2023-02-28 at 10 49 34 AM" src="https://user-images.githubusercontent.com/16691014/221950764-dc8df4d6-7187-45fe-a21c-76bad0ef47b2.png">

**Additional context**

this is not an issue on v2.7.2-rc4, only on head

**Comment by richard-cox** [comment]
I couldn't reproduce this with the same version (v2.7-head `cca09e4`) with DO

- Created a standard user
- assigned them as cluster owner to 
  - rke2 v1.25.6+rke2r1 cluster
  - rke2 v1.24.10+rke2r1 cluster
- create and rke2 v1.25.6+rke2r1 cluster
- checked `Edit Config` availability of all three clusters in the clusters list and each cluster detail page 

The `Edit Config` button will only show if the underlying resource has the `links.update` url. This can be checked via the `<rancher url>/v1/provisioning.cattle.io.clusters` entry for the cluster

@slickwarren some questions..
- It looks like your screenshots are different, are they the same cluster?
- Is the `Edit Config` button shown after a refresh?
- Can you check of the `links.update` url is there in your `provisioning.cattle.io.clusters` resource as described above?

**Comment by slickwarren** [comment]
I have removed the setup since then, but the screenshot differences are:
* first one is for a node driver cluster
* second is for a custom cluster
Not sure if it matters, but in my case I created the cluster(s) as a standard user, (it seems you assigned them the `cluster owner` role as an admin after cluster creation).

**Comment by richard-cox** [comment]
Ah, that makes sense. One type would have less menu entries than the other, thanks.

Of the three clusters i tested with, two were pre-existing but one was created as the standard user

**Comment by richard-cox** [comment]
Neil's and I had a  separate attempt to reproduce this with v2.7-head (c24fb8b), there we brought up a RKE2 Linode cluster as a standard user. From the initial view of the clusters list through to deployment and a refresh the Edit option was visible.

@slickwarren Could you give this another go and if it occurs provide us with access to the system?

**Comment by slickwarren** [comment]
tested on v2.7-head (6cca23f) and I am no longer seeing this issue. It may have been some weird caching issue or something, though I did try clearing it multiple times before creating the issue. 
<img width="1135" alt="Screen Shot 2023-03-06 at 11 43 32 AM" src="https://user-images.githubusercontent.com/16691014/223214527-9d102a1c-ca28-473d-ad8b-914fdd19301e.png">
