### ISSUE TITLE
Cluster Explorer Nav 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#832]
<img width="214" alt="Screen Shot 2020-07-14 at 11 17 58 AM" src="https://user-images.githubusercontent.com/11410997/87461755-b2f64500-c5c3-11ea-815b-a92a42f9f92d.png">

**Comment by sowmyav27** [comment]
**Validated on master-head - commit id: `16616de9c`**

- Logged in as a standard user
- Type into the `Jump to` search text field, the options are filtered. User is able to click on the resource and navigate to the corresponding page
<img width="228" alt="Screen Shot 2020-07-17 at 3 08 36 PM" src="https://user-images.githubusercontent.com/26032343/87834627-bf86d180-c83f-11ea-92d7-090f93bb89bd.png">

- Add star to options in the Cluster Explorer Nav bar and the options are added to another section `Starred`
- Clicking on an option from `Starred`, user is navigated to the right page
<img width="257" alt="Screen Shot 2020-07-17 at 3 10 16 PM" src="https://user-images.githubusercontent.com/26032343/87834642-cad9fd00-c83f-11ea-890e-aa1def7b5dc9.png">
