### ISSUE TITLE
Idle Modal: Configuration

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8322]
Parent Issue: https://github.com/rancher/dashboard/issues/7776

Dependent Issue: rancher/dashboard#8321

- Implement the configuration as detailed in the parent issue
- Replace any hardcoded values from parent issue with the new config settings

**Comment by nwmac** [comment]
@scures Do you plan to write tests? If so, can we move this back to working or re-opened

**Comment by gaktive** [comment]
Let's mark this as engineering done and put the tests in the parent: #7776
