### ISSUE TITLE
Update default dropdown option label for PSA in RKE2/K3S Cluster editor for K3S default case K8S version 1.25+

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8325]
# Description

PSA controller is enabled by default in K3S and does not have a default PSA config.
Change default dropdown option label for PSA in RKE2/K3S Cluster editor for K3S default case K8S version 1.25+ into `(None)`.

## Context

![image](https://user-images.githubusercontent.com/5009481/222498449-d157e5eb-af80-4594-b762-c73a7d378efb.png)

Reported by @macedogm and confirmed by @jiaqiluo.

**Comment by slickwarren** [comment]
pending discussion - will QA after a decision is made
