### ISSUE TITLE
Global Nav Bar - TypeError when clicking in the kubectl icon

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#833]
Rancher version `master-head (07/14/2020)` _691feb01a_ k8s HA install
dashboard-index -> `latest`

1. Deploy a cluster
2. Go to Dashboard and click in the kubectl Terminal icon in the Global Navbar (next to the select cluster dropdown).

Result:

```
TypeError: Cannot read property 'replace' of undefined
    at f.getSocketUrl (KubectlShell.vue:18)
    at ContainerShell.vue:180
    at Generator.next (<anonymous>)
    at r (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at f.connect (ContainerShell.vue:173)
    at ContainerShell.vue:99
te @ commons.app.f7e20867c325f96c399f.js:2

```

**Comment by vincent99** [comment]
This currently only works in standalone steve because the new cluster API isn't in rancher..

**Comment by deniseschannon** [comment]
Appears to be working in master-head (9/8) for local cluster. I haven't tested the downstream user clusters

**Comment by izaac** [comment]
Rancher version: `master-head (09/09/2020)` _f7f8e8bb0_ k8s HA
Rancher version: `master-head (09/09/2020)` _f7f8e8bb0_ Single Docker


I was able to use the Shell from the Dashboard. And use also multiple shell tabs in the browser. (GKE, AKS, EKS, RKE, Imported)

![Screen Shot 2020-09-09 at 10 53 26 AM](https://user-images.githubusercontent.com/27659/92635568-e800da00-f28a-11ea-9569-3eee0e5e99a2.png)

Did a quick check of clusters provisioned in Single Docker Rancher install with RKE clusters and the local k3s.
