### ISSUE TITLE
Global Nav Bar - Switching clusters takes the user to the Cluster Details page

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#834]
Rancher version `master-head (07/14/2020)` _691feb01a_ k8s HA install
dashboard-index -> `latest`

1. Deploy two clusters (A and B)
2. Navigate to Dashboard in Cluster A
3. Select Pods in the Workloads from Cluster Explorer menu - This is Pods list 
4. In the Global NavBar select Cluster B

Result:

User is taken to Cluster B's Cluster Detail (Cluster Dashboard).

Improvement:

Take user to Cluster B but persist the view we were navigating in Cluster A. In this case Pods list. 
This feels more natural that the user can compare or navigate quickly to the same resource page in both clusters. And is in sync  on how Ember UI is behaving.

**Comment by vincent99** [comment]
I don't think we're changing this, particularly as switching clusters is now more of a primary nav task in the slide out menu.
