### ISSUE TITLE
List global roles/users pages for standard users when they have custom permissions assigned

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#8344]
Setup

Rancher version: 2.7-head, 2.7.0
Browser type & version: Chrome

**Describe the bug**
When we assign standard users with custom global roles, the configuration >> Users&Auth pages are not listed for the users

**To Reproduce**
1. As an admin, create a global role by navigating to Users and Auth >> Roles >> Global Roles >> Verbs: List, Get & Resources: Global Roles
2. Create a standard user as an admin and assign the role
3. Log in as standard user

**Result**
Page Configuration >> Users & Authentication pages are not listed for the standard user. 

**Expected Result**
Expected the user to be able to list/get the pages/

**Additional context**
This happens from 2.6.4 as well.
On the ember UI these pages are visible to the standard users. but they cannot edit the roles.

**Comment by gaktive** [comment]
Engineering to write automated tests for this in https://github.com/rancher/dashboard/issues/8777

**Comment by anupama2501** [comment]
Re opening as this issue wasn't validated as part of QA testing.

**Comment by sowmyav27** [comment]
Since this is a forwardport, there will be no QA validations.
