### ISSUE TITLE
ProjectHelmChart values are not passed to CR spec correctly

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#8348]
**Setup**
- Rancher version: 2.7.1
- Browser type & version: Chrome

**Describe the bug**
When creating/editing a ProjectHelmChart through the UI (e.g. by creating a Project Monitor), the UI does not set the Helm Values correctly into the ProjectHelmChart resource.

Instead of setting the values at `spec.values`, the values are set top-level.

**To Reproduce**
* Install Rancher Monitoring
* Install the Prometheus Federator
* Create a Project Monitor
* Change one of the values
* Click on Edit as YAML

**Result**
The values are writing top level into the ProjectHelmChart resource and because of this ignored.

**Expected Result**
The values are written into `spec.values` and applied. When editing the ProjectHelmChart, you see the previously set values.

**Screenshots**
![Bildschirm­foto 2023-03-06 um 10 21 21](https://user-images.githubusercontent.com/243056/223071430-3f9635ae-dca8-4196-b164-57369352e5f8.png)

**Comment by richard-cox** [comment]
QA'd in 2.7.2 via https://github.com/rancher/dashboard/issues/8366, closing
