### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#838]
<img width="1196" alt="Screen Shot 2020-07-14 at 2 22 50 PM" src="https://user-images.githubusercontent.com/11410997/87477780-894a1780-c5dd-11ea-8b1f-a00f9f0d6fdc.png">

The lack of Rancher/UI version is noted with this issue: 
https://github.com/rancher/dashboard/issues/561

**Comment by sowmyav27** [comment]
**Validated on master-head - commit id: `16616de9c`**
- Footer is available
<img width="531" alt="Screen Shot 2020-07-17 at 1 13 15 PM" src="https://user-images.githubusercontent.com/26032343/87827252-5f882f00-c82f-11ea-891b-20e158f1beb9.png">
