### ISSUE TITLE
[Network policies] Matching pods and namespaces are zero

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#8392]
**Setup**
- Rancher version: 2.7
- Browser type & version: any

**Describe the bug**

When the edit view is opened for a Network Policy, the matching pods are always zero, even if there are matching pods in the namespace.

**To Reproduce**

- Create a new `Network Policy` with at least one rule that matches at least one `Pod`
- The banner correctly shows one Pod matching
- Save and reopen the new Network Policy, by clicking 'Edit config' from the action button.
- The matching pods are zero.

**Result**
The matching pods are zero.

**Expected Result**

The banner should display the matching Pods

**Screenshots**

![image](https://user-images.githubusercontent.com/26394656/224142059-39bb0102-f8dc-44f7-8179-2640c065eac0.png)

**Additional context**

**Comment by gaktive** [comment]
Engineering to write an automated test for this in https://github.com/rancher/dashboard/issues/8774
