### ISSUE TITLE
Add bundle assets option to the Vue configuration

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8395]
# Description

After migration from Nuxt to Vue, assets are not bundled anymore for production.

<img width="913" alt="Screenshot 2023-03-10 at 09 57 52" src="https://user-images.githubusercontent.com/5009481/224285342-2b4cffef-28ac-4397-8fc7-bfacc00ac6ba.png">

## Context

The bundling feature is related to Webpack configuration, mapped from the `vue.config` file.
It may probably be enabled by default by passing the production flag in Vue, [see docs](https://v2.vuejs.org/v2/guide/deployment.html#Without-Build-Tools).

**Comment by cnotv** [comment]
An interesting way to [inspect our configuration](https://cli.vuejs.org/guide/webpack.html#inspecting-the-project-s-webpack-config) @codyrancher by using the `inspect` flag, e.g. `vue inspect --mode production > output.prod.js`

**Comment by cnotv** [comment]
@nwmac looks like the only bundling logic Nuxt supports is with [Rollup](https://rollupjs.org/) 😬 
https://github.com/nuxt/nuxt/blob/2.x/scripts/rollup.config.js

Not so sure if we want to do the same or rather find something from the Vue world.

**Comment by codyrancher** [comment]
@cnotv webpack is a bundler and already comes with vue.

Do we even want to disable code splitting? Is there a metric that you've measured that you'd like to improve? Often times code splitting will improve caching and initial load time.

With that said, I'm able to produce this bundle
<img width="900" alt="image" src="https://github.com/rancher/dashboard/assets/55104481/55f9f247-2b81-4be0-a530-b55b1ea0993c">

With this single line change in our vue.config.js (you can reduce it to 1 chunk if desired)
<img width="970" alt="image" src="https://github.com/rancher/dashboard/assets/55104481/2aa4aeae-38de-4d5a-b459-e59c3db54e5f">

And if you wanted to reduce the css files you can always use https://cli.vuejs.org/config/#css-extract but I don't think I'd recommend it.

**Comment by nwmac** [comment]
@cnotv You sure? - pretty sure they use webpack

**Comment by cnotv** [comment]
> Do we even want to disable code splitting? Is there a metric that you've measured that you'd like to improve? Often times code splitting will improve caching and initial load time.

I don't want to disable code splitting, but when I build the project it has an huge list of imports, as you see in the screenshot.
The same is if you check the CI.

Where did you get that output? If you have a way to don't create all these files, then we can use that and close here

> With this single line change in our vue.config.js (you can reduce it to 1 chunk if desired)

This is what I got when I tried to use 1 chunk:

<img width="626" alt="Screenshot 2023-05-09 at 16 01 45" src="https://github.com/rancher/dashboard/assets/5009481/2b3479a4-5024-4bb0-9165-d36bf8a29a3c">

**Comment by cnotv** [comment]
> @cnotv You sure? - pretty sure they use webpack

Look the [package.json](https://github.com/nuxt/nuxt/blob/2.x/package.json).
Then [look the script to bundle things](https://github.com/nuxt/nuxt/blob/2.x/scripts/rollup.config.js).

**Comment by cnotv** [comment]
In version 3 on `main` they use [their own bundler `@nuxt/webpack-builder`](https://github.com/nuxt/nuxt/blob/main/package.json#L32) but also [`@nuxt/vite-builder`](https://github.com/nuxt/nuxt/blob/main/package.json#LL31C6-L31C24), which is kinda confusing without investigate further tbh. 
Vue 3 uses [Rollup and Vite](https://github.com/vuejs/core/blob/main/package.json#L90).

**Comment by codyrancher** [comment]
> Where did you get that output? If you have a way to don't create all these files, then we can use that and close here

Just that one change and `yarn build` just as you did. Might need to get on a call to figure out what's different.

> I don't want to disable code splitting, but when I build the project it has an huge list of imports, as you see in the screenshot.

Do the large number of imports cause a problem I'm unaware of? I guess I'd only want to change this if there was something like a performance metric that regressed. If others disagree that's fine.

**Comment by cnotv** [comment]
We do not measure performance metrics as far as I'm aware.
The scope was just to bring it back to what we had prior migration.
We can close the issue if you think it brings no changes.

**Comment by cnotv** [comment]
As @codyrancher mentioned, the chunks are also generated due Webpack comments (cannot recall the right term), which it may be inconvenient for lazy-loading:
https://router.vuejs.org/guide/advanced/lazy-loading.html#grouping-components-in-the-same-chunk

As testing the current navigation this is what we actually have, it will be counterproductive to load all the pages at once.

Therefore I'm closing this issue and keep it as it is.
