### ISSUE TITLE
Service - Client Side Validation

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#840]
Add in client side validation based on changes from adding ability to do it int this [PR](https://github.com/rancher/dashboard/issues/189) to have friendlier error messages.

**Comment by deniseschannon** [comment]
@westlywright Can you give QA some insights on what they should be testing for?

**Comment by westlywright** [comment]
I used the [original ticket](https://github.com/rancher/dashboard/issues/583) to add validation on the Service Ports and external name inputs for the input type referenced in the corresponding table in the ticket. Please note the Protocol options have been reduced from what was in the original requirement and updated in another comment and then updated to just `TCP/UDP`.

**Comment by izaac** [comment]
#1694

**Comment by izaac** [comment]
Rancher version: `master-head (10/26/2020)` a3a4c87
I've validated the fields validation checks on the different service types there's a 2 part fix in #1694 where the nodeport range was fixed as well as the targetport type. I will follow up that separately.
