### ISSUE TITLE
New side menu with collapsed, always visible bar for easy navigation

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#8418]
Several users have previously mentioned that quickly changing between clusters would be really useful in some scenarios. Right now, they're required to deploy the sidenav to do it. We want to keep a minimised version of it always visible. 

Confluence: https://confluence.suse.com/pages/viewpage.action?pageId=1190330706

Design specs: https://github.com/rancher/dashboard/issues/8834

**Comment by edenhernandez-suse** [comment]
This is an attempt to fit 3 characters into the cluster blocks and the active blue as a background colour. There might be some issues to discuss about.

![Dashboard-Normal – 5](https://user-images.githubusercontent.com/120640736/224752896-ec42df91-2bee-48e7-8dd0-dccfe61c82c0.png)

![Dashboard-Normal – 8](https://user-images.githubusercontent.com/120640736/224752946-ab334f87-e322-407b-82cc-c8846db19a3c.png)

![Dashboard-Normal – 6](https://user-images.githubusercontent.com/120640736/224752986-706e4a7b-709f-43c1-8fa5-46588b24785d.png)

![Dashboard-Normal – 7](https://user-images.githubusercontent.com/120640736/224753008-7542d2d3-7047-41b0-aad8-61debff34110.png)

**Comment by edenhernandez-suse** [comment]
After the UX roundtable, we decided to go for the rectangular blocks.

[Adobe Xd prototype](https://xd.adobe.com/view/b309a7ad-76d5-4a98-9554-985b40e5b31b-e65a/)

![image](https://user-images.githubusercontent.com/120640736/225089685-b820da19-18a7-40cb-8cd9-fa7bb63f8181.png)

![image](https://user-images.githubusercontent.com/120640736/225089937-9bf5394c-27ff-4d19-9fd0-e6a773eeeaff.png)

**Comment by edenhernandez-suse** [comment]
@kwwii should we close this issue and create another one for Dev? the design work is finished.

**Comment by kwwii** [comment]
@edenhernandez-suse Yes, we should create a new issue for the development of these features (probably breaking it down into separate issues during grooming).

I added the QA/None label so that when the card is marked as "Done" it will not go through QA cycles.

**Comment by edenhernandez-suse** [comment]
Regarding the "See all" link (and the "14 more" button), I would suggest linking them temporarily to Cluster Management > Clusters:

![image](https://user-images.githubusercontent.com/120640736/225337793-00265c07-832e-4d22-8a3a-4323e650ca1f.png)

In the future, when we take care of Cluster Management (and probably get rid of it), we would need to replicate that clusters table in a new view; but for the time being, I would just use that Clusters view.

**Comment by kwwii** [comment]
https://confluence.suse.com/pages/viewpage.action?pageId=1190330706

**Comment by gaktive** [comment]
We need to split this ticket into various chunks and work in a separate branch since this all has to land at the same time:
- Bar
- Products
- Clusters

@richard-cox & @rak-phillip can help based on their past experiences, particularly with Rancher Desktop.

**Comment by gaktive** [comment]
Primary focus for this ticket: update the high-level menu.

Down the road: cluster management and other sub-components. We won't fix the convoluted logic that ties into generating some of the other menus since that's been a sticky point for a while.

**Comment by gaktive** [comment]
To allow for more time to work on this, we'll push this to Q3.

**Comment by cnotv** [comment]
To be considered existing tests and related issues https://github.com/rancher/dashboard/issues/5966

**Comment by gaktive** [comment]
https://xd.adobe.com/view/1453b6a5-ca9c-4794-8fbf-34f1349e45a3-4100/ has the proposed view.
