### ISSUE TITLE
Config Map - Update to CruResource and Client Side Validation

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#842]
**Update ConfigMap to CruResource Flow**
Labels and Annotations within Resources
* Move to Vertical Tabs 
* 1 tab name - "Labels & Annotations"
* Inside the tab, use the LabelsAndAnnotations component, which should cause the labels to be stacked on top of the annotations and it should be full width. 

Add in client side validation based on changes from adding ability to do it int this [PR](https://github.com/rancher/dashboard/issues/189) to have friendlier error messages.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `f08bf21f9`**

Validated the following:
- Add labels/annotations
- Add key value
- Labels and annotations in a vertical tab
- Labels stacked on annotations
<img width="1212" alt="Screen Shot 2020-08-20 at 4 51 34 PM" src="https://user-images.githubusercontent.com/26032343/90836920-71b12d80-e305-11ea-8206-8cd9238f8e21.png">
