### ISSUE TITLE
Typo in Basics > Security UI

### ISSUE THREAD

**Issue by martyav** [rancher/dashboard#8426]
**Setup**
- Rancher version: 2.7.2
- Browser type & version:

**Describe the bug**
In the screenshot, there's a typo in the blue callout -- "PodSecurity Admission" should be "Pod Security Admissions"

**Screenshots**
![image](https://user-images.githubusercontent.com/19174201/224819351-7874d7dd-eb59-41c0-a43a-300b1a6f964f.png)

**Comment by brandond** [comment]
It should actually be "Pod Security Standards",  "Pod Security Admission" is the controller that enforces the Standards.

https://kubernetes.io/docs/concepts/security/pod-security-admission/

> The Kubernetes [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) define different isolation levels for Pods. These standards let you define how you want to restrict the behavior of pods in a clear, consistent fashion.
> 
> Kubernetes offers a built-in Pod Security [admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/) to enforce the Pod Security Standards. Pod security restrictions are applied at the [namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces) level when pods are created.

**Comment by gaktive** [comment]
Internal reference: SURE-6022

**Comment by jiaqiluo** [comment]
+1 to @brandond's [comment](https://github.com/rancher/dashboard/issues/8426#issuecomment-1466933984)
