### ISSUE TITLE
Namespaces - Update to CruResource and Client Side Validation

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#843]
**Update ConfigMap to CruResource Flow**
Labels and Annotations within Resources
* Move to Vertical Tabs 
* 1 tab name - "Labels & Annotations"
* Inside the tab, use the LabelsAndAnnotations component, which should cause the labels to be stacked on top of the annotations and it should be full width. 

Add in client side validation based on changes from adding ability to do it int this [PR](https://github.com/rancher/dashboard/issues/189) to have friendlier error messages.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `f08bf21f9`**

- Navigate to Namespace
- Click on a Namespace

**Issue 1**
- `Labels & Annotations` vertical tab is NOT seen
<img width="1690" alt="Screen Shot 2020-08-20 at 3 13 39 PM" src="https://user-images.githubusercontent.com/26032343/90831121-e2e9e400-e2f7-11ea-89e5-72be7d44ee07.png">

**Issue 2**
- There is difference between namespace windows vs Service window
- Service - has extra space between Type/Labels and the bottom section whereas in the namespace - No space between annotations and the bottom section
<img width="741" alt="Screen Shot 2020-08-20 at 3 13 39 PM" src="https://user-images.githubusercontent.com/26032343/90831229-20e70800-e2f8-11ea-802c-b9ab3d2a5e53.png">
<img width="1275" alt="Screen Shot 2020-08-20 at 3 15 06 PM" src="https://user-images.githubusercontent.com/26032343/90831232-22b0cb80-e2f8-11ea-8577-7249f6909498.png">

**Comment by codyrancher** [comment]
Issue 1 is intended behavior. When viewing the labels and annotations are shown within the DetailTop component.
![Screen Shot 2020-08-24 at 1 59 27 PM](https://user-images.githubusercontent.com/55104481/91096215-7e3dca80-e612-11ea-8790-e2f52629f77c.png)

I'm making the change for Issue 2.

**Comment by sowmyav27** [comment]
@codyrancher In config maps and services, the Labels & Annotations on the left in the vertical tab like this. Do we want to change Namespaces like services and config maps, or should it be the other way around? 
<img width="1703" alt="Screen Shot 2020-08-24 at 3 42 49 PM" src="https://user-images.githubusercontent.com/26032343/91103624-cd8af780-e620-11ea-8312-9712c8ae7b74.png">

**Comment by codyrancher** [comment]
@deniseschannon I believe I was asked to hide labels and annotations tab when viewing a resource because it's already in detailtop. Is my memory correct?

**Comment by deniseschannon** [comment]
Correct @codyrancher.For view, labels and annotations should be moved to detail top for the resource.

@sowmyav27 This is how all resources will look like. Where on create/edit, it'll be in the vertical tabs, but in a detail view of the resource, it will only show up in the detail top, which is the section between the heading and tabs.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `5e1b21b93`**

Namespace looks good now and is similar to Services
<img width="1299" alt="Screen Shot 2020-08-27 at 9 53 29 AM" src="https://user-images.githubusercontent.com/26032343/91471745-51c0c300-e84b-11ea-8426-5f9310a22527.png">
