### ISSUE TITLE
configmap cache data is inconsistent

### ISSUE THREAD

**Issue by 467892746** [rancher/dashboard#8430]
**Setup**
- Rancher version:v2.7.1

- Browser type & version: chrome 111.0.5563.64 arm64

**Describe the bug**
![image](https://user-images.githubusercontent.com/46819001/224888909-4f221243-50e0-4670-9a05-1a1e2a09c9e2.png)
![image](https://user-images.githubusercontent.com/46819001/224888940-8272605d-65cd-4d94-9502-25ea4c269e50.png)

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment]
I could not reproduce in 2.9-head, form and yaml content match. Feel free to re-open with some clear steps to recreate
