### ISSUE TITLE
Custom chart UIs show PSP switch on Kubernetes v1.25

### ISSUE THREAD

**Issue by stormqueen1990** [rancher/dashboard#8434]
**Setup**
- Rancher version: Rancher v2.7.2-rc5
- Browser type & version: Microsoft Edge v111.0.1661.41 (Official build) (arm64)

**Describe the bug**

When installing charts on a Kubernetes v1.25.6 cluster, the custom chart UIs still show the **Enable PodSecurityPolicies** checkbox, even though it is not possible to have PSPs in this version of Kubernetes and above.

**To Reproduce**

1. Create an RKE downstream cluster with Kubernetes v1.25.
2. Go to **Explore Cluster** and select the newly created v1.25 cluster.
3. In **Apps**/**Charts**, select one of the following charts:
    * Alerting Drivers
    * Epinio
    * Istio
    * Logging
    * Longhorn
    * Monitoring
    * NeuVector
    * OPA Gatekeeper
    * Prometheus Federator
5. Click **Install**.
6. Select any project then click **Next**.
7. Notice that the second page of configuration shows the **Enable Pod Security Policies** checkbox.

**Result**
A user can still select the checkbox to install PodSecurityPolicies even though these are not supported in Kubernetes v1.25 anymore.

**Expected Result**

A user cannot choose to install PSPs from the UI when the cluster is Kubernetes v1.25.

**Comment by richard-cox** [comment]
Only some of those have custom UIs
- OPA Gatekeeper
- Istio
- Logging
- Monitoring
- Additionally
 - Rancher Backup

For the following they come from the chart themselves (as part of questions.yaml) and need issues on each owners repos
- Alerting 
- Epinio
- Longhorn
- NeuVector
- Prometheus Federator

**Comment by stormqueen1990** [comment]
I updated the issue description above to be clearer. The checkbox must still be available if the underlying cluster is up to Kubernetes v1.24 so as to allow an user to remove PSPs from a chart prior to an upgrade to Kubernetes v1.25.

**Comment by cnotv** [comment]
A tad off-topic although, why are there 2 NeuVector charts which look totally the same?

![Screenshot 2023-03-15 at 15 50 09](https://user-images.githubusercontent.com/5009481/225347215-9ff65145-7da4-4f69-898d-52868bcb1106.png)

**Comment by cnotv** [comment]
I can confirm that we have 4 cases which would fall in that logic, specifically the one we introduced by using `ChartPsp`.

**Comment by gaktive** [comment]
@mantis-toboggan-md can help point where things are for whoever grabs that.

**Comment by cnotv** [comment]
As discussed with @stormqueen1990, we may reconsider the logic adopted for cases where the PSP options is already enabled due cluster upgrades. PSP is not removed automatically in the process due security changes on behalf of the users are avoided.

A suggested solution is to add a validation to the process.

**Comment by gaktive** [comment]
This is blocking backend on 2 tickets: rancher/rancher/issues/40853 & rancher/rancher/issues/40863

**Comment by gaktive** [comment]
Upon clarification, backend is unblocked per https://github.com/rancher/rancher/issues/40863#issuecomment-1478422431 but this issue is needed to complete the work for testing so this is a release blocker.

**Comment by cnotv** [comment]
@gaktive the requirement is still unclear.
Are we going to stick with hiding the checkbox or what is the outcome?
Should I set it back to triage to make it clear?

**Comment by cnotv** [comment]
@kwwii I guess you are required once again to express the final decision.

**Comment by stormqueen1990** [comment]
Extra information on the validation suggestion: considering that some of the charts do not use custom UIs as mentioned [here](https://github.com/rancher/dashboard/issues/8434#issuecomment-1469694660), if a validation was present on the event of clicking install for a chart that would address both the custom and the non-custom UI scenarios.

For context, the charts that we maintain currently error out when a user chooses to install a chart with PSPs enabled on Kubernetes v1.25. However, that is not true for the CRD charts (as they do not have the PSP resources on them), which can then cause confusion when a CRD chart is correctly installed and starts showing the configuration tabs, but the main functionality is missing because the main chart failed to install due to a checked PSP switch.

**Comment by cnotv** [comment]
After discussing with @nwmac and @kwwii we decided to make the checkbox invisible if:
- K8S version is >1.25
- PSP is not enabled

In this way the user will still able to uncheck the PSP while we prevent it to add it in case of the condition above.

**Comment by cnotv** [comment]
@stormqueen1990 I see that in the previous issue https://github.com/rancher/dashboard/issues/8053 we had the need to force the PSP value to false if it did not exists.
Is this a kind of logic which we have to remove data wise, on top of removing the checkbox?

**Comment by cnotv** [comment]
Increasing size due change of requirements and amount of tests and QA.

**Comment by cnotv** [comment]
@stormqueen1990 
When I try to remove the PSP an error is returned. As you can see in the payload, the PSP is correctly removed.

https://user-images.githubusercontent.com/5009481/227241882-6b957f5f-8d21-4690-8108-e617fbbc48d1.mp4

**Comment by cnotv** [comment]
@stormqueen1990 For the charts which are based on `question.yaml` we may create a set of exceptions based on the data and filter up what is displayed mapping some logic.
Thing is that these configurations are not consistent and we may create a layer of complexity by adding the logic here.

Note: this would be regardless of which solution you want implement, as the data is the same.

**Comment by stormqueen1990** [comment]
> @stormqueen1990 I see that in the previous issue #8053 we had the need to force the PSP value to false if it did not exists. Is this a kind of logic which we have to remove data wise, on top of removing the checkbox?

@cnotv removing PSPs is a process on the user side. This is meant to be done by upgrading the charts to v102.0.0 while still on Kubernetes v1.24. In this process, the **Enable PodSecurityPolicies** checkbox would be unchecked, which then results in PSPs being removed. If that has not been followed, after an upgrade to Kubernetes v1.25 has already been performed, a tool such as `helm-mapkubeapis` is required to remove lingering PSPs from an installed chart.

I had originally suggested hiding the checkbox in order to prevent the message you show in your screen recording ("the target cluster does not support PSPs..."). In the case of a chart where only the main chart contains PSPs but not the CRD chart, the installation of the former fails, but not of the latter, and the configuration tabs show up. One such example is Logging. Hence my second suggestion for erroring out on the click of install.

**Comment by stormqueen1990** [comment]
> @stormqueen1990 I see that in the previous issue #8053 we had the need to force the PSP value to false if it did not exists. Is this a kind of logic which we have to remove data wise, on top of removing the checkbox?

Yes, I think setting the checkbox to false would be the correct way to address this.

**Comment by gaktive** [comment]
For those reading two tickets with the same milestone, they exist to ensure that the change is in both `master` and the `2.7.2` release branch.

**Comment by stormqueen1990** [comment]
With the latest RC of Rancher v2.7.2, it seems that the value for the **Enable PodSecurityPolicy** checkbox is always being reset to false, even when the cluster is at a version less than v1.25.

When I opened this issue I meant to say that the checkbox should only be hidden when the clusters are at v1.25 or higher. If a cluster is at a version before v1.25, users should still be able to install and uninstall PodSecurityPolicies as they see fit.

Therefore, I wanted to clarify the requirement:
* For Kubernetes v1.24:
  * A user should be able to check the **Enable PodSecurityPolicies** checkbox.
  * When clicking **Install**, this procedure should not be prevented, and the user selection for the **Enable PodSecurityPolicies** checkbox should be retained. Installation will succeed, as Kubernetes v1.24 still has the PSP API available.
* For Kubernetes v1.25:
  * Checkbox should not be shown in the UI. As it is being hidden, it is OK to reset the value to **false**.

CC @prachidamle @nickwsuse

**Comment by cnotv** [comment]
Can you please make a video of it just as I did?
My PR does exactly what you asked for and you can check the videos.

**Comment by cnotv** [comment]
@stormqueen1990 so I stick with what is written here in the last comment and I remove the extra implementation and test we added.

Code related to the value of the checkbox has been left unchanged, so I will investigate about the issue.

**Comment by cnotv** [comment]
@stormqueen1990 I tried to setup 3 different charts with PSP enabled and I had the following results:
- Istio: it fails to install, no idea why
- Longhorn: it installs it and keeps the PSP value
- Monitoring: it installs, also update, but keeps setting PSP as `false` in the payload as you mentioned

It seems like the issue is restricted and I do not know if this was present also earlier.

https://user-images.githubusercontent.com/5009481/228578661-1c4f24c6-2596-4cd4-b9a3-1ebe5c444ee5.mp4

**Comment by ronhorton** [comment]
**Pass** verified on rancher `v2.7.2-rc8`

On a 1.25 cluster I do not see the enable psp checkbox. 
I do see the enable psp checkbox on a 1.24 cluster. 
When I select `enable psp` the value `global.cattle:psp.enabled: = 'True'`
