### ISSUE TITLE
Update Enterprise Cluster Manager (ECM) concept

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#844]
- Ability to enable MCM
- Provision a new cluster in MCM and ability to go from MCM UI (Ember) to Rancher UI (Vue/Dashboard) to navigate the cluster using the "Cluster Explorer"
- Toggle between Rancher and MCM views (Vue/Ember UIs)

**Comment by maggieliu** [comment]
Can we skip the chart option page is it's empty for ECM?

**Comment by deniseschannon** [comment]
With the removal of ECM as a feature of Rancher, we need to update the UI to remove the ECM dashboard link.

**Comment by deniseschannon** [comment]
* Update ECM text to "Cluster Manager" and have the link navigate to ember UI (clusters list page) in the **same** tab. 
* When in Cluster Explorer, add in a cluster manager button to the navigation bar, Clicking on it navigates to the ember UI (cluster overview page) in the same tab.
