### ISSUE TITLE
When upgrading an RKE2 v1.24/v1.23 imported cluster, the link in the banner does not redirect to the applicable upgrading section in the known issues and limitations page

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#8442]
**Setup** 
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/cd1a71624a94de993d471ce8a643cf4d2dbb75a6
- Browser type & version: Chrome

**Describe the bug**

When upgrading an imported RKE2/K3s cluster, you get the following page:

![image](https://user-images.githubusercontent.com/52591819/225428614-7468c7f8-72d2-4278-84b6-4d9bac1dd923.png)

When clicking the link, you get taken to the top of the known issues and limitations [documentation](https://docs.rke2.io/known_issues). The issue here is that as a user, when I click the link, I am not expecting to get taken to the top of this page. The page itself has a section on `Upgrading Hardened Clusters from v1.24.x to v1.25.x`; I would expect to be taken directly there.

Since Rancher cannot determine if I am using a hardened cluster or not due to it being imported, it's up to me as the user to know if this section is applicable. However, it's still worthwhile to me being directed exactly to that section so I can understand if I have to proceed or not.

**To Reproduce**

1. In a terminal, setup a 3 node, RKE2 v1.24 cluster (I did 1 server, 2 agent nodes).
2. As a standard user, navigate to Rancher > Cluster Management > Import Existing.
3. Import the previously constructed RKE2 cluster; validate that the cluster and nodes come up as `Active` in Cluster Management and Cluster Explorer.
4. Edit the cluster configuration to update the K8s version to v1.25.
5. Attempt to upgrade and note the warning banner that appears.
6. Click the link and note you're taken to the top of the known issues and limitations page.

**Result**
I am taken to the top of the known issues and limitations page.

**Expected Result**

I should be redirected to the `Upgrading Hardened Clusters from v1.24.x to v1.25.x` of the RKE2 known issues and limitations page.

**Comment by mantis-toboggan-md** [comment]
Currently no way to do this - waiting on this small docs change: https://github.com/rancher/rke2-docs/pull/65

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.7-head` https://github.com/rancher/rancher/commit/a841a9e101ae601a033fa8b39342ad4800c91d85.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/a841a9e101ae601a033fa8b39342ad4800c91d85
- Branch tested: `release-2.7.2`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, attempt to upgrade an imported cluster and validate that the shared link specifically goes to the expected, applicable sub-section|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. In a terminal, setup a 4 node, RKE2 v1.24 cluster (3 server nodes, 1 agent node).
2. As a standard user, navigated to Rancher > Cluster Management > Import Existing.
3. Imported the RKE2 cluster and validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
4. Edited the cluster configuration to update the K8s version to v1.25.
5. Attempted to upgrade and validated that I see the following banner:
![image](https://user-images.githubusercontent.com/52591819/225699347-66f2d479-ec96-4419-acf6-7ba96c3b6e83.png) 
6. Clicked the link and was redirected to this section as expected:
![Mar-16-2023 09-43-56](https://user-images.githubusercontent.com/52591819/225699511-b385fa7d-a582-449d-ad87-ed144f90df82.gif)
