### ISSUE TITLE
PSA verbiage in the RKE2 v1.25 custom cluster page is inconsistent with one another and causes confusion 

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#8443]
**Setup**
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/cd1a71624a94de993d471ce8a643cf4d2dbb75a6
- Browser type & version: Chrome

**Describe the bug**

The verbiage when upgrading a hardened custom RKE2 v1.24/v1.23 cluster to v1.25 or provisioning a fresh RKE2 v1.25 custom cluster is inconsistent and needs a bit more clarity. As of now, you see the following:

![image](https://user-images.githubusercontent.com/52591819/225430879-78af6ed8-5649-4d57-b0a7-ab1f27221aca.png)

There are two points here:
1. `Allow PSA Default Template` wording is inconsistent + makes me as a user question what is a PSA Default Template.
2. `PSACT is now set to Rancher default automatically` makes me as a user question what is Rancher default.

To get past the two points above, we should reword each to the following:

1. `Allow Pod Security Admission to be overridden when using a CIS Profile`
2. `Pod Security Admission is now set to rancher-restricted automatically`

**To Reproduce**

1. As a standard user, navigate to Cluster Management > Create > Custom.
2. Attempt to provision a custom RKE2 v1.25 cluster (1 etcd, 1 cp, 1 worker) with CIS profile set to `cis-1.23`.
3. Take note of the two messages that appear as described in the issue.

**Result**
The naming convention of PSA has different names from one another and causes confusion.

**Expected Result**

1. `Allow Pod Security Admission to be overridden when using a CIS Profile`
2. `Pod Security Admission is now set to rancher-restricted automatically`

**Comment by mantis-toboggan-md** [comment]
There is another issue to update the label on the PSA dropdown to `Pod Security Admission Configuration Template` which I think would clear up any confusion around the checkbox label (https://github.com/rancher/dashboard/issues/8426#issuecomment-1466933984) 

>PSACT is now set to Rancher default automatically makes me as a user question what is Rancher default.

This I just disagree with. The user can tell what the default value is because it's in the disabled input right below the banner; removing 'Rancher default' is just giving them less information.

**Comment by mantis-toboggan-md** [comment]
What might a user think the PSACT value is in this scenario if not `rancher-restricted`? There is no other input or info box or anything else on the page suggesting the PSACT is anything other than what is shown in the disabled field that is located directly below the info banner. I don't see any room for interpretation there. If a person can't understand that a value automatically filled in an input is a default value they are going to be confused by almost every form in the UI; we have made the assumption a thousand times over that our users have at least that level of computer literacy.

**Comment by markusewalker** [comment]
@mantis-toboggan-md I understand your point completely, no worries there. I was speaking more so for users to read `Rancher default` and them not directly associating with the disabled field below. If we're confident majority will not have that issue, we can leave as is, I have no problem with that.

If you agree with that, I'll just validate the first verbiage enhancement and then proceed with issue validation + closure.

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/05140546616e90cdc2ae78eb273013c582b7573c.

**ENVIRONEMNT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/05140546616e90cdc2ae78eb273013c582b7573c
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|As a standard user, validate that the verbiage in RKE2 custom cluster is clear when setting a CIS profile|:white_check_mark:|

**Scenario 1**
1. As a standard user, navigated to Cluster Management > Create > Custom.
2. In the `Security` section, enabled `cis-1.23` as the CIS Profile and noted the following:
![image](https://user-images.githubusercontent.com/52591819/225982298-b5b0819f-4914-40f5-ad6e-9c1fb42a71d7.png)
3. Noted that the checkbox is more clear from a user perspective.
     - As per this issue's conversations, we will be leaving `Rancher default` as is.
