### ISSUE TITLE
Global Nav Bar - No longer able to navigate back to Ember UI

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#845]
Rancher version `master-head (07/14/2020)` _691feb01a_ k8s HA install
dashboard-index -> `latest`

1. Deploy cluster
2. Navigate to Dashboard

Result:

There's no way to navigate back to Ember UI anymore in the new Global Nav Bar. Previously there was a `Back to Rancher` link.

**Comment by vincent99** [comment]
This is intentional; it will be a "product" in the top-left dropdown (soon).
