### ISSUE TITLE
Cannot edit imported cluster after creation

### ISSUE THREAD

**Issue by cmurphy** [rancher/dashboard#8452]
**Setup**
- Rancher version: v2.7-head 8835c43
- Browser type & version: Google Chrome 108.0.5359.124

**Describe the bug**

I cannot make edits to an imported cluster after the cluster has been imported. This means I cannot add or remove a user, label or annotation, or set environment variables once the cluster has been imported..

**To Reproduce**

1. Create a user user1.
2. In Cluster Management, import a cluster. Do not add any members.
3. After the cluster is saved, select it and go to "Edit Config". Does not matter if the cluster is done provisioning or not.
4. Under Member Roles, click Add Member, select user1 and any default role. Click Save.

**Result**

The Save button changes to "Saving" with the spinning icon forever. In developer tools, no request has been made, so there is nothing that it is waiting for.

**Expected Result**

An update request should be made and the screen should return to the cluster list, and changes to the cluster should be saved.

**Screenshots**

![image](https://user-images.githubusercontent.com/1220710/225754433-66d122fb-6206-46e5-ab13-145a80b2aabf.png)

**Additional context**

This isn't a problem for any created cluster, RKE1 or RKE2, only imported clusters.

**Comment by mantis-toboggan-md** [comment]
I wasn't able to reproduce this on a fresh setup. It looks like a fix went in for this issue a few weeks ago (https://github.com/rancher/dashboard/issues/8278), but your rancher version is new enough you should have picked that up... 
If you right click>view page source, can you confirm you're loading content from `https://releases.rancher.com/dashboard/release-2.7.2/...` ?
Also, are there any errors in the console?

**Comment by cmurphy** [comment]
I tried again on this morning's 2.7-head image which is 0514054. ui-index is https://releases.rancher.com/ui/release-2.7.2/index.html, ui-dashboard-index is https://releases.rancher.com/dashboard/release-2.7.2/index.html. ui-offline-preferred is "Dynamic". The error in the console is

```
parse-version.js:18 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at e.satisfies (parse-version.js:18:1)
    at e.<anonymous> (component.js:141:1)
    at index.js:1918:1
    at e.untrack (validator.js:842:1)
    at Te.get (index.js:1917:1)
    at e.n [as needsUpgradeWarning] (index.js:1007:1)
    at _e (index.js:1375:1)
    at Object.we [as get] (index.js:1359:1)
    at e.promptUpgradeWarning (component.js:63:1)
    at e.send (action_support.js:18:1)
```

**Comment by mantis-toboggan-md** [comment]
Thank you Colleen, that console error was helpful; I have a PR up for this now
