### ISSUE TITLE
Fleet: new checkbox to enable GitRepos

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8455]
Internal reference: SURE-6037

Quoting @mattfarina:

> The fleet change to accommodate the request is to put a flag on GitRepo to keep the resource when deleted. By default they will be deleted as they are today. One opts in to keeping them. Fleet will remove the Helm chart without uninstalling any resources. If the Helm chart is reinstalled into the cluster with resources in the same namespace with the same names, the new chart instance will pick them up. If the name/namespace has a collision there will be an error to correct but the workloads will keep running.

> This new flag will be exposed in the Rancher UI screen for GitRepos. GitRepos are an existing screen in the dashboard.

**Comment by gaktive** [comment]
Related Fleet PR: https://github.com/rancher/fleet/pull/1382

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 1f014b7`
1. navigate to local cluster
2. search for 'git repos'
3. create repo
4. new section `resource handling` has checkbox `keep resources after deletion`

![2023-05-09_11-32-49.png](https://zube.io/files/rancher/42f9c2434e639dde41a9c1a5a94fb9b3-2023-05-09_11-32-49.png)
