### ISSUE TITLE
secrets unveiled in Rancher GUI when RBAC verbs is only "list"

### ISSUE THREAD

**Issue by phillowAT** [rancher/dashboard#8461]
**Setup**
- Rancher version: 2.7.x
- Browser type & version: Chrome

**Describe the bug**
When setting up RBAC in a way that read-only user can list but not get secrets, this is respected from CLI, but Rancher GUI still shows cleartext and base64 values.

**To Reproduce**
setup a roletemplate with:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list

map a user to a project with RBAC above
test by navigating into an existing secret

**Result**
secret values are base64 OR cleartext available
**Expected Result**
user cannot enter the detail page for secrets; working as such in CLI

**Screenshots**
![image](https://user-images.githubusercontent.com/16717297/225934555-59d7e276-3846-4c9f-baa3-0b99476c9708.png)

**Additional context**

**Comment by richard-cox** [comment]
Unfortunately this is the way native k8s works. 

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb

```Caution: The get, list and watch verbs can all return the full details of a resource. In terms of the returned data they are equivalent. For example, list on secrets will still reveal the data attributes of any returned resources.```
