### ISSUE TITLE
Digital Ocean Node Template pagination calls broken, unable to create Digital Ocean Node Template

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8465]
Internal reference: SURE-6021
Reported in 2.7.1 & 2.6.11

Issue description:
It is not possible to load the Digital Ocean Node Template form if any of the Digital Ocean API requests return more than a single page. This is true for the 'sizes' request with the Rancher Support Digital Ocean account, which returns 107 sizes. This may possibly not be encountered for other Digital Ocean accounts which are newer and where this query does not return some older now deprecated size options.

This appears to be the result of https://github.com/rancher/ui/blob/v2.7.1/lib/shared/addon/digital-ocean/service.js#L46 where apiRequest does not exist for the digitalOcean service. This itself appears to be the result of a copy and paste from a different component such as https://github.com/rancher/ui/blob/v2.7.1/lib/nodes/addon/components/driver-packet/component.js#L149

I belive this should be resolved by updating https://github.com/rancher/ui/blob/v2.7.1/lib/shared/addon/digital-ocean/service.js#L46 to `return this.request(auth, command, opt, out).then(() => {`

Business impact:
Unable to provision RKE Digital Ocean Node Driver clusters

Repro steps:

- Provision a Rancher v2.7.1 instance
- Create a Digital Ocean Cloud Credential
- Attempt to configure a Digital Ocean Node Template
- After clicking 'Next: Configure Droplet' observe that button just spins on Loading
- In the developer tools observe the request to https://<rancher_url>/meta/proxy/api.digitalocean.com/v2/sizes?per_page=100 returns over 100 results [excerpt]

```
"links":{"pages":{"next":"https://api.digitalocean.com/v2/sizes?page=2\u0026per_page=100","last":"https://api.digitalocean.com/v2/sizes?page=2\u0026per_page=100"}},"meta": {"total":107}
```
but there is no request for the second page

- Adding a breakpoint in the browser developer tools below `}, function (err) {` in the component.js file observe err with value of the following format when clicking 'Next: Configure Droplet`:

```
TypeError: e.apiRequest is not a function
at https://68.183.6.66/assets/vendor-3e7e4a452ef5e41a29a6624fdd708d4b.js:21733:111
at v (https://68.183.6.66/assets/vendor-3e7e4a452ef5e41a29a6624fdd708d4b.js:5235:12)
at b (https://68.183.6.66/assets/vendor-3e7e4a452ef5e41a29a6624fdd708d4b.js:5233:128)
at t.invoke (https://68.183.6.66/assets/vendor-3e7e4a452ef5e41a29a6624fdd708d4b.js:4756:163)
at t.flush (https://68.183.6.66/assets/vendor-3e7e4a452ef5e41a29a6624fdd708d4b.js:4748:74)
at t.flush (https://68.183.6.66/assets/vendor-3e7e4a452ef5e41a29a6624fdd708d4b.js:4762:207)
at n._end (https://68.183.6.66/assets/vendor-3e7e4a452ef5e41a29a6624fdd708d4b.js:4825:9)
at _boundAutorunEnd (https://68.183.6.66/assets/vendor-3e7e4a452ef5e41a29a6624fdd708d4b.js:4776:574)
```

@axeal has a proposed Ember PR to fix this: https://github.com/rancher/ui/pull/4990

**Comment by Josh-Diamond** [comment]
Ticket #8465 - Test Results - ✅ 
---

With Docker on a single-node instance using Rancher `v2.7-41aa9a7d8fc9b7508b23ed52b34a3afa4cee64dd-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Navigate to `Cluster Management > RKE1 Config > Node Templates > Add Node Template` and create a DO node template, then provision a downstream cluster using this template | ✅ |
| 2. | Navigate to `Cluster Management > Create`, create a DO node template + provision a downstream cluster w/ template | ✅ |

---

Scenario 1:
1. Fresh install of rancher `v2.7-head`
2. Navigate to `Cluster Management > RKE1 Config > Node Templates > Add Node Template` and create a DO node template
3. Verified - template successfully created
4. Provision a downstream cluster using node template created in step 2
5. Verified - template valid and cluster successfully provisions

---

Scenario 2:
1. Fresh install of rancher `v2.7-head`
2. Navigate to `Cluster Management > Create` and provision a downstream RKE1 DO cluster (using a new node template created specifically for this cluster)
3. Verified - node template successfully created + cluster successfully provisions - [as expected]
