### ISSUE TITLE
Continuous Delivery - User with custom role with access to only list GitRepos can see the Add repo UI elements

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#8467]
**Setup**
- Rancher version: `v2.7-head` `a49d36c`
- Fleet version: `v0.6.0-rc.5`
- Browser type & version: `Firefox` `Chrome`

**Describe the bug**

A user with permissions to only list GitRepos is shown the Add Repository UI elements.

**To Reproduce**

- Add a new user role with all permissions (create, delete, list, etc) on `fleetworkspaces` resources.
- Add access to `gitrepos` resources but only to `list`

**Result**

The user see the add repositories UI elements.

Both cases:
- GitRepos exist
- GitRepos do not exist

The user can't add the GitRepo as expected. With error: `<user> is not able to add the repository as expected. ("Method POST not supported")`

**Expected Result**
Access to the existing GitRepos list, but no add repository elements.

**Comment by bmdepesa** [comment]
Reopening for testing

**Comment by izaac** [comment]
@mantis-toboggan-md Closing as validated.

I've opened a separate issue for the workspaces elements I am still seeing if a user doesn't have permissions on `fleetworkspaces`
https://github.com/rancher/dashboard/issues/8624
