### ISSUE TITLE
Continuous Delivery - User with custom role can't edit allowedTargetNamespaces throws error

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#8468]
**Setup**
- Rancher version: `v2.7-head` `a49d36c`
- Fleet version: `v0.6.0-rc.5`
- Browser type & version: `Firefox` `Chrome`

**Describe the bug**

A user with custom role to ` list, create, update and get` on `fleetworkspaces` resources can't edit an existing `workspace` when adding an `allowedTargetNamespaces`

**To Reproduce**

- Add a new user role with permissions to `list, create, update and get`  on `fleetworkspaces` resources.
- Create a new `workspace` with blank `allowedTargetNamespaces`
- Edit the created workspace and try to add `allowedTargetNamespaces`

**Result**

`Cannot read properties of undefined (reading 'linkFor')`

**Expected Result**
The user with permissions to `fleetworkspaces` can edit a workspace's `allowedTargetNamespaces` successfully.

**Comment by nwmac** [comment]
@mantis-toboggan-md The user will need permissions on GitRepoResource for this to work. The UI will need to check that the user has access to this resource. @Shavindra Did you not check this situation?

**Comment by izaac** [comment]
Validated working on:

Dashboard version: `release-2.7.2 d1ea2d47b`
Rancher version: `v2.7-head-4a9b7ba`
Fleet version: `fleet-agent:v0.6.0-rc.5`
