### ISSUE TITLE
Extension API issues

### ISSUE THREAD

**Issue by tedsync** [rancher/dashboard#8472]
I found the following issues in ui-plugin-examples:
- None of the addPanel extension APIs work: nothing is displayed
- addTableColumn works in example, it works also on catalog.cattle.io.clusterrepo, but not on fleet.cattle.io.cluster or fleet.cattle.io.gitrepo for example. Am I wrong in this case?
Thanks in advance for any help.

**Comment by richard-cox** [comment]
@aalves08 can you validate these are resolved in 2.9.0?

**Comment by aalves08** [comment]
@richard-cox this is a 2 part issue/comment/question:

- Regarding `addPanel`, in 2.8.1 they work fine (I built the `extensions-api-demo` pkg, served it using it `yarn serve-pkgs` then installed in my remote Rancher instance `2.8.1`. Here are the screenshots:

<img width="1782" alt="Screenshot 2024-02-15 at 16 53 14" src="https://github.com/rancher/dashboard/assets/97888974/cd2fc8b9-2298-4670-9ba3-88c97d058b6f">
<img width="1782" alt="Screenshot 2024-02-15 at 16 53 22" src="https://github.com/rancher/dashboard/assets/97888974/873fea83-3e54-4270-9d59-b156e14e5212">
<img width="1782" alt="Screenshot 2024-02-15 at 16 53 25" src="https://github.com/rancher/dashboard/assets/97888974/a45f1181-4e67-439f-84f9-281451617392">
<img width="1782" alt="Screenshot 2024-02-15 at 16 53 35" src="https://github.com/rancher/dashboard/assets/97888974/563df036-e27c-4301-bf55-d21f079d2673">

- As for targeting resources like `fleet.cattle.io.cluster`, it also works (running the same code as `extensions-api-demo`, but just targeting a different resource - I don't have items on the list but the header is there):
<img width="1782" alt="Screenshot 2024-02-15 at 16 58 30" src="https://github.com/rancher/dashboard/assets/97888974/424dc856-4fdd-4f32-9e78-5c131a6b185b">

I've hit problems in the past where we couldn't target certain pages as they aren't "pure k8s resources" but along the way I've extended the [LocationConfig](https://rancher.github.io/dashboard/extensions/api/common#locationconfig) spec to cover those edge-cases as I found them. The above screenshot was taken without an update in `shell`, meaning that this repo is running a very outdated version of shell which might not even include that additional coverage added ( `0.3.29` vs `0.5.2`), but again it works without any special usage of `LocationConfig`.

My opinion is that this issue should be closed 🙏

**Comment by richard-cox** [comment]
Thanks @aalves08 .

@tedsync if using the versions above (or later) you still experience issues just let us know via a new gh issue
