### ISSUE TITLE
[RKE2][Enhancement] - Create minimized section for Dynamic Schema spec section in `edit YAML` page

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/dashboard#8496]
**Setup**
- Rancher version: v2.7-head 2b2ed44
- Browser type & version: Chrome Build 110

**Describe the bug**

There recently was a change due to an azure bug where there is now a Dynamic Schema spec section that takes a huge chunk of the yaml page when you edit in the UI. It looks messy and would be nice if we could have the minimize option like some of the other configs on the `edit YAML` page.

**To Reproduce**

1. Create rke2 downstream cluster
2. Check the `edit YAML` page
3. Scroll down to `dynamicSchemaSpec` section

**Result**
There is a huge chunk of specs that just doesn't look so pleasant to see. The user doesn't really need to interact with this section as this section is generated and updated automatically.

**Expected Result**

Could we create a minimized section like the image below?
![image](https://user-images.githubusercontent.com/108360907/226924986-efbf6783-7e47-4d84-bd7e-d0ecbca72340.png)

**Comment by gaktive** [comment]
Upon analysis, this isn't a quick thing to fix since this likely ties into 3rd party libraries we use. Bumping out.

**Comment by gaktive** [comment]
Ties into SURE-6492 as an internal reference.

**Comment by izaac** [comment]
The data appears minimized as expected on `v2.9-637346f76ea2bb71a82ea6e00a2779f61610a2a4-head`
The data can also be unfolded by clicking on the "arrow" indicator.
Tested on an RKE2 cluster with 3 pools.
