### ISSUE TITLE
Action menu throws unhandled exception

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#8499]
It looks like this issue was introduced rancher/dashboard#8232

@rak-phillip I've found an issue with this branch (non-reproducible on a branch derived from `release-2.7.2` nor in `master`) in an `ActionMenu` item on the extensions panel. The rest seems good to me. I tested install, uninstall, update, rollback, etc, and all worked fine.

![Screenshot 2023-03-22 at 15 59 06](https://user-images.githubusercontent.com/97888974/226966155-a55ca2e3-0f2c-4eb3-9dd3-0376dbf34e96.png)

_Originally posted by @aalves08 in https://github.com/rancher/dashboard/pull/8466#pullrequestreview-1352989060_

**Comment by gaktive** [comment]
Engineering to help QA by writing an automated test in #8807
