### ISSUE TITLE
Not possible to install Istio chart without specific namespace

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8506]
**Setup**
- Rancher version: 2.7.2
- Browser type & version: Chrome

**Describe the bug**
Not possible to install Istio chart without specific namespace.

**To Reproduce**
Install Istio without namespace.

**Result**
Error received: `namespaces "istio-system" not found`

**Expected Result**
It installs

**Screenshots**
![Screenshot 2023-03-23 at 14 48 26](https://user-images.githubusercontent.com/5009481/227224295-fa37a4ba-2648-491e-9dd9-4a71577b9e30.png)

**Additional context**

**Comment by gaktive** [comment]
This is a candidate to pull back into Q3 if there's time.

**Comment by richard-cox** [comment]
We have a team confluence page with some minor details about charts and annotations. There's also the public docs https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps. First breadcrumb would be to confirm the charts `catalog.cattle.io/namespace` annotation

**Comment by torchiaf** [comment]
Adding e2e tests: https://github.com/rancher/dashboard/issues/9719
