### ISSUE TITLE
Project owners/cluster members get permissions errors when adding members/groups when PSPs are enabled

### ISSUE THREAD

**Issue by bentastic27** [rancher/dashboard#8508]
It appears that there needs to be a global permission missing when project/cluster owners add users or groups to clusters/projects when PSPs are enabled

error creating binding: Forbidden 403: podsecuritypolicytemplateprojectbindings.management.cattle.io is forbidden: User "u-b4xv6mhhxu" cannot create resource "podsecuritypolicytemplateprojectbindings" in API group "management.cattle.io" in the namespace "c-7ldp6

Steps to reproduce:

1. enable PSPs on a cluster
2. create project owner and project member users
3. Create a project and set the PSP on the project to 'unrestricted'
4. add the project owner user as an owner of a project
5. log in as the project owner and edit the project to add the project member

You'll be faced with that error, but the project member will be added. It doesn't seem to do this when you navigate to the project and use the members page, only when editing the project to add users that way.

This same behavior seems to also happen when cluster members create projects when PSPs are enabled. Not sure if this should be considered a separate issue.

gz#16350
gz#16365

**Comment by gaktive** [comment]
Internal reference: SURE-3015

**Comment by bguzman-3pillar** [comment]
Reproduced using `v2.7.3`
Validated using `v2.7-head`

Steps:
1. enable PSPs on a cluster
2. create project owner and project member users
3. Create a project and set the PSP on the project to 'unrestricted'
4. add the project owner user as an owner of a project
5. log in as the project owner and edit the project to add the project member

Validate:

![image](https://github.com/rancher/dashboard/assets/95362932/9387aec9-d693-49ed-b41a-2293d47c64db)
