### ISSUE TITLE
Dashboard - 404 thrown in dashboard latest on Rancher master

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#852]
Rancher version: `master-head (07/15/2020)` _fd3826a19_
dashboard-index -> `latest`

![Screen Shot 2020-07-15 at 3 06 47 PM](https://user-images.githubusercontent.com/27659/87603346-d5b05880-c6ac-11ea-96d6-fa19e2c79e07.png)

```js
Failed to load resource: the server responded with a status of 404 ()
index.js:245 Loading error Error
    at y.setError (index.js:243)
    at vuex.esm.js:840
    at vuex.esm.js:462
    at Array.forEach (<anonymous>)
    at vuex.esm.js:461
    at y._withCommit (vuex.esm.js:620)
    at y.commit (vuex.esm.js:460)
    at y.commit (vuex.esm.js:405)
    at authenticated.js:127
    at d (runtime.js:45)
```

**Comment by vincent99** [comment]
@izaac Presumably this doesn't happen anymore..

**Comment by izaac** [comment]
Yes, this is no longer happening in Rancher version `master-head (07/31/2020)` _69bdef3ea_
