### ISSUE TITLE
Pressing `Enter` in `textarea` elements not working

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#8550]
**Setup**
- Rancher version: `master-528d7d94c`
- Browser type & version: any

**To Reproduce**

- Go to local -> Storage -> ConfigMaps
- Create a new ConfigMap
- Add a new entry in Data form
- Select `value` field and press `Enter`

**Result**

Nothing happens

**Expected Result**

A new line should be added to the value.

**Additional Info**
This is a regression of https://github.com/rancher/dashboard/pull/7267
Possible related issue: https://github.com/rancher/dashboard/issues/8470

**Comment by cnotv** [comment]
Did you ask @kwwii about having different behaviors in a form? I think it would be better to always remove this prevention.
There may also be a side issue with submitting the form on enter somewhere else.
@kwwii Should we create a separated issue to discuss UX submission everywhere, so we do not block this?

**Comment by kwwii** [comment]
At first glance, it presents two behaviours that would be hard to learn and confusing for users.

I am unsure if we need another ticket for this (yet). 

Does this change present a new behaviour which is not common to other similar fields?

**Comment by cnotv** [comment]
Yes it should submit if you press enter in other input fields which are in the same form.

**Comment by gaktive** [comment]
Engineering to write an automated test for this in #8817 to help QA.
