### ISSUE TITLE
Members cluster ClusterRoleTemplateBindings and does not display in dashboard UI properly

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#8554]
### Setup
- Rancher version: 2.7.2

### Describe the bug
This partly related to https://github.com/rancher/dashboard/issues/7582 - Highlighted number of issues in ember UI.

This Issue looks at the cluster explorer specific issues. However, issues persists on the cluster explorer dashboard page as well.  

#### Broken RBAC ClusterRoleBindings
1. Cluster Explorer > Cluster > RBAC > Cluster Role Bindings
2. Role, Users, Groups, Service accounts are empty.
3. List page should show users, groups and service accounts

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/1387263/228583102-422a88d8-fc73-4ded-b58b-504484290d0e.png">

#### Cluster Membership Role display
1. Cluster Explorer > Cluster > Cluster membership
2. Add a user with multiple custom roles.
3. It shows one long list of members per roles. Sometimes its not clear which roles would show and which order.
4. Allow flat list, namespace and cluster role grouping.

#### Cluster Project Membership Role display
1. Cluster Explorer > Cluster > Cluster and project members.
5. When user have a multiple roles it create multiple roles.
6. Display all roles per user per project.

**Comment by bguzman-3pillar** [comment]
Reproduced using `v2.7.3`

- RBAC ClusterRoleBindings
![image](https://github.com/rancher/dashboard/assets/95362932/bc8cbd3c-934c-406c-92ce-3089c35881f3)

- Cluster Membership Role display
![image](https://github.com/rancher/dashboard/assets/95362932/8cf3342b-fa7c-46f3-828f-07bbe85efc65)

- Cluster Project Membership Role display
![image](https://github.com/rancher/dashboard/assets/95362932/090bb531-2c1e-4e69-b03f-c4844841fcb7)


--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------


Validated using `v2.7-head` (95edd02)

RBAC ClusterRoleBindings
- List page should show users, groups and service accounts

![cl_RBAC_showingData](https://github.com/rancher/dashboard/assets/95362932/5ba3c5ad-e984-4de2-bca2-9ff0275e8d6e)
![image](https://github.com/rancher/dashboard/assets/95362932/cbaa7328-351d-4aa9-af36-2514ebf7f9ac)



Cluster Membership Role display
- In the Cluster Membership list page click on the different grouping options on top right.


![cl_members_byFlatList](https://github.com/rancher/dashboard/assets/95362932/2f0fcdc5-706f-4c9f-b876-4c67642536e3)
![cl_members_byNames](https://github.com/rancher/dashboard/assets/95362932/bd3a5ef1-9f3b-47a9-9e35-fec286d4d30e)
![cl_membership_byRole](https://github.com/rancher/dashboard/assets/95362932/ff38401a-cef1-4728-b666-596faee58c03)


Cluster Project Membership Role display
- In the Project Membership list page you'd notice that all roles are grouped together.
- Clicking on a X for each role should remove that role from the user

![cl_projmemb_addtags](https://github.com/rancher/dashboard/assets/95362932/f7c3b614-154f-4fc2-a4d3-90e0270d35fb)
![cl_projmemb_moretags](https://github.com/rancher/dashboard/assets/95362932/93206939-fa68-4f86-b923-3ab5aaad1ba2)
