### ISSUE TITLE
custom ingress classes wont show up in dropdown when created from the ingress 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#8556]
Setup

Rancher version: 2.7-head aa7bea9
Browser type & version: Chrome

**Describe the bug**
when we create a custom ingress class while creating an ingress , the ingress class won't show up in the UI from drop down of the ingresses 

**To Reproduce**
1. Create a standard user - u1 and u2
2. Create an rke1 or rke2 cluster node driver - 1 etcd + cp and 1 worker.
3. As a cluster owner/project owner 
4. created a cluster IP service from cluster explorer >> Service Discovery >> Services 
5. Create an ingress from the Ingresses page and select the above service in the target Service 
6. Created an ingress class from Ingress class page on the ingress page by typing a custom name

**Result**
Noticed that once the ingress class is created, it doesn't show up in the drop down if we edit the ingress and try to create a new one.
Notice in the screenshot current ingressclass is custom but its not listed in the kubectl:

 kubectl doesn't return the created ingress class:
```
> k get ingressclass -A
NAME    CONTROLLER             PARAMETERS   AGE
nginx   k8s.io/ingress-nginx   <none>       5h57m

```

**Expected Result**
Custom created ingress shows up in the dropdown.

**Screenshots**

<img width="836" alt="2023-03-28_16-30-38" src="https://user-images.githubusercontent.com/38144301/228389635-f8668201-51e5-4868-a3fd-14550aa62751.png">

**Comment by mantis-toboggan-md** [comment]
This is working as expected. Ingress classes require `spec.controller` to be defined so they can't be created on the fly by inputting a name. That field allows the user to manually input an ingress class name so that users who can't get/list ingress classes can still make ingresses that reference a class that they know exists - see comment [here](https://github.com/rancher/dashboard/pull/7249#issuecomment-1286723238)

**Comment by gaktive** [comment]
Putting back on QA's plate to either close or then petition for a fix, though if that's the case, it won't be for 2.7.2; it'd be Q2 or later.

**Comment by anupama2501** [comment]
Thanks @mantis-toboggan-md . Closing since it is expected.
