### ISSUE TITLE
PSP value in custom charts is not kept on submission

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8566]
**Setup**
- Rancher version: 2.7.2rc7
- Browser type & version: Any

**Describe the bug**
While editing cluster charts the PSP enabled value is not kept while it's still visible in the YAML editor or data.

**To Reproduce**
- Provision cluster K8S 1.24.x
- Install custom chart (e.g. monitoring) 
- Enable PSP checkbox
- Save

**Result**
PSP is disabled.

**Expected Result**
PSP value is still enabled.

**Screenshots**

![image](https://user-images.githubusercontent.com/5009481/228751754-56193637-60bf-406e-b156-5ee98fc47d1b.png)
![image](https://user-images.githubusercontent.com/5009481/228751783-71498013-6043-4b96-ab0a-b8a875196a0f.png)
![image](https://user-images.githubusercontent.com/5009481/228751858-525bc978-e138-4c7b-8f67-84ec4d3ba6af.png)

**Additional context**

**Comment by cnotv** [comment]
@nicholasSUSE Just because I was investigating possible latest changes, I have been searching the release v2.7.2-rc5 but we don't have one 🤔 

![Screenshot 2023-03-30 at 11 12 43](https://user-images.githubusercontent.com/5009481/228789411-1e33021c-6bb3-4183-bf60-b5edff62d57f.png)

Given that I tested pointing to:
- [v2.7.2-rc4 HEAD](https://github.com/rancher/dashboard/commit/7aade7e): it works
- [v2.7.2-rc6 HEAD](https://github.com/rancher/dashboard/commit/4065709): it does not work

It means that the changes are not related to https://github.com/rancher/dashboard/issues/8434

**Comment by mantis-toboggan-md** [comment]
Testing steps:
1. Provision a cluster with k8s version < 1.25
2. 'Explore' cluster, navigate to 'Apps and Marketplace', select monitoring
3. Select install, check the 'enable PSP' option 
4. Navigate to Installed Apps, select the monitoring app, select the 'values YAML' tab
5. Verify that `global.cattle.psp.enabled` is set to `true`
6. Repeat 1-5 but uncheck 'enable PSP' and verify that `global.cattle.psp.enabled` is set to `false`

**Comment by mantis-toboggan-md** [comment]
Closing this as a duplicate of https://github.com/rancher/dashboard/issues/8612
