### ISSUE TITLE
Dashboard becomes unresponsive if a cluster is hung in a deleting state 

### ISSUE THREAD

**Issue by brooksphilip** [rancher/dashboard#8569]
**Setup**
- Rancher version: 2.7.1
- Browser type & version: chrome, safari

**Describe the bug**
When I had a harvester downstream cluster provisioned through rancher stuck in a unresponsive state due to deleting harvester and not removing it from rancher first, the hamburger in the top left does not respond to a click.

**To Reproduce**
see above

**Result**
unresponsive hamburger 

**Expected Result**
responsive hamburger

**Screenshots**

![Screenshot 2023-03-30 at 11 12 45 AM](https://user-images.githubusercontent.com/56730922/228882742-50beba8a-060f-4bc0-9785-e27b7d36a42c.png)

**Additional context**

**Comment by richard-cox** [comment]
Resolved in 2.8.0 via https://github.com/rancher/dashboard/pull/9809 (https://github.com/rancher/dashboard/pull/9809/commits/60b15ad42909c082bd10b33512d9b3fafdf1f794).

Regarding testing, not sure where we want to go. This was fixed in 2.8.0 but needs some kind of validation
