### ISSUE TITLE
StorageClass - Create

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#857]
Related:
https://github.com/rancher/dashboard/issues/855

**Comment by deniseschannon** [comment]
Use a wizard to select StorageClass "type" and then set the options.
> Note: to the developer: Instead of individually creating each custom page for each type. You can build/create a questions.yml for each type and leverage what is being used for deploying applications to build the second step of the wizard. Talk to @vincent99 before implementation.

### Step 1: Select a Provisioner. Please select a provisioner from the list. If you do not see your provisioner, use the Custom provisioner. 

Unlike PVs, all the options in the old ember UI should be ported to dashboard. 

### Step 2: Configure the StorageClass. Configure the provider-specific parameters for the storage class.
### Step 3: Customize the StorageClass. Customize the advanced options.

**Comment by lvuch** [comment]
https://xd.adobe.com/view/40054d06-c741-4247-80f4-cdebd4c8c708-1556/

**Comment by deniseschannon** [comment]
- [ ] Update mocks to the new CruResource Wizard
- [ ] "Step 1" is the subtype of StorageClass
- [ ] "Step 2 and 3" would move into tabs
- [ ] Make sure to include Labels and Annotations

**Comment by lvuch** [comment]
Updated: https://xd.adobe.com/view/40054d06-c741-4247-80f4-cdebd4c8c708-1556/

**Comment by deniseschannon** [comment]
Closing in favor of new design until this is prioritized
