### ISSUE TITLE
Cannot load 'Members' page of Project in Rancher UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8574]
Internal reference: SURE-6071
Reported in 2.6.8

Issue description:
When attempting to view the 'Members' page of a project in Rancher, the page does not load, and one of two problems occurs:
- Either the load seems to 'time out' fairly quickly and no members are displayed
- or the page enters a continuous loop of calling the `projectroletemplatebindings` endpoint and never loads.
This is impacting users as they say that their projects have been created incorrectly as there are no members.

Sample environment: ~1500 users and ~1500 projects across 50+ clusters, SSD disks, Okta via Azure AD

Happening in Vue (new UI) not Ember (old UI) -- Ember brings up a members page quickly across multiple projects & clusters. 

Troubleshooting steps and data available upon request.

**Comment by gaktive** [comment]
Should see if some of our improvements for 2.7.2 help out here, so first step: repro and see if there's any difference between 2.6.8 and 2.7.2.

**Comment by jbilliau-rcd** [comment]
We are having this exact issue, I put in a case for it - 00503406. Randomly, when clicking on one of our 84 clusters, "Cluster Members" is blank for myself and other global admins. If I log in as a user explicitly tied to that cluster though, it works fine....so it seems specifically a problem for global admins.

**Comment by gaktive** [comment]
@Sean-McQ & @richard-cox can help out for whoever grabs this. This could be tied to getters and counts.

**Comment by gaktive** [comment]
@Sean-McQ if you feel this is still doable for Q2, including QA time, we can consider putting this back in. However, if the PR isn't merged by end of day Monday (June 5), then we can leave that for Q3.

**Comment by jbilliau-rcd** [comment]
It would be great to get this fixed asap. As a platform owner for 200+ clusters, this makes my job **extremely** difficult when I randomly cannot see who belongs to a cluster, what access they have, etc.

**Comment by gaktive** [comment]
Pushing to Q4 based on other escalations that have come in. A proper fix for this, as noted in the existing PRs, will take some time.

**Comment by MSpencer87** [comment]
Verified on Rancher 2.8.0-rc3

Member list loads correctly with correct project members, no console errors or failed API calls present

Steps to reproduce:
1. Bring up Rancher v2.6.8 on v1.24.2+rke2r1 (3 Nodes All Roles + 1 Worker)
2. Provision a single node, all roles downstream cluster
3. Create 150 Users, create 400 Projects
4. Add all created users to each project
5. Navigate to one of the created projects members page
6. Intermittent console errors upon viewing the members page directly, reloading page or selecting Edit Config results in long loading times 

Steps for validation:
1. Bring up Rancher on v2.8.0-rc3 on v1.26.9+rke2r1
2. Provision a single node downstream cluster
3. Create 150 Users, create 400 Projects
4. Add all created users to each project
5. Navigate to one of the created projects members page
6. Confirm browser console logs and network tab display no errors, page is responsive on initial load and subsequent reloads and selecting Edit Config
