### ISSUE TITLE
Cluster Management page gets stuck in loading for EKS clusters

### ISSUE THREAD

**Issue by kkaempf** [rancher/dashboard#8578]
#### Issue description:

Cluster Management page gets stuck in loading for EKS clusters

#### Troubleshooting steps:
we did the following:

1. Rancher logs showing some errors system-library-rancher-monitoring
2. Captured the HAR files for a working and not-working EKS cluster
3. Captured the error from the dev tools from the browser for a not-working EKS
4. Restarted Rancher pods

#### Actual behavior:
The cluster management page isn't loading

#### Expected behavior:
The cluster management page should be loading

![Screenshot 2023-04-05 at 08.38.07.png](https://zube.io/files/rancher/f3269de784a0124a9842866dcf505056-screenshot-2023-04-05-at-08-38-07.png)

**Comment by kkaempf** [comment]
Transferred on request from @gaktive

**Comment by cpinjani** [comment]
Validated the issue as fixed on build > v2.7.5-rc5

**To Reproduce**
- Create an EKS cluster in the AWS console on kube version supported by that Rancher release
- Import this cluster into Rancher as Standard User
- Go to the cluster information page.

**Result**

Reproduced on un-fixed version:
![image](https://github.com/rancher/dashboard/assets/73099870/146c34da-ec55-4753-8fe4-558021ad448e)

Able to import and check cluster information on fixed version:
![image](https://github.com/rancher/dashboard/assets/73099870/c4736652-5b6f-45c3-a254-09b14809190d)
