### ISSUE TITLE
Add helmRepoURLRegex field to the GitRepo create and update pages

### ISSUE THREAD

**Issue by raulcabello** [rancher/dashboard#8584]
**Is your feature request related to a problem? Please describe.**
Fleet recently added the [helmRepoURLRegex](https://github.com/rancher/fleet/issues/978) field to the `GitRepo` spec. There is no way to set this field in the UI at the moment.

**Describe the solution you'd like**
Users should be able to set and modify the `helmRepoURLRegex`  in the UI

**Comment by gaktive** [comment]
@kkaempf & @raulcabello when do you this need by? Q2 is already at capacity so what's the priority/urgency since we need to ensure QA has a test plan?

Based on all the details in the related Fleet ticket, a summary for UI would help us.

**Comment by gaktive** [comment]
Internal reference: https://jira.suse.com/browse/SURE-6477

**Comment by gaktive** [comment]
@kwwii to reach out to the Fleet team to understand more of the problem to solve here (cc: @kkaempf)

**Comment by gaktive** [comment]
Q4 is the actual deliverable here but we can work on the design in Q3.

**Comment by kwwii** [comment]
From discussion with Shavi - I think we need to add a HelmRepourlRegex input field similar to the RepositoryURL field. This new field should appear directly beneath the dropdown selector for the Helm Secret type.

**Comment by kwwii** [comment]
Does the new field only apply to secrets created in the fleet default namespace or is this applicable for/to all namespaces?

**Comment by kwwii** [comment]
Do we need to add this field to the create secret workflow for fleet workspaces?

**Comment by nwmac** [comment]
This field ONLY needs to go on the GitRepo create and update page.

See: https://fleet.rancher.io/ref-gitrepo

"Helm credentials from helmSecretName will be used if the helm repository url matches this regular expression."

Add a new input field under "Helm Authentication" - named "Helm Repository URL Regex for Helm Authentication"
![image.png](https://zube.io/files/rancher/220d01ca9f76317b93a9959d6c399160-image.png)

When "Helm Authentication" this new field is enabled and the user can set/edit it.

**Comment by gaktive** [comment]
Unit test or E2E could work here since the Gitrepo doesn't have to be legit.

**Comment by gaktive** [comment]
@Shavindra may have a suite for doing Gitrepo work though.

**Comment by sbulage** [comment]
This issue falls under the team/fleet no the team/highlander, I am moving it. Thanks :smile:
