### ISSUE TITLE
Have E2E in place to ensure that Rancher changes don't break extensions

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8588]
Sample: we'd have a test that loads an extension and then check the page.
@nwmac may have more ideas.

**Comment by richard-cox** [comment]
We have one for [Kubewarden](https://github.com/rancher/dashboard/blob/master/cypress/e2e/tests/pages/extensions/kubewarden.spec.ts). It...
- installs the extension
- checks for route collision
- checks Kubewarden appears in side nav
- checks clicking on it shows the KW dashboard

Think that's enough to cover this issue
