### ISSUE TITLE
enhancement: add `helmRepoURLRegex` to git repo creation workflow

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#8609]
**Setup**
- Rancher version: v2.7.2-rc7
- Browser type & version: chrome

**Describe the bug**

the variable `helmRepoURLRegex` is now available for fleet via yaml, but is not surfaced in the UI options

**To Reproduce**

deploy a `git repo` using continuous delivery / fleet through rancher

**Result**
no option for `helmRepoURLRegex` is available in the UI

**Expected Result**

`helmRepoURLRegex` should be available in the UI

**Screenshots**

**Additional context**

https://github.com/rancher/fleet/issues/978

**Comment by nwmac** [comment]
Duplicate of https://github.com/rancher/dashboard/issues/8584
