### ISSUE TITLE
Discrepancies between views of a chart's values.yaml

### ISSUE THREAD

**Issue by nickwsuse** [rancher/dashboard#8610]
**Setup**
- Rancher version: `v2.7.2-rc8`
- Browser type & version: `Chrome Version 111.0.5563.146 (Official Build) (arm64)`

**Describe the bug**
When viewing an installed chart's values.yaml, there appears to be discrepancies between two of the views of those values.

For example, if you install the Monitoring chart on a v1.24.10 RKE1 cluster with PSPs enabled (`global.cattle.psp.enabled=true`), you will see one view of the values.yaml will show that PSPs **_are_** enabled, and another view will show that they are **_not_** enabled.

Click the name of the chart -> Click Values YAML -> Shows that PSPs are enabled (`global.cattle.psp.enabled=true`)
Three Dots -> View YAML -> Shows that PSPs are not enabled (`global.cattle.psp.enabled=false`)

This isn't just for PSPs or the Monitoring chart either, I saw the same behavior with the Logging chart and trying to enable kubeAudit in the chart's values.yaml

**To Reproduce**
1. Create a downstream RKE1 cluster on v1.24.10 (3 workers, 1 control plane, 1 etcd)
2. Install the Monitoring chart with `global.cattle.psp.enabled=true`
3. After chart install, go to Apps -> Installed Apps
4. For the Monitoring chart, click the `three dots` to the far right of the app
5. Click `View YAML`
6. See that this view shows global.cattle.psp.enabled=false
7. Go back to the Installed Apps page
8. Click into the Monitoring chart
9. Click the `Values YAML` tab
10. See that this view shows global.cattle.psp.enabled=true
11. Go to More Resources -> Policies -> PodSecurityPolicies and see that PSPs are present for the Monitoring chart

**Result**
Different views of a chart's values.yaml file show different settings being enabled/disabled

**Expected Result**
Different views of a chart's values.yaml file show the same settings being enabled/disabled regardless of the view

**Screenshots**

Three Dots -> View YAML
![image](https://user-images.githubusercontent.com/107147272/229610303-37ae1a3f-3d8a-4396-89af-f348075e4f06.png)

![image](https://user-images.githubusercontent.com/107147272/229610407-5a99d199-ca6f-4e73-964a-cc152718f1fb.png)

Click Into Chart -> Values YAML

![image](https://user-images.githubusercontent.com/107147272/229610505-a1e963ff-7b56-4ca3-aa0a-20d17274ffbb.png)

**Comment by mantis-toboggan-md** [comment]
@nickwsuse could you clarify which part of the yaml is in the above screenshot taken from the 'view as yaml' view? I looked into what the Values YAML tab is showing and why, and found [this](https://github.com/rancher/dashboard/issues/1316#issuecomment-697172276) comment which I think explains what you're seeing: `<logging app>.spec.chart.values` lists default values for the chart, while `<logging app>.spec.values` lists any values the user has changed during install. The Values YAML tab of the detail view combines those two objects to show what values the chart was installed with (default values + whatever the user customized). 

So in this example `<monitoring app>.spec.chart.values.global.cattle.psp.enabled` would be the default, `false`, and `<monitoring app>.spec.values.global.cattle.psp.enabled` would be the value you've set, `true`. The Values YAML tab should show the value you set, `true`.

**Comment by gaktive** [comment]
https://github.com/rancher/rancher/issues/40998 is related, which ties into past Dashboard work in https://github.com/rancher/dashboard/issues/8566

**Comment by nickwsuse** [comment]
@mantis-toboggan-md here's the full screenshot that I cropped that section out of
![image](https://user-images.githubusercontent.com/107147272/229634136-0ded51da-71b1-4064-b04b-474d76999f36.png)

I suppose it makes sense that we would see one view that's the default values and one that is the actual value

**Comment by mantis-toboggan-md** [comment]
Thanks @nickwsuse - I think as long as `spec.values` shows any value changed during install this can be called 'working as intended'. I'll continue looking into the other matter of checking and un-checking the psp input in #8612

**Comment by cnotv** [comment]
Why are we talking about PSP and the screenshot is instead about another value? @nickwsuse

**Comment by cnotv** [comment]
@nickwsuse after installing monitoring, if I go in `View YAML` there's 83 results for PSP (actually the value seems changing sometimes).
All of them are set `true` except one. It seems like a server issue here.


https://user-images.githubusercontent.com/5009481/229760660-3c380995-f0f1-41a3-abe4-48108e95c2d4.mp4
