### ISSUE TITLE
[BUG] Chart Installs - Setting global.cattle.psp.enabled=true during install is not respected in the actual chart install

### ISSUE THREAD

**Issue by nickwsuse** [rancher/dashboard#8612]
**Rancher Server Setup**
- Rancher version: `v2.7.2-rc7`
- Installation option (Docker install/Helm Chart): `Helm` 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1 v1.24.10`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.24.10`
- Cluster Type (Local/Downstream): `both Local and Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `AWS EC2`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `Admin`
 
**Describe the bug**
When installing the monitoring chart `v102.0.0+up40.1.2` and setting the `global.cattle.psp.enabled=true`, the install completes but PSPs are not actually enabled. When looking for policies in the cluster there are only pod disruption budgets, and if you check the chart's yaml you'll find that the `global.cattle.psp.enabled` value is set to false.

**To Reproduce**
1. Create an HA on `v2.7.2-rc7`
2. Create a downstream AWS EC2 Cluster - `RKE1 v1.24.10` (3 workers, 1 control plane, 1 etcd)
3. Begin the install of the monitoring chart (`v102.0.0+up40.1.2`)
4. Before completing the install, edit the chart's yaml and set `global.cattle.psp.enabled` to `true`
5. Complete the chart install
6. Once the chart is done installing, check the cluster's policies
7. Check the monitoring chart's yaml

**Result**
PSPs are not enabled for the monitoring chart, even though the `global.cattle.psp.enabled` value is set to `true`

**Expected Result**
PSPs **are** enabled if `global.cattle.psp.enabled` is set to true on a cluster with k8s v1.24.10 or older

**Additional context**
This is happening on both my local and a downstream cluster

**Comment by mantis-toboggan-md** [comment]
@ronhorton I'm a little confused by your screenshots; the third one seems to be contradictory to
> saved value always == false; user change to true is not saved in the chart values.yaml 

Is there a difference between `chart values.yaml` and the yaml shown from update>edit YAML ?

**Comment by ronhorton** [comment]
@mantis-toboggan-md yes! chart values.yaml = false and yaml shown from update>edit yaml = true.

**Comment by cnotv** [comment]
@nickwsuse could you provide an environment with `downstream AWS EC2 Cluster - RKE1 v1.24.10`?

**Comment by nflynt** [comment]
Following the steps laid out by @stormqueen1990, I was able to narrow down the requirements to trigger a mismatch between the PSP setting in the Monitoring chart.

- On Rancher `v2.7.2-rc8`, select Monitoring chart `102.0.0+up40.1.2` for installation
- Click [Next] (defaults for project and such are fine)
- **Check** the box next to "Enable Pod Security Policies"
- **Uncheck** the box next to "Enable Pod Security Policies"
- Click [Install]

Following the above, the network request for `rancher-monitoring` correctly specifies no value for `global.cattle.psp.enabled`, which is expected. (It defaults to false).

However, the request for `rancher-monitoring-crd` now _incorrectly_ specifies `global.cattle.psp.enabled=true`, as though the "uncheck" operation was not consistently applied by the UI:

![002_check_then_uncheck](https://user-images.githubusercontent.com/122321752/229841745-f0287c35-0de2-4973-a18c-77fb6c0bcee2.png)

So far I've only seen this behavior on Monitoring. OPA Gatekeeper seems unaffected. I haven't yet tried it on other charts that have the PSP checkbox.

**Comment by nflynt** [comment]
Update: the above also applies to **chart upgrades.** If you have installed the Monitoring chart with PSP set to `true`, then it is impossible (with the UI alone) to fully update the chart to set PSP to `false`. The setting will correctly apply to `rancher-monitoring` but will be ignored and `rancher-monitoring-crd` will _keep_ its PSPs.

**Comment by prachidamle** [comment]
@mantis-toboggan-md some more info in comments above that can help reproduce

**Comment by cnotv** [comment]
@nflynt I am not able to reproduce that in the video, what am I doing wrong?


https://user-images.githubusercontent.com/5009481/229906157-0acf0412-9ffc-4e0a-8bd2-b8da4f24f66b.mp4

**Comment by cnotv** [comment]
> Update: the above also applies to **chart upgrades.** If you have installed the Monitoring chart with PSP set to `true`, then it is impossible (with the UI alone) to fully update the chart to set PSP to `false`. The setting will correctly apply to `rancher-monitoring` but will be ignored and `rancher-monitoring-crd` will _keep_ its PSPs.

Are these not 2 separated apps? Why should the UI manage both? Is it meant to be handled like that?

**Comment by nflynt** [comment]
@cnotv Possibly nothing. The steps you're following in the video look correct. I was running my test on `v2.7.2-rc8`, are you running on the dev branch? Could this perhaps already be fixed?

**Comment by cnotv** [comment]
> @cnotv Possibly nothing. The steps you're following in the video look correct. I was running my test on `v2.7.2-rc8`, are you running on the dev branch? Could this perhaps already be fixed?

@nflynt I am running what is on `master 2fd348e37` for us, these are the URLs if you wanna give it a try:
- https://releases.rancher.com/ui/latest2/index.html
- https://releases.rancher.com/dashboard/latest/index.html

Doing a comparison of `master` and `v2.7.2-rc8` I see relevant changes to the charts, so it may be that the reason to have different outcomes.

**Comment by mantis-toboggan-md** [comment]
I've tried and failed many times over to reproduce the issue with checking and unchecking the enable PSP option, following the same steps exactly as in @cnotv's video, using the same environment, as well as one provided by @nflynt, as well as my own clusters. It seems to be very elusive.


https://user-images.githubusercontent.com/42977925/230157919-beb9f91a-cf7f-4561-a71b-d41b1bd379dd.mov

> Update: the above also applies to chart upgrades. If you have installed the Monitoring chart with PSP set to true, then it is impossible (with the UI alone) to fully update the chart to set PSP to false. The setting will correctly apply to rancher-monitoring but will be ignored and rancher-monitoring-crd will keep its PSPs.

This I can consistently reproduce and will put a PR up for. It seems the more pressing concern - I think if my fix for the above doesn't resolve the check/uncheck thing others have seen, we should file an issue for 2.7 q2 to look into that further. But we definitely want to fix the upgrade behavior for 2.7.2.

**Comment by nflynt** [comment]
Quick testing on `v2.7.2-rc9`: I am no longer able to reproduce the issues that I found with the PSP checkbox. The value is now correctly applied to both charts (CRD included) during installations and upgrades. :+1:

**Comment by richard-cox** [comment]
@mantis-toboggan-md Is this one fixed via https://github.com/rancher/dashboard/pull/8636?

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 5334be3`
1. created a k8s 1.24 downstream cluster
2. installed `rancher-monitoring:102.0.1+up40.1.2`
3. on screen 2 of install, checked `'enable psps' box
4. completed install of monitoring
5. started `kubeshell on downstream cluster`
6. `checked for psps > they are present as expected`
![2023-05-31_17-59-56.png](https://zube.io/files/rancher/de68004c8b30ee918413fce913f9a70c-2023-05-31_17-59-56.png)
