### ISSUE TITLE
Cluster and Project Members shows "loading..." next to principle name

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#8615]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**
Cluster and Project Members shows "loading..." next to principle name rancher/dashboard#8615

**To Reproduce**

https://user-images.githubusercontent.com/1387263/229741149-290f1f67-b979-41c2-b713-9020fa95aa65.mov

**Result**

**Expected Result**
`Loading...` shouldn't show up

**Screenshots**

**Additional context**
This could be down `v-clean-html`

**Comment by gaktive** [comment]
Engineering to write an automated test in #8804 to help with QA.
