### ISSUE TITLE
[@rancher/components] It's not possible to use the `label` template in `RadioButton` component

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#8619]
**Describe the bug**

`RadioButton.vue` component exposes 2 slots, `description` and `label`, but only `description` works with custom templates:

```
    <radio-button
    ...
    >
      <template #description>
        <span v-html="option.description" />
      </template>
    </radio-button>
```
There are 2 problem with the `label` slot:

1. The label `slot` would be displayed only if the label prop is not null. We should split the logic to display label prop / label slot separately.
2. The label slot is always overwritten by the v-html property of the `label` tag:
![image (8)](https://user-images.githubusercontent.com/26394656/229802065-6d48a80f-2c61-4630-ad9b-a1a17caaf845.png)

This is blocking some new features for Rancher Desktop.

**To Reproduce**

Define a custom label template and see that is not shown as label for RadioButtons:
```
<template #label>
    <span v-html="option.label" />
  </template>
```

**Comment by rak-phillip** [comment]
PR #8625 contained unit tests to assert that the slot is properly rendered when provided. We can expand on these if needed.
