### ISSUE TITLE
Custom solid version of the outlined pin icon

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#8620]
In our icons set, the solid and outlined versions of the pin icon are too different:

![image](https://user-images.githubusercontent.com/120640736/229824855-83085205-c9a3-49df-981e-b36858934b23.png)

@manuelecarlini suggested creating a custom solid version of the outlined icon so they look like part of the same set.

**Comment by kwwii** [comment]
This was done a couple of weeks ago in the rancher icons repo.

**Comment by edenhernandez-suse** [comment]
@manuelecarlini I don't see the commit, can we check it for a quick review?
