### ISSUE TITLE
RKE1 provisioning member roles' "custom role" modal checkbox don't work correctly

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#8621]
When creating/editing an RKE1 cluster the membership section allows users to define custom roles. The modal that appears contains a list of checkboxes: clicking the label of each option appears to select it, but selections are only saved when clicking the box itself.

![Screen Shot 2023-04-04 at 7.54.24 AM.png](https://zube.io/files/rancher/76c3f7e2d80f2d6183aaada56425c6d3-screen-shot-2023-04-04-at-7-54-24-am.png)

**Comment by gaktive** [comment]
Engineering to write automated tests for this in #8785 to help QA.
