### ISSUE TITLE
NetworkAttachmentDefinitions Resource Not Displayed Properly

### ISSUE THREAD

**Issue by frank-at-suse** [rancher/dashboard#8622]
**Setup**
- Rancher version: v2.7.1
- Browser type & version: Chromium-based

**Describe the bug**
Multus NetworkAttachmentDefinitions are not displayed properly or able to be edited (see screenshots).  This issue appears no matter if the 'harvester' feature flag is enabled or disabled.

**To Reproduce**
Add any type of NetworkAttachmentDefinitions resource to cluster & navigate to More Resources -> k8s.cni.cncf.io -> NetworkAttachmentDefinitions.

**Result**
See Attached Screenshot.

**Expected Result**
NetworkAttachmentDefinitions are clearly displayed & their YAML is viewable/editable.

**Screenshots**

![NetworkAttachmentDefinitions Dashboard](https://user-images.githubusercontent.com/88675306/229832778-5e3a32cd-0425-4a6d-82a0-d3e60a66d0d1.png)

![CleanShot 2023-04-04 at 10 51 37](https://user-images.githubusercontent.com/88675306/229833608-8eb43f13-b952-4fec-9df4-e69ac81405d2.png)

**Additional context**

**Comment by David-VTUK** [comment]
Can also recreate this in 2.7.3

**Comment by gaktive** [comment]
@rebeccazzzz is this in the Harvester UI? It looks like a localization string is missing and we've received another report elsewhere.

**Comment by n313893254** [comment]
Hi, @frank-at-suse. Could you please provide me with the Harvester version?

**Comment by frank-at-suse** [comment]
This is in the Rancher UI - not Harvester's.

**Comment by gaktive** [comment]
Upon discussion with @rebeccazzzz, we'll transfer this to `harvester/harvester` and assign to @n313893254. I don't have rights to do that, though.
