### ISSUE TITLE
Labels and annotations space missing with previous section for Repository editor

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8629]
**Setup**
- Rancher version: 2.7.2
- Browser type & version: any

**Describe the bug**
Since the implementation of the switch in the Labels (and Annotation) component used for the PSA, a styling [has been inadvertently moved](https://github.com/rancher/dashboard/commit/3e31e9f1382961edf84c0494560e786898a2d987) to an element to a place where the space is ignored.

**To Reproduce**
Open the repository editor view at `/c/local/apps/catalog.cattle.io.clusterrepo/create`

**Result**

![Screenshot 2023-04-05 at 11 29 35](https://user-images.githubusercontent.com/5009481/230115580-f3eedd88-4fcb-4be9-a0c0-e1b7dc670b49.png)

**Expected Result**

![Screenshot 2023-04-05 at 16 34 56](https://user-images.githubusercontent.com/5009481/230115943-c345a05c-056c-4c2f-8d13-698ac349e626.png)

**Screenshots**

**Additional context**

**Comment by aganesh-suse** [comment]
![Screenshot 2023-05-12 at 1 58 15 PM](https://github.com/rancher/dashboard/assets/129900588/6fc442e8-fdac-4b46-9bc6-953a330d914a)

Verified that the space is acknowledged above the Labels in the Repo Create view.
