### ISSUE TITLE
Namespace - List/Edit/Detail

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#863]
This issue is to track all issues around the component. When changes/updates need to be made to implement/update, a separate issue will be used to track it. 

## Namespace Create/Edit Page
Issue: https://github.com/rancher/dashboard/issues/568

## Namespace Detail Page
Issue: https://github.com/rancher/dashboard/issues/569

Testing of Namespace:
Adding to Projects
Changing Projects

**Comment by soumyalj** [comment]
Tested with master-head(c289ff7de) on HA setup. 

Create projects "project1", "project2", in Ember UI

Case 1:
1. Create namespace in Dashboard UI by selecting the "project1" and providing a name.
Namespace gets created under "project1" and can be observed in the list view

Case 2:
1. Create namespace in Dashboard UI by selecting the desired project and providing a name.Namespace gets created in the desired project
2. Edit the namespace and change the project to "Project2"
Namespace gets listed in "project2" as expected

Issue filed related to namespace creation under a specific project: https://github.com/rancher/dashboard/issues/878
