### ISSUE TITLE
App breaks when creating a new namespace from a workload

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8632]
**Setup**
- Rancher version: 2.7.2
- Browser type & version: Any

**Describe the bug**
While creating a Namespace from any Workload editor, the application breaks.

**To Reproduce**
- Access to Cluster explorer
- Open any Workload section list, e.g. Jobs
- Create a new Job
- Create a new namespace instead of picking one

**Result**
The application breaks.

**Expected Result**
TBD

**Screenshots**

https://user-images.githubusercontent.com/5009481/230131810-e43aee96-71c2-43b2-9c3e-9fb7c4e9e77d.mp4

**Additional context**
More insight from the mapped traceroute log:

```ts
TypeError: this.namespaces.find is not a function
    at VueComponent.updateNamespace (NameNsDescription.vue:333:1)
    at VueComponent.namespace (NameNsDescription.vue:304:1)
```

This issue has been caused while moving the namespace filtering logic to the existing getter, then extending it. https://github.com/rancher/dashboard/issues/6094

**Comment by cnotv** [comment]
`find()` method is for Array and not Object, so when creating a namespace here this should already break before my changes. Otherwise there's something wildly odd.

**Comment by gaktive** [comment]
Engineering to write an automated test in #8806 to help with QA.

**Comment by cnotv** [comment]
We already have a test there https://github.com/rancher/dashboard/pull/8638/files#diff-2b5e2a92db7594b42709ac907f4475c8ee31cb630213a03af52222903c7ffb3e
