### ISSUE TITLE
Footer - Download CLI opens the link in new tab and does not download the file

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#864]
On master-head - commit id: `16616de9c`
- Logged in as a standard user
- Click on Download CLI in the footer. A new tap is opened.

<img width="1452" alt="Screen Shot 2020-07-17 at 2 07 06 PM" src="https://user-images.githubusercontent.com/26032343/87832151-27d2b480-c83a-11ea-9436-10e85f157bbf.png">

**Expected:**
The CLI should be downloaded.

**Comment by deniseschannon** [comment]
Removed Download CLI from the footer

**Comment by sowmyav27** [comment]
**On master-head - commit id: `5e1b21b93`**

Download CLI is NOT available in the footer.
<img width="1912" alt="Screen Shot 2020-08-27 at 10 05 57 AM" src="https://user-images.githubusercontent.com/26032343/91472867-ef68c200-e84c-11ea-98c1-fd82b5cb1727.png">
