### ISSUE TITLE
Cluster Explorer Nav - Update so that the jump frame can be wider to accommodate CRDs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#865]
**On master-head - commit id: `16616de9c`**

- Logged in as a standard user
- Click on `Jump to` search field
- Some of the options are NOT displayed fully.
- The nav bar CANNOT be resized horizontally.
<img width="231" alt="Screen Shot 2020-07-17 at 3 20 36 PM" src="https://user-images.githubusercontent.com/26032343/87835242-6f107380-c841-11ea-9321-a9ce01fd17c9.png">

**Expected**
The nav bar should be resizable
OR
On Hovering over the resource, the name should be displayed fully.

**Comment by vincent99** [comment]
We're not going to do resizing.  There is a separate wireframe for enhancing the Jump menu that will be done eventually.

**Comment by nwmac** [comment]
This is no longer an issue with the 2.6 UI
