### ISSUE TITLE
Activating a node driver or cluster driver does not automatically deselect itself after the state changes to `Active`

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#8650]
**Is your feature request related to a problem? Please describe.**

When a user goes to activate a node driver that is in a state of `Inactive` by default, that works as expected. However, after the node driver state changes to `Active`, that node driver is still selected. To illustrate this behavior, see below:

![Apr-07-2023 15-18-46](https://user-images.githubusercontent.com/52591819/230685787-4b1d60dc-a7ec-45d1-a916-1e21fc9f464e.gif)

Seems a bit counterintuitive as from a user's perspective, I would expect the UI to automatically deselect the now active node driver.

**Describe the solution you'd like**

After a node driver or cluster driver goes from a state of `Inactive` to `Active`, the UI should automatically deselect that driver as it is now `Active`.

**Comment by gaktive** [comment]
This is another page that we should port from Ember to Vue, so we should fix this as part of that new ticket. 

@gaktive to file a new one.
