### ISSUE TITLE
State badges in headers have no margin

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#8651]
**Setup**
- Rancher version: `v2.7-ab561bf837ca6051176bf169784edb01d9dee134-head`

**Describe the bug**
Some Detail views have a state badge in the `h1` header. This badge has no margins and is therefore too close to the item name:

![image](https://user-images.githubusercontent.com/120640736/230878679-18bcc87b-6dcc-46bc-adcb-59ce4b8226fa.png)

![image](https://user-images.githubusercontent.com/120640736/230878876-74d2a367-ead9-4bcc-9cac-d8f02b38fbf6.png)

**Expected Result**
There should be a gap of at least `0.5rem` between the view item name and the badge.

![image](https://user-images.githubusercontent.com/120640736/230879091-83a42f05-3d9c-4221-9891-bb31b5404988.png)

**Comment by richard-cox** [comment]
This one's covered by https://github.com/rancher/dashboard/issues/8389
