### ISSUE TITLE
The namespace selector is still visible during "Research search"

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#8656]
When the user opens the Resource search (cmd+K) a modal dialog pops up.
In this view, the Namespace dropdown is visible and usable. 
It should be hidden by the modal like the rest of the page.

<img width="1406" alt="Screenshot 2023-04-12 at 09 53 38" src="https://user-images.githubusercontent.com/6459624/231407125-e3dd03d8-051c-40f1-bea0-0f49fb146ba0.png">

**Comment by richard-cox** [comment]
No longer reproducible in 2.9-head ~2.9.0

![image](https://github.com/rancher/dashboard/assets/18697775/e6d6ae48-faec-43f9-a7bd-266668bb84fb)
