### ISSUE TITLE
Change the background color of the info box

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#8667]
On the detail page of the extension, there's an info box, right now the background color is dark gray,
but I'd suggest we change for light gray

Color: #EFEFEF

<img width="1045" alt="example-gray" src="https://user-images.githubusercontent.com/6459624/231808964-25aebebc-8ec7-4ecd-800f-5a02b36ecde6.png">

**Comment by nwmac** [comment]
Stale, not planned
