### ISSUE TITLE
Detail Page Issues

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#867]
- [ ] Clicking on "Show X annotations" directs the UI back to the cluster overview page

<img width="355" alt="Screen Shot 2020-07-17 at 1 22 16 PM" src="https://user-images.githubusercontent.com/11410997/87827847-8c891180-c830-11ea-80cc-8012e786ce1d.png">

- [ ] Remove detailtop info from yaml view

<img width="565" alt="Screen Shot 2020-07-17 at 1 22 43 PM" src="https://user-images.githubusercontent.com/11410997/87830708-7ed68a80-c836-11ea-92c5-a06fe9e64808.png">

**Comment by sowmyav27** [comment]
**Validated on latest master-head - commit id: `fd3e37bec`**

-  Clicking on "Show X annotations" shows the annotations
<img width="1666" alt="Screen Shot 2020-07-23 at 12 39 36 PM" src="https://user-images.githubusercontent.com/26032343/88341246-1bdf6a80-ccf2-11ea-8d10-4dd883e10466.png">

- `detailtop info` removed from yaml view
<img width="1146" alt="Screen Shot 2020-07-23 at 2 37 06 PM" src="https://user-images.githubusercontent.com/26032343/88341248-1da92e00-ccf2-11ea-9dc0-a9da1f5348aa.png">
