### ISSUE TITLE
Preferences: The functionality of the 'Hide All Type Descriptions' checkbox is unclear to user

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#8670]
**Setup**
- Rancher version: v2.7.2
- Dashboard version: v2.7.2
- Browser type & version: Chrome 

**Describe the bug**
On the Preferences page, the functionality of the "Hide All Type Descriptions" checkbox is unclear to the user.

**To Reproduce**
- login to Rancher UI as an admin/standard user
- navigate to Preferences Page
- scroll down to Advanced Features section
- note that the Hide All Types Description description is unclear

**Result**
'Hide All Types Description' checkbox description is unclear.

**Expected Result**
The user should be able to understand what the 'Hide All Types Description' checkbox does by reading its label. Please add additional text to clarify what the checkbox does.

**Screenshots**
![Screen Shot 2023-04-13 at 3 31 27 PM](https://user-images.githubusercontent.com/127343932/231897357-2ebf0e8f-6692-4ce2-8aab-3f349965ad6c.png)

**Comment by richard-cox** [comment]
When viewing a resource list some come with descriptions for the resource type in a blue banner above the list. Checking this box will hide them all for the signed in user.

Resources that have descriptions can be found in https://github.com/rancher/dashboard/blob/master/shell/assets/translations/en-us.yaml#L6180

**Comment by yonasberhe23** [comment]
Fix lgtm. existing e2e automation updated to verify checkbox label is sufficient
