### ISSUE TITLE
Ability to select groups within the Organizational Unit (OU) with Okta integration

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8675]
We need a UI that enables users with OKTA integration to search all groups in the OU and not just the groups they are a part of.

We can leverage what we have already in place with Shibboleth, both for the SAML behaviour and the appearance, though @nwmac and @kwwii may have a design in mind already.

Related backend: https://github.com/rancher/rancher/issues/38029

**Comment by ronhorton** [comment]
**Pass** Feature verified for release in rancher 2.7.5. 
Testing complete
Feature has QA sign off.
