### ISSUE TITLE
Details Page - Secret's value is seen in plain text

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#868]
**Validated on master-head - commit id: `16616de9c`**

- Create a secret on Dashboard UI
- Click on the secret
- The value is seen in plain text

<img width="781" alt="Screen Shot 2020-07-17 at 5 49 10 PM" src="https://user-images.githubusercontent.com/26032343/87840696-e3551200-c855-11ea-983e-1ae68464a9c2.png">

**Expected:**
It should not be seen in plain text

**Comment by vincent99** [comment]
This is as-desired at the moment.  The job of a detail page is to show you the details, and the pretty much the only detail of a secret is the values.  Discussion of how these should be shown/hidden by default is in #720.
