### ISSUE TITLE
Cronjob Run Now not generate resources as expected

### ISSUE THREAD

**Issue by niusmallnan** [rancher/dashboard#8683]
**Setup**
- Rancher version: v2.7.2
- Browser type & version: Chrome on Mac

**Describe the bug**

The UI supports the CronJob Run Now, which will generate an API request to create a Job, and the Job will continue to create Pods.
However, the `ownerReferences` is missing in the created Job, which makes it impossible to see the Job in the Cronjob details page.

**To Reproduce**

1. Create a cronjob
2. Click Run Now in the UI

**Result**
Neither the generated Job nor the Pod can view the association relationship through the UI.

**Expected Result**

Jobs can appear on the CronJob details page, and Pods can appear on the Job details page.

**Screenshots**

**bbb-runnow-mfr4g** is created by CronJob Run Now.
**bbb-cron-28029955** is created by CronJob Schedule.
<img width="1645" alt="截屏2023-04-18 下午2 05 38" src="https://user-images.githubusercontent.com/998984/232685919-d4d68d49-9608-4ca7-93b7-77bab7563461.png">

It looks like the **generateName** and **ownerReferences** fields need to be handled correctly.

**Additional context**

**Comment by AndrewHoffmanQA** [comment]
I recreated this issue.   --
when creating cron jobs, the cronjob creates a job, however when the user clicks on the cron job in the UI and is brought to the cron job details page, the user will not see the jobs associated with the cron job. if the user navigates to the 'jobs' portion of the UI they can see their job has been created.'

https://user-images.githubusercontent.com/89030218/233154975-dbb60a76-b4b9-4a88-873d-c7d255b28089.mp4


note: this is also present in 2.7.1

**Comment by weng-pang** [comment]
This behavior also exists in 2.7.3

**Comment by gaktive** [comment]
Engineering to write an automated test for this in #8829 to help QA.
