### ISSUE TITLE
Ensure the legacy harvester plugin works correctly following nuxt removal

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8686]
- The legacy pkg in `rancher/dashboard` `release-harvester-plugin-v1.0.3` branch supports pre 1.1.0 harvester clusters
- We need to ensure this still works following the removal of nuxt (it looks like @torchiaf has a PR up with some changes already)
- If changes are needed, sync with @richard-cox to go through confluence page
  - changes need to get in to the correct branch, in the same PR as a version bump
  - once builds are created we can test by updating an existing dashboard to serve the pkg
  - also need to inform harvester team of the changes, as they'll also need to do similar for their newer pkg

**Comment by torchiaf** [comment]
Related `nuxt` issue: https://github.com/rancher/dashboard/pull/8680

**Comment by WuJun2016** [comment]
Hi @mantis-toboggan-md  @richard-cox  I used rancher-master , tested harvester `v1.0.3,` `v1.1.1` , `v1.1.2` and `harvestr-master `and they all work fine.

Because harvester has not  removed the nuxt-related code, so the relevant tests need to wait for the next version of harvester
