### ISSUE TITLE
Cluster explorer fails to show custom 404 page for unknown links

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8687]
**Setup**
- Rancher version: 2.7.2
 

**Describe the bug**
- Cluster explorer fails to shw 404 page for unknown resources
- For unknown cluster id the user is correctly redirected back to the home page
- For unknown route before cluster id, the nuxt 404 page is shown

**To Reproduce**
- Navigate to the cluster explorer
- Update the url to contain junk (after the valid cluster id)
  - For example `https://<rancher-url>/dashboard/c/c-m-lxqcf286/expasdsadasd/asdsadas/sadasdsadas`

**Result**
- Explorer view is shown.... but without any content in side bar OR main area
- Error in console 
  - `a["".concat(...)] is not a function`

**Expected Result**
- We have a custom 404 page that should show, from memory it states the issue (resource x not found)
- This 404 page might be different than the nuxt 404 page. It could instead be an error page that handles resource not found cluster explorer errors

**Comment by AndrewHoffmanQA** [comment]
I was able to reproduce this issue. users are not seeing the custom 404 page and instead see what is described in the bug

note: this is also present in 2.7.1

**Comment by gaktive** [comment]
Doesn't look tied to Nuxt based on the comment, so we have to look at the routing logic.

**Comment by gaktive** [comment]
The feel is that the Vue router needs to be updated to point at our custom 404 page.
