### ISSUE TITLE
List Page header - Hov text for "Group by" is not available

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#869]
**Validated on master-head - commit id: 16616de9c**

- List page header does not have Hov text for "Group by"
<img width="1442" alt="Screen Shot 2020-07-17 at 5 53 12 PM" src="https://user-images.githubusercontent.com/26032343/87840886-c79e3b80-c856-11ea-8048-9d1fe547fcb9.png">

**Comment by sadiapoddar** [comment]
2.5.2
Rerpo steps. 
1. Cluster Explorer, select namespace page, 
2. Notice there are two buttons to list the namespaces by flat list or group by, but currently, if you mouse hovers over these buttons, the label for these buttons are missing
<img width="175" alt="Screen Shot 2020-12-01 at 4 24 13 PM" src="https://user-images.githubusercontent.com/72409237/100812369-af881c80-33f1-11eb-974d-1960a66a3280.png">
<img width="125" alt="Screen Shot 2020-12-01 at 4 23 42 PM" src="https://user-images.githubusercontent.com/72409237/100812384-b31ba380-33f1-11eb-9f2f-acc666cfbad7.png">

 Verified the fix on Verified the fix 2.5-head 9ee39b9, and mater-head, a549b47.

These buttons now have
<img width="134" alt="Screen Shot 2020-12-01 at 4 25 35 PM" src="https://user-images.githubusercontent.com/72409237/100812512-0f7ec300-33f2-11eb-81da-9a34963d8a48.png">
<img width="168" alt="Screen Shot 2020-12-01 at 4 25 25 PM" src="https://user-images.githubusercontent.com/72409237/100812519-13124a00-33f2-11eb-83fc-55b32d98db98.png">

 appropriate labels.
