### ISSUE TITLE
EPIC: Define a color palette that works with the future plans

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#8697]
The color language of our product needs to be updated for a better user experience and to improve the visual language and reflect better the brand.

- Define the accent color, mainly used for active state https://zube.io/rancher/dashboard-ui/c/9462
- Define the primary color for CTA https://zube.io/rancher/dashboard-ui/c/9463
- Define the color for secondary buttons https://zube.io/rancher/dashboard-ui/c/9464
- Define Semantic colors https://zube.io/rancher/dashboard-ui/c/9383
- Define Grays https://zube.io/rancher/dashboard-ui/c/9461

![image](https://user-images.githubusercontent.com/120640736/233027248-46c47927-b5ec-43cc-9263-6ca98e3f67ab.png)

**Comment by edenhernandez-suse** [comment]
After @manuelecarlini reviewed it, we decided to test the current palette as a theme in a side branch. We will reuse some colours and see how everything works in order to make the necessary adjustments.

@scures I'll need to work with you on this, I only need a branch with a test theme, I can change the colour variables myself.

**Comment by manuelecarlini** [comment]
The current state of the art is tracked in the following document
https://xd.adobe.com/view/d111e7be-4ca1-4721-befa-c40fa8e84eac-8442/
