### ISSUE TITLE
[UI] Extensions icons not aligned

### ISSUE THREAD

**Issue by scures** [rancher/dashboard#8712]
It appears that the images are not aligned in the center with the wrapper.

![image](https://user-images.githubusercontent.com/88777903/233395075-15f81f86-a1e3-4d1d-aad1-1e66a4e42c8c.png)

**Comment by richard-cox** [comment]
@momesgin can this issue and associated PR be added to a MS?

**Comment by momesgin** [comment]
> @momesgin can this issue and associated PR be added to a MS?

I added MS 2.7.5 since this fix is already on 2.7.5 branch

**Comment by gaktive** [comment]
For the sake of QA's timeline for release as they're in crunch time for testing, even though this is merged in 2.7.5, if QA needs to test this, it'll have to be Q3 since this is a minor cosmetic bug.

**Comment by momesgin** [comment]
@richard-cox @gaktive made a [revert PR](https://github.com/rancher/dashboard/pull/9234)
