### ISSUE TITLE
[AKS] Getting error `[object Object]` when creating cloud credentials with invalid credentials

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/dashboard#8713]
**Setup**
- Rancher version: v2.7-head ddbf22a
- Browser type & version: Chrome Build 112

**Describe the bug**

When trying to create a cloud credential while creating an AKS cluster, the error `[object Object]` gets thrown when using invalid credentials. The error should be similar to azure where it can be seen in this ticket https://github.com/rancher/rancher/issues/39611
The error in the dev tools is correct but the UI error message is not showing the correct message.

**To Reproduce**

1. Create AKS cluster on Rancher 2.7-head
2. When creating credential, use invalid credentials
3. See the error message

**Result**
The credential gets created and the error message shown is `[object Object]`
![image](https://user-images.githubusercontent.com/108360907/233421187-80f8caf6-d1de-40cf-b5c7-25dce32ec17f.png)

**Expected Result**

There should be a similar message as when creating invalid Azure credentials
![image](https://user-images.githubusercontent.com/108360907/233421341-c3d919ae-ea00-4a66-8211-65572ecfe141.png)

The correct error is showing in the network tab under dev tools
```
{"error":"Unexpected response from Get Subscription: subscriptions.Client#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"InvalidSubscriptionId\" Message=\"The provided subscription identifier 'test' is malformed or invalid.\""}
```
![image](https://user-images.githubusercontent.com/108360907/233423375-5be3f56b-9049-401d-92cb-2310a6e150e9.png)

**Comment by richard-cox** [comment]
Note - The creds are also created, even though they failed validation

**Comment by gaktive** [comment]
This is a fix against the old UI which has been superseded by the AKS migration to Vue.
