### ISSUE TITLE
fail-whale while opening Apps/Charts

### ISSUE THREAD

**Issue by abonillabeeche** [rancher/dashboard#8714]
**Setup**
- Rancher version: 2.7.2
- Browser type & version: Chrome on Mac

**Describe the bug**
When opening Charts, I get the fail-whale.

**To Reproduce**
Deploy a new cluster, access it immediately, and open Apps/Charts

**Result**
Fail Whale
**Expected Result**

**Screenshots**
<img width="1780" alt="Screenshot 2023-04-20 at 12 30 05 PM" src="https://user-images.githubusercontent.com/5146963/233431789-572de220-ac44-42fe-82a7-d5ac7ea242bd.png">

https://user-images.githubusercontent.com/5146963/233431807-2c265685-d6b5-4722-ad96-d34dd099d700.mov

**Additional context**
This happens randomly but is more likely with a new downstream cluster. I think I've seen this more since the addition of the Featured Charts / Browse vs Featured toggle.

**Comment by richard-cox** [comment]
Alejandro has confirmed no other chart repos are present except the default rancher and partner
