### ISSUE TITLE
Spike: find pages on Ember to move to Vue

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8718]
We need to find all the pages in Ember that we should move to Vue.

Then we need to break out the work and estimate when these could be done. This means ripping out what's embedded in Vue and making them Vue native.

We need to plan this out so we can communicate this to folks as Ember remains a backup option for performance purposes.

AKS, EKS & GKE node providers are the top priority (which are tracked in https://github.com/rancher/dashboard/issues/8083 and related tickets).

RKE1 likely can't be moved but it should be the only thing in Ember.

**Comment by cnotv** [comment]
Based on what @nwmac mentioned many times, these are the path which are using Ember, defined in the [`vue.config.js`](https://github.com/rancher/dashboard/blob/master/shell/vue.config.js#L291-L299)

```
// These are for Ember embedding
'/c/*/edit'
'/k/'
'/g/'
'/n/'
'/p/'
'/assets'
'/translations'
'/engines-dist'
```

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/issues/9274 should be here too.

**Comment by cnotv** [comment]
> #9274 should be here too.

Added to the epic

**Comment by nwmac** [comment]
We already have this list on confluence internally
