### ISSUE TITLE
EKS: default kube version isn't updated when it's out of range

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8721]
**Setup**
- Rancher version: 2.7-head (2.7.3 timeline)

**Describe the bug**
-  https://github.com/rancher/ui/pull/5009 brings in new kube version 1.26
- this version is outside of the allowed max range (/v1/management.cattle.io.setting/ui-k8s-default-version-range) of `<=v1.25.x`
- however the initial value never changes from the first entry
- the user is shown a drop down box with 1.25 selected, however we send 1.26 when creating the cluster

**To Reproduce**
Dev world
- checkout 5009 fix
- Dev World
  - print out `config.kubernetesVersion` in `lib/shared/addon/components/cluster-driver/driver-eks/template.hbs`
  - go to create an EKS cluster and see that the print out is 1.26 whilst the component shows 1.25
- Other worlds
  - go to create an EKS cluster, but don't change the kube version from the shown 1.25
  - see the kube version of the provision cluster is 1.26

**Expected Result**
- provisioned cluster is 1.25

**Comment by furkatgofurov7** [comment]
@richard-cox is there any update on this issue, or it is still a blocker for https://github.com/rancher/ui/pull/5009?

**Comment by richard-cox** [comment]
> @richard-cox is there any update on this issue, or it is still a blocker for [rancher/ui#5009](https://github.com/rancher/ui/pull/5009)?

@furkatgofurov7  This is still blocking https://github.com/rancher/ui/pull/5009. It's been groomed and has a high priority, so in theory should make it in for 2.7 Q2

**Comment by cpinjani** [comment]
Validated as fixed on build > v2.7.5-rc5 - :white_check_mark: 

**Scenario 1**
Checked kube version in `/v1/management.cattle.io.setting/ui-k8s-default-version-range` is `"<=v1.26.x"`
- While provisioning an EKS cluster, the kube versions shown are 1.23, 1.24, 1.25, 1.26
- Provision the clusters with above versions and checked EKS version on AWS is matching the selected version

**Scenario 2**
Changed kube version in `/v1/management.cattle.io.setting/ui-k8s-default-version-range` to `"<=v1.24.x"`
- While provisioning an EKS cluster, the kube versions shown are 1.23, 1.24
- Provision the clusters with above versions and checked EKS version on AWS is matching the selected version
