### ISSUE TITLE
prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.selector created in monitor values YAML, when installing rancher-monitoring chart as YAML

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8723]
Internal reference: SURE-2997

**Repo steps:**

When installing momnitoring:

- Deploy local-path provisioned in downstream https://github.com/rancher/local-path-provisioner
- Go to Cluster Explorer > Apps & Marketplace -> Charts -> Monitoring > Prometheus and 'Enable Persistent Storage for Prometheus', selecting local-path StorageClass
- Click 'Edit as YAML'
- Click 'Install'

Install will fail:

prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0 volume in cattle-monitoring-system Namespace fails to successfully provision with the following error:

failed to provision volume with StorageClass "local-path": claim.Spec.Selector is not supported

The error that needs fixing is that when you click 'Edit as YAML', we populate an empty selector: `volumeClaimTemplate.spec.selector` - this should be removed before being sent to the backend.

**Comment by aalves08** [comment]
Pattern can be found here:
https://github.com/rancher/dashboard/pull/8643
