### ISSUE TITLE
[BUG] Node Pods list is always empty

### ISSUE THREAD

**Issue by p-kimberley** [rancher/dashboard#8725]
Originally posted in: https://github.com/rancher/rancher/issues/41226.

**Rancher Server Setup**
- Rancher version: 2.7.2
- Installation option:
  - Helm chart
  - RKE2 1.25.7+rke2r1

**Information about the Cluster**
- Kubernetes version: 1.25.7+rke2r1
- Cluster Type: Downstream, imported local RKE2 cluster

**User Information**
- What is the role of the user logged in? Cluster Owner

**Describe the bug**
After the upgrade from Rancher v2.7.1 to v2.7.2, the `Pods` list for a selected node, is always empty.

**To Reproduce**
1. Navigate to `Cluster` -> `Nodes`
2. Click on a node

**Result**
Observe the list under `Pods` is empty, regardless of the namespace/project filter

**Expected Result**
The `Pods` list should contain the pods running on the selected node.

**Screenshots**
![image](https://user-images.githubusercontent.com/17559369/233323948-5592b634-9dcf-4abe-a95e-c4a65a656172.png)

**Additional context**
Without having visibility of the running pods on a node, the task of draining nodes is much harder, requiring one to resort to `kubectl` to confirm which pods are failing to be evicted.

**Comment by richard-cox** [comment]
Note - As a fall back until this is resolved in the next functional release, pods per node can be seen via the Pods list when grouped by Node

![image](https://user-images.githubusercontent.com/18697775/234066457-4f31b5c5-4d2d-44c8-b805-86c0df766875.png)

**Comment by skycyan** [comment]
May I ask which small version will address this issue?

**Comment by richard-cox** [comment]
@skycyan It's in the v2.7.5 milestone, which will be the next release

**Comment by skycyan** [comment]
> @skycyan It's in the v2.7.5 milestone, which will be the next release

Because many resource views will report 'There are no rows to show', I would like to temporarily resolve this issue by rolling back from version 2.7.4 to version 2.6.13. May I ask if there are any other hidden dangers?

**Comment by richard-cox** [comment]
> Because many resource views will report 'There are no rows to show'

That sounds like a different issue. It might be worth checking the value of the project / namespace filter in the header.

Issues for bugs / features related to specific releases can be found by searching github issues in this and `rancher/rancher` repos. Alternatively looking through the `rancher/rancher` release notes will give you an idea of what's in each feature.

If you do roll back, please ensure that your upstream and downstream cluster versions align with the supported kube versions for that release - https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-4/
