### ISSUE TITLE
Persistent Volume-create

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#874]
https://xd.adobe.com/view/c9ec94f9-aa3d-45ce-a3f8-b851e80bc641-9cbf/

**Comment by deniseschannon** [comment]
Use wizard to select PV "type" and then select PV options. 

Types: (sort alphabetical with Custom at the end)
Longhorn
HostPath
EmptyDir
Secret
NFS Share
ISCSI Target
PersistentVolumeClaim
Downward API
ConfigMap
Projected
Custom

Note: We are explicitly removing the cloud provider options and expect users to use "Custom" if they want to use a cloud provider. FlexVolume and CSI are expected to use PVC to create PVs.

**Comment by deniseschannon** [comment]
- [ ] Update mocks to the new CruResource Wizard
- [ ] "Step 1" is the subtype of PVs 
- [ ] "Step 2 and 3" would move into tabs
- [ ] Make sure to include Labels and Annotations

**Comment by lvuch** [comment]
updated with above feedback: https://xd.adobe.com/view/c9ec94f9-aa3d-45ce-a3f8-b851e80bc641-9cbf/

**Comment by deniseschannon** [comment]
Closing in favor of new design until this is prioritized
