### ISSUE TITLE
Namespace Edit - Should not be allowed to edit/remove cattle.io related labels and annotations.

### ISSUE THREAD

**Issue by sangeethah** [rancher/dashboard#876]
Rancher  Server - `master-3326-head`

In "Edit as Form" view, user is allowed to remove cattle.io related labels and annotations.

<img width="889" alt="Screen Shot 2020-07-20 at 6 10 25 PM" src="https://user-images.githubusercontent.com/4266958/88001242-7c816400-cab4-11ea-8423-8e15b4176366.png">
<img width="892" alt="Screen Shot 2020-07-20 at 6 09 37 PM" src="https://user-images.githubusercontent.com/4266958/88001244-7db29100-cab4-11ea-98a9-b9056ddca940.png">

Removing `field.cattle.io/projectId` will result in the namespace being removed from project association.

Expected Behavior:
User should not be allowed to remove `cattle.io`  related labels and annotations.

**Comment by deniseschannon** [comment]
This will be addressed with https://github.com/rancher/dashboard/issues/556, but leaving it open so that it explicitly is tested.

**Comment by soumyalj** [comment]
Tested with master-head(master-8a60de75db5324c73535b71c087c3e4bd5f36d29-head)

Steps:
1. Created a project P1 and namespace ns1 under P1. 
2. From the dashboard view, edit the namespace, the follow was observed

-  The edit view displays the cattle.io labels and annotations
- The cattle.io labels can be deleted without a warning

![Screen Shot 2020-08-24 at 11 49 17 AM](https://user-images.githubusercontent.com/18536626/91083870-e20ac800-e5ff-11ea-84af-f22ecd9cd99e.png)

**Comment by codyrancher** [comment]
Fixed issue with https://github.com/rancher/dashboard/pull/1081

**Comment by soumyalj** [comment]
Verified with master-head( master-616259e0274-head)

**Steps:**

1. Create a project "newproject" and namespace newns1 under the project.
2. From the dashboard view, edit the namespace, the following was observed and hence re-opening the issue:

- The edit view does not display cattle.io labels and annotations (and cannot be deleted) as expected
- New labels and annotations can be added 

![Screen Shot 2020-08-26 at 4 47 04 PM](https://user-images.githubusercontent.com/18536626/91367641-db28b480-e7bb-11ea-91e0-1dc48070021c.png)
