### ISSUE TITLE
Automation: List global roles/users pages for standard users when they have custom permissions assigned

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8777]
Taken from work done in https://github.com/rancher/dashboard/issues/8344, we should write an automated test to ensure that we do list the appropriate material in Page Configuration >> Users & Authentication pages for a standard user who has the roles or users.

E2E feels like the goal

To reproduce:
1. As an admin, create a global role by navigating to Users and Auth >> Roles >> Global Roles >> Verbs: List, Get & Resources: Global Roles
2. Create a standard user as an admin and assign the role
3. Log in as standard user

Expected result:
The user to be able to list/get the pages `Users & Auth`

Factors:
- We need to add a test suite around non-admin users.

**Comment by cnotv** [comment]
Added pages expected to be displayed and accessible.
