### ISSUE TITLE
Automation: RKE1 provisioning member roles' "custom role" modal checkbox don't work correctly

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8785]
Based on the work done in https://github.com/rancher/dashboard/issues/8621, let's write an automated test to verify that when we create or edit an RKE1 cluster and the membership section allows users to define custom roles, clicking the label of each checkbox actually selects it. 

Previous, selections are only saved when clicking the box itself.

@Shavindra may be able to help here.

To reproduce:

- Navigate to Cluster Management > Cluster > Edit Cluster > Cluster Roles
- Select user and Custom role
- Click on the labels of the roles. It should select the different roles
- When click on save it should create all the roles
- This can be verified by navigating to Cluster Explorer > Cluster > Cluster & Project members and sorting the list by age to view recently created roles.

**Comment by richard-cox** [comment]
We can only test this via e2e on a created RKE1 cluster (i don't think we need credentials to get to the page like we do with RKE2). It's also ember side where we don't have unit test support

**Comment by richard-cox** [comment]
Depends on https://github.com/rancher/ui/pull/5035. This contains functional changes that shouldn't merge until 2.7q2 is out. I'll bump this out to 2.7q3 and do some limited manual testing
