### ISSUE TITLE
Automation: test that the label template in RadioButton component can be used

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8787]
Based on the work done in https://github.com/rancher/dashboard/issues/8619, let's write an automated test to ensure that the label template can be used in the RadioButton.

For reference, the RadioButton.vue component exposes 2 slots, description and label, but previously, only description works with custom templates.

To reproduce:
Define a custom label template and see that it is shown as label for RadioButtons:

```
<template #label>
    <span v-html="option.label" />
  </template>
```

**Comment by cnotv** [comment]
A test is already present for this issue.
https://github.com/rancher/dashboard/pull/8625/files#diff-e99a689a68e03beac725cc7ba111a7c5c275da598f995cdf0870bf8ba0100322

**Comment by gaktive** [comment]
Closing as done then.
