### ISSUE TITLE
[RFE] Add bare-metal Harvester container workloads and multi-cluster management support

### ISSUE THREAD

**Issue by guangbochen** [rancher/dashboard#8800]
**Is your feature request related to a problem? Please describe.**
We would like to make the bare-metal Harvester support container workloads and multi-cluster management through its built-in Rancher.

**Describe the solution you'd like**
Rancher Dashboard Changes:
- Hamburger Menus:
    - The Harvester cluster will now be displayed on the Explore Cluster section and will use the Harvester icon when detected.
    - A Harvester Dashboard link will be added to the top menu when the cluster is local and running in embedded mode.
- Home Page:
    - All clusters, including Harvester, will now be displayed on the home page.
    - A Virtualization Management button will allow users to jump to the virtualization page when viewing a Harvester cluster.
- Continuous Delivery:
    - The Harvester cluster will now be displayed and will function like other RKE2 clusters since Harvester uses RKE2 under-the-hood.
- Cluster Management:
    - The Harvester cluster will now be displayed.
- Virtualization Management:
    - The Harvester version will now be displayed instead of the Kubernetes version.
- Global Settings:
    - The Harvester and multi-cluster-management feature flags will be locked in the Feature Flags list, similar to RKE2, and cannot be disabled when the local cluster is Harvester.
- Explorer UI (when the local cluster is Harvester):
    - The Rancher upgrade button on the Install Apps page will be disabled/hide since Rancher upgrades will be managed by Harvester when running in embedded mode.
    - Editing/upgrading/deleting Harvester managed system services, such as monitoring, logging, and Harvester, will be disabled since these are Harvester system components that should be managed only by Harvester upgrade only.
    - Operations that could affect Harvester, such as editing/deleting Monitor, Longhorn, and Logging, will be disabled on the Cluster Tools page.
    - CRDs prefixed with [harvesterhci.io](http://harvesterhci.io/).* and [kubevirt.io](http://kubevirt.io/).* will preferably not be displayed since they are Harvester system-level resources.

**Describe alternatives you've considered**

**Additional context**
Harvester HEP: https://github.com/harvester/harvester/pull/3673
https://github.com/harvester/harvester/issues/2679

**Comment by gaktive** [comment]
This PR may be enough to work with here: https://github.com/rancher/dashboard/pull/8754

**Comment by mantis-toboggan-md** [comment]
> - The Rancher upgrade button on the Install Apps page will be disabled/hide since Rancher upgrades will be managed by Harvester when running in embedded mode.
> - Editing/upgrading/deleting Harvester managed system services, such as monitoring, logging, and Harvester, will be disabled since these are Harvester system components that should be managed only by Harvester upgrade only.

To achieve these two requirements, we can use a chart annotation: `catalog.cattle.io/managed` (to be added by @ibrokethecloud )
The dashboard already hides the upgrade button and labels the app 'managed' when this annotation is present, eg:
![Screen Shot 2023-05-16 at 6 07 56 PM](https://github.com/rancher/dashboard/assets/42977925/a6958b19-9f48-4f4f-9809-957e7749a490)

The dashboard will need to be updated to hide the edit and delete buttons on the cluster tools page when the chart has that annotation:
![Screen Shot 2023-05-16 at 6 10 31 PM](https://github.com/rancher/dashboard/assets/42977925/5a223148-4ead-406f-b41f-660f27c8f1a3)

**Comment by mantis-toboggan-md** [comment]
Waiting on https://github.com/rancher/rancher/pull/41710

**Comment by gaktive** [comment]
Backend now merged. @mantis-toboggan-md are we unblocked now for Q3?

**Comment by mantis-toboggan-md** [comment]
@gaktive yes, I'll move this issue accordingly

**Comment by lanfon72** [comment]
## Tested on Harvester `v1.2.0-rc5` with **vcluster**

* Hamburger Menus:
  * [x] The Harvester cluster will now be displayed on the Explore Cluster section and will use the Harvester icon when detected.
  * [ ] A Harvester Dashboard link will be added to the top menu when the cluster is local and running in embedded mode.[^1]
* Home Page:
  * [ ] All clusters, including Harvester, will now be displayed on the home page. [^2]
  * [ ] A Virtualization Management button will allow users to jump to the virtualization page when viewing a Harvester cluster. [^3]
* Continuous Delivery:
  * [ ] The Harvester cluster will now be displayed and will function like other RKE2 clusters since Harvester uses RKE2 under-the-hood. [^4]
* Cluster Management:
  * [ ] The Harvester cluster will now be displayed. [^5]
* Virtualization Management:
  * [ ] The Harvester version will now be displayed instead of the Kubernetes version. [^6]
* Global Settings:
   - [x] The Harvester and multi-cluster-management feature flags will be locked in the Feature Flags list, similar to RKE2, and cannot be disabled when the local cluster is Harvester.
* Explorer UI (when the local cluster is Harvester):
  * [ ] The Rancher upgrade button on the Install Apps page will be disabled/hide since Rancher upgrades will be managed by Harvester when running in embedded mode. [^7]
  * [ ] Editing/upgrading/deleting Harvester managed system services, such as monitoring, logging, and Harvester, will be disabled since these are Harvester system components that should be managed only by Harvester upgrade only. [^8]
  * [ ] Operations that could affect Harvester, such as editing/deleting Monitor, Longhorn, and Logging, will be disabled on the Cluster Tools page. [^9]
  * [ ] CRDs prefixed with [harvesterhci.io](http://harvesterhci.io/).* and [kubevirt.io](http://kubevirt.io/).* will preferably not be displayed since they are Harvester system-level resources. [^10]


[^1]: Dashboard icon is not clickable with link
    ![image](https://github.com/rancher/dashboard/assets/5169694/b07a1621-f240-4a86-9287-4cca95c480b9)
[^2]: Harvester clusters is not listed
    ![image](https://github.com/rancher/dashboard/assets/5169694/9a1a38b8-abbe-4a50-8136-a7f46a2b0d30)
[^3]: No link to visit Virtualization page
[^4]: Same as the original Rancher, can't confirm it is different
[^5]: Harvester cluster is not listed.
    ![image](https://github.com/rancher/dashboard/assets/5169694/e72530d5-b000-4eaa-a767-1ab6283c628c)
[^6]: Version is not Harvester's but Kubernetes'
    ![image](https://github.com/rancher/dashboard/assets/5169694/275287aa-61cc-4cfc-9a86-fa254b6c3f70)
[^7]: Able to edit/upgrade rancher
    ![image](https://github.com/rancher/dashboard/assets/5169694/f00cf108-d8e9-4559-92e0-4d491d4bb00a)
[^8]: Able to edit/upgrade
    ![image](https://github.com/rancher/dashboard/assets/5169694/19e72657-e838-40a9-a1b0-080e98560e00)
[^9]: Cluster Tools is empty
    ![image](https://github.com/rancher/dashboard/assets/5169694/93a8c64e-ebd4-4faa-b2d1-d61b724061fa)
[^10]: Still available
    ![image](https://github.com/rancher/dashboard/assets/5169694/0d7044fd-20d7-487d-bc0f-997ad7000eea)
    ![image](https://github.com/rancher/dashboard/assets/5169694/3525eedd-4715-4099-aeb1-276cde856013)

**Comment by bk201** [comment]
Another observation is:
- Enable vclsuter-rancher addon.
- Import host cluster to Rancher.
- Disable vclsuter-rancher addon.
- Enable vcluster-rancher addon again, but the previous state is gone (like host cluster is not imported).
Just want to confirm if this is expected.

**Comment by guangbochen** [comment]
Hi @lanfon72, please take a look at the following comments; thanks. cc @bk201 @ibrokethecloud 

* Hamburger Menus:
  * [x]  A Harvester Dashboard link will be added to the top menu when the cluster is local and running in embedded mode.[1](#user-content-fn-1-f39a1ba962d15c48fe054934f2661d1a) - `expected behavior, same for the local cluster.`

* Home Page:
  * [x]  All clusters, including Harvester, will now be displayed on the home page. [2](#user-content-fn-2-f39a1ba962d15c48fe054934f2661d1a)  - `only when the harvester-baremetal-container-workload feature flag is enabled, for now, please use v2.7-head for testing before the PR .`
  * [x]  A Virtualization Management button will allow users to jump to the virtualization page when viewing a Harvester cluster. [3](#user-content-fn-3-f39a1ba962d15c48fe054934f2661d1a)  - `There is a link underneath the Provider column; after clicking, it will jump to the Harvester cluster view directly.`
      <img width="1090" alt="image" src="https://github.com/rancher/dashboard/assets/4569037/62867ee1-e3d3-42fe-a64b-c453fa8994ee">
* Continuous Delivery:   
  * [x]  The Harvester cluster will now be displayed and will function like other RKE2 clusters since Harvester uses RKE2 under-the-hood. [4](#user-content-fn-4-f39a1ba962d15c48fe054934f2661d1a) - `ditto, need to enable the new feature flag.`

* Cluster Management:  
  * [x]  The Harvester cluster will now be displayed. [5](#user-content-fn-5-f39a1ba962d15c48fe054934f2661d1a) - `ditto`

* Virtualization Management:
  * [ ]  The Harvester version will now be displayed instead of the Kubernetes version. [6](#user-content-fn-6-f39a1ba962d15c48fe054934f2661d1a). - `currently not supported; let track it as a separated enhancement issue in Harvester.`

* Explorer UI (when the cluster provider is Harvester): `ditto, need enable the container view feature flag and visiting Harvester clusters`
  * [ ]  The Rancher upgrade button on the Install Apps page will be disabled/hidden since Rancher upgrades will be managed by Harvester when running in embedded mode. [7](#user-content-fn-7-f39a1ba962d15c48fe054934f2661d1a)  - `@WuJun2016 can u please help to check this one? thanks`
  * [ ]  Editing/upgrading/deleting Harvester managed system services, such as monitoring, logging, and Harvester, will be disabled since these are Harvester system components that should be managed only by Harvester upgrade only. [8](#user-content-fn-8-f39a1ba962d15c48fe054934f2661d1a) - `also cc @WuJun2016`
  * [x]  Operations that could affect Harvester, such as editing/deleting Monitor, Longhorn, and Logging, will be disabled on the Cluster Tools page. [9](#user-content-fn-9-f39a1ba962d15c48fe054934f2661d1a)  - `cluster tools page is hidden by design; you can compare it with normal k8s clusters like an RKE2 cluster.`
  * [x]  CRDs prefixed with [harvesterhci.io](http://harvesterhci.io/).* and [kubevirt.io](http://kubevirt.io/).* will preferably not be displayed since they are Harvester system-level resources. [10](#user-content-fn-10-f39a1ba962d15c48fe054934f2661d1a) - `It should be fine to keep it on the API/CRDs page, the group menu has been removed in contrast with the old UI`
        <img width="222" alt="image" src="https://github.com/rancher/dashboard/assets/4569037/d860c5a1-4fa2-4317-928d-b75cb0fa8eec">

**Comment by WuJun2016** [comment]
I think the design here aligns with the previously discussed expectations.  （ The Rancher UI will not completely prevent users from performing upgrades; it will only use "Managed" in the "Upgradable" column to indicate that the app is being managed by other services. ）  So the user can click `⋮` to upgrade.
<img width="1726" alt="image" src="https://github.com/rancher/dashboard/assets/24985926/688c1f92-ce94-440f-ba54-638b2bcba08e">

> The Rancher upgrade button on the Install Apps page will be disabled/hidden since Rancher upgrades will be managed by Harvester when running in embedded mode. [7](https://github.com/rancher/dashboard/issues/8800#user-content-fn-7-f39a1ba962d15c48fe054934f2661d1a) - @WuJun2016 can u please help to check this one? thanks

**Comment by lanfon72** [comment]
This would need to be retested, in current Vcluster implementation, we can't change its Rancher version: https://github.com/harvester/harvester/issues/2679#issuecomment-1694740453

- The Rancher version of Vcluster is fixed as `v2.7.5` and can't be changed.
- After enabled **harvester-baremetal-container-workload**, Vcluster entering **CrashloopBackOff**, dashboard is inaccessible.

**Comment by guangbochen** [comment]
Hi @lanfon72, the new version format with `rancher-version (harvester-version)` is an expected design change, so we can know both the Rancher version and the Harvester version in the container dashboard.

**Comment by lanfon72** [comment]
> Hi @lanfon72, the new version format with `rancher-version (harvester-version)` is an expected design change, so we can know both the Rancher version and the Harvester version in the container dashboard.

Yes, the snapshot is just pointing out the version is 2.7.6 with 1.2.0-rc5, all changes requested in this issue has been applied as the test

**Comment by lanfon72** [comment]
As the
> The Harvester version will now be displayed instead of the Kubernetes version.
is going to be tracking in Harvester issues, all changes requested in this issue been applied, this issue is good to close.

**Comment by gaktive** [comment]
Closing as noted in the comments.
