### ISSUE TITLE
Preference: User preference not updated when month and day have same value for these date formats - M/D/YYYY and D/M/YYYY

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#8801]
**Setup**
- Rancher version: v2.7.2
- Dashboard version: v2.7.2
- Browser type & version: Not browser specific 

**Describe the bug**
On the Preferences page, when a user selects date format (M/D/YYYY or D/M/YYYY) on a day where the month and day are the same values (e.g. 5/5/2023), the user's date format preference is not updated (api request is never sent).

**To Reproduce**
- login to Rancher UI as an admin/standard user
- navigate to Preferences Page
- scroll down to Display Settings section
- open network logs
- select date format for M/D/YYYY (notice api request is sent)
- select date format D/M/YYYY (notice api request is NOT sent)

**Result**
The user's date format preference is not updated when the user selects date format (M/D/YYYY or D/M/YYYY) on a day where the month and day are the same values (e.g. 5/5/2023).

**Expected Result**
The user's date format preference should be updated when the user selects date format (M/D/YYYY or D/M/YYYY) on a day where the month and day are the same values (e.g. 5/5/2023).

**Screenshots**
![Screen Shot 2023-05-05 at 4 09 49 PM](https://user-images.githubusercontent.com/127343932/236583382-a9c06655-6148-4f84-bf15-4646a1994f8b.png)

https://user-images.githubusercontent.com/127343932/236583400-c525dceb-c4ad-4724-965d-a030c7d6fec7.mov

**Comment by gaktive** [comment]
For the dropdown when it has the 2 numeric date options, we should give a visual cue whether it's MM/DD or DD/MM
