### ISSUE TITLE
Automation: App breaks when creating a new namespace from a workload

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8806]
Based on work done in https://github.com/rancher/dashboard/issues/8632, let's write an automated test to confirm that nothing breaks when creating a new namespace from a workload.

@cnotv can offer guidance (or maybe he has a test written somewhere)

To Reproduce: 
- Access to Cluster explorer
- Open any Workload section list, e.g. Jobs
- Create a new Job
- Create a new namespace instead of picking one

Expected behaviour:
- Namespace is created and the UI doesn't break

**Comment by cnotv** [comment]
We already have a test there: https://github.com/rancher/dashboard/pull/8638/files#diff-2b5e2a92db7594b42709ac907f4475c8ee31cb630213a03af52222903c7ffb3e
