### ISSUE TITLE
Automation: confirm that static loading indicator respects light & dark mode

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8808]
Based on work done in https://github.com/rancher/dashboard/issues/6065, let's write an automated test to ensure that the static loading indictor looks good in light & dark mode.

Previously, when dark mode was enabled or picked up by OS theme, the user goes from a dark mode log in page, bright white loading page and then a dark home page. It can be quite a quick transition so the page can flash. Removing Nuxt addressed this but we should make sure that upon login, both light & dark modes stay with the expected colour set.

@richard-cox or @codyrancher can offer guidance.

**Comment by richard-cox** [comment]
Additional fix - https://github.com/rancher/dashboard/pull/9022

**Comment by cnotv** [comment]
As suggested, we could have an unit test after replacing inlined code with an imported script.
