### ISSUE TITLE
Automation: Pressing Enter in textarea elements not working

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8817]
Based on work done in https://github.com/rancher/dashboard/issues/8550, let's write an automated test to ensure the Enter works in text areas. @torchiaf can offer guidance.

To reproduce:
- Go to local -> Storage -> ConfigMaps
- Create a new ConfigMap
- Add a new entry in Data form
- Select value field and press Enter

Expected behaviour:
A new line is added to the value.

**Comment by gaktive** [comment]
Unit test could be the way to go here.

**Comment by gaktive** [comment]
More information: https://github.com/rancher/dashboard/issues/7112 & PR https://github.com/rancher/dashboard/pull/7267

**Comment by bisht-richa** [comment]
After reviewing fix we decided to do two unit tests one for to `prevent default on press enter` and another to test `A new line is added to the value.`
