### ISSUE TITLE
Automation: Incorrect favicon shown during setup

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8827]
Based on work done in https://github.com/rancher/dashboard/issues/8794, let's write an automated test to avoid this regression so that the correct favicon appears during setup. 

To Reproduce:
- Bring up a new rancher
- Nav to UI

Expected Result:
In default setups this should be the blue rancher bull

Details:
Problem was caused by `<link rel="shortcut icon" type="image/x-icon" href="/public/favicon.png">` in template; this should just be `/favicon.png` from `shell/public/index.html`

**Comment by nwmac** [comment]
Suggested test approach (e2e):

- Load the UI
- Look in the document head and find the link for the shortcut icon
- Download the link (check for failure to download)
- Compare the file downloaded to the icon in the code tree (use MD5 or some other simple hash algorithm)
