### ISSUE TITLE
Automation: Cronjob Run Now does generate resources in Jobs Detail page

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8829]
Based on the work done in https://github.com/rancher/dashboard/issues/8683, let's write an automated test to confirm that running a cronjob generates the appropriate resource when ran.

To Reproduce:
- Create a cronjob
- Click Run Now in the UI

Expected Result:
Jobs can appear on the CronJob details page, and Pods can appear on the Job details page.

**Comment by cnotv** [comment]
Test has to be done on the model
https://github.com/rancher/dashboard/pull/8734/files#diff-629ca51684689c01e229c34044b8d49c235192a18f593431d9b070ee5e2d815e
