### ISSUE TITLE
Cluster Explorer sidenav - Design specs

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#8835]
[Specs in Xd file](https://xd.adobe.com/view/1453b6a5-ca9c-4794-8fbf-34f1349e45a3-4100/)

![image](https://github.com/rancher/dashboard/assets/120640736/e28668cf-2ee8-4e16-9bae-8efbf5f711c1)

**Comment by richard-cox** [comment]
I think this was tracked somewhere, but we need to provide designs for
- resources that are very very long... and that are namespaced
- menu's with sub menus
  - ![image](https://github.com/rancher/dashboard/assets/18697775/c0c8331f-e5a8-4cd8-b07d-9042ba241253)
