### ISSUE TITLE
Extend Advanced Worker support for `management` and `rancher` stores

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8837]
**Is your feature request related to a problem? Please describe.**
The advanced worker handles socket management and event processing within a Web Worker. Instances align with stores and currently only supports the `cluster` store, which handles resources from a specific cluster (to support cluster explorer)

**Describe the solution you'd like**
Extend the advanced worker to support to additional stores, `rancher` (global support for v3 / norman) and `management` (global support for v1 / steve for the upstream cluster)

**Comment by floatingman** [comment]
Tested the issue by performing the following steps

1. Enabling the updated performance setting in Global Settings (Advanced Websocket Worker, Required Namespace/ Project Filtering)
2. Verified the following 
    1. All workloads list fetch the correct data (via http request)
    2. New endpoint is hit for primary resource type, only resources from selected namespaces/projects are shown
    3. New endpoint is hit for all secondary resource types
    4. All workloads list update with the correct data (via socket)
    5. Changes to resources in the list are automatically shown (when changed via another context/browser/etc)
    6. Changes to resource not in the list do not show (creating a new resource not in a selected namespace/project doesn't appear in the list)
11. Creating resources works fine
12. Navigate to a create page of a resource (deployment, pod). Resource can be created, user is returned to the resource list and, if the resource was created in a namespace in the filter, the new resource should be shown
13. Edit resources work fine
14. Navigate to an existing resource page (deployment, pod). Resource can be edited, user is returned to the resource list and the edited resource should be shown
15. Both Upstream and Downstream clusters work correctly
