### ISSUE TITLE
[BUG] [UI] When editing an RKE2 cluster on the UI, the "Skip TLS certificate" option selected for the second time cannot be saved.

### ISSUE THREAD

**Issue by smallteeths** [rancher/dashboard#8849]
**Rancher Server Setup**
- Rancher version: Rancher version: 2.7.2
- Installation option (Docker install/Helm Chart): Docker

**Describe the bug**
When creating an RKE2 cluster configuration for a UI, if "Skip TLS certificate" is not selected for the first time, and then the "Skip TLS certificate" option is selected when editing the cluster for the second time, the "Skip TLS certificate" option selected before will be lost when saving the cluster configuration.

<img width="767" alt="截屏2023-05-11 下午2 11 29" src="https://github.com/rancher/rancher/assets/27733391/5e3f5cc8-c68f-40d9-8396-2d194287f2c5">

**To Reproduce**
1. Create custom rke2 cluster without select the `Skip TLS certificate` option.
2. Edit the rke2 cluster and select the `Skip TLS certificate` option.
3. When saving the RKE2 cluster, it is found that the "Skip TLS certificate" value is not passed to the backend.

<img width="1712" alt="236721349-6037192d-ae62-446e-96d8-21aa9045b866" src="https://github.com/rancher/rancher/assets/27733391/904f02fd-6dca-4655-9c13-aa7c3808b263">

**Expected Result**
When editing the cluster, the "Skip TLS certificate" option can be saved correctly.

**Comment by Josh-Diamond** [comment]
Will need an RC to resume testing, (one has been requested), moved from `QA Working > QA Next up` in the meantime;

**Comment by Josh-Diamond** [comment]
Ticket # 8849 - Test Results - ✅ 
---

With HA Helm on Rancher `v2.7.7-rc1`:
1. Fresh install of Rancher `v2.7.7-rc1`
2. Provision a downstream RKE2 cluster w/ private registry configured, however, don't check the `Skip TLS Verification` option
3. Once cluster is `active`, navigate to `Cluster Management > Cluster > Edit Config > Registries` and check the `Skip TLS Verification` option, then hit `save`
4. Once cluster is `active`, `edit config` once more navigate to `Registries` section
5. Verified - `Skip TLS Verification` option is selected; as expected
