### ISSUE TITLE
Setup Page has missing image

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8852]
**Setup**
- Rancher version: 2.7.3 ish

**Describe the bug**
- The right hand side image is missing from the setup page

![image(9)](https://github.com/rancher/dashboard/assets/18697775/4bf54ecd-1f09-4ea4-a51b-50b0dbffb681)

**To Reproduce**
- Create a fresh cluster
- Enter the password on the creds page

**Additional context**
This is the second page, after the user has entered credentials

Creds page image is correctly shown
```
Request URL: https://releases.rancher.com/dashboard/latest/img/login-landscape.0a26efb2.svg
Request method: GET
Status code: 200 
```

Config page image is not
```
Request URL: https://releases.rancher.com/dashboard/latest/css/pages/img/login-landscape.911b980e.svg
Request method: GET
Status code: 404 
```

**Comment by richard-cox** [comment]
The login page uses the `BrandImage` component. The setup page uses ` background-image: url('~@shell/assets/images/pl/login-landscape.svg');`. The later should also use 

```
<BrandImage
        class="col span-6 landscape"
        file-name="login-landscape.svg"
      />
```

**Comment by Priyashetty17** [comment]
Validated this with the latest v2.7-head.

Component | Version
-- | --
Rancher | v2.7-f0d4078f4fa75b303ce276c3f4b12fc465b1ba2a-head
Dashboard | master d94e78c24

![SetupPage](https://github.com/rancher/dashboard/assets/42880103/b197f551-4449-4b3d-89dc-20348b1417c2)

Note:
- Tested with different browsers (Chrome and Firefox)
- Tested with different modes (Dark and Auto)
