### ISSUE TITLE
Show full cluster name in global menu via mouseover or scroll

### ISSUE THREAD

**Issue by ebauman** [rancher/dashboard#8854]
Internal Reference: SURE-5959

**Is your feature request related to a problem? Please describe.**
In the global menu, it is frustrating when looking through the list of clusters that one cannot see the full name of a cluster. This is particularly noticeable in situations where clusters have long names. 

**Describe the solution you'd like**
Either a left-to-right scroll bar to roll over and see full names, or a tooltip or similar popup that shows full cluster name when mouseover occurs. 

**Describe alternatives you've considered**
Searching is possible but requires more action on the part of the user. Additionally the user may not know offhand the search criteria required, and instead relies on "see it and know it" to identify the cluster in question.

**Additional context**

**Comment by richard-cox** [comment]
The menu systems on the left are currently undergoing a design review, this will probably be resolved as part of that @kwwii ?

**Comment by kwwii** [comment]
@richard-cox Yes, with the upcoming menu changes the design calls for a tooltip on hover with the full cluster name.

**Comment by aalves08** [comment]
This PR https://github.com/rancher/dashboard/pull/10487 does 95% of the work. My recommendation is to work on this issue **after** this PR get's merged and I would add the tooltip to all clusters instead of being displayed only for clusters that have a description. Test adjustments should be needed.

**Comment by aalves08** [comment]
I've pushed a fix to deal with long strings without blank spaces @scures 

**Problem**
![Screenshot 2024-03-01 at 12 40 02](https://github.com/rancher/dashboard/assets/97888974/49e6dd5f-bfd9-438a-b2d6-955f616744d7)

**Fix**
![Screenshot 2024-03-01 at 12 40 27](https://github.com/rancher/dashboard/assets/97888974/3e6fd8ad-f301-4834-9072-b0b802f534fc)
![Screenshot 2024-03-01 at 12 41 07](https://github.com/rancher/dashboard/assets/97888974/cf349322-4f4b-4b05-947e-527fdfa126fb)

**Why did I cap the max width of the tooltip to 200px? I find this very ugly! It's just a huge tooltip**
![Screenshot 2024-03-01 at 12 40 14](https://github.com/rancher/dashboard/assets/97888974/6189fe22-5e1a-43a2-a5ae-b743d2595552)

**Comment by yonasberhe23** [comment]
we aren't covering this scenario in existing e2e tests. here's follow-up ticket for it https://github.com/rancher/qa-tasks/issues/1240. moving to 'To Test' @izaac

**Comment by IsaSih** [comment]
Manual tests pass with the side menu bar. However, the cluster long name overrides the provider in the home menu (not sure if the home menu is exactly the same as the global menu). Could @aalves08  please confirm?  If they're the same, then I'll reopen the issue.
![Screenshot 2024-04-10 at 2.47.42 AM.png](https://zube.io/files/rancher/439aa0b7fa6890fe8c9eff398fdeb6ef-screenshot-2024-04-10-at-2-47-42-am.png)

**Comment by aalves08** [comment]
> Manual tests pass with the side menu bar. However, the cluster long name overrides the provider in the home menu (not sure if the home menu is exactly the same as the global menu). Could @aalves08 please confirm? If they're the same, then I'll reopen the issue. ![Screenshot 2024-04-10 at 2.47.42 AM.png](https://camo.githubusercontent.com/9fcf8ccfeaedce8a0ed3204014f864b5890388f1e5e4996c8ae05805594198ff/68747470733a2f2f7a7562652e696f2f66696c65732f72616e636865722f34333961613062376661363839306665386339656666333938666465623665662d73637265656e73686f742d323032342d30342d31302d61742d322d34372d34322d616d2e706e67)

@IsaSih this is a separate issue, imo. The cluster name need to be truncated in home page cluster list.

**Comment by IsaSih** [comment]
Created issue https://github.com/rancher/dashboard/issues/10791 to track the overriding content in the home page. Movid this issue to done as the other tests pass
