### ISSUE TITLE
Exec not created on UI to Windows pods with minimal RBAC

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#8855]
**Setup**
- Rancher version: 2.7.2
- Rancher UI Extensions: N/A
- Browser type & version: Unknown

**Describe the bug**

When the user has RBAC exec on Windows pods does not work. Sambe RBAC works for Linux

Try to execute on a windows pod from UI, it does not work

works if download kubeconfig and execute: kubectl -n default exec -it <windows-pod> powershell

**To Reproduce**

- deploy cluster with Windows node
- Create a user
- give permissions on the project: View Monitoring', 'View Workloads' and 'Manage Workloads'
- try to execute on a Windows pod (three dots, execute)

**Result**

it just gives a blank screen

**Expected Result**

User should be able to exec into the pod **with minimal RBAC permissions**.

**Screenshots**

**Additional context**

Same operation works fine for a linux pod

Workaround is to download the kubeconfig and exec from the CLI.

Could be related to fixes put in https://github.com/rancher/dashboard/issues/3157 or https://github.com/rancher/dashboard/issues/4862 requiring the user to have more than just exec permissions, but this needs to be documented if that's the case.

SURE-6180

**Comment by richard-cox** [comment]
@aiyengar2 In the browsers dev tools are there any failed network requests or errors in the console?

**Comment by kwwii** [comment]
As part of this card, we should document how to bring up windows nodes for issues like these.

**Comment by Sean-McQ** [comment]
Will document bringing up a windows node as part of another task but the problem described here isn't something we can resolve directly on the UI side.

Problem description: The UI must reference the cluster node in order to determine if a pod being exec'd into is a Windows node (so it can supply the 'cmd' command rather than /bin/bash).

Workaround: A user with minimal permissions to manage workloads in a project should be able to exec into Windows pods provided they also have cluster permissions to view nodes.

Potential long-term fix: Add metadata to pods to differentiate between Windows and Linux workloads, once we have that we can eliminate the call to `nodes` in `shell/components/nav/WindowManager/ContainerShell.vue` and reference that instead of the related node to determine the OS and generate the correct command to properly open a shell in the pod.

**Comment by nwmac** [comment]
@Sean-McQ We can't just close the issue here - I don't understand the workaround - is the problem that the user can't access nodes, so we can't determine if the pod is running on a Windows node? I don't see what the workaround is.

I assume we try /bin/bash - does that fail in a way we could then try cmd? i.e. we wouldn't need to know if it was windows or not.

I don't think we should add metadata to pods.

If we need something from backend, we need to create an issue and reference it here - we can't close this out until resolved.

**Comment by Josh-Diamond** [comment]
Ticket #8855 - Test Results - :x: - RE-OPENED
---

With HA Helm running Rancher `v2.7-027246f77f03b82660dc2e91df6bf2cd549163f0-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | As standard user and project member of a downstream cluster, `execute shell` for a windows pod via Rancher UI | :x: |
| 2. | As standard user and project member of a downstream cluster, `execute shell` for a linux pod via Rancher UI | ✅ |

---

Scenario 1 - :x:
1. Fresh install of Rancher `v2.7-head`
2. As admin, provision a downstream custom cluster - [ 3 linux nodes: `1 etcd, 1 cp, 1 wkr`; 1 windows node: `1 wkr` ]
3. Once `active`, create a standard user
4. Add standard user created in step 3 as a `project member` to the cluster
5. Deploy a couple windows workloads - [ i used `ranchertest/testcontainer:windows` and `ranchertest/testnginx:windows` ]
6. Once `active`, log out as admin and log back in as standard user
7. As standard user, navigate to `Cluster Explorer > Workloads > Pods`, and `execute shell` for windows pods.
8. Veri-FAILED - shell opens up, reports an error, and immediately disconnects. (shell will remain open in UI, but disconnected)

Error:
```
Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "<REDACTED>": hcs::System::CreateProcess: /bin/sh -c "TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c \"/bin/bash\" /dev/null || exec /bin/bash) || exec /bin/sh" <REDACTED>: The system cannot find the file specified.: unknownInternal error occurred: error executing command in container: failed to exec in container: failed to start exec "<REDACTED>": hcs::System::CreateProcess: undefined <REDACTED>: The system cannot find the file specified.: unknownUnable to open a shell to the container (none of the shell commmands succeeded)
```

Screenshot:
![image (37)](https://github.com/rancher/dashboard/assets/46494969/1c840984-5dec-42a0-8d9a-71d0bdc5a0cc)

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.7-head`
2. As admin, provision a downstream custom cluster - [ 3 linux nodes: `1 etcd, 1 cp, 1 wkr`; 1 windows node: `1 wkr` ]
3. Once `active`, create a standard user
4. Add standard user created in step 3 as a `project member` to the cluster
5. Deploy a linux workload - [ i used `ranchertest/mytestcontainer` ]
6. Once `active`, log out as admin and log back in as standard user
7. As standard user, navigate to `Cluster Explorer > Workloads > Pods`, and `execute shell` for linux pods.
8. Verified - shell opens, connects, and is functional; as expected

**Comment by Josh-Diamond** [comment]
Ticket #8855 - Test Results - ✅ 
---

With HA Helm running Rancher `v2.7-d8a2bcae227717e16caa8519a3709f3e013673f2-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | As standard user and project member of a downstream cluster, `execute shell` for a windows pod via Rancher UI | ✅ |
| 2. | As standard user and project member of a downstream cluster, `execute shell` for a linux pod via Rancher UI | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.7-head`
2. As admin, provision a downstream custom cluster - [ 3 linux nodes: `1 etcd, 1 cp, 1 wkr`; 1 windows node: `1 wkr` ]
3. Once `active`, create a standard user
4. Add standard user created in step 3 as a `project member` to the cluster
5. Deploy a couple windows workloads - [ i used `ranchertest/testcontainer:windows` and `ranchertest/testnginx:windows` ]
6. Once `active`, log out as admin and log back in as standard user
7. As standard user, navigate to `Cluster Explorer > Workloads > Pods`, and `execute shell` for windows pods.
8. Verified - shell opens, connects, and is functional; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.7-head`
2. As admin, provision a downstream custom cluster - [ 3 linux nodes: `1 etcd, 1 cp, 1 wkr`; 1 windows node: `1 wkr` ]
3. Once `active`, create a standard user
4. Add standard user created in step 3 as a `project member` to the cluster
5. Deploy a linux workload - [ i used `ranchertest/mytestcontainer` ]
6. Once `active`, log out as admin and log back in as standard user
7. As standard user, navigate to `Cluster Explorer > Workloads > Pods`, and `execute shell` for linux pods.
8. Verified - shell opens, connects, and is functional; as expected
