### ISSUE TITLE
Banner placement is broken in Istio installing page

### ISSUE THREAD

**Issue by bisht-richa** [rancher/dashboard#8862]
**Setup**
- Rancher version: 2.7.2

**Describe the bug**

Banner row placement is broken in Istio installing step 2 page

**To Reproduce**

Cluster > Cluster tool > install Istio > select `Customize Helm options before install` checkbox > click next button
(you have to scroll the screen to the right side)

**Screenshots**

![Screenshot 2023-05-12 at 12 59 19](https://github.com/rancher/dashboard/assets/18264463/02c39562-7373-4fff-9ee3-d58a590a0d33)

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 5334be3`
1. cluster > apps > charts
2. selected istio to install
3. added check to 'customer helm options before install'
4. clicked next
5. all buttons/banners are in view
6. resizing the window, the banner and buttons adjust, but necessary information is still viewable and clickable. 

![2023-06-01_16-27-57.png](https://zube.io/files/rancher/be7a68eb4cae8c55be103a23aaae9769-2023-06-01_16-27-57.png)
![2023-06-01_16-27-43.png](https://zube.io/files/rancher/599478be3bde67651f067fa54dc2913f-2023-06-01_16-27-43.png)
