### ISSUE TITLE
Fleet allows creation of workspace even though the namespace already exists [front end]

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8866]
Internal reference: SURE-3955
Reported in 2.5.9

Fleet allows the creation of workspace even though the namespace already exists. Deleting that workspace causes the deletion of namespace along with its contents, which means unwanted fleet workspace results in data loss

Fleet will do their work in https://github.com/rancher/fleet/issues/1519 but the ask here is to help things out earlier as a workaround in the UI. @nwmac took a look at what we can do in the front end to detect an existing namespace and it appears we can do something to prevent duplicate namespaces until Fleet can do this themselves in the backend.

Expected behavior:
1. Fleet should not create workspace when namespace exist
~~2. Provide a way to delete workspace without deleting actual namespace and its contents~~

**Comment by kwwii** [comment]
We should create a new issue for the second acceptance criteria. This is not currently in the pointed scope.

**Comment by kwwii** [comment]
There might be rbac considerations here

**Comment by gaktive** [comment]
Leaving off Point 2 for now since that should be covered by the related backend item. 

@kkaempf can you confirm that's the case? or is there a Ui consideration here?

**Comment by kkaempf** [comment]
Confirmed.
The UI part was just a suggested workaround/helper 😉

**Comment by kkaempf** [comment]
Closing as not planned
