### ISSUE TITLE
Downstream AKS `Cluster Management > Cluster details` page not displaying accurate message during update

### ISSUE THREAD

**Issue by kkaempf** [rancher/dashboard#8877]
## From https://github.com/rancher/aks-operator/issues/179

**Setup**
- Rancher version: 2.7.0
- Rancher UI Extensions:
- Browser type & version: Chrome

**Describe the bug**

* When updating a downstream AKS cluster, Cluster Management > Cluster details page does not display accurate message.

**To Reproduce**

*    Fresh install of 2.7.0
*   Provision a downstream AKS cluster
*    Update downstream AKS cluster
*   Navigate to Cluster Management > Cluster Details page
*    Reproduced

**Result**

 - The following message is seen:
`This resource is currently in a transitioning state, but there isn't a detailed message available.`

**Expected Result**
 - expected to show more detailed message, as seen in AKS operator logs:
`time="2023-03-07T02:10:50Z" level=info msg="Waiting for cluster [REDACTED] to update node pool [REDACTED]"`

**Screenshots**
<img width="1038" alt="Screen Shot 2023-03-06 at 6 10 24 PM" src="https://user-images.githubusercontent.com/46494969/223551630-66f9723d-b1a4-41be-80a7-16eaa4db7210.png">

**Comment by richard-cox** [comment]
This is one for the back end team. We show this fallback message when the `provisioning.cattle.io.cluster` `metadata.state` reports as `transitioning` but does not contain a `message`.

That `message` should be updated to contain the requested text

**Comment by richard-cox** [comment]
Blocked on https://github.com/rancher/aks-operator/issues/179

**Comment by nwmac** [comment]
@richard-cox Is there *actually* anything for the UI to do here? or is a case of backend giving better status messages?

**Comment by richard-cox** [comment]
@nwmac In my opinion, given https://github.com/rancher/aks-operator/issues/179#issuecomment-1547497963, there's nothing UI side. Once that suggestion has been implemented we will automagically show the correct message.

**Comment by nwmac** [comment]
@kkaempf Based on the above, I don't think there is anything to UI to do - this was marked backend blocked, so we would validate in the UI once the backend work was done - but for now, we will close this issue and the work to fix will be purely in the operator.
