### ISSUE TITLE
Cluster Overview - Apply a filter when clicking in the different gauges Deployment types.

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#888]
Rancher `master-head (07/23/2020)` _fd3e37bec_ k8s HA install.
dashboard-index -> `latest`

- Deploy any cluster type
- Navigate to Dashboard landing in the Cluster Overview page.
- Click Deployments for example

This will list all other types of deployments including Stateful Sets, Daemon Sets, Tasks, etc.
The same applies if you click on Stateful Sets and the other Cluster Overview Gauges.
We should also make sure to apply `All Namespaces` filter because the Overview Page is a total of all cluster resources.

If we don't filter this properly it's hard to count the Deployment list page with all the different deployment types manually.

**Comment by deniseschannon** [comment]
With the changes to the cluster explorer navigation, this seems to be working now.

**Comment by izaac** [comment]
@deniseschannon just to confirm the expected behavior for this.

the Cluster Overview page shows `All Namespaces` data in the gauges. If I click in each gauge to navigate to those resources right now I think the default is showing `User Namespaces`.

Example:

Let's say the Ingress Gauge has 1 Ingress (HA setup) shown in the Overview page and I click on that gauge card then the Ingress list won't show any Ingress unless I manually set `All Namespaces` in the Global Nav Bar combobox then it will show the expected number of rows in that resource list matching with what's reported on the Overview page.

If the behavior is expected in the example then we're good to close.

**Comment by vincent99** [comment]
That is the currently defined behavior.  The overview page shows totals for the whole cluster (or whatever portion you're authorized to).  Clicking the boxes is the same as picking the type in the left, and those pages list the subset that match the namespace filter.

The Deployments list showing other kinds of workloads was a bug that has been fixed. They were all acting like the Workload list.

**Comment by izaac** [comment]
Rancher version `master-head (08/06/2020)` _74853f3bf_ HA k8s 
dashboard-index -> `latest`

Looks good to me and the behavior is expected. Closing.
