### ISSUE TITLE
Tab names should not have the underline as the link

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#8880]
Once the user goes on mouse over to the tab name it appears the underline of the link,
this underline remains visible on the active tab. It should not be visible
<img width="784" alt="Screenshot 2023-05-15 at 16 54 51" src="https://github.com/rancher/dashboard/assets/6459624/3bd4c174-f7ac-46f2-a957-d4085470181f">

**Comment by nwmac** [comment]
Not planned
