### ISSUE TITLE
Embedded Grafana dashboards don't load in the local cluster with the latest version of monitoring

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#8885]
This came out of an investigation into https://github.com/rancher/rancher/issues/41562 and ties back in to recent work here: https://github.com/rancher/dashboard/pull/8347/files

To reproduce:
1. Install rancher monitoring 102.0.1+up40.1.2 in the local cluster
2. Navigate to the local cluster's explorer dashboard  (`/dashboard/c/local/explorer`)
Result:
Embedded grafana pages fail to load

Additionally, the grafana link on the monitoring index page is not adding this url exception for the local cluster as described in https://github.com/rancher/dashboard/issues/8346. We need to update the hardcoded link [here](https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/monitoring/index.vue#L61) to use the `getClusterPrefix` utility.

The assumption in https://github.com/rancher/dashboard/pull/8347 was that for monitoring versions >=102.0.0+up40.1.2 the grafana url would not need to be different for the local cluster - this isn't the case. See more details from @nflynt  [here](https://github.com/rancher/rancher/issues/41562#issuecomment-1548556453)

We need to update the grafana url-constructing utility [here](https://github.com/rancher/dashboard/blob/master/shell/utils/grafana.js#L9) to include the `/k8s/clusters/${ clusterId }` prefix for local clusters **only when monitoring `100.2.0+up40.1.2` or `102.0.0+up40.1.2` is installed** and continue using this prefix for all downstream clusters regardless of version.

**Comment by w13915984028** [comment]
As described in https://github.com/harvester/harvester-installer/pull/492

In https://charts.rancher.io/index.yaml, there is `assets/rancher-monitoring/rancher-monitoring-102.0.0+up40.1.2.tgz`, but no `102.0.1+up40.1.2` , which is not tformally released yet ? **who can help confirm if `102.0.1+up40.1.2` is released?**  thanks.

And, in 102.0.0+up40.1.2, there is such a bug, that is fixed in 102.0.1+up40.1.2, this is an very important bug fix for us.

https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/102.0.1%2Bup40.1.2/charts/grafana/templates/nginx-config.yaml
```
          {{- if eq .Values.global.cattle.clusterId "local" -}}
          sub_filter '"appSubUrl":""' '"appSubUrl":"/api/v1/namespaces/{{ template "grafana.namespace" . }}/services/http:{{ template "grafana.fullname" . }}:{{ .Values.service.port }}/proxy"';
          {{- else -}}
          sub_filter '"appSubUrl":""' '"appSubUrl":"/k8s/clusters/{{ .Values.global.cattle.clusterId }}/api/v1/namespaces/{{ template "grafana.namespace" . }}/services/http:{{ template "grafana.fullname" . }}:{{ .Values.service.port }}/proxy"';
          {{- end -}}
```          

There are also many changes in servicemonitor
![image](https://github.com/rancher/dashboard/assets/31133476/41f8e2a5-63e7-47e5-9094-13e252aa9745)

**Comment by w13915984028** [comment]
FYI: Harvester local patch of `102.0.0+up40.1.2` with the fix from `102.0.1+up40.1.2` https://github.com/harvester/harvester-installer/pull/492

**Comment by prachidamle** [comment]
@AndrewHoffmanQA This is the backend ticket linked and depends on this UI fix https://github.com/rancher/rancher/issues/41036
Please validate the backend ticket also gets fixed with this fix! thanks

**Comment by AndrewHoffmanQA** [comment]
the scope of this bug passes. when navigating to the local cluster dashboard grafana displays as expected. 

tested on
rancher image 2.7.5-rc4
monitoring - 102.0.1+up40.1.2 (Current)

see video


https://github.com/rancher/dashboard/assets/89030218/4b773a0c-ddbd-4a53-8308-47b1fa82153a
