### ISSUE TITLE
`all` toleration value throws an error in the cluster for cluster / fleet agent customization setting

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#8886]
**Setup**
- Rancher version: v2.7-head (b04c942)
- Rancher UI Extensions: n/a
- Browser type & version: chrome

**Describe the bug**

when using the `all` option for rke2 `appendTolerations` through the UI, fleet will throw an error

**To Reproduce**

* provision an rke2 cluster
  * add a fleet agent customization -> toleration using the `all` value

**Result**
cluster will provision, but fleet won't deploy to the cluster

**Expected Result**

only valid options should be in the dropdown

**Screenshots**

<img width="1189" alt="Screen Shot 2023-05-15 at 2 02 23 PM" src="https://github.com/rancher/dashboard/assets/16691014/519e13fc-d4b4-47b0-a920-c0e39bf45696">

**Comment by aalves08** [comment]
Asking for confirmation that `All` should not be used as an option for Fleet from @Anna-Blendermann @snasovich before committing to any UI changes. 

I believe we may have got the spec wrong on the UI side:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#toleration-v1-core

It seems that `All` is not a valid option. Empty represents All according to the spec. 

FYI @mantis-toboggan-md @gaktive

**Comment by aalves08** [comment]
PR up for review with the fix

**Comment by slickwarren** [comment]
found a related issue for rke1 during testing: https://github.com/rancher/dashboard/issues/8930

but it seems for rke2, testing shows that the `all` option is now working as expected.
