### ISSUE TITLE
Add validation to `server-url` setting for trailing forward slash

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8893]
**Is your feature request related to a problem? Please describe.**
- When supplying a url for `server-url` a trailing slash will break provisioning of clusters

**Describe the solution you'd like**
- On both the setup page and global settings --> settings page add validation to block submission if the value ends in a forward slash

**Additional context**
- It makes sense to tackle https://github.com/rancher/dashboard/issues/5666 at the same time

**Comment by yonasberhe23** [comment]
since this contains sufficient e2e test validation it can be moved to Done. cc @izaac
