### ISSUE TITLE
Login page has some problem in the input fields

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#8894]
The login page presents input fields for username and password. Those fields look broken, especially with the dark theme, they should only have padding with the same background as the whole field.

<img width="771" alt="Screenshot 2023-05-16 at 15 47 49" src="https://github.com/rancher/dashboard/assets/6459624/a1194053-c6de-4144-88f1-1b170c69b07d">

**Comment by richard-cox** [comment]
This is probably an indication by the browser or a password manager that the fields have been auto-populated

**Comment by nwmac** [comment]
Won't fix - this is password manager issue
