### ISSUE TITLE
Dashboard Connection Issue

### ISSUE THREAD

**Issue by ecda909** [rancher/dashboard#890]
I'm getting the connection issue shown below when trying to use the dashboard...

<img width="1920" alt="Screen Shot 2020-07-23 at 10 41 09 PM" src="https://user-images.githubusercontent.com/20650573/88356380-9e3d4e00-cd35-11ea-931e-1c090d065bc7.png">

**Comment by deniseschannon** [comment]
@ecda909 Where are you trying to use this or how? There is a known backend issue for this: https://github.com/rancher/rancher/issues/28150

**Comment by deniseschannon** [comment]
@ecda909 This seems to no longer be an issue on our side, so please let us know if you are testing again  and see issues.
