### ISSUE TITLE
Adding cluster-name label to new Prometheus Recording rules created from the UI. 

### ISSUE THREAD

**Issue by geethub97** [rancher/dashboard#8902]
When an alert fires it does not mention from which cluster it comes. I have made the change to include cluster_name to all existing service monitors in the monitoring chart, but we need this change to be reflected on the UI for all new alerts. 

Related Tickets:  https://github.com/rancher/dashboard/issues/7513
Backend Ticket: https://github.com/rancher/rancher/issues/37128

Request: 
UI add another default label to all rules that to include the cluster_name. (Repeat steps for cluster_id label.) 

<img width="1243" alt="Screen Shot 2022-11-21 at 11 31 28 AM" src="https://user-images.githubusercontent.com/99695266/203142741-680997d4-d869-4f26-86cc-060dcc971f73.png">

**Comment by prachidamle** [comment]
@gaktive this is a ticket closed on backend for Q2 and this needs a UI change in order to test/deliver the fix - Can this change be made for the upcoming Q2 milestone?

**Comment by gaktive** [comment]
@prachidamle is this different from the work in https://github.com/rancher/dashboard/issues/7513 ?

**Comment by ronhorton** [comment]
@gaktive qa is good with this add.

**Comment by prachidamle** [comment]
yes @gaktive we need a similar change as the one in https://github.com/rancher/dashboard/issues/7513 to add clustername now instead of clusterid - QA has reopened the original ticket.

**Comment by ronhorton** [comment]
**Pass** verified in `2.7-head commit ID 707d173`
clustername now included by default in alert labels. 
![2023-05-22_21-01-21.png](https://zube.io/files/rancher/8b18a8800ad879e6ebdb2fa62d34d0dc-2023-05-22_21-01-21.png)![2023-05-22_21-02-03.png](https://zube.io/files/rancher/0fb8442ac530ca440b774958e700b273-2023-05-22_21-02-03.png)
