### ISSUE TITLE
Cypress generated videos and screenshots fail to be uploaded

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8904]
# Description

From run `d0b715adf46d9d8c247a23309822bba5` May 10 2023, 12:51:51 (as pinpoint) seems like the videos and screenshots are not uploaded anymore to Sorry Cypress.

[Example on the run](https://github.com/rancher/dashboard/actions/runs/4994198048/jobs/8944416957):

```
Failed Uploading (1/1) /home/runner/work/dashboard/dashboard/cypress/videos/setup/rancher-setup.spec.ts.mp4
```

![image](https://github.com/rancher/dashboard/assets/5009481/0c835bec-79cb-4d20-8c98-63039d6f99dc)

Problem should be due packages changes or server configuration.

**Comment by richard-cox** [comment]
The issue with the sorry-cypress instance got worse and blocked all e2e tests. We couldn't access the instance (even via DO own terminal) so it's been temporarily removed from tests - https://github.com/rancher/dashboard/pull/8913

**Comment by cnotv** [comment]
Closing as issue has been solved.
Opened in favor of other problems which leads to this issue: https://github.com/rancher/dashboard/issues/8953 https://github.com/rancher/dashboard/issues/8955
