### ISSUE TITLE
toleration `key` has header: `label key` for cluster / fleet agent customization fields. Expected only `key` or possibly `taint key`

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#8910]
**Setup**
- Rancher version: v2.7-head(42f3b50)
- Rancher UI Extensions: n/a
- Browser type & version: chrome

**Describe the bug**

the text for a toleration key is currently set to `label key` which may be confusing, since tolerations are for taints, and affinity are for labels. 

**To Reproduce**

* deploy an rke1 or rke2 cluster
 * go to cluster or fleet agent customization and add a toleration

**Result**
key reads `label key`

**Expected Result**

`key` or possibly `taint key` 

**Screenshots**

<img width="891" alt="Screen Shot 2023-05-16 at 10 27 58 PM" src="https://github.com/rancher/dashboard/assets/16691014/59746bdb-2190-4676-9a45-9ae0a21e30d6">

**Additional context**

when adding a taint, the field reads as just `key`

**Comment by gaktive** [comment]
@slickwarren would you consider this more of a bug? We're past feature complete for Q2 so if you want this in for this release, it could be considered more of that. Otherwise, I'd push this to Q3.

**Comment by slickwarren** [comment]
sure, I've escalated to a bug as I feel this will generate confusion without a fix. @gaktive

**Comment by aalves08** [comment]
@mantis-toboggan-md let's change it to `key`.

**Comment by aalves08** [comment]
@slickwarren fixed for rke2

**Comment by slickwarren** [comment]
just checked and it is correctly identified on rke2; can we also fix it for rke1?

**Comment by mantis-toboggan-md** [comment]
RKE1 has now been updated to say 'Key' as well

**Comment by slickwarren** [comment]
tested on v2.7-head (707d173) and both rke1 and rke2 fleet / cluster agent customization -> toleration has `key` instead of `label key`
