### ISSUE TITLE
Logging: ClusterFlow and ClusterOutput not showing up in UI

### ISSUE THREAD

**Issue by wombelix** [rancher/dashboard#8912]
**Setup**
- Rancher version: 2.7.3
- Rancher UI Extensions: Logging, v102.0.0+up3.17.10
- Browser type & version: Chrome Version 112.0.5615.137 (Official Build) (arm64), Firefox 102.10.0esr (64-bit)

**Describe the bug**

When I create a `ClusterFlow` or `ClusterOutput` via Rancher UI, nothing seem to happen. I click create but it doesn't show up in the UI, also no error message. As I tried to create it again, I've got an error that a resource with this name already exist. When I check with `kubectl` I can see that they were indeed created. In the Cluster Output dropdown when creating a new Cluster Flow, I can also see all previously created Cluster Outputs. Navigating to `Logging` then shows at least the one active set of `ClusterFlow` and `ClusterOutput`. Screenshots attached, kubectl results in addition following as plaintext:

kubectl get clusterflow -n cattle-logging-system
```
NAME              ACTIVE   PROBLEMS
testclusterflow   true     
```

kubectl describe clusterflow -n cattle-logging-system
```
Name:         testclusterflow
Namespace:    cattle-logging-system
Labels:       <none>
Annotations:  <none>
API Version:  logging.banzaicloud.io/v1beta1
Kind:         ClusterFlow
Metadata:
  Creation Timestamp:  2023-05-17T14:27:13Z
  Generation:          1
  Managed Fields:
    API Version:  logging.banzaicloud.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:active:
    Manager:      manager
    Operation:    Update
    Subresource:  status
    Time:         2023-05-17T14:27:13Z
    API Version:  logging.banzaicloud.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:globalOutputRefs:
    Manager:         rancher
    Operation:       Update
    Time:            2023-05-17T14:27:13Z
  Resource Version:  15381474
  UID:               81964bdc-188f-48e4-a391-7cbc30af6863
Spec:
  Global Output Refs:
    testcloudwatchout
Status:
  Active:  true
Events:    <none>
```

kubectl get clusteroutput -A -n cattle-logging-system 
```
NAMESPACE               NAME                     ACTIVE   PROBLEMS
cattle-logging-system   test                     false    
cattle-logging-system   test-cloudwatch-output   false    
cattle-logging-system   testcloudwatchout        true     
```

kubectl describe clusteroutput testcloudwatchout -n cattle-logging-system
```
Name:         testcloudwatchout
Namespace:    cattle-logging-system
Labels:       <none>
Annotations:  <none>
API Version:  logging.banzaicloud.io/v1beta1
Kind:         ClusterOutput
Metadata:
  Creation Timestamp:  2023-05-17T14:03:16Z
  Generation:          1
  Managed Fields:
    API Version:  logging.banzaicloud.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:active:
    Manager:      manager
    Operation:    Update
    Subresource:  status
    Time:         2023-05-17T14:03:16Z
    API Version:  logging.banzaicloud.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:cloudwatch:
          .:
          f:region:
    Manager:         rancher
    Operation:       Update
    Time:            2023-05-17T14:03:16Z
  Resource Version:  15381473
  UID:               a4bd1852-eca8-487b-bdc8-47d9966e6da2
Spec:
  Cloudwatch:
    Region:  us-east-1
Status:
  Active:  true
Events:    <none>
```

**To Reproduce**

Create a new `ClusterOutput`, then a new `ClusterFlow` and select the previously created Cluster Output.

**Result**
The new created cluster output and flow will not show up under the sub-menus `Logging > ClusterFlow` and `Logging > ClusterOutput`. They only show up under the root `Logging`.

**Expected Result**

Every cluster flow or output I create should show up in the UI in the appropriate section. Similar as it does when I create a namespaced flor or output.

**Screenshots**

![Screenshot 2023-05-18 at 09 47 36](https://github.com/rancher/dashboard/assets/16312366/2f3a6905-cec0-46df-b44a-76516dcb1100)
![Screenshot 2023-05-18 at 09 35 15](https://github.com/rancher/dashboard/assets/16312366/93bc9279-9f98-443a-9de3-6a86194e9edf)
![Screenshot 2023-05-18 at 09 22 30](https://github.com/rancher/dashboard/assets/16312366/1c7fd671-c165-46bf-bfa1-0494365a67fa)

**Additional context**

I was checking the debug logs for the rancher container in cattle-system and also the browser developer tools, I couldn't observe any error message related to my issue. I guess it's a frontend problem because I can see the resources via kubectl, but I'm not sure.

**Comment by richard-cox** [comment]
@wombelix The `cattle-logging-system` namespace might fall outside of the `Only User Namespaces` option from the Namespaces filter in the header. Could you change that to `All Namespaces` and see if the resource is correctly shown in the list?

If so, we have a UX issue where the overview page doesn't respect the filter at the top (or indicate that it's not restricted) .... but the lists underneath do

**Comment by wombelix** [comment]
@richard-cox thanks for the swift response, I feel stupid that I didn't thought about changing it to `All Namespaces`, if I do that all resources show up. I guess I wasn't thinking about it in regards to cluster wide resources, I expected that they would just always show up independent of the filter. Also I think `Only User Namespaces` is the default filter right?

![Screenshot 2023-05-18 at 13 37 07](https://github.com/rancher/dashboard/assets/16312366/121ec13b-5144-4e56-8ff3-b91fc068117b)
![Screenshot 2023-05-18 at 13 36 58](https://github.com/rancher/dashboard/assets/16312366/6c5238c8-265f-4161-a22d-f7b01011c1e1)

**Comment by richard-cox** [comment]
Correct, `Only User Namespaces` is the default.

We're looking at the general UX of how to show what's restricted by the filter and what's not. Here we should make it more obvious that the Logging root page doesn't take into account the filter. The indication that the child pages with generic lists are affected by the filter will fall under another issue (can't find it at the moment, but i know there's some initial designs).

**Comment by richard-cox** [comment]
The generic issue is https://github.com/rancher/dashboard/issues/6321. We'll close this one and ensure that this use case is fixed by any changes there (https://github.com/rancher/dashboard/issues/6321#issuecomment-1553144473)
