### ISSUE TITLE
User redirected to `Logout` page upon logging in to a server with shared credentials

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#8921]
**Setup**
- Rancher version: v2.7-head (1eb478f)
- Rancher UI Extensions: n/a
- Browser type & version:chrome

**Describe the bug**

Some users are logging in, and redirected to the Login again to continue screen even though their login was successful. This generally has happened for me when someone sends me a cluster to login to for the first time, with a shared user / credentials. If I remove the logout query from the URL or open it in a new tab, I can access the cluster without actually entering login credentials again. 

**To Reproduce**

create a rancher server with some credentials for admin user
log in normally
share your login credentials with another person, have them log in

**Result**
2nd user is redirected to logout screen upon entering correct credentials

**Expected Result**

2nd user should be directed to the home page

**Screenshots**

**Additional context**

Not 100% about reproducible steps at this time, could be intermittent. But I have had this happen on several occasions over the last week
* also reproducible on the same machine by opening an incognito window and logging in there

**Comment by richard-cox** [comment]
I've managed to reproduce this on an old system using `master`. Log in --> automatically logged out --> nav | login again is fine

**Comment by slickwarren** [comment]
I can no longer reproduce this issue on v2.7-head (6ce75a0)
