### ISSUE TITLE
Project list in Cluster and Project Members Page does not show groups

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#8924]
**Setup**
- Rancher version: 2.7-head

**Describe the bug**
Groups that have been assigned a project role are not visible in the `Projects` tab of the `Cluster and Project Members` page

**To Reproduce**
- Setup Github Auth Provider
- Nav to a cluster and create a project
- Add a github org or team to the project
- Nav to Cluster / Cluster and Project Members --> Project tab

**Result**
- No row is shown for the org / team

**Expected Result**
- Row of the org team is shown

**Additional context**
- groups assigned to a cluster role are correctly shown
- it looks like the bug was introduced by https://github.com/rancher/dashboard/pull/8330
  - the project binding will have either userId or groupPrincipalId
  - the code ignores any binding without a userId
  - i've tried a quick fix to also use the groupPrincipalId... however at some point we request the principal for the group but with an invalid id

```
const { userId, roleTemplate, projectId } = curr;

        const userKey = userId + projectId;

        if (!rows[userKey] && userId ) {
          rows[userKey] = curr;
          rows[userKey].allRoles = [];
        }

        if (roleTemplate && userId) {
          rows[userKey].allRoles.push(curr.roleTemplate);
        }
```

**Comment by richard-cox** [comment]
This isn't really a regression in a release version, as the feature is new in 2.7Q2. It's something we shouldn't release though without. Whether it's a release blocker or not is TBC

**Comment by anupama2501** [comment]
Verified on v2.7-head `f0d4078`

1. Created an rke1, rke2 and k3s node driver cluster - 3 nodes 1 etcd, 1 cp and 1 worker.
2. Enabled azure AD auth 
3. Added a few users/groups while creating projects.
4. Verified the users/groups are shown in the project membership as well as from cluster explorer >> Project >> Members
5. Deleted a few users/groups and verified the users/groups were deleted from both project membership and cluster explorer >> projects >> edit config
6. Edited the project and added groups and users, verified the users and groups were updated in both project membership and  cluster explorer >> projects >> edit config
7. Added a few users/groups from Project membership, verified the users and groups were updated in both project membership and  cluster explorer >> projects >> edit config
