### ISSUE TITLE
Custom Istio Deployment Page: 1.7.x UI Requirements

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#894]
Chart.yaml Annotation: 

`catalog.cattle.io/ui-component: istio`

What fields are required/needed for chart deployment?

**Header: Version**
Label Name | Input | Default
-- | -- | --
 Istio Version | DropDown | Most recent version of chart `rancher-istio` from `dev-charts`

**Header: Components**
Label Name | Input 
-- | -- 
Enabled  CNI | Boolean 
Enabled Ingress Gateway | Boolean 
Enabled Egress Gateway | Boolean 
Enabled  Pilot | Boolean 
Enabled  Policy | Boolean 
Enabled  Telemetry | Boolean 

Default values will be pulled from the [values.yaml](https://github.com/rancher/charts/blob/dev-v2.5/packages/rancher-istio/charts/values.yaml) 

**Header: Custom Answers**
Label Name | Input | Default
-- | -- | --
Variable | Text | ""
Value | Text | ""

Variable and value should be in the same row similar to old UI:
![Screen Shot 2020-07-24 at 5 25 15 PM](https://user-images.githubusercontent.com/19455540/88444612-cdee6380-cdd2-11ea-98e0-a6a7055165e8.png)
- Users should be able to add as many variable = value pairs and be able to remove them 

_This will allow additional customizations to the default install_ 

**Header: Advanced Settings**
Label Name | Description | Input | Default | Notes
-- | -- | -- | -- | --
Custom Overlay File | "Provide a IstioOperator yaml with additional components and configuration that is not available with the default installtion" | Yaml Field | "" | stored in values.yaml as string

_This should also have a read from file option_ 

What other dashboard/forms would need to be created to use the feature?
TBD support for Addon Components:

- Grafana

- Kiali

- Prometheus

- Tracing 

What CRDs would need to have a “custom form” so that users wouldn’t only be required to use YAML
N/A

**Comment by cbron** [comment]
Likely not doing addon components

**Comment by bmdepesa** [comment]
rancher/rancher:master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head

* Istio deployment page is missing: 
  * Version selector drop-down
  * istiodRemote setting (should be `False` by default, according to the above requirements)
* Egress Gateway should be `True` by default, currently it is `False'

![Screen Shot 2020-08-18 at 4 04 44 PM](https://user-images.githubusercontent.com/21316915/90574044-ccfbe800-e16c-11ea-906e-3d824ce99df1.png)

**Comment by deniseschannon** [comment]
@bmdepesa there is only 1 version of istio currently in the chart so no version is shown unless there is more than 1 version. 

@brendarearden can you confirm which are the defaults?

**Comment by brendarearden** [comment]
@brandond @deniseschannon originally we were asked for default values, but I believe the defaults are now pulling from the values.yaml - so it should be matching what the enabled: <true/false> is in the values.yaml

**Comment by brendarearden** [comment]
I updated the ticket to remove the default value column and linked out to the values.yaml file. We are also removing the Custom Answers section per this ticket https://github.com/rancher/dashboard/issues/1005.

**Comment by deniseschannon** [comment]
@bmdepesa Based on the comments, I think this can be tested again.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.0-alpha1

* Istio page shows the correct components
* Overlay file editor is shown
* Values YAML editor is shown
* Helm options are shown
