### ISSUE TITLE
Unable to delete Cluster Members from Cluster Management config

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#8940]
**Setup**
- Rancher version: `v2.7-head` - commit `087dd09` - Single node Docker installation 
- Rancher UI Extensions: None installed
- Browser type & version: FF `112.0`

**Describe the bug**

After adding Member Roles to a cluster through the Cluster Management view, I am unable to delete/remove them. There is no column to delete a member which should be available, following the [documentation](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/access-clusters/add-users-to-clusters#editing-cluster-membership).

This behavior is seen with both RKE, RKE2, and k3s clusters.

**To Reproduce**

- Create a user with the Administrator global permission
- Add the user as a Member to a given Cluster's Member Roles (tested with the local cluster)
- Attempt to delete the Member

**Result**
No delete action is provided, unable to delete the member.

**Expected Result**

There should be a column within the Member list that has an action to delete a member.
![expected](https://github.com/rancher/dashboard/assets/40806497/ada502c6-5d67-41a9-a47a-13c77a9587db)

**Screenshots**

___Cluster edit config view___
![edit-cluster](https://github.com/rancher/dashboard/assets/40806497/d0db1d64-085f-4015-9344-42ecfd4d3947)

**Additional context**

Possibly related to https://github.com/rancher/dashboard/issues/8924

___Workaround___
The ability to delete a Cluster member is still available from within the cluster Explorer -> Cluster and Project Members
![workaround](https://github.com/rancher/dashboard/assets/40806497/fc78a4fc-1c45-4ee1-8572-d5e15d27d758)

**Comment by richard-cox** [comment]
I couldn't reproduce with RKE (old ui) or RKE2 (new ui). I've created a fix for K3S - https://github.com/rancher/ui/pull/5028
