### ISSUE TITLE
Charts UI installation page is not scrollable

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#8941]
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
Chart installation page is not scrollable. 

**To Reproduce**
- Navigate to Cluster > Apps
- Select a chart
- Resize screen so UI doesn't fit existing window
- Click through the steps e.g. Metadata / details. Scroll bar is not visible

**Expected Result**
Page should be scrollable 

**Screenshots**

https://github.com/rancher/dashboard/assets/1387263/33708c99-55b2-423b-9f5c-845d6ea1ce63

**Additional context**
Coud be related to following code. There are other CSS that could be interfering. Not sure how wide the impact would be when changing this. 

NB: There is also chart info slide in. So fix could have a wide impact.

 ```
 .install-steps {
    padding-top: 0;
    height: 0;
    position: relative;
    overflow: hidden;
}

```

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 5334be3`
1. naviaged to cluster > apps > charts
2. selected rancher-logging
3. resized chrome web window to small size
4. verified scroll bar is 
   a. visible
   b. scrollable
5. verified in firefox, as well
![2023-06-01_11-07-22.png](https://zube.io/files/rancher/be95fe0f640e61744e9cabd8e196f517-2023-06-01_11-07-22.png)
![2023-06-01_11-20-30.png](https://zube.io/files/rancher/dc3d543453099d0fe7bc4af5b59abd20-2023-06-01_11-20-30.png)
