### ISSUE TITLE
Logging V2 UI

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#895]
Users will need a custom UI for configuring the cluster logging pipeline.

**annotations**
-   catalog.cattle.io/certified: rancher
-   catalog.cattle.io/namespace: logging-system
-   catalog.cattle.io/release-name: rancher-logging
-   catalog.cattle.io/component: logging

**Header: Output**
A dropdown to select from a list of supported outputs is need.  Based on the value of the select one of the multiple output forms will be displayed.  To start only elasticsearch is supported.

**Outputs::elasticsearch**
| Field | Type | Default |
| -----|------|---------|
| elasticsearch.enabled | hidden field set to true | true |
| elasticsearch.host |  string, required | "" |
| elasticsearch.scheme |  drop down http|https | http |
| elasticsearch.port |  int | 9200 |
| elasticsearch.index_name |  string | <cluster name | "rancher-logging"> |
| elasticsearch.user|   string | null |
| elasticsearch.password |  password | null |
| elasticsearch.client_cert |  string | null |
| elasticsearch.client_key |  string | null |
| elasticsearch.client_key_pass |  string | null |

Additional outputs will be needed as they are supported.

**Comment by cbron** [comment]
There will be more providers as we continue to develop. They can be added here or in separate issues.

**Comment by codyrancher** [comment]
@paynejacob `catalog.cattle.io/component: logging` is supposed to be `catalog.cattle.io/ui-component: logging`

**Comment by codyrancher** [comment]
Here's a screenshot of what we have for now. Let me know if there's anything we want changed.

![Screen Shot 2020-08-03 at 4 07 52 PM](https://user-images.githubusercontent.com/55104481/89236686-19102f80-d5a6-11ea-89d9-58a52a7e12e6.png)

**Comment by paynejacob** [comment]
Additional Outputs

**Outputs::kafka**
| Field | Type | Default |
| -----|------|---------|
| kafka.enabled | hidden field set to true | true |
| kafka.brokers | string | blank |
| kafka.default_topic | string | cattle-logging-system |
| kafka.sasl_over_ssl | bool | false |
| kafka.scram_mechanism | string | PLAIN |
| kafka.username | string | blank |
| kafka.password | string | blank |
| kafka.ssl_ca_cert | string | blank |
| kafka.ssl_client_cert | string | blank |
| kafka.ssl_client_cert_chain | string | blank |
| kafka.ssl_client_cert_key | string | blank |

**Outputs::splunk**
| Field | Type | Default |
| -----|------|---------|
| splunk.enabled | hidden field set to true | true |
| splunk.host | string | blank |
| splunk.port | int | 8088 |
| splunk.protocol | string | http,https |
| splunk.index | string | cattle-logging-system |
| splunk.token | string | blank |
| splunk.client_cert | string | blank |
| splunk.client_key | string | blank |
| splunk.insecure_ssl | bool | false |

**Outputs::syslog**
| Field | Type | Default |
| -----|------|---------|
| syslog.enabled | hidden field set to true | true |
| syslog.address | string | blank |
| syslog.cluster | bool | true |
| splunk.root_ca | string | blank |

**Comment by deniseschannon** [comment]
@paynejacob @cbron Instead of constantly adding to this ticket, can we open new tickets for new providers so that each provider could be tested by QA?

@lvuch For selecting provider, I'd like to be able to use either the graphical boxes that we have for 2.4 logging or using the side tab style to be able to see all options available instead of using a dropdown. 

Is there a way we could group these boxes to be prettier?

**Comment by deniseschannon** [comment]
I think this ticket is irrelevant at this point based on the changes going on in deployment, output/clusterouput, etc. 

@paynejacob if you think otherwise, please let me know.

**Comment by paynejacob** [comment]
I agree this is covered by https://github.com/rancher/dashboard/issues/1109
