### ISSUE TITLE
Solve issue with flaky tests for preferences runs

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8957]
# Description

Solve issue with flaky tests for preferences runs. The error occurs on initialization of the test, in some cases also after 3 attempts.

![Screenshot 2023-05-23 at 08 38 19](https://github.com/rancher/dashboard/assets/5009481/0a2ccdfb-7fc0-4838-9a82-9fb4d9ab5fb1)
![Screenshot 2023-05-23 at 08 44 12](https://github.com/rancher/dashboard/assets/5009481/4ef44fb6-f3cd-4c98-917b-f5ad836991d2)

**Comment by richard-cox** [comment]
User avatar related, should be resolved via https://github.com/rancher/dashboard/pull/9718
