### ISSUE TITLE
[BUG] /login redirects to /dashboard, breaking auth provider logins

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/dashboard#8964]
**Setup**
- Rancher version: 2.7.3
- Rancher UI Extensions: None
- Browser type & version: Firefox v113.0 (though this appears to affect various browser types and versions)

**Describe the bug**
Requests made to `/login` redirect to `/dashboard` instead of processing a login request. This causes issues where login requests (particularly though the rancher cli for SAML providers) fail, resulting in users not being able to use the rancher cli to login. 

**To Reproduce**
1. Setup a basic rancher install.
2. Enter the bootstrap password and complete basic initialization.
3. Go to `$RANCHER/login` in your browser.

**Result**

You are redirected to `/dashboard`

**Expected Result**
As in v2.7.1 the old `/login` page is displayed.

**Screenshots**
N/A.

**Additional context**
This appears to be the cause of rancher/rancher#41520. The use of the old login page is necessary to pass along/create the `finalRedirectURL`, which is required input in the SAML login function. Without this, users are unable to use the rancher cli to login.

For a more complex repro setup that fully shows the issue that we encountered, [integrate okta](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-okta-saml#docusaurus_skipToContent_fallback) and use the [rancher cli](https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/rancher-cli#docusaurus_skipToContent_fallback) to login. You will notice that it gives you a url to access in the browser - this URL will not work as it does in 2.7.1. 

SURE-6385

**Comment by MbolotSuse** [comment]
As mentioned in https://github.com/rancher/rancher/issues/41520#issuecomment-1560247884 - if the UI is reverted to use the 2.7.1 version, the issue is resolved (in case anyone needs a workaround).

**Comment by mantis-toboggan-md** [comment]
Additional context on why this redirect was added: https://github.com/rancher/dashboard/issues/7293

**Comment by nwmac** [comment]
@MbolotSuse Can you give steps to reproduce this - I don't see clear repo steps.

Is the the Rancher CLI? I've tried the latest Rancher CLI and I can't see where it would use the `/login` URL.

We put the redirect in place at the request of another user - see above.

We can update that to ensure the CLI still works, but I don't have repro steps.

**Comment by MbolotSuse** [comment]
@nwmac The repro steps included in the issue are accurate/minimal for the core of the issue - even on a basic rancher install going to `/login` redirects you to `/dashboard` for 2.7.3, and doesn't on 2.7.1. I can get you more repro steps on the exact issue that this causes for the rancher cli/saml integration, but the above is the root cause of the issue. I'll reply in a separate comment for the okta/saml issue.

**Comment by nwmac** [comment]
@MbolotSuse That change is deliberate. `/login` is served by the old Ember UI which is not supported, so it was changed to redirect to the new UI.

Sounds like the best thing to do here is to update the CLI to use the new login URL.

**Comment by MbolotSuse** [comment]
@nwmac That's an option that we can discuss. The issue there is that it breaks everyone using the old CLI on version 2.7.3, and means that 2.7.3's [Dockerfile](https://github.com/rancher/rancher/blob/bbba80e2a0d6dd9bb5494060a45877bcbb2eafc5/package/Dockerfile#L164) refers to an invalid cli version. This is definitely not optimal. Let me get you those repro steps you asked for and then we can discuss offline what we want to do in the long term.

**Comment by nwmac** [comment]
Perfect - thanks

**Comment by nwmac** [comment]
This will need to be manually tested via the steps above using the CLI.
