### ISSUE TITLE
Move AKS from Ember to Vue

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8965]
In support of moving all public cloud provisioning off Ember (https://github.com/rancher/dashboard/issues/8083 and in a way, tied to work for finding all pages off Ember in https://github.com/rancher/dashboard/issues/8718), this ticket is to move the AKS pages to being in Vue. 

Currently, to provision AKS, it's iFramed from Ember into Vue.

Original embedding work: https://github.com/rancher/dashboard/issues/2738

**Comment by gaktive** [comment]
We should start this in Q3 but it will likely land in Q4. I need to link to various other AKS tickets that should be handled as part of this work.

**Comment by gaktive** [comment]
@nwmac this ticket looks like it skipped QA and stayed close. However, QA has been testing parts of this as evidenced by linked issues. Should we put this back To Test?

**Comment by nwmac** [comment]
Yes, we should

**Comment by valaparthvi** [comment]
I am not sure if there is sure shot way of testing this. We have already filed a few UI bugs, after running an entire test suite on 2.9, I believe this issue can be marked as complete. I will close it.
