### ISSUE TITLE
Move GKE from Ember to Vue

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8967]
In support of moving all public cloud provisioning off Ember (https://github.com/rancher/dashboard/issues/8083 and in a way, tied to work for finding all pages off Ember in https://github.com/rancher/dashboard/issues/8718), this ticket is to move the GKE pages to being in Vue. 

Currently, to provision GKE, it's iFramed from Ember into Vue.

Original embedding work: https://github.com/rancher/dashboard/issues/2749

**Comment by gaktive** [comment]
Will need to factor other tickets like:
- rancher/dashboard#9507

**Comment by nwmac** [comment]
@mantis-toboggan-md Moving to your next-up for you to schedule with Eva.
