### ISSUE TITLE
Solve issue with flaky tests for account api keys spec

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8976]
# Description

Issue seems related to the logout case (https://github.com/rancher/dashboard/issues/8975) as it cannot find the user menu dropdown.

<img width="1384" alt="Screenshot 2023-05-24 at 20 24 06" src="https://github.com/rancher/dashboard/assets/5009481/e9d7778a-3af0-462f-9dd4-0a66dc587ec9">

**Comment by richard-cox** [comment]
User avatar related, should be resolved via https://github.com/rancher/dashboard/pull/9718
