### ISSUE TITLE
Docs: Whats-New: What's new page contents not loading when using local env setup

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#8979]
**Setup**
- Rancher version: v2.7.2
- Dashboard version: v2.7.2
- Browser type & version: Any

**Describe the bug**
What's new page contents not loading when using local env setup. User lands on blank page.

**To Reproduce**
- create instance of Rancher Dashboard locally (https://localhost:8011)
- login to Rancher UI as an admin/standard user
- go to What's new page by clicking 
"What's new in 2.7" link (or go directly to https://localhost:8011/docs/whats-new)
- note page is blank

**Result**
What's new page contents not loading when using local env setup.

**Expected Result**
What's new page contents load when using local env setup.

**Screenshots**
![Screen Shot 2023-05-23 at 4 39 21 PM](https://github.com/rancher/dashboard/assets/127343932/c2b586bd-9b63-48cf-80cf-d70717f3d75b)

**Additional context**
The page loads fine when using remote env setup.
Passes: https://yonasb.qa.rancher.space/dashboard/docs/whats-new
Fails: https://localhost:8011/docs/whats-new

**Comment by richard-cox** [comment]
This might be a localhost only issue, but we should validate before the release. It might be the nuxt removal has broken this feature

**Comment by yonasberhe23** [comment]
Fix Verified -

What's new page contents load in local and non-local setups.

<img width="1508" alt="Screen Shot 2023-05-26 at 4 38 55 PM" src="https://github.com/rancher/dashboard/assets/127343932/66709a02-6444-421a-9461-7bada721a442">
