### ISSUE TITLE
Improve Vue directives loading/support in regards to Extensions

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#8995]
**Is your feature request related to a problem? Please describe.**
Improve how Rancher Dashboard handles `Vue directives`, in general, so that they work with extensions in versions of Rancher Dashboard where the imports of the directives themselves are not available (older versions). Also check other logic on [initialize file](https://github.com/rancher/dashboard/blob/master/shell/initialize/index.js) that might have a direct impact on Extensions.

**Additional context**
To address the issue that lead to this problem (inclusion of the `v-clean` directives) - running extensions on a system that doesn't have these imports present - a possible workaround is to include the imports of the said directives directly on each extension [example here](https://github.com/rancher/elemental-ui/pull/116/files)

**Comment by nwmac** [comment]
@aalves08 Is there anything to do here, now that https://github.com/rancher/dashboard/pull/9928 has merged?

**Comment by aalves08** [comment]
This issue can be closed as the fix has been applied from https://github.com/rancher/dashboard/pull/9928 related to issue https://github.com/rancher/dashboard/issues/9920
