### ISSUE TITLE
Monitoring Receiver SSL text renders poorly

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8998]
See below:

<img width="1214" alt="image" src="https://github.com/rancher/dashboard/assets/1955897/8e8ab5bb-4d5a-4c76-a0a3-a8b1ff13a05f">

The text for the SSL section has a scrollbar and is generally poorly presented.

Purely visual, so dev team can manually validate fix.

**Comment by gaktive** [comment]
Could be related to recent changes to `v-html` and localization text.

**Comment by gaktive** [comment]
Some improvement has been made but the code block still looks off.

**Comment by nwmac** [comment]
Some improvements have been made - but there is no spacing now between pieces:

![image](https://github.com/rancher/dashboard/assets/1955897/327efa8f-ab64-4682-9271-91a6596ae046)
