### ISSUE TITLE
Changes made while editing RKE1/EKS cluster and fleet agent config are not saved in certain circumstances

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#9003]
To Reproduce:
1. Create an RKE1 cluster with cluster agent resource requests defined
2. Edit the cluster, clear out the resource request inputs, define some resource limits, and save
3. Edit the cluster again, note that the new values were not saved

This appears to apply to each section of cluster/fleet agent configuration. While editing, if the user clears out previously-set values then adds new ones to the same section, the new values are not saved. Editing the cluster again and setting those values works.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 027246f
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1 cluster

----------

### Testing: ###
Tested this issue with the following steps:
1. Create an RKE1 cluster with cluster agent resource requests defined
2. Edit the cluster, clear out the resource request inputs, define some resource limits, and save

**Result**
The new config changes are now saved and the cluster comes up active after updating.
