### ISSUE TITLE
When Adding SSH Public and Private keys via the GIT Repo Config page, SSH key ends up as null.

### ISSUE THREAD

**Issue by rfutterman91** [rancher/dashboard#9009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to connect my AWS Code Commit repo to Rancher Fleet GIT Repos. I enter in my public and private keys in OPENSSH format. Once I save and look back at the config it shows SSH Key: Null

This is the Error I see on the Git Repo dashboard:

Git ls-remote  ssh://git-codecommit.us-gov-west-1.amazonaws.com/v1/repos/linc-noss-fleet  refs/heads/main error: exit status 128, detail:  gitjob@git-codecommit.us-gov-west-1.amazonaws.com: Permission denied  (publickey).  fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

the repository exists as I am copying it from AWS CodeCommit

### Expected Behavior

SSH Keys to be generated properly

### Steps To Reproduce

1. Continuous Delivery > Git repo > Add Repository
2. Use SSH keys generated from AWS Code Commit in OpenSSH format
3. Save 
4. Look at the config for the repo and notice 'SSH Key: null'

### Environment

```markdown
- Architecture:
- Fleet Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by sbulage** [comment]
I am able to see the secrets created via `GitRepo` UI page, already created secrets (`http/ssh`) both are populated. Also, used them in order to deploy applications from private GitHub repository.

![Selection_103](https://github.com/rancher/dashboard/assets/12134754/34a6d1d4-0deb-40d5-8405-448b3886d95a)
