### ISSUE TITLE
Questions.yaml support

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#901]
* Questions.yml support
* Need a nice Cluster Catalog form

**Comment by deniseschannon** [comment]
Datatypes that are working:
String
Int
Bool
Enum
Hostname
Multiline
Password

The remaining types and validation should be: https://github.com/rancher/dashboard/issues/1097

**Comment by jiaqiluo** [comment]
This feature is validated on rancher:`master-198ec5bdf52d3ed2b4865cfcf6ac1d61150bf55f-head` HA setup 

All the abovementioned types are recognized properly by the UI in the dashboard 
- String
- Int
- Bool
- Enum
- Hostname
- Multiline
- Password
