### ISSUE TITLE
Show custom favicon on loading page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9024]
- User can supply a custom favicon via Global Settings --> Branding --> Favicon
- Previously this could only be applied post loading screen, as loading screen was controlled by nuxt land(?)
- We can do something similar to how the theme works
  - Theme is applied from a THEME preference
  - If THEME is AUTO use the PCS value instead
  - PCS value is set when UI is loaded
  - Both THEME and PCS prefs are configured to be cookies 
- Translating to this feature
  - we could have a FAVICON cookie which is set from the pref once we load
  - `shell/public/index.html` could look at this cookie for a url to use
  - this would mean the initial load shows the default / stale favicon... but subsequent loads are fine

**Comment by nwmac** [comment]
I'm going to close this as won't fix - if you feel strongly that we should do this, please re-open

**Comment by richard-cox** [comment]
This was primarily for epinio, where the rancher icon flashed up before it was replaced with the epinio one
