### ISSUE TITLE
Bump storybook from 6.3.8 to 7.0.6

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9037]
Francesco had been bumping dependencies in https://github.com/rancher/dashboard/issues/4534

Storybook is left to bump: https://github.com/rancher/dashboard/pull/8715

**Comment by gaktive** [comment]
Later on, we can look at more recent versions (as of writing: 8.2.1 is the latest) but this solves our dependencies issue.

**Comment by cnotv** [comment]
Storybook is currently `^7.6.17`.
