### ISSUE TITLE
Out of tree EBS CSI Driver option when creating EKS cluster from Rancher UI

### ISSUE THREAD

**Issue by salasberryfin** [rancher/dashboard#9043]
Internal reference: SURE-6472

**Is your feature request related to a problem? Please describe.**
With EKS v1.23 and higher, it requires the use of the out of tree EBS CSI driver. If this isn't available then and PVC will not be bound and pods using the volumes will stay in pending.

This is a problem for creating new clusters and for upgrading clusters from 1.22

**Describe the solution you'd like**
This is a feature request coming from a change in the `rancher/eks-operator`.

A new spec field will be added to [rancher/eks-operator](https://github.com/rancher/eks-operator) (PR is already being reviewed) that, if set to true, enables the EBS CSI Driver for the new EKS cluster allowing to integrate the use of EBS volumes with EKS. If the user doesn't set this parameter, it can be considered as false and the operator won't install the addon and will operate as usual.

This issue was discussed in [rancher/eks-operator](https://github.com/rancher/eks-operator/issues/106#issuecomment-1541787351) and has been implemented as an optional installation (as is the case when using the AWS console).

The solution is based on:
- A boolean field added to EKSClusterConfigSpec [EBSCSIDriver](https://github.com/rancher/eks-operator/blob/74b09dfe65081cfb101ba678c9ffd59fba8410bd/pkg/apis/eks.cattle.io/v1/types.go#L46). This is the change that requires to update the EKS create cluster UI to have an option to set this new spec.
- If set to true, the EBS CSI driver for EKS will be installed after the cluster is created.

**Describe alternatives you've considered**

**Additional context**
The PR for the changes in the `eks-operator` can be found in rancher/eks-operator#170

**Comment by richard-cox** [comment]
@salasberryfin What release will the changes be available in?

**Comment by salasberryfin** [comment]
Hi @richard-cox. This change has not been merged into the operator's main branch yet. This is a feature so, barring any unexpected issue, this will be included in the next release of the `eks-operator`.

**Comment by salasberryfin** [comment]
@richard-cox Operators have their own releases but these are then part of a global Rancher release.

**Comment by richard-cox** [comment]
@salasberryfin Ok, guessing this won't make it in to Rancher's 2.7.5. Adding target of 2.7q3

**Comment by gaktive** [comment]
Internal reference: SURE-6472

**Comment by gaktive** [comment]
As I understand, we're blocking backend on this, rather than us being blocked. Based on timelines, Q1 is more realistic here but @kkaempf can you tell us the priority from your end?

**Comment by salasberryfin** [comment]
Hi @richard-cox, what are the specific changes you were expecting in the operator? We created a new release candidate of the `eks-operator` for v2.8 last week that will be now validated by QA https://github.com/rancher/charts/commit/d9dd8680f291bc45306c98578ef4716d110f863e

**Comment by richard-cox** [comment]
@salasberryfin Looks like the requirement is to add a new field to a spec somewhere. We'd like to setup Rancher and make use of it.

Would you also be able to clarify which resource it should be added to?

**Comment by salasberryfin** [comment]
@richard-cox sorry, I didn't understand your question initially. This new spec field is available in latest pre-release of Rancher v2.7.7-rc4 https://github.com/rancher/rancher/releases/tag/v2.7.7-rc4 which includes `rancher/eks-operator v1.2.2-rc3`.

With this change, [EKSClusterConfigSpec](https://github.com/rancher/eks-operator/blob/020eea58af00bb88a00ba1e8a1de0c3ef174ab7c/pkg/apis/eks.cattle.io/v1/types.go#L46) includes a boolean field `ebsCSIDriver` that the user will configure from the dashboard. This can be implemented in rancher/dashboard as a checkbox during EKS cluster creation in the `Cluster Options` section as `Enable EBS CSI Driver` with a default value of false.

Just as a reference, I'm thinking about something similar to this:

![image](https://github.com/rancher/dashboard/assets/10220061/9167f25c-b5fe-4a3a-9726-4ea468322dcd)

Let me know if there's anything else I need to clarify.

**Comment by richard-cox** [comment]
@salasberryfin Perfect, thanks! We have this targetted at 2.8.next1 atm. Will leave to @kkaempf / @gaktive to confirm

**Comment by gaktive** [comment]
Will assess on when to do this with regards to porting EKS to Vue but current thinking is that we should add this into Ember, then include as part of the migration after.

**Comment by cpinjani** [comment]
Validation passed on build:
```
Rancher - v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head
Dashboard - master 102f1e6
```
Able to set Out of tree EBS CSI Driver option when creating EKS cluster from Rancher UI and respective value is sent via payload `ebsCSIDriver:true`. Back-end validation is tracked under https://github.com/rancher/eks-operator/issues/106

![image](https://github.com/user-attachments/assets/0e8eb147-bcf5-4842-8630-85a770a82fab)
