### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by vtrenton** [rancher/dashboard#9059]
**Setup**
- Rancher version: 2.7.3
- Rancher UI Extensions: N/A
- Browser type & version: Chrome/Firefox latest

**Describe the bug**

When navigating to the Continuous Delivery section of the UI - if you have a manifest that is missing a repo value in the `spec.repo` of the GitRepo manifests the page will not display the list of objects. in the dev console you will see an error repeating:
`TypeError: Cannot read properties of undefined (reading 'replace')`

*workaround*
Update all of your GitRepo manifests in the local cluster and assure the spec.repo field is filled in with a valid repo or delete that GitRepo object.

**To Reproduce**

 - create a gitrepo with the spec.repo = ''
 - navigate to the Continuous Delivery section in the UI
 - go to the namespace that the bad gitrepo is in
 
**Result**
the page will not populate with the gitrepos and the console logs will be littered with vue.js errors

**Expected Result**

list the resources without error

**Screenshots**

![gitrepo-ui-error](https://github.com/rancher/dashboard/assets/85969349/32d73d18-f2bd-40df-8e6d-a48772f896f6)

**Comment by richard-cox** [comment]
We need to ...

1) Validate this is still an issue with the latest code
2) Understand if the git repo spec.repo field is mandatory or optional
3) Update the git repo edit  component to cater for above (if mandatory don't allow creation until supplied)
4) Ensure the list doesn't fail to render if existing git repos don't have the field

**Comment by gaktive** [comment]
We can add a unit test for this.

**Comment by sbulage** [comment]
I am not able to reproduce it on `Rancher 2.7.7-rc2`.

**Comment by sbulage** [comment]
> We need to ...
> 
> 1. Validate this is still an issue with the latest code
> 2. Understand if the git repo spec.repo field is mandatory or optional
> 3. Update the git repo edit  component to cater for above (if mandatory don't allow creation until supplied)
> 4. Ensure the list doesn't fail to render if existing git repos don't have the field (make the git repo model getter falsy safe)

IMO, Repository field should be mandatory, as this is the main entity.

**Comment by sbulage** [comment]
Not reproducible on Rancher version, please re-open if it still persists. Thanks :)
