### ISSUE TITLE
Can not see "Run Now" button

### ISSUE THREAD

**Issue by bpavra5992** [rancher/dashboard#9062]
Hello, 

I am using Rancher 2.7.3 and I have developed cronjob using yaml. I can see my cronjob under cronjob tab. However I dont see "Run now" button. What could be the reason?

Any help would be appricated!

**Comment by nwmac** [comment]
Do you have the necessary permissions?

You should be able to right-click on the three dots next to your cronjob and chose 'Run Now": e.g.:
![image](https://github.com/rancher/dashboard/assets/1955897/677d88b5-5fb8-403b-b1ba-22468a26683e)

Please re-open if this still does not work.
