### ISSUE TITLE
App - cannot edit apps, url in the request is wrong

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#907]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- run Rancher master-head in HA mode
- go to the local cluster 
- go to the dashboard 
- deploy the monitoring v2 app into the local 
- after the app is deployed, try to edit it as either Yaml or Form
<img width="299" alt="Screen Shot 2020-07-27 at 1 14 15 PM" src="https://user-images.githubusercontent.com/6218999/88587742-463f6980-d00b-11ea-83fe-61ad52960409.png">

**Result:**
- the UI jumps to the edit page but shows data is empty
<img width="290" alt="Screen Shot 2020-07-27 at 12 39 21 PM" src="https://user-images.githubusercontent.com/6218999/88587788-5ce5c080-d00b-11ea-95b1-da71b53c6e2e.png">

- check the GET request, there is a `v1/undefined` part in the URL , and `404` is retuend
<img width="947" alt="Screen Shot 2020-07-27 at 12 40 14 PM" src="https://user-images.githubusercontent.com/6218999/88587860-7981f880-d00b-11ea-922b-e64fced5f0f1.png">

**Comment by cbron** [comment]
Would like to confirm that an update form will exist, which would be the same as create form, so that I can update an app by changing its values without upgrading the version. This would mirror v1 behavior.

**Comment by izaac** [comment]
Edit as YAML is working for `rancher-logging`

**Comment by bmdepesa** [comment]
rancher/rancher:master-head (65a2b808c)

I do not see Edit as YAML / Form on `rancher-istio`, or any other installed apps in the dashboard.

**Comment by jiaqiluo** [comment]
on rancher/rancher:`master-3411-head` 

the edit buttons are gone  for the monitoring app 

<img width="1645" alt="Screen Shot 2020-08-05 at 4 59 25 PM" src="https://user-images.githubusercontent.com/6218999/89475689-899d8480-d73d-11ea-9d38-ba5803b981a5.png">

**Comment by vincent99** [comment]
Upgrade does not exist yet.  It will work similar to create.  Editing the release resource is not the right way to upgrade.

**Comment by izaac** [comment]
`rancher-logging` actions are: Upgrade, View, Download, Delete

**Comment by jiaqiluo** [comment]
the bug fix is validated on `rancher/rancher:master-3426-head`


instead of `edit`,  the `upgrade` button shows in the list  


![image](https://user-images.githubusercontent.com/6218999/89674965-ef088700-d89d-11ea-8e01-a8cc20998455.png)
