### ISSUE TITLE
[e2] Reduce load on github runners by serving built ui

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9073]
- Currently e2e tests build and runs the dashboard via `start:prod`
- This was a good place to start, but we're seeing longer running tests. This could be due to resource issues on the runner (running dashboard, rancher and cypress all together)
- To help we should be able to remove the need to serve up dashboard by using rancher's built in process. So we would need to
  - do a prod build of dashboard to a specific location
  - when we bring up rancher via docker map that location to the location in the rancher container that serves up the embedded dashboard
  - we would need to ensure the embedded version is used (this should be possible by supplying a `CATTLE_` env var). details of this to follow

**Comment by nwmac** [comment]
@richard-cox Can this be closed?

**Comment by richard-cox** [comment]
Sorry, forgot about the issue. 

Completed via https://github.com/rancher/dashboard/pull/9063
