### ISSUE TITLE
Exclude metadata.managedFields from steve request

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/dashboard#9074]
**Is your feature request related to a problem? Please describe.**
This feature is only to add additional performance to front end request to the Steve API

**Request**
When requesting resources from Steve with `/v1` Users have the ability to exclude specific fields with this feature
https://github.com/rancher/steve/pull/46

One field that users rarely use is `metadata.managedFields` This field can be very verbose and greatly increase the size of a payload. So much so that kubectl does not include this field by default see https://github.com/kubernetes/kubernetes/issues/90066

**Describe the solution you'd like**
On `v1` request if the UI uses the steve exclude flag they could decrease the size of payloads pulled back.
`/v1/configmaps?exclude=metadata.managedFields`

**Comment by richard-cox** [comment]
https://github.com/rancher/dashboard/issues/6490 is the root issue to make use of the `exclude` field. 

This field was referenced from there, and after a very brief check I think we're safe to remove this (confirmation required).

@gaktive / @nwmac I know we're keeping q3 slim, it would be nice to bring this one in for 2.7q3 though. Is there any bandwidth?

**Comment by kwwii** [comment]
This probably requires an E2E test as well.

**Comment by MSpencer87** [comment]
Verified on 2.7.7-rc4, rke2 1.26.7


The v1/{resource}?exclude=metadata.managedFields is present on Steve API calls

Steps to validate:

1) Bring up HA Rancher setup on 2.7.7-rc with two downstream clusters
2) Navigate to the Cluster Management page, open the browser development tools to the Network tab
3) Refresh page, select search icon and filter for 
https://your.request.url/v1/
4) Verify ?exclude=metadata.managedFields is present on Steven API calls (v1) as seen in screenshot
![screenshot](https://github.com/rancher/dashboard/assets/6477538/b155c1f6-44be-4715-9bc3-21b6e8689a3e)
