### ISSUE TITLE
Rancher UI Continuous Delivery does not sync/show cluster labels

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9077]
Internal reference: SURE-6102
Reported in 2.7.1

Rancher UI Continuous Delivery does not sync/show cluster labels

Repro steps:

Test 1
-  Continuous Delivery > Clusters> Select cluster > Vertical elipsis(...) >Edit YAML > add labels: `"zone: europe", ct: spain, env:pro"`
- Labels are added but not populate in the Rancher UI cluster Config. 

![RKE1Confignolabels.png](https://zube.io/files/rancher/c29bae8096f11c3244741a672cfe8dc9-rke1confignolabels.png)

- However, the labels are populated in the Rancher UI cluster Detail. 

![RKE1labelsDetails.png](https://zube.io/files/rancher/dfbd802b6a5b63d5c037a0d2f4394d7b-rke1labelsdetails.png)

Test 2

- Continuous Delivery > Clusters> Select cluster > Vertical elipsis(...) > Edit Config > Add Label > `ct=italy` > Save{}
- The user edits again the cluster configuration using the yaml file and remove the label. The cluster yaml file does not shows the label 

![clusteryamlfile-labelremoved.png](https://zube.io/files/rancher/f72cca39f2465c8ebf1b06f455a4e7bc-clusteryamlfile-labelremoved.png)

 but a couple of minutes later the label is recreated

![clusteryamlfile-labelrecreated.png](https://zube.io/files/rancher/50c1a2b0ca215fbc37d39c465d835ade-clusteryamlfile-labelrecreated.png)

Workaround:
Yes. Labeling cluster with kubectl 

Actual behavior:
Rancher UI Config cluster does not show accurate/updated information

Expected behavior:
Cluster Config-Cluster yaml file and Cluster Details should show the same information

Additional notes:
They were able to reproduce this issue, and it seems there is some bug/glitch with the Rancher UI config tab. The Rancher UI config tab doesn't populate the information correctly.

However, by adding a label through editing YAML and tested it by creating a cluster group with the same label rules, it works fine. kubectl also fetch the labels correctly.

**Comment by kwwii** [comment]
We should investigate how we are settings labels and how they are being read first to understand this better.

**Comment by sbulage** [comment]
I see change of label in the YAML and UI is not happening. See below screenshot for more information.
P.S. Difference screenshot taken after 1 hr to check any update happens to the label.

![Selection_068](https://github.com/rancher/dashboard/assets/12134754/cbaa025f-16a1-4bb6-889f-e0c803bbd1d9)

Kubectl output:
```
satya@opensuse15:~> kubectl get clusters.fleet.cattle.io  -n fleet-default   imported-cluster-1 --show-labels 
NAME                 BUNDLES-READY   NODES-READY   SAMPLE-NODE                LAST-SEEN              STATUS   LABELS
imported-cluster-1   2/2             1/1           k3d-k3s-default-server-0   2023-08-18T04:48:09Z            ct=fleet-testing,env=prod,management.cattle.io/cluster-display-name=imported-cluster-1,management.cattle.io/cluster-name=c-<name>,objectset.rio.cattle.io/hash=<hash>,provider.cattle.io=k3s,zone=mars
```
