### ISSUE TITLE
Rancher UI defined roletemplate rules for nonResourceURLs incorrectly have apiGroups definition present, preventing creation of the role in clusters when granted to users

### ISSUE THREAD

**Issue by axeal** [rancher/dashboard#9078]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.4.0+ instance with a single all role node custom cluster (I used https://github.com/superseb/tf-do-rancher2/)
2. Under Global -> Security Roles -> Clusters, click `Add Cluster Role`
3. Add a single Resource Grant with `Get` on the Non-Resource URL `/metrics` and remove the `*` in the API Groups field.
4. Grant this new cluster role to a user on the custom cluster.

**Result:**

The roletemplate generated by the UI has a blank, rather than absent `"apiGroups": [""]`, entry, per the following example:

```json
{

    "administrative": false,
    "annotations": {
        "cleanup.cattle.io/rtUpgradeCluster": "true",
        "lifecycle.cattle.io/create.mgmt-auth-roletemplate-lifecycle": "true"
    },
    "baseType": "roleTemplate",
    "builtin": false,
    "clusterCreatorDefault": false,
    "context": "cluster",
    "created": "2020-12-02T16:07:01Z",
    "createdTS": 1606925221000,
    "creatorId": "user-cpgf6",
    "description": "",
    "external": false,
    "hidden": false,
    "id": "rt-h759b",
    "labels": {
        "cattle.io/creator": "norman"
    },
    "links": {
        "clusterRoleTemplateBindings": "…/v3/clusterRoleTemplateBindings?roleTemplateId=rt-h759b",
        "clusters": "…/v3/clusters?defaultClusterRoleForProjectMembers=rt-h759b",
        "projectRoleTemplateBindings": "…/v3/projectRoleTemplateBindings?roleTemplateId=rt-h759b",
        "remove": "…/v3/roleTemplates/rt-h759b",
        "self": "…/v3/roleTemplates/rt-h759b",
        "update": "…/v3/roleTemplates/rt-h759b"
    },
    "locked": false,
    "name": "kube-apiserver metrics",
    "projectCreatorDefault": false,
    "rules": [
        {
            "apiGroups": [
                ""
            ],
            "nonResourceURLs": [
                "/metrics"
            ],
            "type": "/v3/schemas/policyRule",
            "verbs": [
                "get"
            ]
        }
    ],
    "type": "roleTemplate",
    "uuid": "f12c71c5-2c80-44c9-9878-12a2be88e81c"

}
```

As a result of this incorrectly present `apiGroups` definition, for a `nonResourceUrls` rule the clusterole creation will fail when the custom role is granted to a user, with the following error in the rancher server logs:

```
2020/12/02 16:08:07 [INFO] [mgmt-auth-crtb-controller] Updating clusterRoleBinding clusterrolebinding-bnxwk for cluster membership in cluster c-dpvk7 for subject u-fqrkx
2020/12/02 16:08:07 [INFO] Creating clusterRole for roleTemplate kube-apiserver metrics (rt-h759b).
2020/12/02 16:08:07 [ERROR] ClusterRoleTemplateBindingController c-dpvk7/crtb-25kdp [cluster-crtb-sync] failed with : couldn't ensure roles: couldn't create clusterRole rt-h759b: ClusterRole.rbac.authorization.k8s.io "rt-h759b" is invalid: rules[0].nonResourceURLs: Invalid value: []string{"/metrics"}: rules cannot apply to both regular resources and non-resource URLs
```

Same error occurs if you leave the default API Group `*` definition in the form. Removing the `apiGroups` definition from the rule in the role via the API browser, the role and binding is successfully created in the custom cluster.

**Other details that may be helpful:**

When entering a `Non-Resource URL` in the Add Role UI form, the `Resource` field is automatically disabled. The same should occur the API Groups field and no `apiGroups` array should be submitted to the API by the UI for this rule.

The current workaround is to create the role via the API directly.

**Environment information**
- Reproduced with Rancher v2.4.0, v2.4.10 and v2.5.3

**Comment by richard-cox** [comment]
The solution to this should cover global, cluster and project role creation (because they all pretty much use the same base resource type and components)

**Comment by gaktive** [comment]
Pushing to Q4 as this has been floating around for a while.

**Comment by nwmac** [comment]
@bisht-richa I don't think you've started this - assigning to @Sean-McQ

**Comment by Priyashetty17** [comment]
Re-opening this issue since the following scenario where providing input for only the "Verb" is not working as expected for Cluster Role, Porject Role and Global Role:
| Verb  | Resource           | API Groups           | Non-Resource URLs | Expected Result                                                                                                           | 2.8-head Actual Result                                                                                                    |
|-------|--------------------|----------------------|-------------------|---------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------|
| Get     |                    |                      |                      | Verify following error is displayed in the UI: "You must specify at least one Resource, Non-Resource URL, or API Group for each resource grant". Also, verify that the Create button is disabled | 🔴 Fail|

- UI lets you create the role template.
- There is no error message displayed in the UI when only the verb is updated and the rest of the fields are not updated. 
- Role template yaml has this:
```
rules:
  - apiGroups:
      - ''
    verbs:
      - get
```
- Rancher log has this when the user with the **cluster** role was added to the downstream cluster: 
```
Wed, Oct 11, 2023, 1:15:42 pm: [INFO] [mgmt-auth-crtb-controller] Creating clusterRoleBinding for membership in cluster c-m-dz2fb5vb for subject u-ccw9k 
Wed, Oct 11, 2023, 1:15:43 pm: [INFO] Creating clusterRole for roleTemplate rt5 (rt-ckv2m). 
Wed, Oct 11, 2023, 1:15:43 pm: [ERROR] error syncing 'c-m-dz2fb5vb/crtb-m7mnt': handler cluster-crtb-sync: couldn't ensure roles: couldn't create clusterRole rt-ckv2m: ClusterRole.rbac.authorization.k8s.io "rt-ckv2m" is invalid: rules[0].resources: Required value: resource rules must supply at least one resource, requeuing 
Wed, Oct 11, 2023, 1:15:43 pm: [INFO] Creating clusterRole for roleTemplate rt5 (rt-ckv2m). 
Wed, Oct 11, 2023, 1:15:43 pm: [ERROR] error syncing 'c-m-dz2fb5vb/crtb-m7mnt': handler cluster-crtb-sync: couldn't ensure roles: couldn't create clusterRole rt-ckv2m: ClusterRole.rbac.authorization.k8s.io "rt-ckv2m" is invalid: rules[0].resources: Required value: resource rules must supply at least one resource, requeuing 
Wed, Oct 11, 2023, 1:15:43 pm: [INFO] Creating clusterRole for roleTemplate rt5 (rt-ckv2m). 
Wed, Oct 11, 2023, 1:15:43 pm: [ERROR] error syncing 'c-m-dz2fb5vb/crtb-m7mnt': handler cluster-crtb-sync: couldn't ensure roles: couldn't create clusterRole rt-ckv2m: ClusterRole.rbac.authorization.k8s.io "rt-ckv2m" is invalid: rules[0].resources: Required value: resource rules must supply at least one resource, requeuing 
Wed, Oct 11, 2023, 1:15:43 pm: [INFO] Creating clusterRole for roleTemplate rt5 (rt-ckv2m).
```
- Rancher log has this when a **global** role is created with only "Verb" updated: 
```
2023/10/11 18:22:04 [INFO] [mgmt-auth-gr-controller] Creating clusterRole cattle-globalrole-gr-mw7g7 for corresponding GlobalRole
2023/10/11 18:22:04 [ERROR] error syncing 'gr-mw7g7': handler mgmt-auth-gr-controller: 1 error occurred:
2023-10-11T18:22:04.390910354Z 	* ClusterRole.rbac.authorization.k8s.io "cattle-globalrole-gr-mw7g7" is invalid: rules[0].resources: Required value: resource rules must supply at least one resource

2023-10-11T18:22:04.390922664Z , requeuing
```
- Rancher log has this when the user with the **project** role was added to the downstream cluster's project: 
```
2023/10/11 18:33:13 [ERROR] error syncing 'p-s29sv/prtb-sc2s9': handler cluster-prtb-sync: couldn't ensure roles: couldn't create clusterRole rt-hgdc9: ClusterRole.rbac.authorization.k8s.io "rt-hgdc9" is invalid: rules[0].resources: Required value: resource rules must supply at least one resource, requeuing
2023/10/11 18:33:16 [INFO] Creating clusterRole for roleTemplate p1 (rt-hgdc9).
2023/10/11 18:33:16 [ERROR] error syncing 'p-s29sv/prtb-sc2s9': handler cluster-prtb-sync: couldn't ensure roles: couldn't create clusterRole rt-hgdc9: ClusterRole.rbac.authorization.k8s.io "rt-hgdc9" is invalid: rules[0].resources: Required value: resource rules must supply at least one resource, requeuing
```
Also, I noticed another issue, where the UI allows users to create a cluster/global/project role even without filling in any of the fields (Verb/Resource/API Groups/Non-Resource URLs). However, if you initially add a "Verb" and then remove it, the UI displays an error message stating, "You must specify at least one verb for each resource grant," preventing the role creation.

**Comment by Priyashetty17** [comment]
Validated with `Rancher: v2.8-6cd32b985f0b39ef2eed363458f86a352c67a42b-head` and `Dashboard: master 39adb0880` for Cluster Role, Project Role and Global Role

| Verb  | Resource           | API Groups           | Non-Resource URLs | Expected Result                                                                                                           | 2.8-head Actual Result                                                                                                    |
|-------|--------------------|----------------------|-------------------|---------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------|
| Get     |                    |                      |                      | Verify following error is displayed in the UI: "You must specify at least one Resource, Non-Resource URL, or API Group for each resource grant". Also, verify that the Create button is disabled | 🟢 Pass |
