### ISSUE TITLE
[Monitoring V2 UI] Basic Configuration

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#908]
Annotation: `catalog.rancher.io/ui-component: monitoring`

### General

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Cluster Type | N/A | N/A | `RKE`, `K3s`, `KubeADM`, `Managed Cluster (EKS, GKE, AKS, etc.)`, or `Other` | N/A
Create Default Monitoring Cluster Roles | TBD | N/A | `boolean` | `true`
Aggregate to Default Kubernetes Roles | TBD | Adds permissions provided by default ClusterRoles to default k8s ClusterRoles | `boolean` | `true`

If Cluster Type is `RKE`, `rkeControllerManager.enabled`, `rkeScheduler.enabled`, `rkeProxy.enabled`, and `rkeEtcd.enabled` should all be `true` by default. This does not need to be shown to the user, but may be visible in Advanced Options.

If Cluster Type is `k3s`, `k3sControllerManager.enabled`, `k3sScheduler.enabled`, and `k3sProxy.enabled` should all be `true` by default. This does not need to be shown to the user, but may be visible in Advanced Options.

If Cluster Type is `KubeADM`, `kubeAdmControllerManager.enabled`, `kubeAdmScheduler.enabled`, `kubeAdmProxy.enabled`, and `kubeAdmEtcd.enabled` should all be `true` by default. This does not need to be shown to the user, but may be visible in Advanced Options.

If Cluster Type is `Managed Cluster (EKS, GKE, AKS, etc.)`, `kubeControllerManager.enabled`, `kubeScheduler.enabled`, `kubeEtcd.enabled` should all be `false` by default and disabled. `prometheusOperator.hostNetwork` should be `true`.

If Cluster Type is `Other`, `kubeControllerManager.enabled`, `kubeScheduler.enabled`, `kubeProxy.enabled`, and `kubeEtcd.enabled` should all be `true` by default. This does not need to be shown to the user, but may be visible in Advanced Options.

**Note:** If the monitoring app is allowed to be deployed in any other namespace than `monitoring-system`, `prometheus-adapter.url` should be updated to `http://rancher-monitoring-prometheus.<namespace>.svc`. Ideally this should not be configurable by the user.

### Prometheus
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Scrape Interval | `prometheus.prometheusSpec.scrapeInterval` | Sets the default interval between consecutive scrapes | `string` | `1m`
Evaluation Interval | `prometheus.prometheusSpec.evaluationInterval` | Sets the default interval between consecutive evaluations | `string` | `1m`
Retention | `prometheus.prometheusSpec.retention` | Time duration Prometheus shall retain data for | `string` | `10d`
Retention Size | `prometheus.prometheusSpec.retentionSize` | Used Storage Prometheus shall retain data for | `string` | `50Gib`
Enable Admin API | `prometheus.prometheusSpec.enableAdminAPI` | Enables the Prometheus administrative HTTP API which includes functionality such as deleting time series | `boolean` | `false`

#### Persistent Storage
There should be a radio button that says `Persistent Storage for Prometheus` (`Enabled` or `Disabled`, where the default is `Disabled`) that exposes the following fields. All of the following are contained within `prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec`.
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Access Modes | `.accessModes` | N/A | `ReadWriteOnce`, `ReadOnlyMany`, `ReadWriteMany` | `null`
Storage Class | `.storageClassName` | N/A | `storageclass` | `null`
Volume Mode | `.volumeMode` | N/A | `Filesystem`,`Block` | `null`
Volume Name | `.volumeName` | N/A | `string` | `null`
Size | `.resources.requests.storage` | N/A | `string` | `50Gi`
Selector | `.selector` | Configures which volumes to consider for binding based on the labels attached to them | Ability to supply `LabelSelector` | `null`

#### Resource Limits

There should be a radio button that says `Resource Limits for Prometheus` (`Enabled` or `Disabled`, where the default is `Disabled`) that exposes the following fields.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Memory Limit | `prometheus.prometheusSpec.resources.limits.memory` | Maximum amount of memory that the Prometheus pod is allowed to use on a node | `string` | `1000Mi`
CPU Limit | `prometheus.prometheusSpec.resources.limits.cpu` | Maximum amount of CPU that the Prometheus pod is allowed to use on a node | `string` | `1000m`
Request For Memory | `prometheus.prometheusSpec.resources.requests.memory` | Minimum amount of memory that should be allocated to a Prometheus pod from a node | `string` | `750Mi`
Request For CPU | `prometheus.prometheusSpec.resources.requests.cpu` | Minimum amount of CPU that should be allocated to a Prometheus pod from a node | `string` | `750m`

#### Persistent Storage
There should be a radio button that says `Persistent Storage for Grafana` (`Enable With Existing PVC`, `Enable with PVC Template`, `Enable with StatefulSet Template`, or `Disabled`, where `Disabled is default) that exposes the following fields. 

##### If `Enable With Existing PVC` is selected:

All of the following are contained within `grafana.persistence`.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Use Existing PVC | `.existingClaim` | Existing PVC to persist data in | pvc | `null`
Use Subpath | `.subPath` | Mount a subpath of the persistent volume | string | `null`

##### If `Enable With StatefulSet Template` is selected:

All of the following are contained within `grafana.persistence`. Set `grafana.persistence.type` to `statefulset`.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Access Modes | `.accessModes` | N/A | `ReadWriteOnce`, `ReadOnlyMany`, `ReadWriteMany` | `null`
Storage Class | `.storageClassName` | N/A | `storageclass` | `null`
Size | `.size` | N/A | `string` | `null`
Use Subpath | `.subPath` | Mount a subpath of the persistent volume | `string` | `null`

##### If `Enable With PVC Template` is selected

All of the following are contained within `grafana.persistence`. Set `grafana.persistence.type` to `pvc`.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Access Modes | `.accessModes` | N/A | `ReadWriteOnce`, `ReadOnlyMany`, `ReadWriteMany` | `null`
Storage Class | `.storageClassName` | N/A | `storageclass` | `null`
Size | `.size` | N/A | `string` | `null`
Use Subpath | `.subPath` | Mount a subpath of the persistent volume | `string` | `null`
PVC Annotations | `.annotations` | N/A | Ability to supply annotations | `null`
PVC Finalizers | `.finalizers` | N/A | Ability to supply finalizers | `null`

**Comment by jiaqiluo** [comment]
on `master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head`

---

Issue 1:

the following options are missing in the current UI:

under General
- Create Default Monitoring Cluster Roles
- Aggregate to Default Kubernetes Roles

under Grafana - Enable With PVC Template
- PVC Annotations
- PVC Finalizers

---

issue 2:

The default value for the field  `Retention Size` should be **50GiB**, it is 50Gib now and it does not work

<img width="987" alt="Screen Shot 2020-08-12 at 10 59 09 AM" src="https://user-images.githubusercontent.com/6218999/90053951-02e22d80-dc90-11ea-9ef2-bb0eb5b03a73.png">G

**Comment by jiaqiluo** [comment]
Validated on `master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head` 


Issue 1 is addressed, those missing options are now available in the UI

> on `master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head`
> 
> Issue 1:
> 
> the following options are missing in the current UI:
> 
> under General
> 
> * Create Default Monitoring Cluster Roles
> * Aggregate to Default Kubernetes Roles
> 
> under Grafana - Enable With PVC Template
> 
> * PVC Annotations
> * PVC Finalizers
>

**Comment by jiaqiluo** [comment]
> issue 2:
> 
> The default value for the field `Retention Size` should be **50GiB**, it is 50Gib now and it does not work
> 
> <img alt="Screen Shot 2020-08-12 at 10 59 09 AM" width="987" src="https://user-images.githubusercontent.com/6218999/90053951-02e22d80-dc90-11ea-9ef2-bb0eb5b03a73.png">



issue 2 still existson `master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head`

 
need to change '50Gib' to '50GiB' 

https://github.com/rancher/dashboard/blob/8ede12d7a9b08dbf172af6ef680718a8e60277ea/chart/monitoring/index.vue#L68

**Comment by aiyengar2** [comment]
> If Cluster Type is Other, kubeControllerManager.enabled, kubeScheduler.enabled, kubeProxy.enabled, and kubeEtcd.enabled should all be true by default. This does not need to be shown to the user, but may be visible in Advanced Options.

Based on discussion with @deniseschannon and @cbron offline, we want to modify these requirements to set all these values to false by default (i.e. use the original values on the Chart's `values.yaml`) when the Cluster Type is Other. This prevents empty Grafana Dashboards and unused PrometheusRules from being created.

If a user wants to deploy these components, they can always modify the behavior on the Advanced Configuration since these fields will be exposed there.
