### ISSUE TITLE
[Monitoring V2 UI] Advanced Configuration

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#909]
Followup to https://github.com/rancher/dashboard/issues/908 for exposing additional fields for advanced configuration.

Annotation: `catalog.rancher.io/ui-component: monitoring`

### Components
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Deploy Prometheus Operator | `prometheusOperator.enabled` | N/A | `boolean` | `true`
Deploy Grafana | `grafana.enabled` | N/A | `boolean` | `true`
Deploy Prometheus Adapter | `prometheus-adapter.enabled` | N/A | `boolean` | `true`

If any of these are disabled, the corresponding fields in the Basic Configuration or any fields below that are related to it should disappear from the UI and none of the values that are set on those sub-fields should be passed down to the deployment.

### Default CRs
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Create Default Prometheus CR | `prometheus.enabled` | N/A | `boolean` | `true`
Create Default Alertmanager CR | `alertmanager.enabled` | N/A | `boolean` | `true`
Create Default PrometheusRule CRs | `defaultRules.create` | N/A | `boolean` | `true`
Create Default Grafana Dashboards | `grafana.defaultDashboardsEnabled` | N/A | `boolean` | `true`

### Exporters

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Export Node Exporter Metrics | `nodeExporter.enabled` | N/A | `boolean` | `true`
Export Kube State Metrics | `kubeStateMetrics.enabled` | N/A | `boolean` | `true`
Export Kubelet Metrics | `kubelet.enabled` | N/A | `boolean` | `true`
Export CoreDNS Metrics | `coreDns.enabled` | N/A | `boolean` | `true`
Export KubeDNS Metrics | `kubeDns.enabled` | N/A | `boolean` | `false`

The k8 YAML for kube-controller-manager, kube-scheduler, etcd, and kube-proxy will be dependent on the value for the `Cluster Type` set in the Basic Configuration. By default, if the Cluster Type is changed, the settings here should transfer to the corresponding value in the new Cluster Type.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Export Kube Scheduler Metrics | `<rke\|kubeAdm\|kube>Scheduler.enabled` | N/A | `boolean` | `true` (disabled for Managed Cluster)
Export Kube Controller Manager Metrics | `<rke\|kubeAdm\|kube>ControllerManager.enabled` | N/A | `boolean` | `true` (disabled for Managed Cluster)
Export Kube Proxy Metrics | `<rke\|kubeAdm\|kube>Proxy.enabled` | N/A | `boolean` | `true`
Export Etcd Metrics | `<rke\|kubeAdm\|kube>Etcd.enabled` | N/A | `boolean` | `true` (disabled for Managed Cluster + k3s)

For k3s only, a single option should be available that says "Export Kubernetes Component Metrics" tied to `k3sServer.enabled` and enabled `true` by default.

#### Limit Namespaces

There should be a radio button that says `Limit Namespace For Prometheus CRs` (`Use All Namespaces` `Accept List` or `Deny List`, where the default is `Use All Namespaces`) that exposes the following fields.

##### If `Accept List` is selected:
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Namespaces to Accept | `prometheusOperator.namespaces.additionalNamespaces` | N/A | List of namespaces | [`monitoring-system`]

Before submitting, UI should parse the namespaces provided to see if the deployment namespaces (`monitoring-system`) still exists in the list of Namespaces to Accept. If so, it should be removed from the list and `prometheusOperator.namespaces.releaseNamespace: true` should be set instead. Alternatively, we could expose a field for `prometheusOperator.namespaces.releaseNamespace` which automatically shows or omits the deployment namespace from the list of namespaces based on whether it is selected.

##### If `Deny List` is selected:
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Namespaces to Deny | `prometheusOperator.denyNamespaces` | N/A | List of namespaces | Empty

#### Resource Limits

There should be a radio button that says `Resource Limits for Prometheus Operator` (`Enabled` or `Disabled`, where the default is `Disabled`) that exposes the following fields.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Memory Limit | `prometheusOperator.resources.limits.memory` | Maximum amount of memory that the pod is allowed to use | `string` | `500Mi`
CPU Limit | `prometheusOperator.resources.limits.cpu` | Maximum amount of CPU that the pod is allowed to use | `string` | `200m`
Request For Memory | `prometheusOperator.resources.requests.memory` | Minimum amount of memory that should be allocated to the pod | `string` | `100Mi`
Request For CPU | `prometheusOperator.resources.requests.cpu` | Minimum amount of CPU that should be allocated to the pod | `string` | `100m`

#### Scheduling Constraints

There should be a radio button that says `Scheduling Constraints for Prometheus Operator` (`Enabled` or `Disabled`, where the default is `Disabled`) that exposes the following fields.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Node Selector | `prometheusOperator.nodeSelector` | N/A | Ability to supply `NodeSelectors` | `null`
Tolerations | `prometheusOperator.tolerations` | N/A | Ability to supply `Tolerations` | `null`
Affinity Rules | `prometheusOperator.affinity` | N/A | Ability to supply `Affinity Rules` | `null`

#### Network

There should be a radio button that says `Expose Prometheus on Network` (`ClusterIP`, `NodePort`, or `Ingress`, where the default is `ClusterIP`) that exposes the following fields.

##### If `ClusterIP` is selected:
Set `prometheus.service.type` to `ClusterIP`. Don't show anything else.

##### If `NodePort` is selected:
Set `prometheus.service.type` to `NodePort` and show:
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Node Port | `prometheus.service.nodePort` | Port to expose Prometheus Service on each node | `int` | `30090`

##### If `Ingress` is selected:
Set `prometheus.service.type` to `ClusterIP`. Set `prometheus.ingress.enabled` to `true`.
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
External URL | `prometheus.prometheusSpec.externalUrl` | The external URL the Prometheus instances will be available under | `string` | `""`
Hostnames | `prometheus.ingress.hosts` | N/A | Ability to supply list of strings | Empty
Paths | `prometheus.ingress.paths` | N/A | Ability to supply list of strings | Empty
Annotations | `prometheus.ingress.annotations` | N/A | Ability to supply annotations | Empty
Labels | `prometheus.ingress.labels` | N/A | Ability to supply labels | Empty
TLS Hostnames | `prometheus.ingress.tls.hosts` | List of hosts included in the TLS certificate. Defaults to wildcard host setting | Ability to supply a list of strings | Empty
TLS Secret | `prometheus.ingress.tls.secretName` | Must contains keys for tls.crt and tls.key | `secret` | `null`

#### Scheduling Constraints

There should be a radio button that says `Scheduling Constraints for Prometheus` (`Enabled` or `Disabled`, where the default is `Disabled`) that exposes the following fields.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Node Selector | `prometheus.prometheusSpec.nodeSelector` | N/A | Ability to supply `NodeSelectors` | `null`
Tolerations | `prometheus.prometheusSpec.tolerations` | N/A | Ability to supply `Tolerations` | `null`
Affinity Rules | `prometheus.prometheusSpec.affinity` | N/A| Ability to supply `Affinity Rules` | `null`

#### Configuration

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Configuration | `grafana.grafana.ini` | See [Grafana's docs](http://docs.grafana.org/installation/configuration/) for configuration options | INI file | Whatever is provided in the chart default

Note: the key name itself is `grafana.ini`, so this would be supplied as:
```yaml
grafana:
  grafana.ini:
    <user-content>
```

#### Admin Credentials

There should be a radio button that says `Configure Admin Credentials for Grafana` (`Use Chart Default`, `Provide Password`, and `Provide Secret`, where the default is `Use Chart Default`) that exposes the following fields:

##### If `Provide Password` is selected:
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Admin Password | `grafana.adminPassword` | N/A | `password` | `""`

##### If `Provide Secret` is selected:
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Admin Credentials Secret | `grafana.admin.existingSecret` | A secret that contains the a username and password to be used for admin credentials to Grafana | `secret` | `null`
Key for Username | `grafana.admin.userKey` | The key within the Secret that contains the username | `string` | `""`
Key for Password | `grafana.admin.passwordKey` | The key within the Secret that contains the password | `string` | `""`

#### Network

There should be a radio button that says `Expose Grafana on Network` (`ClusterIP`, `NodePort`, or `Ingress`, where the default is `ClusterIP`) that exposes the following fields.

##### If `ClusterIP` is selected:
Set `grafana.service.type` to `ClusterIP`. Don't show anything else.

##### If `NodePort` is selected:
Set `grafana.service.type` to `NodePort` and show:
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Node Port | `grafana.service.nodePort` | Port to expose Grafana Service on each node | `int` | `30950`

##### If `Ingress` is selected:
Set `grafana.service.type` to `ClusterIP`. Set `grafana.ingress.enabled` to `true`.
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Hostnames | `grafana.ingress.hosts` | N/A | Ability to supply list of strings | Empty
Paths | `grafana.ingress.paths` | N/A | Ability to supply list of strings | Empty
Annotations | `grafana.ingress.annotations` | N/A | Ability to supply annotations | Empty
Labels | `grafana.ingress.labels` | N/A | Ability to supply labels | Empty
TLS Hostnames | `grafana.ingress.tls.hosts` | List of hosts included in the TLS certificate. Defaults to wildcard host setting | Ability to supply a list of strings | Empty
TLS Secret | `grafana.ingress.tls.secretName` | Must contains keys for tls.crt and tls.key | `secret` | `null`

#### Resource Limits

There should be a radio button that says `Resource Limits for Grafana` (`Enabled` or `Disabled`, where the default is `Disabled`) that exposes the following fields.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Memory Limit | `grafana.resources.limits.memory` | Maximum amount of memory that the pod is allowed to use | `string` | `200Mi`
CPU Limit | `grafana.resources.limits.cpu` | Maximum amount of CPU that the pod is allowed to use | `string` | `200m`
Request For Memory | `grafana.resources.requests.memory` | Minimum amount of memory that should be allocated to the pod | `string` | `100Mi`
Request For CPU | `grafana.resources.requests.cpu` | Minimum amount of CPU that should be allocated to the pod | `string` | `100m`

#### Network

There should be a radio button that says `Expose Alertmanager on Network` (`ClusterIP`, `NodePort`, or `Ingress`, where the default is `ClusterIP`) that exposes the following fields.

##### If `ClusterIP` is selected:
Set `alertmanager.service.type` to `ClusterIP`. Don't show anything else.

##### If `NodePort` is selected:
Set `alertmanager.service.type` to `NodePort` and show:
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Node Port | `alertmanager.service.nodePort` | Port to expose Alertmanager Service on each node | `int` | `30903`

##### If `Ingress` is selected:
Set `alertmanager.service.type` to `ClusterIP`. Set `alertmanager.ingress.enabled` to `true`.
Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
External URL | `alertmanager.alertmanagerSpec.externalUrl` | The external URL the Alertmanager instances will be available under | `string` | `""`
Hostnames | `alertmanager.ingress.hosts` | N/A | Ability to supply list of strings | Empty
Paths | `alertmanager.ingress.paths` | N/A | Ability to supply list of strings | Empty
Annotations | `alertmanager.ingress.annotations` | N/A | Ability to supply annotations | Empty
Labels | `alertmanager.ingress.labels` | N/A | Ability to supply labels | Empty
TLS Hostnames | `alertmanager.ingress.tls.hosts` | List of hosts included in the TLS certificate. Defaults to wildcard host setting | Ability to supply a list of strings | Empty
TLS Secret | `alertmanager.ingress.tls.secretName` | Must contains keys for tls.crt and tls.key | `secret` | `null`

#### Scheduling Constraints

There should be a radio button that says `Scheduling Constraints for Alertmanager` (`Enabled` or `Disabled`, where the default is `Disabled`) that exposes the following fields.

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Node Selector | `alertmanager.alertmanagerSpec.nodeSelector` | N/A | Ability to supply `NodeSelectors` | `null`
Tolerations | `alertmanager.alertmanagerSpec.tolerations` | N/A | Ability to supply `Tolerations` | `null`
Affinity Rules | `alertmanager.alertmanagerSpec.affinity` | N/A| Ability to supply `Affinity Rules` | `null`

### Prometheus Adapter

If `Create Default Prometheus CR` is disabled, the URL should have no default value and the user should be required to fill it out on submit. Otherwise, the following should be shown:

Header / Label Name | k8s YAML | Description | Input | Default
---|---|---|---|---|
Prometheus URL | `prometheus-adapter.prometheus.url` | Points to a Prometheus service at http://<prometheus-service-name>.<deployment-namespace>.svc | `string` | `http://rancher-monitoring-prometheus.monitoring-system.svc`
Prometheus Service Port | `prometheus-adapter.prometheus.port` | N/A | `9090`
ConfigMap for Existing Rules | `prometheus-adapter.rules.existing` | Specify a ConfigMap with key 'config.yaml' that has Prometheus Adapter rules for exposing custom metrics | `configmap` | `null`

If the monitoring app is allowed to be deployed in any other namespace than `monitoring-system`, the Prometheus URL should be updated to `http://rancher-monitoring-prometheus.<namespace>.svc`. Ideally this should not be configurable by the user.

**Comment by Tejeev** [comment]
This is lacking fields for Alertmanager.  Though it may be separate it is exposed in the same place as monitoring (rightly so, I think) and visible when editing as yaml so should have fields exposed in the UI such as `selectors` and `tolerations`

**Comment by aiyengar2** [comment]
@Tejeev updated

**Comment by aiyengar2** [comment]
Should also take care of adding in additional exporters mentioned in https://github.com/rancher/dashboard/issues/3095.
