### ISSUE TITLE
Github: when ticket with QA/None or dev-automation tickets are closed, move to new column in Zube (QA Review)

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9093]
To help with keeping QA's To Test column clean, if we work on tickets to help QA, when we close tickets with these labels, we can automatically move them to a new Zube column for automation testers to verify them and then move to Done:
- QA/None
- QA/dev-automation

**Comment by gaktive** [comment]
Need to hash out with @nwmac how the Zube workflow looks first, then we can match Github Actions accordingly.

**Comment by nwmac** [comment]
This has been done
