### ISSUE TITLE
1.26 UI plugin - example UI plugin charts kube version is incompatible with 1.26

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/dashboard#9094]
edit: see comment. charts' k8s' need to be increased 

**Setup**
testing done on local
- Rancher version: 2.7.5-rc4
- Rancher UI Extensions:102.0.0+up0.2.0 
- k8s- 1.26.4

**Describe the bug**

on a local cluster with 1.26.4 k8 with UI plugin repositories and operator installed, when the user clicks the 'ui extensions page, none of the UI charts that should be available are visible. 

note: this bug has been reproduced on an env upgraded from non 1.26 k8s to 1.26+, as well as on a new 2.7.5-rc4 / 1.26.4 cluster

**To Reproduce**
1. stand up a 1.26.4 k8 cluster
2. navigate to global extensions
3. install UI plugin on the local
4. navigate to apps > repositories
5. click create
6. provide a name
7. click the 'git repository' toggle
8. provide this url - https://github.com/rancher/ui-plugin-examples
9. navigate to global extensions 

**Result**
ui-plugin-examples are not displayed. 
<img width="1600" alt="image" src="https://github.com/rancher/dashboard/assets/89030218/f77725c8-0014-474a-a738-e3815e7abc16">

**Expected Result**
ui-plugin examples are displayed.
<img width="1701" alt="image" src="https://github.com/rancher/dashboard/assets/89030218/26ac7ea2-e95a-410a-9e15-0ab3c3cfbdf5">

**Screenshots**

**Comment by AndrewHoffmanQA** [comment]
this is due to the values held in the example charts I'm using. if someone could update the clock app and the homepage app found here I'll be good to go https://github.com/rancher/ui-plugin-examples

<img width="1226" alt="image" src="https://github.com/rancher/dashboard/assets/89030218/32bcf50f-594f-4fca-9520-a21882a88b97">

**Comment by AndrewHoffmanQA** [comment]
this was a result of having an out of date UI plugin operator applied, not an issue with the chart

**Comment by AndrewHoffmanQA** [comment]
re-opening for retesting. this is a valid issue and we hope to have it resolved in the next RC

**Comment by AndrewHoffmanQA** [comment]
retest failed. 
cluster information

rancher image- 2.7.5-rc5
chart version-2.7.5-rc5
upgrading from 1.25.9 to 1.26.4 k8

upon successful upgrade to 1.26 the UI plugin library does not display the charts it did previously. 

video of reproduction available but has sensitive cluster info, request from @AndrewHoffmanQA

**Comment by AndrewHoffmanQA** [comment]
closing. as suspected this was due to chart config.

**Comment by AndrewHoffmanQA** [comment]
@richard-cox, I closed it since this was a 'testing data blocker' type bug. we forked the repo and upped the kube version to unblock testing. 

this is still a valid bug if users want to utilize charts in https://github.com/rancher/ui-plugin-examples on 1.26 clusters. 

additionally I'll update the bug title to reflect the ticket

**Comment by aalves08** [comment]
Should be fixed by https://github.com/rancher/ui-plugin-charts/pull/12

**Comment by AndrewHoffmanQA** [comment]
retest passed. closing bug


Setup
testing done on local

Rancher version: 2.7.5-rc4
Rancher UI Extensions:102.0.0+up0.2.0
k8s- 1.26.4

reproduction steps taken

1. stand up a 1.26.4 k8 cluster
2. navigate to global extensions
3. install UI plugin on the local
4. navigate to apps > repositories
5. click create
6. provide a name
7. click the 'git repository' toggle
8. provide this url - https://github.com/rancher/ui-plugin-examples
9. navigate to global extensions


all extensions now are displayed in the UI again
<img width="1717" alt="image" src="https://github.com/rancher/dashboard/assets/89030218/811fc8db-ce52-42f6-8240-6dabb54c3657">
