### ISSUE TITLE
bug- Project monitoring grafana link and embedded metrics are throwing 404 errors.

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/dashboard#9099]
**Setup**
- Rancher version: 2.7.5-rc4
- monitoring 102.0.1+up40.1.2
- prom federator 2.1.0+up0.3.0 

**Describe the bug**
in project monitoring, when the user views a project monitoring page, neither the embedded grafana metrics nor the link to grafana behave as expected, and instead they respond with 404s

**To Reproduce**
scenario 1

1. install monitoring
2. install prom federator
3. navigation - side menu > monitoring > project monitoring
4. create a project monitor
5. once green and active, click on the project monitor name (user is taken to proj monitor page)
6. click the grafana link between Prometheus and alertmanager

scenario 2

1. install monitoring
2. install prom federator
3. navigation - side menu > monitoring > project monitoring
4. create a project monitor
5. once green and active, click on the project monitor name (user is taken to proj monitor page)
6. the embedded grafana is not displayed correctly- throws 404

**Result**
grafana metrics not displayed

**Expected Result**
grafana metrics displayed

**Screenshots**

**Additional context**
video 

https://github.com/rancher/dashboard/assets/89030218/662d58e0-bae6-4975-84f7-7dd341d4ceeb

**Comment by AndrewHoffmanQA** [comment]
related to https://github.com/rancher/rancher/issues/41036 and https://github.com/rancher/dashboard/issues/8885

**Comment by gaktive** [comment]
@nflynt to confirm, you have the paths in place for the UI to fix this quickly for 2.7.5? Time's tight for the release and I know there's work lined up for Q3 in the backend to try to make this better, along with understanding how UI can be looped in on Grafana upgrades that often break this.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 0bcf068`
`Local Cluster:`
1. installed monitoring 102.0.1+up40.1.2
2. installed prom federator 2.1.0+up0.3.0
3. navigation - side menu > monitoring > project monitoring
4. create a project monitor
5. once green and active, click on the project monitor name (user is taken to proj monitor page)
6. `grafana loaded from both links available on the project monitor page`

`Downstream Cluster:`
1. installed monitoring 102.0.1+up40.1.2
2. installed prom federator 2.1.0+up0.3.0
3. navigation - side menu > monitoring > project monitoring
4. create a project monitor
5. once green and active, click on the project monitor name (user is taken to proj monitor page)
6. `grafana loaded from both links available on the project monitor page`

Screenshots with pages loaded from grafana links:
![2023-06-22_14-01-30.png](https://zube.io/files/rancher/e9d5037493d56b04f07ff5cd5a90dd1b-2023-06-22_14-01-30.png)
![2023-06-22_14-01-41.png](https://zube.io/files/rancher/bb8d04cdf6a009d379fac4a0352ab643-2023-06-22_14-01-41.png)
![2023-06-22_14-01-52.png](https://zube.io/files/rancher/5b9ffdc6db401423484f42c916f3373d-2023-06-22_14-01-52.png)
![2023-06-22_14-02-05.png](https://zube.io/files/rancher/91b880b20d586dbd3ba528894f04f30f-2023-06-22_14-02-05.png)
