### ISSUE TITLE
Ability to deploy AWS external tree provider in RKE2

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9110]
Internal Ref: SURE-4760

The external AWS cloud provider (CCM) deploys onto a cluster and relies on the hostname and/or --provider-id flag (kubelet) to describe the node and initialise into the cluster.

With v2-provisioning, the hostname is always set to a node pool naming convention (OS (see userdata example below) & with -hostname-override), and there appears to be no way of providing the values dynamically to the -provider-id flag.

**Comment by gaktive** [comment]
Need guidance from PM and @Sahota1225 about what UI requirements are here.

This should be done in tandem with #9204

**Comment by gaktive** [comment]
Need to sync with backend to ensure we're on the same page here.

No E2E since this is AWS so this will be manually tested.

**Comment by slickwarren** [comment]
tested on v2.8-head (6376016)
currently, there is no notification to the user on rke2 that there is a requirement for additional settings when using aws cloud provider option. Can we add a banner or something similar that links to the rancher documentation for using out-of-tree when 1.27.x + k8s versions are selected? This way, it is clear to the user what should be done as they are used to it 'just working' when selecting the aws cloud provider. 

This should apply in both creating rke2 clusters as well as upgrading them (if 1.27+ is selected)

x-linking the documentation PR if that is helpful for creating the banner/alert message: https://github.com/rancher/rancher-docs/pull/844

**Comment by slickwarren** [comment]
there is now a notification displayed as of v2.8-head (a6b908d), and is working as intended when selecting the `amazon` option on both fresh 1.27 installs and upgrades to 1.27: 
![image](https://github.com/rancher/dashboard/assets/16691014/aea92bad-7dfe-4c9a-838a-eec657b0bf3e)
