### ISSUE TITLE
Handle extensions that are already installed and shouldn't run in a particular kube version

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#9113]
**Is your feature request related to a problem? Please describe.**
Extensions that are already installed and shouldn't run in a particular kube version are not being checked/validated at the moment as the extension is already cached in the `uiPlugin` CRD instance. It's also missing annotations such as `catalog.cattle.io/kube-version` that should be propagated from the extension `chart.yaml`

**Describe the solution you'd like**
- Add mechanism to copy the extension `chart.yaml` annotations to the `uiPlugin` instance
- Handle the kube version incompatibility in the UI to prevent usage and provide feedback to the user

**Comment by richard-cox** [comment]
Slightly related - https://github.com/rancher/dashboard/issues/9094, where the version needs bumping

**Comment by aalves08** [comment]
True @richard-cox . We need to make a decision if we are to remove the `kube-version` annotation from all the repos or just bump the defaults on `ui-plugin-server` to a version number that doesn't cause us trouble in the near future (ex: v1.6) 😛

**Comment by kwwii** [comment]
We should also warn users when upgrading kubernetes that it will break extensions - https://github.com/rancher/dashboard/issues/9132

**Comment by richard-cox** [comment]
adding MS to match PR
