### ISSUE TITLE
rke2 cluster creation through rancher ui fails

### ISSUE THREAD

**Issue by Phaneeshv** [rancher/dashboard#9119]
rke cluster is succesful through ui but rke2 cluster cluster creation fails with below error

**Comment by Phaneeshv** [comment]
error message
[Waiting] configuring bootstrap node(s) custom-18ca8d596ea7: error applying plan -- check rancher-system-agent.service logs on node for more information, waiting for agent to check in and apply initial plan

**Comment by richard-cox** [comment]
As mentioned in https://github.com/rancher/dashboard/issues/9109#issuecomment-1590648262 this is not a question. Further advise was given there on how to find support to resolve your issue.
