### ISSUE TITLE
Localization plugin not working at the login page

### ISSUE THREAD

**Issue by cogor** [rancher/dashboard#9124]
**Setup**
- Rancher version: 2.7.0
- Rancher UI Extensions: my extension with localization
- Browser type & version: Firefox 114.0.1 

**Describe the bug**
I have created a localization extension following the instructions(and repo with examples), but on the login page, I am unable to select the desired language, even though it is available in the account settings. So, whenever I log out, the translation defaults back to English.

**To Reproduce**
Create new extension like https://github.com/rancher/ui-plugin-examples/tree/main/pkg/uk-locale
Login to dashboard
Install new extension
Change language to new language from plugin
Logout 

**Result**
Translation doesn't work and you can't select it

**Expected Result**
You can select new language on log in page and after logout it will be saved

**Comment by aalves08** [comment]
For future reference, this has possible security implications that have to be taken into consideration when tackling this issue

**Comment by richard-cox** [comment]
Blocked on SURE-6315

**Comment by richard-cox** [comment]
This will be resolved via https://github.com/rancher/dashboard/issues/9814
