### ISSUE TITLE
Warn users when upgrading a kubernetes version will break an installed extension

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#9132]
1) When an extension does not run on a given Kubernetes version the UI should warn the user when upgrading to that Kubernetes version.

2) this is also to look into extensions installed, so that when we update the k8s version, we shouldn't load the extension(s) if they are incompatible with the current k8s version

**Update 28-09-2023**

_Blocked by backend:_
https://github.com/rancher/rancher/issues/42982

_Backend enhancement needed for `ui-plugin-operator`:_
https://github.com/rancher/rancher/issues/42983

**Comment by aalves08** [comment]
This is to look into extensions installed, we update the k8s version, then check if extension is still loaded

**Comment by aalves08** [comment]
**UPDATE:** `local` cluster edition belongs to ember world, which only uses Norman, therefore we don't have access to the list of extensions installed on ember. With this, we cannot display a banner (item **1)**) before updating the kube version on `local` cluster edit. Only **2)** is doable.

**Comment by aalves08** [comment]
**UPDATE:** point **2)** isn't also doable at this point because the meta information at load time for a plugin doesn't include any annotations, therefore we cannot prevent the loading of an extension.

**Comment by aalves08** [comment]
After chatting with @richard-cox , we decided to move this out to `v2.8-next1` as it's not considered a priority and is backend blocked.

Will create backend issues for this and update the description accordingly.

FYI @gaktive

**Comment by aalves08** [comment]
description updated. Backend blocked issue. @richard-cox @jordojordo @codyrancher

**Comment by gaktive** [comment]
For internal coordination, SURE-8095 is our reference.

**Comment by gaktive** [comment]
It's possible that this is resolved via other means now. Will look more in-depth for 2.11.0 before closing but we have a mechanism to detect k8s versions post-install now.

**Comment by aalves08** [comment]
I think we can close this one in light of the effort to improve the extensions gating with https://github.com/rancher/dashboard/pull/12071 + the fact that we now have a proper kube version check
