### ISSUE TITLE
Continuous Delivery dashboard shows 0/0 Bundles Ready

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9137]
Internal Ref: SURE-6398

Add a Git repo that has a `fleet.yaml` file with a `name` set - this causes the bundle(s) generated to use that name.

The logic we use to link GitRepos to Bundles in that case - we assume the name of the GitRepo is the prefix of the Bundle name.

We should be using the fleet.cattle.io/repo-name label of the Bundle to get the name of the associated GitRepo

![image-2023-05-24-16-19-49-681.png](https://zube.io/files/rancher/3a7dd77d0f216eb851bd350d4c31e405-image-2023-05-24-16-19-49-681.png)

Troubleshooting steps:
running `kubectl get bundles -n fleet-default fleet-name-here -o=jsonpath={.status}` to get the bundle status shows:

 ```
{"conditions":
[
{"lastUpdateTime":"2023-05-24T23:17:58Z","status":"True","type":"Ready"},
{"lastUpdateTime":"2023-05-24T23:17:59Z","status":"True","type":"Processed"}
],
"display":{"readyClusters":"1/1"},
"maxNew":50,
"maxUnavailable":1,
"maxUnavailablePartitions":0,
"observedGeneration":1,
"partitions":
[
{"count":1,"maxUnavailable":1,"name":"All","summary":{"desiredReady":1,"ready":1}}
],
"resourceKey":
[
{"apiVersion":"apps/v1","kind":"Deployment","name":"frontend","namespace":"fleet-name-here-ns"},
{"apiVersion":"apps/v1","kind":"Deployment","name":"redis-master","namespace":"fleet-name-here-ns"},
{"apiVersion":"apps/v1","kind":"Deployment","name":"redis-slave","namespace":"fleet-name-here-ns"},
{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","name":"fleet-name-here-crb"},
{"apiVersion":"v1","kind":"Service","name":"frontend","namespace":"fleet-name-here-ns"},
{"apiVersion":"v1","kind":"Service","name":"redis-master","namespace":"fleet-name-here-ns"},
{"apiVersion":"v1","kind":"Service","name":"redis-slave","namespace":"fleet-name-here-ns"}
],
"summary":{"desiredReady":1,"ready":1},
"unavailable":0,
"unavailablePartitions":0}>
```

Format that JSON, and it shows:

```
   "summary":{
      "desiredReady":1,
      "ready":1
   }, 
```

So why does the UI say 0/0 ready?

**Comment by cnotv** [comment]
![Screenshot 2023-06-28 at 17 37 11](https://github.com/rancher/dashboard/assets/5009481/850cf3fd-d4e8-464c-9d8c-0cb72811ce17)

**Comment by gaktive** [comment]
@Shavindra was automation written to test this? I didn't see any tests in the PR.

**Comment by gaktive** [comment]
If tests are needed, we can do this in a separate ticket or then take the dev-automation label off if QA has capacity.

**Comment by nwmac** [comment]
@Shavindra I don't think this needs a downstream cluster? It should be possible with the local cluster

**Comment by gaktive** [comment]
Putting back this issue back to test since the PR opened was for an E2E. 

@Shavindra if this takes time, can you create a new issue to track that?

**Comment by sbulage** [comment]
Able to see correct bundle count on UI.

![Selection_081](https://github.com/rancher/dashboard/assets/12134754/060bed9b-373e-40a1-bb2e-4186e393950e)
