### ISSUE TITLE
Unable to use Auth Providers when running locally

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9138]
**Setup**
- Rancher version: v2.7.5 dev
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
It looks like configuring an Auth Provider, like Github, does not work when serving the dashboard locally (due to the server middleware which redirects /verify-auth to /auth/verify not being wired in). I had to add the following to routes in shell/config/router.js

```
{
    path:     '/verify-auth',
    redirect: (to) => {
      return 'auth/verify';
    },
  }
```

**To Reproduce**
- setup github auth provider

**Result**
redirect after accepting in github redirects to a 404 page

**Expected Result**
redirect succesfuly closes window and auth provider detail page shown

**Comment by richard-cox** [comment]
We should get this working, bugs are creeping in because people are developing / testing AP group use cases (basically anything to do with permissions, roles, etc)

**Comment by cnotv** [comment]
How can you get redirected locally from GH? You need to specify an IP address to be redirected, so or you set local IP or the hosted one.

**Comment by richard-cox** [comment]
The redirect is done locally, so `localhost` previously worked fine.

For whoever picks this up, the routing above was previously done only in dev world when serving locally. We'd need to do similar here. In production the redirect is handled via Rancher.

**Comment by gaktive** [comment]
A unit test would help here but this bug isn't production facing.

**Comment by gaktive** [comment]
This routing logic may have been tied to Nuxt before it was removed. Maybe we can do something in the Vue config.

**Comment by sowmyav27** [comment]
QA will validate if this continues to work on Rancher prod environment

**Comment by ronhorton** [comment]
**Pass**
verified github workflow and authentication with rancher `v2.7-head 027246f `

1. clicked hamburger > users & authentication > auth providers
2. selected github oAuth tile
3. completed required fields in github and rancher
4. enabled github auth
5. logged out 
6. logging in with github
