### ISSUE TITLE
Missing scroll login/setup page

### ISSUE THREAD

**Issue by scures** [rancher/dashboard#9153]
As reported, there's a missing scroll functionality for the login/setup page.

![image](https://github.com/rancher/dashboard/assets/88777903/1273cd9d-5e65-41dd-8205-44164b951137)

**Comment by richard-cox** [comment]
I've reproduced this in both 2.6.11 and 2.7.4. Setting milestone to 2.7q3

**Comment by Priyashetty17** [comment]
Validated ✅  


Component | Version
-- | --
Rancher | v2.7-d3b5469238e965e54306f74d0e98a47b780cbe80-head
Dashboard | master 7896059c4
