### ISSUE TITLE
Restricted admins/cluster owners cannot add or delete users from Project membership page

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#9159]
Rancher version: 2.7-head 0bcf068
Browser type & version: Chrome

Describe the bug
As a cluster owner/restricted admin, logging into rancher and navigating to the cluster membership page, unable to add or delete users from project membership page. We can add/delete users by editing the project and editing the config.

To Reproduce

- Enable azure AD Auth 
- Add a user as a cluster owner in the downstream cluster or add a group from the auth as restriced admin
- Login as the cluster owner
- Navigate to cluster and Project members page >> Project membership page

Result
Unable to add or delete users as cluster owners/restricted admins.

Expected Result
As a restricted admin, cluster owners we should be able to delete or add the members form the project membership page.

Additional Info:

- This happens with local users as well. 
- As a local user if we add/delete another user from a project the delete/ add option appears 
- Reproduced while validating https://github.com/rancher/dashboard/issues/9049

Screenshot:
<img width="400" alt="2023-06-20_09-01-33" src="https://github.com/rancher/dashboard/assets/38144301/04c9ce62-fe95-48c0-a29f-c4495c0ab9dd">

In this screenshot linked, the user is a restricted admin from an auth provider.

**Comment by richard-cox** [comment]
`Add a user as a cluster owner in the downstream cluster`
It isn't expected that the add / remove buttons aren't visible when the facilitating role is user based. Could you confirm that the specific user is the cluster owner, rather than a group the user is in?

`add a group from the auth as restriced admin`
It's expected that the add / remove buttons aren't visible when the facilitating role is group based. @Sean-McQ is creating an issue to cover this.

**Comment by richard-cox** [comment]
I've tried to reproduce the specific user case
- As a local user who is a cluster owner of the downstream cluster
- As a AD user (github) who is a cluster own of the downstream cluster

In both scenarios the `Add` and individual project's `x` buttons are visible

**Comment by richard-cox** [comment]
After some discussion we've discovered for

- An AD User who is a cluster owner of a downstream cluster
- Accessing the Project Members list via FF

Will sometimes fail to see the `Add` and per project `x` buttons. This is normally resolved via a page refresh, or navigating away and returning.

**Comment by richard-cox** [comment]
@anupama2501 Sorry for the issue spam. Zube and other bots not behaving well. Both this and https://github.com/rancher/dashboard/issues/9158 are ready to test

**Comment by anupama2501** [comment]
Verified on v2.7-head `0bcf068`

Enabled azure AD auth providers.
Verified adding users as cluster owner/project owner/cluster members - adding and deleting users from project Membership page works as expected.

**Comment by richard-cox** [comment]
Given https://github.com/rancher/dashboard/issues/9198, this bug is not longer relevant
