### ISSUE TITLE
User should be prompted to change password when accessing the Dashboard UI for the first time.

### ISSUE THREAD

**Issue by sangeethah** [rancher/dashboard#916]
Rancher server version - 6d6199121 (HA install)

When accessing rancher server user for the first time , user is directed to the dashboard log in page where he is expected to enter username and password.

User should be prompted to change password when accessing the Dashboard UI for the first time.

**Comment by deniseschannon** [comment]
In 2.5, the first login will be in the ember UI, so bumping this out of 2.5.
