### ISSUE TITLE
Login page change

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#917]
Change the UX of the login page for Dashboard.

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/913

**Comment by deniseschannon** [comment]
- [ ] Remove "Dashboard" text from login screen

<img width="296" alt="Screen Shot 2020-07-30 at 7 06 25 AM" src="https://user-images.githubusercontent.com/11410997/88932637-330ee280-d233-11ea-94d3-c2cc972feaa9.png">

- [ ] Do we want to add/create friendly Rancher text like in 2.4? 

<img width="405" alt="Screen Shot 2020-07-30 at 7 11 56 AM" src="https://user-images.githubusercontent.com/11410997/88933243-00191e80-d234-11ea-8dd9-9114048ebe99.png">

- [ ] When resizing width of log in, do not adjust the textboxes for username/password and text for "Remember Username"

<img width="334" alt="Screen Shot 2020-07-30 at 7 07 44 AM" src="https://user-images.githubusercontent.com/11410997/88933120-db24ab80-d233-11ea-8f2e-84f6b4d15fe1.png">

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1039

**Comment by deniseschannon** [comment]
If not logged in and you go to `<address>/dashboard`, redirect to `<address>` to log into the ember login page.
