### ISSUE TITLE
Add "v23.0.x" option for "Docker Install URL" dropdown

### ISSUE THREAD

**Issue by rayandas** [rancher/dashboard#9177]
**Is your feature request related to a problem? Please describe.**

As part of https://github.com/rancher/rancher/issues/41851 we're adding support for Docker 24.0.x

**Describe the solution you'd like**

UI dropdowns that allow picking "Docker Install URL" (e.g. on Node Template details page - not sure where else it may be referenced) should have additional "v23.0" choice that populates `https://releases.rancher.com/install-docker/23.0.sh` when selected.

**Describe alternatives you've considered**

Note "Docker Install URL" is editable and doesn't limit users to only the choices available, so they can specify `https://releases.rancher.com/install-docker/24.0.sh` manually as well before this enhancement is done.
Consequently existing option "v23.0.x (Recommended)" should be changed to "v23.0.x".

**Additional context**

Please refer to the snapshot where you can see 23.0.x is not visible on the drop down list.

![Screenshot from 2023-06-23 17-38-40](https://github.com/rancher/dashboard/assets/32811240/d9e2e3cd-ce0d-4871-ab3d-bb63657369bf)

Similar issue https://github.com/rancher/dashboard/issues/8682

**Comment by gaktive** [comment]
24.0.x will be part of https://github.com/rancher/dashboard/issues/9222 so hopefully we can get both over to QA at the same time.

**Comment by rayandas** [comment]
Note that Docker 24.0.x is not yet release by Rancher, hence we should wait before adding it to the UI.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(58aede6)
- Both docker version v24.0.sh and and v23.0.sh are visible on the UI dropdown.
- Node driver cluster using k8s v1.26.6-rancher1-1, provisioned successfully using both the docker versions.

Result :

![docker-versions](https://github.com/rancher/dashboard/assets/36376154/df3ed7c4-c92a-4d97-bda4-329d182aefa6)

**Comment by rishabhmsra** [comment]
Validations are completed, hence closing it.
