### ISSUE TITLE
Post enabling ECM in the dashboard, user should be able to navigate to ECM page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#918]
**On master-head - latest - commit id: `6d6199121`**

- Login to Dashboard
- Go to Apps --> Charts --> Click on Enterpise Cluster Manager --> Click on Create/Finish
- ECM is deployed successfully.
- Currently user has to navigate to the URL https:??<rancher-server> to access the amber view 

**Expected:**
There should be an Icon/tab where user can click on and be navigated to the amber view

**Comment by vincent99** [comment]
It's in the product dropdown. There may be client and/or server issues with it showing up immediately after installing or until reloading the page.

**Comment by deniseschannon** [comment]
This is no longer applicable as ECM will always be on.
