### ISSUE TITLE
[EKS] Security Group section is missing when creating EKS cluster

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/dashboard#9182]
**Setup**
- Rancher version: v2.7-head 0bcf068
- Browser type & version: Chrome

**Describe the bug**

When creating an EKS cluster on v2.7-head, the security group section is missing and only shows logging and node group configuration.

**To Reproduce**

1. Create EKS cluster on v2.7-head
2. After configuring VPC under `Networking` section, select `Next: Select Security Group`

**Result**
The security group section is missing and gets skipped to logging and node group configuration.
![image](https://github.com/rancher/dashboard/assets/108360907/e824a283-7418-422c-9215-67e8b156a000)
![image](https://github.com/rancher/dashboard/assets/108360907/120e1858-2e91-478c-aa9a-865aa290028b)
Cluster is able to create without the security group configuration and security group configuration is left blank.
![image](https://github.com/rancher/dashboard/assets/108360907/cb229ebd-05cf-4d4b-93a7-15ebbeb61ae4)

Cluster gets stuck in updating with the following error
```
Waiting for API to be available:controller.FailureMessage{ClusterName:"", Message_:"Security group sg-<security-group> and subnet subnet-<subnet> belong to different networks.", NodegroupName:""}
```

**Expected Result**

There should be a security group section where users can choose the security group to use for the eks cluster

**Comment by cpinjani** [comment]
**Additional context:**
Security group selection section is displayed only when choosing Custom Subnet type:
![image](https://github.com/rancher/dashboard/assets/73099870/9fbc76cc-d9c7-4c32-ac35-ffc98148dc21)

![image](https://github.com/rancher/dashboard/assets/73099870/159cd0f1-53b1-447b-a07c-6b6f0463b82b)

**Comment by nwmac** [comment]
@gaktive This is not a regression - issue in is 2.7.4, so this shouldn't be a release blocker. Can you remove the label. We should bump to next3

**Comment by richard-cox** [comment]
Alex will add more detail later today, but together we confirmed what Nancy said yesterday. The code hasn't changed for years and it's pretty much if subnet === 'custom' --> show security groups. We've tested with the ui-index set to 2.7.4 as well, same outcome (suggesting it's not a regression in 2.7.5), Alex will confirm with an actual 2.7.4 install.

**Comment by thaneunsoo** [comment]
Sorry for the scare, the problem was with the template I was using for the node group. I ran it again just now and it was fine. Closing this ticket as not reproducible.
![image](https://github.com/rancher/dashboard/assets/108360907/fed5a5c2-3ad3-4a02-85c0-4e258a4b7433)

**Comment by gaktive** [comment]
Thanks @thaneunsoo
