### ISSUE TITLE
Revert display of Cluster and Projects page for users with project roles and no cluster roles

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9198]
See description in https://github.com/rancher/dashboard/pull/9197#issue-1771611768

**Comment by anupama2501** [comment]
Verified on v2.7-head `0bcf068`, UI version `release-2.7.5 093b300b8`

Updated the dashboard and UI index to: `https://releases.rancher.com/dashboard/release-2.7.5/index.html` and `https://releases.rancher.com/ui/release-2.7.5/index.html`

- Verified the project membership page is not longer available for project Members, project Owners, and members from groups added as project owners.
- Verified for restricted admin, cluster owner can view the cluster and project membership page. Cluster members, custom cluster permissions can view the project membership page when they have project created .
