### ISSUE TITLE
The user function button will automatically change from "Edit Config" to "View Config"

### ISSUE THREAD

**Issue by yishenqing** [rancher/dashboard#9206]
**Setup**
Rancher version: 2.7.0
Browser type & version: Chrome

**Describe the bug**
After the admin user logs in, on the Users page under the Users & Authentication menu, the Edit Config function of the non-admin user automatically changes to View Config after a period of time. Refreshing the page or "Refresh Group Memberships" will redisplay "Edit Config", but after some time it will become "View Config" again, the time is not exact.
Is this a bug or a normal mechanism？

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/55734817/a81edb28-d233-4966-a229-cfaf0f135b07)
![image](https://github.com/rancher/dashboard/assets/55734817/596aaf74-5bf3-4239-bf1f-e2b9920f82b9)

**Comment by richard-cox** [comment]
The action will show as `Edit Config` if the underlying resource has a `link.update` value. It shouldn't change given the permissions of the signed in user shouldn't be changing much.

For this table the resource is `management.cattle.io.users`. I'm guessing something is happening in rancher to signed in user and an updated set of users missing the link value is pushed to the UI via socket.

This can be validated by going to `<rancher url>/v1/management.cattle.io.users` and clicking on the id of the affected user. If that shows `links: { "update": "blocked", .. }` (blocked text is fine) but sometimes not then I think you'll need to open a ticket over at `rancher/rancher`. If it always shows the same feel free to re-open this issue
