### ISSUE TITLE
StatefulSet yaml creation throws error

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#921]
Attempting to create a StatefulSet from its list view returns an error: ``unknown schema for type: "io.k8s.api.core.v1.PersistentVolumeClaim"``

**Comment by sowmyav27** [comment]
**Seeing this issue on master-head - commit id: `65a2b808c`**

- Login to Dash --> Click on Statefulset from CLuster Explorer view --> Create
- Error seen in console: 
```
create-yaml.js:58 Uncaught (in promise) Error: Unknown schema for
    at n (create-yaml.js:58)
    at R (create-yaml.js:190)
    at create-yaml.js:122
    at Array.map (<anonymous>)
    at n (create-yaml.js:121)
    at R (create-yaml.js:220)
    at create-yaml.js:118
    at Array.map (<anonymous>)
    at n (create-yaml.js:117)
    at index.vue:92
```

**Comment by deniseschannon** [comment]
Moving this to test but there is still an open issue regarding loading the yaml: https://github.com/rancher/dashboard/issues/1336

**Comment by sowmyav27** [comment]
**On master-head - commit id: `0ccce4501`**

- Login to Dashboard --> Click on Statefulset from Cluster Explorer view --> Create
- No error is seen in the console.
- User is able to deploy a statefulset workload.
- User is also able to list it -- Workload --> Overview and Workload --> Statefulset. No error seen
