### ISSUE TITLE
Extensions: Add partner repository

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9214]
We are introducing an additional repository:

- https://github.com/rancher/partner-extensions

We currently have the Rancher extensions repo - we now need a Partner repository.

We need to cover 3 cases:

(1) Fresh install of Extensions (i.e. enabling the Extensions operator) - we need to add this repository as part of dong this and allow the user to chose when installing (and uninstalling) - e.g. for installing:

<img width="616" alt="image" src="https://github.com/rancher/dashboard/assets/1955897/31990149-08e4-48f8-8f33-596a2288be36">

(We should add a checkbox and also do the same for uninstall)

(2) Upgrade

If a user upgrades and already has the extensions operator installed, we need to allow them to add the new repository.

I'd suggest we add a new setting - in case 1 above, we set this setting, so we know the user has done a fresh install.

On the extensions page, we check for this setting - if not set, we show a banner saying that new repository is available - closing the banner will set the setting, so we don't show it again. We also provide a button/link in the banner that when clicked will add the new repository and set the new setting - this should open a dialog to do this - same as (3) below.

(3) Manual

In step (2), the user might dismiss the banner but then decide they want to add the new repository - we should provide a new option in the menu from the three dots:

![image](https://github.com/rancher/dashboard/assets/1955897/195c52b3-1439-4137-8310-f180492157b8)

Suggest adding a new option 'Add Rancher Repositories' below 'Manage Repositories'.

This would bring up a dialog same as for enabling extensions, but only with 2 checkboxes for each of the Rancher repositories.

**Comment by gaktive** [comment]
QA would like to look at this feature, so reopening for them to look at.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID d8a2bca`
1. enabled extensions with partner repo
2. enabled extensions with rancher repos
3. installed kmaji plugin
3. verified installation
4. disabled extensions
Test 2
1. enabled extensions without partner repo
2. added partner repo after enabling
3. disabled extensions
Test 3
1. verified banner formatted properly on partners repo page
![2023-08-02_12-52-20.png](https://zube.io/files/rancher/f7322fe5fe734a7e39e3f70c7b6898b6-2023-08-02_12-52-20.png)
![2023-08-02_12-53-51.png](https://zube.io/files/rancher/39642b80260aa39fc1ffd56948356644-2023-08-02_12-53-51.png)
![2023-08-02_12-52-02.png](https://zube.io/files/rancher/6bf6b9b5ea7ad8ef6b9ad3e8cda850b1-2023-08-02_12-52-02.png)
