### ISSUE TITLE
Add new EKS region 'ap-northeast-3' so it can be selected when validating creds

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#9219]
**Setup**
- Rancher version: v2.7-3aedc24d3087c3bbc4deb4d8c5ae40f55945e913-head
- Browser type & version: Firefox

**Describe the bug**
Add new EKS region 'ap-northeast-3' so it can be selected when validating AWS credentials, similar to https://github.com/rancher/ui/pull/5039
The region is already part of EKS regions list. Found while validating https://github.com/rancher/dashboard/issues/8701

**Screenshot**
![image](https://github.com/rancher/dashboard/assets/73099870/6ace826f-e164-40bb-8293-0160f60aa5b4)

@richard-cox FYI.

**Comment by richard-cox** [comment]
How does this compare to https://github.com/rancher/dashboard/issues/9220?

The new regions should already be visible when creating creds in the create EKS / RKE1 EC2 screens.

**Comment by cpinjani** [comment]
This compares to https://github.com/rancher/ui/pull/5039,
so that the region is visible in create EKS screen.

**Comment by richard-cox** [comment]
ah, ok, this was missed off.

This means updating lib/shared/addon/utils/amazon.js REGIONS with `ap-northeast-3`

**Comment by richard-cox** [comment]
Addressed in 2.9.0 as part of https://github.com/rancher/dashboard/issues/10294 - https://github.com/rancher/ui/pull/5112/files#diff-73866f48f40e65309c7356a070e404493ebbdf902ab57ca31ecd1936c019e8f1R635
