### ISSUE TITLE
UI for RKE1 Docker 24.0.x Support

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9222]
Internal Ref: SURE-6516

Add support for Docker 24 - note, as before, we add Docker 23 support and then Docker 24 appears when the backend update to add it.

**Comment by gaktive** [comment]
Related backend: https://github.com/rancher/rancher/issues/41851

**Comment by gaktive** [comment]
And we should get 23.0.x in too before giving to QA or else things could get wild: https://github.com/rancher/dashboard/issues/9177

**Comment by rayandas** [comment]
Pleas note that Docker 24.0.x is not yet release by Rancher, hence we should wait before adding it to the UI.
cc: @gaktive

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(58aede6)

Both docker version v24.0.sh and and v23.0.sh are visible on the UI dropdown.
Node driver cluster using k8s v1.26.6-rancher1-1, provisioned successfully using both the docker versions.

Result :

![docker-versions](https://github.com/rancher/dashboard/assets/36376154/6cd5e6e7-a93d-422d-bd1d-1656f13bc0fc)

**Comment by rishabhmsra** [comment]
Validations are completed, hence closing it.
