### ISSUE TITLE
UI for Fleet Drift Detection and Reconciliation

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9223]
Internal Reference: SURE-6464

Add support for a checkbox to enable "Drift Detection and Reconciliation" on a Git Repo.

**Comment by sbulage** [comment]
Auto-reconciliation is working as expected via UI. See below screenshot.
For more test scenario: https://github.com/rancher/fleet/issues/1551

![Selection_084](https://github.com/rancher/dashboard/assets/12134754/1e2162fd-b9c9-457c-b278-e7451e0d5167)
