### ISSUE TITLE
Don't show error icon when a cluster is updating

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9227]
When you provision a cluster and it is in the updating state, we show the error iconL:

![image](https://github.com/rancher/dashboard/assets/1955897/6dae22e2-1d07-4221-8500-8feafbae506e)

This is because  one of the conditions is not ready - you'll see this if you look at the cluster and its conditions:

![image](https://github.com/rancher/dashboard/assets/1955897/bb7a6b74-9290-4375-9417-31336b17de53)

We should update this so that if the cluster is transitioning/updating, we don't show the error icon, since the user knows the cluster is in the process of updating - the purpose of showing the error icon is to alert users to an error condition for a cluster that they expect to be in a stable state.

**Comment by susesgartner** [comment]
Ticket #9227 - Test Results - ✅ 
---

Verified with (HA Helm or Docker) on Rancher `v2.X.X`:
1. Fresh install of rancher v2.7-head
2. Start the provisioning of a EC2 v1.26.6+rke2r1 cluster
3. Verified that no error icon is present on either the cluster display or the conditions
<img width="468" alt="image" src="https://github.com/rancher/dashboard/assets/136753565/8a70af6a-9acc-4bd0-8166-cd6fb2ebd590">
<img width="468" alt="image" src="https://github.com/rancher/dashboard/assets/136753565/8b9ac007-0d0f-4c24-ba92-5bd3eb827bfc">
