### ISSUE TITLE
Relocate Cluster Tools button

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9228]
(Design for Q3, implement for Q4)

In 2.6, with the new UI we added a Cluster Tools button to the bottom of the side nav when exploring a cluster, so users could easily get to the tools section - to help with migrating from the old UI.

![image](https://github.com/rancher/dashboard/assets/1955897/c2e529bc-49c9-41de-919c-f55873c926c9)

Now we're at 2.7, we should figure out where to put cluster tools so that we can remove this item from the side bar.

Suggestion would be a `Tools` item under the Cluster nav, i.e.

![image](https://github.com/rancher/dashboard/assets/1955897/b7193c16-2f7c-4144-b4a4-8fc6933058fa)

I'd also suggest adding a link to the Cluster Dashboard page:

![image](https://github.com/rancher/dashboard/assets/1955897/56045ef9-f72d-4a5c-b726-2f4edbfeae5b)

Suggestion would be to stack the links 'Add cluster badge and install monitoring vertically and to add 'Manage Cluster Tools' in there as well - e.g.

![image](https://github.com/rancher/dashboard/assets/1955897/f5394b39-d23c-49e7-a682-9498f5d7e6e3)

We could take the opportunity to make that header look more visual - we should show the infrastructure provider as well as the k8s provider.

**Comment by edenhernandez-suse** [comment]
Our first idea, given we keep the Cluster Tools page, would be the following:
- Remove the Cluster Tools button
- Add a link in Cluster Dashboard (maybe near the title) to the Tools page with a proper label
- Change the "Edit Cluster Badge" link to a "Customize Appearance" button.

[Xd Prototype](https://xd.adobe.com/view/5d5d5ead-b9d6-4a42-922e-805bb04088c5-080e/?hints=off)

**Comment by nwmac** [comment]
@edenhernandez-suse Design looks good - I think we should proceed with implementing what you propose.

**Comment by edenhernandez-suse** [comment]
I created a new [Spec prototype](https://xd.adobe.com/view/30c5a51c-e7b7-4ebf-b75f-1dc37391d3d7-6596/). Maybe we can include it in the description of this issue.

**Comment by IsaSih** [comment]
So, the cluster tools links on the dashboard page and in the side nav are working as expected. However, the `Customize Appearence` is a label only displayed when the user hovers over the painting brush icon. 

https://github.com/rancher/dashboard/assets/70187881/698a0eed-18a5-49b5-9f10-c17e5f62f210

**Comment by edenhernandez-suse** [comment]
@IsaSih my bad, at some point during our discussions around this we decided to minimise that button to just an icon button with a tooltip, but I never updated the prototype link. It's working as expected.
