### ISSUE TITLE
Remove 'Use the new cluster tools' banner

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9229]
On the cluster dashboard page, we show a banner at the top - `User the new Cluster tools to manage ...`

We can remove this banner now.

![image](https://github.com/rancher/dashboard/assets/1955897/6373371f-42dd-4b84-bd07-33a30004d145)

**Comment by Josh-Diamond** [comment]
Ticket #9229 - Test Results - ✅ 
---

Verified w/ HA Helm Rancher on `v2.7-5f98b0f28bc8a48366e9ced8f0a0fea3d826d90d-head`:
1. Fresh install of Rancher `v2.7-head`
2. Navigate to `Cluster Explorer > local > Cluster Dashboard`
3. Verified - `Use the new cluster tools...` banner has been removed; as expected

Screenshot:
<img width="1662" alt="Screenshot 2023-07-13 at 9 17 14 AM" src="https://github.com/rancher/dashboard/assets/46494969/9a104135-4c66-4aa4-a36f-0cdf0bea5e9d">
