### ISSUE TITLE
Design template for custom deployment pages

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#923]
Need to have a template that will provide a consistent look/feel for the custom deployment pages:
https://github.com/rancher/dashboard/issues/895 => Logging
https://github.com/rancher/dashboard/issues/909 => Monitoring
https://github.com/rancher/dashboard/issues/894 => Istio

**Comment by lvuch** [comment]
https://xd.adobe.com/view/6116eb0f-4dc1-4c8b-ad57-ed8038406645-3445/
