### ISSUE TITLE
Fix E2E flakiness

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9233]
Our E2E tests still show some flakiness when they run, meaning that we have to rerun them regularly. This may require some digging through past failures to see what's going on.

We have other tickets in place with specific actions to clean up:
rancher/dashboard#9040
rancher/dashboard#8956

**Comment by richard-cox** [comment]
Linking three which are probably all user avatar related
- https://github.com/rancher/dashboard/issues/8975
- https://github.com/rancher/dashboard/issues/8957
- https://github.com/rancher/dashboard/issues/8976

**Comment by richard-cox** [comment]
Given most are User avatar related, should be resolved via https://github.com/rancher/dashboard/pull/9718.

If we get more flaky tests we should track specific ones here (and re-open) or in in a new issue
