### ISSUE TITLE
Image table column should wrap

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9235]
Example on Pod table:

<img width="1181" alt="image" src="https://github.com/rancher/dashboard/assets/1955897/35555072-91da-4d42-aa5c-6eb9225fc098">

The image column does not wrap/break correctly, so long image names expand the column size.

The `image` column should use `word-break: break-all`.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 5f98b0f
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
The text wrap and break is now using `word-break: break-all` and the text is correctly breaking according to window size and not stretching out the image column.
![image.png](https://zube.io/files/rancher/afbd77ab500ce508146d512227a16f72-image.png)
![image.png](https://zube.io/files/rancher/0fd5e291e127e21120352c3b0284e4f0-image.png)
![image.png](https://zube.io/files/rancher/6b7d16e8cf903cf8790b189589181081-image.png)
