### ISSUE TITLE
Pod detail view shows full-view loading indicator briefly

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9236]
Go to the detail view of a pod:

![image](https://github.com/rancher/dashboard/assets/1955897/dba47bb2-f5cc-4b2a-b445-5240a0ca7e31)

Observe that the page changes and then you briefly get a loading indicator on a grey panel.

This is because the page is using `fetch` with.a loading indicator - we should show the content as soon as possible and not use a loading indicator - other bits of the UI that need data should update when the data has been loaded.

**Comment by brudnak** [comment]
# ❌ Reopened

## Validation Environment


| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version                  | v2.7-e5deaaf81f8af41a1219d3470a0876d384119386-head |
| Installation option              | Helm (high availability)                           |
| RKE binary version used          | v1.4.4                                             |
| If Helm Chart k8s cluster        | v1.26.4                                            |
| Cert Details                     | external tls aws acm alb                           |
| Docker version                   | 20.10.7, build f0df350                             |
| Downstream cluster type          | n/a                                                |
| Downstream K8s version           | n/a                                                |
| Authentication providers enabled | local                                              |
| Logged in user role              | admin                                              |
| Browser type                     | Opera GX                                           |
| Browser version                  | LVL5 (core: 100.0.4815.82) (x86_64)                |
| Dashboard                        | master d923e267c                                   |


<a name="top"></a>

### :muscle: Test Cases

| \#  | Priority | Description & Link | PASS/FAIL |
| --- | -------- | ------------------ | --------- |
| 1   | P0       | [Test 1](#test-1)  | ❌ FAIL    |


<hr>

<a name="test-1"></a>

## :mag_right: `#`1 / Status: ❌ FAIL 


#### :small_red_triangle: [Back to top](#top)

<details>
    <summary>Test 1 details... Click to expand</summary>

#### Test Steps for Validation:

1. **Installation**:
   - Install Rancher on version 2.7-head.
   - Install the monitoring tool as shown in the original issue.

2. **Navigation to Pod Details**:
   1. Begin at `dashboard/home`.
   2. Proceed to the hamburger menu.
   3. Select `local`.
   4. Choose `workloads`.
   5. Navigate to `pods`.
   6. Click on any listed pod.

3. **Refresh**:
   - Press `ctrl + r`.

4. **Loading Sequence**:
   - Observe an initial "white" loading screen.
   - After this, note if a secondary loading screen appears briefly.

#### ✅ Expected Outcome:

The loading spinner should be absent as per the reported ticket.

#### ❌ Actual Outcome:

The loading spinner remains visible.


</details>

<hr>

**Comment by brudnak** [comment]
# ✅ Pass

## Validation Environment


| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version                  | v2.7-e5deaaf81f8af41a1219d3470a0876d384119386-head |
| Installation option              | Helm (high availability)                           |
| RKE binary version used          | v1.4.4                                             |
| If Helm Chart k8s cluster        | v1.26.4                                            |
| Cert Details                     | external tls aws acm alb                           |
| Docker version                   | 20.10.7, build f0df350                             |
| Downstream cluster type          | n/a                                                |
| Downstream K8s version           | n/a                                                |
| Authentication providers enabled | local                                              |
| Logged in user role              | admin                                              |
| Browser type                     | Opera GX                                           |
| Browser version                  | LVL5 (core: 100.0.4815.82) (x86_64)                |
| Dashboard                        | master d923e267c                                   |


<a name="top"></a>

### :muscle: Test Cases

| \#  | Priority | Description & Link | PASS/FAIL |
| --- | -------- | ------------------ | --------- |
| 1   | P0       | [Test 1](#test-1)  | ✅  PASS    |


<hr>

<a name="test-1"></a>

## :mag_right: `#`1 / Status: ✅  PASS 


#### :small_red_triangle: [Back to top](#top)

<details>
    <summary>Test 1 details... Click to expand</summary>

#### Test Steps for Validation:

1. **Installation**:
   - Install Rancher on version 2.7-head.
   - Install the monitoring tool as shown in the original issue.

2. **Navigation to Pod Details**:
   1. In the browser, right click and go to inspect >>> network >>> then throttle to slow 3G.
   2. Begin at `dashboard/home`.
   3. Proceed to the hamburger menu.
   4. Select `local`.
   5. Choose `workloads`.
   6. Navigate to `pods`.
   7. Click on any listed pod.

#### ✅ Expected Outcome:

The loading spinner should be absent as per the reported ticket.

#### ✅ Actual Outcome:

The loading spinner wasn't visible.


</details>

<hr>
