### ISSUE TITLE
Marketplace design review

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#924]
Date - 7/29

- [x] Change pink color for charts to purple or other color

- [ ] research adding Header image to top of charts page - example:
![image](https://user-images.githubusercontent.com/11514927/88848766-c564a700-d19d-11ea-9a3f-b5b173a71f91.png)

- [x] Change experimental text to black on all charts
![image](https://user-images.githubusercontent.com/11514927/88848871-e75e2980-d19d-11ea-97b1-32d02eab5513.png)

- [x] Delete modal need styling review
![image](https://user-images.githubusercontent.com/11514927/88848991-0eb4f680-d19e-11ea-89fe-9af8fbbd838b.png)

- [x] Chart description from Helm Options needs styling review.  I think it needs to go into box?
![image](https://user-images.githubusercontent.com/11514927/88849195-67848f00-d19e-11ea-8d38-671a59c6e37b.png)

- [x] Blue header is weird on all list pages
![image](https://user-images.githubusercontent.com/11514927/88849339-97339700-d19e-11ea-9b6e-3b43166d4333.png)

- [x] Buttons for Apps & kubectl need styling review
![image](https://user-images.githubusercontent.com/11514927/88849501-d235ca80-d19e-11ea-8be1-2bdca61bc5dc.png)

- [x] Review state badges.  Solid vs. non-solid background, white vs black text, uppercase Active vs. lower case error.  Border for Active or no border?
![image](https://user-images.githubusercontent.com/11514927/88849911-6dc73b00-d19f-11ea-92d1-d1d4c8502268.png)
![image](https://user-images.githubusercontent.com/11514927/88851503-b253d600-d1a1-11ea-9731-2ce7396a5186.png)
![image](https://user-images.githubusercontent.com/11514927/88851134-2e015300-d1a1-11ea-91e0-5111c8fde04a.png)

- [x] Directional shading (Vincent thinks it should always go light at top left to darker on bottom)
![image](https://user-images.githubusercontent.com/11514927/88850213-dd3d2a80-d19f-11ea-8e08-6d745e41007b.png)

- [x] Disabled button for light view doesn't really seem disabled cause it's so dark?
![image](https://user-images.githubusercontent.com/11514927/88852248-dd8af500-d1a2-11ea-8f5c-2f1a57f968d8.png)
Old Rancher
![image](https://user-images.githubusercontent.com/11514927/88852453-25118100-d1a3-11ea-8180-49461d047466.png)

- [ ] Charts, Helm Operations, Installed Apps & Repositories should all align on the left & be same font size.  Only the Cluster Level & Namespace Repos should be indented and smaller font.
![image](https://user-images.githubusercontent.com/11514927/88853113-1b3c4d80-d1a4-11ea-91c1-dc3477667ba8.png)

- [x] Should the Title font size in the Main drop-down be larger?  It just looks so small against the menu options in the drop-down.
![image](https://user-images.githubusercontent.com/11514927/88855697-1aa5b600-d1a8-11ea-8b9c-efe007e0728f.png)

**Comment by deniseschannon** [comment]
@tfiduccia I think some of these are old enough that they can be ignored, but wanted to send to you to validate just in case.

**Comment by tfiduccia** [comment]
Verified fixed.
