### ISSUE TITLE
E2E job parallelization by user role and functionality

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#9243]
Currently, admin and standard user tests run asynchronously but we want them to run in parallel. To handle this, lets pull the Rancher setup spec out of the admin test run and put it in its own step, that way the setup step would precede both the admin and standard user test steps and they can run in parallel.

For more details see conversation [here](https://github.com/rancher/dashboard/pull/9029/commits/87d3a64a67264a50099c817d8da774b04fb8d2cc#r1234481971).

NOTE: `standard_user` creation has been added in the Rancher setup test.

**Comment by richard-cox** [comment]
This should be done alongside https://github.com/rancher/dashboard/issues/9064

**Comment by cnotv** [comment]
I think that if the only issue here is to initialize the Rancher instance, we may rather create a function for that.

In the current state it's necessary to build and run an image of Rancher for both to have 2 separated environments.

**Comment by cnotv** [comment]
> This should be done alongside #9064

That's more about run tests in parallels, not jobs in parallel, so are 2 different cases.

**Comment by cnotv** [comment]
It looks like for the setup we cannot use tags or at least not the same
https://github.com/rancher/dashboard/actions/runs/6487538005?pr=9887

![Screenshot 2023-10-11 at 22 39 45](https://github.com/rancher/dashboard/assets/5009481/a8cfba63-994c-4dd5-9460-2ab77a5d5357)

**Comment by cnotv** [comment]
After talking to @richard-cox and @nwmac we decided to try more job splitting by path/tag, so we can create categories or isolate long jobs which cause issues.

**Comment by cnotv** [comment]
@yonasberhe23 @richard-cox Are we sure the tests are idempotent? I have run 5 times in parallel and the same tests keep failing.

<img width="604" alt="Screenshot 2023-11-17 at 09 19 47" src="https://github.com/rancher/dashboard/assets/5009481/d29b7669-05db-4ffc-ae32-2417ef092088">
