### ISSUE TITLE
Improve Table(s) ReDesign

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#9245]
Tables are the main component of the Rancher Manager, but they might not be the best fit for every situation.
This task aims to consider a different number of use cases and understand whether a table is the best choice for a specific situation and what may be a better alternative. Plus understand if and how the component itself could be improved.

Initial scope:

- Make a list of all use-cases for tables
- Order this information to understand how many different types of tables there are

**Comment by manuelecarlini** [comment]
We can find the first result of the exploration here
https://confluence.suse.com/display/CU/Tables+Exploration+for+Rancher+Manager
