### ISSUE TITLE
[RKE2] Cluster unable to provision after switching back to `Back to Form` from `Edit as YAML`

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/dashboard#9248]
**Setup**
- Rancher version: v2.7-head c402790
- Rancher UI Extensions:
- Browser type & version: Chrome Build 114

**Describe the bug**

When creating a cluster, I went to the `Edit as YAML` and went back to the form edit, I tried to create the cluster but it failed with an error saying `"undefined" is not valid in JSON`
![image](https://github.com/rancher/dashboard/assets/108360907/072ff36f-166c-4f21-be33-a985ce535851)

**To Reproduce**

1. Provision RKE2 AWS node driver cluster on v2.7-head
2. Fill out the default values for provisioning the cluster
3. Click `Edit as YAML`
4. Click `Back to Form`
5. Click `Create`

**Result**
Rancher hits a white page with the error `"undefined" is not valid in JSON`

**Expected Result**

Rancher should be able to provision the cluster since all the default values to create the cluster are filled out. When I do the same steps without going to the YAML and back to form, it works as expected.

**Comment by cnotv** [comment]
Created tech debt related to this https://github.com/rancher/dashboard/issues/9267

**Comment by cnotv** [comment]
Added tech debt related usage of hook causing issue: https://github.com/rancher/dashboard/issues/9275
