### ISSUE TITLE
Helm Chart values not parsed correctly (PodSpec.nodeSelector: got "map", expected "string")

### ISSUE THREAD

**Issue by vizzard** [rancher/dashboard#9249]
**Rancher Server Setup**
- Rancher version: **v2.6.2**
- Installation option (Docker install/Helm Chart): **Helm Chart**
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): **RKE1, Kubernetes v1.19.10**
- Proxy/Cert Details: **Nginx Ingress Controller (came with RKE1 cluster), Rancher-generated TLS certificate (cert-manager installed)**

**Information about the Cluster**
- Kubernetes version: **v1.21.5**	
- Cluster Type (Local/Downstream): **Downstream**
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): **VMware vSphere provider**

**Describe the bug**
Unable to deploy Nginx Ingress Controller on downstream cluster (VMware vSphere provider) from Rancher UI (Apps & Marketplace) with `controller.nodeSelector` set to `node-role.kubernetes.io/worker: 'true'`.  
Deployment with the same values is successful when deploying with helm from CLI:
```
cat > nginx-controller-load-balancer-service.yaml <<EOF
controller:
  nodeSelector:
    node-role.kubernetes.io/worker: 'true'
EOF

helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx -f nginx-controller-load-balancer-service.yaml --version=4.0.8
```
Since it works from CLI, this seems to be Rancher issue.

**To Reproduce**
- Add `ingress-nginx` repository to Rancher (Apps & Marketplace) using this URL (from their docs): `https://kubernetes.github.io/ingress-nginx`
- Try to deploy Nginx Ingress Controller from Rancher UI (Helm Chart version 4.0.8) changing `controller.nodeSelector` to in values yaml (single change in line 149):
```
  nodeSelector:
    node-role.kubernetes.io/worker: 'true'
```

**Result**
Helm install error:
> helm install --namespace=ingress-nginx --timeout=10m0s --values=/home/shell/helm/values-ingress-nginx-4.0.8.yaml --version=4.0.8 --wait=true ingress-nginx /home/shell/helm/ingress-nginx-4.0.8.tgz
> Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.nodeSelector.kubernetes): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got "map", expected "string"

**Expected Result**
Successful installation.

**Additional context**
Default selector only works:
```
  nodeSelector:
    kubernetes.io/os: linux
```
Keeping default selector works:
```
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: 'true'
```
Does not work:
```
  nodeSelector:
    node-role.kubernetes.io/worker: true
```
```
  nodeSelector:
    node-role.kubernetes.io/worker: 'true'
```
```
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
```

**Comment by gaktive** [comment]
Per @kinarashah's notes, we're allowing duplicate values in through the editor somehow. We should look at the install component first, where there's code to merge new values into the resource class.

**Comment by slickwarren** [comment]
not sure who is assigned this issue, but manually testing this is working following the aws out-of-tree documentation

**Comment by izaac** [comment]
Hey @slickwarren do you mean this was covered by these other issues validation?

https://github.com/rancher/dashboard/issues/9110
https://github.com/rancher/rancher-docs/pull/844

**Comment by izaac** [comment]
Automation coverage is here https://github.com/rancher/dashboard/pull/9865
Closing as the automation coverage looks right.
