### ISSUE TITLE
Follow-up from code comments on cluster overview

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#925]
We have had to merge a couple of last minute things for demos/previews so trying to capture comments that weren't fixed before merging. 

https://github.com/rancher/dashboard/pull/870#discussion_r458626940
https://github.com/rancher/dashboard/pull/870#discussion_r458632612
https://github.com/rancher/dashboard/pull/870#issuecomment-662401520

**Comment by deniseschannon** [comment]
I haven't reviewed the code comments, but from playing around the overview page, here are some other issues: 

- [ ] Switch from "Created" to "Age". Add ability to hover over age to see when it was created. 
<img width="354" alt="Screen Shot 2020-07-30 at 6 48 59 AM" src="https://user-images.githubusercontent.com/11410997/88930767-c2ff5d00-d230-11ea-952e-9cfddc9abebe.png">

- [ ] Hide warning/errors if there are none. If there is >1 for either warning or error, show both icons to keep alignment. 
- [ ] Increase icon and number size of warning/error

<img width="115" alt="Screen Shot 2020-07-30 at 6 49 43 AM" src="https://user-images.githubusercontent.com/11410997/88930830-dca0a480-d230-11ea-9090-63f9218df8dc.png">

-[ ] Adjust the column widths to allow the message column to be wider:
<img width="1046" alt="Screen Shot 2020-07-30 at 6 57 34 AM" src="https://user-images.githubusercontent.com/11410997/88931719-0c03e100-d232-11ea-8fe3-7c9d0fdf1972.png">

**Comment by izaac** [comment]
In the cluster Overview I no longer see the Memory and RAM components shown in recent `master-head` builds. I've tried a number of different clusters GKE, RKE DO, Imported (HA local) 

/v1/management.cattle.io.clusters/<cluster>

Returns both `allocatable` and `requested` metrics like (from a GKE cluster):

```json
"allocatable": {
"cpu": "2820m",
"memory": "8059804Ki",
"pods": "330"
},
```

```json
requested": {
"cpu": "1305m",
"memory": "1307Mi",
"pods": "21"
},
```

**Comment by izaac** [comment]
Rancher version: `master-head (08/26/2020)` _a1acca856_ 

Resource graphs are now properly displayed for local and downstream clusters. GKE, RKE, Imported k3s (systemd).
Opened an issue about k3s (openrc) https://github.com/rancher/rancher/issues/28594
