### ISSUE TITLE
Split cluster component in more parts due 3k lines

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#9267]
# Description

The cluster editor component ([rke2.vue](https://github.com/rancher/dashboard/blob/master/shell/edit/provisioning.cattle.io.cluster/rke2.vue)) reached 3k 🎉 
It's time to split the code and markup in parts as the complexity turns a 5 minutes change in days of work.

## Context

Currently we have all the tabs and sections of this view in one file. It would be probably more convenient to have separated files in a tree like:

```
rke2/
├─ index.vue
├─ MachinePools.vue
└─ Tabs
    ├─ Tab1.vue
    ├─ Tab2.vue
    └─ Tab3.vue
```

**Comment by richard-cox** [comment]
This touches upon a lot of functionality, we'll definitely need QA on this.

**Comment by cnotv** [comment]
> This touches upon a lot of functionality, we'll definitely need QA on this.
> 
> Update: Also would recommend we don't do this within the 2.7q3 timeline. There's a lot that could go wrong

Beside I agree with you, especially every time we touch code here something gets broken.
Could you be more specific about what do you foreseen and plan for the QA?

Theoretically the changes should be seamless and just have separated components.

**Comment by cnotv** [comment]
Personally I can see [this issue](https://github.com/rancher/dashboard/pull/9264#issuecomment-1621731362) as a perfect example of possible typical Vue parent-component communication issues to be covered, based on our uncommon architecture structure.

**Comment by cnotv** [comment]
@richard-cox Could you create an issue for the E2E parts you think we should test? It seems pretty much a core functionality of Rancher we want to get covered which hinders a very costly tech debt.

**Comment by richard-cox** [comment]
Created https://github.com/rancher/dashboard/issues/9431. At this stage it's probably just as important having automated tests for these features as refactoring the code. I'm not saying one blocks the other, but we should think about them the same time

**Comment by nwmac** [comment]
I'm closing this as done - Eva refactored it. Please re-open if there is more to do.

**Comment by cnotv** [comment]
We still have 2386 lines of code, so maybe we should abstract the logic? I guess we can create a new issue for this though, as this focusing on the tabs is already sufficient.

**Comment by cnotv** [comment]
Also thanks @eva-vashkevich , I forgot to do that properly 😢
