### ISSUE TITLE
Design Issues 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#927]
- [x] Hyperlinks on new table header doesn't have enough contrast in dark or light mode
- [x] Any way to make the header look less weird when we have the folder view? 

<img width="921" alt="Screen Shot 2020-07-31 at 3 10 54 PM" src="https://user-images.githubusercontent.com/11410997/89081500-3cd23c00-d340-11ea-8fa4-22c251b6935f.png">

- [x] Hovering over button - Text and button color are too similar

<img width="186" alt="Screen Shot 2020-07-31 at 3 14 28 PM" src="https://user-images.githubusercontent.com/11410997/89081636-989cc500-d340-11ea-81b7-67309ef3bc5b.png">

**New button Options**
- [x] Need more distinctive border/shadow around dropdown to have it standout. 

<img width="205" alt="Screen Shot 2020-07-30 at 6 45 38 AM" src="https://user-images.githubusercontent.com/11410997/88930982-18d40500-d231-11ea-88a2-66f7ace52841.png">

- [x] Make the notch bigger to make it more noticeable for the dropdown. 

<img width="205" alt="Screen Shot 2020-07-30 at 6 45 38 AM" src="https://user-images.githubusercontent.com/11410997/88930394-4b313280-d230-11ea-9069-6100dba99118.png">

- [x] The dropdown toggle icon doesn't match the other icons on the page. 

In the button:
<img width="296" alt="Screen Shot 2020-07-30 at 1 10 50 PM" src="https://user-images.githubusercontent.com/11410997/88969767-1fc93a80-d266-11ea-8062-9a649e3049fd.png">

In the layout or other dropdowns:

<img width="313" alt="Screen Shot 2020-07-30 at 1 11 23 PM" src="https://user-images.githubusercontent.com/11410997/88969827-38d1eb80-d266-11ea-9cb4-02a182733e1f.png">

- [x] In light mode, the border around the dropdown button is broken as it blends with the white background. It should be a darker blue or black or something to make it stick out.

Light mode example:

<img width="193" alt="Screen Shot 2020-07-30 at 9 58 34 AM" src="https://user-images.githubusercontent.com/11410997/88951818-5ba2d680-d24b-11ea-9bf7-740d7e4f6ea2.png">

Dark mode example:

<img width="257" alt="Screen Shot 2020-07-30 at 9 59 55 AM" src="https://user-images.githubusercontent.com/11410997/88951869-6fe6d380-d24b-11ea-8a35-c36ef2a6fe87.png">

**Nav Bar "Jump to.." Dropdown**
- [x] when exposing the dropdown, it needs to "pop" out more

<img width="206" alt="Screen Shot 2020-07-30 at 7 16 39 AM" src="https://user-images.githubusercontent.com/11410997/88933829-bd0b7b00-d234-11ea-8273-48f6f2c7b5ad.png">

**Button Styling**
- [x] Please pick a size, width, height, style that has some consistency across the page.

From the workloads:
<img width="239" alt="Screen Shot 2020-07-30 at 1 13 12 PM" src="https://user-images.githubusercontent.com/11410997/88969997-864e5880-d266-11ea-9b48-fd754ac30663.png">

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1025

**Comment by lvuch** [comment]
![image](https://user-images.githubusercontent.com/3013118/90174725-4b1a5200-dd5b-11ea-991a-5d5a52355779.png)
This is consistent with mocks showing a multi action button (create), a tertiary action button (add), and a secondary button (cancel)

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `d19f179c4`**

- Hyperlinks on table header look good
<img width="1435" alt="Screen Shot 2020-08-18 at 4 20 28 PM" src="https://user-images.githubusercontent.com/26032343/90575814-1ea67180-e171-11ea-9719-5ceaec1cafbe.png">
<img width="1436" alt="Screen Shot 2020-08-18 at 4 38 06 PM" src="https://user-images.githubusercontent.com/26032343/90575851-37168c00-e171-11ea-80fd-cad32ab079b5.png">

- Hovering over button - Text color is white now
<img width="676" alt="Screen Shot 2020-08-18 at 4 21 44 PM" src="https://user-images.githubusercontent.com/26032343/90576619-94abd800-e173-11ea-98a8-7648b087ec57.png">
<img width="778" alt="Screen Shot 2020-08-18 at 4 22 00 PM" src="https://user-images.githubusercontent.com/26032343/90576622-95dd0500-e173-11ea-9d96-63b62513ff37.png">

- distinctive border/shadow around dropdown and notch is bigger
<img width="340" alt="Screen Shot 2020-08-18 at 4 55 57 PM" src="https://user-images.githubusercontent.com/26032343/90576675-b6a55a80-e173-11ea-9fb5-3671797ec970.png">
<img width="418" alt="Screen Shot 2020-08-18 at 4 22 36 PM" src="https://user-images.githubusercontent.com/26032343/90576719-d177cf00-e173-11ea-8096-98f5b02bcc5a.png">

- Nav Bar "Jump to.." pops out
<img width="562" alt="Screen Shot 2020-08-18 at 4 34 17 PM" src="https://user-images.githubusercontent.com/26032343/90579703-b5782b80-e17b-11ea-8309-89296334eab8.png">


### Issues:
- The dropdown toggle icons do not match
<img width="400" alt="Screen Shot 2020-08-18 at 4 25 45 PM" src="https://user-images.githubusercontent.com/26032343/90579626-74801700-e17b-11ea-8d3d-cf21ac0e7852.png">

- Clicking on the dropdown button selects the whole button
<img width="295" alt="Screen Shot 2020-08-18 at 4 28 15 PM" src="https://user-images.githubusercontent.com/26032343/90579678-9e393e00-e17b-11ea-9979-5b6162c0620b.png">
<img width="284" alt="Screen Shot 2020-08-18 at 4 28 49 PM" src="https://user-images.githubusercontent.com/26032343/90579682-a1ccc500-e17b-11ea-8ff9-d140135ed382.png">

- Button Styling - "Add Port" button is different than the others in the create workload page. It can say "Add" like the other buttons and have the be of the same color
<img width="521" alt="Screen Shot 2020-08-18 at 4 35 01 PM" src="https://user-images.githubusercontent.com/26032343/90579721-c0cb5700-e17b-11ea-98e1-1a212d72faa9.png">

**Comment by lvuch** [comment]
https://github.com/rancher/dashboard/pull/1093
