### ISSUE TITLE
Initialisation of `ui-brand` setting fails

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9270]
**Setup**
- Rancher version: 2.7.q3 pre-release
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
- Green branding should be applied when the rancher-csp-adapter app is installed (https://github.com/rancher/csp-adapter)
- Branding is applied to a setting ui-branding
- In the initial case when ui-branding has not been set it won't ever get set, regardless of app found

**To Reproduce**
- Ensure /v3/settings/ui-brand does not exist
- Hack in an install of csp-adpater chart
  - From a shell env in the local cluster
    ```
    helm repo add rancher-charts https://charts.rancher.io
    helm install rancher-csp-adapter rancher-charts/rancher-csp-adapter --set aws.enabled=true --set aws.accountNumber=1234 --set aws.roleName=abc
    ```

**Result**
- Once the app is installed the branding will remain blue, even over refresh
**Expected Result**
- The branding should turn green

**Screenshots**

**Additional context**
- Uninstalling the app should return the branding back to blue
- Installing the app again will not result in green branding (expected)
- Deleting the ui-brand setting can be done via /v3/settings/ui-brand

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 95f0b50
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
Tested this issue with the following steps:
1. Ensure /v3/settings/ui-brand does not exist
2. Hack in an install of csp-adpater chart
```
From a shell env in the local cluster
 helm repo add rancher-charts https://charts.rancher.io helm install rancher-csp-adapter rancher-charts/rancher-csp-adapter --set aws.enabled=true --set aws.accountNumber=1234 --set aws.roleName=abc 
```
3. Verify the branding turns green

**Result**
After making installing the csp-adapter chart, the branding color changed to green

![image.png](https://zube.io/files/rancher/83a0b8ec743f60b1f5f90f54f44f2af6-image.png)
