### ISSUE TITLE
Migrate from Ember to Vue: Cluster & Node Drivers page

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9274]
Stemming from a bug found in https://github.com/rancher/dashboard/issues/8650 for activating cluster & node drivers, we should move this page to Vue since it's in Ember.

Before working here, let's make sure the rest of Drivers isn't also in Ember; new tickets can be filed for those pages. Otherwise, after porting, let's make sure the bug is fixed too.

**Comment by gaktive** [comment]
Epic: https://github.com/rancher/dashboard/issues/8718 since that's the ticket tracking all our pages to move off Ember.

**Comment by richard-cox** [comment]
Linked related issue - https://github.com/rancher/dashboard/issues/9183

**Comment by yonasberhe23** [comment]
I think this needs to be tested manually. found a few issues so far

**Comment by yonasberhe23** [comment]
I've added more e2e tests coverage https://github.com/rancher/dashboard/pull/11066 so this no longer needs manual validation. moving to done
