### ISSUE TITLE
Assets `urls` property for extensions being overwritten in index.yaml during build

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#9277]
**Setup**
- Rancher version: v2.7.5
- Rancher UI Extensions: N/A

**Describe the bug**

During a github build of an extension, the `urls` property within the `index.yaml` is being overwritten ([example](https://github.com/kubewarden/ui/blob/85a87b10997164b42f6d2898b77b3a9b12265686/index.yaml#L21-L22)) in the script [here](https://github.com/rancher/dashboard/blob/90377f035ebdf0da35563cc7692ab2d89d6e2b92/shell/scripts/extension/publish#L302-L309) - This property defines the location of the extension assets which the chart uses during the installation process.

**Expected Result**

The url for an extension should be a path with the `assets` directory prefixed to the location. For instance:
```yaml
    urls:
    - assets/kubewarden/kubewarden-1.1.0-rc1.tgz
```

**Additional context**

The existence of these commands is necessary for container builds, so adding additional conditions which prevent the overwriting of this file based whether  `GITHUB_BUILD` is false and if the `ROOT_INDEX` does not exist should suffice.

**Comment by slickwarren** [comment]
since this is QA/None, closing this issue.

**Comment by gaktive** [comment]
For historical purposes, this looks to have shipped in 2.7.6 since the .x milestone typically means unscheduled.
