### ISSUE TITLE
Downloading or editing secret resource as yaml, the data is missing the type attribute

### ISSUE THREAD

**Issue by ly5156** [rancher/dashboard#9280]
**Setup**
- Rancher version: v2.7.5...v2.8.0
- Browser type & version:  Chrome 114.0.5735.198 arm64

**Describe the bug**

Downloading or editing secret resource as yaml, the data is missing the type attribute

**To Reproduce**

1. Create a secret of type Opaque or other type
2. `Download Yaml` or `Edit Yaml`

<img width="884" alt="image" src="https://github.com/rancher/dashboard/assets/3406205/e775807f-7e6d-4c3b-bd8e-aeabfc19cc95">
<img width="882" alt="image" src="https://github.com/rancher/dashboard/assets/3406205/00535791-5aa5-4609-ad14-586e13cdc1ab">

**Result**

1. You will see that the type attribute is missing from the yaml data
2. If I want to execute the apply command using the secret yaml on the UI, it will fail if the type is not Opaque

**Expected Result**

The yaml data should contain the type attribute
Refer to the documentation:
https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/

https://kubernetes.io/docs/concepts/configuration/secret/#secret-types

**Comment by izaac** [comment]
The Unit test validates the type is added in the Yaml as described in the issue. LGTM cc @yonasberhe23
