### ISSUE TITLE
Add SortableTable to Storybook

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#9285]
# Description

As major usage case of this element, add ~table in one of its own wrappers (`ResourceTable` or `SortableTable`)~ `SortableTable` to Storybook and display the different features.

List, to be updated:
- Styles and sections
  - Default view
  - Grouped
  - Simplified
  - Progressive loading
  - Messages and errors
  - Slots
  - Expandable
  - Extra row
- Functionalities
  - Search
  - Advanced filtering
  - Sorting
  - Action menu
  - Row/All selection and total counter (table actions)
  - Context menu
  - Pagination
  - ~Buttons~
    - ~Refresh~
    - ~Download~
    - ~Delete~
  - Shortcuts
  - Tooltips 
- Slots
  - loading	
  - title	
  - header-left	
  - header-middle	
  - header-right	
  - header-button	
  - no-rows	
  - no-results	
  - group-row	
  - group-by	
  - main-row	
  - 'main-row:' + (row.row.mainRowKey || i)	
  - 'col:' + col.col.name	
  - 'cell:' + col.col.name	
  - row-actions	
  - sub-row	
  - shortkeys

EDIT: Buttons are part of a wrapper called `ResourceTable`, so we'll handle this separately as it's not part of the design of the table itself.

![Screenshot 2023-07-07 at 11 27 06](https://github.com/rancher/dashboard/assets/5009481/8304386e-f6c3-46af-bda4-55bdf0181c41)

![image](https://github.com/rancher/dashboard/assets/5009481/74e01fce-f4b3-4966-89ef-672e576c5105)

![image](https://github.com/rancher/dashboard/assets/5009481/00fc2042-258d-4857-961c-ed52af15e244)

![image](https://github.com/rancher/dashboard/assets/5009481/d0a473db-35c0-4783-8365-911fb0915c1d)

**Comment by kwwii** [comment]
@manuelecarlini started a confluence page to capture use-cases and details about how we use tables.

**Comment by richard-cox** [comment]
Our tables tie in to product config, models, stores, etc

We should consider some existing docs as well
- https://rancher.github.io/dashboard/code-base-works/sortable-table
- https://rancher.github.io/dashboard/code-base-works/kubernetes-resources-data-load
- https://rancher.github.io/dashboard/code-base-works/customising-how-k8s-resources-are-presented#list

**Comment by cnotv** [comment]
> Our tables tie in to product config, models, stores, etc
> 
> We should consider some existing docs as well
> 
> * https://rancher.github.io/dashboard/code-base-works/sortable-table
> * https://rancher.github.io/dashboard/code-base-works/kubernetes-resources-data-load
> * https://rancher.github.io/dashboard/code-base-works/customising-how-k8s-resources-are-presented#list

Please mind that this is aimed as style guide for visual usage case and not as code documentation. For that case we can redirect to the links you provided, which I will add inside the style guide as completition.
