### ISSUE TITLE
Convert extension actions to support reusable workflows

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#9290]
**Is your feature request related to a problem? Please describe.**

The workflow files that are generated for extensions (found [here](https://github.com/rancher/dashboard/tree/master/shell/creators/pkg/files/.github/workflows)) should be migrated and converted into reusable workflows.

There is a gap between updating an extension's `@rancher/shell` package and updating the workflows that they utilize to build and publish the extension packages.

**Describe the solution you'd like**

The process of updating the workflows and scripts which they target could benefit from using [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows).
This would allow us to update any workflow actions/scripts independently and remove the required intervention of the extension developer to make manual updates to their extension workflow files.

**Comment by ronhorton** [comment]
QA=none

closing
