### ISSUE TITLE
Improve fatal error page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9292]
**Is your feature request related to a problem? Please describe.**
- we show a default fatal error page that was previously from nuxt `shell/layouts/error.vue`
- we could make this respect light / dark mode and improve how it looks. possibly inline with our non-fatal error page?
  - not sure we can show the header bar with burger menu and user avatar though

**Additional context**

![image](https://github.com/rancher/dashboard/assets/18697775/e0ba44c2-4dd8-46ef-b1bc-e8d7f2df758c)

![image](https://github.com/rancher/dashboard/assets/18697775/3f24dc03-ce0f-4943-aaff-127c2af2235d)

**Comment by nwmac** [comment]
@richard-cox Is this relevant - "fatal errors" are swallowed in production build

**Comment by richard-cox** [comment]
Ah yes, this was pre-discovery. Closing, error page is only seen when running in dev
