### ISSUE TITLE
User is allowed to choose clusters that he does not have access to from the cluster dropdown list.

### ISSUE THREAD

**Issue by sangeethah** [rancher/dashboard#930]
Rancher server version - master-3370-head

Steps to reproduce the problem:
Log in to Dashboard UI as a standard user who does not have access to local cluster.

<img width="1360" alt="Screen Shot 2020-07-30 at 6 42 37 PM" src="https://user-images.githubusercontent.com/4266958/88991256-15726500-d295-11ea-9288-cd34e65e37f3.png">

**Comment by deniseschannon** [comment]
@sangeethah not seeing this in master-head today.

**Comment by sangeethah** [comment]
This issue is not seen anymore when testing with latest master.
