### ISSUE TITLE
Create and view modes are missing from LocationConfig (only missing create...)

### ISSUE THREAD

**Issue by berkitamas** [rancher/dashboard#9302]
**Setup**
- Rancher version: v2.7.3
- Rancher UI Extensions: N/A

**Describe the bug**
Create and view modes are missing from the LocationConfig as described here in the table: https://rancher.github.io/dashboard/extensions/api/common#locationconfig

**To Reproduce**
Create a very simple panel with the mode "create" or "view":
```TypeScript
plugin.addPanel(
  PanelLocation.DETAILS_MASTHEAD,
  { resource: ['provisioning.cattle.io.cluster'], mode: [ 'create' ] },
  { component: () => import('./components/ExampleComponent.vue') }
);
```
components/ExampleComponent.vue
```HTML
<template>
  <div>
    hello world!
  </div>
</template>
```

**Result**
No changes on this page: https://rancher.example.com/c/_/manager/provisioning.cattle.io.cluster/create

**Expected Result**
A hello world! message would be visible in this page: https://rancher.example.com/c/_/manager/provisioning.cattle.io.cluster/create

**Comment by richard-cox** [comment]
Tamás and I discussed this in slack. We should cater for both the create and view options that `mode` can be.

**Comment by aalves08** [comment]
Found a couple of issues where location for `detail` where it was being "duplicated" into `edit` and `config`. Also, we are missing the `create` mode. With these, we will have all of the areas covered.

quick mapping reference:
- `detail` -> detail view
- `config` -> config view (same view as edit, but with fields non-editable)|
- `edit` -> edit view
- `list` -> list view
- `create` -> create view
