### ISSUE TITLE
TableColumn Extensions documentation is misleading

### ISSUE THREAD

**Issue by berkitamas** [rancher/dashboard#9303]
**Setup**
- Rancher version: v2.7.3

**Describe the bug**
[This](https://rancher.github.io/dashboard/extensions/api/table-columns#tablecolumnlocationresource-options) page has a screenshot about the position of the TableColumn extensions. The screenshot also says "New table columns will be added to the end of the table (before inline actions)" and indicates with a double line the position of the new column. 
This is not the position the column will appear. According to this function https://github.com/rancher/dashboard/blob/master/shell/store/type-map.js#L236 the column will be inserted before the "Age" column (if Age is the last column). 

**To Reproduce**
Create a simple TableColumn:
```TypeScript
plugin.addTableColumn(
  TableColumnLocation.RESOURCE,
  { resource: ['pod'], mode: ['list'] },
  {
    name:          'cluster-location',
    label:         'hello',
    getValue: (row: any) => {
      return `${ row.id }-DEMO-COL-STRING-ADDED!`;
    },
    width:         100,
    sort:          ['stateSort', 'nameSort'],
    search:        ['stateSort', 'nameSort']
  }
);
```

**Result**
The column will appear before the "Age" column.

**Expected Result**
According to the documentation the "Age" column does not have any influence to the position of the table columns.

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/6505186/70e50da2-948d-4574-9819-dee8cc8a4895)

**Additional context**
In my opinion, hardcoding the Age column is not a good idea. There are cases where there are action buttons after the Age, for example the Cluster management view (.../dashboard/c/_/manager/provisioning.cattle.io.cluster) with the "Explore" button (which is a column on its own without any ID or header name).

**Comment by aalves08** [comment]
Fixed with https://github.com/rancher/dashboard/pull/9186
