### ISSUE TITLE
Duplicate request to v1 settings on page load

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9304]
**Setup**
- Rancher version: v2.7.4 ish

**Describe the bug**
- Two requests are made to fetch v1 mgmt settings. one `setting` and another `settings`
- ![image](https://github.com/rancher/dashboard/assets/18697775/75b9dd61-b368-4af9-b296-efc7fcc31cd7)

**To Reproduce**
- Refresh on any page

**Result**
- Two requests instead of one

**Expected Result**
- One request to `...settings`

**Additional context**
- mgmt schema `links.collection` url reports `...settings`
- mgmt settings `links.self` reports  `...settings
- mgmt setting `links.self` reports  `...setting

**Comment by richard-cox** [comment]
To confirm if this is one `get` and one `post`

**Comment by izaac** [comment]
The e2e test coverage and api interceptions look good to cover the validation of these multiple calls fix. That wait seems necessary too. @yonasberhe23
