### ISSUE TITLE
Azure Cloud Credentials doesn't pass Environment  

### ISSUE THREAD

**Issue by mjura** [rancher/dashboard#9311]
**Setup**
- Rancher version: v.2.7.5
- Rancher UI Extensions: 
- Browser type & version:

**Describe the bug**
It is followup from https://github.com/rancher/aks-operator/issues/98

It seems that during Cloud Credentials creation process for Azure, name of Environment is not passed to /meta/aksCheckCredentials
https://github.com/rancher/dashboard/blob/master/shell/cloud-credential/azure.vue#L47

**To Reproduce**
Create Azure Cloud Credentials other than default AzurePublicCloud

**Result**
https://github.com/rancher/aks-operator/issues/98#issuecomment-1591127149

**Expected Result**
Cloud Credential will be validated and create

**Screenshots**

![245795993-cc2cac34-7986-41e7-887a-340393867fd3.png](https://zube.io/files/rancher/81aae76321ccbd888d55ee99e0121470-245795993-cc2cac34-7986-41e7-887a-340393867fd3.png)

**Additional context**

**Comment by aalves08** [comment]
Will close this issue as it's unit tested @gaktive

**Comment by cnotv** [comment]
Dev automation for this issue is present and therefore we set it to done @yonasberhe23
