### ISSUE TITLE
ServerMiddleware array not used in the Vue config.

### ISSUE THREAD

**Issue by bisht-richa** [rancher/dashboard#9312]
**Setup**
- Rancher version: v2.7.5 dev
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

It is a follow-up from [Unable to use Auth Providers when running locally
](https://github.com/rancher/dashboard/issues/9138)

There's no clear way forward to address that now defunct old method using the serverMiddleware array (specifically the other parts that don't work in post nuxt world). which needs to be fixed.

**Note:** It might be worth converting what's in there to be compatible with app.use().

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by nwmac** [comment]
Stale
