### ISSUE TITLE
FileDiff component display problem

### ISSUE THREAD

**Issue by TIEDPAG** [rancher/dashboard#9313]
**Setup**
- Rancher version: v2.6.13
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
When we upgraded from rancher 2.6.8 to 2.6.13, we found that there was a problem with the diff function of the yaml editor, as shown below

**To Reproduce**
Edit any resource using yaml

**Result**
<img width="1127" alt="image" src="https://github.com/rancher/dashboard/assets/24646612/d90d1ee3-2416-444d-92f3-49037852a37a">

**Expected Result**
<img width="1028" alt="image" src="https://github.com/rancher/dashboard/assets/24646612/4329241f-ee31-4d28-b655-c0bcd208a6d1">

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment]
@TIEDPAG Can your provide details from the issue template, specifically what browser you're using and clear steps to reproduce?

**Comment by richard-cox** [comment]
I've managed to reproduce this. Seems like an issue with the older component we use to display diff

**Comment by Priyashetty17** [comment]
Recreated the issue with 2.6.13. Validated with v2.7-head 

Component | Version
-- | --
Rancher | v2.7-027246f77f03b82660dc2e91df6bf2cd549163f0-head
Dashboard | master "2f64abbdd"

![fileDiff_AfterFix1](https://github.com/rancher/dashboard/assets/42880103/51a00b6e-a13e-41d1-b325-512b4c081441)

![fileDiff_AfterFix2](https://github.com/rancher/dashboard/assets/42880103/49406c91-80f6-423c-8d71-5636489f8cdc)
