### ISSUE TITLE
Add the ability to customize chart annotations for extensions

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#9318]
**Is your feature request related to a problem? Please describe.**

It would be nice to have the ability to update the annotations which are set for an Extension's chart, for instance the `catalog.cattle.io/kube-version` and `catalog.cattle.io/rancher-version` annotations.

In order to update these annotations for an Extension, the Chart.yaml needs to be updated manually, then the assets and index.yaml need to be rebuilt in order to contain the new annotations. It would be better to have an option within the `yarn publish-pkgs` script that would allow the user to determine the values for the `kube-version` and `rancher-version` annotations.

**Describe the solution you'd like**

Add options to the `yarn publish-pkgs` script to allow updating the annotations. For instance:
```sh
yarn publish-pkgs --kube-version ">= 1.16.0-0 < 1.22.0-0" --rancher-version ">= 2.7.2-0 < 2.8.0-0"
```

**Describe alternatives you've considered**

Perhaps instead of adding options to the script, it would be possible to define a set of options within a manifest like `rancher-config.yml` at the root of the extension which could apply these annotations automatically to each package that would be built as a result of running the `publish-pkgs` script.

**Comment by nwmac** [comment]
Add to package file

**Comment by ronhorton** [comment]
@samjustus @nwmac does this require QA?

**Comment by ronhorton** [comment]
closing - no qa required
