### ISSUE TITLE
Deployment workflow should resize better at smaller screen widths

### ISSUE THREAD

**Issue by sangeethah** [rancher/dashboard#932]
Rancher Server version - `master-3375-head`

Few pages where truncations in fields were observed when following the Deployment workflow to create a workload.

In all pages that have "Next" navigation:
<img width="175" alt="Screen Shot 2020-07-30 at 2 40 49 PM" src="https://user-images.githubusercontent.com/4266958/88980692-1bf2e380-d279-11ea-9cb8-700a037b2460.png">

In Step 4 : Resources tab
<img width="919" alt="Screen Shot 2020-07-30 at 1 47 19 PM" src="https://user-images.githubusercontent.com/4266958/88980694-1c8b7a00-d279-11ea-9937-3632b8c92e79.png">

In Step 4 : Pod Scheduling:

<img width="549" alt="Screen Shot 2020-07-30 at 1 45 41 PM" src="https://user-images.githubusercontent.com/4266958/88980697-1dbca700-d279-11ea-88cb-e7c0c933c832.png">

<img width="763" alt="Screen Shot 2020-07-30 at 3 34 42 PM" src="https://user-images.githubusercontent.com/4266958/88981363-9bcd7d80-d27a-11ea-9437-e5aeaec38bbd.png">

**Comment by sowmyav27** [comment]
This issue is NOT seen in the same setup in my laptop/browser.

**Comment by gaktive** [comment]
Maybe the easiest solution would be to set a minimum horizontal width. Would need some design work.

**Comment by kwwii** [comment]
We should set the minimum size to that of a tablet and ensure that this fixes the problem. Supporting smaller sizes do not need to be taken into account

**Comment by gaktive** [comment]
Closing in light of the newer ticket as the reported ticket is super old and changes have been made since.
