### ISSUE TITLE
Inactivity Modal disconnects sockets whilst `Resume` button is visible 

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9325]
**Setup**
- Rancher version: 2.7.5

**Describe the bug**
- Looks like multiple copies of the inactivity check can run at the same time
- This can cause the model to show in a bad state
  - The sockets will disconnect after the correct amount of time, however...
  - The timeout indicator does not move
  - The `Resume` button remains visible, which if clicked makes the user think sockets are still connected

 **To Reproduce**
- Enable Inactivity modal, set the timeout to 1 minute
- Go to a Cluster Explorer context
- Refresh
- Click on the burger menu --> `Extensions` --> immediately after click to nav wiggle the cursor around for a second
- Move the cursor outside of the browser (there's a different behaviour if it's in the browser)
- Wait 1 minute
- Inactivity modal is shown with a timeout indicator not moving and resume always visible
  -  It might change after a while, but still after the sockets have disconnected

**Result**
- User can click on `Resume` but sockets already disconnected

**Expected Result**
- User is presented with a status indicator that reaches zero and `Resume` button is removed

**Additional context**
- It's important to wiggle the cursor when navigating to the extension page
- The issue seems a lot worse when the timeout is 5 minutes
- To debug i've been printing `console.debug(``checkInactivityTimer: ${ endTime }``);` in `_trackInactivity` --> `checkInactivityTimer`. When the bug happens every second there's two log lines quoting a different endTime. This shouldn't be possible. I don't think it's an issue with the start / stop generally on navigation, maybe a race condition between `this.clearAllTimeouts()` and `checkInactivityTimer()`?

**Comment by nickwsuse** [comment]
`Verified on v2.7-head ID: 4dc8b18`

I set the timeout to 1min and checked the inactivity modal on several different pages of Rancher, with and without the cursor on screen, and the button changes to `Refresh` once the countdown is done as expected. I also tried a few pages, with and without the cursor on screen, with a 5min timer and a 10min timer and they both worked as expected.
