### ISSUE TITLE
Standardize Node Versions used in Github Actions

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#9334]
Our GitHub actions currently employ different versions of Node.js in various workflows, this can lead to inconsistencies and potential incompatibility issues. For instance, the recent issue encountered with `replaceAll` usage in #9309[^1] highlights the challenges posed by varying Node.js versions. Accommodating different versions can be confusing and potentially time consuming to troubleshoot and debug. 

Node.js versions in use:

- check-plugins.yaml: 14.x
- docusaurus.yaml: 16.x
- ~pr-zube.yaml: 14.x~
- rancher-components.yaml: 14.x
- release-rancher-components.yml: 16.x
- ~release-rancher-desktop.yml: 12.x~
- storybook.yaml: 16.x
- test.yaml: 14.x
- ~build-container.yml: 16.x~
- build-extension.yml: 16.x

## Proposed Solution

Evaluate Node.js versions used in all of our workflows and see if they can be updated to support the latest, stable version of Node.js.

[^1]: https://github.com/rancher/dashboard/pull/9309#discussion_r1263141912

**Comment by gaktive** [comment]
Some work may have been done in https://github.com/rancher/dashboard/pull/11302 already per @cnotv 

Since this ticket was first written, Zube has been removed and Rancher Desktop has had its UI need deprioritized. We'll keep reference to them here but they're crossed out.

**Comment by rak-phillip** [comment]
If we use `actions/setup-node@v4`, we can utilize the `node-version-file` option to read our desired node version from `package.json`[^1]. This might be a good approach for reducing the number of times that we need to specify the node version throughout the project. 

[^1]: https://github.com/actions/setup-node?tab=readme-ov-file#usage

```
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: yarn
```

**Comment by cnotv** [comment]
> Some work may have been done in #11302 already per @cnotv

There's a migration script already available for:
- Update node version in the workflow/action: https://github.com/rancher/dashboard/blob/master/shell/scripts/vue-migrate.js#L228-L258
- Update `package.json` node engine: https://github.com/rancher/dashboard/blob/master/shell/scripts/vue-migrate.js#L159
The script does not have an option to flag updates required.

@rak-phillip solution is more convenient and consistent, still mind all the `package.json` to be updated, including creator and so on.
