### ISSUE TITLE
"Create" buttons should be disabled when required fields are not filled on Navlinks page

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#9348]
**Setup**
- Rancher version: v2.7.5-rc5
- Browser type & version: Chrome 14.0.5735.198

**Describe the bug**
"Create" button should be disabled when required fields are empty

**To Reproduce**
Path: /c/local/explorer/ui.cattle.io.navlink/create#group
How to reach:
Search for resource navlink
Create new resource
Leave all fields empty

**Result**
"Create" button is enabled

**Expected Result**
"Create" button should be disabled

**Comment by valaparthvi** [comment]
I can confirm that the issue has been fixed in v2.7-head.
![Screenshot from 2023-08-28 13-33-47](https://github.com/rancher/dashboard/assets/11015077/0103f6d8-96cd-4946-8c1d-1c6437bc18c5)

**Comment by valaparthvi** [comment]
Closing the issue since it's been fixed.
/close

**Comment by yonasberhe23** [comment]
unit tests seem sufficient to me. Moving to done @izaac
