### ISSUE TITLE
Throw an error if not all e2e tests are run

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#9350]
If tests don't have tags defined, they aren't run in CI - we should try to catch this before merging PRs with tests that effectively never run, eg https://github.com/rancher/dashboard/pull/9338/commits/b404f70d071d9ffeaf0d73ed6d76ed7ac53785a5

**Comment by richard-cox** [comment]
We should also consider running tests with no tags as all tags

**Comment by cnotv** [comment]
@mantis-toboggan-md what do you mean with "tags defined"?

**Comment by mantis-toboggan-md** [comment]
@cnotv I mean that a test (or test block) needs grep tags set https://rancher.github.io/dashboard/testing/e2e-test#cypress-tags-cypress-grep-plugin
