### ISSUE TITLE
Admin user unable to view AlertmanagerConfigs after installing Monitoring

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#9352]
**Setup**
- Rancher version: v2.7-head (58aede6)
- Rancher UI Extensions: NA
- Browser type & version: Firefox 116.0b5 (64-bit)

**Describe the bug**

An error is displayed when an admin user attempts to view the AlertmanagerConfigs after installing Monitoring: `Error Resource type monitoring.coreos.com.alertmanagerconfig not found` 

**To Reproduce**

1. Install a new downstream RKE2 cluster in digital ocean
   1. Navigate to Cluster Management and click on Create
   2. Make sure that RKE2/K3s is selected and select DigitalOcean
   3. Provide a name for the cluster use 8GB/4vCPU for the cluster size
   4. Leave the remaining fields as default
   5. Click create
   6. Wait for cluster to enter a ready state
2. Install Monitoring on the new downstream cluster
   1. Navigate to Explore Cluster => { name-of-cluster }
   2. Click on Cluster Tools
   3. Click on Monitoring => Install
   4. We can choose to keep Install into Project as "(None)", or select Default or System. (The behavior should stay the same)
   5. Click Next, leave all defaults, and click Install
   6. Wait for Monitoring install to complete
3. Select Monitoring => Alerting => AlertmanagerConfigs

**Result**

> Error: Resource type monitoring.coreos.com.alertmanagerconfig not found 

![image](https://github.com/rancher/dashboard/assets/835961/f80f2494-3bff-4493-abe4-b1d47e8d20d0)

**Expected Result**

AlertmanagerConfigs or a prompt to create a new config is displayed 

![image](https://github.com/rancher/dashboard/assets/835961/726bad68-be63-47b8-9d74-e042b0212057)

**Additional context**

There are two other potential issues that I encounter in this process. I can open up more issues if this behavior is unrelated to the issue described above. 

Additional Issue 1: Requires a refresh or navigating away from the cluster for the Monitoring menu item to appear

Additional Issue 2: Project Monitors does not display under the Monitoring menu item

**Comment by gaktive** [comment]
Some overlap with https://github.com/rancher/dashboard/pull/9338#discussion_r1265640833 though the users are different.

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: 1955476`

I don't have access to Digital Ocean so I did this with AWS instead, but either way the AlertManagerConfigs is viewable as the admin now for both RKE1 and RKE2 clusters.
