### ISSUE TITLE
[BUG] Fail Whale Error When Accessing CIS Chart on Downstream Clusters 

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/dashboard#9354]
**Rancher Server Setup**
- Rancher version: v2.7-58aede67b99fd5002cc44c2b36583834595acad2-head
- Installation option (Docker install/Helm Chart): Helm Chart
- Browser type & version: Chrome/Firefox

**Information about the Cluster**
- Kubernetes version: v1.25.11
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Node driver provisioned clusters

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
When the CIS chart is not installed on the local cluster in Rancher, accessing the CIS chart on downstream clusters in the Rancher UI results in a fail whale error.

**Steps to Recreate:**
1. Create a Rancher server v2.7-head.
2. Create a downstream cluster.
3. Verify that the CIS chart is not installed on the local cluster.
4. Install the "rancher-cis-benchmark" on the downstream cluster. Verify chart "rancher-cis-benchmark" is installed on the cluster successfully. 
5. In the UI, navigate to the downstream cluster's explorer -> CIS Benchmark. 

**Issue:**
- Fail whale error is displayed when CIS chart is accessed on the downstream cluster. 

**Expected Result:**
The Rancher UI should allow users to access the CIS chart on downstream clusters, regardless of whether the CIS chart is installed on the local cluster. The CIS chart resources should be rendered without any fail whale errors.

**Workaround:**
- Install the CIS chart on the local cluster as a workaround when accessing the CIS chart on downstream clusters in the Rancher UI.

**Note:**
- This issue is not observed on the downstream cluster when the CIS chart is deployed on the local cluster.
- This issue was not observed with v2.7.5.
- Frequency: Seen Always
- Did not see any issues while accessing the following APIs directly:
   - https://cluster/k8s/clusters/c-m-9bvxtzgl/v1/cis.cattle.io.clusterscans
   - https://cluster/k8s/clusters/c-m-9bvxtzgl/v1/cis.cattle.io.clusterscanbenchmarks
   - https://cluster/k8s/clusters/c-m-9bvxtzgl/v1/cis.cattle.io.clusterscanprofiles
   - https://cluster/k8s/clusters/c-m-9bvxtzgl/v1/cis.cattle.io.clusterscanreports
-  CRDs on the downstream cluster at the time of failure:
```
clusterscanbenchmarks.cis.cattle.io                               2023-07-17T15:51:10Z
clusterscanprofiles.cis.cattle.io                                 2023-07-17T15:51:10Z
clusterscanreports.cis.cattle.io                                  2023-07-17T15:51:10Z
clusterscans.cis.cattle.io                                        2023-07-17T15:51:10Z
```

**Screenshots**
![failWhale](https://github.com/rancher/dashboard/assets/42880103/1b4c8b74-ad4e-45fc-ad60-e3513ee3931e)

Log from developer console:
```
Loading original error Error: Resource type cis.cattle.io.clusterscan not found
    at authenticated.js:440:38
    at p (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
```

**Comment by richard-cox** [comment]
This should be resolved by https://github.com/rancher/dashboard/issues/9336 (a fix has been merged today)

**Comment by richard-cox** [comment]
Resolved via https://github.com/rancher/dashboard/pull/9338 (same root issue as https://github.com/rancher/dashboard/issues/9336)

**Comment by richard-cox** [comment]
Note for QA. All three of these should be tested together
- https://github.com/rancher/dashboard/issues/9336
- https://github.com/rancher/dashboard/issues/9352
- https://github.com/rancher/dashboard/issues/9354

**Comment by Priyashetty17** [comment]
Verified ✅ 

| Component| Version | 
|----------|----------|
| Rancher   | v2.7-95f0b50ddf387c0d98a211f0217b34207348502d-head | 
| Dashboard   | master f9a954a26 |
