### ISSUE TITLE
Add AsyncButton to Storybook

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#9358]
# Description

One of the most important elements of our UI Kit is missing from the style guide: the button, aka `AsyncButton`.

States, cases and functionalities TBD.

**Comment by cnotv** [comment]
As a normal button is actually missing in our repository, we should consider to add one: https://github.com/rancher/dashboard/issues/9398

**Comment by gaktive** [comment]
We need some additional work to land first before working on this.

**Comment by cnotv** [comment]
A PR has been already created with a video preview, although the style may not be what we want:

https://github.com/rancher/dashboard/pull/9399#issuecomment-1678599201
