### ISSUE TITLE
workload - cannot set node scheduling when creating deployment 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#936]
rancher:`master-3375-head`

Steps:
- set the node scheduling when creating a deployment for the dashboard 
 
Couple issues here:
1. there is no node showing in the list when choosing `run pods on specific node(s)`
<img width="750" alt="Screen Shot 2020-07-30 at 5 49 41 PM" src="https://user-images.githubusercontent.com/6218999/88988422-bb21d600-d28d-11ea-92e8-eb007297c73b.png">

2. there is no option for operators when choosing `run pods on nodes matching those scheduling rules`
 
<img width="655" alt="Screen Shot 2020-07-30 at 5 51 14 PM" src="https://user-images.githubusercontent.com/6218999/88988466-dab8fe80-d28d-11ea-83f3-e824868558c3.png">

3. UI shows  the error message if trying  to create the deployment 
`Deployment.apps "jiaqi-test" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator: Invalid value: "": not a valid selector operator
`
<img width="1132" alt="Screen Shot 2020-07-30 at 5 51 53 PM" src="https://user-images.githubusercontent.com/6218999/88988498-ec020b00-d28d-11ea-820d-2f04b14a26ce.png">

**Comment by jiaqiluo** [comment]
on rancher `master-5e1b21b931ac58ba0aa3f89c827a0f65dd42051b-head` 


Issue 1 is fixed.

we can set the node scheduling when creating a deployment for the dashboard
<img width="1064" alt="Screen Shot 2020-08-27 at 1 27 33 PM" src="https://user-images.githubusercontent.com/6218999/91491872-90fe0c80-e869-11ea-8418-afe6c3e70052.png">

**Comment by jiaqiluo** [comment]
on rancher `master-5e1b21b931ac58ba0aa3f89c827a0f65dd42051b-head`

Issue 2 is fixed.

<img width="1321" alt="Screen Shot 2020-08-27 at 1 34 55 PM" src="https://user-images.githubusercontent.com/6218999/91492630-d111bf00-e86a-11ea-849b-a68b70e62731.png">

**Comment by jiaqiluo** [comment]
on rancher `master-5e1b21b931ac58ba0aa3f89c827a0f65dd42051b-head`

issue 3 still exists.

<img width="1638" alt="Screen Shot 2020-08-27 at 1 36 07 PM" src="https://user-images.githubusercontent.com/6218999/91492679-e4248f00-e86a-11ea-8e0d-5641801add4f.png">

`
{"type":"error","links":{},"code":"BadRequest","message":"Deployment in version \"v1\" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Affinity: v1.Affinity.NodeAffinity: v1.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution: v1.NodeSelector.NodeSelectorTerms: []v1.NodeSelectorTerm: v1.NodeSelectorTerm.MatchExpressions: []v1.NodeSelectorRequirement: v1.NodeSelectorRequirement.Operator: ReadString: expects \" or n, but found {, error found in #10 byte of ...|perator\":{\"label\":\"=|..., bigger context ...|ons\":[{\"key\":\"kubernetes.io/hostname\",\"operator\":{\"label\":\"=\",\"value\":\"In\"},\"values\":[\"13.58.170.205|...","status":400,"type":"error"}
`

**Comment by deniseschannon** [comment]
@mantis-toboggan-md Here are the requirements for validation of this: 


Field | Description
-- | --
keystring | The label key that the selector applies to.
operatorstring | Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
valuesstring array | An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.

**Comment by mantis-toboggan-md** [comment]
I'm not seeing this issue anymore, it appears to have been fixed inadvertently a few weeks with this commit https://github.com/rancher/dashboard/commit/565520c47afb42fe2c27c9bd0cddabb4bc73fc4c

**Comment by jiaqiluo** [comment]
This bug fix is validated in rancher-master ec04f78

The node scheduling part works as expected.
