### ISSUE TITLE
Incorrect number of active pods is getting displayed for downstream cluster on Rancher UI welcome page

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9363]
Internal reference: SURE-6653
Reported in 2.7.5

We addressed a prior issue of the pod count in https://github.com/rancher/dashboard/issues/8543 but we have a similar issue with active pods in the welcome page.

Troubleshooting steps:
Find out the total number of non-terminated pods in each node using below command and take the count of the pods from worker nodes only

Repro steps:
- Create an Rancher on RKE2 cluster
- Create a downstream cluster with 3 (or less) master nodes and 4 (or less) worker nodes
- Check total number of pods exist on the cluster(including the pods in "completed" status.

Actual behavior:
Displays <total number of pods in the cluster>/<total number of pods allowed in the worker nodes>

Expected behavior:
Calculate pods capacity for downstream clusters based on non-terminated pods running on the workers nodes only

Additional notes:
Attached screenshot shows 50/440, but it should show 15/440  (as shown in the 2nd screenshot taken of Cluster Dashboard) 

![Rancher-UI-welcome-page.png](https://zube.io/files/rancher/ae63d66e1d8ee51c0d47093332f7c4c5-rancher-ui-welcome-page.png)

![Rancher-UI-cluster-dashboard.png](https://zube.io/files/rancher/eaf587233fc62e5f992817e98fadd3c4-rancher-ui-cluster-dashboard.png)

**Comment by nwmac** [comment]
Issue might be that we need to fetch the nodes for the cluster (which we do for the explorer view). Doing this on the home page for all clusters would be too expensive.

Investigate, validate, add findings - solution may be to be clearer in the UI why the numbers are different.

**Comment by susesgartner** [comment]
Ticket #9363 - Test Results - Pass ✅
---
Verified on Rancher v2.8-head:

1. Create a downstream cluster.
2. Verify that downstream cluster displays the correct amount of active pods. 

Result: Both the local and downstream cluster display the correct number of active pods
