### ISSUE TITLE
[BUG] Resource type management.cattle.io.clusterroletemplatebinding not found when trying to add cluster members to downstream clusters

### ISSUE THREAD

**Issue by nickwsuse** [rancher/dashboard#9377]
**Rancher Server Setup**
- Rancher version: `v2.7-head Commit ID: 95f0b50`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.26.6`
- Cluster Type (Local/Downstream): `Downstream EC2 - 1 all-role node, 3 workers`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `EC2`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `Admin`
 
**Describe the bug**
When attempting to add a user as a cluster member for a downstream cluster, clicking the "Add" button leads to the "fail-whale" page with the following error message: 
`Resource type management.cattle.io.clusterroletemplatebinding not found`

**To Reproduce**
1. Provision an EC2 HA cluster
2. Sign into the cluster
3. Create a downstream RKE1 EC2 cluster - 1 all-role, 3 workers
4. Once the cluster is up, create a new standard user - u1
5. Go into the downstream cluster -> Cluster and Project Members
6. Click the "Add" button for adding a cluster member

**Result**
Clicking the "Add" button for cluster members fails due to missing clusterroletemplatebinding

**Expected Result**
User is able to successfully add a cluster member with no errors

**Screenshots**
![image](https://github.com/rancher/rancher/assets/107147272/5b56318d-df10-45e3-ad27-02529b065905)

![image](https://github.com/rancher/rancher/assets/107147272/f9099a11-5090-4bad-bdc1-3fd45006d61f)

**Additional context**
I can repro on both RKE1 and RKE2 clusters

**Comment by ronhorton** [comment]
this fix will also address cloudcredentials resource not found error logged in https://github.com/rancher/dashboard/issues/9388

**Comment by richard-cox** [comment]
Note for QA. All of these should be tested together
- https://github.com/rancher/dashboard/issues/9336
- https://github.com/rancher/dashboard/issues/9352
- https://github.com/rancher/dashboard/issues/9354
- https://github.com/rancher/dashboard/issues/9388
- https://github.com/rancher/dashboard/issues/9377

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: 1955476`

Adding cluster members, as well as project members, is working as expected for local users as well as various auth provider users (oauth, ldap, saml)
