### ISSUE TITLE
CNI Cluster Configuration Discrepancy in Rancher-Provisioned RKE2 Clusters

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9378]
Internal reference: SURE-6647
Reported in 2.7.3

Multiple-CNI configuration for rke2 standalone clusters are defined as a yaml list as referenced here - https://docs.rke2.io/install/network_options#using-multus

However, the Multiple-CNI configuration for rke2 downstream clusters requires a comma-delimited list of strings instead of a yaml list. The suspicion is because the CNI selection is a single-select element, meaning each combination is included as a single, comma-separated entry.

After some inspection, a user tracked down this line, where the cni is broken up:

`rke2.vue @ line: 815\n const parts = cni.split(',').map(x => `rke2-${ x }`);\n\n`

The Rancher documentation references the RKE2 documentation as the complete reference of options for RKE2 Kubernetes Clusters in YAML. This would imply that all options would behave identically between setting options in the Rancher UI with YAML and in the `/etc/rancher/rke2/config.yaml` file - https://docs.rke2.io/install/configuration

The user would like to know if this a UI validation edge-case that should be supported or if they are expected to define our cluster CNI as a comma-separated list?

Repro steps:

- Create a new downstream RKE2 cluster
- When setting the CNI, switch to Edit as YAML and configure the cni as stated in the RKE2 docs:
```
 cni:
- multus
- canal
```
- The error `"ERROR: e.split is not a function. (In 'e.split(",")', 'e.split' is undefined)"` appears.
- Switch the CNI configuration to read: 
```
cni: multus,canal
```
- The cluster provisions successfully.

Notes:
Backend ruled out in that the `"ERROR: e.split is not a function"` error comes from the Rancher dashboard code when it tries to split the array, as it is expecting a string value, not an array.

**Comment by markusewalker** [comment]
Reproduced this on `v2.7.5`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7.5`

**TEST RESULTS**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 cluster with Multus CNI specified in a multi-line format|:x:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 `v1.26.8+rke2r1` node driver cluster with `multus,canal` specified.
     - Immediately after provisioning, I see the following screen:
![image](https://github.com/rancher/dashboard/assets/52591819/5749eece-9df6-4d15-a9b4-9bea34803d46) 
     - When attempting to edit the config, I see this screen:
![image](https://github.com/rancher/dashboard/assets/52591819/b03ae7e4-538d-4569-9674-fb71d6b8a978) 
2. Noted that the cluster itself successfully provisioned despite the above errors.

Now that I have reproduced this, I will attempt to validate that this is addressed on the latest `v2.8-head`.

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.8-head` https://github.com/rancher/rancher/commit/595b76a707bd624e77f2d58d206c686bdf3503f7. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/595b76a707bd624e77f2d58d206c686bdf3503f7

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 cluster with Multus CNI specified in a multi-line format|:white_check_mark:|
|2|As a standard user, provision a downstream RKE2 cluster with Multus CNI specified in a single line format|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 `v1.27.5+rke2r1` node driver cluster with `multus,canal` specified.
     - Edited the YAML to ensure that the CNI was specified as a multi-line configuration.
2. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
     - Successfully able to edit the config and edit the YAML without an error screen popping up.

______

**Scenario 2**
1. As a standard user, provisioned a downstream RKE2 `v1.27.5+rke2r1` node driver cluster with `multus,canal` specified.
     - Did not edit as YAML to ensure that the CNI was specified on a single line.
2. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
     - Successfully able to edit the config and edit the YAML without an error screen popping up.
