### ISSUE TITLE
[BUG] Cannot load create page for cloud credentials in latest 2.7-head

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#9388]
**Setup**
- Rancher version: `2.7-head commit ID 95f0b50`
- Rancher UI Extensions:
- Browser type & version: `chrome latest`

**Describe the bug**
When clicking the 'create' button for cloud credentials, getting the fail whale 404 page. 

**To Reproduce**
1. login to rancher
2. click hamburger > cluster management
3. click cloud credentials
4. click 'create'

**Result**
404 error page
resource type cloudcredential not found

**Expected Result**
cloud credentials create page loads

**Screenshots**

<img width="1265" alt="2023-07-20_12-16-38" src="https://github.com/rancher/dashboard/assets/89212856/cc8ddfae-4ad9-4eee-b895-7da54e6d6e5c">

**Additional context**

**Comment by aalves08** [comment]
I believe this will be fixed once we merge https://github.com/rancher/dashboard/pull/9380. 

FYI @gaktive @richard-cox

**Comment by richard-cox** [comment]
Note for QA. All of these should be tested together
- https://github.com/rancher/dashboard/issues/9336
- https://github.com/rancher/dashboard/issues/9352
- https://github.com/rancher/dashboard/issues/9354
- https://github.com/rancher/dashboard/issues/9388
- https://github.com/rancher/dashboard/issues/9377
