### ISSUE TITLE
Misbehaviour during downstream cluster provisioning: Rancher showing importation commands

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9402]
Internal reference: SURE-6520
Reported in 2.7.2 & 2.7.3

Issue description:
When CREATING (not importing) a new downstream cluster using a hosted Kubernetes provider (tested with Azure and Google Cloud), there are some small misbehaviours in the Rancher UI:

- The GUI is showing for a small period of time an "imported" cluster type. This is not an imported cluster, but created using the cloud providers throughout the Rancher UI.
- If you access the cluster in the "Cluster Management" section, it's possible to see the "Registration" tab, which offers the necessary command to import an existing cluster, which has nothing to do with the expected behaviour. This tab should only be shown when trying to import and already existing cluster, but not when creating a new one.

Finally, after some minutes, anything related to the "import process" disappears and the downstream clusters are effectively created

Business impact:
Small, this is more an aesthetic issue. The creation of the cluster works as expected in the end.

Troubleshooting steps:

Repro steps:
- Rancher Management -> Create
- Select a hosted Kubernetes provider (e.g. Azure AKS)
- If you haven't done it yet, create the cloud credentials.
- Provide the requested information to create a new cluster.
- See the previously described behaviour on Rancher UI.

Workaround:
None

Actual behavior:
Created clusters have a tab for Registration command.

Expected behavior:
Created clusters don't have a tab for Registration command.

Files, logs, traces:
Find screenshots attached.

![Figure1.png](https://zube.io/files/rancher/0c47aa8977bbe0c2a450631fa5cf425e-figure1.png)

![Figure2.png](https://zube.io/files/rancher/1005ceafde8cb0ba57b0faddb9659a65-figure2.png)

![Figure3.png](https://zube.io/files/rancher/3e348b740db3e2085e4f130144b28136-figure3.png)

Additional notes:
If we're doing work on this front to port from Ember to Vue, perhaps we can fix this in Vue.

**Comment by richard-cox** [comment]
Note that the bug came in when we showed the registration tab for hosted clusters in order for private hosted clusters to dial home. So the solution needs to consider that. See [thread](https://github.com/rancher/dashboard/pull/9745/files#r1333137709) for details

**Comment by nwmac** [comment]
I don't understand the comment in that thread about private hosted clusters.

It seems to me, we should remove the lines for:

```
if ( this.value.isHostedKubernetesProvider && !this.isClusterReady ) {
```

I don' know why we have - imported clusters are accounted for by the line earlier on in that function, so this specifically catches hosted providers that are not imported - I can't think of a case where you would then manually import that type of cluster.

I'd suggest removing those lines, which is what the PR (https://github.com/rancher/dashboard/pull/9745/files) does.

**Comment by richard-cox** [comment]
Ok, i think i follow.  `isImported` was [updated](https://github.com/rancher/dashboard/pull/9868/files#diff-d888082c4e23d876ed1154a65f0abf824000d685eda426eee3512d88318f7d2bR251) in 2.9.0 to take hosted clusters into account. Given that should now return true it would indeed get caught by `if ( this.value.isImported )`. Think this just needs confirming with the linked PR as is (when this last broke we got three different gh issues).

**Comment by aalves08** [comment]
may be related with https://github.com/rancher/dashboard/pull/9745 ?

**Comment by IsaSih** [comment]
Registration tab was removed, but the imported status in the provider field of the clusters table is displayed for 1 second before disappearing, so I'm reopen the issue to address this behavior.

Tested in v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head

**Comment by nwmac** [comment]
@IsaSih Moving back to test - I think it is okay for now - Alex has created a separate issued for the flicker - we will address that in the next release
