### ISSUE TITLE
EKS Node group details not showing correct information for Custom Launch template

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#9406]
**Setup**
- Rancher version:
```
2.7-head - 95f0b50
eks-operator:v1.2.2-rc3
```

- Browser type & version: Chrome Latest

**Describe the bug**
EKS Node group details not showing correct information for Custom Launch template (eg. AMI ID, Instance type) while Editing cluster
Found while validating: https://github.com/rancher/eks-operator/issues/85

**To Reproduce**
- Create Custom EC2 Launch template with AMI ID and Instance Type
- Provision downstream EKS cluster using above Launch template
- Edit Cluster

**Expected Result**
EKS Node group details must show correct information for Custom Launch template while Editing cluster

**Screenshots**
EKS Node group details:
![image](https://github.com/rancher/dashboard/assets/73099870/d091614b-9b52-41c5-9ec5-94554771fdf1)

Launch template info:
![image](https://github.com/rancher/dashboard/assets/73099870/a612e560-e638-40be-9df5-d2b27ced3681)

**Comment by mantis-toboggan-md** [comment]
This appears to be fixed in 2.9.0

create:
![Screenshot 2024-07-24 at 2 10 13 PM](https://github.com/user-attachments/assets/68da085f-a133-45cc-9724-ae4a58be5fa3)


edit:
![Screenshot 2024-07-24 at 2 10 56 PM](https://github.com/user-attachments/assets/38599b4d-7b0e-4437-9da2-ac94fa029557)

**Comment by gaktive** [comment]
Putting on to the 2.9.0 milestone though at this stage, if it's not a blocker, this could be tested from 2.9.next1.

**Comment by cpinjani** [comment]
Validation passed on build:
```
Rancher - v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head
Dashboard - release-2.9 e108b95
```
![image](https://github.com/user-attachments/assets/b693bcd2-5601-4c7d-a7aa-80bdb490e653)
