### ISSUE TITLE
RKE1 Failed S3 snapshots are able to be restored

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#9409]
This issue is created to separate the RKE1 part of this issue: rancher/dashboard#8839.

**Comment by gaktive** [comment]
UI to repro this; part of this is to confirm with the backend of what the CLI should be returning.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 4dc8b18
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1

----------

### Testing: ###
Tested this issue with the following steps:
1. Create rke1 cluster with s3 enabled for etcd snapshots
2. Create snapshots
3. Create failed snapshot
4. Verify failed snapshot cannot be restored

**Result**
Snapshots are created successfully and failed s3 snapshots are unable to restore.
