### ISSUE TITLE
Daemonsets not available under Workload in Cluster Explorer

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#941]
**On master-head - commit id: `6aef36313`**

`Daemonsets` not available under Workload in Cluster Explorer
<img width="463" alt="Screen Shot 2020-07-31 at 1 55 31 PM" src="https://user-images.githubusercontent.com/26032343/89076673-984afc80-d335-11ea-90a6-a92c1ad6abaa.png">

**Comment by vincent99** [comment]
This is intentional, the groups contain a set we chose as the most useful to show.  Replication Controllers, ReplicaSets, CronJobs, DaemonSets, etc and everything else are under "More Resources".
