### ISSUE TITLE
Add workflow to build extensions in a repo on a release creation (github)

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#9419]
**Is your feature request related to a problem? Please describe.**
Add workflow to build extensions in a repo on a release creation (github)

**Describe the solution you'd like**
Not everyone wants to have a CI/CD like workflow. Some (again Opni) would like to only build the extension when a release is created/tagged. I believe our scripts are setup in such a way that this would be relatively easy to do. Maybe we just needs docs showing how you can create builds using tags or generate different workflows.

**Comment by l4zy0n3** [comment]
This does not seem related to mapps-qa @sowmyav27

**Comment by jordojordo** [comment]
Closing as this doesn't require QA and has been tested by UI developers.
