### ISSUE TITLE
Navigating to cluster explorer page returns Cannot read properties of undefined sometimes

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#9422]
Setup

Rancher version: 2.7-head `c00569d`
Browser type & version: Chrome

**Describe the bug**
When we have a kubectl shell open and then navigate to user Accounts & API keys, create a token and navigate back to the downstream explorer, the explorer page wont load and returns `Cannot read properties of undefined`

**To Reproduce**
1. Create an rke1 and rke2 node driver cluster
2. Open kubectl shell from the explorer of the rke1 and k3s node driver cluster
3. Navigate to profile >> Accounts & Api keys
4. Create a token with the downstream cluster scope.
5. Navigate back to the downstream cluster explorer 

**Result**
The page wont load and returns a blank page with `Cannot read properties of undefined (reading 'rows')`

**Expected Result**
Expected the page to load without errors

**Screenshots**
<img width="300" alt="2023-07-25_15-11-21" src="https://github.com/rancher/dashboard/assets/38144301/276c0b52-f394-46d3-80c0-2a9c81f1c8b9">

**Additional context**
Console Errors:
```
console.js:31 Cannot read properties of undefined (reading 'rows')
```

**Comment by Sean-McQ** [comment]
Issue seems more specific to ContainerShell (the terminal open to a container) rather than the cluster explorer itself.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 027246f
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1 and rke2 aws node driver clusters

----------

### Testing: ###
Tested this issue with the following steps:
1. Create an rke1 and rke2 node driver cluster
2. Open kubectl shell from the explorer of the rke1 and k3s node driver cluster
3. Navigate to profile >> Accounts & Api keys
4. Create a token with the downstream cluster scope.
5. Navigate back to the downstream cluster explorer

**Result**
The page was able to load successfully and the kubectl shell also loaded up with a new session.
