### ISSUE TITLE
In UI for Fleet Continuous Delivery shows target cluster display name. In YAML it uses cluster id

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#9424]
**Describe the bug**

- REF: https://github.com/rancher/fleet/issues/1403#issuecomment-1648135073
- Fleet expects target cluster to be Cluster ID. In UI display name is show. Creates confusion when inspecting / editing the YAML

**To Reproduce**
1. In Continuous Delievery add a GitRepo
2. Make sure in the second step it targets a specific cluster
3. In YAML `spec.targets.clusterName` Cluster ID. In UI it shows the friendly name from label `management.cattle.io/cluster-display-name`

**Expected Result**

- In UI cluster display name is shown everywhere. However Fleet expects cluster ID.  However, this may cause confusion user where they see cluster name in dashboard/cluster list and then try to update yaml with that name instead of ID.
- This works as intended. Not sure if this is feature or a bug. However, it creates a valid confusion and frustration.
- **NB:** Not sure if cluster name can change and be out of sync between management and fleet.

**Comment by nwmac** [comment]
@Shavindra Can you look at this for 2.8, please?

**Comment by nwmac** [comment]
Closing as won't fix - this is just how it is.
