### ISSUE TITLE
Custom Favicon no longer works in 2.7.5

### ISSUE THREAD

**Issue by brownz11** [rancher/dashboard#9426]
**Setup**
- Rancher version: 2.75
- Rancher UI Extensions: N/A
- Browser type & version: Chrome115.0.5790.99 (Official Build) (64-bit)

**Describe the bug**
Custom Favicons no longer work in Rancher 2.7.5

If I had to guess, it appears this bug was introduced in https://github.com/rancher/dashboard/commit/bbb7eebc90297d221cf2ff354eb73813c4e456ed as part of removing nuxt and introducing the index.html with a "shortcut icon" that appears to take precedence over the normal "icon"

**To Reproduce**
Set a custom favicon in a Rancher 2.7.5 installation.

**Result**
The favicon displayed by the browser is the default icon rather than the custom one.

**Expected Result**
The custom icon should display.

**Screenshots**
Wrong
![image](https://github.com/rancher/dashboard/assets/74672092/d60f87d9-f97c-4583-a593-7a740b8a8a57)

Right
![image](https://github.com/rancher/dashboard/assets/74672092/d341efa6-8875-4362-ae83-e290bf4f1436)

**Additional context**
Manually setting the "shortcut icon" to the correct value results in the correct favicon displayed.

**Comment by richard-cox** [comment]
I couldn't reproduce this on v2.7.5.

![image](https://github.com/rancher/dashboard/assets/18697775/988f9ff7-260f-48be-ae4e-b423d4182c48)

Do you see any network request errors, or anything interesting in the console?

**Comment by brownz11** [comment]
I do not.

So far I've only been able to reproduce on Chrome with a cluster that's been upgraded to 2.7.5. Firefox displays the favicon correctly, I haven't yet tested Chrome with a fresh cluster

**Comment by richard-cox** [comment]
I still cannot reproduce this, using Chrome 121.0.6167.184 (Official Build) (64-bit) and the latest code.

It looks like this is an issue with how the favicon href is set though. In your screen shot it's `/favicon.png` where it should be different (`data:image/png;base64,iVBORw....`).

It's applied via https://github.com/rancher/dashboard/blob/master/shell/utils/favicon.js#L10. Do you have a value set for `<rancher domain>/v3/settings/ui-brand`? Are there any errors in the console?

**Comment by brownz11** [comment]
No ui-brand set, no errors. I'm unable to reproduce on 2.8.2. 

Stepping through with a debugger on that function and comparing it to a 2.7.5 cluster I have, it appears https://github.com/rancher/dashboard/commit/1f17d72da01d57178cf1aa856d56105520626106 fixed it by relaxing the logic so it overwrote the shortcut icon
