### ISSUE TITLE
Decouple the sidenav from the default layout to create a standalone component

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#9427]
In support of updating the sidenav, we should first decouple the default layout to a separate component. 

Design: https://xd.adobe.com/view/1453b6a5-ca9c-4794-8fbf-34f1349e45a3-4100/

Rely on the epic rancher/dashboard#9254 for full details but here's some helpful info from there:

----

Added by @aalves08 on 19/07/2023:

I think that this is a great opportunity to decouple the sidenav (make it as a component) from the default layout. We would benefit a lot from that work. There's similar work done here https://github.com/codyrancher/rancher-desktop/pull/1/files#diff-0c0232aeeb5da2a0b2ff8dadf8922e23b71d4c14da75d3d9aa1d99ca66937aec which can give great insights on how to achieve it with the current logic.

Added by @rak-phillip on 19/07/2023:

We also attempted to isolate the sidenav a while back but were not ready to take it. https://github.com/rancher/dashboard/pull/8000

**Comment by gaktive** [comment]
We have existing E2E to help with confirming that we've not broken anything here.
