### ISSUE TITLE
Highlight navigation groups when child items are selected

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#9428]

**Comment by gaktive** [comment]
E2E will be looked at after all the navigation sub-tasks are done (of which, this is one).

**Comment by Josh-Diamond** [comment]
Ticket #9428 - Test Results - ❌ - RE-OPENED
---

Verified on Rancher `v2.8-2e6895ddb220e9dbdeff3fe3a1b554f777e7c4bd-head`:
1. Fresh install of Rancher `v2.8-head`
2. Navigate to Cluster Explorer of any cluster (local may be used, or you may provision a downstream cluster), and select a child item from the nav within a group
3. Verified - navigation group is highlighted when child item is selected; functionally as expected
4. Veri-FAILED - highlighting does not translate well in dark mode and becomes more distracting than helpful; re-opening to voice this concern and bring awareness to the teams

Screenshots:

`Light Mode`
<img width="514" alt="Screenshot 2023-10-18 at 12 17 28 PM" src="https://github.com/rancher/dashboard/assets/46494969/7c79fac7-6eef-4cf5-811a-61c9b97aecdb">

`Dark Mode`
<img width="513" alt="Screenshot 2023-10-18 at 12 17 03 PM" src="https://github.com/rancher/dashboard/assets/46494969/78d7f1b5-cdbe-4a93-bd81-b953137a269e">

**Comment by Josh-Diamond** [comment]
Closing this issue out, as the code is functioning as expected.  Opened a RFE [here](https://github.com/rancher/dashboard/issues/9948), to address styling concerns w/ Dark Mode, which is targeted for `v2.8.x` milestone
