### ISSUE TITLE
Update icons and location for the namespace icon

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#9429]

**Comment by gaktive** [comment]
Wait until #9427 is done so that we don't have to port this over.

**Comment by ronhorton** [comment]
These changes are still in progress.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.8-head commit ID 5cffa89`
1. nav groups highlighted - done
2. sidenav - done
3. sidenav decoupled as standalone element - done

![2023-09-26_14-15-13.png](https://zube.io/files/rancher/308625496fc08cb5e09adf8fb120e0af-2023-09-26_14-15-13.png)
