### ISSUE TITLE
AKS: Page hangs while creating cluster with invalid Node resource name

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#9433]
**Setup**
Rancher version: `v2.7-5f2e119ef43aeff14bfd214d49d6ac36b5cdddf5-head`
Browser type & version: `Firefox 115.0.2esr`

**Describe the bug**
AKS: Page hangs while creating cluster with invalid Node resource name, on Saving button

**To Reproduce**
Create AKS cluster via Rancher UI with unsupported special character in Node resource group name input field eg. !@ and length greater than 80 characters
eg. rancher-test-rancher-test-rancher-test-rancher-test-rancher-test-rancher-test-ra!

**Expected Result**
Proper error must be displayed for unsupported Node resource group name and page must not hang

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/2299d65f-f08d-4cc8-a664-6ce8f46560f1)

**Comment by cpinjani** [comment]
Validated on build: `v2.9-4479597c19bb4f7a74c304aa621932d213a05532-head`
The issue is reproducing on new UI (Vue) as well.

![image](https://github.com/rancher/dashboard/assets/73099870/60e579a1-65da-479e-afbd-f76080b58512)

**Comment by cpinjani** [comment]
Validation passed on build `v2.9-c1d92781561c0d4d5a18b32b2f312655dfe67e9c-head`

![image](https://github.com/rancher/dashboard/assets/73099870/19efa3c7-c34b-4b5e-aa34-58f162d34276)

**Comment by gaktive** [comment]
@cpinjani does UI QA have to test anything here? Or by moving this to Done on the CAPI & Hosted board, can this ticket be closed as validated?

**Comment by cpinjani** [comment]
Closing this ticket as its already validated, thanks.
