### ISSUE TITLE
[BUG]Logs viewed in Rancher are not showing line breaks

### ISSUE THREAD

**Issue by chestarss** [rancher/dashboard#9437]
**Rancher Server Setup**
- Rancher version: v2.6.8
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.24
- Cluster Type (Local/Downstream): eks
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

rancher view logs:
![image](https://github.com/rancher/rancher/assets/11288347/c7cfc110-f526-420b-83c6-d9dffc382695)

kubectl logs output
![image](https://github.com/rancher/rancher/assets/11288347/37c3cbb8-353d-47e6-8d6d-f01b49b43e3b)

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by kerecsen** [comment]
> This looks like a specific problem with EKS. Transferring to the UI to triage
> 
> @chestarss can you add steps to reproduce?
> 
> @kerecsen can you confirm the rancher version?
> 
> @chestarss , @skirsch-alethix , @kerecsen it's not clear which logs these are. can you confirm if they're pod, job, helm chart install, etc?

my rancher version is 2.6.8 and the logs are from pod

**Comment by skirsch-alethix** [comment]
@richard-cox These are pod logs. Behavior is across the board. All pod logs now appear this way in Rancher immediately after upgrade to 1.24. When you download the log using the Download button under the pod log view, the downloaded log looks good.

**Comment by yannickvidal** [comment]
It isn't EKS specific either, we have the exact same issue with AKS (Azure Kubernetes Service)

**Comment by m3talstorm** [comment]
Getting this on Rancher `2.7.1` with a  local cluster running `v1.24.11+k3s1`

**Comment by wormza** [comment]
This happens on 2.6.9 and version 2.7.4 and 2.7.5. However, in the 2.6.9 environment, if you view the logs via the old UI, the logs display correctly.

**Comment by HakimJawrawala** [comment]
How to switch to old UI ? @wormza

**Comment by HakimJawrawala** [comment]
we also have a similar problem 
you can deselect the wrap lines option when you want to view logs. 
The new trailing logs will come in a proper line by line format, but if we want to view logs for last 12 hrs then the old logs would be somewhere still messy.

**Comment by wormza** [comment]
> How to switch to old UI ? @wormza

Sorry for the delayed reply. If you add /g/clusters to the end of your URL it will take you to the old UI. 

eg: rancher.domain.com/g/clusters

**Comment by wormza** [comment]
> Please note accessing the old UI via /g is not supported. There be dragons.

For sure, but for viewing logs until the issue is sorted it’s the only way. I wouldn’t use it for anything else.

**Comment by IsaSih** [comment]
Tests pass on  v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
