### ISSUE TITLE
Cannot create Vsphere cloud credentials in Rancher UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9438]
Internal reference: SURE-6695
Reported in 2.7.5

Issue description:
A user is trying to connect their rancher to vSphere, but they're stuck when creating a cloud credential. It always returns an error `Authentication test failed, please check your credentials` even though if they check these same credentials outside of rancher it works fine.

Business impact:
Unable to spin up the clusters and it is a blocker.

Repro steps:

- Create a fresh Rancher 2.7.5
- Try to add a cloud provider cluster or cloud credentials.

Workaround: none

Actual behavior:
Authentication is failing while providing correct credentials.

Expected behavior:
Authentication should pass through while providing correct credentials.

Goal for UI: 
- reproduce this and see if this points to backend (att'n: @snasovich & @Sahota1225).

**Comment by aalves08** [comment]
Running locally a Rancher `2.7.5` system + Dashboard `2.7-head` I was able to provision valid Vsphere credentials and also a Vsphere RKE2 cluster (in provisioning mode), so I cannot reproduce the issue.

<img width="1374" alt="Screenshot 2023-07-27 at 17 14 43" src="https://github.com/rancher/dashboard/assets/97888974/8c277a52-2991-4b93-adcf-25b93330758d">

https://github.com/rancher/dashboard/assets/97888974/86c1b4b4-cb69-4966-85ab-0791228fa3bc

FYI @richard-cox

**Comment by richard-cox** [comment]
We'll need someone with auth provider / vsphere knowledge to continue debugging this

**Comment by aalves08** [comment]
Update: same test but with Rancher `2.7.5 system` + Dashboard `2.7.5` also good. Cannot reproduce it.

**Comment by gaktive** [comment]
I requested more info; let's see what we get back.

**Comment by gaktive** [comment]
@Jono-SUSE-Rancher this is UI's potential 2.7.6 issue. Awaiting feedback on repro before proceeding.

**Comment by gaktive** [comment]
No update from the initial reporter. This may be bumped or closed since the most recent report indicated that the repro can't be done anymore.

**Comment by gaktive** [comment]
Closing since we were informed that the initial reporter isn't seeing this problem anymore.
