### ISSUE TITLE
ConfigMap name missing UI validation

### ISSUE THREAD

**Issue by nickwsuse** [rancher/dashboard#9442]
**Setup**
- Rancher version: v2.7.5
- Rancher UI Extensions: 
- Browser type & version: Chrome Version 115.0.5790.98 (Official Build) (arm64)

**Describe the bug**
When attempting to create a configmap that has a capital letter in the name, the request is made with no error checks and you get an api error page instead of an error on the UI (or the string being lowercased before the request is made).

**To Reproduce**
1. Provision a v2.7.5 Rancher instance
2. Log into the Rancher instance
3. Click into the `local` cluster from the home page
4. On the left side of the page, click Storage -> ConfigMaps
5. Click the `Create` button in the upper right of the page
6. In the `Name` field, enter at least one uppercase character and whatever else you want
7. Click the `Create` button on the lower right of the page

**Result**
Receive an API error

**Expected Result**
Receive a UI error (or the text is lowercased for the request)

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/107147272/b9877e8b-f42f-4a13-a64d-241f4d0b485b)

**Comment by richard-cox** [comment]
Reproduced in 2.7.5, but in master (2.7q3) we get taken back to the config maps list. The request still fails. There's no error presented to user.

Tries the same with secrets, but the error is shown to the user.

Given the limited impact, i don't think this is a blocker, moving out of 2.7q3
