### ISSUE TITLE
Global Settings: Branding: Private Label: User must reload the page to see the updated title in the browser tab

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#9444]
**Setup**
- Rancher version: v2.7.5
- Dashboard version: v2.7.5
- Browser type & version: Any

**Describe the bug**
After updating the 'Private Label' in Branding, the user must reload the page to see the updated title in the browser tab.

**To Reproduce**
- login to Rancher UI as an admin/standard user
- go to Global Settings -> Branding (/dashboard/c/local/settings/brand)
- update Private Label text (e.g. 'Rancher-e2e')
- click 'Apply'
- check title in the browser tab (this test passes - title updated)
- revert the Private Label text to its original state  (e.g. 'Rancher')
- click 'Apply'
- check title in the browser tab (this test fails - title not updated)

**Result**
The user sees the updated title in the browser tag after page reload.

**Expected Result**
The user should see the updated title in the browser tag in session.

**Screenshots**
![Screenshot 2023-07-27 at 1 49 17 PM](https://github.com/rancher/dashboard/assets/127343932/87ba2c46-83b7-42ee-a167-0f1035c9e9ca)

https://github.com/rancher/dashboard/assets/127343932/40b4aec6-9f79-4964-8480-e29603af1228

**Comment by gaktive** [comment]
This may be prioritized if we address other flaky tests first.

**Comment by nwmac** [comment]
@yonasberhe23 I don't see this anymore - can you close this, if this is no longer an issue.

**Comment by yonasberhe23** [comment]
@nwmac I'm also, unable to repo it. I'll close it. thanks!
