### ISSUE TITLE
Backport 2.7.6: Fix failed to pass guest cluster name into Harvester cloud provider

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9472]
Backport of https://github.com/rancher/dashboard/pull/9381

Summary
Fix failed to pass guest cluster name into Harvester cloud provider

Occurred changes and/or fixed issues
[BUG/DOC] Failed to pass guest cluster name into Harvester cloud provider harvester/harvester#4232

**Comment by khushboo-rancher** [comment]
This has been validated on v2.7.6-rc2 - https://github.com/rancher/dashboard/pull/9381#issuecomment-1669014539
