### ISSUE TITLE
Improve extensions documentation: document cluster-level product

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#9481]
Improve extensions documentation: document `cluster-level` product as an extension (ex: Kubewarden) since I believe we've fixed all of the problems we had with routing.

**Comment by aalves08** [comment]
@jordojordo are you okay with the stability of kubewarden, especially when installed at the same time as Elemental? If so, and if you agree with this issue, then we might do this for `2.7.8`

**Comment by jordojordo** [comment]
@aalves08 Sorry I missed this, I have noticed no issues with both Kubewarden and Elemental installed. I'd say it's safe to make these updates.
