### ISSUE TITLE
Show message to users who try to login during GUID <> AD migration

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/dashboard#9482]
We want to be able to display a unique message when a login fails because AD login is disabled due to the migration.

For Rancher 2.7.6:

    While the migration configmap object indicates that a migration is in progress, logins are rejected for ActiveDirectory.
    The migration script can provide a custom error message, and this may be updated to reflect the migration progress (as a percentage) for particularly large environments.
        The error returned from the API call will look like:
            {
            "baseType": "error",
            "code": "ClusterUnavailable",
            "message": "Login is disabled while migration is running",
            "status": 503,
            "type": "error"
            }
        If we want to show a custom message in the UI, that will require a UI change, otherwise the user will just see the standard, "An error occurred logging in. Please try again."
        If it's useful, it is possible for the migration script to create a RancherUserNotification object.  I think the UI would still need to be updated to display that notification on the login page since afaik, there is nothing doing that right now.
    Local users are not affected and may log in, primarily because we want to ensure local admins are always empowered to investigate the ongoing migration and troubleshoot if necessary

**Comment by gaktive** [comment]
@nwmac may have an existing pattern to use here. He's checking for a prior PR.

**Comment by gaktive** [comment]
PR: https://github.com/rancher/dashboard/pull/9487

**Comment by mantis-toboggan-md** [comment]
Backend has a pr up; waiting on an image w/ that code to continue work on this

**Comment by mantis-toboggan-md** [comment]
UI side is merged; testing will require https://github.com/rancher/rancher/pull/42325 to be merged

**Comment by sowmyav27** [comment]
There is a typo in this error message `An error occured logging in: login is disabled while migration is running`
 . It should be `occurred` instead.

**Comment by sowmyav27** [comment]
On latest 2.7.6-head, i can see the correct error message - `An error occurred logging in: login is disabled while migration is running`.

- Edit configmap from Finished status to Running status.
- Noticed this in rancher logs `2023/08/18 18:45:52 [INFO] [migrate-ad-user] ad-guid migration is currently running, refusing to run again concurrently but the admin/std users were still able to login`
- Edited the Authconfig and changed Finished status to Running status.
- Admin and Std user are blocked from logging in with this ^ error message
