### ISSUE TITLE
Add deprecation notice for OPA Gatekeeper Chart

### ISSUE THREAD

**Issue by rohitsakala** [rancher/dashboard#9483]
**Is your feature request related to a problem? Please describe.**
https://jira.suse.com/browse/SURE-6270

**Describe the solution you'd like**
In the past, there were notices of deprecation for chart ex:- https://github.com/rancher/rancher/releases/tag/v2.5.0 `Deprecation Features` 

We want to deprecate OPA Gatekeeper and we want to send this notication in v2.8.0.

I think the warning/notices could be shown at the following pages 

**Installed Apps**

If the user has OPA Gatekeeper installed, then this warning/notice could be shown. 

**OPA Gatekeeper Chart Info Page**

When the user clicks on the Chart icon the user is redirected to the info page from where he could click on Install. So, showing a warning here would be nice.

**Describe alternatives you've considered**

**Additional context**

**Comment by momesgin** [comment]
@kwwii After installing OPA Gatekeeper it will have its own dedicated section on the sidebar and NOT under the _Apps -> Installed   Apps_. Should the warning be shown on these two places then?
 
 1. Overview page of OPA Gatekeeper:
<img width="1231" alt="image" src="https://github.com/rancher/dashboard/assets/135728925/33f1720a-fe36-464b-960a-33b8e516da28">

2. OPA Gatekeeper's charts Info page:
<img width="1225" alt="image" src="https://github.com/rancher/dashboard/assets/135728925/6b8c05eb-8f2c-4b8f-9515-e67b17a7f599">


Also please provide the copy for the warning message.

**Comment by rohitsakala** [comment]
I think the message would be 

`OPA Gatekeeper chart will be deprecated starting 2.8.0 and will be removed starting 2.10.0. You can switch to kubewarden which is installable using the extensions feature of Rancher.`

cc @leflambeur @gunamata @diogoasouza 

Question - Should we add this comparison document in the warning as well ? https://deploy-preview-205--silly-bunny-8cedd0.netlify.app/comparisons/opa

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.8-head commit ID 07a99a5`
1. navigated to cluster > Apps > opa Gatekeeper
2. deprecation message on install page
3. naviagated to cluster > OPA gatekeepr
4. deprecation message sppears on app overview page

![2023-09-18_16-49-35.png](https://zube.io/files/rancher/2244905ffe58f1f934c3a859c71767ce-2023-09-18_16-49-35.png)
