### ISSUE TITLE
App upgrade can not select namespace

### ISSUE THREAD

**Issue by rd3public** [rancher/dashboard#9489]
Hello,

When Rancher UI upgrades, there is no place to select namespace?

We want to backup/restore the APP, but when the following operations are performed, it will always be upgraded to the original namespace (namespace A) ? Is the original design not to modify the namespace when App upgrade?

**Describe the question**
Step1. Install the APP in `namespace A` 
Step2. Back up the APP in `namespace A` 
Step3. Restore the APP to `namespace B`
Step4. Upgrade the APP to `namespace B`

**Comment by richard-cox** [comment]
@rd3public  Can you provider clearer steps to reproduce? What do you mean by APP and backing up?

**Comment by richard-cox** [comment]
Closing, no additional information
