### ISSUE TITLE
Ensure home page cluster lists handles many many clusters

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9494]
- cluster count may go up to 2k
- the home page would show all 2k in the same page
- we should ensure the page handles this, most probably by adding `:paging="true"`

**Comment by izaac** [comment]
This is an extension of the validation done in: https://github.com/rancher/dashboard/issues/11995#issuecomment-2455487689 . With some environment adjustments for consistency with the [Rancher installation requirements](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-requirements) documentation for Large cluster types (up to 500 downstream).

Rancher version: `2.10.0-alpha7`
UI version: `v2.10.0-alpha5`
Rancher repro version: `2.9.1`
k8s: `1.29` as `HA` with 3 all roles `t3a.2xlarge` nodes. RKE2
**Cluster count: `2001` (includes local)**
Browser: Chrome `130.0.6723.92 (Official Build) (arm64)` Cache disabled on first session.
**Server-side Pagination**: `Enabled`


`v2.9.1` was really slow and it didn't finish rendering the Home page cluster List for me on a few attempts. The Browser crashed too on a couple of occasions. So I decided to skip the performance profiling and focus on acceptable response times.

on `v2.10.0-alpha7` The first session is usually not yet cached by the browser and the request/response and rendering times from end to end was acceptable with less than ~30 seconds on average with the Browser under test.
Subsequent sessions reduced this load times significantly with the cache and the UI felt noticeable more responsive. 
I didn't experience Browser crashes on this version either.
