### ISSUE TITLE
Extension Helm charts are incorrectly filtered when using display-name annotation

### ISSUE THREAD

**Issue by jtomasek** [rancher/dashboard#9496]
**Setup**
- Rancher version: v2.7.5
- Rancher UI Extensions: v2.7.5

**Describe the bug**
`catalog.cattle.io/display-name` annotation on extension Helm chart is used to define a human readable name of the extension which is then used to display it in the extensions list

[The logic which combines the helm charts list](https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/uiplugins/index.vue#L248) with uiplugins list is incorrect because the chart name is set to `chart.chartDisplayName` instead of `chartName`. The relevant uiplugin is then not found and this causes a plugin to be listed in both `Installed` and `Available` tabs.

**To Reproduce**
In Rancher dashboard add a repository which includes a chart which has a `catalog.cattle.io/display-name` annotation. Install the chart.

**Result**
The same plugin is listed as `Installed` and `Available`.

**Expected Result**
The plugin is only visible in `Installed` tab.

**Screenshots**
KubeVirt chart uses `catalog.cattle.io/display-name` annotation to define its human readable name. After it is installed it is visible in both `Available` and `Installed` tabs:
<img width="982" alt="Screenshot 2023-08-08 at 10 45 22" src="https://github.com/rancher/dashboard/assets/1121740/4bbf472e-158d-4eb6-956d-5a750ff6e1eb">
<img width="983" alt="Screenshot 2023-08-08 at 10 45 09" src="https://github.com/rancher/dashboard/assets/1121740/d88b332b-4593-45a2-9f1c-30bc90363518">

**Comment by aalves08** [comment]
Closed in favor of https://github.com/rancher/dashboard/pull/9544
