### ISSUE TITLE
Iconsistent usage of extension annotations

### ISSUE THREAD

**Issue by jtomasek** [rancher/dashboard#9501]
**Describe the bug**
There is an inconsistency among usage of extension chart and plugin annotations defined in extension package.json

extension package.json includes a `rancher` section which allows to enhance extension metadata with custom values. This property is used for example to annotate a Helm chart and extension plugin with `display-name` annotation. However some parts of the code expect it to be nested under `annotations` property, some parts don't:

```
"rancher": {
    "catalog.cattle.io/display-name": "MyExtension",
}
```
vs 
```
"rancher": {
    "annotations": {
      "catalog.cattle.io/display-name": "MyExtension"
    }
}
```

It turns out both are currently needed:
When generating a Helm Chart from a plugin using build-extension.yaml github actions workflow [the code](https://github.com/rancher/dashboard/blob/master/shell/scripts/extension/helmpatch#L43) populates the Chart annotations from package.json -> uses `pkg.rancher.annotations` Without it being defined, no annotations are copied from package.json

When listing Charts in extensions catalog we're looking at Chart annotations: https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/uiplugins/index.vue#L246

When listing installed plugins which don't have a corresponding charts (e.g. builtin plugins or plugins which are installed but their helm repository has been removed) we're looking at the plugin's `pkg.rancher.<someannotation>` (https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/uiplugins/index.vue#L307-L308)

I believe the third case is incorrect and we should enforce defining the annotations in package.json as `pkg.rancher.annotations`.

Doing this however requires plugins to update their package.json if they use an incorrect `display-name` annotation definition such as for example Harvester Manager plugin: https://github.com/rancher/dashboard/blob/master/pkg/harvester-manager/package.json#L7

Slightly related bug: https://github.com/rancher/dashboard/pull/9497

**Comment by jtomasek** [comment]
@aalves08

**Comment by richard-cox** [comment]
We should also document these annotations / locations

**Comment by aalves08** [comment]
Closed as completed via https://github.com/rancher/dashboard/pull/9544
