### ISSUE TITLE
[Flake] Rancher running on Firefox crashes when Alt+~  is pressed 

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#9508]
**Setup**
- Rancher version: v2.7.6-68bd3be1b794cc9ec5473e4187b31dd92eeebb6a-head
- Rancher UI Extensions:
- Browser type & version: Firefox 115.0.2esr (64-bit) (Firefox for openSUSE Leap 15)

**Describe the bug**

Rancher running on Firefox crashes when `Alt+~` is pressed. I use `Alt+~` to switch between multiple  windows.

**To Reproduce**

1. Go to 'Cluster Management' or 'Virtualization Management' or create cluster form.
2. Press `Alt+~` once or twice

**Result**
1.
2. Rancher crashes.

**Expected Result**

1.
2. Nothing should happen.
**Screenshots**

![Screenshot from 2023-08-09 15-46-55](https://github.com/rancher/dashboard/assets/11015077/7cadfc40-2683-417f-b6b9-0cb68e97322d)

**Additional context**

This is a flake.

**Comment by richard-cox** [comment]
I couldn't reproduce this with FF 115.1.0esr (64-bit) on openSUSE 15.4.

Could you..
- provide more details about the type of clusters you have (number, type, etc)
- try to reproduce the error in ff's safe mode
- share a screen shot of the browser dev tools console (there should be an `error` level log with a stack trace

**Comment by valaparthvi** [comment]
I couldn't reproduce this on the v2.7-head image tag either. I'll close this for now, will reopen if I encounter it again.

/close
