### ISSUE TITLE
New cluster template isn't displayed after repository refresh

### ISSUE THREAD

**Issue by susesgartner** [rancher/dashboard#9510]
**Setup**
- Rancher version: 2.7.4, 2.7.5, 2.7.6-rc2
- Browser type & version: Chrome 114.0.5735.198

**Describe the bug**
When you add a new cluster template to a git repository and then refresh the repository in the rancher UI from Cluster Management->Advanced->Repositories the UI doesn't update with the new template until you do a hard refresh.

**To Reproduce**
1. Deploy rancher (versions above)
2. Add a repository to rancher
3. update the repository with a new template
4. refresh the repository from rancher without leaving cluster management (Cluster Management->Advanced->Repositories)
5. Create cluster.

NOTE: this bug doesn't show up if you refresh the repo from local->Apps->Repositories. 

**Result**
The new template will not be displayed.

**Expected Result**
The template will be displayed after the refresh occurs without needing a hard refresh of the page or any other page hopping.

**Comment by gaktive** [comment]
@susesgartner this has been around for a while, so is this needed for the 2.7.6 release? Feels like Q4 is most appropriate but how urgent is this?

**Comment by susesgartner** [comment]
@aalves08 They are catalogue templates from what I understand. They can be used to deploy clusters, to find them in the UI map a github repo with some cluster templates refresh the UI and then they should show up when you create a cluster. 
Here is the repo I was using for testing: https://github.com/susesgartner/cluster-template-examples
The branch is: main

<img width="1307" alt="image" src="https://github.com/rancher/dashboard/assets/136753565/64976380-8e7b-4db0-a23f-65f02104bf97">
