### ISSUE TITLE
Node Detail Page is unreachable

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9515]
**Setup**
- Rancher version: pre-release 2.7q3

**Describe the bug**
- Unable to view node detail page due to full page error

**To Reproduce**
- Navigate to any cluster's node list
- click on any node's name

**Result**
- most of the screen will show up followed by a loading indicator (eugh)
- then white page error shows

**Expected Result**
- node detail page successfully shows

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/75a12e51-54a2-497b-827a-c2b4b67e26d1)

**Additional context**
- think this is caused by https://github.com/rancher/dashboard/pull/9186

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE2 node driver cluster, validate that the node detail appears successfully|

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/b1b5ef0145f5a37ec1fb90263a587452e6b13607. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/b1b5ef0145f5a37ec1fb90263a587452e6b13607

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 node driver cluster, validate that the node detail appears successfully|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Provisioned a downstream RKE2 `v1.26.7+rke2r1` node driver cluster (1 etcd, 1 cp, 1 worker).
2. Navigated to Cluster Explorer > RKE2 cluster > Cluster > Nodes.
3. Validated that the node details appears in each node in my cluster.
