### ISSUE TITLE
Cloud Credential in use is not visible when created inline while Creating a cluster

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#9521]
**Setup**
- Rancher version: v2.7-head
- Rancher UI Extensions:
- Browser type & version: Firefox 15 on openSUSE Leap 15

**Describe the bug**

Cloud credentials used to create/import a cluster is not visible when it is created inline with creating/importing the cluster.

**To Reproduce**

1. Go to Create cluster page.
2. Select GKE.
3. Add a new credential and click on Create.
4. Check the "Google Account Access > Cloud Credential" once "Cluster Location" loads.
**Result**
1.
2.
3. 
4. "Cloud Credential" is empty.
**Expected Result**
1.
2.
3.
4. "Cloud Credential" must not be empty.

**Screenshots**

[Screencast from 08-11-2023 12:28:46 PM.webm](https://github.com/rancher/dashboard/assets/11015077/91afa9ad-40e2-42aa-a0be-90cdc93e2228)

![Screenshot from 2023-08-11 12-17-12](https://github.com/rancher/dashboard/assets/11015077/d4a1c430-25ff-485c-b25b-a3f0cc4b12e8)

**Additional context**

The credential is created successfully, the problem is mostly on the UI.

<details><summary>Inner HTML code:</summary>
<p>

```html
<div class="accordion-header" data-testid="__header" data-ember-action="" data-ember-action-32="32">
  <div class="expand">
      <i role="button" class="icon icon-play eased btn bg-transparent icon-rotate-90">
      <span class="visually-hidden">Open accordion</span></i>
  </div>
  <div class="title">
    <span class="m-0">Google Account Access</span>
    <p class="help-block accordion-detail-text">Choose the Google Project ID and Cloud Credential that will be used to launch your cluster.</p>
  </div>
<!----><!----></div>
<div class="accordion-content " data-testid="__content">
    
        <div class="row">
          <div class="col span-3">
            <label class="acc-label">
              Google Project ID
              <span id="ember51" class="field-required ember-view">*
</span>
            </label>
            <span style="" id="ember52" class="ember-view">      <div class="">
        container-project-qa
      </div>
</span>
          </div>
            <div class="row">
              <div class="col span-4">
                <label class="acc-label">
                  Cloud Credential
                </label>
                <div>
                  
                </div>
              </div>
            </div>
        </div>
      
</div>
```

</p>
</details> 

<details><summary>Outer HTML code</summary>
<p>

```html
<div id="ember31" class="accordion ember-view"><div class="accordion-header" data-testid="__header" data-ember-action="" data-ember-action-32="32">
  <div class="expand">
      <i role="button" class="icon icon-play eased btn bg-transparent icon-rotate-90">
      <span class="visually-hidden">Open accordion</span></i>
  </div>
  <div class="title">
    <span class="m-0">Google Account Access</span>
    <p class="help-block accordion-detail-text">Choose the Google Project ID and Cloud Credential that will be used to launch your cluster.</p>
  </div>
<!----><!----></div>
<div class="accordion-content " data-testid="__content">
    
        <div class="row">
          <div class="col span-3">
            <label class="acc-label">
              Google Project ID
              <span id="ember51" class="field-required ember-view">*
</span>
            </label>
            <span style="" id="ember52" class="ember-view">      <div class="">
        container-project-qa
      </div>
</span>
          </div>
            <div class="row">
              <div class="col span-4">
                <label class="acc-label">
                  Cloud Credential
                </label>
                <div>
                  
                </div>
              </div>
            </div>
        </div>
      
</div>
</div>
```

</p>
</details>

**Comment by mantis-toboggan-md** [comment]
This appears to be fixed in 2.9.0:
![Screenshot 2024-07-24 at 2 39 42 PM](https://github.com/user-attachments/assets/f9ad5d59-0d3d-465c-8175-f5f59f748e82)

**Comment by gaktive** [comment]
Putting on to the 2.9.0 milestone though at this stage, if it's not a blocker, this could be tested from 2.9.next1.

@valaparthvi in the future, be sure to put a milestone at least tied to a version that you discovered this bug in so it's on our project board.

**Comment by izaac** [comment]
The UI is slightly different on Rancher `v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head`

Before creating the GKE cluster the user is required to Authenticate by providing the Project ID and the Cloud Credential from a Dropdown.

The cloud credential is listed in that Dropdown after I created it and I was able to authenticate to start editing a new cluster.
