### ISSUE TITLE
AKS: Allow IPv4 address in Authorized IP Ranges

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#9525]
**Setup**
- Rancher version: v2.7-0b2f7fa0f878c3402ddf416a5b622327949b9348-head
- Browser type & version: Chrome latest

**Describe the bug**
Allow IPv4 address in Authorized IP Ranges while creating downstream AKS cluster. The same is allowed on AKS UI.

**To Reproduce**
- Create downstream AKS cluster and select Set Authorized IP Ranges checkbox under Networking
- Provide IPv4 address, instead of IPv4 CIDR

**Screenshots**
Dashboard:
![image](https://github.com/rancher/aks-operator/assets/73099870/9f8712a0-7180-4711-9324-1b5a0ad248d3)

AKS:
![image](https://github.com/rancher/aks-operator/assets/73099870/5170df25-ccd8-49fa-9e47-6dcfa6f13f81)

Found while validating https://github.com/rancher/rancher/issues/42496

**Comment by richard-cox** [comment]
Adding MS
