### ISSUE TITLE
Can't see Show deprecated Kubernetes patch version for an imported RKE2 clusters

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9530]
Internal reference: SURE-6772
Reported in 2.7.5

Issue description:

Someone can't see the "Show deprecated Kubernetes patch version" checkbox for an imported RKE2 cluster and as such, one of their users can't upgrade to 1.24.15 that they want. The next available is 1.24.16

Business impact:

The user can't upgrade the prod downstream cluster to the desired version

Troubleshooting steps:

We suggested that option as the troubleshooting step, but it is not available

Repro steps:

- Create an RKE2 downstream with version 1.24.9
- Import into to Rancher
- Attempt to upgrade to 1.24.15

Workaround:
none

Actual behavior:
The checkbox "Show deprecated Kubernetes patch version" is not available

Expected behavior:
The checkbox "Show deprecated Kubernetes patch version" should be available

**Comment by gaktive** [comment]
Will be done as part of the port of this page over to Vue.

**Comment by eva-vashkevich** [comment]
This will be fixed once we migrate UI from ember which is currently blocked by BE issue https://github.com/rancher/rancher/issues/43191

**Comment by gaktive** [comment]
Backend should have unblocked this for UI and now we're blocking them. Moving to Next Up.

**Comment by gaktive** [comment]
Upon discussion with product, we won't track this work specifically as a requirement. If it gets fixed as the result of migration, then that's fine.
