### ISSUE TITLE
Replace vue-clipboard2 with Vue3 compatible lib

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#9536]
# Description

Replace current library `vue-clipboard2` with alternative, e.g. [useClipboard](https://vueuse.org/core/useClipboard/) as component.

## Context

As identified in the [migration report](https://github.com/rancher/dashboard/issues/9028#issuecomment-1582565599), it is not possible to use the same library for clipboard functionalities.

As defined in https://github.com/rancher/dashboard/issues/9842 we have 2 components for this and we may take the chance to deal with that as well.

The replacement should affect pretty much 3 places: Vue setup, Jest setup and component.

**Comment by nwmac** [comment]
Note: Work can be started now, but should be merged after 2.8.0

**Comment by richard-cox** [comment]
See https://github.com/Inndy/vue-clipboard2. The functionality we need to update revolve around `$copyText` and `v-clipboard`. Need to understand if `textContent` is available without this lib as well

**Comment by nwmac** [comment]
@eva-vashkevich I think we just use the `$copyText` function of the library to copy to the clipboard.

I think we can just use https://github.com/lgarron/clipboard-polyfill - we probably could get away with the new `navigator.clipboard.writeText` API, but the polyfill would ensure we have the widest browser compatibility.

I think it should be a straight-forward swap in - I'd suggest creating a file `clipboard.js` in utils that exports a `copyTextToClipboard` function that uses the polyfill to copy to clipboard (or could use the new API directly) and then replace usages of `$copyText` with calls to that exported function (need to import it into relevant components etc)
