### ISSUE TITLE
Replace vue-js-modal with Vue3 compatible lib (hold until 8207)

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#9537]
# Description

Replace current library `vue-js-modal` with alternative, no alternative defined yet.

## Context

As in the current state there's an use of several modals, a refactoring with the issue https://github.com/rancher/dashboard/issues/8207 is required before procede.

Scope of the issue:
- Keep same design
- Verify functionality is intact by testing it in a single place

**Comment by nwmac** [comment]
Note: Work can be started now, but should be merged after 2.8.0

**Comment by gaktive** [comment]
Until we get to Vue 3, we should find something that will work with Vue 2 & 3.

**Comment by gaktive** [comment]
We have a lot of modals so this will need some exploration and that some PoCs.

**Comment by gaktive** [comment]
Upon discussion, let's hold on this to ensure we have one modal model since this will simplify the work needed here.

**Comment by richard-cox** [comment]
For reference it looks like the library uses `$modal` which appears 52 times and includes harvester modals, generic models (like Dialog, ModelWithCard, PromptModal etc) and function specific modals.

Any changes to modals will also need to be communicated to extension owners, who will need to update their own modals (harvester, epinio, etc)

**Comment by cnotv** [comment]
@richard-cox please move the discussion to https://github.com/rancher/dashboard/issues/8207, as it's out of the scope of this migration and more bound to the technical debt.

**Comment by richard-cox** [comment]
Related to https://github.com/rancher/dashboard/issues/10661

**Comment by rak-phillip** [comment]
This was removed in #10591 and re-introduced in #10675 to maintain Harvester compatibility. Harvester will have to migrate off of `vue-js-modal` to the new solution in the Vue3 migration. 

@torchiaf let me know if you have questions, comments, or concerns about this change moving forward.
