### ISSUE TITLE
Remove vue-meta

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#9538]
# Description

Replace `vue-meta`, discontinued since 3 years but [has replacement for Vue3](https://github.com/nuxt/vue-meta/tree/next), still discontinued since 1 year, there's also no envisioned use case, as we don't update metadata.

**Comment by cogor** [comment]
Simple alternative is UseTitle from VueUse 
 https://vueuse.org/core/useTitle/#usetitle

**Comment by nwmac** [comment]
Note: Work can be started now, but should be merged after 2.8.0

**Comment by nwmac** [comment]
Note, although not used currently, we do have a feature for Q1 to add meaningful page titles

**Comment by cnotv** [comment]
It should not be complex to add another library afterwards and link it to the router.

**Comment by gaktive** [comment]
Let's remove it and if we need it later, we can add it back in.

**Comment by CC007** [comment]
> Note, although not used currently, we do have a feature for Q1 to add meaningful page titles

That's good news! Seeing just the text 'Rancher' in your page history was never that helpful, especially when navigating through a lot of pages.
