### ISSUE TITLE
Update Storybook to use Vue3

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#9540]
# Description

[As defined in the findings](https://github.com/rancher/dashboard/issues/9028#issuecomment-1582565599), update Storybook libraries and configuration to a working version.

[Identified issues in CI](https://github.com/cnotv/dashboard/actions/runs/7037458886/job/19152268422).

(screenshot in case of expiration)

<img width="1299" alt="Screenshot 2023-11-29 at 20 22 23" src="https://github.com/rancher/dashboard/assets/5009481/fda0e55b-5ad7-4d0c-b576-9cde46b8b0ec">

**Comment by gaktive** [comment]
We need an updated link of the CI logs since the ones here are expired.

**Comment by cnotv** [comment]
Updated URL due CI log expiration. Fixed PR conflicts. Added screenshot samples.

**Comment by cnotv** [comment]
"@storybook/manager-webpack5/html-webpack-plugin": "^5.0.0"

**Comment by cnotv** [comment]
Looks like they decided to deprecate @storybook/vue after I did my investigation 
https://github.com/storybookjs/storybook/issues/24779

I also see that they are considering exclusively Vite as an option, if I am not understanding it wrong
https://storybook.js.org/blog/first-class-vue-support-storybook-8/

**Comment by cnotv** [comment]
Completed with:
- https://github.com/cnotv/dashboard/commit/913777691bbf25b3a7e3af656d683c67d78c95a7
- https://github.com/cnotv/dashboard/commit/8902e161515043c3e803f1de4469d9ad706df9f9

Remaining rendering issues to be solved separately, since the pipeline is green.
