### ISSUE TITLE
Global Settings: Settings: 'ui-brand' value automatically reverted to none when navigating away from global settings

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#9551]
**Setup**
- Rancher version: v2.7.5
- Rancher UI Extensions: N/A
- Browser type & version: Any

**Describe the bug**
'ui-brand' value is automatically reverted to <None> when navigating away from global settings.

**To Reproduce**
- login to Rancher UI as an admin user
- go to Global Settings -> Settings (/dashboard/c/local/settings/management.cattle.io.setting)
- scroll down to 'ui-brand' option
- click elipsis
- click 'Edit Setting'
- update ui-brand value (e.g. 'suse')
- click 'Save'
- notice rancher logos are used
- navigate to the home page
- notice rancher logos are no longer used

**Result**
'ui-brand' settings value is automatically reverted to <None> when navigating away from global settings.

**Expected Result**
'ui-brand' settings value should be preserved.

**Screenshots**

<img width="1487" alt="Screenshot 2023-08-15 at 1 29 28 PM" src="https://github.com/rancher/dashboard/assets/127343932/451e5d56-f770-44db-b350-69ae5738265a">

https://github.com/rancher/dashboard/assets/127343932/75743452-2e98-4865-92b1-42827e738445

**Comment by gaktive** [comment]
Based on the video, the ui-brand parameter has been changed. @codyrancher tried a repro and noted that upon leaving the page, 2 PUTs are made and the value is blank.

**Comment by codyrancher** [comment]
Caused by this section of code in branding https://github.com/rancher/dashboard/blob/b99b65003ea4a8ff6f41298db371edf90cf662fd/shell/mixins/brand.js#L147-L151

**Comment by richard-cox** [comment]
In terms of branding the cspAdapter is king, so if that thinks there's no branding and a branding option is set... it removes the branding option. This catches errors if the user goes from prime / suse world to not prime / suse world.

However that introduces the bug here where there is no cspAdapter branding and the user tries to set a branding value.  

Need to check with @nwmac to see which is best here, cater for the case an instance goes non-prime or allow the user to manually set a branding.

**Comment by nwmac** [comment]
@richard-cox I'm confused - we'll need to discuss this

**Comment by richard-cox** [comment]
Discussed with Neil, we can chop out the code that resets the branding setting if there's no cspAdapter app. i.e.
shell/mixins/brand.js
```
      else if (!neu) {
        const brandSetting = findBy(this.globalSettings, 'id', SETTING.BRAND);

        if (brandSetting) {
          brandSetting.value = '';
          brandSetting.save();
        }
```

**Comment by yonasberhe23** [comment]
Fixed: ui-brand no longer reset automatically when navigating away from page


https://github.com/rancher/dashboard/assets/127343932/2c5b30fa-4069-411c-a40a-35f31e374def
