### ISSUE TITLE
Rancher UI crashes when adding incomplete Project Resource Quotas

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9558]
Internal reference: SURE-6733
Reported in 2.7.5

Issue description:
Rancher UI "crashes" when adding incomplete Project Resource Quotas. 

Business impact:
No real impact because you can go back and add the "missing" part

Troubleshooting steps:
Easy to reproduce 

Repro steps:

1. create a dummy project 
2. add a namespace to the project
3. Edit Project configuration --> Resource Quotas (there should be no quota listed at that time) 
4. add Resource, i.e. "CPU Limit" and only add a value for the Project Limit (no entry for the Namespace)  and press "Save". 

Result: Rancher UI "crashes" and the message " "Cannot read properties of null (reading 'limit')"  is getting displayed

Workaround:
Add values to all fields defined

Actual behavior:
Rancher UI "crashes"

Expected behavior:
Display an error message instead, i.e. "does not have all fields defined on a resourceQuota". This error message gets already displayed when you have already one Resource Quota defined and you re-edit the project configuration by adding a second, but incomplete set of resource quotas

![Screenshot from 2023-08-03 13-38-08.png](https://zube.io/files/rancher/b316675fc536634b9e83a7c3e2f9b4ee-screenshot-from-2023-08-03-13-38-08.png)

**Comment by jonatan5524** [comment]
Hi I'm new to this repo, I would like to work on this issue

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

<details>
    <summary>Reproduction details... Click to expand</summary>




| Component                        | Version / Type                                         |
| -------------------------------- | ------------------------------------------------------ |
| Rancher version starting         | v2.7.6                                                 |
| Rancher version upgraded         | not applicable / `fresh install`                       |
| Rancher commit link              | https://github.com/rancher/rancher/releases/tag/v2.7.6 |
| Installation option              | Docker                                                 |
| Cert Details                     | `--acme-domain`                                        |
| Docker version                   | 20.10.7, build f0df350                                 |
| Helm version                     | v2.16.8-rancher2                                       |
| Downstream cluster type          | not applicable                                         |
| Downstream K8s version           | not applicable                                         |
| Authentication providers enabled | local                                                  |
| Logged in user role              | admin                                                  |
| Browser type                     | Firefox Developer Edition                              |
| Browser version                  | 119.0b5 (64-bit)                                       |
| Dashboard                        | v2.7.6                                                 |
| Webhook version                  | rancher-webhook:v0.3.5                                 |
| Rancher env setup via            | https://github.com/brudnak/linode-docker-cattle        |



## Reproduction steps

1. Logged into Rancher as admin
2. Create a project ===> `test-project1`
3. Within that project, create a namespace ===> `test-ns1`
4. Then edit the config of `test-project1`
5. Add a `Resource Quota`
   - Click `Add Resource`
   - Resource Type: ===> `CPU Limit`
   - Project Limit: ===> `48`
   - Namespace Default Limit: ===> not specified
   - Click `Save`


## Reproduction Results

### ✅ (Reproduction) Expected

For there to be some validation and the UI to have a message the Namespace Default Limit is needed.

### ❌ (Reproduction) Actual

Rancher UI "crashes" with `can't access property "limit", e.value.spec.namespaceDefaultResourceQuota is null `

</details>

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version starting         | v2.8-fc12e7d779577d10ded1a8e249f51727848b878e-head                                 |
| Rancher version upgraded         | not applicable / `fresh install`                                                   |
| Rancher commit link              | https://github.com/rancher/rancher/commit/fc12e7d779577d10ded1a8e249f51727848b878e |
| Installation option              | Docker                                                                             |
| Cert Details                     | `--acme-domain`                                                                    |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin                                                                              |
| Browser type                     | Firefox Developer Edition                                                          |
| Browser version                  | 119.0b5 (64-bit)                                                                   |
| Dashboard                        | master 702c54e96                                                                   |
| Webhook version                  | rancher-webhook:v0.4.0-rc10                                                        |
| Rancher env setup via            | https://github.com/brudnak/linode-docker-cattle                                    |


<a name="top"></a>

### :muscle: Test Cases

| \#  | Priority | Description & Link | PASS/FAIL |
| --- | -------- | ------------------ | --------- |
| 1   | P0       | [Test 1](#test-1)  | ✅ PASS    |


<details>
    <summary>🚨 1 test case... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Status: ✅ PASS

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Logged into Rancher as admin
2. Create a project ===> `test-project1`
3. Within that project, create a namespace ===> `test-ns1`
4. Then edit the config of `test-project1`
5. Add a `Resource Quota`
   - Click `Add Resource`
   - Resource Type: ===> `CPU Limit`
   - Project Limit: ===> `48`
   - Namespace Default Limit: ===> not specified
   - Click `Save`

**✅ Expected Outcome**

For there to be some validation and the UI to have a message the Namespace Default Limit is needed.

**✅ Actual Outcome**

Getting an error banner with a message as expected: `does not have all fields defined on a resourceQuota`


</details>

<hr>

</details>
