### ISSUE TITLE
Refactor Basics and Members role tabs from RKE2.vue into separate tabs

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#9572]
Need to Refactor RKE2.vue for better reusability. This issues is for Basics and Member roles tabs.

**Comment by richard-cox** [comment]
@eva-vashkevich Was this for v2.8.0?

**Comment by richard-cox** [comment]
I've moved this in to 2.8.0 to represent the splitting out of basics and members tabs. There'll need to be follow on issues for the other tabs / remaining work

**Comment by slickwarren** [comment]
@eva-vashkevich or @richard-cox was this validated with e2e testing by your team, or would QA need to validate this?

**Comment by eva-vashkevich** [comment]
@slickwarren We don't have E2E tests for this right now

**Comment by richard-cox** [comment]
This issue represents the entire refactor of the component.

Work as merged in the 2.8.0 timeline though. @eva-vashkevich what were the issues for those, do we need QA or e2e for them?

**Comment by eva-vashkevich** [comment]
I think we should have Qa validate that nothing has changed as a result of this refactoring. I will be adding tests but don't have them yet. SO it will be good to validate that nothing is broken

**Comment by susesgartner** [comment]
Ticket #9572 - Test Results - PASS ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Add a member | PASS |
| 2. | Create a cluster with default basics tab values | PASS |
| 3. | Create a cluster with non-default basics tab values | PASS |
  
---
Verified with HA Helm on Rancher `v2.8-head`:
---
 
Basic UI elements validations: 
---
1. Validated that all UI elements in basics and member roles exist and match the test plan [TestPlan.docx](https://github.com/rancher/dashboard/files/12529188/TestPlan.docx)
2. Validated that you can cycle states of all UI elements in basics and member

Functional Tests
---
Scenario 1: Add a member
---
1. Create a new user.
2. Create a cluster and add the user via the member roles tab

Result: Cluster provisions successfully 

Scenario 2: Create a cluster with default basics tab values:
---
1. Create an AWS ec2 cluster and leave the basics tabs default

Result: cluster provisions successfully

Scenario 3: Create a cluster with non-default basics tab values:
---
1. Create a cluster with the following Basics tab config:
k8s version: 1.23 (deprecated)
Container network: Cilium

Result: cluster provisions successfully
