### ISSUE TITLE
EKS: Restrict disabling both Public & Private Access 

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#9576]
**Setup**
```
Rancher version: v2.7-0b2f7fa0f878c3402ddf416a5b622327949b9348-head
Browser type & version: Chrome latest
```

**Describe the bug**
User must not be allowed to disable both Public/Private Access, there must be validation for the same.

**To Reproduce**
1. Start to create downstream EKS cluster
2. Select both Private/Public under Networking API Server Endpoint Access and create cluster
3. Edit cluster and unselect both Private/Public access checkbox and submit -> Fails (Expected, screenshot below)
4. Edit cluster and unselect Private access checkbox and submit
5. Edit cluster and unselect Public access checkbox and submit, this step must not allowed on UI as both Access are disabled, but User is able to Submit

**Screenshots**
Expected Validation on Step 5:
![image](https://github.com/rancher/dashboard/assets/73099870/6abf388e-f88f-4ac2-a7ec-e25f335c71fa)

Error after disabling both Access:
![image](https://github.com/rancher/dashboard/assets/73099870/188318b6-793b-434e-b838-806d67e717b6)

Found while validating https://github.com/rancher/rancher/issues/42496

**Comment by mantis-toboggan-md** [comment]
This appears to be fixed in 2.9.0 - users are shown an error message and saving is prevented if neither public nor private access is enabled.
https://github.com/user-attachments/assets/596e5fc4-8918-4cc7-97a3-3883871c5663

**Comment by gaktive** [comment]
Putting on to the 2.9.0 milestone though at this stage, if it's not a blocker, this could be tested from 2.9.next1.

**Comment by izaac** [comment]
Validated on Rancher `v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head`

The user is no longer able to Submit using the UI on Step 5 from this issue Description because the Save button is disabled immediately when both Private/Public network options are disabled.
