### ISSUE TITLE
 Installing `rancher-istio-installer` chart from dashboard always installs the latest version

### ISSUE THREAD

**Issue by bmdepesa** [rancher/dashboard#958]
rancher/rancher:master-head a9c601609 

* Navigate to dashboard for the cluster
* Select Istio `1.6.6` or `1.6.5` when launching `rancher-istio-installer` (or any version below the latest)
* Deploy chart
* Installation fails after attempting to install Istio `1.7.0`, even though a lower version was specified: 
```
Tue, Aug 4 2020 2:52:40 pm
helm install --create-namespace=true --version=1.7.000 rancher-istio /home/shell/helm/rancher-istio-installer-1.7.000.tgz
Tue, Aug 4 2020 2:52:41 pm
Error: file '/home/shell/helm/rancher-istio-installer-1.7.000.tgz' does not appear to be a gzipped archive; got 'text/html; charset=utf-8'
```

The call to `dev-charts?action=install` from UI has `1.7.0` specfied:
```
{"type":"chartInstallAction","charts":[{"chartName":"rancher-istio-installer","version":"1.7.000","releaseName":"rancher-istio","values":{}}]}
```

The dev tools also show the UI calling GET `dev-charts/info?chartName=rancher-istio-installer&version=1.7.000` and receiving a `500` error: `{"type":"error","links":{},"code":"ServerError","message":"gzip: invalid header","status":500,"type":"error"}`

**Comment by deniseschannon** [comment]
Now that istio has 2 versions and the UI flow for chart deployment has changed, can we re-test to see if this is still an issue.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head a1acca8567ec3f51735d3c657b17e282979d0d9a

There is no version selector, and `1.7.000` is loaded by default. 

By editing the URL to include `1.6.800`: 
`dashboard/c/local/apps/install?repo-type=cluster&repo=rancher-charts&chart=rancher-istio&version=1.6.800#values-yaml`

the `Values YAML` is populated with the correct version, and I can install the previous version

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.0-alpha1

* The version selector is now displayed and installs the selected version
