### ISSUE TITLE
Extensions page -- Help/verification for docs note about which extensions are displayed under Available vs Installed

### ISSUE THREAD

**Issue by martyav** [rancher/dashboard#9580]
I was updating a doc when I ran across the note in this [section](https://ranchermanager.docs.rancher.com/integrations-in-rancher/rancher-extensions#installing-extensions) of the Installing Extensions page:

> In v2.7.0, the built-in extensions will not be displayed under the Available tab. Therefore, you will need to manually add the desired repos to install extensions. We will update the community once these extensions have been pulled out to be available for selection.

Upon investigation, Virtualization Manager is the only built-in extension listed in v2.7.2 and later, under the **Installed** tab. In v2.7.1 and v2.7.0, all tabs other than **Available** are empty. 

 I'm not sure that I understand the note. I interpreted it as meaning, several built-in extensions were once listed under **Installed**, then removed in 2.7.0. If they're built-in, why do they need to be manually added? "Pulled out to be available" == placed under the **Available** tab? Why is Virtualization Manager still listed? 

Can you clarify how we should address this in the Rancher documentation?

**Comment by aalves08** [comment]
Hi @martyav . I work for the UI team of Rancher and I mostly deal with extensions. I don't exactly remember that point in time (as I only started working on the extensions after `v2.7.0`) but I believe what that note means was that built-in extensions before `v2.7.0` probably appeared on the `available` tab or something along those lines. They now appear in the `installed` tab.

Imo, for `latest` documents, I would remove that note altogether as we are a few patch versions after `v2.7.0` and it's confusing in that particular context. Maybe keep it for people who are updating to `v2.7.0` in a historical context still makes sense.

Nevertheless, the whole extension mechanism on the UI as we know it was in it's infancy at the point of time I think. Again, imo, if Rancher users want to full use extensions in the UI we should encourage them to update Rancher (stuff like `Elemental` or `Kubewarden` only appeared much later in time, so no "official" rancher extensions at that point in time and they should not work on 2.7.0 either).

We also have documentation on extensions that we try to update as regular as possible: https://rancher.github.io/dashboard/extensions/home 

This should be a good source of truth. 

Cheers! 🙏

**Comment by martyav** [comment]
Thank you!

**Comment by martyav** [comment]
Initially closed. @aalves08 Since the latest version and the 2.7 version of the docs page are essentially the same, we probably do need to keep the note there. How does this revision sound?

> If you've upgraded from an older Rancher version to v2.7.0, uninstalled built-in extensions are no longer listed under the **Available** tab, unless you've manually imported them.

**Comment by aalves08** [comment]
Sounds good @martyav . Going to close this issue.
