### ISSUE TITLE
Cluster Explorer adjustments for smaller screens

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#9584]
As a part of rancher/dashboard#4215, we need to provide some adjustments for the Cluster Explorer views so they can be used in smaller screens. 

While we're not aiming for a mobile-first experience, we need to make sure the UI does not break.

**Comment by edenhernandez-suse** [comment]
Documentation of the process in this [Confluence page](https://confluence.suse.com/display/CU/Cluster+Explorer+responsive+design)

**Comment by kwwii** [comment]
The next step is to create specification
