### ISSUE TITLE
UI workload creation with storage should pick the default storage class

### ISSUE THREAD

**Issue by kourosh7** [rancher/dashboard#9585]
**Setup**
- Rancher version: 2.7.5
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
 Creating a workload from the UI with storage should default to the default storage class. 

**To Reproduce**

1. Create a default StorageClass in a cluster
2. For the same cluster, select Workloads > Deployments > Create from the UI
3. Select Pod > Storage > Add Volume > Create PVC 

**Result**
 The storage class dropdown is empty
 
**Expected Result**
The storage class field should default to the default storage class

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/39573922/af803713-15da-4088-85a5-ffdb8012f345)
![image](https://github.com/rancher/dashboard/assets/39573922/f63befae-d2b1-4818-904b-1139c336f871)

**Additional context**

**Comment by gaktive** [comment]
Internal reference: SURE-6812

**Comment by cnotv** [comment]
Once again a dev automation seems not possible as defined in https://github.com/rancher/dashboard/pull/9264#issuecomment-1633877037

**Comment by dasarinaidu** [comment]
I have validated this issue on` v2.8.0-rc3` and `v2.8-head`

On both versions I am seeing an issue in populating the default value. 

When user changes the default value selection from a storage class to a different one : The newly selected default value is not reflected in Deployment creation section.

**Details as below :** 
1. Provision rancher v2.8.0-rc3
2. Create a Downstream cluster
3. DownstreamCluster->StorageClasses->Create 2 storage classes(ex: sc1 and sc2)
4. Select one of them as Default (sc1)
5. Goto DownstreamCluster->Workloads->Deployments->Create-> Pod->Storage->Add volumes->CPVC
6. Check for the default value of the Storage class , It is displayed as sc1 and it is correct
7. Repeat steps 3,4: Now modify the default value to (sc2)
8. Check for the default value of the Storage class , It is displayed as sc1 only, it is not changing it to sc1

**Actual:**
1. Update default value in Storage class is NOT reflecting in Deployment creation
2. Always shows the initial value which was selected as default

**Note:**
1. I validated by logout and login to the application and seeing the same issue
2. Validated by using Incognito and seeing the same issue
3. I deleted the sc1 and then changed the setting to a different storage class and it started displaying the new value
4. I added a new storage class and mark it as a Default value and it is NOT reflecting in Deployment creation



![image](https://github.com/rancher/dashboard/assets/22034884/11774a1c-9a6a-4da4-9a98-842c501e94d5)

**Comment by cnotv** [comment]
It seems like the value is not updated till refreshed the page, so there's an issue with the "set default" not updating the data.

**Comment by richard-cox** [comment]
@dasarinaidu A fix will be ready once the build completes https://drone-publish.rancher.io/rancher/dashboard/4806

I've also deleted the `reopened` label (`[zube]: Reopened` is the one to use)

**Comment by dasarinaidu** [comment]
Looks like the build is failed? please advise..

**Comment by richard-cox** [comment]
It needed a bump, see https://github.com/rancher/dashboard/issues/9585#issuecomment-1816582888

**Comment by dasarinaidu** [comment]
Validated this his issue on `v2.8-58bfcb19605d51bf24f0aa5bf1d60a68b1ae2a27-head` , looks good to me and closing this card.

**Test cases:**
1. Validated this on creating a **Deployment / DaemonSet/Jobs/Pods**
2. Admin and standard users( Create storage class as Admin and check if the Standard user can see the defaulted values)
3. Add / remove & update storage classes and add Set default and make sure the reflection is working as expected
4. Standard and auto mode
5. Validated on chrome and Incognito browsers
