### ISSUE TITLE
APP Bar - Pinning clusters

### ISSUE THREAD

**Issue by scures** [rancher/dashboard#9587]
**Describe the solution you'd like**

We want to be able to pin a cluster by clicking it from the menu.

## AC:
- Allow the user to pin a cluster by clicking it
- Store this configuration of the saved clusters in the same format as we get it here (https://github.com/rancher/dashboard/blob/master/shell/components/nav/TopLevelMenu.vue#L64) 

Specs: https://xd.adobe.com/view/04a2e3b8-4895-405d-a067-5f2c88e83738-51f1/specs/

**Comment by susesgartner** [comment]
Ticket 9587 - Test Results - Pass ✅
---
Verified on Rancher v2.8-alpha1:

Scenario 1 -

1.  In rancher instance pin a multiple clusters
2. Confirmed that pinned clusters moved to the top and had appropriate UI icons

Scenario 2 -

1. Unpin multiple clusters
2. Confirmed that the clusters returned to their appropriate location in the UI and all UI icons returned to their original state.
