### ISSUE TITLE
Add support for additional / legacy question features

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9588]
See description in https://github.com/rancher/dashboard/pull/9488

**Additional context**
For testing please use the repo `https://github.com/richard-cox/rodeo`, branch `test` and app `tetris`. The [questions.yaml](https://github.com/richard-cox/rodeo/blob/master/charts/tetris/questions.yml) should contain examples of all new features

**Comment by richard-cox** [comment]
See https://github.com/rancher/dashboard/issues/9589 for ip6 validation

**Comment by l4zy0n3** [comment]
Verified on 
k8s v1.26.8
rancher v2.8-head
1. Add the repository https://github.com/richard-cox/rodeo in rancher
2. Open the installation form for Tetris Chart
3. Verified features mentioned here https://github.com/rancher/dashboard/pull/9488
