### ISSUE TITLE
UI does not handle failures when creating or editing via YAML

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9592]
**Setup**
- Rancher version: 2.7.7 ish

**Describe the bug**
- failures thrown after pressing create / save in any resource yaml returns the user to the resource list as if it succeeded
- user is not shown error, resource remains uncreated/saved
- this happens in both the vanilla `Create from Yaml` view and also the create/edit forms `Edit as Yaml` view

**To Reproduce**
- Multiple ways
  - Pods List --> Create --> Edit Yaml --> break yaml syntax --> Create (error in console)
  - More Resources --> Apps --> ControllerRevisions --> Create from YAML --> Create (error in console, failed network request)

**Result**
- User is taken back to the resource's list view

**Expected Result**
- User should stay in the same view and be presented with the error

**Comment by richard-cox** [comment]
Don't think this is related, but might be worth investigating, resource-class `async _saveYaml(yaml) {` uses ` method: 'PUT',`. in code we normally look for `put` and lowercase the method that's being processed. could be a gap there

**Comment by Josh-Diamond** [comment]
Ticket #9592 - Test Results - ✅ 
---

Reproduced on Docker install running Rancher `v2.7.7-rc4`:
1. Fresh install of Rancher `v2.7.7-rc4`
2. Provision a downstream K3s AWS Node driver cluster
3. Once `active`, navigate to `Cluster Explorer > Workloads > Pods > Create > Edit as YAML`, break the YAML syntax, and then hit `Create`
4. Reproduced - user is navigated back to `Pods List` page and resource is NOT created; console logs show `Uncaught (in promise)` error

---

Verified on Docker install running Rancher `v2.8-5eb68ce6199009ab30878d6e687c76ba7c862dd6-head`:
1. Fresh install of Rancher `v2.8-head` 
2. Provision a downstream K3s AWS Node driver cluster
3. Once `active`, navigate to `Cluster Explorer > Workloads > Pods > Create > Edit as YAML`, break the YAML syntax, and then hit `Create`
4. Verified - UI validation checks prevent the request from being sent; the user is informed of the error and the user is NOT navigated away from the page; as expected

Screenshot:
<img width="1287" alt="Screenshot 2023-09-25 at 1 50 47 PM" src="https://github.com/rancher/dashboard/assets/46494969/66952ec7-ee0e-4cbf-ac6f-33f6a85ca4f1">
