### ISSUE TITLE
PSP warning when upgrading a cluster does not display correctly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9593]
**Setup**
- Rancher version: 2.7.5

**Describe the bug**
- see screenshots

**To Reproduce**
- create a 1.25 cluster in Rancher 
- create some psps
- attempt to upgrade from 1.25 to 1.26 via Cluster Manager --> Edit Config

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/ce878f49-0951-4361-a7e8-f7ba8ee1580f)

![image](https://github.com/rancher/dashboard/assets/18697775/f9b12c12-b2c4-41f7-a9dd-a13779a06712)

**Additional context**
- could be a v-clean-html thing with the `manually` text?

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a hardened K3S `v1.24.17+k3s1` custom cluster with PSPs enabled, attempt to upgrade and validate that the warning message displays properly|

**Comment by markusewalker** [comment]
Validated this against `v2.8-head` https://github.com/rancher/rancher/commit/a9ea4ce4a5bab9dd112cd20c9e250aba4dbe5176.

**ENVIRONMENT DETAILS**
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/a9ea4ce4a5bab9dd112cd20c9e250aba4dbe5176
- Rancher install: Docker

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a hardened K3S `v1.24.17+k3s1` custom cluster with PSPs enabled, attempt to upgrade and validate that the warning message displays properly|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a hardened downstream custom K3S `v1.24.17+k3s1` cluster w/PSPs.
2. Validated that the cluster and nodes are `Active`.
3. Attempted to upgrade to `v1.27.5+k3s1` and received the following warning message:
![image](https://github.com/rancher/dashboard/assets/52591819/d50592ba-1881-4ac5-8b0b-2ee3ca2fb47a)
