### ISSUE TITLE
Users Redirected Back to Login Page After First Successful Login

### ISSUE THREAD

**Issue by mvcodez** [rancher/dashboard#9595]
**Setup**
- Rancher version: 2.7.4, 2.7.5, 2.7-head
- Rancher UI Extensions:
- Browser type & version: Firefox/Edge/Chrome latest

**Describe the bug**

The dashboard will fail to login on first attempt and will briefly redirect the user to the home page before instantly redirecting them back to the login page with a timed-out error `/dashboard/auth/login?timed-out`. Manually reloading the dashboard homepage will successfully take the user there, however, without logging in again.

This error only occurs without having logged into the site before (or clearing cache/cookies). If I log in then manually log out, I won't see the error when I relogin. However, if I open a private window and try to login, I'll see the error. I've attempted building the image with 2.7.4, 2.7.5, and 2.7-head and I'm experiencing the error across all 3 versions.

**To Reproduce**

Clone dashboard v2.7.4, then build the full rancher image and deploy (I change the container image version in the `cattle-system/rancher` deployment).

My Dockerfile:
```
FROM node:16.20.1-bullseye AS builder

WORKDIR /src

COPY ./dashboard .
RUN yarn --pure-lockfile install

ENV ROUTER_BASE="/dashboard"
ENV RESOURCE_BASE="/dashboard"
RUN yarn run build

FROM rancher/rancher:v2.7.4
WORKDIR /var/lib/rancher
RUN rm -rf /usr/share/rancher/ui-dashboard/dashboard*
COPY --from=builder /src/dist /usr/share/rancher/ui-dashboard/dashboard
```

**Result**
User is briefly redirected to `dashboard/home` before being redirected back to `/dashboard/auth/login?timed-out`.

**Expected Result**

User is logged in correctly and redirected to Dashboard homepage.

**Screenshots**

Immediately after initial login:
`/dashboard/auth/login?timed-out`
![image](https://github.com/rancher/dashboard/assets/143118052/21a86be1-3ffa-4781-ada9-c1f5ac69a21c)

**Additional context**

I have a customized Dashboard that we manually package and deploy with our Rancher instance. The customizations exclusively modify static assets (styles/images). I also am seeing the same problem with a fresh clone of v2.7.4 with 0 modifications.

Not sure if this is a bug in the dashboard or an issue with my deployment but any help would be much appreciated. Thanks!

**Comment by richard-cox** [comment]
I think a while back there was an issue when bringing up Rancher in docker (which we do not recommend for production) that was similar to this, however I think was resolved and hasn't been seen in a while. Could you try again with the latest version of Rancher? Does it always happen or only when the container has been recently brought up?

**Comment by richard-cox** [comment]
No response, closing
