### ISSUE TITLE
Resource modified handler fails

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9597]
**Setup**
- Rancher version: 2.7.7ish

**Describe the bug**
- When a user edits an existing kube resource and that resource has independently changed somewhere else we get a  409 conflict response from the PUT requests
- We have code in place handle this
  - the latest changes are fetched
  - we determine the diff between old and latest changes
  - we determine the diff between old and user changes
  - if there are the same changes in both diffs (conflicts) we should...
    - inform the user of the conflict
    - override the user changes with the latest changes in the form
    - user can then continue with their edits
  - if there is not the same changes in both diffs (no conflicts) we should
    - apply the latest changes to the user copy and attempt to save again
- however current code does not work
  - conflicting changes are not detected and we show the user the generic resource modified error messages
  - non-conflict changes are not applied and we show the user the generic resource modified error messages

**To Reproduce**
- conflicting changes
  - open browser A and browser B on the edit page for a pod
  - in browser A change the container image to "nginx:1" (don't do anything else)
  - in browser B change the container image to "nginx:2" (don't do anything else)
  - in browser A press save
  - in browser A wait pods list to be visible
  - in browser B promptly press save
- non-conflicting changes
  - same as above except
    - pick something that doens't churn, for instance a secrets
    - add labels to the pod in browser A and annotations to the pod in browser B

**Result**
- conflicting and non-conflicting changes are the same
  - edit page shows `Operation cannot be fulfilled on pods "asdsad": the object has been modified; please apply your changes to the latest version and try again`

**Expected Result**
- as described above

**Comment by richard-cox** [comment]
Caused by failure to locate `cleanForDiff` action in shell/plugins/dashboard-store/normalize.js handleConflict. 

Fix is to pass in the store namespace and dispatch with it and {root:true}

I also stumbled on another bug that caused the process to fail. shell/utils/object.js remove does not handle root level paths, it always expects there to be at least one parent - child relationship. Fix is simple there.

With all above in place the `conflict` use case is handled. However it seems like the non-conflicts case isn't. Still trying to get a successful save.

**Comment by sbulage** [comment]
Able to see the Operation cannot be fulfilled on pods.....See below screenshot.

![Screenshot from 2023-11-03 18-12-48](https://github.com/rancher/dashboard/assets/12134754/f92cf907-cc5f-4f0b-9eb6-920071146ffd)
