### ISSUE TITLE
I am not able to see the cluster in Rancher UI

### ISSUE THREAD

**Issue by faizanbashir** [rancher/dashboard#9604]
We have a setup that uses the Azure AD groups for permissions. I am a member of the admin group, but I can't see the clusters in Rancher UI.

What should I do to get the access?

**Comment by richard-cox** [comment]
- What version of Rancher are you using?
- What Rancher roles does your admin group have, anything global?
- Has the admin group been added as a member to the cluster?
- In your browsers Developer Tools window, can you see the cluster in the response to the network request to `/v1/provisioning.cattle.io.clusters`?

**Comment by richard-cox** [comment]
No update, closing
