### ISSUE TITLE
Statefulset losing volume yaml config after "Edit Config" on Rancher UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9607]
Internal reference: SURE-6816
Reported in 2.7.5

Issue description:
A user has a statefulset that has volumeClaimTemplates which contains a volume declaration. The volume is also declared in volumeMounts to be mounted and used later by Pods. When the user tries to edit the statefulset via "Edit Config" button, the volume declared in volumeMounts section disappears.
However, when edited via "Edit YAML" the behavior does not occur.

The user is not using the "Edit config" button to avoid data loss in a prod environment especially its data.

Business impact:
This is in a production environment

Troubleshooting steps:
- check yaml file whether it's valid or not
- used a simplified yaml to test in another cluster but no luck
- restarted Rancher deployment but no luck

Repro steps:
- create downstream cluster
- click "Import YAML" and paste the yaml file content then save
- go to Workloads > StatefulSets
- select the statefulset and click the 3-dotted menu then click "Edit Config"
- make a change, for example reduce replicas number to 1, then save
- check the statefulset again via "Edit Yaml"
- the volume declared via volumeClaimTemplates is gone in the volumeMounts section

Workaround:
Using the "Edit YAML" button instead to avoid the issue

Actual behavior:
Statefulset losing volume yaml config lines (volumeMounts) when edited using "Edit Config" button via Rancher UI

Expected behavior:
Statefulset must NOT lose volume yaml config lines (volumeMounts) when edited using "Edit Config" button via Rancher UI

Additional notes:
this has been reproduced and confirmed as it's a bug.

Screenshots:
![1._after_import_yaml_2023-08-23_11_31_22.png](https://zube.io/files/rancher/621c8a276bc9058111272d3b1f4d72c5-1-_after_import_yaml_2023-08-23_11_31_22.png)

![2._reduce_scale_2023-08-23_11_31_55.png](https://zube.io/files/rancher/cbeec3e5c0e77f2c0fa109eed26abadb-2-_reduce_scale_2023-08-23_11_31_55.png)

![3._edit_config_save_2023-08-23_11_32_01.png](https://zube.io/files/rancher/7cf4a084d8068dbc8159912e442cf26d-3-_edit_config_save_2023-08-23_11_32_01.png)

![4._after_edit_config_2023-08-23_11_32_15.png](https://zube.io/files/rancher/f18e0156dd288ca8bc54e0457760fc5e-4-_after_edit_config_2023-08-23_11_32_15.png)

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.8-head commit id 331d18b`
1. created downstream cluster
2. set up the necessary storage class.
3. created the persistent volumes.
4. created the persistent volume claims.
5. created the stateful set with the volume mounts.
6. edit config on statefulset
7. changed replicas to 1 (from 3)
8. saved changes
9. edit yaml on stateful set
10. volume yaml remains

<img width="637" alt="2023-09-14_15-08-51" src="https://github.com/rancher/dashboard/assets/89212856/7e9719e2-d5fb-4f99-b697-63220ec3db0c">
