### ISSUE TITLE
Have dashboard handle requestId parameter in login endpoint requests

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9608]
Is your feature request related to a problem? Please describe.
This is related to rancher/dashboard#8964. Currently, when using the rancher token command with a SAML provider (such as OKTA) the rancher CLI produces a URL for the user to initiate the login process inside of rancher. This uses the /login endpoint, which produces a login page for the old ember UI.

Going forward, the rancher CLI should not use this endpoint, and instead should use an equivalent page from the dashboard.

Describe the solution you'd like
The URL produced by the CLI should refer to a dashboard endpoint, like /dashboard/auth/login.

Describe alternatives you've considered
Other endpoints could be used, as long as they are not from the ember UI.

Additional context
Initial testing showed some issues with the /dashboard/auth/login endpoint. More testing will be needed to verify if this endpoint is suitable (or needs some modification).

### Update from https://github.com/rancher/rancher/issues/41651

@eliyamlevy spoke with @mantis-toboggan-md and after some investigation, they came to the conclusion that the solution is some updates to the Dashboard code to handle the case that the `/dashboard/auth/login/` endpoint receives a request with the requestId parameter. Currently the dashboard does not handle this parameter.

The solution is to add this case to the dashboard code, have it forward the request to the norman api (mirroring the ember flow) and then updating the login url to the dashboard one.

There shouldn't need to be any major changes to the CLI code.

**Comment by mantis-toboggan-md** [comment]
The relevant Ember code we need to replicate appears to be this: https://github.com/rancher/ui/blob/master/lib/shared/addon/saml/service.js#L12-L30

**Comment by mantis-toboggan-md** [comment]
The original issue requesting this functionality in the Ember UI is https://github.com/rancherlabs/rancher-security/issues/444

**Comment by nwmac** [comment]
@torchiaf I think there are 3 params that need to be passed through:

```
requestId
publicKey
responseType
```

I think in here - https://github.com/rancher/dashboard/blob/master/shell/components/auth/login/saml.vue - where it passes the body, the body needs to include the above parameters from the query string, if they are set there.
