### ISSUE TITLE
Warning for RKE2 custom clusters that have just a control plane and no worker nodes

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9609]
Internal reference: SURE-6777
Reported in 2.7.5

Issue description:
Users creating RKE2 custom cluster with just a control plane and no worker nodes results in a cluster that never deploys due to cattle-agent and fleet-agent having nowhere to deploy to. There should either be a warning that a cluster without workers will fail to deploy, or the cattle-agent and fleet-agent deployments should be exceptions to the control plane taint/toleration.

Business impact:
Some users like to create "placeholder" clusters with no actual workers, their workflow requires this.

Actual behavior:
Deployment of single node workerless cluster fails

Expected behavior:
Deployment of single node workerless cluster succeeds, or warns that it will fail.

Notes:
- Other deployments within the UI do show that creating clusters without worker nodes, so this is purely tied to custom clusters.
- However, custom clusters do have checkboxes that can allow workers to be skipped but there's no warning when if workers are unchecked:
![Screenshot 2023-08-16 at 7.23.59 AM.png](https://zube.io/files/rancher/a1dd06267524975a2900aa021ffac268-screenshot-2023-08-16-at-7-23-59-am.png)
- Based on that, it seems that some users require the warning label or will, bar red things, do something that leads to a broken configuration.

**Comment by torchiaf** [comment]
> For custom cluster, if the user unchecks 'Worker', we should show a warning banner underneath - we already have the message as we do show it in the RKE2 creation UI if the user does not add a worker to a cluster.
> 
> We should create an automated test for this.

@nwmac shouldn't we add the warning message for all the checkboxes ? This is the current behavior for custom RKE1 clusters:

![image](https://github.com/rancher/dashboard/assets/26394656/41705797-456d-497e-adb5-0da0f8e0727c)

**Comment by richard-cox** [comment]
Discussed with Neil, lets warn on just the worker role.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, create a custom RKE2 cluster, validate that a warning message appears when not all node roles are specified|

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.8-head` https://github.com/rancher/rancher/commit/c55d3344dc46525a860c712f868f1b7ab1826b1b.

**ENVIRONMENT DETAILS**
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/c55d3344dc46525a860c712f868f1b7ab1826b1b
- Rancher install: Docker

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, create a custom RKE2 cluster, validate that a warning message appears when not all node roles are specified|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, noted the banner is correctly when not all node roles are selected:
![validate](https://github.com/rancher/dashboard/assets/52591819/b2455ba3-9338-44cb-8577-9cb2a471c70b)
