### ISSUE TITLE
Define the accent color

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/dashboard#9611]
We think our accent color could be improved for better contrast and to give a different personality to the look of the overall UI.
<img width="436" alt="Screenshot 2023-08-29 at 09 18 44" src="https://github.com/rancher/dashboard/assets/6459624/9c958b23-9732-4fa9-8c60-0fb988dc77e8">

After being through a cycle of research, exploration, proposal, and discussion, the team decided that #4062B9 will be the new accent color.

The outcome of our work can be seen in this prototype:
https://xd.adobe.com/view/67a4bda1-c68f-42a5-991e-a9cb1f45528e-32f7/screen/bf856414-3b16-4e6c-8c56-3f8ea3486362

**Comment by ElvinPero** [comment]
I would be happy to work on it.

**Comment by nwmac** [comment]
Stale
