### ISSUE TITLE
Expose the option for setting graceful shutdown timeout for vSphere-node-driver RKE1/RKE2/K3s cluster

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#9620]
**Is your feature request related to a problem? Please describe.**

https://github.com/rancher/rancher/issues/42308 
SURE-3285
Internal design docs 

We are adding a new field named `gracefulShutdownTimeout` to the underlying vSphere node driver. Rancher has a mechanism to make the new field available in the `NodeTemplate` for RKE1 and `VmwarevsphereMachineTemplates` for RKE2/K3s. 

For the UI side, we would like expose the field for users to configure.  
Here are some information and requirements of the new field: 

Name | Graceful Shutdown Timeout
-- | --
Description | The time in seconds to wait before forcing deleting VMs in the infrastructure. Zero means disable graceful shutdown.
Data Type | integer
Value Range | >= 0
Location | RKE1: the new option should show in the creating/editing page for the vSphere node template.  REK2/K3S: the new option should show in the machine pool section on the cluster creation/editing page

RKE2/K3s 
- Endpoint: "/v1/rke-machine-config.cattle.io.vmwarevsphereconfigs/fleet-default/<pool-name>"
- Method: POST, PUT
- filed: ".gracefulShutdownTimeout"

RKE1
- Endpoint: "v3/nodetemplate/<name>"
- Method: POST, PUT
- filed: ".vmwarevsphereConfig.gracefulShutdownTimeout"

</div><br class="Apple-interchange-newline">

**Describe the solution you'd like**

In the case of  `NodeTemplate` for RKE1, the new field can probably be added under section `2. Scheduling` or another appropriate place. Note that the same form also shows up when editing an existing node template. 

![screencapture-rainbow-cp-dev-rancher-space-dashboard-c-manager-provisioning-cattle-io-cluster-create-2023-08-29-15_54_06](https://github.com/rancher/dashboard/assets/6218999/b65faaeb-499b-4210-82ac-ed223ad91295)

In the case of `VmwarevsphereMachineTemplates` for RKE2/K3s, the new field can be added next to the 	`Drain` option or another appropriate place. 
 
 
<img width="1865" alt="image" src="https://github.com/rancher/dashboard/assets/6218999/9d3a477a-4556-443c-86b0-647b0579069d">

**Describe alternatives you've considered**

N/A 

**Additional context**

N/A

**Comment by gaktive** [comment]
RKE1 will be Ember, RKE2 will be Vue.

**Comment by gaktive** [comment]
Before UI can start, we need the details of the field that the UI will need to set for both RKE1 and RKE2; what is the path to the field in the appropriate API call that the UI makes?

**Comment by jiaqiluo** [comment]
hi @gaktive, 
1. I think we are using the same vSphere system which is offline now. 
2. The issue description is updated to include that information. Please let me know if you have more questions.

**Comment by nwmac** [comment]
@gaktive This is too late for 2.8

**Comment by gaktive** [comment]
Pushing to Q1. @Sahota1225 let us know if this is needed sooner though time's running out for Q4.

**Comment by slickwarren** [comment]
I'm currently testing this feature in the backend, but I'm not sure how I can do this through rancher for rke2/k3s without the UI work. 

(v2.8.0-alpha2)

I tried manually editing the cluster's `machinePools[].dynamicClusterSpec` via the `view in API` after I created the cluster, however this did not result in the value for graceful shutdown being honored (the node is not gracefully shutdown through vsphere's ui).  

I was able to edit via the API for rke1 and observe the machine(s) gracefully shutdown, however this feels less than optimal to do thinking from the customer's point of view.

**Comment by richard-cox** [comment]
@slickwarren Think you'll need to manually edit the machine config associated with the provider / cluster.

For instance, for a loca DO cluster one of the machine pools has...
```
machineConfigRef:
          kind: DigitaloceanConfig
          name: nc-rc-rke2-pool1-g8xdp
``` 
For this case, I think (not sure) the resource to update would be `v1/rke-machine-config.cattle.io.digitaloceanconfigs/fleet-default/nc-rc-rke2-pool1-g8xdp`. That can be found in the upstream cluster's DigitalocenConfigs resource list.

Overall though, i'm not sure the parent issue can be closed without the dashboard issue being resolved. It's a lot to ask of the user to go through the steps above

**Comment by gaktive** [comment]
This was tested in 2.8.next1 and passed. QA can skip this if they feel they're over capacity based on other tests that haven't been run yet.

**Comment by izaac** [comment]
Validated the Graceful Shutdown option is exposed in the UI as expected on both RKE1 and RKE2/k3s.

Rancher version: `v2.9-37f6eebf662459addc96bd31f486d8573a281c27-head`

This is in since the 2.8.3 milestone. A quick validation was done for 2.9.0
