### ISSUE TITLE
Pods are not listed in daemonset detail page until the page is refreshed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#963]
**On master-head - commit id: `65a2b808c`**

- Login to Dashboard
- Cluster Explorer --> Workloads --> Overview --> Daemonsets --> Create --> Deploy a daemonset
- Click on the daemonset created
- User is navigated to the detail page.
- Section under pods is empty.
- Do a refresh of the page.
- the section now shows the pods.

**Comment by vincent99** [comment]
Ideally this should be done by finishing https://github.com/rancher/dashboard/issues/714#issuecomment-670428878 to get related resources efficiently instead of fixing whatever's wrong with getting them inefficiently.

**Comment by mantis-toboggan-md** [comment]
This should be fixed along with rancher/dashboard#780 now

**Comment by sowmyav27** [comment]
**On master-head - commit id: `33f755f18`**

- Login to Dashboard
- Cluster Explorer --> Workloads --> Overview --> Daemonsets --> Create --> Deploy a daemonset
- Click on the daemonset created
- User is navigated to the detail page.
- Pods are listed

<img width="1443" alt="Screen Shot 2020-09-16 at 9 36 29 PM" src="https://user-images.githubusercontent.com/26032343/93420848-b7a9d480-f864-11ea-80cc-ebfa04fa23da.png">
