### ISSUE TITLE
Cannot paste into textboxes under Advanced section

### ISSUE THREAD

**Issue by jakefhyde** [rancher/dashboard#9630]
**Setup**
- Rancher version: v2.7-head (8a18f16)
- Rancher UI Extensions: N/A
- Browser type & version: Chrome Version 116.0.5845.110 (Official Build) unknown (64-bit)

**Describe the bug**

Cannot paste into the additional kubelet args, additional controller manager args, additional API server args, or additional scheduler args prompts under the Advanced section during v2prov cluster creation.

**To Reproduce**

Try to paste into field

**Result**

Cannot paste

**Expected Result**

Should be able to paste

**Screenshots**

![image](https://github.com/rancher/dashboard/assets/33796120/3258b98a-f5fe-4787-988a-06e4af8558a4)

**Additional context**

**Comment by cnotv** [comment]
Issue does not happen when pasting multilines, so something must be wrong in that direction.
It can be reproduced also in Storybook, so this is a component (ArrayList) case issue.
https://rancher.github.io/storybook/?path=/story/components-arraylist--empty

Generic input component works fine.
https://rancher.github.io/storybook/?path=/docs/form-input--input

A regression unit test is required in this case.

**Comment by cnotv** [comment]
@yonasberhe23 closed due test automation.
