### ISSUE TITLE
[RFE] - request to clear out VPC/Subnet value (if configured) when changing the Region field for AWS Node driver v2prov clusters

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#9636]
**Is your feature request related to a problem? Please describe.**
When provisioning a downstream rke2/k3s AWS node driver cluster, if a VPC/Subnet is selected (for a particular region), then the Region field is changed, the VPC/Subnet value persists, but is now invalid, as the region has changed.

**Describe the solution you'd like**
Ideally, when the Region field is changed, the VPC/Subnet value (if configured) would be cleared out, allowing the user to re-select a value from the VPC/Subnets dropdown

**Describe alternatives you've considered**
An alternative solution could be to add form validation to prevent the creation of downstream v2prov AWS Node driver clusters, when the selected VPC/Subnet is not found in the desired Region selected (in the Machine Pools configurations)

**Additional context**
Without this enhancement, it is easier for users to get into a situation where their cluster won't provision, as they might expect.

**Comment by gaktive** [comment]
Feature complete for 2.8.0 is this week but this feels late to get in and needs some input from product on priority. However, this looks like a scenario that avoids sticky situations. @nwmac how does this sound to you?

**Comment by Josh-Diamond** [comment]
Ticket #9636 - Test Results - ✅ 
---

Verified on Rancher `v2.8-bc74a4bdec7164285a0d5893fb040a3109e83fc3-head`:
1. Fresh install of Rancher `v2.8-head`
2. Navigate to `Cluster Management > Create`, and select a VPC/Subnet from drop down
3. Change the `region`
4. Verified - selected VPC/Subnet value is cleared out upon changing `region`; as expected 🎉
