### ISSUE TITLE
AKS: Imported cluster showing invalid warning for Nodepool version upgrade

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#9637]
**Setup**
```
Rancher version: v2.7-e0566312558ca549dfdf8b6b47f2800da0c783a6-head
Browser: Chrome Latest
```

**Describe the bug**
AKS: Imported cluster showing invalid warning for Nodepool version upgrade. Even though CP version is same as Node pool version.

**To Reproduce**
- Create AKS clsuter using AZ console/CLI
- Import cluster into Rancher and wait for it to be Active
- Edit cluster and check Node pool Kubernetes version

**Screenshots**
CP Version:
![image](https://github.com/rancher/dashboard/assets/73099870/1fb3aa00-fe4f-457c-9f90-40630f16a584)

Nodepool version:
![image](https://github.com/rancher/dashboard/assets/73099870/d82458c6-afc1-468c-b8fd-13a956ad5289)

Found while validating https://github.com/rancher/rancher/issues/42496

**Comment by mantis-toboggan-md** [comment]
This appears to be fixed in 2.9.0 - I imported a cluster and do not see any notice about upgrading the node pool kubernetes version
![Screenshot 2024-07-24 at 2 39 42 PM](https://github.com/user-attachments/assets/9cb8dd41-6d7a-4f43-a6c4-ab2123f122da)

**Comment by gaktive** [comment]
Putting on to the 2.9.0 milestone though at this stage, if it's not a blocker, this could be tested from 2.9.next1.

@cpinjani in the future, be sure to put a milestone at least tied to a version that you discovered this bug in so it's on our project board.

**Comment by cpinjani** [comment]
@gaktive I'll make sure to put milestone while reporting an issue, thanks.

Validation passed on build: 
```
Rancher - v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head
Dashboard - release-2.9 e108b95
```
- Imported AKS cluster is not showing invalid warning for Nodepool version upgrade. 

![image](https://github.com/user-attachments/assets/d2f1fd2d-a0ea-4f0c-a0f7-aba2c07bec41)

- Imported AKS cluster shows valid warning for Nodepool version upgrade when new CP version is selected.

![image](https://github.com/user-attachments/assets/5b6cfdba-2a44-41ae-9dae-6d5c088ee999)
