### ISSUE TITLE
Workload - Updated Create/Edit Flow 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#964]
All resources are moving to the following creation workflow:

1. If there are subtypes for a resource, select the subtype. 
2. Define the resource with the tabs moved to a vertical sidebar. Ability to create from the form.
3. Ability to review the YAML and make changes before create. 

Edit Workflow:
1. Ability to either edit through form or through yaml from the menu action. 

https://xd.adobe.com/view/a6c990fb-2efd-4444-b999-96111772c11c-f39a/screen/4209c6d7-a395-4019-b2dd-da9d25d753a4

**Comment by jiaqiluo** [comment]
A bug is found during validating the creation workflow: https://github.com/rancher/dashboard/issues/1008
