### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9648]
We have some packages to update on dashboard before we ship our next version.

We did get a PR from @pjbgf to do this but based on how our UI works, we need to split those updates into separate ones for easier work. https://github.com/rancher/dashboard/pull/9439 for reference.

Some of these may require a Vue update, or depend on webpacks, which means we could look at those later. This could be coordinated with updating Vue libraries prior to Vue3.

- [x] axios: >=0.21.2
  - rancher/dashboard#9775
- [x] postcss: >=7.0.36
  - rancher/dashboard#9775
- [x] qs: >=6.7.3
  - Already compliant
- [x] loader-utils: >=1.4.1
- [ ] #12088
- [ ] #12090
- [x] semver: >=7.5.2
  - rancher/dashboard#9793
- [ ] #12105
- [x] word-wrap: >=1.2.4

**Comment by nwmac** [comment]
Note: We need to look at each in tern - not all can be done at this time.

**Comment by gaktive** [comment]
`yarn why` would help understand the dependencies' own dependencies. `yarn audit` can help too.

**Comment by richard-cox** [comment]
I've updated those we can do given vue-cli and where where we are for this release (see confluence rancher / dashboard dependencies for a full write up). I'll make this in to an epic and split out the ones that are done

**Comment by richard-cox** [comment]
I've jigged around the target milestone given what we're committed to

**Comment by richard-cox** [comment]
Linking dependent issue https://github.com/rancher/dashboard/issues/7653. Until we bump vue (specifically vue-cli) we can't progress this. Moving to v2.8.next2 to check status of that vue3 migration in next release

**Comment by richard-cox** [comment]
Given the vue3 bump this can now be re-evaluated

**Comment by rak-phillip** [comment]
I'm checking off `loader-utils` for the following reasons

1. This is a transitive dependency that is not explicitly declared as a dependency in dashboard
2. `loader-utils` is at 1.4.2  as of writing this comment

```
yarn why loader-utils

yarn why v1.22.19
[1/4] Why do we have the module "loader-utils"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "loader-utils@1.4.2"
info Has been hoisted to "loader-utils"
info Reasons this module exists
   - "workspace-aggregator-7f68b920-9183-44c5-9a85-c1d73de0033e" depends on it
   - Hoisted from "_project_#cache-loader#loader-utils"
   - Hoisted from "_project_#js-yaml-loader#loader-utils"
   - Hoisted from "_project_#@vue#cli-service#vue-style-loader#loader-utils"
   - Hoisted from "_project_#@vue#cli-service#@vue#vue-loader-v15#loader-utils"
   - Hoisted from "_project_#@cypress#webpack-dev-server#html-webpack-plugin-4#loader-utils"
=> Found "csv-loader#loader-utils@2.0.4"
info This module exists because "_project_#csv-loader" depends on it.
=> Found "frontmatter-markdown-loader#loader-utils@2.0.4"
info This module exists because "_project_#frontmatter-markdown-loader" depends on it.
=> Found "worker-loader#loader-utils@2.0.4"
info This module exists because "_project_#worker-loader" depends on it.
=> Found "thread-loader#loader-utils@2.0.4"
info This module exists because "_project_#@vue#cli-service#thread-loader" depends on it.
=> Found "@vue/cli-plugin-babel#loader-utils@2.0.4"
info Reasons this module exists
   - "_project_#@rancher#components#@vue#cli-plugin-babel#babel-loader" depends on it
   - Hoisted from "_project_#@rancher#components#@vue#cli-plugin-babel#babel-loader#loader-utils"
=> Found "@vue/cli-plugin-typescript#loader-utils@2.0.4"
info Reasons this module exists
   - "_project_#@rancher#components#@vue#cli-plugin-typescript#babel-loader" depends on it
   - Hoisted from "_project_#@rancher#components#@vue#cli-plugin-typescript#babel-loader#loader-utils"
Done in 0.56s.
```

**Comment by rak-phillip** [comment]
Marking `word-wrap` as completed. At this time, `word-wrap` is at 1.2.5. It is also a transitive dependency.  

```
➤ yarn why word-wrap

yarn why v1.22.19
[1/4] Why do we have the module "word-wrap"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "word-wrap@1.2.5"
info Reasons this module exists
   - "_project_#eslint#optionator" depends on it
   - Hoisted from "_project_#eslint#optionator#word-wrap"
   - Hoisted from "_project_#browser-env#window#jsdom#escodegen#optionator#word-wrap"
info Disk size without dependencies: "24KB"
info Disk size with unique dependencies: "24KB"
info Disk size with transitive dependencies: "24KB"
info Number of shared dependencies: 0
Done in 0.62s.
```

**Comment by rak-phillip** [comment]
Moving this to QA Review - all dependencies listed in the epic now satisfy their requirements.

**Comment by yonasberhe23** [comment]
nothing for QA to do here. moving to done
