### ISSUE TITLE
Opening various configuration pages in Rancher 2.7.5 fails with "Cannot read properties of undefined (reading 'nameDisplay')"

### ISSUE THREAD

**Issue by stranljip** [rancher/dashboard#9651]
**Setup**
- Rancher version: Rancher 2.7.5 installed on rke2 1.25
- Rancher UI Extensions: none
- Browser type & version: any installed browser (tested with Chrome 116, FF 117, Edge 116)

**Describe the bug**
Since a couple of days we see that it is no longer possible to open some pages in Rancher. Most prominently this happens with the configuration view for some (not all) of our rke2 clusters. The error message is `Cannot read properties of undefined (reading 'nameDisplay')`

**To Reproduce**
- Go to "Cluster Management"
- Either open the configuration page via cluster view by clicking on the cluster name and then opening the 3-dot menu and select "Edit config" or select "Edit config" via the 3-dot menu next to the cluster from the overview page directly.

**Result**
- The page opens, reloads 1 or 2 times and shows a white page with the error message "Cannot read properties of undefined (reading 'nameDisplay')"

- The same symptom occurs in some (not all) namespaces of an affected cluster when trying to edit the namespace details

**Expected Result**
- the page is loaded and I am able to see and edit the desired options

**Screenshots**
<img width="708" alt="Screenshot 2023-09-05 at 12 55 33" src="https://github.com/rancher/dashboard/assets/8318307/47828014-78f2-4252-9bbb-eac12a774ece">

**Additional context**
- There are no errors in the Rancher logs (that I could find)
- the same error that I see in the UI can be found in the console (attached)
- all downstream clusters working fine
- Export from Dev console: [rancher-1693900843771.log](https://github.com/rancher/dashboard/files/12522548/rancher-1693900843771.log)

**Comment by stranljip** [comment]
Hi @richard-cox - thank you for your detailed answer! Concerning your remarks:
- The reloads is repro step is a loading message on page, and not a manual refresh of the page? --> yes, there is no manual reload
- You see the exact same error in the edit namespace context? --> The part "Cannot read properties of undefined (reading 'nameDisplay')" was the same, for the rest I am not 100% sure. Since I now deleted the namespace, I cannot reproduce this :-/
- Are there any failed network requests? --> all responses after requesting the configuration page have the status 200
- Has anything happened to the cluster since the error started showing that would remove resources? --> No, there were no changes or incidents 
- Has any change been made to the cluster configuration since the error started showing (for instance scaling nodes)? --> No
- Is the cluster provisioned on a public cloud provider or bare metal? --> rke2 cluster on-site with VMWare provisioner

**Comment by richard-cox** [comment]
The error handling has been fixed in
- 2.7.next-1 - https://github.com/rancher/dashboard/issues/9979
- 2.8.0 and later 2.8.x releases - https://github.com/rancher/dashboard/issues/9542 
- 2.9.0 given we branched after 2.8.0

The error itself... please open a new gh issue if there are any further problems in the future
