### ISSUE TITLE
Missing of spacing to min-width in pagination area

### ISSUE THREAD

**Issue by ChrisEdS** [rancher/dashboard#9653]
**Describe the bug**
In some cases the minimum width of the pagination text (200px) may not be sufficient. If the text is wider, the text will hit the navigation elements directly. To output a tidy display in this case, a spacing of 20px would be ideal.

**Screenshots**
<img width="684" alt="image" src="https://github.com/rancher/dashboard/assets/33026403/20dfd71f-48b5-47cc-9abd-8ac03c7c7a5a">

**Additional context**
I will provide a pull request

**Comment by richard-cox** [comment]
I think this might be a harvester rather than dashboard issue. See https://github.com/rancher/dashboard/pull/9654#issuecomment-1737837207

**Comment by richard-cox** [comment]
Closing as per PR
