### ISSUE TITLE
Unit Testing `smallIdentifier()`

### ISSUE THREAD

**Issue by scures** [rancher/dashboard#9658]
**Describe the solution you'd like**

There's a new function as part of the new `app-bar` that takes a string (ex: `www-aa-cc`) and generates a small version of it (`wac`). We want to move it outside of the component and create the proper tests for it.

## AC:
- Move the function outside of the component to `utils`
- Create tests to cover the scenarios described inside the `smallIdentifier()`
- If there's room for improvement, please do so (allow more scenarios, things like `foo-123` and `foo-133` could return something different instead of both returning `F13`) 

**Additional context**

Example:
![image](https://github.com/rancher/dashboard/assets/88777903/8ef12a8f-3395-477e-aa0b-16e9379bc87d)

Part of https://github.com/rancher/dashboard/pull/9560

```js
/**
 * Shortens an input string based on the number of segments it contains.
 * @param {string} input - The input string to be shortened.
 * @returns {string} - The shortened string.
 * @example smallIdentifier('local') => 'lcl'
 * @example smallIdentifier('word-wide-web') => 'www'
     */
```

**Comment by bisht-richa** [comment]
Some more input for the test from Richard. Please check below comment :
https://github.com/rancher/dashboard/pull/9674#discussion_r1324432677
