### ISSUE TITLE
New Side Nav Visual Bugs

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9659]
**Setup**
- Rancher version: pre-2.8.0

**Describe the bug**
Following on from https://github.com/rancher/dashboard/pull/9582

- General
  - Menu items outside of groups should be left aligned with group names
    - these previously had icons which meant they kind of aligned with the group names. now there's no icons they're not aligned
    - ![image](https://github.com/rancher/dashboard/assets/18697775/c7b759ba-ee45-4c01-a711-e24b75f95dd8)
  - Best seen in Cluster Management.
    - Items at top with no group should not have a bottom margin (margin wise they should be treated the same as closed groups) 
      - ![image](https://github.com/rancher/dashboard/assets/18697775/775dfff9-bd59-42ed-b570-27ceae203d74)
      - note the gap betweens drivers and rke1 config, which is not between rke1 config and advanced
    - Group labels are not vertically centrally aligned. This is best seen on the Node Templates page and the `RKE1 Configuration` group is closed
      - ![image](https://github.com/rancher/dashboard/assets/18697775/74ae3797-22eb-4a51-93d6-a79cfdaaef51)
  - Best seen in Cluster Explorer.
    -  The backgound for open groups should not include the bottom margin
      - ![image](https://github.com/rancher/dashboard/assets/18697775/cefa4906-1a65-4138-a7c9-662d4053d8ee)
      - note the light grey area under the hovered over `Events` entry
  - All menu items are background highlighted for 
    - Users & Authentication
    - Global Settings
    - Global Configuration (requires FF `legacy` enabled)
    - Cluster Management top level groups
    - Continues Delivery - dashboard, git repos, clusters and cluster groups
    - ![image](https://github.com/rancher/dashboard/assets/18697775/15b7680a-2437-4752-b0a4-d5038f7d28be)
- Cluster Explorer
  - Custom nav links aren't the same size as other links
      - ![image](https://github.com/rancher/dashboard/assets/18697775/e80dbba8-d8b6-4586-84e7-410c553c1b46)
      - Note - these are shown by creating `ui.cattle.io.navlink` resources in the cluster. note that when adding a `group name` the menu item is different to those with out it
  
Question
- What's the plan to connect the namespace icon to the namespace filter?

Discussion
- The highlight colours (current group & current menu item) are quite bold in dark mode. We might need to consider toning them down
  - ![image](https://github.com/rancher/dashboard/assets/18697775/909fbf94-466f-4ec5-8dcf-3cc07def633f)
- We might also need to tone down the colour of current menu item in light mode
  - ![image](https://github.com/rancher/dashboard/assets/18697775/cc864dc1-1832-4f51-a812-46225d51cc1e)

**Comment by richard-cox** [comment]
Sorry, late entry. The increase in burger menu and side nav now result in much less horizontal space resulting in the following

![image](https://github.com/rancher/dashboard/assets/18697775/a7f45273-9724-48c5-bfe8-1a48e91996c4)

vs

![image](https://github.com/rancher/dashboard/assets/18697775/09c81683-178a-4970-a5a6-28986073e3dc)

We probably need to `word-break: break-all;` in the name column

**Comment by valaparthvi** [comment]
Noticed one more bug where the side nav overlaps with the menu.
![Screenshot from 2023-09-11 14-40-37](https://github.com/rancher/dashboard/assets/11015077/785100bf-a75c-4e1e-9b34-5680a3d71817)

**Comment by valaparthvi** [comment]
>I couldn't reproduce that though. Could you create a separate issue with details in the issue template?

I am using rancher-latest with image `v2.8-head` here.

![Screenshot from 2023-09-11 15-38-18](https://github.com/rancher/dashboard/assets/11015077/5d4c8d02-9a1a-4041-b472-c1e05982d031)

**Comment by sbulage** [comment]
I have verified most of the issues mentioned in the description. see below screenshots.

**1. Dark mode**
![Screenshot from 2023-11-03 16-22-35](https://github.com/rancher/dashboard/assets/12134754/1e3033de-b451-4092-983b-26ce75ad90b7)
---------------------------------------------------

**2. Continuous Delivery**
![Screenshot from 2023-11-03 16-09-29](https://github.com/rancher/dashboard/assets/12134754/21a38ad3-bddf-403d-94e3-2c7c01ea6496)

---------------------------------------------------
**3. Custom Navigation links and Groups** 
![Screenshot from 2023-11-03 16-20-10](https://github.com/rancher/dashboard/assets/12134754/c555629d-df1c-437b-a714-dd548431701b)

---------------------------------------------------
**4. Cluster explorer space and alignment**
![Screenshot from 2023-11-03 15-51-56](https://github.com/rancher/dashboard/assets/12134754/83e29215-71e4-486d-9725-5c2b1bc164e4)
