### ISSUE TITLE
Error: `Cannot read properties of undefined (reading 'find')`seen after Scaling down nodes in a nodepool

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#9665]
**Setup**
- Rancher version: 2.7-head commit id: `787c056`
- Browser type & version: Chrome

**Describe the bug**
Error: `Cannot read properties of undefined (reading 'find')`seen after Scaling down nodes in a nodepool

**To Reproduce**

- Deploy a node driver k3s cluster - 1 node pool all roles, 1 nodepool - 2 CP nodes, 1 nodepool with 2 worker nodes
- Once the cluster is Active, select one CP only node and click on `Scale Down`
- Select the other CP only node  and click on `Scale Down`
- The page then loads and shows `Cannot read properties of undefined (reading 'find')`

<img width="671" alt="Screen Shot 2023-09-07 at 5 36 29 PM" src="https://github.com/rancher/dashboard/assets/26032343/dfd4da86-9205-429f-a12d-8c4c1529eea5">

**Expected Result**
No error should be seen.

**Console output:**
```
Cannot read properties of undefined (reading 'find')


e.forEach.console.<computed> | @ | console.js:31
-- | -- | --
  | (anonymous) | @ | client.js:111
  | p | @ | regeneratorRuntime.js:44
  | (anonymous) | @ | regeneratorRuntime.js:125
  | (anonymous) | @ | regeneratorRuntime.js:69
  | r | @ | asyncToGenerator.js:3
  | s | @ | asyncToGenerator.js:22
  | (anonymous) | @ | asyncToGenerator.js:27
  | (anonymous) | @ | asyncToGenerator.js:19
  | (anonymous) | @ | client.js:113
  | Hn | @ | vue.runtime.esm.js:3031
  | Bn | @ | vue.runtime.esm.js:3008
  | Tn.e._render | @ | vue.runtime.esm.js:2687
  | r | @ | vue.runtime.esm.js:3875
  | e.get | @ | vue.runtime.esm.js:3446
  | e.run | @ | vue.runtime.esm.js:3522
  | Jr | @ | vue.runtime.esm.js:4121
  | (anonymous) | @ | vue.runtime.esm.js:3143
  | Kn | @ | vue.runtime.esm.js:3065
  | Promise.then (async) |   |  
  | qn | @ | vue.runtime.esm.js:3090
  | Jn | @ | vue.runtime.esm.js:3155
  | ni | @ | vue.runtime.esm.js:4207
  | e.update | @ | vue.runtime.esm.js:3513
  | e.notify | @ | vue.runtime.esm.js:720
  | set | @ | vue.runtime.esm.js:963
  | Mi.Fi.set | @ | vue.runtime.esm.js:5356
  | setBulkActionOfInterest | @ | index.vue:799
  | mouseover | @ | index.vue:1
  | Un | @ | vue.runtime.esm.js:3017
  | n | @ | vue.runtime.esm.js:1815
  | La.o._wrapper | @ | vue.runtime.esm.js:7473


```

**Comment by susesgartner** [comment]
Ticket #9665 - Test Results - ✅ PASS
---
Verified with a Docker install of Rancher `v2.8-head`:
---
 
Scenario 1: Validate that no error page is displayed
---
1. Deploy a node driver k3s cluster - 1 node pool all roles, 1 nodepool - 2 CP nodes, 1 nodepool with 2 worker nodes
2. Once the cluster is Active, select one CP only node and click on Scale Down
3. Select the other CP only node and click on Scale Down
 
Results: Scale down works properly and no undefined page shows up.
