### ISSUE TITLE
More Design Issues - mostly service and some other areas

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#967]
**Node List**

- [x] No matter how wide I stretch the screen/table, this RAM column keeps looking like this:

<img width="438" alt="Screen Shot 2020-08-05 at 2 23 06 PM" src="https://user-images.githubusercontent.com/11410997/89465599-3a4c5980-d727-11ea-8ae7-23fc030f452f.png">

**Create Workflow**
- [x] The background of the selected tab on the tab list is too light in light mode

<img width="1114" alt="Screen Shot 2020-08-05 at 2 24 40 PM" src="https://user-images.githubusercontent.com/11410997/89465736-7384c980-d727-11ea-8934-46c81ae14e7e.png">

- [x] There is a weird border that sometimes shows up on the tab list but is sometime hidden. It's white in dark mode and white in light mode which makes it invisible in light mode

<img width="423" alt="Screen Shot 2020-08-05 at 2 27 32 PM" src="https://user-images.githubusercontent.com/11410997/89465977-df673200-d727-11ea-8c10-093a72d176a6.png">
<img width="370" alt="Screen Shot 2020-08-05 at 2 27 38 PM" src="https://user-images.githubusercontent.com/11410997/89465983-e0985f00-d727-11ea-85bb-64c7be0c2c15.png">

**DetailTop**
- [x] The spacing isn't equal between the dividing lines and content when there are no Annotations

<img width="1039" alt="Screen Shot 2020-08-05 at 2 40 31 PM" src="https://user-images.githubusercontent.com/11410997/89467000-aaf47580-d729-11ea-9e16-0ee9e18dc3c7.png">

**Service Create/Edit Page**

- [x] Padding between Name, Namespace Description and the Tabs seems too tall
<img width="1013" alt="Screen Shot 2020-08-05 at 2 49 58 PM" src="https://user-images.githubusercontent.com/11410997/89467700-f3f8f980-d72a-11ea-94a9-80d8d7b1dd82.png">

- [ ] Spacing around boxes in the port rules is too skinny

<img width="792" alt="Screen Shot 2020-08-05 at 2 46 30 PM" src="https://user-images.githubusercontent.com/11410997/89467475-77feb180-d72a-11ea-908c-ba139529fcbc.png">

- [x] The styling of these banners/alerts are completely different. Different border widths. Different padding around text. The padding from the top of the tab to the banner is also inconsistent. The different tabs are ListenerIPs, Selectors and Session Affinity. 

Prefer the border and padding of the yellow warning banner. 
Prefer the placement of the grey banner inside the tab. 

Warning Banner
<img width="1089" alt="Screen Shot 2020-08-05 at 2 26 11 PM" src="https://user-images.githubusercontent.com/11410997/89465861-aaf37600-d727-11ea-9515-f9cb1d60362e.png">

Normal Banner
<img width="1096" alt="Screen Shot 2020-08-05 at 2 26 39 PM" src="https://user-images.githubusercontent.com/11410997/89465878-b0e95700-d727-11ea-9ca9-870ae1f68763.png">

- [x] Adding External IPs is all weird (under listener IPs tab) for light and dark mode
- [x] When fixing how to add external IPs, can the text box of the IP line up with the Cluster IP text box? 
Note: It looks like Port Rules, KeyValues are using one type of grid/table while external IPs are using the table format, which might be why it's looking off? 

Light Mode

<img width="523" alt="Screen Shot 2020-08-05 at 2 47 44 PM" src="https://user-images.githubusercontent.com/11410997/89467560-a9777d00-d72a-11ea-8a38-5cb473cfc586.png">

Dark Mode
<img width="535" alt="Screen Shot 2020-08-05 at 2 48 31 PM" src="https://user-images.githubusercontent.com/11410997/89467607-c01dd400-d72a-11ea-930e-198d4d71c128.png">

**Comment by lvuch** [comment]
" Spacing around boxes in the port rules is too skinny" --- needs a dev to convert to grid not table

**Comment by lvuch** [comment]
"Adding External IPs is all weird (under listener IPs tab) for light and dark mode" --- needs more info

**Comment by tfiduccia** [comment]
@lvuch Not sure where this is merged... but it's not on master?  The top few seem to be there, but starting at the DetailTop issue down, they aren't there?

**Comment by tfiduccia** [comment]
Fixed - moving Port rules to it's own bug
