### ISSUE TITLE
APP Bar overlaps with the cluster management/virtualization/CD menu.

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#9673]
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:
![Screenshot from 2023-09-11 15-38-18](https://github.com/rancher/dashboard/assets/11015077/b1776460-c594-472c-9cd9-7c71277df1dc)

**Describe the bug**

The new APP Bar overlaps with the menu. This overlap happens with all the menu.

**To Reproduce**

1. Use rancher-latest with rancherImageTag=v2.8-head.
```sh
helm upgrade --install rancher --devel rancher-latest/rancher --namespace cattle-system --set hostname=$hostname --set replicas=1 --set bootstrapPassword=adminadmin --create-namespace --set rancherImageTag=v2.8-head 
```
2. Visit Cluster Management/Virtualization Management/Fleet page.

**Result**
1. The APP Bar overlaps with the menu.

**Expected Result**

1. The APP Bar should not overlap any menu.

**Screenshots**
![Screenshot from 2023-09-11 14-40-37](https://github.com/rancher/dashboard/assets/11015077/785100bf-a75c-4e1e-9b34-5680a3d71817)

**Additional context**

_Originally posted by @valaparthvi in https://github.com/rancher/dashboard/issues/9659#issuecomment-1713486111_

**Comment by richard-cox** [comment]
@valaparthvi could you fill in the bug issue template?

**Comment by richard-cox** [comment]
@valaparthvi Specifically what browser you're using, and if you have any Extensions installed?

**Comment by richard-cox** [comment]
Ah, think i've got it, it's a firefox thing

**Comment by richard-cox** [comment]
@bisht-richa whilst @scures's away, can you take a look? The app bar has issues in FireFox

**Comment by bisht-richa** [comment]
Firefox does not support pseudo-class has() by default and that is why the app bar is having an overlapping issue and also not working for highlight navigation groups when child items are selected.

**Comment by valaparthvi** [comment]
I tested this on rancher v2.8-f9bb34da1f2f4e3c8c8908047a53c671126384a0-head, and it works as expected. Thank you for the quick fix!

Feel free to close the issue.

**Comment by valaparthvi** [comment]
Is there any additional process that needs to be done on this issue? If not, I'll close the issue, or feel free to do so :)

**Comment by richard-cox** [comment]
Happy to close this if you are, and thanks for finding this bug!
