### ISSUE TITLE
Errors when editing chart yaml not fully visible

### ISSUE THREAD

**Issue by nickwsuse** [rancher/dashboard#9680]
Setup
Rancher version: 2.7-head

Describe the bug
If there are a lot of issues with the chart yaml when editing, the errors at the bottom of the screen are cut off and the user can't see them all as the page won't scroll. The user could still fix some errors and save again to shorten the list and see more errors, but that's not the greatest UX.

To Reproduce
1. Deploy a Rancher 2.7-head cluster
2. On local or downstream, go to install a chart
3. Click the Edit YAML button
4. Make a bunch of errors in the yaml
5. Click Save

Result
Error list is shown, but cut off at the bottom if there are more than a few errors

Expected Result
Page to be scrollable with full error list shown

**Comment by kwwii** [comment]
![image](https://github.com/rancher/dashboard/assets/617368/aa76e505-e649-46bc-b14d-05ff862048eb)
From the issue above ^^^

**Comment by bisht-richa** [comment]
I tried to reproduce the bug but I can not see the scrolling issue

https://zube.io/files/rancher/8edf10182a8dba4ea4dbd6a7b66c2f33-screen-recording-2023-10-18-at-12-18-23.mov

**Comment by bisht-richa** [comment]
This bug has been resolved in 2.8
