### ISSUE TITLE
No matching clusters when all clusters are pinned

### ISSUE THREAD

**Issue by bisht-richa** [rancher/dashboard#9683]
**Describe the bug**

If the user pins all clusters the separator line is shown and then the text No matching clusters,
When there's no filter text and all clusters are pinned we just shouldn't show that line and text.

**Screenshots**

![267289583-0992ce11-309f-4501-aa97-a2db5d9ff180](https://github.com/rancher/dashboard/assets/18264463/ab28137f-0cef-4070-8c5d-3374128ca739)

**Comment by richard-cox** [comment]
@cnotv , @bisht-richa this issue had no milestone and was languishing in the `To Test` column (which means no-one would look at it).

I've added a MS, and i think now the correct zube column for `dev automation` is the new `QA Review`

**Comment by cnotv** [comment]
The Zube bot reopened the issue. This is not for QA.

**Comment by richard-cox** [comment]
@cnotv i think it's still to be announced, but issues labelled as `dev automate` will go to the `QA Review` column.

the github bot re-opened the issue given it didn't know about dev automate, i think that's now resolved

**Comment by cnotv** [comment]
Good to know.

**Comment by izaac** [comment]
Automation coverage is here https://github.com/rancher/dashboard/pull/9864  
Closing as the automation coverage looks right.
