### ISSUE TITLE
Expose Raw Field Options in vSphere Cluster Form

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#9700]
## Description

In the vSphere form, options for fields often have user-readable labels, such as displaying "Datacenter" as the label while the actual value expected is "/Datacenter". This can lead to discrepancies when users reference these fields and options to populate their Terraform configuration. Consequently, the value provided for `datacenter` in the Terraform config may not match the expected value of "/Datacenter" in the form.

When working with a vSphere cluster in Rancher, users should have the option to view the raw, unprocessed options for fields, rather than just the user-readable labels. This additional visibility will help users correctly configure their Terraform scripts to match the expected values in the Rancher form.

**Comment by richard-cox** [comment]
Adding milestone

**Comment by izaac** [comment]
This was covered by the QA validation of 2.8-next on March. https://github.com/rancher/dashboard/issues/10550#issuecomment-2009949176

I did a quick validation pass on `v2.9-37f6eebf662459addc96bd31f486d8573a281c27-head` for the Manual provisioning part using the UI.
Pass, meeting the expectation.
