### ISSUE TITLE
Issue with font size in the side menu

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#9703]
**Setup**
- Rancher version: `v2.8-9f9275cdfb5ce833802353a35935a0cc6a578f7a-head`
- Browser type & version: Chrome

**Describe the bug**
Issue with font size in the side menu for `RKE1 Configuration` and `Advanced`

**To Reproduce**
Deploy Rancher 2.8-head

**Result**
`RKE1 Configuration` and `Advanced` appear quite large

**Expected Result**
`RKE1 Configuration` and `Advanced` should be smaller - Font size - 14px instead of 16px

**Screenshots**
<img width="768" alt="Screen Shot 2023-09-13 at 6 23 59 PM" src="https://github.com/rancher/dashboard/assets/26032343/39287e0e-2460-4595-a23c-2ed7cfc1b03c">

**Comment by richard-cox** [comment]
This is on the list to bring up with the UX team. The size of top level menu items, groups or leaf entries, should be consistent

**Comment by sbulage** [comment]
Able to see all string in the same font, see below screenshot.

![Selection_125](https://github.com/rancher/dashboard/assets/12134754/917c5083-0e62-4628-b41c-2d0f41464e8d)
