### ISSUE TITLE
pkg/rancher-components/StringList: add bulk addition

### ISSUE THREAD

**Issue by s0nea** [rancher/dashboard#9707]
https://github.com/rancher-sandbox/rancher-desktop/issues/5344 requires a bulk addition option to be added to the string list component. The bulk addition makes it easier to pass a bunch of data to the component at once. 

Features:

* Bulk addition can be enabled and disabled
* The delimiter can be defined for each component individually
* By passing a string to the input field, the string will be split by the delimiter
* It won't accept the string (and show an error), if there is a duplicate within the string itself and also in comparison to other entries that are already on the list
* Once enabled, the bulk addition applies to the add mode as well as the edit mode

Required property:

`bulkAdditionDelimiter`: Enables bulk addition and defines the delimiter to split the input string. `null` by default.

**Comment by richard-cox** [comment]
There's something similar in the KeyValue component (`onPaste`). Not sure if that could be used, or there's enough crossover for something common?

**Comment by s0nea** [comment]
> There's something similar in the KeyValue component (onPaste). Not sure if that could be used, or there's enough crossover for something common?

Thank you for mentioning it! I created a draft PR https://github.com/rancher/dashboard/pull/9709. I think the KeyValue component is slightly different from the StringList. However there might be something in common we can generalize. If we identify something sensible, I'm happy to improve my PR accordingly.
