### ISSUE TITLE
Deleting multiple clusters confirmation could be more generic

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#9708]
**Is your feature request related to a problem? Please describe.**

While deleting multiple clusters, the confirmation only asks to enter name of the first selected cluster.
**Describe the solution you'd like**

I believe the confirmation could be more generic where it would ask for a simple verb such as "Delete" when attempting to delete multiple clusters.

**Describe alternatives you've considered**

**Additional context**

![Screenshot from 2023-09-14 15-23-18](https://github.com/rancher/dashboard/assets/11015077/975b0be4-fda8-419b-a77f-e4a4179dbbf9)

**Comment by richard-cox** [comment]
There's cross over with https://github.com/rancher/dashboard/issues/6260.

The root problems are
- how to inform the user of the resources they are going to delete, specifically if there are multiple
- how to confirm with the user that they are happy for the resources to be deleted

Gonna tag both with UX

**Comment by kwwii** [comment]
This behaviour is consistent with github and other well known UIs. Closing this as I don't think we want to change it
