### ISSUE TITLE
Creating a ClusterRoleTemplateBinding with a non-existent user breaks the Cluster Membership page

### ISSUE THREAD

**Issue by JonCrowther** [rancher/dashboard#9729]
**Setup**
- Rancher version: dev-2.8 (also on 2.7.7)
- Rancher UI Extensions: None
- Browser type & version: Firefox

**Describe the bug**
If you create a CRTB that does not have a user that exists, when you open the Cluster Membership page the list of members will not load. Doing the same for PRTBs does not cause an issue in the Project Membership page. Also, if you use a field other than userName, such as userPrincipalName it doesn't cause the UI to break.

**To Reproduce**

With public API in 2.8.0:

1. Create a Cluster Role Template in the Users & Authentication tab
2. Open a kubectl shell for your local cluster
3. Apply the following CRTB via kubectl apply -f crtb.yaml

```
apiVersion: management.cattle.io/v3
kind: ClusterRoleTemplateBinding
metadata:
  name: test-crtb
  namespace: local
clusterName: local
roleTemplateName: <clusterRoleTemplate.Name>
userName: fake-user
```

Alternatively, this can be done through the Norman API in 2.7.7:
1. Create a Cluster Role Template in the Users & Authentication tab
2. Use the following curl command:
```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
"${RANCHER_URL}/v3/clusterroletemplatebindings" -d \
'{  
    "clusterId": "local",  
    "groupId": "",  
    "groupPrincipalId": "",  
    "name": "",  
    "namespaceId": "",  
    "roleTemplateId": "${ROLE_TEMPLATE}",  
    "userId": "fake-user",  
    "userPrincipalId": ""  
}'

```

**Result**

Go to the "Cluster and Project Members" tab and see that the list of Cluster Memberships won't populate any members, not even those previously visible.

**Expected Result**
All the members should be listed, and if the user doesn't exist use the same image from PRTBs:
![image](https://github.com/rancher/dashboard/assets/9119124/cbb51cd3-597c-44ad-bbe1-6e51c2365cf0)

**Screenshots**
What the broken UI looks like:
![image](https://github.com/rancher/dashboard/assets/9119124/619b1875-2f3b-40ca-9a39-3f7583f8de44)

**Additional context**
Issue in rancher/rancher with some additional context and more screenshots:
https://github.com/rancher/rancher/issues/42822

**Comment by dasarinaidu** [comment]
I have validated this issue on `v2.8-01127d844339ea8ab498f334121e2956be610409-head`, the issue got fixed and closing the issue.
