### ISSUE TITLE
Allow `Change Workspace` action for non-RKE1 clusters if (to be introduced) feature flag is enabled

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#9730]
Per https://github.com/rancher/dashboard/issues/7734 `Change Workspace` action is hidden for non-RKE1 clusters.

The current plan is to implement https://github.com/rancher/rancher/issues/36132 on the back-end however we want to keep the feature behind the feature flag `provisioningv2-fleet-workspace-back-population` so it's "opt-in".

As part of this issue, it requested to enable back the `Change Workspace` action for non-RKE1 clusters if that feature flag is enabled.

**Comment by richard-cox** [comment]
See https://github.com/rancher/dashboard/issues/9764 for more details

**Comment by snasovich** [comment]
FYI feature name is `provisioningv2-fleet-workspace-back-population` - see https://github.com/rancher/rancher/pull/42955/files#diff-2f6213e2bd15bb256be4ed430e664c08612e86384445be797a20d5f56d48d101R117

**Comment by richard-cox** [comment]
Waiting on confirmation FF exists - https://github.com/rancher/rancher/issues/36132#issuecomment-1743411778

**Comment by slickwarren** [comment]
tested on v2.8-head (fc12e7d): (enable the new flag `provisioningv2-fleet-workspace-back-population` to enable this experimental feature)
* transfer node driver rke1 cluster (should not be affected, existing behavior) -- pass
* transfer node driver rke2 cluster to new workspace -- pass
* transfer node driver k3s cluster to new workspace -- pass
* transfer custom rke2 cluster to new workspace -- TBD
* transfer custom k3s cluster to new workspace -- TBD

deploy rke2, k3s, rke1 on version of rancher that doesn't support the new feature, then upgrade rancher, enable the flag, and test changing workspaces: TBD

**Comment by slickwarren** [comment]
tested this on v2.7.8 -> v2.8-head (2e6895d)
* transfer custom rke2 cluster to new workspace -- pass
* transfer custom k3s cluster to new workspace -- pass

this was tested on both rke1 non-hardened local cluster and rke2 hardened local cluster.
