### ISSUE TITLE
Allow extensions to add products to an existing top level menu item

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#9733]
Similar to how the Kubewarden extension adds a 'product' within the explorer side nav, we need a way of adding an extension product within another top level menu item - the request is specifically to support adding something to Cluster Manager (CAPI extension) but maybe it'd make sense to generalize the functionality. Ideally an extension product should also be able to re-arrange side nav items within the parent product.

**Comment by eva-vashkevich** [comment]
Confirmed that CAPI can be navigated to and from without re-initializing store
Confirmed that Kubewarden and Harvester navigation was not affected.
