### ISSUE TITLE
Add ns filtering to main Istio section (and maybe remove duplicate section)

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9739]
Internal Reference: SURE-6784

- Istio has two sections in the UI dropdowns on the left side but ns filtering is missing for the main one (though monitoring allows for it as expected)

- The types shown in the Istio section are not the complete set of Istio types - this should be made consistent with the more resources section

**Comment by ronhorton** [comment]
@nwmac 
Verified the menus in the PR and v2.8-head
The menu items match - but are pluralized / singular mismatched. 

Is this acceptable from your perspective? If so, this is verified. Else, needs to be re-tooled to match the PR. 
left column - PR | right column - `v2.8-head commit ID 436f4de`
![2023-10-02_17-02-05.png](https://zube.io/files/rancher/2bf68b161033fa5d78188fc87dab6e49-2023-10-02_17-02-05.png)

**Comment by nwmac** [comment]
@ronhorton yeah that’s fine - that’s a general difference in those two parts.

**Comment by nwmac** [comment]
@ronhorton you okay to move this to some?
