### ISSUE TITLE
Sidecars for Workloads

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#975]
Sidecar issues:
https://github.com/rancher/dashboard/issues/2722
https://github.com/rancher/dashboard/issues/2709
https://github.com/rancher/dashboard/issues/2708

Other related issues found during sidecar tests:
https://github.com/rancher/dashboard/issues/2807
https://github.com/rancher/dashboard/issues/2804
https://github.com/rancher/dashboard/issues/2723

Tested on 2.5-head and v2.5.8-rc8

**Comment by deniseschannon** [comment]
When designing sidecar, we need to address this use case: 
```
Pod detail screen does not show the images for the containers. But the containers tab in general is not really clear what it's showing. I think it might be because the container name is also not shown so if you have multiple containers you just get a repeated list of headers, but the context of what container I'm looking at is lost.
```

**Comment by gaktive** [comment]
Pushing to 2.5.7 based on giving QA time to test everything else. Do not merge until 2.5.6 released.
