### ISSUE TITLE
Cluster explorer resources display an icon adjacent to the resource count

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#9750]
Setup

Rancher version: 2.8-head `efc48ac`
Browser type & version: Chrome

**Describe the bug**
In the cluster explorer page of the downstream clusters, all the resources have a symbol {-} that do not convey any specific meaning or significance.

**To Reproduce**
Navigate to local cluster explorer and click on events. Notice on the menu, a symbol is noticed next to the count of the resources. 

**Expected Result**
Expected no symbols to be present since they do not convey any specific meaning or significance.

**Screenshots**
<img width="287" alt="2023-09-21_14-59-08" src="https://github.com/rancher/dashboard/assets/38144301/29790c42-13d9-4270-a802-58c8ef020647">

**Comment by richard-cox** [comment]
@edenhernandez-suse I think there was a UX issue somewhere that tracks this?

**Comment by richard-cox** [comment]
Closing in favour of https://github.com/rancher/dashboard/issues/9788
