### ISSUE TITLE
Group Roles disappear after navigating from auth provider tab to Groups tab

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#9751]
Setup

Rancher version: 2.8-head `efc48ac`
Browser type & version: Chrome

**Describe the bug**
The roles that are configured for the groups in groups tab disappear when we navigate from auth provider tab to Groups tab. If we refresh the UI, the roles reappear.

**To Reproduce**
1. Configure any auth provider
2. Navigate to groups tab Users & Authentication >> Groups
3. Add a group with any role.
4. Navigate to auth providers tab and then back to groups tab

**Result**
Notice the role name thats assigned to the group disappears. 

**Expected Result**
Expected the role name to not disappear.

**Screenshots**
Before navigating to auth provider and then to groups tab:
<img width="500" alt="2023-09-21_16-30-23" src="https://github.com/rancher/dashboard/assets/38144301/e056e2c6-04f6-423d-89e7-cf8b7fdaf46f">

After navigating to groups tab from auth providers tab:
<img width="500" alt="2023-09-21_16-24-32" src="https://github.com/rancher/dashboard/assets/38144301/72eadd2f-b45d-4189-bc4e-78e06ddafedc">

**Additional context**
Does not happen when we navigate from other tabs, for example users/Role templates
Notice the following console errors:
```
console.js:31 TypeError: Cannot read properties of undefined (reading 'id')
    at PrincipalGroupBindings.vue:19:1
    at Array.filter (<anonymous>)
    at a.boundRoles (PrincipalGroupBindings.vue:19:1)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at a.boundRoles (vue.runtime.esm.js:5537:25)
    at a (PrincipalGroupBindings.vue:1:110)
    at Tn.e._render (vue.runtime.esm.js:2684:28)
    at a.r (vue.runtime.esm.js:3875:27)
    at e.get (vue.runtime.esm.js:3446:33)
```

**Comment by aalves08** [comment]
@anupama2501 I cannot reproduce this in my local env (2.8-head):

https://github.com/rancher/dashboard/assets/97888974/a8156d00-3d78-4721-b727-d6d19bfe899c

Any additional comments to help reproducing this? Could I have access to your system/instance?

**Comment by anupama2501** [comment]
@aalves08 Provided the test setup where the issue is reproduced.

**Comment by anupama2501** [comment]
Verified on v2.8-head `6376016`

- Configure Active Directory auth provider
- Navigated to groups tab Users & Authentication >> Groups
- Added a group with any role.
- Navigate to auth providers tab and then back to groups tab.
- Verified the group role names do not disappear in both the dark and light modes
