### ISSUE TITLE
Header and Footer banners should be full width

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9752]
With the app bar changes, the header and footer banners don't go full width - they should:

![image](https://github.com/rancher/dashboard/assets/1955897/084f9af0-ef03-4ffb-8d5b-ccfc2ef8b694)

Note, they are still full width on the login view, so this would also give consistency:

![image](https://github.com/rancher/dashboard/assets/1955897/e0bfe49f-204c-4b58-beb9-604892fe3fd2)

**Comment by susesgartner** [comment]
Ticket #9752 - Test Results - Pass ✅  
---

Verified with (HA Helm or Docker) on Rancher v2.8-head:
1. Enable the header and footer in global settings

Result: The banners are full length as expected.
