### ISSUE TITLE
Edit YAML backspace doesn't work at start

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#9757]
** Setup **
Browser: Chrome
UI version: Current master: https://github.com/rancher/dashboard/tree/92d57d955263e429fc3610ee0f6d6136af433711

**Describe the bug**
In Edit YAML view backspace doesn't work

**To Reproduce**

- Navigate to any `edit YAML` view. e.g. Cluster Management > Workloads > Deployments > Create Workload > Edit YAML
- Use backspace to remove characters
- Press any alpha numeric characters and press backspace again

**Result**
Backspace only work if other characters are typed first

**Expected Result**
Backspace should just work from beginning without having to type any 

**Screenshots**

[
](https://github.com/rancher/dashboard/assets/1387263/2a55e2f2-4945-476f-8570-1409acaa2727)

**Comment by cnotv** [comment]
Ok I see there's an issue in Storybook and that's why it's not visible, in case you want to deal with it:

![Screenshot 2023-09-28 at 12 44 06](https://github.com/rancher/dashboard/assets/5009481/6666a06b-a981-4131-860a-108c89d6ae7f)

**Comment by gaktive** [comment]
Based on @Sean-McQ's own testing, this may be a keyboard shortcut tied to a personal preference on editor mode (vim/emacs/etc.)

**Comment by gaktive** [comment]
@kwwii to look at why this is popping up and if we need it.

**Comment by nwmac** [comment]
I understand this is because the keyboard config was set to vim - is there anything we need to do here @scures ?

**Comment by kwwii** [comment]
If this is due to user configuration (setting the keyboard config to vim) we can close this issue.

**Comment by kwwii** [comment]
We should find a way to inform the user in or near the yaml editor of the current mode when they have set one in the configuration page.

**Comment by cnotv** [comment]
@kwwii I think you can see what we have and come out with an idea about it https://rancher.github.io/storybook/?path=/story/form-editor--yaml

**Comment by Sean-McQ** [comment]
@kwwii For reference, we're using a generic component called "[CodeMirror](https://codemirror.net/)" for our yaml editor that has quite a few options (although my past experience is that it can be a bit fiddly in our codebase).

Just looking through the options, we might be able to create a bottom panel for the editor that displays some metadata about the editor such as the current Keymap mode (which is the setting for VIM, eMacs, or standard input) and potentially some other info such as validation errors or the like. Here's the docs on [that](https://codemirror.net/examples/panel/) and a quick screenshot just showing a simple wordcount.
![image](https://github.com/rancher/dashboard/assets/37550899/7c0cde69-28f1-4d20-a7e5-85f3516c9f4f)

**Comment by cnotv** [comment]
Yeah they have the typical panel for editors, although it seems limited to text only, which means one line only, no?

**Comment by Sean-McQ** [comment]
One line is really all we'd need to communicate that they're in VIM mode, this wouldn't be too different from the bottom panel in vscode
![image](https://github.com/rancher/dashboard/assets/37550899/277928e2-6ece-486e-af09-54fc8d136a4e)

Potential fly in the ointment here though, codemirror is on v6 now, the docs are still available for v5 but we're on v4 (v4.0.6 to be specific) and it looks like the APIs in the v6 docs are very different than how we've implemented codemirror. Might be worth the upgrade since we're pretty far behind anyway but I don't know what that kind of effort would look like.

**Comment by cnotv** [comment]
Yeah that's what I meant, are you sure we can put something else than just text? The panel of VSCode is something way more complex.
I think is important from the design perspective to know if we have more than that.

**Comment by cnotv** [comment]
Also 100% in agreement with keeping everything updated, which is why I always push to have everything in control and be able to do so. 
We'll have to check if is compatible and we can easily check if there's any UI/feature issue using Storybook.

**Comment by Sean-McQ** [comment]
The panelConstructor passed into the show panel function takes a dom node so theoretically we could pass in anything we can put into a div.

**Comment by kwwii** [comment]
When the user has set an editor mode other than the default, we should show a small overlay at the top right of the editor itself which has text to show the input mode "VIM" or "Emacs"
