### ISSUE TITLE
Re-enable fleet workspace migration for rke2/k3s clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#9764]
**Setup**
- Rancher version: v2.8-head
- Rancher UI Extensions:
- Browser type & version: any (chrome)

**Describe the bug**

rke2/k3s clusters in fleet don't currently support migration, however it will be soon. Currently, the UI doesn't show an option to migrate the workspace for these cluster types but does allow it for rke1

**To Reproduce**

deploy an rke2 cluster
go to `continuous delivery` and migrate the cluster to a new fleet workspace

**Result**
no UI option to migrate

**Expected Result**

we should re-enable this option for users now that the backend will support it

**Screenshots**

![Screen Shot 2023-09-22 at 12 25 25 PM](https://github.com/rancher/dashboard/assets/16691014/1bfe086e-9611-44c3-a693-f30d860df4ab)

**Additional context**

https://github.com/rancher/rancher/issues/36132

**Comment by richard-cox** [comment]
This is much better worded, but covered by an existing issue https://github.com/rancher/dashboard/issues/9730 (which includes details about feature flags)
