### ISSUE TITLE
cloudProviderOptions is undefined in rke2 after the recent changes

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#9765]
**Setup**
- Rancher version: 
- Rancher UI Extensions: N/A
- Browser type & version: any

**Describe the bug**
cloudProviderOptions was unnecessarily removed from rke2.vue
 

**To Reproduce**
1. Create an AWS cluster. 
2. Edit the cluster

**Result**
"Cannot read properties of undefined (reading 'find')" error is displayed.

**Expected Result**

No error should be shown.

**Screenshots**

**Additional context**

**Comment by slickwarren** [comment]
are there any repro steps you can give for this issue? 
also I glanced at the code changes, is there any possible regression for `isHarvesterExternalCredential`, which seems to be at least in part removed?

**Comment by eva-vashkevich** [comment]
@slickwarren I will try to find a way to show a bug for more clarity. I haven't been able to see what the original code change broke, just that this part got missing. 
I've checked isHarvesterExternalCredential and it is defined in one of the files and is not needed in the other one anymore.

**Comment by eva-vashkevich** [comment]
This bug was breaking changes made in https://github.com/rancher/dashboard/pull/9643

**Comment by slickwarren** [comment]
tested on v2.8-head (6376016): 
* provisioning in-tree cloud provider aws with rke2 1.26.x -- pass
* switching between 1.27 and 1.26 reset the cloudProviderOptions to `embedded` option
* no error observed in UI nor through rancher when switching nor provisioning
