### ISSUE TITLE
UI workload creation should pick the default storage class

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9773]
Internal reference: SURE-6879
Reported in 2.7.5

Issue description:
Creating a workload from the UI with storage should default to the default storage class.

Business impact:
If the user does not notice the SC isn't set, they will have to troubleshoot why their PVC is in a pending state

Repro steps:
- Create a default StorageClass in your cluster
- in the UI go to Workloads > Deployments > Create
- in the Pod section click Storage > Add Volume > Create PVC

Workaround:
Manually pick the storage class

Actual behavior:
The storage class field is empty

Expected behavior:
The storage class field should default to the default storage class

![image-2023-08-23-10-38-33-345.png](https://zube.io/files/rancher/f6a4a8a50b25bcb1b34ed6c150fc5cf2-image-2023-08-23-10-38-33-345.png)

![image-2023-08-23-10-39-27-381.png](https://zube.io/files/rancher/3284a6ab5195045c3b2c36b591300f00-image-2023-08-23-10-39-27-381.png)

**Comment by richard-cox** [comment]
@gaktive Think they've already created this one - https://github.com/rancher/dashboard/issues/9585

**Comment by gaktive** [comment]
OK, closing as a duplicate.
