### ISSUE TITLE
Page goes blank with "t is undefined"

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9776]
Internal reference: SURE-6845
Reported in 2.7.5

Issue description:
A user sees quite often an error message like "t is undefined" or "p is undefined" in the Rancher GUI. The error message is the page content. Simply reloading the page is working.

This seems to be happening since the Rancher 2.7.5 upgrade.
It happens on all production clusters and lots of (or all) users are experiencing it.

"p is undefined" has been reported when accessing URL https://$URL/dashboard/c/_/manager/provisioning.cattle.io.cluster 
Other URLs might be affected too.

Business impact:
During normal operation, Rancher UI shows error messages that most probably are harmless but can confuse users. It also leaves the impression of an unstable product.

Troubleshooting steps:
Testing happened with Rancher 2.7.5/Harvester 1.1.2 and then also with 2.7.4 and upgraded to 2.7.5 but the error isn't seen.

Workaround (partial):
The user disabled the incremental loading feature and that seems to mitigate the problem, so it looks like the incremental loading performance feature is causing problems. Unfortunately, it backfires as the UI locks up when it is trying to load all changes in the UI that are pushed through the websockets on a heavily used cluster.

Additional notes:
@ravarga tested various combinations and the issue is not browser dependent. 

> It also doesn't happen with Harvester 1.1.1 and Rancher 2.7.5. But it's 100% reproducible with R2.7.5 and H1.1.2 and I believe some change in proxying to Harvester introduces this. I even found another error, but I cannot get "t is undefined". I can get this:

1. Prerequisite is Harvester 1.1.2 registered to Rancher 2.7.5 and guest cluster deployed or in the deployment phase. With no cluster on Harvester, there is no error
2. Go to Virtualization Management in Rancher and click on Harvester cluster. It will open a proxy link to https://$URL/dashboard/harvester/c/c-m-8nvjgbwp/harvesterhci.io.dashboard#vm
3. Click "hamburger menu" and pick "Cluster management". There I get "Cannot read properties of undefined (reading 'id')"
It may be a different message when terraform was used to provision the downstream cluster. I have not tried that yet.
4. Refresh the page, it shows okay. It is at https://$URL/dashboard/c/_/manager/provisioning.cattle.io.cluster

> It also happens with no downstream cluster, but only if I delete the existing cluster(s). The fresh install doesn't trigger the error.
I asked customer to confirm they get the error by following these steps.

> Yesterday I was able to trigger another error message by going to the Harvester proxied link (Virtualization mgmt) and then to Continuous delivery. Today with a new set of downstream clusters I cannot reproduce that one anymore.

The user ran into another similar error:  "e.availableActions is undefined "
This time they deleted a node. URL was https://$URL/dashboard/c/_/manager/provisioning.cattle.io.cluster/fleet-default/qxz1wet-update-test#machine-pools

**Comment by gaktive** [comment]
There's been a report that Harvester could be ruled out if that helps with repro. Reported in AWS with someone trying an upgrade to 2.7.6

**Comment by gaktive** [comment]
Update: the issue is still present when Rancher 2.7.6 and Harvester 1.1.2 is used. But doesn't happen anymore with Harvester 1.2.1 (with the same Rancher 2.7.6) so this may narrow things down.

**Comment by gaktive** [comment]
Moving to Harvester 1.2.1 addresses this so closing as solved. For others who run into this, please confirm which Harvester version you're running on and upgrade where appropriate.

**Comment by richard-cox** [comment]
Note - https://github.com/rancher/dashboard/pull/10211 brings in the fix to not show the fill blank page when there is an error. Not sure if that is sufficient for this backport? I couldn't see any other code changes related to addressing the underling fix associated with the original issue
