### ISSUE TITLE
Add v1.27 k8s versions to EKS hardcoded list

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9786]
From @mjura 

Updates v1.27 k8s versions list with newer versions based on https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

rancher/eks-operator#264

PR: https://github.com/rancher/ui/pull/5070

**Comment by cpinjani** [comment]
This has been validated via https://github.com/rancher/rancher/issues/41797
