### ISSUE TITLE
Projects with long Display Names do not get truncated

### ISSUE THREAD

**Issue by pjbgf** [rancher/dashboard#9790]
**Setup**
- Rancher version: `v2.8-head`
- Rancher UI Extensions:
- Browser type & version: Chrome / Firefox

**Describe the bug**
Projects with long display names are not truncated, which may lead to some of the text overflowing on other UI components.

**To Reproduce**
- Create a project with a very long Display Name

**Result**
If the display name is long enough, part of the text will appear over the project namespaces and potentially over the next project as well.

**Expected Result**

The display name is truncated, so that the visual identity is not distorted.

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/5452977/307523da-a42d-4a5b-904f-b10b8d42be5c)

It is less of an issue within the project edit page:
![image](https://github.com/rancher/dashboard/assets/5452977/6556f088-17e0-47b2-847a-f73996601241)

**Additional context**

**Comment by cnotv** [comment]
@kwwii @edenhernandez-suse do we have guidelines about lenght?
@pjbgf do you have a real use case which breaks?

**Comment by pjbgf** [comment]
@cnotv no specific use case that I am aware of. This came up on the back of testing the feature for validation that was in place vs missing.

**Comment by edenhernandez-suse** [comment]
@cnotv we don't have guidelines on this. It does not feel like a realistic case, however we can guarantee a correct behaviour with a max width of 400px for the project name. It would need to be wrapped around an HTML element (right now it's not). 400px is just an arbitrary number, @kwwii can comment on this if needed.

![image](https://github.com/rancher/dashboard/assets/120640736/b7f198d7-fb3f-4989-83e3-708644a3f313)

**Comment by cnotv** [comment]
FYI it is already handled in the top filter in a similar fashion.

<img width="396" alt="Screenshot 2023-10-04 at 09 23 37" src="https://github.com/rancher/dashboard/assets/5009481/266dad44-6e0d-4e4a-b346-63cc1c5cf8a9">

**Comment by kwwii** [comment]
I think that k8s resources are limited to a max a 253 characters, many just to 63 (pod names or labels come to mind). In any case, if the name is longer than can be displayed we should shorten it with an ellipsis and show the full name on hover.

**Comment by IsaSih** [comment]
Tests pass on v2.9-e2023b437f3ccba16169b1e51db18419832ca5d7-head
