### ISSUE TITLE
Feature Request: Fleet UI - Ability to see status of GitRepos for an individual cluster.

### ISSUE THREAD

**Issue by atoy3731** [rancher/dashboard#9791]
**Is your feature request related to a problem? Please describe.**

When you currently look at an individual cluster within the Continous Delivery UI, it still shows the GitRepo status of all clusters for that GitRepo. That can be confusing, since it will show a `Modified` state for a perfectly sync'd cluster if that GitRepo is out of sync on another cluster.

For instance, this is the UI on a cluster that is perfectly in-sync:

![Screen Shot 2023-09-27 at 11 24 55 AM](https://github.com/rancher/dashboard/assets/5939985/ddea35e2-8b14-48ac-85bb-24ecb20ee0a8)

**Describe the solution you'd like**

Ideally, the UI would specifically show the state of cluster, and filter the GitRepo status to that specific cluster.

**Comment by aalves08** [comment]
Possible `automation-candidate` IF we can fake Fleet data

**Comment by aalves08** [comment]
Validated that issue has been fixed on Rancher `v2.9-a57f7025abdd80a2912f7fe53247ef7e1d4993de-head`.

Moving to done @yonasberhe23 @izaac @IsaSih
