### ISSUE TITLE
Resolve semver dep bump

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9793]
Ensure the following package dependencies are resolved

- semver: >=7.5.2
  - See confluence Rancher / Dashboard Dependencies for more info. this might be tricky with vue-cli. we might be able to fix it to a more modern version 

See parent issue https://github.com/rancher/dashboard/issues/9648 for more detail

**Comment by cnotv** [comment]
As mentioned by @richard-cox in [the comment](https://github.com/rancher/dashboard/issues/9648#issuecomment-1734073970), this a dependency used by `vue-cli` and not defined in the packages, although it has been used broadly inside the code as well, so it will end up in production.

**Comment by nwmac** [comment]
@torchiaf @richard-cox What should the testing on this be?

**Comment by richard-cox** [comment]
Looks like there's a lot to do. There's no mention of any manual or automated tests in the PR. We need to confirm if vue cli is broken (brief check where it uses semver?) and at least manually validate a few places where `semver` is used in our code. In terms of automation it looks like there's a few places unit tests could be written

**Comment by torchiaf** [comment]
@richard-cox I added a list of required checks in the PR description.
vue-cli and extensions code, where semver is used, seem to work fine. Most of the UI components where semver is imported are not covered by unit tests.
Could I open a dedicated PR to add the automated tests @nwmac?

**Comment by cnotv** [comment]
There's a `version.js` util which also uses `semver`. Maybe we can move all the code there and test the functions for all the cases?
Let's avoid to have code spread everywhere and not standard. As we can see it creates issues on refactoring or when we have to do something so simple like version bump.

**Comment by torchiaf** [comment]
Yes, I agree with moving the code in that utils file and apply the unit tests there, where possible.

**Comment by rak-phillip** [comment]
Confirmed that the semver bump produces the expected output for rke2 & k3s versions when creating an rke2 cluster. I also validated the parsed kubernetes versions for EKS
