### ISSUE TITLE
Add automated workflow to publish @rancher/shell to npm

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#9796]
**Is your feature request related to a problem? Please describe.**
Currently in order to publish a new version of the `@rancher/shell` package to npm, a user with access needs to manually run the `./scripts/publish-shell` script.

**Describe the solution you'd like**

It would be nice to have a workflow that would run automatically when detecting a change to the `./shell/package.json` version to publish the new version of the the shell to npm.

**Comment by jordojordo** [comment]
The shell package isn't tied to a Rancher release. Although I wouldn't be opposed to having a release tag for this package, I think it could cause some unexpected issues depending on how we name the releases. Perhaps we could have a release titled `shell-<version>` and check against this naming scheme?

**Comment by cnotv** [comment]
Yeah to pinpoint in somehow I guess it's always a good idea, although I have no idea about how this is planned, like frequency, number and so on.
It's also a matter of how we want to deal the project which I tried to talk about the other day.
