### ISSUE TITLE
App - render errors in the advance setting page 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#980]
`rancher/rancher:master-3426-head`

deploy any app, go the the `advanced` page, the names of options are not rendered properly. 

<img width="1039" alt="Screen Shot 2020-08-07 at 10 53 52 AM" src="https://user-images.githubusercontent.com/6218999/89674176-97b5e700-d89c-11ea-8263-06f2e03c6de7.png">

**Comment by deniseschannon** [comment]
Looks fixed as of today's master-head (8/18)

**Comment by jiaqiluo** [comment]
Validated on `master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head`

<img width="543" alt="Screen Shot 2020-08-18 at 3 49 18 PM" src="https://user-images.githubusercontent.com/6218999/90575081-747a1a00-e16f-11ea-9063-934439698809.png">
