### ISSUE TITLE
rancher-logging helm options UI not available in latest master

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#981]
Rancher `master-head (08/07/2020)` _4fb56e2b7_ k8s HA
dashboard-index -> `latest`

Before:

![Screen Shot 2020-08-06 at 10 14 27 AM](https://user-images.githubusercontent.com/27659/89677247-f29e0d00-d8a1-11ea-9df7-d8dc61ea923d.png)

After (current latest `master-head`):

<img width="778" alt="Screen Shot 2020-08-07 at 11 19 57 AM" src="https://user-images.githubusercontent.com/27659/89677347-21b47e80-d8a2-11ea-8160-3366637f1cbe.png">

**Comment by izaac** [comment]
Steps I've follow to repro:

- Install Rancher HA k8s
- Login with default `admin`
- Go to Apps enable ECM wait for it to be installed.
- Navigate to `rancher-logging` see the YAML view  from the screenshot above.

404 is returned from
`/v1/catalog.cattle.io.repos/default/rancher-charts/info?chartName=rancher-logging&version=3.4.000`

**Comment by izaac** [comment]
Workaround, re-login.

**Comment by deniseschannon** [comment]
This looks to be working based on today's master (8/18)

**Comment by izaac** [comment]
This will be harder to reproduce now as ECM is enabled by default closing.
