### ISSUE TITLE
Incorrect app bar cluster abbreviations

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9810]
**Setup**
- Rancher version: pre 2.8.0

**Describe the bug**
- `rc-rke1-3` and `rc-rke1-4` both shorten to `RR1` instead of `RR3` and `RR4`

**To Reproduce**
- create imported clusters with names above
- view them in the new app bar

**Result**
![image](https://github.com/rancher/dashboard/assets/18697775/77eecd3d-4f08-4ef2-869e-01aae10e0a09)

**Expected Result**
`RR3` and `RR4`

**Comment by richard-cox** [comment]
In addition we should look at how these work

https://github.com/rancher/dashboard/blob/master/shell/utils/__tests__/cluster.test.ts#L36C1-L43C44

```
    ['customer-support-team-1', 'cst'],
    ['customer-support-team-one', 'cst'],
    ['customer-support-team-prod', 'cst'],
    ['customer-support-team-dev', 'cst'],
    ['customer-support-team-prod-1', 'cst'],
    ['customer-support-team-dev-1', 'cst'],
    ['customer-support-team-prod-2', 'cst'],
    ['customer-support-team-dev-2', 'cst'],
```

**Comment by edenhernandez-suse** [comment]
For reference, here are the specs for the cases with & without cluster colour:

[Adobe Xd Specs](https://xd.adobe.com/view/c0a1af46-aa3c-45c7-81f6-78ced3e277fc-95f2/)

**Comment by izaac** [comment]
I didn't spot a check for this test expectation:

- Opening the Customise modal, the Use custom badge & Apply buttons should be disable.

Let me know if I've missed it but I checked the e2e and I didn't find an is disabled assertion. @yonasberhe23

**Comment by gaktive** [comment]
@nwmac with @scures gone, can you answer this question from QA?

**Comment by richard-cox** [comment]
> Opening the Customise modal, the Use custom badge & Apply buttons should be disable.

@izaac This has partially changed during the lifetime of the PR. the use custom badge _should_ be enabled and the `Apply` button disabled. However this isn't working (when there are no setting the Apply button is enabled). I think there were some other changes we might make as well, so i createed a separate [issue](https://github.com/rancher/dashboard/issues/11050)

**Comment by nwmac** [comment]
Thank you @richard-cox

**Comment by yonasberhe23** [comment]
I think it's safe to move this to done. test coverage is sufficient with e2e testing the modal functionality and unit testing the cluster abbreviations. @izaac
