### ISSUE TITLE
Specify Distros Labels on Chart Icons in Apps & MarketPlace Catalog Page

### ISSUE THREAD

**Issue by rohitsakala** [rancher/dashboard#9811]
**Is your feature request related to a problem? Please describe.**
The detailed design is mentioned here https://confluence.suse.com/display/EN/Proposed+solution+to+chart+support+for+specific+distributions

**Describe the solution you'd like**
Every Chart.yaml will have an annotation of which distros it is certified to run on. The UI needs to put a Certified label on the Chart Icon if such a annotation exists in Index.yaml.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gunamata** [comment]
SURE-6131

**Comment by gaktive** [comment]
Seems like a duplicate of #9818 though this ticket seems to specify a specific icon action whilst the other one is the main work that UI will do.

**Comment by rohitsakala** [comment]
Closing this. The original seems right.
