### ISSUE TITLE
Specify Arch label on Chart Icons 

### ISSUE THREAD

**Issue by rohitsakala** [rancher/dashboard#9812]
**Is your feature request related to a problem? Please describe.**
RFC Link - https://confluence.suse.com/pages/viewpage.action?pageId=1279001207

**Describe the solution you'd like**
We would like the UI to display a label on the Chart Icon with the architectures the chart supports. The list of arch's can be retrieved from the annotation on index.yaml after some computation from the UI. The complete details are mentioned in the RFC.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gunamata** [comment]
SURE-6440

**Comment by rohitsakala** [comment]
I will leave it to the UI team for making the decision of how to show it. So closing this.
