### ISSUE TITLE
Remove need to Install Extensions Operator

### ISSUE THREAD

**Issue by rohitsakala** [rancher/dashboard#9813]
**Is your feature request related to a problem? Please describe.**
Right now, users have to click on `Enable Extensions` on the extensions page. This is an additional step for users. We can mitigate this by allowing Rancher to install extensions by default based on some criteria which needs to be agreed upon. 

**Describe the solution you'd like**
Just like Fleet and Rancher webhook, extensions can be installed through the Rancher codebase. 

**Describe alternatives you've considered**
N/A

**Additional context**
There is a spike going on right now and the Mapps team will come up with a detailed plan soon and edit this issue with the UI requirements

JIRA Issue - https://jira.suse.com/browse/SURE-6314

**Comment by richard-cox** [comment]
Superseded by https://github.com/rancher/dashboard/issues/10939
