### ISSUE TITLE
Extensions: Allow extensions to load before login

### ISSUE THREAD

**Issue by rohitsakala** [rancher/dashboard#9814]
**Is your feature request related to a problem? Please describe.**
We need some UI extensions to load before login such internationalization, custom login page, etc..

**Describe the solution you'd like**
The current solution being explored by the Mapps team is giving the system:unauthenticated access to UI-plugins CRD but the spike is still going on.

**Describe alternatives you've considered**
N/A

**Additional context**
Right now, there is no requirement from UI for this issue. But, after the completion of the spike, the Mapps team will edit this issue if there are any UI requirements.
JIRA Issue - https://jira.suse.com/browse/SURE-6315

**Comment by richard-cox** [comment]
The UI will need to load the plugins earlier than it currently does. Hopefully it should be as clean as simply moving the initialisation stuff, but needs some careful thought

**Comment by richard-cox** [comment]
@rohitsakala is there a target MS for this one too?

**Comment by rohitsakala** [comment]
@richard-cox Yes, that would be Q1-2.8 Rancher release. I don't have permissions to add milestone

**Comment by gaktive** [comment]
As @rak-phillip spotted, the UI plugin behaviour changed in https://github.com/rancher/rancher/pull/44230 so that the ui-plugin-operator is now inside Rancher. This means that either we can work on this or we have to check if we have to change the dashboard behaviour.

**Comment by rohitsakala** [comment]
@diogoasouza Can you update this issue with the expectations that we need from the UI team and also update the JIRA issue corresponding to this and relations with the backend issue ?

**Comment by diogoasouza** [comment]
@rohitsakala Sure! 
The behavior shouldn't have changed, just the endpoints. The `ui-plugin-operator` helm chart should not be installed anymore.
There's a couple of new ones:

1. `/v1/uiplugins`: This is the equivalent to the `index.json` endpoint from before, with the main difference being that it works with unauthenticated users as well if the `noAuth` flag of the CRD is set to true.
2. `/v1/uiplugins/{name}/{version}/{rest:.*}`: This is the endpoint to get the files from the extension. Should have the same behavior as the one from the operator, with the difference being handling unauthenticated users

**Comment by gaktive** [comment]
In the extension examples repo, there's something to try out using the UK locale.

**Comment by gaktive** [comment]
We should check the behaviour upon logout and relogin since we may have something running and not loaded.

**Comment by yonasberhe23** [comment]
manual testing is needed to cover the recommended test scenario mentioned 

> A cluster with 2 versions of harvester and navigating between the two separate instances

the other scenarios seem to be covered by the e2e tests.

 cc @izaac

**Comment by izaac** [comment]
This issue needs a final validation on a harvester cluster scenario. I've added the label to reflect that.

**Comment by lanfon72** [comment]
hi @yonasberhe23 and @izaac, I checked changes in PR https://github.com/rancher/dashboard/pull/10727, as the extensions function is outside of Harvester, I think it will not affect Harvester's behaviors?

Or and I misunderstanding something?

**Comment by IsaSih** [comment]
Switching back and forth from harvester clusters with different versions 1.3.1 and 1.2.2. Extensions loaded as expected. 

![Image](https://github.com/user-attachments/assets/c8969595-18e0-48f0-80e8-81cf08f80c41)
![Image](https://github.com/user-attachments/assets/6f14e04c-46fc-4dc3-a191-db8a6ec86c63)

**Comment by noahgildersleeve** [comment]
I was checking a bit more into this after reading the earlier comments more closely.

- It doesn’t show SR-IOV GPU in advanced settings on v1.3.1
- it doesn’t show vGPU in advanced settings on v1.3.1
- It’s not loading serial console on either v1.2.2 or v1.3.1 for accessing the VMs
- It’s not loading web VNC on v1.2.2 or v1.3.1 for accessing the VMs
- [6:38](https://suse.slack.com/archives/D0718063Y3E/p1721957926480699)

Here are some screenshots. The one missing the settings section are from Rancher, the 0one that has it is the Harvester UI.
![Greenshot 2024-07-25 18 34 43](https://github.com/user-attachments/assets/07613001-52cb-499d-9ac2-45e8e6bd60a5)
![Greenshot 2024-07-25 18 33 36](https://github.com/user-attachments/assets/2b5e375d-b6c4-498a-9462-a7e6e389a039)
![Greenshot 2024-07-25 18 32 55](https://github.com/user-attachments/assets/8cb95c57-e242-49c3-be5d-9a5860c29d6b)
![Greenshot 2024-07-25 18 30 48](https://github.com/user-attachments/assets/276eb342-33f7-451c-9217-e4adb438354b)

**Comment by codyrancher** [comment]
@noahgildersleeve was this caused when switching between different versions of harvester clusters or were these failing to load even when on refresh?

If it's a problem even on refresh I don't think it's related to this issue.

**Comment by gaktive** [comment]
Will hold until moving into the Reopened column until this is clarified. As a result, I can't tell if this is a blocker yet. @noahgildersleeve keep us posted.

**Comment by gaktive** [comment]
@noahgildersleeve this reads like a separate problem from the original ticket's intent.

**Comment by richard-cox** [comment]
Release notes..

```
VM Management (Harvester)

Known Issues

In the Rancher UI when navigating between Harvester clusters of different versions a refresh may be required to view version specific functionality.
```

**Comment by richard-cox** [comment]
- It doesn’t show SR-IOV GPU in advanced settings on v1.3.1
  - Spun out to https://github.com/rancher/dashboard/issues/11559
- it doesn’t show vGPU in advanced settings on v1.3.1
  - Spun out to https://github.com/rancher/dashboard/issues/11559
- It’s not loading serial console on either v1.2.2 or v1.3.1 for accessing the VMs
  - Fixed by https://github.com/rancher/dashboard/pull/11557
- It’s not loading web VNC on v1.2.2 or v1.3.1 for accessing the VMs
  - Fixed by https://github.com/rancher/dashboard/pull/11557

**Comment by richard-cox** [comment]
Give comment above, this feature is now complete
