### ISSUE TITLE
OIDC (OpenID Connect) support external ID providers

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9820]
Internal reference: SURE-4586

Request description:
Many users leverage external identity providers (IdP) that support the OpenID Connect (OIDC) standard, such as Google, Salesforce, ForgeRock, NetIQ, and would like Rancher to support this for web identity federation for authentication.

Workaround:
There is limited support for other authentication providers; OIDC is a broadly accepted standard that many enterprises have adopted and is preferred.

Additional notes:
Some examples of how other services support OIDC providers:

- OIDC on AWS: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html
- OpenID Connect authentication with Azure Active Directory: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/auth-oidc
- GCP: Signing in users with OIDC: https://cloud.google.com/identity-platform/docs/web/oidc

Related backend: https://github.com/rancher/rancher/issues/10053

**Comment by richard-cox** [comment]
Initial keycloak oidc integration - https://github.com/rancher/dashboard/issues/2191#issue-783541182
- there's a lot of support in the dashboard for generic oidc, but we restricted it to just keycloak - https://github.com/rancher/dashboard/blob/master/shell/utils/auth.js#L67
- i think this was due to issue with search (user / group)

we need the backend to confirm that generic oidc works and get a build with it in

**Comment by txj-xyz** [comment]
Following for implementation

**Comment by wzrdtales** [comment]
oh, someone is working on this now. There was never a real reason to not just release this, go for it, no one really cares to be perfectly capable to link unknown users from their SSO. That is a very secondary problem to being able to utilize SSO. SSO is really about reducing the number of accounts in the first place, being able to search for users is nice, but that is it. And honestly, if this efficiency feature is wanted then it is not what customers would want. You would want to setup the permission in the SSO and not in the software below, so matching permission to groups is the way.

**Comment by gaktive** [comment]
Backend has https://github.com/rancher/rancher/issues/10053 in progress now so we can check when there are test builds available for UI to work off of.

**Comment by richard-cox** [comment]
Backend will be able to provide us an image to start implementing this, alongside RFC this should be ready to work on

**Comment by richard-cox** [comment]
For whoever picks this up, contact @crobby for details on image and instructions on bringing up an oidc instance to test with

**Comment by izaac** [comment]
https://github.com/rancher/rancher/issues/10053#issuecomment-2230960661
The scenarios listed and executed as part of QA in the BE issue include the expected validation for UI.
I reviewed the Test Plan for this too.
