### ISSUE TITLE
Make column widths adjustable

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9821]
Internal reference: SURE-6364

Request description:
1. Please make all columns in list views adjustable in width.
2. Ideally the column width is saved in the user profile.

Actual behavior:
A lot of UI items are misplaced or truncated due to hardcoded column size

Expected behavior:
Column width should be configurable and saved in the user profile

**Comment by richard-cox** [comment]
If we persist this setting per user, we should bear in mind other similar settings we may persist later on (search term, sort order, possibly page in session, etc).

We should also consider how these settings are maintained (per cluster, stale resource types, etc).

**Comment by gaktive** [comment]
The easiest thing to tackle here first is to look at the Harvester tables since it looks like the column widths aren't set at all.

**Comment by richard-cox** [comment]
Worth mentioning that width is only set on about a quarter of our columns

**Comment by torchiaf** [comment]
Revisioning columns widths on Harvester UI, as preparatory step for this enhancement:  https://github.com/harvester/harvester/issues/4989
