### ISSUE TITLE
[RFE] More specific page titles

### ISSUE THREAD

**Issue by CC007** [rancher/dashboard#9822]
**Is your feature request related to a problem? Please describe.**
Right now the page title for rancher is always Rancher. If you want to go back to a previous page in your browser history, this makes it hard to find the right page to go back to.

**Describe the solution you'd like**
It would be nice if the page title was more specific, like:
 - `Rancher - <cluster name> - Deployments`
 - `Rancher - <cluster name> - Deployment: phpmyadmin`
 - `Rancher - CD - <git repo>`
 - `Rancher - VM mgmt - <harvester cluster name> - Hosts`
 - `Rancher - VM mgmt - <harvester cluster name> - Image: ubuntu-22.04-minimal-cloudimg-amd64`
 - etc.

**Describe alternatives you've considered**
An alternative is that Rancher keeps track of a page history itself, but that seems clunky and the browser doesn't provide the functionality without a reason.

**Additional context**
![afbeelding](https://user-images.githubusercontent.com/5381337/218258807-5c52c79c-47cb-40ca-b901-50c45e489f04.png)

**Comment by gaktive** [comment]
Internal reference: SURE-6121

**Comment by CC007** [comment]
Thanks for the response, @gaktive . I'm glad to see not just a comment, but actual actions taken to triage the issue.

**Comment by gaktive** [comment]
#9538 will be a prerequisite for this.

**Comment by nwmac** [comment]
@codyrancher I've re-opened this - there is a small bug - go to Workloads, then go to a workload type, like Deployments and then go back to Workloads and the title is now incorrect - is says `Rancher - local - ?` - first time in, it is correct.

I had a tiny look and I see a watch in `TabTitle`, but I don't think Vue allows watching of slot content like that.

**Comment by nwmac** [comment]
If you add `:key="_typeDisplay"` to the `TabTitle` in MastHead.vue, this resolves the issue, but this forces the TabTitle to be recreated/rendered when _typeDisplay changes - which gets around the watch - but not sure why this is not an issue when you move to a different resource type.

**Comment by yonasberhe23** [comment]
The page titles have been updated to be more specific however when clicking and holding the back button to see browser history, I only see the specific page titles there for a few areas. Going to reopen this for further investigation



https://github.com/rancher/dashboard/assets/127343932/c7752f2f-05ac-409e-bdf7-328023a8c2c2

**Comment by codyrancher** [comment]
@yonasberhe23 do you notice anything different about the way I'm testing the app? I seem to get titles in firefox when using the back button.


https://github.com/rancher/dashboard/assets/55104481/d87de5f7-d9dd-4204-8392-a6daadb2101c

**Comment by yonasberhe23** [comment]
@codyrancher it seems like it works for certain page visits and not for others. For example, it works for the tabs under `Workloads` but not for the ones under `Cluster`.

https://github.com/rancher/dashboard/assets/127343932/b54deb0c-43c7-4197-b8cf-52d315c82827

**Comment by yonasberhe23** [comment]
this looks good to me, thank you @codyrancher !


Tested in v2.9-01491294fbb5870288d476ef82560512ae11937b-head


https://github.com/rancher/dashboard/assets/127343932/60745d4e-0bca-4f71-93d1-9f4d0118b7e5

**Comment by CC007** [comment]
I want to confirm that this now works for me in v2.9.0. 

Thanks for your effort!

**Comment by codyrancher** [comment]
> I want to confirm that this now works for me in v2.9.0.
> 
> Thanks for your effort!

I'm glad it's working for you! Sorry it took as long as it did to get in.

**Comment by CC007** [comment]
No problem. From what I saw in the timeline, there were a couple of roadblocks that had to get fixed first.
