### ISSUE TITLE
YAML diff is broken when editing clusters

### ISSUE THREAD

**Issue by lindhe** [rancher/dashboard#9829]
**Setup**
- Rancher version: v2.7.6
- Rancher UI Extensions: None.
- Browser type & version: Firefox 118.0.1

**Describe the bug**

The "Show Diff" function is cluttered with line numbers (and possibly other things) and bad indentation, making it impossible to use.

**To Reproduce**

1. Go to Cluster Management.
2. Click the menu for a cluster and select "Edit YAML".
3. Make a change.
4. Click "Show Diff".

**Result**

![image](https://github.com/rancher/dashboard/assets/7773090/48915f7f-e4d8-4789-bf70-f5b642ccb999)

![image](https://github.com/rancher/dashboard/assets/7773090/923cd918-e019-4c39-a2e2-21972846cbc6)

**Expected Result**

I expect a clear, uncluttered diff like in Git. If line numbers are included, they should stay at the right-hand-side of the text box.

**Screenshots**

See above. ☝️ 

**Additional context**

It's even worse if one selects "Edit Config" instead of "Edit YAML". If you do that and then click "Edit as YAML" and "Show Diff", the diff is huge and looks even worse than when a single line gets edited.

**Comment by richard-cox** [comment]
Thanks for raising this issue. It was resolved in 2.7.7 though via https://github.com/rancher/dashboard/issues/9313 / https://github.com/rancher/dashboard/pull/9323
