### ISSUE TITLE
Workloads - Layout Issue

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#983]
- [ ] Move NameNS Description to outside of tabs. Here is the example of how Create Service is:

<img width="1120" alt="Screen Shot 2020-08-07 at 2 26 06 PM" src="https://user-images.githubusercontent.com/11410997/89689893-33098500-d8ba-11ea-918b-1f7946c359bb.png">

- [ ]. Add in ability for it to say `Workload: Create <SubType` into masthead. Coordinate with @westlywright as I've asked the same in this service ticket: https://github.com/rancher/dashboard/issues/966

- [ ] Where did stdn and workindir go to in the new tabs? We can move them into the "Command" section on the define container page. 

- [ ] Hide/Show Advanced Options -> It's a little weird that you could be selected one of the advanced options tab and then hide them, so you end up with this weird navigation.  Once we show them the advanced options, we should just hide the "Hide Advanced Options". Once you've shown the advanced options, you can't hide them again. Should we remove hiding the advanced options in Edit workloads? What do you think @vincent99 ?

<img width="710" alt="Screen Shot 2020-08-07 at 2 35 34 PM" src="https://user-images.githubusercontent.com/11410997/89690412-49641080-d8bb-11ea-8bfd-a34ddaf21001.png">

**Comment by vincent99** [comment]
> Once we show them the advanced options, we should just hide the "Hide Advanced Options". Once you've shown the advanced options, you can't hide them again. Should we remove hiding the advanced options in Edit workloads? What do you think @vincent99 ?

That appears to be what it does now, though none of them line up:

![image](https://user-images.githubusercontent.com/753917/89869317-0cbd4100-db69-11ea-86c4-7a365315fb04.png)

**Comment by izaac** [comment]
We're missing the `Subtype` from Denise's requirement checklist. Will that get addressed in #966?

**Comment by izaac** [comment]
Closing, will track `Subtype` in  #966
