### ISSUE TITLE
Color property is undefined when an extension adds an svg icon to an action

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#9833]
**Setup**
- Rancher version: v2.8.0-alpha1
- Rancher UI Extensions: ui-plugin-examples
- Browser type & version: FF 117.0

**Describe the bug**

The IconOrSvg component is causing the UI to break when the `extensions-api-demo` extension is installed.

<details>
  <summary>Console Log</summary>

```
TypeError: color is undefined
    colorToRgb color.js:126
    setColor IconOrSvg.vue:102
    created IconOrSvg.vue:60
    VueJS 85
    finish GlobalLoading.vue:14
    _callee5$ client.js:524
    tryCatch runtime.js:64
    invoke runtime.js:299
    defineIteratorMethods runtime.js:124
    Babel 4
```
</details>

Related: rancher/dashboard#9157

**To Reproduce**

- Add the [ui-plugin-examples](https://github.com/rancher/ui-plugin-examples/) repository
- Install the `extensions-api-demo`
- Navigate to the local cluster

**Result**
Page breaks with error `color is undefined`

**Screenshots**

https://github.com/rancher/dashboard/assets/40806497/2640eaaf-37df-4cfd-b1ee-e9b63c3596e8

**Additional context**

The issue stems from one of [these conditions](https://github.com/rancher/dashboard/blob/master/shell/components/IconOrSvg.vue#L79-L81) not being met, which leaves the property `uiColor` undefined when `colorToRgb(uiColor)` is [called](https://github.com/rancher/dashboard/blob/e6acc87cc1ee735d232a21916760e1e2ce7dcf3e/shell/components/IconOrSvg.vue#L102-L103).

This could initially be fixed by checking for a defined color in the `colorToRgb` [method](https://github.com/rancher/dashboard/blob/e6acc87cc1ee735d232a21916760e1e2ce7dcf3e/shell/utils/color.js#L123-L137), but more importantly the conditions should be modified to fit the correct case of using an svg icon.

**Comment by jordojordo** [comment]
@aalves08

**Comment by nwmac** [comment]
@jordojordo I think this has been fixed - can you verify please

**Comment by aalves08** [comment]
Hummmm, thinking about it, Neil might be right. I think we might only need a bump on the shell version. I remember fixing some stuff a couple of times on the colors of the icons. This build of the `extensions-api-demo` might just be using an outdated version.

**Comment by jordojordo** [comment]
The initial problem seems to be gone, I am able to navigate to a cluster and the icon that was causing the trouble does appear. There are still errors popping up within the console related to the same issue:

![icon](https://github.com/rancher/dashboard/assets/40806497/bd07bdf5-438d-4dda-a235-a2b8b233672c)

**Comment by nwmac** [comment]
@jordojordo I don't see those console error messages on my system - what's your environment? Is this latest dashboard code?

**Comment by aalves08** [comment]
I cannot reproduce it as well @nwmac @jordojordo . Running the `ui-plugin-examples` locally with Rancher backend `2.8.0-rc3`. `ui-plugin-examples` is still using an old version of `shell - 0.3.5`. We are now at `0.3.29`.

**Comment by jordojordo** [comment]
This was on Rancher `2.8.0-rc1` - When running the extension locally these don't appear but if you install the `extensions-api-demo` from the repository they will show up.

I did attempt to build a new version of the extension but it would fail with:
```
 ERROR  Failed to compile with 1 error                                                                                                          7:11:27 AM

 error  in /home/jordon/Documents/jordojordo/ui-plugin-examples/node_modules/@rancher/shell/core/plugin.ts

ERROR in /home/jordon/Documents/jordojordo/ui-plugin-examples/node_modules/@rancher/shell/core/plugin.ts(18,32):
18:32 Cannot find module '@shell/initialize/layouts' or its corresponding type declarations.
    16 | } from './types';
    17 | import coreStore, { coreStoreModule, coreStoreState } from '@shell/plugins/dashboard-store';
  > 18 | import { registerLayout } from '@shell/initialize/layouts';
       |                                ^
    19 | 
    20 | export type ProductFunction = (plugin: IPlugin, store: any) => void;
    21 | 

Webpack Bundle Analyzer saved report to /home/jordon/Documents/jordojordo/ui-plugin-examples/dist-pkg/extensions-api-demo-0.1.0/report.html
 ERROR  Build failed with errors.
Updating package file
~/Documents/jordojordo/ui-plugin-examples
error Command failed with exit code 1.
```

**Comment by aalves08** [comment]
It needs a new shell version

**Comment by aalves08** [comment]
@nwmac @jordojordo I've updated the `ui-plugin-examples` project. Now we can build pkgs again and I could verify that, after updating the shell version, the bug was no longer reproducible. Just needs a review https://github.com/rancher/ui-plugin-examples/pull/32/
