### ISSUE TITLE
Remove references to deprecated setting kubeconfig-token-ttl-minutes

### ISSUE THREAD

**Issue by JonCrowther** [rancher/dashboard#9834]
In 2.8, the setting `kubeconfig-token-ttl-minutes` has been deprecated. (Issue: https://github.com/rancher/rancher/issues/38535) 

There are 2 references that I could find to that setting in `shell/config`:
https://github.com/rancher/dashboard/blob/e6acc87cc1ee735d232a21916760e1e2ce7dcf3e/shell/config/settings.ts#L45
https://github.com/rancher/dashboard/blob/e6acc87cc1ee735d232a21916760e1e2ce7dcf3e/shell/config/settings.ts#L130

As well as 2 references in `shell/assets`:
https://github.com/rancher/dashboard/blob/e6acc87cc1ee735d232a21916760e1e2ce7dcf3e/shell/assets/translations/en-us.yaml#L7082
https://github.com/rancher/dashboard/blob/e6acc87cc1ee735d232a21916760e1e2ce7dcf3e/shell/assets/translations/zh-hans.yaml#L7054

These references should be removed in 2.8.

**Comment by gaktive** [comment]
@JonCrowther this feels late for 2.8.0 but based on what you've provided, let's see how quickly this can be done.

**Comment by JonCrowther** [comment]
@gaktive Appreciate it, it was my mistake. When I removed the setting from rancher, it stopped appearing in the UI, but when a user upgrades rancher from a version that had the setting it still appears in the UI as [discovered by Anupama](https://github.com/rancher/rancher/issues/38535#issuecomment-1743518333)

I wrongly assumed that there wasn't UI work needed.

**Comment by anupama2501** [comment]
Verified on an upgrade from v2.7.8 to v2.8-head `6376016`  
no setting for `kubeconfig-token-ttl-minutes` is listed in the global settings

Verified on fresh install v2.8-head `6376016`
no setting for `kubeconfig-token-ttl-minutes` is listed in the global settings
