### ISSUE TITLE
Rancher 2.8 support link is redirected to docs for 2.7.6

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#9839]
**Setup**
- Rancher version: v2.8.0-alpha2
- Rancher UI Extensions: N/A
- Browser type & version: Chrome Version 117.0.5938.92 (Official Build) (x86_64)

**Describe the bug**
when a user in 2.8.0-alpha2 clicks the `commercial support` link, then the [Find out more about SUSE Rancher Support](https://rancher.com/support-maintenance-terms) link, redirects to v2.7.6 docs

**To Reproduce**
1. create a 2.8.0-alpha2 rancher instance (HA or docker)
2. on the home screen, click the commercial support link
3. click the find out more link on the support page

**Result**
user is directed to https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-6/

**Expected Result**
user is directed to rancher 2.8 docs

**Screenshots**
There are currently no 2.8 docs live on the website - 
<img width="327" alt="2023-10-03_13-15-30" src="https://github.com/rancher/dashboard/assets/89212856/0c7f6122-db28-42bd-8c30-f196bb906e17">

**Additional context**

**Comment by richard-cox** [comment]
We need to clear this up with the docs team, or product. Looks like they have a redirect from the support page to the support matrix, which isn't great. We'll triage this and probably send it on to another repo

**Comment by gaktive** [comment]
Docs do have versioned links (up to /v2.7 right now, but will add /v2.8 this week).
They would like to see if the UI can use the current domain (https://ranchermanager.docs.rancher.com/) instead of the old one (https://rancher.com/docs/rancher/) so we don't need to add redirects

**Comment by gaktive** [comment]
When 2.8 is live:
- an unversioned link (latest) representing 2.8: https://ranchermanager.docs.rancher.com/
- a versioned link for the 2.8 docs set: https://ranchermanager.docs.rancher.com/v2.8
- a versioned link for the 2.7 docs set: https://ranchermanager.docs.rancher.com/v2.7

**Comment by richard-cox** [comment]
This isn't about docs versioning (title is misleading).

This is about a non-versioned link (https://rancher.com/support-maintenance-terms) to help guide users to how they can learn more about rancher support. Docs side that's incorrectly linking to the support matrix page. 

We need to find out from docs where we should link to, and update the link in the dashboard

**Comment by gaktive** [comment]
Upon chatting with docs, I'll check with product.

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/issues/9854 will take care of the docs URL request so this ticket will again focus on getting the right link for commercial support.

**Comment by gaktive** [comment]
And versioning is now https://github.com/rancher/dashboard/issues/9855 -- sorry for any confusion as all the docs issues are now coming in.
Product looking into the commercial support issue.

**Comment by richard-cox** [comment]
@gaktive Did you mention you reached out to product to understand what the link for suse rancher support should be?

**Comment by momesgin** [comment]
The logic for generating the support link takes into account dev builds, including alpha versions. If your Rancher version is a dev build, the support url will be `https://rancher.com/support-maintenance-terms` that always redirects you to the latest version which at this time is 2.7.6. So I think we don't need to fix anything here because once the docs page for 2.8.0 is created, the user will be redirected to that page.

**Comment by richard-cox** [comment]
@momesgin `support-maintenance-terms` redirects to a page it shouldn't. This is NOT a versioning issue. https://github.com/rancher/dashboard/issues/9839#issuecomment-1747110462

**Comment by CamrynCarter** [comment]
@ronhorton @gaktive The [Find out more about SUSE Rancher Support](https://rancher.com/support-maintenance-terms) link should instead be directing to https://www.rancher.com/support

**Comment by ronhorton** [comment]
**Pass** verified on rancher `v2.8-01127d844339ea8ab498f334121e2956be610409-head`

1. logged in to rancher 
2. clicked 'commercial support' link under 'Links' on right side of page
3. clicked 'find out more...' link under `Get Support`
4. link led to rancher.com/support

![2023-10-09_18-43-54.png](https://zube.io/files/rancher/b4bdcf33a8055133076e611312bb73f1-2023-10-09_18-43-54.png)
![2023-10-09_18-43-17.png](https://zube.io/files/rancher/0e885d498b67809b1d6ce1386c1a35b8-2023-10-09_18-43-17.png)
