### ISSUE TITLE
[BUG] Editing a ConfigMap with `\n` or `\t` in the data field via `edit Config` results in `a line break is expected` error in the UI

### ISSUE THREAD

**Issue by altulek** [rancher/dashboard#9841]
**Rancher Server Setup**
- Rancher version: 2.7.6
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: 1.25.10
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom

**Describe the bug**
ConfigMap edit doesn't work properly when you are using "\t" (tabulator) character.

**To Reproduce**

1. Create new config map
2. key: a, value: a
a	b 	c  <- with tab instead of space
3. key: b, value:a
a	b 	c  <- with tab instead of space
4. save

**Result**
Error: "a line break is expected"
**Expected Result**
Saved properly

**Screenshots**

![Zrzut ekranu 2023-10-03 142028](https://github.com/rancher/rancher/assets/83636764/2493fe4a-c400-493d-8a75-6d4e732f1779)

![Zrzut ekranu 2023-10-03 142003](https://github.com/rancher/rancher/assets/83636764/4201f724-d7b6-4b4d-bfaf-2db6c34ce13f)

**Additional context**
The issue happens when values are saved as string. Rancher adds additional key into first data section.

**Comment by altulek** [comment]
Caused by #7670. Same as in [[BUG] configmap formatting breaking on creation/edit #42288](https://github.com/rancher/rancher/issues/42288) It seems that [https://github.com/nodeca/js-yaml](js-yaml) doesen't work properly.

**Comment by gaktive** [comment]
Internal reference: SURE-7246

**Comment by hhstu** [comment]
> 内部参考：SURE-7246

can we get any help? @gaktive

**Comment by mohag** [comment]
Also see rancher/rancher#43118

**Comment by richard-cox** [comment]
https://github.com/rancher/dashboard/issues/10067 should be tackled at the same time as this. If it's the same issue can be closed as a duplicate

**Comment by nwmac** [comment]
@rak-phillip Is it possible to write automated tests for this?

**Comment by rak-phillip** [comment]
@nwmac Of course we can! We wrote tests in both #10179 & #10178 that address this area of dashboard. Are there  any specific cases that we would like to see represented here?

**Comment by nwmac** [comment]
@rak-phillip I'm just looking for tests that test the changes in the PR for this issue - it looks like https://github.com/rancher/dashboard/pull/10168/files# has a unit test - if that is sufficient, then we should move this to `QA Review`, rather than `To Test`.

**Comment by rak-phillip** [comment]
@nwmac I've moved to `QA Review`. I think that the test covers in such a way we'll prevent regressions of this type in the future. Behavior should remain unchanged otherwise.

**Comment by izaac** [comment]
Manual validation would complement any automation coverage before closing, let's move to `To Test` @yonasberhe23

**Comment by gaktive** [comment]
Since this was tested in 2.7.next1 & 2.8.next1 and marked done, I'll defer to QA whether this needs to be retested or if automation was in fact built up in the other tix.

**Comment by aalves08** [comment]
@gaktive @nwmac can SURE-7246 be closed in light of this issue status?

**Comment by LaoZhang-best** [comment]
this issue closed in 2.7.11, 2.7.12, but this version is non public

**Comment by richard-cox** [comment]
@LaoZhang-best This specific issue is for 2.9.0 which is the next minor release. It looks like it was also shipped in 2.8.3 which is the current minor release and is available to the community. Patch versions of a previous minor release (2.7) are for rancher prime customers and we would recommend community uses upgrade to the current minor release (2.8)
