### ISSUE TITLE
Update docs links to /v2.8 for that UI version

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9855]
@btat and the docs team are updating the web server with a new directory for the 2.8 doc structure. For our 2.8.x version, we should update our docs references.

Our dashboard docs links still point to `/v2.7/` so once the new structure will be `/v2.8/`. The tricky part is we should only add this once the links are live and working.

Note that 2.7.x releases should still point to that version.

**Comment by gaktive** [comment]
Putting in Backend Blocked until docs has the directory in place.

**Comment by gaktive** [comment]
Links are now live so this is unblocked.

**Comment by ronhorton** [comment]
**Pass** verified:
rancher `v2.8.0-rc3 Docs link directs user to v2.8 documentation` https://ranchermanager.docs.rancher.com/v2.8
rancher `v2.7.9 Docs link directs user to v2.7 documentation` https://rancher.com/docs/rancher/v2.7/en
