### ISSUE TITLE
Warning message for Istio installation

### ISSUE THREAD

**Issue by nicholasSUSE** [rancher/dashboard#9856]
The @rancher/mapps team has updated the Istio chart to version 1.19 and also its default authentication strategy. 

This is a different user experience from before. 

Please include the following warning:
"
The default authentication strategy for Kiali has changed from anonymous to token from **103.2.0+up1.19.0**. 
You can always edit it in the Helm values Yaml file `Kiali.auth.strategy` while installing or upgrading the chart. 
More information on: https://kiali.io/docs/configuration/authentication/
"

This is the page it should be included:

![image](https://github.com/rancher/dashboard/assets/127259813/962ad61e-5108-4258-8867-4405a8f8a891)

**Comment by richard-cox** [comment]
@nicholasSUSE This should be information included in the affected version's rancher readme (not sure on branches, but this one https://github.com/rancher/charts/blob/dev-v2.8/charts/rancher-istio/103.2.0%2Bup1.19.0/app-readme.md.

**Comment by richard-cox** [comment]
Setting this as backing blocked until we have a resolotion

**Comment by nicholasSUSE** [comment]
> @nicholasSUSE This should be information included in the affected version's rancher readme (not sure on branches, but this one https://github.com/rancher/charts/blob/dev-v2.8/charts/rancher-istio/103.2.0%2Bup1.19.0/app-readme.md.

Hello @richard-cox , we are adding to the `app-readme.md` as well but some sort of pop-up or warning would be a much better experience to the user since people updating Istio will rarely take a look at the README file.

**Comment by gaktive** [comment]
@nicholasSUSE we're running tight to the timeline for 2.8.0 as backend hits code freeze. This means late feature requests like this are at risk since we need QA time to test and this wasn't anticipated during planning.

**Comment by gaktive** [comment]
Upon discussion, this is better managed in the Readme since if there are subsequent updates to the chart, UI would have to then have to update the warning banner. 

As long as the chart Readme has the appropriate warning bolded enough in Markdown, this should be sufficient to warn users.
