### ISSUE TITLE
Azure RKE2 hardcoded default region is not available in the Azure Gov environment

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9858]
As this is RKE2 the relevant code is in rancher/dashboard. In rke2 the region options are not hardcoded, they're fetched from `/v1/meta/aksLocations` ...assuming the list we get from that request is accurate when using azure gov credentials, the ui fix would require us to update the hardcoded default region [here](https://github.com/rancher/dashboard/blob/master/shell/machine-config/azure.vue#L95) and hardcoded default node pool configuration [here](https://github.com/rancher/dashboard/blob/master/shell/machine-config/azure.vue#L37) to use a location returned from the api call [here](https://github.com/rancher/dashboard/blob/master/shell/machine-config/azure.vue#L159)

_Originally posted by @mantis-toboggan-md in https://github.com/rancher/rancher/issues/43024#issuecomment-1747274142_

**Comment by gaktive** [comment]
Internal reference: SURE-5437
Blocks https://github.com/rancher/aks-operator/issues/98

**Comment by mantis-toboggan-md** [comment]
We should use azure gov credentials to verify but this looks to be fixed by https://github.com/rancher/dashboard/pull/10083, repro steps for that PR use azure china but the underlying issue is the same: the default hardcoded region isn't available with those credentials.

**Comment by mantis-toboggan-md** [comment]
I confirmed that this is covered by https://github.com/rancher/dashboard/pull/10083.

**Comment by aalves08** [comment]
Added possible `automation-candidate` IF we can mock the requests needed in order to load the machine-config for an Azure RKE2 cluster and check if default region is set. We might need to mock "cloud creds" reply, if possible. To be evaluated

**Comment by izaac** [comment]
@yonasberhe23 I believe only US citizens would be able to do this? cc @yonasberhe23 @gaktive

**Comment by mantis-toboggan-md** [comment]
That's right @izaac  - to work on this one I borrowed temporary credentials from Rancher Government team

**Comment by gaktive** [comment]
Looking over the related backend ticket, part of this was already tested by someone with the appropriate access: https://github.com/rancher/rancher/issues/43024#issuecomment-1997789020 so UI QA could try talking with @atoy3731 for help but this likely could be marked as done.

**Comment by IsaSih** [comment]
@atoy3731 confirmed offline that he tested this issue, so closing as complete
