### ISSUE TITLE
Repos - support Git repos

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#986]
`rancher/rancher:master-3426-head`

The UI needs to be updated to support adding repos with git URL and branch.

the backend is already in. see  `…/v1/schemas/catalog.cattle.io.v1.repo.spec` for details.

**Comment by deniseschannon** [comment]
Looks available:
![Screen Shot 2020-08-18 at 1.54.57 PM.png](https://zube.io/files/rancher/c28ade1819a936b8dc5e6d3c0327afa1-screen-shot-2020-08-18-at-1-54-57-pm.png)

**Comment by jiaqiluo** [comment]
Validated on master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head

we can add Git Repos now either as Form or as Yaml 
and the apps show in the list 

 
<img width="1142" alt="Screen Shot 2020-08-18 at 4 32 31 PM" src="https://user-images.githubusercontent.com/6218999/90576009-bb690f00-e171-11ea-95f4-e842feb45870.png">

<img width="619" alt="Screen Shot 2020-08-18 at 4 34 15 PM" src="https://user-images.githubusercontent.com/6218999/90575989-a8563f00-e171-11ea-9695-4b8ebaf705b1.png">
