### ISSUE TITLE
[BUG] User-base users cannot use secrets in Rancher 2.7.5+

### ISSUE THREAD

**Issue by gnoling** [rancher/dashboard#9863]
**Rancher Server Setup**
- Rancher version: 2.7.5 or newer
- Installation option (Docker install/Helm Chart):
   - Helm chart, RKE2; Both brand new latest installs and upgraded older versions.

**Information about the Cluster**
- Kubernetes version: 1.24.x
- Cluster Type (Local/Downstream):
   - Doesn't matter

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Custom users created with "user-base" global permissions. Standard users are not effected.

**Describe the bug**
In Rancher 2.7.5, users that are created with user-base global permissions (standard users can still use secrets) are no longer able to use secrets. Users like this can use secrets fine in 2.6.x.

**To Reproduce**
- Create user with "user-base" global permissions; Nothing else customized. Starting with standard user level seems to create users that can still use secrets.
- Explore any cluster (any will work, local or downstream), go to Cluster => Projects/Namespaces
- Create a project
- Add the new user, any project permissions that "should" work for this (Owner, Member, or Custom)
- Create a registry secret
- Log out and back in as the new user
   - Create another registry secret if you want to
- Go to the cluster in question and try to create something using the registry secret, such as a deployment or pod
- No secrets will be available under Pull Secrets
- Secrets WILL be available under Storage => Secrets

It doesn't matter who creates the secret, which is why I suggested making them under both admin and the created user in question.

This seems like a bug since users can create and manage secrets fine under Storage > Secrets, but are unable to actually use them, and did work fine in older versions of rancher as expected.

**Result**
Limited users given permission to use secrets cannot use them.

**Expected Result**
Limited users given permission to use secrets should be able to use them.

**Additional context**
This bug was already confirmed by SUSE, and this was opened to track it.

**Comment by gaktive** [comment]
Per https://github.com/rancher/team-13/issues/3#issuecomment-1743553281, backend points to UI for the issue. Quoting @tomleb:

> It seems to be a UI bug but hard to tell.. I do see that as the test user, I am able to list the secrets by accessing /v1/secrets. However I'm seeing the more weird behavior where the admin itself isn't able to use secrets.

> More details: 

> As admin, I can't do the following (which I believe I should be able to do) for Pod/Deployment/StatefulSet/DaemonSet/CronJob and Job:

- Use a Secret for imagePullSecrets (mentioned in the JIRA ticket)
- Add a volume from a Secret
- Add a volume from a ConfigMap

Workaround

> There are a couple of workarounds (EDIT: which work for both admin and test user)

1. From the UI, when creating a resource (or editing), it is possible to fill the form and then click on Edit as YAML. This will bring the user to a YAML editor. From there, they can manually add the imagePullSecrets to the YAML. (Note that this doesn't work well for Pods, there seems to be another issue specific to pods here..)
2. Use kubectl directly to create resources with the imagePullSecrets.

**Comment by gaktive** [comment]
Internal reference: SURE-6757

**Comment by Priyashetty17** [comment]
I was able to recreate the issue with **2.7.9** and **User-Base** user. 
Validated the fix with `v2.8-1f6bae66d73aed3f214c48f895cac06cb6b9a322-head` and Dashboard: `release-2.8.0 a387f685b`

Following scenario was run with multiples users created as User-Base, standard user, admin and restricted admin. Each user was assigned the following roles:
- Project Member
- Project Owner
- Cluster Owner

### Test steps:
- As admin, create a user with user-base
- Create a project and add a namespace
- Create a registry secret in the new namespace
- Give the new user member access to the project
- Login as the new user 
- Create the following workloads in the namespace:
  - CronJob
  - DaemonSet
  - Deployment
  - Job
  - StatefulSet
  - Pod
- For each workload, I verified the 'Pull Secrets' dropdown in the Image section to ensure that the created secret appeared in the list. I also confirmed that the secret was displayed in the dropdown for the Secret in the "Environment Variables" section.
