### ISSUE TITLE
GitRepo detail view displays incorrect number of bundles

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#9866]
To repo:
1. Create a non-empty gitrepo named `test`
2. Create another non-empty gitrepo `test-abc`
3. Go to the detail view for the first repo - # of bundles is wrong

Found while investigating SURE-6692

**Comment by aalves08** [comment]
Added "automation-candidate" based on the same comment as https://github.com/rancher/dashboard/issues/9791

**Comment by yonasberhe23** [comment]
e2e tests are sufficient. moving to done cc: @izaac

**Comment by mantis-toboggan-md** [comment]
Reopening this for manual testing as fleet e2e tests need to be re-done

**Comment by IsaSih** [comment]
Tests pass on v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head
