### ISSUE TITLE
Refactor remaining tabs from rke2.vue into separate tabs

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#9869]
**Is your feature request related to a problem? Please describe.**

Refactor "Add on config", "Advanced", "Etcd", "Networking", "Registries", "Upgrade" tab into separate components.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by richard-cox** [comment]
Note for QA - This affects create/edit of RKE2 clusters for all providers

![image](https://github.com/rancher/dashboard/assets/18697775/52f4f29b-f674-4e6f-ab2c-9771728cc98d)

**Comment by izaac** [comment]
This is validated on Rancher v2.8.5 includeing: `"Add on config", "Advanced", "Etcd", "Networking", "Registries", "Upgrade"`
The pass on v2.8.5 helps identify possible regressions on the following:

- There's still a pending quick pass left on v2.9-head after a [backend fix](https://github.com/rancher/rancher/issues/46160).

**Comment by izaac** [comment]
This area is also covered by automation in the cluster manager specs.
Manual validation was done too on `v2.9-637346f76ea2bb71a82ea6e00a2779f61610a2a4-head` 
Pass.
