### ISSUE TITLE
Want to join your develop team

### ISSUE THREAD

**Issue by PmcFizz** [rancher/dashboard#987]
Hi , I'm PmcFizz, I want to join in your team to develop dashboard. I write code with Vue three years. and be good at Component development. and I see you hava many issues to close and lot of thing to do, maybe I can help. waiting for your reply.

**Comment by deniseschannon** [comment]
@PmcFizz We are an open source project. If you are interesting in helping and want to be directed to specific issues to help close, we can try to direct you, but otherwise, take a look and see if there's anything that interests you in helping with. I'm going to close this issue.
