### ISSUE TITLE
Kubectl Explain Not Present for Global Roles

### ISSUE THREAD

**Issue by brudnak** [rancher/dashboard#9871]
# Setup

| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version starting         | v2.8-fc12e7d779577d10ded1a8e249f51727848b878e-head                                 |
| Rancher version upgraded         | not applicable / `fresh install`                                                   |
| Rancher commit link              | https://github.com/rancher/rancher/commit/fc12e7d779577d10ded1a8e249f51727848b878e |
| Installation option              | Docker                                                                             |
| Cert Details                     | `--acme-domain`                                                                    |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin                                                                              |
| Browser type                     | Firefox Developer Edition                                                          |
| Browser version                  | 119.0b5 (64-bit)                                                                   |
| Dashboard                        | master 702c54e96                                                                   |
| Webhook version                  | rancher-webhook:v0.4.0-rc10                                                        |
| Rancher env setup via            | https://github.com/brudnak/linode-docker-cattle                                    |

# Describe the bug

Don't see any UI elements for kubectl explain for Global Roles.

# To Reproduce

1. Start Rancher on v2.8-head
2. While logged in as admin, navigate to`Users & Authentication` >>> `Role Templates` >>> `Global`
3. Able to `Edit Configs` at this page
4. Able to `Edit YAML` here

# Result

There is no UI element apparent here to get the kubectl explain for global roles.

# Expected Result

For there to be some UI element that gives the kubectl explain info for global roles.

Especially since these two points should qualify for kubectl explain to be present for global roles.

https://github.com/rancher/dashboard/issues/9107#issuecomment-1652098717

>This API Docs link would appear in 2 places:
>any modal with a YAML editor
>any page where someone could modify the config

**Comment by nwmac** [comment]
@brudnak This seems to cover the same as the re-opening of https://github.com/rancher/dashboard/issues/9107

Can you either close this, or close the other one.

Thanks.
