### ISSUE TITLE
An error occurred when daemonset modified Scaling and Upgrade Policy

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#9874]
**Setup**
- Rancher version: v2.7.8
- Rancher UI Extensions:
- Browser type & version: chrome 117.0.5938.149

**Describe the bug**

An error occurred when daemonset modified Scaling and Upgrade Policy
**To Reproduce**

1. Navigate to daemonset and modify Scaling and Upgrade Policy to `On Delete`
2. Save

**Result**
Unable to save with error message：
```
DaemonSet.apps "demo" is invalid: spec.updateStrategy: Unsupported value: apps.DaemonSetUpdateStrategy{Type:"Delete", RollingUpdate:(*apps.RollingUpdateDaemonSet)(nil)}: supported values: "RollingUpdate", "OnDelete"
```

**Expected Result**

**Screenshots**

<img width="1792" alt="image" src="https://github.com/rancher/dashboard/assets/19684717/626c1c33-3a8b-413d-9a6c-b754b0027222">

**Additional context**

**Comment by aalves08** [comment]
Based on https://github.com/rancher/dashboard/blob/master/cypress/e2e/blueprints/nav/fake-cluster.ts, if the `Daemonsets` are browsable, we might be able to test this on an e2e. Possible `automation-candidate`

**Comment by aalves08** [comment]
@yonasberhe23 @IsaSih @izaac added an e2e test for this issue https://github.com/rancher/dashboard/pull/10872. it's merged

**Comment by izaac** [comment]
Let's use the current provision capabilities. RKE2 clusters can be provisioned using AWS and Azure using the framework now. Keeping open.

**Comment by izaac** [comment]
Moving to done. E2E looks good.
