### ISSUE TITLE
App bar should overlap the side navigation for a neater appearance

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#9882]
Setup

Rancher version: 2.8-head 01127d8
Browser type & version: Chrome

**Describe the bug**
When we click on the app bar, it overlaps the side navigation but not entirely. If the app bar covers the side nave it provides a neater appearance

**To Reproduce**
1. Install rancher server on v2.8-head
2. Navigate to local cluster explorer
3. Click on app bar

**Result**
App bar does not cover side navigation entirely, if covered entirely it looks neater.

**Screenshots**
<img width="393" alt="2023-10-10_16-11-52" src="https://github.com/rancher/dashboard/assets/38144301/65f0c3e8-d307-45c1-9e05-eaafda3336d9">

**Comment by aalves08** [comment]
@kwwii @edenhernandez-suse any inputs/comments? Thanks 🙏

**Comment by gaktive** [comment]
Bumping out to Q1 for consideration.

**Comment by edenhernandez-suse** [comment]
There is a series of refinement changes here: https://github.com/rancher/dashboard/issues/9780 

This issue won't be applicable since the visual appearance in general will be different.

**Comment by gaktive** [comment]
Closed as a duplicate. As of writing, #9780 is in To Test for 2.9.0
