### ISSUE TITLE
NeuVector UI changes to toggle the display to its own extension

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9889]
@nwmac has the details but for NeuVector, work is being done on an extension to show an enhanced UI for NV. However, we have a few hardcoded references to NV that we need to toggle depending on whether the extension is present or not.

If the NeuVector extension is not installed, then we can show the existing NV options, though maybe they can be modified to take the existing helm chart and push towards the extension as a non-community version.

However, if a user has the NV extension installed, we should not be showing the current NV material; we can point to the extension UI. This may have to handle a "NV of NV" scenario though the design is under discussion per the roadmap (along with project filters & multiclusters).

**Comment by nwmac** [comment]
I think this might work as is - need to validate.
