### ISSUE TITLE
Visual bug on the node pool view "Unknown - no location"

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9892]
Internal reference: SURE-7049
Reported in 2.7.6

Beneath the title of the pool (Cluster Management -> Click on one of the clusters), there is a grey subtitle that contains the following: Unknown – No Location / No Size ($RESOURCE_POOL_NAME). 

This is confusing for users about the relevance, which looks to be tied to broken metrics in that the correct location isn't being shown.

Screenshot available upon request.

**Comment by nwmac** [comment]
For Harvester clusters, we should remove this extra pool info or figure out if we can get some useful information to show.

This data should come from the model - so should be a case of updating that

**Comment by gaktive** [comment]
Asked for more details from support about how the cluster was imported and the user permissions but this appears connected to #9804

**Comment by IsaSih** [comment]
Validated with @noahgildersleeve. No "Unknown – No Location" subtitles found 

![Image](https://github.com/user-attachments/assets/8529ac08-fb8d-4a14-9595-41e3fdf30d6b)

![Image](https://github.com/user-attachments/assets/c9316052-bc80-491d-8e00-9d7f5a01d74f)
