### ISSUE TITLE
API keys are not displayed in tabular form anymore 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#9895]
Setup

Rancher version: 2.8-head `6376016 `
Browser type & version: Chrome

**Is your feature request related to a problem? Please describe.**
The Accounts & API Keys page currently lacks a tabular format for displaying access tokens, secret tokens, and bearer tokens. These tokens are highlighted when selected. Presenting these tokens in a tabular format similar to the 2.7.8 version would improve clarity and enhance the user experience.

**Describe the solution you'd like**
Having the API tokens presented in a tabular format, as seen in v2.7.8 versions, enhances the overall visual organization and appearance.

**Describe alternatives you've considered**
Highlighting the tokens continuously, not just when they are selected, could further enhance the user experience.

**Screenshots**
v2.8-head -version

<img width="600" alt="2023-10-11_08-10-49" src="https://github.com/rancher/dashboard/assets/38144301/4b39532c-cff5-430b-8bd1-e04022f91a97">

On v27.8 versions:
<img width="600" alt="2023-10-11_08-10-14" src="https://github.com/rancher/dashboard/assets/38144301/e175845e-d1bf-49ee-a86f-81998bac0160">

**Comment by aalves08** [comment]
Hello @anupama2501 . These changes were introduced as fixes for https://github.com/rancher/dashboard/issues/9320 and https://github.com/rancher/dashboard/issues/9321, where we fixed contrast issues in annotations and the YAML editor for light and dark themes.

Those affected the UI elements present on the page you mentioned.

This is an UX decision as we weren't happy with the contrast levels for light and dark themes.

Maybe @kwwii can provide more input here.

Thanks 🙏

**Comment by aalves08** [comment]
@edenhernandez-suse

**Comment by kwwii** [comment]
We improved the usability by moving the copy action directly next to that which is copied. The hierarchical order of the information has not been changed in any way which negatively effects the usability.

**Comment by gaktive** [comment]
This should be addressed by reverting #9835

**Comment by anupama2501** [comment]
Verified on v2.8-head `6376016`

API keys are seen in a hierarchical order. 
<img width="1171" alt="2023-10-12_14-02-58" src="https://github.com/rancher/dashboard/assets/38144301/1010bc64-c66f-4db6-b8e5-054a862824fa">
