### ISSUE TITLE
Link has wrong version number "Learn what's new in 2.7"

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9901]
We need to update the text to be 2.8:

![image](https://github.com/rancher/dashboard/assets/1955897/36cd6bb4-c84e-4e32-ac38-42dd2ce4eca0)

**Comment by yonasberhe23** [comment]
I've updated existing UI test to cover this scenario https://github.com/rancher/dashboard/pull/9908

**Comment by cnotv** [comment]
@nwmac was this not one of the version dependent changes which require manual work?

**Comment by susesgartner** [comment]
Ticket #9901 - Test Results - PASS ✅ 
---
 
 Validated on v2.8-head:
 1. Create a rancher instance
 2. Validate that "what is new in 2.8" is displayed properly in the home screen
 
Results: The correct message was displayed.
