### ISSUE TITLE
Embeded (IFramed) Ember pages are positioned incorrectly

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9904]
With the new sidebar, for an embedded iframe page, the page overlaps the side nav slightly - see below:

![image](https://github.com/rancher/dashboard/assets/1955897/10a7afec-37a0-46d6-95a7-31789478173a)

The vertical grey divider line for the side nav is hidden as the IFRAME overlaps is - I suspect the IFRAME component needs updating to reflect the new sizing of the app bar and side nav.

The example shown requires the Legacy feature flag to be enabled, then click on the 'Global Configuration' icon in the app bar.

**Comment by anupama2501** [comment]
Verified on v2.8-head `6cd32b9`

1. Created a rancher server on v2.8-head
2. Enabled the legacy feature flag
3. Verified the embedded pages and side navigations are not overlapping 
<img width="500" alt="2023-10-17_15-09-59" src="https://github.com/rancher/dashboard/assets/38144301/dd8ce42f-bdcf-4653-9b14-ef075d61784b">

Verified in dark mode and light mode on both chrome and firefox browsers.
Verified the legacy tab in the cluster explorer is not overlapped too.
