### ISSUE TITLE
Can not disable/enable Project Network Isolation from UI for EKS clusters

### ISSUE THREAD

**Issue by kkaempf** [rancher/dashboard#9905]
### Issue description:
Project Network Isolation can be selected at cluster creation, once set cannot be changed through UI.
Edit config where you can tick/untick the box and click save but changes do not stick.
Same for imported clusters.

### Business impact:
Users needs to disable that as its impacting their webhooks mainly Hierarchical Namespace Controller (HNC) when we add the namespace to a project a network policy is created and webhook misbehave

### Repro steps:

Provision EKS cluster, choosing PNI enabled (or not)
Go back to edit the config once cluster is up and disable (or enable) PNI, then save
*Go back to see chance has not taken hold.

### Workaround:
If you want to workaround this problem, you can do it from the rancherserver CLI, 

`kubectl edit cluster.management.cattle.io/<cluster-id>`

and in the spec section set enableNetworkPolicy to true/false and save it. The 'hn' network policies for PNI were then added/deleted respectively... 

Moreover I am interested in support scope of this operation because there is nothing mentioned in the EKS reference documentation about this... https://ranchermanager.docs.rancher.com/v2.7/reference-guides/cluster-configuration/rancher-server-configuration/eks-cluster-configuration

### Actual behaviour:
PNI setting cannot be changed once set.

### Expected behaviour:
Expect ability to change setting through UI.

**Comment by codyrancher** [comment]
@kkaempf @mjura as Neil mentioned this was done intentionally to address https://github.com/rancher/dashboard/issues/4454. I see that there's workarounds but the workarounds seem to go around the rancher backend. Do either of you know if there's been a change to the backend? Do you know who I could talk to about it?

**Comment by nwmac** [comment]
ping @kkaempf @mjura - could you help Cody out (see above), so we can action this issue. Thanks.

**Comment by gaktive** [comment]
This should be unblocked now. @codyrancher can you look this over based on the most recent comment?

**Comment by codyrancher** [comment]
@mjura I've put together a PR to address your comment https://github.com/rancher/ui/pull/5119.

I reread the original SURE-6638 issue and it sounds like EKS and possibly GKE were also affected. The UI doesn't disable the checkbox for those other providers. By any chance was the issue for EKS and GKE that even if the user unchecked `Project Network Isolation` the `enableNetworkPolicy ` configuration wasn't changed?

**Comment by mjura** [comment]
@codyrancher thank you Cody, it looks great, so we are good

**Comment by IsaSih** [comment]
Issue #11199 blocks testing.

**Comment by yonasberhe23** [comment]
@IsaSih you should be unblocked now. moving to To Test

**Comment by IsaSih** [comment]
Tried to edit the cluster after creating EKS cluster, but blocked by https://github.com/rancher/dashboard/issues/11438

**Comment by IsaSih** [comment]
Reopening issue, because after creating the EKS cluster with Project Isolation selected via UI, when I edit the config via UI, this parameter is unselected

https://github.com/user-attachments/assets/03df3778-e73d-4efc-aa53-024362bdead1

**Comment by thehejik** [comment]
**Test report**

Successfully validated on rancher `v2.9-637346f76ea2bb71a82ea6e00a2779f61610a2a4-head` with dashboard `master ddd2dee`

EKS 1.29 provisioned with the PNI flag enabled.
![pasted_image009](https://github.com/user-attachments/assets/f2e1b80a-9b74-4d80-94b4-16588a89758b)

After provisioning I could disable the flag via `Edit Config` and on a new attempt to `Edit Config` I could see the flag remained disabled:
![pasted_image010](https://github.com/user-attachments/assets/8c981198-adc4-4cc2-9aae-129b076f7f7d)

Also I could re-enable the flag state afterwards. 

Closing as done.
