### ISSUE TITLE
RKE2/K3sClusters created via rancher test framework cannot be viewed/edited using `Config` option `this.spec.rkeConfig.... undefined`

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#9906]
**Setup**
- Rancher version: v2.7.7
- Rancher UI Extensions: n/a
- Browser type & version:tested with chrome and firefox

**Describe the bug**

when deploying clusters using [rancher's test framework](https://github.com/rancher/rancher/tree/release/v2.8/tests) we get an error in the UI when viewing the cluster via the 'config' option, or when trying to edit the cluster via config. 

**To Reproduce**

deploy any cluster using the test framework
in rancher, view or edit the created cluster's config

**Result**
UI error displayed to user related to the spec being undefined. Example: 
```
this.spec.rkeConfig.machineSelectorConfig.find(...) is undefined 
```

**Expected Result**

I would expect to be able to view clusters created like this in the UI

**Screenshots**

![image](https://github.com/rancher/dashboard/assets/16691014/dc7c0a6a-e87c-40fe-a7dc-c90768c45afc)

**Additional context**

QA can spin up a cluster if the team needs more context upon request
this does not happen for rke1 clusters that are created via the rancher test framework

**Comment by jakefhyde** [comment]
I have also encountered this issue when enabling the out of tree aws cloud provider. The out of tree provider requires setting `cloud-provider=external` per component using an appropriate machineLabelSelector, so in my configuration there are no empty machineLabelSelectors.

**Comment by nwmac** [comment]
@torchiaf I think your kubelet args fixes may have also fixed this?

**Comment by jakefhyde** [comment]
@nwmac I can confirm I'm not seeing this behavior anymore on `rancher/rancher:v2.8-4716667b53c4b76e82fe34207899da46470c5e0d-head`.

**Comment by torchiaf** [comment]
@nwmac @jakefhyde https://github.com/rancher/dashboard/pull/10186 resolved the missing rke2 configs issue.
