### ISSUE TITLE
RKE2: Cannot Scale up node pool after scaling nodepool to 0 nodes

### ISSUE THREAD

**Issue by susesgartner** [rancher/dashboard#9909]
**Setup**
- Rancher version: v2.8-head
- Browser type & version: Chrome 117.0.5938.132

**Describe the bug**
When scaling a node pool to 0 nodes in a nodepool the UI option for scaling the nodepool up goes away and you can no longer add nodes to the cluster in that nodepool

**To Reproduce**
1. Create a AWS RKE2 cluster using k8s 1.27 and the following nodepool setup
pool1: 3 node all roles
pool2: 2 cp nodes
2. Scale down pool2 to 0 nodes
3. Attempt to scale pool2 back up.

**Result**
The option to scale up in the UI disappears 

**Expected Result**
Node pool should be able to be scaled back up.

**Screenshots**
<img width="1039" alt="image" src="https://github.com/rancher/dashboard/assets/136753565/b557870e-3171-444c-854f-88d49a67982b">

Additional context: 
I was able to edit the cluster and add 2 nodes to the nodepool and they provisioned successfully. This makes it seem that this is only a UI issue as the backend can provision properly.
This behavior seems to be specific of RKE2, I tried to reproduce this on RKE1 but was unable to.

**Comment by gaktive** [comment]
Need to see if we can repro this on Digital Ocean then look at what the behaviour is for 2.7-head. If this didn't happen in 2.7-head, it's not technically a regression but this may need to be prioritized for 2.8.0 if this did work recently.

**Comment by momesgin** [comment]
This is not a regression since I could reproduce it on 2.7.8 with RKE2 - Digital ocean - k8s 1.26
![image.png](https://zube.io/files/rancher/c8e889c4f204e9bf41e3abcc37840197-image.png)

**Comment by gaktive** [comment]
Whoever grabs this, check the git blame history to see if there was a possible scenario that this was removed for another reason.

**Comment by susesgartner** [comment]
Tested this on v2.9-head and I can scale up from 0 nodes in a pool. Everything seems to be working as intended.
