### ISSUE TITLE
Error message when installing chart isn't visible

### ISSUE THREAD

**Issue by nickwsuse** [rancher/dashboard#9917]
**Setup**
- Rancher version: v2.8.0-alpha2
- Rancher UI Extensions: N/A
- Browser type & version: Chrome Version 117.0.5938.149 (Official Build) (arm64)

**Describe the bug**
When installing the Istio chart, an error message appeared but only the very edge of the error box was visible (see screenshot)

**To Reproduce**
1. Deploy Rancher v2.8.0-alpha2
2. Go into local cluster explorer
3. Apps > Istio > Install v103.2.0+up1.19.0

**Result**
Error message isn't visible

**Expected Result**
Error message is clearly visible

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/107147272/89aec23f-56bb-4425-a1e3-68a66ea432db)

**Additional context**
The error itself was a 500 error based on the network logs.
Might be related to/fixable with https://github.com/rancher/dashboard/issues/9680

**Comment by richard-cox** [comment]
Closing https://github.com/rancher/dashboard/issues/9454 which was older, but this was the one worked on.

**Comment by nickwsuse** [comment]
`Verified on v2.8-head ID: 1efca41` ✅ 
----
The error is appearing clearly and as expected now for chart install errors.
