### ISSUE TITLE
target="_blank" doesn't work in the UI with v-clean-html

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#9920]
**Setup**
- Rancher version: Any
- Rancher UI Extensions: 2.8-head (master)
- Browser type & version: Any

**Describe the bug**

A link using `v-clean-html` and with a `target="_blank"` doesn't open in a new tab because of the `v-clean-html` directive that removes the `target` attribute.

**To Reproduce**

Add a HTML element to a Vue view like (just as an example... find another translation string with an anchor `<a>` inside:
```
<p
    v-if="role.id === 'restricted-admin'"
    v-clean-html="t('rbac.globalRoles.role.restricted-admin.deprecation', { releaseNotesUrl }, true)"
    class="deprecation-notice"
  />
```
click on it via the UI

**Result**
Doesn't open the link in a new tab

**Expected Result**

Should open the link in a new tab

**Screenshots**

**Additional context**

**Comment by aalves08** [comment]
@nwmac by merging https://github.com/rancher/dashboard/pull/10728 in regards to https://github.com/rancher/dashboard/pull/10193, we would already be covering this issue with an e2e test based on the fact that the "documentation" link on the test uses `v-clean-html`, right? https://github.com/rancher/dashboard/blob/master/shell/edit/provisioning.cattle.io.cluster/rke2.vue#L2051

If so, then we could remove the label `automation-candidate` and remove the label `QA-manual-test`

Wdyt?

**Comment by nwmac** [comment]
@aalves08 Yes, I think that is fine

**Comment by aalves08** [comment]
Based on previous comments and with the e2e test https://github.com/rancher/dashboard/pull/10728, we believe this issue doesn't need manual testing anymore. Will adjust labels and move to the correct column

**Comment by izaac** [comment]
Agreed the e2e test coverage is enough. cc @yonasberhe23
