### ISSUE TITLE
Cluster "Etcd Metrics" Chinese translation error

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#9922]
**Setup**
- Rancher version: v2.7.8
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

Switch to Chinese and access the cluster "Etcd Metrics". The Chinese translation is wrong.
in:
1. `ETCD 有一个 Leader： 是`, `是` should not be translated into Chinese
2. Since it is displayed in Chinese, it is best to separate each Metric with a comma.
3. `失败的 proposal 数量 0`, the ":" separator is missing between key and value

<img width="804" alt="image" src="https://github.com/rancher/dashboard/assets/19684717/56fdc7c1-31f0-4b2c-a9d8-5d6526d0482a">

**Comment by IsaSih** [comment]
Tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head
