### ISSUE TITLE
Switch to Chinese. The content of the `Severity` drop-down box in Alerting Rules should not be translated into Chinese.

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#9923]
**Setup**
- Rancher version: v2.7.8
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

Switch to Chinese and add Prometheusrule. The content in the `Severity` drop-down box (critica, warning, none) does not need to be in Chinese. Otherwise, after saving, view the configuration through yaml. The content of the `Severity` field is in Chinese.

<img width="1552" alt="image" src="https://github.com/rancher/dashboard/assets/19684717/50aa72f7-dfdd-4022-8531-93f7644a4ed8">

<img width="1024" alt="image" src="https://github.com/rancher/dashboard/assets/19684717/ea9fe6c7-38c2-4787-afff-75106f4c31e5">

**Comment by aalves08** [comment]
Updated QA labels since I've added an e2e test with https://github.com/rancher/dashboard/pull/10899
