### ISSUE TITLE
Add multiple Alerting Rules in PrometheusRule to always display the same value

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#9926]
**Setup**
- Rancher version: v2.7.8
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

When adding a second or more `Alerting Rules` to a `PrometheusRule`, the newly added `Alerting Rules` are the same as the first one

**To Reproduce**

1. Enable rancher monitoring, navigate to `PrometheusRule` and add multiple `Alerting Rules`
**Result**
All `Alerting Rules` are the same, and if you modify one of the `Alerting Rules`, the other forms will also take effect.

**Screenshots**

**Additional context**

![prometheus](https://github.com/rancher/dashboard/assets/19684717/6a3ef837-1a47-4208-8528-38c181b0ee56)

**Comment by nwmac** [comment]
automated e2e tests added with this PR: https://github.com/rancher/dashboard/pull/10745

**Comment by yonasberhe23** [comment]
e2e test seems sufficient to me. Moving this to Done cc: @izaac
