### ISSUE TITLE
Container logs do not render correctly

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9931]
Internal Reference: SURE-6931

Looks like lines are not being detected correctly.

Look at the logs for a container - e.g. Fleet Agent:

<img width="907" alt="image" src="https://github.com/rancher/dashboard/assets/1955897/c392e3b2-4cdd-4184-bd03-35344c33b87b">

We don't seem to be parsing out the dates for lines - in this example, we seem to miss the 2nd line, so its date is not shown on the left but appears as part of the message for the previous log line.

**Comment by nwmac** [comment]
This may be a change in the backed - the assumption in the UI is that each web socket message from the log endpoint will return a single line - it appears that multiple lines are now returned.

**Comment by IsaSih** [comment]
Tests pass in v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head

![Image](https://github.com/rancher/dashboard/assets/70187881/80e4584e-aca0-416f-88d1-3361cff0c8ca)
