### ISSUE TITLE
[Flake] Cluster Create button fails to close the form after cluster creation sometimes

### ISSUE THREAD

**Issue by valaparthvi** [rancher/dashboard#9943]
**Setup**
- Rancher version: v2.8.0-rc1
- Rancher UI Extensions: v2.8.0-rc1
- Browser type & version: Firefox 115

**Describe the bug**

While creating a cluster, clicking on the _Create_ button triggers the cluster creation but fails to close the form and returns an error as shows in the screenshot below.
**To Reproduce**

1. Go to Cluster Management > Click on _Create_ > Select any hosted provider (have not tested this bug with others)
2. Populate all the fields in the Cluster creation form and click on _Create_ button.
**Result**
The cluster gets created, but the form does not close (see the screen cast below) and returns an error as show in the screenshot.

**Expected Result**

The form should get closed.

**Screenshots**

![Screenshot from 2023-10-18 08-31-24](https://github.com/rancher/dashboard/assets/11015077/8359e6a4-cec6-4c7e-9a72-72552e48174c)
[Screencast from 10-18-2023 08:40:29 AM.webm](https://github.com/rancher/dashboard/assets/11015077/12aeb993-3af9-4ae3-a80a-4a22f8af69d2)

**Additional context**

This happens very rarely, it might be related to some issue with the way Rancher is installed because sometimes re-installing Rancher seems to make the problem go away.

**Comment by cpinjani** [comment]
See also https://github.com/rancher/dashboard/issues/9837

**Comment by valaparthvi** [comment]
Duplicate.
