### ISSUE TITLE
Remove references to pod-security-policies for RKE1

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9945]
In conjunction with Vue work in rancher/dashboard#9725, Rancher 2.8.0 is dropping support for <1.25 clusters. Therefore no cluster that supports PSP's will be supported by Rancher. We can remove any references towards it.

The UI should remove any code around PSPs, and references to following endpoints:

- /v3/podsecuritypolicytemplates
- /v3/podsecuritypolicytemplateprojectbindings
- /v1/management.cattle.io.podsecuritypolicytemplates
- /v1/management.cattle.io.podsecuritypolicytemplateprojectbindings

Or references directly towards CRDs of:

- upstream's PodSecurityPolicies
- podsecuritypolicytemplates
- podsecuritypolicytemplateprojectbindings

Additional context

Backend issue doing the same, will be blocked by this issue: https://github.com/rancher/rancher/issues/39789

**Comment by gaktive** [comment]
QA for this could be none if the backport for 2.8.next2 goes through.

**Comment by aalves08** [comment]
Validated that issue has been fixed on Rancher `v2.9-a57f7025abdd80a2912f7fe53247ef7e1d4993de-head`. Cannot find any references to PSPs both in the code and the UI. 

![Image](https://github.com/rancher/dashboard/assets/97888974/772392b2-4816-455a-8963-6822bd65b497)
![Image](https://github.com/rancher/dashboard/assets/97888974/063faa05-6861-4ba4-8bf6-45d2b08e5a59)

Moving to Done @yonasberhe23 @IsaSih @izaac
