### ISSUE TITLE
[BUG] Wrong rendering of Markdown files

### ISSUE THREAD

**Issue by recena** [rancher/dashboard#9951]
### Rancher Server Setup

- Rancher version: 2.7.6

### Information about the Cluster

N/A

### User Information

N/A

### Describe the bug

Markdown files are rendered in a wrong way in the Apps section.

### To Reproduce

- Go to Apps, click on Charts
- Select an app

### Result

A `README` file is rendered but some elements (especially tables) are wrong. The information is unreadable.

### Expected Result

- The output could be improved in terms of margins, sizes (headers, paragraphs), etc...
- Tables are rendered correctly.

### Screenshots

![screenshot1](https://github.com/rancher/rancher/assets/1021745/8bf7c731-23c3-4781-90b4-9e396e1f4e1d)

### Additional context

A good render can improve a lot the readability and user experience.

![screenshot2](https://github.com/rancher/rancher/assets/1021745/bb8e6494-5dab-4558-aa8c-2aee1227fdaf)

**Comment by rohitsakala** [comment]
I just quickly tried and the content rendered fine on my Mac machine on Chrome and Safari.

<img width="1713" alt="Screenshot 2023-10-19 at 3 07 52 PM" src="https://github.com/rancher/dashboard/assets/8402361/d8bdcc8d-5917-4dcc-9d1f-1cd05ad76899">

**Comment by recena** [comment]
@rohitsakala Thank you for you feedback. I forget to mention I use MacOSX and Firefox 118.0.2 (64-bit).

**Comment by nflondo** [comment]
@rohitsakala Is the entire README rendered correctly for you? For us the render problem starts with the "Parameters" section right after the "Uninstalling the Chart" section as you can see in this screenshot of the full page:
[tomcat-chart-full-page.pdf](https://github.com/rancher/dashboard/files/13048227/tomcat-chart-full-page.pdf)
I'm running: Rancher 2.7.6 and Chrome Version 118.0.5993.70 (Official Build) (64-bit)on linux:

**Comment by recena** [comment]
In his case, it is working because you can see how the headers are rendered properly.

**Comment by IsaSih** [comment]
Tests pass in v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head

![Image](https://github.com/rancher/dashboard/assets/70187881/597c26ee-1b87-4ea1-96c6-5bd263a75067)
