### ISSUE TITLE
`Edit/Upgrade`ing a Helm App fails to find the associated chart

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9957]
**Setup**
- Rancher version: 2.8.0 before release

**Describe the bug**
- Before a helm app is edited or upgraded the ui needs to find the associated helm chart it came from
- this mechanism is currently broken, from https://github.com/rancher/dashboard/pull/9806
- So any attempt to edit/upgrade a chart results in the user having to find the chart in a drop down

**To Reproduce**
- install any chart
- go to Apps --> Installed Apps --> < row for app that was just created> --> click action menu `Edit/Ugprade`

**Result**
![image](https://github.com/rancher/dashboard/assets/18697775/50c5763f-1ee2-4a72-9861-9cc1a4bffdab)

**Expected Result**
![image](https://github.com/rancher/dashboard/assets/18697775/4c7020e8-1034-4f15-936e-b6f10c4a02dc)

**Additional context**
Marking this as a blocker
- Although the workaround for this specific issue exists (user can select from drop down) it's confusing for the user
- It breaks the upgrade column in the apps list (guessing this uses `matchingChart`)
- It also breaks other usages of the `catalog/chart` action (https://github.com/rancher/kubewarden-ui/pull/518)
- The PR that broke these should not have been merged in this release

**Comment by cnotv** [comment]
Can we identify data wise what has been the issue? Behavior wise does not make it that clear from what we had earlier. 
Since the issue has been tested based on data for another area, it would be great to have insight about the logic if any.

**Comment by Priyashetty17** [comment]
Re-opening this issue as I still see this issue with **fleet-agent-local** chart. I don't see this issue with other charts - monitoring, cis etc. Refer the screenshot below
`Rancher version:  v2.8-c3411e0ca574b7086308bf4ef2e49984cd247dd1-head`
`Dashboard: release-2.8.0 a387f685b`
![image](https://github.com/rancher/dashboard/assets/42880103/88577434-ed21-4766-b842-8eff571e9b02)

**Comment by richard-cox** [comment]
@Priyashetty17 This is expected behaviour, there is no visible fleet chart that the user can see so the edit/upgrade flow allows the user to try to find one. I wondered if this should be a separate bug, but disabling the edit/upgrade action if we can't find a matching chart would mean other scenarios where the user can find the chart aren't possible.

**Comment by Priyashetty17** [comment]
Thanks for the clarification @richard-cox. Closing this issue based on the comment ^^.
