### ISSUE TITLE
Chart installation question groups are "None" if there is only 1 group defined

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#9959]
On kubewarden-defaults we display `(None)` tab instead of `Settings` (that is defined in questions.yaml).

![Screenshot from 2023-10-20 09-31-54](https://github.com/rancher/kubewarden-ui/assets/538604/c601710c-32e6-4a97-8a1b-55ed0f799170)

**Comment by yonasberhe23** [comment]
Automation reviewed. The test code included in the PR seems to have sufficient test automation coverage. Moving to 'Done'
