### ISSUE TITLE
[Bug] Docs link to RKE1 vs RKE2 behavior differences is incorrect

### ISSUE THREAD

**Issue by git-ival** [rancher/dashboard#9970]
**Setup**
- Rancher version: 2.8.0-rc1

**Describe the bug**

The link to the behavior differences between RKE1 and RKE2 on the cluster configuration page is incorrect.

**To Reproduce**

- Open up the cluster configuration page on an existing cluster registered to a 2.8.0-rc1 Rancher cluster.
- View the link to the documenation at the top of the page
- Click on the link and get directed to a nonexistent page in the docs

**Result**

**Expected Result**
The user should be directed to the correctl URL for the expected page.

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/85186645/ff58bc3a-bfd6-491e-8b7a-b81142ef777b)

**Additional context**
The link is as follows: https://ranchermanager.docs.rancher.com/v2.8/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/

But it should be: https://ranchermanager.docs.rancher.com/v2.8/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/rke1-vs-rke2-differences#docusaurus_skipToContent_fallback

**Comment by gaktive** [comment]
@nwmac should we sneak this in for 2.8.0?

**Comment by gaktive** [comment]
Checking with docs. cc @btat

**Comment by gaktive** [comment]
Docs added redirects for these links so this should work in 2.8.0. We may need to sweep through other links based on a change in URL paths.

**Comment by dasarinaidu** [comment]
Validated this on `v2.8-head` the links are pointing to the correct location and closing this card.

**Steps:**

1. Open up the cluster configuration page on an existing cluster registered to a `2.8-head` Rancher cluster.
2. View the link to the documentation at the top of the page
3. Click on the link and check the content and the URL pattern

**Actual:**
https://ranchermanager.docs.rancher.com/v2.8/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/rke1-vs-rke2-differences
