### ISSUE TITLE
K8s 1.29 support: replace cis-1.23 with new cis option in RKE2

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9971]
From https://github.com/rancher/rancher/issues/43110 (and @snasovich) as Kubernetes 1.28 & 1.29 bumps are on the radar:

- In 1.29, the `cis-1.23` option is scheduled to be removed in favor of `cis` in RKE2 1.29 releases per https://github.com/rancher/rke2/blob/9e79849266360b1aa27fabe0d981bcc6bc069858/pkg/rke2/rke2.go#L274

Backend is looking into impact but the UI does have this setting in place.

**Comment by gaktive** [comment]
Leaving as Backend Blocked for now until it's clear that UI can start work on this.

**Comment by gaktive** [comment]
By all apperances, k8s 1.28 doesn't require any UI so this may just be a 1.29 ticket in the end.

To watch: https://github.com/rancher/rancher/issues/43110#issuecomment-1918808001 indicates that there may be some API breakage with continued PSP usage.

**Comment by gaktive** [comment]
This will require a backport to 2.8.x once we know when the backend is ready.

**Comment by gaktive** [comment]
We'll likely have to follow a similar pattern to 1.28 for updating the appropriate dropdowns to include newer versions: https://github.com/rancher/dashboard/issues/10504 for reference.

**Comment by gaktive** [comment]
Nothing is hardcoded in the UI from analysis. And there is a deprecation warning already in place from an earlier k8s bump.

Questions that arose that will require some research:
- what is the expected behaviour for folks upgrading from versions that supported `cis-1.23`? We likely need to check for the deprecated (and soon-to-be removed) options and then provide indication that the option will go away.

**Comment by richard-cox** [comment]
The options come from `/v1-rke2-release/releases` <kube version, for example <v1.29.4+rke2r1> `agentArgs.profile.options[1]`.

![image](https://github.com/rancher/dashboard/assets/18697775/49dc5be2-80e8-467b-8647-4434147f8742)

Not quite sure where we display it thought

**Comment by mantis-toboggan-md** [comment]
This is display in the 'Basics' tab of RKE2 provisioning. We may already be checking for unsupported cis values but someone will need to verify: https://github.com/rancher/dashboard/blob/master/shell/edit/provisioning.cattle.io.cluster/tabs/Basics.vue#L213C5-L213C19

**Comment by richard-cox** [comment]
Nice work @momesgin!

@gaktive Can we transfer this to host busters?

**Comment by gaktive** [comment]
No UI changes required. Putting in To Test so that QA is aware once k8s 1.29 is done, they can verify this appears as `cis`.

**Comment by mantis-toboggan-md** [comment]
I have verified that if cis-1.23 option is removed, the UI shows a banner informing the user of the deprecation
![Screenshot 2024-07-08 at 2 03 09 PM](https://github.com/rancher/dashboard/assets/42977925/2a07f488-9a7d-4fe3-a746-9f7ee5dbf19a)
