### ISSUE TITLE
cluster.x-k8s.io.machine list page breaks if a machine doesn't have an associated provisioning cluster

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#9973]
I hit this bug after deploying the rancher turtles example repo: https://github.com/rancher-sandbox/rancher-turtles-fleet-example
In this case, there is no provisioning cluster for the machine, and the `canScaleDown` getter throws an error, preventing the table from rendering.

![Screen Shot 2023-10-24 at 10.53.38 AM.png](https://zube.io/files/rancher/c66673c9bfcb26dd1468f68888b0053e-screen-shot-2023-10-24-at-10-53-38-am.png)

**Comment by momesgin** [comment]
Since this change is extremely safe and creating the repro environment is time-consuming, I will close this ticket
