### ISSUE TITLE
[BUG]Fleet UI crash when switch language to CN

### ISSUE THREAD

**Issue by orangedeng** [rancher/dashboard#9984]
**Setup**
- Rancher version: v2.7.8
- Rancher UI Extensions: fleet
- Browser type & version: Chrome 118.0.5993.88 x86_64

**Describe the bug**
UI crash when get into git repo details page.

**To Reproduce**
1. Create a cluster, like k3s
2. Added git repo, set target cluster selector matching the new cluster. And put manifest content in repo
3. Change the preference, switch language to CN(简体中文)
4. Go back to git repos page, and click the git repo to open detail page.

**Result**
UI crash with following screenshot.

**Expected Result**
Displaying detail page.

**Screenshots**
<img width="1049" alt="ui-crash" src="https://github.com/rancher/dashboard/assets/15376837/0621a310-ca9e-45ac-9c6e-05cc60e7782a">

**Additional context**

**Comment by yonasberhe23** [comment]
e2e test coverage covers the scenarios related to this ticket and test is passing in 2.9. moving to 'Done' 
cc: @izaac
