### ISSUE TITLE
[SURE-7334] Need validation for duplicate Nodegroup names

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#9987]
Internal Reference: SURE-7334

**Setup**
Rancher version: v2.8-head
Browser: Chrome Latest

**Describe the bug**
While creating downstream cluster for hosted providers EKS/AKS/GKE, creating nodegroups is allowed with duplicate names.
There must be validation for same names on UI so cluster creation is not allowed.
See also: https://github.com/rancher/gke-operator/issues/122

**To Reproduce**
- Create downstream EKS cluster having two node groups with same name
- Create downstream AKS cluster having two node pools with same name
- Create downstream GKE cluster having two node pools with same name

**Logs**
```
time="2023-10-26T10:14:44Z" level=error msg="error syncing 'cattle-global-data/c-f8ktx': handler eks-controller: error creating nodegroup: ResourceInUseException: NodeGroup already exists with name test and cluster name cpinjani-eks\n{\n  RespMetadata: {\n    StatusCode: 409,\n    RequestID: \"3cae198b\"\n  },\n  ClusterName: \"cpinjani-eks\",\n  Message_: \"NodeGroup already exists with name test and cluster name cpinjani-eks\",\n  NodegroupName: \"test\"\n}, requeuing"

time="2023-10-26T11:06:05Z" level=error msg="error syncing 'cattle-global-data/c-rd4gt': handler aks-controller: error failed to create cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code=\"BadRequest\" Message=\"One or more agentPoolProfile name(s) were assigned the same value. Value of 'name' field must be unique for each agentPoolProfile.\" , requeuing"

time="2023-10-26T11:08:30Z" level=error msg="error syncing 'cattle-global-data/c-t5kgt': handler gke-controller: googleapi: Error 500: Internal error encountered.\nDetails:\n[\n  {\n    \"@type\": \"type.googleapis.com/google.rpc.RequestInfo\",\n    \"requestId\": \"0x4077\"\n  }\n]\n, backendError, requeuing"

```

**Comment by richard-cox** [comment]
Note - there's an [RKE2 equivalent issue](https://github.com/rancher/dashboard/issues/5211). If this is solved when hosted providers are ported, they use the same controls as rke2 and this is fixed.... then that issue can also be marked as fixed

**Comment by IsaSih** [comment]
tests pass on v2.9-16190ecee0aa3fb4aa570aa0fc932a36d9dcd082-head.
However, the behavior is different across different providers. For example, GKE allows the creation request to be sent, but the UI then shows an error. As seen in the screenshot. In EKS, the Create button is locked until the user changes the name of one of the duplicate node names, but no message is informed to the user. 
Created issue  #11208  to unify the same behavior for all providers
