### ISSUE TITLE
Rancher crashes when clicking the namespace in cluster view

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9993]
Internal reference: SURE-7048
Reported in 2.7.6

Issue description:
In Cluster Management, if you open a cluster, there is the name of the cluster as a title and below that, there is the Namespace which is "fleet-default". That is a link, and when a user clicks on that link, Rancher crashes with "Cannot read properties of undefined (reading 'id')".

Business impact:
In environments where Rancher is used to manage a Harvester cluster the link in Cluster Management crashes the UI and the user needs to re-login or use the browser to go back in history to reach UI again. The error is happening via multiple paths and negatively impacts the user experience with the product. 

Troubleshooting steps:
They were able to reproduce it 100% on multiple environments. There is no clear workaround as refresh doesn't help

Repro steps:

- In Cluster Management pick a guest cluster on Harvester
- Click "fleet-default" namespace link below the title

Workaround:
None

Actual behavior:
Clicking fleet-default link ends up in app crash/error

Expected behavior:
Clicking fleet-default link should not end up in app crash/error

![Screenshot 2023-10-06 at 16.40.36.png](https://zube.io/files/rancher/d36fcb4b83603caac721968508a5e026-screenshot-2023-10-06-at-16-40-36.png)

**Comment by izaac** [comment]
E2E coverage looks good. Moving to Done
